### ISSUE TITLE
ClientMapNearCacheTest.receives_one_clearEvent_after_mapEvictAll_call_from_member

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#10024]
```
java.lang.AssertionError: Expecting only 1 clear event expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.client.map.impl.nearcache.ClientMapNearCacheTest$29.run(ClientMapNearCacheTest.java:1053)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:967)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:984)
	at com.hazelcast.client.map.impl.nearcache.ClientMapNearCacheTest.receives_one_clearEvent_after_mapEvictAll_call_from_member(ClientMapNearCacheTest.java:1050)
```
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-freestyle/134/testReport/junit/com.hazelcast.client.map.impl.nearcache/ClientMapNearCacheTest/receives_one_clearEvent_after_mapEvictAll_call_from_member_batchInvalidationEnabled_false_/

possibly related to #9940

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: Expecting only 1 clear event expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.client.map.impl.nearcache.ClientMapNearCacheTest$29.run(ClientMapNearCacheTest.java:1053)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:967)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:984)
	at com.hazelcast.client.map.impl.nearcache.ClientMapNearCacheTest.receives_one_clearEvent_after_mapEvictAll_call_from_member(ClientMapNearCacheTest.java:1050)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-freestyle/164/testReport/junit/com.hazelcast.client.map.impl.nearcache/ClientMapNearCacheTest/receives_one_clearEvent_after_mapEvictAll_call_from_member_batchInvalidationEnabled_true_/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: Expecting only 1 clear event expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.client.map.impl.nearcache.ClientMapNearCacheTest$29.run(ClientMapNearCacheTest.java:1053)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:967)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:984)
	at com.hazelcast.client.map.impl.nearcache.ClientMapNearCacheTest.receives_one_clearEvent_after_mapEvictAll_call_from_member(ClientMapNearCacheTest.java:1050)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-ZuluJDK6-freestyle/43/testReport/junit/com.hazelcast.client.map.impl.nearcache/ClientMapNearCacheTest/receives_one_clearEvent_after_mapEvictAll_call_from_member_batchInvalidationEnabled_false_/

**Comment by hasancelik** [comment]
**maintenance**
```
java.lang.AssertionError: Expecting only 1 clear event expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.client.map.impl.nearcache.ClientMapNearCacheTest$29.run(ClientMapNearCacheTest.java:1053)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:967)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:984)
	at com.hazelcast.client.map.impl.nearcache.ClientMapNearCacheTest.receives_one_clearEvent_after_mapEvictAll_call_from_member(ClientMapNearCacheTest.java:1050)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-freestyle/61/testReport/junit/com.hazelcast.client.map.impl.nearcache/ClientMapNearCacheTest/receives_one_clearEvent_after_mapEvictAll_call_from_member_batchInvalidationEnabled_true_/

**Comment by hasancelik** [comment]
*master*
```
java.lang.AssertionError: Expecting only 1 clear event expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.client.map.impl.nearcache.ClientMapNearCacheTest$27.run(ClientMapNearCacheTest.java:1009)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1003)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1020)
	at com.hazelcast.client.map.impl.nearcache.ClientMapNearCacheTest.receives_one_clearEvent_after_mapEvictAll_call_from_member(ClientMapNearCacheTest.java:1006)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-ZuluJDK7/com.hazelcast$hazelcast-client/565/testReport/junit/com.hazelcast.client.map.impl.nearcache/ClientMapNearCacheTest/receives_one_clearEvent_after_mapEvictAll_call_from_member_batchInvalidationEnabled_false_/

**Comment by ihsandemir** [comment]
Can not reproduce the problem locally but I have a theory for it to happen:

1 - The second member joins the cluster.
2 - client did not connect and register the listener to the second member yet.
3 - memberMap.evictAll is called. The eviction event will only be sent from the member owning the partition getPartitionId(mapName) and if this happens to be newly initialised member to which the client did not register the listener yet.

In this scenario, the new member will not send the event to the client.
