### ISSUE TITLE
[near-cache] ClientNearCacheTest.putToCacheAndGetInvalidationEventWhenNodeShutdown[format:BINARY]

### ISSUE THREAD

**Issue by Donnerbart** [hazelcast/hazelcast#10031]
This test seems to fail quite regularly:
```
java.lang.AssertionError: expected:<Value-16> but was:<null>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.client.cache.impl.nearcache.ClientNearCacheTestSupport.putToCacheAndGetInvalidationEventWhenNodeShutdown(ClientNearCacheTestSupport.java:291)
	at com.hazelcast.client.cache.impl.nearcache.ClientNearCacheTest.putToCacheAndGetInvalidationEventWhenNodeShutdown(ClientNearCacheTest.java:66)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/7438/testReport/junit/com.hazelcast.client.cache.impl.nearcache/ClientNearCacheTest/putToCacheAndGetInvalidationEventWhenNodeShutdown_format_BINARY_/

```
java.lang.AssertionError: expected:<Value-71> but was:<null>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.client.cache.impl.nearcache.ClientNearCacheTestSupport.putToCacheAndGetInvalidationEventWhenNodeShutdown(ClientNearCacheTestSupport.java:291)
	at com.hazelcast.client.cache.impl.nearcache.ClientNearCacheTest.putToCacheAndGetInvalidationEventWhenNodeShutdown(ClientNearCacheTest.java:66)
```
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/new-lab-fast-pr/7435/testReport/junit/com.hazelcast.client.cache.impl.nearcache/ClientNearCacheTest/putToCacheAndGetInvalidationEventWhenNodeShutdown_format_BINARY_/

**Comment by Donnerbart** [comment]
Ignored test via https://github.com/hazelcast/hazelcast/commit/d12bcd44010d6adf9ec69ba0780cd9111159931b

**Comment by Donnerbart** [comment]
Passed 500 local runs and a couple of PR builders without failure. Test is re-activated.
