### ISSUE TITLE
ClientReplicatedMapNearCacheBasicTest.whenCacheIsFull_thenPutOnSameKeyShouldUpdateValue_withUpdateOnDataAdapter

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#10067]
```
java.lang.AssertionError: Near Cache entry count should be 500, but was 1 (NearCacheStatsImpl{ownedEntryCount=1, ownedEntryMemoryCost=112, creationTime=1489374270237, hits=1198, misses=1002, ratio=119.6%, evictions=0, expirations=0, lastPersistenceTime=0, persistenceCount=0, lastPersistenceDuration=0, lastPersistenceWrittenBytes=0, lastPersistenceKeyCount=0, lastPersistenceFailure=''}) expected:<500> but was:<1>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils.assertEqualsFormat(NearCacheTestUtils.java:170)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils.assertNearCacheStats(NearCacheTestUtils.java:157)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils.assertNearCacheStats(NearCacheTestUtils.java:139)
	at com.hazelcast.internal.nearcache.AbstractNearCacheBasicTest$1.run(AbstractNearCacheBasicTest.java:183)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:967)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:984)
	at com.hazelcast.internal.nearcache.AbstractNearCacheBasicTest.whenCacheIsFull_thenPutOnSameKeyShouldUpdateValue_withUpdateOnDataAdapter(AbstractNearCacheBasicTest.java:174)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:95)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.lang.Thread.run(Thread.java:785)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.8/com.hazelcast$hazelcast-client/525/testReport/junit/com.hazelcast.client.replicatedmap.nearcache/ClientReplicatedMapNearCacheBasicTest/whenCacheIsFull_thenPutOnSameKeyShouldUpdateValue_withUpdateOnDataAdapter_format_BINARY_/

**Comment by Donnerbart** [comment]
Tests were refactored a lot and some bugs regarding the NearCacheStats were fixed. Closing until this happens again.
