### ISSUE TITLE
MemcacheTest.testDecrement

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#10070]
```
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1440)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1464)
	at sun.nio.ch.SelectorImpl.implCloseSelector(SelectorImpl.java:124)
	at java.nio.channels.spi.AbstractSelector.close(AbstractSelector.java:122)
	at net.spy.memcached.MemcachedConnection.shutdown(MemcachedConnection.java:1339)
	at net.spy.memcached.MemcachedClient.shutdown(MemcachedClient.java:2512)
	at net.spy.memcached.MemcachedClient.shutdown(MemcachedClient.java:2474)
	at com.hazelcast.internal.ascii.MemcacheTest.tearDown(MemcacheTest.java:81)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-IbmJDK1.8/com.hazelcast$hazelcast/186/testReport/junit/com.hazelcast.internal.ascii/MemcacheTest/testDecrement/

**Comment by ahmetmircik** [comment]
@hasancelik updated `IbmJDK1.8` as a fix attempt, lets wait for next failure.
