### ISSUE TITLE
ScheduledExecutorServiceSlowTest.stats_longRunningTask_durable

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#10071]
```
java.lang.AssertionError: expected:<6> but was:<8>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.scheduledexecutor.ScheduledExecutorServiceSlowTest.stats_longRunningTask_durable(ScheduledExecutorServiceSlowTest.java:120)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-nightly/com.hazelcast$hazelcast/1156/testReport/junit/com.hazelcast.scheduledexecutor/ScheduledExecutorServiceSlowTest/stats_longRunningTask_durable/

**Comment by hasancelik** [comment]
*master*
```
java.lang.AssertionError: expected:<6> but was:<7>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.scheduledexecutor.ScheduledExecutorServiceSlowTest.stats_longRunningTask_durable(ScheduledExecutorServiceSlowTest.java:122)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/1302/testReport/junit/com.hazelcast.scheduledexecutor/ScheduledExecutorServiceSlowTest/stats_longRunningTask_durable/
