### ISSUE TITLE
ClientMapNearCachePreloaderTest.testStoreAndLoad_withStringKeys_withInMemoryFormatBinary

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#10106]
```
org.junit.runners.model.TestTimedOutException: test timed out after 120000 milliseconds
	at java.lang.Thread.sleep(Native Method)
	at java.lang.Thread.sleep(Thread.java:340)
	at java.util.concurrent.TimeUnit.sleep(TimeUnit.java:360)
	at com.hazelcast.test.HazelcastTestSupport.sleepMillis(HazelcastTestSupport.java:261)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:975)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:984)
	at com.hazelcast.internal.nearcache.AbstractNearCachePreloaderTest.assertNearCacheSizeEventually(AbstractNearCachePreloaderTest.java:363)
	at com.hazelcast.internal.nearcache.AbstractNearCachePreloaderTest.storeAndLoad(AbstractNearCachePreloaderTest.java:166)
	at com.hazelcast.internal.nearcache.AbstractNearCachePreloaderTest.testStoreAndLoad_withStringKeys_withInMemoryFormatBinary(AbstractNearCachePreloaderTest.java:136)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.lang.Thread.run(Thread.java:745)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast-client/1280/testReport/junit/com.hazelcast.client.map.impl.nearcache/ClientMapNearCachePreloaderTest/testStoreAndLoad_withStringKeys_withInMemoryFormatBinary_invalidationOnChange_true_/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/1301/

**Comment by mmedenjak** [comment]
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/1308/

**Comment by hasancelik** [comment]
*testStoreAndLoad_withStringKeys_withInMemoryFormatBinary[invalidationOnChange:true]
testStoreAndLoad_withIntegerKeys_withInMemoryFormatBinary[invalidationOnChange:true]
testStoreAndLoad_withStringKeys_withInMemoryFormatObject[invalidationOnChange:true]*
```
org.junit.runners.model.TestTimedOutException: test timed out after 120000 milliseconds
	at java.lang.Thread.sleep(Native Method)
	at java.lang.Thread.sleep(Thread.java:340)
	at java.util.concurrent.TimeUnit.sleep(TimeUnit.java:386)
	at com.hazelcast.test.HazelcastTestSupport.sleepMillis(HazelcastTestSupport.java:272)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1049)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1058)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils.assertNearCacheSizeEventually(NearCacheTestUtils.java:334)
	at com.hazelcast.internal.nearcache.AbstractNearCachePreloaderTest.storeAndLoad(AbstractNearCachePreloaderTest.java:167)
	at com.hazelcast.internal.nearcache.AbstractNearCachePreloaderTest.testStoreAndLoad_withStringKeys_withInMemoryFormatBinary(AbstractNearCachePreloaderTest.java:137)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
```

https://hazelcast-l337.ci.cloudbees.com/view/Sonar/job/Hazelcast-3.x-sonar/1517/

**Comment by Donnerbart** [comment]
I suspect that the IO is very slow (similar issue to the logging). The test timeout has been increased in this PR: https://github.com/hazelcast/hazelcast/pull/10694

Let's see if that fixes the issue.

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: Near Cache size didn't reach the desired value (4223 vs. 4222) (NearCacheStatsImpl{ownedEntryCount=4222, ownedEntryMemoryCost=0, creationTime=1498700305590, hits=0, misses=4223, ratio=0.0%, evictions=0, expirations=0, lastPersistenceTime=1498700427618, persistenceCount=60, lastPersistenceDuration=27, lastPersistenceWrittenBytes=100218, lastPersistenceKeyCount=4222, lastPersistenceFailure=''}) expected:<4223> but was:<4222>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils.assertNearCacheSize(NearCacheTestUtils.java:364)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils$3.run(NearCacheTestUtils.java:384)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1064)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1081)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils.assertNearCacheSizeEventually(NearCacheTestUtils.java:381)
	at com.hazelcast.internal.nearcache.AbstractNearCachePreloaderTest.storeAndLoad(AbstractNearCachePreloaderTest.java:160)
	at com.hazelcast.internal.nearcache.AbstractNearCachePreloaderTest.testStoreAndLoad_withStringKeys(AbstractNearCachePreloaderTest.java:137)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.lang.Thread.run(Thread.java:745)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast-client/1393/testReport/junit/com.hazelcast.client.map.impl.nearcache/ClientMapNearCachePreloaderTest/testStoreAndLoad_withStringKeys_format_OBJECT_invalidationOnChange_true_serializeKeys_true_/

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast-client/1395/testReport/junit/com.hazelcast.client.map.impl.nearcache/ClientMapNearCachePreloaderTest/testStoreAndLoad_withStringKeys_format_BINARY_invalidationOnChange_true_serializeKeys_true_/
