### ISSUE TITLE
NearCacheRecordStoreTest.statsCalculated

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#10108]
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.internal.nearcache.NearCacheRecordStoreTestSupport.statsCalculated(NearCacheRecordStoreTestSupport.java:112)
	at com.hazelcast.internal.nearcache.NearCacheRecordStoreTest.statsCalculated(NearCacheRecordStoreTest.java:75)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK1.7/797/

**Comment by ahmetmircik** [comment]
merged a fix attempt: https://github.com/hazelcast/hazelcast/commit/42d0b7d256fbe52bf286437729d2fc8d03435ac0

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.internal.nearcache.NearCacheRecordStoreTestSupport.statsCalculated(NearCacheRecordStoreTestSupport.java:114)
	at com.hazelcast.internal.nearcache.NearCacheRecordStoreTest$1.run(NearCacheRecordStoreTest.java:79)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:992)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1009)
	at com.hazelcast.internal.nearcache.NearCacheRecordStoreTest.statsCalculated(NearCacheRecordStoreTest.java:76)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-freestyle/388/

**Comment by ahmetmircik** [comment]
lets wait for another failure, added failure message, suspecting a clock issue: https://github.com/hazelcast/hazelcast/commit/6d868d17c5df82a853b596ce4dbc78a4c133cdff
