### ISSUE TITLE
ringBuffer java.lang.IllegalArgumentException: sequence:  is too large. The current tailSequence is:

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#10125]
3.9-SNAPSHOT

ring buff test, which normally passes every time under stable cluster conditions.
when run, while members are shutdown and restarted gives java.lang.IllegalArgumentException

```
java.lang.IllegalArgumentException: sequence:17108 is too large. The current tailSequence is:0
	at com.hazelcast.ringbuffer.impl.RingbufferContainer.checkBlockableReadSequence(RingbufferContainer.java:358)
	at com.hazelcast.ringbuffer.impl.operations.ReadOneOperation.beforeRun(ReadOneOperation.java:46)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:180)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:382)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:409)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:534)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:519)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:490)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:200)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:59)
	at com.hazelcast.client.impl.protocol.task.AbstractPartitionMessageTask.processMessage(AbstractPartitionMessageTask.java:64)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:122)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:102)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:142)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:127)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:102)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:114)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run(AbstractInvocationFuture.java:243)
	at com.hazelcast.client.impl.protocol.task.AbstractPartitionMessageTask.execute(AbstractPartitionMessageTask.java:78)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.unblock(AbstractInvocationFuture.java:239)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.andThen(AbstractInvocationFuture.java:215)
	at com.hazelcast.client.impl.protocol.task.AbstractPartitionMessageTask.processMessage(AbstractPartitionMessageTask.java:69)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:122)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:102)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:142)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:127)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:102)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:109)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:35)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:155)
	at com.hazelcast.client.proxy.ClientRingbufferProxy.invoke(ClientRingbufferProxy.java:250)
	at com.hazelcast.client.proxy.ClientRingbufferProxy.readOne(ClientRingbufferProxy.java:187)
	at hzcmd.ring.ReadOne.timeStep(ReadOne.java:20)
	at remote.bench.marker.MetricsMarker.flatOut(MetricsMarker.java:53)
	at remote.bench.marker.MetricsMarker.bench(MetricsMarker.java:40)
	at remote.bench.BenchThread.call(BenchThread.java:38)
	at remote.bench.BenchThread.call(BenchThread.java:12)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
java.lang.IllegalArgumentException: sequence:19782 is too large. The current tailSequence is:14
	at com.hazelcast.ringbuffer.impl.RingbufferContainer.checkBlockableReadSequence(RingbufferContainer.java:358)
	at com.hazelcast.ringbuffer.impl.operations.ReadOneOperation.beforeRun(ReadOneOperation.java:46)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:180)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:401)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:117)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:102)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:114)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run(AbstractInvocationFuture.java:243)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:109)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:35)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:155)
	at com.hazelcast.client.proxy.ClientRingbufferProxy.invoke(ClientRingbufferProxy.java:250)
	at com.hazelcast.client.proxy.ClientRingbufferProxy.readOne(ClientRingbufferProxy.java:187)
	at hzcmd.ring.ReadOne.timeStep(ReadOne.java:20)
	at remote.bench.marker.MetricsMarker.flatOut(MetricsMarker.java:53)
	at remote.bench.marker.MetricsMarker.bench(MetricsMarker.java:40)
	at remote.bench.BenchThread.call(BenchThread.java:38)
	at remote.bench.BenchThread.call(BenchThread.java:12)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

/disk1/jenkins/workspace/shutdown-All/3.9-SNAPSHOT/2017_03_20-20_07_52/stable/ring

https://hazelcast-l337.ci.cloudbees.com/view/rollup/job/rollup-All/9/consoleFull

**Comment by tkountis** [comment]
@Danny-Hazelcast went through the code, and wrote a small test that attempts to force this exception, and this is what I came up with

```
@Test
public void read_whenAllReplicasAreKilled() throws Exception {
   TestHazelcastInstanceFactory factory = createHazelcastInstanceFactory(3);

   HazelcastInstance instanceA = factory.newHazelcastInstance();
   HazelcastInstance instanceB = factory.newHazelcastInstance();
   HazelcastInstance instanceC = factory.newHazelcastInstance();

   Collection<HazelcastInstance> instances = factory.getAllHazelcastInstances();

   String ringBufferName = generateKeyOwnedBy(instanceA);
   InternalPartitionService partitionService = getPartitionService(instanceA);
   Address replicaAddress = partitionService.getPartition(partitionService.getPartitionId(ringBufferName)).getReplicaAddress(1);

   HazelcastInstance replica = null;
   HazelcastInstance lastInstance = null;

   for (int i = 0; i < factory.getCount(); i++) {
       HazelcastInstance currInst = (HazelcastInstance) instances.toArray()[i];
       if (replicaAddress.equals(currInst.getCluster().getLocalMember().getAddress())) {
           replica = currInst;
       }

       if (!currInst.equals(instanceA) && !currInst.equals(replica)) {
           lastInstance = currInst;
       }
   }

   Ringbuffer<String> ringbuffer = instanceA.getRingbuffer(ringBufferName);
   for (int i = 0; i < 10000; i++) {
       ringbuffer.add("Entry_" + i);
   }

   for (int i = 0; i < 10000; i++) {
       ringbuffer.readOne(i);
       if (i == 1000) {
           instanceA.getLifecycleService().terminate();
           replica.getLifecycleService().terminate();

           ringbuffer = lastInstance.getRingbuffer(ringBufferName);
       }
   }
}
```

In other words, the only way I can see this happening, is by losing partition or split-brain scenarios. The add operation is backed, so tail-sequence among replicas should be in sync, or *very* close to each other, but not 0. I believe the random member bounce, needs enhancement to make sure after the member restarts, the cluster is back in safe mode, before bouncing the next random member.

Below is another code sample which demonstrates that tail-sequence is ok, when forcefully terminating the owner

```
@Test
public void read_whenOwnerKilled() throws Exception {
    TestHazelcastInstanceFactory factory = createHazelcastInstanceFactory(3);

    HazelcastInstance instanceA = factory.newHazelcastInstance();
    HazelcastInstance instanceB = factory.newHazelcastInstance();
    HazelcastInstance instanceC = factory.newHazelcastInstance();
    
    String ringBufferName = generateKeyOwnedBy(instanceA);

    Ringbuffer<String> ringbuffer = instanceA.getRingbuffer(ringBufferName);
    for (int i = 0; i < 10000; i++) {
        ringbuffer.add("Entry_" + i);
    }

    for (int i = 0; i < 10000; i++) {
        ringbuffer.readOne(i);
        if (i == 1000) {
            instanceA.getLifecycleService().terminate();
            ringbuffer = instanceB.getRingbuffer(ringBufferName);
            ringbuffer.add("Entry_" + (10000 + i));
        }
    }
}
```

**Comment by Danny-Hazelcast** [comment]
https://github.com/hazelcast/hazelcast-enterprise/issues/1385

is better issue for this, as its in group of similar issues, with matching titles and group issue numbers

**Comment by Danny-Hazelcast** [comment]
closing a duplicate
