### ISSUE TITLE
*OnReconnectTest.testListenersNonSmartRoutingTerminateRandomNode

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#10235]
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:226)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1037)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1326)
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:281)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:877)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:872)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:864)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest$9.run(AbstractListenersOnReconnectTest.java:523)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:972)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:989)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest.validateListenerFunctionality(AbstractListenersOnReconnectTest.java:510)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest.validateRegistrationsAndListenerFunctionality(AbstractListenersOnReconnectTest.java:473)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest.testListenersTerminateRandomNode(AbstractListenersOnReconnectTest.java:113)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest.testListenersNonSmartRoutingTerminateRandomNode(AbstractListenersOnReconnectTest.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:622)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.lang.Thread.run(Thread.java:701)
```

https://hazelcast-l337.ci.cloudbees.com/view/Zing/job/Hazelcast-3.x-ZingJDK6/17/testReport/junit/com.hazelcast.client.listeners/ListItemListenerOnReconnectTest/testListenersNonSmartRoutingTerminateRandomNode/

**Comment by Donnerbart** [comment]
**com.hazelcast.client.listeners.EntryListenerOnReconnectTest.testListenersNonSmartRoutingMultipleServer**
```java
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:196)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1011)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1303)
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:253)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:942)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:937)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:929)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest$9.run(AbstractListenersOnReconnectTest.java:523)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1037)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1054)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest.validateListenerFunctionality(AbstractListenersOnReconnectTest.java:510)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest.validateRegistrationsAndListenerFunctionality(AbstractListenersOnReconnectTest.java:473)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest.testListenersTerminateOwnerNode(AbstractListenersOnReconnectTest.java:458)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest.testListenersNonSmartRoutingMultipleServer(AbstractListenersOnReconnectTest.java:409)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.lang.Thread.run(Thread.java:662)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/8993/testReport/junit/com.hazelcast.client.listeners/EntryListenerOnReconnectTest/testListenersNonSmartRoutingMultipleServer/

**Comment by Donnerbart** [comment]
**com.hazelcast.client.listeners.ListItemListenerOnReconnectTest.testListenersNonSmartRoutingTerminateRandomNode**
```java
java.lang.AssertionError: Received event count is 20 but it is expected to stay at 10 expected:<10> but was:<20>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest$9$1.run(AbstractListenersOnReconnectTest.java:530)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueAllTheTime(HazelcastTestSupport.java:1021)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest$9.run(AbstractListenersOnReconnectTest.java:525)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1037)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1054)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest.validateListenerFunctionality(AbstractListenersOnReconnectTest.java:510)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest.validateRegistrationsAndListenerFunctionality(AbstractListenersOnReconnectTest.java:473)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest.testListenersTerminateRandomNode(AbstractListenersOnReconnectTest.java:113)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest.testListenersNonSmartRoutingTerminateRandomNode(AbstractListenersOnReconnectTest.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.lang.Thread.run(Thread.java:662)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/8993/testReport/junit/com.hazelcast.client.listeners/ListItemListenerOnReconnectTest/testListenersNonSmartRoutingTerminateRandomNode/

**Comment by Donnerbart** [comment]
Failed again on a 3.9 PR builder
**com.hazelcast.client.listeners.ListItemListenerOnReconnectTest.testListenersNonSmartRoutingMultipleServer**
```java
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertNotNull(Assert.java:712)
	at org.junit.Assert.assertNotNull(Assert.java:722)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest$8.run(AbstractListenersOnReconnectTest.java:482)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1086)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1103)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest.validateRegistrationsOnMembers(AbstractListenersOnReconnectTest.java:475)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest.validateRegistrationsAndListenerFunctionality(AbstractListenersOnReconnectTest.java:468)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest.testListenersTerminateOwnerNode(AbstractListenersOnReconnectTest.java:455)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest.testListenersNonSmartRoutingMultipleServer(AbstractListenersOnReconnectTest.java:406)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/10434/testReport/junit/com.hazelcast.client.listeners/ListItemListenerOnReconnectTest/testListenersNonSmartRoutingMultipleServer/

**Comment by Donnerbart** [comment]
**com.hazelcast.client.listeners.MultiMapEntryListenerOnReconnectTest.testClusterReconnectDueToHeartbeatNonSmartRouting**
```java
java.lang.AssertionError: expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest$9.run(AbstractListenersOnReconnectTest.java:501)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1086)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1103)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest.validateRegistrations(AbstractListenersOnReconnectTest.java:495)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest.validateRegistrationsAndListenerFunctionality(AbstractListenersOnReconnectTest.java:469)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest.testListenersHeartbeatTimeoutToOwner(AbstractListenersOnReconnectTest.java:385)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest.testClusterReconnectDueToHeartbeatNonSmartRouting(AbstractListenersOnReconnectTest.java:345)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/10488/testReport/junit/com.hazelcast.client.listeners/MultiMapEntryListenerOnReconnectTest/testClusterReconnectDueToHeartbeatNonSmartRouting/

**Comment by sancar** [comment]
Issue on comment https://github.com/hazelcast/hazelcast/issues/10235#issuecomment-325973662 is resolved with 
https://github.com/hazelcast/hazelcast/pull/11306 and 
https://github.com/hazelcast/hazelcast/pull/11307

Issue on 
https://github.com/hazelcast/hazelcast/issues/10235#issuecomment-324879476 
is already reported in and will be followed from there

Closing this one.
