### ISSUE TITLE
PartitionReplicaVersionsCorrectnessStressTest.testReplicaVersionsWhenNodesCrashSimultaneously

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#10236]
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.lang.Thread.sleep(Native Method)
	at java.lang.Thread.sleep(Thread.java:340)
	at java.util.concurrent.TimeUnit.sleep(TimeUnit.java:360)
	at com.hazelcast.test.HazelcastTestSupport.sleepMillis(HazelcastTestSupport.java:266)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:980)
	at com.hazelcast.test.HazelcastTestSupport.waitAllForSafeState(HazelcastTestSupport.java:592)
	at com.hazelcast.partition.AbstractPartitionLostListenerTest.waitAllForSafeStateAndDumpPartitionServiceOnFailure(AbstractPartitionLostListenerTest.java:180)
	at com.hazelcast.internal.partition.PartitionReplicaVersionsCorrectnessStressTest.testReplicaVersionsWhenNodesCrashSimultaneously(PartitionReplicaVersionsCorrectnessStressTest.java:100)
```

https://hazelcast-l337.ci.cloudbees.com/view/Zing/job/Hazelcast-3.x-ZingJDK8/18/testReport/junit/com.hazelcast.internal.partition/PartitionReplicaVersionsCorrectnessStressTest/testReplicaVersionsWhenNodesCrashSimultaneously_numberOfNodesToCrash_1_nodeCount_7_nodeLeaveType_TERMINATE_/

https://hazelcast-l337.ci.cloudbees.com/view/Zing/job/Hazelcast-3.x-ZingJDK8/18/#showFailuresLink

**Comment by mdogan** [comment]
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/1353/

```
java.lang.AssertionError: Surviving: [HazelcastInstance{name='_hzInstance_14_dev', node=[127.0.0.1]:5004}, HazelcastInstance{name='_hzInstance_13_dev', node=[127.0.0.1]:5003}, HazelcastInstance{name='_hzInstance_18_dev', node=[127.0.0.1]:5008}, HazelcastInstance{name='_hzInstance_15_dev', node=[127.0.0.1]:5005}, HazelcastInstance{name='_hzInstance_12_dev', node=[127.0.0.1]:5002}, HazelcastInstance{name='_hzInstance_16_dev', node=[127.0.0.1]:5006}] Terminating: [HazelcastInstance{name='_hzInstance_17_dev', node=[127.0.0.1]:5007}] PartitionId: 2 InitialReplicaVersions: null ReplicaVersions: [0, 0, 0, 0, 0, 0] SmallestSurvivingReplicaIndex: 1 InitialReplicaAddresses: [[127.0.0.1]:5007, [127.0.0.1]:5006, [127.0.0.1]:5003, [127.0.0.1]:5005, [127.0.0.1]:5008, [127.0.0.1]:5002, [127.0.0.1]:5004] Instance: [127.0.0.1]:5004 CurrentReplicaAddresses: [[127.0.0.1]:5004, [127.0.0.1]:5006, [127.0.0.1]:5003, [127.0.0.1]:5005, [127.0.0.1]:5008, [127.0.0.1]:5002, null]: expected array was null
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.internal.ComparisonCriteria.assertArraysAreSameLength(ComparisonCriteria.java:68)
	at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:37)
	at org.junit.Assert.internalArrayEquals(Assert.java:532)
	at org.junit.Assert.assertArrayEquals(Assert.java:441)
	at com.hazelcast.internal.partition.PartitionReplicaVersionsCorrectnessStressTest.validateReplicaVersions(PartitionReplicaVersionsCorrectnessStressTest.java:133)
	at com.hazelcast.internal.partition.PartitionReplicaVersionsCorrectnessStressTest.testReplicaVersionsWhenNodesCrashSimultaneously(PartitionReplicaVersionsCorrectnessStressTest.java:102)
```

```
java.lang.AssertionError: Surviving: [HazelcastInstance{name='_hzInstance_92_dev', node=[127.0.0.1]:5082}, HazelcastInstance{name='_hzInstance_93_dev', node=[127.0.0.1]:5083}, HazelcastInstance{name='_hzInstance_85_dev', node=[127.0.0.1]:5075}, HazelcastInstance{name='_hzInstance_87_dev', node=[127.0.0.1]:5077}, HazelcastInstance{name='_hzInstance_91_dev', node=[127.0.0.1]:5081}, HazelcastInstance{name='_hzInstance_86_dev', node=[127.0.0.1]:5076}, HazelcastInstance{name='_hzInstance_90_dev', node=[127.0.0.1]:5080}] Terminating: [HazelcastInstance{name='_hzInstance_84_dev', node=[127.0.0.1]:5074}, HazelcastInstance{name='_hzInstance_89_dev', node=[127.0.0.1]:5079}, HazelcastInstance{name='_hzInstance_88_dev', node=[127.0.0.1]:5078}] PartitionId: 2 InitialReplicaVersions: null ReplicaVersions: [0, 0, 0, 0, 0, 0] SmallestSurvivingReplicaIndex: 0 InitialReplicaAddresses: [[127.0.0.1]:5082, [127.0.0.1]:5077, [127.0.0.1]:5081, [127.0.0.1]:5075, [127.0.0.1]:5078, [127.0.0.1]:5074, [127.0.0.1]:5076] Instance: [127.0.0.1]:5082 CurrentReplicaAddresses: [[127.0.0.1]:5082, [127.0.0.1]:5080, [127.0.0.1]:5081, [127.0.0.1]:5075, [127.0.0.1]:5076, [127.0.0.1]:5083, [127.0.0.1]:5077]: expected array was null
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.internal.ComparisonCriteria.assertArraysAreSameLength(ComparisonCriteria.java:68)
	at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:37)
	at org.junit.Assert.internalArrayEquals(Assert.java:532)
	at org.junit.Assert.assertArrayEquals(Assert.java:441)
	at com.hazelcast.internal.partition.PartitionReplicaVersionsCorrectnessStressTest.validateReplicaVersions(PartitionReplicaVersionsCorrectnessStressTest.java:133)
	at com.hazelcast.internal.partition.PartitionReplicaVersionsCorrectnessStressTest.testReplicaVersionsWhenNodesCrashSimultaneously(PartitionReplicaVersionsCorrectnessStressTest.java:102)
```

**Comment by hasancelik** [comment]
*maintenance*
```
java.lang.AssertionError: CountDownLatch failed to complete within 120 seconds, count left: 3
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:1012)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:1005)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:997)
	at com.hazelcast.partition.AbstractPartitionLostListenerTest.stopInstances(AbstractPartitionLostListenerTest.java:104)
	at com.hazelcast.internal.partition.PartitionReplicaVersionsCorrectnessStressTest.testReplicaVersionsWhenNodesCrashSimultaneously(PartitionReplicaVersionsCorrectnessStressTest.java:107)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-nightly/1438/

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-nightly/1434/

**Comment by mmedenjak** [comment]
@mdogan @metanet do you think this can be addressed in 3.9.3?

**Comment by mdogan** [comment]
@mmedenjak: That doesn't look like a _real_ test failure. Somehow shutdown of multiple nodes didn't complete in 2 minutes.

In failure below, 6 of 10 nodes were being shutdown concurrently, but latch timed out before shutdown complete. I looked at the failure log, by the time it failed, there were still on going/pending migrations due to graceful shutdown.

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-nightly/com.hazelcast$hazelcast/1453/testReport/junit/com.hazelcast.internal.partition/PartitionReplicaVersionsCorrectnessStressTest/testReplicaVersionsWhenNodesCrashSimultaneously_numberOfNodesToCrash_6_nodeCount_10_nodeLeaveType_SHUTDOWN_/

We can increase the latch timeout or reduce the number of nodes as a solution.

**Comment by mmedenjak** [comment]
Sure, if you can then just make the test less susceptible to failing (lower partition count/node count/increase latch timeout) or otherwise just close the issue if you deem it does not occur that often.

**Comment by mmedenjak** [comment]
Moving this to 3.9.4 as it is an environmental issue. @mdogan @metanet please improve the test or close the issue.

**Comment by mmedenjak** [comment]
@mdogan thanks!

**Comment by tezc** [comment]
http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-nightly/27/testReport/junit/com.hazelcast.internal.partition/PartitionReplicaVersionsCorrectnessStressTest/testReplicaVersionsWhenNodesCrashSimultaneously_numberOfNodesToCrash_3_nodeCount_7_nodeLeaveType_SHUTDOWN_/

```
java.lang.AssertionError: Surviving: [HazelcastInstance{name='_hzInstance_3589_dev', node=[127.0.0.1]:5707}, HazelcastInstance{name='_hzInstance_3583_dev', node=[127.0.0.1]:5701}, HazelcastInstance{name='_hzInstance_3584_dev', node=[127.0.0.1]:5702}, HazelcastInstance{name='_hzInstance_3588_dev', node=[127.0.0.1]:5706}] Terminating: [HazelcastInstance{name='_hzInstance_3586_dev', node=[127.0.0.1]:5704}, HazelcastInstance{name='_hzInstance_3585_dev', node=[127.0.0.1]:5703}, HazelcastInstance{name='_hzInstance_3587_dev', node=[127.0.0.1]:5705}] PartitionId: 1 InitialReplicaVersions: Replica Versions={DefaultObjectNamespace{service='hz:impl:mapService', objectName=map-6}=[29, 29, 29, 29, 29, 29],DefaultObjectNamespace{service='hz:impl:mapService', objectName=map-4}=[29, 29, 29, 29, 0, 0],DefaultObjectNamespace{service='hz:impl:mapService', objectName=map-5}=[29, 29, 29, 29, 29, 0],NonFragmentedServiceNamespace=[0, 0, 0, 0, 0, 0],DefaultObjectNamespace{service='hz:impl:mapService', objectName=map-2}=[29, 29, 0, 0, 0, 0],DefaultObjectNamespace{service='hz:impl:mapService', objectName=map-3}=[29, 29, 29, 0, 0, 0],DefaultObjectNamespace{service='hz:impl:mapService', objectName=map-1}=[29, 0, 0, 0, 0, 0],}, Dirty Namespaces=[] ReplicaVersions: Replica Versions={DefaultObjectNamespace{service='hz:impl:mapService', objectName=map-4}=[29, 29, 29, 29, 0, 0],DefaultObjectNamespace{service='hz:impl:mapService', objectName=map-5}=[29, 29, 29, 29, 29, 0],NonFragmentedServiceNamespace=[0, 0, 0, 0, 0, 0],DefaultObjectNamespace{service='hz:impl:mapService', objectName=map-2}=[29, 29, 0, 0, 0, 0],DefaultObjectNamespace{service='hz:impl:mapService', objectName=map-3}=[29, 29, 29, 0, 0, 0],DefaultObjectNamespace{service='hz:impl:mapService', objectName=map-0}=[0, 0, 0, 0, 0, 0],DefaultObjectNamespace{service='hz:impl:mapService', objectName=map-1}=[29, 0, 0, 0, 0, 0],}, Dirty Namespaces=[] SmallestSurvivingReplicaIndex: 1 InitialReplicaAddresses: [[127.0.0.1]:5704, [127.0.0.1]:5706, [127.0.0.1]:5703, [127.0.0.1]:5701, [127.0.0.1]:5702, [127.0.0.1]:5707, [127.0.0.1]:5705] Instance: [127.0.0.1]:5702 CurrentReplicaAddresses: [[127.0.0.1]:5702, [127.0.0.1]:5701, [127.0.0.1]:5706, [127.0.0.1]:5707, null, null, null] expected:<Replica Versions={DefaultObjectNamespace{service='hz:impl:mapService', objectName=map-6}=[29, 29, 29, 29, 29, 29],DefaultObjectNamespace{service='hz:impl:mapService', objectName=map-4}=[29, 29, 29, 29, 0, 0],DefaultObjectNamespace{service='hz:impl:mapService', objectName=map-5}=[29, 29, 29, 29, 29, 0],NonFragmentedServiceNamespace=[0, 0, 0, 0, 0, 0],DefaultObjectNamespace{service='hz:impl:mapService', objectName=map-2}=[29, 29, 0, 0, 0, 0],DefaultObjectNamespace{service='hz:impl:mapService', objectName=map-3}=[29, 29, 29, 0, 0, 0],DefaultObjectNamespace{service='hz:impl:mapService', objectName=map-1}=[29, 0, 0, 0, 0, 0],}, Dirty Namespaces=[]> but was:<Replica Versions={DefaultObjectNamespace{service='hz:impl:mapService', objectName=map-4}=[29, 29, 29, 29, 0, 0],DefaultObjectNamespace{service='hz:impl:mapService', objectName=map-5}=[29, 29, 29, 29, 29, 0],NonFragmentedServiceNamespace=[0, 0, 0, 0, 0, 0],DefaultObjectNamespace{service='hz:impl:mapService', objectName=map-2}=[29, 29, 0, 0, 0, 0],DefaultObjectNamespace{service='hz:impl:mapService', objectName=map-3}=[29, 29, 29, 0, 0, 0],DefaultObjectNamespace{service='hz:impl:mapService', objectName=map-0}=[0, 0, 0, 0, 0, 0],DefaultObjectNamespace{service='hz:impl:mapService', objectName=map-1}=[29, 0, 0, 0, 0, 0],}, Dirty Namespaces=[]>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at com.hazelcast.internal.partition.PartitionReplicaVersionsCorrectnessStressTest.validateReplicaVersions(PartitionReplicaVersionsCorrectnessStressTest.java:137)
	at com.hazelcast.internal.partition.PartitionReplicaVersionsCorrectnessStressTest.testReplicaVersionsWhenNodesCrashSimultaneously(PartitionReplicaVersionsCorrectnessStressTest.java:105)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by metanet** [comment]
Fixed by https://github.com/hazelcast/hazelcast/pull/14582
