### ISSUE TITLE
[queue] QueueTestsFrom2X.issue370

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#10287]
```
java.lang.AssertionError: expected:<2> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.collection.impl.queue.QueueTestsFrom2X.issue370(QueueTestsFrom2X.java:209)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK1.7/com.hazelcast$hazelcast/820/testReport/junit/com.hazelcast.collection.impl.queue/QueueTestsFrom2X/issue370/

**Comment by mmedenjak** [comment]
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK1.7/816/
