### ISSUE TITLE
ClientMapTest failures

### ISSUE THREAD

**Issue by mmedenjak** [hazelcast/hazelcast#10303]
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.7/1240/

com.hazelcast.client.map.ClientMapTest.testExecuteOnKey

```
java.lang.IllegalStateException: Unable to connect to any address in the config! The following addresses were tried: [localhost/127.0.0.1:5703, /127.0.0.1:8005, /127.0.0.1:8004, localhost/127.0.0.1:5702, /127.0.0.1:8003, localhost/127.0.0.1:5701]
	at com.hazelcast.client.spi.impl.ClusterListenerSupport.connectToCluster(ClusterListenerSupport.java:180)
	at com.hazelcast.client.spi.impl.ClientClusterServiceImpl.start(ClientClusterServiceImpl.java:189)
	at com.hazelcast.client.impl.HazelcastClientInstanceImpl.start(HazelcastClientInstanceImpl.java:408)
	at com.hazelcast.client.test.TestHazelcastFactory.newHazelcastClient(TestHazelcastFactory.java:76)
	at com.hazelcast.client.map.ClientMapTest.setup(ClientMapTest.java:111)
```

com.hazelcast.client.map.ClientMapTest.testPartitionAwareKey
```
java.lang.IllegalStateException: Unable to connect to any address in the config! The following addresses were tried: [localhost/127.0.0.1:5703, /127.0.0.1:8014, /127.0.0.1:8013, /127.0.0.1:8012, localhost/127.0.0.1:5702, localhost/127.0.0.1:5701]
	at com.hazelcast.client.spi.impl.ClusterListenerSupport.connectToCluster(ClusterListenerSupport.java:180)
	at com.hazelcast.client.spi.impl.ClientClusterServiceImpl.start(ClientClusterServiceImpl.java:189)
	at com.hazelcast.client.impl.HazelcastClientInstanceImpl.start(HazelcastClientInstanceImpl.java:408)
	at com.hazelcast.client.test.TestHazelcastFactory.newHazelcastClient(TestHazelcastFactory.java:76)
	at com.hazelcast.client.map.ClientMapTest.setup(ClientMapTest.java:111)
```

com.hazelcast.client.map.ClientMapTest.testLock

```
java.lang.IllegalStateException: Unable to connect to any address in the config! The following addresses were tried: [localhost/127.0.0.1:5703, /127.0.0.1:8014, /127.0.0.1:8015, /127.0.0.1:8016, localhost/127.0.0.1:5702, localhost/127.0.0.1:5701]
	at com.hazelcast.client.spi.impl.ClusterListenerSupport.connectToCluster(ClusterListenerSupport.java:180)
	at com.hazelcast.client.spi.impl.ClientClusterServiceImpl.start(ClientClusterServiceImpl.java:189)
	at com.hazelcast.client.impl.HazelcastClientInstanceImpl.start(HazelcastClientInstanceImpl.java:408)
	at com.hazelcast.client.test.TestHazelcastFactory.newHazelcastClient(TestHazelcastFactory.java:76)
	at com.hazelcast.client.map.ClientMapTest.setup(ClientMapTest.java:111)
```

**Comment by mmedenjak** [comment]
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.8/578/
com.hazelcast.client.map.ClientMapTest.testMapStatistics
```
java.lang.AssertionError: get latency
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.client.map.ClientMapTest.testMapStatistics(ClientMapTest.java:820)
```

**Comment by sancar** [comment]
Merging to https://github.com/hazelcast/hazelcast/issues/3138
