### ISSUE TITLE
[entry-processor] EntryProcessorOffloadableTest test failures

### ISSUE THREAD

**Issue by mmedenjak** [hazelcast/hazelcast#10300]
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.7/1243/

com.hazelcast.map.EntryProcessorOffloadableTest.testEntryProcessorWithKey_offloadableReadOnly_returnValue[0: BINARY sync=0 async=0]

```
java.lang.AssertionError: expected:<value: 1> but was:<null>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.map.EntryProcessorOffloadableTest.testEntryProcessorWithKey_offloadableReadOnly_returnValue(EntryProcessorOffloadableTest.java:295)
```

com.hazelcast.map.EntryProcessorOffloadableTest.testEntryProcessorWithKey_offloadable_setValue[0: BINARY sync=0 async=0]

```
java.lang.AssertionError: expected:<value: 2> but was:<null>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.map.EntryProcessorOffloadableTest.testEntryProcessorWithKey_offloadable_setValue(EntryProcessorOffloadableTest.java:118)
```

com.hazelcast.map.EntryProcessorOffloadableTest.testEntryProcessorWithKey_offloadableReadOnly_withoutSetValue[0: BINARY sync=0 async=0]

```
java.lang.AssertionError: expected:<value: 1> but was:<null>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.map.EntryProcessorOffloadableTest.testEntryProcessorWithKey_offloadableReadOnly_withoutSetValue(EntryProcessorOffloadableTest.java:251)
```

com.hazelcast.map.EntryProcessorOffloadableTest.testEntryProcessorWithKey_offloadable_withoutSetValue[0: BINARY sync=0 async=0]

```
java.lang.AssertionError: expected:<value: 1> but was:<null>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.map.EntryProcessorOffloadableTest.testEntryProcessorWithKey_offloadable_withoutSetValue(EntryProcessorOffloadableTest.java:167)
```

com.hazelcast.map.EntryProcessorOffloadableTest.testEntryProcessorWithKey_offloadableReadOnly_noReturnValue[0: BINARY sync=0 async=0]

```
java.lang.AssertionError: expected:<value: 1> but was:<null>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.map.EntryProcessorOffloadableTest.testEntryProcessorWithKey_offloadableReadOnly_noReturnValue(EntryProcessorOffloadableTest.java:337)
```

**Comment by mmedenjak** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-ee-OracleJDK8/721/#showFailuresLink

**Comment by tombujok** [comment]
All of them failed on put, since the value is null. The EP should increment the value, but it didn't even get to it since the value has not been initialised.

**Comment by ahmetmircik** [comment]
not failed since April
