### ISSUE TITLE
ThreadLocalLeakTest failures

### ISSUE THREAD

**Issue by mmedenjak** [hazelcast/hazelcast#10305]
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.7/1237/

classloading.ThreadLocalLeakTest.testLeakingApplication_withThreadLocalCleanup[classLoaderType:OWN]

```
java.lang.AssertionError: Application created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@dd622dfd]) and a value of type [java.lang.Class] (value [class com.hazelcast.cache.impl.JCacheDetectorTest) but failed to remove it when the application was stopped.
	at org.junit.Assert.fail(Assert.java:88)
	at classloading.ThreadLocalLeakTestUtils.checkThreadLocalMapForLeaks(ThreadLocalLeakTestUtils.java:170)
	at classloading.ThreadLocalLeakTestUtils.checkThreadLocalsForLeaks(ThreadLocalLeakTestUtils.java:68)
	at classloading.ThreadLocalLeakTest.testLeakingApplication_withThreadLocalCleanup(ThreadLocalLeakTest.java:80)
```

classloading.ThreadLocalLeakTest.testHazelcast[classLoaderType:OWN]
```
java.lang.AssertionError: Application created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@dd622dfd]) and a value of type [java.lang.Class] (value [class com.hazelcast.cache.impl.JCacheDetectorTest) but failed to remove it when the application was stopped.
	at org.junit.Assert.fail(Assert.java:88)
	at classloading.ThreadLocalLeakTestUtils.checkThreadLocalMapForLeaks(ThreadLocalLeakTestUtils.java:170)
	at classloading.ThreadLocalLeakTestUtils.checkThreadLocalsForLeaks(ThreadLocalLeakTestUtils.java:68)
	at classloading.ThreadLocalLeakTest.testHazelcast(ThreadLocalLeakTest.java:106)
```

Possibly related : https://github.com/hazelcast/hazelcast/pull/10218

**Comment by mmedenjak** [comment]
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK1.7/815/

**Comment by Donnerbart** [comment]
I changed the `ThreadLocalLeakTest` to a `NightlyTest` recently, so no new builds beside the ones using the `nightly-build` profile should be affected.

**Comment by mmedenjak** [comment]
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/1308/

**Comment by Donnerbart** [comment]
I disabled the `OWN` classloader yesterday, since it picks up test instances which are stored in `ThreadLocal` (maybe another mystery of the surefire plugin). It didn't fail last night anymore. To get the `OWN` classloader work reliably needs more work, but it's not my number one priority at the moment.

**Comment by Donnerbart** [comment]
Look like the test changes in April helped, no failures reported since then. Closing the issue.
