### ISSUE TITLE
[query-cache] QueryCacheMethodsWithPredicateTest.testKeySet_onIndexedField_whenIncludeValueFalse

### ISSUE THREAD

**Issue by mmedenjak** [hazelcast/hazelcast#10310]
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-ZuluJDK8/539/

```
java.lang.AssertionError: cache size = 144 expected:<195> but was:<121>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.map.impl.querycache.QueryCacheMethodsWithPredicateTest$1.run(QueryCacheMethodsWithPredicateTest.java:212)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:977)
	at com.hazelcast.map.impl.querycache.QueryCacheMethodsWithPredicateTest.assertKeySetSizeEventually(QueryCacheMethodsWithPredicateTest.java:216)
	at com.hazelcast.map.impl.querycache.QueryCacheMethodsWithPredicateTest.testKeySet_onIndexedField_whenIncludeValueFalse(QueryCacheMethodsWithPredicateTest.java:77)
```

**Comment by ahmetmircik** [comment]
updated Zulu and haven't seen this failure recently
