### ISSUE TITLE
Source parameter is null on JCache.loadAll() call

### ISSUE THREAD

**Issue by Donnerbart** [hazelcast/hazelcast#10328]
I'm adding new tests for the `loadAll()` methods of `JCache` and `IMap`: https://github.com/hazelcast/hazelcast/pull/10326

The `ClientCacheNearCacheBasicTest` fails on the method `whenLoadAllWithListenerIsUsed_thenNearCacheIsInvalidated_onDataAdapter()` and creates the following exceptions:
```java
java.lang.NullPointerException
	at com.hazelcast.client.impl.protocol.util.ParameterUtil.calculateDataSize(ParameterUtil.java:32)
	at com.hazelcast.client.impl.protocol.codec.CacheAddNearCacheInvalidationListenerCodec.encodeCacheBatchInvalidationEvent(CacheAddNearCacheInvalidationListenerCodec.java:168)
	at com.hazelcast.client.impl.protocol.task.cache.CacheAddNearCacheInvalidationListenerTask$NearCacheInvalidationListener.encodeBatchInvalidation(CacheAddNearCacheInvalidationListenerTask.java:63)
	at com.hazelcast.internal.nearcache.impl.invalidation.AbstractBaseNearCacheInvalidationListener.sendInvalidation(AbstractBaseNearCacheInvalidationListener.java:54)
	at com.hazelcast.client.impl.protocol.task.cache.AbstractCacheClientNearCacheInvalidationListener.handleEvent(AbstractCacheClientNearCacheInvalidationListener.java:47)
	at com.hazelcast.cache.impl.AbstractCacheService.dispatchEvent(AbstractCacheService.java:465)
	at com.hazelcast.cache.impl.AbstractCacheService.dispatchEvent(AbstractCacheService.java:65)
	at com.hazelcast.spi.impl.eventservice.impl.LocalEventDispatcher.run(LocalEventDispatcher.java:56)
	at com.hazelcast.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:221)
	at com.hazelcast.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:204)
```

The scenario is a member and client node, both configured with a simple `CacheLoader`. The client has a Near Cache configured, invalidations are enabled.. The `loadAll()` is invoked on the member:
```java
ICacheCompletionListener listener = new ICacheCompletionListener();
memberCache.loadAll(allKeys, true, listener);
listener.await();
```

```java
public class ICacheCacheLoader implements CacheLoader<Integer, String> {

    @Override
    public String load(Integer key) throws CacheLoaderException {
        return "newValue-" + key;
    }

    @Override
    public Map<Integer, String> loadAll(Iterable<? extends Integer> keys)
            throws CacheLoaderException {
        Map<Integer, String> entries = new HashMap<Integer, String>();
        for (Integer key : keys) {
            entries.put(key, "newValue-" + key);
        }
        return entries;
    }
}
```
```java
public class ICacheCompletionListener implements CompletionListener {

    private final CountDownLatch completed = new CountDownLatch(1);

    private volatile Exception exception;

    @Override
    public void onCompletion() {
        completed.countDown();
    }

    @Override
    public void onException(Exception e) {
        exception = e;
    }

    public void await() {
        HazelcastTestSupport.assertOpenEventually(completed);
        if (exception != null) {
            throw rethrow(exception);
        }
    }
}
```

**Comment by Donnerbart** [comment]
With the new assertion Ahmet added we have the source of the `null`:
```
java.lang.AssertionError
	at com.hazelcast.internal.nearcache.impl.invalidation.Invalidator.invalidateKey(Invalidator.java:70)
	at com.hazelcast.cache.impl.CacheEventHandler.sendInvalidationEvent(CacheEventHandler.java:126)
	at com.hazelcast.cache.impl.AbstractCacheService.sendInvalidationEvent(AbstractCacheService.java:695)
	at com.hazelcast.cache.impl.AbstractCacheRecordStore.invalidateEntry(AbstractCacheRecordStore.java:393)
	at com.hazelcast.cache.impl.AbstractCacheRecordStore.updateRecord(AbstractCacheRecordStore.java:652)
	at com.hazelcast.cache.impl.AbstractCacheRecordStore.updateRecordWithExpiry(AbstractCacheRecordStore.java:675)
	at com.hazelcast.cache.impl.AbstractCacheRecordStore.updateRecordWithExpiry(AbstractCacheRecordStore.java:716)
	at com.hazelcast.cache.impl.AbstractCacheRecordStore.updateRecordWithExpiry(AbstractCacheRecordStore.java:699)
	at com.hazelcast.cache.impl.AbstractCacheRecordStore.put(AbstractCacheRecordStore.java:1007)
	at com.hazelcast.cache.impl.AbstractCacheRecordStore.loadAll(AbstractCacheRecordStore.java:1393)
	at com.hazelcast.cache.impl.operation.CacheLoadAllOperation.run(CacheLoadAllOperation.java:93)
```

**Comment by pschmeltzer** [comment]
Application notes:

- Programmatic configured cluster and clients
- Cluster nodes may have beans which use local cache (without near cache)
- Clients have near cache configured on jcache instances like so:

```
for (String cache : caches) {
            NearCacheConfig nearCacheConfig = new NearCacheConfig(cache);
            nearCacheConfig.setInMemoryFormat(InMemoryFormat.OBJECT);
            EvictionConfig evictionConfig = new EvictionConfig();
            evictionConfig.setSize(size);
            config.addNearCacheConfig(nearCacheConfig);
        }
```

- Clients retrieve access to cache through jet:
`IStreamCache<K,V> jcache = instance.getCacheManager().getCache(name);`
- Cluster creates cache like:
```
CachingProvider cachingProvider = Caching.getCachingProvider(JetInstance.class.getClassLoader());
        Properties properties = new Properties();
        properties.put("hazelcast.instance.itself",server.getHazelcastInstance());
        CacheManager cacheManager = cachingProvider.getCacheManager(null, JetInstance.class.getClassLoader(), properties);
.....set other properties .....
jcache = cacheManager.createCache(name, config);
```

```
2018-02-28 15:52:01,904 [hz.ttcore.event-3] ERROR c.h.s.i.e.i.EventServiceImpl - [192.168.70.25]:18320 [ttcore] [0.5.1] hz.ttcore.event-3 caught an exception while processing task:com.hazelcast.spi.impl.eventservice.impl.LocalEventDispatcher@74e130af
java.lang.NullPointerException: null
        at com.hazelcast.client.impl.protocol.util.ParameterUtil.calculateDataSize(ParameterUtil.java:32) ~[hazelcast-3.9.1.jar:3.9.1]
        at com.hazelcast.client.impl.protocol.codec.CacheAddNearCacheInvalidationListenerCodec.encodeCacheBatchInvalidationEvent(CacheAddNearCacheInvalidationListenerCodec.java:169) ~[hazelcast-3.9.1.jar:3.9.1]
        at com.hazelcast.client.impl.protocol.task.cache.CacheAddNearCacheInvalidationListenerTask$NearCacheInvalidationListener.encodeBatchInvalidation(CacheAddNearCacheInvalidationListenerTask.java:63) ~[hazelcast-3.9.1.jar:3.9.1]
        at com.hazelcast.internal.nearcache.impl.invalidation.AbstractBaseNearCacheInvalidationListener.sendInvalidation(AbstractBaseNearCacheInvalidationListener.java:54) ~[hazelcast-3.9.1.jar:3.9.1]
        at com.hazelcast.client.impl.protocol.task.cache.AbstractCacheClientNearCacheInvalidationListener.handleEvent(AbstractCacheClientNearCacheInvalidationListener.java:47) ~[hazelcast-3.9.1.jar:3.9.1]
        at com.hazelcast.cache.impl.AbstractCacheService.dispatchEvent(AbstractCacheService.java:460) ~[hazelcast-3.9.1.jar:3.9.1]
        at com.hazelcast.cache.impl.AbstractCacheService.dispatchEvent(AbstractCacheService.java:70) ~[hazelcast-3.9.1.jar:3.9.1]
        at com.hazelcast.spi.impl.eventservice.impl.LocalEventDispatcher.run(LocalEventDispatcher.java:64) ~[hazelcast-3.9.1.jar:3.9.1]
        at com.hazelcast.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:225) [hazelcast-3.9.1.jar:3.9.1]
        at com.hazelcast.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:208) [hazelcast-3.9.1.jar:3.9.1]
```

**Comment by vbekiaris** [comment]
It seems the issue (or another way to trigger it) still exists in 3.9.3. Reopening this issue to investigate further.

**Comment by vbekiaris** [comment]
thanks @pschmeltzer for reporting this

**Comment by pschmeltzer** [comment]
Some notes on observing application logs.
Application doesn't replace cache values very often, so they only expire from the near cache when it hits the max local size?
It seems like this null pointer might be getting thrown in the cluster when a client has a miss on near cache and makes a call to the cluster.

Stack traces of client make it also appear that the cluster is calling cache loader when I expect it should have already had this value cached.

Client:
```
"main" #1 prio=5 os_prio=0 tid=0x00007f8f9c00b000 nid=0x2f2c waiting on condition [0x00007f8fa5277000]
   java.lang.Thread.State: TIMED_WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:338)
        at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:179)
        at com.hazelcast.client.util.ClientDelegatingFuture.get(ClientDelegatingFuture.java:137)
        at com.hazelcast.client.util.ClientDelegatingFuture.get(ClientDelegatingFuture.java:128)
        at com.hazelcast.client.cache.impl.AbstractClientCacheProxy.getSyncInternal(AbstractClientCacheProxy.java:88)
        at com.hazelcast.client.cache.impl.NearCachedClientCacheProxy.getSyncInternal(NearCachedClientCacheProxy.java:129)
        at com.hazelcast.client.cache.impl.AbstractClientCacheProxy.get(AbstractClientCacheProxy.java:212)
        at com.hazelcast.client.cache.impl.ClientCacheProxy.get(ClientCacheProxy.java:94)
        at com.hazelcast.client.cache.impl.ClientCacheProxy.get(ClientCacheProxy.java:130)
        at com.hazelcast.jet.stream.impl.CacheDecorator.get(CacheDecorator.java:226)
        at com.ttcore.caching.client.GenericHZClientCache.get(GenericHZClientCache.java:44)
      .... omitted ...
```

Cluster side:
```
"hz.ttcore.partition-operation.thread-2" #21 prio=5 os_prio=0 tid=0x00007f2e51143000 nid=0x2c34 runnable [0x00007f2df69ef000]
   java.lang.Thread.State: RUNNABLE
.... omitted ....
        at com.ttcore.caching.distributed.jcache.AccountCacheLoader.load(AccountCacheLoader.java:15)
        at com.hazelcast.cache.impl.AbstractCacheRecordStore.readThroughCache(AbstractCacheRecordStore.java:803)
        at com.hazelcast.cache.impl.AbstractCacheRecordStore.get(AbstractCacheRecordStore.java:966)
        at com.hazelcast.cache.impl.operation.CacheGetOperation.run(CacheGetOperation.java:50)
        at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:194)
        at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:406)
        at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:433)
        at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:569)
        at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:554)
        at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:513)
        at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:207)
        at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:60)
        at com.hazelcast.client.impl.protocol.task.AbstractPartitionMessageTask.processMessage(AbstractPartitionMessageTask.java:67)
        at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:123)
        at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:103)
        at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:154)
        at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:125)
        at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:100)

```

If these are being expired for some reason, then I don't know why.

Please be advised if this type of commentary isn't appropriate for this github project.

**Comment by mdogan** [comment]
I'm not able to reproduce the issue. But here what I found by just inspecting the code:

- `Invalidation` event defines `sourceUuid` field as nullable.
https://github.com/hazelcast/hazelcast/blob/01e78f0c09de3460b551526db00192ab193ace7c/hazelcast/src/main/java/com/hazelcast/internal/nearcache/impl/invalidation/Invalidation.java#L53-L58

- `List<String> sourceUuids` is extracted from a `BatchNearCacheInvalidation` event, which contains list of `Invalidation`s.
https://github.com/hazelcast/hazelcast/blob/01e78f0c09de3460b551526db00192ab193ace7c/hazelcast/src/main/java/com/hazelcast/internal/nearcache/impl/invalidation/AbstractBaseNearCacheInvalidationListener.java#L51-L55
https://github.com/hazelcast/hazelcast/blob/01e78f0c09de3460b551526db00192ab193ace7c/hazelcast/src/main/java/com/hazelcast/internal/nearcache/impl/invalidation/BatchNearCacheInvalidation.java#L29-L31

- That means `List<String> sourceUuids` may contain null items if `BatchNearCacheInvalidation` contains an `Invalidation` with null `sourceUuid`.

- Extracted parameters are encoded via `CacheAddNearCacheInvalidationListenerCodec.encodeCacheBatchInvalidationEvent(..)`. But it doesn't handle null items inside the collections. 

I don't know exactly which path leads to a null `sourceUuid` in an `Invalidation` event.

**Comment by pschmeltzer** [comment]
I am using a cache loader.
Dataset was larger than eviction size.
After increasing cache size to be larger than the underlying dataset size, errors are gone.
I can't do this indefinitely though.

It seems to be a combination perhaps of:

- Near cache on clients
- Dataset bigger than eviction size
- (Maybe) with a cache loader

**Comment by mdogan** [comment]
@pschmeltzer: I'm able to reproduce the issue with your combination.

**Comment by narayanan57** [comment]
hello i am not able to enable near cache for multiple caches using below method.First cache is only enabled with near cache.This runs into loop for the number of cache entry Names...
cachingProvider.getCacheManager(null, null, propertiesByInstanceItself(setHazelCastConfig())
protected HazelcastInstance setHazelCastConfig() {

        //TODO : Need to find a way to remove Hazelcast specific code
        ClientConfig clientConfig = new ClientConfig();
        String[] members = config.cluster().split(",");
        clientConfig.getNetworkConfig().addAddress(members);
        clientConfig.setInstanceName(cacheName);

        // Add near cache config if nearcache property is enabled
        if(configMap.hzlConfigs().isNearCacheEnabled().equalsIgnoreCase("enabled")) {
            NearCacheConfig nearCacheConfig = new NearCacheConfig()
                    .setTimeToLiveSeconds(configMap.hzlConfigs().nearCacheExpiry())
                    .setMaxIdleSeconds(configMap.hzlConfigs().nearCacheIdle())
                    .setLocalUpdatePolicy(NearCacheConfig.LocalUpdatePolicy.CACHE_ON_UPDATE)
                    .setEvictionConfig(new EvictionConfig()
                            .setSize(configMap.hzlConfigs().nearCacheEvictSize()))
                    .setName(cacheName);
            clientConfig.addNearCacheConfig(nearCacheConfig);
        }
        return HazelcastClient.newHazelcastClient(clientConfig);
    }

public Cache<Object, Object> createCache(CacheManager manager) {
        LOG.info("Logger at create cache hazelcast ---"+cacheName);
        com.hazelcast.config.CacheConfig hzConfig = new com.hazelcast.config.CacheConfig();
        hzConfig.setName(cacheName);
        hzConfig.setEvictionConfig(new EvictionConfig()
                        .setSize(configMap.evictionSize())
                        .setEvictionPolicy(EvictionPolicy.LRU))
                .setExpiryPolicyFactory(FactoryBuilder.factoryOf(
                        new AccessedExpiryPolicy( new Duration( TimeUnit.MINUTES, configMap.idle()))))
                .setTypes(Object.class, Object.class)
                .setManagementEnabled(true)
                .setStatisticsEnabled(true);
        return manager.createCache(cacheName, hzConfig);
    }
