### ISSUE TITLE
MigrationCommitTest test failures

### ISSUE THREAD

**Issue by mmedenjak** [hazelcast/hazelcast#10346]
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.8/560/

com.hazelcast.internal.partition.impl.MigrationCommitTest.shouldEvictCompletedMigrationsWhenAllMembersAckPublishedPartitionTableAfterSuccessfulMigration

```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.internal.partition.impl.MigrationCommitTest$4.run(MigrationCommitTest.java:398)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:976)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:993)
	at com.hazelcast.internal.partition.impl.MigrationCommitTest.shouldEvictCompletedMigrationsWhenAllMembersAckPublishedPartitionTableAfterSuccessfulMigration(MigrationCommitTest.java:395)
```

com.hazelcast.internal.partition.impl.MigrationCommitTest.shouldCommitMigrationWhenMasterCrashesAfterDestinationCommit

```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.internal.partition.impl.MigrationCommitTest$2.run(MigrationCommitTest.java:243)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:976)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:993)
	at com.hazelcast.internal.partition.impl.MigrationCommitTest.shouldCommitMigrationWhenMasterCrashesAfterDestinationCommit(MigrationCommitTest.java:239)
```

**Comment by mmedenjak** [comment]
Suspicion is slow environment, could be closed by https://github.com/hazelcast/hazelcast/pull/10343.

**Comment by Donnerbart** [comment]
Failed again in the PR builder:
```java
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.internal.partition.impl.MigrationCommitTest$2.run(MigrationCommitTest.java:264)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:992)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1009)
	at com.hazelcast.internal.partition.impl.MigrationCommitTest.shouldCommitMigrationWhenMasterCrashesAfterDestinationCommit(MigrationCommitTest.java:260)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/8405/testReport/junit/com.hazelcast.internal.partition.impl/MigrationCommitTest/shouldCommitMigrationWhenMasterCrashesAfterDestinationCommit/

**Comment by Donnerbart** [comment]
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.internal.partition.impl.MigrationCommitTest$2.run(MigrationCommitTest.java:264)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:992)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1009)
	at com.hazelcast.internal.partition.impl.MigrationCommitTest.shouldCommitMigrationWhenMasterCrashesAfterDestinationCommit(MigrationCommitTest.java:260)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/8510/testReport/junit/com.hazelcast.internal.partition.impl/MigrationCommitTest/shouldCommitMigrationWhenMasterCrashesAfterDestinationCommit/

**Comment by mmedenjak** [comment]
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.internal.partition.impl.MigrationCommitTest$4.run(MigrationCommitTest.java:448)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:992)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1009)
	at com.hazelcast.internal.partition.impl.MigrationCommitTest.shouldEvictCompletedMigrationsWhenAllMembersAckPublishedPartitionTableAfterSuccessfulMigration(MigrationCommitTest.java:445)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.7/1269/

**Comment by Donnerbart** [comment]
```java
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.internal.partition.impl.MigrationCommitTest$4.run(MigrationCommitTest.java:422)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1037)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1054)
	at com.hazelcast.internal.partition.impl.MigrationCommitTest.shouldEvictCompletedMigrationsWhenAllMembersAckPublishedPartitionTableAfterSuccessfulMigration(MigrationCommitTest.java:419)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/8896/testReport/junit/com.hazelcast.internal.partition.impl/MigrationCommitTest/shouldEvictCompletedMigrationsWhenAllMembersAckPublishedPartitionTableAfterSuccessfulMigration/

**Comment by hasancelik** [comment]
**shouldEvictCompletedMigrationsWhenAllMembersAckPublishedPartitionTableAfterSuccessfulMigration**
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.internal.partition.impl.MigrationCommitTest$4.run(MigrationCommitTest.java:422)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1037)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1054)
	at com.hazelcast.internal.partition.impl.MigrationCommitTest.shouldEvictCompletedMigrationsWhenAllMembersAckPublishedPartitionTableAfterSuccessfulMigration(MigrationCommitTest.java:419)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-freestyle/512/testReport/junit/com.hazelcast.internal.partition.impl/MigrationCommitTest/shouldEvictCompletedMigrationsWhenAllMembersAckPublishedPartitionTableAfterSuccessfulMigration/
