### ISSUE TITLE
HDMapNearCacheBasicTest test failures

### ISSUE THREAD

**Issue by mmedenjak** [hazelcast/hazelcast#10368]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-ee-OracleJDK8/721/#showFailuresLink

com.hazelcast.map.impl.nearcache.HDMapNearCacheBasicTest.whenRemoveAllIsUsed_thenNearCacheShouldBeInvalidated_onDataAdapter[format:BINARY]
com.hazelcast.map.impl.nearcache.HDMapNearCacheBasicTest.whenRemoveAllIsUsed_thenNearCacheShouldBeInvalidated_onDataAdapter[format:OBJECT]
com.hazelcast.map.impl.nearcache.HDMapNearCacheBasicTest.whenRemoveAllIsUsed_thenNearCacheShouldBeInvalidated_onDataAdapter[format:NATIVE]

```
java.lang.AssertionError: Invalidation is not working on removeAll() Near Cache size didn't reach the desired value (0 vs. 1) (NearCacheStatsImpl{ownedEntryCount=1, ownedEntryMemoryCost=149, creationTime=1492406549120, hits=0, misses=1000, ratio=0.0%, evictions=0, expirations=0, lastPersistenceTime=0, persistenceCount=0, lastPersistenceDuration=0, lastPersistenceWrittenBytes=0, lastPersistenceKeyCount=0, lastPersistenceFailure=''}) expected:<0> but was:<1>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils.assertNearCacheSize(NearCacheTestUtils.java:259)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils$2.run(NearCacheTestUtils.java:279)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:992)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1009)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils.assertNearCacheSizeEventually(NearCacheTestUtils.java:276)
	at com.hazelcast.internal.nearcache.AbstractNearCacheBasicTest.whenEntryIsRemoved_thenNearCacheShouldBeInvalidated(AbstractNearCacheBasicTest.java:711)
	at com.hazelcast.internal.nearcache.AbstractNearCacheBasicTest.whenRemoveAllIsUsed_thenNearCacheShouldBeInvalidated_onDataAdapter(AbstractNearCacheBasicTest.java:649)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by mmedenjak** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-ee-OracleJDK8/719/

**Comment by mmedenjak** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-ee-OracleJDK8/720/#showFailuresLink

**Comment by mmedenjak** [comment]
Moving to EE
