### ISSUE TITLE
HDMapNearCacheSerializationCountTest test failures

### ISSUE THREAD

**Issue by mmedenjak** [hazelcast/hazelcast#10369]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-ee-OracleJDK8/719/

com.hazelcast.map.impl.nearcache.HDMapNearCacheSerializationCountTest.testSerializationCounts[mapFormat:OBJECT nearCacheFormat:null]
com.hazelcast.map.impl.nearcache.HDMapNearCacheSerializationCountTest.testSerializationCounts[mapFormat:OBJECT nearCacheFormat:NATIVE]
com.hazelcast.map.impl.nearcache.HDMapNearCacheSerializationCountTest.testSerializationCounts[mapFormat:OBJECT nearCacheFormat:BINARY]
com.hazelcast.map.impl.nearcache.HDMapNearCacheSerializationCountTest.testSerializationCounts[mapFormat:OBJECT nearCacheFormat:OBJECT]

```
java.lang.AssertionError: deserializeCount on put(): expected 2, but was 1
[com.hazelcast.nio.serialization.HazelcastSerializationException: invoked deserialization
	at com.hazelcast.internal.nearcache.AbstractNearCacheSerializationCountTest$SerializationCountingData.getStackTrace(AbstractNearCacheSerializationCountTest.java:194)
	at com.hazelcast.internal.nearcache.AbstractNearCacheSerializationCountTest$SerializationCountingData.readPortable(AbstractNearCacheSerializationCountTest.java:188)
	at com.hazelcast.internal.serialization.impl.PortableSerializer.read(PortableSerializer.java:92)
	at com.hazelcast.internal.serialization.impl.PortableSerializer.read(PortableSerializer.java:81)
	at com.hazelcast.internal.serialization.impl.PortableSerializer.read(PortableSerializer.java:34)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:184)
	at com.hazelcast.map.impl.record.ObjectRecordFactory.newRecord(ObjectRecordFactory.java:37)
	at com.hazelcast.map.impl.recordstore.AbstractRecordStore.createRecord(AbstractRecordStore.java:96)
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.createRecord(DefaultRecordStore.java:73)
	at com.hazelcast.map.impl.recordstore.EnterpriseRecordStore.createRecordInternal(EnterpriseRecordStore.java:125)
	at com.hazelcast.map.impl.recordstore.EnterpriseRecordStore.createRecord(EnterpriseRecordStore.java:121)
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.putInternal(DefaultRecordStore.java:766)
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.put(DefaultRecordStore.java:750)
	at com.hazelcast.map.impl.operation.PutOperation.run(PutOperation.java:33)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:194)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:122)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:102)
] expected:<2> but was:<1>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.internal.nearcache.AbstractNearCacheSerializationCountTest.assertAndReset(AbstractNearCacheSerializationCountTest.java:156)
	at com.hazelcast.internal.nearcache.AbstractNearCacheSerializationCountTest.testSerializationCounts(AbstractNearCacheSerializationCountTest.java:121)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
```

Related : https://github.com/hazelcast/hazelcast/pull/10194

**Comment by mmedenjak** [comment]
Moving to EE
