### ISSUE TITLE
[ZING] MembershipFailureTest_withTCP Failures

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#10364]
**MembershipFailureTest_withTCP.test_whenNodesStartedTerminatedConcurrently**
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.internal.cluster.impl.MembershipFailureTest.startInstancesConcurrently(MembershipFailureTest.java:797)
	at com.hazelcast.internal.cluster.impl.MembershipFailureTest.test_whenNodesStartedTerminatedConcurrently(MembershipFailureTest.java:774)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:622)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.lang.Thread.run(Thread.java:701)
```

https://hazelcast-l337.ci.cloudbees.com/view/Zing/job/Hazelcast-3.x-ZingJDK6/lastCompletedBuild/testReport/junit/com.hazelcast.internal.cluster.impl/MembershipFailureTest_withTCP/test_whenNodesStartedTerminatedConcurrently/

**Comment by hasancelik** [comment]
**MembershipFailureTest_withTCP.secondMastershipClaimByYounger_shouldRetry_when_firstMastershipClaimByElder_accepted**
```
java.lang.AssertionError: expected:<[127.0.0.1]:5702> but was:<[127.0.0.1]:5701>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.test.HazelcastTestSupport.assertMasterAddress(HazelcastTestSupport.java:895)
	at com.hazelcast.test.HazelcastTestSupport$13.run(HazelcastTestSupport.java:905)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1037)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1054)
	at com.hazelcast.test.HazelcastTestSupport.assertMasterAddressEventually(HazelcastTestSupport.java:900)
	at com.hazelcast.internal.cluster.impl.MembershipFailureTest.secondMastershipClaimByYounger_shouldRetry_when_firstMastershipClaimByElder_accepted(MembershipFailureTest.java:641)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.lang.Thread.run(Thread.java:745)
```

https://hazelcast-l337.ci.cloudbees.com/view/Zing/job/Hazelcast-3.x-ZingJDK7/lastCompletedBuild/testReport/com.hazelcast.internal.cluster.impl/MembershipFailureTest_withTCP/secondMastershipClaimByYounger_shouldRetry_when_firstMastershipClaimByElder_accepted/

**Comment by metanet** [comment]
failure logs: [master.txt](https://github.com/hazelcast/hazelcast/files/1001390/master.txt)

**Comment by metanet** [comment]
Failed before recent fixes on May 15. Closing this one. We can re-open it if fails again
