### ISSUE TITLE
Near Cache size didn't reach the desired value (off-by-one)

### ISSUE THREAD

**Issue by mmedenjak** [hazelcast/hazelcast#10389]
**com.hazelcast.client.map.impl.nearcache.ClientMapNearCacheBasicTest.whenNearCacheIsFull_thenPutOnSameKeyShouldUpdateValue_onDataAdapter[format:BINARY]**
```
java.lang.AssertionError: Near Cache size didn't reach the desired value (499 vs. 500) (NearCacheStatsImpl{ownedEntryCount=500, ownedEntryMemoryCost=74443, creationTime=1492640495276, hits=0, misses=1001, ratio=0.0%, evictions=0, expirations=0, lastPersistenceTime=0, persistenceCount=0, lastPersistenceDuration=0, lastPersistenceWrittenBytes=0, lastPersistenceKeyCount=0, lastPersistenceFailure=''}) expected:<499> but was:<500>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils.assertNearCacheSize(NearCacheTestUtils.java:271)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils$2.run(NearCacheTestUtils.java:291)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:992)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1009)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils.assertNearCacheSizeEventually(NearCacheTestUtils.java:288)
	at com.hazelcast.internal.nearcache.AbstractNearCacheBasicTest.whenNearCacheIsFull_thenPutOnSameKeyShouldUpdateValue(AbstractNearCacheBasicTest.java:1036)
	at com.hazelcast.internal.nearcache.AbstractNearCacheBasicTest.whenNearCacheIsFull_thenPutOnSameKeyShouldUpdateValue_onDataAdapter(AbstractNearCacheBasicTest.java:1008)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.lang.Thread.run(Thread.java:662)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/8411/testReport/junit/com.hazelcast.client.map.impl.nearcache/ClientMapNearCacheBasicTest/whenNearCacheIsFull_thenPutOnSameKeyShouldUpdateValue_onDataAdapter_format_BINARY_/

**Comment by Donnerbart** [comment]
Similar failure here:

**com.hazelcast.client.map.impl.nearcache.ClientHDMapNearCacheBasicTest.testNearCacheMemoryCostCalculation[format:BINARY]**
```
java.lang.AssertionError: Near Cache size didn't reach the desired value (1000 vs. 999) (NearCacheStatsImpl{ownedEntryCount=999, ownedEntryMemoryCost=148743, creationTime=1492574657097, hits=0, misses=1000, ratio=0.0%, evictions=0, expirations=0, lastPersistenceTime=0, persistenceCount=0, lastPersistenceDuration=0, lastPersistenceWrittenBytes=0, lastPersistenceKeyCount=0, lastPersistenceFailure=''}) expected:<1000> but was:<999>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils.assertNearCacheSize(NearCacheTestUtils.java:271)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils$2.run(NearCacheTestUtils.java:291)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:992)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1009)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils.assertNearCacheSizeEventually(NearCacheTestUtils.java:288)
	at com.hazelcast.internal.nearcache.AbstractNearCacheBasicTest.testNearCacheMemoryCostCalculation(AbstractNearCacheBasicTest.java:959)
	at com.hazelcast.internal.nearcache.AbstractNearCacheBasicTest.testNearCacheMemoryCostCalculation(AbstractNearCacheBasicTest.java:924)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
```
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Enterprise/job/Hazelcast-ee-ZuluJDK8/296/com.hazelcast$hazelcast-enterprise-client/testReport/com.hazelcast.client.map.impl.nearcache/ClientHDMapNearCacheBasicTest/testNearCacheMemoryCostCalculation_format_BINARY_/

**Comment by mmedenjak** [comment]
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-ZuluJDK7/com.hazelcast$hazelcast-client/550/

**Comment by mmedenjak** [comment]
Same on replicated map : 
com.hazelcast.client.replicatedmap.nearcache.ClientReplicatedMapNearCacheBasicTest.testNearCacheMemoryCostCalculation[format:BINARY]

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK1.7/com.hazelcast$hazelcast-client/836/

**Comment by hasancelik** [comment]
```
ava.lang.AssertionError: Near Cache size didn't reach the desired value (499 vs. 500) (NearCacheStatsImpl{ownedEntryCount=500, ownedEntryMemoryCost=74394, creationTime=1492994421033, hits=0, misses=1001, ratio=0.0%, evictions=0, expirations=0, lastPersistenceTime=0, persistenceCount=0, lastPersistenceDuration=0, lastPersistenceWrittenBytes=0, lastPersistenceKeyCount=0, lastPersistenceFailure=''}) expected:<499> but was:<500>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils.assertNearCacheSize(NearCacheTestUtils.java:271)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils$2.run(NearCacheTestUtils.java:291)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:992)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1009)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils.assertNearCacheSizeEventually(NearCacheTestUtils.java:288)
	at com.hazelcast.internal.nearcache.AbstractNearCacheBasicTest.whenNearCacheIsFull_thenPutOnSameKeyShouldUpdateValue(AbstractNearCacheBasicTest.java:1036)
	at com.hazelcast.internal.nearcache.AbstractNearCacheBasicTest.whenNearCacheIsFull_thenPutOnSameKeyShouldUpdateValue_onDataAdapter(AbstractNearCacheBasicTest.java:1008)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.lang.Thread.run(Thread.java:745)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-ZuluJDK7/com.hazelcast$hazelcast-client/550/testReport/junit/com.hazelcast.client.map.impl.nearcache/ClientMapNearCacheBasicTest/whenNearCacheIsFull_thenPutOnSameKeyShouldUpdateValue_onDataAdapter_format_BINARY_/

**Comment by Donnerbart** [comment]
Looks like we have the issue with more than an off-by-one error as well:
```java
java.lang.AssertionError: Near Cache size didn't reach the desired value (1000 vs. 977) (NearCacheStatsImpl{ownedEntryCount=977, ownedEntryMemoryCost=145463, creationTime=1493993474069, hits=5268, misses=1079, ratio=488.2%, evictions=0, expirations=0, lastPersistenceTime=0, persistenceCount=0, lastPersistenceDuration=0, lastPersistenceWrittenBytes=0, lastPersistenceKeyCount=0, lastPersistenceFailure=''}) expected:<1000> but was:<977>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils.assertNearCacheSize(NearCacheTestUtils.java:273)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils$2.run(NearCacheTestUtils.java:293)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1003)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1020)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils.assertNearCacheSizeEventually(NearCacheTestUtils.java:290)
	at com.hazelcast.internal.nearcache.AbstractNearCacheBasicTest.testNearCacheMemoryCostCalculation(AbstractNearCacheBasicTest.java:979)
	at com.hazelcast.internal.nearcache.AbstractNearCacheBasicTest.testNearCacheMemoryCostCalculation_withConcurrentCacheMisses(AbstractNearCacheBasicTest.java:954)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.lang.Thread.run(Thread.java:662)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/8712/testReport/junit/com.hazelcast.map.impl.nearcache/MapNearCacheBasicTest/testNearCacheMemoryCostCalculation_withConcurrentCacheMisses_format_BINARY_/
