### ISSUE TITLE
ClientMapIssueTest

### ISSUE THREAD

**Issue by Donnerbart** [hazelcast/hazelcast#10400]
**com.hazelcast.client.map.ClientMapIssueTest.testNoOperationTimeoutException_whenUserCodeLongRunning**
```java
com.hazelcast.core.OperationTimeoutException: EntryOperation invocation failed to complete due to operation-heartbeat-timeout. Current time: 2017-04-20 12:41:18.212. Start time: 2017-04-20 12:41:08.208. Total elapsed time: 10004 ms. Last operation heartbeat: 2017-04-20 12:41:11.224. Last operation heartbeat from member: 2017-04-20 12:41:17.222. Invocation{op=com.hazelcast.map.impl.operation.EntryOperation{serviceName='hz:impl:mapService', identityHash=134585789, partitionId=232, replicaIndex=0, callId=-4, invocationTime=1492692068208 (2017-04-20 12:41:08.208), waitTimeout=-1, callTimeout=2000, name=b9c91e06-643c-4078-876b-028128190d0b}, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=2000, firstInvocationTimeMs=1492692068208, firstInvocationTime='2017-04-20 12:41:08.208', lastHeartbeatMillis=1492692071224, lastHeartbeatTime='2017-04-20 12:41:11.224', target=[127.0.0.1]:5003, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=null}
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.newOperationTimeoutException(InvocationFuture.java:157)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:104)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run(AbstractInvocationFuture.java:243)
	at com.hazelcast.client.impl.protocol.task.AbstractPartitionMessageTask.execute(AbstractPartitionMessageTask.java:78)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.unblock(AbstractInvocationFuture.java:239)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.andThen(AbstractInvocationFuture.java:215)
	at com.hazelcast.client.impl.protocol.task.AbstractPartitionMessageTask.processMessage(AbstractPartitionMessageTask.java:69)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:123)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:103)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:154)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:127)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:102)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:93)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:33)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:155)
	at com.hazelcast.client.spi.ClientProxy.invokeOnPartition(ClientProxy.java:154)
	at com.hazelcast.client.spi.ClientProxy.invoke(ClientProxy.java:148)
	at com.hazelcast.client.proxy.ClientMapProxy.executeOnKeyInternal(ClientMapProxy.java:1247)
	at com.hazelcast.client.proxy.ClientMapProxy.executeOnKey(ClientMapProxy.java:1241)
	at com.hazelcast.client.map.ClientMapIssueTest.testNoOperationTimeoutException_whenUserCodeLongRunning(ClientMapIssueTest.java:350)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/8429/testReport/junit/com.hazelcast.client.map/ClientMapIssueTest/testNoOperationTimeoutException_whenUserCodeLongRunning/

**Comment by ihsandemir** [comment]
I examined the logs. We see these:

```
12:41:07,829  INFO |testNoOperationTimeoutException_whenUserCodeLongRunning| - [LifecycleService] testNoOperationTimeoutException_whenUserCodeLongRunning - hz.client_1 [dev] [3.9-SNAPSHOT] HazelcastClient 3.9-SNAPSHOT (20170420 - c4f91f9) is CLIENT_CONNECTED
12:41:08,045  INFO |testNoOperationTimeoutException_whenUserCodeLongRunning| - [PartitionStateManager] hz._hzInstance_3_dev.priority-generic-operation.thread-0 - [127.0.0.1]:5003 [dev] [3.9-SNAPSHOT] Initializing cluster partition table arrangement...
12:41:13,349  INFO |testNoOperationTimeoutException_whenUserCodeLongRunning| - [InvocationMonitor] hz._hzInstance_3_dev.InvocationMonitorThread - [127.0.0.1]:5003 [dev] [3.9-SNAPSHOT] Invocations:1 timeouts:1 backup-timeouts:0
12:41:18,211  WARN |testNoOperationTimeoutException_whenUserCodeLongRunning| - [Invocation] hz._hzInstance_3_dev.partition-operation.thread-16 - [127.0.0.1]:5003 [dev] [3.9-SNAPSHOT] Future.complete(Object) on completed future. Request: Invocation{op=com.hazelcast.map.impl.operation.EntryOperation{serviceName='hz:impl:mapService', identityHash=134585789, partitionId=232, replicaIndex=0, callId=-4, invocationTime=1492692068208 (2017-04-20 12:41:08.208), waitTimeout=-1, callTimeout=2000, name=b9c91e06-643c-4078-876b-028128190d0b}, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=2000, firstInvocationTimeMs=1492692068208, firstInvocationTime='2017-04-20 12:41:08.208', lastHeartbeatMillis=1492692071224, lastHeartbeatTime='2017-04-20 12:41:11.224', target=[127.0.0.1]:5003, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=null}, current value: Invocation::HEARTBEAT_TIMEOUT, offered value: HeapData{type=-11, hashCode=-1017440648, partitionHash=-1017440648, totalSize=48, dataSize=40, heapCost=68}
THREAD DUMP FOR TEST FAILURE: "EntryOperation invocation failed to complete due to operation-heartbeat-timeout. Current time: 2017-04-20 12:41:18.212. Start time: 2017-04-20 12:41:08.208. Total elapsed time: 10004 ms. Last operation heartbeat: 2017-04-20 12:41:11.224. Last operation heartbeat from member: 2017-04-20 12:41:17.222. Invocation{op=com.hazelcast.map.impl.operation.EntryOperation{serviceName='hz:impl:mapService', identityHash=134585789, partitionId=232, replicaIndex=0, callId=-4, invocationTime=1492692068208 (2017-04-20 12:41:08.208), waitTimeout=-1, callTimeout=2000, name=b9c91e06-643c-4078-876b-028128190d0b}, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=2000, firstInvocationTimeMs=1492692068208, firstInvocationTime='2017-04-20 12:41:08.208', lastHeartbeatMillis=1492692071224, lastHeartbeatTime='2017-04-20 12:41:11.224', target=[127.0.0.1]:5003, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=null}" at "testNoOperationTimeoutException_whenUserCodeLongRunning"
```
6 seconds after the client ıs connected, it wrote the number of timeouts as 1 at 12:41:13,349. The timeout was set to 2 seconds, hence if no heartbeat is received ınıtıally for 2 + 2 = 4 seconds, operation will heartbeat timeout as seen here: https://github.com/hazelcast/hazelcast/blob/v3.8.2/hazelcast/src/main/java/com/hazelcast/spi/impl/operationservice/impl/Invocation.java#L412

The operation service sends 4 heartbeats every heartbeat duration (i.e. 0.5 seconds in this case). But for any reason that this is delayed and lastHeartbeatMillis was never set, then this may cause operation heartbeat fail as logged as Invocation::HEARTBEAT_TIMEOUT.

**Comment by sancar** [comment]
fixed via https://github.com/hazelcast/hazelcast/pull/10701
