### ISSUE TITLE
ClientRegressionWithMockNetworkTest failures

### ISSUE THREAD

**Issue by mmedenjak** [hazelcast/hazelcast#10410]
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/1319/

com.hazelcast.client.ClientRegressionWithMockNetworkTest.testLock_WhenSmartClientAndOwnerNodeDiesTogether

```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.client.ClientRegressionWithMockNetworkTest.testLock_WhenClientAndOwnerNodeDiesTogether(ClientRegressionWithMockNetworkTest.java:534)
	at com.hazelcast.client.ClientRegressionWithMockNetworkTest.testLock_WhenSmartClientAndOwnerNodeDiesTogether(ClientRegressionWithMockNetworkTest.java:520)
```

com.hazelcast.client.ClientRegressionWithMockNetworkTest.testLock_WhenDummyClientAndOwnerNodeDiesTogether

```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.client.ClientRegressionWithMockNetworkTest.testLock_WhenClientAndOwnerNodeDiesTogether(ClientRegressionWithMockNetworkTest.java:534)
	at com.hazelcast.client.ClientRegressionWithMockNetworkTest.testLock_WhenDummyClientAndOwnerNodeDiesTogether(ClientRegressionWithMockNetworkTest.java:514)
```

**Comment by mmedenjak** [comment]
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/1321

**Comment by mmedenjak** [comment]
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast-client/1322/

**Comment by mmedenjak** [comment]
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/1325/

**Comment by mmedenjak** [comment]
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/1323/#showFailuresLink

**Comment by mmedenjak** [comment]
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/1324/#showFailuresLink

**Comment by hasancelik** [comment]
**testLock_WhenDummyClientAndOwnerNodeDiesTogether
testLock_WhenSmartClientAndOwnerNodeDiesTogether**

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/1329/#showFailuresLink

**Comment by hasancelik** [comment]
*maintenance*
```
java.lang.AssertionError: CountDownLatch failed to complete within 120 seconds, count left: 1
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:1012)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:1005)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:997)
	at com.hazelcast.client.ClientRegressionWithMockNetworkTest.testDeadlock_whenDoingOperationFromLifecycleListener_withNearCache(ClientRegressionWithMockNetworkTest.java:655)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-ZuluJDK6-freestyle/95/testReport/junit/com.hazelcast.client/ClientRegressionWithMockNetworkTest/testDeadlock_whenDoingOperationFromLifecycleListener_withNearCache/
