### ISSUE TITLE
Hazelcast client not connecting to 5704 port 

### ISSUE THREAD

**Issue by pavan2017** [hazelcast/hazelcast#10412]
I am trying test hazelcast for our test environment .The Hazelcast client is not able to connect to 5704 port even there is host up and running on 5704.Client is able to scan only for 5701,5702,5703.I have tried both TCP and multicast config .Even i tried supplying "**hazelcast.tcp.join.port.try.count**" as system property

[HCServer.txt](https://github.com/hazelcast/hazelcast/files/946834/HCServer.txt)
[HCClient.txt](https://github.com/hazelcast/hazelcast/files/946835/HCClient.txt)

The attached two programs reproduces this.
Start HCServer with 4 different group names as command line argument 
Start HCClient and provide the groupname same as 4th group name

The following is the error 

WARNING: hz.client_0 [dev] [3.7.4] Exception during initial connection to localhost/127.0.0.1:5701
com.hazelcast.client.AuthenticationException: Invalid credentials!
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl$2.onResponse(ClientConnectionManagerImpl.java:525)
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl$2.onResponse(ClientConnectionManagerImpl.java:507)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run(AbstractInvocationFuture.java:251)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)

Apr 21, 2017 12:49:00 PM com.hazelcast.client.connection.nio.ClientConnection
WARNING: hz.client_0 [dev] [3.7.4] ClientConnection{live=false, connectionId=2, socketChannel=DefaultSocketChannelWrapper{socketChannel=java.nio.channels.SocketChannel[connected local=/127.0.0.1:63143 remote=/127.0.0.1:5702]}, remoteEndpoint=null, lastReadTime=2017-04-21 12:49:00.950, lastWriteTime=2017-04-21 12:49:00.836, closedTime=2017-04-21 12:49:00.961, lastHeartbeatRequested=never, lastHeartbeatReceived=never, connected server version=null} lost. Reason: com.hazelcast.client.AuthenticationException[Invalid credentials!]
Apr 21, 2017 12:49:00 PM com.hazelcast.client.spi.impl.ClusterListenerSupport
WARNING: hz.client_0 [dev] [3.7.4] Exception during initial connection to localhost/127.0.0.1:5702
com.hazelcast.client.AuthenticationException: Invalid credentials!
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl$2.onResponse(ClientConnectionManagerImpl.java:525)
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl$2.onResponse(ClientConnectionManagerImpl.java:507)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run(AbstractInvocationFuture.java:251)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)

Apr 21, 2017 12:49:01 PM com.hazelcast.client.connection.nio.ClientConnection
WARNING: hz.client_0 [dev] [3.7.4] ClientConnection{live=false, connectionId=3, socketChannel=DefaultSocketChannelWrapper{socketChannel=java.nio.channels.SocketChannel[connected local=/127.0.0.1:63144 remote=/127.0.0.1:5703]}, remoteEndpoint=null, lastReadTime=2017-04-21 12:49:01.146, lastWriteTime=2017-04-21 12:49:00.970, closedTime=2017-04-21 12:49:01.147, lastHeartbeatRequested=never, lastHeartbeatReceived=never, connected server version=null} lost. Reason: com.hazelcast.client.AuthenticationException[Invalid credentials!]
Apr 21, 2017 12:49:01 PM com.hazelcast.client.spi.impl.ClusterListenerSupport
WARNING: hz.client_0 [dev] [3.7.4] Exception during initial connection to localhost/127.0.0.1:5703
com.hazelcast.client.AuthenticationException: Invalid credentials!
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl$2.onResponse(ClientConnectionManagerImpl.java:525)
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl$2.onResponse(ClientConnectionManagerImpl.java:507)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run(AbstractInvocationFuture.java:251)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)

Apr 21, 2017 12:49:01 PM com.hazelcast.client.spi.impl.ClusterListenerSupport
WARNING: hz.client_0 [dev] [3.7.4] Unable to get alive cluster connection, try in 2388 ms later, attempt 1 of 2.
Apr 21, 2017 12:49:03 PM com.hazelcast.client.connection.nio.ClientConnection
WARNING: hz.client_0 [dev] [3.7.4] ClientConnection{live=false, connectionId=4, socketChannel=DefaultSocketChannelWrapper{socketChannel=java.nio.channels.SocketChannel[connected local=/127.0.0.1:63145 remote=/127.0.0.1:5702]}, remoteEndpoint=null, lastReadTime=2017-04-21 12:49:03.567, lastWriteTime=2017-04-21 12:49:03.560, closedTime=2017-04-21 12:49:03.579, lastHeartbeatRequested=never, lastHeartbeatReceived=never, connected server version=null} lost. Reason: com.hazelcast.client.AuthenticationException[Invalid credentials!]
Apr 21, 2017 12:49:03 PM com.hazelcast.client.spi.impl.ClusterListenerSupport
WARNING: hz.client_0 [dev] [3.7.4] Exception during initial connection to localhost/127.0.0.1:5702
com.hazelcast.client.AuthenticationException: Invalid credentials!
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl$2.onResponse(ClientConnectionManagerImpl.java:525)
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl$2.onResponse(ClientConnectionManagerImpl.java:507)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run(AbstractInvocationFuture.java:251)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)

Apr 21, 2017 12:49:03 PM com.hazelcast.client.connection.nio.ClientConnection
WARNING: hz.client_0 [dev] [3.7.4] ClientConnection{live=false, connectionId=5, socketChannel=DefaultSocketChannelWrapper{socketChannel=java.nio.channels.SocketChannel[connected local=/127.0.0.1:63146 remote=/127.0.0.1:5701]}, remoteEndpoint=null, lastReadTime=2017-04-21 12:49:03.613, lastWriteTime=2017-04-21 12:49:03.600, closedTime=2017-04-21 12:49:03.618, lastHeartbeatRequested=never, lastHeartbeatReceived=never, connected server version=null} lost. Reason: com.hazelcast.client.AuthenticationException[Invalid credentials!]
Apr 21, 2017 12:49:03 PM com.hazelcast.client.spi.impl.ClusterListenerSupport
WARNING: hz.client_0 [dev] [3.7.4] Exception during initial connection to localhost/127.0.0.1:5701
com.hazelcast.client.AuthenticationException: Invalid credentials!
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl$2.onResponse(ClientConnectionManagerImpl.java:525)
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl$2.onResponse(ClientConnectionManagerImpl.java:507)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run(AbstractInvocationFuture.java:251)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)

Apr 21, 2017 12:49:03 PM com.hazelcast.client.connection.nio.ClientConnection
WARNING: hz.client_0 [dev] [3.7.4] ClientConnection{live=false, connectionId=6, socketChannel=DefaultSocketChannelWrapper{socketChannel=java.nio.channels.SocketChannel[connected local=/127.0.0.1:63147 remote=/127.0.0.1:5703]}, remoteEndpoint=null, lastReadTime=2017-04-21 12:49:03.646, lastWriteTime=2017-04-21 12:49:03.635, closedTime=2017-04-21 12:49:03.653, lastHeartbeatRequested=never, lastHeartbeatReceived=never, connected server version=null} lost. Reason: com.hazelcast.client.AuthenticationException[Invalid credentials!]
Apr 21, 2017 12:49:03 PM com.hazelcast.client.spi.impl.ClusterListenerSupport
WARNING: hz.client_0 [dev] [3.7.4] Exception during initial connection to localhost/127.0.0.1:5703
com.hazelcast.client.AuthenticationException: Invalid credentials!
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl$2.onResponse(ClientConnectionManagerImpl.java:525)
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl$2.onResponse(ClientConnectionManagerImpl.java:507)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run(AbstractInvocationFuture.java:251)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)

Apr 21, 2017 12:49:03 PM com.hazelcast.client.spi.impl.ClusterListenerSupport
WARNING: hz.client_0 [dev] [3.7.4] Unable to get alive cluster connection, try in 2880 ms later, attempt 2 of 2.
Apr 21, 2017 12:49:06 PM com.hazelcast.core.LifecycleService
INFO: hz.client_0 [dev] [3.7.4] HazelcastClient 3.7.4 (20161209 - 3df1bb5) is SHUTTING_DOWN
Apr 21, 2017 12:49:06 PM com.hazelcast.core.LifecycleService
INFO: hz.client_0 [dev] [3.7.4] HazelcastClient 3.7.4 (20161209 - 3df1bb5) is SHUTDOWN
Exception in thread "main" java.lang.IllegalStateException: Unable to connect to any address in the config! The following addresses were tried:[localhost/127.0.0.1:5701, localhost/127.0.0.1:5702, localhost/127.0.0.1:5703]
	at com.hazelcast.client.spi.impl.ClusterListenerSupport.connectToCluster(ClusterListenerSupport.java:174)
	at com.hazelcast.client.spi.impl.ClientClusterServiceImpl.start(ClientClusterServiceImpl.java:191)
	at com.hazelcast.client.impl.HazelcastClientInstanceImpl.start(HazelcastClientInstanceImpl.java:379)
	at com.hazelcast.client.HazelcastClientManager.newHazelcastClient(HazelcastClientManager.java:78)
	at com.hazelcast.client.HazelcastClientManager.newHazelcastClient(HazelcastClientManager.java:60)
	at com.hazelcast.client.HazelcastClient.newHazelcastClient(HazelcastClient.java:68)
	at com.edb.fs.enterprise.ctp.grid.app.HcClient.main(HcClient.java:12)

**Comment by jerrinot** [comment]
hi @pavan2017,

can you try to add
```java
clientConfig.getNetworkConfig().addAddress("localhost:5704")
```
to your test code?

**Comment by pavan2017** [comment]
Yeah that works.But how this works if the individual nodes goes up.I need to add 5705,5706 and so on.
I am expecting a configurable solution for this like "**hazelcast.tcp.join.port.try.count**"

**Comment by pavan2017** [comment]
Is it possible to configure this through some property?.I think this should be possible

**Comment by jerrinot** [comment]
right now it's hard-coded to 3 on the client side. this sounds like a valid feature-request.
@asimarslan wdyt?

**Comment by asimarslan** [comment]
Yes, it only try other ports if no port number exists in the address. We may introduce initial default port and port try count properties.

**Comment by pavan2017** [comment]
Hi @jerrinot 
Can i expect this in 3.9 release??

**Comment by pavan2017** [comment]
@jerrinot is this going to implemented in next version??

**Comment by Holmistr** [comment]
Isn't it possible by `<port port-count="200" auto-increment="true">5701</port>` or am I missing something?

**Comment by Holmistr** [comment]
Hi @pavan2017 , could you answer my question above? I would be happy to look into that issue.

**Comment by kwart** [comment]
@Holmistr the port configuration you mention is the server side configuration. It doesn't have a client side counterpart.

@pavan2017 Do you use the multicast for members discovery? And do you have the clients on the same LAN? If it is the case, you can use `MulticastDiscoveryStrategy` on both member and client side and then you don't need to care about the ports configuration. See the http://docs.hazelcast.org/docs/latest/manual/html-single/index.html#discovering-native-clients

This is how could the client configuration look like in such case:
```xml
<hazelcast-client xsi:schemaLocation="http://www.hazelcast.com/schema/client-config hazelcast-client-config-3.9.xsd"
           xmlns="http://www.hazelcast.com/schema/client-config"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

  <properties>
    <property name="hazelcast.discovery.enabled">true</property>
  </properties>

  <network>
    <discovery-strategies>
        <discovery-strategy class="com.hazelcast.spi.discovery.multicast.MulticastDiscoveryStrategy" enabled="true">
          <properties>
          <property name="group">224.2.2.3</property>
          <property name="port">54327</property>
          </properties>
        </discovery-strategy>
    </discovery-strategies>
  </network>
</hazelcast-client>
```

**Comment by burakcelebi** [comment]
Hi @pavan2017, do you have any updates?

**Comment by pavan2017** [comment]
Tried about but doesnt work.
Here is configuration on server
Config config = new ConfigProcessorDelegate().initHazelcast();
        config.getGroupConfig().setName(hazelcastGroup).setPassword(hazelcastGroup);
        config.setProperty("hazelcast.discovery.enabled", "true");
        NetworkConfig networkConfig = new NetworkConfig();
        DiscoveryStrategyConfig discoveryStrategyConfig = new DiscoveryStrategyConfig("com.hazelcast.spi.discovery.multicast.MulticastDiscoveryStrategy");
        DiscoveryConfig discoveryConfig = new DiscoveryConfig();
        discoveryConfig.addDiscoveryStrategyConfig(discoveryStrategyConfig);
        networkConfig.getJoin().getDiscoveryConfig().addDiscoveryStrategyConfig(discoveryStrategyConfig);
        networkConfig.getJoin().getMulticastConfig().setEnabled(false);


Here is configuration fro client 
 DiscoveryStrategyConfig discoveryStrategyConfig = new DiscoveryStrategyConfig("com.hazelcast.spi.discovery.multicast.MulticastDiscoveryStrategy");
        DiscoveryConfig discoveryConfig = new DiscoveryConfig();
        discoveryConfig.addDiscoveryStrategyConfig(discoveryStrategyConfig);
        clientConfig.getNetworkConfig().setDiscoveryConfig(discoveryConfig);

Client is failing with same problem

**Comment by dbrimley** [comment]
There seems to be two issues in this thread. The first report seems to be around port scanning for the client and the last post by @pavan2017 talks about multicast client discovery.

@Holmistr Can you work with @pavan2017 on this.  If there is a bug with port scanning and configuration from clients can you raise another github issue and we can get this fixed.

**Comment by sancar** [comment]
I have just double checked. This will confirm @jerrinot , @asimarslan and @kwart , but writing to emphasize this is still not addressed. 

Both `hazelcast.tcp.join.port.try.count` and 
`<port port-count="200" auto-increment="true">5701</port>` does not work for client. And client does not have any counterpart for this. 
@dbrimley 
An xml configuration as above could be a good addition for our clients.

**Comment by kwart** [comment]
@pavan2017 The working configuration can look like following:

**Server:**
```java
String hazelcastGroup = "test";
Config config = new Config();
config.setProperty("hazelcast.discovery.enabled", "true");
config.getGroupConfig().setName(hazelcastGroup).setPassword(hazelcastGroup);

JoinConfig joinConfig = config.getNetworkConfig().getJoin();
DiscoveryStrategyConfig discoveryStrategyConfig = new DiscoveryStrategyConfig(
        "com.hazelcast.spi.discovery.multicast.MulticastDiscoveryStrategy");
joinConfig.getDiscoveryConfig().addDiscoveryStrategyConfig(discoveryStrategyConfig);
joinConfig.getMulticastConfig().setEnabled(false);
Hazelcast.newHazelcastInstance(config);
```

**Client:**
```java
String hazelcastGroup = "test";
ClientConfig clientConfig = new ClientConfig();
clientConfig.setProperty("hazelcast.discovery.enabled", "true");
clientConfig.getGroupConfig().setName(hazelcastGroup).setPassword(hazelcastGroup);

DiscoveryStrategyConfig discoveryStrategyConfig = new DiscoveryStrategyConfig(
        "com.hazelcast.spi.discovery.multicast.MulticastDiscoveryStrategy");
clientConfig.getNetworkConfig().getDiscoveryConfig().addDiscoveryStrategyConfig(discoveryStrategyConfig);
HazelcastClient.newHazelcastClient(clientConfig);
```
