### ISSUE TITLE
[scheduled-executor] ScheduledExecutorServiceSlowTest.scheduleRandomPartitions_getAllScheduled_durable

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#10462]
```
java.lang.AssertionError: expected:<11.0> but was:<9.0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:575)
	at org.junit.Assert.assertEquals(Assert.java:700)
	at com.hazelcast.scheduledexecutor.ScheduledExecutorServiceSlowTest.scheduleRandomPartitions_getAllScheduled_durable(ScheduledExecutorServiceSlowTest.java:161)
```

https://hazelcast-l337.ci.cloudbees.com/view/Sonar/job/Hazelcast-3.x-sonar/com.hazelcast$hazelcast/1481/testReport/junit/com.hazelcast.scheduledexecutor/ScheduledExecutorServiceSlowTest/scheduleRandomPartitions_getAllScheduled_durable/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: expected:<11.0> but was:<10.0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:575)
	at org.junit.Assert.assertEquals(Assert.java:700)
	at com.hazelcast.scheduledexecutor.ScheduledExecutorServiceSlowTest.scheduleRandomPartitions_getAllScheduled_durable(ScheduledExecutorServiceSlowTest.java:167)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/1414/testReport/junit/com.hazelcast.scheduledexecutor/ScheduledExecutorServiceSlowTest/scheduleRandomPartitions_getAllScheduled_durable/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: expected:<11.0> but was:<10.0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:575)
	at org.junit.Assert.assertEquals(Assert.java:700)
	at com.hazelcast.scheduledexecutor.ScheduledExecutorServiceSlowTest.scheduleRandomPartitions_getAllScheduled_durable(ScheduledExecutorServiceSlowTest.java:167)
```

https://hazelcast-l337.ci.cloudbees.com/view/Sonar/job/Hazelcast-3.x-sonar/com.hazelcast$hazelcast/1568/testReport/junit/com.hazelcast.scheduledexecutor/ScheduledExecutorServiceSlowTest/scheduleRandomPartitions_getAllScheduled_durable/

**Comment by tkountis** [comment]
Issues https://github.com/hazelcast/hazelcast/issues/10363 & https://github.com/hazelcast/hazelcast/issues/10354 are the same issue.

**Comment by tkountis** [comment]
There is nothing in the logs to pin-point this to some root cause other than **total** partition loss. All log files, have multiple lost partition entries in them, therefore since this test is trying to count **all** available tasks in all available partitions, its only normal to have a count off by a few when a partition is missing. In the test, I do a graceful shutdown.

I can try to increase the replicas just for this test.

**Comment by tkountis** [comment]
Attempted fix with #11083 
If it happens again, we will investigate closer as to why the partitions are lost in the first place or relax the test a bit more.

**Comment by hasancelik** [comment]
*maintenance*
```
java.lang.AssertionError: expected:<11.0> but was:<10.0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:575)
	at org.junit.Assert.assertEquals(Assert.java:700)
	at com.hazelcast.scheduledexecutor.ScheduledExecutorServiceSlowTest.scheduleRandomPartitions_getAllScheduled_durable(ScheduledExecutorServiceSlowTest.java:167)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-nightly/com.hazelcast$hazelcast/1323/testReport/junit/com.hazelcast.scheduledexecutor/ScheduledExecutorServiceSlowTest/scheduleRandomPartitions_getAllScheduled_durable/

**Comment by mdogan** [comment]
Backported @tkountis 's changes to the maintenance branch. See https://github.com/hazelcast/hazelcast/compare/ccd81104b97b...dd897708c704

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: expected:<11.0> but was:<10.0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:575)
	at org.junit.Assert.assertEquals(Assert.java:700)
	at com.hazelcast.scheduledexecutor.ScheduledExecutorServiceSlowTest.scheduleRandomPartitions_getAllScheduled_durable(ScheduledExecutorServiceSlowTest.java:172)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/1533/testReport/junit/com.hazelcast.scheduledexecutor/ScheduledExecutorServiceSlowTest/scheduleRandomPartitions_getAllScheduled_durable/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: expected:<11.0> but was:<8.0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:575)
	at org.junit.Assert.assertEquals(Assert.java:700)
	at com.hazelcast.scheduledexecutor.ScheduledExecutorServiceSlowTest.scheduleRandomPartitions_getAllScheduled_durable(ScheduledExecutorServiceSlowTest.java:172)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/1587/testReport/junit/com.hazelcast.scheduledexecutor/ScheduledExecutorServiceSlowTest/scheduleRandomPartitions_getAllScheduled_durable/
