### ISSUE TITLE
WaitNotifySplitBrainTest.testSplitBrain

### ISSUE THREAD

**Issue by Donnerbart** [hazelcast/hazelcast#10491]
```java
java.lang.AssertionError: expected:<1000> but was:<1024>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.test.HazelcastTestSupport$16.run(HazelcastTestSupport.java:1082)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1003)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1020)
	at com.hazelcast.test.HazelcastTestSupport.assertWaitingOperationCountEventually(HazelcastTestSupport.java:1079)
	at com.hazelcast.spi.impl.operationparker.impl.WaitNotifySplitBrainTest.assertOnlyOwnerHasWaitingOperationsEventually(WaitNotifySplitBrainTest.java:62)
	at com.hazelcast.spi.impl.operationparker.impl.WaitNotifySplitBrainTest.onAfterSplitBrainHealed(WaitNotifySplitBrainTest.java:49)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/8662/testReport/junit/com.hazelcast.spi.impl.operationparker.impl/WaitNotifySplitBrainTest/testSplitBrain/

**Comment by mdogan** [comment]
No failures for 2 months. I think we can close this issue.
