### ISSUE TITLE
ClusterRollingRestartTest.test_rollingRestart[clusterState:FROZEN,partitionAssignmentType:AT_THE_END]

### ISSUE THREAD

**Issue by mmedenjak** [hazelcast/hazelcast#10500]
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.7/1268/

```
java.lang.IllegalStateException: Node failed to start!
	at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:138)
	at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:195)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:174)
	at com.hazelcast.test.TestHazelcastInstanceFactory.newHazelcastInstance(TestHazelcastInstanceFactory.java:137)
	at com.hazelcast.test.TestHazelcastInstanceFactory.newHazelcastInstance(TestHazelcastInstanceFactory.java:123)
	at com.hazelcast.internal.cluster.impl.ClusterRollingRestartTest.test_rollingRestart(ClusterRollingRestartTest.java:84)
```

**Comment by metanet** [comment]
failure logs: [rolling.txt](https://github.com/hazelcast/hazelcast/files/996972/rolling.txt)
