### ISSUE TITLE
Split-Brain Network doesn't work

### ISSUE THREAD

**Issue by IdefixTeam** [hazelcast/hazelcast#10517]
Hi,
I use hazelcast version 3.6.4. I have 2-node cluster. 
I disconnect the network cable of a node then I reconnect it a few minutes later. 
Sometime the reconnection happens well, sometime the reconnection never occurs and the following exception appears without stop:

```java
Still have pending migration tasks, cannot lock cluster state! New state: FROZEN, current state: ACTIVE
java.lang.IllegalStateException: Still have pending migration tasks, cannot lock cluster state! New state: FROZEN, current state: ACTIVE
	at com.hazelcast.cluster.impl.ClusterStateManager.checkMigrationsAndPartitionStateVersion(ClusterStateManager.java:167) [hazelcast-all-3.6.4.jar:3.6.4]
	at com.hazelcast.cluster.impl.ClusterStateManager.lockClusterState(ClusterStateManager.java:139) [hazelcast-all-3.6.4.jar:3.6.4]
	at com.hazelcast.cluster.impl.operations.LockClusterStateOperation.run(LockClusterStateOperation.java:75) ~[hazelcast-all-3.6.4.jar:3.6.4]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:172) ~[hazelcast-all-3.6.4.jar:3.6.4]
	at com.hazelcast.spi.impl.operationexecutor.classic.ClassicOperationExecutor.runOnCallingThread(ClassicOperationExecutor.java:392) [hazelcast-all-3.6.4.jar:3.6.4]
	at com.hazelcast.spi.impl.operationexecutor.classic.ClassicOperationExecutor.runOnCallingThreadIfPossible(ClassicOperationExecutor.java:345) [hazelcast-all-3.6.4.jar:3.6.4]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:259) [hazelcast-all-3.6.4.jar:3.6.4]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:243) [hazelcast-all-3.6.4.jar:3.6.4]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invokeInternal(Invocation.java:210) [hazelcast-all-3.6.4.jar:3.6.4]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:180) [hazelcast-all-3.6.4.jar:3.6.4]
	at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.invokeOnTarget(OperationServiceImpl.java:323) [hazelcast-all-3.6.4.jar:3.6.4]
	at com.hazelcast.cluster.impl.ClusterStateManager.lockClusterState(ClusterStateManager.java:270) [hazelcast-all-3.6.4.jar:3.6.4]
	at com.hazelcast.cluster.impl.ClusterStateManager.changeClusterState(ClusterStateManager.java:249) [hazelcast-all-3.6.4.jar:3.6.4]
	at com.hazelcast.cluster.impl.ClusterStateManager.changeClusterState(ClusterStateManager.java:228) [hazelcast-all-3.6.4.jar:3.6.4]
	at com.hazelcast.cluster.impl.ClusterServiceImpl.changeClusterState(ClusterServiceImpl.java:819) [hazelcast-all-3.6.4.jar:3.6.4]
	at com.hazelcast.cluster.impl.AbstractJoiner.prepareClusterState(AbstractJoiner.java:333) [hazelcast-all-3.6.4.jar:3.6.4]
	at com.hazelcast.cluster.impl.AbstractJoiner.startClusterMerge(AbstractJoiner.java:306) [hazelcast-all-3.6.4.jar:3.6.4]
	at com.hazelcast.cluster.impl.TcpIpJoiner.searchForOtherClusters(TcpIpJoiner.java:517) [hazelcast-all-3.6.4.jar:3.6.4]
	at com.hazelcast.cluster.impl.SplitBrainHandler.searchForOtherClusters(SplitBrainHandler.java:75) [hazelcast-all-3.6.4.jar:3.6.4]
	at com.hazelcast.cluster.impl.SplitBrainHandler.run(SplitBrainHandler.java:42) [hazelcast-all-3.6.4.jar:3.6.4]
	at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:212) [hazelcast-all-3.6.4.jar:3.6.4]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_60]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_60]
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76) [hazelcast-all-3.6.4.jar:3.6.4]
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92) [hazelcast-all-3.6.4.jar:3.6.4]
```
I think the repartition due to the disconnection is always on hold or never ends because I do not see the last log info of repartitionning task.
When reconnection works, disconnection products the following logs  :
"Partition balance is ok, no need to re-partition cluster data..."
When reconnection does not work, disconnection does not produce any of the following logs  :
"Partition balance is ok, no need to re-partition cluster data..."
"Re-partitioning cluster data... Migration queue size: ..."

**Comment by metanet** [comment]
Hi @IdefixTeam 

We have made a lot of improvements in our internal partition / migration systems. Any chance that you can upgrade your cluster to the recent version? 

Regards,

**Comment by mmedenjak** [comment]
@IdefixTeam have you been able to test with a more recent version of hazelcast?

**Comment by mmedenjak** [comment]
Hi @IdefixTeam !

I am closing this issue due to no activity. Please upgrade to the newest version of hazelcast. We have especially made an effort in the split brain healing and migration system in hazelcast 3.10.
If you continue to experience problems, please open a new issue.
