### ISSUE TITLE
Significant cluster performance degragation

### ISSUE THREAD

**Issue by dimas** [hazelcast/hazelcast#10518]
It is not going to be an easy issue to explain as many things have happened to the cluster as we were trying to resolve the problem. I am not sure we will be able to provide all the relevant logs either as it was spread in time over multiple days. However, the issue itself was very real so at least I hope the evidences you may ask from us will help us know what to look for if it ever happens again.

* It was a big 3.7.3 cluster 40 to 50 nodes that we kept under stress (tens of thousands requests per second) for many days monitoring its performance.
* It only had couple of distributed maps (under a million entries each) in it
* the most frequent request is invocation of entry processor on either one of them.
* no sync or async backups

The latency of put operations started in 10ms range but was slowly going up over time. Also, it was not growing linearly but was following some complex pattern of ups and downs as load was added and removed but overall trend was growth. In the last days it reached 60ms which made the cluster unusable for further testing so the decision was made to attempt recovering its performance without rebuilding the cluster.

First of all, because of other issues (https://github.com/hazelcast/hazelcast/issues/10482) we did not have management console and had to restart several brokers to fix that. The restart normally has a very little impact on the cluster - as there were no backups, it loses some data, but the cluster recovers quickly and entry processors keep recreating the missing data.

When MC was restored, it did not really provide any insight into what is wrong with the cluster as everything looked normal. "put latency" for the map was a few ms on all the nodes but that was obviously not the case because our client code that was invoking entry processors was logging average latency of 60ms. (Not enough network IO threads?)

Another client, performing just map.get() operation on random keys was reporting a huge spread of latency so we started looking for what keys the latency was way too high (more than a second). We could not find a better way of doing that (I raised https://github.com/hazelcast/hazelcast/issues/10510) so with a bit of scripting via MC we managed to pull owning member for these keys. And all the "slow" keys were pointing to the same member (10.0.139.41)

Even when we identified misbehaving member, we could not see anything suspicious about it in Management Center. Neither could we find in it in the logs. The 10.0.139.41 node was only logging two message types:
* com.hazelcast.internal.diagnostics.HealthMonitor in a weird pattern judging by timestamp (bunch of messages every 20 seconds then long pause then again)
* com.hazelcast.internal.management.ManagementCenterService - a continuous stream of "Failed to connect to", "Connection to management center restored."

But other nodes were also demonstrating the same pattern so it wasn't something special for 10.0.139.41

We decided to restart the node. And at that moment cluster performance degraded severely. Previously we restarted individual members multiple times and always it was a barely noticeable operation as cluster quickly recovered. This restart was a very different one.

Symptoms were (even 20 minutes after restart):
* the number of entries on the restarted node in the map (as shown by Management Center) was only half of number of entries on all other nodes.
* huge lag reported by all the clients doing both puts and gets
* Management Centre was showing many "pending migrations" and that value was not going down
* Management Centre "throughput" chart for map was not flat - it was climbing to its target value, staying there for short time and then dropping to almost zero, staying there longer that at "good" throughput, then climbing back. And so on

Because we could not find problem with MC, we started trawling through logs where we found lots of WARN messages like these (com.hazelcast.spi.impl.operationservice.impl.Invocation)
```
[10.0.141.144]:5701 [] [3.7.3] Retrying invocation: Invocation{op=com.hazelcast.map.impl.operation.EntryOperation{serviceName='hz:impl:mapService', identityHash=228679050, partitionId=136, replicaIndex=0, callId=8919258822, invocationTime=1493900930967 (2017-05-04 12:28:50.967), waitTimeout=-1, callTimeout=60000, name=hubs}, tryCount=250, tryPauseMillis=500, invokeCount=240, callTimeoutMillis=60000, firstInvocationTimeMs=1493900809830, firstInvocationTime='2017-05-04 12:26:49.830', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 00:00:00.000', target=[10.0.141.144]:5701, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=null}, Reason: com.hazelcast.spi.exception.PartitionMigratingException: Partition is migrating! this: [10.0.141.144]:5701, partitionId: 136, operation: com.hazelcast.map.impl.operation.EntryOperation, service: hz:impl:mapService
[10.0.141.144]:5701 [] [3.7.3] Retrying invocation: Invocation{op=com.hazelcast.map.impl.operation.EntryOperation{serviceName='hz:impl:mapService', identityHash=75744533, partitionId=136, replicaIndex=0, callId=8919258494, invocationTime=1493900930964 (2017-05-04 12:28:50.964), waitTimeout=-1, callTimeout=60000, name=hubs}, tryCount=250, tryPauseMillis=500, invokeCount=220, callTimeoutMillis=60000, firstInvocationTimeMs=1493900819812, firstInvocationTime='2017-05-04 12:26:59.812', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 00:00:00.000', target=[10.0.141.144]:5701, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=null}, Reason: com.hazelcast.spi.exception.PartitionMigratingException: Partition is migrating! this: [10.0.141.144]:5701, partitionId: 136, operation: com.hazelcast.map.impl.operation.EntryOperation, service: hz:impl:mapService
```

As all of them were referring to partitionId=136. We found member owning this partition and it turned to be the same node that was logging these warnings - 10.0.141.144

The node was restarted and all problems disappeared instantly.

So to me there are two problems:
* why cluster "broke" in the first place. Is there anything we should be looking in the logs for?
* how restarting of a single node in a cluster can lead to such a disastrous results that it requires and does not recover

Thanks

**Comment by dimas** [comment]
Trawling through collected logs trying to find any information.

###### Before restart of 10.0.139.41 (cluster is operational but 10.0.139.41 is very slow)

com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor in InvocationMonitorThread logs
```
[10.0.151.46]:5701 [] [3.7.3] Invocations:2 timeouts:1 backup-timeouts:0
[10.0.141.144]:5701 [] [3.7.3] Invocations:6 timeouts:1 backup-timeouts:0
```
These two nodes log about 600 of these messages over duration of 6 hours.

Also, pretty much all nodes complain about Management Center connection continuously: com.hazelcast.internal.management.ManagementCenterService in MC.State.Sender thread:
```
[10.0.130.18]:5701 [] [3.7.3] Failed to connect to:http://
[10.0.130.18]:5701 [] [3.7.3] Connection to management center restored.

```
These are about 3 seconds apart. There are lots of these, all nodes do that and it seem to have started long time ago.


###### After restart of 10.0.139.41 (cluster becomes unusable)

After 10.0.139.41 restart, the 10.0.141.144 (which became broken) logs WARN from com.hazelcast.map.impl.operation.ClearExpiredOperation in partition-operation.thread-0:

```
[10.0.141.144]:5701 [] [3.7.3] com.hazelcast.spi.exception.PartitionMigratingException: Partition is migrating! this: [10.0.141.144]:5701, partitionId: 136, operation: com.hazelcast.map.impl.operation.ClearExpiredOperation, service: hz:impl:mapService
```

And there is some logging from 10.0.163.225 which seem to coordinate migration somehow because it is the only node logging these things. com.hazelcast.internal.partition.impl.MigrationManager in migration thread:

```
[10.0.163.225]:5701 [] [3.7.3] Re-partitioning cluster data... Migration queue size: 83

... (6 minutes later)

[10.0.163.225]:5701 [] [3.7.3] Failed migration from Member [10.0.141.144]:5701 - d130dbc4-2dd9-4360-ada6-6683f0d00bbb for MigrationInfo{uuid=271fbc5d-82f7-4c9c-8799-acc8464ad520, partitionId=136, source=null, sourceUuid=<invalid-uuid>, sourceCurrentReplicaIndex=-1, sourceNewReplicaIndex=-1, destination=[10.0.151.46]:5701, destinationUuid=a7ab8a79-83b6-4b30-bf6e-d6d2f74cfda5, destinationCurrentReplicaIndex=6, destinationNewReplicaIndex=1, master=[10.0.163.225]:5701, processing=false, status=ACTIVE}
	java.util.concurrent.ExecutionException: com.hazelcast.core.OperationTimeoutException: MigrationOperation invocation failed to complete due to operation-heartbeat-timeout. Current time: 2017-05-04 12:16:02.850. Total elapsed time: 360464 ms. Last operation heartbeat: never. Last operation heartbeat from member: 2017-05-04 08:33:35.547. Invocation{op=com.hazelcast.internal.partition.operation.MigrationOperation{serviceName='hz:core:partitionService', identityHash=2090233369, partitionId=136, replicaIndex=0, callId=0, invocationTime=1493899802386 (2017-05-04 12:10:02.386), waitTimeout=-1, callTimeout=300000, migration=MigrationInfo{uuid=271fbc5d-82f7-4c9c-8799-acc8464ad520, partitionId=136, source=null, sourceUuid=null, sourceCurrentReplicaIndex=-1, sourceNewReplicaIndex=-1, destination=[10.0.151.46]:5701, destinationUuid=a7ab8a79-83b6-4b30-bf6e-d6d2f74cfda5, destinationCurrentReplicaIndex=6, destinationNewReplicaIndex=1, master=[10.0.163.225]:5701, processing=false, status=ACTIVE}, replicaVersions=[0, 0, 0, 0, 0, 0], numberOfTasks=4}, tryCount=6, tryPauseMillis=10000, invokeCount=1, callTimeoutMillis=300000, firstInvocationTimeMs=1493899802386, firstInvocationTime='2017-05-04 12:10:02.386', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 00:00:00.000', target=[10.0.151.46]:5701, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=Connection[id=2506, /10.0.141.144:5701->/10.0.151.46:55779, endpoint=[10.0.151.46]:5701, alive=true, type=MEMBER]}
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrow(InvocationFuture.java:85)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:158)
	at com.hazelcast.internal.partition.impl.MigrationManager$MigrateTask.executeMigrateOperation(MigrationManager.java:902)
	at com.hazelcast.internal.partition.impl.MigrationManager$MigrateTask.run(MigrationManager.java:817)
	at com.hazelcast.internal.partition.impl.MigrationThread.processTask(MigrationThread.java:107)
	at com.hazelcast.internal.partition.impl.MigrationThread.doRun(MigrationThread.java:84)
	at com.hazelcast.internal.partition.impl.MigrationThread.run(MigrationThread.java:59)
Caused by: com.hazelcast.core.OperationTimeoutException: MigrationOperation invocation failed to complete due to operation-heartbeat-timeout. Current time: 2017-05-04 12:16:02.850. Total elapsed time: 360464 ms. Last operation heartbeat: never. Last operation heartbeat from member: 2017-05-04 08:33:35.547. Invocation{op=com.hazelcast.internal.partition.operation.MigrationOperation{serviceName='hz:core:partitionService', identityHash=2090233369, partitionId=136, replicaIndex=0, callId=0, invocationTime=1493899802386 (2017-05-04 12:10:02.386), waitTimeout=-1, callTimeout=300000, migration=MigrationInfo{uuid=271fbc5d-82f7-4c9c-8799-acc8464ad520, partitionId=136, source=null, sourceUuid=null, sourceCurrentReplicaIndex=-1, sourceNewReplicaIndex=-1, destination=[10.0.151.46]:5701, destinationUuid=a7ab8a79-83b6-4b30-bf6e-d6d2f74cfda5, destinationCurrentReplicaIndex=6, destinationNewReplicaIndex=1, master=[10.0.163.225]:5701, processing=false, status=ACTIVE}, replicaVersions=[0, 0, 0, 0, 0, 0], numberOfTasks=4}, tryCount=6, tryPauseMillis=10000, invokeCount=1, callTimeoutMillis=300000, firstInvocationTimeMs=1493899802386, firstInvocationTime='2017-05-04 12:10:02.386', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 00:00:00.000', target=[10.0.151.46]:5701, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=Connection[id=2506, /10.0.141.144:5701->/10.0.151.46:55779, endpoint=[10.0.151.46]:5701, alive=true, type=MEMBER]}
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.newOperationTimeoutException(InvocationFuture.java:150)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:98)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run(AbstractInvocationFuture.java:246)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:111)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrow(InvocationFuture.java:74)
	... 6 common frames omitted
[10.0.163.225]:5701 [] [3.7.3] Migration failed: MigrationInfo{uuid=271fbc5d-82f7-4c9c-8799-acc8464ad520, partitionId=136, source=null, sourceUuid=<invalid-uuid>, sourceCurrentReplicaIndex=-1, sourceNewReplicaIndex=-1, destination=[10.0.151.46]:5701, destinationUuid=a7ab8a79-83b6-4b30-bf6e-d6d2f74cfda5, destinationCurrentReplicaIndex=6, destinationNewReplicaIndex=1, master=[10.0.163.225]:5701, processing=false, status=ACTIVE}
[10.0.163.225]:5701 [] [3.7.3] Re-partitioning cluster data... Migration queue size: 85

... (6 more minutes later)

[10.0.163.225]:5701 [] [3.7.3] Failed migration from Member [10.0.141.144]:5701 - d130dbc4-2dd9-4360-ada6-6683f0d00bbb for MigrationInfo{uuid=bf1b9d10-a9a3-448f-bcef-2f773a4869e0, partitionId=136, source=null, sourceUuid=<invalid-uuid>, sourceCurrentReplicaIndex=-1, sourceNewReplicaIndex=-1, destination=[10.0.151.46]:5701, destinationUuid=a7ab8a79-83b6-4b30-bf6e-d6d2f74cfda5, destinationCurrentReplicaIndex=6, destinationNewReplicaIndex=1, master=[10.0.163.225]:5701, processing=false, status=ACTIVE}
java.util.concurrent.ExecutionException: com.hazelcast.core.OperationTimeoutException: MigrationOperation invocation failed to complete due to operation-heartbeat-timeout. Current time: 2017-05-04 12:22:12.850. Total elapsed time: 360048 ms. Last operation heartbeat: never. Last operation heartbeat from member: 2017-05-04 08:33:35.547. Invocation{op=com.hazelcast.internal.partition.operation.MigrationOperation{serviceName='hz:core:partitionService', identityHash=1615651049, partitionId=136, replicaIndex=0, callId=0, invocationTime=1493900172802 (2017-05-04 12:16:12.802), waitTimeout=-1, callTimeout=300000, migration=MigrationInfo{uuid=bf1b9d10-a9a3-448f-bcef-2f773a4869e0, partitionId=136, source=null, sourceUuid=null, sourceCurrentReplicaIndex=-1, sourceNewReplicaIndex=-1, destination=[10.0.151.46]:5701, destinationUuid=a7ab8a79-83b6-4b30-bf6e-d6d2f74cfda5, destinationCurrentReplicaIndex=6, destinationNewReplicaIndex=1, master=[10.0.163.225]:5701, processing=false, status=ACTIVE}, replicaVersions=[0, 0, 0, 0, 0, 0], numberOfTasks=4}, tryCount=6, tryPauseMillis=10000, invokeCount=1, callTimeoutMillis=300000, firstInvocationTimeMs=1493900172802, firstInvocationTime='2017-05-04 12:16:12.802', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 00:00:00.000', target=[10.0.151.46]:5701, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=Connection[id=2506, /10.0.141.144:5701->/10.0.151.46:55779, endpoint=[10.0.151.46]:5701, alive=true, type=MEMBER]}
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrow(InvocationFuture.java:85)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:158)
	at com.hazelcast.internal.partition.impl.MigrationManager$MigrateTask.executeMigrateOperation(MigrationManager.java:902)
	at com.hazelcast.internal.partition.impl.MigrationManager$MigrateTask.run(MigrationManager.java:817)
	at com.hazelcast.internal.partition.impl.MigrationThread.processTask(MigrationThread.java:107)
	at com.hazelcast.internal.partition.impl.MigrationThread.doRun(MigrationThread.java:84)
	at com.hazelcast.internal.partition.impl.MigrationThread.run(MigrationThread.java:59)
Caused by: com.hazelcast.core.OperationTimeoutException: MigrationOperation invocation failed to complete due to operation-heartbeat-timeout. Current time: 2017-05-04 12:22:12.850. Total elapsed time: 360048 ms. Last operation heartbeat: never. Last operation heartbeat from member: 2017-05-04 08:33:35.547. Invocation{op=com.hazelcast.internal.partition.operation.MigrationOperation{serviceName='hz:core:partitionService', identityHash=1615651049, partitionId=136, replicaIndex=0, callId=0, invocationTime=1493900172802 (2017-05-04 12:16:12.802), waitTimeout=-1, callTimeout=300000, migration=MigrationInfo{uuid=bf1b9d10-a9a3-448f-bcef-2f773a4869e0, partitionId=136, source=null, sourceUuid=null, sourceCurrentReplicaIndex=-1, sourceNewReplicaIndex=-1, destination=[10.0.151.46]:5701, destinationUuid=a7ab8a79-83b6-4b30-bf6e-d6d2f74cfda5, destinationCurrentReplicaIndex=6, destinationNewReplicaIndex=1, master=[10.0.163.225]:5701, processing=false, status=ACTIVE}, replicaVersions=[0, 0, 0, 0, 0, 0], numberOfTasks=4}, tryCount=6, tryPauseMillis=10000, invokeCount=1, callTimeoutMillis=300000, firstInvocationTimeMs=1493900172802, firstInvocationTime='2017-05-04 12:16:12.802', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 00:00:00.000', target=[10.0.151.46]:5701, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=Connection[id=2506, /10.0.141.144:5701->/10.0.151.46:55779, endpoint=[10.0.151.46]:5701, alive=true, type=MEMBER]}
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.newOperationTimeoutException(InvocationFuture.java:150)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:98)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run(AbstractInvocationFuture.java:246)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:111)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrow(InvocationFuture.java:74)
	... 6 common frames omitted
[10.0.163.225]:5701 [] [3.7.3] Migration failed: MigrationInfo{uuid=bf1b9d10-a9a3-448f-bcef-2f773a4869e0, partitionId=136, source=null, sourceUuid=<invalid-uuid>, sourceCurrentReplicaIndex=-1, sourceNewReplicaIndex=-1, destination=[10.0.151.46]:5701, destinationUuid=a7ab8a79-83b6-4b30-bf6e-d6d2f74cfda5, destinationCurrentReplicaIndex=6, destinationNewReplicaIndex=1, master=[10.0.163.225]:5701, processing=false, status=ACTIVE}
[10.0.163.225]:5701 [] [3.7.3] Re-partitioning cluster data... Migration queue size: 48

... (and then it repeats over and over every 6 minites with the same exceptions etc)

[10.0.163.225]:5701 [] [3.7.3] Re-partitioning cluster data... Migration queue size: 41
...
[10.0.163.225]:5701 [] [3.7.3] Re-partitioning cluster data... Migration queue size: 42
...
[10.0.163.225]:5701 [] [3.7.3] Re-partitioning cluster data... Migration queue size: 42
```
(not sure why it went to 41 and then back to 42)


Also, after restart, as I already described, the 10.0.141.144 node logs tens of thousands of 
```
[10.0.141.144]:5701 [] [3.7.3] Retrying invocation: Invocation{op=com.hazelcast.map.impl.operation.EntryOperation{serviceName='hz:impl:mapService', identityHash=380195793, partitionId=136, replicaIndex=0, callId=8906185107, invocationTime=1493900372509 (2017-05-04 12:19:32.509), waitTimeout=-1, callTimeout=60000, name=hubs}, tryCount=250, tryPauseMillis=500, invokeCount=100, callTimeoutMillis=60000, firstInvocationTimeMs=1493900324959, firstInvocationTime='2017-05-04 12:18:44.959', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 00:00:00.000', target=[10.0.141.144]:5701, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=null}, Reason: com.hazelcast.spi.exception.PartitionMigratingException: Partition is migrating! this: [10.0.141.144]:5701, partitionId: 136, operation: com.hazelcast.map.impl.operation.EntryOperation, service: hz:impl:mapService

```

and at the same time all other nodes log com.hazelcast.map.impl.LocalMapStatsProvider in MC.State.Sender thread:
```
[10.0.147.119]:5701 [] [3.7.3] Partition: Partition [136]{
	0:[10.0.141.144]:5701
	2:[10.0.168.38]:5701
	3:[10.0.166.98]:5701
	4:[10.0.170.244]:5701
	5:[10.0.134.187]:5701
	6:[10.0.151.46]:5701
}, replica: 1 has no owner!
[10.0.173.192]:5701 [] [3.7.3] Partition: Partition [136]{
	0:[10.0.141.144]:5701
	2:[10.0.168.38]:5701
	3:[10.0.166.98]:5701
	4:[10.0.170.244]:5701
	5:[10.0.134.187]:5701
	6:[10.0.151.46]:5701
}, replica: 1 has no owner!
```

Hope that helps.

**Comment by tombujok** [comment]
Thx for the detailed write-up. Would that be possible to get logs of the node if you don't have any business sensitive information there? 
I can imagine this is impossible to tackle without having logs...

**Comment by dimas** [comment]
That would be interesting to know what logs are missing or what would you be looking for.
Because I thought I found everything that matters.

Extracting full logs is a possibility but I am not sure we are prepared to just dump them onto some public storage. Not sure what sensitive can be there. I am sure we can share them with Hazelcast folks though but we need some guidance - what do they need exactly.

**Comment by pveentjer** [comment]
Can you send the configuration of the relevant maps? 

Can you also add the following parameters to your JVM:

```
-Dhazelcast.diagnostics.enabled=true
-Dhazelcast.diagnostics.metric.level=info
```
It is unlikely that the number of network io threads are the cause; only in case of TLS increasing the number of IO threads makes a significant improvement.

This will create a diagnostics log file containing a lot more information than the health monitor issues you have been seeing. Also it will give us better insights into slow operations. The above settings are fine to be used in production.

A 'cause' of your slow performance could be the migration of data. There is a migration going on that appearently is timing out. When operations are going to be executed on a partition being migrated, you can get big latencies and bad performance. However the big question is: why is this migration not completing..

**Comment by dimas** [comment]
@pveentjer , thanks for the reply.

1. the config for these maps is very simple
```xml
    <map name="map1">
        <backup-count>0</backup-count>
        <async-backup-count>0</async-backup-count>
        <read-backup-data>false</read-backup-data>
        <indexes>
            <index>lastUpdateTime</index>
            <index>mode</index>
        </indexes>
    </map>
```
this is how we defined it. And
```xml
     <map name="map1">
          <in-memory-format>BINARY</in-memory-format>
          <backup-count>0</backup-count>
          <async-backup-count>0</async-backup-count>
          <time-to-live-seconds>0</time-to-live-seconds>
          <max-idle-seconds>0</max-idle-seconds>
          <eviction-policy>NONE</eviction-policy>
          <max-size policy="PER_NODE">2147483647</max-size>
          <eviction-percentage>25</eviction-percentage>
          <min-eviction-check-millis>100</min-eviction-check-millis>
          <merge-policy>com.hazelcast.map.merge.PutIfAbsentMapMergePolicy</merge-policy>
          <read-backup-data>false</read-backup-data>
          <hot-restart enabled="false">
               <fsync>false</fsync>
          </hot-restart>
          <statistics-enabled>true</statistics-enabled>
          <map-store enabled="false">
               <class-name>null</class-name>
               <write-delay-seconds>0</write-delay-seconds>
               <write-batch-size>1</write-batch-size>
          </map-store>
          <indexes>
               <index ordered="false">lastTime</index>
               <index ordered="false">mode</index>
          </indexes>
     </map>
```
how Management Center sees its config

And second map is almost the same but it has 4 indexed properties in the model instead of 2.

2. re -Dhazelcast.diagnostics.enabled=true and -Dhazelcast.diagnostics.metric.level=info
I tried these options for a test. Thought they are going to add some logging. But they are actually causing Hazelcast to create a files on the file system. Which of course fails on a closed down system where all the permissions revoked and Java process logs are sent to remote servers...
So regarding "The above settings are fine to be used in production" - from the amount of data they are generating - maybe. But from the operational standpoint that is not very convenient really. 

I can check if it is possible to do it on one of the servers for some analysis but I cannot see us doing it on the entire cluster and keeping like that forever (until the next incident).

However looking at the data makes me think that some of them probably available via JMX so we can collect and chart it.

3. "It is unlikely that the number of network io threads are the cause; only in case of TLS increasing the number of IO threads makes a significant improvement."

There were no TLS used, so it is not for us.

4. "Can you give an impression of how much data you roughly have in memory so I can get a bit of an idea about the size of a partition."
I belive when I checked it was about 50-70 Mb of "entry memory" per node (as reported by Management Center) for the fist map and about 230 Mb "entry memory" per node for the second.
Are these numbers helpful in any way ?

5. re partitions. Yes, we are using standard 271 one. Increasing number of partitions is indeed a very interesting idea. I will dig into docs on how it affects parallelism.

Thanks

**Comment by dimas** [comment]
@pveentjer , regarding this:
> PS: How many partitions do you have? If you have the default of 271, and a 50 node cluster, each member will get roughly 5 partitions which is very little. I would raise to 5003 so that each member has roughly 100 partitions. If you don't have enough partitions, there won't be enough parallelism. Increasing the number of partitions will also reduce the size of the partition data in case of a migration; speeding up the migration. But normally..even with larger partitions... you should not run into a timeout.. something fishy is happening..

Is there any documentation or whitepaper or anything like that explaining how number of partition affects parallelism and what are pros and cons of changing the number?
I cannot seem to find anything in the documentation....

Thanks

**Comment by mmedenjak** [comment]
@dimas it's hard to tell what is going on other than replication operations taking a long time and timing out. I don't think there is an extensive documentation on how the partition count affects the behaviour of the cluster but roughly a bigger partition count means that there are more partitions that are smaller in size. The cluster migration (when a member joins/leaves) will be performed in many small operations rather than a couple of big ones. This could last longer because of more round trips but the cluster stability could be better. From the size of your data set it would seem you could benefit from a higher partition count.
The problem with migrations is that mutation operations are not allowed until they finish. So if you have a smaller count of big partitions, you will more likely hit the migrations that is currrently being migrated and the operation will be rejected. 
If you still experience timeouts on operations, you can increase those but it means that the system will wait longer before declaring some operation lost.

**Comment by dimas** [comment]
We ended up increasing number of partitions as Peter suggested - this shows some good results on a test runs. However we do not have enough statistics yet as changes haven't hit prod yet.

In any case, this issue is not about performance or how much time it takes to replicate stuff.
To me the main problem is that cluster has not recovered from the problem. Something happened and it was not handled properly and the cluster was permanently damaged and could not operate properly until human intervention. Kind of problem for HA systems...

**Comment by mmedenjak** [comment]
It could be then that the cause were large partitions. The default partition count of 271 seems like a good default for some cases but not all. In your case the large partitions would produce large replication operations which could spike up memory usage and GC. When those operations are sent over the wire they can block the network traffic, causing even more load on the system. Because of this heartbeat operations don't come as often as they should and the cluster becomes unstable. Unfortunately it's a cascading issue - once a member is kicked out, new migrations need to happen which further clog down the system.
Putting a higher partition count could have more smaller partitions and everything should be smoother. Of course, you don't want to put a too-high partition count if you don't have lots of data - that has different issues.

**Comment by Dineshseervi** [comment]
These two are very help full to over come any connection issue we face while clustering like HTT or not able to form cluster due to lots of pod to scan .Plz try set property either service-name or below that will help to use Hazelcast in your application without any clustering issue you face in k8s env  
-->
join.getKubernetesConfig().setProperty("service-label-name", "label-name-you-want-to-use-from-pod");
join.getKubernetesConfig().setProperty("service-label-value", "label-value-for-lable-name");
or (dont use service label and pod label together)
join.getKubernetesConfig().setProperty("pod-laber-name", "label-name-you-want-to-use-from-service");
join.getKubernetesConfig().setProperty("pod-laber-value", "label-value-for-lable-name");
