### ISSUE TITLE
MockJoinerTest.restart_multipleInParallel()

### ISSUE THREAD

**Issue by Donnerbart** [hazelcast/hazelcast#10526]
```java
java.lang.AssertionError: Cluster size is not correct. Expected: 5 Actual: 4
	at org.junit.Assert.fail(Assert.java:88)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSize(HazelcastTestSupport.java:870)
	at com.hazelcast.test.HazelcastTestSupport$12.run(HazelcastTestSupport.java:889)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1003)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:885)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:880)
	at com.hazelcast.test.mocknetwork.MockJoinerTest.assertClusterSizeEventually(MockJoinerTest.java:145)
	at com.hazelcast.test.mocknetwork.MockJoinerTest.restart_multipleInParallel(MockJoinerTest.java:139)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/8738/testReport/junit/com.hazelcast.test.mocknetwork/MockJoinerTest/restart_multipleInParallel/

**Comment by metanet** [comment]
[mock.txt](https://github.com/hazelcast/hazelcast/files/989315/mock.txt)

failure logs
