### ISSUE TITLE
ExtractionInCollectionSpecTest.comparable_primitive_comparedToNull

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#10578]
```
com.hazelcast.core.HazelcastInstanceNotActiveException: State: PASSIVE Operation: class com.hazelcast.map.impl.operation.AddIndexOperation
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.engineActive(Invocation.java:467)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:500)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:490)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:200)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:59)
	at com.hazelcast.spi.impl.operationservice.impl.InvokeOnPartitions.retryFailedPartitions(InvokeOnPartitions.java:137)
	at com.hazelcast.spi.impl.operationservice.impl.InvokeOnPartitions.invoke(InvokeOnPartitions.java:73)
	at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.invokeOnAllPartitions(OperationServiceImpl.java:369)
	at com.hazelcast.map.impl.proxy.MapProxySupport.addIndex(MapProxySupport.java:1110)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.addIndex(MapProxyImpl.java:101)
	at com.hazelcast.map.impl.proxy.MapProxySupport.initializeIndexes(MapProxySupport.java:291)
	at com.hazelcast.map.impl.proxy.MapProxySupport.initialize(MapProxySupport.java:225)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.initialize(MapProxyImpl.java:101)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyRegistry.doCreateProxy(ProxyRegistry.java:194)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyRegistry.createProxy(ProxyRegistry.java:184)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyRegistry.getOrCreateProxyFuture(ProxyRegistry.java:154)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyRegistry.getOrCreateProxy(ProxyRegistry.java:135)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyServiceImpl.getDistributedObject(ProxyServiceImpl.java:147)
	at com.hazelcast.instance.HazelcastInstanceImpl.getDistributedObject(HazelcastInstanceImpl.java:380)
	at com.hazelcast.instance.HazelcastInstanceImpl.getMap(HazelcastInstanceImpl.java:186)
	at com.hazelcast.instance.HazelcastInstanceProxy.getMap(HazelcastInstanceProxy.java:96)
	at com.hazelcast.query.impl.extractor.AbstractExtractionTest.setupInstance(AbstractExtractionTest.java:119)
	at com.hazelcast.query.impl.extractor.AbstractExtractionTest.setup(AbstractExtractionTest.java:81)
	at com.hazelcast.query.impl.extractor.AbstractExtractionTest.execute(AbstractExtractionTest.java:187)
	at com.hazelcast.query.impl.extractor.specification.ExtractionInCollectionSpecTest.comparable_primitive_comparedToNull(ExtractionInCollectionSpecTest.java:265)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.8/com.hazelcast$hazelcast/587/testReport/junit/com.hazelcast.query.impl.extractor.specification/ExtractionInCollectionSpecTest/comparable_primitive_comparedToNull_4__BINARY__UNORDERED__LIST_/

**Comment by tombujok** [comment]
That's not related to the test itself, but to a cluster failure - maybe some network connection issues, etc.
