### ISSUE TITLE
NPE ClientEngineImpl.getThisUuid

### ISSUE THREAD

**Issue by pveentjer** [hazelcast/hazelcast#10615]
This is with 3.9 master

```
Exception in thread "hz._hzInstance_2_dev.cached.thread-4" java.lang.NullPointerException
	at com.hazelcast.instance.Node.getThisUuid(Node.java:727)
	at com.hazelcast.client.impl.ClientEngineImpl.getThisUuid(ClientEngineImpl.java:263)
	at com.hazelcast.client.impl.ClientHeartbeatMonitor.run(ClientHeartbeatMonitor.java:71)
	at com.hazelcast.spi.impl.executionservice.impl.DelegateAndSkipOnConcurrentExecutionDecorator$DelegateDecorator.run(DelegateAndSkipOnConcurrentExecutionDecorator.java:66)
	at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:228)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
Finished Running Test: testSockets in 10.146 seconds.
```

**Comment by pveentjer** [comment]
I guess the ClientHeartbeatMonitor starts to mess around with the Node before the node is fully initialized. And it could very well be that the ClientHeartbeatMonitor starts working after running into such an exception?
