### ISSUE TITLE
ClusterVersionInitTest

### ISSUE THREAD

**Issue by Donnerbart** [hazelcast/hazelcast#10614]
**com.hazelcast.internal.cluster.impl.ClusterVersionInitTest.test_clusterVersion_isEventuallySet_whenTcpJoinerConfiguredSingleNode**
```java
java.lang.NullPointerException: null
	at sun.nio.ch.Util.atBugLevel(Util.java:448)
	at sun.nio.ch.SelectorImpl.<init>(SelectorImpl.java:40)
	at sun.nio.ch.EPollSelectorImpl.<init>(EPollSelectorImpl.java:47)
	at sun.nio.ch.EPollSelectorProvider.openSelector(EPollSelectorProvider.java:18)
	at java.nio.channels.Selector.open(Selector.java:209)
	at com.hazelcast.internal.networking.nio.NioThread.newSelector(NioThread.java:137)
	at com.hazelcast.internal.networking.nio.NioThread.<init>(NioThread.java:117)
	at com.hazelcast.internal.networking.nio.NioEventLoopGroup.start(NioEventLoopGroup.java:163)
	at com.hazelcast.nio.tcp.TcpIpConnectionManager.start(TcpIpConnectionManager.java:417)
	at com.hazelcast.instance.Node.start(Node.java:360)
	at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:132)
	at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:195)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:174)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:124)
	at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:58)
	at com.hazelcast.internal.cluster.impl.ClusterVersionInitTest.setupInstance(ClusterVersionInitTest.java:137)
	at com.hazelcast.internal.cluster.impl.ClusterVersionInitTest.test_clusterVersion_isEventuallySet_whenTcpJoinerConfiguredSingleNode(ClusterVersionInitTest.java:85)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/9015/testReport/junit/com.hazelcast.internal.cluster.impl/ClusterVersionInitTest/test_clusterVersion_isEventuallySet_whenTcpJoinerConfiguredSingleNode/

**Comment by mdogan** [comment]
JDK issue: 
- https://bugs.openjdk.java.net/browse/JDK-6427854
- http://www-01.ibm.com/support/docview.wss?uid=swg1IV81797
