### ISSUE TITLE
[query-cache] QueryCacheInMemoryFormatTest.testObjectFormat_deserializeOneTime

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#10627]
```
java.lang.AssertionError: expected:<1> but was:<2>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.map.impl.querycache.QueryCacheInMemoryFormatTest.testInMemoryFormat(QueryCacheInMemoryFormatTest.java:85)
	at com.hazelcast.map.impl.querycache.QueryCacheInMemoryFormatTest.testObjectFormat_deserializeOneTime(QueryCacheInMemoryFormatTest.java:49)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK1.7/com.hazelcast$hazelcast/858/testReport/junit/com.hazelcast.map.impl.querycache/QueryCacheInMemoryFormatTest/testObjectFormat_deserializeOneTime/

**Comment by ahmetmircik** [comment]
not failed recently.

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: expected:<1> but was:<2>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.map.impl.querycache.QueryCacheInMemoryFormatTest.testInMemoryFormat(QueryCacheInMemoryFormatTest.java:85)
	at com.hazelcast.map.impl.querycache.QueryCacheInMemoryFormatTest.testObjectFormat_deserializeOneTime(QueryCacheInMemoryFormatTest.java:49)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-ZuluJDK7/com.hazelcast$hazelcast/665/testReport/junit/com.hazelcast.map.impl.querycache/QueryCacheInMemoryFormatTest/testObjectFormat_deserializeOneTime/

**Comment by tombujok** [comment]
Closing this one, added reasoning and more debug here: https://github.com/hazelcast/hazelcast/pull/11326
