### ISSUE TITLE
No DataSerializerFactory registered for namespace: -2000

### ISSUE THREAD

**Issue by gionn** [hazelcast/hazelcast#10646]
Hi,

during the process of migrating a java 8 web application using hazelcast also as 2nd-level cache hibernate from a standalone WAR deployed on tomcat 7 to standalone shaded jar with jetty embedded, I got the following stacktrace on every interaction with application:

```
May 25, 2017 9:36:09 AM com.hazelcast.client.spi.ClientListenerService
SEVERE: hz.client_0 [cmw] [3.8.2] hz.client_0.event-7 caught an exception while processing task:com.hazelcast.client.spi.impl.listener.ClientListenerServiceImpl$ClientEventProcessor@242241
com.hazelcast.nio.serialization.HazelcastSerializationException: No DataSerializerFactory registered for namespace: -2000
        at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.readInternal(DataSerializableSerializer.java:134)
        at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:103)
        at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:49)
        at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48)
        at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:184)
        at com.hazelcast.topic.impl.DataAwareMessage.getMessageObject(DataAwareMessage.java:44)
        at com.hazelcast.hibernate.local.LocalRegionCache$1.onMessage(LocalRegionCache.java:214)
        at com.hazelcast.client.proxy.ClientTopicProxy$TopicItemHandler.handle(ClientTopicProxy.java:90)
        at com.hazelcast.client.impl.protocol.codec.TopicAddMessageListenerCodec$AbstractEventHandler.handle(TopicAddMessageListenerCodec.java:145)
        at com.hazelcast.client.proxy.ClientTopicProxy$TopicItemHandler.handle(ClientTopicProxy.java:75)
        at com.hazelcast.client.spi.impl.listener.ClientListenerServiceImpl$ClientEventProcessor.run(ClientListenerServiceImpl.java:134)
        at com.hazelcast.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:217)
        at com.hazelcast.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:200)
```

these are the dependencies I am using:

```
		<dependency>
			<groupId>com.hazelcast</groupId>
			<artifactId>hazelcast</artifactId>
			<version>${hazelcast.version}</version>
		</dependency>
		<dependency>
			<groupId>com.hazelcast</groupId>
			<artifactId>hazelcast</artifactId>
			<version>${hazelcast.version}</version>
			<scope>test</scope>
			<classifier>tests</classifier>
		</dependency>
		<dependency>
			<groupId>com.hazelcast</groupId>
			<artifactId>hazelcast-spring</artifactId>
			<version>${hazelcast.version}</version>
		</dependency>
		<dependency>
			<groupId>com.hazelcast</groupId>
			<artifactId>hazelcast-client</artifactId>
			<version>${hazelcast.version}</version>
		</dependency>
		<dependency>
			<groupId>com.hazelcast</groupId>
			<artifactId>hazelcast-hibernate5</artifactId>
			<version>1.2.1</version>
		</dependency>
```

Tried with version 3.8.2 and 3.7.6.

Application behaviour is not changing, probably just the 2nd level cache is not working at all.

Any suggestions?

Thanks!

**Comment by vbekiaris** [comment]
Hi @gionn , from your description it looks like you're creating a fat-jar with all dependencies included, right? If that's the case, then the problem is that service definition files (in `META-INF/services` path) included in `hazelcast-hibernate5` artifact are overwritten by those in other artifacts (`hazelcast` JAR also specifies services for `com.data.DataSerializerHook`s --> one of the two overlapping files is included in the final jar).
I don't know how that might fit in your packaging process, however the resulting JAR must have the contents of each service definition files merged instead of overwritten, so all the services from each individual dependency are picked up at runtime in the final JAR.

**Comment by gionn** [comment]
Hi @vbekiaris, I've added a transformer to the maven-shade-plugin configuration:

```
<transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
    <resource>META-INF/services/com.hazelcast.DataSerializerHook</resource>
</transformer>
```

and exceptions are gone.

Thanks!

**Comment by vbekiaris** [comment]
Great, thanks for the heads up!

**Comment by htejwani** [comment]
Hi @vbekiaris,
Do you have any idea on how to use this with Spring Boot? I added a maven-shade-plugin in my spring boot application with the transformer configuration that you have provided. But it doesn't seem to work. It's throwing the same exception. Thanks.
