### ISSUE TITLE
MembershipFailureTest.slave_master_confirmation_timeout

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#10657]
```
java.lang.AssertionError: Cluster size is not correct. Expected: 2 Actual: 1
	at org.junit.Assert.fail(Assert.java:88)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSize(HazelcastTestSupport.java:870)
	at com.hazelcast.test.HazelcastTestSupport$12.run(HazelcastTestSupport.java:892)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1041)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:888)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:882)
	at com.hazelcast.internal.cluster.impl.MembershipFailureTest.slave_master_confirmation_timeout(MembershipFailureTest.java:370)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-ZuluJDK6-freestyle/116/testReport/junit/com.hazelcast.internal.cluster.impl/MembershipFailureTest/slave_master_confirmation_timeout/

**Comment by mdogan** [comment]
There are huge pauses during the test:

```
[InvocationMonitor] [127.0.0.1]:17237 [dev] [3.9-SNAPSHOT] MonitorInvocationsTask delayed 67093 ms
[InvocationMonitor] [127.0.0.1]:17237 [dev] [3.9-SNAPSHOT] BroadcastOperationControlTask delayed 67093 ms
[InvocationMonitor] [127.0.0.1]:17249 [dev] [3.9-SNAPSHOT] MonitorInvocationsTask delayed 67365 ms
[InvocationMonitor] [127.0.0.1]:17249 [dev] [3.9-SNAPSHOT] BroadcastOperationControlTask delayed 65349 ms
[InvocationMonitor] [127.0.0.1]:17272 [dev] [3.9-SNAPSHOT] MonitorInvocationsTask delayed 67766 ms
[InvocationMonitor] [127.0.0.1]:17272 [dev] [3.9-SNAPSHOT] BroadcastOperationControlTask delayed 59765 ms

[ClusterHeartbeatManager] [127.0.0.1]:17272 [dev] [3.9-SNAPSHOT] Resetting master confirmation timestamps because of huge system clock jump! Clock-Jump: 67767 ms, Master-Confirmation-Timeout: 15000 ms
[ClusterHeartbeatManager] [127.0.0.1]:17272 [dev] [3.9-SNAPSHOT] Resetting heartbeat timestamps because of huge system clock jump! Clock-Jump: 67767 ms, Heartbeat-Timeout: 15000 ms
[ClusterHeartbeatManager] [127.0.0.1]:17249 [dev] [3.9-SNAPSHOT] Resetting master confirmation timestamps because of huge system clock jump! Clock-Jump: 72340 ms, Master-Confirmation-Timeout: 15000 ms
[ClusterHeartbeatManager] [127.0.0.1]:17249 [dev] [3.9-SNAPSHOT] Resetting heartbeat timestamps because of huge system clock jump! Clock-Jump: 72340 ms, Heartbeat-Timeout: 15000 ms
[ClusterHeartbeatManager] [127.0.0.1]:17237 [dev] [3.9-SNAPSHOT] Resetting master confirmation timestamps because of huge system clock jump! Clock-Jump: 72069 ms, Master-Confirmation-Timeout: 15000 ms
[ClusterHeartbeatManager] [127.0.0.1]:17237 [dev] [3.9-SNAPSHOT] Resetting heartbeat timestamps because of huge system clock jump! Clock-Jump: 72069 ms, Heartbeat-Timeout: 15000 ms
```

```
03:48:00, accumulated pauses: 72833 ms, max pause: 72795 ms, pauses over 1000 ms: 1
```

**Comment by mdogan** [comment]
This test is built on and testing master confirmation timeout but because of large pause (~73 sec) during the test, timeouts didn't work as expected. That's why test failure happened.
