### ISSUE TITLE
[cluster] MembershipFailureTest_withTCP.test_whenNodesStartedTerminatedConcurrently

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#10658]
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.internal.cluster.impl.MembershipFailureTest.startInstancesConcurrently(MembershipFailureTest.java:727)
	at com.hazelcast.internal.cluster.impl.MembershipFailureTest.test_whenNodesStartedTerminatedConcurrently(MembershipFailureTest.java:704)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
```

https://hazelcast-l337.ci.cloudbees.com/view/Sonar/job/Hazelcast-3.x-sonar/com.hazelcast$hazelcast/1508/testReport/junit/com.hazelcast.internal.cluster.impl/MembershipFailureTest_withTCP/test_whenNodesStartedTerminatedConcurrently/

https://hazelcast-l337.ci.cloudbees.com/view/Sonar/job/Hazelcast-3.x-sonar/com.hazelcast$hazelcast/1512/testReport/junit/com.hazelcast.internal.cluster.impl/MembershipFailureTest_withTCP/test_whenNodesStartedTerminatedConcurrently/

**Comment by mdogan** [comment]
Cause of the failure:
```
java.lang.NullPointerException
	at com.hazelcast.cluster.impl.TcpIpJoiner.getConfigurationMembers(TcpIpJoiner.java:491) ~[classes/:?]
	at com.hazelcast.cluster.impl.TcpIpJoiner.getMembers(TcpIpJoiner.java:482) ~[classes/:?]
	at com.hazelcast.cluster.impl.TcpIpJoiner.getPossibleAddresses(TcpIpJoiner.java:398) ~[classes/:?]
	at com.hazelcast.cluster.impl.TcpIpJoiner.joinViaPossibleMembers(TcpIpJoiner.java:130) [classes/:?]
	at com.hazelcast.cluster.impl.TcpIpJoiner.doJoin(TcpIpJoiner.java:89) [classes/:?]
	at com.hazelcast.internal.cluster.impl.AbstractJoiner.join(AbstractJoiner.java:133) [classes/:?]
	at com.hazelcast.instance.Node.join(Node.java:680) [classes/:?]
	at com.hazelcast.instance.Node.start(Node.java:380) [classes/:?]
	at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:132) [classes/:?]
	at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:195) [classes/:?]
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:174) [classes/:?]
	at com.hazelcast.internal.cluster.impl.MembershipFailureTest_withTCP.newHazelcastInstance(MembershipFailureTest_withTCP.java:53) [test-classes/:?]
	at com.hazelcast.internal.cluster.impl.MembershipFailureTest$8.run(MembershipFailureTest.java:722) [test-classes/:?]
```

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: Cluster size is not correct. Expected: 4 Actual: 2
	at org.junit.Assert.fail(Assert.java:88)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSize(HazelcastTestSupport.java:941)
	at com.hazelcast.test.HazelcastTestSupport$13.run(HazelcastTestSupport.java:962)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1133)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:959)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:953)
	at com.hazelcast.internal.cluster.impl.MembershipFailureTest.test_whenNodesStartedTerminatedConcurrently(MembershipFailureTest.java:728)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/1517/testReport/junit/com.hazelcast.internal.cluster.impl/MembershipFailureTest_withTCP/test_whenNodesStartedTerminatedConcurrently_fd_phi_accrual_/

**Comment by mdogan** [comment]
I have tried to reproduce this issue (for a few hours) but not able to yet. Closing for now, there are no    recurring failures.
