### ISSUE TITLE
TransactionQueueTest.transactionShouldBeRolledBack_whenInitiatorTerminatesBeforeCommit

### ISSUE THREAD

**Issue by Donnerbart** [hazelcast/hazelcast#10663]
**com.hazelcast.collection.impl.txnqueue.TransactionQueueTest.transactionShouldBeRolledBack_whenInitiatorTerminatesBeforeCommit**
```java
java.lang.AssertionError: expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.collection.impl.txnqueue.TransactionQueueTest$8.run(TransactionQueueTest.java:541)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1041)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1058)
	at com.hazelcast.collection.impl.txnqueue.TransactionQueueTest.transactionShouldBeRolledBack_whenInitiatorTerminatesBeforeCommit(TransactionQueueTest.java:538)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/9162/testReport/junit/com.hazelcast.collection.impl.txnqueue/TransactionQueueTest/transactionShouldBeRolledBack_whenInitiatorTerminatesBeforeCommit/

**Comment by sancar** [comment]
Failed on my pr twice. 
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/9270/

```
Error Message

expected:<1> but was:<0>
Stacktrace

java.lang.AssertionError: expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.collection.impl.txnqueue.TransactionQueueTest$8.run(TransactionQueueTest.java:541)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1041)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1058)
	at com.hazelcast.collection.impl.txnqueue.TransactionQueueTest.transactionShouldBeRolledBack_whenInitiatorTerminatesBeforeCommit(TransactionQueueTest.java:538)
```

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.collection.impl.txnqueue.TransactionQueueTest$8.run(TransactionQueueTest.java:541)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1041)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1058)
	at com.hazelcast.collection.impl.txnqueue.TransactionQueueTest.transactionShouldBeRolledBack_whenInitiatorTerminatesBeforeCommit(TransactionQueueTest.java:538)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-ZuluJDK6-freestyle/125/testReport/junit/com.hazelcast.collection.impl.txnqueue/TransactionQueueTest/transactionShouldBeRolledBack_whenInitiatorTerminatesBeforeCommit/

**Comment by hasancelik** [comment]
**maintenance**
```
java.lang.AssertionError: expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.collection.impl.txnqueue.TransactionQueueTest$8.run(TransactionQueueTest.java:541)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:988)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1005)
	at com.hazelcast.collection.impl.txnqueue.TransactionQueueTest.transactionShouldBeRolledBack_whenInitiatorTerminatesBeforeCommit(TransactionQueueTest.java:538)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-ZuluJDK8/com.hazelcast$hazelcast/214/testReport/junit/com.hazelcast.collection.impl.txnqueue/TransactionQueueTest/transactionShouldBeRolledBack_whenInitiatorTerminatesBeforeCommit/
