### ISSUE TITLE
implement PartitionPredicate, MemberPredicate

### ISSUE THREAD

**Issue by dsukhoroslov** [hazelcast/hazelcast#10673]
they could be quite usefull in some cases, in conjunction with other regular predicates, when someone does know that the data he is looking for is cached on  particular member(s) or in particular partition(s). the simplest implementation could do something like this:
```
public boolean apply(Map.Entry<K, V> mapEntry) {
        PartitionService ps = ...;
	return partitionId == partService.getPartition(mapEntry.getKey()).getPartitionId());
}
```
but it wold be much more effective to run this predicate on the specified member(s)/partition(s) only. Is this achiveable?

Thanks, Denis.

**Comment by dsukhoroslov** [comment]
I could implement them if someone point me where to start with.

**Comment by tombujok** [comment]
There is a PartitionPredicate already. Could you maybe look into it?
https://github.com/tombujok/hazelcast/blob/16bd03c7794322b5989d1bd5641c80352c1117cb/hazelcast/src/main/java/com/hazelcast/query/PartitionPredicate.java#L41-L41

Maybe we need to improve doc on this one. This predicate is not supported in all methods that accept predicates. I guess the MemberPredicate could be implemented in a similar way.

**Comment by dsukhoroslov** [comment]
Hi @tombujok 
Thanks for pointing me on this. Yes, it looks like what I need. But does not work, unfortunately. I build a predicate and run query as follows:
```
	Query query = new Query(CN_XDM_DOCUMENT, new PartitionPredicate(uri.hashCode(), Predicates.equal("uri", uri)), IterationType.KEY, null, null);
	QueryResult rs = (QueryResult) mapCtx.getMapQueryRunner(CN_XDM_DOCUMENT).runIndexOrPartitionScanQueryOnOwnedPartitions(query);
```
and got an exception:
```
     [java] java.lang.UnsupportedOperationException: null
     [java]     at com.hazelcast.query.PartitionPredicate.apply(PartitionPredicate.java:83) ~[hazelcast-all-3.8.2.jar:3.8.2]
     [java]     at com.hazelcast.map.impl.query.PartitionScanRunner.run(PartitionScanRunner.java:94) ~[hazelcast-all-3.8.2.jar:3.8.2]
     [java]     at com.hazelcast.map.impl.query.ParallelPartitionScanExecutor$QueryPartitionCallable.call(ParallelPartitionScanExecutor.java:104) ~[hazelcast-all-3.8.2.jar:3.8.2]
     [java]     at com.hazelcast.map.impl.query.ParallelPartitionScanExecutor$QueryPartitionCallable.call(ParallelPartitionScanExecutor.java:91) ~[hazelcast-all-3.8.2.jar:3.8.2]
     [java]     at com.hazelcast.util.executor.CompletableFutureTask.run(CompletableFutureTask.java:67) ~[hazelcast-all-3.8.2.jar:3.8.2]
     [java]     at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:228) ~[hazelcast-all-3.8.2.jar:3.8.2]
     [java]     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_74]
..........
```
In general, it would be nice to have PartitionAware predicates. The PartitionPredicate mentioned above could also implement this interface.

**Comment by mmedenjak** [comment]
@dsukhoroslov you should use one of the methods : 
`com.hazelcast.core.IMap#keySet(com.hazelcast.query.Predicate)`
`com.hazelcast.core.IMap#entrySet(com.hazelcast.query.Predicate)`
`com.hazelcast.core.IMap#values(com.hazelcast.query.Predicate)`
because the `PartitionPredicate` is unwrapped in `com.hazelcast.map.impl.proxy.MapProxyImpl#executePredicate`. Calling the map query runner directly will cause the exception. Can you try calling the methods in `IMap`?

**Comment by dsukhoroslov** [comment]
@mmedenjak yes, it does work in this way. But ususaly I have to search for values from EntryProcessor which is already working in the partition thread. Do you have some low-level API to do this?

**Comment by mmedenjak** [comment]
@dsukhoroslov no, there is no such API. If you really need to do it, you could try getting the record store (by casting and invoking private API) and use it's methods - see what the GetOperation and HDGetOperation do in the `run` method. But that's very much private API and we don't provide any backwards compatibility there.

**Comment by silvaran** [comment]
It's unfortunately not supported by TransactionalMap either.  For IMap, it gets unwrapped in MapProxySupport.executeQueryInternal:
<pre>        if (predicate instanceof PartitionPredicate) {
            PartitionPredicate partitionPredicate = (PartitionPredicate) predicate;
            Data key = toData(partitionPredicate.getPartitionKey());
            int partitionId = partitionService.getPartitionId(key);
            userPredicate = partitionPredicate.getTarget();
            target = Target.of().partitionOwner(partitionId).build();
        }</pre>
That could be copied with a few modifications to TransactionalMapProxy.keySet( Predicate ) and TransactionalMapProxy.values( Predicate ).
