### ISSUE TITLE
Failed to serialize 'com.hazelcast.collection.impl.set.SetProxyImpl' when using IMap<Long, ISet<Long>> hazelcastMap = hz.getMap("myMap");

### ISSUE THREAD

**Issue by swapnilgangrade01** [hazelcast/hazelcast#10693]
Hi I am using Hazelcast IMap and as a value I am using Hazelcast ISet but when I am trying to put the value in map there is exception. Below is my method.

```
private static void testJavaMapvsHazelcastIMap() {
    HazelcastInstance hz = Hazelcast.getOrCreateHazelcastInstance(new Config("a"));

    try {
        IMap<Long, ISet<Long>> hazelcastMap = hz.getMap("myMap");
        Map<Long, Set<Long>> javaMap = new HashMap<Long, Set<Long>>();
        Set<Long> javaSet = new HashSet<Long>();
        ISet<Long> hazelcastSet = hz.getSet("hazelcastSet");
        for (long i = 0; i < 10; i++) {
            javaSet.add(i);
            hazelcastSet.add(i);
        }
        long a = 1;
        javaMap.put(a, javaSet);
        //Getting error at this line...
        hazelcastMap.put(a, hazelcastSet);
    } finally {
         hz.shutdown();
    }

}
```

Exception is below.
Exception in thread "main" com.hazelcast.nio.serialization.HazelcastSerializationException: Failed to serialize 'com.hazelcast.collection.impl.set.SetProxyImpl'
	at com.hazelcast.internal.serialization.impl.SerializationUtil.handleSerializeException(SerializationUtil.java:73)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:154)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:135)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toData(AbstractSerializationService.java:119)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toData(AbstractSerializationService.java:107)
	at com.hazelcast.spi.impl.NodeEngineImpl.toData(NodeEngineImpl.java:350)
	at com.hazelcast.spi.AbstractDistributedObject.toData(AbstractDistributedObject.java:67)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.put(MapProxyImpl.java:128)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.put(MapProxyImpl.java:119)
	at com.hezelcast.connect.TestClass.testJavaMapvsHazelcastIMap(TestClass.java:87)
	at com.hezelcast.connect.TestClass.main(TestClass.java:17)
Caused by: com.hazelcast.nio.serialization.HazelcastSerializationException: There is no suitable serializer for class com.hazelcast.collection.impl.set.SetProxyImpl
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.serializerFor(AbstractSerializationService.java:484)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:145)
	... 9 more

```
```

**Comment by jerrinot** [comment]
hi @swapnilgangrade01,

you can put Hazelcast `ISet` into `IMap`. I can recommend you to look at [MultiMap](http://docs.hazelcast.org/docs/3.8.2/manual/html-single/index.html#multimap)
