### ISSUE TITLE
Max pool size must be positive! with openjdk 8u131 within docker container

### ISSUE THREAD

**Issue by gionn** [hazelcast/hazelcast#10704]
Hi,

I am running a java app with hazelcast 3.8.2 within docker, and after switching from `openjdk:8u121-jre-alpine` to `openjdk:8u131-jre-alpine`, I've started to get the following stacktrace during cluster bootstrap:

```
Caused by: java.lang.IllegalArgumentException: Max pool size must be positive!
  at com.hazelcast.util.executor.CachedExecutorServiceDelegate.<init>(CachedExecutorServiceDelegate.java:65)
  at com.hazelcast.spi.impl.executionservice.impl.ExecutionServiceImpl.createExecutor(ExecutionServiceImpl.java:199)
  at com.hazelcast.spi.impl.executionservice.impl.ExecutionServiceImpl.register(ExecutionServiceImpl.java:186)
  at com.hazelcast.spi.impl.executionservice.impl.ExecutionServiceImpl.<init>(ExecutionServiceImpl.java:148)
  at com.hazelcast.spi.impl.NodeEngineImpl.<init>(NodeEngineImpl.java:134)
  at com.hazelcast.instance.Node.<init>(Node.java:204)
  at com.hazelcast.instance.HazelcastInstanceImpl.createNode(HazelcastInstanceImpl.java:159)
  at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:127)
  at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:218)
  at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:176)
  at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:126)
```

After googling a bit, it looks like that some jvm behaviour is changed in u131 when the app is run inside a container.

ref:
https://bugs.openjdk.java.net/browse/JDK-8140793
https://blogs.oracle.com/developers/official-docker-image-for-oracle-java-and-the-openjdk-roadmap-for-containers

**Comment by lazerion** [comment]
@gionn Hi,
I will look into it, however it would be greate if you could share ```Dockerfile``` with us?

**Comment by gionn** [comment]
It's a spring boot application, so Dockerfile is really simple:

```
FROM openjdk:8u131-jre-alpine
ADD target/app.jar /usr/local/java/app.jar
CMD exec java -jar /usr/local/java/app.jar
```

Thanks!

**Comment by lazerion** [comment]
Hi @gionn 
I have changed our OSS docker image to `openjdk:8u131-jre-alpine` and shebang.
Instance is up, could you please check java -version on failing container.

```
docker exec <container-id> java -version
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (IcedTea 3.4.0) (Alpine 8.131.11-r1)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)
```

**Comment by gionn** [comment]
You are right, it looks like that I trigger the bug only when running integration tests in CircleCI 1.0, probably this is glitch in their Docker environment with updated jvm and not an hazelcast fault.

Thanks for your support @lazerion!

**Comment by lazerion** [comment]
@gionn You're welcome.
