### ISSUE TITLE
Older versions of Mulesoft clash with Hazelcast Client Classpath

### ISSUE THREAD

**Issue by dbrimley** [hazelcast/hazelcast#10706]
@jerrinot fixed classpath issues Mulesoft ESB 3.8 from Hazelcast 3.8.1 Client onwards.

However we've now encountered issues with some users on Mulesoft 3.7, which we believe may be using Hazelcast 3.5 in it classpath.

The following stack trace shows an issue when using Mule * Version: 3.7.3 Build: b7977ef2 * and Hazelcast Client 3.8.2

The exception occurs when calling...

```HazelcastInstance client = HazelcastClient.newHazelcastClient(clientConfig)```

Inside of a Mule Component Callback

```
Jun 05, 2017 9:07:38 AM com.hazelcast.core.LifecycleService

INFO: hz.client_0 [dev] [3.8.2] HazelcastClient 3.8.2 (20170518 - a60f944) is STARTING

ERROR 2017-06-05 09:08:30,412 [[mule-currency-cache-reader].HTTP_Listener_Configuration.worker.01] org.mule.exception.DefaultMessagingExceptionStrategy:

********************************************************************************

Message : Component that caused exception is: DefaultJavaComponent{currencies.component.1302459274}. Message payload is of type: NullPayload

Type : org.mule.component.ComponentException

Code : MULE_ERROR--2

JavaDoc : http://www.mulesoft.org/docs/site/current3/apidocs/org/mule/component/ComponentException.html

Payload : {NullPayload}

********************************************************************************

Exception stack is:

1. Class com.hazelcast.multimap.MultiMapPortableHook does not implement com.hazelcast.internal.serialization.PortableHook (java.lang.ClassCastException)

com.hazelcast.util.ServiceLoader$ClassIterator:436 (null)

2. Component that caused exception is: DefaultJavaComponent{currencies.component.1302459274}. Message payload is of type: NullPayload (org.mule.component.ComponentException)

org.mule.component.DefaultComponentLifecycleAdapter:348 (http://www.mulesoft.org/docs/site/current3/apidocs/org/mule/component/ComponentException.html)

********************************************************************************

Root Exception stack trace:

java.lang.ClassCastException: Class com.hazelcast.multimap.MultiMapPortableHook does not implement com.hazelcast.internal.serialization.PortableHook

at com.hazelcast.util.ServiceLoader$ClassIterator.onNonAssignableClass(ServiceLoader.java:436)

at com.hazelcast.util.ServiceLoader$ClassIterator.advance(ServiceLoader.java:394)

at com.hazelcast.util.ServiceLoader$ClassIterator.hasNext(ServiceLoader.java:379)

at com.hazelcast.util.ServiceLoader$NewInstanceIterator.hasNext(ServiceLoader.java:326)

at com.hazelcast.internal.serialization.impl.PortableHookLoader.load(PortableHookLoader.java:50)

at com.hazelcast.internal.serialization.impl.PortableHookLoader.<init>(PortableHookLoader.java:44)

at com.hazelcast.internal.serialization.impl.SerializationServiceV1.<init>(SerializationServiceV1.java:95)

at com.hazelcast.internal.serialization.impl.DefaultSerializationServiceBuilder.createSerializationService(DefaultSerializationServiceBuilder.java:267)

at com.hazelcast.internal.serialization.impl.DefaultSerializationServiceBuilder.build(DefaultSerializationServiceBuilder.java:221)

at com.hazelcast.internal.serialization.impl.DefaultSerializationServiceBuilder.build(DefaultSerializationServiceBuilder.java:49)

at com.hazelcast.client.impl.DefaultClientExtension.createSerializationService(DefaultClientExtension.java:85)

at com.hazelcast.client.impl.HazelcastClientInstanceImpl.<init>(HazelcastClientInstanceImpl.java:218)

at com.hazelcast.client.HazelcastClient$1.createHazelcastInstanceClient(HazelcastClient.java:55)

at com.hazelcast.client.HazelcastClientManager.newHazelcastClient(HazelcastClientManager.java:74)

at com.hazelcast.client.HazelcastClient.newHazelcastClient(HazelcastClient.java:72)

at CurrencyMap.onCall(CurrencyMap.java:27)

at org.mule.model.resolvers.CallableEntryPointResolver.invoke(CallableEntryPointResolver.java:46)

at org.mule.model.resolvers.DefaultEntryPointResolverSet.invoke(DefaultEntryPointResolverSet.java:36)

at org.mule.component.DefaultComponentLifecycleAdapter.invoke(DefaultComponentLifecycleAdapter.java:339)

at org.mule.component.AbstractJavaComponent.invokeComponentInstance(AbstractJavaComponent.java:82)

at org.mule.component.AbstractJavaComponent.doInvoke(AbstractJavaComponent.java:73)

at org.mule.component.AbstractComponent.invokeInternal(AbstractComponent.java:120)

at org.mule.component.AbstractComponent.access$000(AbstractComponent.java:55)

at org.mule.component.AbstractComponent$1$1.process(AbstractComponent.java:236)

at org.mule.execution.ExceptionToMessagingExceptionExecutionInterceptor.execute(ExceptionToMessagingExceptionExecutionInterceptor.java:24)

at org.mule.execution.MessageProcessorNotificationExecutionInterceptor.execute(MessageProcessorNotificationExecutionInterceptor.java:107)

at org.mule.execution.MessageProcessorExecutionTemplate.execute(MessageProcessorExecutionTemplate.java:44)

at org.mule.processor.BlockingProcessorExecutor.executeNext(BlockingProcessorExecutor.java:88)

at org.mule.processor.BlockingProcessorExecutor.execute(BlockingProcessorExecutor.java:59)

at org.mule.execution.ExceptionToMessagingExceptionExecutionInterceptor.execute(ExceptionToMessagingExceptionExecutionInterceptor.java:24)

at org.mule.execution.MessageProcessorNotificationExecutionInterceptor.execute(MessageProcessorNotificationExecutionInterceptor.java:107)

at org.mule.execution.MessageProcessorExecutionTemplate.execute(MessageProcessorExecutionTemplate.java:44)

at org.mule.component.AbstractComponent.process(AbstractComponent.java:154)

at org.mule.execution.ExceptionToMessagingExceptionExecutionInterceptor.execute(ExceptionToMessagingExceptionExecutionInterceptor.java:24)

at org.mule.execution.MessageProcessorNotificationExecutionInterceptor.execute(MessageProcessorNotificationExecutionInterceptor.java:107)

at org.mule.execution.MessageProcessorExecutionTemplate.execute(MessageProcessorExecutionTemplate.java:44)

at org.mule.processor.BlockingProcessorExecutor.executeNext(BlockingProcessorExecutor.java:98)

at org.mule.processor.BlockingProcessorExecutor.execute(BlockingProcessorExecutor.java:59)

at org.mule.execution.ExceptionToMessagingExceptionExecutionInterceptor.execute(ExceptionToMessagingExceptionExecutionInterceptor.java:24)

at org.mule.execution.MessageProcessorExecutionTemplate.execute(MessageProcessorExecutionTemplate.java:44)

at org.mule.processor.BlockingProcessorExecutor.executeNext(BlockingProcessorExecutor.java:98)

at org.mule.processor.BlockingProcessorExecutor.execute(BlockingProcessorExecutor.java:59)

at org.mule.processor.AsyncInterceptingMessageProcessor.process(AsyncInterceptingMessageProcessor.java:102)

at org.mule.execution.ExceptionToMessagingExceptionExecutionInterceptor.execute(ExceptionToMessagingExceptionExecutionInterceptor.java:24)

at org.mule.execution.MessageProcessorNotificationExecutionInterceptor.execute(MessageProcessorNotificationExecutionInterceptor.java:107)

at org.mule....
```

**Comment by dbrimley** [comment]
It looks like mule 3.6 compatibility will also be a requirement so we should fix for mule 3.7.x and mule 3.6.x
