### ISSUE TITLE
[near-cache] ClientMapNearCachePreloaderTest.testStoreAndLoad_withIntegerKeys & withStringKeys

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#10732]
```
ava.lang.AssertionError: Near Cache size didn't reach the desired value (2342 vs. 2300) (NearCacheStatsImpl{ownedEntryCount=2300, ownedEntryMemoryCost=0, creationTime=1497226625322, hits=0, misses=2342, ratio=0.0%, evictions=0, expirations=0, lastPersistenceTime=1497226747340, persistenceCount=60, lastPersistenceDuration=18, lastPersistenceWrittenBytes=36800, lastPersistenceKeyCount=2300, lastPersistenceFailure=''}) expected:<2342> but was:<2300>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils.assertNearCacheSize(NearCacheTestUtils.java:317)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils$3.run(NearCacheTestUtils.java:337)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1053)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1070)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils.assertNearCacheSizeEventually(NearCacheTestUtils.java:334)
	at com.hazelcast.internal.nearcache.AbstractNearCachePreloaderTest.storeAndLoad(AbstractNearCachePreloaderTest.java:160)
	at com.hazelcast.internal.nearcache.AbstractNearCachePreloaderTest.testStoreAndLoad_withIntegerKeys(AbstractNearCachePreloaderTest.java:131)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)

```

https://hazelcast-l337.ci.cloudbees.com/view/Sonar/job/Hazelcast-3.x-sonar/1526/

**Comment by Donnerbart** [comment]
From the logs it looks like everything was loaded beside the last batch. So either the timeout is slightly too short or there is a bug in the batch handling. I've increased the timeout to 10 minutes, which should really be enough even for a system with slow I/O and concurrent test execution: https://github.com/hazelcast/hazelcast/commit/56b89110d4a3a64b76e35cc9bf939589bf62744e

**Comment by hasancelik** [comment]
*maintenance*
```
java.lang.AssertionError: Near Cache size didn't reach the desired value (2342 vs. 2340) (NearCacheStatsImpl{ownedEntryCount=2340, ownedEntryMemoryCost=349890, creationTime=1498949081527, hits=0, misses=2342, ratio=0.0%, evictions=0, expirations=0, lastPersistenceTime=1498949203542, persistenceCount=60, lastPersistenceDuration=14, lastPersistenceWrittenBytes=37440, lastPersistenceKeyCount=2340, lastPersistenceFailure=''}) expected:<2342> but was:<2340>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils.assertNearCacheSize(NearCacheTestUtils.java:361)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils$3.run(NearCacheTestUtils.java:381)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:988)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1005)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils.assertNearCacheSizeEventually(NearCacheTestUtils.java:378)
	at com.hazelcast.internal.nearcache.AbstractNearCachePreloaderTest.storeAndLoad(AbstractNearCachePreloaderTest.java:160)
	at com.hazelcast.internal.nearcache.AbstractNearCachePreloaderTest.testStoreAndLoad_withIntegerKeys(AbstractNearCachePreloaderTest.java:131)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.lang.Thread.run(Thread.java:745)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-nightly/com.hazelcast$hazelcast-client/1269/testReport/junit/com.hazelcast.client.map.impl.nearcache/ClientMapNearCachePreloaderTest/testStoreAndLoad_withIntegerKeys_format_BINARY_invalidationOnChange_true_/

**Comment by hasancelik** [comment]
*sonar*
```
java.lang.AssertionError: Near Cache size didn't reach the desired value (2342 vs. 2340) (NearCacheStatsImpl{ownedEntryCount=2340, ownedEntryMemoryCost=275010, creationTime=1498868457145, hits=0, misses=2342, ratio=0.0%, evictions=0, expirations=0, lastPersistenceTime=1498868579161, persistenceCount=60, lastPersistenceDuration=16, lastPersistenceWrittenBytes=37440, lastPersistenceKeyCount=2340, lastPersistenceFailure=''}) expected:<2342> but was:<2340>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils.assertNearCacheSize(NearCacheTestUtils.java:364)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils$3.run(NearCacheTestUtils.java:384)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1064)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1081)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils.assertNearCacheSizeEventually(NearCacheTestUtils.java:381)
	at com.hazelcast.internal.nearcache.AbstractNearCachePreloaderTest.storeAndLoad(AbstractNearCachePreloaderTest.java:160)
	at com.hazelcast.internal.nearcache.AbstractNearCachePreloaderTest.testStoreAndLoad_withIntegerKeys(AbstractNearCachePreloaderTest.java:131)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
```

https://hazelcast-l337.ci.cloudbees.com/view/Sonar/job/Hazelcast-3.x-sonar/com.hazelcast$hazelcast-client/1547/testReport/junit/com.hazelcast.client.map.impl.nearcache/ClientMapNearCachePreloaderTest/testStoreAndLoad_withIntegerKeys_format_BINARY_invalidationOnChange_true_serializeKeys_false_/

**Comment by hasancelik** [comment]
*maintenance*
```
java.lang.AssertionError: Near Cache size didn't reach the desired value (2342 vs. 2322) (NearCacheStatsImpl{ownedEntryCount=2322, ownedEntryMemoryCost=0, creationTime=1499122787082, hits=0, misses=2342, ratio=0.0%, evictions=0, expirations=0, lastPersistenceTime=1499122909095, persistenceCount=60, lastPersistenceDuration=13, lastPersistenceWrittenBytes=37152, lastPersistenceKeyCount=2322, lastPersistenceFailure=''}) expected:<2342> but was:<2322>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils.assertNearCacheSize(NearCacheTestUtils.java:361)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils$3.run(NearCacheTestUtils.java:381)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:988)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1005)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils.assertNearCacheSizeEventually(NearCacheTestUtils.java:378)
	at com.hazelcast.internal.nearcache.AbstractNearCachePreloaderTest.storeAndLoad(AbstractNearCachePreloaderTest.java:160)
	at com.hazelcast.internal.nearcache.AbstractNearCachePreloaderTest.testStoreAndLoad_withIntegerKeys(AbstractNearCachePreloaderTest.java:131)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.lang.Thread.run(Thread.java:745)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-nightly/com.hazelcast$hazelcast-client/1271/testReport/junit/com.hazelcast.client.map.impl.nearcache/ClientMapNearCachePreloaderTest/testStoreAndLoad_withIntegerKeys_format_OBJECT_invalidationOnChange_true_/

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-nightly/1275/

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-nightly/1276/#showFailuresLink
