### ISSUE TITLE
[near-cache] com.hazelcast.core.HazelcastException: Cannot acquire lock on. NearCachePreloaderLock create use distributed object destroy

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#10759]
I have started this job, running some test after all the merging, https://hazelcast-l337.ci.cloudbees.com/view/stable/job/stable-All/46/console

a new fail is from 
`/disk1/jenkins/workspace/stable-All/3.9-SNAPSHOT/2017_06_13-17_35_05/stable/destroy/create-use-dist-destroy Failed`
http://54.163.63.218/~jenkins/workspace/stable-All/3.9-SNAPSHOT/2017_06_13-17_35_05/stable/destroy/create-use-dist-destroy

`HzClient1HZ _create-use-dist-destroy_createUseDistDestroy_mapBak1 hzcmd.map.CreateUse threadId=0 com.hazelcast.core.HazelcastException: Cannot acquire lock on /home/ec2-user/hz-root/HzClient1HZ/nearCache-mapBak1createUseDestroy_create-use-dist-destroy0.store.lock. File is already being used by this Hazelcast instance.`

```
com.hazelcast.core.HazelcastException: Cannot acquire lock on /home/ec2-user/hz-root/HzClient1HZ/nearCache-mapBak1createUseDestroy_create-use-dist-destroy0.store.lock. File is already being used by this Hazelcast instance.
    at com.hazelcast.internal.nearcache.impl.preloader.NearCachePreloaderLock.acquireLock(NearCachePreloaderLock.java:62)
    at com.hazelcast.internal.nearcache.impl.preloader.NearCachePreloaderLock.<init>(NearCachePreloaderLock.java:44)
    at com.hazelcast.internal.nearcache.impl.preloader.NearCachePreloader.<init>(NearCachePreloader.java:109)
    at com.hazelcast.internal.nearcache.impl.nativememory.SegmentedNativeMemoryNearCacheRecordStore.createPreloader(SegmentedNativeMemoryNearCacheRecordStore.java:108)
    at com.hazelcast.internal.nearcache.impl.nativememory.SegmentedNativeMemoryNearCacheRecordStore.<init>(SegmentedNativeMemoryNearCacheRecordStore.java:75)
    at com.hazelcast.internal.nearcache.HiDensityNearCache.createNearCacheRecordStore(HiDensityNearCache.java:68)
    at com.hazelcast.internal.nearcache.impl.DefaultNearCache.initialize(DefaultNearCache.java:76)
    at com.hazelcast.internal.nearcache.HiDensityNearCache.initialize(HiDensityNearCache.java:51)
    at com.hazelcast.internal.nearcache.impl.DefaultNearCacheManager.getOrCreateNearCache(DefaultNearCacheManager.java:82)
    at com.hazelcast.client.proxy.NearCachedClientMapProxy.onInitialize(NearCachedClientMapProxy.java:104)
    at com.hazelcast.client.spi.ProxyManager.initialize(ProxyManager.java:371)
    at com.hazelcast.client.spi.ProxyManager.initializeWithRetry(ProxyManager.java:326)
    at com.hazelcast.client.spi.ProxyManager.getOrCreateProxy(ProxyManager.java:299)
    at com.hazelcast.client.impl.HazelcastClientInstanceImpl.getDistributedObject(HazelcastClientInstanceImpl.java:669)
    at com.hazelcast.client.impl.HazelcastClientInstanceImpl.getMap(HazelcastClientInstanceImpl.java:484)
    at com.hazelcast.client.impl.HazelcastClientProxy.getMap(HazelcastClientProxy.java:118)
    at hzcmd.map.CreateUse.timeStep(CreateUse.java:11)
```

**Comment by Donnerbart** [comment]
Didn't fail since June. I've also created a similar test, so we check this scenario in every PR builder: https://github.com/hazelcast/hazelcast/pull/11166
