### ISSUE TITLE
3.9-SNAPSHOT client received generic HazelcastException when cause was MemberLeftException

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#10763]
from this shutdown job 
https://hazelcast-l337.ci.cloudbees.com/view/shutdown/job/shutdown-All/18/consoleFull
the first fail was 
```
/disk1/jenkins/workspace/shutdown-All/3.9-SNAPSHOT/2017_06_14-05_30_54/stable/destroy/create-use-destroy Failed
```
with
```HzClient4HZ _create-use-destroy_createUseDestroy_mapBak1HD_queryCache hzcmd.map.cqc.CreateUseDestroy threadId=0 com.hazelcast.core.HazelcastException: com.hazelcast.core.MemberLeftException: Member [10.0.0.165]:5701 - 51cd3b27-8fae-403b-b81a-beb961c505fa has left cluster! ```

so the client / user / me  received a very generic `com.hazelcast.core.HazelcastException`  
and not the `com.hazelcast.core.MemberLeftException`  
i can handle the `MemberLeftException` as i expect it in a shutdown case.  
but i can not do any thing with the generic  `HazelcastException`
  
why don't i get the correct exception ?

**Comment by Danny-Hazelcast** [comment]
```
com.hazelcast.core.HazelcastException: com.hazelcast.core.MemberLeftException: Member [10.0.0.165]:5701 - 51cd3b27-8fae-403b-b81a-beb961c505fa has left cluster!
	at com.hazelcast.util.ExceptionUtil.peel(ExceptionUtil.java:83)
	at com.hazelcast.util.ExceptionUtil.peel(ExceptionUtil.java:56)
	at com.hazelcast.util.ExceptionUtil.peel(ExceptionUtil.java:52)
	at com.hazelcast.util.ExceptionUtil.rethrow(ExceptionUtil.java:105)
	at com.hazelcast.client.impl.protocol.task.map.MapPublisherCreateWithValueMessageTask.getQueryResults(MapPublisherCreateWithValueMessageTask.java:98)
	at com.hazelcast.client.impl.protocol.task.map.MapPublisherCreateWithValueMessageTask.call(MapPublisherCreateWithValueMessageTask.java:68)
	at com.hazelcast.client.impl.protocol.task.AbstractCallableMessageTask.processMessage(AbstractCallableMessageTask.java:35)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:123)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:103)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:94)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:34)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:155)
	at com.hazelcast.client.impl.querycache.subscriber.ClientInvokerWrapper.invoke(ClientInvokerWrapper.java:89)
	at com.hazelcast.client.impl.querycache.subscriber.ClientQueryCacheEndToEndConstructor.createPublishAccumulatorWithIncludeValue(ClientQueryCacheEndToEndConstructor.java:68)
	at com.hazelcast.client.impl.querycache.subscriber.ClientQueryCacheEndToEndConstructor.createPublisherAccumulator(ClientQueryCacheEndToEndConstructor.java:49)
	at com.hazelcast.map.impl.querycache.subscriber.AbstractQueryCacheEndToEndConstructor.createNew(AbstractQueryCacheEndToEndConstructor.java:90)
	at com.hazelcast.map.impl.querycache.subscriber.AbstractQueryCacheEndToEndConstructor.createNew(AbstractQueryCacheEndToEndConstructor.java:40)
	at com.hazelcast.util.ConcurrencyUtil.getOrPutSynchronized(ConcurrencyUtil.java:73)
	at com.hazelcast.map.impl.querycache.subscriber.QueryCacheEndToEndProvider.getOrCreateQueryCache(QueryCacheEndToEndProvider.java:76)
	at com.hazelcast.client.proxy.ClientMapProxy.createQueryCache(ClientMapProxy.java:1448)
	at com.hazelcast.client.proxy.ClientMapProxy.getQueryCacheInternal(ClientMapProxy.java:1439)
	at com.hazelcast.client.proxy.ClientMapProxy.getQueryCache(ClientMapProxy.java:1416)
	at hzcmd.map.cqc.CreateUseDestroy.timeStep(CreateUseDestroy.java:16)
	at remote.bench.marker.MetricsMarker.flatOut(MetricsMarker.java:53)
	at remote.bench.marker.MetricsMarker.bench(MetricsMarker.java:40)
	at remote.bench.BenchThread.call(BenchThread.java:38)
	at remote.bench.BenchThread.call(BenchThread.java:12)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:473)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.hazelcast.core.MemberLeftException: Member [10.0.0.165]:5701 - 51cd3b27-8fae-403b-b81a-beb961c505fa has left cluster!
	at com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor$OnMemberLeftTask.run0(InvocationMonitor.java:345)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor$MonitorTask.run(InvocationMonitor.java:228)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:473)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:748)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:120)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:77)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:155)
	at com.hazelcast.client.impl.protocol.task.map.MapPublisherCreateWithValueMessageTask.getQueryResults(MapPublisherCreateWithValueMessageTask.java:96)
	at com.hazelcast.client.impl.protocol.task.map.MapPublisherCreateWithValueMessageTask.call(MapPublisherCreateWithValueMessageTask.java:68)
	at com.hazelcast.client.impl.protocol.task.AbstractCallableMessageTask.processMessage(AbstractCallableMessageTask.java:35)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:123)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:103)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
```

**Comment by Danny-Hazelcast** [comment]
http://54.163.63.218/~jenkins/workspace/shutdown-All/3.9-SNAPSHOT/2017_06_14-05_30_54/stable/destroy/create-use-destroy/

**Comment by sancar** [comment]
MemberLeftException is a checked exception. Fix here is to make it RuntimeException. And I am not sure how that effects the all other usages of MemberLeftException.

**Comment by sancar** [comment]
It looks like there is no harm to convert it to RuntimeException except from behaviour change. I send a pr to see if it affects anything. I would like get the core teams opinion on this ?
 @tombujok @jerrinot

**Comment by jerrinot** [comment]
certainly we cannot change a superclass of exceptions:
it is:
1. an incompatible change. imagine someone has `catch (ExecutionException e)` <- now it will just fall-through
2. `MemberLeftException` does not have explcitly defined `serialVersionUUID`. I am not sure, but I believe super-classes affect the computed values. implemented interfaces certainly do. 

the #2 is solvable be introducing an explicit `serialVersionUUID` field with the same value as is currently calculated. We did this in the past. However the #1 is a no-go.

**Comment by sancar** [comment]
Then  question is do we want this to change in 4.0 ?

**Comment by ahmetmircik** [comment]
related issue: https://github.com/hazelcast/hazelcast-enterprise/issues/1981

**Comment by ahmetmircik** [comment]
another related issue: https://github.com/hazelcast/hazelcast/issues/12678

**Comment by Danny-Hazelcast** [comment]
I can open a new issue if we find this type of issue in 4.0
