### ISSUE TITLE
ClientHeartbeatTest.testHeartbeatResumedEvent

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#10777]
```
java.lang.AssertionError: CountDownLatch failed to complete within 120 seconds, count left: 1
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:961)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:954)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:946)
	at com.hazelcast.client.heartbeat.ClientHeartbeatTest.testHeartbeatResumedEvent(ClientHeartbeatTest.java:143)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-ZuluJDK6-freestyle/137/testReport/junit/com.hazelcast.client.heartbeat/ClientHeartbeatTest/testHeartbeatResumedEvent/

**Comment by ahmetmircik** [comment]
Zulu is updated as a fix attempt

**Comment by hasancelik** [comment]
```
com.hazelcast.spi.exception.TargetDisconnectedException: Heartbeat timed out to MockedClientConnection{localAddress=[127.0.0.1]:40017, super=ClientConnection{alive=true, connectionId=2, channel=null, remoteEndpoint=[127.0.0.1]:5025, lastReadTime=2017-12-09 06:29:05.221, lastWriteTime=2017-12-09 06:29:05.221, closedTime=never, lastHeartbeatRequested=2017-12-09 06:29:05.221, lastHeartbeatReceived=2017-12-09 06:29:01.760, connected server version=3.10-SNAPSHOT}}
	at com.hazelcast.client.spi.impl.AbstractClientInvocationService$CleanResourcesTask.notifyException(AbstractClientInvocationService.java:225)
	at com.hazelcast.client.spi.impl.AbstractClientInvocationService$CleanResourcesTask.run(AbstractClientInvocationService.java:211)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRunAndReset(FutureTask.java:317)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:150)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$101(ScheduledThreadPoolExecutor.java:98)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.runPeriodic(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:204)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:96)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:33)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:155)
	at com.hazelcast.client.spi.ProxyManager.initialize(ProxyManager.java:373)
	at com.hazelcast.client.spi.ProxyManager.initializeWithRetry(ProxyManager.java:332)
	at com.hazelcast.client.spi.ProxyManager.getOrCreateProxy(ProxyManager.java:305)
	at com.hazelcast.client.impl.HazelcastClientInstanceImpl.getDistributedObject(HazelcastClientInstanceImpl.java:690)
	at com.hazelcast.client.impl.HazelcastClientInstanceImpl.getMap(HazelcastClientInstanceImpl.java:505)
	at com.hazelcast.client.impl.HazelcastClientProxy.getMap(HazelcastClientProxy.java:118)
	at com.hazelcast.client.heartbeat.ClientHeartbeatTest.testHeartbeatResumedEvent(ClientHeartbeatTest.java:113)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-freestyle/1397/testReport/junit/com.hazelcast.client.heartbeat/ClientHeartbeatTest/testHeartbeatResumedEvent/
