### ISSUE TITLE
ClientEvictionTest.testMaxSizeEvictionWorks

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#10778]
```
java.lang.AssertionError: CountDownLatch failed to complete within 120 seconds, count left: 1
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:895)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:888)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:880)
	at com.hazelcast.client.map.querycache.ClientEvictionTest.testMaxSizeEvictionWorks(ClientEvictionTest.java:96)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-ZuluJDK7/com.hazelcast$hazelcast-client/219/testReport/junit/com.hazelcast.client.map.querycache/ClientEvictionTest/testMaxSizeEvictionWorks/

**Comment by ahmetmircik** [comment]
@hasancelik updated Zulu as a fix attempt.
