### ISSUE TITLE
[reliable-topic] [ringbuffer] NullPointerException ReliableTopic / Ringbuffer  init

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#10772]
in this multi-version  job 
https://hazelcast-l337.ci.cloudbees.com/view/multi-version/job/multi-version-stable-All/10/console

```
/disk1/jenkins/workspace/multi-version-stable-All/3.9-SNAPSHOT/2017_06_15-13_19_49/stable/destroy/create-use-dist-destroy Failed
```

 http://54.163.63.218/~jenkins/workspace/multi-version-stable-All/3.9-SNAPSHOT/2017_06_15-13_19_49/stable/destroy/create-use-dist-destroy

cluster versions
```
20:22:14 HzMember2HZ Started on 10.0.0.25 797@ip-10-0-0-25 /home/ec2-user/hz-root/hz-lib/3.8 
20:22:14 HzMember1HZ Started on 10.0.0.140 1101@ip-10-0-0-140 /home/ec2-user/hz-root/hz-lib/3.8 
20:22:14 HzClient1HZ Started on 10.0.0.140 1222@ip-10-0-0-140 /home/ec2-user/hz-root/hz-lib/3.8 
20:22:14 HzClient2HZ Started on 10.0.0.25 918@ip-10-0-0-25 /home/ec2-user/hz-root/hz-lib/3.8 

20:22:14 HzMember4HZ Started on 10.0.0.5 793@ip-10-0-0-5 /home/ec2-user/hz-root/hz-lib/3.8.1 
20:22:14 HzMember3HZ Started on 10.0.0.223 1117@ip-10-0-0-223 /home/ec2-user/hz-root/hz-lib/3.8.1 
20:22:14 HzClient3HZ Started on 10.0.0.223 1244@ip-10-0-0-223 /home/ec2-user/hz-root/hz-lib/3.8.1 
20:22:14 HzClient4HZ Started on 10.0.0.5 918@ip-10-0-0-5 /home/ec2-user/hz-root/hz-lib/3.8.1 

20:22:14 HzMember6HZ Started on 10.0.0.165 1341@ip-10-0-0-165 /home/ec2-user/hz-root/hz-lib/3.8.2 
20:22:14 HzMember5HZ Started on 10.0.0.35 1166@ip-10-0-0-35 /home/ec2-user/hz-root/hz-lib/3.8.2 
20:22:14 HzClient5HZ Started on 10.0.0.35 1293@ip-10-0-0-35 /home/ec2-user/hz-root/hz-lib/3.8.2 
20:22:14 HzClient6HZ Started on 10.0.0.165 1469@ip-10-0-0-165 /home/ec2-user/hz-root/hz-lib/3.8.2 

20:22:14 HzMember7HZ Started on 10.0.0.85 1532@ip-10-0-0-85 /home/ec2-user/hz-root/hz-lib/3.9-SNAPSHOT 
20:22:14 HzMember8HZ Started on 10.0.0.33 965@ip-10-0-0-33 /home/ec2-user/hz-root/hz-lib/3.9-SNAPSHOT 
20:22:14 HzClient8HZ Started on 10.0.0.33 1090@ip-10-0-0-33 /home/ec2-user/hz-root/hz-lib/3.9-SNAPSHOT 
20:22:14 HzClient7HZ Started on 10.0.0.85 1660@ip-10-0-0-85 /home/ec2-user/hz-root/hz-lib/3.9-SNAPSHOT 
```

HzMember4HZ _create-use-dist-destroy_createUseDistDestroy_reliableTopic hzcmd.topic.CreateUse threadId=0 java.lang.NullPointerException 

http://54.163.63.218/~jenkins/workspace/multi-version-stable-All/3.9-SNAPSHOT/2017_06_15-13_19_49/stable/destroy/create-use-dist-destroy/output/HZ/HzMember4HZ/exception.txt

```
java.lang.NullPointerException
	at com.hazelcast.ringbuffer.impl.RingbufferContainer.<init>(RingbufferContainer.java:99)
	at com.hazelcast.ringbuffer.impl.RingbufferService.getContainer(RingbufferService.java:159)
	at com.hazelcast.ringbuffer.impl.operations.AbstractRingBufferOperation.getRingBufferContainer(AbstractRingBufferOperation.java:78)
	at com.hazelcast.ringbuffer.impl.operations.AddOperation.run(AddOperation.java:56)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:194)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:409)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:115)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:100)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:114)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:75)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:155)
	at com.hazelcast.topic.impl.reliable.ReliableTopicProxy.addWithBackoff(ReliableTopicProxy.java:190)
	at com.hazelcast.topic.impl.reliable.ReliableTopicProxy.publish(ReliableTopicProxy.java:163)
	at hzcmd.topic.CreateUse.timeStep(CreateUse.java:21)
	at remote.bench.marker.MetricsMarker.flatOut(MetricsMarker.java:53)
	at remote.bench.marker.MetricsMarker.bench(MetricsMarker.java:40)
	at remote.bench.BenchThread.call(BenchThread.java:38)
	at remote.bench.BenchThread.call(BenchThread.java:12)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:473)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Danny-Hazelcast** [comment]
Failed test in Multi version Job
 https://hazelcast-l337.ci.cloudbees.com/view/multi-version/job/multi-version-stable-All/11/console

/disk1/jenkins/workspace/multi-version-stable-All/3.9-SNAPSHOT/2017_06_19-15_22_11/stable/destroy/create-use-dist-destroy Failed

 http://54.163.63.218/~jenkins/workspace/multi-version-stable-All/3.9-SNAPSHOT/2017_06_19-15_22_11/stable/destroy/create-use-dist-destroy


```
HzClient1HZ _create-use-dist-destroy_createUseDistDestroy_reliableTopic hzcmd.topic.CreateUse threadId=0 com.hazelcast.core.HazelcastException: Failed to publish message: [B@40d481f9 to topic:topicReliableCreateUseDestroy_create-use-dist-destroy0 
```


```
com.hazelcast.core.HazelcastException: Failed to publish message: [B@40d481f9 to topic:topicReliableCreateUseDestroy_create-use-dist-destroy0
	at com.hazelcast.client.proxy.ClientReliableTopicProxy.publish(ClientReliableTopicProxy.java:120)
	at hzcmd.topic.CreateUse.timeStep(CreateUse.java:21)
	at remote.bench.marker.MetricsMarker.flatOut(MetricsMarker.java:53)
	at remote.bench.marker.MetricsMarker.bench(MetricsMarker.java:40)
	at remote.bench.BenchThread.call(BenchThread.java:38)
	at remote.bench.BenchThread.call(BenchThread.java:12)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:473)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:87)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:31)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:183)
	at com.hazelcast.client.util.ClientDelegatingFuture.get(ClientDelegatingFuture.java:127)
	at com.hazelcast.client.util.ClientDelegatingFuture.get(ClientDelegatingFuture.java:113)
	at com.hazelcast.client.proxy.ClientReliableTopicProxy.addWithBackoff(ClientReliableTopicProxy.java:138)
	at com.hazelcast.client.proxy.ClientReliableTopicProxy.publish(ClientReliableTopicProxy.java:112)
	... 11 more
Caused by: java.lang.NullPointerException
	at com.hazelcast.ringbuffer.impl.RingbufferContainer.<init>(RingbufferContainer.java:101)
	at com.hazelcast.ringbuffer.impl.RingbufferService.getContainer(RingbufferService.java:159)
	at com.hazelcast.ringbuffer.impl.operations.AbstractRingBufferOperation.getRingBufferContainer(AbstractRingBufferOperation.java:78)
	at com.hazelcast.ringbuffer.impl.operations.AddOperation.run(AddOperation.java:56)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:194)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:405)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:432)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:534)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:519)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:490)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:200)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:59)
	at com.hazelcast.client.impl.protocol.task.AbstractPartitionMessageTask.processMessage(AbstractPartitionMessageTask.java:64)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:123)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:103)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:154)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:125)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:100)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:120)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run(AbstractInvocationFuture.java:243)
	at com.hazelcast.client.impl.protocol.task.AbstractPartitionMessageTask.execute(AbstractPartitionMessageTask.java:78)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.unblock(AbstractInvocationFuture.java:239)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.andThen(AbstractInvocationFuture.java:215)
	at com.hazelcast.client.impl.protocol.task.AbstractPartitionMessageTask.processMessage(AbstractPartitionMessageTask.java:69)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:123)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:103)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:154)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:125)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:100)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:74)
	... 17 more
```


from http://54.163.63.218/~jenkins/workspace/multi-version-stable-All/3.9-SNAPSHOT/2017_06_19-15_22_11/stable/destroy/create-use-dist-destroy/output/HZ/HzClient1HZ/out.txt
```
SEVERE: hz.client_0 [HZ] [3.8] hz.client_0.event-2 caught an exception while processing task:com.hazelcast.client.spi.impl.listener.ClientListenerServiceImpl$ClientEventProcessor@3fc3ceb3
java.lang.NullPointerException
	at com.hazelcast.client.cache.impl.AbstractClientInternalCacheProxy$RepairableNearCacheEventHandler.handle(AbstractClientInternalCacheProxy.java:1019)
	at com.hazelcast.client.impl.protocol.codec.CacheAddNearCacheInvalidationListenerCodec$AbstractEventHandler.handle(CacheAddNearCacheInvalidationListenerCodec.java:256)
	at com.hazelcast.client.cache.impl.AbstractClientInternalCacheProxy$ConnectedServerVersionAwareNearCacheEventHandler.handle(AbstractClientInternalCacheProxy.java:989)
	at com.hazelcast.client.cache.impl.AbstractClientInternalCacheProxy$ConnectedServerVersionAwareNearCacheEventHandler.handle(AbstractClientInternalCacheProxy.java:963)
	at com.hazelcast.client.spi.impl.listener.ClientListenerServiceImpl$ClientEventProcessor.run(ClientListenerServiceImpl.java:136)
	at com.hazelcast.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:221)
	at com.hazelcast.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:204)

Jun 19, 2017 7:09:22 PM com.hazelcast.client.spi.ClientListenerService
SEVERE: hz.client_0 [HZ] [3.8] hz.client_0.event-2 caught an exception while processing task:com.hazelcast.client.spi.impl.listener.ClientListenerServiceImpl$ClientEventProcessor@1865b707
java.lang.NullPointerException
	at com.hazelcast.client.cache.impl.AbstractClientInternalCacheProxy$RepairableNearCacheEventHandler.handle(AbstractClientInternalCacheProxy.java:1019)
	at com.hazelcast.client.impl.protocol.codec.CacheAddNearCacheInvalidationListenerCodec$AbstractEventHandler.handle(CacheAddNearCacheInvalidationListenerCodec.java:256)
	at com.hazelcast.client.cache.impl.AbstractClientInternalCacheProxy$ConnectedServerVersionAwareNearCacheEventHandler.handle(AbstractClientInternalCacheProxy.java:989)
	at com.hazelcast.client.cache.impl.AbstractClientInternalCacheProxy$ConnectedServerVersionAwareNearCacheEventHandler.handle(AbstractClientInternalCacheProxy.java:963)
	at com.hazelcast.client.spi.impl.listener.ClientListenerServiceImpl$ClientEventProcessor.run(ClientListenerServiceImpl.java:136)
	at com.hazelcast.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:221)
	at com.hazelcast.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:204)

com.hazelcast.core.HazelcastException: Failed to publish message: [B@40d481f9 to topic:topicReliableCreateUseDestroy_create-use-dist-destroy0
	at com.hazelcast.client.proxy.ClientReliableTopicProxy.publish(ClientReliableTopicProxy.java:120)
	at hzcmd.topic.CreateUse.timeStep(CreateUse.java:21)
	at remote.bench.marker.MetricsMarker.flatOut(MetricsMarker.java:53)
	at remote.bench.marker.MetricsMarker.bench(MetricsMarker.java:40)
	at remote.bench.BenchThread.call(BenchThread.java:38)
	at remote.bench.BenchThread.call(BenchThread.java:12)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:473)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:87)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:31)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:183)
	at com.hazelcast.client.util.ClientDelegatingFuture.get(ClientDelegatingFuture.java:127)
	at com.hazelcast.client.util.ClientDelegatingFuture.get(ClientDelegatingFuture.java:113)
	at com.hazelcast.client.proxy.ClientReliableTopicProxy.addWithBackoff(ClientReliableTopicProxy.java:138)
	at com.hazelcast.client.proxy.ClientReliableTopicProxy.publish(ClientReliableTopicProxy.java:112)
	... 11 more
Caused by: java.lang.NullPointerException
	at com.hazelcast.ringbuffer.impl.RingbufferContainer.<init>(RingbufferContainer.java:101)
	at com.hazelcast.ringbuffer.impl.RingbufferService.getContainer(RingbufferService.java:159)
	at com.hazelcast.ringbuffer.impl.operations.AbstractRingBufferOperation.getRingBufferContainer(AbstractRingBufferOperation.java:78)
	at com.hazelcast.ringbuffer.impl.operations.AddOperation.run(AddOperation.java:56)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:194)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:405)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:432)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:534)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:519)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:490)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:200)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:59)
	at com.hazelcast.client.impl.protocol.task.AbstractPartitionMessageTask.processMessage(AbstractPartitionMessageTask.java:64)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:123)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:103)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:154)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:125)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:100)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:120)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run(AbstractInvocationFuture.java:243)
	at com.hazelcast.client.impl.protocol.task.AbstractPartitionMessageTask.execute(AbstractPartitionMessageTask.java:78)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.unblock(AbstractInvocationFuture.java:239)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.andThen(AbstractInvocationFuture.java:215)
	at com.hazelcast.client.impl.protocol.task.AbstractPartitionMessageTask.processMessage(AbstractPartitionMessageTask.java:69)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:123)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:103)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:154)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:125)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:100)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:74)
	... 17 more
Jun 19, 2017 7:09:22 PM com.hazelcast.client.spi.ClientListenerService
SEVERE: hz.client_0 [HZ] [3.8] hz.client_0.event-2 caught an exception while processing task:com.hazelcast.client.spi.impl.listener.ClientListenerServiceImpl$ClientEventProcessor@2cdfaddd
java.lang.NullPointerException
	at com.hazelcast.client.cache.impl.AbstractClientInternalCacheProxy$RepairableNearCacheEventHandler.handle(AbstractClientInternalCacheProxy.java:1019)
	at com.hazelcast.client.impl.protocol.codec.CacheAddNearCacheInvalidationListenerCodec$AbstractEventHandler.handle(CacheAddNearCacheInvalidationListenerCodec.java:256)
	at com.hazelcast.client.cache.impl.AbstractClientInternalCacheProxy$ConnectedServerVersionAwareNearCacheEventHandler.handle(AbstractClientInternalCacheProxy.java:989)
	at com.hazelcast.client.cache.impl.AbstractClientInternalCacheProxy$ConnectedServerVersionAwareNearCacheEventHandler.handle(AbstractClientInternalCacheProxy.java:963)
	at com.hazelcast.client.spi.impl.listener.ClientListenerServiceImpl$ClientEventProcessor.run(ClientListenerServiceImpl.java:136)
	at com.hazelcast.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:221)
	at com.hazelcast.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:204)

```

**Comment by Danny-Hazelcast** [comment]
https://hazelcast-l337.ci.cloudbees.com/view/stable/job/stable-x/66/console

/disk1/jenkins/workspace/stable-x/3.9-SNAPSHOT/2017_06_26-16_29_16/create-use-destroy Failed
http://54.163.63.218/~jenkins/workspace/stable-x/3.9-SNAPSHOT/2017_06_26-16_29_16/create-use-destroy

HzClient1HZ _create-use-destroy_createUseDestroy_reliableTopic hzcmd.topic.CreateUseDestroy threadId=0 java.lang.NullPointerException 

output/HZ/HzClient1HZ/exception.txt


http://54.163.63.218/~jenkins/workspace/stable-x/3.9-SNAPSHOT/2017_06_26-16_29_16/create-use-destroy/output/HZ/HzClient1HZ/exception.txt

```
java.lang.NullPointerException
	at com.hazelcast.ringbuffer.impl.RingbufferContainer.<init>(RingbufferContainer.java:101)
	at com.hazelcast.ringbuffer.impl.RingbufferService.getContainer(RingbufferService.java:159)
	at com.hazelcast.ringbuffer.impl.operations.AbstractRingBufferOperation.getRingBufferContainer(AbstractRingBufferOperation.java:78)
	at com.hazelcast.ringbuffer.impl.operations.AddOperation.run(AddOperation.java:56)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:194)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:405)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:432)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:534)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:519)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:490)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:200)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:59)
	at com.hazelcast.client.impl.protocol.task.AbstractPartitionMessageTask.processMessage(AbstractPartitionMessageTask.java:64)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:123)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:103)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:154)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:125)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:100)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:120)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run(AbstractInvocationFuture.java:243)
	at com.hazelcast.client.impl.protocol.task.AbstractPartitionMessageTask.execute(AbstractPartitionMessageTask.java:78)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.unblock(AbstractInvocationFuture.java:239)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.andThen(AbstractInvocationFuture.java:215)
	at com.hazelcast.client.impl.protocol.task.AbstractPartitionMessageTask.processMessage(AbstractPartitionMessageTask.java:69)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:123)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:103)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:154)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:125)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:100)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:96)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:33)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:183)
	at com.hazelcast.client.util.ClientDelegatingFuture.get(ClientDelegatingFuture.java:137)
	at com.hazelcast.client.util.ClientDelegatingFuture.get(ClientDelegatingFuture.java:128)
	at com.hazelcast.client.proxy.ClientReliableTopicProxy.addWithBackoff(ClientReliableTopicProxy.java:139)
	at com.hazelcast.client.proxy.ClientReliableTopicProxy.publish(ClientReliableTopicProxy.java:114)
	at hzcmd.topic.CreateUseDestroy.timeStep(CreateUseDestroy.java:21)
	at remote.bench.marker.MetricsMarker.flatOut(MetricsMarker.java:53)
	at remote.bench.marker.MetricsMarker.bench(MetricsMarker.java:40)
	at remote.bench.BenchThread.call(BenchThread.java:38)
	at remote.bench.BenchThread.call(BenchThread.java:12)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:473)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:748)
```
