### ISSUE TITLE
[transaction] 3.9-SNAPSHOT com.hazelcast.core.HazelcastException: java.io.IOException  Packet not send to

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#10773]
This cluster member shutdown job Fails every time with

```
com.hazelcast.core.HazelcastException: java.io.IOException  Packet not send to
```

https://hazelcast-l337.ci.cloudbees.com/view/shutdown/job/shutdown-map-txn-1phase/75/console

/disk1/jenkins/workspace/shutdown-map-txn-1phase/3.9-SNAPSHOT/2017_06_16-06_09_36

http://54.163.63.218//~jenkins/workspace/shutdown-map-txn-1phase/3.9-SNAPSHOT/2017_06_16-06_09_36

we have this odd generic exception HazelcastException wrapping a IOException "Packet not send"
exception.  the test is a cluster member controled shutdown test, where we would expect to hit

any of 
```
com.hazelcast.spi.exception.TargetDisconnectedException:com.hazelcast.spi.exception.TargetNotMemberException:com.hazelcast.core.HazelcastInstanceNotActiveException:java.lang.IllegalStateException
```

```
HzClient3HZ txn1 hzcmd.txn.map.validate.GetForUpdateSet threadId=7 com.hazelcast.core.HazelcastException: java.io.IOException: Packet not send to [10.0.0.42]:5701
```

```
com.hazelcast.core.HazelcastException: java.io.IOException: Packet not send to [10.0.0.42]:5701
	at com.hazelcast.util.ExceptionUtil.peel(ExceptionUtil.java:94)
	at com.hazelcast.util.ExceptionUtil.peel(ExceptionUtil.java:56)
	at com.hazelcast.util.ExceptionUtil.peel(ExceptionUtil.java:81)
	at com.hazelcast.util.ExceptionUtil.peel(ExceptionUtil.java:56)
	at com.hazelcast.util.ExceptionUtil.peel(ExceptionUtil.java:52)
	at com.hazelcast.util.ExceptionUtil.rethrow(ExceptionUtil.java:105)
	at com.hazelcast.client.proxy.txn.ClientTxnProxy.invoke(ClientTxnProxy.java:71)
	at com.hazelcast.client.proxy.txn.ClientTxnMapProxy.getForUpdate(ClientTxnMapProxy.java:90)
	at hzcmd.txn.map.validate.GetForUpdateSet.timeStep(GetForUpdateSet.java:52)
	at remote.bench.marker.MetricsMarker.flatOut(MetricsMarker.java:53)
	at remote.bench.marker.MetricsMarker.bench(MetricsMarker.java:40)
	at remote.bench.BenchThread.call(BenchThread.java:38)
	at remote.bench.BenchThread.call(BenchThread.java:12)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:473)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Packet not send to [10.0.0.42]:5701
	at com.hazelcast.client.spi.impl.ClientInvocationServiceImpl.send(ClientInvocationServiceImpl.java:113)
	at com.hazelcast.client.spi.impl.ClientSmartInvocationServiceImpl.invokeOnConnection(ClientSmartInvocationServiceImpl.java:79)
	at com.hazelcast.client.spi.impl.ClientInvocation.invokeOnSelection(ClientInvocation.java:141)
	at com.hazelcast.client.spi.impl.ClientInvocation.retry(ClientInvocation.java:171)
	at com.hazelcast.client.spi.impl.ClientInvocation.run(ClientInvocation.java:159)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:473)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
	at com.hazelcast.util.executor.LoggingScheduledExecutor$LoggingDelegatingFuture.run(LoggingScheduledExecutor.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:94)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:34)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:155)
	at com.hazelcast.client.proxy.txn.ClientTxnProxy.invoke(ClientTxnProxy.java:69)
	... 12 more
```

**Comment by sancar** [comment]
We converted the IOExceptions to OperationTimeoutException in any place else. We are getting IOExceptions from Transactions because Transactions are bound to a connection. As soon as they get an IOException from connection they fail. When I just think about reason the name of exception `TargetDisconnectedException`  seems like correct exception here. But `TargetDisconnectedException` indicates an indeterminate state. In case of issue, we know that invocation never run. 
I will look for a more appropriate exception.

**Comment by sancar** [comment]
Similar issues described also here. 
https://github.com/hazelcast/hazelcast/issues/11439

**Comment by Danny-Hazelcast** [comment]
https://github.com/hazelcast/hazelcast/issues/11439  has more examples of the generic exception wrapping, and not just in the case of txn's

**Comment by sancar** [comment]
@Danny-Hazelcast I did not realise that. Then I need to investigate each log and fix them separately if not related. I am reopening the issue.
