### ISSUE TITLE
[query] [map] 3.9-SNAPSHOT page-predicate member shutdown OperationTimeoutException

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#10787]
from a 3.9-SNAPSHOT shutdown page predicate test 
https://hazelcast-l337.ci.cloudbees.com/view/shutdown/job/shutdown-x/27/console

/disk1/jenkins/workspace/shutdown-x/3.9-SNAPSHOT/2017_06_20-14_08_33/page-pred Failed
http://54.163.63.218/~jenkins/workspace/shutdown-x/3.9-SNAPSHOT/2017_06_20-14_08_33/page-pred

```
HzClient1HZ _serializable_page-predicate_sql_mapBak1HDSql hzcmd.map.sql.predicate.PagePredCheck threadId=0 com.hazelcast.core.OperationTimeoutException: ClientInvocation{clientMessageType=313, target=random, sendConnection=ClientConnection{alive=false, connectionId=6, channel=NioChannel{0.0.0.0/0.0.0.0:35226->null}, remoteEndpoint=[10.0.0.20]:5701, lastReadTime=2017-06-20 11:18:49.431, lastWriteTime=2017-06-20 11:18:49.239, closedTime=2017-06-20 11:18:49.431, lastHeartbeatRequested=never, lastHeartbeatReceived=never, connected server version=3.9-SNAPSHOT}} timed out by 3938 ms
```

http://54.163.63.218/~jenkins/workspace/shutdown-x/3.9-SNAPSHOT/2017_06_20-14_08_33/page-pred/output/HZ/HzClient1HZ/
```
com.hazelcast.core.OperationTimeoutException: ClientInvocation{clientMessageType=313, target=random, sendConnection=ClientConnection{alive=false, connectionId=6, channel=NioChannel{0.0.0.0/0.0.0.0:35226->null}, remoteEndpoint=[10.0.0.20]:5701, lastReadTime=2017-06-20 11:18:49.431, lastWriteTime=2017-06-20 11:18:49.239, closedTime=2017-06-20 11:18:49.431, lastHeartbeatRequested=never, lastHeartbeatReceived=never, connected server version=3.9-SNAPSHOT}} timed out by 3938 ms
    at com.hazelcast.client.spi.impl.ClientInvocation.notifyException(ClientInvocation.java:208)
    at com.hazelcast.client.spi.impl.ClientInvocationServiceImpl$CleanResourcesTask.notifyException(ClientInvocationServiceImpl.java:232)
    at com.hazelcast.client.spi.impl.ClientInvocationServiceImpl$CleanResourcesTask.run(ClientInvocationServiceImpl.java:212)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:473)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at com.hazelcast.util.executor.LoggingScheduledExecutor$LoggingDelegatingFuture.run(LoggingScheduledExecutor.java:128)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:748)
    at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
    at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
    at ------ submitted from ------.(Unknown Source)
    at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:96)
    at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:33)
    at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:155)
    at com.hazelcast.client.spi.ClientProxy.invoke(ClientProxy.java:206)
    at com.hazelcast.client.proxy.ClientMapProxy.valuesForPagingPredicate(ClientMapProxy.java:1238)
    at com.hazelcast.client.proxy.ClientMapProxy.values(ClientMapProxy.java:1223)```
```

and not any of 
```
com.hazelcast.core.MemberLeftException
com.hazelcast.spi.exception.TargetDisconnectedException
com.hazelcast.spi.exception.TargetNotMemberException
com.hazelcast.core.HazelcastInstanceNotActiveException
java.util.concurrent.ExecutionException
java.lang.IllegalStateException
```

I note that no other SQL, aggregator, predicate test under member shutdown conditions throw's a
com.hazelcast.core.OperationTimeoutException

**Comment by pveentjer** [comment]
OperationTimeoutException is a valid exception allowed to be thrown by almost any IMap method. In case of the client it can happen that  a retryable exception is received, and the client decides not to retry the invocation because too much time has been spend on the preceeding invocations.

Can you add 'OperationTimeoutException' to the list of allowed exceptions.

**Comment by sancar** [comment]
OperationTimeoutException is directly related to `hazelcast.client.invocation.timeout.seconds`. If invocation takes more time than that any invocation can take `OperationTimeoutException` as Peter said.
