### ISSUE TITLE
ConfiguredBehaviourTest

### ISSUE THREAD

**Issue by Donnerbart** [hazelcast/hazelcast#10810]
**com.hazelcast.client.connectionstrategy.ConfiguredBehaviourTest.testReconnectModeONSingleMember**
```java
com.hazelcast.client.HazelcastClientNotActiveException: Partition does not have an owner. partitionId: 31
	at com.hazelcast.client.spi.impl.ClientInvocation.notifyException(ClientInvocation.java:186)
	at com.hazelcast.client.spi.impl.ClientInvocation.invokeOnSelection(ClientInvocation.java:153)
	at com.hazelcast.client.spi.impl.ClientInvocation.retry(ClientInvocation.java:171)
	at com.hazelcast.client.spi.impl.ClientInvocation.run(ClientInvocation.java:159)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:98)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:206)
	at com.hazelcast.util.executor.LoggingScheduledExecutor$LoggingDelegatingFuture.run(LoggingScheduledExecutor.java:128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:96)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:33)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:155)
	at com.hazelcast.client.spi.ClientProxy.invokeOnPartition(ClientProxy.java:188)
	at com.hazelcast.client.spi.ClientProxy.invoke(ClientProxy.java:182)
	at com.hazelcast.client.proxy.ClientMapProxy.putInternal(ClientMapProxy.java:516)
	at com.hazelcast.client.proxy.ClientMapProxy.put(ClientMapProxy.java:508)
	at com.hazelcast.client.proxy.ClientMapProxy.put(ClientMapProxy.java:311)
	at com.hazelcast.client.connectionstrategy.ConfiguredBehaviourTest.testReconnectModeONSingleMember(ConfiguredBehaviourTest.java:157)
Caused by: java.io.IOException: Partition does not have an owner. partitionId: 31
	at com.hazelcast.client.spi.impl.ClientSmartInvocationServiceImpl.invokeOnPartitionOwner(ClientSmartInvocationServiceImpl.java:42)
	at com.hazelcast.client.spi.impl.ClientInvocation.invokeOnSelection(ClientInvocation.java:143)
	at com.hazelcast.client.spi.impl.ClientInvocation.retry(ClientInvocation.java:171)
	at com.hazelcast.client.spi.impl.ClientInvocation.run(ClientInvocation.java:159)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:98)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:206)
	at com.hazelcast.util.executor.LoggingScheduledExecutor$LoggingDelegatingFuture.run(LoggingScheduledExecutor.java:128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/9592/testReport/junit/com.hazelcast.client.connectionstrategy/ConfiguredBehaviourTest/testReconnectModeONSingleMember/

**Comment by sancar** [comment]
fixed by https://github.com/hazelcast/hazelcast/commit/67c03615783d268752fe0bf01d9710f86a49a700

**Comment by mdogan** [comment]
```
java.lang.AssertionError: CountDownLatch failed to complete within 120 seconds, count left: 1
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:1009)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:1002)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:994)
	at com.hazelcast.client.connectionstrategy.ConfiguredBehaviourTest.testReconnectModeASYNCSingleMemberStartLate(ConfiguredBehaviourTest.java:200)
```

https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/10669/testReport/junit/com.hazelcast.client.connectionstrategy/ConfiguredBehaviourTest/testReconnectModeASYNCSingleMemberStartLate/

**Comment by jerrinot** [comment]
this is what can I see in the [log](https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/10669/testReport/junit/com.hazelcast.client.connectionstrategy/ConfiguredBehaviourTest/testReconnectModeASYNCSingleMemberStartLate/):
```
15:03:43,856  WARN |testReconnectModeASYNCSingleMemberStartLate| - [ClientConnectionManager] hz.client_1.cluster- - hz.client_1 [dev] [3.9-SNAPSHOT] Unable to get alive cluster connection, try in 2997 ms later, attempt 2 of 2.
[...]
15:03:46,855  WARN |testReconnectModeASYNCSingleMemberStartLate| - [ClientConnectionManager] hz.client_1.cluster- - hz.client_1 [dev] [3.9-SNAPSHOT] Could not connect to cluster, shutting down the client. Unable to connect to any address in the config! The following addresses were tried: [/127.0.0.1:5002, /127.0.0.1:5007]
[...]
15:03:47,245  INFO |testReconnectModeASYNCSingleMemberStartLate| - [LifecycleService] hz.client_1.clientShutdown- - hz.client_1 [dev] [3.9-SNAPSHOT] HazelcastClient 3.9-SNAPSHOT (20170911 - 2cda06b) is SHUTTING_DOWN
[...]
15:03:47,521  INFO |testReconnectModeASYNCSingleMemberStartLate| - [LifecycleService] hz.client_1.clientShutdown- - hz.client_1 [dev] [3.9-SNAPSHOT] HazelcastClient 3.9-SNAPSHOT (20170911 - 2cda06b) is SHUTDOWN
```

**Comment by hasancelik** [comment]
*testReconnectModeOFFTwoMembers*
```
java.lang.AssertionError: Expected exception: com.hazelcast.client.HazelcastClientNotActiveException
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:32)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
```

https://hazelcast-l337.ci.cloudbees.com/view/Sonar/job/Hazelcast-3.x-sonar/com.hazelcast$hazelcast-client/1634/testReport/junit/com.hazelcast.client.connectionstrategy/ConfiguredBehaviourTest/testReconnectModeOFFTwoMembers/

**Comment by mmedenjak** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/10927

**com.hazelcast.client.connectionstrategy.ConfiguredBehaviourTest.testReconnectModeASYNCTwoMembers**

```
java.lang.AssertionError: CountDownLatch failed to complete within 120 seconds, count left: 1
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:1012)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:1005)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:997)
	at com.hazelcast.client.connectionstrategy.ConfiguredBehaviourTest.testReconnectModeASYNCTwoMembers(ConfiguredBehaviourTest.java:248)
```

**Comment by mdogan** [comment]
```
java.lang.Exception: Unexpected exception, expected<com.hazelcast.client.HazelcastClientOfflineException> but was<com.hazelcast.core.HazelcastInstanceNotActiveException>
	at com.hazelcast.client.connectionstrategy.ConfiguredBehaviourTest.testReconnectModeASYNCSingleMemberInitiallyOffline(ConfiguredBehaviourTest.java:178)
```

https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/10983/testReport/com.hazelcast.client.connectionstrategy/ConfiguredBehaviourTest/testReconnectModeASYNCSingleMemberInitiallyOffline/

**Comment by mdogan** [comment]
```
com.hazelcast.client.HazelcastClientOfflineException: Client is offline.
	at com.hazelcast.client.connection.nio.DefaultClientConnectionStrategy.beforeGetConnection(DefaultClientConnectionStrategy.java:57)
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.getConnection(ClientConnectionManagerImpl.java:352)
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.getOrTriggerConnect(ClientConnectionManagerImpl.java:342)
	at com.hazelcast.client.spi.impl.SmartClientInvocationService.getOrTriggerConnect(SmartClientInvocationService.java:70)
	at com.hazelcast.client.spi.impl.SmartClientInvocationService.invokeOnTarget(SmartClientInvocationService.java:65)
	at com.hazelcast.client.spi.impl.ClientInvocation.invokeOnSelection(ClientInvocation.java:152)
	at com.hazelcast.client.spi.impl.ClientInvocation.invoke(ClientInvocation.java:133)
	at com.hazelcast.client.spi.ProxyManager.initialize(ProxyManager.java:372)
	at com.hazelcast.client.spi.ProxyManager.initializeWithRetry(ProxyManager.java:331)
	at com.hazelcast.client.spi.ProxyManager.getOrCreateProxy(ProxyManager.java:304)
	at com.hazelcast.client.impl.HazelcastClientInstanceImpl.getDistributedObject(HazelcastClientInstanceImpl.java:690)
	at com.hazelcast.client.impl.HazelcastClientInstanceImpl.getMap(HazelcastClientInstanceImpl.java:505)
	at com.hazelcast.client.impl.HazelcastClientProxy.getMap(HazelcastClientProxy.java:118)
	at com.hazelcast.client.connectionstrategy.ConfiguredBehaviourTest.testReconnectModeASYNCSingleMemberStartLate(ConfiguredBehaviourTest.java:242)
```

https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/11122/testReport/junit/com.hazelcast.client.connectionstrategy/ConfiguredBehaviourTest/testReconnectModeASYNCSingleMemberStartLate/

**Comment by mmedenjak** [comment]
@sancar can we move this to 3.9.1 if it is not critical or simple to fix?

**Comment by sancar** [comment]
It turns out it is a simple test fix. :)

**Comment by Donnerbart** [comment]
**com.hazelcast.client.connectionstrategy.ConfiguredBehaviourTest.testReconnectModeASYNCSingleMemberStartLate**
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.client.connectionstrategy.ConfiguredBehaviourTest.testReconnectModeASYNCSingleMemberStartLate(ConfiguredBehaviourTest.java:250)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/11572/testReport/junit/com.hazelcast.client.connectionstrategy/ConfiguredBehaviourTest/testReconnectModeASYNCSingleMemberStartLate/
