### ISSUE TITLE
[query] [map] MapUnboundedReturnValues_IntKeyTest Failures

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#10869]
**testMap_LargeLimit_IntKey**
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at com.hazelcast.internal.memory.impl.EndiannessUtil.readInt(EndiannessUtil.java:126)
	at com.hazelcast.nio.Bits.readInt(Bits.java:138)
	at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readInt(ByteArrayObjectDataInput.java:289)
	at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readInt(ByteArrayObjectDataInput.java:282)
	at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readByteArray(ByteArrayObjectDataInput.java:389)
	at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readData(ByteArrayObjectDataInput.java:619)
	at com.hazelcast.map.impl.query.QueryResultRow.readData(QueryResultRow.java:78)
	at com.hazelcast.map.impl.query.QueryResult.readData(QueryResult.java:199)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.readInternal(DataSerializableSerializer.java:158)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:105)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:50)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.readObject(AbstractSerializationService.java:267)
	at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readObject(ByteArrayObjectDataInput.java:601)
	at com.hazelcast.spi.impl.operationservice.impl.responses.NormalResponse.readData(NormalResponse.java:111)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.readInternal(DataSerializableSerializer.java:158)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:105)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:50)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:185)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:106)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:77)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:147)
	at com.hazelcast.map.impl.query.MapQueryEngineImpl.addResultsOfPredicate(MapQueryEngineImpl.java:177)
	at com.hazelcast.map.impl.query.MapQueryEngineImpl.dispatchQueryOnQueryThreads(MapQueryEngineImpl.java:153)
	at com.hazelcast.map.impl.query.MapQueryEngineImpl.doRunQueryOnQueryThreads(MapQueryEngineImpl.java:146)
	at com.hazelcast.map.impl.query.MapQueryEngineImpl.runQueryOnAllPartitions(MapQueryEngineImpl.java:125)
	at com.hazelcast.map.impl.query.MapQueryEngineImpl.execute(MapQueryEngineImpl.java:86)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.executePredicate(MapProxyImpl.java:652)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.keySet(MapProxyImpl.java:608)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.keySet(MapProxyImpl.java:602)
	at com.hazelcast.map.MapUnboundedReturnValuesTestSupport.internalRunWithLowerBoundCheck(MapUnboundedReturnValuesTestSupport.java:235)
	at com.hazelcast.map.MapUnboundedReturnValuesTestSupport.runMapFullTest(MapUnboundedReturnValuesTestSupport.java:83)
	at com.hazelcast.map.MapUnboundedReturnValues_IntKeyTest.testMap_LargeLimit_IntKey(MapUnboundedReturnValues_IntKeyTest.java:41)
```

**testMap_MediumLimit_IntKey**
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at com.hazelcast.internal.memory.impl.EndiannessUtil.readInt(EndiannessUtil.java:126)
	at com.hazelcast.nio.Bits.readInt(Bits.java:138)
	at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readInt(ByteArrayObjectDataInput.java:289)
	at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readInt(ByteArrayObjectDataInput.java:282)
	at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readByteArray(ByteArrayObjectDataInput.java:389)
	at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readData(ByteArrayObjectDataInput.java:619)
	at com.hazelcast.map.impl.query.QueryResultRow.readData(QueryResultRow.java:78)
	at com.hazelcast.map.impl.query.QueryResult.readData(QueryResult.java:199)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.readInternal(DataSerializableSerializer.java:158)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:105)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:50)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.readObject(AbstractSerializationService.java:267)
	at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readObject(ByteArrayObjectDataInput.java:601)
	at com.hazelcast.spi.impl.operationservice.impl.responses.NormalResponse.readData(NormalResponse.java:111)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.readInternal(DataSerializableSerializer.java:158)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:105)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:50)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:185)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:106)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:77)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:147)
	at com.hazelcast.map.impl.query.MapQueryEngineImpl.addResultsOfPredicate(MapQueryEngineImpl.java:177)
	at com.hazelcast.map.impl.query.MapQueryEngineImpl.dispatchQueryOnQueryThreads(MapQueryEngineImpl.java:153)
	at com.hazelcast.map.impl.query.MapQueryEngineImpl.doRunQueryOnQueryThreads(MapQueryEngineImpl.java:146)
	at com.hazelcast.map.impl.query.MapQueryEngineImpl.runQueryOnAllPartitions(MapQueryEngineImpl.java:125)
	at com.hazelcast.map.impl.query.MapQueryEngineImpl.execute(MapQueryEngineImpl.java:86)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.executePredicate(MapProxyImpl.java:652)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.keySet(MapProxyImpl.java:608)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.keySet(MapProxyImpl.java:602)
	at com.hazelcast.map.MapUnboundedReturnValuesTestSupport.internalRunWithLowerBoundCheck(MapUnboundedReturnValuesTestSupport.java:235)
	at com.hazelcast.map.MapUnboundedReturnValuesTestSupport.runMapFullTest(MapUnboundedReturnValuesTestSupport.java:83)
	at com.hazelcast.map.MapUnboundedReturnValues_IntKeyTest.testMap_LargeLimit_IntKey(MapUnboundedReturnValues_IntKeyTest.java:41)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/1397/

**Comment by mdogan** [comment]
See https://github.com/hazelcast/hazelcast/issues/7498#issuecomment-312671410

**Comment by hasancelik** [comment]
*testMap_MediumLimit_IntKey*
```
org.junit.runners.model.TestTimedOutException: test timed out after 600000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:315)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:153)
	at com.hazelcast.map.impl.proxy.MapProxySupport.invokeOperation(MapProxySupport.java:417)
	at com.hazelcast.map.impl.proxy.MapProxySupport.putInternal(MapProxySupport.java:382)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.put(MapProxyImpl.java:135)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.put(MapProxyImpl.java:126)
	at com.hazelcast.map.MapUnboundedReturnValuesTestSupport.mapPut(MapUnboundedReturnValuesTestSupport.java:185)
	at com.hazelcast.map.MapUnboundedReturnValuesTestSupport.internalRunWithLowerBoundCheck(MapUnboundedReturnValuesTestSupport.java:234)
	at com.hazelcast.map.MapUnboundedReturnValuesTestSupport.runMapFullTest(MapUnboundedReturnValuesTestSupport.java:84)
	at com.hazelcast.map.MapUnboundedReturnValues_IntKeyTest.testMap_MediumLimit_IntKey(MapUnboundedReturnValues_IntKeyTest.java:36)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/1473/testReport/junit/com.hazelcast.map/MapUnboundedReturnValues_IntKeyTest/testMap_MediumLimit_IntKey/

*testMap_LargeLimit_IntKey*
```
org.junit.runners.model.TestTimedOutException: test timed out after 600000 milliseconds
	at java.util.HashMap.createEntry(HashMap.java:897)
	at java.util.HashMap.addEntry(HashMap.java:884)
	at java.util.HashMap.put(HashMap.java:505)
	at java.util.HashSet.add(HashSet.java:217)
	at java.util.AbstractCollection.addAll(AbstractCollection.java:342)
	at com.hazelcast.map.impl.query.QueryResultCollection.addAllRows(QueryResultCollection.java:64)
	at com.hazelcast.map.impl.query.QueryResultCollection.<init>(QueryResultCollection.java:51)
	at com.hazelcast.map.impl.query.QueryResultUtils.transformToSet(QueryResultUtils.java:40)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.executePredicate(MapProxyImpl.java:679)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.keySet(MapProxyImpl.java:631)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.keySet(MapProxyImpl.java:624)
	at com.hazelcast.map.MapUnboundedReturnValuesTestSupport.internalRunWithLowerBoundCheck(MapUnboundedReturnValuesTestSupport.java:236)
	at com.hazelcast.map.MapUnboundedReturnValuesTestSupport.runMapFullTest(MapUnboundedReturnValuesTestSupport.java:84)
	at com.hazelcast.map.MapUnboundedReturnValues_IntKeyTest.testMap_LargeLimit_IntKey(MapUnboundedReturnValues_IntKeyTest.java:41)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/1473/testReport/junit/com.hazelcast.map/MapUnboundedReturnValues_IntKeyTest/testMap_LargeLimit_IntKey/

**Comment by mdogan** [comment]
Fixed by https://github.com/hazelcast/hazelcast/commit/20e13a4c9b09c981e491d7703a78df3c7504faf3
