### ISSUE TITLE
[near-cache] Test Failure: ClientHDMapNearCachePreloaderTest.testStoreAndLoad_withIntegerKeys

### ISSUE THREAD

**Issue by jerrinot** [hazelcast/hazelcast#10880]
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Enterprise/job/Hazelcast-EE-3x-maintenance-nightly/com.hazelcast$hazelcast-enterprise-client/641/testReport/junit/com.hazelcast.client.map.impl.nearcache/ClientHDMapNearCachePreloaderTest/testStoreAndLoad_withIntegerKeys_format_OBJECT_invalidationOnChange_true_/

**Comment by jerrinot** [comment]
Error Message
```
Near Cache size didn't reach the desired value (2342 vs. 2339) (NearCacheStatsImpl{ownedEntryCount=2339, ownedEntryMemoryCost=0, creationTime=1499376548538, hits=0, misses=2342, ratio=0.0%, evictions=0, expirations=0, lastPersistenceTime=1499376670552, persistenceCount=60, lastPersistenceDuration=13, lastPersistenceWrittenBytes=37424, lastPersistenceKeyCount=2339, lastPersistenceFailure=''}) expected:<2342> but was:<2339>
```

```
Stacktrace

java.lang.AssertionError: Near Cache size didn't reach the desired value (2342 vs. 2339) (NearCacheStatsImpl{ownedEntryCount=2339, ownedEntryMemoryCost=0, creationTime=1499376548538, hits=0, misses=2342, ratio=0.0%, evictions=0, expirations=0, lastPersistenceTime=1499376670552, persistenceCount=60, lastPersistenceDuration=13, lastPersistenceWrittenBytes=37424, lastPersistenceKeyCount=2339, lastPersistenceFailure=''}) expected:<2342> but was:<2339>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils.assertNearCacheSize(NearCacheTestUtils.java:361)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils$3.run(NearCacheTestUtils.java:381)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:988)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1005)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils.assertNearCacheSizeEventually(NearCacheTestUtils.java:378)
	at com.hazelcast.internal.nearcache.AbstractNearCachePreloaderTest.storeAndLoad(AbstractNearCachePreloaderTest.java:160)
	at com.hazelcast.internal.nearcache.AbstractNearCachePreloaderTest.testStoreAndLoad_withIntegerKeys(AbstractNearCachePreloaderTest.java:131)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask.run(FutureTask.java:
```

**Comment by jerrinot** [comment]
another: https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Enterprise/job/Hazelcast-EE-3x-nightly/com.hazelcast$hazelcast-enterprise-client/841/testReport/junit/com.hazelcast.client.map.impl.nearcache/ClientHDMapNearCachePreloaderTest/testStoreAndLoad_withIntegerKeys_format_NATIVE_invalidationOnChange_true_serializeKeys_true_/

**Comment by jerrinot** [comment]
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Enterprise/job/Hazelcast-EE-3x-nightly/841/com.hazelcast$hazelcast-enterprise-client/testReport/com.hazelcast.client.map.impl.nearcache/ClientHDMapNearCachePreloaderTest/testStoreAndLoad_withStringKeys_format_NATIVE_invalidationOnChange_true_serializeKeys_true_/history/
