### ISSUE TITLE
ClientStateListenerTest Failures

### ISSUE THREAD

**Issue by mmedenjak** [hazelcast/hazelcast#10885]
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.client.util.ClientStateListenerTest.testClientConnectedWithTimeout(ClientStateListenerTest.java:239)
```

https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/9708/testReport/junit/com.hazelcast.client.util/ClientStateListenerTest/testClientConnectedWithTimeout/
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/9709/testReport/com.hazelcast.client.util/ClientStateListenerTest/testClientConnectedWithTimeout/
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/9711/testReport/com.hazelcast.client.util/ClientStateListenerTest/testClientConnectedWithTimeout/

**Comment by Donnerbart** [comment]
**com.hazelcast.client.util.ClientStateListenerTest.testClientReconnecModeOffDisconnected**
```java
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at org.junit.Assert.assertFalse(Assert.java:74)
	at com.hazelcast.client.util.ClientStateListenerTest.testClientReconnecModeOffDisconnected(ClientStateListenerTest.java:227)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/12957/testReport/com.hazelcast.client.util/ClientStateListenerTest/testClientReconnecModeOffDisconnected/

**Comment by hasancelik** [comment]
**testClientReconnecModeOffDisconnected**
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at org.junit.Assert.assertFalse(Assert.java:74)
	at com.hazelcast.client.util.ClientStateListenerTest.testClientReconnecModeOffDisconnected(ClientStateListenerTest.java:227)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.8/com.hazelcast$hazelcast-client/865/testReport/junit/com.hazelcast.client.util/ClientStateListenerTest/testClientReconnecModeOffDisconnected/

**Comment by Holmistr** [comment]
Failed again in the PR builder https://hazelcast-l337.ci.cloudbees.com/view/Lab/job/new-lab-fast-pr/14275/

Stacktrace:
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.client.util.ClientStateListenerTest.testClientReconnectModeAsyncConnected(ClientStateListenerTest.java:129)
```

**Comment by mdogan** [comment]
On maintenance branch (3.9.x):

```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.client.util.ClientStateListenerTest.testClientASYNCStartConnected(ClientStateListenerTest.java:91)
```

https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/14555/testReport/junit/com.hazelcast.client.util/ClientStateListenerTest/testClientASYNCStartConnected/
