### ISSUE TITLE
Hazelcast with tomcat parallel deploy - com.hazelcast.nio.serialization.HazelcastSerializationException: java.lang.ClassNotFoundException: org.springframework.security.web.csrf.DefaultCsrfToken

### ISSUE THREAD

**Issue by wellprado** [hazelcast/hazelcast#10925]
Hi guys,
 
Im trying to do parallel deploy in my environment and all the times when I put the second deploy (eg: ROOT##002.war ) everything sounds good but I'm not able to load the website anymore when I try to login.

In the catalina.out log I have this situation when this problem appears:

```
2017-07-14 00:19:47.471  INFO 32730 --- [cached.thread-1] c.h.nio.tcp.TcpIpConnectionManager       : [10.56.46.5]:5710 [hazelepp] [3.8] Established socket connection between /10.XX.XX.5:33753 and /10.56.46.33:5710
2017-07-14 00:19:47.471  INFO 32730 --- [cached.thread-2] c.h.nio.tcp.TcpIpConnectionManager       : [10.56.46.5]:5710 [hazelepp] [3.8] Established socket connection between /10.XX.XX.5:26437 and /10.56.46.6:5710
2017-07-14 00:19:47.722  INFO 32730 --- [elepp.migration] c.h.i.partition.impl.MigrationManager    : [10.56.46.5]:5711 [hazelepp] [3.8] Re-partitioning cluster data... Migration queue size: 542
2017-07-14 00:19:48.889  INFO 32730 --- [cached.thread-2] c.h.i.p.InternalPartitionService         : [10.56.46.5]:5711 [hazelepp] [3.8] Remaining migration tasks in queue => 103
2017-07-14 00:19:50.140  INFO 32730 --- [elepp.migration] c.h.i.partition.impl.MigrationThread     : [10.56.46.5]:5711 [hazelepp] [3.8] All migration tasks have been completed, queues are empty.
14-Jul-2017 00:20:09.939 INFO [ajp-nio-8009-exec-1529] com.hazelcast.session.HazelcastSessionManager.findSession Sticky Session is currently enabled.Some failover occured so reading session from Hazelcast map:empty_session_replication
14-Jul-2017 00:20:09.946 SEVERE [ajp-nio-8009-exec-1529] org.apache.coyote.ajp.AjpProcessor.service Error processing request
 com.hazelcast.nio.serialization.HazelcastSerializationException: java.lang.ClassNotFoundException: org.springframework.security.web.csrf.DefaultCsrfToken
        at com.hazelcast.internal.serialization.impl.JavaDefaultSerializers$JavaSerializer.read(JavaDefaultSerializers.java:224)
        at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48)
        at com.hazelcast.internal.serialization.impl.AbstractSerializationService.readObject(AbstractSerializationService.java:266)
        at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readObject(ByteArrayObjectDataInput.java:599)
        at com.hazelcast.session.HazelcastSession.deserializeMap(HazelcastSession.java:141)
        at com.hazelcast.session.HazelcastSession.readData(HazelcastSession.java:127)
        at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.readInternal(DataSerializableSerializer.java:155)
        at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:103)
        at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:49)
        at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48)
        at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:184)
        at com.hazelcast.map.impl.proxy.MapProxySupport.toObject(MapProxySupport.java:1075)
        at com.hazelcast.map.impl.proxy.MapProxyImpl.get(MapProxyImpl.java:114)
        at com.hazelcast.session.HazelcastSessionManager.findSession(HazelcastSessionManager.java:213)
        at org.apache.catalina.connector.CoyoteAdapter.postParseRequest(CoyoteAdapter.java:726)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344)
        at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:478)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:798)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1434)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.springframework.security.web.csrf.DefaultCsrfToken
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at com.hazelcast.nio.ClassLoaderUtil.tryLoadClass(ClassLoaderUtil.java:146)
        at com.hazelcast.nio.ClassLoaderUtil.loadClass(ClassLoaderUtil.java:120)
        at com.hazelcast.nio.IOUtil$ClassLoaderAwareObjectInputStream.resolveClass(IOUtil.java:522)
        at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1819)
        at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1713)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1986)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
        at com.hazelcast.internal.serialization.impl.JavaDefaultSerializers$JavaSerializer.read(JavaDefaultSerializers.java:219)
        ... 24 more

14-Jul-2017 00:20:44.268 INFO [ajp-nio-8009-exec-1534] com.hazelcast.session.HazelcastSessionManager.findSession Sticky Session is currently enabled.Some failover occured so reading session from Hazelcast map:empty_session_replication
14-Jul-2017 00:20:44.270 SEVERE [ajp-nio-8009-exec-1534] org.apache.coyote.ajp.AjpProcessor.service Error processing request
 com.hazelcast.nio.serialization.HazelcastSerializationException: java.lang.ClassNotFoundException: org.springframework.security.web.csrf.DefaultCsrfToken
        at com.hazelcast.internal.serialization.impl.JavaDefaultSerializers$JavaSerializer.read(JavaDefaultSerializers.java:224)
        at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48)
        at com.hazelcast.internal.serialization.impl.AbstractSerializationService.readObject(AbstractSerializationService.java:266)
        at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readObject(ByteArrayObjectDataInput.java:599)
        at com.hazelcast.session.HazelcastSession.deserializeMap(HazelcastSession.java:141)
        at com.hazelcast.session.HazelcastSession.readData(HazelcastSession.java:127)
        at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.readInternal(DataSerializableSerializer.java:155)
        at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:103)
        at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:49)
        at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48)
        at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:184)
        at com.hazelcast.map.impl.proxy.MapProxySupport.toObject(MapProxySupport.java:1075)
        at com.hazelcast.map.impl.proxy.MapProxyImpl.get(MapProxyImpl.java:114)
        at com.hazelcast.session.HazelcastSessionManager.findSession(HazelcastSessionManager.java:213)
        at org.apache.catalina.connector.CoyoteAdapter.postParseRequest(CoyoteAdapter.java:726)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344)
        at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:478)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:798)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1434)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.springframework.security.web.csrf.DefaultCsrfToken
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at com.hazelcast.nio.ClassLoaderUtil.tryLoadClass(ClassLoaderUtil.java:146)
        at com.hazelcast.nio.ClassLoaderUtil.loadClass(ClassLoaderUtil.java:120)
        at com.hazelcast.nio.IOUtil$ClassLoaderAwareObjectInputStream.resolveClass(IOUtil.java:522)
        at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1819)
        at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1713)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1986)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
        at com.hazelcast.internal.serialization.impl.JavaDefaultSerializers$JavaSerializer.read(JavaDefaultSerializers.java:219)
        ... 24 more
```

  Some tip about this problem ? Is this a bug ?

My env:
hazelcast-all-3.8.jar
hazelcast-tomcat85-sessionmanager-1.1.1.jar
Tomcat 8.5  64bits  
Linux Redhat 7.3

**Comment by mmedenjak** [comment]
Hi @wellprado, seems like the spring security class `org.springframework.security.web.csrf.DefaultCsrfToken` is put into the session `HazelcastSession` and replicated but isn't available on all of the hazelcast nodes.

**Comment by wellprado** [comment]
Hi @mmedenjak,

  I use the "automatic deploy" in this environment So the same .war file used for deploy is replicated for every node. They have the same configuration and deploy  :(
  I put the spring-security-web-4.1.1.RELEASE.jar in tomcat/lib  installation in every node, but didn't work too.

Thank you

**Comment by mmedenjak** [comment]
Hm, seems then like the class is not found in the classloaders that hazelcast is searching through. Can you try adding the spring security JAR in the WAR file together with the hazelcast JAR?

**Comment by wellprado** [comment]
Hi @mmedenjak , I think I already did and it didn't work, but I'm not sure!!! I will test again and post the result here ASAP!

Thank you

**Comment by mesutcelik** [comment]
Hi @wellprado 
Do you have any update for us?

**Comment by mmedenjak** [comment]
Hi @wellprado , any updates?

**Comment by mmedenjak** [comment]
Closing the issue due to non-activity. @wellprado please open a new issue if the problem persists.
