### ISSUE TITLE
ClientProxy gets NullPointerException from getClient method

### ISSUE THREAD

**Issue by sancar** [hazelcast/hazelcast#10961]
```
Jul 20, 2017 10:53:29 AM com.hazelcast.client.spi.impl.ClusterListenerSupport
WARNING: hz.client_0 [fi-int] [3.7.5] Unable to get alive cluster connection, try in 998 ms later, attempt 24 of 2147483647.
Jul 20, 2017 10:53:29 AM com.hazelcast.client.spi.impl.ClusterListenerSupport
WARNING: hz.client_0 [fi-int] [3.7.5] Unable to get alive cluster connection, try in 998 ms later, attempt 24 of 2147483647.
Jul 20, 2017 10:53:29 AM com.hazelcast.client.spi.impl.ClusterListenerSupport
WARNING: hz.client_0 [fi-int] [3.7.5] Unable to get alive cluster connection, try in 998 ms later, attempt 24 of 2147483647.
Jul 20, 2017 10:53:29 AM com.hazelcast.client.spi.impl.ClusterListenerSupport
WARNING: hz.client_0 [fi-int] [3.7.5] Unable to get alive cluster connection, try in 998 ms later, attempt 24 of 2147483647.
java.lang.NullPointerException
        at com.hazelcast.client.spi.ClientProxy.getClient(ClientProxy.java:65)
        at com.hazelcast.client.spi.ClientProxy.invoke(ClientProxy.java:170)
        at com.hazelcast.client.proxy.ClientMapProxy.clear(ClientMapProxy.java:1430)
        .......
```

Findings after a little bit investigation, 
Context is set to Proxy only when initializing. Null context means it is not initialized properly. 
Bug seems to be caused by following line:
https://github.com/hazelcast/hazelcast/blob/master/hazelcast-client/src/main/java/com/hazelcast/client/spi/ProxyManager.java#L336
 if user gets an exception and wait in the line above, after retryCountLimit is reached, we are returning as if it is initialized successfully. Actually initialization is not successful : context is not set to proxy.

**Comment by sancar** [comment]
Although issue is reported with 3.7.5. Current master & maintenance have the same problem.
