### ISSUE TITLE
[near-cache] MapNearCacheSerializationCountTest.testSerializationCounts

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#10970]
```
key serializeCount on second getAll(): expected 0, but was 1
GET_ALL, newInt(1, 1, 0), newInt(0, 0, 0), newInt(1, 0, 0), newInt(0, 1, 1), BINARY, BINARY, true, false
                      ↑
[com.hazelcast.nio.serialization.HazelcastSerializationException: invoked key serialization (executeEqualsAndHashCode: false)
 at com.hazelcast.internal.nearcache.AbstractNearCacheSerializationCountTest.getStackTrace(AbstractNearCacheSerializationCountTest.java:348)
 at com.hazelcast.internal.nearcache.AbstractNearCacheSerializationCountTest.access$700(AbstractNearCacheSerializationCountTest.java:62)
 at com.hazelcast.internal.nearcache.AbstractNearCacheSerializationCountTest$KeySerializationCountingData.writePortable(AbstractNearCacheSerializationCountTest.java:380)
 at com.hazelcast.internal.serialization.impl.PortableSerializer.writeInternal(PortableSerializer.java:69)
 at com.hazelcast.internal.serialization.impl.PortableSerializer.write(PortableSerializer.java:60)
 at com.hazelcast.internal.serialization.impl.PortableSerializer.write(PortableSerializer.java:34)
 at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.write(StreamSerializerAdapter.java:43)
 at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:152)
 at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toData(AbstractSerializationService.java:122)
 at com.hazelcast.map.impl.proxy.MapProxySupport.toDataWithStrategy(MapProxySupport.java:1153)
 at com.hazelcast.map.impl.proxy.NearCachedMapProxyImpl.toDataKeysWithReservations(NearCachedMapProxyImpl.java:407)
 at com.hazelcast.map.impl.proxy.NearCachedMapProxyImpl.getAllInternal(NearCachedMapProxyImpl.java:389)
 at com.hazelcast.map.impl.proxy.MapProxyImpl.getAll(MapProxyImpl.java:343)
 at com.hazelcast.internal.adapter.IMapDataStructureAdapter.getAll(IMapDataStructureAdapter.java:151)
 at com.hazelcast.internal.nearcache.AbstractNearCacheSerializationCountTest.runTest(AbstractNearCacheSerializationCountTest.java:229)
 at com.hazelcast.internal.nearcache.AbstractNearCacheSerializationCountTest.testSerializationCounts(AbstractNearCacheSerializationCountTest.java:175)
 at sun.reflect.GeneratedMethodAccessor350.invoke(Unknown Source)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:606)
 at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
 at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
 at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
 at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
 at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
 at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
 at java.util.concurrent.FutureTask.run(FutureTask.java:262)
 at java.lang.Thread.run(Thread.java:745)
]
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK1.7/com.hazelcast$hazelcast/924/testReport/junit/com.hazelcast.map.impl.nearcache/MapNearCacheSerializationCountTest/testSerializationCounts_method_GET_ALL_mapFormat_BINARY_nearCacheFormat_BINARY_invalidateOnChange_true_serializeKeys_false_/

**Comment by Donnerbart** [comment]
Should be the same root cause as the other Near Cache failures: The unwanted serialization is on a `getAll()` call, which should be served from the Near Cache. So it's likely that the cached entry was invalidated by the first population. The solution will be the same as in the other unified tests: populate the data structure, then start the Near Cache instance.
