### ISSUE TITLE
[near-cache] ClientNearCacheInvalidationTests

### ISSUE THREAD

**Issue by Donnerbart** [hazelcast/hazelcast#10988]
Since the Near Cache invalidations on JCache entry creation have been merged (https://github.com/hazelcast/hazelcast/pull/10527), some tests in `ClientNearCacheTest` are failing spuriously, but quite often.

They all use the same configuration and start with the same test approach:
* `putToCacheAndUpdateFromOtherNodeThenGetUpdatedFromClientNearCache()`
* `putToCacheAndRemoveFromOtherNodeThenCantGetUpdatedFromClientNearCache()`
* `putToCacheAndClearOrDestroyThenCantGetAnyRecordFromClientNearCache()`

This is an example of the failure:
**com.hazelcast.client.cache.impl.nearcache.ClientNearCacheTest.putToCacheAndRemoveFromOtherNodeThenCantGetUpdatedFromClientNearCache[format:BINARY]**
```java
java.lang.AssertionError: Expected the Near Cache to contain 'Value-0', but was 'null' (NearCacheStatsImpl{ownedEntryCount=0, ownedEntryMemoryCost=0, creationTime=1501033944340, hits=0, misses=601, ratio=0.0%, evictions=0, expirations=0, lastPersistenceTime=0, persistenceCount=0, lastPersistenceDuration=0, lastPersistenceWrittenBytes=0, lastPersistenceKeyCount=0, lastPersistenceFailure=''}) expected:<Value-0> but was:<null>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at com.hazelcast.client.cache.impl.nearcache.ClientNearCacheTestSupport.assertEqualsFormat(ClientNearCacheTestSupport.java:590)
	at com.hazelcast.client.cache.impl.nearcache.ClientNearCacheTestSupport.access$100(ClientNearCacheTestSupport.java:66)
	at com.hazelcast.client.cache.impl.nearcache.ClientNearCacheTestSupport$11.run(ClientNearCacheTestSupport.java:574)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1066)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1083)
	at com.hazelcast.client.cache.impl.nearcache.ClientNearCacheTestSupport.populateNearCacheAndAssertNearCacheValues(ClientNearCacheTestSupport.java:571)
	at com.hazelcast.client.cache.impl.nearcache.ClientNearCacheTestSupport.putToCacheAndRemoveFromOtherNodeThenCantGetUpdatedFromClientNearCache(ClientNearCacheTestSupport.java:324)
	at com.hazelcast.client.cache.impl.nearcache.ClientNearCacheTest.putToCacheAndRemoveFromOtherNodeThenCantGetUpdatedFromClientNearCache(ClientNearCacheTest.java:76)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/9908/testReport/junit/com.hazelcast.client.cache.impl.nearcache/ClientNearCacheTest/putToCacheAndRemoveFromOtherNodeThenCantGetUpdatedFromClientNearCache_format_BINARY_/

I'm going to ignore them, so the PR builders are not blocked by these failures.

**Comment by Donnerbart** [comment]
Successful run:
```java
############### Filling Cache
Remove 0, stack trace: java.lang.Thread.getStackTrace(Thread.java:1559)
    com.hazelcast.internal.nearcache.impl.DefaultNearCache.remove(DefaultNearCache.java:148)
    com.hazelcast.client.cache.impl.NearCachedClientCacheProxy.invalidateNearCache(NearCachedClientCacheProxy.java:501)
    com.hazelcast.client.cache.impl.NearCachedClientCacheProxy.cacheOrInvalidate(NearCachedClientCacheProxy.java:494)
    com.hazelcast.client.cache.impl.NearCachedClientCacheProxy.onPutSyncInternal(NearCachedClientCacheProxy.java:177)
    com.hazelcast.client.cache.impl.AbstractClientInternalCacheProxy.putSyncInternal(AbstractClientInternalCacheProxy.java:413)
    com.hazelcast.client.cache.impl.AbstractClientCacheProxy.put(AbstractClientCacheProxy.java:261)
    com.hazelcast.client.cache.impl.ClientCacheProxy.put(ClientCacheProxy.java:94)
    com.hazelcast.client.cache.impl.ClientCacheProxy.put(ClientCacheProxy.java:191)
    com.hazelcast.client.cache.impl.nearcache.ClientNearCacheTestSupport.putToCacheAndUpdateFromOtherNodeThenGetUpdatedFromClientNearCache(ClientNearCacheTestSupport.java:215)
    com.hazelcast.client.cache.impl.nearcache.ClientNearCacheTest.putToCacheAndUpdateFromOtherNodeThenGetUpdatedFromClientNearCache(ClientNearCacheTest.java:71)
    sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    java.lang.reflect.Method.invoke(Method.java:498)
    org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
    com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
    java.util.concurrent.FutureTask.run(FutureTask.java:266)
    java.lang.Thread.run(Thread.java:748)
############### Populating Near Cache
Remove 0, stack trace: Get 0 -> null
java.lang.Thread.getStackTrace(Thread.java:1559)
    com.hazelcast.internal.nearcache.impl.DefaultNearCache.remove(DefaultNearCache.java:148)
    com.hazelcast.internal.nearcache.impl.invalidation.RepairingHandler.handle(RepairingHandler.java:90)
    com.hazelcast.internal.nearcache.impl.invalidation.RepairingHandler.handle(RepairingHandler.java:120)
    com.hazelcast.client.cache.impl.NearCachedClientCacheProxy$RepairableNearCacheEventHandler.handle(NearCachedClientCacheProxy.java:829)
    com.hazelcast.client.impl.protocol.codec.CacheAddNearCacheInvalidationListenerCodec$AbstractEventHandler.handle(CacheAddNearCacheInvalidationListenerCodec.java:316)
    com.hazelcast.client.cache.impl.NearCachedClientCacheProxy$ConnectedServerVersionAwareNearCacheEventHandler.handle(NearCachedClientCacheProxy.java:792)
    com.hazelcast.client.cache.impl.NearCachedClientCacheProxy$ConnectedServerVersionAwareNearCacheEventHandler.handle(NearCachedClientCacheProxy.java:766)
    com.hazelcast.client.spi.impl.listener.ClientListenerServiceImpl$ClientEventProcessor.run(ClientListenerServiceImpl.java:133)
    com.hazelcast.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:217)
    com.hazelcast.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:200)
getSyncInternal 0 -> Value-0
tryPublishReserved 0 -> Value-0 (was: Value-0)
cache.get() returned: Value-0
Get 0 -> Value-0
############### Updating Near Cache
```
Failing run:
```java
############### Filling Cache
Remove 0, stack trace: java.lang.Thread.getStackTrace(Thread.java:1559)
    com.hazelcast.internal.nearcache.impl.DefaultNearCache.remove(DefaultNearCache.java:148)
    com.hazelcast.client.cache.impl.NearCachedClientCacheProxy.invalidateNearCache(NearCachedClientCacheProxy.java:501)
    com.hazelcast.client.cache.impl.NearCachedClientCacheProxy.cacheOrInvalidate(NearCachedClientCacheProxy.java:494)
    com.hazelcast.client.cache.impl.NearCachedClientCacheProxy.onPutSyncInternal(NearCachedClientCacheProxy.java:177)
    com.hazelcast.client.cache.impl.AbstractClientInternalCacheProxy.putSyncInternal(AbstractClientInternalCacheProxy.java:413)
    com.hazelcast.client.cache.impl.AbstractClientCacheProxy.put(AbstractClientCacheProxy.java:261)
    com.hazelcast.client.cache.impl.ClientCacheProxy.put(ClientCacheProxy.java:94)
    com.hazelcast.client.cache.impl.ClientCacheProxy.put(ClientCacheProxy.java:191)
    com.hazelcast.client.cache.impl.nearcache.ClientNearCacheTestSupport.putToCacheAndUpdateFromOtherNodeThenGetUpdatedFromClientNearCache(ClientNearCacheTestSupport.java:215)
    com.hazelcast.client.cache.impl.nearcache.ClientNearCacheTest.putToCacheAndUpdateFromOtherNodeThenGetUpdatedFromClientNearCache(ClientNearCacheTest.java:71)
    sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
    sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    java.lang.reflect.Method.invoke(Method.java:498)
    org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
    com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
    java.util.concurrent.FutureTask.run(FutureTask.java:266)
    java.lang.Thread.run(Thread.java:748)
Remove 0, stack trace: ############### Populating Near Cache
Get 0 -> null
java.lang.Thread.getStackTrace(Thread.java:1559)
    com.hazelcast.internal.nearcache.impl.DefaultNearCache.remove(DefaultNearCache.java:148)
    com.hazelcast.internal.nearcache.impl.invalidation.RepairingHandler.handle(RepairingHandler.java:90)
    com.hazelcast.internal.nearcache.impl.invalidation.RepairingHandler.handle(RepairingHandler.java:120)
    com.hazelcast.client.cache.impl.NearCachedClientCacheProxy$RepairableNearCacheEventHandler.handle(NearCachedClientCacheProxy.java:829)
    com.hazelcast.client.impl.protocol.codec.CacheAddNearCacheInvalidationListenerCodec$AbstractEventHandler.handle(CacheAddNearCacheInvalidationListenerCodec.java:316)
    com.hazelcast.client.cache.impl.NearCachedClientCacheProxy$ConnectedServerVersionAwareNearCacheEventHandler.handle(NearCachedClientCacheProxy.java:792)
    com.hazelcast.client.cache.impl.NearCachedClientCacheProxy$ConnectedServerVersionAwareNearCacheEventHandler.handle(NearCachedClientCacheProxy.java:766)
getSyncInternal 0 -> Value-0
    com.hazelcast.client.spi.impl.listener.ClientListenerServiceImpl$ClientEventProcessor.run(ClientListenerServiceImpl.java:133)
    com.hazelcast.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:217)
    com.hazelcast.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:200)
tryPublishReserved 0 -> Value-0 (was: Value-0)
cache.get() returned: Value-0
Get 0 -> null
Get 0 -> null
Get 0 -> null
Get 0 -> null
Get 0 -> null
```

**Comment by Donnerbart** [comment]
With more debugging it looks like our waiting for invalidations doesn't work in some edge cases:
```java
############### Setup
Client 1: 23a792c7-b762-4cce-ad8c-dfd6e91a7213
Client 2: f7b9fd22-ca13-4948-a5db-643463d7ff71
Near Cache 1: 460084531
Near Cache 2: 1088299151
############### Filling Cache
invalidate 0 from 23a792c7-b762-4cce-ad8c-dfd6e91a7213
Remove 0 on 460084531, stack trace: java.lang.Thread.getStackTrace(Thread.java:1559)
    com.hazelcast.internal.nearcache.impl.DefaultNearCache.remove(DefaultNearCache.java:149)
    com.hazelcast.client.cache.impl.NearCachedClientCacheProxy.invalidateNearCache(NearCachedClientCacheProxy.java:501)
    com.hazelcast.client.cache.impl.NearCachedClientCacheProxy.cacheOrInvalidate(NearCachedClientCacheProxy.java:494)
    com.hazelcast.client.cache.impl.NearCachedClientCacheProxy.onPutSyncInternal(NearCachedClientCacheProxy.java:177)
    com.hazelcast.client.cache.impl.AbstractClientInternalCacheProxy.putSyncInternal(AbstractClientInternalCacheProxy.java:413)
    com.hazelcast.client.cache.impl.AbstractClientCacheProxy.put(AbstractClientCacheProxy.java:261)
    com.hazelcast.client.cache.impl.ClientCacheProxy.put(ClientCacheProxy.java:94)
    com.hazelcast.client.cache.impl.ClientCacheProxy.put(ClientCacheProxy.java:191)
    com.hazelcast.client.cache.impl.nearcache.ClientNearCacheTestSupport.populateCache(ClientNearCacheTestSupport.java:570)
    com.hazelcast.client.cache.impl.nearcache.ClientNearCacheTestSupport.putToCacheAndUpdateFromOtherNodeThenGetUpdatedFromClientNearCache(ClientNearCacheTestSupport.java:216)
    com.hazelcast.client.cache.impl.nearcache.ClientNearCacheTest.putToCacheAndUpdateFromOtherNodeThenGetUpdatedFromClientNearCache(ClientNearCacheTest.java:71)
    sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    java.lang.reflect.Method.invoke(Method.java:498)
    org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
    com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
    java.util.concurrent.FutureTask.run(FutureTask.java:266)
    java.lang.Thread.run(Thread.java:748)
Waiting for 100 invalidations...
Remove 0 on 1088299151, stack trace: java.lang.Thread.getStackTrace(Thread.java:1559)
    com.hazelcast.internal.nearcache.impl.DefaultNearCache.remove(DefaultNearCache.java:149)
    com.hazelcast.internal.nearcache.impl.invalidation.RepairingHandler.handle(RepairingHandler.java:90)
    com.hazelcast.internal.nearcache.impl.invalidation.RepairingHandler.handle(RepairingHandler.java:120)
    com.hazelcast.client.cache.impl.NearCachedClientCacheProxy$RepairableNearCacheEventHandler.handle(NearCachedClientCacheProxy.java:829)
    com.hazelcast.client.impl.protocol.codec.CacheAddNearCacheInvalidationListenerCodec$AbstractEventHandler.handle(CacheAddNearCacheInvalidationListenerCodec.java:316)
    com.hazelcast.client.cache.impl.NearCachedClientCacheProxy$ConnectedServerVersionAwareNearCacheEventHandler.handle(NearCachedClientCacheProxy.java:792)
    com.hazelcast.client.cache.impl.NearCachedClientCacheProxy$ConnectedServerVersionAwareNearCacheEventHandler.handle(NearCachedClientCacheProxy.java:766)
    com.hazelcast.client.spi.impl.listener.ClientListenerServiceImpl$ClientEventProcessor.run(ClientListenerServiceImpl.java:133)
    com.hazelcast.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:217)
    com.hazelcast.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:200)
Done!
Waiting for 100 invalidations...
Done!
############### Populating Near Cache
Get 0 -> null
getSyncInternal 0 -> Value-0
tryPublishReserved 0 -> Value-0 (was: Value-0)
cache.get() returned: Value-0
Get 0 -> Value-0
############### Updating Near Cache
```
vs.
```java
############### Setup
Client 1: e179cc05-8190-414e-861f-03ad06695033
Client 2: fb1fce24-03f5-4d0b-925c-b8bfbb6d720a
Near Cache 1: 1701289125
Near Cache 2: 705590296
############### Filling Cache
invalidate 0 from e179cc05-8190-414e-861f-03ad06695033
Remove 0 on 1701289125, stack trace: java.lang.Thread.getStackTrace(Thread.java:1559)
    com.hazelcast.internal.nearcache.impl.DefaultNearCache.remove(DefaultNearCache.java:149)
    com.hazelcast.client.cache.impl.NearCachedClientCacheProxy.invalidateNearCache(NearCachedClientCacheProxy.java:501)
    com.hazelcast.client.cache.impl.NearCachedClientCacheProxy.cacheOrInvalidate(NearCachedClientCacheProxy.java:494)
    com.hazelcast.client.cache.impl.NearCachedClientCacheProxy.onPutSyncInternal(NearCachedClientCacheProxy.java:177)
    com.hazelcast.client.cache.impl.AbstractClientInternalCacheProxy.putSyncInternal(AbstractClientInternalCacheProxy.java:413)
    com.hazelcast.client.cache.impl.AbstractClientCacheProxy.put(AbstractClientCacheProxy.java:261)
    com.hazelcast.client.cache.impl.ClientCacheProxy.put(ClientCacheProxy.java:94)
    com.hazelcast.client.cache.impl.ClientCacheProxy.put(ClientCacheProxy.java:191)
    com.hazelcast.client.cache.impl.nearcache.ClientNearCacheTestSupport.populateCache(ClientNearCacheTestSupport.java:570)
    com.hazelcast.client.cache.impl.nearcache.ClientNearCacheTestSupport.putToCacheAndUpdateFromOtherNodeThenGetUpdatedFromClientNearCache(ClientNearCacheTestSupport.java:216)
    com.hazelcast.client.cache.impl.nearcache.ClientNearCacheTest.putToCacheAndUpdateFromOtherNodeThenGetUpdatedFromClientNearCache(ClientNearCacheTest.java:71)
    sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
    sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    java.lang.reflect.Method.invoke(Method.java:498)
    org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
    com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
    java.util.concurrent.FutureTask.run(FutureTask.java:266)
    java.lang.Thread.run(Thread.java:748)
Waiting for 100 invalidations...
Done!
Waiting for 100 invalidations...
Done!
############### Populating Near Cache
Get 0 -> null
Remove 0 on 705590296, stack trace: java.lang.Thread.getStackTrace(Thread.java:1559)
    com.hazelcast.internal.nearcache.impl.DefaultNearCache.remove(DefaultNearCache.java:149)
    com.hazelcast.internal.nearcache.impl.invalidation.RepairingHandler.handle(RepairingHandler.java:90)
    com.hazelcast.internal.nearcache.impl.invalidation.RepairingHandler.handle(RepairingHandler.java:120)
    com.hazelcast.client.cache.impl.NearCachedClientCacheProxy$RepairableNearCacheEventHandler.handle(NearCachedClientCacheProxy.java:829)
    com.hazelcast.client.impl.protocol.codec.CacheAddNearCacheInvalidationListenerCodec$AbstractEventHandler.handle(CacheAddNearCacheInvalidationListenerCodec.java:316)
    com.hazelcast.client.cache.impl.NearCachedClientCacheProxy$ConnectedServerVersionAwareNearCacheEventHandler.handle(NearCachedClientCacheProxy.java:792)
    com.hazelcast.client.cache.impl.NearCachedClientCacheProxy$ConnectedServerVersionAwareNearCacheEventHandler.handle(NearCachedClientCacheProxy.java:766)
    com.hazelcast.client.spi.impl.listener.ClientListenerServiceImpl$ClientEventProcessor.run(ClientListenerServiceImpl.java:133)
    com.hazelcast.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:217)
    com.hazelcast.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:200)
getSyncInternal 0 -> Value-0
tryPublishReserved 0 -> null (was: Value-0)
cache.get() returned: Value-0
Get 0 -> null
Get 0 -> null
Get 0 -> null
Get 0 -> null
Get 0 -> null
```

**Comment by hasancelik** [comment]
*when_shuttingDown_invalidationEventIsNotReceived*
```
java.lang.AssertionError: expected:<0> but was:<1>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.client.cache.impl.nearcache.ClientNearCacheInvalidationTest$3.run(ClientNearCacheInvalidationTest.java:234)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueAllTheTime(HazelcastTestSupport.java:1050)
	at com.hazelcast.client.cache.impl.nearcache.ClientNearCacheInvalidationTest.assertInvalidationEventNeverReceived(ClientNearCacheInvalidationTest.java:230)
	at com.hazelcast.client.cache.impl.nearcache.ClientNearCacheInvalidationTest.when_shuttingDown_invalidationEventIsNotReceived(ClientNearCacheInvalidationTest.java:205)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast-client/1428/testReport/junit/com.hazelcast.client.cache.impl.nearcache/ClientNearCacheInvalidationTest/when_shuttingDown_invalidationEventIsNotReceived_fromMember_true__format_OBJECT_/

**Comment by ahmetmircik** [comment]
@hasancelik refactored those tests, didn't fail since then: https://github.com/hazelcast/hazelcast/commit/b6d98d72b4fc20022663f3d2880652197f08410a

**Comment by Donnerbart** [comment]
Failed locally:
**ClientNearCacheInvalidationTest.when_cacheDestroyed_invalidationEventIsReceived()**
```java
java.lang.AssertionError: invalidationCount = [0] but should be >= [1]

	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.client.cache.impl.nearcache.ClientNearCacheInvalidationTest$3.run(ClientNearCacheInvalidationTest.java:244)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueAllTheTime(HazelcastTestSupport.java:1070)
	at com.hazelcast.client.cache.impl.nearcache.ClientNearCacheInvalidationTest.assertLeastInvalidationCount(ClientNearCacheInvalidationTest.java:249)
	at com.hazelcast.client.cache.impl.nearcache.ClientNearCacheInvalidationTest.when_cacheDestroyed_invalidationEventIsReceived(ClientNearCacheInvalidationTest.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Donnerbart** [comment]
There seem to be similar failures in other tests (from a local test run):
**HotRestartClientNearCacheInvalidationTest.when_cacheCleared_invalidationEventIsReceived() [fromMember:false, format:OBJECT]**
```java
java.lang.AssertionError: 
Expected :1
Actual   :0
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.client.cache.impl.nearcache.ClientNearCacheInvalidationTest$2.run(ClientNearCacheInvalidationTest.java:231)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueAllTheTime(HazelcastTestSupport.java:1070)
	at com.hazelcast.client.cache.impl.nearcache.ClientNearCacheInvalidationTest.assertNoFurtherInvalidationThan(ClientNearCacheInvalidationTest.java:235)
	at com.hazelcast.client.cache.impl.nearcache.ClientNearCacheInvalidationTest.when_cacheCleared_invalidationEventIsReceived(ClientNearCacheInvalidationTest.java:186)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by hasancelik** [comment]
*ClientNearCacheInvalidationTest.when_cacheManagerDestroyCacheInvoked_invalidationEventMayBeReceived*
```
java.lang.AssertionError: invalidationCount = [0] but should be >= [1]
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.client.cache.impl.nearcache.ClientNearCacheInvalidationTest$6.run(ClientNearCacheInvalidationTest.java:414)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueAllTheTime(HazelcastTestSupport.java:1070)
	at com.hazelcast.client.cache.impl.nearcache.ClientNearCacheInvalidationTest.assertLeastInvalidationCount(ClientNearCacheInvalidationTest.java:419)
	at com.hazelcast.client.cache.impl.nearcache.ClientNearCacheInvalidationTest.when_cacheManagerDestroyCacheInvoked_invalidationEventMayBeReceived(ClientNearCacheInvalidationTest.java:361)
```

https://hazelcast-l337.ci.cloudbees.com/view/Sonar/job/Hazelcast-3.x-sonar/com.hazelcast$hazelcast-client/1599/testReport/junit/com.hazelcast.client.cache.impl.nearcache/ClientNearCacheInvalidationTest/when_cacheManagerDestroyCacheInvoked_invalidationEventMayBeReceived_fromMember_true__format_OBJECT_/

**Comment by Donnerbart** [comment]
The tests from `ClientNearCacheTest` have been migrated to the unified tests and the class has been removed. No more issues should be possible from master builds. So the remaining issues are from the invalidation test classes.
