### ISSUE TITLE
MapLoader NPE on loadAll(Collection)

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast#11079]
This code
```
	@Override
	public Map<String, String> loadAll(Collection<String> keys) {
	    Map<String, String> result = new HashMap<>();
	    result.put(null, "notnull");
	    return result;
	}
```
causes this exception on 3.8.3
```
09:19:04.330 [hz._hzInstance_1_dev.partition-operation.thread-1] ERROR com.hazelcast.map.impl.operation.PutFromLoadAllOperation - [127.0.0.1]:5701 [dev] [3.8.3] null
 java.lang.NullPointerException: null
	at com.hazelcast.util.ConcurrentReferenceHashMap.hashOf(ConcurrentReferenceHashMap.java:297) ~[hazelcast-3.8.3.jar!/:3.8.3]
	at com.hazelcast.util.ConcurrentReferenceHashMap.get(ConcurrentReferenceHashMap.java:1258) ~[hazelcast-3.8.3.jar!/:3.8.3]
	at com.hazelcast.map.impl.recordstore.StorageImpl.get(StorageImpl.java:94) ~[hazelcast-3.8.3.jar!/:3.8.3]
	at com.hazelcast.map.impl.recordstore.StorageImpl.get(StorageImpl.java:42) ~[hazelcast-3.8.3.jar!/:3.8.3]
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.getRecord(DefaultRecordStore.java:226) ~[hazelcast-3.8.3.jar!/:3.8.3]
	at com.hazelcast.map.impl.operation.PutFromLoadAllOperation.run(PutFromLoadAllOperation.java:73) ~[hazelcast-3.8.3.jar!/:3.8.3]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:186) [hazelcast-3.8.3.jar!/:3.8.3]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:120) [hazelcast-3.8.3.jar!/:3.8.3]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:100) [hazelcast-3.8.3.jar!/:3.8.3]
```

A bit surprising you can put a null key into a HashMap.

**Comment by neilstevenson** [comment]
https://docs.oracle.com/javase/8/docs/api/java/util/HashMap.html

At the top "_Hash table based implementation of the Map interface. This implementation provides all of the optional map operations, and permits null values and the null key._ "

**Comment by gokhanoner** [comment]
also, another example

this code:

```
    public static final class TestMapLoader extends MapStoreAdapter<String, String> implements PostProcessingMapStore{

        @Override
        public Iterable<String> loadAllKeys() {
            return Arrays.asList("1", "2", "null");
        }

        @Override
        public Map<String, String> loadAll(Collection<String> keys) {
            Map<String, String> val = new HashMap<>();
            val.put("1", "1");
            val.put("2", null);
            val.put("null", "");
            return val;
        }

    }
```

causes this:

```
Aug 12, 2017 5:38:44 AM com.hazelcast.map.impl.recordstore.DefaultRecordStore
WARNING: [192.168.0.27]:5701 [gokhan] [3.8.3] Found an attempt to load a null value from map-store, ignoring it.
Aug 12, 2017 5:38:44 AM com.hazelcast.map.impl.operation.PutFromLoadAllOperation
SEVERE: [192.168.0.27]:5701 [gokhan] [3.8.3] null
java.lang.NullPointerException
	at com.hazelcast.map.impl.operation.PutFromLoadAllOperation.run(PutFromLoadAllOperation.java:75)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:186)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:120)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:100)

Aug 12, 2017 5:38:45 AM com.hazelcast.map.impl.recordstore.DefaultRecordStore
SEVERE: [192.168.0.27]:5701 [gokhan] [3.8.3] Exception while loading map test6
java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at com.hazelcast.util.executor.CompletableFutureTask.run(CompletableFutureTask.java:69)
	at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:228)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:88)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:155)
	at com.hazelcast.map.impl.recordstore.BasicRecordStoreLoader.loadValuesInternal(BasicRecordStoreLoader.java:127)
	at com.hazelcast.map.impl.recordstore.BasicRecordStoreLoader.access$100(BasicRecordStoreLoader.java:55)
	at com.hazelcast.map.impl.recordstore.BasicRecordStoreLoader$GivenKeysLoaderTask.call(BasicRecordStoreLoader.java:107)
	at com.hazelcast.util.executor.CompletableFutureTask.run(CompletableFutureTask.java:67)
	... 6 more
Caused by: java.lang.NullPointerException
	at com.hazelcast.map.impl.operation.PutFromLoadAllOperation.run(PutFromLoadAllOperation.java:75)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:186)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:120)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:100)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:114)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:75)
	... 11 more
```


instead of  implementing `PostProcessingMapStore`, if map has an `Interceptor`, same exception occurs.

**Comment by mdogan** [comment]
@neilstevenson: Can you elaborate more? What this issue mean? 

This is javadoc of `java.util.HashMap` implementation, not `java.util.Map` interface contract. Hazelcast IMap doesn't support `null` keys, similar to `java.util.concurrent.ConcurrentHashMap`.

**Comment by neilstevenson** [comment]
Null keys should be rejected by validation rather than throw an exception

**Comment by pveentjer** [comment]
But the validation will also throw an exception :)

**Comment by gokhanoner** [comment]
@pveentjer not necessarily. See this:
`WARNING: [192.168.0.27]:5701 [gokhan] [3.8.3] Found an attempt to load a null value from map-store, ignoring it.`

There is also a similar warning for keys as well. So we check if keys/values are null. But then continue to process. #11081 also related to this one, but a different case.

**Comment by pveentjer** [comment]
Hi @gokhanoner if validation is added, then the validaiton will also throw an exception in case of a validation error.

**Comment by gokhanoner** [comment]
@pveentjer there is already a check, and this one already fails to pass.
First line call this internally `isKeyAndValueLoadable(key, value)` and it fails if key or value is null. But there is no null check after that. That's the problem. So we have a validation but not checking the result of the validation..

```
            Object previousValue = recordStore.putFromLoad(key, value);

            callAfterPutInterceptors(value);
            Record record = recordStore.getRecord(key);
            if (isPostProcessing(recordStore)) {
                value = record.getValue();
            }
```

**Comment by pveentjer** [comment]
Till so far I don't see a good reason to add extra validation. The key problem is lack of documentation stating that the returned collections/map should not contain null keys.

**Comment by gokhanoner** [comment]
So we're OK throwing exception to user code, event though we already validated that data/key should not be processed any further?

**Comment by pveentjer** [comment]
Adding a null keys in the 'loadAllKeys' already doesn't make sense and this should be added to the documentation. 

The example given by Neal is erroneous since it is inserted a value for a key (null key) that should already not have been passed to this method.

What should be fixed is the argument checking of the DefaultRecordStore.getRecord(Data key). If it can't handle a null key, it should check for it.

**Comment by gokhanoner** [comment]
👍 Thanks @pveentjer . can you also look to #11081 & put some thoughts.

**Comment by tombujok** [comment]
Fixed by improving the NullPointerException message via #11097. The documentation has been also supplemented. MapLoaders are not allowed not return null/key values.
