### ISSUE TITLE
MapLoader NPE on loadAllKeys()

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast#11078]
This code
```
	@Override
	public Iterable<String> loadAllKeys() {
		Collection<String> result = new ArrayList<>();
		result.add(null);
		return result;
	}
```
gives
```
Caused by: java.lang.NullPointerException
	at com.hazelcast.internal.partition.impl.InternalPartitionServiceImpl.getPartitionId(InternalPartitionServiceImpl.java:845) ~[hazelcast-3.8.3.jar!/:3.8.3]
	at com.hazelcast.map.impl.MapKeyLoaderUtil$2.apply(MapKeyLoaderUtil.java:113) ~[hazelcast-3.8.3.jar!/:3.8.3]
	at com.hazelcast.map.impl.MapKeyLoaderUtil$2.apply(MapKeyLoaderUtil.java:110) ~[hazelcast-3.8.3.jar!/:3.8.3]
	at com.hazelcast.util.IterableUtil$2.next(IterableUtil.java:60) ~[hazelcast-3.8.3.jar!/:3.8.3]
	at com.hazelcast.map.impl.MapKeyLoaderUtil.nextBatch(MapKeyLoaderUtil.java:86) ~[hazelcast-3.8.3.jar!/:3.8.3]
	at com.hazelcast.map.impl.MapKeyLoaderUtil$1.next(MapKeyLoaderUtil.java:76) ~[hazelcast-3.8.3.jar!/:3.8.3]
	at com.hazelcast.map.impl.MapKeyLoaderUtil$1.next(MapKeyLoaderUtil.java:65) ~[hazelcast-3.8.3.jar!/:3.8.3]
	at com.hazelcast.map.impl.MapKeyLoader.sendKeysInBatches(MapKeyLoader.java:341) ~[hazelcast-3.8.3.jar!/:3.8.3]
	at com.hazelcast.map.impl.MapKeyLoader.access$200(MapKeyLoader.java:72) ~[hazelcast-3.8.3.jar!/:3.8.3]
	at com.hazelcast.map.impl.MapKeyLoader$1.call(MapKeyLoader.java:191) ~[hazelcast-3.8.3.jar!/:3.8.3]
	at com.hazelcast.map.impl.MapKeyLoader$1.call(MapKeyLoader.java:188) ~[hazelcast-3.8.3.jar!/:3.8.3]
	at com.hazelcast.util.executor.CompletableFutureTask.run(CompletableFutureTask.java:67) ~[hazelcast-3.8.3.jar!/:3.8.3]
	at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:228) ~[hazelcast-3.8.3.jar!/:3.8.3]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_144]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_144]
```

**Comment by neilstevenson** [comment]
Tried this on 3.8.3
See also https://github.com/hazelcast/hazelcast/issues/11079

**Comment by mdogan** [comment]
@neilstevenson: What is the point of loading a `null` key? IMap doesn't support `null` keys. 
Only issue I see is, this is not documented in `MapLoader. loadAllKeys()` javadoc.

**Comment by neilstevenson** [comment]
Agreed, this is stupid to try, but validation should catch it. Currently it lets it through.

**Comment by tombujok** [comment]
@neilstevenson IMap does not allow null keys. The validation will throw an exception anyway. So we are we talking about more intuitive exception message, aren't we?

**Comment by neilstevenson** [comment]
The NPE might be interpreted currently as Hazelcast at fault. 
It's invalid input, which isn't rejected, and results in an exception with a vague message.
If you do `map.put(null,null)` is it rejected, so the validation is inconsistent and perhaps this is the best fix, but even a clearer exception message would suffice

**Comment by tombujok** [comment]
Fixed by improving the NullPointerException message. The documentation has been also supplemented. MapLoaders are not allowed not return null/key values.
