### ISSUE TITLE
MemberToMemberDiscoveryTest

### ISSUE THREAD

**Issue by Donnerbart** [hazelcast/hazelcast#11085]
**com.hazelcast.spi.discovery.multicast.MemberToMemberDiscoveryTest.formClusterWithTwoMembersTest**
```java
java.lang.AssertionError: Cluster size is not correct. Expected: 2 Actual: 1
	at org.junit.Assert.fail(Assert.java:88)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSize(HazelcastTestSupport.java:915)
	at com.hazelcast.test.HazelcastTestSupport$13.run(HazelcastTestSupport.java:937)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1086)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:933)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:927)
	at com.hazelcast.spi.discovery.multicast.MemberToMemberDiscoveryTest.formClusterWithTwoMembersTest(MemberToMemberDiscoveryTest.java:58)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/10127/testReport/junit/com.hazelcast.spi.discovery.multicast/MemberToMemberDiscoveryTest/formClusterWithTwoMembersTest/

**Comment by Donnerbart** [comment]
**com.hazelcast.spi.discovery.multicast.MemberToMemberDiscoveryTest.formClusterWithTwoMembersTest**
```java
java.lang.AssertionError: Cluster size is not correct. Expected: 2 Actual: 1
	at org.junit.Assert.fail(Assert.java:88)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSize(HazelcastTestSupport.java:915)
	at com.hazelcast.test.HazelcastTestSupport$13.run(HazelcastTestSupport.java:937)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1086)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:933)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:927)
	at com.hazelcast.spi.discovery.multicast.MemberToMemberDiscoveryTest.formClusterWithTwoMembersTest(MemberToMemberDiscoveryTest.java:58)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/10501/testReport/junit/com.hazelcast.spi.discovery.multicast/MemberToMemberDiscoveryTest/formClusterWithTwoMembersTest/

**Comment by mesutcelik** [comment]
It appears this [2 seconds](https://github.com/hazelcast/hazelcast/blob/v3.8.5/hazelcast/src/main/java/com/hazelcast/spi/discovery/multicast/impl/MulticastDiscoverySender.java#L33) sleep time is causing problem. 

```
        HazelcastInstance instance = Hazelcast.newHazelcastInstance(config);
        Hazelcast.newHazelcastInstance(config);
        assertClusterSizeEventually(2, instance);
```
If the second member is fast enough to start before the first member sends data packet after [2 seconds](https://github.com/hazelcast/hazelcast/blob/v3.8.5/hazelcast/src/main/java/com/hazelcast/spi/discovery/multicast/impl/MulticastDiscoverySender.java#L33), the test simply fails.

The failure can be reproduced by increasing the sleep time [here](https://github.com/hazelcast/hazelcast/blob/v3.8.5/hazelcast/src/main/java/com/hazelcast/spi/discovery/multicast/impl/MulticastDiscoverySender.java#L70).

**Comment by Donnerbart** [comment]
**com.hazelcast.spi.discovery.multicast.MemberToMemberDiscoveryTest.formClusterWithTwoMembersTest**
```java
java.lang.AssertionError: Cluster size is not correct. Expected: 2 Actual: 1
	at org.junit.Assert.fail(Assert.java:88)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSize(HazelcastTestSupport.java:934)
	at com.hazelcast.test.HazelcastTestSupport$13.run(HazelcastTestSupport.java:956)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1105)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:952)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:946)
	at com.hazelcast.spi.discovery.multicast.MemberToMemberDiscoveryTest.formClusterWithTwoMembersTest(MemberToMemberDiscoveryTest.java:58)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/10778/testReport/junit/com.hazelcast.spi.discovery.multicast/MemberToMemberDiscoveryTest/formClusterWithTwoMembersTest/

Failed again in a PR builder :(

**Comment by mesutcelik** [comment]
This test is still time sensitive. We use `hazelcast.wait.seconds.before.join` which is by default 5 seconds. This is used as a barrier in [DiscoveryJoiner](https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/internal/cluster/impl/DiscoveryJoiner.java#L57) to be able to receive first multicast packet but in our test suite, we set it to [1 second](https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/test/java/com/hazelcast/test/AbstractHazelcastClassRunner.java#L129).
thinking about the best solution cc: @jerrinot
