### ISSUE TITLE
CheckDependenciesIT.testNoMandatoryDependencyDeclared

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#11093]
*sonar*
```
java.lang.AssertionError: Cannot find Hazelcast manifest
	at com.hazelcast.osgi.CheckDependenciesIT.findHazelcastManifestURL(CheckDependenciesIT.java:108)
	at com.hazelcast.osgi.CheckDependenciesIT.getHazelcastManifest(CheckDependenciesIT.java:61)
	at com.hazelcast.osgi.CheckDependenciesIT.testNoMandatoryDependencyDeclared(CheckDependenciesIT.java:48)
```

https://hazelcast-l337.ci.cloudbees.com/view/Sonar/job/Hazelcast-3.x-sonar/com.hazelcast$hazelcast/1592/testReport/junit/com.hazelcast.osgi/CheckDependenciesIT/testNoMandatoryDependencyDeclared/

**Comment by Donnerbart** [comment]
Also failed locally:
```java
java.lang.AssertionError: Cannot find Hazelcast manifest

	at com.hazelcast.osgi.CheckDependenciesIT.findHazelcastManifestURL(CheckDependenciesIT.java:108)
	at com.hazelcast.osgi.CheckDependenciesIT.getHazelcastManifest(CheckDependenciesIT.java:61)
	at com.hazelcast.osgi.CheckDependenciesIT.testNoMandatoryDependencyDeclared(CheckDependenciesIT.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Donnerbart** [comment]
Also failed locally on the client test:
**ClientCheckDependenciesIT.testNoMandatoryDependencyDeclared()**
```java
java.lang.AssertionError: Cannot find Hazelcast manifest

	at com.hazelcast.osgi.CheckDependenciesIT.findHazelcastManifestURL(CheckDependenciesIT.java:108)
	at com.hazelcast.osgi.CheckDependenciesIT.getHazelcastManifest(CheckDependenciesIT.java:61)
	at com.hazelcast.osgi.CheckDependenciesIT.testNoMandatoryDependencyDeclared(CheckDependenciesIT.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by hasancelik** [comment]
com.hazelcast.osgi.CheckDependenciesIT.testNoMandatoryDependencyDeclared
com.hazelcast.it.CheckAllDependenciesIT.testNoMandatoryDependencyDeclared
com.hazelcast.client.osgi.ClientCheckDependenciesIT.testNoMandatoryDependencyDeclared

https://hazelcast-l337.ci.cloudbees.com/view/Sonar/job/Hazelcast-3.x-sonar/1597/#showFailuresLink

**Comment by mesutcelik** [comment]
@hasancelik 
the failure on Sonar build is suspicious because default build runs the test as integration test but `test-coverage` profile runs it through surefire plugin(please check the sonar logs).

Can you try to check params and add `failsafe` plugin to `test-coverage`? That might solve the problem.
