### ISSUE TITLE
NearCacheTest

### ISSUE THREAD

**Issue by Donnerbart** [hazelcast/hazelcast#11101]
**com.hazelcast.map.impl.nearcache.NearCacheTest.testNearCacheTTLRecordsExpired[batchInvalidationEnabled:true]**
**com.hazelcast.map.impl.nearcache.NearCacheTest.testNearCacheTTLRecordsExpired[batchInvalidationEnabled:false]**
```java
java.lang.AssertionError: we expected to have all map entries in the Near Cache or already expired (NearCacheStatsImpl{ownedEntryCount=0, ownedEntryMemoryCost=0, creationTime=1502794588353, hits=0, misses=0, ratio=NaN%, evictions=0, expirations=0, lastPersistenceTime=0, persistenceCount=0, lastPersistenceDuration=0, lastPersistenceWrittenBytes=0, lastPersistenceKeyCount=0, lastPersistenceFailure=''})
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.map.impl.nearcache.NearCacheTestSupport$1.run(NearCacheTestSupport.java:99)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1086)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1103)
	at com.hazelcast.map.impl.nearcache.NearCacheTestSupport.assertNearCacheExpiration(NearCacheTestSupport.java:96)
	at com.hazelcast.map.impl.nearcache.NearCacheTest.testNearCacheTTLRecordsExpired(NearCacheTest.java:887)
```

**com.hazelcast.map.impl.nearcache.NearCacheTest.testNearCacheMaxIdleRecordsExpired[batchInvalidationEnabled:true]**
**com.hazelcast.map.impl.nearcache.NearCacheTest.testNearCacheMaxIdleRecordsExpired[batchInvalidationEnabled:false]**
```java
java.lang.AssertionError: we expected to have all map entries in the Near Cache or already expired (NearCacheStatsImpl{ownedEntryCount=0, ownedEntryMemoryCost=0, creationTime=1502794604150, hits=0, misses=0, ratio=NaN%, evictions=0, expirations=0, lastPersistenceTime=0, persistenceCount=0, lastPersistenceDuration=0, lastPersistenceWrittenBytes=0, lastPersistenceKeyCount=0, lastPersistenceFailure=''})
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.map.impl.nearcache.NearCacheTestSupport$1.run(NearCacheTestSupport.java:99)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1086)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1103)
	at com.hazelcast.map.impl.nearcache.NearCacheTestSupport.assertNearCacheExpiration(NearCacheTestSupport.java:96)
	at com.hazelcast.map.impl.nearcache.NearCacheTest.testNearCacheMaxIdleRecordsExpired(NearCacheTest.java:903)
```

https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/10170/testReport/junit/

Same for the EE variant. I hope to have those tests in the unified test framework very soon.

**Comment by ahmetmircik** [comment]
should be fixed by 731b20cbfafa0abc4ed06894f4b04ceb1bbefec8
