### ISSUE TITLE
[executor] DurableExecutorServiceTest

### ISSUE THREAD

**Issue by Donnerbart** [hazelcast/hazelcast#11105]
**com.hazelcast.durableexecutor.DurableExecutorServiceTest.testLongRunningCallable**
```java
java.util.concurrent.ExecutionException: RetrieveResultOperation invocation failed to complete due to operation-heartbeat-timeout. Current time: 2017-08-15 12:25:40.337. Start time: 2017-08-15 12:25:35.568. Total elapsed time: 4770 ms. Last operation heartbeat: 2017-08-15 12:25:37.265. Last operation heartbeat from member: 2017-08-15 12:25:37.265. Invocation{op=com.hazelcast.durableexecutor.impl.operations.RetrieveResultOperation{serviceName='hz:impl:durableExecutorService', identityHash=830322226, partitionId=119, replicaIndex=0, callId=-3, invocationTime=1502799935568 (2017-08-15 12:25:35.568), waitTimeout=-1, callTimeout=3000, name=test}, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=3000, firstInvocationTimeMs=1502799935568, firstInvocationTime='2017-08-15 12:25:35.568', lastHeartbeatMillis=1502799937265, lastHeartbeatTime='2017-08-15 12:25:37.265', target=[127.0.0.1]:5047, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=MockConnection{localEndpoint=[127.0.0.1]:5046, remoteEndpoint=[127.0.0.1]:5047}}
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.newOperationTimeoutException(InvocationFuture.java:157)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:104)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:77)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:183)
	at com.hazelcast.util.executor.DelegatingFuture.get(DelegatingFuture.java:88)
	at com.hazelcast.durableexecutor.DurableExecutorServiceTest.testLongRunningCallable(DurableExecutorServiceTest.java:532)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/10183/testReport/junit/com.hazelcast.durableexecutor/DurableExecutorServiceTest/testLongRunningCallable/

**Comment by tkountis** [comment]
Unable to locate any obvious reason from the log files. Could be related to the invocation system or to that PR. We didn't do any change in the Durable Executor to justify this either. Keeping it open in case we see it again, but moving to 3.10 to avoid blocking 3.9

**Comment by hasancelik** [comment]
```
java.util.concurrent.ExecutionException: RetrieveResultOperation invocation failed to complete due to operation-heartbeat-timeout. Current time: 2017-12-23 06:48:29.143. Start time: 2017-12-23 06:48:25.183. Total elapsed time: 3960 ms. Last operation heartbeat: 2017-12-23 06:48:25.668. Last operation heartbeat from member: 2017-12-23 06:48:25.668. Invocation{op=com.hazelcast.durableexecutor.impl.operations.RetrieveResultOperation{serviceName='hz:impl:durableExecutorService', identityHash=857798131, partitionId=155, replicaIndex=0, callId=-3, invocationTime=1514004505183 (2017-12-23 06:48:25.183), waitTimeout=-1, callTimeout=3000, name=test}, tryCount=250, tryPauseMillis=500, invokeCount=0, callTimeoutMillis=3000, firstInvocationTimeMs=1514004505183, firstInvocationTime='2017-12-23 06:48:25.183', lastHeartbeatMillis=1514004505668, lastHeartbeatTime='2017-12-23 06:48:25.668', target=[127.0.0.1]:21716, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=MockConnection{localEndpoint=[127.0.0.1]:21715, remoteEndpoint=[127.0.0.1]:21716}}
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.newOperationTimeoutException(InvocationFuture.java:164)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:106)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:79)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:183)
	at com.hazelcast.util.executor.DelegatingFuture.get(DelegatingFuture.java:88)
	at com.hazelcast.durableexecutor.DurableExecutorServiceTest.testLongRunningCallable(DurableExecutorServiceTest.java:532)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-freestyle/420/testReport/junit/com.hazelcast.durableexecutor/DurableExecutorServiceTest/testLongRunningCallable/

**Comment by mdogan** [comment]
Test is using 3 seconds operation timeout, which can timeout when there's a pause more than 3sec. There are no new failure reports for 3 months.

**Comment by Fly-Style** [comment]
Failed again: https://github.com/hazelcast/hazelcast/pull/26064#issuecomment-1829933681

**Comment by olukas** [comment]
Closing the test failure - it doesn't seem to be related to `master` or the latest maintenance stream `5.5.z` and it hasn't fail in the last 3 months. Feel free to reopen test failure if it occurs on `master` or on the latest maintenance stream.
