### ISSUE TITLE
Hazelcast failing - "this is the migration destination but has a different uuid!"

### ISSUE THREAD

**Issue by sshorkey** [hazelcast/hazelcast#11117]
I'm running Hazelcast on a cluster of EC2 instances via the hazelcast-aws plugin and I'm having this strange issue:

```
16-Aug-2017 18:25:16.453 INFO [hz.SESSION-REPLICATION-INSTANCE.migration] com.hazelcast.internal.partition.impl.MigrationManager.null [172.31.29.145]:5701 [dev] [3.8.3] Re-partitioning cluster data... Migration queue size: 858
16-Aug-2017 18:25:16.536 WARNING [hz.SESSION-REPLICATION-INSTANCE.migration] com.hazelcast.internal.partition.impl.MigrationManager.null [172.31.29.145]:5701 [dev] [3.8.3] Failed migration from Member [172.31.43.12]:5701 - fc17c9fe-c174-4ea5-b2aa-724c269676cc for MigrationInfo{uuid=c069b2ad-1718-4f2f-a191-98f3c59c5c7c, partitionId=1, source=[172.31.43.12]:5701, sourceUuid=fc17c9fe-c174-4ea5-b2aa-724c269676cc, sourceCurrentReplicaIndex=0, sourceNewReplicaIndex=5, destination=[172.31.43.12]:5702, destinationUuid=cdc9b4f4-728e-4187-89a5-7ee13327d2df, destinationCurrentReplicaIndex=-1, destinationNewReplicaIndex=0, master=[172.31.29.145]:5701, processing=false, status=ACTIVE}
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: This member Member [172.31.43.12]:5702 - 1fbb34b8-b642-4673-b851-32657951602f this is the migration destination but has a different uuid! Migration: MigrationInfo{uuid=c069b2ad-1718-4f2f-a191-98f3c59c5c7c, partitionId=1, source=[172.31.43.12]:5701, sourceUuid=fc17c9fe-c174-4ea5-b2aa-724c269676cc, sourceCurrentReplicaIndex=0, sourceNewReplicaIndex=5, destination=[172.31.43.12]:5702, destinationUuid=cdc9b4f4-728e-4187-89a5-7ee13327d2df, destinationCurrentReplicaIndex=-1, destinationNewReplicaIndex=0, master=[172.31.29.145]:5701, processing=false, status=ACTIVE}
at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:88)
at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:155)
at com.hazelcast.internal.partition.impl.MigrationManager$MigrateTask.executeMigrateOperation(MigrationManager.java:910)
at com.hazelcast.internal.partition.impl.MigrationManager$MigrateTask.run(MigrationManager.java:825)
at com.hazelcast.internal.partition.impl.MigrationThread.processTask(MigrationThread.java:113)
at com.hazelcast.internal.partition.impl.MigrationThread.doRun(MigrationThread.java:90)
at com.hazelcast.internal.partition.impl.MigrationThread.run(MigrationThread.java:65)
```

**Comment by metanet** [comment]
Hi

Did you encounter a split brain issue in your cluster?

Even if you see this error, it should be resolved eventually by itself. Do you see it repeatedly without resolution?

**Comment by sshorkey** [comment]
I was attempting to run hazelcast in docker swarm, with 3 nodes and 2 instances of hazelcast on each node. I've changed configuration to run only 1 instance of hazelcast on each node and that fixed this problem but created another one.

**Comment by sshorkey** [comment]
Issue has resurfaced. Turns out I have no choice but to run 2 instances on each node, so this issue needs resolving.

**Comment by sshorkey** [comment]
It's an issue that appears immediately when the cluster starts and keeps ongoing forever and ever.. it's not a temporary problem or a one-time problem.

**Comment by metanet** [comment]
Can you share your config and logs?

**Comment by metanet** [comment]
I just checked https://github.com/hazelcast/hazelcast/issues/11118 and I think the problem you encounter has nothing to do with migration system. Closing this one. Please follow up on the other issue
