### ISSUE TITLE
NPE in MembershipFailureTest_withTCP

### ISSUE THREAD

**Issue by Donnerbart** [hazelcast/hazelcast#11119]
The failure is from a local test run, so no Jenkins build log available.

**master_candidate_discovers_member_list_recursively()**
```java
java.lang.NullPointerException
	at java.util.Hashtable.put(Hashtable.java:459)
	at com.hazelcast.config.Config.setProperty(Config.java:206)
	at com.hazelcast.internal.cluster.impl.MembershipFailureTest_withTCP.newHazelcastInstance(MembershipFailureTest_withTCP.java:52)
	at com.hazelcast.internal.cluster.impl.MembershipFailureTest.master_candidate_discovers_member_list_recursively(MembershipFailureTest.java:485)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

That's all output I got on the stdout:
```
BuildInfo right after master_candidate_discovers_member_list_recursively(com.hazelcast.internal.cluster.impl.MembershipFailureTest_withTCP): BuildInfo{version='3.9-SNAPSHOT', build='20170816', buildNumber=20170816, revision=24c3d11, enterprise=false, serializationVersion=1}
```

**Comment by Donnerbart** [comment]
Looks like all other methods failed as well.

Found more stdout logs in another test entry:
https://gist.github.com/Donnerbart/95d1ae1623d7f2d7047e551c7a051f68

**Comment by Donnerbart** [comment]
That issue is not fixed! The test also throws the NPE when running on Jenkins:
**com.hazelcast.internal.cluster.impl.MembershipFailureTest_withTCP.master_candidate_has_stale_member_list**
```java
java.lang.NullPointerException: null
	at java.util.Hashtable.put(Hashtable.java:459)
	at com.hazelcast.config.Config.setProperty(Config.java:206)
	at com.hazelcast.internal.cluster.impl.MembershipFailureTest_withTCP.newHazelcastInstance(MembershipFailureTest_withTCP.java:52)
```
https://hazelcast-l337.ci.cloudbees.com/view/Sonar/job/Hazelcast-3.x-sonar/lastCompletedBuild/com.hazelcast$hazelcast/testReport/com.hazelcast.internal.cluster.impl/MembershipFailureTest_withTCP/master_candidate_has_stale_member_list/

And again most of the test methods failed with it:
https://hazelcast-l337.ci.cloudbees.com/view/Sonar/job/Hazelcast-3.x-sonar/lastCompletedBuild/com.hazelcast$hazelcast/testReport/com.hazelcast.internal.cluster.impl/MembershipFailureTest_withTCP/

**Comment by mdogan** [comment]
@Donnerbart: See revision printed after failure. That build doesn't have the fix. 

>BuildInfo right after master_candidate_has_stale_member_list(com.hazelcast.internal.cluster.impl.MembershipFailureTest_withTCP): BuildInfo{version='3.9-SNAPSHOT', build='20170816', buildNumber=20170816, revision=80b48ea, enterprise=false, serializationVersion=1}

**Comment by Donnerbart** [comment]
Ah, sorry, I misread that the fix was just to get the test running on Jenkins.
