### ISSUE TITLE
[scheduled-executor] ClientScheduledExecutorServiceSlowTest Failures

### ISSUE THREAD

**Issue by Donnerbart** [hazelcast/hazelcast#11126]
**ClientScheduledExecutorServiceSlowTest.scheduleRandomPartitions_getAllScheduled_durable()**
```java
java.lang.NullPointerException
    at com.hazelcast.client.scheduledexecutor.ClientScheduledExecutorServiceSlowTest.getScheduledExecutor(ClientScheduledExecutorServiceSlowTest.java:52)
    at com.hazelcast.scheduledexecutor.ScheduledExecutorServiceSlowTest.scheduleRandomPartitions_getAllScheduled_durable(ScheduledExecutorServiceSlowTest.java:168)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
    at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.lang.Thread.run(Thread.java:748)
```
It's from a local test run, so no Jenkins link is available.

**Comment by hasancelik** [comment]
*maintenance*
**schedule_thenDisposeLeakTest**
```
java.lang.NullPointerException: null
	at com.hazelcast.client.scheduledexecutor.ClientScheduledExecutorServiceSlowTest.getScheduledExecutor(ClientScheduledExecutorServiceSlowTest.java:52)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-nightly/com.hazelcast$hazelcast-client/1345/testReport/junit/com.hazelcast.client.scheduledexecutor/ClientScheduledExecutorServiceSlowTest/schedule_thenDisposeLeakTest/

**scheduleRandomPartitions_getAllScheduled_durable**
```
java.lang.NullPointerException: null
	at com.hazelcast.client.scheduledexecutor.ClientScheduledExecutorServiceSlowTest.getScheduledExecutor(ClientScheduledExecutorServiceSlowTest.java:52)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-nightly/com.hazelcast$hazelcast-client/1345/testReport/junit/com.hazelcast.client.scheduledexecutor/ClientScheduledExecutorServiceSlowTest/scheduleRandomPartitions_getAllScheduled_durable/


https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-nightly/1346/#showFailuresLink

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-nightly/1347/#showFailuresLink

**Comment by hasancelik** [comment]
*schedule_thenDisposeLeakTest*
```
org.junit.runners.model.TestTimedOutException: test timed out after 600000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:315)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:153)
	at com.hazelcast.client.proxy.ClientScheduledExecutorProxy.scheduleOnPartition(ClientScheduledExecutorProxy.java:347)
	at com.hazelcast.client.proxy.ClientScheduledExecutorProxy.schedule(ClientScheduledExecutorProxy.java:103)
	at com.hazelcast.scheduledexecutor.ScheduledExecutorServiceSlowTest.schedule_thenDisposeLeakTest(ScheduledExecutorServiceSlowTest.java:423)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.lang.Thread.run(Thread.java:745)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast-client/1480/testReport/junit/com.hazelcast.client.scheduledexecutor/ClientScheduledExecutorServiceSlowTest/schedule_thenDisposeLeakTest/

**Comment by Donnerbart** [comment]
The NPE fix has been merged. I have no idea where this timeout is coming from though.

**Comment by tkountis** [comment]
Will increase the timeout, its probably unpredictably slower on the build environment. The nature of the test is to keep scheduling stuff, stressing the GC.

**Comment by hasancelik** [comment]
**scheduleRandomPartitions_getAllScheduled_durable**
```
java.lang.AssertionError: expected:<11.0> but was:<10.0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:575)
	at org.junit.Assert.assertEquals(Assert.java:700)
	at com.hazelcast.scheduledexecutor.ScheduledExecutorServiceSlowTest.scheduleRandomPartitions_getAllScheduled_durable(ScheduledExecutorServiceSlowTest.java:172)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

https://hazelcast-l337.ci.cloudbees.com/view/Sonar/job/Hazelcast-3.x-sonar/com.hazelcast$hazelcast-client/1662/testReport/junit/com.hazelcast.client.scheduledexecutor/ClientScheduledExecutorServiceSlowTest/scheduleRandomPartitions_getAllScheduled_durable/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: expected:<11.0> but was:<10.0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:575)
	at org.junit.Assert.assertEquals(Assert.java:700)
	at com.hazelcast.scheduledexecutor.ScheduledExecutorServiceSlowTest.scheduleRandomPartitions_getAllScheduled_durable(ScheduledExecutorServiceSlowTest.java:172)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast-client/1515/testReport/junit/com.hazelcast.client.scheduledexecutor/ClientScheduledExecutorServiceSlowTest/scheduleRandomPartitions_getAllScheduled_durable/

**Comment by hasancelik** [comment]
**schedule_thenDisposeLeakTest**
```
org.junit.runners.model.TestTimedOutException: test timed out after 600000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:304)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:153)
	at com.hazelcast.client.proxy.ClientScheduledExecutorProxy.scheduleOnPartition(ClientScheduledExecutorProxy.java:347)
	at com.hazelcast.client.proxy.ClientScheduledExecutorProxy.schedule(ClientScheduledExecutorProxy.java:103)
	at com.hazelcast.scheduledexecutor.ScheduledExecutorServiceSlowTest.schedule_thenDisposeLeakTest(ScheduledExecutorServiceSlowTest.java:423)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast-client/1529/testReport/junit/com.hazelcast.client.scheduledexecutor/ClientScheduledExecutorServiceSlowTest/schedule_thenDisposeLeakTest/

https://hazelcast-l337.ci.cloudbees.com/view/Sonar/job/Hazelcast-3.x-sonar/com.hazelcast$hazelcast-client/1676/testReport/junit/com.hazelcast.client.scheduledexecutor/ClientScheduledExecutorServiceSlowTest/schedule_thenDisposeLeakTest/

https://hazelcast-l337.ci.cloudbees.com/view/Sonar/job/Hazelcast-3.x-sonar/com.hazelcast$hazelcast-client/1678/testReport/junit/com.hazelcast.client.scheduledexecutor/ClientScheduledExecutorServiceSlowTest/schedule_thenDisposeLeakTest/

**Comment by Holmistr** [comment]
*maintenance*

Reopening as it failed on maintenance nightly: https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-nightly-lab/74/testReport/junit/com.hazelcast.client.scheduledexecutor/ClientScheduledExecutorServiceSlowTest/scheduleRandomPartitions_getAllScheduled_durable/

Stacktrace:
```
java.lang.AssertionError: expected:<11.0> but was:<9.0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:575)
	at org.junit.Assert.assertEquals(Assert.java:700)
	at com.hazelcast.scheduledexecutor.ScheduledExecutorServiceSlowTest.scheduleRandomPartitions_getAllScheduled_durable(ScheduledExecutorServiceSlowTest.java:172)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by tkountis** [comment]
Closed by https://github.com/hazelcast/hazelcast/pull/12865
