### ISSUE TITLE
BackupExpirationBouncingMemberTest.backups_should_be_empty_after_expiration failure

### ISSUE THREAD

**Issue by Donnerbart** [hazelcast/hazelcast#11120]
From a local test run.

**backups_should_be_empty_after_expiration()**
```java
com.hazelcast.core.HazelcastInstanceNotActiveException: Hazelcast instance is not active!

	at com.hazelcast.instance.HazelcastInstanceProxy.getOriginal(HazelcastInstanceProxy.java:303)
	at com.hazelcast.instance.HazelcastInstanceProxy.getMap(HazelcastInstanceProxy.java:96)
	at com.hazelcast.map.BackupExpirationBouncingMemberTest$1.assertSize(BackupExpirationBouncingMemberTest.java:85)
	at com.hazelcast.map.BackupExpirationBouncingMemberTest$1.run(BackupExpirationBouncingMemberTest.java:75)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1086)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1103)
	at com.hazelcast.map.BackupExpirationBouncingMemberTest.backups_should_be_empty_after_expiration(BackupExpirationBouncingMemberTest.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

Log output:
https://gist.github.com/Donnerbart/1c8617ba8bf456a7629cc9c146098b8e

**Comment by ahmetmircik** [comment]
should be fixed via: https://github.com/hazelcast/hazelcast/commit/3c337ed166209291febf375c9401e541bc111079

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: expected:<0> but was:<72>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.map.BackupExpirationBouncingMemberTest$1.assertSize(BackupExpirationBouncingMemberTest.java:85)
	at com.hazelcast.map.BackupExpirationBouncingMemberTest$1.run(BackupExpirationBouncingMemberTest.java:75)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1129)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1146)
	at com.hazelcast.map.BackupExpirationBouncingMemberTest.backups_should_be_empty_after_expiration(BackupExpirationBouncingMemberTest.java:69)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-nightly/com.hazelcast$hazelcast/1454/testReport/junit/com.hazelcast.map/BackupExpirationBouncingMemberTest/backups_should_be_empty_after_expiration/

**Comment by ahmetmircik** [comment]
merged a fix attempt: https://github.com/hazelcast/hazelcast/commit/a1ee74980693c35dcb7bfd89a8151bc155a80bb6

**Comment by Holmistr** [comment]
*maintenance* (commit 8ce2bcfa11baedf3d1b0efe7143c371052adc5ff)

Reopening as it failed on nightly build: https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-nightly/123/testReport/junit/com.hazelcast.map/BackupExpirationBouncingMemberTest/backups_should_be_empty_after_expiration/

Stacktrace:
```
java.lang.AssertionError: Current cluster state is:ACTIVE expected:<0> but was:<19>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.map.BackupExpirationBouncingMemberTest$1.assertSize(BackupExpirationBouncingMemberTest.java:89)
	at com.hazelcast.map.BackupExpirationBouncingMemberTest$1.run(BackupExpirationBouncingMemberTest.java:76)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1246)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1272)
	at com.hazelcast.map.BackupExpirationBouncingMemberTest.backups_should_be_empty_after_expiration(BackupExpirationBouncingMemberTest.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

Standard output:
```
Hiccups measured while running test 'backups_should_be_empty_after_expiration(com.hazelcast.map.BackupExpirationBouncingMemberTest):'
03:09:10, accumulated pauses: 86 ms, max pause: 23 ms, pauses over 1000 ms: 0
03:09:15, accumulated pauses: 512 ms, max pause: 175 ms, pauses over 1000 ms: 0
03:09:20, accumulated pauses: 488 ms, max pause: 20 ms, pauses over 1000 ms: 0
03:09:25, accumulated pauses: 484 ms, max pause: 22 ms, pauses over 1000 ms: 0
03:09:30, accumulated pauses: 635 ms, max pause: 226 ms, pauses over 1000 ms: 0
03:09:35, accumulated pauses: 223 ms, max pause: 5 ms, pauses over 1000 ms: 0
03:09:40, accumulated pauses: 292 ms, max pause: 22 ms, pauses over 1000 ms: 0
03:09:45, accumulated pauses: 214 ms, max pause: 11 ms, pauses over 1000 ms: 0
03:09:50, accumulated pauses: 315 ms, max pause: 25 ms, pauses over 1000 ms: 0
03:09:55, accumulated pauses: 195 ms, max pause: 13 ms, pauses over 1000 ms: 0
03:10:00, accumulated pauses: 190 ms, max pause: 7 ms, pauses over 1000 ms: 0
03:10:05, accumulated pauses: 295 ms, max pause: 35 ms, pauses over 1000 ms: 0
03:10:10, accumulated pauses: 294 ms, max pause: 22 ms, pauses over 1000 ms: 0
03:10:15, accumulated pauses: 264 ms, max pause: 4 ms, pauses over 1000 ms: 0
03:10:20, accumulated pauses: 323 ms, max pause: 16 ms, pauses over 1000 ms: 0
03:10:25, accumulated pauses: 308 ms, max pause: 25 ms, pauses over 1000 ms: 0
03:10:30, accumulated pauses: 295 ms, max pause: 40 ms, pauses over 1000 ms: 0
03:10:35, accumulated pauses: 243 ms, max pause: 22 ms, pauses over 1000 ms: 0
03:10:40, accumulated pauses: 179 ms, max pause: 15 ms, pauses over 1000 ms: 0
03:10:45, accumulated pauses: 254 ms, max pause: 27 ms, pauses over 1000 ms: 0
03:10:50, accumulated pauses: 204 ms, max pause: 6 ms, pauses over 1000 ms: 0
03:10:55, accumulated pauses: 235 ms, max pause: 27 ms, pauses over 1000 ms: 0
03:11:00, accumulated pauses: 214 ms, max pause: 7 ms, pauses over 1000 ms: 0
03:11:05, accumulated pauses: 239 ms, max pause: 10 ms, pauses over 1000 ms: 0
03:11:10, accumulated pauses: 296 ms, max pause: 18 ms, pauses over 1000 ms: 0
03:11:15, accumulated pauses: 165 ms, max pause: 11 ms, pauses over 1000 ms: 0
03:11:20, accumulated pauses: 359 ms, max pause: 110 ms, pauses over 1000 ms: 0
03:11:25, accumulated pauses: 237 ms, max pause: 25 ms, pauses over 1000 ms: 0
03:11:30, accumulated pauses: 173 ms, max pause: 53 ms, pauses over 1000 ms: 0
03:11:35, accumulated pauses: 540 ms, max pause: 440 ms, pauses over 1000 ms: 0
```

**Comment by Holmistr** [comment]
Closed by https://github.com/hazelcast/hazelcast/pull/13232
