### ISSUE TITLE
ClientStatisticsTest fails on fast collections

### ISSUE THREAD

**Issue by Donnerbart** [hazelcast/hazelcast#11156]
**com.hazelcast.client.statistics.ClientStatisticsTest.testStatisticsCollectionNonDefaultPeriod**
```java
java.lang.AssertionError: Time difference between two collections is 996 msecs but it should be greater than 1000 msecs
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.client.statistics.ClientStatisticsTest.verifyThatCollectionIsPeriodic(ClientStatisticsTest.java:265)
	at com.hazelcast.client.statistics.ClientStatisticsTest.testStatisticsCollectionNonDefaultPeriod(ClientStatisticsTest.java:126)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/10292/testReport/junit/com.hazelcast.client.statistics/ClientStatisticsTest/testStatisticsCollectionNonDefaultPeriod/

**Comment by Donnerbart** [comment]
Fixed via https://github.com/hazelcast/hazelcast/commit/4560e60dc3641f486a89f4d114d97f47991cd5d7
