### ISSUE TITLE
[query-cache] QueryCache destroy, ConcurrentModificationException, NoSuchElementException

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#11185]
```
java.util.NoSuchElementException
java.util.ConcurrentModificationException    at java.util.ArrayList$Itr.next(ArrayList.java:854)
at com.hazelcast.map.impl.querycache.subscriber.NodeQueryCacheConfigurator.removeConfiguration(NodeQueryCacheConfigurator.java:86)    at java.util.ArrayList$Itr.remove(ArrayList.java:873)
at com.hazelcast.map.impl.querycache.subscriber.DefaultQueryCache.removeConfig(DefaultQueryCache.java:236)
at com.hazelcast.map.impl.querycache.subscriber.NodeQueryCacheConfigurator.removeConfiguration(NodeQueryCacheConfigurator.java:88)    at com.hazelcast.map.impl.querycache.subscriber.DefaultQueryCache.destroyLocalResources(DefaultQueryCache.java:209)
at com.hazelcast.map.impl.querycache.subscriber.DefaultQueryCache.removeConfig(DefaultQueryCache.java:236)
```

```
java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.remove(ArrayList.java:873)
    at com.hazelcast.map.impl.querycache.subscriber.NodeQueryCacheConfigurator.removeConfiguration(NodeQueryCacheConfigurator.java:94)
    at com.hazelcast.map.impl.querycache.subscriber.DefaultQueryCache.removeConfig(DefaultQueryCache.java:236)
    at com.hazelcast.map.impl.querycache.subscriber.DefaultQueryCache.destroyLocalResources(DefaultQueryCache.java:209)
    at com.hazelcast.map.impl.querycache.subscriber.DefaultQueryCache.destroy(DefaultQueryCache.java:178)
```

```
java.util.NoSuchElementException
    at java.util.ArrayList$Itr.next(ArrayList.java:854)
    at com.hazelcast.map.impl.querycache.subscriber.NodeQueryCacheConfigurator.removeConfiguration(NodeQueryCacheConfigurator.java:92)
    at com.hazelcast.map.impl.querycache.subscriber.AbstractQueryCacheEndToEndConstructor.removeQueryCacheConfig(AbstractQueryCacheEndToEndConstructor.java:170)
    at com.hazelcast.map.impl.querycache.subscriber.AbstractQueryCacheEndToEndConstructor.createNew(AbstractQueryCacheEndToEndConstructor.java:95)
    at com.hazelcast.map.impl.querycache.subscriber.AbstractQueryCacheEndToEndConstructor.createNew(AbstractQueryCacheEndToEndConstructor.java:40)
    at com.hazelcast.util.ConcurrencyUtil.getOrPutSynchronized(ConcurrencyUtil.java:73)
    at com.hazelcast.map.impl.querycache.subscriber.QueryCacheEndToEndProvider.getOrCreateQueryCache(QueryCacheEndToEndProvider.java:76)
    at com.hazelcast.map.impl.proxy.MapProxyImpl.createQueryCache(MapProxyImpl.java:1003)
    at com.hazelcast.map.impl.proxy.MapProxyImpl.getQueryCacheInternal(MapProxyImpl.java:995)
    at com.hazelcast.map.impl.proxy.MapProxyImpl.getQueryCache(MapProxyImpl.java:970)
```

**Comment by mmedenjak** [comment]
Possibly related : https://github.com/hazelcast/hazelcast/pull/11135

**Comment by vbekiaris** [comment]
Rather related to #11149, #11135 is about `Cache` data structure.
