### ISSUE TITLE
Semaphore create use destroy hanging at semaphore.acquire();

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#11245]
a run of a create use destroy test hit a time out,  on a Semaphore test http://54.82.84.143/~jenkins/workspace/stable-All-const/3.9-SNAPSHOT/2017_08_26-14_59_10/destroy/create-use-dist-destroy/output/HZ/HzMember2HZ/

`_create-use-dist-destroy_createUseDistDestroy_semaphore HzMember2HZ timeout`

I have collected the stack traces, in all client and member stdout files.

in the logs / stack trace  of Member2 i see

`at hzcmd.semaphore.CreateUse.timeStep(CreateUse.java:14)`

https://github.com/hazelcast/hzCmd-bench/blob/60c7ef050dc25712854bb4d788b31818a5f4c2b0/src/main/java/hzcmd/semaphore/CreateUse.java#L14

its not a new test, and normally passes, so it look like its very rare occurrence, to hang 
`at hzcmd.semaphore.CreateUse.timeStep(CreateUse.java:14)`

4 clients 4 members, each running with 1 thread 
http://54.82.84.143/~jenkins/workspace/stable-All-const/3.9-SNAPSHOT/2017_08_26-14_59_10/destroy/create-use-dist-destroy/createUseDestroy

jenkins job https://hazelcast-l337.ci.cloudbees.com/view/stable/job/stable-All-const/4/console

**Comment by Danny-Hazelcast** [comment]
/disk1/jenkins/workspace/stable-All-const/3.9-SNAPSHOT/2017_08_26-14_59_10/destroy/create-use-dist-destroy/output/HZ

```
./HzMember2HZ/out.txt:	at hzcmd.semaphore.CreateUse.timeStep(CreateUse.java:14)
./HzMember1HZ/out.txt:	at hzcmd.executor.scheduled.CreateUseDestroy.timeStep(CreateUseDestroy.java:28)
./HzMember1HZ/out.txt:	at hzcmd.executor.scheduled.CreateUseDestroy.timeStep(CreateUseDestroy.java:28)
```

**Comment by mmedenjak** [comment]
Test :
```
public class CreateUse extends SemaphoreBench {

    public int max=10;

    public void timeStep() {
        ISemaphore semaphore = hzInstance.getSemaphore(name+random.nextInt(max));
        try {
            semaphore.init(Integer.MAX_VALUE);
            semaphore.acquire();
        } catch (InterruptedException e) {}
        semaphore.release();
        semaphore.destroy();
    }
}
```

Benchmark:
```
_create-use-dist-destroy_createUseDistDestroy_mapBak1HD-ncHD@class=hzcmd.map.CreateUse
_create-use-dist-destroy_createUseDistDestroy_mapBak1HD-ncHD@threads=1
_create-use-dist-destroy_createUseDistDestroy_mapBak1HD-ncHD@name=mapBak1HD-ncHD_CreateUseDestroy_create-use-dist-destroy
_create-use-dist-destroy_createUseDistDestroy_mapBak1HD-ncHD@max=1
_create-use-dist-destroy_createUseDistDestroy_mapBak1HD-ncHD@ignore=com.hazelcast.spi.exception.DistributedObjectDestroyedException

_create-use-dist-destroy_createUseDistDestroy_mapBak1HD@class=hzcmd.map.CreateUse
_create-use-dist-destroy_createUseDistDestroy_mapBak1HD@threads=1
_create-use-dist-destroy_createUseDistDestroy_mapBak1HD@name=mapBak1HDCreateUseDestroy_create-use-dist-destroy
_create-use-dist-destroy_createUseDistDestroy_mapBak1HD@max=1
_create-use-dist-destroy_createUseDistDestroy_mapBak1HD@ignore=com.hazelcast.spi.exception.DistributedObjectDestroyedException

_create-use-dist-destroy_createUseDistDestroy_mapBak1HD_queryCache@class=hzcmd.map.cqc.CreateUse
_create-use-dist-destroy_createUseDistDestroy_mapBak1HD_queryCache@threads=1
_create-use-dist-destroy_createUseDistDestroy_mapBak1HD_queryCache@name=mapBak1HD_queryCache_createUseDistDestroy_create-use-dist-destroy
_create-use-dist-destroy_createUseDistDestroy_mapBak1HD_queryCache@max=1
_create-use-dist-destroy_createUseDistDestroy_mapBak1HD_queryCache@ignore=com.hazelcast.spi.exception.DistributedObjectDestroyedException

_create-use-dist-destroy_createUseDistDestroy_mapBak1@class=hzcmd.map.CreateUse
_create-use-dist-destroy_createUseDistDestroy_mapBak1@threads=1
_create-use-dist-destroy_createUseDistDestroy_mapBak1@name=mapBak1createUseDestroy_create-use-dist-destroy
_create-use-dist-destroy_createUseDistDestroy_mapBak1@max=1
_create-use-dist-destroy_createUseDistDestroy_mapBak1@ignore=com.hazelcast.spi.exception.DistributedObjectDestroyedException

_create-use-dist-destroy_createUseDistDestroy_cacheBak1HD-ncHD@class=hzcmd.cache.CreateUse
_create-use-dist-destroy_createUseDistDestroy_cacheBak1HD-ncHD@threads=1
_create-use-dist-destroy_createUseDistDestroy_cacheBak1HD-ncHD@name=cacheBak1HD-ncHD_CreateUseDestroy_create-use-dist-destroy
_create-use-dist-destroy_createUseDistDestroy_cacheBak1HD-ncHD@max=1
_create-use-dist-destroy_createUseDistDestroy_cacheBak1HD-ncHD@ignore=com.hazelcast.spi.exception.DistributedObjectDestroyedException:com.hazelcast.cache.CacheNotExistsException:java.lang.IllegalStateException

_create-use-dist-destroy_createUseDistDestroy_cacheBak1HD@class=hzcmd.cache.CreateUse
_create-use-dist-destroy_createUseDistDestroy_cacheBak1HD@threads=1
_create-use-dist-destroy_createUseDistDestroy_cacheBak1HD@name=cacheBak1HDCreateUseDestroy_create-use-dist-destroy
_create-use-dist-destroy_createUseDistDestroy_cacheBak1HD@max=1
_create-use-dist-destroy_createUseDistDestroy_cacheBak1HD@ignore=com.hazelcast.spi.exception.DistributedObjectDestroyedException:com.hazelcast.cache.CacheNotExistsException:java.lang.IllegalStateException

_create-use-dist-destroy_createUseDistDestroy_cacheBak1@class=hzcmd.cache.CreateUse
_create-use-dist-destroy_createUseDistDestroy_cacheBak1@threads=1
_create-use-dist-destroy_createUseDistDestroy_cacheBak1@name=cacheBak1createUseDestroy_create-use-dist-destroy
_create-use-dist-destroy_createUseDistDestroy_cacheBak1@max=1
_create-use-dist-destroy_createUseDistDestroy_cacheBak1@ignore=com.hazelcast.spi.exception.DistributedObjectDestroyedException:com.hazelcast.cache.CacheNotExistsException:java.lang.IllegalStateException


_create-use-dist-destroy_createUseDistDestroy_atomic@class=hzcmd.atomic.CreateUse
_create-use-dist-destroy_createUseDistDestroy_atomic@threads=1
_create-use-dist-destroy_createUseDistDestroy_atomic@name=atomicCreateUseDestroy_create-use-dist-destroy
_create-use-dist-destroy_createUseDistDestroy_atomic@max=1
_create-use-dist-destroy_createUseDistDestroy_atomic@ignore=com.hazelcast.spi.exception.DistributedObjectDestroyedException


_create-use-dist-destroy_createUseDistDestroy_executor@class=hzcmd.executor.regular.CreateUse
_create-use-dist-destroy_createUseDistDestroy_executor@threads=1
_create-use-dist-destroy_createUseDistDestroy_executor@name=executorCreateUseDestroy_create-use-dist-destroy
_create-use-dist-destroy_createUseDistDestroy_executor@max=1
_create-use-dist-destroy_createUseDistDestroy_executor@ignore=com.hazelcast.spi.exception.DistributedObjectDestroyedException

_create-use-dist-destroy_createUseDistDestroy_scheduledExecutor@class=hzcmd.executor.scheduled.CreateUse
_create-use-dist-destroy_createUseDistDestroy_scheduledExecutor@threads=1
_create-use-dist-destroy_createUseDistDestroy_scheduledExecutor@name=scheduledExecutorCreateUseDestroy_create-use-dist-destroy
_create-use-dist-destroy_createUseDistDestroy_scheduledExecutor@max=1
_create-use-dist-destroy_createUseDistDestroy_scheduledExecutor@ignore=com.hazelcast.spi.exception.DistributedObjectDestroyedException:java.util.concurrent.RejectedExecutionException

_create-use-dist-destroy_createUseDistDestroy_durableExecutor@class=hzcmd.executor.durable.CreateUse
_create-use-dist-destroy_createUseDistDestroy_durableExecutor@threads=1
_create-use-dist-destroy_createUseDistDestroy_durableExecutor@name=durableExecutorCreateUseDestroy_create-use-dist-destroy
_create-use-dist-destroy_createUseDistDestroy_durableExecutor@max=1
_create-use-dist-destroy_createUseDistDestroy_durableExecutor@ignore=com.hazelcast.spi.exception.DistributedObjectDestroyedException

_create-use-dist-destroy_createUseDistDestroy_id@class=hzcmd.id.CreateUse
_create-use-dist-destroy_createUseDistDestroy_id@threads=1
_create-use-dist-destroy_createUseDistDestroy_id@name=idCreateUseDestroy_create-use-dist-destroy
_create-use-dist-destroy_createUseDistDestroy_id@max=1
_create-use-dist-destroy_createUseDistDestroy_id@ignore=com.hazelcast.spi.exception.DistributedObjectDestroyedException


_create-use-dist-destroy_createUseDistDestroy_latch@class=hzcmd.latch.CreateUse
_create-use-dist-destroy_createUseDistDestroy_latch@threads=1
_create-use-dist-destroy_createUseDistDestroy_latch@name=latchCreateUseDestroy_create-use-dist-destroy
_create-use-dist-destroy_createUseDistDestroy_latch@max=1
_create-use-dist-destroy_createUseDistDestroy_latch@ignore=com.hazelcast.spi.exception.DistributedObjectDestroyedException


_create-use-dist-destroy_createUseDistDestroy_list@class=hzcmd.list.CreateUse
_create-use-dist-destroy_createUseDistDestroy_list@threads=1
_create-use-dist-destroy_createUseDistDestroy_list@name=listCreateUseDestroy_create-use-dist-destroy
_create-use-dist-destroy_createUseDistDestroy_list@max=1
_create-use-dist-destroy_createUseDistDestroy_list@ignore=com.hazelcast.spi.exception.DistributedObjectDestroyedException


_create-use-dist-destroy_createUseDistDestroy_lock@class=hzcmd.lock.CreateUse
_create-use-dist-destroy_createUseDistDestroy_lock@threads=1
_create-use-dist-destroy_createUseDistDestroy_lock@name=lockCreateUseDestroy_create-use-dist-destroy
_create-use-dist-destroy_createUseDistDestroy_lock@max=1
_create-use-dist-destroy_createUseDistDestroy_lock@ignore=com.hazelcast.spi.exception.DistributedObjectDestroyedException


_create-use-dist-destroy_createUseDistDestroy_queue@class=hzcmd.queue.CreateUse
_create-use-dist-destroy_createUseDistDestroy_queue@threads=1
_create-use-dist-destroy_createUseDistDestroy_queue@name=queueCreateUseDestroy_create-use-dist-destroy
_create-use-dist-destroy_createUseDistDestroy_queue@max=1
_create-use-dist-destroy_createUseDistDestroy_queue@ignore=com.hazelcast.spi.exception.DistributedObjectDestroyedException


_create-use-dist-destroy_createUseDistDestroy_repmap@class=hzcmd.repmap.CreateUse
_create-use-dist-destroy_createUseDistDestroy_repmap@threads=1
_create-use-dist-destroy_createUseDistDestroy_repmap@name=repmapCreateUseDestroy_create-use-dist-destroy
_create-use-dist-destroy_createUseDistDestroy_repmap@max=1
_create-use-dist-destroy_createUseDistDestroy_repmap@ignore=com.hazelcast.spi.exception.DistributedObjectDestroyedException


_create-use-dist-destroy_createUseDistDestroy_ring@class=hzcmd.ring.CreateUse
_create-use-dist-destroy_createUseDistDestroy_ring@threads=1
_create-use-dist-destroy_createUseDistDestroy_ring@name=ringCreateUseDestroy_create-use-dist-destroy
_create-use-dist-destroy_createUseDistDestroy_ring@max=1
_create-use-dist-destroy_createUseDistDestroy_ring@ignore=com.hazelcast.spi.exception.DistributedObjectDestroyedException


_create-use-dist-destroy_createUseDistDestroy_semaphore@class=hzcmd.semaphore.CreateUse
_create-use-dist-destroy_createUseDistDestroy_semaphore@threads=1
_create-use-dist-destroy_createUseDistDestroy_semaphore@name=semaphoreCreateUseDestroy_create-use-dist-destroy
_create-use-dist-destroy_createUseDistDestroy_semaphore@max=1
_create-use-dist-destroy_createUseDistDestroy_semaphore@ignore=com.hazelcast.spi.exception.DistributedObjectDestroyedException


_create-use-dist-destroy_createUseDistDestroy_set@class=hzcmd.set.CreateUse
_create-use-dist-destroy_createUseDistDestroy_set@threads=1
_create-use-dist-destroy_createUseDistDestroy_set@name=setCreateUseDestroy_create-use-dist-destroy
_create-use-dist-destroy_createUseDistDestroy_set@max=1
_create-use-dist-destroy_createUseDistDestroy_set@ignore=com.hazelcast.spi.exception.DistributedObjectDestroyedException


_create-use-dist-destroy_createUseDistDestroy_reliableTopic@class=hzcmd.topic.CreateUse
_create-use-dist-destroy_createUseDistDestroy_reliableTopic@reliable=true
_create-use-dist-destroy_createUseDistDestroy_reliableTopic@threads=1
_create-use-dist-destroy_createUseDistDestroy_reliableTopic@name=topicReliableCreateUseDestroy_create-use-dist-destroy
_create-use-dist-destroy_createUseDistDestroy_reliableTopic@max=1
_create-use-dist-destroy_createUseDistDestroy_reliableTopic@ignore=com.hazelcast.spi.exception.DistributedObjectDestroyedException

_create-use-dist-destroy_createUseDistDestroy_topic@class=hzcmd.topic.CreateUse
_create-use-dist-destroy_createUseDistDestroy_topic@reliable=false
_create-use-dist-destroy_createUseDistDestroy_topic@threads=1
_create-use-dist-destroy_createUseDistDestroy_topic@name=topicCreateUseDestroy_create-use-dist-destroy
_create-use-dist-destroy_createUseDistDestroy_topic@max=1
_create-use-dist-destroy_createUseDistDestroy_topic@ignore=com.hazelcast.spi.exception.DistributedObjectDestroyedException

_create-use-dist-destroy_createUseDistDestroy-Obj@class=hzcmd.distributed.Destroy
_create-use-dist-destroy_createUseDistDestroy-Obj@threads=2
```

**Comment by Danny-Hazelcast** [comment]
@mmedenjak 's  explanation

Since destroy and partition operations are concurrent and multiple clients are using the same semaphore, one client may create the semaphore and immediately afterwards, an another client may destroy it. The semaphore.acquire() will then implicitly recreate the semaphore with a permit count of zero and hang on the first client.

 explanation for semaphore case is correct, i have changed the test to just create destroy and it
is not longer hanging.
