### ISSUE TITLE
[map] [event] MapListenerTest.testListener_eventCountsCorrect

### ISSUE THREAD

**Issue by tombujok** [hazelcast/hazelcast#11285]

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: expected:<46> but was:<38>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.map.MapListenerTest.testListener_eventCountsCorrect(MapListenerTest.java:70)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK1.6-freestyle/217/testReport/com.hazelcast.map/MapListenerTest/testListener_eventCountsCorrect/

**Comment by Donnerbart** [comment]
The build was triggered before the tests were ignored. They are now properly suppressed.
