### ISSUE TITLE
MapLoaderTest.testNullValue_loadAll_withInterceptor

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#11298]
```
java.lang.AssertionError: Expected test to throw (an instance of java.lang.NullPointerException and exception with message is "Value loaded by a MapLoader cannot be null.")
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.rules.ExpectedException.failDueToMissingException(ExpectedException.java:263)
	at org.junit.rules.ExpectedException.access$200(ExpectedException.java:106)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:245)
	at com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:15)
	at com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:104)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:50)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:29)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at com.hazelcast.test.AbstractHazelcastClassRunner$3.evaluate(AbstractHazelcastClassRunner.java:327)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:108)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:78)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:54)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:144)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast$hazelcast/1393/testReport/junit/com.hazelcast.map.impl.mapstore/MapLoaderTest/testNullValue_loadAll_withInterceptor/

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast$hazelcast/1390/testReport/junit/com.hazelcast.map.impl.mapstore/MapLoaderTest/testNullValue_loadAll_withInterceptor/

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.8/com.hazelcast$hazelcast/704/testReport/junit/com.hazelcast.map.impl.mapstore/MapLoaderTest/testNullValue_loadAll_withInterceptor/

**Comment by hasancelik** [comment]
*maintenance*
```
java.lang.AssertionError: Expected test to throw (an instance of java.lang.NullPointerException and exception with message is "Value loaded by a MapLoader cannot be null.")
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.rules.ExpectedException.failDueToMissingException(ExpectedException.java:263)
	at org.junit.rules.ExpectedException.access$200(ExpectedException.java:106)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:245)
	at com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:103)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:50)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:29)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at com.hazelcast.test.AbstractHazelcastClassRunner$1.evaluate(AbstractHazelcastClassRunner.java:280)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:108)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:78)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:54)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:144)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-IbmJDK1.7/com.hazelcast$hazelcast/557/testReport/junit/com.hazelcast.map.impl.mapstore/MapLoaderTest/testNullValue_loadAll_withInterceptor/

**Comment by hasancelik** [comment]
*maintenance*
```
java.lang.AssertionError: Expected test to throw (an instance of java.lang.NullPointerException and exception with message is "Value loaded by a MapLoader cannot be null.")
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.rules.ExpectedException.failDueToMissingException(ExpectedException.java:263)
	at org.junit.rules.ExpectedException.access$200(ExpectedException.java:106)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:245)
	at com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:103)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:50)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:29)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at com.hazelcast.test.AbstractHazelcastClassRunner$1.evaluate(AbstractHazelcastClassRunner.java:280)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:108)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:78)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:54)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:144)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-IbmJDK1.7/com.hazelcast$hazelcast/561/testReport/junit/com.hazelcast.map.impl.mapstore/MapLoaderTest/testNullValue_loadAll_withInterceptor/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: Expected test to throw (an instance of java.lang.NullPointerException and exception with message is "Value loaded by a MapLoader cannot be null.")
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.rules.ExpectedException.failDueToMissingException(ExpectedException.java:263)
	at org.junit.rules.ExpectedException.access$200(ExpectedException.java:106)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:245)
	at com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:103)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:50)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:29)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at com.hazelcast.test.AbstractHazelcastClassRunner$1.evaluate(AbstractHazelcastClassRunner.java:280)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:108)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:78)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:54)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:144)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-IbmJDK1.7/562/com.hazelcast$hazelcast/testReport/com.hazelcast.map.impl.mapstore/MapLoaderTest/testNullValue_loadAll_withInterceptor/

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-IbmJDK1.7/com.hazelcast$hazelcast/563/testReport/junit/com.hazelcast.map.impl.mapstore/MapLoaderTest/testNullKey_loadAll/

**Comment by ahmetmircik** [comment]
@hasancelik will update JVMs.

**Comment by hasancelik** [comment]
@ahmetmircik I have updated JDK versions, current versions are:

```
16:58:59 + java -version
16:59:00 java version "1.7.0"
16:59:00 Java(TM) SE Runtime Environment (build pxa6470sr10fp1-20170215_01(SR10 FP1))
16:59:00 IBM J9 VM (build 2.6, JRE 1.7.0 Linux amd64-64 Compressed References 20170111_332921 (JIT enabled, AOT enabled)
16:59:00 J9VM - R26_Java726_SR10_20170111_1358_B332921
16:59:00 JIT  - tr.r11_20170107_130494
16:59:00 GC   - R26_Java726_SR10_20170111_1358_B332921_CMPRSS
16:59:00 J9CL - 20170111_332921)
16:59:00 JCL - 20170215_01 based on Oracle jdk7u131-b12
```

```
16:59:51 + java -version
16:59:51 java version "1.8.0"
16:59:51 Java(TM) SE Runtime Environment (build pxa6480sr4fp1-20170215_01(SR4 FP1))
16:59:51 IBM J9 VM (build 2.8, JRE 1.8.0 Linux amd64-64 Compressed References 20170209_336038 (JIT enabled, AOT enabled)
16:59:51 J9VM - R28_20170209_0201_B336038
16:59:51 JIT  - tr.r14.java.green_20170125_131456
16:59:51 GC   - R28_20170209_0201_B336038_CMPRSS
16:59:51 J9CL - 20170209_336038)
16:59:51 JCL - 20170215_01 based on Oracle jdk8u121-b13
```

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: Expected a NPE due to a null value in a MapLoader
	at org.junit.Assert.fail(Assert.java:88)
	at com.hazelcast.map.impl.mapstore.MapLoaderTest.testNullValue_loadAll_withInterceptor(MapLoaderTest.java:369)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast$hazelcast/1431/testReport/junit/com.hazelcast.map.impl.mapstore/MapLoaderTest/testNullValue_loadAll_withInterceptor/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: Expected test to throw (an instance of java.lang.NullPointerException and exception with message is "Value loaded by a MapLoader cannot be null.")
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.rules.ExpectedException.failDueToMissingException(ExpectedException.java:263)
	at org.junit.rules.ExpectedException.access$200(ExpectedException.java:106)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:245)
	at com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:103)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:50)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:29)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at com.hazelcast.test.AbstractHazelcastClassRunner$1.evaluate(AbstractHazelcastClassRunner.java:286)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:108)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:78)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:54)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:144)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-IbmJDK1.8/com.hazelcast$hazelcast/259/testReport/junit/com.hazelcast.map.impl.mapstore/MapLoaderTest/testNullValue_loadAll_withInterceptor/

**Comment by hasancelik** [comment]
Failed at **Oracle** build first time.
```
java.lang.AssertionError: Expected test to throw (an instance of java.lang.NullPointerException and exception with message is "Value loaded by a MapLoader cannot be null.")
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.rules.ExpectedException.failDueToMissingException(ExpectedException.java:263)
	at org.junit.rules.ExpectedException.access$200(ExpectedException.java:106)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:245)
	at com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:103)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:50)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:29)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at com.hazelcast.test.AbstractHazelcastClassRunner$1.evaluate(AbstractHazelcastClassRunner.java:286)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:108)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:78)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:54)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:144)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-OracleJDK8/com.hazelcast$hazelcast/553/testReport/junit/com.hazelcast.map.impl.mapstore/MapLoaderTest/testNullValue_loadAll_withInterceptor/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: Expected a NPE due to a null value in a MapLoader
	at org.junit.Assert.fail(Assert.java:88)
	at com.hazelcast.map.impl.mapstore.MapLoaderTest.testNullValue_loadAll_withInterceptor(MapLoaderTest.java:369)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.7-freestyle/14/testReport/junit/com.hazelcast.map.impl.mapstore/MapLoaderTest/testNullValue_loadAll_withInterceptor/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: Expected a NPE due to a null value in a MapLoader
	at org.junit.Assert.fail(Assert.java:88)
	at com.hazelcast.map.impl.mapstore.MapLoaderTest.testNullValue_loadAll_withInterceptor(MapLoaderTest.java:369)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.7-freestyle/19/testReport/junit/com.hazelcast.map.impl.mapstore/MapLoaderTest/testNullValue_loadAll_withInterceptor/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: Expected a NPE due to a null value in a MapLoader
	at org.junit.Assert.fail(Assert.java:88)
	at com.hazelcast.map.impl.mapstore.MapLoaderTest.testNullValue_loadAll_withInterceptor(MapLoaderTest.java:369)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.7-freestyle/26/testReport/junit/com.hazelcast.map.impl.mapstore/MapLoaderTest/testNullValue_loadAll_withInterceptor/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: Expected a NPE due to a null value in a MapLoader
	at org.junit.Assert.fail(Assert.java:88)
	at com.hazelcast.map.impl.mapstore.MapLoaderTest.testNullValue_loadAll_withInterceptor(MapLoaderTest.java:369)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.8/com.hazelcast$hazelcast/773/testReport/junit/com.hazelcast.map.impl.mapstore/MapLoaderTest/testNullValue_loadAll_withInterceptor/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: Expected a NPE due to a null value in a MapLoader
	at org.junit.Assert.fail(Assert.java:88)
	at com.hazelcast.map.impl.mapstore.MapLoaderTest.testNullValue_loadAll_withInterceptor(MapLoaderTest.java:369)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.8/com.hazelcast$hazelcast/784/testReport/junit/com.hazelcast.map.impl.mapstore/MapLoaderTest/testNullValue_loadAll_withInterceptor/

**Comment by sancar** [comment]
master
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/11689/testReport/junit/com.hazelcast.map.impl.mapstore/MapLoaderTest/testNullValue_loadAll_withInterceptor/

Error Message

Expected a NPE due to a null value in a MapLoader
Stacktrace
```
java.lang.AssertionError: Expected a NPE due to a null value in a MapLoader
	at org.junit.Assert.fail(Assert.java:88)
	at com.hazelcast.map.impl.mapstore.MapLoaderTest.testNullValue_loadAll_withInterceptor(MapLoaderTest.java:369)
```

**Comment by Donnerbart** [comment]
**com.hazelcast.map.impl.mapstore.MapLoaderTest.testNullValue_loadAll_withInterceptor**
```java
java.lang.AssertionError: Expected a NPE due to a null value in a MapLoader
	at org.junit.Assert.fail(Assert.java:88)
	at com.hazelcast.map.impl.mapstore.MapLoaderTest.testNullValue_loadAll_withInterceptor(MapLoaderTest.java:369)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/11711/testReport/junit/com.hazelcast.map.impl.mapstore/MapLoaderTest/testNullValue_loadAll_withInterceptor/

**Comment by hasancelik** [comment]
*maintenance*
**testNullValue_loadAll_withInterceptor**
```
java.lang.AssertionError: Expected a NPE due to a null value in a MapLoader
	at org.junit.Assert.fail(Assert.java:88)
	at com.hazelcast.map.impl.mapstore.MapLoaderTest.testNullValue_loadAll_withInterceptor(MapLoaderTest.java:369)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-IbmJDK1.8/com.hazelcast$hazelcast/275/testReport/junit/com.hazelcast.map.impl.mapstore/MapLoaderTest/testNullValue_loadAll_withInterceptor/

**Comment by hasancelik** [comment]
*master*
**testNullValue_loadAll_withInterceptor**
```
java.lang.AssertionError: Expected a NPE due to a null value in a MapLoader
	at org.junit.Assert.fail(Assert.java:88)
	at com.hazelcast.map.impl.mapstore.MapLoaderTest.testNullValue_loadAll_withInterceptor(MapLoaderTest.java:369)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.8/com.hazelcast$hazelcast/798/testReport/junit/com.hazelcast.map.impl.mapstore/MapLoaderTest/testNullValue_loadAll_withInterceptor/

**Comment by Holmistr** [comment]
FIxed by: https://github.com/hazelcast/hazelcast/pull/11918

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: Expected a NPE due to a null value in a MapLoader
	at org.junit.Assert.fail(Assert.java:88)
	at com.hazelcast.map.impl.mapstore.MapLoaderTest.testNullValue_loadAll_withInterceptor(MapLoaderTest.java:369)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-IbmJDK1.7-freestyle/23/testReport/junit/com.hazelcast.map.impl.mapstore/MapLoaderTest/testNullValue_loadAll_withInterceptor/

**Comment by Holmistr** [comment]
This is failing on the maintenance branch, I will backport the fix there as well.

**Comment by hasancelik** [comment]
*maintenance*
```
java.lang.AssertionError: Expected a NPE due to a null value in a MapLoader
	at org.junit.Assert.fail(Assert.java:88)
	at com.hazelcast.map.impl.mapstore.MapLoaderTest.testNullValue_loadAll_withInterceptor(MapLoaderTest.java:369)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-IbmJDK1.7-freestyle/26/testReport/junit/com.hazelcast.map.impl.mapstore/MapLoaderTest/testNullValue_loadAll_withInterceptor/

**Comment by hasancelik** [comment]
*maintenance*
```
java.lang.AssertionError: Expected a NPE due to a null value in a MapLoader
	at org.junit.Assert.fail(Assert.java:88)
	at com.hazelcast.map.impl.mapstore.MapLoaderTest.testNullValue_loadAll_withInterceptor(MapLoaderTest.java:369)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-freestyle/427/testReport/junit/com.hazelcast.map.impl.mapstore/MapLoaderTest/testNullValue_loadAll_withInterceptor/

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-IbmJDK1.7-freestyle/31/testReport/junit/com.hazelcast.map.impl.mapstore/MapLoaderTest/testNullValue_loadAll_withInterceptor/

**Comment by Holmistr** [comment]
Fixed by https://github.com/hazelcast/hazelcast/pull/12076
