### ISSUE TITLE
ClientToMemberDiscoveryTest

### ISSUE THREAD

**Issue by Donnerbart** [hazelcast/hazelcast#11304]
**com.hazelcast.client.spi.impl.discovery.ClientToMemberDiscoveryTest.clientTest**
```java
java.lang.IllegalStateException: Unable to connect to any address in the config! The following addresses were tried: []
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.connectToClusterInternal(ClientConnectionManagerImpl.java:849)
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.access$1500(ClientConnectionManagerImpl.java:100)
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl$3.call(ClientConnectionManagerImpl.java:859)
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl$3.call(ClientConnectionManagerImpl.java:855)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/10579/testReport/junit/com.hazelcast.client.spi.impl.discovery/ClientToMemberDiscoveryTest/clientTest/

There is also this follow-up issue from the same run:
**com.hazelcast.client.spi.impl.discovery.ClientToMemberDiscoveryTest.com.hazelcast.client.spi.impl.discovery.ClientToMemberDiscoveryTest**
```java
java.lang.IllegalStateException: Instances haven't been shut down: [HazelcastInstance{name='_hzInstance_102_dev', node=[127.0.0.1]:5079}, HazelcastInstance{name='_hzInstance_103_dev', node=[127.0.0.1]:5080}]
	at com.hazelcast.test.AbstractHazelcastClassRunner$3.evaluate(AbstractHazelcastClassRunner.java:333)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:108)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:78)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:54)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:144)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/10579/testReport/junit/com.hazelcast.client.spi.impl.discovery/ClientToMemberDiscoveryTest/com_hazelcast_client_spi_impl_discovery_ClientToMemberDiscoveryTest/

**Comment by Donnerbart** [comment]
The second issue has been fixed via: https://github.com/hazelcast/hazelcast/commit/a58b3ed4dc05a51279933eefac225c7fd70b0526

Could not reproduce the first one locally.

**Comment by sancar** [comment]
I wrote this test initially to prove that multicast discovery is broken. It was constantly failing in my local back then. I send the following pr expecting that it will fail on pr builder too. 
https://github.com/hazelcast/hazelcast/pull/11016
It seems that test is passed in pr builder and pr is merged. 

Basically multicast discovery is not waiting enough for UDP packages. 

And seems like this is directly related to following fix
https://github.com/hazelcast/hazelcast/pull/11312

Members and clients use same infrastructure, so @jerrinot fix should also fix this test.

**Comment by jerrinot** [comment]
fixed by #11312

**Comment by Donnerbart** [comment]
`com.hazelcast.client.spi.impl.discovery.ClientToMemberDiscoveryTest.clientTest`
```java
java.lang.IllegalStateException: Unable to connect to any address! The following addresses were tried: []
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.connectToClusterInternal(ClientConnectionManagerImpl.java:875)
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.access$1500(ClientConnectionManagerImpl.java:102)
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl$3.call(ClientConnectionManagerImpl.java:885)
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl$3.call(ClientConnectionManagerImpl.java:881)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/12757/testReport/junit/com.hazelcast.client.spi.impl.discovery/ClientToMemberDiscoveryTest/clientTest/

**Comment by Donnerbart** [comment]
**com.hazelcast.client.spi.impl.discovery.ClientToMemberDiscoveryTest.clientTest**
```java
java.lang.IllegalStateException: Unable to connect to any address! The following addresses were tried: []
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.connectToClusterInternal(ClientConnectionManagerImpl.java:849)
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.access$1200(ClientConnectionManagerImpl.java:103)
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl$2.call(ClientConnectionManagerImpl.java:859)
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl$2.call(ClientConnectionManagerImpl.java:855)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/12972/testReport/junit/com.hazelcast.client.spi.impl.discovery/ClientToMemberDiscoveryTest/clientTest/

**Comment by Holmistr** [comment]
This issue occurred again in the PR builder: https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/14543/testReport/junit/com.hazelcast.client.spi.impl.discovery/ClientToMemberDiscoveryTest/clientTest/

Stacktrace: 
```
java.lang.IllegalStateException: Unable to connect to any address in the config! The following addresses were tried: []
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.connectToClusterInternal(ClientConnectionManagerImpl.java:851)
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.access$1200(ClientConnectionManagerImpl.java:104)
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl$2.call(ClientConnectionManagerImpl.java:861)
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl$2.call(ClientConnectionManagerImpl.java:857)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
```

**Comment by sancar** [comment]
It seems that test failed in maintenance branch because https://github.com/hazelcast/hazelcast/pull/12492 is not backported. I will prepare a backport.

**Comment by sancar** [comment]
Fixed by https://github.com/hazelcast/hazelcast/pull/12669
