### ISSUE TITLE
Client 3.8.4+ with near cache gets java.lang.UnsupportedOperationException when connected to 3.7.x cluster

### ISSUE THREAD

**Issue by alparslanavci** [hazelcast/hazelcast#11343]
When Java client 3.8.4+ is configured with near cache and connects to a 3.7.x cluster, it continously gets the following exception:

```
Caused by: java.lang.UnsupportedOperationException: Unrecognized client message received with type: 0x142
    at com.hazelcast.client.impl.protocol.task.NoSuchMessageTask.processMessage(NoSuchMessageTask.java:50)
    at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:123)
    at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:103)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
    at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
    at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)
    at ------ submitted from ------.(Unknown Source)
    at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:95)
    ... 17 more
```

The operations are working as expected, but this is exception is thrown continuously.

**Comment by ahmetmircik** [comment]
Further clarification, this is a new regression in version 3.8.4, 3.8.3 is working as expected, means no exception is thrown.
