### ISSUE TITLE
[query-cache] ClientQueryCacheListenerTest Failures

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#11386]
*shouldNotReceiveValue_whenIncludeValue_disabled*
```
java.lang.AssertionError: expected:<10> but was:<9>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.client.map.querycache.ClientQueryCacheListenerTest$2.run(ClientQueryCacheListenerTest.java:191)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1105)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1122)
	at com.hazelcast.client.map.querycache.ClientQueryCacheListenerTest.testIncludeValue(ClientQueryCacheListenerTest.java:188)
	at com.hazelcast.client.map.querycache.ClientQueryCacheListenerTest.shouldNotReceiveValue_whenIncludeValue_disabled(ClientQueryCacheListenerTest.java:169)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-freestyle/1036/testReport/junit/com.hazelcast.client.map.querycache/ClientQueryCacheListenerTest/shouldNotReceiveValue_whenIncludeValue_disabled/

*shouldReceiveValue_whenIncludeValue_enabled*
```
java.lang.AssertionError: expected:<10> but was:<9>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.client.map.querycache.ClientQueryCacheListenerTest$2.run(ClientQueryCacheListenerTest.java:191)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1105)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1122)
	at com.hazelcast.client.map.querycache.ClientQueryCacheListenerTest.testIncludeValue(ClientQueryCacheListenerTest.java:188)
	at com.hazelcast.client.map.querycache.ClientQueryCacheListenerTest.shouldReceiveValue_whenIncludeValue_enabled(ClientQueryCacheListenerTest.java:162)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-freestyle/1043/testReport/junit/com.hazelcast.client.map.querycache/ClientQueryCacheListenerTest/shouldReceiveValue_whenIncludeValue_enabled/

**Comment by hasancelik** [comment]
*shouldReceiveValue_whenIncludeValue_enabled*
```
java.lang.AssertionError: expected:<10> but was:<9>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.client.map.querycache.ClientQueryCacheListenerTest$2.run(ClientQueryCacheListenerTest.java:191)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1105)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1122)
	at com.hazelcast.client.map.querycache.ClientQueryCacheListenerTest.testIncludeValue(ClientQueryCacheListenerTest.java:188)
	at com.hazelcast.client.map.querycache.ClientQueryCacheListenerTest.shouldReceiveValue_whenIncludeValue_enabled(ClientQueryCacheListenerTest.java:162)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-freestyle/1065/testReport/junit/com.hazelcast.client.map.querycache/ClientQueryCacheListenerTest/shouldReceiveValue_whenIncludeValue_enabled/
