### ISSUE TITLE
Invocation_OnMemberLeftTest.whenMemberRestarts_withSameAddress

### ISSUE THREAD

**Issue by mdogan** [hazelcast/hazelcast#11401]
See https://github.com/hazelcast/hazelcast/pull/11390#issuecomment-330623531

```
java.util.concurrent.ExecutionException: com.hazelcast.core.HazelcastInstanceNotActiveException: Member [127.0.0.1]:5008 is currently passive! Operation: com.hazelcast.spi.impl.operationservice.impl.Invocation_OnMemberLeftTest$UnresponsiveTargetOperation{serviceName='null', identityHash=461898543, partitionId=-1, replicaIndex=0, callId=2, invocationTime=1505831222134 (2017-09-19 14:27:02.134), waitTimeout=-1, callTimeout=60000}
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.checkNodeState(OperationRunnerImpl.java:229)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:178)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:409)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:115)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:100)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:127)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:79)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:147)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation_OnMemberLeftTest.whenMemberRestarts(Invocation_OnMemberLeftTest.java:130)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation_OnMemberLeftTest.whenMemberRestarts_withSameAddress(Invocation_OnMemberLeftTest.java:86)
```

**Comment by mmedenjak** [comment]
Builder run : https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/10813/
