### ISSUE TITLE
TransactionalMap error

### ISSUE THREAD

**Issue by tvd12** [hazelcast/hazelcast#11400]
When I get an error at mapstore:

```java
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.mongodb.morphia.mapping.MappedClass.callLifecycleMethods(MappedClass.java:274)
	at org.mongodb.morphia.mapping.Mapper.fromDb(Mapper.java:295)
	at org.mongodb.morphia.mapping.Mapper.fromDBObject(Mapper.java:193)
	at org.mongodb.morphia.DatastoreImpl.findAndModify(DatastoreImpl.java:377)
	at com.tvd12.service.impl.AbstractNoHazelcastService.findAndModify(AbstractNoHazelcastService.java:92)
	at com.tvd12.service.impl.UserFreeTurnsStoreServiceImpl.findById(UserFreeTurnsStoreServiceImpl.java:29)
	at com.tvd12.service.impl.UserFreeTurnsStoreServiceImpl.findById(UserFreeTurnsStoreServiceImpl.java:12)
	at com.tvd12.mapstore.UserFreeTurnsMapstore.load(UserFreeTurnsMapstore.java:42)
	at com.tvd12.mapstore.UserFreeTurnsMapstore.load(UserFreeTurnsMapstore.java:20)
	at com.hazelcast.map.impl.MapStoreWrapper.load(MapStoreWrapper.java:152)
	at com.hazelcast.map.impl.mapstore.writethrough.WriteThroughStore.load(WriteThroughStore.java:72)
	at com.hazelcast.map.impl.mapstore.writethrough.WriteThroughStore.load(WriteThroughStore.java:28)
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.loadRecordOrNull(DefaultRecordStore.java:416)
	at com.hazelcast.map.impl.tx.TxnLockAndGetOperation.run(TxnLockAndGetOperation.java:59)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:186)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:382)
	at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.run(OperationServiceImpl.java:277)
	at com.hazelcast.spi.impl.operationparker.impl.OperationParkerImpl.unpark(OperationParkerImpl.java:150)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.afterRun(OperationRunnerImpl.java:291)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:188)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:122)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:102)
Caused by: java.lang.NullPointerException
	at com.tvd12.data.UserFreeTurns.postLoad(UserFreeTurns.java:149)
	... 26 more
```
I try again with same key and I get error:

```java
Caused by: com.hazelcast.transaction.TransactionTimedOutException: Transaction couldn't obtain lock for the key: dungtv
	at com.hazelcast.map.impl.tx.TransactionalMapProxySupport.lockAndGet(TransactionalMapProxySupport.java:285)
	at com.hazelcast.map.impl.tx.TransactionalMapProxySupport.getForUpdateInternal(TransactionalMapProxySupport.java:138)
	at com.hazelcast.map.impl.tx.TransactionalMapProxy.getForUpdate(TransactionalMapProxy.java:127)
	at com.tvd12.service.impl.AbstractHazelcastMapService.transactionalReturn(AbstractHazelcastMapService.java:69)
	at com.tvd12.service.impl.UserFreeTurnsServiceImpl.acquisiteFreeTurns(UserFreeTurnsServiceImpl.java:21)
	... 2 more
```

Here is my source code:

```java
Thread threads[] = new Thread[5];
		for(int i = 0 ; i < threads.length ; i++) {
			threads[i] = new Thread(
					() -> {
						try {
							service.acquisiteFreeTurns("dungtv", 0, "ss1");
						}
						catch(Exception e) {
							e.printStackTrace();
						}
					}
			);
		}
		
		for(int i = 0 ; i < threads.length ; i++) {
			threads[i].start();
		}
```

**Comment by mmedenjak** [comment]
Hi @tvd12 ! Which version of hazelcast are you using?

**Comment by tvd12** [comment]
@mmedenjak 3.8.1

**Comment by mmedenjak** [comment]
Thank you for submitting the issue. We will check it out. In the meantime, you can wrap your map loader in a `try-catch` block so the entry does not stay locked.

**Comment by tvd12** [comment]
I did:

```java
protected <R> R transactionalReturn(K key, Function<V, R> applier, V defValue) throws Exception {
    	TransactionOptions txOptions = new TransactionOptions()
                .setTimeout(3, TimeUnit.SECONDS)
                .setTransactionType(TransactionOptions.TransactionType.TWO_PHASE)
                .setDurability(1);
        TransactionContext txCxt = hzInstance.newTransactionContext(txOptions);
        txCxt.beginTransaction();
        try {
	    	TransactionalMap<K, V> map = txCxt.getMap(getMapName());
	    	V value = map.getForUpdate(key);
	    	if(value == null) {
	    		value = defValue;
	    	}
	    	R result = null;
	    	if(value != null) {
	    		result = applier.apply(value);
	    		map.set(key, value);
	    	}
	    	txCxt.commitTransaction();
	    	return result;
        }
        catch(Throwable e) {
        	txCxt.rollbackTransaction();
        	throw e;
        }
    }
```

**Comment by mmedenjak** [comment]
That's fine but as I see it, the exception was thrown in `com.tvd12.mapstore.UserFreeTurnsMapstore.load(UserFreeTurnsMapstore.java:20)`. You will probably need to wrap the code in the `UserFreeTurnsMapstore#load` method in a `try-catch` block to handle the case where the entry was not loaded due to an exception.

**Comment by tvd12** [comment]
okay, I know
