### ISSUE TITLE
java.lang.AssertionError: Only single namespace is allowed before V3.9

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#11414]
rollup test 3.8.6 3.9-SNAPSHOT, the member logs are full of

```
Sep 21, 2017 11:07:54 AM com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl
SEVERE: [10.0.0.95]:5701 [HZ] [3.9-SNAPSHOT] Failed to process packet: com.hazelcast.internal.partition.impl.PartitionPrimaryReplicaAntiEntropyTask@5a5df82a on hz._hzInstance_1_HZ.p
artition-operation.thread-3
java.lang.AssertionError: Only single namespace is allowed before V3.9: {}
    at com.hazelcast.internal.partition.impl.AbstractPartitionPrimaryReplicaAntiEntropyTask.invokePartitionBackupReplicaAntiEntropyOp(AbstractPartitionPrimaryReplicaAntiEntropyT
ask.java:98)
    at com.hazelcast.internal.partition.impl.PartitionPrimaryReplicaAntiEntropyTask.run(PartitionPrimaryReplicaAntiEntropyTask.java:46)
    at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:154)
    at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:125)
    at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:100)
```

from http://54.82.84.143/~jenkins/workspace/rollup-All_3.8.6_3.9-SNAPSHOT/3.8.6_3.9-SNAPSHOT/2017_09_21-13_53_09/async/output/HZ/HzMember1HZ/out.txt

**Comment by mdogan** [comment]
Failed run was using a stale snapshot. 

```
INFO: [10.0.0.95]:5701 [HZ] [3.9-SNAPSHOT] Hazelcast Enterprise 3.9-SNAPSHOT (20170920 - b6bcd1d, 311a5e75) starting at [10.0.0.95]:5701
```

This issue is already fixed by https://github.com/hazelcast/hazelcast/pull/10857
