### ISSUE TITLE
ClientQueryCacheMemoryLeakTest

### ISSUE THREAD

**Issue by Donnerbart** [hazelcast/hazelcast#11424]
**com.hazelcast.client.map.querycache.ClientQueryCacheMemoryLeakTest.no_query_cache_left_after_creating_and_destroying_same_map_concurrently**
```java
java.lang.AssertionError: expected:<0> but was:<8>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.client.map.querycache.ClientQueryCacheMemoryLeakTest.no_query_cache_left_after_creating_and_destroying_same_map_concurrently(ClientQueryCacheMemoryLeakTest.java:129)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/10851/testReport/com.hazelcast.client.map.querycache/ClientQueryCacheMemoryLeakTest/no_query_cache_left_after_creating_and_destroying_same_map_concurrently/

The assert should be this one:
```java
assertEquals(0, provider.getQueryCacheCount(mapName));
```

I tried to reproduce this locally, but the test didn't fail once in 3966 runs.

**Comment by ahmetmircik** [comment]
added eventual assertions, according to latest runs seems the test is passing: e5a343916cf17d97515d84ff9382eaf87993ca12

lets wait till the next failure.
