### ISSUE TITLE
com.hazelcast.core.HazelcastException wrapping more specific  MemberLeftException, java.io.IOException,  

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#11439]
3.9-SANPSHOT

we have the following exceptions, which we expected to be thrown.

com.hazelcast.core.OperationTimeoutException
com.hazelcast.core.MemberLeftException
com.hazelcast.spi.exception.TargetDisconnectedException
com.hazelcast.spi.exception.TargetNotMemberException
com.hazelcast.core.HazelcastInstanceNotActiveException
java.util.concurrent.ExecutionException
java.lang.IllegalStateException

it is difficult to handle the generic exception com.hazelcast.core.HazelcastException
and we should not thrown a generic exception wrapping an exception which we all ready throw
in its original format.

client is receiving a com.hazelcast.core.HazelcastException which wraps a more specific exception of com.hazelcast.core.MemberLeftException
 

```
com.hazelcast.core.HazelcastException: com.hazelcast.core.MemberLeftException: Member [10.0.0.42]:5701 - f84f23ef-f436-4dfa-8383-85b4e38f5794 has left cluster!
	at com.hazelcast.util.ExceptionUtil.peel(ExceptionUtil.java:83)
	at com.hazelcast.util.ExceptionUtil.peel(ExceptionUtil.java:56)
	at com.hazelcast.util.ExceptionUtil.peel(ExceptionUtil.java:52)
	at com.hazelcast.util.ExceptionUtil.rethrow(ExceptionUtil.java:105)
	at com.hazelcast.client.impl.protocol.task.map.MapPublisherCreateWithValueMessageTask.getQueryResults(MapPublisherCreateWithValueMessageTask.java:98)
	at com.hazelcast.client.impl.protocol.task.map.MapPublisherCreateWithValueMessageTask.call(MapPublisherCreateWithValueMessageTask.java:68)
	at com.hazelcast.client.impl.protocol.task.AbstractCallableMessageTask.processMessage(AbstractCallableMessageTask.java:35)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:123)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:103)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:96)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:33)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:155)
	at com.hazelcast.client.impl.querycache.subscriber.ClientInvokerWrapper.invoke(ClientInvokerWrapper.java:89)
	at com.hazelcast.client.impl.querycache.subscriber.ClientQueryCacheEndToEndConstructor.createPublishAccumulatorWithIncludeValue(ClientQueryCacheEndToEndConstructor.java:68)
	at com.hazelcast.client.impl.querycache.subscriber.ClientQueryCacheEndToEndConstructor.createPublisherAccumulator(ClientQueryCacheEndToEndConstructor.java:49)
	at com.hazelcast.map.impl.querycache.subscriber.AbstractQueryCacheEndToEndConstructor.createNew(AbstractQueryCacheEndToEndConstructor.java:90)
	at com.hazelcast.map.impl.querycache.subscriber.AbstractQueryCacheEndToEndConstructor.createNew(AbstractQueryCacheEndToEndConstructor.java:40)
	at com.hazelcast.map.impl.querycache.subscriber.QueryCacheEndToEndProvider.getOrCreateQueryCache(QueryCacheEndToEndProvider.java:55)
	at com.hazelcast.client.proxy.ClientMapProxy.createQueryCache(ClientMapProxy.java:1490)
	at com.hazelcast.client.proxy.ClientMapProxy.getQueryCacheInternal(ClientMapProxy.java:1483)
	at com.hazelcast.client.proxy.ClientMapProxy.getQueryCache(ClientMapProxy.java:1460)
```

and com.hazelcast.core.HazelcastException: java.io.IOException: Owner connection is not available!
```
com.hazelcast.core.HazelcastException: java.io.IOException: Owner connection is not available!
	at com.hazelcast.util.ExceptionUtil.peel(ExceptionUtil.java:94)
	at com.hazelcast.util.ExceptionUtil.peel(ExceptionUtil.java:56)
	at com.hazelcast.util.ExceptionUtil.peel(ExceptionUtil.java:52)
	at com.hazelcast.util.ExceptionUtil.rethrow(ExceptionUtil.java:105)
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.getOrConnect(ClientConnectionManagerImpl.java:390)
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.getOrConnect(ClientConnectionManagerImpl.java:326)
	at com.hazelcast.client.cache.impl.ClientCacheHelper.resolveCacheConfig(ClientCacheHelper.java:163)
	at com.hazelcast.client.cache.impl.ClientCacheHelper.createCacheConfig(ClientCacheHelper.java:124)
	at com.hazelcast.client.cache.impl.HazelcastClientCacheManager.createCacheConfig(HazelcastClientCacheManager.java:143)
	at com.hazelcast.cache.impl.AbstractHazelcastCacheManager.createCacheInternal(AbstractHazelcastCacheManager.java:121)
	at com.hazelcast.cache.impl.AbstractHazelcastCacheManager.createCache(AbstractHazelcastCacheManager.java:150)
	at com.hazelcast.cache.impl.AbstractHazelcastCacheManager.createCache(AbstractHazelcastCacheManager.java:67)
	at hzcmd.cache.CreateUseDestroyProgConfig.timeStep(CreateUseDestroyProgConfig.java:19)
	at remote.bench.marker.MetricsMarker.flatOut(MetricsMarker.java:53)
	at remote.bench.marker.MetricsMarker.bench(MetricsMarker.java:40)
	at remote.bench.BenchThread.call(BenchThread.java:38)
	at remote.bench.BenchThread.call(BenchThread.java:12)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:473)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Owner connection is not available!
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.getConnection(ClientConnectionManagerImpl.java:344)
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.getOrConnect(ClientConnectionManagerImpl.java:375)
	... 18 more
```

and com.hazelcast.core.HazelcastException: java.io.IOException: Packet not send to
```
com.hazelcast.core.HazelcastException: java.io.IOException: Packet not send to [10.0.0.14]:5701
	at com.hazelcast.util.ExceptionUtil.peel(ExceptionUtil.java:94)
	at com.hazelcast.util.ExceptionUtil.peel(ExceptionUtil.java:56)
	at com.hazelcast.util.ExceptionUtil.peel(ExceptionUtil.java:81)
	at com.hazelcast.util.ExceptionUtil.peel(ExceptionUtil.java:56)
	at com.hazelcast.util.ExceptionUtil.peel(ExceptionUtil.java:52)
	at com.hazelcast.util.ExceptionUtil.rethrow(ExceptionUtil.java:105)
	at com.hazelcast.client.proxy.txn.ClientTxnProxy.invoke(ClientTxnProxy.java:71)
	at com.hazelcast.client.proxy.txn.ClientTxnMapProxy.getForUpdate(ClientTxnMapProxy.java:90)
	at hzcmd.txn.map.validate.GetForUpdateSet.timeStep(GetForUpdateSet.java:52)
	at remote.bench.marker.MetricsMarker.flatOut(MetricsMarker.java:53)
	at remote.bench.marker.MetricsMarker.bench(MetricsMarker.java:40)
	at remote.bench.BenchThread.call(BenchThread.java:38)
	at remote.bench.BenchThread.call(BenchThread.java:12)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:473)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Packet not send to [10.0.0.14]:5701
	at com.hazelcast.client.spi.impl.ClientInvocationServiceImpl.send(ClientInvocationServiceImpl.java:127)
	at com.hazelcast.client.spi.impl.ClientSmartInvocationServiceImpl.invokeOnConnection(ClientSmartInvocationServiceImpl.java:79)
	at com.hazelcast.client.spi.impl.ClientInvocation.invokeOnSelection(ClientInvocation.java:147)
	at com.hazelcast.client.spi.impl.ClientInvocation.retry(ClientInvocation.java:177)
	at com.hazelcast.client.spi.impl.ClientInvocation.run(ClientInvocation.java:165)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:473)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
	at com.hazelcast.util.executor.LoggingScheduledExecutor$LoggingDelegatingFuture.run(LoggingScheduledExecutor.java:140)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:96)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:33)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:155)
	at com.hazelcast.client.proxy.txn.ClientTxnProxy.invoke(ClientTxnProxy.java:69)
	... 12 more
```

**Comment by Danny-Hazelcast** [comment]
```
com.hazelcast.core.HazelcastException: Could not obtain Connection!
	at com.hazelcast.client.proxy.txn.TransactionContextProxy.<init>(TransactionContextProxy.java:67)
	at com.hazelcast.client.spi.impl.ClientTransactionManagerServiceImpl.newTransactionContext(ClientTransactionManagerServiceImpl.java:60)
	at com.hazelcast.client.impl.HazelcastClientInstanceImpl.newTransactionContext(HazelcastClientInstanceImpl.java:582)
	at com.hazelcast.client.impl.HazelcastClientProxy.newTransactionContext(HazelcastClientProxy.java:185)
	at hzcmd.txn.set.Add.timeStep(Add.java:26)
	at remote.bench.marker.MetricsMarker.flatOut(MetricsMarker.java:53)
	at remote.bench.marker.MetricsMarker.bench(MetricsMarker.java:40)
	at remote.bench.BenchThread.call(BenchThread.java:38)
	at remote.bench.BenchThread.call(BenchThread.java:12)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:473)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.hazelcast.core.HazelcastException: java.io.IOException: Owner connection is not available!
	at com.hazelcast.util.ExceptionUtil.peel(ExceptionUtil.java:94)
	at com.hazelcast.util.ExceptionUtil.peel(ExceptionUtil.java:56)
	at com.hazelcast.util.ExceptionUtil.peel(ExceptionUtil.java:52)
	at com.hazelcast.util.ExceptionUtil.rethrow(ExceptionUtil.java:105)
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.getOrConnect(ClientConnectionManagerImpl.java:390)
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.getOrConnect(ClientConnectionManagerImpl.java:326)
	at com.hazelcast.client.spi.impl.ClientTransactionManagerServiceImpl.connect(ClientTransactionManagerServiceImpl.java:114)
	at com.hazelcast.client.proxy.txn.TransactionContextProxy.<init>(TransactionContextProxy.java:65)
	... 14 more
com.hazelcast.core.HazelcastException: Could not obtain Connection!Caused by: java.io.IOException: Owner connection is not available!

	at com.hazelcast.client.proxy.txn.TransactionContextProxy.<init>(TransactionContextProxy.java:67)	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.getConnection(ClientConnectionManagerImpl.java:344)

	at com.hazelcast.client.spi.impl.ClientTransactionManagerServiceImpl.newTransactionContext(ClientTransactionManagerServiceImpl.java:60)	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.getOrConnect(ClientConnectionManagerImpl.java:375)

	at com.hazelcast.client.impl.HazelcastClientInstanceImpl.newTransactionContext(HazelcastClientInstanceImpl.java:582)	... 17 more

	at com.hazelcast.client.impl.HazelcastClientProxy.newTransactionContext(HazelcastClientProxy.java:185)
	at hzcmd.txn.set.Add.timeStep(Add.java:26)
	at remote.bench.marker.MetricsMarker.flatOut(MetricsMarker.java:53)
	at remote.bench.marker.MetricsMarker.bench(MetricsMarker.java:40)
	at remote.bench.BenchThread.call(BenchThread.java:38)
	at remote.bench.BenchThread.call(BenchThread.java:12)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:473)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.hazelcast.core.HazelcastException: java.io.IOException: Owner connection is not available!
	at com.hazelcast.util.ExceptionUtil.peel(ExceptionUtil.java:94)
	at com.hazelcast.util.ExceptionUtil.peel(ExceptionUtil.java:56)
	at com.hazelcast.util.ExceptionUtil.peel(ExceptionUtil.java:52)
	at com.hazelcast.util.ExceptionUtil.rethrow(ExceptionUtil.java:105)
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.getOrConnect(ClientConnectionManagerImpl.java:390)
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.getOrConnect(ClientConnectionManagerImpl.java:326)
	at com.hazelcast.client.spi.impl.ClientTransactionManagerServiceImpl.connect(ClientTransactionManagerServiceImpl.java:114)
	at com.hazelcast.client.proxy.txn.TransactionContextProxy.<init>(TransactionContextProxy.java:65)
	... 14 more
Caused by: java.io.IOException: Owner connection is not available!
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.getConnection(ClientConnectionManagerImpl.java:344)
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.getOrConnect(ClientConnectionManagerImpl.java:375)
	... 17 more
```

**Comment by sancar** [comment]
@Danny-Hazelcast This is the same issue with https://github.com/hazelcast/hazelcast/issues/10773
I am closing this one to follow the issue from one place.

**Comment by sancar** [comment]
@Danny-Hazelcast , Since there are different scenarios. I am opening a task list here. I will sign the one already solved or planned to solved in a different issue as done. We can close this issue once all of them marked as done. 
 

- [ ] Member left exception is already discussed here . Change is planned in 4.0 https://github.com/hazelcast/hazelcast/issues/10763

- [ ] ClientCacheHelper.resolveCacheConfig sending (com.hazelcast.core.HazelcastException: java.io.IOException ) seems like a problem, i will investigate what we can do about it. 

- [ ] ClientTxnProxy.invoke sending  (com.hazelcast.core.HazelcastException: java.io.IOException )  handled in https://github.com/hazelcast/hazelcast/issues/10773

- [ ] com.hazelcast.core.HazelcastException: Could not obtain Connection!
at com.hazelcast.client.proxy.txn.TransactionContextProxy.<init>
I will investigate this. A transaction exception seems more appropriate here.

**Comment by sancar** [comment]
Postponing this issue to 3.10, as we will address the HazelcastException more extensively.

**Comment by Danny-Hazelcast** [comment]
ok thanks sancar

**Comment by sancar** [comment]
@Danny-Hazelcast I resolved the list item in the list (https://github.com/hazelcast/hazelcast/issues/11439#issuecomment-332815871) in following pr 
https://github.com/hazelcast/hazelcast/pull/12172

Closing this one. 
Taking more extensive action HazelcastException does not seem to happen anytime soon. If you find any similar usage continue to report them as usual. We will tackle them one by one.
