### ISSUE TITLE
[cache] CacheBasicClientTest.cacheManagerOfCache_cannotBeOverwrittenConcurrently

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#11432]
```
java.lang.AssertionError: Unexpected exception thrown: A cache named the-cache already exists.
	at com.hazelcast.cache.CacheBasicAbstractTest.cacheManagerOfCache_cannotBeOverwrittenConcurrently(CacheBasicAbstractTest.java:949)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.lang.Thread.run(Thread.java:785)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.8/com.hazelcast$hazelcast-client/725/testReport/junit/com.hazelcast.client.cache/CacheBasicClientTest/cacheManagerOfCache_cannotBeOverwrittenConcurrently/

**Comment by vbekiaris** [comment]
When `AbstractHazelcastCacheManager.createCacheConfig` returns `null` it is not possible to distinguish whether this return value is due to:
- `CacheConfig` was not already registered in `AbstractCacheService` configs
- `createAlsoOnOthers==true` (as is the case when invoked from `AbstractHazelcastCacheManager.createCacheInternal`) and there are remote members to which the `CacheConfig` is sent for local registration --> the `CacheCreateConfigOperation` returns always `null`, regardless of whether the `CacheConfig` was already registered.

The cache creation process took into account this response to follow different code paths, considering that the `CacheConfig` was not already registered (first case above). This led to manifestation of this issue due to the client-side test being executed on a single member, while the member-side test was always executed on several members --> it always follows the [`currentCacheConfig==null` branch](https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/cache/impl/AbstractHazelcastCacheManager.java#L124).
