### ISSUE TITLE
IndeterminateOperationStateExceptionTest.targetInvocation_shouldFailWithMemberLeftException_onTargetMemberLeave

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#11431]
```
ava.lang.Exception: Unexpected exception, expected<com.hazelcast.core.MemberLeftException> but was<java.util.concurrent.ExecutionException>
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.checkNodeState(OperationRunnerImpl.java:229)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:178)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:409)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:115)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:100)
	at ------ submitted from ------.(Unknown Source)
	at java.lang.Thread.getStackTrace(Thread.java:1117)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:127)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:79)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:183)
	at com.hazelcast.partition.IndeterminateOperationStateExceptionTest.targetInvocation_shouldFailWithMemberLeftException_onTargetMemberLeave(IndeterminateOperationStateExceptionTest.java:159)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.8/com.hazelcast$hazelcast/723/testReport/junit/com.hazelcast.partition/IndeterminateOperationStateExceptionTest/targetInvocation_shouldFailWithMemberLeftException_onTargetMemberLeave/

**Comment by mdogan** [comment]
Already fixed by https://github.com/hazelcast/hazelcast/pull/11402
