### ISSUE TITLE
HyperLogLogImplTest.testEstimateErrorRateForBigCardinalities

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#11433]
```
java.lang.AssertionError: For P=11: Expected max error=6.0%. Actual error=6.15%.
	at org.junit.Assert.fail(Assert.java:88)
	at com.hazelcast.cardinality.impl.hyperloglog.impl.HyperLogLogImplTest.testEstimateErrorRateForBigCardinalities(HyperLogLogImplTest.java:126)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/1479/testReport/junit/com.hazelcast.cardinality.impl.hyperloglog.impl/HyperLogLogImplTest/testEstimateErrorRateForBigCardinalities_precision_11_/

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/1481/testReport/junit/com.hazelcast.cardinality.impl.hyperloglog.impl/HyperLogLogImplTest/testEstimateErrorRateForBigCardinalities_precision_11_/

**Comment by hasancelik** [comment]
*testEstimateErrorRateForBigCardinalities*
```
java.lang.AssertionError: For P=14: Expected max error=4.0%. Actual error=4.33%.
	at org.junit.Assert.fail(Assert.java:88)
	at com.hazelcast.cardinality.impl.hyperloglog.impl.HyperLogLogImplTest.testEstimateErrorRateForBigCardinalities(HyperLogLogImplTest.java:129)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/1620/#showFailuresLink

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/1621/#showFailuresLink

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/1622/#showFailuresLink

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/1623/#showFailuresLink

**Comment by Donnerbart** [comment]
These are the highest failures from the test runs:
> For P=15: Expected max error=4.0%. Actual error=7.49%.
> For P=16: Expected max error=3.0%. Actual error=12.39%.

So another two precisions fail now. Is this still reasonable or does it smell like a bug?

**Comment by tkountis** [comment]
Ill have a closer look at the implementation, the higher precision with higher error rate is not looking right to me. However, this is a random set of data, so this might as well be expected. Maybe it's better if we rely on a specific data-set.

**Comment by Holmistr** [comment]
Hey guys, I have added an Ignore to this test, since it's constantly failing our nightly builds. This issue is 100% reproducible, so there is no reason in having it fail the build all the time. Here is the PR with the Ignore (https://github.com/hazelcast/hazelcast/pull/12465), let's not forget to enable the test after the issue is fixed @tkountis .

**Comment by Holmistr** [comment]
*master* (commit c72162c7af92f5685552a8a4ff6144b67ca9637b)

Reopening as it failed on Sonar build: https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-sonar/96/testReport/junit/com.hazelcast.cardinality.impl.hyperloglog.impl/HyperLogLogImplTest/testEstimateErrorRateForBigCardinalities_precision_11__errorRange_6_5_/

Parameters: testEstimateErrorRateForBigCardinalities[precision:11, errorRange:6.5]

Stacktrace:
```
java.lang.AssertionError: For P=11: Expected max error=9.0%. Actual error=9.6%.
	at org.junit.Assert.fail(Assert.java:88)
	at com.hazelcast.cardinality.impl.hyperloglog.impl.HyperLogLogImplTest.testEstimateErrorRateForBigCardinalities(HyperLogLogImplTest.java:128)
```

**Comment by olukas** [comment]
_master_ (commit 48058420325e5fa88d4e432cf01ae22c40bded98)

Reopening as it failed on Sonar build: https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-sonar/294/testReport/junit/com.hazelcast.cardinality.impl.hyperloglog.impl/HyperLogLogImplTest/testEstimateErrorRateForBigCardinalities_precision_11__errorRange_7_/

Stacktrace:
```
java.lang.AssertionError: For P=11: Expected max error=10.0%. Actual error=10.28%.
	at org.junit.Assert.fail(Assert.java:88)
	at com.hazelcast.cardinality.impl.hyperloglog.impl.HyperLogLogImplTest.testEstimateErrorRateForBigCardinalities(HyperLogLogImplTest.java:128)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by tkountis** [comment]
A bit skeptical to alter error acceptance rate for this single failure. The difference is small, and the test is heavily affected by the randomness of the data. I am leaning towards letting this one pass. If it happens again, on the *same* precision P=11 I will increase the error range by 1%.

**Comment by Holmistr** [comment]
@tkountis Ideas for future - couldn't we fixate the test data set? If we introduce randomness in the test, it's like asking for random failures (see the "random" parts in the statement :D )

**Comment by tkountis** [comment]
Yes, we could and I have thought of putting an end on this open bleeding. But, (there is always a but) a fixed data set on this kind of data structure could hide a problem. In other words, if we break sth in the implementation, this is the only kind of test which will reliably fail from time to time. This test was the reason we found a good bug in the implementation a few months ago. 
Having said that, I am considering, relaxing it a bit, and maybe only stress test the highest precision settings,  i.e. `12 > P < 17`
