### ISSUE TITLE
NullPointerException runOffloaded HDEntryOperation.java 108

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#11453]
version
```
INFO: [10.0.0.205]:5701 [HZ] [3.9-SNAPSHOT] Hazelcast Enterprise 3.9-SNAPSHOT (20170925 - 1678248, c2eac8a) starting at [10.0.0.205]:5701
```

/disk1/jenkins/workspace/freeze-all/3.9-SNAPSHOT/2017_09_25-20_32_09/processor/off-load/execute-on

HzMember1HZ
```
java.lang.NullPointerException
	at com.hazelcast.map.impl.operation.HDEntryOperation.runOffloaded(HDEntryOperation.java:108)
	at com.hazelcast.map.impl.operation.HDEntryOperation.runInternal(HDEntryOperation.java:93)
	at com.hazelcast.map.impl.operation.HDMapOperation.run(HDMapOperation.java:72)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:194)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:120)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:100)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:127)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:79)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:155)
	at com.hazelcast.map.impl.proxy.MapProxySupport.executeOnKeyInternal(MapProxySupport.java:1066)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.executeOnKeyInternal(MapProxyImpl.java:110)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.executeOnKey(MapProxyImpl.java:708)
	at hzcmd.map.processor.person.execute.ExecuteOnKeyPersonInc.timeStep(ExecuteOnKeyPersonInc.java:12)
```

**Comment by pveentjer** [comment]
```
private void runOffloaded() {
        if (!(entryProcessor instanceof Offloadable)) {
            throw new HazelcastException("EntryProcessor is expected to implement Offloadable for this operation");
        }
        if (readOnly && entryProcessor.getBackupProcessor() != null) {
            throw new HazelcastException("EntryProcessor.getBackupProcessor() should return null if ReadOnly implemented");
        }

        Object value = recordStore.get(dataKey, false);
        value = new HeapData(((Data) value).toByteArray());<------

        String executorName = ((Offloadable) entryProcessor).getExecutorName();
        executorName = executorName.equals(Offloadable.OFFLOADABLE_EXECUTOR) ? OFFLOADABLE_EXECUTOR : executorName;

        if (readOnly) {
            runOffloadedReadOnlyEntryProcessor(value, executorName);
        } else {
            runOffloadedModifyingEntryProcessor(value, executorName);
        }
    }
```

It looks like the value from the recordStore for the key was not found. @Danny-Hazelcast are you sure you are not executing an entry processor on a non existing key? Or do you have e.g. expiration enabled?

**Comment by jerrinot** [comment]
it appears to be connected to https://github.com/hazelcast/hazelcast/issues/11452
it both cases the `valueData` is null.

**Comment by ahmetmircik** [comment]
Getting null is legal from this line   `Object value = recordStore.get(dataKey, false);`. I will prepare a fix candidate.

**Comment by jerrinot** [comment]
great. will it fix also #11452 ?

**Comment by ahmetmircik** [comment]
@jerrinot i need to understand how the failure occurred in #11452, at first glance it seemed a different defect.

**Comment by mmedenjak** [comment]
It's strange how the EP was executed on a null entry in the first place.

This was the EP being executed:
https://github.com/hazelcast/hzCmd-bench/blob/cca6ce201f4d38c2b870d286e041a0dafe3c639a/src/main/java/hzcmd/map/processor/person/execute/ExecuteOnKeyPersonInc.java

And the params:
```
_processor_off-load_execute-on_inc_mapBak1HD@class=hzcmd.map.processor.person.execute.ExecuteOnKeyPersonInc
_processor_off-load_execute-on_inc_mapBak1HD@offLoadable=true
_processor_off-load_execute-on_inc_mapBak1HD@threads=8
_processor_off-load_execute-on_inc_mapBak1HD@keyDomain=10000
_processor_off-load_execute-on_inc_mapBak1HD@name=mapBak1HD_processor_off-load_execute-on

_processor_off-load_execute-on_inc_mapBak1@class=hzcmd.map.processor.person.execute.ExecuteOnKeyPersonInc
_processor_off-load_execute-on_inc_mapBak1@offLoadable=true
_processor_off-load_execute-on_inc_mapBak1@threads=8
_processor_off-load_execute-on_inc_mapBak1@keyDomain=10000
_processor_off-load_execute-on_inc_mapBak1@name=mapBak1_processor_off-load_execute-on
```
So basically it runs on a random key [0-10000] both on HD and non-HD map. The map should be filled with the keys:
https://github.com/hazelcast/hzCmd-bench/blob/1c89d95ad8f79a37738505b34518b999b30df2b5/src/main/java/hzcmd/map/member/base/Loader.java#L15-L30

```
_processor_off-load_execute-on_load_mapBak1HD@class=hzcmd.map.member.LoadPersonRandom
_processor_off-load_execute-on_load_mapBak1HD@driver=Member
_processor_off-load_execute-on_load_mapBak1HD@keyDomain=10000
_processor_off-load_execute-on_load_mapBak1HD@name=mapBak1HD_processor_off-load_execute-on

_processor_off-load_execute-on_load_mapBak1@class=hzcmd.map.member.LoadPersonRandom
_processor_off-load_execute-on_load_mapBak1@driver=Member
_processor_off-load_execute-on_load_mapBak1@keyDomain=10000
_processor_off-load_execute-on_load_mapBak1@name=mapBak1_processor_off-load_execute-on
```
