### ISSUE TITLE
NullPointerException PartitionWideEntryWithPredicateOperation CachedQueryEntry.java:105

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#11452]
version 
```
INFO: [10.0.0.205]:5701 [HZ] [3.9-SNAPSHOT] Hazelcast Enterprise 3.9-SNAPSHOT (20170925 - 1678248, c2eac8a) starting at [10.0.0.205]:5701
```

/disk1/jenkins/workspace/freeze-all/3.9-SNAPSHOT/2017_09_25-20_32_09/processor/off-load/execute-on-predicate
HzMember1HZ/out.txt

```
Sep 26, 2017 10:02:03 AM com.hazelcast.map.impl.operation.PartitionWideEntryWithPredicateOperation
SEVERE: [10.0.0.205]:5701 [HZ] [3.9-SNAPSHOT] null
java.lang.NullPointerException
	at com.hazelcast.query.impl.CachedQueryEntry.getTargetObject(CachedQueryEntry.java:105)
	at com.hazelcast.query.impl.QueryableEntry.extractAttributeValue(QueryableEntry.java:81)
	at com.hazelcast.query.impl.QueryableEntry.getAttributeValue(QueryableEntry.java:48)
	at com.hazelcast.query.impl.predicates.AbstractPredicate.readAttributeValue(AbstractPredicate.java:132)
	at com.hazelcast.query.impl.predicates.AbstractPredicate.apply(AbstractPredicate.java:57)
	at com.hazelcast.query.impl.predicates.AndPredicate.apply(AndPredicate.java:129)
	at com.hazelcast.query.SqlPredicate.apply(SqlPredicate.java:74)
	at com.hazelcast.map.impl.operation.EntryOperator.outOfPredicateScope(EntryOperator.java:269)
	at com.hazelcast.map.impl.operation.EntryOperator.operateOnKeyValueInternal(EntryOperator.java:183)
	at com.hazelcast.map.impl.operation.EntryOperator.operateOnKey(EntryOperator.java:172)
	at com.hazelcast.map.impl.operation.PartitionWideEntryOperation.run(PartitionWideEntryOperation.java:84)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:194)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:120)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:100)

```

**Comment by Danny-Hazelcast** [comment]
```
java.lang.NullPointerException
	at com.hazelcast.query.impl.CachedQueryEntry.getTargetObject(CachedQueryEntry.java:105)
	at com.hazelcast.query.impl.QueryableEntry.extractAttributeValue(QueryableEntry.java:81)
	at com.hazelcast.query.impl.QueryableEntry.getAttributeValue(QueryableEntry.java:48)
	at com.hazelcast.query.impl.predicates.AbstractPredicate.readAttributeValue(AbstractPredicate.java:132)
	at com.hazelcast.query.impl.predicates.AbstractPredicate.apply(AbstractPredicate.java:57)
	at com.hazelcast.query.impl.predicates.AndPredicate.apply(AndPredicate.java:129)
	at com.hazelcast.query.SqlPredicate.apply(SqlPredicate.java:74)
	at com.hazelcast.map.impl.operation.EntryOperator.outOfPredicateScope(EntryOperator.java:269)
	at com.hazelcast.map.impl.operation.EntryOperator.operateOnKeyValueInternal(EntryOperator.java:183)
	at com.hazelcast.map.impl.operation.EntryOperator.operateOnKey(EntryOperator.java:172)
	at com.hazelcast.map.impl.operation.PartitionWideEntryOperation.run(PartitionWideEntryOperation.java:84)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:194)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:120)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:100)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:127)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:79)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:147)
	at com.hazelcast.spi.impl.operationservice.impl.InvokeOnPartitions.retryFailedPartitions(InvokeOnPartitions.java:144)
	at com.hazelcast.spi.impl.operationservice.impl.InvokeOnPartitions.invoke(InvokeOnPartitions.java:74)
	at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.invokeOnAllPartitions(OperationServiceImpl.java:380)
	at com.hazelcast.map.impl.proxy.MapProxySupport.executeOnEntriesInternal(MapProxySupport.java:1133)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.executeOnEntriesInternal(MapProxyImpl.java:110)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.executeOnEntries(MapProxyImpl.java:751)
	at hzcmd.map.processor.person.execute.ExecuteOnPredicatePersonInc.timeStep(ExecuteOnPredicatePersonInc.java:18)

```

**Comment by ahmetmircik** [comment]
A possible scenario that results with NPE can be like this:
1. split brain happened
2. cluster merge started
3. cluster merge reset record-store data on joining side
4. during all this healing process we have a long running partition operation and it is still running during cluster-merge
5. and it sees some values inside recordstore null as a result of record-store reset at step 3.

According the logs of above run, NPE is happening on joining node after [LocalMemberResetException](https://github.com/hazelcast/hazelcast/blob/7738c39e55148954abc92e228251b76ffe2b7f12/hazelcast/src/main/java/com/hazelcast/core/LocalMemberResetException.java#L23).

**Comment by Danny-Hazelcast** [comment]
http://54.82.84.143/~jenkins/workspace/freeze-all/3.9-SNAPSHOT/2017_10_07-06_58_58/processor/off-load/execute-on-predicate/output/HZ/
and 
http://54.82.84.143/~jenkins/workspace/freeze-all/3.9-SNAPSHOT/2017_10_07-06_58_58/processor/regular/execute-on-predicate/output/HZ/

have `com.hazelcast.query.impl.CachedQueryEntry.getTargetObject(CachedQueryEntry.java:105)`

**Comment by Danny-Hazelcast** [comment]
and
http://54.82.84.143/~jenkins/workspace/freeze-all/3.9-SNAPSHOT/2017_10_07-06_58_58/map/remove-predicate/output/HZ

and

http://54.82.84.143/~jenkins/workspace/freeze-all/3.9-SNAPSHOT/2017_10_07-06_58_58/sql/put-remove-all/output/HZ/
