### ISSUE TITLE
TxnMapNearCacheBasicTest

### ISSUE THREAD

**Issue by Donnerbart** [hazelcast/hazelcast#11456]
**com.hazelcast.map.impl.tx.TxnMapNearCacheBasicTest.whenGetIsUsed_thenNearCacheShouldBePopulated[format:OBJECT serializeKeys:true]**
```java
java.lang.AssertionError: Near Cache size didn't reach the desired value (1000 vs. 575) (NearCacheStatsImpl{ownedEntryCount=575, ownedEntryMemoryCost=0, creationTime=1506414197798, hits=575, misses=2425, ratio=23.7%, evictions=0, expirations=0, lastPersistenceTime=0, persistenceCount=0, lastPersistenceDuration=0, lastPersistenceWrittenBytes=0, lastPersistenceKeyCount=0, lastPersistenceFailure=''}) expected:<1000> but was:<575>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils.assertNearCacheSize(NearCacheTestUtils.java:428)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils$4.run(NearCacheTestUtils.java:448)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1129)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1146)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils.assertNearCacheSizeEventually(NearCacheTestUtils.java:445)
	at com.hazelcast.map.impl.tx.TxnMapNearCacheBasicTest.whenGetIsUsed_thenNearCacheShouldBePopulated(TxnMapNearCacheBasicTest.java:180)
```
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-freestyle/1081/testReport/junit/com.hazelcast.map.impl.tx/TxnMapNearCacheBasicTest/whenGetIsUsed_thenNearCacheShouldBePopulated_format_OBJECT_serializeKeys_true_/

The `TxnMapNearCacheBasicTest` is a bit special, since the `TransactionalMap` only reads from the Near Cache, but doesn't populate it. So some of the unified Near Cache tests don't work out-of-the-box. So the `TxnMapNearCacheBasicTest` overwrites the `whenGetIsUsed_thenNearCacheShouldBePopulated(DataStructureMethods method)` to populate the Near Cache via a the normal `IMap.get()` method.

What totally puzzles me is, that the Near Cache is filled, since the first assertion passes. But on the second assertion it fails.
```java
// use IMap.get() which populates the Near Cache (but also increases the misses again)
IMap<Integer, String> map = context.nearCacheInstance.getMap(DEFAULT_NEAR_CACHE_NAME);
for (int i = 0; i < DEFAULT_RECORD_COUNT; i++) {
    map.get(i);
}
assertNearCacheSizeEventually(context, DEFAULT_RECORD_COUNT); // <---------- passed
assertNearCacheStats(context, DEFAULT_RECORD_COUNT, 0, DEFAULT_RECORD_COUNT * 2);

// use TransactionalMap.get() to make some hits
populateNearCache(context, method);
assertNearCacheSizeEventually(context, DEFAULT_RECORD_COUNT);  // <---------- fails
assertNearCacheStats(context, DEFAULT_RECORD_COUNT, DEFAULT_RECORD_COUNT, DEFAULT_RECORD_COUNT * 2);
```
The Near Cache size of 575 vs. 1000 looks like we lost the entries of a whole node. But I cannot figure out what has happened.

**Comment by Donnerbart** [comment]
I just had this test running locally while reviewing other PRs and almost forgot about it. After 1h 42m and 3873 executions I could reproduce the failure o_O
https://gist.githubusercontent.com/Donnerbart/0f4df3f68eb40159ecdc30f7eb64e9e0/raw/5634f83b6533e3a85938383e8ad2b478c174df68/whenGetIsUsed_thenNearCacheShouldBePopulated.log

I'm not 100% sure, but are we losing a cluster member here?

**Comment by mmedenjak** [comment]
Had another PR builder failure. Note - the environment has been very unstable these days so maybe it's also caused by some split brain or slow environment.

https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/11040

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: Near Cache size didn't reach the desired value (1000 vs. 575) (NearCacheStatsImpl{ownedEntryCount=575, ownedEntryMemoryCost=87905, creationTime=1507134955457, hits=575, misses=2425, ratio=23.7%, evictions=0, expirations=0, lastPersistenceTime=0, persistenceCount=0, lastPersistenceDuration=0, lastPersistenceWrittenBytes=0, lastPersistenceKeyCount=0, lastPersistenceFailure=''}) expected:<1000> but was:<575>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils.assertNearCacheSize(NearCacheTestUtils.java:428)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils$4.run(NearCacheTestUtils.java:448)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1129)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1146)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils.assertNearCacheSizeEventually(NearCacheTestUtils.java:445)
	at com.hazelcast.map.impl.tx.TxnMapNearCacheBasicTest.whenGetIsUsed_thenNearCacheShouldBePopulated(TxnMapNearCacheBasicTest.java:180)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-freestyle/1132/testReport/junit/com.hazelcast.map.impl.tx/TxnMapNearCacheBasicTest/whenGetIsUsed_thenNearCacheShouldBePopulated_format_BINARY_serializeKeys_true_/

**Comment by ahmetmircik** [comment]
added some more checks to txn test related to cluster-size and backing imap size, expecting more insights from those checks, lets wait for the next failure. https://github.com/hazelcast/hazelcast/commit/9f18fc4f76ca4b1493785296d536dea0bee33666

**Comment by hasancelik** [comment]
*whenGetIsUsed_thenNearCacheShouldBePopulated[format:BINARY serializeKeys:true]*
```
java.lang.AssertionError: Near Cache size didn't reach the desired value (1000 vs. 780) (NearCacheStatsImpl{ownedEntryCount=780, ownedEntryMemoryCost=119250, creationTime=1509928176446, hits=780, misses=2220, ratio=35.1%, evictions=0, expirations=0, lastPersistenceTime=0, persistenceCount=0, lastPersistenceDuration=0, lastPersistenceWrittenBytes=0, lastPersistenceKeyCount=0, lastPersistenceFailure=''}) expected:<1000> but was:<780>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils.assertNearCacheSize(NearCacheTestUtils.java:428)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils$4.run(NearCacheTestUtils.java:448)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1133)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1150)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils.assertNearCacheSizeEventually(NearCacheTestUtils.java:445)
	at com.hazelcast.map.impl.tx.TxnMapNearCacheBasicTest.whenGetIsUsed_thenNearCacheShouldBePopulated(TxnMapNearCacheBasicTest.java:194)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.7-freestyle/28/testReport/junit/com.hazelcast.map.impl.tx/TxnMapNearCacheBasicTest/whenGetIsUsed_thenNearCacheShouldBePopulated_format_BINARY_serializeKeys_true_/

**Comment by hasancelik** [comment]
*whenGetIsUsed_thenNearCacheShouldBePopulated*
```
java.lang.AssertionError: Near Cache size didn't reach the desired value (1000 vs. 575) (NearCacheStatsImpl{ownedEntryCount=575, ownedEntryMemoryCost=0, creationTime=1510285244144, hits=575, misses=2425, ratio=23.7%, evictions=0, expirations=0, lastPersistenceTime=0, persistenceCount=0, lastPersistenceDuration=0, lastPersistenceWrittenBytes=0, lastPersistenceKeyCount=0, lastPersistenceFailure=''}) expected:<1000> but was:<575>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils.assertNearCacheSize(NearCacheTestUtils.java:428)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils$4.run(NearCacheTestUtils.java:448)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1133)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1150)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils.assertNearCacheSizeEventually(NearCacheTestUtils.java:445)
	at com.hazelcast.map.impl.tx.TxnMapNearCacheBasicTest.whenGetIsUsed_thenNearCacheShouldBePopulated(TxnMapNearCacheBasicTest.java:194)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.8/com.hazelcast$hazelcast/774/testReport/junit/com.hazelcast.map.impl.tx/TxnMapNearCacheBasicTest/whenGetIsUsed_thenNearCacheShouldBePopulated_format_OBJECT_serializeKeys_false_/

**Comment by hasancelik** [comment]
*whenGetIsUsed_thenNearCacheShouldBePopulated*
```
java.lang.AssertionError: Near Cache size didn't reach the desired value (1000 vs. 780) (NearCacheStatsImpl{ownedEntryCount=780, ownedEntryMemoryCost=0, creationTime=1510532898187, hits=780, misses=2220, ratio=35.1%, evictions=0, expirations=0, lastPersistenceTime=0, persistenceCount=0, lastPersistenceDuration=0, lastPersistenceWrittenBytes=0, lastPersistenceKeyCount=0, lastPersistenceFailure=''}) expected:<1000> but was:<780>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils.assertNearCacheSize(NearCacheTestUtils.java:428)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils$4.run(NearCacheTestUtils.java:448)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1133)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1150)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils.assertNearCacheSizeEventually(NearCacheTestUtils.java:445)
	at com.hazelcast.map.impl.tx.TxnMapNearCacheBasicTest.whenGetIsUsed_thenNearCacheShouldBePopulated(TxnMapNearCacheBasicTest.java:194)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-ZuluJDK7-freestyle/35/testReport/junit/com.hazelcast.map.impl.tx/TxnMapNearCacheBasicTest/whenGetIsUsed_thenNearCacheShouldBePopulated_format_OBJECT_serializeKeys_true_/

**Comment by hasancelik** [comment]
*whenGetIsUsed_thenNearCacheShouldBePopulated*
```
java.lang.AssertionError: Near Cache size didn't reach the desired value (1000 vs. 780) (NearCacheStatsImpl{ownedEntryCount=780, ownedEntryMemoryCost=119250, creationTime=1511142358992, hits=780, misses=2220, ratio=35.1%, evictions=0, expirations=0, lastPersistenceTime=0, persistenceCount=0, lastPersistenceDuration=0, lastPersistenceWrittenBytes=0, lastPersistenceKeyCount=0, lastPersistenceFailure=''}) expected:<1000> but was:<780>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils.assertNearCacheSize(NearCacheTestUtils.java:428)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils$4.run(NearCacheTestUtils.java:448)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1133)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1150)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils.assertNearCacheSizeEventually(NearCacheTestUtils.java:445)
	at com.hazelcast.map.impl.tx.TxnMapNearCacheBasicTest.whenGetIsUsed_thenNearCacheShouldBePopulated(TxnMapNearCacheBasicTest.java:194)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK1.6-freestyle/294/testReport/junit/com.hazelcast.map.impl.tx/TxnMapNearCacheBasicTest/whenGetIsUsed_thenNearCacheShouldBePopulated_format_BINARY_serializeKeys_true_/

**Comment by hasancelik** [comment]
*maintenance*
**whenGetIsUsed_thenNearCacheShouldBePopulated**
```
java.lang.AssertionError: Near Cache size didn't reach the desired value (1000 vs. 575) (NearCacheStatsImpl{ownedEntryCount=575, ownedEntryMemoryCost=0, creationTime=1511594676544, hits=575, misses=2425, ratio=23.7%, evictions=0, expirations=0, lastPersistenceTime=0, persistenceCount=0, lastPersistenceDuration=0, lastPersistenceWrittenBytes=0, lastPersistenceKeyCount=0, lastPersistenceFailure=''}) expected:<1000> but was:<575>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils.assertNearCacheSize(NearCacheTestUtils.java:428)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils$4.run(NearCacheTestUtils.java:448)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1129)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1146)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils.assertNearCacheSizeEventually(NearCacheTestUtils.java:445)
	at com.hazelcast.map.impl.tx.TxnMapNearCacheBasicTest.whenGetIsUsed_thenNearCacheShouldBePopulated(TxnMapNearCacheBasicTest.java:194)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-ZuluJDK7-freestyle/16/testReport/junit/com.hazelcast.map.impl.tx/TxnMapNearCacheBasicTest/whenGetIsUsed_thenNearCacheShouldBePopulated_format_OBJECT_serializeKeys_true_/

**Comment by hasancelik** [comment]
*master*
**whenGetIsUsed_thenNearCacheShouldBePopulated**
```
java.lang.AssertionError: Near Cache size didn't reach the desired value (1000 vs. 780) (NearCacheStatsImpl{ownedEntryCount=780, ownedEntryMemoryCost=0, creationTime=1511828091900, hits=780, misses=2220, ratio=35.1%, evictions=0, expirations=0, lastPersistenceTime=0, persistenceCount=0, lastPersistenceDuration=0, lastPersistenceWrittenBytes=0, lastPersistenceKeyCount=0, lastPersistenceFailure=''}) expected:<1000> but was:<780>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils.assertNearCacheSize(NearCacheTestUtils.java:428)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils$4.run(NearCacheTestUtils.java:448)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1133)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1150)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils.assertNearCacheSizeEventually(NearCacheTestUtils.java:445)
	at com.hazelcast.map.impl.tx.TxnMapNearCacheBasicTest.whenGetIsUsed_thenNearCacheShouldBePopulated(TxnMapNearCacheBasicTest.java:194)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-ZuluJDK8/com.hazelcast$hazelcast/773/testReport/junit/com.hazelcast.map.impl.tx/TxnMapNearCacheBasicTest/whenGetIsUsed_thenNearCacheShouldBePopulated_format_OBJECT_serializeKeys_false_/

**Comment by Donnerbart** [comment]
Suppressed via https://github.com/hazelcast/hazelcast/commit/093e77416ec5673164c7ea355acad8ccf672328f

**Comment by hasancelik** [comment]
*maintenance*
```
java.lang.AssertionError: Near Cache size didn't reach the desired value (1000 vs. 780) (NearCacheStatsImpl{ownedEntryCount=780, ownedEntryMemoryCost=91170, creationTime=1514975010282, hits=780, misses=2220, ratio=35.1%, evictions=0, expirations=0, lastPersistenceTime=0, persistenceCount=0, lastPersistenceDuration=0, lastPersistenceWrittenBytes=0, lastPersistenceKeyCount=0, lastPersistenceFailure=''}) expected:<1000> but was:<780>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils.assertNearCacheSize(NearCacheTestUtils.java:428)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils$4.run(NearCacheTestUtils.java:448)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1129)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1146)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils.assertNearCacheSizeEventually(NearCacheTestUtils.java:445)
	at com.hazelcast.map.impl.tx.TxnMapNearCacheBasicTest.whenGetIsUsed_thenNearCacheShouldBePopulated(TxnMapNearCacheBasicTest.java:194)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-freestyle/439/testReport/junit/com.hazelcast.map.impl.tx/TxnMapNearCacheBasicTest/whenGetIsUsed_thenNearCacheShouldBePopulated_format_BINARY_serializeKeys_false_/

**Comment by hasancelik** [comment]
*maintenance*
```
java.lang.AssertionError: Near Cache size didn't reach the desired value (1000 vs. 575) (NearCacheStatsImpl{ownedEntryCount=575, ownedEntryMemoryCost=0, creationTime=1518223168534, hits=575, misses=2425, ratio=23.7%, evictions=0, expirations=0, lastPersistenceTime=0, persistenceCount=0, lastPersistenceDuration=0, lastPersistenceWrittenBytes=0, lastPersistenceKeyCount=0, lastPersistenceFailure=''}) expected:<1000> but was:<575>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils.assertNearCacheSize(NearCacheTestUtils.java:428)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils$4.run(NearCacheTestUtils.java:448)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1145)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1162)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils.assertNearCacheSizeEventually(NearCacheTestUtils.java:445)
	at com.hazelcast.map.impl.tx.TxnMapNearCacheBasicTest.whenGetIsUsed_thenNearCacheShouldBePopulated(TxnMapNearCacheBasicTest.java:196)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-OracleJDK1.6-freestyle/132/testReport/junit/com.hazelcast.map.impl.tx/TxnMapNearCacheBasicTest/whenGetIsUsed_thenNearCacheShouldBePopulated_format_OBJECT_serializeKeys_false_/

**Comment by sancar** [comment]
master pr builder 

https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/13882/testReport/com.hazelcast.map.impl.tx/TxnMapNearCacheBasicTest/whenGetIsUsed_thenNearCacheShouldBePopulated_format_BINARY_serializeKeys_false_/

com.hazelcast.map.impl.tx.TxnMapNearCacheBasicTest.whenGetIsUsed_thenNearCacheShouldBePopulated[format:BINARY serializeKeys:false]



```
Error Message
Near Cache size didn't reach the desired value (1000 vs. 780) (NearCacheStatsImpl{ownedEntryCount=780, ownedEntryMemoryCost=91170, creationTime=1519737261755, hits=780, misses=2220, ratio=35.1%, evictions=0, expirations=0, lastPersistenceTime=0, persistenceCount=0, lastPersistenceDuration=0, lastPersistenceWrittenBytes=0, lastPersistenceKeyCount=0, lastPersistenceFailure=''}) expected:<1000> but was:<780>
Stacktrace
java.lang.AssertionError: Near Cache size didn't reach the desired value (1000 vs. 780) (NearCacheStatsImpl{ownedEntryCount=780, ownedEntryMemoryCost=91170, creationTime=1519737261755, hits=780, misses=2220, ratio=35.1%, evictions=0, expirations=0, lastPersistenceTime=0, persistenceCount=0, lastPersistenceDuration=0, lastPersistenceWrittenBytes=0, lastPersistenceKeyCount=0, lastPersistenceFailure=''}) expected:<1000> but was:<780>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils.assertNearCacheSize(NearCacheTestUtils.java:428)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils$4.run(NearCacheTestUtils.java:448)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1145)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1162)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils.assertNearCacheSizeEventually(NearCacheTestUtils.java:445)
	at com.hazelcast.map.impl.tx.TxnMapNearCacheBasicTest.whenGetIsUsed_thenNearCacheShouldBePopulated(TxnMapNearCacheBasicTest.java:196)
```

**Comment by sancar** [comment]
Failed in master pr builder

https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/14579/testReport/junit/com.hazelcast.map.impl.tx/TxnMapNearCacheBasicTest/whenGetIsUsed_thenNearCacheShouldBePopulated_format_BINARY_serializeKeys_false_/

```
Error Message
Near Cache size didn't reach the desired value (1000 vs. 780) (NearCacheStatsImpl{ownedEntryCount=780, ownedEntryMemoryCost=91170, creationTime=1521633996823, hits=780, misses=2220, ratio=35.1%, evictions=0, expirations=0, lastPersistenceTime=0, persistenceCount=0, lastPersistenceDuration=0, lastPersistenceWrittenBytes=0, lastPersistenceKeyCount=0, lastPersistenceFailure=''}) expected:<1000> but was:<780>
Stacktrace
java.lang.AssertionError: Near Cache size didn't reach the desired value (1000 vs. 780) (NearCacheStatsImpl{ownedEntryCount=780, ownedEntryMemoryCost=91170, creationTime=1521633996823, hits=780, misses=2220, ratio=35.1%, evictions=0, expirations=0, lastPersistenceTime=0, persistenceCount=0, lastPersistenceDuration=0, lastPersistenceWrittenBytes=0, lastPersistenceKeyCount=0, lastPersistenceFailure=''}) expected:<1000> but was:<780>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils.assertNearCacheSize(NearCacheTestUtils.java:428)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils$4.run(NearCacheTestUtils.java:448)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1151)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1168)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils.assertNearCacheSizeEventually(NearCacheTestUtils.java:445)
	at com.hazelcast.map.impl.tx.TxnMapNearCacheBasicTest.whenGetIsUsed_thenNearCacheShouldBePopulated(TxnMapNearCacheBasicTest.java:196)
```

**Comment by Holmistr** [comment]
*maintenance*

Failed again on IBM 1.7 JDK: https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.maintenance-IbmJDK1.7-freestyle/62/testReport/junit/com.hazelcast.map.impl.tx/TxnMapNearCacheBasicTest/whenGetIsUsed_thenNearCacheShouldBePopulated_format_BINARY_serializeKeys_false_/

Stacktrace:
```
java.lang.AssertionError: Near Cache size didn't reach the desired value (1000 vs. 780) (NearCacheStatsImpl{ownedEntryCount=780, ownedEntryMemoryCost=91170, creationTime=1522585272848, hits=780, misses=2220, ratio=35.1%, evictions=0, expirations=0, lastPersistenceTime=0, persistenceCount=0, lastPersistenceDuration=0, lastPersistenceWrittenBytes=0, lastPersistenceKeyCount=0, lastPersistenceFailure=''}) expected:<1000> but was:<780>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils.assertNearCacheSize(NearCacheTestUtils.java:428)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils$4.run(NearCacheTestUtils.java:448)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1151)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1168)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils.assertNearCacheSizeEventually(NearCacheTestUtils.java:445)
	at com.hazelcast.map.impl.tx.TxnMapNearCacheBasicTest.whenGetIsUsed_thenNearCacheShouldBePopulated(TxnMapNearCacheBasicTest.java:196)
```

Apparently, the stacktrace is completely the same, look at the actual value = 780. It seems like there is something weird going on, not like a regular random failure, since the number is still constant.
