### ISSUE TITLE
Issue9766Test.serverRestartWhenReliableTopicListenerRegistered

### ISSUE THREAD

**Issue by mdogan** [hazelcast/hazelcast#11487]
```
com.hazelcast.client.HazelcastClientNotActiveException: Partition does not have an owner. partitionId: 98
	at com.hazelcast.client.topic.Issue9766Test.serverRestartWhenReliableTopicListenerRegistered(Issue9766Test.java:91)
Caused by: java.io.IOException: Partition does not have an owner. partitionId: 98
```

https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/11008

**Comment by mmedenjak** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-pr-builder/15738

```java
java.lang.AssertionError: CountDownLatch failed to complete within 120 seconds, count left: 1
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:1131)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:1116)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:1104)
	at com.hazelcast.client.topic.Issue9766Test.serverRestartWhenReliableTopicListenerRegistered(Issue9766Test.java:96)
```

**Comment by mmedenjak** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-pr-builder/15921/testReport/junit/com.hazelcast.client.topic/Issue9766Test/serverRestartWhenReliableTopicListenerRegistered/

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-pr-builder/15923/testReport/junit/com.hazelcast.client.topic/Issue9766Test/serverRestartWhenReliableTopicListenerRegistered/
