### ISSUE TITLE
WriteBehindFailAndRetryTest.testPartialStoreOperationDone_afterTemporaryMapStoreFailure

### ISSUE THREAD

**Issue by mmedenjak** [hazelcast/hazelcast#11496]
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/11043

```
java.lang.AssertionError: expected:<3> but was:<2>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.map.impl.mapstore.writebehind.WriteBehindFailAndRetryTest$4.run(WriteBehindFailAndRetryTest.java:196)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1129)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1146)
	at com.hazelcast.map.impl.mapstore.writebehind.WriteBehindFailAndRetryTest.testPartialStoreOperationDone_afterTemporaryMapStoreFailure(WriteBehindFailAndRetryTest.java:193)
```

**Comment by Donnerbart** [comment]
**com.hazelcast.map.impl.mapstore.writebehind.WriteBehindFailAndRetryTest.testPartialStoreOperationDone_afterTemporaryMapStoreFailure**
```java
java.lang.AssertionError: expected:<3> but was:<2>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.map.impl.mapstore.writebehind.WriteBehindFailAndRetryTest$4.run(WriteBehindFailAndRetryTest.java:196)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1149)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1166)
	at com.hazelcast.map.impl.mapstore.writebehind.WriteBehindFailAndRetryTest.testPartialStoreOperationDone_afterTemporaryMapStoreFailure(WriteBehindFailAndRetryTest.java:193)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/12263/testReport/junit/com.hazelcast.map.impl.mapstore.writebehind/WriteBehindFailAndRetryTest/testPartialStoreOperationDone_afterTemporaryMapStoreFailure/

**Comment by Donnerbart** [comment]
**com.hazelcast.map.impl.mapstore.writebehind.WriteBehindFailAndRetryTest.testPartialStoreOperationDone_afterTemporaryMapStoreFailure**
```java
java.lang.AssertionError: expected:<3> but was:<2>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.map.impl.mapstore.writebehind.WriteBehindFailAndRetryTest$4.run(WriteBehindFailAndRetryTest.java:196)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1149)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1166)
	at com.hazelcast.map.impl.mapstore.writebehind.WriteBehindFailAndRetryTest.testPartialStoreOperationDone_afterTemporaryMapStoreFailure(WriteBehindFailAndRetryTest.java:193)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/12483/testReport/junit/com.hazelcast.map.impl.mapstore.writebehind/WriteBehindFailAndRetryTest/testPartialStoreOperationDone_afterTemporaryMapStoreFailure/

**Comment by ahmetmircik** [comment]
merged a fix attempt for this issue: https://github.com/hazelcast/hazelcast/commit/ceff89b26068e1a248e835f26466736d7b1dfb03
