### ISSUE TITLE
simulator profile ee/setA/large failing with NPE

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#11519]
simulator profile's 
https://github.com/hazelcast/release-verification/tree/master/3.9-SNAPSHOT

multi run's, ending in 'java.lang.NullPointerException' from random tests,
and event a `./2017-09-29__10_12_56/C_A10_W1-34.228.113.162-member/hs_err_pid3470.log`

/ee/setA/small                         is passing
/os/setA/small and large         is passing

only passing run for `/ee/setA/large`  
i disabled 3 jcache tests,  CacheConcurrentCreate  CacheCreateDestroy  CacheMangle

**Comment by Danny-Hazelcast** [comment]
to be abel to reproduce the issue use the /ee/setA/large profile,

https://github.com/hazelcast/release-verification/tree/master/3.9-SNAPSHOT/ee/setA/large

**Comment by mmedenjak** [comment]
URL: http://54.82.84.143/~jenkins/workspace/Release/3.9-SNAPSHOT/ee/setA/large/2017-09-29__10_12_56/

Exception:
```
WARN  2017-09-29 11:02:02,530 [MapCas-runThread-3] com.hazelcast.simulator.utils.ExceptionReporter: Exception #1 detected
java.lang.NullPointerException
        at com.hazelcast.simulator.tests.map.MapCasTest.timeStep(MapCasTest.java:86)
        at MapCasTestRunnerMapCas.timeStepLoop(MapCasTestRunnerMapCas.java:34)
        at com.hazelcast.simulator.worker.testcontainer.TimeStepRunner.run(TimeStepRunner.java:84)
        at java.lang.Thread.run(Thread.java:745)
        at com.hazelcast.simulator.utils.ThreadSpawner$ReportExceptionThread.run(ThreadSpawner.java:181)
```
```
WARN  2017-09-29 11:02:02,800 [CacheEP-runThread-2] com.hazelcast.simulator.utils.ExceptionReporter: Exception #2 detected
javax.cache.processor.EntryProcessorException: java.lang.NullPointerException
        at com.hazelcast.client.cache.impl.ClientCacheProxy.invokeInternal(ClientCacheProxy.java:336)
        at com.hazelcast.client.cache.impl.ClientCacheProxy.invoke(ClientCacheProxy.java:310)
        at com.hazelcast.simulator.tests.icache.EntryProcessorICacheTest.timeStep(EntryProcessorICacheTest.java:87)
        at EntryProcessorICacheTestRunnerCacheEP.timeStepLoop(EntryProcessorICacheTestRunnerCacheEP.java:34)
        at com.hazelcast.simulator.worker.testcontainer.TimeStepRunner.run(TimeStepRunner.java:84)
        at java.lang.Thread.run(Thread.java:745)
        at com.hazelcast.simulator.utils.ThreadSpawner$ReportExceptionThread.run(ThreadSpawner.java:181)
Caused by: java.lang.NullPointerException
        at com.hazelcast.simulator.tests.icache.EntryProcessorICacheTest$IncrementEntryProcessor.process(EntryProcessorICacheTest.java:122)
        at com.hazelcast.cache.impl.AbstractCacheRecordStore.invoke(AbstractCacheRecordStore.java:1461)
        at com.hazelcast.cache.hidensity.operation.CacheEntryProcessorOperation.runInternal(CacheEntryProcessorOperation.java:47)
```
```
WARN  2017-09-29 11:02:02,986 [MapLock-runThread-3] com.hazelcast.simulator.utils.ExceptionReporter: Exception #3 detected
java.lang.NullPointerException
        at com.hazelcast.simulator.tests.map.MapLockTest.timeStep(MapLockTest.java:67)
        at MapLockTestRunnerMapLock.timeStepLoop(MapLockTestRunnerMapLock.java:34)
        at com.hazelcast.simulator.worker.testcontainer.TimeStepRunner.run(TimeStepRunner.java:84)
        at java.lang.Thread.run(Thread.java:745)
        at com.hazelcast.simulator.utils.ThreadSpawner$ReportExceptionThread.run(ThreadSpawner.java:181)
```
```
WARN  2017-09-29 11:02:02,803 [CacheCas-runThread-1] com.hazelcast.simulator.utils.ExceptionReporter: Exception #1 detected
java.lang.NullPointerException
        at com.hazelcast.simulator.tests.icache.CasICacheTest.timeStep(CasICacheTest.java:75)
        at CasICacheTestRunnerCacheCas.timeStepLoop(CasICacheTestRunnerCacheCas.java:34)
        at com.hazelcast.simulator.worker.testcontainer.TimeStepRunner.run(TimeStepRunner.java:84)
        at java.lang.Thread.run(Thread.java:745)
        at com.hazelcast.simulator.utils.ThreadSpawner$ReportExceptionThread.run(ThreadSpawner.java:181)
```
```
WARN  2017-09-29 11:02:02,955 [MapEntryProcessor-runThread-2] com.hazelcast.simulator.utils.ExceptionReporter: Exception #2 detected
java.lang.NullPointerException
        at com.hazelcast.simulator.tests.map.MapEntryProcessorTest$IncrementEntryProcessor.process(MapEntryProcessorTest.java:114)
        at com.hazelcast.map.impl.operation.EntryOperator.process(EntryOperator.java:328)
        at com.hazelcast.map.impl.operation.EntryOperator.operateOnKeyValueInternal(EntryOperator.java:187)
        at com.hazelcast.map.impl.operation.EntryOperator.operateOnKey(EntryOperator.java:172)
        at com.hazelcast.map.impl.operation.HDEntryOperation.runVanilla(HDEntryOperation.java:305)
        at com.hazelcast.map.impl.operation.HDEntryOperation.runInternal(HDEntryOperation.java:95)
        at com.hazelcast.map.impl.operation.HDMapOperation.run(HDMapOperation.java:72)
```
```
WARN  2017-09-29 11:02:03,860 [MapTransaction-runThread-2] com.hazelcast.simulator.utils.ExceptionReporter: Exception #10 detected
java.lang.NullPointerException
        at com.hazelcast.simulator.tests.map.MapTransactionTest$1.execute(MapTransactionTest.java:89)
        at com.hazelcast.client.spi.impl.ClientTransactionManagerServiceImpl.executeTransaction(ClientTransactionManagerServiceImpl.java:73)
        at com.hazelcast.client.impl.HazelcastClientInstanceImpl.executeTransaction(HazelcastClientInstanceImpl.java:569)
        at com.hazelcast.client.impl.HazelcastClientProxy.executeTransaction(HazelcastClientProxy.java:175)
        at com.hazelcast.simulator.tests.map.MapTransactionTest.timeStep(MapTransactionTest.java:79)
        at MapTransactionTestRunnerMapTransaction.timeStepLoop(MapTransactionTestRunnerMapTransaction.java:34)
        at com.hazelcast.simulator.worker.testcontainer.TimeStepRunner.run(TimeStepRunner.java:84)
        at java.lang.Thread.run(Thread.java:745)
        at com.hazelcast.simulator.utils.ThreadSpawner$ReportExceptionThread.run(ThreadSpawner.java:181)
```

**Comment by mmedenjak** [comment]
Also, only one member encountered `NullPointerException`s and it is the one which ultimately crashed. That member also logged lots of errors such as:
```
ERROR 2017-09-29 11:02:02,775 [hz._hzInstance_1_workers.partition-operation.thread-5] com.hazelcast.map.impl.operation.EnterpriseMapReplicationOperation: [10.0.0.86]:5701 [workers] [3.9-SNAPSHOT] map replication operation failed for partitionId=149
java.lang.AssertionError: Size mismatch -> header: 1, param: 16
```

**Comment by mmedenjak** [comment]
The failing member logs, config, crash log and others: [member.tar.gz](https://github.com/hazelcast/hazelcast/files/1359307/member.tar.gz)

**Comment by mmedenjak** [comment]
The NPEs seem to start after these:
```
ERROR 2017-09-29 11:02:02,472 [hz._hzInstance_1_workers.partition-operation.thread-5] com.hazelcast.cache.operation.CacheSegmentDestroyOperation: [10.0.0.86]:5701 [workers] [3.9-SNAPSHOT] Double free() -> address: 140505011351088, size: 392740
java.lang.AssertionError: Double free() -> address: 140505011351088, size: 392740
        at com.hazelcast.memory.AbstractPoolingMemoryManager.free(AbstractPoolingMemoryManager.java:100)
        at com.hazelcast.internal.serialization.impl.EnterpriseSerializationServiceV1.disposeDataInternal(EnterpriseSerializationServiceV1.java:206)
        at com.hazelcast.internal.serialization.impl.EnterpriseSerializationServiceV1.disposeData(EnterpriseSerializationServiceV1.java:196)
        at com.hazelcast.internal.hidensity.impl.AbstractHiDensityRecordAccessor.disposeData(AbstractHiDensityRecordAccessor.java:100)
        at com.hazelcast.internal.hidensity.impl.AbstractHiDensityRecordAccessor.disposeData(AbstractHiDensityRecordAccessor.java:106)
        at com.hazelcast.internal.hidensity.impl.AbstractHiDensityRecordAccessor.disposeValue(AbstractHiDensityRecordAccessor.java:88)
        at com.hazelcast.internal.hidensity.impl.AbstractHiDensityRecordAccessor.dispose(AbstractHiDensityRecordAccessor.java:56)
        at com.hazelcast.internal.hidensity.impl.AbstractHiDensityRecordAccessor.dispose(AbstractHiDensityRecordAccessor.java:66)
        at com.hazelcast.internal.hidensity.impl.DefaultHiDensityRecordProcessor.dispose(DefaultHiDensityRecordProcessor.java:58)
        at com.hazelcast.elastic.map.BinaryElasticHashMap$SlotIter.removeInternal(BinaryElasticHashMap.java:827)
        at com.hazelcast.elastic.map.BinaryElasticHashMap$KeyIter.removeInternal(BinaryElasticHashMap.java:916)
        at com.hazelcast.elastic.map.BinaryElasticHashMap$SlotIter.remove(BinaryElasticHashMap.java:806)
        at com.hazelcast.elastic.map.BinaryElasticHashMap.clear(BinaryElasticHashMap.java:1105)
        at com.hazelcast.internal.hidensity.impl.DefaultHiDensityRecordMap.clear(DefaultHiDensityRecordMap.java:103)
        at com.hazelcast.cache.impl.AbstractCacheRecordStore.clear(AbstractCacheRecordStore.java:1501)
        at com.hazelcast.cache.hidensity.impl.nativememory.HiDensityNativeMemoryCacheRecordStore.clear(HiDensityNativeMemoryCacheRecordStore.java:875)
        at com.hazelcast.cache.impl.AbstractCacheRecordStore.destroy(AbstractCacheRecordStore.java:1513)
        at com.hazelcast.cache.hidensity.impl.nativememory.HiDensityNativeMemoryCacheRecordStore.destroy(HiDensityNativeMemoryCacheRecordStore.java:907)
        at com.hazelcast.cache.impl.CachePartitionSegment.deleteRecordStore(CachePartitionSegment.java:83)
        at com.hazelcast.cache.operation.CacheSegmentDestroyOperation.run(CacheSegmentDestroyOperation.java:39)
        at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:194)
        at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:120)
        at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:100)
```
```
ERROR 2017-09-29 11:02:02,488 [hz._hzInstance_1_workers.partition-operation.thread-5] com.hazelcast.map.impl.operation.HDPutTransientOperation: [10.0.0.86]:5701 [workers] [3.9-SNAPSHOT] Size mismatch -> header: 1, param: 16
java.lang.AssertionError: Size mismatch -> header: 1, param: 16
        at com.hazelcast.memory.AbstractPoolingMemoryManager.free(AbstractPoolingMemoryManager.java:104)
        at com.hazelcast.memory.PoolingMemoryManager.free(PoolingMemoryManager.java:164)
        at com.hazelcast.internal.serialization.impl.EnterpriseSerializationServiceV1.disposeDataInternal(EnterpriseSerializationServiceV1.java:206)
        at com.hazelcast.internal.serialization.impl.EnterpriseSerializationServiceV1.disposeData(EnterpriseSerializationServiceV1.java:196)
        at com.hazelcast.internal.hidensity.impl.AbstractHiDensityRecordAccessor.disposeData(AbstractHiDensityRecordAccessor.java:100)
        at com.hazelcast.internal.hidensity.impl.DefaultHiDensityRecordProcessor.disposeData(DefaultHiDensityRecordProcessor.java:94)
        at com.hazelcast.internal.hidensity.impl.DefaultHiDensityRecordProcessor.disposeDeferredBlocks(DefaultHiDensityRecordProcessor.java:181)
        at com.hazelcast.map.impl.recordstore.HDStorageImpl.disposeDeferredBlocks(HDStorageImpl.java:196)
        at com.hazelcast.map.impl.recordstore.AbstractRecordStore.disposeDeferredBlocks(AbstractRecordStore.java:204)
        at com.hazelcast.map.impl.recordstore.DefaultRecordStore.disposeDeferredBlocks(DefaultRecordStore.java:73)
        at com.hazelcast.map.impl.operation.HDMapOperation.disposeDeferredBlocks(HDMapOperation.java:122)
        at com.hazelcast.map.impl.operation.HDMapOperation.evict(HDMapOperation.java:110)
        at com.hazelcast.map.impl.operation.HDBasePutOperation.afterRun(HDBasePutOperation.java:41)
        at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.afterRun(OperationRunnerImpl.java:295)
        at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:196)
        at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:406)
        at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:433)
        at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:569)
        at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:554)
        at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:513)
        at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:207)
        at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:60)
        at com.hazelcast.client.impl.protocol.task.AbstractPartitionMessageTask.processMessage(AbstractPartitionMessageTask.java:64)
        at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:123)
        at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:103)
        at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:154)
        at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:125)
        at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:100)
```

**Comment by mmedenjak** [comment]
The `java.lang.AssertionError: Size mismatch` affects map and cache operations as well as a partition migration:
```
ERROR 2017-09-29 11:02:02,527 [hz._hzInstance_1_workers.partition-operation.thread-5] com.hazelcast.map.impl.operation.EnterpriseMapReplicationOperation: [10.0.0.86]:5701 [workers] [3.9-SNAPSHOT] map repl
ication operation failed for partitionId=109
java.lang.AssertionError: Size mismatch -> header: 1, param: 16
        at com.hazelcast.memory.AbstractPoolingMemoryManager.free(AbstractPoolingMemoryManager.java:104)
        at com.hazelcast.memory.PoolingMemoryManager.free(PoolingMemoryManager.java:164)
        at com.hazelcast.internal.serialization.impl.EnterpriseSerializationServiceV1.disposeDataInternal(EnterpriseSerializationServiceV1.java:206)
        at com.hazelcast.internal.serialization.impl.EnterpriseSerializationServiceV1.disposeData(EnterpriseSerializationServiceV1.java:196)
        at com.hazelcast.internal.hidensity.impl.DefaultHiDensityRecordProcessor.disposeData(DefaultHiDensityRecordProcessor.java:145)
        at com.hazelcast.elastic.map.BinaryElasticHashMap$SlotIter.removeInternal(BinaryElasticHashMap.java:823)
        at com.hazelcast.elastic.map.BinaryElasticHashMap$KeyIter.removeInternal(BinaryElasticHashMap.java:916)
        at com.hazelcast.elastic.map.BinaryElasticHashMap$SlotIter.remove(BinaryElasticHashMap.java:806)
        at com.hazelcast.elastic.map.BinaryElasticHashMap.clear(BinaryElasticHashMap.java:1105)
        at com.hazelcast.map.impl.recordstore.HDStorageImpl.clear(HDStorageImpl.java:137)
        at com.hazelcast.map.impl.recordstore.DefaultRecordStore.reset(DefaultRecordStore.java:504)
        at com.hazelcast.map.impl.recordstore.EnterpriseRecordStore.reset(EnterpriseRecordStore.java:151)
        at com.hazelcast.map.impl.operation.MapReplicationStateHolder.applyState(MapReplicationStateHolder.java:167)
        at com.hazelcast.map.impl.operation.MapReplicationOperation.run(MapReplicationOperation.java:71)
        at com.hazelcast.map.impl.operation.EnterpriseMapReplicationOperation.run(EnterpriseMapReplicationOperation.java:39)
        at com.hazelcast.internal.partition.operation.PartitionReplicaSyncResponse.executeOperations(PartitionReplicaSyncResponse.java:152)
        at com.hazelcast.internal.partition.operation.PartitionReplicaSyncResponse.run(PartitionReplicaSyncResponse.java:92)
        at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:194)
        at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:409)
        at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:115)
        at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:100)
```

**Comment by mmedenjak** [comment]
it might not be related but we had similar assertion errors in a hot restart issue a while back: https://github.com/hazelcast/hazelcast-enterprise/issues/1587#issuecomment-320622818

**Comment by tombujok** [comment]
NullPointer should be fixed once this one get's fixed: https://github.com/hazelcast/hazelcast/issues/11452
Ahmet is on it.

**Comment by jerrinot** [comment]
@ahmetmircik: is this also fixed by https://github.com/hazelcast/hazelcast/pull/11474 ?

**Comment by mmedenjak** [comment]
@jerrinot @tombujok 
I don't think the merged PR will fix this. This test caused NPE's in other parts of the code as well as in test code because `map.get()` started returning `null` for a previously associated key. This is probably connected to the fact the assertions on the HD memory manager started failing and the record store was failing (ultimately leading to a JVM crash).

**Comment by tombujok** [comment]
Vassilis is looking at it. If anyone else is free, plz join him! This may not be a failure that's easy to diagnose. If you guys are free @tkountis @ahmetmircik @mdogan, plz look at it too.
It may be related to HD-indexes work, but I didn't check if that record store that failed had an HD-index.

**Comment by ahmetmircik** [comment]
@jerrinot #11474  is not a fix for this issue. Seems the main issue here is failing assertions on HD memory, NPE appears as a side effect of it (reason for NPE: entry processors don't expect any null entry and weren't coded to tolerate nulls).

**Comment by mdogan** [comment]
I'm trying to reproduce the issue but I couldn't make the tests start. Instance start fails with
```
com.hazelcast.nio.serialization.HazelcastSerializationException: java.lang.ClassNotFoundException: com.hazelcast.simulator.tests.synthetic.SyntheticSerializableFactory
        at com.hazelcast.internal.serialization.impl.DefaultSerializationServiceBuilder.buildDataSerializableFactories(DefaultSerializationServiceBuilder.java:360)
        at com.hazelcast.internal.serialization.impl.DefaultSerializationServiceBuilder.addConfigDataSerializableFactories(DefaultSerializationServiceBuilder.java:319)
        at com.hazelcast.internal.serialization.impl.DefaultSerializationServiceBuilder.build(DefaultSerializationServiceBuilder.java:218)
        at com.hazelcast.internal.serialization.impl.EnterpriseSerializationServiceBuilder.build(EnterpriseSerializationServiceBuilder.java:130)
        at com.hazelcast.internal.serialization.impl.EnterpriseSerializationServiceBuilder.build(EnterpriseSerializationServiceBuilder.java:20)
        at com.hazelcast.instance.EnterpriseNodeExtension.createSerializationService(EnterpriseNodeExtension.java:325)
        at com.hazelcast.instance.Node.<init>(Node.java:203)
        at com.hazelcast.instance.HazelcastInstanceImpl.createNode(HazelcastInstanceImpl.java:160)
        at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:128)
        at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:195)
        at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:174)
        at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:124)
        at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:58)
        at com.hazelcast.simulator.vendors.HazelcastDriver.startVendorInstance(HazelcastDriver.java:229)
        at com.hazelcast.simulator.worker.Worker.start(Worker.java:90)
        at com.hazelcast.simulator.worker.Worker.main(Worker.java:126)
```

I tried with 0.11-snapshot, 0.10, 0.9.6 but no luck. Also I couldn't find the class `com.hazelcast.simulator.tests.synthetic.SyntheticSerializableFactory` in simulator repo.

**Comment by mdogan** [comment]
Also I did some changes to `simulator.properties` and `coordinator` parameters to make it work.

**Comment by vbekiaris** [comment]
A recurring issue in the log is that there's a failure to put an entry and the error handling in `onOwnError` attempts to remove the event from the event journal -> fails with `Cache /hz/CreateDestroyICacheTest is already destroyed or not created yet`. The original error that occurs in `onOwn` (while putting the value) is not visible, however it could be the same error, given that `onOwn` attempts to write an event to the event journal itself, before throwing an exception and then throwing yet another exception while handling the original one.
Stack trace:
```
ERROR 2017-09-29 10:27:45,466 [hz._hzInstance_1_workers.partition-operation.thread-4] com.hazelcast.cache.hidensity.operation.CachePutBackupOperation: [10.0.0.86]:5701 [workers] [3.9-SNAPSHOT] Cache /hz/CreateDestroyICacheTest is already destroyed or not created yet, on Member [10.0.0.86]:5701 - b406c1a4-9dee-4435-9fb6-67acf8afed17 this
com.hazelcast.cache.CacheNotExistsException: Cache /hz/CreateDestroyICacheTest is already destroyed or not created yet, on Member [10.0.0.86]:5701 - b406c1a4-9dee-4435-9fb6-67acf8afed17 this
	at com.hazelcast.cache.impl.journal.RingbufferCacheEventJournalImpl.getEventJournalConfig(RingbufferCacheEventJournalImpl.java:161)
	at com.hazelcast.cache.impl.journal.RingbufferCacheEventJournalImpl.getRingbufferOrNull(RingbufferCacheEventJournalImpl.java:255)
	at com.hazelcast.cache.impl.journal.RingbufferCacheEventJournalImpl.addToEventRingbuffer(RingbufferCacheEventJournalImpl.java:185)
	at com.hazelcast.cache.impl.journal.RingbufferCacheEventJournalImpl.writeRemoveEvent(RingbufferCacheEventJournalImpl.java:76)
	at com.hazelcast.cache.hidensity.impl.nativememory.HiDensityNativeMemoryCacheRecordStore.onOwnError(HiDensityNativeMemoryCacheRecordStore.java:644)
	at com.hazelcast.cache.hidensity.impl.nativememory.HiDensityNativeMemoryCacheRecordStore.own(HiDensityNativeMemoryCacheRecordStore.java:720)
	at com.hazelcast.cache.hidensity.impl.nativememory.HiDensityNativeMemoryCacheRecordStore.putBackup(HiDensityNativeMemoryCacheRecordStore.java:661)
	at com.hazelcast.cache.hidensity.operation.CachePutBackupOperation.runInternal(CachePutBackupOperation.java:47)
	at com.hazelcast.cache.hidensity.operation.AbstractHiDensityCacheOperation.run(AbstractHiDensityCacheOperation.java:115)
	at com.hazelcast.spi.impl.operationservice.impl.operations.Backup.run(Backup.java:141)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:194)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:409)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:115)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:100)
```

**Comment by ahmetmircik** [comment]
@vbekiaris seems as a result of that exception, [here](https://github.com/hazelcast/hazelcast-enterprise/blob/master/hazelcast-enterprise/src/main/java/com/hazelcast/cache/hidensity/impl/nativememory/HiDensityNativeMemoryCacheRecordStore.java#L720) `oldValueData` is missing from dispose.

**Comment by Donnerbart** [comment]
The class `SyntheticSerializableFactory` is part of the test modules, which are specific to the HZ version (it's part of a network component test, which relies heavily on HZ internals, so we need a custom test per HZ version). Those test classes should automatically be deployed by Hazelcast, and the matching one should be added the Simulator worker classpath (together with the common test JAR, which should be HZ version independent).

**Comment by mdogan** [comment]
@donnerbart: I understand the issue but still I don't know how to fix that 😀

Or I can switch to the latest simulator version that is containing these tests.

**Comment by Donnerbart** [comment]
Those test JARs should be part of every Simulator version starting from 0.8 or 0.9 (don't remember exactly, when we introduced this).

It looks like Peter removed the `tests-hz35` and `tests-hz36` modules in newer Simulator versions and `tests-hz39` is not yet added (master branch, 0.10 and 0.11). I fixed this in the maintenance branch though, which is used for HZ releases (0.9.x).

This is our latest stable release 0.9.6, which contains all expected test folders:
```
[jenkins@ip-127-0-0-1 test-lib]$ pwd
/home/jenkins/hazelcast-simulator-0.9.6/test-lib
[jenkins@ip-127-0-0-1 test-lib]$ ls -l
total 24
drwxr-xr-x 2 jenkins jenkins 4096 29. Jun 13:28 35
drwxr-xr-x 2 jenkins jenkins 4096 29. Jun 13:28 36
drwxr-xr-x 2 jenkins jenkins 4096 29. Jun 13:28 37
drwxr-xr-x 2 jenkins jenkins 4096 29. Jun 13:28 38
drwxr-xr-x 2 jenkins jenkins 4096 29. Jun 13:28 39
drwxr-xr-x 2 jenkins jenkins 4096 29. Jun 13:28 common
```

**Comment by mdogan** [comment]
@Donnerbart: thanks.

@vbekiaris: very good finding. That failure can clearly cause memory corruption. When `onOwnError()` exits early before disposing the record, it can leave the record in a corrupted state, `value` is released/disposed by operation but `value` address remains in the record. When record is disposed later, a double free error will be raised.

**Comment by mdogan** [comment]
I'll try to reproduce the issue myself and then will try again after fixing these cases.

**Comment by mmedenjak** [comment]
I may wrap the call to the event journal in a try-catch block but before doing that I am wondering if anyone knows if there is a safe way of fetching the cache config when inside the `onOwnError` method. Currently, the journal was using the `cacheService.getCacheConfig("/hz/CreateDestroyICacheTest")` which seems to return `null`.
Basically, I wasn't expecting it to be `null` here since the call to the event journal comes from the record store and the record store used the exact same method of fetching the config on initialisation:
https://github.com/hazelcast/hazelcast/blob/456a6366d087957f5e7e73827a686e4a4c8a00bc/hazelcast/src/main/java/com/hazelcast/cache/impl/AbstractCacheRecordStore.java#L114-L118

**Comment by mdogan** [comment]
@mmedenjak: I can observe `CacheNotExistsException` even while doing a 
- cache.create()
- cache.put()
- cache.destroy()
in a single thread. `CacheNotExistsException` can thrown on backup node. I guess, that's because cache config replication mechanism. Until that's fixed, I don't think there's any other way.

**Comment by tkountis** [comment]
Simulator is failing for me, both 0.10 & 0.11 fail with the same error as @mdogan .
0.9.6 is also complaining about probabilities for one of the tests, which uses (.5 + .1 + .1 + .1 +.1 + .1) which suffers from the precision
>The total probability of TimeStep methods in test com.hazelcast.simulator.tests.icache.MangleICacheTest is smaller than 1.0, found: 0.98]

**Comment by mdogan** [comment]
I've reproduced the `AssertionError: Double free()` and `AssertionError: Size mismatch ->` errors without eventjournal, on local machine. Apparently `CacheNotExistsException ` thrown by event journal is not the only issue.

**Comment by mmedenjak** [comment]
@mdogan thanks for the info.
I guess the best thing to do then is wrap all event journal actions for cache in a try-catch block. 
I will leave the map journal unchanged since I believe map has a simpler config lifecycle and we can rely on the config being more readily available.

**Comment by tkountis** [comment]
@mdogan can you share the reproducer ?

**Comment by mdogan** [comment]
I'll share soon, just a few mins, cleaning up a bit.

**Comment by mdogan** [comment]
Using standard memory manager:

**Comment by mdogan** [comment]
```java
public static void main(String[] args) throws Exception {
    Config config = new Config();
    config.getNetworkConfig().getJoin().getMulticastConfig().setEnabled(false);
    config.getNetworkConfig().getJoin().getTcpIpConfig().setEnabled(true).clear().addMember("127.0.0.1");
    config.setLicenseKey(SampleLicense.UNLIMITED_LICENSE);

    MemoryAllocatorType allocatorType = MemoryAllocatorType.STANDARD;
    config.getNativeMemoryConfig().setEnabled(true)
            .setAllocatorType(allocatorType)
            .setSize(new MemorySize(1, MemoryUnit.GIGABYTES));

    config.getCacheConfig("HD*").setInMemoryFormat(InMemoryFormat.NATIVE).setEvictionConfig(
            new EvictionConfig(99, EvictionConfig.MaxSizePolicy.USED_NATIVE_MEMORY_PERCENTAGE,
                    EvictionConfig.DEFAULT_EVICTION_POLICY));

    final HazelcastInstance hz1 = Hazelcast.newHazelcastInstance(config);
    final HazelcastInstance hz2 = Hazelcast.newHazelcastInstance(config);
    final int threads = 2;

    for (int i = 0; i < threads; i++) {
        final int index = i;
        new Thread() {
            public void run() {
                Random random = new Random();
                HazelcastInstance hz = index % 2 == 0 ? hz1 : hz2;
                while (true) {
                    ICache<Object, Object> cache = hz.getCacheManager().getCache("HD" + random.nextInt(10));
                    for (int x = 0; x < 100; x++) {
                        try {
                            cache.put(x, UuidUtil.newUnsecureUuidString());
                        } catch (CacheNotExistsException e) {
                        }
                    }
                    cache.destroy();
                }
            }
        }.start();
    }
}    
```

**Comment by Donnerbart** [comment]
That probability issue should be fixed in Simulator 0.9.7-SNAPSHOT, I'll try to release 0.9.7 today (so we also have that version for the final release process). I'll also try to fix the 0.11-SNAPSHOT master version to work with HZ 3.9. I don't know if I should make a Simulator 0.10.1 release as well with the HZ 3.9 module.

**Comment by mdogan** [comment]
@mmedenjak: I don't know the other consequences of the above `getEventJournalConfig()` change. Is it acceptable?

**Comment by vbekiaris** [comment]
I have also verified the same in local testing. I think it makes sense to return `null` from `getEventJournalConfig` when no `CacheConfig` is found.

**Comment by tombujok** [comment]
@mdogan @vbekiaris @ahmetmircik @mmedenjak Great job guys!
