### ISSUE TITLE
DynamicConfigSlowPreJoinBouncingTest.doNotThrowExceptionWhenMemberIsGone

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#11536]
```
com.hazelcast.core.HazelcastException: Cluster topology was not stable for 100 retries, invoke on stable cluster failed
	at com.hazelcast.internal.util.iterator.RestartingMemberIterator.retry(RestartingMemberIterator.java:99)
	at com.hazelcast.internal.util.iterator.RestartingMemberIterator.advance(RestartingMemberIterator.java:84)
	at com.hazelcast.internal.util.iterator.RestartingMemberIterator.hasNext(RestartingMemberIterator.java:78)
	at com.hazelcast.util.IterableUtil$2.hasNext(IterableUtil.java:55)
	at com.hazelcast.internal.util.futures.ChainingFuture.advanceOrComplete(ChainingFuture.java:75)
	at com.hazelcast.internal.util.futures.ChainingFuture.access$000(ChainingFuture.java:36)
	at com.hazelcast.internal.util.futures.ChainingFuture$1.onFailure(ChainingFuture.java:65)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run(AbstractInvocationFuture.java:246)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/1490/com.hazelcast$hazelcast/testReport/com.hazelcast.internal.dynamicconfig/DynamicConfigSlowPreJoinBouncingTest/doNotThrowExceptionWhenMemberIsGone/

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/1493/testReport/junit/com.hazelcast.internal.dynamicconfig/DynamicConfigSlowPreJoinBouncingTest/doNotThrowExceptionWhenMemberIsGone/

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/1495/testReport/junit/com.hazelcast.internal.dynamicconfig/DynamicConfigSlowPreJoinBouncingTest/doNotThrowExceptionWhenMemberIsGone/

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/1496/testReport/junit/com.hazelcast.internal.dynamicconfig/DynamicConfigSlowPreJoinBouncingTest/doNotThrowExceptionWhenMemberIsGone/

**Comment by mdogan** [comment]
Problem here is, retries are done immediately when `ClusterTopologyChangedException` is received. But cluster stabilization may take longer than 100 immediate retries, especially when pre-join operation executes slower, as in this test.

**Comment by tombujok** [comment]
@mdogan What do you suggest? Should we increase the retry count here?

**Comment by mdogan** [comment]
No. We should have a pause between retries, similar to invocation retries. Easier is to add a sleep between retries, but that will block Hazelcast internal async executor thread. That's why I'm trying to figure out a better way.

**Comment by jerrinot** [comment]
@mdogan: I assigned you this issue you are already sent a PR.
