### ISSUE TITLE
ClientCacheNearCachePreloaderTest.testPreloadNearCache_withStringKeys

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#11534]
```
java.lang.AssertionError: Near Cache size didn't reach the desired value (10000 vs. 7000) (NearCacheStatsImpl{ownedEntryCount=7000, ownedEntryMemoryCost=0, creationTime=1507155858507, hits=0, misses=7100, ratio=0.0%, evictions=0, expirations=0, lastPersistenceTime=0, persistenceCount=0, lastPersistenceDuration=0, lastPersistenceWrittenBytes=0, lastPersistenceKeyCount=0, lastPersistenceFailure=''}) expected:<10000> but was:<7000>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils.assertNearCacheSize(NearCacheTestUtils.java:428)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils$4.run(NearCacheTestUtils.java:448)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1129)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1146)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils.assertNearCacheSizeEventually(NearCacheTestUtils.java:445)
	at com.hazelcast.internal.nearcache.AbstractNearCachePreloaderTest.preloadNearCache(AbstractNearCachePreloaderTest.java:302)
	at com.hazelcast.internal.nearcache.AbstractNearCachePreloaderTest.testPreloadNearCache_withStringKeys(AbstractNearCachePreloaderTest.java:261)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.lang.Thread.run(Thread.java:662)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-freestyle/1133/testReport/junit/com.hazelcast.client.cache.nearcache/ClientCacheNearCachePreloaderTest/testPreloadNearCache_withStringKeys_format_OBJECT_invalidationOnChange_false_serializeKeys_true_/

**Comment by tombujok** [comment]
@Donnerbart Is it a new regression?

**Comment by Donnerbart** [comment]
Looks like https://github.com/hazelcast/hazelcast/issues/11456 to me, but this is also quite new. I could reproduce this once locally and saved the log, but could not find the reason.

**Comment by vbekiaris** [comment]
This looks like an environmental issue:
```
01:24:16,773 Started Running Test: testPreloadNearCache_withStringKeys[format:OBJECT invalidationOnChange:false serializeKeys:true]
```
The member is started at `01:24:18,502` and the client gets authenticated with the member at `01:24:18,505`. However there is a huge pause due to logging from another test:
```
01:24:21,988  INFO |testCreateAndDestroyDataStructure_withSameName[format:OBJECT invalidationOnChange:false serializeKeys:true]| - [CacheService] hz._hzInstance_1486_dev.partition-operation.thread-2 - [127.0.0.1]:6512 [dev] [3.9-SNAPSHOT] Added cache config: CacheConfig{name='createDestroyNearCache', managerPrefix='/hz/', inMemoryFormat=OBJECT, backupCount=1, hotRestart=HotRestartConfig{enabled=false, fsync=false}, wanReplicationRef=null}
01:25:33,856  WARN |testCreateAndDestroyDataStructure_withSameName[format:OBJECT invalidationOnChange:false serializeKeys:true]| - [CacheService] hz._hzInstance_1486_dev.partition-operation.thread-2 - Logging took 71868 ms.
```

Since more than one minute has passed, the `HeartbeatManager` kills the client-member connection and `NearCachePreloader.loadKeySet` fails as it attempts to get all key at `adapter.getAll(builder.build());` with an exception:
```
01:25:33,906  WARN |testPreloadNearCache_withStringKeys[format:OBJECT invalidationOnChange:false serializeKeys:true]| - [NearCachePreloader] hz.client_884.internal-1 - Could not pre-load Near Cache /hz/defaultNea
rCache (/scratch/jenkins/workspace/Hazelcast-3.x-freestyle/hazelcast-client/target/test-classes/nearcache-10k-string/nearCache-_hz_defaultNearCache.store)
com.hazelcast.spi.exception.TargetDisconnectedException: Heartbeat timed out to owner connection MockedClientConnection{localAddress=[127.0.0.1]:41363, super=ClientConnection{alive=true, connectionId=1, channel=n
ull, remoteEndpoint=[127.0.0.1]:6519, lastReadTime=2017-10-05 01:25:33.855, lastWriteTime=2017-10-05 01:25:33.856, closedTime=never, lastHeartbeatRequested=never, lastHeartbeatReceived=never, connected server ver
sion=3.9-SNAPSHOT}}
        at com.hazelcast.client.spi.impl.ClientInvocationServiceImpl$CleanResourcesTask.notifyException(ClientInvocationServiceImpl.java:223) ~[classes/:?]
        at com.hazelcast.client.spi.impl.ClientInvocationServiceImpl$CleanResourcesTask.run(ClientInvocationServiceImpl.java:211) ~[classes/:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439) ~[?:1.6.0_45]
        at java.util.concurrent.FutureTask$Sync.innerRunAndReset(FutureTask.java:317) ~[?:1.6.0_45]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:150) ~[?:1.6.0_45]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$101(ScheduledThreadPoolExecutor.java:98) ~[?:1.6.0_45]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.runPeriodic(ScheduledThreadPoolExecutor.java:180) ~[?:1.6.0_45]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:204) ~[?:1.6.0_45]
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895) ~[?:1.6.0_45]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918) ~[?:1.6.0_45]
        at java.lang.Thread.run(Thread.java:662) ~[?:1.6.0_45]
        at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64) ~[hazelcast-3.9-SNAPSHOT.jar:3.9-SNAPSHOT]
        at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80) ~[hazelcast-3.9-SNAPSHOT.jar:3.9-SNAPSHOT]
        at ------ submitted from ------.(Unknown Source) ~[?:?]
        at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:96) ~[classes/:?]
        at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:33) ~[classes/:?]
        at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:155) ~[hazelcast-3.9-SNAPSHOT.jar:3.9-SNAPSHOT]
        at com.hazelcast.client.cache.impl.AbstractClientCacheProxyBase.invoke(AbstractClientCacheProxyBase.java:207) ~[classes/:?]
        at com.hazelcast.client.cache.impl.AbstractClientCacheProxy.getAllInternal(AbstractClientCacheProxy.java:246) ~[classes/:?]
        at com.hazelcast.client.cache.impl.NearCachedClientCacheProxy.getAllInternal(NearCachedClientCacheProxy.java:247) ~[classes/:?]
        at com.hazelcast.client.cache.impl.AbstractClientCacheProxy.getAll(AbstractClientCacheProxy.java:227) ~[classes/:?]
        at com.hazelcast.client.cache.impl.ClientCacheProxy.getAll(ClientCacheProxy.java:94) ~[classes/:?]
        at com.hazelcast.client.cache.impl.ClientCacheProxy.getAll(ClientCacheProxy.java:135) ~[classes/:?]
        at com.hazelcast.internal.adapter.ICacheDataStructureAdapter.getAll(ICacheDataStructureAdapter.java:209) ~[hazelcast-3.9-SNAPSHOT.jar:3.9-SNAPSHOT]
        at com.hazelcast.internal.nearcache.impl.preloader.NearCachePreloader.loadKeySet(NearCachePreloader.java:227) ~[hazelcast-3.9-SNAPSHOT.jar:3.9-SNAPSHOT]
        at com.hazelcast.internal.nearcache.impl.preloader.NearCachePreloader.loadKeys(NearCachePreloader.java:138) [hazelcast-3.9-SNAPSHOT.jar:3.9-SNAPSHOT]
        at com.hazelcast.internal.nearcache.impl.store.BaseHeapNearCacheRecordStore.loadKeys(BaseHeapNearCacheRecordStore.java:125) [hazelcast-3.9-SNAPSHOT.jar:3.9-SNAPSHOT]
        at com.hazelcast.internal.nearcache.impl.DefaultNearCache.preload(DefaultNearCache.java:182) [hazelcast-3.9-SNAPSHOT.jar:3.9-SNAPSHOT]
        at com.hazelcast.internal.nearcache.impl.DefaultNearCacheManager$PreloadTask.run(DefaultNearCacheManager.java:177) [hazelcast-3.9-SNAPSHOT.jar:3.9-SNAPSHOT]
```
