### ISSUE TITLE
DistributedDatastructuresMetricsTest Failures

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#11535]
**testReplicatedMap**
**testNearCache**
**testTopic**
**testExecutor**
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.internal.diagnostics.DistributedDatastructuresMetricsTest$2.run(DistributedDatastructuresMetricsTest.java:167)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1129)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1146)
	at com.hazelcast.internal.diagnostics.DistributedDatastructuresMetricsTest.assertHasStatsEventually(DistributedDatastructuresMetricsTest.java:162)
	at com.hazelcast.internal.diagnostics.DistributedDatastructuresMetricsTest.testReplicatedMap(DistributedDatastructuresMetricsTest.java:134)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-freestyle/1142/
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-freestyle/1143/testReport/junit/com.hazelcast.internal.diagnostics/DistributedDatastructuresMetricsTest/testTopic/
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-freestyle/1147/
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-freestyle/1148/

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK1.7/1001/
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK1.7/1002/

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK8/1324/
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK8/1325/
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK8/1326/

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-ZuluJDK7/717/
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-ZuluJDK7/719/

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-ZuluJDK8/721/
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-ZuluJDK8/723/

**Comment by tombujok** [comment]
@mmedenjak how critical is this? Should we address this in 3.9.1?

**Comment by mmedenjak** [comment]
I'm looking into this right now just to see if it's simple enough to fix.

**Comment by mmedenjak** [comment]
The `StatisticsAwareMetricsSet$Task` silently stopped because of:
```
java.lang.NullPointerException
	at com.hazelcast.map.impl.LocalMapStatsProvider.createAllLocalMapStats(LocalMapStatsProvider.java:104)
	at com.hazelcast.map.impl.MapStatisticsAwareService.getStats(MapStatisticsAwareService.java:42)
	at com.hazelcast.map.impl.MapService.getStats(MapService.java:202)
	at com.hazelcast.internal.metrics.metricsets.StatisticsAwareMetricsSet$Task.registerAliveStats(StatisticsAwareMetricsSet.java:98)
	at com.hazelcast.internal.metrics.metricsets.StatisticsAwareMetricsSet$Task.run(StatisticsAwareMetricsSet.java:84)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
