### ISSUE TITLE
Disabling class caching doesn't work for user code deployments

### ISSUE THREAD

**Issue by kwart** [hazelcast/hazelcast#11549]
Client is not able to replace existing deployment code even the  class cache mode is set to `OFF`.

**Reproducer**
* Use [user-code-deployment](https://github.com/hazelcast/hazelcast-code-samples/tree/master/clients/user-code-deployment) Hazelcast example.
* Change the `Member.java` code - disable class caching:
    ```java
    Config config = new Config();
    UserCodeDeploymentConfig userCodeDeploymentConfig = new UserCodeDeploymentConfig();
    userCodeDeploymentConfig.setEnabled(true);
    userCodeDeploymentConfig.setClassCacheMode(ClassCacheMode.OFF);
    ```
* Run the `Member`
* Run the `Client` - everything should work as expected here
* Change client's `IncrementingEntryProcessor` implementation (e.g. change the incremented value)
* Run the `Client` again

**Actual result**
The second `Client` execution fails when connecting to the cluster.

Member log:
```
SEVERE: [172.17.0.1]:5701 [dev] [3.9-SNAPSHOT] Class IncrementingEntryProcessor is already in a local cache and conflicting byte code representation
java.lang.IllegalStateException: Class IncrementingEntryProcessor is already in a local cache and conflicting byte code representation
	at com.hazelcast.internal.usercodedeployment.impl.ClassLocator.defineClassFromClient(ClassLocator.java:110)
	at com.hazelcast.internal.usercodedeployment.UserCodeDeploymentService.defineClass(UserCodeDeploymentService.java:72)
	at com.hazelcast.internal.usercodedeployment.impl.operation.DeployClassesOperation.run(DeployClassesOperation.java:50)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:194)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:406)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:433)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:569)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:554)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:513)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:207)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:60)
	at com.hazelcast.client.impl.protocol.task.AbstractMultiTargetMessageTask.processMessage(AbstractMultiTargetMessageTask.java:57)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:123)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:103)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
```

**Expected result**
The second `Client` execution will deploy and use the new `IncrementingEntryProcessor` implementation.

**Comment by sancar** [comment]
Hi @kwart, 
Client does not support ClassCacheMode.OFF. 
Classes loaded by clients will always behave like ClassCacheMode.ETERNAL and ProviderMode.LOCAL_AND_CACHED_CLASSES.

I will update our documentation accordingly.

**Comment by kwart** [comment]
@sancar Thanks for looking into it.  Shall we leave this open until the documentation fix is ready?

**Comment by sancar** [comment]
That sounds about right. I will close the issue when I fixed it.

**Comment by tombujok** [comment]
Added issue to the ref-manual repo. Closing this one. 
@Serdaro @sancar here's the doc issue: https://github.com/hazelcast/hazelcast-reference-manual/issues/335

**Comment by ksoot** [comment]
Hi, Though the ref-manual has been updated. But how handle this scenario on clients? Only possible solution I have found is to restart the member. 
It look here we are looking for class name in cache rather than modified byte code. Correct me if I am wrong here?

**Comment by sancar** [comment]
@ksoot You either 
1. restart the member to clear all old deployed classes.
2. always use a different name for the classes that change its bytecode for the classes deployed by the clients.

**Comment by ksoot** [comment]
@sancar For solution no#1 you have provided is applicable in:
1. embedded mode? (client and server both on same machine)
2.  Or in client-server mode? (client on one machine and member running in another machine)

**Comment by sancar** [comment]
If there is a client that running in a separate jvm, they will try to redeploy any classes configured in their config. 
So, if you want your clients to deploy the updated classes, you need to restart your clients as well. Otherwise, they will just redeploy the old version of classes to the restarted server.
