### ISSUE TITLE
Client Code Deployment doesn't work for classes in non-default package

### ISSUE THREAD

**Issue by kwart** [hazelcast/hazelcast#11558]
User code deployed from client is not located correctly, when it's not in a default package.

**Reproducer**
* Use [user-code-deployment](https://github.com/hazelcast/hazelcast-code-samples/tree/master/clients/user-code-deployment) Hazelcast example.
* Run the `Member`
* Change the client. Move the `IncrementingEntryProcessor` class into a non-default java package (e.g. `com.hazelcast.test`). 
* Fix the client code to use the correct entry processor class:
    ```java
  ClientUserCodeDeploymentConfig clientUserCodeDeploymentConfig = new ClientUserCodeDeploymentConfig();
  clientUserCodeDeploymentConfig.addClass(IncrementingEntryProcessor.class);
    ```
* Run the `Client`

**Actual result**
Processor execution fails with class not found.

Client log:
```
ception in thread "main" com.hazelcast.nio.serialization.HazelcastSerializationException: java.lang.ClassNotFoundException: com.hazelcast.test.IncrementingEntryProcessor
	at com.hazelcast.internal.serialization.impl.JavaDefaultSerializers$JavaSerializer.read(JavaDefaultSerializers.java:224)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:185)
	at com.hazelcast.client.impl.protocol.task.map.MapExecuteOnAllKeysMessageTask.createOperationFactory(MapExecuteOnAllKeysMessageTask.java:47)
	at com.hazelcast.client.impl.protocol.task.AbstractAllPartitionsMessageTask.processMessage(AbstractAllPartitionsMessageTask.java:38)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:123)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:103)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:96)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:33)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:155)
	at com.hazelcast.client.spi.ClientProxy.invoke(ClientProxy.java:231)
	at com.hazelcast.client.proxy.ClientMapProxy.executeOnEntries(ClientMapProxy.java:1338)
	at Client.main(Client.java:28)
Caused by: java.lang.ClassNotFoundException: com.hazelcast.test.IncrementingEntryProcessor
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.hazelcast.nio.ClassLoaderUtil.tryLoadClass(ClassLoaderUtil.java:173)
	at com.hazelcast.nio.ClassLoaderUtil.loadClass(ClassLoaderUtil.java:147)
	at com.hazelcast.nio.IOUtil$ClassLoaderAwareObjectInputStream.resolveClass(IOUtil.java:535)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1826)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1713)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2000)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
	at com.hazelcast.internal.serialization.impl.JavaDefaultSerializers$JavaSerializer.read(JavaDefaultSerializers.java:219)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:185)
	at com.hazelcast.client.impl.protocol.task.map.MapExecuteOnAllKeysMessageTask.createOperationFactory(MapExecuteOnAllKeysMessageTask.java:47)
	at com.hazelcast.client.impl.protocol.task.AbstractAllPartitionsMessageTask.processMessage(AbstractAllPartitionsMessageTask.java:38)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:123)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:103)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
```

**Expected result**
The execution completes in the same way as if the processor was in the default package.

**Comment by kwart** [comment]
It again seems as a documentation issue rather than a defect. 

The `ClassLocator.handleClassNotFoundException` chacks the loaded class name against a blacklist and the `com.hazelcast.*` is on the list

Once I've changed the package to a new one which didn't match any entry from the blacklist, the sample started to work again.

**Comment by kwart** [comment]
Closing this one. The issue will be tracked in hazelcast/hazelcast-reference-manual#338
