### ISSUE TITLE
AwsCloudDiscoveryTest

### ISSUE THREAD

**Issue by Donnerbart** [hazelcast/hazelcast#11571]
**com.hazelcast.client.discovery.AwsCloudDiscoveryTest.testAwsAddressProvider**
```java
java.lang.IllegalStateException: Unable to connect to any address in the config! The following addresses were tried: [[172.30.0.181]:5701, [172.30.0.181]:5702, [172.30.0.181]:5703]
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.connectToClusterInternal(ClientConnectionManagerImpl.java:864)
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.access$1500(ClientConnectionManagerImpl.java:101)
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl$3.call(ClientConnectionManagerImpl.java:874)
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl$3.call(ClientConnectionManagerImpl.java:870)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
```
https://hazelcast-l337.ci.cloudbees.com/view/Sonar/job/Hazelcast-3.x-sonar/lastCompletedBuild/com.hazelcast$hazelcast-client/testReport/com.hazelcast.client.discovery/AwsCloudDiscoveryTest/testAwsAddressProvider/

**Comment by Donnerbart** [comment]
Suppressed via https://github.com/hazelcast/hazelcast/commit/5542075cbca9c0758806939566e5f88446a25aef
