### ISSUE TITLE
Wrong hazelcast-config XSD schema is used when minor major or minor has more than 1 digit

### ISSUE THREAD

**Issue by kwart** [hazelcast/hazelcast#11586]
Wrong hazelcast-config XSD schema is used when minor major or minor has more than 1 digit.

Currently a Member with default configuration is not able to start from the master branch (version `3.10-SNAPSHOT`), because it uses XSD for version `3.1`. 

The stack trace:

```
Exception in thread "main" com.hazelcast.core.HazelcastException: org.xml.sax.SAXParseException: src-resolve: Cannot resolve the name 'listener-base' to a(n) 'type definition' component.
	at com.hazelcast.util.ExceptionUtil$1.create(ExceptionUtil.java:40)
	at com.hazelcast.util.ExceptionUtil.peel(ExceptionUtil.java:124)
	at com.hazelcast.util.ExceptionUtil.peel(ExceptionUtil.java:69)
	at com.hazelcast.util.ExceptionUtil.rethrow(ExceptionUtil.java:129)
	at com.hazelcast.config.XmlConfigBuilder.build(XmlConfigBuilder.java:218)
	at com.hazelcast.config.XmlConfigBuilder.build(XmlConfigBuilder.java:209)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:121)
	at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:92)
	at ClientServer.main(ClientServer.java:24)
Caused by: org.xml.sax.SAXParseException: src-resolve: Cannot resolve the name 'listener-base' to a(n) 'type definition' component.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:195)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:131)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:384)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.reportSchemaErr(XSDHandler.java:2537)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.reportSchemaError(XSDHandler.java:2528)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.getGlobalDecl(XSDHandler.java:1472)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDComplexTypeTraverser.traverseSimpleContent(XSDComplexTypeTraverser.java:373)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDComplexTypeTraverser.traverseComplexTypeDecl(XSDComplexTypeTraverser.java:249)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDComplexTypeTraverser.traverseGlobal(XSDComplexTypeTraverser.java:160)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.traverseSchemas(XSDHandler.java:1255)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.parseSchema(XSDHandler.java:579)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadSchema(XMLSchemaLoader.java:556)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadGrammar(XMLSchemaLoader.java:523)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadGrammar(XMLSchemaLoader.java:489)
	at com.sun.org.apache.xerces.internal.jaxp.validation.XMLSchemaFactory.newSchema(XMLSchemaFactory.java:224)
	at com.hazelcast.config.AbstractXmlConfigHelper.schemaValidation(AbstractXmlConfigHelper.java:183)
	at com.hazelcast.config.XmlConfigBuilder.parseAndBuildConfig(XmlConfigBuilder.java:235)
	at com.hazelcast.config.XmlConfigBuilder.build(XmlConfigBuilder.java:216)
	... 4 more
```

**Comment by mmedenjak** [comment]
Nice observation!

**Comment by Donnerbart** [comment]
Woohoo, good catch!
