### ISSUE TITLE
LiteMemberClientMapNearCacheBasicTest.whenLoadAllIsUsed_thenNearCacheIsInvalidated_onDataAdapter

### ISSUE THREAD

**Issue by ahmetmircik** [hazelcast/hazelcast#11637]
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/11291/testReport/junit/com.hazelcast.client.map.impl.nearcache/LiteMemberClientMapNearCacheBasicTest/whenLoadAllIsUsed_thenNearCacheIsInvalidated_onDataAdapter_format_BINARY_serializeKeys_true_/

**Comment by tombujok** [comment]
@ahmetmircik is it an easy fix? will you address it in 3.9.1?

**Comment by hasancelik** [comment]
*master*
```
java.lang.AssertionError: Invalidation is not working on loadAll() Near Cache owned entry count didn't reach the desired value (0 vs. -1) (NearCacheStatsImpl{ownedEntryCount=-1, ownedEntryMemoryCost=-153, creationTime=1514683818372, hits=0, misses=1000, ratio=0.0%, evictions=0, expirations=0, lastPersistenceTime=0, persistenceCount=0, lastPersistenceDuration=0, lastPersistenceWrittenBytes=0, lastPersistenceKeyCount=0, lastPersistenceFailure=''}) expected:<0> but was:<-1>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils.assertNearCacheSize(NearCacheTestUtils.java:432)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils$4.run(NearCacheTestUtils.java:448)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1149)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1166)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils.assertNearCacheSizeEventually(NearCacheTestUtils.java:445)
	at com.hazelcast.internal.nearcache.AbstractNearCacheBasicTest.whenEntryIsLoaded_thenNearCacheShouldBeInvalidated(AbstractNearCacheBasicTest.java:1033)
	at com.hazelcast.internal.nearcache.AbstractNearCacheBasicTest.whenLoadAllIsUsed_thenNearCacheIsInvalidated_onDataAdapter(AbstractNearCacheBasicTest.java:908)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

https://hazelcast-l337.ci.cloudbees.com/view/Sonar/job/Hazelcast-3.x-sonar/com.hazelcast$hazelcast-client/1740/testReport/junit/com.hazelcast.client.map.impl.nearcache/LiteMemberClientMapNearCacheBasicTest/whenLoadAllIsUsed_thenNearCacheIsInvalidated_onDataAdapter_format_BINARY_serializeKeys_true_/

**Comment by jerrinot** [comment]
interesting: "ownedEntryCount=-1" :)

**Comment by jerrinot** [comment]
no failure since Jan, closing
