### ISSUE TITLE
[transaction] [queue] TransactionQueueTest.testIssue859And863_WhenInQueueOnSecondInstance_OutQueueOnFirstInstance

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#11647]
```
java.lang.AssertionError: expected:<3000> but was:<2998>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.collection.impl.txnqueue.TransactionQueueTest$5.run(TransactionQueueTest.java:395)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1129)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1146)
	at com.hazelcast.collection.impl.txnqueue.TransactionQueueTest.testIssue859And863(TransactionQueueTest.java:392)
	at com.hazelcast.collection.impl.txnqueue.TransactionQueueTest.testIssue859And863_WhenInQueueOnSecondInstance_OutQueueOnFirstInstance(TransactionQueueTest.java:358)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-freestyle/1211/testReport/junit/com.hazelcast.collection.impl.txnqueue/TransactionQueueTest/testIssue859And863_WhenInQueueOnSecondInstance_OutQueueOnFirstInstance/

**Comment by jerrinot** [comment]
no failure since October, closing.

**Comment by mdogan** [comment]
😱 1st failure in two years! https://github.com/hazelcast/hazelcast/pull/17090#issuecomment-644664627

**Comment by mdogan** [comment]
A new failure: http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/2172/testReport/junit/com.hazelcast.collection.impl.txnqueue/TransactionQueueTest/testIssue859And863_WhenQueuesAreOnSecondInstance_comparatorClassName__null_/

```
java.lang.AssertionError: expected:<3000> but was:<2999>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.collection.impl.txnqueue.TransactionQueueTest.lambda$testIssue859And863$4(TransactionQueueTest.java:411)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1248)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1350)
	at com.hazelcast.collection.impl.txnqueue.TransactionQueueTest.testIssue859And863(TransactionQueueTest.java:410)
	at com.hazelcast.collection.impl.txnqueue.TransactionQueueTest.testIssue859And863_WhenQueuesAreOnSecondInstance(TransactionQueueTest.java:349)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by pivovarit** [comment]
Failed again here: https://github.com/hazelcast/hazelcast/pull/17452

```
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   TransactionQueueTest.testIssue859And863_WhenInQueueOnSecondInstance_OutQueueOnFirstInstance:375->testIssue859And863:410->HazelcastTestSupport.assertTrueEventually:1350->HazelcastTestSupport.assertTrueEventually:1248->lambda$testIssue859And863$4:411 expected:<3000> but was:<2998>
[INFO] 
[ERROR] Tests run: 31485, Failures: 1, Errors: 0, Skipped: 977
[INFO] 
[ERROR] There are test failures.
```

**Comment by mmedenjak** [comment]
Looks like this is an artifact of our invocation system being at-least-once. The `TxnReservePollOperation` is invoked [here](https://github.com/hazelcast/hazelcast/blob/416f627ea1a0cada60dd781bddb93fc545ef3940/hazelcast/src/main/java/com/hazelcast/collection/impl/txnqueue/TransactionalQueueProxySupport.java#L140-L141) and it assumes it will only run once. In fact, it runs twice and manages to remove two items from the queue and adds both in the transaction map in `QueueContainer#txnPollReserve`. 

But, it only returns one response and that is the queue item that gets transferred to another queue which is the intent of the whole transaction.

I'm inclined to leave this as a known issue. We might invest into de-duplicating transaction operations but I don't think it's worth it. Transactions have other issues and we'd better invest time into a redesign.

We might also invest time into deduplicating all invocations, but that's also a bigger undertaking and I'm not sure if we have any strong reason to do so other than transactions, which should be redesigned in the first place.

**Comment by mmedenjak** [comment]
Other similar issues: https://github.com/hazelcast/hazelcast/issues/11839 and https://github.com/hazelcast/hazelcast/issues/12952.
