### ISSUE TITLE
[ringbuffer] Ringbuffer access throws HazelcastInstanceNotActiveException when cluster state is PASSIVE

### ISSUE THREAD

**Issue by nlwillia** [hazelcast/hazelcast#11664]
In version 3.9, I'm trying to use read-only methods of a Ringbuffer while the cluster state is PASSIVE.  ex: `size` or `headSequence` or `read`, but `HazelcastInstanceNotActiveException` is being thrown.  According to the [reference docs](http://docs.hazelcast.org/docs/3.9/manual/html-single/index.html#cluster-states), read-only methods should be permitted.

````
trace:     com.hazelcast.core.HazelcastInstanceNotActiveException: State: PASSIVE Operation: class com.hazelcast.ringbuffer.impl.operations.GenericOperation
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.engineActive(Invocation.java:490)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:523)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:513)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:207)
	at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.invokeOnPartition(OperationServiceImpl.java:318)
	at com.hazelcast.spi.AbstractDistributedObject.invokeOnPartition(AbstractDistributedObject.java:72)
	at com.hazelcast.ringbuffer.impl.RingbufferProxy.headSequence(RingbufferProxy.java:111)
````

**Comment by mmedenjak** [comment]
This should be easy to fix. We will do so in 3.9.1. Thanks for reporting!

**Comment by tombujok** [comment]
@mmedenjak will you address it in 3.9.1?

**Comment by mmedenjak** [comment]
@tombujok sure, I'll do so ASAP

**Comment by mmedenjak** [comment]
Postponed until 3.9.2
