### ISSUE TITLE
[scheduled-executor] ScheduledExecutorServiceSlowTest.schedule_thenDisposeLeakTest

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#11683]
```
org.junit.runners.model.TestTimedOutException: test timed out after 600000 milliseconds
	at java.lang.System.identityHashCode(Native Method)
	at java.io.ObjectOutputStream$HandleTable.hash(ObjectOutputStream.java:2360)
	at java.io.ObjectOutputStream$HandleTable.insert(ObjectOutputStream.java:2323)
	at java.io.ObjectOutputStream$HandleTable.assign(ObjectOutputStream.java:2281)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1428)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at com.hazelcast.internal.serialization.impl.JavaDefaultSerializers$JavaSerializer.write(JavaDefaultSerializers.java:242)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.write(StreamSerializerAdapter.java:43)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.writeObject(AbstractSerializationService.java:250)
	at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataOutput.writeObject(ByteArrayObjectDataOutput.java:370)
	at com.hazelcast.scheduledexecutor.impl.TaskDefinition.writeData(TaskDefinition.java:119)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.write(DataSerializableSerializer.java:201)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.write(DataSerializableSerializer.java:50)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.write(StreamSerializerAdapter.java:43)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.writeObject(AbstractSerializationService.java:250)
	at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataOutput.writeObject(ByteArrayObjectDataOutput.java:370)
	at com.hazelcast.scheduledexecutor.impl.operations.ScheduleTaskOperation.writeInternal(ScheduleTaskOperation.java:60)
	at com.hazelcast.spi.Operation.writeData(Operation.java:565)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.write(DataSerializableSerializer.java:201)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.write(DataSerializableSerializer.java:50)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.write(StreamSerializerAdapter.java:43)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:152)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:128)
	at com.hazelcast.spi.impl.operationservice.impl.OutboundOperationHandler.send(OutboundOperationHandler.java:51)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeRemote(Invocation.java:574)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:552)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:513)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:207)
	at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.invokeOnPartition(OperationServiceImpl.java:318)
	at com.hazelcast.spi.AbstractDistributedObject.invokeOnPartition(AbstractDistributedObject.java:72)
	at com.hazelcast.scheduledexecutor.impl.ScheduledExecutorServiceProxy.submitOnPartitionSync(ScheduledExecutorServiceProxy.java:428)
	at com.hazelcast.scheduledexecutor.impl.ScheduledExecutorServiceProxy.schedule(ScheduledExecutorServiceProxy.java:110)
	at com.hazelcast.scheduledexecutor.ScheduledExecutorServiceSlowTest.schedule_thenDisposeLeakTest(ScheduledExecutorServiceSlowTest.java:423)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-nightly/com.hazelcast$hazelcast/1384/testReport/junit/com.hazelcast.scheduledexecutor/ScheduledExecutorServiceSlowTest/schedule_thenDisposeLeakTest/

**Comment by hasancelik** [comment]
*maintenance*
**ClientScheduledExecutorServiceSlowTest.schedule_thenDisposeLeakTest**
```
org.junit.runners.model.TestTimedOutException: test timed out after 600000 milliseconds
	at sun.misc.Unsafe.unpark(Native Method)
	at java.util.concurrent.locks.LockSupport.unpark(LockSupport.java:141)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.unparkSuccessor(AbstractQueuedSynchronizer.java:662)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.release(AbstractQueuedSynchronizer.java:1264)
	at java.util.concurrent.locks.ReentrantLock.unlock(ReentrantLock.java:457)
	at java.util.concurrent.LinkedBlockingQueue.signalNotEmpty(LinkedBlockingQueue.java:176)
	at java.util.concurrent.LinkedBlockingQueue.offer(LinkedBlockingQueue.java:430)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1371)
	at java.util.concurrent.Executors$DelegatedExecutorService.execute(Executors.java:668)
	at com.hazelcast.client.test.TwoWayBlockableExecutor.executeOutgoing(TwoWayBlockableExecutor.java:115)
	at com.hazelcast.client.test.TestClientRegistry$MockedClientConnection.write(TestClientRegistry.java:254)
	at com.hazelcast.client.spi.impl.AbstractClientInvocationService.writeToConnection(AbstractClientInvocationService.java:141)
	at com.hazelcast.client.spi.impl.AbstractClientInvocationService.send(AbstractClientInvocationService.java:123)
	at com.hazelcast.client.spi.impl.SmartClientInvocationService.invokeOnPartitionOwner(SmartClientInvocationService.java:46)
	at com.hazelcast.client.spi.impl.ClientInvocation.invokeOnSelection(ClientInvocation.java:150)
	at com.hazelcast.client.spi.impl.ClientInvocation.invoke(ClientInvocation.java:133)
	at com.hazelcast.client.proxy.ClientScheduledExecutorProxy.scheduleOnPartition(ClientScheduledExecutorProxy.java:347)
	at com.hazelcast.client.proxy.ClientScheduledExecutorProxy.schedule(ClientScheduledExecutorProxy.java:103)
	at com.hazelcast.scheduledexecutor.ScheduledExecutorServiceSlowTest.schedule_thenDisposeLeakTest(ScheduledExecutorServiceSlowTest.java:423)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-nightly/com.hazelcast$hazelcast-client/1434/testReport/junit/com.hazelcast.client.scheduledexecutor/ClientScheduledExecutorServiceSlowTest/schedule_thenDisposeLeakTest/



**ScheduledExecutorServiceSlowTest.schedule_thenDisposeLeakTest**
```
org.junit.runners.model.TestTimedOutException: test timed out after 600000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:304)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:153)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.join(AbstractInvocationFuture.java:136)
	at com.hazelcast.scheduledexecutor.impl.ScheduledExecutorServiceProxy.submitOnPartitionSync(ScheduledExecutorServiceProxy.java:428)
	at com.hazelcast.scheduledexecutor.impl.ScheduledExecutorServiceProxy.schedule(ScheduledExecutorServiceProxy.java:110)
	at com.hazelcast.scheduledexecutor.ScheduledExecutorServiceSlowTest.schedule_thenDisposeLeakTest(ScheduledExecutorServiceSlowTest.java:423)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-nightly/com.hazelcast$hazelcast/1437/testReport/junit/com.hazelcast.scheduledexecutor/ScheduledExecutorServiceSlowTest/schedule_thenDisposeLeakTest/

**Comment by hasancelik** [comment]
*maintenance*
```
org.junit.runners.model.TestTimedOutException: test timed out after 600000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:304)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:153)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.join(AbstractInvocationFuture.java:136)
	at com.hazelcast.scheduledexecutor.impl.ScheduledExecutorServiceProxy.submitOnPartitionSync(ScheduledExecutorServiceProxy.java:428)
	at com.hazelcast.scheduledexecutor.impl.ScheduledExecutorServiceProxy.schedule(ScheduledExecutorServiceProxy.java:110)
	at com.hazelcast.scheduledexecutor.ScheduledExecutorServiceSlowTest.schedule_thenDisposeLeakTest(ScheduledExecutorServiceSlowTest.java:423)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-nightly/com.hazelcast$hazelcast/1457/testReport/junit/com.hazelcast.scheduledexecutor/ScheduledExecutorServiceSlowTest/schedule_thenDisposeLeakTest/

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-nightly/com.hazelcast$hazelcast/1458/testReport/junit/com.hazelcast.scheduledexecutor/ScheduledExecutorServiceSlowTest/schedule_thenDisposeLeakTest/

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-nightly/com.hazelcast$hazelcast/1460/testReport/junit/com.hazelcast.scheduledexecutor/ScheduledExecutorServiceSlowTest/schedule_thenDisposeLeakTest/

**Comment by sancar** [comment]
I could not figure out the problem. Here are my findings:

Test is not able to finish in 30 minutes during nightly builds. It is taking at most 3 minutes in local. 
Since health monitor logs shows some major gc, I made the test run longer to see if memory grows over time, there seems to be no problem. 

```
18394: 02:24:20,783  INFO |schedule_thenDisposeLeakTest| - [HealthMonitor] hz._hzInstance_1510_dev.HealthMonitor - [127.0.0.1]:16208 [dev] [3.9.3-SNAPSHOT] processors=16, physical.memory.total=16.0G, physical.memory.free=0, swap.space.total=4.0G, swap.space.free=4.0G, heap.memory.used=747.8M, heap.memory.free=199.2M, heap.memory.total=947.0M, heap.memory.max=947.0M, heap.memory.used/total=78.85%, heap.memory.used/max=78.85%, minor.gc.count=15210, minor.gc.time=210661ms, major.gc.count=470, major.gc.time=2572269ms, load.process=0.00%, load.system=0.00%, load.systemAverage=716.00%, thread.count=191, thread.peakCount=1686, cluster.timeDiff=0, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=24, executor.q.priorityOperation.size=0, operations.completed.count=2585192, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=6, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=13, proxy.count=0, clientEndpoint.count=0, connection.active.count=0, client.connection.count=0, connection.count=0
 18418: 02:24:42,025  INFO |schedule_thenDisposeLeakTest| - [HealthMonitor] hz._hzInstance_1510_dev.HealthMonitor - [127.0.0.1]:16208 [dev] [3.9.3-SNAPSHOT] processors=16, physical.memory.total=16.0G, physical.memory.free=0, swap.space.total=4.0G, swap.space.free=4.0G, heap.memory.used=747.9M, heap.memory.free=199.1M, heap.memory.total=947.0M, heap.memory.max=947.0M, heap.memory.used/total=78.88%, heap.memory.used/max=78.88%, minor.gc.count=15210, minor.gc.time=210661ms, major.gc.count=473, major.gc.time=2592638ms, load.process=0.00%, load.system=0.40%, load.systemAverage=663.00%, thread.count=191, thread.peakCount=1686, cluster.timeDiff=-1, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=7, executor.q.priorityOperation.size=0, operations.completed.count=2607627, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=14, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=15, proxy.count=0, clientEndpoint.count=0, connection.active.count=0, client.connection.count=0, connection.count=0
 ```

Problem is also not specific to client/server, both of them timing out.

**Comment by sancar** [comment]
A problem I see that, these tests are running parallel. Since these are consuming a lot of memory, it could be the case that memory starting to be problem. I will switch them to serial tests for now.

**Comment by sancar** [comment]
Closed by mistake.  The commit https://github.com/hazelcast/hazelcast/commit/c97a629ccbabbd55252bf2cab77b36c8036b265b  is not related to this issue.

**Comment by sancar** [comment]
Made below fixes as fix attempt. 
https://github.com/hazelcast/hazelcast/pull/12140
https://github.com/hazelcast/hazelcast/pull/12141

I made the change because memory seems to be the problem when tests are running in parallel. If it fails again, we can suspect other things. Closing for now.
