### ISSUE TITLE
TCP discovery with public-address specified doesn't handle correctly member shutdowns

### ISSUE THREAD

**Issue by kwart** [hazelcast/hazelcast#11701]
I see "Connection reset by peer exceptions" in the (active) member log after one of Hazelcast members shuts down in my  Docker environment.

### Environment
Docker host runs 2 containers with Hazelcast members. Both have configured TCP discovery and hosts public address. The Hazelcast port is exposed to the Docker host.

#### hazelcast.xml
```xml
<port auto-increment="false" port-count="100">5701</port>
<public-address>${hazelcast.public.ip}:${hazelcast.port}</public-address>
<join>
    <multicast enabled="false">
    </multicast>
    <tcp-ip enabled="true">
        <member>${hazelcast.public.ip}:5555</member>
        <member>${hazelcast.public.ip}:5556</member>
    </tcp-ip>
   ...
</join>
```

#### Start Docker containers
```bash
docker run -it --rm -p 5555:5701 hazelcast-tcp
docker run -it --rm -p 5556:5701 hazelcast-tcp
```

#### Start Hazelcast in the containers
Provide system properties used in `hazelcast.xml` (public Docker host IP address and the port - 5555 and 5556):
```
System.setProperty("hazelcast.public.ip", "192.168.1.105");  // replace the IP value with your own IP
System.setProperty("hazelcast.port", "5555");  // for the second container use 5556
hz = Hazelcast.newHazelcastInstance();
```

#### Shut down one of the containers
```java
hz.shutdown();
```

#### Check the log in the running container
The remaining cluster member try to connect to the stopped one and log contains bunch of entries similar to:
```
Oct 31, 2017 12:14:55 PM com.hazelcast.nio.tcp.TcpIpConnector
INFO: [192.168.1.105]:5555 [dev] [3.9] Connecting to /192.168.1.105:5556, timeout: 0, bind-any: true
Oct 31, 2017 12:14:55 PM com.hazelcast.nio.tcp.TcpIpConnectionManager
INFO: [192.168.1.105]:5555 [dev] [3.9] Established socket connection between /172.17.0.3:56203 and /192.168.1.105:5556
Oct 31, 2017 12:14:55 PM com.hazelcast.nio.tcp.TcpIpConnection
INFO: [192.168.1.105]:5555 [dev] [3.9] Connection[id=24, /172.17.0.3:56203->/192.168.1.105:5556, endpoint=[192.168.1.105]:5556, alive=false, type=NONE] closed. Reason: Connection closed by the other side
Oct 31, 2017 12:14:55 PM com.hazelcast.nio.tcp.TcpIpConnector
INFO: [192.168.1.105]:5555 [dev] [3.9] Connecting to /192.168.1.105:5556, timeout: 0, bind-any: true
Oct 31, 2017 12:14:55 PM com.hazelcast.nio.tcp.TcpIpConnectionManager
INFO: [192.168.1.105]:5555 [dev] [3.9] Established socket connection between /172.17.0.3:53561 and /192.168.1.105:5556
Oct 31, 2017 12:14:55 PM com.hazelcast.nio.tcp.TcpIpConnection
WARNING: [192.168.1.105]:5555 [dev] [3.9] Connection[id=25, /172.17.0.3:53561->/192.168.1.105:5556, endpoint=[192.168.1.105]:5556, alive=false, type=NONE] closed. Reason: Exception in Connection[id=25, /172.17.0.3:53561->/192.168.1.105:5556, endpoint=[192.168.1.105]:5556, alive=true, type=NONE], thread=hz._hzInstance_1_dev.IO.thread-in-0
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:197)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at com.hazelcast.internal.networking.AbstractChannel.read(AbstractChannel.java:94)
	at com.hazelcast.nio.tcp.MemberChannelInitializer.inboundProtocol(MemberChannelInitializer.java:101)
	at com.hazelcast.nio.tcp.MemberChannelInitializer.initInbound(MemberChannelInitializer.java:73)
	at com.hazelcast.internal.networking.nio.NioChannelReader.init(NioChannelReader.java:143)
	at com.hazelcast.internal.networking.nio.NioChannelReader.handle(NioChannelReader.java:123)
	at com.hazelcast.internal.networking.nio.NioThread.handleSelectionKey(NioThread.java:401)
	at com.hazelcast.internal.networking.nio.NioThread.handleSelectionKeys(NioThread.java:386)
	at com.hazelcast.internal.networking.nio.NioThread.selectLoop(NioThread.java:293)
	at com.hazelcast.internal.networking.nio.NioThread.run(NioThread.java:248)
```

**Comment by kwart** [comment]
I've created a public docker image which shows the issue:

Run 2 nodes (in different consoles):
```bash
docker run -it --rm -p 5555:5701 kwart/hazelcast-reproducers:tcp-ip-shutdown
docker run -it --rm -p 5556:5701 kwart/hazelcast-reproducers:tcp-ip-shutdown
```

In each docker container run `hz` command (bash function) and provide public docker host IP and the public port. E.g.
```bash
hz 192.168.1.105 5555
```

Groovy shell will be started by this commands. And the `hz` variable is initialized to be a Hazelcast instance.

In one docker console window run:
```java
hz.shutdown();
```

Look into the log of another member - it should show the exception.

**Comment by mdogan** [comment]
Can this behaviour caused by docker?

When I stop one the members (`10.216.1.39:5556`) via `hz.shutdown()` or `:q` (exit groovy shell), then other instance (`10.216.1.39:5555`) continuously tries to reconnect. Interestingly connection is established successfully but then it's reset by other peer. See;

```
Feb 27, 2018 11:07:32 AM com.hazelcast.nio.tcp.TcpIpConnector
INFO: [10.216.1.39]:5555 [dev] [3.9] Connecting to /10.216.1.39:5556, timeout: 0, bind-any: true
Feb 27, 2018 11:07:32 AM com.hazelcast.nio.tcp.TcpIpConnectionManager
INFO: [10.216.1.39]:5555 [dev] [3.9] Established socket connection between /172.17.0.2:44759 and /10.216.1.39:5556
Feb 27, 2018 11:07:32 AM com.hazelcast.nio.tcp.TcpIpConnection
INFO: [10.216.1.39]:5555 [dev] [3.9] Connection[id=28, /172.17.0.2:44759->/10.216.1.39:5556, endpoint=[10.216.1.39]:5556, alive=false, type=NONE] closed. Reason: Connection closed by the other side
Feb 27, 2018 11:07:32 AM com.hazelcast.nio.tcp.TcpIpConnector
INFO: [10.216.1.39]:5555 [dev] [3.9] Connecting to /10.216.1.39:5556, timeout: 0, bind-any: true
Feb 27, 2018 11:07:32 AM com.hazelcast.nio.tcp.TcpIpConnectionManager
INFO: [10.216.1.39]:5555 [dev] [3.9] Established socket connection between /172.17.0.2:38911 and /10.216.1.39:5556
Feb 27, 2018 11:07:32 AM com.hazelcast.nio.tcp.TcpIpConnection
INFO: [10.216.1.39]:5555 [dev] [3.9] Connection[id=29, /172.17.0.2:38911->/10.216.1.39:5556, endpoint=[10.216.1.39]:5556, alive=false, type=NONE] closed. Reason: Connection closed by the other side
Feb 27, 2018 11:07:35 AM com.hazelcast.nio.tcp.TcpIpConnector
INFO: [10.216.1.39]:5555 [dev] [3.9] Connecting to /10.216.1.39:5556, timeout: 0, bind-any: true
Feb 27, 2018 11:07:35 AM com.hazelcast.nio.tcp.TcpIpConnectionManager
INFO: [10.216.1.39]:5555 [dev] [3.9] Established socket connection between /172.17.0.2:48847 and /10.216.1.39:5556
Feb 27, 2018 11:07:35 AM com.hazelcast.nio.tcp.TcpIpConnection
INFO: [10.216.1.39]:5555 [dev] [3.9] Connection[id=30, /172.17.0.2:48847->/10.216.1.39:5556, endpoint=[10.216.1.39]:5556, alive=false, type=NONE] closed. Reason: Connection closed by the other side
Feb 27, 2018 11:07:35 AM com.hazelcast.nio.tcp.TcpIpConnector
INFO: [10.216.1.39]:5555 [dev] [3.9] Connecting to /10.216.1.39:5556, timeout: 0, bind-any: true
Feb 27, 2018 11:07:35 AM com.hazelcast.nio.tcp.TcpIpConnectionManager
INFO: [10.216.1.39]:5555 [dev] [3.9] Established socket connection between /172.17.0.2:40047 and /10.216.1.39:5556
Feb 27, 2018 11:07:35 AM com.hazelcast.nio.tcp.TcpIpConnection
WARNING: [10.216.1.39]:5555 [dev] [3.9] Connection[id=31, /172.17.0.2:40047->/10.216.1.39:5556, endpoint=[10.216.1.39]:5556, alive=false, type=NONE] closed. Reason: Exception in Connection[id=31, /172.17.0.2:40047->/10.216.1.39:5556, endpoint=[10.216.1.39]:5556, alive=true, type=NONE], thread=hz._hzInstance_1_dev.IO.thread-in-0
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:197)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at com.hazelcast.internal.networking.AbstractChannel.read(AbstractChannel.java:94)
	at com.hazelcast.nio.tcp.MemberChannelInitializer.inboundProtocol(MemberChannelInitializer.java:101)
	at com.hazelcast.nio.tcp.MemberChannelInitializer.initInbound(MemberChannelInitializer.java:73)
	at com.hazelcast.internal.networking.nio.NioChannelReader.init(NioChannelReader.java:143)
	at com.hazelcast.internal.networking.nio.NioChannelReader.handle(NioChannelReader.java:123)
	at com.hazelcast.internal.networking.nio.NioThread.handleSelectionKey(NioThread.java:401)
	at com.hazelcast.internal.networking.nio.NioThread.handleSelectionKeys(NioThread.java:386)
	at com.hazelcast.internal.networking.nio.NioThread.selectLoop(NioThread.java:293)
	at com.hazelcast.internal.networking.nio.NioThread.run(NioThread.java:248)
```

This `Established socket connection between...` and `Connection closed by the other side...` loop continues until member is kicked out by heartbeat failure detector.

```
Feb 27, 2018 11:08:20 AM com.hazelcast.internal.cluster.impl.ClusterHeartbeatManager
WARNING: [10.216.1.39]:5555 [dev] [3.9] Suspecting Member [10.216.1.39]:5556 - ba761542-04f0-47a0-a531-1dce5ac8f982 because it has not sent any heartbeats since 2018-02-27 11:07:19.674. Now: 2018-02-27 11:08:20.352, heartbeat timeout: 60000 ms, suspicion level: 1.00
```

Even though there's no jvm process running on 2nd node, (most probably) docker accepts the tcp connection and it's closed immediately.

When I stop 2nd docker container just after shutting down the Hazelcast node, 1st node detects its leave (`SocketException[Connection refused to address /10.216.1.39:5556]`) immediately.

```
INFO: [10.216.1.39]:5555 [dev] [3.9] Connecting to /10.216.1.39:5556, timeout: 0, bind-any: true
Feb 27, 2018 11:15:01 AM com.hazelcast.nio.tcp.TcpIpConnector
INFO: [10.216.1.39]:5555 [dev] [3.9] Could not connect to: /10.216.1.39:5556. Reason: SocketException[Connection refused to address /10.216.1.39:5556]
Feb 27, 2018 11:15:01 AM com.hazelcast.nio.tcp.TcpIpConnector
INFO: [10.216.1.39]:5555 [dev] [3.9] Connecting to /10.216.1.39:5556, timeout: 0, bind-any: true
Feb 27, 2018 11:15:01 AM com.hazelcast.nio.tcp.TcpIpConnector
INFO: [10.216.1.39]:5555 [dev] [3.9] Could not connect to: /10.216.1.39:5556. Reason: SocketException[Connection refused to address /10.216.1.39:5556]
Feb 27, 2018 11:15:01 AM com.hazelcast.nio.tcp.TcpIpConnector
INFO: [10.216.1.39]:5555 [dev] [3.9] Connecting to /10.216.1.39:5556, timeout: 0, bind-any: true
Feb 27, 2018 11:15:01 AM com.hazelcast.nio.tcp.TcpIpConnector
INFO: [10.216.1.39]:5555 [dev] [3.9] Could not connect to: /10.216.1.39:5556. Reason: SocketException[Connection refused to address /10.216.1.39:5556]
Feb 27, 2018 11:15:01 AM com.hazelcast.nio.tcp.TcpIpConnectionErrorHandler
WARNING: [10.216.1.39]:5555 [dev] [3.9] Removing connection to endpoint [10.216.1.39]:5556 Cause => java.net.SocketException {Connection refused to address /10.216.1.39:5556}, Error-Count: 5
Feb 27, 2018 11:15:01 AM com.hazelcast.internal.cluster.impl.MembershipManager
INFO: [10.216.1.39]:5555 [dev] [3.9] Removing Member [10.216.1.39]:5556 - 20199f4f-fdc6-407a-9408-c79973578752
```

**Comment by kwart** [comment]
It seems to be a Docker networking related issue.

When opening a connection from one container, it's accepted always if the second container is running, even if there nobody listening on the port.

```
root@1bdd732f10c9:/opt/hazelcast# nc -v 192.168.1.105 5556
(UNKNOWN) [192.168.1.105] 5556 (freeciv) open
```

When I stop the second container, the correct answer comes finally:
```
root@1bdd732f10c9:/opt/hazelcast# nc -v 192.168.1.105 5556
(UNKNOWN) [192.168.1.105] 5556 (freeciv) : Connection refused
```

If the connection test is not executed in the Docker container, then the result is correct when container is running without application listening on the port:
```
josef@test:~$ nc -v 192.168.1.105 5556
nc: connect to 192.168.1.105 port 5556 (tcp) failed: Connection refused
```

**Comment by mdogan** [comment]
@kwart: Is there any action for this issue on Hazelcast side?

**Comment by kwart** [comment]
@mdogan IMO there is nothing on our side now. I'll close this. If we find a solution within Hazelcast sources we can reopen.
