### ISSUE TITLE
Replace "should" with "have to" in exception messages

### ISSUE THREAD

**Issue by kwart** [hazelcast/hazelcast#11723]
Let's use "have to" (obligation) instead of "should" (advice) in exception messages.

Lots of configuration checks throw exceptions when a provided value is not allowed. The exception messages often say something like "[This field] should be a [non-negative integer]". As we are forcing a value range in such cases by throwing an exception, we should rather use "[This field] has to be a [non-negative integer]" message.

Example exeption:
```
Exception in thread "main" java.lang.IllegalArgumentException: Capacity should be greater than 0
	at com.hazelcast.util.Preconditions.checkPositive(Preconditions.java:198)
	at com.hazelcast.config.DurableExecutorConfig.setCapacity(DurableExecutorConfig.java:156)
```

**Comment by Holmistr** [comment]
To be honest, is it really worth the effort? :D I know it's a trivial change, however probably on so many places and I don't see a lot of value gained by addressing this. @mmedenjak WDYT?

**Comment by mmedenjak** [comment]
Agree. We can leave it but I lowered the priority to low.

**Comment by Holmistr** [comment]
To be honest, I was thinking if we shouldn't close this issue completely. I'm usually against these minor things that don't really bring any value, only a commit with lots of line changes. @kwart Do you strongly believe that this is a good thing? If you and @mmedenjak I would vote from closing this issue without addressing it.

**Comment by mmedenjak** [comment]
I have no strong opinion on this one. True, it would change a lot of lines. We have "should" 166 times in production code and 506 times in test code. Feel free to close or leave open after the discussion.

**Comment by Donnerbart** [comment]
I would as @Serdaro what's the better phrasing and unify it according to his advice.

**Comment by Serdaro** [comment]
@kwart , @Holmistr , @mmedenjak , @Donnerbart ;
I went through some resources including some of our competitors Javadocs and StackOverflow, and in that particular case (giving the solution in the exception message), the exception message generally uses "must". 
For example:
`.......IllegalArgumentException: Capacity must be greater than 0`.

If you consider changing the tone, thus the degree of obligation, I would (also personally) prefer using "must".

**Comment by ndeevy** [comment]
Hi @kwart if this is still needing to be done, can I try to address it for hacktoberfest?
In my tech writing day job we use the IBM Style Guide, which says: 
"Always prefer a more direct verb or way of saying something. Omit “should,” or use “must” or “might,” as appropriate." so usually replace should with must to be more prescriptive.
Thanks!

**Comment by kwart** [comment]
@ndeevy Sure, there are still places that need to be fixed. So if you take it, it will be great!
Thank you.

**Comment by mmedenjak** [comment]
Sure @ndeevy , go ahead. Currently we're a bit tight on schedule with the 4.1 release, which should be out in a few weeks but we'll definitely appreciate this PR.

**Comment by ndeevy** [comment]
> @ndeevy Sure, there are still places that need to be fixed. So if you take it, it will be great!
> Thank you.
Thanks @kwart well, after an initial search of the repo I'm not sure where to find exception messages. I found lots of instances where replacing should might improve user focus and being prescriptive but not specifically exception messages. Could you point me in the right direction (otherwise I might be out of my depth and can leave this open for someone else). Thanks :)

**Comment by kwart** [comment]
I would start with a command similar to:
```bash
git grep should | grep Exception | grep -v '/test/'
```

It gives a list similar to:
```
$ git grep should|grep Exception|grep -v '/test/'
hazelcast-sql/src/main/java/com/hazelcast/sql/impl/calcite/opt/physical/index/IndexResolver.java:            throw new IllegalStateException("The operation should not be called.");
hazelcast/src/main/java/com/hazelcast/client/UndefinedErrorCodeException.java: * For the client to be able to recreate original exception it should be available on the classpath and
hazelcast/src/main/java/com/hazelcast/client/UndefinedErrorCodeException.java: * it should have one of the following constructors publicly.
hazelcast/src/main/java/com/hazelcast/client/config/ClientConfigXmlGenerator.java:            throw new IllegalArgumentException("Indent should be greater than 0");
hazelcast/src/main/java/com/hazelcast/client/config/impl/QueryCacheYamlConfigBuilderHelper.java:            throw new InvalidConfigurationException("Either class-name and sql should be defined for the predicate of map "
hazelcast/src/main/java/com/hazelcast/client/config/impl/YamlClientFailoverDomConfigProcessor.java:            throw new InvalidConfigurationException(String.format("At least one client configuration should be defined "
hazelcast/src/main/java/com/hazelcast/client/impl/clientside/ClientExceptionFactory.java:            assert checkClassNameForValidity(className) : "Exception should be defined in the protocol : " + className;
hazelcast/src/main/java/com/hazelcast/client/impl/clientside/ClientExceptionFactory.java:     * hazelcast and jdk exceptions should always be defined
hazelcast/src/main/java/com/hazelcast/client/impl/clientside/FailoverClientConfigSupport.java:            throw new InvalidConfigurationException("ClientFailoverConfig should have at least one client config.");
hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/scheduledexecutor/ScheduledExecutorTaskGetResultFromPartitionMessageTask.java:     * Exceptions may be wrapped in ExecutionExceptionDecorator, the wrapped ExecutionException should be sent to
hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/scheduledexecutor/ScheduledExecutorTaskGetResultFromTargetMessageTask.java:     * Exceptions may be wrapped in ExecutionExceptionDecorator, the wrapped ExecutionException should be sent to
hazelcast/src/main/java/com/hazelcast/config/AbstractCacheConfig.java:     * @throws NullPointerException should the key or value type be null
hazelcast/src/main/java/com/hazelcast/config/CacheConfiguration.java:     * @throws NullPointerException should the key or value type be {@code null}
hazelcast/src/main/java/com/hazelcast/config/MapStoreConfig.java:            throw new IllegalArgumentException("Write batch size should be at least 1");
hazelcast/src/main/java/com/hazelcast/core/RuntimeInterruptedException.java: * that don't have InterruptedException in their signatures. Users should be able to catch and handle
hazelcast/src/main/java/com/hazelcast/internal/ascii/memcache/BulkGetCommandProcessor.java:        throw new UnsupportedOperationException("not used, this method should be removed from the interface");
hazelcast/src/main/java/com/hazelcast/internal/ascii/rest/HttpPostCommand.java:            throw new IllegalStateException("'\\n' should follow '\\r', but got '" + (char) b + "'");
hazelcast/src/main/java/com/hazelcast/internal/cluster/impl/ClusterJoinManager.java:            throw new IllegalArgumentException("Addresses should be different! This: "
hazelcast/src/main/java/com/hazelcast/internal/cluster/impl/TcpIpJoiner.java:            throw new IllegalArgumentException(String.format("%s should be greater than zero! Current value: %d",
hazelcast/src/main/java/com/hazelcast/internal/config/ConfigValidator.java:     * should throw {@link IllegalArgumentException} in case of invalid configuration.
hazelcast/src/main/java/com/hazelcast/internal/config/DomVariableReplacer.java:     *                 InvalidConfigurationException} should be thrown if no
hazelcast/src/main/java/com/hazelcast/internal/config/YamlMemberDomConfigProcessor.java:            throw new InvalidConfigurationException("Either class-name and sql should be defined for the predicate of map "
hazelcast/src/main/java/com/hazelcast/internal/json/NonTerminalJsonValue.java:        throw new HazelcastException("This object should not be encoded");
hazelcast/src/main/java/com/hazelcast/internal/networking/nio/NioPipeline.java:     * IOException should not be dealt with in the handle method but should
hazelcast/src/main/java/com/hazelcast/internal/nio/ClassLoaderUtil.java:            throw new UnsupportedOperationException("Irresolvable constructor should never be instantiated.");
hazelcast/src/main/java/com/hazelcast/internal/partition/PartitionServiceProxy.java:            throw new NullPointerException("Parameter member should not be null");
hazelcast/src/main/java/com/hazelcast/internal/partition/impl/CheckPartitionReplicaVersionTask.java:            throw new IllegalArgumentException("Replica index should be in range [1-"
hazelcast/src/main/java/com/hazelcast/internal/partition/impl/MigrationManager.java:                throw new IllegalStateException("Promotion migrations should be handled by "
hazelcast/src/main/java/com/hazelcast/internal/usercodedeployment/impl/ClassLocator.java:                // question: should we give up on loading at this point and simply throw ClassNotFoundException?
hazelcast/src/main/java/com/hazelcast/internal/util/Preconditions.java:            throw new IllegalArgumentException(object + " should be instanceof " + type.getName());
hazelcast/src/main/java/com/hazelcast/map/impl/mapstore/MapStoreContextFactory.java:            throw new UnsupportedOperationException("This method should not be called. No defined map store exists.");
hazelcast/src/main/java/com/hazelcast/map/impl/mapstore/MapStoreContextFactory.java:            throw new UnsupportedOperationException("This method should not be called. No defined map store exists.");
hazelcast/src/main/java/com/hazelcast/map/impl/mapstore/MapStoreContextFactory.java:            throw new UnsupportedOperationException("This method should not be called. No defined map store exists.");
hazelcast/src/main/java/com/hazelcast/map/impl/mapstore/MapStoreContextFactory.java:            throw new UnsupportedOperationException("This method should not be called. No defined map store exists.");
hazelcast/src/main/java/com/hazelcast/map/impl/mapstore/MapStoreContextFactory.java:            throw new UnsupportedOperationException("This method should not be called. No defined map store exists.");
hazelcast/src/main/java/com/hazelcast/map/impl/operation/EntryOperation.java:                throw new HazelcastException("EntryProcessor.getBackupProcessor() should return null if ReadOnly implemented");
hazelcast/src/main/java/com/hazelcast/query/impl/ConverterCache.java:            throw new UnsupportedOperationException("should never be called");
hazelcast/src/main/java/com/hazelcast/query/impl/predicates/PagingPredicateImpl.java:            throw new IllegalArgumentException("pageSize should be greater than 0!");
hazelcast/src/main/java/com/hazelcast/query/impl/predicates/SqlPredicate.java:            throw new IllegalArgumentException(String.format("%s should have a public default constructor", klass.getName()));
hazelcast/src/main/java/com/hazelcast/ringbuffer/impl/RingbufferService.java:            throw new NullPointerException("Ringbuffer config should not be null when ringbuffer is being created");
hazelcast/src/main/java/com/hazelcast/spi/exception/SilentException.java: * should log it on its own.
hazelcast/src/main/java/com/hazelcast/spi/impl/operationservice/ExceptionAction.java:     * Indicates that the exception should bubble up.
hazelcast/src/main/java/com/hazelcast/spi/impl/operationservice/impl/OperationBackupHandler.java:            throw new IllegalArgumentException("Backup operation should not be null! " + backupAwareOp);
hazelcast/src/main/java/com/hazelcast/spi/impl/operationservice/impl/PartitionInvocation.java:        if (shouldFailOnIndeterminateOperationState() && (t instanceof MemberLeftException)) {
hazelcast/src/main/java/com/hazelcast/spi/impl/proxyservice/impl/DistributedObjectFuture.java:            throw new IllegalArgumentException("Proxy should not be null!");
hazelcast/src/main/java/com/hazelcast/spi/impl/proxyservice/impl/DistributedObjectFuture.java:            throw new IllegalArgumentException("Error should not be null!");
hazelcast/src/main/java/com/hazelcast/sql/SqlStatement.java:            throw new IllegalArgumentException("Timeout should be non-negative or -1: " + timeout);
hazelcast/src/main/java/com/hazelcast/sql/SqlStatement.java:            throw new IllegalArgumentException("Cursor buffer size should be positive: " + cursorBufferSize);
hazelcast/src/main/java/com/hazelcast/sql/impl/type/converter/NullConverter.java:        throw new UnsupportedOperationException("should never be called");
```

Many of the lines are OK with "should", some cases can be fixed immediately. Some have to be reviewed in the context of the class.

**Comment by ndeevy** [comment]
Thanks @kwart ! I'll work on the list that command produced.
