### ISSUE TITLE
ClientRegressionWithMockNetworkTest.testDeadlock_WhenDoingOperationFromLifecycleListener

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#11738]
```
java.lang.AssertionError: CountDownLatch failed to complete within 120 seconds, count left: 1
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:1012)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:1005)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:997)
	at com.hazelcast.client.ClientRegressionWithMockNetworkTest.testDeadlock_WhenDoingOperationFromLifecycleListener(ClientRegressionWithMockNetworkTest.java:587)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-ZuluJDK8/com.hazelcast$hazelcast-client/266/testReport/junit/com.hazelcast.client/ClientRegressionWithMockNetworkTest/testDeadlock_WhenDoingOperationFromLifecycleListener/

**Comment by sancar** [comment]
fixed via https://github.com/hazelcast/hazelcast/pull/11698
