### ISSUE TITLE
[ZING] ProducerConsumerConditionStressTest.test

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#11739]
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.lang.Object.wait(Native Method)
	at java.lang.Thread.join(Thread.java:1289)
	at com.hazelcast.test.HazelcastTestSupport.assertJoinable(HazelcastTestSupport.java:844)
	at com.hazelcast.concurrent.lock.ProducerConsumerConditionStressTest.test(ProducerConsumerConditionStressTest.java:63)
```

https://hazelcast-l337.ci.cloudbees.com/view/Zing/job/Hazelcast-3.x-ZingJDK7/104/testReport/junit/com.hazelcast.concurrent.lock/ProducerConsumerConditionStressTest/test/

**Comment by mmedenjak** [comment]
@hasancelik I can't seem to find the logs here:
https://console.aws.amazon.com/s3/buckets/j-artifacts/?region=us-east-1&tab=overview&prefixSearch=Hazelcast-3.x-ZingJDK7

Are the logs stored under a different bucket or are they missing?

**Comment by taburet** [comment]
Looks like this failure is already fixed by https://github.com/hazelcast/hazelcast/commit/f5dbba5da3f413e6d6d9ee53b8d660da14f98ede. Closing.
