### ISSUE TITLE
ClientServiceTest.testClientListener_withShuttingDownOwnerMember

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#11737]
```
java.lang.AssertionError: expected:<1> but was:<2>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.client.ClientServiceTest$15.run(ClientServiceTest.java:535)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueAllTheTime(HazelcastTestSupport.java:1089)
	at com.hazelcast.client.ClientServiceTest.testClientListener_withShuttingDownOwnerMember(ClientServiceTest.java:532)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-ZuluJDK7-freestyle/9/testReport/junit/com.hazelcast.client/ClientServiceTest/testClientListener_withShuttingDownOwnerMember/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: expected:<1> but was:<2>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.client.ClientServiceTest$15.run(ClientServiceTest.java:537)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueAllTheTime(HazelcastTestSupport.java:1109)
	at com.hazelcast.client.ClientServiceTest.testClientListener_withShuttingDownOwnerMember(ClientServiceTest.java:534)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK1.6-freestyle/341/testReport/junit/com.hazelcast.client/ClientServiceTest/testClientListener_withShuttingDownOwnerMember/

**Comment by PavloBida** [comment]
```
java.lang.AssertionError: expected:<1> but was:<3>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at com.hazelcast.client.ClientServiceTest$12.run(ClientServiceTest.java:494)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueAllTheTime(HazelcastTestSupport.java:1206)
	at com.hazelcast.client.ClientServiceTest.testClientListener_withShuttingDownOwnerMember(ClientServiceTest.java:491)
```
http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-4.maintenance-IbmJDK8/115/testReport/junit/com.hazelcast.client/ClientServiceTest/testClientListener_withShuttingDownOwnerMember/

**Comment by sancar** [comment]
Should be fixed by https://github.com/hazelcast/hazelcast/pull/18040 
I have checked the commit and the test failure is before the above pr is merged. 
Closing for now. If we see a new failure we can reopen.
