### ISSUE TITLE
ReplicatedMapSplitBrainTest.testSplitBrain

### ISSUE THREAD

**Issue by kwart** [hazelcast/hazelcast#11758]
The test `com.hazelcast.replicatedmap.merge.ReplicatedMapSplitBrainTest.testSplitBrain[mergePolicy:class com.hazelcast.replicatedmap.merge.PutIfAbsentMapMergePolicy]` fails intermittently:

```
java.lang.AssertionError: expected:<PutIfAbsentValue2> but was:<null>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.replicatedmap.merge.ReplicatedMapSplitBrainTest.afterMergePutIfAbsentMapMergePolicy(ReplicatedMapSplitBrainTest.java:207)
	at com.hazelcast.replicatedmap.merge.ReplicatedMapSplitBrainTest.onAfterSplitBrainHealed(ReplicatedMapSplitBrainTest.java:124)
```

https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/11518/testReport/junit/com.hazelcast.replicatedmap.merge/ReplicatedMapSplitBrainTest/testSplitBrain_mergePolicy_class_com_hazelcast_replicatedmap_merge_PutIfAbsentMapMergePolicy_/

**Comment by Donnerbart** [comment]
Yeah, I introduced that test recently, since it was missing for the existing split-brain healing in the `ReplicatedMap`. It seems to fail spuriously on different merge policies. I have no idea why yet.

I also changed the test to add the values on all instances, so there should be no issue with waiting for the replication. I'm really not sure what's going on here.

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: expected:<higherHitsValue2> but was:<null>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.replicatedmap.merge.ReplicatedMapSplitBrainTest.afterMergeHigherHitsMapMergePolicy(ReplicatedMapSplitBrainTest.java:183)
	at com.hazelcast.replicatedmap.merge.ReplicatedMapSplitBrainTest.onAfterSplitBrainHealed(ReplicatedMapSplitBrainTest.java:115)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.7-freestyle/73/testReport/junit/com.hazelcast.replicatedmap.merge/ReplicatedMapSplitBrainTest/testSplitBrain_mergePolicy_class_com_hazelcast_replicatedmap_merge_HigherHitsMapMergePolicy_/

**Comment by hasancelik** [comment]
```
org.junit.ComparisonFailure: expected:<[higherHitsV]alue2> but was:<[v]alue2>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.replicatedmap.merge.ReplicatedMapSplitBrainTest.afterMergeHigherHitsMapMergePolicy(ReplicatedMapSplitBrainTest.java:179)
	at com.hazelcast.replicatedmap.merge.ReplicatedMapSplitBrainTest.onAfterSplitBrainHealed(ReplicatedMapSplitBrainTest.java:112)
```

https://hazelcast-l337.ci.cloudbees.com/view/Sonar/job/Hazelcast-3.x-sonar/com.hazelcast$hazelcast/1748/testReport/junit/com.hazelcast.replicatedmap.merge/ReplicatedMapSplitBrainTest/testSplitBrain_mergePolicy_class_com_hazelcast_replicatedmap_merge_HigherHitsMapMergePolicy_/

**Comment by Donnerbart** [comment]
Fixed via https://github.com/hazelcast/hazelcast/commit/f6b18cd699d49fe1fdb84da3a86c7072dda4f2b7
