### ISSUE TITLE
ClientDisconnectTest.testClientOperationCancelled_whenDisconnected_lock

### ISSUE THREAD

**Issue by kwart** [hazelcast/hazelcast#11757]
The test `com.hazelcast.client.ClientDisconnectTest.testClientOperationCancelled_whenDisconnected_lock` fails intermittently:

```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at org.junit.Assert.assertFalse(Assert.java:74)
	at com.hazelcast.client.ClientDisconnectTest$4.run(ClientDisconnectTest.java:116)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueAllTheTime(HazelcastTestSupport.java:1093)
	at com.hazelcast.client.ClientDisconnectTest.testClientOperationCancelled_whenDisconnected_lock(ClientDisconnectTest.java:113)
```

https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/11520/testReport/com.hazelcast.client/ClientDisconnectTest/testClientOperationCancelled_whenDisconnected_lock/

**Comment by hasancelik** [comment]
*testClientOperationCancelled_whenDisconnected*
```
java.lang.AssertionError: expected:<0> but was:<1>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.client.ClientDisconnectTest$2.run(ClientDisconnectTest.java:82)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueAllTheTime(HazelcastTestSupport.java:1093)
	at com.hazelcast.client.ClientDisconnectTest.testClientOperationCancelled_whenDisconnected(ClientDisconnectTest.java:79)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.8/com.hazelcast$hazelcast-client/773/testReport/junit/com.hazelcast.client/ClientDisconnectTest/testClientOperationCancelled_whenDisconnected/

**Comment by hasancelik** [comment]
*testClientOperationCancelled_whenDisconnected_lock*
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at org.junit.Assert.assertFalse(Assert.java:74)
	at com.hazelcast.client.ClientDisconnectTest$4.run(ClientDisconnectTest.java:116)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueAllTheTime(HazelcastTestSupport.java:1093)
	at com.hazelcast.client.ClientDisconnectTest.testClientOperationCancelled_whenDisconnected_lock(ClientDisconnectTest.java:113)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK1.6-freestyle/286/testReport/junit/com.hazelcast.client/ClientDisconnectTest/testClientOperationCancelled_whenDisconnected_lock/

**Comment by hasancelik** [comment]
*testClientOperationCancelled_whenDisconnected*
```
java.lang.AssertionError: expected:<0> but was:<1>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.client.ClientDisconnectTest$2.run(ClientDisconnectTest.java:82)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueAllTheTime(HazelcastTestSupport.java:1093)
	at com.hazelcast.client.ClientDisconnectTest.testClientOperationCancelled_whenDisconnected(ClientDisconnectTest.java:79)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-ZuluJDK8/com.hazelcast$hazelcast-client/753/testReport/junit/com.hazelcast.client/ClientDisconnectTest/testClientOperationCancelled_whenDisconnected/

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-ZuluJDK8/com.hazelcast$hazelcast-client/756/testReport/junit/com.hazelcast.client/ClientDisconnectTest/testClientOperationCancelled_whenDisconnected/

**Comment by hasancelik** [comment]
*maintenance*
**testClientOperationCancelled_whenDisconnected_lock**

```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at org.junit.Assert.assertFalse(Assert.java:74)
	at com.hazelcast.client.ClientDisconnectTest$4.run(ClientDisconnectTest.java:116)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueAllTheTime(HazelcastTestSupport.java:1089)
	at com.hazelcast.client.ClientDisconnectTest.testClientOperationCancelled_whenDisconnected_lock(ClientDisconnectTest.java:113)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-ZuluJDK8/com.hazelcast$hazelcast-client/270/testReport/junit/com.hazelcast.client/ClientDisconnectTest/testClientOperationCancelled_whenDisconnected_lock/

**Comment by Donnerbart** [comment]
**com.hazelcast.client.ClientDisconnectTest.testClientOperationCancelled_whenDisconnected_lock**
```java
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at org.junit.Assert.assertFalse(Assert.java:74)
	at com.hazelcast.client.ClientDisconnectTest$4.run(ClientDisconnectTest.java:116)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueAllTheTime(HazelcastTestSupport.java:1109)
	at com.hazelcast.client.ClientDisconnectTest.testClientOperationCancelled_whenDisconnected_lock(ClientDisconnectTest.java:113)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/11590/testReport/junit/com.hazelcast.client/ClientDisconnectTest/testClientOperationCancelled_whenDisconnected_lock/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at org.junit.Assert.assertFalse(Assert.java:74)
	at com.hazelcast.client.ClientDisconnectTest$4.run(ClientDisconnectTest.java:116)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueAllTheTime(HazelcastTestSupport.java:1093)
	at com.hazelcast.client.ClientDisconnectTest.testClientOperationCancelled_whenDisconnected_lock(ClientDisconnectTest.java:113)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK8/com.hazelcast$hazelcast-client/1363/testReport/junit/com.hazelcast.client/ClientDisconnectTest/testClientOperationCancelled_whenDisconnected_lock/

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK8/com.hazelcast$hazelcast-client/1366/testReport/junit/com.hazelcast.client/ClientDisconnectTest/testClientOperationCancelled_whenDisconnected_lock/

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK8/1367/com.hazelcast$hazelcast-client/testReport/com.hazelcast.client/ClientDisconnectTest/testClientOperationCancelled_whenDisconnected_lock/
