### ISSUE TITLE
[cluster] GracefulShutdownTest.shutdownMemberAndCluster_concurrently_withPartitionInitialization

### ISSUE THREAD

**Issue by Donnerbart** [hazelcast/hazelcast#11798]
**com.hazelcast.internal.partition.GracefulShutdownTest.shutdownMemberAndCluster_concurrently_withPartitionInitialization**
```java
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Still have pending migration tasks, cannot lock cluster state! New state: ClusterStateChange{type=class com.hazelcast.cluster.ClusterState, newState=PASSIVE}, current state: ACTIVE
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:188)
	at com.hazelcast.internal.partition.GracefulShutdownTest.shutdownMemberAndCluster_concurrently(GracefulShutdownTest.java:467)
	at com.hazelcast.internal.partition.GracefulShutdownTest.shutdownMemberAndCluster_concurrently_withPartitionInitialization(GracefulShutdownTest.java:437)
Caused by: java.lang.IllegalStateException: Still have pending migration tasks, cannot lock cluster state! New state: ClusterStateChange{type=class com.hazelcast.cluster.ClusterState, newState=PASSIVE}, current state: ACTIVE
	at com.hazelcast.internal.cluster.impl.ClusterStateManager.checkMigrationsAndPartitionStateVersion(ClusterStateManager.java:256)
	at com.hazelcast.internal.cluster.impl.ClusterStateManager.lockClusterState(ClusterStateManager.java:211)
	at com.hazelcast.internal.cluster.impl.operations.LockClusterStateOp.run(LockClusterStateOp.java:77)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:194)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:409)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:115)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:100)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:127)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:79)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:183)
	at com.hazelcast.util.FutureUtil.executeWithDeadline(FutureUtil.java:372)
	at com.hazelcast.util.FutureUtil.waitWithDeadline(FutureUtil.java:356)
	at com.hazelcast.util.FutureUtil.waitWithDeadline(FutureUtil.java:330)
	at com.hazelcast.internal.cluster.impl.ClusterStateManager.lockClusterStateOnAllMembers(ClusterStateManager.java:407)
	at com.hazelcast.internal.cluster.impl.ClusterStateManager.changeClusterState(ClusterStateManager.java:356)
	at com.hazelcast.internal.cluster.impl.ClusterStateManager.changeClusterState(ClusterStateManager.java:334)
	at com.hazelcast.internal.cluster.impl.ClusterServiceImpl.changeClusterState(ClusterServiceImpl.java:847)
	at com.hazelcast.internal.cluster.impl.ClusterServiceImpl.changeClusterState(ClusterServiceImpl.java:842)
	at com.hazelcast.internal.cluster.impl.AdvancedClusterStateTest.changeClusterStateEventually(AdvancedClusterStateTest.java:779)
	at com.hazelcast.internal.partition.GracefulShutdownTest$6.run(GracefulShutdownTest.java:461)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.lang.Thread.run(Thread.java:745)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/11601/testReport/junit/com.hazelcast.internal.partition/GracefulShutdownTest/shutdownMemberAndCluster_concurrently_withPartitionInitialization/

**Comment by sancar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/11642/testReport/junit/com.hazelcast.internal.partition/GracefulShutdownTest/shutdownMemberAndCluster_concurrently_withPartitionInitialization/

```
Error Message

java.lang.IllegalStateException: Still have pending migration tasks, cannot lock cluster state! New state: ClusterStateChange{type=class com.hazelcast.cluster.ClusterState, newState=PASSIVE}, current state: ACTIVE
Stacktrace

java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Still have pending migration tasks, cannot lock cluster state! New state: ClusterStateChange{type=class com.hazelcast.cluster.ClusterState, newState=PASSIVE}, current state: ACTIVE
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:188)
	at com.hazelcast.internal.partition.GracefulShutdownTest.shutdownMemberAndCluster_concurrently(GracefulShutdownTest.java:467)
	at com.hazelcast.internal.partition.GracefulShutdownTest.shutdownMemberAndCluster_concurrently_withPartitionInitialization(GracefulShutdownTest.java:437)
Caused by: java.lang.IllegalStateException: Still have pending migration tasks, cannot lock cluster state! New state: ClusterStateChange{type=class com.hazelcast.cluster.ClusterState, newState=PASSIVE}, current state: ACTIVE
	at com.hazelcast.internal.cluster.impl.ClusterStateManager.checkMigrationsAndPartitionStateVersion(ClusterStateManager.java:256)
	at com.hazelcast.internal.cluster.impl.ClusterStateManager.lockClusterState(ClusterStateManager.java:211)
	at com.hazelcast.internal.cluster.impl.operations.LockClusterStateOp.run(LockClusterStateOp.java:77)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:194)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:409)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:115)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:100)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:127)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:79)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:183)
	at com.hazelcast.util.FutureUtil.executeWithDeadline(FutureUtil.java:372)
	at com.hazelcast.util.FutureUtil.waitWithDeadline(FutureUtil.java:356)
	at com.hazelcast.util.FutureUtil.waitWithDeadline(FutureUtil.java:330)
	at com.hazelcast.internal.cluster.impl.ClusterStateManager.lockClusterStateOnAllMembers(ClusterStateManager.java:407)
	at com.hazelcast.internal.cluster.impl.ClusterStateManager.changeClusterState(ClusterStateManager.java:356)
	at com.hazelcast.internal.cluster.impl.ClusterStateManager.changeClusterState(ClusterStateManager.java:334)
	at com.hazelcast.internal.cluster.impl.ClusterServiceImpl.changeClusterState(ClusterServiceImpl.java:847)
	at com.hazelcast.internal.cluster.impl.ClusterServiceImpl.changeClusterState(ClusterServiceImpl.java:842)
	at com.hazelcast.internal.cluster.impl.AdvancedClusterStateTest.changeClusterStateEventually(AdvancedClusterStateTest.java:779)
	at com.hazelcast.internal.partition.GracefulShutdownTest$6.run(GracefulShutdownTest.java:461)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by Donnerbart** [comment]
**com.hazelcast.internal.partition.GracefulShutdownTest.shutdownMultipleMembers_withPartitionInitialization**
```java
java.lang.AssertionError: CountDownLatch failed to complete within 120 seconds, count left: 3
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:1032)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:1025)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:1017)
	at com.hazelcast.internal.partition.GracefulShutdownTest.shutdownMultipleMembers(GracefulShutdownTest.java:246)
	at com.hazelcast.internal.partition.GracefulShutdownTest.shutdownMultipleMembers_withPartitionInitialization(GracefulShutdownTest.java:224)
```
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/new-lab-fast-pr/11722/testReport/junit/com.hazelcast.internal.partition/GracefulShutdownTest/shutdownMultipleMembers_withPartitionInitialization/
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/new-lab-fast-pr/11723/testReport/junit/com.hazelcast.internal.partition/GracefulShutdownTest/shutdownMultipleSlaveMembers_withPartitionInitialization/

**Comment by mdogan** [comment]
`GracefulShutdownTest` has been converted to a serial test by https://github.com/hazelcast/hazelcast/pull/12041. This change might fix above failures, test was very resource hungry before.
