### ISSUE TITLE
com.hazelcast.client.statistics.ClientStatisticsTest.testStatisticsCollectionNonDefaultPeriod

### ISSUE THREAD

**Issue by mmedenjak** [hazelcast/hazelcast#11807]
```
java.lang.AssertionError: nc.hz/StatTestICache,First.hits should not be null ({runtime.maxMemory=1908932608, nc.StatTestMapFirst.First.hits=1, nc.StatTestMapFirst.First.evictions=0, nc.StatTestMapFirst.First.lastPersistenceWrittenBytes=0, runtime.freeMemory=680943472, runtime.uptime=114858, nc.StatTestMapFirst.First.misses=1, lastStatisticsCollectionTime=1510842007587, clientName=hz.client_14, os.maxFileDescriptorCount=65536, runtime.totalMemory=1045954560, os.processCpuTime=37110000000, os.openFileDescriptorCount=66, executionService.userExecutorQueueSize=0, nc.StatTestMapFirst.First.lastPersistenceDuration=0, os.freePhysicalMemorySize=61656928256, os.totalPhysicalMemorySize=405450608640, os.systemLoadAverage=149778.0, nc.StatTestMapFirst.First.ownedEntryMemoryCost=108, runtime.usedMemory=365011088, nc.StatTestMapFirst.First.creationTime=1510842005044, enterprise=false, clientAddress=127.0.0.1:40023, nc.StatTestMapFirst.First.lastPersistenceTime=0, os.totalSwapSpaceSize=4294963200, nc.StatTestMapFirst.First.lastPersistenceKeyCount=0, nc.StatTestMapFirst.First.expirations=0, runtime.availableProcessors=72, clusterConnectionTimestamp=1510841998465, nc.StatTestMapFirst.First.ownedEntryCount=1, os.committedVirtualMemorySize=42863824896, os.freeSwapSpaceSize=4294914048, clientType=JAVA})
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertNotNull(Assert.java:712)
	at com.hazelcast.client.statistics.ClientStatisticsTest.testStatisticsCollectionNonDefaultPeriod(ClientStatisticsTest.java:149)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/11647

**Comment by sancar** [comment]
Also failed in maintenance moving to 3.9.2
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/11699/testReport/junit/com.hazelcast.client.statistics/ClientStatisticsTest/testStatisticsCollectionNonDefaultPeriod/


```
Error Message

nc.hz/StatTestICache,First.hits should not be null ({runtime.maxMemory=954728448, nc.StatTestMapFirst.First.hits=1, nc.StatTestMapFirst.First.evictions=0, nc.StatTestMapFirst.First.lastPersistenceWrittenBytes=0, runtime.freeMemory=109336552, runtime.uptime=11145, nc.StatTestMapFirst.First.misses=1, lastStatisticsCollectionTime=1511253839057, clientName=hz.client_3, os.maxFileDescriptorCount=65536, runtime.totalMemory=233308160, os.processCpuTime=11850000000, os.openFileDescriptorCount=63, executionService.userExecutorQueueSize=0, nc.StatTestMapFirst.First.lastPersistenceDuration=0, os.freePhysicalMemorySize=229989498880, os.totalPhysicalMemorySize=405450608640, os.systemLoadAverage=31282.0, nc.StatTestMapFirst.First.ownedEntryMemoryCost=108, runtime.usedMemory=123971608, nc.StatTestMapFirst.First.creationTime=1511253837837, enterprise=false, clientAddress=127.0.0.1:40004, nc.StatTestMapFirst.First.lastPersistenceTime=0, os.totalSwapSpaceSize=4294963200, nc.StatTestMapFirst.First.lastPersistenceKeyCount=0, nc.StatTestMapFirst.First.expirations=0, runtime.availableProcessors=72, clusterConnectionTimestamp=1511253836454, nc.StatTestMapFirst.First.ownedEntryCount=1, os.committedVirtualMemorySize=40785838080, os.freeSwapSpaceSize=4294918144, clientType=JAVA})
```
Stacktrace
```
java.lang.AssertionError: nc.hz/StatTestICache,First.hits should not be null ({runtime.maxMemory=954728448, nc.StatTestMapFirst.First.hits=1, nc.StatTestMapFirst.First.evictions=0, nc.StatTestMapFirst.First.lastPersistenceWrittenBytes=0, runtime.freeMemory=109336552, runtime.uptime=11145, nc.StatTestMapFirst.First.misses=1, lastStatisticsCollectionTime=1511253839057, clientName=hz.client_3, os.maxFileDescriptorCount=65536, runtime.totalMemory=233308160, os.processCpuTime=11850000000, os.openFileDescriptorCount=63, executionService.userExecutorQueueSize=0, nc.StatTestMapFirst.First.lastPersistenceDuration=0, os.freePhysicalMemorySize=229989498880, os.totalPhysicalMemorySize=405450608640, os.systemLoadAverage=31282.0, nc.StatTestMapFirst.First.ownedEntryMemoryCost=108, runtime.usedMemory=123971608, nc.StatTestMapFirst.First.creationTime=1511253837837, enterprise=false, clientAddress=127.0.0.1:40004, nc.StatTestMapFirst.First.lastPersistenceTime=0, os.totalSwapSpaceSize=4294963200, nc.StatTestMapFirst.First.lastPersistenceKeyCount=0, nc.StatTestMapFirst.First.expirations=0, runtime.availableProcessors=72, clusterConnectionTimestamp=1511253836454, nc.StatTestMapFirst.First.ownedEntryCount=1, os.committedVirtualMemorySize=40785838080, os.freeSwapSpaceSize=4294918144, clientType=JAVA})
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertNotNull(Assert.java:712)
	at com.hazelcast.client.statistics.ClientStatisticsTest.testStatisticsCollectionNonDefaultPeriod(ClientStatisticsTest.java:149)
```
