### ISSUE TITLE
Invocation_NetworkSplitTest

### ISSUE THREAD

**Issue by sancar** [hazelcast/hazelcast#11813]
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/11642/testReport/junit/com.hazelcast.spi.impl.operationservice.impl/Invocation_NetworkSplitTest/testWaitingInvocations_whenNodePartiallySplitFromCluster/

com.hazelcast.spi.impl.operationservice.impl.Invocation_NetworkSplitTest.testWaitingInvocations_whenNodePartiallySplitFromCluster

```
Error Message

java.util.concurrent.ExecutionException: com.hazelcast.spi.exception.CallerNotMemberException: Not Member! this: [127.0.0.1]:5002, caller: [127.0.0.1]:5003, partitionId: 0, operation: com.hazelcast.spi.impl.operationservice.impl.Invocation_NetworkSplitTest$AlwaysBlockingOperation, service: AlwaysBlockingOperationService
Stacktrace

java.lang.AssertionError: java.util.concurrent.ExecutionException: com.hazelcast.spi.exception.CallerNotMemberException: Not Member! this: [127.0.0.1]:5002, caller: [127.0.0.1]:5003, partitionId: 0, operation: com.hazelcast.spi.impl.operationservice.impl.Invocation_NetworkSplitTest$AlwaysBlockingOperation, service: AlwaysBlockingOperationService
	at org.junit.Assert.fail(Assert.java:88)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation_NetworkSplitTest.testWaitingInvocations_whenNodeSplitFromCluster(Invocation_NetworkSplitTest.java:109)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation_NetworkSplitTest.testWaitingInvocations_whenNodePartiallySplitFromCluster(Invocation_NetworkSplitTest.java:67)
```

**Comment by jerrinot** [comment]
no failure since mid-November. closing.

**Comment by kwart** [comment]
Reopening. Failure in PR builder:
```
com.hazelcast.spi.impl.operationservice.impl.Invocation_NetworkSplitTest.testWaitNotifyService_whenNodeSplitFromCluster

Stacktrace
java.lang.AssertionError: expected:<4> but was:<3>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation_NetworkSplitTest.testWaitNotifyService_whenNodeSplitFromCluster(Invocation_NetworkSplitTest.java:167)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation_NetworkSplitTest.testWaitNotifyService_whenNodeSplitFromCluster(Invocation_NetworkSplitTest.java:114)
```

https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/14172/testReport/com.hazelcast.spi.impl.operationservice.impl/Invocation_NetworkSplitTest/testWaitNotifyService_whenNodeSplitFromCluster/
