### ISSUE TITLE
The WaitSet#queue can contain duplicate parked operations

### ISSUE THREAD

**Issue by mmedenjak** [hazelcast/hazelcast#11839]
The operation queue can get the same operation enqueued several times. Consequently, the `WaitSet#queue` can get multiple `WaitSetEntry` instances with the same `WaitSetEntry#op` fields. This happens when an operation is retried because of multiple reasons concurrently (one could be the periodic retry task and the other is a `MemberLeftException` set by the `OnMemberLeftTask`).

Because we have the same operation parked twice, the operation will be unparked and completed because of one notifier. The next notifier will unpark an another `WaitSetEntry` containing the same operation and the operation will be completed twice.

A fix candidate would be keeping the `WaitSetEntry#valid` flag in the operation and checking if the operation was valid in the `WaitSetEntry#isValid` method or adding some other check if the operation was already completed in the same method.

Then we get:
```
com.hazelcast.spi.exception.ResponseAlreadySentException: NormalResponse already responseReceived for callback: Invocation{op=com.hazelcast.concurrent.semaphore.operations.AcquireOperation{serviceName='hz:impl:semaphoreService', identityHash=1233404311, partitionId=3, replicaIndex=0, callId=-11, invocationTime=1511263609695 (2017-11-21 12:26:49.695), waitTimeout=-1, callTimeout=60000, name=f732fd6d-bf53-4488-8aaa-1411900df906}, tryCount=250, tryPauseMillis=500, invokeCount=4, callTimeoutMillis=60000, firstInvocationTimeMs=1511263609640, firstInvocationTime='2017-11-21 12:26:49.640', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 01:00:00.000', target=[127.0.0.1]:5004, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=null}, current-response: NormalResponse{callId=11, urgent=false, value=true, backupAcks=1}
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.sendResponse(Invocation.java:189) ~[classes/:?]
	at com.hazelcast.spi.Operation.sendResponse(Operation.java:360) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.sendResponse(OperationRunnerImpl.java:287) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.handleResponse(OperationRunnerImpl.java:278) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:195) [classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:406) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.run(OperationServiceImpl.java:288) [classes/:?]
	at com.hazelcast.spi.impl.operationparker.impl.WaitSet.unpark(WaitSet.java:104) [classes/:?]
	at com.hazelcast.spi.impl.operationparker.impl.OperationParkerImpl.unpark(OperationParkerImpl.java:114) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.afterRun(OperationRunnerImpl.java:299) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:196) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:409) [classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:115) [classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:100) [classes/:?]
```

This bug was harder to achieve in 3.8 since the `OnMemberLeftTask` was triggered with a delay
```
    void onMemberLeft(MemberImpl member) {
        // postpone notifying invocations since real response may arrive in the mean time.
        scheduler.schedule(new OnMemberLeftTask(member), ON_MEMBER_LEFT_DELAY_MILLIS, MILLISECONDS);
    }
```
And the `InvocationRetryTask` was scheduled with a fixed delay:
```
context.invocationMonitor.schedule(retryTask, tryPauseMillis);
```

Related: https://github.com/hazelcast/hazelcast/issues/11818

**Comment by Danny-Hazelcast** [comment]
root cause of  https://github.com/hazelcast/hazelcast/issues/12952  ?

**Comment by taburet** [comment]
@Danny-Hazelcast probably not, this issue usually manifests itself as "No Invocation found for _normal_ response" or "ResponseAlreadySentException: NormalResponse already responseReceived" messages in logs, I was checking the logs from https://github.com/hazelcast/hazelcast/issues/12952 and there were no such messages, but there is still a chance I just missed them...

**Comment by ulfjack** [comment]
We are seeing a significant amount of ResponseAlreadySentException errors in our logs. Is this a serious issue or is it benign?

**Comment by mmedenjak** [comment]
@ulfjack it should be benign but I've noticed the same and I think we should fix it regardless, possibly in 4.2

**Comment by ulfjack** [comment]
Anything I can help with to get this fixed?

**Comment by mmedenjak** [comment]
hey @ulfjack , it would help if you could determine why the response is already sent in the first place, meaning determine what sequences of actions cause it to be completed twice. It may be the same reason as here (membership changes) or it may be some other reason if no member was added or removed from the cluster during that time.
