### ISSUE TITLE
How to configure the DescribeInstances Request rate of a member in a AWS cluster?

### ISSUE THREAD

**Issue by GDRDABARERA** [hazelcast/hazelcast#11859]
We have an AWS EC2 cluster with 3 members. The Hazelcaset version used is 3.5.0
The EC2 members call DescribeInstances Request to the AWS API to find the cluster members.

- For 24 hours, average 36000 DescribeInstances Request API calls were sent by the 3 members in the AWS cluster, to the AWS API and out of them, 150 calls throttle.
- Therefore, roughly 8 DescribeInstances Request API calls were sent by one member within a minute.

That is in every 8 seconds a DescribeInstances Request is sent by a member to keep track of the cluster.

Is there a way to configure the number of API calls sent by the members in a cluster in hazel cast configuration?

What is the recommended rate to send these API calls by a single member in a cluster?

**Comment by mmedenjak** [comment]
Hi @GDRDABARERA ,

once a member has joined a cluster, it should not look for any other members anymore. Only the master node (which is one designated node in the entire cluster) periodically searches for other clusters to perform cluster merge. This is controlled by the `hazelcast.merge.next.run.delay.seconds` and is 120 seconds by default. That means that during 24 hours, only one member should send out `DescribeInstances` requests and there should be up to 720 requests in one day.

Can you increase the value for that configuration property and see if it has any effect?
Are you sure that all members send DescribeInstances Request API calls every 8 seconds? Can you increase the logging for the `com.hazelcast.cluster.impl.TcpIpJoinerOverAWS` class to `FINEST` or `TRACE` and see if you get something like `Found the following EC2 instances...` or `No EC2 instances found!`? How often does it appear? Does it appear on all members?

P.S. please ask questions on google groups if you are not experiencing an issue and just have a question - https://groups.google.com/forum/#!forum/hazelcast

**Comment by lazerion** [comment]
Hi @GDRDABARERA , >=3.8.6 releases have improvements regarding AWS discovery and endpoint calls. Therefore, is it possible for you to upgrade?

**Comment by GDRDABARERA** [comment]
Hi,
@lazerion at the moment we can not upgrade, but as @mmedenjak mentioned will check for the log traces and check. Will update with the results.
Thank you so much.

**Comment by GDRDABARERA** [comment]
Hi @mmedenjak,
I didn't have a hazelcast.properties file inside my confs, therefore I created one and added this property "hazelcast.merge.next.run.delay.seconds=150"
Is this right(How I added the configuration file)?
After I restart my server with the above configurations I get the following ERROR on my back end.


TID: [0] [IS] [2017-11-28 13:00:35,788]  WARN {org.wso2.carbon.ui.valve.CSRFValve} -  Possible CSRF attack. Refer header : http://xx.xx.xx.xx/phpmyadmin {org.wso2.carbon.ui.valve.CSRFValve}
TID: [0] [IS] [2017-11-28 13:00:35,788] ERROR {org.wso2.carbon.tomcat.ext.valves.CompositeValve} -  Could not handle request: /phpmyadmin {org.wso2.carbon.tomcat.ext.valves.CompositeValve}
javax.servlet.ServletException: Possible CSRF attack. Refer header : http://xx.xx.xx.xx/phpmyadmin
	at org.wso2.carbon.ui.valve.CSRFValve.validateRefererHeader(CSRFValve.java:146)
	at org.wso2.carbon.ui.valve.CSRFValve.validatePatterns(CSRFValve.java:97)
	at org.wso2.carbon.ui.valve.CSRFValve.invoke(CSRFValve.java:79)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:178)
	at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)
	at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:57)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:141)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:156)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:52)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1736)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1695)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:744)
TID: [0] [IS] [2017-11-28 18:37:53,514]  WARN {org.wso2.carbon.ui.valve.CSRFValve} -  Possible CSRF attack. Refer header : http://yy.yy.yy.yy:80 {org.wso2.carbon.ui.valve.CSRFValve}
TID: [0] [IS] [2017-11-28 18:37:53,515] ERROR {org.wso2.carbon.tomcat.ext.valves.CompositeValve} -  Could not handle request: / {org.wso2.carbon.tomcat.ext.valves.CompositeValve}
javax.servlet.ServletException: Possible CSRF attack. Refer header : http://yy.yy.yy.y:80
	at org.wso2.carbon.ui.valve.CSRFValve.validateRefererHeader(CSRFValve.java:146)
	at org.wso2.carbon.ui.valve.CSRFValve.validatePatterns(CSRFValve.java:97)
	at org.wso2.carbon.ui.valve.CSRFValve.invoke(CSRFValve.java:79)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:178)
	at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)
	at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:57)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:141)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:156)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:52)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1736)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1695)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:744)


Do you have any idea why this happens? Now I don't get that throttling error as frequent as before, only 2 /3 per day.

**Comment by mmedenjak** [comment]
The number depends on your environment, your use case and your code. The recommended value is the default value. But you may try and change it to see the effect on the EC2 calls and how the instances behave. 
If you increase it, it will decrease the frequency of how often the master node makes to discover other clusters and it will decrease how often it calls the EC2 API. On the other hand, if your cluster gets split into two because of network issues or because some members are unresponsive, it will take a longer time to merge the two clusters into one.
Have you changed the logging configuration and confirmed that all members are calling the EC2 API?
