### ISSUE TITLE
MapEntryListenerTest fails in the simulator every time - "expected" failure

### ISSUE THREAD

**Issue by Holmistr** [hazelcast/hazelcast#11860]
Stacktrace:
```
java.lang.AssertionError: Add Events  expected:<513554> but was:<513552>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:834)
    at org.junit.Assert.assertEquals(Assert.java:645)
    at com.hazelcast.simulator.tests.map.helpers.EventCount.assertEventsEquals(EventCount.java:91)
    at com.hazelcast.simulator.tests.map.MapEntryListenerTest.verify(MapEntryListenerTest.java:270)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.hazelcast.simulator.worker.testcontainer.MethodInvokingCallable.call(MethodInvokingCallable.java:34)
    at com.hazelcast.simulator.worker.testcontainer.CompositeCallable.call(CompositeCallable.java:32)
    at com.hazelcast.simulator.worker.testcontainer.TestContainer.invoke(TestContainer.java:183)
    at com.hazelcast.simulator.protocol.processors.TestOperationProcessor$1.run0(TestOperationProcessor.java:151)
    at com.hazelcast.simulator.protocol.processors.TestOperationProcessor$OperationThread.run(TestOperationProcessor.java:225)
WARN  2017-11-22 16:48:56,200 [Thread-37] com.hazelcast.simulator.utils.ExceptionReporter: Exception #1 detected
java.lang.AssertionError: Add Events  expected:<513554> but was:<513552>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:834)
    at org.junit.Assert.assertEquals(Assert.java:645)
    at com.hazelcast.simulator.tests.map.helpers.EventCount.assertEventsEquals(EventCount.java:91)
    at com.hazelcast.simulator.tests.map.MapEntryListenerTest.verify(MapEntryListenerTest.java:270)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.hazelcast.simulator.worker.testcontainer.MethodInvokingCallable.call(MethodInvokingCallable.java:34)
```

**Comment by tombujok** [comment]
It's en expected failure - maybe we remove it from the profile.

**Comment by mmedenjak** [comment]
@tombujok can you comment on why this one is expected?

**Comment by Danny-Hazelcast** [comment]
the event system in hazelcast is unreliable, and events can be lossed.

the simulator test  MapEntryListenerTest.java could be changed to not make an assertion
about the number of events that have been sent received

**Comment by Holmistr** [comment]
This issue should no longer be present in Simulator 0.10, which is currently being used for testing. Closing.
