### ISSUE TITLE
Remove group-password based credentials check in client connection

### ISSUE THREAD

**Issue by kwart** [hazelcast/hazelcast#11867]
Members don't check the group password anymore when they form a cluster (during joins). Nevertheless  for clients the check still exists.

This behavior should be changed for the client side too (i.e. group password is not checked).

```xml
<group>
    <name>dev</name>
    <password>this value should not be important anymore</password>
</group>
```

This issue is related to issue #11667 and PR #10377.

When authentication fails, client log contains:
```
Nov 23, 2017 12:51:36 PM com.hazelcast.client.connection.nio.ClientConnection
WARNING: hz.client_0 [dev] [3.9] ClientConnection{alive=false, connectionId=3, channel=NioChannel{/172.17.0.2:35061->/172.17.0.4:5701}, remoteEndpoint=null, lastReadTime=2017-11-23 12:51:36.312, lastWriteTime=2017-11-23 12:51:36.309, closedTime=2017-11-23 12:51:36.313, lastHeartbeatRequested=never, lastHeartbeatReceived=never, connected server version=null} closed. Reason: com.hazelcast.client.AuthenticationException[Invalid credentials! Principal: ClientPrincipal{uuid='6aad8208-1664-4a6c-b924-90dbc0f47579', ownerUuid='7a609c09-977b-42d5-b8f4-4dc87f67b8c5'}]
com.hazelcast.client.AuthenticationException: Invalid credentials! Principal: ClientPrincipal{uuid='6aad8208-1664-4a6c-b924-90dbc0f47579', ownerUuid='7a609c09-977b-42d5-b8f4-4dc87f67b8c5'}
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl$2.onResponse(ClientConnectionManagerImpl.java:664)
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl$2.onResponse(ClientConnectionManagerImpl.java:634)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture$InternalDelegatingExecutionCallback.onResponse(ClientInvocationFuture.java:130)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture$InternalDelegatingExecutionCallback.onResponse(ClientInvocationFuture.java:118)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture$InternalDelegatingExecutionCallback.onResponse(ClientInvocationFuture.java:130)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture$InternalDelegatingExecutionCallback.onResponse(ClientInvocationFuture.java:118)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run(AbstractInvocationFuture.java:248)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at com.hazelcast.util.executor.LoggingScheduledExecutor$LoggingDelegatingFuture.run(LoggingScheduledExecutor.java:160)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
```

**Suggested fix**
Don't verify group password for client connections. Align the behavior with member connections.

**Comment by sancar** [comment]
One consideration about backward compatibility:
Example: 
A 3.6 client was getting AuthException when password was wrong. 
After the change, when that client connects to new server it will connect to cluster without exception. 
Does that count as breaking backward compatibility ?
If yes, we should search for  a solution with new clients always passing and old clients getting the exception when password is wrong.

**Comment by asimarslan** [comment]
We need to solve this without breaking older clients behaviour. They still need to connect to cluster with password validation.

For a safe solution we can introduce a new Authentication Status like `AUTHENTICATED_IGNORED` so that older client will fail anyway but the newer clients can handle it.

**Comment by kwart** [comment]
If only the Java Native client is affected, then the new `AuthenticationStatus` could be the safest way here. On the other hand, if the `AuthenticationStatus` is used by all clients, then I think we should not force the client update to support this new behavior and we should stick to returning `AUTHENTICATED` when the security is not enabled on the server (i.e. copy the member behavior).
