### ISSUE TITLE
MapStoreTest fails in the simulator every time - "expected" failure

### ISSUE THREAD

**Issue by Holmistr** [hazelcast/hazelcast#11861]
Stacktrace:
```
java.lang.AssertionError: Map entrySets should be equal expected:<[515=386088682, 391=-1709439229, 265=2137967448, 781=-76626273, 13=813539359, 915=-1586272298, 277=-1831883068, 796=554676894, 412=1066083579, 668=-1283924768, 541=1984494502, 414=-893218033, 928=-1554891200, 418=926950661, 674=-32965231, 676=-377038995, 932=592606764, 549=-845760967, 550=142720498, 938=853405353, 298=-1814316687, 427=1703859388, 556=543972827, 429=309228521, 430=-135981911, 52=522511708, 565=-1100888013, 566=-1724393421, 568=-1017743998, 442=-621012713, 954=832327541, 827=907223196, 60=513736897, 573=-1242799310, 578=795182298, 324=681345900, 967=1385141194, 841=119884038, 715=-189132754, 203=564181925, 76=-1118648365, 845=1653280127, 80=1957432837, 343=-1623819954, 856=-324836484, 858=-1425866122, 859=-720470143, 482=1152888462, 611=1776013874, 612=1583583601, 484=-2063987045, 357=691404091, 102=1277635439, 486=-1662147976, 747=1338914692, 620=-654690165, 109=1069306299, 622=-320789531, 751=871366228, 114=1480660, 503=-826115983, 250=1220715867, 764=-1269957648, 509=1921121151, 382=-1633069267]> but was:<[514=-2056254602, 515=386088682, 7=-1108788375, 8=783607525, 521=-1878029031, 13=813539359, 527=465400845, 23=184653620, 26=428161479, 538=-927496904, 541=1984494502, 544=988530981, 549=-845760967, 550=142720498, 552=-1785701650, 42=-1928562564, 554=1240163689, 43=-216942687, 44=-206501176, 556=543972827, 46=-88310046, 559=-789380205, 561=-560381230, 50=-919727325, 562=1353093282, 52=522511708, 565=-1100888013, 54=312287393, 566=-1724393421, 568=-1017743998, 570=-645862803, 572=386511572, 60=513736897, 573=-1242799310, 578=795182298, 583=-1134949027, 76=-1118648365, 589=-2033215691, 590=-533340527, 80=1957432837, 89=-1654611957, 92=-943101827, 97=1358516883, 611=1776013874, 100=982143793, 612=1583583601, 102=1277635439, 105=-724172241, 617=36688951, 620=-654690165, 109=1069306299, 110=-1808679205, 622=-320789531, 625=-900789537, 114=1480660, 116=1389357267, 117=-56398083, 123=-467504895, 126=1101122414, 638=1085710696, 128=-733008166, 643=342002649, 133=-1495663260, 645=35463946, 646=948318379, 648=-408061449, 649=-1216477171, 654=1965034591, 142=860647749, 655=-1211022122, 147=812838127, 149=1172759894, 663=1626475041, 153=-1947531121, 154=1512854201, 668=-1283924768, 671=-626244759, 161=-445029316, 674=-32965231, 676=-377038995, 166=47682115, 682=-579671724, 683=-395227274, 173=416632056, 690=1861800067, 712=60138069, 201=1220817605, 715=-189132754, 203=564181925, 719=-1482092914, 207=-1431247659, 208=1487789023, 218=1693384347, 221=1995218589, 222=75787860, 229=1625525705, 743=-2139125310, 747=1338914692, 748=1835148768, 239=-1413112503, 751=871366228, 241=-116974627, 244=-582505096, 757=-1041472902, 249=351284403, 250=1220715867, 764=-1269957648, 766=116737394, 265=2137967448, 781=-76626273, 270=-1713833642, 786=-1695128108, 275=1049868603, 787=-712859113, 788=766205223, 789=614322395, 277=-1831883068, 281=367595765, 795=-465038200, 796=554676894, 285=-1775704721, 810=-2000521095, 298=-1814316687, 299=-2137934383, 304=767570653, 827=907223196, 828=2003981821, 830=682258138, 318=1158237563, 831=1289355048, 321=-1855612968, 324=681345900, 837=1846486719, 841=119884038, 845=1653280127, 335=41426921, 339=-1600367346, 340=-1150478414, 854=813182450, 343=-1623819954, 856=-324836484, 346=-368044053, 858=-1425866122, 859=-720470143, 861=-980734375, 350=-424682163, 863=-413723922, 868=1720895600, 869=1925980281, 357=691404091, 872=-400948707, 361=91580722, 874=-26619729, 880=811773908, 372=131554621, 885=1273267099, 375=-397006739, 889=942475360, 382=-1633069267, 899=1594501922, 902=99466661, 391=-1709439229, 392=1148553610, 904=-1109286162, 905=816475715, 394=-13404914, 395=-2088051340, 915=-1586272298, 404=-219608077, 411=-1903552184, 924=-553262358, 412=1066083579, 926=754185085, 414=-893218033, 927=-631531766, 416=-1167403285, 928=-1554891200, 418=926950661, 419=1283300563, 932=592606764, 933=-219142309, 422=796202602, 937=-582132413, 938=853405353, 427=1703859388, 429=309228521, 430=-135981911, 432=1316969004, 944=-425979077, 434=1106213457, 439=-188541367, 954=832327541, 442=-621012713, 955=-1467195875, 962=-833947686, 451=2087613768, 452=-1920254080, 965=-1184395313, 454=1114122813, 966=-1299098770, 967=1385141194, 969=1782831799, 971=1984552437, 465=712343912, 469=-779979848, 982=-269291635, 472=2023421436, 473=1608918457, 475=-860421897, 988=-884923147, 990=1386008415, 481=752097773, 994=-941234262, 482=1152888462, 996=744169372, 484=-2063987045, 486=-1662147976, 498=-1548091751, 503=-826115983, 504=-825153923, 507=-684101471, 509=1921121151]>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:118)
        at com.hazelcast.simulator.tests.map.MapStoreTest$1.run(MapStoreTest.java:245)
        at com.hazelcast.simulator.utils.TestUtils.assertTrueEventually(TestUtils.java:126)
        at com.hazelcast.simulator.utils.TestUtils.assertTrueEventually(TestUtils.java:157)
        at com.hazelcast.simulator.tests.map.MapStoreTest.verify(MapStoreTest.java:239)

```

**Comment by tombujok** [comment]
It's en expected failure - maybe we remove it from the profile.

**Comment by mmedenjak** [comment]
This test has already been improved by David and the failing assertion has been replaced - https://github.com/hazelcast/hazelcast-simulator/commit/5fe3d3ef09aab13409fb3f548ccaecbda135fe80

**Comment by Holmistr** [comment]
@mmedenjak Nice! So can we close the issue?

**Comment by mmedenjak** [comment]
I will just run it on EC2 for an exercise and then close it :)
