### ISSUE TITLE
ProducerConsumerConditionStressTest.test

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#11952]
*maintenance*
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.lang.Object.wait(Native Method)
	at java.lang.Thread.join(Thread.java:1260)
	at com.hazelcast.test.HazelcastTestSupport.assertJoinable(HazelcastTestSupport.java:837)
	at com.hazelcast.concurrent.lock.ProducerConsumerConditionStressTest.test(ProducerConsumerConditionStressTest.java:63)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-nightly/com.hazelcast$hazelcast/1431/testReport/junit/com.hazelcast.concurrent.lock/ProducerConsumerConditionStressTest/test/

**Comment by hasancelik** [comment]
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.lang.Object.wait(Native Method)
	at java.lang.Thread.join(Thread.java:1260)
	at com.hazelcast.test.HazelcastTestSupport.assertJoinable(HazelcastTestSupport.java:860)
	at com.hazelcast.concurrent.lock.ProducerConsumerConditionStressTest.test(ProducerConsumerConditionStressTest.java:63)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/1591/testReport/junit/com.hazelcast.concurrent.lock/ProducerConsumerConditionStressTest/test/

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/1592/com.hazelcast$hazelcast/testReport/com.hazelcast.concurrent.lock/ProducerConsumerConditionStressTest/test/

**Comment by ahmetmircik** [comment]
merged a fix attempt https://github.com/hazelcast/hazelcast/commit/09a3f7310d6cb726356c4c1c9d50a2ef6995371f
