### ISSUE TITLE
TestHazelcastInstanceFactory.terminateAll() fails with MultiMap

### ISSUE THREAD

**Issue by Donnerbart** [hazelcast/hazelcast#11966]
It looks like `TestHazelcastInstanceFactory.terminateAll()` triggers a `RetryableHazelcastException` in `NodeEngineImpl.getService()`.
```java
10:18:56,683  WARN |testSplitBrain[isBinary:true, mergePolicy:class com.hazelcast.multimap.MultiMapSplitBrainTest$CustomMergePolicy]| - [Node] Thread-7 - [127.0.0.1]:5020 [dev] [3.10-SNAPSHOT] Terminating forcefully...
10:18:56,683  INFO |testSplitBrain[isBinary:true, mergePolicy:class com.hazelcast.multimap.MultiMapSplitBrainTest$CustomMergePolicy]| - [Node] Thread-7 - [127.0.0.1]:5020 [dev] [3.10-SNAPSHOT] Shutting down connection manager...
10:18:56,683  INFO |testSplitBrain[isBinary:true, mergePolicy:class com.hazelcast.multimap.MultiMapSplitBrainTest$CustomMergePolicy]| - [Node] Thread-7 - [127.0.0.1]:5020 [dev] [3.10-SNAPSHOT] Shutting down node engine...
10:18:56,684 ERROR |testSplitBrain[isBinary:true, mergePolicy:class com.hazelcast.multimap.MultiMapSplitBrainTest$CustomMergePolicy]| - [ServiceManagerImpl] Thread-7 - [127.0.0.1]:5020 [dev] [3.10-SNAPSHOT] Error while shutting down service[com.hazelcast.multimap.impl.MultiMapService@3b07e7ca]: HazelcastInstance[[127.0.0.1]:5020] is not active!
com.hazelcast.spi.exception.RetryableHazelcastException: HazelcastInstance[[127.0.0.1]:5020] is not active!
	at com.hazelcast.spi.impl.NodeEngineImpl.getService(NodeEngineImpl.java:358) ~[classes/:?]
	at com.hazelcast.multimap.impl.MultiMapContainer.destroy(MultiMapContainer.java:190) ~[classes/:?]
	at com.hazelcast.multimap.impl.MultiMapPartitionContainer.destroy(MultiMapPartitionContainer.java:101) ~[classes/:?]
	at com.hazelcast.multimap.impl.MultiMapService.reset(MultiMapService.java:154) ~[classes/:?]
	at com.hazelcast.multimap.impl.MultiMapService.shutdown(MultiMapService.java:161) ~[classes/:?]
	at com.hazelcast.spi.impl.servicemanager.impl.ServiceManagerImpl.shutdownService(ServiceManagerImpl.java:307) [classes/:?]
	at com.hazelcast.spi.impl.servicemanager.impl.ServiceManagerImpl.shutdown(ServiceManagerImpl.java:298) [classes/:?]
	at com.hazelcast.spi.impl.NodeEngineImpl.shutdown(NodeEngineImpl.java:468) [classes/:?]
	at com.hazelcast.instance.Node.shutdownServices(Node.java:474) [classes/:?]
	at com.hazelcast.instance.Node.shutdown(Node.java:448) [classes/:?]
	at com.hazelcast.instance.LifecycleServiceImpl.shutdown(LifecycleServiceImpl.java:98) [classes/:?]
	at com.hazelcast.instance.LifecycleServiceImpl.terminate(LifecycleServiceImpl.java:86) [classes/:?]
	at com.hazelcast.test.mocknetwork.TestNodeRegistry.shutdown(TestNodeRegistry.java:121) [test-classes/:?]
	at com.hazelcast.test.mocknetwork.TestNodeRegistry.terminate(TestNodeRegistry.java:111) [test-classes/:?]
	at com.hazelcast.test.TestHazelcastInstanceFactory.terminateAll(TestHazelcastInstanceFactory.java:263) [test-classes/:?]
	at com.hazelcast.test.HazelcastTestSupport.shutdownNodeFactory(HazelcastTestSupport.java:128) [test-classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.12.jar:4.12]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33) [junit-4.12.jar:4.12]
	at com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:21) [test-classes/:?]
	at org.junit.rules.RunRules.evaluate(RunRules.java:20) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325) [junit-4.12.jar:4.12]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78) [junit-4.12.jar:4.12]
	at com.hazelcast.test.HazelcastParallelClassRunner.access$301(HazelcastParallelClassRunner.java:48) [test-classes/:?]
	at com.hazelcast.test.HazelcastParallelClassRunner$TestRunner.run(HazelcastParallelClassRunner.java:153) [test-classes/:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
10:18:56,781  INFO |testSplitBrain[isBinary:true, mergePolicy:class com.hazelcast.multimap.MultiMapSplitBrainTest$CustomMergePolicy]| - [NodeExtension] Thread-7 - [127.0.0.1]:5020 [dev] [3.10-SNAPSHOT] Destroying node NodeExtension.
10:18:56,781  INFO |testSplitBrain[isBinary:true, mergePolicy:class com.hazelcast.multimap.MultiMapSplitBrainTest$CustomMergePolicy]| - [Node] Thread-7 - [127.0.0.1]:5020 [dev] [3.10-SNAPSHOT] Hazelcast Shutdown is completed in 98 ms.
10:18:56,781  INFO |testSplitBrain[isBinary:true, mergePolicy:class com.hazelcast.multimap.MultiMapSplitBrainTest$CustomMergePolicy]| - [LifecycleService] Thread-7 - [127.0.0.1]:5020 [dev] [3.10-SNAPSHOT] [127.0.0.1]:5020 is SHUTDOWN
```
I see this when executing the `MultiMapSplitBrainTest` in my PR https://github.com/hazelcast/hazelcast/pull/11964. But this looks like a general issue when using `terminate()`.

**Comment by Donnerbart** [comment]
The issue also occurs on the normal `MultiMapTest`, e.g.
```java
14:20:08,821 ERROR |testPutGetRemoveWhileCollectionTypeSet| - [ServiceManagerImpl] Thread-14 - [127.0.0.1]:5017 [dev] [3.10-SNAPSHOT] Error while shutting down service[com.hazelcast.multimap.impl.MultiMapService@62140ba1]: HazelcastInstance[[127.0.0.1]:5017] is not active!
com.hazelcast.spi.exception.RetryableHazelcastException: HazelcastInstance[[127.0.0.1]:5017] is not active!
	at com.hazelcast.spi.impl.NodeEngineImpl.getService(NodeEngineImpl.java:358) ~[classes/:?]
	at com.hazelcast.multimap.impl.MultiMapContainer.destroy(MultiMapContainer.java:190) ~[classes/:?]
	at com.hazelcast.multimap.impl.MultiMapPartitionContainer.destroy(MultiMapPartitionContainer.java:101) ~[classes/:?]
	at com.hazelcast.multimap.impl.MultiMapService.reset(MultiMapService.java:153) ~[classes/:?]
	at com.hazelcast.multimap.impl.MultiMapService.shutdown(MultiMapService.java:160) ~[classes/:?]
	at com.hazelcast.spi.impl.servicemanager.impl.ServiceManagerImpl.shutdownService(ServiceManagerImpl.java:307) [classes/:?]
	at com.hazelcast.spi.impl.servicemanager.impl.ServiceManagerImpl.shutdown(ServiceManagerImpl.java:298) [classes/:?]
	at com.hazelcast.spi.impl.NodeEngineImpl.shutdown(NodeEngineImpl.java:468) [classes/:?]
	at com.hazelcast.instance.Node.shutdownServices(Node.java:474) [classes/:?]
	at com.hazelcast.instance.Node.shutdown(Node.java:448) [classes/:?]
	at com.hazelcast.instance.LifecycleServiceImpl.shutdown(LifecycleServiceImpl.java:98) [classes/:?]
	at com.hazelcast.instance.LifecycleServiceImpl.terminate(LifecycleServiceImpl.java:86) [classes/:?]
	at com.hazelcast.test.mocknetwork.TestNodeRegistry.shutdown(TestNodeRegistry.java:121) [test-classes/:?]
	at com.hazelcast.test.mocknetwork.TestNodeRegistry.terminate(TestNodeRegistry.java:111) [test-classes/:?]
	at com.hazelcast.test.TestHazelcastInstanceFactory.terminateAll(TestHazelcastInstanceFactory.java:263) [test-classes/:?]
	at com.hazelcast.test.HazelcastTestSupport.shutdownNodeFactory(HazelcastTestSupport.java:128) [test-classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.12.jar:4.12]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33) [junit-4.12.jar:4.12]
	at com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:21) [test-classes/:?]
	at org.junit.rules.RunRules.evaluate(RunRules.java:20) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325) [junit-4.12.jar:4.12]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78) [junit-4.12.jar:4.12]
	at com.hazelcast.test.HazelcastParallelClassRunner.access$301(HazelcastParallelClassRunner.java:48) [test-classes/:?]
	at com.hazelcast.test.HazelcastParallelClassRunner$TestRunner.run(HazelcastParallelClassRunner.java:153) [test-classes/:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
```

**Comment by Donnerbart** [comment]
If I fix this by changing the `MultiMapContainer.destroy()` to
```java
    public void destroy() {
        if (nodeEngine.isRunning()) {
            LockService lockService = nodeEngine.getService(LockService.SERVICE_NAME);
            if (lockService != null) {
                lockService.clearLockStore(partitionId, lockNamespace);
            }
        }
        multiMapValues.clear();
    }
```
there is another `HazelcastInstanceNotActiveException`:
```java
Exception in thread "Thread-16" com.hazelcast.core.HazelcastInstanceNotActiveException: Hazelcast instance is not active!
	at com.hazelcast.spi.impl.operationservice.impl.InvocationRegistry.shutdown(InvocationRegistry.java:198)
	at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.shutdownInvocations(OperationServiceImpl.java:477)
	at com.hazelcast.spi.impl.NodeEngineImpl.shutdown(NodeEngineImpl.java:466)
	at com.hazelcast.instance.Node.shutdownServices(Node.java:474)
	at com.hazelcast.instance.Node.shutdown(Node.java:448)
	at com.hazelcast.instance.LifecycleServiceImpl.shutdown(LifecycleServiceImpl.java:98)
	at com.hazelcast.instance.LifecycleServiceImpl.terminate(LifecycleServiceImpl.java:86)
	at com.hazelcast.test.mocknetwork.TestNodeRegistry.shutdown(TestNodeRegistry.java:121)
	at com.hazelcast.test.mocknetwork.TestNodeRegistry.terminate(TestNodeRegistry.java:111)
	at com.hazelcast.test.TestHazelcastInstanceFactory.terminateAll(TestHazelcastInstanceFactory.java:263)
	at com.hazelcast.test.HazelcastTestSupport.shutdownNodeFactory(HazelcastTestSupport.java:128)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:21)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at com.hazelcast.test.HazelcastParallelClassRunner.access$301(HazelcastParallelClassRunner.java:48)
	at com.hazelcast.test.HazelcastParallelClassRunner$TestRunner.run(HazelcastParallelClassRunner.java:153)
	at java.lang.Thread.run(Thread.java:748)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:127)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:79)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:155)
	at com.hazelcast.multimap.impl.MultiMapProxySupport.invoke(MultiMapProxySupport.java:252)
	at com.hazelcast.multimap.impl.MultiMapProxySupport.putInternal(MultiMapProxySupport.java:67)
	at com.hazelcast.multimap.impl.ObjectMultiMapProxy.put(ObjectMultiMapProxy.java:107)
	at com.hazelcast.multimap.MultiMapTest$1.run(MultiMapTest.java:115)
```

**Comment by Donnerbart** [comment]
I also so the original exception once during a split-brain test, when `clearMapsHavingLesserBackupCountThan()` was called in between, which also triggers the `container.destroy()` (maybe it was on a re-joining node, which was not active at that time?). I cannot reproduce this one anymore though.

**Comment by mdogan** [comment]
I can't see how the below stacktrace can happen (from https://github.com/hazelcast/hazelcast/issues/11966#issuecomment-351049376):

```
com.hazelcast.spi.exception.RetryableHazelcastException: HazelcastInstance[[127.0.0.1]:5017] is not active!
	at com.hazelcast.spi.impl.NodeEngineImpl.getService(NodeEngineImpl.java:358) ~[classes/:?]
	at com.hazelcast.multimap.impl.MultiMapContainer.destroy(MultiMapContainer.java:190) ~[classes/:?]
	at com.hazelcast.multimap.impl.MultiMapPartitionContainer.destroy(MultiMapPartitionContainer.java:101) ~[classes/:?]
	at com.hazelcast.multimap.impl.MultiMapService.reset(MultiMapService.java:153) ~[classes/:?]
	at com.hazelcast.multimap.impl.MultiMapService.shutdown(MultiMapService.java:160) ~[classes/:?]
	at com.hazelcast.spi.impl.servicemanager.impl.ServiceManagerImpl.shutdownService(ServiceManagerImpl.java:307) [classes/:?]
	at com.hazelcast.spi.impl.servicemanager.impl.ServiceManagerImpl.shutdown(ServiceManagerImpl.java:298) [classes/:?]
	at com.hazelcast.spi.impl.NodeEngineImpl.shutdown(NodeEngineImpl.java:468) [classes/:?]
	at com.hazelcast.instance.Node.shutdownServices(Node.java:474) [classes/:?]
	at com.hazelcast.instance.Node.shutdown(Node.java:448) [classes/:?]
[...]
```

`MultiMapContainer.destroy()` does not call `NodeEngineImpl.getService()` but calls `nodeEngine.getSharedService(LockService.SERVICE_NAME)` since 2016 (see commit: 0a2b272cb8cb45faafd95a3bbc9e9af813620e09), which silently returns null when service is not found.
