### ISSUE TITLE
java.lang.NoClassDefFoundError: org/apache/xml/serializer/TreeWalker

### ISSUE THREAD

**Issue by AM05307** [hazelcast/hazelcast#12036]
I use eclipse 10g & Tomcat 8.5 and got this exception,How can I fix it? 
========================================
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/xml/serializer/TreeWalker
	at org.apache.xalan.processor.TransformerFactoryImpl.newTransformer(TransformerFactoryImpl.java:818)
	at com.ibatis.sqlmap.engine.mapping.statement.RowHandlerCallback.documentToString(RowHandlerCallback.java:86)
	at com.ibatis.sqlmap.engine.mapping.statement.RowHandlerCallback.handleResultObject(RowHandlerCallback.java:73)
	at com.ibatis.sqlmap.engine.execution.SqlExecutor.handleResults(SqlExecutor.java:385)
	at com.ibatis.sqlmap.engine.execution.SqlExecutor.handleMultipleResults(SqlExecutor.java:300)
	at com.ibatis.sqlmap.engine.execution.SqlExecutor.executeQuery(SqlExecutor.java:189)
	at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.sqlExecuteQuery(MappedStatement.java:221)
	at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.executeQueryWithCallback(MappedStatement.java:189)
	at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.executeQueryForObject(MappedStatement.java:120)
	at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.queryForObject(SqlMapExecutorDelegate.java:518)
	at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.queryForObject(SqlMapExecutorDelegate.java:493)
	at com.ibatis.sqlmap.engine.impl.SqlMapSessionImpl.queryForObject(SqlMapSessionImpl.java:106)
	at com.ibatis.sqlmap.engine.impl.SqlMapClientImpl.queryForObject(SqlMapClientImpl.java:82)
	at pack.SimpleExe.getSelect(SimpleExe.java:45)
	at pack.MTest.main(MTest.java:30)
Caused by: java.lang.ClassNotFoundException: org.apache.xml.serializer.TreeWalker
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 15 more
```

**Comment by mmedenjak** [comment]
Hi @AM05307 ! 

I think you opened the issue on the wrong repo :) But be sure to try out hazelcast, we are really an awesome project!

**Comment by AM05307** [comment]
omg,
sorry, thanks to notice!! i will delete atfer 5minutes.
