### ISSUE TITLE
MembershipFailureTest.test_shouldNotRemoveMemberBecauseOfMasterConfirmationTimeout_duringMastershipClaim

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#12047]
```
java.lang.AssertionError: Cluster size is not correct. Expected: 3, actual: 1, instance index: 0
	at org.junit.Assert.fail(Assert.java:88)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSize(HazelcastTestSupport.java:934)
	at com.hazelcast.internal.cluster.impl.MembershipFailureTest.test_shouldNotRemoveMemberBecauseOfMasterConfirmationTimeout_duringMastershipClaim(MembershipFailureTest.java:743)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-freestyle/419/testReport/junit/com.hazelcast.internal.cluster.impl/MembershipFailureTest/test_shouldNotRemoveMemberBecauseOfMasterConfirmationTimeout_duringMastershipClaim_fd_phi_accrual_/

**Comment by sancar** [comment]
Started to fail a lot in pr builders.

https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/13728/
```
com.hazelcast.internal.cluster.impl.MembershipFailureTest.test_shouldNotRemoveMemberBecauseOfMasterConfirmationTimeout_duringMastershipClaim[fd:phi-accrual]

Error Message
Cluster size is not correct. Expected: 3, actual: 2, instance index: 0
Stacktrace
java.lang.AssertionError: Cluster size is not correct. Expected: 3, actual: 2, instance index: 0
	at org.junit.Assert.fail(Assert.java:88)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSize(HazelcastTestSupport.java:950)
	at com.hazelcast.internal.cluster.impl.MembershipFailureTest.test_shouldNotRemoveMemberBecauseOfMasterConfirmationTimeout_duringMastershipClaim(MembershipFailureTest.java:743)
```


https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/13722/

```
com.hazelcast.internal.cluster.impl.MembershipFailureTest.test_shouldNotRemoveMemberBecauseOfMasterConfirmationTimeout_duringMastershipClaim[fd:deadline]



Error Message
Cluster size is not correct. Expected: 3, actual: 1, instance index: 0
Stacktrace
java.lang.AssertionError: Cluster size is not correct. Expected: 3, actual: 1, instance index: 0
	at org.junit.Assert.fail(Assert.java:88)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSize(HazelcastTestSupport.java:950)
	at com.hazelcast.test.HazelcastTestSupport$13.run(HazelcastTestSupport.java:972)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1145)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:968)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:962)
	at com.hazelcast.internal.cluster.impl.MembershipFailureTest.test_shouldNotRemoveMemberBecauseOfMasterConfirmationTimeout_duringMastershipClaim(MembershipFailureTest.java:742)
```

**Comment by mdogan** [comment]
This test is already removed from master by https://github.com/hazelcast/hazelcast/pull/11604

**Comment by mdogan** [comment]
Test has 5 seconds master-confirmation timeout and it seems when system is a bit slow, a member is removed before 3 member cluster is formed:

>12:30:57,059  WARN |test_shouldNotRemoveMemberBecauseOfMasterConfirmationTimeout_duringMastershipClaim[fd:phi-accrual]| - [ClusterHeartbeatManager] hz._hzInstance_240_dev.generic-operation.thread-5 - [127.0.0.1]:5239 [dev] [3.9.4-SNAPSHOT] Removing Member [127.0.0.1]:5265 - 43c21495-88cf-4ab7-9f7c-16f68b989223 because it has not sent any master confirmation for 5000 ms.  Clock time: 2018-02-20 12:30:57.059. Cluster time: 2018-02-20 12:30:57.059. Last confirmation time was 2018-02-20 12:30:51.381.


```
12:30:35, accumulated pauses: 237 ms, max pause: 5 ms, pauses over 1000 ms: 0
12:30:40, accumulated pauses: 2420 ms, max pause: 1669 ms, pauses over 1000 ms: 1
12:30:45, accumulated pauses: 2614 ms, max pause: 1399 ms, pauses over 1000 ms: 1
12:30:50, accumulated pauses: 1966 ms, max pause: 876 ms, pauses over 1000 ms: 0
12:30:55, accumulated pauses: 2985 ms, max pause: 2775 ms, pauses over 1000 ms: 1
12:31:00, accumulated pauses: 3562 ms, max pause: 1484 ms, pauses over 1000 ms: 1
12:31:05, accumulated pauses: 2786 ms, max pause: 1006 ms, pauses over 1000 ms: 1
12:31:10, accumulated pauses: 2521 ms, max pause: 1014 ms, pauses over 1000 ms: 1
12:31:15, accumulated pauses: 2393 ms, max pause: 879 ms, pauses over 1000 ms: 0
12:31:20, accumulated pauses: 1254 ms, max pause: 331 ms, pauses over 1000 ms: 0
12:31:25, accumulated pauses: 471 ms, max pause: 129 ms, pauses over 1000 ms: 0
```
