### ISSUE TITLE
TEST FAILURE - com.hazelcast.map.mapstore.MapStoreTest.testTwoMemberWriteThrough2

### ISSUE THREAD

**Issue by mdogan** [hazelcast/hazelcast#1208]
````
testTwoMemberWriteThrough2(com.hazelcast.map.mapstore.MapStoreTest)  Time elapsed: 6.923 sec  <<< FAILURE!
java.lang.AssertionError: expected:<1000> but was:<494>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:555)
	at org.junit.Assert.assertEquals(Assert.java:542)
	at com.hazelcast.map.mapstore.MapStoreTest.testTwoMemberWriteThrough2(MapStoreTest.java:648)
````

**Comment by Donnerbart** [comment]
I think we might have a regression on this bug in PR #4560:
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-pr-builder/11896/console

**Comment by ahmetmircik** [comment]
can not manage to reproduce yet.
Increased timeout.https://github.com/hazelcast/hazelcast/commit/04fa7ab06a36416ebde2e2a3016494258541280d
waiting for the next possible failure. closing now.
