### ISSUE TITLE
MultiMapListenerTest.testListeners

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#12100]
```
java.lang.AssertionError: the size of the collection is not correct: found-content:[key8, key7, key4, key5] expected:<1> but was:<4>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.test.HazelcastTestSupport$8.run(HazelcastTestSupport.java:906)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1149)
	at com.hazelcast.test.HazelcastTestSupport.assertSizeEventually(HazelcastTestSupport.java:903)
	at com.hazelcast.test.HazelcastTestSupport.assertSizeEventually(HazelcastTestSupport.java:899)
	at com.hazelcast.multimap.MultiMapListenerTest.testListeners(MultiMapListenerTest.java:542)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-freestyle/1479/testReport/junit/com.hazelcast.multimap/MultiMapListenerTest/testListeners/

**Comment by jerrinot** [comment]
apparently the `multimap.clear()` calls a local listener only when called on a local instance only.

**Comment by jerrinot** [comment]
The question is what's desired behaviour. 

I guess `CLEAR` events can be seen as global events hence they should be delivered to local listeners regardless of where they are registered. This is the behaviour in the IMap anyway.

**Comment by jerrinot** [comment]
actually I was wrong - IMap does not fire local events for non-local `clear()`.
