### ISSUE TITLE
TransactionalQueueQuorumWriteTest.take_quorum & remove_quorum

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#12101]
**TransactionalQueueQuorumWriteTest.take_quorum**
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:315)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:153)
	at com.hazelcast.collection.impl.txnqueue.TransactionalQueueProxySupport.pollInternal(TransactionalQueueProxySupport.java:140)
	at com.hazelcast.collection.impl.txnqueue.TransactionalQueueProxy.poll(TransactionalQueueProxy.java:81)
	at com.hazelcast.collection.impl.txnqueue.TransactionalQueueProxy.take(TransactionalQueueProxy.java:62)
	at com.hazelcast.quorum.queue.TransactionalQueueQuorumWriteTest.take_quorum(TransactionalQueueQuorumWriteTest.java:159)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.8/com.hazelcast$hazelcast/833/testReport/junit/com.hazelcast.quorum.queue/TransactionalQueueQuorumWriteTest/take_quorum_Executing__TransactionOptions_timeoutMillis_120000__durability_1__txType_ONE_PHASE__READ_WRITE_/

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-ZuluJDK6-freestyle/344/testReport/junit/com.hazelcast.quorum.queue/TransactionalQueueQuorumWriteTest/take_quorum_Executing__TransactionOptions_timeoutMillis_120000__durability_1__txType_ONE_PHASE__READ_WRITE_/

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-ZuluJDK7-freestyle/91/testReport/junit/com.hazelcast.quorum.queue/TransactionalQueueQuorumWriteTest/take_quorum_Executing__TransactionOptions_timeoutMillis_120000__durability_1__txType_ONE_PHASE__READ_WRITE_/

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-ZuluJDK8/com.hazelcast$hazelcast/814/testReport/junit/com.hazelcast.quorum.queue/TransactionalQueueQuorumWriteTest/take_quorum_Executing__TransactionOptions_timeoutMillis_120000__durability_1__txType_ONE_PHASE__READ_WRITE_/

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-ZuluJDK8/com.hazelcast$hazelcast/814/testReport/junit/com.hazelcast.quorum.queue/TransactionalQueueQuorumWriteTest/take_quorum_Executing__TransactionOptions_timeoutMillis_120000__durability_1__txType_TWO_PHASE__READ_WRITE_/

**ClientTransactionalQueueQuorumWriteTest.take_quorum**
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:283)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:153)
	at com.hazelcast.client.proxy.txn.ClientTransactionUtil.invoke(ClientTransactionUtil.java:57)
	at com.hazelcast.client.proxy.txn.ClientTxnProxy.invoke(ClientTxnProxy.java:61)
	at com.hazelcast.client.proxy.txn.ClientTxnQueueProxy.take(ClientTxnQueueProxy.java:66)
	at com.hazelcast.quorum.queue.TransactionalQueueQuorumWriteTest.take_quorum(TransactionalQueueQuorumWriteTest.java:159)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.lang.Thread.run(Thread.java:662)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-freestyle/1487/testReport/junit/com.hazelcast.client.quorum.queue/ClientTransactionalQueueQuorumWriteTest/take_quorum_Executing__TransactionOptions_timeoutMillis_120000__durability_1__txType_ONE_PHASE__READ_WRITE_/

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-ZuluJDK8/com.hazelcast$hazelcast-client/814/testReport/junit/com.hazelcast.client.quorum.queue/ClientQueueQuorumWriteTest/take_quorum_quorumType_WRITE_/
  
  **ClientQueueQuorumWriteTest.remove_quorum**
```
java.util.NoSuchElementException: Queue is empty!
	at com.hazelcast.client.proxy.ClientQueueProxy.remove(ClientQueueProxy.java:263)
	at com.hazelcast.quorum.queue.QueueQuorumWriteTest.remove_quorum(QueueQuorumWriteTest.java:107)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-ZuluJDK8/com.hazelcast$hazelcast-client/814/testReport/junit/com.hazelcast.client.quorum.queue/ClientQueueQuorumWriteTest/remove_quorum_quorumType_WRITE_/

**Comment by tombujok** [comment]
Fixed by #12085
