### ISSUE TITLE
QueueQuorumReadTest.element_quorum

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#12102]
**QueueQuorumReadTest.element_quorum**
```
java.util.NoSuchElementException: Queue is empty!
	at com.hazelcast.collection.impl.queue.QueueProxyImpl.element(QueueProxyImpl.java:150)
	at com.hazelcast.quorum.queue.QueueQuorumReadTest.element_quorum(QueueQuorumReadTest.java:65)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-freestyle/1486/testReport/junit/com.hazelcast.quorum.queue/QueueQuorumReadTest/element_quorum_quorumType_READ_/

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK1.6-freestyle/342/testReport/junit/com.hazelcast.quorum.queue/QueueQuorumReadTest/element_quorum_quorumType_READ_/

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-ZuluJDK6-freestyle/343/testReport/junit/com.hazelcast.quorum.queue/QueueQuorumReadTest/element_quorum_quorumType_READ_/

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-ZuluJDK6-freestyle/343/testReport/junit/com.hazelcast.quorum.queue/QueueQuorumReadTest/element_quorum_quorumType_READ_WRITE_/

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-ZuluJDK8/com.hazelcast$hazelcast/813/testReport/junit/com.hazelcast.quorum.queue/QueueQuorumReadTest/element_quorum_quorumType_READ_/

https://hazelcast-l337.ci.cloudbees.com/view/Sonar/job/Hazelcast-3.x-sonar/com.hazelcast$hazelcast/1747/testReport/junit/com.hazelcast.quorum.queue/QueueQuorumReadTest/element_quorum_quorumType_READ_/

**ClientQueueQuorumReadTest.element_quorum**
```
java.util.NoSuchElementException: Queue is empty!
	at com.hazelcast.client.proxy.ClientQueueProxy.element(ClientQueueProxy.java:281)
	at com.hazelcast.quorum.queue.QueueQuorumReadTest.element_quorum(QueueQuorumReadTest.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.lang.Thread.run(Thread.java:662)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-freestyle/1488/testReport/junit/com.hazelcast.client.quorum.queue/ClientQueueQuorumReadTest/element_quorum_quorumType_READ_WRITE_/

**Comment by ahmetmircik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/12734/console
```
17:05:19 element_quorum[quorumType:READ](com.hazelcast.quorum.queue.QueueQuorumReadTest)  Time elapsed: 0.196 sec  <<< ERROR!
17:05:19 java.util.NoSuchElementException: Queue is empty!
17:05:19 	at com.hazelcast.collection.impl.queue.QueueProxyImpl.element(QueueProxyImpl.java:150)
17:05:19 	at com.hazelcast.quorum.queue.QueueQuorumReadTest.element_quorum(QueueQuorumReadTest.java:65)
```

**Comment by mmedenjak** [comment]
@tombujok did this PR fix the test - https://github.com/hazelcast/hazelcast/pull/12085?

**Comment by tombujok** [comment]
Yep
