### ISSUE TITLE
com.hazelcast.quorum.queue.QueueQuorumReadTest

### ISSUE THREAD

**Issue by ahmetmircik** [hazelcast/hazelcast#12125]
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/12734/console
```
17:05:19 element_quorum[quorumType:READ](com.hazelcast.quorum.queue.QueueQuorumReadTest)  Time elapsed: 0.196 sec  <<< ERROR!
17:05:19 java.util.NoSuchElementException: Queue is empty!
17:05:19 	at com.hazelcast.collection.impl.queue.QueueProxyImpl.element(QueueProxyImpl.java:150)
17:05:19 	at com.hazelcast.quorum.queue.QueueQuorumReadTest.element_quorum(QueueQuorumReadTest.java:65)
```

**Comment by ahmetmircik** [comment]
duplicate of https://github.com/hazelcast/hazelcast/issues/12102
