### ISSUE TITLE
Hazelcast instance is not active! due to java.lang.InterruptedException: LockOperation was interrupted

### ISSUE THREAD

**Issue by nakulpatil24** [hazelcast/hazelcast#12130]
Hello,

I have 2 nodes cluster managed by hazelcast v. 3.8. activeMQ, executor service and hazelcast cache map which has large amount of locking and unlocking activities. e.g.
```java
getLocalCache().lock(changelog.getBranch());
updateLocalCache(changelog, crw, getLocalCache());
getLocalCache().unlock(changelog.getBranch());
```

after couple of days working nicely following error starts popping continously 

```
11:57:34.097 [pool-24-thread-16] ERROR c.t.c.h.j.ChangelogGapFillerThread1 - java.lang.InterruptedException: LockOperation was interrupted. Invocation{op=com.hazelcast.concurrent.lock.operations.LockOperation{serviceName='hz:impl:lockService', identityHash=639755771, partitionId=139, replicaIndex=0, callId=-1141578, invocationTime=1515585172356 (2018-01-10 11:52:52.356), waitTimeout=-1, callTimeout=60000, namespace=DefaultObjectNamespace{service='hz:impl:mapService', objectName=distributed_cache}, threadId=810}, tryCount=250, tryPauseMillis=500, invokeCount=0, callTimeoutMillis=60000, firstInvocationTimeMs=1515584888830, firstInvocationTime='2018-01-10 11:48:08.830', lastHeartbeatMillis=1515585243068, lastHeartbeatTime='2018-01-10 11:54:03.068', target=[172.29.238.122]:5701, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=null}
11:57:34.121 [pool-24-thread-8] ERROR c.t.c.h.j.ChangelogGapFillerThread1 - UnlockOperation got rejected before execution due to not starting within the operation-call-timeout of: 60000 ms. Current time: 2018-01-10 11:56:25.038. Start time: 2018-01-10 11:54:19.443. Total elapsed time: 125595 ms. Invocation{op=com.hazelcast.concurrent.lock.operations.UnlockOperation{serviceName='hz:impl:lockService', identityHash=1453843575, partitionId=139, replicaIndex=0, callId=-1141603, invocationTime=1515585259441 (2018-01-10 11:54:19.441), waitTimeout=-1, callTimeout=60000, namespace=DefaultObjectNamespace{service='hz:impl:mapService', objectName=local_cache}, threadId=802}, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=60000, firstInvocationTimeMs=1515585259443, firstInvocationTime='2018-01-10 11:54:19.443', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 00:00:00.000', target=[172.29.238.122]:5701, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=null}
Caused by: com.hazelcast.core.HazelcastInstanceNotActiveException: Hazelcast instance is not active!
              at com.hazelcast.spi.impl.operationservice.impl.InvocationRegistry.shutdown(InvocationRegistry.java:192)
              at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.shutdownInvocations(OperationServiceImpl.java:479)
              at com.hazelcast.spi.impl.NodeEngineImpl.shutdown(NodeEngineImpl.java:487)
              at com.hazelcast.instance.Node.shutdownServices(Node.java:489)
              at com.hazelcast.instance.Node.shutdown(Node.java:463)
              at com.hazelcast.instance.OutOfMemoryHandlerHelper.tryShutdown(OutOfMemoryHandlerHelper.java:61)
              at com.hazelcast.instance.DefaultOutOfMemoryHandler.onOutOfMemory(DefaultOutOfMemoryHandler.java:87)
              at com.hazelcast.instance.OutOfMemoryErrorDispatcher.onOutOfMemory(OutOfMemoryErrorDispatcher.java:189)
              at com.hazelcast.instance.OutOfMemoryErrorDispatcher.inspectOutOfMemoryError(OutOfMemoryErrorDispatcher.java:158)
              at com.hazelcast.spi.impl.packetdispatcher.impl.PacketDispatcherImpl.dispatch(PacketDispatcherImpl.java:84)
              at com.hazelcast.nio.tcp.MemberReadHandler.handlePacket(MemberReadHandler.java:77)
              at com.hazelcast.nio.tcp.MemberReadHandler.onRead(MemberReadHandler.java:60)
              at com.hazelcast.internal.networking.nonblocking.NonBlockingSocketReader.handle(NonBlockingSocketReader.java:161)
              at com.hazelcast.internal.networking.nonblocking.NonBlockingIOThread.handleSelectionKey(NonBlockingIOThread.java:350)
              at com.hazelcast.internal.networking.nonblocking.NonBlockingIOThread.handleSelectionKeys(NonBlockingIOThread.java:335)
              at com.hazelcast.internal.networking.nonblocking.NonBlockingIOThread.selectLoop(NonBlockingIOThread.java:253)
              at com.hazelcast.internal.networking.nonblocking.NonBlockingIOThread.run(NonBlockingIOThread.java:206)
              at ------ submitted from ------.(Unknown Source)
              at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:114)
              at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:75)
              at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:155)
              at com.hazelcast.map.impl.proxy.MapProxySupport.containsKeyInternal(MapProxySupport.java:559)
              at com.hazelcast.map.impl.proxy.MapProxyImpl.containsKey(MapProxyImpl.java:245)
              at com.tomtom.cpp.herald.BaselineChangelogProcessor.isCLogNewerAndAheadOfHeadInDCache(BaselineChangelogProcessor.java:222)
              at com.tomtom.cpp.herald.BaselineChangelogProcessor.process(BaselineChangelogProcessor.java:67)
              at com.tomtom.cpp.herald.jms.ChangelogListener.handle(ChangelogListener.java:22)
              at sun.reflect.GeneratedMethodAccessor89.invoke(Unknown Source)
              at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
              at java.lang.reflect.Method.invoke(Method.java:498)
              at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:180)
              at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:112)
              at org.springframework.jms.listener.adapter.MessagingMessageListenerAdapter.invokeHandler(MessagingMessageListenerAdapter.java:104)
```

**Comment by mdogan** [comment]
From the stack trace your application ran out of memory while Hazelcast IO thread processing packets and Hazelcast shutdown automatically by the default OutOfMemoryHandler (`DefaultOutOfMemoryHandler`).

```
Caused by: com.hazelcast.core.HazelcastInstanceNotActiveException: Hazelcast instance is not active!
              at com.hazelcast.spi.impl.operationservice.impl.InvocationRegistry.shutdown(InvocationRegistry.java:192)
              at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.shutdownInvocations(OperationServiceImpl.java:479)
              at com.hazelcast.spi.impl.NodeEngineImpl.shutdown(NodeEngineImpl.java:487)
              at com.hazelcast.instance.Node.shutdownServices(Node.java:489)
              at com.hazelcast.instance.Node.shutdown(Node.java:463)
              at com.hazelcast.instance.OutOfMemoryHandlerHelper.tryShutdown(OutOfMemoryHandlerHelper.java:61)
              at com.hazelcast.instance.DefaultOutOfMemoryHandler.onOutOfMemory(DefaultOutOfMemoryHandler.java:87)
              at com.hazelcast.instance.OutOfMemoryErrorDispatcher.onOutOfMemory(OutOfMemoryErrorDispatcher.java:189)
              at com.hazelcast.instance.OutOfMemoryErrorDispatcher.inspectOutOfMemoryError(OutOfMemoryErrorDispatcher.java:158)
              at com.hazelcast.spi.impl.packetdispatcher.impl.PacketDispatcherImpl.dispatch(PacketDispatcherImpl.java:84)
              at com.hazelcast.nio.tcp.MemberReadHandler.handlePacket(MemberReadHandler.java:77)
```

`LockOperation` was interrupted due to that shutdown and `UnlockOperation` got rejected because it wasn't able to start due to GC pauses (due to memory pressure).

Please inspect your memory usage and either increase heap memory if required or gather periodic heap dumps to figure out whether or not there's a memory leak.
