### ISSUE TITLE
OperationServiceImpl_invokeOnPartitionsTest

### ISSUE THREAD

**Issue by Donnerbart** [hazelcast/hazelcast#12138]
`com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl_invokeOnPartitionsTest.testLongRunning`
```java
java.util.concurrent.ExecutionException: com.hazelcast.nio.serialization.HazelcastSerializationException: Problem while reading DataSerializable, namespace: 0, ID: 0, class: 'com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl_invokeOnPartitionsTest$SlowOperationFactoryImpl$1', exception: com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl_invokeOnPartitionsTest$SlowOperationFactoryImpl$1.<init>()
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.rethrowReadException(DataSerializableSerializer.java:176)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.readInternal(DataSerializableSerializer.java:161)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:105)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:50)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:185)
	at com.hazelcast.spi.impl.NodeEngineImpl.toObject(NodeEngineImpl.java:312)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:391)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:115)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:100)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:127)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:79)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:155)
	at com.hazelcast.spi.impl.operationservice.impl.InvokeOnPartitions.retryFailedPartitions(InvokeOnPartitions.java:144)
	at com.hazelcast.spi.impl.operationservice.impl.InvokeOnPartitions.invoke(InvokeOnPartitions.java:74)
	at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.invokeOnAllPartitions(OperationServiceImpl.java:383)
	at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl_invokeOnPartitionsTest.testLongRunning(OperationServiceImpl_invokeOnPartitionsTest.java:76)
Caused by: java.lang.NoSuchMethodException: com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl_invokeOnPartitionsTest$SlowOperationFactoryImpl$1.<init>()
	at java.lang.Class.getConstructor0(Class.java:2902)
	at java.lang.Class.getDeclaredConstructor(Class.java:2066)
	at com.hazelcast.nio.ClassLoaderUtil.newInstance(ClassLoaderUtil.java:106)
	at com.hazelcast.nio.ClassLoaderUtil.newInstance(ClassLoaderUtil.java:102)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.readInternal(DataSerializableSerializer.java:150)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:105)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:50)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:185)
	at com.hazelcast.spi.impl.NodeEngineImpl.toObject(NodeEngineImpl.java:312)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:391)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:115)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:100)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/12761/testReport/junit/com.hazelcast.spi.impl.operationservice.impl/OperationServiceImpl_invokeOnPartitionsTest/testLongRunning/

**Comment by mdogan** [comment]
It looks like this is a temporary failure, cause was `NoSuchMethodException` for constructor of an anonymous class in `SlowOperationFactoryImpl`.

**Comment by sancar** [comment]
Same test failed in one my pr's. 

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-pr-builder/15868/testReport/junit/com.hazelcast.spi.impl.operationservice.impl/OperationServiceImpl_invokeOnPartitionsTest/testLongRunning/

```
com.hazelcast.nio.serialization.HazelcastSerializationException: Problem while reading DataSerializable, namespace: 0, ID: 0, class: 'com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl_invokeOnPartitionsTest$SlowOperationFactoryImpl$1', exception: com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl_invokeOnPartitionsTest$SlowOperationFactoryImpl$1.<init>()
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.rethrowReadException(DataSerializableSerializer.java:180) ~[classes/:?]
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.readInternal(DataSerializableSerializer.java:161) ~[classes/:?]
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:105) ~[classes/:?]
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:50) ~[classes/:?]
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48) ~[classes/:?]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:187) ~[classes/:?]
	at com.hazelcast.spi.impl.NodeEngineImpl.toObject(NodeEngineImpl.java:322) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:390) ~[classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:115) [classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:100) [classes/:?]
Caused by: java.lang.NoSuchMethodException: com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl_invokeOnPartitionsTest$SlowOperationFactoryImpl$1.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082) ~[?:1.8.0_171]
	at java.lang.Class.getDeclaredConstructor(Class.java:2178) ~[?:1.8.0_171]
	at com.hazelcast.nio.ClassLoaderUtil.newInstance(ClassLoaderUtil.java:106) ~[classes/:?]
	at com.hazelcast.nio.ClassLoaderUtil.newInstance(ClassLoaderUtil.java:102) ~[classes/:?]
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.readInternal(DataSerializableSerializer.java:150) ~[classes/:?]
	... 8 more
```

This logs says that this class `com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl_invokeOnPartitionsTest$SlowOperationFactoryImpl$1` is trying to be instantiated via class loader as if it is not IdentifiedDataSerializable, but it is. How is that possible ? Am I reading the log wrong ?

**Comment by blazember** [comment]
Another failure in a maintenance-3.x PR https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-pr-builder/15893/.

**Comment by blazember** [comment]
It seems that `OperationServiceImpl_invokeOnPartitionsTest$SlowOperationFactoryImpl$1` is not even seen by `DataSerializableSerializer#readInternal` during successful runs. At least my commit https://github.com/blazember/hazelcast/commit/b78c8ab268f5b90abc981c39818daaa8037db30e#diff-83733246452132c3d1aa8c5c9b19bb0c does not log anything apart from 
```
***** Created instance of com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl_invokeOnPartitionsTest$SlowOperationFactoryImpl via factory com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl_invokeOnPartitionsTest$SlowOperationSerializationFactory
```
The other thing I noticed that in the failed case I found the following in the log, which I can't find in the log of the successful local executions:
```
17:39:07,914  INFO |testLongRunning| - [InvocationMonitor] hz._hzInstance_13_dev.InvocationMonitorThread - [127.0.0.1]:5012 [dev] [3.10.3-SNAPSHOT] Invocations:2 timeouts:1 backup-timeouts:0
17:39:14,953  WARN |testLongRunning| - [InboundResponseHandler] hz._hzInstance_13_dev.response-0 - [127.0.0.1]:5012 [dev] [3.10.3-SNAPSHOT] No Invocation found for normal response with callId 3 sent from [127.0.0.1]:5014
```
:point_up:  is from https://s3.amazonaws.com/j-artifacts/Hazelcast-pr-builder/15893/Hazelcast-pr-builder-15893.zip

My gut feeling is that this test is failing in some fallback case. 
@pveentjer any thoughts on this?

**Comment by taburet** [comment]
The root cause is:

1. Initially all operations are issued to members using `PartitionIteratingOperation` which accepts operation factory to create the actual operations. The factory implements `IdentifiedDataSerializable` and may be (de)serialized properly.

2. Some of the operations fail, due to timeouts in our case, and the invocations are retried in `InvokeOnPartitions#retryFailedPartitions`, but this time they are issued to the failed partitions individually without `PartitionIteratingOperation` which knows the factory.

3. All operations implement `DataSerializable`, so the operations are serialized, but during the deserialization we can't instantiate them since the operation class is anonymous and implicitly accepts an instance of the enclosing class in its "default" constructor.

Possible solutions:

1. Add a better (de)serialization support for anonymous, local and non-static member classes. There are two problems here: (a) in a general case we can't provide a proper enclosing class instance and (b) anonymous and local classes may capture variables from an enclosing method which are implicitly passed to their constructors, we don't know where we can obtain these captured variables.

2. Fix the test case by converting the anonymous operation class into a regular one.

3. Rework the `InvokeOnPartitions` implementation to use `PartitionIteratingOperation` while retying the invocations for failed partitions, so we will always rely on the serialization implementation provided by the operation factory.

In any case, a better error message must be added, saying that we are not supporting anonymous, local and non-static member classes for `DataSerializable`.

**Comment by mustafaiman** [comment]
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/1434/testReport/junit/com.hazelcast.spi.impl.operationservice.impl/OperationServiceImpl_invokeOnPartitionsTest/testLongRunning/

**Comment by vbekiaris** [comment]
`testLongRunning` failed due to long JVM pauses:

```
SlowOperation got rejected before execution due to not starting within the operation-call-timeout of: 2000 ms. Current time: 2019-05-10 15:27:18.712. Start time: 2019-05-10 15:27:15.949. Total elapsed time: 2763 ms. Invocation{op=com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl_invokeOnPartitionsTest$SlowOperation{serviceName=&apos;null&apos;, identityHash=2145166688, partitionId=1, replicaIndex=0, callId=-5, invocationTime=1557502035949 (2019-05-10 15:27:15.949), waitTimeout=-1, callTimeout=2000}, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=2000, firstInvocationTimeMs=1557502035949, firstInvocationTime=&apos;2019-05-10 15:27:15.949&apos;, lastHeartbeatMillis=0, lastHeartbeatTime=&apos;1970-01-01 00:00:00.000&apos;, target=[127.0.0.1]:5702, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=MockConnection{localEndpoint=[127.0.0.1]:5701, remoteEndpoint=[127.0.0.1]:5702, alive=true}}" type="com.hazelcast.core.OperationTimeoutException">com.hazelcast.core.OperationTimeoutException: SlowOperation got rejected before execution due to not starting within the operation-call-timeout of: 2000 ms. Current time: 2019-05-10 15:27:18.712. Start time: 2019-05-10 15:27:15.949. Total elapsed time: 2763 ms. Invocation{op=com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl_invokeOnPartitionsTest$SlowOperation{serviceName='null', identityHash=2145166688, partitionId=1, replicaIndex=0, callId=-5, invocationTime=1557502035949 (2019-05-10 15:27:15.949), waitTimeout=-1, callTimeout=2000}, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=2000, firstInvocationTimeMs=1557502035949, firstInvocationTime='2019-05-10 15:27:15.949', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 00:00:00.000', target=[127.0.0.1]:5702, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=MockConnection{localEndpoint=[127.0.0.1]:5701, remoteEndpoint=[127.0.0.1]:5702, alive=true}}
        at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.newOperationTimeoutException(InvocationFuture.java:163)
        at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:104)
        at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run(AbstractInvocationFuture.java:251)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
        at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
        at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)

Hiccups measured while running test 'testLongRunning(com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl_invokeOnPartitionsTest):'
15:27:10, accumulated pauses: 4128 ms, max pause: 2434 ms, pauses over 1000 ms: 2
15:27:15, accumulated pauses: 5392 ms, max pause: 2681 ms, pauses over 1000 ms: 2
15:27:20, accumulated pauses: 241 ms, max pause: 48 ms, pauses over 1000 ms: 0
```
