### ISSUE TITLE
Split brain protection over verbose QuorumException stack trace logging from Durable / regular  Executor

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#12178]
durable executor service and "regular" executor service print an overly verbose stack trace 

we note the Scheduled executor service or any of the other structures that are configured to run with split brain protection/quorum, do not produce such overvley verbose logging.

the test is https://hazelcast-l337.ci.cloudbees.com/view/split/job/split-quorum/31/console
and the logs from the "NO" quorum side of the cluster very quickly grow to multi GB
due to the following verbose stack trace printed 

```
java.util.concurrent.ExecutionException: com.hazelcast.quorum.QuorumException: Split brain protection exception: There is not enough members in the cluster. Required size: 3, current size: 2
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:92)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:155)
	at com.hazelcast.durableexecutor.impl.DurableExecutorServiceProxy.submitToPartition(DurableExecutorServiceProxy.java:257)
	at com.hazelcast.durableexecutor.impl.DurableExecutorServiceProxy.submit(DurableExecutorServiceProxy.java:154)
	at hzcmd.executor.durable.SubmitAndUse.timeStep(SubmitAndUse.java:16)
	at remote.bench.marker.MetricsMarker.flatOut(MetricsMarker.java:53)
	at remote.bench.marker.MetricsMarker.bench(MetricsMarker.java:40)
	at remote.bench.BenchThread.call(BenchThread.java:38)
	at remote.bench.BenchThread.call(BenchThread.java:12)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:473)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.hazelcast.quorum.QuorumException: Split brain protection exception: There is not enough members in the cluster. Required size: 3, current size: 2
	at com.hazelcast.quorum.impl.QuorumImpl.newQuorumException(QuorumImpl.java:175)
	at com.hazelcast.quorum.impl.QuorumImpl.ensureQuorumPresent(QuorumImpl.java:166)
	at com.hazelcast.quorum.impl.QuorumImpl.ensureQuorumPresent(QuorumImpl.java:161)
	at com.hazelcast.quorum.impl.QuorumServiceImpl.ensureQuorumPresent(QuorumServiceImpl.java:138)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.ensureQuorumPresent(OperationRunnerImpl.java:277)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:187)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:406)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:115)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:100)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:127)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:79)
	... 14 more
```

```
java.util.concurrent.ExecutionException: com.hazelcast.quorum.QuorumException: Split brain protection exception: There is not enough members in the cluster. Required size: 3, current size: 2
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:92)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:155)
	at com.hazelcast.util.executor.DelegatingFuture.get(DelegatingFuture.java:83)
	at hzcmd.executor.regular.SubmitToAllAndUse.timeStep(SubmitToAllAndUse.java:23)
	at remote.bench.marker.MetricsMarker.flatOut(MetricsMarker.java:53)
	at remote.bench.marker.MetricsMarker.bench(MetricsMarker.java:40)
	at remote.bench.BenchThread.call(BenchThread.java:38)
	at remote.bench.BenchThread.call(BenchThread.java:12)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:473)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.hazelcast.quorum.QuorumException: Split brain protection exception: There is not enough members in the cluster. Required size: 3, current size: 2
	at com.hazelcast.quorum.impl.QuorumImpl.newQuorumException(QuorumImpl.java:175)
	at com.hazelcast.quorum.impl.QuorumImpl.ensureQuorumPresent(QuorumImpl.java:166)
	at com.hazelcast.quorum.impl.QuorumImpl.ensureQuorumPresent(QuorumImpl.java:161)
	at com.hazelcast.quorum.impl.QuorumServiceImpl.ensureQuorumPresent(QuorumServiceImpl.java:138)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.ensureQuorumPresent(OperationRunnerImpl.java:277)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:187)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:406)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:115)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:100)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:127)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:79)
	... 13 more
```

**Comment by Danny-Hazelcast** [comment]
https://hazelcast-l337.ci.cloudbees.com/view/split/job/split-quorum/31/console

http://54.82.84.143/~jenkins/workspace/split-quorum/3.10-SNAPSHOT/2018_01_19-11_06_28/quorum/


small sub cluster  1G of logs 
http://54.82.84.143/~jenkins/workspace/split-quorum/3.10-SNAPSHOT/2018_01_19-11_06_28/quorum/output/HZ/HzClient4HZAA/
http://54.82.84.143/~jenkins/workspace/split-quorum/3.10-SNAPSHOT/2018_01_19-11_06_28/quorum/output/HZ/HzMember4HZAA/



big sub cluster kb's of logs 
http://54.82.84.143/~jenkins/workspace/split-quorum/3.10-SNAPSHOT/2018_01_19-11_06_28/quorum/output/HZ/HzClient1HZBB/
http://54.82.84.143/~jenkins/workspace/split-quorum/3.10-SNAPSHOT/2018_01_19-11_06_28/quorum/output/HZ/HzMember1HZBB/

**Comment by tombujok** [comment]
I guess it's due to the fact that you generated multiple tasks and then split the clusters, so each task gets executed and gets a quorum exception.

**Comment by mmedenjak** [comment]
I'm looking at this issue a bit and here are the findings. If I'm not mistaken, the test is actually doing the logging, not the hazelcast instance itself - https://github.com/hazelcast/hzCmd-bench/blob/6a0720466a297408c2abe315599b17b24d24d27c/src/main/java/hzcmd/executor/regular/SubmitToAllAndUse.java#L22-L28

So you may opt not to log the `ExecutionException` if the cause is a `QuorumException`:
``` java
            try {
                Integer i = future.get();
            } catch (InterruptedException e) {
                e.printStackTrace();
            } catch (ExecutionException e) {
                if (e.getCause() instanceof QuorumException) {
                    throw (QuorumException) e.getCause();
                }
                e.printStackTrace();
            }
```
Now there's the other question whether the `QuorumException` should be wrapped in a `ExecutionException` at all or if the call to the `*Executor.submit*` methods should directly throw the `QuorumException`. It is certainly possible but I seem to think it's ok to wrap it in the `ExecutionException`. The javadoc says:
```
/**
 * Exception thrown when attempting to retrieve the result of a task
 * that aborted by throwing an exception. This exception can be
 * inspected using the {@link #getCause()} method.
 */
```
And the javadoc of `Future#get`:
```
     * @throws ExecutionException if the computation threw an
     * exception
```
In this sense it's sensible the future is wrapping the `QuorumException` - once the call to e.g. `DurableExecutorServiceProxy.submit` is made, you just get the `Future`. We don't know if the quorum is present or not. We would need to block the thread to find that out.

WDYT? Can you modify the test so that it doesn't log `ExecutionException` if the cause is `QuorumException`?

**Comment by Danny-Hazelcast** [comment]
@mmedenjak  ok i did not see that it was me makingthe logging, bit of an oversight there, not very good

**Comment by Danny-Hazelcast** [comment]
o dear is was all my fault i was logging stack trace.

**Comment by mmedenjak** [comment]
not to worry! :)
