### ISSUE TITLE
ClientMultiMapQuorumReadTest & MultiMapQuorumReadTest Failures

### ISSUE THREAD

**Issue by Donnerbart** [hazelcast/hazelcast#12176]
**com.hazelcast.client.quorum.multimap.ClientMultiMapQuorumReadTest.aggregate_successful_whenQuorumSize_notMet[quorumType:READ]**
```java
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.lang.Object.wait(Native Method)
	at com.hazelcast.spi.impl.AbstractCompletableFuture.get(AbstractCompletableFuture.java:230)
	at com.hazelcast.spi.impl.AbstractCompletableFuture.get(AbstractCompletableFuture.java:191)
	at com.hazelcast.client.proxy.ClientMultiMapProxy.aggregate(ClientMultiMapProxy.java:447)
	at com.hazelcast.client.proxy.ClientMultiMapProxy.aggregate(ClientMultiMapProxy.java:421)
	at com.hazelcast.quorum.multimap.MultiMapQuorumReadTest.aggregate_successful_whenQuorumSize_notMet(MultiMapQuorumReadTest.java:185)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.lang.Thread.run(Thread.java:745)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/12892/testReport/junit/com.hazelcast.client.quorum.multimap/ClientMultiMapQuorumReadTest/aggregate_successful_whenQuorumSize_notMet_quorumType_READ_/

**Comment by Donnerbart** [comment]
**com.hazelcast.client.quorum.multimap.ClientMultiMapQuorumReadTest.aggregate_successful_whenQuorumSize_notMet[quorumType:READ]**
```java
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.lang.Object.wait(Native Method)
	at com.hazelcast.spi.impl.AbstractCompletableFuture.get(AbstractCompletableFuture.java:230)
	at com.hazelcast.spi.impl.AbstractCompletableFuture.get(AbstractCompletableFuture.java:191)
	at com.hazelcast.client.proxy.ClientMultiMapProxy.aggregate(ClientMultiMapProxy.java:447)
	at com.hazelcast.client.proxy.ClientMultiMapProxy.aggregate(ClientMultiMapProxy.java:421)
	at com.hazelcast.quorum.multimap.MultiMapQuorumReadTest.aggregate_successful_whenQuorumSize_notMet(MultiMapQuorumReadTest.java:185)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.lang.Thread.run(Thread.java:745)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/12955/testReport/junit/com.hazelcast.client.quorum.multimap/ClientMultiMapQuorumReadTest/aggregate_successful_whenQuorumSize_notMet_quorumType_READ_/

**Comment by hasancelik** [comment]
**MultiMapQuorumReadTest.aggregate_successful_whenQuorumSize_met**
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.lang.Object.wait(Native Method)
	at com.hazelcast.spi.impl.AbstractCompletableFuture.get(AbstractCompletableFuture.java:230)
	at com.hazelcast.spi.impl.AbstractCompletableFuture.get(AbstractCompletableFuture.java:191)
	at com.hazelcast.multimap.impl.ObjectMultiMapProxy.aggregate(ObjectMultiMapProxy.java:363)
	at com.hazelcast.multimap.impl.ObjectMultiMapProxy.aggregate(ObjectMultiMapProxy.java:338)
	at com.hazelcast.quorum.multimap.MultiMapQuorumReadTest.aggregate_successful_whenQuorumSize_met(MultiMapQuorumReadTest.java:184)
Standard Output
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK1.6-freestyle/374/testReport/junit/com.hazelcast.quorum.multimap/MultiMapQuorumReadTest/aggregate_successful_whenQuorumSize_met_quorumType_READ_/

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-freestyle/1613/testReport/junit/com.hazelcast.quorum.multimap/MultiMapQuorumReadTest/aggregate_successful_whenQuorumSize_notMet_quorumType_READ_/

**Comment by hasancelik** [comment]
**MultiMapQuorumReadTest.aggregate_successful_whenQuorumSize_notMet**
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.lang.Object.wait(Native Method)
	at com.hazelcast.spi.impl.AbstractCompletableFuture.get(AbstractCompletableFuture.java:230)
	at com.hazelcast.spi.impl.AbstractCompletableFuture.get(AbstractCompletableFuture.java:191)
	at com.hazelcast.multimap.impl.ObjectMultiMapProxy.aggregate(ObjectMultiMapProxy.java:363)
	at com.hazelcast.multimap.impl.ObjectMultiMapProxy.aggregate(ObjectMultiMapProxy.java:338)
	at com.hazelcast.quorum.multimap.MultiMapQuorumReadTest.aggregate_successful_whenQuorumSize_notMet(MultiMapQuorumReadTest.java:189)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-freestyle/1661/testReport/junit/com.hazelcast.quorum.multimap/MultiMapQuorumReadTest/aggregate_successful_whenQuorumSize_notMet_quorumType_READ_/

**Comment by jerrinot** [comment]
these tests are using the old M-R based aggregations. The old aggregations are deprecated and I believe we can safely ignore these.
