### ISSUE TITLE
CacheQuorumWriteTest

### ISSUE THREAD

**Issue by Donnerbart** [hazelcast/hazelcast#12177]
**com.hazelcast.quorum.cache.CacheQuorumWriteTest.putAll_quorum[quorumType:READ_WRITE]**
```java
com.hazelcast.cache.CacheNotExistsException: Cache /hz/quorumef4fe53f-86bd-453c-8f73-409ec0523710READ_WRITE is already destroyed or not created yet, on Member [127.0.0.1]:5480 - 6bdc8a3e-4320-4901-9ad3-5dfdd4a32cde this
	at com.hazelcast.cache.impl.AbstractCacheRecordStore.<init>(AbstractCacheRecordStore.java:121)
	at com.hazelcast.cache.impl.CacheRecordStore.<init>(CacheRecordStore.java:69)
	at com.hazelcast.cache.impl.CacheService.createNewRecordStore(CacheService.java:69)
	at com.hazelcast.cache.impl.CachePartitionSegment.createNew(CachePartitionSegment.java:52)
	at com.hazelcast.cache.impl.CachePartitionSegment.createNew(CachePartitionSegment.java:37)
	at com.hazelcast.util.ConcurrencyUtil.getOrPutSynchronized(ConcurrencyUtil.java:73)
	at com.hazelcast.cache.impl.CachePartitionSegment.getOrCreateRecordStore(CachePartitionSegment.java:74)
	at com.hazelcast.cache.impl.AbstractCacheService.getOrCreateRecordStore(AbstractCacheService.java:268)
	at com.hazelcast.cache.impl.operation.CachePutAllOperation.getServiceNamespace(CachePutAllOperation.java:143)
	at com.hazelcast.cache.impl.operation.CachePutAllOperation.getServiceNamespace(CachePutAllOperation.java:46)
	at com.hazelcast.quorum.impl.QuorumServiceImpl.getQuorumName(QuorumServiceImpl.java:191)
	at com.hazelcast.quorum.impl.QuorumServiceImpl.findQuorum(QuorumServiceImpl.java:181)
	at com.hazelcast.quorum.impl.QuorumServiceImpl.ensureQuorumPresent(QuorumServiceImpl.java:134)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.ensureQuorumPresent(OperationRunnerImpl.java:277)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:187)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:406)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:115)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:100)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:127)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:79)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:155)
	at com.hazelcast.cache.impl.AbstractCacheProxy.putToAllPartitionsAndWaitForCompletion(AbstractCacheProxy.java:273)
	at com.hazelcast.cache.impl.AbstractCacheProxy.putAll(AbstractCacheProxy.java:226)
	at com.hazelcast.cache.impl.CacheProxy.putAll(CacheProxy.java:80)
	at com.hazelcast.cache.impl.CacheProxy.putAll(CacheProxy.java:147)
	at com.hazelcast.quorum.cache.CacheQuorumWriteTest.putAll_quorum(CacheQuorumWriteTest.java:141)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/12903/testReport/junit/com.hazelcast.quorum.cache/CacheQuorumWriteTest/putAll_quorum_quorumType_READ_WRITE_/

**Comment by Donnerbart** [comment]
**com.hazelcast.quorum.cache.CacheQuorumWriteTest.putAll_quorum[quorumType:READ_WRITE]**
```java
com.hazelcast.cache.CacheNotExistsException: Cache /hz/quorumf97f192a-fe50-4453-a863-c79094ea4c7bREAD_WRITE is already destroyed or not created yet, on Member [127.0.0.1]:5193 - 022305e5-467a-4a37-ab49-3caf05fde6f7 this
	at com.hazelcast.cache.impl.AbstractCacheRecordStore.<init>(AbstractCacheRecordStore.java:132)
	at com.hazelcast.cache.impl.CacheRecordStore.<init>(CacheRecordStore.java:61)
	at com.hazelcast.cache.impl.CacheService.createNewRecordStore(CacheService.java:69)
	at com.hazelcast.cache.impl.CachePartitionSegment.createNew(CachePartitionSegment.java:52)
	at com.hazelcast.cache.impl.CachePartitionSegment.createNew(CachePartitionSegment.java:37)
	at com.hazelcast.util.ConcurrencyUtil.getOrPutSynchronized(ConcurrencyUtil.java:73)
	at com.hazelcast.cache.impl.CachePartitionSegment.getOrCreateRecordStore(CachePartitionSegment.java:74)
	at com.hazelcast.cache.impl.AbstractCacheService.getOrCreateRecordStore(AbstractCacheService.java:268)
	at com.hazelcast.cache.impl.operation.CachePutAllOperation.getServiceNamespace(CachePutAllOperation.java:143)
	at com.hazelcast.cache.impl.operation.CachePutAllOperation.getServiceNamespace(CachePutAllOperation.java:46)
	at com.hazelcast.quorum.impl.QuorumServiceImpl.getQuorumName(QuorumServiceImpl.java:191)
	at com.hazelcast.quorum.impl.QuorumServiceImpl.findQuorum(QuorumServiceImpl.java:181)
	at com.hazelcast.quorum.impl.QuorumServiceImpl.ensureQuorumPresent(QuorumServiceImpl.java:134)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.ensureQuorumPresent(OperationRunnerImpl.java:277)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:187)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:406)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:115)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:100)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:127)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:79)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:155)
	at com.hazelcast.cache.impl.AbstractCacheProxy.putToAllPartitionsAndWaitForCompletion(AbstractCacheProxy.java:273)
	at com.hazelcast.cache.impl.AbstractCacheProxy.putAll(AbstractCacheProxy.java:226)
	at com.hazelcast.cache.impl.CacheProxy.putAll(CacheProxy.java:80)
	at com.hazelcast.cache.impl.CacheProxy.putAll(CacheProxy.java:147)
	at com.hazelcast.quorum.cache.CacheQuorumWriteTest.putAll_quorum(CacheQuorumWriteTest.java:145)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/13232/testReport/junit/com.hazelcast.quorum.cache/CacheQuorumWriteTest/putAll_quorum_quorumType_READ_WRITE_/
