### ISSUE TITLE
QuorumException logged in app console

### ISSUE THREAD

**Issue by dbydzovsky** [hazelcast/hazelcast#12188]
Hi Hazelcast team 🥇 

I would like to submit new minor issue, which is uncatched exception during initialization, which is printed into app console instead of logging into log file. See attached file with stack trace.

**Steps to reproduce are**
1. Install cluster with 3 nodes.
2. Start all nodes.
3. Increase cluster size up to 7 nodes.
4. Stop and start one node 
5. There occurs an stack trace in app console during spring boot app initialization

```
Exception in thread "hz._hzInstance_1_Scaler-1e2946d9-hzl-cluster}.cached.thread-7" com.hazelcast.quorum.QuorumException: Cluster quorum failed
	at com.hazelcast.quorum.impl.QuorumImpl.newQuorumException(QuorumImpl.java:164)
	at com.hazelcast.quorum.impl.QuorumImpl.ensureQuorumPresent(QuorumImpl.java:158)
	at com.hazelcast.quorum.impl.QuorumServiceImpl.ensureQuorumPresent(QuorumServiceImpl.java:127)
```
..more in the attached file [stacktraceHazelcast.txt](https://github.com/hazelcast/hazelcast/files/1652329/stacktraceHazelcast.txt)

We use 3.9.2 hazelcast together with spring boot 1.5.8.RELEASE.
We have cluster size set to 7, but number of clients is actually 3 (so quorum is broken).
Java version is "1.8.0_152" 64, Windows 10

**Our expectation is that the stack trace is logged into log file instead of in console.**

Thank you very much!
Dominik

**Comment by mdogan** [comment]
Full stack trace:
```
Exception in thread "hz._hzInstance_1_Scaler-1e2946d9-hzl-cluster}.cached.thread-7" com.hazelcast.quorum.QuorumException: Cluster quorum failed
	at com.hazelcast.quorum.impl.QuorumImpl.newQuorumException(QuorumImpl.java:164)
	at com.hazelcast.quorum.impl.QuorumImpl.ensureQuorumPresent(QuorumImpl.java:158)
	at com.hazelcast.quorum.impl.QuorumServiceImpl.ensureQuorumPresent(QuorumServiceImpl.java:127)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.ensureQuorumPresent(OperationRunnerImpl.java:245)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:186)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:409)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:115)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:100)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:127)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:79)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:147)
	at com.hazelcast.spi.impl.operationservice.impl.InvokeOnPartitions.retryFailedPartitions(InvokeOnPartitions.java:144)
	at com.hazelcast.spi.impl.operationservice.impl.InvokeOnPartitions.invoke(InvokeOnPartitions.java:74)
	at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.invokeOnAllPartitions(OperationServiceImpl.java:383)
	at com.hazelcast.map.impl.proxy.MapProxySupport.addIndex(MapProxySupport.java:1165)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.addIndex(MapProxyImpl.java:111)
	at com.hazelcast.map.impl.proxy.MapProxySupport.initializeIndexes(MapProxySupport.java:288)
	at com.hazelcast.map.impl.proxy.MapProxySupport.initialize(MapProxySupport.java:226)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.initialize(MapProxyImpl.java:111)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyRegistry.doCreateProxy(ProxyRegistry.java:194)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyRegistry.createProxy(ProxyRegistry.java:184)
	at com.hazelcast.spi.impl.proxyservice.impl.operations.PostJoinProxyOperation$CreateProxyTask.run(PostJoinProxyOperation.java:126)
	at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:227)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
```

It seems quorum fails while initializing IMap (initializing & adding indexes) in `PostJoinProxyOperation`. This `QuorumException` is not delegated to the caller and not catched & printed via logger, that's why it's caught by the default `UncaughtExceptionHandler` and printed to the console.
