### ISSUE TITLE
Heartbeat timed out to owner connection when network delay present

### ISSUE THREAD

**Issue by lazerion** [hazelcast/hazelcast#12185]
Hi, 

Hazelcast Client/Server version: 3.10-SNAPSHOT (20180118 - f77afed) 

- Cluster of 5 member is up and running 
- Quorum size is 3
- Quorum type is  READ_WRITE
- Cluster member network timeouts and attempt counts [100 ms timeout, and 2 attempts max] details are also given below.

When we put network delay of 5000 ms on two nodes including owner on cluster, and during that time we use `IList` add operation with 10 ms sleeps.

We got below error on client
```
Caused by: com.hazelcast.spi.exception.TargetDisconnectedException: Heartbeat timed out to owner connection ClientConnection{alive=true, connectionId=1, channel=NioChannel{/172.20.0.3:34017->hazelcast/172.20.0.2:5701}, remoteEndpoint=[172.20.0.2]:5701, lastReadTime=2018-01-19 19:05:39.175, lastWriteTime=2018-01-19 19:05:39.186, closedTime=never, lastHeartbeatRequested=2018-01-19 19:05:34.874, lastHeartbeatReceived=2018-01-19 19:05:34.876, connected server version=3.10-SNAPSHOT}
        at com.hazelcast.client.connection.nio.DefaultClientConnectionStrategy.onHeartbeatStopped(DefaultClientConnectionStrategy.java:119)
        at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.heartbeatStopped(ClientConnectionManagerImpl.java:706)
        at com.hazelcast.client.connection.nio.HeartbeatManager.fireHeartbeatStopped(HeartbeatManager.java:130)
        at com.hazelcast.client.connection.nio.ClientICMPManager$PeriodicPingTask.run(ClientICMPManager.java:179)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
        at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
        at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)

```
These are statistics regarding that period of time success=2361, failures=0, **exceptions=1**

Client config
```
<network>
        <icmp-ping enabled="true">
            <timeout-milliseconds>100</timeout-milliseconds>
            <interval-milliseconds>1000</interval-milliseconds>
            <ttl>255</ttl>
            <max-attempts>2</max-attempts>
            <echo-fail-fast-on-startup>true</echo-fail-fast-on-startup>
        </icmp-ping>
        <cluster-members>
            <address>hazelcast</address>
        </cluster-members>
        <socket-options>
            <linger-seconds>0</linger-seconds>
        </socket-options>
    </network>
```

Server config
```
<properties>
        <property name="hazelcast.icmp.enabled">true</property>
        <property name="hazelcast.icmp.timeout">100</property>
        <property name="hazelcast.icmp.interval">1000</property>
        <property name="hazelcast.icmp.ttl">255</property>
        <property name="hazelcast.icmp.max.attempts">2</property>
        <property name="hazelcast.icmp.echo.fail.fast.on.startup">true</property>
        <property name="hazelcast.merge.next.run.delay.seconds">10</property>
        <property name="hazelcast.merge.first.run.delay.seconds">20</property>
        <!-- default is 5000 ms -->
        <property name="hazelcast.operation.backup.timeout.millis">1000</property>
    </properties>

    <quorum name="q3" enabled="true">
        <quorum-size>3</quorum-size>
    </quorum>

    <list name="default">
        <quorum-ref>q3</quorum-ref>
        <backup-count>2</backup-count>
    </list>
```

Our expectation was to get no exceptions, including Quorum protection, are we missing configuration setting?

**Comment by lazerion** [comment]
We got similar error when two non-owner member removed from network, this time it is sporadic, with same settings given in previous comment.

Steps:
1] Initial cluster size is 5
2]Start adding items to list with 10 ms delays
3] remove 2 non-owner member from network
4] wait 5 secs
5] Verify new cluster size is 3
6] stop adding items to quorum protected list

```
INFO: hz.client_0 [hz-quorum] [3.10-SNAPSHOT] 

Members [5] {
        Member [172.22.0.6]:5701 - 12cf96c2-03f2-4943-aba9-eadd3ba85ebd
        Member [172.22.0.4]:5701 - c8441609-ecb1-43c6-9a16-337e7e124930
        Member [172.22.0.2]:5701 - b7b8adcf-f202-4618-bede-3d957dcde670
        Member [172.22.0.3]:5701 - b5ee42a8-e776-4850-88cd-e8f0d8fdca50
        Member [172.22.0.5]:5701 - 9f124369-190d-45a7-bf5a-1736b8b3a8a0
}

Jan 27, 2018 5:06:58 PM com.hazelcast.client.connection.ClientConnectionManager
INFO: hz.client_0 [hz-quorum] [3.10-SNAPSHOT] Setting ClientConnection{alive=true, connectionId=2, channel=NioChannel{/172.22.0.7:37803->hz-1/172.22.0.2:5701}, remoteEndpoint=[172.22.0.2]:5701, lastReadTime=2018-01-27 17:06:58.065, lastWriteTime=2018-01-27 17:06:58.061, closedTime=never, lastHeartbeatRequested=never, lastHeartbeatReceived=never, connected server version=3.10-SNAPSHOT} as owner with principal ClientPrincipal{uuid='1b612982-f0fd-4139-8173-6d14a8b54912', ownerUuid='b7b8adcf-f202-4618-bede-3d957dcde670'}
Jan 27, 2018 5:06:58 PM com.hazelcast.core.LifecycleService
INFO: hz.client_0 [hz-quorum] [3.10-SNAPSHOT] HazelcastClient 3.10-SNAPSHOT (20180118 - f77afed) is CLIENT_CONNECTED
Jan 27, 2018 5:06:58 PM com.hazelcast.internal.diagnostics.Diagnostics
INFO: hz.client_0 [hz-quorum] [3.10-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
Jan 27, 2018 5:06:59 PM com.hazelcast.client.connection.ClientConnectionManager
INFO: hz.client_0 [hz-quorum] [3.10-SNAPSHOT] Authenticated with server [172.22.0.3]:5701, server version:3.10-SNAPSHOT Local address: /172.22.0.7:33417
Jan 27, 2018 5:06:59 PM com.hazelcast.client.connection.ClientConnectionManager
INFO: hz.client_0 [hz-quorum] [3.10-SNAPSHOT] Authenticated with server [172.22.0.4]:5701, server version:3.10-SNAPSHOT Local address: /172.22.0.7:45731
Jan 27, 2018 5:06:59 PM com.hazelcast.client.connection.ClientConnectionManager
INFO: hz.client_0 [hz-quorum] [3.10-SNAPSHOT] Authenticated with server [172.22.0.6]:5701, server version:3.10-SNAPSHOT Local address: /172.22.0.7:42261
Jan 27, 2018 5:06:59 PM com.hazelcast.client.connection.ClientConnectionManager
INFO: hz.client_0 [hz-quorum] [3.10-SNAPSHOT] Authenticated with server [172.22.0.5]:5701, server version:3.10-SNAPSHOT Local address: /172.22.0.7:35207
Jan 27, 2018 5:06:59 PM com.hazelcast.client.connection.nio.ClientICMPManager
WARNING: hz.client_0 [hz-quorum] [3.10-SNAPSHOT] Could not ping [172.22.0.6]:5701
Jan 27, 2018 5:07:00 PM com.hazelcast.client.connection.nio.ClientICMPManager
WARNING: hz.client_0 [hz-quorum] [3.10-SNAPSHOT] Could not ping [172.22.0.6]:5701
Jan 27, 2018 5:07:00 PM com.hazelcast.client.connection.nio.ClientICMPManager
WARNING: hz.client_0 [hz-quorum] [3.10-SNAPSHOT] Could not ping [172.22.0.4]:5701
[pool-1-thread-1] ERROR com.hazelcast.quorum.it.client.Nanny - Exception during operation Heartbeat timed out to ClientConnection{alive=true, connectionId=3, channel=NioChannel{/172.22.0.7:42261->/172.22.0.6:5701}, remoteEndpoint=[172.22.0.6]:5701, lastReadTime=2018-01-27 17:06:59.454, lastWriteTime=2018-01-27 17:06:59.465, closedTime=never, lastHeartbeatRequested=never, lastHeartbeatReceived=never, connected server version=3.10-SNAPSHOT}
com.hazelcast.spi.exception.TargetDisconnectedException: Heartbeat timed out to ClientConnection{alive=true, connectionId=3, channel=NioChannel{/172.22.0.7:42261->/172.22.0.6:5701}, remoteEndpoint=[172.22.0.6]:5701, lastReadTime=2018-01-27 17:06:59.454, lastWriteTime=2018-01-27 17:06:59.465, closedTime=never, lastHeartbeatRequested=never, lastHeartbeatReceived=never, connected server version=3.10-SNAPSHOT}
        at com.hazelcast.client.spi.impl.AbstractClientInvocationService$CleanResourcesTask.notifyException(AbstractClientInvocationService.java:225)
        at com.hazelcast.client.spi.impl.AbstractClientInvocationService$CleanResourcesTask.run(AbstractClientInvocationService.java:211)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at com.hazelcast.util.executor.LoggingScheduledExecutor$LoggingDelegatingFuture.run(LoggingScheduledExecutor.java:160)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
        at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
        at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
        at ------ submitted from ------.(Unknown Source)
        at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:96)
        at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:33)
        at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:155)
        at com.hazelcast.client.spi.ClientProxy.invokeOnPartition(ClientProxy.java:204)
        at com.hazelcast.client.proxy.PartitionSpecificClientProxy.invokeOnPartition(PartitionSpecificClientProxy.java:49)
        at com.hazelcast.client.proxy.ClientListProxy.add(ClientListProxy.java:169)
        at com.hazelcast.quorum.it.client.Nanny.lambda$runOn$0(Nanny.java:33)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Jan 27, 2018 5:07:01 PM com.hazelcast.client.spi.impl.ClientMembershipListener
INFO: hz.client_0 [hz-quorum] [3.10-SNAPSHOT] 

Members [4] {
        Member [172.22.0.4]:5701 - c8441609-ecb1-43c6-9a16-337e7e124930
        Member [172.22.0.2]:5701 - b7b8adcf-f202-4618-bede-3d957dcde670
        Member [172.22.0.3]:5701 - b5ee42a8-e776-4850-88cd-e8f0d8fdca50
        Member [172.22.0.5]:5701 - 9f124369-190d-45a7-bf5a-1736b8b3a8a0
}

Jan 27, 2018 5:07:01 PM com.hazelcast.client.connection.nio.ClientConnection
WARNING: hz.client_0 [hz-quorum] [3.10-SNAPSHOT] ClientConnection{alive=false, connectionId=3, channel=NioChannel{/172.22.0.7:42261->/172.22.0.6:5701}, remoteEndpoint=[172.22.0.6]:5701, lastReadTime=2018-01-27 17:06:59.454, lastWriteTime=2018-01-27 17:06:59.465, closedTime=2018-01-27 17:07:01.728, lastHeartbeatRequested=never, lastHeartbeatReceived=never, connected server version=3.10-SNAPSHOT} closed. Reason: com.hazelcast.spi.exception.TargetDisconnectedException[The client has closed the connection to this member, after receiving a member left event from the cluster. ClientConnection{alive=true, connectionId=3, channel=NioChannel{/172.22.0.7:42261->/172.22.0.6:5701}, remoteEndpoint=[172.22.0.6]:5701, lastReadTime=2018-01-27 17:06:59.454, lastWriteTime=2018-01-27 17:06:59.465, closedTime=never, lastHeartbeatRequested=never, lastHeartbeatReceived=never, connected server version=3.10-SNAPSHOT}]
com.hazelcast.spi.exception.TargetDisconnectedException: The client has closed the connection to this member, after receiving a member left event from the cluster. ClientConnection{alive=true, connectionId=3, channel=NioChannel{/172.22.0.7:42261->/172.22.0.6:5701}, remoteEndpoint=[172.22.0.6]:5701, lastReadTime=2018-01-27 17:06:59.454, lastWriteTime=2018-01-27 17:06:59.465, closedTime=never, lastHeartbeatRequested=never, lastHeartbeatReceived=never, connected server version=3.10-SNAPSHOT}
        at com.hazelcast.client.spi.impl.ClientMembershipListener.newTargetDisconnectedExceptionCausedByMemberLeftEvent(ClientMembershipListener.java:203)
        at com.hazelcast.client.spi.impl.ClientMembershipListener.memberRemoved(ClientMembershipListener.java:159)
        at com.hazelcast.client.spi.impl.ClientMembershipListener.handle(ClientMembershipListener.java:77)
        at com.hazelcast.client.impl.protocol.codec.ClientAddMembershipListenerCodec$AbstractEventHandler.handle(ClientAddMembershipListenerCodec.java:182)
        at com.hazelcast.client.spi.impl.ClientMembershipListener.handle(ClientMembershipListener.java:48)
        at com.hazelcast.client.spi.impl.listener.AbstractClientListenerService$ClientEventProcessor.run(AbstractClientListenerService.java:129)
        at com.hazelcast.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:225)
        at com.hazelcast.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:208)

Jan 27, 2018 5:07:01 PM com.hazelcast.client.connection.ClientConnectionManager
INFO: hz.client_0 [hz-quorum] [3.10-SNAPSHOT] Removed connection to endpoint: [172.22.0.6]:5701, connection: ClientConnection{alive=false, connectionId=3, channel=NioChannel{0.0.0.0/0.0.0.0:42261->/172.22.0.6:5701}, remoteEndpoint=[172.22.0.6]:5701, lastReadTime=2018-01-27 17:06:59.454, lastWriteTime=2018-01-27 17:07:01.729, closedTime=2018-01-27 17:07:01.728, lastHeartbeatRequested=never, lastHeartbeatReceived=never, connected server version=3.10-SNAPSHOT}
Jan 27, 2018 5:07:01 PM com.hazelcast.client.spi.impl.ClientMembershipListener
INFO: hz.client_0 [hz-quorum] [3.10-SNAPSHOT] 

Members [3] {
        Member [172.22.0.2]:5701 - b7b8adcf-f202-4618-bede-3d957dcde670
        Member [172.22.0.3]:5701 - b5ee42a8-e776-4850-88cd-e8f0d8fdca50
        Member [172.22.0.5]:5701 - 9f124369-190d-45a7-bf5a-1736b8b3a8a0
}
```
Our expectation was to get no exceptions, including Quorum protection.

**Comment by sancar** [comment]
Getting exception when connection is broken is expected, because operations are not read-only. 
When connection is broken while operation is being done, since we don't get a response, we don't know if operation is applied on server or not. In that case, we throw `TargetDisconnectedException`. In short, current behaviour is expected. 
One can argue that, client should be able to ask for operation to be applied or not because it is still connected to majority of the cluster. This is not supported right now. 

We could improve these tests by enabling redo-operation. In that case, all operations are retried. And in that case, no exception should be thrown to user application. 
Our documentation related to this is here:
http://docs.hazelcast.org/docs/latest-development/manual/html/Hazelcast_Clients/Java_Client/Getting_Started.html#page_Handling+Retry-able+Operation+Failure

**Comment by lazerion** [comment]
@sancar Thanks for the answer. +1 from me about the support it since client connected to majority of cluster that is healthy w/out enabling redo operation.

**Comment by mmedenjak** [comment]
@lazerion can you change the test so that it uses `redo-operation`? This means that some of the client operations might get run twice instead of once.

I am moving this issue from the https://hazelcast.atlassian.net/wiki/spaces/PM/pages/144540336/Extend+Hazelcast+Split-Brain+Protection PRD since split brain protection is not related to this issue.

**Comment by mmedenjak** [comment]
As I understand here, the issue here is that the client does not receive the response for an operation and is not sure if the operation is applied, thus throwing the `TargetDisconnectedException`. The most intuitive behaviour would be if the client internally retried the operation without user knowledge but this requires exactly-once-delivery guarantees.
As this is a fundamental design change in hazelcast, I'm not sure we are going to implement this in the near future.

**Comment by lazerion** [comment]
@mmedenjak Thanks for the answer, IT suite uses `redo` as enabled.

**Comment by sancar** [comment]
@lazerion The feature request here is to guarantee exactly once delivery. In the current design, we can not add anything to this to improve this area. We are implementing CP data structures to improve the situation. I think we should close this issue saying that work as expected. Is it OK ?

**Comment by burakcelebi** [comment]
Hey @lazerion, have you had a chance to check this? Do you think we can close this? Thanks!

**Comment by lazerion** [comment]
@sancar please feel free to close per your comment.
