### ISSUE TITLE
split brain heal ISet data loss.

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#12234]
@donnerbart 
so, this split 'set' test looses some data after a few iterations of split heal https://hazelcast-l337.ci.cloudbees.com/view/split/job/split-set/14/consoleFull

from the fail 
`fail HzMember3HZBB _set_validate_setA hzcmd.set.SetAssert threadId=0 global.AssertionException: set set_setA414 size 0 != 100`  we see that we have lost all the data out of `set_setA414 `

the loop is
```
split clusters AA BB
untilCluster AA Size2  
untilCluster BB Size3
heal
until AA merged 
untilClusterSafe
validate sets  
```

and as the iterations continue we loose the data out of a 2nd set, we see in the logs that a set with a lower number/name is empty  `set_setA145 size 0 != 100`
I think you were saying that 'set' merging did have this batching optimisations ?  which should prevent merge operation time out
in total the 5 node cluster contains 1000 sets each containing 100 Integers.
test run details  http://54.82.84.143/~jenkins/workspace/split-set/3.10-SNAPSHOT/2018_01_30-04_25_15/merg/

GC looks ok, but I will maker a longer run just to check http://54.82.84.143/~jenkins/workspace/split-set/3.10-SNAPSHOT/2018_01_30-04_25_15/merg/gc.html

from the logs of member3 the first to report data loss out of set 414 http://54.82.84.143/~jenkins/workspace/split-set/3.10-SNAPSHOT/2018_01_30-04_25_15/merg/output/HZ/HzMember3HZBB/out.txt

```
WARNING: [10.0.0.39]:5701 [HZ] [3.10-SNAPSHOT] Following unknown addresses are found in partition table sent from master[[10.0.0.249]:5701]. (Probably they have recently joined or left the cluster.) {
    [10.0.0.134]:5701
}
```

Danny Conlon [4:18 PM]
I see a few of these messages in the logs
```
./HzMember1HZAA/out.txt:WARNING: [10.0.0.134]:5701 [HZ] [3.10-SNAPSHOT] Error while running merge operation: CollectionMergeOperation invocation failed to complete due to operation-heartbeat-timeout. Current time: 2018-01-30 02:46:38.927. Start time: 2018-01-30 02:44:38.280. Total elapsed time: 120647 ms. Last operation heartbeat: never. Last operation heartbeat from member: 2018-01-30 02:46:26.935. Invocation{op=com.hazelcast.collection.impl.collection.operations.CollectionMergeOperation{serviceName='hz:impl:setService', identityHash=27334452, partitionId=57, replicaIndex=0, callId=-827892, invocationTime=1517280278268 (2018-01-30 02:44:38.268), waitTimeout=-1, callTimeout=60000, name=set_setA103}, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=60000, firstInvocationTimeMs=1517280278280, firstInvocationTime='2018-01-30 02:44:38.280', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 00:00:00.000', target=[10.0.0.154]:5701, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=Connection[id=106, /10.0.0.134:38503->/10.0.0.154:5701, endpoint=[10.0.0.154]:5701, alive=true, type=MEMBER]}
```

and some

```
./HzMember4HZBB/out.txt:WARNING: [10.0.0.249]:5701 [HZ] [3.10-SNAPSHOT] Migration failed: MigrationInfo{uuid=d1166263-27ff-4194-85f3-d207371a7423, partitionId=0, source=[10.0.0.154]:5701, sourceUuid=1ac00c1c-7041-43bc-8b7e-dfff79ae5daa, sourceCurrentReplicaIndex=0, sourceNewReplicaIndex=3, destination=[10.0.0.204]:5701, destinationUuid=3f80fbe3-3bb1-4f72-a220-8e75c8895e8e, destinationCurrentReplicaIndex=-1, destinationNewReplicaIndex=0, master=[10.0.0.249]:5701, processing=false, status=ACTIVE}
```

mm is see `./HzMember1HZAA/out.txt:Members {size:1, ver:1} [`
but even the 2 node sub cluster, will not loose data if it splits and rejoins

**Comment by Danny-Hazelcast** [comment]
I added debug logging and diagnostic data to the run below, which failed with set data loss

https://hazelcast-l337.ci.cloudbees.com/view/split/job/split-set/16/console

http://54.82.84.143/~jenkins/workspace/split-set/3.10-SNAPSHOT/2018_02_02-12_57_20/merg/

**Comment by metanet** [comment]
I see a strange pattern on the logs here: http://54.82.84.143/~jenkins/workspace/split-set/3.10-SNAPSHOT/2018_02_02-12_57_20/merg/

2 AA members are merging to the 3-node BB cluster.

Some merge processes encounter the following exception on both AA members:

```
2018-02-02 10:33:23,821 ERROR [hz._hzInstance_1_HZ.cached.thread-12]: [10.0.0.221]:5701 [HZ] While merging...
java.util.concurrent.TimeoutException
	at com.hazelcast.spi.impl.AbstractCompletableFuture.get(AbstractCompletableFuture.java:225)
	at com.hazelcast.internal.cluster.impl.ClusterMergeTask.waitOnFutureInterruptible(ClusterMergeTask.java:169)
	at com.hazelcast.internal.cluster.impl.ClusterMergeTask.executeMergeTasks(ClusterMergeTask.java:152)
	at com.hazelcast.internal.cluster.impl.ClusterMergeTask.run(ClusterMergeTask.java:78)
	at com.hazelcast.instance.LifecycleServiceImpl.runUnderLifecycleLock(LifecycleServiceImpl.java:107)
	at com.hazelcast.internal.cluster.impl.ClusterServiceImpl.merge(ClusterServiceImpl.java:302)
	at com.hazelcast.internal.cluster.impl.operations.MergeClustersOp$1.run(MergeClustersOp.java:63)
	at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:227)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
2018-02-02 10:33:23,822 INFO  [hz._hzInstance_1_HZ.cached.thread-12]: [10.0.0.221]:5701 [HZ] [10.0.0.221]:5701 is MERGED
```

```
2018-02-02 10:33:23,844 ERROR [hz._hzInstance_1_HZ.cached.thread-7]: [10.0.0.33]:5701 [HZ] While merging...
java.util.concurrent.TimeoutException
	at com.hazelcast.spi.impl.AbstractCompletableFuture.get(AbstractCompletableFuture.java:225)
	at com.hazelcast.internal.cluster.impl.ClusterMergeTask.waitOnFutureInterruptible(ClusterMergeTask.java:169)
	at com.hazelcast.internal.cluster.impl.ClusterMergeTask.executeMergeTasks(ClusterMergeTask.java:152)
	at com.hazelcast.internal.cluster.impl.ClusterMergeTask.run(ClusterMergeTask.java:78)
	at com.hazelcast.instance.LifecycleServiceImpl.runUnderLifecycleLock(LifecycleServiceImpl.java:107)
	at com.hazelcast.internal.cluster.impl.ClusterServiceImpl.merge(ClusterServiceImpl.java:302)
	at com.hazelcast.internal.cluster.impl.operations.MergeClustersOp$1.run(MergeClustersOp.java:63)
	at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:227)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
```

2 non-master nodes of the BB cluster always print the following failures when we see this timeout exception:

```
2018-02-02 10:32:21,841 INFO  [hz._hzInstance_1_HZ.priority-generic-operation.thread-0]: [10.0.0.167]:5701 [HZ] [3.10-SNAPSHOT] 

Members {size:5, ver:525} [
	Member [10.0.0.203]:5701 - 7a1cdc15-967b-4a81-88d3-9d0e52276998
	Member [10.0.0.54]:5701 - 5f7678a0-b00b-4ebd-b9bf-a7a3726372d5
	Member [10.0.0.167]:5701 - c90c40e6-6ded-4405-9ab9-35d7a475aaf7 this
	Member [10.0.0.221]:5701 - 44788afe-cc9f-441d-83f4-8f9e8be4440d
	Member [10.0.0.33]:5701 - c95f7edb-d118-4c6c-bfed-f8cea2f2d8b1
]

...

2018-02-02 10:32:26,992 WARN  [hz._hzInstance_1_HZ.IO.thread-in-2]: [10.0.0.167]:5701 [HZ] [3.10-SNAPSHOT] Connection[id=30, /10.0.0.167:42923->/10.0.0.221:5701, endpoint=[10.0.0.221]:5701, alive=false, type=MEMBER] closed. Reason: Exception in Connection[id=30, /10.0.0.167:42923->/10.0.0.221:5701, endpoint=[10.0.0.221]:5701, alive=true, type=MEMBER], thread=hz._hzInstance_1_HZ.IO.thread-in-2
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:197)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:384)
	at com.hazelcast.internal.networking.AbstractChannel.read(AbstractChannel.java:94)
	at com.hazelcast.internal.networking.nio.NioChannelReader.handle(NioChannelReader.java:127)
	at com.hazelcast.internal.networking.nio.NioThread.handleSelectionKey(NioThread.java:401)
	at com.hazelcast.internal.networking.nio.NioThread.handleSelectionKeys(NioThread.java:386)
	at com.hazelcast.internal.networking.nio.NioThread.selectLoop(NioThread.java:293)
	at com.hazelcast.internal.networking.nio.NioThread.run(NioThread.java:248)
2018-02-02 10:32:26,992 WARN  [hz._hzInstance_1_HZ.IO.thread-in-1]: [10.0.0.167]:5701 [HZ] [3.10-SNAPSHOT] Connection[id=31, /10.0.0.167:35975->/10.0.0.33:5701, endpoint=[10.0.0.33]:5701, alive=false, type=MEMBER] closed. Reason: Exception in Connection[id=31, /10.0.0.167:35975->/10.0.0.33:5701, endpoint=[10.0.0.33]:5701, alive=true, type=MEMBER], thread=hz._hzInstance_1_HZ.IO.thread-in-1
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:197)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:384)
	at com.hazelcast.internal.networking.AbstractChannel.read(AbstractChannel.java:94)
	at com.hazelcast.internal.networking.nio.NioChannelReader.handle(NioChannelReader.java:127)
	at com.hazelcast.internal.networking.nio.NioThread.handleSelectionKey(NioThread.java:401)
	at com.hazelcast.internal.networking.nio.NioThread.handleSelectionKeys(NioThread.java:386)
	at com.hazelcast.internal.networking.nio.NioThread.selectLoop(NioThread.java:293)
	at com.hazelcast.internal.networking.nio.NioThread.run(NioThread.java:248)
2018-02-02 10:32:26,993 DEBUG [hz._hzInstance_1_HZ.event-4]: [10.0.0.167]:5701 [HZ] [3.10-SNAPSHOT] Removed connection to [10.0.0.221]:5701
2018-02-02 10:32:26,993 DEBUG [hz._hzInstance_1_HZ.event-5]: [10.0.0.167]:5701 [HZ] [3.10-SNAPSHOT] Removed connection to [10.0.0.33]:5701
2018-02-02 10:32:26,993 INFO  [hz._hzInstance_1_HZ.cached.thread-3]: [10.0.0.167]:5701 [HZ] [3.10-SNAPSHOT] Connecting to /10.0.0.221:5701, timeout: 0, bind-any: true
2018-02-02 10:32:26,993 INFO  [hz._hzInstance_1_HZ.cached.thread-6]: [10.0.0.167]:5701 [HZ] [3.10-SNAPSHOT] Connecting to /10.0.0.33:5701, timeout: 0, bind-any: true
2018-02-02 10:32:26,993 INFO  [hz._hzInstance_1_HZ.cached.thread-3]: [10.0.0.167]:5701 [HZ] [3.10-SNAPSHOT] Established socket connection between /10.0.0.167:39470 and /10.0.0.221:5701
2018-02-02 10:32:26,994 INFO  [hz._hzInstance_1_HZ.cached.thread-6]: [10.0.0.167]:5701 [HZ] [3.10-SNAPSHOT] Established socket connection between /10.0.0.167:39476 and /10.0.0.33:5701
```

```
Members {size:5, ver:525} [
	Member [10.0.0.203]:5701 - 7a1cdc15-967b-4a81-88d3-9d0e52276998
	Member [10.0.0.54]:5701 - 5f7678a0-b00b-4ebd-b9bf-a7a3726372d5 this
	Member [10.0.0.167]:5701 - c90c40e6-6ded-4405-9ab9-35d7a475aaf7
	Member [10.0.0.221]:5701 - 44788afe-cc9f-441d-83f4-8f9e8be4440d
	Member [10.0.0.33]:5701 - c95f7edb-d118-4c6c-bfed-f8cea2f2d8b1
]

...

endpoint=[10.0.0.221]:5701, alive=false, type=MEMBER] closed. Reason: Exception in Connection[id=31, /10.0.0.54:59037->/10.0.0.221:5701, endpoint=[10.0.0.221]:5701, alive=true, type=MEMBER], thread=hz._hzInstance_1_HZ.IO.thread-in-0
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:197)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:384)
	at com.hazelcast.internal.networking.AbstractChannel.read(AbstractChannel.java:94)
	at com.hazelcast.internal.networking.nio.NioChannelReader.handle(NioChannelReader.java:127)
	at com.hazelcast.internal.networking.nio.NioThread.handleSelectionKey(NioThread.java:401)
	at com.hazelcast.internal.networking.nio.NioThread.handleSelectionKeys(NioThread.java:386)
	at com.hazelcast.internal.networking.nio.NioThread.selectLoop(NioThread.java:293)
	at com.hazelcast.internal.networking.nio.NioThread.run(NioThread.java:248)
2018-02-02 10:32:26,855 WARN  [hz._hzInstance_1_HZ.IO.thread-in-1]: [10.0.0.54]:5701 [HZ] [3.10-SNAPSHOT] Connection[id=32, /10.0.0.54:38614->/10.0.0.33:5701, endpoint=[10.0.0.33]:5701, alive=false, type=MEMBER] closed. Reason: Exception in Connection[id=32, /10.0.0.54:38614->/10.0.0.33:5701, endpoint=[10.0.0.33]:5701, alive=true, type=MEMBER], thread=hz._hzInstance_1_HZ.IO.thread-in-1
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:197)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:384)
	at com.hazelcast.internal.networking.AbstractChannel.read(AbstractChannel.java:94)
	at com.hazelcast.internal.networking.nio.NioChannelReader.handle(NioChannelReader.java:127)
	at com.hazelcast.internal.networking.nio.NioThread.handleSelectionKey(NioThread.java:401)
	at com.hazelcast.internal.networking.nio.NioThread.handleSelectionKeys(NioThread.java:386)
	at com.hazelcast.internal.networking.nio.NioThread.selectLoop(NioThread.java:293)
	at com.hazelcast.internal.networking.nio.NioThread.run(NioThread.java:248)
2018-02-02 10:32:26,856 DEBUG [hz._hzInstance_1_HZ.event-4]: [10.0.0.54]:5701 [HZ] [3.10-SNAPSHOT] Removed connection to [10.0.0.221]:5701
2018-02-02 10:32:26,856 DEBUG [hz._hzInstance_1_HZ.event-5]: [10.0.0.54]:5701 [HZ] [3.10-SNAPSHOT] Removed connection to [10.0.0.33]:5701
2018-02-02 10:32:26,856 INFO  [hz._hzInstance_1_HZ.cached.thread-8]: [10.0.0.54]:5701 [HZ] [3.10-SNAPSHOT] Connecting to /10.0.0.221:5701, timeout: 0, bind-any: true
2018-02-02 10:32:26,856 INFO  [hz._hzInstance_1_HZ.cached.thread-2]: [10.0.0.54]:5701 [HZ] [3.10-SNAPSHOT] Connecting to /10.0.0.33:5701, timeout: 0, bind-any: true
2018-02-02 10:32:26,856 INFO  [hz._hzInstance_1_HZ.cached.thread-8]: [10.0.0.54]:5701 [HZ] [3.10-SNAPSHOT] Established socket connection between /10.0.0.54:53109 and /10.0.0.221:5701
2018-02-02 10:32:26,856 INFO  [hz._hzInstance_1_HZ.cached.thread-2]: [10.0.0.54]:5701 [HZ] [3.10-SNAPSHOT] Established socket connection between /10.0.0.54:33846 and /10.0.0.33:5701
```

I am not sure if these connection errors on BB nodes are related to the timeouts we see in AA nodes.

**Comment by mdogan** [comment]
Timed waiting in `ClusterMergeTask ` was removed by https://github.com/hazelcast/hazelcast/pull/12344. 

2 runs seem passed successfully;
- https://hazelcast-l337.ci.cloudbees.com/view/split/job/split-set/17/ 
- https://hazelcast-l337.ci.cloudbees.com/view/split/job/split-set/18/

Started another run just now: https://hazelcast-l337.ci.cloudbees.com/view/split/job/split-set/19/

**Comment by Danny-Hazelcast** [comment]
yes I have seen that this job seems to be passing over the last few day

**Comment by jerrinot** [comment]
@Danny-Hazelcast so this can be closed now?

**Comment by Danny-Hazelcast** [comment]
closing
