### ISSUE TITLE
When minority of members have network delays, Transactional Exceptions on Client 

### ISSUE THREAD

**Issue by lazerion** [hazelcast/hazelcast#12252]
Cluster information
```
Size: 5
Version: Hazelcast 3.10-SNAPSHOT (20180201 - 31dcc3e)
Client Count: 1
Client Docker : FROM openjdk:8-slim (debian)
Member Docker: FROM openjdk:8-jre (debian)
Client log level: DEBUG [slf4j]
Member log level: ALL [jdk]
```
Steps:
1. Sanity check, wait for initial cluster size to be 1, therefore we sure that owner connection is not lost during test
2. Scale cluster size to 5
3. Sanity check that cluster size is 5 
4. Begin generating traffic from client to cluster for Transactional data structures (Set, List, MultiMap)
5. Apply 5000ms delay that is higher than icmp ping timeout and retry attempts
6. Sanity check that cluster size is 3
7. Collect statistics

We have below statistics
```
Statistics QuorumStatistics(success=4311, failures=0, exceptions=8, quorumExceptions=0)
```
Error log segment on client
```
2018-02-05T09:27:13.305576414Z 09:27:13:305 [pool-1-thread-3] ERROR QuorumTask - Exception during operation null
2018-02-05T09:27:13.305594492Z com.hazelcast.transaction.TransactionException
2018-02-05T09:27:13.305781932Z 	at com.hazelcast.client.proxy.txn.ClientTransactionUtil$1.create(ClientTransactionUtil.java:39)
2018-02-05T09:27:13.305796185Z 	at com.hazelcast.util.ExceptionUtil.peel(ExceptionUtil.java:124)
2018-02-05T09:27:13.305976804Z 	at com.hazelcast.util.ExceptionUtil.peel(ExceptionUtil.java:114)
2018-02-05T09:27:13.305985977Z 	at com.hazelcast.util.ExceptionUtil.rethrow(ExceptionUtil.java:134)
2018-02-05T09:27:13.305988633Z 	at com.hazelcast.client.proxy.txn.ClientTransactionUtil.invoke(ClientTransactionUtil.java:59)
2018-02-05T09:27:13.305991011Z 	at com.hazelcast.client.proxy.txn.TransactionProxy.commit(TransactionProxy.java:103)
2018-02-05T09:27:13.305993403Z 	at com.hazelcast.client.proxy.txn.TransactionContextProxy.commitTransaction(TransactionContextProxy.java:83)
2018-02-05T09:27:13.306189165Z 	at com.hazelcast.quorum.it.client.FixtureBuilder.lambda$transactionalMultiMap$36(FixtureBuilder.java:298)
2018-02-05T09:27:13.306197152Z 	at com.hazelcast.quorum.it.client.QuorumTask.call(QuorumTask.java:43)
2018-02-05T09:27:13.306199644Z 	at com.hazelcast.quorum.it.client.QuorumTask.call(QuorumTask.java:18)
2018-02-05T09:27:13.306201982Z 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2018-02-05T09:27:13.306204215Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2018-02-05T09:27:13.306206473Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2018-02-05T09:27:13.306208758Z 	at java.lang.Thread.run(Thread.java:748)
2018-02-05T09:27:13.306210905Z Caused by: java.io.IOException: Packet not sent to [172.25.0.6]:5701
2018-02-05T09:27:13.306410792Z 	at com.hazelcast.client.spi.impl.AbstractClientInvocationService.send(AbstractClientInvocationService.java:127)
2018-02-05T09:27:13.306418775Z 	at com.hazelcast.client.spi.impl.SmartClientInvocationService.invokeOnConnection(SmartClientInvocationService.java:82)
2018-02-05T09:27:13.306421433Z 	at com.hazelcast.client.spi.impl.ClientInvocation.invokeOnSelection(ClientInvocation.java:160)
2018-02-05T09:27:13.306430834Z 	at com.hazelcast.client.spi.impl.ClientInvocation.retry(ClientInvocation.java:190)
2018-02-05T09:27:13.306433433Z 	at com.hazelcast.client.spi.impl.ClientInvocation.run(ClientInvocation.java:178)
2018-02-05T09:27:13.306435604Z 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
2018-02-05T09:27:13.306438189Z 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2018-02-05T09:27:13.306440488Z 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
2018-02-05T09:27:13.306442741Z 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
2018-02-05T09:27:13.306445055Z 	at com.hazelcast.util.executor.LoggingScheduledExecutor$LoggingDelegatingFuture.run(LoggingScheduledExecutor.java:160)
2018-02-05T09:27:13.306646280Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2018-02-05T09:27:13.306654106Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2018-02-05T09:27:13.306656599Z 	at java.lang.Thread.run(Thread.java:748)
2018-02-05T09:27:13.306658835Z 	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
2018-02-05T09:27:13.306661165Z 	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
2018-02-05T09:27:13.306663443Z 	at ------ submitted from ------.(Unknown Source)
2018-02-05T09:27:13.306665679Z 	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:96)
2018-02-05T09:27:13.306667987Z 	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:33)
2018-02-05T09:27:13.306670284Z 	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:155)
2018-02-05T09:27:13.306672584Z 	at com.hazelcast.client.proxy.txn.ClientTransactionUtil.invoke(ClientTransactionUtil.java:57)
2018-02-05T09:27:13.306674881Z 	... 9 more
2018-02-05T09:27:13.996816540Z 09:27:13:996 [pool-1-thread-2] ERROR QuorumTask - Exception during operation Transaction is not active
2018-02-05T09:27:13.996840175Z java.lang.IllegalStateException: Transaction is not active
2018-02-05T09:27:13.997073207Z 	at com.hazelcast.client.proxy.txn.TransactionProxy.rollback(TransactionProxy.java:116)
2018-02-05T09:27:13.997174489Z 	at com.hazelcast.client.proxy.txn.TransactionContextProxy.rollbackTransaction(TransactionContextProxy.java:88)
2018-02-05T09:27:13.997317408Z 	at com.hazelcast.quorum.it.client.FixtureBuilder.lambda$transactionalList$32(FixtureBuilder.java:242)
2018-02-05T09:27:13.997327609Z 	at com.hazelcast.quorum.it.client.QuorumTask.call(QuorumTask.java:36)
2018-02-05T09:27:13.997330189Z 	at com.hazelcast.quorum.it.client.QuorumTask.call(QuorumTask.java:18)
2018-02-05T09:27:13.997332534Z 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2018-02-05T09:27:13.997582142Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2018-02-05T09:27:13.997591369Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2018-02-05T09:27:13.997593945Z 	at java.lang.Thread.run(Thread.java:748)
2018-02-05T09:27:14.099250259Z 09:27:14:098 [pool-1-thread-2] ERROR QuorumTask - Exception during operation Transaction is not active
2018-02-05T09:27:14.099302255Z java.lang.IllegalStateException: Transaction is not active
2018-02-05T09:27:14.099308407Z 	at com.hazelcast.client.proxy.txn.TransactionProxy.rollback(TransactionProxy.java:116)
2018-02-05T09:27:14.099313407Z 	at com.hazelcast.client.proxy.txn.TransactionContextProxy.rollbackTransaction(TransactionContextProxy.java:88)
2018-02-05T09:27:14.099318053Z 	at com.hazelcast.quorum.it.client.FixtureBuilder.lambda$transactionalList$32(FixtureBuilder.java:242)
2018-02-05T09:27:14.099322371Z 	at com.hazelcast.quorum.it.client.QuorumTask.call(QuorumTask.java:36)
2018-02-05T09:27:14.099327312Z 	at com.hazelcast.quorum.it.client.QuorumTask.call(QuorumTask.java:18)
2018-02-05T09:27:14.099333959Z 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2018-02-05T09:27:14.099363515Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2018-02-05T09:27:14.099679272Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2018-02-05T09:27:14.099704107Z 	at java.lang.Thread.run(Thread.java:748)
```

During test period we do not expect `TransactionalException`. This is issue can be a duplicate with  #12185 
[transactional-logs.zip](https://github.com/hazelcast/hazelcast/files/1694575/transactional-logs.zip)

Test repo can be found [here](https://github.com/lazerion/hz-quorum-it) 
Predicates are build in [this builder](https://github.com/lazerion/hz-quorum-it/blob/master/quorumitclient/src/main/java/com/hazelcast/quorum/it/client/FixtureBuilder.java)
Predicates tested in [this callable](https://github.com/lazerion/hz-quorum-it/blob/master/quorumitclient/src/main/java/com/hazelcast/quorum/it/client/QuorumTask.java)

**Comment by lazerion** [comment]
Test code repo transfered to https://github.com/hazelcast/hazelcast-qe

**Comment by sancar** [comment]
Transactions do not support Quorums on the client at the moment. 
If a related connection is disconnected user needs to rollback and re-acquire a transaction.
As far as I understand members are closed during a transaction and it does not seem suitable for current design. 

Secondly, there seems to be an issue with transaction usage.
https://github.com/hazelcast/hazelcast-qe/blob/master/it/quorum/quorumitclient/src/main/java/com/hazelcast/quorum/it/client/FixtureBuilder.java#L234
Transaction.rollback can be called if `commit` fails. These tests are calling rollback when `begin` fails, which causes 
```
2018-02-05T09:27:13.996840175Z java.lang.IllegalStateException: Transaction is not active
2018-02-05T09:27:13.997073207Z 	at com.hazelcast.client.proxy.txn.TransactionProxy.rollback(TransactionProxy.java:116)
```

**Comment by lazerion** [comment]
@sancar thanks for the reply, I am updating `exception` handling for `rollback` and `beginTransaction` calls. As far as understand, this issue will be closed when Transactions support Quorums on client side, or can we close it now?

**Comment by sancar** [comment]
Client side transactions needs to be rewritten to overcome failure when one connection gone. We already have a long term plan for this.

Secondly, even we had this test from members, when two members are down, transactions could be rolled back. This is not related to minority/majority of  the cluster. Transactions always have one backup. 
See details here
http://docs.hazelcast.org/docs/latest-development/manual/html/Transactions/Creating_a_Transaction_Interface.html#page_ONE+_+PHASE+vs.+TWO+_+PHASE

**Comment by sancar** [comment]
@mmedenjak 
Do we have a plan with Transactions with more than 1 backup ?
Or do we have a plan Quorum like support for Transactions ?

**Comment by mmedenjak** [comment]
There is no plan do do any kind of enhancements or fixes on transactions at this point. We only commit to fixing critical issues that do not take up too much time.

**Comment by sancar** [comment]
Then, I am closing this issue.
