### ISSUE TITLE
ScheduledExecutorSplitBrainTest

### ISSUE THREAD

**Issue by Donnerbart** [hazelcast/hazelcast#12255]
**com.hazelcast.scheduledexecutor.ScheduledExecutorSplitBrainTest.testSplitBrain[mergePolicy:class com.hazelcast.spi.merge.DiscardMergePolicy]**
```java
java.lang.AssertionError: expected:<100> but was:<99>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.scheduledexecutor.ScheduledExecutorSplitBrainTest.assertContents(ScheduledExecutorSplitBrainTest.java:196)
	at com.hazelcast.scheduledexecutor.ScheduledExecutorSplitBrainTest.onAfterMergeDiscardMergePolicy(ScheduledExecutorSplitBrainTest.java:150)
	at com.hazelcast.scheduledexecutor.ScheduledExecutorSplitBrainTest.onAfterSplitBrainHealed(ScheduledExecutorSplitBrainTest.java:129)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/13220/testReport/com.hazelcast.scheduledexecutor/ScheduledExecutorSplitBrainTest/testSplitBrain_mergePolicy_class_com_hazelcast_spi_merge_DiscardMergePolicy_/

**Comment by Donnerbart** [comment]
**com.hazelcast.scheduledexecutor.ScheduledExecutorSplitBrainTest.testSplitBrain[mergePolicy:class com.hazelcast.spi.merge.DiscardMergePolicy]**
```java
java.lang.AssertionError: expected:<100> but was:<98>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.scheduledexecutor.ScheduledExecutorSplitBrainTest.assertContents(ScheduledExecutorSplitBrainTest.java:196)
	at com.hazelcast.scheduledexecutor.ScheduledExecutorSplitBrainTest.onAfterMergeDiscardMergePolicy(ScheduledExecutorSplitBrainTest.java:150)
	at com.hazelcast.scheduledexecutor.ScheduledExecutorSplitBrainTest.onAfterSplitBrainHealed(ScheduledExecutorSplitBrainTest.java:129)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/13231/testReport/junit/com.hazelcast.scheduledexecutor/ScheduledExecutorSplitBrainTest/testSplitBrain_mergePolicy_class_com_hazelcast_spi_merge_DiscardMergePolicy_/

**Comment by Donnerbart** [comment]
**com.hazelcast.scheduledexecutor.ScheduledExecutorSplitBrainTest.testSplitBrain[mergePolicy:class com.hazelcast.spi.merge.DiscardMergePolicy]**
```java
java.lang.AssertionError: expected:<100> but was:<98>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.scheduledexecutor.ScheduledExecutorSplitBrainTest.assertContents(ScheduledExecutorSplitBrainTest.java:196)
	at com.hazelcast.scheduledexecutor.ScheduledExecutorSplitBrainTest.onAfterMergeDiscardMergePolicy(ScheduledExecutorSplitBrainTest.java:150)
	at com.hazelcast.scheduledexecutor.ScheduledExecutorSplitBrainTest.onAfterSplitBrainHealed(ScheduledExecutorSplitBrainTest.java:129)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/13240/testReport/junit/com.hazelcast.scheduledexecutor/ScheduledExecutorSplitBrainTest/testSplitBrain_mergePolicy_class_com_hazelcast_spi_merge_DiscardMergePolicy_/

**Comment by Donnerbart** [comment]
**com.hazelcast.scheduledexecutor.ScheduledExecutorSplitBrainTest.testSplitBrain[mergePolicy:class com.hazelcast.spi.merge.DiscardMergePolicy]**
```java
java.lang.AssertionError: expected:<100> but was:<99>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.scheduledexecutor.ScheduledExecutorSplitBrainTest.assertContents(ScheduledExecutorSplitBrainTest.java:196)
	at com.hazelcast.scheduledexecutor.ScheduledExecutorSplitBrainTest.onAfterMergeDiscardMergePolicy(ScheduledExecutorSplitBrainTest.java:150)
	at com.hazelcast.scheduledexecutor.ScheduledExecutorSplitBrainTest.onAfterSplitBrainHealed(ScheduledExecutorSplitBrainTest.java:129)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/13254/testReport/com.hazelcast.scheduledexecutor/ScheduledExecutorSplitBrainTest/testSplitBrain_mergePolicy_class_com_hazelcast_spi_merge_DiscardMergePolicy_/

**Comment by Donnerbart** [comment]
Due to the high failure rate I've ignored the test via https://github.com/hazelcast/hazelcast/commit/38640b9db543de24c25b921b0eec13644418f662
