### ISSUE TITLE
MapSplitBrainTest

### ISSUE THREAD

**Issue by Donnerbart** [hazelcast/hazelcast#12263]
**com.hazelcast.map.merge.MapSplitBrainTest.testSplitBrain[format:BINARY, mergePolicy:class com.hazelcast.spi.merge.PassThroughMergePolicy]**
```java
java.lang.AssertionError: expected:<PassThroughValue2> but was:<null>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.map.merge.MapSplitBrainTest.afterMergePassThroughMergePolicy(MapSplitBrainTest.java:342)
	at com.hazelcast.map.merge.MapSplitBrainTest.onAfterSplitBrainHealed(MapSplitBrainTest.java:188)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/13240/testReport/junit/com.hazelcast.map.merge/MapSplitBrainTest/testSplitBrain_format_BINARY__mergePolicy_class_com_hazelcast_spi_merge_PassThroughMergePolicy_/

**Comment by kwart** [comment]
```
Error Message
expected:<[higherHitsV]alue2> but was:<[v]alue2>
Stacktrace
org.junit.ComparisonFailure: expected:<[higherHitsV]alue2> but was:<[v]alue2>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.map.merge.MapSplitBrainTest.afterMergeHigherHitsMergePolicy(MapSplitBrainTest.java:245)
	at com.hazelcast.map.merge.MapSplitBrainTest.onAfterSplitBrainHealed(MapSplitBrainTest.java:175)
```

https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/13584/testReport/junit/com.hazelcast.map.merge/MapSplitBrainTest/testSplitBrain_format_BINARY__mergePolicy_class_com_hazelcast_spi_merge_HigherHitsMergePolicy_/

**Comment by Donnerbart** [comment]
I can rule out, that the issue is due to the ownership of the used keys. I did a test with pinned keys on all three instances and they never failed locally (in contrast to the `ReplicatedMapSplitBrainTest` which needs the keys on a certain member).

Also with just a repetition of the existing test, there are no local failures.

The PR builder logs also seem to have no long GC pauses and obvious exceptions (the split-brain process sometimes throws some exceptions, when the split-brain is created).

**Comment by sancar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/13654/

com.hazelcast.map.merge.MapSplitBrainTest.testSplitBrain[format:BINARY, mergePolicy:class com.hazelcast.spi.merge.PassThroughMergePolicy]


```
Error Message
expected:<[PassThroughV]alue1> but was:<[v]alue1>
Stacktrace
org.junit.ComparisonFailure: expected:<[PassThroughV]alue1> but was:<[v]alue1>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.map.merge.MapSplitBrainTest.afterMergePassThroughMergePolicy(MapSplitBrainTest.java:331)
	at com.hazelcast.map.merge.MapSplitBrainTest.onAfterSplitBrainHealed(MapSplitBrainTest.java:181)

```

**Comment by jerrinot** [comment]
Bingo!

It seems all failures are at backup-related assertions. 
I can reproduce the failure it by injecting a bit of sleep at the very start of the `PutAllBackupOperation::run`:
```java
@Override
    public void run() {
        try {
            Thread.sleep(ThreadLocalRandomProvider.get().nextInt(1000));
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        boolean wanEnabled = mapContainer.isWanReplicationEnabled();
        for (int i = 0; i < entries.size(); i++) {
            Data dataKey = entries.getKey(i);
[...]
```

The `PutAllBackupOperation` is used as a backup of `MergeOperation` for some reason. However the `MergeOperation` does NOT wait for its backup to complete. They will be complicated eventually. 

Hence I believe even split-brain tests should use assert-eventually when verifying backup maps.

**Comment by jerrinot** [comment]
When I change the assertion to backup maps to use the `-eventually` form then it's passing again. I believe this behavior is correct - backups after split-brain will be eventually sync-ed with the primary store. 

I will send a PR changing the test.

**Comment by hasancelik** [comment]
**MapSplitBrainTest.testSplitBrain[format:BINARY, mergePolicy:class com.hazelcast.spi.merge.LatestUpdateMergePolicy]**
```
java.lang.AssertionError: Cluster size is not correct. Expected: 6, actual: 5, instance index: 0
	at org.junit.Assert.fail(Assert.java:88)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSize(HazelcastTestSupport.java:989)
	at com.hazelcast.test.HazelcastTestSupport$14.run(HazelcastTestSupport.java:1010)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1193)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:1007)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:1001)
	at com.hazelcast.test.SplitBrainTestSupport.healSplitBrain(SplitBrainTestSupport.java:296)
	at com.hazelcast.test.SplitBrainTestSupport.doIteration(SplitBrainTestSupport.java:202)
	at com.hazelcast.test.SplitBrainTestSupport.testSplitBrain(SplitBrainTestSupport.java:191)
	at sun.reflect.GeneratedMethodAccessor179.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.lang.Thread.run(Thread.java:662)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK1.6-freestyle/400/testReport/junit/com.hazelcast.map.merge/MapSplitBrainTest/testSplitBrain_format_BINARY__mergePolicy_class_com_hazelcast_spi_merge_LatestUpdateMergePolicy_/

**Comment by Donnerbart** [comment]
The last failure seems to be the same one like this: https://github.com/hazelcast/hazelcast/issues/12555

**Comment by mmedenjak** [comment]
Regarding the first test failure, cluster consists of these members:
```
Members {size:6, ver:6} [
        Member [127.0.0.1]:16181 - 90b8ae16-5e66-4b5b-b50f-c8e606103116
        Member [127.0.0.1]:16182 - 25c4c3f8-ebb3-402b-aaa6-03a011a0e6d5
        Member [127.0.0.1]:16183 - ea102a8f-7fc7-4dc7-b06f-4c07910b393f
        Member [127.0.0.1]:16184 - 80c0ae65-6deb-4eb5-9473-a2f5cccf0e97
        Member [127.0.0.1]:16185 - 326a7192-911e-4f63-a00e-6f8c73818499
        Member [127.0.0.1]:16186 - fb0a926d-7285-4ce6-b766-36985ae331c4
]
```
Cluster splits into these groups:
```
Members {size:3, ver:9} [
        Member [127.0.0.1]:16181 - 90b8ae16-5e66-4b5b-b50f-c8e606103116
        Member [127.0.0.1]:16182 - 25c4c3f8-ebb3-402b-aaa6-03a011a0e6d5
        Member [127.0.0.1]:16183 - ea102a8f-7fc7-4dc7-b06f-4c07910b393f
]
```
```
Members {size:3, ver:7} [
        Member [127.0.0.1]:16184 - 80c0ae65-6deb-4eb5-9473-a2f5cccf0e97
        Member [127.0.0.1]:16185 - 326a7192-911e-4f63-a00e-6f8c73818499
        Member [127.0.0.1]:16186 - fb0a926d-7285-4ce6-b766-36985ae331c4
]
```
Just then member `[127.0.0.1]:16185` starts the merge process:

```
04:04:08,082  WARN |testSplitBrain[format:BINARY, mergePolicy:class com.hazelcast.spi.merge.LatestUpdateMergePolicy]| - [MergeClustersOp] hz._hzInstance_10846_dev.priority-generic-operation.thread-0 - [127.0.0.1]:16185 [dev] [3.10-SNAPSHOT] [127.0.0.1]:16185 is merging to [127.0.0.1]:16181, because: instructed by master [127.0.0.1]:16184
04:04:08,082  INFO |testSplitBrain[format:BINARY, mergePolicy:class com.hazelcast.spi.merge.LatestUpdateMergePolicy]| - [LifecycleService] hz._hzInstance_10846_dev.cached.thread-5 - [127.0.0.1]:16185 [dev] [3.10-SNAPSHOT] [127.0.0.1]:16185 is MERGING
04:04:08,082  INFO |testSplitBrain[format:BINARY, mergePolicy:class com.hazelcast.spi.merge.LatestUpdateMergePolicy]| - [ClusterService] hz._hzInstance_10846_dev.cached.thread-5 - [127.0.0.1]:16185 [dev] [3.10-SNAPSHOT] Converted local member to lite-member before start of split brain healing
```

It then suspects the master and other member in the brain it was connecting to:
```
04:04:08,083 DEBUG |testSplitBrain[format:BINARY, mergePolicy:class com.hazelcast.spi.merge.LatestUpdateMergePolicy]| - [MockConnectionManager] hz._hzInstance_10846_dev.cached.thread-5 - [127.0.0.1]:16185 [dev] [3.10-SNAPSHOT] [127.0.0.1]:16181 is instructed to suspect from [127.0.0.1]:16185
04:04:08,083 DEBUG |testSplitBrain[format:BINARY, mergePolicy:class com.hazelcast.spi.merge.LatestUpdateMergePolicy]| - [MockConnectionManager] hz._hzInstance_10846_dev.cached.thread-5 - [127.0.0.1]:16185 [dev] [3.10-SNAPSHOT] [127.0.0.1]:16183 is instructed to suspect from [127.0.0.1]:16185
```

And proceeds to connect back to the cluster it once belonged:
```
04:04:08,085 DEBUG |testSplitBrain[format:BINARY, mergePolicy:class com.hazelcast.spi.merge.LatestUpdateMergePolicy]| - [MockConnectionManager] hz._hzInstance_10846_dev.cached.thread-5 - [127.0.0.1]:16185 [dev] [3.10-SNAPSHOT] Starting connection manager
04:04:08,092 DEBUG |testSplitBrain[format:BINARY, mergePolicy:class com.hazelcast.spi.merge.LatestUpdateMergePolicy]| - [MockJoiner] hz._hzInstance_10846_dev.cached.thread-5 - [127.0.0.1]:16185 [dev] [3.10-SNAPSHOT] Known master address is: null
04:04:08,093 DEBUG |testSplitBrain[format:BINARY, mergePolicy:class com.hazelcast.spi.merge.LatestUpdateMergePolicy]| - [MockJoiner] hz._hzInstance_10846_dev.cached.thread-5 - [127.0.0.1]:16185 [dev] [3.10-SNAPSHOT] Searching possible addresses for master [[127.0.0.1]:16186, [127.0.0.1]:16181, [127.0.0.1]:16183, [127.0.0.1]:16182, [127.0.0.1]:16184, [127.0.0.1]:16185]
04:04:08,093 DEBUG |testSplitBrain[format:BINARY, mergePolicy:class com.hazelcast.spi.merge.LatestUpdateMergePolicy]| - [MockJoiner] hz._hzInstance_10846_dev.cached.thread-5 - [127.0.0.1]:16185 [dev] [3.10-SNAPSHOT] Found an alive node. Will ask master of [127.0.0.1]:16186
04:04:08,093 DEBUG |testSplitBrain[format:BINARY, mergePolicy:class com.hazelcast.spi.merge.LatestUpdateMergePolicy]| - [MockJoiner] hz._hzInstance_10846_dev.cached.thread-5 - [127.0.0.1]:16185 [dev] [3.10-SNAPSHOT] Found alive node. Will try to connect to [127.0.0.1]:16186
04:04:08,094 DEBUG |testSplitBrain[format:BINARY, mergePolicy:class com.hazelcast.spi.merge.LatestUpdateMergePolicy]| - [ClusterService] hz._hzInstance_10846_dev.generic-operation.thread-6 - [127.0.0.1]:16185 [dev] [3.10-SNAPSHOT] Setting master address to [127.0.0.1]:16184
04:04:08,094 DEBUG |testSplitBrain[format:BINARY, mergePolicy:class com.hazelcast.spi.merge.LatestUpdateMergePolicy]| - [ClusterStateManager] hz._hzInstance_10846_dev.generic-operation.thread-6 - [127.0.0.1]:16185 [dev] [3.10-SNAPSHOT] Setting initial cluster state: FROZEN and version: 3.10
04:04:08,096 DEBUG |testSplitBrain[format:BINARY, mergePolicy:class com.hazelcast.spi.merge.LatestUpdateMergePolicy]| - [MockJoiner] hz._hzInstance_10846_dev.cached.thread-5 - [127.0.0.1]:16185 [dev] [3
.10-SNAPSHOT] Sending join request to [127.0.0.1]:16186
04:04:08,097 ERROR |testSplitBrain[format:BINARY, mergePolicy:class com.hazelcast.spi.merge.LatestUpdateMergePolicy]| - [PromoteLiteMemberOp] hz._hzInstance_10845_dev.priority-generic-operation.thread-0 - [127.0.0.1]:16184 [dev] [3.10-SNAPSHOT] Lite member promotion is not allowed when cluster state is FROZEN
java.lang.IllegalStateException: Lite member promotion is not allowed when cluster state is FROZEN
        at com.hazelcast.internal.cluster.impl.MembershipManager.ensureLiteMemberPromotionIsAllowed(MembershipManager.java:965) ~[classes/:?]
        at com.hazelcast.internal.cluster.impl.MembershipManager.promoteToDataMember(MembershipManager.java:917) ~[classes/:?]
        at com.hazelcast.internal.cluster.impl.operations.PromoteLiteMemberOp.run(PromoteLiteMemberOp.java:44) ~[classes/:?]
        at com.hazelcast.spi.Operation.call(Operation.java:148) [classes/:?]
        at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:202) [classes/:?]
        at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:191) [classes/:?]
        at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:405) [classes/:?]
        at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:115) [classes/:?]
        at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:100) [classes/:?]
04:04:08,098  INFO |testSplitBrain[format:BINARY, mergePolicy:class com.hazelcast.spi.merge.LatestUpdateMergePolicy]| - [LifecycleService] hz._hzInstance_10846_dev.cached.thread-5 - [127.0.0.1]:16185 [dev] [3.10-SNAPSHOT] [127.0.0.1]:16185 is MERGED
```

After the other members leave, it claims mastership:
```
04:04:08,102  INFO |testSplitBrain[format:BINARY, mergePolicy:class com.hazelcast.spi.merge.LatestUpdateMergePolicy]| - [ClusterService] hz._hzInstance_10846_dev.cached.thread-12 - [127.0.0.1]:16185 [de
v] [3.10-SNAPSHOT] 

Members {size:1, ver:10} [
        Member [127.0.0.1]:16185 - 553c94ea-72ff-45b3-972a-546448fe1a85 this lite
]

04:04:08,102  INFO |testSplitBrain[format:BINARY, mergePolicy:class com.hazelcast.spi.merge.LatestUpdateMergePolicy]| - [MembershipManager] hz._hzInstance_10846_dev.cached.thread-12 - [127.0.0.1]:16185 [dev] [3.10-SNAPSHOT] Mastership is claimed with: MembersView{version=10, members=[MemberInfo{address=[127.0.0.1]:16185, uuid=553c94ea-72ff-45b3-972a-546448fe1a85, liteMember=true, memberListJoinVersion=9}]}
```

Same thing happened in other tests. Still analysing why the member `[127.0.0.1]:16185` didn't join the cluster side it was instructed to in the first place.

**Comment by Donnerbart** [comment]
Hmm, looks like @ahmetmircik changed the cluster size to
```
private static final int[] BRAINS = new int[]{3, 3};
```
Before it was using the default of `2, 1`, which also makes clear which the larger cluster is.

I'm not sure if it's is an edge-case if both sub-clusters have the same size, which needs other assertions etc. So I would recommend of reverting this change and using the default brains again (which should also use half of the resources for this test).

**Comment by Donnerbart** [comment]
See https://github.com/hazelcast/hazelcast/pull/12600

**Comment by ahmetmircik** [comment]
@Donnerbart this was needed to test backup partitions on brains. If one brain has only 1 member all partitions on that brain will be owner partition and we will miss the opportunity to test backup ones. Can we keep it as each brain contains more than one member?

**Comment by mmedenjak** [comment]
Seems like a bug in `MockJoiner` since it didn't first try connecting to the address set by master when merging, like other joiners do.
