### ISSUE TITLE
Invocation_OnBackupLeftTest.whenPrimaryResponseAlreadyReceived

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#12308]
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertNotNull(Assert.java:712)
	at org.junit.Assert.assertNotNull(Assert.java:722)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation_OnBackupLeftTest$2.run(Invocation_OnBackupLeftTest.java:120)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1158)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1175)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation_OnBackupLeftTest.waitForPrimaryResponse(Invocation_OnBackupLeftTest.java:117)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation_OnBackupLeftTest.whenPrimaryResponseAlreadyReceived(Invocation_OnBackupLeftTest.java:98)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.8/com.hazelcast$hazelcast/862/testReport/junit/com.hazelcast.spi.impl.operationservice.impl/Invocation_OnBackupLeftTest/whenPrimaryResponseAlreadyReceived/

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-freestyle/1610/testReport/junit/com.hazelcast.spi.impl.operationservice.impl/Invocation_OnBackupLeftTest/whenPrimaryResponseAlreadyReceived/

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK1.7-freestyle/123/testReport/junit/com.hazelcast.spi.impl.operationservice.impl/Invocation_OnBackupLeftTest/whenPrimaryResponseAlreadyReceived/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertNotNull(Assert.java:712)
	at org.junit.Assert.assertNotNull(Assert.java:722)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation_OnBackupLeftTest$2.run(Invocation_OnBackupLeftTest.java:120)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1158)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1175)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation_OnBackupLeftTest.waitForPrimaryResponse(Invocation_OnBackupLeftTest.java:117)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation_OnBackupLeftTest.whenPrimaryResponseAlreadyReceived(Invocation_OnBackupLeftTest.java:98)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK1.6-freestyle/381/testReport/junit/com.hazelcast.spi.impl.operationservice.impl/Invocation_OnBackupLeftTest/whenPrimaryResponseAlreadyReceived/
