### ISSUE TITLE
Adding configuration for maps results in serialization exception

### ISSUE THREAD

**Issue by Addvilz** [hazelcast/hazelcast#12361]
After upgrading to 3.9.2 from 3.8.5, adding a custom map configuration during runtime results in serialization exception, when custom MapStoreConfig is used as part of MapConfig, and custom implementation is set using MapStoreConfig#setImplementation during runtime. This custom implementation is not serializable nor is it intended to be.

This seems like something new that appeared anywhere inbetween 3.8.5 and 3.9.2. 

Any way to avoid/prevent/tell Hazelcast to leave the configuration for the map alone?

Relevant stack:
```
com.hazelcast.nio.serialization.HazelcastSerializationException: Failed to serialize 'com.hazelcast.config.MapConfig'
	at com.hazelcast.internal.serialization.impl.SerializationUtil.handleSerializeException(SerializationUtil.java:75) ~[hazelcast-3.9.2.jar:3.9.2]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:155) ~[hazelcast-3.9.2.jar:3.9.2]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toData(AbstractSerializationService.java:122) ~[hazelcast-3.9.2.jar:3.9.2]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toData(AbstractSerializationService.java:110) ~[hazelcast-3.9.2.jar:3.9.2]
	at com.hazelcast.internal.dynamicconfig.ClusterWideConfigurationService.cloneConfig(ClusterWideConfigurationService.java:227) ~[hazelcast-3.9.2.jar:3.9.2]
	at com.hazelcast.internal.dynamicconfig.ClusterWideConfigurationService.broadcastConfigAsync(ClusterWideConfigurationService.java:219) ~[hazelcast-3.9.2.jar:3.9.2]
	at com.hazelcast.internal.dynamicconfig.ClusterWideConfigurationService.broadcastConfig(ClusterWideConfigurationService.java:199) ~[hazelcast-3.9.2.jar:3.9.2]
	at com.hazelcast.internal.dynamicconfig.DynamicConfigurationAwareConfig.addMapConfig(DynamicConfigurationAwareConfig.java:219) ~[hazelcast-3.9.2.jar:3.9.2]
	at REDACTED(StoreModule.java:32) ~[main/:?]
[REDACTED]
```

**Comment by mdogan** [comment]
@Addvilz:
Before 3.9, adding a new map configuration (or generally adding a new data structure configuration) at runtime was an undefined behaviour. That was not a supported functionality, because Hazelcast expects all members in a cluster to have the same configuration.

With 3.9, we introduced ability to add new data structure configurations on-the-fly, which requires newly added configuration to be serializable, since it's needed to be replicated to all cluster members.

See [Dynamically Adding Data Structure Configuration on a Cluster](http://docs.hazelcast.org/docs/latest-development/manual/html/Understanding_Configuration/Dynamically_Adding_Data_Structure_Configuration_on_a_Cluster.html) on reference manual.

If you don't want your configuration to be serialized, then you should define that configuration before starting the Hazelcast member.

**Comment by Addvilz** [comment]
@mdogan okay, that makes perfect sense then - in our implementation our app was managing the configuration by other means however, so it seemed to work well enough. Thanks!
