### ISSUE TITLE
EvictionTest.testTTL_prolongationAfterNonTTLUpdate_Quick

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#12376]
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.map.EvictionTest.testTTL_prolongationAfterNonTTLUpdate_Quick(EvictionTest.java:144)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-OracleJDK1.6-freestyle/135/testReport/com.hazelcast.map/EvictionTest/testTTL_prolongationAfterNonTTLUpdate_Quick/

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-OracleJDK1.6-freestyle/134/testReport/junit/com.hazelcast.map/EvictionTest/testTTL_prolongationAfterNonTTLUpdate_Quick/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.map.EvictionTest.testTTL_prolongationAfterNonTTLUpdate_Quick(EvictionTest.java:120)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-freestyle/1794/testReport/junit/com.hazelcast.map/EvictionTest/testTTL_prolongationAfterNonTTLUpdate_Quick/

**Comment by blazember** [comment]
```
Stacktrace
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.map.EvictionTest.testTTL_prolongationAfterNonTTLUpdate_Quick(EvictionTest.java:138)
Standard Output
Finished Running Test: testEvictionSpeedTestPerPartition in 10.402 seconds.
15:09:42,124  INFO |testTTL_prolongationAfterNonTTLUpdate_Quick| - [NodeExtension] Thread-62 - [127.0.0.1]:5062 [dev] [3.9.4-SNAPSHOT] Destroying node NodeExtension.
15:09:42,125  INFO |testTTL_prolongationAfterNonTTLUpdate_Quick| - [Node] Thread-62 - [127.0.0.1]:5062 [dev] [3.9.4-SNAPSHOT] Hazelcast Shutdown is completed in 121 ms.
15:09:42,125  INFO |testTTL_prolongationAfterNonTTLUpdate_Quick| - [LifecycleService] Thread-62 - [127.0.0.1]:5062 [dev] [3.9.4-SNAPSHOT] [127.0.0.1]:5062 is SHUTDOWN
BuildInfo right after testTTL_prolongationAfterNonTTLUpdate_Quick(com.hazelcast.map.EvictionTest): BuildInfo{version='3.9.4-SNAPSHOT', build='20180327', buildNumber=20180327, revision=b6615ab, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'testTTL_prolongationAfterNonTTLUpdate_Quick(com.hazelcast.map.EvictionTest):'
15:09:35, accumulated pauses: 1094 ms, max pause: 194 ms, pauses over 1000 ms: 0
15:09:40, accumulated pauses: 1524 ms, max pause: 1396 ms, pauses over 1000 ms: 1

Started Running Test: testTTL_appliedFromLastUpdate
```

https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/14735/testReport/junit/com.hazelcast.map/EvictionTest/testTTL_prolongationAfterNonTTLUpdate_Quick/

**Comment by vbekiaris** [comment]
Reopening as it failed on `maintenance-3.x` in PR builder https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/15248/testReport/junit/com.hazelcast.map/EvictionTest/testTTL_prolongationAfterNonTTLUpdate_Quick/ 

```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.map.EvictionTest.testTTL_prolongationAfterNonTTLUpdate_Quick(EvictionTest.java:129)
```
