### ISSUE TITLE
Intermittent failures in MemberListJoinVersionTest.when_splitSubClustersMerge_then_targetClusterShouldIncrementMemberListVersion

### ISSUE THREAD

**Issue by kwart** [hazelcast/hazelcast#12398]
Test: `com.hazelcast.internal.cluster.impl.MemberListJoinVersionTest.when_splitSubClustersMerge_then_targetClusterShouldIncrementMemberListVersion`

```
java.lang.AssertionError: expected:<6> but was:<5>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.internal.cluster.impl.MembershipUpdateTest.assertMemberViewsAreSame(MembershipUpdateTest.java:754)
	at com.hazelcast.internal.cluster.impl.MemberListJoinVersionTest.when_splitSubClustersMerge_then_targetClusterShouldIncrementMemberListVersion(MemberListJoinVersionTest.java:130)
```

https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/13730/testReport/junit/com.hazelcast.internal.cluster.impl/MemberListJoinVersionTest/when_splitSubClustersMerge_then_targetClusterShouldIncrementMemberListVersion/

**Comment by mdogan** [comment]
[failure.log](https://github.com/hazelcast/hazelcast/files/1743449/failure.log)
