### ISSUE TITLE
ScheduledExecutorSplitBrainTest.testSplitBrain

### ISSUE THREAD

**Issue by mmedenjak** [hazelcast/hazelcast#12424]
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/13831
```
java.lang.IllegalStateException: Partition holding this Scheduled task was lost along with all backups.
	at com.hazelcast.scheduledexecutor.impl.ScheduledFutureProxy.checkAccessibleOwner(ScheduledFutureProxy.java:208)
	at com.hazelcast.scheduledexecutor.impl.ScheduledFutureProxy.isDone(ScheduledFutureProxy.java:133)
	at com.hazelcast.scheduledexecutor.ScheduledExecutorSplitBrainTest.onAfterMergeDiscardMergePolicy(ScheduledExecutorSplitBrainTest.java:153)
	at com.hazelcast.scheduledexecutor.ScheduledExecutorSplitBrainTest.onAfterSplitBrainHealed(ScheduledExecutorSplitBrainTest.java:128)
```

**Comment by tkountis** [comment]
Interesting
