### ISSUE TITLE
DefaultAddressPickerInterfacesTest

### ISSUE THREAD

**Issue by Donnerbart** [hazelcast/hazelcast#12459]
**com.hazelcast.instance.DefaultAddressPickerInterfacesTest.testIPv4Preferred**
```java
org.junit.ComparisonFailure: expected:<[192.168.1.1]> but was:<[fe80:0:0:0:9711:82f4:383a:e254]>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.instance.DefaultAddressPickerInterfacesTest.testIPv4Preferred(DefaultAddressPickerInterfacesTest.java:288)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/13952/testReport/junit/com.hazelcast.instance/DefaultAddressPickerInterfacesTest/testIPv4Preferred/

**com.hazelcast.instance.DefaultAddressPickerInterfacesTest.testComplexScenario**
```java
org.junit.ComparisonFailure: expected:<[192.168.1.]4> but was:<[fe80:0:0:0:9711:82f4:383a:e25]4>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.instance.DefaultAddressPickerInterfacesTest.testComplexScenario(DefaultAddressPickerInterfacesTest.java:335)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/13952/testReport/junit/com.hazelcast.instance/DefaultAddressPickerInterfacesTest/testComplexScenario/

**Comment by Donnerbart** [comment]
This test also fails with the same errors on my machine.
