### ISSUE TITLE
CacheBasicServerTest

### ISSUE THREAD

**Issue by mmedenjak** [hazelcast/hazelcast#12480]
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/14013

com.hazelcast.cache.CacheBasicServerTest.cacheManagerOfCache_cannotBeOverwritten
```
com.hazelcast.core.HazelcastInstanceNotActiveException: Hazelcast instance is not active!
	at com.hazelcast.spi.AbstractDistributedObject.throwNotActiveException(AbstractDistributedObject.java:105)
	at com.hazelcast.spi.AbstractDistributedObject.lifecycleCheck(AbstractDistributedObject.java:100)
	at com.hazelcast.spi.AbstractDistributedObject.getNodeEngine(AbstractDistributedObject.java:94)
	at com.hazelcast.cache.impl.CacheProxy.<init>(CacheProxy.java:88)
	at com.hazelcast.cache.impl.AbstractCacheService.createDistributedObject(AbstractCacheService.java:225)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyRegistry.doCreateProxy(ProxyRegistry.java:191)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyRegistry.createProxy(ProxyRegistry.java:184)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyServiceImpl.dispatchEvent(ProxyServiceImpl.java:240)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyServiceImpl.dispatchEvent(ProxyServiceImpl.java:64)
	at com.hazelcast.spi.impl.eventservice.impl.EventProcessor.process(EventProcessor.java:61)
	at com.hazelcast.spi.impl.eventservice.impl.RemoteEventProcessor.run(RemoteEventProcessor.java:43)
	at com.hazelcast.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:226)
	at com.hazelcast.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:209)
```

com.hazelcast.cache.CacheBasicServerTest.com.hazelcast.cache.CacheBasicServerTest
```
java.lang.IllegalStateException: Instances haven't been shut down: [HazelcastInstance{name='_hzInstance_39_dev', node=[127.0.0.1]:5039}, HazelcastInstance{name='_hzInstance_40_dev', node=[127.0.0.1]:5040}]
	at com.hazelcast.test.AbstractHazelcastClassRunner$3.evaluate(AbstractHazelcastClassRunner.java:342)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:108)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeLazy(JUnitCoreWrapper.java:89)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:58)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:144)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
```

**Comment by Donnerbart** [comment]
**com.hazelcast.cache.CacheBasicServerTest.cacheManagerOfCache_cannotBeOverwritten**
```java
com.hazelcast.core.HazelcastInstanceNotActiveException: Hazelcast instance is not active!
	at com.hazelcast.spi.AbstractDistributedObject.throwNotActiveException(AbstractDistributedObject.java:105)
	at com.hazelcast.spi.AbstractDistributedObject.lifecycleCheck(AbstractDistributedObject.java:100)
	at com.hazelcast.spi.AbstractDistributedObject.getNodeEngine(AbstractDistributedObject.java:94)
	at com.hazelcast.cache.impl.CacheProxy.<init>(CacheProxy.java:88)
	at com.hazelcast.cache.impl.AbstractCacheService.createDistributedObject(AbstractCacheService.java:241)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyRegistry.doCreateProxy(ProxyRegistry.java:191)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyRegistry.createProxy(ProxyRegistry.java:184)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyServiceImpl.dispatchEvent(ProxyServiceImpl.java:240)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyServiceImpl.dispatchEvent(ProxyServiceImpl.java:64)
	at com.hazelcast.spi.impl.eventservice.impl.EventProcessor.process(EventProcessor.java:61)
	at com.hazelcast.spi.impl.eventservice.impl.RemoteEventProcessor.run(RemoteEventProcessor.java:47)
	at com.hazelcast.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:226)
	at com.hazelcast.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:209)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/14233/testReport/junit/com.hazelcast.cache/CacheBasicServerTest/cacheManagerOfCache_cannotBeOverwritten/

**Comment by blazember** [comment]
Related: #12515 and #12516

**Comment by blazember** [comment]
[Reproducer](https://github.com/blazember/hazelcast/commit/56c2924994f20f0c2df3f0510d0e7ef8800e8519)

**Explanation**
If `CacheProxy` is getting instantiated on an instance, which is shutting down, `HazelcastInstanceNotActiveException` is thrown. That exception is swallowed/ignored in most of the places and it shouldn't cause such an issue. However, if `ProxyRegistry#destroy()` executes between these two lines in [`ProxyRegistry#doCreateProxy()`](https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/spi/impl/proxyservice/impl/ProxyRegistry.java#L205-L206), the exception is visible to [`ProxyRegistry#destroy()`](https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/spi/impl/proxyservice/impl/ProxyRegistry.java#L265) and it is rethrown on the test's thread, breaking the test in the way observed by the linked builds.
