### ISSUE TITLE
ClientOwnershipTest test_ownerShip_whenSmartClientAndOwnerDiesTogether

### ISSUE THREAD

**Issue by tkountis** [hazelcast/hazelcast#12506]
Error Message
```expected:<0> but was:<1>```
Stacktrace
```
java.lang.AssertionError: expected:<0> but was:<1>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.client.ClientOwnershipTest$9.run(ClientOwnershipTest.java:248)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1179)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1196)
	at com.hazelcast.client.ClientOwnershipTest.test_ownerShip_whenClientAndOwnerDiesTogether(ClientOwnershipTest.java:243)
	at com.hazelcast.client.ClientOwnershipTest.test_ownerShip_whenSmartClientAndOwnerDiesTogether(ClientOwnershipTest.java:219)
```

https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/14117/testReport/junit/com.hazelcast.client/ClientOwnershipTest/test_ownerShip_whenSmartClientAndOwnerDiesTogether/

**Comment by mdogan** [comment]
Similar to this, I observed another failure on my local run:

```
java.lang.AssertionError: expected:<0> but was:<1>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.client.ClientOwnershipTest$6.run(ClientOwnershipTest.java:183)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1199)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1216)
	at com.hazelcast.client.ClientOwnershipTest.test_ownerShipRemoved_afterClientDies(ClientOwnershipTest.java:177)
```

**Comment by sancar** [comment]
Issue posted by @tkountis is possibly fixed via https://github.com/hazelcast/hazelcast/pull/12374
This fix was 14 days ago. 

@mdogan I am planning to wait for this to fail again, and check it with logs.
