### ISSUE TITLE
NearCacheTest.testMapContainsKey_withNearCache random failure

### ISSUE THREAD

**Issue by Holmistr** [hazelcast/hazelcast#12516]
Failed on master in Sonar build. Please note that this failure appeared together with https://github.com/hazelcast/hazelcast/issues/12515

Stacktrace:
```
com.hazelcast.core.HazelcastInstanceNotActiveException: Hazelcast instance is not active!
	at com.hazelcast.spi.AbstractDistributedObject.throwNotActiveException(AbstractDistributedObject.java:105)
	at com.hazelcast.spi.AbstractDistributedObject.lifecycleCheck(AbstractDistributedObject.java:100)
	at com.hazelcast.spi.AbstractDistributedObject.getNodeEngine(AbstractDistributedObject.java:94)
	at com.hazelcast.map.impl.proxy.NearCachedMapProxyImpl.addNearCacheInvalidationListener(NearCachedMapProxyImpl.java:608)
	at com.hazelcast.map.impl.proxy.NearCachedMapProxyImpl.registerInvalidationListener(NearCachedMapProxyImpl.java:615)
	at com.hazelcast.map.impl.proxy.NearCachedMapProxyImpl.initialize(NearCachedMapProxyImpl.java:97)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyRegistry.doCreateProxy(ProxyRegistry.java:194)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyRegistry.createProxy(ProxyRegistry.java:184)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyServiceImpl.dispatchEvent(ProxyServiceImpl.java:240)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyServiceImpl.dispatchEvent(ProxyServiceImpl.java:64)
	at com.hazelcast.spi.impl.eventservice.impl.EventProcessor.process(EventProcessor.java:61)
	at com.hazelcast.spi.impl.eventservice.impl.RemoteEventProcessor.run(RemoteEventProcessor.java:43)
	at com.hazelcast.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:226)
	at com.hazelcast.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:209)
```

https://hazelcast-l337.ci.cloudbees.com/view/Lab/job/Hazelcast-3.x-sonar-lab/21/

**Comment by blazember** [comment]
The below stacktrace originally reported in #12515 belongs to this test. The instances reported (by afterclass check) as still running were created by this test and appear in this test's log. The `NearCacheTest` and `NearCacheStalenessTest` tests were running in parallel during the sonar build and the  overlapping log lines from different test cases confused surefire. 
```
java.lang.IllegalStateException: Instances haven't been shut down: [HazelcastInstance{name='_hzInstance_6541_dev', node=[127.0.0.1]:11618}, HazelcastInstance{name='_hzInstance_6563_dev', node=[127.0.0.1]:11620}, HazelcastInstance{name='_hzInstance_6572_dev', node=[127.0.0.1]:11622}]
	at com.hazelcast.test.AbstractHazelcastClassRunner$3.evaluate(AbstractHazelcastClassRunner.java:342)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:108)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:78)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:54)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:144)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
```

**Comment by blazember** [comment]
Seems the following sequence of the events caused this:
```
01. [21:29:47,372] NearCacheTest.testMapContainsKey_withNearCache[batchInvalidationEnabled:false] started
02. [21:29:47,795] _hzInstance_6563_dev created
03. [21:29:47,967] _hzInstance_6541_dev created
04. [21:29:48,469] _hzInstance_6572_dev created
05. [21:29:56,297] NearCacheStalenessTest started
06. [21:30:21,945] NearCacheStalenessTest finished
07. [21:30:21,94?] NearCacheStalenessTest's afterclass throws java.lang.IllegalStateException: Instances haven't been shut down: [HazelcastInstance{name='_hzInstance_6541_dev', node=[127.0.0.1]:11618}, HazelcastInstance{name='_hzInstance_6563_dev', node=[127.0.0.1]:11620}, HazelcastInstance{name='_hzInstance_6572_dev', node=[127.0.0.1]:11622}]
08. [21:30:22,134] _hzInstance_6541_dev SHUTDOWN
09. [21:30:22,142] _hzInstance_6563_dev SHUTDOWN
10. [21:30:22,235] NearCacheTest.testMapContainsKey_withNearCache[batchInvalidationEnabled:false] finished
11. [21:30:22,245] _hzInstance_6572_dev SHUTDOWN
```

**Comment by mmedenjak** [comment]
Closing in effect of #12584
