### ISSUE TITLE
NearCacheStalenessTest random failure

### ISSUE THREAD

**Issue by Holmistr** [hazelcast/hazelcast#12515]
Failed on master in Sonar build.

Stacktrace:
```
java.lang.IllegalStateException: Instances haven't been shut down: [HazelcastInstance{name='_hzInstance_6541_dev', node=[127.0.0.1]:11618}, HazelcastInstance{name='_hzInstance_6563_dev', node=[127.0.0.1]:11620}, HazelcastInstance{name='_hzInstance_6572_dev', node=[127.0.0.1]:11622}]
	at com.hazelcast.test.AbstractHazelcastClassRunner$3.evaluate(AbstractHazelcastClassRunner.java:342)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:108)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:78)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:54)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:144)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
```

Standard output:
```
21:30:22,124 ERROR || - [ServiceManagerImpl] main - [127.0.0.1]:11618 [dev] [3.10-SNAPSHOT] Error while shutting down service[com.hazelcast.map.impl.MapService@4ca72e51]: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@568c5af8 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@475ab7fb[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@568c5af8 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@475ab7fb[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047) ~[?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823) ~[?:1.8.0_121]
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326) ~[?:1.8.0_121]
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533) ~[?:1.8.0_121]
	at com.hazelcast.test.mocknetwork.MockConnectionManager.send(MockConnectionManager.java:281) ~[test-classes/:?]
	at com.hazelcast.test.mocknetwork.MockConnectionManager.transmit(MockConnectionManager.java:264) ~[test-classes/:?]
	at com.hazelcast.nio.tcp.FirewallingConnectionManager.transmit(FirewallingConnectionManager.java:161) ~[test-classes/:?]
	at com.hazelcast.spi.impl.eventservice.impl.EventServiceImpl.sendEvent(EventServiceImpl.java:519) ~[classes/:?]
	at com.hazelcast.spi.impl.eventservice.impl.EventServiceImpl.publishEvent(EventServiceImpl.java:403) ~[classes/:?]
	at com.hazelcast.internal.nearcache.impl.invalidation.Invalidator.sendImmediately(Invalidator.java:123) ~[classes/:?]
	at com.hazelcast.internal.nearcache.impl.invalidation.Invalidator.invalidateAllKeys(Invalidator.java:86) ~[classes/:?]
	at com.hazelcast.internal.nearcache.impl.invalidation.Invalidator.destroy(Invalidator.java:137) ~[classes/:?]
	at com.hazelcast.map.impl.nearcache.MapNearCacheManager.destroyNearCache(MapNearCacheManager.java:134) ~[classes/:?]
	at com.hazelcast.internal.nearcache.impl.DefaultNearCacheManager.destroyAllNearCaches(DefaultNearCacheManager.java:141) ~[classes/:?]
	at com.hazelcast.map.impl.nearcache.MapNearCacheManager.shutdown(MapNearCacheManager.java:125) ~[classes/:?]
	at com.hazelcast.map.impl.MapServiceContextImpl.shutdown(MapServiceContextImpl.java:417) ~[classes/:?]
	at com.hazelcast.map.impl.MapManagedService.shutdown(MapManagedService.java:66) ~[classes/:?]
	at com.hazelcast.map.impl.MapService.shutdown(MapService.java:116) ~[classes/:?]
	at com.hazelcast.spi.impl.servicemanager.impl.ServiceManagerImpl.shutdownService(ServiceManagerImpl.java:311) [classes/:?]
	at com.hazelcast.spi.impl.servicemanager.impl.ServiceManagerImpl.shutdown(ServiceManagerImpl.java:302) [classes/:?]
	at com.hazelcast.spi.impl.NodeEngineImpl.shutdown(NodeEngineImpl.java:464) [classes/:?]
	at com.hazelcast.instance.Node.shutdownServices(Node.java:490) [classes/:?]
	at com.hazelcast.instance.Node.shutdown(Node.java:454) [classes/:?]
	at com.hazelcast.instance.LifecycleServiceImpl.shutdown(LifecycleServiceImpl.java:98) [classes/:?]
	at com.hazelcast.instance.LifecycleServiceImpl.shutdown(LifecycleServiceImpl.java:81) [classes/:?]
	at com.hazelcast.instance.HazelcastInstanceFactory.shutdownAll(HazelcastInstanceFactory.java:289) [classes/:?]
	at com.hazelcast.instance.HazelcastInstanceFactory.shutdownAll(HazelcastInstanceFactory.java:259) [classes/:?]
	at com.hazelcast.core.Hazelcast.shutdownAll(Hazelcast.java:40) [classes/:?]
	at com.hazelcast.test.AbstractHazelcastClassRunner$3.evaluate(AbstractHazelcastClassRunner.java:341) [test-classes/:?]
```

https://hazelcast-l337.ci.cloudbees.com/view/Lab/job/Hazelcast-3.x-sonar-lab/21/

**Comment by blazember** [comment]
I believe this test did not fail. It was reported failed by surefire by mistake because `NearCacheTest` and `NearCacheStalenessTest` tests were running in parallel during the sonar build and the overlapping log lines from the different test cases confused surefire. The instances named in the stacktrace were created by `testMapContainsKey_withNearCache`. The first one by `[batchInvalidationEnabled:true]`, the other two by `[batchInvalidationEnabled:false]`.

Below is the content of the `TEST-com.hazelcast.map.impl.nearcache.NearCacheStalenessTest.xml` surefire report xml. Note that there was no failure nor error reported for the only one test case in this test class.
```
<testcase name="testNearCache_notContainsStaleValue_whenUpdatedByMultipleThreads" classname="com.hazelcast.map.impl.nearcache.NearCacheStalenessTest" time="25.646"/>
<testcase name="com.hazelcast.map.impl.nearcache.NearCacheStalenessTest" classname="com.hazelcast.map.impl.nearcache.NearCacheStalenessTest" time="25.947">
    <error message="Instances haven&apos;t been shut down: [HazelcastInstance{name=&apos;_hzInstance_6541_dev&apos;, node=[127.0.0.1]:11618}, HazelcastInstance{name=&apos;_hzInstance_6563_dev&apos;, node=[127.0.0.1]:11620}, HazelcastInstance{name=&apos;_hzInstance_6572_dev&apos;, node=[127.0.0.1]:11622}]" type="java.lang.IllegalStateException">java.lang.IllegalStateException: Instances haven't been shut down: [HazelcastInstance{name='_hzInstance_6541_dev', node=[127.0.0.1]:11618}, HazelcastInstance{name='_hzInstance_6563_dev', node=[127.0.0.1]:11620}, HazelcastInstance{name='_hzInstance_6572_dev', node=[127.0.0.1]:11622}]
	at com.hazelcast.test.AbstractHazelcastClassRunner$3.evaluate(AbstractHazelcastClassRunner.java:342)
[...]
```

Closing this issue with the explanation above. @Holmistr feel free to reopen if you're not happy with the explanation.
