### ISSUE TITLE
RetryableHazelcastException when shutting down an instance

### ISSUE THREAD

**Issue by eminn** [hazelcast/hazelcast#12547]
```
36:04,867 [10.216.1.11]:5701 [jet] [0.6-SNAPSHOT] Error while shutting down service[CacheService[hz:impl:cacheService]]: HazelcastInstance[[10.216.1.11]:5701] is not active!
com.hazelcast.spi.exception.RetryableHazelcastException: HazelcastInstance[[10.216.1.11]:5701] is not active!
    at com.hazelcast.spi.impl.NodeEngineImpl.getService(NodeEngineImpl.java:358)
    at com.hazelcast.cache.impl.AbstractCacheService.deleteCache(AbstractCacheService.java:333)
    at com.hazelcast.cache.impl.AbstractCacheService.reset(AbstractCacheService.java:169)
    at com.hazelcast.cache.impl.AbstractCacheService.shutdown(AbstractCacheService.java:192)
    at com.hazelcast.spi.impl.servicemanager.impl.ServiceManagerImpl.shutdownService(ServiceManagerImpl.java:311)
    at com.hazelcast.spi.impl.servicemanager.impl.ServiceManagerImpl.shutdown(ServiceManagerImpl.java:302)
    at com.hazelcast.spi.impl.NodeEngineImpl.shutdown(NodeEngineImpl.java:464)
    at com.hazelcast.instance.Node.shutdownServices(Node.java:490)
    at com.hazelcast.instance.Node.shutdown(Node.java:454)
    at com.hazelcast.instance.LifecycleServiceImpl.shutdown(LifecycleServiceImpl.java:98)
    at com.hazelcast.instance.LifecycleServiceImpl.shutdown(LifecycleServiceImpl.java:81)
    at com.hazelcast.instance.HazelcastInstanceFactory.shutdownAll(HazelcastInstanceFactory.java:289)
    at com.hazelcast.instance.HazelcastInstanceFactory.shutdownAll(HazelcastInstanceFactory.java:259)
    at com.hazelcast.core.Hazelcast.shutdownAll(Hazelcast.java:40)
    at com.hazelcast.jet.Jet.shutdownAll(Jet.java:90)
    at CacheJournalSource.main(CacheJournalSource.java:62)
```

To reproduce it just shutdown an instance which has a configured cache on it.

**Comment by mdogan** [comment]
Change added by https://github.com/hazelcast/hazelcast/pull/11782

**Comment by mdogan** [comment]
As a solution right now, we can mark `WanReplicationService` as shared and use `nodeEngine. getSharedService()` instead. Similar to lock-service usage, see https://github.com/hazelcast/hazelcast/pull/8255.
