### ISSUE TITLE
NearCacheTest.testNearCacheTTLRecordsExpired

### ISSUE THREAD

**Issue by mdogan** [hazelcast/hazelcast#12566]
```
java.lang.AssertionError: we expected to have all map entries in the Near Cache or already expired (NearCacheStatsImpl{ownedEntryCount=4616, ownedEntryMemoryCost=498528, creationTime=1520845086699, hits=0, misses=5000, ratio=0.0%, evictions=0, expirations=383, lastPersistenceTime=0, persistenceCount=0, lastPersistenceDuration=0, lastPersistenceWrittenBytes=0, lastPersistenceKeyCount=0, lastPersistenceFailure=''})
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.map.impl.nearcache.NearCacheTestSupport$1.run(NearCacheTestSupport.java:99)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1199)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1216)
	at com.hazelcast.map.impl.nearcache.NearCacheTestSupport.assertNearCacheExpiration(NearCacheTestSupport.java:96)
	at com.hazelcast.map.impl.nearcache.NearCacheTest.testNearCacheExpiration(NearCacheTest.java:835)
	at com.hazelcast.map.impl.nearcache.NearCacheTest.testNearCacheTTLRecordsExpired(NearCacheTest.java:808)
```

https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/14298/testReport/junit/com.hazelcast.map.impl.nearcache/NearCacheTest/testNearCacheTTLRecordsExpired_batchInvalidationEnabled_true_/

**Comment by ahmetmircik** [comment]
merged a possible fix : https://github.com/hazelcast/hazelcast/pull/12567
