### ISSUE TITLE
TransactionContextImpl_backupLogsTest random failures

### ISSUE THREAD

**Issue by Holmistr** [hazelcast/hazelcast#12589]
Failed in Sonar build https://hazelcast-l337.ci.cloudbees.com/view/Lab/job/Hazelcast-3.x-sonar-lab/lastCompletedBuild/testReport/

Stacktrace:
```
com.hazelcast.core.HazelcastInstanceNotActiveException: Hazelcast instance is not active!
	at com.hazelcast.spi.AbstractDistributedObject.throwNotActiveException(AbstractDistributedObject.java:105)
	at com.hazelcast.spi.AbstractDistributedObject.lifecycleCheck(AbstractDistributedObject.java:100)
	at com.hazelcast.spi.AbstractDistributedObject.getNodeEngine(AbstractDistributedObject.java:94)
	at com.hazelcast.collection.impl.collection.AbstractCollectionProxyImpl.initialize(AbstractCollectionProxyImpl.java:73)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyRegistry.doCreateProxy(ProxyRegistry.java:194)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyRegistry.createProxy(ProxyRegistry.java:184)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyServiceImpl.dispatchEvent(ProxyServiceImpl.java:240)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyServiceImpl.dispatchEvent(ProxyServiceImpl.java:64)
	at com.hazelcast.spi.impl.eventservice.impl.EventProcessor.process(EventProcessor.java:61)
	at com.hazelcast.spi.impl.eventservice.impl.RemoteEventProcessor.run(RemoteEventProcessor.java:47)
	at com.hazelcast.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:226)
	at com.hazelcast.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:209)
```

Test methods that failed: com.hazelcast.transaction.impl.TransactionContextImpl_backupLogsTest.com.hazelcast.transaction.impl.TransactionContextImpl_backupLogsTest
com.hazelcast.transaction.impl.TransactionContextImpl_backupLogsTest.list_backupLogCreationForced

This issue seem to have the root cause in https://github.com/hazelcast/hazelcast/issues/12480#issuecomment-372480437
The fix is already pending for reviews: https://github.com/hazelcast/hazelcast/pull/12584

**Comment by mmedenjak** [comment]
Closing in effect of https://github.com/hazelcast/hazelcast/pull/12584
