### ISSUE TITLE
Exception on server when attempting to update item in level2 cache hibernate 

### ISSUE THREAD

**Issue by shahbour** [hazelcast/hazelcast#12615]
I am trying to use hazelcast in a spring boot project with hibernate as level2 cache

It is working good when trying to insert item or read item , but when trying to update an item i got the below error 

```
SEVERE: [172.17.0.3]:5701 [dev] [3.7.8] There is no suitable de-serializer for type -205. This exception is likely to be caused by differences in the serialization configuration between members or between clients and members.
com.hazelcast.nio.serialization.HazelcastSerializationException: There is no suitable de-serializer for type -205. This exception is likely to be caused by differences in the serialization configuration between members or between clients and members.
        at com.hazelcast.internal.serialization.impl.AbstractSerializationService.newHazelcastSerializationException(AbstractSerializationService.java:220)
        at com.hazelcast.internal.serialization.impl.AbstractSerializationService.readObject(AbstractSerializationService.java:247)
        at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readObject(ByteArrayObjectDataInput.java:600)
        at com.hazelcast.hibernate.serialization.Value.readData(Value.java:78)
        at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.readInternal(DataSerializableSerializer.java:151)
        at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:104)
        at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:54)
        at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48)
        at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:172)
        at com.hazelcast.query.impl.CachedQueryEntry.getValue(CachedQueryEntry.java:70)
        at com.hazelcast.hibernate.distributed.LockEntryProcessor.process(LockEntryProcessor.java:49)
        at com.hazelcast.hibernate.distributed.LockEntryProcessor.process(LockEntryProcessor.java:32)
        at com.hazelcast.map.impl.operation.EntryOperation.process(EntryOperation.java:195)
        at com.hazelcast.map.impl.operation.EntryOperation.run(EntryOperation.java:88)
        at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:181)
        at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:375)
        at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:402)
        at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:283)
        at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:268)
        at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:232)
        at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:207)
        at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:59)
        at com.hazelcast.client.impl.protocol.task.AbstractPartitionMessageTask.processMessage(AbstractPartitionMessageTask.java:67)
        at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:123)
        at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:103)
        at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:137)
        at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:127)
        at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:102)

```

I am using the below pom , where hazelcast version 3.7.8 and i tried using server 3.9.3

```
<dependency>
    <groupId>com.hazelcast</groupId>
    <artifactId>hazelcast-hibernate5</artifactId>
    <version>1.2.3</version>
</dependency>
<dependency>
    <groupId>com.hazelcast</groupId>
    <artifactId>hazelcast-spring</artifactId>
</dependency>
<dependency>
    <groupId>com.h2database</groupId>
    <artifactId>h2</artifactId>
</dependency>
<dependency>
    <groupId>com.hazelcast</groupId>
    <artifactId>hazelcast-client</artifactId>
</dependency>
```

**Comment by shahbour** [comment]
Hello @emre-aydin  , Sorry I did not get back to this but it was from hibernate version docker image, so I customized the image to a new one that contains hibernate5 . The default one only contains version 3

```
FROM centos:7
MAINTAINER Ali Shahbour <ali.shahbour@teltacworldwide.com>

ENV HZ_HOME /opt/hazelcast/
ENV HZ_CP_MOUNT ${HZ_HOME}/external
ENV JAVA_HOME /usr/lib/jvm/java
ENV LANG en_US.utf8

ENV USER_NAME=hazelcast
ENV USER_UID=10001

ENV HZ_VERSION 3.9.3
ARG HZ_KUBE_VERSION=1.1.0
ARG HZ_MAVEN_DIR=${HZ_VERSION}
ARG REPOSITORY_URL=https://repo1.maven.org/maven2

RUN mkdir -p $HZ_HOME
RUN mkdir -p $HZ_CP_MOUNT
WORKDIR $HZ_HOME

ADD hazelcast.xml $HZ_HOME/hazelcast.xml
ADD start.sh $HZ_HOME/start.sh
ADD stop.sh $HZ_HOME/stop.sh
ADD liveness.sh $HZ_HOME/liveness.sh
ADD readiness.sh $HZ_HOME/readiness.sh

RUN yum update -y && \
yum install -y wget && \
yum install -y java-1.8.0-openjdk && \
yum clean all

ENV JAVA_HOME /etc/alternatives/jre
### add hazelcast enterprise
ADD ${REPOSITORY_URL}/com/hazelcast/hazelcast-all/${HZ_VERSION}/hazelcast-all-${HZ_VERSION}.jar $HZ_HOME

### Adding Logging redirector
ADD https://repo1.maven.org/maven2/org/slf4j/jul-to-slf4j/1.7.12/jul-to-slf4j-1.7.12.jar $HZ_HOME

### Adding JCache
ADD https://repo1.maven.org/maven2/javax/cache/cache-api/1.0.0/cache-api-1.0.0.jar $HZ_HOME

### Adding Hazelcast-hibernate
ADD https://repo1.maven.org/maven2/com/hazelcast/hazelcast-hibernate5/1.2.3/hazelcast-hibernate5-1.2.3.jar $HZ_HOME

### Adding Hibernate Core
ADD https://repo1.maven.org/maven2/org/hibernate/hibernate-core/5.0.12.Final/hibernate-core-5.0.12.Final.jar $HZ_HOME

### Adding maven wrapper, downloading Hazelcast Kubernetes discovery plugin and dependencies and cleaning up
ADD https://github.com/takari/maven-wrapper/archive/maven-wrapper-0.3.0.tar.gz $HZ_HOME
RUN cd $HZ_HOME && \
    tar zxf maven-wrapper*.tar.gz && \
    rm -fr maven-wrapper*.tar.gz && \
    mv maven-wrapper* mvnw
COPY mvnw $HZ_HOME/mvnw

### Configure Hazelcast
RUN useradd -l -u $USER_UID -r -g 0 -d $HZ_HOME -s /sbin/nologin -c "${USER_UID} application user" $USER_NAME
RUN chown -R $USER_UID:0 $HZ_HOME $HZ_CP_MOUNT
RUN chmod +x $HZ_HOME/*.sh

### Switch to hazelcast user
USER $USER_UID
RUN cd mvnw && \
    chmod +x mvnw && \
    sync && \
    ./mvnw -f dependency-copy.xml -Dhazelcast-kubernetes-version=${HZ_KUBE_VERSION} dependency:copy-dependencies && \
    cd .. && \
    rm -rf $HZ_HOME/mvnw && \
    rm -rf $HZ_HOME/.m2 && \
    chmod -R +r $HZ_HOME

### Expose port
EXPOSE 5701
### Start hazelcast standalone server.
CMD ["/bin/sh", "-c", "./start.sh"]
```

doing so worked perfectly for all add, delete, update.

**Comment by emre-aydin** [comment]
@shahbour so we can close the issue, right?

**Comment by shahbour** [comment]
Sure thanks for the follow up
