### ISSUE TITLE
[TEST-FAILURE] ClientMapLoadAllTest.testGetMap_issue_3031 failure

### ISSUE THREAD

**Issue by vbekiaris** [hazelcast/hazelcast#12663]
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/14557/testReport/junit/com.hazelcast.client.map/ClientMapLoadAllTest/testGetMap_issue_3031/

```
org.junit.runners.model.TestTimedOutException: test timed out after 60000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:304)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:153)
	at com.hazelcast.map.impl.proxy.MapProxySupport.invokeOperation(MapProxySupport.java:425)
	at com.hazelcast.map.impl.proxy.MapProxySupport.putInternal(MapProxySupport.java:390)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.put(MapProxyImpl.java:132)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.put(MapProxyImpl.java:123)
	at com.hazelcast.client.map.ClientMapLoadAllTest.populateMap(ClientMapLoadAllTest.java:164)
	at com.hazelcast.client.map.ClientMapLoadAllTest.testGetMap_issue_3031(ClientMapLoadAllTest.java:75)
```

**Comment by mustafaiman** [comment]
Test fails during populating the map from Server.

**Comment by sancar** [comment]
Hi, a new failure. It seems like failed for same reason. May be logs can help more. 
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/14795/testReport/junit/com.hazelcast.client.map/ClientMapLoadAllTest/testGetMap_issue_3031/

https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/14795/artifact/hazelcast-client/target/surefire-reports/com.hazelcast.client.map.ClientMapLoadAllTest-output.txt
