### ISSUE TITLE
ClientServiceTest.testClientListenerDisconnected fails randomly

### ISSUE THREAD

**Issue by Holmistr** [hazelcast/hazelcast#12674]
*master*

Failed in the PR builder for master branch: https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/14581/testReport/junit/com.hazelcast.client/ClientServiceTest/testClientListenerDisconnected/

Stacktrace:
```
org.junit.runners.model.TestTimedOutException: test timed out after 120000 milliseconds
	at java.lang.Thread.sleep(Native Method)
	at java.lang.Thread.sleep(Thread.java:340)
	at java.util.concurrent.TimeUnit.sleep(TimeUnit.java:386)
	at com.hazelcast.test.HazelcastTestSupport.sleepMillis(HazelcastTestSupport.java:349)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1208)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1217)
	at com.hazelcast.client.ClientServiceTest.testClientListenerDisconnected(ClientServiceTest.java:337)
```

Standard output (interesting part):
```
12:41:51,703  INFO |testClientListenerDisconnected| - [TransactionManagerService] hz._hzInstance_6_dev.cached.thread-6 - [127.0.0.1]:5006 [dev] [3.10-SNAPSHOT] Committing/rolling-back alive transactions of client, UUID: 2dae38da-71df-46a9-abbb-29c4c655f3d1
12:41:51,705  INFO |testClientListenerDisconnected| - [TransactionManagerService] hz._hzInstance_5_dev.cached.thread-6 - [127.0.0.1]:5005 [dev] [3.10-SNAPSHOT] Committing/rolling-back alive transactions of client, UUID: e89c62d9-107e-4f60-8217-aef45a740822
12:41:51,705  INFO |testClientListenerDisconnected| - [TransactionManagerService] hz._hzInstance_5_dev.cached.thread-6 - [127.0.0.1]:5005 [dev] [3.10-SNAPSHOT] Committing/rolling-back alive transactions of client, UUID: 1a67a2f9-5e03-46eb-b832-ae377cda0bb1
12:41:51,706  INFO |testClientListenerDisconnected| - [TransactionManagerService] hz._hzInstance_6_dev.cached.thread-6 - [127.0.0.1]:5006 [dev] [3.10-SNAPSHOT] Committing/rolling-back alive transactions of client, UUID: 1a67a2f9-5e03-46eb-b832-ae377cda0bb1
12:41:51,707  INFO |testClientListenerDisconnected| - [TransactionManagerService] hz._hzInstance_6_dev.cached.thread-6 - [127.0.0.1]:5006 [dev] [3.10-SNAPSHOT] Committing/rolling-back alive transactions of client, UUID: e89c62d9-107e-4f60-8217-aef45a740822

Hiccups measured while running test 'testClientListenerDisconnected(com.hazelcast.client.ClientServiceTest):'
12:40:55, accumulated pauses: 1004 ms, max pause: 406 ms, pauses over 1000 ms: 0
12:41:00, accumulated pauses: 1879 ms, max pause: 298 ms, pauses over 1000 ms: 0
12:41:05, accumulated pauses: 939 ms, max pause: 264 ms, pauses over 1000 ms: 0
12:41:10, accumulated pauses: 1600 ms, max pause: 280 ms, pauses over 1000 ms: 0
12:41:15, accumulated pauses: 1944 ms, max pause: 696 ms, pauses over 1000 ms: 0
12:41:20, accumulated pauses: 1357 ms, max pause: 157 ms, pauses over 1000 ms: 0
12:41:25, accumulated pauses: 2245 ms, max pause: 631 ms, pauses over 1000 ms: 0
12:41:30, accumulated pauses: 1359 ms, max pause: 128 ms, pauses over 1000 ms: 0
12:41:35, accumulated pauses: 1574 ms, max pause: 240 ms, pauses over 1000 ms: 0
12:41:40, accumulated pauses: 2390 ms, max pause: 326 ms, pauses over 1000 ms: 0
12:41:45, accumulated pauses: 776 ms, max pause: 34 ms, pauses over 1000 ms: 0
12:41:50, accumulated pauses: 752 ms, max pause: 16 ms, pauses over 1000 ms: 0
12:41:55, accumulated pauses: 724 ms, max pause: 24 ms, pauses over 1000 ms: 0
12:42:00, accumulated pauses: 768 ms, max pause: 40 ms, pauses over 1000 ms: 0
12:42:05, accumulated pauses: 692 ms, max pause: 23 ms, pauses over 1000 ms: 0
12:42:10, accumulated pauses: 665 ms, max pause: 21 ms, pauses over 1000 ms: 0
12:42:15, accumulated pauses: 387 ms, max pause: 18 ms, pauses over 1000 ms: 0
12:42:20, accumulated pauses: 143 ms, max pause: 49 ms, pauses over 1000 ms: 0
12:42:25, accumulated pauses: 28 ms, max pause: 4 ms, pauses over 1000 ms: 0
12:42:30, accumulated pauses: 35 ms, max pause: 6 ms, pauses over 1000 ms: 0
12:42:35, accumulated pauses: 41 ms, max pause: 6 ms, pauses over 1000 ms: 0
12:42:40, accumulated pauses: 38 ms, max pause: 5 ms, pauses over 1000 ms: 0
12:42:45, accumulated pauses: 37 ms, max pause: 2 ms, pauses over 1000 ms: 0
12:42:50, accumulated pauses: 28 ms, max pause: 0 ms, pauses over 1000 ms: 0
12:42:55, accumulated pauses: 51 ms, max pause: 21 ms, pauses over 1000 ms: 0
```

**Comment by Holmistr** [comment]
Maybe @sancar can take a look?

**Comment by mmedenjak** [comment]
Failed in maintenance. Backport maybe @sancar ?
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/15153

**Comment by mmedenjak** [comment]
Ok, I am going to assume this is not critical and move it to the next release :)

**Comment by kwart** [comment]
Reopeneing I see a new failure on 3.10 branch:
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/15242/

**Comment by Holmistr** [comment]
Closing for now with additional logging added in the linked PRs. See the reasoning here: https://github.com/hazelcast/hazelcast/pull/13081#issuecomment-388888448

**Comment by blazember** [comment]
New failure on master: https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-pr-builder/15851/
