### ISSUE TITLE
general HazelcastException wraps specific MemberLeftException

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#12678]
https://hazelcast-l337.ci.cloudbees.com/view/freeze/job/freeze-all/19/console#

/disk1/jenkins/workspace/freeze-all/3.10-SNAPSHOT/2018_03_20-16_04_37/stable/executor/scheduled/schedule-dispose-all Failed

```
fail HzMember3HZ _executor-scheduled_schedule-all_dispose hzcmd.executor.scheduled.DisposeAll threadId=0 com.hazelcast.core.HazelcastException: com.hazelcast.core.MemberLeftException: Member [10.0.0.22]:5701 - 9ac3685e-f339-449a-b139-afd41dcc20c5 has left cluster! 
```

http://54.82.84.143/~jenkins/workspace/freeze-all/3.10-SNAPSHOT/2018_03_20-16_04_37/stable/executor/scheduled/schedule-dispose-all

```
com.hazelcast.core.HazelcastException: com.hazelcast.core.MemberLeftException: Member [10.0.0.22]:5701 - 9ac3685e-f339-449a-b139-afd41dcc20c5 has left cluster!
	at com.hazelcast.util.ExceptionUtil$1.create(ExceptionUtil.java:40)
	at com.hazelcast.util.ExceptionUtil.peel(ExceptionUtil.java:116)
	at com.hazelcast.util.ExceptionUtil.peel(ExceptionUtil.java:69)
	at com.hazelcast.util.ExceptionUtil.rethrow(ExceptionUtil.java:129)
	at com.hazelcast.scheduledexecutor.impl.ScheduledExecutorServiceProxy.retrieveAllMemberOwnedScheduled(ScheduledExecutorServiceProxy.java:333)
	at com.hazelcast.scheduledexecutor.impl.ScheduledExecutorServiceProxy.getAllScheduledFutures(ScheduledExecutorServiceProxy.java:306)
	at hzcmd.executor.scheduled.DisposeAll.timeStep(DisposeAll.java:21)
	at remote.bench.marker.MetricsMarker.flatOut(MetricsMarker.java:53)
	at remote.bench.marker.MetricsMarker.bench(MetricsMarker.java:40)
	at remote.bench.BenchThread.call(BenchThread.java:38)
	at remote.bench.BenchThread.call(BenchThread.java:12)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:473)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.hazelcast.core.MemberLeftException: Member [10.0.0.22]:5701 - 9ac3685e-f339-449a-b139-afd41dcc20c5 has left cluster!
	at com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor$OnMemberLeftTask.onTargetLoss(InvocationMonitor.java:392)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor$OnMemberLeftTask.run0(InvocationMonitor.java:359)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor$MonitorTask.run(InvocationMonitor.java:240)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:473)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
	at java.lang.Thread.run(Thread.java:748)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:127)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:79)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:155)
	at com.hazelcast.scheduledexecutor.impl.InvokeOnMembers.retryFailedTargets(InvokeOnMembers.java:127)
	at com.hazelcast.scheduledexecutor.impl.InvokeOnMembers.invoke(InvokeOnMembers.java:78)
	at com.hazelcast.scheduledexecutor.impl.ScheduledExecutorServiceProxy.retrieveAllMemberOwnedScheduled(ScheduledExecutorServiceProxy.java:331)
	... 12 more
```

**Comment by ahmetmircik** [comment]
closed in favour of: https://github.com/hazelcast/hazelcast/issues/10763

**Comment by Danny-Hazelcast** [comment]
@ahmetmircik  just to check  is it the same stack trace / same code path which causes the issue 
#10763

the do not look like the same stack trace and so not the same code path that is causing the issue 
and so will need to be fixed in separate places ?

**Comment by mmedenjak** [comment]
Although annoying, I think this approach is ok for now. The reason is that `MemberLeftException` isn't a subtype of `HazelcastException` and the user should then `catch (HazelcastException ex)` and `catch (MemberLeftException ex)` if we were to unwrap it.
This whole idea of wrapping is debatable and we don't have a concensus on it - some services wrap some exceptions, some don't wrap some exceptions.
I'm moving this to 4.0 as this seems to be ok for now.

**Comment by Danny-Hazelcast** [comment]
ok, the confusion about which exceptions are thrown makes using hazelcast more tricky to use and soak test.  

also i thought we were not throwing the generic `HazelcastException`  and only using it a base class 

anyway maybe a PRD is needed to think about making exception handling in hazelcast easy.

**Comment by mmedenjak** [comment]
+1, I am definitely for cleaning up various exceptions in 4.0. Related issue - https://github.com/hazelcast/hazelcast/issues/12233
