### ISSUE TITLE
ClientServiceTest

### ISSUE THREAD

**Issue by Donnerbart** [hazelcast/hazelcast#12673]
**com.hazelcast.client.ClientServiceTest.testClientListenerDisconnected**
```java
org.junit.runners.model.TestTimedOutException: test timed out after 120000 milliseconds
	at java.lang.Thread.sleep(Native Method)
	at java.lang.Thread.sleep(Thread.java:340)
	at java.util.concurrent.TimeUnit.sleep(TimeUnit.java:386)
	at com.hazelcast.test.HazelcastTestSupport.sleepMillis(HazelcastTestSupport.java:349)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1208)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1217)
	at com.hazelcast.client.ClientServiceTest.testClientListenerDisconnected(ClientServiceTest.java:337)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/14581/testReport/junit/com.hazelcast.client/ClientServiceTest/testClientListenerDisconnected/

**Comment by Donnerbart** [comment]
Duplicate of https://github.com/hazelcast/hazelcast/issues/12674
