### ISSUE TITLE
MembershipFailureTest

### ISSUE THREAD

**Issue by Donnerbart** [hazelcast/hazelcast#12677]
**com.hazelcast.internal.cluster.impl.MembershipFailureTest.test_whenNodesStartedTerminatedConcurrently[fd:deadline]**
```java
java.lang.AssertionError: Cluster size is not correct. Expected: 2, actual: 1, instance index: 0
	at org.junit.Assert.fail(Assert.java:88)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSize(HazelcastTestSupport.java:990)
	at com.hazelcast.test.HazelcastTestSupport$14.run(HazelcastTestSupport.java:1017)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1200)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:1014)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:1002)
	at com.hazelcast.internal.cluster.impl.MembershipFailureTest.test_whenNodesStartedTerminatedConcurrently(MembershipFailureTest.java:672)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/14577/testReport/junit/com.hazelcast.internal.cluster.impl/MembershipFailureTest/test_whenNodesStartedTerminatedConcurrently_fd_deadline_/

Occurred in a PR builder. I had a quick peek at the closed issues and it looks like all other fixes have been merged before.

**Comment by sancar** [comment]
Three tests failed under same class. http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/5654/
All seems to have same problem. 

http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/5654/testReport/junit/com.hazelcast.internal.cluster.impl/MembershipFailureTest/slave_heartbeat_removes_suspicion_fd_deadline_/

```
Error Message
Cluster size is not correct. Expected: 3, actual: 2, instance index: 0
Stacktrace
java.lang.AssertionError: Cluster size is not correct. Expected: 3, actual: 2, instance index: 0
	at com.hazelcast.internal.cluster.impl.MembershipFailureTest.slave_heartbeat_removes_suspicion(MembershipFailureTest.java:317)
Standard Output
```

**Comment by mmedenjak** [comment]
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/4395/

**Comment by ahmetmircik** [comment]
Not failing for a long time, closing until next failure.
