### ISSUE TITLE
EntryProcessorOffloadableTest.testHeartBeatsComingWhenEntryPropcessorOffloaded failure

### ISSUE THREAD

**Issue by Holmistr** [hazelcast/hazelcast#12744]
*master*

Failed on Oracle JDK6:
https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-OracleJDK1.6-freestyle/lastCompletedBuild/testReport/

Stacktrace:
```
java.lang.AssertionError: Heartbeats came too close to each other: 773ms
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.map.EntryProcessorOffloadableTest.testHeartBeatsComingWhenEntryPropcessorOffloaded(EntryProcessorOffloadableTest.java:998)
```

Standard output:
```
04:28:20, accumulated pauses: 860 ms, max pause: 659 ms, pauses over 1000 ms: 0
04:28:25, accumulated pauses: 3889 ms, max pause: 3032 ms, pauses over 1000 ms: 1
04:28:30, accumulated pauses: 246 ms, max pause: 190 ms, pauses over 1000 ms: 0
```

Maybe related to https://github.com/hazelcast/hazelcast-enterprise/issues/2012 @tkountis  ?

**Comment by Holmistr** [comment]
*maintenance* (commit 56dd06f989e32e753c3d98a3b47faae259eec1c6)

Reopening as it failed with Oracle JDK6, but this time with a different stacktrace: https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.maintenance-OracleJDK6/lastCompletedBuild/testReport/com.hazelcast.map/EntryProcessorOffloadableTest/testHeartBeatsComingWhenEntryPropcessorOffloaded_0__BINARY_sync_0_async_0_/

Stacktrace:
```
java.lang.AssertionError: At least 4 heartBeats expected, 3 came.
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.map.EntryProcessorOffloadableTest.testHeartBeatsComingWhenEntryPropcessorOffloaded(EntryProcessorOffloadableTest.java:990)
```

Standard output:
```
16:58:20, accumulated pauses: 4229 ms, max pause: 1919 ms, pauses over 1000 ms: 2
16:58:25, accumulated pauses: 187 ms, max pause: 18 ms, pauses over 1000 ms: 0
16:58:30, accumulated pauses: 405 ms, max pause: 372 ms, pauses over 1000 ms: 0
```

**Comment by tezc** [comment]
_master_ (commit 3c4d426e678b767816760a41f994066b2aafe2b2)

Failed on IbmJDK : http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK8-fips-nightly/108/#showFailuresLink

**Stacktrace**
```
java.lang.AssertionError: Heartbeats should be received while offloadable entry processor is running
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.map.EntryProcessorOffloadableTest.testHeartBeatsComingWhenEntryProcessorOffloaded(EntryProcessorOffloadableTest.java:910)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.lang.Thread.run(Thread.java:811)
```

**Comment by tezc** [comment]
http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK8-fips-nightly/109/testReport/com.hazelcast.map/EntryProcessorOffloadableTest/testHeartBeatsComingWhenEntryProcessorOffloaded_5__OBJECT_sync_0_async_1_/
