### ISSUE TITLE
Failing ClientCacheQuorumReadTest

### ISSUE THREAD

**Issue by kwart** [hazelcast/hazelcast#12806]
The `ClientCacheQuorumReadTest` fails intermittently in the PR builder:

https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/14974/testReport/junit/com.hazelcast.client.quorum.cache/ClientCacheQuorumReadTest/size_quorum_quorumType_READ_WRITE_/

**Stacktrace**
```
com.hazelcast.cache.CacheNotExistsException: Cache config for cache /hz/quorum103e0700-6bb5-46fa-b6b3-8677d07a073eREAD_WRITE has not been created yet!
	at com.hazelcast.client.impl.protocol.task.cache.AbstractCacheAllPartitionsTask.getOperationProvider(AbstractCacheAllPartitionsTask.java:45)
	at com.hazelcast.client.impl.protocol.task.cache.CacheSizeMessageTask.createOperationFactory(CacheSizeMessageTask.java:47)
	at com.hazelcast.client.impl.protocol.task.AbstractAllPartitionsMessageTask.processMessage(AbstractAllPartitionsMessageTask.java:38)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:130)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:110)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:96)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:33)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:162)
	at com.hazelcast.client.cache.impl.AbstractClientCacheProxyBase.invoke(AbstractClientCacheProxyBase.java:207)
	at com.hazelcast.client.cache.impl.AbstractClientCacheProxy.size(AbstractClientCacheProxy.java:428)
	at com.hazelcast.client.cache.impl.ClientCacheProxy.size(ClientCacheProxy.java:94)
	at com.hazelcast.quorum.cache.CacheQuorumReadTest.size_quorum(CacheQuorumReadTest.java:127)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by ahmetmircik** [comment]
also see: https://github.com/hazelcast/hazelcast-enterprise/issues/2048

**Comment by mdogan** [comment]
See https://github.com/hazelcast/hazelcast-enterprise/issues/2054#issuecomment-380755334 to understand how this test fails.

**Comment by blazember** [comment]
New failure in 3.10.x PR: https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-pr-builder/15898/testReport/junit/com.hazelcast.client.quorum.cache/ClientCacheQuorumReadTest/com_hazelcast_client_quorum_cache_ClientCacheQuorumReadTest/

This time with a different cause:

```
java.lang.AssertionError: CountDownLatch failed to complete within 60 seconds, count left: 2
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:1129)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:1114)
	at com.hazelcast.quorum.PartitionedCluster.splitFiveMembersThreeAndTwo(PartitionedCluster.java:97)
	at com.hazelcast.quorum.AbstractQuorumTest.initCluster(AbstractQuorumTest.java:267)
	at com.hazelcast.quorum.AbstractQuorumTest.initTestEnvironment(AbstractQuorumTest.java:104)
	at com.hazelcast.client.quorum.cache.ClientCacheQuorumReadTest.setUp(ClientCacheQuorumReadTest.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeLazy(JUnitCoreWrapper.java:119)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:87)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:379)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:340)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:413)
```

**Comment by mustafaiman** [comment]
@blazember pointed out that the issue resurfaced because of a forgotten backport. Should be fixed vy https://github.com/hazelcast/hazelcast/pull/13282
