### ISSUE TITLE
Hazelcast is continously throwing "java.io.IOException: Packet not send to [10.60.0.229]:5701" 

### ISSUE THREAD

**Issue by barathguna** [hazelcast/hazelcast#12812]
Hazelcast is continously throwing "java.io.IOException: Packet not send to [10.60.0.229]:5701" exception. This happens after one time error of "java.lang.NoClassDefFoundError: com/hazelcast/internal/networking/nonblocking/NonBlockingSocketReader$2".

Double checked on classpath and only "hazelcast-3.8.9.jar" and "hazelcast-client-3.8.9.jar" are in our classpath.

Issue:
1. Why NoClassDefFoundError for the NonBlockingSocketReader$2? Is it a known issue?
2. Why HazelcastInstance object (created via HazelcastClient.newHazelcastClient(clientConfig)) is not closed after 2 "java.io.IOException: Packet not send to [10.60.0.229]:5701" exception?
3. Is it possible to detect the HazelcastInstance which are in this state at client side and kill it and create new HazelcastInstance object?

Note: 
1. It happened once and it is hardly reproducible. 
2. Tested multiple times by killing the hazelcase server and,
        1. NoClassDefFoundError is never thrown.
        2. Hazelcast client connection closed after 2 retry.

> Apr 03, 2018 9:17:18 PM com.hazelcast.client.connection.nio.ClientConnection
> INFO: distributed-cache-service [dev] [3.8.9] ClientConnection{alive=false, connectionId=1, socketChannel=DefaultSocketChannelWrapper{socketChannel=java.nio.channels.SocketChannel[connected local=/10.60.3.79:47878 remote=distributed-cache-service.fusion.svc.cluster.local/10.60.10.212:5701]}, remoteEndpoint=[10.60.0.229]:5701, lastReadTime=2018-04-03 21:17:18.171, lastWriteTime=2018-04-03 21:17:11.487, closedTime=2018-04-03 21:17:18.172, lastHeartbeatRequested=2018-04-03 21:17:11.276, lastHeartbeatReceived=2018-04-03 21:17:11.277, connected server version=3.8.9} closed. Reason: Connection closed by the other side
> Apr 03, 2018 9:17:18 PM com.hazelcast.internal.networking.nonblocking.NonBlockingIOThread
> WARNING: distributed-cache-service [dev] [3.8.9] Unhandled exception in hz.distributed-cache-service.IO.thread-in-0
> java.lang.NoClassDefFoundError: com/hazelcast/internal/networking/nonblocking/NonBlockingSocketReader$2
>         at com.hazelcast.internal.networking.nonblocking.NonBlockingSocketReader.close(NonBlockingSocketReader.java:171)
>         at com.hazelcast.client.connection.nio.ClientConnection.innerClose(ClientConnection.java:290)
>         at com.hazelcast.client.connection.nio.ClientConnection.close(ClientConnection.java:251)
>         at com.hazelcast.internal.networking.nonblocking.AbstractHandler.onFailure(AbstractHandler.java:128)
>         at com.hazelcast.internal.networking.nonblocking.NonBlockingIOThread.handleSelectionKey(NonBlockingIOThread.java:351)
>         at com.hazelcast.internal.networking.nonblocking.NonBlockingIOThread.handleSelectionKeys(NonBlockingIOThread.java:334)
>         at com.hazelcast.internal.networking.nonblocking.NonBlockingIOThread.selectLoop(NonBlockingIOThread.java:252)
>         at com.hazelcast.internal.networking.nonblocking.NonBlockingIOThread.run(NonBlockingIOThread.java:205)
> Caused by: java.lang.ClassNotFoundException: com.hazelcast.internal.networking.nonblocking.NonBlockingSocketReader$2
>         at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
>         at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
>         at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:450)
>         at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:403)
>         ... 8 more
> 
> Apr 03, 2018 9:17:21 PM com.hazelcast.client.spi.ClientPartitionService
> WARNING: distributed-cache-service [dev] [3.8.9] Error while fetching cluster partition table!
> java.util.concurrent.ExecutionException: java.io.IOException: Packet not send to [10.60.0.229]:5701
>         at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolve(ClientInvocationFuture.java:72)
>         at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run(AbstractInvocationFuture.java:243)
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
>         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
>         at com.hazelcast.util.executor.LoggingScheduledExecutor$LoggingDelegatingFuture.run(LoggingScheduledExecutor.java:140)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>         at java.lang.Thread.run(Thread.java:745)
>         at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
>         at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
> Caused by: java.io.IOException: Packet not send to [10.60.0.229]:5701
>         at com.hazelcast.client.spi.impl.ClientInvocationServiceSupport.send(ClientInvocationServiceSupport.java:114)
>         at com.hazelcast.client.spi.impl.ClientSmartInvocationServiceImpl.invokeOnConnection(ClientSmartInvocationServiceImpl.java:100)
>         at com.hazelcast.client.spi.impl.ClientInvocation.invokeOnSelection(ClientInvocation.java:142)
>         at com.hazelcast.client.spi.impl.ClientInvocation.invokeUrgent(ClientInvocation.java:135)
>         at com.hazelcast.client.spi.impl.ClientPartitionServiceImpl.getPartitionsFrom(ClientPartitionServiceImpl.java:138)
>         at com.hazelcast.client.spi.impl.ClientPartitionServiceImpl.access$600(ClientPartitionServiceImpl.java:47)
>         at com.hazelcast.client.spi.impl.ClientPartitionServiceImpl$RefreshTask.run(ClientPartitionServiceImpl.java:242)
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
>         at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
>         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
>         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
>         ... 6 more
> 
> Apr 03, 2018 9:17:31 PM com.hazelcast.client.spi.ClientPartitionService
> WARNING: distributed-cache-service [dev] [3.8.9] Error while fetching cluster partition table!
> java.util.concurrent.ExecutionException: java.io.IOException: Packet not send to [10.60.0.229]:5701
>         at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolve(ClientInvocationFuture.java:72)
>         at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run(AbstractInvocationFuture.java:243)
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
>         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
>         at com.hazelcast.util.executor.LoggingScheduledExecutor$LoggingDelegatingFuture.run(LoggingScheduledExecutor.java:140)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)

**Comment by ahmetmircik** [comment]
can you please give more details about your deployment, java version, web server version, are you using hot deploy? Or can it be possible some class files were removed by something?

**Comment by barathguna** [comment]
Hello,

Root cause: intermediate mount issue with glusterfs caused the NoClassDefFoundError.

Refer: https://github.com/hazelcast/hazelcast/blob/v3.8.9/hazelcast/src/main/java/com/hazelcast/internal/networking/nonblocking/NonBlockingIOThread.java

In run method catch block with Throwable is just logging. 
Could you add a hook for the application to register for Throwable?

Thanks
-Barath

**Comment by mmedenjak** [comment]
Hi @barathguna ! 

Thank you for submitting the report. I believe you are referring to [this line](https://github.com/mmedenjak/hazelcast/blob/5a0ce6538799fd6ad95ad698d3f482b13ea57605/hazelcast/src/main/java/com/hazelcast/internal/networking/nonblocking/NonBlockingIOThread.java#L223). We will most probably not be adding a hook for processing `Throwable` in the close future but I will keep this issue open for future consideration. If there is more community interest, we may consider adding it.
