### ISSUE TITLE
Sporadic hazelcast timeouts

### ISSUE THREAD

**Issue by praveensrao** [hazelcast/hazelcast#12838]
Hi,

We are having a constant issue that has cropped up in our production environment when sporadically hazelcast operations timeout on one of the maps (where we have integration with shiro to store http sessions) a couple of times in the day.
I am not able to attach a unit test because the issue is not seen in other environments.

**Java being used:**
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

**Hazelcast version used:**
Hazelcast 3.6.4

**Deployment architecture:**
We have 2 hazelcast jvms - hazelcast0 and hazelcast1 that form a cluster and deployed as spring boot applications. (Spring Boot :: v1.4.1.RELEASE)
We then have the business application tomcat servers that serve business REST apis and communicate with hazelcast to store authenticated sessions (tomcat Server version: Apache Tomcat/7.0.56 (Debian))

Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u5 (2017-09-19) x86_64 GNU/Linux

**Log stacktrace in one of the hazelcast jvms:**

```
AsyncResolver-bootstrap-executor-0 2018-04-11 12:48:06,892 INFO  com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver.getClusterEndpoints(ConfigClusterResolver.java:43) - Resolving eureka endpoints via configuration
AsyncResolver-bootstrap-executor-0 2018-04-11 12:53:06,892 INFO  com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver.getClusterEndpoints(ConfigClusterResolver.java:43) - Resolving eureka endpoints via configuration
hz._hzInstance_1_dev.InvocationMonitorThread 2018-04-11 12:56:12,701 INFO  com.hazelcast.logging.StandardLoggerFactory$StandardLogger.log(StandardLoggerFactory.java:49) - [127.0.0.1]:11410 [dev] [3.6.4] Invocations:1 timeouts:1 backup-timeouts:0
cached4 2018-04-11 12:56:12,702 WARN  com.hazelcast.logging.StandardLoggerFactory$StandardLogger.log(StandardLoggerFactory.java:49) - [127.0.0.1]:11410 [dev] [3.6.4] Asking if operation execution has been started: Invocation{serviceName='hz:impl:mapService', op=com.hazelcast.map.impl.operation.PutOperation{identityHash=615799460, serviceName='hz:impl:mapService', partitionId=74, replicaIndex=0, callId=2342007, invocationTime=1523465633284 (Wed Apr 11 12:53:53 EDT 2018), waitTimeout=-1, callTimeout=60000, name=shiro-activeSessionCache, name=shiro-activeSessionCache}, partitionId=74, replicaIndex=0, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeout=60000, target=Address[127.0.0.1]:11410, backupsExpected=1, backupsCompleted=0, connection=null}
hz._hzInstance_1_dev.async.thread-2 2018-04-11 12:56:12,702 WARN  com.hazelcast.logging.StandardLoggerFactory$StandardLogger.log(StandardLoggerFactory.java:49) - [127.0.0.1]:11410 [dev] [3.6.4] 'is-executing': false -> Invocation{serviceName='hz:impl:mapService', op=com.hazelcast.map.impl.operation.PutOperation{identityHash=615799460, serviceName='hz:impl:mapService', partitionId=74, replicaIndex=0, callId=2342007, invocationTime=1523465633284 (Wed Apr 11 12:53:53 EDT 2018), waitTimeout=-1, callTimeout=60000, name=shiro-activeSessionCache, name=shiro-activeSessionCache}, partitionId=74, replicaIndex=0, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeout=60000, target=Address[127.0.0.1]:11410, backupsExpected=1, backupsCompleted=0, connection=null}
```

**Relevant Log stacktrace in the application jvm:**

```
com.hazelcast.core.OperationTimeoutException: No response for 120000 ms. Aborting invocation! Invocation{serviceName='hz:impl:mapService', op=com.hazelcast.map.impl.operation.PutOperation{identityHash=166531985, serviceName='hz:impl:mapService', partitionId=74, replicaIndex=0, callId=2355513, invocationTime=1523468800538 (Wed Apr 11 13:46:40 EDT 2018), waitTimeout=-1, callTimeout=60000, name=shiro-activeSessionCache, name=shiro-activeSessionCache}, partitionId=74, replicaIndex=0, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeout=60000, target=Address[127.0.0.1]:11410, backupsExpected=1, backupsCompleted=0, connection=null} Not all backups have completed!  backups-expected:1 backups-completed: 0
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.newOperationTimeoutException(Invocation.java:530) ~[hazelcast-all-3.6.4.jar:3.6.4]
	at com.hazelcast.spi.impl.operationservice.impl.IsStillRunningService$IsOperationStillRunningCallback.setOperationTimeout(IsStillRunningService.java:241) ~[hazelcast-all-3.6.4.jar:3.6.4]
	at com.hazelcast.spi.impl.operationservice.impl.IsStillRunningService$IsOperationStillRunningCallback.onResponse(IsStillRunningService.java:229) ~[hazelcast-all-3.6.4.jar:3.6.4]
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture$1.run(InvocationFuture.java:127) ~[hazelcast-all-3.6.4.jar:3.6.4]
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76) ~[hazelcast-all-3.6.4.jar:3.6.4]
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92) ~[hazelcast-all-3.6.4.jar:3.6.4]
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveResponse(ClientInvocationFuture.java:128) ~[hazelcast-all-3.6.4.jar:3.6.4]
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.get(ClientInvocationFuture.java:95) ~[hazelcast-all-3.6.4.jar:3.6.4]
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.get(ClientInvocationFuture.java:74) ~[hazelcast-all-3.6.4.jar:3.6.4]
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.get(ClientInvocationFuture.java:37) ~[hazelcast-all-3.6.4.jar:3.6.4]
	at com.hazelcast.client.spi.ClientProxy.invokeOnPartition(ClientProxy.java:126) ~[hazelcast-all-3.6.4.jar:3.6.4]
	at com.hazelcast.client.spi.ClientProxy.invoke(ClientProxy.java:120) ~[hazelcast-all-3.6.4.jar:3.6.4]
	at com.hazelcast.client.proxy.ClientMapProxy.putInternal(ClientMapProxy.java:411) ~[hazelcast-all-3.6.4.jar:3.6.4]
	at com.hazelcast.client.proxy.ClientMapProxy.put(ClientMapProxy.java:405) ~[hazelcast-all-3.6.4.jar:3.6.4]
	at com.hazelcast.client.proxy.ClientMapProxy.put(ClientMapProxy.java:233) ~[hazelcast-all-3.6.4.jar:3.6.4]
```

Is there a way to troubleshoot why we are getting these sporadic timeouts?
Any help would be appreciated. Thanks.

**Comment by ahmetmircik** [comment]
Hi @praveensrao,
 
A quick action to recommend can be upgrading to the latest 3.10 if it is possible for you, lots of fixes done after 3.6. And by starting 3.7, there is [diagnostics](http://docs.hazelcast.org/docs/latest-development/manual/html/Management/Diagnostics/index.html) support to monitor system better, you can enable it. 

Other than this, it seems it is hard to reason about this sporadic timeout with the givens. Maybe you can provide some more info for the time of incident like gc logs, thread dumps, your hazelcast configuration, hazelcast logs and we can try to reason with those.

**Comment by praveensrao** [comment]
Thanks for the inputs @ahmetmircik 
Will try upgrading and get back

**Comment by mmedenjak** [comment]
@praveensrao any updates on the issue?

**Comment by mmedenjak** [comment]
Closing the issue due to non-activity. Please open a new issue with more information or when you encounter other problems running Hazelcast.
