### ISSUE TITLE
Failing ConnectMemberListOrderTest

### ISSUE THREAD

**Issue by kwart** [hazelcast/hazelcast#12841]
The
**`com.hazelcast.client.connection.nio.ConnectMemberListOrderTest.testPossibleMemberAddressesAfterDisconnection[shuffleMemberList == false]`**
failed in the PR builder:
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/15070/testReport/junit/com.hazelcast.client.connection.nio/ConnectMemberListOrderTest/testPossibleMemberAddressesAfterDisconnection_shuffleMemberList____false_/

**Stacktrace**
```
java.lang.AssertionError: Values should be different. Actual: [127.0.0.1]:5024
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failEquals(Assert.java:185)
	at org.junit.Assert.assertNotEquals(Assert.java:161)
	at org.junit.Assert.assertNotEquals(Assert.java:175)
	at com.hazelcast.client.connection.nio.ConnectMemberListOrderTest.testPossibleMemberAddressesAfterDisconnection(ConnectMemberListOrderTest.java:97)
```

**Comment by mmedenjak** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/15059

**Comment by ahmetmircik** [comment]
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/4092/testReport/junit/com.hazelcast.client.impl.connection.nio/ConnectMemberListOrderTest/testPossibleMemberAddressesAfterDisconnection_shuffleMemberList____true_/

```
Error Message
possibleMemberAddresses : [[127.0.0.1]:5701, [127.0.0.1]:5703, [127.0.0.1]:5702], lastConnectedMemberAddress [127.0.0.1]:5701. Actual: [127.0.0.1]:5701
Stacktrace
java.lang.AssertionError: possibleMemberAddresses : [[127.0.0.1]:5701, [127.0.0.1]:5703, [127.0.0.1]:5702], lastConnectedMemberAddress [127.0.0.1]:5701. Actual: [127.0.0.1]:5701
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failEquals(Assert.java:185)
	at org.junit.Assert.assertNotEquals(Assert.java:161)
	at com.hazelcast.client.impl.connection.nio.ConnectMemberListOrderTest.testPossibleMemberAddressesAfterDisconnection(ConnectMemberListOrderTest.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```
