### ISSUE TITLE
NullPointerException canAcquireLock(LockResourceImpl.java:149) HzClient 3.9.4

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#12869]
In this multi version Compatibility test 

https://hazelcast-l337.ci.cloudbees.com/view/multi-version/job/multi-version-client-compat/44/consoleFull

clusterCase2

```
HzMember1HZ Started on  /home/ec2-user/hz-root/hz-lib/3.6.8 
HzClient1HZ Started on  /home/ec2-user/hz-root/hz-lib/3.6.8 
HzClient2HZ Started on  /home/ec2-user/hz-root/hz-lib/3.7.8 
HzClient3HZ Started on  /home/ec2-user/hz-root/hz-lib/3.8.9 
HzClient4HZ Started on  /home/ec2-user/hz-root/hz-lib/3.9.4 
HzClient5HZ Started on  /home/ec2-user/hz-root/hz-lib/3.10-SNAPSHOT
````

HzClient4HZ 3.9.4

`fail HzClient4HZ _create-use-destroy_createUseDestroy_lock hzcmd.lock.CreateUseDestroy threadId=0 java.lang.NullPointerException` 

/disk1/jenkins/workspace/multi-version-client-compat/3.10-SNAPSHOT/2018_04_13-19_15_49/create-use-destroy-usa/clusterCase2

```
[jenkins@ip-10-72-134-107 clusterCase2]$ cat ./HZ/HzClient4HZ/exception.txt
java.lang.NullPointerException
    at com.hazelcast.concurrent.lock.LockResourceImpl.canAcquireLock(LockResourceImpl.java:149)
    at com.hazelcast.concurrent.lock.LockStoreImpl.canAcquireLock(LockStoreImpl.java:146)
    at com.hazelcast.concurrent.lock.operations.LockOperation.shouldWait(LockOperation.java:64)
    at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.waitingNeeded(OperationRunnerImpl.java:225)
    at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:168)
    at com.hazelcast.spi.impl.operationexecutor.classic.ClassicOperationExecutor.runOnCallingThread(ClassicOperationExecutor.java:392)
    at com.hazelcast.spi.impl.operationexecutor.classic.ClassicOperationExecutor.runOnCallingThreadIfPossible(ClassicOperationExecutor.java:345)
    at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:259)
    at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:243)
    at com.hazelcast.spi.impl.operationservice.impl.Invocation.invokeInternal(Invocation.java:210)
    at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:180)
    at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:46)
    at com.hazelcast.client.impl.protocol.task.AbstractPartitionMessageTask.processMessage(AbstractPartitionMessageTask.java:65)
    at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:118)
    at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:98)
    at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:127)
    at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.processPartitionSpecificRunnable(OperationThread.java:159)
    at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.process(OperationThread.java:142)
    at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.doRun(OperationThread.java:124)
    at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.run(OperationThread.java:99)
    at ------ submitted from ------.(Unknown Source)
    at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:96)
    at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:33)
    at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:155)
    at com.hazelcast.client.spi.ClientProxy.invokeOnPartition(ClientProxy.java:225)
    at com.hazelcast.client.proxy.PartitionSpecificClientProxy.invokeOnPartition(PartitionSpecificClientProxy.java:49)
    at com.hazelcast.client.proxy.ClientLockProxy.tryLock(ClientLockProxy.java:146)
    at com.hazelcast.client.proxy.ClientLockProxy.tryLock(ClientLockProxy.java:136)
    at hzcmd.lock.CreateUseDestroy.timeStep(CreateUseDestroy.java:18)```
    
```

other cluster cases are failing by hanging in semaphore executor
_create-use-destroy_createUseDestroy_semaphore 
_create-use-destroy_createUseDestroy_executor

**Comment by Danny-Hazelcast** [comment]
re-run, excluding semaphore and executor tests

https://hazelcast-l337.ci.cloudbees.com/view/multi-version/job/multi-version-client-compat/45/console


again   clusterCase2    HzClient3HZ 3.8.9

```
fail HzClient3HZ _create-use-destroy_createUseDestroy_lock hzcmd.lock.CreateUseDestroy threadId=0 java.lang.NullPointerException
```

**Comment by Danny-Hazelcast** [comment]
both fails were in cluster case2 

using member at version 3.6.8, so could the root cause be the member ?

**Comment by mmedenjak** [comment]
I'm not sure about the root cause but I see the lock is used and destroyed. The NPE comes from the check where the lockCount is non-zero but the owner is `null` - this might be because of a concurrent destroy.
OTOH I don't know why this would fail, only or more often, in 3.6.8. Maybe we introduced some changes to the operation system/proxy lifecycle/lock in the later versions which make this issue harder to hit.

**Comment by Danny-Hazelcast** [comment]
there is the old issue with a similar lock NPE
https://github.com/hazelcast/hazelcast/issues/9562

**Comment by mdogan** [comment]
@Danny-Hazelcast: Yes, that looks like the same issue. According to backport PR (https://github.com/hazelcast/hazelcast/pull/9566), it's fixed for 3.7.5+.

**Comment by Danny-Hazelcast** [comment]
both fails were in cluster case2
using member at version 3.6.8.

**Comment by Danny-Hazelcast** [comment]
@mmedenjak  looking at https://hazelcast-l337.ci.cloudbees.com/view/multi-version/job/multi-version-client-compat/45/consoleFull

we can see that the Lock NPE issue is only hit in cluster Case 2

and in the thest we have 14 cluster cases,  where mbember are created at all versions
3.6.8, 3.7.8, 3.8.9,  3.9.4 and 3.10-SANPSHOT

**Comment by mmedenjak** [comment]
@Danny-Hazelcast I'm pretty sure this is the old issue, fixed in 3.7.5. You probably don't need to encounter this issue in every run since it's timing sensitive.
I will inspect the hanging issue and if it's also caused by the concurrent destroy, we can close this as a known issue with the proxy lifecycle.

**Comment by mmedenjak** [comment]
I'm concluding this is an issue with the semaphore/lock/executor lifecycle and how destruction is done on a non-partition thread. In some cases we fixed this issue (as for the lock NPE) but there are still a lot of other issues (e.g. semaphore/executor hanging). 

The hanging is reproducible with this test:
```java
@RunWith(HazelcastParallelClassRunner.class)
@Category({QuickTest.class, ParallelTest.class})
public class SemaphoreConcurrentTest extends HazelcastTestSupport {

    private final AtomicBoolean stop = new AtomicBoolean();
    private HazelcastInstance hzInstance;


    @Test
    public void testAcquire() {
        this.hzInstance = createHazelcastInstance();
        final SemaphoreThread[] threads = new SemaphoreThread[5];
        for (int i = 0; i < 5; i++) {
            final SemaphoreThread thread = new SemaphoreThread();
            thread.start();
            threads[i] = thread;
        }
        sleepAndStop(stop, TimeUnit.MINUTES.toSeconds(1));

        System.out.println("STOPPING TEST");
        for (SemaphoreThread thread : threads) {
            thread.assertSucceedsEventually();
        }
    }

    public class SemaphoreThread extends TestThread {
        @Override
        public void onError(Throwable t) {
            stop.set(true);
        }

        @Override
        public void doRun() {
            while (!stop.get()) {
                try {
                    final Random random = new Random();
                    ISemaphore semaphore = hzInstance.getSemaphore("semaphoreCreateUseDestroy_create-use-destroy"
                            + random.nextInt(1));
                    try {
                        semaphore.init(Integer.MAX_VALUE);
                        semaphore.acquire();
                    } catch (InterruptedException e) {
                    }
                    semaphore.release();
                    semaphore.destroy();
                } catch (DistributedObjectDestroyedException ignored) {

                }
            }
        }
    }
}
```
And by adding this to the `AcquireOperation#getWaitKey`:
```
    @Override
    public WaitNotifyKey getWaitKey() {
        SemaphoreService service = getService();
        if (!service.containsSemaphore(name)){
            System.out.println("PARKING OPERATION FOR A MISSING SEMAPHORE");
        }
        return new SemaphoreWaitNotifyKey(name, "acquire");
    }
```

What happens here is that the acquire operation on the partition threads checks if it needs to park. This returns true. Concurrently the semaphore is destroyed on a non-partition thread. After this, the partition thread is resumed and the operation is parked. But it will never get unparked again since the semaphore doesn't exist anymore.

There is no easy fix for this. We need to introduce ordering between destroy and other partition operations (e.g. destroy the container on the partition thread). Otherwise threads may hang or one thread might initialise a container while an another one is destroying it.

Moving this issue into 3.11.

**Comment by Danny-Hazelcast** [comment]
this issue is about multi version compatibility.  
so is not an issue in 4.0
