### ISSUE TITLE
AbstractDistributedObjectTest intermittent failure

### ISSUE THREAD

**Issue by kwart** [hazelcast/hazelcast#12883]
Several methods failed in class `com.hazelcast.spi.AbstractDistributedObjectTest` in PR builder:
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/15171/testReport/com.hazelcast.spi/AbstractDistributedObjectTest/

**Sample Stacktrace**
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.spi.AbstractDistributedObjectTest.testClusterVersion_isEqualTo_currentVersion(AbstractDistributedObjectTest.java:57)
```

**Comment by taburet** [comment]
Seems like this failure is already fixed by https://github.com/hazelcast/hazelcast/pull/12878. Closing.
