### ISSUE TITLE
LossToleranceTest intermittent failure

### ISSUE THREAD

**Issue by kwart** [hazelcast/hazelcast#12882]
`com.hazelcast.topic.impl.reliable.LossToleranceTest.whenLossTolerant_andOwnerCrashes_thenContinue` failure in PR builder:
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/15181/

**Stacktrace**
```
java.lang.NullPointerException: null
	at com.hazelcast.instance.TestUtil.terminateInstance(TestUtil.java:66)
	at com.hazelcast.topic.impl.reliable.LossToleranceTest.whenLossTolerant_andOwnerCrashes_thenContinue(LossToleranceTest.java:139)
```

**Standard Output**
```
Finished Running Test: whenLossTolerant_thenContinue in 1.306 seconds.
05:46:49,998  INFO |whenLossTolerant_andOwnerCrashes_thenContinue| - [Node] Thread-82 - [127.0.0.1]:5119 [dev] [3.11-SNAPSHOT] Hazelcast Shutdown is completed in 346 ms.
05:46:49,998  INFO |whenLossTolerant_andOwnerCrashes_thenContinue| - [LifecycleService] Thread-82 - [127.0.0.1]:5119 [dev] [3.11-SNAPSHOT] [127.0.0.1]:5119 is SHUTDOWN
05:46:49,998  INFO |whenLossTolerant_andOwnerCrashes_thenContinue| - [LifecycleService] Thread-82 - [127.0.0.1]:5120 [dev] [3.11-SNAPSHOT] [127.0.0.1]:5120 is SHUTTING_DOWN
05:46:49,998  WARN |whenLossTolerant_andOwnerCrashes_thenContinue| - [Node] Thread-82 - [127.0.0.1]:5120 [dev] [3.11-SNAPSHOT] Terminating forcefully...
05:46:49,998  INFO |whenLossTolerant_andOwnerCrashes_thenContinue| - [Node] Thread-82 - [127.0.0.1]:5120 [dev] [3.11-SNAPSHOT] Shutting down connection manager...
05:46:49,998  INFO |whenLossTolerant_andOwnerCrashes_thenContinue| - [Node] Thread-82 - [127.0.0.1]:5120 [dev] [3.11-SNAPSHOT] Shutting down node engine...
05:46:50,002  INFO |whenLossTolerant_andOwnerCrashes_thenContinue| - [NodeExtension] Thread-82 - [127.0.0.1]:5120 [dev] [3.11-SNAPSHOT] Destroying node NodeExtension.
05:46:50,002  INFO |whenLossTolerant_andOwnerCrashes_thenContinue| - [Node] Thread-82 - [127.0.0.1]:5120 [dev] [3.11-SNAPSHOT] Hazelcast Shutdown is completed in 4 ms.
05:46:50,002  INFO |whenLossTolerant_andOwnerCrashes_thenContinue| - [LifecycleService] Thread-82 - [127.0.0.1]:5120 [dev] [3.11-SNAPSHOT] [127.0.0.1]:5120 is SHUTDOWN
BuildInfo right after whenLossTolerant_andOwnerCrashes_thenContinue(com.hazelcast.topic.impl.reliable.LossToleranceTest): BuildInfo{version='3.11-SNAPSHOT', build='20180417', buildNumber=20180417, revision=93ad3f0, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'whenLossTolerant_andOwnerCrashes_thenContinue(com.hazelcast.topic.impl.reliable.LossToleranceTest):'
05:46:45, accumulated pauses: 1056 ms, max pause: 314 ms, pauses over 1000 ms: 0
```

**Comment by mdogan** [comment]
Failed in maintenance branch (3.10.1):

https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/15460/testReport/junit/com.hazelcast.topic.impl.reliable/LossToleranceTest/whenLossTolerant_andOwnerCrashes_thenContinue/

```
java.lang.NullPointerException: null
	at com.hazelcast.instance.TestUtil.terminateInstance(TestUtil.java:66)
	at com.hazelcast.topic.impl.reliable.LossToleranceTest.whenLossTolerant_andOwnerCrashes_thenContinue(LossToleranceTest.java:139)
```

Apparently, this is not backported to maintenance.

**Comment by Holmistr** [comment]
Fixed by https://github.com/hazelcast/hazelcast/pull/13026 (backport).
