### ISSUE TITLE
ClientCacheNearCachePreloaderTest intermittent failure

### ISSUE THREAD

**Issue by kwart** [hazelcast/hazelcast#12899]
The `com.hazelcast.client.cache.nearcache.ClientCacheNearCachePreloaderTest.testPreloadNearCache_withStringKeys` fails on PR builder:
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/15213/

The PR was for the 3.10 branch.

**Stacktrace**
```
java.lang.AssertionError: expected:<value-26> but was:<null>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.internal.nearcache.AbstractNearCachePreloaderTest.assertNearCacheContent(AbstractNearCachePreloaderTest.java:465)
	at com.hazelcast.internal.nearcache.AbstractNearCachePreloaderTest.preloadNearCache(AbstractNearCachePreloaderTest.java:303)
	at com.hazelcast.internal.nearcache.AbstractNearCachePreloaderTest.testPreloadNearCache_withStringKeys(AbstractNearCachePreloaderTest.java:261)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Donnerbart** [comment]
I've downloaded the log files, which are a bit messy due to the parallel method execution. But it looks like the 10k keys have been loaded successfully:
```java
12:20:31,530  INFO |testPreloadNearCache_withStringKeys| - [NearCachePreloader] hz.client_3.internal-1 - Loaded 10000 keys of Near Cache /hz/defaultNearCache in 24488 ms
```

**Comment by Donnerbart** [comment]
The Near Cache tests have been improved a lot in 3.11 (current master), but I cannot easily backport the fixes, since a bunch of them relies on the new invalidation Near Cache stats. I would recommend that we discuss this in Brno, where I can show you easier what would need to be backported and if we want to do this :)

**Comment by Donnerbart** [comment]
We discussed not to backport any fixed, since they require production code changes as well. We are very sure that it's a test failure only, so future failures will be ignored or suppressed.
