### ISSUE TITLE
Intermittently failing SetItemListenerOnReconnectTest

### ISSUE THREAD

**Issue by kwart** [hazelcast/hazelcast#12917]
The `com.hazelcast.client.listeners.SetItemListenerOnReconnectTest.testListenersWhenClientDisconnectedOperationRuns_whenOwnerConnectionRemoved` is failing intermittently in PR builder:
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/15239/

**Stacktrace**
```
com.hazelcast.core.OperationTimeoutException: ClientInvocation{clientMessage = ClientMessage{length=101, correlationId=928, operation=Client.createProxy, messageType=5, partitionId=-1, isComplete=true, isRetryable=false, isEvent=false, writeOffset=0}, objectName = hz:impl:setService, target = address [127.0.0.1]:5020, sendConnection = null} timed out because exception occurred after client invocation timeout 120000 ms. Current time: 2018-04-19 07:11:38.760. Start time: 2018-04-19 07:09:37.879. Total elapsed time: 120881 ms. 
	at com.hazelcast.client.spi.impl.ClientInvocation.newOperationTimeoutException(ClientInvocation.java:333)
	at com.hazelcast.client.spi.impl.ClientInvocation.notifyException(ClientInvocation.java:230)
	at com.hazelcast.client.spi.impl.ClientInvocation.invokeOnSelection(ClientInvocation.java:172)
	at com.hazelcast.client.spi.impl.ClientInvocation.retry(ClientInvocation.java:190)
	at com.hazelcast.client.spi.impl.ClientInvocation.run(ClientInvocation.java:178)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:96)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:33)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:162)
	at com.hazelcast.client.spi.ProxyManager.initialize(ProxyManager.java:436)
	at com.hazelcast.client.spi.ProxyManager.initializeWithRetry(ProxyManager.java:395)
	at com.hazelcast.client.spi.ProxyManager.getOrCreateProxy(ProxyManager.java:316)
	at com.hazelcast.client.impl.HazelcastClientInstanceImpl.getDistributedObject(HazelcastClientInstanceImpl.java:707)
	at com.hazelcast.client.impl.HazelcastClientInstanceImpl.getSet(HazelcastClientInstanceImpl.java:501)
	at com.hazelcast.client.impl.HazelcastClientProxy.getSet(HazelcastClientProxy.java:110)
	at com.hazelcast.client.listeners.SetItemListenerOnReconnectTest.addListener(SetItemListenerOnReconnectTest.java:42)
Caused by: java.io.IOException: Owner connection is not available!
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.checkAllowed(ClientConnectionManagerImpl.java:398)
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.getConnection(ClientConnectionManagerImpl.java:361)
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.getOrTriggerConnect(ClientConnectionManagerImpl.java:352)
	at com.hazelcast.client.spi.impl.SmartClientInvocationService.getOrTriggerConnect(SmartClientInvocationService.java:73)
	at com.hazelcast.client.spi.impl.SmartClientInvocationService.invokeOnTarget(SmartClientInvocationService.java:68)
	at com.hazelcast.client.spi.impl.ClientInvocation.invokeOnSelection(ClientInvocation.java:164)
	at com.hazelcast.client.spi.impl.ClientInvocation.retry(ClientInvocation.java:190)
	at com.hazelcast.client.spi.impl.ClientInvocation.run(ClientInvocation.java:178)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
```

**Comment by sancar** [comment]
fixed by https://github.com/hazelcast/hazelcast/pull/12966

**Comment by Holmistr** [comment]
Fixed by: https://github.com/hazelcast/hazelcast/pull/12966
