### ISSUE TITLE
ClientCacheConfigTest.cacheManagerByInstanceNameTest & cacheManagerByLocationClasspathTest failure

### ISSUE THREAD

**Issue by Holmistr** [hazelcast/hazelcast#12938]
*maintenance*

Failed in Sonar build: https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-sonar/5/testReport/junit/com.hazelcast.client.cache/ClientCacheConfigTest/cacheManagerByInstanceNameTest/

Stacktrace:
```
java.lang.AssertionError: expected:<0> but was:<2>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.client.cache.ClientCacheConfigTest.cacheManagerByInstanceNameTest(ClientCacheConfigTest.java:128)
```

Standard output:
```
00:07:41,695  WARN |createSingleCache_whenMemberDown_throwsOperationTimeoutException| - [ClientConnection] hz.client_1400.internal-3 - hz.client_1400 [dev] [3.10.1-SNAPSHOT] ClientConnection{alive=false, connectionId=3, channel=NioChannel{/127.0.0.1:40244->/127.0.0.1:5701}, remoteEndpoint=null, lastReadTime=2018-04-22 00:07:41.695, lastWriteTime=2018-04-22 00:07:41.694, closedTime=2018-04-22 00:07:41.695, lastHeartbeatRequested=never, lastHeartbeatReceived=never, connected server version=null} closed. Reason: com.hazelcast.client.AuthenticationException[Invalid credentials! Principal: ClientPrincipal{uuid='cd8b6061-545c-4fac-a824-e816a5c07917', ownerUuid='2a8c0db7-7595-41e6-844b-ddfbd67d9642'}]
com.hazelcast.client.AuthenticationException: Invalid credentials! Principal: ClientPrincipal{uuid='cd8b6061-545c-4fac-a824-e816a5c07917', ownerUuid='2a8c0db7-7595-41e6-844b-ddfbd67d9642'}
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl$AuthCallback.onResponse(ClientConnectionManagerImpl.java:1004) [classes/:?]
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl$AuthCallback.onResponse(ClientConnectionManagerImpl.java:959) [classes/:?]
	at com.hazelcast.client.spi.impl.ClientInvocationFuture$InternalDelegatingExecutionCallback.onResponse(ClientInvocationFuture.java:130) [classes/:?]
	at com.hazelcast.client.spi.impl.ClientInvocationFuture$InternalDelegatingExecutionCallback.onResponse(ClientInvocationFuture.java:118) [classes/:?]
	at com.hazelcast.client.spi.impl.ClientInvocationFuture$InternalDelegatingExecutionCallback.onResponse(ClientInvocationFuture.java:130) [classes/:?]
	at com.hazelcast.client.spi.impl.ClientInvocationFuture$InternalDelegatingExecutionCallback.onResponse(ClientInvocationFuture.java:118) [classes/:?]
	at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run(AbstractInvocationFuture.java:255) [classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_171]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64) [classes/:?]
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80) [classes/:?]
```

**Comment by Holmistr** [comment]
*maintenance*

Another failure of ClientCacheConfigTest.cacheManagerByLocationClasspathTest: https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-sonar/8/testReport/com.hazelcast.client.cache/ClientCacheConfigTest/cacheManagerByLocationClasspathTest/

Stacktrace:
```
java.lang.AssertionError: expected:<0> but was:<2>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.client.cache.ClientCacheConfigTest.cacheManagerByLocationClasspathTest(ClientCacheConfigTest.java:87)
```

**Comment by Holmistr** [comment]
*maintenance* (revision 55f25979f94a9e4c965939504a6611802b70d53c)

ClientCacheConfigTest.cacheManagerByLocationFileTest failed again on Sonar build: https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-sonar/9/testReport/junit/com.hazelcast.client.cache/ClientCacheConfigTest/cacheManagerByLocationFileTest/

Stacktrace:
```
java.lang.AssertionError: expected:<0> but was:<2>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.client.cache.ClientCacheConfigTest.cacheManagerByLocationFileTest(ClientCacheConfigTest.java:105)
```

Standard output:
```
00:10:09,815  WARN |cacheManagerByLocationFileTest| - [AuthenticationMessageTask] hz._hzInstance_1751_cluster2.priority-generic-operation.thread-0 - [127.0.0.1]:5702 [cluster2] [3.10.1-SNAPSHOT] Received auth from Connection[id=1, /127.0.0.1:5702->/127.0.0.1:39593, endpoint=null, alive=true, type=NONE] with principal ClientPrincipal{uuid='bad84359-7d10-4a0b-bf30-7c31fb163493', ownerUuid='58fd1911-3b1b-4f9c-91fe-3ca5c60f71b4'}, authentication failed
00:10:09,815  WARN |createSingleCache_whenMemberDown_throwsOperationTimeoutException| - [ClientConnection] hz.client_1395.internal-3 - hz.client_1395 [dev] [3.10.1-SNAPSHOT] ClientConnection{alive=false, connectionId=12, channel=NioChannel{/127.0.0.1:39593->/127.0.0.1:5702}, remoteEndpoint=null, lastReadTime=2018-04-26 00:10:09.815, lastWriteTime=2018-04-26 00:10:09.814, closedTime=2018-04-26 00:10:09.815, lastHeartbeatRequested=never, lastHeartbeatReceived=never, connected server version=null} closed. Reason: com.hazelcast.client.AuthenticationException[Invalid credentials! Principal: ClientPrincipal{uuid='bad84359-7d10-4a0b-bf30-7c31fb163493', ownerUuid='58fd1911-3b1b-4f9c-91fe-3ca5c60f71b4'}]
com.hazelcast.client.AuthenticationException: Invalid credentials! Principal: ClientPrincipal{uuid='bad84359-7d10-4a0b-bf30-7c31fb163493', ownerUuid='58fd1911-3b1b-4f9c-91fe-3ca5c60f71b4'}
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl$AuthCallback.onResponse(ClientConnectionManagerImpl.java:1004) [classes/:?]
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl$AuthCallback.onResponse(ClientConnectionManagerImpl.java:959) [classes/:?]
	at com.hazelcast.client.spi.impl.ClientInvocationFuture$InternalDelegatingExecutionCallback.onResponse(ClientInvocationFuture.java:130) [classes/:?]
	at com.hazelcast.client.spi.impl.ClientInvocationFuture$InternalDelegatingExecutionCallback.onResponse(ClientInvocationFuture.java:118) [classes/:?]
	at com.hazelcast.client.spi.impl.ClientInvocationFuture$InternalDelegatingExecutionCallback.onResponse(ClientInvocationFuture.java:130) [classes/:?]
	at com.hazelcast.client.spi.impl.ClientInvocationFuture$InternalDelegatingExecutionCallback.onResponse(ClientInvocationFuture.java:118) [classes/:?]
	at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run(AbstractInvocationFuture.java:255) [classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_171]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64) [classes/:?]
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80) [classes/:?]
```

**Comment by Holmistr** [comment]
*maintenance* (commit cd9822273aff3b9c523b5107079334830e16cebd)

Failed on Sonar build: https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-sonar/11/testReport/com.hazelcast.client.cache/ClientCacheConfigTest/cacheManagerByInstanceNameTest/

Stacktrace:
```
java.lang.AssertionError: expected:<0> but was:<2>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.client.cache.ClientCacheConfigTest.cacheManagerByInstanceNameTest(ClientCacheConfigTest.java:128)
```

Maybe some clue from standard output:
```
00:07:11,470  INFO |createSingleCache_whenMemberDown_throwsOperationTimeoutException| - [ClientConnectionManager] hz.client_1392.cluster- - hz.client_1392 [dev] [3.10.1-SNAPSHOT] Trying to connect to [127.0.0.1]:5702 as owner member
00:07:11,470  WARN |createSingleCache_whenMemberBounce| - [ClientConnectionManager] hz.client_1399.cluster- - hz.client_1399 [dev] [3.10.1-SNAPSHOT] Could not connect to cluster, shutting down the client. Giving up on retrying to connect to cluster since client is shutdown.
00:07:11,471  INFO |cacheManagerByInstanceNameTest| - [TcpIpAcceptor] hz._hzInstance_1751_cluster2.IO.thread-Acceptor - [127.0.0.1]:5702 [cluster2] [3.10.1-SNAPSHOT] Accepting socket connection from /127.0.0.1:40297
00:07:11,471  INFO |cacheManagerByInstanceNameTest| - [TcpIpConnectionManager] hz._hzInstance_1751_cluster2.IO.thread-Acceptor - [127.0.0.1]:5702 [cluster2] [3.10.1-SNAPSHOT] Established socket connection between /127.0.0.1:5702 and /127.0.0.1:40297
00:07:11,472  INFO |cacheManagerByInstanceNameTest| - [LifecycleService] main - hz.client_1399 [dev] [3.10.1-SNAPSHOT] HazelcastClient 3.10.1-SNAPSHOT (20180427 - cd98222) is SHUTDOWN
00:07:11,472  INFO |cacheManagerByInstanceNameTest| - [LifecycleService] main - hz.client_1392 [dev] [3.10.1-SNAPSHOT] HazelcastClient 3.10.1-SNAPSHOT (20180427 - cd98222) is SHUTTING_DOWN
00:07:11,473  WARN |cacheManagerByInstanceNameTest| - [AuthenticationMessageTask] hz._hzInstance_1751_cluster2.priority-generic-operation.thread-0 - [127.0.0.1]:5702 [cluster2] [3.10.1-SNAPSHOT] Received auth from Connection[id=1, /127.0.0.1:5702->/127.0.0.1:40297, endpoint=null, alive=true, type=NONE] with principal ClientPrincipal{uuid='125ecdf6-99a3-4809-94bf-47776bb2dc6c', ownerUuid='f2d57b86-8436-42aa-ae55-6f87b612d792'}, authentication failed
00:07:11,473  INFO |cacheManagerByInstanceNameTest| - [TcpIpConnection] hz._hzInstance_1751_cluster2.IO.thread-in-0 - [127.0.0.1]:5702 [cluster2] [3.10.1-SNAPSHOT] Connection[id=1, /127.0.0.1:5702->/127.0.0.1:40297, endpoint=null, alive=false, type=NONE] closed. Reason: Connection closed by the other side
00:07:11,474  WARN |createSingleCache_whenMemberDown_throwsOperationTimeoutException| - [ClientConnectionManager] hz.client_1392.cluster- - hz.client_1392 [dev] [3.10.1-SNAPSHOT] Exception during initial connection to [127.0.0.1]:5702, exception com.hazelcast.client.AuthenticationException: Invalid credentials! Principal: ClientPrincipal{uuid='125ecdf6-99a3-4809-94bf-47776bb2dc6c', ownerUuid='f2d57b86-8436-42aa-ae55-6f87b612d792'}
00:07:11,474  WARN |createSingleCache_whenMemberDown_throwsOperationTimeoutException| - [ClientConnectionManager] hz.client_1392.cluster- - hz.client_1392 [dev] [3.10.1-SNAPSHOT] Could not connect to cluster, shutting down the client. Giving up on retrying to connect to cluster since client is shutdown.
00:07:11,475  INFO |cacheManagerByInstanceNameTest| - [LifecycleService] main - hz.client_1392 [dev] [3.10.1-SNAPSHOT] HazelcastClient 3.10.1-SNAPSHOT (20180427 - cd98222) is SHUTDOWN
```
