### ISSUE TITLE
Client's ReliableTopic message listener is terminated when cluster goes down for longer than hazelcast.client.invocation.timeout.seconds

### ISSUE THREAD

**Issue by wneild** [hazelcast/hazelcast#12948]
The following exception is thrown when a client registers a message listener against a reliable topic, the cluster is shutdown and time elapses that is greater than the value of `hazelcast.client.invocation.timeout.seconds`:

```
WARNING: hz.client_0 [dev] [3.9.3] Terminating MessageListener com.wneild.hazelcast.ListenerIntegrationTest$$Lambda$3/1161382705@124a67e6 on topic: topic. Reason: Unhandled exception, message: ClientInvocation{clientMessage = ClientMessage{length=55, correlationId=27, operation=Ringbuffer.readMany, messageType=190a, partitionId=85, isComplete=true, isRetryable=true, isEvent=false, writeOffset=0}, objectName = _hz_rb_topic, target = partition 85, sendConnection = ClientConnection{alive=false, connectionId=1, channel=NioChannel{0.0.0.0/0.0.0.0:63848->/127.0.0.1:5701}, remoteEndpoint=[10.128.42.209]:5701, lastReadTime=2018-04-23 20:08:05.647, lastWriteTime=2018-04-23 20:08:05.649, closedTime=2018-04-23 20:08:05.647, lastHeartbeatRequested=never, lastHeartbeatReceived=never, connected server version=3.9.3}} timed out because exception occurred after client invocation timeout 1000 ms. Current time: 2018-04-23 20:08:06.750. Start time: 2018-04-23 20:08:05.531. Total elapsed time: 1220 ms. 
com.hazelcast.core.OperationTimeoutException: ClientInvocation{clientMessage = ClientMessage{length=55, correlationId=27, operation=Ringbuffer.readMany, messageType=190a, partitionId=85, isComplete=true, isRetryable=true, isEvent=false, writeOffset=0}, objectName = _hz_rb_topic, target = partition 85, sendConnection = ClientConnection{alive=false, connectionId=1, channel=NioChannel{0.0.0.0/0.0.0.0:63848->/127.0.0.1:5701}, remoteEndpoint=[10.128.42.209]:5701, lastReadTime=2018-04-23 20:08:05.647, lastWriteTime=2018-04-23 20:08:05.649, closedTime=2018-04-23 20:08:05.647, lastHeartbeatRequested=never, lastHeartbeatReceived=never, connected server version=3.9.3}} timed out because exception occurred after client invocation timeout 1000 ms. Current time: 2018-04-23 20:08:06.750. Start time: 2018-04-23 20:08:05.531. Total elapsed time: 1220 ms. 
	at com.hazelcast.client.spi.impl.ClientInvocation.newOperationTimeoutException(ClientInvocation.java:309)
	at com.hazelcast.client.spi.impl.ClientInvocation.notifyException(ClientInvocation.java:216)
	at com.hazelcast.client.spi.impl.ClientInvocation.invokeOnSelection(ClientInvocation.java:160)
	at com.hazelcast.client.spi.impl.ClientInvocation.retry(ClientInvocation.java:178)
	at com.hazelcast.client.spi.impl.ClientInvocation.run(ClientInvocation.java:166)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at com.hazelcast.util.executor.LoggingScheduledExecutor$LoggingDelegatingFuture.run(LoggingScheduledExecutor.java:160)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
Caused by: java.io.IOException: Owner connection is not available!
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.getConnection(ClientConnectionManagerImpl.java:357)
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.getOrTriggerConnect(ClientConnectionManagerImpl.java:344)
	at com.hazelcast.client.spi.impl.SmartClientInvocationService.getOrTriggerConnect(SmartClientInvocationService.java:73)
	at com.hazelcast.client.spi.impl.SmartClientInvocationService.invokeOnPartitionOwner(SmartClientInvocationService.java:48)
	at com.hazelcast.client.spi.impl.ClientInvocation.invokeOnSelection(ClientInvocation.java:150)
	... 12 more
```

Here is a failing test that demonstrates this behaviour:

```
@Test
    public void shouldReestablishListenerOnClusterRestart() throws InterruptedException {
        HazelcastInstance hzMember = Hazelcast.newHazelcastInstance();
        ClientConfig clientConfig = new ClientConfig();
        clientConfig.setProperty("hazelcast.client.invocation.timeout.seconds", "1");
        HazelcastInstance hzClient = HazelcastClient.newHazelcastClient(clientConfig);
        AtomicReference<String> value = new AtomicReference<>();

        hzClient.<String>getReliableTopic(TOPIC_NAME).addMessageListener(message -> value.set(message.getMessageObject()));

        hzMember.getReliableTopic(TOPIC_NAME).publish(TOPIC_MESSAGE_ONE);
        Thread.sleep(100L);
        assertEquals(TOPIC_MESSAGE_ONE, value.get());
        hzMember.shutdown();
        Thread.sleep(1000L); // if we wait for hazelcast.client.invocation.timeout.seconds then the listener doesn't work any more
        hzMember = Hazelcast.newHazelcastInstance();
        hzMember.getReliableTopic(TOPIC_NAME).publish(TOPIC_MESSAGE_TWO);
        Thread.sleep(100L);
        assertEquals(TOPIC_MESSAGE_TWO, value.get());
    }
```

My expectation would be that the message listener is re-established when the client's connection to the cluster is re-established, rather than being terminated.

This is using Hazelcast 3.9.3

**Comment by gokhanoner** [comment]
@wneild Why are you expecting to see `TOPIC_MESSAGE_TWO`. Since `TOPIC_MESSAGE_ONE` is not delivered, it'll be retired. I did 2 changes to your test & it passed:


```
    @Test
    public void shouldReestablishListenerOnClusterRestart() throws InterruptedException {
        HazelcastInstance hzMember = Hazelcast.newHazelcastInstance();
        ClientConfig clientConfig = new ClientConfig();
        clientConfig.setProperty("hazelcast.client.invocation.timeout.seconds", "1");
        //Necessary to prevent client shutdown due connection attempt limit
        clientConfig.getNetworkConfig().setConnectionAttemptLimit(0);
        HazelcastInstance hzClient = HazelcastClient.newHazelcastClient(clientConfig);
        AtomicReference<String> value = new AtomicReference<>();

        hzClient.<String>getReliableTopic(TOPIC_NAME).addMessageListener(message -> value.set(message.getMessageObject()));

        hzMember.getReliableTopic(TOPIC_NAME).publish(TOPIC_MESSAGE_ONE);
        Thread.sleep(100L);
        assertEquals(TOPIC_MESSAGE_ONE, value.get());
        hzMember.shutdown();
        Thread.sleep(3000L); // if we wait for hazelcast.client.invocation.timeout.seconds then the listener doesn't work any more
        hzMember = Hazelcast.newHazelcastInstance();
        hzMember.getReliableTopic(TOPIC_NAME).publish(TOPIC_MESSAGE_TWO);
        Thread.sleep(100L);
        assertEquals(TOPIC_MESSAGE_ONE, value.get());
    }
```

Can you please check & confirm?

**Comment by gokhanoner** [comment]
@wneild my bad, I didn't see `AtomicReference` usage. Yes, it seems your listener deregistered. Increasing `hazelcast.client.invocation.timeout.seconds` can help but it also affects all client related invocations so I suggest you use it carefully.

**Comment by sancar** [comment]
I think test is not really suitable to show the problem. Even if we increase the timeout test will not pass. 
Because, in the test, all cluster shutdown. First published item is already lost. When cluster comes back, client listener will try to fetch a non-existing item, and it will wait for it to become available. 
Test will not pass. 

` hazelcast.client.invocation.timeout.seconds`  effects all invocations. Idea behind it was to provide a way to invocations to give up at some point. It seems that this logic is contradicts with usage reliable topic listener . Because we don't ever want it to give up on listener because of a timeout. 

So a fix could be to handle OperationTimeoutException in ClientReliableTopicProxy.MessageRunner.handleFailure and just send a new request to make it continue to wait. 

Similar problem could be on member side again with OperationTimeoutException. Adding "core" label to get core teams opinion. 
@mmedenjak What do you think ?

**Comment by wneild** [comment]
@sancar Thanks for feeding back on the test. I have validated for myself that increasing `hazelcast.client.invocation.timeout.seconds` to longer than the time the cluster is down indeed doesn't enable the test to pass. Apologies, this is down to not enough time given for the client to reconnect. Otherwise, adding a reasonable wait between starting the member back up and publishing message two enables the test to pass.

**Comment by sancar** [comment]
@wneild Sorry to but I think we are not still in same page. 
It should not matter how long you wait for client to reconnect test should not able to pass. 
May be I am mistaken. Can you share the version of the test that passes ?

My thinking as follows:
It is related backend implementation of reliable topic. It uses a ring buffer internally. When first member is down, ring buffer is completely lost.
When second member, comes back up, we store the item as the first item of the ringbuffer. 

Since the client is not aware of that, it tries to read the response from second field. And it will never arrive. 

This problem described here and not resolved yet. 
https://github.com/hazelcast/hazelcast/issues/11857#issuecomment-366949893

**Comment by wneild** [comment]
@sancar My bad, I understand what you were saying now. I confused myself by removing the initial assert that verified the message listener was working, then increasing the timeout worked.

As you say, that existing issue makes the test I provided invalid. Without the verification the message listener is initially working this test should pass:

```
@Test
    public void shouldReestablishListenerOnClusterRestart() throws InterruptedException {
        HazelcastInstance hzMember = Hazelcast.newHazelcastInstance();
        ClientConfig clientConfig = new ClientConfig();
        clientConfig.setProperty("hazelcast.client.invocation.timeout.seconds", "2");
        HazelcastInstance hzClient = HazelcastClient.newHazelcastClient(clientConfig);
        AtomicReference<String> value = new AtomicReference<>();

        hzClient.<String>getReliableTopic(TOPIC_NAME).addMessageListener(message -> value.set(message.getMessageObject()));

        hzMember.shutdown();
        Thread.sleep(1000L); // if we wait for hazelcast.client.invocation.timeout.seconds then the listener doesn't work any more
        hzMember = Hazelcast.newHazelcastInstance();
        Thread.sleep(5000L); // Wait for client to reconnect to cluster
        hzMember.getReliableTopic(TOPIC_NAME).publish(TOPIC_MESSAGE_ONE);
        Thread.sleep(1000L); // ensure message has time to be delivered to message listener
        assertEquals(TOPIC_MESSAGE_ONE, value.get());
    }
```

**Comment by sancar** [comment]
I think client should handle OperationTimeout and to be able to continue when a member opened back. A test that should pass looks like following(basically added is tolerant to listener to test in https://github.com/hazelcast/hazelcast/issues/12948#issuecomment-384233921 shared by @wneild ) 

Currently this listener terminated with OperationTimeout and does not continue when cluster comes back. 
```
  @Test
    public void shouldReestablishListenerOnClusterRestart() throws InterruptedException {
        HazelcastInstance member = hazelcastFactory.newHazelcastInstance();
        ClientConfig clientConfig = new ClientConfig();
        clientConfig.getNetworkConfig().setConnectionAttemptLimit(100);
        int invocationTimeoutSeconds = 2;
        clientConfig.setProperty(ClientProperty.INVOCATION_TIMEOUT_SECONDS.getName(), String.valueOf(invocationTimeoutSeconds));
        HazelcastInstance client = hazelcastFactory.newHazelcastClient(clientConfig);

        final CountDownLatch messageArrived = new CountDownLatch(1);
        String topicName = "topic";
        client.<String>getReliableTopic(topicName).addMessageListener(new DurableSubscriptionTest.DurableMessageListener<String>() {
            @Override
            public void onMessage(Message<String> message) {
                messageArrived.countDown();
            }

            @Override
            public boolean isLossTolerant() {
                return true;
            }
        });

        member.shutdown();
        // wait for the topic operation to timeout
        Thread.sleep(TimeUnit.SECONDS.toMillis(invocationTimeoutSeconds));

        member = hazelcastFactory.newHazelcastInstance();
        member.getReliableTopic(topicName).publish("message");
        assertOpenEventually(messageArrived);
    }

```

I've tried to test similar behaviour on nodes no luck so far, because I could not find a way to trigger OperationTimeout with a unit-test.  I have ended up with following test. I was expecting to get OperationTimeoutException but, listener is terminated with  NoDataMemberInClusterException. And, event though cluster comes back listener does not work. Looks like similar behaviour. 

```
 @Test
    public void shouldReestablishListenerOnClusterRestart() throws InterruptedException {
        long callTimeoutMillis = 2000;
        Config config = new Config();

        config.getRingbufferConfig("default").setBackupCount(0).setAsyncBackupCount(0);
        TestHazelcastInstanceFactory factory = createHazelcastInstanceFactory(3);
        HazelcastInstance topicOwningMember = factory.newHazelcastInstance(config);


        Config liteMemberConfig = new Config();
        liteMemberConfig.setProperty(GroupProperty.OPERATION_CALL_TIMEOUT_MILLIS.getName(), String.valueOf(callTimeoutMillis));
        liteMemberConfig.setLiteMember(true);
        HazelcastInstance liteMember = factory.newHazelcastInstance(liteMemberConfig);

        warmUpPartitions(topicOwningMember, liteMember);

        String topicName = generateKeyOwnedBy(topicOwningMember);

        final CountDownLatch messageArrived = new CountDownLatch(1);
        liteMember.<String>getReliableTopic(topicName).addMessageListener(new DurableSubscriptionTest.DurableMessageListener<String>() {
            @Override
            public void onMessage(Message<String> message) {
                messageArrived.countDown();
            }

            @Override
            public boolean isLossTolerant() {
                return true;
            }
        });

        topicOwningMember.shutdown();

        // wait for the topic operation to timeout
        Thread.sleep(callTimeoutMillis * 3);

        factory.newHazelcastInstance(config);

        liteMember.getReliableTopic(topicName).publish("message");
        assertOpenEventually(messageArrived);
    }
```

Question is, should we handle these kind of exceptions to make listeners continue ? 
(OperationTimeoutException  , NoDataMemberInClusterException)

I want to get core team's opinion to continue because behaviour should be consistent.
