### ISSUE TITLE
QueueItemListenerOnReconnectTest.testListenersNonSmartRouting failure

### ISSUE THREAD

**Issue by taburet** [hazelcast/hazelcast#12954]
Failed on PR builder:

```
java.lang.AssertionError: Member [127.0.0.1]:5011 - 7ae7914f-7b73-4b74-a098-c0c7c55bb5f5 this expected:<1> but was:<2>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest$8.run(AbstractListenersOnReconnectTest.java:484)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1244)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1261)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest.validateRegistrationsOnMembers(AbstractListenersOnReconnectTest.java:475)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest.validateRegistrationsAndListenerFunctionality(AbstractListenersOnReconnectTest.java:468)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest.testListenersTerminateOwnerNode(AbstractListenersOnReconnectTest.java:455)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest.testListenersNonSmartRouting(AbstractListenersOnReconnectTest.java:425)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/15317/testReport/junit/com.hazelcast.client.listeners/QueueItemListenerOnReconnectTest/testListenersNonSmartRouting/

**Comment by Holmistr** [comment]
Pretty sure that this will be related to https://github.com/hazelcast/hazelcast/issues/8254
