### ISSUE TITLE
QueueTestsFrom2X.issue99TestQueueTakeAndDuringRollback failure

### ISSUE THREAD

**Issue by Holmistr** [hazelcast/hazelcast#12965]
*master*

Failed on Sonar build: https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-sonar/lastCompletedBuild/testReport/com.hazelcast.collection.impl.queue/QueueTestsFrom2X/issue99TestQueueTakeAndDuringRollback/

Stacktrace:
```
java.lang.AssertionError: Queue take failed after rollback!
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at com.hazelcast.collection.impl.queue.QueueTestsFrom2X.issue99TestQueueTakeAndDuringRollback(QueueTestsFrom2X.java:503)
```

Standard output:
```
Hiccups measured while running test 'issue99TestQueueTakeAndDuringRollback(com.hazelcast.collection.impl.queue.QueueTestsFrom2X):'
22:58:15, accumulated pauses: 42 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:58:20, accumulated pauses: 41 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:58:25, accumulated pauses: 41 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:58:30, accumulated pauses: 39 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:58:35, accumulated pauses: 39 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:58:40, accumulated pauses: 42 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:58:45, accumulated pauses: 41 ms, max pause: 1 ms, pauses over 1000 ms: 0
22:58:50, accumulated pauses: 37 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:58:55, accumulated pauses: 42 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:59:00, accumulated pauses: 48 ms, max pause: 1 ms, pauses over 1000 ms: 0
22:59:05, accumulated pauses: 50 ms, max pause: 1 ms, pauses over 1000 ms: 0
22:59:10, accumulated pauses: 50 ms, max pause: 10 ms, pauses over 1000 ms: 0
22:59:15, accumulated pauses: 39 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:59:20, accumulated pauses: 41 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:59:25, accumulated pauses: 40 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:59:30, accumulated pauses: 40 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:59:35, accumulated pauses: 39 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:59:40, accumulated pauses: 37 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:59:45, accumulated pauses: 34 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:59:50, accumulated pauses: 41 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:59:55, accumulated pauses: 41 ms, max pause: 0 ms, pauses over 1000 ms: 0
23:00:00, accumulated pauses: 38 ms, max pause: 0 ms, pauses over 1000 ms: 0
23:00:05, accumulated pauses: 47 ms, max pause: 0 ms, pauses over 1000 ms: 0
23:00:10, accumulated pauses: 44 ms, max pause: 0 ms, pauses over 1000 ms: 0
23:00:15, accumulated pauses: 437 ms, max pause: 401 ms, pauses over 1000 ms: 0
```

**Comment by Holmistr** [comment]
*maintenance* (commit 55f25979f94a9e4c965939504a6611802b70d53c)

Failure on Sonar build: https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-sonar/9/

Stacktrace:
```
java.lang.AssertionError: Queue take failed after rollback!
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at com.hazelcast.collection.impl.queue.QueueTestsFrom2X.issue99TestQueueTakeAndDuringRollback(QueueTestsFrom2X.java:503)
```

Standard error:
```
com.hazelcast.transaction.TransactionException: Transaction is timed-out!
	at com.hazelcast.transaction.impl.TransactionImpl.checkTimeout(TransactionImpl.java:308)
	at com.hazelcast.transaction.impl.TransactionImpl.commit(TransactionImpl.java:288)
	at com.hazelcast.transaction.impl.TransactionContextImpl.commitTransaction(TransactionContextImpl.java:74)
	at com.hazelcast.collection.impl.queue.QueueTestsFrom2X$7.run(QueueTestsFrom2X.java:489)
```

Standard output:
```
Hiccups measured while running test 'issue99TestQueueTakeAndDuringRollback(com.hazelcast.collection.impl.queue.QueueTestsFrom2X):'
22:41:25, accumulated pauses: 33 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:41:30, accumulated pauses: 34 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:41:35, accumulated pauses: 31 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:41:40, accumulated pauses: 33 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:41:45, accumulated pauses: 34 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:41:50, accumulated pauses: 33 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:41:55, accumulated pauses: 36 ms, max pause: 2 ms, pauses over 1000 ms: 0
22:42:00, accumulated pauses: 32 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:42:05, accumulated pauses: 30 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:42:10, accumulated pauses: 32 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:42:15, accumulated pauses: 35 ms, max pause: 2 ms, pauses over 1000 ms: 0
22:42:20, accumulated pauses: 31 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:42:25, accumulated pauses: 31 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:42:30, accumulated pauses: 33 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:42:35, accumulated pauses: 31 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:42:40, accumulated pauses: 31 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:42:45, accumulated pauses: 34 ms, max pause: 2 ms, pauses over 1000 ms: 0
22:42:50, accumulated pauses: 35 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:42:55, accumulated pauses: 31 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:43:00, accumulated pauses: 31 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:43:05, accumulated pauses: 34 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:43:10, accumulated pauses: 34 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:43:15, accumulated pauses: 31 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:43:20, accumulated pauses: 31 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:43:25, accumulated pauses: 396 ms, max pause: 387 ms, pauses over 1000 ms: 0
```
