### ISSUE TITLE
Cannot override cache's CacheManager - after restart of remote Hazelcast

### ISSUE THREAD

**Issue by exmortal** [hazelcast/hazelcast#12975]
Hi everyone,

I faced with `Cannot override cache's CacheManager` exception when I tried to recreate a cache instance after I restarted remote Hazelcast. Hazelcast client successfully reestablished connection, but... all cache instances already using in application are inactive now. Any attempts to touch it will throw:
```
com.hazelcast.cache.CacheNotExistsException: Cache /hz/cache1 is already destroyed or not created yet...
````
To avoid that I tried to recreate each cache instance using new cache manager, because previous was closed due lost connection. First attempt to create a cache fails with:
```
java.lang.IllegalStateException: Cannot overwrite a Cache's CacheManager.
	at com.hazelcast.client.cache.impl.AbstractClientInternalCacheProxy.setCacheManager(AbstractClientInternalCacheProxy.java:173) ~[hazelcast-client-3.9.3.jar:3.9.3]
	at com.hazelcast.client.cache.impl.ClientCacheProxy.setCacheManager(ClientCacheProxy.java:94) ~[hazelcast-client-3.9.3.jar:3.9.3]
	at com.hazelcast.client.cache.impl.HazelcastClientCacheManager.createCacheProxy(HazelcastClientCacheManager.java:112) ~[hazelcast-client-3.9.3.jar:3.9.3]
	at com.hazelcast.cache.impl.AbstractHazelcastCacheManager.getCacheUnchecked(AbstractHazelcastCacheManager.java:243) ~[hazelcast-3.9.3.jar:3.9.3]
	at com.hazelcast.cache.impl.AbstractHazelcastCacheManager.getCache(AbstractHazelcastCacheManager.java:219) ~[hazelcast-3.9.3.jar:3.9.3]
	at com.hazelcast.cache.impl.AbstractHazelcastCacheManager.getCache(AbstractHazelcastCacheManager.java:67) ~[hazelcast-3.9.3.jar:3.9.3]
````

My application uses JCache API to create caches, like this:
```
CachingProvider provider = Caching.getCachingProvider();
CacheManager manager = provider.getCacheManager();

Cache<K, V> cache = manager.getCache(cacheName);
if (cache != null) {
    return cache;
}
      
return manager.createCache(cacheName, configuration);       
````

This error happened because of this PR https://github.com/hazelcast/hazelcast/pull/11076 
Any ideas how to invalidate all `Cache` instances on fly ? Or it's a bug ?

Thanks,
Vlad

**Comment by vbekiaris** [comment]
@exmortal thanks for the issue report. It is a bug and a fix PR (#13228) has been created.
