### ISSUE TITLE
java.lang.OutOfMemoryError: GC overhead limit exceeded expereince with Xms=4096

### ISSUE THREAD

**Issue by Pushpalanka** [hazelcast/hazelcast#13005]
Hi All,

Experiencing an OOM error with below error trace even under `Xms=4096` allocation.

```
### > TID: [-1234] [] [2018-04-27 03:02:06,923] DEBUG {org.wso2.carbon.user.core.common.RealmCache} -  created authorization cache : org.wso2.carbon.caching.impl.CacheImpl@922bea56
TID: [6934] [] [2018-04-27 03:02:06,923] @63c501a5-3971-48b2-8da6-20d10854fe42 [6934] [IS]DEBUG {org.wso2.carbon.user.core.common.DefaultRealmService} -  Error occurred while getting tenant user realm for tenant id : 6934
com.hazelcast.core.HazelcastInstanceNotActiveException: Hazelcast instance is not active!
        at com.hazelcast.spi.impl.proxyservice.impl.ProxyRegistry.getService(ProxyRegistry.java:64)
        at com.hazelcast.spi.impl.proxyservice.impl.ProxyRegistry.<init>(ProxyRegistry.java:52)
        at com.hazelcast.spi.impl.proxyservice.impl.ProxyServiceImpl$1.createNew(ProxyServiceImpl.java:74)
        at com.hazelcast.spi.impl.proxyservice.impl.ProxyServiceImpl$1.createNew(ProxyServiceImpl.java:72)
        at com.hazelcast.util.ConcurrencyUtil.getOrPutIfAbsent(ConcurrencyUtil.java:51)
        at com.hazelcast.spi.impl.proxyservice.impl.ProxyServiceImpl.getOrCreateRegistry(ProxyServiceImpl.java:110)
        at com.hazelcast.spi.impl.proxyservice.impl.ProxyServiceImpl.getDistributedObject(ProxyServiceImpl.java:118)
        at com.hazelcast.instance.HazelcastInstanceImpl.getDistributedObject(HazelcastInstanceImpl.java:390)
        at com.hazelcast.instance.HazelcastInstanceImpl.getMap(HazelcastInstanceImpl.java:192)
        at com.hazelcast.instance.HazelcastInstanceProxy.getMap(HazelcastInstanceProxy.java:75)
        at org.wso2.carbon.core.clustering.hazelcast.HazelcastDistributedMapProvider$DistMap.<init>(HazelcastDistributedMapProvider.java:67)
------------
TID: [-1234] [] [2018-04-27 03:02:06,928] ERROR {com.hazelcast.spi.impl.operationservice.impl.operations.PartitionIteratingOperation} -  [10.0.10.233]:4000 [wso2.carbon.domain] [3.5.4] GC overhead limit exceeded
java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.util.concurrent.locks.ReentrantLock.<init>(ReentrantLock.java:257)
        at com.hazelcast.util.ResponseQueueFactory$LockBasedResponseQueue.<init>(ResponseQueueFactory.java:49)
        at com.hazelcast.util.ResponseQueueFactory$LockBasedResponseQueue.<init>(ResponseQueueFactory.java:46)
        at com.hazelcast.util.ResponseQueueFactory.newResponseQueue(ResponseQueueFactory.java:43)
        at com.hazelcast.spi.impl.operationservice.impl.operations.PartitionIteratingOperation$ResponseQueue.<init>(PartitionIteratingOperation.java:114)
        at com.hazelcast.spi.impl.operationservice.impl.operations.PartitionIteratingOperation$ResponseQueue.<init>(PartitionIteratingOperation.java:113)
        at com.hazelcast.spi.impl.operationservice.impl.operations.PartitionIteratingOperation.executeOperations(PartitionIteratingOperation.java:84)
        at com.hazelcast.spi.impl.operationservice.impl.operations.PartitionIteratingOperation.run(PartitionIteratingOperation.java:60)
        at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:137)
        at com.hazelcast.spi.impl.operationexecutor.classic.ClassicOperationExecutor.runOnCallingThread(ClassicOperationExecutor.java:380)
        at com.hazelcast.spi.impl.operationexecutor.classic.ClassicOperationExecutor.runOnCallingThreadIfPossible(ClassicOperationExecutor.java:342)
        at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:247)
        at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:231)
        at com.hazelcast.spi.impl.operationservice.impl.Invocation.invokeInternal(Invocation.java:198)
        at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:168)
        at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:54)
        at com.hazelcast.spi.impl.operationservice.impl.InvokeOnPartitions.invokeOnAllPartitions(InvokeOnPartitions.java:83)
        at com.hazelcast.spi.impl.operationservice.impl.InvokeOnPartitions.invoke(InvokeOnPartitions.java:63)
        at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.invokeOnAllPartitions(OperationServiceImpl.java:326)
        at com.hazelcast.map.impl.proxy.MapProxySupport.clearInternal(MapProxySupport.java:914)
        at com.hazelcast.map.impl.proxy.MapProxyImpl.clearInternal(MapProxyImpl.java:71)
        at com.hazelcast.map.impl.proxy.MapProxyImpl.clear(MapProxyImpl.java:532)
        at org.wso2.carbon.core.clustering.hazelcast.HazelcastDistributedMapProvider$DistMap.clear(HazelcastDistributedMapProvider.java:173)
```

Appreciate you thoughts interpreting this issue.
When analysing the heapdump could notice this object is keeping more than 55% of memory 'com.hazelcast.spi.impl.eventservice.impl.EventServiceImpl'.

![snip20180424_10](https://user-images.githubusercontent.com/791850/39391631-a996a72e-4a5b-11e8-8ae1-7f5e92e28529.png)

**Comment by pveentjer** [comment]
Are you using nearcache or collection-listeners?

**Comment by Pushpalanka** [comment]
Thanks @mmedenjak and @pveentjer for the replies. I am trying to capture the information you requested. Thanks for the hints to look towards Hazelcast listeners, will check and get back.

**Comment by mmedenjak** [comment]
@Pushpalanka any updates? Have you managed to analyse the heap dump in more detail?

**Comment by mmedenjak** [comment]
@Pushpalanka any updates?

**Comment by Pushpalanka** [comment]
Sorry @mmedenjak  We recovered the issue via another path. Thank you very much for your attention. I will close this.

**Comment by RameshP96** [comment]
Hi Peter, Matko,

we are experiencing similar behavior (i.e. com.hazelcast.spi.impl.eventservice.impl.EventServiceImpl is occupying half of the heapMemory), we are using Hazelcast3.9.1 in our product.

Though our product has been using hazelcast, I am relatively new to hazelcast libraries. 
Initially product was using 2.6.9 and we upgraded it to 3.8.1 in May2017 and again to 3.9.1 in Dec2017.

Following is the information given by java profiler (Eclipse Mat tool) with hazelcast3.9.1
------------------------------------
One instance of "com.hazelcast.spi.impl.eventservice.impl.EventServiceImpl" loaded by "sun.misc.Launcher$AppClassLoader @ 0x1348e440" occupies 59,510,416 (40.10%) bytes. The memory is accumulated in one instance of "com.hazelcast.spi.impl.eventservice.impl.EventServiceSegment" loaded by "sun.misc.Launcher$AppClassLoader @ 0x1348e440".
------------------------------------

Matko, can you please help me know what i should check for in the "EventServiceSegment" object? I have attached screen-capture of this class from a java-profiler by name "EventServiceSegment.png", please let me know what i need to look at in this object? or if you need anymore from me

![eventservicesegment](https://user-images.githubusercontent.com/44966026/48542686-d4ca9080-e8e5-11e8-9c9b-ceb1a536c3cf.png)

![eventservicesegment-retainedby](https://user-images.githubusercontent.com/44966026/48543556-ced5af00-e8e7-11e8-9d6f-1654ba22df53.png)

Peter, we are using listeners in the product (use addMessageListener(...)/removeMessageListener(...)) on topics. I am not sure about near-cache, can you please help how to find it so that I can tell whether we are using.

Thanks and regards
Ramesh
