### ISSUE TITLE
ClientCacheNearCachePreloaderTest createStoreFile failures in LITTLE_ENDIAN

### ISSUE THREAD

**Issue by vbekiaris** [hazelcast/hazelcast#13029]
`testCreateStoreFile_withStringKey` and `testCreateStoreFile_withIntegerKey` fail when executed with `LITTLE_ENDIAN` byte order (eg override with `-Dhazelcast.serialization.byteOrder=LITTLE_ENDIAN`):

```
java.lang.AssertionError: Near Cache size didn't reach the desired value (10023 vs. 10022) (NearCacheStatsImpl{ownedEntryCount=10022, ownedEntryMemoryCost=1181510, creationTime=1525351370141, hits=0, misses=10023, ratio=0.0%, evictions=0, expirations=0, lastPersistenceTime=0, persistenceCount=0, lastPersistenceDuration=0, lastPersistenceWrittenBytes=0, lastPersistenceKeyCount=0, lastPersistenceFailure=''}) 

	at com.hazelcast.internal.nearcache.NearCacheTestUtils.assertNearCacheSize(NearCacheTestUtils.java:428)
	at com.hazelcast.internal.nearcache.AbstractNearCachePreloaderTest.populateNearCache(AbstractNearCachePreloaderTest.java:412)
	at com.hazelcast.internal.nearcache.AbstractNearCachePreloaderTest.createStoreFile(AbstractNearCachePreloaderTest.java:233)
	at com.hazelcast.internal.nearcache.AbstractNearCachePreloaderTest.testCreateStoreFile_withIntegerKey(AbstractNearCachePreloaderTest.java:217)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
```

A value that was supposed to exist in the cache, does not exist. Introducing an assertion for the cache's size immediately [after it is populated](https://github.com/hazelcast/hazelcast/blob/d19b15ce68ccfeff2ab62eacaed7cc6534fccfd6/hazelcast-client/src/test/java/com/hazelcast/client/cache/nearcache/ClientCacheNearCachePreloaderTest.java#L111) (eg `assertEquals(keyCount, dataAdapter.size());`) fails.

The particular tests are annotated as `SlowTest`s so they are not executed as part of the little-endian jenkins jobs.

**Comment by Holmistr** [comment]
```
The particular tests are annotated as SlowTests so they are not executed as part of the little-endian jenkins jobs.
```

@vbekiaris So should we execute it in the Jenkins job? Or maybe we should execute the whole testsuite in little endian?

**Comment by mdogan** [comment]
Is this an issue in NearCachePreloader implementation or in tests? Currently, when byte-order is `LITTLE_ENDIAN` those tests are ignored: https://github.com/hazelcast/hazelcast/pull/13030

**Comment by vbekiaris** [comment]
We assume `BIG_ENDIAN` in `testPreloadNearCache_withIntegerKeys` and `testPreloadNearCache_withStringKeys` which load keys from `src/test/resources/*.store` (which are serialized in those files in `BIG_ENDIAN`). The test failures reported in this issue relate to another pair of tests, `testCreateStoreFile_withIntegerKey` and `testCreateStoreFile_withStringKey`. That said, I have not been able to fail those tests after hundreds of executions in `LITTLE_ENDIAN` (neither in IntelliJ nor in maven), so closing this issue.

@Holmistr maybe it's worth also running the `nightly-build` profile in `LITTLE_ENDIAN` once in a while?

**Comment by Holmistr** [comment]
@vbekiaris Perhaps I should configure the little endian job to run the whole slow category. Good thinking!
