### ISSUE TITLE
MigrationCorrectnessTest.testPartitionData_whenBackupNodesStartedTerminated failure

### ISSUE THREAD

**Issue by Holmistr** [hazelcast/hazelcast#13061]
*maintenance* (commit c0844036d5081c12bbb1239ece1122da0ed7c7e2)

Failed on Zing JDK 7: https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.maintenance-ZingJDK7/lastCompletedBuild/testReport/com.hazelcast.internal.partition/MigrationCorrectnessTest/testPartitionData_whenBackupNodesStartedTerminated_backups_3_nodes_4_fragmented_false_/

Stacktrace:
```
java.lang.AssertionError: Replica version mismatch! Owner: [127.0.0.1]:15541, Backup: [127.0.0.1]:15540, Partition: Partition [83]{
	0:[127.0.0.1]:15541
	1:[127.0.0.1]:15540
	2:[127.0.0.1]:15545
	3:[127.0.0.1]:15547
	4:[127.0.0.1]:15548
	5:[127.0.0.1]:15546
}, Replica: 1 owner versions: [1, 1, 1, 0, 0, 0] backup versions: [0, 0, 0, 0, 0, 0] expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.internal.partition.PartitionCorrectnessTestSupport.assertPartitionVersionsAndBackupValues(PartitionCorrectnessTestSupport.java:284)
	at com.hazelcast.internal.partition.PartitionCorrectnessTestSupport.assertSizeAndData(PartitionCorrectnessTestSupport.java:220)
	at com.hazelcast.internal.partition.PartitionCorrectnessTestSupport.access$000(PartitionCorrectnessTestSupport.java:61)
	at com.hazelcast.internal.partition.PartitionCorrectnessTestSupport$AssertSizeAndDataTask.run(PartitionCorrectnessTestSupport.java:359)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1246)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1263)
	at com.hazelcast.internal.partition.PartitionCorrectnessTestSupport.assertSizeAndDataEventually(PartitionCorrectnessTestSupport.java:178)
	at com.hazelcast.internal.partition.PartitionCorrectnessTestSupport.assertSizeAndDataEventually(PartitionCorrectnessTestSupport.java:174)
	at com.hazelcast.internal.partition.AbstractMigrationCorrectnessTest.testPartitionData_whenBackupNodesStartedTerminated(AbstractMigrationCorrectnessTest.java:98)
	at com.hazelcast.internal.partition.AbstractMigrationCorrectnessTest.testPartitionData_whenBackupNodesStartedTerminated(AbstractMigrationCorrectnessTest.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.lang.Thread.run(Thread.java:745)
```

Standard output (maybe interesting parts):
```
05:26:09,658  WARN |testPartitionData_whenBackupNodesStartedTerminated[backups:3,nodes:4,fragmented:false]| - [InternalPartitionService] hz._hzInstance_7873_dev.generic-operation.thread-0 - [127.0.0.1]:15546 [dev] [3.10.1-SNAPSHOT] Following unknown addresses are found in partition table sent from master[[127.0.0.1]:15541]. (Probably they have recently joined or left the cluster.) {
	[127.0.0.1]:15545
}
```

```
Hiccups measured while running test 'testPartitionData_whenBackupNodesStartedTerminated[backups:3,nodes:4,fragmented:false](com.hazelcast.internal.partition.MigrationCorrectnessTest):'
05:23:30, accumulated pauses: 4041 ms, max pause: 23 ms, pauses over 1000 ms: 0
05:23:35, accumulated pauses: 4025 ms, max pause: 20 ms, pauses over 1000 ms: 0
05:23:40, accumulated pauses: 4011 ms, max pause: 17 ms, pauses over 1000 ms: 0
05:23:45, accumulated pauses: 3991 ms, max pause: 15 ms, pauses over 1000 ms: 0
05:23:50, accumulated pauses: 3990 ms, max pause: 12 ms, pauses over 1000 ms: 0
05:23:55, accumulated pauses: 3987 ms, max pause: 15 ms, pauses over 1000 ms: 0
05:24:00, accumulated pauses: 3979 ms, max pause: 14 ms, pauses over 1000 ms: 0
05:24:05, accumulated pauses: 3979 ms, max pause: 16 ms, pauses over 1000 ms: 0
05:24:10, accumulated pauses: 3983 ms, max pause: 16 ms, pauses over 1000 ms: 0
05:24:15, accumulated pauses: 3978 ms, max pause: 13 ms, pauses over 1000 ms: 0
05:24:20, accumulated pauses: 3990 ms, max pause: 17 ms, pauses over 1000 ms: 0
05:24:25, accumulated pauses: 3977 ms, max pause: 17 ms, pauses over 1000 ms: 0
05:24:30, accumulated pauses: 3980 ms, max pause: 12 ms, pauses over 1000 ms: 0
05:24:35, accumulated pauses: 3982 ms, max pause: 17 ms, pauses over 1000 ms: 0
05:24:40, accumulated pauses: 3983 ms, max pause: 12 ms, pauses over 1000 ms: 0
05:24:45, accumulated pauses: 3979 ms, max pause: 14 ms, pauses over 1000 ms: 0
05:24:50, accumulated pauses: 3975 ms, max pause: 11 ms, pauses over 1000 ms: 0
05:24:55, accumulated pauses: 3979 ms, max pause: 14 ms, pauses over 1000 ms: 0
05:25:00, accumulated pauses: 3978 ms, max pause: 14 ms, pauses over 1000 ms: 0
05:25:05, accumulated pauses: 3984 ms, max pause: 13 ms, pauses over 1000 ms: 0
05:25:10, accumulated pauses: 3982 ms, max pause: 12 ms, pauses over 1000 ms: 0
05:25:15, accumulated pauses: 3983 ms, max pause: 14 ms, pauses over 1000 ms: 0
05:25:20, accumulated pauses: 3976 ms, max pause: 13 ms, pauses over 1000 ms: 0
05:25:25, accumulated pauses: 3978 ms, max pause: 12 ms, pauses over 1000 ms: 0
05:25:30, accumulated pauses: 3977 ms, max pause: 16 ms, pauses over 1000 ms: 0
05:25:35, accumulated pauses: 3978 ms, max pause: 14 ms, pauses over 1000 ms: 0
05:25:40, accumulated pauses: 3985 ms, max pause: 17 ms, pauses over 1000 ms: 0
05:25:45, accumulated pauses: 3976 ms, max pause: 14 ms, pauses over 1000 ms: 0
05:25:50, accumulated pauses: 3980 ms, max pause: 12 ms, pauses over 1000 ms: 0
05:25:55, accumulated pauses: 3977 ms, max pause: 15 ms, pauses over 1000 ms: 0
05:26:00, accumulated pauses: 3983 ms, max pause: 13 ms, pauses over 1000 ms: 0
05:26:05, accumulated pauses: 3738 ms, max pause: 12 ms, pauses over 1000 ms: 0
```

**Comment by mmedenjak** [comment]
@mdogan @metanet can you take a quick look? Thanks!

**Comment by Holmistr** [comment]
LOL, sorry @mdogan , epic fail :1st_place_medal:

**Comment by Holmistr** [comment]
Merging https://github.com/hazelcast/hazelcast/pull/13329 should give us more information on next failure. Closing for now.

**Comment by lprimak** [comment]
Looks like I am getting this (or similar) issue with the tests for #17428 
When running the test, once in about 25 times, it fails.

**Comment by lprimak** [comment]
Looks like termination of nodes is hanging somewhere, so the whole thing times out.
I added some `waitAllForSafeState()` there to make the failure very infrequent, but it still happens very sporadically.

**Comment by mdogan** [comment]
@lprimak: There's already an open issue for this failure: https://github.com/hazelcast/hazelcast/issues/17377

**Comment by mmedenjak** [comment]
@lprimak you can usually ignore tests that fail which seem unrelated to your change. We're aware of [several of them](https://github.com/issues?q=is%3Aopen+is%3Aissue+label%3A%22Team%3A+Core%22+repo%3Ahazelcast%2Fhazelcast++sort%3Aupdated-desc+label%3A%22Type%3A+Test-Failure%22+) and usually it's a race condition that doesn't occur every time but under the right conditions, thus failing sporadically. Right now we're in the bugfixing phase so we're closing down these kinds of issues (but new ones keep popping up).

**Comment by lprimak** [comment]
ok thanks
