### ISSUE TITLE
java.lang.NoClassDefFoundError: com/hazelcast/spi/impl/operationservice/impl/Invocation$HeartbeatTimeout

### ISSUE THREAD

**Issue by witeX** [hazelcast/hazelcast#13079]
Hi,

We have issue hazelcast cluster. We have 2 groups of servers and network configuration was split by groups.
Our release policy is to just stop 1 group, deploy new application version and start. When first group started, then redeploy with new version second group.

We start receive errors and application fail to startup on second group.

**java version "1.8.0_162"**

**Network configuration for HZ**
````
<hazelcast xmlns="http://www.hazelcast.com/schema/config">
    <properties>
        <property name="hazelcast.jmx">true</property>
    </properties>
    <network>
        <port port-count="20">5701</port>
        <reuse-address>true</reuse-address>
        <join>
            <multicast enabled="false"/>
            <tcp-ip enabled="true" connection-timeout-seconds="10">
                <member>10.0.22.121</member>
                <member>10.0.22.122</member>
                <member>10.0.22.123</member>
                <member>10.0.22.124</member>
                <member>10.0.22.125</member>
                <member>10.0.22.126</member>
                <member>10.0.22.127</member>
                <member>10.0.22.128</member>
            </tcp-ip>
        </join>
    </network
````

Exception is:
````
java.lang.NoClassDefFoundError: ERROR [com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor] (hz.distributedHazelcast.InvocationMonitorThread) [10.0.22.121]:5701 [live] [3.9.1] Failed to check invocation:Invocation{op=com.hazelcast.map.impl.operation.MapGetInvalidationMetaDataOperation{serviceName='hz:impl:mapServ
ice', identityHash=685211386, partitionId=-1, replicaIndex=0, callId=771, invocationTime=1525862440031 (2018-05-09 10:40:40.031), waitTimeout=-1, callTimeout=60000}, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=60000, firstInvocationTimeMs=1525862440128, firstInvocationTime='2018-05-09 10:40:40.1
28', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 00:00:00.000', target=[10.0.22.124]:5701, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=Connection[id=4, /10.0.22.121:56979->/10.0.22.124:5701, endpoint=[10.0.22.124]:5701, alive=false, type=MEMBER]}
java.lang.NoClassDefFoundError: com/hazelcast/spi/impl/operationservice/impl/Invocation$HeartbeatTimeout
at com.hazelcast.spi.impl.operationservice.impl.Invocation.detectTimeout(Invocation.java:434)
at com.hazelcast.spi.impl.operationservice.impl.Invocation.detectAndHandleTimeout(Invocation.java:398)
at com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor$MonitorInvocationsTask.run0(InvocationMonitor.java:312)
at com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor$FixedRateMonitorTask.run(InvocationMonitor.java:268)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
```` 

It's really strange that this enum from line 434 are on in same main java class. How it could happens that it's class not found?

**Comment by pveentjer** [comment]
It smells like some kind of class loading problem. Could it be you have multiple HZ versions on the classpath?

**Comment by witeX** [comment]
Hi, 

Yesterday found where is issue. I didn't have access to full logs before.
I didn't have multiple version of HZ in classpath. 
I will describe where issue, for others who could have that issue.

Main issue was, that I didn't have shutdown hook  for spring bean hazelcast instance. 
Spring context failed initialisation and application with already running HZ was shouted down.  Thread with MonitorInvocation was running, but because enum  **HeartbeatTimeout** was never used before, was unloaded with all jars from class loader. When verification thread was found timeout, he can't find enum. That's why **NoClassDefFoundError**. 
Also here is added problems that our environment can't stop right now without force kill application, our JMS listeners stuck during context destroy, that allowed to HZ monitor thread live forever, until OPS found tons of exceptions.

**Comment by pveentjer** [comment]
Happy to hear the problem is solved. And very nice that you have posted the cause of the problem!
