### ISSUE TITLE
MapStableReadStressTest.testChangingCluster failure

### ISSUE THREAD

**Issue by Holmistr** [hazelcast/hazelcast#13085]
*master* (commit 25f2e0c57eae5e20f2edf3078acf2e4d372f6622)

Failed on nightly build: https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/86/testReport/junit/com.hazelcast.client.stress/MapStableReadStressTest/testChangingCluster/

Stacktrace:
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.lang.Thread.sleep(Native Method)
	at com.hazelcast.client.stress.StressTestSupport.startAndWaitForTestCompletion(StressTestSupport.java:101)
	at com.hazelcast.client.stress.MapStableReadStressTest.test(MapStableReadStressTest.java:89)
	at com.hazelcast.client.stress.MapStableReadStressTest.testChangingCluster(MapStableReadStressTest.java:77)
```

Standard output:
```
Hiccups measured while running test 'testChangingCluster(com.hazelcast.client.stress.MapStableReadStressTest):'
04:34:55, accumulated pauses: 35 ms, max pause: 3 ms, pauses over 1000 ms: 0
04:35:00, accumulated pauses: 32 ms, max pause: 2 ms, pauses over 1000 ms: 0
04:35:05, accumulated pauses: 32 ms, max pause: 2 ms, pauses over 1000 ms: 0
04:35:10, accumulated pauses: 36 ms, max pause: 1 ms, pauses over 1000 ms: 0
04:35:15, accumulated pauses: 35 ms, max pause: 1 ms, pauses over 1000 ms: 0
04:35:20, accumulated pauses: 62 ms, max pause: 2 ms, pauses over 1000 ms: 0
04:35:25, accumulated pauses: 53 ms, max pause: 1 ms, pauses over 1000 ms: 0
04:35:30, accumulated pauses: 93 ms, max pause: 4 ms, pauses over 1000 ms: 0
04:35:35, accumulated pauses: 245 ms, max pause: 3 ms, pauses over 1000 ms: 0
04:35:40, accumulated pauses: 252 ms, max pause: 4 ms, pauses over 1000 ms: 0
04:35:45, accumulated pauses: 260 ms, max pause: 4 ms, pauses over 1000 ms: 0
04:35:50, accumulated pauses: 183 ms, max pause: 3 ms, pauses over 1000 ms: 0
04:35:55, accumulated pauses: 182 ms, max pause: 4 ms, pauses over 1000 ms: 0
04:36:00, accumulated pauses: 130 ms, max pause: 3 ms, pauses over 1000 ms: 0
04:36:05, accumulated pauses: 105 ms, max pause: 4 ms, pauses over 1000 ms: 0
04:36:10, accumulated pauses: 111 ms, max pause: 3 ms, pauses over 1000 ms: 0
04:36:15, accumulated pauses: 138 ms, max pause: 3 ms, pauses over 1000 ms: 0
04:36:20, accumulated pauses: 94 ms, max pause: 5 ms, pauses over 1000 ms: 0
04:36:25, accumulated pauses: 147 ms, max pause: 3 ms, pauses over 1000 ms: 0
04:36:30, accumulated pauses: 159 ms, max pause: 4 ms, pauses over 1000 ms: 0
04:36:35, accumulated pauses: 119 ms, max pause: 2 ms, pauses over 1000 ms: 0
04:36:40, accumulated pauses: 175 ms, max pause: 3 ms, pauses over 1000 ms: 0
04:36:45, accumulated pauses: 143 ms, max pause: 3 ms, pauses over 1000 ms: 0
04:36:50, accumulated pauses: 161 ms, max pause: 3 ms, pauses over 1000 ms: 0
04:36:55, accumulated pauses: 187 ms, max pause: 3 ms, pauses over 1000 ms: 0
04:37:00, accumulated pauses: 168 ms, max pause: 5 ms, pauses over 1000 ms: 0
04:37:05, accumulated pauses: 206 ms, max pause: 3 ms, pauses over 1000 ms: 0
04:37:10, accumulated pauses: 329 ms, max pause: 34 ms, pauses over 1000 ms: 0
04:37:15, accumulated pauses: 150 ms, max pause: 3 ms, pauses over 1000 ms: 0
04:37:20, accumulated pauses: 150 ms, max pause: 73 ms, pauses over 1000 ms: 0
04:37:25, accumulated pauses: 104 ms, max pause: 6 ms, pauses over 1000 ms: 0
04:37:30, accumulated pauses: 115 ms, max pause: 3 ms, pauses over 1000 ms: 0
04:37:35, accumulated pauses: 119 ms, max pause: 1 ms, pauses over 1000 ms: 0
04:37:40, accumulated pauses: 117 ms, max pause: 3 ms, pauses over 1000 ms: 0
04:37:45, accumulated pauses: 74 ms, max pause: 1 ms, pauses over 1000 ms: 0
04:37:50, accumulated pauses: 67 ms, max pause: 2 ms, pauses over 1000 ms: 0
04:37:55, accumulated pauses: 68 ms, max pause: 1 ms, pauses over 1000 ms: 0
04:38:00, accumulated pauses: 88 ms, max pause: 7 ms, pauses over 1000 ms: 0
04:38:05, accumulated pauses: 77 ms, max pause: 5 ms, pauses over 1000 ms: 0
04:38:10, accumulated pauses: 134 ms, max pause: 51 ms, pauses over 1000 ms: 0
04:38:15, accumulated pauses: 94 ms, max pause: 2 ms, pauses over 1000 ms: 0
04:38:20, accumulated pauses: 140 ms, max pause: 61 ms, pauses over 1000 ms: 0
04:38:25, accumulated pauses: 117 ms, max pause: 9 ms, pauses over 1000 ms: 0
04:38:30, accumulated pauses: 121 ms, max pause: 44 ms, pauses over 1000 ms: 0
04:38:35, accumulated pauses: 58 ms, max pause: 1 ms, pauses over 1000 ms: 0
04:38:40, accumulated pauses: 184 ms, max pause: 42 ms, pauses over 1000 ms: 0
04:38:45, accumulated pauses: 101 ms, max pause: 2 ms, pauses over 1000 ms: 0
04:38:50, accumulated pauses: 97 ms, max pause: 21 ms, pauses over 1000 ms: 0
04:38:55, accumulated pauses: 96 ms, max pause: 25 ms, pauses over 1000 ms: 0
04:39:00, accumulated pauses: 84 ms, max pause: 4 ms, pauses over 1000 ms: 0
04:39:05, accumulated pauses: 89 ms, max pause: 33 ms, pauses over 1000 ms: 0
04:39:10, accumulated pauses: 60 ms, max pause: 13 ms, pauses over 1000 ms: 0
04:39:15, accumulated pauses: 35 ms, max pause: 8 ms, pauses over 1000 ms: 0
04:39:20, accumulated pauses: 28 ms, max pause: 2 ms, pauses over 1000 ms: 0
04:39:25, accumulated pauses: 37 ms, max pause: 10 ms, pauses over 1000 ms: 0
04:39:30, accumulated pauses: 45 ms, max pause: 17 ms, pauses over 1000 ms: 0
04:39:35, accumulated pauses: 53 ms, max pause: 14 ms, pauses over 1000 ms: 0
04:39:40, accumulated pauses: 31 ms, max pause: 6 ms, pauses over 1000 ms: 0
04:39:45, accumulated pauses: 86 ms, max pause: 58 ms, pauses over 1000 ms: 0
04:39:50, accumulated pauses: 47 ms, max pause: 8 ms, pauses over 1000 ms: 0
04:39:55, accumulated pauses: 35 ms, max pause: 9 ms, pauses over 1000 ms: 0
04:40:00, accumulated pauses: 44 ms, max pause: 17 ms, pauses over 1000 ms: 0
04:40:05, accumulated pauses: 43 ms, max pause: 11 ms, pauses over 1000 ms: 0
04:40:10, accumulated pauses: 32 ms, max pause: 7 ms, pauses over 1000 ms: 0
04:40:15, accumulated pauses: 330 ms, max pause: 270 ms, pauses over 1000 ms: 0
04:40:20, accumulated pauses: 21 ms, max pause: 8 ms, pauses over 1000 ms: 0
```

**Comment by sancar** [comment]
This tests timed out after 5 minutes. In my local machine it took 4 minutes to complete. 
Under the load, it seems pretty normal for this test to take 5 minutes. I think we just need to increase the timeout.
