### ISSUE TITLE
ClientRegressionWithMockNetworkTest.testOperationRedo failure

### ISSUE THREAD

**Issue by Holmistr** [hazelcast/hazelcast#13093]
*maintenance*

Failed on PR builder: https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/15586/testReport/junit/com.hazelcast.client/ClientRegressionWithMockNetworkTest/testOperationRedo/

Stacktrace:
```
org.junit.runners.model.TestTimedOutException: test timed out after 60000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:304)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:160)
	at com.hazelcast.client.spi.ClientProxy.invokeOnPartition(ClientProxy.java:225)
	at com.hazelcast.client.spi.ClientProxy.invoke(ClientProxy.java:219)
	at com.hazelcast.client.proxy.ClientMapProxy.putInternal(ClientMapProxy.java:518)
	at com.hazelcast.client.proxy.ClientMapProxy.put(ClientMapProxy.java:510)
	at com.hazelcast.client.proxy.ClientMapProxy.put(ClientMapProxy.java:313)
	at com.hazelcast.client.ClientRegressionWithMockNetworkTest.testOperationRedo(ClientRegressionWithMockNetworkTest.java:142)
```

Standard output:
```
Hiccups measured while running test 'testOperationRedo(com.hazelcast.client.ClientRegressionWithMockNetworkTest):'
09:14:25, accumulated pauses: 7110 ms, max pause: 5133 ms, pauses over 1000 ms: 1
09:14:30, accumulated pauses: 261 ms, max pause: 119 ms, pauses over 1000 ms: 0
09:14:35, accumulated pauses: 1818 ms, max pause: 46 ms, pauses over 1000 ms: 0
09:14:40, accumulated pauses: 2261 ms, max pause: 361 ms, pauses over 1000 ms: 0
09:14:45, accumulated pauses: 2351 ms, max pause: 363 ms, pauses over 1000 ms: 0
09:14:50, accumulated pauses: 2670 ms, max pause: 691 ms, pauses over 1000 ms: 0
09:14:55, accumulated pauses: 2556 ms, max pause: 385 ms, pauses over 1000 ms: 0
09:15:00, accumulated pauses: 3651 ms, max pause: 2133 ms, pauses over 1000 ms: 1
09:15:05, accumulated pauses: 3897 ms, max pause: 2454 ms, pauses over 1000 ms: 1
09:15:10, accumulated pauses: 2870 ms, max pause: 627 ms, pauses over 1000 ms: 0
09:15:15, accumulated pauses: 1652 ms, max pause: 191 ms, pauses over 1000 ms: 0
09:15:20, accumulated pauses: 7123 ms, max pause: 4414 ms, pauses over 1000 ms: 1
09:15:25, accumulated pauses: 1116 ms, max pause: 1104 ms, pauses over 1000 ms: 1
09:15:30, accumulated pauses: 2670 ms, max pause: 995 ms, pauses over 1000 ms: 0
09:15:35, accumulated pauses: 2801 ms, max pause: 396 ms, pauses over 1000 ms: 0
09:15:40, accumulated pauses: 2154 ms, max pause: 259 ms, pauses over 1000 ms: 0
09:15:45, accumulated pauses: 1152 ms, max pause: 113 ms, pauses over 1000 ms: 0
```

Possibly related to https://github.com/hazelcast/hazelcast/issues/6153 ?

**Comment by sancar** [comment]
There is a high load in the system. Even 2 nodes and a client start took 30 seconds in the test. 
I will remove the explicit timeout from the test `@Test(timeout = 60000)`, which should increase the default timeout and close the issue.
