### ISSUE TITLE
ClientCacheReadWriteThroughTest fails intermittently

### ISSUE THREAD

**Issue by kwart** [hazelcast/hazelcast#13098]
The `com.hazelcast.client.cache.ClientCacheReadWriteThroughTest.test_readThroughCacheLoader_withNearCache` fails intermittently on PR builder:
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/15605/testReport/junit/com.hazelcast.client.cache/ClientCacheReadWriteThroughTest/test_readThroughCacheLoader_withNearCache/

**Stacktrace**
```
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@25415c10 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@6e2d08a4[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 16]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:549)
	at java.util.concurrent.ScheduledThreadPoolExecutor.submit(ScheduledThreadPoolExecutor.java:648)
	at java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:681)
	at com.hazelcast.client.spi.impl.listener.AbstractClientListenerService.deregisterListener(AbstractClientListenerService.java:135)
	at com.hazelcast.client.cache.impl.NearCachedClientCacheProxy.removeInvalidationListener(NearCachedClientCacheProxy.java:592)
	at com.hazelcast.client.cache.impl.NearCachedClientCacheProxy.close(NearCachedClientCacheProxy.java:450)
	at com.hazelcast.cache.impl.AbstractHazelcastCacheManager.close(AbstractHazelcastCacheManager.java:328)
	at com.hazelcast.cache.impl.AbstractHazelcastCachingProvider.close(AbstractHazelcastCachingProvider.java:169)
	at com.hazelcast.cache.CacheReadWriteThroughTest.tearDown(CacheReadWriteThroughTest.java:108)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:432)
	at com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37)
	at com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:104)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at com.hazelcast.test.HazelcastParallelClassRunner.access$301(HazelcastParallelClassRunner.java:49)
	at com.hazelcast.test.HazelcastParallelClassRunner$TestRunner.run(HazelcastParallelClassRunner.java:162)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Holmistr** [comment]
Occurred again in the PR builder under very heavy load on the machine: https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/15619/testReport/junit/com.hazelcast.client.cache/ClientCacheReadWriteThroughTest/test_readThroughCacheLoader_withNearCache/
