### ISSUE TITLE
NPE when authentication if conneciton get closed right before `bind`

### ISSUE THREAD

**Issue by sancar** [hazelcast/hazelcast#13118]
from this  multi version split heal test  https://hazelcast-l337.ci.cloudbees.com/view/split/job/split-data-loss-multi-v/7/console
using versions 3.9.4 and 3.10.1 (edited)

Here is the related stack trace
```
SEVERE: [10.0.0.174]:5701 [HZ] [3.9.4] Failed asynchronous execution of execution callback: com.hazelcast.client.impl.protocol.task.AuthenticationMessageTask@344026c1for call class
com.hazelcast.internal.util.futures.ChainingFuture
java.lang.NullPointerException: inetSocketAddress can't be null
    at com.hazelcast.util.Preconditions.checkNotNull(Preconditions.java:59)
    at com.hazelcast.nio.Address.resolve(Address.java:193)
    at com.hazelcast.nio.Address.<init>(Address.java:70)
    at com.hazelcast.client.impl.ClientEngineImpl.bind(ClientEngineImpl.java:312)
    at com.hazelcast.client.impl.protocol.task.AuthenticationBaseMessageTask.prepareAuthenticatedClientMessage(AuthenticationBaseMessageTask.java:203)
    at com.hazelcast.client.impl.protocol.task.AuthenticationBaseMessageTask.resolve(AuthenticationBaseMessageTask.java:70)
    at com.hazelcast.client.impl.protocol.task.AbstractStableClusterMessageTask.onResponse(AbstractStableClusterMessageTask.java:49)
    at com.hazelcast.spi.impl.AbstractCompletableFuture$ExecutionCallbackRunnable.run(AbstractCompletableFuture.java:339)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
    at java.lang.Thread.run(Thread.java:748)
    at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
    at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
```

**Comment by sancar** [comment]
Since connection is closed we can't return a response to client. Only solution here seems to catch the exception and put a friendly warning.
