### ISSUE TITLE
Payara 4.1 Throws serialization error with hazelcast 3.10 com.hazelcast.nio.serialization.HazelcastSerializationException: java.io.EOFException: Cannot read 4 bytes!

### ISSUE THREAD

**Issue by virtualcousin** [hazelcast/hazelcast#13126]
Hello,

My application was running on hazlecast 3.8.5 without any issues. We are now trying to migrate to 3.10. However the following error log is getting logged on the server when multiple nodes are started. Some times with only one node running also it is logging this error. Application as such is working fine and we do not observe any issue, but how can we remove this error from getting logged almost every 30 seconds. Complete error trace below. My application is on Payara Glassfish 4.1 and JDK 8 with two nodes holding a total of 8.5 Million records. Let me know for any additional information.

```
[2018-05-17T04:14:18.532-0400] [Payara 4.1] [SEVERE] [] [com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl] [tid: _ThreadID=86 _ThreadName=hz._hzInstance_1_vlsuser.priority-generic-operation.thread-0] [timeMillis: 1526544858532] [levelValue: 1000] [[
  [160.50.34.194]:5701 [vlsuser] [3.10] Failed to process packet: Packet{partitionId=-1, conn=Connection[id=3, /160.50.34.194:53556->/160.50.34.82:5701, endpoint=[160.50.34.82]:5701, alive=true, type=MEMBER], rawFlags=10001, isUrgent=true, packetType=OPERATION, typeSpecificFlags=[isResponse=false, isOpControl=false]} on hz._hzInstance_1_vlsuser.priority-generic-operation.thread-0
com.hazelcast.nio.serialization.HazelcastSerializationException: java.io.EOFException: Cannot read 4 bytes!
        at com.hazelcast.internal.serialization.impl.SerializationUtil.handleException(SerializationUtil.java:63)
        at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:197)
        at com.hazelcast.spi.impl.NodeEngineImpl.toObject(NodeEngineImpl.java:322)
        at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:390)
        at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:115)
        at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:100)
Caused by: java.io.EOFException: Cannot read 4 bytes!
        at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.checkAvailable(ByteArrayObjectDataInput.java:642)
        at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readInt(ByteArrayObjectDataInput.java:275)
        at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readInt(ByteArrayObjectDataInput.java:269)
        at com.hazelcast.internal.cluster.impl.SplitBrainJoinMessage.readData(SplitBrainJoinMessage.java:73)
        at com.hazelcast.internal.cluster.impl.operations.SplitBrainMergeValidationOp.readInternal(SplitBrainMergeValidationOp.java:185)
        at com.hazelcast.spi.Operation.readData(Operation.java:669)
        at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.readInternal(DataSerializableSerializer.java:158)
        at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:105)
        at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:50)
        at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48)
        at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:191)
        ... 4 more
```

**Comment by mmedenjak** [comment]
Hi @virtualcousin !

Are you running 3.8.5 and 3.10 members at the same time in the cluster? Or is this exception occurring when there are members of only one version in the cluster?

**Comment by mmedenjak** [comment]
@virtualcousin any updates on this issue?

**Comment by virtualcousin** [comment]
@mmedenjak : Glassfish server installation on UNIX machine has a built in module library for hazelcast version 3.8.5. So to answer your question, we have 3.10 first in the classpath and probably 3.8.5 is also getting included since that is available with the server libraries. We do not have a possibility to remove that as that is on a base installation mount.

**Comment by virtualcousin** [comment]
@mmedenjak : Do you have any feedback on this topic ? Is this a known issue ? 
On the same server Payara server I tried with hazlecast versions 3.9.3 and 3.9.4 and all of them had the same problem. For now switched the version back to default one 3.8.5 and it is working fine. Let me know if you need any additional information.

**Comment by vbekiaris** [comment]
@virtualcousin Hazelcast open source cluster members are only compatible across different patch versions, so 3.9.x or 3.10.x are not guaranteed to (and will not) work in the same cluster with a 3.8.x member. If you want to use newer Hazelcast versions in your app, you should ensure that the Hazelcast member that is embedded with Payara is on a separate cluster, independent of your app's Hazelcast instances or upgrade the embedded Hazelcast in Payara (but I'm not sure if that's possible or recommended -- better ask the Payara experts about that). There are a couple of ways to achieve this (eg define explicit members with TCP/IP join config), it would help If you could describe how your deployment looks like (topology of your Hazelcast instances vs embedded ones in Payara) and post your Hazelcast configs.

Since this is not an issue, I am closing this now but feel free to discuss further on Hazelcast [google group](https://groups.google.com/forum/#!forum/hazelcast) or [chat on gitter](https://gitter.im/hazelcast/hazelcast).
