### ISSUE TITLE
MemcacheTest.testIncrement failure

### ISSUE THREAD

**Issue by Holmistr** [hazelcast/hazelcast#13152]
*master* (commit d62efd8632985019f5436f260d3fda2df05772fe)

Failed on IBM JDK7: https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK7/198/testReport/junit/com.hazelcast.internal.ascii/MemcacheTest/testIncrement/

Stacktrace:
```
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextEntry(HashMap.java:934)
	at java.util.HashMap$KeyIterator.next(HashMap.java:968)
	at sun.nio.ch.SelectorImpl.implCloseSelector(SelectorImpl.java:126)
	at java.nio.channels.spi.AbstractSelector.close(AbstractSelector.java:120)
	at net.spy.memcached.MemcachedConnection.shutdown(MemcachedConnection.java:1339)
	at net.spy.memcached.MemcachedClient.shutdown(MemcachedClient.java:2512)
	at net.spy.memcached.MemcachedClient.shutdown(MemcachedClient.java:2474)
	at com.hazelcast.internal.ascii.MemcacheTest.tearDown(MemcacheTest.java:81)
```

Standard output: 
```
Hiccups measured while running test 'testIncrement(com.hazelcast.internal.ascii.MemcacheTest):'
06:58:35, accumulated pauses: 645 ms, max pause: 352 ms, pauses over 1000 ms: 0
```

Standard error:
```
2018-05-19 06:58:37.583 INFO net.spy.memcached.MemcachedConnection:  Shut down memcached client
```

**Comment by Holmistr** [comment]
@mdogan Regarding this test failure, it looks completely unrelated to Hazelcast, it's spymemcached issue. I remember when I was working with the client, it's single threaded and not really suitable for parallel execution. I see that in the commit 9ef45d03b75778b700071217e7d9ca3c9b951507 you changed the JUnit runner from Serial to Parallel. I'm wondering whether this couldn't be the issue. WDYT?

**Comment by mdogan** [comment]
I agree that, this failure looks like a _spymemcached_ issue. But it should not be related to serial or parallel test runner, because even tests are executed in parallel, each test method creates its own `MemcachedClient` instance. So, `MemcachedClient`s are not shared between tests.

**Comment by Holmistr** [comment]
I'm closing this issue. Even after investigation of the logs, I didn't find anything that could be related to Hazelcast and everything point to the fact that it's a spymemcached issue. I will reopen if the issue starts to happen more often, otherwise let's not spend any more time on fixing spymemcached issues.
