### ISSUE TITLE
ClientCacheInvalidationMemberAddRemoveTest.ensure_nearCachedClient_and_member_data_sync_eventually failure

### ISSUE THREAD

**Issue by Holmistr** [hazelcast/hazelcast#13210]
*master* (commit 4e24ea071ff17f2b98b47dd42dcb4a0fd0ac74e6)

Failed on nightly build: https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/101/

Stacktrace:
```
java.lang.AssertionError: partition=251, onRecordSequence=-1, latestSequence=30, staleSequence=0, memberSequence=30 expected:<null> but was:<685792170>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at com.hazelcast.client.cache.impl.nearcache.invalidation.ClientCacheInvalidationMemberAddRemoveTest$5.run(ClientCacheInvalidationMemberAddRemoveTest.java:202)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1248)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1274)
	at com.hazelcast.client.cache.impl.nearcache.invalidation.ClientCacheInvalidationMemberAddRemoveTest.ensure_nearCachedClient_and_member_data_sync_eventually(ClientCacheInvalidationMemberAddRemoveTest.java:190)
```

```
Hiccups measured while running test 'ensure_nearCachedClient_and_member_data_sync_eventually[localUpdatePolicy:INVALIDATE](com.hazelcast.client.cache.impl.nearcache.invalidation.ClientCacheInvalidationMemberAddRemoveTest):'
04:23:00, accumulated pauses: 51 ms, max pause: 11 ms, pauses over 1000 ms: 0
04:23:05, accumulated pauses: 44 ms, max pause: 8 ms, pauses over 1000 ms: 0
04:23:10, accumulated pauses: 104 ms, max pause: 58 ms, pauses over 1000 ms: 0
04:23:15, accumulated pauses: 62 ms, max pause: 12 ms, pauses over 1000 ms: 0
04:23:20, accumulated pauses: 28 ms, max pause: 0 ms, pauses over 1000 ms: 0
04:23:25, accumulated pauses: 43 ms, max pause: 14 ms, pauses over 1000 ms: 0
04:23:30, accumulated pauses: 31 ms, max pause: 4 ms, pauses over 1000 ms: 0
04:23:35, accumulated pauses: 32 ms, max pause: 0 ms, pauses over 1000 ms: 0
04:23:40, accumulated pauses: 34 ms, max pause: 0 ms, pauses over 1000 ms: 0
04:23:45, accumulated pauses: 34 ms, max pause: 1 ms, pauses over 1000 ms: 0
04:23:50, accumulated pauses: 39 ms, max pause: 4 ms, pauses over 1000 ms: 0
04:23:55, accumulated pauses: 31 ms, max pause: 0 ms, pauses over 1000 ms: 0
04:24:00, accumulated pauses: 38 ms, max pause: 2 ms, pauses over 1000 ms: 0
04:24:05, accumulated pauses: 45 ms, max pause: 3 ms, pauses over 1000 ms: 0
04:24:10, accumulated pauses: 33 ms, max pause: 0 ms, pauses over 1000 ms: 0
04:24:15, accumulated pauses: 32 ms, max pause: 0 ms, pauses over 1000 ms: 0
04:24:20, accumulated pauses: 34 ms, max pause: 1 ms, pauses over 1000 ms: 0
04:24:25, accumulated pauses: 30 ms, max pause: 0 ms, pauses over 1000 ms: 0
04:24:30, accumulated pauses: 42 ms, max pause: 8 ms, pauses over 1000 ms: 0
04:24:35, accumulated pauses: 33 ms, max pause: 1 ms, pauses over 1000 ms: 0
04:24:40, accumulated pauses: 37 ms, max pause: 1 ms, pauses over 1000 ms: 0
04:24:45, accumulated pauses: 40 ms, max pause: 1 ms, pauses over 1000 ms: 0
04:24:50, accumulated pauses: 29 ms, max pause: 0 ms, pauses over 1000 ms: 0
04:24:55, accumulated pauses: 40 ms, max pause: 0 ms, pauses over 1000 ms: 0
04:25:00, accumulated pauses: 45 ms, max pause: 2 ms, pauses over 1000 ms: 0
04:25:05, accumulated pauses: 59 ms, max pause: 17 ms, pauses over 1000 ms: 0
04:25:10, accumulated pauses: 42 ms, max pause: 2 ms, pauses over 1000 ms: 0
04:25:15, accumulated pauses: 39 ms, max pause: 2 ms, pauses over 1000 ms: 0
04:25:20, accumulated pauses: 47 ms, max pause: 6 ms, pauses over 1000 ms: 0
04:25:25, accumulated pauses: 49 ms, max pause: 3 ms, pauses over 1000 ms: 0
04:25:30, accumulated pauses: 35 ms, max pause: 0 ms, pauses over 1000 ms: 0
04:25:35, accumulated pauses: 61 ms, max pause: 21 ms, pauses over 1000 ms: 0
04:25:40, accumulated pauses: 41 ms, max pause: 1 ms, pauses over 1000 ms: 0
04:25:45, accumulated pauses: 378 ms, max pause: 344 ms, pauses over 1000 ms: 0
```

**Comment by Holmistr** [comment]
*master* (commit ce422a72f77b125d3461d42abeea2275b0c4bba5)

Failed again on Sonar build: https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-EE-3.x-sonar/118/testReport/junit/com.hazelcast.client.cache.nearcache/ClientHDCacheNearCacheInvalidationTest/when_shuttingDown_invalidationEventIsNotReceived_format_OBJECT__fromMember_false_/

Stacktrace:
```
java.lang.AssertionError: Expected no further Near Cache invalidation events than 0, but received 1 (NearCacheStatsImpl{ownedEntryCount=0, ownedEntryMemoryCost=0, creationTime=1527831535385, hits=0, misses=0, ratio=NaN%, evictions=0, expirations=0, invalidations=0, lastPersistenceTime=0, persistenceCount=0, lastPersistenceDuration=0, lastPersistenceWrittenBytes=0, lastPersistenceKeyCount=0, lastPersistenceFailure=''})
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.client.cache.impl.nearcache.ClientCacheNearCacheInvalidationTest$5.run(ClientCacheNearCacheInvalidationTest.java:484)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1248)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1274)
	at com.hazelcast.client.cache.impl.nearcache.ClientCacheNearCacheInvalidationTest.assertNoFurtherInvalidationThan(ClientCacheNearCacheInvalidationTest.java:490)
	at com.hazelcast.client.cache.impl.nearcache.ClientCacheNearCacheInvalidationTest.assertNoFurtherInvalidation(ClientCacheNearCacheInvalidationTest.java:476)
	at com.hazelcast.client.cache.impl.nearcache.ClientCacheNearCacheInvalidationTest.when_shuttingDown_invalidationEventIsNotReceived(ClientCacheNearCacheInvalidationTest.java:331)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```
