### ISSUE TITLE
IMapDataStructureAdapterTest.testLoadAll failure

### ISSUE THREAD

**Issue by Holmistr** [hazelcast/hazelcast#13234]
*master* (commit 12d23f34c4152fac4747eb06dac179517f00e4a5)

Failed on Zing JDK7: https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-ZingJDK7/144/testReport/junit/com.hazelcast.internal.adapter/IMapDataStructureAdapterTest/testLoadAll/

Stacktrace:
```
org.junit.ComparisonFailure: expected:<[newV]alue-23> but was:<[v]alue-23>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.internal.adapter.IMapDataStructureAdapterTest.testLoadAll(IMapDataStructureAdapterTest.java:381)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by Holmistr** [comment]
*master* (commit bb8ffe323db553fc109f58a2469470ca20422871)

Failed again on Zing JDK8: https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-ZingJDK8/112/testReport/junit/com.hazelcast.internal.adapter/IMapDataStructureAdapterTest/testLoadAll/

Stacktrace:
```
org.junit.ComparisonFailure: expected:<[newV]alue-23> but was:<[v]alue-23>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.internal.adapter.IMapDataStructureAdapterTest.testLoadAll(IMapDataStructureAdapterTest.java:382)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
```

Standard output:
```
Hiccups measured while running test 'testLoadAll(com.hazelcast.internal.adapter.IMapDataStructureAdapterTest):'
23:14:30, accumulated pauses: 3128 ms, max pause: 31 ms, pauses over 1000 ms: 0
```

**Comment by Holmistr** [comment]
*master* (commit 7ed1e84762c4e5ca8afa22416f6e73187509f4f9)

Failed again on Zing JDK7: https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-ZingJDK7/178/testReport/com.hazelcast.internal.adapter/IMapDataStructureAdapterTest/testLoadAll/

Stacktrace:
```
rg.junit.ComparisonFailure: expected:<[newV]alue-23> but was:<[v]alue-23>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.internal.adapter.IMapDataStructureAdapterTest.testLoadAll(IMapDataStructureAdapterTest.java:382)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.lang.Thread.run(Thread.java:745)
```

Standard output:
```
Hiccups measured while running test 'testLoadAll(com.hazelcast.internal.adapter.IMapDataStructureAdapterTest):'
00:27:50, accumulated pauses: 2241 ms, max pause: 20 ms, pauses over 1000 ms: 0
```

**Comment by vbekiaris** [comment]
From the thread dump in the first failure's logs (Zing-JDK8 # 112) it seems map loading was still in progress, so `MapProxySupport#waitUntilLoaded` and then `GetOperation` proceeded even though map loading wasn't finished:
```
"hz._hzInstance_5227_dev.cached.thread-14"
        java.lang.Thread.State: WAITING, cpu=661055 nsecs, usr=0 nsecs, blocked=0 msecs, waited=12 msecs
                at sun.misc.Unsafe.park(Native Method)
                at java.util.concurrent.locks.LockSupport.park(LockSupport.java:304)
                at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:160)
                at com.hazelcast.util.FutureUtil.waitForever(FutureUtil.java:288)
                at com.hazelcast.util.FutureUtil.waitForever(FutureUtil.java:304)
                at com.hazelcast.map.impl.MapKeyLoader.sendKeyLoadCompleted(MapKeyLoader.java:535)
                at com.hazelcast.map.impl.MapKeyLoader.sendKeysInBatches(MapKeyLoader.java:461)
                at com.hazelcast.map.impl.MapKeyLoader.access$200(MapKeyLoader.java:73)
                at com.hazelcast.map.impl.MapKeyLoader$1.call(MapKeyLoader.java:245)
                at com.hazelcast.map.impl.MapKeyLoader$1.call(MapKeyLoader.java:242)
                at com.hazelcast.util.executor.CompletableFutureTask.run(CompletableFutureTask.java:67)
                at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:227)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
                at java.lang.Thread.run(Thread.java:745)
                at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
                at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
```

**Comment by vbekiaris** [comment]
After thousands of executions with various JDKs, this test has not yet failed for me locally. Created #13854 to enable `TRACE` level logging for this test so we will have more information about the state of `MapKeyLoader` on a next failure.

**Comment by vbekiaris** [comment]
#13854 merged, closing this issue for now. If the test failure occurs again, more info will be available in the logs.
