### ISSUE TITLE
ClientLockQuorumWriteTest failure

### ISSUE THREAD

**Issue by Holmistr** [hazelcast/hazelcast#13235]
*master*

Failed on PR builder: https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-pr-builder/15870/testReport/junit/com.hazelcast.client.quorum.lock/ClientLockQuorumWriteTest/com_hazelcast_client_quorum_lock_ClientLockQuorumWriteTest/

Stacktrace:
```
08:43:35,112 ERROR || - [FetchMembersViewOp] hz._hzInstance_7_yqeydrnocm.generic-operation.thread-9 - [127.0.0.1]:5007 [yqeydrnocm] [3.10.3-SNAPSHOT] [127.0.0.1]:5006 claims mastership but this node is master!
java.lang.IllegalArgumentException: [127.0.0.1]:5006 claims mastership but this node is master!
	at com.hazelcast.util.Preconditions.checkFalse(Preconditions.java:314) ~[hazelcast-3.10.3-SNAPSHOT.jar:3.10.3-SNAPSHOT]
	at com.hazelcast.internal.cluster.impl.ClusterServiceImpl.handleMastershipClaim(ClusterServiceImpl.java:258) ~[hazelcast-3.10.3-SNAPSHOT.jar:3.10.3-SNAPSHOT]
	at com.hazelcast.internal.cluster.impl.operations.FetchMembersViewOp.run(FetchMembersViewOp.java:58) ~[hazelcast-3.10.3-SNAPSHOT.jar:3.10.3-SNAPSHOT]
	at com.hazelcast.spi.Operation.call(Operation.java:148) [hazelcast-3.10.3-SNAPSHOT.jar:3.10.3-SNAPSHOT]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:202) [hazelcast-3.10.3-SNAPSHOT.jar:3.10.3-SNAPSHOT]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:191) [hazelcast-3.10.3-SNAPSHOT.jar:3.10.3-SNAPSHOT]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:405) [hazelcast-3.10.3-SNAPSHOT.jar:3.10.3-SNAPSHOT]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:115) [hazelcast-3.10.3-SNAPSHOT.jar:3.10.3-SNAPSHOT]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:100) [hazelcast-3.10.3-SNAPSHOT.jar:3.10.3-SNAPSHOT]
08:43:35,114 ERROR || - [FetchMembersViewOp] hz._hzInstance_9_yqeydrnocm.generic-operation.thread-19 - [127.0.0.1]:5009 [yqeydrnocm] [3.10.3-SNAPSHOT] [127.0.0.1]:5006 claims mastership but this node is master!
java.lang.IllegalArgumentException: [127.0.0.1]:5006 claims mastership but this node is master!
	at com.hazelcast.util.Preconditions.checkFalse(Preconditions.java:314) ~[hazelcast-3.10.3-SNAPSHOT.jar:3.10.3-SNAPSHOT]
	at com.hazelcast.internal.cluster.impl.ClusterServiceImpl.handleMastershipClaim(ClusterServiceImpl.java:258) ~[hazelcast-3.10.3-SNAPSHOT.jar:3.10.3-SNAPSHOT]
	at com.hazelcast.internal.cluster.impl.operations.FetchMembersViewOp.run(FetchMembersViewOp.java:58) ~[hazelcast-3.10.3-SNAPSHOT.jar:3.10.3-SNAPSHOT]
	at com.hazelcast.spi.Operation.call(Operation.java:148) [hazelcast-3.10.3-SNAPSHOT.jar:3.10.3-SNAPSHOT]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:202) [hazelcast-3.10.3-SNAPSHOT.jar:3.10.3-SNAPSHOT]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:191) [hazelcast-3.10.3-SNAPSHOT.jar:3.10.3-SNAPSHOT]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:405) [hazelcast-3.10.3-SNAPSHOT.jar:3.10.3-SNAPSHOT]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:115) [hazelcast-3.10.3-SNAPSHOT.jar:3.10.3-SNAPSHOT]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:100) [hazelcast-3.10.3-SNAPSHOT.jar:3.10.3-SNAPSHOT]
```

**Comment by sancar** [comment]
Adding core label. Test failed when initialising the cluster before the actual intended split.  Somehow members are split when trying to load the test data to cluster.
