### ISSUE TITLE
NPE client side get map com.hazelcast.spi.DefaultObjectNamespace.hashCode(DefaultObjectNamespace.java:92)

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#13244]
client side NPE

```
java.lang.NullPointerException
	at com.hazelcast.spi.DefaultObjectNamespace.hashCode(DefaultObjectNamespace.java:92)
	at java.util.concurrent.ConcurrentHashMap.hash(ConcurrentHashMap.java:333)
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:988)
	at com.hazelcast.client.spi.ProxyManager.getOrCreateProxy(ProxyManager.java:300)
	at com.hazelcast.client.impl.HazelcastClientInstanceImpl.getDistributedObject(HazelcastClientInstanceImpl.java:697)
	at com.hazelcast.client.impl.HazelcastClientInstanceImpl.getMap(HazelcastClientInstanceImpl.java:501)
	at com.hazelcast.client.impl.HazelcastClientProxy.getMap(HazelcastClientProxy.java:120)

```

where as from the Member side 

```
java.lang.NullPointerException: Retrieving a map instance with a null name is not allowed!
	at com.hazelcast.util.Preconditions.checkNotNull(Preconditions.java:59)
	at com.hazelcast.instance.HazelcastInstanceImpl.getMap(HazelcastInstanceImpl.java:186)
	at com.hazelcast.instance.HazelcastInstanceProxy.getMap(HazelcastInstanceProxy.java:98)
```

`Retrieving a map instance with a null name is not allowed!`  makes the problem visible.

**Comment by Danny-Hazelcast** [comment]
interestingly, member side cacheGet(null);  seams to work ?

**Comment by sancar** [comment]
Yes, it looks like client side missing this check for every get operations on the client instance.
