### ISSUE TITLE
NPE  getCache()  client protocol ParameterUtil.java:32

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#13243]
HazelcastClient 3.11-SNAPSHOT (20180604 - f38c335, 12d23f3) is CLIENT_CONNECTED

https://hazelcast-l337.ci.cloudbees.com/view/stable/job/stable-x1/224/console

/disk1/jenkins/workspace/stable-x1/3.11-SNAPSHOT/2018_06_04-18_07_39/ttl Failed

fail HzClient1HZ _ttl_cache-putTTL java.lang.NullPointerException 
 
http://54.82.84.143/~jenkins/workspace/stable-x1/3.11-SNAPSHOT/2018_06_04-18_07_39/ttl

```
java.lang.NullPointerException
    at com.hazelcast.client.impl.protocol.util.ParameterUtil.calculateDataSize(ParameterUtil.java:32)
    at com.hazelcast.client.impl.protocol.codec.CacheGetConfigCodec$RequestParameters.calculateDataSize(CacheGetConfigCodec.java:29)
    at com.hazelcast.client.impl.protocol.codec.CacheGetConfigCodec.encodeRequest(CacheGetConfigCodec.java:37)
    at com.hazelcast.client.cache.impl.ClientCacheHelper.getCacheConfig(ClientCacheHelper.java:70)
    at com.hazelcast.client.cache.impl.HazelcastClientCacheManager.getCacheConfig(HazelcastClientCacheManager.java:103)
    at com.hazelcast.client.cache.impl.HazelcastClientCacheManager.findCacheConfig(HazelcastClientCacheManager.java:126)
    at com.hazelcast.cache.impl.AbstractHazelcastCacheManager.getCacheUnchecked(AbstractHazelcastCacheManager.java:238)
    at com.hazelcast.cache.impl.AbstractHazelcastCacheManager.getCache(AbstractHazelcastCacheManager.java:220)
    at com.hazelcast.cache.impl.AbstractHazelcastCacheManager.getCache(AbstractHazelcastCacheManager.java:67)
```

**Comment by Danny-Hazelcast** [comment]
I think its from 

Object name=null;

cacheManager.getCache(name);

**Comment by Danny-Hazelcast** [comment]
interestingly the behaviour on the member side is different, it seams like it "allows" null names

**Comment by Danny-Hazelcast** [comment]
example of get map from member side 

`Retrieving a map instance with a null name is not allowed!`  makes it simple 

```
java.lang.NullPointerException: Retrieving a map instance with a null name is not allowed!
	at com.hazelcast.util.Preconditions.checkNotNull(Preconditions.java:59)
	at com.hazelcast.instance.HazelcastInstanceImpl.getMap(HazelcastInstanceImpl.java:186)
	at com.hazelcast.instance.HazelcastInstanceProxy.getMap(HazelcastInstanceProxy.java:98)

```

**Comment by sancar** [comment]
I have checked the javadoc of CacheManager. It does not state a NullPointerException when cacheName is null. So member side behaviour seems more accurate here. 
```
 /**
   * Looks up a managed {@link Cache} given its name.
   * <p>
   * This method may only be used to acquire {@link Cache}s that were
   * configured without runtime key and value types, or were configured
   * to use Object.class key and value types.
   * <p>
   * Use the {@link #getCache(String, Class, Class)} method to acquire
   * {@link Cache}s with a check that the supplied key and value type parameters
   * match the runtime types.
   * <p>
   * Implementations that support declarative mechanisms for pre-configuring
   * {@link Cache}s may return a pre-configured {@link Cache} instead of
   * <code>null</code>.
   *
   * @param <K> the type of key
   * @param <V> the type of value
   * @param cacheName the name of the cache to look for
   * @return the Cache or null if it does exist or can't be pre-configured
   * @throws IllegalStateException    if the CacheManager is {@link #isClosed()}
   * @throws SecurityException        when the operation could not be performed
   *                                  due to the current security settings
   * @see #getCache(String, Class, Class)
   */
  <K, V> Cache<K, V> getCache(String cacheName);
```

**Comment by sancar** [comment]
https://github.com/jsr107/RI/blob/master/cache-ri-impl/src/main/java/org/jsr107/ri/RICacheManager.java#L239

Thanks to @asimarslan , I have found the reference implementation. It returns also `null` when cacheName is null.
