### ISSUE TITLE
ClientTimeoutTest.testTimeoutToOutsideNetwork failure

### ISSUE THREAD

**Issue by Holmistr** [hazelcast/hazelcast#13303]
*master* (commit 1f10121522ff194497d4d51660b5e77262681877)

Failed on Zulu JDK6: https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-ZuluJDK6/464/testReport/junit/com.hazelcast.client/ClientTimeoutTest/testTimeoutToOutsideNetwork/

Stacktrace:
```
org.junit.runners.model.TestTimedOutException: test timed out after 20000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:838)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:998)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
	at java.util.concurrent.FutureTask$Sync.innerGet(FutureTask.java:248)
	at java.util.concurrent.FutureTask.get(FutureTask.java:111)
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.connectToCluster(ClientConnectionManagerImpl.java:805)
	at com.hazelcast.client.connection.nio.DefaultClientConnectionStrategy.start(DefaultClientConnectionStrategy.java:45)
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.start(ClientConnectionManagerImpl.java:298)
	at com.hazelcast.client.impl.HazelcastClientInstanceImpl.start(HazelcastClientInstanceImpl.java:412)
	at com.hazelcast.client.test.TestHazelcastFactory.newHazelcastClient(TestHazelcastFactory.java:75)
	at com.hazelcast.client.ClientTimeoutTest.testTimeoutToOutsideNetwork(ClientTimeoutTest.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:622)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.lang.Thread.run(Thread.java:704)
```

**Comment by tkountis** [comment]
Looked into this, and cant see why it would spend 20 seconds before timing out. The timeout IMO is already too high, so i am a bit reluctant to increase it. On every local attempt it times out in ms.

**Comment by Donnerbart** [comment]
Maybe it's time to remove the `ParallelTest`, so the test runs in isolation.

**Comment by olukas** [comment]
It failed again on OracleJDK6: https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.maintenance-OracleJDK6/250/testReport/com.hazelcast.client/ClientTimeoutTest/testTimeoutToOutsideNetwork/

_maintenance-3.x_ (commit 250af582a595fa788d3144385f931f97fc56b771)

Stacktrace:
```
org.junit.runners.model.TestTimedOutException: test timed out after 20000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:156)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:811)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:969)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1281)
	at java.util.concurrent.FutureTask$Sync.innerGet(FutureTask.java:218)
	at java.util.concurrent.FutureTask.get(FutureTask.java:83)
	at com.hazelcast.client.connection.nio.ClusterConnector.connectToCluster(ClusterConnector.java:116)
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.connectToCluster(ClientConnectionManagerImpl.java:693)
	at com.hazelcast.client.connection.nio.DefaultClientConnectionStrategy.start(DefaultClientConnectionStrategy.java:45)
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.start(ClientConnectionManagerImpl.java:245)
	at com.hazelcast.client.impl.clientside.HazelcastClientInstanceImpl.start(HazelcastClientInstanceImpl.java:576)
	at com.hazelcast.client.test.TestHazelcastFactory.newHazelcastClient(TestHazelcastFactory.java:75)
	at com.hazelcast.client.ClientTimeoutTest.testTimeoutToOutsideNetwork(ClientTimeoutTest.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.lang.Thread.run(Thread.java:662)
```

**Comment by ahmetmircik** [comment]
closed by https://github.com/hazelcast/hazelcast/pull/14231
