### ISSUE TITLE
Restarting hazelcast docker container fails with below exception and eventually works after few attempts.

### ISSUE THREAD

**Issue by SachinB2** [hazelcast/hazelcast#13343]
We are using hazelcast to replicate web session among different instances of same service on docker swarm , endpoint mode is set as dnsrr, Though this error is not consistent but we are facing this issue quite frequently during container startup

```
Java.lang.NullPointerException: null
    at com.hazelcast.instance.DelegatingAddressPicker.validatePublicAddress(DelegatingAddressPicker.java:130)
    at com.hazelcast.instance.DelegatingAddressPicker.pickAddress(DelegatingAddressPicker.java:66)
    at com.hazelcast.instance.Node.<init>(Node.java:184)
    at com.hazelcast.instance.HazelcastInstanceImpl.createNode(HazelcastInstanceImpl.java:160)
    at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:128)
    at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:195)
    at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:174)
    at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:124)
    at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:58)
```

**Comment by jerrinot** [comment]
hi @SachinB2,
can you share your Hazelcast configuration? It looks like a bug in `MemberAddressProvider` implementation.

**Comment by SachinB2** [comment]
Hi Jaromir,
   As per our further troubleshooting, looks like issue was due to binding
by service name fails sometime during service initialization  (especially
when we have http based healthcheck, looks like docker initializes service
name as hostname after healthcheck passes)  , as alternative we implemented
network interface name based binding for hazelcast. I will try to submit
Pull Request towards this weekend.

Thanks
Sachin

**Comment by jerrinot** [comment]
@SachinB2: hello, do you have any update? is the change in Hazelcast (core)?

**Comment by SachinB2** [comment]
@Jaromir,
  Created PR#
https://github.com/bitsofinfo/hazelcast-docker-swarm-discovery-spi/pull/24

Thanks
Sachin

**Comment by mdogan** [comment]
Thanks for update @SachinB2. It seems this issue is not in Hazelcast.
