### ISSUE TITLE
Concurrency issue in TestLoggerFactory

### ISSUE THREAD

**Issue by Donnerbart** [hazelcast/hazelcast#13341]
There is a concurrency issue in `TestLoggerFactory`, when multiple loggers are created at the same time:
```java
java.lang.ArrayIndexOutOfBoundsException: 22

	at java.util.ArrayList.add(ArrayList.java:463)
	at com.hazelcast.test.TestLoggerFactory.createLogger(TestLoggerFactory.java:84)
	at com.hazelcast.logging.LoggerFactorySupport$1.createNew(LoggerFactorySupport.java:32)
	at com.hazelcast.logging.LoggerFactorySupport$1.createNew(LoggerFactorySupport.java:30)
	at com.hazelcast.util.ConcurrencyUtil.getOrPutIfAbsent(ConcurrencyUtil.java:107)
	at com.hazelcast.logging.LoggerFactorySupport.getLogger(LoggerFactorySupport.java:38)
	at com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.<init>(LoggingServiceImpl.java:153)
	at com.hazelcast.logging.LoggingServiceImpl$1.createNew(LoggingServiceImpl.java:44)
	at com.hazelcast.logging.LoggingServiceImpl$1.createNew(LoggingServiceImpl.java:40)
	at com.hazelcast.util.ConcurrencyUtil.getOrPutIfAbsent(ConcurrencyUtil.java:107)
	at com.hazelcast.logging.LoggingServiceImpl.getLogger(LoggingServiceImpl.java:75)
```

**Comment by mustafaiman** [comment]
Looks like this issue:
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-EE-pr-builder/3887/testReport/junit/com.hazelcast.client.cache.nearcache/ClientHDCacheNearCachePreloaderTest/testPreloadNearCache_withStringKeys/

**Comment by Donnerbart** [comment]
Yes, didn't see that we already have failures in Jenkins :)

I have a fix candidate for this one and another issue in the `TestLoggerFactory`.
