### ISSUE TITLE
Not an appropriate max size policy FREE_NATIVE_MEMORY_PERCENTAGE xml config is not failing fast.

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#13382]
```
<map name="mapBak1HDStoreThrough*">
        <backup-count>1</backup-count>
        <in-memory-format>NATIVE</in-memory-format>
        <eviction-policy>LRU</eviction-policy>
        <max-size policy="FREE_NATIVE_MEMORY_PERCENTAGE">15</max-size>

        <map-store enabled="true" initial-mode="EAGER">
            <class-name>hzcmd.map.store.PersonMapStore</class-name>
            <write-delay-seconds>0</write-delay-seconds>
            <properties>
                <property name="loadKeyDomain">1000</property>
                <property name="exceptionProb">0</property>
            </properties>
        </map-store>
    </map>

    <map name="mapBak1StoreThrough*">
        <backup-count>1</backup-count>
        <in-memory-format>BINARY</in-memory-format>
        <eviction-policy>LRU</eviction-policy>
        <max-size policy="FREE_NATIVE_MEMORY_PERCENTAGE">15</max-size>

        <map-store enabled="true" initial-mode="EAGER">
            <class-name>hzcmd.map.store.PersonMapStore</class-name>
            <write-delay-seconds>0</write-delay-seconds>
            <properties>
                <property name="loadKeyDomain">1000</property>
                <property name="exceptionProb">0</property>
            </properties>
        </map-store>
    </map>
```

mapBak1StoreThrough use's in-memory-format BINARY
and the incorrect config of
<max-size policy="FREE_NATIVE_MEMORY_PERCENTAGE">15</max-size>

but it is not failing fast.

**Comment by Danny-Hazelcast** [comment]
```
Jun 29, 2018 9:30:11 AM com.hazelcast.map.impl.operation.PutFromLoadAllOperation
SEVERE: [10.0.0.94]:5701 [A] [3.11-SNAPSHOT] Not an appropriate max size policy [FREE_NATIVE_MEMORY_PERCENTAGE]
java.lang.IllegalArgumentException: Not an appropriate max size policy [FREE_NATIVE_MEMORY_PERCENTAGE]
	at com.hazelcast.map.impl.eviction.EvictionChecker.checkEvictable(EvictionChecker.java:105)
	at com.hazelcast.map.impl.eviction.EvictorImpl.checkEvictable(EvictorImpl.java:106)
	at com.hazelcast.map.impl.recordstore.AbstractEvictableRecordStore.shouldEvict(AbstractEvictableRecordStore.java:174)
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.shouldEvict(DefaultRecordStore.java:83)
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.putFromLoadInternal(DefaultRecordStore.java:966)
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.putFromLoad(DefaultRecordStore.java:951)
	at com.hazelcast.map.impl.operation.PutFromLoadAllOperation.run(PutFromLoadAllOperation.java:71)
	at com.hazelcast.spi.Operation.call(Operation.java:170)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:207)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:196)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:147)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:125)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:110)

```

**Comment by Danny-Hazelcast** [comment]
```
Jun 29, 2018 9:30:18 AM com.hazelcast.map.impl.recordstore.DefaultRecordStore
SEVERE: [10.0.0.94]:5701 [A] [3.11-SNAPSHOT] Exception while loading map mapBak1StoreThrough-store
java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Not an appropriate max size policy [FREE_NATIVE_MEMORY_PERCENTA
GE]
	at com.hazelcast.util.executor.CompletableFutureTask.run(CompletableFutureTask.java:69)
	at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:227)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Not an appropriate max size policy [FREE_NATIVE_MEMORY_PERCENTAGE]
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:92)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:162)
	at com.hazelcast.map.impl.recordstore.BasicRecordStoreLoader.loadValuesInternal(BasicRecordStoreLoader.java:141)
	at com.hazelcast.map.impl.recordstore.BasicRecordStoreLoader.access$100(BasicRecordStoreLoader.java:52)
	at com.hazelcast.map.impl.recordstore.BasicRecordStoreLoader$GivenKeysLoaderTask.call(BasicRecordStoreLoader.java:109)
	at com.hazelcast.util.executor.CompletableFutureTask.run(CompletableFutureTask.java:67)
	... 6 more
Caused by: java.lang.IllegalArgumentException: Not an appropriate max size policy [FREE_NATIVE_MEMORY_PERCENTAGE]
	at com.hazelcast.map.impl.eviction.EvictionChecker.checkEvictable(EvictionChecker.java:105)
	at com.hazelcast.map.impl.eviction.EvictorImpl.checkEvictable(EvictorImpl.java:106)
	at com.hazelcast.map.impl.recordstore.AbstractEvictableRecordStore.shouldEvict(AbstractEvictableRecordStore.java:174)
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.shouldEvict(DefaultRecordStore.java:83)
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.putFromLoadInternal(DefaultRecordStore.java:966)
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.putFromLoad(DefaultRecordStore.java:951)
	at com.hazelcast.map.impl.operation.PutFromLoadAllOperation.run(PutFromLoadAllOperation.java:71)
	at com.hazelcast.spi.Operation.call(Operation.java:170)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:207)
```

**Comment by Danny-Hazelcast** [comment]
```
Jun 29, 2018 9:31:42 AM com.hazelcast.map.impl.operation.RemoveOperation
SEVERE: [10.0.0.94]:5701 [A] [3.11-SNAPSHOT] Not an appropriate max size policy [FREE_NATIVE_MEMORY_PERCENTAGE]
java.lang.IllegalArgumentException: Not an appropriate max size policy [FREE_NATIVE_MEMORY_PERCENTAGE]
	at com.hazelcast.map.impl.eviction.EvictionChecker.checkEvictable(EvictionChecker.java:105)
	at com.hazelcast.map.impl.eviction.EvictorImpl.checkEvictable(EvictorImpl.java:106)
	at com.hazelcast.map.impl.recordstore.AbstractEvictableRecordStore.shouldEvict(AbstractEvictableRecordStore.java:174)
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.shouldEvict(DefaultRecordStore.java:83)
	at com.hazelcast.map.impl.recordstore.AbstractEvictableRecordStore.evictEntries(AbstractEvictableRecordStore.java:166)
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.evictEntries(DefaultRecordStore.java:83)
	at com.hazelcast.map.impl.operation.MapOperation.evict(MapOperation.java:155)
	at com.hazelcast.map.impl.operation.BaseRemoveOperation.afterRun(BaseRemoveOperation.java:53)
	at com.hazelcast.map.impl.operation.RemoveOperation.afterRun(RemoveOperation.java:42)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.afterRun(OperationRunnerImpl.java:298)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:212)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:196)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:147)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:125)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:110)
```

**Comment by Danny-Hazelcast** [comment]
removed 
```
       <eviction-policy>LRU</eviction-policy>
       <max-size policy="FREE_NATIVE_MEMORY_PERCENTAGE">15</max-size>
```

from  "mapBak1StoreThrough* config
