### ISSUE TITLE
Setting `ExpirationTimeMergePolicy` throws exception during config validation

### ISSUE THREAD

**Issue by sertugkaya** [hazelcast/hazelcast#13392]
It works when I set it as `com.hazelcast.spi.merge.ExpirationTimeMergePolicy`
Using:
``` 
<dependency>
            <groupId>com.hazelcast</groupId>
            <artifactId>hazelcast-enterprise-all</artifactId>
            <version>3.10.2</version>
        </dependency>
        <dependency>
            <groupId>javax.cache</groupId>
            <artifactId>cache-api</artifactId>
            <version>1.1.0</version>
        </dependency>
``` 
and cache config:
``` 
    <cache name="mycache">
        <in-memory-format>NATIVE</in-memory-format>
        <backup-count>0</backup-count>
        <async-backup-count>1</async-backup-count>
        <eviction size="30" max-size-policy="FREE_NATIVE_MEMORY_PERCENTAGE" eviction-policy="LRU"/>
        <expiry-policy-factory>
            <timed-expiry-policy-factory expiry-policy-type="ACCESSED" duration-amount="60" time-unit="MINUTES"/>
        </expiry-policy-factory>
        <statistics-enabled>true</statistics-enabled>
        <merge-policy>ExpirationTimeMergePolicy</merge-policy>
    </cache>
``` 
 Related trace:
```  
Jul 02, 2018 12:16:53 PM com.hazelcast.client.connection.ClientConnectionManager
INFO: hz.client_0 [sertug] [3.10.2] Authenticated with server [127.0.0.1]:5702, server version:3.10.2 Local address: /127.0.0.1:56475
Exception in thread "main" com.hazelcast.config.InvalidConfigurationException: Merge policy must be an instance of SplitBrainMergePolicy or CacheMergePolicy, but was ExpirationTimeMergePolicy
	at com.hazelcast.internal.config.MergePolicyValidator.getMergePolicyInstance(MergePolicyValidator.java:109)
	at com.hazelcast.internal.config.MergePolicyValidator.checkCacheMergePolicy(MergePolicyValidator.java:100)
	at com.hazelcast.internal.config.ConfigValidator.checkCacheConfig(ConfigValidator.java:260)
	at com.hazelcast.internal.config.ConfigValidator.checkCacheConfig(ConfigValidator.java:242)
	at com.hazelcast.cache.impl.AbstractCacheService.createDistributedObject(AbstractCacheService.java:252)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyRegistry.doCreateProxy(ProxyRegistry.java:192)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyRegistry.createProxy(ProxyRegistry.java:185)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyServiceImpl.initializeDistributedObject(ProxyServiceImpl.java:133)
	at com.hazelcast.spi.impl.proxyservice.impl.operations.InitializeDistributedObjectOperation.run(InitializeDistributedObjectOperation.java:44)
	at com.hazelcast.spi.Operation.call(Operation.java:148)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:202)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:191)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:406)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:433)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:581)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:566)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:525)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:215)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:60)
	at com.hazelcast.client.impl.protocol.task.AbstractInvocationMessageTask.processMessage(AbstractInvocationMessageTask.java:40)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:123)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.doRun(AbstractMessageTask.java:111)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:101)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:127)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run(AbstractInvocationFuture.java:250)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:96)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:33)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:162)
	at com.hazelcast.client.spi.ProxyManager.initialize(ProxyManager.java:436)
	at com.hazelcast.client.spi.ProxyManager.initializeWithRetry(ProxyManager.java:395)
	at com.hazelcast.client.spi.ProxyManager.getOrCreateProxy(ProxyManager.java:316)
	at com.hazelcast.client.impl.HazelcastClientInstanceImpl.getDistributedObject(HazelcastClientInstanceImpl.java:707)
	at com.hazelcast.client.impl.ClientICacheManager.getCacheByFullName(ClientICacheManager.java:53)
	at com.hazelcast.client.impl.ClientICacheManager.getCache(ClientICacheManager.java:47)
	at Client.main(Client.java:19)
Caused by: java.lang.ClassNotFoundException: ExpirationTimeMergePolicy
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at com.hazelcast.nio.ClassLoaderUtil.tryLoadClass(ClassLoaderUtil.java:173)
	at com.hazelcast.nio.ClassLoaderUtil.loadClass(ClassLoaderUtil.java:147)
	at com.hazelcast.nio.ClassLoaderUtil.newInstance(ClassLoaderUtil.java:101)
	at com.hazelcast.cache.impl.merge.policy.CacheMergePolicyProvider$1.createNew(CacheMergePolicyProvider.java:45)
	at com.hazelcast.cache.impl.merge.policy.CacheMergePolicyProvider$1.createNew(CacheMergePolicyProvider.java:41)
	at com.hazelcast.util.ConcurrencyUtil.getOrPutIfAbsent(ConcurrencyUtil.java:107)
	at com.hazelcast.cache.impl.merge.policy.CacheMergePolicyProvider.getMergePolicy(CacheMergePolicyProvider.java:91)
	at com.hazelcast.internal.config.MergePolicyValidator.getMergePolicyInstance(MergePolicyValidator.java:106)
	at com.hazelcast.internal.config.MergePolicyValidator.checkCacheMergePolicy(MergePolicyValidator.java:100)
	at com.hazelcast.internal.config.ConfigValidator.checkCacheConfig(ConfigValidator.java:260)
	at com.hazelcast.internal.config.ConfigValidator.checkCacheConfig(ConfigValidator.java:242)
	at com.hazelcast.cache.impl.AbstractCacheService.createDistributedObject(AbstractCacheService.java:252)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyRegistry.doCreateProxy(ProxyRegistry.java:192)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyRegistry.createProxy(ProxyRegistry.java:185)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyServiceImpl.initializeDistributedObject(ProxyServiceImpl.java:133)
	at com.hazelcast.spi.impl.proxyservice.impl.operations.InitializeDistributedObjectOperation.run(InitializeDistributedObjectOperation.java:44)
	at com.hazelcast.spi.Operation.call(Operation.java:148)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:202)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:191)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:406)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:433)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:581)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:566)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:525)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:215)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:60)
	at com.hazelcast.client.impl.protocol.task.AbstractInvocationMessageTask.processMessage(AbstractInvocationMessageTask.java:40)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:123)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.doRun(AbstractMessageTask.java:111)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:101)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
```

**Comment by Donnerbart** [comment]
The `ExpirationTimeMergePolicy` has been added very late in the process, since I needed a merge policy, which didn't work for all data structures. But I forgot to add it to the `SplitBrainMergePolicyProvider`, so it doesn't work with the short classname, like the other out-of-the-box merge policies. It's easy to fix, sorry for the inconvenience.
