### ISSUE TITLE
MergePolicyProviderConstructorTest.testConstructor failure

### ISSUE THREAD

**Issue by Holmistr** [hazelcast/hazelcast#13519]
*master* (commit c32a53bcb94235a3f59791b792ca07bdd89d63e4)

Failed on nightly build: https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/165/testReport/junit/com.hazelcast.test.starter.constructor.test/MergePolicyProviderConstructorTest/testConstructor/

Stacktrace:
```
com.hazelcast.test.starter.GuardianException: Cannot download file from https://repo1.maven.org/maven2/com/hazelcast/hazelcast/3.11-SNAPSHOT/hazelcast-3.11-SNAPSHOT.jar, http response code: 404
	at com.hazelcast.test.starter.HazelcastVersionLocator.downloadFile(HazelcastVersionLocator.java:139)
	at com.hazelcast.test.starter.HazelcastVersionLocator.downloadMember(HazelcastVersionLocator.java:113)
	at com.hazelcast.test.starter.HazelcastVersionLocator.locateMember(HazelcastVersionLocator.java:78)
	at com.hazelcast.test.starter.HazelcastVersionLocator.locateVersion(HazelcastVersionLocator.java:61)
	at com.hazelcast.test.starter.HazelcastStarter$HazelcastVersionClassloaderFuture.get(HazelcastStarter.java:343)
	at com.hazelcast.test.starter.HazelcastStarter.getTargetVersionClassloader(HazelcastStarter.java:210)
	at com.hazelcast.test.starter.HazelcastStarter.newHazelcastInstance(HazelcastStarter.java:101)
	at com.hazelcast.test.starter.constructor.test.MergePolicyProviderConstructorTest.setUp(MergePolicyProviderConstructorTest.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:416)
	at com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37)
	at com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:104)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:50)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:29)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at com.hazelcast.test.AbstractHazelcastClassRunner$3.evaluate(AbstractHazelcastClassRunner.java:335)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:107)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:83)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:379)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:340)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:413)
```

**Comment by jerrinot** [comment]
The tries to access Hazelcast `3.11-SNAPSHOT`. Snapshot versions are not in Maven Central. The test works locally because it first tries to does a lookup into a local Maven repo. This normally passes on a local, but not necessary on Jenkins - it depends on a state of the local repo. 

However the bigger question is whether a test should depend on a snapshot version in the first place - it makes it non-repeatable. Let me have a look what is it actually doing.

**Comment by Holmistr** [comment]
Fixed by: https://github.com/hazelcast/hazelcast/pull/13542
