### ISSUE TITLE
SetBasicDistributedTest.testNameBasedAffinity failure

### ISSUE THREAD

**Issue by Holmistr** [hazelcast/hazelcast#13588]
*maintenance* (commit bee5a9667eda77cd6a694337ca9b682413be831e)

Failed on IBM JDK7: https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.maintenance-IbmJDK7/114/testReport/com.hazelcast.collection.impl.set/SetBasicDistributedTest/testNameBasedAffinity/

Stacktrace:
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.io.BufferedInputStream.<init>(BufferedInputStream.java:207)
	at java.io.BufferedInputStream.<init>(BufferedInputStream.java:187)
	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:104)
	at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:202)
	at java.net.URL.openStream(URL.java:1061)
	at com.hazelcast.util.ServiceLoader.parse(ServiceLoader.java:132)
	at com.hazelcast.util.ServiceLoader.getServiceDefinitions(ServiceLoader.java:92)
	at com.hazelcast.util.ServiceLoader.classIterator(ServiceLoader.java:78)
	at com.hazelcast.util.ServiceLoader.iterator(ServiceLoader.java:72)
	at com.hazelcast.internal.serialization.impl.PortableHookLoader.load(PortableHookLoader.java:49)
	at com.hazelcast.internal.serialization.impl.PortableHookLoader.<init>(PortableHookLoader.java:44)
	at com.hazelcast.internal.serialization.impl.SerializationServiceV1.<init>(SerializationServiceV1.java:89)
	at com.hazelcast.internal.serialization.impl.SerializationServiceV1$Builder.build(SerializationServiceV1.java:313)
	at com.hazelcast.internal.serialization.impl.DefaultSerializationServiceBuilder.createSerializationService(DefaultSerializationServiceBuilder.java:290)
	at com.hazelcast.internal.serialization.impl.DefaultSerializationServiceBuilder.build(DefaultSerializationServiceBuilder.java:243)
	at com.hazelcast.internal.serialization.impl.DefaultSerializationServiceBuilder.build(DefaultSerializationServiceBuilder.java:56)
	at com.hazelcast.instance.DefaultNodeExtension.createSerializationService(DefaultNodeExtension.java:188)
	at com.hazelcast.instance.Node.<init>(Node.java:209)
	at com.hazelcast.instance.HazelcastInstanceImpl.createNode(HazelcastInstanceImpl.java:164)
	at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:132)
	at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:196)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:175)
	at com.hazelcast.test.TestHazelcastInstanceFactory.newHazelcastInstance(TestHazelcastInstanceFactory.java:112)
	at com.hazelcast.collection.impl.set.SetBasicDistributedTest.newInstances(SetBasicDistributedTest.java:42)
	at com.hazelcast.collection.impl.set.SetAbstractTest.testNameBasedAffinity(SetAbstractTest.java:285)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:95)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:56)
	at java.lang.reflect.Method.invoke(Method.java:620)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask.run(FutureTask.java:274)
	at java.lang.Thread.run(Thread.java:809)
```

Standard output:
```
BuildInfo right after testNameBasedAffinity(com.hazelcast.collection.impl.set.SetBasicDistributedTest): BuildInfo{version='3.10.5-SNAPSHOT', build='20180814', buildNumber=20180814, revision=bee5a96, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'testNameBasedAffinity(com.hazelcast.collection.impl.set.SetBasicDistributedTest):'
10:52:10, accumulated pauses: 1349 ms, max pause: 589 ms, pauses over 1000 ms: 0
10:52:15, accumulated pauses: 4537 ms, max pause: 1607 ms, pauses over 1000 ms: 2
10:52:20, accumulated pauses: 4327 ms, max pause: 982 ms, pauses over 1000 ms: 0
10:52:25, accumulated pauses: 6303 ms, max pause: 1927 ms, pauses over 1000 ms: 3
10:52:30, accumulated pauses: 3766 ms, max pause: 1673 ms, pauses over 1000 ms: 2
10:52:35, accumulated pauses: 4859 ms, max pause: 1862 ms, pauses over 1000 ms: 3
10:52:40, accumulated pauses: 4803 ms, max pause: 1869 ms, pauses over 1000 ms: 3
10:52:45, accumulated pauses: 5093 ms, max pause: 1893 ms, pauses over 1000 ms: 3
10:52:50, accumulated pauses: 5881 ms, max pause: 1757 ms, pauses over 1000 ms: 4
10:52:55, accumulated pauses: 4211 ms, max pause: 1874 ms, pauses over 1000 ms: 3
10:53:00, accumulated pauses: 4873 ms, max pause: 3181 ms, pauses over 1000 ms: 2
10:53:05, accumulated pauses: 4893 ms, max pause: 1550 ms, pauses over 1000 ms: 3
10:53:10, accumulated pauses: 5122 ms, max pause: 1940 ms, pauses over 1000 ms: 3
10:53:15, accumulated pauses: 6500 ms, max pause: 1911 ms, pauses over 1000 ms: 3
10:53:20, accumulated pauses: 3103 ms, max pause: 1460 ms, pauses over 1000 ms: 2
10:53:25, accumulated pauses: 5891 ms, max pause: 1882 ms, pauses over 1000 ms: 2
10:53:30, accumulated pauses: 4211 ms, max pause: 1877 ms, pauses over 1000 ms: 2
10:53:35, accumulated pauses: 5245 ms, max pause: 1899 ms, pauses over 1000 ms: 2
10:53:40, accumulated pauses: 4622 ms, max pause: 1822 ms, pauses over 1000 ms: 3
10:53:45, accumulated pauses: 4772 ms, max pause: 1970 ms, pauses over 1000 ms: 3
10:53:50, accumulated pauses: 5735 ms, max pause: 1767 ms, pauses over 1000 ms: 3
10:53:55, accumulated pauses: 4880 ms, max pause: 1696 ms, pauses over 1000 ms: 3
10:54:00, accumulated pauses: 5179 ms, max pause: 1598 ms, pauses over 1000 ms: 3
10:54:05, accumulated pauses: 5241 ms, max pause: 1704 ms, pauses over 1000 ms: 3
10:54:10, accumulated pauses: 5142 ms, max pause: 1668 ms, pauses over 1000 ms: 3
10:54:15, accumulated pauses: 3547 ms, max pause: 860 ms, pauses over 1000 ms: 0
10:54:20, accumulated pauses: 5877 ms, max pause: 1753 ms, pauses over 1000 ms: 3
10:54:25, accumulated pauses: 4978 ms, max pause: 1393 ms, pauses over 1000 ms: 3
10:54:30, accumulated pauses: 4274 ms, max pause: 1763 ms, pauses over 1000 ms: 2
10:54:35, accumulated pauses: 4973 ms, max pause: 1713 ms, pauses over 1000 ms: 3
10:54:40, accumulated pauses: 4911 ms, max pause: 1642 ms, pauses over 1000 ms: 3
10:54:45, accumulated pauses: 4835 ms, max pause: 1692 ms, pauses over 1000 ms: 3
10:54:50, accumulated pauses: 5788 ms, max pause: 1474 ms, pauses over 1000 ms: 4
10:54:55, accumulated pauses: 3956 ms, max pause: 1710 ms, pauses over 1000 ms: 2
10:55:00, accumulated pauses: 5580 ms, max pause: 1654 ms, pauses over 1000 ms: 3
10:55:05, accumulated pauses: 4453 ms, max pause: 1387 ms, pauses over 1000 ms: 1
10:55:10, accumulated pauses: 6049 ms, max pause: 1551 ms, pauses over 1000 ms: 3
10:55:15, accumulated pauses: 3949 ms, max pause: 1582 ms, pauses over 1000 ms: 3
10:55:20, accumulated pauses: 5294 ms, max pause: 1611 ms, pauses over 1000 ms: 2
10:55:25, accumulated pauses: 5053 ms, max pause: 1640 ms, pauses over 1000 ms: 3
10:55:30, accumulated pauses: 5149 ms, max pause: 1544 ms, pauses over 1000 ms: 3
10:55:35, accumulated pauses: 5150 ms, max pause: 1501 ms, pauses over 1000 ms: 2
10:55:40, accumulated pauses: 4144 ms, max pause: 801 ms, pauses over 1000 ms: 0
10:55:45, accumulated pauses: 5689 ms, max pause: 1238 ms, pauses over 1000 ms: 3
10:55:50, accumulated pauses: 4232 ms, max pause: 1438 ms, pauses over 1000 ms: 2
10:55:55, accumulated pauses: 5396 ms, max pause: 1305 ms, pauses over 1000 ms: 3
10:56:00, accumulated pauses: 4448 ms, max pause: 1284 ms, pauses over 1000 ms: 3
10:56:05, accumulated pauses: 5017 ms, max pause: 1351 ms, pauses over 1000 ms: 2
10:56:10, accumulated pauses: 5284 ms, max pause: 1501 ms, pauses over 1000 ms: 3
10:56:15, accumulated pauses: 4559 ms, max pause: 1214 ms, pauses over 1000 ms: 1
10:56:20, accumulated pauses: 4484 ms, max pause: 1280 ms, pauses over 1000 ms: 2
10:56:25, accumulated pauses: 6000 ms, max pause: 1345 ms, pauses over 1000 ms: 3
10:56:30, accumulated pauses: 3919 ms, max pause: 1349 ms, pauses over 1000 ms: 2
10:56:35, accumulated pauses: 5351 ms, max pause: 1314 ms, pauses over 1000 ms: 4
10:56:40, accumulated pauses: 4975 ms, max pause: 1178 ms, pauses over 1000 ms: 3
10:56:45, accumulated pauses: 5475 ms, max pause: 1359 ms, pauses over 1000 ms: 2
10:56:50, accumulated pauses: 4091 ms, max pause: 1066 ms, pauses over 1000 ms: 1
10:56:55, accumulated pauses: 5017 ms, max pause: 1124 ms, pauses over 1000 ms: 3
10:57:00, accumulated pauses: 4710 ms, max pause: 1311 ms, pauses over 1000 ms: 1
10:57:05, accumulated pauses: 5264 ms, max pause: 1208 ms, pauses over 1000 ms: 3
10:57:10, accumulated pauses: 4873 ms, max pause: 1312 ms, pauses over 1000 ms: 2
10:57:15, accumulated pauses: 946 ms, max pause: 946 ms, pauses over 1000 ms: 0
10:58:20, accumulated pauses: 69115 ms, max pause: 69115 ms, pauses over 1000 ms: 1
10:58:25, accumulated pauses: 4900 ms, max pause: 1271 ms, pauses over 1000 ms: 3
10:58:30, accumulated pauses: 4941 ms, max pause: 1142 ms, pauses over 1000 ms: 2
10:58:35, accumulated pauses: 5201 ms, max pause: 1092 ms, pauses over 1000 ms: 2
10:58:40, accumulated pauses: 4480 ms, max pause: 1167 ms, pauses over 1000 ms: 1
10:58:45, accumulated pauses: 5254 ms, max pause: 1127 ms, pauses over 1000 ms: 2
10:58:50, accumulated pauses: 4847 ms, max pause: 1122 ms, pauses over 1000 ms: 3
10:58:55, accumulated pauses: 4492 ms, max pause: 1058 ms, pauses over 1000 ms: 3
10:59:00, accumulated pauses: 5541 ms, max pause: 1086 ms, pauses over 1000 ms: 2
10:59:05, accumulated pauses: 4228 ms, max pause: 1058 ms, pauses over 1000 ms: 1
10:59:10, accumulated pauses: 5417 ms, max pause: 1102 ms, pauses over 1000 ms: 1
10:59:15, accumulated pauses: 4636 ms, max pause: 954 ms, pauses over 1000 ms: 0
10:59:20, accumulated pauses: 4579 ms, max pause: 919 ms, pauses over 1000 ms: 0
10:59:25, accumulated pauses: 5493 ms, max pause: 946 ms, pauses over 1000 ms: 0
10:59:30, accumulated pauses: 5024 ms, max pause: 921 ms, pauses over 1000 ms: 0
10:59:35, accumulated pauses: 4337 ms, max pause: 928 ms, pauses over 1000 ms: 0
10:59:40, accumulated pauses: 5114 ms, max pause: 827 ms, pauses over 1000 ms: 0
10:59:45, accumulated pauses: 4719 ms, max pause: 1027 ms, pauses over 1000 ms: 2
10:59:50, accumulated pauses: 4993 ms, max pause: 1018 ms, pauses over 1000 ms: 1
10:59:55, accumulated pauses: 4884 ms, max pause: 905 ms, pauses over 1000 ms: 0
11:00:00, accumulated pauses: 5367 ms, max pause: 965 ms, pauses over 1000 ms: 0
11:00:05, accumulated pauses: 4622 ms, max pause: 905 ms, pauses over 1000 ms: 0
11:00:10, accumulated pauses: 4983 ms, max pause: 1241 ms, pauses over 1000 ms: 1
11:00:15, accumulated pauses: 4862 ms, max pause: 862 ms, pauses over 1000 ms: 0
11:00:20, accumulated pauses: 4570 ms, max pause: 919 ms, pauses over 1000 ms: 0
11:00:25, accumulated pauses: 5152 ms, max pause: 781 ms, pauses over 1000 ms: 0
11:00:30, accumulated pauses: 5024 ms, max pause: 822 ms, pauses over 1000 ms: 0
11:00:35, accumulated pauses: 4737 ms, max pause: 761 ms, pauses over 1000 ms: 0
11:00:40, accumulated pauses: 5433 ms, max pause: 839 ms, pauses over 1000 ms: 0
11:00:45, accumulated pauses: 4471 ms, max pause: 892 ms, pauses over 1000 ms: 0
11:00:50, accumulated pauses: 4844 ms, max pause: 776 ms, pauses over 1000 ms: 0
11:00:55, accumulated pauses: 4903 ms, max pause: 753 ms, pauses over 1000 ms: 0
11:01:00, accumulated pauses: 4892 ms, max pause: 697 ms, pauses over 1000 ms: 0
11:01:05, accumulated pauses: 4545 ms, max pause: 655 ms, pauses over 1000 ms: 0
11:01:10, accumulated pauses: 5159 ms, max pause: 647 ms, pauses over 1000 ms: 0
11:01:15, accumulated pauses: 5073 ms, max pause: 609 ms, pauses over 1000 ms: 0
11:01:20, accumulated pauses: 4783 ms, max pause: 563 ms, pauses over 1000 ms: 0
11:01:25, accumulated pauses: 4711 ms, max pause: 537 ms, pauses over 1000 ms: 0
11:01:30, accumulated pauses: 4773 ms, max pause: 560 ms, pauses over 1000 ms: 0
11:01:35, accumulated pauses: 4848 ms, max pause: 499 ms, pauses over 1000 ms: 0
11:01:40, accumulated pauses: 4773 ms, max pause: 517 ms, pauses over 1000 ms: 0
11:01:45, accumulated pauses: 4774 ms, max pause: 500 ms, pauses over 1000 ms: 0
11:01:50, accumulated pauses: 4725 ms, max pause: 458 ms, pauses over 1000 ms: 0
11:01:55, accumulated pauses: 4818 ms, max pause: 426 ms, pauses over 1000 ms: 0
11:02:00, accumulated pauses: 4776 ms, max pause: 390 ms, pauses over 1000 ms: 0
11:02:05, accumulated pauses: 4776 ms, max pause: 352 ms, pauses over 1000 ms: 0
11:02:10, accumulated pauses: 4797 ms, max pause: 311 ms, pauses over 1000 ms: 0
11:02:15, accumulated pauses: 4758 ms, max pause: 266 ms, pauses over 1000 ms: 0
11:02:20, accumulated pauses: 4490 ms, max pause: 205 ms, pauses over 1000 ms: 0
11:02:25, accumulated pauses: 4534 ms, max pause: 198 ms, pauses over 1000 ms: 0
11:02:30, accumulated pauses: 4341 ms, max pause: 126 ms, pauses over 1000 ms: 0
11:02:35, accumulated pauses: 2579 ms, max pause: 85 ms, pauses over 1000 ms: 0
11:02:40, accumulated pauses: 25 ms, max pause: 0 ms, pauses over 1000 ms: 0
```

**Comment by Holmistr** [comment]
After investigation with @taburet , we suspect issues in the build environment. Based on the GC log analysis and measured hiccups (very extreme!), it seems that IBM JDK 7 in particular is more demanding and needs some extra memory. Attempting to fix this issue by adjusting the heap size of the builds. Closing for now.
