### ISSUE TITLE
MapMaxAggregationTest.testBigIntegerMax failure

### ISSUE THREAD

**Issue by Holmistr** [hazelcast/hazelcast#13589]
*master* (commit f1af3ea29490e9d163bf97ae5a6519a1fdf823f7)

Failed on Zulu JDK9: https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-ZuluJDK9/2/testReport/junit/com.hazelcast.mapreduce.aggregation/MapMaxAggregationTest/testBigIntegerMax/

Also other test methods failing:
MultiMapMaxAggregationTest.testBigIntegerMaxWithExtractor
MultiMapMaxAggregationTest.testBigIntegerMax

Stacktrace:
```
java.lang.AssertionError: expected:<11999> but was:<null>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.mapreduce.aggregation.MapMaxAggregationTest.testBigIntegerMax(MapMaxAggregationTest.java:101)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

Standard output:
```
Hiccups measured while running test 'testBigIntegerMax(com.hazelcast.mapreduce.aggregation.MapMaxAggregationTest):'
13:57:15, accumulated pauses: 482 ms, max pause: 468 ms, pauses over 1000 ms: 0
```

**Comment by Holmistr** [comment]
Failing on Oracle JDK9 as well: https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-OracleJDK9/8/testReport/

**Comment by taburet** [comment]
Closing because of:

1. The map-reduce feature is deprecated approaching its end-of-life phase and we are not supposed to fix flaky tests for it.

2. We were running the map-reduce test suite by mistake, https://github.com/hazelcast/hazelcast/pull/13634 fixes this. We still going to run the suite in a separate build with relaxed flaky test policy just to make sure we are not breaking map-reduce completely.
