### ISSUE TITLE
fast path plugin not working with hazelcast

### ISSUE THREAD

**Issue by ashish6793** [hazelcast/hazelcast#13609]
below error is coming when agent accepted the chat.
```
Aug 21, 2018 7:49:49 PM com.hazelcast.impl.ListenerManager
SEVERE: [10.140.72.41]:5701 [openfire] Caught error while calling event listener; cause: null
java.lang.NullPointerException
	at com.jivesoftware.util.cache.ClusterListener$DirectedPresenceListener.entryUpdated(ClusterListener.java:439)
	at com.hazelcast.impl.ListenerManager.callListener(ListenerManager.java:398)
	at com.hazelcast.impl.ListenerManager.callListeners(ListenerManager.java:334)
	at com.hazelcast.impl.BaseManager$2.run(BaseManager.java:1391)
	at com.hazelcast.impl.executor.ParallelExecutorService$ParallelExecutorImpl$ExecutionSegment.run(ParallelExecutorService.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
	at com.hazelcast.impl.ExecutorThreadFactory$1.run(ExecutorThreadFactory.java:38) 
```

**Comment by jerrinot** [comment]
this looks like a bug in the Openfire plugin. The plugin is not maintained by Hazelcast. Moreover it appears you are using an old version of the plugin. Please try to use the latest version. If it does not help then please open a new issue at the [Openfire issue tracker](https://issues.igniterealtime.org/projects/OF/issues/OF-1594?filter=allopenissues)
