### ISSUE TITLE
CacheExpirationTest.test_whenEntryIsRemovedBackupIsCleaned failure

### ISSUE THREAD

**Issue by Holmistr** [hazelcast/hazelcast#13619]
*master* (commit d5b4547109b77483621639d5a1248ffda295984a)

Failed on Oracle JDK6: https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-OracleJDK6/487/testReport/junit/com.hazelcast.cache.eviction/CacheExpirationTest/test_whenEntryIsRemovedBackupIsCleaned/

Stacktrace:
```
java.lang.AssertionError: expected:<0> but was:<1>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.cache.eviction.CacheExpirationTest.test_whenEntryIsRemovedBackupIsCleaned(CacheExpirationTest.java:275)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.lang.Thread.run(Thread.java:662)
```

Standard output:
```
Hiccups measured while running test 'test_whenEntryIsRemovedBackupIsCleaned(com.hazelcast.cache.eviction.CacheExpirationTest):'
05:52:10, accumulated pauses: 2744 ms, max pause: 2449 ms, pauses over 1000 ms: 1
05:52:15, accumulated pauses: 770 ms, max pause: 458 ms, pauses over 1000 ms: 0
05:52:20, accumulated pauses: 0 ms, max pause: 0 ms, pauses over 1000 ms: 0
```

**Comment by kwart** [comment]
Reopening due to
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-pr-builder/16850/testReport/junit/com.hazelcast.cache.eviction/CacheExpirationTest/test_whenEntryIsRemovedBackupIsCleaned/
and sending backport to 3.11-BETA-1: #13633

**Comment by Holmistr** [comment]
@kwart You didn't really have to create a backport to 3.11-BETA-1 as we agreed that we should backport only important stuff now. But since you have already created it, let's merge it unless @jerrinot has objections.

**Comment by Holmistr** [comment]
*master* (commit 8da8b845ee5c32d8d12eddfb191ce61595a729ac)

Reopening as it failed again on Sonar build: https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-sonar/202/testReport/junit/com.hazelcast.cache.eviction/CacheExpirationTest/test_whenEntryIsRemovedBackupIsCleaned/

Stacktrace:
```
java.lang.AssertionError: expected:<0> but was:<1>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.cache.eviction.CacheExpirationTest.test_whenEntryIsRemovedBackupIsCleaned(CacheExpirationTest.java:275)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

Standard output:
```
Hiccups measured while running test 'test_whenEntryIsRemovedBackupIsCleaned(com.hazelcast.cache.eviction.CacheExpirationTest):'
22:31:35, accumulated pauses: 209 ms, max pause: 56 ms, pauses over 1000 ms: 0
22:31:40, accumulated pauses: 304 ms, max pause: 61 ms, pauses over 1000 ms: 0
22:31:45, accumulated pauses: 121 ms, max pause: 29 ms, pauses over 1000 ms: 0
22:31:50, accumulated pauses: 400 ms, max pause: 361 ms, pauses over 1000 ms: 0
22:31:55, accumulated pauses: 7 ms, max pause: 0 ms, pauses over 1000 ms: 0
```

**Comment by blazember** [comment]
Another failure in the PR builder: https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-pr-builder/16961/testReport/junit/com.hazelcast.cache.eviction/CacheExpirationTest/test_whenEntryIsRemovedBackupIsCleaned/

```
java.lang.AssertionError: expected:<0> but was:<1>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.cache.eviction.CacheExpirationTest.test_whenEntryIsRemovedBackupIsCleaned(CacheExpirationTest.java:275)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```
Hiccups:
```
23:28:10, accumulated pauses: 625 ms, max pause: 195 ms, pauses over 1000 ms: 0
23:28:15, accumulated pauses: 656 ms, max pause: 143 ms, pauses over 1000 ms: 0
23:28:20, accumulated pauses: 672 ms, max pause: 136 ms, pauses over 1000 ms: 0
23:28:25, accumulated pauses: 414 ms, max pause: 61 ms, pauses over 1000 ms: 0
23:28:30, accumulated pauses: 551 ms, max pause: 181 ms, pauses over 1000 ms: 0
```

**Comment by Holmistr** [comment]
More failures on master, just in case for need of more information: https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-sonar/214/testReport/com.hazelcast.cache.eviction/CacheExpirationTest/test_whenEntryIsRemovedBackupIsCleaned/

**Comment by mmedenjak** [comment]
I'm suspecting the problem here is that the TTL test is inherently racy. It assumes that if it puts entries and immediately removes it, none of them will have time to expire. But if there is a pause or a clock jump, some of the entries might have already been expired.

**Comment by vbekiaris** [comment]
Failed in http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/4658:
```
java.lang.AssertionError: Expected to remove entry 0 but entry was not present. Expired entry count: 1
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.cache.eviction.CacheExpirationTest.test_whenEntryIsRemovedBackupIsCleaned(CacheExpirationTest.java:350)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```
