### ISSUE TITLE
SelectNow_TcpIpConnection_BasicTest.lastReadTimeMillis failure

### ISSUE THREAD

**Issue by Holmistr** [hazelcast/hazelcast#13617]
*maintenance* (commit b76ef08d6b124647863b520569ff63266bc154ba)

Failed on Zing JDK7: https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.maintenance-ZingJDK7/48/testReport/junit/com.hazelcast.internal.networking.nio/SelectNow_TcpIpConnection_BasicTest/lastReadTimeMillis/

Stacktrace:
```
java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:463)
	at sun.nio.ch.Net.bind(Net.java:455)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:67)
	at com.hazelcast.nio.tcp.MockIOService.<init>(MockIOService.java:67)
	at com.hazelcast.nio.tcp.TcpIpConnection_AbstractTest.newConnectionManager(TcpIpConnection_AbstractTest.java:114)
	at com.hazelcast.nio.tcp.TcpIpConnection_AbstractTest.setup(TcpIpConnection_AbstractTest.java:80)
	at com.hazelcast.nio.tcp.TcpIpConnection_AbstractBasicTest.setup(TcpIpConnection_AbstractBasicTest.java:49)
	at com.hazelcast.internal.networking.nio.SelectNow_TcpIpConnection_BasicTest.setup(SelectNow_TcpIpConnection_BasicTest.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:416)
	at com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37)
	at com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:104)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:50)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:29)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at com.hazelcast.test.AbstractHazelcastClassRunner$3.evaluate(AbstractHazelcastClassRunner.java:335)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:107)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:83)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:379)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:340)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:413)
```

Standard output:
```
Hiccups measured while running test 'lastReadTimeMillis(com.hazelcast.internal.networking.nio.SelectNow_TcpIpConnection_BasicTest):'
05:35:55, accumulated pauses: 2020 ms, max pause: 48 ms, pauses over 1000 ms: 0
```

**Comment by Holmistr** [comment]
Probably related to https://github.com/hazelcast/hazelcast/issues/13713 .

**Comment by blazember** [comment]
New failure: https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-pr-builder/17031/
The description is the same.

**Comment by blazember** [comment]
A strange observation is made that jenkins show double test case executions. See comment [here](https://github.com/hazelcast/hazelcast/issues/13713#issuecomment-419875819).

**Comment by Holmistr** [comment]
Another test failure on Zing JDK7:
com.hazelcast.internal.networking.nio.SelectNow_TcpIpConnection_BasicTest.write_whenNotAlive

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.maintenance-ZingJDK7/58/testReport/junit/com.hazelcast.internal.networking.nio/SelectNow_TcpIpConnection_BasicTest/write_whenNotAlive/

Whole standard output:
```
Finished Running Test: getPort in 0.302 seconds.
Started Running Test: write_whenNotAlive
05:35:45,775  INFO |write_whenNotAlive| - [NioEventLoopGroup] main - [LOCAL] [somegroup] [3.10.6-SNAPSHOT] IO threads selector mode is SELECT_NOW
05:35:45,776  WARN |write_whenNotAlive| - [IOBalancer] main - [LOCAL] [somegroup] [3.10.6-SNAPSHOT] I/O Balancer is disabled as the 'hazelcast.io.balancer.interval.seconds' property is set to 0. Set the property to a value larger than 0 to enable the I/O Balancer.
05:35:45,776  INFO |write_whenNotAlive| - [NioEventLoopGroup] main - [LOCAL] [somegroup] [3.10.6-SNAPSHOT] IO threads selector mode is SELECT_NOW
05:35:45,777  WARN |write_whenNotAlive| - [IOBalancer] main - [LOCAL] [somegroup] [3.10.6-SNAPSHOT] I/O Balancer is disabled as the 'hazelcast.io.balancer.interval.seconds' property is set to 0. Set the property to a value larger than 0 to enable the I/O Balancer.
05:35:45,777  INFO |write_whenNotAlive| - [NioEventLoopGroup] main - [LOCAL] [somegroup] [3.10.6-SNAPSHOT] IO threads selector mode is SELECT_NOW
05:35:45,778  WARN |write_whenNotAlive| - [IOBalancer] main - [LOCAL] [somegroup] [3.10.6-SNAPSHOT] I/O Balancer is disabled as the 'hazelcast.io.balancer.interval.seconds' property is set to 0. Set the property to a value larger than 0 to enable the I/O Balancer.
05:35:45,826  INFO |write_whenNotAlive| - [TcpIpConnector] Thread-5848 - [LOCAL] [somegroup] [3.10.6-SNAPSHOT] Connecting to /127.0.0.1:5702, timeout: 0, bind-any: true
05:35:45,826  INFO |write_whenNotAlive| - [TcpIpConnectionManager] Thread-5848 - [LOCAL] [somegroup] [3.10.6-SNAPSHOT] Established socket connection between /127.0.0.1:53166 and /127.0.0.1:5702
05:35:45,827  INFO |write_whenNotAlive| - [MockIOService] Thread-5848 - [LOCAL] [somegroup] [3.10.6-SNAPSHOT] Successful connection: [127.0.0.1]:5702
05:35:45,831  INFO |write_whenNotAlive| - [TcpIpAcceptor] hz.hz.IO.thread-Acceptor - [LOCAL] [somegroup] [3.10.6-SNAPSHOT] Accepting socket connection from /127.0.0.1:53166
05:35:45,831  INFO |write_whenNotAlive| - [TcpIpConnectionManager] hz.hz.IO.thread-Acceptor - [LOCAL] [somegroup] [3.10.6-SNAPSHOT] Established socket connection between /127.0.0.1:5702 and /127.0.0.1:53166
05:35:45,845  INFO |write_whenNotAlive| - [MockIOService] hz.hz.IO.thread-in-0 - [LOCAL] [somegroup] [3.10.6-SNAPSHOT] Successful connection: [127.0.0.1]:5701
05:35:45,845  INFO |write_whenNotAlive| - [MockIOService] hz.hz.IO.thread-in-0 - [LOCAL] [somegroup] [3.10.6-SNAPSHOT] Successful connection: [127.0.0.1]:5701
05:35:45,851  INFO |write_whenNotAlive| - [MockIOService] hz.hz.IO.thread-in-0 - [LOCAL] [somegroup] [3.10.6-SNAPSHOT] Successful connection: [127.0.0.1]:5702
05:35:46,014  INFO |write_whenNotAlive| - [TcpIpConnection] write_whenNotAlive - [LOCAL] [somegroup] [3.10.6-SNAPSHOT] Connection[id=1, /127.0.0.1:53166->/127.0.0.1:5702, endpoint=[127.0.0.1]:5702, alive=false, type=MEMBER] closed. Reason: Socket explicitly closed
05:35:46,014  INFO |write_whenNotAlive| - [TcpIpConnection] hz.hz.IO.thread-in-0 - [LOCAL] [somegroup] [3.10.6-SNAPSHOT] Connection[id=1, /127.0.0.1:5702->/127.0.0.1:53166, endpoint=[127.0.0.1]:5701, alive=false, type=MEMBER] closed. Reason: Connection closed by the other side
05:35:46,014  WARN |write_whenNotAlive| - [MockIOService] write_whenNotAlive - [LOCAL] [somegroup] [3.10.6-SNAPSHOT] Disconnected address: [127.0.0.1]:5702
05:35:46,014  WARN |write_whenNotAlive| - [MockIOService] hz.hz.IO.thread-in-0 - [LOCAL] [somegroup] [3.10.6-SNAPSHOT] Disconnected address: [127.0.0.1]:5701
java.io.EOFException: Remote socket closed!
	at com.hazelcast.internal.networking.nio.NioInboundPipeline.process(NioInboundPipeline.java:132) ~[classes/:?]
	at com.hazelcast.internal.networking.nio.NioThread.handleSelectionKey(NioThread.java:383) [classes/:?]
	at com.hazelcast.internal.networking.nio.NioThread.handleSelectionKeys(NioThread.java:368) [classes/:?]
	at com.hazelcast.internal.networking.nio.NioThread.selectNowLoop(NioThread.java:318) [classes/:?]
	at com.hazelcast.internal.networking.nio.NioThread.run(NioThread.java:227) [classes/:?]
05:35:46,015  WARN |write_whenNotAlive| - [TcpIpConnectionErrorHandler] hz.hz.IO.thread-in-0 - [LOCAL] [somegroup] [3.10.6-SNAPSHOT] Removing connection to endpoint [127.0.0.1]:5701 Cause => java.io.EOFException {Remote socket closed!}, Error-Count: 2
05:35:46,015  INFO |write_whenNotAlive| - [MockIOService] hz.hz.IO.thread-in-0 - [LOCAL] [somegroup] [3.10.6-SNAPSHOT] Removing endpoint: [127.0.0.1]:5701
BuildInfo right after write_whenNotAlive(com.hazelcast.internal.networking.nio.SelectNow_TcpIpConnection_BasicTest): BuildInfo{version='3.10.6-SNAPSHOT', build='20180916', buildNumber=20180916, revision=8400dd0, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'write_whenNotAlive(com.hazelcast.internal.networking.nio.SelectNow_TcpIpConnection_BasicTest):'
05:35:45, accumulated pauses: 1018 ms, max pause: 20 ms, pauses over 1000 ms: 0
```

**Comment by Holmistr** [comment]
Possibly fixed by: https://github.com/hazelcast/hazelcast/pull/13759
