### ISSUE TITLE
IllegalStateException on client connection

### ISSUE THREAD

**Issue by enesakar** [hazelcast/hazelcast#13614]
Server: 3.10.4, enterprise, SSL enabled (no mutual auth)
Client: 3.11-SNAPSHOT = 3.11-20180822.174215-445.jar, enterprise, SSL enabled (no mutual auth)

It cannot connect to the cluster throws the below exception.
Note that it used to connect and run properly with snapshot version that I downloaded in July:  3.11-201807-----.jar

```
WARNING: hz.client_0 [abcde] [3.11-SNAPSHOT] ClientConnection{alive=false, connectionId=1, channel=16:7:4 54682=>30787, remoteEndpoint=null, lastReadTime=2018-08-22 16:07:04.924, lastWriteTime=2018-08-22 16:07:04.908, closedTime=2018-08-22 16:07:04.933, connected server version=null} closed. Reason: Exception in ClientConnection{alive=true, connectionId=1, channel=16:7:4 54682=>30787, remoteEndpoint=null, lastReadTime=2018-08-22 16:07:04.924, lastWriteTime=2018-08-22 16:07:04.908, closedTime=never, connected server version=null}, thread=hz.hz.client_0.IO.thread-in-0
java.lang.IllegalStateException: Unexpected Status = BUFFER_OVERFLOW HandshakeStatus = NEED_UNWRAP
bytesConsumed = 0 bytesProduced = 0
	at com.hazelcast.nio.ssl.TLSHandshakeDecoder.onRead(TLSHandshakeDecoder.java:105)
	at com.hazelcast.internal.networking.nio.NioInboundPipeline.process(NioInboundPipeline.java:135)
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKey(NioThread.java:368)
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKeys(NioThread.java:353)
	at com.hazelcast.internal.networking.nio.NioThread.selectLoop(NioThread.java:279)
	at com.hazelcast.internal.networking.nio.NioThread.run(NioThread.java:234)
```

**Comment by jerrinot** [comment]
it looks like a regression caused by the Pipeline I/O work

**Comment by jerrinot** [comment]
@enesakar is the server configured to use OpenSSL?

**Comment by kwart** [comment]
@enesakar Can you share more details about your environment? 
Operating System used
Java vendor & version.
Hazelcast member & client config.

**Comment by enesakar** [comment]
standard ssl
I am using hazelcast official docker container for the server:
FROM hazelcast/hazelcast-enterprise:3.10

For client, I am on my mac pro with jdk1.8.0_152.jdk

As I have told, server version is fixed. Old client works (3.10.4) new client (3.11-SNAPSHOT) does not work.

**Comment by enesakar** [comment]
server config 
```
<?xml version="1.0" encoding="UTF-8"?>
<hazelcast xmlns="http://www.hazelcast.com/schema/config"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.hazelcast.com/schema/config
           http://www.hazelcast.com/schema/config/hazelcast-config-3.11.xsd">
  <license-key>ENTERPRISE_HD#9999Nodes#AI7H6FJTEmOjukwaybVfr5N1KSl0U3899191011099111011011199000893</license-key>
  <group>
    <name>${clusterConfig.name}</name>
    <password>${clusterConfig.clusterPassword}</password>
  </group>
  <properties>
    <property name="hazelcast.shutdownhook.enabled">TRUE</property>
    <property name="hazelcast.shutdownhook.policy">GRACEFUL</property>
    <property name="hazelcast.http.healthcheck.enabled">true</property>
  </properties>
  <management-center enabled="true">${clusterConfig.mancenterInternalUrl}</management-center>
  <network>
    <port auto-increment="true" port-count="100">${clusterConfig.port}</port>
    <join>
      <tcp-ip enabled="false" />
      <multicast enabled="true">
        <multicast-group>224.2.2.3</multicast-group>
        <multicast-port>${clusterConfig.multicastPort}</multicast-port>
      </multicast>
    </join>
    <interfaces enabled="true">
      <interface>10.*.*.*</interface>
      <interface>100.*.*.*</interface>
    </interfaces>
    <ssl enabled="false">
      <factory-class-name>com.hazelcast.nio.ssl.BasicSSLContextFactory</factory-class-name>
      <properties>
        <property name="keyStore">${clusterConfig.tlsFileName}</property>
        <#if clusterConfig.tlsPassword??>
          <property name="keyStorePassword">${clusterConfig.tlsPassword}</property>
        </#if>
        <property name="trustStore">${clusterConfig.tlsFileName}</property>
        <#if clusterConfig.tlsPassword??>
          <property name="trustStorePassword">${clusterConfig.tlsPassword}</property>
        </#if>
        <property name="keyManagerAlgorithm">SunX509</property>
        <property name="protocol">TLS</property>
      </properties>
    </ssl>
  </network>
  <#list clusterConfig.mapConfigs as mapConfigRequest>
    <map name="${mapConfigRequest.name}">
      <in-memory-format>NATIVE</in-memory-format>
      <hot-restart enabled="false">
        <fsync>false</fsync>
      </hot-restart>
      <#if mapConfigRequest.ttlSeconds??>
        <time-to-live-seconds>${mapConfigRequest.ttlSeconds?c}</time-to-live-seconds>
      </#if>
      <#if mapConfigRequest.maxIdleSeconds??>
        <max-idle-seconds>${mapConfigRequest.maxIdleSeconds?c}</max-idle-seconds>
      </#if>
      <#if mapConfigRequest.evictionPolicy??>
        <eviction-policy>${mapConfigRequest.evictionPolicy}</eviction-policy>
      </#if>
      <#if mapConfigRequest.maxSizePolicy??>
        <max-size policy="${mapConfigRequest.maxSizePolicy}">${mapConfigRequest.maxSize?c}</max-size>
      </#if>
      <#if mapConfigRequest.indexes??>
        <indexes>
          <#list mapConfigRequest.indexes as mapIndex>
            <index ordered="true">${mapIndex.name}</index>
          </#list>
        </indexes>
      </#if>
    </map>
  </#list>

  <native-memory enabled="true" allocator-type="POOLED">
    <size value="${clusterConfig.nativeMemory}" unit="MEGABYTES" />
    <metadata-space-percentage>10</metadata-space-percentage>
  </native-memory>
  <user-code-deployment enabled="true">
    <class-cache-mode>ETERNAL</class-cache-mode>
    <provider-mode>LOCAL_AND_CACHED_CLASSES</provider-mode>
  </user-code-deployment>
  <hot-restart-persistence enabled="false">
    <backup-dir>/opt</backup-dir>
    <parallelism>1</parallelism>
    <validation-timeout-seconds>120</validation-timeout-seconds>
    <data-load-timeout-seconds>900</data-load-timeout-seconds>
    <cluster-data-recovery-policy>FULL_RECOVERY_ONLY</cluster-data-recovery-policy>
  </hot-restart-persistence>
  <security enabled="true">
    <client-login-modules>
      <login-module usage="REQUIRED" class-name="com.hazelcast.security.impl.DefaultLoginModule">
      </login-module>

    </client-login-modules>

    <client-permissions>
      <all-permissions principal="${clusterConfig.name}">
      </all-permissions>
    </client-permissions>
  </security>
</hazelcast>
```

**Comment by enesakar** [comment]
client config
```
<?xml version="1.0" encoding="UTF-8"?>
<hazelcast-client xsi:schemaLocation="http://www.hazelcast.com/schema/client-config hazelcast-client-config-3.11.xsd"
                  xmlns="http://www.hazelcast.com/schema/client-config"
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <group>
        <name>test4</name>
        <password>4f8c9d1742a24a0da73c039e510a21d6</password>
    </group>
    <properties>
        <property name="hazelcast.client.cloud.url">https://enes.hazelcast.cloud</property>
        <property name="hazelcast.client.statistics.enabled">false</property>
    </properties>
    <network>
        <ssl enabled="true"/>
        <hazelcast-cloud enabled="true">
            <discovery-token>35de153340e</discovery-token>
        </hazelcast-cloud>
    </network>
</hazelcast-client>
```

**Comment by kwart** [comment]
Thanks for details, Enes. I'm going to look into it.

**Comment by kwart** [comment]
There is already a PR to fix this: hazelcast/hazelcast-enterprise#2341
I'll update the PR description to reference this issue.

I failed to reproduce the issue locally (Ubuntu 18.04, Docker 18.09.0-ce-tp3). I just tried to start the client several times (~10).

**Comment by jerrinot** [comment]
@kwart: thanks! I just tried your reproducer to confirm the issue is gone with [this PR](https://github.com/hazelcast/hazelcast-enterprise/pull/2341).
