### ISSUE TITLE
Q: transactions now throw ConcurrentModificationException and TransactionNotActiveException ?

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#13629]
Question. 

i have seen that transaction test are now throwing 'ConcurrentModificationException and TransactionNotActiveException '

is this exception expected ?

as maybe the point of using transaction's is not to have `ConcurrentModificationException` ?

**Comment by Danny-Hazelcast** [comment]
TransactionNotActiveException from it wording seams more expected.

**Comment by Danny-Hazelcast** [comment]
@mmedenjak  

ConcurrentModificationException started to be thrown from  3.11-SNAPSHOT

**Comment by Danny-Hazelcast** [comment]
```java.util.ConcurrentModificationException: Transaction couldn't obtain lock 63
    at com.hazelcast.multimap.impl.txn.TransactionalMultiMapProxySupport.putInternal(TransactionalMultiMapProxySupport.java:126)
    at com.hazelcast.multimap.impl.txn.TransactionalMultiMapProxy.put(TransactionalMultiMapProxy.java:40)```
or
```com.hazelcast.transaction.TransactionNotActiveException: Transaction is not active!
    at com.hazelcast.collection.impl.txnqueue.TransactionalQueueProxySupport.checkTransactionState(TransactionalQueueProxySupport.java:94)
    at com.hazelcast.collection.impl.txnqueue.TransactionalQueueProxy.offer(TransactionalQueueProxy.java:55)
    at com.hazelcast.collection.impl.txnqueue.TransactionalQueueProxy.offer(TransactionalQueueProxy.java:43)```
 for TransactionNotActiveException

Mehmet Dogan [4:47 PM]
`TransactionNotActiveException` seems a valid failure, it's thrown here:
    ```void checkTransactionState() {
        if (!tx.getState().equals(Transaction.State.ACTIVE)) {
            throw new TransactionNotActiveException("Transaction is not active!");
        }
    }```
`ConcurrentModificationException` should be a bug.
hmm.. no.
it's thrown here:
            ```MultiMapResponse response = lockAndGet(key, timeout, ttl);
            if (response == null) {
                throw new ConcurrentModificationException("Transaction couldn't obtain lock " + getThreadId());
            }```
I'm not sure whether this is the correct exception type to throw here...

Danny Conlon [4:49 PM]
https://github.com/hazelcast/hazelcast/issues/13629
GitHub
Q: transactions now throw ConcurrentModificationException and TransactionNotActiveException ? · Issue #13629 · hazelcast/hazelcast
Question. i have seen that transaction test are now throwing &#39;ConcurrentModificationException and TransactionNotActiveException &#39; is this exception expected ? as maybe the point of using tr...

Mehmet Dogan [4:51 PM]
`ConcurrentModificationException` is there since 2013, not a newly addition: https://github.com/hazelcast/hazelcast/commit/fb768fff6b2b0ae9339278e31f27e7d23bb5ef89#diff-2b7981cec752e9e9848d93a0bbf77bacR52 (edited)
`ConcurrentModificationException` is thrown when multimap cannot acquire lock in time.
The same logic in IMap throws `TransactionTimedOutException`, which sounds more suitable
            ```int partitionId = partitionService.getPartitionId(key);
            Future<VersionedValue> future = operationService.invokeOnPartition(SERVICE_NAME, operation, partitionId);
            versionedValue = future.get();
            if (versionedValue == null) {
                throw new TransactionTimedOutException("Transaction couldn't obtain lock for the key: " + toObjectIfNeeded(key));
            }```

**Comment by Danny-Hazelcast** [comment]
@mmedenjak   i up dated this issue. to

Multi map transaction throw ConcurrentModificationException but should be TransactionNotActiveException

which i think Mehmet was recommending in the comment above
