### ISSUE TITLE
ClientIndexStatsTest.testAverageQuerySelectivityCalculation_WhenSomePartitionsAreEmpty failure

### ISSUE THREAD

**Issue by Holmistr** [hazelcast/hazelcast#13657]
*master* (commit a8fa0e469f5275ff88037c4f01e08219681890f5)

Failed on Sonar build: https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-sonar/204/testReport/junit/com.hazelcast.client.map/ClientIndexStatsTest/testAverageQuerySelectivityCalculation_WhenSomePartitionsAreEmpty_format_OBJECT_/

Stacktrace:
```
java.lang.AssertionError: expected:<0.7578947368421053> but was:<0.773643092105263>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:553)
	at org.junit.Assert.assertEquals(Assert.java:683)
	at com.hazelcast.map.LocalIndexStatsTest.testAverageQuerySelectivityCalculation(LocalIndexStatsTest.java:261)
	at com.hazelcast.map.LocalIndexStatsTest.testAverageQuerySelectivityCalculation_WhenSomePartitionsAreEmpty(LocalIndexStatsTest.java:227)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

Standard output:
```
Hiccups measured while running test 'testAverageQuerySelectivityCalculation_WhenSomePartitionsAreEmpty[format:OBJECT](com.hazelcast.client.map.ClientIndexStatsTest):'
23:52:05, accumulated pauses: 4048 ms, max pause: 524 ms, pauses over 1000 ms: 0
```

**Comment by blazember** [comment]
New failure in the PR builder:

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-pr-builder/17460/testReport/junit/com.hazelcast.client.map/ClientIndexStatsTest/testAverageQuerySelectivityCalculation_WhenSomePartitionsAreEmpty_format_OBJECT_/

**Error Message**
```
expected:<0.7722222222222223> but was:<0.7877604166666666>
```

**Stacktrace**
```
java.lang.AssertionError: expected:<0.7722222222222223> but was:<0.7877604166666666>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:553)
	at org.junit.Assert.assertEquals(Assert.java:683)
	at com.hazelcast.map.LocalIndexStatsTest.testAverageQuerySelectivityCalculation(LocalIndexStatsTest.java:261)
	at com.hazelcast.map.LocalIndexStatsTest.testAverageQuerySelectivityCalculation_WhenSomePartitionsAreEmpty(LocalIndexStatsTest.java:227)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Hiccups during the test**
```
Hiccups measured while running test 'testAverageQuerySelectivityCalculation_WhenSomePartitionsAreEmpty[format:OBJECT](com.hazelcast.client.map.ClientIndexStatsTest):'
15:42:25, accumulated pauses: 1616 ms, max pause: 387 ms, pauses over 1000 ms: 0
15:42:30, accumulated pauses: 852 ms, max pause: 294 ms, pauses over 1000 ms: 0
```
