### ISSUE TITLE
NoClassDefFoundError with 3.11-SNAPSHOT

### ISSUE THREAD

**Issue by enesakar** [hazelcast/hazelcast#13663]
my server is 3.10.4
my client uses the latest snapshot (3.11-SNAPHOT)

My client fails fast with following exception

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.lang.NoClassDefFoundError: com/hazelcast/internal/networking/EventLoopGroup
	at com.hazelcast.client.HazelcastClient$1.createHazelcastInstanceClient(HazelcastClient.java:55)
	at com.hazelcast.client.HazelcastClientManager.newHazelcastClient(HazelcastClientManager.java:75)
	at com.hazelcast.client.HazelcastClientManager.newHazelcastClient(HazelcastClientManager.java:61)
	at com.hazelcast.client.HazelcastClient.newHazelcastClient(HazelcastClient.java:68)
	at com.hazelcast.managedservice.testclient.loadgenerator.SimpleMetricsTest.run(SimpleMetricsTest.java:31)
	at com.hazelcast.managedservice.testclient.ClientApp.main(ClientApp.java:23)
	... 8 more
Caused by: java.lang.ClassNotFoundException: com.hazelcast.internal.networking.EventLoopGroup
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:94)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 14 more
```

**Comment by jerrinot** [comment]
@enesakar: Hi, can you double-check you do not have multiple Hazelcast JARs on a classpath? It's easy with Spring Boot. Is it your own snapshot build or it's from the sonatype snapshot repository? Can you please try with `3.11-BETA-1` instead of snapshot? Thanks!

**Comment by jerrinot** [comment]
I am getting the same error when I have Hazelcast Core 3.11-SNAPSHOT and Hazelcast Client 3.10.4 on a classpath. 

```xml
        <dependency>
            <groupId>com.hazelcast</groupId>
            <artifactId>hazelcast</artifactId>
            <version>3.11-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>com.hazelcast</groupId>
            <artifactId>hazelcast-client</artifactId>
            <version>3.10.4</version>
        </dependency>
```

```
java.lang.NoClassDefFoundError: com/hazelcast/internal/networking/EventLoopGroup

	at com.hazelcast.client.HazelcastClient$1.createHazelcastInstanceClient(HazelcastClient.java:55)
	at com.hazelcast.client.HazelcastClientManager.newHazelcastClient(HazelcastClientManager.java:75)
	at com.hazelcast.client.HazelcastClient.newHazelcastClient(HazelcastClient.java:72)
	at kubernetes.ClientConnect.startClient(ClientConnect.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.ClassNotFoundException: com.hazelcast.internal.networking.EventLoopGroup
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 26 more
```

**Comment by enesakar** [comment]
@jerrinot  Have you also tried my case? 

I have only 3.11-SNAPSHOT on my classpath.
No spring, no server, no enterprise, I get the exact same exception with an empty project with just one line of code:
```
  public static void main(String[] args) {
        HazelcastInstance client = HazelcastClient.newHazelcastClient();
    }
```

No problem with 3.11-BETA-1

Here my project, let me know if I miss something?
https://github.com/enesakar/hazelcastclienttest

**Comment by enesakar** [comment]
issues has gone, after deleteing my local maven repo. so closing.
