### ISSUE TITLE
HazelcastStarterTest related test failures

### ISSUE THREAD

**Issue by Holmistr** [hazelcast/hazelcast#13687]
Identified causing commit: https://github.com/hazelcast/hazelcast/commit/ac02477456b2a9516692706c2967c6e95acb996e

Failing constantly, easily locally reproducible. Tests failing:
 com.hazelcast.test.starter.answer.test.AnswerTest.testQueueService
 com.hazelcast.test.starter.answer.test.AnswerTest.testMapService
 com.hazelcast.test.starter.answer.test.AnswerTest.testPartitionService
 com.hazelcast.test.starter.answer.test.AnswerTest.testSerializationService
 com.hazelcast.test.starter.answer.test.AnswerTest.testHazelcastInstanceImpl
 com.hazelcast.test.starter.answer.test.AnswerTest.testClusterService
 com.hazelcast.test.starter.answer.test.AnswerTest.testNode
 com.hazelcast.test.starter.answer.test.AnswerTest.testSetService
 com.hazelcast.test.starter.answer.test.AnswerTest.testCacheService
 com.hazelcast.test.starter.answer.test.AnswerTest.testMultiMapService
 com.hazelcast.test.starter.answer.test.AnswerTest.testNodeEngine
 com.hazelcast.test.starter.constructor.test.MergePolicyProviderConstructorTest.testConstructor
 com.hazelcast.test.starter.constructor.test.MergePolicyProviderConstructorTest.testConstructor
 com.hazelcast.test.starter.test.HazelcastStarterTest.testMemberWithConfig_withFirewallingConnectionManager
com.hazelcast.test.starter.test.HazelcastStarterTest.testMemberWithConfig_withoutFirewallingConnectionManager
com.hazelcast.test.starter.test.HazelcastStarterTest.testHazelcastInstanceCompatibility_withStarterInstance 

Stacktrace:
```
java.lang.IllegalArgumentException: object is not an instance of declaring class
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.hazelcast.test.starter.constructor.ConfigConstructor.createNew0(ConfigConstructor.java:40)
	at com.hazelcast.test.starter.constructor.AbstractStarterObjectConstructor.createNew(AbstractStarterObjectConstructor.java:45)
	at com.hazelcast.test.starter.HazelcastProxyFactory.construct(HazelcastProxyFactory.java:316)
	at com.hazelcast.test.starter.HazelcastProxyFactory.constructWithoutProxy(HazelcastProxyFactory.java:276)
	at com.hazelcast.test.starter.HazelcastProxyFactory.proxyObjectForStarter(HazelcastProxyFactory.java:191)
	at com.hazelcast.test.starter.HazelcastStarter.getConfig(HazelcastStarter.java:294)
	at com.hazelcast.test.starter.HazelcastStarter.createInstanceViaInstanceFactory(HazelcastStarter.java:234)
	at com.hazelcast.test.starter.HazelcastStarter.newHazelcastInstanceWithNetwork(HazelcastStarter.java:220)
	at com.hazelcast.test.starter.HazelcastStarter.newHazelcastInstance(HazelcastStarter.java:109)
	at com.hazelcast.test.starter.answer.test.AnswerTest.setUp(AnswerTest.java:110)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:386)
	at com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37)
	at com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:104)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:50)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:29)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at com.hazelcast.test.AbstractHazelcastClassRunner$1.evaluate(AbstractHazelcastClassRunner.java:305)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:107)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:83)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:379)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:340)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:413)
```

**Comment by taburet** [comment]
The root cause is in https://github.com/hazelcast/hazelcast/commit/ac02477456b2a9516692706c2967c6e95acb996e#diff-0c56fa6800f9817dbe3a5c2a5e7e3c7bR164, the code assumes that all class loaders are born unequal and only a single class loader may load a certain class. Which is not true at least for our compatibility tests.

I see two options here:

1. Always try the passed `classLoaderHint` first. This requires `ClassNotFoundException` results caching in `CLASS_CACHE` to avoid possible performance problems.

2. Support `VersionAware` class loaders to avoid loading wrong classes. If the passed class loader is `VersionAware` while the inferred one is not, we will always prefer the passed one, this doesn't require `ClassNotFoundException` caching since `VersionAware` will be implemented by our compatibility tests class loader only and performance is not that important there. If the passed and the inferred class loaders are both `VersionAware` and of different versions the error will be produced.

@viliam-durina WDYT?
