### ISSUE TITLE
NPE HD near cache AbstractPoolingMemoryManager compact

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#13718]
https://hazelcast-l337.ci.cloudbees.com/view/kill/job/kill-members/9/console

```
java.lang.NullPointerException
    at com.hazelcast.memory.AbstractPoolingMemoryManager.compact(AbstractPoolingMemoryManager.java:212)
    at com.hazelcast.memory.AbstractPoolingMemoryManager.compact(AbstractPoolingMemoryManager.java:131)
    at com.hazelcast.internal.nearcache.HiDensityNearCache.compactMemory(HiDensityNearCache.java:208)
    at com.hazelcast.internal.nearcache.HiDensityNearCache.put(HiDensityNearCache.java:96)
    at com.hazelcast.client.cache.impl.NearCachedClientCacheProxy.cacheOrInvalidate(NearCachedClientCacheProxy.java:504)
    at com.hazelcast.client.cache.impl.NearCachedClientCacheProxy.onPutSyncInternal(NearCachedClientCacheProxy.java:167)
    at com.hazelcast.client.cache.impl.AbstractClientInternalCacheProxy.putSyncInternal(AbstractClientInternalCacheProxy.java:437)
    at com.hazelcast.client.cache.impl.AbstractClientCacheProxy.put(AbstractClientCacheProxy.java:264)
    at com.hazelcast.client.cache.impl.ClientCacheProxy.put(ClientCacheProxy.java:94)
    at com.hazelcast.client.cache.impl.ClientCacheProxy.put(ClientCacheProxy.java:192)
```

**Comment by Danny-Hazelcast** [comment]
/disk1/jenkins/workspace/kill-members/3.11-SNAPSHOT/2018_09_10-13_23_12/member

**Comment by Danny-Hazelcast** [comment]
this might have been provoked by calling

HazelcastInstance.shutdown()  on the client.
