### ISSUE TITLE
SelectWithSelectorFix_TcpIpConnectionManager_ConnectMemberTest.testConnectionCount failure

### ISSUE THREAD

**Issue by Holmistr** [hazelcast/hazelcast#13713]
*master* (commit 5acd84dee8cc7db1085e6fa0a43afbdff4b68ee9)

Failed on nightly build: https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-sonar/216/testReport/junit/com.hazelcast.internal.networking.nio/SelectWithSelectorFix_TcpIpConnectionManager_ConnectMemberTest/testConnectionCount/

Stacktrace:
```
java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:67)
	at com.hazelcast.nio.tcp.MockIOService.<init>(MockIOService.java:71)
	at com.hazelcast.nio.tcp.TcpIpConnection_AbstractTest.newConnectionManager(TcpIpConnection_AbstractTest.java:114)
	at com.hazelcast.nio.tcp.TcpIpConnection_AbstractTest.setup(TcpIpConnection_AbstractTest.java:76)
	at com.hazelcast.internal.networking.nio.SelectWithSelectorFix_TcpIpConnectionManager_ConnectMemberTest.setup(SelectWithSelectorFix_TcpIpConnectionManager_ConnectMemberTest.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:386)
	at com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37)
	at com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:104)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:50)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:29)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at com.hazelcast.test.AbstractHazelcastClassRunner$1.evaluate(AbstractHazelcastClassRunner.java:305)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:107)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:83)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:379)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:340)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:413)
```

Standard output:
```
Hiccups measured while running test 'testConnectionCount(com.hazelcast.internal.networking.nio.SelectWithSelectorFix_TcpIpConnectionManager_ConnectMemberTest):'
21:44:00, accumulated pauses: 189 ms, max pause: 120 ms, pauses over 1000 ms: 0
```

Probably related to https://github.com/hazelcast/hazelcast/issues/13617 .

**Comment by blazember** [comment]
Something is fishy with the `TcpIpConnection_*` tests. 
All the recent related failures reported by jenkins show double test executions. It happens systematically, not very likely it is a jenkins bug.

See the failure in [this build](https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-sonar/216/testReport/junit/com.hazelcast.internal.networking.nio/SelectWithSelectorFix_TcpIpConnectionManager_ConnectMemberTest/testConnectionCount/)
```
Test Result (2 failures / ±0)
com.hazelcast.internal.networking.nio.SelectWithSelectorFix_TcpIpConnectionManager_ConnectMemberTest.testConnectionCount
com.hazelcast.internal.networking.nio.SelectWithSelectorFix_TcpIpConnectionManager_ConnectMemberTest.testConnectionCount
```

Another one from https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-pr-builder/17031/ (different test class and case, but they have a common parent)

```
Test Result (2 failures / +2)
com.hazelcast.internal.networking.nio.SelectWithSelectorFix_TcpIpConnection_BasicTest.lastReadTimeMillis
com.hazelcast.internal.networking.nio.SelectWithSelectorFix_TcpIpConnection_BasicTest.lastReadTimeMillis
```

Same is true for the other failures in the linked #13617.

**Comment by mdogan** [comment]
@blazember: I think reason for double failure reports is, first failure is during test execution and second failure comes from `tearDown` method after test.

**Comment by mustafaiman** [comment]
I dont think the issue is reproducible by running the test alone. I managed to make it fail with this once:
```
mvn org.jacoco:jacoco-maven-plugin:prepare-agent test -B -U -Ptest-coverage -DfailIfNoTests=false -Dtest=com.hazelcast.nio.tcp.**,com.hazelcast.internal.networking.** -Dmaven.test.failure.ignore=true
```
However, looks like it fails on PR builder too (https://github.com/hazelcast/hazelcast/issues/13617#issuecomment-419876076)

I kept track of requested ports by using a custom security manager but it did not fail with the security manager on. The following logs all socket listen actions happening in the JVM.
```
    @Override
    public void checkListen(int port) {
        super.checkListen(port);
        String str = String.format("Listen on port %d called from %s at %s\n%s\n\n",
                port,
                Thread.currentThread().getName(),
                new Date().toString(),
                Arrays.toString(Thread.currentThread().getStackTrace()));
        try {
            bw.write(str);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
```

I also suspected
```
"RMI TCP Accept-21414" 
	java.lang.Thread.State: RUNNABLE, cpu=133091 nsecs, usr=0 nsecs, blocked=0 msecs, waited=0 msecs
		at java.net.PlainSocketImpl.socketAccept(Native Method)
		at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
		at java.net.ServerSocket.implAccept(ServerSocket.java:545)
		at java.net.ServerSocket.accept(ServerSocket.java:513)
		at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.executeAcceptLoop(TCPTransport.java:405)
		at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.run(TCPTransport.java:377)
		at java.lang.Thread.run(Thread.java:748)

"RMI TCP Accept-21413" 
	java.lang.Thread.State: RUNNABLE, cpu=242637 nsecs, usr=0 nsecs, blocked=0 msecs, waited=0 msecs
		at java.net.PlainSocketImpl.socketAccept(Native Method)
		at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
		at java.net.ServerSocket.implAccept(ServerSocket.java:545)
		at java.net.ServerSocket.accept(ServerSocket.java:513)
		at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.executeAcceptLoop(TCPTransport.java:405)
		at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.run(TCPTransport.java:377)
		at java.lang.Thread.run(Thread.java:748)
```
These might have allocated the port but I could not find much info on RMI TCP Accept threads. I looked at their source code and looks like the number there represents the port that they are listening. So these should not be the thread that blocks `570x` ports.

**Comment by mmedenjak** [comment]
Minimal reproducer:
```java
    @Test
    public void testLala() throws Exception {
        int i = 0;
        while (i < 1000 * 1000) {
            if (i++ % 10000 == 0) {
                System.out.println("Running " + i);
            }
            ServerSocketChannel serverSocketChannel = ServerSocketChannel.open();
            ServerSocket serverSocket = serverSocketChannel.socket();
            serverSocket.setReuseAddress(true);
            serverSocket.setSoTimeout(1000);
            serverSocket.bind(new InetSocketAddress("0.0.0.0", 5701));

            serverSocketChannel.close();
            
        }
    }
```

This does not seem to fail locally but fails on the PR builder machine:
```
Started Running Test: testLala
Running 1
Running 10001
Running 20001
Running 30001
Running 40001
Running 50001
java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:67)
	at com.hazelcast.internal.networking.nio.SelectWithSelectorFix_TcpIpConnectionManager_ConnectMemberTest.testLala(SelectWithSelectorFix_TcpIpConnectionManager_ConnectMemberTest.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Holmistr** [comment]
Possibly fixed by: https://github.com/hazelcast/hazelcast/pull/13759
