### ISSUE TITLE
HazelcastSerializationException: No DataSerializerFactory registered for namespace: -41

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#13724]
https://hazelcast-l337.ci.cloudbees.com/view/stable/job/stable-cleanShutdown/2/console

just after cluster shutdown. we get a HazelcastSerializationException

```
16:20:09 /disk1/jenkins/workspace/stable-cleanShutdown/3.11-SNAPSHOT/2018_09_10-16_15_03/stable/aggregator/predicate Failed
16:20:09 fail HzMember4HZ _aggregator-predicate_count_mapBak1HDIdx hzcmd.map.aggregate.CountPredicate threadId=3 com.hazelcast.nio.serialization.HazelcastSerializationException: No DataSerializerFactory registered for namespace: -41 
16:20:09 http://54.82.84.143/~jenkins/workspace/stable-cleanShutdown/3.11-SNAPSHOT/2018_09_10-16_15_03/stable/aggregator/predicate
16:20:09  
16:22:29 /disk1/jenkins/workspace/stable-cleanShutdown/3.11-SNAPSHOT/2018_09_10-16_15_03/stable/aggregator/regular Failed
16:22:29 fail HzMember4HZ _aggregator_count_mapBak1 hzcmd.map.aggregate.Count threadId=0 com.hazelcast.nio.serialization.HazelcastSerializationException: No DataSerializerFactory registered for namespace: -41 
16:22:29 http://54.82.84.143/~jenkins/workspace/stable-cleanShutdown/3.11-SNAPSHOT/2018_09_10-16_15_03/stable/aggregator/regular
```

```
com.hazelcast.nio.serialization.HazelcastSerializationException: No DataSerializerFactory registered for namespace: -41
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.createIdentifiedDataSerializable(EnterpriseDataSerializableSerializer.java:173)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.readIdentifiedDataSerializable(EnterpriseDataSerializableSerializer.java:151)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.doRead(EnterpriseDataSerializableSerializer.java:130)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.read(EnterpriseDataSerializableSerializer.java:124)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.read(EnterpriseDataSerializableSerializer.java:52)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:187)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.aggregate(MapProxyImpl.java:826)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.aggregate(MapProxyImpl.java:816)
```

**Comment by Danny-Hazelcast** [comment]
something like this might be expected ? 

```
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@4a4416bc rejected from ThreadPoolExecutor{name='hz:async'}
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2070)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:828)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1382)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
	at com.hazelcast.instance.Node.callGracefulShutdownAwareServices(Node.java:472)
	at com.hazelcast.instance.Node.shutdown(Node.java:429)
	at com.hazelcast.instance.LifecycleServiceImpl.shutdown(LifecycleServiceImpl.java:98)
	at com.hazelcast.instance.LifecycleServiceImpl.shutdown(LifecycleServiceImpl.java:81)
	at com.hazelcast.internal.cluster.impl.ClusterServiceImpl.shutdownNodes(ClusterServiceImpl.java:973)
	at com.hazelcast.internal.cluster.impl.ClusterServiceImpl.shutdownCluster(ClusterServiceImpl.java:943)
	at com.hazelcast.internal.cluster.impl.ClusterServiceImpl.shutdown(ClusterServiceImpl.java:923)

```

**Comment by Danny-Hazelcast** [comment]
issue happens just after cluster shutdown
but the aggregation returns the HazelcastSerializationException

/disk1/jenkins/workspace/stable-cleanShutdown/3.11-SNAPSHOT/2018_09_10-16_15_03/stable/aggregator/predicate

http://54.82.84.143/~jenkins/workspace/stable-cleanShutdown/3.11-SNAPSHOT/2018_09_10-16_15_03/stable/aggregator/predicate/output/HZ/HzMember4HZ/out.txt

```
INFO: [10.0.0.87]:5701 [HZ] [3.11-SNAPSHOT] Shutting down node engine...
Sep 10, 2018 1:17:26 PM com.hazelcast.spi.impl.operationservice.impl.OutboundResponseHandler
WARNING: [10.0.0.87]:5701 [HZ] [3.11-SNAPSHOT] Cannot send response: com.hazelcast.map.impl.query.AggregationResult@2db61b13 to [10.0.0.137]:5701. com.hazelcast.map.impl.query.HDQueryOperation{serviceName='hz:impl:mapService', identityHash=1332360673, partitionId=-1, replicaIndex=0, callId=103084, invocationTime=1536585444757 (2018-09-10 13:17:24.757), waitTimeout=-1, callTimeout=60000, name=mapBak1HDIdx_aggregator-predicate}
Sep 10, 2018 1:17:26 PM com.hazelcast.spi.impl.operationservice.impl.OutboundResponseHandler
WARNING: [10.0.0.87]:5701 [HZ] [3.11-SNAPSHOT] Cannot send response: com.hazelcast.map.impl.query.AggregationResult@22770fc7 to [10.0.0.137]:5701. com.hazelcast.map.impl.query.HDQueryOperation{serviceName='hz:impl:mapService', identityHash=1173843842, partitionId=-1, replicaIndex=0, callId=103088, invocationTime=1536585444757 (2018-09-10 13:17:24.757), waitTimeout=-1, callTimeout=60000, name=mapBak1HD_aggregator-predicate}
Sep 10, 2018 1:17:26 PM com.hazelcast.spi.impl.operationservice.impl.OutboundResponseHandler
WARNING: [10.0.0.87]:5701 [HZ] [3.11-SNAPSHOT] Cannot send response: com.hazelcast.map.impl.query.AggregationResult@108b813d to [10.0.0.137]:5701. com.hazelcast.map.impl.query.HDQueryOperation{serviceName='hz:impl:mapService', identityHash=2008671152, partitionId=-1, replicaIndex=0, callId=103092, invocationTime=1536585444758 (2018-09-10 13:17:24.758), waitTimeout=-1, callTimeout=60000, name=mapBak1HDIdx_aggregator-predicate}
Sep 10, 2018 1:17:26 PM com.hazelcast.spi.impl.operationservice.impl.OutboundResponseHandler
WARNING: [10.0.0.87]:5701 [HZ] [3.11-SNAPSHOT] Cannot send response: com.hazelcast.map.impl.query.AggregationResult@9c79d6f to [10.0.0.137]:5701. com.hazelcast.map.impl.query.HDQueryOperation{serviceName='hz:impl:mapService', identityHash=1293120824, partitionId=-1, replicaIndex=0, callId=103096, invocationTime=1536585444758 (2018-09-10 13:17:24.758), waitTimeout=-1, callTimeout=60000, name=mapBak1HD_aggregator-predicate}
Sep 10, 2018 1:17:26 PM com.hazelcast.spi.impl.operationservice.impl.OutboundResponseHandler
WARNING: [10.0.0.87]:5701 [HZ] [3.11-SNAPSHOT] Cannot send response: com.hazelcast.map.impl.query.AggregationResult@7aa9ad68 to [10.0.0.221]:5701. com.hazelcast.map.impl.query.HDQueryOperation{serviceName='hz:impl:mapService', identityHash=119568336, partitionId=-1, replicaIndex=0, callId=104063, invocationTime=1536585444891 (2018-09-10 13:17:24.891), waitTimeout=-1, callTimeout=60000, name=mapBak1HD_aggregator-predicate}
Sep 10, 2018 1:17:26 PM com.hazelcast.spi.impl.operationservice.impl.OutboundResponseHandler
WARNING: [10.0.0.87]:5701 [HZ] [3.11-SNAPSHOT] Cannot send response: com.hazelcast.map.impl.query.AggregationResult@701850be to [10.0.0.221]:5701. com.hazelcast.map.impl.query.HDQueryOperation{serviceName='hz:impl:mapService', identityHash=1687813207, partitionId=-1, replicaIndex=0, callId=104067, invocationTime=1536585444912 (2018-09-10 13:17:24.912), waitTimeout=-1, callTimeout=60000, name=mapBak1HD_aggregator-predicate}
Sep 10, 2018 1:17:26 PM com.hazelcast.spi.impl.operationservice.impl.OutboundResponseHandler
WARNING: [10.0.0.87]:5701 [HZ] [3.11-SNAPSHOT] Cannot send response: com.hazelcast.map.impl.query.AggregationResult@76c1b53a to [10.0.0.137]:5701. com.hazelcast.map.impl.query.HDQueryOperation{serviceName='hz:impl:mapService', identityHash=965076826, partitionId=-1, replicaIndex=0, callId=103104, invocationTime=1536585445027 (2018-09-10 13:17:25.027), waitTimeout=-1, callTimeout=60000, name=mapBak1HD_aggregator-predicate}
Sep 10, 2018 1:17:29 PM com.hazelcast.internal.metrics.MetricsRegistry
WARNING: [10.0.0.87]:5701 [HZ] [3.11-SNAPSHOT] Overwriting existing probe 'map[mapBak1Idx_aggregator-predicate].entryCount'
Sep 10, 2018 1:17:29 PM com.hazelcast.internal.metrics.MetricsRegistry
WARNING: [10.0.0.87]:5701 [HZ] [3.11-SNAPSHOT] Overwriting existing probe 'map[mapBak1Idx_aggregator-predicate].usedMemory'
Sep 10, 2018 1:17:29 PM com.hazelcast.internal.metrics.MetricsRegistry
WARNING: [10.0.0.87]:5701 [HZ] [3.11-SNAPSHOT] Overwriting existing probe 'map[mapBak1Idx_aggregator-predicate].forceEvictionCount'
Sep 10, 2018 1:17:29 PM com.hazelcast.internal.metrics.MetricsRegistry
WARNING: [10.0.0.87]:5701 [HZ] [3.11-SNAPSHOT] Overwriting existing probe 'map[mapBak1Idx_aggregator-predicate].forceEvictedEntryCount'
Sep 10, 2018 1:17:29 PM com.hazelcast.internal.metrics.MetricsRegistry
WARNING: [10.0.0.87]:5701 [HZ] [3.11-SNAPSHOT] Overwriting existing probe 'map[mapBak1HD_aggregator-predicate].entryCount'
Sep 10, 2018 1:17:29 PM com.hazelcast.internal.metrics.MetricsRegistry
WARNING: [10.0.0.87]:5701 [HZ] [3.11-SNAPSHOT] Overwriting existing probe 'map[mapBak1HD_aggregator-predicate].usedMemory'
Sep 10, 2018 1:17:29 PM com.hazelcast.internal.metrics.MetricsRegistry
WARNING: [10.0.0.87]:5701 [HZ] [3.11-SNAPSHOT] Overwriting existing probe 'map[mapBak1HD_aggregator-predicate].forceEvictionCount'
Sep 10, 2018 1:17:29 PM com.hazelcast.internal.metrics.MetricsRegistry
WARNING: [10.0.0.87]:5701 [HZ] [3.11-SNAPSHOT] Overwriting existing probe 'map[mapBak1HD_aggregator-predicate].forceEvictedEntryCount'
Sep 10, 2018 1:17:29 PM com.hazelcast.internal.metrics.MetricsRegistry
WARNING: [10.0.0.87]:5701 [HZ] [3.11-SNAPSHOT] Overwriting existing probe 'map[mapBak1HDIdx_aggregator-predicate].entryCount'
Sep 10, 2018 1:17:29 PM com.hazelcast.internal.metrics.MetricsRegistry
WARNING: [10.0.0.87]:5701 [HZ] [3.11-SNAPSHOT] Overwriting existing probe 'map[mapBak1_aggregator-predicate].entryCount'
Sep 10, 2018 1:17:29 PM com.hazelcast.internal.metrics.MetricsRegistry
WARNING: [10.0.0.87]:5701 [HZ] [3.11-SNAPSHOT] Overwriting existing probe 'map[mapBak1_aggregator-predicate].usedMemory'
Sep 10, 2018 1:17:29 PM com.hazelcast.internal.metrics.MetricsRegistry
WARNING: [10.0.0.87]:5701 [HZ] [3.11-SNAPSHOT] Overwriting existing probe 'map[mapBak1_aggregator-predicate].forceEvictionCount'
Sep 10, 2018 1:17:29 PM com.hazelcast.internal.metrics.MetricsRegistry
WARNING: [10.0.0.87]:5701 [HZ] [3.11-SNAPSHOT] Overwriting existing probe 'map[mapBak1_aggregator-predicate].forceEvictedEntryCount'
Sep 10, 2018 1:17:29 PM com.hazelcast.internal.metrics.MetricsRegistry
WARNING: [10.0.0.87]:5701 [HZ] [3.11-SNAPSHOT] Overwriting existing probe 'map[mapBak1HDIdx_aggregator-predicate].usedMemory'
Sep 10, 2018 1:17:29 PM com.hazelcast.internal.metrics.MetricsRegistry
WARNING: [10.0.0.87]:5701 [HZ] [3.11-SNAPSHOT] Overwriting existing probe 'map[mapBak1HDIdx_aggregator-predicate].forceEvictionCount'
Sep 10, 2018 1:17:29 PM com.hazelcast.internal.metrics.MetricsRegistry
WARNING: [10.0.0.87]:5701 [HZ] [3.11-SNAPSHOT] Overwriting existing probe 'map[mapBak1HDIdx_aggregator-predicate].forceEvictedEntryCount'
Sep 10, 2018 1:17:29 PM com.hazelcast.instance.NodeExtension
INFO: [10.0.0.87]:5701 [HZ] [3.11-SNAPSHOT] Destroying node NodeExtension.
Sep 10, 2018 1:17:29 PM com.hazelcast.instance.Node
INFO: [10.0.0.87]:5701 [HZ] [3.11-SNAPSHOT] Hazelcast Shutdown is completed in 6047 ms.
com.hazelcast.nio.serialization.HazelcastSerializationException: No DataSerializerFactory registered for namespace: -41
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.createIdentifiedDataSerializable(EnterpriseDataSerializableSerializer.java:173)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.readIdentifiedDataSerializable(EnterpriseDataSerializableSerializer.java:151)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.doRead(EnterpriseDataSerializableSerializer.java:130)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.read(EnterpriseDataSerializableSerializer.java:124)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.read(EnterpriseDataSerializableSerializer.java:52)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:187)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.aggregate(MapProxyImpl.java:826)
```

**Comment by jerrinot** [comment]
I removed the `critical` label - as the issue here is a wrong exception. It should be `HazelcastInstanceNotActiveException` instead of `HazelcastSerializationException`. but still an exception.
