### ISSUE TITLE
RejectedExecutionException on shutdownCluster

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#13725]
i try to shutdown my cluster but hazelcast cluster gives RejectedExecutionException,
and will not do a graceful shutdown when requested.

```
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@4a4416bc rejected from ThreadPoolExecutor{name='hz:async'}
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2070)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:828)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1382)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
	at com.hazelcast.instance.Node.callGracefulShutdownAwareServices(Node.java:472)
	at com.hazelcast.instance.Node.shutdown(Node.java:429)
	at com.hazelcast.instance.LifecycleServiceImpl.shutdown(LifecycleServiceImpl.java:98)
	at com.hazelcast.instance.LifecycleServiceImpl.shutdown(LifecycleServiceImpl.java:81)
	at com.hazelcast.internal.cluster.impl.ClusterServiceImpl.shutdownNodes(ClusterServiceImpl.java:973)
	at com.hazelcast.internal.cluster.impl.ClusterServiceImpl.shutdownCluster(ClusterServiceImpl.java:943)
	at com.hazelcast.internal.cluster.impl.ClusterServiceImpl.shutdown(ClusterServiceImpl.java:923)
	at hzcmd.ops.ClusterShutDown.timeStep(ClusterShutDown.java:8)

```

for example in another test i see a RejectedExecutionException from Durable Executor submit,
which looks ok, as it some operation that is rejected as the cluster is shutting down.

```
java.util.concurrent.RejectedExecutionException
	at com.hazelcast.durableexecutor.impl.DurableExecutorServiceProxy.throwNotActiveException(DurableExecutorServiceProxy.java:244)
	at com.hazelcast.spi.AbstractDistributedObject.lifecycleCheck(AbstractDistributedObject.java:100)
	at com.hazelcast.spi.AbstractDistributedObject.getNodeEngine(AbstractDistributedObject.java:94)
	at com.hazelcast.spi.AbstractDistributedObject.invokeOnPartition(AbstractDistributedObject.java:72)
	at com.hazelcast.durableexecutor.impl.DurableExecutorServiceProxy.submitToPartition(DurableExecutorServiceProxy.java:263)
	at com.hazelcast.durableexecutor.impl.DurableExecutorServiceProxy.submit(DurableExecutorServiceProxy.java:154)
```

**Comment by Danny-Hazelcast** [comment]
i do not see this same behaviour / exception thrown when shutting down just one member

**Comment by Danny-Hazelcast** [comment]
I also see this exception when trying to shutdown the cluster.  which stop's dev ops shutting down the cluster when wanted.

```
com.hazelcast.core.HazelcastOverloadException: Failed to start invocation due to overload: Invocation{op=com.hazelcast.internal.cluster.impl.operations.LockClusterStateOp{serviceName='hz:core:clusterService', identityHash=682232950, partitionId=-1, replicaIndex=0, callId=0, invocationTime=1536586084033 (2018-09-10 13:28:04.033), waitTimeout=-1, callTimeout=60000}, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=60000, firstInvocationTimeMs=1536586084031, firstInvocationTime='2018-09-10 13:28:04.031', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 00:00:00.000', target=[10.0.0.87]:5701, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=null}
	at com.hazelcast.spi.impl.operationservice.impl.InvocationRegistry.register(InvocationRegistry.java:117)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:559)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:530)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:220)
	at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.invokeOnTarget(OperationServiceImpl.java:327)
	at com.hazelcast.internal.cluster.impl.ClusterStateManager.lockClusterStateOnAllMembers(ClusterStateManager.java:413)
	at com.hazelcast.internal.cluster.impl.ClusterStateManager.changeClusterState(ClusterStateManager.java:367)
	at com.hazelcast.internal.cluster.impl.ClusterStateManager.changeClusterState(ClusterStateManager.java:345)
	at com.hazelcast.internal.cluster.impl.ClusterServiceImpl.changeClusterState(ClusterServiceImpl.java:854)
	at com.hazelcast.internal.cluster.impl.ClusterServiceImpl.shutdownCluster(ClusterServiceImpl.java:933)
	at com.hazelcast.internal.cluster.impl.ClusterServiceImpl.shutdown(ClusterServiceImpl.java:923)
	at hzcmd.ops.ClusterShutDown.timeStep(ClusterShutDown.java:8)
```

**Comment by Danny-Hazelcast** [comment]
I have also seen a hang calling `hzInstance.getCluster().shutdown();`

stack traces at
/disk1/jenkins/workspace/stable-cleanShutdown/3.11-SNAPSHOT/2018_09_10-16_15_03/stable/async/async-bak/put-hd/sml-val


./output/HZ/HzMember1HZ/out.txt:	at hzcmd.ops.ClusterShutDown.timeStep(ClusterShutDown.java:8)

```
/disk1/jenkins/hzCmd-bench/lab/hz/functions/clientShutDown Done
clusterShutdown@class=hzcmd.ops.ClusterShutDown [driver=Member1, threads=1, warmup=0, duration=600, bench=Metrics, interval=0, recordException=true, ignore=com.hazelcast.core.OperationTimeoutException:com.hazelcast.core.MemberLeftException:com.hazelcast.spi.exception.TargetDisconnectedException:com.hazelcast.spi.exception.TargetNotMemberException:com.hazelcast.core.HazelcastInstanceNotActiveException:java.util.concurrent.ExecutionException:java.lang.IllegalStateException:com.hazelcast.transaction.TransactionException:java.util.ConcurrentModificationException]
ops Done
 clusterShutdown HzMember1HZ timeout=900 running bench
output/HZ/HzMember1HZ/timeout
```

after 15 mins hzInstance.getCluster().shutdown(); still did not return.

**Comment by Danny-Hazelcast** [comment]
also see an operation timeout from cluster shutdown.

/disk1/jenkins/workspace/stable-cleanShutdown/3.11-SNAPSHOT/2018_09_10-16_15_03/stable/destroy/create-use-destroy-HDnearcache

```
fail HzMember1HZ clusterShutdown hzcmd.ops.ClusterShutDown threadId=0 com.hazelcast.core.HazelcastException: java.util.concurrent.TimeoutException: LockClusterStateOp failed to complete within 59999997424 NANOSECONDS. Invocation{op=com.hazelcast.internal.cluster.impl.operations.LockClusterStateOp{serviceName='hz:core:clusterService', identityHash=1540392765, partitionId=-1, replicaIndex=0, callId=40692, invocationTime=1536590108840 (2018-09-10 14:35:08.840), waitTimeout=-1, callTimeout=600000}, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=600000, firstInvocationTimeMs=1536590108842, firstInvocationTime='2018-09-10 14:35:08.842', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 00:00:00.000', target=[10.0.0.87]:5701, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=Connection[id=3, /10.0.0.221:39804->/10.0.0.87:5701, endpoint=[10.0.0.87]:5701, alive=true, type=MEMBER]} 
```

```
cat output/HZ/HzMember1HZ/exception.txt
com.hazelcast.core.HazelcastException: java.util.concurrent.TimeoutException: LockClusterStateOp failed to complete within 59999997424 NANOSECONDS. Invocation{op=com.hazelcast.internal.cluster.impl.operations.LockClusterStateOp{serviceName='hz:core:clusterService', identityHash=1540392765, partitionId=-1, replicaIndex=0, callId=40692, invocationTime=1536590108840 (2018-09-10 14:35:08.840), waitTimeout=-1, callTimeout=600000}, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=600000, firstInvocationTimeMs=1536590108842, firstInvocationTime='2018-09-10 14:35:08.842', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 00:00:00.000', target=[10.0.0.87]:5701, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=Connection[id=3, /10.0.0.221:39804->/10.0.0.87:5701, endpoint=[10.0.0.87]:5701, alive=true, type=MEMBER]}
	at com.hazelcast.util.ExceptionUtil$1.create(ExceptionUtil.java:40)
	at com.hazelcast.util.ExceptionUtil.peel(ExceptionUtil.java:124)
	at com.hazelcast.util.ExceptionUtil.peel(ExceptionUtil.java:69)
	at com.hazelcast.util.ExceptionUtil.rethrow(ExceptionUtil.java:129)
	at com.hazelcast.internal.cluster.impl.ClusterStateManager$StateManagerExceptionHandler.rethrowIfFailed(ClusterStateManager.java:489)
	at com.hazelcast.internal.cluster.impl.ClusterStateManager.lockClusterStateOnAllMembers(ClusterStateManager.java:419)
	at com.hazelcast.internal.cluster.impl.ClusterStateManager.changeClusterState(ClusterStateManager.java:367)
	at com.hazelcast.internal.cluster.impl.ClusterStateManager.changeClusterState(ClusterStateManager.java:345)
	at com.hazelcast.internal.cluster.impl.ClusterServiceImpl.changeClusterState(ClusterServiceImpl.java:854)
	at com.hazelcast.internal.cluster.impl.ClusterServiceImpl.shutdownCluster(ClusterServiceImpl.java:933)
	at com.hazelcast.internal.cluster.impl.ClusterServiceImpl.shutdown(ClusterServiceImpl.java:923)
```

**Comment by Danny-Hazelcast** [comment]
http://54.82.84.143/~jenkins/workspace/stable-cleanShutdown/3.11-SNAPSHOT/2018_09_10-16_15_03/stable/async/sync-bak/put/
./sync-bak/put/out.txt:fail HzMember1HZ clusterShutdown hzcmd.ops.ClusterShutDown threadId=0 java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@7f113180 rejected from ThreadPoolExecutor{name='hz:async'}
so cluster shutdown called on just one member gets a .RejectedExecutionException
and
http://54.82.84.143/~jenkins/workspace/stable-cleanShutdown/3.11-SNAPSHOT/2018_09_10-16_15_03/stable/async/async-bak/put-clear/

./async-bak/put-clear/out.txt:fail HzMember1HZ clusterShutdown hzcmd.ops.ClusterShutDown threadId=0 java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@4a4416bc rejected from ThreadPoolExecutor{name='hz:async'}

**Comment by ahmetmircik** [comment]
Summarizing 2 outcomes from my investigations:

__First outcome:__

`RejectedExecutionException` was thrown by `ASYNC_EXECUTOR`.

`ASYNC_EXECUTOR` is a shared executor used by many proxies/services. Near-cached-map-proxies or reliable-topic-proxies are 2 examples among many usages.

Creation of `ASYNC_EXECUTOR` is initiated by
[OperationServiceImpl#initInvocationContext](https://github.com/hazelcast/hazelcast/blob/55027987bbbe4e9d93540538f3ffec2f6476b0cb/hazelcast/src/main/java/com/hazelcast/spi/impl/operationservice/impl/OperationServiceImpl.java#L446) like this: 

```
ManagedExecutorService asyncExecutor = nodeEngine.getExecutionService().register(
                ExecutionService.ASYNC_EXECUTOR, RuntimeAvailableProcessors.get(),
                ASYNC_QUEUE_CAPACITY, ExecutorType.CONCRETE);
```

This executor can have at most `RuntimeAvailableProcessors.get()` thread count and it can only contain `100_000 (ASYNC_QUEUE_CAPACITY)` entries at most in its queue to process.

It seems easy to reject shutdown tasks under load. Since shutdown task also using this globally shared executor. And these shutdown tasks may not found either an empty place in queue or a new worker thread, then `ThreadPoolExecutor` throws this exception. 

__Second outcome:__

ASYNC_EXECUTOR creation is fragile.

[NodeEngineImpl#start](https://github.com/hazelcast/hazelcast/blob/55027987bbbe4e9d93540538f3ffec2f6476b0cb/hazelcast/src/main/java/com/hazelcast/spi/impl/NodeEngineImpl.java#L208)

```
public void start() {
        RuntimeMetricSet.register(metricsRegistry);
        GarbageCollectionMetricSet.register(metricsRegistry);
        OperatingSystemMetricSet.register(metricsRegistry);
        ThreadMetricSet.register(metricsRegistry);
        ClassLoadingMetricSet.register(metricsRegistry);
        FileMetricSet.register(metricsRegistry);
        if (node.getProperties().getBoolean(METRICS_DISTRIBUTED_DATASTRUCTURES)) {
            new StatisticsAwareMetricsSet(serviceManager, this).register(metricsRegistry);
        }
        metricsRegistry.scanAndRegister(node.getNodeExtension().getMemoryStats(), "memory");
        metricsRegistry.collectMetrics(operationService, proxyService, eventService, operationParker);

        serviceManager.start();
        proxyService.init();
        operationService.start();<-- ASYNC_EXECUTOR is created at this stage now.
        quorumService.start();
        diagnostics.start();

        node.getNodeExtension().registerPlugins(diagnostics);
    }
```

In current code base, it is created by `operationService.start()` as a `CONCRETE` executor but it is possible that any time in the future any other class starting before `operationService` can create `ASYNC_EXECUTOR` either as `CONCRETE` or as `CACHED` type and with different settings. Maybe we can think of creating an executor specific to operation service. 

__Conclusion:__ 

`RejectedExecutionException` can be seen as an expected exception in a loaded cluster or we can create a specific executor only for operation service, so internal working parts of the system affects operation service less.

@mdogan @mmedenjak Can you please share your thoughts on these outcomes? 

@Danny-Hazelcast Can you re-run this test by disabling map-stats? Map stats are on by default and using `ASYNC_EXECUTOR` for async puts as in this test.

**Comment by jerrinot** [comment]
@ahmetmircik: good analysis. 

ad the 1st outcome: do you think the ASYNC executor is a good choice here? Perhaps the system executor would be a better choice? 

I am not sure if I understand the 2nd outcome. Is the problem because if someone ask for the ASYNC executor before it's registered then it will be created with default settings? Am I understand it right?
