### ISSUE TITLE
OperationTimeoutException with dynamic mapconfig

### ISSUE THREAD

**Issue by saimonsez** [hazelcast/hazelcast#13840]
Adding the following dynamic map config on a Hazelcast 3.9.3 Cluster deployed on OpenShift 3.6 used to work fine:

`
@Bean
    public HazelcastInstance hazelcastClientInstance() {
        final ClientConfig clientConfig = new ClientConfig();
        clientConfig.setNetworkConfig(new ClientNetworkConfig().setConnectionAttemptLimit(10).setAddresses(Collections.singletonList("host")).setRedoOperation(true));
        clientConfig.setGroupConfig(new GroupConfig("groupName", "groupPassword"));
        clientConfig.setSerializationConfig(serializationConfig());
        HazelcastInstance instance = HazelcastClient.newHazelcastClient(clientConfig);
        instance.getConfig().addMapConfig(new MapConfig()
                .setName("my-map-*")
                .setTimeToLiveSeconds(60)
                .setEvictionPolicy(EvictionPolicy.LRU)
                .setMaxIdleSeconds(0)
                .setAsyncBackupCount(1)
                .setMaxSizeConfig(new MaxSizeConfig().setMaxSizePolicy(MaxSizeConfig.MaxSizePolicy.PER_NODE).setSize(200_000))
                .setBackupCount(0));
        return instance;
    }
`
However, with Hazelcast 3.10.x I'm getting a timeout exception:
'
[2018-09-26 07:20:34,722] [hz.client_0.cluster-] INFO  com.hazelcast.client.connection.ClientConnectionManager - corid= hz.client_0 [hazelcast-dev] [3.10.2] Trying to connect to [hazelcast-dev]:5701 as owner member
[2018-09-26 07:20:34,922] [hz.client_0.internal-3] INFO  com.hazelcast.client.connection.ClientConnectionManager - corid= hz.client_0 [hazelcast-dev] [3.10.2] Setting ClientConnection{alive=true, connectionId=1, channel=NioChannel{/10.1.23.138:44003->hazelcast-dev/10.1.17.99:5701}, remoteEndpoint=[10.1.17.99]:5701, lastReadTime=2018-09-26 07:20:34.841, lastWriteTime=2018-09-26 07:20:34.837, closedTime=never, lastHeartbeatRequested=never, lastHeartbeatReceived=never, connected server version=3.10.2} as owner with principal ClientPrincipal{uuid='f1f8e393-7e36-48b4-9c8c-ca48163abae3', ownerUuid='17b697ef-8124-44be-bba8-2a782888420e'}
[2018-09-26 07:20:34,922] [hz.client_0.internal-3] INFO  com.hazelcast.client.connection.ClientConnectionManager - corid= hz.client_0 [hazelcast-dev] [3.10.2] Authenticated with server [10.1.17.99]:5701, server version:3.10.2 Local address: /10.1.23.138:44003
[2018-09-26 07:20:34,940] [hz.client_0.event-2] INFO  com.hazelcast.client.spi.impl.ClientMembershipListener - corid= hz.client_0 [hazelcast-dev] [3.10.2] 

Members [2] {
	Member [10.1.27.184]:5701 - ab6e8aa2-c0ce-4c5a-9575-889ac8723468
	Member [10.1.17.99]:5701 - 17b697ef-8124-44be-bba8-2a782888420e
}

[2018-09-26 07:20:34,942] [hz.client_0.cluster-] INFO  com.hazelcast.core.LifecycleService - corid= hz.client_0 [hazelcast-dev] [3.10.2] HazelcastClient 3.10.2 (20180606 - 84cfd49) is CLIENT_CONNECTED
[2018-09-26 07:20:34,943] [main] INFO  com.hazelcast.internal.diagnostics.Diagnostics - corid= hz.client_0 [hazelcast-dev] [3.10.2] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
[2018-09-26 07:22:36,257] [main] WARN  org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext - corid= Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hazelcastInstance' defined in class path resource [config/HazelcastAutoConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.hazelcast.core.HazelcastInstance]: Factory method 'hazelcastClientInstance' threw exception; nested exception is com.hazelcast.core.OperationTimeoutException: ClientInvocation{clientMessage = ClientMessage{length=22, correlationId=228, operation=null, messageType=1e0e, partitionId=-1, isComplete=false, isRetryable=false, isEvent=false, writeOffset=0}, objectName = null, target = random, sendConnection = ClientConnection{alive=true, connectionId=2, channel=NioChannel{/10.1.23.138:45403->/10.1.27.184:5701}, remoteEndpoint=[10.1.27.184]:5701, lastReadTime=2018-09-26 07:22:36.248, lastWriteTime=2018-09-26 07:22:36.246, closedTime=never, lastHeartbeatRequested=never, lastHeartbeatReceived=never, connected server version=3.10.2}} timed out because exception occurred after client invocation timeout 120000 ms. Current time: 2018-09-26 07:22:36.249. Start time: 2018-09-26 07:20:35.535. Total elapsed time: 120714 ms. 
[2018-09-26 07:22:36,263] [main] INFO  org.apache.catalina.core.StandardService - corid= Stopping service [Tomcat]
[2018-09-26 07:22:36,431] [main] INFO  org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener - corid= 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
[2018-09-26 07:22:36,732] [main] ERROR org.springframework.boot.SpringApplication - corid= Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hazelcastInstance' defined in class path resource [config/HazelcastAutoConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.hazelcast.core.HazelcastInstance]: Factory method 'hazelcastClientInstance' threw exception; nested exception is com.hazelcast.core.OperationTimeoutException: ClientInvocation{clientMessage = ClientMessage{length=22, correlationId=228, operation=null, messageType=1e0e, partitionId=-1, isComplete=false, isRetryable=false, isEvent=false, writeOffset=0}, objectName = null, target = random, sendConnection = ClientConnection{alive=true, connectionId=2, channel=NioChannel{/10.1.23.138:45403->/10.1.27.184:5701}, remoteEndpoint=[10.1.27.184]:5701, lastReadTime=2018-09-26 07:22:36.248, lastWriteTime=2018-09-26 07:22:36.246, closedTime=never, lastHeartbeatRequested=never, lastHeartbeatReceived=never, connected server version=3.10.2}} timed out because exception occurred after client invocation timeout 120000 ms. Current time: 2018-09-26 07:22:36.249. Start time: 2018-09-26 07:20:35.535. Total elapsed time: 120714 ms. 
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:590) ~[spring-beans-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1247) ~[spring-beans-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1096) ~[spring-beans-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:535) ~[spring-beans-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:495) ~[spring-beans-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317) ~[spring-beans-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315) ~[spring-beans-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:304) ~[spring-beans-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1089) ~[spring-context-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:859) ~[spring-context-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550) ~[spring-context-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140) ~[spring-boot-2.0.5.RELEASE.jar!/:2.0.5.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:780) [spring-boot-2.0.5.RELEASE.jar!/:2.0.5.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:412) [spring-boot-2.0.5.RELEASE.jar!/:2.0.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:333) [spring-boot-2.0.5.RELEASE.jar!/:2.0.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1277) [spring-boot-2.0.5.RELEASE.jar!/:2.0.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1265) [spring-boot-2.0.5.RELEASE.jar!/:2.0.5.RELEASE]
	at MyApp.main(MyApp.java:26) [classes!/:1.166.3-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_181]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [app.jar:1.166.3-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [app.jar:1.166.3-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [app.jar:1.166.3-SNAPSHOT]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [app.jar:1.166.3-SNAPSHOT]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.hazelcast.core.HazelcastInstance]: Factory method 'hazelcastClientInstance' threw exception; nested exception is com.hazelcast.core.OperationTimeoutException: ClientInvocation{clientMessage = ClientMessage{length=22, correlationId=228, operation=null, messageType=1e0e, partitionId=-1, isComplete=false, isRetryable=false, isEvent=false, writeOffset=0}, objectName = null, target = random, sendConnection = ClientConnection{alive=true, connectionId=2, channel=NioChannel{/10.1.23.138:45403->/10.1.27.184:5701}, remoteEndpoint=[10.1.27.184]:5701, lastReadTime=2018-09-26 07:22:36.248, lastWriteTime=2018-09-26 07:22:36.246, closedTime=never, lastHeartbeatRequested=never, lastHeartbeatReceived=never, connected server version=3.10.2}} timed out because exception occurred after client invocation timeout 120000 ms. Current time: 2018-09-26 07:22:36.249. Start time: 2018-09-26 07:20:35.535. Total elapsed time: 120714 ms. 
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:582) ~[spring-beans-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
	... 28 common frames omitted
Caused by: com.hazelcast.core.OperationTimeoutException: ClientInvocation{clientMessage = ClientMessage{length=22, correlationId=228, operation=null, messageType=1e0e, partitionId=-1, isComplete=false, isRetryable=false, isEvent=false, writeOffset=0}, objectName = null, target = random, sendConnection = ClientConnection{alive=true, connectionId=2, channel=NioChannel{/10.1.23.138:45403->/10.1.27.184:5701}, remoteEndpoint=[10.1.27.184]:5701, lastReadTime=2018-09-26 07:22:36.248, lastWriteTime=2018-09-26 07:22:36.246, closedTime=never, lastHeartbeatRequested=never, lastHeartbeatReceived=never, connected server version=3.10.2}} timed out because exception occurred after client invocation timeout 120000 ms. Current time: 2018-09-26 07:22:36.249. Start time: 2018-09-26 07:20:35.535. Total elapsed time: 120714 ms. 
	at com.hazelcast.client.spi.impl.ClientInvocation.newOperationTimeoutException(ClientInvocation.java:344) ~[hazelcast-all-3.10.2.jar!/:3.10.2]
	at com.hazelcast.client.spi.impl.ClientInvocation.notifyException(ClientInvocation.java:241) ~[hazelcast-all-3.10.2.jar!/:3.10.2]
	at com.hazelcast.client.spi.impl.ClientResponseHandlerSupplier.handleClientMessage(ClientResponseHandlerSupplier.java:134) ~[hazelcast-all-3.10.2.jar!/:3.10.2]
	at com.hazelcast.client.spi.impl.ClientResponseHandlerSupplier.process(ClientResponseHandlerSupplier.java:115) ~[hazelcast-all-3.10.2.jar!/:3.10.2]
	at com.hazelcast.client.spi.impl.ClientResponseHandlerSupplier.access$500(ClientResponseHandlerSupplier.java:50) ~[hazelcast-all-3.10.2.jar!/:3.10.2]
	at com.hazelcast.client.spi.impl.ClientResponseHandlerSupplier$ResponseThread.doRun(ClientResponseHandlerSupplier.java:168) ~[hazelcast-all-3.10.2.jar!/:3.10.2]
	at com.hazelcast.client.spi.impl.ClientResponseHandlerSupplier$ResponseThread.run(ClientResponseHandlerSupplier.java:152) ~[hazelcast-all-3.10.2.jar!/:3.10.2]
	at ------ submitted from ------.(Unknown Source) ~[na:na]
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:96) ~[hazelcast-all-3.10.2.jar!/:3.10.2]
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:33) ~[hazelcast-all-3.10.2.jar!/:3.10.2]
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:162) ~[hazelcast-all-3.10.2.jar!/:3.10.2]
	at com.hazelcast.client.impl.ClientDynamicClusterConfig.invoke(ClientDynamicClusterConfig.java:1206) ~[hazelcast-all-3.10.2.jar!/:3.10.2]
	at com.hazelcast.client.impl.ClientDynamicClusterConfig.addMapConfig(ClientDynamicClusterConfig.java:156) ~[hazelcast-all-3.10.2.jar!/:3.10.2]
	at ch.config.HazelcastAutoConfig.hazelcastClientInstance(HazelcastAutoConfig.java:66) ~[classes!/:1.166.3-SNAPSHOT]
	at ch.config.HazelcastAutoConfig$$EnhancerBySpringCGLIB$$4e1d13c4.CGLIB$hazelcastClientInstance$0(<generated>) ~[classes!/:1.166.3-SNAPSHOT]
	at ch.config.HazelcastAutoConfig$$EnhancerBySpringCGLIB$$4e1d13c4$$FastClassBySpringCGLIB$$a08dcd77.invoke(<generated>) ~[classes!/:1.166.3-SNAPSHOT]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:365) ~[spring-context-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
	at ch.config.HazelcastAutoConfig$$EnhancerBySpringCGLIB$$4e1d13c4.hazelcastClientInstance(<generated>) ~[classes!/:1.166.3-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_181]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
	... 29 common frames omitted
Caused by: com.hazelcast.config.ConfigurationException: Cannot add a dynamic configuration 'MapConfig{name='my-map-*', inMemoryFormat=BINARY', backupCount=0, asyncBackupCount=1, timeToLiveSeconds=259200, maxIdleSeconds=0, evictionPolicy='LRU', mapEvictionPolicy='com.hazelcast.map.eviction.LRUEvictionPolicy@45cd5c81', evictionPercentage=25, minEvictionCheckMillis=100, maxSizeConfig=MaxSizeConfig{maxSizePolicy='PER_NODE', size=200000}, readBackupData=false, hotRestart=HotRestartConfig{enabled=false, fsync=false}, nearCacheConfig=null, mapStoreConfig=MapStoreConfig{enabled=false, className='null', factoryClassName='null', writeDelaySeconds=0, writeBatchSize=1, implementation=null, factoryImplementation=null, properties={}, initialLoadMode=LAZY, writeCoalescing=true}, mergePolicyConfig=MergePolicyConfig{policy='com.hazelcast.spi.merge.PutIfAbsentMergePolicy', batchSize=100}, wanReplicationRef=null, entryListenerConfigs=null, mapIndexConfigs=[], mapAttributeConfigs=[], quorumName=null, queryCacheConfigs=null, cacheDeserializedValues=INDEX_ONLY}' as there is already a conflicting configuration 'MapConfig{name='my-map-*', inMemoryFormat=BINARY', backupCount=0, asyncBackupCount=1, timeToLiveSeconds=259200, maxIdleSeconds=0, evictionPolicy='LRU', mapEvictionPolicy='com.hazelcast.map.eviction.LRUEvictionPolicy@45cd5c81', evictionPercentage=25, minEvictionCheckMillis=100, maxSizeConfig=MaxSizeConfig{maxSizePolicy='PER_NODE', size=200000}, readBackupData=false, hotRestart=HotRestartConfig{enabled=false, fsync=false}, nearCacheConfig=null, mapStoreConfig=MapStoreConfig{enabled=false, className='null', factoryClassName='null', writeDelaySeconds=0, writeBatchSize=1, implementation=null, factoryImplementation=null, properties={}, initialLoadMode=LAZY, writeCoalescing=true}, mergePolicyConfig=MergePolicyConfig{policy='com.hazelcast.map.merge.PutIfAbsentMapMergePolicy', batchSize=100}, wanReplicationRef=null, entryListenerConfigs=[], mapIndexConfigs=[], mapAttributeConfigs=[], quorumNa
me=null, queryCacheConfigs=[], cacheDeserializedValues=INDEX_ONLY}'
	at com.hazelcast.internal.dynamicconfig.ClusterWideConfigurationService.checkCurrentConfigNullOrEqual(ClusterWideConfigurationService.java:402) ~[hazelcast-all-3.10.2.jar!/:3.10.2]
	at com.hazelcast.internal.dynamicconfig.ClusterWideConfigurationService.registerConfigLocally(ClusterWideConfigurationService.java:360) ~[hazelcast-all-3.10.2.jar!/:3.10.2]
	at com.hazelcast.internal.dynamicconfig.AddDynamicConfigOperation.run(AddDynamicConfigOperation.java:48) ~[hazelcast-all-3.10.2.jar!/:3.10.2]
	at com.hazelcast.spi.Operation.call(Operation.java:148) ~[hazelcast-all-3.10.2.jar!/:3.10.2]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:202) ~[hazelcast-all-3.10.2.jar!/:3.10.2]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:191) ~[hazelcast-all-3.10.2.jar!/:3.10.2]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:406) ~[hazelcast-all-3.10.2.jar!/:3.10.2]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:433) ~[hazelcast-all-3.10.2.jar!/:3.10.2]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:581) ~[hazelcast-all-3.10.2.jar!/:3.10.2]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:566) ~[hazelcast-all-3.10.2.jar!/:3.10.2]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:525) ~[hazelcast-all-3.10.2.jar!/:3.10.2]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:215) ~[hazelcast-all-3.10.2.jar!/:3.10.2]
	at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.invokeOnTarget(OperationServiceImpl.java:321) ~[hazelcast-all-3.10.2.jar!/:3.10.2]
	at com.hazelcast.internal.util.InvocationUtil$InvokeOnMemberFunction.invokeOnMember(InvocationUtil.java:165) ~[hazelcast-all-3.10.2.jar!/:3.10.2]
	at com.hazelcast.internal.util.InvocationUtil$InvokeOnMemberFunction.apply(InvocationUtil.java:142) ~[hazelcast-all-3.10.2.jar!/:3.10.2]
	at com.hazelcast.internal.util.InvocationUtil$InvokeOnMemberFunction.apply(InvocationUtil.java:119) ~[hazelcast-all-3.10.2.jar!/:3.10.2]
	at com.hazelcast.util.IterableUtil$2.next(IterableUtil.java:60) ~[hazelcast-all-3.10.2.jar!/:3.10.2]
	at com.hazelcast.internal.util.futures.ChainingFuture.<init>(ChainingFuture.java:49) ~[hazelcast-all-3.10.2.jar!/:3.10.2]
	at com.hazelcast.internal.util.InvocationUtil.invokeOnStableClusterSerial(InvocationUtil.java:87) ~[hazelcast-all-3.10.2.jar!/:3.10.2]
	at com.hazelcast.internal.dynamicconfig.ClusterWideConfigurationService.broadcastConfigAsync(ClusterWideConfigurationService.java:246) ~[hazelcast-all-3.10.2.jar!/:3.10.2]
	at com.hazelcast.client.impl.protocol.task.dynamicconfig.AbstractAddConfigMessageTask.processMessage(AbstractAddConfigMessageTask.java:73) ~[hazelcast-all-3.10.2.jar!/:3.10.2]
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:123) ~[hazelcast-all-3.10.2.jar!/:3.10.2]
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.doRun(AbstractMessageTask.java:111) ~[hazelcast-all-3.10.2.jar!/:3.10.2]
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:101) ~[hazelcast-all-3.10.2.jar!/:3.10.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_181]
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64) ~[hazelcast-all-3.10.2.jar!/:3.10.2]
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80) ~[hazelcast-all-3.10.2.jar!/:3.10.2]
	at ------ submitted from ------.(Unknown Source) ~[na:na]
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:127) ~[hazelcast-all-3.10.2.jar!/:3.10.2]
	at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run(AbstractInvocationFuture.java:250) ~[hazelcast-all-3.10.2.jar!/:3.10.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_181]
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64) ~[hazelcast-all-3.10.2.jar!/:3.10.2]
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80) ~[hazelcast-all-3.10.2.jar!/:3.10.2][2018-09-26 07:20:35,550] [hz.client_0.internal-3] INFO  com.hazelcast.client.connection.ClientConnectionManager - corid= hz.client_0 [hazelcast-dev] [3.10.2] Authenticated with server [10.1.27.184]:5701, server version:3.10.2 Local address: /10.1.23.138:45403
'
I cannot reproduce this behaviour on my local machine, but only on OpenShift. 
If I remove the dynamic configuration code snippet, everything works as expected.

**Comment by tkountis** [comment]
@saimonsez can you please also share the `hazelcast.xml` config?

**Comment by saimonsez** [comment]
````xml
<?xml version="1.0" encoding="UTF-8"?>
<hazelcast xsi:schemaLocation="http://www.hazelcast.com/schema/config hazelcast-config-3.7.xsd"
                   xmlns="http://www.hazelcast.com/schema/config"
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
      <group>
                <name>hazelcast-test</name>
                <password>hazelcast-test</password>
        </group>
        <properties>
                <property name="hazelcast.discovery.enabled">true</property>
                <property name="hazelcast.logging.type">slf4j</property>
        </properties>

        <network>
                <port port-count="1" auto-increment="false">5701</port>
                <reuse-address>true</reuse-address>
                <join>
                        <multicast enabled="false"/>
                        <tcp-ip enabled="false"/>

                        <discovery-strategies>
                                <discovery-strategy enabled="true" class="com.hazelcast.kubernetes.HazelcastKubernetesDiscoveryStrategy">
                                        <properties>
                                                <property name="service-name">hazelcast-test</property>
                                                <property name="namespace">hazelcast-test</property>
                                                <property name="service-label-name"></property>
                        <property name="service-label-value"></property>
                                        </properties>
                                </discovery-strategy>
                        </discovery-strategies>
                </join>
        </network>
        <quorum name="quorumRuleForCluster" enabled="true">
                <quorum-size>2</quorum-size>
        </quorum>
        <map name="default">
                <quorum-ref>quorumRuleForCluster</quorum-ref>
                <time-to-live-seconds>1200</time-to-live-seconds>
                <max-idle-seconds>1200</max-idle-seconds>
                <eviction-policy>LRU</eviction-policy>
                <max-size policy="PER_NODE">200000</max-size>
                <eviction-percentage>25</eviction-percentage>
                <min-eviction-check-millis>100</min-eviction-check-millis>
                <backup-count>1</backup-count>
                <async-backup-count>0</async-backup-count>
                <read-backup-data>false</read-backup-data>
        </map>

        <management-center enabled="true">http://hazelcast-mgt/hazelcast-mancenter</management-center>

</hazelcast>
````

**Comment by mdogan** [comment]
It seems cause of the failure is following exception:
```
Caused by: com.hazelcast.config.ConfigurationException: Cannot add a dynamic configuration 'MapConfig{name='my-map-*', inMemoryFormat=BINARY', backupCount=0, asyncBackupCount=1, timeToLiveSeconds=259200, maxIdleSeconds=0, evictionPolicy='LRU', mapEvictionPolicy='com.hazelcast.map.eviction.LRUEvictionPolicy@45cd5c81', evictionPercentage=25, minEvictionCheckMillis=100, maxSizeConfig=MaxSizeConfig{maxSizePolicy='PER_NODE', size=200000}, readBackupData=false, hotRestart=HotRestartConfig{enabled=false, fsync=false}, nearCacheConfig=null, mapStoreConfig=MapStoreConfig{enabled=false, className='null', factoryClassName='null', writeDelaySeconds=0, writeBatchSize=1, implementation=null, factoryImplementation=null, properties={}, initialLoadMode=LAZY, writeCoalescing=true}, mergePolicyConfig=MergePolicyConfig{policy='com.hazelcast.spi.merge.PutIfAbsentMergePolicy', batchSize=100}, wanReplicationRef=null, entryListenerConfigs=null, mapIndexConfigs=[], mapAttributeConfigs=[], quorumName=null, queryCacheConfigs=null, cacheDeserializedValues=INDEX_ONLY}' as there is already a conflicting configuration 'MapConfig{name='my-map-*', inMemoryFormat=BINARY', backupCount=0, asyncBackupCount=1, timeToLiveSeconds=259200, maxIdleSeconds=0, evictionPolicy='LRU', mapEvictionPolicy='com.hazelcast.map.eviction.LRUEvictionPolicy@45cd5c81', evictionPercentage=25, minEvictionCheckMillis=100, maxSizeConfig=MaxSizeConfig{maxSizePolicy='PER_NODE', size=200000}, readBackupData=false, hotRestart=HotRestartConfig{enabled=false, fsync=false}, nearCacheConfig=null, mapStoreConfig=MapStoreConfig{enabled=false, className='null', factoryClassName='null', writeDelaySeconds=0, writeBatchSize=1, implementation=null, factoryImplementation=null, properties={}, initialLoadMode=LAZY, writeCoalescing=true}, mergePolicyConfig=MergePolicyConfig{policy='com.hazelcast.map.merge.PutIfAbsentMapMergePolicy', batchSize=100}, wanReplicationRef=null, entryListenerConfigs=[], mapIndexConfigs=[], mapAttributeConfigs=[], quorumNa
me=null, queryCacheConfigs=[], cacheDeserializedValues=INDEX_ONLY}'
```

Notice the difference between `mergePolicyConfig`s:

- `mergePolicyConfig=MergePolicyConfig{policy='com.hazelcast.spi.merge.PutIfAbsentMergePolicy', batchSize=100}`
- `mergePolicyConfig=MergePolicyConfig{policy='com.hazelcast.map.merge.PutIfAbsentMapMergePolicy', batchSize=100}`

But `mergePolicyConfig` is not configured in neither xml config nor via dynamic config. 

`PutIfAbsentMapMergePolicy` was default in 3.9.x: https://github.com/hazelcast/hazelcast/blob/v3.9.4/hazelcast/src/main/java/com/hazelcast/config/MapConfig.java#L96

But default merge policy changed to `PutIfAbsentMergePolicy ` in 3.10 with commit https://github.com/hazelcast/hazelcast/commit/2b7c0819ef93dffdf76c7f0e7abcaf03860e47f0#diff-40451a9ef0612cc8c226187ac603e3e6

**Comment by mmedenjak** [comment]
@saimonsez as @mdogan noticed, you are unable to add the config because a different one already exists with the same name (because of a changed default). Can you try adding the config with the same merge policy or under a different name?

**Comment by saimonsez** [comment]
@mmedenjak:
adding 
````
.setMergePolicyConfig(new MergePolicyConfig().setPolicy(PutIfAbsentMapMergePolicy.class.getName()))
````
to the mapconfig worked. I consider this as a workaround because

- having no specific merge policy should not lead to a timeout
- having no specific merge policy should be possible if the the map does not already exist

Thanks for your support.
