### ISSUE TITLE
Unblocking reads when owner lost and invocations enabled test failure

### ISSUE THREAD

**Issue by lazerion** [hazelcast/hazelcast#13851]
As can be seen [here](https://hazelcast-l337.ci.cloudbees.com/view/Integration%20Tests/job/client-resource-management/) unblocking read verification test began to fail starting from build 115.

* Steps
     * 1] Verify cluster formation till owner connection available
     * 2] Scale cluster given size that is 5
     * 3] Apply network package delay on owner for 5000ms total of 60secs
     * 4] Collect read-only statistics from client and verify exceptions 🚫 
     * 5] Collect locking statistics from client and verify exceptions

Statistic collection in order to verify unblocking reads fails at step 4.
Statistics are collected in [this class](https://github.com/hazelcast/hazelcast-qe/blob/master/it/client-resource-management/unblock-client/src/main/java/com/hazelcast/it/client/unblock/read/container/Task.java#L19)

During above scenario client logs exceed **7MB**.

Failing test case can be found [here](https://github.com/hazelcast/hazelcast-qe/blob/master/it/client-resource-management/runner/src/test/java/com/hazelcast/it/client/resource/management/runner/UnblockingReadsTest.java#L107)

Regarding logs from local run attached
[Archive.zip](https://github.com/hazelcast/hazelcast/files/2424318/Archive.zip)

Client and Member configurations attached
[configs.zip](https://github.com/hazelcast/hazelcast/files/2424324/configs.zip)

Regarding how to run tests on local is described in [README](https://github.com/hazelcast/hazelcast-qe/tree/master/it/client-resource-management)

**Comment by sancar** [comment]
While investigating the logs, I found a NPE exception which explains the failure 
```
2018-09-27T13:26:31.593451800Z 13:26:31:593 [hz.client_0.cluster-] WARN ClientConnectionManager - hz.client_0 [hz-crmi] [3.11-clientresourcemanagement] Exception during initial connection to [172.18.0.6]:5701, exception java.lang.NullPointerException
2018-09-27T13:26:31.594271700Z 13:26:31:594 [hz.client_0.cluster-] WARN ClientConnection - hz.client_0 [hz-crmi] [3.11-clientresourcemanagement] ClientConnection{alive=false, connectionId=3, channel=13:26:31 59407=>5701, remoteEndpoint=[172.18.0.6]:5701, lastReadTime=2018-09-27 13:26:31.591, lastWriteTime=2018-09-27 13:26:31.590, closedTime=2018-09-27 13:26:31.593, connected server version=3.11-clientresourcemanagement} closed. Reason: Could not connect to [172.18.0.6]:5701 as owner
2018-09-27T13:26:31.594299900Z java.lang.NullPointerException
2018-09-27T13:26:31.594742300Z 	at com.hazelcast.client.spi.ProxyManager.createCachesOnCluster(ProxyManager.java:493)
2018-09-27T13:26:31.594766800Z 	at com.hazelcast.client.spi.ProxyManager.createDistributedObjectsOnCluster(ProxyManager.java:488)
2018-09-27T13:26:31.594779000Z 	at com.hazelcast.client.impl.clientside.HazelcastClientInstanceImpl.onClusterConnect(HazelcastClientInstanceImpl.java:593)
2018-09-27T13:26:31.594790300Z 	at com.hazelcast.client.connection.nio.ClusterConnector.connectAsOwner(ClusterConnector.java:137)
2018-09-27T13:26:31.594798000Z 	at com.hazelcast.client.connection.nio.ClusterConnector.connectToClusterInternal(ClusterConnector.java:194)
2018-09-27T13:26:31.594805700Z 	at com.hazelcast.client.connection.nio.ClusterConnector.access$400(ClusterConnector.java:56)
2018-09-27T13:26:31.594813400Z 	at com.hazelcast.client.connection.nio.ClusterConnector$2.call(ClusterConnector.java:215)
2018-09-27T13:26:31.594821100Z 	at com.hazelcast.client.connection.nio.ClusterConnector$2.call(ClusterConnector.java:211)
2018-09-27T13:26:31.594840400Z 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2018-09-27T13:26:31.594852200Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2018-09-27T13:26:31.594869900Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2018-09-27T13:26:31.594886600Z 	at java.lang.Thread.run(Thread.java:748)
2018-09-27T13:26:31.594895900Z 	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
2018-09-27T13:26:31.594905700Z 	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
```

The pr that made the change is this
https://github.com/hazelcast/hazelcast/pull/13810

I am preparing a fix.
