### ISSUE TITLE
HazelcastSerializationException: There is no suitable de-serializer in CustomSerializer

### ISSUE THREAD

**Issue by lshens** [hazelcast/hazelcast#13874]
Hi,

I implemented a **Custom Serializer** using the interface _StreamSerializer_ and I got the _HazelcastSerializationException_ in my Raspberry Pi3. I have two members in my cluster; one is my local machine (Linux and jar compiled in Java 8 64bits) and the other one is my Raspberry Pi3 (Linux and compiled in Java ArmV7) and both are with Hazelcast version **3.10.5** and Spring-Boot version **1.4.3.RELEASE**.

The _StreamSerializer_ implementation:

```
public class JsonStreamSerializer<T> implements StreamSerializer<T> {

    @Getter
    private final Class<T> type;
    private final int typeId;

    public JsonStreamSerializer(Class<T> type, int typeId) {
        this.type = type;
        this.typeId = typeId;
    }

    @Override
    public void write(ObjectDataOutput out, Object object) throws IOException {
        out.write(MAPPER.writeValueAsString(object).getBytes());
    }

    @Override
    public T read(ObjectDataInput in) throws IOException {
        return MAPPER.configure(FAIL_ON_UNKNOWN_PROPERTIES, FALSE).readValue(in, getType());
    }

    @Override
    public int getTypeId() {
        return typeId;
    }

    @Override
    public void destroy() {
    }
}
```

The configuration:

```
config.getSerializationConfig().addSerializerConfig(new SerializerConfig()
                .setImplementation(new JsonStreamSerializer<>(Foo.class, 6))
                .setTypeClass(Foo.class));
```

The Foo class:

```
@Entity
@Table(name = "foo")
@EqualsAndHashCode(callSuper = true)
@Data
public class Foo extends AbstractBaseEntity {

    @Column(name = "bar_id")
    @JsonProperty("bar_id")
    private String barId;

    @Column(name = "name")
    private String name;

    @Enumerated(EnumType.STRING)
    @Column(name = "type")
    private BarTypeEnum type;

    @Column(name = "reference")
    private Long reference;

    public Station() {
    }
}
```

The exception:

```
com.hazelcast.nio.serialization.HazelcastSerializationException: There is no suitable de-serializer for type 6. This exception is likely to be caused by differences in the serialization configuration between members or between clients and members.
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.newHazelcastSerializationException(AbstractSerializationService.java:238) ~[hazelcast-3.10.5.jar:3.10.5]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:182) ~[hazelcast-3.10.5.jar:3.10.5]
	at com.hazelcast.map.impl.proxy.MapProxySupport.toObject(MapProxySupport.java:1169) ~[hazelcast-3.10.5.jar:3.10.5]
	at com.hazelcast.map.impl.proxy.MapProxyImpl.get(MapProxyImpl.java:116) ~[hazelcast-3.10.5.jar:3.10.5]
	at org.springframework.data.hazelcast.HazelcastKeyValueAdapter.get(HazelcastKeyValueAdapter.java:68) ~[spring-data-hazelcast-1.0.jar:na]
	at org.springframework.data.keyvalue.core.AbstractKeyValueAdapter.get(AbstractKeyValueAdapter.java:66) ~[spring-data-keyvalue-1.1.6.RELEASE.jar:na]
	at org.springframework.data.keyvalue.core.KeyValueTemplate$4.doInKeyValue(KeyValueTemplate.java:274) ~[spring-data-keyvalue-1.1.6.RELEASE.jar:na]
	at org.springframework.data.keyvalue.core.KeyValueTemplate.execute(KeyValueTemplate.java:377) ~[spring-data-keyvalue-1.1.6.RELEASE.jar:na]
	at org.springframework.data.keyvalue.core.KeyValueTemplate.findById(KeyValueTemplate.java:268) ~[spring-data-keyvalue-1.1.6.RELEASE.jar:na]
	at org.springframework.data.keyvalue.repository.support.SimpleKeyValueRepository.findOne(SimpleKeyValueRepository.java:124) ~[spring-data-keyvalue-1.1.6.RELEASE.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_181]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.executeMethodOn(RepositoryFactorySupport.java:503) ~[spring-data-commons-1.12.6.RELEASE.jar:na]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:488) ~[spring-data-commons-1.12.6.RELEASE.jar:na]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:460) ~[spring-data-commons-1.12.6.RELEASE.jar:na]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.5.RELEASE.jar:4.3.5.RELEASE]
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:61) ~[spring-data-commons-1.12.6.RELEASE.jar:na]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.5.RELEASE.jar:4.3.5.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) ~[spring-aop-4.3.5.RELEASE.jar:4.3.5.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.5.RELEASE.jar:4.3.5.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213) ~[spring-aop-4.3.5.RELEASE.jar:4.3.5.RELEASE]
	at com.sun.proxy.$Proxy146.findOne(Unknown Source) ~[na:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_181]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333) ~[spring-aop-4.3.5.RELEASE.jar:4.3.5.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190) ~[spring-aop-4.3.5.RELEASE.jar:4.3.5.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.3.5.RELEASE.jar:4.3.5.RELEASE]
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:136) ~[spring-tx-4.3.5.RELEASE.jar:4.3.5.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.5.RELEASE.jar:4.3.5.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213) ~[spring-aop-4.3.5.RELEASE.jar:4.3.5.RELEASE]
	at com.sun.proxy.$Proxy146.findOne(Unknown Source) ~[na:na]
```

I  have read the [Documentation](https://docs.hazelcast.org/docs/latest-development/manual/html/Serialization/Overview.html), but didn't find any help. Any one as an ideia of this problem

**Comment by sancar** [comment]
Did you put the serializer config on both members ? It looks like one of them is missing the related config.

**Comment by lshens** [comment]
Hello, @sancar !

Yes, I put the same serializers on both members. One think that a notice is this error happen because one member has a jar compiled with the Java for arm and the other has a jar compiled with the Java for 64 bits.

**Comment by mmedenjak** [comment]
Hi @lshens ! Does the error go away if you compile and run both jars with the same java?
Can you post your reproducer here?
