### ISSUE TITLE
Irregular WAN replication failure after RU completed and Merkle Tree enabled

### ISSUE THREAD

**Issue by lazerion** [hazelcast/hazelcast#13896]
**Deployment**
1] 2 Clusters deployed as A, B
     Cluster A Versions 3.10 [Active]
     Cluster B Versions 3.10 [Active]
     Each contains 2 member
2] Deployed client in A running on Put/Get operations on IMap
3] disable merkle tree for WAN sync when rolling up to 3.11
      Target version will be 3.11 on both Cluster-A and Cluster-B

**Steps**
1] Wait for cluster sanity, client A and B should see 2 member
2] Begin IMap (merkle tree) operations on Cluster-A and Cluster-B
4] Verify RU and change versions to 3.11 with disable merkle tree usage
5] Verify Rolling Restart with merkle tree usage enabled on both clusters
6] Verify IMap replication between clusters 🚫 

When we run regarding [test case](https://github.com/hazelcast/hazelcast-qe/blob/master/it/wan/runner/src/test/java/com/hazelcast/wan/it/runner/MerkleTreeTest.java#L211) until failure, we fail at step 6 and got below **logs after step 5**.
[Archive.zip](https://github.com/hazelcast/hazelcast/files/2442947/Archive.zip)

Above test case uses deployment files [here](https://github.com/hazelcast/hazelcast-qe/tree/master/it/wan/runner/src/test/resources/merkle)

Configuration files can be traced from deployment files and can be found [here](https://github.com/hazelcast/hazelcast-qe/tree/master/it/wan/runner/src/test/resources/hz/server/merkle)

Below log segment noticed from cluster-A logs
```
2018-10-03T16:05:30.408734000Z java.io.EOFException: Remote socket closed!
2018-10-03T16:05:30.408744900Z 	at com.hazelcast.internal.networking.nio.NioInboundPipeline.process(NioInboundPipeline.java:116)
2018-10-03T16:05:30.408755600Z 	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKey(NioThread.java:368)
2018-10-03T16:05:30.408766300Z 	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKeys(NioThread.java:353)
2018-10-03T16:05:30.408776700Z 	at com.hazelcast.internal.networking.nio.NioThread.selectLoop(NioThread.java:279)
2018-10-03T16:05:30.408787200Z 	at com.hazelcast.internal.networking.nio.NioThread.run(NioThread.java:234)
2018-10-03T16:05:30.408797600Z 
```

**Comment by lazerion** [comment]
Closed to transfer EE repo.
