### ISSUE TITLE
java.io.IOException: Packet not send to

### ISSUE THREAD

**Issue by ksv510** [hazelcast/hazelcast#13926]
We have two servers. Each contains hazelcast server. Also, each server contains hazelcast client and the client connects to the localhost server. Here it is hazelcast-client.xml:

```<connection-strategy reconnect-mode="ASYNC"  />

    <network>
        <redo-operation>true</redo-operation>
        <connection-attempt-limit>1200</connection-attempt-limit>
        <connection-attempt-period>3000</connection-attempt-period>
        <cluster-members>
            <address>127.0.0.1:5400</address>
        </cluster-members>
    </network>

    <near-cache name="*">
        <in-memory-format>OBJECT</in-memory-format>
    </near-cache>```

 And almost all the time everything works great, but sometimes there is a network issue on one of the servers an we get next stack traces:

```com.hazelcast.core.OperationTimeoutException: ClientInvocation{clientMessage = ClientMessage{length=124, correlationId=764556, operation=Cache.get, messageType=150e, partitionId=18, isComplete=true, isRetryable=true, isEvent=false, writeOffset=0}, objectName = cache.CachedOriginDomains, target = partition 18, sendConnection = null} timed out because exception occurred after client invocation timeout 120000 ms. Current time: 2018-10-08 06:51:54.374. Start time: 2018-10-08 06:49:54.190. Total elapsed time: 120184 ms. 
	at com.hazelcast.client.spi.impl.ClientInvocation.newOperationTimeoutException(ClientInvocation.java:309)
	at com.hazelcast.client.spi.impl.ClientInvocation.notifyException(ClientInvocation.java:216)
	at com.hazelcast.client.spi.impl.ClientInvocation.invokeOnSelection(ClientInvocation.java:160)
	at com.hazelcast.client.spi.impl.ClientInvocation.retry(ClientInvocation.java:178)
	at com.hazelcast.client.spi.impl.ClientInvocation.run(ClientInvocation.java:166)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at com.hazelcast.util.executor.LoggingScheduledExecutor$LoggingDelegatingFuture.run(LoggingScheduledExecutor.java:160)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:96)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:33)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:183)
	at com.hazelcast.client.util.ClientDelegatingFuture.get(ClientDelegatingFuture.java:137)
	at com.hazelcast.client.util.ClientDelegatingFuture.get(ClientDelegatingFuture.java:128)
	at com.hazelcast.client.cache.impl.AbstractClientCacheProxy.getSyncInternal(AbstractClientCacheProxy.java:88)
	at com.hazelcast.client.cache.impl.NearCachedClientCacheProxy.getSyncInternal(NearCachedClientCacheProxy.java:129)
	at com.hazelcast.client.cache.impl.AbstractClientCacheProxy.get(AbstractClientCacheProxy.java:212)
	at com.hazelcast.client.cache.impl.ClientCacheProxy.get(ClientCacheProxy.java:94)
	at com.hazelcast.client.cache.impl.ClientCacheProxy.get(ClientCacheProxy.java:130)
Caused by: java.io.IOException: Packet not send to [app1.prod]:5400
	at com.hazelcast.client.spi.impl.AbstractClientInvocationService.send(AbstractClientInvocationService.java:127)
	at com.hazelcast.client.spi.impl.SmartClientInvocationService.invokeOnPartitionOwner(SmartClientInvocationService.java:49)
	at com.hazelcast.client.spi.impl.ClientInvocation.invokeOnSelection(ClientInvocation.java:150)
	at com.hazelcast.client.spi.impl.ClientInvocation.retry(ClientInvocation.java:178)
	at com.hazelcast.client.spi.impl.ClientInvocation.run(ClientInvocation.java:166)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at com.hazelcast.util.executor.LoggingScheduledExecutor$LoggingDelegatingFuture.run(LoggingScheduledExecutor.java:160)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)```

`app1.prod` it is the server with network issue

is there a possibility to configure the client to use only one server(localhost) and do not use other servers from cluster?

**Comment by sancar** [comment]
You can turn off the the smart routing. This way client will open only one connection to cluster. 
All operations to cluster, will go though single member.
```
<network>
        <smart-routing>false</smart-routing>
</network>
```

When this connection is dropped for some reason, client opens a new connection to one of the cluster members. If you want to avoid that also, you can configure a load balancer to return always same member address. 

https://docs.hazelcast.org/docs/3.10.5/manual/html-single/index.html#configuring-client-load-balancer

With this two config, client will always try to connect to the same member. 
Note that, when configured this way, client will still get the data from the second member. Only difference will be client use other member as proxy. If the second member is not reachable from other members, you will get timeout anyway. And eventually the second member will be kicked out from cluster.

**Comment by ksv510** [comment]
Thank you @sancar. Just to clarify, because I am not sure that I understand what do you mean when you say `second member`. Let say that we have two servers `S1` and `S2`. Also we have client `C1` with config
```
<network>
        <cluster-members>
            <smart-routing>false</smart-routing>
            <address>S1:5400</address>
        </cluster-members>
    </network>
```

and `C2` with config
```
<network>
        <cluster-members>
            <smart-routing>false</smart-routing>
            <address>S2:5400</address>
        </cluster-members>
    </network>
```

So where `C2` will always try to connect?  to `S1` or `S2` ?

**Comment by sancar** [comment]
C2 will connect to S2 at the beginning. Then it will be aware of all the cluster members. When it is disconnected temporarily, it will try to connect back to cluster. In that case, it will try both S1 and S2. 
If you want it to only try S2, you need to configure the load balancer.

**Comment by ksv510** [comment]
@sancar thank you very much. 

Documentation does not contain information about how `smart-routing` works https://docs.hazelcast.org/docs/3.10.5/manual/html-single/index.html#setting-smart-routing.  Should I create a new ticket for documentation issue?

**Comment by sancar** [comment]
How about this part ? 
https://docs.hazelcast.org/docs/3.10.5/manual/html-single/index.html#java-client-operation-modes

**Comment by ksv510** [comment]
Good enough )), but it would be great is you add a link that describes modes to this section https://docs.hazelcast.org/docs/3.10.5/manual/html-single/index.html#setting-smart-routing.

**Comment by Serdaro** [comment]
Added the link (https://github.com/hazelcast/hazelcast-reference-manual/commit/e5fab559850f212ecbce2bb565c3a59ef2e6899e).
