### ISSUE TITLE
Hazelcast 3.10.5: [Get|Set]Operation invocation failed to complete due to operation-heartbeat-timeout

### ISSUE THREAD

**Issue by markathomas** [hazelcast/hazelcast#13924]
After running fine for days my cluster just started failing this morning with timeouts.  Only a 2 node cluster with both nodes on the same host in docker containers.  Here's the stack trace:
```
com.hazelcast.core.OperationTimeoutException: GetOperation invocation failed to complete due to operation-heartbeat-timeout. Current time: 2018-10-08 08:19:11.608. Start time: 2018-10-08 08:18:50.609. Total elapsed time: 20999 ms. Last operation heartbeat: never. Last operation heartbeat from member: 2018-10-08 08:19:09.359. Invocation{op=com.hazelcast.map.impl.operation.GetOperation{serviceName='hz:impl:mapService', identityHash=608580207, partitionId=218, replicaIndex=0, callId=-89548030, invocationTime=1538986730609 (2018-10-08 08:18:50.609), waitTimeout=-1, callTimeout=10000, name=orgPastHourAlarms}, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=10000, firstInvocationTimeMs=1538986730609, firstInvocationTime='2018-10-08 08:18:50.609', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 00:00:00.000', target=[172.31.23.6]:5701, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=Connection[id=1, /172.17.0.2:48627->/172.31.23.6:5701, endpoint=[172.31.23.6]:5701, alive=true, type=MEMBER]}
        at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.newOperationTimeoutException(InvocationFuture.java:164)
        at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:106)
        at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:79)
        at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:162)
        at com.hazelcast.map.impl.proxy.MapProxySupport.invokeOperation(MapProxySupport.java:425)
        at com.hazelcast.map.impl.proxy.MapProxySupport.getInternal(MapProxySupport.java:347)
        at com.hazelcast.map.impl.proxy.MapProxyImpl.get(MapProxyImpl.java:116)
        at com.boxview.grid.data.hazelcast.HazelcastCacheDelegate.get(HazelcastCacheDelegate.java:93)
        at java.util.Map.getOrDefault(Map.java:588)
        at com.boxview.integration.server.alert.spacelabs.DefaultCachingService.addAlarmEntry(DefaultCachingService.java:230)
        at com.boxview.integration.server.alert.spacelabs.DefaultCachingService.handleAlert(DefaultCachingService.java:212)
        at com.boxview.integration.server.alert.spacelabs.DefaultCachingService.handleAlertSavedEvent(DefaultCachingService.java:190)
        at sun.reflect.GeneratedMethodAccessor280.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:95)
        at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:154)
        at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:80)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at com.boxview.concurrency.LoggingRunnable.run(LoggingRunnable.java:21)
        at java.lang.Thread.run(Thread.java:748)
```

After this exception the connection between the two nodes severed and never resumed.  Log files and a diagnostics file attached.

**Comment by markathomas** [comment]
[logs.zip](https://github.com/hazelcast/hazelcast/files/2455827/logs.zip)

**Comment by markathomas** [comment]
I should mention the nodes are on AWS using AWS Joiner so the times are sync'd to NTP.

**Comment by mdogan** [comment]
It seems, for some reason, `[172.31.23.6]:5702` was crashed and `[172.31.23.6]:5701` remained as a single node cluster. 
```
2018-10-08 08:23:58,834 com.hazelcast.nio.tcp.TcpIpConnectionErrorHandler WARN 
[hz.hazelcast-boxview-ackbar.cached.thread-37] [172.31.23.6]:5701 [boxview-prod-ackbar] 
[3.10.5] Removing connection to endpoint [172.31.23.6]:5702 
Cause => java.net.SocketException {Connection refused to address /172.31.23.6:5702}, Error-Count: 5

2018-10-08 08:23:58,838 com.hazelcast.internal.cluster.impl.MembershipManager INFO 
[hz.hazelcast-boxview-ackbar.cached.thread-37] [172.31.23.6]:5701 [boxview-prod-ackbar] 
[3.10.5] Removing Member [172.31.23.6]:5702 - 6f148b6b-c6e8-42de-a052-0eca5a4b8cad
```

Since both nodes are on the same machine, my assumption is, it crashed because of an OOM. 

On `[172.31.23.6]:5701`  heap memory usage is very high:
```
heap.memory.used=3.5G, heap.memory.free=265.0M, heap.memory.total=3.8G, 
heap.memory.max=3.8G, heap.memory.used/total=93.20%, heap.memory.used/max=93.20%,
```

`grid.log` file contains only logs from `[172.31.23.6]:5701`. Do you have logs from `[172.31.23.6]:5702` too?

**Comment by markathomas** [comment]
Unfortunately, only the singe file node2.log.  I have enabled diagnostics for node2 as well as of this morning but we unfortunately has to rollback.

I missed the heap usage.  That has to be the problem.  I bet GC was stalling the JVM long enough to block the operation timeout.  I'll look into that more.  Thank you for pointing it out.
