### ISSUE TITLE
LiteMemberClientMapNearCacheBasicTest test failures on IBM JDK

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#13949]
_maintenance-3.x_ (commit 4f044165fa040b77d58184e9eff51bd9e6d45328)

Following tests of LiteMemberClientMapNearCacheBasicTest fail:
* `whenGetAsyncIsUsedOnEmptyDataStructure_thenAlwaysReturnNullFromNearCache`
* `whenGetAsyncIsUsed_thenNearCacheShouldBePopulated`
* `whenRemoveAsyncIsUsed_thenNearCacheShouldBeInvalidated_onNearCacheAdapter`

Failed on IBM 7 builds:
* https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.maintenance-IbmJDK7/135/testReport/com.hazelcast.client.map.impl.nearcache/LiteMemberClientMapNearCacheBasicTest/whenGetAsyncIsUsedOnEmptyDataStructure_thenAlwaysReturnNullFromNearCache/
* https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.maintenance-IbmJDK7/135/testReport/com.hazelcast.client.map.impl.nearcache/LiteMemberClientMapNearCacheBasicTest/whenGetAsyncIsUsed_thenNearCacheShouldBePopulated/
* https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.maintenance-IbmJDK7/135/testReport/com.hazelcast.client.map.impl.nearcache/LiteMemberClientMapNearCacheBasicTest/whenRemoveAsyncIsUsed_thenNearCacheShouldBeInvalidated_onNearCacheAdapter/

Stacktrace for `whenGetAsyncIsUsedOnEmptyDataStructure_thenAlwaysReturnNullFromNearCache`:
```
java.lang.AssertionError: Could not get value for index 1 via getAsync() GetOperation invocation failed to complete due to operation-heartbeat-timeout. Current time: 2018-10-11 12:10:44.352. Start time: 2018-10-11 12:08:09.800. Total elapsed time: 154552 ms. Last operation heartbeat: never. Last operation heartbeat from member: 2018-10-11 12:10:00.870. Invocation{op=com.hazelcast.map.impl.operation.GetOperation{serviceName='hz:impl:mapService', identityHash=1818783743, partitionId=1, replicaIndex=0, callId=-6, invocationTime=1539259689800 (2018-10-11 12:08:09.800), waitTimeout=-1, callTimeout=60000, name=defaultNearCache}, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=60000, firstInvocationTimeMs=1539259689800, firstInvocationTime='2018-10-11 12:08:09.800', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 00:00:00.000', target=[127.0.0.1]:5186, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=MockConnection{localEndpoint=[127.0.0.1]:5270, remoteEndpoint=[127.0.0.1]:5186}}
	at com.hazelcast.internal.nearcache.NearCacheTestUtils.getFuture(NearCacheTestUtils.java:85)
	at com.hazelcast.internal.nearcache.AbstractNearCacheBasicTest.populateNearCache(AbstractNearCacheBasicTest.java:1645)
	at com.hazelcast.internal.nearcache.AbstractNearCacheBasicTest.whenGetIsUsedOnEmptyDataStructure_thenAlwaysReturnNullFromNearCache(AbstractNearCacheBasicTest.java:1471)
	at com.hazelcast.internal.nearcache.AbstractNearCacheBasicTest.whenGetAsyncIsUsedOnEmptyDataStructure_thenAlwaysReturnNullFromNearCache(AbstractNearCacheBasicTest.java:1451)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:95)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:56)
	at java.lang.reflect.Method.invoke(Method.java:620)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask.run(FutureTask.java:274)
	at java.lang.Thread.run(Thread.java:809)
```

Stacktrace for `whenGetAsyncIsUsed_thenNearCacheShouldBePopulated`:
```
java.lang.AssertionError: Could not get value for index 62 via getAsync() GetOperation invocation failed to complete due to operation-heartbeat-timeout. Current time: 2018-10-11 12:10:44.539. Start time: 2018-10-11 12:08:06.153. Total elapsed time: 158386 ms. Last operation heartbeat: never. Last operation heartbeat from member: 2018-10-11 12:10:00.830. Invocation{op=com.hazelcast.map.impl.operation.GetOperation{serviceName='hz:impl:mapService', identityHash=2116361382, partitionId=3, replicaIndex=0, callId=-67, invocationTime=1539259686152 (2018-10-11 12:08:06.152), waitTimeout=-1, callTimeout=60000, name=defaultNearCache}, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=60000, firstInvocationTimeMs=1539259686153, firstInvocationTime='2018-10-11 12:08:06.153', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 00:00:00.000', target=[127.0.0.1]:5177, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=MockConnection{localEndpoint=[127.0.0.1]:5237, remoteEndpoint=[127.0.0.1]:5177}}
	at com.hazelcast.internal.nearcache.NearCacheTestUtils.getFuture(NearCacheTestUtils.java:85)
	at com.hazelcast.internal.nearcache.AbstractNearCacheBasicTest.populateNearCache(AbstractNearCacheBasicTest.java:1645)
	at com.hazelcast.internal.nearcache.AbstractNearCacheBasicTest.populateNearCache(AbstractNearCacheBasicTest.java:1618)
	at com.hazelcast.internal.nearcache.AbstractNearCacheBasicTest.whenGetIsUsed_thenNearCacheShouldBePopulated(AbstractNearCacheBasicTest.java:224)
	at com.hazelcast.internal.nearcache.AbstractNearCacheBasicTest.whenGetAsyncIsUsed_thenNearCacheShouldBePopulated(AbstractNearCacheBasicTest.java:203)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:95)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:56)
	at java.lang.reflect.Method.invoke(Method.java:620)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask.run(FutureTask.java:274)
	at java.lang.Thread.run(Thread.java:809)
```

Stacktrace for `whenRemoveAsyncIsUsed_thenNearCacheShouldBeInvalidated_onNearCacheAdapter`:
```
java.lang.AssertionError: Could not remove entry via removeAsync() com.hazelcast.partition.NoDataMemberInClusterException: Target of invocation cannot be found! Partition owner is null but partitions can't be assigned since all nodes in the cluster are lite members.
	at com.hazelcast.internal.nearcache.NearCacheTestUtils.getFuture(NearCacheTestUtils.java:85)
	at com.hazelcast.internal.nearcache.AbstractNearCacheBasicTest.whenEntryIsRemoved_thenNearCacheShouldBeInvalidated(AbstractNearCacheBasicTest.java:1207)
	at com.hazelcast.internal.nearcache.AbstractNearCacheBasicTest.whenRemoveAsyncIsUsed_thenNearCacheShouldBeInvalidated_onNearCacheAdapter(AbstractNearCacheBasicTest.java:1057)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:95)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:56)
	at java.lang.reflect.Method.invoke(Method.java:620)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask.run(FutureTask.java:274)
	at java.lang.Thread.run(Thread.java:809)
```

Measured hiccups for those tests:
```
Hiccups measured while running test 'whenGetAsyncIsUsedOnEmptyDataStructure_thenAlwaysReturnNullFromNearCache(com.hazelcast.client.map.impl.nearcache.LiteMemberClientMapNearCacheBasicTest):'
12:07:45, accumulated pauses: 51 ms, max pause: 16 ms, pauses over 1000 ms: 0
12:07:50, accumulated pauses: 671 ms, max pause: 639 ms, pauses over 1000 ms: 0
12:07:55, accumulated pauses: 2448 ms, max pause: 1343 ms, pauses over 1000 ms: 2
12:08:00, accumulated pauses: 1058 ms, max pause: 982 ms, pauses over 1000 ms: 0
12:08:05, accumulated pauses: 69 ms, max pause: 38 ms, pauses over 1000 ms: 0
12:08:10, accumulated pauses: 648 ms, max pause: 623 ms, pauses over 1000 ms: 0
12:08:15, accumulated pauses: 30 ms, max pause: 0 ms, pauses over 1000 ms: 0
12:08:20, accumulated pauses: 29 ms, max pause: 0 ms, pauses over 1000 ms: 0
12:08:25, accumulated pauses: 36 ms, max pause: 3 ms, pauses over 1000 ms: 0
12:08:30, accumulated pauses: 30 ms, max pause: 0 ms, pauses over 1000 ms: 0
12:08:35, accumulated pauses: 30 ms, max pause: 0 ms, pauses over 1000 ms: 0
12:08:40, accumulated pauses: 31 ms, max pause: 0 ms, pauses over 1000 ms: 0
12:08:45, accumulated pauses: 30 ms, max pause: 0 ms, pauses over 1000 ms: 0
12:08:50, accumulated pauses: 87 ms, max pause: 53 ms, pauses over 1000 ms: 0
12:08:55, accumulated pauses: 30 ms, max pause: 0 ms, pauses over 1000 ms: 0
12:09:00, accumulated pauses: 29 ms, max pause: 0 ms, pauses over 1000 ms: 0
12:09:05, accumulated pauses: 30 ms, max pause: 0 ms, pauses over 1000 ms: 0
12:09:10, accumulated pauses: 30 ms, max pause: 0 ms, pauses over 1000 ms: 0
12:09:15, accumulated pauses: 29 ms, max pause: 0 ms, pauses over 1000 ms: 0
12:09:20, accumulated pauses: 5207 ms, max pause: 5198 ms, pauses over 1000 ms: 1
12:09:25, accumulated pauses: 38 ms, max pause: 19 ms, pauses over 1000 ms: 0
12:09:30, accumulated pauses: 30 ms, max pause: 0 ms, pauses over 1000 ms: 0
12:09:35, accumulated pauses: 6067 ms, max pause: 6063 ms, pauses over 1000 ms: 1
12:09:40, accumulated pauses: 18 ms, max pause: 0 ms, pauses over 1000 ms: 0
12:09:45, accumulated pauses: 29 ms, max pause: 0 ms, pauses over 1000 ms: 0
12:09:50, accumulated pauses: 30 ms, max pause: 0 ms, pauses over 1000 ms: 0
12:09:55, accumulated pauses: 30 ms, max pause: 0 ms, pauses over 1000 ms: 0
12:10:00, accumulated pauses: 31 ms, max pause: 0 ms, pauses over 1000 ms: 0
12:10:05, accumulated pauses: 30 ms, max pause: 0 ms, pauses over 1000 ms: 0
12:10:10, accumulated pauses: 30 ms, max pause: 0 ms, pauses over 1000 ms: 0
12:10:15, accumulated pauses: 29 ms, max pause: 0 ms, pauses over 1000 ms: 0
12:10:20, accumulated pauses: 29 ms, max pause: 0 ms, pauses over 1000 ms: 0
12:10:25, accumulated pauses: 29 ms, max pause: 0 ms, pauses over 1000 ms: 0
12:10:30, accumulated pauses: 28 ms, max pause: 0 ms, pauses over 1000 ms: 0
12:10:35, accumulated pauses: 27 ms, max pause: 0 ms, pauses over 1000 ms: 0
12:10:40, accumulated pauses: 369 ms, max pause: 177 ms, pauses over 1000 ms: 0
12:10:45, accumulated pauses: 9 ms, max pause: 0 ms, pauses over 1000 ms: 0
```

**Comment by mmedenjak** [comment]
Possibly related:
https://github.com/hazelcast/hazelcast-enterprise/issues/2297
https://github.com/hazelcast/hazelcast-enterprise/issues/2481

Fix PR: https://github.com/hazelcast/hazelcast/pull/13943

**Comment by taburet** [comment]
Potentially fixed by https://github.com/hazelcast/hazelcast/pull/13943, closing.
