### ISSUE TITLE
No DataSerializerFactory registered for namespace: 0 from version 3.9.1 with Scala code.

### ISSUE THREAD

**Issue by wpoosanguansit** [hazelcast/hazelcast#13952]
Hi,

I am trying to use:

  "com.hazelcast" % "hazelcast" % "3.9.1" withSources(),
  "com.hazelcast" %% "hazelcast-scala" % "3.9.1" withSources(),

with scala 2.12.6 and Java 8.  When I setup the cluster, I do see the error below:

```
SEVERE: [44.128.0.55]:5701 [com-streaming-hz] [3.10.6] Failed to process: Packet{partitionId=-1, conn=Connection[id=2, /10.92.240.174:5701->/10.92.240.211:33044, endpoint=null, alive=true, type=MEMBER], rawFlags=100000, isUrgent=false, packetType=BIND, typeSpecificFlags=<NONE>}
com.hazelcast.nio.serialization.HazelcastSerializationException: No DataSerializerFactory registered for namespace: 0
    at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.readInternal(DataSerializableSerializer.java:139)
    at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:106)
    at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:51)
    at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48)
    at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:187)
    at com.hazelcast.nio.tcp.TcpIpConnectionManager.handle(TcpIpConnectionManager.java:213)
    at com.hazelcast.spi.impl.NodeEngineImpl$ConnectionManagerPacketHandler.handle(NodeEngineImpl.java:510)
    at com.hazelcast.spi.impl.PacketDispatcher.handle(PacketDispatcher.java:73)
    at com.hazelcast.nio.tcp.PacketDecoder.onPacketComplete(PacketDecoder.java:68)
    at com.hazelcast.nio.tcp.PacketDecoder.onRead(PacketDecoder.java:55)
    at com.hazelcast.internal.networking.nio.NioInboundPipeline.process(NioInboundPipeline.java:140)
    at com.hazelcast.internal.networking.nio.NioThread.handleSelectionKey(NioThread.java:383)
    at com.hazelcast.internal.networking.nio.NioThread.handleSelectionKeys(NioThread.java:368)
    at com.hazelcast.internal.networking.nio.NioThread.selectLoop(NioThread.java:275)
    at com.hazelcast.internal.networking.nio.NioThread.run(NioThread.java:230)

Oct 12, 2018 10:39:15 PM com.hazelcast.nio.tcp.TcpIpAcceptor
INFO: [44.128.0.55]:5701 [com-streaming-hz] [3.10.6] Accepting socket connection from /44.128.0.66:35723
Oct 12, 2018 10:39:15 PM com.hazelcast.nio.tcp.TcpIpConnectionManager
INFO: [44.128.0.55]:5701 [com-streaming-hz] [3.10.6] Established socket connection between /10.92.240.174:5701 and /44.128.0.66:35723
Oct 12, 2018 10:39:15 PM com.hazelcast.client.impl.protocol.task.AuthenticationMessageTask
INFO: [44.128.0.55]:5701 [com-streaming-hz] [3.10.6] Received auth from Connection[id=3, /10.92.240.174:5701->/44.128.0.66:35723, endpoint=null, alive=true, type=JAVA_CLIENT], successfully authenticated, principal: ClientPrincipal{uuid='cc96f6a2-b8f6-48cd-a8d9-04e873ac0749', ownerUuid='cd1b5dc1-3e7c-492b-b3ef-fcaf45a4ba52'}, owner connection: true, client version: 3.9.1
Oct 12, 2018 10:39:24 PM com.hazelcast.nio.tcp.TcpIpConnection
INFO: [44.128.0.55]:5701 [com-streaming-hz] [3.10.6] Connection[id=1, /11.235.209.10:49270->hazelcastcom-streaming-hazelcast.marathon.l4lb.thisdcos.directory/11.235.209.10:5701, endpoint=[hazelcastcom-streaming-hazelcast.marathon.l4lb.thisdcos.directory]:5701, alive=false, type=MEMBER] closed. Reason: Connection closed by the other side
Oct 12, 2018 10:41:20 PM com.hazelcast.nio.tcp.TcpIpConnectionManager
INFO: [44.128.0.55]:5701 [com-streaming-hz] [3.10.6] Established socket connection between /11.235.209.10:38163 and hazelcastcom-streaming-hazelcast.marathon.l4lb.thisdcos.directory/11.235.209.10:5701
```

Any help is appreciated

**Comment by mdogan** [comment]
In the logs Hazelcast version is `[3.10.6]`. Are you using 3.9.1 and 3.10.6 versions in the same cluster?

**Comment by wpoosanguansit** [comment]
i did moved everything to 3.9.1.  I probably took the log from the other run.  Now I am having everything at 3.9.1 and I am still facing the same issue.  Any suggestion?

**Comment by wpoosanguansit** [comment]
And this is the error that I got from the latest run:
```
SEVERE: [193.11.254.1]:5701 [com-hz] [3.9.1] Failed to process:Packet{partitionId=-1, conn=Connection[id=2, /10.92.240.84:5701->/10.251.218.104:8550, endpoint=null, alive=true, type=MEMBER], rawFlags=100000, isUrgent=false, packetType=BIND, typeSpecificFlags=<NONE>}
com.hazelcast.nio.serialization.HazelcastSerializationException: No DataSerializerFactory registered for namespace: 0
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.readInternal(DataSerializableSerializer.java:137)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:105)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:50)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:185)
	at com.hazelcast.nio.tcp.TcpIpConnectionManager.handle(TcpIpConnectionManager.java:213)
	at com.hazelcast.spi.impl.NodeEngineImpl$ConnectionManagerPacketHandler.handle(NodeEngineImpl.java:199)
	at com.hazelcast.spi.impl.PacketDispatcher.handle(PacketDispatcher.java:73)
	at com.hazelcast.nio.tcp.MemberChannelInboundHandler.handlePacket(MemberChannelInboundHandler.java:71)
	at com.hazelcast.nio.tcp.MemberChannelInboundHandler.onRead(MemberChannelInboundHandler.java:54)
	at com.hazelcast.internal.networking.nio.NioChannelReader.handle(NioChannelReader.java:138)
	at com.hazelcast.internal.networking.nio.NioThread.handleSelectionKey(NioThread.java:401)
	at com.hazelcast.internal.networking.nio.NioThread.handleSelectionKeys(NioThread.java:386)
	at com.hazelcast.internal.networking.nio.NioThread.selectLoop(NioThread.java:293)
	at com.hazelcast.internal.networking.nio.NioThread.run(NioThread.java:248)

Oct 15, 2018 7:58:01 PM com.hazelcast.system
INFO: [193.11.254.1]:5701 [com-hz] [3.9.1] Cluster version set to 3.9
Oct 15, 2018 7:58:01 PM com.hazelcast.internal.cluster.ClusterService
INFO: [193.11.254.1]:5701 [com-hz] [3.9.1] 

Members {size:1, ver:1} [
	Member [193.11.254.1]:5701 - 33914c4a-65e6-4dbc-b8ae-fa42a8735088 this
]

Oct 15, 2018 7:58:01 PM com.hazelcast.internal.management.ManagementCenterService
INFO: [193.11.254.1]:5701 [com-hz] [3.9.1] Hazelcast will connect to Hazelcast Management Center on address:
```

**Comment by pveentjer** [comment]
Are all the clients and members configured the same? So do they have the same serialization configuration?

If there are differences, one machine could create data that can't be read by another and this can lead to your exception.

**Comment by wpoosanguansit** [comment]
Yes.  They are both 3.10.6 or 3.9.1.  I tested them both.

**Comment by sancar** [comment]
@meryam94benfredj See https://docs.hazelcast.com/imdg/4.2/serialization/implementing-dataserializable.html#identifieddataserializable

**Comment by meryam94benfredj** [comment]
> @meryam94benfredj See https://docs.hazelcast.com/imdg/4.2/serialization/implementing-dataserializable.html#identifieddataserializable

i saw it but there is things that not clear for me. in fact i use c++ client i configured the client but i didn't know how to configure the cluster

**Comment by meryam94benfredj** [comment]
@sancar if you have an exemple or somthing except the hazelcast documentation send it to even though in java. thank you in advance

**Comment by sancar** [comment]
@wpoosanguansit 
It looks like we did not pay attention to this issue for a while. Since no milestone is set, it skipped our attention. We should have set a milestone when the issue first arrived. 
Please feel free to reopen if you have any questions. 

@meryam94benfredj I hope we covered your questions as well. I am closing the issue for now.
