### ISSUE TITLE
ClientScheduledExecutorServiceBasicTest test failures

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#13971]
_master_ (commit 43dab15a9d0b3f4cbd8b3eee423991c89af68c37)

Failed on OracleJDK6 build: https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-OracleJDK6/505/testReport/

Following tests fail:
* `com.hazelcast.client.scheduledexecutor.ClientScheduledExecutorServiceBasicTest.scheduleAndGet_withCallable_durableAfterTaskCompletion`
* `com.hazelcast.client.scheduledexecutor.ClientScheduledExecutorServiceBasicTest.getErroneous_durable`
* `com.hazelcast.client.scheduledexecutor.ClientScheduledExecutorServiceBasicTest.schedule_withStatefulRunnable`
* `com.hazelcast.client.scheduledexecutor.ClientScheduledExecutorServiceBasicTest.scheduleOnMemberWithRepetition`
* `com.hazelcast.client.scheduledexecutor.ClientScheduledExecutorServiceBasicTest.schedule_withMapChanges_durable`
* `com.hazelcast.client.scheduledexecutor.ClientScheduledExecutorServiceBasicTest.cancelledAndDone_durable`

Stacktrace is like (`com.hazelcast.client.scheduledexecutor.ClientScheduledExecutorServiceBasicTest.scheduleAndGet_withCallable_durableAfterTaskCompletion`):
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:156)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:811)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:842)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1178)
	at java.util.concurrent.locks.ReentrantLock$NonfairSync.lock(ReentrantLock.java:186)
	at java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:262)
	at java.util.concurrent.ThreadPoolExecutor.awaitTermination(ThreadPoolExecutor.java:1254)
	at com.hazelcast.spi.impl.executionservice.impl.ExecutionServiceImpl.shutdown(ExecutionServiceImpl.java:327)
	at com.hazelcast.spi.impl.NodeEngineImpl.shutdown(NodeEngineImpl.java:495)
	at com.hazelcast.instance.Node.shutdownServices(Node.java:534)
	at com.hazelcast.instance.Node.shutdown(Node.java:469)
	at com.hazelcast.instance.LifecycleServiceImpl.shutdown(LifecycleServiceImpl.java:98)
	at com.hazelcast.instance.LifecycleServiceImpl.shutdown(LifecycleServiceImpl.java:81)
	at com.hazelcast.scheduledexecutor.ScheduledExecutorServiceBasicTest.scheduleAndGet_withCallable_durableAfterTaskCompletion(ScheduledExecutorServiceBasicTest.java:311)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.lang.Thread.run(Thread.java:662)
```

Standard Output is like (`com.hazelcast.client.scheduledexecutor.ClientScheduledExecutorServiceBasicTest.scheduleAndGet_withCallable_durableAfterTaskCompletion`):
```
Hiccups measured while running test 'scheduleAndGet_withCallable_durableAfterTaskCompletion(com.hazelcast.client.scheduledexecutor.ClientScheduledExecutorServiceBasicTest):'
09:11:30, accumulated pauses: 5578 ms, max pause: 2880 ms, pauses over 1000 ms: 2
09:11:35, accumulated pauses: 3304 ms, max pause: 3303 ms, pauses over 1000 ms: 1
09:11:40, accumulated pauses: 5453 ms, max pause: 2730 ms, pauses over 1000 ms: 2
09:11:45, accumulated pauses: 6099 ms, max pause: 3329 ms, pauses over 1000 ms: 2
09:11:50, accumulated pauses: 2771 ms, max pause: 2771 ms, pauses over 1000 ms: 1
09:11:55, accumulated pauses: 8399 ms, max pause: 5585 ms, pauses over 1000 ms: 2
09:12:00, accumulated pauses: 2921 ms, max pause: 2921 ms, pauses over 1000 ms: 1
09:12:05, accumulated pauses: 5656 ms, max pause: 5656 ms, pauses over 1000 ms: 1
09:12:10, accumulated pauses: 2890 ms, max pause: 2890 ms, pauses over 1000 ms: 1
09:12:15, accumulated pauses: 2718 ms, max pause: 2718 ms, pauses over 1000 ms: 1
09:12:20, accumulated pauses: 9137 ms, max pause: 9137 ms, pauses over 1000 ms: 1
09:12:30, accumulated pauses: 2839 ms, max pause: 2839 ms, pauses over 1000 ms: 1
09:12:35, accumulated pauses: 14221 ms, max pause: 5675 ms, pauses over 1000 ms: 3
09:12:40, accumulated pauses: 6010 ms, max pause: 6010 ms, pauses over 1000 ms: 1
09:12:55, accumulated pauses: 5662 ms, max pause: 5662 ms, pauses over 1000 ms: 1
09:13:00, accumulated pauses: 13699 ms, max pause: 8178 ms, pauses over 1000 ms: 2
09:13:05, accumulated pauses: 0 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:13:10, accumulated pauses: 2913 ms, max pause: 2913 ms, pauses over 1000 ms: 1
09:13:30, accumulated pauses: 24263 ms, max pause: 17858 ms, pauses over 1000 ms: 2
09:13:35, accumulated pauses: 7906 ms, max pause: 7906 ms, pauses over 1000 ms: 1
09:13:50, accumulated pauses: 5793 ms, max pause: 5793 ms, pauses over 1000 ms: 1
09:14:10, accumulated pauses: 28418 ms, max pause: 28418 ms, pauses over 1000 ms: 1
09:14:25, accumulated pauses: 9179 ms, max pause: 9179 ms, pauses over 1000 ms: 1
09:14:40, accumulated pauses: 12097 ms, max pause: 12097 ms, pauses over 1000 ms: 1
09:14:50, accumulated pauses: 11476 ms, max pause: 11476 ms, pauses over 1000 ms: 1
09:15:05, accumulated pauses: 20390 ms, max pause: 20390 ms, pauses over 1000 ms: 1
09:15:10, accumulated pauses: 2796 ms, max pause: 2795 ms, pauses over 1000 ms: 1
09:15:15, accumulated pauses: 5673 ms, max pause: 2864 ms, pauses over 1000 ms: 2
09:15:20, accumulated pauses: 5751 ms, max pause: 5751 ms, pauses over 1000 ms: 1
09:15:25, accumulated pauses: 5279 ms, max pause: 2710 ms, pauses over 1000 ms: 2
09:15:30, accumulated pauses: 0 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:15:35, accumulated pauses: 8371 ms, max pause: 5354 ms, pauses over 1000 ms: 2
09:15:40, accumulated pauses: 2847 ms, max pause: 2847 ms, pauses over 1000 ms: 1
09:15:45, accumulated pauses: 10854 ms, max pause: 5340 ms, pauses over 1000 ms: 3
09:15:50, accumulated pauses: 0 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:15:55, accumulated pauses: 5769 ms, max pause: 2920 ms, pauses over 1000 ms: 2
09:16:00, accumulated pauses: 2850 ms, max pause: 2850 ms, pauses over 1000 ms: 1
09:16:05, accumulated pauses: 13340 ms, max pause: 7670 ms, pauses over 1000 ms: 3
09:16:15, accumulated pauses: 5879 ms, max pause: 3139 ms, pauses over 1000 ms: 2
09:16:20, accumulated pauses: 2661 ms, max pause: 2660 ms, pauses over 1000 ms: 1
09:16:25, accumulated pauses: 7699 ms, max pause: 4868 ms, pauses over 1000 ms: 2
09:16:30, accumulated pauses: 1267 ms, max pause: 1267 ms, pauses over 1000 ms: 1
09:16:35, accumulated pauses: 3723 ms, max pause: 3698 ms, pauses over 1000 ms: 1
09:16:40, accumulated pauses: 2866 ms, max pause: 2847 ms, pauses over 1000 ms: 1
09:16:45, accumulated pauses: 72 ms, max pause: 22 ms, pauses over 1000 ms: 0
09:16:50, accumulated pauses: 55 ms, max pause: 20 ms, pauses over 1000 ms: 0
```

**Comment by tezc** [comment]
_master_ (commit 66f00c806cf96e33b993f5e6447fdc8da7e4cf96)

Failed on IbmJDK6 build this time with more failures. 
https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-OracleJDK6/506/

More test failures :
```
com.hazelcast.client.scheduledexecutor.ClientScheduledExecutorServiceBasicTest.schedule_andCancel_onMember
com.hazelcast.client.scheduledexecutor.ClientScheduledExecutorServiceBasicTest.scheduleWithRepetition
com.hazelcast.client.scheduledexecutor.ClientScheduledExecutorServiceBasicTest.scheduleOnKeyOwner_withCallable
com.hazelcast.client.scheduledexecutor.ClientScheduledExecutorServiceBasicTest.schedule_partitionAware
com.hazelcast.client.scheduledexecutor.ClientScheduledExecutorServiceBasicTest.scheduleOnAllMembers_getAllScheduled
com.hazelcast.client.scheduledexecutor.ClientScheduledExecutorServiceBasicTest.scheduleOnMember_getDelay
com.hazelcast.client.scheduledexecutor.ClientScheduledExecutorServiceBasicTest.scheduleOnKeyOwner_withNotPeriodicRunnableDurable
com.hazelcast.client.scheduledexecutor.ClientScheduledExecutorServiceBasicTest.scheduleAndGet_withCallable_durableAfterTaskCompletion
com.hazelcast.client.scheduledexecutor.ClientScheduledExecutorServiceBasicTest.scheduleOnMemberWithRepetition
com.hazelcast.client.scheduledexecutor.ClientScheduledExecutorServiceBasicTest.getErroneous_durable
com.hazelcast.client.scheduledexecutor.ClientScheduledExecutorServiceBasicTest.schedule_withStatefulRunnable
com.hazelcast.client.scheduledexecutor.ClientScheduledExecutorServiceBasicTest.schedule_withMapChanges_durable
com.hazelcast.client.scheduledexecutor.ClientScheduledExecutorServiceBasicTest.cancelledAndDone_durable
```
Stacktraces : 
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:283)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:160)
	at com.hazelcast.client.spi.ProxyManager.initialize(ProxyManager.java:433)
	at com.hazelcast.client.spi.ProxyManager.initializeWithRetry(ProxyManager.java:396)
	at com.hazelcast.client.spi.ProxyManager.getOrCreateProxy(ProxyManager.java:317)
	at com.hazelcast.client.impl.clientside.HazelcastClientInstanceImpl.getDistributedObject(HazelcastClientInstanceImpl.java:882)
	at com.hazelcast.client.impl.clientside.HazelcastClientInstanceImpl.getScheduledExecutorService(HazelcastClientInstanceImpl.java:812)
	at com.hazelcast.client.impl.clientside.HazelcastClientProxy.getScheduledExecutorService(HazelcastClientProxy.java:232)
	at com.hazelcast.client.scheduledexecutor.ClientScheduledExecutorServiceBasicTest.getScheduledExecutor(ClientScheduledExecutorServiceBasicTest.java:64)
	at com.hazelcast.scheduledexecutor.ScheduledExecutorServiceBasicTest.schedule_andCancel_onMember(ScheduledExecutorServiceBasicTest.java:510)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.lang.Thread.run(Thread.java:662)
```
```
com.hazelcast.spi.exception.TargetNotMemberException: Target '[127.0.0.1]:5701' is not a member.
	at com.hazelcast.client.spi.impl.SmartClientInvocationService.invokeOnTarget(SmartClientInvocationService.java:66)
	at com.hazelcast.client.spi.impl.ClientInvocation.invokeOnSelection(ClientInvocation.java:165)
	at com.hazelcast.client.spi.impl.ClientInvocation.invoke(ClientInvocation.java:146)
	at com.hazelcast.client.proxy.ClientScheduledExecutorProxy.scheduleOnMember(ClientScheduledExecutorProxy.java:382)
	at com.hazelcast.client.proxy.ClientScheduledExecutorProxy.scheduleOnMembers(ClientScheduledExecutorProxy.java:231)
	at com.hazelcast.client.proxy.ClientScheduledExecutorProxy.scheduleOnMember(ClientScheduledExecutorProxy.java:149)
	at com.hazelcast.scheduledexecutor.ScheduledExecutorServiceBasicTest.scheduleOnMember_getDelay(ScheduledExecutorServiceBasicTest.java:475)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.lang.Thread.run(Thread.java:662)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:96)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:33)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:154)
	at com.hazelcast.client.proxy.ClientScheduledExecutorProxy.scheduleOnMember(ClientScheduledExecutorProxy.java:382)
	at com.hazelcast.client.proxy.ClientScheduledExecutorProxy.scheduleOnMembers(ClientScheduledExecutorProxy.java:231)
	at com.hazelcast.client.proxy.ClientScheduledExecutorProxy.scheduleOnMember(ClientScheduledExecutorProxy.java:149)
	at com.hazelcast.scheduledexecutor.ScheduledExecutorServiceBasicTest.scheduleOnMember_getDelay(ScheduledExecutorServiceBasicTest.java:475)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.lang.Thread.run(Thread.java:662)
```
```
java.lang.AssertionError: expected:<0> but was:<3>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.scheduledexecutor.ScheduledExecutorServiceBasicTest.scheduleWithRepetition(ScheduledExecutorServiceBasicTest.java:763)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.lang.Thread.run(Thread.java:662)
```

**Comment by tkountis** [comment]
After spending a day on this, and re-writing some tests, I think its not worth making any change whatsoever for this issue. The logged hiccups are on the extreme side, eg. *minutes*. No change can account for such hiccups. 
I am voting to close this as is, unless we have solid objections @mmedenjak @Holmistr

**Comment by Holmistr** [comment]
But how do we prevent this issue from happening in the future?

**Comment by tkountis** [comment]
i  honestly am out of solid ideas. 
if we have minutes of hiccups on the build environment this is a bigger problem. Some of the tests fail even during waiting on the shutdown process (not inside test code). 
On the other hand this is quite extreme, I personally don't remember any other similar cases of such delays, if that happens again, we can put our heads together to discuss it.
