### ISSUE TITLE
Cluster not merging. Still have pending migration tasks, cannot lock cluster state

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#13988]
https://hazelcast-l337.ci.cloudbees.com/view/icmp/job/block-all/63/console

`clusterAAMerged HzMember1HZAA timeout=99 running bench`

the cluster failed to merge on the 2nd iteration of the test.
the cluster is loaded with 400 maps each containing 100 entries.

http://54.82.84.143/~jenkins/workspace/block-all/3.12-SNAPSHOT/2018_10_23-02_57_02/block-all

/disk1/jenkins/workspace/block-all/3.12-SNAPSHOT/2018_10_23-02_57_02/block-all

/output/HZ/HzMember1HZAA/out.txt
```
2018-10-23 00:18:12,659 DEBUG [hz._hzInstance_1_HZ.cached.thread-2]: [10.0.0.176]:5701 [HZ] [3.12-SNAPSHOT] [10.0.0.176]:5701 will ping [10.0.0.170]:5701
2018-10-23 00:18:12,660 DEBUG [hz._hzInstance_1_HZ.cached.thread-2]: [10.0.0.176]:5701 [HZ] [3.12-SNAPSHOT] [10.0.0.176]:5701 pinged [10.0.0.170]:5701 successfully
2018-10-23 00:18:12,672 DEBUG [hz._hzInstance_1_HZ.InvocationMonitorThread]: [10.0.0.176]:5701 [HZ] [3.12-SNAPSHOT] Invocations:5 timeouts:0 backup-timeouts:0
2018-10-23 00:18:13,315 DEBUG [hz._hzInstance_1_HZ.cached.thread-9]: [10.0.0.176]:5701 [HZ] [3.12-SNAPSHOT] Returning null timeout<0, -10
2018-10-23 00:18:13,315 DEBUG [hz._hzInstance_1_HZ.cached.thread-9]: [10.0.0.176]:5701 [HZ] [3.12-SNAPSHOT] Sending SplitBrainJoinMessage to [10.0.0.170]:5703
2018-10-23 00:18:13,659 DEBUG [hz._hzInstance_1_HZ.cached.thread-2]: [10.0.0.176]:5701 [HZ] [3.12-SNAPSHOT] [10.0.0.176]:5701 will ping [10.0.0.170]:5701
2018-10-23 00:18:13,660 DEBUG [hz._hzInstance_1_HZ.cached.thread-2]: [10.0.0.176]:5701 [HZ] [3.12-SNAPSHOT] [10.0.0.176]:5701 pinged [10.0.0.170]:5701 successfully
2018-10-23 00:18:13,672 DEBUG [hz._hzInstance_1_HZ.InvocationMonitorThread]: [10.0.0.176]:5701 [HZ] [3.12-SNAPSHOT] Invocations:5 timeouts:0 backup-timeouts:0
2018-10-23 00:18:14,659 DEBUG [hz._hzInstance_1_HZ.cached.thread-2]: [10.0.0.176]:5701 [HZ] [3.12-SNAPSHOT] [10.0.0.176]:5701 will ping [10.0.0.170]:5701
2018-10-23 00:18:14,660 DEBUG [hz._hzInstance_1_HZ.cached.thread-2]: [10.0.0.176]:5701 [HZ] [3.12-SNAPSHOT] [10.0.0.176]:5701 pinged [10.0.0.170]:5701 successfully
2018-10-23 00:18:14,672 DEBUG [hz._hzInstance_1_HZ.InvocationMonitorThread]: [10.0.0.176]:5701 [HZ] [3.12-SNAPSHOT] Invocations:5 timeouts:0 backup-timeouts:0
2018-10-23 00:18:15,659 DEBUG [hz._hzInstance_1_HZ.cached.thread-2]: [10.0.0.176]:5701 [HZ] [3.12-SNAPSHOT] [10.0.0.176]:5701 will ping [10.0.0.170]:5701
2018-10-23 00:18:15,660 DEBUG [hz._hzInstance_1_HZ.cached.thread-2]: [10.0.0.176]:5701 [HZ] [3.12-SNAPSHOT] [10.0.0.176]:5701 pinged [10.0.0.170]:5701 successfully
2018-10-23 00:18:15,672 DEBUG [hz._hzInstance_1_HZ.InvocationMonitorThread]: [10.0.0.176]:5701 [HZ] [3.12-SNAPSHOT] Invocations:5 timeouts:0 backup-timeouts:0
2018-10-23 00:18:16,659 DEBUG [hz._hzInstance_1_HZ.cached.thread-2]: [10.0.0.176]:5701 [HZ] [3.12-SNAPSHOT] [10.0.0.176]:5701 will ping [10.0.0.170]:5701
2018-10-23 00:18:16,660 DEBUG [hz._hzInstance_1_HZ.cached.thread-2]: [10.0.0.176]:5701 [HZ] [3.12-SNAPSHOT] [10.0.0.176]:5701 pinged [10.0.0.170]:5701 successfully
2018-10-23 00:18:16,672 DEBUG [hz._hzInstance_1_HZ.InvocationMonitorThread]: [10.0.0.176]:5701 [HZ] [3.12-SNAPSHOT] Invocations:5 timeouts:0 backup-timeouts:0
2018-10-23 00:18:17,612 DEBUG [hz._hzInstance_1_HZ.priority-generic-operation.thread-0]: [10.0.0.176]:5701 [HZ] [3.12-SNAPSHOT] Received heartbeat from Member [10.0.0.170]:5701 - 96
88471b-0671-4e33-ade0-4557b20be0c3 (now: 2018-10-23 00:18:17.611, timestamp: 2018-10-23 00:18:17.611)
2018-10-23 00:18:17,659 DEBUG [hz._hzInstance_1_HZ.cached.thread-2]: [10.0.0.176]:5701 [HZ] [3.12-SNAPSHOT] [10.0.0.176]:5701 will ping [10.0.0.170]:5701
2018-10-23 00:18:17,660 DEBUG [hz._hzInstance_1_HZ.cached.thread-2]: [10.0.0.176]:5701 [HZ] [3.12-SNAPSHOT] [10.0.0.176]:5701 pinged [10.0.0.170]:5701 successfully
2018-10-23 00:18:17,672 DEBUG [hz._hzInstance_1_HZ.InvocationMonitorThread]: [10.0.0.176]:5701 [HZ] [3.12-SNAPSHOT] Invocations:5 timeouts:0 backup-timeouts:0
2018-10-23 00:18:18,394 DEBUG [hz._hzInstance_1_HZ.cached.thread-9]: [10.0.0.176]:5701 [HZ] [3.12-SNAPSHOT] Returning null timeout<0, -10
2018-10-23 00:18:18,394 DEBUG [hz._hzInstance_1_HZ.cached.thread-9]: [10.0.0.176]:5701 [HZ] [3.12-SNAPSHOT] Sending SplitBrainJoinMessage to [10.0.0.38]:5701
2018-10-23 00:18:18,395 DEBUG [hz._hzInstance_1_HZ.cached.thread-9]: [10.0.0.176]:5701 [HZ] [3.12-SNAPSHOT] Checking if we should merge to: SplitBrainJoinMessage{packetVersion=4, bu
ildNumber=20181022, memberVersion=3.12.0, clusterVersion=3.12, address=[10.0.0.38]:5701, uuid='829dcb5f-56ec-46c7-bb00-8df7afe272d8', liteMember=false, memberCount=3, dataMemberCoun
t=3, memberListVersion=13}
2018-10-23 00:18:18,395 INFO  [hz._hzInstance_1_HZ.cached.thread-9]: [10.0.0.176]:5701 [HZ] [3.12-SNAPSHOT] We should merge to [10.0.0.38]:5701 because their data member count is bi
gger than ours [3 > 2]
2018-10-23 00:18:18,395 WARN  [hz._hzInstance_1_HZ.cached.thread-9]: [10.0.0.176]:5701 [HZ] [3.12-SNAPSHOT] [10.0.0.176]:5701 is merging [tcp/ip] to [10.0.0.38]:5701
2018-10-23 00:18:18,398 INFO  [hz._hzInstance_1_HZ.cached.thread-9]: [10.0.0.176]:5701 [HZ] [3.12-SNAPSHOT] Locking cluster state. Initiator: [10.0.0.176]:5701, lease-time: 60000
2018-10-23 00:18:18,398 ERROR [hz._hzInstance_1_HZ.cached.thread-9]: [10.0.0.176]:5701 [HZ] [3.12-SNAPSHOT] Still have pending migration tasks, cannot lock cluster state! New state:
 ClusterStateChange{type=class com.hazelcast.cluster.ClusterState, newState=FROZEN}, current state: ACTIVE
java.lang.IllegalStateException: Still have pending migration tasks, cannot lock cluster state! New state: ClusterStateChange{type=class com.hazelcast.cluster.ClusterState, newState
=FROZEN}, current state: ACTIVE
	at com.hazelcast.internal.cluster.impl.ClusterStateManager.checkMigrationsAndPartitionStateVersion(ClusterStateManager.java:283)
	at com.hazelcast.internal.cluster.impl.ClusterStateManager.lockClusterState(ClusterStateManager.java:215)
	at com.hazelcast.internal.cluster.impl.operations.LockClusterStateOp.run(LockClusterStateOp.java:83)
	at com.hazelcast.spi.Operation.call(Operation.java:170)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:208)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:197)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:407)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:434)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:586)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:571)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:530)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:220)
	at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.invokeOnTarget(OperationServiceImpl.java:324)
	at com.hazelcast.internal.cluster.impl.ClusterStateManager.lockClusterStateOnAllMembers(ClusterStateManager.java:433)
	at com.hazelcast.internal.cluster.impl.ClusterStateManager.changeClusterState(ClusterStateManager.java:385)
	at com.hazelcast.internal.cluster.impl.ClusterStateManager.changeClusterState(ClusterStateManager.java:362)
	at com.hazelcast.internal.cluster.impl.ClusterServiceImpl.changeClusterState(ClusterServiceImpl.java:862)
	at com.hazelcast.internal.cluster.impl.ClusterServiceImpl.changeClusterState(ClusterServiceImpl.java:857)
	at com.hazelcast.internal.cluster.impl.AbstractJoiner.prepareClusterState(AbstractJoiner.java:335)
	at com.hazelcast.internal.cluster.impl.AbstractJoiner.startClusterMerge(AbstractJoiner.java:280)
	at com.hazelcast.cluster.impl.TcpIpJoiner.searchForOtherClusters(TcpIpJoiner.java:523)
	at com.hazelcast.internal.cluster.impl.SplitBrainHandler.searchForOtherClusters(SplitBrainHandler.java:75)
	at com.hazelcast.internal.cluster.impl.SplitBrainHandler.run(SplitBrainHandler.java:42)
	at com.hazelcast.spi.impl.executionservice.impl.DelegateAndSkipOnConcurrentExecutionDecorator$DelegateDecorator.run(DelegateAndSkipOnConcurrentExecutionDecorator.java:66)
	at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:227)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
2018-10-23 00:18:18,399 DEBUG [hz._hzInstance_1_HZ.cached.thread-9]: [10.0.0.176]:5701 [HZ] [3.12-SNAPSHOT] failure during cluster state change
java.lang.IllegalStateException: Still have pending migration tasks, cannot lock cluster state! New state: ClusterStateChange{type=class com.hazelcast.cluster.ClusterState, newState
=FROZEN}, current state: ACTIVE
	at com.hazelcast.internal.cluster.impl.ClusterStateManager.checkMigrationsAndPartitionStateVersion(ClusterStateManager.java:283)
	at com.hazelcast.internal.cluster.impl.ClusterStateManager.lockClusterState(ClusterStateManager.java:215)
	at com.hazelcast.internal.cluster.impl.operations.LockClusterStateOp.run(LockClusterStateOp.java:83)
	at com.hazelcast.spi.Operation.call(Operation.java:170)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:208)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:197)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:407)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:434)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:586)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:571)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:530)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:220)
	at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.invokeOnTarget(OperationServiceImpl.java:324)
	at com.hazelcast.internal.cluster.impl.ClusterStateManager.lockClusterStateOnAllMembers(ClusterStateManager.java:433)
	at com.hazelcast.internal.cluster.impl.ClusterStateManager.changeClusterState(ClusterStateManager.java:385)
	at com.hazelcast.internal.cluster.impl.ClusterStateManager.changeClusterState(ClusterStateManager.java:362)
	at com.hazelcast.internal.cluster.impl.ClusterServiceImpl.changeClusterState(ClusterServiceImpl.java:862)
	at com.hazelcast.internal.cluster.impl.ClusterServiceImpl.changeClusterState(ClusterServiceImpl.java:857)
	at com.hazelcast.internal.cluster.impl.AbstractJoiner.prepareClusterState(AbstractJoiner.java:335)
	at com.hazelcast.internal.cluster.impl.AbstractJoiner.startClusterMerge(AbstractJoiner.java:280)
	at com.hazelcast.cluster.impl.TcpIpJoiner.searchForOtherClusters(TcpIpJoiner.java:523)
	at com.hazelcast.internal.cluster.impl.SplitBrainHandler.searchForOtherClusters(SplitBrainHandler.java:75)
	at com.hazelcast.internal.cluster.impl.SplitBrainHandler.run(SplitBrainHandler.java:42)
	at com.hazelcast.spi.impl.executionservice.impl.DelegateAndSkipOnConcurrentExecutionDecorator$DelegateDecorator.run(DelegateAndSkipOnConcurrentExecutionDecorator.java:66)
	at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:227)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:127)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:79)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:178)
	at com.hazelcast.util.FutureUtil.executeWithDeadline(FutureUtil.java:379)
	at com.hazelcast.util.FutureUtil.waitWithDeadline(FutureUtil.java:363)
	at com.hazelcast.util.FutureUtil.waitWithDeadline(FutureUtil.java:337)
	at com.hazelcast.internal.cluster.impl.ClusterStateManager.lockClusterStateOnAllMembers(ClusterStateManager.java:438)
	at com.hazelcast.internal.cluster.impl.ClusterStateManager.changeClusterState(ClusterStateManager.java:385)
	at com.hazelcast.internal.cluster.impl.ClusterStateManager.changeClusterState(ClusterStateManager.java:362)
	at com.hazelcast.internal.cluster.impl.ClusterServiceImpl.changeClusterState(ClusterServiceImpl.java:862)
	at com.hazelcast.internal.cluster.impl.ClusterServiceImpl.changeClusterState(ClusterServiceImpl.java:857)
	at com.hazelcast.internal.cluster.impl.AbstractJoiner.prepareClusterState(AbstractJoiner.java:335)
	at com.hazelcast.internal.cluster.impl.AbstractJoiner.startClusterMerge(AbstractJoiner.java:280)
	at com.hazelcast.cluster.impl.TcpIpJoiner.searchForOtherClusters(TcpIpJoiner.java:523)
	at com.hazelcast.internal.cluster.impl.SplitBrainHandler.searchForOtherClusters(SplitBrainHandler.java:75)
	at com.hazelcast.internal.cluster.impl.SplitBrainHandler.run(SplitBrainHandler.java:42)
	at com.hazelcast.spi.impl.executionservice.impl.DelegateAndSkipOnConcurrentExecutionDecorator$DelegateDecorator.run(DelegateAndSkipOnConcurrentExecutionDecorator.java:66)
	at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:227)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
2018-10-23 00:18:18,402 DEBUG [hz._hzInstance_1_HZ.cached.thread-9]: [10.0.0.176]:5701 [HZ] [3.12-SNAPSHOT] failure during cluster state change
java.lang.IllegalStateException: Still have pending migration tasks, cannot lock cluster state! New state: ClusterStateChange{type=class com.hazelcast.cluster.ClusterState, newState
=FROZEN}, current state: ACTIVE
```

**Comment by Danny-Hazelcast** [comment]
test scripts https://github.com/hazelcast/hzCmd-bench/tree/master/lab/hz/icmp/block-all.

**Comment by Danny-Hazelcast** [comment]
from https://hazelcast-l337.ci.cloudbees.com/view/icmp/job/block-all/63/console
or 
/disk1/jenkins/workspace/block-all/3.12-SNAPSHOT/2018_10_23-02_57_02/block-all/out.txt

we see that after the 2nd failed iteration where the cluster is not merged.  
we continue the split heal cycles, and in later iterations the cluster is splitting and merging.

but is looks like

```
2018-10-23 00:18:18,398 ERROR [hz._hzInstance_1_HZ.cached.thread-9]: [10.0.0.176]:5701 [HZ] [3.12-SNAPSHOT] Still have pending migration tasks, cannot lock cluster state! New state:
```

is repeatedly logged

**Comment by Danny-Hazelcast** [comment]
this similar test https://hazelcast-l337.ci.cloudbees.com/view/icmp/job/block-tcp/61/console
looks to be having the same issue.

**Comment by Danny-Hazelcast** [comment]
if i add a wait for cluster safe, after the split, making sure that all migration have finished in the 2 smaller split sub clusters. before joining again, it looks like it will not fail.

however as it a random fail we can not say for sure.
  
https://github.com/hazelcast/hzCmd-bench/blob/master/lab/hz/icmp/block-all/go#L31

**Comment by mmedenjak** [comment]
Rerunning the tests on the new jenkins:
http://jenkins.hazelcast.com/view/icmp/job/block-all/
http://jenkins.hazelcast.com/view/icmp/job/block-tcp/
I see the tests have been passing lately.

**Comment by mmedenjak** [comment]
The `Still have pending migration tasks, cannot lock cluster state!` message should be suppressed  now as of https://github.com/hazelcast/hazelcast/pull/14668.

So the question remains why the cluster was not merging.

**Comment by mmedenjak** [comment]
It takes over 12 minutes to repartition the cluster:
```
2019-02-12 03:18:22,920 INFO  [hz._hzInstance_1_HZ.migration]: [10.0.0.146]:5701 [HZ] [3.12-SNAPSHOT] Re-partitioning cluster data... Migration queue size: 271
...
2019-02-12 03:30:23,581 INFO  [hz._hzInstance_1_HZ.migration]: [10.0.0.146]:5701 [HZ] [3.12-SNAPSHOT] All migration tasks have been completed, queues are empty.
```

During this time, the cluster state cannot change which is why the clusters cannot merge. Next question is, why the migrations are taking so long.

**Comment by mmedenjak** [comment]
It is possible the slow migration issue was alleviated since we merged https://hazelcast.atlassian.net/wiki/spaces/EN/pages/1279656113/Speed-Up+Partition+Migrations+Design:
https://github.com/hazelcast/hazelcast/pull/14351
https://github.com/hazelcast/hazelcast/pull/14526

It would correspond to the last time we saw these builds fail (on 2019_02_12).

**Comment by mmedenjak** [comment]
I don't see any particular reason that the migrations are slow because of data replication but I assume they might be slow because there is interference between the migration mechanism and the cluster state change mechanism. I may be wrong, though.

For instance, in this failed run:
http://54.147.27.51/~jenkins/workspace/block-all/3.12-SNAPSHOT/2019_02_12-02_56_02/block-all/

Migrating partition 254 takes the longest (about 10 seconds):
```
2019-02-12 03:29:45,229 DEBUG [hz._hzInstance_1_HZ.migration]: [10.0.0.146]:5701 [HZ] [3.12-SNAPSHOT] Starting Migration: MigrationInfo{uuid=e0b330a1-20e2-4580-be69-e0869f562f6f, partitionId=254, source=null, sourceCurrentReplicaIndex=-1, sourceNewReplicaIndex=-1, destination=[10.0.0.242]:5701 - 85c84a65-67bc-41bc-83e2-0fa626916c65, destinationCurrentReplicaIndex=-1, destinationNewReplicaIndex=1, master=[10.0.0.146]:5701, processing=false, status=ACTIVE}
...
2019-02-12 03:29:55,695 DEBUG [hz._hzInstance_1_HZ.migration]: [10.0.0.146]:5701 [HZ] [3.12-SNAPSHOT] Finished Migration: MigrationInfo{uuid=e0b330a1-20e2-4580-be69-e0869f562f6f, partitionId=254, source=null, sourceCurrentReplicaIndex=-1, sourceNewReplicaIndex=-1, destination=[10.0.0.242]:5701 - 85c84a65-67bc-41bc-83e2-0fa626916c65, destinationCurrentReplicaIndex=-1, destinationNewReplicaIndex=1, master=[10.0.0.146]:5701, processing=false, status=ACTIVE}
```

In the meantime, there are no errors except for failed cluster state changes on both nodes of the smaller brain:
```
...
2019-02-12 03:29:45,578 INFO  [hz._hzInstance_1_HZ.cached.thread-13]: [10.0.0.146]:5701 [HZ] [3.12-SNAPSHOT] Locking cluster state. Initiator: [10.0.0.146]:5701, lease-time: 60000
2019-02-12 03:29:45,578 ERROR [hz._hzInstance_1_HZ.cached.thread-13]: [10.0.0.146]:5701 [HZ] [3.12-SNAPSHOT] Still have pending migration tasks, cannot lock cluster state! New state: ClusterStateChange{ty
pe=class com.hazelcast.cluster.ClusterState, newState=FROZEN}, current state: ACTIVE
2019-02-12 03:29:45,580 INFO  [hz._hzInstance_1_HZ.cached.thread-13]: [10.0.0.146]:5701 [HZ] [3.12-SNAPSHOT] Rolling back cluster state! Initiator: [10.0.0.146]:5701
2019-02-12 03:29:45,580 WARN  [hz._hzInstance_1_HZ.cached.thread-13]: [10.0.0.146]:5701 [HZ] [3.12-SNAPSHOT] While changing cluster state to FROZEN! java.lang.IllegalStateException: Still have pending migration tasks, cannot lock cluster state! New state: ClusterStateChange{type=class com.hazelcast.cluster.ClusterState, newState=FROZEN}, current state: ACTIVE
2019-02-12 03:29:46,581 INFO  [hz._hzInstance_1_HZ.cached.thread-13]: [10.0.0.146]:5701 [HZ] [3.12-SNAPSHOT] Locking cluster state. Initiator: [10.0.0.146]:5701, lease-time: 60000
2019-02-12 03:29:46,581 ERROR [hz._hzInstance_1_HZ.cached.thread-13]: [10.0.0.146]:5701 [HZ] [3.12-SNAPSHOT] Still have pending migration tasks, cannot lock cluster state! New state: ClusterStateChange{type=class com.hazelcast.cluster.ClusterState, newState=FROZEN}, current state: ACTIVE
java.lang.IllegalStateException: Still have pending migration tasks, cannot lock cluster state! New state: ClusterStateChange{type=class com.hazelcast.cluster.ClusterState, newState=FROZEN}, current state: ACTIVE
2019-02-12 03:29:46,582 INFO  [hz._hzInstance_1_HZ.cached.thread-13]: [10.0.0.146]:5701 [HZ] [3.12-SNAPSHOT] Rolling back cluster state! Initiator: [10.0.0.146]:5701
2019-02-12 03:29:46,582 WARN  [hz._hzInstance_1_HZ.cached.thread-13]: [10.0.0.146]:5701 [HZ] [3.12-SNAPSHOT] While changing cluster state to FROZEN! java.lang.IllegalStateException: Still have pending migration tasks, cannot lock cluster state! New state: ClusterStateChange{type=class com.hazelcast.cluster.ClusterState, newState=FROZEN}, current state: ACTIVE
2019-02-12 03:29:46,682 DEBUG [hz._hzInstance_1_HZ.cached.thread-4]: [10.0.0.146]:5701 [HZ] [3.12-SNAPSHOT] [10.0.0.146]:5701 will ping [10.0.0.242]:5701
...
```

It then needs to be validated that the migrations are, in fact, slow because there is interference between the cluster state change mechanism and migrations. @mdogan does that sound plausible?

In any case, I don't think this issue is critical and I am prone to closing it until it resurfaces, especially because the partition migration mechanism was changed after which we didn't see any failures.

**Comment by mdogan** [comment]
Not sure how cluster state change and migrations interfere with each other apart from competing for generic operation threads. 
But I agree that this might be solved by migration speedup change, because if there's at least a single unresponsive/slow node, it will add a significant latency after each migration. With the new mechanism, only migrations to/from that slow node will be effected.

**Comment by mmedenjak** [comment]
You're right, after some additional inspection I see that the `stateLockRef` being held by the state change mechanism isn't the one used by the migration mechanism. Closing for now as we suspect the issue to be fixed. Please reopen with new failures.
