### ISSUE TITLE
MapStableReadStressTest.testChangingCluster

### ISSUE THREAD

**Issue by tezc** [hazelcast/hazelcast#14027]
_master_ (commit d28bfad6751504641c8d27bea8d081c17b9eea11)

Failed on nightly build : https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-nightly/248/testReport/junit/com.hazelcast.client.stress/MapStableReadStressTest/testChangingCluster/

Stacktrace :
```
java.lang.AssertionError: com.hazelcast.client.stress.MapStableReadStressTest$StressThread1 encountered an error expected null, but was:<java.lang.NullPointerException>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotNull(Assert.java:755)
	at org.junit.Assert.assertNull(Assert.java:737)
	at com.hazelcast.client.stress.StressTestSupport$TestThread.assertNoError(StressTestSupport.java:187)
	at com.hazelcast.client.stress.StressTestSupport.assertNoErrors(StressTestSupport.java:138)
	at com.hazelcast.client.stress.StressTestSupport.joinAll(StressTestSupport.java:159)
	at com.hazelcast.client.stress.MapStableReadStressTest.test(MapStableReadStressTest.java:91)
	at com.hazelcast.client.stress.MapStableReadStressTest.testChangingCluster(MapStableReadStressTest.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

Standard output:
```
19:26:43,131  INFO |testChangingCluster| - [AddressPicker] main - [LOCAL] [dev] [3.12-SNAPSHOT] Picked [127.0.0.1]:5702, using socket ServerSocket[addr=/0.0.0.0,localport=5702], bind any local is true
19:26:43,132  INFO |testChangingCluster| - [system] main - [127.0.0.1]:5702 [dev] [3.12-SNAPSHOT] Hazelcast 3.12-SNAPSHOT (20181023 - d28bfad) starting at [127.0.0.1]:5702
19:26:43,132  INFO |testChangingCluster| - [system] main - [127.0.0.1]:5702 [dev] [3.12-SNAPSHOT] Copyright (c) 2008-2018, Hazelcast, Inc. All Rights Reserved.
19:26:43,132  INFO |testChangingCluster| - [Node] main - [127.0.0.1]:5702 [dev] [3.12-SNAPSHOT] A non-empty group password is configured for the Hazelcast member. Starting with Hazelcast version 3.8.2, members with the same group name, but with different group passwords (that do not use authentication) form a cluster. The group password configuration will be removed completely in a future release.
19:26:43,133  INFO |testClientLifecycle| - [MigrationManager] hz._hzInstance_1_dev.migration - [127.0.0.1]:5701 [dev] [3.7] Partition balance is ok, no need to re-partition cluster data... 
19:26:43,137  INFO |testChangingCluster| - [BackpressureRegulator] main - [127.0.0.1]:5702 [dev] [3.12-SNAPSHOT] Backpressure is disabled
19:26:43,155  WARN |testChangingCluster| - [Node] main - [127.0.0.1]:5702 [dev] [3.12-SNAPSHOT] Hazelcast is bound to 127.0.0.1 and loop-back mode is disabled in the configuration. This could cause multicast auto-discovery issues and render it unable to work. Check you network connectivity, try to enable the loopback mode and/or force -Djava.net.preferIPv4Stack=true on your JVM.
19:26:43,155  INFO |testChangingCluster| - [Node] main - [127.0.0.1]:5702 [dev] [3.12-SNAPSHOT] Creating MulticastJoiner
19:26:43,162  INFO |testChangingCluster| - [OperationExecutorImpl] main - [127.0.0.1]:5702 [dev] [3.12-SNAPSHOT] Starting 72 partition threads and 37 generic threads (1 dedicated for priority tasks)
19:26:43,201  INFO |testChangingCluster| - [Diagnostics] main - [127.0.0.1]:5702 [dev] [3.12-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
19:26:43,201  INFO |testChangingCluster| - [LifecycleService] main - [127.0.0.1]:5702 [dev] [3.12-SNAPSHOT] [127.0.0.1]:5702 is STARTING
19:26:43,210  WARN |testClientLifecycle| - [MulticastService] hz._hzInstance_1_dev.MulticastThread - [127.0.0.1]:5701 [dev] [3.7] Received data format is invalid. (An old version of Hazelcast may be running here.)
com.hazelcast.nio.serialization.HazelcastSerializationException: com.hazelcast.internal.cluster.impl.ClusterDataSerializerHook$ClusterDataSerializerFactoryImpl@5af5d6c is not be able to create an instance for id: 30 on factoryId: 0
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:119) ~[hazelcast-3.7.jar:3.12-SNAPSHOT]
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:52) ~[hazelcast-3.7.jar:3.12-SNAPSHOT]
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:46) ~[hazelcast-3.7.jar:3.12-SNAPSHOT]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.readObject(AbstractSerializationService.java:216) ~[hazelcast-3.7.jar:3.12-SNAPSHOT]
	at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readObject(ByteArrayObjectDataInput.java:600) ~[hazelcast-3.7.jar:3.12-SNAPSHOT]
	at com.hazelcast.internal.cluster.impl.MulticastService.receive(MulticastService.java:207) [hazelcast-3.7.jar:3.12-SNAPSHOT]
	at com.hazelcast.internal.cluster.impl.MulticastService.run(MulticastService.java:165) [hazelcast-3.7.jar:3.12-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
19:26:43,312  WARN |testClientLifecycle| - [MulticastService] hz._hzInstance_1_dev.MulticastThread - [127.0.0.1]:5701 [dev] [3.7] Received data format is invalid. (An old version of Hazelcast may be running here.)
com.hazelcast.nio.serialization.HazelcastSerializationException: com.hazelcast.internal.cluster.impl.ClusterDataSerializerHook$ClusterDataSerializerFactoryImpl@5af5d6c is not be able to create an instance for id: 30 on factoryId: 0
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:119) ~[hazelcast-3.7.jar:3.12-SNAPSHOT]
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:52) ~[hazelcast-3.7.jar:3.12-SNAPSHOT]
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:46) ~[hazelcast-3.7.jar:3.12-SNAPSHOT]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.readObject(AbstractSerializationService.java:216) ~[hazelcast-3.7.jar:3.12-SNAPSHOT]
	at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readObject(ByteArrayObjectDataInput.java:600) ~[hazelcast-3.7.jar:3.12-SNAPSHOT]
	at com.hazelcast.internal.cluster.impl.MulticastService.receive(MulticastService.java:207) [hazelcast-3.7.jar:3.12-SNAPSHOT]
	at com.hazelcast.internal.cluster.impl.MulticastService.run(MulticastService.java:165) [hazelcast-3.7.jar:3.12-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
19:26:43,465  WARN |testClientLifecycle| - [MulticastService] hz._hzInstance_1_dev.MulticastThread - [127.0.0.1]:5701 [dev] [3.7] Received data format is invalid. (An old version of Hazelcast may be running here.)
com.hazelcast.nio.serialization.HazelcastSerializationException: com.hazelcast.internal.cluster.impl.ClusterDataSerializerHook$ClusterDataSerializerFactoryImpl@5af5d6c is not be able to create an instance for id: 30 on factoryId: 0
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:119) ~[hazelcast-3.7.jar:3.12-SNAPSHOT]
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:52) ~[hazelcast-3.7.jar:3.12-SNAPSHOT]
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:46) ~[hazelcast-3.7.jar:3.12-SNAPSHOT]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.readObject(AbstractSerializationService.java:216) ~[hazelcast-3.7.jar:3.12-SNAPSHOT]
	at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readObject(ByteArrayObjectDataInput.java:600) ~[hazelcast-3.7.jar:3.12-SNAPSHOT]
	at com.hazelcast.internal.cluster.impl.MulticastService.receive(MulticastService.java:207) [hazelcast-3.7.jar:3.12-SNAPSHOT]
	at com.hazelcast.internal.cluster.impl.MulticastService.run(MulticastService.java:165) [hazelcast-3.7.jar:3.12-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]

-------
```
```
Hiccups measured while running test 'testChangingCluster(com.hazelcast.client.stress.MapStableReadStressTest):'
19:26:40, accumulated pauses: 228 ms, max pause: 8 ms, pauses over 1000 ms: 0
19:26:45, accumulated pauses: 178 ms, max pause: 3 ms, pauses over 1000 ms: 0
19:26:50, accumulated pauses: 218 ms, max pause: 7 ms, pauses over 1000 ms: 0
19:26:55, accumulated pauses: 224 ms, max pause: 3 ms, pauses over 1000 ms: 0
19:27:00, accumulated pauses: 204 ms, max pause: 15 ms, pauses over 1000 ms: 0
19:27:05, accumulated pauses: 167 ms, max pause: 3 ms, pauses over 1000 ms: 0
19:27:10, accumulated pauses: 217 ms, max pause: 10 ms, pauses over 1000 ms: 0
19:27:15, accumulated pauses: 205 ms, max pause: 1 ms, pauses over 1000 ms: 0
19:27:20, accumulated pauses: 264 ms, max pause: 43 ms, pauses over 1000 ms: 0
19:27:25, accumulated pauses: 132 ms, max pause: 1 ms, pauses over 1000 ms: 0
19:27:30, accumulated pauses: 122 ms, max pause: 3 ms, pauses over 1000 ms: 0
19:27:35, accumulated pauses: 170 ms, max pause: 8 ms, pauses over 1000 ms: 0
19:27:40, accumulated pauses: 195 ms, max pause: 50 ms, pauses over 1000 ms: 0
19:27:45, accumulated pauses: 137 ms, max pause: 2 ms, pauses over 1000 ms: 0
19:27:50, accumulated pauses: 151 ms, max pause: 2 ms, pauses over 1000 ms: 0
19:27:55, accumulated pauses: 170 ms, max pause: 41 ms, pauses over 1000 ms: 0
19:28:00, accumulated pauses: 142 ms, max pause: 36 ms, pauses over 1000 ms: 0
19:28:05, accumulated pauses: 130 ms, max pause: 5 ms, pauses over 1000 ms: 0
19:28:10, accumulated pauses: 159 ms, max pause: 7 ms, pauses over 1000 ms: 0
19:28:15, accumulated pauses: 188 ms, max pause: 35 ms, pauses over 1000 ms: 0
19:28:20, accumulated pauses: 129 ms, max pause: 2 ms, pauses over 1000 ms: 0
19:28:25, accumulated pauses: 399 ms, max pause: 190 ms, pauses over 1000 ms: 0
19:28:30, accumulated pauses: 140 ms, max pause: 2 ms, pauses over 1000 ms: 0
19:28:35, accumulated pauses: 164 ms, max pause: 15 ms, pauses over 1000 ms: 0
19:28:40, accumulated pauses: 181 ms, max pause: 27 ms, pauses over 1000 ms: 0
19:28:45, accumulated pauses: 141 ms, max pause: 3 ms, pauses over 1000 ms: 0
19:28:50, accumulated pauses: 213 ms, max pause: 54 ms, pauses over 1000 ms: 0
19:28:55, accumulated pauses: 160 ms, max pause: 11 ms, pauses over 1000 ms: 0
19:29:00, accumulated pauses: 125 ms, max pause: 2 ms, pauses over 1000 ms: 0
19:29:05, accumulated pauses: 68 ms, max pause: 26 ms, pauses over 1000 ms: 0
19:29:10, accumulated pauses: 36 ms, max pause: 10 ms, pauses over 1000 ms: 0
19:29:15, accumulated pauses: 65 ms, max pause: 10 ms, pauses over 1000 ms: 0
19:29:20, accumulated pauses: 75 ms, max pause: 25 ms, pauses over 1000 ms: 0
19:29:25, accumulated pauses: 45 ms, max pause: 16 ms, pauses over 1000 ms: 0
19:29:30, accumulated pauses: 43 ms, max pause: 11 ms, pauses over 1000 ms: 0
19:29:35, accumulated pauses: 72 ms, max pause: 27 ms, pauses over 1000 ms: 0
19:29:40, accumulated pauses: 47 ms, max pause: 21 ms, pauses over 1000 ms: 0
19:29:45, accumulated pauses: 52 ms, max pause: 12 ms, pauses over 1000 ms: 0
19:29:50, accumulated pauses: 52 ms, max pause: 19 ms, pauses over 1000 ms: 0
19:29:55, accumulated pauses: 46 ms, max pause: 21 ms, pauses over 1000 ms: 0
19:30:00, accumulated pauses: 56 ms, max pause: 19 ms, pauses over 1000 ms: 0
19:30:05, accumulated pauses: 58 ms, max pause: 17 ms, pauses over 1000 ms: 0
19:30:10, accumulated pauses: 591 ms, max pause: 446 ms, pauses over 1000 ms: 0
19:30:15, accumulated pauses: 38 ms, max pause: 8 ms, pauses over 1000 ms: 0
```

**Comment by mmedenjak** [comment]
Looks like `HazelcastClientStarterTest#testClientLifecycle` was interfering with the test.
