### ISSUE TITLE
HazelcastStarterTest.testMember

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#14033]
_master_ (commit 1ea1072518a48d7aa4c607e41c6007ef64dc903b)

Failed on Sonar build: https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-sonar/263/testReport/com.hazelcast.test.starter.test/HazelcastStarterTest/testMember/

It is probably caused by the same issue as https://github.com/hazelcast/hazelcast/issues/13969

Stacktrace:
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.readV3Record(InputRecord.java:593)
	at sun.security.ssl.InputRecord.read(InputRecord.java:532)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:975)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:933)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:136)
	at org.apache.http.impl.io.SessionInputBufferImpl.read(SessionInputBufferImpl.java:195)
	at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:178)
	at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:200)
	at org.apache.http.entity.BasicHttpEntity.writeTo(BasicHttpEntity.java:113)
	at org.apache.http.impl.execchain.ResponseEntityWrapper.writeTo(ResponseEntityWrapper.java:95)
	at com.hazelcast.test.starter.HazelcastVersionLocator.downloadFile(HazelcastVersionLocator.java:143)
	at com.hazelcast.test.starter.HazelcastVersionLocator.downloadMember(HazelcastVersionLocator.java:113)
	at com.hazelcast.test.starter.HazelcastVersionLocator.locateMember(HazelcastVersionLocator.java:78)
	at com.hazelcast.test.starter.HazelcastVersionLocator.locateVersion(HazelcastVersionLocator.java:61)
	at com.hazelcast.test.starter.HazelcastStarter$HazelcastVersionClassloaderFuture.get(HazelcastStarter.java:343)
	at com.hazelcast.test.starter.HazelcastStarter.getTargetVersionClassloader(HazelcastStarter.java:210)
	at com.hazelcast.test.starter.HazelcastStarter.newHazelcastInstance(HazelcastStarter.java:101)
	at com.hazelcast.test.starter.HazelcastStarter.newHazelcastInstance(HazelcastStarter.java:69)
	at com.hazelcast.test.starter.test.HazelcastStarterTest.testMember(HazelcastStarterTest.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by vbekiaris** [comment]
Logs show long pauses (>1 minute) while waiting for artifacts download. Given that the test downloads & starts 7 HZ versions (3.7 - 3.7.6), the default 5 minutes timeout is not long enough. Did something change recently in the test environment? Artifacts download shouldn't take that long.

```
19:44:42,977  INFO |testMember| - [LifecycleService] testMember - [127.0.0.1]:5701 [dev] [3.7] [127.0.0.1]:5701 is STARTED
Starting member 3.7.1
class com.hazelcast.core.Hazelcast loaded by com.hazelcast.test.starter.HazelcastAPIDelegatingClassloader@152aff43
19:46:05,789  INFO |testMember| - [DefaultAddressPicker] testMember - [LOCAL] [dev] [3.7.1] Picked [127.0.0.1]:5702, using socket ServerSocket[addr=/0.0.0.0,localport=5702], bind any local is true
...
19:46:12,591  INFO |testMember| - [LifecycleService] testMember - [127.0.0.1]:5702 [dev] [3.7.1] [127.0.0.1]:5702 is SHUTDOWN
Starting member 3.7.2
19:46:12,591  INFO |testMember| - [TransactionManagerService] hz._hzInstance_1_dev.cached.thread-3 - [127.0.0.1]:5701 [dev] [3.7] Committing/rolling-back alive transactions of Memb
er [127.0.0.1]:5702 - 767d6ebc-1431-4c4d-b8f3-5fe32048a36c, UUID: 767d6ebc-1431-4c4d-b8f3-5fe32048a36c
class com.hazelcast.core.Hazelcast loaded by com.hazelcast.test.starter.HazelcastAPIDelegatingClassloader@7cba47c1
19:47:48,888  INFO |testMember| - [DefaultAddressPicker] testMember - [LOCAL] [dev] [3.7.2] Picked [127.0.0.1]:5702, using socket ServerSocket[addr=/0.0.0.0,localport=5702], bind a
ny local is true

...
19:47:54,531  INFO |testMember| - [LifecycleService] testMember - [127.0.0.1]:5702 [dev] [3.7.2] [127.0.0.1]:5702 is SHUTDOWN
Starting member 3.7.3
class com.hazelcast.core.Hazelcast loaded by com.hazelcast.test.starter.HazelcastAPIDelegatingClassloader@7651c392
19:48:43,518  INFO |testMember| - [DefaultAddressPicker] testMember - [LOCAL] [dev] [3.7.3] Picked [127.0.0.1]:5702, using socket ServerSocket[addr=/0.0.0.0,localport=5702], bind any local is true
```

**Comment by Holmistr** [comment]
@vbekiaris So you're saying that this is an issue of a slow downloading of Maven artifacts, right? We actually saw it in the past that sometimes Maven Central is being slow or not responsive for a while. 
If this is really the issue, maybe we can just increase the timeout for the artifacts download and close this, WDYT?

**Comment by Holmistr** [comment]
As discussed on the meeting, we will try to adjust build environment and also pre-download the needed artifacts. Closing this issue.
