### ISSUE TITLE
CacheLoaderTest, CacheLoaderWithoutReadThroughTest and CacheWriterTest failures

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#14034]
_master_ (commit 1ea1072518a48d7aa4c607e41c6007ef64dc903b)
_maintenance-3.x_ (commit 433611491761b8925df4307f4ef4880e9688e94f)

Failed on Sonar build:
* for master - https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-sonar/263/testReport/
* for maintenance-3.x - https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-sonar/192/testReport/

Following tests fail for probably the same reason:
* `com.hazelcast.client.cache.jsr.CacheLoaderTest.shouldPropagateExceptionUsingLoadAll`
* `com.hazelcast.client.cache.jsr.CacheLoaderWithoutReadThroughTest.shouldPropagateExceptionUsingLoadAll`
* `com.hazelcast.client.cache.jsr.CacheWriterTest.shouldWrapWriterExceptions`
* `com.hazelcast.client.cache.jsr.CacheWriterTest.shouldWriteThroughRemoveAll_partialSuccess`
* `com.hazelcast.client.cache.jsr.CacheWriterTest.shouldWriteThroughRemoveAllSpecific_partialSuccess`

Stacktrace:
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at javax.cache.integration.CompletionListenerFuture.get(CompletionListenerFuture.java:144)
	at org.jsr107.tck.integration.CacheLoaderTest.shouldPropagateExceptionUsingLoadAll(CacheLoaderTest.java:837)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

Standard outputs are:
```
21:54:07,021 ERROR || - [Invocation] hz._hzInstance_4_dev.async.thread-45 - [127.0.0.1]:5701 [dev] [3.12-SNAPSHOT] Failed asynchronous execution of execution callback: com.hazelcast.spi.impl.operationservice.impl.InvokeOnPartitionsAsync$FirstAttemptExecutionCallback@78dfe218for call Invocation{op=com.hazelcast.spi.impl.operationservice.impl.operations.PartitionIteratingOperation{serviceName='hz:impl:cacheService', identityHash=271317690, partitionId=-1, replicaIndex=0, callId=-361, invocationTime=1540418046697 (2018-10-24 21:54:06.697), waitTimeout=-1, callTimeout=120000, operationFactory=OperationFactoryWrapper{opFactory=com.hazelcast.cache.impl.operation.CacheLoadAllOperationFactory@76180373, uuid='5605042d-6b55-4061-89b4-b75979889748'}}, tryCount=10, tryPauseMillis=300, invokeCount=1, callTimeoutMillis=120000, firstInvocationTimeMs=1540418046697, firstInvocationTime='2018-10-24 21:54:06.697', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 00:00:00.000', target=[127.0.0.1]:5701, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=null}
javax.cache.integration.CacheLoaderException: Exception in CacheLoader during loadAll
	at com.hazelcast.cache.impl.AbstractCacheRecordStore.loadAllCacheEntry(AbstractCacheRecordStore.java:1073) ~[hazelcast-3.12-SNAPSHOT.jar:3.12-SNAPSHOT]
	at com.hazelcast.cache.impl.AbstractCacheRecordStore.loadAll(AbstractCacheRecordStore.java:1708) ~[hazelcast-3.12-SNAPSHOT.jar:3.12-SNAPSHOT]
	at com.hazelcast.cache.impl.operation.CacheLoadAllOperation.run(CacheLoadAllOperation.java:98) ~[hazelcast-3.12-SNAPSHOT.jar:3.12-SNAPSHOT]
	at com.hazelcast.spi.Operation.call(Operation.java:170) ~[hazelcast-3.12-SNAPSHOT.jar:3.12-SNAPSHOT]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:208) ~[hazelcast-3.12-SNAPSHOT.jar:3.12-SNAPSHOT]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:197) ~[hazelcast-3.12-SNAPSHOT.jar:3.12-SNAPSHOT]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:147) ~[hazelcast-3.12-SNAPSHOT.jar:3.12-SNAPSHOT]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:177) ~[hazelcast-3.12-SNAPSHOT.jar:3.12-SNAPSHOT]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:131) ~[hazelcast-3.12-SNAPSHOT.jar:3.12-SNAPSHOT]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:110) ~[hazelcast-3.12-SNAPSHOT.jar:3.12-SNAPSHOT]
Caused by: java.lang.UnsupportedOperationException
	at org.jsr107.tck.integration.FailingCacheLoader.loadAll(FailingCacheLoader.java:32) ~[cache-tests-1.1.0.jar:?]
	at org.jsr107.tck.integration.CacheLoaderServer$LoadAllOperationHandler.onProcess(CacheLoaderServer.java:98) ~[cache-tests-1.1.0.jar:?]
	at org.jsr107.tck.support.Server$ClientConnection.run(Server.java:310) ~[cache-tests-1.1.0.jar:?]
```
```
21:59:34,414 ERROR || - [CachePutOperation] hz._hzInstance_11_dev.partition-operation.thread-32 - [127.0.0.1]:5701 [dev] [3.12-SNAPSHOT] Exception in CacheWriter during write
javax.cache.integration.CacheWriterException: Exception in CacheWriter during write
	at com.hazelcast.cache.impl.AbstractCacheRecordStore.writeThroughCache(AbstractCacheRecordStore.java:1008) ~[hazelcast-3.12-SNAPSHOT.jar:3.12-SNAPSHOT]
	at com.hazelcast.cache.impl.AbstractCacheRecordStore.createRecord(AbstractCacheRecordStore.java:678) ~[hazelcast-3.12-SNAPSHOT.jar:3.12-SNAPSHOT]
	at com.hazelcast.cache.impl.AbstractCacheRecordStore.createRecordWithExpiry(AbstractCacheRecordStore.java:702) ~[hazelcast-3.12-SNAPSHOT.jar:3.12-SNAPSHOT]
	at com.hazelcast.cache.impl.AbstractCacheRecordStore.createRecordWithExpiry(AbstractCacheRecordStore.java:731) ~[hazelcast-3.12-SNAPSHOT.jar:3.12-SNAPSHOT]
	at com.hazelcast.cache.impl.AbstractCacheRecordStore.put(AbstractCacheRecordStore.java:1266) ~[hazelcast-3.12-SNAPSHOT.jar:3.12-SNAPSHOT]
	at com.hazelcast.cache.impl.AbstractCacheRecordStore.put(AbstractCacheRecordStore.java:1297) ~[hazelcast-3.12-SNAPSHOT.jar:3.12-SNAPSHOT]
	at com.hazelcast.cache.impl.operation.CachePutOperation.run(CachePutOperation.java:61) ~[hazelcast-3.12-SNAPSHOT.jar:3.12-SNAPSHOT]
	at com.hazelcast.spi.Operation.call(Operation.java:170) ~[hazelcast-3.12-SNAPSHOT.jar:3.12-SNAPSHOT]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:208) [hazelcast-3.12-SNAPSHOT.jar:3.12-SNAPSHOT]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:197) [hazelcast-3.12-SNAPSHOT.jar:3.12-SNAPSHOT]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:407) [hazelcast-3.12-SNAPSHOT.jar:3.12-SNAPSHOT]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:434) [hazelcast-3.12-SNAPSHOT.jar:3.12-SNAPSHOT]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:586) [hazelcast-3.12-SNAPSHOT.jar:3.12-SNAPSHOT]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:571) [hazelcast-3.12-SNAPSHOT.jar:3.12-SNAPSHOT]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:530) [hazelcast-3.12-SNAPSHOT.jar:3.12-SNAPSHOT]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:220) [hazelcast-3.12-SNAPSHOT.jar:3.12-SNAPSHOT]
	at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:60) [hazelcast-3.12-SNAPSHOT.jar:3.12-SNAPSHOT]
	at com.hazelcast.client.impl.protocol.task.AbstractPartitionMessageTask.processMessage(AbstractPartitionMessageTask.java:67) [hazelcast-3.12-SNAPSHOT.jar:3.12-SNAPSHOT]
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:123) [hazelcast-3.12-SNAPSHOT.jar:3.12-SNAPSHOT]
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.doRun(AbstractMessageTask.java:111) [hazelcast-3.12-SNAPSHOT.jar:3.12-SNAPSHOT]
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:101) [hazelcast-3.12-SNAPSHOT.jar:3.12-SNAPSHOT]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:161) [hazelcast-3.12-SNAPSHOT.jar:3.12-SNAPSHOT]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:159) [hazelcast-3.12-SNAPSHOT.jar:3.12-SNAPSHOT]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:127) [hazelcast-3.12-SNAPSHOT.jar:3.12-SNAPSHOT]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:110) [hazelcast-3.12-SNAPSHOT.jar:3.12-SNAPSHOT]
Caused by: java.lang.UnsupportedOperationException
	at org.jsr107.tck.integration.FailingCacheWriter.write(FailingCacheWriter.java:24) ~[cache-tests-1.1.0.jar:?]
	at org.jsr107.tck.integration.CacheWriterServer$WriteOperationHandler.onProcess(CacheWriterServer.java:274) ~[cache-tests-1.1.0.jar:?]
	at org.jsr107.tck.support.Server$ClientConnection.run(Server.java:310) ~[cache-tests-1.1.0.jar:?]
```
```
22:09:38,561 ERROR || - [Invocation] hz._hzInstance_11_dev.async.thread-48 - [127.0.0.1]:5701 [dev] [3.12-SNAPSHOT] Failed asynchronous execution of execution callback: com.hazelcast.spi.impl.operationservice.impl.InvokeOnPartitionsAsync$FirstAttemptExecutionCallback@4f27653efor call Invocation{op=com.hazelcast.spi.impl.operationservice.impl.operations.PartitionIteratingOperation{serviceName='hz:impl:cacheService', identityHash=2024586464, partitionId=-1, replicaIndex=0, callId=-586, invocationTime=1540418978320 (2018-10-24 22:09:38.320), waitTimeout=-1, callTimeout=120000, operationFactory=OperationFactoryWrapper{opFactory=com.hazelcast.cache.impl.operation.CacheRemoveAllOperationFactory@41e082aa, uuid='0462871d-e805-4f19-9ca2-09bf6f237767'}}, tryCount=10, tryPauseMillis=300, invokeCount=1, callTimeoutMillis=120000, firstInvocationTimeMs=1540418978320, firstInvocationTime='2018-10-24 22:09:38.320', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 00:00:00.000', target=[127.0.0.1]:5701, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=null}
javax.cache.integration.CacheWriterException: Exception in CacheWriter during deleteAll
	at com.hazelcast.cache.impl.AbstractCacheRecordStore.deleteAllCacheEntry(AbstractCacheRecordStore.java:1048) ~[hazelcast-3.12-SNAPSHOT.jar:3.12-SNAPSHOT]
	at com.hazelcast.cache.impl.AbstractCacheRecordStore.removeAll(AbstractCacheRecordStore.java:1678) ~[hazelcast-3.12-SNAPSHOT.jar:3.12-SNAPSHOT]
	at com.hazelcast.cache.impl.operation.CacheRemoveAllOperation.run(CacheRemoveAllOperation.java:82) ~[hazelcast-3.12-SNAPSHOT.jar:3.12-SNAPSHOT]
	at com.hazelcast.spi.Operation.call(Operation.java:170) ~[hazelcast-3.12-SNAPSHOT.jar:3.12-SNAPSHOT]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:208) ~[hazelcast-3.12-SNAPSHOT.jar:3.12-SNAPSHOT]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:197) ~[hazelcast-3.12-SNAPSHOT.jar:3.12-SNAPSHOT]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:147) ~[hazelcast-3.12-SNAPSHOT.jar:3.12-SNAPSHOT]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:177) ~[hazelcast-3.12-SNAPSHOT.jar:3.12-SNAPSHOT]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:131) ~[hazelcast-3.12-SNAPSHOT.jar:3.12-SNAPSHOT]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:110) ~[hazelcast-3.12-SNAPSHOT.jar:3.12-SNAPSHOT]
Caused by: javax.cache.CacheException: simulated delete failure for key 1
	at org.jsr107.tck.integration.BatchPartialSuccessRecordingClassWriter.deleteAll(BatchPartialSuccessRecordingClassWriter.java:107) ~[cache-tests-1.1.0.jar:?]
	at org.jsr107.tck.integration.CacheWriterServer$DeleteAllOperationHandler.onProcess(CacheWriterServer.java:95) ~[cache-tests-1.1.0.jar:?]
	at org.jsr107.tck.support.Server$ClientConnection.run(Server.java:310) ~[cache-tests-1.1.0.jar:?]
```

**Comment by olukas** [comment]
Closing, duplicate of https://github.com/hazelcast/hazelcast/issues/14003
