### ISSUE TITLE
MemcacheTest.testSetGetDelete_WithDefaultIMap

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#14048]
_maintenance-3.x_ (commit d150acefb554f2055c7566f79830e63652d29bb9)

Failed on IBM JDK8 build: https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.maintenance-IbmJDK8/37/testReport/com.hazelcast.internal.ascii/MemcacheTest/testSetGetDelete_WithDefaultIMap/

Stacktrace:
```
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1453)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1477)
	at sun.nio.ch.SelectorImpl.implCloseSelector(SelectorImpl.java:124)
	at java.nio.channels.spi.AbstractSelector.close(AbstractSelector.java:122)
	at net.spy.memcached.MemcachedConnection.shutdown(MemcachedConnection.java:1339)
	at net.spy.memcached.MemcachedClient.shutdown(MemcachedClient.java:2512)
	at net.spy.memcached.MemcachedClient.shutdown(MemcachedClient.java:2474)
	at com.hazelcast.internal.ascii.MemcacheTest.tearDown(MemcacheTest.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:402)
	at com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37)
	at com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:104)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at com.hazelcast.test.HazelcastParallelClassRunner.access$301(HazelcastParallelClassRunner.java:49)
	at com.hazelcast.test.HazelcastParallelClassRunner$TestRunner.run(HazelcastParallelClassRunner.java:162)
	at java.lang.Thread.run(Thread.java:811)
```

Standard output:
```
Hiccups measured while running test 'testSetGetDelete_WithDefaultIMap(com.hazelcast.internal.ascii.MemcacheTest):'
09:50:05, accumulated pauses: 49 ms, max pause: 39 ms, pauses over 1000 ms: 0
```

**Comment by olukas** [comment]
Closing this issue after discussion with @Holmistr. He investigated this issue a while ago and it shows that it's a bug in the Spymemcached client (see stacktrace). We do not want to fix Spymemcached client and there is probably nothing what we can do with this issue. It also fails very rarely.
