### ISSUE TITLE
ClientScheduledExecutorServiceBasicTest.schedule_whenShutdown

### ISSUE THREAD

**Issue by tezc** [hazelcast/hazelcast#14055]
_master_ (commit 75c2b735be752f6502d903e28c29edc641f3c13d)

Failed on OracleJDK6 : https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-OracleJDK6/508/testReport/junit/com.hazelcast.client.scheduledexecutor/ClientScheduledExecutorServiceBasicTest/schedule_whenShutdown/

Stacktrace : 

```
java.lang.AssertionError: Expected exception: java.util.concurrent.RejectedExecutionException
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:32)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.lang.Thread.run(Thread.java:662)
```

Standard output : 
```
Finished Running Test: getErroneous in 170.552 seconds.
06:53:04,055  INFO |schedule_whenShutdown| - [NodeExtension] Thread-3060 - [127.0.0.1]:5702 [dev] [3.12-SNAPSHOT] Destroying node NodeExtension.
06:53:04,055  INFO |schedule_whenShutdown| - [Node] Thread-3060 - [127.0.0.1]:5702 [dev] [3.12-SNAPSHOT] Hazelcast Shutdown is completed in 23 ms.
06:53:04,055  INFO |schedule_whenShutdown| - [LifecycleService] Thread-3060 - [127.0.0.1]:5702 [dev] [3.12-SNAPSHOT] [127.0.0.1]:5702 is SHUTDOWN
BuildInfo right after schedule_whenShutdown(com.hazelcast.client.scheduledexecutor.ClientScheduledExecutorServiceBasicTest): BuildInfo{version='3.12-SNAPSHOT', build='20181026', buildNumber=20181026, revision=75c2b73, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'schedule_whenShutdown(com.hazelcast.client.scheduledexecutor.ClientScheduledExecutorServiceBasicTest):'
06:50:10, accumulated pauses: 4445 ms, max pause: 4302 ms, pauses over 1000 ms: 1
06:50:15, accumulated pauses: 2905 ms, max pause: 2903 ms, pauses over 1000 ms: 1
06:50:20, accumulated pauses: 3448 ms, max pause: 3446 ms, pauses over 1000 ms: 1
06:50:25, accumulated pauses: 6852 ms, max pause: 3910 ms, pauses over 1000 ms: 2
06:50:30, accumulated pauses: 0 ms, max pause: 0 ms, pauses over 1000 ms: 0
06:50:35, accumulated pauses: 9633 ms, max pause: 6654 ms, pauses over 1000 ms: 2
06:50:40, accumulated pauses: 9386 ms, max pause: 6489 ms, pauses over 1000 ms: 2
06:50:50, accumulated pauses: 5893 ms, max pause: 5892 ms, pauses over 1000 ms: 1
06:50:55, accumulated pauses: 101 ms, max pause: 101 ms, pauses over 1000 ms: 0
06:51:00, accumulated pauses: 8984 ms, max pause: 3120 ms, pauses over 1000 ms: 3
06:51:05, accumulated pauses: 2848 ms, max pause: 2848 ms, pauses over 1000 ms: 1
06:51:10, accumulated pauses: 6053 ms, max pause: 3251 ms, pauses over 1000 ms: 2
06:51:15, accumulated pauses: 12285 ms, max pause: 9387 ms, pauses over 1000 ms: 2
06:51:25, accumulated pauses: 6196 ms, max pause: 6196 ms, pauses over 1000 ms: 1
06:51:35, accumulated pauses: 6199 ms, max pause: 3245 ms, pauses over 1000 ms: 2
06:51:40, accumulated pauses: 6110 ms, max pause: 3033 ms, pauses over 1000 ms: 2
06:51:45, accumulated pauses: 0 ms, max pause: 0 ms, pauses over 1000 ms: 0
06:51:50, accumulated pauses: 9501 ms, max pause: 6568 ms, pauses over 1000 ms: 2
06:51:55, accumulated pauses: 9415 ms, max pause: 6465 ms, pauses over 1000 ms: 2
06:52:05, accumulated pauses: 1949 ms, max pause: 1949 ms, pauses over 1000 ms: 1
06:52:10, accumulated pauses: 12081 ms, max pause: 6132 ms, pauses over 1000 ms: 2
06:52:15, accumulated pauses: 4640 ms, max pause: 4640 ms, pauses over 1000 ms: 1
06:52:25, accumulated pauses: 5829 ms, max pause: 2902 ms, pauses over 1000 ms: 2
06:52:30, accumulated pauses: 6129 ms, max pause: 3326 ms, pauses over 1000 ms: 2
06:52:35, accumulated pauses: 5853 ms, max pause: 2955 ms, pauses over 1000 ms: 2
06:52:40, accumulated pauses: 3360 ms, max pause: 3360 ms, pauses over 1000 ms: 1
06:52:45, accumulated pauses: 5796 ms, max pause: 2925 ms, pauses over 1000 ms: 2
06:52:50, accumulated pauses: 2876 ms, max pause: 2872 ms, pauses over 1000 ms: 1
06:52:55, accumulated pauses: 2873 ms, max pause: 2857 ms, pauses over 1000 ms: 1
06:53:00, accumulated pauses: 750 ms, max pause: 670 ms, pauses over 1000 ms: 0
```

Might be related with https://github.com/hazelcast/hazelcast/issues/13971

**Comment by Holmistr** [comment]
This is a timing problem. We need to invest more time into spreading up the load on the build machine. Please, let's leave this issue opened for sharing ideas.

**Comment by tezc** [comment]
Builds schedule has been adjusted on the lab machine so we don't expect to see extreme hiccups. Closing the issue as it hasn't occurred for a while.
