### ISSUE TITLE
Unable to read custom hazelcast.xml on classpath

### ISSUE THREAD

**Issue by pavasthi1** [hazelcast/hazelcast#14070]
I am using hazelcast 3.10.  My hazelcast.xml file is in my project's resource directory. This is the excerpt from hazelcast.xml.
```xml
<hazelcast xmlns="http://www.hazelcast.com/schema/config"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.hazelcast.com/schema/config
           http://www.hazelcast.com/schema/config/hazelcast-config-3.10.xsd">
```

I get the following error:

```
Nov 06, 2018 12:02:41 PM com.hazelcast.config.AbstractXmlConfigHelper
WARNING: Name of the hazelcast schema location incorrect using default
2018-11-06 11:49:16,748    INFO  com.bnymellon.ais.anp.core.hazelcast.HazelcastConfiguration - Exception occured
com.hazelcast.config.InvalidConfigurationException: cvc-complex-type.2.4.a: Invalid content was found starting with element 'failure-detector'. One of '{"http://www.hazelcast.com/schema/config":public-address, "http://www.hazelcast.com/schema/config":reuse-address, "http://www.hazelcast.com/schema/config":interfaces, "http://www.hazelcast.com/schema/config":member-address-provider}' is expected.
	at com.hazelcast.config.AbstractXmlConfigHelper.schemaValidation(AbstractXmlConfigHelper.java:186)
	at com.hazelcast.config.XmlConfigBuilder.parseAndBuildConfig(XmlConfigBuilder.java:235)
	at com.hazelcast.config.XmlConfigBuilder.build(XmlConfigBuilder.java:216)
	at com.hazelcast.config.XmlConfigBuilder.build(XmlConfigBuilder.java:209)
```

**Comment by ahmetmircik** [comment]
Seems below xsd-s are not in sync and `failure-detector` doesn't exist in the first link.

1. https://hazelcast.com/schema/config/hazelcast-config-3.10.xsd
2. https://github.com/hazelcast/hazelcast/blob/v3.10.6/hazelcast/src/main/resources/hazelcast-config-3.10.xsd

**Comment by mmedenjak** [comment]
Related: https://github.com/hazelcast/hazelcast/issues/13011

**Comment by tezc** [comment]
@pavasthi1 XSD files are in sync now, you can try it again. Let us know if there is any problem with that.

**Comment by mmedenjak** [comment]
Closing as the XSDs should be in sync. Please open a new issue if you encounter more problems.
