### ISSUE TITLE
client connection problems with OpenSSL

### ISSUE THREAD

**Issue by enesakar** [hazelcast/hazelcast#14071]
On hazelcast cloud, when we enabled TLS (open ssl); clients are quite instable. 
They rarely connect succesfully.

When I try to connect client throws following exception:
```java
WARNING: hz.client_0 [tls2] [3.11-BETA-1] ClientConnection{alive=false, connectionId=1, channel=13:16:49 63540=>31637, remoteEndpoint=null, lastReadTime=2018-11-06 13:15:49.110, lastWriteTime=2018-11-06 13:15:49.110, closedTime=2018-11-06 13:16:49.108, connected server version=null} closed. Reason: java.util.concurrent.ExecutionException[java.util.concurrent.TimeoutException: Authentication response did not come back in 60000 millis]
java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException: Authentication response did not come back in 60000 millis
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolve(ClientInvocationFuture.java:73)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run(AbstractInvocationFuture.java:250)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
Caused by: java.util.concurrent.TimeoutException: Authentication response did not come back in 60000 millis
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl$TimeoutAuthenticationTask.run(ClientConnectionManagerImpl.java:613)
	... 9 more
```

server config
```xml
 <ssl enabled="true">
                <factory-class-name>com.hazelcast.nio.ssl.OpenSSLEngineFactory</factory-class-name>
                <properties>
                    <property name="keyStore">${clusterConfig.tlsFileName}</property>
                    <property name="keyStorePassword">${clusterConfig.tlsPassword}</property>
                    <property name="keyManagerAlgorithm">SunX509</property>
                    <property name="trustManagerAlgorithm">SunX509</property>
                    <property name="trustStore">${clusterConfig.tlsFileName}</property>
                    <property name="trustStorePassword">${clusterConfig.tlsPassword}</property>
                    <property name="ciphersuites">TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,
                        TLS_ECDH_RSA_WITH_3DES_EDE_CBC_SHA</property>
                    <property name="protocol">TLSv1.2</property>
                </properties>
            </ssl>
```

client config
```java
      SSLConfig sslConfig = new SSLConfig();
        config.getNetworkConfig().setSSLConfig(sslConfig.setEnabled(true));
```

**Comment by sancar** [comment]
@huseyinbabal Is this still a problem in 4.x series or should we close if there is no known issue at the moment ?

**Comment by mmedenjak** [comment]
@huseyinbabal any updates from your side?

**Comment by sancar** [comment]
@huseyinbabal I have run a test with 4.2.2 and TLS enabled. It worked without a problem.

**Comment by huseyinbabal** [comment]
> @huseyinbabal I have run a test with 4.2.2 and TLS enabled. It worked without a problem.

We don't have SSL problems in up-to-date versions, you can close. Thanks
