### ISSUE TITLE
MessageListener fails to receive messages after client reconnect to cluster

### ISSUE THREAD

**Issue by kdohz** [hazelcast/hazelcast#14123]
Report issue:

When the client reconnects (transition from CONNECTED -> DISCONNECTED -> CONNECTED), the MessageListener added to the client no longer receives messages. However, the MapListener continues to receive map entry events after reconnection. 
The HZ version in use is 3.11.

Scenario details:

1) HZ cluster has 2 members 41 and 43.
2) HZ client is configured as follows:
```
      ClientConnectionStrategyConfig connectionStrategy = clientConfig.getConnectionStrategyConfig();
      ConnectionRetryConfig connectionRetry = connectionStrategy.getConnectionRetryConfig();
      
      connectionStrategy.setAsyncStart(true); // default is false
      connectionStrategy.setReconnectMode(ClientConnectionStrategyConfig.ReconnectMode.ASYNC); // default is OFF
      connectionRetry.setInitialBackoffMillis(1000);
      connectionRetry.setMaxBackoffMillis(1000); // default is 30000
      connectionRetry.setMultiplier(2); // default is 2
      connectionRetry.setFailOnMaxBackoff(false); // default is false. 
      connectionRetry.setJitter(0.2); // default is 0.2
      connectionRetry.setEnabled(true); // default is false
```
3) HZ client is CONNECTED to the cluster via 41 as owner member.
4) MessageListener is successfully registered and is successfully receive messages.
5) MapListener is successfully registered and is successfully receive notification upon add/update/remove entry in the map.
6) Disconnect 41 from the network.
7) HZ client transition from DISCONNECTED to CONNECTED state where 43 is now the owner member. 
8) Add/update/remove entry in the map successfully triggers the MapListener to receive the corresponding event.
9) MessageListener receives nothing when a message is published.

Note that the same issue is observed when the cluster has only one member and the client is reconnected.

Observation
Remove the old message listener and add new message listener works around the problem i.e the new MessageListener starts to receive published messages.

**Comment by sancar** [comment]
Hi @kdohz 
I assume that you are using ReliableTopic, because ITopic Messagelistener and MapListener works same. 
ReliableTopic can terminate when events are lost. Not sure what is happened in your case. You can check the logs to see if it is terminated.  Messages like "Terminating MessageListener ... " are logged in `warning` level. 

Also to have more control over ReliableTopic you can use `ReliableMessageListener` instead of `MessageListener`

**Comment by kdohz** [comment]
Here is some details information that could help diagnose the problem:

1.  Yes, ReliableTopic is being used:

          ITopic<byte[]> topic = hazelcastClient.getReliableTopic(topicName);

2.  Yes, ReliableMessageListener is being used:

    private class ReliableMessageListenerImpl implements ReliableMessageListener<byte[]>
    {
      public void onMessage(Message<byte[]> m)
      {
        queueMessage(m.getMessageObject());
      }
      
      /**
       * This method is called when we try to read messages using the staled sequence. 
       * Staled sequence happens when we lose connectivity on the cluster or the publisher
       * is much faster than us (unlikely). We want to return true to prevent Hazelcast
       * from terminating the observer.
       */
      @Override
      public boolean isLossTolerant() 
      {
        // notify observer that some messages may have lost
        handleMessagesLost();
        return true;
      }

      /** 
       * Tell Hazelcast whether observer should be terminated on the failure parameter.
       * Return false to prevent Hazelcast from terminating the observer.
       */
      @Override
      public boolean isTerminal(Throwable failure) 
      {
        return false;
      }

      /** 
       * @return the stored sequence
       * This method is called once when we register the observer. 
       */
      @Override
      public long retrieveInitialSequence() 
      {
        return (msgSequence == -1)? msgSequence: msgSequence + 1;
      }

      /** 
       * Store the sequence for failure recovery purpose 
       */
      @Override
      public void storeSequence(long sequence) 
      {
        msgSequence = sequence;
      }
    }
  }

3. And finally, right after the client receives CLIENT_DISCONNECTED event, this warning log is seen:

        hz.client_0 [as] [3.11] Terminating MessageListener com.broadsoft.persistence.hazelcast.BWHazelcastInstance$TopicContainer$ReliableMessageListenerImpl@7dc4a2ed on topic: profileManagementUpdate. Reason: Unhandled exception, message: Client is offline. <com.hazelcast.client.HazelcastClientOfflineException: Client is offline.>com.hazelcast.client.HazelcastClientOfflineException: Client is offline.
        at com.hazelcast.client.connection.nio.DefaultClientConnectionStrategy.beforeGetConnection(DefaultClientConnectionStrategy.java:58)
        at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.checkAllowed(ClientConnectionManagerImpl.java:335)
        at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.getConnection(ClientConnectionManagerImpl.java:307)
        at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.getOrTriggerConnect(ClientConnectionManagerImpl.java:298)
        at com.hazelcast.client.spi.impl.SmartClientInvocationService.getOrTriggerConnect(SmartClientInvocationService.java:73)
        at com.hazelcast.client.spi.impl.SmartClientInvocationService.invokeOnPartitionOwner(SmartClientInvocationService.java:48)
        at com.hazelcast.client.spi.impl.ClientInvocation.invokeOnSelection(ClientInvocation.java:163)
        at com.hazelcast.client.spi.impl.ClientInvocation.retry(ClientInvocation.java:194)
        at com.hazelcast.client.spi.impl.ClientInvocation.run(ClientInvocation.java:179)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
        at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
        at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)

**Comment by sancar** [comment]
This seems like a bug. It make sense to retry HazelcastClientOfflineException. 
I will prepare a fix for next patch. 
Thanks for the report.
