### ISSUE TITLE
Disable Hibernate in hazelcast-spring

### ISSUE THREAD

**Issue by shahbour** [hazelcast/hazelcast#14155]
I am trying to use hazelcast as a cache client for my application using spring-boot 2.1 but I am getting error complaining about class not found even though in don't have hibernate in my classpath

in my config map i added 

```
		<dependency>
			<groupId>com.hazelcast</groupId>
			<artifactId>hazelcast</artifactId>
		</dependency>
		<dependency>
			<groupId>com.hazelcast</groupId>
			<artifactId>hazelcast-spring</artifactId>
		</dependency>
		<dependency>
			<groupId>com.hazelcast</groupId>
			<artifactId>hazelcast-client</artifactId>
		</dependency>
```

But as soon as I start using method that do have `@Cache` enabled i got the below error , even though the logic of my code compelete sucessfully .

I don't know who is using `com.hazelcast.hibernate.region.CacheKeyImpl` but i think it might be some statistics ?

```
com.hazelcast.nio.serialization.HazelcastSerializationException: Problem while reading DataSerializable, namespace: 0, ID: 0, class: 'com.hazelcast.hibernate.region.CacheKeyImpl', exception: com.hazelcast.hibernate.region.CacheKeyImpl
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.rethrowReadException(DataSerializableSerializer.java:183) ~[hazelcast-3.11.jar:3.11]
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.readInternal(DataSerializableSerializer.java:164) ~[hazelcast-3.11.jar:3.11]
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:106) ~[hazelcast-3.11.jar:3.11]
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:51) ~[hazelcast-3.11.jar:3.11]
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48) ~[hazelcast-3.11.jar:3.11]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:187) ~[hazelcast-3.11.jar:3.11]
	at com.hazelcast.internal.nearcache.impl.invalidation.RepairingHandler.handle(RepairingHandler.java:90) ~[hazelcast-3.11.jar:3.11]
	at com.hazelcast.internal.nearcache.impl.invalidation.RepairingHandler.handle(RepairingHandler.java:120) ~[hazelcast-3.11.jar:3.11]
	at com.hazelcast.client.proxy.NearCachedClientMapProxy$NearCacheInvalidationEventHandler.handleIMapBatchInvalidationEventV14(NearCachedClientMapProxy.java:743) ~[hazelcast-client-3.11.jar:3.11]
	at com.hazelcast.client.impl.protocol.codec.MapAddNearCacheInvalidationListenerCodec$AbstractEventHandler.handle(MapAddNearCacheInvalidationListenerCodec.java:271) ~[hazelcast-3.11.jar:3.11]
	at com.hazelcast.client.proxy.NearCachedClientMapProxy$NearCacheInvalidationEventHandler.handle(NearCachedClientMapProxy.java:686) ~[hazelcast-client-3.11.jar:3.11]
	at com.hazelcast.client.spi.impl.listener.AbstractClientListenerService$ClientEventProcessor.run(AbstractClientListenerService.java:368) ~[hazelcast-client-3.11.jar:3.11]
	at com.hazelcast.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:226) [hazelcast-3.11.jar:3.11]
	at com.hazelcast.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:209) [hazelcast-3.11.jar:3.11]
Caused by: java.lang.ClassNotFoundException: com.hazelcast.hibernate.region.CacheKeyImpl
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_101]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_101]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[na:1.8.0_101]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_101]
	at com.hazelcast.nio.ClassLoaderUtil.tryLoadClass(ClassLoaderUtil.java:288) ~[hazelcast-3.11.jar:3.11]
	at com.hazelcast.nio.ClassLoaderUtil.newInstance0(ClassLoaderUtil.java:212) ~[hazelcast-3.11.jar:3.11]
	at com.hazelcast.nio.ClassLoaderUtil.newInstance(ClassLoaderUtil.java:193) ~[hazelcast-3.11.jar:3.11]
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.readInternal(DataSerializableSerializer.java:152) ~[hazelcast-3.11.jar:3.11]
	... 12 common frames omitted
```

**Comment by jerrinot** [comment]
hi,

is there another application with Hibernate using the same map?

**Comment by shahbour** [comment]
Hello 

No all the cache i use are prefixed with program name so they don't conflict with another . I think the issue is raising from this Map `org.hibernate.cache.spi.UpdateTimestampsCache` as it is auto created and not by me , so it is shared by all programs

**Comment by shahbour** [comment]
Another type of error i receive if i add the hibernate class , i think this is happening because my application is spring boot 2.1 and some others are 2.0 . Putting it just if it can help identifiy the class being cached 

```
hz.client_0 [dev] [3.11] hz.client_0.event-2 caught an exception while processing task:com.hazelcast.client.spi.impl.listener.AbstractClientListenerService$ClientEventProcessor@5460b626
com.hazelcast.nio.serialization.HazelcastSerializationException: java.io.InvalidClassException: org.hibernate.type.descriptor.java.AbstractTypeDescriptor; local class incompatible: stream classdesc serialVersionUID = -4368592018570692011, local class serialVersionUID = 3579666590527054900
	at com.hazelcast.internal.serialization.impl.SerializationUtil.handleException(SerializationUtil.java:63) ~[hazelcast-3.11.jar!/:3.11]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.readObject(AbstractSerializationService.java:275) ~[hazelcast-3.11.jar!/:3.11]
	at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readObject(ByteArrayObjectDataInput.java:574) ~[hazelcast-3.11.jar!/:3.11]
	at com.hazelcast.hibernate.region.CacheKeyImpl.readData(CacheKeyImpl.java:89) ~[hazelcast-hibernate52-1.2.3.jar!/:1.2.3]
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.readInternal(DataSerializableSerializer.java:160) ~[hazelcast-3.11.jar!/:3.11]
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:106) ~[hazelcast-3.11.jar!/:3.11]
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:51) ~[hazelcast-3.11.jar!/:3.11]
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48) ~[hazelcast-3.11.jar!/:3.11]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:187) ~[hazelcast-3.11.jar!/:3.11]
	at com.hazelcast.internal.nearcache.impl.invalidation.RepairingHandler.handle(RepairingHandler.java:90) ~[hazelcast-3.11.jar!/:3.11]
	at com.hazelcast.internal.nearcache.impl.invalidation.RepairingHandler.handle(RepairingHandler.java:120) ~[hazelcast-3.11.jar!/:3.11]
	at com.hazelcast.client.proxy.NearCachedClientMapProxy$NearCacheInvalidationEventHandler.handleIMapBatchInvalidationEventV14(NearCachedClientMapProxy.java:743) ~[hazelcast-client-3.11.jar!/:3.11]
	at com.hazelcast.client.impl.protocol.codec.MapAddNearCacheInvalidationListenerCodec$AbstractEventHandler.handle(MapAddNearCacheInvalidationListenerCodec.java:271) ~[hazelcast-3.11.jar!/:3.11]
	at com.hazelcast.client.proxy.NearCachedClientMapProxy$NearCacheInvalidationEventHandler.handle(NearCachedClientMapProxy.java:686) ~[hazelcast-client-3.11.jar!/:3.11]
	at com.hazelcast.client.spi.impl.listener.AbstractClientListenerService$ClientEventProcessor.run(AbstractClientListenerService.java:368) ~[hazelcast-client-3.11.jar!/:3.11]
	at com.hazelcast.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:226) [hazelcast-3.11.jar!/:3.11]
	at com.hazelcast.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:209) [hazelcast-3.11.jar!/:3.11]
Caused by: java.io.InvalidClassException: org.hibernate.type.descriptor.java.AbstractTypeDescriptor; local class incompatible: stream classdesc serialVersionUID = -4368592018570692011, local class serialVersionUID = 3579666590527054900
	at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:699) ~[na:1.8.0_181]
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1885) ~[na:1.8.0_181]
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1751) ~[na:1.8.0_181]
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1885) ~[na:1.8.0_181]
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1751) ~[na:1.8.0_181]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2042) ~[na:1.8.0_181]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573) ~[na:1.8.0_181]
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2287) ~[na:1.8.0_181]
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2211) ~[na:1.8.0_181]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069) ~[na:1.8.0_181]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573) ~[na:1.8.0_181]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:431) ~[na:1.8.0_181]
	at com.hazelcast.internal.serialization.impl.JavaDefaultSerializers$JavaSerializer.read(JavaDefaultSerializers.java:82) ~[hazelcast-3.11.jar!/:3.11]
	at com.hazelcast.internal.serialization.impl.JavaDefaultSerializers$JavaSerializer.read(JavaDefaultSerializers.java:75) ~[hazelcast-3.11.jar!/:3.11]
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48) ~[hazelcast-3.11.jar!/:3.11]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.readObject(AbstractSerializationService.java:269) ~[hazelcast-3.11.jar!/:3.11]
	... 15 common frames omitted
```

**Comment by shahbour** [comment]
Hello

After more digging into the issue, I saw that the problem is raising on RepairingTask, for some reason the ReparingTask is being run on Maps that I don't use on this program. 

So maybe it is a misconfiguration from my side when setting up the near cache config, I don't know if i should specify what maps to use , i thought this will be done automatically as needed .

below are my configuration for near cache 

```
  @Bean
    public HazelcastInstance getHazelcastInstance() {
        ClientConfig config = new ClientConfig();

        config.getNetworkConfig().addAddress(serviceIp);

        EvictionConfig evictionConfig = new EvictionConfig()
                .setMaximumSizePolicy(EvictionConfig.MaxSizePolicy.ENTRY_COUNT)
                .setEvictionPolicy(EvictionPolicy.LFU)
                .setSize(3000);

        NearCacheConfig aDefault = new NearCacheConfig()
                .setName("default")
                .setTimeToLiveSeconds(1800)
                .setMaxIdleSeconds(900)
                .setInMemoryFormat(InMemoryFormat.OBJECT)
                .setEvictionConfig(evictionConfig);


        config.addNearCacheConfig(aDefault);

        return HazelcastClient.newHazelcastClient(config);
    }
```

Attached is the image where the error is being raised 

![screen shot 2018-11-23 at 8 37 33 am](https://user-images.githubusercontent.com/1893624/48930880-f4704300-eefb-11e8-9593-aa4e99a557ae.png)

**Comment by ahmetmircik** [comment]
Hi @shahbour,

`default` is a specially treated name in Hazelcast configurations. Adding `NearCacheConfig` with `default` name makes all maps accessed over this client as near-cached maps. Because if a map has no explicit near-cache config with its name, near-cache config for the name `default` is picked. So there should be no near-cache config with `default` name, if the intention is not really to make all maps near-cached.

In your case instead of `default`, you can use specific map name.

```
NearCacheConfig aDefault = new NearCacheConfig()
                .setName("yourMapName") 
```

**Comment by shahbour** [comment]
Hello

Yes, I have changed the name to cdr-import* as all my cache use this prefix and it is working perfectly now no more hibernate issues.

Note: In the above example I never used the map `com.teltacworldwide.domain.common.Carrier` in my program but still ReparingTask was using it.

Thanks for your help.
