### ISSUE TITLE
JavaXCacheDependencyClientTest.createHazelcastInstance

### ISSUE THREAD

**Issue by tezc** [hazelcast/hazelcast#14178]
_master_ (commit ddc5d0f8df8d1d3aac02f5e3caf40be9ff0253ae)

Failed on nightly build : https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/285/testReport/junit/classloading/JavaXCacheDependencyClientTest/createHazelcastInstance/

Stacktrace : 

```
java.lang.AssertionError: Application created a ThreadLocal with key of type [com.hazelcast.client.spi.impl.ClientResponseHandlerSupplier$1] (value [com.hazelcast.client.spi.impl.ClientResponseHandlerSupplier$1@2bcb3313]) and a value of type [com.hazelcast.util.MutableInteger] (value [com.hazelcast.util.MutableInteger@2725e0bf) but failed to remove it when the application was stopped.
	at org.junit.Assert.fail(Assert.java:88)
	at classloading.ThreadLocalLeakTestUtils.checkThreadLocalMapForLeaks(ThreadLocalLeakTestUtils.java:173)
	at classloading.ThreadLocalLeakTestUtils.checkThreadLocalsForLeaks(ThreadLocalLeakTestUtils.java:71)
	at classloading.AbstractJavaXCacheDependencyTest.createHazelcastInstance(AbstractJavaXCacheDependencyTest.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by vbekiaris** [comment]
The `ThreadLocal` reported in the test failure is added to `NioThread`s by `ClientResponseHandlerSupplier$AsyncMultiThreadedResponseHandler`. `NioThread`s are properly interrupted but not joined in `NioNetworking#shutdown` to avoid delay during shutdown, so it may be the case `hz.shutdown` returns before the `NioThread`s are joined (even though eventually they will). In this case, the test's thread local assertions are executed before all `NioThread`s are joined -> test fails.

Since this failure seems rather rare and to avoid introducing delay during shutdown, I suggest we add more info (including the above explanation about this known issue) to the test failure message (see PR #14258). If the failure occurs frequently, we can consider adding a wait for `NioThread`s to join in `NioNetworking#shutdown`, sounds good @Holmistr @tezc ?

**Comment by Holmistr** [comment]
@vbekiaris Sounds good to me. Let's do it this way. Thanks for looking into it!
