### ISSUE TITLE
MemcacheTest.testPrepend

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#14204]
_master_ (commit aab4960ef82ebb7cf29146a68f2a07b65fec1853)

Failed on IbmJDK8: https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK8/45/testReport/com.hazelcast.internal.ascii/MemcacheTest/testPrepend/

Stacktrace:
```
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1453)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1477)
	at sun.nio.ch.SelectorImpl.implCloseSelector(SelectorImpl.java:124)
	at java.nio.channels.spi.AbstractSelector.close(AbstractSelector.java:122)
	at net.spy.memcached.MemcachedConnection.shutdown(MemcachedConnection.java:1339)
	at net.spy.memcached.MemcachedClient.shutdown(MemcachedClient.java:2512)
	at net.spy.memcached.MemcachedClient.shutdown(MemcachedClient.java:2474)
	at com.hazelcast.internal.ascii.MemcacheTest.tearDown(MemcacheTest.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:402)
	at com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37)
	at com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:104)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at com.hazelcast.test.HazelcastParallelClassRunner.access$301(HazelcastParallelClassRunner.java:49)
	at com.hazelcast.test.HazelcastParallelClassRunner$TestRunner.run(HazelcastParallelClassRunner.java:162)
	at java.lang.Thread.run(Thread.java:811)
```

Standard output:
```
Hiccups measured while running test 'testPrepend(com.hazelcast.internal.ascii.MemcacheTest):'
05:21:05, accumulated pauses: 48 ms, max pause: 29 ms, pauses over 1000 ms: 0
```

**Comment by tezc** [comment]
Looks like same with https://github.com/hazelcast/hazelcast/issues/14048

**Comment by olukas** [comment]
You are right guys, this is my fault. Closing this issue. I am not sure whether we have any reasonable option with issues like this now. It is mentioned in our document with know issues. Probably most reasonable idea for now is just to be more careful in in reporting issues.

**Comment by tezc** [comment]
Memcached client has a race condition, selector.close() is called from application thread while connection thread is iterating on Selector keys, as a result CME is thrown.

We decided to ignore ConcurrentModificationException on MemcachedConnection.shutdown().
