### ISSUE TITLE
java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer

### ISSUE THREAD

**Issue by ahmetmircik** [hazelcast/hazelcast#14214]
```
java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
        at com.hazelcast.internal.networking.OutboundHandler.initDstBuffer(OutboundHandler.java:120)
        at com.hazelcast.internal.networking.OutboundHandler.initDstBuffer(OutboundHandler.java:95)
        at com.hazelcast.nio.tcp.ProtocolEncoder.handlerAdded(ProtocolEncoder.java:64)
        at com.hazelcast.internal.networking.nio.NioOutboundPipeline.addLast(NioOutboundPipeline.java:322)
        at com.hazelcast.nio.tcp.PlainChannelInitializer.initChannel(PlainChannelInitializer.java:67)
        at com.hazelcast.internal.networking.nio.NioChannel.start(NioChannel.java:105)
        at com.hazelcast.nio.tcp.TcpIpConnectionManager.newConnection(TcpIpConnectionManager.java:386)
        at com.hazelcast.nio.tcp.TcpIpAcceptor$AcceptorIOThread.configureAndAssignSocket(TcpIpAcceptor.java:292)
        at com.hazelcast.nio.tcp.TcpIpAcceptor$AcceptorIOThread.acceptSocket(TcpIpAcceptor.java:284)
        at com.hazelcast.nio.tcp.TcpIpAcceptor$AcceptorIOThread.handleSelectionKeys(TcpIpAcceptor.java:220)
        at com.hazelcast.nio.tcp.TcpIpAcceptor$AcceptorIOThread.acceptLoop(TcpIpAcceptor.java:172)
        at com.hazelcast.nio.tcp.TcpIpAcceptor$AcceptorIOThread.run(TcpIpAcceptor.java:150)

```
JDK9 breaks compatibility with older versions for `ByteBuffer.flip()` by returning `ByteBuffer` instead of `Buffer`. Compiled code with target 1.6 causes this exception.

This casting can be a solution: `((Buffer) buffer).flip();`

**Comment by jerrinot** [comment]
It sounds like it could be a nice addition into animal-sniffer?
There there is a similar situation with CHM - I believe the `keySet()` methods returns a subclass of what it used to return.
