### ISSUE TITLE
AnswerTest.testPartitionService

### ISSUE THREAD

**Issue by tezc** [hazelcast/hazelcast#14320]
_master_ (commit a31d0df545758b469189b9d57152fd97f2cd1c18)

Failed on nightly build : https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-nightly/311/testReport/com.hazelcast.test.starter.answer.test/AnswerTest/testPartitionService/

Stacktrace : 

```
java.lang.NoSuchFieldError: 
Field localReplica does not exist on object Partition [0]{
}
	at com.hazelcast.test.starter.ReflectionUtils.getFieldValueReflectively(ReflectionUtils.java:140)
	at com.hazelcast.test.starter.constructor.InternalPartitionImplConstructor.createNew0(InternalPartitionImplConstructor.java:47)
	at com.hazelcast.test.starter.constructor.AbstractStarterObjectConstructor.createNew(AbstractStarterObjectConstructor.java:45)
	at com.hazelcast.test.starter.HazelcastProxyFactory.construct(HazelcastProxyFactory.java:316)
	at com.hazelcast.test.starter.HazelcastProxyFactory.constructWithoutProxy(HazelcastProxyFactory.java:276)
	at com.hazelcast.test.starter.HazelcastProxyFactory.proxyObjectForStarter(HazelcastProxyFactory.java:191)
	at com.hazelcast.test.starter.HazelcastProxyFactory.toArray(HazelcastProxyFactory.java:340)
	at com.hazelcast.test.starter.HazelcastProxyFactory.proxyObjectForStarter(HazelcastProxyFactory.java:177)
	at com.hazelcast.test.starter.answer.AbstractAnswer.invoke(AbstractAnswer.java:266)
	at com.hazelcast.test.starter.answer.AbstractAnswer.invoke(AbstractAnswer.java:222)
	at com.hazelcast.test.starter.answer.AbstractAnswer.invoke(AbstractAnswer.java:171)
	at com.hazelcast.test.starter.answer.PartitionServiceAnswer.answer(PartitionServiceAnswer.java:41)
	at com.hazelcast.test.starter.answer.AbstractAnswer.answer(AbstractAnswer.java:98)
	at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:104)
	at org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29)
	at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:35)
	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:63)
	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:49)
	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor$DispatcherDefaultingToRealMethod.interceptAbstract(MockMethodInterceptor.java:128)
	at com.hazelcast.internal.partition.InternalPartitionService$MockitoMock$1213416615.getPartitions(Unknown Source)
	at com.hazelcast.test.starter.answer.test.AnswerTest.testPartitionService(AnswerTest.java:189)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Holmistr** [comment]
*master* (commit 33082885b9b021e53bfabd4bf1589f21dec97d52)

This has started to fail constantly after update to 3.13-SNAPSHOT. Easily reproducible locally.

Stacktrace:
```
[INFO] Running com.hazelcast.test.starter.answer.test.AnswerTest
[ERROR] Tests run: 11, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 41.654 s <<< FAILURE! - in com.hazelcast.test.starter.answer.test.AnswerTest
[ERROR] testPartitionService(com.hazelcast.test.starter.answer.test.AnswerTest)  Time elapsed: 2.466 s  <<< ERROR!
java.lang.IllegalArgumentException: argument type mismatch
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at com.hazelcast.test.starter.constructor.InternalPartitionImplConstructor.createNew0(InternalPartitionImplConstructor.java:59)
	at com.hazelcast.test.starter.constructor.AbstractStarterObjectConstructor.createNew(AbstractStarterObjectConstructor.java:45)
	at com.hazelcast.test.starter.HazelcastProxyFactory.construct(HazelcastProxyFactory.java:316)
	at com.hazelcast.test.starter.HazelcastProxyFactory.constructWithoutProxy(HazelcastProxyFactory.java:276)
	at com.hazelcast.test.starter.HazelcastProxyFactory.proxyObjectForStarter(HazelcastProxyFactory.java:191)
	at com.hazelcast.test.starter.HazelcastProxyFactory.toArray(HazelcastProxyFactory.java:340)
	at com.hazelcast.test.starter.HazelcastProxyFactory.proxyObjectForStarter(HazelcastProxyFactory.java:177)
	at com.hazelcast.test.starter.answer.AbstractAnswer.invoke(AbstractAnswer.java:266)
	at com.hazelcast.test.starter.answer.AbstractAnswer.invoke(AbstractAnswer.java:222)
	at com.hazelcast.test.starter.answer.AbstractAnswer.invoke(AbstractAnswer.java:171)
	at com.hazelcast.test.starter.answer.PartitionServiceAnswer.answer(PartitionServiceAnswer.java:41)
	at com.hazelcast.test.starter.answer.AbstractAnswer.answer(AbstractAnswer.java:98)
	at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:104)
	at org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29)
	at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:35)
	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:63)
	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:49)
	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor$DispatcherDefaultingToRealMethod.interceptAbstract(MockMethodInterceptor.java:128)
	at com.hazelcast.internal.partition.InternalPartitionService$MockitoMock$1051967996.getPartitions(Unknown Source)
	at com.hazelcast.test.starter.answer.test.AnswerTest.testPartitionService(AnswerTest.java:189)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
```
