### ISSUE TITLE
The hazelcast client connect failed after hazelcast cluster restart in version 3.11

### ISSUE THREAD

**Issue by Jiangew** [hazelcast/hazelcast#14325]
```
java.util.concurrent.ExecutionException: com.hazelcast.client.HazelcastClientNotActiveException: Client is shutting down
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:109)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:33)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:178)
	at com.hazelcast.client.util.ClientDelegatingFuture.get(ClientDelegatingFuture.java:139)
	at com.hazelcast.client.util.ClientDelegatingFuture.get(ClientDelegatingFuture.java:130)
	at com.xxx.xxx.account.service.hazelcast.HazelcastExecutor.submit(HazelcastExecutor.java:18)
	at com.xxx.xxx.account.service.SubaccountHazelcastEventListener.onSubaccountUpdated(SubaccountHazelcastEventListener.java:69)
	at com.xxx.account.service.AccountService.publishAccountsUpdated(AccountService.java:382)
	at com.xxx.account.service.AccountService.transfer(AccountService.java:147)
	at com.xxx.account.service.AccountService$$FastClassBySpringCGLIB$$6ae95734.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:652)
	at com.xxx.account.service.AccountService$$EnhancerBySpringCGLIB$$b5fc1c91.transfer(<generated>)
	at com.xxx.clearing.service.ClearingTransferSupport.transfer(ClearingTransferSupport.java:120)
	at com.xxx.clearing.service.ClearingTransferService.updateClearingTransfer(ClearingTransferService.java:326)
	at com.xxx.clearing.service.ClearingTransferService.lambda$asyncUpdateClearingTransfer$1(ClearingTransferService.java:175)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.hazelcast.client.HazelcastClientNotActiveException: Client is shutting down
	at com.hazelcast.client.spi.impl.ClientInvocation.notifyException(ClientInvocation.java:215)
	at com.hazelcast.client.spi.impl.ClientInvocation.invokeOnSelection(ClientInvocation.java:173)
	at com.hazelcast.client.spi.impl.ClientInvocation.invoke(ClientInvocation.java:146)
	at com.hazelcast.client.proxy.ClientExecutorServiceProxy.invokeOnPartitionOwner(ClientExecutorServiceProxy.java:632)
	at com.hazelcast.client.proxy.ClientExecutorServiceProxy.submitToKeyOwnerInternal(ClientExecutorServiceProxy.java:430)
	at com.hazelcast.client.proxy.ClientExecutorServiceProxy.submitToKeyOwner(ClientExecutorServiceProxy.java:324)
	at com.xxx.xxx.account.service.hazelcast.HazelcastExecutor.submit(HazelcastExecutor.java:17)
	at com.xxx.xxx.account.service.SubaccountHazelcastEventListener.onSubaccountUpdated(SubaccountHazelcastEventListener.java:69)
	at com.xxx.account.service.AccountService.publishAccountsUpdated(AccountService.java:382)
	at com.xxx.account.service.AccountService.transfer(AccountService.java:147)
	at com.xxx.account.service.AccountService$$FastClassBySpringCGLIB$$6ae95734.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:652)
	at com.xxx.account.service.AccountService$$EnhancerBySpringCGLIB$$b5fc1c91.transfer(<generated>)
	at com.xxx.clearing.service.ClearingTransferSupport.transfer(ClearingTransferSupport.java:120)
	at com.xxx.clearing.service.ClearingTransferService.updateClearingTransfer(ClearingTransferService.java:326)
	at com.xxx.clearing.service.ClearingTransferService.lambda$asyncUpdateClearingTransfer$1(ClearingTransferService.java:175)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:96)
	... 18 common frames omitted
```

**Comment by sancar** [comment]
Hazelcast client can decide to shut down after trying to connect to the cluster. Attempt count and period can be configured. See the following link for details. 
https://docs.hazelcast.org/docs/3.11.1/manual/html-single/index.html#handling-failures

**Comment by sancar** [comment]
Hi @Jiangew , I am closing the issue for now. If you need further answers, please use our google group, because it looks like a usage issue rather than a bug. We can always open an issue when we found a bug.

https://groups.google.com/forum/#!forum/hazelcast
Regards.

**Comment by Jiangew** [comment]
@sancar OK, Thanks.
