### ISSUE TITLE
unable to connect devicehive-backend to postgre database hazelcats client unable to connect

### ISSUE THREAD

**Issue by MahmodulHasan** [hazelcast/hazelcast#14341]
```
2019-01-06 11:17:59.824 [main] INFO   c.d.a.DeviceHiveBackendApplication - Starting DeviceHiveBackendApplication v3.5.0
on DESKTOP-E4EARF9 with PID 4336 (C:\devicehive-java-server-master\devicehive-backend\target\devicehive-backend-3.5.0-bo
ot.jar started by HASAN in C:\Users\HASAN)
2019-01-06 11:17:59.832 [main] INFO   c.d.a.DeviceHiveBackendApplication - The following profiles are active: ws-kafka-p
roxy-backend
2019-01-06 11:17:59.903 [main] INFO   o.s.c.a.AnnotationConfigApplicationContext - Refreshing org.springframework.contex
t.annotation.AnnotationConfigApplicationContext@1a77460: startup date [Sun Jan 06 11:17:59 BDT 2019]; root of context hi
erarchy
2019-01-06 11:18:00.350 [background-preinit] INFO   o.h.validator.internal.util.Version - HV000001: Hibernate Validator
5.3.5.Final
2019-01-06 11:18:01.683 [main] INFO   o.s.b.f.a.AutowiredAnnotationBeanPostProcessor - JSR-330 'javax.inject.Inject' ann
otation found and supported for autowiring
2019-01-06 11:18:02.989 [main] INFO   o.f.c.internal.util.VersionPrinter - Flyway 3.2.1 by Boxfuse
2019-01-06 11:18:03.466 [main] INFO   o.f.c.i.dbsupport.DbSupportFactory - Database: jdbc:postgresql://127.0.0.1:5432/de
vicehive (PostgreSQL 10.6)
2019-01-06 11:18:03.675 [main] INFO   o.f.core.internal.command.DbValidate - Validated 38 migrations (execution time 00:
00.116s)
2019-01-06 11:18:03.714 [main] INFO   o.f.core.internal.command.DbMigrate - Current version of schema "public": 3.4.11
2019-01-06 11:18:03.715 [main] INFO   o.f.core.internal.command.DbMigrate - Schema "public" is up to date. No migration
necessary.
2019-01-06 11:18:04.146 [main] INFO   o.s.o.j.LocalContainerEntityManagerFactoryBean - Building JPA container EntityMana
gerFactory for persistence unit 'default'
2019-01-06 11:18:04.186 [main] INFO   o.h.jpa.internal.util.LogHelper - HHH000204: Processing PersistenceUnitInfo [
        name: default
        ...]
2019-01-06 11:18:04.408 [main] INFO   org.hibernate.Version - HHH000412: Hibernate Core {5.2.11.Final}
2019-01-06 11:18:04.412 [main] INFO   org.hibernate.cfg.Environment - HHH000206: hibernate.properties not found
2019-01-06 11:18:04.545 [main] INFO   o.h.annotations.common.Version - HCANN000001: Hibernate Commons Annotations {5.0.1
.Final}
2019-01-06 11:18:05.094 [main] INFO   org.hibernate.dialect.Dialect - HHH000400: Using dialect: org.hibernate.dialect.Po
stgreSQL9Dialect
2019-01-06 11:18:05.328 [main] INFO   org.hibernate.type.BasicTypeRegistry - HHH000270: Type registration [java.util.UUI
D] overrides previous : org.hibernate.type.UUIDBinaryType@b6ffe0
2019-01-06 11:18:06.145 [main] INFO   c.h.h.HazelcastLocalCacheRegionFactory - Starting up HazelcastLocalCacheRegionFact
ory
2019-01-06 11:18:06.299 [main] INFO   com.hazelcast.core.LifecycleService - hz.client_0 [dev] [3.8.1] HazelcastClient 3.
8.1 (20170411 - f1e9264) is STARTING
2019-01-06 11:18:07.426 [main] INFO   com.hazelcast.core.LifecycleService - hz.client_0 [dev] [3.8.1] HazelcastClient 3.
8.1 (20170411 - f1e9264) is STARTED
2019-01-06 11:18:07.503 [main] INFO   c.h.c.s.impl.ClusterListenerSupport - hz.client_0 [dev] [3.8.1] Trying to connect
to [127.0.0.1]:5701 as owner member
2019-01-06 11:18:08.611 [main] WARN   c.h.c.s.impl.ClusterListenerSupport - hz.client_0 [dev] [3.8.1] Unable to get aliv
e cluster connection, try in 1885 ms later, attempt 1 of 10.
2019-01-06 11:18:10.497 [main] INFO   c.h.c.s.impl.ClusterListenerSupport - hz.client_0 [dev] [3.8.1] Trying to connect
to [127.0.0.1]:5701 as owner member
2019-01-06 11:18:11.585 [main] WARN   c.h.c.s.impl.ClusterListenerSupport - hz.client_0 [dev] [3.8.1] Unable to get aliv
e cluster connection, try in 1912 ms later, attempt 2 of 10.
2019-01-06 11:18:13.498 [main] INFO   c.h.c.s.impl.ClusterListenerSupport - hz.client_0 [dev] [3.8.1] Trying to connect
to [127.0.0.1]:5701 as owner member
2019-01-06 11:18:14.499 [main] WARN   c.h.c.s.impl.ClusterListenerSupport - hz.client_0 [dev] [3.8.1] Unable to get aliv
e cluster connection, try in 1999 ms later, attempt 3 of 10.
2019-01-06 11:18:16.499 [main] INFO   c.h.c.s.impl.ClusterListenerSupport - hz.client_0 [dev] [3.8.1] Trying to connect
to [127.0.0.1]:5701 as owner member
2019-01-06 11:18:17.500 [main] WARN   c.h.c.s.impl.ClusterListenerSupport - hz.client_0 [dev] [3.8.1] Unable to get aliv
e cluster connection, try in 1999 ms later, attempt 4 of 10.
2019-01-06 11:18:19.500 [main] INFO   c.h.c.s.impl.ClusterListenerSupport - hz.client_0 [dev] [3.8.1] Trying to connect
to [127.0.0.1]:5701 as owner member
2019-01-06 11:18:20.509 [main] WARN   c.h.c.s.impl.ClusterListenerSupport - hz.client_0 [dev] [3.8.1] Unable to get aliv
e cluster connection, try in 1991 ms later, attempt 5 of 10.
2019-01-06 11:18:22.501 [main] INFO   c.h.c.s.impl.ClusterListenerSupport - hz.client_0 [dev] [3.8.1] Trying to connect
to [127.0.0.1]:5701 as owner member
2019-01-06 11:18:23.696 [main] WARN   c.h.c.s.impl.ClusterListenerSupport - hz.client_0 [dev] [3.8.1] Unable to get aliv
e cluster connection, try in 1805 ms later, attempt 6 of 10.
2019-01-06 11:18:25.502 [main] INFO   c.h.c.s.impl.ClusterListenerSupport - hz.client_0 [dev] [3.8.1] Trying to connect
to [127.0.0.1]:5701 as owner member
2019-01-06 11:18:26.696 [main] WARN   c.h.c.s.impl.ClusterListenerSupport - hz.client_0 [dev] [3.8.1] Unable to get aliv
e cluster connection, try in 1806 ms later, attempt 7 of 10.
2019-01-06 11:18:28.503 [main] INFO   c.h.c.s.impl.ClusterListenerSupport - hz.client_0 [dev] [3.8.1] Trying to connect
to [127.0.0.1]:5701 as owner member
2019-01-06 11:18:29.509 [main] WARN   c.h.c.s.impl.ClusterListenerSupport - hz.client_0 [dev] [3.8.1] Unable to get aliv
e cluster connection, try in 1994 ms later, attempt 8 of 10.
2019-01-06 11:18:31.504 [main] INFO   c.h.c.s.impl.ClusterListenerSupport - hz.client_0 [dev] [3.8.1] Trying to connect
to [127.0.0.1]:5701 as owner member
2019-01-06 11:18:32.505 [main] WARN   c.h.c.s.impl.ClusterListenerSupport - hz.client_0 [dev] [3.8.1] Unable to get aliv
e cluster connection, try in 1999 ms later, attempt 9 of 10.
2019-01-06 11:18:34.505 [main] INFO   c.h.c.s.impl.ClusterListenerSupport - hz.client_0 [dev] [3.8.1] Trying to connect
to [127.0.0.1]:5701 as owner member
2019-01-06 11:18:35.506 [main] WARN   c.h.c.s.impl.ClusterListenerSupport - hz.client_0 [dev] [3.8.1] Unable to get aliv
e cluster connection, try in 1999 ms later, attempt 10 of 10.
2019-01-06 11:18:37.506 [main] INFO   com.hazelcast.core.LifecycleService - hz.client_0 [dev] [3.8.1] HazelcastClient 3.
8.1 (20170411 - f1e9264) is SHUTTING_DOWN
2019-01-06 11:18:37.510 [main] INFO   com.hazelcast.core.LifecycleService - hz.client_0 [dev] [3.8.1] HazelcastClient 3.
8.1 (20170411 - f1e9264) is SHUTDOWN
2019-01-06 11:18:37.511 [main] WARN   o.s.c.a.AnnotationConfigApplicationContext - Exception encountered during context
initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bea
n with name 'entityManagerFactory' defined in class path resource [com/devicehive/application/RdbmsPersistenceConfig.cla
ss]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: def
ault] Unable to build Hibernate SessionFactory
2019-01-06 11:18:37.525 [main] INFO   o.s.b.a.l.AutoConfigurationReportLoggingInitializer -

Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled
.
2019-01-06 11:18:37.545 [main] ERROR  o.s.boot.SpringApplication - Application startup failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in
 class path resource [com/devicehive/application/RdbmsPersistenceConfig.class]: Invocation of init method failed; nested
 exception is javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactor
y
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireC
apableBeanFactory.java:1628) ~[spring-beans-4.3.11.RELEASE.jar!/:4.3.11.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCap
ableBeanFactory.java:555) ~[spring-beans-4.3.11.RELEASE.jar!/:4.3.11.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapab
leBeanFactory.java:483) ~[spring-beans-4.3.11.RELEASE.jar!/:4.3.11.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spr
ing-beans-4.3.11.RELEASE.jar!/:4.3.11.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegis
try.java:230) ~[spring-beans-4.3.11.RELEASE.jar!/:4.3.11.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[sprin
g-beans-4.3.11.RELEASE.jar!/:4.3.11.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-
beans-4.3.11.RELEASE.jar!/:4.3.11.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1078)
~[spring-context-4.3.11.RELEASE.jar!/:4.3.11.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplic
ationContext.java:857) ~[spring-context-4.3.11.RELEASE.jar!/:4.3.11.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543) ~
[spring-context-4.3.11.RELEASE.jar!/:4.3.11.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) ~[spring-boot-1.5.7.RELEASE.ja
r!/:1.5.7.RELEASE]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360) ~[spring-boot-1.5.7.REL
EASE.jar!/:1.5.7.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) ~[spring-boot-1.5.7.RELEASE.jar!/:
1.5.7.RELEASE]
        at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134) [spring-boot
-1.5.7.RELEASE.jar!/:1.5.7.RELEASE]
        at com.devicehive.application.DeviceHiveBackendApplication.main(DeviceHiveBackendApplication.java:37) [classes!/
:3.5.0]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_191]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_191]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_191]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_191]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [devicehive-backend-3.5.0-boot
.jar:3.5.0]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [devicehive-backend-3.5.0-boot.jar:3.5.0]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [devicehive-backend-3.5.0-boot.jar:3.5.0]
        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:587) [devicehive-backend-3.5.
0-boot.jar:3.5.0]
Caused by: javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.persistenceException(EntityManagerFactoryBuil
derImpl.java:967) ~[hibernate-core-5.2.11.Final.jar!/:5.2.11.Final]
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:89
2) ~[hibernate-core-5.2.11.Final.jar!/:5.2.11.Final]
        at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(
SpringHibernateJpaPersistenceProvider.java:60) ~[spring-orm-4.3.11.RELEASE.jar!/:4.3.11.RELEASE]
        at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalCont
ainerEntityManagerFactoryBean.java:353) ~[spring-orm-4.3.11.RELEASE.jar!/:4.3.11.RELEASE]
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityMa
nagerFactoryBean.java:370) ~[spring-orm-4.3.11.RELEASE.jar!/:4.3.11.RELEASE]
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryB
ean.java:359) ~[spring-orm-4.3.11.RELEASE.jar!/:4.3.11.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowi
reCapableBeanFactory.java:1687) ~[spring-beans-4.3.11.RELEASE.jar!/:4.3.11.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireC
apableBeanFactory.java:1624) ~[spring-beans-4.3.11.RELEASE.jar!/:4.3.11.RELEASE]
        ... 22 common frames omitted
Caused by: org.hibernate.service.spi.ServiceException: Unable to create requested service [org.hibernate.engine.spi.Cach
eImplementor]
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:271
) ~[hibernate-core-5.2.11.Final.jar!/:5.2.11.Final]
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java
:233) ~[hibernate-core-5.2.11.Final.jar!/:5.2.11.Final]
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:210) ~
[hibernate-core-5.2.11.Final.jar!/:5.2.11.Final]
        at org.hibernate.service.internal.SessionFactoryServiceRegistryImpl.getService(SessionFactoryServiceRegistryImpl
.java:80) ~[hibernate-core-5.2.11.Final.jar!/:5.2.11.Final]
        at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:244) ~[hibernate-core-5.2.11.Final.j
ar!/:5.2.11.Final]
        at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:452) ~[hibernate-c
ore-5.2.11.Final.jar!/:5.2.11.Final]
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:88
9) ~[hibernate-core-5.2.11.Final.jar!/:5.2.11.Final]
        ... 28 common frames omitted
Caused by: java.lang.IllegalStateException: Unable to connect to any address in the config! The following addresses were
 tried: [/127.0.0.1:5701]
        at com.hazelcast.client.spi.impl.ClusterListenerSupport.connectToCluster(ClusterListenerSupport.java:180) ~[haze
lcast-client-3.8.1.jar!/:3.8.1]
        at com.hazelcast.client.spi.impl.ClientClusterServiceImpl.start(ClientClusterServiceImpl.java:189) ~[hazelcast-c
lient-3.8.1.jar!/:3.8.1]
        at com.hazelcast.client.impl.HazelcastClientInstanceImpl.start(HazelcastClientInstanceImpl.java:407) ~[hazelcast
-client-3.8.1.jar!/:3.8.1]
        at com.hazelcast.client.HazelcastClientManager.newHazelcastClient(HazelcastClientManager.java:78) ~[hazelcast-cl
ient-3.8.1.jar!/:3.8.1]
        at com.hazelcast.client.HazelcastClient.newHazelcastClient(HazelcastClient.java:72) ~[hazelcast-client-3.8.1.jar
!/:3.8.1]
        at com.hazelcast.hibernate.instance.HazelcastClientLoader.loadInstance(HazelcastClientLoader.java:88) ~[hazelcas
t-hibernate52-1.2.2.jar!/:1.2.2]
        at com.hazelcast.hibernate.AbstractHazelcastCacheRegionFactory.start(AbstractHazelcastCacheRegionFactory.java:97
) ~[hazelcast-hibernate52-1.2.2.jar!/:1.2.2]
        at org.hibernate.cache.spi.RegionFactory.start(RegionFactory.java:63) ~[hibernate-core-5.2.11.Final.jar!/:5.2.11
.Final]
        at org.hibernate.internal.CacheImpl.<init>(CacheImpl.java:71) ~[hibernate-core-5.2.11.Final.jar!/:5.2.11.Final]
        at org.hibernate.engine.spi.CacheInitiator.initiateService(CacheInitiator.java:28) ~[hibernate-core-5.2.11.Final
.jar!/:5.2.11.Final]
        at org.hibernate.engine.spi.CacheInitiator.initiateService(CacheInitiator.java:20) ~[hibernate-core-5.2.11.Final
.jar!/:5.2.11.Final]
        at org.hibernate.service.internal.SessionFactoryServiceRegistryImpl.initiateService(SessionFactoryServiceRegistr
yImpl.java:59) ~[hibernate-core-5.2.11.Final.jar!/:5.2.11.Final]
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:259
) ~[hibernate-core-5.2.11.Final.jar!/:5.2.11.Final]
        ... 34 common frames omitted
```

**Comment by gokhanoner** [comment]
@MahmodulHasan problem here is `hazelcast-hibernate` module tries to start as client & fails to connect to a Hazelcast cluster after 10 connection attempts. You need to make sure that Hazelcast cluster up & running and accessible from your application.
