### ISSUE TITLE
LockAdvancedTest.testCleanupOperationIgnoresQuorum

### ISSUE THREAD

**Issue by tezc** [hazelcast/hazelcast#14350]
_master_ (commit 8b0a17f574591f61440d9ac8a2b37f0f3977aa09)

Failed on ZuluJDK10 : https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-ZuluJDK10/43/testReport/com.hazelcast.concurrent.lock/LockAdvancedTest/testCleanupOperationIgnoresQuorum/

**Stacktrace**
```
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at org.junit.Assert.assertFalse(Assert.java:74)
	at com.hazelcast.concurrent.lock.LockAdvancedTest.testCleanupOperationIgnoresQuorum(LockAdvancedTest.java:89)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

**Standard Output**
```
Hiccups measured while running test 'testCleanupOperationIgnoresQuorum(com.hazelcast.concurrent.lock.LockAdvancedTest):'
06:24:00, accumulated pauses: 1576 ms, max pause: 999 ms, pauses over 1000 ms: 0
```

**Comment by tezc** [comment]
http://jenkins.hazelcast.com/job/Hazelcast-3.x-OracleJDK10/1/testReport/com.hazelcast.concurrent.lock/LockAdvancedTest/testCleanupOperationIgnoresQuorum/

Failing on multiple builds.
