### ISSUE TITLE
UndefinedErrorCodeException Class name: com.hazelcast.cp.exception.NotLeaderException, Message: null is not LEADER

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#14433]
```
com.hazelcast.client.UndefinedErrorCodeException: Class name: com.hazelcast.cp.exception.NotLeaderException, Message: null is not LEADER of CPGroupId{name='METADATA', seed=0, commitIndex=0}. Known leader is: N/A
	at com.hazelcast.cp.internal.operation.RaftReplicateOp.run(RaftReplicateOp.java:62)
	at com.hazelcast.spi.Operation.call(Operation.java:170)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:210)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:199)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:416)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:153)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:123)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:110)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:126)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:79)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:162)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.get(InvocationFuture.java:177)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.join(AbstractInvocationFuture.java:143)
	at com.hazelcast.cp.internal.RaftService.getGroupIdForProxy(RaftService.java:727)
	at com.hazelcast.cp.internal.RaftService.createRaftGroupForProxy(RaftService.java:710)
	at com.hazelcast.cp.internal.datastructures.spi.client.CreateRaftGroupMessageTask.processMessage(CreateRaftGroupMessageTask.java:41)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:123)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.doRun(AbstractMessageTask.java:111)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:101)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:96)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:33)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:162)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.join(AbstractInvocationFuture.java:143)
	at com.hazelcast.client.cp.internal.datastructures.atomiclong.RaftAtomicLongProxyFactory.create(RaftAtomicLongProxyFactory.java:47)
	at com.hazelcast.client.spi.ProxyManager.createClientProxy(ProxyManager.java:401)
	at com.hazelcast.client.spi.ProxyManager.getOrCreateProxy(ProxyManager.java:331)
	at com.hazelcast.client.impl.clientside.HazelcastClientInstanceImpl.getDistributedObject(HazelcastClientInstanceImpl.java:880)
	at com.hazelcast.client.impl.clientside.CPSubsystemImpl.getAtomicLong(CPSubsystemImpl.java:49)
```

**Comment by mdogan** [comment]
Updated the PR (https://github.com/hazelcast/hazelcast/pull/14429) to throw original exceptions (`CannotReplicateException`, `NotLeaderException` etc) on the client.

**Comment by Danny-Hazelcast** [comment]
@mdogan is still go
```
com.hazelcast.client.UndefinedErrorCodeException: Class name: com.hazelcast.cp.exception.NotLeaderException, Message: null is not LEADER of CPGroupId{name='default', seed=0, commitIndex=12}. Known leader is: N/A
	at com.hazelcast.cp.internal.operation.RaftReplicateOp.run(RaftReplicateOp.java:62)
	at com.hazelcast.spi.Operation.call(Operation.java:170)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:210)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:199)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:416)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:153)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:123)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:110)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:126)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run(AbstractInvocationFuture.java:250)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:96)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:33)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:190)
	at com.hazelcast.client.util.ClientDelegatingFuture.get(ClientDelegatingFuture.java:125)
	at com.hazelcast.client.util.ClientDelegatingFuture.get(ClientDelegatingFuture.java:116)
	at com.hazelcast.client.util.ClientDelegatingFuture.join(ClientDelegatingFuture.java:132)
	at com.hazelcast.client.cp.internal.datastructures.atomiclong.RaftAtomicLongProxy.get(RaftAtomicLongProxy.java:127)
	at hzcmd.cp.ilong.Cas.timeStep(Cas.java:17)
```

**Comment by Danny-Hazelcast** [comment]
still get 
```
com.hazelcast.client.UndefinedErrorCodeException: Class name: com.hazelcast.cp.exception.NotLeaderException, Message: CPMember{uuid=7f7970ed-25dd-400b-89eb-2ff33730435e, address=[10.0.0.85]:5701} is not LEADER of CPGroupId{name='default', seed=0, commitIndex=10}. Known leader is: CPMember{uuid=b8da81ee-c29d-4a9d-b46d-290d7d2a4b03, address=[10.0.0.218]:5701}
	at com.hazelcast.cp.internal.raft.impl.task.ReplicateTask.run(ReplicateTask.java:67)
	at com.hazelcast.cp.internal.NodeEngineRaftIntegration.execute(NodeEngineRaftIntegration.java:95)
	at com.hazelcast.cp.internal.raft.impl.RaftNodeImpl.replicate(RaftNodeImpl.java:252)
	at com.hazelcast.cp.internal.operation.RaftReplicateOp.replicate(RaftReplicateOp.java:76)
	at com.hazelcast.cp.internal.operation.RaftReplicateOp.run(RaftReplicateOp.java:67)
	at com.hazelcast.spi.Operation.call(Operation.java:170)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:210)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:199)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:416)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:153)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:123)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:110)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:126)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run(AbstractInvocationFuture.java:250)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:96)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:33)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:162)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.join(AbstractInvocationFuture.java:143)
	at com.hazelcast.client.cp.internal.datastructures.atomiclong.RaftAtomicLongProxy.onDestroy(RaftAtomicLongProxy.java:269)
	at com.hazelcast.client.spi.ClientProxy.destroyLocally(ClientProxy.java:160)
	at com.hazelcast.client.spi.ProxyManager.destroyProxy(ProxyManager.java:365)
	at com.hazelcast.client.spi.ClientProxy.destroy(ClientProxy.java:146)
	at hzcmd.cp.ilong.Destroy.timeStep(Destroy.java:9)
```

**Comment by Danny-Hazelcast** [comment]
a 2nd occurrence of this issue

```
com.hazelcast.client.UndefinedErrorCodeException: Class name: com.hazelcast.cp.exception.NotLeaderException, Message: CPMember{uuid=b927aa17-a4ce-4d54-9734-81e844e0c69a, address=[10.0.0.124]:5701} is not LEADER of CPGroupId{name='METADATA', seed=0, commitIndex=0}. Known leader is: CPMember{uuid=c10f0afa-7bd4-4222-800d-1cc422675deb, address=[10.0.0.88]:5701}
	at com.hazelcast.cp.internal.raft.impl.task.ReplicateTask.run(ReplicateTask.java:67)
	at com.hazelcast.cp.internal.NodeEngineRaftIntegration.execute(NodeEngineRaftIntegration.java:95)
	at com.hazelcast.cp.internal.raft.impl.RaftNodeImpl.replicate(RaftNodeImpl.java:252)
	at com.hazelcast.cp.internal.operation.RaftReplicateOp.replicate(RaftReplicateOp.java:76)
	at com.hazelcast.cp.internal.operation.RaftReplicateOp.run(RaftReplicateOp.java:67)
	at com.hazelcast.spi.Operation.call(Operation.java:170)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:210)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:199)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:416)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:153)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:123)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:110)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:126)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:79)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:162)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.get(InvocationFuture.java:177)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.join(AbstractInvocationFuture.java:143)
	at com.hazelcast.cp.internal.RaftService.getGroupIdForProxy(RaftService.java:725)
	at com.hazelcast.cp.internal.RaftService.createRaftGroupForProxy(RaftService.java:708)
	at com.hazelcast.cp.internal.datastructures.atomicref.RaftAtomicRefService.createDistributedObject(RaftAtomicRefService.java:159)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyRegistry.doCreateProxy(ProxyRegistry.java:216)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyRegistry.createProxy(ProxyRegistry.java:209)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyServiceImpl.initializeDistributedObject(ProxyServiceImpl.java:133)
	at com.hazelcast.spi.impl.proxyservice.impl.operations.InitializeDistributedObjectOperation.run(InitializeDistributedObjectOperation.java:44)
	at com.hazelcast.spi.Operation.call(Operation.java:170)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:210)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:199)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:407)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:434)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:638)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:623)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:582)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:250)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:60)
	at com.hazelcast.client.impl.protocol.task.AbstractInvocationMessageTask.processMessage(AbstractInvocationMessageTask.java:40)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:123)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.doRun(AbstractMessageTask.java:111)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:101)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:126)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run(AbstractInvocationFuture.java:250)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:96)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:33)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:162)
	at com.hazelcast.client.spi.ProxyManager.initialize(ProxyManager.java:448)
	at com.hazelcast.client.spi.ProxyManager.initializeWithRetry(ProxyManager.java:411)
	at com.hazelcast.client.spi.ProxyManager.getOrCreateProxy(ProxyManager.java:332)
	at com.hazelcast.client.impl.clientside.HazelcastClientInstanceImpl.getDistributedObject(HazelcastClientInstanceImpl.java:880)
	at com.hazelcast.client.impl.clientside.CPSubsystemImpl.getAtomicReference(CPSubsystemImpl.java:54)
```

**Comment by Danny-Hazelcast** [comment]
i dont see UndefinedErrorCodeException any more, fixed
