### ISSUE TITLE
UndefinedErrorCodeException: Class name: com.hazelcast.cp.exception.CannotReplicateException

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#14430]
```
com.hazelcast.client.UndefinedErrorCodeException: Class name: com.hazelcast.cp.exception.CannotReplicateException, Message: Cannot replicate new operations for now
	at com.hazelcast.cp.internal.raft.impl.task.ReplicateTask.run(ReplicateTask.java:72)
	at com.hazelcast.cp.internal.NodeEngineRaftIntegration.execute(NodeEngineRaftIntegration.java:95)
	at com.hazelcast.cp.internal.raft.impl.RaftNodeImpl.replicate(RaftNodeImpl.java:239)
	at com.hazelcast.cp.internal.operation.RaftReplicateOp.replicate(RaftReplicateOp.java:76)
	at com.hazelcast.cp.internal.operation.RaftReplicateOp.run(RaftReplicateOp.java:67)
	at com.hazelcast.spi.Operation.call(Operation.java:170)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:210)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:199)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:416)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:153)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:123)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:110)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:126)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run(AbstractInvocationFuture.java:250)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:96)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:33)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:190)
	at com.hazelcast.client.util.ClientDelegatingFuture.get(ClientDelegatingFuture.java:125)
	at com.hazelcast.client.util.ClientDelegatingFuture.get(ClientDelegatingFuture.java:116)
	at com.hazelcast.client.util.ClientDelegatingFuture.join(ClientDelegatingFuture.java:132)
	at com.hazelcast.client.cp.internal.datastructures.atomiclong.RaftAtomicLongProxy.get(RaftAtomicLongProxy.java:127)
```

http://54.234.90.98/~jenkins/workspace/kill-x/3.12-SNAPSHOT/2019_01_29-15_07_00/long/output/HZ/HzClient1HZ/exception.txt

http://54.234.90.98/~jenkins/workspace/kill-x/3.12-SNAPSHOT/2019_01_29-15_07_00/long/output/HZ/HzMember1HZ/out.txt

**Comment by mdogan** [comment]
Updated the PR (https://github.com/hazelcast/hazelcast/pull/14429) to throw original exceptions (`CannotReplicateException`, `NotLeaderException` etc) on the client.

**Comment by Danny-Hazelcast** [comment]
i dont see UndefinedErrorCodeException any more, fixed
