### ISSUE TITLE
com.hazelcast.client.UndefinedErrorCodeException: Class name: com.hazelcast.cp.internal.exception.CannotCreateRaftGroupException

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#14454]
```
com.hazelcast.client.UndefinedErrorCodeException: Class name: com.hazelcast.cp.internal.exception.CannotCreateRaftGroupException, Message: Cannot create CP group: default since CPMember{uuid=82b82ff5-fdac-48b5-aebe-06de84426b94, address=[10.0.0.233]:5701} is not active
	at com.hazelcast.cp.internal.MetadataRaftGroupManager.createRaftGroup(MetadataRaftGroupManager.java:346)
	at com.hazelcast.cp.internal.raftop.metadata.CreateRaftGroupOp.run(CreateRaftGroupOp.java:69)
	at com.hazelcast.cp.internal.NodeEngineRaftIntegration.runOperation(NodeEngineRaftIntegration.java:182)
	at com.hazelcast.cp.internal.raft.impl.RaftNodeImpl.applyLogEntry(RaftNodeImpl.java:611)
	at com.hazelcast.cp.internal.raft.impl.RaftNodeImpl.applyLogEntries(RaftNodeImpl.java:572)
	at com.hazelcast.cp.internal.raft.impl.handler.AppendSuccessResponseHandlerTask.commitEntries(AppendSuccessResponseHandlerTask.java:160)
	at com.hazelcast.cp.internal.raft.impl.handler.AppendSuccessResponseHandlerTask.handleResponse(AppendSuccessResponseHandlerTask.java:88)
	at com.hazelcast.cp.internal.raft.impl.handler.AbstractResponseHandlerTask.innerRun(AbstractResponseHandlerTask.java:43)
	at com.hazelcast.cp.internal.raft.impl.task.RaftNodeStatusAwareTask.run(RaftNodeStatusAwareTask.java:45)
	at com.hazelcast.cp.internal.NodeEngineRaftIntegration.execute(NodeEngineRaftIntegration.java:95)
	at com.hazelcast.cp.internal.raft.impl.RaftNodeImpl.execute(RaftNodeImpl.java:646)
	at com.hazelcast.cp.internal.raft.impl.RaftNodeImpl.handleAppendResponse(RaftNodeImpl.java:236)
	at com.hazelcast.cp.internal.RaftService.handleAppendResponse(RaftService.java:596)
	at com.hazelcast.cp.internal.operation.integration.AppendSuccessResponseOp.run(AppendSuccessResponseOp.java:48)
	at com.hazelcast.spi.Operation.call(Operation.java:170)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:210)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:199)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:416)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:153)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:123)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:110)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:126)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run(AbstractInvocationFuture.java:250)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:96)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:33)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:162)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.join(AbstractInvocationFuture.java:143)
	at com.hazelcast.client.cp.internal.datastructures.atomiclong.RaftAtomicLongProxyFactory.create(RaftAtomicLongProxyFactory.java:47)
	at com.hazelcast.client.spi.ProxyManager.createClientProxy(ProxyManager.java:401)
	at com.hazelcast.client.spi.ProxyManager.getOrCreateProxy(ProxyManager.java:331)
	at com.hazelcast.client.impl.clientside.HazelcastClientInstanceImpl.getDistributedObject(HazelcastClientInstanceImpl.java:880)
	at com.hazelcast.client.impl.clientside.CPSubsystemImpl.getAtomicLong(CPSubsystemImpl.java:49)
```

**Comment by Danny-Hazelcast** [comment]
http://jenkins.hazelcast.com/view/cp-system/job/cp-atomicLongInc-kill/1/console
`com.hazelcast.client.UndefinedErrorCodeException: Class name: com.hazelcast.cp.internal.exception.CannotCreateRaftGroupException`
http://54.234.90.98/~jenkins/workspace/cp-atomicLongInc-kill/3.12-SNAPSHOT/2019_02_04-15_08_47/inc/output/HZ/HzClient1HZ/exception.txt

**Comment by Danny-Hazelcast** [comment]
fixed as test are now throwing  com.hazelcast.cp.internal.exception.CannotCreateRaftGroupException
