### ISSUE TITLE
Hazelcast is not finding VLAN tagged IPv6 interface

### ISSUE THREAD

**Issue by eoso** [hazelcast/hazelcast#14460]
Hello,

I am working with hazelcast version 3.10.4 (a dependency from our vert.x 3.5.x dependency). 

I setting up a cluster using IPv6 addresses and have the settings working correctly on a dev machine. When trying to deploy on a test environment, I am using an interface on a VLAN. The `InetAddress.getHostAddress()` for this interface returns an IPv6 address with format `”x:x:x:x:x:x:x:x%bond0.31”`.

I supply the network config an interface of format `[”x:x:x:x:x:x:x:x”]` (an exact match to the InetAddress besides the `”bond0.31”` suffix) in the config, hazelcast does not find the interface. And throws the error:

```
java.lang.RuntimeException: Hazelcast CANNOT start on this node. No matching network interface found.
Interface matching must be either disabled or updated in the hazelcast.xml config file.
        at com.hazelcast.instance.DefaultAddressPicker.pickInterfaceAddressDef(DefaultAddressPicker.java:210)
        at com.hazelcast.instance.DefaultAddressPicker.pickAddressDef(DefaultAddressPicker.java:178)
        at com.hazelcast.instance.DefaultAddressPicker.getPublicAddressByPortSearch(DefaultAddressPicker.java:112)
        at com.hazelcast.instance.DefaultAddressPicker.pickAddress(DefaultAddressPicker.java:81)
        at com.hazelcast.instance.Node.<init>(Node.java:189)
...
```

I ran through some of the hazelcast code and it appears to be caused by the following code in `AddressUtil.java`:
https://github.com/hazelcast/hazelcast/blob/14cbd8ae1b7908c2b02d03f213dbf41f18e075d3/hazelcast/src/main/java/com/hazelcast/util/AddressUtil.java#L308-L337

Specifically line:
https://github.com/hazelcast/hazelcast/blob/14cbd8ae1b7908c2b02d03f213dbf41f18e075d3/hazelcast/src/main/java/com/hazelcast/util/AddressUtil.java#L316
returns false since the InetAddress hostname string contains the suffix `“bond0.31”`.

Is there a hazelcast property I can use to set the interface without making this check?

**Comment by mdogan** [comment]
It seems we missed that `scope-interface` of an IPv6 address may include a `.` character. That's why `AddressUtil` assumes that's an _IPv4-mapped IPv6_ address.

**Comment by eoso** [comment]
Thanks! Would I be correct in assuming that there isn't a different hazelcast property I can set which would bypass selecting an interface?

**Comment by mdogan** [comment]
You're right. There's no such a property. But since you already have dived into the code, you are welcome to provide a fix for this. :)
