### ISSUE TITLE
QueryCacheSimpleStressTest.testStress

### ISSUE THREAD

**Issue by tezc** [hazelcast/hazelcast#14474]
_master_ (commit 23874cba403df9667e56ef2f45d1c99f9c8ed7aa)

http://jenkins.hazelcast.com/job/Hazelcast-3.x-nightly/19/testReport/junit/

**Failed tests :** 
ClientQueryCacheSimpleStressTest.testStress 
QueryCacheSimpleStressTest.testStress

**Stacktrace**
```
java.lang.AssertionError: expected:<10000> but was:<9855>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.client.map.impl.querycache.ClientQueryCacheSimpleStressTest$2.run(ClientQueryCacheSimpleStressTest.java:105)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1302)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1328)
	at com.hazelcast.client.map.impl.querycache.ClientQueryCacheSimpleStressTest.assertQueryCacheSizeEventually(ClientQueryCacheSimpleStressTest.java:109)
	at com.hazelcast.client.map.impl.querycache.ClientQueryCacheSimpleStressTest.testStress(ClientQueryCacheSimpleStressTest.java:98)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```
Standard output:
```
22:03:10,541  WARN |testStress| - [SubscriberAccumulator] hz.client_741.event-4506 - Event lost detected for queryCache=`f083a1c6-6800-406c-a8bf-5028e48d8ff9`: partitionId=5, expectedSequence=1, foundSequence=2, cacheSize=133
22:03:10,567  WARN |testStress| - [SubscriberAccumulator] hz.client_741.event-4510 - Event lost detected for queryCache=`f083a1c6-6800-406c-a8bf-5028e48d8ff9`: partitionId=174, expectedSequence=1, foundSequence=2, cacheSize=171
22:03:10,622  WARN |testStress| - [SubscriberAccumulator] hz.client_741.event-4508 - Event lost detected for queryCache=`f083a1c6-6800-406c-a8bf-5028e48d8ff9`: partitionId=42, expectedSequence=1, foundSequence=2, cacheSize=273
22:03:10,910  WARN |testStress| - [SubscriberAccumulator] hz.client_741.event-4510 - Event lost detected for queryCache=`f083a1c6-6800-406c-a8bf-5028e48d8ff9`: partitionId=169, expectedSequence=1, foundSequence=2, cacheSize=933
```

**Comment by tezc** [comment]
http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-nightly/20/testReport/
