### ISSUE TITLE
QueryCacheNoEventLossTest.no_event_lost_during_migrations__with_many_parallel_nodes

### ISSUE THREAD

**Issue by tezc** [hazelcast/hazelcast#14476]
_master_ (commit cf45a1b4d42d87580d08c4957264f4c3d0ac8779)

http://jenkins.hazelcast.com/job/Hazelcast-3.x-sonar/23/testReport/junit/com.hazelcast.map.impl.querycache/QueryCacheNoEventLossTest/no_event_lost_during_migrations__with_many_parallel_nodes/

**Stacktrace**
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.lang.Object.wait(Native Method)
	at com.hazelcast.spi.impl.AbstractCompletableFuture.get(AbstractCompletableFuture.java:229)
	at com.hazelcast.util.FutureUtil.executeWithDeadline(FutureUtil.java:379)
	at com.hazelcast.util.FutureUtil.waitWithDeadline(FutureUtil.java:363)
	at com.hazelcast.util.FutureUtil.waitWithDeadline(FutureUtil.java:337)
	at com.hazelcast.instance.Node.callGracefulShutdownAwareServices(Node.java:502)
	at com.hazelcast.instance.Node.shutdown(Node.java:442)
	at com.hazelcast.instance.LifecycleServiceImpl.shutdown(LifecycleServiceImpl.java:98)
	at com.hazelcast.instance.LifecycleServiceImpl.shutdown(LifecycleServiceImpl.java:81)
	at com.hazelcast.test.mocknetwork.TestNodeRegistry.shutdown(TestNodeRegistry.java:125)
	at com.hazelcast.test.mocknetwork.TestNodeRegistry.shutdown(TestNodeRegistry.java:109)
	at com.hazelcast.test.TestHazelcastInstanceFactory.shutdownAll(TestHazelcastInstanceFactory.java:284)
	at com.hazelcast.map.impl.querycache.QueryCacheNoEventLossTest$1.run(QueryCacheNoEventLossTest.java:76)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1302)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1328)
	at com.hazelcast.map.impl.querycache.QueryCacheNoEventLossTest.no_event_lost_during_migrations__with_many_parallel_nodes(QueryCacheNoEventLossTest.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

Standard output: 
```
21:50:17,891  WARN |no_event_lost_during_migrations__with_many_parallel_nodes| - [InternalPartitionService] hz._hzInstance_5864_dev.priority-generic-operation.thread-0 - [127.0.0.1]:5703 [dev] [3.12-SNAPSHOT] Master version should be greater than ours! Local version: 8654, Master version: 8653 Master: [127.0.0.1]:5701
21:50:26,890  WARN |no_event_lost_during_migrations__with_many_parallel_nodes| - [SubscriberAccumulator] hz._hzInstance_5864_dev.event-22268 - Event lost detected for queryCache=`e2bb0b9e-4f84-43a9-93c0-f67ae7cf4f63`: partitionId=462, expectedSequence=1, foundSequence=2, cacheSize=1
21:50:26,900  WARN |no_event_lost_during_migrations__with_many_parallel_nodes| - [SubscriberAccumulator] hz._hzInstance_5864_dev.event-22267 - Event lost detected for queryCache=`e2bb0b9e-4f84-43a9-93c0-f67ae7cf4f63`: partitionId=471, expectedSequence=1, foundSequence=2, cacheSize=2
21:50:26,950  WARN |no_event_lost_during_migrations__with_many_parallel_nodes| - [SubscriberAccumulator] hz._hzInstance_5864_dev.event-22269 - Event lost detected for queryCache=`e2bb0b9e-4f84-43a9-93c0-f67ae7cf4f63`: partitionId=588, expectedSequence=1, foundSequence=2, cacheSize=2
21:50:26,964  WARN |no_event_lost_during_migrations__with_many_parallel_nodes| - [SubscriberAccumulator] hz._hzInstance_5864_dev.event-22269 - Event lost detected for queryCache=`e2bb0b9e-4f84-43a9-93c0-f67ae7cf4f63`: partitionId=808, expectedSequence=1, foundSequence=2, cacheSize=2
21:50:26,966  WARN |no_event_lost_during_migrations__with_many_parallel_nodes| - [SubscriberAccumulator] hz._hzInstance_5864_dev.event-22270 - Event lost detected for queryCache=`e2bb0b9e-4f84-43a9-93c0-f67ae7cf4f63`: partitionId=1439, expectedSequence=1, foundSequence=2, cacheSize=2
```

Probably related with : https://github.com/hazelcast/hazelcast/issues/14474

**Comment by tezc** [comment]
http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-nightly/20/testReport/

**Comment by tezc** [comment]
http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.maintenance-sonar/63/testReport/com.hazelcast.map.impl.querycache/QueryCacheNoEventLossTest/no_event_lost_during_migrations__with_many_parallel_nodes/

**Comment by Holmistr** [comment]
Closing this issue, since maintenance is now 3.12.x, where this test failure was fixed.
