### ISSUE TITLE
Exception - java.lang.AbstractMethodError: Receiver class com.hazelcast.client.impl.clientside.DefaultClientExtension 

### ISSUE THREAD

**Issue by sebvige** [hazelcast/hazelcast#14488]
Hello,

The following code executes ok with submit-job.bat and at hz cluster of 2 member up and running on local host.

```java
import com.hazelcast.client.HazelcastClient;
import com.hazelcast.client.config.ClientConfig;
import com.hazelcast.core.HazelcastInstance;
import com.hazelcast.jet.Jet;
import com.hazelcast.jet.JetInstance;
import com.hazelcast.jet.config.JobConfig;
import com.hazelcast.jet.pipeline.Pipeline;
import com.hazelcast.jet.pipeline.Sinks;
import com.hazelcast.jet.pipeline.Sources;

import java.io.IOException;
import java.util.List;

import static com.hazelcast.jet.Traversers.traverseArray;
import static com.hazelcast.jet.aggregate.AggregateOperations.counting;
import static com.hazelcast.jet.function.DistributedFunctions.wholeItem;



public class JetJob {

    private static final String MAP_1 = "counts";

    public static void main(String[] args) throws IOException {


        JetInstance localjet = Jet.newJetInstance();

        try {
        ClientConfig clientConfig = clientConfigForExternalHazelcast();

        HazelcastInstance externalHz = startExternalHazelcastClient(clientConfig);





        // Create the specification of the computation pipeline. Note
        // it's a pure POJO: no instance of Jet needed to create it.
        Pipeline p2 = Pipeline.create();
        p2.drawFrom(Sources.<String>list("text"))
                .flatMap(line -> traverseArray(line.toLowerCase().split("\\W+")))
                .filter(word -> !word.isEmpty())
                .groupingKey(wholeItem())
                .aggregate(counting())
                .drainTo(Sinks.remoteMap(MAP_1,clientConfig));

        // Start Jet, populate the input list


            List<String> text = localjet.getList("text");
            text.add("hello world hello hello world");
            text.add("world world hello world");

            // Perform the computation
            JobConfig jc = new JobConfig();
            jc.addClass(JetJob.class);
            localjet.newJob(p2,jc).join();

            // Check the results

            System.out.println("remote map content"+externalHz.getMap(MAP_1).entrySet());
        } finally {
            Jet.shutdownAll();
        }
    }


    private static ClientConfig clientConfigForExternalHazelcast() {
        ClientConfig cfg = new ClientConfig();
        cfg.getNetworkConfig().addAddress("localhost:5701");
        cfg.getGroupConfig().setName("dev").setPassword("dev-pass");
        return cfg;

    }

    private static HazelcastInstance startExternalHazelcastClient(ClientConfig config) {
        System.out.println("Creating and populating remote Hazelcast instance...");

        return HazelcastClient.newHazelcastClient(config);
    }
}
```

====== fails when running directly in IDE Intellij ===================

```
java.lang.AbstractMethodError: Receiver class com.hazelcast.client.impl.clientside.DefaultClientExtension does not define or inherit an implementation of the resolved method abstract beforeStart(Lcom/hazelcast/client/impl/HazelcastClientInstanceImpl;)V of interface com.hazelcast.client.ClientExtension.
	at com.hazelcast.client.impl.HazelcastClientInstanceImpl.<init>(HazelcastClientInstanceImpl.java:237)
	at com.hazelcast.client.HazelcastClient$1.createHazelcastInstanceClient(HazelcastClient.java:55)
	at com.hazelcast.client.HazelcastClientManager.newHazelcastClient(HazelcastClientManager.java:75)
	at com.hazelcast.client.HazelcastClient.newHazelcastClient(HazelcastClient.java:72)
	at JetJob.startExternalHazelcastClient(JetJob.java:80)
	at JetJob.main(JetJob.java:32)
```

The grid then stops functioning correctly - It does not seem to be a serialisation issue as described in documentation
Running on java 11G - windows 10 - HZ3.11.1 and Jet 07.2

Kind Regards 

Sébastien

**Comment by cangencer** [comment]
Jet 0.7.2 uses HZ 3.10.5, do you have two different versions of Hazelcast in your classpath perhaps?

**Comment by cangencer** [comment]
This issue was moved to hazelcast/hazelcast-jet#1262
