### ISSUE TITLE
RestMultiendpointTest test failures

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#14499]
_master_ (commit 92ca85687ad1f9cc2057a7cd3b7a27f22bad8019)

Failed on nightly build: http://jenkins.hazelcast.com/job/Hazelcast-3.x-nightly/25/testReport/

Stacktrace:
```
com.hazelcast.config.ConfigurationException: Service start failed. The legacy property hazelcast.rest.enabled is provided together with new Config object. Remove the property from your configuration to fix this issue.
	at com.hazelcast.internal.config.ConfigValidator.ensurePropertyNotConfigured(ConfigValidator.java:486)
	at com.hazelcast.nio.NodeIOService.initRestApiConfig(NodeIOService.java:92)
	at com.hazelcast.nio.NodeIOService.<init>(NodeIOService.java:74)
	at com.hazelcast.instance.DefaultNodeContext.createNetworkingService(DefaultNodeContext.java:146)
	at com.hazelcast.instance.Node.<init>(Node.java:247)
	at com.hazelcast.instance.HazelcastInstanceImpl.createNode(HazelcastInstanceImpl.java:156)
	at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:126)
	at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:228)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:207)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:157)
	at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:57)
	at com.hazelcast.internal.ascii.RestMultiendpointTest.setup(RestMultiendpointTest.java:83)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:394)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:50)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:29)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at com.hazelcast.test.AbstractHazelcastClassRunner$1.evaluate(AbstractHazelcastClassRunner.java:310)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:107)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:83)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:379)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:340)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:413)
```

**Comment by tezc** [comment]
Sonar build : http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-sonar/31/testReport/com.hazelcast.internal.ascii/RestMultiendpointTest/com_hazelcast_internal_ascii_RestMultiendpointTest/

```
Instances haven't been shut down: [HazelcastInstance{name='_hzInstance_11394_83bce04b-c991-42c1-99b5-9c95ac4b36eb', node=[127.0.0.1]:6041}, HazelcastInstance{name='_hzInstance_11404_0b9d3573-e5b5-41bf-899b-90a84f245b4c', node=[127.0.0.1]:6048}, HazelcastInstance{name='_hzInstance_11337_c62f52b5-e9c4-480f-91e4-bd3cda608aec', node=[127.0.0.1]:6003}, HazelcastInstance{name='_hzInstance_11396_4b88714d-ccb7-4855-82a2-17a7b2f67e45', node=[127.0.0.1]:6042}, HazelcastInstance{name='_hzInstance_11358_f898f31e-d437-443b-8d47-8f48b0f48e81', node=[127.0.0.1]:6017}, HazelcastInstance{name='_hzInstance_11333_aa4e83e5-0ed0-4f22-b0d9-245adc5f0268', node=[127.0.0.1]:6000}, HazelcastInstance{name='_hzInstance_11360_0f990b39-f9bb-4e1d-811e-98f00a767e22', node=[127.0.0.1]:6018}, HazelcastInstance{name='_hzInstance_11378_72219cbd-eee9-4ca9-9d0a-ff9bf8b1cd77', node=[127.0.0.1]:6030}, HazelcastInstance{name='_hzInstance_11339_aef97da0-f9bf-4755-88a4-7c7fa865ee9d', node=[127.0.0.1]:6004}, HazelcastInstance{name='_hzInstance_11381_6ceba94a-cf18-4a5a-9316-cb8e3d747aed', node=[127.0.0.1]:6032}, HazelcastInstance{name='_hzInstance_11334_aa4e83e5-0ed0-4f22-b0d9-245adc5f0268', node=[127.0.0.1]:6001}, HazelcastInstance{name='_hzInstance_11349_08c15cb6-4c84-40d2-87e2-4a5b3d8cac9a', node=[127.0.0.1]:6011}, HazelcastInstance{name='_hzInstance_11398_755f2e3b-466b-489e-9ecc-20836ea656d1', node=[127.0.0.1]:6044}, HazelcastInstance{name='_hzInstance_11372_e22f4aca-ebd0-4f35-9f17-8aea3557a749', node=[127.0.0.1]:6026}, HazelcastInstance{name='_hzInstance_11382_6ceba94a-cf18-4a5a-9316-cb8e3d747aed', node=[127.0.0.1]:6033}, HazelcastInstance{name='_hzInstance_11385_c93686e1-5e08-4282-804c-abf4f2e235d4', node=[127.0.0.1]:6035}, HazelcastInstance{name='_hzInstance_11375_4a479447-c741-4a9d-bf3f-7d2328c46f54', node=[127.0.0.1]:6028}, HazelcastInstance{name='_hzInstance_11410_170f17d1-d718-40e3-8561-218a7d319de1', node=[127.0.0.1]:6052}, HazelcastInstance{name='_hzInstance_11399_755f2e3b-466b-489e-9ecc-20836ea656d1', node=[127.0.0.1]:6045}, HazelcastInstance{name='_hzInstance_11373_e22f4aca-ebd0-4f35-9f17-8aea3557a749', node=[127.0.0.1]:6027}, HazelcastInstance{name='_hzInstance_11348_08c15cb6-4c84-40d2-87e2-4a5b3d8cac9a', node=[127.0.0.1]:6010}, HazelcastInstance{name='_hzInstance_11355_3a0f5b2a-7b7b-4a9b-99a5-2c8f943d8aeb', node=[127.0.0.1]:6015}, HazelcastInstance{name='_hzInstance_11342_620d5dae-6e32-44c7-a9df-e6aa57394a75', node=[127.0.0.1]:6006}, HazelcastInstance{name='_hzInstance_11379_72219cbd-eee9-4ca9-9d0a-ff9bf8b1cd77', node=[127.0.0.1]:6031}, HazelcastInstance{name='_hzInstance_11376_4a479447-c741-4a9d-bf3f-7d2328c46f54', node=[127.0.0.1]:6029}, HazelcastInstance{name='_hzInstance_11357_f898f31e-d437-443b-8d47-8f48b0f48e81', node=[127.0.0.1]:6016}, HazelcastInstance{name='_hzInstance_11361_0f990b39-f9bb-4e1d-811e-98f00a767e22', node=[127.0.0.1]:6019}, HazelcastInstance{name='_hzInstance_11369_d002bcfe-ccc9-40e2-aa1d-89b05ff5f779', node=[127.0.0.1]:6024}, HazelcastInstance{name='_hzInstance_11370_d002bcfe-ccc9-40e2-aa1d-89b05ff5f779', node=[127.0.0.1]:6025}, HazelcastInstance{name='_hzInstance_11407_2d187877-f174-43dc-85dd-3bcd294a403e', node=[127.0.0.1]:6050}, HazelcastInstance{name='_hzInstance_11411_170f17d1-d718-40e3-8561-218a7d319de1', node=[127.0.0.1]:6053}, HazelcastInstance{name='_hzInstance_11351_3c00b4f5-6cc4-493c-9298-490880eab364', node=[127.0.0.1]:6012}, HazelcastInstance{name='_hzInstance_11343_620d5dae-6e32-44c7-a9df-e6aa57394a75', node=[127.0.0.1]:6007}, HazelcastInstance{name='_hzInstance_11354_3a0f5b2a-7b7b-4a9b-99a5-2c8f943d8aeb', node=[127.0.0.1]:6014}
```

**Comment by tkountis** [comment]
Should be fixed by https://github.com/hazelcast/hazelcast/pull/14518 the build on Sonar has an older commit ref.

**Comment by tezc** [comment]
_master_ (commit 58abe5433401a6d857c23710cfc9813dde0eb3d2)

http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-sonar/334/testReport/junit/com.hazelcast.internal.ascii/RestMultiendpointTest/testUndefined_GetRequest/

**Stacktrace**
```
java.lang.Exception: Unexpected exception, expected<org.apache.http.NoHttpResponseException> but was<java.net.SocketException>
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:28)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:136)
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:152)
	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:270)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:260)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:161)
	at sun.reflect.GeneratedMethodAccessor1022.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.http.impl.conn.CPoolProxy.invoke(CPoolProxy.java:138)
	at com.sun.proxy.$Proxy191.receiveResponseHeader(Unknown Source)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:271)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:253)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:194)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:85)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
	at com.hazelcast.internal.ascii.HTTPCommunicator.doGet(HTTPCommunicator.java:458)
	at com.hazelcast.internal.ascii.HTTPCommunicator.getRequestToUndefinedURI(HTTPCommunicator.java:554)
	at com.hazelcast.internal.ascii.RestTest.testUndefined_GetRequest(RestTest.java:328)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)
	... 4 more
```
