### ISSUE TITLE
MigrationCommitTest.shouldCommitMigrationWhenSourceFailsDuringCommit

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#14492]
_master_ (commit a8627230b270395b5775172c6599dd0f9d6a2fd4)

Failed on IbmJDK7: http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK7/6/testReport/com.hazelcast.internal.partition.impl/MigrationCommitTest/shouldCommitMigrationWhenSourceFailsDuringCommit/

Stacktrace:
```
java.lang.AssertionError: Instances not in safe state! {[127.0.0.1]:5703=REPLICA_NOT_OWNED}
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport.assertAllInSafeState(HazelcastTestSupport.java:825)
	at com.hazelcast.test.HazelcastTestSupport$4.run(HazelcastTestSupport.java:790)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1302)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1319)
	at com.hazelcast.test.HazelcastTestSupport.waitAllForSafeState(HazelcastTestSupport.java:788)
	at com.hazelcast.test.HazelcastTestSupport.waitAllForSafeState(HazelcastTestSupport.java:784)
	at com.hazelcast.test.HazelcastTestSupport.waitAllForSafeState(HazelcastTestSupport.java:810)
	at com.hazelcast.internal.partition.impl.MigrationCommitTest.shouldCommitMigrationWhenSourceFailsDuringCommit(MigrationCommitTest.java:300)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:95)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:56)
	at java.lang.reflect.Method.invoke(Method.java:620)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.util.concurrent.FutureTask.run(FutureTask.java:274)
	at java.lang.Thread.run(Thread.java:809)
```

Standard output:
```
Hiccups measured while running test 'shouldCommitMigrationWhenSourceFailsDuringCommit(com.hazelcast.internal.partition.impl.MigrationCommitTest):'
04:44:10, accumulated pauses: 58 ms, max pause: 3 ms, pauses over 1000 ms: 0
04:44:15, accumulated pauses: 143 ms, max pause: 13 ms, pauses over 1000 ms: 0
04:44:20, accumulated pauses: 124 ms, max pause: 9 ms, pauses over 1000 ms: 0
04:44:25, accumulated pauses: 69 ms, max pause: 3 ms, pauses over 1000 ms: 0
04:44:30, accumulated pauses: 75 ms, max pause: 3 ms, pauses over 1000 ms: 0
04:44:35, accumulated pauses: 59 ms, max pause: 4 ms, pauses over 1000 ms: 0
04:44:40, accumulated pauses: 55 ms, max pause: 1 ms, pauses over 1000 ms: 0
04:44:45, accumulated pauses: 58 ms, max pause: 2 ms, pauses over 1000 ms: 0
04:44:50, accumulated pauses: 52 ms, max pause: 2 ms, pauses over 1000 ms: 0
04:44:55, accumulated pauses: 72 ms, max pause: 17 ms, pauses over 1000 ms: 0
04:45:00, accumulated pauses: 60 ms, max pause: 3 ms, pauses over 1000 ms: 0
04:45:05, accumulated pauses: 81 ms, max pause: 5 ms, pauses over 1000 ms: 0
04:45:10, accumulated pauses: 75 ms, max pause: 3 ms, pauses over 1000 ms: 0
04:45:15, accumulated pauses: 57 ms, max pause: 3 ms, pauses over 1000 ms: 0
04:45:20, accumulated pauses: 51 ms, max pause: 4 ms, pauses over 1000 ms: 0
04:45:25, accumulated pauses: 46 ms, max pause: 3 ms, pauses over 1000 ms: 0
04:45:30, accumulated pauses: 36 ms, max pause: 2 ms, pauses over 1000 ms: 0
04:45:35, accumulated pauses: 48 ms, max pause: 2 ms, pauses over 1000 ms: 0
04:45:40, accumulated pauses: 45 ms, max pause: 2 ms, pauses over 1000 ms: 0
04:45:45, accumulated pauses: 49 ms, max pause: 2 ms, pauses over 1000 ms: 0
04:45:50, accumulated pauses: 72 ms, max pause: 3 ms, pauses over 1000 ms: 0
04:45:55, accumulated pauses: 58 ms, max pause: 2 ms, pauses over 1000 ms: 0
04:46:00, accumulated pauses: 49 ms, max pause: 1 ms, pauses over 1000 ms: 0
04:46:05, accumulated pauses: 70 ms, max pause: 1 ms, pauses over 1000 ms: 0
04:46:10, accumulated pauses: 76 ms, max pause: 4 ms, pauses over 1000 ms: 0
04:46:15, accumulated pauses: 546 ms, max pause: 510 ms, pauses over 1000 ms: 0
```

**Comment by mmedenjak** [comment]
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/2161

**Comment by mmedenjak** [comment]
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/2135

**Comment by mmedenjak** [comment]
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/2149

**Comment by mdogan** [comment]
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/2178/testReport/junit/com.hazelcast.internal.partition.impl/MigrationCommitTest/shouldCommitMigrationWhenSourceFailsDuringCommit/

```
java.lang.AssertionError: expected:<COMMIT> but was:<ROLLBACK>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.internal.partition.impl.MigrationCommitTest.shouldCommitMigrationWhenSourceFailsDuringCommit(MigrationCommitTest.java:316)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```
