### ISSUE TITLE
HazelcastStarterTest.testMemberWithConfig_withoutFirewallingConnectionManager and HazelcastStarterTest.testMemberWithConfig_withFirewallingConnectionManager

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#14500]
_master_ (commit 92ca85687ad1f9cc2057a7cd3b7a27f22bad8019)

Failed on nightly build: 
* http://jenkins.hazelcast.com/job/Hazelcast-3.x-nightly/25/testReport/com.hazelcast.test.starter.test/HazelcastStarterTest/testMemberWithConfig_withoutFirewallingConnectionManager/
* http://jenkins.hazelcast.com/job/Hazelcast-3.x-nightly/25/testReport/com.hazelcast.test.starter.test/HazelcastStarterTest/testMemberWithConfig_withFirewallingConnectionManager/

Stacktrace:
```
java.lang.NoSuchMethodException: 
class com.hazelcast.instance.Node.getNetworkingService([])

Methods: [public com.hazelcast.instance.HazelcastThreadGroup com.hazelcast.instance.Node.getHazelcastThreadGroup(), public void com.hazelcast.instance.Node.setAsMaster(), public com.hazelcast.logging.ILogger com.hazelcast.instance.Node.getLogger(java.lang.Class), public com.hazelcast.logging.ILogger com.hazelcast.instance.Node.getLogger(java.lang.String), public boolean com.hazelcast.instance.Node.isRunning(), public com.hazelcast.config.Config com.hazelcast.instance.Node.getConfig(), public com.hazelcast.internal.cluster.impl.ClusterServiceImpl com.hazelcast.instance.Node.getClusterService(), public com.hazelcast.internal.partition.InternalPartitionService com.hazelcast.instance.Node.getPartitionService(), public com.hazelcast.internal.serialization.InternalSerializationService com.hazelcast.instance.Node.getSerializationService(), public boolean com.hazelcast.instance.Node.isMaster(), public java.lang.ClassLoader com.hazelcast.instance.Node.getConfigClassLoader(), public com.hazelcast.instance.BuildInfo com.hazelcast.instance.Node.getBuildInfo(), public com.hazelcast.spi.impl.NodeEngineImpl com.hazelcast.instance.Node.getNodeEngine(), public com.hazelcast.nio.Address com.hazelcast.instance.Node.getThisAddress(), public com.hazelcast.instance.MemberImpl com.hazelcast.instance.Node.getLocalMember(), public com.hazelcast.instance.NodeExtension com.hazelcast.instance.Node.getNodeExtension(), public com.hazelcast.nio.Address com.hazelcast.instance.Node.getMasterAddress(), public boolean com.hazelcast.instance.Node.isLiteMember(), public com.hazelcast.internal.management.ManagementCenterService com.hazelcast.instance.Node.getManagementCenterService(), public void com.hazelcast.instance.Node.changeNodeStateToActive(), public void com.hazelcast.instance.Node.changeNodeStateToPassive(), public com.hazelcast.internal.ascii.TextCommandService com.hazelcast.instance.Node.getTextCommandService(), public com.hazelcast.spi.discovery.integration.DiscoveryService com.hazelcast.instance.Node.getDiscoveryService(), public com.hazelcast.internal.cluster.impl.JoinMessage com.hazelcast.instance.Node.createSplitBrainJoinMessage(), public com.hazelcast.internal.cluster.impl.JoinRequest com.hazelcast.instance.Node.createJoinRequest(boolean), public com.hazelcast.internal.cluster.impl.ConfigCheck com.hazelcast.instance.Node.createConfigCheck(), public com.hazelcast.cluster.Joiner com.hazelcast.instance.Node.getJoiner(), public boolean com.hazelcast.instance.Node.joined(), public void com.hazelcast.instance.Node.setMasterAddress(com.hazelcast.nio.Address), public void com.hazelcast.instance.Node.setJoined(), public com.hazelcast.nio.ConnectionManager com.hazelcast.instance.Node.getConnectionManager(), public void com.hazelcast.instance.Node.shutdown(boolean), public java.lang.String com.hazelcast.instance.Node.toString(), public void com.hazelcast.instance.Node.join(), public com.hazelcast.spi.properties.HazelcastProperties com.hazelcast.instance.Node.getProperties(), public com.hazelcast.instance.NodeState com.hazelcast.instance.Node.getState(), public void com.hazelcast.instance.Node.reset(), public final void java.lang.Object.wait(long,int) throws java.lang.InterruptedException, public final native void java.lang.Object.wait(long) throws java.lang.InterruptedException, public final void java.lang.Object.wait() throws java.lang.InterruptedException, public boolean java.lang.Object.equals(java.lang.Object), public native int java.lang.Object.hashCode(), public final native java.lang.Class java.lang.Object.getClass(), public final native void java.lang.Object.notify(), public final native void java.lang.Object.notifyAll()]

Declared Methods: [public com.hazelcast.instance.HazelcastThreadGroup com.hazelcast.instance.Node.getHazelcastThreadGroup(), public void com.hazelcast.instance.Node.setAsMaster(), public com.hazelcast.logging.ILogger com.hazelcast.instance.Node.getLogger(java.lang.Class), public com.hazelcast.logging.ILogger com.hazelcast.instance.Node.getLogger(java.lang.String), public boolean com.hazelcast.instance.Node.isRunning(), public com.hazelcast.config.Config com.hazelcast.instance.Node.getConfig(), public com.hazelcast.internal.cluster.impl.ClusterServiceImpl com.hazelcast.instance.Node.getClusterService(), public com.hazelcast.internal.partition.InternalPartitionService com.hazelcast.instance.Node.getPartitionService(), public com.hazelcast.internal.serialization.InternalSerializationService com.hazelcast.instance.Node.getSerializationService(), public boolean com.hazelcast.instance.Node.isMaster(), public java.lang.ClassLoader com.hazelcast.instance.Node.getConfigClassLoader(), public com.hazelcast.instance.BuildInfo com.hazelcast.instance.Node.getBuildInfo(), public com.hazelcast.spi.impl.NodeEngineImpl com.hazelcast.instance.Node.getNodeEngine(), public com.hazelcast.nio.Address com.hazelcast.instance.Node.getThisAddress(), public com.hazelcast.instance.MemberImpl com.hazelcast.instance.Node.getLocalMember(), public com.hazelcast.instance.NodeExtension com.hazelcast.instance.Node.getNodeExtension(), public com.hazelcast.nio.Address com.hazelcast.instance.Node.getMasterAddress(), public boolean com.hazelcast.instance.Node.isLiteMember(), private com.hazelcast.spi.discovery.integration.DiscoveryService com.hazelcast.instance.Node.createDiscoveryService(com.hazelcast.config.Config), private void com.hazelcast.instance.Node.initializeListeners(com.hazelcast.config.Config), public com.hazelcast.internal.management.ManagementCenterService com.hazelcast.instance.Node.getManagementCenterService(), private void com.hazelcast.instance.Node.shutdownServices(boolean), private void com.hazelcast.instance.Node.mergeEnvironmentProvidedMemberMetadata(), private boolean com.hazelcast.instance.Node.setShuttingDown(), private void com.hazelcast.instance.Node.waitIfAlreadyShuttingDown(), public void com.hazelcast.instance.Node.changeNodeStateToActive(), public void com.hazelcast.instance.Node.changeNodeStateToPassive(), public com.hazelcast.internal.ascii.TextCommandService com.hazelcast.instance.Node.getTextCommandService(), public com.hazelcast.spi.discovery.integration.DiscoveryService com.hazelcast.instance.Node.getDiscoveryService(), public com.hazelcast.internal.cluster.impl.JoinMessage com.hazelcast.instance.Node.createSplitBrainJoinMessage(), public com.hazelcast.internal.cluster.impl.JoinRequest com.hazelcast.instance.Node.createJoinRequest(boolean), public com.hazelcast.internal.cluster.impl.ConfigCheck com.hazelcast.instance.Node.createConfigCheck(), public com.hazelcast.cluster.Joiner com.hazelcast.instance.Node.getJoiner(), com.hazelcast.cluster.Joiner com.hazelcast.instance.Node.createJoiner(), private java.util.Map com.hazelcast.instance.Node.findMemberAttributes(com.hazelcast.config.MemberAttributeConfig), protected com.hazelcast.instance.NodeExtension com.hazelcast.instance.Node.createNodeExtension(com.hazelcast.instance.NodeContext), public boolean com.hazelcast.instance.Node.joined(), public void com.hazelcast.instance.Node.setMasterAddress(com.hazelcast.nio.Address), public void com.hazelcast.instance.Node.setJoined(), public com.hazelcast.nio.ConnectionManager com.hazelcast.instance.Node.getConnectionManager(), public void com.hazelcast.instance.Node.shutdown(boolean), public java.lang.String com.hazelcast.instance.Node.toString(), public void com.hazelcast.instance.Node.join(), static com.hazelcast.logging.ILogger com.hazelcast.instance.Node.access$100(com.hazelcast.instance.Node), static com.hazelcast.instance.NodeState com.hazelcast.instance.Node.access$000(com.hazelcast.instance.Node), public com.hazelcast.spi.properties.HazelcastProperties com.hazelcast.instance.Node.getProperties(), void com.hazelcast.instance.Node.start(), public com.hazelcast.instance.NodeState com.hazelcast.instance.Node.getState(), public void com.hazelcast.instance.Node.reset()]
	at com.hazelcast.test.starter.ReflectionUtils.getMethod(ReflectionUtils.java:111)
	at com.hazelcast.test.starter.answer.AbstractAnswer.getDelegateMethod(AbstractAnswer.java:140)
	at com.hazelcast.test.starter.answer.AbstractAnswer.invoke(AbstractAnswer.java:221)
	at com.hazelcast.test.starter.answer.AbstractAnswer.invoke(AbstractAnswer.java:171)
	at com.hazelcast.test.starter.answer.NodeAnswer.answer(NodeAnswer.java:59)
	at com.hazelcast.test.starter.answer.AbstractAnswer.answer(AbstractAnswer.java:98)
	at com.hazelcast.test.starter.answer.NodeAnswer.answer(NodeAnswer.java:36)
	at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:104)
	at org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29)
	at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:35)
	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:63)
	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:49)
	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor$DispatcherDefaultingToRealMethod.interceptSuperCallable(MockMethodInterceptor.java:110)
	at com.hazelcast.instance.Node$MockitoMock$1455670778.getNetworkingService(Unknown Source)
	at com.hazelcast.test.starter.test.HazelcastStarterTest.testMemberWithConfig(HazelcastStarterTest.java:111)
	at com.hazelcast.test.starter.test.HazelcastStarterTest.testMemberWithConfig_withoutFirewallingConnectionManager(HazelcastStarterTest.java:94)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by olukas** [comment]
Failed also on Sonar: http://jenkins.hazelcast.com/job/Hazelcast-3.x-sonar/34/testReport/
