### ISSUE TITLE
Some YAML test fail with 'Invalid YAML configuration'

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#14501]
_master_ (commit 92ca85687ad1f9cc2057a7cd3b7a27f22bad8019)

Failed on IbmJDK7: http://jenkins.hazelcast.com/job/Hazelcast-3.x-IbmJDK7/7/testReport/
Failed on OracleJDK6: http://jenkins.hazelcast.com/job/Hazelcast-3.x-OracleJDK6/9/testReport/

There is a lot of YAML related tests which fail with following exception. Tests in following test classes fail with that:
* ServiceConfigTest
* XmlYamlConfigBuilderEqualsTest
* YamlConfigBuilderTest
* YamlConfigWithSystemPropertyTest

Stacktrace is like following:
```
com.hazelcast.config.InvalidConfigurationException: Invalid YAML configuration
	at com.hazelcast.config.YamlConfigBuilder.parseAndBuildConfig(YamlConfigBuilder.java:136)
	at com.hazelcast.config.YamlConfigBuilder.build(YamlConfigBuilder.java:124)
	at com.hazelcast.config.ClasspathYamlConfig.<init>(ClasspathYamlConfig.java:98)
	at com.hazelcast.config.ClasspathYamlConfig.<init>(ClasspathYamlConfig.java:57)
	at com.hazelcast.config.ClasspathYamlConfig.<init>(ClasspathYamlConfig.java:44)
	at com.hazelcast.config.ServiceConfigTest.testYaml(ServiceConfigTest.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:95)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:56)
	at java.lang.reflect.Method.invoke(Method.java:620)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.util.concurrent.FutureTask.run(FutureTask.java:274)
	at java.lang.Thread.run(Thread.java:809)
Caused by: com.hazelcast.internal.yaml.YamlException: An error occurred while loading and parsing the YAML stream
	at com.hazelcast.internal.yaml.YamlLoader.load(YamlLoader.java:74)
	at com.hazelcast.config.YamlConfigBuilder.parseAndBuildConfig(YamlConfigBuilder.java:134)
	... 17 more
Caused by: java.lang.UnsupportedOperationException: Processing YAML documents requires Java 8 or higher version
	at com.hazelcast.internal.yaml.YamlLoader.getLoad(YamlLoader.java:158)
	at com.hazelcast.internal.yaml.YamlLoader.load(YamlLoader.java:69)
	... 18 more
```

Standard output:
```
Hiccups measured while running test 'testYaml(com.hazelcast.config.ServiceConfigTest):'
04:10:20, accumulated pauses: 106 ms, max pause: 41 ms, pauses over 1000 ms: 0
```

**Comment by mdogan** [comment]
`Caused by: java.lang.UnsupportedOperationException: Processing YAML documents requires Java 8 or higher version`
