### ISSUE TITLE
JsonGetterContextCacheTest.testCacheSizeIsLimited

### ISSUE THREAD

**Issue by tezc** [hazelcast/hazelcast#14513]
_master_ (commit 9df16954b93393e913808f1138f0bcd97df177d4)

Failed on Solaris OracleJDK8 : http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-Solaris-OracleJDK8/14/com.hazelcast$hazelcast/testReport/com.hazelcast.query.impl.getters/JsonGetterContextCacheTest/testCacheSizeIsLimited/

**Stacktrace**
```
java.lang.AssertionError: expected:<3> but was:<2>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.query.impl.getters.JsonGetterContextCacheTest.testCacheSizeIsLimited(JsonGetterContextCacheTest.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by mmedenjak** [comment]
https://github.com/hazelcast/hazelcast/pull/14510
