### ISSUE TITLE
NullPointerException QueryableEntry extractAttributeValueFromTargetObject 155

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#14511]
http://jenkins.hazelcast.com/view/stable/job/stable-x3/5/console

```
java.lang.NullPointerException
    at com.hazelcast.query.impl.QueryableEntry.extractAttributeValueFromTargetObject(QueryableEntry.java:155)
    at com.hazelcast.query.impl.QueryableEntry.extractAttributeValue(QueryableEntry.java:91)
    at com.hazelcast.query.impl.QueryableEntry.getAttributeValue(QueryableEntry.java:61)
    at com.hazelcast.query.impl.predicates.AbstractPredicate.readAttributeValue(AbstractPredicate.java:141)
    at com.hazelcast.query.impl.predicates.AbstractPredicate.apply(AbstractPredicate.java:61)
    at com.hazelcast.query.impl.predicates.AndPredicate.apply(AndPredicate.java:129)
    at com.hazelcast.query.SqlPredicate.apply(SqlPredicate.java:129)
    at com.hazelcast.query.impl.predicates.OrPredicate.apply(OrPredicate.java:96)
```

```
14:01:04 /disk1/jenkins/workspace/stable-x3/3.12-SNAPSHOT/2019_02_19-08_29_00/comp-idx Failed
14:01:04 fail HzMember4HZ mapBak1BinidAge_predicate hzcmd.map.sql.predicate.PersonIdAgePred threadId=1 java.lang.ClassCastException: java.util.AbstractMap$SimpleImmutableEntry cannot be cast to com.hazelcast.query.impl.Extractable [0m
14:01:05 http://54.234.90.98/~jenkins/workspace/stable-x3/3.12-SNAPSHOT/2019_02_19-08_29_00/comp-idx
```

**Comment by Danny-Hazelcast** [comment]
map config used
```
  <map name="mapBak1HD*">
        <backup-count>1</backup-count>
        <in-memory-format>NATIVE</in-memory-format>
        <eviction-policy>LRU</eviction-policy>

        <max-size policy="FREE_NATIVE_MEMORY_PERCENTAGE">15</max-size>

        <indexes>
            <index ordered="false">firstName, lastName, personId, age</index>
        </indexes>
    </map>


    <map name="mapBak1Bin*">
        <in-memory-format>BINARY</in-memory-format>
        <backup-count>1</backup-count>

        <indexes>
            <index ordered="false">firstName, lastName, personId, age</index>
        </indexes>
    </map>


    <map name="mapBak1Obj*">
        <in-memory-format>OBJECT</in-memory-format>
        <backup-count>1</backup-count>

        <indexes>
            <index ordered="false">firstName, lastName, personId, age</index>
        </indexes>
    </map>

```

**Comment by Danny-Hazelcast** [comment]
http://54.227.64.79/~jenkins/workspace/stable-x3/3.12-SNAPSHOT/2019_02_19-08_29_00/comp-idx/

**Comment by Danny-Hazelcast** [comment]
java.lang.ClassCastException: java.util.AbstractMap$SimpleImmutableEntry cannot be cast to com.hazelcast.query.impl.Extractable

**Comment by taburet** [comment]
Not sure about `NullPointerException` yet, but `ClassCastException` is related more to the test itself: predicates are not supposed to be evaluated on the caller side, it works the same way (and was working before) even if there are no indexes at all. I understand, that's is inconvenient while testing, but the desired behaviour may be achieved in the test by using a custom predicate acting directly on the `Personable` attributes while verifying the returned results.

**Comment by taburet** [comment]
The `NullPointerException` is because of the same reason, but on the client.

**Comment by Danny-Hazelcast** [comment]
yes that was the issue, thanks
