### ISSUE TITLE
CP lock LockOwnershipLostException: Current thread is not owner of the Lock

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#14519]
http://jenkins.hazelcast.com/view/cp-system/job/cp-multiStruts-stable/1/console

/disk1/jenkins/workspace/cp-multiStruts-stable/3.12-SNAPSHOT/2019_02_19-03_00_49/multi-structs

fail HzMember1HZ cp_tryLock hzcmd.cp.lock.TryLocker threadId=0 com.hazelcast.cp.lock.exception.LockOwnershipLostException: Current thread is not owner of the Lock[cp_tryLock12] because its Session[1] is closed by server!

http://54.227.64.79/~jenkins/workspace/cp-multiStruts-stable/3.12-SNAPSHOT/2019_02_19-03_00_49/multi-structs/

this is a stable cluster test using all cp structs concurrently 

```
cat output/HZ/HzMember1HZ/exception.txt
com.hazelcast.cp.lock.exception.LockOwnershipLostException: Current thread is not owner of the Lock[cp_tryLock12] because its Session[1] is closed by server!
	at com.hazelcast.cp.internal.datastructures.lock.proxy.AbstractRaftFencedLockProxy.newLockOwnershipLostException(AbstractRaftFencedLockProxy.java:361)
	at com.hazelcast.cp.internal.datastructures.lock.proxy.AbstractRaftFencedLockProxy.unlock(AbstractRaftFencedLockProxy.java:219)
	at hzcmd.cp.lock.TryLocker.timeStep(TryLocker.java:23)
	at remote.bench.marker.MetricsMarker.flatOut(MetricsMarker.java:53)
	at remote.bench.marker.MetricsMarker.bench(MetricsMarker.java:40)
	at remote.bench.BenchThread.call(BenchThread.java:41)
	at remote.bench.BenchThread.call(BenchThread.java:14)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.IllegalStateException: No valid session!
	at com.hazelcast.cp.internal.datastructures.semaphore.proxy.RaftSessionAwareSemaphoreProxy.newIllegalStateException(RaftSessionAwareSemaphoreProxy.java:246)
	at com.hazelcast.cp.internal.datastructures.semaphore.proxy.RaftSessionAwareSemaphoreProxy.release(RaftSessionAwareSemaphoreProxy.java:168)
	at com.hazelcast.cp.internal.datastructures.semaphore.proxy.RaftSessionAwareSemaphoreProxy.release(RaftSessionAwareSemaphoreProxy.java:150)
	at hzcmd.cp.semaphore.TryAcquire.timeStep(TryAcquire.java:26)
	at remote.bench.marker.MetricsMarker.flatOut(MetricsMarker.java:53)
	at remote.bench.marker.MetricsMarker.bench(MetricsMarker.java:40)
	at remote.bench.BenchThread.call(BenchThread.java:41)
	at remote.bench.BenchThread.call(BenchThread.java:14)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.hazelcast.cp.internal.session.SessionExpiredException: active session: 1 does not exist in CPGroupId{name='default', seed=0, commitIndex=8}
	at com.hazelcast.cp.internal.datastructures.spi.blocking.AbstractBlockingService.heartbeatSession(AbstractBlockingService.java:260)
	at com.hazelcast.cp.internal.datastructures.semaphore.RaftSemaphoreService.releasePermits(RaftSemaphoreService.java:102)
	at com.hazelcast.cp.internal.datastructures.semaphore.operation.ReleasePermitsOp.run(ReleasePermitsOp.java:53)
	at com.hazelcast.cp.internal.NodeEngineRaftIntegration.runOperation(NodeEngineRaftIntegration.java:184)
	at com.hazelcast.cp.internal.raft.impl.RaftNodeImpl.applyLogEntry(RaftNodeImpl.java:601)
	at com.hazelcast.cp.internal.raft.impl.RaftNodeImpl.applyLogEntries(RaftNodeImpl.java:551)
	at com.hazelcast.cp.internal.raft.impl.handler.AppendSuccessResponseHandlerTask.commitEntries(AppendSuccessResponseHandlerTask.java:162)
	at com.hazelcast.cp.internal.raft.impl.handler.AppendSuccessResponseHandlerTask.handleResponse(AppendSuccessResponseHandlerTask.java:88)
	at com.hazelcast.cp.internal.raft.impl.handler.AbstractResponseHandlerTask.innerRun(AbstractResponseHandlerTask.java:43)
	at com.hazelcast.cp.internal.raft.impl.task.RaftNodeStatusAwareTask.run(RaftNodeStatusAwareTask.java:46)
	at com.hazelcast.cp.internal.NodeEngineRaftIntegration.execute(NodeEngineRaftIntegration.java:97)
	at com.hazelcast.cp.internal.raft.impl.RaftNodeImpl.execute(RaftNodeImpl.java:636)
	at com.hazelcast.cp.internal.raft.impl.RaftNodeImpl.handleAppendResponse(RaftNodeImpl.java:239)
	at com.hazelcast.cp.internal.RaftService.handleAppendResponse(RaftService.java:605)
	at com.hazelcast.cp.internal.operation.integration.AppendSuccessResponseOp.run(AppendSuccessResponseOp.java:48)com.hazelcast.cp.lock.exception.LockOwnershipLostException: Current thread is not owner of the Lock[cp_tryLock12] because its Session[1] is closed by server!
	at com.hazelcast.spi.Operation.call(Operation.java:170)

	at com.hazelcast.cp.internal.datastructures.lock.proxy.AbstractRaftFencedLockProxy.newLockOwnershipLostException(AbstractRaftFencedLockProxy.java:361)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:210)	at com.hazelcast.cp.internal.datastructures.lock.proxy.AbstractRaftFencedLockProxy.unlock(AbstractRaftFencedLockProxy.java:219)

	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:199)	at hzcmd.cp.lock.TryLocker.timeStep(TryLocker.java:23)

	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:416)
	at remote.bench.marker.MetricsMarker.flatOut(MetricsMarker.java:53)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:153)	at remote.bench.marker.MetricsMarker.bench(MetricsMarker.java:40)

	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:123)	at remote.bench.BenchThread.call(BenchThread.java:41)

	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:110)	at remote.bench.BenchThread.call(BenchThread.java:14)

	at ------ submitted from ------.(Unknown Source)	at java.util.concurrent.FutureTask.run(FutureTask.java:266)

	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:126)	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:79)	at java.util.concurrent.FutureTask.run(FutureTask.java:266)

	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:162)	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.get(InvocationFuture.java:177)	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

	at com.hazelcast.spi.impl.AbstractInvocationFuture.join(AbstractInvocationFuture.java:143)	at java.lang.Thread.run(Thread.java:748)

	at com.hazelcast.cp.internal.datastructures.semaphore.proxy.RaftSessionAwareSemaphoreProxy.release(RaftSessionAwareSemaphoreProxy.java:165)
	... 12 more
java.lang.IllegalStateException: No valid session!
	at com.hazelcast.cp.internal.datastructures.semaphore.proxy.RaftSessionAwareSemaphoreProxy.newIllegalStateException(RaftSessionAwareSemaphoreProxy.java:246)
	at com.hazelcast.cp.internal.datastructures.semaphore.proxy.RaftSessionAwareSemaphoreProxy.release(RaftSessionAwareSemaphoreProxy.java:168)
	at com.hazelcast.cp.internal.datastructures.semaphore.proxy.RaftSessionAwareSemaphoreProxy.release(RaftSessionAwareSemaphoreProxy.java:150)
	at hzcmd.cp.semaphore.TryAcquire.timeStep(TryAcquire.java:26)
	at remote.bench.marker.MetricsMarker.flatOut(MetricsMarker.java:53)
	at remote.bench.marker.MetricsMarker.bench(MetricsMarker.java:40)
	at remote.bench.BenchThread.call(BenchThread.java:41)
	at remote.bench.BenchThread.call(BenchThread.java:14)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.hazelcast.cp.internal.session.SessionExpiredException: active session: 1 does not exist in CPGroupId{name='default', seed=0, commitIndex=8}
	at com.hazelcast.cp.internal.datastructures.spi.blocking.AbstractBlockingService.heartbeatSession(AbstractBlockingService.java:260)
	at com.hazelcast.cp.internal.datastructures.semaphore.RaftSemaphoreService.releasePermits(RaftSemaphoreService.java:102)
	at com.hazelcast.cp.internal.datastructures.semaphore.operation.ReleasePermitsOp.run(ReleasePermitsOp.java:53)
	at com.hazelcast.cp.internal.NodeEngineRaftIntegration.runOperation(NodeEngineRaftIntegration.java:184)
	at com.hazelcast.cp.internal.raft.impl.RaftNodeImpl.applyLogEntry(RaftNodeImpl.java:601)
	at com.hazelcast.cp.internal.raft.impl.RaftNodeImpl.applyLogEntries(RaftNodeImpl.java:551)
	at com.hazelcast.cp.internal.raft.impl.handler.AppendSuccessResponseHandlerTask.commitEntries(AppendSuccessResponseHandlerTask.java:162)
	at com.hazelcast.cp.internal.raft.impl.handler.AppendSuccessResponseHandlerTask.handleResponse(AppendSuccessResponseHandlerTask.java:88)
	at com.hazelcast.cp.internal.raft.impl.handler.AbstractResponseHandlerTask.innerRun(AbstractResponseHandlerTask.java:43)
	at com.hazelcast.cp.internal.raft.impl.task.RaftNodeStatusAwareTask.run(RaftNodeStatusAwareTask.java:46)
	at com.hazelcast.cp.internal.NodeEngineRaftIntegration.execute(NodeEngineRaftIntegration.java:97)
	at com.hazelcast.cp.internal.raft.impl.RaftNodeImpl.execute(RaftNodeImpl.java:636)
	at com.hazelcast.cp.internal.raft.impl.RaftNodeImpl.handleAppendResponse(RaftNodeImpl.java:239)
	at com.hazelcast.cp.internal.RaftService.handleAppendResponse(RaftService.java:605)
	at com.hazelcast.cp.internal.operation.integration.AppendSuccessResponseOp.run(AppendSuccessResponseOp.java:48)
	at com.hazelcast.spi.Operation.call(Operation.java:170)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:210)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:199)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:416)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:153)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:123)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:110)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:126)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:79)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:162)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.get(InvocationFuture.java:177)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.join(AbstractInvocationFuture.java:143)
	at com.hazelcast.cp.internal.datastructures.semaphore.proxy.RaftSessionAwareSemaphoreProxy.release(RaftSessionAwareSemaphoreProxy.java:165)
	... 12 more
```

**Comment by mdogan** [comment]
New URL: http://34.207.251.106/~jenkins/workspace/cp-multiStruts-stable/3.12-SNAPSHOT/2019_02_19-03_00_49/multi-structs/
