### ISSUE TITLE
MapPredicateJsonMixedTypeTest.testPortableWithSamePath failure

### ISSUE THREAD

**Issue by blazember** [hazelcast/hazelcast#14517]
Failed in the PR builder both with `OBJECT` and `NATIVE` memory format:
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/427/

In both case:
```
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
	at java.lang.Long.compareTo(Long.java:54)
	at com.hazelcast.query.impl.predicates.GreaterLessPredicate.applyForSingleAttributeValue(GreaterLessPredicate.java:67)
	at com.hazelcast.query.impl.predicates.AbstractPredicate.convertAndApplyForSingleAttributeValue(AbstractPredicate.java:88)
	at com.hazelcast.query.impl.predicates.AbstractPredicate.apply(AbstractPredicate.java:68)
	at com.hazelcast.map.impl.query.PartitionScanRunner.run(PartitionScanRunner.java:100)
	at com.hazelcast.map.impl.query.CallerRunsPartitionScanExecutor.execute(CallerRunsPartitionScanExecutor.java:42)
	at com.hazelcast.map.impl.query.QueryRunner.runPartitionScanQueryOnGivenOwnedPartition(QueryRunner.java:220)
	at com.hazelcast.map.impl.query.QueryPartitionOperation.run(QueryPartitionOperation.java:46)
	at com.hazelcast.spi.Operation.call(Operation.java:170)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:210)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:199)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:147)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:125)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:110)
```

Eventually fails in local as well.

**Comment by mmedenjak** [comment]
The problem is not inherent to JSON but an already present issue of querying the same path where the attribute value results in different types. The same issue can be reproduced by adding two different portables with the same attribute but different attribute type (in one portable, `age` can be `int`, in the other it can be `long`).

Since the `AbstractPredicate#convert(java.lang.Comparable, java.lang.Comparable)` method is called for each extracted value and since it caches the result of the previously seen attribute type in `attributeType`, it can wrongly assume that the next extracted value is of the same type.

In the case of this test, JSON extractor will extract an attributeValue of type `long` while the portable will extract a value of type `int`. If the predicate first encounters a portable, it will assume all further values are of type `int` and convert the predicate value to `int`. Once we attempt to compare the predicate value with the attribute value obtained from JSON, we get the exception.
