### ISSUE TITLE
PartitionIteratingOperation ERROR during shutdown

### ISSUE THREAD

**Issue by ceeaspb** [hazelcast/hazelcast#14525]
In our cluster tests we see this error during shutdown intermittently.

Hazelcast 3.11
3 member cluster
Java 8u191

```
2019-02-19 17:52:20.063|INFO|main||[10.32.0.7]:5701 [dev] [3.11] Hazelcast 3.11 (20181023 - 1500bbb) starting at [10.32.0.7]:5701|com.hazelcast.system
2019-02-19 17:52:20.063|INFO|main||[10.32.0.7]:5701 [dev] [3.11] Copyright (c) 2008-2018, Hazelcast, Inc. All Rights Reserved.|com.hazelcast.system
2019-02-19 17:52:20.329|INFO|main||[10.32.0.7]:5701 [dev] [3.11] Backpressure is disabled|com.hazelcast.spi.impl.operationservice.impl.BackpressureRegulator
2019-02-19 17:52:21.108|INFO|main||[10.32.0.7]:5701 [dev] [3.11] Creating TcpIpJoiner|com.hazelcast.instance.Node
2019-02-19 17:52:21.479|INFO|main||[10.32.0.7]:5701 [dev] [3.11] Starting 2 partition threads and 3 generic threads (1 dedicated for priority tasks)|com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl
2019-02-19 17:52:21.487|INFO|main||[10.32.0.7]:5701 [dev] [3.11] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.|com.hazelcast.internal.diagnostics.Diagnostics
2019-02-19 17:52:21.511|INFO|main||[10.32.0.7]:5701 [dev] [3.11] [10.32.0.7]:5701 is STARTING|com.hazelcast.core.LifecycleService

...

2019-02-19 18:21:32.545|INFO|shutdown thread||[10.32.0.7]:5701 [dev] [3.11] [10.32.0.7]:5701 is SHUTTING_DOWN|com.hazelcast.core.LifecycleService
2019-02-19 18:21:37.837|INFO|hz.x-76959fc57-r9zff.cached.thread-1||[10.32.0.7]:5701 [dev] [3.11] Could not connect to: /10.36.0.3:5701. Reason: SocketException[Connection refused to address /10.36.0.3:5701]|com.hazelcast.nio.tcp.TcpIpConnector
2019-02-19 18:21:37.837|WARN|hz.x-76959fc57-r9zff.cached.thread-1||[10.32.0.7]:5701 [dev] [3.11] Removing connection to endpoint [10.36.0.3]:5701 Cause => java.net.SocketException {Connection refused to address /10.36.0.3:5701}, Error-Count: 7|com.hazelcast.nio.tcp.TcpIpConnectionErrorHandler
2019-02-19 18:21:37.904|INFO|hz.x-76959fc57-r9zff.cached.thread-3||[10.32.0.7]:5701 [dev] [3.11] Connecting to /10.36.0.3:5701, timeout: 0, bind-any: true|com.hazelcast.nio.tcp.TcpIpConnector
2019-02-19 18:21:38.106|INFO|hz.x-76959fc57-r9zff.cached.thread-3||[10.32.0.7]:5701 [dev] [3.11] Could not connect to: /10.36.0.3:5701. Reason: SocketException[Connection refused to address /10.36.0.3:5701]|com.hazelcast.nio.tcp.TcpIpConnector
2019-02-19 18:21:38.106|WARN|hz.x-76959fc57-r9zff.cached.thread-3||[10.32.0.7]:5701 [dev] [3.11] Removing connection to endpoint [10.36.0.3]:5701 Cause => java.net.SocketException {Connection refused to address /10.36.0.3:5701}, Error-Count: 8|com.hazelcast.nio.tcp.TcpIpConnectionErrorHandler
2019-02-19 18:21:38.171|INFO|hz.x-76959fc57-r9zff.priority-generic-operation.thread-0||[10.32.0.7]:5701 [dev] [3.11] 

Members {size:2, ver:22} [
    Member [10.44.0.2]:5701 - 93bb0ef4-ea91-406e-bbc6-727ceccd8422
    Member [10.32.0.7]:5701 - b6f61180-ce13-4b35-9633-6c638e2f77bb this
]
|com.hazelcast.internal.cluster.ClusterService
2019-02-19 18:21:38.188|ERROR|hz.x-76959fc57-r9zff.generic-operation.thread-1||[10.32.0.7]:5701 [dev] [3.11] Member [10.32.0.7]:5701 is currently passive! Operation: com.hazelcast.spi.impl.operationservice.impl.operations.PartitionIteratingOperation{serviceName='hz:impl:mapService', identityHash=1383516254, partitionId=-1, replicaIndex=0, callId=10484, invocationTime=1550600498057 (2019-02-19 18:21:38.057), waitTimeout=-1, callTimeout=60000, operationFactory=com.hazelcast.map.impl.operation.PartitionWideEntryWithPredicateOperationFactory@320e7793}|com.hazelcast.spi.impl.operationservice.impl.operations.PartitionIteratingOperation
com.hazelcast.core.HazelcastInstanceNotActiveException: Member [10.32.0.7]:5701 is currently passive! Operation: com.hazelcast.spi.impl.operationservice.impl.operations.PartitionIteratingOperation{serviceName='hz:impl:mapService', identityHash=1383516254, partitionId=-1, replicaIndex=0, callId=10484, invocationTime=1550600498057 (2019-02-19 18:21:38.057), waitTimeout=-1, callTimeout=60000, operationFactory=com.hazelcast.map.impl.operation.PartitionWideEntryWithPredicateOperationFactory@320e7793}
    at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.checkNodeState(OperationRunnerImpl.java:269) ~[hazelcast-3.11.jar:3.11]
    at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:185) ~[hazelcast-3.11.jar:3.11]
    at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:413) ~[hazelcast-3.11.jar:3.11]
    at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:153) ~[hazelcast-3.11.jar:3.11]
    at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:123) ~[hazelcast-3.11.jar:3.11]
    at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:110) ~[hazelcast-3.11.jar:3.11]
2019-02-19 18:21:43.203|INFO|Diffusion shutdown handler||[10.32.0.7]:5701 [dev] [3.11] Shutting down connection manager...|com.hazelcast.instance.Node
2019-02-19 18:21:43.204|INFO|Diffusion shutdown handler||[10.32.0.7]:5701 [dev] [3.11] Connection[id=1, /10.32.0.7:38534->/10.44.0.2:5701, endpoint=[10.44.0.2]:5701, alive=false, type=MEMBER] closed. Reason: TcpIpConnectionManager is stopping|com.hazelcast.nio.tcp.TcpIpConnection
2019-02-19 18:21:43.405|INFO|Diffusion shutdown handler||[10.32.0.7]:5701 [dev] [3.11] Shutting down node engine...|com.hazelcast.instance.Node
2019-02-19 18:21:43.426|INFO|Diffusion shutdown handler||[10.32.0.7]:5701 [dev] [3.11] Destroying node NodeExtension.|com.hazelcast.instance.NodeExtension
2019-02-19 18:21:43.427|INFO|Diffusion shutdown handler||[10.32.0.7]:5701 [dev] [3.11] Hazelcast Shutdown is completed in 10881 ms.|com.hazelcast.instance.Node
2019-02-19 18:21:43.428|INFO|Diffusion shutdown handler||[10.32.0.7]:5701 [dev] [3.11] [10.32.0.7]:5701 is SHUTDOWN|com.hazelcast.core.LifecycleService```

**Comment by anatolibarski** [comment]
same problem here

**Comment by parvezalisha** [comment]
@mmedenjak i am also seeing similar error as @antidote2 . Do we know what's causing it and when is it going to be fixed?

**Comment by mmedenjak** [comment]
Hi @ceeaspb @antidote2 @parvezalisha !

I would say that these errors are mostly ok as the invocation (operation) will be retried for several times until the cluster is stable again and the operation is able to successfully return the correct results.

This error is caused because the operation has started execution on the node which is about to shut down, which can always happen and shouldn't be a problem. We have tests covering this scenario as well.

I see you're invoking some EntryProcessor and `map.size`. Are you noticing that the operation returns that error or returns incorrect results?

**Comment by ceeaspb** [comment]
Hi @mmedenjak thanks - maybe this log message level could be changed from ERROR to DEBUG as you say this is not an error condition and should not be a problem.

What do you think?

**Comment by mmedenjak** [comment]
You're right @ceeaspb , we'll consider changing this in the next release.
