### ISSUE TITLE
Exception when deserializing cache config on 3.12-BETA-1 client in compatibility mode

### ISSUE THREAD

**Issue by mmedenjak** [hazelcast/hazelcast#14541]
Failed: http://jenkins.hazelcast.com/view/multi-version/job/multi-version-client-compat/3

```
com.hazelcast.nio.serialization.HazelcastSerializationException: Problem while reading DataSerializable, namespace: 0, ID: 0, class: 'com.hazelcast.config.CacheEvictionConfig', exception: java.lang.Class cannot be cast to com.hazelcast.internal.eviction.EvictionPolicyComparator
        at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.rethrowReadException(DataSerializableSerializer.java:183)
        at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.readInternal(DataSerializableSerializer.java:164)
        at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:106)
        at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:51)
        at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48)
        at com.hazelcast.internal.serialization.impl.AbstractSerializationService.readObject(AbstractSerializationService.java:269)
        at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readObject(ByteArrayObjectDataInput.java:574)
        at com.hazelcast.config.CacheConfig.readData(CacheConfig.java:551)
        at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.readInternal(DataSerializableSerializer.java:160)
        at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:106)
        at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:51)
        at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48)
        at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:187)
        at com.hazelcast.client.cache.impl.ClientCacheHelper.deserializeCacheConfig(ClientCacheHelper.java:101)
        at com.hazelcast.client.cache.impl.ClientCacheHelper.getCacheConfig(ClientCacheHelper.java:78)
        at com.hazelcast.client.cache.impl.HazelcastClientCacheManager.getCacheConfig(HazelcastClientCacheManager.java:106)
        at com.hazelcast.client.cache.impl.HazelcastClientCacheManager.findCacheConfig(HazelcastClientCacheManager.java:133)
        at com.hazelcast.cache.impl.AbstractHazelcastCacheManager.getCacheUnchecked(AbstractHazelcastCacheManager.java:228)
        at com.hazelcast.cache.impl.AbstractHazelcastCacheManager.getCache(AbstractHazelcastCacheManager.java:210)
        at com.hazelcast.cache.impl.AbstractHazelcastCacheManager.getCache(AbstractHazelcastCacheManager.java:65)
        at hzcmd.cache.base.CacheBench.init(CacheBench.java:21)
        at remote.bench.BenchContainer.init(BenchContainer.java:70)
        at remote.bench.BenchManager.init(BenchManager.java:113)
        at remote.main.Controler.initBench(Controler.java:92)
        at remote.command.InitCmd.exicute(InitCmd.java:23)
        at remote.main.Controler.run(Controler.java:203)
        at vendor.hz.java.HzClient.main(HzClient.java:9)
Caused by: java.lang.ClassCastException: java.lang.Class cannot be cast to com.hazelcast.internal.eviction.EvictionPolicyComparator
        at com.hazelcast.config.EvictionConfig.readData(EvictionConfig.java:325)
        at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.readInternal(DataSerializableSerializer.java:160)
```

Seems to look like the config was serialized using compatibility config (probably because member had the legacy setting enabled) but client tried to deserialize it with non-compatibility config.

JVM properties:
```
CLIENT_OPS=-Xms200M -Xmx200M -Dhazelcast.diagnostics.enabled\=true -Dhazelcast.diagnostics.metric.level\=DEBUG -Dhazelcast.diagnostics.overloaded.connections.period.seconds\=10 -Dhazelcast.diagnostics.overloaded.connections.threshold\=5000 -Dhazelcast.diagnostics.invocation.slow.threshold.seconds\=10 -Dhazelcast.diagnostics.invocation.sample.period.seconds\=10 -Dhazelcast.health.monitoring.level\=NOISY -Dhazelcast.health.monitoring.delay.seconds\=10 -Dhazelcast.operation.backup.timeout.millis\=240000 -Dhazelcast.operation.call.timeout.millis\=240000 -Dhazelcast.enterprise.license.key\=HazelcastEnterpriseHD\#9999Nodes\#RiUHNE1lOrwITY7F5K3VAm539qt3h099W999C99999xn999PsQ1Pv19q39h0 
MEMBER_OPS=-Xms2G -Xmx2G -Dhazelcast.diagnostics.enabled\=true -Dhazelcast.diagnostics.metric.level\=DEBUG -Dhazelcast.diagnostics.overloaded.connections.period.seconds\=10 -Dhazelcast.diagnostics.overloaded.connections.threshold\=5000 -Dhazelcast.diagnostics.invocation.slow.threshold.seconds\=10 -Dhazelcast.diagnostics.invocation.sample.period.seconds\=10 -Dhazelcast.health.monitoring.level\=NOISY -Dhazelcast.health.monitoring.delay.seconds\=10 -Dhazelcast.operation.backup.timeout.millis\=240000 -Dhazelcast.operation.call.timeout.millis\=240000 -Dhazelcast.enterprise.license.key\=HazelcastEnterpriseHD\#9999Nodes\#RiUHNE1lOrwITY7F5K3VAm539qt3h099W999C99999xn999PsQ1Pv19q39h0 -Dhazelcast.compatibility.3.6.client\=true 
```

**Comment by sancar** [comment]
The issue is caused by BuildInfo.calcualteVersion. It cannot parse `3.12-BETA-1` treats it as an unknown version in older versions of hazelcast(before 3.10)
This affects only new beta releases when a beta client is used with a member before 3.10. 
BuildInfo.calcualteVersion was already fixed here in 3.10. 
https://github.com/hazelcast/hazelcast/pull/12365
