### ISSUE TITLE
AdvancedNetworkClientIntegrationTest.clientSmokeTest

### ISSUE THREAD

**Issue by tezc** [hazelcast/hazelcast#14543]
_master_ (commit b04e92cd992e7299844dc361b491103208cd2335)

Failed on ZuluJDK7 : http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-ZuluJDK7/8/testReport/com.hazelcast.client.io/AdvancedNetworkClientIntegrationTest/clientSmokeTest/

**Stacktrace**
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:315)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:160)
	at com.hazelcast.client.spi.ClientProxy.invokeOnPartition(ClientProxy.java:225)
	at com.hazelcast.client.spi.ClientProxy.invoke(ClientProxy.java:219)
	at com.hazelcast.client.proxy.ClientMapProxy.putInternal(ClientMapProxy.java:584)
	at com.hazelcast.client.proxy.ClientMapProxy.put(ClientMapProxy.java:334)
	at com.hazelcast.client.io.AdvancedNetworkClientIntegrationTest.clientSmokeTest(AdvancedNetworkClientIntegrationTest.java:87)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by tezc** [comment]
http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-OracleJDK9/7/testReport/com.hazelcast.client.io/AdvancedNetworkClientIntegrationTest/testClientMembershipEvent/

**Stacktrace**
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.base@9.0.4/java.lang.Object.wait(Native Method)
	at app//com.hazelcast.spi.impl.AbstractCompletableFuture.get(AbstractCompletableFuture.java:229)
	at app//com.hazelcast.util.FutureUtil.executeWithDeadline(FutureUtil.java:379)
	at app//com.hazelcast.util.FutureUtil.waitWithDeadline(FutureUtil.java:363)
	at app//com.hazelcast.util.FutureUtil.waitWithDeadline(FutureUtil.java:337)
	at app//com.hazelcast.instance.Node.callGracefulShutdownAwareServices(Node.java:537)
	at app//com.hazelcast.instance.Node.shutdown(Node.java:474)
	at app//com.hazelcast.instance.LifecycleServiceImpl.shutdown(LifecycleServiceImpl.java:98)
	at app//com.hazelcast.instance.LifecycleServiceImpl.shutdown(LifecycleServiceImpl.java:81)
	at app//com.hazelcast.instance.HazelcastInstanceProxy.shutdown(HazelcastInstanceProxy.java:310)
	at app//com.hazelcast.client.io.AdvancedNetworkClientIntegrationTest.testClientMembershipEvent(AdvancedNetworkClientIntegrationTest.java:132)
	at java.base@9.0.4/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@9.0.4/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base@9.0.4/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@9.0.4/java.lang.reflect.Method.invoke(Method.java:564)
	at app//org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at app//org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at app//org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at app//org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at app//com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at app//com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.base@9.0.4/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base@9.0.4/java.lang.Thread.run(Thread.java:844)
```

```
14:58:37,186  WARN |testClientMembershipEvent| - [ClientReAuthOperation] hz._hzInstance_4482_dev.priority-generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [3.12-SNAPSHOT] com.hazelcast.spi.exception.CallerNotMemberException: Not Member! this: [127.0.0.1]:5701, caller: [127.0.0.1]:59948, partitionId: -1, operation: com.hazelcast.client.impl.operations.ClientReAuthOperation, service: hz:core:clientEngine
14:58:37,190  WARN |testClientMembershipEvent| - [ClientReAuthOperation] hz._hzInstance_4482_dev.generic-operation.thread-1 - [127.0.0.1]:5701 [dev] [3.12-SNAPSHOT] com.hazelcast.spi.exception.CallerNotMemberException: Not Member! this: [127.0.0.1]:5701, caller: [127.0.0.1]:59948, partitionId: -1, operation: com.hazelcast.client.impl.operations.ClientReAuthOperation, service: hz:core:clientEngine
14:58:37,191  WARN |testClientMembershipEvent| - [ClientReAuthOperation] hz._hzInstance_4482_dev.priority-generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [3.12-SNAPSHOT] com.hazelcast.spi.exception.CallerNotMemberException: Not Member! this: [127.0.0.1]:5701, caller: [127.0.0.1]:59948, partitionId: -1, operation: com.hazelcast.client.impl.operations.ClientReAuthOperation, service: hz:core:clientEngine
14:58:37,193  WARN |testClientMembershipEvent| - [ClientReAuthOperation] hz._hzInstance_4482_dev.priority-generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [3.12-SNAPSHOT] com.hazelcast.spi.exception.CallerNotMemberException: Not Member! this: [127.0.0.1]:5701, caller: [127.0.0.1]:59948, partitionId: -1, operation: com.hazelcast.client.impl.operations.ClientReAuthOperation, service: hz:core:clientEngine
14:58:37,195  WARN |testClientMembershipEvent| - [ClientReAuthOperation] hz._hzInstance_4482_dev.priority-generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [3.12-SNAPSHOT] com.hazelcast.spi.exception.CallerNotMemberException: Not Member! this: [127.0.0.1]:5701, caller: [127.0.0.1]:59948, partitionId: -1, operation: com.hazelcast.client.impl.operations.ClientReAuthOperation, service: hz:core:clientEngine
14:58:37,200  WARN |testClientMembershipEvent| - [ClientReAuthOperation] hz._hzInstance_4482_dev.priority-generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [3.12-SNAPSHOT] com.hazelcast.spi.exception.CallerNotMemberException: Not Member! this: [127.0.0.1]:5701, caller: [127.0.0.1]:59948, partitionId: -1, operation: com.hazelcast.client.impl.operations.ClientReAuthOperation, service: hz:core:clientEngine
14:58:37,205  WARN |testClientMembershipEvent| - [ClientReAuthOperation] hz._hzInstance_4482_dev.priority-generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [3.12-SNAPSHOT] com.hazelcast.spi.exception.CallerNotMemberException: Not Member! this: [127.0.0.1]:5701, caller: [127.0.0.1]:59948, partitionId: -1, operation: com.hazelcast.client.impl.operations.ClientReAuthOperation, service: hz:core:clientEngine
14:58:37,212  WARN |testClientMembershipEvent| - [ClientReAuthOperation] hz._hzInstance_4482_dev.priority-generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [3.12-SNAPSHOT] com.hazelcast.spi.exception.CallerNotMemberException: Not Member! this: [127.0.0.1]:5701, caller: [127.0.0.1]:59948, partitionId: -1, operation: com.hazelcast.client.impl.operations.ClientReAuthOperation, service: hz:core:clientEngine
14:58:37,223  WARN |testClientMembershipEvent| - [ClientReAuthOperation] hz._hzInstance_4482_dev.priority-generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [3.12-SNAPSHOT] com.hazelcast.spi.exception.CallerNotMemberException: Not Member! this: [127.0.0.1]:5701, caller: [127.0.0.1]:59948, partitionId: -1, operation: com.hazelcast.client.impl.operations.ClientReAuthOperation, service: hz:core:clientEngine
14:58:37,227 DEBUG |testClientMembershipEvent| - [AuthenticationMessageTask] hz._hzInstance_4483_dev.generic-operation.thread-1 - [127.0.0.1]:5702 [dev] [3.12-SNAPSHOT] Processing owner authentication with principal ClientPrincipal{uuid='76469389-d80a-485b-8484-c27766420cb7', ownerUuid='4dccf733-c588-4b54-b1ce-4415e2e4ee3e'}
14:58:37,227  WARN |testClientMembershipEvent| - [ClientReAuthOperation] hz._hzInstance_4482_dev.generic-operation.thread-1 - [127.0.0.1]:5701 [dev] [3.12-SNAPSHOT] com.hazelcast.spi.exception.CallerNotMemberException: Not Member! this: [127.0.0.1]:5701, caller: [127.0.0.1]:59948, partitionId: -1, operation: com.hazelcast.client.impl.operations.ClientReAuthOperation, service: hz:core:clientEngine
14:58:37,229  WARN |testClientMembershipEvent| - [ClientReAuthOperation] hz._hzInstance_4482_dev.generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [3.12-SNAPSHOT] com.hazelcast.spi.exception.CallerNotMemberException: Not Member! this: [127.0.0.1]:5701, caller: [127.0.0.1]:59948, partitionId: -1, operation: com.hazelcast.client.impl.operations.ClientReAuthOperation, service: hz:core:clientEngine
14:58:37,230  WARN |testClientMembershipEvent| - [ClientReAuthOperation] hz._hzInstance_4482_dev.generic-operation.thread-1 - [127.0.0.1]:5701 [dev] [3.12-SNAPSHOT] com.hazelcast.spi.exception.CallerNotMemberException: Not Member! this: [127.0.0.1]:5701, caller: [127.0.0.1]:59948, partitionId: -1, operation: com.hazelcast.client.impl.operations.ClientReAuthOperation, service: hz:core:clientEngine
14:58:37,231  WARN |testClientMembershipEvent| - [ClientReAuthOperation] hz._hzInstance_4482_dev.priority-generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [3.12-SNAPSHOT] com.hazelcast.spi.exception.CallerNotMemberException: Not Member! this: [127.0.0.1]:5701, caller: [127.0.0.1]:59948, partitionId: -1, operation: com.hazelcast.client.impl.operations.ClientReAuthOperation, service: hz:core:clientEngine
14:58:37,232  WARN |testClientMembershipEvent| - [ClientReAuthOperation] hz._hzInstance_4482_dev.generic-operation.thread-1 - [127.0.0.1]:5701 [dev] [3.12-SNAPSHOT] com.hazelcast.spi.exception.CallerNotMemberException: Not Member! this: [127.0.0.1]:5701, caller: [127.0.0.1]:59948, partitionId: -1, operation: com.hazelcast.client.impl.operations.ClientReAuthOperation, service: hz:core:clientEngine
14:58:37,235  WARN |testClientMembershipEvent| - [ClientReAuthOperation] hz._hzInstance_4482_dev.generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [3.12-SNAPSHOT] com.hazelcast.spi.exception.CallerNotMemberException: Not Member! this: [127.0.0.1]:5701, caller: [127.0.0.1]:59948, partitionId: -1, operation: com.hazelcast.client.impl.operations.ClientReAuthOperation, service: hz:core:clientEngine
14:58:37,240  WARN |testClientMembershipEvent| - [ClientReAuthOperation] hz._hzInstance_4482_dev.generic-operation.thread-1 - [127.0.0.1]:5701 [dev] [3.12-SNAPSHOT] com.hazelcast.spi.exception.CallerNotMemberException: Not Member! this: [127.0.0.1]:5701, caller: [127.0.0.1]:59948, partitionId: -1, operation: com.hazelcast.client.impl.operations.ClientReAuthOperation, service: hz:core:clientEngine
14:58:37,241  WARN |testClientMembershipEvent| - [ClientReAuthOperation] hz._hzInstance_4482_dev.generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [3.12-SNAPSHOT] com.hazelcast.spi.exception.CallerNotMemberException: Not Member! this: [127.0.0.1]:5701, caller: [127.0.0.1]:59948, partitionId: -1, operation: com.hazelcast.client.impl.operations.ClientReAuthOperation, service: hz:core:clientEngine
14:58:37,244 DEBUG |testClientMembershipEvent| - [AuthenticationMessageTask] hz._hzInstance_4483_dev.generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [3.12-SNAPSHOT] Processing owner authentication with principal ClientPrincipal{uuid='66fb87fc-3d7a-4ea5-8b08-d5bbd1a13614', ownerUuid='4dccf733-c588-4b54-b1ce-4415e2e4ee3e'}
14:58:37,244  WARN |testClientMembershipEvent| - [ClientReAuthOperation] hz._hzInstance_4482_dev.generic-operation.thread-1 - [127.0.0.1]:5701 [dev] [3.12-SNAPSHOT] com.hazelcast.spi.exception.CallerNotMemberException: Not Member! this: [127.0.0.1]:5701, caller: [127.0.0.1]:59948, partitionId: -1, operation: com.hazelcast.client.impl.operations.ClientReAuthOperation, service: hz:core:clientEngine
14:58:37,248  WARN |testClientMembershipEvent| - [ClientReAuthOperation] hz._hzInstance_4482_dev.generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [3.12-SNAPSHOT] com.hazelcast.spi.exception.CallerNotMemberException: Not Member! this: [127.0.0.1]:5701, caller: [127.0.0.1]:59948, partitionId: -1, operation: com.hazelcast.client.impl.operations.ClientReAuthOperation, service: hz:core:clientEngine
14:58:37,248  WARN |testClientMembershipEvent| - [ClientReAuthOperation] hz._hzInstance_4482_dev.generic-operation.thread-1 - [127.0.0.1]:5701 [dev] [3.12-SNAPSHOT] com.hazelcast.spi.exception.CallerNotMemberException: Not Member! this: [127.0.0.1]:5701, caller: [127.0.0.1]:59948, partitionId: -1, operation: com.hazelcast.client.impl.operations.ClientReAuthOperation, service: hz:core:clientEngine
14:58:37,248  WARN |testClientMembershipEvent| - [ClientReAuthOperation] hz._hzInstance_4482_dev.generic-operation.thread-1 - [127.0.0.1]:5701 [dev] [3.12-SNAPSHOT] com.hazelcast.spi.exception.CallerNotMemberException: Not Member! this: [127.0.0.1]:5701, caller: [127.0.0.1]:59948, partitionId: -1, operation: com.hazelcast.client.impl.operations.ClientReAuthOperation, service: hz:core:clientEngine
14:58:37,250  WARN |testClientMembershipEvent| - [ClientReAuthOperation] hz._hzInstance_4482_dev.generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [3.12-SNAPSHOT] com.hazelcast.spi.exception.CallerNotMemberException: Not Member! this: [127.0.0.1]:5701, caller: [127.0.0.1]:59948, partitionId: -1, operation: com.hazelcast.client.impl.operations.ClientReAuthOperation, service: hz:core:clientEngine
14:58:37,250  WARN |testClientMembershipEvent| - [ClientReAuthOperation] hz._hzInstance_4482_dev.generic-operation.thread-1 - [127.0.0.1]:5701 [dev] [3.12-SNAPSHOT] com.hazelcast.spi.exception.CallerNotMemberException: Not Member! this: [127.0.0.1]:5701, caller: [127.0.0.1]:59948, partitionId: -1, operation: com.hazelcast.client.impl.operations.ClientReAuthOperation, service: hz:core:clientEngine
14:58:37,252  WARN |testClientMembershipEvent| - [ClientReAuthOperation] hz._hzInstance_4482_dev.generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [3.12-SNAPSHOT] com.hazelcast.spi.exception.CallerNotMemberException: Not Member! this: [127.0.0.1]:5701, caller: [127.0.0.1]:59948, partitionId: -1, operation: com.hazelcast.client.impl.operations.ClientReAuthOperation, service: hz:core:clientEngine
14:58:37,257  WARN |testClientMembershipEvent| - [ClientReAuthOperation] hz._hzInstance_4482_dev.generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [3.12-SNAPSHOT] com.hazelcast.spi.exception.CallerNotMemberException: Not Member! this: [127.0.0.1]:5701, caller: [127.0.0.1]:59948, partitionId: -1, operation: com.hazelcast.client.impl.operations.ClientReAuthOperation, service: hz:core:clientEngine
14:58:37,257  WARN |testClientMembershipEvent| - [ClientReAuthOperation] hz._hzInstance_4482_dev.generic-operation.thread-1 - [127.0.0.1]:5701 [dev] [3.12-SNAPSHOT] com.hazelcast.spi.exception.CallerNotMemberException: Not Member! this: [127.0.0.1]:5701, caller: [127.0.0.1]:59948, partitionId: -1, operation: com.hazelcast.client.impl.operations.ClientReAuthOperation, service: hz:core:clientEngine
14:58:37,266  WARN |testClientMembershipEvent| - [ClientReAuthOperation] hz._hzInstance_4482_dev.priority-generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [3.12-SNAPSHOT] com.hazelcast.spi.exception.CallerNotMemberException: Not Member! this: [127.0.0.1]:5701, caller: [127.0.0.1]:59948, partitionId: -1, operation: com.hazelcast.client.impl.operations.ClientReAuthOperation, service: hz:core:clientEngine
14:58:37,276  WARN |testClientMembershipEvent| - [ClientReAuthOperation] hz._hzInstance_4482_dev.generic-operation.thread-1 - [127.0.0.1]:5701 [dev] [3.12-SNAPSHOT] com.hazelcast.spi.exception.CallerNotMemberException: Not Member! this: [127.0.0.1]:5701, caller: [127.0.0.1]:59948, partitionId: -1, operation: com.hazelcast.client.impl.operations.ClientReAuthOperation, service: hz:core:clientEngine
14:58:37,277  WARN |testClientMembershipEvent| - [ClientReAuthOperation] hz._hzInstance_4482_dev.priority-generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [3.12-SNAPSHOT] com.hazelcast.spi.exception.CallerNotMemberException: Not Member! this: [127.0.0.1]:5701, caller: [127.0.0.1]:59948, partitionId: -1, operation: com.hazelcast.client.impl.operations.ClientReAuthOperation, service: hz:core:clientEngine
14:58:37,278  WARN |testClientMembershipEvent| - [ClientReAuthOperation] hz._hzInstance_4482_dev.generic-operation.thread-1 - [127.0.0.1]:5701 [dev] [3.12-SNAPSHOT] com.hazelcast.spi.exception.CallerNotMemberException: Not Member! this: [127.0.0.1]:5701, caller: [127.0.0.1]:59948, partitionId: -1, operation: com.hazelcast.client.impl.operations.ClientReAuthOperation, service: hz:core:clientEngine
14:58:37,295  WARN |testClientMembershipEvent| - [ClientReAuthOperation] hz._hzInstance_4482_dev.priority-generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [3.12-SNAPSHOT] com.hazelcast.spi.exception.CallerNotMemberException: Not Member! this: [127.0.0.1]:5701, caller: [127.0.0.1]:59948, partitionId: -1, operation: com.hazelcast.client.impl.operations.ClientReAuthOperation, service: hz:core:clientEngine
14:58:37,311  WARN |testClientMembershipEvent| - [ClientReAuthOperation] hz._hzInstance_4482_dev.priority-generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [3.12-SNAPSHOT] com.hazelcast.spi.exception.CallerNotMemberException: Not Member! this: [127.0.0.1]:5701, caller: [127.0.0.1]:59948, partitionId: -1, operation: com.hazelcast.client.impl.operations.ClientReAuthOperation, service: hz:core:clientEngine
14:58:37,352  WARN |testClientMembershipEvent| - [ClientReAuthOperation] hz._hzInstance_4482_dev.generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [3.12-SNAPSHOT] com.hazelcast.spi.exception.CallerNotMemberException: Not Member! this: [127.0.0.1]:5701, caller: [127.0.0.1]:59948, partitionId: -1, operation: com.hazelcast.client.impl.operations.ClientReAuthOperation, service: hz:core:clientEngine
14:58:37,352  WARN |testClientMembershipEvent| - [ClientReAuthOperation] hz._hzInstance_4482_dev.generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [3.12-SNAPSHOT] com.hazelcast.spi.exception.CallerNotMemberException: Not Member! this: [127.0.0.1]:5701, caller: [127.0.0.1]:59948, partitionId: -1, operation: 
```

**Comment by mdogan** [comment]
Similarly:

```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at com.hazelcast.client.io.AdvancedNetworkClientIntegrationTest.testClientMembershipEvent(AdvancedNetworkClientIntegrationTest.java:132)
```

http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/550/testReport/junit/com.hazelcast.client.io/AdvancedNetworkClientIntegrationTest/testClientMembershipEvent/
