### ISSUE TITLE
MetadataRaftGroupTest.when_membersLeaveDuringDiscoveryAfterCPSubsystemRestart_then_discoveryIsCancelled

### ISSUE THREAD

**Issue by mdogan** [hazelcast/hazelcast#14554]
```
14:23:03 [ERROR] when_membersLeaveDuringDiscoveryAfterCPSubsystemRestart_then_discoveryIsCancelled(com.hazelcast.cp.internal.MetadataRaftGroupTest)  Time elapsed: 21.861 s  <<< ERROR!
14:23:03 com.hazelcast.spi.exception.RetryableHazelcastException: HazelcastInstance[[127.0.0.1]:5706] is not active!
14:23:03     at com.hazelcast.spi.impl.NodeEngineImpl.getService(NodeEngineImpl.java:370)
14:23:03     at com.hazelcast.cp.internal.HazelcastRaftTestSupport.getRaftService(HazelcastRaftTestSupport.java:214)
14:23:03     at com.hazelcast.cp.internal.MetadataRaftGroupTest$27.run(MetadataRaftGroupTest.java:759)
14:23:03     at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1302)
14:23:03     at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1328)
14:23:03     at com.hazelcast.cp.internal.MetadataRaftGroupTest.when_membersLeaveDuringDiscoveryAfterCPSubsystemRestart_then_discoveryIsCancelled(MetadataRaftGroupTest.java:755)
14:23:03     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
14:23:03     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
14:23:03     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
14:23:03     at java.lang.reflect.Method.invoke(Method.java:498)
14:23:03     at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
14:23:03     at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
14:23:03     at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
14:23:03     at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
14:23:03     at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
14:23:03     at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
14:23:03     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
14:23:03     at java.lang.Thread.run(Thread.java:748)
```

**Comment by sancar** [comment]
Failed here in my pr 
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/2166/testReport/junit/com.hazelcast.cp.internal/MetadataRaftGroupTest/when_membersLeaveDuringDiscoveryAfterCPSubsystemRestart_then_discoveryIsCancelled/


Error Message
`HazelcastInstance[[127.0.0.1]:5706] is not active!`
Stacktrace
```
com.hazelcast.spi.exception.RetryableHazelcastException: HazelcastInstance[[127.0.0.1]:5706] is not active!
	at com.hazelcast.spi.impl.NodeEngineImpl.getService(NodeEngineImpl.java:368)
	at com.hazelcast.cp.internal.HazelcastRaftTestSupport.getRaftService(HazelcastRaftTestSupport.java:200)
	at com.hazelcast.cp.internal.MetadataRaftGroupTest.lambda$when_membersLeaveDuringDiscoveryAfterCPSubsystemRestart_then_discoveryIsCancelled$25(MetadataRaftGroupTest.java:668)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1303)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1405)
	at com.hazelcast.cp.internal.MetadataRaftGroupTest.when_membersLeaveDuringDiscoveryAfterCPSubsystemRestart_then_discoveryIsCancelled(MetadataRaftGroupTest.java:666)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```
