### ISSUE TITLE
AggregationMemberBounceTest.aggregationReturnsCorrectResultWhenBouncing

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#14565]
_master_ (commit 023ba6c39d8a327c6612abe19a51a03c3c79a284)

Failed on Sonar: http://jenkins.hazelcast.com/job/Hazelcast-3.x-sonar/35/testReport/com.hazelcast.aggregation/AggregationMemberBounceTest/aggregationReturnsCorrectResultWhenBouncing/

Stacktrace:
```
java.lang.AssertionError: There is missing data in the map! expected:<999> but was:<997>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.aggregation.AggregatorsSpecTest.assertNoDataMissing(AggregatorsSpecTest.java:398)
	at com.hazelcast.aggregation.AggregatorsSpecTest.assertSumAggregators(AggregatorsSpecTest.java:149)
	at com.hazelcast.aggregation.AggregationMemberBounceTest$1.run(AggregationMemberBounceTest.java:73)
	at com.hazelcast.test.bounce.BounceMemberRule$TestTaskRunnable.run(BounceMemberRule.java:613)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Standard output:
```
Hiccups measured while running test 'aggregationReturnsCorrectResultWhenBouncing(com.hazelcast.aggregation.AggregationMemberBounceTest):'
23:05:10, accumulated pauses: 96 ms, max pause: 14 ms, pauses over 1000 ms: 0
23:05:15, accumulated pauses: 43 ms, max pause: 0 ms, pauses over 1000 ms: 0
23:05:20, accumulated pauses: 523 ms, max pause: 357 ms, pauses over 1000 ms: 0
23:05:25, accumulated pauses: 64 ms, max pause: 23 ms, pauses over 1000 ms: 0
23:05:30, accumulated pauses: 81 ms, max pause: 2 ms, pauses over 1000 ms: 0
23:05:35, accumulated pauses: 105 ms, max pause: 38 ms, pauses over 1000 ms: 0
23:05:40, accumulated pauses: 68 ms, max pause: 1 ms, pauses over 1000 ms: 0
23:05:45, accumulated pauses: 37 ms, max pause: 1 ms, pauses over 1000 ms: 0
```

**Comment by taburet** [comment]
Should be fixed by https://github.com/hazelcast/hazelcast/pull/14526
