### ISSUE TITLE
HazelcastClientNotActiveException  Client is blacklisted from this cluster

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#14564]
in these rollup test, a lot of tests (15) are failing with a

com.hazelcast.client.HazelcastClientNotActiveException

and the logs show `Client is blacklisted from this cluster` however i have not black listed the client
in any config or settings

http://jenkins.hazelcast.com/view/rollup/job/rollup-All_3.11_3.12-SNAPSHOT/2/console

```
/disk1/jenkins/workspace/rollup-All_3.11_3.12-SNAPSHOT/3.12-SNAPSHOT/2019_02_23-11_33_49/stable/atomic Failed
18:10:15 fail HzClient8HZ _atomic_atomic com.hazelcast.client.HazelcastClientNotActiveException: Client is not active. [0m
18:10:15 http://54.234.90.98/~jenkins/workspace/rollup-All_3.11_3.12-SNAPSHOT/3.12-SNAPSHOT/2019_02_23-11_33_49/stable/atomic
18:10:15  
18:15:56 /disk1/jenkins/workspace/rollup-All_3.11_3.12-SNAPSHOT/3.12-SNAPSHOT/2019_02_23-11_33_49/stable/cas Failed
18:15:56 fail HzClient7HZ _map-cas_long com.hazelcast.client.HazelcastClientNotActiveException: Client is not active. [0m
18:15:57 http://54.234.90.98/~jenkins/workspace/rollup-All_3.11_3.12-SNAPSHOT/3.12-SNAPSHOT/2019_02_23-11_33_49/stable/cas
```

in the logs of the client i see this warning repeated over and over in the logs.

```
Feb 23, 2019 8:26:46 PM com.hazelcast.client.connection.nio.ClientConnection
WARNING: hz.client_0 [HZ] [3.12-SNAPSHOT] ClientConnection{alive=false, connectionId=523, channel=NioChannel{/10.0.0.56:54402->/10.0.0.23:5701}, remoteEndpoint=null, lastReadTime=20
19-02-23 20:26:46.664, lastWriteTime=2019-02-23 20:26:46.664, closedTime=2019-02-23 20:26:46.664, connected server version=null} closed. Reason: com.hazelcast.client.ClientNotAllowe
dInClusterException[Client is blacklisted from this cluster]
com.hazelcast.client.ClientNotAllowedInClusterException: Client is blacklisted from this cluster
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl$AuthCallback.onResponse(ClientConnectionManagerImpl.java:699)
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl$AuthCallback.onResponse(ClientConnectionManagerImpl.java:644)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture$InternalDelegatingExecutionCallback.onResponse(ClientInvocationFuture.java:130)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture$InternalDelegatingExecutionCallback.onResponse(ClientInvocationFuture.java:118)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture$InternalDelegatingExecutionCallback.onResponse(ClientInvocationFuture.java:130)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture$InternalDelegatingExecutionCallback.onResponse(ClientInvocationFuture.java:118)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run(AbstractInvocationFuture.java:255)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
```

```
com.hazelcast.client.HazelcastClientNotActiveException: Client is not active.
	at com.hazelcast.client.impl.clientside.HazelcastClientProxy.getClient(HazelcastClientProxy.java:314)
	at com.hazelcast.client.impl.clientside.HazelcastClientProxy.getAtomicLong(HazelcastClientProxy.java:203)
```

**Comment by Danny-Hazelcast** [comment]
loads of thest multi version test are failing with the same issue,  looks like every time the 
3.12-SANPSHOT client are cont connecting to the 3.11 / 3.12 mixed version cluster 

```
    hz cluster -size m2 -v 3.11        -ee -boxes a.box -user ec2-user >> out.txt
    hz cluster -size m2 -v ${hzVersion}  -ee -boxes a.box -user ec2-user >> out.txt

    hz cluster -size c2 -v 3.11        -ee -boxes a.box -user ec2-user >> out.txt
    hz cluster -size c2 -v ${hzVersion}  -ee -boxes a.box -user ec2-user >> out.txt
```

**Comment by sancar** [comment]
@Danny-Hazelcast I found the problem. Fix is on the way.
