### ISSUE TITLE
CPMemberAddRemoveTest.testMetadataGroupReinitializationAfterLostMajority

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#14567]
_master_ (commit d4e66fd0b0f71bcc956594802b146945ef45d7dc)

Failed on Windows: http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-Windows-OracleJDK8/10/console

Unfortunately whole related run was failed due to `ChannelClosedException` hence standard output was not persisted.

Stacktrace:
```
java.lang.AssertionError
 	at org.junit.Assert.fail(Assert.java:86)
 	at org.junit.Assert.assertTrue(Assert.java:41)
 	at org.junit.Assert.assertTrue(Assert.java:52)
 	at com.hazelcast.cp.internal.HazelcastRaftTestSupport$2.run(HazelcastRaftTestSupport.java:95)
 	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1302)
 	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1328)
 	at com.hazelcast.cp.internal.HazelcastRaftTestSupport.waitUntilCPDiscoveryCompleted(HazelcastRaftTestSupport.java:90)
 	at com.hazelcast.cp.internal.CPMemberAddRemoveTest.testMetadataGroupReinitializationAfterLostMajority(CPMemberAddRemoveTest.java:287)
 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 	at java.lang.reflect.Method.invoke(Method.java:498)
 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
 	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
 	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by olukas** [comment]
Failed also on ZingJDK8: http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-ZingJDK8/11/testReport/com.hazelcast.cp.internal/CPMemberAddRemoveTest/testMetadataGroupReinitializationAfterLostMajority/

However there are high hiccups in that run:
```
Hiccups measured while running test 'testMetadataGroupReinitializationAfterLostMajority(com.hazelcast.cp.internal.CPMemberAddRemoveTest):'
12:45:45, accumulated pauses: 4944 ms, max pause: 14 ms, pauses over 1000 ms: 0
12:45:50, accumulated pauses: 4940 ms, max pause: 10 ms, pauses over 1000 ms: 0
12:45:55, accumulated pauses: 4940 ms, max pause: 10 ms, pauses over 1000 ms: 0
12:46:00, accumulated pauses: 4942 ms, max pause: 11 ms, pauses over 1000 ms: 0
12:46:05, accumulated pauses: 4940 ms, max pause: 10 ms, pauses over 1000 ms: 0
12:46:10, accumulated pauses: 4940 ms, max pause: 10 ms, pauses over 1000 ms: 0
12:46:15, accumulated pauses: 4940 ms, max pause: 10 ms, pauses over 1000 ms: 0
12:46:20, accumulated pauses: 4940 ms, max pause: 10 ms, pauses over 1000 ms: 0
12:46:25, accumulated pauses: 4940 ms, max pause: 10 ms, pauses over 1000 ms: 0
12:46:30, accumulated pauses: 4940 ms, max pause: 10 ms, pauses over 1000 ms: 0
12:46:35, accumulated pauses: 4940 ms, max pause: 10 ms, pauses over 1000 ms: 0
12:46:40, accumulated pauses: 4940 ms, max pause: 10 ms, pauses over 1000 ms: 0
12:46:45, accumulated pauses: 4940 ms, max pause: 10 ms, pauses over 1000 ms: 0
12:46:50, accumulated pauses: 4940 ms, max pause: 10 ms, pauses over 1000 ms: 0
12:46:55, accumulated pauses: 4941 ms, max pause: 10 ms, pauses over 1000 ms: 0
12:47:00, accumulated pauses: 4940 ms, max pause: 10 ms, pauses over 1000 ms: 0
12:47:05, accumulated pauses: 4940 ms, max pause: 10 ms, pauses over 1000 ms: 0
12:47:10, accumulated pauses: 4940 ms, max pause: 10 ms, pauses over 1000 ms: 0
12:47:15, accumulated pauses: 4941 ms, max pause: 10 ms, pauses over 1000 ms: 0
12:47:20, accumulated pauses: 4940 ms, max pause: 10 ms, pauses over 1000 ms: 0
12:47:25, accumulated pauses: 4940 ms, max pause: 10 ms, pauses over 1000 ms: 0
12:47:30, accumulated pauses: 4941 ms, max pause: 10 ms, pauses over 1000 ms: 0
12:47:35, accumulated pauses: 4941 ms, max pause: 10 ms, pauses over 1000 ms: 0
12:47:40, accumulated pauses: 4941 ms, max pause: 10 ms, pauses over 1000 ms: 0
12:47:45, accumulated pauses: 4931 ms, max pause: 10 ms, pauses over 1000 ms: 0
12:47:50, accumulated pauses: 4940 ms, max pause: 10 ms, pauses over 1000 ms: 0
12:47:55, accumulated pauses: 4941 ms, max pause: 10 ms, pauses over 1000 ms: 0
12:48:00, accumulated pauses: 4941 ms, max pause: 10 ms, pauses over 1000 ms: 0
12:48:05, accumulated pauses: 4010 ms, max pause: 10 ms, pauses over 1000 ms: 0
```

**Comment by tezc** [comment]
http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-ZingJDK8/12/testReport/com.hazelcast.cp.internal/CPMemberAddRemoveTest/testMetadataGroupReinitializationAfterLostMajority/

```
19:50:21,549 ERROR |testMetadataGroupReinitializationAfterLostMajority| - [PostJoinProxyOperation] hz._hzInstance_9057_dev.cached.thread-4 - [127.0.0.1]:5705 [dev] [3.12-SNAPSHOT] Cannot create proxy [hz:raft:atomicLongService:proxy]!
com.hazelcast.cp.exception.CPGroupDestroyedException: CPGroupId{name='METADATA', seed=0, commitIndex=0}
	at com.hazelcast.cp.internal.MetadataRaftGroupManager.getGroup(MetadataRaftGroupManager.java:274) ~[classes/:?]
	at com.hazelcast.cp.internal.RaftService.getCPGroupLocally(RaftService.java:513) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.RaftInvocationContext.newMemberCursor(RaftInvocationContext.java:109) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.RaftInvocation.getTargetEndpoint(RaftInvocation.java:145) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.RaftInvocation.getInvocationTarget(RaftInvocation.java:64) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.RaftInvocation.getInvocationTarget(RaftInvocation.java:44) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.initInvocationTarget(Invocation.java:286) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:614) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.access$400(Invocation.java:96) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation$InvocationRetryTask.run(Invocation.java:827) ~[classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0-zing_16.07.0.0]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0-zing_16.07.0.0]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0-zing_16.07.0.0]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:1.8.0-zing_16.07.0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0-zing_16.07.0.0]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0-zing_16.07.0.0]
	at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0-zing_16.07.0.0]
	at ------ submitted from ------.(Unknown Source) ~[?:?]
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:126) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:79) ~[classes/:?]
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:162) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.get(InvocationFuture.java:177) ~[classes/:?]
	at com.hazelcast.spi.impl.AbstractInvocationFuture.join(AbstractInvocationFuture.java:143) ~[classes/:?]
	at com.hazelcast.cp.internal.RaftService.getGroupIdForProxy(RaftService.java:742) ~[classes/:?]
	at com.hazelcast.cp.internal.RaftService.createRaftGroupForProxy(RaftService.java:725) ~[classes/:?]
	at com.hazelcast.cp.internal.datastructures.atomiclong.RaftAtomicLongService.createDistributedObject(RaftAtomicLongService.java:159) ~[classes/:?]
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyRegistry.doCreateProxy(ProxyRegistry.java:216) ~[classes/:?]
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyRegistry.createProxy(ProxyRegistry.java:209) ~[classes/:?]
	at com.hazelcast.spi.impl.proxyservice.impl.operations.PostJoinProxyOperation$CreateProxyTask.run(PostJoinProxyOperation.java:127) [classes/:?]
	at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:227) [classes/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0-zing_16.07.0.0]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0-zing_16.07.0.0]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0-zing_16.07.0.0]
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64) [classes/:?]
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80) [classes/:?]
```

```
19:51:03,650  WARN |testMetadataGroupReinitializationAfterLostMajority| - [Invocation] hz._hzInstance_9057_dev.response-1 - [127.0.0.1]:5705 [dev] [3.12-SNAPSHOT] Retrying invocation: Invocation{op=com.hazelcast.cp.internal.operation.RaftQueryOp{serviceName='hz:core:raft', identityHash=381234731, partitionId=109, replicaIndex=0, callId=2629, invocationTime=1551142263649 (2019-02-25 19:51:03.649), waitTimeout=-1, callTimeout=60000, op=com.hazelcast.cp.internal.raftop.metadata.GetRaftGroupOp{serviceName='hz:core:raft', targetGroupId=CPGroupId{name='METADATA', seed=1551142217525, commitIndex=0}}, groupId=CPGroupId{name='METADATA', seed=1551142217525, commitIndex=0}, policy=LEADER_LOCAL}, tryCount=250, tryPauseMillis=500, invokeCount=100, callTimeoutMillis=60000, firstInvocationTimeMs=1551142229076, firstInvocationTime='2019-02-25 19:50:29.076', lastHeartbeatMillis=0, lastHeartbeatTime='1969-12-31 19:00:00.000', target=[127.0.0.1]:5701, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=MockConnection{localEndpoint=[127.0.0.1]:5705, remoteEndpoint=[127.0.0.1]:5701}}, Reason: com.hazelcast.cp.exception.NotLeaderException: CPMember{uuid=b608e906-7d85-4a0d-863a-cf68a122ddb6, address=[127.0.0.1]:5701} is not LEADER of CPGroupId{name='METADATA', seed=1551142217525, commitIndex=0}. Known leader is: CPMember{uuid=793217b1-105b-4b34-9eb2-98d27ebf72c9, address=[127.0.0.1]:5704}
19:51:04,165  WARN |testMetadataGroupReinitializationAfterLostMajority| - [Invocation] hz._hzInstance_9057_dev.response-0 - [127.0.0.1]:5705 [dev] [3.12-SNAPSHOT] Retrying invocation: Invocation{op=com.hazelcast.cp.internal.operation.RaftQueryOp{serviceName='hz:core:raft', identityHash=381234731, partitionId=109, replicaIndex=0, callId=2689, invocationTime=1551142264164 (2019-02-25 19:51:04.164), waitTimeout=-1, callTimeout=60000, op=com.hazelcast.cp.internal.raftop.metadata.GetRaftGroupOp{serviceName='hz:core:raft', targetGroupId=CPGroupId{name='METADATA', seed=1551142217525, commitIndex=0}}, groupId=CPGroupId{name='METADATA', seed=1551142217525, commitIndex=0}, policy=LEADER_LOCAL}, tryCount=250, tryPauseMillis=500, invokeCount=110, callTimeoutMillis=60000, firstInvocationTimeMs=1551142229076, firstInvocationTime='2019-02-25 19:50:29.076', lastHeartbeatMillis=0, lastHeartbeatTime='1969-12-31 19:00:00.000', target=[127.0.0.1]:5701, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=MockConnection{localEndpoint=[127.0.0.1]:5705, remoteEndpoint=[127.0.0.1]:5701}}, Reason: com.hazelcast.cp.exception.NotLeaderException: CPMember{uuid=b608e906-7d85-4a0d-863a-cf68a122ddb6, address=[127.0.0.1]:5701} is not LEADER of CPGroupId{name='METADATA', seed=1551142217525, commitIndex=0}. Known leader is: CPMember{uuid=793217b1-105b-4b34-9eb2-98d27ebf72c9, address=[127.0.0.1]:5704}
19:51:05,653  WARN |testMetadataGroupReinitializationAfterLostMajority| - [Invocation] hz._hzInstance_9057_dev.response-1 - [127.0.0.1]:5705 [dev] [3.12-SNAPSHOT] Retrying invocation: Invocation{op=com.hazelcast.cp.internal.operation.RaftQueryOp{serviceName='hz:core:raft', identityHash=1066055055, partitionId=109, replicaIndex=0, callId=2785, invocationTime=1551142265652 (2019-02-25 19:51:05.652), waitTimeout=-1, callTimeout=60000, op=com.hazelcast.cp.internal.raftop.metadata.GetRaftGroupOp{serviceName='hz:core:raft', targetGroupId=CPGroupId{name='METADATA', seed=1551142217525, commitIndex=0}}, groupId=CPGroupId{name='METADATA', seed=1551142217525, commitIndex=0}, policy=LEADER_LOCAL}, tryCount=250, tryPauseMillis=500, invokeCount=100, callTimeoutMillis=60000, firstInvocationTimeMs=1551142231078, firstInvocationTime='2019-02-25 19:50:31.078', lastHeartbeatMillis=0, lastHeartbeatTime='1969-12-31 19:00:00.000', target=[127.0.0.1]:5704, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=MockConnection{localEndpoint=[127.0.0.1]:5705, remoteEndpoint=[127.0.0.1]:5704}}, Reason: com.hazelcast.cp.internal.exception.MetadataRaftGroupInitInProgressException
19:51:05,662  WARN |testMetadataGroupReinitializationAfterLostMajority| - [Invocation] hz._hzInstance_9057_dev.response-0 - [127.0.0.1]:5705 [dev] [3.12-SNAPSHOT] Retrying invocation: Invocation{op=com.hazelcast.cp.internal.operation.RaftQueryOp{serviceName='hz:core:raft', identityHash=706338428, partitionId=109, replicaIndex=0, callId=2798, invocationTime=1551142265662 (2019-02-25 19:51:05.662), waitTimeout=-1, callTimeout=60000, op=com.hazelcast.cp.internal.raftop.metadata.GetRaftGroupOp{serviceName='hz:core:raft', targetGroupId=CPGroupId{name='METADATA', seed=1551142217525, commitIndex=0}}, groupId=CPGroupId{name='METADATA', seed=1551142217525, commitIndex=0}, policy=LEADER_LOCAL}, tryCount=250, tryPauseMillis=500, invokeCount=120, callTimeoutMillis=60000, firstInvocationTimeMs=1551142225572, firstInvocationTime='2019-02-25 19:50:25.572', lastHeartbeatMillis=0, lastHeartbeatTime='1969-12-31 19:00:00.000', target=[127.0.0.1]:5704, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=MockConnection{localEndpoint=[127.0.0.1]:5705, remoteEndpoint=[127.0.0.1]:5704}}, Reason: com.hazelcast.cp.internal.exception.MetadataRaftGroupInitInProgressException
19:51:06,168  WARN |testMetadataGroupReinitializationAfterLostMajority| - [Invocation] hz._hzInstance_9057_dev.response-1 - [127.0.0.1]:5705 [dev] [3.12-SNAPSHOT] Retrying invocation: Invocation{op=com.hazelcast.cp.internal.operation.RaftQueryOp{serviceName='hz:core:raft', identityHash=1066055055, partitionId=109, replicaIndex=0, callId=2858, invocationTime=1551142266168 (2019-02-25 19:51:06.168), waitTimeout=-1, callTimeout=60000, op=com.hazelcast.cp.internal.raftop.metadata.GetRaftGroupOp{serviceName='hz:core:raft', targetGroupId=CPGroupId{name='METADATA', seed=1551142217525, commitIndex=0}}, groupId=CPGroupId{name='METADATA', seed=1551142217525, commitIndex=0}, policy=LEADER_LOCAL}, tryCount=250, tryPauseMillis=500, invokeCount=110, callTimeoutMillis=60000, 
```
