### ISSUE TITLE
NullPointerException at CollectionContainer.destroy()  at java.util.HashSet.clear(HashSet.java:244)

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#14572]
multi version client compat test's have started to faile.

http://jenkins.hazelcast.com/view/multi-version/job/multi-version-client-compat/5/console

```
java.lang.NullPointerException
	at java.util.HashSet.clear(HashSet.java:244)
	at com.hazelcast.collection.impl.set.SetContainer.onDestroy(SetContainer.java:118)
	at com.hazelcast.collection.impl.collection.CollectionContainer.destroy(CollectionContainer.java:340)
	at com.hazelcast.collection.impl.collection.CollectionService.destroyDistributedObject(CollectionService.java:93)
	at com.hazelcast.collection.impl.set.SetService.destroyDistributedObject(SetService.java:91)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyServiceImpl.destroyLocalDistributedObject(ProxyServiceImpl.java:182)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyServiceImpl.destroyDistributedObject(ProxyServiceImpl.java:169)
	at com.hazelcast.client.impl.protocol.task.DestroyProxyMessageTask.call(DestroyProxyMessageTask.java:40)
	at com.hazelcast.client.impl.protocol.task.AbstractCallableMessageTask.processMessage(AbstractCallableMessageTask.java:35)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:124)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:104)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:96)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:33)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:162)
	at com.hazelcast.client.spi.ClientProxy.destroyRemotely(ClientProxy.java:174)
	at com.hazelcast.client.spi.ProxyManager.destroyProxy(ProxyManager.java:367)
	at com.hazelcast.client.spi.ClientProxy.destroy(ClientProxy.java:146)
	at hzcmd.set.CreateUseDestroy.timeStep(CreateUseDestroy.java:14)
```

pwd
/disk1/jenkins/workspace/multi-version-client-compat/3.12-SNAPSHOT/2019_02_25-12_17_22/create-use-destroy-usa
[jenkins@ip-10-72-134-107 create-use-destroy-usa]$ cat ./clusterCaseA1/HZ/HzClient14HZ/out.txt

HazelcastClient 3.12-SNAPSHOT (20190222 - bb1dd64, b04e92c) is STARTING

**Comment by sancar** [comment]
It looks like there is a concurrency problem. 
`CollectionService.destroyDistributedObject` needs to be thread-safe. 
It seems, CollectionContainer.destroy and CollectionContainer.onDestroy violating thread-safety.

**Comment by Danny-Hazelcast** [comment]
@mmedenjak  this is a regression in 3.12

**Comment by Danny-Hazelcast** [comment]
http://jenkins.hazelcast.com/view/multi-version/job/multi-version-client-compat/8/console

clusterCase17/HZ/HzClient2HZ/exception.txt


/disk1/jenkins/workspace/multi-version-client-compat/3.12-SNAPSHOT/2019_03_01-00_42_30/create-use-destroy-usa

```
java.lang.NullPointerException
	at java.util.HashSet.clear(HashSet.java:244)
	at com.hazelcast.collection.impl.set.SetContainer.onDestroy(SetContainer.java:118)
	at com.hazelcast.collection.impl.collection.CollectionContainer.destroy(CollectionContainer.java:340)
	at com.hazelcast.collection.impl.collection.CollectionService.destroyDistributedObject(CollectionService.java:93)
	at com.hazelcast.collection.impl.set.SetService.destroyDistributedObject(SetService.java:91)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyServiceImpl.destroyLocalDistributedObject(ProxyServiceImpl.java:182)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyServiceImpl.destroyDistributedObject(ProxyServiceImpl.java:169)
	at com.hazelcast.client.impl.protocol.task.DestroyProxyMessageTask.call(DestroyProxyMessageTask.java:40)
	at com.hazelcast.client.impl.protocol.task.AbstractCallableMessageTask.processMessage(AbstractCallableMessageTask.java:35)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:124)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:104)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:95)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:32)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:155)
	at com.hazelcast.client.spi.ClientProxy.destroy(ClientProxy.java:118)
	at hzcmd.set.CreateUseDestroy.timeStep(CreateUseDestroy.java:14)
	at remote.bench.marker.MetricsMarker.flatOut(MetricsMarker.java:53)
	at remote.bench.marker.MetricsMarker.bench(MetricsMarker.java:40)
	at remote.bench.BenchThread.call(BenchThread.java:41)
	at remote.bench.BenchThread.call(BenchThread.java:14)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by mustafaiman** [comment]
The issue is caused by running "set destroy" operation on calling thread(when local instance is the owner) or generic thread(when remote instance is the owner) rather than partition thread. We could delegate the operation from generic thread to partition thread as in here: 
https://github.com/hazelcast/hazelcast/pull/14677

The same technique is applied in LockService(https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/concurrent/lock/LockServiceImpl.java#L344) too.

However that leads to losing the guarantee that distributed object is destroyed once destroy method returns. Operation in partition thread may be executed later. Also we do not want to wait partition operation execution on generic thread because waiting in generic threads is not permitted. (However, I think MapService waits partition destroy operations on generic thread)

So I think this should be handled properly at once for all data structures.

**Comment by mmedenjak** [comment]
Thanks for the analysis @mustafaiman ! I'll open a PRD if there isn't any tomorrow to address this systematically.

**Comment by Danny-Hazelcast** [comment]
this is only related to 3.X.X  not 4.0

**Comment by Danny-Hazelcast** [comment]
```
23:10:37 /disk1/jenkins/workspace/kill-All/3.12.9/2020_08_11-10_14_42/stable/destroy/create-use-destroy Failed
23:10:37 fail HzClient4HZ _create-use-destroy_createUseDestroy_set hzcmd.set.CreateUseDestroy threadId=0 java.lang.NullPointerException [0m
23:10:37 http://54.147.27.51/~jenkins/workspace/kill-All/3.12.9/2020_08_11-10_14_42/stable/destroy/create-use-destroy
```

(base) [jenkins@ip-10-72-134-107 create-use-destroy]$ pwd
/disk1/jenkins/workspace/kill-All/3.12.9/2020_08_11-10_14_42/stable/destroy/create-use-destroy

```
(base) [jenkins@ip-10-72-134-107 create-use-destroy]$ cat output/HZ/HzClient4HZ/exception.txt
java.lang.NullPointerException
	at java.util.HashSet.clear(HashSet.java:244)
	at com.hazelcast.collection.impl.set.SetContainer.onDestroy(SetContainer.java:118)
	at com.hazelcast.collection.impl.collection.CollectionContainer.destroy(CollectionContainer.java:340)
	at com.hazelcast.collection.impl.collection.CollectionService.destroyDistributedObject(CollectionService.java:93)
	at com.hazelcast.collection.impl.set.SetService.destroyDistributedObject(SetService.java:91)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyServiceImpl.destroyLocalDistributedObject(ProxyServiceImpl.java:188)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyServiceImpl.destroyDistributedObject(ProxyServiceImpl.java:175)
	at com.hazelcast.client.impl.protocol.task.DestroyProxyMessageTask.call(DestroyProxyMessageTask.java:40)
	at com.hazelcast.client.impl.protocol.task.AbstractCallableMessageTask.processMessage(AbstractCallableMessageTask.java:35)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:137)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:96)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:33)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:163)
	at com.hazelcast.client.spi.ClientProxy.destroyRemotely(ClientProxy.java:174)
	at com.hazelcast.client.spi.ProxyManager.destroyProxy(ProxyManager.java:364)
	at com.hazelcast.client.spi.ClientProxy.destroy(ClientProxy.java:146)
	at hzcmd.set.CreateUseDestroy.timeStep(CreateUseDestroy.java:14)
	at remote.bench.marker.MetricsMarker.flatOut(MetricsMarker.java:53)
	at remote.bench.marker.MetricsMarker.bench(MetricsMarker.java:40)
	at remote.bench.BenchThread.call(BenchThread.java:41)
	at remote.bench.BenchThread.call(BenchThread.java:14)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
