### ISSUE TITLE
RestCluster & RestClusterMultiEndpoint test failures on Windows 

### ISSUE THREAD

**Issue by tkountis** [hazelcast/hazelcast#14608]
Build: http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-Windows-OracleJDK8/11/testReport/

- com.hazelcast.internal.ascii.RestClusterMultiendpointTest.fail_with_deactivatedHealthCheck
- com.hazelcast.internal.ascii.RestClusterTest.fail_with_deactivatedHealthCheck

```
java.lang.Exception: Unexpected exception, expected<java.net.SocketException> but was<org.apache.http.NoHttpResponseException>
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:28)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.http.NoHttpResponseException: The target server failed to respond
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:143)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:260)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:161)
	at sun.reflect.GeneratedMethodAccessor159.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.http.impl.conn.CPoolProxy.invoke(CPoolProxy.java:138)
```

-----

- com.hazelcast.internal.ascii.RestClusterMultiendpointTest.testDisabledRest
- com.hazelcast.internal.ascii.RestClusterTest.testDisabledRest

```
org.apache.http.NoHttpResponseException: The target server failed to respond
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:143)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:260)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:161)
	at sun.reflect.GeneratedMethodAccessor159.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.http.impl.conn.CPoolProxy.invoke(CPoolProxy.java:138)
	at com.sun.proxy.$Proxy141.receiveResponseHeader(Unknown Source)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:271)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:253)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:194)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:85)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
	at com.hazelcast.internal.ascii.HTTPCommunicator.doGet(HTTPCommunicator.java:406)
	at com.hazelcast.internal.ascii.HTTPCommunicator.getClusterInfo(HTTPCommunicator.java:154)
	at com.hazelcast.internal.ascii.RestClusterTest.testDisabledRest(RestClusterTest.java:92)```

**Comment by tezc** [comment]
looks similar : https://github.com/hazelcast/hazelcast/issues/14470

**Comment by tkountis** [comment]
Thanks, closing as duplicate.
