### ISSUE TITLE
ThreadDumpRequestTest.testThreadDumpRequest

### ISSUE THREAD

**Issue by tezc** [hazelcast/hazelcast#14600]
_maintenance_ (commit 5445d5de6b5290a467fb185c8291f6be8b3b4e31)

Failed on OracleJDK7 : http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.maintenance-OracleJDK7/11/testReport/junit/com.hazelcast.internal.management/ThreadDumpRequestTest/testThreadDumpRequest/

**Stacktrace**
```
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.internal.management.ThreadDumpRequestTest.testThreadDumpRequest(ThreadDumpRequestTest.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by tezc** [comment]
Bug in JDK
```
00:25:46,635 ERROR |testThreadDumpRequest| - [ThreadDumpOperation] testThreadDumpRequest - [127.0.0.1]:5701 [dev] [3.11.3-SNAPSHOT] null
java.lang.NullPointerException
	at java.lang.management.ThreadInfo.<init>(ThreadInfo.java:168) ~[?:1.7.0_80]
	at sun.management.ThreadImpl.dumpThreads0(Native Method) ~[?:1.7.0_80]
	at sun.management.ThreadImpl.dumpAllThreads(ThreadImpl.java:446) ~[?:1.7.0_80]
	at com.hazelcast.internal.management.ThreadDumpGenerator.getAllThreads(ThreadDumpGenerator.java:77) ~[classes/:?]
	at com.hazelcast.internal.management.ThreadDumpGenerator.dumpAllThreads(ThreadDumpGenerator.java:40) ~[classes/:?]
	at com.hazelcast.internal.management.operation.ThreadDumpOperation.run(ThreadDumpOperation.java:36) ~[classes/:?]
	at com.hazelcast.spi.Operation.call(Operation.java:170) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:208) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:197) [classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:407) [classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:434) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:586) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:571) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:530) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:220) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.invokeOnTarget(OperationServiceImpl.java:325) [classes/:?]
	at com.hazelcast.internal.management.ManagementCenterService.callOnAddress(ManagementCenterService.java:256) [classes/:?]
	at com.hazelcast.internal.management.ManagementCenterService.callOnThis(ManagementCenterService.java:260) [classes/:?]
	at com.hazelcast.internal.management.request.ThreadDumpRequest.writeResponse(ThreadDumpRequest.java:51) [classes/:?]
	at com.hazelcast.internal.management.ThreadDumpRequestTest.testThreadDumpRequest(ThreadDumpRequestTest.java:56) [test-classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_80]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_80]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_80]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_80]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.12.jar:4.12]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) [junit-4.12.jar:4.12]
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106) [test-classes/:?]
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98) [test-classes/:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_80]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_80]
```

**Comment by tezc** [comment]
Closing until it occurs again.
