### ISSUE TITLE
error at cache population with custom partition strategy

### ISSUE THREAD

**Issue by dsukhoroslov** [hazelcast/hazelcast#14602]
HZ 3.11.2, I configured a custom partitioning strategy for my cache. The strategy is pretty simple, it splits string keys of XXXX.XXXXXX.XXXX format to 3 parts by dots and returns the first part as partition key. Then I connected a MapLoader to my cache and got the following exception at cache population:
```

java.lang.IllegalStateException: MapLoader loaded an item belongs to a different partition
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.isKeyAndValueLoadable(DefaultRecordStore.java:979)
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.putFromLoadInternal(DefaultRecordStore.java:909)
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.putFromLoad(DefaultRecordStore.java:900)
	at com.hazelcast.map.impl.operation.PutFromLoadAllOperation.run(PutFromLoadAllOperation.java:71)
	at com.hazelcast.spi.Operation.call(Operation.java:170)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:208)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:197)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:147)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:125)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:110)
```
Please have a look,
Thanks, Denis

**Comment by mmedenjak** [comment]
Hi @dsukhoroslov ! Thank you for the report. I assume this is because the map loader does not take into account the custom partitioning strategy. I'll add this to the next release as we are just about to release 4.0 which was mostly focusing on cleaning up technical debt and improving the design in several areas.
