### ISSUE TITLE
Client side yaml config is `not` loaded

### ISSUE THREAD

**Issue by lazerion** [hazelcast/hazelcast#14613]
Configuration passed with `JAVA_OPTS=-Dhazelcast.client.config=/configFolder/hazelcast-client.yaml`

And configuration is below
```
# Client side YAML config

hazelcast-client:
  group:
    name: hz-icmp
    password: s3crEt
  properties:
    hazelcast.logging.type: true
    hazelcast.client.shuffle.member.list: false

  network:
    icmp-ping:
      enabled: true
      timeout-milliseconds: 100
      interval-milliseconds: 1000
      ttl: 255
      max-attempts: 2
      echo-fail-fast-on-startup: true
    cluster-members:
      - hazelcast:5701
    socket-options:
      linger-seconds: 0
    redo-operation: true
```
client instance is created as below
```
YamlClientConfigLocator yamlClientConfigLocator = new YamlClientConfigLocator();
        if (yamlClientConfigLocator.isConfigPresent()) {
            config = new YamlClientConfigBuilder().build();
        } else {
            config = new XmlClientConfigBuilder().build();
        }

        config.setProperty("hazelcast.client.connection.strategy.classname", RecordingStrategy.class.getName());
        client = HazelcastClient.newHazelcastClient(config);
        nanny.run(client);
```
However, issue seems not related with above config, as discussed with @blazember client side locator is not loading yaml, and uses default config xml as can be deducted from below logs

```
2019-02-28T15:24:25.808212806Z Feb 28, 2019 3:24:25 PM com.hazelcast.config.AbstractConfigLocator
2019-02-28T15:24:25.808273913Z INFO: Loading 'hazelcast-client-default.xml' from the classpath.
...
Trying to connect to [127.0.0.1]:5701 as owner member
...
2019-02-28T15:24:29.708503302Z Exception in thread "main" java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@7bd7d6d6 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@43f02ef2[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
2019-02-28T15:24:29.709074652Z 	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
2019-02-28T15:24:29.709157577Z 	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
2019-02-28T15:24:29.709434452Z 	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326)
2019-02-28T15:24:29.709627233Z 	at java.util.concurrent.ScheduledThreadPoolExecutor.scheduleWithFixedDelay(ScheduledThreadPoolExecutor.java:597)
2019-02-28T15:24:29.709641738Z 	at java.util.concurrent.Executors$DelegatedScheduledExecutorService.scheduleWithFixedDelay(Executors.java:738)
2019-02-28T15:24:29.709847454Z 	at com.hazelcast.client.spi.impl.listener.SmartClientListenerService.start(SmartClientListenerService.java:43)
2019-02-28T15:24:29.709863488Z 	at com.hazelcast.client.impl.clientside.HazelcastClientInstanceImpl.start(HazelcastClientInstanceImpl.java:405)
...
```

**Comment by lazerion** [comment]
I am closing the issue. 
I will transfer below to config files
```
config.setProperty("hazelcast.client.connection.strategy.classname", RecordingStrategy.class.getName());
```
But, IIUC, there is no **mixed** programatic and declarative configuration possible w/out directly knowing the configuration type.
