### ISSUE TITLE
 Hazelcast Node Disconnection/Join Makes unstable the system - Hazelcast version - -3.10.2 

### ISSUE THREAD

**Issue by esakki2092** [hazelcast/hazelcast#14642]
Hi,
    We are using Hazelcast for our production cluster environment. Here we are facing issues with hazelcast and it makes system become unstable. So that we are restarting whole cluster environment.
      Please help us to solve the issues. find the following error details which printed by hazelcast.

PFA - Hazelcast configuration xml

Hazelcast Node Splitting Log:

=====================

    Jan 31, 2019 5:27:41 AM com.hazelcast.nio.tcp.TcpIpConnector
    INFO: [172.30.6.21]:5750 [Cluster_Main] [3.10.2] Connecting to /172.30.6.24:5750, timeout: 0, bind-any: true
    Jan 31, 2019 5:27:41 AM com.hazelcast.nio.tcp.TcpIpConnectionManager
    INFO: [172.30.6.21]:5750 [Cluster_Main] [3.10.2] Established socket connection between /172.30.6.21:33664 and /172.30.6.24:5750
    Jan 31, 2019 5:27:41 AM com.hazelcast.nio.tcp.TcpIpConnection
    INFO: [172.30.6.21]:5750 [Cluster_Main] [3.10.2] Connection[id=43, /172.30.6.21:33054->/172.30.6.15:5750, endpoint=[172.30.6.15]:5750, alive=false, type=MEMBER] closed. Reason: Member left event received
    from master
    Jan 31, 2019 5:27:41 AM com.hazelcast.nio.tcp.TcpIpConnector
    INFO: [172.30.6.21]:5750 [Cluster_Main] [3.10.2] Connecting to /172.30.6.15:5750, timeout: 0, bind-any: true
    Jan 31, 2019 5:27:41 AM com.hazelcast.nio.tcp.TcpIpConnection
    INFO: [172.30.6.21]:5750 [Cluster_Main] [3.10.2] Connection[id=44, /172.30.6.21:33664->/172.30.6.24:5750, endpoint=[172.30.6.24]:5750, alive=false, type=MEMBER] closed. Reason: Member left event received
    from master
    Jan 31, 2019 5:27:41 AM com.hazelcast.transaction.TransactionManagerService
    INFO: [172.30.6.21]:5750 [Cluster_Main] [3.10.2] Committing/rolling-back alive transactions of Member [172.30.6.15]:5750 - 27e9b3aa-f12d-46e9-8e15-4bb2ba0b5695, UUID: 27e9b3aa-f12d-46e9-8e15-4bb2ba0b5695
    Jan 31, 2019 5:27:41 AM com.hazelcast.nio.tcp.TcpIpConnectionManager
    INFO: [172.30.6.21]:5750 [Cluster_Main] [3.10.2] Established socket connection between /172.30.6.21:56290 and /172.30.6.15:5750
    Jan 31, 2019 5:27:41 AM com.hazelcast.internal.partition.InternalPartitionService
    INFO: [172.30.6.21]:5750 [Cluster_Main] [3.10.2] Fetching most recent partition table! my version: 6964
    Jan 31, 2019 5:27:41 AM com.hazelcast.internal.partition.InternalPartitionService
    INFO: [172.30.6.21]:5750 [Cluster_Main] [3.10.2] Most recent partition table version: 6964
    Jan 31, 2019 5:27:41 AM com.hazelcast.nio.tcp.TcpIpConnection
    INFO: [172.30.6.21]:5750 [Cluster_Main] [3.10.2] Connection[id=39, /172.30.6.21:52259->/172.30.6.17:5750, endpoint=[172.30.6.17]:5750, alive=false, type=MEMBER] closed. Reason: Member left event received
    from master
    Jan 31, 2019 5:27:41 AM com.hazelcast.transaction.TransactionManagerService
    INFO: [172.30.6.21]:5750 [Cluster_Main] [3.10.2] Committing/rolling-back alive transactions of Member [172.30.6.24]:5750 - 54fe042b-5e6f-4d73-bc27-d2015c5632b4, UUID: 54fe042b-5e6f-4d73-bc27-d2015c5632b4
    Jan 31, 2019 5:27:41 AM com.hazelcast.nio.tcp.TcpIpConnection
    INFO: [172.30.6.21]:5750 [Cluster_Main] [3.10.2] Connection[id=37, /172.30.6.21:5750->/172.30.6.13:42570, endpoint=[172.30.6.13]:5750, alive=false, type=MEMBER] closed. Reason: Member left event received from master
    Jan 31, 2019 5:27:41 AM com.hazelcast.transaction.TransactionManagerService
    INFO: [172.30.6.21]:5750 [Cluster_Main] [3.10.2] Committing/rolling-back alive transactions of Member [172.30.6.17]:5750 - 74f77c7f-93ec-4698-87a9-b0795b8db433, UUID: 74f77c7f-93ec-4698-87a9-b0795b8db433
    Jan 31, 2019 5:27:41 AM com.hazelcast.internal.cluster.ClusterService
    INFO: [172.30.6.21]:5750 [Cluster_Main] [3.10.2]

After Some time the following exceptions keep on printing.
Log 1:

    	at com.hazelcast.concurrent.lock.LockStoreContainer$1.createNew(LockStoreContainer.java:58)
    	at com.hazelcast.concurrent.lock.LockStoreContainer$1.createNew(LockStoreContainer.java:45)
    	at com.hazelcast.util.ConcurrencyUtil.getOrPutIfAbsent(ConcurrencyUtil.java:107)
    	at com.hazelcast.concurrent.lock.LockStoreContainer.getOrCreateLockStore(LockStoreContainer.java:75)
    	at com.hazelcast.concurrent.lock.LockServiceImpl.getLockStore(LockServiceImpl.java:175)
    	at com.hazelcast.concurrent.lock.operations.AbstractLockOperation.getLockStore(AbstractLockOperation.java:88)
    	at com.hazelcast.concurrent.lock.operations.LockOperation.shouldWait(LockOperation.java:82)
    	at com.hazelcast.spi.Operation.call(Operation.java:143)
    	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:202)
    	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:191)
    	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:405)
    	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:115)
    	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:100)
    	at ------ submitted from ------.(Unknown Source)
    	at java.lang.Thread.getStackTrace(Thread.java:1144)
    	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:127)
    	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:79)
    	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:162)
    	at com.hazelcast.concurrent.lock.LockProxySupport.tryLock(LockProxySupport.java:138)
    	at com.hazelcast.map.impl.proxy.MapProxyImpl.tryLock(MapProxyImpl.java:378)

Log 2: It is keep on printing. why it is printing. Is there any internal process going? whether some other issue leads this info log.

    Mar 02, 2019 10:45:21 PM com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor
    INFO: [172.30.6.13]:5750 [Cluster_Main] [3.10.2] Invocations:126 timeouts:0 backup-timeouts:8
    Mar 02, 2019 10:45:22 PM com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor
    INFO: [172.30.6.13]:5750 [Cluster_Main] [3.10.2] Invocations:126 timeouts:0 backup-timeouts:5
    Mar 02, 2019 10:45:23 PM com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor
    INFO: [172.30.6.13]:5750 [Cluster_Main] [3.10.2] Invocations:129 timeouts:0 backup-timeouts:9
    Mar 02, 2019 10:45:24 PM com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor
    INFO: [172.30.6.13]:5750 [Cluster_Main] [3.10.2] Invocations:125 timeouts:0 backup-timeouts:1
    Mar 02, 2019 10:45:25 PM com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor
    INFO: [172.30.6.13]:5750 [Cluster_Main] [3.10.2] Invocations:126 timeouts:0 backup-timeouts:7
    Mar 02, 2019 10:45:26 PM com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor
    INFO: [172.30.6.13]:5750 [Cluster_Main] [3.10.2] Invocations:121 timeouts:0 backup-timeouts:2

**Comment by burakcelebi** [comment]
Hi @esakki2092, looks like a network issue but this is just speculation without the configuration file & logs from all members. 

If you did not solve the problem, would it be possible to use Hazelcast google groups mailing list for these kinds of issues? I believe you will get a faster response.
