### ISSUE TITLE
HazelcastSerializationException: ClassNotFoundException for classes available after upgrading to OpenJDK 11

### ISSUE THREAD

**Issue by wemu** [hazelcast/hazelcast#14684]
hello

I'm using hazelcast 3.11.1 and spring boot 2.1.3 in an embedded mode (standalone application, no cluster), all worked nicely. I only use the spring cache annotations and the spring boot auto-configuration. no xml config file.

i recently upgraded from jdk 8 to openjdk 11 and now the logs show weird exceptions (the spring context starts normally):

```
com.hazelcast.nio.serialization.HazelcastSerializationException: com.hazelcast.nio.serialization.HazelcastSerializationException: java.lang.ClassNotFoundException: ch.mobi.mobitor.plugin.teamcity.service.client.domain.BuildsResponse
            at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:na]
            at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:na]
            at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:na]
            at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[na:na]
            at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:600) ~[na:na]
            at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:678) ~[na:na]
            at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:737) ~[na:na]
            at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159) ~[na:na]
            at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173) ~[na:na]
            at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233) ~[na:na]
            at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[na:na]
            at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:661) ~[na:na]
            at ch.mobi.mobitor.plugin.teamcity.service.scheduling.TeamCityBuildStatusCollector.collectTeamCityBuildInformationForScreens(TeamCityBuildStatusCollector.java:80) ~[mobitor-plugin-teamcity-3.0.1.jar:3.0.1]
            at ch.mobi.mobitor.plugin.teamcity.service.scheduling.TeamCityBuildStatusCollector$$FastClassBySpringCGLIB$$2a2e806f.invoke(<generated>) ~[mobitor-plugin-teamcity-3.0.1.jar:3.0.1]
            at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.1.5.RELEASE.jar:5.1.5.RELEASE]
            at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749) ~[spring-aop-5.1.5.RELEASE.jar:5.1.5.RELEASE]
            at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.1.5.RELEASE.jar:5.1.5.RELEASE]
            at org.springframework.cache.interceptor.CacheInterceptor.lambda$invoke$0(CacheInterceptor.java:53) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
            at org.springframework.cache.interceptor.CacheAspectSupport.invokeOperation(CacheAspectSupport.java:365) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
            at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:420) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
            at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:345) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
            at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:61) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
            at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.5.RELEASE.jar:5.1.5.RELEASE]
            at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688) ~[spring-aop-5.1.5.RELEASE.jar:5.1.5.RELEASE]
            at ch.mobi.mobitor.plugin.teamcity.service.scheduling.TeamCityBuildStatusCollector$$EnhancerBySpringCGLIB$$2ba02680.collectTeamCityBuildInformationForScreens(<generated>) ~[mobitor-plugin-teamcity-3.0.1.jar:3.0.1]
            at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
            at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
            at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
            at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
            at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
            at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
            at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
            at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[na:na]
            at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
            at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
            at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
            at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Caused by: com.hazelcast.nio.serialization.HazelcastSerializationException: java.lang.ClassNotFoundException: ch.mobi.mobitor.plugin.teamcity.service.client.domain.BuildsResponse
            at com.hazelcast.internal.serialization.impl.JavaDefaultSerializers$JavaSerializer.read(JavaDefaultSerializers.java:86) ~[hazelcast-3.11.1.jar:3.11.1]
            at com.hazelcast.internal.serialization.impl.JavaDefaultSerializers$JavaSerializer.read(JavaDefaultSerializers.java:75) ~[hazelcast-3.11.1.jar:3.11.1]
            at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48) ~[hazelcast-3.11.1.jar:3.11.1]
            at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:187) ~[hazelcast-3.11.1.jar:3.11.1]
            at com.hazelcast.map.impl.proxy.MapProxySupport.toObject(MapProxySupport.java:1245) ~[hazelcast-3.11.1.jar:3.11.1]
            at com.hazelcast.map.impl.proxy.MapProxyImpl.get(MapProxyImpl.java:120) ~[hazelcast-3.11.1.jar:3.11.1]
            at com.hazelcast.spring.cache.HazelcastCache.lookup(HazelcastCache.java:162) ~[hazelcast-spring-3.11.1.jar:3.11.1]
            at com.hazelcast.spring.cache.HazelcastCache.get(HazelcastCache.java:67) ~[hazelcast-spring-3.11.1.jar:3.11.1]
            at org.springframework.cache.interceptor.AbstractCacheInvoker.doGet(AbstractCacheInvoker.java:73) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
            at org.springframework.cache.interceptor.CacheAspectSupport.findInCaches(CacheAspectSupport.java:554) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
            at org.springframework.cache.interceptor.CacheAspectSupport.findCachedItem(CacheAspectSupport.java:519) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
            at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:401) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
            at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:345) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
            at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:61) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
            at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.5.RELEASE.jar:5.1.5.RELEASE]
            at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688) ~[spring-aop-5.1.5.RELEASE.jar:5.1.5.RELEASE]
            at ch.mobi.mobitor.plugin.teamcity.service.client.TeamCityClient$$EnhancerBySpringCGLIB$$9a349235.retrieveBuildInformation(<generated>) ~[mobitor-plugin-teamcity-3.0.1.jar:3.0.1]
            at ch.mobi.mobitor.plugin.teamcity.service.client.TeamCityInformationProviderService.updateBuildInformation(TeamCityInformationProviderService.java:108) ~[mobitor-plugin-teamcity-3.0.1.jar:3.0.1]
            at java.base/java.util.ArrayList.forEach(ArrayList.java:1540) ~[na:na]
            at ch.mobi.mobitor.plugin.teamcity.service.scheduling.TeamCityBuildStatusCollector.populateBuildInformation(TeamCityBuildStatusCollector.java:91) ~[mobitor-plugin-teamcity-3.0.1.jar:3.0.1]
            at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[na:na]
            at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654) ~[na:na]
            at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[na:na]
            at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290) ~[na:na]
            at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746) ~[na:na]
            at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[na:na]
            at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[na:na]
            at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[na:na]
            at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[na:na]
            at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177) ~[na:na]
Caused by: java.lang.ClassNotFoundException: ch.mobi.mobitor.plugin.teamcity.service.client.domain.BuildsResponse
            at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583) ~[na:na]
            at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[na:na]
            at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[na:na]
            at com.hazelcast.nio.ClassLoaderUtil.tryLoadClass(ClassLoaderUtil.java:288) ~[hazelcast-3.11.1.jar:3.11.1]
            at com.hazelcast.nio.ClassLoaderUtil.loadClass(ClassLoaderUtil.java:252) ~[hazelcast-3.11.1.jar:3.11.1]
            at com.hazelcast.nio.IOUtil$ClassLoaderAwareObjectInputStream.resolveClass(IOUtil.java:646) ~[hazelcast-3.11.1.jar:3.11.1]
            at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1886) ~[na:na]
            at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1772) ~[na:na]
            at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2060) ~[na:na]
            at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1594) ~[na:na]
            at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:430) ~[na:na]
            at com.hazelcast.internal.serialization.impl.JavaDefaultSerializers$JavaSerializer.read(JavaDefaultSerializers.java:82) ~[hazelcast-3.11.1.jar:3.11.1]
            ... 29 common frames omitted
```

the missing class it complains about: `ClassNotFoundException: ch.mobi.mobitor.plugin.teamcity.service.client.domain.BuildsResponse` is in the classpath.

There are exceptions for other classes as well (very similar to this one). The complained classes are part of a dependency.

I don't know why this happens or why there seems to be a classloader issue. The openjdk 11 upgrade might be a bit too much but I can't find why this is happening.

any hints would be cool!

**Comment by wemu** [comment]
I found a hazelcast config in the spring-boot app that might have caused this (not sure why), after I deleted this config the serializer exception above disappeared. (the config was to play around anyway). Not sure whats the connection between this config and the exception. Probably something is missing. Still weird this came up only with jdk 11

`
import com.hazelcast.config.Config;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration
public class HazelcastCacheConfiguration {

    @Bean
    public Config config() {
        Config config = new Config();
        config.setInstanceName("my-special-hazelcache");

        config.setProperty("hazelcast.phone.home.enabled", "false");

        return config;
    }
}

`

**Comment by mesutcelik** [comment]
Hi @wemu ,

I just tried both with jdk 8 and jdk 11 and saw no issue with official [Spring Cache Guide](https://spring.io/guides/gs/caching/).
I am glad it worked for you too.

I am actually not sure the purpose of `HazelcastCacheConfiguration` but as you said it was for playing around. I assume you have another Hazelcast Config Bean somewhere like below at its simplest version so you deleted that `HazelcastCacheConfiguration`.
```
    @Bean
    public Config hazelcastConfig(){
        return new Config();
    }
```

I think one Hazelcast Config bean is enough to use Hazelcast with all your caching annotations. 
Additionally, If you need direct access to Hazelcast Instance, you just need to autowire Hazelcast which gives you the option to interact with Hazelcast API directly.

```
    @Autowired
    HazelcastInstance hazelcastInstance;
```

I am closing the issue for now and please feel free to reopen if you still experience a problem.

**Comment by wemu** [comment]
hello

thanks for the reply! I am still not sure why adding my own config changed the classpath that hazelcast is using. I assume there are some defaults missing, so configuring the cache instance via the config beans seems to be sort of "wrong". But using the instance bean will probably work well. So I'm gonna follow that path :)

thanks a lot!
