### ISSUE TITLE
MapStoreConfig fails with "Transition not allowed from NOT_LOADED to LOADED" and intermittent NPE

### ISSUE THREAD

**Issue by kdubb** [hazelcast/hazelcast#14706]
Using 3.11.2 locally in a java application, and setting a map store configuration as follows

```java
    MapStoreConfig mapStoreConfig = new MapStoreConfig()
        .setEnabled(true)
        .setImplementation(messageStoreProcessor)
        .setInitialLoadMode(InitialLoadMode.EAGER)
        .setWriteDelaySeconds(messageStoreProcessor.getWriteBackDelaySeconds())
        .setWriteBatchSize(messageStoreProcessor.getWriteBackBatchSize());

    MaxSizeConfig maxSizeConfig = new MaxSizeConfig()
        .setMaxSizePolicy(MaxSizePolicy.FREE_HEAP_PERCENTAGE)
        .setSize(messageStoreProcessor.getFreeHeapPercentage());

    event.getConfig().addMapConfig(new MapConfig()
                                       .setName(OBJECT_NAME)
                                       .setBackupCount(1)
                                       .setAsyncBackupCount(1)
                                       .setReadBackupData(true)
                                       .setMapStoreConfig(mapStoreConfig)
                                       .setEvictionPolicy(EvictionPolicy.LRU)
                                       .setMaxSizeConfig(maxSizeConfig)
                                       .addMapIndexConfig(new MapIndexConfig("recipientDeviceKey", true)));
```

causes intermittent NPE's with the following stacktrace

```java
java.lang.NullPointerException: null
	at java.util.Objects.requireNonNull(Objects.java:221) ~[?:?]
	at java.util.concurrent.ConcurrentLinkedQueue.offer(ConcurrentLinkedQueue.java:355) ~[?:?]
	at java.util.concurrent.ConcurrentLinkedQueue.add(ConcurrentLinkedQueue.java:283) ~[?:?]
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.loadAllFromStore(DefaultRecordStore.java:1157) ~[hazelcast-3.11.2.jar:3.11.2]
	at com.hazelcast.map.impl.operation.LoadAllOperation.run(LoadAllOperation.java:60) ~[hazelcast-3.11.2.jar:3.11.2]
	at com.hazelcast.spi.Operation.call(Operation.java:170) [hazelcast-3.11.2.jar:3.11.2]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:208) [hazelcast-3.11.2.jar:3.11.2]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:197) [hazelcast-3.11.2.jar:3.11.2]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:413) [hazelcast-3.11.2.jar:3.11.2]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:153) [hazelcast-3.11.2.jar:3.11.2]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:123) [hazelcast-3.11.2.jar:3.11.2]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:110) [hazelcast-3.11.2.jar:3.11.2]
```

and numerous (~50 or so) `Transition not allowed from state NOT_LOADED to LOADED` with the following stack trace

```java
2019-03-15 10:31:41.787 ERROR 43244 --- [ration.thread-7] c.h.m.i.o.KeyLoadStatusOperation         : [localhost]:5701 [dev] [3.11.2] Transition not allowed from state NOT_LOADED to LOADED
java.lang.IllegalStateException: Transition not allowed from state NOT_LOADED to LOADED
	at com.hazelcast.util.Preconditions.checkState(Preconditions.java:355) ~[hazelcast-3.11.2.jar:3.11.2]
	at com.hazelcast.util.StateMachine.next(StateMachine.java:62) ~[hazelcast-3.11.2.jar:3.11.2]
	at com.hazelcast.util.StateMachine.nextOrStay(StateMachine.java:75) ~[hazelcast-3.11.2.jar:3.11.2]
	at com.hazelcast.map.impl.MapKeyLoader.trackLoading(MapKeyLoader.java:355) ~[hazelcast-3.11.2.jar:3.11.2]
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.updateLoadStatus(DefaultRecordStore.java:1168) ~[hazelcast-3.11.2.jar:3.11.2]
	at com.hazelcast.map.impl.operation.KeyLoadStatusOperation.run(KeyLoadStatusOperation.java:45) ~[hazelcast-3.11.2.jar:3.11.2]
	at com.hazelcast.spi.Operation.call(Operation.java:170) [hazelcast-3.11.2.jar:3.11.2]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:208) [hazelcast-3.11.2.jar:3.11.2]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:197) [hazelcast-3.11.2.jar:3.11.2]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:413) [hazelcast-3.11.2.jar:3.11.2]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:153) [hazelcast-3.11.2.jar:3.11.2]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:123) [hazelcast-3.11.2.jar:3.11.2]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:110) [hazelcast-3.11.2.jar:3.11.2]
```

at some point previously we're sure this wasn't an issue but now (reverting all the way back to 3.6.X) we still see the issue.

**Comment by ahmetmircik** [comment]
Do you have that same map store config across the nodes of cluster? Not identical configurations between nodes can be a cause.

**Comment by kdubb** [comment]
This is happening in our integration testing. So it's a single node.

It is running 2 separate instance of Hazelcast but they are handling different data structures.

**Comment by ahmetmircik** [comment]
Can you please check if those 2 instances are forming a cluster? If not, sharing a reproducer would be helpful.

**Comment by kdubb** [comment]
It seems they were forming a cluster.  I've set the group config of each instance to have separate names and passwords and that appears to solve the issue.

Is that the correct way to delineate instance clusters?

**Comment by ahmetmircik** [comment]
Yes it is. With groups, it is possible to create multiple clusters where each cluster has its own group and doesn't interfere with other clusters.

**Comment by kdubb** [comment]
Ok. It appears the issue was, as you said, different configurations on separate nodes because our setup was incorrectly allowing all nodes to join both clusters but wasn't setting them up the same. We, incorrectly, assumed instances automatically created separate clusters.
