### ISSUE TITLE
ClientMapIssueTest.testOperationNotBlockingAfterClusterShutdown

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#14707]
_master_ (commit a9c15ef4ac48beb25770d47412b7d684055da417)

Failed on nightly job: http://jenkins.hazelcast.com/job/Hazelcast-3.x-nightly/51/testReport/com.hazelcast.client.map/ClientMapIssueTest/testOperationNotBlockingAfterClusterShutdown/

Stacktrace:
```
java.lang.AssertionError: CountDownLatch failed to complete within 120 seconds, count left: 1
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:1190)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:1175)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:1163)
	at com.hazelcast.client.map.ClientMapIssueTest.testOperationNotBlockingAfterClusterShutdown(ClientMapIssueTest.java:158)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

Standard output:
```
Hiccups measured while running test 'testOperationNotBlockingAfterClusterShutdown(com.hazelcast.client.map.ClientMapIssueTest):'
22:18:00, accumulated pauses: 69 ms, max pause: 19 ms, pauses over 1000 ms: 0
22:18:05, accumulated pauses: 42 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:18:10, accumulated pauses: 31 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:18:15, accumulated pauses: 28 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:18:20, accumulated pauses: 28 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:18:25, accumulated pauses: 27 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:18:30, accumulated pauses: 28 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:18:35, accumulated pauses: 30 ms, max pause: 2 ms, pauses over 1000 ms: 0
22:18:40, accumulated pauses: 28 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:18:45, accumulated pauses: 27 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:18:50, accumulated pauses: 27 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:18:55, accumulated pauses: 33 ms, max pause: 3 ms, pauses over 1000 ms: 0
22:19:00, accumulated pauses: 28 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:19:05, accumulated pauses: 26 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:19:10, accumulated pauses: 26 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:19:15, accumulated pauses: 26 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:19:20, accumulated pauses: 27 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:19:25, accumulated pauses: 30 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:19:30, accumulated pauses: 28 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:19:35, accumulated pauses: 26 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:19:40, accumulated pauses: 27 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:19:45, accumulated pauses: 25 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:19:50, accumulated pauses: 27 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:19:55, accumulated pauses: 28 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:20:00, accumulated pauses: 268 ms, max pause: 243 ms, pauses over 1000 ms: 0
```

**Comment by blazember** [comment]
Can be reproduced easily in local. There are a few failures in every 10 runs.

After logging the exception from the catch block, this is how the Exception and the stack trace looks like in a successful run:
```
15:04:36,214  WARN |testOperationNotBlockingAfterClusterShutdown| - [ClusterConnectorService] hz.client_2.cluster- - hz.client_2 [dev] [3.12-SNAPSHOT] Unable to get live cluster connection, retry in 3000 ms, attempt 4 of 2147483647.
15:04:37,190  INFO |testOperationNotBlockingAfterClusterShutdown| - [ClientMapIssueTest] Thread-6 - ***** IGNORED: ClientInvocation{clientMessage = ClientMessage{connection=null, length=22, correlationId=45, operation=Map.get, messageType=102, partitionId=23, isComplete=false, isRetryable=true, isEvent=false, writeOffset=0}, objectName = 0091fbab-050e-4aa1-b037-91c1f2ef3925, target = partition 23, sendConnection = null} timed out because exception occurred after client invocation timeout 10000 ms. Current time: 2019-03-18 15:04:37.189. Start time: 2019-03-18 15:04:27.160. Total elapsed time: 10030 ms. 
com.hazelcast.core.OperationTimeoutException: ClientInvocation{clientMessage = ClientMessage{connection=null, length=22, correlationId=45, operation=Map.get, messageType=102, partitionId=23, isComplete=false, isRetryable=true, isEvent=false, writeOffset=0}, objectName = 0091fbab-050e-4aa1-b037-91c1f2ef3925, target = partition 23, sendConnection = null} timed out because exception occurred after client invocation timeout 10000 ms. Current time: 2019-03-18 15:04:37.189. Start time: 2019-03-18 15:04:27.160. Total elapsed time: 10030 ms. 
	at com.hazelcast.client.spi.impl.ClientInvocation.newOperationTimeoutException(ClientInvocation.java:333) ~[classes/:?]
	at com.hazelcast.client.spi.impl.ClientInvocation.notifyException(ClientInvocation.java:238) ~[classes/:?]
	at com.hazelcast.client.spi.impl.ClientInvocation.invokeOnSelection(ClientInvocation.java:173) ~[classes/:?]
	at com.hazelcast.client.spi.impl.ClientInvocation.retry(ClientInvocation.java:194) ~[classes/:?]
	at com.hazelcast.client.spi.impl.ClientInvocation.run(ClientInvocation.java:179) ~[classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_181]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_181]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_181]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_181]
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64) ~[classes/:?]
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80) ~[classes/:?]
	at ------ submitted from ------.(Unknown Source) ~[?:?]
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:96) ~[classes/:?]
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:33) ~[classes/:?]
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:163) ~[classes/:?]
	at com.hazelcast.client.spi.ClientProxy.invokeOnPartition(ClientProxy.java:225) ~[classes/:?]
	at com.hazelcast.client.spi.ClientProxy.invoke(ClientProxy.java:219) ~[classes/:?]
	at com.hazelcast.client.proxy.ClientMapProxy.getInternal(ClientMapProxy.java:324) ~[classes/:?]
	at com.hazelcast.client.proxy.ClientMapProxy.get(ClientMapProxy.java:318) ~[classes/:?]
	at com.hazelcast.client.map.ClientMapIssueTest$3.run(ClientMapIssueTest.java:160) [test-classes/:?]
Caused by: java.io.IOException: Owner connection is not available!
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.checkAllowed(ClientConnectionManagerImpl.java:312) ~[classes/:?]
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.getConnection(ClientConnectionManagerImpl.java:271) ~[classes/:?]
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.getOrTriggerConnect(ClientConnectionManagerImpl.java:262) ~[classes/:?]
	at com.hazelcast.client.spi.impl.SmartClientInvocationService.getOrTriggerConnect(SmartClientInvocationService.java:73) ~[classes/:?]
	at com.hazelcast.client.spi.impl.SmartClientInvocationService.invokeOnPartitionOwner(SmartClientInvocationService.java:48) ~[classes/:?]
	at com.hazelcast.client.spi.impl.ClientInvocation.invokeOnSelection(ClientInvocation.java:163) ~[classes/:?]
	at com.hazelcast.client.spi.impl.ClientInvocation.retry(ClientInvocation.java:194) ~[classes/:?]
	at com.hazelcast.client.spi.impl.ClientInvocation.run(ClientInvocation.java:179) ~[classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_181]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_181]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_181]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_181]
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64) ~[classes/:?]
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80) ~[classes/:?]
```
and this is a failed run:
```
15:04:49,908  WARN |testOperationNotBlockingAfterClusterShutdown| - [ClientPartitionService] Thread-8 - hz.client_3 [dev] [3.12-SNAPSHOT] Error while fetching cluster partition table!
java.util.concurrent.ExecutionException: com.hazelcast.core.OperationTimeoutException: ClientInvocation{clientMessage = ClientMessage{connection=null, length=22, correlationId=46, operation=Client.getPartitions, messageType=8, partitionId=-1, isComplete=true, isRetryable=false, isEvent=false, writeOffset=0}, objectName = null, target = random, sendConnection = null} timed out because exception occurred after client invocation timeout 10000 ms. Current time: 2019-03-18 15:04:49.907. Start time: 2019-03-18 15:04:39.878. Total elapsed time: 10029 ms. 
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:109) ~[classes/:?]
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:33) ~[classes/:?]
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:163) ~[classes/:?]
	at com.hazelcast.client.spi.impl.ClientPartitionServiceImpl.waitForPartitionsFetchedOnce(ClientPartitionServiceImpl.java:134) [classes/:?]
	at com.hazelcast.client.spi.impl.ClientPartitionServiceImpl.getPartitionOwner(ClientPartitionServiceImpl.java:184) [classes/:?]
	at com.hazelcast.client.spi.impl.SmartClientInvocationService.invokeOnPartitionOwner(SmartClientInvocationService.java:40) [classes/:?]
	at com.hazelcast.client.spi.impl.ClientInvocation.invokeOnSelection(ClientInvocation.java:163) [classes/:?]
	at com.hazelcast.client.spi.impl.ClientInvocation.invoke(ClientInvocation.java:146) [classes/:?]
	at com.hazelcast.client.spi.ClientProxy.invokeOnPartition(ClientProxy.java:224) [classes/:?]
	at com.hazelcast.client.spi.ClientProxy.invoke(ClientProxy.java:219) [classes/:?]
	at com.hazelcast.client.proxy.ClientMapProxy.getInternal(ClientMapProxy.java:324) [classes/:?]
	at com.hazelcast.client.proxy.ClientMapProxy.get(ClientMapProxy.java:318) [classes/:?]
	at com.hazelcast.client.map.ClientMapIssueTest$3.run(ClientMapIssueTest.java:160) [test-classes/:?]
Caused by: com.hazelcast.core.OperationTimeoutException: ClientInvocation{clientMessage = ClientMessage{connection=null, length=22, correlationId=46, operation=Client.getPartitions, messageType=8, partitionId=-1, isComplete=true, isRetryable=false, isEvent=false, writeOffset=0}, objectName = null, target = random, sendConnection = null} timed out because exception occurred after client invocation timeout 10000 ms. Current time: 2019-03-18 15:04:49.907. Start time: 2019-03-18 15:04:39.878. Total elapsed time: 10029 ms. 
	at com.hazelcast.client.spi.impl.ClientInvocation.newOperationTimeoutException(ClientInvocation.java:333) ~[classes/:?]
	at com.hazelcast.client.spi.impl.ClientInvocation.notifyException(ClientInvocation.java:238) ~[classes/:?]
	at com.hazelcast.client.spi.impl.ClientInvocation.invokeOnSelection(ClientInvocation.java:173) ~[classes/:?]
	at com.hazelcast.client.spi.impl.ClientInvocation.retry(ClientInvocation.java:194) ~[classes/:?]
	at com.hazelcast.client.spi.impl.ClientInvocation.run(ClientInvocation.java:179) ~[classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_181]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_181]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_181]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_181]
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64) ~[classes/:?]
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80) ~[classes/:?]
	at ------ submitted from ------.(Unknown Source) ~[?:?]
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:96) ~[classes/:?]
	... 12 more
Caused by: java.io.IOException: Owner connection is not available!
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.checkAllowed(ClientConnectionManagerImpl.java:312) ~[classes/:?]
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.getConnection(ClientConnectionManagerImpl.java:271) ~[classes/:?]
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.getOrTriggerConnect(ClientConnectionManagerImpl.java:262) ~[classes/:?]
	at com.hazelcast.client.spi.impl.SmartClientInvocationService.getOrTriggerConnect(SmartClientInvocationService.java:73) ~[classes/:?]
	at com.hazelcast.client.spi.impl.SmartClientInvocationService.invokeOnRandomTarget(SmartClientInvocationService.java:58) ~[classes/:?]
	at com.hazelcast.client.spi.impl.ClientInvocation.invokeOnSelection(ClientInvocation.java:167) ~[classes/:?]
	at com.hazelcast.client.spi.impl.ClientInvocation.retry(ClientInvocation.java:194) ~[classes/:?]
	at com.hazelcast.client.spi.impl.ClientInvocation.run(ClientInvocation.java:179) ~[classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_181]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_181]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_181]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_181]
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64) ~[classes/:?]
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80) ~[classes/:?]
```

The exception is getting propagated to the caller if the timed out operation is `Map.get`, but it's not getting propagated if the timed out operation is `Client.getPartitions`.

**Comment by blazember** [comment]
The reason seems to be this change: https://github.com/hazelcast/hazelcast/commit/f65089dfc66898ba1277f4bf99ca1f9d2b7aefc5#diff-9caf7fbb823cf694ab81b4b0deb7a762R160
Before the change we kept the partition table as is if the partition table was empty in the response, now we replace it with an empty one, leading to the issue. Need to find out why we get the response with an empty partition table.

**Comment by Danny-Hazelcast** [comment]
https://github.com/hazelcast/hazelcast-enterprise/issues/2820
