### ISSUE TITLE
NPE is thrown recursively when client is connected to unreachable member during split-brain

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#14722]
When client is connected to the member which becomes unreachable during split-brain then following NPE is thrown recursively (in extreme pace like 10000 logs per second) in that member: 
```
Mar 20, 2019 10:02:04 AM com.hazelcast.internal.partition.InternalPartitionService
INFO: [172.28.1.4]:5701 [dev] [3.12-advancednetworkit] Most recent partition table version: 1192
Mar 20, 2019 10:02:04 AM com.hazelcast.internal.partition.impl.MigrationThread
WARNING: [172.28.1.4]:5701 [dev] [3.12-advancednetworkit] null
java.lang.NullPointerException
        at com.hazelcast.client.impl.ClientPartitionListenerService.clientAddressOf(ClientPartitionListenerService.java:108)
        at com.hazelcast.client.impl.ClientPartitionListenerService.getPartitions(ClientPartitionListenerService.java:93)
        at com.hazelcast.client.impl.ClientPartitionListenerService.getPartitionsMessage(ClientPartitionListenerService.java:61)
        at com.hazelcast.client.impl.ClientPartitionListenerService.onPartitionStateChange(ClientPartitionListenerService.java:49)
        at com.hazelcast.instance.DefaultNodeExtension.onPartitionStateChange(DefaultNodeExtension.java:347)
        at com.hazelcast.instance.EnterpriseNodeExtension.onPartitionStateChange(EnterpriseNodeExtension.java:704)
        at com.hazelcast.internal.partition.impl.InternalPartitionServiceImpl$FetchMostRecentPartitionTableTask.processNewState(InternalPartitionServiceImpl.java:1519)
        at com.hazelcast.internal.partition.impl.InternalPartitionServiceImpl$FetchMostRecentPartitionTableTask.run(InternalPartitionServiceImpl.java:1413)
        at com.hazelcast.internal.partition.impl.MigrationThread.processTask(MigrationThread.java:122)
        at com.hazelcast.internal.partition.impl.MigrationThread.doRun(MigrationThread.java:98)
        at com.hazelcast.internal.partition.impl.MigrationThread.run(MigrationThread.java:67)
```

**Comment by olukas** [comment]
It has been fixed by https://github.com/hazelcast/hazelcast/pull/14728
