### ISSUE TITLE
AtomicLongUpdateStressTest.testFixedCluster

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#14738]
_master_ (commit c9fd2b48bd1834f0a3b1c1a034c0da7800ceee0a)

Failed on nightly build: http://jenkins.hazelcast.com/job/Hazelcast-3.x-nightly/56/testReport/com.hazelcast.client.stress/AtomicLongUpdateStressTest/testFixedCluster/

Stacktrace:
```
java.lang.AssertionError: There are failed writes, number of failures:22
	at org.junit.Assert.fail(Assert.java:88)
	at com.hazelcast.client.stress.AtomicLongUpdateStressTest.assertNoUpdateFailures(AtomicLongUpdateStressTest.java:124)
	at com.hazelcast.client.stress.AtomicLongUpdateStressTest.test(AtomicLongUpdateStressTest.java:96)
	at com.hazelcast.client.stress.AtomicLongUpdateStressTest.testFixedCluster(AtomicLongUpdateStressTest.java:88)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

Standard output:
```
Hiccups measured while running test 'testFixedCluster(com.hazelcast.client.stress.AtomicLongUpdateStressTest):'
23:04:40, accumulated pauses: 57 ms, max pause: 6 ms, pauses over 1000 ms: 0
23:04:45, accumulated pauses: 45 ms, max pause: 1 ms, pauses over 1000 ms: 0
23:04:50, accumulated pauses: 51 ms, max pause: 6 ms, pauses over 1000 ms: 0
23:04:55, accumulated pauses: 50 ms, max pause: 3 ms, pauses over 1000 ms: 0
23:05:00, accumulated pauses: 395 ms, max pause: 360 ms, pauses over 1000 ms: 0
23:05:05, accumulated pauses: 248 ms, max pause: 49 ms, pauses over 1000 ms: 0
23:05:10, accumulated pauses: 189 ms, max pause: 53 ms, pauses over 1000 ms: 0
23:05:15, accumulated pauses: 187 ms, max pause: 53 ms, pauses over 1000 ms: 0
23:05:20, accumulated pauses: 125 ms, max pause: 45 ms, pauses over 1000 ms: 0
23:05:25, accumulated pauses: 130 ms, max pause: 49 ms, pauses over 1000 ms: 0
23:05:30, accumulated pauses: 111 ms, max pause: 44 ms, pauses over 1000 ms: 0
23:05:35, accumulated pauses: 72 ms, max pause: 43 ms, pauses over 1000 ms: 0
23:05:40, accumulated pauses: 117 ms, max pause: 46 ms, pauses over 1000 ms: 0
23:05:45, accumulated pauses: 71 ms, max pause: 38 ms, pauses over 1000 ms: 0
23:05:50, accumulated pauses: 84 ms, max pause: 41 ms, pauses over 1000 ms: 0
23:05:55, accumulated pauses: 132 ms, max pause: 56 ms, pauses over 1000 ms: 0
23:06:00, accumulated pauses: 79 ms, max pause: 40 ms, pauses over 1000 ms: 0
23:06:05, accumulated pauses: 45 ms, max pause: 9 ms, pauses over 1000 ms: 0
23:06:10, accumulated pauses: 36 ms, max pause: 7 ms, pauses over 1000 ms: 0
23:06:15, accumulated pauses: 50 ms, max pause: 10 ms, pauses over 1000 ms: 0
23:06:20, accumulated pauses: 94 ms, max pause: 56 ms, pauses over 1000 ms: 0
23:06:25, accumulated pauses: 60 ms, max pause: 21 ms, pauses over 1000 ms: 0
23:06:30, accumulated pauses: 35 ms, max pause: 8 ms, pauses over 1000 ms: 0
23:06:35, accumulated pauses: 50 ms, max pause: 12 ms, pauses over 1000 ms: 0
23:06:40, accumulated pauses: 33 ms, max pause: 4 ms, pauses over 1000 ms: 0
23:06:45, accumulated pauses: 44 ms, max pause: 11 ms, pauses over 1000 ms: 0
23:06:50, accumulated pauses: 55 ms, max pause: 12 ms, pauses over 1000 ms: 0
23:06:55, accumulated pauses: 59 ms, max pause: 14 ms, pauses over 1000 ms: 0
23:07:00, accumulated pauses: 53 ms, max pause: 13 ms, pauses over 1000 ms: 0
23:07:05, accumulated pauses: 70 ms, max pause: 13 ms, pauses over 1000 ms: 0
23:07:10, accumulated pauses: 37 ms, max pause: 7 ms, pauses over 1000 ms: 0
23:07:15, accumulated pauses: 53 ms, max pause: 11 ms, pauses over 1000 ms: 0
23:07:20, accumulated pauses: 38 ms, max pause: 7 ms, pauses over 1000 ms: 0
23:07:25, accumulated pauses: 153 ms, max pause: 94 ms, pauses over 1000 ms: 0
23:07:30, accumulated pauses: 40 ms, max pause: 9 ms, pauses over 1000 ms: 0
23:07:35, accumulated pauses: 36 ms, max pause: 6 ms, pauses over 1000 ms: 0
23:07:40, accumulated pauses: 39 ms, max pause: 6 ms, pauses over 1000 ms: 0
23:07:45, accumulated pauses: 44 ms, max pause: 8 ms, pauses over 1000 ms: 0
23:07:50, accumulated pauses: 41 ms, max pause: 10 ms, pauses over 1000 ms: 0
23:07:55, accumulated pauses: 40 ms, max pause: 8 ms, pauses over 1000 ms: 0
23:08:00, accumulated pauses: 42 ms, max pause: 14 ms, pauses over 1000 ms: 0
23:08:05, accumulated pauses: 197 ms, max pause: 182 ms, pauses over 1000 ms: 0
```

**Comment by mustafaiman** [comment]
This test suffers from multicast isolation, too. (https://github.com/hazelcast/hazelcast-enterprise/issues/2862#issuecomment-475517934)
```
23:05:05,080  WARN |testFixedCluster| - [NodeMulticastListener] hz._hzInstance_2172_dev.MulticastThread - [127.0.0.1]:5705 [dev] [3.12-SNAPSHOT] New join request has been received from current master. Suspecting [127.0.0.1]:5701
23:05:05,080  WARN |testFixedCluster| - [NodeMulticastListener] hz._hzInstance_2171_dev.MulticastThread - [127.0.0.1]:5704 [dev] [3.12-SNAPSHOT] New join request has been received from current master. Suspecting [127.0.0.1]:5701
23:05:05,080  WARN |testFixedCluster| - [NodeMulticastListener] hz._hzInstance_2173_dev.MulticastThread - [127.0.0.1]:5706 [dev] [3.12-SNAPSHOT] New join request has been received from current master. Suspecting [127.0.0.1]:5701
23:05:05,080  WARN |testFixedCluster| - [MembershipManager] hz._hzInstance_2172_dev.MulticastThread - [127.0.0.1]:5705 [dev] [3.12-SNAPSHOT] Member [127.0.0.1]:5701 - 9283c009-3a4c-44fe-9de1-d06857122bcf is suspected to be dead for reason: New join request has been received from current master. Suspecting [127.0.0.1]:5701
23:05:05,080  WARN |testFixedCluster| - [NodeMulticastListener] hz._hzInstance_2170_dev.MulticastThread - [127.0.0.1]:5703 [dev] [3.12-SNAPSHOT] New join request has been received from current master. Suspecting [127.0.0.1]:5701
23:05:05,080  WARN |testFixedCluster| - [NodeMulticastListener] hz._hzInstance_2169_dev.MulticastThread - [127.0.0.1]:5702 [dev] [3.12-SNAPSHOT] New join request has been received from current master. Suspecting [127.0.0.1]:5701
23:05:05,080  WARN |testFixedCluster| - [MembershipManager] hz._hzInstance_2170_dev.MulticastThread - [127.0.0.1]:5703 [dev] [3.12-SNAPSHOT] Member [127.0.0.1]:5701 - 9283c009-3a4c-44fe-9de1-d06857122bcf is suspected to be dead for reason: New join request has been received from current master. Suspecting [127.0.0.1]:5701
23:05:05,080  WARN |testFixedCluster| - [MembershipManager] hz._hzInstance_2171_dev.MulticastThread - [127.0.0.1]:5704 [dev] [3.12-SNAPSHOT] Member [127.0.0.1]:5701 - 9283c009-3a4c-44fe-9de1-d06857122bcf is suspected to be dead for reason: New join request has been received from current master. Suspecting [127.0.0.1]:5701
23:05:05,080  WARN |testFixedCluster| - [MembershipManager] hz._hzInstance_2173_dev.MulticastThread - [127.0.0.1]:5706 [dev] [3.12-SNAPSHOT] Member [127.0.0.1]:5701 - 9283c009-3a4c-44fe-9de1-d06857122bcf is suspected to be dead for reason: New join request has been received from current master. Suspecting [127.0.0.1]:5701
23:05:05,080  WARN |testFixedCluster| - [MembershipManager] hz._hzInstance_2169_dev.MulticastThread - [127.0.0.1]:5702 [dev] [3.12-SNAPSHOT] Member [127.0.0.1]:5701 - 9283c009-3a4c-44fe-9de1-d06857122bcf is suspected to be dead for reason: New join request has been received from current master. Suspecting [127.0.0.1]:5701
23:05:05,080  INFO |testFixedCluster| - [MembershipManager] hz._hzInstance_2169_dev.MulticastThread - [127.0.0.1]:5702 [dev] [3.12-SNAPSHOT] Starting mastership claim process...
23:05:05,080  INFO |testFixedCluster| - [MembershipManager] hz._hzInstance_2169_dev.MulticastThread - [127.0.0.1]:5702 [dev] [3.12-SNAPSHOT] Local MembersView{version=6, members=[MemberInfo{address=[127.0.0.1]:5701, uuid=9283c009-3a4c-44fe-9de1-d06857122bcf, liteMember=false, memberListJoinVersion=1}, MemberInfo{address=[127.0.0.1]:5702, uuid=db89e993-e968-4338-9d7d-1ea4dc3133aa, liteMember=false, memberListJoinVersion=2}, MemberInfo{address=[127.0.0.1]:5703, uuid=fbb17682-3253-4793-99f1-1b3bf4bf6137, liteMember=false, memberListJoinVersion=3}, MemberInfo{address=[127.0.0.1]:5704, uuid=e2fd4432-9d93-491f-aa59-349168795e12, liteMember=false, memberListJoinVersion=4}, MemberInfo{address=[127.0.0.1]:5705, uuid=836029a3-a2ed-4fcc-bbd9-5cdd0830390b, liteMember=false, memberListJoinVersion=5}, MemberInfo{address=[127.0.0.1]:5706, uuid=11456b90-f7d7-468f-b966-30c9e3ba8110, liteMember=false, memberListJoinVersion=6}]} with suspected members: [[127.0.0.1]:5701] and initial addresses to ask: [Member [127.0.0.1]:5705 - 836029a3-a2ed-4fcc-bbd9-5cdd0830390b, Member [127.0.0.1]:5703 - fbb17682-3253-4793-99f1-1b3bf4bf6137, Member [127.0.0.1]:5706 - 11456b90-f7d7-468f-b966-30c9e3ba8110, Member [127.0.0.1]:5704 - e2fd4432-9d93-491f-aa59-349168795e12]
23:05:05,080  WARN |testFixedCluster| - [ClusterService] hz._hzInstance_2172_dev.priority-generic-operation.thread-0 - [127.0.0.1]:5705 [dev] [3.12-SNAPSHOT] Mastership of [127.0.0.1]:5702 is accepted. Response: MembersView{version=6, members=[MemberInfo{address=[127.0.0.1]:5702, uuid=db89e993-e968-4338-9d7d-1ea4dc3133aa, liteMem
```

**Comment by mmedenjak** [comment]
Closing as duplicate. We will definitely need to look into it but we don't need multiple issues for the same thing. Thank you for looking into the issue. I don't have any ideas how to solve it, though. If you have any ideas, go ahead!
