### ISSUE TITLE
LiteMemberJoinTest.test_liteMemberReconnects_multicast

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#14737]
_master_ (commit f8ee8f31d151fcd6ed10e2bee6ee00ff6851f205)

Failed on Windows: http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-Windows-OracleJDK8/21/testReport/com.hazelcast.cluster/LiteMemberJoinTest/test_liteMemberReconnects_multicast/

Stacktrace:
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.lang.Thread.sleep(Native Method)
	at com.hazelcast.internal.cluster.impl.MulticastJoiner.joinMaster(MulticastJoiner.java:99)
	at com.hazelcast.internal.cluster.impl.MulticastJoiner.doJoin(MulticastJoiner.java:78)
	at com.hazelcast.internal.cluster.impl.AbstractJoiner.join(AbstractJoiner.java:137)
	at com.hazelcast.instance.Node.join(Node.java:809)
	at com.hazelcast.internal.cluster.impl.ClusterMergeTask.rejoin(ClusterMergeTask.java:153)
	at com.hazelcast.internal.cluster.impl.ClusterMergeTask.run(ClusterMergeTask.java:68)
	at com.hazelcast.instance.LifecycleServiceImpl.runUnderLifecycleLock(LifecycleServiceImpl.java:107)
	at com.hazelcast.internal.cluster.impl.ClusterServiceImpl.merge(ClusterServiceImpl.java:299)
	at com.hazelcast.cluster.LiteMemberJoinTest.reconnect(LiteMemberJoinTest.java:190)
	at com.hazelcast.cluster.LiteMemberJoinTest.test_liteMemberReconnects(LiteMemberJoinTest.java:177)
	at com.hazelcast.cluster.LiteMemberJoinTest.test_liteMemberReconnects_multicast(LiteMemberJoinTest.java:165)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by mmedenjak** [comment]
Not sure but this looks fishy. `[172.30.0.148]:5701` is merging to `[172.30.0.148]:5702`. First a connection is established after which it is closed with `EndpointManager is stopping`. Maybe there is some race between connections being established and the endpoint manager being reset?

```
02:30:39,802  INFO |test_liteMemberReconnects_multicast| - [LifecycleService] test_liteMemberReconnects_multicast - [172.30.0.148]:5701 [d84bcac1-a9f8-4149-b941-8147940f42fa] [3.12-SNAPSHOT] [172.30.0.148]:5701 is MERGING
02:30:39,802  WARN |test_liteMemberReconnects_multicast| - [ClusterService] test_liteMemberReconnects_multicast - [172.30.0.148]:5701 [d84bcac1-a9f8-4149-b941-8147940f42fa] [3.12-SNAPSHOT] Resetting local member UUID. Previous: ca1c1a80-8e5b-4232-8997-497caa42b960, new: e1e5d3dd-56a0-45c9-8699-bca67b3435c5
02:30:39,802  INFO |test_liteMemberReconnects_multicast| - [InternalPartitionService] hz._hzInstance_824_d84bcac1-a9f8-4149-b941-8147940f42fa.migration - [172.30.0.148]:5702 [d84bcac1-a9f8-4149-b941-8147940f42fa] [3.12-SNAPSHOT] Fetching most recent partition table! my version: 0
02:30:39,803  INFO |test_liteMemberReconnects_multicast| - [TransactionManagerService] hz._hzInstance_824_d84bcac1-a9f8-4149-b941-8147940f42fa.cached.thread-3 - [172.30.0.148]:5702 [d84bcac1-a9f8-4149-b941-8147940f42fa] [3.12-SNAPSHOT] Committing/rolling-back live transactions of [172.30.0.148]:5701, UUID: ca1c1a80-8e5b-4232-8997-497caa42b960
02:30:39,803  INFO |test_liteMemberReconnects_multicast| - [TcpIpConnection] test_liteMemberReconnects_multicast - [172.30.0.148]:5701 [d84bcac1-a9f8-4149-b941-8147940f42fa] [3.12-SNAPSHOT] Connection[id=2, /172.30.0.148:5701->/172.30.0.148:60845, qualifier=null, endpoint=null, alive=false, type=MEMBER] closed. Reason: EndpointManager is stopping
02:30:39,802  INFO |test_liteMemberReconnects_multicast| - [TcpIpConnection] hz._hzInstance_823_d84bcac1-a9f8-4149-b941-8147940f42fa.IO.thread-in-1 - [172.30.0.148]:5701 [d84bcac1-a9f8-4149-b941-8147940f42fa] [3.12-SNAPSHOT] Initialized new cluster connection between /172.30.0.148:5701 and /172.30.0.148:60845
02:30:39,803  INFO |test_liteMemberReconnects_multicast| - [InternalPartitionService] hz._hzInstance_824_d84bcac1-a9f8-4149-b941-8147940f42fa.migration - [172.30.0.148]:5702 [d84bcac1-a9f8-4149-b941-8147940f42fa] [3.12-SNAPSHOT] Most recent partition table version: 0
02:30:39,803  INFO |test_liteMemberReconnects_multicast| - [TcpIpConnection] hz._hzInstance_824_d84bcac1-a9f8-4149-b941-8147940f42fa.IO.thread-in-1 - [172.30.0.148]:5702 [d84bcac1-a9f8-4149-b941-8147940f42fa] [3.12-SNAPSHOT] Initialized new cluster connection between /0.0.0.0:60845 and /172.30.0.148:5701
02:30:39,804  INFO |test_liteMemberReconnects_multicast| - [TcpIpConnection] hz._hzInstance_824_d84bcac1-a9f8-4149-b941-8147940f42fa.IO.thread-in-1 - [172.30.0.148]:5702 [d84bcac1-a9f8-4149-b941-8147940f42fa] [3.12-SNAPSHOT] Connection[id=2, /0.0.0.0:60845->/172.30.0.148:5701, qualifier=null, endpoint=[172.30.0.148]:5701, alive=false, type=MEMBER] closed. Reason: Connection closed by the other side
02:30:39,809  INFO |test_liteMemberReconnects_multicast| - [MulticastJoiner] test_liteMemberReconnects_multicast - [172.30.0.148]:5701 [d84bcac1-a9f8-4149-b941-8147940f42fa] [3.12-SNAPSHOT] Trying to join to discovered node: [172.30.0.148]:5702
02:31:09,948  INFO |test_liteMemberReconnects_multicast| - [MulticastJoiner] test_liteMemberReconnects_multicast - [172.30.0.148]:5701 [d84bcac1-a9f8-4149-b941-8147940f42fa] [3.12-SNAPSHOT] Trying to join to discovered node: [172.30.0.148]:5702
02:31:40,148  INFO |test_liteMemberReconnects_multicast| - [MulticastJoiner] test_liteMemberReconnects_multicast - [172.30.0.148]:5701 [d84bcac1-a9f8-4149-b941-8147940f42fa] [3.12-SNAPSHOT] Trying to join to discovered node: [172.30.0.148]:5702
02:32:10,301  INFO |test_liteMemberReconnects_multicast| - [MulticastJoiner] test_liteMemberReconnects_multicast - [172.30.0.148]:5701 [d84bcac1-a9f8-4149-b941-8147940f42fa] [3.12-SNAPSHOT] Trying to join to discovered node: [172.30.0.148]:5702
02:32:40,505  INFO |test_liteMemberReconnects_multicast| - [MulticastJoiner] test_liteMemberReconnects_multicast - [172.30.0.148]:5701 [d84bcac1-a9f8-4149-b941-8147940f42fa] [3.12-SNAPSHOT] Trying to join to discovered node: [172.30.0.148]:5702
02:33:10,680  INFO |test_liteMemberReconnects_multicast| - [MulticastJoiner] test_liteMemberReconnects_multicast - [172.30.0.148]:5701 [d84bcac1-a9f8-4149-b941-8147940f42fa] [3.12-SNAPSHOT] Trying to join to discovered node: [172.30.0.148]:5702
02:33:40,786  INFO |test_liteMemberReconnects_multicast| - [MulticastJoiner] test_liteMemberReconnects_multicast - [172.30.0.148]:5701 [d84bcac1-a9f8-4149-b941-8147940f42fa] [3.12-SNAPSHOT] Trying to join to discovered node: [172.30.0.148]:5702
02:34:10,982  INFO |test_liteMemberReconnects_multicast| - [MulticastJoiner] test_liteMemberReconnects_multicast - [172.30.0.148]:5701 [d84bcac1-a9f8-4149-b941-8147940f42fa] [3.12-SNAPSHOT] Trying to join to discovered node: [172.30.0.148]:5702
02:34:41,137  INFO |test_liteMemberReconnects_multicast| - [MulticastJoiner] test_liteMemberReconnects_multicast - [172.30.0.148]:5701 [d84bcac1-a9f8-4149-b941-8147940f42fa] [3.12-SNAPSHOT] Trying to join to discovered node: [172.30.0.148]:5702
02:35:11,338  INFO |test_liteMemberReconnects_multicast| - [MulticastJoiner] test_liteMemberReconnects_multicast - [172.30.0.148]:5701 [d84bcac1-a9f8-4149-b941-8147940f42fa] [3.12-SNAPSHOT] Trying to join to discovered node: [172.30.0.148]:5702
02:35:41,338 ERROR |test_liteMemberReconnects_multicast| - [Node] test_liteMemberReconnects_multicast - [172.30.0.148]:5701 [d84bcac1-a9f8-4149-b941-8147940f42fa] [3.12-SNAPSHOT] Could not join cluster. Shutting down now!
```

**Comment by mmedenjak** [comment]
Looks like there is a race between processing a late bind response and clearing the `TcpIpEndpointManager#connectionsMap` when doing split brain. In some cases, the connection is closed but because of bind message processing, a closed connection is put back into the `connectionsMap` [here](https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/nio/tcp/BindHandler.java#L199).
Further attempts to connect to the node fail as there is already a connection in the map. Not sure if we need to prevent putting a closed connection into the map or remove the closed connection on reconnect.
