### ISSUE TITLE
ClientRegressionWithRealNetworkTest.testOperationsContinueWhenOwnerDisconnected_reconnectModeAsync

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#14741]
_master_ (commit f8ee8f31d151fcd6ed10e2bee6ee00ff6851f205)

Failed on Sonar: http://jenkins.hazelcast.com/job/Hazelcast-3.x-sonar/60/testReport/com.hazelcast.client/ClientRegressionWithRealNetworkTest/testOperationsContinueWhenOwnerDisconnected_reconnectModeAsync/

Stacktrace:
```
com.hazelcast.client.HazelcastClientOfflineException: Client is offline
	at com.hazelcast.client.connection.nio.DefaultClientConnectionStrategy.beforeOpenConnection(DefaultClientConnectionStrategy.java:76)
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.triggerConnect(ClientConnectionManagerImpl.java:345)
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.getOrTriggerConnect(ClientConnectionManagerImpl.java:266)
	at com.hazelcast.client.spi.impl.SmartClientInvocationService.getOrTriggerConnect(SmartClientInvocationService.java:73)
	at com.hazelcast.client.spi.impl.SmartClientInvocationService.invokeOnPartitionOwner(SmartClientInvocationService.java:48)
	at com.hazelcast.client.spi.impl.ClientInvocation.invokeOnSelection(ClientInvocation.java:163)
	at com.hazelcast.client.spi.impl.ClientInvocation.invoke(ClientInvocation.java:146)
	at com.hazelcast.client.spi.ClientProxy.invokeOnPartition(ClientProxy.java:224)
	at com.hazelcast.client.spi.ClientProxy.invoke(ClientProxy.java:219)
	at com.hazelcast.client.proxy.ClientMapProxy.putInternal(ClientMapProxy.java:584)
	at com.hazelcast.client.proxy.ClientMapProxy.put(ClientMapProxy.java:334)
	at com.hazelcast.client.ClientRegressionWithRealNetworkTest.testOperationsContinueWhenOwnerDisconnected(ClientRegressionWithRealNetworkTest.java:293)
	at com.hazelcast.client.ClientRegressionWithRealNetworkTest.testOperationsContinueWhenOwnerDisconnected_reconnectModeAsync(ClientRegressionWithRealNetworkTest.java:247)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:96)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:33)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:155)
	at com.hazelcast.client.spi.ClientProxy.invokeOnPartition(ClientProxy.java:225)
	at com.hazelcast.client.spi.ClientProxy.invoke(ClientProxy.java:219)
	at com.hazelcast.client.proxy.ClientMapProxy.putInternal(ClientMapProxy.java:584)
	at com.hazelcast.client.proxy.ClientMapProxy.put(ClientMapProxy.java:334)
	at com.hazelcast.client.ClientRegressionWithRealNetworkTest.testOperationsContinueWhenOwnerDisconnected(ClientRegressionWithRealNetworkTest.java:293)
	at com.hazelcast.client.ClientRegressionWithRealNetworkTest.testOperationsContinueWhenOwnerDisconnected_reconnectModeAsync(ClientRegressionWithRealNetworkTest.java:247)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

Standard output:
```
Hiccups measured while running test 'testOperationsContinueWhenOwnerDisconnected_reconnectModeAsync(com.hazelcast.client.ClientRegressionWithRealNetworkTest):'
02:50:20, accumulated pauses: 35 ms, max pause: 1 ms, pauses over 1000 ms: 0
02:50:25, accumulated pauses: 30 ms, max pause: 0 ms, pauses over 1000 ms: 0
02:50:30, accumulated pauses: 441 ms, max pause: 412 ms, pauses over 1000 ms: 0
02:50:35, accumulated pauses: 35 ms, max pause: 0 ms, pauses over 1000 ms: 0
02:50:40, accumulated pauses: 40 ms, max pause: 0 ms, pauses over 1000 ms: 0
02:50:45, accumulated pauses: 35 ms, max pause: 0 ms, pauses over 1000 ms: 0
02:50:50, accumulated pauses: 34 ms, max pause: 0 ms, pauses over 1000 ms: 0
02:50:55, accumulated pauses: 37 ms, max pause: 0 ms, pauses over 1000 ms: 0
02:51:00, accumulated pauses: 8 ms, max pause: 0 ms, pauses over 1000 ms: 0
```

**Comment by sancar** [comment]
Same isolation problem. Closing as duplicate https://github.com/hazelcast/hazelcast-enterprise/issues/2862
