### ISSUE TITLE
ERROR after restarting one node

### ISSUE THREAD

**Issue by SoreGaInochi** [hazelcast/hazelcast#14754]
Hi,

We're running 2 nodes with Hazelcast 3.9.4

After the restart of one the nodes, we got the error below: 

```
14-03-2019 10:41:22,066 - thread=hz.exportData.partition-operation.thread-16 - ERROR - c.h.l.StandardLoggerFactory$StandardLogger |  [SERVER1]:[8045] [dev] [3.9.4] Op: com.hazelcast.collection.impl.queue.operations.PollOperation{serviceName='hz:impl:queueService', identityHash=1278049620, partitionId=160, replicaIndex=0, callId=-78, invocationTime=1552560081062 (2019-03-14 10:41:21.062), waitTimeout=1000, callTimeout=10000, name=requestsFull}, Error: NormalResponse already responseReceived for callback: Invocation{op=com.hazelcast.collection.impl.queue.operations.PollOperation{serviceName='hz:impl:queueService', identityHash=1278049620, partitionId=160, replicaIndex=0, callId=-78, invocationTime=1552560081062 (2019-03-14 10:41:21.062), waitTimeout=1000, callTimeout=10000, name=requestsFull}, tryCount=250, tryPauseMillis=500, invokeCount=13, callTimeoutMillis=10000, firstInvocationTimeMs=1552560080915, firstInvocationTime='2019-03-14 10:41:20.915', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 00:00:00.000', target=[SERVER1]:8045, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=null}, current-response: null
com.hazelcast.spi.exception.ResponseAlreadySentException: NormalResponse already responseReceived for callback: Invocation{op=com.hazelcast.collection.impl.queue.operations.PollOperation{serviceName='hz:impl:queueService', identityHash=1278049620, partitionId=160, replicaIndex=0, callId=-78, invocationTime=1552560081062 (2019-03-14 10:41:21.062), waitTimeout=1000, callTimeout=10000, name=requestsFull}, tryCount=250, tryPauseMillis=500, invokeCount=13, callTimeoutMillis=10000, firstInvocationTimeMs=1552560080915, firstInvocationTime='2019-03-14 10:41:20.915', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 00:00:00.000', target=[SERVER1]:8045, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=null}, current-response: null
        at com.hazelcast.spi.impl.operationservice.impl.Invocation.sendResponse(Invocation.java:189)
        at com.hazelcast.spi.Operation.sendResponse(Operation.java:353)
        at com.hazelcast.collection.impl.queue.operations.PollOperation.onWaitExpire(PollOperation.java:98)
        at com.hazelcast.spi.impl.operationparker.impl.ParkedOperation.run(ParkedOperation.java:140)
        at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:194)
        at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:120)
        at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:100)
14-03-2019 10:41:22,067 - thread=hz.exportData.partition-operation.thread-16 - WARN  - c.h.l.StandardLoggerFactory$StandardLogger |  [SERVER1]:8045 [dev] [3.9.4] Missing responseHandler for com.hazelcast.spi.impl.operationparker.impl.ParkedOperation{serviceName='hz:impl:queueService', identityHash=154135221, partitionId=160, replicaIndex=0, callId=0, invocationTime=-1 (1969-12-31 23:59:59.999), waitTimeout=-1, callTimeout=9223372036854775807, op=com.hazelcast.collection.impl.queue.operations.PollOperation{serviceName='hz:impl:queueService', identityHash=1278049620, partitionId=160, replicaIndex=0, callId=-78, invocationTime=1552560081062 (2019-03-14 10:41:21.062), waitTimeout=1000, callTimeout=10000, name=requestsFull}, expirationTime=1552560082062, valid=false}
com.hazelcast.spi.exception.ResponseAlreadySentException: NormalResponse already responseReceived for callback: Invocation{op=com.hazelcast.collection.impl.queue.operations.PollOperation{serviceName='hz:impl:queueService', identityHash=1278049620, partitionId=160, replicaIndex=0, callId=-78, invocationTime=1552560081062 (2019-03-14 10:41:21.062), waitTimeout=1000, callTimeout=10000, name=requestsFull}, tryCount=2
```

There was no further impacts on the application, but the error is troubling.

**Comment by ahmetmircik** [comment]
Hi @SoreGaInochi,
Thanks for the report, this is a known issue. 
Please follow it from [here](https://github.com/hazelcast/hazelcast/issues/11839)
