### ISSUE TITLE
AtomicLongStableReadStressTest.testFixedCluster

### ISSUE THREAD

**Issue by tezc** [hazelcast/hazelcast#14766]
_master_ (commit 07cef59265bce72d6c37fdcda7b5a30be1d749a5)

Failed on nightly build : http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-nightly/60/testReport/com.hazelcast.client.stress/AtomicLongStableReadStressTest/testFixedCluster/

**Stacktrace**

 ```java.lang.AssertionError:
com.hazelcast.client.stress.AtomicLongStableReadStressTest$StressThread7 encountered an error expected null, but was:<java.lang.AssertionError: The value for atomic reference: IAtomicLong{name='atomicreference:2642'} was not consistent expected:<2642> but was:<0>>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotNull(Assert.java:755)
	at org.junit.Assert.assertNull(Assert.java:737)
	at com.hazelcast.client.stress.StressTestSupport$TestThread.assertNoError(StressTestSupport.java:187)
	at com.hazelcast.client.stress.StressTestSupport.assertNoErrors(StressTestSupport.java:138)
	at com.hazelcast.client.stress.StressTestSupport.joinAll(StressTestSupport.java:159)
	at com.hazelcast.client.stress.AtomicLongStableReadStressTest.test(AtomicLongStableReadStressTest.java:88)
	at com.hazelcast.client.stress.AtomicLongStableReadStressTest.testFixedCluster(AtomicLongStableReadStressTest.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by mmedenjak** [comment]
Same isolation issue as [here](https://github.com/hazelcast/hazelcast-enterprise/issues/2862#issuecomment-475517934):

```
22:59:44,893  WARN |testFixedCluster| - [NodeMulticastListener] hz._hzInstance_2142_dev.MulticastThread - [127.0.0.1]:5703 [dev] [3.12-SNAPSHOT] New join request has been received from current master. Suspecting [127.0.0.1]:5701
```

Closing as duplicate.
