### ISSUE TITLE
ClientRegressionWithRealNetworkTest failures

### ISSUE THREAD

**Issue by blazember** [hazelcast/hazelcast#14764]
Multiple test cases in `ClientRegressionWithRealNetworkTest` started failing with `java.lang.IllegalStateException: Node failed to start!` cause in the PR builder. 

http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/927/
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/938/

**Error Message**
```
Node failed to start!
```
**Stacktrace**
```
java.lang.IllegalStateException: Node failed to start!
	at com.hazelcast.client.ClientRegressionWithRealNetworkTest.testConnectionCountAfterOwnerReconnect(ClientRegressionWithRealNetworkTest.java:136)
	at com.hazelcast.client.ClientRegressionWithRealNetworkTest.testConnectionCountAfterOwnerReconnect_memberHostname_clientIp(ClientRegressionWithRealNetworkTest.java:115)
```

**Comment by ihsandemir** [comment]
```
14:57:49,439 ERROR |testConnectionCountAfterOwnerReconnect_memberHostname_clientIp| - [cluster] hz._hzInstance_122_dev.priority-generic-operation.thread-0 - [localhost]:5701 [dev] [3.12-SNAPSHOT] Node could not join cluster. A Configuration mismatch was detected: Incompatible partition groups! expected: enabled / HOST_AWARE, found: disabled / null Node is going to shutdown now!
```

**Comment by mmedenjak** [comment]
Thanks for the analysis @ihsandemir ! Looks like the same isolation issue we've been encountering since Friday (https://github.com/hazelcast/hazelcast-enterprise/issues/2862#issuecomment-475517934). Closing as duplicate.
