### ISSUE TITLE
JsonMetadataCreationTest.testPutAllCreatesMetadataForJson

### ISSUE THREAD

**Issue by tezc** [hazelcast/hazelcast#14787]
_master_ (commit 23dade94e33cfb816249e93839eb8ecb9cbcb12c)

Failed on ZingJDK7 : http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-ZingJDK7/23/testReport/com.hazelcast.json.internal/JsonMetadataCreationTest/testPutAllCreatesMetadataForJson_InMemoryFormat__BINARY_/

**Stacktrace**
```
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertNotNull(Assert.java:712)
	at org.junit.Assert.assertNotNull(Assert.java:722)
	at com.hazelcast.json.internal.JsonMetadataCreationTest.assertMetadataCreated(JsonMetadataCreationTest.java:325)
	at com.hazelcast.json.internal.JsonMetadataCreationTest.assertMetadataCreated(JsonMetadataCreationTest.java:318)
	at com.hazelcast.json.internal.JsonMetadataCreationTest.testPutAllCreatesMetadataForJson(JsonMetadataCreationTest.java:239)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by AleksPeychev** [comment]
Reopening as issue occurred again on: _master_ (commit 0b6a0d34f85e31fc7390ec534fcff9f08455ef53)
with OpenJDK17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-OpenJDK17-Esxi7/78/testReport/junit/com.hazelcast.json.internal/JsonMetadataCreationTest/testPutAllCreatesMetadataForJson_InMemoryFormat__BINARY_/
<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: Could not find backup member for partition 7
	at com.hazelcast.test.Accessors.getBackupInstance(Accessors.java:163)
	at com.hazelcast.json.internal.JsonMetadataCreationTest.getMetadata(JsonMetadataCreationTest.java:322)
	at com.hazelcast.json.internal.JsonMetadataCreationTest.assertMetadataCreated(JsonMetadataCreationTest.java:349)
	at com.hazelcast.json.internal.JsonMetadataCreationTest.assertMetadataCreated(JsonMetadataCreationTest.java:339)
	at com.hazelcast.json.internal.JsonMetadataCreationTest.testPutAllCreatesMetadataForJson(JsonMetadataCreationTest.java:260)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:840)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-OpenJDK17-Esxi7/78/

**Comment by olukas** [comment]
Closing the test failure - it doesn't seem to be related to `master` or the latest maintenance stream `5.5.z` and it hasn't fail in the last 3 months. Feel free to reopen test failure if it occurs on `master` or on the latest maintenance stream.
