### ISSUE TITLE
Hazelcast enterprise ssl connection

### ISSUE THREAD

**Issue by OuyangDanwen** [hazelcast/hazelcast#14786]
Hi Hazelcast team,
I am using hazelcast java client v3.10.3 with Springboot to connect to my company's hazelcast cluster (enterprise version 3.10.3) through ssl. However, I am getting the following error:
```
Caused by: java.lang.IllegalStateException: SSL/TLS requires Hazelcast Enterprise Edition
                at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.checkSslAllowed(ClientConnectionManagerImpl.java:204)
                at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.<init>(ClientConnectionManagerImpl.java:197)
                at com.hazelcast.client.impl.DefaultClientConnectionManagerFactory.createConnectionManager(DefaultClientConnectionManagerFactory.java:37)
                at com.hazelcast.client.impl.HazelcastClientInstanceImpl.<init>(HazelcastClientInstanceImpl.java:257)
                at com.hazelcast.client.HazelcastClient$1.createHazelcastInstanceClient(HazelcastClient.java:55)
                at com.hazelcast.client.HazelcastClientManager.newHazelcastClient(HazelcastClientManager.java:75)
                at com.hazelcast.client.HazelcastClient.newHazelcastClient(HazelcastClient.java:72)
                at com.visa.loyalty.marketing.campaignmanagement.campaignmanager.cache.HazelcastClientConfiguration.hazelcastInstance(HazelcastClientConfiguration.java:45)
                at com.visa.loyalty.marketing.campaignmanagement.campaignmanager.cache.HazelcastClientConfiguration$$EnhancerBySpringCGLIB$$c8abcda9.CGLIB$hazelcastInstance$1(<generated>)
                at com.visa.loyalty.marketing.campaignmanagement.campaignmanager.cache.HazelcastClientConfiguration$$EnhancerBySpringCGLIB$$c8abcda9$$FastClassBySpringCGLIB$$85c7271c.invoke(<generated>)
                at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
                at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:358)
                at com.visa.loyalty.marketing.campaignmanagement.campaignmanager.cache.HazelcastClientConfiguration$$EnhancerBySpringCGLIB$$c8abcda9.hazelcastInstance(<generated>)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:498)
                at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
                ... 106 more
```
Here is my configuration bean:
` @Bean
  public ClientConfig clientConfig() {
    ClientConfig clientConfig = new ClientConfig();
    ClientNetworkConfig networkConfig = clientConfig.getNetworkConfig();
    GroupConfig groupConfig = clientConfig.getGroupConfig();
    groupConfig.setName("").setPassword("");
 
    networkConfig.addAddress("", "")
        .setSmartRouting(true)
        .setRedoOperation(true)
        .setConnectionTimeout(100000)
        .setConnectionAttemptLimit(5);
    SSLConfig sslConfig = new SSLConfig();
    sslConfig.setEnabled(true);
    networkConfig.setSSLConfig(sslConfig);
 
    return clientConfig;
`
I did not provide a certificate as it is set to be optional on the server. I am sure ssl connection is required as observed from logs, as the cluster rejects plaintext connection. I am wondering if I have to set any property at client side for enterprise version or I am missing something else. Please help with this.

**Comment by pveentjer** [comment]
On the client side you need to make use of the Hazelcast enterprise client jar. Otherwise TLS isn't available.

**Comment by pveentjer** [comment]
I'm going to close this ticket. Feel free to reopen it if you have further questions.
