### ISSUE TITLE
Statistics in spring boot 2.1.x no longer exported to prometheus

### ISSUE THREAD

**Issue by wemu** [hazelcast/hazelcast#14799]
I ran into am issue with spring boot 2.1.3 and the cache metrics.
Maybe related to: https://github.com/hazelcast/hazelcast/issues/14684

I use actuator and prometheus to export the cache statistics. This worked before by using the CacheMetricsRegistrar. For some reason the cache metrics are no longer there.

Experimenting around: I added a hazelcast.xml config file:

```
<?xml version="1.0" encoding="UTF-8"?>
<hazelcast xmlns="http://www.hazelcast.com/schema/config"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.hazelcast.com/schema/config
           http://www.hazelcast.com/schema/config/hazelcast-config-3.11.xsd">

    <cache name="default">
        <statistics-enabled>false</statistics-enabled>
    </cache>

</hazelcast>
```

Interestingly this makes the cache statistics available in actuator/prometheus (for all the caches I have). But the logs now contains HazelcastSerializationException because of a ClassNotFoundException. And I can't figure out what that xml file changes regarding to classloading. 

The whole issue with the missing cache metrics seems to have come up around the jdk-11 / spring-boot 2.1.x upgrade.

The linked issue above is a similar case. Once I add my own config (via the hazelcast.xml file or as a bean) the exception below apperas. If I work with the defaults (spring boot autoconfiguration) all is fine but no cache metrics are exported anymore.

The existence of that hazelcast.xml file seems to put hazelcast into a different mode: 
(the logs below are not there if the file is not there)
```

2019-03-29 10:25:47.088  WARN 15104 --- [           main] c.h.instance.HazelcastInstanceFactory    : Hazelcast is starting in a Java modular environment (Java 9 and newer) but without proper access to required Java packages. Use additional Java arguments to provide Hazelcast access to Java internal API. The internal API access is used to get the best performance results. Arguments to be used:
 --add-modules java.se --add-exports java.base/jdk.internal.ref=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.management/sun.management=ALL-UNNAMED --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED
2019-03-29 10:25:47.106  INFO 15104 --- [           main] com.hazelcast.config.XmlConfigLocator    : Loading 'hazelcast.xml' from classpath.
```

The application is quite simple and currently not replicated. In future I may use the cache in some peer to peer mode embedded in the application - but I have no plans for client-server setups.

Anyway.

How are statistics enabled without running into this classloader issue?

```

com.hazelcast.nio.serialization.HazelcastSerializationException: com.hazelcast.nio.serialization.HazelcastSerializationException: java.lang.ClassNotFoundException: ch.mobi.mobitor.plugin.rest.domain.FlywayRestServiceResponse
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:600) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:678) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:737) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:661) ~[na:na]
	at ch.mobi.mobitor.plugin.rest.service.scheduling.RestInformationCollector.collectRestCallsServiceResponses(RestInformationCollector.java:96) ~[mobitor-plugin-rest-3.0.11.jar:3.0.11]
	at ch.mobi.mobitor.plugin.rest.service.scheduling.RestInformationCollector$$FastClassBySpringCGLIB$$a66c723b.invoke(<generated>) ~[mobitor-plugin-rest-3.0.11.jar:3.0.11]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749) ~[spring-aop-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.cache.interceptor.CacheInterceptor.lambda$invoke$0(CacheInterceptor.java:53) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.cache.interceptor.CacheAspectSupport.invokeOperation(CacheAspectSupport.java:365) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:420) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:345) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:61) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688) ~[spring-aop-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at ch.mobi.mobitor.plugin.rest.service.scheduling.RestInformationCollector$$EnhancerBySpringCGLIB$$559d8bd1.collectRestCallsServiceResponses(<generated>) ~[mobitor-plugin-rest-3.0.11.jar:3.0.11]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Caused by: com.hazelcast.nio.serialization.HazelcastSerializationException: java.lang.ClassNotFoundException: ch.mobi.mobitor.plugin.rest.domain.FlywayRestServiceResponse
	at com.hazelcast.internal.serialization.impl.JavaDefaultSerializers$JavaSerializer.read(JavaDefaultSerializers.java:86) ~[hazelcast-3.11.1.jar:3.11.1]
	at com.hazelcast.internal.serialization.impl.JavaDefaultSerializers$JavaSerializer.read(JavaDefaultSerializers.java:75) ~[hazelcast-3.11.1.jar:3.11.1]
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48) ~[hazelcast-3.11.1.jar:3.11.1]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:187) ~[hazelcast-3.11.1.jar:3.11.1]
	at com.hazelcast.map.impl.proxy.MapProxySupport.toObject(MapProxySupport.java:1245) ~[hazelcast-3.11.1.jar:3.11.1]
	at com.hazelcast.map.impl.proxy.MapProxyImpl.get(MapProxyImpl.java:120) ~[hazelcast-3.11.1.jar:3.11.1]
	at com.hazelcast.spring.cache.HazelcastCache.lookup(HazelcastCache.java:162) ~[hazelcast-spring-3.11.1.jar:3.11.1]
	at com.hazelcast.spring.cache.HazelcastCache.get(HazelcastCache.java:67) ~[hazelcast-spring-3.11.1.jar:3.11.1]
	at org.springframework.cache.interceptor.AbstractCacheInvoker.doGet(AbstractCacheInvoker.java:73) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.cache.interceptor.CacheAspectSupport.findInCaches(CacheAspectSupport.java:554) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.cache.interceptor.CacheAspectSupport.findCachedItem(CacheAspectSupport.java:519) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:401) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:345) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:61) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688) ~[spring-aop-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at ch.mobi.mobitor.plugin.rest.service.restservice.interpreters.JesFlywayInformationInterpreter$$EnhancerBySpringCGLIB$$2bc058ca.fetchResponse(<generated>) ~[mobitor-plugin-rest-3.0.11.jar:3.0.11]
	at ch.mobi.mobitor.plugin.rest.service.scheduling.RestInformationCollector.lambda$populateRestServiceStatusFromSwagger$0(RestInformationCollector.java:129) ~[mobitor-plugin-rest-3.0.11.jar:3.0.11]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540) ~[na:na]
	at ch.mobi.mobitor.plugin.rest.service.scheduling.RestInformationCollector.lambda$populateRestServiceStatusFromSwagger$2(RestInformationCollector.java:128) ~[mobitor-plugin-rest-3.0.11.jar:3.0.11]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540) ~[na:na]
	at ch.mobi.mobitor.plugin.rest.service.scheduling.RestInformationCollector.populateRestServiceStatusFromSwagger(RestInformationCollector.java:109) ~[mobitor-plugin-rest-3.0.11.jar:3.0.11]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[na:na]
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290) ~[na:na]
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177) ~[na:na]
Caused by: java.lang.ClassNotFoundException: ch.mobi.mobitor.plugin.rest.domain.FlywayRestServiceResponse
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[na:na]
	at com.hazelcast.nio.ClassLoaderUtil.tryLoadClass(ClassLoaderUtil.java:288) ~[hazelcast-3.11.1.jar:3.11.1]
	at com.hazelcast.nio.ClassLoaderUtil.loadClass(ClassLoaderUtil.java:252) ~[hazelcast-3.11.1.jar:3.11.1]
	at com.hazelcast.nio.IOUtil$ClassLoaderAwareObjectInputStream.resolveClass(IOUtil.java:646) ~[hazelcast-3.11.1.jar:3.11.1]
	at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1886) ~[na:na]
	at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1772) ~[na:na]
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2060) ~[na:na]
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1594) ~[na:na]
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:430) ~[na:na]
	at com.hazelcast.internal.serialization.impl.JavaDefaultSerializers$JavaSerializer.read(JavaDefaultSerializers.java:82) ~[hazelcast-3.11.1.jar:3.11.1]
	... 31 common frames omitted

```

**Comment by wemu** [comment]
I think this can be closed. I did some more digging:

The Spring Boot Autconfiugration does not really start a hazelcast instance if there is no Config bean or no hazelcast.xml file present. It falls back to some SimpleCacheConfiguration. Thats probably why there are no metrics anymore. Once I added a hazelcast Config bean things went back to normal. Only the classpath exceptions remaind. Those can be worked around setting the classloader:

    @Bean
    public Config hazelCastConfig() {
        Config config = new Config();
        config.setClassLoader(Thread.currentThread().getContextClassLoader());
        config.setInstanceName("hazelcache");
        return config;
    }

This looks very weird but currently I don't know if java 11 is to blame or some mechanism in spring boot. The classloader above is the tomcat one. If I don't set it then Hazelcast uses one from the JDK: ClassLoaders$AppClassLoader (since it may spawns a sperate process?). 

Anyway. It seems that hazelcast works as expected and my issues with this lie in the autoconfiguration of spring boot.

**Comment by vaughnd** [comment]
I ran in to the same issue using our own HazelcastInstanceFactory extends AbstractFactoryBean on java 11, running embedded in a Spring Boot 2.3 instance on Tomcat. Everything that ran in a ForkJoinPool got these ClassNotFoundExceptions intermittently. Forcing the Thread.currentThread().getContextClassLoader() in the factory fixed it. 

It seems to be ForkJoinPool itself that randomly gets different classloaders which cause trouble. https://www.devworx.co.uk/blog/Beware-The-ForkJoinPool-In-Web-Applications/index.html
