### ISSUE TITLE
MembershipUpdateTest.OperationExecuted_beforePreJoinOpIsDone

### ISSUE THREAD

**Issue by tezc** [hazelcast/hazelcast#14808]
_master_ (commit 8fe0e51a2da43b82274b3325ae467bccb3909bae)

Failed on OracleJDK10 : http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-OracleJDK10/16/testReport/junit/com.hazelcast.internal.cluster.impl/MembershipUpdateTest/com_hazelcast_internal_cluster_impl_MembershipUpdateTest/

**Stacktrace**
```
java.lang.IllegalStateException: Instances haven't been shut down: [HazelcastInstance{name='_hzInstance_1566_dev', node=[127.0.0.1]:5702}]
	at com.hazelcast.test.AbstractHazelcastClassRunner$1.evaluate(AbstractHazelcastClassRunner.java:309)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:107)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:83)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:379)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:340)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:413)
```

At first glance, it looks like instance creation here takes some time  :
https://github.com/hazelcast/hazelcast/blob/ede022c8f8dfe07fc29c8c8dd712102ab18195a7/hazelcast/src/test/java/com/hazelcast/internal/cluster/impl/MembershipUpdateTest.java#L786

It completes its start after test case finishes under load. If this is correct, we may set CountDownLatch(2) and countDown on both PreJoinAwareServiceImpl and in test case itself. 
Additionally we can add assertTrue(service.preJoinOpExecutionCompleted.get())

**Comment by mmedenjak** [comment]
Looks like that test passed: http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-OracleJDK10/16/testReport/junit/com.hazelcast.internal.cluster.impl/MembershipUpdateTest/noOperationExecuted_beforePreJoinOpIsDone/

But the test class didn't shut down all instances. Moving to 3.13 as it's not a blocker for 3.12.
