### ISSUE TITLE
WanConnectionManager throws [3.11.2] Failed to connect to WAN endpoint exception

### ISSUE THREAD

**Issue by kdohz** [hazelcast/hazelcast#14838]

**Comment by mmedenjak** [comment]
Hi @kdohz !

Can you post the logs here from both the active/source and passive/target cluster members here?

**Comment by kdohz** [comment]
Hello:

Our system (IPv6) has 2 clusters. 
WAN Replication is enabled for each cluster.
Member in cluster-1:
	Member [xxxx:xxxx:xxxx:22c1:0:0:2:1]:5701 - aa0ba67a-4617-4ff1-8dea-471ff4a282c9 
 Member in cluster-2:
	Member [xxxx:xxxx:xxxx:244f:0:0:2:3]:5701 - 775f8fac-3f6c-424b-ab04-81901c25fd17

We experience the [3.11.2] Failed to connect to WAN endpoint and data is not replicated over WAN from cluster-1 to cluster-2.

Below is event logging we see at cluster-1.
WAN replication is critical activity in our system. We ensure that the cluster's password is correct.
Please let us know what does exception mean?
We have another lab IPv4 that runs 3.11.2 and we don't have this problem

Regards,
Kinh

2019.03.29 06:20:29:933 PDT | Debug      | Hazelcast

	[xxxx:xxxx:xxxx:22c1:0:0:2:1]:5701 [hzcluster1] [3.11.2] Starting to connect to [xxxx:xxxx:xxxx:244f::2:3]:5701
2019.03.29 06:20:29:934 PDT | Info       | Hazelcast

	[xxxx:xxxx:xxxx:22c1:0:0:2:1]:5701 [hzcluster1] [3.11.2] Connecting to /xxxx:xxxx:xxxx:244f:0:0:2:3:5701, timeout: 0, bind-any: false


2019.03.29 06:20:29:997 PDT | Debug      | Hazelcast

	Successfully connected to: /xxxx:xxxx:xxxx:244f:0:0:2:3:5701 using socket Socket[addr=/xxxx:xxxx:xxxx:244f:0:0:2:3,port=5701,localport=45690]

2019.03.29 06:20:29:997 PDT | FieldDebug | Hazelcast

	[xxxx:xxxx:xxxx:22c1:0:0:2:1]:5701 [hzcluster1] [3.11.2] Established socket connection between /xxxx:xxxx:xxxx:22c1:0:0:2:1:45690 and /xxxx:xxxx:xxxx:244f:0:0:2:3:5701

2019.03.29 06:20:29:997 PDT | Debug      | Hazelcast

	[xxxx:xxxx:xxxx:22c1:0:0:2:1]:5701 [hzcluster1] [3.11.2] [Partition: 122] Promote suspended

2019.03.29 06:20:29:997 PDT | Debug      | Hazelcast

	[xxxx:xxxx:xxxx:22c1:0:0:2:1]:5701 [hzcluster1] [3.11.2] Sending bind packet to [xxxx:xxxx:xxxx:244f::2:3]:5701

2019.03.29 06:20:30:059 PDT | Info       | Hazelcast

	[xxxx:xxxx:xxxx:22c1:0:0:2:1]:5701 [hzcluster1] [3.11.2] Initialized new cluster connection between /xxxx:xxxx:xxxx:22c1:0:0:2:1:45690 and /xxxx:xxxx:xxxx:244f:0:0:2:3:5701

2019.03.29 06:20:30:059 PDT | Debug      | Hazelcast

	[xxxx:xxxx:xxxx:22c1:0:0:2:1]:5701 [hzcluster1] [3.11.2] Binding Connection[id=51, /xxxx:xxxx:xxxx:22c1:0:0:2:1:45690->/xxxx:xxxx:xxxx:244f:0:0:2:3:5701, endpoint=[xxxx:xxxx:xxxx:244f::2:3]:5701, alive=true, type=MEMBER] to [xxxx:xxxx:xxxx:244f:0:0:2:3]:5701, reply is false

2019.03.29 06:20:30:059 PDT | Debug      | Hazelcast

	[xxxx:xxxx:xxxx:22c1:0:0:2:1]:5701 [hzcluster1] [3.11.2] Resetting connection monitor for endpoint [xxxx:xxxx:xxxx:244f:0:0:2:3]:5701

2019.03.29 06:20:39:935 PDT | Warn       | Hazelcast

	[xxxx:xxxx:xxxx:22c1:0:0:2:1]:5701 [hzcluster1] [3.11.2] Failed to connect to WAN endpoint : [xxxx:xxxx:xxxx:244f::2:3]:5701 <java.lang.RuntimeException: Connection was not established in expected time or was not authorized>java.lang.RuntimeException: Connection was not established in expected time or was not authorized
	at com.hazelcast.enterprise.wan.connection.WanConnectionManager$1.createNew(WanConnectionManager.java:70)
	at com.hazelcast.enterprise.wan.connection.WanConnectionManager$1.createNew(WanConnectionManager.java:65)
	at com.hazelcast.util.ConcurrencyUtil.getOrPutSynchronized(ConcurrencyUtil.java:73)
	at com.hazelcast.enterprise.wan.connection.WanConnectionManager.getConnectionByTargetAddress(WanConnectionManager.java:285)
	at com.hazelcast.enterprise.wan.connection.WanConnectionManager.getConnection(WanConnectionManager.java:196)
	at com.hazelcast.enterprise.wan.replication.DefaultWanBatchSender.send(DefaultWanBatchSender.java:46)
	at com.hazelcast.enterprise.wan.replication.WanBatchReplication$BatchStripedRunnable.run(WanBatchReplication.java:243)
	at com.hazelcast.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:226)
	at com.hazelcast.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:209)

**Comment by mmedenjak** [comment]
Can you post the logs from the target member (`Member [xxxx:xxxx:xxxx:244f:0:0:2:3]:5701 - 775f8fac-3f6c-424b-ab04-81901c25fd17`)?

**Comment by kdohz** [comment]
[ATTLOG_cluster1.txt](https://github.com/hazelcast/hazelcast/files/3040041/ATTLOG_cluster1.txt)
[ATTLOG_cluster2.txt](https://github.com/hazelcast/hazelcast/files/3040042/ATTLOG_cluster2.txt)

Cluster-1:
Members {size:3, ver:9} [
	Member [2001:1890:1001:22c1:0:0:2:2]:5701 - 6e66f27e-ac52-4614-a7ee-8df5907c4eee
	Member [2001:1890:1001:22c1:0:0:2:3]:5701 - 1299e037-27b0-4786-a234-da2e078a8bc8
	Member [2001:1890:1001:22c1:0:0:2:1]:5701 - aa0ba67a-4617-4ff1-8dea-471ff4a282c9 this
]

Cluster-2:
Members {size:3, ver:9} [
	Member [2001:1890:1001:244f:0:0:2:2]:5701 - 22d3004e-5dbc-4462-9246-2d47f110a5f5
	Member [2001:1890:1001:244f:0:0:2:3]:5701 - 775f8fac-3f6c-424b-ab04-81901c25fd17
	Member [2001:1890:1001:244f:0:0:2:1]:5701 - 18043cc0-9527-4e01-b829-6eb45cdd3957 this
]

**Comment by kdohz** [comment]
Do you have a chat line?

**Comment by mmedenjak** [comment]
We have [gitter](https://gitter.im/hazelcast/hazelcast) but I'm not currently available for chatting.

**Comment by kdohz** [comment]
That is all the log I have. There are 3 members in each cluster. I don;t have log for each member in the cluster. Is there a specific log you are looking for ?

**Comment by mmedenjak** [comment]
Are your hazelcast instances behind any kind of firewall, NAT, deployed in docker or virtualized environment or in AWS? Or otherwise, do they have both public and private IP addresses?

**Comment by kdohz** [comment]
In our system, the client server still runs hazelcast-enterprise-client 3.8. The core server runs hazelcast-enterprise 3.11.2. Eventually all servers will run 3.11.2 as part of the complete system upgrade.

**Comment by mmedenjak** [comment]
I'm asking about how servers are deployed. Are your hazelcast instances behind any kind of firewall, NAT, deployed in docker or virtualized environment or in AWS? Or otherwise, do they have both public and private IP addresses?

**Comment by kdohz** [comment]
All hazelcast nodes in the cluster are in private network

**Comment by kdohz** [comment]
What does the exception mean? not established in expected time or was not authorize ? which authorize?. 

	[2001:1890:1001:22c1:0:0:2:1]:5701 [hzcluster1] [3.11.2] Failed to connect to WAN endpoint : [2001:1890:1001:244f::2:3]:5701 <java.lang.RuntimeException: Connection was not established in expected time or was not authorized>java.lang.RuntimeException: Connection was not established in expected time or was not authorized

**Comment by mmedenjak** [comment]
@kdohz establishing a connection between the source and target cluster is an asynchronous process. We wait for some time for the connection is established (something like 10 seconds) but if it's not established, the exception is thrown. If the connection needs more than 10 seconds (e.g. 15 seconds) to be established, the next time we try sending WAN events, it will not throw the exception anymore.

The other part "or was not authorized" is when you misconfigure the source cluster. The publisher on the source cluster must have the correct group name and password of the members of the target cluster (see 
 `group-name` and `group.password` https://docs.hazelcast.org/docs/latest/manual/html-single/#defining-wan-replication). If this is the case, you should see additional logs in your source cluster, something like `WAN authorization failed for groupName ...  and target ...`.

**Comment by mmedenjak** [comment]
I'm not sure but this may be the issue you are encountering: https://github.com/hazelcast/hazelcast/issues/11256.

Can you try running with Hazelcast 3.12-SNAPSHOT? If you are using maven, choose this repository:

```
<repository>
    <id>Hazelcast Private Snapshot Repository</id>
    <url>https://repository.hazelcast.com/snapshot/</url>
</repository>
```

And update your hazelcast-enterprise dependency to 3.12-SNAPSHOT.

**Comment by kdohz** [comment]
@mmedenjak Thanks for advice so far. I am working with the system support people to determine if the network is playing any role in here. Prior to upgrade the server to 3.11.2 they are having the system 3.8.2 WAN replication does not work either. It works well with us in other lab. So before going with the SNAPSHOT, we want to dig ... Will get back to you. Tx

**Comment by kdohz** [comment]
Hello @mmedenjak 

We have the work around for this exception
[2001:1890:1001:244f:0:0:2:2]:5701 [hzcluster2] [3.11.2] Failed to connect to WAN endpoint : [2001:1890:1001:22c1::2:1]:5701 <java.lang.RuntimeException: Connection was not established in expected time or was not authorized>java.lang.RuntimeException: Connection was not established in expected time or was not authorized

Basically hazelcast.xml wan-replication has this endpoints [2001:1890:1001:22c1::2:1]:5701 configured with out '0' in between colon which is totally correct format.

To work around, we modify hazelcast.xml and add the '0' between colon. 
So  [2001:1890:1001:22c1::2:1]:5701 becomes [/2001:1890:1001:22c1:0:0:2:1]:5701

This is a snippet in hazelcast.xml for the wan-replication endpoints
Before
     <property name="endpoints">[2001:1890:1001:22c1::2:1]:5701,[2001:1890:1001:22c1::2:2]:5701,[2001:1890:1001:22c1::2:3]:5701</property>
After
     <property name="endpoints">[2001:1890:1001:22c1:0:0:2:1]:5701,[2001:1890:1001:22c1:0:0:2:2]:5701,[2001:1890:1001:22c1:0:0:2:3]:5701</property>


The question is: Why the binding is not working properly because of a difference in how the IPV6 is specified in the hazelcast configuration and how it is received in the packets ?

Thanks,
kdo

**Comment by mmedenjak** [comment]
Hi @kdohz !

Thank you for the analysis. As I've mentioned, I think this may be the issue you are encountering: https://github.com/hazelcast/hazelcast/issues/11256. Can you try running with Hazelcast 3.12? It has just been released a couple of days ago and this issue might be fixed.

**Comment by kdohz** [comment]
ok. I will try that 3.12. I just hope it is what we need. Please don't close this ticket yet. I will let you know

**Comment by kdohz** [comment]
Hello @mmedenjak

We upgrade to use 3.12. 
Again the system WAN replication fails as I described in my previous comment.
Please note our system is IPv6.
I will provide logs early next week but please consider my comments 
"Basically hazelcast.xml wan-replication has this endpoints [2001:1890:1001:22c1::2:1]:5701 configured with out '0' in between colon which is totally correct format.

To work around, we modify hazelcast.xml and add the '0' between colon.
So [2001:1890:1001:22c1::2:1]:5701 becomes [/2001:1890:1001:22c1:0:0:2:1]:5701"

Thanks,
Kinh

**Comment by kdohz** [comment]
Hello @mmedenjak

I attach full log Cluster2Node1-Hazelcast2019.04.13-07.23.41.txt.
In the analysis extracted from that log below. I look at this timestamp and trace backward to why it throws exception on Failed to connect to WAN endpoint : [2001:1890:1001:22c1::2:1]:5701.
You notice that the IPv6 address of the WAN endpoint is in compressed format.
Prior to the exception, the address is like this: [2001:1890:1001:22c1:0:0:2:1]:5701
Hazelcast need to be consistent with IPv6 format.
In that exception, the source is [2001:1890:1001:244f:0:0:2:1]:5701 yet the destination WAN endpoint is [2001:1890:1001:22c1::2:1]:5701

The hazelcast.xml is configured with compressed format
<property name="endpoints">[2001:1890:1001:22c1::2:1]:5701,[2001:1890:1001:22c1::2:2]:5701,[2001:1890:1001:22c1::2:3]:5701</property>
We work around by adding 0:0 then things work.
<property name="endpoints">[2001:1890:1001:22c1:0:0:2:1]:5701,[2001:1890:1001:22c1:0:0:2:2]:5701,[2001:1890:1001:22c1:0:0:2:3]:5701</property>

Here is the analysis. Please follow timestamp and that target WAN endpoint 22c1::2:1 or 22c1:0:0:2:1


2019.04.13 07:32:08:822 PDT | Debug      | Hazelcast

	[2001:1890:1001:244f:0:0:2:1]:5701 [hzcluster2] [3.12] Starting to connect to [2001:1890:1001:22c1::2:1]:5701
2019.04.13 07:32:08:823 PDT | Debug      | Hazelcast

	[2001:1890:1001:244f:0:0:2:1]:5701 [hzcluster2] [3.12] Adding pipelines: NioChannel{null->null}.inboundPipeline, NioChannel{null->null}.outboundPipeline

2019.04.13 07:32:08:823 PDT | Info       | Hazelcast

	[2001:1890:1001:244f:0:0:2:1]:5701 [hzcluster2] [3.12] Connecting to /2001:1890:1001:22c1:0:0:2:1:5701, timeout: 10000, bind-any: false

2019.04.13 07:32:08:884 PDT | Debug      | Hazelcast

	Successfully connected to: /2001:1890:1001:22c1:0:0:2:1:5701 using socket Socket[addr=/2001:1890:1001:22c1:0:0:2:1,port=5701,localport=58243]

2019.04.13 07:32:08:884 PDT | FieldDebug | Hazelcast

	[2001:1890:1001:244f:0:0:2:1]:5701 [hzcluster2] [3.12] Established socket connection between /2001:1890:1001:244f:0:0:2:1:58243 and /2001:1890:1001:22c1:0:0:2:1:5701

2019.04.13 07:32:08:884 PDT | Debug      | Hazelcast

	[2001:1890:1001:244f:0:0:2:1]:5701 [hzcluster2] [3.12] Sending bind packet to [2001:1890:1001:22c1::2:1]:5701

2019.04.13 07:32:08:945 PDT | Info       | Hazelcast

	[2001:1890:1001:244f:0:0:2:1]:5701 [hzcluster2] [3.12] Initialized new cluster connection between /2001:1890:1001:244f:0:0:2:1:58243 and /2001:1890:1001:22c1:0:0:2:1:5701

2019.04.13 07:32:08:946 PDT | Debug      | Hazelcast

	[2001:1890:1001:244f:0:0:2:1]:5701 [hzcluster2] [3.12] Extended binding Connection[id=118, /2001:1890:1001:244f:0:0:2:1:58243->/2001:1890:1001:22c1:0:0:2:1:5701, qualifier=null, endpoint=[2001:1890:1001:22c1::2:1]:5701, alive=true, type=MEMBER], complete message is ExtendedBindMessage{schemaVersion=1, localAddresses={MEMBER=[[2001:1890:1001:22c1:0:0:2:1]:5701]}, targetAddress=[2001:1890:1001:244f:0:0:2:1]:5701, reply=false}
	[2001:1890:1001:244f:0:0:2:1]:5701 [hzcluster2] [3.12] Registering connection Connection[id=118, /2001:1890:1001:244f:0:0:2:1:58243->/2001:1890:1001:22c1:0:0:2:1:5701, qualifier=null, endpoint=[2001:1890:1001:22c1:0:0:2:1]:5701, alive=true, type=MEMBER] to address [2001:1890:1001:22c1:0:0:2:1]:5701

2019.04.13 07:32:08:946 PDT | Debug      | Hazelcast

	[2001:1890:1001:244f:0:0:2:1]:5701 [hzcluster2] [3.12] Resetting connection monitor for endpoint [2001:1890:1001:22c1:0:0:2:1]:5701

2019.04.13 07:32:08:946 PDT | Debug      | Hazelcast

	[2001:1890:1001:244f:0:0:2:1]:5701 [hzcluster2] [3.12] Registering connection Connection[id=118, /2001:1890:1001:244f:0:0:2:1:58243->/2001:1890:1001:22c1:0:0:2:1:5701, qualifier=null, endpoint=[2001:1890:1001:22c1:0:0:2:1]:5701, alive=true, type=MEMBER] to address alias [2001:1890:1001:22c1:0:0:2:1]:5701

2019.04.13 07:32:08:946 PDT | Debug      | Hazelcast

	[2001:1890:1001:244f:0:0:2:1]:5701 [hzcluster2] [3.12] Registering connection Connection[id=118, /2001:1890:1001:244f:0:0:2:1:58243->/2001:1890:1001:22c1:0:0:2:1:5701, qualifier=null, endpoint=[2001:1890:1001:22c1:0:0:2:1]:5701, alive=true, type=MEMBER] to address alias [2001:1890:1001:22c1:0:0:2:1]:5701

2019.04.13 07:32:08:946 PDT | Debug      | Hazelcast

	[2001:1890:1001:244f:0:0:2:1]:5701 [hzcluster2] [3.12] Connection Connection[id=118, /2001:1890:1001:244f:0:0:2:1:58243->/2001:1890:1001:22c1:0:0:2:1:5701, qualifier=null, endpoint=[2001:1890:1001:22c1:0:0:2:1]:5701, alive=true, type=MEMBER] is already bound, ignoring incoming Bind [2001:1890:1001:22c1:0:0:2:1]:5701


2019.04.13 07:32:18:824 PDT | Warn       | Hazelcast

	[2001:1890:1001:244f:0:0:2:1]:5701 [hzcluster2] [3.12] Failed to connect to WAN endpoint : [2001:1890:1001:22c1::2:1]:5701 <java.lang.RuntimeException: Connection was not established in expected time or was not authorized>java.lang.RuntimeException: Connection was not established in expected time or was not authorized

2019.04.13 07:32:22:927 PDT | Debug      | Hazelcast

	[2001:1890:1001:244f:0:0:2:1]:5701 [hzcluster2] [3.12] 
Max NioThread hz._hzInstance_1_hzcluster2.IO.thread-in-1 receive-load 20240It contains following pipelines: 
NioChannel{/2001:1890:1001:244f:0:0:2:1:58243->/2001:1890:1001:22c1:0:0:2:1:5701}.inboundPipeline:  245

This matter is urgent. It gates our system production test. Please help

Regards,
Kinh
[Cluster2Node1-Hazelcast2019.04.13-07.23.41.txt](https://github.com/hazelcast/hazelcast/files/3080670/Cluster2Node1-Hazelcast2019.04.13-07.23.41.txt)

**Comment by mmedenjak** [comment]
We'll look into the issue. Until then, please use the workaround with the non-compressed addresses.

**Comment by kdohz** [comment]
@mmedenjak 

Do you need any further information? Would you be able to tell roughly we can have a solution for this issue? We need to know the ETA for planning.

Thanks,
Kinh

**Comment by mmedenjak** [comment]
Hi @kdohz !

We don't need any further information but there are no plans when it will be solved. I suggest you use the workaround with the non-compressed addresses until then.
