### ISSUE TITLE
RestCPSubsystemTest.test_forceCloseValidCPSession_withInvalidCredentials

### ISSUE THREAD

**Issue by tezc** [hazelcast/hazelcast#14931]
_maintenance_ (commit bacf1f1c3851fd2f3e33f217ae57dcf144033e81)

Failed on Sonar : http://jenkins.hazelcast.com/job/Hazelcast-3.maintenance-sonar/89/testReport/junit/com.hazelcast.internal.ascii/RestCPSubsystemTest/test_forceCloseValidCPSession_withInvalidCredentials/

**Stacktrace**
```
org.apache.http.NoHttpResponseException: The target server failed to respond
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:143)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:260)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:161)
	at sun.reflect.GeneratedMethodAccessor648.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.http.impl.conn.CPoolProxy.invoke(CPoolProxy.java:138)
	at com.sun.proxy.$Proxy231.receiveResponseHeader(Unknown Source)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:271)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:253)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:194)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:85)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
	at com.hazelcast.internal.ascii.HTTPCommunicator.doPost(HTTPCommunicator.java:441)
	at com.hazelcast.internal.ascii.HTTPCommunicator.forceCloseCPSession(HTTPCommunicator.java:350)
	at com.hazelcast.internal.ascii.RestCPSubsystemTest.test_forceCloseValidCPSession_withInvalidCredentials(RestCPSubsystemTest.java:612)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by tezc** [comment]
http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.maintenance-sonar/108/testReport/com.hazelcast.internal.ascii/RestCPSubsystemTest/test_forceDestroyCPGroup_withInvalidCredentials/

**Comment by tezc** [comment]
http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.maintenance-sonar/121/testReport/com.hazelcast.internal.ascii/RestCPSubsystemTest/test_forceCloseValidCPSession_withInvalidCredentials/

**Comment by tezc** [comment]
Maybe this is related : 

http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-sonar/240/testReport/com.hazelcast.internal.ascii/RestCPSubsystemTest/test_forceDestroyCPGroup_withInvalidCredentials/

**Stacktrace**

```
org.apache.http.NoHttpResponseException: The target server failed to respond
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:143)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:260)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:161)
	at sun.reflect.GeneratedMethodAccessor819.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.http.impl.conn.CPoolProxy.invoke(CPoolProxy.java:138)
	at com.sun.proxy.$Proxy163.receiveResponseHeader(Unknown Source)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:271)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:253)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:194)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:85)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
	at com.hazelcast.internal.ascii.HTTPCommunicator.doPost(HTTPCommunicator.java:441)
	at com.hazelcast.internal.ascii.HTTPCommunicator.forceDestroyCPGroup(HTTPCommunicator.java:336)
	at com.hazelcast.internal.ascii.RestCPSubsystemTest.test_forceDestroyCPGroup_withInvalidCredentials(RestCPSubsystemTest.java:350)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)

```

**Standard output:**
```
.....

00:03:53,718  WARN |test_forceDestroyCPGroup_withInvalidCredentials| - [NodeExtension] hz.romantic_shannon.cached.thread-5 - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] Security features are only available on Hazelcast Enterprise!
00:03:53,718  WARN |test_forceDestroyCPGroup_withInvalidCredentials| - [TcpIpConnection] hz.romantic_shannon.IO.thread-out-0 - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] Connection[id=3, /127.0.0.1:5701->/127.0.0.1:52260, qualifier=null, endpoint=null, alive=false, type=REST_CLIENT] closed. Reason: Exception in Connection[id=3, /127.0.0.1:5701->/127.0.0.1:52260, qualifier=null, endpoint=null, alive=true, type=REST_CLIENT], thread=hz.romantic_shannon.IO.thread-out-0
java.lang.NullPointerException
	at com.hazelcast.internal.ascii.rest.HttpCommand.writeTo(HttpCommand.java:184) ~[classes/:?]
	at com.hazelcast.nio.ascii.TextEncoder.onWrite(TextEncoder.java:92) ~[classes/:?]
	at com.hazelcast.internal.networking.nio.NioOutboundPipeline.process(NioOutboundPipeline.java:276) ~[classes/:?]
	at com.hazelcast.internal.networking.nio.NioPipeline.run(NioPipeline.java:234) [classes/:?]
	at com.hazelcast.internal.networking.nio.NioThread.processTaskQueue(NioThread.java:341) [classes/:?]
	at com.hazelcast.internal.networking.nio.NioThread.selectLoop(NioThread.java:276) [classes/:?]
	at com.hazelcast.internal.networking.nio.NioThread.run(NioThread.java:235) [classes/:?]

....
```
