### ISSUE TITLE
QueryResultSizeLimiterTest.testNodeResultPreCheckLimitNegative

### ISSUE THREAD

**Issue by tezc** [hazelcast/hazelcast#14933]
_master_ (commit fe533226aeec1db3949acc7de0f75c10af3e651c)

Failed on Sonar : http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-sonar/94/testReport/com.hazelcast.map.impl.query/QueryResultSizeLimiterTest/testNodeResultPreCheckLimitNegative/

**Stacktrace**
```
java.lang.Exception: Unexpected exception, expected<java.lang.IllegalArgumentException> but was<java.lang.OutOfMemoryError>
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:28)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at java.util.BitSet.initWords(BitSet.java:166)
	at java.util.BitSet.<init>(BitSet.java:161)
	at com.hazelcast.util.collection.PartitionIdSet.<init>(PartitionIdSet.java:50)
	at com.hazelcast.util.collection.PartitionIdSet.<init>(PartitionIdSet.java:54)
	at com.hazelcast.map.impl.query.QueryResultSizeLimiterTest.initMocksWithConfiguration(QueryResultSizeLimiterTest.java:256)
	at com.hazelcast.map.impl.query.QueryResultSizeLimiterTest.testNodeResultPreCheckLimitNegative(QueryResultSizeLimiterTest.java:89)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)
	... 4 more
```

**Comment by tezc** [comment]
http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-sonar/95/testReport/
