### ISSUE TITLE
ClientCacheNearCacheInvalidationTest.when_shuttingDown_invalidationEventIsNotReceived

### ISSUE THREAD

**Issue by tezc** [hazelcast/hazelcast#14978]
_master_ (commit e1361b6226ac2ed1c1fa5fb5a00be696e5ceae13)

Failed on nightly build : http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-nightly/101/testReport/com.hazelcast.client.cache.impl.nearcache/ClientCacheNearCacheInvalidationTest/when_shuttingDown_invalidationEventIsNotReceived_format_BINARY__fromMember_false_/

**Stacktrace**
```
java.lang.AssertionError: Expected no further Near Cache invalidation events than 0, but received 1 (NearCacheStatsImpl{ownedEntryCount=0, ownedEntryMemoryCost=0, creationTime=1557094831328, hits=0, misses=0, ratio=NaN%, evictions=0, expirations=0, invalidations=0, lastPersistenceTime=0, persistenceCount=0, lastPersistenceDuration=0, lastPersistenceWrittenBytes=0, lastPersistenceKeyCount=0, lastPersistenceFailure=''})
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.client.cache.impl.nearcache.ClientCacheNearCacheInvalidationTest$5.run(ClientCacheNearCacheInvalidationTest.java:484)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1310)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1412)
	at com.hazelcast.client.cache.impl.nearcache.ClientCacheNearCacheInvalidationTest.assertNoFurtherInvalidationThan(ClientCacheNearCacheInvalidationTest.java:490)
	at com.hazelcast.client.cache.impl.nearcache.ClientCacheNearCacheInvalidationTest.assertNoFurtherInvalidation(ClientCacheNearCacheInvalidationTest.java:476)
	at com.hazelcast.client.cache.impl.nearcache.ClientCacheNearCacheInvalidationTest.when_shuttingDown_invalidationEventIsNotReceived(ClientCacheNearCacheInvalidationTest.java:333)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

```
22:20:30, accumulated pauses: 86 ms, max pause: 6 ms, pauses over 1000 ms: 0
22:20:35, accumulated pauses: 67 ms, max pause: 2 ms, pauses over 1000 ms: 0
22:20:40, accumulated pauses: 127 ms, max pause: 60 ms, pauses over 1000 ms: 0
22:20:45, accumulated pauses: 101 ms, max pause: 20 ms, pauses over 1000 ms: 0
22:20:50, accumulated pauses: 115 ms, max pause: 4 ms, pauses over 1000 ms: 0
22:20:55, accumulated pauses: 68 ms, max pause: 3 ms, pauses over 1000 ms: 0
22:21:00, accumulated pauses: 78 ms, max pause: 7 ms, pauses over 1000 ms: 0
22:21:05, accumulated pauses: 116 ms, max pause: 4 ms, pauses over 1000 ms: 0
22:21:10, accumulated pauses: 105 ms, max pause: 4 ms, pauses over 1000 ms: 0
22:21:15, accumulated pauses: 95 ms, max pause: 6 ms, pauses over 1000 ms: 0
22:21:20, accumulated pauses: 63 ms, max pause: 7 ms, pauses over 1000 ms: 0
22:21:25, accumulated pauses: 62 ms, max pause: 2 ms, pauses over 1000 ms: 0
22:21:30, accumulated pauses: 62 ms, max pause: 4 ms, pauses over 1000 ms: 0
22:21:35, accumulated pauses: 58 ms, max pause: 1 ms, pauses over 1000 ms: 0
22:21:40, accumulated pauses: 124 ms, max pause: 21 ms, pauses over 1000 ms: 0
22:21:45, accumulated pauses: 99 ms, max pause: 12 ms, pauses over 1000 ms: 0
22:21:50, accumulated pauses: 105 ms, max pause: 10 ms, pauses over 1000 ms: 0
22:21:55, accumulated pauses: 99 ms, max pause: 1 ms, pauses over 1000 ms: 0
22:22:00, accumulated pauses: 67 ms, max pause: 2 ms, pauses over 1000 ms: 0
22:22:05, accumulated pauses: 142 ms, max pause: 78 ms, pauses over 1000 ms: 0
22:22:10, accumulated pauses: 86 ms, max pause: 3 ms, pauses over 1000 ms: 0
22:22:15, accumulated pauses: 62 ms, max pause: 1 ms, pauses over 1000 ms: 0
22:22:20, accumulated pauses: 128 ms, max pause: 34 ms, pauses over 1000 ms: 0
22:22:25, accumulated pauses: 76 ms, max pause: 1 ms, pauses over 1000 ms: 0
22:22:30, accumulated pauses: 172 ms, max pause: 143 ms, pauses over 1000 ms: 0
```

**Comment by lazerion** [comment]
Reopening, reoccured #15067.
Closing #15067 in favor of this.

**Comment by tezc** [comment]
Latest failed build does not include the fix, closing the issue.
