### ISSUE TITLE
ArrayIndexOutOfBoundsException in diagnostics

### ISSUE THREAD

**Issue by StefanLiebenberg** [hazelcast/hazelcast#14973]
There is a ArrayIndexOutOfBoundsException in [DiagnosticsLogWriterImpl.java:122](https://github.com/hazelcast/hazelcast/blob/b7c48097df47b713f8192ce9fe25711f6b55dff3/hazelcast/src/main/java/com/hazelcast/internal/diagnostics/DiagnosticsLogWriterImpl.java#L123) 
when `sectionLevel` exceeds the length of `INDENTS`.

```
[ip]:5701 [cluster] [0.7] Failed to write file: /app/diagnostics-ip_5701-1556748740616-031.logjava.lang.ArrayIndexOutOfBoundsException: 5
	at com.hazelcast.internal.diagnostics.DiagnosticsLogWriterImpl.startSection(DiagnosticsLogWriterImpl.java:122)
	at com.hazelcast.internal.diagnostics.DiagnosticsLogWriterImpl.startSection(DiagnosticsLogWriterImpl.java:107)
	at com.hazelcast.internal.diagnostics.OperationThreadSamplerPlugin.run(OperationThreadSamplerPlugin.java:115)
	at com.hazelcast.internal.diagnostics.DiagnosticsLogFile.renderPlugin(DiagnosticsLogFile.java:111)
	at com.hazelcast.internal.diagnostics.DiagnosticsLogFile.write(DiagnosticsLogFile.java:82)
	at com.hazelcast.internal.diagnostics.Diagnostics$WritePluginTask.run(Diagnostics.java:255)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
```
Addtional details:

We're running Hazelcast Jet 0.7 and our diagnostics options are 

```
 -Dhazelcast.diagnostics.enabled=true
 -Dhazelcast.diagnostics.directory=/app 
 -Dhazelcast.diagnostics.operationthreadsamples.period.seconds=30 
 -Dhazelcast.diagnostics.operationthreadsamples.includeName=true 
 -Dhazelcast.diagnostics.metric.level=info 
 -Dhazelcast.diagnostics.invocation.sample.period.seconds=30 
 -Dhazelcast.diagnostics.pending.invocations.period.seconds=30 
 -Dhazelcast.diagnostics.slowoperations.period.seconds=30 
 -Dhazelcast.diagnostics.storeLatency.period.seconds=60
```

**Comment by pveentjer** [comment]
I tried running with this setup in Hazelcast 4.0 and I don't see any problems.

My guess is that a different plugin for whatever reason hasn't called 'endSection'. Perhaps multiple times.. and then everything is shifted till you eventually run out of indents.

**Comment by pveentjer** [comment]
Did you see any other exceptions in the log related to diagnostics?

**Comment by StefanLiebenberg** [comment]
The only other exception I can find is ( no stack trace ):

```
full_message
[ip]:5701 [cluster] [0.7] Failed to write file: /app/diagnostics-ip_5701-1556748740616-031.logjava.lang.ArrayIndexOutOfBoundsException: null
````

However, Looking at the diagnostics logs, it seems the last plugin to write a timestamp was `OperationThreadSamples` 

```
02-05-2019 10:16:22 1556792182220 OperationThreadSamples[
                          Partition[
                                  PendingInvocations[
                                          count=1,292
                                          invocations[
                                                  com.hazelcast.map.impl.journal.MapEventJournalReadOperation=1,286
                                                  com.hazelcast.jet.impl.operation.StartExecutionOperation=4
                                                  com.hazelcast.jet.impl.operation.JoinSubmittedJobOperation=2]]
                                  SlowOperations[]
```

So perhaps some npe exception in this plugin?

**Comment by martinkrc** [comment]
Hi, just experienced the same exception in our environment. The exceptions keeps repeating, but not sure about the trigger.

**Comment by francesco-hz** [comment]
The issue has been reported again, on a [3.11] cluster. ZD6483.
Interestingly, logs were captured since IMDG node start, and another `NullPointerException` exception is seen right before `ArrayIndexOutOfBoundsException` in the probe.

*Following exception Repeated 5 times, at diagnostics interval*
> [3.11] Failed to write file: /var/log/DP/HZ/diagnostics-xxx.log
java.lang.NullPointerException: null
        at com.hazelcast.internal.diagnostics.StoreLatencyPlugin$InstanceProbes.access$500(StoreLatencyPlugin.java:209)
        at com.hazelcast.internal.diagnostics.StoreLatencyPlugin$ServiceProbes.render(StoreLatencyPlugin.java:194)
        at com.hazelcast.internal.diagnostics.StoreLatencyPlugin$ServiceProbes.access$100(StoreLatencyPlugin.java:171)
        at com.hazelcast.internal.diagnostics.StoreLatencyPlugin.render(StoreLatencyPlugin.java:148)
        at com.hazelcast.internal.diagnostics.StoreLatencyPlugin.run(StoreLatencyPlugin.java:142)
        at com.hazelcast.internal.diagnostics.DiagnosticsLogFile.renderPlugin(DiagnosticsLogFile.java:111)
        at com.hazelcast.internal.diagnostics.DiagnosticsLogFile.write(DiagnosticsLogFile.java:82)
        at com.hazelcast.internal.diagnostics.Diagnostics$WritePluginTask.run(Diagnostics.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)


*followed by the well know IOUB exception*

> [3.11] Failed to write file: /var/log/DP/HZ/diagnostics-xxx.log
java.lang.ArrayIndexOutOfBoundsException: 5
        at com.hazelcast.internal.diagnostics.DiagnosticsLogWriterImpl.writeKeyValueHead(DiagnosticsLogWriterImpl.java:211)
        at com.hazelcast.internal.diagnostics.DiagnosticsLogWriterImpl.writeKeyValueEntry(DiagnosticsLogWriterImpl.java:194)
        at com.hazelcast.internal.diagnostics.PendingInvocationsPlugin.render(PendingInvocationsPlugin.java:100)
        at com.hazelcast.internal.diagnostics.PendingInvocationsPlugin.run(PendingInvocationsPlugin.java:85)
        at com.hazelcast.internal.diagnostics.DiagnosticsLogFile.renderPlugin(DiagnosticsLogFile.java:111)
        at com.hazelcast.internal.diagnostics.DiagnosticsLogFile.write(DiagnosticsLogFile.java:82)
        at com.hazelcast.internal.diagnostics.Diagnostics$WritePluginTask.run(Diagnostics.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

Node had just been started, and was performing MAP load operations from external store.

**Comment by pveentjer** [comment]
There are 2 problems.

1: a plugin throws some kind of exception
2: the rendering system not resetting the idents which leads to an IndexOutOfBoundsException. So improper exception handling. 

I have resolved the second issue by always resetting the idents before any plugin is rendered; this way one plugin won't mess up the next plugin. But I'm trying to figure out what the cause is of the original exception.

**Comment by kwart** [comment]
I'm taking a look - starting with 3.12.z code check.
