### ISSUE TITLE
Issues releasing locks - Current thread is not owner of the lock

### ISSUE THREAD

**Issue by mrtinkz** [hazelcast/hazelcast#14975]
I have a service that acquire and release the locks, but sometimes I see below error.

```
java.lang.IllegalMonitorStateException: Current thread is not owner of the lock! -> Owner: d04da573-5827-4d83-a29d-cacd22aafda6, thread ID: 39
	at com.hazelcast.concurrent.lock.operations.UnlockOperation.unlock(UnlockOperation.java:75) ~[hazelcast-3.11.3.jar:3.11.3]
	at com.hazelcast.concurrent.lock.operations.UnlockOperation.run(UnlockOperation.java:64) ~[hazelcast-3.11.3.jar:3.11.3]
	at com.hazelcast.spi.Operation.call(Operation.java:170) ~[hazelcast-3.11.3.jar:3.11.3]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:208) ~[hazelcast-3.11.3.jar:3.11.3]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:197) ~[hazelcast-3.11.3.jar:3.11.3]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:147) ~[hazelcast-3.11.3.jar:3.11.3]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:125) ~[hazelcast-3.11.3.jar:3.11.3]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:110) ~[hazelcast-3.11.3.jar:3.11.3]
	at ------ submitted from ------.(Unknown Source) ~[na:na]
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:127) ~[hazelcast-3.11.3.jar:3.11.3]
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:79) ~[hazelcast-3.11.3.jar:3.11.3]
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:162) ~[hazelcast-3.11.3.jar:3.11.3]
	at com.hazelcast.spi.impl.AbstractInvocationFuture.join(AbstractInvocationFuture.java:143) ~[hazelcast-3.11.3.jar:3.11.3]
	at com.hazelcast.concurrent.lock.LockProxySupport.unlock(LockProxySupport.java:151) ~[hazelcast-3.11.3.jar:3.11.3]
	at com.hazelcast.concurrent.lock.LockProxy.unlock(LockProxy.java:106) ~[hazelcast-3.11.3.jar:3.11.3]
	at com.stream.consumer.service.LockHolderService.removeHzLock(LockHolderService.java:115) ~[classes/:na]
	at com.stream.consumer.service.LockHolderService.lambda$1(LockHolderService.java:140) ~[classes/:na]
	at java.util.Collection.removeIf(Collection.java:414) ~[na:1.8.0_202]
	at com.stream.consumer.service.LockHolderService.releaseLocks(LockHolderService.java:140) ~[classes/:na]
```

**Comment by chhaj5236** [comment]
I have found two possibilities that may cause such issue.
https://github.com/hazelcast/hazelcast/issues/13699 
https://github.com/hazelcast/hazelcast/issues/14961

**Comment by jerrinot** [comment]
@MrEasy is there any other exception in the log? perhaps a network partition (split-brain)?

**Comment by MrEasy** [comment]
> @MrEasy is there any other exception in the log? perhaps a network partition (split-brain)?

Probably you meant @mrtinkz ?!

**Comment by mrtinkz** [comment]
@jerrinot nope, I was running a single node. Apologies for the late reply.

**Comment by mrtinkz** [comment]
I was able to reproduce this issue a bit more. I have a lock holder service which acquires and releases locks, and I have a REST Api that sends commands to get locks and release. I suspect the thread for each request seems to be different and that might be causing issues with unlock. But I do not see any issues releasing locks with force unlock.

**Comment by mmedenjak** [comment]
Hi @mrtinkz!

With Hazelcast 4.0, we have replaced the entire implementation of ILock with the unsafe mode of CP subsystem (https://docs.hazelcast.org/docs/latest-dev/manual/html-single/#removal-of-deprecated-concurrency-api-implementations). If you don't require strong consistency guarantees, that mode might fit your use case and solve the issue. Can you try it out?

**Comment by mmedenjak** [comment]
Closing as the old lock implementation was removed in 4.0 with https://github.com/hazelcast/hazelcast/pull/15625.

**Comment by arushi315** [comment]
@mrtinkz what is the hazelcast version where you are seeing this error? 


We recently moved our application from hazelcast 3.9.2 to 3.11.4. 
This is just single node (no cluster) starting seeing the following errors in production: 

```
Unexpected error occurred with details: com.hazelcast.core.OperationTimeoutException: UnlockOperation got rejected before execution due to not starting within the operation-call-timeout of: 60000 ms. Current time: 2020-03-22 00:03:50.664. Start time: 2020-03-22 00:00:34.326. Total elapsed time: 196338 ms. Invocation{op=com.hazelcast.concurrent.lock.operations.UnlockOperation{serviceName='hz:impl:lockService', identityHash=1066156369, partitionId=27, replicaIndex=0, callId=-1171860577, invocationTime=1584849634326 (2020-03-22 00:00:34.326), waitTimeout=-1, callTimeout=60000, namespace=DefaultObjectNamespace{service='hz:impl:mapService', objectName=busymessages}, threadId=69}, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=60000, firstInvocationTimeMs=1584849634326, firstInvocationTime='2020-03-22 00:00:34.326', lastHeartbeatMillis=0, lastHeartbeatTime='1969-12-31 19:00:00.000', target=[10.102.3.58]:5701, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=null}
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.newOperationTimeoutException(InvocationFuture.java:164)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:104)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:79)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:162)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.join(AbstractInvocationFuture.java:143)
	at com.hazelcast.concurrent.lock.LockProxySupport.unlock(LockProxySupport.java:151)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.unlock(MapProxyImpl.java:332)
```

Eventually run into, 
```
java.lang.IllegalMonitorStateException: Current thread is not owner of the lock! -> <not-locked>
	at com.hazelcast.concurrent.lock.operations.UnlockOperation.unlock(UnlockOperation.java:75)
	at com.hazelcast.concurrent.lock.operations.UnlockOperation.run(UnlockOperation.java:64)
	at com.hazelcast.spi.Operation.call(Operation.java:170)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:208)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:197)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:147)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:125)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:110)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:127)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:79)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:162)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.join(AbstractInvocationFuture.java:143)
	at com.hazelcast.concurrent.lock.LockProxySupport.unlock(LockProxySupport.java:151)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.unlock(MapProxyImpl.java:332)
```

@mmedenjak  can you provide some guidance on how to further troubleshoot this?

**Comment by arushi315** [comment]
Nvm @mrtinkz I see the version in the logs you posted. 
version: 3.11.3

**Comment by mmedenjak** [comment]
@arushi315 your case seems to be clearer. `OperationTimeoutException: UnlockOperation got rejected before execution due to not starting within the operation-call-timeout of: 60000 ms` means that one of your members was very slow and unresponsive and was not able to process the unlock operation in 1 minute. The other error then is more or less expected as some other code tried to acquire the lock, but it was still locked.

I suggest you monitor your application to determine why it was unresponsive or as a last resort, you can increase the operation timeout (`hazelcast.operation.call.timeout.millis`).

**Comment by arushi315** [comment]
Hi @mmedenjak 
Sorry for the late reply on this. 
Looking at the description for the property 
`hazelcast.operation.call.timeout.millis- "Timeout to wait for a response when a remote call is sent, in milliseconds."`

Does it matter only for remote calls to let's say other members? 
As we observed this only on single node (no clustering)

**Comment by mmedenjak** [comment]
It's not only for remote calls. All operations can be rejected if they are too old, which probably means your instance is under heavy load.
