### ISSUE TITLE
LegacyAsyncMap test failures

### ISSUE THREAD

**Issue by tezc** [hazelcast/hazelcast#15001]
_master_ (commit 9d33cc97bb53a8ff852f51cfc65d88a7c2cb809b)

Failed on nightly build : http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-sonar/108/

http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-nightly/105/testReport/com.hazelcast.test.starter.test/PatchLevelCompatibilityTest/testMap_whenMixed_V37_Cluster/

AnswerTest.testMapService
HazelcastClientStarterTest.testClientMap_async
HazelcastClientStarterTest.testClientMap
PatchLevelCompatibilityTest.testMap_whenMixed_V37_Cluster

**Stacktrace**
```
com.hazelcast.test.starter.GuardianException: java.lang.ClassNotFoundException: com.hazelcast.map.impl.LegacyAsyncMap
	at com.hazelcast.test.starter.ProxyInvocationHandler.proxyReturnObject(ProxyInvocationHandler.java:168)
	at com.hazelcast.test.starter.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:70)
	at com.sun.proxy.$Proxy150.getMap(Unknown Source)
	at com.hazelcast.test.starter.answer.test.AnswerTest.testMapService(AnswerTest.java:390)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.hazelcast.map.impl.LegacyAsyncMap
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.hazelcast.test.starter.HazelcastProxyFactory.constructWithJdkProxy(HazelcastProxyFactory.java:257)
	at com.hazelcast.test.starter.HazelcastProxyFactory.proxyObjectForStarter(HazelcastProxyFactory.java:197)
	at com.hazelcast.test.starter.ProxyInvocationHandler.proxyReturnObject(ProxyInvocationHandler.java:164)
```

Related with : https://github.com/hazelcast/hazelcast/pull/14994

**Comment by vbekiaris** [comment]
These failures are due to incompatible changes in 4.0 (`LegacyAsyncMap` does not exist any more -> `IMap` class loaded from 3.x version cannot be proxied to 4.x -> test failures). Since the purpose of these tests is ensure some basic compatibility with previous minor version, I think we should ignore them and create an issue to enable again in 4.1. @tezc @Holmistr if you agree I will prepare a PR.

**Comment by tezc** [comment]
I'm okay with this :+1:

**Comment by Holmistr** [comment]
:+1:
