### ISSUE TITLE
QueryException: java.lang.IllegalArgumentException: There is no suitable accessor for 

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#15031]
```
com.hazelcast.query.QueryException: java.lang.IllegalArgumentException: There is no suitable accessor for 'personId' on class '[B'
	at com.hazelcast.query.impl.getters.ReflectionHelper.createGetter(ReflectionHelper.java:171)
	at com.hazelcast.query.impl.getters.Extractors.instantiateGetter(Extractors.java:152)
	at com.hazelcast.query.impl.getters.Extractors.getGetter(Extractors.java:118)
	at com.hazelcast.query.impl.getters.Extractors.extract(Extractors.java:73)
	at com.hazelcast.query.impl.QueryableEntry.extractAttributeValueFromTargetObject(QueryableEntry.java:171)
	at com.hazelcast.query.impl.QueryableEntry.extractAttributeValue(QueryableEntry.java:139)
	at com.hazelcast.query.impl.AbstractIndex.extractAttributeValue(AbstractIndex.java:224)
	at com.hazelcast.query.impl.AbstractIndex.putEntry(AbstractIndex.java:114)
	at com.hazelcast.query.impl.Indexes.putEntry(Indexes.java:220)
	at com.hazelcast.map.impl.recordstore.AbstractRecordStore.saveIndex(AbstractRecordStore.java:165)
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.putInternal(DefaultRecordStore.java:710)
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.put(DefaultRecordStore.java:686)
	at com.hazelcast.map.impl.operation.HDPutOperation.runInternal(HDPutOperation.java:18)
	at com.hazelcast.map.impl.operation.HDMapOperation.run(HDMapOperation.java:88)
	at com.hazelcast.spi.Operation.call(Operation.java:170)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:210)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:199)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:407)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:434)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:648)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:633)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:592)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:256)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:61)
	at com.hazelcast.client.impl.protocol.task.AbstractPartitionMessageTask.processMessage(AbstractPartitionMessageTask.java:67)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:129)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:109)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:163)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:159)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:127)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:110)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:126)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run(AbstractInvocationFuture.java:251)
	at com.hazelcast.client.impl.protocol.task.AbstractPartitionMessageTask.execute(AbstractPartitionMessageTask.java:78)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.unblock(AbstractInvocationFuture.java:247)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.andThen(AbstractInvocationFuture.java:223)
	at com.hazelcast.client.impl.protocol.task.AbstractPartitionMessageTask.processMessage(AbstractPartitionMessageTask.java:69)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:129)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:109)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:163)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:159)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:127)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:110)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:96)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:33)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:163)
	at com.hazelcast.client.spi.ClientProxy.invokeOnPartition(ClientProxy.java:210)
	at com.hazelcast.client.spi.ClientProxy.invoke(ClientProxy.java:204)
	at com.hazelcast.client.proxy.ClientMapProxy.putInternal(ClientMapProxy.java:584)
	at com.hazelcast.client.proxy.ClientMapProxy.put(ClientMapProxy.java:334)
```

i start with a map with
```
map mapBak1HDSqlIdx key 0 PersonSerializable{personId=0, age=0, firstName='0', lastName='0', salary=0.0, count=0}
map mapBak1HDSqlIdx key 1 PersonDataSerializable{} BasePerson{personId=1, age=1, firstName='1', lastName='1', salary=1.0, count=0}
```
the map has in index set on personId
then i do a put,  to key 0, of a byte array.
I get the exception com.hazelcast.query.QueryException: java.lang.IllegalArgumentException: There is no suitable accessor for 'personId' on class '[B'
but when i check the content of the map is see

```
map mapBak1HDSqlIdx key 0 [B@58d29d9f
map mapBak1HDSqlIdx key 1 PersonDataSerializable{} BasePerson{personId=1, age=1, firstName='1', lastName='1', salary=1.0, count=0}
```

so it looks like the byte array was put in the map despite the exception.
is this expected ?

it's somewhat expected, the record store write succeeded, but the index write failed, we have no atomic/transactional writes, as another example: `IMap.putAll` may fail as a whole, but some of puts may actually be successful and present in `IMap` instance, sure it's better to rollback changes if some part of the operation is failed...

**Comment by cruzmatheus** [comment]
Hello,

Is there any update why is this happening?

**Comment by mmedenjak** [comment]
Hi @cruzmatheus , this was the answer:
>>> it's somewhat expected, the record store write succeeded, but the index write failed, we have no atomic/transactional writes, as another example: IMap.putAll may fail as a whole, but some of puts may actually be successful and present in IMap instance, sure it's better to rollback changes if some part of the operation is failed...

The configuration wasn't correct so part of the operation succeeded while part of the operation failed.

**Comment by cruzmatheus** [comment]
> Hi @cruzmatheus , this was the answer:
> 
> > it's somewhat expected, the record store write succeeded, but the index write failed, we have no atomic/transactional writes, as another example: IMap.putAll may fail as a whole, but some of puts may actually be successful and present in IMap instance, sure it's better to rollback changes if some part of the operation is failed...
> 
> The configuration wasn't correct so part of the operation succeeded while part of the operation failed.

Thanks for the reply @mmedenjak. I'm experiencing something very similar: I've created a index using `IMap.addIndex` and now I'm getting the error above. Is the a way to remove the index from the HazelcastInstance?

**Comment by mmedenjak** [comment]
No, unfortunately, once an index has been added dynamically, it is in use and cannot be removed. You'll have to restart your cluster to remove it.

**Comment by cruzmatheus** [comment]
I see. Thanks for the help @mmedenjak

**Comment by mmedenjak** [comment]
As we're heavily invested in the new query engine, I don't know if it makes sense to spend too much time on this issue.
