### ISSUE TITLE
[V3.12] IMap.addEntryListener with a PagingPredicate serialization problem (Multi-node cluster)

### ISSUE THREAD

**Issue by HeadHunter90** [hazelcast/hazelcast#15049]
Hello, I am trying to automatically sort an IMap with an EntryListener containing a PagingPredicate.
Like in issue https://github.com/hazelcast/hazelcast/issues/12208, I also tried to serialize my comparator but I still get the error that its not serializable. Maybe you can help me?

This is my stacktrace:

`	at com.hazelcast.spi.impl.eventservice.impl.operations.RegistrationOperation.writeInternalImpl(RegistrationOperation.java:53)
	at com.hazelcast.spi.impl.eventservice.impl.operations.AbstractRegistrationOperation.writeInternal(AbstractRegistrationOperation.java:71)
	at com.hazelcast.spi.Operation.writeData(Operation.java:686)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.write(DataSerializableSerializer.java:244)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.write(DataSerializableSerializer.java:51)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.write(StreamSerializerAdapter.java:43)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:154)
	... 21 more
Caused by: com.hazelcast.nio.serialization.HazelcastSerializationException: Failed to serialize 'com.hazelcast.map.impl.query.QueryEventFilter'
	at com.hazelcast.internal.serialization.impl.SerializationUtil.handleSerializeException(SerializationUtil.java:75)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.writeObject(AbstractSerializationService.java:254)
	at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataOutput.writeObject(ByteArrayObjectDataOutput.java:376)
	at com.hazelcast.map.impl.EventListenerFilter.writeData(EventListenerFilter.java:71)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.write(DataSerializableSerializer.java:244)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.write(DataSerializableSerializer.java:51)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.write(StreamSerializerAdapter.java:43)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.writeObject(AbstractSerializationService.java:252)
	... 30 more
Caused by: com.hazelcast.nio.serialization.HazelcastSerializationException: Failed to serialize 'com.hazelcast.query.PagingPredicate'
	at com.hazelcast.internal.serialization.impl.SerializationUtil.handleSerializeException(SerializationUtil.java:75)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.writeObject(AbstractSerializationService.java:254)
	at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataOutput.writeObject(ByteArrayObjectDataOutput.java:376)
	at com.hazelcast.map.impl.query.QueryEventFilter.writeData(QueryEventFilter.java:60)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.write(DataSerializableSerializer.java:244)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.write(DataSerializableSerializer.java:51)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.write(StreamSerializerAdapter.java:43)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.writeObject(AbstractSerializationService.java:252)
	... 36 more
Caused by: java.lang.NullPointerException
	at com.hazelcast.query.PagingPredicate.writeData(PagingPredicate.java:343)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.write(DataSerializableSerializer.java:244)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.write(DataSerializableSerializer.java:51)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.write(StreamSerializerAdapter.java:43)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.writeObject(AbstractSerializationService.java:252)
	... 42 more`

Thank you

**Comment by HeadHunter90** [comment]
Solution: pagingPredicate.setIterationType(IterationType.ENTRY);
