### ISSUE TITLE
ClientCacheNearCacheInvalidationTest.when_shuttingDown_invalidationEventIsNotReceived

### ISSUE THREAD

**Issue by lazerion** [hazelcast/hazelcast#15067]
Job uses `master` branch.

Failed on Hazelcast-3.x-sonar: [Job 120](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-sonar/120/testReport/junit/com.hazelcast.client.cache.impl.nearcache/ClientCacheNearCacheInvalidationTest/when_shuttingDown_invalidationEventIsNotReceived_format_BINARY__fromMember_true_/)

Stacktrace :
```
java.lang.AssertionError: Expected no further Near Cache invalidation events than 0, but received 1 (NearCacheStatsImpl{ownedEntryCount=0, ownedEntryMemoryCost=0, creationTime=1558402501728, hits=0, misses=0, ratio=NaN%, evictions=0, expirations=0, invalidations=0, lastPersistenceTime=0, persistenceCount=0, lastPersistenceDuration=0, lastPersistenceWrittenBytes=0, lastPersistenceKeyCount=0, lastPersistenceFailure=''})
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.client.cache.impl.nearcache.ClientCacheNearCacheInvalidationTest$5.run(ClientCacheNearCacheInvalidationTest.java:484)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1312)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1414)
	at com.hazelcast.client.cache.impl.nearcache.ClientCacheNearCacheInvalidationTest.assertNoFurtherInvalidationThan(ClientCacheNearCacheInvalidationTest.java:490)
	at com.hazelcast.client.cache.impl.nearcache.ClientCacheNearCacheInvalidationTest.assertNoFurtherInvalidation(ClientCacheNearCacheInvalidationTest.java:476)
	at com.hazelcast.client.cache.impl.nearcache.ClientCacheNearCacheInvalidationTest.when_shuttingDown_invalidationEventIsNotReceived(ClientCacheNearCacheInvalidationTest.java:333)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by lazerion** [comment]
reopened #14978
