### ISSUE TITLE
ClientClusterRestartEventTest.testSingleMemberRestart

### ISSUE THREAD

**Issue by mdogan** [hazelcast/hazelcast#15203]
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/1792/testReport/junit/com.hazelcast.client/ClientClusterRestartEventTest/testSingleMemberRestart/

```
java.lang.AssertionError: CountDownLatch failed to complete within 120 seconds, count left: 1
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:1186)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:1171)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:1159)
	at com.hazelcast.client.ClientClusterRestartEventTest.testSingleMemberRestart(ClientClusterRestartEventTest.java:107)
```

**Comment by mmedenjak** [comment]
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/3227/

**Comment by ihsandemir** [comment]
I examined the failing test (http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/3227/) log. It looks like a timing problem for the test. Hence, a test fix should be OK for this test. The client connection attempt finishes before the new member can start.

The failing log:
```
12:49:50,122  INFO |testSingleMemberRestart| - [LifecycleService] testSingleMemberRestart - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
12:49:50,128  WARN |testSingleMemberRestart| - [ClusterConnectorService] hz.client_67.cluster- - hz.client_67 [dev] [4.0-SNAPSHOT] Exception during initial connection to [127.0.0.1]:5701: com.hazelcast.core.HazelcastException: java.io.IOException: Can not connected to [127.0.0.1]:5701: instance does not exist
12:49:50,128  WARN |testSingleMemberRestart| - [ClusterConnectorService] hz.client_67.cluster- - hz.client_67 [dev] [4.0-SNAPSHOT] Unable to get live cluster connection, attempt 2 of 2.
12:49:50,128  WARN |testSingleMemberRestart| - [ClusterConnectorService] hz.client_67.cluster- - hz.client_67 [dev] [4.0-SNAPSHOT] Unable to connect to any address for cluster: dev. The following addresses were tried: [[127.0.0.1]:5701]
12:49:50,128  WARN |testSingleMemberRestart| - [ClusterConnectorService] hz.client_67.cluster- - hz.client_67 [dev] [4.0-SNAPSHOT] Could not connect to any cluster, shutting down the client: Unable to connect to any cluster.
12:49:50,129  INFO |testSingleMemberRestart| - [LifecycleService] hz.client_67.clientShutdown- - hz.client_67 [dev] [4.0-SNAPSHOT] HazelcastClient 4.0-SNAPSHOT (20190920 - e0eb5b9) is SHUTTING_DOWN
12:49:50,152  INFO |testSingleMemberRestart| - [LifecycleService] hz.client_67.clientShutdown- - hz.client_67 [dev] [4.0-SNAPSHOT] HazelcastClient 4.0-SNAPSHOT (20190920 - e0eb5b9) is SHUTDOWN
```
In this test, we expect that the client does not shutdown on connection attempt failure and retry until the new server comes up again.
