### ISSUE TITLE
Can't boot server with only one node

### ISSUE THREAD

**Issue by mufumbo** [hazelcast/hazelcast#15214]
Anyone else having this issue when upgrading from `3.11.4` to `3.12.1` ?

We used to be able to boot hazelcast with only one node. 

For example:
- development, `alpha`, `beta` environments. 
- production machines that don't need to communicate with others, but use same codebase. 

I get this log 
```
19-06-24 21:59:24.545 WARN  [ead-0] c.h.s.i.o.impl.OperationRunnerImpl       - [88.99.31.152]:5701 [craft-cluster] [3.12.1] While sending op error... op: com.hazelcast.internal.cluster.impl.operations.JoinMastershipClaimOp{serviceName='hz:core:clusterService', identityHash=1744193757, partitionId=-1, replicaIndex=0, callId=2, invocationTime=1561413564544 (2019-06-24 21:59:24.544), waitTimeout=-1, callTimeout=60000}, error: java.lang.IllegalArgumentException: Target is this node! -> [88.99.31.152]:5701
java.lang.IllegalArgumentException: Target is this node! -> [88.99.31.152]:5701, response: ErrorResponse{callId=2, urgent=true, cause=java.lang.IllegalArgumentException: Target is this node! -> [88.99.31.152]:5701}
	at com.hazelcast.spi.impl.operationservice.impl.OutboundResponseHandler.send(OutboundResponseHandler.java:111)
	at com.hazelcast.spi.impl.operationservice.impl.OutboundResponseHandler.sendResponse(OutboundResponseHandler.java:94)
	at com.hazelcast.spi.Operation.sendResponse(Operation.java:456)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.sendResponseAfterOperationError(OperationRunnerImpl.java:374)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.handleOperationError(OperationRunnerImpl.java:368)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:201)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:416)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:153)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:123)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:110)
```

And this one:
```
19-06-24 21:59:36.546 ERROR [ead-0] c.h.i.c.i.o.JoinMastershipClaimOp        - [88.99.31.152]:5701 [craft-cluster] [3.12.1] Target is this node! -> [88.99.31.152]:5701
java.lang.IllegalArgumentException: Target is this node! -> [88.99.31.152]:5701
	at com.hazelcast.spi.impl.operationservice.impl.OutboundResponseHandler.checkTarget(OutboundResponseHandler.java:219)
	at com.hazelcast.spi.impl.operationservice.impl.OutboundResponseHandler.sendNormalResponse(OutboundResponseHandler.java:123)
	at com.hazelcast.spi.impl.operationservice.impl.OutboundResponseHandler.sendResponse(OutboundResponseHandler.java:99)
	at com.hazelcast.spi.Operation.sendResponse(Operation.java:456)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.handleResponse(OperationRunnerImpl.java:242)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:214)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:199)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:416)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:153)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:123)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:110)
```

My configuration:
```
            <network port="${cluster.port}" port-auto-increment="false" public-address="${serverIp}">
                <join>
                    <multicast enabled="false" multicast-timeout-seconds="2"/>
                    <tcp-ip enabled="true" connection-timeout-seconds="2">
                        <members>${hazelcast.members}</members>
                    </tcp-ip>
                </join>
            </network>
```

Properties:
```
cluster.port=${cluster.port?:5701}
hazelcast.members=${serverIp?:127.0.0.1}
```

**Comment by jain-chinmay** [comment]
I am having the same problem. Booting a server with just one node and then adding another afterwards.

**Comment by vbekiaris** [comment]
@mufumbo thanks for the detailed info. I can reproduce the issue when using `127.0.0.1` as public  address while using local LAN IP (eg `192.168.1.11`) as cluster members address, but probably you might hit it with another address configuration.

Unless your members are configured with NAT, there is no reason to set an explicit public address. Also, setting the public-address to 127.0.0.1 (as I did to reproduce the issue) seems like a misconfiguration, since public address is meant to advertise the address to which other cluster members have to connect to, in order to join this member. Removing the `public-address` attribute from your configuration, should allow your member to start normally. See more info about `public-address` configuration in https://docs.hazelcast.org/docs/3.12.5/manual/html-single/index.html#public-address. If you feel we need to investigate this more, please post what your actual values for `${serverIp}` and `${hazelcast.members}` properties are when you hit the issue and re-open it.
