### ISSUE TITLE
ClientDynamicClusterConfigTest.testRingbufferConfig_whenConfiguredWithRingbufferStore_byFactoryImplementation

### ISSUE THREAD

**Issue by lazerion** [hazelcast/hazelcast#15237]
maintenance-3.x 

- There seems to be no recent change since June 10, however, this test failed today, therefore I could not provide `commit` hash. Also, assigned as `low` priority, I will update issue with higher priority if stable reproducible.

- Failed on [Hazelcast-3.maintenance-IbmJDK7](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.maintenance-IbmJDK7/56/testReport/com.hazelcast.client.impl.clientside/ClientDynamicClusterConfigTest/testRingbufferConfig_whenConfiguredWithRingbufferStore_byFactoryImplementation/)

- Stack Trace
```
java.lang.AssertionError: expected:<RingbufferConfig{name='f8c9c925-edb2-4735-b665-7ca93b0527e3', capacity=33, backupCount=4, asyncBackupCount=2, timeToLiveSeconds=59, inMemoryFormat=OBJECT, ringbufferStoreConfig=RingbufferStoreConfig{enabled=true, className='null', properties={}}, quorumName=null, mergePolicyConfig=MergePolicyConfig{policy='AnotherMergePolicy', batchSize=31415}}> but was:<RingbufferConfig{name='f8c9c925-edb2-4735-b665-7ca93b0527e3', capacity=10000, backupCount=1, asyncBackupCount=0, timeToLiveSeconds=0, inMemoryFormat=BINARY, ringbufferStoreConfig=RingbufferStoreConfig{enabled=false, className='null', properties={}}, quorumName=null, mergePolicyConfig=MergePolicyConfig{policy='com.hazelcast.spi.merge.PutIfAbsentMergePolicy', batchSize=100}}>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.internal.dynamicconfig.DynamicConfigTest.assertConfigurationsEqualsOnAllMembers(DynamicConfigTest.java:738)
	at com.hazelcast.internal.dynamicconfig.DynamicConfigTest.testRingbufferConfig_whenConfiguredWithRingbufferStore_byFactoryImplementation(DynamicConfigTest.java:278)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:95)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:56)
	at java.lang.reflect.Method.invoke(Method.java:620)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.util.concurrent.FutureTask.run(FutureTask.java:274)
	at java.lang.Thread.run(Thread.java:809)
```

**Comment by vbekiaris** [comment]
The test failed due to an unexpected cluster split during the test caused by load on the machine.

Test starts:
```
03:33:56,545  INFO |testRingbufferConfig_whenConfiguredWithRingbufferStore_byFactoryImplementation| - [system] Thread-3059 - [127.0.0.1]:5701 [dev] [3.12.2-SNAPSHOT] Hazelcast 3.12.2-SNAPSHOT (20190701 - 14451f7) starting at [127.0.0.1]:5701
```

Two member cluster is formed:
```
03:34:05,244  INFO |testRingbufferConfig_whenConfiguredWithRingbufferStore_byFactoryImplementation| - [ClusterService] hz._hzInstance_3779_dev.priority-generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [3.12.2-SNAPSHOT]

Members {size:2, ver:2} [
        Member [127.0.0.1]:5701 - 3a3d8583-6841-467f-a0da-c0e1829e379b this
        Member [127.0.0.1]:5702 - 9df828ab-2139-42a2-b2e6-416fb5fbf0f2
]
```

Health monitor in the meanwhile reports 92,61% system load, 12K thread count:
```
03:34:00,382  INFO |testMapConfig_withEntryListenerImplementation| - [HealthMonitor] hz._hzInstance_3812_dev.HealthMonitor - [127.0.0.1]:5702 [dev] [3.12.2-SNAPSHOT] processor
s=72, physical.memory.total=0, physical.memory.free=106.8G, swap.space.total=4.0G, swap.space.free=4.0G, heap.memory.used=3.1G, heap.memory.free=922.1M, heap.memory.total=4.0G
, heap.memory.max=4.0G, heap.memory.used/total=77.48%, heap.memory.used/max=77.48%, minor.gc.count=0, minor.gc.time=0ms, major.gc.count=0, major.gc.time=0ms, load.process=3.28
%, load.system=92.61%, load.systemAverage=15.42, thread.count=12671, thread.peakCount=12671, cluster.timeDiff=-2, event.q.size=0, executor.q.async.size=0, executor.q.client.si
ze=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, 
executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=12, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.clust
er.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=0, clie
ntEndpoint.count=0, connection.active.count=0, client.connection.count=0, connection.count=0
```

Client starts almost a minute later. Starting the client is literally the next statement after starting the cluster in the test's setup method:

```
03:35:08,483  INFO |testRingbufferConfig_whenConfiguredWithRingbufferStore_byFactoryImplementation| - [ClientMembershipListener] hz.client_2599.event-30047 - hz.client_2599 [d
ev] [3.12.2-SNAPSHOT]

Members [2] {
        Member [127.0.0.1]:5701 - 3a3d8583-6841-467f-a0da-c0e1829e379b
        Member [127.0.0.1]:5702 - 9df828ab-2139-42a2-b2e6-416fb5fbf0f2
}
```

Shortly followed by heartbeat timeout and the cluster being split to two separate single-member clusters:
```
03:35:10,578  WARN |testRingbufferConfig_whenConfiguredWithRingbufferStore_byFactoryImplementation| - [ClusterHeartbeatManager] hz._hzInstance_3779_dev.cached.thread-31 - [127
.0.0.1]:5701 [dev] [3.12.2-SNAPSHOT] Suspecting Member [127.0.0.1]:5702 - 9df828ab-2139-42a2-b2e6-416fb5fbf0f2 because it has not sent any heartbeats since 2019-07-01 03:34:09
.146. Now: 2019-07-01 03:35:10.577, heartbeat timeout: 60000 ms, suspicion level: 1.00
```

This results in the ringbuffer config being added to the single member that is still connected to the client after the split, while the other member is unaware of the added ringbuffer config -> reports a default ringbuffer config and assertion fails.
