### ISSUE TITLE
HazelcastStarterTest.testHazelcastInstanceCompatibility_withStarterInstance

### ISSUE THREAD

**Issue by lazerion** [hazelcast/hazelcast#15263]
- Fails on `Hazelcast-3.x-IbmJDK8-fips-nightly`, `Hazelcast-3.x-sonar` and `Hazelcast-3.x-nightly`
- Starting from [this Build #45](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK8-fips-nightly/45/)
- Seems from commit: 6531b52
- Error Message
```
java.lang.ClassNotFoundException: com.hazelcast.instance.impl.HazelcastInstanceProxy
```
- Stack trace
```
com.hazelcast.test.starter.GuardianException: java.lang.ClassNotFoundException: com.hazelcast.instance.impl.HazelcastInstanceProxy
	at com.hazelcast.test.starter.HazelcastStarterUtils.rethrowGuardianException(HazelcastStarterUtils.java:53)
	at com.hazelcast.test.starter.HazelcastStarter.getNode(HazelcastStarter.java:127)
	at com.hazelcast.instance.impl.TestUtil.getNode(TestUtil.java:74)
	at com.hazelcast.test.HazelcastTestSupport.getNode(HazelcastTestSupport.java:258)
	at com.hazelcast.test.HazelcastTestSupport.getNodeEngineImpl(HazelcastTestSupport.java:266)
	at com.hazelcast.test.starter.constructor.test.MergePolicyProviderConstructorTest.testConstructor(MergePolicyProviderConstructorTest.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.lang.Thread.run(Thread.java:811)
Caused by: java.lang.ClassNotFoundException: com.hazelcast.instance.impl.HazelcastInstanceProxy
	at java.net.URLClassLoader.findClass(URLClassLoader.java:609)
	at com.hazelcast.test.starter.HazelcastAPIDelegatingClassloader.loadClass(HazelcastAPIDelegatingClassloader.java:118)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:853)
	at com.hazelcast.test.starter.HazelcastStarter.getHazelcastInstanceImpl(HazelcastStarter.java:162)
	at com.hazelcast.test.starter.HazelcastStarter.getNode(HazelcastStarter.java:120)
	... 16 more
```

**Comment by vojtechtoman** [comment]
`HazelcastInstanceProxy` has been moved to an `impl` package in 4.0. I will check with @vbekiaris whether it still makes sense to test 4.0 against older versions in these tests (this means adapting `HazelcastStarter` to use original packages for older versions), or whether we should disable the tests for now until it makes sense to re-instante them again.

**Comment by Holmistr** [comment]
@vbekiaris @vojtechtoman Guys, could you please take a look at this? The test is constantly failing for quite some time :)

**Comment by vbekiaris** [comment]
Making a PR to ignore `HazelcastStarterTest` as @vojtechtoman suggested above, it makes no sense to test `HazelcastStarter` in 4.x with 3.x instances
