### ISSUE TITLE
MapEventJournalExpiringTest.skipsEventsWhenExpired

### ISSUE THREAD

**Issue by tezc** [hazelcast/hazelcast#15295]
Failed on Sonar : http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-sonar/170/testReport/com.hazelcast.map.impl.journal/MapEventJournalExpiringTest/skipsEventsWhenExpired/

_master_ (commit 54d318a318af4831876b3b72db233cef93f58625)

**Stacktrace**
```
java.lang.UnsupportedOperationException: Cannot subscribe to event journal because it is either not configured or disabled for com.hazelcast.spi.DistributedObjectNamespace@a66a38da
	at com.hazelcast.internal.journal.EventJournalReadOperation.beforeRun(EventJournalReadOperation.java:81)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:197)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:416)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:153)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:123)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:110)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:126)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run(AbstractInvocationFuture.java:251)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
```

**Comment by vojtechtoman** [comment]
When `EventJournalConfig` was moved inside `MapConfig` and `CacheConfig`, the fallback to the "default" event journal config was removed. (Only the fallback to the "default" `MapConfig`/`CacheConfig` remained which is used when config for map/cache X cannot be found.) `MapEventJournalExpiringTest` relied on this behavior. What happens now is that every new `MapConfig`/`CacheConfig` instance (created using `new`, which is what the test does) always has a default (disabled) `EventJournalConfig`, which means that the "default" event journal config is never used. I fixed the test by adding the `MapConfig` using `addMapConfig` in which case the copy constructor (copying the journal config from the "default" map) is used.
