### ISSUE TITLE
CP Members not reachable

### ISSUE THREAD

**Issue by tamademicheli** [hazelcast/hazelcast#15299]
Hallo im experiencing a strange behaviour and i cannot clarify it:
- Hazecast 3.12, Client and Members
- Openshift 3.9, kubernetes discovery mechanism. using the hazelcast openshift official template
- Members java version (the one of your 3.12.1 image)
- Client uses openjdk8 latest version (docker image)
- 3 Members.

**client network configuration:**
```
 clientConfig.getConnectionStrategyConfig().setReconnectMode(ClientConnectionStrategyConfig.ReconnectMode.ASYNC);
        clientConfig.getConnectionStrategyConfig().getConnectionRetryConfig().setInitialBackoffMillis(1000)
                .setMaxBackoffMillis(20000)
                .setMultiplier(100)
                .setFailOnMaxBackoff(false)
                .setJitter(0.2)
                .setEnabled(true);
```

Server configuration
`<?xml version="1.0" encoding="UTF-8"?>
        <hazelcast xsi:schemaLocation="http://www.hazelcast.com/schema/config hazelcast-config-3.10.xsd"
                       xmlns="http://www.hazelcast.com/schema/config"
                       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
          <group>
              <name>qnnect</name>
          </group>
          <management-center enabled="true" update-interval="3">http://management-center:8080/hazelcast-mancenter</management-center>
          <network>
            <join>
              <multicast enabled="false"/>
              <kubernetes enabled="true"/>
            </join>
          </network>
          <cp-subsystem>
              <cp-member-count>3</cp-member-count>
          </cp-subsystem>
        </hazelcast>`

I use fenced locks to guarantee a single execution of a task by the clients. 
`Lock lock = hazelcastInstance.getCPSubsystem().getLock(lockKey);

        if (lock.tryLock()) {
            StopWatch sw = new StopWatch();
            sw.start();
            try {
                log.debug("Executing Cluster Locked Operation: {}", lockKey);
                Object proceed = execute(joinPoint);
                log.debug("Executed Cluster Locked Operation: {} in ms: {}", lockKey, sw.getTime());

                return proceed;
            } catch (Throwable t) {
                log.warn("Executed Cluster Locked Operation: {} in ms: {}, with the following Error: {}", lockKey, sw.getTime(), t.getMessage());
                throw t;
            } finally {
                lock.unlock();
            }
        } else {
            log.debug("Skip Execution, Operation:  {} is currently locked on the Cluster.", lockKey);
        }
`
**Problem**

I didn't figured out yet when this occurs, but happens when either the members restarts (i.E an update of Hazelcast image by your side) or the client restarts.

![image](https://user-images.githubusercontent.com/24875849/60959342-4ee1d680-a308-11e9-8ae2-9d4c9264c723.png)

i got this exception along the way and the clients cannot connect to the CP subsystem anymore  (see below).

After restarting the subsystems with the man-center the issue disappear, but it it will come again.
`2019-07-10 08:24:40 [XXXScheduler-1] ERROR org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
com.hazelcast.core.OperationTimeoutException: ClientInvocation{clientMessage = ClientMessage{connection=null, length=22, correlationId=7052, operation=CPGroup.createCPGroup, messageType=2101, partitionId=-1, isComplete=false, isRetryable=true, isEvent=false, writeOffset=0}, objectName = EmailReminderScheduler.emailReminderTrigger(), target = random, sendConnection = ClientConnection{alive=true, connectionId=5, channel=NioChannel{/10.1.26.98:49354->/10.1.12.208:5701}, remoteEndpoint=[10.1.12.208]:5701, lastReadTime=2019-07-10 08:24:40.532, lastWriteTime=2019-07-10 08:24:39.707, closedTime=never, connected server version=3.12.1}} timed out because exception occurred after client invocation timeout 120000 ms. Current time: 2019-07-10 08:24:40.532. Start time: 2019-07-10 08:21:46.227. Total elapsed time: 174306 ms. 
	at com.client.spi.impl.ClientInvocation.newOperationTimeoutException(ClientInvocation.java:333)
...
	at com.hazelcast.client.spi.impl.ClientResponseHandlerSupplier$ResponseThread.run(ClientResponseHandlerSupplier.java:182)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:96)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:33)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:163)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.join(AbstractInvocationFuture.java:144)
	at com.hazelcast.client.cp.internal.datastructures.proxy.ClientRaftProxyFactory.getGroupId(ClientRaftProxyFactory.java:122)
	at com.hazelcast.client.cp.internal.datastructures.proxy.ClientRaftProxyFactory.createProxy(ClientRaftProxyFactory.java:70)
	at com.hazelcast.client.cp.internal.CPSubsystemImpl.getLock(CPSubsystemImpl.java:69)
	at xxxxxxxxxxxxxx.xxx.x.x.x.x.x.executeWithDistributedLock(ClusterScheduledAspect.java:57)
	at sun.reflect.GeneratedMethodAccessor470.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:629)
...
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)
...
...
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
...
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.hazelcast.spi.exception.WrongTargetException: WrongTarget! local: Member [10.1.12.208]:5701 - 47c8db10-f7b7-4f4e-a02f-ab7b68290c2a this, expected-target: null, partitionId: 109, replicaIndex: 0, operation: com.hazelcast.cp.internal.operation.DefaultRaftReplicateOp, service: hz:core:raft
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.newTargetNullException(Invocation.java:336)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.initInvocationTarget(Invocation.java:289)
...
	at java.lang.Thread.run(Thread.java:748)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:126)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run(AbstractInvocationFuture.java:251)
...
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)`

**Comment by metanet** [comment]
Hi @tamademicheli 

Thanks for reporting the issue. 

CP member restarts are a bit different than other "AP" Hazelcast members. When you shut down a CP member, or when it fails, you need to remove that member from CP Subsystem via making the "Remove CP Member" API call. Then, when you restart it, or start a new member from scratch, if you want this member to participate to CP Subsystem, you need to make another API call: "Promote Local Member to a CP Member". You can see documentation for these APIs in the following link: https://docs.hazelcast.org/docs/3.12.1/manual/html-single/index.html#cp-subsystem-management-apis

The thing with CP Subsystem is, even though we did our best to make its behavior close to the regular "Hazelcast way", there are certain things that cannot be done automatically and require user intervention, like the APIs I described here. 

Please don't hesitate to ping us if you have more questions.

Regards,

**Comment by tamademicheli** [comment]
Thanks a lot for the link i couldn't find it so far, for the moment we falled back to the deprecated ILock... how can i fix this "properly" this? i am sure the Fenced Lock is more reliable the ILock, but if a member is not reachable, in my use case, i can restart it without particular problems. Do you have some best practices to share ?

**Comment by afilipchik** [comment]
so, I hit something like that today and after some debugging it think the issue is in the way kube integration is done. What had: 3 pods running with CP enabled. During upgrades cluster was constantly getting into a unrecoverable state. The reason is in the previous post, when kube shuts down the pod, hazelcast doesn't remove the instance from CP System. Because of it everything that tries to access it eventually dies. New nodes can;t join it as it thinks that it has enough nodes which are unavailable (even though they are long gone).

it doesn't look like a proper kubernetes integration, as it is an environment where pods are coming and going all the time. Expected behavior will be something along:
When app receives a shutdown signal from kube it should: 
a) remove itself from CP 
b) Notify other members that spot is available, so new non participant can join
c)When new instance is coming up it should check whether CP has empty spots and join

Or some other way that assumes that everything can change. maybe statefull sets with preserved UUID so it can rejoin after the startup?

**Comment by saimonsez** [comment]
Do you have any news about this issue or something like a best practice to handle this situation?

**Comment by mmedenjak** [comment]
@saimonsez as mentioned in the comment [here](https://github.com/hazelcast/hazelcast/issues/15299#issuecomment-510793887), all membership changes for the CP subsystem need to be manual and explicit. Not sure if that answers your question.

@afilipchik since I don't have experience with kubernetes, maybe @leszko can share some thoughts. Not sure how much of your issue applies to your kubernetes usage and how much applies to the CP subsystem.

**Comment by leszko** [comment]
We actually haven't ever tested specifically CP subsystem features in Kubernetes. Created a related GH Issue: https://github.com/hazelcast/hazelcast-kubernetes/issues/262

**Comment by saimonsez** [comment]
As @afilipchik already described, the CP subsystem does not seem to be designed to run on kubernetes or at least it's not clear how things should work. Given the docs and the information in this ticket, dying cluster nodes will cause application failures (exceptions while working with locks) until those API calls are made to remove and add a CP member. Someone or some application code needs to detect that state and fix it. In the meantime any Hazelcast Client using locks has a downtime. At least that was the case when I tried to migrate from ILock to FencedLock using CP subsystem on a kubernetes cluster as a stateful set with 5 pods, if I remember correctly. I have no idea what CP cluster size I was using then.

If this works as designed, there should at least be some documentation on how to avoid any downtime.

**Comment by mmedenjak** [comment]
@saimonsez are you using FencedLock in unsafe mode? Unsafe mode is more closer to how `ILock` used to behave. You can also use the `IMap` lock methods which are basically the same as the 3.x `ILock` methods.

Other than that, `FencedLock` is supposed to be strongly consistent and will not remove members even if they have died. This is by-design to ensure safety of the protocol. You can turn this off with [this configuration option](https://github.com/hazelcast/hazelcast/blob/97ff57ba92dc1fbfa77720885e7db40757999080/hazelcast/src/main/java/com/hazelcast/config/cp/CPSubsystemConfig.java#L215-L238).

**Comment by saimonsez** [comment]
I don't remember if I was using FencedLock in unsafe mode. Anyway, thank you for all the hints. 

How do you want to proceed with this ticket?

**Comment by mmedenjak** [comment]
We'll take a look some time in the near future. Adding to the next release.

**Comment by sancar** [comment]
Hi everyone, 
I see two options here. 
One is to use `missing-cp-member-auto-removal-seconds`
This property should be used carefully. When it is set to a too low value, and a node assumed to be crashed appears back it should be removed from the system `manually`. So this value should be long enough to make sure that a member will not appear back.

https://docs.hazelcast.org/docs/4.1/manual/html-single/index.html#cp-subsystem-configuration 

@tamademicheli and @afilipchik mentions restart scenarios
@afilipchik 
>  maybe stateful sets with preserved UUID so it can rejoin after the startup?

For this, we have introduced `cp persistence` in 4.0. It was not available in 3.12. 
If you create a persistent volume and attach it to your nodes, and also enable cp persistence in hazelcast config, 
the crashing pod should be able to recover its state and continue as a `CP Member` when restarted.
See configuration details here:
https://docs.hazelcast.org/docs/4.1/manual/html-single/index.html#cp-subsystem-persistence
