### ISSUE TITLE
Missing support for nested JSON objects in arrays

### ISSUE THREAD

**Issue by alparslanavci** [hazelcast/hazelcast#15368]
Please see the test case in the following commit: https://github.com/alparslanavci/hazelcast/commit/157b7226573921645803ec1e911fc4eb515f1717

It throws the following exception: 

```
java.lang.ClassCastException: com.hazelcast.internal.json.NonTerminalJsonValue cannot be cast to java.lang.Comparable

    at com.hazelcast.aggregation.impl.MaxAggregator.accumulateExtracted(MaxAggregator.java:27)
    at com.hazelcast.aggregation.impl.AbstractAggregator.accumulate(AbstractAggregator.java:75)
    at com.hazelcast.map.impl.query.AggregationResult.add(AggregationResult.java:85)
    at com.hazelcast.map.impl.query.PartitionScanRunner.run(PartitionScanRunner.java:103)
    at com.hazelcast.map.impl.query.CallerRunsPartitionScanExecutor.execute(CallerRunsPartitionScanExecutor.java:42)
    at com.hazelcast.map.impl.query.QueryRunner.runPartitionScanQueryOnGivenOwnedPartition(QueryRunner.java:206)
    at com.hazelcast.map.impl.query.QueryPartitionOperation.run(QueryPartitionOperation.java:46)
    at com.hazelcast.spi.Operation.call(Operation.java:170)
    at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:210)
    at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:199)
    at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:147)
    at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:125)
    at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:110)
    at ------ submitted from ------.(Unknown Source)
    at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:126)
    at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:79)
    at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:155)
    at com.hazelcast.map.impl.query.QueryEngineImpl.addResultsOfPredicate(QueryEngineImpl.java:199)
    at com.hazelcast.map.impl.query.QueryEngineImpl.doRunOnPartitionThreads(QueryEngineImpl.java:185)
    at com.hazelcast.map.impl.query.QueryEngineImpl.runOnAllPartitions(QueryEngineImpl.java:132)
    at com.hazelcast.map.impl.query.QueryEngineImpl.execute(QueryEngineImpl.java:90)
    at com.hazelcast.map.impl.proxy.MapProxySupport.executeQueryInternal(MapProxySupport.java:1317)
    at com.hazelcast.map.impl.proxy.MapProxyImpl.aggregate(MapProxyImpl.java:856)
    at com.hazelcast.map.impl.proxy.MapProxyImpl.aggregate(MapProxyImpl.java:844)
    at com.hazelcast.json.MapAggregationJsonTest.testArrayWithNestedField(MapAggregationJsonTest.java:122)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
    at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.lang.Thread.run(Thread.java:748)
```

**Comment by ahmetmircik** [comment]
fixed by https://github.com/hazelcast/hazelcast/pull/15430
