### ISSUE TITLE
EntryLoaderInitializationTest.testEagerEntryLoaderInitializesValues_withExpirationTime

### ISSUE THREAD

**Issue by mmedenjak** [hazelcast/hazelcast#15376]
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/2145

```
java.lang.AssertionError: expected:<0> but was:<12>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.map.impl.mapstore.EntryLoaderInitializationTest.testEagerEntryLoaderInitializesValues_withExpirationTime(EntryLoaderInitializationTest.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by mmedenjak** [comment]
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/2313

**Comment by vojtechtoman** [comment]
At least the lazy loader test fails now, too. That might help.

**Comment by vojtechtoman** [comment]
There is very little info in the logs, but there were hiccups in both builds /http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/2145 and http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/2313. I am gravitating to the conclusion that the cause is `GetOperation` retries (most likely in relation to the hiccups) during the second round of `IMap.get()`s in the failing tests. With enough luck, the entry loader may get called multiple times and as a result, `TestEntryLoader.getLoadCallCount()` returns a higher number than expected. I was able to 'reproduce' this failure scenario by throwing a `RetryableHazelcastException` manually.

I will modify `TestEntryLoader` not to count the total number of calls to `load(key)` but to count the number of distinct keys loaded this way instead.

**Comment by vojtechtoman** [comment]
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/2323 - this is the PR builder for the above fix. This time, the test failed in a different place (maybe because of the same reason; not sure yet). I will add temporary debug output to get more clarity.
