### ISSUE TITLE
FencedLockClientBasicTest.test_lockAutoRelease_onClientShutdown

### ISSUE THREAD

**Issue by tezc** [hazelcast/hazelcast#15399]
_master_ (commit 108939ae3c5077d91adc134d87620dde5990cfeb)

Failed on Sonar : http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-sonar/191/testReport/com.hazelcast.client.cp.internal.datastructures.lock/FencedLockClientBasicTest/test_lockAutoRelease_onClientShutdown/

**Stacktrace**
```
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at org.junit.Assert.assertFalse(Assert.java:74)
	at com.hazelcast.client.cp.internal.datastructures.lock.FencedLockClientBasicTest.test_lockAutoRelease_onClientShutdown(FencedLockClientBasicTest.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by tezc** [comment]
http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-ZuluJDK13/9/testReport/junit/com.hazelcast.client.cp.internal.datastructures.lock/FencedLockClientBasicTest/test_lockAutoRelease_onClientShutdown/
