### ISSUE TITLE
BindHandlerTest failures

### ISSUE THREAD

**Issue by lazerion** [hazelcast/hazelcast#15422]
- Fails on `Hazelcast-3.x-ZuluJDK12`, `Hazelcast-3.x-ZuluJDK13`
- Unable to provide commit hash, it is failing for a while, possibly superseded by other failures.
- Fails on [this job](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-ZuluJDK12/19/#showFailuresLink)
- Error Message
```
Internal error: Failed to find the "modifiers" field in method setInternalState.
```
- Stack Trace
```
java.lang.RuntimeException: Internal error: Failed to find the "modifiers" field in method setInternalState.
	at org.powermock.reflect.internal.WhiteboxImpl.sedModifiersToField(WhiteboxImpl.java:2354)
	at org.powermock.reflect.internal.WhiteboxImpl.removeFinalModifierIfPresent(WhiteboxImpl.java:2318)
	at org.powermock.reflect.internal.WhiteboxImpl.setField(WhiteboxImpl.java:2304)
	at org.powermock.reflect.internal.WhiteboxImpl.setInternalState(WhiteboxImpl.java:304)
	at org.powermock.reflect.Whitebox.setInternalState(Whitebox.java:174)
	at com.hazelcast.nio.tcp.BindHandlerTest.setup(BindHandlerTest.java:250)
	at com.hazelcast.nio.tcp.BindHandlerTest.setup(BindHandlerTest.java:161)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:386)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at com.hazelcast.test.HazelcastParallelClassRunner.access$301(HazelcastParallelClassRunner.java:49)
	at com.hazelcast.test.HazelcastParallelClassRunner$TestRunner.run(HazelcastParallelClassRunner.java:162)
	at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: java.lang.NoSuchFieldException: modifiers
	at java.base/java.lang.Class.getDeclaredField(Class.java:2417)
	at org.powermock.reflect.internal.WhiteboxImpl.sedModifiersToField(WhiteboxImpl.java:2348)
	... 20 more

```

kindly check

**Comment by vbekiaris** [comment]
Powermock's `Whitebox.setInternalState` cannot set `final` fields on JDK 12+ (see https://github.com/powermock/powermock/issues/939). Test needs to be refactored
