### ISSUE TITLE
HazelcastProxyFactoryTest and HazelcastClientStarterTest failures

### ISSUE THREAD

**Issue by tezc** [hazelcast/hazelcast#15457]
Failed on nightly build : http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-nightly/206/

master (commit e8a9f6ab789c9e4f8243335ec315415183618e3b)

HazelcastClientStarterTest.testAdvancedClientMap
HazelcastClientStarterTest.testClientLifecycle
HazelcastProxyFactoryTest.testProxyHazelcastInstanceClasses_ofSameVersion_areSame

**Stacktrace**
```
com.hazelcast.test.starter.GuardianException: java.lang.reflect.InvocationTargetException
	at com.hazelcast.test.starter.HazelcastStarterUtils.rethrowGuardianException(HazelcastStarterUtils.java:53)
	at com.hazelcast.test.starter.HazelcastStarter.createInstanceViaHazelcast(HazelcastStarter.java:279)
	at com.hazelcast.test.starter.HazelcastStarter.newHazelcastInstanceWithNetwork(HazelcastStarter.java:222)
	at com.hazelcast.test.starter.HazelcastStarter.newHazelcastInstance(HazelcastStarter.java:109)
	at com.hazelcast.test.starter.HazelcastStarter.newHazelcastInstance(HazelcastStarter.java:69)
	at com.hazelcast.client.starter.HazelcastClientStarterTest.testClientLifecycle(HazelcastClientStarterTest.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.hazelcast.test.starter.HazelcastStarter.createInstanceViaHazelcast(HazelcastStarter.java:271)
	... 16 more
Caused by: java.lang.NoClassDefFoundError: com/hazelcast/serviceprovider/TestRemoteService
	at com.hazelcast.serviceprovider.TestRemoteServiceDescriptor.getService(TestRemoteServiceDescriptor.java:16)
	at com.hazelcast.spi.impl.servicemanager.impl.ServiceManagerImpl.readServiceDescriptors(ServiceManagerImpl.java:178)
	at com.hazelcast.spi.impl.servicemanager.impl.ServiceManagerImpl.registerDefaultServices(ServiceManagerImpl.java:160)
	at com.hazelcast.spi.impl.servicemanager.impl.ServiceManagerImpl.registerServices(ServiceManagerImpl.java:107)
	at com.hazelcast.spi.impl.servicemanager.impl.ServiceManagerImpl.start(ServiceManagerImpl.java:96)
	at com.hazelcast.spi.impl.NodeEngineImpl.start(NodeEngineImpl.java:192)
	at com.hazelcast.instance.Node.start(Node.java:339)
	at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:132)
	at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:218)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:176)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:126)
	at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:58)
	... 21 more
```

**Comment by vojtechtoman** [comment]
The failures are due to commit 2fc81e6 (@pveentjer) in which `RemoteService` was moved from `com.hazelcast.spi` to `com.hazelcast.internal.services`. Both `HazelcastProxyFactoryTest` and `HazelcastClientStarterTest` use `HazelcastStarter` to fetch older 3.x artifacts that do not have the new `RemoteService`.

@pveentjer, I think these tests can simply be disabled until there is 4.1?

**Comment by pveentjer** [comment]
Doesn't make sense to have 3.x compatible tests in the system. So yes, I'm in favor of disabling.

**Comment by vojtechtoman** [comment]
OK, let me disable them
