### ISSUE TITLE
MembershipFailureTest.slave_receives_member_list_from_non_master[fd:phi-accrual]

### ISSUE THREAD

**Issue by tezc** [hazelcast/hazelcast#15458]
_maintenance_ (commit a5b3e6775f19fcb3f56f0840707719514e7d9948)

Failed on IbmJDK7 : http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.maintenance-IbmJDK7/71/testReport/junit/com.hazelcast.internal.cluster.impl/MembershipFailureTest/slave_receives_member_list_from_non_master_fd_phi_accrual_/

**Stacktrace**
```
java.lang.AssertionError: Cluster size is not correct. Expected: 2, actual: 4, instance index: 0
	at org.junit.Assert.fail(Assert.java:88)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSize(HazelcastTestSupport.java:1099)
	at com.hazelcast.test.HazelcastTestSupport$14.run(HazelcastTestSupport.java:1127)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1310)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1327)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:1124)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:1112)
	at com.hazelcast.internal.cluster.impl.MembershipFailureTest.slave_receives_member_list_from_non_master(MembershipFailureTest.java:373)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:95)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:56)
	at java.lang.reflect.Method.invoke(Method.java:620)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.util.concurrent.FutureTask.run(FutureTask.java:274)
	at java.lang.Thread.run(Thread.java:809)
```

**Comment by vbekiaris** [comment]
Analysis of test failure log from build linked above:
```
// test starts at 00:31:59,159, starts members 1 through 4, with 1 being master of initial cluster

// 3 suspects 1, connections mutually removed
00:32:04,192  WARN |slave_receives_member_list_from_non_master[fd:phi-accrual]| - [MembershipManager] slave_receives_member_list_from_non_master - [127.0.0.1]:5703 [dev] [3.12.3-SNAPSHOT] Member [127.0.0.1]:5701 - 11a3257a-e67e-47dc-96a5-78437dff4e05 is suspected to be dead
00:32:04,192  INFO |slave_receives_member_list_from_non_master[fd:phi-accrual]| - [MockNetworkingService] slave_receives_member_list_from_non_master - [127.0.0.1]:5701 [dev] [3.12.3-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5703, connection: MockConnection{localEndpoint=[127.0.0.1]:5701, remoteEndpoint=[127.0.0.1]:5703, alive=false}
00:32:04,192  INFO |slave_receives_member_list_from_non_master[fd:phi-accrual]| - [MockNetworkingService] slave_receives_member_list_from_non_master - [127.0.0.1]:5703 [dev] [3.12.3-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5701, connection: MockConnection{localEndpoint=[127.0.0.1]:5703, remoteEndpoint=[127.0.0.1]:5701, alive=false}

// 3 suspects 2, similarly connections removed
00:32:04,192  WARN |slave_receives_member_list_from_non_master[fd:phi-accrual]| - [MembershipManager] slave_receives_member_list_from_non_master - [127.0.0.1]:5703 [dev] [3.12.3-SNAPSHOT] Member [127.0.0.1]:5702 - 67f39b5b-aac2-4ad1-8f3a-bd9a7e6d2f06 is suspected to be dead
00:32:04,192  INFO |slave_receives_member_list_from_non_master[fd:phi-accrual]| - [MockNetworkingService] slave_receives_member_list_from_non_master - [127.0.0.1]:5702 [dev] [3.12.3-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5703, connection: MockConnection{localEndpoint=[127.0.0.1]:5702, remoteEndpoint=[127.0.0.1]:5703, alive=false}
00:32:04,192  INFO |slave_receives_member_list_from_non_master[fd:phi-accrual]| - [MockNetworkingService] slave_receives_member_list_from_non_master - [127.0.0.1]:5703 [dev] [3.12.3-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5702, connection: MockConnection{localEndpoint=[127.0.0.1]:5703, remoteEndpoint=[127.0.0.1]:5702, alive=false}

// 3 starts mastership claim
00:32:04,192  INFO |slave_receives_member_list_from_non_master[fd:phi-accrual]| - [MembershipManager] slave_receives_member_list_from_non_master - [127.0.0.1]:5703 [dev] [3.12.3-SNAPSHOT] Starting mastership claim process...
00:32:04,193  INFO |slave_receives_member_list_from_non_master[fd:phi-accrual]| - [MembershipManager] slave_receives_member_list_from_non_master - [127.0.0.1]:5703 [dev] [3.12.3-SNAPSHOT] Local MembersView{version=4, members=[MemberInfo{address=[127.0.0.1]:5701, uuid=11a3257a-e67e-47dc-96a5-78437dff4e05, liteMember=false, memberListJoinVersion=1}, MemberInfo{address=[127.0.0.1]:5702, uuid=67f39b5b-aac2-4ad1-8f3a-bd9a7e6d2f06, liteMember=false, memberListJoinVersion=2}, MemberInfo{address=[127.0.0.1]:5703, uuid=0386f1a0-e5ea-4e2f-8ef5-8607732f340e, liteMember=false, memberListJoinVersion=3}, MemberInfo{address=[127.0.0.1]:5704, uuid=9cef15a5-6d86-45cf-b835-2428f1b8acbb, liteMember=false, memberListJoinVersion=4}]} with suspected members: [[127.0.0.1]:5701, [127.0.0.1]:5702] and initial addresses to ask: [Member [127.0.0.1]:5704 - 9cef15a5-6d86-45cf-b835-2428f1b8acbb]

// 4 suspects 1
00:32:04,193  WARN |slave_receives_member_list_from_non_master[fd:phi-accrual]| - [MembershipManager] slave_receives_member_list_from_non_master - [127.0.0.1]:5704 [dev] [3.12.3-SNAPSHOT] Member [127.0.0.1]:5701 - 11a3257a-e67e-47dc-96a5-78437dff4e05 is suspected to be dead
00:32:04,195  INFO |slave_receives_member_list_from_non_master[fd:phi-accrual]| - [MockNetworkingService] slave_receives_member_list_from_non_master - [127.0.0.1]:5701 [dev] [3.12.3-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5704, connection: MockConnection{localEndpoint=[127.0.0.1]:5701, remoteEndpoint=[127.0.0.1]:5704, alive=false}
00:32:04,195  INFO |slave_receives_member_list_from_non_master[fd:phi-accrual]| - [MockNetworkingService] slave_receives_member_list_from_non_master - [127.0.0.1]:5704 [dev] [3.12.3-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5701, connection: MockConnection{localEndpoint=[127.0.0.1]:5704, remoteEndpoint=[127.0.0.1]:5701, alive=false}

// 4 suspects 2
00:32:04,195  WARN |slave_receives_member_list_from_non_master[fd:phi-accrual]| - [MembershipManager] slave_receives_member_list_from_non_master - [127.0.0.1]:5704 [dev] [3.12.3-SNAPSHOT] Member [127.0.0.1]:5702 - 67f39b5b-aac2-4ad1-8f3a-bd9a7e6d2f06 is suspected to be dead
00:32:04,195  INFO |slave_receives_member_list_from_non_master[fd:phi-accrual]| - [MockNetworkingService] slave_receives_member_list_from_non_master - [127.0.0.1]:5702 [dev] [3.12.3-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5704, connection: MockConnection{localEndpoint=[127.0.0.1]:5702, remoteEndpoint=[127.0.0.1]:5704, alive=false}
00:32:04,195  INFO |slave_receives_member_list_from_non_master[fd:phi-accrual]| - [MockNetworkingService] slave_receives_member_list_from_non_master - [127.0.0.1]:5704 [dev] [3.12.3-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5702, connection: MockConnection{localEndpoint=[127.0.0.1]:5704, remoteEndpoint=[127.0.0.1]:5702, alive=false}

// 1 creates immediately connections to 3 & 4
00:32:04,196  INFO |slave_receives_member_list_from_non_master[fd:phi-accrual]| - [MockNetworkingService] hz._hzInstance_2016_dev.cached.thread-4 - [127.0.0.1]:5701 [dev] [3.12.3-SNAPSHOT] Created connection to endpoint: [127.0.0.1]:5703, connection: MockConnection{localEndpoint=[127.0.0.1]:5701, remoteEndpoint=[127.0.0.1]:5703, alive=true}
00:32:04,196  INFO |slave_receives_member_list_from_non_master[fd:phi-accrual]| - [MockNetworkingService] hz._hzInstance_2016_dev.cached.thread-4 - [127.0.0.1]:5701 [dev] [3.12.3-SNAPSHOT] Created connection to endpoint: [127.0.0.1]:5704, connection: MockConnection{localEndpoint=[127.0.0.1]:5701, remoteEndpoint=[127.0.0.1]:5704, alive=true}

// 3 refuses to update members; 1 sent a MembersUpdateOp to 3?
00:32:04,196  WARN |slave_receives_member_list_from_non_master[fd:phi-accrual]| - [ClusterService] hz._hzInstance_2068_dev.priority-generic-operation.thread-0 - [127.0.0.1]:5703 [dev] [3.12.3-SNAPSHOT] Not updating members because caller: [127.0.0.1]:5701 is not known master: [127.0.0.1]:5703

// but 4 un-suspects 1, reason: Valid heartbeat
// ClusterHeartbeatManager#onHeartbeat was invoked
// since HeartbeatOps are dropped by test packet filter,
// probably onHeartbeat was reached via MembersUpdateOp sent from 1?
00:32:04,198  INFO |slave_receives_member_list_from_non_master[fd:phi-accrual]| - [MembershipManager] hz._hzInstance_2076_dev.generic-operation.thread-10 - [127.0.0.1]:5704 [dev] [3.12.3-SNAPSHOT] Removed suspicion from [127.0.0.1]:5701. Reason: Valid heartbeat

// after all is done (test is being torn down due to timeout at this point)
// 3 decides it is the master of its own single-member cluster; all this time
// it was waiting for some response?
00:34:04,204  INFO |slave_receives_member_list_from_non_master[fd:phi-accrual]| - [MembershipManager] hz._hzInstance_2068_dev.cached.thread-2 - [127.0.0.1]:5703 [dev] [3.12.3-SNAPSHOT] Mastership is claimed with: MembersView{version=5, members=[MemberInfo{address=[127.0.0.1]:5703, uuid=0386f1a0-e5ea-4e2f-8ef5-8607732f340e, liteMember=false, memberListJoinVersion=3}]}
```

**Comment by vbekiaris** [comment]
Investigated with @metanet , looks like a timing-related intermittent failure, similar to #11797.
