### ISSUE TITLE
HazelcastClientConfigResolutionTest.testResolveSystemProperty_file_yaml_loadedAsYaml

### ISSUE THREAD

**Issue by tezc** [hazelcast/hazelcast#15460]
_master_ (commit e8a9f6ab789c9e4f8243335ec315415183618e3b)

Failed on IbmJDK8 : http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK8/35/testReport/com.hazelcast.client/HazelcastClientConfigResolutionTest/testResolveSystemProperty_file_yaml_loadedAsYaml/

**Stacktrace**
```
java.lang.NullPointerException
	at com.hazelcast.internal.networking.nio.NioChannel.close0(NioChannel.java:120)
	at com.hazelcast.internal.networking.AbstractChannel.close(AbstractChannel.java:170)
	at com.hazelcast.nio.IOUtil.closeResource(IOUtil.java:339)
	at com.hazelcast.internal.networking.nio.NioNetworking.shutdown(NioNetworking.java:231)
	at com.hazelcast.client.impl.connection.nio.ClientConnectionManagerImpl.stopNetworking(ClientConnectionManagerImpl.java:250)
	at com.hazelcast.client.impl.connection.nio.ClientConnectionManagerImpl.shutdown(ClientConnectionManagerImpl.java:232)
	at com.hazelcast.client.impl.clientside.HazelcastClientInstanceImpl.doShutdown(HazelcastClientInstanceImpl.java:805)
	at com.hazelcast.client.impl.clientside.LifecycleServiceImpl.doShutdown(LifecycleServiceImpl.java:161)
	at com.hazelcast.client.impl.clientside.LifecycleServiceImpl.shutdown(LifecycleServiceImpl.java:140)
	at com.hazelcast.client.impl.clientside.HazelcastClientProxy.shutdown(HazelcastClientProxy.java:297)
	at com.hazelcast.client.HazelcastClientConfigResolutionTest.tearDown(HazelcastClientConfigResolutionTest.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:402)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:50)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:29)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at com.hazelcast.test.AbstractHazelcastClassRunner$1.evaluate(AbstractHazelcastClassRunner.java:302)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:107)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:83)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:379)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:340)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:413)
```

**Comment by vojtechtoman** [comment]
Visibility problem while accessing `NioChannel.outboundPipeline` concurrently or `NioChannel.init()` not called before `close()`?

**Comment by tezc** [comment]
I had a quick look, looks like connection retry is async, so when one thread is here :


https://github.com/hazelcast/hazelcast/blob/489959df24504eff9978829a2c88a1515e87c8b3/hazelcast/src/main/java/com/hazelcast/internal/networking/nio/NioNetworking.java#L285

```
        channels.add(channel);

        channel.init(inboundPipeline, outboundPipeline);
```

other one calls shutdown(). There is a chance that uninitialized channel in `channels` set, leads to NPE. Not sure adding to channels set after initializing covers all the scenarios. 

cc: @pveentjer

**Comment by pveentjer** [comment]
I think @tezc has found the cause. The channel is registered before properly initialized. 

It should be added to the channels after it is properly initialized.
