### ISSUE TITLE
WARNING: JAVA_CLIENT closed thread=hz._hzInstance_1_HZ.IO .thread-out-1 java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#15475]
http://jenkins.hazelcast.com/view/stable/job/stable-x3/25/console

 http://54.147.27.51/~jenkins/workspace/stable-x3/4.0-SNAPSHOT/2019_08_21-07_37_12/hd-idx-put-remove

```
WARNING: [10.0.0.25]:5701 [HZ] [4.0-SNAPSHOT] Connection[id=8, /10.0.0.25:5701->/10.0.0.161:53810, qualifier=null, endpoint=[10.0.0.161]:53810, alive=false, type=JAVA_CLIENT] closed
. Reason: Exception in Connection[id=8, /10.0.0.25:5701->/10.0.0.161:53810, qualifier=null, endpoint=[10.0.0.161]:53810, alive=true, type=JAVA_CLIENT], thread=hz._hzInstance_1_HZ.IO
.thread-out-1
java.lang.IndexOutOfBoundsException
	at java.nio.Buffer.checkBounds(Buffer.java:567)
	at java.nio.HeapByteBuffer.put(HeapByteBuffer.java:187)
	at com.hazelcast.client.impl.protocol.ClientMessageWriter.writeFrame(ClientMessageWriter.java:88)
	at com.hazelcast.client.impl.protocol.ClientMessageWriter.writeTo(ClientMessageWriter.java:36)
	at com.hazelcast.client.impl.protocol.util.ClientMessageEncoder.onWrite(ClientMessageEncoder.java:58)
	at com.hazelcast.internal.networking.nio.NioOutboundPipeline.process(NioOutboundPipeline.java:276)
	at com.hazelcast.internal.networking.nio.NioPipeline.run(NioPipeline.java:234)
	at com.hazelcast.internal.networking.nio.NioThread.processTaskQueue(NioThread.java:341)
	at com.hazelcast.internal.networking.nio.NioThread.selectLoop(NioThread.java:276)
	at com.hazelcast.internal.networking.nio.NioThread.run(NioThread.java:235)
```

```
INFO: hz.client_0 [HZ] [4.0-SNAPSHOT] Authenticated with server [10.0.0.25]:5701, server version:4.0-SNAPSHOT Local address: /10.0.0.161:46730
com.hazelcast.spi.exception.TargetDisconnectedException: Connection closed by the other side
	at com.hazelcast.client.impl.spi.impl.AbstractClientInvocationService$CleanResourcesTask.notifyException(AbstractClientInvocationService.java:221)
	at com.hazelcast.client.impl.spi.impl.AbstractClientInvocationService$CleanResourcesTask.run(AbstractClientInvocationService.java:216)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.client.impl.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:96)
	at com.hazelcast.client.impl.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:33)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:162)
	at com.hazelcast.client.impl.proxy.ClientMapProxy.putAllInternal(ClientMapProxy.java:1734)
	at com.hazelcast.client.impl.proxy.ClientMapProxy.putAll(ClientMapProxy.java:1720)
	at hzcmd.map.txnModel.PutAllTxnModel.timeStep(PutAllTxnModel.java:22)
	at remote.bench.marker.MetricsMarker.flatOut(MetricsMarker.java:53)
	at remote.bench.marker.MetricsMarker.bench(MetricsMarker.java:40)
	at remote.bench.BenchThread.call(BenchThread.java:41)
	at remote.bench.BenchThread.call(BenchThread.java:14)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.EOFException: Remote socket closed!
	at com.hazelcast.internal.networking.nio.NioInboundPipeline.process(NioInboundPipeline.java:116)
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKey(NioThread.java:369)
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKeys(NioThread.java:354)
	at com.hazelcast.internal.networking.nio.NioThread.selectLoop(NioThread.java:280)
	at com.hazelcast.internal.networking.nio.NioThread.run(NioThread.java:235)
```

**Comment by tezc** [comment]
Will be fixed by https://github.com/hazelcast/hazelcast/pull/15472

**Comment by Danny-Hazelcast** [comment]
Hazelcast Enterprise 4.0-SNAPSHOT (20190820 - 6117042, ee42872) starting at [10.0.0.161]:5701

**Comment by Danny-Hazelcast** [comment]
fixed
