### ISSUE TITLE
ClientClusterStateTest.testClusterShutdownDuringMapPutAll

### ISSUE THREAD

**Issue by tezc** [hazelcast/hazelcast#15508]
_master_ (commit 57ac2b5317a0ade45cf1d5be4ca20c05a379daf3)

Failed on Sonar : http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-sonar/225/testReport/com.hazelcast.client.cluster/ClientClusterStateTest/testClusterShutdownDuringMapPutAll/

**Stacktrace**
```
java.lang.AssertionError: All threads could not be finished
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.client.cluster.ClientClusterStateTest.testClusterShutdownDuringMapPutAll(ClientClusterStateTest.java:209)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by tezc** [comment]
`map.putAll` throws RejectedExecutionException, we don't catch it and thread stays in the loop. I'm not sure if this is expected, maybe we wrap it in a HazelcastClientNotActive exception.

```
java.util.concurrent.RejectedExecutionException: Internal executor rejected task: java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@19fc64a4, because client is shutting down...
	at com.hazelcast.client.impl.spi.impl.ClientExecutionServiceImpl.lambda$new$0(ClientExecutionServiceImpl.java:70)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533)
	at java.util.concurrent.ScheduledThreadPoolExecutor.execute(ScheduledThreadPoolExecutor.java:622)
	at com.hazelcast.client.impl.spi.impl.ClientExecutionServiceImpl.execute(ClientExecutionServiceImpl.java:98)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.unblock(AbstractInvocationFuture.java:246)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.andThen(AbstractInvocationFuture.java:222)
	at com.hazelcast.client.impl.spi.impl.ClientInvocationFuture.andThen(ClientInvocationFuture.java:85)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.andThen(AbstractInvocationFuture.java:212)
	at com.hazelcast.client.impl.spi.impl.ClientInvocationFuture.andThen(ClientInvocationFuture.java:80)
	at com.hazelcast.client.impl.proxy.ClientMapProxy.putAllInternal(ClientMapProxy.java:1775)
	at com.hazelcast.client.impl.proxy.ClientMapProxy.putAll(ClientMapProxy.java:1710)
	at com.hazelcast.client.cluster.ClientClusterStateTest$1.run(ClientClusterStateTest.java:178)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by blazember** [comment]
New occurrence: http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/3160/testReport/junit/com.hazelcast.client.cluster/ClientClusterStateTest/testClusterShutdownDuringMapPutAll/

**Comment by ahmetmircik** [comment]
Another failure: http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/3172/

**Comment by sancar** [comment]
I started working on a fix https://github.com/hazelcast/hazelcast/pull/15558, but then I have started to hesitate to do the change. Maybe I just fix the test and continue.

Is it acceptable for putAll to throw RejectedExecutionException or not? A node/client can throw this when internal async executor shut down at the right moment. It goes down to what our internal executors throw when they are closed(currently they are throwing `RejectedExecutionException` and the exception is propagated to users). We could change the exception thrown to Hazelcast(Instance/Client)NotActiveException or keep it as is(that means I just need to fix the test).
