### ISSUE TITLE
Livelock when (de)registering metrics

### ISSUE THREAD

**Issue by viliam-durina** [hazelcast/hazelcast#15503]
The livelock is possible in this method:
```java
    private void incrementMod() {
        for (; ; ) {
            SortedProbeInstances current = sortedProbeInstancesRef.get();
            SortedProbeInstances update = new SortedProbeInstances(current.mod + 1);
            if (sortedProbeInstancesRef.compareAndSet(current, update)) {
                break;
            }
        }
    }
```
Happened when many jet jobs were terminating at the same time on a machine with 72 threads.

The stack trace is: 
```
at com.hazelcast.internal.metrics.impl.MetricsRegistryImpl.incrementMod(MetricsRegistryImpl.java:205)
at com.hazelcast.internal.metrics.impl.MetricsRegistryImpl.deregister(MetricsRegistryImpl.java:265)
```

**Comment by mmedenjak** [comment]
Closing as fixed
