### ISSUE TITLE
HazelcastManifestTransformerTest.testTransformation

### ISSUE THREAD

**Issue by tezc** [hazelcast/hazelcast#15535]
_master_ (commit fa0e04456409bb3aa423e20649130f7e56ce7ffb)

Failed on ZuluJDK13 : http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-ZuluJDK13/9/testReport/junit/com.hazelcast.buildutils/HazelcastManifestTransformerTest/testTransformation/

```
No interactions wanted here:
-> at com.hazelcast.buildutils.HazelcastManifestTransformerTest.testTransformation(HazelcastManifestTransformerTest.java:99)
But found this interaction on mock 'jarOutputStream':
-> at java.base/java.io.DataOutputStream.write(DataOutputStream.java:107)
***
For your reference, here is the list of all invocations ([?] - means unverified).
1. -> at com.hazelcast.buildutils.HazelcastManifestTransformer.modifyOutputStream(HazelcastManifestTransformer.java:203)
2. [?]-> at java.base/java.io.DataOutputStream.write(DataOutputStream.java:107)
3. -> at java.base/java.io.DataOutputStream.write(DataOutputStream.java:88)
4. -> at java.base/java.io.DataOutputStream.write(DataOutputStream.java:88)
5. -> at java.base/java.io.DataOutputStream.write(DataOutputStream.java:88)
6. [?]-> at java.base/java.io.DataOutputStream.write(DataOutputStream.java:107)
7. -> at java.base/java.io.DataOutputStream.write(DataOutputStream.java:88)
8. -> at java.base/java.io.DataOutputStream.write(DataOutputStream.java:88)
9. -> at java.base/java.io.DataOutputStream.write(DataOutputStream.java:88)
10. [?]-> at java.base/java.io.DataOutputStream.write(DataOutputStream.java:107)
11. -> at java.base/java.io.DataOutputStream.write(DataOutputStream.java:88)
12. -> at java.base/java.io.DataOutputStream.write(DataOutputStream.java:88)
13. -> at java.base/java.io.DataOutputStream.write(DataOutputStream.java:88)
14. [?]-> at java.base/java.io.DataOutputStream.write(DataOutputStream.java:107)
15. -> at java.base/java.io.DataOutputStream.write(DataOutputStream.java:88)
16. -> at java.base/java.io.DataOutputStream.write(DataOutputStream.java:88)
17. -> at java.base/java.io.DataOutputStream.write(DataOutputStream.java:88)
18. [?]-> at java.base/java.io.DataOutputStream.write(DataOutputStream.java:107)
19. -> at java.base/java.io.DataOutputStream.write(DataOutputStream.java:88)
20. -> at java.base/java.io.DataOutputStream.write(DataOutputStream.java:88)
21. -> at java.base/java.io.DataOutputStream.write(DataOutputStream.java:88)
22. [?]-> at java.base/java.io.DataOutputStream.write(DataOutputStream.java:107)
23. -> at java.base/java.io.DataOutputStream.write(DataOutputStream.java:88)
24. -> at java.base/java.io.DataOutputStream.write(DataOutputStream.java:88)
25. -> at java.base/java.io.DataOutputStream.write(DataOutputStream.java:88)
26. [?]-> at java.base/java.io.DataOutputStream.write(DataOutputStream.java:107)
27. -> at java.base/java.io.DataOutputStream.write(DataOutputStream.java:88)
28. -> at java.base/java.io.DataOutputStream.write(DataOutputStream.java:88)
29. -> at java.base/java.io.DataOutputStream.write(DataOutputStream.java:88)
30. [?]-> at java.base/java.io.DataOutputStream.write(DataOutputStream.java:107)
31. -> at java.base/java.io.DataOutputStream.write(DataOutputStream.java:88)
32. -> at java.base/java.io.DataOutputStream.write(DataOutputStream.java:88)
33. -> at java.base/java.io.DataOutputStream.write(DataOutputStream.java:88)
34. [?]-> at java.base/java.io.DataOutputStream.write(DataOutputStream.java:107)
35. -> at java.base/java.io.DataOutputStream.write(DataOutputStream.java:88)

.....


6474. [?]-> at java.base/java.io.DataOutputStream.write(DataOutputStream.java:107)
6475. -> at java.base/java.io.DataOutputStream.write(DataOutputStream.java:88)
6476. -> at java.base/java.io.DataOutputStream.write(DataOutputStream.java:88)
6477. -> at java.base/java.io.DataOutputStream.write(DataOutputStream.java:88)
6478. [?]-> at java.base/java.io.DataOutputStream.write(DataOutputStream.java:107)
6479. -> at java.base/java.io.DataOutputStream.write(DataOutputStream.java:88)
6480. -> at java.base/java.io.DataOutputStream.write(DataOutputStream.java:88)
6481. -> at java.base/java.io.DataOutputStream.write(DataOutputStream.java:88)
6482. [?]-> at java.base/java.io.DataOutputStream.write(DataOutputStream.java:107)
6483. -> at java.base/java.io.DataOutputStream.write(DataOutputStream.java:88)
6484. -> at java.base/java.io.DataOutputStream.write(DataOutputStream.java:88)
6485. -> at java.base/java.io.DataOutputStream.write(DataOutputStream.java:88)
6486. -> at java.base/java.io.DataOutputStream.write(DataOutputStream.java:88)
6487. -> at java.base/java.io.DataOutputStream.flush(DataOutputStream.java:123)
6488. -> at com.hazelcast.buildutils.HazelcastManifestTransformer.modifyOutputStream(HazelcastManifestTransformer.java:205)
" at "testTransformation"
```

**Comment by vbekiaris** [comment]
JDK 8 `java.util.jar.Attributes.writeMain` invokes `out.writeBytes(String)` -> `out.write(int)`:
```
    public final void writeBytes(String s) throws IOException {
        int len = s.length();
        for (int i = 0 ; i < len ; i++) {
            out.write((byte)s.charAt(i));
        }
        incCount(len);
    }
```

JDK 13 `java.util.jar.Attributes.java.writeMain` converts String to UTF-8 bytes -> invokes `out.write(byte[]) -> out.write(byte[], int, int)` -> test fails because those invocations are not expected in the test.
