### ISSUE TITLE
RaftCountDownLatchAdvancedTest.testNewRaftGroupMemberSchedulesTimeoutsWithSnapshot

### ISSUE THREAD

**Issue by mmedenjak** [hazelcast/hazelcast#15532]
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/3022

```
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at org.junit.Assert.assertFalse(Assert.java:74)
	at com.hazelcast.cp.internal.datastructures.countdownlatch.RaftCountDownLatchAdvancedTest.lambda$testNewRaftGroupMemberSchedulesTimeoutsWithSnapshot$6(RaftCountDownLatchAdvancedTest.java:197)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1308)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1410)
	at com.hazelcast.cp.internal.datastructures.countdownlatch.RaftCountDownLatchAdvancedTest.testNewRaftGroupMemberSchedulesTimeoutsWithSnapshot(RaftCountDownLatchAdvancedTest.java:187)
```

**Comment by mmedenjak** [comment]
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/3023/testReport/

**Comment by mdogan** [comment]
`RaftCountDownLatchAdvancedTest` was renamed to `CountDownLatchAdvancedTest`. Duplicate of #15708
