### ISSUE TITLE
Flaky test failure UnsafeFencedLockClientBasicTest.test_lockAutoRelease_onClientShutdown

### ISSUE THREAD

**Issue by petrpleshachkov** [hazelcast/hazelcast#15550]
```
Stacktrace
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at org.junit.Assert.assertFalse(Assert.java:74)
	at com.hazelcast.client.cp.internal.datastructures.lock.UnsafeFencedLockClientBasicTest.test_lockAutoRelease_onClientShutdown(UnsafeFencedLockClientBasicTest.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)

```

http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/3106/testReport/junit/com.hazelcast.client.cp.internal.datastructures.lock/UnsafeFencedLockClientBasicTest/test_lockAutoRelease_onClientShutdown/

**Comment by mdogan** [comment]
Looks like the same issue: https://github.com/hazelcast/hazelcast/issues/15399
