### ISSUE TITLE
Moby name collusion throws InvalidConfigurationException

### ISSUE THREAD

**Issue by tezc** [hazelcast/hazelcast#15563]
http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-ZingJDK8/87/testReport/com.hazelcast.map/EntryProcessorTest/test_executeOnEntriesWithPredicate_notTriesToUseIndexes_whenNoIndexAvailable_1__OBJECT_/

**Stacktrace**

```
com.hazelcast.config.InvalidConfigurationException: HazelcastInstance with name 'determined_hypatia' already exists!
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:235)
	at com.hazelcast.test.TestHazelcastInstanceFactory.newHazelcastInstance(TestHazelcastInstanceFactory.java:203)
	at com.hazelcast.test.HazelcastTestSupport.createHazelcastInstance(HazelcastTestSupport.java:201)
	at com.hazelcast.map.EntryProcessorTest.test_executeOnEntriesWithPredicate_notTriesToUseIndexes_whenNoIndexAvailable(EntryProcessorTest.java:1261)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by tezc** [comment]
@galibey Just fyi :)

**Comment by blazember** [comment]
Probably related: http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/3151/testReport/junit/com.hazelcast.cache.impl/InternalCacheRecordStoreTest/batchEventMapShouldBeCleanedAfterRemoveAll/
