### ISSUE TITLE
EntryProcessorTest.test_executeOnEntriesWithPredicate_runsOnBackup_whenIndexesAvailable

### ISSUE THREAD

**Issue by mmedenjak** [hazelcast/hazelcast#15579]
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/3202

```
java.lang.AssertionError: Expecting two predicate#apply method call one on owner, other one on backup expected:<2> but was:<1>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.map.EntryProcessorTest.test_executeOnEntriesWithPredicate_runsOnBackup_whenIndexesAvailable(EntryProcessorTest.java:1293)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by mmedenjak** [comment]
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/3293

**Comment by ahmetmircik** [comment]
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/3790/testReport/junit/com.hazelcast.map/EntryProcessorTest/test_executeOnEntriesWithPredicate_runsOnBackup_whenIndexesAvailable_1__OBJECT_/

**Comment by vojtechtoman** [comment]
The backup operation is asynchronous. Because of the way the test is written, it can happen that the backup operation is not yet applied when the test checks the number of invocations of the test EP.

**Comment by tezc** [comment]
http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-sonar/268/testReport/junit/com.hazelcast.map/EntryProcessorTest/test_executeOnEntriesWithPredicate_runsOnBackup_whenIndexesAvailable_1__OBJECT_/

**Stacktrace**

```
java.lang.AssertionError: Expecting two predicate#apply method call one on owner, other one on backup expected:<2> but was:<1>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.map.EntryProcessorTest.test_executeOnEntriesWithPredicate_runsOnBackup_whenIndexesAvailable(EntryProcessorTest.java:1295)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```
