### ISSUE TITLE
MemberMapInvalidationMetaDataMigrationTest.uuids_migrated_when_source_node_shutdown

### ISSUE THREAD

**Issue by tezc** [hazelcast/hazelcast#15605]
_maintenance_ (commit 6e7aeb7bdfd934ab7b3480062b0da4edb3d800bc)

Failed on Sonar : http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.maintenance-sonar/243/testReport/com.hazelcast.map.impl.nearcache.invalidation/MemberMapInvalidationMetaDataMigrationTest/uuids_migrated_when_source_node_shutdown/

**Stacktrace**

```
java.lang.AssertionError: Expected source and destination partition UUIDs to be the same (source: {0=0cd2b456-9caf-4d88-a07e-5ebd1c1283bd, 1=3764cb3c-58a2-4a3f-82a8-888d2a802bb6, 2=9360d588-2885-4da0-be5f-de86156c41df, 3=92867d1b-02a8-4f92-8f24-bc7713b84161, 4=8fd3fb69-3f60-47dd-b3f1-ef248c5c3e72, 5=12918d8a-8e33-4773-8bb6-0541358e54d4, 6=538369a5-2c3e-4044-8599-bf8b5cb116eb, 7=fcfbe96c-5148-4877-bc4f-939985ae5157, 8=33d5fe0a-ed3e-47cf-9e39-b89c367cfade, 9=d7989532-9303-47ce-8e28-e8230ff28936, 10=0858c649-b5c7-4b1c-8ce5-aec81d39da06}) (destination {0=0cd2b456-9caf-4d88-a07e-5ebd1c1283bd, 1=3764cb3c-58a2-4a3f-82a8-888d2a802bb6, 2=9360d588-2885-4da0-be5f-de86156c41df, 3=92867d1b-02a8-4f92-8f24-bc7713b84161, 4=8fd3fb69-3f60-47dd-b3f1-ef248c5c3e72, 5=12918d8a-8e33-4773-8bb6-0541358e54d4, 6=538369a5-2c3e-4044-8599-bf8b5cb116eb, 7=fcfbe96c-5148-4877-bc4f-939985ae5157, 8=33d5fe0a-ed3e-47cf-9e39-b89c367cfade, 9=d7989532-9303-47ce-8e28-e8230ff28936, 10=32806b46-3cb6-4fbd-ad42-faa591f34560}) expected:<0858c649-b5c7-4b1c-8ce5-aec81d39da06> but was:<32806b46-3cb6-4fbd-ad42-faa591f34560>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at com.hazelcast.map.impl.nearcache.invalidation.MemberMapInvalidationMetaDataMigrationTest.assertPartitionUUIDsEqual(MemberMapInvalidationMetaDataMigrationTest.java:339)
	at com.hazelcast.map.impl.nearcache.invalidation.MemberMapInvalidationMetaDataMigrationTest.uuids_migrated_when_source_node_shutdown(MemberMapInvalidationMetaDataMigrationTest.java:225)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by ahmetmircik** [comment]
same issue with https://github.com/hazelcast/hazelcast-enterprise/issues/2837, closing this one.
