### ISSUE TITLE
MetadataRaftGroupTest.when_metadataClusterNodeFallsFarBehind_then_itInstallsSnapshot

### ISSUE THREAD

**Issue by kwart** [hazelcast/hazelcast#15622]
%subj% test failure on PR builder (master branch):

```
Stacktrace
com.hazelcast.cp.exception.StaleAppendRequestException
	at com.hazelcast.cp.internal.raft.impl.RaftNodeImpl$HeartbeatTask.innerRun(RaftNodeImpl.java:1000)
	at com.hazelcast.cp.internal.raft.impl.task.RaftNodeStatusAwareTask.run(RaftNodeStatusAwareTask.java:47)
	at com.hazelcast.cp.internal.util.PartitionSpecificRunnableAdaptor.run(PartitionSpecificRunnableAdaptor.java:41)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:163)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:159)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:127)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:110)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:137)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run(AbstractInvocationFuture.java:250)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
```
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/3392/testReport/junit/com.hazelcast.cp.internal/MetadataRaftGroupTest/when_metadataClusterNodeFallsFarBehind_then_itInstallsSnapshot/

**Comment by lazerion** [comment]
@mdogan Failed on 07/01 in [Hazelcast-3.x-sonar](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-sonar/lastCompletedBuild/testReport/com.hazelcast.cp.internal/MetadataRaftGroupTest/when_metadataClusterNodeFallsFarBehind_then_itInstallsSnapshot/) 

```
Error Message
com.hazelcast.core.MemberLeftException: Member [127.0.0.1]:5702 - 4ff9e988-e727-47bf-ba03-bcd7b2cf3b29 this has left cluster!
```

**Comment by mdogan** [comment]
@lazerion: 👍 reproduced myself too.
