### ISSUE TITLE
ConnectedClientOperationTest.testNumberOfConnectedClients

### ISSUE THREAD

**Issue by tezc** [hazelcast/hazelcast#15627]
_master_ (maintenance ba4199e2780cdbdca7b2628a5909c92b49b7c801)

Failed on OracleJDK9 : http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-OracleJDK9/41/testReport/com.hazelcast.client/ConnectedClientOperationTest/testNumberOfConnectedClients/

**Stacktrace**

```
java.lang.AssertionError: expected:<6> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.client.ConnectedClientOperationTest.testNumberOfConnectedClients(ConnectedClientOperationTest.java:65)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by ihsandemir** [comment]
When the log is analyzed the error was:

```
java.lang.ClassCastException: java.base/java.util.UUID cannot be cast to java.base/java.lang.String
	at com.hazelcast.client.impl.ClientEngineImpl.getConnectedClientStats(ClientEngineImpl.java:635) [classes/:?]
```

I observed that at the Hazelcast version that the test was run, the operation return was being incorrectly cast to `String` at `Map<String, ClientType> endpoints = future.get();`, and this was corrected in commit 9b836d1163a1585161aaaf854bee77818dde90a7 (ownerless client). Hence, the latest such failing test was before this fix. The latest failing test (http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-OracleJDK9/42/) ran with commit 18aef4311d5edb925e8ca289e0dba397a8207ed3 (Oct 2, 2019) which was before the fix commit (Oct 4, 2019). And the run after 42 does not have this test failure.

Hence, the problem seems to be solved. Closing the issue.
