### ISSUE TITLE
NPE MemberHazelcastInstanceInfoPlugin

### ISSUE THREAD

**Issue by pveentjer** [hazelcast/hazelcast#15629]
```
java.lang.NullPointerException
	at com.hazelcast.internal.diagnostics.MemberHazelcastInstanceInfoPlugin.run(MemberHazelcastInstanceInfoPlugin.java:74)
	at com.hazelcast.internal.diagnostics.DiagnosticsLogFile.renderPlugin(DiagnosticsLogFile.java:128)
	at com.hazelcast.internal.diagnostics.DiagnosticsLogFile.write(DiagnosticsLogFile.java:83)
	at com.hazelcast.internal.diagnostics.Diagnostics$WritePluginTask.run(Diagnostics.java:237)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by pveentjer** [comment]
My guess is that the cluster id can be null.

could be caused by this commit 2632299b3c9d911ecf4c89ec233a5bd449a4816e
