### ISSUE TITLE
SelectWithSelectorFix_TcpIpConnection_BasicTest.lastWriteTime_whenNothingWritten

### ISSUE THREAD

**Issue by tezc** [hazelcast/hazelcast#15628]
_master_ (commit 05fb45237db1fff1e3212f8d56016f89dc2f4935)

Failed on CorrettoJDK11: http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-CorrettoJDK11/30/testReport/com.hazelcast.internal.networking.nio/SelectWithSelectorFix_TcpIpConnection_BasicTest/lastWriteTime_whenNothingWritten/

**Stacktrace**

```
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertNotNull(Assert.java:712)
	at org.junit.Assert.assertNotNull(Assert.java:722)
	at com.hazelcast.internal.nio.tcp.TcpIpConnection_AbstractTest$2.run(TcpIpConnection_AbstractTest.java:166)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1308)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1410)
	at com.hazelcast.internal.nio.tcp.TcpIpConnection_AbstractTest.connect(TcpIpConnection_AbstractTest.java:162)
	at com.hazelcast.internal.nio.tcp.TcpIpConnection_AbstractBasicTest.lastWriteTime_whenNothingWritten(TcpIpConnection_AbstractBasicTest.java:135)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

```
Hiccups measured while running test 'lastWriteTime_whenNothingWritten(com.hazelcast.internal.networking.nio.SelectWithSelectorFix_TcpIpConnection_BasicTest):'
06:46:50, accumulated pauses: 30 ms, max pause: 0 ms, pauses over 1000 ms: 0
06:46:55, accumulated pauses: 38 ms, max pause: 0 ms, pauses over 1000 ms: 0
06:47:00, accumulated pauses: 29 ms, max pause: 1 ms, pauses over 1000 ms: 0
06:47:05, accumulated pauses: 30 ms, max pause: 0 ms, pauses over 1000 ms: 0
06:47:10, accumulated pauses: 32 ms, max pause: 0 ms, pauses over 1000 ms: 0
06:47:15, accumulated pauses: 31 ms, max pause: 0 ms, pauses over 1000 ms: 0
06:47:20, accumulated pauses: 35 ms, max pause: 0 ms, pauses over 1000 ms: 0
06:47:25, accumulated pauses: 39 ms, max pause: 0 ms, pauses over 1000 ms: 0
06:47:30, accumulated pauses: 37 ms, max pause: 1 ms, pauses over 1000 ms: 0
06:47:35, accumulated pauses: 38 ms, max pause: 0 ms, pauses over 1000 ms: 0
06:47:40, accumulated pauses: 37 ms, max pause: 0 ms, pauses over 1000 ms: 0
06:47:45, accumulated pauses: 36 ms, max pause: 0 ms, pauses over 1000 ms: 0
06:47:50, accumulated pauses: 31 ms, max pause: 0 ms, pauses over 1000 ms: 0
06:47:55, accumulated pauses: 31 ms, max pause: 0 ms, pauses over 1000 ms: 0
06:48:00, accumulated pauses: 30 ms, max pause: 0 ms, pauses over 1000 ms: 0
06:48:05, accumulated pauses: 34 ms, max pause: 0 ms, pauses over 1000 ms: 0
06:48:10, accumulated pauses: 36 ms, max pause: 0 ms, pauses over 1000 ms: 0
06:48:15, accumulated pauses: 29 ms, max pause: 0 ms, pauses over 1000 ms: 0
06:48:20, accumulated pauses: 27 ms, max pause: 0 ms, pauses over 1000 ms: 0
06:48:25, accumulated pauses: 34 ms, max pause: 0 ms, pauses over 1000 ms: 0
06:48:30, accumulated pauses: 30 ms, max pause: 0 ms, pauses over 1000 ms: 0
06:48:35, accumulated pauses: 35 ms, max pause: 0 ms, pauses over 1000 ms: 0
06:48:40, accumulated pauses: 31 ms, max pause: 0 ms, pauses over 1000 ms: 0
06:48:45, accumulated pauses: 30 ms, max pause: 0 ms, pauses over 1000 ms: 0
06:48:50, accumulated pauses: 1225 ms, max pause: 1196 ms, pauses over 1000 ms: 1
06:48:55, accumulated pauses: 0 ms, max pause: 0 ms, pauses over 1000 ms: 0
```

**Comment by mmedenjak** [comment]
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/3646

**Comment by mmedenjak** [comment]
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/3648

**Comment by vbekiaris** [comment]
Unable to reproduce, #15761 adds logging to verify a potential explanation if this fails again in the future.

**Comment by mdogan** [comment]
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/4066/testReport/junit/com.hazelcast.internal.networking.nio/SelectWithSelectorFix_TcpIpConnection_BasicTest/lastWriteTimeMillis_whenPacketWritten/

**Comment by sancar** [comment]
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/4285/testReport/junit/com.hazelcast.internal.networking.nio/SelectWithSelectorFix_TcpIpConnection_BasicTest/lastWriteTimeMillis_whenPacketWritten/
