### ISSUE TITLE
NPE in `DiagnosticsLogFile#renderPlugin` during member start

### ISSUE THREAD

**Issue by puzpuzpuz** [hazelcast/hazelcast#15647]
When I'm starting an OS member on the latest 4.0-SNAPSHOT with diagnostics enabled, I'm getting the following NPE:

```
WARNING: [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] Failed to write file: /home/puzpuzpuz/projects/hzStarter/diagnostics-127.0.0.1_5701-1569844348101-000.log
java.lang.NullPointerException
	at com.hazelcast.internal.diagnostics.MemberHazelcastInstanceInfoPlugin.run(MemberHazelcastInstanceInfoPlugin.java:74)
	at com.hazelcast.internal.diagnostics.DiagnosticsLogFile.renderPlugin(DiagnosticsLogFile.java:128)
	at com.hazelcast.internal.diagnostics.DiagnosticsLogFile.write(DiagnosticsLogFile.java:83)
	at com.hazelcast.internal.diagnostics.Diagnostics$WritePluginTask.run(Diagnostics.java:237)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:305)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:835)
```

The exception is thrown at the following line of `MemberHazelcastInstanceInfoPlugin`:
```
writer.writeKeyValueEntry("clusterId", this.nodeEngine.getClusterService().getClusterId().toString());
```

Here `getClusterId()` returns `null`, thus we have a NPE. This bug seems related with recent UUID changes.

**Comment by vbekiaris** [comment]
fixed by #15640
