### ISSUE TITLE
ClientMessageProtectionTest.testAccumulatedMessageSizeOverflow

### ISSUE THREAD

**Issue by tezc** [hazelcast/hazelcast#15658]
_master_ (commit ea8293d6dbc734c4d03c8830b9c8935c8ba2ba37)

http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-ZingJDK8/92/testReport/com.hazelcast.client.protocol/ClientMessageProtectionTest/testAccumulatedMessageSizeOverflow/

**Stacktrace**

```
java.lang.AssertionError: Expected test to throw an instance of java.io.EOFException
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.rules.ExpectedException.failDueToMissingException(ExpectedException.java:263)
	at org.junit.rules.ExpectedException.access$200(ExpectedException.java:106)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:245)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at com.hazelcast.test.HazelcastParallelClassRunner.access$301(HazelcastParallelClassRunner.java:49)
	at com.hazelcast.test.HazelcastParallelClassRunner$TestRunner.run(HazelcastParallelClassRunner.java:162)
	at java.lang.Thread.run(Thread.java:745)
```

```
20:30:48,156  WARN |testExceededMessageSize| - [TcpIpConnection] hz.frosty_hopper.IO.thread-in-0 - [127.0.0.1]:5306 [testExceededMessageSize] [4.0-SNAPSHOT] Connection[id=1, /127.0.0.1:5306->/127.0.0.1:34202, qualifier=null, endpoint=null, alive=false, type=NONE] closed. Reason: Exception in Connection[id=1, /127.0.0.1:5306->/127.0.0.1:34202, qualifier=null, endpoint=null, alive=true, type=NONE], thread=hz.frosty_hopper.IO.thread-in-0
com.hazelcast.client.impl.protocol.exception.MaxMessageSizeExceeded: The client message size (108 + 806) exceededs the maximum allowed length (800)
	at com.hazelcast.client.impl.protocol.ClientMessageReader.readFrame(ClientMessageReader.java:82) ~[classes/:?]
	at com.hazelcast.client.impl.protocol.ClientMessageReader.readFrom(ClientMessageReader.java:45) ~[classes/:?]
	at com.hazelcast.client.impl.protocol.util.ClientMessageDecoder.onRead(ClientMessageDecoder.java:81) ~[classes/:?]
	at com.hazelcast.internal.networking.nio.NioInboundPipeline.process(NioInboundPipeline.java:131) ~[classes/:?]
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKey(NioThread.java:368) [classes/:?]
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKeys(NioThread.java:353) [classes/:?]
	at com.hazelcast.internal.networking.nio.NioThread.selectLoop(NioThread.java:279) [classes/:?]
	at com.hazelcast.internal.networking.nio.NioThread.run(NioThread.java:234) [classes/:?]
```

Looks like related with : https://github.com/hazelcast/hazelcast/pull/15396

**Comment by mdogan** [comment]
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/3545/testReport/junit/com.hazelcast.client.protocol/ClientMessageProtectionTest/testAccumulatedMessageSizeOverflow/

**Comment by tezc** [comment]
http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-OracleJDK9/43/testReport/com.hazelcast.client.protocol/ClientMessageProtectionTest/testExceededMessageSize/

**Comment by mdumandag** [comment]
fixed by https://github.com/hazelcast/hazelcast/pull/15772
