### ISSUE TITLE
NPE in MultiMapService.getStats()

### ISSUE THREAD

**Issue by blazember** [hazelcast/hazelcast#15656]
Probably `getStats()` called before `partitionContainers` was initialized that shut down MC service. 

```
12:51:54,821  WARN |testWithOneMapTwoSyncs[consistencyCheckStrategy:NONE, maxConcurrentInvocations:-1]| - [ManagementCenterService] hz.ClusterA-194ce8ff-a50d-44ff-a160-fbeb3a8de1580.MC.State.Sender - [127.0.0.1]:5701 [A] [4.0-SNAPSHOT] Hazelcast Management Center Service will be shutdown due to exception.
java.lang.NullPointerException
	at com.hazelcast.multimap.impl.MultiMapService.getStats(MultiMapService.java:459) ~[hazelcast-4.0-SNAPSHOT.jar:4.0-SNAPSHOT]
	at com.hazelcast.internal.management.TimedMemberStateFactory.createMemState(TimedMemberStateFactory.java:251) ~[hazelcast-4.0-SNAPSHOT.jar:4.0-SNAPSHOT]
	at com.hazelcast.internal.management.TimedMemberStateFactory.createMemberState(TimedMemberStateFactory.java:201) ~[hazelcast-4.0-SNAPSHOT.jar:4.0-SNAPSHOT]
	at com.hazelcast.internal.management.TimedMemberStateFactory.createTimedMemberState(TimedMemberStateFactory.java:126) ~[hazelcast-4.0-SNAPSHOT.jar:4.0-SNAPSHOT]
	at com.hazelcast.internal.management.ManagementCenterService$PrepareStateThread.run(ManagementCenterService.java:450) [hazelcast-4.0-SNAPSHOT.jar:4.0-SNAPSHOT]
```

Caught in https://console.aws.amazon.com/s3/object/j-artifacts/Hazelcast-EE-pr-builder/1214 accidentally, in `WanSyncTrackingTest-output.txt`. The NPE occurred multiple times in different test cases.

**Comment by blazember** [comment]
cc @emre-aydin @puzpuzpuz

**Comment by mmedenjak** [comment]
Closing as fixed.
