### ISSUE TITLE
HDEntryProcessorOffloadableTest.testEntryProcessorWithKey_localNotReentrant

### ISSUE THREAD

**Issue by vojtechtoman** [hazelcast/hazelcast#15683]
http://jenkins.hazelcast.com/job/Hazelcast-EE-pr-builder/1288

com.hazelcast.map.HDEntryProcessorOffloadableTest.testEntryProcessorWithKey_localNotReentrant[0: BINARY sync=0 async=0]

```
EntryOperation invocation failed to complete due to operation-heartbeat-timeout. Current time: 2019-10-04 18:13:43.954. Start time: 2019-10-04 18:13:27.514. Total elapsed time: 16462 ms. Last operation heartbeat: never. Last operation heartbeat from member: never. Invocation{op=com.hazelcast.map.impl.operation.EntryOperation{serviceName='hz:impl:mapService', identityHash=1172792139, partitionId=226, replicaIndex=0, callId=-28, invocationTime=1570212807446 (2019-10-04 18:13:27.446), waitTimeout=-1, callTimeout=8000, name=EntryProcessorOffloadableTest}, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=8000, firstInvocationTimeMs=1570212807514, firstInvocationTime='2019-10-04 18:13:27.514', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 00:00:00.000', target=[127.0.0.1]:5701, pendingResponse={VOID}, backupsAcksExpected=-1, backupsAcksReceived=0, connection=MockConnection{localEndpoint=[127.0.0.1]:5702, remoteEndpoint=[127.0.0.1]:5701, alive=true}}

Stacktrace

java.util.concurrent.ExecutionException: EntryOperation invocation failed to complete due to operation-heartbeat-timeout. Current time: 2019-10-04 18:13:43.954. Start time: 2019-10-04 18:13:27.514. Total elapsed time: 16462 ms. Last operation heartbeat: never. Last operation heartbeat from member: never. Invocation{op=com.hazelcast.map.impl.operation.EntryOperation{serviceName='hz:impl:mapService', identityHash=1172792139, partitionId=226, replicaIndex=0, callId=-28, invocationTime=1570212807446 (2019-10-04 18:13:27.446), waitTimeout=-1, callTimeout=8000, name=EntryProcessorOffloadableTest}, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=8000, firstInvocationTimeMs=1570212807514, firstInvocationTime='2019-10-04 18:13:27.514', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 00:00:00.000', target=[127.0.0.1]:5701, pendingResponse={VOID}, backupsAcksExpected=-1, backupsAcksReceived=0, connection=MockConnection{localEndpoint=[127.0.0.1]:5702, remoteEndpoint=[127.0.0.1]:5701, alive=true}}
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.newOperationTimeoutException(InvocationFuture.java:174)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:117)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:90)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:162)
	at com.hazelcast.internal.util.executor.DelegatingFuture.get(DelegatingFuture.java:83)
	at com.hazelcast.map.EntryProcessorOffloadableTest.testEntryProcessorWithKey_localNotReentrant(EntryProcessorOffloadableTest.java:724)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.hazelcast.core.OperationTimeoutException: EntryOperation invocation failed to complete due to operation-heartbeat-timeout. Current time: 2019-10-04 18:13:43.954. Start time: 2019-10-04 18:13:27.514. Total elapsed time: 16462 ms. Last operation heartbeat: never. Last operation heartbeat from member: never. Invocation{op=com.hazelcast.map.impl.operation.EntryOperation{serviceName='hz:impl:mapService', identityHash=1172792139, partitionId=226, replicaIndex=0, callId=-28, invocationTime=1570212807446 (2019-10-04 18:13:27.446), waitTimeout=-1, callTimeout=8000, name=EntryProcessorOffloadableTest}, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=8000, firstInvocationTimeMs=1570212807514, firstInvocationTime='2019-10-04 18:13:27.514', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 00:00:00.000', target=[127.0.0.1]:5701, pendingResponse={VOID}, backupsAcksExpected=-1, backupsAcksReceived=0, connection=MockConnection{localEndpoint=[127.0.0.1]:5702, remoteEndpoint=[127.0.0.1]:5701, alive=true}}
	... 18 more
```

**Comment by petrpleshachkov** [comment]
I analyzed the logs of the failure and I assume the failure happens due to slow environment. 
We have 2 members `cranky_boyd` and `confident_boyd` on ports 5701 and 5702 respectively. 
We see first logs from them at `18:13:26`

`18:13:26,475  INFO |testEntryProcessorWithKey_localNotReentrant[0: BINARY sync=0 async=0]| - [ClusterService] hz.cranky_boyd.generic-operation.thread-1 - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] `

`18:13:26,505  INFO |testEntryProcessorWithKey_localNotReentrant[0: BINARY sync=0 async=0]| - [ClusterService] hz.confident_boyd.priority-generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [4.0-SNAPSHOT] `

Then we have only a few log messages during 16 seconds. 

```
18:13:27,534  INFO |testEntryProcessorWithKey_localNotReentrant_latchTest[0: BINARY sync=0 async=0]| - [TransactionManagerService] hz.cool_boyd.cached.thread-7 - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] Committing/rolling-back live transactions of [127.0.0.1]:5702, UUID: 93fd3718-a7a4-44a7-af24-7c7767ad2f8f
18:13:30,749  INFO |puts_entry_into_empty_map[0: BINARY sync=0 async=0]| - [NodeExtension] Thread-4 - [127.0.0.1]:5702 [dev] [4.0-SNAPSHOT] Destroying node NodeExtension.
18:13:43,890  INFO |testEntryProcessorWithKey_offloadable_withoutSetValue[0: BINARY sync=0 async=0]| - [MigrationManager] hz.competent_boyd.migration - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] Repartitioning cluster data. Migration tasks count: 136
```
At 18:13:44 a normal response comes from cranky_boyd to confident_boyd, but too late, the invocation has been already de-registered due to timeout. 

`18:13:44,307  WARN |testEntryProcessorWithKey_localNotReentrant[0: BINARY sync=0 async=0]| - [InboundResponseHandler] hz.confident_boyd.response-0 - [127.0.0.1]:5702 [dev] [4.0-SNAPSHOT] No Invocation found for normal response with callId=28 sent from [127.0.0.1]:5701`

And we see many hiccups between 18:13:27 and 18:13:44.

```
Hiccups measured while running test 'testEntryProcessorWithKey_localNotReentrant[0: BINARY sync=0 async=0](com.hazelcast.map.HDEntryProcessorOffloadableTest):'
18:13:20, accumulated pauses: 1026 ms, max pause: 139 ms, pauses over 1000 ms: 0
18:13:25, accumulated pauses: 7209 ms, max pause: 6045 ms, pauses over 1000 ms: 1
18:13:30, accumulated pauses: 10180 ms, max pause: 10128 ms, pauses over 1000 ms: 1
18:13:40, accumulated pauses: 93 ms, max pause: 18 ms, pauses over 1000 ms: 0
18:13:45, accumulated pauses: 7792 ms, max pause: 4348 ms, pauses over 1000 ms: 2
```
That is why I suspect slow environment. I am not sure that we have to increase explicitly operation timeouts for the test because we do have to fail if detect real timeout. I tend to close this case. @vojtechtoman, @mmedenjak , WDYT?

**Comment by mmedenjak** [comment]
Yes, true, if you don't have any ideas how to make the test more resilient (smaller instances, longer timeouts, other creative ideas), let's close it.

**Comment by petrpleshachkov** [comment]
The test already uses `smallInstanceConfig()` introduced in https://github.com/hazelcast/hazelcast/pull/16201. I am closing the issue.
