### ISSUE TITLE
EntryProcessorTest.test_executeOnEntriesWithPredicate_runsOnBackup_whenIndexesAvailable[0: BINARY]

### ISSUE THREAD

**Issue by tezc** [hazelcast/hazelcast#15696]
http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-Windows-OracleJDK8/91/testReport/junit/com.hazelcast.map/EntryProcessorTest/test_executeOnEntriesWithPredicate_runsOnBackup_whenIndexesAvailable_0__BINARY_/

**Stacktrace**
```
Stacktrace
java.lang.AssertionError: Expecting two predicate#apply method call one on owner, other one on backup expected:<2> but was:<1>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.map.EntryProcessorTest.test_executeOnEntriesWithPredicate_runsOnBackup_whenIndexesAvailable(EntryProcessorTest.java:1295)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by ahmetmircik** [comment]
same issue with https://github.com/hazelcast/hazelcast/issues/15579
