### ISSUE TITLE
SelectWithSelectorFix_TcpIpConnection_BasicTest.test_equals

### ISSUE THREAD

**Issue by tezc** [hazelcast/hazelcast#15706]
_master_ (commit 4a6825bb471cedfd692ee970412fda34ab66c0d3)

Failed on ZingJDK8 : http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-ZingJDK8/94/testReport/com.hazelcast.internal.networking.nio/SelectWithSelectorFix_TcpIpConnection_BasicTest/test_equals/

**Stacktrace**
```
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertNotNull(Assert.java:712)
	at org.junit.Assert.assertNotNull(Assert.java:722)
	at com.hazelcast.internal.nio.tcp.TcpIpConnection_AbstractTest.lambda$connect$1(TcpIpConnection_AbstractTest.java:156)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1316)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1418)
	at com.hazelcast.internal.nio.tcp.TcpIpConnection_AbstractTest.connect(TcpIpConnection_AbstractTest.java:154)
	at com.hazelcast.internal.nio.tcp.TcpIpConnection_AbstractBasicTest.test_equals(TcpIpConnection_AbstractBasicTest.java:230)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by vbekiaris** [comment]
Unable to reproduce, #15761 adds logging to verify a potential explanation if this fails again in the future.

**Comment by vbekiaris** [comment]
Another failure: http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/3849/testReport/junit/com.hazelcast.internal.networking.nio/SelectWithSelectorFix_TcpIpConnection_BasicTest/test_equals/ 

Findings look the same: the selector is rebuilt early during the test, then 2 minutes without any logging pass (GC pauses are not significant) and test fails.

**Comment by vbekiaris** [comment]
At the beginning of each of the failing tests, there is a statement like the following:
```
TcpIpConnection connAB = connect(networkingServiceA, addressB);
```

`A` initiates a connection to `B`. Once the connection is established, `A` sends `ExtendedBind` / `Bind` message to `B`. At that point `B` registers the connection and replies with an `ExtendedBind` / `Bind` message. When using `SELECT_WITH_FIX` selector mode, there is a race between selector being rebuilt and writing the outbound `ExtendedBind` message which may result in the reply bind message from `B` to `A` not being sent --> `A` never registers the connection in its `TcpIpEndpointManager` --> the assertion at https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/test/java/com/hazelcast/internal/nio/tcp/TcpIpConnection_AbstractTest.java#L156 fails.

This is the code path on `B` that leads to the `ExtendedBind` reply never being sent back to `A`:
* `B` writes the `ExtendedBind` to the `Connection` at https://github.com/hazelcast/hazelcast/blob/d4ec22142061335849718dec7c81c88cde50d68e/hazelcast/src/main/java/com/hazelcast/internal/nio/tcp/BindRequest.java#L66 (this happens on `B`'s input `NioThread` which processes the bind message)
* write-through is not enabled in the test, the code path eventually leads to [`executePipeline()`](https://github.com/hazelcast/hazelcast/blob/007479ac4a816ee6ae63015d5cbe947bf7e3709d/hazelcast/src/main/java/com/hazelcast/internal/networking/nio/NioOutboundPipeline.java#L204)
* the selection key registers interest for `WRITE` ops and wakes up the selector at https://github.com/hazelcast/hazelcast/blob/007479ac4a816ee6ae63015d5cbe947bf7e3709d/hazelcast/src/main/java/com/hazelcast/internal/networking/nio/NioOutboundPipeline.java#L232-L233
* concurrently, on `B`'s output `NioThread`, the test simulates detection of the selector hang issue -> triggers a rebuild of the selector and in the process cancels existing selection keys and closes the old selector -> the bind message is never sent -> `A` never adds the connection to its `EndpointManager`'s connections map.

Reverting the queue skipping code in commit 64a2a9bdaa1a3544bc23c4b32c4fe519b510faf4 resolves the issue.
