### ISSUE TITLE
ListBasicDistributedTest.testClear

### ISSUE THREAD

**Issue by tezc** [hazelcast/hazelcast#15700]
maintenance (commit cb88760c728ef804de527a70421f183df1a6ef14)

Failed on IbmJDK7 : http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.maintenance-IbmJDK7/85/testReport/junit/com.hazelcast.collection.impl.list/ListBasicDistributedTest/testClear/

**Stacktrace**
```
com.hazelcast.core.OperationTimeoutException: CollectionAddOperation got rejected before execution due to not starting within the operation-call-timeout of: 60000 ms. Current time: 2019-10-07 01:16:36.270. Start time: 2019-10-07 01:16:36.269. Total elapsed time: 1 ms. Invocation{op=com.hazelcast.collection.impl.collection.operations.CollectionAddOperation{serviceName='hz:impl:listService', identityHash=1530278952, partitionId=127, replicaIndex=0, callId=-3, invocationTime=1570410865656 (2019-10-07 01:14:25.656), waitTimeout=-1, callTimeout=60000, name=testClearaf94a19f-d363-4099-8d4b-4ac03aa4c72c}, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=60000, firstInvocationTimeMs=1570410996269, firstInvocationTime='2019-10-07 01:16:36.269', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 00:00:00.000', target=[127.0.0.1]:5702, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=MockConnection{localEndpoint=[127.0.0.1]:5701, remoteEndpoint=[127.0.0.1]:5702, alive=true}}
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.newOperationTimeoutException(InvocationFuture.java:163)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:104)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:79)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:163)
	at com.hazelcast.collection.impl.collection.AbstractCollectionProxyImpl.invoke(AbstractCollectionProxyImpl.java:236)
	at com.hazelcast.collection.impl.collection.AbstractCollectionProxyImpl.add(AbstractCollectionProxyImpl.java:111)
	at com.hazelcast.collection.impl.list.ListAbstractTest.addItems(ListAbstractTest.java:543)
	at com.hazelcast.collection.impl.list.ListAbstractTest.testClear(ListAbstractTest.java:223)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:95)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:56)
	at java.lang.reflect.Method.invoke(Method.java:620)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.util.concurrent.FutureTask.run(FutureTask.java:274)
	at java.lang.Thread.run(Thread.java:809)
```

```
Hiccups measured while running test 'testClear(com.hazelcast.collection.impl.list.ListBasicDistributedTest):'
01:13:50, accumulated pauses: 98 ms, max pause: 65 ms, pauses over 1000 ms: 0
01:13:55, accumulated pauses: 207 ms, max pause: 165 ms, pauses over 1000 ms: 0
01:14:00, accumulated pauses: 36 ms, max pause: 2 ms, pauses over 1000 ms: 0
01:14:05, accumulated pauses: 60 ms, max pause: 9 ms, pauses over 1000 ms: 0
01:14:10, accumulated pauses: 36 ms, max pause: 2 ms, pauses over 1000 ms: 0
01:14:15, accumulated pauses: 34 ms, max pause: 2 ms, pauses over 1000 ms: 0
01:14:20, accumulated pauses: 2544 ms, max pause: 2518 ms, pauses over 1000 ms: 1
01:14:25, accumulated pauses: 95 ms, max pause: 5 ms, pauses over 1000 ms: 0
01:14:30, accumulated pauses: 99 ms, max pause: 8 ms, pauses over 1000 ms: 0
01:14:35, accumulated pauses: 172 ms, max pause: 20 ms, pauses over 1000 ms: 0
01:14:40, accumulated pauses: 130 ms, max pause: 6 ms, pauses over 1000 ms: 0
01:14:45, accumulated pauses: 51 ms, max pause: 2 ms, pauses over 1000 ms: 0
01:14:50, accumulated pauses: 101 ms, max pause: 9 ms, pauses over 1000 ms: 0
01:14:55, accumulated pauses: 35 ms, max pause: 2 ms, pauses over 1000 ms: 0
01:15:00, accumulated pauses: 49 ms, max pause: 4 ms, pauses over 1000 ms: 0
01:15:05, accumulated pauses: 45 ms, max pause: 6 ms, pauses over 1000 ms: 0
01:15:10, accumulated pauses: 68 ms, max pause: 10 ms, pauses over 1000 ms: 0
01:15:15, accumulated pauses: 190 ms, max pause: 11 ms, pauses over 1000 ms: 0
01:15:20, accumulated pauses: 377 ms, max pause: 16 ms, pauses over 1000 ms: 0
01:15:25, accumulated pauses: 802 ms, max pause: 36 ms, pauses over 1000 ms: 0
01:15:30, accumulated pauses: 751 ms, max pause: 25 ms, pauses over 1000 ms: 0
01:15:35, accumulated pauses: 577 ms, max pause: 15 ms, pauses over 1000 ms: 0
01:15:40, accumulated pauses: 214 ms, max pause: 11 ms, pauses over 1000 ms: 0
01:15:45, accumulated pauses: 203 ms, max pause: 11 ms, pauses over 1000 ms: 0
01:15:50, accumulated pauses: 94 ms, max pause: 5 ms, pauses over 1000 ms: 0
01:15:55, accumulated pauses: 320 ms, max pause: 11 ms, pauses over 1000 ms: 0
01:16:00, accumulated pauses: 670 ms, max pause: 36 ms, pauses over 1000 ms: 0
01:16:05, accumulated pauses: 940 ms, max pause: 52 ms, pauses over 1000 ms: 0
01:16:10, accumulated pauses: 635 ms, max pause: 27 ms, pauses over 1000 ms: 0
01:16:15, accumulated pauses: 899 ms, max pause: 21 ms, pauses over 1000 ms: 0
01:16:20, accumulated pauses: 393 ms, max pause: 14 ms, pauses over 1000 ms: 0
01:16:25, accumulated pauses: 87 ms, max pause: 6 ms, pauses over 1000 ms: 0
01:16:30, accumulated pauses: 144 ms, max pause: 13 ms, pauses over 1000 ms: 0
01:16:35, accumulated pauses: 705 ms, max pause: 598 ms, pauses over 1000 ms: 0
```

**Comment by petrpleshachkov** [comment]
Based on the output from the log we see that for timed out operation we observ the following timestamps and it looks like the operation was in the queue for a long time (> 1 minute).
```
Current time: 2019-10-07 01:16:36.270
Start time: 2019-10-07 01:16:36.269
invocationTime=1570410865656 (2019-10-07 01:14:25.656)
```
Another observation is that the test took too much time. On my local machine it takes around 4 seconds, but on Jenkins it took 162 seconds. 
```
02:13:54 [INFO] Running com.hazelcast.collection.impl.list.ListBasicDistributedTest
02:16:37 [ERROR] Tests run: 53, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 162.361 s <<< FAILURE! - in com.hazelcast.collection.impl.list.ListBasicDistributedTest
```
This is why we assume that slow environment triggered the timeout. The PR https://github.com/hazelcast/hazelcast/pull/15928 minimizes the resources consumed by this specific test to reduce a chance that we run thousands of threads in parallel on Jenkins.
