### ISSUE TITLE
CPMemberAddRemoveTest.testNodesBecomeAP_whenMoreThanInitialRaftMembers_areStartedConcurrently

### ISSUE THREAD

**Issue by tezc** [hazelcast/hazelcast#15726]
Failed on Sonar : http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-sonar/263/testReport/com.hazelcast.cp.internal/CPMemberAddRemoveTest/testNodesBecomeAP_whenMoreThanInitialRaftMembers_areStartedConcurrently/

**Stacktrace**
```
java.lang.IllegalStateException: Missing CP member in active CP members: [] for CPGroupInfo{id=CPGroupId{name='METADATA', seed=0, commitIndex=0}, initialMembers=[RaftEndpoint{uuid='bd59210f-a99b-42c4-8cea-967f2639941f'}, RaftEndpoint{uuid='f91c63b5-6f8d-4807-b8bb-94218c816940'}, RaftEndpoint{uuid='20a37926-924e-4661-82c8-bdbcad495f3c'}], membersCommitIndex=0, members=[RaftEndpoint{uuid='bd59210f-a99b-42c4-8cea-967f2639941f'}, RaftEndpoint{uuid='f91c63b5-6f8d-4807-b8bb-94218c816940'}, RaftEndpoint{uuid='20a37926-924e-4661-82c8-bdbcad495f3c'}], status=ACTIVE}
	at com.hazelcast.cp.internal.CPGroupInfo.toSummary(CPGroupInfo.java:169)
	at com.hazelcast.cp.internal.MetadataRaftGroupManager.getGroup(MetadataRaftGroupManager.java:344)
	at com.hazelcast.cp.internal.HazelcastRaftTestSupport.getRaftGroupLocally(HazelcastRaftTestSupport.java:220)
	at com.hazelcast.cp.internal.CPMemberAddRemoveTest.lambda$testNodesBecomeAP_whenMoreThanInitialRaftMembers_areStartedConcurrently$13(CPMemberAddRemoveTest.java:558)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1316)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1418)
	at com.hazelcast.cp.internal.CPMemberAddRemoveTest.testNodesBecomeAP_whenMoreThanInitialRaftMembers_areStartedConcurrently(CPMemberAddRemoveTest.java:550)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

```
Hiccups measured while running test 'testNodesBecomeAP_whenMoreThanInitialRaftMembers_areStartedConcurrently(com.hazelcast.cp.internal.CPMemberAddRemoveTest):'
01:27:30, accumulated pauses: 1503 ms, max pause: 1141 ms, pauses over 1000 ms: 1
01:27:35, accumulated pauses: 2376 ms, max pause: 1734 ms, pauses over 1000 ms: 1
01:27:40, accumulated pauses: 1246 ms, max pause: 226 ms, pauses over 1000 ms: 0
01:27:45, accumulated pauses: 1224 ms, max pause: 311 ms, pauses over 1000 ms: 0
01:27:50, accumulated pauses: 859 ms, max pause: 297 ms, pauses over 1000 ms: 0
01:27:55, accumulated pauses: 135 ms, max pause: 30 ms, pauses over 1000 ms: 0
```

**Comment by mdogan** [comment]
Same issue https://github.com/hazelcast/hazelcast/issues/15771

Fixed by https://github.com/hazelcast/hazelcast/pull/15815
