### ISSUE TITLE
com.hazelcast.client.bluegreen.ClientSelectorRaceTest.com.hazelcast.client.bluegreen.ClientSelectorRaceTest [API-1426]

### ISSUE THREAD

**Issue by ahmetmircik** [hazelcast/hazelcast#15739]
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/3746/testReport/junit/com.hazelcast.client.bluegreen/ClientSelectorRaceTest/com_hazelcast_client_bluegreen_ClientSelectorRaceTest/
```
Stacktrace
java.lang.IllegalStateException: Instances haven't been shut down: [HazelcastInstance{name='amazing_booth', node=[127.0.0.1]:5701}]
	at com.hazelcast.test.AbstractHazelcastClassRunner$1.evaluate(AbstractHazelcastClassRunner.java:309)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeLazy(JUnitCoreWrapper.java:119)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:87)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:379)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:340)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:413)
```

**Comment by ihsandemir** [comment]
[com.hazelcast.client.bluegreen.ClientSelectorRaceTest-output.txt](https://github.com/hazelcast/hazelcast/files/3729345/com.hazelcast.client.bluegreen.ClientSelectorRaceTest-output.txt)

The exception occured during test cleanup phase while executing `hazelcastFactory.terminateAll();`
It has `NullPointerException` and I observed it at the `TEST-com.hazelcast.client.bluegreen.ClientSelectorRaceTest.xml` file. The error is:
```
  <testcase name="testConcurrency" classname="com.hazelcast.client.bluegreen.ClientSelectorRaceTest" time="3.224">
    <error type="java.lang.NullPointerException">java.lang.NullPointerException
	at com.hazelcast.client.test.TestHazelcastFactory.terminateAll(TestHazelcastFactory.java:145)
	at com.hazelcast.client.bluegreen.ClientSelectorRaceTest.cleanup(ClientSelectorRaceTest.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:402)
	at com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37)
	at com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:104)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at com.hazelcast.test.HazelcastParallelClassRunner.access$301(HazelcastParallelClassRunner.java:49)
	at com.hazelcast.test.HazelcastParallelClassRunner$TestRunner.run(HazelcastParallelClassRunner.java:162)
	at java.lang.Thread.run(Thread.java:748)
</error>
```
We need to understand how this case can occur.

**Comment by olukas** [comment]
Reopening since it happened again on `master` with CorrettoJDK17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-CorrettoJDK17/32/testReport/com.hazelcast.client.bluegreen/ClientSelectorRaceTest/com_hazelcast_client_bluegreen_ClientSelectorRaceTest/

Stacktrace:
```
java.lang.IllegalStateException: Client instances haven't been shut down: [com.hazelcast.client.impl.clientside.HazelcastClientInstanceImpl@1c437904]
	at com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:52)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:107)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:83)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
```

**Comment by olukas** [comment]
Failed on `master` on CorrettoJDK17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-CorrettoJDK17/42/testReport/com.hazelcast.client.bluegreen/ClientSelectorRaceTest/com_hazelcast_client_bluegreen_ClientSelectorRaceTest/

**Comment by olukas** [comment]
Failed on `master` on OracleJDK17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-OracleJDK17/36/testReport/com.hazelcast.client.bluegreen/ClientSelectorRaceTest/com_hazelcast_client_bluegreen_ClientSelectorRaceTest/

**Comment by olukas** [comment]
Failed on `master` on:
- `ZuluJDK8`: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZuluJDK8/195/testReport/com.hazelcast.client.bluegreen/ClientSelectorRaceTest/com_hazelcast_client_bluegreen_ClientSelectorRaceTest/
- `Openj9-11`: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Openj9-11/86/testReport/com.hazelcast.client.bluegreen/ClientSelectorRaceTest/com_hazelcast_client_bluegreen_ClientSelectorRaceTest/

**Comment by olukas** [comment]
Failed on `master` on Sonar build (Oracle JDK 11): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/1280/testReport/com.hazelcast.client.bluegreen/ClientSelectorRaceTest/com_hazelcast_client_bluegreen_ClientSelectorRaceTest/
