### ISSUE TITLE
SessionManagerServiceTest.sessionHeartbeatsAreSent_whenSessionInUse

### ISSUE THREAD

**Issue by ahmetmircik** [hazelcast/hazelcast#15735]
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/3748/testReport/junit/com.hazelcast.cp.internal.session/SessionManagerServiceTest/sessionHeartbeatsAreSent_whenSessionInUse/

**Comment by mmedenjak** [comment]
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/3808

**Comment by mmedenjak** [comment]
Sorry guys :(
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/4569

There are some large-ish pauses and some exceptions so this might just be a bad run.

```
11:28:15, accumulated pauses: 1426 ms, max pause: 559 ms, pauses over 1000 ms: 0
11:28:20, accumulated pauses: 1184 ms, max pause: 44 ms, pauses over 1000 ms: 0
11:28:25, accumulated pauses: 3472 ms, max pause: 2544 ms, pauses over 1000 ms: 1
11:28:30, accumulated pauses: 1227 ms, max pause: 29 ms, pauses over 1000 ms: 0
11:28:35, accumulated pauses: 3430 ms, max pause: 727 ms, pauses over 1000 ms: 0
11:28:40, accumulated pauses: 1033 ms, max pause: 344 ms, pauses over 1000 ms: 0
11:28:45, accumulated pauses: 972 ms, max pause: 326 ms, pauses over 1000 ms: 0
11:28:50, accumulated pauses: 391 ms, max pause: 283 ms, pauses over 1000 ms: 0
```
```
11:28:51,959  INFO |sessionHeartbeatsAreSent_whenSessionInUse| - [TransactionManagerService] hz.hopeful_agnesi.cached.thread-80 - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] Committing/rolling-back live transactions of [127.0.0.1]:5702, UUID: 1dbc8ef5-7a84-44f4-ad14-c5bfa8bbd0fa
11:28:51,960  WARN |sessionHeartbeatsAreSent_whenSessionInUse| - [RaftService] hz.hopeful_agnesi.cached.thread-80 - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] CPMember{uuid=1dbc8ef5-7a84-44f4-ad14-c5bfa8bbd0fa, address=[127.0.0.1]:5702} is not present in the cluster. It will be auto-removed after 14400 seconds.
...
11:28:51,988  WARN |sessionHeartbeatsAreSent_whenSessionInUse| - [PartitionEventManager$InternalPartitionLostEventPublisher] hz.festive_agnesi.cached.thread-47 - [127.0.0.1]:5702 [dev] [4.0-SNAPSHOT] Handling partitionLostEvent failed. Service: class com.hazelcast.internal.partition.impl.InternalPartitionServiceImpl Event: com.hazelcast.internal.partition.PartitionLostEventImpl{partitionId=255, lostBackupCount=0, eventSource=[127.0.0.1]:5702}
com.hazelcast.spi.exception.RetryableHazelcastException: HazelcastInstance[[127.0.0.1]:5702] is not active!
	at com.hazelcast.spi.impl.NodeEngineImpl.getService(NodeEngineImpl.java:387) ~[classes/:?]
	at com.hazelcast.spi.impl.eventservice.impl.EventServiceImpl.getSegment(EventServiceImpl.java:594) ~[classes/:?]
	at com.hazelcast.spi.impl.eventservice.impl.EventServiceImpl.sendEvent(EventServiceImpl.java:553) ~[classes/:?]
	at com.hazelcast.spi.impl.eventservice.impl.EventServiceImpl.publishEvent(EventServiceImpl.java:477) ~[classes/:?]
	at com.hazelcast.internal.partition.impl.PartitionEventManager.onPartitionLost(PartitionEventManager.java:177) ~[classes/:?]
	at com.hazelcast.internal.partition.impl.InternalPartitionServiceImpl.onPartitionLost(InternalPartitionServiceImpl.java:1098) ~[classes/:?]
	at com.hazelcast.internal.partition.impl.PartitionEventManager$InternalPartitionLostEventPublisher.run(PartitionEventManager.java:204) [classes/:?]
	at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217) [classes/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64) [classes/:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80) [classes/:?]
11:28:51,987  WARN |sessionHeartbeatsAreSent_whenSessionInUse| - [PartitionEventManager$InternalPartitionLostEventPublisher] hz.festive_agnesi.cached.thread-46 - [127.0.0.1]:5702 [dev] [4.0-SNAPSHOT] Handling partitionLostEvent failed. Service: class com.hazelcast.internal.partition.impl.InternalPartitionServiceImpl Event: com.hazelcast.internal.partition.PartitionLostEventImpl{partitionId=251, lostBackupCount=0, eventSource=[127.0.0.1]:5702}
com.hazelcast.spi.exception.RetryableHazelcastException: HazelcastInstance[[127.0.0.1]:5702] is not active!
	at com.hazelcast.spi.impl.NodeEngineImpl.getService(NodeEngineImpl.java:387) ~[classes/:?]
	at com.hazelcast.spi.impl.eventservice.impl.EventServiceImpl.getSegment(EventServiceImpl.java:594) ~[classes/:?]
	at com.hazelcast.spi.impl.eventservice.impl.EventServiceImpl.sendEvent(EventServiceImpl.java:553) ~[classes/:?]
	at com.hazelcast.spi.impl.eventservice.impl.EventServiceImpl.publishEvent(EventServiceImpl.java:477) ~[classes/:?]
	at com.hazelcast.internal.partition.impl.PartitionEventManager.onPartitionLost(PartitionEventManager.java:177) ~[classes/:?]
	at com.hazelcast.internal.partition.impl.InternalPartitionServiceImpl.onPartitionLost(InternalPartitionServiceImpl.java:1098) ~[classes/:?]
	at com.hazelcast.internal.partition.impl.PartitionEventManager$InternalPartitionLostEventPublisher.run(PartitionEventManager.java:204) [classes/:?]
	at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217) [classes/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64) [classes/:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80) [classes/:?]
...

11:28:52,047  WARN |sessionHeartbeatsAreSent_whenSessionInUse| - [Invocation] hz.hopeful_agnesi.priority-generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] Future.complete(Object) on completed future. Request: Invocation{op=com.hazelcast.internal.partition.operation.PromotionCommitOperation{serviceName='hz:core:partitionService', identityHash=2141742271, partitionId=-1, replicaIndex=0, callId=-62, invocationTime=1574335732015 (2019-11-21 11:28:52.015), waitTimeout=-1, callTimeout=60000}, tryCount=2147483647, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=60000, firstInvocationTimeMs=1574335732015, firstInvocationTime='2019-11-21 11:28:52.015', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 00:00:00.000', target=[127.0.0.1]:5701, pendingResponse={VOID}, backupsAcksExpected=-1, backupsAcksReceived=0, connection=null}, current value: ExceptionalResult{cause=com.hazelcast.core.HazelcastInstanceNotActiveException: Hazelcast instance is not active!}, offered value: true
java.lang.Exception
	at com.hazelcast.spi.impl.AbstractInvocationFuture.warnIfSuspiciousDoubleCompletion(AbstractInvocationFuture.java:1225) [classes/:?]
	at com.hazelcast.spi.impl.AbstractInvocationFuture.complete0(AbstractInvocationFuture.java:1206) [classes/:?]
	at com.hazelcast.spi.impl.AbstractInvocationFuture.complete(AbstractInvocationFuture.java:1195) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.complete(Invocation.java:646) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.sendResponse(Invocation.java:231) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.Operation.sendResponse(Operation.java:470) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.handleResponse(OperationRunnerImpl.java:254) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:222) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:207) [classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:148) [classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:126) [classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:111) [classes/:?]
```

**Comment by sancar** [comment]
A new failure:
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/5509/testReport/junit/com.hazelcast.client.cp.internal.session/ClientSessionManagerTest/sessionHeartbeatsAreSent_whenSessionInUse/

```
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.cp.internal.session.AbstractProxySessionManagerTest.sessionHeartbeatsAreSent_whenSessionInUse(AbstractProxySessionManagerTest.java:147)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Standard Output
```
