### ISSUE TITLE
DurableExecutorServiceTest.testDestroyCleansAllContainers

### ISSUE THREAD

**Issue by ahmetmircik** [hazelcast/hazelcast#15736]
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/3748/testReport/junit/com.hazelcast.durableexecutor/DurableExecutorServiceTest/testDestroyCleansAllContainers/

**Comment by blazember** [comment]
Another occurrence: http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/4468/testReport/junit/com.hazelcast.durableexecutor/DurableExecutorServiceTest/testDestroyCleansAllContainers/

**Comment by mdogan** [comment]
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/4935/testReport/junit/com.hazelcast.durableexecutor/DurableExecutorServiceTest/testDestroyCleansAllContainers/

```
java.lang.AssertionError: 
Some partitions has non-null containers for executor 30a426cb-0f50-44b3-9282-c63759534c5e:
Partition 99

	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.durableexecutor.DurableExecutorServiceTest$1.run(DurableExecutorServiceTest.java:136)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1345)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1362)
	at com.hazelcast.durableexecutor.DurableExecutorServiceTest.testDestroyCleansAllContainers(DurableExecutorServiceTest.java:122)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

```
Hiccups measured while running test 'testDestroyCleansAllContainers(com.hazelcast.durableexecutor.DurableExecutorServiceTest):'
07:15:05, accumulated pauses: 681 ms, max pause: 163 ms, pauses over 1000 ms: 0
07:15:10, accumulated pauses: 438 ms, max pause: 11 ms, pauses over 1000 ms: 0
07:15:15, accumulated pauses: 386 ms, max pause: 9 ms, pauses over 1000 ms: 0
07:15:20, accumulated pauses: 267 ms, max pause: 9 ms, pauses over 1000 ms: 0
07:15:25, accumulated pauses: 237 ms, max pause: 8 ms, pauses over 1000 ms: 0
07:15:30, accumulated pauses: 356 ms, max pause: 8 ms, pauses over 1000 ms: 0
07:15:35, accumulated pauses: 300 ms, max pause: 9 ms, pauses over 1000 ms: 0
07:15:40, accumulated pauses: 374 ms, max pause: 318 ms, pauses over 1000 ms: 0
```

**Comment by vbekiaris** [comment]
`DurableExecutorPartitionContainer#executorContainerMap` is a plain `HashMap` (probably assuming access only from single partition thread). However proxy destruction can be executed on calling or generic operation thread, so when a `DurableExecutorServiceProxy` is being destroyed, `DistributedDurableExecutorService#removeAllContainers` will invoke `remove` on the `HashMap`. It seems proxy destruction needs to fan-out separate partition operations to perform the removal or `executorContainerMap` has to become a `ConcurrentMap` for proper usage from multiple threads.

**Comment by blazember** [comment]
New occurrence: http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/5612/testReport/junit/com.hazelcast.durableexecutor/DurableExecutorServiceTest/testDestroyCleansAllContainers/

**Error Message**
```
Some partitions have non-null containers for executor e6e5e865-0e62-4084-81ef-854f34f9c211:
Partition 4 owned by [127.0.0.1]:5703
```
**Stacktrace**
```
java.lang.AssertionError: 
Some partitions have non-null containers for executor e6e5e865-0e62-4084-81ef-854f34f9c211:
Partition 4 owned by [127.0.0.1]:5703

	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.durableexecutor.DurableExecutorServiceTest.lambda$testDestroyCleansAllContainers$0(DurableExecutorServiceTest.java:137)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1356)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1373)
	at com.hazelcast.durableexecutor.DurableExecutorServiceTest.testDestroyCleansAllContainers(DurableExecutorServiceTest.java:121)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```
**Hiccups measured while running test**
```
14:14:35, accumulated pauses: 1859 ms, max pause: 342 ms, pauses over 1000 ms: 0
14:14:40, accumulated pauses: 212 ms, max pause: 14 ms, pauses over 1000 ms: 0
14:14:45, accumulated pauses: 243 ms, max pause: 12 ms, pauses over 1000 ms: 0
14:14:50, accumulated pauses: 231 ms, max pause: 10 ms, pauses over 1000 ms: 0
14:14:55, accumulated pauses: 228 ms, max pause: 9 ms, pauses over 1000 ms: 0
14:15:00, accumulated pauses: 277 ms, max pause: 11 ms, pauses over 1000 ms: 0
14:15:05, accumulated pauses: 303 ms, max pause: 20 ms, pauses over 1000 ms: 0
14:15:10, accumulated pauses: 225 ms, max pause: 18 ms, pauses over 1000 ms: 0
14:15:15, accumulated pauses: 407 ms, max pause: 340 ms, pauses over 1000 ms: 0
```
