### ISSUE TITLE
CPMemberAddRemoveTest.when_newCPMemberIsAddedToTheMetadataGroupAfterRestartAndSnapshot_newMemberInstallsSnapshot

### ISSUE THREAD

**Issue by mmedenjak** [hazelcast/hazelcast#15771]
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/3808

```
java.lang.IllegalStateException: Missing CP member in active CP members: [CPMember{uuid=cd80dc0e-ea1a-466f-8bf5-620212d08bb0, address=[127.0.0.1]:5704}, CPMember{uuid=f4c54513-6aaf-41c2-9173-0140f54b7f5e, address=[127.0.0.1]:5705}, CPMember{uuid=539027f8-1688-4270-bdd3-3c5f4e552e0e, address=[127.0.0.1]:5701}] for CPGroupInfo{id=CPGroupId{name='METADATA', seed=1571122220030, commitIndex=0}, initialMembers=[RaftEndpoint{uuid='cd80dc0e-ea1a-466f-8bf5-620212d08bb0'}, RaftEndpoint{uuid='f4c54513-6aaf-41c2-9173-0140f54b7f5e'}, RaftEndpoint{uuid='539027f8-1688-4270-bdd3-3c5f4e552e0e'}], membersCommitIndex=65, members=[RaftEndpoint{uuid='cd80dc0e-ea1a-466f-8bf5-620212d08bb0'}, RaftEndpoint{uuid='f4c54513-6aaf-41c2-9173-0140f54b7f5e'}, RaftEndpoint{uuid='7665b5e7-f5e3-4bc7-87a8-2e626ee6c5c9'}], status=ACTIVE}
	at com.hazelcast.cp.internal.CPGroupInfo.toSummary(CPGroupInfo.java:169)
	at com.hazelcast.cp.internal.MetadataRaftGroupManager.getGroup(MetadataRaftGroupManager.java:344)
	at com.hazelcast.cp.internal.HazelcastRaftTestSupport.getRaftGroupLocally(HazelcastRaftTestSupport.java:220)
	at com.hazelcast.cp.internal.CPMemberAddRemoveTest.lambda$when_newCPMemberIsAddedToTheMetadataGroupAfterRestartAndSnapshot_newMemberInstallsSnapshot$19(CPMemberAddRemoveTest.java:815)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1316)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1418)
	at com.hazelcast.cp.internal.CPMemberAddRemoveTest.when_newCPMemberIsAddedToTheMetadataGroupAfterRestartAndSnapshot_newMemberInstallsSnapshot(CPMemberAddRemoveTest.java:811)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by mdogan** [comment]
```
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Cannot rebalance CP groups because there is ongoing MembershipChangeSchedule{membershipChangeCommitIndices=[58], member=CPMember{uuid=e270e361-6789-4c12-8e25-ec0f8752ff12, address=[127.0.0.1]:5701}, membershipChangeMode=REMOVE, changes=[CPGroupMembershipChange{groupId=CPGroupId{name='group1', seed=1572504503473, commitIndex=56}, membersCommitIndex=0, members=[RaftEndpoint{uuid='cf2f46d7-531f-4db0-abf2-542bdd36cae3'}, RaftEndpoint{uuid='7a8c77a0-e3dc-4828-a931-7aacea5d04cf'}, RaftEndpoint{uuid='e270e361-6789-4c12-8e25-ec0f8752ff12'}], memberToAdd=null, memberToRemove=RaftEndpoint{uuid='e270e361-6789-4c12-8e25-ec0f8752ff12'}}, CPGroupMembershipChange{groupId=CPGroupId{name='METADATA', seed=1572504503473, commitIndex=0}, membersCommitIndex=0, members=[RaftEndpoint{uuid='cf2f46d7-531f-4db0-abf2-542bdd36cae3'}, RaftEndpoint{uuid='e270e361-6789-4c12-8e25-ec0f8752ff12'}, RaftEndpoint{uuid='7a8c77a0-e3dc-4828-a931-7aacea5d04cf'}], memberToAdd=null, memberToRemove=RaftEndpoint{uuid='e270e361-6789-4c12-8e25-ec0f8752ff12'}}, CPGroupMembershipChange{groupId=CPGroupId{name='group2', seed=1572504503473, commitIndex=57}, membersCommitIndex=0, members=[RaftEndpoint{uuid='e270e361-6789-4c12-8e25-ec0f8752ff12'}, RaftEndpoint{uuid='7a8c77a0-e3dc-4828-a931-7aacea5d04cf'}, RaftEndpoint{uuid='cf2f46d7-531f-4db0-abf2-542bdd36cae3'}], memberToAdd=null, memberToRemove=RaftEndpoint{uuid='e270e361-6789-4c12-8e25-ec0f8752ff12'}}]}
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
	at com.hazelcast.spi.impl.DeserializingCompletableFuture.get(DeserializingCompletableFuture.java:96)
	at com.hazelcast.cp.internal.CPMemberAddRemoveTest.when_newCPMemberIsAddedToTheMetadataGroupAfterRestartAndSnapshot_newMemberInstallsSnapshot(CPMemberAddRemoveTest.java:877)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Cannot rebalance CP groups because there is ongoing MembershipChangeSchedule{membershipChangeCommitIndices=[58], member=CPMember{uuid=e270e361-6789-4c12-8e25-ec0f8752ff12, address=[127.0.0.1]:5701}, membershipChangeMode=REMOVE, changes=[CPGroupMembershipChange{groupId=CPGroupId{name='group1', seed=1572504503473, commitIndex=56}, membersCommitIndex=0, members=[RaftEndpoint{uuid='cf2f46d7-531f-4db0-abf2-542bdd36cae3'}, RaftEndpoint{uuid='7a8c77a0-e3dc-4828-a931-7aacea5d04cf'}, RaftEndpoint{uuid='e270e361-6789-4c12-8e25-ec0f8752ff12'}], memberToAdd=null, memberToRemove=RaftEndpoint{uuid='e270e361-6789-4c12-8e25-ec0f8752ff12'}}, CPGroupMembershipChange{groupId=CPGroupId{name='METADATA', seed=1572504503473, commitIndex=0}, membersCommitIndex=0, members=[RaftEndpoint{uuid='cf2f46d7-531f-4db0-abf2-542bdd36cae3'}, RaftEndpoint{uuid='e270e361-6789-4c12-8e25-ec0f8752ff12'}, RaftEndpoint{uuid='7a8c77a0-e3dc-4828-a931-7aacea5d04cf'}], memberToAdd=null, memberToRemove=RaftEndpoint{uuid='e270e361-6789-4c12-8e25-ec0f8752ff12'}}, CPGroupMembershipChange{groupId=CPGroupId{name='group2', seed=1572504503473, commitIndex=57}, membersCommitIndex=0, members=[RaftEndpoint{uuid='e270e361-6789-4c12-8e25-ec0f8752ff12'}, RaftEndpoint{uuid='7a8c77a0-e3dc-4828-a931-7aacea5d04cf'}, RaftEndpoint{uuid='cf2f46d7-531f-4db0-abf2-542bdd36cae3'}], memberToAdd=null, memberToRemove=RaftEndpoint{uuid='e270e361-6789-4c12-8e25-ec0f8752ff12'}}]}
	at com.hazelcast.internal.util.Preconditions.checkState(Preconditions.java:355)
	at com.hazelcast.cp.internal.MetadataRaftGroupManager.addMember(MetadataRaftGroupManager.java:1010)
	at com.hazelcast.cp.internal.raftop.metadata.AddCPMemberOp.run(AddCPMemberOp.java:50)
	at com.hazelcast.cp.internal.raftop.metadata.MetadataRaftGroupOp.run(MetadataRaftGroupOp.java:38)
	at com.hazelcast.cp.internal.NodeEngineRaftIntegration.runOperation(NodeEngineRaftIntegration.java:210)
	at com.hazelcast.cp.internal.raft.impl.RaftNodeImpl.applyLogEntry(RaftNodeImpl.java:828)
	at com.hazelcast.cp.internal.raft.impl.RaftNodeImpl.applyLogEntries(RaftNodeImpl.java:769)
	at com.hazelcast.cp.internal.raft.impl.RaftNodeImpl.commitEntries(RaftNodeImpl.java:1278)
	at com.hazelcast.cp.internal.raft.impl.RaftNodeImpl.tryAdvanceCommitIndex(RaftNodeImpl.java:1262)
	at com.hazelcast.cp.internal.raft.impl.handler.AppendSuccessResponseHandlerTask.handleResponse(AppendSuccessResponseHandlerTask.java:71)
	at com.hazelcast.cp.internal.raft.impl.handler.AbstractResponseHandlerTask.innerRun(AbstractResponseHandlerTask.java:43)
	at com.hazelcast.cp.internal.raft.impl.task.RaftNodeStatusAwareTask.run(RaftNodeStatusAwareTask.java:52)
	at com.hazelcast.cp.internal.NodeEngineRaftIntegration.execute(NodeEngineRaftIntegration.java:113)
	at com.hazelcast.cp.internal.raft.impl.RaftNodeImpl.execute(RaftNodeImpl.java:862)
	at com.hazelcast.cp.internal.raft.impl.RaftNodeImpl.handleAppendResponse(RaftNodeImpl.java:393)
	at com.hazelcast.cp.internal.RaftService.handleAppendResponse(RaftService.java:645)
	at com.hazelcast.cp.internal.operation.integration.AppendSuccessResponseOp.run(AppendSuccessResponseOp.java:48)
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:184)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:216)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:205)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:429)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:154)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:124)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:111)
```

http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/4066/testReport/junit/com.hazelcast.cp.internal/CPMemberAddRemoveTest/when_newCPMemberIsAddedToTheMetadataGroupAfterRestartAndSnapshot_newMemberInstallsSnapshot/

**Comment by tezc** [comment]
http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.maintenance-sonar/332/testReport/com.hazelcast.cp.internal/CPMemberAddRemoveTest/when_newCPMemberIsAddedToTheMetadataGroupAfterSnapshot_newMemberInstallsSnapshot/

**Stacktrace**
```
java.lang.AssertionError: expected:<[CPMember{uuid=e4f81b39-ff75-40f0-ac1f-e0c21b520164, address=[127.0.0.1]:5702}, CPMember{uuid=e6dc1432-9832-43b4-a102-4487262518be, address=[127.0.0.1]:5703}, CPMember{uuid=a7b14107-76cf-4c53-b1e5-5dd05faed50d, address=[127.0.0.1]:5704}]> but was:<[CPMember{uuid=07a25ea1-a39e-4270-be28-cd5fbb6451c9, address=[127.0.0.1]:5701}, CPMember{uuid=e4f81b39-ff75-40f0-ac1f-e0c21b520164, address=[127.0.0.1]:5702}, CPMember{uuid=e6dc1432-9832-43b4-a102-4487262518be, address=[127.0.0.1]:5703}]>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.cp.internal.CPMemberAddRemoveTest$17.run(CPMemberAddRemoveTest.java:731)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1310)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1412)
	at com.hazelcast.cp.internal.CPMemberAddRemoveTest.when_newCPMemberIsAddedToTheMetadataGroupAfterSnapshot_newMemberInstallsSnapshot(CPMemberAddRemoveTest.java:714)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by kwart** [comment]
Another failure - PR builder run for `maintenance-3.x` branch:
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/5391/

**Comment by lazerion** [comment]
Also fails on [Hazelcast-3.maintenance-IbmJDK8](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.maintenance-IbmJDK8/lastCompletedBuild/testReport/com.hazelcast.cp.internal/CPMemberAddRemoveTest/when_newCPMemberIsAddedToTheMetadataGroupAfterSnapshot_newMemberInstallsSnapshot/). FYI

**Comment by cangencer** [comment]
new failure: 

http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/5603/testReport/junit/com.hazelcast.cp.internal/CPMemberAddRemoveTest/when_newCPMemberIsAddedToTheMetadataGroupAfterRestartAndSnapshot_newMemberInstallsSnapshot/

**Comment by lazerion** [comment]
- Fails on [Build #116 (Jan 20, 2020 5:21:15 AM)](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.maintenance-IbmJDK7/116/testReport/junit/com.hazelcast.cp.internal/CPMemberAddRemoveTest/when_newCPMemberIsAddedToTheMetadataGroupAfterSnapshot_newMemberInstallsSnapshot/)

- Stacktrace
```
java.lang.AssertionError: expected:<[CPMember{uuid=b80660b2-20d9-4503-96e1-a3d96f06851e, address=[127.0.0.1]:5702}, CPMember{uuid=c221ed3a-3b88-4bf3-b007-50b50c437ee3, address=[127.0.0.1]:5703}, CPMember{uuid=698301a5-d6a8-423a-ac74-ea24e5f55bfe, address=[127.0.0.1]:5704}]> but was:<[CPMember{uuid=4086e6bd-014e-4181-a868-460c007aeaa3, address=[127.0.0.1]:5701}, CPMember{uuid=b80660b2-20d9-4503-96e1-a3d96f06851e, address=[127.0.0.1]:5702}, CPMember{uuid=c221ed3a-3b88-4bf3-b007-50b50c437ee3, address=[127.0.0.1]:5703}]>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.cp.internal.CPMemberAddRemoveTest$17.run(CPMemberAddRemoveTest.java:731)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1310)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1412)
	at com.hazelcast.cp.internal.CPMemberAddRemoveTest.when_newCPMemberIsAddedToTheMetadataGroupAfterSnapshot_newMemberInstallsSnapshot(CPMemberAddRemoveTest.java:714)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:95)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:56)
	at java.lang.reflect.Method.invoke(Method.java:620)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.util.concurrent.FutureTask.run(FutureT
```

**Comment by metanet** [comment]
closed by https://github.com/hazelcast/hazelcast/pull/16345
