### ISSUE TITLE
Partition assigment/rebalance issue prevents test cases to finish

### ISSUE THREAD

**Issue by tezc** [hazelcast/hazelcast#15833]
I've seen hanging test cases for hours, I couldn't get logs before but managed to get this time : 

http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-sonar/276/consoleFull

Log file : https://console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-3.x-sonar/276/

MapPredicateJsonTest log shows logs for half an hour than no more logs in the file but this test case hangs for hours. Heap usage is also quite high %90+ time to time. 
Looks like related with partitioning/membership, most exceptions are related with that.

```
04:57:42 [INFO] Running com.hazelcast.json.MapPredicateJsonTest
08:36:34 Build timed out (after 480 minutes). Marking the build as failed.
```

Stacktraces are like : 

```
java.util.concurrent.ExecutionException: com.hazelcast.core.OperationTimeoutException: PromotionCommitOperation got rejected before execution due to not starting within the operation-call-timeout of: 60000 ms. Current time: 2019-10-22 02:19:50.125. Start time: 2019-10-22 02:19:50.125. Total elapsed time: 0 ms. Invocation{op=com.hazelcast.internal.partition.operation.PromotionCommitOperation{serviceName='hz:core:partitionService', identityHash=200445985, partitionId=-1, replicaIndex=0, callId=-158, invocationTime=1571710209986 (2019-10-22 02:10:09.986), waitTimeout=-1, callTimeout=60000}, tryCount=2147483647, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=60000, firstInvocationTimeMs=1571710790125, firstInvocationTime='2019-10-22 02:19:50.125', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 00:00:00.000', target=[127.0.0.1]:5702, pendingResponse={VOID}, backupsAcksExpected=-1, backupsAcksReceived=0, connection=MockConnection{localEndpoint=[127.0.0.1]:5701, remoteEndpoint=[127.0.0.1]:5702, alive=true}}
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.returnOrThrowWithGetConventions(InvocationFuture.java:114) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:98) ~[classes/:?]
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:619) ~[classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1417) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionsToDestination(MigrationManager.java:1427) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.commitPromotionMigrations(MigrationManager.java:1301) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.promoteBackupsForMissingOwners(MigrationManager.java:1287) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationManager$RepairPartitionTableTask.run(MigrationManager.java:1231) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationThread.processTask(MigrationThread.java:122) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationThread.doRun(MigrationThread.java:98) [classes/:?]
	at com.hazelcast.internal.partition.impl.MigrationThread.run(MigrationThread.java:67) [classes/:?]
Caused by: com.hazelcast.core.OperationTimeoutException: PromotionCommitOperation got rejected before execution due to not starting within the operation-call-timeout of: 60000 ms. Current time: 2019-10-22 02:19:50.125. Start time: 2019-10-22 02:19:50.125. Total elapsed time: 0 ms.
```

Standard output : 

```
02:20:09,797  WARN |testArrayInNestedQuery_whenOneArrayIsShort_shouldNotThrow[inMemoryFormat: OBJECT, metadataPolicy: OFF]| - [PartitionStateManager] hz.sharp_chaplygin.partition-operation.thread-55 - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] Partitions can't be assigned since startup is not completed yet.
02:20:09,797  WARN |testArrayInNestedQuery_whenOneArrayIsShort_shouldNotThrow[inMemoryFormat: OBJECT, metadataPolicy: OFF]| - [PartitionStateManager] hz.sharp_chaplygin.partition-operation.thread-55 - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] Partitions can't be assigned since startup is not completed yet.
02:20:09,797  WARN |testArrayInNestedQuery_whenOneArrayIsShort_shouldNotThrow[inMemoryFormat: OBJECT, metadataPolicy: OFF]| - [PartitionStateManager] hz.sharp_chaplygin.partition-operation.thread-55 - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] Partitions can't be assigned since startup is not completed yet.
02:20:09,797  WARN |testArrayInNestedQuery_whenOneArrayIsShort_shouldNotThrow[inMemoryFormat: OBJECT, metadataPolicy: OFF]| - [PartitionStateManager] hz.sharp_chaplygin.partition-operation.thread-55 - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] Partitions can't be assigned since startup is not completed yet.
02:20:09,797  WARN |testArrayInNestedQuery_whenOneArrayIsShort_shouldNotThrow[inMemoryFormat: OBJECT, metadataPolicy: OFF]| - [PartitionStateManager] hz.sharp_chaplygin.partition-operation.thread-55 - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] Partitions can't be assigned since startup is not completed yet.
02:20:09,797  WARN |testArrayInNestedQuery_whenOneArrayIsShort_shouldNotThrow[inMemoryFormat: OBJECT, metadataPolicy: OFF]| - [PartitionStateManager] hz.sharp_chaplygin.partition-operation.thread-55 - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] Partitions can't be assigned since startup is not completed yet.
02:20:09,797  WARN |testArrayInNestedQuery_whenOneArrayIsShort_shouldNotThrow[inMemoryFormat: OBJECT, metadataPolicy: OFF]| - [PartitionStateManager] hz.sharp_chaplygin.partition-operation.thread-55 - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] Partitions can't be assigned since startup is not completed yet.
02:20:09,797  WARN |testArrayInNestedQuery_whenOneArrayIsShort_shouldNotThrow[inMemoryFormat: OBJECT, metadataPolicy: OFF]| - [PartitionStateManager] hz.sharp_chaplygin.partition-operation.thread-55 - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] Partitions can't be assigned since startup is not completed yet.
02:20:09,797  WARN |testArrayInNestedQuery_whenOneArrayIsShort_shouldNotThrow[inMemoryFormat: OBJECT, metadataPolicy: OFF]| - [PartitionStateManager] hz.sharp_chaplygin.partition-operation.thread-55 - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] Partitions can't be assigned since startup is not completed yet.
02:20:09,797  WARN |testArrayInNestedQuery_whenOneArrayIsShort_shouldNotThrow[inMemoryFormat: OBJECT, metadataPolicy: OFF]| - [PartitionStateManager] hz.sharp_chaplygin.partition-operation.thread-55 - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] Partitions can't be assigned since startup is not completed yet.
02:20:09,797  WARN |testArrayInNestedQuery_whenOneArrayIsShort_shouldNotThrow[inMemoryFormat: OBJECT, metadataPolicy: OFF]| - [PartitionStateManager] hz.sharp_chaplygin.partition-operation.thread-55 - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] Partitions can't be assigned since startup is not completed yet.
02:20:09,797  WARN |testArrayInNestedQuery_whenOneArrayIsShort_shouldNotThrow[inMemoryFormat: OBJECT, metadataPolicy: OFF]| - [PartitionStateManager] hz.sharp_chaplygin.partition-operation.thread-55 - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] Partitions can't be assigned since startup is not completed yet.
02:20:09,797  WARN |testArrayInNestedQuery_whenOneArrayIsShort_shouldNotThrow[inMemoryFormat: OBJECT, metadataPolicy: OFF]| - [PartitionStateManager] hz.sharp_chaplygin.partition-operation.thread-55 - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] Partitions can't be assigned since startup is not completed yet.
02:20:09,797  WARN |testArrayInNestedQuery_whenOneArrayIsShort_shouldNotThrow[inMemoryFormat: OBJECT, metadataPolicy: OFF]| - [PartitionStateManager] hz.sharp_chaplygin.partition-operation.thread-55 - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] Partitions can't be assigned since startup is not completed yet.
```

**Comment by mdogan** [comment]
Rebalance does not complete because invocations fail with `OperationTimeoutException`s, because there are constant huge pauses in the system.

See following logging pauses:
```
02:07:17,604  WARN  - [InvocationMonitor] hz.sharp_chaplygin.InvocationMonitorThread - Logging took 145015 ms.
02:07:17,605  WARN  - [ClusterHeartbeatManager] hz.pensive_colden.generic-operation.thread-26 - Logging took 145016 ms.
02:07:17,605  WARN  - [ClusterHeartbeatManager] hz.pensive_colden.generic-operation.thread-11 - Logging took 145016 ms.
02:07:17,608  WARN  - [ClusterHeartbeatManager] hz.pensive_colden.cached.thread-34 - Logging took 143975 ms.
02:07:17,608  WARN  - [ClusterHeartbeatManager] hz.pensive_colden.generic-operation.thread-35 - Logging took 142800 ms.
02:07:17,608  WARN  - [ClusterHeartbeatManager] hz.pensive_colden.generic-operation.thread-10 - Logging took 142800 ms.
02:07:17,623  WARN  - [ClusterHeartbeatManager] hz.pensive_colden.generic-operation.thread-17 - Logging took 186249 ms.
02:07:17,623  WARN  - [InvocationMonitor] hz.pensive_colden.InvocationMonitorThread - Logging took 184823 ms.
02:07:17,624  WARN  - [ClusterHeartbeatManager] hz.pensive_colden.generic-operation.thread-16 - Logging took 182013 ms.
02:07:17,626  WARN  - [ClusterService] Thread-24218 - Logging took 178247 ms.
```

And some hiccups recorded during the test (these are just the ones over 10s):
```
02:05:20, accumulated pauses: 15173 ms, max pause: 11844 ms, pauses over 1000 ms: 2
02:05:50, accumulated pauses: 14427 ms, max pause: 9315 ms, pauses over 1000 ms: 5
02:06:10, accumulated pauses: 18610 ms, max pause: 18610 ms, pauses over 1000 ms: 1
02:06:25, accumulated pauses: 12960 ms, max pause: 12960 ms, pauses over 1000 ms: 1
02:06:35, accumulated pauses: 12134 ms, max pause: 9561 ms, pauses over 1000 ms: 2
02:07:00, accumulated pauses: 13154 ms, max pause: 13154 ms, pauses over 1000 ms: 1
02:07:15, accumulated pauses: 17605 ms, max pause: 12825 ms, pauses over 1000 ms: 4
02:07:30, accumulated pauses: 13879 ms, max pause: 8098 ms, pauses over 1000 ms: 3
02:07:45, accumulated pauses: 11559 ms, max pause: 5957 ms, pauses over 1000 ms: 4
02:08:35, accumulated pauses: 13719 ms, max pause: 13719 ms, pauses over 1000 ms: 1
02:09:15, accumulated pauses: 11662 ms, max pause: 6894 ms, pauses over 1000 ms: 2
02:10:00, accumulated pauses: 12492 ms, max pause: 8045 ms, pauses over 1000 ms: 2
02:10:15, accumulated pauses: 13609 ms, max pause: 6516 ms, pauses over 1000 ms: 4
02:10:30, accumulated pauses: 10160 ms, max pause: 10160 ms, pauses over 1000 ms: 1
02:10:50, accumulated pauses: 19649 ms, max pause: 15220 ms, pauses over 1000 ms: 4
02:11:05, accumulated pauses: 10949 ms, max pause: 6721 ms, pauses over 1000 ms: 3
02:12:30, accumulated pauses: 22691 ms, max pause: 21170 ms, pauses over 1000 ms: 2
02:13:35, accumulated pauses: 23379 ms, max pause: 18720 ms, pauses over 1000 ms: 4
02:14:20, accumulated pauses: 10701 ms, max pause: 10701 ms, pauses over 1000 ms: 1
02:14:45, accumulated pauses: 24026 ms, max pause: 24026 ms, pauses over 1000 ms: 1
```

**Comment by tezc** [comment]
test_gc.log shows a lot of GC activity that might explain these hiccups but don't know if we have a leak somewhere or suddenly we started using more heap.

**Comment by tezc** [comment]
I ran on lab many times, couldn't reproduced it. Also, it didn't fail on last 3-4 builds. Root cause might have already been fixed with latest commits. 

Closing the issue for now.
