### ISSUE TITLE
MetadataRaftGroupTest.when_raftGroupIsDestroyed_then_itCanBeCreatedAgain

### ISSUE THREAD

**Issue by tezc** [hazelcast/hazelcast#15868]
master (commit e365d94d4bc8a06280f7094e47cc8a5bb29b6097)

Failed on Sonar : http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-sonar/279/testReport/com.hazelcast.cp.internal/MetadataRaftGroupTest/when_raftGroupIsDestroyed_then_itCanBeCreatedAgain/

**Stacktrace**

```
java.lang.IllegalStateException: CPGroupId{name='id', seed=0, commitIndex=7} already exists with a different size: 5
	at com.hazelcast.cp.internal.MetadataRaftGroupManager.createRaftGroup(MetadataRaftGroupManager.java:496)
	at com.hazelcast.cp.internal.raftop.metadata.CreateRaftGroupOp.run(CreateRaftGroupOp.java:65)
	at com.hazelcast.cp.internal.raftop.metadata.MetadataRaftGroupOp.run(MetadataRaftGroupOp.java:38)
	at com.hazelcast.cp.internal.NodeEngineRaftIntegration.runOperation(NodeEngineRaftIntegration.java:210)
	at com.hazelcast.cp.internal.raft.impl.RaftNodeImpl.applyLogEntry(RaftNodeImpl.java:828)
	at com.hazelcast.cp.internal.raft.impl.RaftNodeImpl.applyLogEntries(RaftNodeImpl.java:769)
	at com.hazelcast.cp.internal.raft.impl.RaftNodeImpl.commitEntries(RaftNodeImpl.java:1278)
	at com.hazelcast.cp.internal.raft.impl.RaftNodeImpl.tryAdvanceCommitIndex(RaftNodeImpl.java:1262)
	at com.hazelcast.cp.internal.raft.impl.handler.AppendSuccessResponseHandlerTask.handleResponse(AppendSuccessResponseHandlerTask.java:71)
	at com.hazelcast.cp.internal.raft.impl.handler.AbstractResponseHandlerTask.innerRun(AbstractResponseHandlerTask.java:43)
	at com.hazelcast.cp.internal.raft.impl.task.RaftNodeStatusAwareTask.run(RaftNodeStatusAwareTask.java:52)
	at com.hazelcast.cp.internal.NodeEngineRaftIntegration.execute(NodeEngineRaftIntegration.java:113)
	at com.hazelcast.cp.internal.raft.impl.RaftNodeImpl.execute(RaftNodeImpl.java:862)
	at com.hazelcast.cp.internal.raft.impl.RaftNodeImpl.handleAppendResponse(RaftNodeImpl.java:393)
	at com.hazelcast.cp.internal.RaftService.handleAppendResponse(RaftService.java:645)
	at com.hazelcast.cp.internal.operation.integration.AppendSuccessResponseOp.run(AppendSuccessResponseOp.java:48)
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:184)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:216)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:205)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:429)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:154)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:124)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:111)

```

**Comment by tezc** [comment]
http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-sonar/289/testReport/com.hazelcast.cp.internal/MetadataRaftGroupTest/when_raftGroupIsDestroyed_then_itCanBeCreatedAgain/

**Comment by ahmetmircik** [comment]
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/4278/testReport/junit/com.hazelcast.cp.internal/MetadataRaftGroupTest/when_raftGroupIsDestroyed_then_itCanBeCreatedAgain/
