### ISSUE TITLE
ClientMessageProtectionTest.testExceededMessageSize

### ISSUE THREAD

**Issue by tezc** [hazelcast/hazelcast#15870]
master (commit 3bde0614307e2ab11cfaeded7d027bf68765ce29)

http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-ZuluJDK8/49/testReport/com.hazelcast.client.protocol/ClientMessageProtectionTest/testExceededMessageSize/

**Stacktrace**

```
java.lang.AssertionError: 

Expected: an instance of java.io.EOFException
     but: <java.net.SocketException: Connection reset> is a java.net.SocketException
Stacktrace was: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at com.hazelcast.internal.nio.IOUtil.readFullyOrNothing(IOUtil.java:151)
	at com.hazelcast.internal.nio.IOUtil.readFully(IOUtil.java:171)
	at com.hazelcast.client.protocol.ClientMessageProtectionTest.readResponse(ClientMessageProtectionTest.java:224)
	at com.hazelcast.client.protocol.ClientMessageProtectionTest.testExceededMessageSize(ClientMessageProtectionTest.java:151)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)

	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.junit.rules.ExpectedException.handleException(ExpectedException.java:252)
	at org.junit.rules.ExpectedException.accjava.lang.AssertionError: 

Expected: an instance of java.io.EOFException
     but: <java.net.SocketException: Connection reset> is a java.net.SocketException
Stacktrace was: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at com.hazelcast.internal.nio.IOUtil.readFullyOrNothing(IOUtil.java:151)
	at com.hazelcast.internal.nio.IOUtil.readFully(IOUtil.java:171)
	at com.hazelcast.client.protocol.ClientMessageProtectionTest.readResponse(ClientMessageProtectionTest.java:224)
	at com.hazelcast.client.protocol.ClientMessageProtectionTest.testExceededMessageSize(ClientMessageProtectionTest.java:151)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)

	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.junit.rules.ExpectedException.handleException(ExpectedException.java:252)
	at org.junit.rules.ExpectedException.access$000(ExpectedException.java:106)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:241)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at com.hazelcast.test.HazelcastParallelClassRunner.access$301(HazelcastParallelClassRunner.java:49)
	at com.hazelcast.test.HazelcastParallelClassRunner$TestRunner.run(HazelcastParallelClassRunner.java:162)
	at java.lang.Thread.run(Thread.java:748)ess$000(ExpectedException.java:106)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:241)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at com.hazelcast.test.HazelcastParallelClassRunner.access$301(HazelcastParallelClassRunner.java:49)
	at com.hazelcast.test.HazelcastParallelClassRunner$TestRunner.run(HazelcastParallelClassRunner.java:162)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by sancar** [comment]
Similar test failed 
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/4096/

com.hazelcast.client.protocol.ClientMessageProtectionTest.testLimitsRemovedAfterAValidAuthentication

```
Stacktrace
java.lang.AssertionError
	at com.hazelcast.client.protocol.ClientMessageProtectionTest.readResponse(ClientMessageProtectionTest.java:234)
	at com.hazelcast.client.protocol.ClientMessageProtectionTest.testLimitsRemovedAfterAValidAuthentication(ClientMessageProtectionTest.java:90)
Standard Output
Finished Running Test: testAccumulatedMessageSizeOverflow in 0.406 seconds.
11:45:35,827  INFO |testLimitsRemovedAfterAValidAuthentication| - [LifecycleService] Thread-1914 - [127.0.0.1]:5302 [testLimitsRemovedAfterAValidAuthentication] [4.0-SNAPSHOT] [127.0.0.1]:5302 is SHUTTING_DOWN
11:45:35,828  WARN |testLimitsRemovedAfterAValidAuthentication| - [Node] Thread-1914 - [127.0.0.1]:5302 [testLimitsRemovedAfterAValidAuthentication] [4.0-SNAPSHOT] Terminating forcefully...
11:45:35,828  INFO |testLimitsRemovedAfterAValidAuthentication| - [Node] Thread-1914 - [127.0.0.1]:5302 [testLimitsRemovedAfterAValidAuthentication] [4.0-SNAPSHOT] Shutting down connection manager...
11:45:35,828  INFO |testLimitsRemovedAfterAValidAuthentication| - [Node] Thread-1914 - [127.0.0.1]:5302 [testLimitsRemovedAfterAValidAuthentication] [4.0-SNAPSHOT] Shutting down node engine...
11:45:35,829  INFO |testLimitsRemovedAfterAValidAuthentication| - [NodeExtension] Thread-1914 - [127.0.0.1]:5302 [testLimitsRemovedAfterAValidAuthentication] [4.0-SNAPSHOT] Destroying node NodeExtension.
11:45:35,829  INFO |testLimitsRemovedAfterAValidAuthentication| - [Node] Thread-1914 - [127.0.0.1]:5302 [testLimitsRemovedAfterAValidAuthentication] [4.0-SNAPSHOT] Hazelcast Shutdown is completed in 1 ms.
11:45:35,829  INFO |testLimitsRemovedAfterAValidAuthentication| - [LifecycleService] Thread-1914 - [127.0.0.1]:5302 [testLimitsRemovedAfterAValidAuthentication] [4.0-SNAPSHOT] [127.0.0.1]:5302 is SHUTDOWN
```

I am sending a pr to ignore the whole `ClientMessageProtectionTest` because it is failing a lot. 
https://github.com/hazelcast/hazelcast/pull/15922
We should remove the @Ignore tag once the issue is addressed.

**Comment by petrpleshachkov** [comment]
@kwart, I've managed to reproduce an initial test failure on my machine. In the below method you expect -1 from `in.read`. My understanding is that you may get `SocketException("Connection reset")` when socket closes on the server side. WDYT, to handle this exception here as well?

```
    public static boolean readFullyOrNothing(InputStream in, byte[] buffer) throws IOException {
        int bytesRead = 0;
        do {
            int count = in.read(buffer, bytesRead, buffer.length - bytesRead);
            if (count < 0) {
                if (bytesRead == 0) {
                    return false;
                }
                throw new EOFException();
            }
            bytesRead += count;
        } while (bytesRead < buffer.length);
        return true;
    }
```

**Comment by kwart** [comment]
@petrpleshachkov Thank you for the analysis. I think the `SocketException` handling should be on the callers side. I'll prepare a fix for the test case code.
