### ISSUE TITLE
WriteBehindEntryStoreQueueReplicationTest.queued_entries_with_expirationTimes_are_replicated_when_cluster_scaled

### ISSUE THREAD

**Issue by mdogan** [hazelcast/hazelcast#15877]
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/4021/testReport/junit/com.hazelcast.map.impl.mapstore.writebehind/WriteBehindEntryStoreQueueReplicationTest/queued_entries_with_expirationTimes_are_replicated_when_cluster_scaled_up/

```
java.lang.AssertionError: Expected 'expirationTime' to be between 1572011647548 and 1572011651548, but was 1572011652000
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport.assertBetween(HazelcastTestSupport.java:1461)
	at com.hazelcast.map.impl.mapstore.TestEntryStore.assertRecordStored(TestEntryStore.java:171)
	at com.hazelcast.map.impl.mapstore.writebehind.WriteBehindEntryStoreQueueReplicationTest.lambda$queued_entries_with_expirationTimes_are_replicated_when_cluster_scaled_up$2(WriteBehindEntryStoreQueueReplicationTest.java:116)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1318)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1420)
	at com.hazelcast.map.impl.mapstore.writebehind.WriteBehindEntryStoreQueueReplicationTest.queued_entries_with_expirationTimes_are_replicated_when_cluster_scaled_up(WriteBehindEntryStoreQueueReplicationTest.java:114)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by mdogan** [comment]
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/4021/testReport/junit/com.hazelcast.map.impl.mapstore.writebehind/WriteBehindEntryStoreQueueReplicationTest/queued_entries_with_expiration_times_are_not_lost_when_cluster_scaled_down/

```
java.lang.AssertionError: Expected 'expirationTime' to be between 1572011649119 and 1572011653119, but was 1572011654000
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport.assertBetween(HazelcastTestSupport.java:1461)
	at com.hazelcast.map.impl.mapstore.TestEntryStore.assertRecordStored(TestEntryStore.java:171)
	at com.hazelcast.map.impl.mapstore.writebehind.WriteBehindEntryStoreQueueReplicationTest.lambda$queued_entries_with_expiration_times_are_not_lost_when_cluster_scaled_down$0(WriteBehindEntryStoreQueueReplicationTest.java:73)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1318)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1420)
	at com.hazelcast.map.impl.mapstore.writebehind.WriteBehindEntryStoreQueueReplicationTest.queued_entries_with_expiration_times_are_not_lost_when_cluster_scaled_down(WriteBehindEntryStoreQueueReplicationTest.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(Future
```

**Comment by mmedenjak** [comment]
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/4561

**Comment by vbekiaris** [comment]
Failed again in PR builder http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/4669 with several pauses.

**Comment by mdogan** [comment]
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/5784/testReport/junit/com.hazelcast.map.impl.mapstore.writebehind/WriteBehindEntryStoreQueueReplicationTest/queued_entries_with_expiration_times_are_not_lost_when_cluster_scaled_down/

```
java.lang.AssertionError: Expected 'expirationTime' to be between 1581342776000 and 1581342780000, but was 1581342781000
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport.assertBetween(HazelcastTestSupport.java:1385)
	at com.hazelcast.map.impl.mapstore.TestEntryStore.assertRecordStored(TestEntryStore.java:171)
	at com.hazelcast.map.impl.mapstore.writebehind.WriteBehindEntryStoreQueueReplicationTest.lambda$queued_entries_with_expiration_times_are_not_lost_when_cluster_scaled_down$0(WriteBehindEntryStoreQueueReplicationTest.java:84)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1242)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1344)
	at com.hazelcast.map.impl.mapstore.writebehind.WriteBehindEntryStoreQueueReplicationTest.queued_entries_with_expiration_times_are_not_lost_when_cluster_scaled_down(WriteBehindEntryStoreQueueReplicationTest.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

```
Hiccups measured while running test 'queued_entries_with_expiration_times_are_not_lost_when_cluster_scaled_down(com.hazelcast.map.impl.mapstore.writebehind.WriteBehindEntryStoreQueueReplicationTest):'
13:52:45, accumulated pauses: 3760 ms, max pause: 1487 ms, pauses over 1000 ms: 2
13:52:50, accumulated pauses: 2319 ms, max pause: 991 ms, pauses over 1000 ms: 0
13:52:55, accumulated pauses: 2444 ms, max pause: 1062 ms, pauses over 1000 ms: 1
13:53:00, accumulated pauses: 1077 ms, max pause: 345 ms, pauses over 1000 ms: 0
13:53:05, accumulated pauses: 457 ms, max pause: 34 ms, pauses over 1000 ms: 0
13:53:10, accumulated pauses: 375 ms, max pause: 23 ms, pauses over 1000 ms: 0
13:53:15, accumulated pauses: 394 ms, max pause: 34 ms, pauses over 1000 ms: 0
13:53:20, accumulated pauses: 495 ms, max pause: 35 ms, pauses over 1000 ms: 0
13:53:25, accumulated pauses: 639 ms, max pause: 49 ms, pauses over 1000 ms: 0
13:53:30, accumulated pauses: 603 ms, max pause: 114 ms, pauses over 1000 ms: 0
13:53:35, accumulated pauses: 529 ms, max pause: 27 ms, pauses over 1000 ms: 0
13:53:40, accumulated pauses: 294 ms, max pause: 17 ms, pauses over 1000 ms: 0
13:53:45, accumulated pauses: 274 ms, max pause: 14 ms, pauses over 1000 ms: 0
13:53:50, accumulated pauses: 656 ms, max pause: 27 ms, pauses over 1000 ms: 0
13:53:55, accumulated pauses: 414 ms, max pause: 32 ms, pauses over 1000 ms: 0
13:54:00, accumulated pauses: 699 ms, max pause: 42 ms, pauses over 1000 ms: 0
13:54:05, accumulated pauses: 698 ms, max pause: 36 ms, pauses over 1000 ms: 0
13:54:10, accumulated pauses: 682 ms, max pause: 196 ms, pauses over 1000 ms: 0
13:54:15, accumulated pauses: 1107 ms, max pause: 575 ms, pauses over 1000 ms: 0
13:54:20, accumulated pauses: 605 ms, max pause: 113 ms, pauses over 1000 ms: 0
13:54:25, accumulated pauses: 429 ms, max pause: 19 ms, pauses over 1000 ms: 0
13:54:30, accumulated pauses: 492 ms, max pause: 16 ms, pauses over 1000 ms: 0
13:54:35, accumulated pauses: 426 ms, max pause: 17 ms, pauses over 1000 ms: 0
13:54:40, accumulated pauses: 743 ms, max pause: 33 ms, pauses over 1000 ms: 0
13:54:45, accumulated pauses: 457 ms, max pause: 84 ms, pauses over 1000 ms: 0
13:54:50, accumulated pauses: 465 ms, max pause: 83 ms, pauses over 1000 ms: 0
13:54:55, accumulated pauses: 517 ms, max pause: 30 ms, pauses over 1000 ms: 0
13:55:00, accumulated pauses: 445 ms, max pause: 118 ms, pauses over 1000 ms: 0
```

**Comment by Holmistr** [comment]
Closing the issue since we adjusted the environment's resources. Should be more stable now.
