### ISSUE TITLE
Double metric collection for tcp.connection.clientCount

### ISSUE THREAD

**Issue by blazember** [hazelcast/hazelcast#15883]
`tcp.connection.clientCount` is collected and published twice as the assertion error reports.

```
AssertionError: metric '[unit=count,metric=tcp.connection.clientCount]' was rendered twice
    at com.hazelcast.internal.metrics.jmx.JmxPublisher.publishNumber(JmxPublisher.java:100)
    at com.hazelcast.internal.metrics.jmx.JmxPublisher.publishLong(JmxPublisher.java:86)
    at com.hazelcast.internal.metrics.impl.MetricsService$PublisherMetricsCollector.collectLong(MetricsService.java:250)
    at com.hazelcast.internal.metrics.impl.MetricsCollectionCycle.collectLong(MetricsCollectionCycle.java:165)
    at com.hazelcast.internal.metrics.impl.MetricsCollectionCycle.collect(MetricsCollectionCycle.java:144)
    at com.hazelcast.internal.metrics.impl.MetricsCollectionCycle.extractAndCollectDynamicMetrics(MetricsCollectionCycle.java:116)
    at com.hazelcast.internal.metrics.impl.MetricsCollectionCycle.access$300(MetricsCollectionCycle.java:47)
    at com.hazelcast.internal.metrics.impl.MetricsCollectionCycle$MetricsContext.collect(MetricsCollectionCycle.java:183)
    at com.hazelcast.internal.nio.tcp.TcpIpUnifiedEndpointManager.provideDynamicMetrics(TcpIpUnifiedEndpointManager.java:118)
    at com.hazelcast.internal.nio.tcp.TcpIpNetworkingService$MetricsProvider.provideDynamicMetrics(TcpIpNetworkingService.java:393)
    at com.hazelcast.internal.metrics.impl.MetricsCollectionCycle.collectDynamicMetrics(MetricsCollectionCycle.java:89)
    at com.hazelcast.internal.metrics.impl.MetricsRegistryImpl.collect(MetricsRegistryImpl.java:287)
    at com.hazelcast.internal.metrics.impl.MetricsService.collectMetrics(MetricsService.java:157)
    at com.hazelcast.internal.metrics.impl.MetricsService.collectMetrics(MetricsService.java:152)
    at com.hazelcast.spi.impl.executionservice.impl.DelegateAndSkipOnConcurrentExecutionDecorator$DelegateDecorator.run(DelegateAndSkipOnConcurrentExecutionDecorator.java:77)
    at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
    at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
    at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
```

**Comment by blazember** [comment]
This happens because both `TcpIpEndpointManager` and its child `TcpIpUnifiedEndpointManager` provides `this` as a metric source under `tcp.connection` namespace. The solution should be making `TcpIpUnifiedEndpointManager` not to provide dynamic metrics since all of its metrics are provided by its parent.
