### ISSUE TITLE
Metric `memory.freePhysical` throws InvocationTargetException on JDK11

### ISSUE THREAD

**Issue by blazember** [hazelcast/hazelcast#15884]
```
08:53:27,905  WARN || - [MetricsService] hz.compassionate_almeida.cached.thread-10 - [127.0.0.1]:5702 [jet] [4.0-SNAPSHOT] Error when rendering '[unit=count,metric=memory.freePhysical]'
java.lang.reflect.InvocationTargetException
    at jdk.internal.reflect.GeneratedMethodAccessor37.invoke(Unknown Source)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at com.hazelcast.internal.metrics.impl.MethodProbe$LongMethodProbe.get(MethodProbe.java:114)
    at com.hazelcast.internal.metrics.impl.MetricsCollectionCycle.collectLong(MetricsCollectionCycle.java:164)
    at com.hazelcast.internal.metrics.impl.MetricsCollectionCycle.collectStaticMetrics(MetricsCollectionCycle.java:78)
    at com.hazelcast.internal.metrics.impl.MetricsRegistryImpl.collect(MetricsRegistryImpl.java:286)
    at com.hazelcast.internal.metrics.impl.MetricsService.collectMetrics(MetricsService.java:157)
    at com.hazelcast.internal.metrics.impl.MetricsService.collectMetrics(MetricsService.java:152)
    at com.hazelcast.spi.impl.executionservice.impl.DelegateAndSkipOnConcurrentExecutionDecorator$DelegateDecorator.run(DelegateAndSkipOnConcurrentExecutionDecorator.java:77)
    at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:834)
    at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
    at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.hazelcast.internal.memory.MemoryStatsSupport
    at com.hazelcast.internal.memory.DefaultMemoryStats.getFreePhysical(DefaultMemoryStats.java:39)
    ... 16 more
```

**Comment by blazember** [comment]
Closed with #15892
