### ISSUE TITLE
CPMemberAddRemoveTest.testExpandRaftGroup

### ISSUE THREAD

**Issue by ahmetmircik** [hazelcast/hazelcast#15903]
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/4061/testReport/junit/com.hazelcast.cp.internal/CPMemberAddRemoveTest/testExpandRaftGroup/

__Error Message__

```
java.lang.IllegalStateException: Cannot rebalance CP groups because there is 
ongoing MembershipChangeSchedule{membershipChangeCommitIndices=[5], 
member=CPMember{uuid=fec34bf2-8d47-45cf-a55e-2b60eedefd8b, address=
[127.0.0.1]:5701}, membershipChangeMode=REMOVE, changes=
[CPGroupMembershipChange{groupId=CPGroupId{name='METADATA', seed=0, 
commitIndex=0}, membersCommitIndex=0, members=[RaftEndpoint{uuid='fec34bf2-8d47-
45cf-a55e-2b60eedefd8b'}, RaftEndpoint{uuid='2cd7a9e8-97f1-40be-a9e9-
80bdb4ff864d'}, RaftEndpoint{uuid='3f8c63fc-b8ab-412a-8794-21515b012753'}], 
memberToAdd=null, memberToRemove=RaftEndpoint{uuid='fec34bf2-8d47-45cf-a55e-
2b60eedefd8b'}}]}
```

__Stacktrace__
```
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Cannot rebalance CP groups because there is ongoing MembershipChangeSchedule{membershipChangeCommitIndices=[5], member=CPMember{uuid=fec34bf2-8d47-45cf-a55e-2b60eedefd8b, address=[127.0.0.1]:5701}, membershipChangeMode=REMOVE, changes=[CPGroupMembershipChange{groupId=CPGroupId{name='METADATA', seed=0, commitIndex=0}, membersCommitIndex=0, members=[RaftEndpoint{uuid='fec34bf2-8d47-45cf-a55e-2b60eedefd8b'}, RaftEndpoint{uuid='2cd7a9e8-97f1-40be-a9e9-80bdb4ff864d'}, RaftEndpoint{uuid='3f8c63fc-b8ab-412a-8794-21515b012753'}], memberToAdd=null, memberToRemove=RaftEndpoint{uuid='fec34bf2-8d47-45cf-a55e-2b60eedefd8b'}}]}
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
	at com.hazelcast.spi.impl.DeserializingCompletableFuture.get(DeserializingCompletableFuture.java:101)
	at com.hazelcast.cp.internal.CPMemberAddRemoveTest.testExpandRaftGroup(CPMemberAddRemoveTest.java:399)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Cannot rebalance CP groups because there is ongoing MembershipChangeSchedule{membershipChangeCommitIndices=[5], member=CPMember{uuid=fec34bf2-8d47-45cf-a55e-2b60eedefd8b, address=[127.0.0.1]:5701}, membershipChangeMode=REMOVE, changes=[CPGroupMembershipChange{groupId=CPGroupId{name='METADATA', seed=0, commitIndex=0}, membersCommitIndex=0, members=[RaftEndpoint{uuid='fec34bf2-8d47-45cf-a55e-2b60eedefd8b'}, RaftEndpoint{uuid='2cd7a9e8-97f1-40be-a9e9-80bdb4ff864d'}, RaftEndpoint{uuid='3f8c63fc-b8ab-412a-8794-21515b012753'}], memberToAdd=null, memberToRemove=RaftEndpoint{uuid='fec34bf2-8d47-45cf-a55e-2b60eedefd8b'}}]}
	at com.hazelcast.internal.util.Preconditions.checkState(Preconditions.java:355)
	at com.hazelcast.cp.internal.MetadataRaftGroupManager.addMember(MetadataRaftGroupManager.java:1010)
	at com.hazelcast.cp.internal.raftop.metadata.AddCPMemberOp.run(AddCPMemberOp.java:50)
	at com.hazelcast.cp.internal.raftop.metadata.MetadataRaftGroupOp.run(MetadataRaftGroupOp.java:38)
	at com.hazelcast.cp.internal.NodeEngineRaftIntegration.runOperation(NodeEngineRaftIntegration.java:210)
	at com.hazelcast.cp.internal.raft.impl.RaftNodeImpl.applyLogEntry(RaftNodeImpl.java:828)
	at com.hazelcast.cp.internal.raft.impl.RaftNodeImpl.applyLogEntries(RaftNodeImpl.java:769)
	at com.hazelcast.cp.internal.raft.impl.RaftNodeImpl.commitEntries(RaftNodeImpl.java:1278)
	at com.hazelcast.cp.internal.raft.impl.RaftNodeImpl.tryAdvanceCommitIndex(RaftNodeImpl.java:1262)
	at com.hazelcast.cp.internal.raft.impl.handler.AppendSuccessResponseHandlerTask.handleResponse(AppendSuccessResponseHandlerTask.java:71)
	at com.hazelcast.cp.internal.raft.impl.handler.AbstractResponseHandlerTask.innerRun(AbstractResponseHandlerTask.java:43)
	at com.hazelcast.cp.internal.raft.impl.task.RaftNodeStatusAwareTask.run(RaftNodeStatusAwareTask.java:52)
	at com.hazelcast.cp.internal.NodeEngineRaftIntegration.execute(NodeEngineRaftIntegration.java:113)
	at com.hazelcast.cp.internal.raft.impl.RaftNodeImpl.execute(RaftNodeImpl.java:862)
	at com.hazelcast.cp.internal.raft.impl.RaftNodeImpl.handleAppendResponse(RaftNodeImpl.java:393)
	at com.hazelcast.cp.internal.RaftService.handleAppendResponse(RaftService.java:645)
	at com.hazelcast.cp.internal.operation.integration.AppendSuccessResponseOp.run(AppendSuccessResponseOp.java:48)
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:184)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:216)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:205)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:429)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:154)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:124)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:111)
```

**Comment by metanet** [comment]
fixed by https://github.com/hazelcast/hazelcast/pull/15906
