### ISSUE TITLE
ScheduledExecutorSplitBrainProtectionWriteTest .schedule_runnable_splitBrainProtection

### ISSUE THREAD

**Issue by ahmetmircik** [hazelcast/hazelcast#15904]
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/4061/testReport/junit/com.hazelcast.splitbrainprotection.scheduledexecutor/ScheduledExecutorSplitBrainProtectionWriteTest/schedule_runnable_splitBrainProtection_splitBrainProtectionType_WRITE_/

__Error Message__
```
test timed out after 300000 milliseconds
```

__Stacktrace__
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:304)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:620)
	at com.hazelcast.scheduledexecutor.impl.ScheduledFutureProxy.get(ScheduledFutureProxy.java:150)
	at com.hazelcast.splitbrainprotection.scheduledexecutor.ScheduledExecutorSplitBrainProtectionWriteTest.schedule_runnable_splitBrainProtection(ScheduledExecutorSplitBrainProtectionWriteTest.java:87)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by ihsandemir** [comment]
Another failure: http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/4167/testReport/junit/com.hazelcast.client.splitbrainprotection.scheduledexecutor/ClientScheduledExecutorSplitBrainProtectionWriteTest/schedule_runnable_splitBrainProtection_splitBrainProtectionType_READ_WRITE_/

```
Error Message
test timed out after 300000 milliseconds
Stacktrace
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:338)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:646)
	at com.hazelcast.client.impl.proxy.ClientScheduledFutureProxy.get0(ClientScheduledFutureProxy.java:210)
	at com.hazelcast.client.impl.proxy.ClientScheduledFutureProxy.get(ClientScheduledFutureProxy.java:220)
	at com.hazelcast.splitbrainprotection.scheduledexecutor.ScheduledExecutorSplitBrainProtectionWriteTest.schedule_runnable_splitBrainProtection(ScheduledExecutorSplitBrainProtectionWriteTest.java:87)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by mmedenjak** [comment]
The issue seems to be because the task in `ScheduledExecutorSplitBrainProtectionWriteTest#schedule_runnable_splitBrainProtection` is scheduled but is later cancelled due to a migration even though the partition owner never changes and the migration is only promoting another member to a backup replica.

The task is scheduled:
```
16:25:43,238 TRACE || - [ScheduledExecutorContainer] hz.cocky_booth.partition-operation.thread-1 - [127.0.0.1]:5702 [rlalspncdr] [4.0-SNAPSHOT] [Scheduler: splitBrainProtectiond8cb8440-6d9f-4501-8fda-b99eca021b02WRITE][Partition: 3][Task: 00566bc3-ddd4-4dd1-859f-f28188ed16ee] Scheduled
16:25:43,240 TRACE || - [ScheduledExecutorContainer] hz.cocky_booth.partition-operation.thread-1 - [127.0.0.1]:5702 [rlalspncdr] [4.0-SNAPSHOT] [Scheduler: splitBrainProtectiond8cb8440-6d9f-4501-8fda-b99eca021b02WRITE][Partition: 3]Queue size: 1
```

The promotion of the other member starts and the partition owner prepares the data:
```
16:25:43,242 DEBUG || - [MigrationManager] hz.cool_booth.migration - [127.0.0.1]:5701 [rlalspncdr] [4.0-SNAPSHOT] Starting Migration: MigrationInfo{uuid=10a5408b-e6d2-4986-97e5-11d6c454b5a0, partitionId=3, source=null, sourceCurrentReplicaIndex=-1, sourceNewReplicaIndex=-1, destination=[127.0.0.1]:5701 - a1cd022b-35f6-43f6-be1a-2bbbd9e9f773, destinationCurrentReplicaIndex=4, destinationNewReplicaIndex=1, master=[127.0.0.1]:5701, initialPartitionVersion=91, partitionVersionIncrement=2, processing=false, status=ACTIVE}

16:25:43,242 TRACE || - [ScheduledExecutorPartition] hz.cocky_booth.partition-operation.thread-1 - [127.0.0.1]:5702 [rlalspncdr] [4.0-SNAPSHOT] [Partition: 3] Prepare replication(migration: true) for index: 1
```

The task is then copied to the other node, which is now the backup and the migration completes:
```
16:25:43,245 TRACE || - [ScheduledExecutorPartition] hz.cool_booth.partition-operation.thread-1 - [127.0.0.1]:5701 [rlalspncdr] [4.0-SNAPSHOT] [Partition:3]Create new scheduled executor container with name:splitBrainProtectiond8cb8440-6d9f-4501-8fda-b99eca021b02WRITE
16:25:43,245 TRACE || - [ScheduledExecutorContainer] hz.cool_booth.partition-operation.thread-1 - [127.0.0.1]:5701 [rlalspncdr] [4.0-SNAPSHOT] [Scheduler: splitBrainProtectiond8cb8440-6d9f-4501-8fda-b99eca021b02WRITE][Partition: 3]Enqueuing suspended, i.e., backup: TaskDefinition{type=SINGLE_RUN, name='00566bc3-ddd4-4dd1-859f-f28188ed16ee', command=ScheduledRunnableAdapter{task=com.hazelcast.splitbrainprotection.scheduledexecutor.ScheduledExecutorSplitBrainProtectionWriteTest$ExecRunnable@766cc8ea}, initialDelay=10, period=0, unit=MILLISECONDS}


16:25:43,246 DEBUG || - [MigrationManager] hz.cool_booth.migration - [127.0.0.1]:5701 [rlalspncdr] [4.0-SNAPSHOT] Finished Migration: MigrationInfo{uuid=10a5408b-e6d2-4986-97e5-11d6c454b5a0, partitionId=3, source=null, sourceCurrentReplicaIndex=-1, sourceNewReplicaIndex=-1, destination=[127.0.0.1]:5701 - a1cd022b-35f6-43f6-be1a-2bbbd9e9f773, destinationCurrentReplicaIndex=4, destinationNewReplicaIndex=1, master=[127.0.0.1]:5701, initialPartitionVersion=91, partitionVersionIncrement=2, processing=false, status=ACTIVE}
```

The problem is, we have mistakenly cancelled the task on the partition owner while collecting the tasks - see `ScheduledExecutorContainer#prepareForReplication`.

**Comment by mmedenjak** [comment]
This might be one of the reasons for https://github.com/hazelcast/hazelcast/issues/12197 as well.

**Comment by mmedenjak** [comment]
Actually the problem seems to be that there is a concurrent `FinalizeMigrationOperation` from a previous migration running as otherwise the `DistributedScheduledExecutorService#beforeMigration` method would not have been invoked since the member `[127.0.0.1]:5702` is not migrating for partition 3:

```
16:25:43,241 DEBUG || - [MigrationManager] hz.cool_booth.migration - [127.0.0.1]:5701 [rlalspncdr] [4.0-SNAPSHOT] Finished Migration: MigrationInfo{uuid=55b5dc0f-3336-4aa1-bd91-46eb6423f7cc, partitionId
=2, source=null, sourceCurrentReplicaIndex=-1, sourceNewReplicaIndex=-1, destination=[127.0.0.1]:5702 - 83abd748-2958-4563-8a5c-364c0311d619, destinationCurrentReplicaIndex=4, destinationNewReplicaIndex
=1, master=[127.0.0.1]:5701, initialPartitionVersion=89, partitionVersionIncrement=2, processing=false, status=ACTIVE}
16:25:43,241 DEBUG || - [InternalPartitionService] hz.cocky_booth.priority-generic-operation.thread-0 - [127.0.0.1]:5702 [rlalspncdr] [4.0-SNAPSHOT] Committed MigrationInfo{uuid=55b5dc0f-3336-4aa1-bd91-
46eb6423f7cc, partitionId=2, source=null, sourceCurrentReplicaIndex=-1, sourceNewReplicaIndex=-1, destination=[127.0.0.1]:5702 - 83abd748-2958-4563-8a5c-364c0311d619, destinationCurrentReplicaIndex=4, d
estinationNewReplicaIndex=1, master=[127.0.0.1]:5701, initialPartitionVersion=89, partitionVersionIncrement=2, processing=false, status=SUCCESS} on destination with partition state version: 91
```
