### ISSUE TITLE
PNCounterBounceTest.mutateAndBounceMembersProducesCorrectResult

### ISSUE THREAD

**Issue by tezc** [hazelcast/hazelcast#15905]
master (commit c34bd6d658dd8b6e553aa0fdc4d6074dce3dadd4)

http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-sonar/285/testReport/com.hazelcast.internal.crdt.pncounter/PNCounterBounceTest/mutateAndBounceMembersProducesCorrectResult/

**Stacktrace**
```
java.lang.AssertionError: expected:<-9467899> but was:<-9467925>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.internal.crdt.pncounter.PNCounterBounceTest$1.run(PNCounterBounceTest.java:56)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1325)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1427)
	at com.hazelcast.internal.crdt.pncounter.PNCounterBounceTest.assertState(PNCounterBounceTest.java:53)
	at com.hazelcast.internal.crdt.AbstractCRDTBounceTest.mutateAndBounceMembersProducesCorrectResult(AbstractCRDTBounceTest.java:95)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by vbekiaris** [comment]
Member 5703 is shutting down to be bounced:

```
23:50:03,946  INFO |mutateAndBounceMembersProducesCorrectResult| - [LifecycleService] Thread-16250 - [127.0.0.1]:5703 [dev] [4.0-SNAPSHOT] [127.0.0.1]:5703 is SHUTTING_DOWN
23:50:03,947  INFO |mutateAndBounceMembersProducesCorrectResult| - [Node] Thread-16250 - [127.0.0.1]:5703 [dev] [4.0-SNAPSHOT] Shutting down connection manager...
```

Connections are closed, other members update their members table:
```
23:50:03,947  INFO |mutateAndBounceMembersProducesCorrectResult| - [ClusterService] Thread-16250 - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] 

Members {size:2, ver:6} [
        Member [127.0.0.1]:5701 - 4fdc61f3-7f45-4433-aa18-5a12cadc98c2 this
        Member [127.0.0.1]:5704 - fb93501f-dc5d-4bd1-a909-1f333b5921a4
]
23:50:03,949  INFO |mutateAndBounceMembersProducesCorrectResult| - [ClusterService] hz.festive_kirch.priority-generic-operation.thread-0 - [127.0.0.1]:5704 [dev] [4.0-SNAPSHOT] 

Members {size:2, ver:6} [
        Member [127.0.0.1]:5701 - 4fdc61f3-7f45-4433-aa18-5a12cadc98c2
        Member [127.0.0.1]:5704 - fb93501f-dc5d-4bd1-a909-1f333b5921a4 this
]
```

The only suspicious log entry is the one that follows:
```
23:50:03,949  WARN |mutateAndBounceMembersProducesCorrectResult| - [Invocation] MutationThread - [127.0.0.1]:5703 [dev] [4.0-SNAPSHOT] Future.complete(Object) on completed future. Request: Invocation{op=com.hazelcast.internal.crdt.pncounter.operations.AddOperation{serviceName='hz:impl:PNCounterService', identityHash=2144917531, partitionId=-1, replicaIndex=0, callId=-948180, invocationTime=1572479403946 (2019-10-30 23:50:03.946), waitTimeout=-1, callTimeout=120000, name=counter}, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=120000, firstInvocationTimeMs=1572479403946, firstInvocationTime='2019-10-30 23:50:03.946', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 00:00:00.000', target=[127.0.0.1]:5703, pendingResponse={VOID}, backupsAcksExpected=-1, backupsAcksReceived=0, connection=null}, current value: ExceptionalResult{cause=com.hazelcast.core.HazelcastInstanceNotActiveException: Hazelcast instance is not active!}, offered value: com.hazelcast.internal.crdt.pncounter.operations.CRDTTimestampedLong@711f2990
java.lang.Exception
        at com.hazelcast.spi.impl.AbstractInvocationFuture.warnIfSuspiciousDoubleCompletion(AbstractInvocationFuture.java:1225) [classes/:?]
        at com.hazelcast.spi.impl.AbstractInvocationFuture.complete0(AbstractInvocationFuture.java:1206) [classes/:?]
        at com.hazelcast.spi.impl.AbstractInvocationFuture.complete(AbstractInvocationFuture.java:1195) [classes/:?]
        at com.hazelcast.spi.impl.operationservice.impl.Invocation.complete(Invocation.java:646) [classes/:?]
        at com.hazelcast.spi.impl.operationservice.impl.Invocation.sendResponse(Invocation.java:231) [classes/:?]
        at com.hazelcast.spi.impl.operationservice.Operation.sendResponse(Operation.java:470) [classes/:?]
        at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.handleResponse(OperationRunnerImpl.java:252) [classes/:?]
        at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:220) [classes/:?]
        at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:205) [classes/:?]
        at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:394) [classes/:?]
        at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:421) [classes/:?]
        at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:590) [classes/:?]
        at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:575) [classes/:?]
        at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:534) [classes/:?]
        at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:236) [classes/:?]
        at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:60) [classes/:?]
        at com.hazelcast.internal.crdt.pncounter.PNCounterProxy.invokeInternal(PNCounterProxy.java:195) [classes/:?]
        at com.hazelcast.internal.crdt.pncounter.PNCounterProxy.invoke(PNCounterProxy.java:159) [classes/:?]
        at com.hazelcast.internal.crdt.pncounter.PNCounterProxy.addAndGet(PNCounterProxy.java:100) [classes/:?]
        at com.hazelcast.internal.crdt.pncounter.PNCounterBounceTest.mutate(PNCounterBounceTest.java:47) [test-classes/:?]
        at com.hazelcast.internal.crdt.AbstractCRDTBounceTest$MutationThread.doRun(AbstractCRDTBounceTest.java:151) [test-classes/:?]
        at com.hazelcast.test.TestThread.run(TestThread.java:43) [test-classes/:?]
```

So a `com.hazelcast.internal.crdt.pncounter.operations.AddOperation` was being executed on 5703; the `InvocationFuture` is already completed with `HazelcastInstanceNotActiveException` (due to 5703 shutting down) and the result of the `AddOperation` is not used to complete the invocation future. The `HazelcastInstanceNotActiveException` is not caught in [`PNCounterProxy#invoke`](https://github.com/hazelcast/hazelcast/blob/d4ec22142061335849718dec7c81c88cde50d68e/hazelcast/src/main/java/com/hazelcast/internal/crdt/pncounter/PNCounterProxy.java#L199) -> mutation thread [ignores this exception](https://github.com/hazelcast/hazelcast/blob/305ccfc05776dad5672848ef8d92545b311d5ff9/hazelcast/src/test/java/com/hazelcast/internal/crdt/AbstractCRDTBounceTest.java#L152), also ignoring the outcome of the failed operation, so it shouldn't cause any trouble with the test assertion. There is no further indication of anything gone wrong in the test, I can only suggest lowering log level in the test and waiting for another failure. @mmedenjak wdyt?

**Comment by mmedenjak** [comment]
What I can conclude is that the mutator thread invoked `PNCounter#addAndGet` and got a `HazelcastInstanceNotActiveException` which then was a signal that the operation wasn't executed so the [PNCounterBounceTest#assertionCounter](https://github.com/hazelcast/hazelcast/blob/305ccfc05776dad5672848ef8d92545b311d5ff9/hazelcast/src/test/java/com/hazelcast/internal/crdt/pncounter/PNCounterBounceTest.java#L48) wasn't updated.

But, somehow, in fact, the operation ended up being rescheduled and executed successfully:
```
23:50:03,949  WARN |mutateAndBounceMembersProducesCorrectResult| - [Invocation] MutationThread - [127.0.0.1]:5703 [dev] [4.0-SNAPSHOT] Future.complete(Object) on completed future. Request: Invocation{op=com.hazelcast.internal.crdt.pncounter.operations.AddOperation..., current value: ExceptionalResult{cause=com.hazelcast.core.HazelcastInstanceNotActiveException: Hazelcast instance is not active!}, offered value: com.hazelcast.internal.crdt.pncounter.operations.CRDTTimestampedLong@711f2990
```

If this mutation ended up being replicated to other members, we get divergence between the `assertionCounter` and the actual state. Since the difference between the expected and the actual state is `-26`, which is in the range of a single mutation operation (`final int delta = rnd.nextInt(100) - 50;`), I would conclude this is the case.

The issue then, isn't about the PN counter implementation but why an operation may be executed twice and if it can be avoided. Generally speaking, there are other similar issues:
https://github.com/hazelcast/hazelcast/issues/11617
https://github.com/hazelcast/hazelcast/issues/11839
https://github.com/hazelcast/hazelcast/issues/12952

And we even list it in our [documentation](https://docs.hazelcast.org/docs/latest/manual/html-single/#exactly-once-at-least-once-or-at-most-once-execution).
I would then close this issue, either with additional logging or as a known issue.

**Comment by vbekiaris** [comment]
🤦‍♂  failed to see that. Closing then as a known issue
