### ISSUE TITLE
Current thread is not owner of the lock!

### ISSUE THREAD

**Issue by Diarsid** [hazelcast/hazelcast#15927]
We are constantly seeing this exception in our production environment.

We have 3 nodes and we are using a lot of locking operations:
```
imap.lock("lockName");
locksObserver.onLocked("lockName");
try {
     // logic
} finally {
     imap.unlock("lockName");
     locksObserver.onUnlocked("lockName");
}
```

Sometimes cluster breaks due to other unknown issue with time leaps that I've filed earlier:
https://github.com/hazelcast/hazelcast/issues/15546

In a minute or two cluster reunites, and then we see a lot of  such exceptions. The worst thing that sometimes these exceptions are thrown on imap.unlock() and it causes a distributed deadlock - lock is locked, all members are present, but .unlock() was unsuccessful so it remains locked forever. 

Here is simplified log of the problem depicted in two nodes.
DistributedLocksObserver in further logs is a simple component that silently intercepts all lock/unlock invocations and writes them into ITopic in order to every node can listen and log all lock/unlock operations on every other node.

NODE_1
```
2019-11-01 16:52:51 INFO  NODE_1 DistributedLocksObserver:25 - 2019-11-01T16:52:51.940 : UNLOCK : %SOME_LOCK_NAME%
2019-11-01 16:52:51 INFO  NODE_1 TcpIpConnector:65 - [1.1.1.101]:25701 [NODES_GROUP] [3.11.2] Connecting to /1.1.1.91:25701, timeout: 0, bind-any: true
2019-11-01 16:52:51 INFO  NODE_1 DistributedLocksObserver:25 - 2019-11-01T16:52:51.944 : LOCK : %SOME_LOCK_NAME%
2019-11-01 16:52:51 INFO  NODE_1 DistributedLocksObserver:25 - 2019-11-01T16:52:51.946 : UNLOCK : %SOME_LOCK_NAME%
2019-11-01 16:52:51 INFO  NODE_1 TcpIpConnection:65 - [1.1.1.101]:25701 [NODES_GROUP] [3.11.2] Initialized new cluster connection between /1.1.1.101:35606 and /1.1.1.91:25701
2019-11-01 16:52:52 INFO  NODE_1 DistributedLocksObserver:25 - 2019-11-01T16:52:52.260 : LOCK : %SOME_LOCK_NAME%
```
As it can be seen, some operation have acquired %SOME_LOCK_NAME% at .944 ms and then released it at .946
Than some other operation have acquired the same lock at .52.260 and it is not released anymore

NODE_2
```
2019-11-01 16:52:45 INFO  NODE_2 TcpIpConnector:65 - [1.1.1.91]:25701 [NODES_GROUP] [3.11.2] Connecting to /1.1.1.215:25701, timeout: 0, bind-any: true
2019-11-01 16:52:45 INFO  NODE_2 TcpIpConnection:65 - [1.1.1.91]:25701 [NODES_GROUP] [3.11.2] Initialized new cluster connection between /1.1.1.91:48367 and /1.1.1.215:25701
2019-11-01 16:52:51 INFO  NODE_2 TcpIpConnection:65 - [1.1.1.91]:25701 [NODES_GROUP] [3.11.2] Initialized new cluster connection between /1.1.1.91:25701 and /1.1.1.101:35606
2019-11-01 16:52:51 INFO  NODE_2 ClusterService:65 - [1.1.1.91]:25701 [NODES_GROUP] [3.11.2]

Members {size:3, ver:39} [
        Member [1.1.1.215]:25701 - 8d103b01-5bef-470b-b7a9-81daba15a58b
        Member [1.1.1.101]:25701 - a8dd2137-38e5-4ee2-8de6-a70eaed82c21
        Member [1.1.1.91]:25701 - 78350eee-3058-4aa5-a389-5137d1e32eb5 this
]

2019-11-01 16:52:52 INFO  NODE_2 DistributedLocksObserver:25 - 2019-11-01T16:52:52.260 : LOCK : %SOME_LOCK_NAME%
2019-11-01 16:52:52 ERROR NODE_2 EventServiceImpl:69 - [1.1.1.91]:25701 [NODES_GROUP] [3.11.2] hz._hzInstance_1_NODES_GROUP.event-4 caught an exception while processing task:com.hazelcast.spi.impl.eventservice.impl.LocalEventDispatcher@178bf18a
java.lang.IllegalMonitorStateException: Current thread is not owner of the lock! -> Owner: 7a8f7235-b849-4c2e-af65-8e19432af6fb, thread ID: 47
        at com.hazelcast.concurrent.lock.operations.UnlockOperation.unlock(UnlockOperation.java:75)
        at com.hazelcast.concurrent.lock.operations.UnlockOperation.run(UnlockOperation.java:64)
        at com.hazelcast.spi.Operation.call(Operation.java:170)
        at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:208)
        at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:197)
        at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:413)
        at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:153)
        at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:123)
        at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:110)
        at ------ submitted from ------.(Unknown Source)
        at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:127)
        at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:79)
        at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:162)
        at com.hazelcast.spi.impl.AbstractInvocationFuture.join(AbstractInvocationFuture.java:143)
        at com.hazelcast.concurrent.lock.LockProxySupport.unlock(LockProxySupport.java:151)
        at com.hazelcast.map.impl.proxy.MapProxyImpl.unlock(MapProxyImpl.java:332)

        at ...... // our application code invoking IMap.unlock(%SOME_LOCK_NAME%);

        at com.hazelcast.internal.cluster.impl.ClusterServiceImpl.dispatchEvent(ClusterServiceImpl.java:809)
        at com.hazelcast.internal.cluster.impl.ClusterServiceImpl.dispatchEvent(ClusterServiceImpl.java:85)
        at com.hazelcast.spi.impl.eventservice.impl.LocalEventDispatcher.run(LocalEventDispatcher.java:64)
        at com.hazelcast.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:226)
        at com.hazelcast.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:209)
```
Here we also see logged lock operation at .52.260 and unlock attempt that fails.
After that lock %SOME_LOCK_NAME% remains locked and no one can access it anymore.

**Comment by mmedenjak** [comment]
Hi @Diarsid !

Thank you for a detailed report. I too have a hunch that the issue has something to do with cluster split and split-brain healing. 

One thing that comes to mind is that the lock information is kept on as many backups as there are map backups. By default, it's one synchronous backup count and one asynchronous backup count. 
I see your cluster has three members  - let's call them A, B and C. If the lock backup count is 1, the lock information might be kept on A and B. Member C might be the one holding the lock. The cluster might then split into two sub-clusters - [A,B] and [C]. Partitions on member C will be promoted because most hazelcast structures favour availability. If member C tries to unlock the lock, it will then look for the lock information on itself (since it cannot reach A and B and its' partitions were promoted). This causes the operation to fail as it fails to find the lock information. Once the cluster heals, the member C might successfully send an operation to members A and B to unlock the lock.

The case can be even worse - if the lock information is kept in its' entirety on the smaller sub-cluster, it will be discarded during split-brain healing. For instance, if you had more members (A,B,C,D,E), the lock information was kept on D and E and the cluster then split into [A,B,C] and [D,E], during split-brain healing the lock information from D and E would be dropped, causing any locks to be unlocked and unlock operations to fail (like yours one did). Not saying this is the case, though. 

I'm putting this issue in our next release so we at least verify the behaviour. For now, here are some pointers:
• during Hazelcast 3.10, we were implementing sensible split-brain healing policies for most data structures. We left our lock on purpose since there was always an use case where it didn't behave properly. Distributed locks are supposed to be done in a better way which is what we ultimatively did.
• we then implemented the [CP subsystem](https://docs.hazelcast.org/docs/latest/manual/html-single/index.html#cp-subsystem), specifically the FencedLock. It addresses the issues you might encounter with the old lock which favoured availability by choosing to be unresponsive if enough members are unreachable. For use-cases needing safety, I strongly suggest you move to this lock.
• if you don't need strong guarantees but would like to work around this issue that you have, you can try using `IMap#forceUnlock`. It will unlock any lock without consulting the lock information.
• we also introduced logging for lock/unlock operations in Hazelcast 3.10. By increasing the log level for `com.hazelcast.internal.locksupport` to `FINEST`, you might be able to collect more information about the state of the locks and which member is currently handling the lock/unlock operations.
