### ISSUE TITLE
CacheResourceTest.testCloseableCacheListener

### ISSUE THREAD

**Issue by ihsandemir** [hazelcast/hazelcast#15935]
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/4141/testReport/junit/com.hazelcast.cache/CacheResourceTest/testCloseableCacheListener/

```
Error Message
CloseableListener.close() should be called when cache is closed!
Stacktrace
java.lang.AssertionError: CloseableListener.close() should be called when cache is closed!
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.cache.CacheResourceTest.testCloseableCacheListener(CacheResourceTest.java:217)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by petrpleshachkov** [comment]
The failure happened when running tests for https://github.com/hazelcast/hazelcast/pull/15860 which makes the events registration asynchronous so that it directly relates to this failure. The buggy code is not in the master and will be fixed in the scope of the PR and carefully reviewed.

**Comment by ihsandemir** [comment]
Closing the issue since it seems to be related to my PR changes.
