### ISSUE TITLE
Exception encountered by TimedMemberStateFactory stops MC service

### ISSUE THREAD

**Issue by blazember** [hazelcast/hazelcast#15946]
`ManagementCenterService` shuts down itself if it encounters an exception when creating the `TimedMemberState`. This issue makes the cluster to disappear from MC. The related code is here: https://github.com/hazelcast/hazelcast/blob/91ae6c327b9c2e8f73e95a1ffadfeba090267272/hazelcast/src/main/java/com/hazelcast/internal/management/ManagementCenterService.java#L447-L460

This happens even if the exception is a retryable one such as in this case:
```
[127.0.0.1]:5702 [A] [4.0-SNAPSHOT] Hazelcast Management Center Service will be shutdown due to exception.
com.hazelcast.spi.exception.RetryableHazelcastException: HazelcastInstance[[127.0.0.1]:5702] is not active!
    at com.hazelcast.spi.impl.NodeEngineImpl.getService(NodeEngineImpl.java:385) ~[hazelcast-4.0-SNAPSHOT.jar:4.0-SNAPSHOT]
    at com.hazelcast.internal.management.TimedMemberStateFactory.getCacheService(TimedMemberStateFactory.java:422) ~[hazelcast-4.0-SNAPSHOT.jar:4.0-SNAPSHOT]
    at com.hazelcast.internal.management.TimedMemberStateFactory.createMemState(TimedMemberStateFactory.java:278) ~[hazelcast-4.0-SNAPSHOT.jar:4.0-SNAPSHOT]
    at com.hazelcast.internal.management.TimedMemberStateFactory.createMemberState(TimedMemberStateFactory.java:200) ~[hazelcast-4.0-SNAPSHOT.jar:4.0-SNAPSHOT]
    at com.hazelcast.internal.management.TimedMemberStateFactory.createTimedMemberState(TimedMemberStateFactory.java:126) ~[hazelcast-4.0-SNAPSHOT.jar:4.0-SNAPSHOT]
    at com.hazelcast.internal.management.ManagementCenterService$PrepareStateThread.run(ManagementCenterService.java:450) [hazelcast-4.0-SNAPSHOT.jar:4.0-SNAPSHOT]
```

Related closed issue #15656

**Comment by blazember** [comment]
cc @emre-aydin @puzpuzpuz

**Comment by puzpuzpuz** [comment]
@emre-aydin @blazember should we close this issue now, as #15980 was merged?

**Comment by emre-aydin** [comment]
> @emre-aydin @blazember should we close this issue now, as #15980 was merged?

Yes we should.
