### ISSUE TITLE
EvictionTest.testTTL_prolongationAfterNonTTLUpdate

### ISSUE THREAD

**Issue by tezc** [hazelcast/hazelcast#15974]
master (commit 94d3d2c713ed0f6c49a2922330cb21e3785be449)

http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK8-fips-nightly/95/testReport/com.hazelcast.map/EvictionTest/testTTL_prolongationAfterNonTTLUpdate/

**Stacktrace**

```
java.lang.AssertionError: expected:<10.0> but was:<9.2233703E15>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:575)
	at org.junit.Assert.assertEquals(Assert.java:700)
	at com.hazelcast.map.EvictionTest.sleepAndAssertTtlExpirationCorrectness(EvictionTest.java:336)
	at com.hazelcast.map.EvictionTest.testTTL_prolongationAfterNonTTLUpdate(EvictionTest.java:276)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.lang.Thread.run(Thread.java:811)
```

**Comment by petrpleshachkov** [comment]
A duplicate issue https://github.com/hazelcast/hazelcast-enterprise/issues/2422
Was fixed here https://github.com/hazelcast/hazelcast/pull/15959. This PR was merged after this issue was created. 
@tezc, if you are ok I will close this issue?
