### ISSUE TITLE
DynamicConfigBouncingTest & DynamicConfigSlowPreJoinBouncingTest failure

### ISSUE THREAD

**Issue by tezc** [hazelcast/hazelcast#16035]
_master_ (commit f39e27fe5179d4de9112b707d5516c3fa1e56758)

http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK8-fips-nightly/97/testReport/junit/com.hazelcast.internal.dynamicconfig/DynamicConfigSlowPreJoinBouncingTest/doNotThrowExceptionWhenMemberIsGone/

http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK8-fips-nightly/97/testReport/junit/com.hazelcast.internal.dynamicconfig/DynamicConfigBouncingTest/doNotThrowExceptionWhenMemberIsGone/

**Stacktrace**
```
com.hazelcast.config.InvalidConfigurationException: Cannot add a dynamic configuration 'MapConfig{name='574f9b6b-e182-42bf-91ed-f3ab6a6f1df9', inMemoryFormat=OBJECT', metadataPolicy=CREATE_ON_UPDATE, backupCount=3, asyncBackupCount=0, timeToLiveSeconds=12, maxIdleSeconds=20, readBackupData=true, evictionConfig=EvictionConfig{size=1000, maxSizePolicy=FREE_HEAP_SIZE, evictionPolicy=LRU, comparatorClassName=null, comparator=LRUEvictionPolicyComparator{com.hazelcast.internal.eviction.impl.comparator.LRUEvictionPolicyComparator@495c62a3} }, merkleTree=MerkleTreeConfig{enabled=false, depth=10}, eventJournal=EventJournalConfig{enabled=false, capacity=10000, timeToLiveSeconds=0}, hotRestart=HotRestartConfig{enabled=true, fsync=true}, nearCacheConfig=NearCacheConfig{name=default, inMemoryFormat=NATIVE, invalidateOnChange=true, timeToLiveSeconds=0, maxIdleSeconds=0, evictionConfig=EvictionConfig{size=10000, maxSizePolicy=ENTRY_COUNT, evictionPolicy=LRU, comparatorClassName=null, comparator=null}, cacheLocalEntries=true, localUpdatePolicy=CACHE_ON_UPDATE, preloaderConfig=NearCachePreloaderConfig{enabled=true, directory=, storeInitialDelaySeconds=600, storeIntervalSeconds=600}}, mapStoreConfig=MapStoreConfig{enabled=true, className='foo.bar.MapStoreDoesNotExist', factoryClassName='null', writeDelaySeconds=0, writeBatchSize=1, implementation=null, factoryImplementation=null, properties={}, initialLoadMode=LAZY, writeCoalescing=true}, mergePolicyConfig=MergePolicyConfig{policy='com.hazelcast.spi.merge.PutIfAbsentMergePolicy', batchSize=100}, wanReplicationRef=WanReplicationRef{name='name', mergePolicy='foo.bar.PolicyClass', filters='[]', republishingEnabled='true'}, entryListenerConfigs=[EntryListenerConfig{local=true, includeValue=true}, EntryListenerConfig{local=true, includeValue=true}, EntryListenerConfig{local=true, includeValue=true}], indexConfigs=[IndexConfig{name=null, type=SORTED, attributes=[orderAttribute]}, IndexConfig{name=null, type=HASH, attributes=[unorderedAttribute]}], attributeConfigs=[AttributeConfig{name='attribute'extractorClassName='foo.bar.ExtractorClass'}], splitBrainProtectionName=split-brain-protection, queryCacheConfigs=[QueryCacheConfig{batchSize=100, bufferSize=16, delaySeconds=0, includeValue=true, populate=true, coalesce=false, inMemoryFormat=OBJECT, name='queryCacheName', predicateConfig=PredicateConfig{className='null', sql='null', implementation=null}, evictionConfig=EvictionConfig{size=10000, maxSizePolicy=ENTRY_COUNT, evictionPolicy=LRU, comparatorClassName=null, comparator=null}, entryListenerConfigs=[EntryListenerConfig{local=false, includeValue=true}], indexConfigs=[IndexConfig{name=null, type=HASH, attributes=[attribute]}]}], cacheDeserializedValues=ALWAYS}' as there is already a conflicting configuration 'MapConfig{name='574f9b6b-e182-42bf-91ed-f3ab6a6f1df9', inMemoryFormat=OBJECT', metadataPolicy=CREATE_ON_UPDATE, backupCount=3, asyncBackupCount=0, timeToLiveSeconds=12, maxIdleSeconds=20, readBackupData=true, evictionConfig=EvictionConfig{size=1000, maxSizePolicy=FREE_HEAP_SIZE, evictionPolicy=LRU, comparatorClassName=null, comparator=LRUEvictionPolicyComparator{com.hazelcast.internal.eviction.impl.comparator.LRUEvictionPolicyComparator@2abd3aee} }, merkleTree=MerkleTreeConfig{enabled=false, depth=10}, eventJournal=EventJournalConfig{enabled=false, capacity=10000, timeToLiveSeconds=0}, hotRestart=HotRestartConfig{enabled=true, fsync=true}, nearCacheConfig=NearCacheConfig{name=default, inMemoryFormat=NATIVE, invalidateOnChange=true, timeToLiveSeconds=0, maxIdleSeconds=0, evictionConfig=EvictionConfig{size=10000, maxSizePolicy=ENTRY_COUNT, evictionPolicy=LRU, comparatorClassName=null, comparator=null}, cacheLocalEntries=true, localUpdatePolicy=CACHE_ON_UPDATE, preloaderConfig=NearCachePreloaderConfig{enabled=true, directory=, storeInitialDelaySeconds=600, storeIntervalSeconds=600}}, mapStoreConfig=MapStoreConfig{enabled=true, className='foo.bar.MapStoreDoesNotExist', factoryClassName='null', writeDelaySeconds=0, writeBatchSize=1, implementation=null, factoryImplementation=null, properties={}, initialLoadMode=LAZY, writeCoalescing=true}, mergePolicyConfig=MergePolicyConfig{policy='com.hazelcast.spi.merge.PutIfAbsentMergePolicy', batchSize=100}, wanReplicationRef=WanReplicationRef{name='name', mergePolicy='foo.bar.PolicyClass', filters='[]', republishingEnabled='true'}, entryListenerConfigs=[EntryListenerConfig{local=true, includeValue=true}, EntryListenerConfig{local=true, includeValue=true}, EntryListenerConfig{local=true, includeValue=true}], indexConfigs=[IndexConfig{name=null, type=SORTED, attributes=[orderAttribute]}, IndexConfig{name=null, type=HASH, attributes=[unorderedAttribute]}], attributeConfigs=[AttributeConfig{name='attribute'extractorClassName='foo.bar.ExtractorClass'}], splitBrainProtectionName=split-brain-protection, queryCacheConfigs=[QueryCacheConfig{batchSize=100, bufferSize=16, delaySeconds=0, includeValue=true, populate=true, coalesce=false, inMemoryFormat=OBJECT, name='queryCacheName', predicateConfig=PredicateConfig{className='null', sql='null', implementation=null}, evictionConfig=EvictionConfig{size=10000, maxSizePolicy=ENTRY_COUNT, evictionPolicy=LRU, comparatorClassName=null, comparator=null}, entryListenerConfigs=[EntryListenerConfig{local=false, includeValue=true}], indexConfigs=[IndexConfig{name=null, type=HASH, attributes=[attribute]}]}], cacheDeserializedValues=ALWAYS}'
	at com.hazelcast.internal.dynamicconfig.ClusterWideConfigurationService.checkCurrentConfigNullOrEqual(ClusterWideConfigurationService.java:325)
	at com.hazelcast.internal.dynamicconfig.ClusterWideConfigurationService.registerConfigLocally(ClusterWideConfigurationService.java:309)
	at com.hazelcast.internal.dynamicconfig.AddDynamicConfigOperation.run(AddDynamicConfigOperation.java:48)
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:184)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:218)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:207)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:431)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:154)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:124)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:111)
```

**Comment by ahmetmircik** [comment]
Test was broken in PR: https://github.com/hazelcast/hazelcast/pull/15939
