### ISSUE TITLE
WanRESTTest.syncSuccess failure

### ISSUE THREAD

**Issue by blazember** [hazelcast/hazelcast#16053]
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/4480/

**Error Message**
```
expected:<[success]> but was:<[fail]>
```
**Stacktrace**
```
org.junit.ComparisonFailure: expected:<[success]> but was:<[fail]>
	at com.hazelcast.wan.WanRESTTest.assertSuccess(WanRESTTest.java:199)
	at com.hazelcast.wan.WanRESTTest.syncSuccess(WanRESTTest.java:104)
```
**Hiccups**
```
Hiccups measured while running test 'syncSuccess(com.hazelcast.wan.WanRESTTest):'
21:01:10, accumulated pauses: 346 ms, max pause: 328 ms, pauses over 1000 ms: 0
```

There is also an NPE in the log, which is probably the cause of the failure:
```
21:01:11,642  WARN |syncSuccess| - [HttpPostCommandProcessor] hz.eager_bartik.cached.thread-2 - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] Error occurred while syncing map
java.lang.NullPointerException
	at com.hazelcast.internal.ascii.rest.HttpPostCommandProcessor.handleWanSyncMap(HttpPostCommandProcessor.java:414) [classes/:?]
	at com.hazelcast.internal.ascii.rest.HttpPostCommandProcessor.handle(HttpPostCommandProcessor.java:100) [classes/:?]
	at com.hazelcast.internal.ascii.rest.HttpPostCommandProcessor.handle(HttpPostCommandProcessor.java:55) [classes/:?]
	at com.hazelcast.internal.ascii.TextCommandServiceImpl$CommandExecutor.run(TextCommandServiceImpl.java:396) [classes/:?]
	at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217) [classes/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64) [classes/:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80) [classes/:?]
```

**Comment by mmedenjak** [comment]
The wiremock service stub is set up so that it returns an UUID for some parameters. For other parameters it will return `null` which causes the NPE above. Now, the question is why the service mock object wasn't set up.

**Comment by mmedenjak** [comment]
The issue can occur if, during stubbing, another method on the same mock instance was called. For instance, during this stubbing:
```
when(wanServiceMock.syncMap("atob", "B", "mapName"))
                .thenReturn(expectedUuid);
```
If we invoke `wanServiceMock.toString()` after the invocation to `when` but before the invocation to `thenReturn` (e.g. by putting a breakpoint and calling that method), the stubbing will continue not for the method passed as an argument in the `when` method but for the `toString()` method. Of course, `toString` cannot return `UUID` so we get the error mentioned [here](https://github.com/hazelcast/hazelcast-enterprise/issues/3364).

I assume then that somehow, during this test execution, the stub was set up for some other method (which must return `UUID`, otherwise we would have gotten the exception from the other issue) and not for `syncMap`.

Invoking then `syncMap` will have simply returned `null`, causing the NPE and the test failure.
