### ISSUE TITLE
Test failure ClientRegressionWithMockNetworkTest

### ISSUE THREAD

**Issue by petrpleshachkov** [hazelcast/hazelcast#16063]
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/4503/testReport/junit/com.hazelcast.client/ClientRegressionWithMockNetworkTest/testOperationRedo_smartRoutingDisabled/

```
java.util.NoSuchElementException
	at java.util.concurrent.ConcurrentHashMap$ValueIterator.next(ConcurrentHashMap.java:3436)
	at com.hazelcast.client.impl.spi.impl.NonSmartClientInvocationService.getConnection(NonSmartClientInvocationService.java:54)
	at com.hazelcast.client.impl.spi.impl.NonSmartClientInvocationService.invokeOnPartitionOwner(NonSmartClientInvocationService.java:45)
	at com.hazelcast.client.impl.spi.impl.ClientInvocation.invokeOnSelection(ClientInvocation.java:165)
	at com.hazelcast.client.impl.spi.impl.ClientInvocation.retry(ClientInvocation.java:193)
	at com.hazelcast.client.impl.spi.impl.ClientInvocation.run(ClientInvocation.java:178)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)

```

**Comment by sancar** [comment]
fixed by https://github.com/hazelcast/hazelcast/pull/16036
