### ISSUE TITLE
QueryCacheMemoryLeakTest.stress_user_listener_removal_upon_query_cache_destroy

### ISSUE THREAD

**Issue by tezc** [hazelcast/hazelcast#16079]
_master_ (commit ec78a3d6a93689c2192a619bfb5c3f19ec3bc871)

Failed on Windows : http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-Windows-OracleJDK8/108/testReport/com.hazelcast.map.impl.querycache/QueryCacheMemoryLeakTest/stress_user_listener_removal_upon_query_cache_destroy/

**Stacktrace**
```
java.lang.AssertionError: {bcde1890-6232-4bd9-81a3-10cd5e0a5f69=[], 610d747b-10e2-4524-a996-8ab189380a8f=[], mapD=[]}
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.map.impl.querycache.QueryCacheMemoryLeakTest.assertNoUserListenerLeft(QueryCacheMemoryLeakTest.java:352)
	at com.hazelcast.map.impl.querycache.QueryCacheMemoryLeakTest.stress_user_listener_removal_upon_query_cache_destroy(QueryCacheMemoryLeakTest.java:170)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

```
BuildInfo right after stress_user_listener_removal_upon_query_cache_destroy(com.hazelcast.map.impl.querycache.QueryCacheMemoryLeakTest): BuildInfo{version='4.0-SNAPSHOT', build='20191122', buildNumber=20191122, revision=ec78a3d, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'stress_user_listener_removal_upon_query_cache_destroy(com.hazelcast.map.impl.querycache.QueryCacheMemoryLeakTest):'
04:24:10, accumulated pauses: 809 ms, max pause: 47 ms, pauses over 1000 ms: 0
04:24:15, accumulated pauses: 773 ms, max pause: 21 ms, pauses over 1000 ms: 0
04:24:20, accumulated pauses: 724 ms, max pause: 2 ms, pauses over 1000 ms: 0
04:24:25, accumulated pauses: 725 ms, max pause: 2 ms, pauses over 1000 ms: 0
04:24:30, accumulated pauses: 734 ms, max pause: 2 ms, pauses over 1000 ms: 0
04:24:35, accumulated pauses: 719 ms, max pause: 2 ms, pauses over 1000 ms: 0
04:24:40, accumulated pauses: 727 ms, max pause: 2 ms, pauses over 1000 ms: 0
04:24:45, accumulated pauses: 735 ms, max pause: 2 ms, pauses over 1000 ms: 0
04:24:50, accumulated pauses: 732 ms, max pause: 2 ms, pauses over 1000 ms: 0
04:24:55, accumulated pauses: 723 ms, max pause: 2 ms, pauses over 1000 ms: 0
04:25:00, accumulated pauses: 737 ms, max pause: 14 ms, pauses over 1000 ms: 0
04:25:05, accumulated pauses: 718 ms, max pause: 2 ms, pauses over 1000 ms: 0
04:25:10, accumulated pauses: 731 ms, max pause: 2 ms, pauses over 1000 ms: 0
04:25:15, accumulated pauses: 726 ms, max pause: 2 ms, pauses over 1000 ms: 0
04:25:20, accumulated pauses: 726 ms, max pause: 2 ms, pauses over 1000 ms: 0
04:25:25, accumulated pauses: 729 ms, max pause: 2 ms, pauses over 1000 ms: 0
04:25:30, accumulated pauses: 740 ms, max pause: 3 ms, pauses over 1000 ms: 0
04:25:35, accumulated pauses: 724 ms, max pause: 2 ms, pauses over 1000 ms: 0
04:25:40, accumulated pauses: 729 ms, max pause: 2 ms, pauses over 1000 ms: 0
04:25:45, accumulated pauses: 725 ms, max pause: 2 ms, pauses over 1000 ms: 0
04:25:50, accumulated pauses: 735 ms, max pause: 2 ms, pauses over 1000 ms: 0
04:25:55, accumulated pauses: 732 ms, max pause: 2 ms, pauses over 1000 ms: 0
04:26:00, accumulated pauses: 733 ms, max pause: 2 ms, pauses over 1000 ms: 0
04:26:05, accumulated pauses: 737 ms, max pause: 2 ms, pauses over 1000 ms: 0
04:26:10, accumulated pauses: 758 ms, max pause: 250 ms, pauses over 1000 ms: 0
```

**Comment by tezc** [comment]
http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-Windows-OracleJDK8/112/testReport/com.hazelcast.map.impl.querycache/QueryCacheMemoryLeakTest/stress_user_listener_removal_upon_query_cache_destroy/

**Comment by mdogan** [comment]
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/4914/testReport/junit/com.hazelcast.map.impl.querycache/QueryCacheMemoryLeakTest/stress_user_listener_removal_upon_query_cache_destroy/

```
java.lang.AssertionError: {64ff6266-df1f-499b-a862-86aee24ab9e0=[], c36eca11-a3c1-48ad-bd46-c2f0218cf50b=[], 7c845afe-6ed1-4f47-9188-f17263c492a4=[], 56b2fcc2-157b-4dc4-8680-ddf4f7b4e77c=[]}
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.map.impl.querycache.QueryCacheMemoryLeakTest.assertNoUserListenerLeft(QueryCacheMemoryLeakTest.java:352)
	at com.hazelcast.map.impl.querycache.QueryCacheMemoryLeakTest.stress_user_listener_removal_upon_query_cache_destroy(QueryCacheMemoryLeakTest.java:170)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

There are lots of slow operation logs:
```
12:50:38,435  WARN |stress_user_listener_removal_upon_query_cache_destroy| - [SlowOperationDetector] hz.stoic_mirzakhani.SlowOperationDetectorThread - [127.0.0.1]:5703 [dev] [4.0-SNAPSHOT] Slow operation detected: com.hazelcast.map.impl.querycache.subscriber.operation.DestroyQueryCacheOperation
Hint: You can enable the logging of stacktraces with the following system property: -Dhazelcast.slow.operation.detector.stacktrace.logging.enabled
12:50:38,436  WARN |stress_user_listener_removal_upon_query_cache_destroy| - [SlowOperationDetector] hz.stoic_mirzakhani.SlowOperationDetectorThread - [127.0.0.1]:5703 [dev] [4.0-SNAPSHOT] Slow operation detected: com.hazelcast.map.impl.querycache.subscriber.operation.DestroyQueryCacheOperation (2 invocations)
12:50:38,437  WARN |stress_user_listener_removal_upon_query_cache_destroy| - [SlowOperationDetector] hz.stoic_mirzakhani.SlowOperationDetectorThread - [127.0.0.1]:5703 [dev] [4.0-SNAPSHOT] Slow operation detected: com.hazelcast.map.impl.querycache.subscriber.operation.DestroyQueryCacheOperation (3 invocations)
12:50:38,438  WARN |stress_user_listener_removal_upon_query_cache_destroy| - [SlowOperationDetector] hz.stoic_mirzakhani.SlowOperationDetectorThread - [127.0.0.1]:5703 [dev] [4.0-SNAPSHOT] Slow operation detected: com.hazelcast.map.impl.querycache.subscriber.operation.DestroyQueryCacheOperation (4 invocations)
12:50:38,804  WARN |stress_user_listener_removal_upon_query_cache_destroy| - [SlowOperationDetector] hz.gallant_mirzakhani.SlowOperationDetectorThread - [127.0.0.1]:5702 [dev] [4.0-SNAPSHOT] Slow operation detected: com.hazelcast.map.impl.querycache.subscriber.operation.DestroyQueryCacheOperation
```

```
12:50:20, accumulated pauses: 532 ms, max pause: 99 ms, pauses over 1000 ms: 0
12:50:25, accumulated pauses: 702 ms, max pause: 197 ms, pauses over 1000 ms: 0
12:50:30, accumulated pauses: 317 ms, max pause: 19 ms, pauses over 1000 ms: 0
12:50:35, accumulated pauses: 564 ms, max pause: 46 ms, pauses over 1000 ms: 0
12:50:40, accumulated pauses: 417 ms, max pause: 10 ms, pauses over 1000 ms: 0
12:50:45, accumulated pauses: 316 ms, max pause: 24 ms, pauses over 1000 ms: 0
12:50:50, accumulated pauses: 317 ms, max pause: 26 ms, pauses over 1000 ms: 0
12:50:55, accumulated pauses: 402 ms, max pause: 10 ms, pauses over 1000 ms: 0
12:51:00, accumulated pauses: 357 ms, max pause: 13 ms, pauses over 1000 ms: 0
12:51:05, accumulated pauses: 344 ms, max pause: 12 ms, pauses over 1000 ms: 0
12:51:10, accumulated pauses: 78 ms, max pause: 8 ms, pauses over 1000 ms: 0
12:51:15, accumulated pauses: 238 ms, max pause: 20 ms, pauses over 1000 ms: 0
12:51:20, accumulated pauses: 174 ms, max pause: 14 ms, pauses over 1000 ms: 0
12:51:25, accumulated pauses: 132 ms, max pause: 12 ms, pauses over 1000 ms: 0
12:51:30, accumulated pauses: 73 ms, max pause: 9 ms, pauses over 1000 ms: 0
12:51:35, accumulated pauses: 65 ms, max pause: 10 ms, pauses over 1000 ms: 0
12:51:40, accumulated pauses: 72 ms, max pause: 8 ms, pauses over 1000 ms: 0
12:51:45, accumulated pauses: 33 ms, max pause: 0 ms, pauses over 1000 ms: 0
12:51:50, accumulated pauses: 124 ms, max pause: 5 ms, pauses over 1000 ms: 0
12:51:55, accumulated pauses: 467 ms, max pause: 13 ms, pauses over 1000 ms: 0
12:52:00, accumulated pauses: 31 ms, max pause: 0 ms, pauses over 1000 ms: 0
12:52:05, accumulated pauses: 30 ms, max pause: 0 ms, pauses over 1000 ms: 0
12:52:10, accumulated pauses: 30 ms, max pause: 1 ms, pauses over 1000 ms: 0
12:52:15, accumulated pauses: 41 ms, max pause: 1 ms, pauses over 1000 ms: 0
12:52:20, accumulated pauses: 67 ms, max pause: 34 ms, pauses over 1000 ms: 0
12:52:25, accumulated pauses: 91 ms, max pause: 71 ms, pauses over 1000 ms: 0
```

**Comment by ahmetmircik** [comment]
another failure:
https://github.com/hazelcast/hazelcast/issues/16214#issue-535516560

**Comment by petrpleshachkov** [comment]
I've managed to reproduce the issue locally. 

```
java.lang.AssertionError: {8c57d432-cc9a-4ff6-9c40-0f6a58ec61f9=[], 59ce181c-e87d-4a06-963d-39e3dfaa90c9=[], 2f42f512-d549-4c59-8d76-424b48979e22=[], bf936eac-9a3c-426e-94e2-5cd5c4316847=[]}

	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.map.impl.querycache.QueryCacheMemoryLeakTest.assertNoUserListenerLeft(QueryCacheMemoryLeakTest.java:354)
	at com.hazelcast.map.impl.querycache.QueryCacheMemoryLeakTest.stress_user_listener_removal_upon_query_cache_destroy(QueryCacheMemoryLeakTest.java:172)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)

```
