### ISSUE TITLE
Test failure ClientSessionManagerTest.sessionHeartbeatsAreSent_whenSessionInUse

### ISSUE THREAD

**Issue by vbekiaris** [hazelcast/hazelcast#16077]
Failed in http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/4574

```
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.cp.internal.session.AbstractProxySessionManagerTest.lambda$sessionHeartbeatsAreSent_whenSessionInUse$4(AbstractProxySessionManagerTest.java:139)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueAllTheTime(HazelcastTestSupport.java:1284)
	at com.hazelcast.cp.internal.session.AbstractProxySessionManagerTest.sessionHeartbeatsAreSent_whenSessionInUse(AbstractProxySessionManagerTest.java:139)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

```
Hiccups measured while running test 'sessionHeartbeatsAreSent_whenSessionInUse(com.hazelcast.client.cp.internal.session.ClientSessionManagerTest):'
12:50:20, accumulated pauses: 2345 ms, max pause: 981 ms, pauses over 1000 ms: 0
12:50:25, accumulated pauses: 4774 ms, max pause: 2032 ms, pauses over 1000 ms: 1
12:50:30, accumulated pauses: 2312 ms, max pause: 1064 ms, pauses over 1000 ms: 2
12:50:35, accumulated pauses: 8526 ms, max pause: 4522 ms, pauses over 1000 ms: 3
12:50:40, accumulated pauses: 3377 ms, max pause: 3343 ms, pauses over 1000 ms: 1
12:50:45, accumulated pauses: 1908 ms, max pause: 1869 ms, pauses over 1000 ms: 1
12:50:50, accumulated pauses: 4191 ms, max pause: 3368 ms, pauses over 1000 ms: 1
12:50:55, accumulated pauses: 2228 ms, max pause: 2160 ms, pauses over 1000 ms: 1
12:51:00, accumulated pauses: 4383 ms, max pause: 3026 ms, pauses over 1000 ms: 2
12:51:05, accumulated pauses: 3557 ms, max pause: 1071 ms, pauses over 1000 ms: 2
12:51:10, accumulated pauses: 1464 ms, max pause: 673 ms, pauses over 1000 ms: 0
```

probably similar to #15735 ?

**Comment by mdogan** [comment]
There are again large pauses. It seems we should make it more resilient to these pauses.
