### ISSUE TITLE
FailoverTest.testFailoverNotSupportedInCommunityVersion

### ISSUE THREAD

**Issue by vbekiaris** [hazelcast/hazelcast#16099]
Failed in http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/4662:

```
java.lang.Exception: Unexpected exception, expected<java.lang.IllegalStateException> but was<java.util.NoSuchElementException>
	at com.hazelcast.client.bluegreen.FailoverTest.testFailoverNotSupportedInCommunityVersion(FailoverTest.java:79)
```

**Comment by tkountis** [comment]
There is no stack-trace anywhere in the build logs (checked S3 too).
I verified that the version of JUnit is actually logging the `Expected` exception (or actual) locally.
The only assumption I have is that it might be related to the latest client changes (ie. https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/client/impl/clientside/ClientDiscoveryService.java#L51) but it also looks correct.

Without a stacktrace its not easy to debug. We can close this, and come back to it if it happens again (hopefully with a stacktrace).

**Comment by sancar** [comment]
It looks related to https://github.com/hazelcast/hazelcast/pull/16036. 
I am closing this given that we don't have the logs.

**Comment by mmedenjak** [comment]
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/4998

```
java.lang.Exception: Unexpected exception, expected<java.lang.IllegalStateException> but was<java.util.NoSuchElementException>
	at com.hazelcast.client.bluegreen.FailoverTest.testFailoverNotSupportedInCommunityVersion(FailoverTest.java:79)
```

**Comment by mdogan** [comment]
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/5010/testReport/junit/com.hazelcast.client.bluegreen/FailoverTest/testFailoverNotSupportedInCommunityVersion/

```
java.lang.Exception: Unexpected exception, expected<java.lang.IllegalStateException> but was<java.util.NoSuchElementException>
	at com.hazelcast.client.bluegreen.FailoverTest.testFailoverNotSupportedInCommunityVersion(FailoverTest.java:79)
```

```
11:57:05,389  WARN |testFailoverNotSupportedInCommunityVersion| - [ClientConnectionManager] hz.client_144.internal-1 - hz.client_144 [dev2] [4.0-SNAPSHOT] Cluster did not answer to failover support query. 
java.util.concurrent.ExecutionException: java.io.IOException: No connection found to cluster.
	at com.hazelcast.client.impl.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:109) ~[classes/:?]
	at com.hazelcast.client.impl.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:39) ~[classes/:?]
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:601) ~[classes/:?]
	at com.hazelcast.client.impl.connection.nio.ClientConnectionManagerImpl.checkFailoverSupport(ClientConnectionManagerImpl.java:869) [classes/:?]
	at com.hazelcast.client.impl.connection.nio.ClientConnectionManagerImpl.connectToCandidate(ClientConnectionManagerImpl.java:398) [classes/:?]
	at com.hazelcast.client.impl.connection.nio.ClientConnectionManagerImpl.connectToClusterSync(ClientConnectionManagerImpl.java:336) [classes/:?]
	at com.hazelcast.client.impl.connection.nio.ClientConnectionManagerImpl.access$100(ClientConnectionManagerImpl.java:114) [classes/:?]
	at com.hazelcast.client.impl.connection.nio.ClientConnectionManagerImpl$1.run(ClientConnectionManagerImpl.java:324) [classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_181]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64) [classes/:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80) [classes/:?]
Caused by: java.io.IOException: No connection found to cluster.
	at com.hazelcast.client.impl.connection.nio.ClientConnectionManagerImpl.checkInvocationAllowed(ClientConnectionManagerImpl.java:434) ~[classes/:?]
	at com.hazelcast.client.impl.spi.impl.AbstractClientInvocationService.checkInvocationAllowed(AbstractClientInvocationService.java:191) ~[classes/:?]
	at com.hazelcast.client.impl.spi.impl.ClientInvocation.invokeOnSelection(ClientInvocation.java:165) ~[classes/:?]
	at com.hazelcast.client.impl.spi.impl.ClientInvocation.invoke(ClientInvocation.java:143) ~[classes/:?]
	at com.hazelcast.client.impl.connection.nio.ClientConnectionManagerImpl.checkFailoverSupport(ClientConnectionManagerImpl.java:867) ~[classes/:?]
	... 13 more
11:57:05,389  WARN |testFailoverNotSupportedInCommunityVersion| - [ClientConnectionManager] testFailoverNotSupportedInCommunityVersion - hz.client_144 [dev2] [4.0-SNAPSHOT] Cluster did not answer to failover support query. 
java.util.concurrent.ExecutionException: java.io.IOException: No connection found to cluster.
	at com.hazelcast.client.impl.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:109) ~[classes/:?]
	at com.hazelcast.client.impl.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:39) ~[classes/:?]
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:601) ~[classes/:?]
	at com.hazelcast.client.impl.connection.nio.ClientConnectionManagerImpl.checkFailoverSupport(ClientConnectionManagerImpl.java:869) [classes/:?]
	at com.hazelcast.client.impl.connection.nio.ClientConnectionManagerImpl.connectToCandidate(ClientConnectionManagerImpl.java:398) [classes/:?]
	at com.hazelcast.client.impl.connection.nio.ClientConnectionManagerImpl.connectToClusterSync(ClientConnectionManagerImpl.java:352) [classes/:?]
	at com.hazelcast.client.impl.connection.nio.ClientConnectionManagerImpl.connectToCluster(ClientConnectionManagerImpl.java:315) [classes/:?]
	at com.hazelcast.client.impl.connection.nio.ClientConnectionManagerImpl.start(ClientConnectionManagerImpl.java:257) [classes/:?]
	at com.hazelcast.client.impl.clientside.HazelcastClientInstanceImpl.start(HazelcastClientInstanceImpl.java:363) [classes/:?]
	at com.hazelcast.client.HazelcastClient.newHazelcastClientInternal(HazelcastClient.java:196) [classes/:?]
	at com.hazelcast.client.HazelcastClient.newHazelcastFailoverClient(HazelcastClient.java:184) [classes/:?]
	at com.hazelcast.client.bluegreen.FailoverTest.testFailoverNotSupportedInCommunityVersion(FailoverTest.java:79) [test-classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.12.jar:4.12]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19) [junit-4.12.jar:4.12]
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114) [test-classes/:?]
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106) [test-classes/:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.io.IOException: No connection found to cluster.
	at com.hazelcast.client.impl.connection.nio.ClientConnectionManagerImpl.checkInvocationAllowed(ClientConnectionManagerImpl.java:434) ~[classes/:?]
	at com.hazelcast.client.impl.spi.impl.AbstractClientInvocationService.checkInvocationAllowed(AbstractClientInvocationService.java:191) ~[classes/:?]
	at com.hazelcast.client.impl.spi.impl.ClientInvocation.invokeOnSelection(ClientInvocation.java:165) ~[classes/:?]
	at com.hazelcast.client.impl.spi.impl.ClientInvocation.invoke(ClientInvocation.java:143) ~[classes/:?]
	at com.hazelcast.client.impl.connection.nio.ClientConnectionManagerImpl.checkFailoverSupport(ClientConnectionManagerImpl.java:867) ~[classes/:?]
	... 21 more
```

**Comment by vojtechtoman** [comment]
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/5018/testReport/junit/com.hazelcast.client.bluegreen/FailoverTest/testFailoverNotSupportedInCommunityVersion/

**Comment by vbekiaris** [comment]
Another failure: http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/5040/

**Comment by tkountis** [comment]
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/5045/

**Comment by ihsandemir** [comment]
Another failure: http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/5102/testReport/com.hazelcast.client.bluegreen/FailoverTest/testFailoverNotSupportedInCommunityVersion/

```
java.lang.Exception: Unexpected exception, expected<java.lang.IllegalStateException> but was<java.util.NoSuchElementException>
	at com.hazelcast.client.bluegreen.FailoverTest.testFailoverNotSupportedInCommunityVersion(FailoverTest.java:79)
```
