### ISSUE TITLE
dynamic configuration

### ISSUE THREAD

**Issue by lishijun121910** [hazelcast/hazelcast#16165]
V3.12
I have one node hazelcast-server, and it's config is like this:

```
map:
   SimpleMap:
        in-memory-format: BINARY
        backup-count: 1
        async-backup-count: 0
        time-to-live-seconds: 10
```
And in my TestUnit, I call this :
```
		IMap<String, Object> cache = hazelcastClientCase.getMap("SimpleMap");
		cache.get("4");

		MapConfig mCfg = new MapConfig("SimpleMap");
		mCfg.setTimeToLiveSeconds(20);

		hazelcastClientCase.getConfig().addMapConfig(mCfg);
```

I expect a exception here because there is a conflict of config, but in fact I get no exception. 

Then I executed code : 
```
		Employee employee = new Employee("4", 29, "IT");
                cache.put(employee.getName(), employee);
		System.out.println("PutValue: " + cache.get("4"));
		
		Thread.sleep(11000);
		
		System.out.println("GetValue: " + cache.get("4"));
```

result:
PutValue: Name: 4 Age: 29 Department: IT
GetValue: null

apparently my dynamic config is not working .

and I try again:
```
		IMap<String, Object> cache = hazelcastClientCase.getMap("SimpleMap");
		cache.get("4");

		MapConfig mCfg = new MapConfig("SimpleMap");
		mCfg.setTimeToLiveSeconds(20);

		hazelcastClientCase.getConfig().addMapConfig(mCfg);
```

the second time I get exception, it looks like my dynamic configuration is done but not working in act:

```
com.hazelcast.config.ConfigurationException: Cannot add a dynamic configuration 'MapConfig{name='SimpleMap',.................., timeToLiveSeconds=20, ................}' as there is already a conflicting configuration 'MapConfig{name='SimpleMap', ...................., timeToLiveSeconds=20, ............}'
	at com.hazelcast.internal.dynamicconfig.ClusterWideConfigurationService.checkCurrentConfigNullOrEqual(ClusterWideConfigurationService.java:410)
	at com.hazelcast.internal.dynamicconfig.ClusterWideConfigurationService.registerConfigLocally(ClusterWideConfigurationService.java:368)
	at com.hazelcast.internal.dynamicconfig.AddDynamicConfigOperation.run(AddDynamicConfigOperation.java:48)
	at com.hazelcast.spi.Operation.call(Operation.java:170)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:210)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:199)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:407)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:434)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:648)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:633)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:592)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:256)
	at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.invokeOnTarget(OperationServiceImpl.java:326)
	at com.hazelcast.internal.util.InvocationUtil$InvokeOnMemberFunction.invokeOnMember(InvocationUtil.java:164)
	at com.hazelcast.internal.util.InvocationUtil$InvokeOnMemberFunction.apply(InvocationUtil.java:141)
	at com.hazelcast.internal.util.InvocationUtil$InvokeOnMemberFunction.apply(InvocationUtil.java:118)
	at com.hazelcast.util.IterableUtil$2.next(IterableUtil.java:60)
	at com.hazelcast.internal.util.futures.ChainingFuture.<init>(ChainingFuture.java:49)
	at com.hazelcast.internal.util.InvocationUtil.invokeOnStableClusterSerial(InvocationUtil.java:86)
	at com.hazelcast.internal.dynamicconfig.ClusterWideConfigurationService.broadcastConfigAsync(ClusterWideConfigurationService.java:251)
	at com.hazelcast.client.impl.protocol.task.dynamicconfig.AbstractAddConfigMessageTask.processMessage(AbstractAddConfigMessageTask.java:73)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:129)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:126)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run(AbstractInvocationFuture.java:251)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:96)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:33)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:163)
	at com.hazelcast.client.impl.clientside.ClientDynamicClusterConfig.invoke(ClientDynamicClusterConfig.java:1261)
	at com.hazelcast.client.impl.clientside.ClientDynamicClusterConfig.addMapConfig(ClientDynamicClusterConfig.java:161)
	at com.chinaums.hazelcast.datastructure.SimpleTest.test(SimpleTest.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestExecutionCallbacks.evaluate(RunBeforeTestExecutionCallbacks.java:74)
	at org.springframework.test.context.junit4.statements.RunAfterTestExecutionCallbacks.evaluate(RunAfterTestExecutionCallbacks.java:84)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:251)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)
```

**Comment by lishijun121910** [comment]
I look the code and find that static config and dynamic config will work together but static config is in priority.

this section in manual should be edit:

![image](https://user-images.githubusercontent.com/8045307/70019335-e26fb880-15c3-11ea-9c5d-b6acbbdc28c5.png)

**Comment by vbekiaris** [comment]
@lishijun121910 thanks for reporting the issue, this looks like a defect: adding a map (or any other data structure) config that is conflicting with static config should throw a `ConfigurationException` (in 3.12.x).

**Comment by vbekiaris** [comment]
Clarification: with member-side `HazelcastInstance`s an exception is already thrown, the issue has to do with using a client-side `HazelcastInstance` to add the dynamic config.

**Comment by lishijun121910** [comment]
> Clarification: with member-side `HazelcastInstance`s an exception is already thrown, the issue has to do with using a client-side `HazelcastInstance` to add the dynamic config.

thanks for replying , this happens in client-side case.
