### ISSUE TITLE
ClientJmxMetricsTest.testNoMBeanLeak

### ISSUE THREAD

**Issue by tezc** [hazelcast/hazelcast#16206]
_master_ (commit 320b492c89c9c32403de6798d7f4effadb53b3c4)

Failed on ZuluJDK10 : http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-ZuluJDK10/54/testReport/com.hazelcast.client.internal.metrics/ClientJmxMetricsTest/testNoMBeanLeak/

**Stacktrace**
```
java.lang.AssertionError: expected:<0> but was:<7>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.internal.metrics.jmx.JmxPublisherTestHelper.assertNoMBeans(JmxPublisherTestHelper.java:50)
	at com.hazelcast.client.internal.metrics.ClientJmxMetricsTest.testNoMBeanLeak(ClientJmxMetricsTest.java:52)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

Might be related with https://github.com/hazelcast/hazelcast/commit/8f3e2c16a743a009a7c6f2a9389fc36427a424c6 ? @blazember fyi.

**Comment by tezc** [comment]
Another one : 

http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-OracleJDK10/58/testReport/com.hazelcast.internal.metrics.jmx/MemberJmxMetricsTest/testNoMBeanLeak/

**Comment by devozerov** [comment]
Two tests fail because some of the previous tests leave dangling JMX beans. We need to understand which exact beans these are. Added logging to https://github.com/hazelcast/hazelcast/pull/16219 to check that.

**Comment by blazember** [comment]
Reopen with many failures. An example: http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/5967/testReport/junit/com.hazelcast.client.internal.metrics/ClientJmxMetricsTest/testNoMBeanLeak/

**Comment by sancar** [comment]
One more failure here
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/5987/testReport/junit/com.hazelcast.client.internal.metrics/ClientJmxMetricsTest/testNoMBeanLeak/

**Comment by sancar** [comment]
It started fail a lot:
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/5990/testReport/junit/com.hazelcast.client.internal.metrics/ClientJmxMetricsTest/testNoMBeanLeak/

**Comment by lazerion** [comment]
- Fails on `Hazelcast-4.master-CorrettoJDK8`
- Fails on [Build #63 (Mar 18, 2020 6:15:03 AM)](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-4.master-CorrettoJDK8/63/testReport/junit/com.hazelcast.client.internal.metrics/ClientJmxMetricsTest/testNoMBeanLeak/)
FYI

**Comment by blazember** [comment]
Copied from https://github.com/hazelcast/hazelcast/issues/17853

- Fails on **Hazelcast-4.master-ZuluJDK16**
- Fails on [Build #1 (Nov 12, 2020 8:00:00 AM)](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-4.master-ZuluJDK16/1/testReport/junit/com.hazelcast.client.internal.metrics/ClientJmxMetricsTest/testNoMBeanLeak/)
- Error
```
expected:<0> but was:<10>
```
- Stacktrace
```
java.lang.AssertionError: expected:<0> but was:<10>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at com.hazelcast.internal.metrics.jmx.JmxPublisherTestHelper.assertNoMBeans(JmxPublisherTestHelper.java:60)
	at com.hazelcast.client.internal.metrics.ClientJmxMetricsTest.testNoMBeanLeak(ClientJmxMetricsTest.java:52)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:832)

```
- Kindly check

**Comment by PavloBida** [comment]
Also fails on Hazelcast-4.master-Windows-OracleJDK8:
[13-Jan-2021 14:46](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-4.master-Windows-OracleJDK8/246/testReport/com.hazelcast.client.internal.metrics/ClientJmxMetricsTest/testNoMBeanLeak/)
