### ISSUE TITLE
QueryCacheMemoryLeakTest.stress_user_listener_removal_upon_query_cache_destroy

### ISSUE THREAD

**Issue by tezc** [hazelcast/hazelcast#16214]
_master_ (commit e73488e58a2d0b2799b20575eaf55743b09d3a09)

Failed on Windows : http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-Windows-OracleJDK8/117/testReport/junit/com.hazelcast.map.impl.querycache/QueryCacheMemoryLeakTest/stress_user_listener_removal_upon_query_cache_destroy/

**Stacktrace**
```
java.lang.AssertionError: {mapA=[], f24c245f-4e6b-45be-a596-9ccb78ed19b0=[], b9c3205d-3c58-48c7-9953-1fd357e6062d=[]}
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.map.impl.querycache.QueryCacheMemoryLeakTest.assertNoUserListenerLeft(QueryCacheMemoryLeakTest.java:352)
	at com.hazelcast.map.impl.querycache.QueryCacheMemoryLeakTest.stress_user_listener_removal_upon_query_cache_destroy(QueryCacheMemoryLeakTest.java:170)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

```
Hiccups measured while running test 'stress_user_listener_removal_upon_query_cache_destroy(com.hazelcast.map.impl.querycache.QueryCacheMemoryLeakTest):'
04:22:40, accumulated pauses: 847 ms, max pause: 27 ms, pauses over 1000 ms: 0
04:22:45, accumulated pauses: 757 ms, max pause: 14 ms, pauses over 1000 ms: 0
04:22:50, accumulated pauses: 731 ms, max pause: 2 ms, pauses over 1000 ms: 0
04:22:55, accumulated pauses: 721 ms, max pause: 2 ms, pauses over 1000 ms: 0
04:23:00, accumulated pauses: 722 ms, max pause: 2 ms, pauses over 1000 ms: 0
04:23:05, accumulated pauses: 729 ms, max pause: 2 ms, pauses over 1000 ms: 0
04:23:10, accumulated pauses: 726 ms, max pause: 2 ms, pauses over 1000 ms: 0
04:23:15, accumulated pauses: 718 ms, max pause: 2 ms, pauses over 1000 ms: 0
04:23:20, accumulated pauses: 719 ms, max pause: 2 ms, pauses over 1000 ms: 0
04:23:25, accumulated pauses: 737 ms, max pause: 2 ms, pauses over 1000 ms: 0
04:23:30, accumulated pauses: 718 ms, max pause: 2 ms, pauses over 1000 ms: 0
04:23:35, accumulated pauses: 745 ms, max pause: 2 ms, pauses over 1000 ms: 0
04:23:40, accumulated pauses: 725 ms, max pause: 2 ms, pauses over 1000 ms: 0
04:23:45, accumulated pauses: 736 ms, max pause: 2 ms, pauses over 1000 ms: 0
04:23:50, accumulated pauses: 729 ms, max pause: 2 ms, pauses over 1000 ms: 0
04:23:55, accumulated pauses: 730 ms, max pause: 12 ms, pauses over 1000 ms: 0
04:24:00, accumulated pauses: 730 ms, max pause: 2 ms, pauses over 1000 ms: 0
04:24:05, accumulated pauses: 732 ms, max pause: 2 ms, pauses over 1000 ms: 0
04:24:10, accumulated pauses: 735 ms, max pause: 2 ms, pauses over 1000 ms: 0
04:24:15, accumulated pauses: 724 ms, max pause: 2 ms, pauses over 1000 ms: 0
04:24:20, accumulated pauses: 729 ms, max pause: 2 ms, pauses over 1000 ms: 0
04:24:25, accumulated pauses: 739 ms, max pause: 2 ms, pauses over 1000 ms: 0
04:24:30, accumulated pauses: 715 ms, max pause: 2 ms, pauses over 1000 ms: 0
04:24:35, accumulated pauses: 726 ms, max pause: 2 ms, pauses over 1000 ms: 0
04:24:40, accumulated pauses: 745 ms, max pause: 335 ms, pauses over 1000 ms: 0
```

**Comment by ahmetmircik** [comment]
we already have an issue for this test failure: https://github.com/hazelcast/hazelcast/issues/16079

closing this one.
