### ISSUE TITLE
How to disable cluster member attempts to execute scheduled task

### ISSUE THREAD

**Issue by Pinkolik** [hazelcast/hazelcast#16218]
Hello everyone,
We have a following situation. In our multi-module application, we have a module which saves documents (byte arrays) to database. Those modules share distributed map which contains those documents. And saving is executed with distributed ScheduledExecutorService.
For our application it is very important not to lose any of those documents even if all of cluster members unexpectedly shut down and not all documents were saved from distributed map to database.
So we came up with a following solution: we developed a simple app which only task is to hold backups of this map. And even if saving modules fall for some reason, they will be able to resotre data from this backup app.
But then we encountered a problem: when we run our backup application, saving modules try to backup their scheduled tasks along with maps. And, obviously, back up application isn't intended to execute those task. And we get the following exception:
```
2019-12-10 14:04:01.419 ERROR 13360 --- [ration.thread-2] c.h.s.i.o.impl.OperationExecutorImpl     : [10.66.200.125]:15057 [dev] [3.12.4] Failed to process: Packet{partitionId=86, frameLength=1059, conn=Connection[id=1, /10.66.200.125:64217->/10.66.200.125:11088, qualifier=null, endpoint=[10.66.200.125]:11088, alive=true, type=MEMBER], rawFlags=10001, isUrgent=true, packetType=OPERATION, typeSpecificFlags=[isResponse=false, isOpControl=false]} on: hz.blobSaverService.partition-operation.thread-2

com.hazelcast.nio.serialization.HazelcastSerializationException: java.lang.ClassNotFoundException: ru.renue.blob.saver.runnable.OldBatchCleanerRunnable
	at com.hazelcast.internal.serialization.impl.JavaDefaultSerializers$JavaSerializer.read(JavaDefaultSerializers.java:88) ~[hazelcast-3.12.4.jar:3.12.4]
	at com.hazelcast.internal.serialization.impl.JavaDefaultSerializers$JavaSerializer.read(JavaDefaultSerializers.java:77) ~[hazelcast-3.12.4.jar:3.12.4]
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48) ~[hazelcast-3.12.4.jar:3.12.4]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.readObject(AbstractSerializationService.java:269) ~[hazelcast-3.12.4.jar:3.12.4]
	at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readObject(ByteArrayObjectDataInput.java:574) ~[hazelcast-3.12.4.jar:3.12.4]
	at com.hazelcast.scheduledexecutor.impl.ScheduledRunnableAdapter.readData(ScheduledRunnableAdapter.java:106) ~[hazelcast-3.12.4.jar:3.12.4]
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.readInternal(DataSerializableSerializer.java:160) ~[hazelcast-3.12.4.jar:3.12.4]
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:106) ~[hazelcast-3.12.4.jar:3.12.4]
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:51) ~[hazelcast-3.12.4.jar:3.12.4]
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48) ~[hazelcast-3.12.4.jar:3.12.4]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.readObject(AbstractSerializationService.java:269) ~[hazelcast-3.12.4.jar:3.12.4]
	at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readObject(ByteArrayObjectDataInput.java:574) ~[hazelcast-3.12.4.jar:3.12.4]
	at com.hazelcast.scheduledexecutor.impl.TaskDefinition.readData(TaskDefinition.java:132) ~[hazelcast-3.12.4.jar:3.12.4]
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.readInternal(DataSerializableSerializer.java:160) ~[hazelcast-3.12.4.jar:3.12.4]
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:106) ~[hazelcast-3.12.4.jar:3.12.4]
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:51) ~[hazelcast-3.12.4.jar:3.12.4]
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48) ~[hazelcast-3.12.4.jar:3.12.4]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.readObject(AbstractSerializationService.java:269) ~[hazelcast-3.12.4.jar:3.12.4]
	at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readObject(ByteArrayObjectDataInput.java:574) ~[hazelcast-3.12.4.jar:3.12.4]
	at com.hazelcast.scheduledexecutor.impl.ScheduledTaskDescriptor.readData(ScheduledTaskDescriptor.java:192) ~[hazelcast-3.12.4.jar:3.12.4]
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.readInternal(DataSerializableSerializer.java:160) ~[hazelcast-3.12.4.jar:3.12.4]
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:106) ~[hazelcast-3.12.4.jar:3.12.4]
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:51) ~[hazelcast-3.12.4.jar:3.12.4]
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48) ~[hazelcast-3.12.4.jar:3.12.4]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.readObject(AbstractSerializationService.java:269) ~[hazelcast-3.12.4.jar:3.12.4]
	at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readObject(ByteArrayObjectDataInput.java:574) ~[hazelcast-3.12.4.jar:3.12.4]
	at com.hazelcast.scheduledexecutor.impl.operations.ReplicationOperation.readInternal(ReplicationOperation.java:87) ~[hazelcast-3.12.4.jar:3.12.4]
	at com.hazelcast.spi.Operation.readData(Operation.java:728) ~[hazelcast-3.12.4.jar:3.12.4]
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.readInternal(DataSerializableSerializer.java:160) ~[hazelcast-3.12.4.jar:3.12.4]
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:106) ~[hazelcast-3.12.4.jar:3.12.4]
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:51) ~[hazelcast-3.12.4.jar:3.12.4]
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48) ~[hazelcast-3.12.4.jar:3.12.4]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.readObject(AbstractSerializationService.java:269) ~[hazelcast-3.12.4.jar:3.12.4]
	at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readObject(ByteArrayObjectDataInput.java:574) ~[hazelcast-3.12.4.jar:3.12.4]
	at com.hazelcast.internal.partition.ReplicaFragmentMigrationState.readData(ReplicaFragmentMigrationState.java:97) ~[hazelcast-3.12.4.jar:3.12.4]
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.readInternal(DataSerializableSerializer.java:160) ~[hazelcast-3.12.4.jar:3.12.4]
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:106) ~[hazelcast-3.12.4.jar:3.12.4]
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:51) ~[hazelcast-3.12.4.jar:3.12.4]
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48) ~[hazelcast-3.12.4.jar:3.12.4]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.readObject(AbstractSerializationService.java:269) ~[hazelcast-3.12.4.jar:3.12.4]
	at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readObject(ByteArrayObjectDataInput.java:574) ~[hazelcast-3.12.4.jar:3.12.4]
	at com.hazelcast.internal.partition.operation.MigrationOperation.readInternal(MigrationOperation.java:267) ~[hazelcast-3.12.4.jar:3.12.4]
	at com.hazelcast.spi.Operation.readData(Operation.java:728) ~[hazelcast-3.12.4.jar:3.12.4]
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.readInternal(DataSerializableSerializer.java:160) ~[hazelcast-3.12.4.jar:3.12.4]
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:106) ~[hazelcast-3.12.4.jar:3.12.4]
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:51) ~[hazelcast-3.12.4.jar:3.12.4]
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48) ~[hazelcast-3.12.4.jar:3.12.4]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:187) ~[hazelcast-3.12.4.jar:3.12.4]
	at com.hazelcast.spi.impl.NodeEngineImpl.toObject(NodeEngineImpl.java:324) ~[hazelcast-3.12.4.jar:3.12.4]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:401) ~[hazelcast-3.12.4.jar:3.12.4]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:153) [hazelcast-3.12.4.jar:3.12.4]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:123) [hazelcast-3.12.4.jar:3.12.4]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:110) [hazelcast-3.12.4.jar:3.12.4]
Caused by: java.lang.ClassNotFoundException: ru.renue.blob.saver.runnable.OldBatchCleanerRunnable
	at org.springframework.boot.web.embedded.tomcat.TomcatEmbeddedWebappClassLoader.loadClass(TomcatEmbeddedWebappClassLoader.java:72) ~[spring-boot-2.2.2.RELEASE.jar:2.2.2.RELEASE]
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1188) ~[tomcat-embed-core-9.0.29.jar:9.0.29]
	at com.hazelcast.nio.ClassLoaderUtil.tryLoadClass(ClassLoaderUtil.java:288) ~[hazelcast-3.12.4.jar:3.12.4]
	at com.hazelcast.nio.ClassLoaderUtil.loadClass(ClassLoaderUtil.java:252) ~[hazelcast-3.12.4.jar:3.12.4]
	at com.hazelcast.nio.IOUtil$ClassLoaderAwareObjectInputStream.resolveClass(IOUtil.java:699) ~[hazelcast-3.12.4.jar:3.12.4]
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1868) ~[na:1.8.0_211]
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1751) ~[na:1.8.0_211]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2042) ~[na:1.8.0_211]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573) ~[na:1.8.0_211]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:431) ~[na:1.8.0_211]
	at com.hazelcast.internal.serialization.impl.JavaDefaultSerializers$JavaSerializer.read(JavaDefaultSerializers.java:84) ~[hazelcast-3.12.4.jar:3.12.4]
```

Is there a way I can set up this cluster member to accept updates concerning IMap and ignore all ScheduledExecutorService updates?

Our setup parameters:
Cluster size: 4 savers, 1 backup application
Version of Java: 8
Operating system: Linux and Windows

**Comment by tkountis** [comment]
@Pinkolik this looks like you are missing the class from your classpath.
without getting more info on how this "backup-app" works / is set-up, we wont be able to help much. Could you share some code maybe?

**Comment by Pinkolik** [comment]
@tkountis yes, that's correct. It is our intention not to have those Runnable classes in backup-application because the idea is to make it as lightweight as possible. 
And backup-app works as follows: start up, connect to consul cluster, discover other hazelcast members, connects to them and just stands there and receives updates from actually working applications. You can consider this app as some kind of storage. It should not do anything except for holding a backup copy of the map

**Comment by Pinkolik** [comment]
To be clear, I understand what causes this exception. What I'm asking is that is there a way to configure a cluster member not to execute scheduled tasks received from other members?

**Comment by tkountis** [comment]
@Pinkolik there is no way to achieve this, that I aware of, at least trivially and reliably. One possible approach would be to rely on the 'OnMember' API of the 'IScheduledExecutorService' (ie. https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/scheduledexecutor/IScheduledExecutorService.java#L423) but keep in mind that by doing so you will effectively disable fault-tolerance on your tasks. If that target member dies, then the task will stop, no other node will resume it.

I hope that helps?

**Comment by tkountis** [comment]
@Pinkolik any update on this one?
We don't consider this a design flaw on our side, and there is no plans to have services ON/OFF selectively per node in the foreseeable future. Please let us know if this trick helps, or if we can provide any further help for your use-case.

**Comment by Pinkolik** [comment]
@tkountis Thank you for your reply, it was helpful, I will try your approach. 
You may close the issue :)
