### ISSUE TITLE
ClientClusterRestartEventTest.testMultiMemberRestart

### ISSUE THREAD

**Issue by ahmetmircik** [hazelcast/hazelcast#16217]
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/4928/testReport/junit/com.hazelcast.client/ClientClusterRestartEventTest/testMultiMemberRestart/

```
Error Message
Can not lock cluster state! Partition tables have different versions! Expected 
version: 0 Current version: 543
```

```
Stacktrace
java.lang.IllegalStateException: Can not lock cluster state! Partition tables have different versions! Expected version: 0 Current version: 543
	at com.hazelcast.internal.cluster.impl.ClusterStateManager.checkMigrationsAndPartitionStateVersion(ClusterStateManager.java:283)
	at com.hazelcast.internal.cluster.impl.ClusterStateManager.lockClusterState(ClusterStateManager.java:214)
	at com.hazelcast.internal.cluster.impl.operations.LockClusterStateOp.run(LockClusterStateOp.java:83)
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:184)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:221)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:210)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:394)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:421)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:590)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:575)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:534)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:236)
	at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.invokeOnTarget(OperationServiceImpl.java:337)
	at com.hazelcast.internal.cluster.impl.ClusterStateManager.lockClusterStateOnAllMembers(ClusterStateManager.java:453)
	at com.hazelcast.internal.cluster.impl.ClusterStateManager.changeClusterState(ClusterStateManager.java:387)
	at com.hazelcast.internal.cluster.impl.ClusterStateManager.changeClusterState(ClusterStateManager.java:360)
	at com.hazelcast.internal.cluster.impl.ClusterServiceImpl.changeClusterState(ClusterServiceImpl.java:786)
	at com.hazelcast.internal.cluster.impl.ClusterServiceImpl.shutdownCluster(ClusterServiceImpl.java:869)
	at com.hazelcast.internal.cluster.impl.ClusterServiceImpl.shutdown(ClusterServiceImpl.java:859)
	at com.hazelcast.client.ClientClusterRestartEventTest.testMultiMemberRestart(ClientClusterRestartEventTest.java:140)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by vojtechtoman** [comment]
Looks like there is a race in the test between the `PartitionStateOperation` sent from the master to the other members and the call to `shutdown()`. If `PartitionStateOperation` is delayed (i.e. arrives or is executed late relative to the shutdown request), some members may not have up-to-date partition table version at the time of the shutdown.

**Comment by cangencer** [comment]
This exact exception happend on a 3.12.6 build:

http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/5628/testReport/junit/com.hazelcast.client/ClientClusterRestartEventTest/testMultiMemberRestart/
