### ISSUE TITLE
EntryListenerOnReconnectTest.testListenersTerminateRandomNode_nonSmart

### ISSUE THREAD

**Issue by tezc** [hazelcast/hazelcast#16231]
_master_ (commit 1d89ff4ac6ab2b4ab4ff396c5bc7d983773fc938)

Failed on Sonar : http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-sonar/326/testReport/com.hazelcast.client.listeners/EntryListenerOnReconnectTest/testListenersTerminateRandomNode_nonSmart/

**Stacktrace**
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.lang.Thread.sleep(Native Method)
	at com.hazelcast.client.impl.spi.impl.ClientClusterViewService.getPartitionCount(ClientClusterViewService.java:545)
	at com.hazelcast.client.impl.spi.impl.ClientClusterViewService.getPartitionId(ClientClusterViewService.java:522)
	at com.hazelcast.client.impl.spi.impl.ClientClusterViewService.getPartitionId(ClientClusterViewService.java:533)
	at com.hazelcast.client.impl.spi.ClientProxy.invoke(ClientProxy.java:182)
	at com.hazelcast.client.impl.proxy.ClientMapProxy.putInternal(ClientMapProxy.java:535)
	at com.hazelcast.client.impl.proxy.ClientMapProxy.put(ClientMapProxy.java:263)
	at com.hazelcast.client.listeners.EntryListenerOnReconnectTest.produceEvent(EntryListenerOnReconnectTest.java:56)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest.validateListenerFunctionality(AbstractListenersOnReconnectTest.java:368)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest.validateRegistrationsAndListenerFunctionality(AbstractListenersOnReconnectTest.java:308)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest.testListenersTerminateRandomNode(AbstractListenersOnReconnectTest.java:115)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest.testListenersTerminateRandomNode_nonSmart(AbstractListenersOnReconnectTest.java:86)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by petrpleshachkov** [comment]
I've managed to reproduce the issue on my local machine.

**Comment by sancar** [comment]
@petrpleshachkov Did you do anything special to reproduce ?

**Comment by sancar** [comment]
https://github.com/hazelcast/hazelcast/pull/16195
This pr might fix this problem.

**Comment by petrpleshachkov** [comment]
@sancar, no just run it with `@Repeat(100) `and it fails after a while.

**Comment by sancar** [comment]
My investigation so far on the logs of failure here
 http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-sonar/326/testReport/com.hazelcast.client.listeners/EntryListenerOnReconnectTest/testListenersTerminateRandomNode_nonSmart/

Initial Memberlist
```
Members {size:3, ver:3} [
	Member [127.0.0.1]:5701 - 77248d38-9c5f-495d-9ee9-0d3a6db0c3a8
	Member [127.0.0.1]:5702 - 9bc2a7b1-17c2-498c-a071-a6df7bccf9ef
	Member [127.0.0.1]:5703 - 5ef83a58-25dd-4fdf-9c40-0e69bc55f09c this
]
```

Master says the following and shuts down 

```
22:12:37,802  INFO |testListenersTerminateRandomNode_nonSmart| - [PartitionStateManager] hz.priceless_shockley.priority-generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] Initializing cluster partition table arrangement...

22:12:37,859  INFO |testListenersTerminateRandomNode_nonSmart| - [Node] testListenersTerminateRandomNode_nonSmart - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] Hazelcast Shutdown is completed in 52 ms.
22:12:37,859  INFO |testListenersTerminateRandomNode_nonSmart| - [LifecycleService] testListenersTerminateRandomNode_nonSmart - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
```
Other members says that partition table version is 0. Note that 5702 is the new master. 
```
22:12:37,926  INFO |testListenersTerminateRandomNode_nonSmart| - [InternalPartitionService] hz.gracious_shockley.migration - [127.0.0.1]:5702 [dev] [4.0-SNAPSHOT] Fetching most recent partition table! my version: 0
22:12:37,928  INFO |testListenersTerminateRandomNode_nonSmart| - [InternalPartitionService] hz.gracious_shockley.migration - [127.0.0.1]:5702 [dev] [4.0-SNAPSHOT] Most recent partition table version: 0

22:17:37,134  INFO |testListenersTerminateRandomNode_nonSmart| - [InternalPartitionService] hz.romantic_shockley.migration - [127.0.0.1]:5704 [dev] [4.0-SNAPSHOT] Fetching most recent partition table! my version: 0
22:17:37,134  INFO |testListenersTerminateRandomNode_nonSmart| - [InternalPartitionService] hz.romantic_shockley.migration - [127.0.0.1]:5704 [dev] [4.0-SNAPSHOT] Most recent partition table version: 0
```


And there is confusing error about 5701 left. Even though the uuid matches the error is from another test ! Both tests are using mock network. 
The log of `whenEvictAllIsUsed_thenNearCacheIsInvalidated_onNearCacheAdapter` should not be in `com.hazelcast.client.listeners.EntryListenerOnReconnectTest-output.txt` , but it is there:
```
22:12:37,810 ERROR |whenEvictAllIsUsed_thenNearCacheIsInvalidated_onNearCacheAdapter| - [InternalPartitionService] ForkJoinPool.commonPool-worker-91 - [127.0.0.1]:5702 [dev] [4.0-SNAPSHOT] Member [127.0.0.1]:5701 - 77248d38-9c5f-495d-9ee9-0d3a6db0c3a8 has left cluster!
com.hazelcast.core.MemberLeftException: Member [127.0.0.1]:5701 - 77248d38-9c5f-495d-9ee9-0d3a6db0c3a8 has left cluster!
	at com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor$OnMemberLeftTask.onTargetLoss(InvocationMonitor.java:418) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor$OnMemberLeftTask.run0(InvocationMonitor.java:385) ~[classes/:?]
```

**Comment by sancar** [comment]
In this run, uniscoket client is connected to `5702`. It register partition listener to 5702 and calls `InterPartitionService.firstArrangement`. I assume that master dies before completing the partition assignment. 

As far as I understand from the code of `triggerMasterToAssignPartitions` , when `AssignPartitions` operations fails on master, we do not retry if member left. And unisocket client was relying on that. 

A fix could be to add a call to `triggerMasterToAssignPartitions` when exception is memberleft here
https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/internal/partition/impl/InternalPartitionServiceImpl.java#L281
I will prepare a fix.
