### ISSUE TITLE
ManagementCenterServiceTest.testShutdownCluster

### ISSUE THREAD

**Issue by tezc** [hazelcast/hazelcast#16242]
_master_ (commit 45aef4a6ed5f7d0ea08306e464cfb17e68ee7fec)

Failed on Sonar : http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-sonar/327/testReport/junit/com.hazelcast.client.management/ManagementCenterServiceTest/testShutdownCluster/

**Stacktrace**
```
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.client.management.ManagementCenterServiceTest.lambda$testShutdownCluster$9(ManagementCenterServiceTest.java:257)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1351)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1453)
	at com.hazelcast.client.management.ManagementCenterServiceTest.testShutdownCluster(ManagementCenterServiceTest.java:257)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

```
Hiccups measured while running test 'testShutdownCluster(com.hazelcast.client.management.ManagementCenterServiceTest):'
22:41:05, accumulated pauses: 1919 ms, max pause: 1876 ms, pauses over 1000 ms: 1
22:41:10, accumulated pauses: 3280 ms, max pause: 2016 ms, pauses over 1000 ms: 1
22:41:15, accumulated pauses: 274 ms, max pause: 50 ms, pauses over 1000 ms: 0
22:41:20, accumulated pauses: 33 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:41:25, accumulated pauses: 35 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:41:30, accumulated pauses: 37 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:41:35, accumulated pauses: 38 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:41:40, accumulated pauses: 38 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:41:45, accumulated pauses: 38 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:41:50, accumulated pauses: 53 ms, max pause: 12 ms, pauses over 1000 ms: 0
22:41:55, accumulated pauses: 30 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:42:00, accumulated pauses: 37 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:42:05, accumulated pauses: 38 ms, max pause: 1 ms, pauses over 1000 ms: 0
22:42:10, accumulated pauses: 38 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:42:15, accumulated pauses: 39 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:42:20, accumulated pauses: 36 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:42:25, accumulated pauses: 39 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:42:30, accumulated pauses: 54 ms, max pause: 3 ms, pauses over 1000 ms: 0
22:42:35, accumulated pauses: 51 ms, max pause: 1 ms, pauses over 1000 ms: 0
22:42:40, accumulated pauses: 38 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:42:45, accumulated pauses: 48 ms, max pause: 5 ms, pauses over 1000 ms: 0
22:42:50, accumulated pauses: 46 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:42:55, accumulated pauses: 69 ms, max pause: 1 ms, pauses over 1000 ms: 0
22:43:00, accumulated pauses: 43 ms, max pause: 1 ms, pauses over 1000 ms: 0
22:43:05, accumulated pauses: 44 ms, max pause: 2 ms, pauses over 1000 ms: 0
22:43:10, accumulated pauses: 443 ms, max pause: 406 ms, pauses over 1000 ms: 0
22:43:15, accumulated pauses: 9 ms, max pause: 0 ms, pauses over 1000 ms: 0
```

**Comment by vojtechtoman** [comment]
`22:41:11,172 ERROR |testShutdownCluster| - [LockClusterStateOp] hz.festive_jepsen.priority-generic-operation.thread-0 - [127.0.0.1]:5703 [dev] [4.0-SNAPSHOT] Can not lock cluster state! Partition tables have different versions! Expected version: 543 Current version: 0`

This is the very same issue as seen in https://github.com/hazelcast/hazelcast/issues/16217 - i.e. shutdown was initiated while some of the members don't have the up-to-date partition table version yet.
