### ISSUE TITLE
ClientServiceTest.testAddingListenersOpenConnectionsToAllCluster

### ISSUE THREAD

**Issue by ahmetmircik** [hazelcast/hazelcast#16254]
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/5047/testReport/junit/com.hazelcast.client/ClientServiceTest/testAddingListenersOpenConnectionsToAllCluster/

```
Error Message
expected:<4> but was:<1>
Stacktrace
java.lang.AssertionError: expected:<4> but was:<1>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.client.ClientServiceTest.testAddingListenersOpenConnectionsToAllCluster(ClientServiceTest.java:526)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by mdogan** [comment]
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/5069/testReport/junit/com.hazelcast.client/ClientServiceTest/testAddingListenersOpenConnectionsToAllCluster/

```
java.lang.AssertionError: expected:<4> but was:<1>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.client.ClientServiceTest.testAddingListenersOpenConnectionsToAllCluster(ClientServiceTest.java:526)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

```
Hiccups measured while running test 'testAddingListenersOpenConnectionsToAllCluster(com.hazelcast.client.ClientServiceTest):'
07:44:20, accumulated pauses: 1231 ms, max pause: 474 ms, pauses over 1000 ms: 0
07:44:25, accumulated pauses: 999 ms, max pause: 432 ms, pauses over 1000 ms: 0
```
