### ISSUE TITLE
PartitionMigrationListenerTest.testMigrationStats_whenMigrationProcessCompletes

### ISSUE THREAD

**Issue by tezc** [hazelcast/hazelcast#16299]
_master_ (commit 58abe5433401a6d857c23710cfc9813dde0eb3d2)

Failed on Windows : http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-Windows-OracleJDK8/120/testReport/com.hazelcast.partition/PartitionMigrationListenerTest/testMigrationStats_whenMigrationProcessCompletes/

**Stacktrace**
```
java.lang.AssertionError: expected:<271> but was:<1>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.partition.PartitionMigrationListenerTest.assertMigrationProcessEventsConsistent(PartitionMigrationListenerTest.java:201)
	at com.hazelcast.partition.PartitionMigrationListenerTest.testMigrationStats_whenMigrationProcessCompletes(PartitionMigrationListenerTest.java:83)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by sancar** [comment]
A new test failure 
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/3545/testReport/junit/com.hazelcast.partition/PartitionMigrationListenerTest/testMigrationStats_whenMigrationProcessCompletes/

```
Error Message
expected:<271> but was:<10>
Stacktrace
java.lang.AssertionError: expected:<271> but was:<10>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at com.hazelcast.partition.PartitionMigrationListenerTest.assertMigrationProcessEventsConsistent(PartitionMigrationListenerTest.java:224)
	at com.hazelcast.partition.PartitionMigrationListenerTest.testMigrationStats_whenMigrationProcessCompletes(PartitionMigrationListenerTest.java:88)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by vbekiaris** [comment]
In the latest failure, the cluster state was observed as `IN_TRANSITION` from the `MigrationOperation`s scheduled by the repartioning task:

```
12:27:49,398 ERROR |testMigrationStats_whenMigrationProcessCompletes| - [MigrationOperation] hz.zealous_curran.partition-operation.thread-1 - [127.0.0.1]:5702 [dev] [4.2-SNAPSHOT] Cluster state does not allow migrations! IN_TRANSITION
java.lang.IllegalStateException: Cluster state does not allow migrations! IN_TRANSITION
        at com.hazelcast.internal.partition.operation.BaseMigrationOperation.verifyClusterState(BaseMigrationOperation.java:215) ~[classes/:?]
        at com.hazelcast.internal.partition.operation.BaseMigrationOperation.beforeRun(BaseMigrationOperation.java:89) ~[classes/:?]
        at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:247) [classes/:?]
        at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:469) [classes/:?]
        at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:197) [classes/:?]
        at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:137) [classes/:?]
        at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123) [classes/:?]
        at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) [classes/:?]
``` 

This does not look like an issue, repartitioning is rescheduled and migrations are completed successfully. However it breaks the planned vs actual completed migrations assertion in the test.

**Comment by vbekiaris** [comment]
The failure can be reproduced consistently by introducing a delay in the [`for` loop that delivers](https://github.com/hazelcast/hazelcast/blob/40d555dc1110da9f63fd66f504c83d4382d0384b/hazelcast/src/main/java/com/hazelcast/transaction/impl/TransactionLog.java#L91) the `CommitClusterStateOp`s to each member.

The mechanics of the failure are as follows:

* In transaction prepare phase, all members lock the `ClusterStateManager#stateLockRef`. Notice that while this `LockGuard` reports that it is locked, `ClusterStateManager#getState` reports `IN_TRANSITION` cluster state.
* In transaction commit phase, `CommitClusterStateOp`s are delivered and executed sequentially on each member. During `CommitClusterStateOp` execution, the `LockGuard` is unlocked.
* It can be the case that the cluster’s master member receives the `CommitClusterStateOp` before other members. With unlucky timing, the master will schedule migrations while other members have not yet executed the `CommitClusterStateOp` -> partition migration operations will observe the cluster state as `IN_TRANSITION` and fail those migration operations.

The migration failure is transient because the master will reschedule partition migrations which will eventually succeed. However the test’s assertions will not hold, because it expects that all migrations occur in a single go. The same applies to test `testMigrationListenerCalledOnlyOnceWhenMigrationHappens`, its assertion fails with the added delay because it expects migrations to start only once. 

The failure goes away (even with artificial delay) if `TransactionLog` is changed to delay committing the transaction to master member. However this is an implementation detail of `TransactionLog#commit` and shouldn't be relied upon. The failure is benign and since it occurred only once after a year, I would keep test assertions as they are, even though they are a bit stricter than actual production code guarantees. If the test fails more frequently, we can reconsider a fix.
