### ISSUE TITLE
NearCachePreloaderLockTest.testRelease

### ISSUE THREAD

**Issue by tezc** [hazelcast/hazelcast#16300]
_master_ (commit 58abe5433401a6d857c23710cfc9813dde0eb3d2)

Failed on Windows : http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-Windows-OracleJDK8/120/testReport/junit/com.hazelcast.internal.nearcache.impl.preloader/NearCachePreloaderLockTest/testRelease/

**Stacktrace**
```
com.hazelcast.core.HazelcastException: Failed to delete C:\Jenkins\workspace\Hazelcast-3.x-Windows-OracleJDK8\hazelcast\4f6f2f43-ff72-48aa-a7b5-606a2e41bdcc
	at com.hazelcast.internal.nio.IOUtil.delete(IOUtil.java:434)
	at com.hazelcast.internal.nearcache.impl.preloader.NearCachePreloaderLock.releaseInternal(NearCachePreloaderLock.java:82)
	at com.hazelcast.internal.nearcache.impl.preloader.NearCachePreloaderLockTest.testRelease(NearCachePreloaderLockTest.java:134)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by tezc** [comment]
http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-Windows-OracleJDK8/122/testReport/com.hazelcast.internal.nearcache.impl.preloader/NearCachePreloaderLockTest/testRelease/
