### ISSUE TITLE
WanPublisherMigrationTest.testMigration

### ISSUE THREAD

**Issue by mdogan** [hazelcast/hazelcast#16308]
__failMigrations = false__

http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/5178/testReport/junit/com.hazelcast.wan.impl/WanPublisherMigrationTest/testMigration_failMigrations_false_/

```
java.lang.AssertionError: expected:<6> but was:<7>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.wan.impl.WanPublisherMigrationTest.testMigration(WanPublisherMigrationTest.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

```
Hiccups measured while running test 'testMigration[failMigrations:false](com.hazelcast.wan.impl.WanPublisherMigrationTest):'
12:14:30, accumulated pauses: 618 ms, max pause: 21 ms, pauses over 1000 ms: 0
12:14:35, accumulated pauses: 334 ms, max pause: 259 ms, pauses over 1000 ms: 0
```

**Comment by ahmetmircik** [comment]
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/5210/testReport/junit/com.hazelcast.wan.impl/WanPublisherMigrationTest/testMigration_failMigrations_true_/
