### ISSUE TITLE
[TEST-FAILURE] MultiCastJoinTest test failures

### ISSUE THREAD

**Issue by andrew-davie** [hazelcast/hazelcast#16358]
I thought I'd report this "error", as I couldn't see a match in the issues...
Symptoms of this are that I never get the exception when running "normally", but always do when I engage a VPN. My VPN isn't THAT slow, but my overall connection being wireless may be contributing.
In short, I suspect that the timeout values on the test and/or the code called are too short and trigger the exception. But I thought I'd report this, in case there's a more serious underlying error.
I am *not* getting similar errors on the other tests in the suite, as far as I am aware, but I can reproduce this one at will... 100%. VPN on --> error. VPN off --> test OK. I have no other internet issues with VPN use, and have been using it for literally years.

from "mvn clean install" on a fresh git clone of the current codebase... with VPN engaged...

```
[INFO] --- maven-surefire-plugin:2.21.0:test (default-test) @ hazelcast ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.hazelcast.ringbuffer.RingbufferSplitBrainTest
[INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 44.572 s - in com.hazelcast.ringbuffer.RingbufferSplitBrainTest
[INFO] Running com.hazelcast.aggregation.AggregatorsSpecTest
[INFO] Tests run: 24, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 36.811 s - in com.hazelcast.aggregation.AggregatorsSpecTest
[INFO] Running com.hazelcast.cluster.MulticastJoinTest
[ERROR] Tests run: 6, Failures: 3, Errors: 0, Skipped: 0, Time elapsed: 72.3 s <<< FAILURE! - in com.hazelcast.cluster.MulticastJoinTest
[ERROR] test_whenInterfacesEnabled(com.hazelcast.cluster.MulticastJoinTest)  Time elapsed: 16.129 s  <<< FAILURE!
java.lang.AssertionError: Cluster size is not correct. Expected: 2, actual: 1, instance index: 0
	at org.junit.Assert.fail(Assert.java:88)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSize(HazelcastTestSupport.java:1143)
	at com.hazelcast.cluster.AbstractJoinTest.testJoin(AbstractJoinTest.java:38)
	at com.hazelcast.cluster.MulticastJoinTest.test_whenInterfacesEnabled(MulticastJoinTest.java:88)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:830)

[ERROR] test_whenDifferentBuildNumber(com.hazelcast.cluster.MulticastJoinTest)  Time elapsed: 15.83 s  <<< FAILURE!
java.lang.AssertionError: Cluster size is not correct. Expected: 2, actual: 1, instance index: 0
	at org.junit.Assert.fail(Assert.java:88)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSize(HazelcastTestSupport.java:1143)
	at com.hazelcast.cluster.AbstractJoinTest.testJoin_With_DifferentBuildNumber(AbstractJoinTest.java:59)
	at com.hazelcast.cluster.MulticastJoinTest.test_whenDifferentBuildNumber(MulticastJoinTest.java:99)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:830)

[ERROR] test(com.hazelcast.cluster.MulticastJoinTest)  Time elapsed: 15.636 s  <<< FAILURE!
java.lang.AssertionError: Cluster size is not correct. Expected: 2, actual: 1, instance index: 0
	at org.junit.Assert.fail(Assert.java:88)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSize(HazelcastTestSupport.java:1143)
	at com.hazelcast.cluster.AbstractJoinTest.testJoin(AbstractJoinTest.java:38)
	at com.hazelcast.cluster.MulticastJoinTest.test(MulticastJoinTest.java:71)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:830)
```

MacOS Catalina 10.15.1
java 13.0.1 2019-10-15
Java(TM) SE Runtime Environment (build 13.0.1+9)
Java HotSpot(TM) 64-Bit Server VM (build 13.0.1+9, mixed mode, sharing)
VPN: PIA, node: romania

**Comment by andrew-davie** [comment]
actually, may be the same thing as #16353
Timeout value "too low" - at least for my situation/usage.

**Comment by mdogan** [comment]
@andrew-davie: If the test is failing when VPN is on, most probably VPN's network interface is selected by default. I guess that interface doesn't support multicast on selected address. 

Do you see any `java.net.*` exceptions in the log? Such as `java.net.SocketException: Can't assign requested address`.

**Comment by andrew-davie** [comment]
> @andrew-davie: If the test is failing when VPN is on, most probably VPN's network interface is selected by default. I guess that interface doesn't support multicast on selected address.
> 
> Do you see any `java.net.*` exceptions in the log? Such as `java.net.SocketException: Can't assign requested address`.

Sorry for the delay. I had to do a complete OS reinstall. Now back and running again, with the same error. I do see some likely info in the ".txt" logs that may be related.

[2d775d80-32ea-4bd5-8579-d4106d7faa4b] [4.0-SNAPSHOT] Could not connect to: /127.0.0.1:5703. Reason: SocketException[Connection refused to address /127.0.0.1:5703]

**Comment by lprimak** [comment]
I had these tests fail also on multi-homed hosts

**Comment by lprimak** [comment]
I think this one can be closed as it’s fixed now as far as I can see

**Comment by lprimak** [comment]
@Holmistr Please close this issue. It is confirmed fixed.

**Comment by Holmistr** [comment]
Thanks a lot :)
