### ISSUE TITLE
ScheduledExecutorServiceBasicTest.schedule_withNamedInstanceAware_whenRemoteRun

### ISSUE THREAD

**Issue by tezc** [hazelcast/hazelcast#16364]
http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.maintenance-IbmJDK7/109/testReport/com.hazelcast.scheduledexecutor/ScheduledExecutorServiceBasicTest/schedule_withNamedInstanceAware_whenRemoteRun/

**Stacktrace**
```
java.lang.AssertionError: expected:<0> but was:<1>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.scheduledexecutor.ScheduledExecutorServiceBasicTest.schedule_withNamedInstanceAware_whenRemoteRun(ScheduledExecutorServiceBasicTest.java:799)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:95)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:56)
	at java.lang.reflect.Method.invoke(Method.java:620)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.util.concurrent.FutureTask.run(FutureTask.java:274)
	at java.lang.Thread.run(Thread.java:809)
```

```
Hiccups measured while running test 'schedule_withNamedInstanceAware_whenRemoteRun(com.hazelcast.scheduledexecutor.ScheduledExecutorServiceBasicTest):'
03:00:45, accumulated pauses: 190 ms, max pause: 162 ms, pauses over 1000 ms: 0
03:00:50, accumulated pauses: 1002 ms, max pause: 980 ms, pauses over 1000 ms: 0
03:00:55, accumulated pauses: 62 ms, max pause: 4 ms, pauses over 1000 ms: 0
03:01:00, accumulated pauses: 106 ms, max pause: 20 ms, pauses over 1000 ms: 0
03:01:05, accumulated pauses: 85 ms, max pause: 6 ms, pauses over 1000 ms: 0
03:01:10, accumulated pauses: 1008 ms, max pause: 934 ms, pauses over 1000 ms: 0
03:01:15, accumulated pauses: 52 ms, max pause: 5 ms, pauses over 1000 ms: 0
03:01:20, accumulated pauses: 53 ms, max pause: 6 ms, pauses over 1000 ms: 0
03:01:25, accumulated pauses: 21 ms, max pause: 6 ms, pauses over 1000 ms: 0
```

**Comment by metanet** [comment]
closed by https://github.com/hazelcast/hazelcast/pull/16383
