### ISSUE TITLE
MembershipUpdateTest.shouldNotProcessStaleJoinRequest

### ISSUE THREAD

**Issue by tezc** [hazelcast/hazelcast#16361]
http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-ZuluJDK8/58/

MembershipUpdateTest.shouldNotProcessStaleJoinRequest
MembershipUpdateTest.shouldNotProcessStaleJoinRequest_whenMasterChanges

**Stacktrace**
```
java.lang.AssertionError: Cluster size is not correct. Expected: 1, actual: 2, instance index: 0
	at org.junit.Assert.fail(Assert.java:88)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSize(HazelcastTestSupport.java:1143)
	at com.hazelcast.internal.cluster.impl.MembershipUpdateTest$12.run(MembershipUpdateTest.java:683)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueAllTheTime(HazelcastTestSupport.java:1314)
	at com.hazelcast.internal.cluster.impl.MembershipUpdateTest.shouldNotProcessStaleJoinRequest(MembershipUpdateTest.java:677)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by tezc** [comment]
```
Hiccups measured while running test 'shouldNotProcessStaleJoinRequest(com.hazelcast.internal.cluster.impl.MembershipUpdateTest):'
08:30:55, accumulated pauses: 2593 ms, max pause: 2131 ms, pauses over 1000 ms: 1
08:31:00, accumulated pauses: 1507 ms, max pause: 1290 ms, pauses over 1000 ms: 1
08:31:05, accumulated pauses: 12478 ms, max pause: 9092 ms, pauses over 1000 ms: 2
08:31:15, accumulated pauses: 159 ms, max pause: 6 ms, pauses over 1000 ms: 0
08:31:20, accumulated pauses: 644 ms, max pause: 81 ms, pauses over 1000 ms: 0
08:31:25, accumulated pauses: 2185 ms, max pause: 1926 ms, pauses over 1000 ms: 1
08:31:30, accumulated pauses: 3343 ms, max pause: 1376 ms, pauses over 1000 ms: 2
08:31:35, accumulated pauses: 1888 ms, max pause: 1060 ms, pauses over 1000 ms: 1
08:31:40, accumulated pauses: 3224 ms, max pause: 1652 ms, pauses over 1000 ms: 1
08:31:45, accumulated pauses: 1292 ms, max pause: 651 ms, pauses over 1000 ms: 0
08:31:50, accumulated pauses: 292 ms, max pause: 11 ms, pauses over 1000 ms: 0
08:31:55, accumulated pauses: 1810 ms, max pause: 1134 ms, pauses over 1000 ms: 1
08:32:00, accumulated pauses: 335 ms, max pause: 61 ms, pauses over 1000 ms: 0
08:32:05, accumulated pauses: 114 ms, max pause: 24 ms, pauses over 1000 ms: 0
```

There are huge hiccups. 
I see that these tests use upto ~13k threads, can we decrease load somehow? 

Log file :
[com.hazelcast.internal.cluster.impl.MembershipUpdateTest-output.zip](https://github.com/hazelcast/hazelcast/files/4002440/com.hazelcast.internal.cluster.impl.MembershipUpdateTest-output.zip)

**Comment by andrew-davie** [comment]
I also got a "cluster size not correct" assert in #16358 - is it related?

**Comment by mdogan** [comment]
@andrew-davie: I don't think these are related. It's a very generic assertion for expected cluster size. There might be tons of reasons for cluster formation to fail.

**Comment by mdogan** [comment]
@tezc: We can reduce parallelization of the test. This test is not doing any heavy computations or executing operations, I don't expect those threads to cause long hiccups. 

Cause of the failure is the hiccups. Shutdown of the 2nd member took ~29 seconds. => `Shutdown is completed in 28796 ms.`  Stale join prevention timeout is by default 30 seconds. 

I am closing this issue for now. If it fails again because of long pauses, I will lower the parallelism and number of operation threads.

**Comment by tezc** [comment]
@mdogan ok, thanks
