### ISSUE TITLE
DistributedObjectListenerTest.testDestroyEventReceived_WhenDestroyedByServer

### ISSUE THREAD

**Issue by ahmetmircik** [hazelcast/hazelcast#16374]
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/5319/testReport/junit/com.hazelcast.core/DistributedObjectListenerTest/testDestroyEventReceived_WhenDestroyedByServer/

```
Error Message
Create event failed. unexpectedObjectName:null expected:<1> but was:<2>
Stacktrace
java.lang.AssertionError: Create event failed. unexpectedObjectName:null expected:<1> but was:<2>
	at com.hazelcast.core.DistributedObjectListenerTest.lambda$testDestroyEventReceived_WhenDestroyedByServer$3(DistributedObjectListenerTest.java:167)
	at com.hazelcast.core.DistributedObjectListenerTest.testDestroyEventReceived_WhenDestroyedByServer(DistributedObjectListenerTest.java:174)
```

**Comment by mmedenjak** [comment]
Maybe caused by latest changes in proxy lifecycle (https://github.com/hazelcast/hazelcast/pull/16347). @ihsandemir can you take a look?

**Comment by tkountis** [comment]
One more local run with the events logged

```
Members {size:4, ver:4} [
	Member [127.0.0.1]:5701 - c9316432-4db2-40e9-abcf-e4fec5ce13de
	Member [127.0.0.1]:5702 - 991f6d37-9172-42c2-ad04-af7d9e28d6cf this
	Member [127.0.0.1]:5703 - 8c4f64a8-ee4b-4315-bfc9-5d657b85668b
	Member [127.0.0.1]:5704 - c776daf8-bf68-4cde-867a-5cb13aa79836
]
```

```
12:52:53,801  INFO |testDestroyEventReceived_WhenDestroyedByServer| - [LifecycleService] testDestroyEventReceived_WhenDestroyedByServer - [127.0.0.1]:5704 [dev] [4.0-SNAPSHOT] [127.0.0.1]:5704 is STARTED
Created: DistributedObjectEvent{distributedObject=IMap{name='8ff574d8-d3e6-4e13-bec1-a29980fbfe0d'}, eventType=CREATED, serviceName='hz:impl:mapService', objectName='8ff574d8-d3e6-4e13-bec1-a29980fbfe0d', source=c776daf8-bf68-4cde-867a-5cb13aa79836}
Destroyed: DistributedObjectEvent{distributedObject=IMap{name='8ff574d8-d3e6-4e13-bec1-a29980fbfe0d'}, eventType=DESTROYED, serviceName='hz:impl:mapService', objectName='8ff574d8-d3e6-4e13-bec1-a29980fbfe0d', source=c9316432-4db2-40e9-abcf-e4fec5ce13de}
Created: DistributedObjectEvent{distributedObject=IMap{name='8ff574d8-d3e6-4e13-bec1-a29980fbfe0d'}, eventType=CREATED, serviceName='hz:impl:mapService', objectName='8ff574d8-d3e6-4e13-bec1-a29980fbfe0d', source=c9316432-4db2-40e9-abcf-e4fec5ce13de}
Destroyed: DistributedObjectEvent{distributedObject=IMap{name='8ff574d8-d3e6-4e13-bec1-a29980fbfe0d'}, eventType=DESTROYED, serviceName='hz:impl:mapService', objectName='8ff574d8-d3e6-4e13-bec1-a29980fbfe0d', source=c9316432-4db2-40e9-abcf-e4fec5ce13de}
```

**Comment by ihsandemir** [comment]
When I examine the problem, I realize that this is actually caused by the race of proxy creation between member and client. The test actually was aiming to test the destroyProxy but as a side affect it triggers this race on proxy creation. The race is:

1. Client creates proxy on a random server. This creation sends events to other members to create the proxy. The other members will create proxies on receiving the event but the event sender member will not wait for them and will return to the client and a create proxy event is also sent to the registered listeners.
2. The next test step does getMap on the server side and if this server is one of those members which will be creating the proxy on receiving the event and the event delivery is slow, then the member will create the proxy thinking that it was not created in the cluster and hence send a second creation event and test fails with 2 creation events.

We were already aware of these kinds of problems and they need to be handled with a proper proxy creation solution not depending on the events if possible.

**Comment by kwart** [comment]
@ihsandemir Could you ignore the failing tests if the fix is not going to 4.0?

**Comment by ihsandemir** [comment]
@kwart The test is fixed but the root cause of the problem is not. I am not expecting the test to fail after the merged PR above.

**Comment by sancar** [comment]
@ihsandemir Test failed again. It seems fix was not enough.

http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/5384/testReport/junit/com.hazelcast.client.impl.proxy/ClientDistributedObjectListenerTest/testDestroyEventReceived_WhenDestroyedByServer/

**Comment by mdogan** [comment]
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/5410/testReport/junit/com.hazelcast.core/DistributedObjectListenerTest/testDestroyEventReceived_WhenDestroyedByServer/

```
java.lang.AssertionError: Distributed object is not created for member:HazelcastInstance{name='heuristic_solomon', node=[127.0.0.1]:5702}, objects:[IMap{name='f906766f-8c72-4c97-b551-1b0fc9606678'}] expected:<0> but was:<1>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.core.DistributedObjectListenerTest.lambda$null$2(DistributedObjectListenerTest.java:243)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.hazelcast.core.DistributedObjectListenerTest.lambda$checkTheNumberOfObjectsInClusterIsEventuallyAsExpected$3(DistributedObjectListenerTest.java:241)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1356)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1458)
	at com.hazelcast.core.DistributedObjectListenerTest.checkTheNumberOfObjectsInClusterIsEventuallyAsExpected(DistributedObjectListenerTest.java:240)
	at com.hazelcast.core.DistributedObjectListenerTest.lambda$getVerifyProxyDestroyedTask$1(DistributedObjectListenerTest.java:216)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1356)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1458)
	at com.hazelcast.core.DistributedObjectListenerTest.verifyDestroy(DistributedObjectListenerTest.java:207)
	at com.hazelcast.core.DistributedObjectListenerTest.testDestroyEventReceived_WhenDestroyedByServer(DistributedObjectListenerTest.java:168)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by ihsandemir** [comment]
Changing the milestone to 4.1 after the merged PRs https://github.com/hazelcast/hazelcast/pull/16422 and https://github.com/hazelcast/hazelcast/pull/16418

**Comment by lazerion** [comment]
@ihsandemir could you guide the failure on [testGetDistributedObjectsAfterDestroy_fromInstance](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-Windows-OracleJDK8/133/testReport/junit/com.hazelcast.core/DistributedObjectListenerTest/testGetDistributedObjectsAfterDestroy_fromInstance/) ? I think it is similar, do we need a side or new issue?

**Comment by ahmetmircik** [comment]
not failed since January, closing now.
