### ISSUE TITLE
Test failure with "JMX beans are still registered" exception

### ISSUE THREAD

**Issue by tezc** [hazelcast/hazelcast#16381]
http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-Windows-OracleJDK8/127/testReport/com.hazelcast.client/ClientRegressionWithRealNetworkTest/com_hazelcast_client_ClientRegressionWithRealNetworkTest/

**Stacktrace**
```
java.lang.IllegalStateException: 
JMX beans are still registered:
	com.hazelcast:instance=hz.client_708,prefix=classloading,type=Metrics
	com.hazelcast:instance=hz.client_708,prefix=file.partition,tag0="dir=user.home",type=Metrics
	com.hazelcast:instance=hz.client_708,prefix=gc,type=Metrics
	com.hazelcast:instance=hz.client_708,prefix=invocations,type=Metrics
	com.hazelcast:instance=hz.client_708,prefix=listeners,type=Metrics
	com.hazelcast:instance=hz.client_708,prefix=memory,type=Metrics
	com.hazelcast:instance=hz.client_708,prefix=os,type=Metrics
	com.hazelcast:instance=hz.client_708,prefix=runtime,type=Metrics
	com.hazelcast:instance=hz.client_708,prefix=tcp,type=Metrics
	com.hazelcast:instance=hz.client_708,prefix=tcp.balancer,type=Metrics
	com.hazelcast:instance=hz.client_708,prefix=tcp.connection.in,tag0="pipelineId=/0.0.0.0:52604->null",type=Metrics
	com.hazelcast:instance=hz.client_708,prefix=tcp.connection.out,tag0="pipelineId=/0.0.0.0:52604->null",type=Metrics
	com.hazelcast:instance=hz.client_708,prefix=tcp.inputThread,tag0="thread=hz.hz.client_708.IO.thread-in-0",type=Metrics
	com.hazelcast:instance=hz.client_708,prefix=tcp.outputThread,tag0="thread=hz.hz.client_708.IO.thread-out-0",type=Metrics
	com.hazelcast:instance=hz.client_708,prefix=thread,type=Metrics

	at com.hazelcast.test.JmxLeakHelper.checkJmxBeans(JmxLeakHelper.java:69)
	at com.hazelcast.test.AbstractHazelcastClassRunner$1.evaluate(AbstractHazelcastClassRunner.java:312)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:107)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:83)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:379)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:340)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:413)
```

Same issue on EE :

https://github.com/hazelcast/hazelcast-enterprise/issues/3449

**Comment by tezc** [comment]
Another one :

http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-ZuluJDK10/57/testReport/com.hazelcast.replicatedmap/ReplicatedMapStatsTest/com_hazelcast_replicatedmap_ReplicatedMapStatsTest/

We are getting this exception a lot lately, maybe we need different approach to this?
