### ISSUE TITLE
ClientCacheNearCacheCacheOnUpdateTest.with_invalidate_policy_concurrently_updated_near_cache_causes_misses

### ISSUE THREAD

**Issue by sancar** [hazelcast/hazelcast#16397]
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/5354/testReport/junit/com.hazelcast.client.cache.impl.nearcache/ClientCacheNearCacheCacheOnUpdateTest/with_invalidate_policy_concurrently_updated_near_cache_causes_misses/

```
Stacktrace
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.client.cache.impl.nearcache.ClientCacheNearCacheCacheOnUpdateTest.with_invalidate_policy_concurrently_updated_near_cache_causes_misses(ClientCacheNearCacheCacheOnUpdateTest.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by lazerion** [comment]
- Fails on `Hazelcast-4.maintenance-ZuluJDK8`
- Fails on [Build #63 (Feb 19, 2020 2:05:02 AM)](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-4.maintenance-ZuluJDK8/63/testReport/junit/com.hazelcast.client.cache.impl.nearcache/ClientCacheNearCacheCacheOnUpdateTest/with_invalidate_policy_concurrently_updated_near_cache_causes_misses/)

- Failing cases 
```
com.hazelcast.client.cache.impl.nearcache.ClientCacheNearCacheCacheOnUpdateTest.with_invalidate_policy_concurrently_updated_near_cache_causes_misses
com.hazelcast.client.cache.impl.nearcache.ClientCacheNearCacheCacheOnUpdateTest.with_cacheOnUpdate_policy_concurrently_updated_near_cache_does_not_cause_any_miss
```

kindly check

**Comment by Holmistr** [comment]
Crazy hiccups here:
```
Hiccups measured while running test 'with_invalidate_policy_concurrently_updated_near_cache_causes_misses(com.hazelcast.client.cache.impl.nearcache.ClientCacheNearCacheCacheOnUpdateTest):'
02:16:30, accumulated pauses: 1419 ms, max pause: 99 ms, pauses over 1000 ms: 0
02:16:35, accumulated pauses: 4518 ms, max pause: 590 ms, pauses over 1000 ms: 0
02:16:40, accumulated pauses: 4409 ms, max pause: 98 ms, pauses over 1000 ms: 0
02:16:45, accumulated pauses: 4359 ms, max pause: 490 ms, pauses over 1000 ms: 0
02:16:50, accumulated pauses: 4379 ms, max pause: 889 ms, pauses over 1000 ms: 0
02:16:55, accumulated pauses: 4729 ms, max pause: 3190 ms, pauses over 1000 ms: 1
02:17:00, accumulated pauses: 4429 ms, max pause: 590 ms, pauses over 1000 ms: 0
02:17:05, accumulated pauses: 4429 ms, max pause: 490 ms, pauses over 1000 ms: 0
02:17:10, accumulated pauses: 4299 ms, max pause: 90 ms, pauses over 1000 ms: 0
02:17:15, accumulated pauses: 5505 ms, max pause: 2896 ms, pauses over 1000 ms: 1
02:17:20, accumulated pauses: 3964 ms, max pause: 2074 ms, pauses over 1000 ms: 1
02:17:25, accumulated pauses: 6890 ms, max pause: 3190 ms, pauses over 1000 ms: 1
02:17:30, accumulated pauses: 2308 ms, max pause: 93 ms, pauses over 1000 ms: 0
02:17:35, accumulated pauses: 4479 ms, max pause: 3190 ms, pauses over 1000 ms: 2
02:17:40, accumulated pauses: 5339 ms, max pause: 1690 ms, pauses over 1000 ms: 2
02:17:45, accumulated pauses: 4719 ms, max pause: 2389 ms, pauses over 1000 ms: 1
02:17:50, accumulated pauses: 18920 ms, max pause: 18390 ms, pauses over 1000 ms: 1
02:18:05, accumulated pauses: 879 ms, max pause: 189 ms, pauses over 1000 ms: 0
02:18:10, accumulated pauses: 4739 ms, max pause: 2095 ms, pauses over 1000 ms: 1
02:18:15, accumulated pauses: 4469 ms, max pause: 180 ms, pauses over 1000 ms: 0
02:18:20, accumulated pauses: 4619 ms, max pause: 1090 ms, pauses over 1000 ms: 1
02:18:25, accumulated pauses: 4369 ms, max pause: 101 ms, pauses over 1000 ms: 0
02:18:30, accumulated pauses: 4639 ms, max pause: 1590 ms, pauses over 1000 ms: 1
02:18:35, accumulated pauses: 4579 ms, max pause: 1407 ms, pauses over 1000 ms: 1
02:18:40, accumulated pauses: 4599 ms, max pause: 889 ms, pauses over 1000 ms: 0
02:18:45, accumulated pauses: 4749 ms, max pause: 2003 ms, pauses over 1000 ms: 1
02:18:50, accumulated pauses: 4729 ms, max pause: 2989 ms, pauses over 1000 ms: 1
02:18:55, accumulated pauses: 4499 ms, max pause: 700 ms, pauses over 1000 ms: 0
02:19:00, accumulated pauses: 12380 ms, max pause: 12290 ms, pauses over 1000 ms: 1
02:19:10, accumulated pauses: 2569 ms, max pause: 2389 ms, pauses over 1000 ms: 1
02:19:15, accumulated pauses: 4473 ms, max pause: 994 ms, pauses over 1000 ms: 0
02:19:20, accumulated pauses: 4485 ms, max pause: 290 ms, pauses over 1000 ms: 0
02:19:25, accumulated pauses: 90 ms, max pause: 90 ms, pauses over 1000 ms: 0
02:19:30, accumulated pauses: 15139 ms, max pause: 9579 ms, pauses over 1000 ms: 2
02:19:40, accumulated pauses: 4394 ms, max pause: 2779 ms, pauses over 1000 ms: 1
02:19:45, accumulated pauses: 5286 ms, max pause: 2297 ms, pauses over 1000 ms: 2
02:19:50, accumulated pauses: 4139 ms, max pause: 3090 ms, pauses over 1000 ms: 1
02:19:55, accumulated pauses: 29154 ms, max pause: 27795 ms, pauses over 1000 ms: 1
02:20:20, accumulated pauses: 3165 ms, max pause: 2810 ms, pauses over 1000 ms: 1
02:20:25, accumulated pauses: 69 ms, max pause: 69 ms, pauses over 1000 ms: 0
02:20:35, accumulated pauses: 42690 ms, max pause: 42690 ms, pauses over 1000 ms: 1
02:21:10, accumulated pauses: 4569 ms, max pause: 1987 ms, pauses over 1000 ms: 2
02:21:15, accumulated pauses: 4049 ms, max pause: 2990 ms, pauses over 1000 ms: 1
02:21:25, accumulated pauses: 12593 ms, max pause: 12593 ms, pauses over 1000 ms: 1
02:21:30, accumulated pauses: 22757 ms, max pause: 21569 ms, pauses over 1000 ms: 2
02:21:50, accumulated pauses: 1603 ms, max pause: 1603 ms, pauses over 1000 ms: 1
02:21:55, accumulated pauses: 16995 ms, max pause: 15090 ms, pauses over 1000 ms: 1
02:22:10, accumulated pauses: 89 ms, max pause: 89 ms, pauses over 1000 ms: 0
02:22:15, accumulated pauses: 5919 ms, max pause: 4690 ms, pauses over 1000 ms: 1
02:22:20, accumulated pauses: 4459 ms, max pause: 90 ms, pauses over 1000 ms: 0
02:22:25, accumulated pauses: 4489 ms, max pause: 895 ms, pauses over 1000 ms: 0
02:22:30, accumulated pauses: 4774 ms, max pause: 2179 ms, pauses over 1000 ms: 1
02:22:35, accumulated pauses: 4474 ms, max pause: 1790 ms, pauses over 1000 ms: 1
02:22:40, accumulated pauses: 4569 ms, max pause: 889 ms, pauses over 1000 ms: 0
02:22:45, accumulated pauses: 5223 ms, max pause: 1092 ms, pauses over 1000 ms: 1
02:22:50, accumulated pauses: 4275 ms, max pause: 1990 ms, pauses over 1000 ms: 1
02:22:55, accumulated pauses: 6943 ms, max pause: 2790 ms, pauses over 1000 ms: 1
02:23:00, accumulated pauses: 2176 ms, max pause: 489 ms, pauses over 1000 ms: 0
02:23:05, accumulated pauses: 4509 ms, max pause: 1579 ms, pauses over 1000 ms: 1
02:23:10, accumulated pauses: 4599 ms, max pause: 1194 ms, pauses over 1000 ms: 2
02:23:15, accumulated pauses: 3802 ms, max pause: 1292 ms, pauses over 1000 ms: 2
02:23:20, accumulated pauses: 5767 ms, max pause: 2579 ms, pauses over 1000 ms: 2
02:23:25, accumulated pauses: 5879 ms, max pause: 1689 ms, pauses over 1000 ms: 2
02:23:30, accumulated pauses: 3149 ms, max pause: 990 ms, pauses over 1000 ms: 0
02:23:35, accumulated pauses: 9040 ms, max pause: 5000 ms, pauses over 1000 ms: 1
02:23:40, accumulated pauses: 729 ms, max pause: 164 ms, pauses over 1000 ms: 0
02:23:45, accumulated pauses: 3859 ms, max pause: 179 ms, pauses over 1000 ms: 0
02:23:50, accumulated pauses: 4439 ms, max pause: 104 ms, pauses over 1000 ms: 0
02:23:55, accumulated pauses: 4763 ms, max pause: 793 ms, pauses over 1000 ms: 0
02:24:00, accumulated pauses: 4455 ms, max pause: 1386 ms, pauses over 1000 ms: 1
02:24:05, accumulated pauses: 7288 ms, max pause: 5998 ms, pauses over 1000 ms: 1
02:24:10, accumulated pauses: 2190 ms, max pause: 402 ms, pauses over 1000 ms: 0
02:24:15, accumulated pauses: 4230 ms, max pause: 2190 ms, pauses over 1000 ms: 1
02:24:20, accumulated pauses: 5169 ms, max pause: 700 ms, pauses over 1000 ms: 0
02:24:25, accumulated pauses: 3410 ms, max pause: 497 ms, pauses over 1000 ms: 0
02:24:30, accumulated pauses: 5794 ms, max pause: 2480 ms, pauses over 1000 ms: 2
02:24:35, accumulated pauses: 5074 ms, max pause: 5074 ms, pauses over 1000 ms: 1
02:24:40, accumulated pauses: 4599 ms, max pause: 791 ms, pauses over 1000 ms: 0
02:24:45, accumulated pauses: 4644 ms, max pause: 404 ms, pauses over 1000 ms: 0
02:24:50, accumulated pauses: 4515 ms, max pause: 1190 ms, pauses over 1000 ms: 1
02:24:55, accumulated pauses: 5104 ms, max pause: 2080 ms, pauses over 1000 ms: 1
02:25:00, accumulated pauses: 2675 ms, max pause: 1480 ms, pauses over 1000 ms: 2
02:25:05, accumulated pauses: 7065 ms, max pause: 4204 ms, pauses over 1000 ms: 2
02:25:10, accumulated pauses: 3882 ms, max pause: 3882 ms, pauses over 1000 ms: 1
02:25:15, accumulated pauses: 5540 ms, max pause: 1801 ms, pauses over 1000 ms: 2
02:25:20, accumulated pauses: 6779 ms, max pause: 5090 ms, pauses over 1000 ms: 1
02:25:25, accumulated pauses: 3960 ms, max pause: 1489 ms, pauses over 1000 ms: 3
02:25:30, accumulated pauses: 3618 ms, max pause: 689 ms, pauses over 1000 ms: 0
02:25:35, accumulated pauses: 4138 ms, max pause: 2598 ms, pauses over 1000 ms: 1
02:25:40, accumulated pauses: 3310 ms, max pause: 3310 ms, pauses over 1000 ms: 1
02:25:45, accumulated pauses: 7150 ms, max pause: 5264 ms, pauses over 1000 ms: 1
02:25:50, accumulated pauses: 1855 ms, max pause: 807 ms, pauses over 1000 ms: 0
```

**Comment by lazerion** [comment]
it also fails on `Hazelcast-4.master-OracleJDK10` [Build #72 (Mar 9, 2020 6:03:03 AM)](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-4.master-OracleJDK10/72/testReport/junit/com.hazelcast.client.cache.impl.nearcache/ClientCacheNearCacheCacheOnUpdateTest/with_invalidate_policy_concurrently_updated_near_cache_causes_misses/)

**Comment by lazerion** [comment]
- Another test failure in same class [Build #74 (Mar 23, 2020 6:03:02 AM)](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-4.master-OracleJDK10/74/testReport/junit/com.hazelcast.client.cache.impl.nearcache/ClientCacheNearCacheCacheOnUpdateTest/with_cacheOnUpdate_policy_concurrently_updated_near_cache_does_not_cause_any_miss/) with crazy hiccups
```
06:49:20, accumulated pauses: 4369 ms, max pause: 96 ms, pauses over 1000 ms: 0
06:49:25, accumulated pauses: 4419 ms, max pause: 190 ms, pauses over 1000 ms: 0
06:49:30, accumulated pauses: 4409 ms, max pause: 94 ms, pauses over 1000 ms: 0
06:49:35, accumulated pauses: 4559 ms, max pause: 890 ms, pauses over 1000 ms: 0
06:49:40, accumulated pauses: 4549 ms, max pause: 789 ms, pauses over 1000 ms: 0
06:49:45, accumulated pauses: 4349 ms, max pause: 790 ms, pauses over 1000 ms: 0
```

```
com.hazelcast.client.cache.impl.nearcache.ClientCacheNearCacheCacheOnUpdateTest.with_cacheOnUpdate_policy_concurrently_updated_near_cache_does_not_cause_any_miss
```
FYI

**Comment by ahmetmircik** [comment]
closed in https://github.com/hazelcast/hazelcast/pull/16880

**Comment by ahmetmircik** [comment]
Not failing for a long time, closing until next failure.
