### ISSUE TITLE
com.hazelcast.client.protocol.CodecHashTest.testCustomCodecHashCodes test failure

### ISSUE THREAD

**Issue by Holmistr** [hazelcast/hazelcast#16426]
Failed on PR builder: http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/5418/testReport/junit/com.hazelcast.client.protocol/CodecHashTest/testCustomCodecHashCodes/

Stacktrace:
```
org.junit.ComparisonFailure: WanReplicationRefCodec.java modified by hand. Instead, use hazelcast-client-protocol to generate this codec. Cause: Hash code does not match with the file content. expected:<[8629644303b63ded181a2ecede9b644e]> but was:<[2722184084b59d2f9a2c4326cca74a88]>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at com.hazelcast.client.protocol.CodecHashTest.testCodecsInternal(CodecHashTest.java:78)
	at com.hazelcast.client.protocol.CodecHashTest.testCustomCodecHashCodes(CodecHashTest.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by sancar** [comment]
fixed via https://github.com/hazelcast/hazelcast/pull/16414
