### ISSUE TITLE
HDLocalIndexStatsTest.testInsertsTracking

### ISSUE THREAD

**Issue by vojtechtoman** [hazelcast/hazelcast#16457]
Test failed in my private Jenkins build:

http://jenkins.hazelcast.com/job/vojtech-Hazelcast-EE/ws/hazelcast-enterprise/hazelcast-enterprise/target/surefire-reports/com.hazelcast.map.HDLocalIndexStatsTest.txt
http://jenkins.hazelcast.com/job/vojtech-Hazelcast-EE/ws/hazelcast-enterprise/hazelcast-enterprise/target/surefire-reports/com.hazelcast.map.HDLocalIndexStatsTest-output.txt

```
-------------------------------------------------------------------------------
Test set: com.hazelcast.map.HDLocalIndexStatsTest
-------------------------------------------------------------------------------
Tests run: 18, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 15.755 s <<< FAILURE! - in com.hazelcast.map.HDLocalIndexStatsTest
testInsertsTracking[format:NATIVE](com.hazelcast.map.HDLocalIndexStatsTest)  Time elapsed: 7.512 s  <<< FAILURE!
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.map.LocalIndexStatsTest.testInsertsTracking(LocalIndexStatsTest.java:457)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.lang.Thread.run(Thread.java:818)

Hiccups measured while running test 'testInsertsTracking[format:NATIVE](com.hazelcast.map.HDLocalIndexStatsTest):'
12:51:15, accumulated pauses: 834 ms, max pause: 177 ms, pauses over 1000 ms: 0
12:51:20, accumulated pauses: 622 ms, max pause: 183 ms, pauses over 1000 ms: 0
```

stdout: 
```
12:51:16,267  INFO |testInsertsTracking[format:NATIVE]| - [MetricsConfigHelper] Thread-3801 - [LOCAL] [dev] [4.0-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
12:51:16,268  INFO |testInsertsTracking[format:NATIVE]| - [system] Thread-3801 - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] Hazelcast Enterprise 4.0-SNAPSHOT (20200109 - 389a02c, 0d0caf9) starting at [127.0.0.1]:5701
12:51:16,268  INFO |testInsertsTracking[format:NATIVE]| - [system] Thread-3801 - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] Copyright (c) 2008-2020, Hazelcast, Inc. All Rights Reserved.
12:51:16,268  INFO |testInsertsTracking[format:NATIVE]| - [NodeExtension] Thread-3801 - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] Checking Hazelcast Enterprise license...
12:51:16,268  INFO |testInsertsTracking[format:NATIVE]| - [NodeExtension] Thread-3801 - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] License{allowedNumberOfNodes=99, expiryDate=08/11/2099 23:59:59, featureList=[ Management Center, Clustered JMX, Clustered Rest, Security, Wan Replication, High Density Memory, Hot Restart, Rolling Upgrade, Cluster Client Filtering ], type=Enterprise HD, companyName=null, ownerEmail=null, keyHash=OsLh4O6vqDuKhn8lOANQuuAaRnmDf8fRPrFSEhA7T3Y=, No Version Restriction}
12:51:16,268  INFO |testInsertsTracking[format:NATIVE]| - [NodeExtension] Thread-3801 - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] Creating STANDARD native memory manager with 32 MB size
12:51:16,271  INFO |testInsertsTracking[format:NATIVE]| - [MetricsConfigHelper] Thread-3801 - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
12:51:16,271  INFO |testInsertsTracking[format:NATIVE]| - [BackpressureRegulator] Thread-3801 - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] Backpressure is disabled
12:51:16,504  WARN |testInsertsTracking[format:NATIVE]| - [CPSubsystem] Thread-3801 - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
12:51:16,508  INFO |testInsertsTracking[format:NATIVE]| - [OperationExecutorImpl] Thread-3801 - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] Starting 72 partition threads and 37 generic threads (1 dedicated for priority tasks)
12:51:21,358  INFO |testInsertsTracking[format:NATIVE]| - [Diagnostics] Thread-3801 - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
12:51:21,358  INFO |testInsertsTracking[format:NATIVE]| - [LifecycleService] Thread-3801 - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] [127.0.0.1]:5701 is STARTING
12:51:21,358  INFO |testInsertsTracking[format:NATIVE]| - [ClusterService] Thread-3801 - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] 
12:51:21,359  INFO |testInsertsTracking[format:NATIVE]| - [ManagementCenterService] Thread-3801 - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] Hazelcast is ready for communication with Hazelcast Management Center
12:51:21,359  INFO |testInsertsTracking[format:NATIVE]| - [LifecycleService] Thread-3801 - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] [127.0.0.1]:5701 is STARTED
12:51:21,363  INFO |testInsertsTracking[format:NATIVE]| - [HealthMonitor] hz.happy_driscoll.HealthMonitor - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] processors=72, physical.memory.total=377.6G, physical.memory.free=79.3G, swap.space.total=4.0G, swap.space.free=3.9G, heap.memory.used=518.2M, heap.memory.free=505.8M, heap.memory.total=1024.0M, heap.memory.max=1024.0M, heap.memory.used/total=50.60%, heap.memory.used/max=50.60%, native.memory.used=0, native.memory.free=32.0M, native.memory.total=0, native.memory.max=32.0M, minor.gc.count=0, minor.gc.time=0ms, major.gc.count=0, major.gc.time=0ms, unknown.gc.count=2223, unknown.gc.time=43252ms, load.process=2.37%, load.system=100.00%, load.systemAverage=349.60, thread.count=2348, thread.peakCount=13338, cluster.timeDiff=0, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=0, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=2, clientEndpoint.count=0, connection.active.count=0, client.connection.count=0, connection.count=0
12:51:21,365  INFO |testInsertsTracking[format:NATIVE]| - [PartitionStateManager] testInsertsTracking - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] Initializing cluster partition table arrangement...
12:51:23,717  INFO |testInsertsTracking[format:NATIVE]| - [LifecycleService] Thread-3801 - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
12:51:23,719  WARN |testInsertsTracking[format:NATIVE]| - [Node] Thread-3801 - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] Terminating forcefully...
12:51:23,719  INFO |testInsertsTracking[format:NATIVE]| - [Node] Thread-3801 - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] Shutting down connection manager...
12:51:23,719  INFO |testInsertsTracking[format:NATIVE]| - [Node] Thread-3801 - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] Shutting down node engine...
12:51:23,857  INFO |testInsertsTracking[format:NATIVE]| - [NodeExtension] Thread-3801 - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] Destroying node NodeExtension.
12:51:23,863  INFO |testInsertsTracking[format:NATIVE]| - [Node] Thread-3801 - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] Hazelcast Shutdown is completed in 144 ms.
12:51:23,863  INFO |testInsertsTracking[format:NATIVE]| - [LifecycleService] Thread-3801 - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
BuildInfo right after testInsertsTracking[format:NATIVE](com.hazelcast.map.HDLocalIndexStatsTest): BuildInfo{version='4.0-SNAPSHOT', build='20200109', buildNumber=20200109, revision=389a02c, enterprise=true, serializationVersion=1, upstream=BuildInfo{version='4.0-SNAPSHOT', build='20200109', buildNumber=20200109, revision=0d0caf9, enterprise=false, serializationVersion=1}}
Finished Running Test: testInsertsTracking[format:NATIVE] in 7.690 seconds.
```

**Comment by mmedenjak** [comment]
Caused by https://github.com/hazelcast/hazelcast/pull/16367?

**Comment by vojtechtoman** [comment]
Inserting artificial small hiccups into the `LocalMapStatsProvider` code can cause all sorts of similar failures, for instance:

```
java.lang.AssertionError: 
Expected :62
Actual   :61
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.map.LocalIndexStatsTest.testInsertsTracking(LocalIndexStatsTest.java:456)
	at com.hazelcast.map.HDLocalIndexStatsTest.testInsertsTracking(HDLocalIndexStatsTest.java:54)
	...
```

Still not clear to me whether this is by design and the test is racy, or whether it's an actual issue.

**Comment by vojtechtoman** [comment]
Seems like a problem with the thread-safety of `LocalMapStatsImpl#updateIndexStats`, namely this piece of check-then-act code:

```java
LocalIndexStatsImpl indexStats = mutableIndexStats.get(indexName);
if (indexStats == null) {
    indexStats = new LocalIndexStatsImpl();
    indexStats.setAllFrom(freshIndexEntry.getValue());
    mutableIndexStats.putIfAbsent(indexName, indexStats);
} else {
    indexStats.setAllFrom(freshIndexEntry.getValue());
}
```
If the scheduled `MetricsPublisher` thread enters this block concurrently with the test (at the moment it is requesting the local index stats), all sorts of race conditions may occur, from losing the latest stats (by inserting obsolete `indexStats` into `mutableIndexStats`) to getting undefined stats (calling `indexStats#setAllFrom` concurrently).

**Comment by vojtechtoman** [comment]
This may be a more general issue with other `get*Stats()` that collect statistics on demand but not in a thread-safe way - a concurrent thread (such as the periodic metrics collection) doing the same may interfere.
