### ISSUE TITLE
CacheExpirationTest.test_whenEntryIsRemovedBackupIsCleaned[useSyncBackups:true]

### ISSUE THREAD

**Issue by mdumandag** [hazelcast/hazelcast#16465]
Failed on a PR builder http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/5501/testReport/junit/com.hazelcast.cache.eviction/CacheExpirationTest/test_whenEntryIsRemovedBackupIsCleaned_useSyncBackups_true_/

Output
```
Error Message
Expected to remove entry 0 but entry was not present. Expired entry count: 1
Stacktrace
java.lang.AssertionError: Expected to remove entry 0 but entry was not present. Expired entry count: 1
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.cache.eviction.CacheExpirationTest.test_whenEntryIsRemovedBackupIsCleaned(CacheExpirationTest.java:310)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Standard Output
Finished Running Test: testBackupsAreEmptyAfterExpiration[useSyncBackups:true] in 2.828 seconds.
10:07:47,488  INFO |test_whenEntryIsRemovedBackupIsCleaned[useSyncBackups:true]| - [InvocationMonitor] hz.upbeat_bell.InvocationMonitorThread - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] Invocations:1 timeouts:0 backup-timeouts:1
10:07:47,650  INFO |test_whenEntryIsRemovedBackupIsCleaned[useSyncBackups:true]| - [CacheService] Thread-152 - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] Removed cache config: CacheConfig{name='34fd03a9-4563-4304-a490-a0419175d508', managerPrefix='/hz/', inMemoryFormat=BINARY, backupCount=1, hotRestart=HotRestartConfig{enabled=false, fsync=false}, wanReplicationRef=null}
10:07:47,651  INFO |test_whenEntryIsRemovedBackupIsCleaned[useSyncBackups:true]| - [CacheService] hz.jovial_bell.generic-operation.thread-1 - [127.0.0.1]:5702 [dev] [4.0-SNAPSHOT] Removed cache config: CacheConfig{name='34fd03a9-4563-4304-a490-a0419175d508', managerPrefix='/hz/', inMemoryFormat=BINARY, backupCount=1, hotRestart=HotRestartConfig{enabled=false, fsync=false}, wanReplicationRef=null}
10:07:47,651  INFO |test_whenEntryIsRemovedBackupIsCleaned[useSyncBackups:true]| - [LifecycleService] Thread-152 - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
10:07:47,652  INFO |test_whenEntryIsRemovedBackupIsCleaned[useSyncBackups:true]| - [MigrationManager] hz.upbeat_bell.cached.thread-3 - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] Shutdown request of Member [127.0.0.1]:5701 - 9d5a4977-2955-4e34-8a1c-b23a26ca51b9 this is handled
10:07:47,749  INFO |test_whenEntryIsRemovedBackupIsCleaned[useSyncBackups:true]| - [MigrationManager] hz.upbeat_bell.migration - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] Repartitioning cluster data. Migration tasks count: 6
10:07:47,773  INFO |test_whenEntryIsRemovedBackupIsCleaned[useSyncBackups:true]| - [Node] Thread-152 - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] Shutting down connection manager...
10:07:47,773  INFO |test_whenEntryIsRemovedBackupIsCleaned[useSyncBackups:true]| - [MockNetworkingService] Thread-152 - [127.0.0.1]:5702 [dev] [4.0-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5701, connection: MockConnection{localEndpoint=[127.0.0.1]:5702, remoteEndpoint=[127.0.0.1]:5701, alive=false}
10:07:47,773  INFO |test_whenEntryIsRemovedBackupIsCleaned[useSyncBackups:true]| - [MockNetworkingService] Thread-152 - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5702, connection: MockConnection{localEndpoint=[127.0.0.1]:5701, remoteEndpoint=[127.0.0.1]:5702, alive=false}
10:07:47,773  WARN |test_whenEntryIsRemovedBackupIsCleaned[useSyncBackups:true]| - [MembershipManager] Thread-152 - [127.0.0.1]:5702 [dev] [4.0-SNAPSHOT] Member [127.0.0.1]:5701 - 9d5a4977-2955-4e34-8a1c-b23a26ca51b9 is suspected to be dead for reason: Connection manager is stopped on Member [127.0.0.1]:5701 - 9d5a4977-2955-4e34-8a1c-b23a26ca51b9 this
10:07:47,773  INFO |test_whenEntryIsRemovedBackupIsCleaned[useSyncBackups:true]| - [MembershipManager] Thread-152 - [127.0.0.1]:5702 [dev] [4.0-SNAPSHOT] Starting mastership claim process...
10:07:47,773  INFO |test_whenEntryIsRemovedBackupIsCleaned[useSyncBackups:true]| - [MembershipManager] Thread-152 - [127.0.0.1]:5702 [dev] [4.0-SNAPSHOT] Local MembersView{version=2, members=[MemberInfo{address=[127.0.0.1]:5701, uuid=9d5a4977-2955-4e34-8a1c-b23a26ca51b9, liteMember=false, memberListJoinVersion=1}, MemberInfo{address=[127.0.0.1]:5702, uuid=8773221b-3f4b-4cba-bfd7-f1ab2d8b93fb, liteMember=false, memberListJoinVersion=2}]} with suspected members: [[127.0.0.1]:5701] and initial addresses to ask: []
10:07:47,773  INFO |test_whenEntryIsRemovedBackupIsCleaned[useSyncBackups:true]| - [Node] Thread-152 - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] Shutting down node engine...
10:07:47,773  WARN |test_whenEntryIsRemovedBackupIsCleaned[useSyncBackups:true]| - [OutboundResponseHandler] hz.jovial_bell.generic-operation.thread-1 - [127.0.0.1]:5702 [dev] [4.0-SNAPSHOT] Cannot send response: true to [127.0.0.1]:5701. com.hazelcast.internal.partition.operation.PublishCompletedMigrationsOperation{serviceName='hz:core:partitionService', identityHash=748755723, partitionId=-1, replicaIndex=0, callId=39, invocationTime=1578650867772 (2020-01-10 10:07:47.772), waitTimeout=-1, callTimeout=60000}
10:07:47,776  INFO |test_whenEntryIsRemovedBackupIsCleaned[useSyncBackups:true]| - [TransactionManagerService] hz.jovial_bell.cached.thread-7 - [127.0.0.1]:5702 [dev] [4.0-SNAPSHOT] Committing/rolling-back live transactions of [127.0.0.1]:5701, UUID: 9d5a4977-2955-4e34-8a1c-b23a26ca51b9
10:07:47,775  INFO |test_whenEntryIsRemovedBackupIsCleaned[useSyncBackups:true]| - [ClusterService] hz.jovial_bell.cached.thread-3 - [127.0.0.1]:5702 [dev] [4.0-SNAPSHOT] 

Members {size:1, ver:3} [
	Member [127.0.0.1]:5702 - 8773221b-3f4b-4cba-bfd7-f1ab2d8b93fb this
]

10:07:47,783  INFO |test_whenEntryIsRemovedBackupIsCleaned[useSyncBackups:true]| - [MembershipManager] hz.jovial_bell.cached.thread-3 - [127.0.0.1]:5702 [dev] [4.0-SNAPSHOT] Mastership is claimed with: MembersView{version=3, members=[MemberInfo{address=[127.0.0.1]:5702, uuid=8773221b-3f4b-4cba-bfd7-f1ab2d8b93fb, liteMember=false, memberListJoinVersion=2}]}
10:07:47,877  INFO |testSimpleExpiration_getAndPutAsync[useSyncBackups:true]| - [CacheService] Thread-157 - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] Removed cache config: CacheConfig{name='7b55239d-1706-4d48-be4e-ff9e2683ba49', managerPrefix='/hz/', inMemoryFormat=BINARY, backupCount=1, hotRestart=HotRestartConfig{enabled=false, fsync=false}, wanReplicationRef=null}
10:07:47,877  INFO |testSimpleExpiration_getAndPutAsync[useSyncBackups:true]| - [CacheService] hz.quizzical_bell.generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [4.0-SNAPSHOT] Removed cache config: CacheConfig{name='7b55239d-1706-4d48-be4e-ff9e2683ba49', managerPrefix='/hz/', inMemoryFormat=BINARY, backupCount=1, hotRestart=HotRestartConfig{enabled=false, fsync=false}, wanReplicationRef=null}
10:07:47,878  INFO |testSimpleExpiration_getAndPutAsync[useSyncBackups:true]| - [LifecycleService] Thread-157 - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
10:07:47,878  INFO |testSimpleExpiration_getAndPutAsync[useSyncBackups:true]| - [MigrationManager] hz.nifty_bell.cached.thread-6 - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] Shutdown request of Member [127.0.0.1]:5701 - 7843e3ac-1453-4d34-8afe-df1132246625 this is handled
10:07:47,972  INFO |testSimpleExpiration_getAndPutAsync[useSyncBackups:true]| - [MigrationManager] hz.nifty_bell.migration - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] Repartitioning cluster data. Migration tasks count: 5
10:07:48,008  INFO |testSimpleExpiration_getAndPutAsync[useSyncBackups:true]| - [Node] Thread-157 - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] Shutting down connection manager...
10:07:48,008  INFO |testSimpleExpiration_getAndPutAsync[useSyncBackups:true]| - [MockNetworkingService] Thread-157 - [127.0.0.1]:5702 [dev] [4.0-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5701, connection: MockConnection{localEndpoint=[127.0.0.1]:5702, remoteEndpoint=[127.0.0.1]:5701, alive=false}
10:07:48,008  WARN |testSimpleExpiration_getAndPutAsync[useSyncBackups:true]| - [OutboundResponseHandler] hz.quizzical_bell.priority-generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [4.0-SNAPSHOT] Cannot send response: true to [127.0.0.1]:5701. com.hazelcast.internal.partition.operation.PublishCompletedMigrationsOperation{serviceName='hz:core:partitionService', identityHash=1579828041, partitionId=-1, replicaIndex=0, callId=33, invocationTime=1578650868007 (2020-01-10 10:07:48.007), waitTimeout=-1, callTimeout=60000}
10:07:48,008  INFO |testSimpleExpiration_getAndPutAsync[useSyncBackups:true]| - [MockNetworkingService] Thread-157 - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5702, connection: MockConnection{localEndpoint=[127.0.0.1]:5701, remoteEndpoint=[127.0.0.1]:5702, alive=false}
10:07:48,008  INFO |test_whenEntryIsRemovedBackupIsCleaned[useSyncBackups:true]| - [NodeExtension] Thread-152 - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] Destroying node NodeExtension.
10:07:48,008  WARN |testSimpleExpiration_getAndPutAsync[useSyncBackups:true]| - [MembershipManager] Thread-157 - [127.0.0.1]:5702 [dev] [4.0-SNAPSHOT] Member [127.0.0.1]:5701 - 7843e3ac-1453-4d34-8afe-df1132246625 is suspected to be dead for reason: Connection manager is stopped on Member [127.0.0.1]:5701 - 7843e3ac-1453-4d34-8afe-df1132246625 this
10:07:48,008  INFO |testSimpleExpiration_getAndPutAsync[useSyncBackups:true]| - [MembershipManager] Thread-157 - [127.0.0.1]:5702 [dev] [4.0-SNAPSHOT] Starting mastership claim process...
10:07:48,009  INFO |test_whenEntryIsRemovedBackupIsCleaned[useSyncBackups:true]| - [Node] Thread-152 - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] Hazelcast Shutdown is completed in 358 ms.
10:07:48,009  INFO |test_whenEntryIsRemovedBackupIsCleaned[useSyncBackups:true]| - [LifecycleService] Thread-152 - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
10:07:48,009  INFO |test_whenEntryIsRemovedBackupIsCleaned[useSyncBackups:true]| - [LifecycleService] Thread-152 - [127.0.0.1]:5702 [dev] [4.0-SNAPSHOT] [127.0.0.1]:5702 is SHUTTING_DOWN
10:07:48,009  INFO |test_whenEntryIsRemovedBackupIsCleaned[useSyncBackups:true]| - [MigrationManager] hz.jovial_bell.cached.thread-9 - [127.0.0.1]:5702 [dev] [4.0-SNAPSHOT] Shutdown request of Member [127.0.0.1]:5702 - 8773221b-3f4b-4cba-bfd7-f1ab2d8b93fb this is handled
10:07:48,009  INFO |testSimpleExpiration_getAndPutAsync[useSyncBackups:true]| - [MembershipManager] Thread-157 - [127.0.0.1]:5702 [dev] [4.0-SNAPSHOT] Local MembersView{version=2, members=[MemberInfo{address=[127.0.0.1]:5701, uuid=7843e3ac-1453-4d34-8afe-df1132246625, liteMember=false, memberListJoinVersion=1}, MemberInfo{address=[127.0.0.1]:5702, uuid=fc097e63-2f95-42e6-aa24-ce7d8545a705, liteMember=false, memberListJoinVersion=2}]} with suspected members: [[127.0.0.1]:5701] and initial addresses to ask: []
10:07:48,009  INFO |testSimpleExpiration_getAndPutAsync[useSyncBackups:true]| - [Node] Thread-157 - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] Shutting down node engine...
10:07:48,011  INFO |testSimpleExpiration_getAndPutAsync[useSyncBackups:true]| - [ClusterService] hz.quizzical_bell.cached.thread-3 - [127.0.0.1]:5702 [dev] [4.0-SNAPSHOT] 

Members {size:1, ver:3} [
	Member [127.0.0.1]:5702 - fc097e63-2f95-42e6-aa24-ce7d8545a705 this
]

10:07:48,011  INFO |testSimpleExpiration_getAndPutAsync[useSyncBackups:true]| - [MembershipManager] hz.quizzical_bell.cached.thread-3 - [127.0.0.1]:5702 [dev] [4.0-SNAPSHOT] Mastership is claimed with: MembersView{version=3, members=[MemberInfo{address=[127.0.0.1]:5702, uuid=fc097e63-2f95-42e6-aa24-ce7d8545a705, liteMember=false, memberListJoinVersion=2}]}
10:07:48,012  INFO |testSimpleExpiration_getAndPutAsync[useSyncBackups:true]| - [TransactionManagerService] hz.quizzical_bell.cached.thread-2 - [127.0.0.1]:5702 [dev] [4.0-SNAPSHOT] Committing/rolling-back live transactions of [127.0.0.1]:5701, UUID: 7843e3ac-1453-4d34-8afe-df1132246625
10:07:48,015  INFO |testSimpleExpiration_getAndPutAsync[useSyncBackups:true]| - [NodeExtension] Thread-157 - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] Destroying node NodeExtension.
10:07:48,025  INFO |testSimpleExpiration_getAndPutAsync[useSyncBackups:true]| - [Node] Thread-157 - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] Hazelcast Shutdown is completed in 147 ms.
10:07:48,025  INFO |test_whenEntryIsRemovedBackupIsCleaned[useSyncBackups:true]| - [InternalPartitionService] hz.jovial_bell.migration - [127.0.0.1]:5702 [dev] [4.0-SNAPSHOT] Fetching most recent partition table! my version: 40
10:07:48,025  INFO |testSimpleExpiration_getAndPutAsync[useSyncBackups:true]| - [LifecycleService] Thread-157 - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
10:07:48,025  INFO |test_whenEntryIsRemovedBackupIsCleaned[useSyncBackups:true]| - [InternalPartitionService] hz.jovial_bell.migration - [127.0.0.1]:5702 [dev] [4.0-SNAPSHOT] Most recent partition table version: 40
10:07:48,026  INFO |testSimpleExpiration_getAndPutAsync[useSyncBackups:true]| - [LifecycleService] Thread-157 - [127.0.0.1]:5702 [dev] [4.0-SNAPSHOT] [127.0.0.1]:5702 is SHUTTING_DOWN
10:07:48,026  INFO |testSimpleExpiration_getAndPutAsync[useSyncBackups:true]| - [MigrationManager] hz.quizzical_bell.cached.thread-4 - [127.0.0.1]:5702 [dev] [4.0-SNAPSHOT] Shutdown request of Member [127.0.0.1]:5702 - fc097e63-2f95-42e6-aa24-ce7d8545a705 this is handled
10:07:48,030  INFO |test_whenEntryIsRemovedBackupIsCleaned[useSyncBackups:true]| - [Node] Thread-152 - [127.0.0.1]:5702 [dev] [4.0-SNAPSHOT] Shutting down connection manager...
10:07:48,030  INFO |test_whenEntryIsRemovedBackupIsCleaned[useSyncBackups:true]| - [Node] Thread-152 - [127.0.0.1]:5702 [dev] [4.0-SNAPSHOT] Shutting down node engine...
10:07:48,037  INFO |test_whenEntryIsRemovedBackupIsCleaned[useSyncBackups:true]| - [NodeExtension] Thread-152 - [127.0.0.1]:5702 [dev] [4.0-SNAPSHOT] Destroying node NodeExtension.
10:07:48,038  INFO |test_whenEntryIsRemovedBackupIsCleaned[useSyncBackups:true]| - [Node] Thread-152 - [127.0.0.1]:5702 [dev] [4.0-SNAPSHOT] Hazelcast Shutdown is completed in 29 ms.
10:07:48,038  INFO |test_whenEntryIsRemovedBackupIsCleaned[useSyncBackups:true]| - [LifecycleService] Thread-152 - [127.0.0.1]:5702 [dev] [4.0-SNAPSHOT] [127.0.0.1]:5702 is SHUTDOWN
10:07:48,040  INFO |test_whenEntryIsRemovedBackupIsCleaned[useSyncBackups:true]| - [LifecycleService] Thread-152 - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
10:07:48,040  INFO |test_whenEntryIsRemovedBackupIsCleaned[useSyncBackups:true]| - [Node] Thread-152 - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] Node is already shutting down... Waiting for shutdown process to complete...
10:07:48,040  INFO |test_whenEntryIsRemovedBackupIsCleaned[useSyncBackups:true]| - [LifecycleService] Thread-152 - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
BuildInfo right after test_whenEntryIsRemovedBackupIsCleaned[useSyncBackups:true](com.hazelcast.cache.eviction.CacheExpirationTest): BuildInfo{version='4.0-SNAPSHOT', build='20200110', buildNumber=20200110, revision=8434ade, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'test_whenEntryIsRemovedBackupIsCleaned[useSyncBackups:true](com.hazelcast.cache.eviction.CacheExpirationTest):'
10:07:40, accumulated pauses: 1340 ms, max pause: 356 ms, pauses over 1000 ms: 0
10:07:45, accumulated pauses: 577 ms, max pause: 113 ms, pauses over 1000 ms: 0

```

**Comment by vbekiaris** [comment]
There is nothing suspicious in the logs. It looks like >=3 seconds passed between the time the entry was [`put`](https://github.com/hazelcast/hazelcast/blob/97ff57ba92dc1fbfa77720885e7db40757999080/hazelcast/src/test/java/com/hazelcast/cache/eviction/CacheExpirationTest.java#L309) with a 3-second TTL and the next `remove` instruction failed to find the entry, as is evident from the expiration count. The hiccups do not fully account for the elapsed time, but probably there was too much load on the build machine anyway. [Around the time the cache was created](https://github.com/hazelcast/hazelcast/blob/97ff57ba92dc1fbfa77720885e7db40757999080/hazelcast/src/test/java/com/hazelcast/cache/eviction/CacheExpirationTest.java#L306) (the instruction immediately prior to the `put`) the health monitor reports:
```
10:07:41,996  INFO |test_whenEntryIsRemovedBackupIsCleaned[useSyncBackups:true]| - [HealthMonitor] hz.jovial_bell.HealthMonitor - [127.0.0.1]:5702 [dev] [4.0-SNAPSHOT] processors=72, physical.memory.total=377.6G, physical.memory.free=76.1G, swap.space.total=4.0G, swap.space.free=4.0G, heap.memory.used=501.4M, heap.memory.free=357.1M, heap.memory.total=858.5M, heap.memory.max=1.8G, heap.memory.used/total=58.29%, heap.memory.used/max=27.49%, minor.gc.count=5, minor.gc.time=820ms, major.gc.count=2, major.gc.time=805ms, load.process=3.85%, load.system=90.45%, load.systemAverage=137.68, thread.count=221, thread.peakCount=295, cluster.timeDiff=-2, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=16, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=1, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=1, clientEndpoint.count=0, connection.active.count=0, client.connection.count=0, connection.count=0
```

It is notable that the PR builder uses JDK 8u181 which is not docker-aware and reports all of the host's CPUs as available processors. Probably upgrading the JDK will ease the load on the build machine? /cc @Holmistr

**Comment by mmedenjak** [comment]
Related: https://hazelcast.slack.com/archives/G6EDCRY49/p1576680812023900

**Comment by vbekiaris** [comment]
Closing this issue; if it fails again we can consider prolonging the TTL value in the test (which will also prolong the test's execution time).

**Comment by lazerion** [comment]
- Re-opening per [Build #648 (Oct 10, 2020 9:17:00 PM)](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-4.master-sonar/648/testReport/junit/com.hazelcast.cache.eviction/CacheExpirationTest/test_whenEntryIsRemovedBackupIsCleaned_useSyncBackups_true_/) on `Hazelcast-4.master-sonar`
- Error
```
Expected to remove entry 0 but entry was not present. Expired entry count: 1
```
- Stacktrace
```
java.lang.AssertionError: Expected to remove entry 0 but entry was not present. Expired entry count: 1
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.cache.eviction.CacheExpirationTest.test_whenEntryIsRemovedBackupIsCleaned(CacheExpirationTest.java:310)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)

```
- Hiccups
```
Hiccups measured while running test 'test_whenEntryIsRemovedBackupIsCleaned[useSyncBackups:true](com.hazelcast.cache.eviction.CacheExpirationTest):'
21:25:40, accumulated pauses: 90 ms, max pause: 52 ms, pauses over 1000 ms: 0
21:25:45, accumulated pauses: 171 ms, max pause: 152 ms, pauses over 1000 ms: 0

```
- kindly check
