### ISSUE TITLE
QueryCacheNoEventLossTest.no_event_lost_during_migrations__with_many_parallel_nodes

### ISSUE THREAD

**Issue by lazerion** [hazelcast/hazelcast#16470]
- Fails on `Hazelcast-3.x-nightly`
- Fails on [this build](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-nightly/348/testReport/com.hazelcast.map.impl.querycache/QueryCacheNoEventLossTest/no_event_lost_during_migrations__with_many_parallel_nodes/)
- Error
```
expected:<0> but was:<1>
```
- Stack Trace
```
java.lang.AssertionError: expected:<0> but was:<1>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.map.impl.querycache.QueryCacheNoEventLossTest.no_event_lost_during_migrations(QueryCacheNoEventLossTest.java:123)
	at com.hazelcast.map.impl.querycache.QueryCacheNoEventLossTest.access$000(QueryCacheNoEventLossTest.java:53)
	at com.hazelcast.map.impl.querycache.QueryCacheNoEventLossTest$1.run(QueryCacheNoEventLossTest.java:74)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1356)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1458)
	at com.hazelcast.map.impl.querycache.QueryCacheNoEventLossTest.no_event_lost_during_migrations__with_many_parallel_nodes(QueryCacheNoEventLossTest.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

kindly check

**Comment by ahmetmircik** [comment]
closed by https://github.com/hazelcast/hazelcast/pull/16478
