### ISSUE TITLE
SEVERE PartitionWideEntryWithPredicateBackupOperation keyData cannot be null

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#16480]
I see lots of this exception in logs of one of tests

```
Jan 13, 2020 4:11:23 PM com.hazelcast.internal.partition.impl.MigrationManager
INFO: [10.0.0.66]:5701 [HZ] [4.0-SNAPSHOT] Repartitioning cluster data. Migration tasks count: 271
Jan 13, 2020 4:11:23 PM com.hazelcast.map.impl.operation.PartitionWideEntryWithPredicateBackupOperation
SEVERE: [10.0.0.66]:5701 [HZ] [4.0-SNAPSHOT] keyData cannot be null
java.lang.IllegalArgumentException: keyData cannot be null
	at com.hazelcast.query.impl.CachedQueryEntry.init(CachedQueryEntry.java:50)
	at com.hazelcast.map.impl.LazyMapEntry.init(LazyMapEntry.java:79)
	at com.hazelcast.map.impl.LockAwareLazyMapEntry.init(LockAwareLazyMapEntry.java:47)
	at com.hazelcast.map.impl.operation.EntryOperator.init(EntryOperator.java:148)
	at com.hazelcast.map.impl.operation.PartitionWideEntryBackupOperation.runWithPartitionScanForNative(PartitionWideEntryBackupOperation.java:87)
	at com.hazelcast.map.impl.operation.PartitionWideEntryBackupOperation.runInternal(PartitionWideEntryBackupOperation.java:48)
	at com.hazelcast.map.impl.operation.MapOperation.run(MapOperation.java:112)
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:184)
	at com.hazelcast.spi.impl.operationexecutor.OperationRunner.runDirect(OperationRunner.java:150)
	at com.hazelcast.spi.impl.operationservice.impl.operations.Backup.run(Backup.java:174)
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:184)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:220)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:209)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:425)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:157)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:127)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:114)
(edited)
```

  /disk1/jenkins/workspace/scale-up/4.0-SNAPSHOT/2020_01_13-09_30_28/stable/sql/put-remove-all

http://54.147.27.51/~jenkins/workspace/scale-up/4.0-SNAPSHOT/2020_01_13-09_30_28/stable/sql/put-remove-all/

the test is making putAll and removeAll predicate, while new members are added to the cluster.  exception starts to be logged just after 2nd member is added. (edited)

**Comment by Danny-Hazelcast** [comment]
I also see that after a member is added to the cluster never becomes "SAFE"

**Comment by Danny-Hazelcast** [comment]
/disk1/jenkins/workspace/scale-up/4.0-SNAPSHOT/2020_01_13-09_30_28/stable/processor/regular/execute-on-predicate

 http://54.147.27.51/~jenkins/workspace/scale-up/4.0-SNAPSHOT/2020_01_13-09_30_28/stable/processor/regular/execute-on-predicate

logs the same exception

**Comment by Danny-Hazelcast** [comment]
and a 3rd execute on predicate off loadable
/disk1/jenkins/workspace/scale-up/4.0-SNAPSHOT/2020_01_13-09_30_28/stable/processor/off-load/execute-on-predicate
http://54.147.27.51/~jenkins/workspace/scale-up/4.0-SNAPSHOT/2020_01_13-09_30_28/stable/processor/off-load/execute-on-predicate

**Comment by Danny-Hazelcast** [comment]
and a 4th test

```
02:37:03.214 /disk1/jenkins/workspace/scale-up/4.0-SNAPSHOT/2020_01_13-09_30_28/stable/map/remove-predicate Failed
02:37:03.216 fail HzMember2HZ untilClusterSafe hzcmd.ops.UntilClusterSafe threadId=0 global.AssertionException: isClusterSafe()=false try's=41 interval 10 [0m
02:37:03.216 fail HzMember3HZ untilClusterSafe hzcmd.ops.UntilClusterSafe threadId=0 global.AssertionException: isClusterSafe()=false try's=41 interval 10 [0m
02:37:03.216 fail HzMember4HZ untilClusterSafe hzcmd.ops.UntilClusterSafe threadId=0 global.AssertionException: isClusterSafe()=false try's=41 interval 10 [0m
02:37:03.566 http://54.147.27.51/~jenkins/workspace/scale-up/4.0-SNAPSHOT/2020_01_13-09_30_28/stable/map/remove-predicate
```

**Comment by Danny-Hazelcast** [comment]
http://jenkins.hazelcast.com/view/stable/job/scale-up/18/console
