### ISSUE TITLE
Quorum enabled="false" does not affect

### ISSUE THREAD

**Issue by gokhansari** [hazelcast/hazelcast#16507]
Declarative quorum configuration for hazelcast member has **enabled** flag. When it is **false**, I simply expect to have not split brain protection. When the cluster size is less than **quorum-size**, hazelcast client still gets **QuorumException** for the map which has reference for this quorum definition.

    <quorum name="quorumRule" enabled="false">
        <quorum-size>2</quorum-size>
        <quorum-type>READ_WRITE</quorum-type>
    </quorum>

```
com.hazelcast.quorum.QuorumException: Split brain protection exception: quorumRuleForMaps has failed!
	at com.hazelcast.quorum.impl.QuorumImpl.newQuorumException(QuorumImpl.java:262)
	at com.hazelcast.quorum.impl.QuorumImpl.ensureQuorumPresent(QuorumImpl.java:257)
	at com.hazelcast.quorum.impl.QuorumImpl.ensureQuorumPresent(QuorumImpl.java:252)
	at com.hazelcast.quorum.impl.QuorumServiceImpl.ensureQuorumPresent(QuorumServiceImpl.java:224)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.ensureQuorumPresent(OperationRunnerImpl.java:287)
```

Hazelcast version: **3.12.3**

**Comment by mdogan** [comment]
@gokhansari: Can you please post the whole configuration? Since quorum name in configuration (`<quorum name="quorumRule" ..`) and quorum name in exception message (`QuorumException: Split brain protection exception: quorumRuleForMaps has failed!`) are different.

**Comment by gokhansari** [comment]
It's just copy paste mistake. Here is full configuration:

```
<hazelcast xmlns="http://www.hazelcast.com/schema/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.hazelcast.com/schema/config http://www.hazelcast.com/schema/config/hazelcast-config-3.12.xsd">
    <group>
        <name>sample-group</name>
    </group>

    <network>
        <join>
            <multicast enabled="false"/>
            <tcp-ip enabled="false"/>
            <aws enabled="false"/>
            <gcp enabled="false"/>
            <azure enabled="false"/>
            <kubernetes enabled="false"/>

            <!--Check eureka-client.properties file for other eureka properties-->
            <eureka enabled="true">
                ...
            </eureka>

            <discovery-strategies/>
        </join>

        <interfaces enabled="true">
            <interface>192.168.*.*</interface>
        </interfaces>

        <rest-api enabled="true">
            <endpoint-group name="HEALTH_CHECK" enabled="true"/>
        </rest-api>

    </network>

    <properties>
        <property name="hazelcast.initial.min.cluster.size">1</property>
    </properties>

    <quorum name="quorumRuleForMaps" enabled="false">
        <quorum-size>2</quorum-size>
        <quorum-type>READ_WRITE</quorum-type>
    </quorum>

    <map name="map1">
        <quorum-ref>quorumRuleForMaps</quorum-ref>
        ...
        <map-store enabled="true" initial-mode="LAZY">
            <class-name>com.xxx.xxx</class-name>
            <write-delay-seconds>0</write-delay-seconds>
            <properties>
                ...
            </properties>
        </map-store>
    </map>

    <map name="map2">
        <quorum-ref>quorumRuleForMaps</quorum-ref>
        ...
        <map-store enabled="true" initial-mode="LAZY">
            <class-name>com.yyy.yyy</class-name>
            <write-delay-seconds>0</write-delay-seconds>
            <properties>
                ...
            </properties>
        </map-store>

    </map>

</hazelcast>
```

**Comment by gokhansari** [comment]
By the way, dynamically hazelcast.xml can be manipulated by external processes according to some external variables. When given **quorum-size** is **1**, disabling split brain protection might be a good option. @mdogan do you think that It's a valid request?

**Comment by mdogan** [comment]
@gokhansari: Do you mean xml config is updated dynamically while cluster is running? If that was you mean, that's not supported currently.

Otherwise, if quorum size is 1, quorum (split-brain-protection) will be effectively disabled already.

**Comment by gokhansari** [comment]
Not while cluster is running. If quorum size is **1** in xml, hazelcast member can not start. 

```
Exception in thread "main" com.hazelcast.config.InvalidConfigurationException: Minimum quorum size cannot be less than 2
	at com.hazelcast.config.QuorumConfig.setSize(QuorumConfig.java:121)
	at com.hazelcast.config.MemberDomConfigProcessor.handleQuorumNode(MemberDomConfigProcessor.java:371)
```

**Comment by mdogan** [comment]
Ah I see. Can you please create a ticket for that? It's trivial to implement but it should be discussed. We generally prefer failing fast instead of implicitly making a decision about config parameters.
