### ISSUE TITLE
Disable split-brain protection when quorum size is 1

### ISSUE THREAD

**Issue by gokhansari** [hazelcast/hazelcast#16514]
If **quorum-size** is **1** in xml, hazelcast member can not start.

**Config**:
```
<quorum name="quorumRule" enabled="true">
    <quorum-size>1</quorum-size>
    <quorum-type>READ_WRITE</quorum-type>
</quorum>
```
**Exception on startup**:
```
Exception in thread "main" com.hazelcast.config.InvalidConfigurationException: Minimum quorum size cannot be less than 2
	at com.hazelcast.config.QuorumConfig.setSize(QuorumConfig.java:121)
	at com.hazelcast.config.MemberDomConfigProcessor.handleQuorumNode(MemberDomConfigProcessor.java:371)
```
**Version**: 3.12.3

hazelcast.xml can be manipulated by external processes according to some external variables, like docker environment variables etc.. When given quorum-size is 1, **disabling split brain protection** might be a good option. Otherwise, only way to start single node is to remove quorum definition in xml, which set you struggle to handle it .

https://github.com/hazelcast/hazelcast/issues/16507

**Comment by Holmistr** [comment]
Hey @gokhansari , thanks for reporting the issue. We'll discuss this internally, whether we really want to implement it this way as @mdogan noted here: https://github.com/hazelcast/hazelcast/issues/16507#issuecomment-576620185

In the meantime, just one question. If we decide to implement this, would you like to implement it yourself and contribute it to Hazelcast codebase? It's probably quite trivial and I would be happy to point you to the correct places and give you some hints to implement it :) Just an idea, feel free to say no :)

**Comment by weaverjoel** [comment]
Hmmm

**Comment by gokhansari** [comment]
Thank you :) but I'm afraid that i can not track it. but here is the simple solution I think 

In **QuorumServiceImpl** add size control in the condition of @mdogan 
```
if (!quorumConfig.isEnabled() && quorumConfig.getSize() < 2) {
    continue;
}
```

In **QuorumConfig** remove size check lines in **setSize** method
```
if (size < 2) {
     throw new InvalidConfigurationException("Minimum quorum size cannot be less than 2");
}
```

**Comment by Holmistr** [comment]
Hi @gokhansari , no worries :) We'll find out whether we actually want to do that and then perhaps use your suggestions. If you wanted to contribute any time in the future, just ping me, happy to help.
