### ISSUE TITLE
split brain NullPointerException CompositeRangePredicate.java:120

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#16525]
```
java.lang.NullPointerException
	at com.hazelcast.query.impl.predicates.CompositeRangePredicate.filter(CompositeRangePredicate.java:120)
	at com.hazelcast.query.impl.Indexes.query(Indexes.java:325)
	at com.hazelcast.map.impl.query.QueryRunner.runPartitionIndexOrPartitionScanQueryOnGivenOwnedPartition(QueryRunner.java:196)
	at com.hazelcast.map.impl.query.QueryPartitionOperation.runInternal(QueryPartitionOperation.java:46)
	at com.hazelcast.map.impl.operation.MapOperation.run(MapOperation.java:112)
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:184)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:220)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:209)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:425)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:157)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:127)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:114)
java.lang.NullPointerException
	at com.hazelcast.query.impl.predicates.CompositeRangePredicate.filter(CompositeRangePredicate.java:120)
	at com.hazelcast.query.impl.Indexes.query(Indexes.java:325)
	at com.hazelcast.map.impl.query.QueryRunner.runPartitionIndexOrPartitionScanQueryOnGivenOwnedPartition(QueryRunner.java:196)
	at com.hazelcast.map.impl.query.QueryPartitionOperation.runInternal(QueryPartitionOperation.java:46)
	at com.hazelcast.map.impl.operation.MapOperation.run(MapOperation.java:112)
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:184)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:220)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:209)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:425)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:157)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:127)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:114)
java.lang.NullPointerException
```

from http://jenkins.hazelcast.com/view/split/job/split-x/19/console

a split brain bitmap index test,  look's like it tool a long time to hit this issue, so not easy to reproduce. (edited) 

all though is say's CompositeRangePredicate so its not bitmap's then ?

 hz-bench-run-jenkins-split hz/stress/bit-map

**Comment by petrpleshachkov** [comment]
It seems this is the issue we fixed in https://github.com/hazelcast/hazelcast/pull/16520
@Danny-Hazelcast  please try the test with the fix and close it if it works.

**Comment by mmedenjak** [comment]
Closing as fixed.
