### ISSUE TITLE
ScheduledExecutorServiceBasicTest.schedule_withLongSleepingCallable_cancelledAndGet

### ISSUE THREAD

**Issue by lazerion** [hazelcast/hazelcast#16530]
- Fails on `Hazelcast-3.maintenance-IbmJDK7`
- Fails on [this build 116 Jan 20, 2020](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.maintenance-IbmJDK7/116/testReport/junit/com.hazelcast.scheduledexecutor/ScheduledExecutorServiceBasicTest/schedule_withLongSleepingCallable_cancelledAndGet/)
- Error
```
CountDownLatch failed to complete within 120 seconds, count left: 1
```
- Stack trace
```
java.lang.AssertionError: CountDownLatch failed to complete within 120 seconds, count left: 1
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:1193)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:1182)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:1170)
	at com.hazelcast.scheduledexecutor.ScheduledExecutorServiceBasicTest.schedule_withLongSleepingCallable_cancelledAndGet(ScheduledExecutorServiceBasicTest.java:390)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:95)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:56)
	at java.lang.reflect.Method.invoke(Method.java:620)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.util.concurrent.FutureTask.run(FutureTask.java:274)
	at java.lang.Thread.run(Thread.java:809)
```

```
Hiccups measured while running test 'schedule_withLongSleepingCallable_cancelledAndGet(com.hazelcast.scheduledexecutor.ScheduledExecutorServiceBasicTest):'
07:51:00, accumulated pauses: 324 ms, max pause: 13 ms, pauses over 1000 ms: 0
07:51:05, accumulated pauses: 270 ms, max pause: 9 ms, pauses over 1000 ms: 0
07:51:10, accumulated pauses: 183 ms, max pause: 7 ms, pauses over 1000 ms: 0
07:51:15, accumulated pauses: 763 ms, max pause: 648 ms, pauses over 1000 ms: 0
07:51:20, accumulated pauses: 148 ms, max pause: 8 ms, pauses over 1000 ms: 0
07:51:25, accumulated pauses: 75 ms, max pause: 8 ms, pauses over 1000 ms: 0
07:51:30, accumulated pauses: 88 ms, max pause: 9 ms, pauses over 1000 ms: 0
07:51:35, accumulated pauses: 58 ms, max pause: 6 ms, pauses over 1000 ms: 0
07:51:40, accumulated pauses: 69 ms, max pause: 8 ms, pauses over 1000 ms: 0
07:51:45, accumulated pauses: 203 ms, max pause: 98 ms, pauses over 1000 ms: 0
07:51:50, accumulated pauses: 25 ms, max pause: 1 ms, pauses over 1000 ms: 0
07:51:55, accumulated pauses: 51 ms, max pause: 1 ms, pauses over 1000 ms: 0
07:52:00, accumulated pauses: 29 ms, max pause: 0 ms, pauses over 1000 ms: 0
07:52:05, accumulated pauses: 32 ms, max pause: 0 ms, pauses over 1000 ms: 0
07:52:10, accumulated pauses: 37 ms, max pause: 0 ms, pauses over 1000 ms: 0
07:52:15, accumulated pauses: 34 ms, max pause: 0 ms, pauses over 1000 ms: 0
07:52:20, accumulated pauses: 37 ms, max pause: 1 ms, pauses over 1000 ms: 0
07:52:25, accumulated pauses: 36 ms, max pause: 1 ms, pauses over 1000 ms: 0
07:52:30, accumulated pauses: 29 ms, max pause: 0 ms, pauses over 1000 ms: 0
07:52:35, accumulated pauses: 36 ms, max pause: 0 ms, pauses over 1000 ms: 0
07:52:40, accumulated pauses: 34 ms, max pause: 0 ms, pauses over 1000 ms: 0
07:52:45, accumulated pauses: 30 ms, max pause: 1 ms, pauses over 1000 ms: 0
07:52:50, accumulated pauses: 33 ms, max pause: 1 ms, pauses over 1000 ms: 0
07:52:55, accumulated pauses: 34 ms, max pause: 1 ms, pauses over 1000 ms: 0
07:53:00, accumulated pauses: 42 ms, max pause: 1 ms, pauses over 1000 ms: 0
07:53:05, accumulated pauses: 37 ms, max pause: 0 ms, pauses over 1000 ms: 0
07:53:10, accumulated pauses: 45 ms, max pause: 1 ms, pauses over 1000 ms: 0
07:53:15, accumulated pauses: 38 ms, max pause: 2 ms, pauses over 1000 ms: 0
07:53:20, accumulated pauses: 43 ms, max pause: 3 ms, pauses over 1000 ms: 0
07:53:25, accumulated pauses: 35 ms, max pause: 0 ms, pauses over 1000 ms: 0
07:53:30, accumulated pauses: 325 ms, max pause: 306 ms, pauses over 1000 ms: 0
```

**Comment by vojtechtoman** [comment]
The test ran exceptionally slow (it took over 2 minutes instead of the regular 15 seconds). Just forming the cluster of 2 nodes took almost half a minute.

The test schedules a long-running task, sleeps for 4 seconds and then cancels the task (without interrupting it, thus expecting it to finish). What happened, I think, is that the 4 second timeout was not enough for the task to start and as a result, the task was canceled before it even ran. I will make the test (and maybe other tests in the test class that are written in a similar way) more resilient.
