### ISSUE TITLE
java.lang.NoClassDefFoundError is thrown when the user uploaded classes come in a wrong order

### ISSUE THREAD

**Issue by ncherkas** [hazelcast/hazelcast#16575]
`java.lang.NoClassDefFoundError` is thrown when the classes uploaded using the client user code upload come in a wrong order:
```
...
        ClientUserCodeDeploymentConfig clientUserCodeDeploymentConfig = new ClientUserCodeDeploymentConfig();
        clientUserCodeDeploymentConfig.setEnabled(true);
        clientUserCodeDeploymentConfig.addClass(B.class); //If B goes before A it doesn't work
        clientUserCodeDeploymentConfig.addClass(A.class);
        clientUserCodeDeploymentConfig.addClass(Command.class);
        config.setUserCodeDeploymentConfig(clientUserCodeDeploymentConfig);

        HazelcastInstance client = HazelcastClient.newHazelcastClient(config);
        IExecutorService executorService = client.getExecutorService("executorService");
        executorService.submit(new Command()).get();

...

    public static class A {

    }

    public static class B
            extends A {

    }

    public static class Command
            implements Callable<String>, Serializable {

        @Override
        public String call() {
            return "call";
        }
    }

```

**Expected behavior**
Classes are successfully uploaded independently of order in the config or jar.

**To Reproduce**
Please find the attached reproducer. It uses the Hazelcast Public Cloud. 
Steps to reproduce:
 - download reproducer [hazelcast-cloud-java-sample-client-ucd 2.zip](https://github.com/hazelcast/hazelcast/files/4128079/hazelcast-cloud-java-sample-client-ucd.2.zip)

 - create the Hazelcast Public Cloud cluster
 - change credentials in the code (cluster name, password, and discovery token)
 - run it
 - you should get `java.lang.NoClassDefFoundError` in the output

Example of output:
```
Jan 29, 2020 11:14:12 AM com.hazelcast.client.HazelcastClient
INFO: hz.client_0 [Test1] [3.12.5] A non-empty group password is configured for the Hazelcast client. Starting with Hazelcast version 3.11, clients with the same group name, but with different group passwords (that do not use authentication) will be accepted to a cluster. The group password configuration will be removed completely in a future release.
Jan 29, 2020 11:14:13 AM com.hazelcast.client.spi.ClientInvocationService
INFO: hz.client_0 [Test1] [3.12.5] Running with 2 response threads, dynamic=false
Jan 29, 2020 11:14:13 AM com.hazelcast.core.LifecycleService
INFO: hz.client_0 [Test1] [3.12.5] HazelcastClient 3.12.5 (20191210 - d54936e, 294ff46) is STARTING
Jan 29, 2020 11:14:13 AM com.hazelcast.core.LifecycleService
INFO: hz.client_0 [Test1] [3.12.5] HazelcastClient 3.12.5 (20191210 - d54936e, 294ff46) is STARTED
Jan 29, 2020 11:14:13 AM com.hazelcast.client.connection.nio.ClusterConnectorService
INFO: hz.client_0 [Test1] [3.12.5] Trying to connect to cluster with name: Test1
Jan 29, 2020 11:14:14 AM com.hazelcast.client.connection.nio.ClusterConnectorService
INFO: hz.client_0 [Test1] [3.12.5] Trying to connect to [100.111.22.24]:31001 as owner member
Jan 29, 2020 11:14:15 AM com.hazelcast.client.connection.ClientConnectionManager
INFO: hz.client_0 [Test1] [3.12.5] Setting ClientConnection{alive=true, connectionId=1, channel=NioChannel{/172.16.21.222:55924->/52.88.245.106:31001}, remoteEndpoint=[100.111.22.24]:31001, lastReadTime=2020-01-29 11:14:15.734, lastWriteTime=2020-01-29 11:14:15.369, closedTime=never, connected server version=3.12.2} as owner with principal ClientPrincipal{uuid='3db9b654-ba28-455e-8d8a-25f487371fa1', ownerUuid='23a8fb33-897d-4a73-90a6-0b16f30412e8'}
Jan 29, 2020 11:14:15 AM com.hazelcast.client.connection.ClientConnectionManager
INFO: hz.client_0 [Test1] [3.12.5] Authenticated with server [100.111.22.24]:31001, server version:3.12.2 Local address: /172.16.21.222:55924
Jan 29, 2020 11:14:16 AM com.hazelcast.client.spi.impl.ClientMembershipListener
INFO: hz.client_0 [Test1] [3.12.5] 

Members [1] {
	Member [100.111.22.24]:31001 - 23a8fb33-897d-4a73-90a6-0b16f30412e8
}

Jan 29, 2020 11:14:16 AM com.hazelcast.client.connection.nio.ClusterConnectorService
WARNING: hz.client_0 [Test1] [3.12.5] Exception during initial connection to [100.111.22.24]:31001: java.util.concurrent.ExecutionException: com.hazelcast.client.UndefinedErrorCodeException: Class name: java.lang.NoClassDefFoundError, Message: com/hz/cloud/Client$A
Jan 29, 2020 11:14:16 AM com.hazelcast.client.connection.nio.ClientConnection
WARNING: hz.client_0 [Test1] [3.12.5] ClientConnection{alive=false, connectionId=1, channel=NioChannel{/172.16.21.222:55924->/52.88.245.106:31001}, remoteEndpoint=[100.111.22.24]:31001, lastReadTime=2020-01-29 11:14:16.661, lastWriteTime=2020-01-29 11:14:16.437, closedTime=2020-01-29 11:14:16.667, connected server version=3.12.2} closed. Reason: Could not connect to [100.111.22.24]:31001 as owner
java.util.concurrent.ExecutionException: com.hazelcast.client.UndefinedErrorCodeException: Class name: java.lang.NoClassDefFoundError, Message: com/hz/cloud/Client$A
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:109)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:33)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:163)
	at com.hazelcast.client.spi.impl.ClientUserCodeDeploymentService.deploy(ClientUserCodeDeploymentService.java:172)
	at com.hazelcast.client.impl.clientside.HazelcastClientInstanceImpl.onClusterConnect(HazelcastClientInstanceImpl.java:444)
	at com.hazelcast.client.connection.nio.ClusterConnectorServiceImpl.connectAsOwner(ClusterConnectorServiceImpl.java:150)
	at com.hazelcast.client.connection.nio.ClusterConnectorServiceImpl.connectToCandidate(ClusterConnectorServiceImpl.java:252)
	at com.hazelcast.client.connection.nio.ClusterConnectorServiceImpl.connectToClusterInternal(ClusterConnectorServiceImpl.java:192)
	at com.hazelcast.client.connection.nio.ClusterConnectorServiceImpl.access$000(ClusterConnectorServiceImpl.java:62)
	at com.hazelcast.client.connection.nio.ClusterConnectorServiceImpl$1.call(ClusterConnectorServiceImpl.java:279)
	at com.hazelcast.client.connection.nio.ClusterConnectorServiceImpl$1.call(ClusterConnectorServiceImpl.java:275)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
Caused by: com.hazelcast.client.UndefinedErrorCodeException: Class name: java.lang.NoClassDefFoundError, Message: com/hz/cloud/Client$A
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
	at com.hazelcast.internal.usercodedeployment.impl.ClassSource.define(ClassSource.java:50)
	at com.hazelcast.internal.usercodedeployment.impl.ClassLocator.defineClassFromClient(ClassLocator.java:126)
	at com.hazelcast.internal.usercodedeployment.UserCodeDeploymentService.defineClass(UserCodeDeploymentService.java:72)
	at com.hazelcast.internal.usercodedeployment.impl.operation.DeployClassesOperation.run(DeployClassesOperation.java:50)
	at com.hazelcast.spi.Operation.call(Operation.java:170)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:210)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:199)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:407)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:434)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:648)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:633)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:592)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:256)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:61)
	at com.hazelcast.client.impl.protocol.task.AbstractMultiTargetMessageTask.processMessage(AbstractMultiTargetMessageTask.java:57)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:129)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:126)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run(AbstractInvocationFuture.java:251)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:96)
	... 16 more

Jan 29, 2020 11:14:16 AM com.hazelcast.client.connection.ClientConnectionManager
INFO: hz.client_0 [Test1] [3.12.5] Removed connection to endpoint: [100.111.22.24]:31001, connection: ClientConnection{alive=false, connectionId=1, channel=NioChannel{/172.16.21.222:55924->/52.88.245.106:31001}, remoteEndpoint=[100.111.22.24]:31001, lastReadTime=2020-01-29 11:14:16.661, lastWriteTime=2020-01-29 11:14:16.437, closedTime=2020-01-29 11:14:16.667, connected server version=3.12.2}
Jan 29, 2020 11:14:16 AM com.hazelcast.client.connection.nio.ClusterConnectorService
WARNING: hz.client_0 [Test1] [3.12.5] Unable to get live cluster connection, retry in 3000 ms, attempt 1 of 2.
Jan 29, 2020 11:14:19 AM com.hazelcast.client.connection.nio.ClusterConnectorService
INFO: hz.client_0 [Test1] [3.12.5] Trying to connect to [100.111.22.24]:31001 as owner member
Jan 29, 2020 11:14:20 AM com.hazelcast.client.connection.ClientConnectionManager
INFO: hz.client_0 [Test1] [3.12.5] Setting ClientConnection{alive=true, connectionId=2, channel=NioChannel{/172.16.21.222:55930->/52.88.245.106:31001}, remoteEndpoint=[100.111.22.24]:31001, lastReadTime=2020-01-29 11:14:20.432, lastWriteTime=2020-01-29 11:14:20.126, closedTime=never, connected server version=3.12.2} as owner with principal ClientPrincipal{uuid='3db9b654-ba28-455e-8d8a-25f487371fa1', ownerUuid='23a8fb33-897d-4a73-90a6-0b16f30412e8'}
Jan 29, 2020 11:14:20 AM com.hazelcast.client.connection.ClientConnectionManager
INFO: hz.client_0 [Test1] [3.12.5] Authenticated with server [100.111.22.24]:31001, server version:3.12.2 Local address: /172.16.21.222:55930
Jan 29, 2020 11:14:20 AM com.hazelcast.client.spi.impl.ClientMembershipListener
INFO: hz.client_0 [Test1] [3.12.5] 

Members [1] {
	Member [100.111.22.24]:31001 - 23a8fb33-897d-4a73-90a6-0b16f30412e8
}

Jan 29, 2020 11:14:21 AM com.hazelcast.client.connection.nio.ClusterConnectorService
WARNING: hz.client_0 [Test1] [3.12.5] Exception during initial connection to [100.111.22.24]:31001: java.util.concurrent.ExecutionException: com.hazelcast.client.UndefinedErrorCodeException: Class name: java.lang.NoClassDefFoundError, Message: com/hz/cloud/Client$A
Jan 29, 2020 11:14:21 AM com.hazelcast.client.connection.nio.ClientConnection
WARNING: hz.client_0 [Test1] [3.12.5] ClientConnection{alive=false, connectionId=2, channel=NioChannel{/172.16.21.222:55930->/52.88.245.106:31001}, remoteEndpoint=[100.111.22.24]:31001, lastReadTime=2020-01-29 11:14:21.151, lastWriteTime=2020-01-29 11:14:20.938, closedTime=2020-01-29 11:14:21.153, connected server version=3.12.2} closed. Reason: Could not connect to [100.111.22.24]:31001 as owner
java.util.concurrent.ExecutionException: com.hazelcast.client.UndefinedErrorCodeException: Class name: java.lang.NoClassDefFoundError, Message: com/hz/cloud/Client$A
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:109)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:33)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:163)
	at com.hazelcast.client.spi.impl.ClientUserCodeDeploymentService.deploy(ClientUserCodeDeploymentService.java:172)
	at com.hazelcast.client.impl.clientside.HazelcastClientInstanceImpl.onClusterConnect(HazelcastClientInstanceImpl.java:444)
	at com.hazelcast.client.connection.nio.ClusterConnectorServiceImpl.connectAsOwner(ClusterConnectorServiceImpl.java:150)
	at com.hazelcast.client.connection.nio.ClusterConnectorServiceImpl.connectToCandidate(ClusterConnectorServiceImpl.java:252)
	at com.hazelcast.client.connection.nio.ClusterConnectorServiceImpl.connectToClusterInternal(ClusterConnectorServiceImpl.java:192)
	at com.hazelcast.client.connection.nio.ClusterConnectorServiceImpl.access$000(ClusterConnectorServiceImpl.java:62)
	at com.hazelcast.client.connection.nio.ClusterConnectorServiceImpl$1.call(ClusterConnectorServiceImpl.java:279)
	at com.hazelcast.client.connection.nio.ClusterConnectorServiceImpl$1.call(ClusterConnectorServiceImpl.java:275)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
Caused by: com.hazelcast.client.UndefinedErrorCodeException: Class name: java.lang.NoClassDefFoundError, Message: com/hz/cloud/Client$A
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
	at com.hazelcast.internal.usercodedeployment.impl.ClassSource.define(ClassSource.java:50)
	at com.hazelcast.internal.usercodedeployment.impl.ClassLocator.defineClassFromClient(ClassLocator.java:126)
	at com.hazelcast.internal.usercodedeployment.UserCodeDeploymentService.defineClass(UserCodeDeploymentService.java:72)
	at com.hazelcast.internal.usercodedeployment.impl.operation.DeployClassesOperation.run(DeployClassesOperation.java:50)
	at com.hazelcast.spi.Operation.call(Operation.java:170)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:210)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:199)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:407)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:434)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:648)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:633)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:592)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:256)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:61)
	at com.hazelcast.client.impl.protocol.task.AbstractMultiTargetMessageTask.processMessage(AbstractMultiTargetMessageTask.java:57)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:129)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:126)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run(AbstractInvocationFuture.java:251)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:96)
	... 16 more

Jan 29, 2020 11:14:21 AM com.hazelcast.client.connection.ClientConnectionManager
INFO: hz.client_0 [Test1] [3.12.5] Removed connection to endpoint: [100.111.22.24]:31001, connection: ClientConnection{alive=false, connectionId=2, channel=NioChannel{/172.16.21.222:55930->/52.88.245.106:31001}, remoteEndpoint=[100.111.22.24]:31001, lastReadTime=2020-01-29 11:14:21.151, lastWriteTime=2020-01-29 11:14:20.938, closedTime=2020-01-29 11:14:21.153, connected server version=3.12.2}
Jan 29, 2020 11:14:21 AM com.hazelcast.client.connection.nio.ClusterConnectorService
WARNING: hz.client_0 [Test1] [3.12.5] Unable to get live cluster connection, attempt 2 of 2.
Jan 29, 2020 11:14:21 AM com.hazelcast.client.connection.nio.ClusterConnectorService
WARNING: hz.client_0 [Test1] [3.12.5] Unable to connect to any address for cluster: Test1. The following addresses were tried: [[100.111.22.24]:31001]
Jan 29, 2020 11:14:21 AM com.hazelcast.client.connection.nio.ClusterConnectorService
WARNING: hz.client_0 [Test1] [3.12.5] Could not connect to any cluster, shutting down the client: Unable to connect to any cluster.
Jan 29, 2020 11:14:21 AM com.hazelcast.core.LifecycleService
INFO: hz.client_0 [Test1] [3.12.5] HazelcastClient 3.12.5 (20191210 - d54936e, 294ff46) is SHUTTING_DOWN
Jan 29, 2020 11:14:21 AM com.hazelcast.core.LifecycleService
INFO: hz.client_0 [Test1] [3.12.5] HazelcastClient 3.12.5 (20191210 - d54936e, 294ff46) is SHUTDOWN
Exception in thread "main" java.lang.IllegalStateException: Unable to connect to any cluster.
	at com.hazelcast.client.connection.nio.ClusterConnectorServiceImpl.connectToClusterInternal(ClusterConnectorServiceImpl.java:214)
	at com.hazelcast.client.connection.nio.ClusterConnectorServiceImpl.access$000(ClusterConnectorServiceImpl.java:62)
	at com.hazelcast.client.connection.nio.ClusterConnectorServiceImpl$1.call(ClusterConnectorServiceImpl.java:279)
	at com.hazelcast.client.connection.nio.ClusterConnectorServiceImpl$1.call(ClusterConnectorServiceImpl.java:275)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
```

**Comment by sancar** [comment]
It seems issue is related to only subclasses ? At least that is what I see from my test. 
Can you also confirm that @ncherkas ?Do you have any issue when you put A, B and Command separate files and make them normal class.
