### ISSUE TITLE
CPMemberAddRemoveTest.when_snapshotIsTakenWhileRemovingCPMember_newMemberInstallsSnapshot

### ISSUE THREAD

**Issue by taburet** [hazelcast/hazelcast#16574]
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/5678/testReport/junit/com.hazelcast.cp.internal/CPMemberAddRemoveTest/when_snapshotIsTakenWhileRemovingCPMember_newMemberInstallsSnapshot/

**Error Message**
```
expected:<[CPMember{uuid=f40dfd6c-fc17-417a-b919-ea0a3c9b5016, address=[127.0.0.1]:5702}, CPMember{uuid=0907d4a0-45d5-440e-a551-a1bf49606f36, address=[127.0.0.1]:5703}, CPMember{uuid=3f65b986-e666-4149-93f4-372cac76d4e5, address=[127.0.0.1]:5704}]> but was:<[CPMember{uuid=e522c645-e231-4d2b-a831-8ae15b3595cb, address=[127.0.0.1]:5701}, CPMember{uuid=f40dfd6c-fc17-417a-b919-ea0a3c9b5016, address=[127.0.0.1]:5702}, CPMember{uuid=0907d4a0-45d5-440e-a551-a1bf49606f36, address=[127.0.0.1]:5703}]>
```

**Stacktrace**
```
java.lang.AssertionError: expected:<[CPMember{uuid=f40dfd6c-fc17-417a-b919-ea0a3c9b5016, address=[127.0.0.1]:5702}, CPMember{uuid=0907d4a0-45d5-440e-a551-a1bf49606f36, address=[127.0.0.1]:5703}, CPMember{uuid=3f65b986-e666-4149-93f4-372cac76d4e5, address=[127.0.0.1]:5704}]> but was:<[CPMember{uuid=e522c645-e231-4d2b-a831-8ae15b3595cb, address=[127.0.0.1]:5701}, CPMember{uuid=f40dfd6c-fc17-417a-b919-ea0a3c9b5016, address=[127.0.0.1]:5702}, CPMember{uuid=0907d4a0-45d5-440e-a551-a1bf49606f36, address=[127.0.0.1]:5703}]>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.cp.internal.CPMemberAddRemoveTest.lambda$when_snapshotIsTakenWhileRemovingCPMember_newMemberInstallsSnapshot$17(CPMemberAddRemoveTest.java:770)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1356)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1458)
	at com.hazelcast.cp.internal.CPMemberAddRemoveTest.when_snapshotIsTakenWhileRemovingCPMember_newMemberInstallsSnapshot(CPMemberAddRemoveTest.java:767)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by lazerion** [comment]
Also, fails on [Hazelcast-4.master-ZingJDK8](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-4.master-ZingJDK8/146/testReport/com.hazelcast.cp.internal/CPMemberAddRemoveTest/when_snapshotIsTakenWhileRemovingCPMember_newMemberInstallsSnapshot/) with hiccups
```
Hiccups measured while running test 'when_snapshotIsTakenWhileRemovingCPMember_newMemberInstallsSnapshot(com.hazelcast.cp.internal.CPMemberAddRemoveTest):'
07:32:00, accumulated pauses: 4939 ms, max pause: 20 ms, pauses over 1000 ms: 0
07:32:05, accumulated pauses: 4944 ms, max pause: 20 ms, pauses over 1000 ms: 0
07:32:10, accumulated pauses: 4934 ms, max pause: 20 ms, pauses over 1000 ms: 0
07:32:15, accumulated pauses: 4941 ms, max pause: 15 ms, pauses over 1000 ms: 0
07:32:20, accumulated pauses: 4944 ms, max pause: 14 ms, pauses over 1000 ms: 0
07:32:25, accumulated pauses: 4942 ms, max pause: 10 ms, pauses over 1000 ms: 0
07:32:30, accumulated pauses: 4933 ms, max pause: 11 ms, pauses over 1000 ms: 0
07:32:35, accumulated pauses: 4944 ms, max pause: 10 ms, pauses over 1000 ms: 0
07:32:40, accumulated pauses: 4943 ms, max pause: 11 ms, pauses over 1000 ms: 0
07:32:45, accumulated pauses: 4936 ms, max pause: 11 ms, pauses over 1000 ms: 0
07:32:50, accumulated pauses: 4942 ms, max pause: 10 ms, pauses over 1000 ms: 0
07:32:55, accumulated pauses: 4938 ms, max pause: 13 ms, pauses over 1000 ms: 0
07:33:00, accumulated pauses: 4943 ms, max pause: 10 ms, pauses over 1000 ms: 0
07:33:05, accumulated pauses: 4932 ms, max pause: 10 ms, pauses over 1000 ms: 0
07:33:10, accumulated pauses: 4943 ms, max pause: 11 ms, pauses over 1000 ms: 0
07:33:15, accumulated pauses: 4942 ms, max pause: 11 ms, pauses over 1000 ms: 0
07:33:20, accumulated pauses: 4943 ms, max pause: 10 ms, pauses over 1000 ms: 0
07:33:25, accumulated pauses: 4932 ms, max pause: 11 ms, pauses over 1000 ms: 0
07:33:30, accumulated pauses: 4942 ms, max pause: 10 ms, pauses over 1000 ms: 0
07:33:35, accumulated pauses: 4941 ms, max pause: 10 ms, pauses over 1000 ms: 0
07:33:40, accumulated pauses: 4942 ms, max pause: 10 ms, pauses over 1000 ms: 0
07:33:45, accumulated pauses: 4941 ms, max pause: 10 ms, pauses over 1000 ms: 0
07:33:50, accumulated pauses: 4942 ms, max pause: 11 ms, pauses over 1000 ms: 0
07:33:55, accumulated pauses: 4932 ms, max pause: 11 ms, pauses over 1000 ms: 0
07:34:00, accumulated pauses: 4945 ms, max pause: 10 ms, pauses over 1000 ms: 0
07:34:05, accumulated pauses: 4934 ms, max pause: 10 ms, pauses over 1000 ms: 0
07:34:10, accumulated pauses: 4413 ms, max pause: 10 ms, pauses over 1000 ms: 0
```

**Comment by kwart** [comment]
Another fail: http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/2697/

**Comment by sancar** [comment]
I have spent some time on it and could not find the issue.
[out.txt](https://github.com/hazelcast/hazelcast/files/5806819/out.txt)
Leaving the logs of the first failure here.  `Hazelcast-pr-builder/5678/`

I will add a second test and increase the log level of cp classes on tests. 

==== IMPORTANT ====
To the future reader, If a new incident happens, the new logs will be more informative, please don't skip sharing the link.

**Comment by mmedenjak** [comment]
Closing with increased logging. Reopen on next failure.

**Comment by olukas** [comment]
Reopening since it failed on `5.1.z` branch on OracleJDK8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-OracleJDK8-nightly/54/testReport/com.hazelcast.cp.internal/CPMemberAddRemoveTest/when_snapshotIsTakenWhileRemovingCPMember_newMemberInstallsSnapshot/
