### ISSUE TITLE
NullPointerException SparseBitSet.java:97 add JVM freeze 

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#16601]
http://jenkins.hazelcast.com/view/freeze/job/freeze-all/12/console

fail HzMember2HZ put-mapBak1Obj hzcmd.map.PutRandomStylePerson threadId=0 java.lang.NullPointerException

http://54.147.27.51/~jenkins/workspace/freeze-all/4.0/2020_02_03-18_20_04/stable/sql/bit-map

/disk1/jenkins/workspace/freeze-all/4.0/2020_02_03-18_20_04/stable/sql/bit-map

```
(base) [jenkins@ip-10-72-134-107 bit-map]$ cat ./output/HZ/HzMember2HZ/exception.txt
java.lang.NullPointerException
	at com.hazelcast.query.impl.bitmap.SparseBitSet.add(SparseBitSet.java:97)
	at com.hazelcast.query.impl.bitmap.Bitmap.update(Bitmap.java:103)
	at com.hazelcast.query.impl.BitmapIndexStore.update(BitmapIndexStore.java:216)
	at com.hazelcast.query.impl.AbstractIndex.putEntry(AbstractIndex.java:145)
	at com.hazelcast.query.impl.Indexes.putEntry(Indexes.java:271)
	at com.hazelcast.map.impl.recordstore.IndexingMutationObserver.saveIndex(IndexingMutationObserver.java:168)
	at com.hazelcast.map.impl.recordstore.IndexingMutationObserver.onUpdateRecord(IndexingMutationObserver.java:69)
	at com.hazelcast.map.impl.recordstore.CompositeMutationObserver.onUpdateRecord(CompositeMutationObserver.java:85)
	at com.hazelcast.map.impl.recordstore.AbstractRecordStore.updateRecord(AbstractRecordStore.java:208)
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.putInternal(DefaultRecordStore.java:768)
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.put(DefaultRecordStore.java:748)
	at com.hazelcast.map.impl.operation.PutOperation.runInternal(PutOperation.java:36)
	at com.hazelcast.map.impl.operation.MapOperation.run(MapOperation.java:112)
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:184)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:228)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:217)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:160)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:138)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:123)
```

**Comment by Danny-Hazelcast** [comment]
http://jenkins.hazelcast.com/view/freeze/job/freeze-x/

hz-bench-run-jenkins-freeze hz/stable/sql/bit-map

looks like this issue is rare / tricky to reproduce

**Comment by taburet** [comment]
Yes, looks like that's some kind of a corner case in partition management, the log on one of the members is flooded with "Partitions can't be assigned since startup is not completed yet.", then "Assigning new owners for 271 LOST partitions!" is reported...

**Comment by Danny-Hazelcast** [comment]
1 more occurance,  maybe 1 in 5 ish

http://jenkins.hazelcast.com/view/freeze/job/freeze-x/
http://jenkins.hazelcast.com/view/freeze/job/freeze-x/10/console

same stack trace 
```
java.lang.NullPointerException
	at com.hazelcast.query.impl.bitmap.SparseBitSet.add(SparseBitSet.java:97)
	at com.hazelcast.query.impl.bitmap.Bitmap.update(Bitmap.java:103)
	at com.hazelcast.query.impl.BitmapIndexStore.update(BitmapIndexStore.java:216)
	at com.hazelcast.query.impl.AbstractIndex.putEntry(AbstractIndex.java:145)
	at com.hazelcast.query.impl.Indexes.putEntry(Indexes.java:271)
	at com.hazelcast.map.impl.recordstore.IndexingMutationObserver.saveIndex(IndexingMutationObserver.java:168)
	at com.hazelcast.map.impl.recordstore.IndexingMutationObserver.onUpdateRecord(IndexingMutationObserver.java:69)
	at com.hazelcast.map.impl.recordstore.CompositeMutationObserver.onUpdateRecord(CompositeMutationObserver.java:85)
	at com.hazelcast.map.impl.recordstore.AbstractRecordStore.updateRecord(AbstractRecordStore.java:208)
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.putInternal(DefaultRecordStore.java:768)
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.put(DefaultRecordStore.java:748)
	at com.hazelcast.map.impl.operation.PutOperation.runInternal(PutOperation.java:36)
	at com.hazelcast.map.impl.operation.MapOperation.run(MapOperation.java:112)
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:184)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:228)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:217)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:160)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:138)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:123)
```

**Comment by Danny-Hazelcast** [comment]
run with -ea  but it passed http://jenkins.hazelcast.com/view/freeze/job/freeze-x/12/console
2:02
where are some log's
```
Feb 04, 2020 10:54:39 AM com.hazelcast.spi.impl.operationservice.impl.operations.PartitionIteratingOperation
SEVERE: [10.0.0.109]:5701 [HZ] [4.0] Not Member! this: [10.0.0.109]:5701, caller: [10.0.0.139]:5701, partitionId: -1, operation: com.hazelcast.spi.impl.operationservice.impl.operati
ons.PartitionIteratingOperation, service: hz:impl:mapService
com.hazelcast.spi.exception.CallerNotMemberException: Not Member! this: [10.0.0.109]:5701, caller: [10.0.0.139]:5701, partitionId: -1, operation: com.hazelcast.spi.impl.operationser
vice.impl.operations.PartitionIteratingOperation, service: hz:impl:mapService
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.ensureValidMember(OperationRunnerImpl.java:480)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:426)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:166)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:136)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:123)
```

**Comment by Danny-Hazelcast** [comment]
run with -ea Failed 

http://jenkins.hazelcast.com/view/freeze/job/freeze-x/14/console

fail HzClient3HZ put-mapBak1Bin hzcmd.map.PutRandomStylePerson threadId=0 java.lang.AssertionError: null

/disk1/jenkins/workspace/freeze-x/4.0/2020_02_04-11_06_16/bit-map

http://54.147.27.51/~jenkins/workspace/freeze-x/4.0/2020_02_04-11_06_16/bit-map

./output/HZ/HzClient3HZ/exception.txt

```
cat ./output/HZ/HzClient3HZ/exception.txt
java.lang.AssertionError: null
	at com.hazelcast.query.impl.BitmapIndexStore.update(BitmapIndexStore.java:215)
	at com.hazelcast.query.impl.AbstractIndex.putEntry(AbstractIndex.java:145)
	at com.hazelcast.query.impl.Indexes.putEntry(Indexes.java:271)
	at com.hazelcast.map.impl.recordstore.IndexingMutationObserver.saveIndex(IndexingMutationObserver.java:168)
	at com.hazelcast.map.impl.recordstore.IndexingMutationObserver.onUpdateRecord(IndexingMutationObserver.java:69)
	at com.hazelcast.map.impl.recordstore.CompositeMutationObserver.onUpdateRecord(CompositeMutationObserver.java:85)
	at com.hazelcast.map.impl.recordstore.AbstractRecordStore.updateRecord(AbstractRecordStore.java:208)
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.putInternal(DefaultRecordStore.java:768)
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.put(DefaultRecordStore.java:748)
	at com.hazelcast.map.impl.operation.PutOperation.runInternal(PutOperation.java:36)
	at com.hazelcast.map.impl.operation.MapOperation.run(MapOperation.java:112)
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:184)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:228)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:217)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:405)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:432)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:590)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:575)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:534)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:236)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:59)
	at com.hazelcast.client.impl.protocol.task.AbstractPartitionMessageTask.processInternal(AbstractPartitionMessageTask.java:51)
	at com.hazelcast.client.impl.protocol.task.AbstractAsyncMessageTask.processMessage(AbstractAsyncMessageTask.java:71)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:145)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:108)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:181)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:172)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:140)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:123)
```
