### ISSUE TITLE
 java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by dineshr360** [hazelcast/hazelcast#16604]
OS: ?
JDK: ?
Hazelcast version: ?

```
java.lang.OutOfMemoryError: Java heap space
        at com.hazelcast.nio.Packet.readValue(Packet.java:202)
        at com.hazelcast.nio.Packet.readFrom(Packet.java:195)
        at com.hazelcast.nio.tcp.MemberReadHandler.onRead(MemberReadHandler.java:56)
        at com.hazelcast.nio.tcp.nonblocking.NonBlockingSocketReader.handle(NonBlockingSocketReader.java:159)
        at com.hazelcast.nio.tcp.nonblocking.NonBlockingIOThread.handleSelectionKey(NonBlockingIOThread.java:345)
        at com.hazelcast.nio.tcp.nonblocking.NonBlockingIOThread.handleSelectionKeys(NonBlockingIOThread.java:330)
        at com.hazelcast.nio.tcp.nonblocking.NonBlockingIOThread.selectLoop(NonBlockingIOThread.java:248)
        at com.hazelcast.nio.tcp.nonblocking.NonBlockingIOThread.run(NonBlockingIOThread.java:201)
```

**Comment by tkountis** [comment]
Hi @dineshr360 the exception is not enough to track and fix any potential leaks in the code base.
Would you be able to provide more details like, OS, JDK & Hazelcast version, along with a heap dump of the time of the exception? If you don't want to share here publicly we can create a private channel for you to share with us.

**Comment by pveentjer** [comment]
Closing due to inactivity.
