### ISSUE TITLE
com.hazelcast.map.impl.query.SingleValueBitmapIndexTest.testConsecutiveQueries

### ISSUE THREAD

**Issue by cangencer** [hazelcast/hazelcast#16634]
Failed on 4.0.z branch:

http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/5780/testReport/junit/com.hazelcast.map.impl.query/SingleValueBitmapIndexTest/testConsecutiveQueries_IndexConfig_name_null__type_BITMAP__attributes__age___bitmapIndexOptions_BitmapIndexOptions_uniqueKey_stringId__uniqueKeyTransformation_OBJECT___/

```
com.hazelcast.map.impl.query.SingleValueBitmapIndexTest.testConsecutiveQueries[IndexConfig{name=null, type=BITMAP, attributes=[age], bitmapIndexOptions=BitmapIndexOptions{uniqueKey=stringId, uniqueKeyTransformation=OBJECT}}]
```
```
Error Message
expected:<1> but was:<0>
Stacktrace
java.lang.AssertionError: expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.map.impl.query.SingleValueBitmapIndexTest.verifyQueries(SingleValueBitmapIndexTest.java:235)
	at com.hazelcast.map.impl.query.SingleValueBitmapIndexTest.testConsecutiveQueries(SingleValueBitmapIndexTest.java:143)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by taburet** [comment]
The test should be fixed by https://github.com/hazelcast/hazelcast/commit/21f89d83d5e0c53b1827173ad1d1676a8325ce7d, please rebase.

**Comment by cangencer** [comment]
Normally it should automatically build against the latest in the branch, even if the branch wasn't created at the latest for that branch. I'll try rebasing, though.

**Comment by taburet** [comment]
As far as I understand, the PR builder builds it exactly at the PR branch head. But honestly I'm not that certain about the fix. Basically the test verifies that the queries are served using the bitmap index. If there are some partition migrations detected during the query execution, a fallback to the no-index full scan execution is performed. Therefore the fix tries to make sure the cluster is stable before starting the test, but there might be some other unexpected migrations... fingers crossed.
