### ISSUE TITLE
OperationTimeoutException in the logs when using heml chart 3.0.2 and Spring Cache

### ISSUE THREAD

**Issue by kleung** [hazelcast/hazelcast#16678]
Hi,
I installed Hazelcast 4 through helm chart 3.0.2 with Service Type set to LoadBalancer and clusterIP to "".

My Spring project uses hazelcast-all version 4.0 as the dependency and when I work with Spring Caching, I have the following configuration:

```java
@Bean
    public CacheManager cacheManager() {
        ClientConfig config = new ClientConfig();
        config.getNetworkConfig().addAddress("IP:PORT");
        HazelcastInstance client = HazelcastClient.newHazelcastClient(config);

        return new HazelcastCacheManager(client);
    }
```

I noticed that almost always get timeout and the following stacktrace after I call a method annotated with @CacheEvict:

```
java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:787) [spring-boot-2.2.4.RELEASE.jar:2.2.4.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:768) [spring-boot-2.2.4.RELEASE.jar:2.2.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:322) [spring-boot-2.2.4.RELEASE.jar:2.2.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.2.4.RELEASE.jar:2.2.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) [spring-boot-2.2.4.RELEASE.jar:2.2.4.RELEASE]
	at com.test.hazelcastcaching.HazelcastcachingApplication.main(HazelcastcachingApplication.java:21) [classes/:na]
Caused by: com.hazelcast.core.OperationTimeoutException: ClientInvocation{clientMessage = ClientMessage{connection=null, length=62, operation=Map.Get, isRetryable=true, correlationId=215, messageType=10200, isEvent=false, isfragmented=false}, objectName = TestData, target = partition 31, sendConnection = null} timed out because exception occurred after client invocation timeout 120000 ms. Current time: 2020-02-23 22:03:22.076. Start time: 2020-02-23 22:01:21.774. Total elapsed time: 120302 ms. 
	at com.hazelcast.client.impl.spi.impl.ClientInvocation.notifyException(ClientInvocation.java:264) ~[hazelcast-all-4.0.jar:4.0]
	at com.hazelcast.client.impl.spi.impl.ClientInvocation.invokeOnSelection(ClientInvocation.java:173) ~[hazelcast-all-4.0.jar:4.0]
	at com.hazelcast.client.impl.spi.impl.ClientInvocation.retry(ClientInvocation.java:193) ~[hazelcast-all-4.0.jar:4.0]
	at com.hazelcast.client.impl.spi.impl.ClientInvocation.run(ClientInvocation.java:179) ~[hazelcast-all-4.0.jar:4.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_161]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_161]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_161]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_161]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_161]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64) ~[hazelcast-all-4.0.jar:4.0]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80) ~[hazelcast-all-4.0.jar:4.0]
Caused by: java.io.IOException: No available connection to member 520e257c-e306-47c6-9e2d-6d8d02a867d8
	at com.hazelcast.client.impl.spi.impl.SmartClientInvocationService.getConnection(SmartClientInvocationService.java:125) ~[hazelcast-all-4.0.jar:4.0]
	at com.hazelcast.client.impl.spi.impl.SmartClientInvocationService.invokeOnTarget(SmartClientInvocationService.java:118) ~[hazelcast-all-4.0.jar:4.0]
	at com.hazelcast.client.impl.spi.impl.SmartClientInvocationService.invokeOnPartitionOwner(SmartClientInvocationService.java:95) ~[hazelcast-all-4.0.jar:4.0]
	at com.hazelcast.client.impl.spi.impl.ClientInvocation.invokeOnSelection(ClientInvocation.java:166) ~[hazelcast-all-4.0.jar:4.0]
	... 11 common frames omitted
```

**Comment by mesutcelik** [comment]
Hi @kleung 
You are missing Kubernetes Discovery configuration in your ClientConfig.
This guide might help you to run hazelcast +spring on k8s environment. It is working in embedded mode but you just need to convert Config part into [ClientConfig](https://github.com/hazelcast-guides/caching-springboot-microservices-on-kubernetes/blob/master/final/src/main/java/guides/hazelcast/spring/Application.java#L24). 
https://github.com/hazelcast-guides/caching-springboot-microservices-on-kubernetes

**Comment by kleung** [comment]
Hi @mesutcelik 
Thanks for your reply!

Sorry I think I forgot 1 piece of information - my application is outside of kubernetes, that's why I chose to use LoadBalancer instead of the helm chart's default value.

Should I also use kubernetes discovery too?

Should I follow [https://github.com/hazelcast/hazelcast-code-samples/tree/master/hazelcast-integration/kubernetes/samples/external-client](https://github.com/hazelcast/hazelcast-code-samples/tree/master/hazelcast-integration/kubernetes/samples/external-client) with the api key and certificate too?

**Comment by mesutcelik** [comment]
> Should I follow https://github.com/hazelcast/hazelcast-code-samples/tree/master/hazelcast-integration/kubernetes/samples/external-client with the api key and certificate too?

yes

> Should I also use kubernetes discovery too?

yes because you have no fixed IPs of your hazelcast members.
 
> Sorry I think I forgot 1 piece of information - my application is outside of kubernetes, that's why I chose to use LoadBalancer instead of the helm chart's default value.

LoadBalancer or headless service is only used for discovery in hazelcast kubernetes deployment. Hazelcast Client that you use in your application has a feature called smart routing so applications are connected all hazelcast members and send the operations(read|write) directly to the responsible hazelcast member. Therefore, loadbalancing is basically done on hazelcast client level.
https://docs.hazelcast.org/docs/latest/manual/html-single/#java-client-operation-modes

**Comment by mesutcelik** [comment]
Hi @kleung ,
I am closing this issue. Please contact back if you still see a problem.
