### ISSUE TITLE
HazelcastVersionLocatorTest testDownloadVersion

### ISSUE THREAD

**Issue by lazerion** [hazelcast/hazelcast#16708]
- Fails on `Hazelcast-4.master-nightly`
- Fails on [Build #397 (Feb 28, 2020 5:07:03 PM)](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-4.master-nightly/397/testReport/junit/com.hazelcast.test.starter.test/HazelcastVersionLocatorTest/testDownloadVersion/)
- Error
```
test timed out after 300000 milliseconds
```
- Stacktrace 
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.readV3Record(InputRecord.java:593)
	at sun.security.ssl.InputRecord.read(InputRecord.java:532)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:975)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:933)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at sun.net.www.MeteredStream.read(MeteredStream.java:134)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3454)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at java.io.FilterInputStream.read(FilterInputStream.java:107)
	at com.hazelcast.internal.nio.IOUtil.drainTo(IOUtil.java:689)
	at com.hazelcast.test.starter.HazelcastVersionLocator.downloadFile(HazelcastVersionLocator.java:121)
	at com.hazelcast.test.starter.HazelcastVersionLocator.downloadMainArtifact(HazelcastVersionLocator.java:96)
	at com.hazelcast.test.starter.HazelcastVersionLocator.locateMainArtifact(HazelcastVersionLocator.java:78)
	at com.hazelcast.test.starter.HazelcastVersionLocator.locateVersion(HazelcastVersionLocator.java:63)
	at com.hazelcast.test.starter.test.HazelcastVersionLocatorTest.testDownloadVersion(HazelcastVersionLocatorTest.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```
- Possible commits
 (commit: c96d696) 
(commit: 7e665c7)

kindly check

**Comment by mmedenjak** [comment]
Seems like a temporary failure. Simply, downloading the JAR took over 5 minutes. Usually it takes up to 6 seconds - http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-4.master-nightly/408/testReport/com.hazelcast.test.starter.test/HazelcastVersionLocatorTest/testDownloadVersion/history/.

On the recent builds, the test is passing so I suggest we close it. WDYT @lazerion  ?

**Comment by mmedenjak** [comment]
Closing until next failure, then we can think about how to approach this.
