### ISSUE TITLE
Embeded Hazelcast on kubernetes with autoscalling problem

### ISSUE THREAD

**Issue by jakubigla** [hazelcast/hazelcast#16714]
**Describe the bug**
I use Hazelcast on Kubernetes with default options and I have Horizontal Pod Auto Scaling enabled for my microservice. Whe the deployment scales out (for example to 10 replicas) everything works fine, but when the HPA kills pods (let's say 4 at the same time) I get MASSIVE number of these exceptions per second 

```
java.io.IOException: Connection reset by peer
	at java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:245)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:358)
	at com.hazelcast.internal.networking.nio.NioInboundPipeline.process(NioInboundPipeline.java:113)
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKey(NioThread.java:368)
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKeys(NioThread.java:353)
	at com.hazelcast.internal.networking.nio.NioThread.selectLoop(NioThread.java:279)
	at com.hazelcast.internal.networking.nio.NioThread.run(NioThread.java:234)

2020-03-02 10:55:37.787  INFO 1 --- [cached.thread-4] com.hazelcast.nio.tcp.TcpIpConnector     : [10.252.4.49]:5701 [dev] [3.11.1] Connecting to /10.252.4.21:5701, timeout: 0, bind-any: true
2020-03-02 10:55:37.789  WARN 1 --- [.IO.thread-in-2] com.hazelcast.nio.tcp.TcpIpConnection    : [10.252.4.49]:5701 [dev] [3.11.1] Connection[id=72, /10.252.4.49:33907->/10.252.4.21:5701, endpoint=[10.252.4.21]:5701, alive=false, type=NONE] closed. Reason: Exception in Connection[id=72, /10.252.4.49:33907->/10.252.4.21:5701, endpoint=[10.252.4.21]:5701, alive=true, type=NONE], thread=hz._hzInstance_1_dev.IO.thread-in-2

```
I get like 100 of these per second, which causes the pod using maximum number of resources, it throws Java heap space exceptions and the pod is stuck. 

Maybe it's just a matter of hazelcast configuration? 
Would hazelcast.shutdownhook.policy=GRACEFUL make things better? 

**Expected behavior**

I expect that running pods don't throw any exceptions when the other pods get killed.

**Comment by mesutcelik** [comment]
Hi @jakubigla ,
How did you deploy Hazelcast in Kubernetes?
Can you reproduce the error using [this guide](https://github.com/hazelcast-guides/hazelcast-hpa)?


If you are using [hazelcast helm charts](https://github.com/hazelcast/charts), graceful shutdown is [enabled](https://github.com/hazelcast/charts/blob/dec16bdecf67a282b8de4c6ef15586dc08c99b1d/stable/hazelcast/values.yaml#L83) by default.

**Comment by mesutcelik** [comment]
Hi @jakubigla ,
Have you had a chance to look at my comment above?

**Comment by mesutcelik** [comment]
I am closing this issue due to inactivity. Please free to reopen if you have more insights
