### ISSUE TITLE
HazelcastProxyFactoryTest failures

### ISSUE THREAD

**Issue by vbekiaris** [hazelcast/hazelcast#16751]
Since 088f3680 tests starting proxied `HazelcastInstance`s fail to shutdown with:

```
java.lang.AbstractMethodError
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.destroy(StreamSerializerAdapter.java:70)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.dispose(AbstractSerializationService.java:344)
	at com.hazelcast.instance.impl.Node.shutdownServices(Node.java:579)
	at com.hazelcast.instance.impl.Node.shutdown(Node.java:506)
	at com.hazelcast.instance.impl.LifecycleServiceImpl.shutdown(LifecycleServiceImpl.java:101)
	at com.hazelcast.instance.impl.LifecycleServiceImpl.shutdown(LifecycleServiceImpl.java:84)
	at com.hazelcast.instance.impl.HazelcastInstanceProxy.shutdown(HazelcastInstanceProxy.java:297)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.hazelcast.test.starter.ProxyInvocationHandler.invokeMethodDelegate(ProxyInvocationHandler.java:99)
	at com.hazelcast.test.starter.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:56)
	at com.sun.proxy.$Proxy31.shutdown(Unknown Source)
```

As a result, there may be leftover `HazelcastInstance`s after tests execution resulting in unrelated  test failures (eg http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-4.master-nightly/409/ has 136 failures).

**Comment by lazerion** [comment]
@vbekiaris IIRC, this issue was after and fixing `Node failed to start!` errors, but it seems still failing after merge, kindly check.
- fails on `136` cases [Build #141 (Mar 19, 2020 9:11:26 AM)](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-4.master-IbmJDK8-fips-nightly/141/)
- Errors
```
Error Message
Node failed to start!
Stacktrace
java.lang.IllegalStateException: Node failed to start!
	at com.hazelcast.instance.impl.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:124)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:241)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:220)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:158)
	at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:91)
	at com.hazelcast.client.cache.ClientCacheCreationTest.createSingleCache_whenMemberBounce(ClientCacheCreationTest.java:83)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.lang.Thread.run(Thread.java:811)
```

**Comment by lazerion** [comment]
@vbekiaris 
- `Hazelcast-4.master-sonar` still failing with similar errors in logs [Build #441 (Mar 28, 2020 9:17:02 PM)](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-4.master-sonar/441/#showFailuresLink)

```
Caused by: java.lang.IllegalStateException: Node failed to start!
	at com.hazelcast.instance.impl.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:124)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:241)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.getOrCreateHazelcastInstance(HazelcastInstanceFactory.java:113)
	at com.hazelcast.core.Hazelcast.getOrCreateHazelcastInstance(Hazelcast.java:165)
	at com.hazelcast.cache.impl.HazelcastServerCachingProvider.getDefaultInstance(HazelcastServerCachingProvider.java:99)
	at com.hazelcast.cache.impl.AbstractHazelcastCachingProvider.getOrCreateInstance(AbstractHazelcastCachingProvider.java:341)
	at com.hazelcast.cache.impl.AbstractHazelcastCachingProvider.createHazelcastCacheManager(AbstractHazelcastCachingProvider.java:247)
	at com.hazelcast.cache.impl.AbstractHazelcastCachingProvider.getCacheManager(AbstractHazelcastCachingProvider.java:131)
```

**Comment by vbekiaris** [comment]
@lazerion the build was initiated on commit b89cf6df31a805b0da61cbc293974f39982de431 which does not include the changes from #16789 . Can you run again the job on a branch that includes #16789, it should fix the failing tests.

**Comment by lazerion** [comment]
@vbekiaris you are right! sorry for inconvenience.
