### ISSUE TITLE
OOME on map.set when sufficient memory exists

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast#16760]
This code

```
    public static void main(String[] args) throws Exception {
        Config config = new Config();
        config.getNetworkConfig().getJoin().getMulticastConfig().setEnabled(false);
        HazelcastInstance hazelcastInstance = Hazelcast.newHazelcastInstance(config);

        IMap<Integer, Object> map = hazelcastInstance.getMap("test");
        
        int key = 1;
        // This this -- int[] megabytes = { 20, 20, 20 };
        int[] megabytes = { 10, 15, 20 };
        for (int mega : megabytes) {
            byte[] value = new byte[mega * MEGABYTE];

            for (int i = 0 ; i < 10 ; i++) {
                System.out.println("Write: " + key + ", size " + value.length + " when freeMemory()=="
                        + (Runtime.getRuntime().freeMemory() / MEGABYTE) + "MB");
                map.set(key, value);
                key++;
            }
        }
        
        hazelcastInstance.shutdown();
    }
```
gives an OOME with usually about 100MB free memory reported, for a 20MB object.

Typical output I get
```
Write: 2, size 10485760 when freeMemory()==439MB
Write: 3, size 10485760 when freeMemory()==417MB
Write: 4, size 10485760 when freeMemory()==395MB
Write: 5, size 10485760 when freeMemory()==373MB
Write: 6, size 10485760 when freeMemory()==351MB
Write: 7, size 10485760 when freeMemory()==329MB
Write: 8, size 10485760 when freeMemory()==307MB
Write: 9, size 10485760 when freeMemory()==284MB
Write: 10, size 10485760 when freeMemory()==262MB
Write: 11, size 15728640 when freeMemory()==356MB
Write: 12, size 15728640 when freeMemory()==324MB
Write: 13, size 15728640 when freeMemory()==292MB
Write: 14, size 15728640 when freeMemory()==314MB
Write: 15, size 15728640 when freeMemory()==282MB
Write: 16, size 15728640 when freeMemory()==282MB
Write: 17, size 15728640 when freeMemory()==266MB
Write: 18, size 15728640 when freeMemory()==250MB
Write: 19, size 15728640 when freeMemory()==234MB
Write: 20, size 15728640 when freeMemory()==218MB
Write: 21, size 20971520 when freeMemory()==214MB
Write: 22, size 20971520 when freeMemory()==171MB
Write: 23, size 20971520 when freeMemory()==150MB
Write: 24, size 20971520 when freeMemory()==129MB
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataOutput.toByteArray(ByteArrayObjectDataOutput.java:424)
	at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataOutput.toByteArray(ByteArrayObjectDataOutput.java:415)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:155)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:133)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toData(AbstractSerializationService.java:118)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toData(AbstractSerializationService.java:106)
	at com.hazelcast.spi.impl.NodeEngineImpl.toData(NodeEngineImpl.java:334)
	at com.hazelcast.spi.impl.AbstractDistributedObject.toData(AbstractDistributedObject.java:78)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.set(MapProxyImpl.java:234)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.set(MapProxyImpl.java:225)
	at neil.demo.Application.main(Application.java:28)
```

The issue seems to occur if ten 10MB objects are inserted, then ten 15MB objects before
ten 20MB objects.
If all objects are 20MB heap size runs down to near zero before failure, as you would expect.

Tried on IMDG 3.12.6 and 4.0, using AdoptOpenJDK (build 11.0.6+10) on OSX 10.15.3

**Comment by neilstevenson** [comment]
I run with `-Xms512m -Xms512m`

**Comment by neilstevenson** [comment]
See https://stackoverflow.com/questions/60704216/hazelcast-eviction-is-not-working-with-free-heap-percentage-policy/60710982#60710982 for how this was discovered

**Comment by neilstevenson** [comment]
May be JDK related, doesn't run out at the same point on Java 8 v 11

**Comment by neilstevenson** [comment]
Adding `-XX:+UseParallelGC` changes the behaviouir. Looks like related to G1.

**Comment by neilstevenson** [comment]
It's just a G1 issue due to large objects. Humongous space out.
```[1.299s][info][gc             ] GC(30) Pause Full (G1 Humongous Allocation) 381M->381M(512M) 7.950ms
[1.299s][info][gc,cpu         ] GC(30) User=0.04s Sys=0.00s Real=0.00s
[1.299s][info][gc,task        ] GC(31) Using 10 workers of 10 for full compaction
[1.299s][info][gc,start       ] GC(31) Pause Full (G1 Humongous Allocation)
[1.300s][info][gc,phases,start] GC(31) Phase 1: Mark live objects
[1.304s][info][gc,stringtable ] GC(31) Cleaned string and symbol table, strings: 9459 processed, 1249 removed, symbols: 81795 processed, 0 removed
[1.304s][info][gc,phases      ] GC(31) Phase 1: Mark live objects 4.335ms
[1.304s][info][gc,phases,start] GC(31) Phase 2: Prepare for compaction
[1.305s][info][gc,phases      ] GC(31) Phase 2: Prepare for compaction 0.610ms
[1.305s][info][gc,phases,start] GC(31) Phase 3: Adjust pointers
[1.306s][info][gc,phases      ] GC(31) Phase 3: Adjust pointers 1.731ms
[1.306s][info][gc,phases,start] GC(31) Phase 4: Compact heap
[1.307s][info][gc,phases      ] GC(31) Phase 4: Compact heap 0.525ms
[1.308s][info][gc,heap        ] GC(31) Eden regions: 0->0(44)
[1.308s][info][gc,heap        ] GC(31) Survivor regions: 0->0(8)
[1.308s][info][gc,heap        ] GC(31) Old regions: 7->7
[1.308s][info][gc,heap        ] GC(31) Humongous regions: 376->376
[1.308s][info][gc,metaspace   ] GC(31) Metaspace: 26143K->26020K(1073152K)
[1.308s][info][gc             ] GC(31) Pause Full (G1 Humongous Allocation) 381M->380M(512M) 8.880ms
[1.308s][info][gc,cpu         ] GC(31) User=0.05s Sys=0.00s Real=0.01s
[1.308s][info][gc,marking     ] GC(28) Concurrent Rebuild Remembered Sets 19.786ms
[1.308s][info][gc,marking     ] GC(28) Concurrent Mark Abort
[1.308s][info][gc             ] GC(28) Concurrent Cycle 25.207ms
[10.226s][info][gc,heap,exit   ] Heap
[10.226s][info][gc,heap,exit   ]  garbage-first heap   total 524288K, used 402179K [0x00000007e0000000, 0x0000000800000000)
[10.226s][info][gc,heap,exit   ]   region size 1024K, 13 young (13312K), 0 survivors (0K)
[10.226s][info][gc,heap,exit   ]  Metaspace       used 26857K, capacity 28010K, committed 28544K, reserved 1073152K
[10.226s][info][gc,heap,exit   ]   class space    used 3265K, capacity 3824K, committed 3968K, reserved 1048576K```
