### ISSUE TITLE
SEVERE: Failed to ScheduledFutureTask AssertionError: Collecting metrics from source MetricsCollectionCycle.java:91 TcpIpNetworkingService$MetricsProvider failed 

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#16827]
test http://jenkins.hazelcast.com/view/hot-restart/job/hot-snapshot/87/console

/disk1/jenkins/workspace/hot-snapshot/4.0.1-SNAPSHOT/2020_03_31-07_15_01/snapshot
 
http://54.147.27.51/~jenkins/workspace/hot-snapshot/4.0.1-SNAPSHOT/2020_03_31-07_15_01/snapshot

I see this warning and sever msg in all 4.0.1-SNAPSHOT member logs
```
INFO: [10.0.0.136]:5701 [HZ] [4.0.1-SNAPSHOT] Initialized new cluster connection between /10.0.0.136:48233 and /10.0.0.129:5701
Mar 31, 2020 7:25:26 AM com.hazelcast.internal.metrics.impl.MetricsCollectionCycle
WARNING: Collecting metrics from source com.hazelcast.internal.nio.tcp.TcpIpNetworkingService$MetricsProvider failed
java.lang.AssertionError: metric '[endpoint=[10.0.0.192]:5701,unit=enum,metric=tcp.connection.connectionType,excludedTargets={}]' was rendered twice
	at com.hazelcast.internal.metrics.jmx.JmxPublisher.publishNumber(JmxPublisher.java:109)
	at com.hazelcast.internal.metrics.jmx.JmxPublisher.publishLong(JmxPublisher.java:86)
	at com.hazelcast.internal.metrics.impl.PublisherMetricsCollector.collectLong(PublisherMetricsCollector.java:62)
	at com.hazelcast.internal.metrics.impl.MetricsCollectionCycle.collectLong(MetricsCollectionCycle.java:168)
	at com.hazelcast.internal.metrics.impl.MetricsCollectionCycle.collect(MetricsCollectionCycle.java:145)
	at com.hazelcast.internal.metrics.impl.MetricsCollectionCycle.extractAndCollectDynamicMetrics(MetricsCollectionCycle.java:119)
	at com.hazelcast.internal.metrics.impl.MetricsCollectionCycle.access$200(MetricsCollectionCycle.java:45)
	at com.hazelcast.internal.metrics.impl.MetricsCollectionCycle$MetricsContext.collect(MetricsCollectionCycle.java:181)
	at com.hazelcast.internal.nio.tcp.TcpIpEndpointManager.provideDynamicMetrics(TcpIpEndpointManager.java:431)
	at com.hazelcast.internal.nio.tcp.TcpIpNetworkingService$MetricsProvider.provideDynamicMetrics(TcpIpNetworkingService.java:394)
	at com.hazelcast.internal.metrics.impl.MetricsCollectionCycle.collectDynamicMetrics(MetricsCollectionCycle.java:88)
	at com.hazelcast.internal.metrics.impl.MetricsRegistryImpl.collect(MetricsRegistryImpl.java:316)
	at com.hazelcast.internal.metrics.impl.MetricsService.collectMetrics(MetricsService.java:160)
	at com.hazelcast.internal.metrics.impl.MetricsService.collectMetrics(MetricsService.java:154)
	at com.hazelcast.spi.impl.executionservice.impl.DelegateAndSkipOnConcurrentExecutionDecorator$DelegateDecorator.run(DelegateAndSkipOnConcurrentExecutionDecorator.java:77)
	at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)

Mar 31, 2020 7:25:31 AM com.hazelcast.spi.impl.executionservice.ExecutionService
SEVERE: [10.0.0.136]:5701 [HZ] [4.0.1-SNAPSHOT] Failed to execute java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@54ebae17
java.lang.AssertionError: Collecting metrics from source com.hazelcast.internal.nio.tcp.TcpIpNetworkingService$MetricsProvider failed
	at com.hazelcast.internal.metrics.impl.MetricsCollectionCycle.collectDynamicMetrics(MetricsCollectionCycle.java:91)
	at com.hazelcast.internal.metrics.impl.MetricsRegistryImpl.collect(MetricsRegistryImpl.java:316)
	at com.hazelcast.internal.metrics.impl.MetricsService.collectMetrics(MetricsService.java:160)
	at com.hazelcast.internal.metrics.impl.MetricsService.collectMetrics(MetricsService.java:154)
	at com.hazelcast.spi.impl.executionservice.impl.DelegateAndSkipOnConcurrentExecutionDecorator$DelegateDecorator.run(DelegateAndSkipOnConcurrentExecutionDecorator.java:77)
	at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)

Mar 31, 2020 7:25:37 AM com.hazelcast.internal.cluster.ClusterService
```

then the  we get on the clients

fail HzClient2HZ clear javax.cache.CacheException: Error opening URI [hazelcast] 
```
javax.cache.CacheException: Error opening URI [hazelcast]
	at com.hazelcast.cache.impl.AbstractHazelcastCachingProvider.getCacheManager(AbstractHazelcastCachingProvider.java:134)
	at hzcmd.utils.CacheManagerSinglton.getCacheManager(CacheManagerSinglton.java:36)
```

**Comment by blazember** [comment]
I believe the two exceptions in the description are unrelated. The `AssertionError` warns that the same `TcpIpConnection` metric MBean was rendered twice. Because the `TcpIpConnection` metrics are discriminated by their endpoint strings, it feels the reason is that we have two `TcpIpConnection` instances with the same endpoint stored in the `activeConnections` here: https://github.com/hazelcast/hazelcast/blob/296aac5c8a3a4970851afc55c9e91622db75c131/hazelcast/src/main/java/com/hazelcast/internal/nio/tcp/TcpIpEndpointManager.java#L429-L435 For the same duplication issue, besides the warning we get a SEVERE `AssertionError` as well, that as a side effect I believe stops the metrics collection entirely for the given member. This is because the `AssertionError` hits the backing executor service, which cancels the scheduled task in exchange. The `AssertionError` was added for testing purposes, prod systems are expected to have assertions turned off, so I don't think this is an issue we should care too much.

I don't know about the `CacheException`, maybe @vbekiaris can comment on that one.

**Comment by Danny-Hazelcast** [comment]
we did get a rare passing run on 4.0.1-SANPSHOT 
http://jenkins.hazelcast.com/view/hot-restart/job/hot-snapshot/91/console


the warning and server messages, from the logs are unusual,
but the test fails due to the cache issue 

```
fail HzClient2HZ clear javax.cache.CacheException: Error opening URI [hazelcast]
```

**Comment by Danny-Hazelcast** [comment]
updated client side config for quicker reconnection 

```
 <connection-strategy>
        <connection-retry>
            <initial-backoff-millis>10</initial-backoff-millis>
            <max-backoff-millis>100</max-backoff-millis>
            <multiplier>2</multiplier>
            <cluster-connect-timeout-millis>99999999</cluster-connect-timeout-millis>
            <jitter>0.1</jitter>
        </connection-retry>
    </connection-strategy>
```

fixing cache issue.

**Comment by Danny-Hazelcast** [comment]
metric warning and sever logging ?
if it's not some thing we will fix/change then we can close this issue

**Comment by mdogan** [comment]
I encountered this issue with 4.1-snapshot too:

**Comment by Danny-Hazelcast** [comment]
```
java.lang.AssertionError: metric '[endpoint=[10.0.0.214]:5701,unit=enum,metric=tcp.connection.connectionType,excludedTargets={}]' was rendered twice
	at com.hazelcast.internal.metrics.jmx.JmxPublisher.publishNumber(JmxPublisher.java:109)
	at com.hazelcast.internal.metrics.jmx.JmxPublisher.publishLong(JmxPublisher.java:86)
	at com.hazelcast.internal.metrics.impl.PublisherMetricsCollector.collectLong(PublisherMetricsCollector.java:62)
	at com.hazelcast.internal.metrics.impl.MetricsCollectionCycle.collectLong(MetricsCollectionCycle.java:168)
	at com.hazelcast.internal.metrics.impl.MetricsCollectionCycle.collect(MetricsCollectionCycle.java:145)
	at com.hazelcast.internal.metrics.impl.MetricsCollectionCycle.extractAndCollectDynamicMetrics(MetricsCollectionCycle.java:119)
	at com.hazelcast.internal.metrics.impl.MetricsCollectionCycle.access$200(MetricsCollectionCycle.java:45)
	at com.hazelcast.internal.metrics.impl.MetricsCollectionCycle$MetricsContext.collect(MetricsCollectionCycle.java:181)
	at com.hazelcast.internal.server.tcp.TcpServerConnectionManager.provideDynamicMetrics(TcpServerConnectionManager.java:436)
	at com.hazelcast.internal.server.tcp.TcpServer$MetricsProvider.provideDynamicMetrics(TcpServer.java:341)
	at com.hazelcast.internal.metrics.impl.MetricsCollectionCycle.collectDynamicMetrics(MetricsCollectionCycle.java:88)
	at com.hazelcast.internal.metrics.impl.MetricsRegistryImpl.collect(MetricsRegistryImpl.java:316)
	at com.hazelcast.internal.metrics.impl.MetricsService.collectMetrics(MetricsService.java:160)
	at com.hazelcast.internal.metrics.impl.MetricsService.collectMetrics(MetricsService.java:154)
	at com.hazelcast.spi.impl.executionservice.impl.DelegateAndSkipOnConcurrentExecutionDecorator$DelegateDecorator.run(DelegateAndSkipOnConcurrentExecutionDecorator.java:77)
	at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
```

**Comment by olukas** [comment]
We encountered this issue in Jet soak tests. What seems interesting is that for some reason the issue does not occur if hot-restart is enabled.

**Comment by Danny-Hazelcast** [comment]
4.2-SNAPSHOT

```
INFO: [10.0.0.157]:5701 [HZ] [4.2-SNAPSHOT] [10.0.0.162]:5702 is added to the blacklist.
Feb 15, 2021 11:52:13 AM com.hazelcast.internal.metrics.impl.MetricsCollectionCycle
WARNING: Collecting metrics from source com.hazelcast.internal.server.tcp.TcpServer$MetricsProvider failed
java.lang.AssertionError: metric '[endpoint=[10.0.0.162]:5701,unit=enum,metric=tcp.connection.connectionType,excludedTargets={}]' was rendered twice. Present value: 1, new value: 1
	at com.hazelcast.internal.metrics.jmx.JmxPublisher.assertDoubleRendering(JmxPublisher.java:123)
	at com.hazelcast.internal.metrics.jmx.JmxPublisher.publishNumber(JmxPublisher.java:110)
	at com.hazelcast.internal.metrics.jmx.JmxPublisher.publishLong(JmxPublisher.java:87)
	at com.hazelcast.internal.metrics.impl.PublisherMetricsCollector.collectLong(PublisherMetricsCollector.java:62)
	at com.hazelcast.internal.metrics.impl.MetricsCollectionCycle.collectLong(MetricsCollectionCycle.java:168)
	at com.hazelcast.internal.metrics.impl.MetricsCollectionCycle.collect(MetricsCollectionCycle.java:145)
	at com.hazelcast.internal.metrics.impl.MetricsCollectionCycle.extractAndCollectDynamicMetrics(MetricsCollectionCycle.java:119)
	at com.hazelcast.internal.metrics.impl.MetricsCollectionCycle.access$200(MetricsCollectionCycle.java:45)
	at com.hazelcast.internal.metrics.impl.MetricsCollectionCycle$MetricsContext.collect(MetricsCollectionCycle.java:181)
	at com.hazelcast.internal.server.tcp.TcpServerConnectionManager.provideDynamicMetrics(TcpServerConnectionManager.java:437)
	at com.hazelcast.internal.server.tcp.TcpServer$MetricsProvider.provideDynamicMetrics(TcpServer.java:341)
	at com.hazelcast.internal.metrics.impl.MetricsCollectionCycle.collectDynamicMetrics(MetricsCollectionCycle.java:88)
	at com.hazelcast.internal.metrics.impl.MetricsRegistryImpl.collect(MetricsRegistryImpl.java:316)
	at com.hazelcast.internal.metrics.impl.MetricsService.collectMetrics(MetricsService.java:160)
	at com.hazelcast.internal.metrics.impl.MetricsService.collectMetrics(MetricsService.java:154)
	at com.hazelcast.spi.impl.executionservice.impl.DelegateAndSkipOnConcurrentExecutionDecorator$DelegateDecorator.run(DelegateAndSkipOnConcurrentExecutionDecorator.java:77)
	at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)

Feb 15, 2021 11:52:13 AM com.hazelcast.internal.cluster.impl.TcpIpJoiner
INFO: [10.0.0.157]:5701 [HZ] [4.2-SNAPSHOT] [10.0.0.157]:5703 is added to the blacklist.
Feb 15, 2021 11:52:13 AM com.hazelcast.internal.cluster.impl.TcpIpJoiner
INFO: [10.0.0.157]:5701 [HZ] [4.2-SNAPSHOT] [10.0.0.223]:5703 is added to the blacklist.
Feb 15, 2021 11:52:13 AM com.hazelcast.internal.cluster.impl.TcpIpJoiner
INFO: [10.0.0.157]:5701 [HZ] [4.2-SNAPSHOT] [10.0.0.157]:5702 is added to the blacklist.
Feb 15, 2021 11:52:13 AM com.hazelcast.internal.cluster.impl.TcpIpJoiner
INFO: [10.0.0.157]:5701 [HZ] [4.2-SNAPSHOT] [10.0.0.223]:5702 is added to the blacklist.
Feb 15, 2021 11:52:13 AM com.hazelcast.internal.cluster.impl.TcpIpJoiner
INFO: [10.0.0.157]:5701 [HZ] [4.2-SNAPSHOT] [10.0.0.72]:5703 is added to the blacklist.
Feb 15, 2021 11:52:13 AM com.hazelcast.internal.cluster.impl.TcpIpJoiner
INFO: [10.0.0.157]:5701 [HZ] [4.2-SNAPSHOT] [10.0.0.72]:5702 is added to the blacklist.
Feb 15, 2021 11:52:13 AM com.hazelcast.internal.cluster.impl.TcpIpJoiner
INFO: [10.0.0.157]:5701 [HZ] [4.2-SNAPSHOT] [10.0.0.162]:5703 is added to the blacklist.
Feb 15, 2021 11:52:13 AM com.hazelcast.internal.cluster.impl.TcpIpJoiner
INFO: [10.0.0.157]:5701 [HZ] [4.2-SNAPSHOT] [10.0.0.162]:5702 is added to the blacklist.
Feb 15, 2021 11:52:18 AM com.hazelcast.spi.impl.executionservice.ExecutionService
SEVERE: [10.0.0.157]:5701 [HZ] [4.2-SNAPSHOT] Failed to execute java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@425e4acd[Completed exceptionally: java.lang.AssertionError: Collecting metrics from source com.hazelcast.internal.server.tcp.TcpServer$MetricsProvider failed]
java.lang.AssertionError: Collecting metrics from source com.hazelcast.internal.server.tcp.TcpServer$MetricsProvider failed
	at com.hazelcast.internal.metrics.impl.MetricsCollectionCycle.collectDynamicMetrics(MetricsCollectionCycle.java:91)
	at com.hazelcast.internal.metrics.impl.MetricsRegistryImpl.collect(MetricsRegistryImpl.java:316)
	at com.hazelcast.internal.metrics.impl.MetricsService.collectMetrics(MetricsService.java:160)
	at com.hazelcast.internal.metrics.impl.MetricsService.collectMetrics(MetricsService.java:154)
	at com.hazelcast.spi.impl.executionservice.impl.DelegateAndSkipOnConcurrentExecutionDecorator$DelegateDecorator.run(DelegateAndSkipOnConcurrentExecutionDecorator.java:77)
	at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)

Feb 15, 2021 11:52:23 AM com.hazelcast.system
INFO: [10.0.0.157]:5701 [HZ] [4.2-SNAPSHOT] Cluster version set to 4.1
Feb 15, 2021 11:52:23 AM com.hazelcast.internal.cluster.ClusterService
INFO: [10.0.0.157]:5701 [HZ] [4.2-SNAPSHOT]
```

/home/ec2-user/workspace/hot-stepup-validate/4.2-SNAPSHOT/2021_02_15-11_48_41/step-up-version

**Comment by ahmetmircik** [comment]
In v5.0, i disabled jmx like this and issue disappeared:
```
<metrics enabled="true">
        <management-center enabled="true"/>
        <jmx enabled="false"/>
        <collection-frequency-seconds>5</collection-frequency-seconds>
    </metrics>
```
