### ISSUE TITLE
 hanging at client side pncounter get after cluster members kill restart

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#16836]
these 3 test run on 4.0 pass every time
http://jenkins.hazelcast.com/view/kill/job/kill-x2/37/console

and the same 3 test run on 4.0.1-SANPSHOT fail hang every time
http://jenkins.hazelcast.com/view/kill/job/kill-x4/9/console

/disk1/jenkins/workspace/kill-x4/4.0.1-SNAPSHOT/2020_04_01-05_00_23/pn-counter/
http://54.147.27.51/~jenkins/workspace/kill-x4/4.0.1-SNAPSHOT/2020_04_01-05_00_23/pn-counter/

find . -name hangers.txt | xargs cat
./output/HZ/HzClient3HZ/out.txt:	at hzcmd.pncounter.Validate.init(Validate.java:13)
./output/HZ/HzClient4HZ/out.txt:	at hzcmd.pncounter.Validate.init(Validate.java:13)
./output/HZ/HzClient2HZ/out.txt:	at hzcmd.pncounter.Validate.init(Validate.java:13)
./output/HZ/HzClient1HZ/out.txt:	at hzcmd.pncounter.Validate.init(Validate.java:13)
./output/HZ/HzClient3HZ/out.txt:	at hzcmd.pncounter.Validate.init(Validate.java:13)
./output/HZ/HzClient4HZ/out.txt:	at hzcmd.pncounter.Validate.init(Validate.java:13)
./output/HZ/HzClient2HZ/out.txt:	at hzcmd.pncounter.Validate.init(Validate.java:13)
./output/HZ/HzClient1HZ/out.txt:	at hzcmd.pncounter.Validate.init(Validate.java:13)
./output/HZ/HzClient3HZ/out.txt:	at hzcmd.pncounter.Validate.init(Validate.java:13)
./output/HZ/HzClient4HZ/out.txt:	at hzcmd.pncounter.Validate.init(Validate.java:13)
./output/HZ/HzClient2HZ/out.txt:	at hzcmd.pncounter.Validate.init(Validate.java:13)
./output/HZ/HzClient1HZ/out.txt:	at hzcmd.pncounter.Validate.init(Validate.java:13)

the client hangs at Validate.java:13

            hzInstance.getCPSubsystem().getAtomicLong(name + "" + i).set( getCounter(i).get() );

PNCounter.get()

**Comment by Danny-Hazelcast** [comment]
in this test all structs are created used and destroyed while  cluster members are killed are restarted. only pncounter ops seam to hang 

/disk1/jenkins/workspace/kill-All/4.0.1-SNAPSHOT/2020_03_30-19_57_28/stable/destroy/create-use-destroy Failed

http://54.147.27.51/~jenkins/workspace/kill-All/4.0.1-SNAPSHOT/2020_03_30-19_57_28/stable/destroy/create-use-destroy

./output/HZ/HzClient4HZ/out.txt:	at hzcmd.pncounter.CreateUseDestroy.timeStep(CreateUseDestroy.java:13)
./output/HZ/HzClient1HZ/out.txt:	at hzcmd.pncounter.CreateUseDestroy.timeStep(CreateUseDestroy.java:13)


 pnCounter.incrementAndGet();

**Comment by Danny-Hazelcast** [comment]
same fail 
http://jenkins.hazelcast.com/view/kill/job/kill-x/46/console

**Comment by Danny-Hazelcast** [comment]
added 
```
<connection-strategy>
        <connection-retry>
            <initial-backoff-millis>10</initial-backoff-millis>
            <max-backoff-millis>100</max-backoff-millis>
            <multiplier>2</multiplier>
            <cluster-connect-timeout-millis>99999999</cluster-connect-timeout-millis>
            <jitter>0.1</jitter>
        </connection-retry>
    </connection-strategy>
```
still failing  http://jenkins.hazelcast.com/view/kill/job/kill-x4/11/console

**Comment by Danny-Hazelcast** [comment]
caused by
https://github.com/hazelcast/hazelcast/pull/16603


is related ?

https://github.com/hazelcast/hazelcast/issues/16836
