### ISSUE TITLE
rolling upgrade of application fails in embedded mode

### ISSUE THREAD

**Issue by thesreyas** [hazelcast/hazelcast#16912]
**Describe the bug**
Application has embedded hazelcast.
Application is upgrading in rolling fashion from V1 to V2.
V2 introduced a new cache (V2-cache) with new value type (V2-classDef1)

1.Let's say I have four nodes in cluster: 4 - V1 nodes
2. Rolling upgrade is triggered.
3. Currently it 3 V1 nodes and 1 V2 node forming hazelcast cluster. 
At this point V2 created V2-Cache.
4.For some application specific reason upgrade has to rollback.
5.So V2 is shutdown. V2-Cache cannot be deleted.
6. New V1 is triggered 
7. New V1 fails saying it could not find "V2-classDef1" as cache is present in cluster.

**Expected behavior**

How to allow V1 HZ instance to startup without failing though any where in cluster class definition is not present?
Justification: Failure makes sense when some one accesses that new cache.

**To Reproduce**

3. ...

**Additional context**

**Comment by vbekiaris** [comment]
hello @thesreyas , can you post the configuration of your `V2-cache` and the complete exception stack trace to pinpoint why the class definition is required on the classpath?

**Comment by thesreyas** [comment]
Thanks  for your quick response @vbekiaris 
We are doing pretty straightforward way.


**Code that creates cache in V2 node**

private Cache createCache(String name, Class valueType) {
CacheManager cacheManager = HazelcastServerCachingProvider.createCachingProvider(gethz()).getCacheManager();
Cache cache = cacheManager.createCache(name, createCacheConfig(name, valueType));
return cache;
}
private CacheConfig createCacheConfig(String name,Class valueType ) {
CacheConfig cfg = new CacheConfig();
cfg.setTypes(String.class, valueType);
return cfg.setName(name);
}

**Exception Seen on V1 node at Step 7 mentioned above**

om.hazelcast.internal.cluster.impl.operations.JoinRequestOp
SEVERE: [55.55.55.5]:5701 [dev] [3.11.5] Could not resolve type com.pega.ClassA
com.hazelcast.core.HazelcastException: Could not resolve type com.pega.ClassA
at com.hazelcast.config.AbstractCacheConfig.resolve(AbstractCacheConfig.java:350)
at com.hazelcast.config.AbstractCacheConfig.resolveValueType(AbstractCacheConfig.java:340)
at com.hazelcast.config.AbstractCacheConfig.getValueType(AbstractCacheConfig.java:322)
at com.hazelcast.config.CacheConfig.copy(CacheConfig.java:682)
at com.hazelcast.cache.impl.PreJoinCacheConfig.<init>(PreJoinCacheConfig.java:59)
at com.hazelcast.cache.impl.PreJoinCacheConfig.<init>(PreJoinCacheConfig.java:55)
at com.hazelcast.cache.impl.AbstractCacheService.getPreJoinOperation(AbstractCacheService.java:656)
at com.hazelcast.spi.impl.NodeEngineImpl.getPreJoinOperations(NodeEngineImpl.java:451)
at com.hazelcast.internal.cluster.impl.ClusterJoinManager.preparePreJoinOps(ClusterJoinManager.java:777)
at com.hazelcast.internal.cluster.impl.ClusterJoinManager.checkIfJoinRequestFromAnExistingMember(ClusterJoinManager.java:649)
at com.hazelcast.internal.cluster.impl.ClusterJoinManager.checkJoinRequest(ClusterJoinManager.java:267)
at com.hazelcast.internal.cluster.impl.ClusterJoinManager.executeJoinRequest(ClusterJoinManager.java:247)
at com.hazelcast.internal.cluster.impl.ClusterJoinManager.handleJoinRequest(ClusterJoinManager.java:171)
at com.hazelcast.internal.cluster.impl.operations.JoinRequestOp.run(JoinRequestOp.java:41)
at com.hazelcast.spi.Operation.call(Operation.java:170)
at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:208)
at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:197)
at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:413)
at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:153)
at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:123)
at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:110)
Caused by: java.lang.ClassNotFoundException: com.pega.ClassA
at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
at com.hazelcast.nio.ClassLoaderUtil.tryLoadClass(ClassLoaderUtil.java:288)
at com.hazelcast.nio.ClassLoaderUtil.loadClass(ClassLoaderUtil.java:252)
at com.hazelcast.config.AbstractCacheConfig.resolve(AbstractCacheConfig.java:348)
... 20 more

**Comment by vbekiaris** [comment]
thanks @thesreyas for the info, I prepared a candidate fix for current `master` in #16917

**Comment by thesreyas** [comment]
Hi @vbekiaris 

Thanks for your attention to this.

Your description says: "When cache service is creating its pre-join operation, it creates a PreJoinCacheConfig assuming that the CacheConfig has been resolved
(ie KV types and other user customizations have been actually loaded). However it might
be the case that even though the CacheConfig is registered in cache service, the cache has not
yet been touched, so user customizations are not resolved yet."

At step 7:
The new V1 node does not access the cache. It is just trying to start HZ instance.
@vbekiaris , Can you please confirm that we are on same page?

**Comment by thesreyas** [comment]
@vbekiaris 
**The issue looks broader.**

**Scenario:** 
_Notations_ :  Nx - node , v1/v2 - application versions
Application is doing a rolling upgrade from v1 to v2. 
V2 application creates a new cache with value type class definition that does not exist on v1.
In the sequence of events below when second node in the cluster is rollingly upgraded it fails.

**Sequence of events:**

1. N1-v1,   N2-v1,  N3- v1  -- three v1 nodes
2. N1-v1,   N2-v1,  N3- v2-- third node is upgraded from v1 to v2.
   And third node created a cache with a definition that does not exist on v1.
  
3. N1-v1,   N2-v2,  N3- v2 -- **fails**
Here second node is rolling restarted to v2.
It sends a request to master ( N1 - the oldest node)
As part of this request something on master is trying to load the non existing class definition
and the join fails

@vbekiaris  Does this issue fix this as well?

If yes, I would add to the description of this issue.

**Comment by vbekiaris** [comment]
@thesreyas the scenario you described is another manifestation of the same issue. All members in the cluster have to be aware of all `CacheConfig`s. Here's what happens in this case:

- In step 2, N3-v2 is the joining member. It receives a pre-join operation from the cluster's master, notifying it of `CacheConfig`s already known to the cluster. The cache config for the new cache is propagated to all members of the cluster.
- In step 3, N1-v1, the master, attempts to create the pre join operation, including the new cache config created in step 2. Because (in current code) it assumes that KV types & user customizations are already resolved, it fails to serialize the pre join op and join fails.

So the fix will address also this scenario.
