### ISSUE TITLE
HazelcastInstanceNotActiveException on grid shutdown after using CPSubsystem

### ISSUE THREAD

**Issue by TomaszGaweda** [hazelcast/hazelcast#16932]
Graceful shutdown after using CPSubsystem causes following exception:
```
INFO: [192.168.1.15]:5702 [dev] [4.0] Shutdown request of Member [192.168.1.15]:5702 - 8308612f-1b48-4d96-864c-46cbb6ae93dd this is handled
kwi 27, 2020 5:30:13 PM com.hazelcast.cp.internal.session.ProxySessionManagerService
WARNING: [192.168.1.15]:5702 [dev] [4.0] Close session failed for CPGroupId{name='ABC', seed=0, groupId=177}
java.util.concurrent.ExecutionException: com.hazelcast.core.HazelcastInstanceNotActiveException: State: PASSIVE Operation: class com.hazelcast.cp.internal.operation.unsafe.UnsafeRaftReplicateOp
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.returnOrThrowWithGetConventions(InvocationFuture.java:114)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:98)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:601)
	at com.hazelcast.cp.internal.session.ProxySessionManagerService.onShutdown(ProxySessionManagerService.java:109)
	at com.hazelcast.instance.impl.Node$2.run(Node.java:526)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at com.hazelcast.internal.util.executor.CompletableFutureTask.run(CompletableFutureTask.java:64)
	at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
Caused by: com.hazelcast.core.HazelcastInstanceNotActiveException: State: PASSIVE Operation: class com.hazelcast.cp.internal.operation.unsafe.UnsafeRaftReplicateOp
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.engineActive(Invocation.java:511)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:544)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:534)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:236)
	at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.invokeOnPartition(OperationServiceImpl.java:334)
	at com.hazelcast.cp.internal.RaftInvocationManager.invokeOnPartition(RaftInvocationManager.java:225)
	at com.hazelcast.cp.internal.RaftInvocationManager.invoke(RaftInvocationManager.java:220)
	at com.hazelcast.cp.internal.session.ProxySessionManagerService.closeSession(ProxySessionManagerService.java:84)
	at com.hazelcast.cp.internal.session.AbstractProxySessionManager.shutdown(AbstractProxySessionManager.java:180)
	at com.hazelcast.cp.internal.session.ProxySessionManagerService.onShutdown(ProxySessionManagerService.java:96)
	... 9 more
```

Reproduction is as simple as:
```java
public final class RaftErrorReproduction {

	public static void main(String[] args) {
		var hz = Hazelcast.newHazelcastInstance();
		FencedLock lock = hz.getCPSubsystem().getLock("ABC");
		lock.tryLock();

		hz.shutdown();
	}
}
```
 My environment:
- Java 13
- Test run from IntelliJ IDEA
- Hazelcast 4.0

**Comment by mmedenjak** [comment]
Hi @TomaszGaweda ! Thank you for the report. Seems like it's a race between member shutdown and some cleanup process. @mdogan @petrpleshachkov can you take a quick look to see if this can be improved?

**Comment by mdogan** [comment]
This is not a race issue... During graceful shutdown, sessions created by shutting down member are closed explicitly. For instance that means lock acquired by a session on shutting down member will be released immediately, instead of waiting for session heartbeat timeout.

But when CP is in **unsafe** mode, that session close operation is actually a partition based write operation, which is forbidden during member shutdown.

**Comment by mmedenjak** [comment]
Changed to `Enhancement` then since it's not a correctness error, it's just misleading and now it needs to wait for the session heartbeat timeout. I guess we could hook into the `MembershipAwareService` in the case of unsafe or something similar. Thank you @mdogan for the explanation!
