### ISSUE TITLE
NodeQueryCacheConfigurator.findQueryCacheConfigFromMapConfig throws java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by lukasherman** [hazelcast/hazelcast#16953]
Got  `ConcurrentModificationException` while setting up Query Cache from multiple threads.
```
java.util.ConcurrentModificationException: null
  at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
  at java.util.ArrayList$Itr.next(ArrayList.java:859)
  at com.hazelcast.map.impl.querycache.subscriber.NodeQueryCacheConfigurator.findQueryCacheConfigFromMapConfig(NodeQueryCacheConfigurator.java:83)
  at com.hazelcast.map.impl.querycache.subscriber.NodeQueryCacheConfigurator.getOrNull(NodeQueryCacheConfigurator.java:70)
  at com.hazelcast.map.impl.querycache.subscriber.AbstractQueryCacheEndToEndConstructor.getOrNullQueryCacheConfig(AbstractQueryCacheEndToEndConstructor.java:157)
  at com.hazelcast.map.impl.querycache.subscriber.AbstractQueryCacheEndToEndConstructor.initQueryCacheConfig(AbstractQueryCacheEndToEndConstructor.java:134)
  at com.hazelcast.map.impl.querycache.subscriber.AbstractQueryCacheEndToEndConstructor.createNew(AbstractQueryCacheEndToEndConstructor.java:74)
  at com.hazelcast.map.impl.querycache.subscriber.AbstractQueryCacheEndToEndConstructor.createNew(AbstractQueryCacheEndToEndConstructor.java:39)
  at com.hazelcast.map.impl.querycache.subscriber.QueryCacheEndToEndProvider.tryCreateQueryCache(QueryCacheEndToEndProvider.java:92)
  at com.hazelcast.map.impl.querycache.subscriber.QueryCacheEndToEndProvider.getOrCreateQueryCache(QueryCacheEndToEndProvider.java:60)
  at com.hazelcast.map.impl.proxy.MapProxyImpl.createQueryCache(MapProxyImpl.java:1074)
  at com.hazelcast.map.impl.proxy.MapProxyImpl.getQueryCacheInternal(MapProxyImpl.java:1067)
  at com.hazelcast.map.impl.proxy.MapProxyImpl.getQueryCache(MapProxyImpl.java:1032)
```

**Expected behavior**
It is expected that method `getQueryCache` is thread-safe.

**To Reproduce**
This is a race condition so reproducer is a bit complicated. But the code inside `NodeQueryCacheConfigurator` is obviously not thread-safe. 

**Additional context**
This happened during Jet job initialization.
```
...
  at com.hazelcast.map.impl.proxy.MapProxyImpl.getQueryCacheInternal(MapProxyImpl.java:1067)
  at com.hazelcast.map.impl.proxy.MapProxyImpl.getQueryCache(MapProxyImpl.java:1032)
...
  at com.hazelcast.jet.impl.execution.ProcessorTasklet.init(ProcessorTasklet.java:231)
  at java.util.ArrayList.forEach(ArrayList.java:1257)
  at com.hazelcast.jet.impl.execution.TaskletExecutionService.lambda$submitCooperativeTasklets$4(TaskletExecutionService.java:170)
  at com.hazelcast.jet.impl.util.Util.doWithClassLoader(Util.java:440)
  at com.hazelcast.jet.impl.execution.TaskletExecutionService.submitCooperativeTasklets(TaskletExecutionService.java:169)
...
  at com.hazelcast.jet.impl.MasterJobContext.invokeStartExecution(MasterJobContext.java:462)
  at com.hazelcast.jet.impl.MasterJobContext.lambda$onInitStepCompleted$4(MasterJobContext.java:437)
  at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$44(JobCoordinationService.java:971)
  at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$45(JobCoordinationService.java:990)
  at com.hazelcast.util.executor.CompletableFutureTask.run(CompletableFutureTask.java:67)
  at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:227)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  at java.lang.Thread.run(Thread.java:748)
  at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
  at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80) 
```
Hazelcast Jet 3.2.1

**Comment by ahmetmircik** [comment]
Hi @lukasherman, thanks for the report. Is it possible to share a reproducer?

**Comment by ahmetmircik** [comment]
@lukasherman all accesses to queryCache configuration are synchronized [here](https://github.com/hazelcast/hazelcast/blob/0811c6942ad25f16087400ac424268bd774cb4d7/hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/QueryCacheEndToEndProvider.java#L78). I couldn't reproduce the issue so far. I would like to know how queryCache is used/accessed in your setup. For example, do you update config after node start, could please describe how you use queryCache, which methods do you call?

**Comment by lukasherman** [comment]
Interesting, that `mutex` should be sufficient. It has also failed only once, we have sorted it out with retry-on-exception workaround.
Anyway, the code configuring `queryCache` looks like:
```
IMap<Long, Map<String, Object>> map = hazelcastInstance.getMap(MAP_NAME);
QueryCache<Long, Map<String, Object>> queryCache = map.getQueryCache(PENDING);
if (queryCache == null) {
  QueryCacheConfig queryCacheConfig = new QueryCacheConfig();
  queryCacheConfig.setName(PENDING);
  PredicateConfig predicateConfig = new PredicateConfig();
  predicateConfig.setImplementation(new PendingPredicate());
  queryCacheConfig.setPredicateConfig(predicateConfig);
  hazelcastInstance.getConfig().getMapConfig(MAP_NAME).addQueryCacheConfig(queryCacheConfig);
  queryCache = transPropertyMap.getQueryCache(PENDING);
}
return queryCache;
```
and it is called on each cluster node in parallel during Jet job startup in `Processor.init` method.

**Comment by ahmetmircik** [comment]
>hazelcastInstance.getConfig().getMapConfig(MAP_NAME).addQueryCacheConfig(queryCacheConfig);

This seems the problematic part. There should be no config update for existing configs after node was started. Above code snippet is updating an existing map-config and this can cause `ConcurrentModificationException`. (With dynamic config capability, you can add new configs, for example new map config, but existing map-config objects cannot be updated). So updating existing config is not supported.

**Comment by lukasherman** [comment]
Thanks for explanation. Will update the code accordingly. Is there any other way to set up `QueryCacheConfig` dynamically?

**Comment by ahmetmircik** [comment]
No that is not supported. But you can always open an enhancement issue with your reasonings.

**Comment by lukasherman** [comment]
OK thank you.
