### ISSUE TITLE
NPE AbstractEventJournalBasicTest

### ISSUE THREAD

**Issue by pveentjer** [hazelcast/hazelcast#16996]
When running AbstractEventJournalBasicTest I can see NPE's in the output

```
java.lang.NullPointerException: null
	at com.hazelcast.multimap.impl.MultiMapService.getStats(MultiMapService.java:496) ~[classes/:?]
	at com.hazelcast.multimap.impl.MultiMapService.provideDynamicMetrics(MultiMapService.java:562) ~[classes/:?]
	at com.hazelcast.internal.metrics.impl.MetricsCollectionCycle.collectDynamicMetrics(MetricsCollectionCycle.java:88) ~[classes/:?]
	at com.hazelcast.internal.metrics.impl.MetricsRegistryImpl.collect(MetricsRegistryImpl.java:316) ~[classes/:?]
	at com.hazelcast.internal.metrics.impl.MetricsService.collectMetrics(MetricsService.java:160) ~[classes/:?]
	at com.hazelcast.internal.metrics.impl.MetricsService.collectMetrics(MetricsService.java:154) ~[classes/:?]
	at com.hazelcast.spi.impl.executionservice.impl.DelegateAndSkipOnConcurrentExecutionDecorator$DelegateDecorator.run(DelegateAndSkipOnConcurrentExecutionDecorator.java:77) [classes/:?]
	at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217) [classes/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_241]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_241]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76) [classes/:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) [classes/:?]
```

**Comment by pveentjer** [comment]
it appears to choke on this:

```
   MultiMapPartitionContainer container = partitionContainers[i];
   if (container.containerMap.isEmpty()) {
                continue;
   }
```
When debugging I see that the container is null.
