### ISSUE TITLE
HazelcastProxyFactoryTest testProxyHazelcastInstanceClasses_ofSameVersion_areSame

### ISSUE THREAD

**Issue by lazerion** [hazelcast/hazelcast#17000]
- Fails on `Hazelcast-4.master-IbmJDK8-fips-nightly`, also `Hazelcast-4.master-nightly`
- Fails on [Build #162 (May 19, 2020 9:11:36 AM)](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-4.master-IbmJDK8-fips-nightly/162/testReport/com.hazelcast.test.starter.test/HazelcastProxyFactoryTest/testProxyHazelcastInstanceClasses_ofSameVersion_areSame/)
- Error
```
java.lang.reflect.InvocationTargetException
```
- Stacktrace
```
Caused by: java.lang.NoClassDefFoundError: com/hazelcast/internal/serialization/impl/SampleIdentifiedDataSerializable
	at com.hazelcast.internal.serialization.impl.TestSerializerHook.getSerializationType(TestSerializerHook.java:37)
	at com.hazelcast.internal.serialization.impl.SerializerHookLoader.load(SerializerHookLoader.java:63)
	at com.hazelcast.internal.serialization.impl.SerializerHookLoader.<init>(SerializerHookLoader.java:55)
	at com.hazelcast.internal.serialization.impl.DefaultSerializationServiceBuilder.registerSerializerHooks(DefaultSerializationServiceBuilder.java:310)
	at com.hazelcast.internal.serialization.impl.DefaultSerializationServiceBuilder.build(DefaultSerializationServiceBuilder.java:238)
	at com.hazelcast.internal.serialization.impl.DefaultSerializationServiceBuilder.build(DefaultSerializationServiceBuilder.java:55)
	at com.hazelcast.instance.impl.DefaultNodeExtension.createSerializationService(DefaultNodeExtension.java:252)
	at com.hazelcast.instance.impl.Node.<init>(Node.java:247)
	at com.hazelcast.instance.impl.HazelcastInstanceImpl.createNode(HazelcastInstanceImpl.java:147)
	at com.hazelcast.instance.impl.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:116)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:241)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:220)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:158)
	at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:57)
```
- Possible commit (commit: 15f8670) 

kindly check

**Comment by vbekiaris** [comment]
#16961 and #16780 broke this test and all EE-side compatibility tests. See fix PR description #17102 for details.
