### ISSUE TITLE
Spring Boot 2: Not able to load hazelcast Resources Files under META-INF/services Folder

### ISSUE THREAD

**Issue by bmistry13** [hazelcast/hazelcast#17009]
Hi All,

I have spring boot app and I build it as a single jar file.  

[23-May-2020 00:49:58.353][ERROR][main][com.hazelcast.internal.util.ServiceLoader] JAR entry BOOT-INF/lib/hazelcast-all-4.0.1.jar!/META-INF/services/com.hazelcast.instance.impl.NodeExtension not found in /opt/xxx/xxx/spring-boot/spring-boot.jar
java.io.FileNotFoundException: JAR entry BOOT-INF/lib/hazelcast-all-4.0.1.jar!/META-INF/services/com.hazelcast.instance.impl.NodeExtension not found in /opt/xxx/xxx/spring-boot/spring-boot.jar
        at java.base/sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:147)
        at java.base/sun.net.www.protocol.jar.JarURLConnection.getInputStream(JarURLConnection.java:155)
        at java.base/java.net.URL.openStream(URL.java:1139)
        at com.hazelcast.internal.util.ServiceLoader.parse(ServiceLoader.java:132)
        at com.hazelcast.internal.util.ServiceLoader.getServiceDefinitions(ServiceLoader.java:92)
        at com.hazelcast.internal.util.ServiceLoader.classIterator(ServiceLoader.java:78)
        at com.hazelcast.instance.impl.NodeExtensionFactory.create(NodeExtensionFactory.java:69)
        at com.hazelcast.instance.impl.DefaultNodeContext.createNodeExtension(DefaultNodeContext.java:60)

  
**Describe the bug**
Spring Boot 2 does not start up when Hazel cast Server Bean is not coming up due to the exception listed above.

**Expected behavior**
Hazel cast should be able to load its resources from spring-boot.jar.  Use java.lang.ClassLoader.getResourceAsStream() to load resource rather then using URL and then opening connection.

**To Reproduce**

1. Build Any Spring Boot App with a single jar version 2.3.0.RELEASE
3. Add bean definition to initialize 
HazelcastInstance instance = Hazelcast.newHazelcastInstance(config);

**Additional context**

Work around:

Copy following resources into your main top-level spring boot project under src/main/resources/META-INF/services

com.hazelcast.client.impl.ClientExtension
com.hazelcast.com.fasterxml.jackson.core.JsonFactory
com.hazelcast.DataSerializerHook
com.hazelcast.instance.impl.NodeExtension
com.hazelcast.PortableHook
com.hazelcast.SerializerHook
com.hazelcast.spi.discovery.DiscoveryStrategyFactory
com.hazelcast.spi.impl.servicemanager.ServiceDescriptorProvider
javax.cache.spi.CachingProvider

**Comment by bmistry13** [comment]
org.springframework.boot.loader.PropertiesLauncher is broken in 2.3.0.  Sorry It is not issue.
