### ISSUE TITLE
ClientReliableTopicOnClusterRestartTest shouldFail_OnClusterRestart_whenDataLoss_notLossTolerant

### ISSUE THREAD

**Issue by lazerion** [hazelcast/hazelcast#17015]
- Fails on `Hazelcast-4.master-OracleJDK8`
- Fails on [Build #94 (May 27, 2020 6:10:04 AM)](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-4.master-OracleJDK8/94/testReport/junit/com.hazelcast.client.topic/ClientReliableTopicOnClusterRestartTest/shouldFail_OnClusterRestart_whenDataLoss_notLossTolerant/)
- Stacktrace
```
junit.framework.AssertionFailedError
	at junit.framework.Assert.fail(Assert.java:55)
	at junit.framework.Assert.assertTrue(Assert.java:22)
	at junit.framework.Assert.assertTrue(Assert.java:31)
	at junit.framework.TestCase.assertTrue(TestCase.java:201)
	at com.hazelcast.client.topic.ClientReliableTopicOnClusterRestartTest.lambda$shouldFail_OnClusterRestart_whenDataLoss_notLossTolerant$5(ClientReliableTopicOnClusterRestartTest.java:187)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1242)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1259)
	at com.hazelcast.client.topic.ClientReliableTopicOnClusterRestartTest.shouldFail_OnClusterRestart_whenDataLoss_notLossTolerant(ClientReliableTopicOnClusterRestartTest.java:185)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```
- Noticed in logs
```
MessageListener com.hazelcast.client.topic.ClientReliableTopicOnClusterRestartTest$1@62206c20 on topic: topic. Reason: Unhandled exception, message: Client is shutting down
com.hazelcast.client.HazelcastClientNotActiveException: Client is shutting down
	at com.hazelcast.client.impl.spi.impl.ClientInvocation.notifyException(ClientInvocation.java:261) ~[classes/:?]
	at com.hazelcast.client.impl.spi.impl.ClientInvocationServiceImpl.shutdown(ClientInvocationServiceImpl.java:273) ~[classes/:?]
	at com.hazelcast.client.impl.clientside.HazelcastClientInstanceImpl.doShutdown(HazelcastClientInstanceImpl.java:763) ~[classes/:?]
	at com.hazelcast.client.impl.clientside.LifecycleServiceImpl.doShutdown(LifecycleServiceImpl.java:172) ~[classes/:?]
	at com.hazelcast.client.impl.clientside.LifecycleServiceImpl.terminate(LifecycleServiceImpl.java:155) ~[classes/:?]
	at com.hazelcast.client.test.TestHazelcastFactory.terminateAll(TestHazelcastFactory.java:177) ~[test-classes/:?
```
kindly check.

**Comment by lazerion** [comment]
- Similar failure on `Hazelcast-4.maintenance-CorrettoJDK8`
- Fails on [Build #65 (May 28, 2020 2:12:05 AM)](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-4.maintenance-CorrettoJDK8/65/testReport/junit/com.hazelcast.client.topic/ClientReliableTopicOnClusterRestartTest/shouldContinue_OnClusterRestart_whenDataLoss_LossTolerant_afterInvocationTimeout/)

**Comment by sancar** [comment]
Failed again here:

http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/2231/testReport/junit/com.hazelcast.client.topic/ClientReliableTopicOnClusterRestartTest/shouldFail_OnClusterRestart_whenDataLoss_notLossTolerant/

```
junit.framework.AssertionFailedError
	at junit.framework.Assert.fail(Assert.java:55)
	at junit.framework.Assert.assertTrue(Assert.java:22)
	at junit.framework.Assert.assertTrue(Assert.java:31)
	at junit.framework.TestCase.assertTrue(TestCase.java:201)
	at com.hazelcast.client.topic.ClientReliableTopicOnClusterRestartTest.lambda$shouldFail_OnClusterRestart_whenDataLoss_notLossTolerant$5(ClientReliableTopicOnClusterRestartTest.java:187)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1248)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1350)
	at com.hazelcast.client.topic.ClientReliableTopicOnClusterRestartTest.shouldFail_OnClusterRestart_whenDataLoss_notLossTolerant(ClientReliableTopicOnClusterRestartTest.java:185)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```
