### ISSUE TITLE
ClientInvocationFutureTest test_applyEither

### ISSUE THREAD

**Issue by lazerion** [hazelcast/hazelcast#17099]
- Fails on `Hazelcast-4..maintenance-ZingJDK8`
- Fails on [Build #183 (Jun 16, 2020 10:56:24 PM)](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-4..maintenance-ZingJDK8/183/testReport/junit/com.hazelcast.client.impl.spi.impl/ClientInvocationFutureTest/test_applyEither/)
- Error
```
expected:<null> but was:<ClientMessage{connection=null, length=42, operation=null, isRetryable=false, correlationId=0, messageType=10201, isEvent=false, isfragmented=false}>
```
- Stacktrace
```
ava.lang.AssertionError: expected:<null> but was:<ClientMessage{connection=null, length=42, operation=null, isRetryable=false, correlationId=0, messageType=10201, isEvent=false, isfragmented=false}>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.client.impl.spi.impl.ClientInvocationFutureTest.test_applyEither(ClientInvocationFutureTest.java:295)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```
- Possible commits
```
CP Client message tasks should not deserialize responses (detail / githubweb)
[BACKPORT] Fixes interoperability issues with CompletableFuture (#17048) (detail / githubweb)
```

kindly check.

**Comment by vbekiaris** [comment]
See [here](https://github.com/hazelcast/hazelcast/pull/17100/files#r441615740) for an explanation of test failures. Fix PRs #17100 & #17101
