### ISSUE TITLE
Classloader problem using StreamSerializer in 3.12.6

### ISSUE THREAD

**Issue by janbartel** [hazelcast/hazelcast#17114]
Using a custom StreamSerializer to serialize a class, in the read(ObjectDataInput in) method, I need to use the thread context classloader in order to be able to properly deserialize the object. However, from a stack trace, I can see that the thread context classloader is not being used.

Doing: 

`IMap.set("foo", sessionData); //where sessionData is a class with a custom StreamSerializer`

I get:

> 2020-06-19 12:34:44.734:ERROR:com.hazelcast.map.impl.operation.SetOperation:hz.SESSION_TEST_350314772.partition-operation.thread-0: [192.168.1.8]:5701 [dev] [3.12.6] java.io.IOException: java.lang.ClassNotFoundException: Proxyable
> com.hazelcast.nio.serialization.HazelcastSerializationException: java.io.IOException: java.lang.ClassNotFoundException: Proxyable
> 	at com.hazelcast.internal.serialization.impl.SerializationUtil.handleException(SerializationUtil.java:70)
> 	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:193)
> 	at com.hazelcast.map.impl.record.Records.tryStoreIntoCache(Records.java:153)
> 	at com.hazelcast.map.impl.record.Records.getValueOrCachedValue(Records.java:120)
> 	at com.hazelcast.map.impl.recordstore.AbstractRecordStore.saveIndex(AbstractRecordStore.java:162)
> 	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.putInternal(DefaultRecordStore.java:713)
> 	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.set(DefaultRecordStore.java:684)
> 	at com.hazelcast.map.impl.operation.SetOperation.run(SetOperation.java:39)
> 	at com.hazelcast.spi.Operation.call(Operation.java:170)
> 	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:210)
> 	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:199)
> 	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:147)
> 	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:125)
> 	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:110)

Proxyable is my class that is only visible to the specific thread context class loader I set before calling IMap.set().

In https://github.com/hazelcast/hazelcast/issues/723 the solution was to ensure that if the classloader in the configuration is null, then the thread context classloader will be null. However, I can see at https://github.com/hazelcast/hazelcast/blob/v3.12.6/hazelcast/src/main/java/com/hazelcast/nio/ClassLoaderUtil.java#L145 that if the classloader passed in is null, then the classloader that loaded the ClassLoaderUtil class is used instead.

Is there any way to force the use of the thread context classloader? Please note that it is not possible for me to set a classloader to use on the configuration, as there will be many different classloaders that need to be used to deserialize objects stored in hazelcast.

**Comment by mmedenjak** [comment]
Hi @janbartel ! Thank you for the report. I don't know the answer but I'm adding this to the current milestone so we take a look.

**Comment by janbartel** [comment]
@mmedenjak thanks. Another datapoint for you:  I just tried this with 4.0.1, but I have the same problem.

**Comment by jerrinot** [comment]
hello @janbartel,

the issue here is that you have an index on the map. In order to index an entry the entry must be deserialized (unless the entry uses the Portable serialization). So far so good. 

The problem: Deserialization is happening on a partition thread which WILL NOT have an access to TCCL you are setting before calling `map.set()`. It could be happening even on a remote server. 

I see this as possible solutions:
1. Use Portable serialization. This way an index can be created without deserilizating the object at all.
2. Don't use index. Likely this is not a solution for you for performance reasons. 
3. Handle serialization inside your `StreamSerializer`. 

Let me elaborate #3: 
I am assuming your current `StreamSerializer` implementation only delegates to methods such as `read/writeObject()`, `read/writeFoo()`, `read/writeBar()`, etc. Instead the `StreamSerializer` could use whatever strategy to turn `Proxyable` into a byte array and then use the same strategy during deserilization. Essentially your `StreamSerializer` implementation would own the process of converting `Proxyable` into byte array and vice versa. This way you would have a fine control over classloadering during deserialization. 

I foresee one possible problem with this strategy: Even your `StreamSerilizer` may not have the knowledge which classloader to use. As that's only set on the thread calling `map.set()`. The `set()` method can result in a remote operation and obviously the remote side has no knowledge about TCCL set by the caller. And if when it's a local operation it's still running on a different thread. If that's the case then you will have to propagate the information which classloader to use. Again, that's something your `StreamSerilizaer` could do - possible include some "classloader id" in the serializaed blobs and then use this ID to set the right TCCL during deserization. 

I'm assuming you are embedding Hazelcast in some multi-tenant system, perhaps an application server/container? Can you please confirm that? Our friends from [Payara](https://www.payara.fish/) have been facing similar issues, I believe @lprimak from the Payara dev team could shed some light into their solution.

**Comment by jerrinot** [comment]
@janbartel I am assuming [this](https://github.com/eclipse/jetty.project/blob/jetty-10.0.x/jetty-hazelcast/src/main/java/org/eclipse/jetty/hazelcast/session/SessionDataSerializer.java#L38) is the Serializer? Do you have a test case I could have a look? Or perhaps a list of steps to reproduce it. I'm not a Jetty expert, but I would like to help, this is an important use-case.

**Comment by janbartel** [comment]
@jerrinot thanks for taking an interest in this problem.

I don't have a simple test case for you unfortunately, but I can explain how we use hazelcast and point you to some existing classes. We use hazelcast in jetty to store/distribute http session data. As the attributes of the http session can contain a mix of classes, some of which may exist on the server's classpath, and some of which may only exist on the webapp's classpath, we need to do some classloading swizzling when serializing and deserializing to ensure the right classloader is being used.

Some starting points for you:
Here's the StreamSerializer we have:  https://github.com/eclipse/jetty.project/blob/jetty-10.0.x/jetty-hazelcast/src/main/java/org/eclipse/jetty/hazelcast/session/SessionDataSerializer.java
Here's the generic session attribute serialization/deserialization mechanism:  https://github.com/eclipse/jetty.project/blob/jetty-10.0.x/jetty-server/src/main/java/org/eclipse/jetty/server/session/SessionData.java#L73
Here's where we interact with Hazelcast to store/retrieve session data: https://github.com/eclipse/jetty.project/blob/jetty-10.0.x/jetty-hazelcast/src/main/java/org/eclipse/jetty/hazelcast/session/HazelcastSessionDataStore.java
Here's where we configure our hazelcast interface: https://github.com/eclipse/jetty.project/blob/jetty-10.0.x/jetty-hazelcast/src/main/java/org/eclipse/jetty/hazelcast/session/HazelcastSessionDataStoreFactory.java

Our test cases that won't work with hazelcast due to the need to switch classloaders are:
https://github.com/eclipse/jetty.project/blob/jetty-10.0.x/tests/test-sessions/test-hazelcast-sessions/src/test/java/org/eclipse/jetty/hazelcast/session/HazelcastSessionDataStoreTest.java#L80
https://github.com/eclipse/jetty.project/blob/jetty-10.0.x/tests/test-sessions/test-hazelcast-sessions/src/test/java/org/eclipse/jetty/hazelcast/session/HazelcastSessionDataStoreTest.java#L92

Sorry that this is only a rudimentary guide for you - if you have any questions, please ask and I'll explain. It's also quite possible that we're not using hazelcast with the right or best configuration for our use-case, so any hints you have for us would be gratefully accepted.

**Comment by lprimak** [comment]
@janbartel This problem I believe is solved by my TenantControl PR #17184 which is slated to go into 4.1

**Comment by lprimak** [comment]
See issue https://github.com/hazelcast/hazelcast/issues/10875 and it's derivatives

**Comment by janbartel** [comment]
@lprimak thanks for the links, very interesting. Looks like with the PayaraHazelcastSerializer, you're taking responsibility for serializing everything that is stored in hazelcast, and storing the id of the context to which the object belongs so you know effectively which classloader should deserialize it. 

We're doing something similar, where we need to know which classloader should deserialize which session attribute of our org.eclipse.jetty.server.session.SessionData. I will experiment with your approach of using the GlobalSerializerConfig, and see if that helps us. I'll report back here. Thanks again for the pointers.

**Comment by lprimak** [comment]
ok, glad to help!

**Comment by mmedenjak** [comment]
One more comment, @jerrinot 's comment about using this approach in the client-server architecture still holds. If you're using client-server architecture, the information about which classloader to use will somehow need to be propagated from the client to the server/member, which is not something we support out-of-the-box and it's not covered by the mentioned tenant control PR. You may embed this information in some header of your domain objects, that you will write and read before actually handling user classes.

**Comment by lprimak** [comment]
Just FYI TenantControl has been a part of Hazelcast for a while now, so fell free to use if needed.
