### ISSUE TITLE
IllegalStateException is thrown instead of HazelcastInstanceNotActiveException

### ISSUE THREAD

**Issue by bergander** [hazelcast/hazelcast#17120]
**Please describe the problem you are trying to solve**
According to issue #12233 all exceptions thrown to the user should extend `HazelcastException`. This is not the case in the CP subsystem session where a generic `IllegalStateException` is thrown  instead when Hazelcast is shutdown. 

```
Exception in thread "Thread-2" java.lang.IllegalStateException: Session manager is already shut down!
	at com.hazelcast.internal.util.Preconditions.checkState(Preconditions.java:355)
	at com.hazelcast.cp.internal.session.AbstractProxySessionManager.getOrCreateSession(AbstractProxySessionManager.java:194)
	at com.hazelcast.cp.internal.session.AbstractProxySessionManager.acquireSession(AbstractProxySessionManager.java:120)
	at com.hazelcast.cp.internal.session.SessionAwareProxy.acquireSession(SessionAwareProxy.java:47)
	at com.hazelcast.cp.internal.datastructures.lock.proxy.AbstractFencedLockProxy.lockAndGetFence(AbstractFencedLockProxy.java:119)
	at com.hazelcast.cp.internal.datastructures.lock.proxy.AbstractFencedLockProxy.lock(AbstractFencedLockProxy.java:76)
```

**Please describe the desired behavior**
The old lock implementation threw a `HazelcastInstanceNotActiveException` which seems more reasonable in this case and would allow better error handling for the user.

**Comment by mmedenjak** [comment]
Hi @bergander ! Thank you for the issue report. The issue you've linked requires that we change all existing user-facing exceptions to extend `HazelcastException` and it doesn't serve as a guarantee that we actually do at the moment. It's something that we still have to address, as you've noticed. Now, regarding your case, I'd say this was an oversight on our side while replacing the lock implementations. Unfortunately, though, we cannot change this behaviour in a minor release as all behaviour should be backwards compatible in minor releases.

We'll keep this issue around and I'll also cc @mdogan and @petrpleshachkov here, maybe they have a different view on this matter.

**Comment by mdogan** [comment]
I agree this was really an oversight. `HazelcastInstanceNotActiveException` would be a more suitable exception type in this case.

`HazelcastInstanceNotActiveException` is already an expected exception when a member/client is shutting down. So I think we can change this behaviour. For the ones handling `IllegalStateException` in their code, that path will be obsolete.

**Comment by mmedenjak** [comment]
Moving back to 4.1 as there is already a simple fix PR for this.
