### ISSUE TITLE
Client should not retry on com.hazelcast.client.AuthenticationException

### ISSUE THREAD

**Issue by cangencer** [hazelcast/hazelcast#17136]
As AuthenticationException is not an intermittent error, the client should not keep trying to connect if such an exception is encountered.

**Comment by sancar** [comment]
There is a test that prevents me to do the change. Note that the test was introduced in 3.5.5. 
https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/test/java/com/hazelcast/client/ClientRegressionWithRealNetworkTest.java#L65

Short description, there could be other clusters on in the address space that the client will try to connect. The client should continue to try other addresses to be able to find the correct address. 
@cangencer If that makes sense, I would like to close the issue saying that implementation and behaviour are expected.

**Comment by asimarslan** [comment]
We can introduce a new feature that prevents the client from retrying on Authentication exception but we cannot change the current behavior for the reasons Sancar shared above.

**Comment by cangencer** [comment]
To me, it sounds like unintuitive behavior because if I configure the client to connect to localhost without a specific port, and have wrong cluster name, it will try localhost:5701 and get the authentication exception, then try localhost:5702 and localhost:5703. That doesn't feel great or user friendly to me.

**Comment by asimarslan** [comment]
trying/scanning ports is a feature itself. Port scan can be simply omitted by setting a specific port. Giving up on the first port attempt feels more user-unfriendly to me. Omitting the port means to try multiple ports, and not means just use the default port.
If that's the intention, this is a big behavior change and I think we shouldn't change it.

**Comment by kwart** [comment]
I see the point in trying another port number, but we retry the same port too

```java
Config config = new Config();
config.getNetworkConfig().getJoin().getMulticastConfig().setEnabled(false);
config.getSecurityConfig().setEnabled(true).setMemberRealmConfig("realm", new RealmConfig()
        .setUsernamePasswordIdentityConfig("u", "p"));
PermissionConfig perm = new PermissionConfig(PermissionType.ALL, "*", null);
config.getSecurityConfig().addClientPermissionConfig(perm);
HazelcastInstance hz = Hazelcast.newHazelcastInstance(config);

ClientConfig clientConfig = new ClientConfig();
clientConfig.getNetworkConfig().addAddress("127.0.0.1:5701");
clientConfig.getSecurityConfig().setUsernamePasswordIdentityConfig("u", "wrong");
HazelcastInstance client = HazelcastClient.newHazelcastClient(clientConfig);
```

Then this part of the output is suspicious:
```
16:19:38,206  WARN |test3| - [ClientConnectionManager] test3 - hz.client_1 [dev] [4.2-SNAPSHOT] Exception during initial connection to [127.0.0.1]:5701: com.hazelcast.client.AuthenticationException: Authentication failed. The configured cluster name on the client (see ClientConfig.setClusterName()) does not match the one configured in the cluster or the credentials set in the Client security config could not be authenticated
16:19:38,206  WARN |test3| - [ClientConnectionManager] test3 - hz.client_1 [dev] [4.2-SNAPSHOT] Unable to get live cluster connection, retry in 1000 ms, attempt: 1 , cluster connect timeout: 20000 seconds , max backoff millis: 30000
```

**Comment by mmedenjak** [comment]
@hazelcast/apis do you think this should go into 5.0, or can we move it out?

**Comment by sancar** [comment]
Hi Joseph(@kwart ), it has been long time since I can take a look at this again. 

If we don't allow a client to connect to an address(hostname:port) after a authentication problem, this means that client will never again try to connect to that address during its lifetime, right ?

**Comment by kwart** [comment]
> If we don't allow a client to connect to an address(hostname:port) after a authentication problem, this means that client will never again try to connect to that address during its lifetime, right ?

Yes, I would expect so. I think the fail-fast approach is usually the best. I'm fine with retrying when there is a network issue for instance. But the authentication failure means either wrong credentials or a misconfiguration somewhere. We could have a configuration option that would do the repeated tries for these types of problems, but I wouldn't have it enabled by default.

I would personally cancel even retries on other ports if the client receives a message saying authentication failed.

Nevertheless, this is getting rather to a state, where PM decision would help to say what's the proper "Hazelcasty" way of resolving the issue.

**Comment by sancar** [comment]
@cangencer @kwart . We have discussed this within the API's team and here are the outcomes. 

1. Authentication exception seems like an permanent failure per address from one perspective but an address pair does not mean the same hazelcast member always(in places like kubernetes, same address can be mapped to a different pod)

2. Going back to this test we have, 
https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/test/java/com/hazelcast/client/ClientRegressionWithRealNetworkTest.java#L65

When cluster name does not match server sends AuthenticationException. It does not look correct but this is what we have historically. So it does not mean the security configuration is wrong, but it means client is trying to connect a wrong address. 
So it brings the following question, lets say user configured 3 addresses in the client config. 
Client tried the first address and could not find a member(or find a different cluster on the given address), should it shutdown ?
Or should it continue to try other two addresses ? 
Depending on your answers, I will come up with other arguments, keeping it short for now,

3. Another usecase, that just comes to my mind could be as follows: 
Also consider scenarios like Rolling Upgrade/Cluster Restart. Client is already started and working. 
User wants to restart the servers/a single member, but accidentally broke  security config and restarted the whole cluster/single member. 
Clients may get AuthenticationException in this case:
     - We can close the client, which will break lots of services and those services needs restart.
     - We can make the client retry AuthenticationException. The client services will temporarily fail, as soon as the member security config is fixed, the clients can continue to their work without requiring any intervention.

**Comment by Colince-Temoi** [comment]
Hi guys, I am new on leveraging HazelCast. But I found this trail and I am experiencing an issue almost same as waht has been discussed here. I have 3 applications, say App1(Gateway Application), App2(Service1) and App3(Service2).  For all of them I have maintained the below programmatic HazelCast configurations:
.../
    Config hazelcastConfig = new Config();
    hazelcastConfig.setClusterName("esb-cluster");
    
    NetworkConfig networkConfig = hazelcastConfig.getNetworkConfig();
    JoinConfig joinConfig = networkConfig.getJoin();

   joinConfig.getMulticastConfig().setEnabled(false);

   TcpIpConfig tcpIpConfig = joinConfig.getTcpIpConfig();
    tcpIpConfig.setEnabled(true);
    tcpIpConfig.setMembers(Arrays.asList("<Ip_address>:5701", "<Ip_address>:5702", "<Ip_address>:5703"));

  VertxOptions options = new VertxOptions().setClusterManager(clusterManager);

    Vertx.clusteredVertx(options, res -> {
      if (res.succeeded()) {
        Vertx vertx = res.result();
   ..../
When I start all these 3 applications, they all connect to the cluster manager as can be seen below:

Members {size:3, ver:3} [ 
                      Member [<Ip_address>]:5701 - d38e920a-3e5d-41da-a245-65e3db77cbce this 
                      Member [<Ip_address>]:5702 - ba9c5b64-3f08-4494-a47f-3cee3733cf27 
                      Member [<Ip_address>]:5703 - 94d910c0-7b09-4e85-bd87-709a26f84dbc
 ]

Notes:
-------
1. When I send a request from App1(Gateway Application) to App2(Service1), all is working as expected in terms, request, Processing and response back to my client application (Postman)
2. When I send a request from App1(Gateway Application) to App3(Service2) the request gets through the gateway application just as expected into App3(Service2) and I can confirm a few methods getting executed. But the execution of my defined logic halts and I start seeing the below in my logs:

..../
INFO: Loading 'hazelcast-client-default.xml' from the classpath.
May 07, 2025 9:51:47 AM com.hazelcast.client.impl.spi.ClientInvocationService
INFO: hz.client_1 [dev] [5.3.5] Running with 2 response threads, dynamic=true
May 07, 2025 9:51:47 AM com.hazelcast.core.LifecycleService
INFO: hz.client_1 [dev] [5.3.5] HazelcastClient 5.3.5 (20231024 - 0a8cc63) is STARTING
May 07, 2025 9:51:47 AM com.hazelcast.core.LifecycleService
INFO: hz.client_1 [dev] [5.3.5] HazelcastClient 5.3.5 (20231024 - 0a8cc63) is STARTED
May 07, 2025 9:51:47 AM com.hazelcast.client.impl.connection.ClientConnectionManager
INFO: hz.client_1 [dev] [5.3.5] Trying to connect to cluster: dev
May 07, 2025 9:51:47 AM com.hazelcast.client.impl.connection.ClientConnectionManager
INFO: hz.client_1 [dev] [5.3.5] Trying to connect to [127.0.0.1]:5701
May 07, 2025 9:51:47 AM com.hazelcast.client.impl.connection.tcp.TcpClientConnection
WARNING: hz.client_1 [dev] [5.3.5] ClientConnection{alive=false, connectionId=1, channel=NioChannel{/127.0.0.1:40903->/127.0.0.1:5701}, remoteAddress=null, lastReadTime=2025-05-07 09:51:47.783, lastWriteTime=2025-05-07 09:51:47.769, closedTime=2025-05-07 09:51:47.785} closed. Reason: Failed to authenticate connection
com.hazelcast.client.AuthenticationException: Authentication failed. The configured cluster name on the client (see ClientConfig.setClusterName()) does not match the one configured in the cluster or the credentials set in the Client security config could not be authenticated
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.checkAuthenticationResponse(TcpClientConnectionManager.java:1140)
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.onAuthenticated(TcpClientConnectionManager.java:1001)
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.getOrConnectToAddress(TcpClientConnectionManager.java:667)
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.lambda$doConnectToCandidateCluster$3(TcpClientConnectionManager.java:550)
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.connect(TcpClientConnectionManager.java:495)
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.doConnectToCandidateCluster(TcpClientConnectionManager.java:549)
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.doConnectToCluster(TcpClientConnectionManager.java:445)
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.connectToCluster(TcpClientConnectionManager.java:406)
	at com.hazelcast.client.impl.clientside.HazelcastClientInstanceImpl.start(HazelcastClientInstanceImpl.java:388)
	at com.hazelcast.client.H
..../



The below second part of the log happens to continue infinitely until I Ctrl + C


..../
May 07, 2025 9:51:47 AM com.hazelcast.client.impl.connection.ClientConnectionManager
WARNING: hz.client_1 [dev] [5.3.5] Exception during initial connection to [127.0.0.1]:5701: com.hazelcast.client.AuthenticationException: Authentication failed. The configured cluster name on the client (see ClientConfig.setClusterName()) does not match the one configured in the cluster or the credentials set in the Client security config could not be authenticated
May 07, 2025 9:51:47 AM com.hazelcast.client.impl.connection.ClientConnectionManager
INFO: hz.client_1 [dev] [5.3.5] Trying to connect to [127.0.0.1]:5702
May 07, 2025 9:51:47 AM com.hazelcast.client.impl.connection.tcp.TcpClientConnection
WARNING: hz.client_1 [dev] [5.3.5] ClientConnection{alive=false, connectionId=2, channel=NioChannel{/127.0.0.1:60161->/127.0.0.1:5702}, remoteAddress=null, lastReadTime=2025-05-07 09:51:47.831, lastWriteTime=2025-05-07 09:51:47.815, closedTime=2025-05-07 09:51:47.832} closed. Reason: Failed to authenticate connection
com.hazelcast.client.AuthenticationException: Authentication failed. The configured cluster name on the client (see ClientConfig.setClusterName()) does not match the one configured in the cluster or the credentials set in the Client security config could not be authenticated
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.checkAuthenticationResponse(TcpClientConnectionManager.java:1140)
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.onAuthenticated(TcpClientConnectionManager.java:1001)
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.getOrConnectToAddress(TcpClientConnectionManager.java:667)
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.lambda$doConnectToCandidateCluster$3(TcpClientConnectionManager.java:550)
	at com.haz
.../

On Checking the logs on the other 2 applications i.e., App1(Gateway Application) to App2(Service1) I can see the below:

App2(Service1)  - This is happening infinitely again until I kill the service
----------------------
May 07, 2025 9:51:47 AM com.hazelcast.client.impl.protocol.task.AuthenticationMessageTask
WARNING: [Ip_address>]:5702 [esb-cluster] [5.3.5] Received auth from Connection[id=3, /127.0.0.1:5702->/127.0.0.1:60161, qualifier=null, endpoint=null, remoteUuid=null, alive=true, connectionType=NONE, planeIndex=-1] with clientUuid 75ac7c87-b987-4b05-96fd-e670f60b58d1 and clientName hz.client_1, authentication failed
May 07, 2025 9:51:47 AM com.hazelcast.internal.server.tcp.TcpServerConnection
INFO: [Ip_address>]:5702 [esb-cluster] [5.3.5] Connection[id=3, /127.0.0.1:5702->/127.0.0.1:60161, qualifier=null, endpoint=null, remoteUuid=null, alive=false, connectionType=NONE, planeIndex=-1] closed. Reason: Connection closed by the other side
May 07, 2025 9:51:48 AM com.hazelcast.client.impl.protocol.task.AuthenticationMessageTask

..../


 App1(Gateway Application) - This is happening infinitely again until I kill the service
----------------------
May 07, 2025 9:51:47 AM com.hazelcast.client.impl.protocol.task.AuthenticationMessageTask
WARNING: [Ip_address>]:5701 [esb-cluster] [5.3.5] Received auth from Connection[id=3, /127.0.0.1:5701->/127.0.0.1:40903, qualifier=null, endpoint=null, remoteUuid=null, alive=true, connectionType=NONE, planeIndex=-1] with clientUuid 75ac7c87-b987-4b05-96fd-e670f60b58d1 and clientName hz.client_1, authentication failed
May 07, 2025 9:51:47 AM com.hazelcast.internal.server.tcp.TcpServerConnection
INFO: [Ip_address>]:5701 [esb-cluster] [5.3.5] Connection[id=3, /127.0.0.1:5701->/127.0.0.1:40903, qualifier=null, endpoint=null, remoteUuid=null, alive=false, connectionType=NONE, planeIndex=-1] closed. Reason: Connection closed by the other side
May 07, 2025 9:51:48 AM com.hazelcast.client.impl.protocol.task.AuthenticationMessageTask
WARNING: [Ip_address>]:5701 [esb-cluster] [5.3.5] Received auth from Connection[id=4, /127.0.0.1:5701->/127.0.0.1:37449, qualifier=null, endpoint=null, remoteUuid=null, alive=true, connectionType=NONE, planeIndex=-1] with clientUuid 75ac7c87-b987-4b05-96fd-e670f60b58d1 and clientName hz.client_1, authentication failed
May 07, 2025 9:51:48 AM com.hazelcast.internal.server.tcp.TcpServerConnection

@Holmistr @cangencer  @sancar  @kwart  @asimarslan 

Any help accorded will be highly appreciated. Thank you

**Comment by Colince-Temoi** [comment]
Hi guys, I am new on leveraging HazelCast. But I found this trail and I am experiencing an issue almost same as waht has been discussed here. I have 3 applications, say App1(Gateway Application), App2(Service1) and App3(Service2).  For all of them I have maintained the below programmatic HazelCast configurations:
.../
    Config hazelcastConfig = new Config();
    hazelcastConfig.setClusterName("esb-cluster");
    
    NetworkConfig networkConfig = hazelcastConfig.getNetworkConfig();
    JoinConfig joinConfig = networkConfig.getJoin();

   joinConfig.getMulticastConfig().setEnabled(false);

   TcpIpConfig tcpIpConfig = joinConfig.getTcpIpConfig();
    tcpIpConfig.setEnabled(true);
    tcpIpConfig.setMembers(Arrays.asList("<Ip_address>:5701", "<Ip_address>:5702", "<Ip_address>:5703"));

  VertxOptions options = new VertxOptions().setClusterManager(clusterManager);

    Vertx.clusteredVertx(options, res -> {
      if (res.succeeded()) {
        Vertx vertx = res.result();
   ..../
When I start all these 3 applications, they all connect to the cluster manager as can be seen below:

Members {size:3, ver:3} [ 
                      Member [<Ip_address>]:5701 - d38e920a-3e5d-41da-a245-65e3db77cbce this 
                      Member [<Ip_address>]:5702 - ba9c5b64-3f08-4494-a47f-3cee3733cf27 
                      Member [<Ip_address>]:5703 - 94d910c0-7b09-4e85-bd87-709a26f84dbc
 ]

Notes:
-------
1. When I send a request from App1(Gateway Application) to App2(Service1), all is working as expected in terms, request, Processing and response back to my client application (Postman)
2. When I send a request from App1(Gateway Application) to App3(Service2) the request gets through the gateway application just as expected into App3(Service2) and I can confirm a few methods getting executed. But the execution of my defined logic halts and I start seeing the below in my logs:

..../
INFO: Loading 'hazelcast-client-default.xml' from the classpath.
May 07, 2025 9:51:47 AM com.hazelcast.client.impl.spi.ClientInvocationService
INFO: hz.client_1 [dev] [5.3.5] Running with 2 response threads, dynamic=true
May 07, 2025 9:51:47 AM com.hazelcast.core.LifecycleService
INFO: hz.client_1 [dev] [5.3.5] HazelcastClient 5.3.5 (20231024 - 0a8cc63) is STARTING
May 07, 2025 9:51:47 AM com.hazelcast.core.LifecycleService
INFO: hz.client_1 [dev] [5.3.5] HazelcastClient 5.3.5 (20231024 - 0a8cc63) is STARTED
May 07, 2025 9:51:47 AM com.hazelcast.client.impl.connection.ClientConnectionManager
INFO: hz.client_1 [dev] [5.3.5] Trying to connect to cluster: dev
May 07, 2025 9:51:47 AM com.hazelcast.client.impl.connection.ClientConnectionManager
INFO: hz.client_1 [dev] [5.3.5] Trying to connect to [127.0.0.1]:5701
May 07, 2025 9:51:47 AM com.hazelcast.client.impl.connection.tcp.TcpClientConnection
WARNING: hz.client_1 [dev] [5.3.5] ClientConnection{alive=false, connectionId=1, channel=NioChannel{/127.0.0.1:40903->/127.0.0.1:5701}, remoteAddress=null, lastReadTime=2025-05-07 09:51:47.783, lastWriteTime=2025-05-07 09:51:47.769, closedTime=2025-05-07 09:51:47.785} closed. Reason: Failed to authenticate connection
com.hazelcast.client.AuthenticationException: Authentication failed. The configured cluster name on the client (see ClientConfig.setClusterName()) does not match the one configured in the cluster or the credentials set in the Client security config could not be authenticated
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.checkAuthenticationResponse(TcpClientConnectionManager.java:1140)
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.onAuthenticated(TcpClientConnectionManager.java:1001)
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.getOrConnectToAddress(TcpClientConnectionManager.java:667)
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.lambda$doConnectToCandidateCluster$3(TcpClientConnectionManager.java:550)
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.connect(TcpClientConnectionManager.java:495)
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.doConnectToCandidateCluster(TcpClientConnectionManager.java:549)
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.doConnectToCluster(TcpClientConnectionManager.java:445)
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.connectToCluster(TcpClientConnectionManager.java:406)
	at com.hazelcast.client.impl.clientside.HazelcastClientInstanceImpl.start(HazelcastClientInstanceImpl.java:388)
	at com.hazelcast.client.H
..../



The below second part of the log happens to continue infinitely until I Ctrl + C
---------------------------------------------------------------------------------------

..../
May 07, 2025 9:51:47 AM com.hazelcast.client.impl.connection.ClientConnectionManager
WARNING: hz.client_1 [dev] [5.3.5] Exception during initial connection to [127.0.0.1]:5701: com.hazelcast.client.AuthenticationException: Authentication failed. The configured cluster name on the client (see ClientConfig.setClusterName()) does not match the one configured in the cluster or the credentials set in the Client security config could not be authenticated
May 07, 2025 9:51:47 AM com.hazelcast.client.impl.connection.ClientConnectionManager
INFO: hz.client_1 [dev] [5.3.5] Trying to connect to [127.0.0.1]:5702
May 07, 2025 9:51:47 AM com.hazelcast.client.impl.connection.tcp.TcpClientConnection
WARNING: hz.client_1 [dev] [5.3.5] ClientConnection{alive=false, connectionId=2, channel=NioChannel{/127.0.0.1:60161->/127.0.0.1:5702}, remoteAddress=null, lastReadTime=2025-05-07 09:51:47.831, lastWriteTime=2025-05-07 09:51:47.815, closedTime=2025-05-07 09:51:47.832} closed. Reason: Failed to authenticate connection
com.hazelcast.client.AuthenticationException: Authentication failed. The configured cluster name on the client (see ClientConfig.setClusterName()) does not match the one configured in the cluster or the credentials set in the Client security config could not be authenticated
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.checkAuthenticationResponse(TcpClientConnectionManager.java:1140)
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.onAuthenticated(TcpClientConnectionManager.java:1001)
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.getOrConnectToAddress(TcpClientConnectionManager.java:667)
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.lambda$doConnectToCandidateCluster$3(TcpClientConnectionManager.java:550)
	at com.haz
.../

On Checking the logs on the other 2 applications i.e., App1(Gateway Application) to App2(Service1) I can see the below:

App2(Service1)  - This is happening infinitely again until I kill the service
----------------------
May 07, 2025 9:51:47 AM com.hazelcast.client.impl.protocol.task.AuthenticationMessageTask
WARNING: [Ip_address>]:5702 [esb-cluster] [5.3.5] Received auth from Connection[id=3, /127.0.0.1:5702->/127.0.0.1:60161, qualifier=null, endpoint=null, remoteUuid=null, alive=true, connectionType=NONE, planeIndex=-1] with clientUuid 75ac7c87-b987-4b05-96fd-e670f60b58d1 and clientName hz.client_1, authentication failed
May 07, 2025 9:51:47 AM com.hazelcast.internal.server.tcp.TcpServerConnection
INFO: [Ip_address>]:5702 [esb-cluster] [5.3.5] Connection[id=3, /127.0.0.1:5702->/127.0.0.1:60161, qualifier=null, endpoint=null, remoteUuid=null, alive=false, connectionType=NONE, planeIndex=-1] closed. Reason: Connection closed by the other side
May 07, 2025 9:51:48 AM com.hazelcast.client.impl.protocol.task.AuthenticationMessageTask

..../


 App1(Gateway Application) - This is happening infinitely again until I kill the service
----------------------
May 07, 2025 9:51:47 AM com.hazelcast.client.impl.protocol.task.AuthenticationMessageTask
WARNING: [Ip_address>]:5701 [esb-cluster] [5.3.5] Received auth from Connection[id=3, /127.0.0.1:5701->/127.0.0.1:40903, qualifier=null, endpoint=null, remoteUuid=null, alive=true, connectionType=NONE, planeIndex=-1] with clientUuid 75ac7c87-b987-4b05-96fd-e670f60b58d1 and clientName hz.client_1, authentication failed
May 07, 2025 9:51:47 AM com.hazelcast.internal.server.tcp.TcpServerConnection
INFO: [Ip_address>]:5701 [esb-cluster] [5.3.5] Connection[id=3, /127.0.0.1:5701->/127.0.0.1:40903, qualifier=null, endpoint=null, remoteUuid=null, alive=false, connectionType=NONE, planeIndex=-1] closed. Reason: Connection closed by the other side
May 07, 2025 9:51:48 AM com.hazelcast.client.impl.protocol.task.AuthenticationMessageTask
WARNING: [Ip_address>]:5701 [esb-cluster] [5.3.5] Received auth from Connection[id=4, /127.0.0.1:5701->/127.0.0.1:37449, qualifier=null, endpoint=null, remoteUuid=null, alive=true, connectionType=NONE, planeIndex=-1] with clientUuid 75ac7c87-b987-4b05-96fd-e670f60b58d1 and clientName hz.client_1, authentication failed
May 07, 2025 9:51:48 AM com.hazelcast.internal.server.tcp.TcpServerConnection

@Holmistr @cangencer  @sancar  @kwart  @asimarslan 

Any help accorded will be highly appreciated. Thank you

**Comment by Holmistr** [comment]
@Colince-Temoi Thanks for the comment.

Unfortunately, all of the above mentioned people (including me) no longer for Hazelcast, so you'll probably have to wait a little for the standard process to have your comment picked up again. I'm sorry, but I can't make any guarantees when that happens.

**Comment by ihsandemir** [comment]
@Colince-Temoi In your shared code, you populated the `hazelcastConfig` but you never used while starting the instances. That is probably your problem.

**Comment by Colince-Temoi** [comment]
> [@Colince-Temoi](https://github.com/Colince-Temoi) In your shared code, you populated the `hazelcastConfig` but you never used while starting the instances. That is probably your problem.

I used it, sorry I missed providing that line where I used it. Here is the code with the missing line:
`Config hazelcastConfig = new Config();
    hazelcastConfig.setClusterName("esb-cluster");
    HazelcastClusterManager clusterManager = new HazelcastClusterManager(hazelcastConfig);
   NetworkConfig networkConfig = hazelcastConfig.getNetworkConfig();
    JoinConfig joinConfig = networkConfig.getJoin();
    joinConfig.getMulticastConfig().setEnabled(false);

  TcpIpConfig tcpIpConfig = joinConfig.getTcpIpConfig();
  tcpIpConfig.setEnabled(true);
  tcpIpConfig.setMembers(Arrays.asList("<Ip_address>:5701", "<Ip_address>:5702", "<Ip_address>:5703"));

  VertxOptions options = new VertxOptions().setClusterManager(clusterManager);
 Vertx.clusteredVertx(options, res -> {
      if (res.succeeded()) {
        Vertx vertx = res.result();
         .......
`

**Comment by ihsandemir** [comment]
You probably missed proper cluster name config in your client applications. can you share that code?
