### ISSUE TITLE
AtomicRefIsolatedServersTest - instance not shut down 

### ISSUE THREAD

**Issue by lazerion** [hazelcast/hazelcast#17188]
- Fails on `Hazelcast-4.master-OracleJDK8`
- Fails on [Build #100 (Jul 8, 2020 6:10:05 AM)](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-4.master-OracleJDK8/100/testReport/junit/com.hazelcast.client.cp.internal.datastructures.atomicref/AtomicRefIsolatedServersTest/com_hazelcast_client_cp_internal_datastructures_atomicref_AtomicRefIsolatedServersTest/)
- Error
```
Instances haven't been shut down: [HazelcastInstance{name='cool_villani', node=[127.0.0.1]:5702}]
```
- Stacktrace
```
java.lang.IllegalStateException: Instances haven't been shut down: [HazelcastInstance{name='cool_villani', node=[127.0.0.1]:5702}]
	at com.hazelcast.test.AbstractHazelcastClassRunner$1.evaluate(AbstractHazelcastClassRunner.java:308)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
```
- kindly check

**Comment by lazerion** [comment]
- Continues to fails as I see [Build #195 (Jul 22, 2020 5:18:26 AM)](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-4.master-ZingJDK8/195/testReport/com.hazelcast.client.cp.internal.datastructures.atomicref/AtomicRefIsolatedServersTest/com_hazelcast_client_cp_internal_datastructures_atomicref_AtomicRefIsolatedServersTest/)
