### ISSUE TITLE
AdvancedNetworkingCommunicationIntegrationTest testMemcacheConnectionToEndpoints

### ISSUE THREAD

**Issue by lazerion** [hazelcast/hazelcast#17187]
- Fails on `Hazelcast-4.master-IbmJDK8-fips-nightly`
- Fails on [Build #179 (Jul 7, 2020 11:54:07 AM)](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-4.master-IbmJDK8-fips-nightly/179/testReport/junit/com.hazelcast.internal.networking.nio/AdvancedNetworkingCommunicationIntegrationTest/testMemcacheConnectionToEndpoints/)
- Stacktrace
```
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1453)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1477)
	at sun.nio.ch.SelectorImpl.implCloseSelector(SelectorImpl.java:124)
	at java.nio.channels.spi.AbstractSelector.close(AbstractSelector.java:122)
	at net.spy.memcached.MemcachedConnection.shutdown(MemcachedConnection.java:1339)
	at net.spy.memcached.MemcachedClient.shutdown(MemcachedClient.java:2512)
	at net.spy.memcached.MemcachedClient.shutdown(MemcachedClient.java:2474)
	at com.hazelcast.internal.networking.nio.AdvancedNetworkingCommunicationIntegrationTest.testMemcacheCallFailsOnPort(AdvancedNetworkingCommunicationIntegrationTest.java:147)
	at com.hazelcast.internal.networking.nio.AdvancedNetworkingCommunicationIntegrationTest.testMemcacheConnectionToEndpoints(AdvancedNetworkingCommunicationIntegrationTest.java:93)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
```
- Possible jenkins resource related. kindly check.

**Comment by vbekiaris** [comment]
Already fixed by #17309
