### ISSUE TITLE
cluster member freeze sql HD idx ClassCastException: com.hazelcast.query.impl.Comparables.compare(Comparables.java:99)

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#17193]
http://jenkins.hazelcast.com/view/freeze/job/freeze-x2/6/console

/disk1/jenkins/workspace/freeze-x2/4.1-SNAPSHOT/2020_07_09-03_44_11/hd-idx

fail HzMember3HZ fn hzcmd.distributed.PutRandPerson threadId=2 java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.String

http://54.147.27.51/~jenkins/workspace/freeze-x2/4.1-SNAPSHOT/2020_07_09-03_44_11/hd-idx

output/HZ/HzClient3HZ/exception.txt
output/HZ/HzMember2HZ/exception.txt
output/HZ/HzMember4HZ/exception.txt
output/HZ/HzClient4HZ/exception.txt
output/HZ/HzMember1HZ/exception.txt
output/HZ/HzMember3HZ/exception.txt
output/HZ/HzClient2HZ/exception.txt
output/HZ/HzClient1HZ/exception.txt

```
more output/HZ/HzMember3HZ/exception.txt
java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.String
	at java.lang.String.compareTo(String.java:111)
	at com.hazelcast.query.impl.Comparables.compare(Comparables.java:99)
	at com.hazelcast.internal.bplustree.DefaultBPlusTreeKeyComparator.compare(DefaultBPlusTreeKeyComparator.java:35)
	at com.hazelcast.internal.bplustree.HDBTreeNodeBaseAccessor.compareKeys0(HDBTreeNodeBaseAccessor.java:231)
	at com.hazelcast.internal.bplustree.HDBTreeNodeBaseAccessor.compareKeys(HDBTreeNodeBaseAccessor.java:201)
	at com.hazelcast.internal.bplustree.HDBTreeLeafNodeAccessor.remove(HDBTreeLeafNodeAccessor.java:185)
	at com.hazelcast.internal.bplustree.HDBPlusTree.remove(HDBPlusTree.java:570)
	at com.hazelcast.internal.bplustree.HDBPlusTree.remove(HDBPlusTree.java:538)
	at com.hazelcast.query.impl.HDBPlusTreeIndex.remove(HDBPlusTreeIndex.java:44)
	at com.hazelcast.query.impl.HDOrderedConcurrentIndexStore.removeMappingForAttribute(HDOrderedConcurrentIndexStore.java:155)
	at com.hazelcast.query.impl.HDOrderedConcurrentIndexStore.removeInternal(HDOrderedConcurrentIndexStore.java:78)
	at com.hazelcast.query.impl.BaseSingleValueIndexStore.unwrapAndRemoveFromIndex(BaseSingleValueIndexStore.java:147)
	at com.hazelcast.query.impl.BaseSingleValueIndexStore.remove(BaseSingleValueIndexStore.java:107)
	at com.hazelcast.query.impl.AbstractIndex.removeEntry(AbstractIndex.java:156)
	at com.hazelcast.query.impl.Indexes.removeEntry(Indexes.java:291)
	at com.hazelcast.map.impl.recordstore.IndexingMutationObserver.removeIndex(IndexingMutationObserver.java:179)
	at com.hazelcast.map.impl.recordstore.IndexingMutationObserver.onEvictRecord(IndexingMutationObserver.java:80)
	at com.hazelcast.map.impl.recordstore.CompositeMutationObserver.onEvictRecord(CompositeMutationObserver.java:107)
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.evict(DefaultRecordStore.java:444)
	at com.hazelcast.map.impl.eviction.HDEvictorImpl.removeKeys(HDEvictorImpl.java:123)
	at com.hazelcast.map.impl.eviction.HDEvictorImpl.evictRecordStore(HDEvictorImpl.java:94)
	at com.hazelcast.map.impl.eviction.HDEvictorImpl.forceEvictByPercentage(HDEvictorImpl.java:69)
	at com.hazelcast.map.impl.operation.MultipleRecordStoreForcedEviction.forceEvictAndRun(MultipleRecordStoreForcedEviction.java:64)
	at com.hazelcast.map.impl.operation.ForcedEviction.runWithForcedEvictionStrategies(ForcedEviction.java:51)
	at com.hazelcast.map.impl.operation.MapOperation.rerunWithForcedEviction(MapOperation.java:125)
	at com.hazelcast.map.impl.operation.MapOperation.run(MapOperation.java:114)
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:184)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:227)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:216)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:160)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:138)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
```

**Comment by mmedenjak** [comment]
@Danny-Hazelcast before this is fixed, can you rerun these tests with this set to `false`? It should fall back to the old index and the tests should pass.

```
    public static final HazelcastProperty PROPERTY_GLOBAL_HD_INDEX_ENABLED
            = new HazelcastProperty("hazelcast.hd.global.index.enabled", true);
```

**Comment by Danny-Hazelcast** [comment]
https://github.com/hazelcast/hazelcast/pull/17338
