### ISSUE TITLE
cluster split sql hd idx IllegalArgumentException Size must be positive AbstractPoolingMemoryManager.java:175

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#17194]
sh hz-bench-run-jenkins-split hz/stable/hd/pool/hd-idx
http://jenkins.hazelcast.com/view/split/job/split-x/27/console

/disk1/jenkins/workspace/split-x/4.1-SNAPSHOT/2020_07_09-03_42_21/hd-idx Failed

fail HzClient4HZBB fn hzcmd.distributed.PutRandPerson threadId=0 java.lang.IllegalArgumentException: Size must be positive: -409714372

 http://54.147.27.51/~jenkins/workspace/split-x/4.1-SNAPSHOT/2020_07_09-03_42_21/hd-idx

output/HZ/HzMember3HZBB/exception.txt
output/HZ/HzClient5HZBB/exception.txt
output/HZ/HzClient3HZBB/exception.txt
output/HZ/HzClient2HZAA/exception.txt
output/HZ/HzMember2HZAA/exception.txt
output/HZ/HzMember5HZBB/exception.txt
output/HZ/HzMember4HZBB/exception.txt
output/HZ/HzClient1HZAA/exception.txt
output/HZ/HzClient4HZBB/exception.txt
output/HZ/HzMember1HZAA/exception.txt

```
more output/HZ/HzClient4HZBB/exception.txt
java.lang.IllegalArgumentException: Size must be positive: -409714372
	at com.hazelcast.internal.memory.AbstractPoolingMemoryManager.getAddressQueue(AbstractPoolingMemoryManager.java:175)
	at com.hazelcast.internal.memory.AbstractPoolingMemoryManager.allocate(AbstractPoolingMemoryManager.java:57)
	at com.hazelcast.internal.monitor.impl.HDGlobalPerIndexStats$MemoryAllocatorWithStats.allocate(HDGlobalPerIndexStats.java:70)
	at com.hazelcast.internal.bplustree.DefaultBPlusTreeKeyAccessor.cloneNativeMemory(DefaultBPlusTreeKeyAccessor.java:81)
	at com.hazelcast.internal.bplustree.HDBTreeInnerNodeAccessor.clonedEntryKeyAddr(HDBTreeInnerNodeAccessor.java:232)
	at com.hazelcast.internal.bplustree.HDBPlusTree.splitLockedLeafWithParentLocked(HDBPlusTree.java:457)
	at com.hazelcast.internal.bplustree.HDBPlusTree.splitLockedNodeWithParentLocked(HDBPlusTree.java:407)
	at com.hazelcast.internal.bplustree.HDBPlusTree.insert(HDBPlusTree.java:305)
	at com.hazelcast.internal.bplustree.HDBPlusTree.insert(HDBPlusTree.java:257)
	at com.hazelcast.query.impl.HDBPlusTreeIndex.put(HDBPlusTreeIndex.java:40)
	at com.hazelcast.query.impl.HDOrderedConcurrentIndexStore.mapAttributeToEntry(HDOrderedConcurrentIndexStore.java:150)
	at com.hazelcast.query.impl.HDOrderedConcurrentIndexStore.insertInternal(HDOrderedConcurrentIndexStore.java:68)
	at com.hazelcast.query.impl.BaseSingleValueIndexStore.unwrapAndInsertToIndex(BaseSingleValueIndexStore.java:128)
	at com.hazelcast.query.impl.BaseSingleValueIndexStore.insert(BaseSingleValueIndexStore.java:85)
	at com.hazelcast.query.impl.AbstractIndex.putEntry(AbstractIndex.java:141)
	at com.hazelcast.query.impl.Indexes.putEntry(Indexes.java:276)
	at com.hazelcast.map.impl.recordstore.IndexingMutationObserver.saveIndex(IndexingMutationObserver.java:169)
	at com.hazelcast.map.impl.recordstore.IndexingMutationObserver.onPutRecord(IndexingMutationObserver.java:54)
	at com.hazelcast.map.impl.recordstore.CompositeMutationObserver.onPutRecord(CompositeMutationObserver.java:61)
	at com.hazelcast.map.impl.recordstore.AbstractRecordStore.putNewRecord(AbstractRecordStore.java:216)
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.putInternal(DefaultRecordStore.java:771)
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.put(DefaultRecordStore.java:753)
	at com.hazelcast.map.impl.operation.PutOperation.runInternal(PutOperation.java:36)
	at com.hazelcast.map.impl.operation.MapOperation.run(MapOperation.java:112)
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:184)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:227)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:216)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:411)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:438)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:597)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:582)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:541)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:238)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:59)
	at com.hazelcast.client.impl.protocol.task.AbstractPartitionMessageTask.processInternal(AbstractPartitionMessageTask.java:51)
	at com.hazelcast.client.impl.protocol.task.AbstractAsyncMessageTask.processMessage(AbstractAsyncMessageTask.java:71)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:153)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:116)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:180)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:172)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:140)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
```

**Comment by mmedenjak** [comment]
@Danny-Hazelcast before this is fixed, can you rerun these tests with this set to `false`? It should fall back to the old index and the tests should pass.

```
    public static final HazelcastProperty PROPERTY_GLOBAL_HD_INDEX_ENABLED
            = new HazelcastProperty("hazelcast.hd.global.index.enabled", true);
```

**Comment by Danny-Hazelcast** [comment]
https://github.com/hazelcast/hazelcast/pull/17338
