### ISSUE TITLE
Getting error during startup with 4.x

### ISSUE THREAD

**Issue by SledgeHammer01** [hazelcast/hazelcast#17231]
Hi,

I was using Hazelcast 3.12.8 + Eureka-one and it worked fine. I tried upgrading to all 3 4.x version 4.0, 4.0.1, 4.0.2 and during startup, I get exceptions:

Pom:

```
		<dependency>
			<groupId>javax.cache</groupId>
			<artifactId>cache-api</artifactId>
			<version>1.1.1</version><!--$NO-MVN-MAN-VER$-->
		</dependency>
		<dependency>
			<groupId>com.hazelcast</groupId>
			<artifactId>hazelcast-eureka-one</artifactId>
			<version>2.0.1</version>
		</dependency>
		<dependency>
			<groupId>com.hazelcast</groupId>
			<artifactId>hazelcast</artifactId>
			<version>4.0</version> <!--$NO-MVN-MAN-VER$-->
		</dependency>

```

```
Caused by: java.lang.ClassCastException: class com.hazelcast.instance.impl.HazelcastInstanceProxy cannot be cast to class com.hazelcast.client.impl.clientside.HazelcastClientInstanceImpl (com.hazelcast.instance.impl.HazelcastInstanceProxy and com.hazelcast.client.impl.clientside.HazelcastClientInstanceImpl are in unnamed module of loader 'app')
	at com.hazelcast.client.cache.impl.HazelcastClientCacheManager.<init>(HazelcastClientCacheManager.java:69) ~[hazelcast-4.0.jar:4.0]
	at com.hazelcast.client.cache.impl.HazelcastClientCachingProvider.createCacheManager(HazelcastClientCachingProvider.java:67) ~[hazelcast-4.0.jar:4.0]
	at com.hazelcast.cache.impl.AbstractHazelcastCachingProvider.createHazelcastCacheManager(AbstractHazelcastCachingProvider.java:254) ~[hazelcast-4.0.jar:4.0]
	at com.hazelcast.cache.impl.AbstractHazelcastCachingProvider.getCacheManager(AbstractHazelcastCachingProvider.java:131) ~[hazelcast-4.0.jar:4.0]
	... 43 common frames omitted

```

Any suggestions?

**Comment by leszko** [comment]
@SledgeHammer01 can you try if the following code sample works for you?
https://github.com/hazelcast/hazelcast-code-samples/tree/master/hazelcast-integration/eureka/springboot-embedded
