### ISSUE TITLE
Reliable topic publish expectation fails when members restarted

### ISSUE THREAD

**Issue by lazerion** [hazelcast/hazelcast#17264]
- Failing case [clientShouldOperateWithListener](https://github.com/hazelcast/hazelcast-qe/blob/master/it/client-tests/runner/src/test/java/com/hazelcast/it/client/tests/runner/IpHostnameMixTest.java#L192)
- Deployment
```
Contains 4 members [A,B,C,D]
Member-A configured with an IP address
Member-B configured with a hostname
Member-C configured with an IP address
Member-D configured with a hostname
Client-A configured with Member-A and Member-B initially.
```
- Steps
```
Member-A and Member-B are up and running
Client-A adds a topic listener, Client-B updates the topic continuously
Restart Member-A multiple times, verify client receives publish events
Restart Member-B multiple times, verify client receives publish events
Join Member-C, verify client receives publish events
Join Member-D, verify client receives publish events
Shutdown Member-C, verify client receives publish events
Shutdown Member-D, verify client receives publish events
```
- **Sporadically** Fails on step
```
Join Member-C, verify client receives publish events
```
- Logs 
[logs.zip](https://github.com/hazelcast/hazelcast/files/4967192/logs.zip)

- Failing job in QE IT suite [Build #126 (Jul 21, 2020 5:00:00 AM)](http://jenkins.hazelcast.com/view/Integration%20Tests/job/client-tests/126/)

- You can find [readme doc](https://github.com/hazelcast/hazelcast-qe/tree/master/it/client-tests) regarding how to run this test in your local dev. env.

- Publisher test code or flow can be found [here](https://github.com/hazelcast/hazelcast-qe/blob/master/it/client-tests/client/src/main/java/com/hazelcast/it/client/tests/container/ReliableTopicPublisherTask.java#L42)

- kindly check and/or guide.

**Comment by sancar** [comment]
@lazerion I have investigated the failure. 
`publish` operation fails when member-A restarted. Related log from `clientshouldoperatewithlistener_hazelcast-client-B_1.log`

```
2020-07-23T08:13:18.158995359Z 08:13:18:158 [pool-1-thread-1] ERROR ReliableTopicPublisherTask - Exception in ClientConnection{alive=true, connectionId=5, channel=NioChannel{/172.20.1.2:33089->/172.20.1.4:5701}, remoteAddress=[172.20.1.4]:5701, lastReadTime=2020-07-23 08:13:18.080, lastWriteTime=2020-07-23 08:13:18.078, closedTime=never, connected server version=4.1-clienttests}, thread=hz.hz.client_1.IO.thread-in-0
2020-07-23T08:13:18.159509678Z com.hazelcast.spi.exception.TargetDisconnectedException: Exception in ClientConnection{alive=true, connectionId=5, channel=NioChannel{/172.20.1.2:33089->/172.20.1.4:5701}, remoteAddress=[172.20.1.4]:5701, lastReadTime=2020-07-23 08:13:18.080, lastWriteTime=2020-07-23 08:13:18.078, closedTime=never, connected server version=4.1-clienttests}, thread=hz.hz.client_1.IO.thread-in-0
2020-07-23T08:13:18.159890695Z 	at com.hazelcast.client.impl.spi.impl.ClientInvocationServiceImpl$CleanResourcesTask.notifyException(ClientInvocationServiceImpl.java:309)
2020-07-23T08:13:18.160175600Z 	at com.hazelcast.client.impl.spi.impl.ClientInvocationServiceImpl$CleanResourcesTask.run(ClientInvocationServiceImpl.java:300)
2020-07-23T08:13:18.160198019Z 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
2020-07-23T08:13:18.160398600Z 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
2020-07-23T08:13:18.160715617Z 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
2020-07-23T08:13:18.161032963Z 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
2020-07-23T08:13:18.161285746Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2020-07-23T08:13:18.161534336Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2020-07-23T08:13:18.161863710Z 	at java.lang.Thread.run(Thread.java:748)
2020-07-23T08:13:18.162108014Z 	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
2020-07-23T08:13:18.162309659Z 	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
2020-07-23T08:13:18.162777096Z Caused by: java.io.IOException: Connection reset by peer
2020-07-23T08:13:18.163135431Z 	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
2020-07-23T08:13:18.163478692Z 	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
2020-07-23T08:13:18.163932214Z 	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
2020-07-23T08:13:18.164197131Z 	at sun.nio.ch.IOUtil.read(IOUtil.java:197)
2020-07-23T08:13:18.164518921Z 	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
2020-07-23T08:13:18.164734245Z 	at com.hazelcast.internal.networking.nio.NioInboundPipeline.process(NioInboundPipeline.java:119)
2020-07-23T08:13:18.165015718Z 	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKey(NioThread.java:383)
2020-07-23T08:13:18.165294672Z 	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKeys(NioThread.java:368)
2020-07-23T08:13:18.165571509Z 	at com.hazelcast.internal.networking.nio.NioThread.selectLoop(NioThread.java:294)
2020-07-23T08:13:18.165813464Z 	at com.hazelcast.internal.networking.nio.NioThread.executeRun(NioThread.java:249)
2020-07-23T08:13:18.166159214Z 	... 1 more
```

It is expected to see a non-idempotent operation to fail while disconnections are happening. They are not necessarily retried. If the connection fails before invocation put into write queue, they will be retried -otherwise. they fail with TargetDisconnectedException`. So it is matter of chance and we can not rely on tests. Rather than exact count, we may verify that there is progress after member restart.

**Comment by lazerion** [comment]
@sancar I opened that issue since it was not the case before and there is still at least one member active in cluster for that client. IIUC, in that case we lost a publish event. Can you confirm, since it is not retried? 

do we need to handle that exception and retry, as another mitigation? 

I did not know that it is the case for reliable topic. I will update the case. 

I could not catch in documentation, do we need to add it?

**Comment by sancar** [comment]
We have documentation for this behavior here. 
https://docs.hazelcast.org/docs/4.0.2/manual/html-single/index.html#handling-failures
It mentions this as all non-idempotent(e.g not read-only ) operations. 

Note that If you catch the exception and retry, it could be the case that you do the operation twice
So you will be switching from at most one event per `publish` to at least one event per `publish`.  That might be more suitable to verify.

**Comment by lazerion** [comment]
Thanks @sancar closing per above discussion and changing case to verify continuation of `publish`.
