### ISSUE TITLE
ClientConsoleApp in ClientConsoleTest is not shutdown sometimes

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#17296]
Test `com.hazelcast.client.console.ClientConsoleTest.connectsToHazelcastCluster()` uses `ClientConsoleApp` which is sometimes not shutdown and stay alive even after test is finished. It blocks finishing surefire tests (it is terminated by surefire after 30 seconds when all tests are finished) which for example causes that jacoco plugin is not executed correctly and test coverage is not reported.

Related thread dump:
```
"pool-7123-thread-1" #160189 prio=5 os_prio=0 tid=0x00007f177c16a000 nid=0x1603 runnable [0x00007f17638f9000]
   java.lang.Thread.State: RUNNABLE
	at java.io.FileInputStream.readBytes(Native Method)
	at java.io.FileInputStream.read(FileInputStream.java:255)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	- locked <0x000000008006e260> (a java.io.BufferedInputStream)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	- locked <0x0000000082ae1530> (a java.io.InputStreamReader)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.io.BufferedReader.readLine(BufferedReader.java:324)
	- locked <0x0000000082ae1530> (a java.io.InputStreamReader)
	at java.io.BufferedReader.readLine(BufferedReader.java:389)
	at com.hazelcast.client.console.ClientConsoleApp$DefaultLineReader.readLine(ClientConsoleApp.java:185)
	at com.hazelcast.client.console.ClientConsoleApp.start(ClientConsoleApp.java:169)
	at com.hazelcast.client.console.ClientConsoleApp.main(ClientConsoleApp.java:1551)
	at com.hazelcast.client.console.ClientConsoleTest.lambda$connectsToHazelcastCluster$0(ClientConsoleTest.java:91)
	at com.hazelcast.client.console.ClientConsoleTest$$Lambda$3794/200997726.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

It can be reproduced by adding `Thread.sleep(60_000);` after `assertNotNull(client);` in given test. You can also add `<forkedProcessExitTimeoutInSeconds>900</forkedProcessExitTimeoutInSeconds>` to `configuration` of surefire plugin to wait 15 minutes instead of default 30 seconds after all tests are finished. If you dump threads during this period (after tests are finished) you'll see mentioned above thread.

**Comment by olukas** [comment]
Reopening. It seems there is some intermittent issue after the first fix. Thread dump:
```
"pool-17877-thread-1" #845273 prio=5 os_prio=0 tid=0x00007f76002d3800 nid=0xc8a83 waiting on condition [0x00007f72105c4000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000090d46008> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at com.hazelcast.client.console.ClientConsoleTest$BQInputStream.read(ClientConsoleTest.java:119)
	at java.io.InputStream.read(InputStream.java:179)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	- locked <0x0000000090d460a0> (a java.io.InputStreamReader)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.io.BufferedReader.readLine(BufferedReader.java:324)
	- locked <0x0000000090d460a0> (a java.io.InputStreamReader)
	at java.io.BufferedReader.readLine(BufferedReader.java:389)
	at com.hazelcast.client.console.ClientConsoleApp$DefaultLineReader.readLine(ClientConsoleApp.java:186)
	at com.hazelcast.client.console.ClientConsoleApp.start(ClientConsoleApp.java:169)
	at com.hazelcast.client.console.ClientConsoleApp.main(ClientConsoleApp.java:1552)
	at com.hazelcast.client.console.ClientConsoleTest.lambda$connectsToHazelcastCluster$0(ClientConsoleTest.java:99)
	at com.hazelcast.client.console.ClientConsoleTest$$Lambda$11120/1449498091.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
