### ISSUE TITLE
Improve error message for unsupported LIMIT clause

### ISSUE THREAD

**Issue by Holmistr** [hazelcast/hazelcast#17294]
Currently, the LIMIT clause in SQL query is not supported. The error message is pretty ugly:
```
Exception in thread "main" java.lang.RuntimeException: com.hazelcast.sql.SqlException: class com.hazelcast.org.apache.calcite.sql.SqlNumericLiteral: 1
	at Main.<init>(Main.java:31)
	at Main.main(Main.java:54)
Caused by: com.hazelcast.sql.SqlException: class com.hazelcast.org.apache.calcite.sql.SqlNumericLiteral: 1
	at com.hazelcast.sql.impl.QueryUtils.toPublicException(QueryUtils.java:67)
	at com.hazelcast.sql.impl.SqlServiceImpl.query(SqlServiceImpl.java:153)
	at com.hazelcast.sql.SqlService.query(SqlService.java:136)
	at Main.run(Main.java:39)
	at Main.<init>(Main.java:29)
	... 1 more
Caused by: java.lang.UnsupportedOperationException: class com.hazelcast.org.apache.calcite.sql.SqlNumericLiteral: 1
	at com.hazelcast.org.apache.calcite.util.Util.needToImplement(Util.java:967)
	at com.hazelcast.org.apache.calcite.sql.validate.SqlValidatorImpl.getValidatedNodeType(SqlValidatorImpl.java:1701)
	at com.hazelcast.sql.impl.calcite.HazelcastSqlToRelConverter.convertLiteral(HazelcastSqlToRelConverter.java:137)
	at com.hazelcast.sql.impl.calcite.HazelcastSqlToRelConverter.convertExtendedExpression(HazelcastSqlToRelConverter.java:69)
	at com.hazelcast.org.apache.calcite.sql2rel.SqlToRelConverter$Blackboard.convertExpression(SqlToRelConverter.java:4733)
	at com.hazelcast.org.apache.calcite.sql2rel.SqlToRelConverter.convertExpression(SqlToRelConverter.java:1887)
	at com.hazelcast.org.apache.calcite.sql2rel.SqlToRelConverter.convertOrder(SqlToRelConverter.java:846)
	at com.hazelcast.org.apache.calcite.sql2rel.SqlToRelConverter.convertSelectImpl(SqlToRelConverter.java:693)
	at com.hazelcast.org.apache.calcite.sql2rel.SqlToRelConverter.convertSelect(SqlToRelConverter.java:640)
	at com.hazelcast.org.apache.calcite.sql2rel.SqlToRelConverter.convertQueryRecursive(SqlToRelConverter.java:3384)
	at com.hazelcast.org.apache.calcite.sql2rel.SqlToRelConverter.convertQuery(SqlToRelConverter.java:566)
	at com.hazelcast.sql.impl.calcite.parse.QueryConverter.convert(QueryConverter.java:76)
	at com.hazelcast.sql.impl.calcite.OptimizerContext.convert(OptimizerContext.java:154)
	at com.hazelcast.sql.impl.calcite.CalciteSqlOptimizer.prepare(CalciteSqlOptimizer.java:142)
	at com.hazelcast.sql.impl.SqlServiceImpl.prepare(SqlServiceImpl.java:200)
	at com.hazelcast.sql.impl.SqlServiceImpl.query0(SqlServiceImpl.java:179)
	at com.hazelcast.sql.impl.SqlServiceImpl.query(SqlServiceImpl.java:151)
	... 4 more
```

**Comment by Holmistr** [comment]
Fix: https://github.com/hazelcast/hazelcast/pull/17295
