### ISSUE TITLE
IndexOutOfBoundsException on member nodes if clients reconnect using iLists

### ISSUE THREAD

**Issue by mirwais-sys** [hazelcast/hazelcast#17307]
If hazelcast clients as kubernetes pods reconnects (e.g. due to a redeployment). We see the following IndexOutOfBoundsExceptions on the hazelcast members:

```
java.lang.IndexOutOfBoundsException: Index 1627 out of bounds for length 1627
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:458)
	at com.hazelcast.collection.impl.list.ListContainer.get(ListContainer.java:92)
	at com.hazelcast.collection.impl.list.operations.ListGetOperation.run(ListGetOperation.java:44)
	at com.hazelcast.spi.Operation.call(Operation.java:170)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:210)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:199)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:407)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:434)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:648)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:633)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:592)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:256)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:61)
	at com.hazelcast.client.impl.protocol.task.AbstractPartitionMessageTask.processMessage(AbstractPartitionMessageTask.java:67)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:129)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:109)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:163)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:159)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:127)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:110)

```

Any idea how it comes? We use version: **[3.12.4]** with open-jdk 11.0.1 with 2 nodes as member. We have around 55 clients connected to the members. All running on k8s.

**Comment by mmedenjak** [comment]
@mirwais-sys is it the case that the client was running but simply disconnected and reconnected? If so, it's possible the list changed in the meantime and doesn't contain enough elements.

**Comment by mirwais-sys** [comment]
Yes, the client instance(s) was disconnected and reconnects after a deployment. But the HZ members were all time online and the exception above comes happens on the members, not on the clients.

**Comment by mmedenjak** [comment]
In that case, I believe it's possible the client asked for item number 1627 and got disconnected. The request was being retried on the client but in the meantime, the list shrunk on the members. Once the client gets reconnected, the request is executed but there is no more item number 1627.

**Comment by mmedenjak** [comment]
Closing due to inactivity. Please reopen or comment if you have further information. Happy Hazelcasting!
