### ISSUE TITLE
JCache providers only accept XML as declarative config

### ISSUE THREAD

**Issue by vbekiaris** [hazelcast/hazelcast#17319]
**Describe the bug**
JCache initialization with explicit configuration file fails with YAML config file.

**Expected behavior**
Since YAML config is now supported, it is expected that users can initialize JCache providers with both supported declarative config formats (XML & YAML).

**To Reproduce**
```
CachingProvider cachingProvider = Caching.getCachingProvider(HazelcastCachingProvider.SERVER_CACHING_PROVIDER);
CacheManager cacheManager = cachingProvider.getCacheManager(null, null, propertiesByLocation("classpath:hazelcast.yaml"));
```
fails with:
```
...
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
	at com.hazelcast.config.XmlConfigBuilder.parse(XmlConfigBuilder.java:197)
```

**Comment by vbekiaris** [comment]
closing as duplicate of #21741
