### ISSUE TITLE
Some threads are not finished correctly in testsuite

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#17324]
Some threads are still alive after testsuite is finished. Some of them can block generating test coverage by jacoco (it is run as hook in JVM shutdown which can be blocked by some of those threads - they're killed forcefully by surefire after 30seconds from testsuite is finished).

This is summarized list of hazelcast-related alive threads. Duplicated stacktraces were removed in this list, please see attachment (
[imdg_ts_thread_dump.txt](https://github.com/hazelcast/hazelcast/files/5049828/imdg_ts_thread_dump.txt)
) for complete thread dump with all threads for each of those runs:
```
"hz.brave_easley.cached.thread-8" Id=1467866 WAITING on java.util.concurrent.Semaphore$NonfairSync@394297df
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.Semaphore$NonfairSync@394297df
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
	at java.util.concurrent.Semaphore.acquire(Semaphore.java:467)
	at com.hazelcast.internal.partition.impl.PartitionReplicaManager$AntiEntropyTask.waitAntiEntropyTaskEnd(PartitionReplicaManager.java:587)
	at com.hazelcast.internal.partition.impl.PartitionReplicaManager$AntiEntropyTask.run(PartitionReplicaManager.java:557)
	...

"hz.heuristic_goldberg.cached.thread-11" Id=1333686 WAITING on java.util.concurrent.CompletableFuture$Signaller@f4ae4e
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.CompletableFuture$Signaller@f4ae4e
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1707)
	at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3323)
	at java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1742)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908)
	at com.hazelcast.cp.internal.datastructures.spi.blocking.AbstractBlockingService.tryReplicateExpiredWaitKeys(AbstractBlockingService.java:334)
	at com.hazelcast.cp.internal.datastructures.spi.blocking.AbstractBlockingService.access$100(AbstractBlockingService.java:71)
	...

"Thread-54391" Id=1142582 WAITING
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:304)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:599)
	at com.hazelcast.spi.impl.AbstractInvocationFuture_IsDoneTest$1.call(AbstractInvocationFuture_IsDoneTest.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)

"hz.optimistic_goldwasser.cached.thread-1" Id=1109127 TIMED_WAITING
	at java.lang.Thread.sleep(Native Method)
	at java.lang.Thread.sleep(Thread.java:340)
	at java.util.concurrent.TimeUnit.sleep(TimeUnit.java:386)
	at com.hazelcast.test.HazelcastTestSupport.sleepAtLeastMillis(HazelcastTestSupport.java:425)
	at com.hazelcast.test.HazelcastTestSupport.sleepAtLeastSeconds(HazelcastTestSupport.java:440)
	at com.hazelcast.executor.ExecutorServiceCancelTest$SleepingTask.call(ExecutorServiceCancelTest.java:169)
	at com.hazelcast.executor.ExecutorServiceCancelTest$SleepingTask.call(ExecutorServiceCancelTest.java:150)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	...

"hz.kind_banzai.cached.thread-3" Id=1104145 TIMED_WAITING
	at java.lang.Thread.sleep(Native Method)
	at java.lang.Thread.sleep(Thread.java:340)
	at java.util.concurrent.TimeUnit.sleep(TimeUnit.java:386)
	at com.hazelcast.test.HazelcastTestSupport.sleepAtLeastMillis(HazelcastTestSupport.java:425)
	at com.hazelcast.test.HazelcastTestSupport.sleepAtLeastSeconds(HazelcastTestSupport.java:440)
	at com.hazelcast.executor.ExecutorServiceTestSupport$SleepingTask.call(ExecutorServiceTestSupport.java:212)
	at com.hazelcast.executor.ExecutorServiceTestSupport$SleepingTask.call(ExecutorServiceTestSupport.java:202)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	...

"hz.frosty_fermat.cached.thread-16" Id=907122 WAITING on java.util.concurrent.Semaphore$NonfairSync@3b5cec71
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.Semaphore$NonfairSync@3b5cec71
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
	at java.util.concurrent.Semaphore.acquire(Semaphore.java:312)
	at com.hazelcast.map.impl.mapstore.writebehind.TemporaryBlockerEntryStore.store(TemporaryBlockerEntryStore.java:32)
	at com.hazelcast.map.impl.mapstore.writebehind.TemporaryBlockerEntryStore.store(TemporaryBlockerEntryStore.java:24)
	...

"hz.heuristic_fermat.cached.thread-5" Id=907078 WAITING on java.util.concurrent.Semaphore$NonfairSync@126e12e0
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.Semaphore$NonfairSync@126e12e0
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
	at java.util.concurrent.Semaphore.acquire(Semaphore.java:312)
	at com.hazelcast.map.impl.mapstore.writebehind.TemporaryBlockerEntryStore.storeAll(TemporaryBlockerEntryStore.java:42)
	at com.hazelcast.map.impl.MapStoreWrapper.storeAll(MapStoreWrapper.java:134)
	...

"pool-17435-thread-1" Id=844021 WAITING on java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync@7e4284db owned by "testInvocation_whenHeartbeatStopped" Id=843166
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync@7e4284db
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireShared(AbstractQueuedSynchronizer.java:967)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireShared(AbstractQueuedSynchronizer.java:1283)
	at java.util.concurrent.locks.ReentrantReadWriteLock$ReadLock.lock(ReentrantReadWriteLock.java:727)
	at com.hazelcast.client.test.TwoWayBlockableExecutor$BlockableRunnable.run(TwoWayBlockableExecutor.java:95)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	...

"hz.friendly_fermi.cached.thread-5" Id=693673 TIMED_WAITING
	at java.lang.Thread.sleep(Native Method)
	at com.hazelcast.client.test.executor.tasks.CancellationAwareTask.call(CancellationAwareTask.java:46)
	at com.hazelcast.client.test.executor.tasks.CancellationAwareTask.call(CancellationAwareTask.java:30)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.hazelcast.executor.impl.DistributedExecutorService$Processor.run(DistributedExecutorService.java:307)
	at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	...

"hz.hz.client_3728.IO.thread-out-0" Id=629659 RUNNABLE (in native)
	at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
	at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
	at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	-  locked com.hazelcast.internal.networking.nio.SelectorOptimizer$SelectionKeysSet@3b94be6d
	-  locked java.util.Collections$UnmodifiableSet@7e1863
	-  locked sun.nio.ch.EPollSelectorImpl@1da664cf
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at com.hazelcast.internal.networking.nio.NioThread.selectLoop(NioThread.java:292)
	at com.hazelcast.internal.networking.nio.NioThread.executeRun(NioThread.java:249)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)

"-12282" Id=131581 WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@38b365e7
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@38b365e7
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at com.hazelcast.internal.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:227)

"JitterThread" Id=131327 TIMED_WAITING
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:338)
	at com.hazelcast.test.jitter.JitterThread.sleepNanos(JitterThread.java:56)
	at com.hazelcast.test.jitter.JitterThread.run(JitterThread.java:41)
```
All logs from testsuite run can be found here - https://console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-4.master-sonar/586/

**Comment by mmedenjak** [comment]
Any updates on this issue @olukas @jerrinot ? I'd move this out of 4.1 milestone since I don't see this as critical.

**Comment by olukas** [comment]
@mmedenjak Feel free to move it out from 4.1 milestone. It was stable for while hence I turned off my patch for surefire which dumps threads when it gets stuck. It failed once from that time. I can turn the patch back on if you want. See https://sonarcloud.io/project/activity?from=2020-07-09T14%3A46%3A02%2B0000&graph=coverage&id=hz-os-master&selected_date=2020-09-02T02%3A51%3A22%2B0000.

**Comment by mmedenjak** [comment]
Sure, turn it back on and keep it like that if you want until it fails. Moving out of 4.1.

**Comment by olukas** [comment]
Issue occurred again in http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-4.master-sonar/612/. Thread dump with all living threads after tests is here - 
[thread_dump.txt](https://github.com/hazelcast/hazelcast/files/5182093/thread_dump.txt)

**Comment by mmedenjak** [comment]
To begin with, I think it's worth correlating the instance names from some threads to the tests. For instance, these:
```
"hz.ecstatic_leavitt.cached.thread-10" Id=605751 TIMED_WAITING
	at java.lang.Thread.sleep(Native Method)
	at com.hazelcast.client.test.executor.tasks.CancellationAwareTask.call(CancellationAwareTask.java:46)
	at com.hazelcast.client.test.executor.tasks.CancellationAwareTask.call(CancellationAwareTask.java:30)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.hazelcast.executor.impl.DistributedExecutorService$Processor.run(DistributedExecutorService.java:276)
	at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	...

	Number of locked synchronizers = 1
	- java.util.concurrent.ThreadPoolExecutor$Worker@340202b
```

We can try looking for `ecstatic_leavitt` in the test logs. Similar for other threads.

**Comment by frant-hartm** [comment]
Since this change in the sonar build

http://jenkins.hazelcast.com/job/Hazelcast-master-sonar/jobConfigHistory/showDiffFiles?timestamp1=2021-06-10_15-26-03&timestamp2=2021-06-29_14-16-04

where we turned on `test-coverage` profile, we seem to be getting code coverage report correctly (apart from some flaky failure, likely caused by incorrect config on a older branch build). We have taken multiple measures to address leaking threads (check for hanging instances, clients, ..).

The issue seems fixed.
