### ISSUE TITLE
sql HD idx IndexOutOfBoundsException: Source offset: 4, length: 0, size: 0 SEVERE logging

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#17330]
i found this is the logs of some experiment test's i am running on the lab,   stable cluster 
only this is logged it looks like the sql queries are returning the correct results 

```
[danny@server16 ~]$ jpsdir
19662: /home/danny/workspace/trials/trial-1
29311: No such process
[danny@server16 ~]$ cd /home/danny/workspace/trials/trial-1
```

```
SEVERE: [10.212.40.101]:5701 [HZ] [4.1-SNAPSHOT] Source offset: 4, length: 0, size: 0
java.lang.IndexOutOfBoundsException: Source offset: 4, length: 0, size: 0
	at com.hazelcast.internal.memory.MemoryBlock.copyTo(MemoryBlock.java:201)
	at com.hazelcast.internal.serialization.impl.NativeMemoryData.toByteArray(NativeMemoryData.java:77)
	at com.hazelcast.internal.serialization.impl.EnterpriseSerializationServiceV1.convertDataInternal(EnterpriseSerializationServiceV1.java:164)
	at com.hazelcast.internal.serialization.impl.EnterpriseSerializationServiceV1.convertData(EnterpriseSerializationServiceV1.java:131)
	at com.hazelcast.internal.serialization.impl.EnterpriseSerializationServiceV1.toDataInternal(EnterpriseSerializationServiceV1.java:82)
	at com.hazelcast.internal.serialization.impl.EnterpriseSerializationServiceV1.toData(EnterpriseSerializationServiceV1.java:64)
	at com.hazelcast.internal.bplustree.DefaultBPlusTreeKeyAccessor.convertToHeapData(DefaultBPlusTreeKeyAccessor.java:50)
	at com.hazelcast.internal.bplustree.HDBTreeNodeBaseAccessor.getIndexKeyHeapData(HDBTreeNodeBaseAccessor.java:141)
	at com.hazelcast.internal.bplustree.HDBPlusTree$EntryIterator.setNextEntry(HDBPlusTree.java:1193)
	at com.hazelcast.internal.bplustree.HDBPlusTree$EntryIterator.nextSlotIsWithinRange(HDBPlusTree.java:1180)
	at com.hazelcast.internal.bplustree.HDBPlusTree$EntryIterator.nextBatch0(HDBPlusTree.java:1157)
	at com.hazelcast.internal.bplustree.HDBPlusTree$BatchingEntryIterator.nextBatch(HDBPlusTree.java:1236)
	at com.hazelcast.internal.bplustree.HDBPlusTree$BatchingEntryIterator.hasNext(HDBPlusTree.java:1227)
	at com.hazelcast.query.impl.HDOrderedConcurrentIndexStore.buildResultSet(HDOrderedConcurrentIndexStore.java:207)
	at com.hazelcast.query.impl.HDOrderedConcurrentIndexStore.getRecords(HDOrderedConcurrentIndexStore.java:144)
	at com.hazelcast.query.impl.AbstractIndex.getRecords(AbstractIndex.java:222)
	at com.hazelcast.query.impl.GlobalQueryContextWithStats$QueryTrackingIndex.getRecords(GlobalQueryContextWithStats.java:162)
	at com.hazelcast.query.impl.predicates.BoundedRangePredicate.filter(BoundedRangePredicate.java:73)
	at com.hazelcast.query.impl.Indexes.query(Indexes.java:342)
	at com.hazelcast.map.impl.query.QueryRunner.runUsingGlobalIndexSafely(QueryRunner.java:263)
	at com.hazelcast.map.impl.query.QueryRunner.runIndexOrPartitionScanQueryOnOwnedPartitions(QueryRunner.java:134)
	at com.hazelcast.map.impl.query.QueryOperation.callInternal(QueryOperation.java:97)
	at com.hazelcast.map.impl.query.QueryOperation.call(QueryOperation.java:78)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:227)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:216)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:422)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:166)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:136)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
```

**Comment by Danny-Hazelcast** [comment]
[danny@server16 workspace]$ ls /nfs/danny/issue-17330/
HzCmd.properties  a.box   config-hz             executor-reg  listeners  map-lock   near-cache-get  output   pred-agg    queue  ring   ttl-put
HzCmd.ser         atomic  execute-on-predicate  hz-trial1     map-cas    mixed-sql  nohup.out       pid.txt  projection  rest   topic  update-listener

[danny@server16 workspace]$ cat  /nfs/danny/issue-17330/output/HZ/HzMember1HZ/out.txt

**Comment by Danny-Hazelcast** [comment]
ls /nfs/danny/issue-17330-2nd/

```
ls /nfs/danny/issue-17330-2nd/
HzCmd.properties  HzCmd.ser  a.box  config-hz  hz-trial1  mixed-sql  nohup.out  output  pid.txt  pred-agg  projection
```

**Comment by Danny-Hazelcast** [comment]
looks like fixed with https://github.com/hazelcast/hazelcast-enterprise/pull/3694
