### ISSUE TITLE
AssertionError: null  BitmapIndexStore.update(BitmapIndexStore.java:215)

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#17342]
http://jenkins.hazelcast.com/view/freeze/job/freeze-x/83/console  is running all tests in "hz/stable/sql"

fail HzClient3HZ put-mapBak1Bin hzcmd.map.PutRandomStylePerson threadId=0 java.lang.AssertionError: null

http://54.147.27.51/~jenkins/workspace/freeze-x/4.1-SNAPSHOT/2020_08_13-07_53_37/sql/bit-map/output/HZ/HzClient3HZ/exception.txt

```
java.lang.AssertionError: null
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at com.hazelcast.internal.util.ExceptionUtil.tryWrapInSameClass(ExceptionUtil.java:233)
	at com.hazelcast.internal.util.ExceptionUtil.wrapError(ExceptionUtil.java:184)
	at com.hazelcast.internal.util.ExceptionUtil.rethrowIfError(ExceptionUtil.java:179)
	at com.hazelcast.internal.util.ExceptionUtil.rethrow(ExceptionUtil.java:147)
	at com.hazelcast.map.impl.recordstore.CompositeMutationObserver.onUpdateRecord(CompositeMutationObserver.java:98)
	at com.hazelcast.map.impl.recordstore.AbstractRecordStore.updateRecord(AbstractRecordStore.java:208)
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.putInternal(DefaultRecordStore.java:773)
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.put(DefaultRecordStore.java:753)
	at com.hazelcast.map.impl.operation.PutOperation.runInternal(PutOperation.java:36)
	at com.hazelcast.map.impl.operation.MapOperation.run(MapOperation.java:112)
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:184)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:227)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:216)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:411)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:438)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:597)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:582)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:541)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:238)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:59)
	at com.hazelcast.client.impl.protocol.task.AbstractPartitionMessageTask.processInternal(AbstractPartitionMessageTask.java:51)
	at com.hazelcast.client.impl.protocol.task.AbstractAsyncMessageTask.processMessage(AbstractAsyncMessageTask.java:71)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:153)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:116)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:180)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:172)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:140)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
```

**Comment by Danny-Hazelcast** [comment]
java.lang.NullPointerException
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at com.hazelcast.internal.util.ExceptionUtil.tryWrapInSameClass(ExceptionUtil.java:243)
	at com.hazelcast.internal.util.ExceptionUtil.wrapException(ExceptionUtil.java:138)
	at com.hazelcast.internal.util.ExceptionUtil.peel(ExceptionUtil.java:114)
	at com.hazelcast.internal.util.ExceptionUtil.peel(ExceptionUtil.java:120)
	at com.hazelcast.internal.util.ExceptionUtil.peel(ExceptionUtil.java:73)
	at com.hazelcast.internal.util.ExceptionUtil.rethrow(ExceptionUtil.java:148)
	at com.hazelcast.map.impl.proxy.MapProxySupport.invokeOperation(MapProxySupport.java:484)
	at com.hazelcast.map.impl.proxy.MapProxySupport.putInternal(MapProxySupport.java:411)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.put(MapProxyImpl.java:130)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.put(MapProxyImpl.java:120)

**Comment by Danny-Hazelcast** [comment]
http://jenkins.hazelcast.com/view/freeze/job/split-x2/10/console

**Comment by Danny-Hazelcast** [comment]
http://jenkins.hazelcast.com/view/split/job/split-x2/10/console

**Comment by Danny-Hazelcast** [comment]
```
/disk1/jenkins/workspace/split-x2/4.1-SNAPSHOT/2020_08_13-07_55_56/sql/bit-map
(base) [jenkins@ip-10-72-134-107 bit-map]$ cat output/HZ/HzMember1HZAA/exception.txt
java.lang.NullPointerException
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at com.hazelcast.internal.util.ExceptionUtil.tryWrapInSameClass(ExceptionUtil.java:243)
	at com.hazelcast.internal.util.ExceptionUtil.wrapException(ExceptionUtil.java:138)
	at com.hazelcast.internal.util.ExceptionUtil.peel(ExceptionUtil.java:114)
	at com.hazelcast.internal.util.ExceptionUtil.peel(ExceptionUtil.java:120)
	at com.hazelcast.internal.util.ExceptionUtil.peel(ExceptionUtil.java:73)
	at com.hazelcast.internal.util.ExceptionUtil.rethrow(ExceptionUtil.java:148)
	at com.hazelcast.map.impl.proxy.MapProxySupport.invokeOperation(MapProxySupport.java:484)
	at com.hazelcast.map.impl.proxy.MapProxySupport.putInternal(MapProxySupport.java:411)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.put(MapProxyImpl.java:130)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.put(MapProxyImpl.java:120)
	at hzcmd.map.PutRandomStylePerson.timeStep(PutRandomStylePerson.java:12)
	at remote.bench.marker.RollMarker.flatOut(RollMarker.java:72)
	at remote.bench.marker.RollMarker.bench(RollMarker.java:59)
	at remote.bench.BenchThread.call(BenchThread.java:41)
	at remote.bench.BenchThread.call(BenchThread.java:14)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at com.hazelcast.internal.util.ExceptionUtil.tryWrapInSameClass(ExceptionUtil.java:243)
	at com.hazelcast.internal.util.ExceptionUtil.wrapException(ExceptionUtil.java:138)
	at com.hazelcast.internal.util.ExceptionUtil.peel(ExceptionUtil.java:114)
	at com.hazelcast.internal.util.ExceptionUtil.peel(ExceptionUtil.java:73)
	at com.hazelcast.internal.util.ExceptionUtil.rethrow(ExceptionUtil.java:148)
	at com.hazelcast.map.impl.recordstore.CompositeMutationObserver.onUpdateRecord(CompositeMutationObserver.java:98)
	at com.hazelcast.map.impl.recordstore.AbstractRecordStore.updateRecord(AbstractRecordStore.java:208)
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.putInternal(DefaultRecordStore.java:773)
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.put(DefaultRecordStore.java:753)
	at com.hazelcast.map.impl.operation.PutOperation.runInternal(PutOperation.java:36)
	at com.hazelcast.map.impl.operation.MapOperation.run(MapOperation.java:112)
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:184)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:227)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:216)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:160)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:138)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
Caused by: java.lang.NullPointerException
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at com.hazelcast.internal.util.ExceptionUtil.tryWrapInSameClass(ExceptionUtil.java:243)
	at com.hazelcast.internal.util.ExceptionUtil.wrapException(ExceptionUtil.java:138)
	at com.hazelcast.internal.util.ExceptionUtil.peel(ExceptionUtil.java:114)
	at com.hazelcast.internal.util.ExceptionUtil.peel(ExceptionUtil.java:73)
	at com.hazelcast.internal.util.ExceptionUtil.rethrow(ExceptionUtil.java:148)
	at com.hazelcast.query.impl.Indexes.putEntry(Indexes.java:288)
	at com.hazelcast.map.impl.recordstore.IndexingMutationObserver.saveIndex(IndexingMutationObserver.java:169)
	at com.hazelcast.map.impl.recordstore.IndexingMutationObserver.onUpdateRecord(IndexingMutationObserver.java:69)
	at com.hazelcast.map.impl.recordstore.CompositeMutationObserver.onUpdateRecord(CompositeMutationObserver.java:89)
	... 12 more
Caused by: java.lang.NullPointerException
	at com.hazelcast.query.impl.bitmap.SparseBitSet.add(SparseBitSet.java:97)
	at com.hazelcast.query.impl.bitmap.Bitmap.update(Bitmap.java:103)
	at com.hazelcast.query.impl.BitmapIndexStore.update(BitmapIndexStore.java:216)
	at com.hazelcast.query.impl.AbstractIndex.putEntry(AbstractIndex.java:145)
	at com.hazelcast.query.impl.Indexes.putEntry(Indexes.java:279)
	... 15 more
java.lang.NullPointerException
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at com.hazelcast.internal.util.ExceptionUtil.tryWrapInSameClass(ExceptionUtil.java:243)
	at com.hazelcast.internal.util.ExceptionUtil.wrapException(ExceptionUtil.java:138)
	at com.hazelcast.internal.util.ExceptionUtil.peel(ExceptionUtil.java:114)
	at com.hazelcast.internal.util.ExceptionUtil.peel(ExceptionUtil.java:120)
	at com.hazelcast.internal.util.ExceptionUtil.peel(ExceptionUtil.java:73)
	at com.hazelcast.internal.util.ExceptionUtil.rethrow(ExceptionUtil.java:148)
	at com.hazelcast.map.impl.proxy.MapProxySupport.invokeOperation(MapProxySupport.java:484)
	at com.hazelcast.map.impl.proxy.MapProxySupport.putInternal(MapProxySupport.java:411)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.put(MapProxyImpl.java:130)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.put(MapProxyImpl.java:120)
	at hzcmd.map.PutRandomStylePerson.timeStep(PutRandomStylePerson.java:12)
	at remote.bench.marker.RollMarker.flatOut(RollMarker.java:72)
	at remote.bench.marker.RollMarker.bench(RollMarker.java:59)
	at remote.bench.BenchThread.call(BenchThread.java:41)
	at remote.bench.BenchThread.call(BenchThread.java:14)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at com.hazelcast.internal.util.ExceptionUtil.tryWrapInSameClass(ExceptionUtil.java:243)
	at com.hazelcast.internal.util.ExceptionUtil.wrapException(ExceptionUtil.java:138)
	at com.hazelcast.internal.util.ExceptionUtil.peel(ExceptionUtil.java:114)
	at com.hazelcast.internal.util.ExceptionUtil.peel(ExceptionUtil.java:73)
	at com.hazelcast.internal.util.ExceptionUtil.rethrow(ExceptionUtil.java:148)
	at com.hazelcast.map.impl.recordstore.CompositeMutationObserver.onUpdateRecord(CompositeMutationObserver.java:98)
	at com.hazelcast.map.impl.recordstore.AbstractRecordStore.updateRecord(AbstractRecordStore.java:208)
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.putInternal(DefaultRecordStore.java:773)
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.put(DefaultRecordStore.java:753)
	at com.hazelcast.map.impl.operation.PutOperation.runInternal(PutOperation.java:36)
	at com.hazelcast.map.impl.operation.MapOperation.run(MapOperation.java:112)
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:184)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:227)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:216)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:160)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:138)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
Caused by: java.lang.NullPointerException
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at com.hazelcast.internal.util.ExceptionUtil.tryWrapInSameClass(ExceptionUtil.java:243)
	at com.hazelcast.internal.util.ExceptionUtil.wrapException(ExceptionUtil.java:138)
	at com.hazelcast.internal.util.ExceptionUtil.peel(ExceptionUtil.java:114)
	at com.hazelcast.internal.util.ExceptionUtil.peel(ExceptionUtil.java:73)
	at com.hazelcast.internal.util.ExceptionUtil.rethrow(ExceptionUtil.java:148)
	at com.hazelcast.query.impl.Indexes.putEntry(Indexes.java:288)
	at com.hazelcast.map.impl.recordstore.IndexingMutationObserver.saveIndex(IndexingMutationObserver.java:169)
	at com.hazelcast.map.impl.recordstore.IndexingMutationObserver.onUpdateRecord(IndexingMutationObserver.java:69)
	at com.hazelcast.map.impl.recordstore.CompositeMutationObserver.onUpdateRecord(CompositeMutationObserver.java:89)
	... 12 more
Caused by: java.lang.NullPointerException
	at com.hazelcast.query.impl.bitmap.SparseBitSet.add(SparseBitSet.java:97)
	at com.hazelcast.query.impl.bitmap.Bitmap.update(Bitmap.java:103)
	at com.hazelcast.query.impl.BitmapIndexStore.update(BitmapIndexStore.java:216)
	at com.hazelcast.query.impl.AbstractIndex.putEntry(AbstractIndex.java:145)
	at com.hazelcast.query.impl.Indexes.putEntry(Indexes.java:279)
	... 15 more
java.lang.NullPointerException
```

**Comment by petrpleshachkov** [comment]
It seems `rethrow(exception)` doesn't work properly with the `AssertionError`. However, the original `AssertionError` happened in the `BitmapIndexStore`.

CC @taburet

**Comment by Danny-Hazelcast** [comment]
/disk1/jenkins/workspace/split-x2/4.1-SNAPSHOT/2020_08_13-07_55_56/sql/bit-map Failed
 
fail HzMember4HZBB put-mapBak1Bin hzcmd.map.PutRandomStylePerson threadId=0 java.lang.NullPointerException 

 http://54.147.27.51/~jenkins/workspace/split-x2/4.1-SNAPSHOT/2020_08_13-07_55_56/sql/bit-map

**Comment by petrpleshachkov** [comment]
As we discussed with @taburet , recent fixes in the storage/index subsystem make sure that the index doesn't contain more entries than storage. We do this to avoid dangling pointers issue and subsequent JVM crash. 

The bitmap index internally relies on the strong consistency of the storage/index. As pointed out in the PRD https://hazelcast.atlassian.net/wiki/spaces/PM/pages/2452979880/Revise+IMap+storage+and+indices+updates+consistency we don't have that in some cases. 

The solution would be to expect this in the BitMap index and to handle it properly instead of throwing `AsserionError`.
