### ISSUE TITLE
wan Failed to serialize WanEventContainerOperation oome hprof jvm crash hs_pid core 

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#17358]
http://jenkins.hazelcast.com/view/wan/job/wan-sync-oome/55/console

/disk1/jenkins/workspace/wan-sync-oome/4.1-SNAPSHOT/2020_08_15-18_22_02/sync-oome

output/C/HzMember1C/HzMember1C.hprof
output/C/HzMember1C/HzMember1C.oome

http://54.147.27.51/~jenkins/workspace/wan-sync-oome/4.1-SNAPSHOT/2020_08_15-18_22_02/sync-oome

```
Hazelcast Enterprise 4.1-SNAPSHOT (20200814 - 1723575, 7344320) starting
```

```
WARNING: [10.0.0.4]:5701 [C] [4.1-SNAPSHOT] Error occurred when sending WAN events to [10.0.0.205]:5701
com.hazelcast.nio.serialization.HazelcastSerializationException: Failed to serialize 'com.hazelcast.enterprise.wan.impl.operation.WanEventContainerOperation'
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at com.hazelcast.internal.util.ExceptionUtil.tryWrapInSameClass(ExceptionUtil.java:233)
	at com.hazelcast.internal.util.ExceptionUtil.wrapException(ExceptionUtil.java:138)
	at com.hazelcast.internal.util.ExceptionUtil.peel(ExceptionUtil.java:114)
	at com.hazelcast.internal.util.ExceptionUtil.peel(ExceptionUtil.java:73)
	at com.hazelcast.internal.util.ExceptionUtil.rethrow(ExceptionUtil.java:148)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.handleInvocationException(Invocation.java:661)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:543)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:238)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:59)
	at com.hazelcast.enterprise.wan.impl.replication.DefaultWanBatchSender.invokeOnWanTarget(DefaultWanBatchSender.java:63)
	at com.hazelcast.enterprise.wan.impl.replication.DefaultWanBatchSender.send(DefaultWanBatchSender.java:46)
	at com.hazelcast.enterprise.wan.impl.replication.WanBatchPublisher.sendBatch(WanBatchPublisher.java:316)
	at com.hazelcast.enterprise.wan.impl.replication.WanBatchPublisher.tryMakeProgress(WanBatchPublisher.java:180)
	at com.hazelcast.enterprise.wan.impl.replication.WanBatchPublisher.run(WanBatchPublisher.java:144)
	at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
Caused by: com.hazelcast.nio.serialization.HazelcastSerializationException: Failed to serialize 'com.hazelcast.enterprise.wan.impl.operation.WanEventContainerOperation'
	at com.hazelcast.internal.serialization.impl.SerializationUtil.handleSerializeException(SerializationUtil.java:115)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:174)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:150)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:141)
	at com.hazelcast.spi.impl.operationservice.impl.OutboundOperationHandler.toPacket(OutboundOperationHandler.java:63)
	at com.hazelcast.spi.impl.operationservice.impl.OutboundOperationHandler.send(OutboundOperationHandler.java:58)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeRemote(Invocation.java:608)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:580)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:541)
	... 13 more
Caused by: com.hazelcast.nio.serialization.HazelcastSerializationException: Failed to serialize 'com.hazelcast.enterprise.wan.impl.replication.WanEventBatch'
	at com.hazelcast.internal.serialization.impl.SerializationUtil.handleSerializeException(SerializationUtil.java:115)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.writeObject(AbstractSerializationService.java:270)
	at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataOutput.writeObject(ByteArrayObjectDataOutput.java:378)
	at com.hazelcast.enterprise.wan.impl.operation.WanEventContainerOperation.writeInternal(WanEventContainerOperation.java:82)
	at com.hazelcast.spi.impl.operationservice.Operation.writeData(Operation.java:704)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.write(EnterpriseDataSerializableSerializer.java:253)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.write(EnterpriseDataSerializableSerializer.java:52)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.write(StreamSerializerAdapter.java:39)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:171)
	... 20 more
Caused by: com.hazelcast.nio.serialization.HazelcastSerializationException: Failed to serialize 'com.hazelcast.map.impl.wan.WanEnterpriseMapMerkleTreeNode'
	at com.hazelcast.internal.serialization.impl.SerializationUtil.handleSerializeException(SerializationUtil.java:115)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.writeObject(AbstractSerializationService.java:270)
	at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataOutput.writeObject(ByteArrayObjectDataOutput.java:378)
	at com.hazelcast.internal.serialization.impl.SerializationUtil.writeCollection(SerializationUtil.java:282)
	at com.hazelcast.enterprise.wan.impl.replication.WanEventBatch.writeData(WanEventBatch.java:162)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.write(EnterpriseDataSerializableSerializer.java:253)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.write(EnterpriseDataSerializableSerializer.java:52)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.write(StreamSerializerAdapter.java:39)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.writeObject(AbstractSerializationService.java:268)
	... 27 more
Caused by: com.hazelcast.nio.serialization.HazelcastSerializationException: Failed to serialize 'com.hazelcast.map.impl.MerkleTreeNodeEntries'
	at com.hazelcast.internal.serialization.impl.SerializationUtil.handleSerializeException(SerializationUtil.java:115)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.writeObject(AbstractSerializationService.java:270)
	at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataOutput.writeObject(ByteArrayObjectDataOutput.java:378)
	at com.hazelcast.map.impl.wan.WanEnterpriseMapMerkleTreeNode.writeData(WanEnterpriseMapMerkleTreeNode.java:59)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.write(EnterpriseDataSerializableSerializer.java:253)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.write(EnterpriseDataSerializableSerializer.java:52)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.write(StreamSerializerAdapter.java:39)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.writeObject(AbstractSerializationService.java:268)
	... 34 more
```

**Comment by Danny-Hazelcast** [comment]
http://jenkins.hazelcast.com/view/wan/job/wan-sync-oome/56/console

/disk1/jenkins/workspace/wan-sync-oome/4.1-SNAPSHOT/2020_08_16-17_07_57/sync-oome

output/A/HzClient1A/exception.txt
output/A/HzMember1A/core.2670
output/A/HzMember1A/hs_err_pid2670.log
output/A/HzClient2A/exception.txt

 http://54.147.27.51/~jenkins/workspace/wan-sync-oome/4.1-SNAPSHOT/2020_08_16-17_07_57/sync-oome

```
 Hazelcast Enterprise 4.1-SNAPSHOT (20200816 - fcf3899, 7344320) starting
```


```
WARNING: [10.0.0.15]:5701 [A] [4.1-SNAPSHOT] Error occurred when sending WAN events to [10.0.0.222]:5701
com.hazelcast.nio.serialization.HazelcastSerializationException: Failed to serialize 'com.hazelcast.enterprise.wan.impl.operation.WanEventContainerOperation'
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at com.hazelcast.internal.util.ExceptionUtil.tryWrapInSameClass(ExceptionUtil.java:233)
	at com.hazelcast.internal.util.ExceptionUtil.wrapException(ExceptionUtil.java:138)
	at com.hazelcast.internal.util.ExceptionUtil.peel(ExceptionUtil.java:114)
	at com.hazelcast.internal.util.ExceptionUtil.peel(ExceptionUtil.java:73)
	at com.hazelcast.internal.util.ExceptionUtil.rethrow(ExceptionUtil.java:148)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.handleInvocationException(Invocation.java:661)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:543)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:238)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:59)
	at com.hazelcast.enterprise.wan.impl.replication.DefaultWanBatchSender.invokeOnWanTarget(DefaultWanBatchSender.java:63)
	at com.hazelcast.enterprise.wan.impl.replication.DefaultWanBatchSender.send(DefaultWanBatchSender.java:46)
	at com.hazelcast.enterprise.wan.impl.replication.WanBatchPublisher.sendBatch(WanBatchPublisher.java:316)
	at com.hazelcast.enterprise.wan.impl.replication.WanBatchPublisher.tryMakeProgress(WanBatchPublisher.java:180)
	at com.hazelcast.enterprise.wan.impl.replication.WanBatchPublisher.run(WanBatchPublisher.java:144)
	at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
Caused by: com.hazelcast.nio.serialization.HazelcastSerializationException: Failed to serialize 'com.hazelcast.enterprise.wan.impl.operation.WanEventContainerOperation'
	at com.hazelcast.internal.serialization.impl.SerializationUtil.handleSerializeException(SerializationUtil.java:115)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:174)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:150)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:141)
	at com.hazelcast.spi.impl.operationservice.impl.OutboundOperationHandler.toPacket(OutboundOperationHandler.java:63)
	at com.hazelcast.spi.impl.operationservice.impl.OutboundOperationHandler.send(OutboundOperationHandler.java:58)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeRemote(Invocation.java:608)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:580)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:541)
	... 13 more
Caused by: com.hazelcast.nio.serialization.HazelcastSerializationException: Failed to serialize 'com.hazelcast.enterprise.wan.impl.replication.WanEventBatch'
	at com.hazelcast.internal.serialization.impl.SerializationUtil.handleSerializeException(SerializationUtil.java:115)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.writeObject(AbstractSerializationService.java:270)
	at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataOutput.writeObject(ByteArrayObjectDataOutput.java:378)
	at com.hazelcast.enterprise.wan.impl.operation.WanEventContainerOperation.writeInternal(WanEventContainerOperation.java:82)
	at com.hazelcast.spi.impl.operationservice.Operation.writeData(Operation.java:704)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.write(EnterpriseDataSerializableSerializer.java:253)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.write(EnterpriseDataSerializableSerializer.java:52)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.write(StreamSerializerAdapter.java:39)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:171)
	... 20 more
Caused by: com.hazelcast.nio.serialization.HazelcastSerializationException: Failed to serialize 'com.hazelcast.map.impl.wan.WanEnterpriseMapMerkleTreeNode'
	at com.hazelcast.internal.serialization.impl.SerializationUtil.handleSerializeException(SerializationUtil.java:115)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.writeObject(AbstractSerializationService.java:270)
	at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataOutput.writeObject(ByteArrayObjectDataOutput.java:378)
	at com.hazelcast.internal.serialization.impl.SerializationUtil.writeCollection(SerializationUtil.java:282)
	at com.hazelcast.enterprise.wan.impl.replication.WanEventBatch.writeData(WanEventBatch.java:162)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.write(EnterpriseDataSerializableSerializer.java:253)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.write(EnterpriseDataSerializableSerializer.java:52)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.write(StreamSerializerAdapter.java:39)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.writeObject(AbstractSerializationService.java:268)
	... 27 more
Caused by: com.hazelcast.nio.serialization.HazelcastSerializationException: Failed to serialize 'com.hazelcast.map.impl.MerkleTreeNodeEntries'
	at com.hazelcast.internal.serialization.impl.SerializationUtil.handleSerializeException(SerializationUtil.java:115)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.writeObject(AbstractSerializationService.java:270)
	at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataOutput.writeObject(ByteArrayObjectDataOutput.java:378)
	at com.hazelcast.map.impl.wan.WanEnterpriseMapMerkleTreeNode.writeData(WanEnterpriseMapMerkleTreeNode.java:59)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.write(EnterpriseDataSerializableSerializer.java:253)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.write(EnterpriseDataSerializableSerializer.java:52)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.write(StreamSerializerAdapter.java:39)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.writeObject(AbstractSerializationService.java:268)
	... 34 more
```



```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fb58db2a656, pid=2670, tid=0x00007fb58871e700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_201-b09) (build 1.8.0_201-b09)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.201-b09 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# J 8700 C2 com.hazelcast.internal.serialization.impl.NativeMemoryData.toString()Ljava/lang/String; (146 bytes) @ 0x00007fb58db2a656 [0x00007fb58db2a3c0+0x296]
#
# Core dump written. Default location: /home/ec2-user/hz-root/HzMember1A/core or core.2670





[error occurred during error reporting (printing register info), id 0xb]

Stack: [0x00007fb58861e000,0x00007fb58871f000],  sp=0x00007fb58871ca50,  free space=1018k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
J 8700 C2 com.hazelcast.internal.serialization.impl.NativeMemoryData.toString()Ljava/lang/String; (146 bytes) @ 0x00007fb58db2a656 [0x00007fb58db2a3c0+0x296]
J 5479 C1 com.hazelcast.internal.serialization.impl.EnterpriseByteArrayObjectDataOutput.copyFromMemoryBlock(Lcom/hazelcast/internal/memory/MemoryBlock;II)V (82 bytes) @ 0x00007fb58d
17820c [0x00007fb58d177920+0x8ec]
j  com.hazelcast.internal.serialization.impl.EnterpriseByteArrayObjectDataOutput.writeData(Lcom/hazelcast/internal/serialization/Data;)V+35
J 5523 C2 com.hazelcast.map.impl.wan.WanMapEntryView.writeData(Lcom/hazelcast/nio/ObjectDataOutput;)V (117 bytes) @ 0x00007fb58d061020 [0x00007fb58d060fc0+0x60]
J 4868 C2 com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.write(Lcom/hazelcast/nio/ObjectDataOutput;Lcom/hazelcast/nio/serialization/DataSerializable;
)V (127 bytes) @ 0x00007fb58d51cb00 [0x00007fb58d51c7c0+0x340]
J 6241 C2 com.hazelcast.internal.serialization.impl.ByteArrayObjectDataOutput.writeObject(Ljava/lang/Object;)V (12 bytes) @ 0x00007fb58d69b97c [0x00007fb58d69b780+0x1fc]
J 5558 C2 com.hazelcast.map.impl.MerkleTreeNodeEntries.writeData(Lcom/hazelcast/nio/ObjectDataOutput;)V (65 bytes) @ 0x00007fb58ca6289c [0x00007fb58ca625a0+0x2fc]
J 4868 C2 com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.write(Lcom/hazelcast/nio/ObjectDataOutput;Lcom/hazelcast/nio/serialization/DataSerializable;
)V (127 bytes) @ 0x00007fb58d51cb00 [0x00007fb58d51c7c0+0x340]
J 6241 C2 com.hazelcast.internal.serialization.impl.ByteArrayObjectDataOutput.writeObject(Ljava/lang/Object;)V (12 bytes) @ 0x00007fb58d69b97c [0x00007fb58d69b780+0x1fc]
J 5601 C2 com.hazelcast.map.impl.wan.WanEnterpriseMapMerkleTreeNode.writeData(Lcom/hazelcast/nio/ObjectDataOutput;)V (16 bytes) @ 0x00007fb58cfd9b98 [0x00007fb58cfd9b40+0x58]
J 4868 C2 com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.write(Lcom/hazelcast/nio/ObjectDataOutput;Lcom/hazelcast/nio/serialization/DataSerializable;
)V (127 bytes) @ 0x00007fb58d51cb00 [0x00007fb58d51c7c0+0x340]
J 6241 C2 com.hazelcast.internal.serialization.impl.ByteArrayObjectDataOutput.writeObject(Ljava/lang/Object;)V (12 bytes) @ 0x00007fb58d69b97c [0x00007fb58d69b780+0x1fc]
J 6327 C2 com.hazelcast.internal.serialization.impl.SerializationUtil.writeCollection(Ljava/util/Collection;Lcom/hazelcast/nio/ObjectDataOutput;)V (46 bytes) @ 0x00007fb58cf0dd4c [0
x00007fb58cf0da80+0x2cc]
J 8126 C2 com.hazelcast.enterprise.wan.impl.replication.WanEventBatch.writeData(Lcom/hazelcast/nio/ObjectDataOutput;)V (9 bytes) @ 0x00007fb58d6d8794 [0x00007fb58d6d86c0+0xd4]
J 4868 C2 com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.write(Lcom/hazelcast/nio/ObjectDataOutput;Lcom/hazelcast/nio/serialization/DataSerializable;
)V (127 bytes) @ 0x00007fb58d51cb00 [0x00007fb58d51c7c0+0x340]
J 6241 C2 com.hazelcast.internal.serialization.impl.ByteArrayObjectDataOutput.writeObject(Ljava/lang/Object;)V (12 bytes) @ 0x00007fb58d69b97c [0x00007fb58d69b780+0x1fc]
J 8107 C2 com.hazelcast.enterprise.wan.impl.operation.WanEventContainerOperation.writeInternal(Lcom/hazelcast/nio/ObjectDataOutput;)V (29 bytes) @ 0x00007fb58d92d1b4 [0x00007fb58d92
d140+0x74]
J 4401 C2 com.hazelcast.spi.impl.operationservice.Operation.writeData(Lcom/hazelcast/nio/ObjectDataOutput;)V (230 bytes) @ 0x00007fb58d3a5f68 [0x00007fb58d3a57c0+0x7a8]
J 4868 C2 com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.write(Lcom/hazelcast/nio/ObjectDataOutput;Lcom/hazelcast/nio/serialization/DataSerializable;
)V (127 bytes) @ 0x00007fb58d51cb00 [0x00007fb58d51c7c0+0x340]
J 5022 C2 com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.write(Lcom/hazelcast/nio/ObjectDataOutput;Ljava/lang/Object;)V (12 bytes) @ 0x00007fb58d5b6434 [0x00007fb
58d5b63c0+0x74]
J 4674 C2 com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(Ljava/lang/Object;IZLcom/hazelcast/partition/PartitioningStrategy;Ljava/nio/ByteOrder;)[B (1
39 bytes) @ 0x00007fb58d42de88 [0x00007fb58d42da80+0x408]
J 5329 C2 com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeRemote()V (113 bytes) @ 0x00007fb58cfffc74 [0x00007fb58cfff8a0+0x3d4]
J 5402 C2 com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Z)V (180 bytes) @ 0x00007fb58c8a5b08 [0x00007fb58c8a5780+0x388]
J 5412 C2 com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke()Lcom/hazelcast/spi/impl/operationservice/impl/InvocationFuture; (134 bytes) @ 0x00007fb58d3287e4
 [0x00007fb58d328420+0x3c4]
J 7890 C2 com.hazelcast.enterprise.wan.impl.replication.WanBatchPublisher.sendBatch(Lcom/hazelcast/cluster/Address;Lcom/hazelcast/enterprise/wan/impl/replication/WanEventBatch;Z)Z (
64 bytes) @ 0x00007fb58d8ac1fc [0x00007fb58d8ab4c0+0xd3c]
J 8549 C2 com.hazelcast.enterprise.wan.impl.replication.WanBatchPublisher$$Lambda$1116.accept(Ljava/lang/Object;Ljava/lang/Object;)V (28 bytes) @ 0x00007fb58d82b44c [0x00007fb58d82b
1e0+0x26c]
J 7289 C1 com.hazelcast.spi.impl.DeserializingCompletableFuture$DeserializingBiConsumer.accept(Ljava/lang/Object;Ljava/lang/Object;)V (64 bytes) @ 0x00007fb58cebd8cc [0x00007fb58ceb
d500+0x3cc]
J 7936 C2 java.util.concurrent.CompletableFuture.uniWhenComplete(Ljava/util/concurrent/CompletableFuture;Ljava/util/function/BiConsumer;Ljava/util/concurrent/CompletableFuture$UniWh
enComplete;)Z (124 bytes) @ 0x00007fb58d871048 [0x00007fb58d870f80+0xc8]
J 6072 C2 java.util.concurrent.CompletableFuture$Completion.run()V (7 bytes) @ 0x00007fb58d2c64f4 [0x00007fb58d2c6480+0x74]
J 6778 C2 com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run()V (72 bytes) @ 0x00007fb58c8f4314 [0x00007fb58c8f4240+0xd4]
j  java.util.concurrent.ThreadPoolExecutor.runWorker(Ljava/util/concurrent/ThreadPoolExecutor$Worker;)V+95
j  java.util.concurrent.ThreadPoolExecutor$Worker.run()V+5
j  java.lang.Thread.run()V+11
j  com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun()V+1
j  com.hazelcast.internal.util.executor.HazelcastManagedThread.run()V+122
v  ~StubRoutines::call_stub
V  [libjvm.so+0x68825b]  JavaCalls::call_helper(JavaValue*, methodHandle*, JavaCallArguments*, Thread*)+0xddb
V  [libjvm.so+0x685b23]  JavaCalls::call_virtual(JavaValue*, KlassHandle, Symbol*, Symbol*, JavaCallArguments*, Thread*)+0x263
V  [libjvm.so+0x6860e7]  JavaCalls::call_virtual(JavaValue*, Handle, KlassHandle, Symbol*, Symbol*, Thread*)+0x47
V  [libjvm.so+0x6f225c]  thread_entry(JavaThread*, Thread*)+0x6c
V  [libjvm.so+0xa7bb6b]  JavaThread::thread_main_inner()+0xdb
V  [libjvm.so+0xa7be71]  JavaThread::run()+0x2d1
V  [libjvm.so+0x90d922]  java_start(Thread*)+0x102
C  [libpthread.so.0+0x7de5]  start_thread+0xc5
```

**Comment by Danny-Hazelcast** [comment]
<img width="922" alt="Screen Shot 2020-08-17 at 11 29 53" src="https://user-images.githubusercontent.com/5988678/90375018-0a814800-e07d-11ea-9eae-7c949489b42f.png">
<img width="927" alt="Screen Shot 2020-08-17 at 11 30 03" src="https://user-images.githubusercontent.com/5988678/90375034-0e14cf00-e07d-11ea-94b3-abf056580433.png">
