### ISSUE TITLE
hazelcast 4.0.2 support jdk11?

### ISSUE THREAD

**Issue by linking12** [hazelcast/hazelcast#17384]
**Describe the bug**
```java
com.hazelcast.nio.serialization.HazelcastSerializationException: java.lang.ClassNotFoundException: io.github.bucket4j.grid.CommandResult
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2022)
	at io.github.tesla.filter.endpoint.plugin.request.RateLimitEndpointRequestPlugin.doFilter(RateLimitEndpointRequestPlugin.java:66)
	at io.github.tesla.gateway.excutor.ServiceRequestPluginExecutor.doFilter(ServiceRequestPluginExecutor.java:32)
	at io.github.tesla.gateway.netty.filter.HttpRequestFilterChain.doFilter(HttpRequestFilterChain.java:71)
	at io.github.tesla.gateway.netty.HttpFiltersAdapter.clientToProxyRequest(HttpFiltersAdapter.java:162)
	at io.github.tesla.gateway.netty.transmit.connection.ClientToProxyConnection.doReadHTTPInitial(ClientToProxyConnection.java:198)
	at io.github.tesla.gateway.netty.transmit.connection.ClientToProxyConnection.readHTTPInitial(ClientToProxyConnection.java:171)
	at io.github.tesla.gateway.netty.transmit.connection.ClientToProxyConnection.readHTTPInitial(ClientToProxyConnection.java:85)
	at io.github.tesla.gateway.netty.transmit.connection.ProxyConnection.readHTTP(ProxyConnection.java:107)
	at io.github.tesla.gateway.netty.transmit.connection.ProxyConnection.read(ProxyConnection.java:97)
	at io.github.tesla.gateway.netty.transmit.connection.ProxyConnection.channelRead0(ProxyConnection.java:438)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:682)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:617)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:534)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.hazelcast.nio.serialization.HazelcastSerializationException: java.lang.ClassNotFoundException: io.github.bucket4j.grid.CommandResult
	at com.hazelcast.internal.serialization.impl.JavaDefaultSerializers$JavaSerializer.read(JavaDefaultSerializers.java:87)
	at com.hazelcast.internal.serialization.impl.JavaDefaultSerializers$JavaSerializer.read(JavaDefaultSerializers.java:76)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:44)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:203)
	at com.hazelcast.spi.impl.DelegatingCompletableFuture$DeserializingFunction.apply(DelegatingCompletableFuture.java:477)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$ComposeNode.lambda$execute$1(AbstractInvocationFuture.java:1627)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.lang.ClassNotFoundException: io.github.bucket4j.grid.CommandResult
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at com.hazelcast.internal.nio.ClassLoaderUtil.tryLoadClass(ClassLoaderUtil.java:287)
	at com.hazelcast.internal.nio.ClassLoaderUtil.loadClass(ClassLoaderUtil.java:251)
	at com.hazelcast.internal.nio.IOUtil$ClassLoaderAwareObjectInputStream.resolveClass(IOUtil.java:783)
	at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1943)
	at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1829)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2117)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1646)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:464)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
	at com.hazelcast.internal.serialization.impl.JavaDefaultSerializers$JavaSerializer.read(JavaDefaultSerializers.java:83)
	... 11 more
```

**Expected behavior**
        There is no error
**To Reproduce**
         Use Jdk11

**Additional context**
I think com.hazelcast.internal.nio.ClassLoaderUtil is something wrong;

**Comment by jerrinot** [comment]
@linking12: do you have the bucket4j library on a classpath of you Hazelcast members?

**Comment by linking12** [comment]
@jerrinot  yes，I have bucket4j-hazelcast in my classpath;
                      <dependency>
				<groupId>com.github.vladimir-bukhtoyarov</groupId>
				<artifactId>bucket4j-hazelcast</artifactId>
				<version>4.10.0</version>
			</dependency>

**Comment by jerrinot** [comment]
@linking12: are you sure you have bucket4j library available on Hazelcast server classpath? 
I have tried it with JDK 14 and it works for me just fine. See the [example](https://github.com/jerrinot/ratelimiter/tree/b50fdc09a91d451bf050fef6b995d3db58c75a0a/src/test/java/info/jerrinot). 

You start 2 instances of the `Member`[https://github.com/jerrinot/ratelimiter/blob/b50fdc09a91d451bf050fef6b995d3db58c75a0a/src/test/java/info/jerrinot/Member.java] and then the [demo](https://github.com/jerrinot/ratelimiter/blob/b50fdc09a91d451bf050fef6b995d3db58c75a0a/src/test/java/info/jerrinot/BucketTest.java)

**Comment by linking12** [comment]
@jerrinot  
![image](https://user-images.githubusercontent.com/4882172/90787327-329bd000-e337-11ea-8a8e-dcffeb5b5cea.png)

JDK:
https://corretto.aws/downloads/latest/amazon-corretto-11-x64-linux-jdk.tar.gz

JDK Version:
![image](https://user-images.githubusercontent.com/4882172/90787597-78589880-e337-11ea-8355-6befb71f5873.png)

**Comment by linking12** [comment]
@jerrinot  
Can you compile your code in jdk8 and run it in jdk11?  I think class loader is changed; so you can not reduce it;

**Comment by jerrinot** [comment]
@linking12 I just tried it with corretto-11.0.8 and it's working just fine.

In theory it could be some interaction between Spring Boot fat jar and Hazelcast classloading. If you could prepare a demo project and upload it to Github it would really help to speed-up investigation.

**Comment by linking12** [comment]
@jerrinot  
I have fix this problem，maybe is spring boot container issue，i fix it as shown below；
![image](https://user-images.githubusercontent.com/4882172/91008210-6f561880-e610-11ea-95a6-16544f2bd589.png)

But when I upgrade jdk8 to jdk11，I have another issue，may be is replicaMigrationFailed triggered，Do you have any idea？
![image](https://user-images.githubusercontent.com/4882172/91008323-b6440e00-e610-11ea-8baa-55f6367a6d62.png)
