### ISSUE TITLE
Cp subsystem client is froze after restart cp subsystem server instances

### ISSUE THREAD

**Issue by mariusz2108** [hazelcast/hazelcast#17436]
**Describe the bug**
After restarting all server instances of cp subsystem client throws NotLeaderException

**Expected behavior**
Client should connect to cluster and work fine.

**To Reproduce**

1. Run cp subsystem server with 3 instances.
`    public static void main(String[] args) {
        System.out.println(ManagementFactory.getRuntimeMXBean().getName());
        final HazelcastInstance hazelcastInstance1 = Hazelcast.newHazelcastInstance();
        final HazelcastInstance hazelcastInstance2 = Hazelcast.newHazelcastInstance();
        final HazelcastInstance hazelcastInstance3 = Hazelcast.newHazelcastInstance();
        CPSubsystem cpSubsystem1 = hazelcastInstance1.getCPSubsystem();
    }`
2. Run client which acquires and releases lock.
`    public static void main(String[] args) throws ExecutionException, InterruptedException {
        System.out.println(ManagementFactory.getRuntimeMXBean().getName());
        ClientConfig clientConfig = new ClientConfig();
        ClientNetworkConfig networkConfig = new ClientNetworkConfig();
        networkConfig.addAddress("localhost");
        clientConfig.setNetworkConfig(networkConfig);
        HazelcastInstance hazelcastInstance1 = HazelcastClient.newHazelcastClient(clientConfig);
        CPSubsystem cpSubsystem = hazelcastInstance1.getCPSubsystem();

        FencedLock lock = cpSubsystem.getLock("Lock");
        while (true) {
            try {
                boolean locked = lock.tryLock();
                try {
                    System.out.println("Locked");
                } finally {
                    if (locked) {
                        lock.unlock();
                    }
                }
                Thread.sleep(1000);
            } catch (NotLeaderException e) {
                System.out.println("Error");
                e.printStackTrace();
            }
        }
    }`
3. Restart server instances (in same moment)
**Additional context**
After client start everything works fine - Locked is printed
After server restart following warnings are printed:
`Aug 31, 2020 2:30:50 PM com.hazelcast.spi.impl.operationservice.impl.Invocation
WARNING: [10.0.2.4]:5000 [dev] [4.0.2] Retrying invocation: Invocation{op=com.hazelcast.cp.internal.operation.DefaultRaftReplicateOp{serviceName='hz:core:raft', identityHash=817427346, partitionId=217, replicaIndex=0, callId=702, invocationTime=1598877050098 (2020-08-31 14:30:50.098), waitTimeout=-1, callTimeout=60000, groupId=CPGroupId{name='default', seed=0, groupId=3740}, op=com.hazelcast.cp.internal.datastructures.lock.operation.TryLockOp{serviceName='hz:raft:lockService', name=Lock, sessionId=1, threadId=1, invocationUid=0d11373d-6a98-421f-a1f9-c1866ef59556, timeoutMs=0, callerAddress=null, callId=0}}, tryCount=250, tryPauseMillis=500, invokeCount=100, callTimeoutMillis=60000, firstInvocationTimeMs=1598877015384, firstInvocationTime='2020-08-31 14:30:15.384', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 01:00:00.000', target=[10.0.2.4]:5002, pendingResponse={VOID}, backupsAcksExpected=-1, backupsAcksReceived=0, connection=Connection[id=3, /10.0.2.4:5000->/10.0.2.4:41817, qualifier=null, endpoint=[10.0.2.4]:5002, alive=true, connectionType=MEMBER]}, Reason: com.hazelcast.cp.exception.NotLeaderException: RaftEndpoint{uuid='0b5786b1-d312-4ace-aded-8017b4d94a02'} is not LEADER of CPGroupId{name='default', seed=0, groupId=3740}. Known leader is: N/A
`
Client throws following error:
`com.hazelcast.cp.exception.NotLeaderException: null is not LEADER of null. Known leader is: N/A
	at com.hazelcast.cp.exception.NotLeaderException.wrap(NotLeaderException.java:42)
	at com.hazelcast.cp.exception.NotLeaderException.wrap(NotLeaderException.java:28)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.wrapRuntimeException(AbstractInvocationFuture.java:1932)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.wrapOrPeel(AbstractInvocationFuture.java:1915)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$ExceptionalResult.wrapForJoinInternal(AbstractInvocationFuture.java:1400)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.resolveAndThrowForJoinInternal(AbstractInvocationFuture.java:593)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.joinInternal(AbstractInvocationFuture.java:577)
	at com.hazelcast.spi.impl.DelegatingCompletableFuture.joinInternal(DelegatingCompletableFuture.java:135)
	at com.hazelcast.cp.internal.datastructures.lock.proxy.AbstractFencedLockProxy.tryLockAndGetFence(AbstractFencedLockProxy.java:172)
	at com.hazelcast.cp.internal.datastructures.lock.proxy.AbstractFencedLockProxy.tryLockAndGetFence(AbstractFencedLockProxy.java:148)
	at com.hazelcast.cp.internal.datastructures.lock.proxy.AbstractFencedLockProxy.tryLock(AbstractFencedLockProxy.java:143)
	at com.hazelcast.client.cp.internal.datastructures.lock.FencedLockProxy.tryLock(FencedLockProxy.java:103)`

**Comment by mmedenjak** [comment]
Hi @mariusz2108 ! I guess @mdogan can confirm but unless you're using CP persistence (which is an enterprise feature), restarting a member causes it to basically become a completely new replica. That said, if you restart all members, there is no initial member available and the CP subsystem cannot make progress. So this should be by-design.

**Comment by mdogan** [comment]
If you restart all cluster members, without CP persistence, they will form a fresh new CP subsystem. In this case, `default` CP group, which your `FencedLock` belongs to, will be assigned a new group ID. 

If you look at the warning log at the server, you can see its former ID: `groupId=CPGroupId{name='default', seed=0, groupId=3740}`. After restart `default` group should have a different ID assigned. 

That's why the `FencedLock` object you acquired before restarting members will not work anymore.  You should acquire a new lock object using `cpSubsystem.getLock("Lock")` again.

This is by design, because without persistence enabled, when you restart all members, all CP state/data are lost. And the consistency of the formerly created CP objects become broken.

**Comment by mdogan** [comment]
Still, we should be able to report it with a better exception, with a more meaningful message.
