### ISSUE TITLE
PostJoinMapOperationTest.testPostJoinMapOperation_mapWithIndex

### ISSUE THREAD

**Issue by mdogan** [hazelcast/hazelcast#17453]
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/2180/testReport/junit/com.hazelcast.map.impl.operation/PostJoinMapOperationTest/testPostJoinMapOperation_mapWithIndex/

```
java.lang.AssertionError: isIndexed should have located an index expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.map.impl.operation.PostJoinMapOperationTest$1.run(PostJoinMapOperationTest.java:234)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1248)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1350)
	at com.hazelcast.map.impl.operation.PostJoinMapOperationTest.testPostJoinMapOperation_mapWithIndex(PostJoinMapOperationTest.java:230)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by mdogan** [comment]
There was an earlier issue: https://github.com/hazelcast/hazelcast/issues/8257 for the same test.

**Comment by mmedenjak** [comment]
@ahmetmircik can we close this with https://github.com/hazelcast/hazelcast/pull/17521? Is there anything else that you wanted to do?

**Comment by ahmetmircik** [comment]
@mmedenjak Yes, we can close this one, despite more than thousand runs, i couldn't manage to reproduce the issue, but i added new logs to diagnose issue better for the next failure.
