### ISSUE TITLE
Management Center Reload Security Config button fails. java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by MonDeveloper** [hazelcast/hazelcast#17463]
**Describe the bug**
Management Center **Reload Security Config** button fails.

**Expected behavior**
The system load the configuration provided via `securityHotReload.properties`.

**To Reproduce**

1. Installation WAR based, started via command line (`hazelcast-management-center-4.0.war`)
  ```
  "C:\Program Files\Java\jre1.8.0_221\bin\java"   -XX:+ExitOnOutOfMemoryError -Xmx256m -Xms64m -Dsf.environment="Integration" -Dlogback.configurationFile="C:/xxx/yyy/zzz/logback.loader.path/logback-spring.xml" -Dhazelcast.mc.http.port="8101" -Dhazelcast.mc.phone.home.enabled="false" -Dhazelcast.mc.home="C:/xxx/yyy/zzz/hazelcast.mc.home" -cp "C:/kkk/www/Crif.REApp.020.HAZELCAST__Type_App91/HAZELCAST-MC__Pkg.Code.2.0.0 [20200902.135857-178] - 4.0/lib/hazelcast-management-center-4.0.war;C:/kkk/www/Crif.REApp.020.HAZELCAST__Type_App91/HAZELCAST-MC__Pkg.Code.2.0.0 [20200902.135857-178] - 4.0/_scripts.override/../addons;C:/kkk/www/Crif.REApp.020.HAZELCAST__Type_App91/HAZELCAST-MC__Pkg.Code.2.0.0 [20200902.135857-178] - 4.0/_scripts.override/../addons/*;C:/xxx/yyy/zzz/logback.loader.path;C:/xxx/yyy/zzz/logback.loader.path/*" "com.hazelcast.webmonitor.Launcher"
  ```
2. Add the file `securityHotReload.properties` under the mc.home `C:/xxx/yyy/zzz/hazelcast.mc.home`
3. Open Chrome browser and go to the `http://<servername>:8101/login.html`
4. Click on the `Reload Security Config` button
  at this point the UI return a toast with this error: 
  `Failed to reload security configuration. Please check Management Center server logs to see the details.`
  and the server logged this message:
   ```
   org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.NullPointerException
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder$NotAsyncServlet.service(ServletHolder.java:1400)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:760)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1617)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:209)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1596)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:545)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:590)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1607)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1297)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:485)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1577)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1212)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:59)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:500)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:547)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:270)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:388)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
	at java.lang.Thread.run(Unknown Source)
   Caused by: java.lang.NullPointerException: null
	at java.util.Hashtable.put(Unknown Source)
	at java.util.Properties.setProperty(Unknown Source)
	at com.hazelcast.webmonitor.security.spi.impl.activedirectory.ActiveDirectoryConfig.toProperties(ActiveDirectoryConfig.java:107)
	at com.hazelcast.webmonitor.security.spi.impl.ldap.PersistentActiveDirectoryConfig.write(PersistentActiveDirectoryConfig.java:24)
	at com.hazelcast.webmonitor.security.spi.impl.activedirectory.ActiveDirectorySecurityProvider.writeConfig(ActiveDirectorySecurityProvider.java:124)
	at com.hazelcast.webmonitor.security.spi.impl.activedirectory.ActiveDirectorySecurityProvider.reloadConfig(ActiveDirectorySecurityProvider.java:112)
	at com.hazelcast.webmonitor.security.spi.impl.AuthenticationManagerImpl.reloadSecurityConfig(AuthenticationManagerImpl.java:173)
	at com.hazelcast.webmonitor.controller.api.SecurityConfigController.reloadConfig(SecurityConfigController.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:888)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	... 44 common frames omitted
   ```

**Additional context**

**Comment by yuraku** [comment]
Hello @MonDeveloper . 

I've tried to reproduce the issue with no luck, I was using the `Management Center 4.2020.08` and LDAP server based on this: https://hub.docker.com/r/osixia/openldap

Could you please provide more details to help us identify the issue:
1. You can try to change the log level to `DEBUG` : https://docs.hazelcast.org/docs/management-center/4.2020.08/manual/html/index.html#configuring-logging
2. Could you please also share the content of `securityHotReload.properties` (it can be anonymised)
3. Any other logs (possibly from LDAP server) that can help.

Thanks.
