### ISSUE TITLE
MetricCompressor can decompress what it compresses

### ISSUE THREAD

**Issue by alex-dukhno** [hazelcast/hazelcast#17519]
This issue was reported for MC https://github.com/hazelcast/management-center/issues/3757
However, from the exception stacktrace I see MetricCompressor miscalculates index here https://github.com/hazelcast/hazelcast/blob/4.0.1/hazelcast/src/main/java/com/hazelcast/internal/metrics/impl/MetricsCompressor.java#L405
```
2020-08-12 10:48:18 [MetricsConsumer] ERROR c.h.w.s.metrics.MetricsConsumer - Could not process Jet metrics from Member [192.168.1.114]:5701 - 2278023f-f6f6-4b00-8682-14bd3cf8a763 of cluster jet.
java.lang.StringIndexOutOfBoundsException: null
	at java.lang.AbstractStringBuilder.delete(AbstractStringBuilder.java:760)
	at java.lang.StringBuilder.delete(StringBuilder.java:244)
	at com.hazelcast.internal.metrics.impl.MetricsCompressor.readDictionary(MetricsCompressor.java:405)
	at com.hazelcast.internal.metrics.impl.MetricsCompressor.extractMetrics(MetricsCompressor.java:375)
	at com.hazelcast.internal.metrics.impl.MetricsCompressor.extractMetrics(MetricsCompressor.java:349)
	at com.hazelcast.webmonitor.metrics.jet.JetClusterMetricsStore.storeMetricsCollection(JetClusterMetricsStore.java:94)
	at com.hazelcast.webmonitor.service.jet.JetMetricsService.save(JetMetricsService.java:29)
	at com.hazelcast.webmonitor.service.jet.JetMetricsService$$FastClassBySpringCGLIB$$ef0fda9.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:685)
	at com.hazelcast.webmonitor.service.jet.JetMetricsService$$EnhancerBySpringCGLIB$$bdc11c63.save(<generated>)
	at com.hazelcast.webmonitor.service.metrics.MetricsConsumer.consumeJetCollection(MetricsConsumer.java:131)
	at com.hazelcast.webmonitor.service.metrics.MetricsConsumer.access$400(MetricsConsumer.java:40)
	at com.hazelcast.webmonitor.service.metrics.MetricsConsumer$JetCollectionConsumer.apply(MetricsConsumer.java:248)
	at com.hazelcast.webmonitor.service.metrics.MetricsConsumer.lambda$readMetrics$2(MetricsConsumer.java:99)
	at com.hazelcast.client.impl.ClientDelegatingFuture$WhenCompleteAdapter.apply(ClientDelegatingFuture.java:482)
	at com.hazelcast.client.impl.ClientDelegatingFuture$WhenCompleteAdapter.apply(ClientDelegatingFuture.java:469)
	at com.hazelcast.client.impl.spi.impl.ClientInvocationFuture$CallIdTrackingBiFunction.apply(ClientInvocationFuture.java:266)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$HandleNode.lambda$execute$0(AbstractInvocationFuture.java:1499)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-08-12 10:48:18 [MetricsConsumer] ERROR c.h.w.s.metrics.MetricsConsumer - Could not process metrics from Member [192.168.1.114]:5701 - 2278023f-f6f6-4b00-8682-14bd3cf8a763 of cluster jet.
java.lang.StringIndexOutOfBoundsException: null
	at java.lang.AbstractStringBuilder.delete(AbstractStringBuilder.java:760)
	at java.lang.StringBuilder.delete(StringBuilder.java:244)
	at com.hazelcast.internal.metrics.impl.MetricsCompressor.readDictionary(MetricsCompressor.java:405)
	at com.hazelcast.internal.metrics.impl.MetricsCompressor.extractMetrics(MetricsCompressor.java:375)
	at com.hazelcast.internal.metrics.impl.MetricsCompressor.extractMetrics(MetricsCompressor.java:349)
	at com.hazelcast.webmonitor.service.metrics.MetricsConsumer.consumeImdgCollection(MetricsConsumer.java:141)
	at com.hazelcast.webmonitor.service.metrics.MetricsConsumer.access$500(MetricsConsumer.java:40)
	at com.hazelcast.webmonitor.service.metrics.MetricsConsumer$JetCollectionConsumer.apply(MetricsConsumer.java:249)
	at com.hazelcast.webmonitor.service.metrics.MetricsConsumer.lambda$readMetrics$2(MetricsConsumer.java:99)
	at com.hazelcast.client.impl.ClientDelegatingFuture$WhenCompleteAdapter.apply(ClientDelegatingFuture.java:482)
	at com.hazelcast.client.impl.ClientDelegatingFuture$WhenCompleteAdapter.apply(ClientDelegatingFuture.java:469)
	at com.hazelcast.client.impl.spi.impl.ClientInvocationFuture$CallIdTrackingBiFunction.apply(ClientInvocationFuture.java:266)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$HandleNode.lambda$execute$0(AbstractInvocationFuture.java:1499)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
I can reproduce it with MC and Jet setup, but couldn't find unit test reproducer.

**Comment by alex-dukhno** [comment]
Closing as it is not reproducible with `4.0.2` version which has the same source as `4.1`.

Sorry guys for disturbance.
