### ISSUE TITLE
LocalMultiMapStatsTest.testPutAllAndHitsGeneratedMap

### ISSUE THREAD

**Issue by mmedenjak** [hazelcast/hazelcast#17533]
```
[ERROR] Failures: 
[ERROR]   ClientMultiMapStatsTest>LocalMultiMapStatsTest.testPutAllAndHitsGeneratedKey:152->LocalMultiMapStatsTest.testPutAllAndHitsGeneratedTemplate:124->testPutAllAndHitsGeneratedTemplateVerify:74 expected:<100> but was:<99>
[ERROR]   ClientMultiMapStatsTest>LocalMultiMapStatsTest.testPutAllAndHitsGeneratedMap:142->LocalMultiMapStatsTest.testPutAllAndHitsGeneratedTemplate:124->testPutAllAndHitsGeneratedTemplateVerify:74 expected:<100> but was:<96>
```

http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/2319
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/2263

**Comment by petrpleshachkov** [comment]
Can be similar to the https://github.com/hazelcast/hazelcast-enterprise/issues/3706

**Comment by olukas** [comment]
Reopen since it failed again on `4.2.z` branch with CorrettoJDK8: http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-4.maintenance-CorrettoJDK8/144/testReport/

Stacktrace:
```
java.lang.AssertionError: expected:<100> but was:<99>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at com.hazelcast.multimap.LocalMultiMapStatsTest.testPutAllAndHitsGeneratedTemplateVerify(LocalMultiMapStatsTest.java:131)
	at com.hazelcast.multimap.LocalMultiMapStatsTest.testPutAllAndHitsGeneratedTemplate(LocalMultiMapStatsTest.java:123)
	at com.hazelcast.multimap.LocalMultiMapStatsTest.testPutAllAndHitsGeneratedKey(LocalMultiMapStatsTest.java:151)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

Standard output:
```
06:19:32,366  INFO |testHitsGenerated_updatedConcurrently| - [MetricsConfigHelper] Thread-56720 - [LOCAL] [dev] [4.2.3-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
06:19:32,366  INFO |testGetAndHitsGenerated| - [MetricsConfigHelper] Thread-56721 - [LOCAL] [dev] [4.2.3-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
06:19:32,366  INFO |testLockedEntryCount_emptyMultiMap| - [MetricsConfigHelper] Thread-56722 - [LOCAL] [dev] [4.2.3-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
Finished Running Test: testLastAccessTime in 0.026 seconds.
06:19:32,366  INFO |testGetAndHitsGenerated| - [system] Thread-56721 - [127.0.0.1]:5701 [dev] [4.2.3-SNAPSHOT] Hazelcast 4.2.3-SNAPSHOT (20210814 - a516020) starting at [127.0.0.1]:5701
06:19:32,366  INFO |testHitsGenerated_updatedConcurrently| - [system] Thread-56720 - [127.0.0.1]:5701 [dev] [4.2.3-SNAPSHOT] Hazelcast 4.2.3-SNAPSHOT (20210814 - a516020) starting at [127.0.0.1]:5701
06:19:32,366  INFO |testLockedEntryCount_emptyMultiMap| - [system] Thread-56722 - [127.0.0.1]:5701 [dev] [4.2.3-SNAPSHOT] Hazelcast 4.2.3-SNAPSHOT (20210814 - a516020) starting at [127.0.0.1]:5701
06:19:32,368  INFO |testGetAndHitsGenerated| - [MetricsConfigHelper] Thread-56721 - [127.0.0.1]:5701 [dev] [4.2.3-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
06:19:32,368  INFO |testHitsGenerated_updatedConcurrently| - [MetricsConfigHelper] Thread-56720 - [127.0.0.1]:5701 [dev] [4.2.3-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
06:19:32,368  INFO |testLockedEntryCount_emptyMultiMap| - [MetricsConfigHelper] Thread-56722 - [127.0.0.1]:5701 [dev] [4.2.3-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
```

**Comment by olukas** [comment]
Changing milestone to `5.0` since it failed also on `master` on ZingJDK8: http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZingJDK8/329/testReport/com.hazelcast.multimap/LocalMultiMapStatsTest/testPutAllAndHitsGeneratedMap/

**Comment by olukas** [comment]
Failed on `master` on OracleJDK8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-OracleJDK8/208/testReport/com.hazelcast.multimap/LocalMultiMapStatsTest/testPutAllAndHitsGeneratedKey/

**Comment by Patras3** [comment]
Failed again on _master_ with ZingJDK8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZingJDK8/467/testReport/junit/com.hazelcast.multimap/LocalMultiMapStatsTest/testPutAllAndHitsGeneratedKey/

**Comment by mdumandag** [comment]
This should also be fixed by https://github.com/hazelcast/hazelcast/pull/22836
