### ISSUE TITLE
DelegatingCompletableFuture_WrappingInvocationFutureTest

### ISSUE THREAD

**Issue by mdogan** [hazelcast/hazelcast#17566]
```
java.lang.AssertionError: expected:<java.lang.Object@7a5b4ab2> but was:<com.hazelcast.spi.impl.AbstractInvocationFuture$WhenCompleteNode@3f59cb9d>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.spi.impl.CompletableFutureAbstractTest.exceptionally_whenAsync(CompletableFutureAbstractTest.java:812)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/2389/testReport/junit/com.hazelcast.spi.impl/DelegatingCompletableFuture_WrappingInvocationFutureTest/exceptionally_whenAsync/

**Comment by mmedenjak** [comment]
Possibly caused by https://github.com/hazelcast/hazelcast/pull/17518? cc @vbekiaris
