### ISSUE TITLE
NPE for null field in 4.1-BETA-1 querying

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast#17608]
On 4.1-BETA-1, a query such as

```
"SELECT firstName FROM " + mapName + " WHERE lastName != 'Stevenson'";
```

for data such as 
```
            Person person3 = new Person();
            person3.setFirstName(null);
            person3.setLastName("Zzz");
```

Gives an NPE,

```
com.hazelcast.sql.HazelcastSqlException: java.lang.NullPointerException
	at com.hazelcast.sql.impl.QueryUtils.toPublicException(QueryUtils.java:79) ~[hazelcast-4.1-BETA-1.jar!/:4.1-BETA-1]
	at com.hazelcast.sql.impl.client.SqlClientService.rethrow(SqlClientService.java:242) ~[hazelcast-4.1-BETA-1.jar!/:4.1-BETA-1]
	at com.hazelcast.sql.impl.client.SqlClientService.rethrow(SqlClientService.java:233) ~[hazelcast-4.1-BETA-1.jar!/:4.1-BETA-1]
	at com.hazelcast.sql.impl.client.SqlClientService.execute(SqlClientService.java:114) ~[hazelcast-4.1-BETA-1.jar!/:4.1-BETA-1]
	at com.hazelcast.sql.SqlService.execute(SqlService.java:144) ~[hazelcast-4.1-BETA-1.jar!/:4.1-BETA-1]
```

I have a reproducer, but it's due to the field being null.

**Comment by mmedenjak** [comment]
@devozerov can you take a look?

**Comment by devozerov** [comment]
Confirming. Our protocol cannot pass the null values back.
