### ISSUE TITLE
ClassDefinitionBuilder doesn't check for duplicate fields

### ISSUE THREAD

**Issue by viliam-durina** [hazelcast/hazelcast#17616]
This test fails in current `master`:
```java
    @Test
    public void test_duplicateField() {
        ClassDefinition def = new ClassDefinitionBuilder(1, 2)
                .addIntField("f")
                .addIntField("f")
                .build();

        GenericRecord.Builder.portable(def)
                .writeInt("f", 1)
                .build();
    }
```
The error is:
```
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at com.hazelcast.internal.serialization.impl.portable.PortableGenericRecordBuilder.write(PortableGenericRecordBuilder.java:172)
	at com.hazelcast.internal.serialization.impl.portable.PortableGenericRecordBuilder.writeInt(PortableGenericRecordBuilder.java:71)
	at com.hazelcast.internal.serialization.impl.portable.ClassAndFieldDefinitionTest.test_duplicateField(ClassAndFieldDefinitionTest.java:64)
```

Expected behavior is to fail at the second `addIntField` call or, less preferably, when building the CD. Currently it produces broken class definition that has 1 field and the only field has index=1.

Calling it an enhancement because the use case is broken, it just should fail earlier.

**Comment by mmedenjak** [comment]
@sancar can you take a look?
