### ISSUE TITLE
CPMemberAddRemoveTest when_cpMembersShutdownConcurrently_then_theyCompleteTheirShutdown

### ISSUE THREAD

**Issue by lazerion** [hazelcast/hazelcast#17650]
- Fails on `Hazelcast-4.master-CorrettoJDK8`
- Fails on [Build #92 (Sep 30, 2020 6:14:00 AM)](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-4.master-CorrettoJDK8/92/testReport/junit/com.hazelcast.cp.internal/CPMemberAddRemoveTest/when_cpMembersShutdownConcurrently_then_theyCompleteTheirShutdown/)
- Error
```
test timed out after 300000 milliseconds
```
- Stacktrace
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1695)
	at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3323)
	at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1775)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
	at com.hazelcast.spi.impl.DeserializingCompletableFuture.get(DeserializingCompletableFuture.java:88)
	at com.hazelcast.internal.util.FutureUtil.executeWithDeadline(FutureUtil.java:389)
	at com.hazelcast.internal.util.FutureUtil.waitWithDeadline(FutureUtil.java:356)
	at com.hazelcast.internal.util.FutureUtil.waitWithDeadline(FutureUtil.java:330)
	at com.hazelcast.instance.impl.Node.callGracefulShutdownAwareServices(Node.java:565)
	at com.hazelcast.instance.impl.Node.shutdown(Node.java:502)
	at com.hazelcast.instance.impl.LifecycleServiceImpl.shutdown(LifecycleServiceImpl.java:101)
	at com.hazelcast.instance.impl.LifecycleServiceImpl.shutdown(LifecycleServiceImpl.java:84)
	at com.hazelcast.instance.impl.HazelcastInstanceProxy.shutdown(HazelcastInstanceProxy.java:304)
	at com.hazelcast.cp.internal.CPMemberAddRemoveTest.when_cpMembersShutdownConcurrently_then_theyCompleteTheirShutdown(CPMemberAddRemoveTest.java:1001)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```
- Exception in logs
```
connection=com.hazelcast.internal.server.FirewallingServer$FirewallingConnection@12393de9}, Reason: com.hazelcast.spi.exception.TargetNotMemberException: Not Member! target: CPMember{uuid=a54e8cb4-3b52-4e31-841b-bc35d39c4f59, address=[127.0.0.1]:5703}, partitionId: 0, operation: com.hazelcast.cp.internal.operation.RaftQueryOp, service: hz:core:raft
```
- kindly check

**Comment by lazerion** [comment]
- Also fails on [Build #70 (Oct 6, 2020 8:14:01 AM)](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-4.master-ZuluJDK13/70/testReport/junit/com.hazelcast.cp.internal/CPMemberAddRemoveTest/when_cpMembersShutdownConcurrently_then_theyCompleteTheirShutdown/)

**Comment by PavloBida** [comment]
Also fails on Coretto builds [JDK8](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-4.maintenance-CorrettoJDK8/101/) and [JDK11 14-Jan-2021 02:12](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-4.maintenance-CorrettoJDK11/101/)

**Comment by sancar** [comment]
My initial finding is that test is taking around 3 to 4 minutes to finish even in healthy runs. 
And the test timeout is 5 minutes. So when it is a little bit more slow, it timed out. And the logs suggest that they were not stuck. The shutdown of all members completes without timeout. 

I will investigate a little more to understand if it is normal for this test to take minutes rather than seconds.

**Comment by mmedenjak** [comment]
cc @alex-dukhno who also might have run into long shutdown procedures in failing WAN tests ☝️

**Comment by sancar** [comment]
@jerrinot You were right here https://github.com/hazelcast/hazelcast/pull/18243#issuecomment-781917035
It was not a test problem and there was an actual bug after all. 
I found the root cause of this. I will reopen the issue and send the new fix.
