### ISSUE TITLE
hang at map size after cluster split brain healed 

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#17707]
http://jenkins.hazelcast.com/view/split/job/split-x2/19/console 

 sh hz-bench-run-jenkins-split hz/stable/sql/mixed

 /disk1/jenkins/workspace/split-x2/4.1-SNAPSHOT/2020_10_09-10_24_43/mixed

 is hanging at a call to map size at the end of the test after the cluster has been healed.

**Comment by jerrinot** [comment]
@Danny-Hazelcast is going to re-run it with diagnostics enabled.

Some observations: The threadump indeed shows a bunch of stuck(?) `map.size()` calls. 
Example:
```
"pool-67-thread-1" #517 prio=5 os_prio=0 tid=0x00007f9fe0005000 nid=0x122e waiting on condition [0x00007f9f9e0c0000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000deb73640> (a java.util.concurrent.CompletableFuture$Signaller)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1693)
	at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3323)
	at java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1729)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
	at com.hazelcast.spi.impl.operationservice.impl.InvokeOnPartitions.invoke(InvokeOnPartitions.java:87)
	at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.invokeOnAllPartitions(OperationServiceImpl.java:404)
	at com.hazelcast.map.impl.proxy.MapProxySupport.size(MapProxySupport.java:790)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.size(MapProxyImpl.java:106)
	at hzcmd.map.validate.Size.timeStep(Size.java:13)
	at remote.bench.marker.RollMarker.flatOut(RollMarker.java:72)
	at remote.bench.marker.RollMarker.bench(RollMarker.java:59)
	at remote.bench.BenchThread.call(BenchThread.java:41)
	at remote.bench.BenchThread.call(BenchThread.java:14)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
the `size()` is coming from [this](https://github.com/hazelcast/hzCmd-bench/blob/zeta/src/main/java/hzcmd/map/validate/Size.java#L15)

I can see partition threads are doing some work. Example:
```
	"hz.vigorous_greider.partition-operation.thread-2" #20 prio=5 os_prio=0 tid=0x00007f2748aa1800 nid=0xa46 runnable [0x00007f2729618000]
   java.lang.Thread.State: RUNNABLE
	at sun.misc.Unsafe.unpark(Native Method)
	at java.util.concurrent.ForkJoinPool.signalWork(ForkJoinPool.java:1649)
	at java.util.concurrent.ForkJoinPool.externalPush(ForkJoinPool.java:2414)
	at java.util.concurrent.ForkJoinPool.execute(ForkJoinPool.java:2648)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$WhenCompleteNode.execute(AbstractInvocationFuture.java:1515)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.unblockOtherNode(AbstractInvocationFuture.java:756)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.unblockAll(AbstractInvocationFuture.java:713)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.complete0(AbstractInvocationFuture.java:1190)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.complete(AbstractInvocationFuture.java:1174)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.complete(Invocation.java:675)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.sendResponse(Invocation.java:239)
	at com.hazelcast.spi.impl.operationservice.Offload$OffloadedOperationResponseHandler.sendResponse(Offload.java:166)
	at com.hazelcast.spi.impl.operationservice.Operation.sendResponse(Operation.java:470)
	at com.hazelcast.spi.impl.operationservice.impl.operations.PartitionIteratingOperation$OperationResponseHandlerImpl.sendResponse(PartitionIteratingOperation.java:270)
	at com.hazelcast.spi.impl.operationservice.impl.operations.PartitionIteratingOperation$OperationResponseHandlerImpl.sendResponse(PartitionIteratingOperation.java:258)
	at com.hazelcast.spi.impl.operationservice.Operation.sendResponse(Operation.java:470)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:266)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:237)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:213)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:160)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:190)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:144)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
```
or
```
"hz.blissful_snyder.partition-operation.thread-1" #19 prio=5 os_prio=0 tid=0x00007fa03ca8e800 nid=0xa08 runnable [0x00007fa01c3e3000]
   java.lang.Thread.State: RUNNABLE
	at com.hazelcast.spi.impl.operationservice.Operation.sendResponse(Operation.java:470)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:266)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:237)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:213)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:160)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:190)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:144)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
```
So this does not look like a deadlock. At least not inside an operation. 

The `size()` are a part of validation after a bunch of split-brain runs. It's called at the very end of a test. Nothing else should be running at this point. 

The question is: why there are the `size()`? related operation running 6 minutes after the validation started? 
Possible explanation:
- a bug in the testing framework. This is unlikely, given the same framework is used for a whole bunch of other tests, including ohter split-brain tests. 
- a bug in Hazelcast: where the `size()` call never finish and it keeps sending size operation factory to members.

It's hard to tell more from just a standard output. @Danny-Hazelcast is going to re-run this with Diagnostics enabled.

**Comment by Danny-Hazelcast** [comment]
passed on 3.12.10


failing on 4.1-SANP

Diagnostics enabled.  


log trace http://jenkins.hazelcast.com/view/split/job/split-x2/31/console
log debug http://jenkins.hazelcast.com/view/split/job/split-x3/25/console

**Comment by Danny-Hazelcast** [comment]
inital hang issue was caused by test ignoring exceptions by mistake.
time out for merge operation increased 
healing is slow,  much slower than other split heal tests.

```
(base) [jenkins@ip-10-72-134-107 split-sql]$ cat output/HZ/HzMember1HZAA/out.txt | grep clusterAAMerged.*fin
HzMember1HZAA clusterAAMerged hzcmd.ops.Merged threadId=0  finished duration 805 seconds
HzMember1HZAA clusterAAMerged hzcmd.ops.Merged threadId=0  finished duration 290 seconds
HzMember1HZAA clusterAAMerged hzcmd.ops.Merged threadId=0  finished duration 185 seconds
HzMember1HZAA clusterAAMerged hzcmd.ops.Merged threadId=0  finished duration 165 seconds
HzMember1HZAA clusterAAMerged hzcmd.ops.Merged threadId=0  finished duration 370 seconds
HzMember1HZAA clusterAAMerged hzcmd.ops.Merged threadId=0  finished duration 415 seconds
HzMember1HZAA clusterAAMerged hzcmd.ops.Merged threadId=0  finished duration 420 seconds
HzMember1HZAA clusterAAMerged hzcmd.ops.Merged threadId=0  finished duration 405 seconds
HzMember1HZAA clusterAAMerged hzcmd.ops.Merged threadId=0  finished duration 190 seconds
HzMember1HZAA clusterAAMerged hzcmd.ops.Merged threadId=0  finished duration 470 seconds
(base) [jenkins@ip-10-72-134-107 split-sql]$
(base) [jenkins@ip-10-72-134-107 split-sql]$ cat output/HZ/HzMember2HZAA/out.txt | grep clusterAAMerged.*fin
HzMember2HZAA clusterAAMerged hzcmd.ops.Merged threadId=0  finished duration 1290 seconds
HzMember2HZAA clusterAAMerged hzcmd.ops.Merged threadId=0  finished duration 65 seconds
HzMember2HZAA clusterAAMerged hzcmd.ops.Merged threadId=0  finished duration 215 seconds
HzMember2HZAA clusterAAMerged hzcmd.ops.Merged threadId=0  finished duration 360 seconds
HzMember2HZAA clusterAAMerged hzcmd.ops.Merged threadId=0  finished duration 270 seconds
HzMember2HZAA clusterAAMerged hzcmd.ops.Merged threadId=0  finished duration 120 seconds
HzMember2HZAA clusterAAMerged hzcmd.ops.Merged threadId=0  finished duration 425 seconds
HzMember2HZAA clusterAAMerged hzcmd.ops.Merged threadId=0  finished duration 240 seconds
HzMember2HZAA clusterAAMerged hzcmd.ops.Merged threadId=0  finished duration 330 seconds
HzMember2HZAA clusterAAMerged hzcmd.ops.Merged threadId=0  finished duration 265 seconds
```

1 split heal round,  stack trace every 5s
http://jenkins.hazelcast.com/view/split/job/split-sql/25/console  stack trace in out.txt
http://jenkins.hazelcast.com/view/split/job/split-sql/28/console stack trace in separate file
