### ISSUE TITLE
SlowOperationDetectorBasicTest testSlowRecursiveOperation

### ISSUE THREAD

**Issue by lazerion** [hazelcast/hazelcast#17711]
- Fails on `Hazelcast-4.master-sonar`
- Fails on [Build #648 (Oct 10, 2020 9:17:00 PM)](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-4.master-sonar/648/testReport/junit/com.hazelcast.spi.impl.operationexecutor.slowoperationdetector/SlowOperationDetectorBasicTest/testSlowRecursiveOperation/)
- Error
```
test timed out after 300000 milliseconds
```
- Stacktrace
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
	at com.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationDetectorAbstractTest$JoinableOperation.join(SlowOperationDetectorAbstractTest.java:268)
	at com.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationDetectorBasicTest.testSlowRecursiveOperation(SlowOperationDetectorBasicTest.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```
- Hiccups
```
Hiccups measured while running test 'testSlowRecursiveOperation(com.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationDetectorBasicTest):'
01:27:05, accumulated pauses: 65 ms, max pause: 9 ms, pauses over 1000 ms: 0
01:27:10, accumulated pauses: 40 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:27:15, accumulated pauses: 38 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:27:20, accumulated pauses: 36 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:27:25, accumulated pauses: 41 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:27:30, accumulated pauses: 45 ms, max pause: 1 ms, pauses over 1000 ms: 0
01:27:35, accumulated pauses: 40 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:27:40, accumulated pauses: 47 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:27:45, accumulated pauses: 42 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:27:50, accumulated pauses: 45 ms, max pause: 1 ms, pauses over 1000 ms: 0
01:27:55, accumulated pauses: 41 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:28:00, accumulated pauses: 42 ms, max pause: 1 ms, pauses over 1000 ms: 0
01:28:05, accumulated pauses: 40 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:28:10, accumulated pauses: 47 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:28:15, accumulated pauses: 41 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:28:20, accumulated pauses: 39 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:28:25, accumulated pauses: 43 ms, max pause: 2 ms, pauses over 1000 ms: 0
01:28:30, accumulated pauses: 39 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:28:35, accumulated pauses: 43 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:28:40, accumulated pauses: 35 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:28:45, accumulated pauses: 36 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:28:50, accumulated pauses: 40 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:28:55, accumulated pauses: 43 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:29:00, accumulated pauses: 42 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:29:05, accumulated pauses: 41 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:29:10, accumulated pauses: 43 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:29:15, accumulated pauses: 44 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:29:20, accumulated pauses: 42 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:29:25, accumulated pauses: 43 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:29:30, accumulated pauses: 44 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:29:35, accumulated pauses: 41 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:29:40, accumulated pauses: 47 ms, max pause: 1 ms, pauses over 1000 ms: 0
01:29:45, accumulated pauses: 43 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:29:50, accumulated pauses: 43 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:29:55, accumulated pauses: 41 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:30:00, accumulated pauses: 43 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:30:05, accumulated pauses: 42 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:30:10, accumulated pauses: 43 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:30:15, accumulated pauses: 42 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:30:20, accumulated pauses: 46 ms, max pause: 2 ms, pauses over 1000 ms: 0
01:30:25, accumulated pauses: 46 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:30:30, accumulated pauses: 45 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:30:35, accumulated pauses: 44 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:30:40, accumulated pauses: 42 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:30:45, accumulated pauses: 47 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:30:50, accumulated pauses: 41 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:30:55, accumulated pauses: 44 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:31:00, accumulated pauses: 42 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:31:05, accumulated pauses: 45 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:31:10, accumulated pauses: 42 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:31:15, accumulated pauses: 45 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:31:20, accumulated pauses: 42 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:31:25, accumulated pauses: 43 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:31:30, accumulated pauses: 42 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:31:35, accumulated pauses: 43 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:31:40, accumulated pauses: 49 ms, max pause: 2 ms, pauses over 1000 ms: 0
01:31:45, accumulated pauses: 40 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:31:50, accumulated pauses: 41 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:31:55, accumulated pauses: 37 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:32:00, accumulated pauses: 41 ms, max pause: 1 ms, pauses over 1000 ms: 0
01:32:05, accumulated pauses: 835 ms, max pause: 807 ms, pauses over 1000 ms: 0
```
- It looks due to hiccups, yet I do not recall similar recently on this one.
- Kindly check

**Comment by jerrinot** [comment]
The `SlowRecursiveOperation` is simply not executed at all and this the [`operation.join();`](https://github.com/hazelcast/hazelcast/blob/3687b51c1312f1978e0661bad341cfc77aaab362/hazelcast/src/test/java/com/hazelcast/spi/impl/operationexecutor/slowoperationdetector/SlowOperationDetectorBasicTest.java#L216) is waiting indefinitely causing a timeout. 

Why is not executed? It's because the operation runner is [checking](https://github.com/hazelcast/hazelcast/blob/baaeac7a3363f56a722a2eca2d563bfc495a73b8/hazelcast/src/main/java/com/hazelcast/spi/impl/operationservice/impl/OperationRunnerImpl.java#L344) whether the local member is the right target. This check may currently fails as at the moment of the check the initial partition assignment may not be completed yet. Normally it's not a problem as this result in `WrongTargetException` and once it's delivered to an `Invocation` the opereation will be retried. However this test does not use Invocation, it uses raw operations. 

Now why it's failing in the current master, but it's passing in 4.0? It's a side-effect of [Parallel Migrations](https://github.com/hazelcast/hazelcast/commit/7455c6693a37b3636af106e043e095087c6d7100) This PR is [replacing](https://github.com/hazelcast/hazelcast/commit/7455c6693a37b3636af106e043e095087c6d7100#diff-607745e90a90fce445da6b6532d724a1R244-R247) a regular `lock()` with `tryLock()` so when this method returns there is a higher chance of the assignment not being completed yet. This method is [triggered by OperationRunner](https://github.com/hazelcast/hazelcast/blob/baaeac7a3363f56a722a2eca2d563bfc495a73b8/hazelcast/src/main/java/com/hazelcast/spi/impl/operationservice/impl/OperationRunnerImpl.java#L334) before doing the ownership check. 

The test is using a single member. So in 4.0 the partition runner triggers the assignment, wait until it's completed and then continues. When multiple partition threads triggers the assignment then they all block until it's finished. However in 4.1 a partition thread may fail to acquire the lock and it will return from the `getPartition()` before the initial assignment is completed. 

What to do about it? Well: The current behaviour of `OperationRunner` does not violate contract, I consider this to be a bad test - it's using raw Operation instead of Invocation. I will send a PR changing this.
