### ISSUE TITLE
Failing PartitionIndexingTest.testOnProgrammaticallyAddedIndexes

### ISSUE THREAD

**Issue by kwart** [hazelcast/hazelcast#17724]
The test `PartitionIndexingTest.testOnProgrammaticallyAddedIndexes[format:OBJECT]` failed on PR builder (`master` branch).
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/2689/

**Stacktrace**
```
java.lang.AssertionError: map_hash_this is missing 1 partitions expected:<101> but was:<100>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at com.hazelcast.query.impl.PartitionIndexingTest.assertPartitionsIndexedCorrectly(PartitionIndexingTest.java:218)
	at com.hazelcast.query.impl.PartitionIndexingTest.testOnProgrammaticallyAddedIndexes(PartitionIndexingTest.java:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by olukas** [comment]
Closing the test failure - it doesn't seem to be related to `master` or the latest maintenance stream `5.5.z`. Feel free to reopen test failure if it occurs on `master` or on the latest maintenance stream.
