### ISSUE TITLE
ExecutorService does not propagate exceptions from task

### ISSUE THREAD

**Issue by Holmistr** [hazelcast/hazelcast#17796]
**Describe the bug**
Having a `Runnable` task that is executed on `ExecutorService`, if there's an exception thrown in the `run` method, the exception is silently swallowed and is not propagated to the client or in the member logs in any way.

**Expected behavior**
At least a log entry in the member log with the exception.

**To Reproduce**
Having this task:
```
public class MyRunnable implements Runnable, Serializable {

    @Override
    public void run() {
        throw new NullPointerException("my NPE");
    }

}
```

Executing it using:
```
public static void main(String[] args) {
        Config config = new Config();
        HazelcastInstance member = Hazelcast.newHazelcastInstance(config);

        IExecutorService executor = member.getExecutorService( "exec" );
        System.out.println("Running task.");
        executor.execute(new MyRunnable());
        System.out.println("Finished task");

        //        member.shutdown();
    }
```

Output:
```
INFO: [192.168.1.100]:5701 [dev] [4.1-SNAPSHOT] [192.168.1.100]:5701 is STARTING
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.hazelcast.internal.networking.nio.SelectorOptimizer (file:/home/jholusa/.m2/repository/com/hazelcast/hazelcast-all/4.1-SNAPSHOT/hazelcast-all-4.1-SNAPSHOT.jar) to field sun.nio.ch.SelectorImpl.selectedKeys
WARNING: Please consider reporting this to the maintainers of com.hazelcast.internal.networking.nio.SelectorOptimizer
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
říj 29, 2020 9:38:16 ODP. com.hazelcast.internal.cluster.ClusterService
INFO: [192.168.1.100]:5701 [dev] [4.1-SNAPSHOT] 

Members {size:1, ver:1} [
	Member [192.168.1.100]:5701 - cea76de2-9ec1-4145-bade-6d241a652146 this
]

říj 29, 2020 9:38:16 ODP. com.hazelcast.core.LifecycleService
INFO: [192.168.1.100]:5701 [dev] [4.1-SNAPSHOT] [192.168.1.100]:5701 is STARTED
Running task.
říj 29, 2020 9:38:16 ODP. com.hazelcast.internal.partition.impl.PartitionStateManager
INFO: [192.168.1.100]:5701 [dev] [4.1-SNAPSHOT] Initializing cluster partition table arrangement...
Finished task
```

*IMDG version:* 4.1-SNAPSHOT (`93be758`)

**Comment by sancar** [comment]
@Holmistr They are logged at the finest level. 
```
14:49:55,350 TRACE || - [DistributedExecutorService] hz.cool_bohr.cached.thread-3 - [127.0.0.1]:5701 [dev] [4.1-SNAPSHOT] While executing callable: RunnableAdapter{task=XNode$MyRunnable@1cde742e}
java.util.concurrent.ExecutionException: java.lang.NullPointerException: my NPE
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.hazelcast.executor.impl.DistributedExecutorService$Processor.run(DistributedExecutorService.java:278)
	at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
Caused by: java.lang.NullPointerException: my NPE
	at XNode$MyRunnable.run(XNode.java:18)
	at com.hazelcast.executor.impl.RunnableAdapter.call(RunnableAdapter.java:56)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at com.hazelcast.executor.impl.DistributedExecutorService$Processor.run(DistributedExecutorService.java:276)
	... 6 more
```

**Comment by Holmistr** [comment]
@sancar Aaaaah ... I would have never thought of that. What's the reasoning behind this? If something goes wrong within my executor service, I probably want to learn about that.

**Comment by sancar** [comment]
Since the exception is already propagated to the callers from most of the API, we leave that to the user. If the user needs to take action upon exception, they can via callbacks or futures. If no action is needed, then the exception log itself probably has no value. 
If you think about a cluster with a large number of clients, it makes sense not to pollute server logs with exceptions. It will be hard to keep track of them anyway.

**Comment by Holmistr** [comment]
> Since the exception is already propagated to the callers from most of the API

What do you mean by that? That the client will actually receive the exception on `execute` method? My point is that I don't receive any exception even with this code:

```
public static void main(String[] args) {
        Config config = new Config();
        HazelcastInstance member = Hazelcast.newHazelcastInstance(config);

        HazelcastInstance client = HazelcastClient.newHazelcastClient();

        IExecutorService executor = client.getExecutorService( "exec" );
        System.out.println("Running task.");
        executor.execute(new MyRunnable());
        System.out.println("Finished task");

        //        member.shutdown();
    }
```

Task:
```
public class MyRunnable implements Runnable, Serializable {

    @Override
    public void run() {
        throw new NullPointerException("my NPE");
    }

}
```

Output:
```
INFO: hz.client_1 [dev] [4.1-SNAPSHOT] 

Members [1] {
	Member [10.0.0.18]:5701 - 000748fb-06b1-49d0-96b9-0d027225c02c
}

lis 01, 2020 5:53:54 ODP. com.hazelcast.client.impl.statistics.ClientStatisticsService
INFO: Client statistics is enabled with period 5 seconds.
Running task.
Finished task
lis 01, 2020 5:53:54 ODP. com.hazelcast.internal.partition.impl.PartitionStateManager
INFO: [10.0.0.18]:5701 [dev] [4.1-SNAPSHOT] Initializing cluster partition table arrangement...
```
```

**Comment by sancar** [comment]
What I meant is, they can use `submit` instead of `execute` to get the exception on the caller side and act on it. If they are using `execute`, they don't want to act on the response(or exception). It is fire-and-forget op.

One improvement we could do is to add a default callback on the `execute` so that it logs the exception on the caller side(instead of logging exceptions on the server by default). 
We are sending the exception to the caller(whether the caller is the client or the member), we just don't log it.
