### ISSUE TITLE
Error when enabling CP subsystem with rolling change

### ISSUE THREAD

**Issue by jerrinot** [hazelcast/hazelcast#17837]
Hello,

I have 3 members of Hazelcast 4.1 running in a kubernetes cluster. They have this configuration:
```yaml
hazelcast:
  network:
    join:
      kubernetes:
        enabled: true
        namespace: ${namespace}
        service-name: ${serviceName}
      multicast:
        enabled: false
    rest-api:
      enabled: true
      endpoint-groups:
        HEALTH_CHECK:
          enabled: true
```
as you can see they have CP subsystem disabled. I want to enable CP the CP so I change the config to
```yaml
hazelcast:
  network:
    join:
      kubernetes:
        enabled: true
        namespace: ${namespace}
        service-name: ${serviceName}
      multicast:
        enabled: false
    rest-api:
      enabled: true
      endpoint-groups:
        HEALTH_CHECK:
          enabled: true
  cp-subsystem:
    cp-member-count: 3
    group-size: 3
```
and restart all cluster members on by one. `$ kubectl rollout restart statefulset hazelcast-release`
This floods logs with various error message such as:
```
:00:00.000', target=[10.1.236.16]:5701, pendingResponse={VOID}, backupsAcksExpected=-1, backupsAcksReceived=2, connection=null}, Reason: com.hazelcast.cp.internal.exception.MetadataRaftGroupInitInProgressException
2020-11-09 21:40:13,550 [ WARN] [hz.jovial_goldwasser.partition-operation.thread-0] [c.h.s.i.o.i.Invocation]: [10.1.236.16]:5701 [dev] [4.1] Retrying invocation: Invocation{op=com.hazelcast.cp.internal.operation.unsafe.UnsafeRaftQueryOp{serviceName='hz:core:raft', identityHash=1539013033, partitionId=0, replicaIndex=0, callId=32826, invocationTime=1604958013531 (2020-11-09 21:40:13.531), waitTimeout=-1, callTimeout=60000, groupId=CPGroupId{name='METADATA', seed=0, groupId=0}, op=com.hazelcast.cp.internal.raftop.metadata.GetRaftGroupOp{serviceName='hz:core:raft', targetGroupId=CPGroupId{name='METADATA', seed=0, groupId=0}}}, tryCount=250, tryPauseMillis=500, invokeCount=200, callTimeoutMillis=60000, firstInvocationTimeMs=1604957944378, firstInvocationTime='2020-11-09 21:39:04.378', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 00:00:00.000', target=[10.1.236.16]:5701, pendingResponse={VOID}, backupsAcksExpected=-1, backupsAcksReceived=2, connection=null}, Reason: com.hazelcast.cp.internal.exception.MetadataRaftGroupInitInProgressException
2020-11-09 21:40:13,555 [ WARN] [hz.jovial_goldwasser.partition-operation.thread-0] [c.h.s.i.o.i.Invocation]: [10.1.236.16]:5701 [dev] [4.1] Retrying invocation: Invocation{op=com.hazelcast.cp.internal.operation.unsafe.UnsafeRaftQueryOp{serviceName='hz:core:raft', identityHash=1457211872, partitionId=0, replicaIndex=0, callId=32829, invocationTime=1604958013536 (2020-11-09 21:40:13.536), waitTimeout=-1, callTimeout=60000, groupId=CPGroupId{name='METADATA', seed=0, groupId=0}, op=com.hazelcast.cp.internal.raftop.metadata.GetRaftGroupOp{serviceName='hz:core:raft', targetGroupId=CPGroupId{name='METADATA', seed=0, groupId=0}}}, tryCount=250, tryPauseMillis=500, invokeCount=240, callTimeoutMillis=60000, firstInvocationTimeMs=1604957931361, firstInvocationTime='2020-11-09 21:38:51.361', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 00:00:00.000', target=[10.1.236.16]:5701, pendingResponse={VOID}, backupsAcksExpected=-1, backupsAcksReceived=2, connection=null}, Reason: com.hazelcast.cp.internal.exception.MetadataRaftGroupInitInProgressException
2020-11-09 21:40:13,567 [ WARN] [hz.jovial_goldwasser.partition-operation.thread-0] [c.h.s.i.o.i.Invocation]: [10.1.236.16]:5701 [dev] [4.1] Retrying invocation: Invocation{op=com.hazelcast.cp.internal.operation.unsafe.UnsafeRaftQueryOp{serviceName='hz:core:raft', identityHash=92272356, partitionId=0, replicaIndex=0, callId=32831, invocationTime=1604958013547 (2020-11-09 21:40:13.547), waitTimeout=-1, callTimeout=60000, groupId=CPGroupId{name='METADATA', seed=0, groupId=0}, op=com.hazelcast.cp.internal.raftop.metadata.GetRaftGroupOp{serviceName='hz:core:raft', targetGroupId=CPGroupId{name='METADATA', seed=0, groupId=0}}}, tryCount=250, tryPauseMillis=500, invokeCount=190, callTimeoutMillis=60000, firstInvocationTimeMs=1604957947396, firstInvocationTime='2020-11-09 21:39:07.396', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 00:00:00.000', target=[10.1.236.16]:5701, pendingResponse={VOID}, backupsAcksExpected=-1, backupsAcksReceived=2, connection=null}, Reason: com.hazelcast.cp.internal.exception.MetadataRaftGroupInitInProgressException
2020-11-09 21:40:13,656 [ WARN] [hz.jovial_goldwasser.partition-operation.thread-0] [c.h.s.i.o.i.Invocation]: [10.1.236.16]:5701 [dev] [4.1] Retrying invocation: Invocation{op=com.hazelcast.cp.internal.operation.unsafe.UnsafeRaftQueryOp{serviceName='hz:core:raft', identityHash=2072602887, partitionId=0, replicaIndex=0, callId=32846, invocationTime=1604958013636 (2020-11-09 21:40:13.636), waitTimeout=-1, callTimeout=60000, groupId=CPGroupId{name='METADATA', seed=0, groupId=0}, op=com.hazelcast.cp.internal.raftop.metadata.GetRaftGroupOp{serviceName='hz:core:raft', targetGroupId=CPGroupId{name='METADATA', seed=0, groupId=0}}}, tryCount=250, tryPauseMillis=500, invokeCount=160, callTimeoutMillis=60000, firstInvocationTimeMs=1604957957996, firstInvocationTime='2020-11-09 21:39:17.996', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 00:00:00.000', target=[10.1.236.16]:5701, pendingResponse={VOID}, backupsAcksExpected=-1, backupsAcksReceived=2, connection=null}, Reason: com.hazelcast.cp.internal.exception.MetadataRaftGroupInitInProgressException
```
or
```
2020-11-09 21:40:57,475 [ERROR] [hz.charming_blackburn.partition-operation.thread-0] [c.h.i.p.o.MigrationOperation]: [10.1.192.78]:5701 [dev] [4.1] Error while executing replication operations MigrationInfo{uuid=28a2625a-c9a9-4e37-8071-2f8f2cce9373, partitionId=0, source=null, sourceCurrentReplicaIndex=-1, sourceNewReplicaIndex=-1, destination=[10.1.192.78]:5701 - dd130fb5-40bb-49c1-8b9a-7057afb493a3, destinationCurrentReplicaIndex=-1, destinationNewReplicaIndex=1, master=[10.1.236.16]:5701, initialPartitionVersion=137, partitionVersionIncrement=1, status=ACTIVE}
java.lang.NullPointerException: null
	at com.hazelcast.cp.internal.RaftService.applyUnsafeModeState(RaftService.java:1381) ~[hazelcast-all-4.1.jar:4.1]
	at com.hazelcast.cp.internal.operation.unsafe.UnsafeStateReplicationOp.run(UnsafeStateReplicationOp.java:46) ~[hazelcast-all-4.1.jar:4.1]
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:184) ~[hazelcast-all-4.1.jar:4.1]
	at com.hazelcast.spi.impl.operationexecutor.OperationRunner.runDirect(OperationRunner.java:150) ~[hazelcast-all-4.1.jar:4.1]
	at com.hazelcast.internal.partition.operation.MigrationOperation.runMigrationOperation(MigrationOperation.java:135) ~[hazelcast-all-4.1.jar:4.1]
	at com.hazelcast.internal.partition.operation.MigrationOperation.doRun(MigrationOperation.java:112) [hazelcast-all-4.1.jar:4.1]
	at com.hazelcast.internal.partition.operation.MigrationOperation.run(MigrationOperation.java:92) [hazelcast-all-4.1.jar:4.1]
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:184) [hazelcast-all-4.1.jar:4.1]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:256) [hazelcast-all-4.1.jar:4.1]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:237) [hazelcast-all-4.1.jar:4.1]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:452) [hazelcast-all-4.1.jar:4.1]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:166) [hazelcast-all-4.1.jar:4.1]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:136) [hazelcast-all-4.1.jar:4.1]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123) [hazelcast-all-4.1.jar:4.1]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) [hazelcast-all-4.1.jar:4.1]
```
or
```
2020-11-09 21:41:03,606 [ERROR] [hz.charming_blackburn.partition-operation.thread-0] [c.h.i.p.o.MigrationOperation]: [10.1.192.78]:5701 [dev] [4.1] Error while executing replication operations MigrationInfo{uuid=403c46d3-9dbd-44e2-91af-3344f182f3fe, partitionId=0, source=null, sourceCurrentReplicaIndex=-1, sourceNewReplicaIndex=-1, destination=[10.1.192.78]:5701 - dd130fb5-40bb-49c1-8b9a-7057afb493a3, destinationCurrentReplicaIndex=-1, destinationNewReplicaIndex=1, master=[10.1.236.16]:5701, initialPartitionVersion=141, partitionVersionIncrement=1, status=ACTIVE}
java.lang.NullPointerException: null
	at com.hazelcast.cp.internal.RaftService.applyUnsafeModeState(RaftService.java:1381) ~[hazelcast-all-4.1.jar:4.1]
	at com.hazelcast.cp.internal.operation.unsafe.UnsafeStateReplicationOp.run(UnsafeStateReplicationOp.java:46) ~[hazelcast-all-4.1.jar:4.1]
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:184) ~[hazelcast-all-4.1.jar:4.1]
	at com.hazelcast.spi.impl.operationexecutor.OperationRunner.runDirect(OperationRunner.java:150) ~[hazelcast-all-4.1.jar:4.1]
	at com.hazelcast.internal.partition.operation.MigrationOperation.runMigrationOperation(MigrationOperation.java:135) ~[hazelcast-all-4.1.jar:4.1]
	at com.hazelcast.internal.partition.operation.MigrationOperation.doRun(MigrationOperation.java:112) [hazelcast-all-4.1.jar:4.1]
	at com.hazelcast.internal.partition.operation.MigrationOperation.run(MigrationOperation.java:92) [hazelcast-all-4.1.jar:4.1]
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:184) [hazelcast-all-4.1.jar:4.1]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:256) [hazelcast-all-4.1.jar:4.1]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:237) [hazelcast-all-4.1.jar:4.1]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:452) [hazelcast-all-4.1.jar:4.1]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:166) [hazelcast-all-4.1.jar:4.1]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:136) [hazelcast-all-4.1.jar:4.1]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123) [hazelcast-all-4.1.jar:4.1]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) [hazelcast-all-4.1.jar:4.1]
```

**Comment by jerrinot** [comment]
it's probably not related to kuberentes at all. I will try to prepare a simpler reproducer.

**Comment by mmedenjak** [comment]
As discussed on slack, as a general rule we don't allow changing configuration with rolling restart. In some cases it'll actually work, but none of it has been tested. 
The reason is, cluster start is a careful orchestration of processes between members - threads start, structures are sized as configured, no-op instances are set if something is disabled, that kind of thing. And here we assume other members will behave as expected according to that configuration as well.

And then comes a rolling restart which places members having some configuration/feature inside the same cluster with other members not having that configuration/feature. Assumptions break and exceptions arise. 

We can fix this issue but I'd rather introduce more support for dynamically adding/changing configuration, as needed.

**Comment by GiovaniFerraroTrivelli** [comment]
I'm having this issue in 5.3.1. Are fixes still considered? Thanks!
