### ISSUE TITLE
Parsing of hazelcast.xml configuration fails if xerces is on classpath

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#17839]
If `xerces` is on classpath and no other XML processor is on classpath before it then parsing `hazelcast.xml` fails with following exception and IMDG is not started:
```
Exception in thread "main" com.hazelcast.core.HazelcastException: org.xml.sax.SAXNotRecognizedException: Property 'http://javax.xml.XMLConstants/property/accessExternalSchema' is not recognized.
	at com.hazelcast.internal.util.ExceptionUtil.lambda$static$0(ExceptionUtil.java:55)
	at com.hazelcast.internal.util.ExceptionUtil.peel(ExceptionUtil.java:133)
	at com.hazelcast.internal.util.ExceptionUtil.peel(ExceptionUtil.java:76)
	at com.hazelcast.internal.util.ExceptionUtil.rethrow(ExceptionUtil.java:138)
	at com.hazelcast.config.XmlConfigBuilder.build(XmlConfigBuilder.java:153)
	at com.hazelcast.config.XmlConfigBuilder.build(XmlConfigBuilder.java:144)
	at com.hazelcast.config.Config.loadFromFile(Config.java:225)
	at com.hazelcast.config.Config.load(Config.java:208)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:125)
	at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:91)
	at com.hazelcast.core.server.HazelcastMemberStarter.main(HazelcastMemberStarter.java:47)
Caused by: org.xml.sax.SAXNotRecognizedException: Property 'http://javax.xml.XMLConstants/property/accessExternalSchema' is not recognized.
	at org.apache.xerces.jaxp.validation.XMLSchemaFactory.setProperty(Unknown Source)
	at com.hazelcast.config.AbstractXmlConfigHelper.schemaValidation(AbstractXmlConfigHelper.java:116)
	at com.hazelcast.config.XmlConfigBuilder.parseAndBuildConfig(XmlConfigBuilder.java:169)
	at com.hazelcast.config.XmlConfigBuilder.build(XmlConfigBuilder.java:151)
	... 6 more
```

It's a regression between Hazelcast IMDG 4.0 and 4.1.

How to Reproduce:
- put `xercesImpl-2.12.0.jar` to classpath and try to start Hazelcast IMDG by `start.sh` script

Hazelcast Jet is using the same properties - https://github.com/hazelcast/hazelcast-jet/blob/master/hazelcast-jet-core/src/main/java/com/hazelcast/jet/config/JetConfigXmlGenerator.java#L92 - the same fix as for this issue should be applied also there.

**Comment by kwart** [comment]
This is a tricky one. Java 7 (u40) introduced JAXP 1.5 and Java 8 contains JAXP 1.6. So the default XML processing implementation in Java just works with the properties we configure.

The problem comes when an old JAXP implementation is added to the classpath (e.g. Xerces, Xalan). The old libraries don't support the properties we use to enable XXE protection and the exception is thrown.

I'll try to workaround it by adding a system property that would allow ignoring the failed property configuration.
