### ISSUE TITLE
hazelcast-sql-4.1.1-SNAPSHOT missing dependency

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast#17863]
Using `hazelcast-sql-4.1.1-SNAPSHOT` (hazelcast-sql-4.1.1-20201106.130301-8.jar)
has a dependency on json-path:2.4.0
which gives the below

```
Caused by: java.lang.ClassNotFoundException: net.minidev.json.writer.JsonReaderI
	at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151) ~[application.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	at com.jayway.jsonpath.internal.DefaultsImpl.<init>(DefaultsImpl.java:17) ~[json-path-2.4.0.jar!/:2.4.0]
	at com.jayway.jsonpath.internal.DefaultsImpl.<clinit>(DefaultsImpl.java:15) ~[json-path-2.4.0.jar!/:2.4.0]
	at com.jayway.jsonpath.Configuration.getEffectiveDefaults(Configuration.java:48) ~[json-path-2.4.0.jar!/:2.4.0]
	at com.jayway.jsonpath.Configuration.access$000(Configuration.java:34) ~[json-path-2.4.0.jar!/:2.4.0]
	at com.jayway.jsonpath.Configuration$ConfigurationBuilder.build(Configuration.java:229) ~[json-path-2.4.0.jar!/:2.4.0]
```

However, the 4.1.1-SNAPSHOT build from snapshot repository is from 6th Nov, so not up to date potentially

**Comment by neilstevenson** [comment]
I get the same when I build from source. Snapshot repo being stale isn't ideal, but might not be the problem

**Comment by neilstevenson** [comment]
Adding `net.minidev:json-smart:jar:2.3` to shading might be enough

**Comment by mmedenjak** [comment]
@devozerov can you take a look?

**Comment by devozerov** [comment]
@neilstevenson do you have a reproducer for the problem?

**Comment by mmedenjak** [comment]
@neilstevenson any updates on the issue?

**Comment by neilstevenson** [comment]
@mmedenjak Problem does not recur, so either fixed since reporting or was stale artifacts.
