### ISSUE TITLE
Wrong ClassLoader for IMap.executeOnKeys after moving from 3.12 to 4.1

### ISSUE THREAD

**Issue by bokken** [hazelcast/hazelcast#17867]
**Describe the bug**
We have hazelcast deployed in a war in tomcat. After updating from 3.12 to 4.1, we occasionally find that calls to IMap.executeOnKeys will fail with a serialization error caused by `java.lang.ClassNotFoundException`. 
We were not explicitly setting the classloader in the Config before creating the Hazelcast instance.
This does not happen on every war deployment, indicating there is likely some initialization order/race condition leading to this scenario.

**Expected behavior**
The same classloader should be used for all interactions, not different for IMap.executeOnKeys.

**To Reproduce**

We are not able to reproduce on demand.
Explicitly setting the classloader in the Config appears to be resolving the issue. However, given the inconsistent nature of occurrence to begin with, we are not completely certain of that yet.

**Additional context**

Hazelcast version 4.1
AdoptOpenJDK 11.0.9 hotspot x86_64
Linux RHEL/OEL 7 (various updates)
Cluster size from 2-4, but only ever seen in cluster members in Tomcat. We have 1 cluster which is a mix of Tomcat and simple jse executable and we will see this in the logs from the webapp, but not the simple jse executable.
We are not using any integration modules. We explicitly manage the hazelcast lifecycle.
Objects are stored in BINARY format.

In this code example, the keys are serializable proprietary objects (i.e. not Strings):

```
        try
        {
            return (Set) realCache.executeOnKeys((Set<Object>) keysAsSet, e -> {
                if (e == null)
                {
                    return null;
                }
                if (e instanceof LazyMapEntry)
                {
                    return ((LazyMapEntry)e).hasNullValue() ? null : Boolean.TRUE;
                }
                return e.getValue() == null ? null : Boolean.TRUE;
            }).keySet();
        }
        catch (HazelcastSerializationException hse)
        {
            logSerializationIssue("containsAny", hse, keysAsSet);

            final Set<Object> actualKeys = getKeys();
            final Set<K> results = Collections3.newSetWithExpectedSize(keysAsSet.size());
            for (Object key : keysAsSet)
            {
                if(actualKeys.contains(key))
                {
                    results.add((K) key);
                }
            }
            return results;
        }
```

Caught and logged this `HazelcastSerializationException `:

```
com.hazelcast.nio.serialization.HazelcastSerializationException: java.lang.ClassNotFoundException: com.***.CacheKey
        at com.hazelcast.internal.serialization.impl.defaultserializers.JavaDefaultSerializers$JavaSerializer.read(JavaDefaultSerializers.java:87)
        at com.hazelcast.internal.serialization.impl.defaultserializers.JavaDefaultSerializers$JavaSerializer.read(JavaDefaultSerializers.java:76)
        at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:44)
        at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:205)
        at com.hazelcast.map.impl.MapEntries.putAllToMap(MapEntries.java:113)
        at com.hazelcast.map.impl.proxy.MapProxySupport.lambda$submitToKeysInternal$3(MapProxySupport.java:1238)
        at com.hazelcast.map.impl.proxy.MapProxySupport$$Lambda$2058/0x0000000801225840.accept(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
        at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.ClassNotFoundException: com.***.CacheKey
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at com.hazelcast.internal.nio.ClassLoaderUtil.tryLoadClass(ClassLoaderUtil.java:287)
        at com.hazelcast.internal.nio.ClassLoaderUtil.loadClass(ClassLoaderUtil.java:251)
        at com.hazelcast.internal.nio.IOUtil$ClassLoaderAwareObjectInputStream.resolveClass(IOUtil.java:783)
        at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1995)
        at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1862)
        at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2169)
        at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1679)
        at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:493)
        at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:451)
        at com.hazelcast.internal.serialization.impl.defaultserializers.JavaDefaultSerializers$JavaSerializer.read(JavaDefaultSerializers.java:83)
        ... 14 more
```

The stack trace does not show a tomcat class loader being used to attempt to load the class.

The catch block, which calls IMap.contains on the same keys succeeds.

In a different IMap the keys are Strings, and in this case the IMap.executeOnKeys fails attempting to deserialize the values.
Again, the work done in the catch block (and other simple get calls from the IMap) succeed.

```
        final Set keysAsSet = (keys instanceof Set) ? (Set) keys : Collections3.copyOfSet(keys);
        try
        {
            return realCache.executeOnKeys(keysAsSet, RemoveEntryProcessor.getInstance());
        }
        catch(HazelcastSerializationException hse)
        {
            logSerializationIssue("removeAll", hse, keysAsSet);
            
            final Map<K, T> results = Collections3.newMapWithExpectedSize(keysAsSet.size());
            for (Object key : keysAsSet)
            {
                T value = realCache.remove(key);
                if (value != null)
                {
                    results.put((K) key, value);
                }
            }
            return results;
        }
```

**Comment by mmedenjak** [comment]
Thank you for the detailed report @bokken ! And nice to see you around again :) I'll see if I can get someone to take a look.

**Comment by JJRdec** [comment]
Hello! Did this ever get resolved, I'm seeing this on 4.2?
