### ISSUE TITLE
QueueSplitBrainProtectionReadTest element_splitBrainProtection[splitBrainProtectionType:READ]

### ISSUE THREAD

**Issue by lazerion** [hazelcast/hazelcast#17896]
- Fails on `Hazelcast-4.master-sonar`
- Fails on [Build #698 (Nov 24, 2020 9:17:00 PM)](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-4.master-sonar/698/testReport/junit/com.hazelcast.splitbrainprotection.queue/QueueSplitBrainProtectionReadTest/element_splitBrainProtection_splitBrainProtectionType_READ_/)
- Error
```
Queue is empty!
```
- Stacktrace
```
java.util.NoSuchElementException: Queue is empty!
	at com.hazelcast.collection.impl.queue.QueueProxyImpl.element(QueueProxyImpl.java:163)
	at com.hazelcast.splitbrainprotection.queue.QueueSplitBrainProtectionReadTest.element_splitBrainProtection(QueueSplitBrainProtectionReadTest.java:70)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
- Hiccups
```
Hiccups measured while running test 'element_splitBrainProtection[splitBrainProtectionType:READ](com.hazelcast.splitbrainprotection.queue.QueueSplitBrainProtectionReadTest):'
22:44:00, accumulated pauses: 314 ms, max pause: 257 ms, pauses over 1000 ms: 0
```
- kindly check, not recall failure on this one recently, I could not catch offending commit for below
```
Ensure that RestApiConfig configuration parsing doesn't overwrite (commit: 86ece7d) (detail)
Ensure that advanced network configuration parsing doesn't overwrite (commit: bbe23f8) (detail)
Exclude StaticLoggerBinder from sql jar (#17864) (commit: 6c71ca3) (detail)
Fix shade warnings during SQL module build (#17819) (commit: 27d9e1f) (detail)
```

**Comment by mmedenjak** [comment]
@ramizdundar can we close this one since we've added logging and wait until the next failure?

**Comment by ramizdundar** [comment]
@mmedenjak ok then I'm closing it. Hopefully queue sizes will be helpful identifying where the problem occurs next time.
