### ISSUE TITLE
SQL Query fails to execute a query when it does not have any entry locally

### ISSUE THREAD

**Issue by jerrinot** [hazelcast/hazelcast#17919]
When executing a SQL query then we are sampling IMap to infer a schema. This strategy fails when IMap has entries, but none of them is stored on a member creating a plan (and hence sampling the IMap)

This means this test is failing:
```java
public class SparseMapTest {
    @Test
    public void testWithClients() {
        var config = new Config();
        config.getMapConfig("myMap").setBackupCount(0);
        var m1 = Hazelcast.newHazelcastInstance(config);
        var m2 = Hazelcast.newHazelcastInstance(config);
        var c1 = HazelcastClient.newHazelcastClient();
        IMap<Integer, Integer> map = c1.getMap("myMap");
        map.set(0, 0);
        for (int i = 0; i < 1000; i++) {
            SqlResult rows = c1.getSql().execute("select * from myMap where __key = 0");
            assertTrue(rows.iterator().hasNext());
        }
    }
}
```
The test has a backup disabled so only a single member will contain the inserted entry. Clients execute SQL on a random member. When it selects the member without the entry then it fails with
```
com.hazelcast.sql.HazelcastSqlException: Cannot resolve IMap schema because it doesn't have entries on the local member: myMap
	at com.hazelcast.sql.impl.client.SqlClientService.handleResponseError(SqlClientService.java:220)
	at com.hazelcast.sql.impl.client.SqlClientService.execute(SqlClientService.java:100)
	at com.hazelcast.sql.SqlService.execute(SqlService.java:144)
	at info.jerrinot.sandbox.sparsemap.SparseMapTest.foo(SparseMapTest.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)
```

Obviously this issue does not affect just clients. It's similar when executing from a member too:
```
    @Test
    public void testWithMembers() {
        var config = new Config();
        config.getMapConfig("myMap").setBackupCount(0);
        var m1 = Hazelcast.newHazelcastInstance(config);
        var m2 = Hazelcast.newHazelcastInstance(config);
        IMap<Integer, Integer> map = m1.getMap("myMap");
        map.set(0, 0);
        assertTrue(m1.getSql().execute("select * from myMap").iterator().hasNext());
        assertTrue(m2.getSql().execute("select * from myMap").iterator().hasNext());
    }
```

**Comment by jerrinot** [comment]
related issue: https://github.com/hazelcast/hazelcast/issues/17883

**Comment by Holmistr** [comment]
Just making sure @devozerov knows about it and also putting myself as a watcher.

**Comment by mmedenjak** [comment]
Moving to backlog as I assume the only alternative is the `CREATE MAPPING` which we can have when/if we merge with jet SQL. cc @devozerov
