### ISSUE TITLE
Cannot start Hazelcast 4.1 on Windows 10

### ISSUE THREAD

**Issue by manish-in-java** [hazelcast/hazelcast#17979]
## Describe the bug

On Windows 10 Professional 64-bit version 20H2 build 19042.685.

Have 64-bit OpenJDK 11.0.2 from AdoptOpenJDK installed.

1. Downloaded the Hazelcast 4.1 ZIP file bundle from https://download.hazelcast.com/download.jsp?version=hazelcast-4.1&p=
2. Unzipped the bundle
3. Added `set JAVA_OPTS=-Djava.net.preferIPv4Stack=true` at the top of the file `start.bat`, since without this I was getting an error
4. Made no other change to any script or file, including `hazelcast.xml`
5. Started a command prompt window and changed to the folder where Hazelcast was unzipped
6. Tried starting Hazelcast by running `start.bat`

## Expected behavior

Hazelcast should start.

## Observed behavior

Hazelcast failed to start, with the following error stacktrace:

```
Dec 16, 2020 1:51:19 PM com.hazelcast.internal.config.AbstractConfigLocator
INFO: Loading 'hazelcast.xml' from the working directory.
Dec 16, 2020 1:51:20 PM com.hazelcast.system
INFO: [192.168.1.6]:5701 [dev] [4.1] Hazelcast 4.1 (20201104 - 2a1a477) starting at [192.168.1.6]:5701
Dec 16, 2020 1:51:20 PM com.hazelcast.spi.discovery.integration.DiscoveryService
INFO: [192.168.1.6]:5701 [dev] [4.1] No discovery strategy is applicable for auto-detection
Dec 16, 2020 1:51:20 PM com.hazelcast.instance.impl.Node
SEVERE: [192.168.1.6]:5701 [dev] [4.1] Address already in use: Cannot bind
java.net.BindException: Address already in use: Cannot bind
        at java.base/java.net.TwoStacksPlainDatagramSocketImpl.bind0(Native Method)
        at java.base/java.net.TwoStacksPlainDatagramSocketImpl.bind0(TwoStacksPlainDatagramSocketImpl.java:114)
        at java.base/java.net.AbstractPlainDatagramSocketImpl.bind(AbstractPlainDatagramSocketImpl.java:131)
        at java.base/java.net.TwoStacksPlainDatagramSocketImpl.bind(TwoStacksPlainDatagramSocketImpl.java:98)
        at java.base/java.net.DatagramSocket.bind(DatagramSocket.java:394)
        at com.hazelcast.internal.cluster.impl.MulticastService.createMulticastService(MulticastService.java:117)
        at com.hazelcast.instance.impl.Node.<init>(Node.java:272)
        at com.hazelcast.instance.impl.HazelcastInstanceImpl.createNode(HazelcastInstanceImpl.java:148)
        at com.hazelcast.instance.impl.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:117)
        at com.hazelcast.instance.impl.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:211)
        at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:190)
        at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:128)
        at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:91)
        at com.hazelcast.core.server.HazelcastMemberStarter.main(HazelcastMemberStarter.java:47)

Dec 16, 2020 1:51:20 PM com.hazelcast.instance.impl.Node
INFO: [192.168.1.6]:5701 [dev] [4.1] Using Multicast discovery
Dec 16, 2020 1:51:20 PM com.hazelcast.instance.impl.Node
SEVERE: [192.168.1.6]:5701 [dev] [4.1] Node creation failed
java.lang.NullPointerException
        at com.hazelcast.internal.cluster.impl.MulticastJoiner.<init>(MulticastJoiner.java:52)
        at com.hazelcast.instance.impl.Node.createJoiner(Node.java:829)
        at com.hazelcast.instance.impl.DefaultNodeContext.createJoiner(DefaultNodeContext.java:142)
        at com.hazelcast.instance.impl.Node.<init>(Node.java:273)
        at com.hazelcast.instance.impl.HazelcastInstanceImpl.createNode(HazelcastInstanceImpl.java:148)
        at com.hazelcast.instance.impl.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:117)
        at com.hazelcast.instance.impl.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:211)
        at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:190)
        at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:128)
        at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:91)
        at com.hazelcast.core.server.HazelcastMemberStarter.main(HazelcastMemberStarter.java:47)

Dec 16, 2020 1:51:20 PM com.hazelcast.instance.impl.Node
INFO: [192.168.1.6]:5701 [dev] [4.1] Shutting down connection manager...
Dec 16, 2020 1:51:20 PM com.hazelcast.instance.impl.Node
INFO: [192.168.1.6]:5701 [dev] [4.1] Shutting down node engine...
Dec 16, 2020 1:51:20 PM com.hazelcast.instance.impl.NodeExtension
INFO: [192.168.1.6]:5701 [dev] [4.1] Destroying node NodeExtension.
Exception in thread "main" java.lang.NullPointerException
        at com.hazelcast.internal.cluster.impl.MulticastJoiner.<init>(MulticastJoiner.java:52)
        at com.hazelcast.instance.impl.Node.createJoiner(Node.java:829)
        at com.hazelcast.instance.impl.DefaultNodeContext.createJoiner(DefaultNodeContext.java:142)
        at com.hazelcast.instance.impl.Node.<init>(Node.java:273)
        at com.hazelcast.instance.impl.HazelcastInstanceImpl.createNode(HazelcastInstanceImpl.java:148)
        at com.hazelcast.instance.impl.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:117)
        at com.hazelcast.instance.impl.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:211)
        at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:190)
        at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:128)
        at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:91)
        at com.hazelcast.core.server.HazelcastMemberStarter.main(HazelcastMemberStarter.java:47)
```

## Additional context

Have checked that neither the default server port 5701, nor the multicast port 54327 is in use by any process.

No other Hazelcast instance is running on the machine.

Rebooted the machine and tried running Hazelcast without any other application running, after ensuring that ports 5701 are 54327 are free, and got the same error.

If auto-discovery is disabled in `hazelcast.xml`, Hazelcast starts fine. This is further proof that ports 5701 and 54327 are not in use by any other process, and somehow Hazelcast is facing an internal deadlock on ports.

I am trying to start a 3-node cluster on a single machine, so I would like to have some mechanism for discovering other nodes. I have tried enabling multicast discovery, which fails with the same error (`address already in use`).

Have also tried using different ports such as 8001 or 12345 and faced the exact same error.

## More context

Downloaded 4.0.3 and faced a similar error with the exact same steps, although Hazelcast starts in standalone mode. Full startup logs below:

```
Dec 16, 2020 2:25:36 PM com.hazelcast.internal.config.AbstractConfigLocator
INFO: Loading 'hazelcast.xml' from the working directory.
Dec 16, 2020 2:25:37 PM com.hazelcast.instance.AddressPicker
INFO: [LOCAL] [dev] [4.0.3] Prefer IPv4 stack is true, prefer IPv6 addresses is false
Dec 16, 2020 2:25:37 PM com.hazelcast.instance.AddressPicker
INFO: [LOCAL] [dev] [4.0.3] Picked [192.168.1.6]:5701, using socket ServerSocket[addr=/0.0.0.0,localport=5701], bind any local is true
Dec 16, 2020 2:25:37 PM com.hazelcast.system
INFO: [192.168.1.6]:5701 [dev] [4.0.3] Hazelcast 4.0.3 (20200921 - 59ae831) starting at [192.168.1.6]:5701
Dec 16, 2020 2:25:37 PM com.hazelcast.system
INFO: [192.168.1.6]:5701 [dev] [4.0.3] Copyright (c) 2008-2020, Hazelcast, Inc. All Rights Reserved.
Dec 16, 2020 2:25:37 PM com.hazelcast.spi.impl.operationservice.impl.BackpressureRegulator
INFO: [192.168.1.6]:5701 [dev] [4.0.3] Backpressure is disabled
Dec 16, 2020 2:25:38 PM com.hazelcast.instance.impl.Node
SEVERE: [192.168.1.6]:5701 [dev] [4.0.3] Address already in use: Cannot bind
java.net.BindException: Address already in use: Cannot bind
        at java.base/java.net.TwoStacksPlainDatagramSocketImpl.bind0(Native Method)
        at java.base/java.net.TwoStacksPlainDatagramSocketImpl.bind0(TwoStacksPlainDatagramSocketImpl.java:114)
        at java.base/java.net.AbstractPlainDatagramSocketImpl.bind(AbstractPlainDatagramSocketImpl.java:131)
        at java.base/java.net.TwoStacksPlainDatagramSocketImpl.bind(TwoStacksPlainDatagramSocketImpl.java:98)
        at java.base/java.net.DatagramSocket.bind(DatagramSocket.java:394)
        at com.hazelcast.internal.cluster.impl.MulticastService.createMulticastService(MulticastService.java:117)
        at com.hazelcast.instance.impl.Node.<init>(Node.java:271)
        at com.hazelcast.instance.impl.HazelcastInstanceImpl.createNode(HazelcastInstanceImpl.java:147)
        at com.hazelcast.instance.impl.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:116)
        at com.hazelcast.instance.impl.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:211)
        at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:190)
        at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:128)
        at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:91)
        at com.hazelcast.core.server.HazelcastMemberStarter.main(HazelcastMemberStarter.java:46)

Dec 16, 2020 2:25:38 PM com.hazelcast.cp.CPSubsystem
WARNING: [192.168.1.6]:5701 [dev] [4.0.3] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
Dec 16, 2020 2:25:38 PM com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl
INFO: [192.168.1.6]:5701 [dev] [4.0.3] Starting 8 partition threads and 5 generic threads (1 dedicated for priority tasks)
Dec 16, 2020 2:25:38 PM com.hazelcast.internal.diagnostics.Diagnostics
INFO: [192.168.1.6]:5701 [dev] [4.0.3] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
Dec 16, 2020 2:25:38 PM com.hazelcast.core.LifecycleService
INFO: [192.168.1.6]:5701 [dev] [4.0.3] [192.168.1.6]:5701 is STARTING
Dec 16, 2020 2:25:38 PM com.hazelcast.instance.impl.Node
WARNING: [192.168.1.6]:5701 [dev] [4.0.3] No join method is enabled! Starting standalone.
Dec 16, 2020 2:25:38 PM com.hazelcast.core.LifecycleService
INFO: [192.168.1.6]:5701 [dev] [4.0.3] [192.168.1.6]:5701 is STARTED
```

**Comment by mmedenjak** [comment]
Thank you for the report @manish-in-java ! @kwart can you take a look?

**Comment by thake** [comment]
A collegue of mine experienced the same problem. He was running Docker Desktop for Windows on Hyper-V. I think this maybe related to this: https://pomeroy.me/2020/09/solved-windows-10-forbidden-port-bind/ 

@manish-in-java Are you also running Docker Desktop on Hyper-V?

**Comment by manish-in-java** [comment]
Hi @thake, no I am not running Docker. I do not have it installed. Nor am I using Hyper-V.

**Comment by kwart** [comment]
I can reproduce the issue on Windows when I disconnect the network cable (and wifi is disabled too).
[hazelcast.log](https://github.com/hazelcast/hazelcast/files/5932320/hazelcast.log)

**Comment by kwart** [comment]
@manish-in-java My finding doesn't explain why you have the bind-address occupied. Could you run the following commands (in cmd as Administrator) and share their output?

```batch
netstat -p udp -a -b
netstat -p udpv6 -a -b
```

**Comment by mmedenjak** [comment]
@manish-in-java any updates on the above? Can you try it?

**Comment by kwart** [comment]
It's getting interesting. Neither was I able to reproduce it in Windows 10 on my second machine, nor on a [testing Windows 10 virtual machine](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/).

The problem is in native JDK part - namely in `NET_SetSockOpt` call which returns error value.
https://github.com/openjdk/jdk11u-dev/blob/jdk-11.0.11%2B2/src/java.base/windows/native/libnet/TwoStacksPlainDatagramSocketImpl.c#L2260-L2267

Internally it calls `setsocketopt()` function and handles (ignores) some error types.
https://github.com/openjdk/jdk11u-dev/blob/jdk-11.0.11%2B2/src/java.base/windows/native/libnet/net_util_md.c#L312-L359

Unfortunatelly, the error which we see is not handled. And the return value is lost (i.e. it's not propagated to the `SocketException`) - so we can't simply check what went wrong.

From this Q&A on StackOverflow it seems it could be related to binding the `MulticastSocket` to a wildcard address.
https://stackoverflow.com/questions/583950/multicastsocket-not-responding-after-failure

We could try a fallback which would pick a network interfaces explicitly.

**Comment by pmverma** [comment]
I had a similar issue where the multicast UDP port `54327` seems to be used by hazelcast even if multicast was disabled.
I had to use a non-reserve port to make it work.

As mentioned in one of above comment, you can use following command to find reserved port.

`netsh interface ipv4 show excludedportrange protocol=udp`

Just make sure to use PowerShell or WindowsTerminal because cmd was not working for me.
