### ISSUE TITLE
Multiple TenantControlTest failures [HZ-1843]

### ISSUE THREAD

**Issue by ghost** [hazelcast/hazelcast#17990]
- Possible commit `Adds tenant control (commit: 02b2b45) (detail)`
- Fails on `Hazelcast-4.master-Solaris-OracleJDK8`
- Fails on [Build #255 (Dec 19, 2020 7:20:46 PM)](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-4.master-Solaris-OracleJDK8/com.hazelcast$hazelcast/255/#showFailuresLink)
- Sample Error
```
expected:<1> but was:<0>
```
- Sample Stacktrace
```
java.lang.AssertionError: expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at com.hazelcast.spi.tenantcontrol.TenantControlTest.basicSetTest(TenantControlTest.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```
- Kindly check

**Comment by lazerion** [comment]
It looks also need update on code-samples repo for tenant updates. ⚠️ 
```
00:03:44.608 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project tenant-control: Compilation failure: Compilation failure: 
00:03:44.608 [ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-4.master-code-samples-OracleJDK8/hazelcast-code-samples/spi/tenant-control/src/main/java/multitenant/MultiTenantControl.java:[9,8] multitenant.MultiTenantControl is not abstract and does not override abstract method clearThreadContext() in com.hazelcast.spi.tenantcontrol.TenantControl
00:03:44.608 [ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-4.master-code-samples-OracleJDK8/hazelcast-code-samples/spi/tenant-control/src/main/java/multitenant/MultiTenantControl.java:[17,5] method does not override or implement a method from a supertype
00:03:44.608 [ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-4.master-code-samples-OracleJDK8/hazelcast-code-samples/spi/tenant-control/src/main/java/multitenant/MultiTenantControl.java:[25,16] incompatible types: multitenant.TenantCloseable cannot be converted to com.hazelcast.spi.tenantcontrol.TenantControl.Closeable
00:03:44.608 [ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-4.master-code-samples-OracleJDK8/hazelcast-code-samples/spi/tenant-control/src/main/java/multitenant/MultiTenantControl.java:[28,5] method does not override or implement a method from a supertype
00:03:44.608 [ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-4.master-code-samples-OracleJDK8/hazelcast-code-samples/spi/tenant-control/src/main/java/multitenant/MultiTenantControlFactory.java:[7,8] multitenant.MultiTenantControlFactory is not abstract and does not override abstract method isClassesAlwaysAvailable() in com.hazelcast.spi.tenantcontrol.TenantControlFactory
00:03:44.608 [ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-4.master-code-samples-OracleJDK8/hazelcast-code-samples/spi/tenant-control/src/main/java/multitenant/MultiTenantControlFactory.java:[9,5] method does not override or implement a method from a supertype
00:03:44.608 [ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-4.master-code-samples-OracleJDK8/hazelcast-code-samples/spi/tenant-control/src/main/java/multitenant/MultiTenantControlFactory.java:[11,33] cannot find symbol
```

**Comment by mmedenjak** [comment]
Related: https://github.com/hazelcast/hazelcast-code-samples/issues/468

**Comment by lprimak** [comment]
I can see this test `TenantControlTest.basicSetTest()` failing on my local machine intermittently, roughly one out of 5 times

**Comment by lprimak** [comment]
samples PR hazelcast/hazelcast-code-samples#469

**Comment by lprimak** [comment]
Working on a PR that fixes the test issue... it's not waiting for async distributed object destroy to happen before performing checks

**Comment by PavloBida** [comment]
Hazelcast-4.master-code-samples-OracleJDK8 keeps failing with Tenant related compilation errors. 
[14-Jan-2021 09:26](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-4.master-code-samples-OracleJDK8/)

**Comment by lprimak** [comment]
https://github.com/hazelcast/hazelcast-code-samples/pull/469 Fixes this

**Comment by lprimak** [comment]
@PavloBida Please close this issue. This issue is already fixed by Hazelcast IMDG tests.
There is already an open issue for the code samples that's open: https://github.com/hazelcast/hazelcast-code-samples/issues/468
thank you

**Comment by vbekiaris** [comment]
Fixed by https://github.com/hazelcast/hazelcast-code-samples/issues/468

**Comment by blazember** [comment]
**Build:** http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/3861/

**Error Message**
```
expected:<3> but was:<2>
```
**Stacktrace**
```
java.lang.AssertionError: expected:<3> but was:<2>
	at com.hazelcast.spi.tenantcontrol.TenantControlTest.testTenantControl_executionBeforeAfterOps(TenantControlTest.java:147)
```
No big hiccups.

**Comment by lprimak** [comment]
@blazember how long did that test take to fail? I can log into jenkins :)

**Comment by lprimak** [comment]
I can see this test failing under rare circumstances. The test is invalid

**Comment by lprimak** [comment]
This was not quite the same issue.
Only one of the tests had a stability issue and I fixed it in the above PR.
Thanks @blazember

**Comment by lprimak** [comment]
@lprimak

**Comment by sumnerib** [comment]
Failed again on _master_ with RedHatJDK11: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-RedHatJDK11/56/testReport/junit/com.hazelcast.spi.tenantcontrol/TenantControlTest/testTenantControl_executionBeforeAfterOps_tenantControl__true_/

**Comment by lprimak** [comment]
@sumnerib can you paste some detail (i.e. which test, how long it ran etc) here?
I don't have access to Jenkins 
@vbekiaris

**Comment by sumnerib** [comment]
Hi @lprimak, here are the details from Jenkins:

`com.hazelcast.spi.tenantcontrol.TenantControlTest.testTenantControl_executionBeforeAfterOps[tenantControl: true]` (took 10s)

<details><summary>Stacktrace</summary>

```
java.lang.AssertionError: expected:<4> but was:<3>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at com.hazelcast.spi.tenantcontrol.TenantControlTest.testTenantControl_executionBeforeAfterOps(TenantControlTest.java:146)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

</details>

<details><summary>Stdout</summary>

```
Finished Running Test: basicQueueTest[tenantControl: true] in 0.224 seconds.
Started Running Test: testTenantControl_executionBeforeAfterOps[tenantControl: true]
18:23:35,003  INFO |testTenantControl_executionBeforeAfterOps[tenantControl: true]| - [MetricsConfigHelper] testTenantControl_executionBeforeAfterOps - [LOCAL] [dev] [5.3.0-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
18:23:35,005  INFO |testTenantControl_executionBeforeAfterOps[tenantControl: true]| - [logo] testTenantControl_executionBeforeAfterOps - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
18:23:35,005  INFO |testTenantControl_executionBeforeAfterOps[tenantControl: true]| - [system] testTenantControl_executionBeforeAfterOps - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Copyright (c) 2008-2022, Hazelcast, Inc. All Rights Reserved.
18:23:35,005  INFO |testTenantControl_executionBeforeAfterOps[tenantControl: true]| - [system] testTenantControl_executionBeforeAfterOps - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Hazelcast Platform 5.3.0-SNAPSHOT (20221102 - 433b97b) starting at [127.0.0.1]:5701
18:23:35,005  INFO |testTenantControl_executionBeforeAfterOps[tenantControl: true]| - [system] testTenantControl_executionBeforeAfterOps - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Cluster name: dev
18:23:35,005  INFO |testTenantControl_executionBeforeAfterOps[tenantControl: true]| - [system] testTenantControl_executionBeforeAfterOps - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed. For more information, see the documentation for Integrity Checker.
18:23:35,005  INFO |testTenantControl_executionBeforeAfterOps[tenantControl: true]| - [system] testTenantControl_executionBeforeAfterOps - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Jet is enabled
18:23:35,012  INFO |testTenantControl_executionBeforeAfterOps[tenantControl: true]| - [MetricsConfigHelper] testTenantControl_executionBeforeAfterOps - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
18:23:35,020  WARN |testTenantControl_executionBeforeAfterOps[tenantControl: true]| - [CPSubsystem] testTenantControl_executionBeforeAfterOps - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
18:23:35,028  INFO |testTenantControl_executionBeforeAfterOps[tenantControl: true]| - [JetServiceBackend] testTenantControl_executionBeforeAfterOps - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Setting number of cooperative threads and default parallelism to 2
18:23:35,040  INFO |testTenantControl_executionBeforeAfterOps[tenantControl: true]| - [Diagnostics] testTenantControl_executionBeforeAfterOps - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
18:23:35,041  INFO |testTenantControl_executionBeforeAfterOps[tenantControl: true]| - [LifecycleService] testTenantControl_executionBeforeAfterOps - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] [127.0.0.1]:5701 is STARTING
18:23:35,041  INFO |testTenantControl_executionBeforeAfterOps[tenantControl: true]| - [ClusterService] testTenantControl_executionBeforeAfterOps - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] 

Members {size:1, ver:1} [
	Member [127.0.0.1]:5701 - 8225b9f6-9a9d-4a8c-b11e-77f3a186da16 this
]

18:23:35,041  INFO |testTenantControl_executionBeforeAfterOps[tenantControl: true]| - [JobCoordinationService] testTenantControl_executionBeforeAfterOps - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Jet started scanning for jobs
18:23:35,041  INFO |testTenantControl_executionBeforeAfterOps[tenantControl: true]| - [LifecycleService] testTenantControl_executionBeforeAfterOps - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] [127.0.0.1]:5701 is STARTED
18:23:35,042 DEBUG |testTenantControl_executionBeforeAfterOps[tenantControl: true]| - [JobCoordinationService] hz.naughty_darwin.cached.thread-1 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
18:23:35,042  INFO |testTenantControl_executionBeforeAfterOps[tenantControl: true]| - [CacheService] testTenantControl_executionBeforeAfterOps - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Added cache config: CacheConfig{name='2446862d-cdbf-433d-a279-baa464ddcbf8', managerPrefix='/hz/', inMemoryFormat=BINARY, backupCount=1, hotRestart=HotRestartConfig{enabled=false, fsync=false}, dataPersistenceConfig=DataPersistenceConfig{enabled=false, fsync=false}, wanReplicationRef=null, merkleTreeConfig=MerkleTreeConfig{enabled=null, depth=10}}
18:23:35,042  INFO |testTenantControl_executionBeforeAfterOps[tenantControl: true]| - [PartitionStateManager] testTenantControl_executionBeforeAfterOps - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Initializing cluster partition table arrangement...
18:23:35,043  INFO |testTenantControl_executionBeforeAfterOps[tenantControl: true]| - [CacheService] testTenantControl_executionBeforeAfterOps - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Removed cache config: CacheConfig{name='2446862d-cdbf-433d-a279-baa464ddcbf8', managerPrefix='/hz/', inMemoryFormat=BINARY, backupCount=1, hotRestart=HotRestartConfig{enabled=false, fsync=false}, dataPersistenceConfig=DataPersistenceConfig{enabled=false, fsync=false}, wanReplicationRef=null, merkleTreeConfig=MerkleTreeConfig{enabled=null, depth=10}}
18:23:35,877 DEBUG |testTenantControl_executionBeforeAfterOps[tenantControl: true]| - [JobRepository] hz.naughty_darwin.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Job cleanup took 0ms
18:23:35,917  INFO |testTenantControl_executionBeforeAfterOps[tenantControl: true]| - [LifecycleService] main - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
18:23:35,917  WARN |testTenantControl_executionBeforeAfterOps[tenantControl: true]| - [Node] main - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Terminating forcefully...
18:23:35,917  INFO |testTenantControl_executionBeforeAfterOps[tenantControl: true]| - [Node] main - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Shutting down connection manager...
18:23:35,917  INFO |testTenantControl_executionBeforeAfterOps[tenantControl: true]| - [Node] main - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Shutting down node engine...
18:23:35,919  INFO |testTenantControl_executionBeforeAfterOps[tenantControl: true]| - [NodeExtension] main - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Destroying node NodeExtension.
18:23:35,920  INFO |testTenantControl_executionBeforeAfterOps[tenantControl: true]| - [Node] main - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Hazelcast Shutdown is completed in 3 ms.
18:23:35,920  INFO |testTenantControl_executionBeforeAfterOps[tenantControl: true]| - [LifecycleService] main - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
BuildInfo right after testTenantControl_executionBeforeAfterOps[tenantControl: true](com.hazelcast.spi.tenantcontrol.TenantControlTest): BuildInfo{version='5.3.0-SNAPSHOT', build='20221102', buildNumber=20221102, revision=433b97b, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'testTenantControl_executionBeforeAfterOps[tenantControl: true](com.hazelcast.spi.tenantcontrol.TenantControlTest):'
18:23:35, accumulated pauses: 828 ms, max pause: 825 ms, pauses over 1000 ms: 0


No metrics recorded during the test
```

</details>

Let me know if you need anything else, and thanks for your help!

**Comment by lprimak** [comment]
@sumnerib I tiny PR done for this - thanks

**Comment by Patras3** [comment]
Failed again on _master_ with ZingJDK11: https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK11/2/testReport/junit/com.hazelcast.spi.tenantcontrol/TenantControlTest/testTenantControl_executionBeforeAfterOps_tenantControl__true_/

**Comment by Patras3** [comment]
Reopening as issue occurred again on: _5.2.z_ (commit 6f7c6d83f5c58d80053c32d0dd97a0516a80970d)
with zing-11: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-ZingJDK11/3/testReport/junit/com.hazelcast.spi.tenantcontrol/TenantControlTest/testTenantControl_executionBeforeAfterOps_tenantControl__true_/
<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: expected:<4> but was:<3>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at com.hazelcast.spi.tenantcontrol.TenantControlTest.testTenantControl_executionBeforeAfterOps(TenantControlTest.java:146)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:887)

```
</details>


<details><summary>Standard output:</summary>

```
Finished Running Test: testDestroyEventContext_destroyRemovesTenantControl[tenantControl: true] in 0.284 seconds.
Started Running Test: testTenantControl_executionBeforeAfterOps[tenantControl: true]
21:02:20,456  INFO |testTenantControl_executionBeforeAfterOps[tenantControl: true]| - [MetricsConfigHelper] testTenantControl_executionBeforeAfterOps - [LOCAL] [dev] [5.2.2-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
21:02:20,473  INFO |testTenantControl_executionBeforeAfterOps[tenantControl: true]| - [logo] testTenantControl_executionBeforeAfterOps - [127.0.0.1]:5701 [dev] [5.2.2-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
21:02:20,473  INFO |testTenantControl_executionBeforeAfterOps[tenantControl: true]| - [system] testTenantControl_executionBeforeAfterOps - [127.0.0.1]:5701 [dev] [5.2.2-SNAPSHOT] Copyright (c) 2008-2022, Hazelcast, Inc. All Rights Reserved.
21:02:20,473  INFO |testTenantControl_executionBeforeAfterOps[tenantControl: true]| - [system] testTenantControl_executionBeforeAfterOps - [127.0.0.1]:5701 [dev] [5.2.2-SNAPSHOT] Hazelcast Platform 5.2.2-SNAPSHOT (20221216 - 6f7c6d8) starting at [127.0.0.1]:5701
21:02:20,473  INFO |testTenantControl_executionBeforeAfterOps[tenantControl: true]| - [system] testTenantControl_executionBeforeAfterOps - [127.0.0.1]:5701 [dev] [5.2.2-SNAPSHOT] Cluster name: dev
21:02:20,473  INFO |testTenantControl_executionBeforeAfterOps[tenantControl: true]| - [system] testTenantControl_executionBeforeAfterOps - [127.0.0.1]:5701 [dev] [5.2.2-SNAPSHOT] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed. For more information, see the documentation for Integrity Checker.
21:02:20,473  INFO |testTenantControl_executionBeforeAfterOps[tenantControl: true]| - [system] testTenantControl_executionBeforeAfterOps - [127.0.0.1]:5701 [dev] [5.2.2-SNAPSHOT] Jet is enabled
21:02:20,579  INFO |testTenantControl_executionBeforeAfterOps[tenantControl: true]| - [MetricsConfigHelper] testTenantControl_executionBeforeAfterOps - [127.0.0.1]:5701 [dev] [5.2.2-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
21:02:20,601  WARN |testTenantControl_executionBeforeAfterOps[tenantControl: true]| - [CPSubsystem] testTenantControl_executionBeforeAfterOps - [127.0.0.1]:5701 [dev] [5.2.2-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
21:02:20,603  INFO |testTenantControl_executionBeforeAfterOps[tenantControl: true]| - [JetServiceBackend] testTenantControl_executionBeforeAfterOps - [127.0.0.1]:5701 [dev] [5.2.2-SNAPSHOT] Setting number of cooperative threads and default parallelism to 2
21:02:20,604  INFO |testTenantControl_executionBeforeAfterOps[tenantControl: true]| - [Diagnostics] testTenantControl_executionBeforeAfterOps - [127.0.0.1]:5701 [dev] [5.2.2-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
21:02:20,604  INFO |testTenantControl_executionBeforeAfterOps[tenantControl: true]| - [LifecycleService] testTenantControl_executionBeforeAfterOps - [127.0.0.1]:5701 [dev] [5.2.2-SNAPSHOT] [127.0.0.1]:5701 is STARTING
21:02:20,604  INFO |testTenantControl_executionBeforeAfterOps[tenantControl: true]| - [ClusterService] testTenantControl_executionBeforeAfterOps - [127.0.0.1]:5701 [dev] [5.2.2-SNAPSHOT] 

Members {size:1, ver:1} [
	Member [127.0.0.1]:5701 - 26a2fb67-8406-42b7-a833-cd68f4ccf36a this
]

21:02:20,604  INFO |testTenantControl_executionBeforeAfterOps[tenantControl: true]| - [JobCoordinationService] testTenantControl_executionBeforeAfterOps - [127.0.0.1]:5701 [dev] [5.2.2-SNAPSHOT] Jet started scanning for jobs
21:02:20,604  INFO |testTenantControl_executionBeforeAfterOps[tenantControl: true]| - [LifecycleService] testTenantControl_executionBeforeAfterOps - [127.0.0.1]:5701 [dev] [5.2.2-SNAPSHOT] [127.0.0.1]:5701 is STARTED
21:02:20,605  INFO |testTenantControl_executionBeforeAfterOps[tenantControl: true]| - [CacheService] testTenantControl_executionBeforeAfterOps - [127.0.0.1]:5701 [dev] [5.2.2-SNAPSHOT] Added cache config: CacheConfig{name='7b727ce0-0cf6-4d03-a9c3-921b9d07cfb6', managerPrefix='/hz/', inMemoryFormat=BINARY, backupCount=1, hotRestart=HotRestartConfig{enabled=false, fsync=false}, dataPersistenceConfig=DataPersistenceConfig{enabled=false, fsync=false}, wanReplicationRef=null, merkleTreeConfig=MerkleTreeConfig{enabled=null, depth=10}}
21:02:20,605  INFO |testTenantControl_executionBeforeAfterOps[tenantControl: true]| - [PartitionStateManager] testTenantControl_executionBeforeAfterOps - [127.0.0.1]:5701 [dev] [5.2.2-SNAPSHOT] Initializing cluster partition table arrangement...
21:02:20,606 DEBUG |testTenantControl_executionBeforeAfterOps[tenantControl: true]| - [JobRepository] hz.xenodochial_brahmagupta.cached.thread-1 - [127.0.0.1]:5701 [dev] [5.2.2-SNAPSHOT] Job cleanup took 0ms
21:02:20,609  INFO |testTenantControl_executionBeforeAfterOps[tenantControl: true]| - [CacheService] testTenantControl_executionBeforeAfterOps - [127.0.0.1]:5701 [dev] [5.2.2-SNAPSHOT] Removed cache config: CacheConfig{name='7b727ce0-0cf6-4d03-a9c3-921b9d07cfb6', managerPrefix='/hz/', inMemoryFormat=BINARY, backupCount=1, hotRestart=HotRestartConfig{enabled=false, fsync=false}, dataPersistenceConfig=DataPersistenceConfig{enabled=false, fsync=false}, wanReplicationRef=null, merkleTreeConfig=MerkleTreeConfig{enabled=null, depth=10}}
21:02:20,639  INFO |testTenantControl_executionBeforeAfterOps[tenantControl: true]| - [LifecycleService] main - [127.0.0.1]:5701 [dev] [5.2.2-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
21:02:20,639  WARN |testTenantControl_executionBeforeAfterOps[tenantControl: true]| - [Node] main - [127.0.0.1]:5701 [dev] [5.2.2-SNAPSHOT] Terminating forcefully...
21:02:20,639  INFO |testTenantControl_executionBeforeAfterOps[tenantControl: true]| - [Node] main - [127.0.0.1]:5701 [dev] [5.2.2-SNAPSHOT] Shutting down connection manager...
21:02:20,639  INFO |testTenantControl_executionBeforeAfterOps[tenantControl: true]| - [Node] main - [127.0.0.1]:5701 [dev] [5.2.2-SNAPSHOT] Shutting down node engine...
21:02:20,641  INFO |testTenantControl_executionBeforeAfterOps[tenantControl: true]| - [NodeExtension] main - [127.0.0.1]:5701 [dev] [5.2.2-SNAPSHOT] Destroying node NodeExtension.
21:02:20,641  INFO |testTenantControl_executionBeforeAfterOps[tenantControl: true]| - [Node] main - [127.0.0.1]:5701 [dev] [5.2.2-SNAPSHOT] Hazelcast Shutdown is completed in 2 ms.
21:02:20,641  INFO |testTenantControl_executionBeforeAfterOps[tenantControl: true]| - [LifecycleService] main - [127.0.0.1]:5701 [dev] [5.2.2-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
BuildInfo right after testTenantControl_executionBeforeAfterOps[tenantControl: true](com.hazelcast.spi.tenantcontrol.TenantControlTest): BuildInfo{version='5.2.2-SNAPSHOT', build='20221216', buildNumber=20221216, revision=6f7c6d8, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'testTenantControl_executionBeforeAfterOps[tenantControl: true](com.hazelcast.spi.tenantcontrol.TenantControlTest):'
21:02:20, accumulated pauses: 619 ms, max pause: 15 ms, pauses over 1000 ms: 0


No metrics recorded during the test

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-5.maintenance-ZingJDK11/3/

We need backports to 5.2.z I think.
