### ISSUE TITLE
Hazelcast doesn't work with Sping Boot 2.4.1

### ISSUE THREAD

**Issue by baphuc1998** [hazelcast/hazelcast#18027]
**Describe the bug**
I used Hazelcast with Spring Boot 2.2.2 very well. Then I want to change my Spring Boot version to 2.4.1. But it seems that Hazelcast no longer works as well as it did before.

**Expected behavior**
Use Hazelcast in spring boot 2.4.1

**To Reproduce**

1. Use xml file
2. Add classpath in application.properties
3. Run the project

**Additional context**
Spring Boot 2.4.1
Hazelcast 3.12

hazelcast.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<hazelcast xmlns="http://www.hazelcast.com/schema/config"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.hazelcast.com/schema/config
           http://www.hazelcast.com/schema/config/hazelcast-config-3.12.xsd">
    <group>
        <name>app-template-sourcecode-api-mongo</name>
    </group>
    <management-center enabled="false">http://localhost:8080/hazelcast-mancenter</management-center>
    <network>
        <port auto-increment="true" port-count="10">5701</port>
        <outbound-ports>
            <!--
            Allowed port range when connecting to other nodes.
            0 or * means use system provided port.
            -->
            <ports>0</ports>
        </outbound-ports>
        <join>
            <multicast enabled="false">
                <multicast-group>224.2.2.3</multicast-group>
                <multicast-port>54327</multicast-port>
            </multicast>
            
            <tcp-ip enabled="true">
                <member>127.0.0.1</member>
            </tcp-ip> 
            <kubernetes enabled="false">
                <namespace>development</namespace>
                <service-name>app-api-fileman</service-name>
            </kubernetes>     
        </join>
    </network>
</hazelcast>

```
application.properties
```
spring.cache.type=hazelcast
spring.hazelcast.config=classpath:hazelcast.xml
spring.session.store-type=HAZELCAST
```
Error logs
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hazelcastInstance' defined in class path resource [org/springframework/boot/autoconfigure/hazelcast/HazelcastServerConfiguration$HazelcastServerConfigFileConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.hazelcast.core.HazelcastInstance]: Factory method 'hazelcastInstance' threw exception; nested exception is com.hazelcast.config.InvalidConfigurationException: cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://www.hazelcast.com/schema/config":group}'. One of '{"http://www.hazelcast.com/schema/config":import, "http://www.hazelcast.com/schema/config":config-replacers, "http://www.hazelcast.com/schema/config":cluster-name, "http://www.hazelcast.com/schema/config":license-key, "http://www.hazelcast.com/schema/config":instance-name, "http://www.hazelcast.com/schema/config":management-center, "http://www.hazelcast.com/schema/config":properties, "http://www.hazelcast.com/schema/config":wan-replication, "http://www.hazelcast.com/schema/config":network, "http://www.hazelcast.com/schema/config":partition-group, "http://www.hazelcast.com/schema/config":executor-service, "http://www.hazelcast.com/schema/config":durable-executor-service, "http://www.hazelcast.com/schema/config":scheduled-executor-service, "http://www.hazelcast.com/schema/config":queue, "http://www.hazelcast.com/schema/config":map, "http://www.hazelcast.com/schema/config":multimap, "http://www.hazelcast.com/schema/config":replicatedmap, "http://www.hazelcast.com/schema/config":cache, "http://www.hazelcast.com/schema/config":list, "http://www.hazelcast.com/schema/config":set, "http://www.hazelcast.com/schema/config":topic, "http://www.hazelcast.com/schema/config":reliable-topic, "http://www.hazelcast.com/schema/config":ringbuffer, "http://www.hazelcast.com/schema/config":listeners, "http://www.hazelcast.com/schema/config":serialization, "http://www.hazelcast.com/schema/config":native-memory, "http://www.hazelcast.com/schema/config":security, "http://www.hazelcast.com/schema/config":member-attributes, "http://www.hazelcast.com/schema/config":split-brain-protection, "http://www.hazelcast.com/schema/config":lite-member, "http://www.hazelcast.com/schema/config":hot-restart-persistence, "http://www.hazelcast.com/schema/config":user-code-deployment, "http://www.hazelcast.com/schema/config":cardinality-estimator, "http://www.hazelcast.com/schema/config":flake-id-generator, "http://www.hazelcast.com/schema/config":crdt-replication, "http://www.hazelcast.com/schema/config":pn-counter, "http://www.hazelcast.com/schema/config":advanced-network, "http://www.hazelcast.com/schema/config":cp-subsystem, "http://www.hazelcast.com/schema/config":metrics}' is expected.
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:658) ~[spring-beans-5.3.2.jar:5.3.2]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:638) ~[spring-beans-5.3.2.jar:5.3.2]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1336) ~[spring-beans-5.3.2.jar:5.3.2]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1179) ~[spring-beans-5.3.2.jar:5.3.2]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:571) ~[spring-beans-5.3.2.jar:5.3.2]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:531) ~[spring-beans-5.3.2.jar:5.3.2]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.2.jar:5.3.2]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.2.jar:5.3.2]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.2.jar:5.3.2]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.2.jar:5.3.2]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944) ~[spring-beans-5.3.2.jar:5.3.2]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:923) ~[spring-context-5.3.2.jar:5.3.2]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:588) ~[spring-context-5.3.2.jar:5.3.2]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144) ~[spring-boot-2.4.1.jar:2.4.1]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:767) ~[spring-boot-2.4.1.jar:2.4.1]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759) ~[spring-boot-2.4.1.jar:2.4.1]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:426) ~[spring-boot-2.4.1.jar:2.4.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:326) ~[spring-boot-2.4.1.jar:2.4.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1309) ~[spring-boot-2.4.1.jar:2.4.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1298) ~[spring-boot-2.4.1.jar:2.4.1]
	at vn.vnpt.digo.Application.main(Application.java:13) ~[main/:na]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.hazelcast.core.HazelcastInstance]: Factory method 'hazelcastInstance' threw exception; nested exception is com.hazelcast.config.InvalidConfigurationException: cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://www.hazelcast.com/schema/config":group}'. One of '{"http://www.hazelcast.com/schema/config":import, "http://www.hazelcast.com/schema/config":config-replacers, "http://www.hazelcast.com/schema/config":cluster-name, "http://www.hazelcast.com/schema/config":license-key, "http://www.hazelcast.com/schema/config":instance-name, "http://www.hazelcast.com/schema/config":management-center, "http://www.hazelcast.com/schema/config":properties, "http://www.hazelcast.com/schema/config":wan-replication, "http://www.hazelcast.com/schema/config":network, "http://www.hazelcast.com/schema/config":partition-group, "http://www.hazelcast.com/schema/config":executor-service, "http://www.hazelcast.com/schema/config":durable-executor-service, "http://www.hazelcast.com/schema/config":scheduled-executor-service, "http://www.hazelcast.com/schema/config":queue, "http://www.hazelcast.com/schema/config":map, "http://www.hazelcast.com/schema/config":multimap, "http://www.hazelcast.com/schema/config":replicatedmap, "http://www.hazelcast.com/schema/config":cache, "http://www.hazelcast.com/schema/config":list, "http://www.hazelcast.com/schema/config":set, "http://www.hazelcast.com/schema/config":topic, "http://www.hazelcast.com/schema/config":reliable-topic, "http://www.hazelcast.com/schema/config":ringbuffer, "http://www.hazelcast.com/schema/config":listeners, "http://www.hazelcast.com/schema/config":serialization, "http://www.hazelcast.com/schema/config":native-memory, "http://www.hazelcast.com/schema/config":security, "http://www.hazelcast.com/schema/config":member-attributes, "http://www.hazelcast.com/schema/config":split-brain-protection, "http://www.hazelcast.com/schema/config":lite-member, "http://www.hazelcast.com/schema/config":hot-restart-persistence, "http://www.hazelcast.com/schema/config":user-code-deployment, "http://www.hazelcast.com/schema/config":cardinality-estimator, "http://www.hazelcast.com/schema/config":flake-id-generator, "http://www.hazelcast.com/schema/config":crdt-replication, "http://www.hazelcast.com/schema/config":pn-counter, "http://www.hazelcast.com/schema/config":advanced-network, "http://www.hazelcast.com/schema/config":cp-subsystem, "http://www.hazelcast.com/schema/config":metrics}' is expected.
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.3.2.jar:5.3.2]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653) ~[spring-beans-5.3.2.jar:5.3.2]
	... 20 common frames omitted
Caused by: com.hazelcast.config.InvalidConfigurationException: cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://www.hazelcast.com/schema/config":group}'. One of '{"http://www.hazelcast.com/schema/config":import, "http://www.hazelcast.com/schema/config":config-replacers, "http://www.hazelcast.com/schema/config":cluster-name, "http://www.hazelcast.com/schema/config":license-key, "http://www.hazelcast.com/schema/config":instance-name, "http://www.hazelcast.com/schema/config":management-center, "http://www.hazelcast.com/schema/config":properties, "http://www.hazelcast.com/schema/config":wan-replication, "http://www.hazelcast.com/schema/config":network, "http://www.hazelcast.com/schema/config":partition-group, "http://www.hazelcast.com/schema/config":executor-service, "http://www.hazelcast.com/schema/config":durable-executor-service, "http://www.hazelcast.com/schema/config":scheduled-executor-service, "http://www.hazelcast.com/schema/config":queue, "http://www.hazelcast.com/schema/config":map, "http://www.hazelcast.com/schema/config":multimap, "http://www.hazelcast.com/schema/config":replicatedmap, "http://www.hazelcast.com/schema/config":cache, "http://www.hazelcast.com/schema/config":list, "http://www.hazelcast.com/schema/config":set, "http://www.hazelcast.com/schema/config":topic, "http://www.hazelcast.com/schema/config":reliable-topic, "http://www.hazelcast.com/schema/config":ringbuffer, "http://www.hazelcast.com/schema/config":listeners, "http://www.hazelcast.com/schema/config":serialization, "http://www.hazelcast.com/schema/config":native-memory, "http://www.hazelcast.com/schema/config":security, "http://www.hazelcast.com/schema/config":member-attributes, "http://www.hazelcast.com/schema/config":split-brain-protection, "http://www.hazelcast.com/schema/config":lite-member, "http://www.hazelcast.com/schema/config":hot-restart-persistence, "http://www.hazelcast.com/schema/config":user-code-deployment, "http://www.hazelcast.com/schema/config":cardinality-estimator, "http://www.hazelcast.com/schema/config":flake-id-generator, "http://www.hazelcast.com/schema/config":crdt-replication, "http://www.hazelcast.com/schema/config":pn-counter, "http://www.hazelcast.com/schema/config":advanced-network, "http://www.hazelcast.com/schema/config":cp-subsystem, "http://www.hazelcast.com/schema/config":metrics}' is expected.
	at com.hazelcast.config.AbstractXmlConfigHelper.schemaValidation(AbstractXmlConfigHelper.java:119) ~[hazelcast-4.0.3.jar:4.0.3]
	at com.hazelcast.config.XmlConfigBuilder.parseAndBuildConfig(XmlConfigBuilder.java:169) ~[hazelcast-4.0.3.jar:4.0.3]
	at com.hazelcast.config.XmlConfigBuilder.build(XmlConfigBuilder.java:151) ~[hazelcast-4.0.3.jar:4.0.3]
	at com.hazelcast.config.XmlConfigBuilder.build(XmlConfigBuilder.java:144) ~[hazelcast-4.0.3.jar:4.0.3]
	at com.hazelcast.config.Config.load(Config.java:212) ~[hazelcast-4.0.3.jar:4.0.3]
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:125) ~[hazelcast-4.0.3.jar:4.0.3]
	at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:91) ~[hazelcast-4.0.3.jar:4.0.3]
	at org.springframework.boot.autoconfigure.hazelcast.HazelcastServerConfiguration$HazelcastServerConfigFileConfiguration.hazelcastInstance(HazelcastServerConfiguration.java:55) ~[spring-boot-autoconfigure-2.4.1.jar:2.4.1]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.3.2.jar:5.3.2]
	... 21 common frames omitted
Caused by: org.xml.sax.SAXParseException: cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://www.hazelcast.com/schema/config":group}'. One of '{"http://www.hazelcast.com/schema/config":import, "http://www.hazelcast.com/schema/config":config-replacers, "http://www.hazelcast.com/schema/config":cluster-name, "http://www.hazelcast.com/schema/config":license-key, "http://www.hazelcast.com/schema/config":instance-name, "http://www.hazelcast.com/schema/config":management-center, "http://www.hazelcast.com/schema/config":properties, "http://www.hazelcast.com/schema/config":wan-replication, "http://www.hazelcast.com/schema/config":network, "http://www.hazelcast.com/schema/config":partition-group, "http://www.hazelcast.com/schema/config":executor-service, "http://www.hazelcast.com/schema/config":durable-executor-service, "http://www.hazelcast.com/schema/config":scheduled-executor-service, "http://www.hazelcast.com/schema/config":queue, "http://www.hazelcast.com/schema/config":map, "http://www.hazelcast.com/schema/config":multimap, "http://www.hazelcast.com/schema/config":replicatedmap, "http://www.hazelcast.com/schema/config":cache, "http://www.hazelcast.com/schema/config":list, "http://www.hazelcast.com/schema/config":set, "http://www.hazelcast.com/schema/config":topic, "http://www.hazelcast.com/schema/config":reliable-topic, "http://www.hazelcast.com/schema/config":ringbuffer, "http://www.hazelcast.com/schema/config":listeners, "http://www.hazelcast.com/schema/config":serialization, "http://www.hazelcast.com/schema/config":native-memory, "http://www.hazelcast.com/schema/config":security, "http://www.hazelcast.com/schema/config":member-attributes, "http://www.hazelcast.com/schema/config":split-brain-protection, "http://www.hazelcast.com/schema/config":lite-member, "http://www.hazelcast.com/schema/config":hot-restart-persistence, "http://www.hazelcast.com/schema/config":user-code-deployment, "http://www.hazelcast.com/schema/config":cardinality-estimator, "http://www.hazelcast.com/schema/config":flake-id-generator, "http://www.hazelcast.com/schema/config":crdt-replication, "http://www.hazelcast.com/schema/config":pn-counter, "http://www.hazelcast.com/schema/config":advanced-network, "http://www.hazelcast.com/schema/config":cp-subsystem, "http://www.hazelcast.com/schema/config":metrics}' is expected.
	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:204) ~[na:na]
	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:135) ~[na:na]
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:396) ~[na:na]
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327) ~[na:na]
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:284) ~[na:na]
	at java.xml/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator$XSIErrorReporter.reportError(XMLSchemaValidator.java:511) ~[na:na]
	at java.xml/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.reportSchemaError(XMLSchemaValidator.java:3587) ~[na:na]
	at java.xml/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.handleStartElement(XMLSchemaValidator.java:1971) ~[na:na]
	at java.xml/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.startElement(XMLSchemaValidator.java:829) ~[na:na]
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.validation.ValidatorHandlerImpl.startElement(ValidatorHandlerImpl.java:570) ~[na:na]
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:510) ~[na:na]
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:374) ~[na:na]
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2710) ~[na:na]
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605) ~[na:na]
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112) ~[na:na]
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:534) ~[na:na]
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888) ~[na:na]
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824) ~[na:na]
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141) ~[na:na]
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1216) ~[na:na]
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:635) ~[na:na]
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.validation.ValidatorHandlerImpl.validate(ValidatorHandlerImpl.java:731) ~[na:na]
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.validation.ValidatorImpl.validate(ValidatorImpl.java:101) ~[na:na]
	at java.xml/javax.xml.validation.Validator.validate(Validator.java:124) ~[na:na]
	at com.hazelcast.config.AbstractXmlConfigHelper.schemaValidation(AbstractXmlConfigHelper.java:117) ~[hazelcast-4.0.3.jar:4.0.3]
	... 33 common frames omitted
```

**Comment by baphuc1998** [comment]
I found the problem with "www". Update to 
<hazelcast xmlns="http://www.hazelcast.com/schema/config"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="https://hazelcast.com/schema/config
           https://hazelcast.com/schema/config/hazelcast-config-3.12.xsd">
and it works.
