### ISSUE TITLE
Could not add AttributeConfig Extractor for this attribute name already added failing as of 4.2-SNAPSHOT

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#18039]
http://jenkins.hazelcast.com/view/stable/job/scale-up/45/console

/home/ec2-user/workspace/scale-up/4.2-SNAPSHOT/2021_01_05-17_20_54/value-extractor Failed

17:24:10 fail HzMember1HZ value-extractor_load_mapBak1ObjSql hzcmd.map.member.LoadPersonSerializable threadId=0 java.lang.IllegalArgumentException: Could not add AttributeConfig{name='genId'extractorClassName='hzcmd.extractor.GenIdExtractor'}. Extractor for this attribute name already added.

PASSES on 4.0.  4.1.  4.1.1

Failing on 4.2-SNAPSHOT

```
java.lang.IllegalArgumentException: Could not add AttributeConfig{name='genId'extractorClassName='hzcmd.extractor.GenIdExtractor'}. Extractor for this attribute name already added.
	at com.hazelcast.query.impl.getters.ExtractorHelper.instantiateExtractors(ExtractorHelper.java:40)
	at com.hazelcast.query.impl.getters.Extractors.<init>(Extractors.java:63)
	at com.hazelcast.query.impl.getters.Extractors.<init>(Extractors.java:39)
	at com.hazelcast.query.impl.getters.Extractors$Builder.build(Extractors.java:192)
	at com.hazelcast.map.impl.MapContainer.<init>(MapContainer.java:135)
	at com.hazelcast.map.impl.EnterpriseMapContainer.<init>(EnterpriseMapContainer.java:35)
	at com.hazelcast.map.impl.EnterpriseMapServiceContextImpl.createMapContainer(EnterpriseMapServiceContextImpl.java:114)
	at com.hazelcast.map.impl.MapServiceContextImpl.lambda$createMapConstructor$0(MapServiceContextImpl.java:196)
	at com.hazelcast.internal.util.ConcurrencyUtil.getOrPutSynchronized(ConcurrencyUtil.java:126)
	at com.hazelcast.map.impl.MapServiceContextImpl.getMapContainer(MapServiceContextImpl.java:287)
	at com.hazelcast.map.impl.PartitionContainer.createRecordStore(PartitionContainer.java:90)
	at com.hazelcast.map.impl.PartitionContainer.lambda$new$0(PartitionContainer.java:56)
	at com.hazelcast.internal.util.ConcurrencyUtil.getOrPutSynchronized(ConcurrencyUtil.java:126)
	at com.hazelcast.map.impl.PartitionContainer.getRecordStore(PartitionContainer.java:158)
	at com.hazelcast.map.impl.operation.MapOperation.getRecordStoreOrNull(MapOperation.java:170)
	at com.hazelcast.map.impl.operation.MapOperation.beforeRun(MapOperation.java:87)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:247)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:213)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:175)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:139)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
	at ------ submitted from ------.()
	at com.hazelcast.internal.util.ExceptionUtil.cloneExceptionWithFixedAsyncStackTrace(ExceptionUtil.java:265)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.returnOrThrowWithGetConventions(InvocationFuture.java:112)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:100)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:614)
	at com.hazelcast.map.impl.proxy.MapProxySupport.invokeOperation(MapProxySupport.java:475)
	at com.hazelcast.map.impl.proxy.MapProxySupport.setInternal(MapProxySupport.java:552)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.set(MapProxyImpl.java:247)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.set(MapProxyImpl.java:237)
	at hzcmd.map.member.base.Loader.timeStep(Loader.java:32)
```

```
 <map name="mapBak1HD*">
        <backup-count>1</backup-count>
        <in-memory-format>NATIVE</in-memory-format>


        <attributes>
            <attribute extractor-class-name="hzcmd.extractor.GenIdExtractor">genId</attribute>
        </attributes>
    <eviction eviction-policy="LRU" max-size-policy="FREE_NATIVE_MEMORY_PERCENTAGE" size="15"/></map>

    <map name="mapBak1*">
        <backup-count>1</backup-count>
        <in-memory-format>BINARY</in-memory-format>
        <attributes>
            <attribute extractor-class-name="hzcmd.extractor.GenIdExtractor">genId</attribute>
        </attributes>
    </map>

    <map name="mapBak1Obj*">
        <in-memory-format>OBJECT</in-memory-format>
        <backup-count>1</backup-count>
        <attributes>
            <attribute extractor-class-name="hzcmd.extractor.GenIdExtractor">genId</attribute>
        </attributes>
    </map>
```

**Comment by Danny-Hazelcast** [comment]
4.1.1 passing run http://jenkins.hazelcast.com/view/stable/job/scale-up/46/console

**Comment by Danny-Hazelcast** [comment]
latest 4.2 SNAPSHOT fail
http://jenkins.hazelcast.com/view/stable/job/scale-up/48/console
