### ISSUE TITLE
Using Spring properties on some XML configurations fails 

### ISSUE THREAD

**Issue by jfcfar** [hazelcast/hazelcast#18043]
**Describe the bug**

I'm upgrading from Hazelcast `3.12.1` to  `4.1.1`. On my XML configuration I'm using some properties that are defined in the `application.properties`. After upgrading to `4.1.1` the properties I'm using on attributes that changed syntax stopped working. 

**Expected behavior**
I should be able to use properties to configure hazelcast like I was until version 4

**To Reproduce**

With a map declared this way on a spring boot project:

```xml
            <hz:map name="SUBSCRIBERS"
                    backup-count="0"
                    async-backup-count="1"
                    max-idle-seconds="${hazelcast.subscribers.maxIdleSeconds:7200}">
                <hz:eviction eviction-policy="LRU"
                             max-size-policy="PER_NODE"
                             size="${hazelcast.subscribers.maxSizePerNode:500000}"/>
            </hz:map>
```
The  `max-idle-seconds` attribute works fine as a property but the `size` throws this error:

```
2021-01-08T10:59:14,040 [ERROR] main [SpringApplication reportFailure:771] Application startup failed                                                                                                        
org.springframework.beans.factory.xml.XmlBeanDefinitionStoreException: Line 280 in XML document from class path resource [components.xml] is invalid; nested exception is org.xml.sax.SAXParseException; line
Number: 280; columnNumber: 85; cvc-datatype-valid.1.2.1: '${hazelcast.subscribers.maxSizePerNode:500000}' is not a valid value for 'integer'.
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:399) ~[spring-beans-4.3.18.RELEASE.jar:4.3.18.RELEASE]
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:336) ~[spring-beans-4.3.18.RELEASE.jar:4.3.18.RELEASE]
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:304) ~[spring-beans-4.3.18.RELEASE.jar:4.3.18.RELEASE]

(...)
```

**Comment by mmedenjak** [comment]
Thank you for the report @jfcfar !
@ahmetmircik can you take a look? I'm not if this is due to the changed eviction configuration, a spring integration issue or some misconfiguration?

**Comment by ahmetmircik** [comment]
@mmedenjak 
><xs:attribute name="size" type="xs:nonNegativeInteger" default="10000" use="optional"/>

By starting 4.0, map and cache are using same underlying eviction config implementation, before that map's `size` was a string type. 

I think we can restore old behavior by fixing current one.
