### ISSUE TITLE
set TcpIpConfig,but can't find each other

### ISSUE THREAD

**Issue by CobraStarLE** [hazelcast/hazelcast#18059]
I have two computers to start Hazelcast, but the IP addresses of these two computers are different, 192.168.0.2, 192.168.1.3, but they can ping each other, but these two computers Hazeelcast is not found each other, although I set TcpIpConfig still can not I can, my Hazelcast version is 3.12.11, can you explain why, thank you!

**Comment by mmedenjak** [comment]
Hi @CobraStarLE ! Are you getting some kind of error in the logs of the Hazelcast nodes? Can you share the logs?

**Comment by CobraStarLE** [comment]
Now this error is reported：
2021-01-18 11:00:59.175 |-WARN  [hz.hazelcast-waustreet-instance.partition-operation.thread-6] |-Caller+0	 at com.hazelcast.logging.StandardLoggerFactory$StandardLogger.log(StandardLoggerFactory.java:49)
|- c.h.c.i.raftop.metadata.InitMetadataRaftGroupOp [49] -| [192.168.1.220]:5702 [waustreet] [3.12.11] Invalid initial CP members! Expected: [CPMember{uuid=351767f8-021d-4447-9755-71fbcb6dce46, address=[192.168.1.220]:5701}, CPMember{uuid=e39e392b-d60f-4ecc-985c-bc716976fa56, address=[192.168.1.220]:5702}, CPMember{uuid=e5aaf6ee-858e-4ae0-a8b0-ff26f2997231, address=[192.168.0.157]:5701}], Actual: [CPMember{uuid=e39e392b-d60f-4ecc-985c-bc716976fa56, address=[192.168.1.220]:5702}, CPMember{uuid=e5aaf6ee-858e-4ae0-a8b0-ff26f2997231, address=[192.168.0.157]:5701}, CPMember{uuid=f4e171d1-7aaf-48c6-8394-5eed83f408cb, address=[192.168.1.220]:5701}]
java.lang.IllegalArgumentException: Invalid initial CP members! Expected: [CPMember{uuid=351767f8-021d-4447-9755-71fbcb6dce46, address=[192.168.1.220]:5701}, CPMember{uuid=e39e392b-d60f-4ecc-985c-bc716976fa56, address=[192.168.1.220]:5702}, CPMember{uuid=e5aaf6ee-858e-4ae0-a8b0-ff26f2997231, address=[192.168.0.157]:5701}], Actual: [CPMember{uuid=e39e392b-d60f-4ecc-985c-bc716976fa56, address=[192.168.1.220]:5702}, CPMember{uuid=e5aaf6ee-858e-4ae0-a8b0-ff26f2997231, address=[192.168.0.157]:5701}, CPMember{uuid=f4e171d1-7aaf-48c6-8394-5eed83f408cb, address=[192.168.1.220]:5701}]
	at com.hazelcast.cp.internal.MetadataRaftGroupManager.failMetadataRaftGroupInitializationIfNotCompletedAndThrow(MetadataRaftGroupManager.java:398)
	at com.hazelcast.cp.internal.MetadataRaftGroupManager.initMetadataGroup(MetadataRaftGroupManager.java:328)
	at com.hazelcast.cp.internal.raftop.metadata.InitMetadataRaftGroupOp.run(InitMetadataRaftGroupOp.java:56)
	at com.hazelcast.cp.internal.raftop.metadata.MetadataRaftGroupOp.run(MetadataRaftGroupOp.java:38)
	at com.hazelcast.cp.internal.NodeEngineRaftIntegration.runOperation(NodeEngineRaftIntegration.java:185)
	at com.hazelcast.cp.internal.raft.impl.RaftNodeImpl.applyLogEntry(RaftNodeImpl.java:613)
	at com.hazelcast.cp.internal.raft.impl.RaftNodeImpl.applyLogEntries(RaftNodeImpl.java:556)
	at com.hazelcast.cp.internal.raft.impl.handler.AppendRequestHandlerTask.innerRun(AppendRequestHandlerTask.java:215)
	at com.hazelcast.cp.internal.raft.impl.task.RaftNodeStatusAwareTask.run(RaftNodeStatusAwareTask.java:46)
	at com.hazelcast.cp.internal.NodeEngineRaftIntegration.execute(NodeEngineRaftIntegration.java:98)
	at com.hazelcast.cp.internal.raft.impl.RaftNodeImpl.execute(RaftNodeImpl.java:648)
	at com.hazelcast.cp.internal.raft.impl.RaftNodeImpl.handleAppendRequest(RaftNodeImpl.java:238)
	at com.hazelcast.cp.internal.RaftService.handleAppendEntries(RaftService.java:573)
	at com.hazelcast.cp.internal.operation.integration.AppendRequestOp.run(AppendRequestOp.java:46)
	at com.hazelcast.spi.Operation.call(Operation.java:170)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:210)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:199)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:412)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:153)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:123)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:110)
2021-01-18 11:00:59.179 |-ERROR [hz.hazelcast-waustreet-instance.cached.thread-1] |-Caller+0	 at com.hazelcast.logging.StandardLoggerFactory$StandardLogger.log(StandardLoggerFactory.java:49)
|- com.hazelcast.cp.internal.MetadataRaftGroupManager [49] -| [192.168.1.220]:5702 [waustreet] [3.12.11] Could not initialize METADATA CP group with CP members: [CPMember{uuid=351767f8-021d-4447-9755-71fbcb6dce46, address=[192.168.1.220]:5701}, CPMember{uuid=e39e392b-d60f-4ecc-985c-bc716976fa56, address=[192.168.1.220]:5702}, CPMember{uuid=e5aaf6ee-858e-4ae0-a8b0-ff26f2997231, address=[192.168.0.157]:5701}]
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Invalid initial CP members! Expected: [CPMember{uuid=351767f8-021d-4447-9755-71fbcb6dce46, address=[192.168.1.220]:5701}, CPMember{uuid=e39e392b-d60f-4ecc-985c-bc716976fa56, address=[192.168.1.220]:5702}, CPMember{uuid=e5aaf6ee-858e-4ae0-a8b0-ff26f2997231, address=[192.168.0.157]:5701}], Actual: [CPMember{uuid=e39e392b-d60f-4ecc-985c-bc716976fa56, address=[192.168.1.220]:5702}, CPMember{uuid=e5aaf6ee-858e-4ae0-a8b0-ff26f2997231, address=[192.168.0.157]:5701}, CPMember{uuid=f4e171d1-7aaf-48c6-8394-5eed83f408cb, address=[192.168.1.220]:5701}]
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:92)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:163)
	at com.hazelcast.cp.internal.MetadataRaftGroupManager$DiscoverInitialCPMembersTask.commitMetadataRaftGroupInit(MetadataRaftGroupManager.java:1156)
	at com.hazelcast.cp.internal.MetadataRaftGroupManager$DiscoverInitialCPMembersTask.doRun(MetadataRaftGroupManager.java:1064)
	at com.hazelcast.cp.internal.MetadataRaftGroupManager$DiscoverInitialCPMembersTask.run(MetadataRaftGroupManager.java:1026)
	at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:227)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
Caused by: java.lang.IllegalArgumentException: Invalid initial CP members! Expected: [CPMember{uuid=351767f8-021d-4447-9755-71fbcb6dce46, address=[192.168.1.220]:5701}, CPMember{uuid=e39e392b-d60f-4ecc-985c-bc716976fa56, address=[192.168.1.220]:5702}, CPMember{uuid=e5aaf6ee-858e-4ae0-a8b0-ff26f2997231, address=[192.168.0.157]:5701}], Actual: [CPMember{uuid=e39e392b-d60f-4ecc-985c-bc716976fa56, address=[192.168.1.220]:5702}, CPMember{uuid=e5aaf6ee-858e-4ae0-a8b0-ff26f2997231, address=[192.168.0.157]:5701}, CPMember{uuid=f4e171d1-7aaf-48c6-8394-5eed83f408cb, address=[192.168.1.220]:5701}]
	at com.hazelcast.cp.internal.MetadataRaftGroupManager.failMetadataRaftGroupInitializationIfNotCompletedAndThrow(MetadataRaftGroupManager.java:398)
	at com.hazelcast.cp.internal.MetadataRaftGroupManager.initMetadataGroup(MetadataRaftGroupManager.java:328)
	at com.hazelcast.cp.internal.raftop.metadata.InitMetadataRaftGroupOp.run(InitMetadataRaftGroupOp.java:56)
	at com.hazelcast.cp.internal.raftop.metadata.MetadataRaftGroupOp.run(MetadataRaftGroupOp.java:38)
	at com.hazelcast.cp.internal.NodeEngineRaftIntegration.runOperation(NodeEngineRaftIntegration.java:185)
	at com.hazelcast.cp.internal.raft.impl.RaftNodeImpl.applyLogEntry(RaftNodeImpl.java:613)
	at com.hazelcast.cp.internal.raft.impl.RaftNodeImpl.applyLogEntries(RaftNodeImpl.java:556)
	at com.hazelcast.cp.internal.raft.impl.handler.AppendSuccessResponseHandlerTask.commitEntries(AppendSuccessResponseHandlerTask.java:164)
	at com.hazelcast.cp.internal.raft.impl.handler.AppendSuccessResponseHandlerTask.handleResponse(AppendSuccessResponseHandlerTask.java:88)
	at com.hazelcast.cp.internal.raft.impl.handler.AbstractResponseHandlerTask.innerRun(AbstractResponseHandlerTask.java:43)
	at com.hazelcast.cp.internal.raft.impl.task.RaftNodeStatusAwareTask.run(RaftNodeStatusAwareTask.java:46)
	at com.hazelcast.cp.internal.NodeEngineRaftIntegration.execute(NodeEngineRaftIntegration.java:98)
	at com.hazelcast.cp.internal.raft.impl.RaftNodeImpl.execute(RaftNodeImpl.java:648)
	at com.hazelcast.cp.internal.raft.impl.RaftNodeImpl.handleAppendResponse(RaftNodeImpl.java:243)
	at com.hazelcast.cp.internal.RaftService.handleAppendResponse(RaftService.java:580)
	at com.hazelcast.cp.internal.operation.integration.AppendSuccessResponseOp.run(AppendSuccessResponseOp.java:48)
	at com.hazelcast.spi.Operation.call(Operation.java:170)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:210)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:199)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:412)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:153)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:123)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:110)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:126)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:79)
	... 10 common frames omitted

My Hazelcast configuration is as follows:
Config config = new Config();

        ManagementCenterConfig managementCenterConfig = new ManagementCenterConfig();
        managementCenterConfig.setScriptingEnabled(true);

        GroupConfig groupConfig = new GroupConfig("world-group");
        config.setGroupConfig(groupConfig);
        config.setManagementCenterConfig(managementCenterConfig);

        FlakeIdGeneratorConfig flakeIdGeneratorConfig = new FlakeIdGeneratorConfig("flakeIdConfig");
        flakeIdGeneratorConfig.setPrefetchCount(100).setPrefetchValidityMillis(MINUTES.toMillis(10000));
        Map<String, FlakeIdGeneratorConfig> flakeIdGeneratorConfigMap = new HashMap<>();
        flakeIdGeneratorConfigMap.put("commonIdGenerator", flakeIdGeneratorConfig);
        config.setFlakeIdGeneratorConfigs(flakeIdGeneratorConfigMap);

        MapConfig mapConfig = new MapConfig();
        mapConfig.setName("worldMapCfg");
        mapConfig.setTimeToLiveSeconds(3600);
        mapConfig.setEvictionPolicy(EvictionPolicy.LRU);
        config.addMapConfig(mapConfig);

        NetworkConfig network = config.getNetworkConfig();
        JoinConfig join = network.getJoin();
        join.getMulticastConfig().setEnabled(false);
        join.getTcpIpConfig().addMember( "192.168.1.220" )
                .setMembers(Lists.newArrayList("192.168.0.157")).setEnabled( true );

        config.setInstanceName("hazelcast-waustreet-instance").addMapConfig(mapConfig);
        config.getCPSubsystemConfig().setCPMemberCount(3);

**Comment by CobraStarLE** [comment]
Sometimes it works,but Now,report this error:
2021-01-18 18:03:33.347|-[hz.hazelcast-waustreet-instance.cached.thread-3-] |-INFO  [hz.hazelcast-waustreet-instance.cached.thread-3] |-Caller+0	 at com.hazelcast.logging.StandardLoggerFactory$StandardLogger.log(StandardLoggerFactory.java:49)
|- com.hazelcast.nio.tcp.TcpIpConnector [49] -| [192.168.0.157]:5701 [waustreet] [3.12.11] Could not connect to: /192.168.1.220:5701. Reason: SocketException[Connection refused to address /192.168.1.220:5701]
2021-01-18 18:03:33.453|-[hz.hazelcast-waustreet-instance.cached.thread-3-] |-INFO  [hz.hazelcast-waustreet-instance.cached.thread-3] |-Caller+0	 at com.hazelcast.logging.StandardLoggerFactory$StandardLogger.log(StandardLoggerFactory.java:49)
|- com.hazelcast.nio.tcp.TcpIpConnector [49] -| [192.168.0.157]:5701 [waustreet] [3.12.11] Connecting to /192.168.1.220:5701, timeout: 10000, bind-any: true

**Comment by CobraStarLE** [comment]
hello,
The same IP, but different ports, cannot be discovered by each other using TcpIpConfig.
