### ISSUE TITLE
External config override for rest-api endpoint-group name always lowercase

### ISSUE THREAD

**Issue by smartpuma** [hazelcast/hazelcast#18154]
Config override with system properties to enable REST for endpoint-group DATA:
-Dhz.network.rest-api.enabled=true -Dhz.network.rest-api.endpoint-groups.DATA.enabled=true

```
Exception in thread "main" com.hazelcast.config.InvalidConfigurationException: failed to overwrite configuration coming from system properties
     at com.hazelcast.internal.config.override.ExternalConfigurationOverride.lambda$overwriteMemberConfig$0(ExternalConfigurationOverride.java:48)
     at com.hazelcast.internal.config.override.ExternalConfigurationOverride.overwrite(ExternalConfigurationOverride.java:77)
     at com.hazelcast.internal.config.override.ExternalConfigurationOverride.overwriteMemberConfig(ExternalConfigurationOverride.java:43)
     at com.hazelcast.config.Config.load(Config.java:208)
     at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:125)
     at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:91)
     at com.hazelcast.core.server.HazelcastMemberStarter.main(HazelcastMemberStarter.java:47)
Caused by: com.hazelcast.config.InvalidConfigurationException: Wrong name attribute value was provided in endpoint-group element: data
Allowed values: [CLUSTER_READ, CLUSTER_WRITE, HEALTH_CHECK, HOT_RESTART, WAN, DATA, CP]
     at com.hazelcast.internal.config.MemberDomConfigProcessor.handleEndpointGroup(MemberDomConfigProcessor.java:2723)
     at com.hazelcast.internal.config.YamlMemberDomConfigProcessor.handleRestApiEndpointGroups(YamlMemberDomConfigProcessor.java:776)
     at com.hazelcast.internal.config.MemberDomConfigProcessor.handleRestApi(MemberDomConfigProcessor.java:2681)
     at com.hazelcast.internal.config.MemberDomConfigProcessor.handleNetwork(MemberDomConfigProcessor.java:792)
     at com.hazelcast.internal.config.MemberDomConfigProcessor.handleNode(MemberDomConfigProcessor.java:271)
     at com.hazelcast.internal.config.MemberDomConfigProcessor.buildConfig(MemberDomConfigProcessor.java:256)
     at com.hazelcast.internal.config.override.ExternalConfigurationOverride.lambda$overwriteMemberConfig$0(ExternalConfigurationOverride.java:46)
     ... 6 more
```

It looks like the whole input value from system properties is converted to lowercase. The name of the endpoint-group should remain in uppercase. Or should be converted to uppercase before RestEndpointGroup.valueOf(name) is called.

Hazelcast version: 4.1.1

similar issue:
#17675

**Comment by mmedenjak** [comment]
@smartpuma thank you for your report. @pivovarit can you take a look?

**Comment by pivovarit** [comment]
Good catch, will take care of that
