### ISSUE TITLE
EvictionTest.testOnExpiredKeys_keySet[statisticsEnabled:true]

### ISSUE THREAD

**Issue by sancar** [hazelcast/hazelcast#18173]
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/3748/testReport/junit/com.hazelcast.map/EvictionTest/testOnExpiredKeys_keySet_statisticsEnabled_true_/

Error Message
expected:<0> but was:<2>
Stacktrace
```
java.lang.AssertionError: expected:<0> but was:<2>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at com.hazelcast.map.EvictionTest.testOnExpiredKeys_keySet(EvictionTest.java:1007)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by ahmetmircik** [comment]
We did merge https://github.com/hazelcast/hazelcast/pull/18093 yesterday. This issue should not be seen after merging it. If we see it happening again, we can reopen this issue.
