### ISSUE TITLE
HazelcastClientStarterTest test failures

### ISSUE THREAD

**Issue by kwart** [hazelcast/hazelcast#18228]
The `HazelcastClientStarterTest` tests fail regularly in our CI:

* `testAdvancedClientMap`
* `testClientLifecycle`
* `testClientMap`

Sample job: http://jenkins.hazelcast.com/job/Hazelcast-4.master-nightly/753/

The tests are failing with the `ClassNotFoundException`:

```
java.lang.NoClassDefFoundError: com/hazelcast/logging/impl/InternalLogger
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:635)
	at com.hazelcast.test.starter.HazelcastAPIDelegatingClassloader.findClassInParentURLs(HazelcastAPIDelegatingClassloader.java:149)
	at com.hazelcast.test.starter.HazelcastAPIDelegatingClassloader.loadClass(HazelcastAPIDelegatingClassloader.java:117)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at com.hazelcast.test.TestLoggerFactory.createLogger(TestLoggerFactory.java:94)
	at com.hazelcast.logging.LoggerFactorySupport$1.createNew(LoggerFactorySupport.java:32)
	at com.hazelcast.logging.LoggerFactorySupport$1.createNew(LoggerFactorySupport.java:30)
	at com.hazelcast.internal.util.ConcurrencyUtil.getOrPutIfAbsent(ConcurrencyUtil.java:140)
	at com.hazelcast.logging.LoggerFactorySupport.getLogger(LoggerFactorySupport.java:38)
	at com.hazelcast.logging.Logger.getLogger(Logger.java:110)
	at com.hazelcast.logging.Logger.getLogger(Logger.java:64)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.<clinit>(HazelcastInstanceFactory.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.hazelcast.test.starter.HazelcastStarter.createInstanceViaInstanceFactory(HazelcastStarter.java:246)
	at com.hazelcast.test.starter.HazelcastStarter.newHazelcastInstanceWithNetwork(HazelcastStarter.java:220)
	at com.hazelcast.test.starter.HazelcastStarter.newHazelcastInstance(HazelcastStarter.java:109)
	at com.hazelcast.test.starter.HazelcastStarter.newHazelcastInstance(HazelcastStarter.java:69)
	at com.hazelcast.client.starter.HazelcastClientStarterTest.testAdvancedClientMap(HazelcastClientStarterTest.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.hazelcast.logging.impl.InternalLogger
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at com.hazelcast.test.starter.HazelcastAPIDelegatingClassloader.loadClass(HazelcastAPIDelegatingClassloader.java:120)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 35 more
```

**Comment by vbekiaris** [comment]
The `HazelcastClientStarterTest` starts HZ instances using old released artifacts with the `HazelcastAPIDelegatingClassloader` classloader.

However the test itself is not executed as a compatibility test (`-Dhazelcast.test.compatibility=true`) 
  -> [test logging is used](https://github.com/hazelcast/hazelcast/blob/40d555dc1110da9f63fd66f504c83d4382d0384b/hazelcast/src/test/java/com/hazelcast/test/AbstractHazelcastClassRunner.java#L111-L120) 
  -> new in 4.2 `InternalLogger` interface is implemented by loggers returned by `TestLoggerFactory` 
  -> `InternalLogger` interface is looked up in old artifacts and not found 
  -> failure.

I think we can:
1. move the test to EE repository and execute in `compatibility-tests` profile
1. ignore the test until 4.2 is released. Then update it to start "old" 4.2 artifacts which will include the `InternalLogger` interface
1. remove the test altogether - if the `HazelcastClientStarter` is broken, all client compatibility tests on EE repository will fail anyway and it will be noticed

I am in favour of removing the test - @sancar @mmedenjak wdyt?

**Comment by sancar** [comment]
@vbekiaris How about this fix https://github.com/hazelcast/hazelcast/pull/18230 ?
