### ISSUE TITLE
PortableFactory  is already registered ? while replacing hazelcast from 3.1.5 to 3.2 snapshot

### ISSUE THREAD

**Issue by bwzhang2011** [hazelcast/hazelcast#1826]
while testing 3.2 snapshot, I just replace the 3.1.5 jar with the latest build one, but it failed while creating the hazelcastInstance from spring module here comes the stacktrae(help someone could solve such problem or point out my mistake):
1. StackTrace:
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hazelcastInstance': Instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanDefinitionStoreException: Factory method [public static com.hazelcast.core.HazelcastInstance com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(com.hazelcast.config.Config)] threw exception; nested exception is java.lang.IllegalArgumentException: PortableFactory[-14] is already registered! com.hazelcast.concurrent.countdownlatch.CountDownLatchPortableHook$1@1ed6352 -> com.hazelcast.concurrent.countdownlatch.client.CountDownLatchPortableHook$1@13dc0e
    at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:592)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1094)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:989)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:504)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:475)
    at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:304)
    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:300)
    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:195)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1014)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:957)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:855)
    at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:480)
    ... 16 more
Caused by: org.springframework.beans.factory.BeanDefinitionStoreException: Factory method [public static com.hazelcast.core.HazelcastInstance com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(com.hazelcast.config.Config)] threw exception; nested exception is java.lang.IllegalArgumentException: PortableFactory[-14] is already registered! com.hazelcast.concurrent.countdownlatch.CountDownLatchPortableHook$1@1ed6352 -> com.hazelcast.concurrent.countdownlatch.client.CountDownLatchPortableHook$1@13dc0e
    at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:188)
    at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:581)
    ... 28 more
Caused by: java.lang.IllegalArgumentException: PortableFactory[-14] is already registered! com.hazelcast.concurrent.countdownlatch.CountDownLatchPortableHook$1@1ed6352 -> com.hazelcast.concurrent.countdownlatch.client.CountDownLatchPortableHook$1@13dc0e
    at com.hazelcast.nio.serialization.PortableHookLoader.register(PortableHookLoader.java:84)
    at com.hazelcast.nio.serialization.PortableHookLoader.load(PortableHookLoader.java:51)
    at com.hazelcast.nio.serialization.PortableHookLoader.<init>(PortableHookLoader.java:41)
    at com.hazelcast.nio.serialization.SerializationServiceImpl.<init>(SerializationServiceImpl.java:85)
    at com.hazelcast.nio.serialization.SerializationServiceBuilder.build(SerializationServiceBuilder.java:174)
    at com.hazelcast.instance.Node.<init>(Node.java:130)
    at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:92)
    at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:92)
    at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:72)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:166)
1. while my spring configuration like this:
   <beans xmlns="http://www.springframework.org/schema/beans"
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:hz="http://www.hazelcast.com/schema/spring"
   xmlns:cache="http://www.springframework.org/schema/cache" xmlns:p="http://www.springframework.org/schema/p"
   xsi:schemaLocation="
    http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-3.2.xsd
    http://www.springframework.org/schema/cache http://www.springframework.org/schema/cache/spring-cache-3.2.xsd
    http://www.hazelcast.com/schema/spring http://www.hazelcast.com/schema/spring/hazelcast-spring-3.1.xsd">
   
   
   
   <hz:hazelcast id="hazelcastInstance">
       hz:config
           hz:instance-namewko appServe/hz:instance-name
           
           <hz:group name="${DEFAULT_GROUP_NAME}" password="${DEFAULT_GROUP_PWD}" />
           hz:properties
               <hz:property name="hazelcast.logging.type">sl4j/hz:property
               <hz:property name="hazelcast.executor.query.thread.count">32/hz:property
               <hz:property name="hazelcast.executor.event.thread.count">32/hz:property
           /hz:properties
           
           <hz:network port="${DEFAULT_GROUP_PORT}"
               port-auto-increment="false">
               hz:join
                   <hz:multicast enabled="false" />
                   <hz:tcp-ip enabled="${DEFAULT_GROUP_ENALED}">
                       hz:members${DEFAULT_GROUP_MEMBERS}/hz:members
                   /hz:tcp-ip
               /hz:join
           /hz:network
           
           hz:serialization
              hz:serializers
                 <hz:serializer type-class="${DEFAULT_TYPE_CLASS}" class-name="${DEFAULT_TYPECLASS_IMPL}"/>
              /hz:serializers
           /hz:serialization
       /hz:config
   /hz:hazelcast
   
   
   
   <hz:semaphore id="semaphore" name="semaphore" instance-ref="hazelcastInstance" />
   
   
   
   <bean id="cacheManager" class="com.hazelcast.spring.cache.HazelcastCacheManager">
       <constructor-arg ref="hazelcastInstance" />
   </bean>
   
   
   
   <cache:annotation-driven cache-manager="cacheManager" mode="proxy" />

</beans>

**Comment by qickrooms** [comment]
Yes, I had this same issues as well, and yes, I did not delete previous lib from upgrade. Thanks!

**Comment by ankitbeohar90** [comment]
I am trying to run Hazelcast inside spark code but at the time of job submitting getting below error:-

java.lang.IllegalArgumentException: PortableFactory[-23] is already registered! com.hazelcast.mapreduce.impl.MapReducePortableHook$1@47463f67 -> com.hazelcast.mapreduce.impl.MapReducePortableHook$1@70dccc57
        at com.hazelcast.internal.serialization.impl.PortableHookLoader.register(PortableHookLoader.java:87)
        at com.hazelcast.internal.serialization.impl.PortableHookLoader.load(PortableHookLoader.java:54)
        at com.hazelcast.internal.serialization.impl.PortableHookLoader.<init>(PortableHookLoader.java:44)
        at com.hazelcast.internal.serialization.impl.SerializationServiceV1.<init>(SerializationServiceV1.java:88)
        at com.hazelcast.internal.serialization.impl.DefaultSerializationServiceBuilder.createSerializationService(DefaultSerializationServiceBuilder.java:264)
        at com.hazelcast.internal.serialization.impl.DefaultSerializationServiceBuilder.build(DefaultSerializationServiceBuilder.java:218)
        at com.hazelcast.instance.DefaultNodeExtension.createSerializationService(DefaultNodeExtension.java:125)
        at com.hazelcast.instance.Node.<init>(Node.java:173)
        at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:125)
        at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:160)
        at com.hazelcast.instance.HazelcastInstanceFactory.getOrCreateHazelcastInstance(HazelcastInstanceFactory.java:98)
        at com.hazelcast.core.Hazelcast.getOrCreateHazelcastInstance(Hazelcast.java:116)
        at com.onlinetechvision.spark.hazelcast.connector.config.SparkHazelcastService$.getSparkHazelcastData(SparkHazelcastService.scala:39)
        at com.onlinetechvision.spark.hazelcast.connector.rdd.implicits.package$HazelcastWriter$HazelcastTask.execute(package.scala:43)
        at com.onlinetechvision.spark.hazelcast.connector.rdd.implicits.package$HazelcastWriter$$anonfun$writeToHazelcast$1.apply(package.scala:38)
        at com.onlinetechvision.spark.hazelcast.connector.rdd.implicits.package$HazelcastWriter$$anonfun$writeToHazelcast$1.apply(package.scala:38)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1497)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1497)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:61)
        at org.apache.spark.scheduler.Task.run(Task.scala:64)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:203)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**I do not have multiple version of hazelcast in calsspath**

**Comment by jerrinot** [comment]
@ankitbeohar90: apparently serialization hooks are present multiple times on your classpath. Having multiple JARs is the simplest explanation, but it's not the only one. This issue is also possible in  environments with a complicated classloader graph. 

Do you have a reproducer you could share? Could you describe your environment a bit? So it's a Spark task. Anything else what's significant for classloading? 

A shameless-plug: you might want to have a look at https://github.com/hazelcast/hazelcast-spark

**Comment by ankitbeohar90** [comment]
@jerrinot : Do we have maven binary(entry ) for this project?

**Comment by eminn** [comment]
@ankitbeohar90 It hasn't been released yet. Hopefully we will plan to release it with 3.7

**Comment by ejain** [comment]
I'm seeing the same problem with Hazelcast 3.7.1:

```Failed to instantiate [com.hazelcast.core.HazelcastInstance]: Factory method 'hazelcastInstance' threw exception; nested exception is java.lang.IllegalArgumentException: PortableFactory[-1] is already registered! com.hazelcast.spi.impl.SpiPortableHook$1@688057d0 -> com.hazelcast.spi.impl.SpiPortableHook$1@5be3e5d8
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189)```

The problem goes away if I downgrade to 3.1.5; haven't tried other versions yet.

**Comment by noctarius** [comment]
You most probably have two different Hazelcast JARs on your classpath. Please check. Apart from that please do not reuse those old tickets as, if there's a real problem to be fixed, it cannot be included into any release. If it is a new version, we appreciate creating a new ticket :) Thanks.

**Comment by ejain** [comment]
Verified that there's just one Hazelcast JAR. It's possible that Spring or some other library is secretly configuring Hazelcast in duplicate; if I'm able to pin the blame on Hazelcast, I'll open a new ticket...

**Comment by noctarius** [comment]
Alright thanks :)

**Comment by ejain** [comment]
Looks like this is #2395.
