### ISSUE TITLE
Cluster is in PASSIVE state! Operation: com.hazelcast.cache.impl.operation.AddCacheConfigOperation

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#18261]
java.lang.IllegalStateException: Cluster is in PASSIVE state! Operation: com.hazelcast.cache.impl.operation.AddCacheConfigOperation{serviceName='hz:impl:cacheService', identityHash=294505405, partitionId=-1, replicaIndex=0, callId=0, invocationTime=-1 (1969-12-31 23:59:59.999), waitTimeout=-1, callTimeout=60000, tenantControl=com.hazelcast.spi.impl.tenantcontrol.NoopTenantControl@0}
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.engineActive(Invocation.java:517)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:550)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:540)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:240)
	at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.invokeOnTarget(OperationServiceImpl.java:359)
	at com.hazelcast.internal.util.InvocationUtil$InvokeOnMemberFunction.invokeOnMember(InvocationUtil.java:151)
	at com.hazelcast.internal.util.InvocationUtil$InvokeOnMemberFunction.apply(InvocationUtil.java:128)
	at com.hazelcast.internal.util.InvocationUtil$InvokeOnMemberFunction.apply(InvocationUtil.java:108)
	at com.hazelcast.internal.util.IterableUtil$1.next(IterableUtil.java:62)
	at com.hazelcast.internal.util.futures.ChainingFuture.<init>(ChainingFuture.java:42)
	at com.hazelcast.internal.util.InvocationUtil.invokeOnStableClusterSerial(InvocationUtil.java:77)
	at com.hazelcast.cache.impl.AbstractCacheService.createCacheConfigOnAllMembersAsync(AbstractCacheService.java:849)
	at com.hazelcast.cache.impl.AbstractCacheService.createCacheConfigOnAllMembers(AbstractCacheService.java:844)
	at com.hazelcast.cache.impl.HazelcastServerCacheManager.createCacheConfig(HazelcastServerCacheManager.java:151)
	at com.hazelcast.cache.impl.HazelcastServerCacheManager.findCacheConfig(HazelcastServerCacheManager.java:144)
	at com.hazelcast.cache.impl.AbstractHazelcastCacheManager.getCacheUnchecked(AbstractHazelcastCacheManager.java:228)
	at com.hazelcast.cache.impl.AbstractHazelcastCacheManager.getCache(AbstractHazelcastCacheManager.java:210)
	at com.hazelcast.cache.impl.AbstractHazelcastCacheManager.getCache(AbstractHazelcastCacheManager.java:65)

i am only seeing this issue for cache and not map,  and only in cluster state PASSIVE and not FROZEN,  also this test was passing on older HZ versions

http://jenkins.hazelcast.com/view/hot-restart/job/hot-v-clusterShutdown/45/console

/home/ec2-user/workspace/hot-v-clusterShutdown/4.2-SNAPSHOT/2021_02_21-19_13_38/clusterShutdown

**Comment by Danny-Hazelcast** [comment]
i am only seeing this issue for cache and not map, and only in cluster state PASSIVE and not FROZEN, also this test was passing on older HZ versions

http://jenkins.hazelcast.com/view/hot-restart/job/hot-v-clusterShutdown/45/console

/home/ec2-user/workspace/hot-v-clusterShutdown/4.2-SNAPSHOT/2021_02_21-19_13_38/clusterShutdown

**Comment by Danny-Hazelcast** [comment]
or is it now that the cluster state  PASSIVE is preserved on restart ? 

while FROZEN is not ?

**Comment by vbekiaris** [comment]
The cluster state should be preserved by hot restart and I don't expect this changed since 4.1. Also, `AddCacheConfigOperation` was not allowed in `PASSIVE` state in 4.1 either. I see this in the failed run logs:

```
HzMember3HZ/out.txt
PARTIAL_RECOVERY_MOST_COMPLETE clusterPassive shutdown cluster restart all members
...
INFO: [10.0.0.45]:5701 [HZ] [4.2-SNAPSHOT] Added cache config: CacheConfig{name='cacheBak1', managerPrefix='/hz/', inMemoryFormat=BINARY, backupCount=1, hotRestart=HotRestartConfig{enabled=true, fsync=false}, wanReplic
ationRef=null}
Feb 21, 2021 7:22:04 PM com.hazelcast.cache.impl.EnterpriseCacheService
INFO: [10.0.0.45]:5701 [HZ] [4.2-SNAPSHOT] Added cache config: CacheConfig{name='cacheBak1HD', managerPrefix='/hz/', inMemoryFormat=NATIVE, backupCount=1, hotRestart=HotRestartConfig{enabled=true, fsync=false}, wanRepl
icationRef=null}
```

so upon joining, the `CacheConfig`s became known to the member. @Danny-Hazelcast can you post a link to the source of `validate_cacheBak1` and `validate_cacheBak1HD` tasks?

**Comment by Danny-Hazelcast** [comment]
@vbekiaris  yes the behaviour has changed from 4.1 

test script
https://github.com/hazelcast/hzCmd-bench/blob/m6g/lab/hz/hot/x/clusterShutdown/go 

the FROZEN case seams to be working with no change

**Comment by vbekiaris** [comment]
@Danny-Hazelcast I can reproduce the same issue with `PASSIVE` state on both current `4.1.z` and released 4.1 (`eded1cf`, `2a1a477`). The code path that throws the exception wasn't changed in 4.2. Can you rerun your test on 4.1 and verify?

**Comment by Danny-Hazelcast** [comment]
@vbekiaris  yes in 4.1 it is not working also

**Comment by vbekiaris** [comment]
thanks Danny, so it's not a regression in 4.2

**Comment by Danny-Hazelcast** [comment]
@vbekiaris  is a regression from 4.0
passing run on 4.0. http://jenkins.hazelcast.com/view/hot-restart/job/hot-v-clusterShutdown/47/console

**Comment by Danny-Hazelcast** [comment]
and its an inconsistency between frozen and passive
