### ISSUE TITLE
Test failure: AdvancedNetworkingClientCommunicationIntegrationTest.testClientConnectionToEndpoints

### ISSUE THREAD

**Issue by hakanmemisoglu** [hazelcast/hazelcast#18278]
Failure in: http://jenkins.hazelcast.com/view/Hazelcast/job/Hazelcast-4.master-nightly/759/consoleFull

Related test output: 
```
22:37:58 [ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 303.352 s <<< FAILURE! - in com.hazelcast.client.impl.connection.tcp.AdvancedNetworkingClientCommunicationIntegrationTest
22:37:58 [ERROR] testClientConnectionToEndpoints(com.hazelcast.client.impl.connection.tcp.AdvancedNetworkingClientCommunicationIntegrationTest)  Time elapsed: 303.352 s  <<< ERROR!
22:37:58 org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
22:37:58 	at java.lang.Thread.sleep(Native Method)
22:37:58 	at com.hazelcast.client.impl.connection.tcp.WaitStrategy.sleep(WaitStrategy.java:75)
22:37:58 	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.doConnectToCandidateCluster(TcpClientConnectionManager.java:501)
22:37:58 	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.doConnectToCluster(TcpClientConnectionManager.java:406)
22:37:58 	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.connectToCluster(TcpClientConnectionManager.java:367)
22:37:58 	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.start(TcpClientConnectionManager.java:316)
22:37:58 	at com.hazelcast.client.impl.clientside.HazelcastClientInstanceImpl.start(HazelcastClientInstanceImpl.java:369)
22:37:58 	at com.hazelcast.client.HazelcastClient.constructHazelcastClient(HazelcastClient.java:460)
22:37:58 	at com.hazelcast.client.HazelcastClient.newHazelcastClientInternal(HazelcastClient.java:416)
22:37:58 	at com.hazelcast.client.HazelcastClient.newHazelcastClient(HazelcastClient.java:136)
22:37:58 	at com.hazelcast.client.impl.connection.tcp.AdvancedNetworkingClientCommunicationIntegrationTest.createClient(AdvancedNetworkingClientCommunicationIntegrationTest.java:61)
22:37:58 	at com.hazelcast.client.impl.connection.tcp.AdvancedNetworkingClientCommunicationIntegrationTest.testClientConnectFailOnPort(AdvancedNetworkingClientCommunicationIntegrationTest.java:66)
22:37:58 	at com.hazelcast.client.impl.connection.tcp.AdvancedNetworkingClientCommunicationIntegrationTest.testClientConnectionToEndpoints(AdvancedNetworkingClientCommunicationIntegrationTest.java:51)
22:37:58 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
22:37:58 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
22:37:58 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
22:37:58 	at java.lang.reflect.Method.invoke(Method.java:498)
22:37:58 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
22:37:58 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
22:37:58 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
22:37:58 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
22:37:58 	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
22:37:58 	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
22:37:58 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
22:37:58 	at java.lang.Thread.run(Thread.java:748)
22:37:58 
```

**Comment by hakanmemisoglu** [comment]
```
11:48:52,905  WARN |testClientConnectionToEndpoints| - [ClientConnectionManager] testClientConnectionToEndpoints - hz.client_2 [dev] [4.2-SNAPSHOT] Exception during initial connection to [127.0.0.1]:11000: com.hazelcast.spi.exception.TargetDisconnectedException: Exception in ClientConnection{alive=true, connectionId=5, channel=NioChannel{/127.0.0.1:56824->/127.0.0.1:11000}, remoteAddress=null, lastReadTime=2021-02-24 11:48:52.879, lastWriteTime=2021-02-24 11:48:47.878, closedTime=never, connected server version=null}, thread=hz.hz.client_2.IO.thread-in-0
11:48:52,908  WARN |testClientConnectionToEndpoints| - [ClientConnectionManager] testClientConnectionToEndpoints - hz.client_2 [dev] [4.2-SNAPSHOT] Unable to get live cluster connection, retry in 1214 ms, attempt: 5, cluster connect timeout: 9223372036854775807 ms, max backoff: 30000 ms
11:48:54,128  INFO |testClientConnectionToEndpoints| - [ClientConnectionManager] testClientConnectionToEndpoints - hz.client_2 [dev] [4.2-SNAPSHOT] Trying to connect to [127.0.0.1]:11000
11:48:54,130  WARN |testClientConnectionToEndpoints| - [TcpServerConnection] hz.affectionate_bohr.IO.thread-in-0 - [127.0.0.1]:11000 [dev] [4.2-SNAPSHOT] Connection[id=6, /127.0.0.1:11000->/127.0.0.1:56825, qualifier=EndpointQualifier{type='MEMBER'}, endpoint=null, alive=false, connectionType=NONE, planeIndex=-1] closed. Reason: Exception in Connection[id=6, /127.0.0.1:11000->/127.0.0.1:56825, qualifier=EndpointQualifier{type='MEMBER'}, endpoint=null, alive=true, connectionType=NONE, planeIndex=-1], thread=hz.affectionate_bohr.IO.thread-in-0```

The part `cluster connect timeout: 9223372036854775807 ms`  looks problematic.

**Comment by hakanmemisoglu** [comment]
Result of `git bisect`:
```
8efe09b3c38492447b19ca9de93e55d8f6431639 is the first bad commit
```

https://github.com/hazelcast/hazelcast/commit/8efe09b3c38492447b19ca9de93e55d8f6431639

**Comment by mdumandag** [comment]
For reference, this and other client-related timeouts are happening because we decided to set cluster connect timeout to infinite by default on https://github.com/hazelcast/hazelcast/pull/18094, so that on startup or reconnection, the client will not give up trying to connect to the candidate clusters.
