### ISSUE TITLE
When Discovery IP address is return as null Hazelcast throw NPE 

### ISSUE THREAD

**Issue by bmistry13** [hazelcast/hazelcast#18319]
**Describe the bug**
When discovery-strategy returns NULL as bind and public address NULL, Hazelcast is throwing NPE, rather than throwing  NPE throw an appropriate error message. 

 [org.bitsofinfo.hazelcast.spi.docker.swarm.dnsrr.discovery.DockerDNSRRDiscoveryStrategy](https://github.com/bitsofinfo/hazelcast-docker-swarm-discovery-spi/blob/master/src/main/java/org/bitsofinfo/hazelcast/spi/docker/swarm/dnsrr/DockerDNSRRMemberAddressProvider.java#L42) is used and bindaddress is NULL return.  

```
java.lang.NullPointerException: null
        at com.hazelcast.instance.impl.DelegatingAddressPicker.validatePublicAddress(DelegatingAddressPicker.java:83)
        at com.hazelcast.instance.impl.DelegatingAddressPicker.pickAddressFromNetworkConfig(DelegatingAddressPicker.java:102)
        at com.hazelcast.instance.impl.DelegatingAddressPicker.pickAddress(DelegatingAddressPicker.java:73)
        at com.hazelcast.instance.impl.Node.<init>(Node.java:220)
        at com.hazelcast.instance.impl.HazelcastInstanceImpl.createNode(HazelcastInstanceImpl.java:148)
        at com.hazelcast.instance.impl.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:117)
        at com.hazelcast.instance.impl.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:211)
        at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:190)
```

Hazelcast code:

```
NetworkConfig networkConfig = config.getNetworkConfig();
bindAddress = memberAddressProvider.getBindAddress();  // CHECK HERE IF NULL
publicAddress = memberAddressProvider.getPublicAddress(); // CHECK HERE IF NULL
validatePublicAddress(publicAddress);  


private void validatePublicAddress(InetSocketAddress inetSocketAddress) {
    InetAddress address = inetSocketAddress.getAddress();   //  THIS THROWS NPE 
    if (address == null) {
        throw new InvalidConfigurationException("Cannot resolve address '" + inetSocketAddress + "'");
    }
    if (address.isAnyLocalAddress()) {
        throw new InvalidConfigurationException("Member address provider has to return a specific public address "
                + "to broadcast to other members.");
    }
}
```

**Expected behavior**
The expectation is **DelegatingAddressPicker** would validate input and return appropriate error "can not bind to NULL address.

**To Reproduce**

Implement NULL discovery strategy and return NULL bind-address and public address.

**Additional context**

**Comment by mmedenjak** [comment]
Thank you for your report @bmistry13 ! I'll add this to a future release as I don't see this as critical and we're about to release 4.2 soon.

**Comment by bmistry13** [comment]
@mmedenjak ,  This is just an enhancement bug and you can fix it in the next release.  Thanks for taking a look!
