### ISSUE TITLE
MapIndexScanExecTest.testScan

### ISSUE THREAD

**Issue by sancar** [hazelcast/hazelcast#18310]
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/4073/

Error Message
Cannot use the index "index" of the IMap "map" due to concurrent migration, or because index creation is still in progress
Stacktrace
```
com.hazelcast.sql.impl.QueryException: Cannot use the index "index" of the IMap "map" due to concurrent migration, or because index creation is still in progress
	at com.hazelcast.sql.impl.QueryException.error(QueryException.java:55)
	at com.hazelcast.sql.impl.exec.scan.index.MapIndexScanExec.invalidIndexStamp(MapIndexScanExec.java:133)
	at com.hazelcast.sql.impl.exec.scan.index.MapIndexScanExec.validateConsistency(MapIndexScanExec.java:128)
	at com.hazelcast.sql.impl.exec.scan.AbstractMapScanExec.advance0(AbstractMapScanExec.java:130)
	at com.hazelcast.sql.impl.exec.AbstractExec.advance(AbstractExec.java:58)
	at com.hazelcast.sql.impl.exec.scan.index.MapIndexScanExecTest.executeScan(MapIndexScanExecTest.java:516)
	at com.hazelcast.sql.impl.exec.scan.index.MapIndexScanExecTest.executeScan(MapIndexScanExecTest.java:467)
	at com.hazelcast.sql.impl.exec.scan.index.MapIndexScanExecTest.testScan(MapIndexScanExecTest.java:133)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by mmedenjak** [comment]
@petrpleshachkov can you take a look? Is this related to the latest changes to the safe state?

**Comment by mmedenjak** [comment]
@devozerov @petrpleshachkov can you take a look?
