### ISSUE TITLE
Continuous reconnection when Hazelcast placed behind a proxy

### ISSUE THREAD

**Issue by alparslanavci** [hazelcast/hazelcast#18320]
When a member is disconnected from the cluster, the alive cluster members still try to reconnect if the dying member connection is not closed explicitly. This is done [here](https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/internal/server/tcp/TcpServerContext.java#L182) by checking if the disconnection cause is `null` or not.

However, in some cases, the connection is explicitly closed with a cause (such as `Connection reset by peer` or `Remote socket closed!`). Moreover, a new connection can still be established if the member is placed behind a proxy. This scenario might end up with opening & closing connections continuously. 

A similar use case happens in Hazelcast cluster setup with Istio Service Mesh. Just follow the embedded scenario [in this guide](https://guides.hazelcast.org/istio/) and delete a pod to reproduce the issue. The logs below are produced in this setup:

```
2021-03-01 15:11:27.434  INFO 1 --- [.IO.thread-in-0] c.h.internal.nio.tcp.TcpIpConnection     : [172.17.0.6]:5701 [dev] [4.0.2] Connection[id=7, /172.17.0.6:34111->/172.17.0.7:5701, qualifier=null, endpoint=[172.17.0.7]:5701, alive=false, connectionType=MEMBER] closed. Reason: Connection closed by the other side
2021-03-01 15:11:27.442  INFO 1 --- [.IO.thread-in-1] c.h.internal.nio.tcp.TcpIpConnection     : [172.17.0.6]:5701 [dev] [4.0.2] Connection[id=8, /127.0.0.1:5701->/127.0.0.1:54516, qualifier=null, endpoint=[172.17.0.7]:5701, alive=false, connectionType=MEMBER] closed. Reason: Connection closed by the other side
2021-03-01 15:11:27.449  INFO 1 --- [cached.thread-2] c.h.internal.nio.tcp.TcpIpConnector      : [172.17.0.6]:5701 [dev] [4.0.2] Connecting to /172.17.0.7:5701, timeout: 10000, bind-any: true
2021-03-01 15:11:27.480  WARN 1 --- [.IO.thread-in-2] c.h.internal.nio.tcp.TcpIpConnection     : [172.17.0.6]:5701 [dev] [4.0.2] Connection[id=9, /172.17.0.6:44813->/172.17.0.7:5701, qualifier=null, endpoint=[172.17.0.7]:5701, alive=false, connectionType=NONE] closed. Reason: Exception in Connection[id=9, /172.17.0.6:44813->/172.17.0.7:5701, qualifier=null, endpoint=[172.17.0.7]:5701, alive=true, connectionType=NONE], thread=hz.stupefied_visvesvaraya.IO.thread-in-2

java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[na:1.8.0_275]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[na:1.8.0_275]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_275]
	at sun.nio.ch.IOUtil.read(IOUtil.java:197) ~[na:1.8.0_275]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:379) ~[na:1.8.0_275]
	at com.hazelcast.internal.networking.nio.NioInboundPipeline.process(NioInboundPipeline.java:119) ~[hazelcast-all-4.0.2.jar:4.0.2]
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKey(NioThread.java:382) [hazelcast-all-4.0.2.jar:4.0.2]
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKeys(NioThread.java:367) [hazelcast-all-4.0.2.jar:4.0.2]
	at com.hazelcast.internal.networking.nio.NioThread.selectLoop(NioThread.java:293) [hazelcast-all-4.0.2.jar:4.0.2]
	at com.hazelcast.internal.networking.nio.NioThread.run(NioThread.java:248) [hazelcast-all-4.0.2.jar:4.0.2]

2021-03-01 15:11:27.487  INFO 1 --- [cached.thread-2] c.h.internal.nio.tcp.TcpIpConnector      : [172.17.0.6]:5701 [dev] [4.0.2] Connecting to /172.17.0.7:5701, timeout: 10000, bind-any: true
2021-03-01 15:11:27.492  WARN 1 --- [.IO.thread-in-0] c.h.internal.nio.tcp.TcpIpConnection     : [172.17.0.6]:5701 [dev] [4.0.2] Connection[id=10, /172.17.0.6:41725->/172.17.0.7:5701, qualifier=null, endpoint=[172.17.0.7]:5701, alive=false, connectionType=NONE] closed. Reason: Exception in Connection[id=10, /172.17.0.6:41725->/172.17.0.7:5701, qualifier=null, endpoint=[172.17.0.7]:5701, alive=true, connectionType=NONE], thread=hz.stupefied_visvesvaraya.IO.thread-in-0

java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[na:1.8.0_275]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[na:1.8.0_275]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_275]
	at sun.nio.ch.IOUtil.read(IOUtil.java:197) ~[na:1.8.0_275]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:379) ~[na:1.8.0_275]
	at com.hazelcast.internal.networking.nio.NioInboundPipeline.process(NioInboundPipeline.java:119) ~[hazelcast-all-4.0.2.jar:4.0.2]
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKey(NioThread.java:382) [hazelcast-all-4.0.2.jar:4.0.2]
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKeys(NioThread.java:367) [hazelcast-all-4.0.2.jar:4.0.2]
	at com.hazelcast.internal.networking.nio.NioThread.selectLoop(NioThread.java:293) [hazelcast-all-4.0.2.jar:4.0.2]
	at com.hazelcast.internal.networking.nio.NioThread.run(NioThread.java:248) [hazelcast-all-4.0.2.jar:4.0.2]

2021-03-01 15:11:27.493  INFO 1 --- [cached.thread-2] c.h.internal.nio.tcp.TcpIpConnector      : [172.17.0.6]:5701 [dev] [4.0.2] Connecting to /172.17.0.7:5701, timeout: 10000, bind-any: true
2021-03-01 15:11:27.498  WARN 1 --- [.IO.thread-in-1] c.h.internal.nio.tcp.TcpIpConnection     : [172.17.0.6]:5701 [dev] [4.0.2] Connection[id=11, /172.17.0.6:52527->/172.17.0.7:5701, qualifier=null, endpoint=[172.17.0.7]:5701, alive=false, connectionType=NONE] closed. Reason: Exception in Connection[id=11, /172.17.0.6:52527->/172.17.0.7:5701, qualifier=null, endpoint=[172.17.0.7]:5701, alive=true, connectionType=NONE], thread=hz.stupefied_visvesvaraya.IO.thread-in-1

java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[na:1.8.0_275]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[na:1.8.0_275]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_275]
	at sun.nio.ch.IOUtil.read(IOUtil.java:197) ~[na:1.8.0_275]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:379) ~[na:1.8.0_275]
	at com.hazelcast.internal.networking.nio.NioInboundPipeline.process(NioInboundPipeline.java:119) ~[hazelcast-all-4.0.2.jar:4.0.2]
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKey(NioThread.java:382) [hazelcast-all-4.0.2.jar:4.0.2]
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKeys(NioThread.java:367) [hazelcast-all-4.0.2.jar:4.0.2]
	at com.hazelcast.internal.networking.nio.NioThread.selectLoop(NioThread.java:293) [hazelcast-all-4.0.2.jar:4.0.2]
	at com.hazelcast.internal.networking.nio.NioThread.run(NioThread.java:248) [hazelcast-all-4.0.2.jar:4.0.2]

2021-03-01 15:11:27.499  INFO 1 --- [cached.thread-2] c.h.internal.nio.tcp.TcpIpConnector      : [172.17.0.6]:5701 [dev] [4.0.2] Connecting to /172.17.0.7:5701, timeout: 10000, bind-any: true
2021-03-01 15:11:27.505  WARN 1 --- [.IO.thread-in-2] c.h.internal.nio.tcp.TcpIpConnection     : [172.17.0.6]:5701 [dev] [4.0.2] Connection[id=12, /172.17.0.6:56057->/172.17.0.7:5701, qualifier=null, endpoint=[172.17.0.7]:5701, alive=false, connectionType=NONE] closed. Reason: Exception in Connection[id=12, /172.17.0.6:56057->/172.17.0.7:5701, qualifier=null, endpoint=[172.17.0.7]:5701, alive=true, connectionType=NONE], thread=hz.stupefied_visvesvaraya.IO.thread-in-2

java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[na:1.8.0_275]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[na:1.8.0_275]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_275]
	at sun.nio.ch.IOUtil.read(IOUtil.java:197) ~[na:1.8.0_275]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:379) ~[na:1.8.0_275]
	at com.hazelcast.internal.networking.nio.NioInboundPipeline.process(NioInboundPipeline.java:119) ~[hazelcast-all-4.0.2.jar:4.0.2]
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKey(NioThread.java:382) [hazelcast-all-4.0.2.jar:4.0.2]
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKeys(NioThread.java:367) [hazelcast-all-4.0.2.jar:4.0.2]
	at com.hazelcast.internal.networking.nio.NioThread.selectLoop(NioThread.java:293) [hazelcast-all-4.0.2.jar:4.0.2]
	at com.hazelcast.internal.networking.nio.NioThread.run(NioThread.java:248) [hazelcast-all-4.0.2.jar:4.0.2]

2021-03-01 15:11:27.506  INFO 1 --- [cached.thread-2] c.h.internal.nio.tcp.TcpIpConnector      : [172.17.0.6]:5701 [dev] [4.0.2] Connecting to /172.17.0.7:5701, timeout: 10000, bind-any: true
2021-03-01 15:11:27.510  WARN 1 --- [.IO.thread-in-0] c.h.internal.nio.tcp.TcpIpConnection     : [172.17.0.6]:5701 [dev] [4.0.2] Connection[id=13, /172.17.0.6:38717->/172.17.0.7:5701, qualifier=null, endpoint=[172.17.0.7]:5701, alive=false, connectionType=NONE] closed. Reason: Exception in Connection[id=13, /172.17.0.6:38717->/172.17.0.7:5701, qualifier=null, endpoint=[172.17.0.7]:5701, alive=true, connectionType=NONE], thread=hz.stupefied_visvesvaraya.IO.thread-in-0

java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[na:1.8.0_275]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[na:1.8.0_275]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_275]
	at sun.nio.ch.IOUtil.read(IOUtil.java:197) ~[na:1.8.0_275]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:379) ~[na:1.8.0_275]
	at com.hazelcast.internal.networking.nio.NioInboundPipeline.process(NioInboundPipeline.java:119) ~[hazelcast-all-4.0.2.jar:4.0.2]
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKey(NioThread.java:382) [hazelcast-all-4.0.2.jar:4.0.2]
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKeys(NioThread.java:367) [hazelcast-all-4.0.2.jar:4.0.2]
	at com.hazelcast.internal.networking.nio.NioThread.selectLoop(NioThread.java:293) [hazelcast-all-4.0.2.jar:4.0.2]
	at com.hazelcast.internal.networking.nio.NioThread.run(NioThread.java:248) [hazelcast-all-4.0.2.jar:4.0.2]

2021-03-01 15:11:27.513  INFO 1 --- [cached.thread-2] c.h.internal.nio.tcp.TcpIpConnector      : [172.17.0.6]:5701 [dev] [4.0.2] Connecting to /172.17.0.7:5701, timeout: 10000, bind-any: true
2021-03-01 15:11:27.547  WARN 1 --- [.IO.thread-in-1] c.h.internal.nio.tcp.TcpIpConnection     : [172.17.0.6]:5701 [dev] [4.0.2] Connection[id=14, /172.17.0.6:43179->/172.17.0.7:5701, qualifier=null, endpoint=[172.17.0.7]:5701, alive=false, connectionType=NONE] closed. Reason: Exception in Connection[id=14, /172.17.0.6:43179->/172.17.0.7:5701, qualifier=null, endpoint=[172.17.0.7]:5701, alive=true, connectionType=NONE], thread=hz.stupefied_visvesvaraya.IO.thread-in-1

java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[na:1.8.0_275]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[na:1.8.0_275]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_275]
	at sun.nio.ch.IOUtil.read(IOUtil.java:197) ~[na:1.8.0_275]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:379) ~[na:1.8.0_275]
	at com.hazelcast.internal.networking.nio.NioInboundPipeline.process(NioInboundPipeline.java:119) ~[hazelcast-all-4.0.2.jar:4.0.2]
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKey(NioThread.java:382) [hazelcast-all-4.0.2.jar:4.0.2]
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKeys(NioThread.java:367) [hazelcast-all-4.0.2.jar:4.0.2]
	at com.hazelcast.internal.networking.nio.NioThread.selectLoop(NioThread.java:293) [hazelcast-all-4.0.2.jar:4.0.2]
	at com.hazelcast.internal.networking.nio.NioThread.run(NioThread.java:248) [hazelcast-all-4.0.2.jar:4.0.2]

2021-03-01 15:11:27.557  INFO 1 --- [cached.thread-3] c.h.internal.nio.tcp.TcpIpConnector      : [172.17.0.6]:5701 [dev] [4.0.2] Connecting to /172.17.0.7:5701, timeout: 10000, bind-any: true
2021-03-01 15:11:27.564  INFO 1 --- [.IO.thread-in-2] c.h.internal.nio.tcp.TcpIpConnection     : [172.17.0.6]:5701 [dev] [4.0.2] Connection[id=15, /172.17.0.6:34923->/172.17.0.7:5701, qualifier=null, endpoint=[172.17.0.7]:5701, alive=false, connectionType=NONE] closed. Reason: Connection closed by the other side
2021-03-01 15:11:27.568  INFO 1 --- [cached.thread-1] c.h.internal.nio.tcp.TcpIpConnector      : [172.17.0.6]:5701 [dev] [4.0.2] Connecting to /172.17.0.7:5701, timeout: 10000, bind-any: true
2021-03-01 15:11:27.574  INFO 1 --- [.IO.thread-in-0] c.h.internal.nio.tcp.TcpIpConnection     : [172.17.0.6]:5701 [dev] [4.0.2] Connection[id=16, /172.17.0.6:44791->/172.17.0.7:5701, qualifier=null, endpoint=[172.17.0.7]:5701, alive=false, connectionType=NONE] closed. Reason: Connection closed by the other side
2021-03-01 15:11:27.583  INFO 1 --- [cached.thread-6] c.h.internal.nio.tcp.TcpIpConnector      : [172.17.0.6]:5701 [dev] [4.0.2] Connecting to /172.17.0.7:5701, timeout: 10000, bind-any: true
2021-03-01 15:11:27.590  INFO 1 --- [.IO.thread-in-1] c.h.internal.nio.tcp.TcpIpConnection     : [172.17.0.6]:5701 [dev] [4.0.2] Connection[id=17, /172.17.0.6:45355->/172.17.0.7:5701, qualifier=null, endpoint=[172.17.0.7]:5701, alive=false, connectionType=NONE] closed. Reason: Connection closed by the other side
2021-03-01 15:11:27.590  INFO 1 --- [cached.thread-3] c.h.internal.nio.tcp.TcpIpConnector      : [172.17.0.6]:5701 [dev] [4.0.2] Connecting to /172.17.0.7:5701, timeout: 10000, bind-any: true
2021-03-01 15:11:27.594  INFO 1 --- [.IO.thread-in-2] c.h.internal.nio.tcp.TcpIpConnection     : [172.17.0.6]:5701 [dev] [4.0.2] Connection[id=18, /172.17.0.6:34205->/172.17.0.7:5701, qualifier=null, endpoint=[172.17.0.7]:5701, alive=false, connectionType=NONE] closed. Reason: Connection closed by the other side
2021-03-01 15:11:27.595  INFO 1 --- [cached.thread-2] c.h.internal.nio.tcp.TcpIpConnector      : [172.17.0.6]:5701 [dev] [4.0.2] Connecting to /172.17.0.7:5701, timeout: 10000, bind-any: true
2021-03-01 15:11:27.598  INFO 1 --- [.IO.thread-in-0] c.h.internal.nio.tcp.TcpIpConnection     : [172.17.0.6]:5701 [dev] [4.0.2] Connection[id=19, /172.17.0.6:55751->/172.17.0.7:5701, qualifier=null, endpoint=[172.17.0.7]:5701, alive=false, connectionType=NONE] closed. Reason: Connection closed by the other side
2021-03-01 15:11:27.599  INFO 1 --- [cached.thread-3] c.h.internal.nio.tcp.TcpIpConnector      : [172.17.0.6]:5701 [dev] [4.0.2] Connecting to /172.17.0.7:5701, timeout: 10000, bind-any: true
2021-03-01 15:11:27.613  INFO 1 --- [.IO.thread-in-1] c.h.internal.nio.tcp.TcpIpConnection     : [172.17.0.6]:5701 [dev] [4.0.2] Connection[id=20, /172.17.0.6:38683->/172.17.0.7:5701, qualifier=null, endpoint=[172.17.0.7]:5701, alive=false, connectionType=NONE] closed. Reason: Connection closed by the other side
2021-03-01 15:11:27.614  INFO 1 --- [cached.thread-6] c.h.internal.nio.tcp.TcpIpConnector      : [172.17.0.6]:5701 [dev] [4.0.2] Connecting to /172.17.0.7:5701, timeout: 10000, bind-any: true
2021-03-01 15:11:27.616  INFO 1 --- [.IO.thread-in-2] c.h.internal.nio.tcp.TcpIpConnection     : [172.17.0.6]:5701 [dev] [4.0.2] Connection[id=21, /172.17.0.6:53979->/172.17.0.7:5701, qualifier=null, endpoint=[172.17.0.7]:5701, alive=false, connectionType=NONE] closed. Reason: Connection closed by the other side
2021-03-01 15:11:27.617  INFO 1 --- [cached.thread-3] c.h.internal.nio.tcp.TcpIpConnector      : [172.17.0.6]:5701 [dev] [4.0.2] Connecting to /172.17.0.7:5701, timeout: 10000, bind-any: true
2021-03-01 15:11:27.619  INFO 1 --- [.IO.thread-in-0] c.h.internal.nio.tcp.TcpIpConnection     : [172.17.0.6]:5701 [dev] [4.0.2] Connection[id=22, /172.17.0.6:54381->/172.17.0.7:5701, qualifier=null, endpoint=[172.17.0.7]:5701, alive=false, connectionType=NONE] closed. Reason: Connection closed by the other side
```

After this moment, more than 5400 connections opened & closed in a few minutes.

**Comment by sertugkaya** [comment]
Same with ZD 6695

**Comment by lechen26** [comment]
Any progress here? 10x!

**Comment by Holmistr** [comment]
Hi @lechen26 ,

we haven't worked on it yet as our schedule for the next release is pretty tight but we want to take a look this issue as part of the development period. Let me go back to the team and try getting more insights and estimations.

**Comment by jbartok** [comment]
The root cause of this problem seems to be that, due to the proxy present, not being able to connect from one member to another doesn't behave as expected. 

The expected behaviour is that a connection attempt is made, it fails, another one is made, it fails and after a certain number of attempts we give up and behave accordingly. 

What happens here instead is that a connection attempt is made, it succeeds connecting to the proxy, the proxy tries to connect to the other side, fails, drops the incoming connection. So instead of an "attempt-fail, attempt-fail, ..." sequence of events we get "attempt-succeed-drop, attempt-succeed-drop, ..." sequence and that's not being handled correctly by the current code.

How easy (or not) it would be to handle both scenarios properly is still under investigation. I suspect the answer will be "not easy", but don't really know yet.
