### ISSUE TITLE
Flaky Map idle timeout evictions after upgrading from 3.12 -> 4.1

### ISSUE THREAD

**Issue by LarsKrogJensen** [hazelcast/hazelcast#18329]
**Describe the bug**
After upgrading hazelcast 3.12 to 4.1.1 a subtle/weird/flaky idle timeout evictions has been observed.

What makes it perhaps 'special' is that a map eviction listener is querying the map for some business logic, this has been working fine with 3.12 (see reproducers below)

The problem manifests as entries are not evicted, or evicted very very slowly.

IF the aggegation is removed from the listener callback issue goes away. 

With 4.2-beta the issue is much more apparent as hazelcast throws an NPE:

`12:43:18.948 [ForkJoinPool.commonPool-worker-9] ERROR c.h.map.impl.query.QueryOperation - [10.192.35.218]:5701 [hz4-repro] [4.2-BETA-1] null
java.lang.NullPointerException: null
	at com.hazelcast.map.impl.recordstore.AbstractEvictableRecordStore.accessRecord(AbstractEvictableRecordStore.java:184)
	at com.hazelcast.map.impl.recordstore.AbstractEvictableRecordStore.expireOrAccess(AbstractEvictableRecordStore.java:154)
	at com.hazelcast.map.impl.MapContainer.hasNotExpired(MapContainer.java:185)
	at com.hazelcast.internal.util.IterableUtil$2.hasNext(IterableUtil.java:93)
	at com.hazelcast.map.impl.query.ParallelAccumulationExecutor.accumulateParallel(ParallelAccumulationExecutor.java:80)
	at com.hazelcast.map.impl.query.ParallelAccumulationExecutor.execute(ParallelAccumulationExecutor.java:60)
	at com.hazelcast.map.impl.query.AggregationResultProcessor.populateResult(AggregationResultProcessor.java:40)
	at com.hazelcast.map.impl.query.AggregationResultProcessor.populateResult(AggregationResultProcessor.java:27)
` 

As this is a very subtle issue I spent a lot of time to condense the reproducer in before/after.

**Expected behavior**
Idle eviction to not be flaky

**To Reproduce**
Created a reproducer at:
https://github.com/LarsKrogJensen/hz4-idle-evict-repro

and a 3.12 comparison at:
https://github.com/LarsKrogJensen/hz3-idle-evict-ok

**Additional context**

Details are found in the reproducer repo,

**Comment by ahmetmircik** [comment]
I'll have a look, thanks for the report.

**Comment by LarsKrogJensen** [comment]
Let me know if reproducer needs more explanations

**Comment by ahmetmircik** [comment]
No, i think i can see the issue, prepared an initial fix for 4.2: https://github.com/hazelcast/hazelcast/pull/18334

**Comment by LarsKrogJensen** [comment]
any repo to try out a snapshot build?

**Comment by LarsKrogJensen** [comment]
I clone the branch to try it out, but fails:

17:38:51.630 [hz.boring_hodgkin.partition-operation.thread-5] ERROR c.h.map.impl.operation.SetOperation - [10.192.35.218]:5701 [hz4-repro] [4.2-SNAPSHOT] null
java.lang.ExceptionInInitializerError: null
	at com.hazelcast.map.impl.recordstore.expiry.ExpirySystem.createExpiryMetadata(ExpirySystem.java:129)
	at com.hazelcast.map.impl.recordstore.expiry.ExpirySystem.addExpirableKey(ExpirySystem.java:157)
	at com.hazelcast.map.impl.recordstore.expiry.ExpirySystem.addKeyIfExpirable(ExpirySystem.java:138)
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.putNewRecord(DefaultRecordStore.java:917)
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.putInternal(DefaultRecordStore.java:898)
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.set(DefaultRecordStore.java:818)
	at com.hazelcast.map.impl.operation.SetOperation.runInternal(SetOperation.java:40)
	at com.hazelcast.map.impl.operation.MapOperation.run(MapOperation.java:115)
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:189)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:272)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:248)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:213)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:175)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:139)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
Caused by: java.lang.IllegalArgumentException: Must be long type
	at java.base/java.util.concurrent.atomic.AtomicLongFieldUpdater$CASUpdater.<init>(AtomicLongFieldUpdater.java:415)
	at java.base/java.util.concurrent.atomic.AtomicLongFieldUpdater.newUpdater(AtomicLongFieldUpdater.java:95)
	at com.hazelcast.map.impl.recordstore.expiry.ExpiryMetadataImpl.<clinit>(ExpiryMetadataImpl.java:29)
	... 16 common frames omitted
