### ISSUE TITLE
java.lang.IllegalStateException: RaftEndpoint is not in the current committed member list

### ISSUE THREAD

**Issue by PotatoSpud** [hazelcast/hazelcast#18372]
**Describe the bug**
On trying to switch over to the new CPSubsystem.  Our clients appear to doing just fine but we do see the following on the cluster.  We were wondering if this is a problem and how to address it.  We see this warning throughout the day with spikes every hour. Do we switch back to using 3.12.10 until this is resolved or can trust going forward into production with this warning?  Many thanks
```
[4.1.1] RaftEndpoint{uuid='86d8f030-b3f2-4795-9aa8-d9c5881118ae'} is not in the current committed member list: [RaftEndpoint{uuid='59e0dbc5-f324-48e2-92b3-d056dcf10d50'}, RaftEndpoint{uuid='cc69a45e-def0-4f6b-9d4b-cc02cbd5ebdb'}, RaftEndpoint{uuid='f9a5f001-fd29-4ad6-90b6-7d1cfd3bef70'}] of CPGroupId{name='default', seed=0, groupId=1399}
java.lang.IllegalStateException: RaftEndpoint{uuid='86d8f030-b3f2-4795-9aa8-d9c5881118ae'} is not in the current committed member list: [RaftEndpoint{uuid='59e0dbc5-f324-48e2-92b3-d056dcf10d50'}, RaftEndpoint{uuid='cc69a45e-def0-4f6b-9d4b-cc02cbd5ebdb'}, RaftEndpoint{uuid='f9a5f001-fd29-4ad6-90b6-7d1cfd3bef70'}] of CPGroupId{name='default', seed=0, groupId=1399}
	at com.hazelcast.internal.util.Preconditions.checkState(Preconditions.java:368) ~[hazelcast-4.1.1.jar:4.1.1]
	at com.hazelcast.cp.internal.raftop.GetInitialRaftGroupMembersIfCurrentGroupMemberOp.run(GetInitialRaftGroupMembersIfCurrentGroupMemberOp.java:73) ~[hazelcast-4.1.1.jar:4.1.1]
	at com.hazelcast.cp.internal.NodeEngineRaftIntegration.runOperation(NodeEngineRaftIntegration.java:219) ~[hazelcast-4.1.1.jar:4.1.1]
	at com.hazelcast.cp.internal.raft.impl.RaftNodeImpl.runQuery(RaftNodeImpl.java:870) ~[hazelcast-4.1.1.jar:4.1.1]
	at com.hazelcast.cp.internal.raft.impl.task.QueryTask.handleAnyLocalRead(QueryTask.java:109) ~[hazelcast-4.1.1.jar:4.1.1]
	at com.hazelcast.cp.internal.raft.impl.task.QueryTask.handleLeaderLocalRead(QueryTask.java:98) ~[hazelcast-4.1.1.jar:4.1.1]
	at com.hazelcast.cp.internal.raft.impl.task.QueryTask.run(QueryTask.java:69) ~[hazelcast-4.1.1.jar:4.1.1]
	at com.hazelcast.cp.internal.NodeEngineRaftIntegration.execute(NodeEngineRaftIntegration.java:114) ~[hazelcast-4.1.1.jar:4.1.1]
	at com.hazelcast.cp.internal.raft.impl.RaftNodeImpl.query(RaftNodeImpl.java:443) ~[hazelcast-4.1.1.jar:4.1.1]
	at com.hazelcast.cp.internal.operation.RaftQueryOp.run(RaftQueryOp.java:89) ~[hazelcast-4.1.1.jar:4.1.1]```

**Expected behavior**
No such warnings under normal operations.

**To Reproduce**

Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. ...

**Additional context**
Hazelcast 4.1.1
3 hosts with 3 instances on each host(1 JVM).
```
 <cp-subsystem>
    <cp-member-count>9</cp-member-count>
    <group-size>3</group-size>
    <session-time-to-live-seconds>60</session-time-to-live-seconds>
    <session-heartbeat-interval-seconds>5</session-heartbeat-interval-seconds>
    <missing-cp-member-auto-removal-seconds>120</missing-cp-member-auto-removal-seconds>
    <fail-on-indeterminate-operation-state>false</fail-on-indeterminate-operation-state>
    <persistence-enabled>false</persistence-enabled>
    <base-dir>custom-cp-dir</base-dir>
    <data-load-timeout-seconds>30</data-load-timeout-seconds>
    <raft-algorithm>
      <leader-election-timeout-in-millis>2000</leader-election-timeout-in-millis>
      <leader-heartbeat-period-in-millis>5000</leader-heartbeat-period-in-millis>
      <max-missed-leader-heartbeat-count>5</max-missed-leader-heartbeat-count>
      <append-request-max-entry-count>50</append-request-max-entry-count>
      <commit-index-advance-count-to-snapshot>1000</commit-index-advance-count-to-snapshot>
      <uncommitted-entry-count-to-reject-new-appends>100</uncommitted-entry-count-to-reject-new-appends>
      <append-request-backoff-timeout-in-millis>100</append-request-backoff-timeout-in-millis>
    </raft-algorithm>
    <semaphores>
    </semaphores>
    <locks>
    </locks>
  </cp-subsystem>
```
<!--
Add any other context about the problem here.

Common details that we're often interested in:
- Detailed description of the steps to reproduce your issue
- Logs and stack traces, if available
- Hazelcast version that you use (e.g. 3.4, also specify whether it is a minor release or the latest snapshot)
- If available, integration module versions (e.g. Tomcat, Jetty, Spring, Hibernate). Also, include their detailed configuration information such as web.xml, Hibernate configuration and `context.xml` for Spring
- Cluster size, i.e. the number of Hazelcast cluster members
- Number of the clients
- Version of Java. It is also helpful to mention the JVM parameters
- Operating system. If it is Linux, kernel version is helpful
- Unit test with the `hazelcast.xml` file. If you could include a unit test which reproduces your issue, we would be grateful
-->

**Comment by sancar** [comment]
Hi, 
From the logs, I understand that there is a 4th member. I wonder in which state that is in. 

Can you check if `86d8f030-b3f2-4795-9aa8-d9c5881118ae'` is in the member list or not from the logs?

The member list log looks like following:
```
Members {size:3, ver:3} [
	Member [192.168.1.2]:5701 - fa17979d-fa68-4b20-aba1-88377a598c72 this
	Member [192.168.1.2]:5702 - 84475acd-8f7f-4ed3-9a69-a14e20728c57
	Member [192.168.1.2]:5703 - 5e2817a4-3985-4550-8da7-4c58d233aff2
]
```

We can also check if it is reported as a part of CP Member Groups, which should look like following: 
```
CP Group Members {groupId: METADATA(0), size:3, term:0, logIndex:0} [
	CPMember{uuid=84475acd-8f7f-4ed3-9a69-a14e20728c57, address=[192.168.1.2]:5702}
	CPMember{uuid=fa17979d-fa68-4b20-aba1-88377a598c72, address=[192.168.1.2]:5701} - FOLLOWER this
	CPMember{uuid=5e2817a4-3985-4550-8da7-4c58d233aff2, address=[192.168.1.2]:5703}
]
```

And can you also share what is your CP Member count ?
`cpSubsystemConfig.setCPMemberCount(3);`

**Comment by PotatoSpud** [comment]
We are configuring the CP system with:
```
 <cp-subsystem>
    <cp-member-count>9</cp-member-count>
    <group-size>3</group-size>
    <session-time-to-live-seconds>60</session-time-to-live-seconds>
    <session-heartbeat-interval-seconds>5</session-heartbeat-interval-seconds>
    <missing-cp-member-auto-removal-seconds>120</missing-cp-member-auto-removal-seconds>
    <fail-on-indeterminate-operation-state>false</fail-on-indeterminate-operation-state>
    <persistence-enabled>false</persistence-enabled>
    <base-dir>custom-cp-dir</base-dir>
    <data-load-timeout-seconds>30</data-load-timeout-seconds>
    <raft-algorithm>
      <leader-election-timeout-in-millis>2000</leader-election-timeout-in-millis>
      <leader-heartbeat-period-in-millis>5000</leader-heartbeat-period-in-millis>
      <max-missed-leader-heartbeat-count>5</max-missed-leader-heartbeat-count>
      <append-request-max-entry-count>50</append-request-max-entry-count>
      <commit-index-advance-count-to-snapshot>1000</commit-index-advance-count-to-snapshot>
      <uncommitted-entry-count-to-reject-new-appends>100</uncommitted-entry-count-to-reject-new-appends>
      <append-request-backoff-timeout-in-millis>100</append-request-backoff-timeout-in-millis>
    </raft-algorithm>
    <semaphores>
    </semaphores>
    <locks>
    </locks>
  </cp-subsystem>
```

**Comment by PotatoSpud** [comment]
We see the following:
```
2021-03-10T16:06:12,808 [hz.ld-cs_azelt.e87b23de-062a-4149-bbd4-ccedbb875a27.partition-operation.thread-2] WARN s=indigo c=GetInitialRaftGroupMembersIfCurrentGroupMemberOp - [tvxind-lt-c10002-b.do.xcal.tv]:57003 [ld-cs_azelt] [4.1.1] RaftEndpoint{uuid='94a89c6b-0fed-49e1-8672-356c6a1bc992'} is not in the current committed member list: [RaftEndpoint{uuid='d5b573bb-b220-441c-b26a-27da3b404bc7'}, RaftEndpoint{uuid='6a85c9bc-4c4f-45e5-be8b-14a071b363b7'}, RaftEndpoint{uuid='fddee2ea-c81e-4e79-b315-d6eb89157824'}] of CPGroupId{name='default', seed=0, groupId=2856}
java.lang.IllegalStateException: RaftEndpoint{uuid='94a89c6b-0fed-49e1-8672-356c6a1bc992'} is not in the current committed member list: [RaftEndpoint{uuid='d5b573bb-b220-441c-b26a-27da3b404bc7'}, RaftEndpoint{uuid='6a85c9bc-4c4f-45e5-be8b-14a071b363b7'}, RaftEndpoint{uuid='fddee2ea-c81e-4e79-b315-d6eb89157824'}] of CPGroupId{name='default', seed=0, groupId=2856}
        at com.hazelcast.internal.util.Preconditions.checkState(Preconditions.java:368) ~[hazelcast-4.1.1.jar:4.1.1]
        at com.hazelcast.cp.internal.raftop.GetInitialRaftGroupMembersIfCurrentGroupMemberOp.run(GetInitialRaftGroupMembersIfCurrentGroupMemberOp.java:73) ~[hazelcast-4.1.1.jar:4.1.1]
        at com.hazelcast.cp.internal.NodeEngineRaftIntegration.runOperation(NodeEngineRaftIntegration.java:219) ~[hazelcast-4.1.1.jar:4.1.1]
        at com.hazelcast.cp.internal.raft.impl.RaftNodeImpl.runQuery(RaftNodeImpl.java:870) ~[hazelcast-4.1.1.jar:4.1.1]
        at com.hazelcast.cp.internal.raft.impl.task.QueryTask.handleAnyLocalRead(QueryTask.java:109) ~[hazelcast-4.1.1.jar:4.1.1]
        at com.hazelcast.cp.internal.raft.impl.task.QueryTask.handleLeaderLocalRead(QueryTask.java:98) ~[hazelcast-4.1.1.jar:4.1.1]
        at com.hazelcast.cp.internal.raft.impl.task.QueryTask.run(QueryTask.java:69) ~[hazelcast-4.1.1.jar:4.1.1]
        at com.hazelcast.cp.internal.NodeEngineRaftIntegration.execute(NodeEngineRaftIntegration.java:114) ~[hazelcast-4.1.1.jar:4.1.1]
        at com.hazelcast.cp.internal.raft.impl.RaftNodeImpl.query(RaftNodeImpl.java:443) ~[hazelcast-4.1.1.jar:4.1.1]
        at com.hazelcast.cp.internal.operation.RaftQueryOp.run(RaftQueryOp.java:89) ~[hazelcast-4.1.1.jar:4.1.1]
        at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:184) ~[hazelcast-4.1.1.jar:4.1.1]
        at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:256) ~[hazelcast-4.1.1.jar:4.1.1]
        at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:237) ~[hazelcast-4.1.1.jar:4.1.1]
        at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:452) ~[hazelcast-4.1.1.jar:4.1.1]
        at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:166) ~[hazelcast-4.1.1.jar:4.1.1]
        at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:136) ~[hazelcast-4.1.1.jar:4.1.1]
        at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123) ~[hazelcast-4.1.1.jar:4.1.1]
        at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) ~[hazelcast-4.1.1.jar:4.1.1]
```

**Comment by PotatoSpud** [comment]
Then:
```
        2021-03-10T16:07:15,917 [hz.ld-cs_azelt.e87b23de-062a-4149-bbd4-ccedbb875a27.partition-operation.thread-2] INFO s=indigo c=RaftSessionService - [tvxind-lt-c10002-b.do.xcal.tv]:57003 [ld-cs_azelt] [4.1.1] Created new session: 1870 in CPGroupId{name='default', seed=0, groupId=2856} for CLIENT -> [96.115.89.55]:32999
        2021-03-10T16:07:17,422 [pool-2-thread-1] INFO s=indigo c=AmazonWanPushReplication - sendReplication( name=QueueCheckManager_LastCheckTime.Long, type=LongEventType:{ name="LongSet" }, data=ReplicatedData:{ hash=0, key=Element:{ value.size=7 }, value=null } )::ld-cs_azelt::ld-cs_azelt_ae-va_loadtest
        2021-03-10T16:07:26,557 [hz.ld-cs_azelt.7418893d-3a61-46b0-bf1e-060bb2125d43.cached.thread-1] INFO s=indigo c=RaftGroupMembershipManager - [tvxind-lt-c10002-b.do.xcal.tv]:57002 [ld-cs_azelt] [4.1.1] Current leadership claims:
                CPMember{uuid=7418893d-3a61-46b0-bf1e-060bb2125d43, address=[tvxind-lt-c10002-b.do.xcal.tv]:57001} has 0,
                CPMember{uuid=d5b573bb-b220-441c-b26a-27da3b404bc7, address=[tvxind-lt-c10002-b.do.xcal.tv]:57003} has 1,
                CPMember{uuid=7051269b-068f-43d2-982f-0a3aa5182a7d, address=[tvxind-lt-c10001-b.do.xcal.tv]:57001} has 0,
                CPMember{uuid=94a89c6b-0fed-49e1-8672-356c6a1bc992, address=[tvxind-lt-c10001-b.do.xcal.tv]:57002} has 0,
                CPMember{uuid=f092f0e0-4461-4488-8ec3-e4a0dc15e035, address=[tvxind-lt-c10001-b.do.xcal.tv]:57003} has 0,
                CPMember{uuid=fddee2ea-c81e-4e79-b315-d6eb89157824, address=[tvxind-lt-c10003-b.do.xcal.tv]:57002} has 0,
                CPMember{uuid=6a85c9bc-4c4f-45e5-be8b-14a071b363b7, address=[tvxind-lt-c10003-b.do.xcal.tv]:57001} has 0,
                CPMember{uuid=e87b23de-062a-4149-bbd4-ccedbb875a27, address=[tvxind-lt-c10002-b.do.xcal.tv]:57002} has 0,
                CPMember{uuid=4543489a-8d91-4f1c-a06a-05e5e0c5d791, address=[tvxind-lt-c10003-b.do.xcal.tv]:57003} has 0 leaderships.
        2021-03-10T16:07:26,557 [hz.ld-cs_azelt.7418893d-3a61-46b0-bf1e-060bb2125d43.cached.thread-1] INFO s=indigo c=RaftGroupMembershipManager - [tvxind-lt-c10002-b.do.xcal.tv]:57002 [ld-cs_azelt] [4.1.1] Searching a candidate transfer leadership from CPMember{uuid=d5b573bb-b220-441c-b26a-27da3b404bc7, address=[tvxind-lt-c10002-b.do.xcal.tv]:57003} with 1 leaderships.
        2021-03-10T16:07:26,557 [hz.ld-cs_azelt.7418893d-3a61-46b0-bf1e-060bb2125d43.cached.thread-1] INFO s=indigo c=RaftGroupMembershipManager - [tvxind-lt-c10002-b.do.xcal.tv]:57002 [ld-cs_azelt] [4.1.1] No candidate could be found to get leadership from CPMember{uuid=d5b573bb-b220-441c-b26a-27da3b404bc7, address=[tvxind-lt-c10002-b.do.xcal.tv]:57003}. Skipping to next...
        2021-03-10T16:07:26,557 [hz.ld-cs_azelt.7418893d-3a61-46b0-bf1e-060bb2125d43.cached.thread-1] INFO s=indigo c=RaftGroupMembershipManager - [tvxind-lt-c10002-b.do.xcal.tv]:57002 [ld-cs_azelt] [4.1.1] CPGroup leadership balance is fine, cannot rebalance further...
```

**Comment by PotatoSpud** [comment]
There are 3 machines running one Java VM each.  There are 3 instances of Hazelcast within each Java VM, giving 9 Hazelcast instances in total.  Each is added as a CPMember, with 3 required to form a group.

**Comment by PotatoSpud** [comment]
The other two machines are complaining now with:
```
        2021-03-10T16:29:57,708 [hz.ld-cs_azelt.response-1] WARN s=indigo c=Invocation - [tvxind-lt-c10003-b.do.xcal.tv]:57001 [ld-cs_azelt] [4.1.1] Retrying invocation: Invocation{op=com.hazelcast.cp.internal.operation.RaftQueryOp{serviceName='hz:core:raft', identityHash=1735126131, partitionId=0, replicaIndex=0, callId=18098256, invocationTime=1615393797707 (2021-03-10 16:29:57.707), waitTimeout=-1, callTimeout=60000, op=com.hazelcast.cp.internal.raftop.metadata.GetRaftGroupOp{serviceName='hz:core:raft', targetGroupId=CPGroupId{name='default', seed=0, groupId=2856}}, groupId=CPGroupId{name='METADATA', seed=0, groupId=0}, policy=LEADER_LOCAL}, tryCount=250, tryPauseMillis=500, invokeCount=180, callTimeoutMillis=60000, firstInvocationTimeMs=1615393736553, firstInvocationTime='2021-03-10 16:28:56.553', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 00:00:00.000', target=[tvxind-lt-c10002-b.do.xcal.tv]:57001, pendingResponse={VOID}, backupsAcksExpected=-1, backupsAcksReceived=0, connection=Connection[id=242, /96.115.89.67:57001->/96.115.89.85:58915, qualifier=null, endpoint=[tvxind-lt-c10002-b.do.xcal.tv]:57001, alive=true, connectionType=MEMBER, planeIndex=0]}, Reason: com.hazelcast.cp.exception.NotLeaderException: null is not LEADER of CPGroupId{name='METADATA', seed=0, groupId=0}. Known leader is: N/A
```

**Comment by sancar** [comment]
One simple feedback I can give is that multiple instances of hazelcast in single jvm is unnecessary.
It will complicate the architecture and it will consume more memory with no benefit. Also it is harder to reason about what is going.

We need to understand how you ended up with the following logs: 
`{uuid='94a89c6b-0fed-49e1-8672-356c6a1bc992'} is not in the current committed member list` 
`{uuid='86d8f030-b3f2-4795-9aa8-d9c5881118ae'} is not in the current committed member list`

Is that something you can reproduce ? 
If not I would suggest tracing this uuid's backwards to see their story. Were they part of the CP Group before that ? Why did they left ? Any log contains these uuid's may help.

**Comment by PotatoSpud** [comment]
We also see this:
```
 WARN s=indigo c=RaftGroupMembershipManager - [tvxind-lt-c10003-b.do.xcal.tv]:57001 [ld-cs_azelt] [4.1.1] Could not get CP group info of CPGroupId{name='default', seed=0, groupId=2856}
com.hazelcast.cp.exception.NotLeaderException: RaftEndpoint{uuid='6a85c9bc-4c4f-45e5-be8b-14a071b363b7'} is not LEADER of CPGroupId{name='METADATA', seed=0, groupId=0}. Known leader is: N/A
	at com.hazelcast.cp.internal.operation.RaftQueryOp.run(RaftQueryOp.java:76) ~[hazelcast-4.1.1.jar:4.1.1]
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:184) ~[hazelcast-4.1.1.jar:4.1.1]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:256) ~[hazelcast-4.1.1.jar:4.1.1]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:237) ~[hazelcast-4.1.1.jar:4.1.1]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:213) ~[hazelcast-4.1.1.jar:4.1.1]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:160) ~[hazelcast-4.1.1.jar:4.1.1]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:138) ~[hazelcast-4.1.1.jar:4.1.1]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123) ~[hazelcast-4.1.1.jar:4.1.1]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) ~[hazelcast-4.1.1.jar:4.1.1]
```

**Comment by PotatoSpud** [comment]
The above is after restarting the node with issues yesterday and now we have this.  Our other test cluster is exhibiting the same behavior now.  So yes, this is reproducible.  I have tried to trace back to where the UID first issued a problem but there is nothing.

It seems that the Raft protocol being used is very fragile and unstable.  It does not appear to be able to recover either.

**Comment by sancar** [comment]
If this is reproducible, can you prepare a test suite that we can reproduce the problem ourselves?

**Comment by mmedenjak** [comment]
@PotatoSpud any updates - are you able to create a reproducer?

**Comment by PotatoSpud** [comment]
@mmedenjak Sorry for the delay.  We actually just moved on to a more flexible solution for use.  Please go ahead and close this issue.  Thank you
