### ISSUE TITLE
TransactionsWithWriteBehind_whenNoCoalescingQueueIsFullTest.throws_reached_max_size_exception_when_one_phase

### ISSUE THREAD

**Issue by mmedenjak** [hazelcast/hazelcast#18388]
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/4247

```
java.lang.AssertionError: Expected test to throw an instance of com.hazelcast.map.ReachedMaxSizeException
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.rules.ExpectedException.failDueToMissingException(ExpectedException.java:278)
	at org.junit.rules.ExpectedException.access$100(ExpectedException.java:111)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:264)
	at com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37)
	at com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:104)
	at com.hazelcast.test.metrics.MetricsRule$1.evaluate(MetricsRule.java:62)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at com.hazelcast.test.HazelcastParallelClassRunner.access$301(HazelcastParallelClassRunner.java:49)
	at com.hazelcast.test.HazelcastParallelClassRunner$TestRunner.run(HazelcastParallelClassRunner.java:162)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by ahmetmircik** [comment]
closed via https://github.com/hazelcast/hazelcast/pull/18401
