### ISSUE TITLE
ClientMapPartitionLostListenerTest.test_mapPartitionLostListener_invoked_fromOtherNode [HZ-1920]

### ISSUE THREAD

**Issue by sancar** [hazelcast/hazelcast#18381]
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/4229/testReport/junit/com.hazelcast.client.map/ClientMapPartitionLostListenerTest/test_mapPartitionLostListener_invoked_fromOtherNode/

Error Message
```
There is no proxy with name 9897e763-2d64-4143-87bf-dd81ec2be5b2 created (yet)
Stacktrace
java.lang.AssertionError: There is no proxy with name 9897e763-2d64-4143-87bf-dd81ec2be5b2 created (yet)
	at org.junit.Assert.fail(Assert.java:89)
	at com.hazelcast.client.map.ClientMapPartitionLostListenerTest$2.run(ClientMapPartitionLostListenerTest.java:172)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1248)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1350)
	at com.hazelcast.client.map.ClientMapPartitionLostListenerTest.assertProxyExistsEventually(ClientMapPartitionLostListenerTest.java:163)
	at com.hazelcast.client.map.ClientMapPartitionLostListenerTest.test_mapPartitionLostListener_invoked_fromOtherNode(ClientMapPartitionLostListenerTest.java:133)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

The test failure is not related to `PartitionLostListener`. 

A proxy created by the client is not propagated to the all the members within 2 minutes. 
Logs did not reveal much but this issue reminds of a similar one with event service registrations which is fixed by PreJoinOperations and invokeOnStableCluster here https://github.com/hazelcast/hazelcast/pull/11520
It might worth to investigate proxy creation and replication mechanism from the same perspective.

**Comment by sancar** [comment]
I was searching for a race condition where we can not create proxy, but I haven't found anything. Other than saying "this is caused by proxy creation relies on listeners, and listeners can be lost", I did not find anything else. Closing this as it is a known problem.

**Comment by ufukyilmaz** [comment]
Failed on unrelated pr builder run on 5.1.z, https://github.com/hazelcast/hazelcast/pull/21253: https://jenkins.hazelcast.com/job/Hazelcast-pr-builder/10925/

**Comment by olukas** [comment]
Failed on `5.1.z` branch on ZingJDK8: http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-ZingJDK8/87/testReport/com.hazelcast.client.map/ClientMapPartitionLostListenerTest/test_mapPartitionLostListener_invoked_fromOtherNode/

**Comment by frant-hartm** [comment]
PR builder on `5.2.z` https://github.com/hazelcast/hazelcast/pull/22556 
https://jenkins.hazelcast.com/job/Hazelcast-pr-builder/13815/

**Comment by krzysztofslusarski** [comment]
PR builder on ```5.2.z```: https://github.com/hazelcast/hazelcast/pull/22635
https://jenkins.hazelcast.com/job/Hazelcast-pr-builder/13919/

**Comment by Fly-Style** [comment]
Failed again : https://github.com/hazelcast/hazelcast/pull/22712#issuecomment-1305864326

**Comment by frant-hartm** [comment]
Failed in https://github.com/hazelcast/hazelcast/pull/22804#issuecomment-1313675683

**Comment by ramizdundar** [comment]
https://jenkins.hazelcast.com/job/Hazelcast-pr-builder/14348/testReport/junit/com.hazelcast.client.map/ClientMapPartitionLostListenerTest/test_mapPartitionLostListener_invoked_fromOtherNode/

**Comment by ramizdundar** [comment]
https://jenkins.hazelcast.com/job/Hazelcast-pr-builder/14618/testReport/junit/com.hazelcast.client.map/ClientMapPartitionLostListenerTest/test_mapPartitionLostListener_invoked_fromOtherNode/
