### ISSUE TITLE
member OOME issue using sql service queries possibly related to sqlStatement.setTimeoutMillis(sqlTimeoutMillis); 

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#18395]
i have hit a OOME issue using sql service queries,  

One instance of "java.util.concurrent.ForkJoinPool" loaded by "<system class loader>" occupies 1,225,264,424 (59.25%) bytes. The instance is referenced by com.hazelcast.sql.impl.worker.QueryOperationWorkerPool @ 0x804b5f68 , loaded by "sun.misc.Launcher$AppClassLoader @ 0x8001cc40". The memory is accumulated in one instance of "java.util.concurrent.ForkJoinPool$WorkQueue[]", loaded by "<system class loader>", which occupies 1,225,264,200 (59.25%) bytes.

```
Class Name | Shallow Heap | Retained Heap
-- | -- | --
java.util.concurrent.ForkJoinPool$WorkQueue[128] @ 0x821af6b8 | 528 | 1,225,264,200
workQueues java.util.concurrent.ForkJoinPool @ 0x804b5f88 | 56 | 1,225,264,424
<Java Local>, pool com.hazelcast.sql.impl.worker.QueryOperationWorkerPool$WorkerThread @ 0x81fd48f8 zealous_meninsky-query-fragment-thread-17 Thread | 136 | 11,248
<Java Local>, pool com.hazelcast.sql.impl.worker.QueryOperationWorkerPool$WorkerThread @ 0x81fd6868 zealous_meninsky-query-fragment-thread-7 Thread | 136 | 10,072
<Java Local>, pool com.hazelcast.sql.impl.worker.QueryOperationWorkerPool$WorkerThread @ 0x82000240 zealous_meninsky-query-fragment-thread-13 Thread | 136 | 7,248
<Java Local>, pool com.hazelcast.sql.impl.worker.QueryOperationWorkerPool$WorkerThread @ 0x82015c78 zealous_meninsky-query-fragment-thread-9 Thread | 136 | 7,240
<Java Local>, pool com.hazelcast.sql.impl.worker.QueryOperationWorkerPool$WorkerThread @ 0x820209a8 zealous_meninsky-query-fragment-thread-15 Thread | 136 | 10,768
<Java Local>, pool com.hazelcast.sql.impl.worker.QueryOperationWorkerPool$WorkerThread @ 0x82021810 zealous_meninsky-query-fragment-thread-14 Thread | 136 | 11,000

```

possible related to using the ‘sqlStatement.setTimeoutMillis(sqlTimeoutMillis);’ and running queries 

```
Installing core
installing /home/danny/.m2/repository/com/hazelcast/hazelcast-enterprise/4.2-SNAPSHOT/hazelcast-enterprise-4.2-SNAPSHOT.jar
installing /home/danny/.m2/repository/com/hazelcast/hazelcast-sql/4.2-SNAPSHOT/hazelcast-sql-4.2-SNAPSHOT.jar
HzMember1HZ Started 10.212.1.101 933360@Server1 /appdisk/danny/hz-root/hz-lib/4.2-SNAPSHOT
HzMember2HZ Started 10.212.1.102 332339@SERVER2 /appdisk/danny/hz-root/hz-lib/4.2-SNAPSHOT
HzMember10HZ Started 10.212.1.110 783396@server10 /appdisk/danny/hz-root/hz-lib/4.2-SNAPSHOT
HzMember9HZ Started 10.212.1.109 525202@SERVER9 /appdisk/danny/hz-root/hz-lib/4.2-SNAPSHOT
HzMember5HZ Started 10.212.1.105 642227@server5 /appdisk/danny/hz-root/hz-lib/4.2-SNAPSHOT
HzMember6HZ Started 10.212.1.106 397972@server6 /appdisk/danny/hz-root/hz-lib/4.2-SNAPSHOT
HzMember3HZ Started 10.212.1.103 961342@SERVER3 /appdisk/danny/hz-root/hz-lib/4.2-SNAPSHOT
HzMember4HZ Started 10.212.1.104 299416@SERVER4 /appdisk/danny/hz-root/hz-lib/4.2-SNAPSHOT
HzMember7HZ Started 10.212.1.107 829975@SERVER7 /appdisk/danny/hz-root/hz-lib/4.2-SNAPSHOT
HzMember8HZ Started 10.212.1.108 529345@SERVER8 /appdisk/danny/hz-root/hz-lib/4.2-SNAPSHOT
HzClient10HZ Started 10.212.1.110 783642@server10 /appdisk/danny/hz-root/hz-lib/4.2-SNAPSHOT
HzClient9HZ Started 10.212.1.109 525437@SERVER9 /appdisk/danny/hz-root/hz-lib/4.2-SNAPSHOT
HzClient2HZ Started 10.212.1.102 332593@SERVER2 /appdisk/danny/hz-root/hz-lib/4.2-SNAPSHOT
HzClient6HZ Started 10.212.1.106 398225@server6 /appdisk/danny/hz-root/hz-lib/4.2-SNAPSHOT
HzClient5HZ Started 10.212.1.105 642462@server5 /appdisk/danny/hz-root/hz-lib/4.2-SNAPSHOT
HzClient3HZ Started 10.212.1.103 961625@SERVER3 /appdisk/danny/hz-root/hz-lib/4.2-SNAPSHOT
HzClient1HZ Started 10.212.1.101 933615@Server1 /appdisk/danny/hz-root/hz-lib/4.2-SNAPSHOT
HzClient4HZ Started 10.212.1.104 299651@SERVER4 /appdisk/danny/hz-root/hz-lib/4.2-SNAPSHOT
HzClient7HZ Started 10.212.1.107 830229@SERVER7 /appdisk/danny/hz-root/hz-lib/4.2-SNAPSHOT
HzClient8HZ Started 10.212.1.108 529580@SERVER8 /appdisk/danny/hz-root/hz-lib/4.2-SNAPSHOT
fn hzcmd.map.loader.LoadEntitys driver=.* threads=100 duration=0 bench=No interval=0 keyDomain=5000000 maxPrice=1000 name=mapBak1HD
fn Done
fn hzcmd.distributed.AddIndex driver=Member1 threads=1 duration=0 bench=No interval=0 fields=id
fn Done
fn hzcmd.distributed.Size driver=Member threads=1 duration=0 bench=No interval=0 size=5000000
fn Done
q-id hzcmd.map.sql.service.IdRange driver=.* threads=10 duration=0 bench=Roll interval=0 keyDomain=5000000 range=1 name=mapBak1HD sqlTimeoutMillis=3 ignore=com.hazelcast.sql.HazelcastSqlException
q-price hzcmd.map.sql.service.PriceIs driver=.* threads=10 duration=0 bench=Roll interval=0 maxPrice=1000 name=mapBak1HD sqlTimeoutMillis=3 ignore=com.hazelcast.sql.HazelcastSqlException
q-bool hzcmd.map.sql.service.BoolIs driver=.* threads=10 duration=0 bench=Roll interval=0 name=mapBak1HD sqlTimeoutMillis=3 ignore=com.hazelcast.sql.HazelcastSqlException
fail HzMember1HZ q-id hzcmd.map.sql.service.IdRange threadId=6 java.lang.OutOfMemoryError: GC overhead limit exceeded
fail HzMember9HZ q-bool hzcmd.map.sql.service.BoolIs threadId=0 java.lang.OutOfMemoryError: GC overhead limit exceeded
fail HzMember9HZ q-price hzcmd.map.sql.service.PriceIs threadId=5 java.lang.OutOfMemoryError: GC overhead limit exceeded
output/HZ/HzMember1HZ/HzMember1HZ.oome
output/HZ/HzMember1HZ/exception.txt
output/HZ/HzMember1HZ/HzMember1HZ.hprof
output/HZ/HzMember6HZ/HzMember6HZ.oome
output/HZ/HzMember6HZ/HzMember6HZ.hprof
output/HZ/HzMember7HZ/HzMember7HZ.oome
output/HZ/HzMember7HZ/HzMember7HZ.hprof
output/HZ/HzMember9HZ/HzMember9HZ.hprof
output/HZ/HzMember9HZ/exception.txt
output/HZ/HzMember9HZ/HzMember9HZ.oome
output/HZ/HzMember10HZ/HzMember10HZ.oome
output/HZ/HzMember10HZ/exception.txt
output/HZ/HzMember10HZ/HzMember10HZ.hprof
```

```
#!/usr/bin/env bash
hz broker $(hostname -i | awk '{print $5}')
hz jversion 8

ops="$ops -Dhazelcast.enterprise.license.key=${HAZELCAST_EE_KEY}"
ops="$ops -Dhazelcast.partition.count=2411"
ops="$ops -Dhazelcast.hd.global.index.enabled=true"

hz xml config-hz-600
hz memberOps "-Xms2G -Xmx2G ${ops}"
hz clientOps "-Xms1G  -Xmx1G ${ops}"
hz cluster -ee -size M10C10 -v $(hazelcastVersion)

sz=5000000
hz go hzcmd.map.loader.LoadEntitys threads=100 keyDomain=${sz} maxPrice=1000 name=mapBak1HD bench=No
hz go hzcmd.distributed.AddIndex driver=Member1 fields=id bench=No
hz go hzcmd.distributed.Size driver=Member size=${sz} bench=No

hz ignore com.hazelcast.sql.HazelcastSqlException
hz go -f q-id hzcmd.map.sql.service.IdRange keyDomain=${sz} range=1 name=mapBak1HD threads=10 &
hz go -f q-price hzcmd.map.sql.service.PriceIs maxPrice=1000 name=mapBak1HD threads=10 &
hz go -f q-bool hzcmd.map.sql.service.BoolIs name=mapBak1HD threads=10 &

hz go -f q-put hzcmd.distributed.PutEntity keyDomain=${sz} maxPrice=1000 threads=10 &

wait
hz download
```

hprofs at
/nfs/danny/output-oom-tiomeout/

**Comment by devozerov** [comment]
@Danny-Hazelcast  What are the indications that the problem is caused by timeout? Initial analysis shows that it might be so, as there are lots of relatively small messages ~2kb in size, which could be `cancel` messages initiated due to timeout (haven't confirmed yet). Just interesting if you had any solid observations that the problem disappear if the timeout is removed.

**Comment by Danny-Hazelcast** [comment]
@devozerov 

some other examples of the OOM issue,  probably the same root cause 

[danny@server16 output-oom3]$ pwd
/home/danny/workspace/sqlService/output-oom3

[danny@server16 output-oome-2G]$ pwd
/home/danny/workspace/sqlService/output-oome-2G

[danny@server16 output-oome-12G]$ pwd
/home/danny/workspace/sqlService/output-oome-12G

**Comment by viliam-durina** [comment]
Looks like the FJP is congested by threads stuck here:
```
"pool-6-thread-8" prio=5 tid=342 WAITING
    at java.lang.Object.wait(Native Method)
    at java.lang.Object.wait(Object.java:502)
    at com.hazelcast.sql.impl.exec.root.BlockingRootResultConsumer.awaitNextBatch(BlockingRootResultConsumer.java:125)
       Local Variable: com.hazelcast.sql.impl.exec.root.BlockingRootResultConsumer#23564
    at com.hazelcast.sql.impl.exec.root.BlockingRootResultConsumer.access$100(BlockingRootResultConsumer.java:33)
    at com.hazelcast.sql.impl.exec.root.BlockingRootResultConsumer$InternalIterator.hasNext(BlockingRootResultConsumer.java:168)
       Local Variable: com.hazelcast.sql.impl.exec.root.BlockingRootResultConsumer$InternalIterator#23561
    at com.hazelcast.sql.impl.SqlResultImpl$RowToSqlRowIterator.hasNext(SqlResultImpl.java:150)
    at hzcmd.map.sql.service.PriceIs.timeStep(PriceIs.java:20)
       Local Variable: com.hazelcast.sql.impl.SqlResultImpl$RowToSqlRowIterator#10
    at remote.bench.marker.RollMarker.flatOut(RollMarker.java:72)
       Local Variable: com.codahale.metrics.Timer$Context#2
    at remote.bench.marker.RollMarker.bench(RollMarker.java:59)
       Local Variable: hzcmd.map.sql.service.PriceIs#3
    at remote.bench.BenchThread.call(BenchThread.java:41)
       Local Variable: remote.command.ReplyMsg#3
    at remote.bench.BenchThread.call(BenchThread.java:14)
       Local Variable: remote.bench.BenchThread#3
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       Local Variable: java.util.concurrent.FutureTask#4
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
       Local Variable: java.util.concurrent.Executors$RunnableAdapter#36
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
       Local Variable: java.util.concurrent.ExecutorCompletionService$QueueingFuture#3
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
       Local Variable: java.util.concurrent.ThreadPoolExecutor$Worker#39
    at java.lang.Thread.run(Thread.java:748)
```
Maybe new tasks are added, but these aren't removed and occupy the threads.

**Comment by viliam-durina** [comment]
@Danny-Hazelcast can you share the code to reproduce your issue? I can't get that from the above code...

**Comment by Danny-Hazelcast** [comment]
It might be so. First, we do not have any limit on the maximum number of queries at the moment. Second, our cancellation routine is not very responsive at the moment (https://github.com/hazelcast/hazelcast/issues/17721). This is what might happen:
Worker thread submit queries with very small timeouts (3ms)
Background member thread initiates the cancel on timeout. The client cursor is notified immediately, and the next query is scheduled.
But the member-side executor cannot cancel the query that fast
As a result, clients submit queries faster than they are discarded. (edited) 
This is just an idea, needs to be proven




run a query and iterate over the result set,  if we hit an com.hazelcast.sql.HazelcastSqlException. ignore it and run timeStep again.  sqlStatement.setTimeoutMillis(sqlTimeoutMillis); is set so some queries throw HazelcastSqlException on timeout.


```
public void timeStep() throws Exception {

        int price = random.nextInt(maxPrice);

        sqlStatement.setSql("select * from "+name+" where price = "+price);
        SqlResult sqlResult = sqlService.execute(sqlStatement);

        int size=0;
        for (SqlRow row : sqlResult) {
            int p = row.getObject("price");
            if( p!=price ){
                throw new AssertionException(row+" != "+ sqlStatement.getSql());
            }
            size++;
        }
        if(size==0){
            throw new AssertionException(sqlStatement.getSql() +" result set empty");
        }
    }
```

**Comment by viliam-durina** [comment]
I was trying to reproduce it but couldn't. I ran this test:
```java
    public static void main(String[] args) {
        TestHazelcastFactory factory = new TestHazelcastFactory();
        HazelcastInstance inst = factory.newHazelcastInstance();
        factory.newHazelcastInstance();
        HazelcastInstance client = factory.newHazelcastClient();
        Map<Integer, Integer> tmpMap = new HashMap<>();
        for (int i = 0; i < 10_000; i++) {
            tmpMap.put(i, i);
        }
        inst.getMap("m").putAll(tmpMap);

        ExecutorService threadPool = Executors.newFixedThreadPool(64);
        for (int i = 0; i < 65535; i++) {
            int finalI = i;
            threadPool.submit(() -> {
                System.out.println("executing query " + finalI);
                client.getSql().execute(new SqlStatement("select * from m"));
            });
        }

        sleepSeconds(600);
    }
```
It quickly failed, but the memory was spent in `QueryClientStateRegistry` which is expected. @Danny-Hazelcast could you share your full workload? What's the contents of the map, how do you execute queries etc. I'd like to confirm the cause.

**Comment by Danny-Hazelcast** [comment]
```
#!/usr/bin/env bash
hz broker $(hostname -i | awk '{print $5}')
hz jversion 8

ops="$ops -Dhazelcast.enterprise.license.key=${HAZELCAST_EE_KEY}"
ops="$ops -Dhazelcast.partition.count=2411"
ops="$ops -Dhazelcast.hd.global.index.enabled=true"

hz xml config-hz-600
hz memberOps "-Xms2G -Xmx2G ${ops}"
hz clientOps "-Xms1G  -Xmx1G ${ops}"
hz cluster -ee -size M10C10 -v $(hazelcastVersion)

sz=10000000
hz go hzcmd.map.loader.LoadEntitys threads=100 keyDomain=${sz} maxPrice=1000 name=mapBak1HD bench=No
hz go hzcmd.distributed.AddIndex driver=Member1 fields=id bench=No
hz go hzcmd.distributed.Size driver=Member size=${sz} bench=No

hz ignore com.hazelcast.sql.HazelcastSqlException
hz go -f q-id hzcmd.map.sql.service.IdRange keyDomain=${sz} range=1 name=mapBak1HD threads=10 sqlTimeoutMillis=10 &
hz go -f q-price hzcmd.map.sql.service.PriceIs maxPrice=1000 name=mapBak1HD threads=10 sqlTimeoutMillis=10 &
hz go -f q-bool hzcmd.map.sql.service.BoolIs name=mapBak1HD threads=10 sqlTimeoutMillis=10 &


wait
hz download
```


https://github.com/hazelcast/hzCmd-bench/blob/zeta/src/main/java/hzcmd/map/loader/LoadEntitys.java
https://github.com/hazelcast/hzCmd-bench/blob/zeta/src/main/java/hzcmd/distributed/AddIndex.java
https://github.com/hazelcast/hzCmd-bench/blob/zeta/src/main/java/hzcmd/distributed/Size.java

ignore com.hazelcast.sql.HazelcastSqlException
sqlTimeoutMillis=10
https://github.com/hazelcast/hzCmd-bench/blob/zeta/src/main/java/hzcmd/map/sql/service/IdRange.java
https://github.com/hazelcast/hzCmd-bench/blob/zeta/src/main/java/hzcmd/map/sql/service/PriceIs.java
https://github.com/hazelcast/hzCmd-bench/blob/zeta/src/main/java/hzcmd/map/sql/service/BoolIs.java

**Comment by Danny-Hazelcast** [comment]
run a "long" query with a timeout when it times out repeat,  wait until member nodes OOME

**Comment by viliam-durina** [comment]
This applied to the IMDG engine which will be retired in 5.0
