### ISSUE TITLE
Failed to access the probe: os.totalSwapSpaceSize

### ISSUE THREAD

**Issue by ilkerkorkut** [hazelcast/hazelcast#18412]
Server - Openjdk version "1.8.0_275"
Client  - Openjdk version "1.8.x"
 
Server: Linux CentOS Linux release 7.7.1908 (Core)
Clients: Dockerized and through Kubernetes GCP cloud  jdk:8-alpine

Looping following warning on client :
  
```
WARNING: *** [dev] [3.12.12] Failed to access the probe: os.totalSwapSpaceSize
java.lang.reflect.InvocationTargetException
at sun.reflect.GeneratedMethodAccessor155.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.hazelcast.internal.metrics.metricsets.OperatingSystemMetricSet$3.get(OperatingSystemMetricSet.java:107)
at com.hazelcast.internal.metrics.impl.LongGaugeImpl.read(LongGaugeImpl.java:52)
at com.hazelcast.internal.metrics.impl.LongGaugeImpl.render(LongGaugeImpl.java:66)
at com.hazelcast.client.impl.statistics.Statistics$PeriodicStatistics.fillMetrics(Statistics.java:386)
at com.hazelcast.client.impl.statistics.Statistics$1.run(Statistics.java:166)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
Caused by: java.lang.UnsatisfiedLinkError: sun.management.OperatingSystemImpl.getTotalSwapSpaceSize()J
at sun.management.OperatingSystemImpl.getTotalSwapSpaceSize(Native Method)
```

**Comment by sertugkaya** [comment]
A fix for a similar issue: https://github.com/hazelcast/hazelcast/pull/13567

**Comment by sertugkaya** [comment]
No functional impact. Workaround is disabling client diagnostics altogether

**Comment by AyberkSorgun** [comment]
Related ZD Ticket: [7186](https://hazelcast.zendesk.com/agent/tickets/7186)
