### ISSUE TITLE
IMap isEmpty() check is hang forever and all application threads are blocked.

### ISSUE THREAD

**Issue by bmistry13** [hazelcast/hazelcast#18433]
**Describe the bug**

We have hazelcast and we use it to store 2000 entries in map and both Hazelcast client and server are on the SAME JVM.  

There is no way to recover other than restarting the JVM.   Please see attached thread dump.
[tdump.txt](https://github.com/hazelcast/hazelcast/files/6193117/tdump.txt)

"https-jsse-nio-9183-exec-16" #1284190 daemon prio=5 os_prio=0 cpu=11368.32ms elapsed=1115966.71s tid=0x00007ff16c268000 nid=0x4d69 waiting on condition  [0x00007ff0f099c000]
   java.lang.Thread.State: WAITING (parking)
                at jdk.internal.misc.Unsafe.park(java.base@11.0.5/Native Method)
                at java.util.concurrent.locks.LockSupport.park(java.base@11.0.5/LockSupport.java:323)
                at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:607)
                at com.hazelcast.client.impl.spi.ClientProxy.invoke(ClientProxy.java:215)
                at com.hazelcast.client.impl.proxy.ClientMapProxy.isEmpty(ClientMapProxy.java:1594)
                at org.apache.commons.collections4.MapUtils.isEmpty(MapUtils.java:1215)
                at org.apache.commons.collections4.MapUtils.isNotEmpty(MapUtils.java:1228)
                

**Expected behavior**

I expect isEmpty() on IMap to be non-blocking.

**To Reproduce**
We do not know how to reproduce it this has happened twice already and real production issue.

**Additional context**

This is how we start the Server :
```
	public void startHazelcastServer(){
        LOGGER.info("startHazelcastServer()");
		
        Config config = new Config();
        NetworkConfig network = config.getNetworkConfig();
        JoinConfig join = network.getJoin();
		join.getMulticastConfig().setEnabled( false );
		join.getTcpIpConfig().setEnabled( false );
		join.getAwsConfig().setEnabled(false);

		
		MapConfig mapConfig = new MapConfig();
		mapConfig.setName( "VersaConfig" );	

		NearCacheConfig nearCacheConfig = new NearCacheConfig();
                mapConfig.setNearCacheConfig(nearCacheConfig);

		config.addMapConfig( mapConfig );		
        

        HazelcastInstance instance = Hazelcast.newHazelcastInstance(config);
        }
```
	
This is how we start our Client:
```
                 ClientConfig clientConfig = new ClientConfig();        
		ClientNetworkConfig networkConfig = clientConfig.getNetworkConfig();
		networkConfig.setConnectionTimeout(3000);
		client = HazelcastClient.newHazelcastClient(clientConfig);
```
Version Hazel cast server and client: 4.0.3

**Comment by ahmetmircik** [comment]
@bmistry13, Would you be able to create a reproducer? I tried but no luck unfortunately.

**Comment by bmistry13** [comment]
@ahmetmircik  It does not happen all the time 1% chance it happens.  From thread dump can you please check the code why IsEmpty is blocking?  Is it a host of connectivity issues or etc (even if client and server are ON Same JVM)?  Can you please check thread dump and stack trace to find out why isEmpty() blocked?

**Comment by ahmetmircik** [comment]
@bmistry13 all fork-join pool threads in thread dump are waiting for the same condition. By starting from version 4.0, Hazelcast uses fork-join common pool, some condition that blocks it also affects Hazelcast. Your application code or used libraries should not block threads in the common fjp. If this is the reason of the issue, we also improved the situation in latest 4.2 release(see https://github.com/hazelcast/hazelcast/issues/17959), you can also try with it.

**Comment by bmistry13** [comment]
@ahmetmircik ,  Thank you very much for the pointers, I think I know the issue Fork And Join thread is busy getting data from DB (blocking call).  Hence, others are blocked.  I have analyzed the thread dump again and found the root cause of this.  Thank you for your pointers and help on this issue.
