### ISSUE TITLE
ClientBitmapIndexTest.testRandomQueries

### ISSUE THREAD

**Issue by mmedenjak** [hazelcast/hazelcast#18457]
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/4393

```
java.lang.AssertionError: expected:<1> but was:<2>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at com.hazelcast.client.map.impl.query.ClientBitmapIndexTest.verifyQueries(ClientBitmapIndexTest.java:253)
	at com.hazelcast.client.map.impl.query.ClientBitmapIndexTest.testRandomQueries(ClientBitmapIndexTest.java:194)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by ramizdundar** [comment]
With Ufuk we have taken a look at this and maybe the cause is the high load when tests are run.

The test usually takes around 10 seconds (at least in my local). However in this case it took 112 seconds. This is probably because of high load when the tests are run. Here are the HealthMonitor logs:

```
15:05:22,838  INFO |testRandomQueries[IndexConfig{name=null, type=BITMAP, attributes=[age], bitmapIndexOptions=BitmapIndexOptions{uniqueKey=stringId, uniqueKeyTransformation=OBJECT}}]| - [HealthMonitor] hz.mystifying_edison.HealthMonitor - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] processors=24, physical.memory.total=377.6G, physical.memory.free=2.1G, swap.space.total=4.0G, swap.space.free=3.7G, heap.memory.used=520.1M, heap.memory.free=633.4M, heap.memory.total=1.1G, heap.memory.max=1.8G, heap.memory.used/total=45.09%, heap.memory.used/max=28.57%, minor.gc.count=88, minor.gc.time=19787ms, major.gc.count=4, major.gc.time=4723ms, load.process=0.00%, load.system=100.00%, load.systemAverage=13023.41, thread.count=111, thread.peakCount=671, cluster.timeDiff=0, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=8086, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=7, clientEndpoint.count=1, connection.active.count=0, client.connection.count=0, connection.count=0
15:05:42,841  INFO |testRandomQueries[IndexConfig{name=null, type=BITMAP, attributes=[age], bitmapIndexOptions=BitmapIndexOptions{uniqueKey=stringId, uniqueKeyTransformation=OBJECT}}]| - [HealthMonitor] hz.mystifying_edison.HealthMonitor - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] processors=24, physical.memory.total=377.6G, physical.memory.free=1.3G, swap.space.total=4.0G, swap.space.free=3.7G, heap.memory.used=520.1M, heap.memory.free=633.4M, heap.memory.total=1.1G, heap.memory.max=1.8G, heap.memory.used/total=45.09%, heap.memory.used/max=28.57%, minor.gc.count=88, minor.gc.time=19787ms, major.gc.count=4, major.gc.time=4723ms, load.process=0.00%, load.system=100.00%, load.systemAverage=13043.14, thread.count=111, thread.peakCount=671, cluster.timeDiff=0, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=8086, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=7, clientEndpoint.count=1, connection.active.count=0, client.connection.count=0, connection.count=0
15:06:02,845  INFO |testRandomQueries[IndexConfig{name=null, type=BITMAP, attributes=[age], bitmapIndexOptions=BitmapIndexOptions{uniqueKey=stringId, uniqueKeyTransformation=OBJECT}}]| - [HealthMonitor] hz.mystifying_edison.HealthMonitor - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] processors=24, physical.memory.total=377.6G, physical.memory.free=1.7G, swap.space.total=4.0G, swap.space.free=3.7G, heap.memory.used=520.1M, heap.memory.free=633.4M, heap.memory.total=1.1G, heap.memory.max=1.8G, heap.memory.used/total=45.09%, heap.memory.used/max=28.57%, minor.gc.count=88, minor.gc.time=19787ms, major.gc.count=4, major.gc.time=4723ms, load.process=0.00%, load.system=100.00%, load.systemAverage=13107.35, thread.count=111, thread.peakCount=671, cluster.timeDiff=0, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=8086, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=7, clientEndpoint.count=1, connection.active.count=0, client.connection.count=0, connection.count=0
15:06:22,851  INFO |testRandomQueries[IndexConfig{name=null, type=BITMAP, attributes=[age], bitmapIndexOptions=BitmapIndexOptions{uniqueKey=stringId, uniqueKeyTransformation=OBJECT}}]| - [HealthMonitor] hz.mystifying_edison.HealthMonitor - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] processors=24, physical.memory.total=377.6G, physical.memory.free=1.9G, swap.space.total=4.0G, swap.space.free=3.7G, heap.memory.used=520.3M, heap.memory.free=633.2M, heap.memory.total=1.1G, heap.memory.max=1.8G, heap.memory.used/total=45.09%, heap.memory.used/max=28.57%, minor.gc.count=88, minor.gc.time=19787ms, major.gc.count=4, major.gc.time=4723ms, load.process=0.00%, load.system=100.00%, load.systemAverage=13175.44, thread.count=108, thread.peakCount=671, cluster.timeDiff=0, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=8086, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=7, clientEndpoint.count=1, connection.active.count=0, client.connection.count=0, connection.count=0
15:06:42,877  INFO |testRandomQueries[IndexConfig{name=null, type=BITMAP, attributes=[age], bitmapIndexOptions=BitmapIndexOptions{uniqueKey=stringId, uniqueKeyTransformation=OBJECT}}]| - [HealthMonitor] hz.mystifying_edison.HealthMonitor - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] processors=24, physical.memory.total=377.6G, physical.memory.free=1.1G, swap.space.total=4.0G, swap.space.free=3.7G, heap.memory.used=520.3M, heap.memory.free=633.2M, heap.memory.total=1.1G, heap.memory.max=1.8G, heap.memory.used/total=45.10%, heap.memory.used/max=28.58%, minor.gc.count=88, minor.gc.time=19787ms, major.gc.count=4, major.gc.time=4723ms, load.process=0.00%, load.system=100.00%, load.systemAverage=13204.06, thread.count=108, thread.peakCount=671, cluster.timeDiff=0, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=8086, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=7, clientEndpoint.count=1, connection.active.count=0, client.connection.count=0, connection.count=0
```

They indicate %100 system load during the test. We couldn't prove that the problem is because of this system load and we couldn't reproduce the failure in local even though we stressed the CPU. However given the time length difference of the test from the usual, it should be the cause (or at least related).

`classname="com.hazelcast.client.map.impl.query.ClientBitmapIndexTest" time="112.663"`
`15:06:50, accumulated pauses: 93742 ms, max pause: 92900 ms, pauses over 1000 ms: 1`

**Comment by ufukyilmaz** [comment]
Note that having a pause longer than the heartbeat timeout causes unusual actions such as client disconnection during the test.

**Comment by mmedenjak** [comment]
Thank you guys for the analysis, closing. If it occurs again, we can evaluate if we can improve it somehow.
