### ISSUE TITLE
PhoneHomeClientsTest.testSingleClient_withSingleMember_whenTheClientIsShutdown

### ISSUE THREAD

**Issue by mmedenjak** [hazelcast/hazelcast#18456]
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/4391

```
java.lang.AssertionError: expected:<1> but was:<0>
	at com.hazelcast.internal.util.phonehome.PhoneHomeClientsTest.assertParameters(PhoneHomeClientsTest.java:330)
	at com.hazelcast.internal.util.phonehome.PhoneHomeClientsTest.testSingleClient_withSingleMember_whenTheClientIsShutdown(PhoneHomeClientsTest.java:130)
```

**Comment by gurbuzali** [comment]
another failure http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/4556/testReport/junit/com.hazelcast.internal.util.phonehome/PhoneHomeClientsTest/testSingleClient_withSingleMember_whenTheClientIsShutdown_clientType_JAVA_/
