### ISSUE TITLE
MulticastConfigTest.testEqualsAndHashCode

### ISSUE THREAD

**Issue by mmedenjak** [hazelcast/hazelcast#18460]
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/4399

```
java.lang.AssertionError: 
EqualsVerifier found a problem in class com.hazelcast.config.MulticastConfig.
-> Significant fields: equals does not use enableSetInterface, or it is stateless.

For more information, go to: http://www.jqno.nl/equalsverifier/errormessages
	at nl.jqno.equalsverifier.api.SingleTypeEqualsVerifierApi.verify(SingleTypeEqualsVerifierApi.java:292)
	at com.hazelcast.config.MulticastConfigTest.testEqualsAndHashCode(MulticastConfigTest.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: nl.jqno.equalsverifier.internal.exceptions.AssertionException
	at nl.jqno.equalsverifier.internal.util.Assert.assertTrue(Assert.java:53)
	at nl.jqno.equalsverifier.internal.checkers.fieldchecks.SignificantFieldCheck.assertFieldShouldHaveBeenUsed(SignificantFieldCheck.java:203)
	at nl.jqno.equalsverifier.internal.checkers.fieldchecks.SignificantFieldCheck.assertFieldShouldBeIgnored(SignificantFieldCheck.java:141)
	at nl.jqno.equalsverifier.internal.checkers.fieldchecks.SignificantFieldCheck.execute(SignificantFieldCheck.java:81)
	at nl.jqno.equalsverifier.internal.checkers.FieldInspector.check(FieldInspector.java:29)
	at nl.jqno.equalsverifier.internal.checkers.FieldsChecker.check(FieldsChecker.java:72)
	at nl.jqno.equalsverifier.api.SingleTypeEqualsVerifierApi.verifyWithExamples(SingleTypeEqualsVerifierApi.java:399)
	at nl.jqno.equalsverifier.api.SingleTypeEqualsVerifierApi.performVerification(SingleTypeEqualsVerifierApi.java:355)
	at nl.jqno.equalsverifier.api.SingleTypeEqualsVerifierApi.verify(SingleTypeEqualsVerifierApi.java:290)
	... 13 more
```

**Comment by mmedenjak** [comment]
Seems issue might have been caused by changes in PR, closing for now.
