### ISSUE TITLE
HazelcastConnector_RestartTest.when_iListWrittenAndMemberShutdown_then_jobRestarts

### ISSUE THREAD

**Issue by mmedenjak** [hazelcast/hazelcast#18463]
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/4408

```
java.lang.AssertionError: output continues after shutdown expected:<6> but was:<15>
	at com.hazelcast.jet.impl.connector.HazelcastConnector_RestartTest.lambda$when_iListWrittenAndMemberShutdown_then_jobRestarts$3(HazelcastConnector_RestartTest.java:106)
	at com.hazelcast.jet.impl.connector.HazelcastConnector_RestartTest.when_iListWrittenAndMemberShutdown_then_jobRestarts(HazelcastConnector_RestartTest.java:106)
```

**Comment by mmedenjak** [comment]
Closing as duplicate of https://github.com/hazelcast/hazelcast/issues/18469
