### ISSUE TITLE
MapLoaderTest.testSenderAndBackupTerminates_AfterInitialLoad

### ISSUE THREAD

**Issue by mmedenjak** [hazelcast/hazelcast#18471]
http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-4.master-IbmJDK8/124

```
com.hazelcast.spi.exception.TargetNotMemberException: Not Member! target: [127.0.0.1]:5703 - 92fa0f1e-ae9a-4f70-b914-e9c045032671, partitionId: 1, operation: com.hazelcast.map.impl.operation.LoadMapOperation, service: hz:impl:mapService
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.initInvocationTarget(Invocation.java:290)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:562)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.access$400(Invocation.java:100)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation$InvocationRetryTask.run(Invocation.java:804)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:522)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:191)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:822)
	at ------ submitted from ------.()
	at com.hazelcast.internal.util.ExceptionUtil.cloneExceptionWithFixedAsyncStackTrace(ExceptionUtil.java:279)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.returnOrThrowWithGetConventions(InvocationFuture.java:112)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:100)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:617)
	at com.hazelcast.map.impl.proxy.MapProxySupport.loadAllInternal(MapProxySupport.java:604)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.loadAll(MapProxyImpl.java:667)
	at com.hazelcast.map.impl.mapstore.MapLoaderTest.testSenderAndBackupTerminates_AfterInitialLoad(MapLoaderTest.java:129)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.lang.Thread.run(Thread.java:822)
```

**Comment by mmedenjak** [comment]
I've been able to reproduce the issue by running on the lab several thousands of times. We may then improve the test stability or add more logging to verify the root cause.

**Comment by Holmistr** [comment]
Closing this issue to wait for another failure, based on the comments above.
