### ISSUE TITLE
HazelcastCacheReadTimeoutTest failure

### ISSUE THREAD

**Issue by viliam-durina** [hazelcast/hazelcast#18476]
_master_

Failed on `Hazelcast-pr-builder`: http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/4402/testReport/junit/com.hazelcast.spring.cache/HazelcastCacheReadTimeoutTest/

Stacktrace:
```
Caused by: com.hazelcast.core.HazelcastException: Cannot bind to a given address: /127.0.0.1. Hazelcast cannot start. Port [5701] is already in use and auto-increment is disabled.
	at com.hazelcast.instance.impl.ServerSocketHelper.createServerSocketChannel(ServerSocketHelper.java:84) ~[hazelcast-5.0-SNAPSHOT.jar:5.0-SNAPSHOT]
	at com.hazelcast.instance.impl.DefaultAddressPicker.getPublicAddressByPortSearch(DefaultAddressPicker.java:146) ~[hazelcast-5.0-SNAPSHOT.jar:5.0-SNAPSHOT]
	at com.hazelcast.instance.impl.DefaultAddressPicker.pickAddress(DefaultAddressPicker.java:120) ~[hazelcast-5.0-SNAPSHOT.jar:5.0-SNAPSHOT]
	at com.hazelcast.instance.impl.Node.<init>(Node.java:221) ~[hazelcast-5.0-SNAPSHOT.jar:5.0-SNAPSHOT]
	at com.hazelcast.instance.impl.HazelcastInstanceImpl.createNode(HazelcastInstanceImpl.java:149) ~[hazelcast-5.0-SNAPSHOT.jar:5.0-SNAPSHOT]
	at com.hazelcast.instance.impl.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:118) ~[hazelcast-5.0-SNAPSHOT.jar:5.0-SNAPSHOT]
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:211) ~[hazelcast-5.0-SNAPSHOT.jar:5.0-SNAPSHOT]
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:190) ~[hazelcast-5.0-SNAPSHOT.jar:5.0-SNAPSHOT]
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:128) ~[hazelcast-5.0-SNAPSHOT.jar:5.0-SNAPSHOT]
```

**Comment by gurbuzali** [comment]
closed via https://github.com/hazelcast/hazelcast/pull/18467
