### ISSUE TITLE
MemberJmxMetricsTest

### ISSUE THREAD

**Issue by mmedenjak** [hazelcast/hazelcast#18484]
JIRA issue was deleted but this test was ignored during merge and needs to be re-enabled and fixed.

**Comment by frant-hartm** [comment]
Failed here https://github.com/hazelcast/hazelcast/pull/18515#issuecomment-818615480

**Comment by mmedenjak** [comment]
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/4573
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/4593
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/4587
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/4585
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/4588
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/4583
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/4582
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/4577
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/4576

**Comment by jbartok** [comment]
This test (and one other) are brittle in the sense that they fail, if some other test leaves JMX metrics lying around (for example after it had failed for some reason). Can't really find out which other test is the culprit for the above failures, but can improve this test (and its companion, `ClientJmxMetricsTest`) to start with a clean slate and erase such garbage, when they find it, before doing their thing. Will open a PR in a sec.

**Comment by mmedenjak** [comment]
I think one technique for finding out which test leaves MBeans behind is finding some identifier (can't remember was it instance ID or MBean ID) in this test failure, and grep the build logs to find out which member/MBean had that ID, so you correlate the leaky test to the this test failure.

**Comment by jbartok** [comment]
Yes, found the relevant comment in `ClientJmxMetricsTest`. But still, these tests should not fail because something else left garbage around, so I've made sure of that.

> // if failing, grep for "test-jvm"
>         // there should be a Metric[com.hazelcast:type=Metrics,instance=$CLIENT_NAME,prefix=test-jvm-$JVM_NAME] metric if the
>         // client was created with TestHazelcastFactory
>         // $JVM_NAME contains the PID, so $CLIENT_NAME + $JVM_NAME together helps identifying the test left the given metric
>         // around

**Comment by sumnerib** [comment]
Reopening as issue occurred again on: _master_ (commit a695aebece92f5160827ba437577323daa448ff0)
with openjdk-17: https://jenkins.hazelcast.com/job/Hazelcast-master-ZuluJDK17/111/testReport/junit/com.hazelcast.internal.metrics.jmx/MemberJmxMetricsTest/testNoMBeanLeak/

<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: expected:<0> but was:<1>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at com.hazelcast.internal.metrics.jmx.JmxPublisherTestHelper.assertNoMBeans(JmxPublisherTestHelper.java:75)
	at com.hazelcast.internal.metrics.jmx.MemberJmxMetricsTest.testNoMBeanLeak(MemberJmxMetricsTest.java:64)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)

```
</details>

<details><summary>Standard output:</summary>

```
Started Running Test: testNoMBeanLeak
20:18:34,371  INFO |testNoMBeanLeak| - [MetricsConfigHelper] testNoMBeanLeak - [LOCAL] [dev] [5.4.0-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
20:18:34,372  INFO |testNoMBeanLeak| - [logo] testNoMBeanLeak - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
20:18:34,372  INFO |testNoMBeanLeak| - [system] testNoMBeanLeak - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Copyright (c) 2008-2023, Hazelcast, Inc. All Rights Reserved.
20:18:34,372  INFO |testNoMBeanLeak| - [system] testNoMBeanLeak - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Hazelcast Platform 5.4.0-SNAPSHOT (20231113 - a695aeb) starting at [127.0.0.1]:5701
20:18:34,372  INFO |testNoMBeanLeak| - [system] testNoMBeanLeak - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Cluster name: dev
20:18:34,372  INFO |testNoMBeanLeak| - [system] testNoMBeanLeak - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed. For more information, see the documentation for Integrity Checker.
20:18:34,372  INFO |testNoMBeanLeak| - [system] testNoMBeanLeak - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Jet is enabled
20:18:34,373  INFO |testNoMBeanLeak| - [MetricsConfigHelper] testNoMBeanLeak - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
20:18:34,374  INFO |testNoMBeanLeak| - [TpcServerBootstrap] testNoMBeanLeak - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] TPC: disabled
20:18:34,377  WARN |testNoMBeanLeak| - [CPSubsystem] testNoMBeanLeak - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
20:18:34,380  INFO |testNoMBeanLeak| - [JetServiceBackend] testNoMBeanLeak - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Setting number of cooperative threads and default parallelism to 2
20:18:34,380  INFO |testNoMBeanLeak| - [Diagnostics] testNoMBeanLeak - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
20:18:34,380  INFO |testNoMBeanLeak| - [LifecycleService] testNoMBeanLeak - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] [127.0.0.1]:5701 is STARTING
20:18:34,381  INFO |testNoMBeanLeak| - [ClusterService] testNoMBeanLeak - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] 

Members {size:1, ver:1} [
	Member [127.0.0.1]:5701 - ab1e2e30-a10a-4342-bc2c-a1204676e2bf this
]

20:18:34,381  INFO |testNoMBeanLeak| - [JobCoordinationService] testNoMBeanLeak - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Jet started scanning for jobs
20:18:34,381  INFO |testNoMBeanLeak| - [LifecycleService] testNoMBeanLeak - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] [127.0.0.1]:5701 is STARTED
20:18:34,381 DEBUG |testNoMBeanLeak| - [JobCoordinationService] hz.ReadMetricsOperationTest_gracious_lalande.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
20:18:34,481 DEBUG |testNoMBeanLeak| - [JobCoordinationService] hz.ReadMetricsOperationTest_gracious_lalande.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
20:18:34,581 DEBUG |testNoMBeanLeak| - [JobCoordinationService] hz.ReadMetricsOperationTest_gracious_lalande.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
20:18:34,681 DEBUG |testNoMBeanLeak| - [JobCoordinationService] hz.ReadMetricsOperationTest_gracious_lalande.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
20:18:34,781 DEBUG |testNoMBeanLeak| - [JobCoordinationService] hz.ReadMetricsOperationTest_gracious_lalande.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
20:18:34,881 DEBUG |testNoMBeanLeak| - [JobCoordinationService] hz.ReadMetricsOperationTest_gracious_lalande.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
20:18:34,982 DEBUG |testNoMBeanLeak| - [JobCoordinationService] hz.ReadMetricsOperationTest_gracious_lalande.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
20:18:35,082 DEBUG |testNoMBeanLeak| - [JobCoordinationService] hz.ReadMetricsOperationTest_gracious_lalande.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
20:18:35,182 DEBUG |testNoMBeanLeak| - [JobCoordinationService] hz.ReadMetricsOperationTest_gracious_lalande.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
20:18:35,282 DEBUG |testNoMBeanLeak| - [JobCoordinationService] hz.ReadMetricsOperationTest_gracious_lalande.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
20:18:35,383 DEBUG |testNoMBeanLeak| - [JobCoordinationService] hz.ReadMetricsOperationTest_gracious_lalande.cached.thread-9 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
20:18:35,383  INFO |testNoMBeanLeak| - [LifecycleService] testNoMBeanLeak - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
20:18:35,383 DEBUG |testNoMBeanLeak| - [JobCoordinationService] testNoMBeanLeak - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Added a shutting-down member: ab1e2e30-a10a-4342-bc2c-a1204676e2bf
20:18:35,383  INFO |testNoMBeanLeak| - [Node] testNoMBeanLeak - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Shutting down connection manager...
20:18:35,383  INFO |testNoMBeanLeak| - [Node] testNoMBeanLeak - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Shutting down node engine...
20:18:35,388  INFO |testNoMBeanLeak| - [NodeExtension] testNoMBeanLeak - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Destroying node NodeExtension.
20:18:35,388  INFO |testNoMBeanLeak| - [Node] testNoMBeanLeak - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Hazelcast Shutdown is completed in 5 ms.
20:18:35,388  INFO |testNoMBeanLeak| - [LifecycleService] testNoMBeanLeak - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
20:18:35,388  INFO |testNoMBeanLeak| - [JmxPublisherTestHelper] testNoMBeanLeak - Dangling metrics MBeans created by 2847@f21234b4873b: [Metric[com.hazelcast:type=Metrics,instance=ReadMetricsOperationTest_gracious_lalande,prefix=executor.internal,tag0="name=hz:jet-job-offloadable"]]
20:18:35,666  INFO |testNoMBeanLeak| - [LifecycleService] main - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
20:18:35,666  INFO |testNoMBeanLeak| - [Node] main - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Node is already shutting down... Waiting for shutdown process to complete...
20:18:35,666  INFO |testNoMBeanLeak| - [LifecycleService] main - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-ZuluJDK17/111/

**Comment by olukas** [comment]
Failed again on _5.3.z_ with ZuluJDK17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-ZuluJDK17/102/testReport/com.hazelcast.internal.metrics.jmx/MemberJmxMetricsTest/testNoMBeanLeak/

**Comment by AleksPeychev** [comment]
Failed again on _5.4.z_ with oracle-17 (force-offload): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-force-offload/80/testReport/junit/com.hazelcast.internal.metrics.jmx/MemberJmxMetricsTest/testNoMBeanLeak/

**Comment by olukas** [comment]
Closing the test failure - it doesn't seem to be related to `master` or the latest maintenance stream `5.5.z` and it hasn't fail in the last 3 months. Feel free to reopen test failure if it occurs on `master` or on the latest maintenance stream.
