### ISSUE TITLE
PendingInvocationsPluginTest.testRun

### ISSUE THREAD

**Issue by gurbuzali** [hazelcast/hazelcast#18490]
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/4464/

Stacktrace:
```
' didn't contain expected 'count=2'
	at com.hazelcast.internal.diagnostics.PendingInvocationsPluginTest.lambda$testRun$1(PendingInvocationsPluginTest.java:70)
	at com.hazelcast.internal.diagnostics.PendingInvocationsPluginTest.testRun(PendingInvocationsPluginTest.java:65)
```

**Comment by gurbuzali** [comment]
a bit of history -> 
- during the merge we changed the `count=1` to `count=2` with a note:
`TODO Jet Merge - there are 2 after the merge - PartitionIteratingOperation is not expected- something Jet does?`
- With the lazy creation of jet internal maps fix, converted back to the original

The logs from the build are weird, lots of 
```
20:26:32,874  INFO || - [ClientConnectionManager] hz.client_239.internal-6 - hz.client_239 [5c77676a-1123-4d29-b24e-2b2bc059cdc7] [5.0-SNAPSHOT] [5.0-SNAPSHOT] Trying to connect to Member [127.0.0.1]:5701 - efce218c-3f44-4d26-9fb3-72d151892191
20:26:32,874  WARN || - [ClientConnectionManager] hz.client_239.internal-6 - hz.client_239 [5c77676a-1123-4d29-b24e-2b2bc059cdc7] [5.0-SNAPSHOT] [5.0-SNAPSHOT] Exception during initial connection to Member [127.0.0.1]:5701 - efce218c-3f44-4d26-9fb3-72d151892191: com.hazelcast.core.HazelcastException: java.net.SocketException: Connection refused to address /127.0.0.1:5701
```
The targeted member uuid is not the one created in this test btw.

Conclusion: let's close the issue assuming that `lazy creation of jet internal maps` fixed it.
