### ISSUE TITLE
QueryOperationHandlerTest.test_E[targetIsNotInitiator:true]

### ISSUE THREAD

**Issue by gurbuzali** [hazelcast/hazelcast#18512]
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/4556/

Stacktrace:
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.lang.Thread.sleep(Native Method)
	at java.lang.Thread.sleep(Thread.java:340)
	at java.util.concurrent.TimeUnit.sleep(TimeUnit.java:386)
	at com.hazelcast.test.HazelcastTestSupport.sleepMillis(HazelcastTestSupport.java:352)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1256)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1265)
	at com.hazelcast.sql.impl.operation.QueryOperationHandlerTest.assertQueryNotRegisteredEventually(QueryOperationHandlerTest.java:606)
	at com.hazelcast.sql.impl.operation.QueryOperationHandlerTest.test_E(QueryOperationHandlerTest.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by mmedenjak** [comment]
Quite big hiccups and load in the aforementioned run and test hasn't failed in a week. We improved the stability of the builds a lot since then so closing until next failure.

```
09:02:15,058  INFO |test_E[targetIsNotInitiator:true]| - [HealthMonitor] hz.cranky_chaplygin.HealthMonitor - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] processors=24, physical.memory.total=377.6G, physical.memory.free=61.1G, swap.space.total=4.0G, swap.spac
e.free=3.4G, heap.memory.used=372.2M, heap.memory.free=790.8M, heap.memory.total=1.1G, heap.memory.max=1.8G, heap.memory.used/total=32.00%, heap.memory.used/max=20.44%, minor.gc.count=112, minor.gc.time=38743ms, major.gc.count=5, major.gc.time=17388ms,
 load.process=0.00%, load.system=100.00%, load.systemAverage=9008.03, thread.count=207, thread.peakCount=3887, cluster.timeDiff=-4, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blo
cking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=69, executor.q.mapLoad.size=0, executor.q.
mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=0, clientEndpoint.count=0, connection.active.
count=0, client.connection.count=0, connection.count=0
```

```
Hiccups measured while running test 'test_E[targetIsNotInitiator:true](com.hazelcast.sql.impl.operation.QueryOperationHandlerTest):'
08:57:50, accumulated pauses: 1319 ms, max pause: 570 ms, pauses over 1000 ms: 0
08:57:55, accumulated pauses: 2212 ms, max pause: 1817 ms, pauses over 1000 ms: 1
08:58:00, accumulated pauses: 583 ms, max pause: 20 ms, pauses over 1000 ms: 0
08:58:05, accumulated pauses: 902 ms, max pause: 21 ms, pauses over 1000 ms: 0
08:58:10, accumulated pauses: 837 ms, max pause: 14 ms, pauses over 1000 ms: 0
08:58:15, accumulated pauses: 1893 ms, max pause: 60 ms, pauses over 1000 ms: 0
08:58:20, accumulated pauses: 971 ms, max pause: 31 ms, pauses over 1000 ms: 0
08:58:25, accumulated pauses: 1167 ms, max pause: 50 ms, pauses over 1000 ms: 0
08:58:30, accumulated pauses: 1011 ms, max pause: 20 ms, pauses over 1000 ms: 0
08:58:35, accumulated pauses: 790 ms, max pause: 21 ms, pauses over 1000 ms: 0
08:58:40, accumulated pauses: 461 ms, max pause: 12 ms, pauses over 1000 ms: 0
08:58:45, accumulated pauses: 834 ms, max pause: 13 ms, pauses over 1000 ms: 0
08:58:50, accumulated pauses: 1151 ms, max pause: 34 ms, pauses over 1000 ms: 0
08:58:55, accumulated pauses: 1083 ms, max pause: 432 ms, pauses over 1000 ms: 0
08:59:00, accumulated pauses: 350 ms, max pause: 8 ms, pauses over 1000 ms: 0
08:59:05, accumulated pauses: 928 ms, max pause: 56 ms, pauses over 1000 ms: 0
08:59:10, accumulated pauses: 1435 ms, max pause: 33 ms, pauses over 1000 ms: 0
08:59:15, accumulated pauses: 1413 ms, max pause: 44 ms, pauses over 1000 ms: 0
08:59:20, accumulated pauses: 2148 ms, max pause: 63 ms, pauses over 1000 ms: 0
08:59:25, accumulated pauses: 2308 ms, max pause: 89 ms, pauses over 1000 ms: 0
08:59:30, accumulated pauses: 1380 ms, max pause: 30 ms, pauses over 1000 ms: 0
08:59:35, accumulated pauses: 1152 ms, max pause: 40 ms, pauses over 1000 ms: 0
08:59:40, accumulated pauses: 1861 ms, max pause: 40 ms, pauses over 1000 ms: 0
08:59:45, accumulated pauses: 1414 ms, max pause: 58 ms, pauses over 1000 ms: 0
08:59:50, accumulated pauses: 311 ms, max pause: 40 ms, pauses over 1000 ms: 0
08:59:55, accumulated pauses: 362 ms, max pause: 57 ms, pauses over 1000 ms: 0
09:00:00, accumulated pauses: 464 ms, max pause: 12 ms, pauses over 1000 ms: 0
09:00:05, accumulated pauses: 492 ms, max pause: 7 ms, pauses over 1000 ms: 0
09:00:10, accumulated pauses: 954 ms, max pause: 29 ms, pauses over 1000 ms: 0
09:00:15, accumulated pauses: 1136 ms, max pause: 29 ms, pauses over 1000 ms: 0
09:00:20, accumulated pauses: 777 ms, max pause: 16 ms, pauses over 1000 ms: 0
09:00:25, accumulated pauses: 542 ms, max pause: 19 ms, pauses over 1000 ms: 0
09:00:30, accumulated pauses: 734 ms, max pause: 30 ms, pauses over 1000 ms: 0
09:00:35, accumulated pauses: 1129 ms, max pause: 85 ms, pauses over 1000 ms: 0
09:00:40, accumulated pauses: 1097 ms, max pause: 34 ms, pauses over 1000 ms: 0
09:00:45, accumulated pauses: 1383 ms, max pause: 30 ms, pauses over 1000 ms: 0
09:00:50, accumulated pauses: 1021 ms, max pause: 40 ms, pauses over 1000 ms: 0
09:00:55, accumulated pauses: 899 ms, max pause: 35 ms, pauses over 1000 ms: 0
09:01:00, accumulated pauses: 904 ms, max pause: 19 ms, pauses over 1000 ms: 0
09:01:05, accumulated pauses: 1403 ms, max pause: 33 ms, pauses over 1000 ms: 0
09:01:10, accumulated pauses: 707 ms, max pause: 24 ms, pauses over 1000 ms: 0
09:01:15, accumulated pauses: 1239 ms, max pause: 60 ms, pauses over 1000 ms: 0
09:01:20, accumulated pauses: 1092 ms, max pause: 23 ms, pauses over 1000 ms: 0
09:01:25, accumulated pauses: 1492 ms, max pause: 45 ms, pauses over 1000 ms: 0
09:01:30, accumulated pauses: 1904 ms, max pause: 23 ms, pauses over 1000 ms: 0
09:01:35, accumulated pauses: 560 ms, max pause: 13 ms, pauses over 1000 ms: 0
09:01:40, accumulated pauses: 702 ms, max pause: 35 ms, pauses over 1000 ms: 0
09:01:45, accumulated pauses: 1730 ms, max pause: 37 ms, pauses over 1000 ms: 0
09:01:50, accumulated pauses: 1543 ms, max pause: 23 ms, pauses over 1000 ms: 0
09:01:55, accumulated pauses: 2060 ms, max pause: 40 ms, pauses over 1000 ms: 0
09:02:00, accumulated pauses: 2762 ms, max pause: 90 ms, pauses over 1000 ms: 0
09:02:05, accumulated pauses: 2662 ms, max pause: 56 ms, pauses over 1000 ms: 0
09:02:10, accumulated pauses: 1587 ms, max pause: 87 ms, pauses over 1000 ms: 0
09:02:15, accumulated pauses: 2020 ms, max pause: 51 ms, pauses over 1000 ms: 0
09:02:20, accumulated pauses: 987 ms, max pause: 30 ms, pauses over 1000 ms: 0
09:02:25, accumulated pauses: 148 ms, max pause: 9 ms, pauses over 1000 ms: 0
09:02:30, accumulated pauses: 695 ms, max pause: 25 ms, pauses over 1000 ms: 0
09:02:35, accumulated pauses: 481 ms, max pause: 30 ms, pauses over 1000 ms: 0
09:02:40, accumulated pauses: 1175 ms, max pause: 60 ms, pauses over 1000 ms: 0
09:02:45, accumulated pauses: 1955 ms, max pause: 86 ms, pauses over 1000 ms: 0
09:02:50, accumulated pauses: 1326 ms, max pause: 35 ms, pauses over 1000 ms: 0
09:02:55, accumulated pauses: 738 ms, max pause: 637 ms, pauses over 1000 ms: 0
```
