### ISSUE TITLE
member oom / hz_err_pid.  jet job continual state change restart suspend resume

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#18549]
http://jenkins.hazelcast.com/view/stable/job/stable-x3/99/console
/disk1/workspace/stable-x3/5.0-SNAPSHOT/2021_04_14-15_08_57/jet

add 1000 jobs 
https://github.com/hazelcast/hzCmd-bench/blob/zeta/src/main/java/hzcmd/jet/AddJobs.java

check there are 1000 jobs
https://github.com/hazelcast/hzCmd-bench/blob/zeta/src/main/java/hzcmd/jet/CountJobs.java

check 1000 jobs are RUNNING
https://github.com/hazelcast/hzCmd-bench/blob/zeta/src/main/java/hzcmd/jet/State.java

continually change the state of all jobs,  restart suspend resume over and over
https://github.com/hazelcast/hzCmd-bench/blob/zeta/src/main/java/hzcmd/jet/RestartSuspendResume.java

```
Installing core
installing /home/ec2-user/.m2/repository/com/hazelcast/hazelcast-enterprise/5.0-SNAPSHOT/hazelcast-enterprise-5.0-SNAPSHOT.jar
HzMember2HZ Started 10.0.0.24 1953@ip-10-0-0-24.ec2.internal /home/ec2-user/hz-root/hz-lib/5.0-SNAPSHOT
HzMember3HZ Started 10.0.0.218 1975@ip-10-0-0-218.ec2.internal /home/ec2-user/hz-root/hz-lib/5.0-SNAPSHOT
HzMember4HZ Started 10.0.0.109 1988@ip-10-0-0-109.ec2.internal /home/ec2-user/hz-root/hz-lib/5.0-SNAPSHOT
HzMember1HZ Started 10.0.0.54 1992@ip-10-0-0-54.ec2.internal /home/ec2-user/hz-root/hz-lib/5.0-SNAPSHOT
HzClient1HZ Started 10.0.0.54 2292@ip-10-0-0-54.ec2.internal /home/ec2-user/hz-root/hz-lib/5.0-SNAPSHOT
HzClient4HZ Started 10.0.0.109 2301@ip-10-0-0-109.ec2.internal /home/ec2-user/hz-root/hz-lib/5.0-SNAPSHOT
HzClient2HZ Started 10.0.0.24 2305@ip-10-0-0-24.ec2.internal /home/ec2-user/hz-root/hz-lib/5.0-SNAPSHOT
HzClient3HZ Started 10.0.0.218 2283@ip-10-0-0-218.ec2.internal /home/ec2-user/hz-root/hz-lib/5.0-SNAPSHOT
add hzcmd.jet.AddJobs driver=Member1 threads=1 duration=0 bench=Roll interval=0 count=1000
add Done
count hzcmd.jet.CountJobs driver=.* threads=1 duration=0 bench=Roll interval=0 count=1000
count Done
state hzcmd.jet.State driver=.* threads=1 duration=0 bench=Roll interval=0 state=RUNNING
running Done
rsr hzcmd.jet.RestartSuspendResume driver=.* threads=1 duration=0 bench=Roll interval=0
fail HzMember2HZ rsr hzcmd.jet.RestartSuspendResume threadId=0 java.lang.IllegalStateException: Job already completed
output/HZ/HzClient3HZ/exception.txt
output/HZ/HzMember2HZ/exception.txt
output/HZ/HzClient4HZ/exception.txt
output/HZ/HzMember1HZ/exception.txt
output/HZ/HzMember3HZ/hs_err_pid1975.log
output/HZ/HzClient2HZ/hs_err_pid2305.log
output/HZ/HzClient1HZ/exception.txt
```

after a few hours we hit the OOME issue on a member and a client. 
the member jvm and client jvm were running on different boxes 

./output/HZ/HzMember3HZ/hs_err_pid1975.log
./output/HZ/HzClient2HZ/hs_err_pid2305.log

the we also hit this exception, however no job was explicitly put into a completed state ?  maybe after a member crash 
the state of a job could be completed ? 

```
java.lang.IllegalStateException: Job already completed
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$resumeJob$28(JobCoordinationService.java:512)
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$toNullFunction$37(JobCoordinationService.java:636)
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$callWithJob$38(JobCoordinationService.java:671)
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$47(JobCoordinationService.java:1057)
	at com.hazelcast.internal.util.executor.CompletableFutureTask.run(CompletableFutureTask.java:64)
	at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
	at ------ submitted from ------.()
	at com.hazelcast.internal.util.ExceptionUtil.cloneExceptionWithFixedAsyncStackTrace(ExceptionUtil.java:279)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.returnOrThrowWithGetConventions(InvocationFuture.java:112)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:100)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:617)
	at com.hazelcast.jet.impl.JobProxy.resume(JobProxy.java:113)
	at hzcmd.jet.RestartSuspendResume.timeStep(RestartSuspendResume.java:21)
```

GC chart of OOM client. no mem leak pattern 
![client2-verbosegc log](https://user-images.githubusercontent.com/5988678/115005523-dbd39f80-9e9f-11eb-840c-f2a309510cc8.png)

GC chart of OOM member,
![member3-verbosegc log](https://user-images.githubusercontent.com/5988678/115005825-310fb100-9ea0-11eb-83a9-cfb722234c6a.png)

```
cat ./output/HZ/HzMember3HZ/hs_err_pid1975.log | more
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 16384 bytes for committing reserved memory.
# Possible reasons:
#   The system is out of physical RAM or swap space
#   The process is running with CompressedOops enabled, and the Java Heap may be blocking the growth of the native heap
# Possible solutions:
#   Reduce memory load on the system
#   Increase physical memory or swap space
#   Check if swap backing store is full
#   Decrease Java heap size (-Xmx/-Xms)
#   Decrease number of Java threads
#   Decrease Java thread stack sizes (-Xss)
#   Set larger code cache with -XX:ReservedCodeCacheSize=
#   JVM is running with Unscaled Compressed Oops mode in which the Java heap is
#     placed in the first 4GB address space. The Java Heap base address is the
#     maximum limit for the native heap growth. Please use -XX:HeapBaseMinAddress
#     to set the Java Heap base and to place the Java Heap above 4GB virtual address.
# This output file may be truncated or incomplete.
#
#  Out of Memory Error (os_linux.cpp:2916), pid=1975, tid=3259
#
# JRE version: OpenJDK Runtime Environment Corretto-11.0.9.11.1 (11.0.9+11) (build 11.0.9+11-LTS)
# Java VM: OpenJDK 64-Bit Server VM Corretto-11.0.9.11.1 (11.0.9+11-LTS, mixed mode, tiered, compressed oops, g1 gc, linux-aarch64)
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#

---------------  S U M M A R Y ------------

Command Line: -DMQIP=3.87.100.12 -DQ=/disk1/workspace/stable-x3/5.0-SNAPSHOT/2021_04_14-15_08_57/jet/HzMember3HZ -DID=HzMember3HZ -DVENDOR_LIB=/home/ec2-user/hz-root/hz-lib/5.0-SNAPSHOT -XX:+HeapDumpOnOut
OfMemoryError -XX:HeapDumpPath=HzMember3HZ.hprof -XX:OnOutOfMemoryError= date >> HzMember3HZ.oome -Xlog:gc*,gc+ref=debug,gc+heap=debug,gc+age=trace:file=verbosegc.log:tags,uptime,time,level:filecount=1,fi
lesize=900m --add-modules=java.se --add-exports=java.base/jdk.internal.ref=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/sun.nio.
ch=ALL-UNNAMED --add-opens=java.management/sun.management=ALL-UNNAMED --add-opens=jdk.management/com.ibm.lang.management.internal=ALL-UNNAMED --add-opens=jdk.management/com.sun.management.internal=ALL-UNN
AMED -Xms2G -Xmx2G -Dhazelcast.enterprise.license.key=HazelcastEnterpriseHD#9999Nodes#RiUHNE1lOrwITY7F5K3VAm539qt3h099W999C99999xn999PsQ1Pv19q39h0 vendor.hz.java.HzMember

Host: AArch64, 4 cores, 15G, Amazon Linux release 2 (Karoo)
Time: Wed Apr 14 16:25:40 2021 UTC elapsed time: 4571.022368 seconds (0d 1h 16m 11s)

---------------  T H R E A D  ---------------

Current thread (0x0000ffff24188000):  JavaThread "hz.eloquent_sinoussi.cached.thread-5" [_thread_new, id=3259, stack(0x0000fffea8a00000,0x0000fffea8c00000)]

Stack: [0x0000fffea8a00000,0x0000fffea8c00000],  sp=0x0000fffea8bfe4a0,  free space=2041k
Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [libjvm.so+0xc7bae0]  VMError::report_and_die(int, char const*, char const*, std::__va_list, Thread*, unsigned char*, void*, void*, char const*, int, unsigned long)+0x2dc
V  [libjvm.so+0xc7c6b0]  VMError::report_and_die(Thread*, char const*, int, unsigned long, VMErrorType, char const*, std::__va_list)+0x50
V  [libjvm.so+0x557a14]  report_vm_out_of_memory(char const*, int, unsigned long, VMErrorType, char const*, ...)+0xac
V  [libjvm.so+0xa70664]  os::pd_commit_memory(char*, unsigned long, bool)+0x124
V  [libjvm.so+0xa67840]  os::commit_memory(char*, unsigned long, bool)+0x1c
V  [libjvm.so+0xa72448]  os::pd_create_stack_guard_pages(char*, unsigned long)+0xa0
V  [libjvm.so+0xc0f950]  JavaThread::run()+0x6c
V  [libjvm.so+0xc0d33c]  Thread::call_run()+0x94
V  [libjvm.so+0xa777e8]  thread_native_entry(Thread*)+0x108
C  [libpthread.so.0+0x72ac]  start_thread+0xac
```

i see reported 
No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again

however other tests have produced core dumps and hprofs,  but will try to set ulimit

**Comment by viliam-durina** [comment]
It looks like the JVM asks for more than the OS can provide:
```
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 16384 bytes for committing reserved memory.
# Possible reasons:
#   The system is out of physical RAM or swap space
#   The process is running with CompressedOops enabled, and the Java Heap may be blocking the growth of the native heap
```

**Comment by Danny-Hazelcast** [comment]
when adding ulimit -c unlimited,  the jvm process crashes with no logging,  hs_err_pid, core or hprof.

**Comment by vbekiaris** [comment]
It seems logs are no longer available on `stabilizer` machine. @Danny-Hazelcast is there a new jenkins job that performs the same kind of test? Have we seen it fail again?

**Comment by Danny-Hazelcast** [comment]
http://jenkins.hazelcast.com/view/stable/job/stable-x3/111/console
hz/stress/jet-a
running with 5.2-SNAPSHOT master

**Comment by Danny-Hazelcast** [comment]
can not reproduce this issue on 5.2-SNAPSHOT master @vbekiaris 


re-running the test.  hz/stress/jet-a    on   5.2-SNAPSHOT master 
http://jenkins.hazelcast.com/view/stable/job/stable-x3/111/console
http://jenkins.hazelcast.com/view/stable/job/stable-x1/225/console
