### ISSUE TITLE
IOUtilTest.test_zipAndUnzipNestedFolder_then_contentsShouldBeSame failure

### ISSUE THREAD

**Issue by viliam-durina** [hazelcast/hazelcast#18541]
_master_ (commit a7bcd8809462f9548bd23d36f259dc91768d3c6b)

Failed on Hazelcast-pr-builder: http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/4635/testReport/junit/com.hazelcast.jet.impl.util/IOUtilTest/test_zipAndUnzipNestedFolder_then_contentsShouldBeSame/

Stacktrace:
```
java.io.UncheckedIOException: java.nio.file.NoSuchFileException: /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder_3/hazelcast/target/test-classes/nested/da7e6253-0db2-4f9f-ae65-9433202154ac
	at java.nio.file.FileTreeIterator.fetchNextIfNeeded(FileTreeIterator.java:88)
	at java.nio.file.FileTreeIterator.hasNext(FileTreeIterator.java:104)
	at java.util.Iterator.forEachRemaining(Iterator.java:115)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at com.hazelcast.jet.impl.util.IOUtil.packDirectoryIntoZip(IOUtil.java:55)
	at com.hazelcast.jet.impl.util.IOUtilTest.test(IOUtilTest.java:81)
	at com.hazelcast.jet.impl.util.IOUtilTest.test_zipAndUnzipNestedFolder_then_contentsShouldBeSame(IOUtilTest.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.nio.file.NoSuchFileException: /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder_3/hazelcast/target/test-classes/nested/da7e6253-0db2-4f9f-ae65-9433202154ac
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
	at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
	at java.nio.file.Files.readAttributes(Files.java:1737)
	at java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:219)
	at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
	at java.nio.file.FileTreeWalker.next(FileTreeWalker.java:372)
	at java.nio.file.FileTreeIterator.fetchNextIfNeeded(FileTreeIterator.java:95)
```

Standard output:
```
Finished Running Test: when_zipSlipVulnerability_then_zipEntryIgnored_relativePath in 0.028 seconds.
BuildInfo right after test_zipAndUnzipNestedFolder_then_contentsShouldBeSame(com.hazelcast.jet.impl.util.IOUtilTest): BuildInfo{version='5.0-SNAPSHOT', build='20210415', buildNumber=20210415, revision=3d7a2b0, enterprise=false, serializationVersion=1, jet=JetBuildInfo{version='5.0-SNAPSHOT', build='20210415', revision='3d7a2b0'}}
Hiccups measured while running test 'test_zipAndUnzipNestedFolder_then_contentsShouldBeSame(com.hazelcast.jet.impl.util.IOUtilTest):'
12:16:15, accumulated pauses: 123 ms, max pause: 120 ms, pauses over 1000 ms: 0
```

**Comment by mmedenjak** [comment]
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/4645
