### ISSUE TITLE
"Failed to parse statistics" warning logged once every second in v4.2

### ISSUE THREAD

**Issue by APIANT** [hazelcast/hazelcast#18551]
Hi,

We upgraded from v4.0.1 to v4.2 and now see this warning logged once every second:

2021-04-16 14:09:03 [MetricsConsumer] WARN  c.h.w.service.CentralManager - Failed to parse statistics received from member Member [127.0.0.1]:5701 - a10170aa-569d-40cc-b22e-457accf59b1e of cluster dev: getCount field is null.
com.hazelcast.webmonitor.model.DeserializationException: getCount field is null
	at com.hazelcast.webmonitor.utils.JsonUtil.mandatoryMember(JsonUtil.java:75)
	at com.hazelcast.webmonitor.utils.JsonUtil.getMandatoryLong(JsonUtil.java:44)
	at com.hazelcast.webmonitor.model.hz.req.state.LocalMapStats.<init>(LocalMapStats.java:67)
	at com.hazelcast.webmonitor.utils.JsonUtil.putMembers(JsonUtil.java:84)
	at com.hazelcast.webmonitor.model.hz.req.state.MemberState.<init>(MemberState.java:60)
	at com.hazelcast.webmonitor.model.hz.req.state.TimedMemberState.<init>(TimedMemberState.java:41)
	at com.hazelcast.webmonitor.service.CentralManager.addMemberState(CentralManager.java:89)
	at com.hazelcast.webmonitor.service.MetricsConsumer.lambda$readMetrics$1(MetricsConsumer.java:55)
	at com.hazelcast.client.impl.ClientDelegatingFuture$WhenCompleteAdapter.apply(ClientDelegatingFuture.java:482)
	at com.hazelcast.client.impl.ClientDelegatingFuture$WhenCompleteAdapter.apply(ClientDelegatingFuture.java:469)
	at com.hazelcast.client.impl.spi.impl.ClientInvocationFuture$CallIdTrackingBiFunction.apply(ClientInvocationFuture.java:266)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$HandleNode.lambda$execute$0(AbstractInvocationFuture.java:1499)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

2021-04-16 14:09:04 [MetricsConsumer] WARN  c.h.w.service.CentralManager - Failed to parse statistics received from member Member [127.0.0.1]:5701 - a10170aa-569d-40cc-b22e-457accf59b1e of cluster dev: getCount field is null.
com.hazelcast.webmonitor.model.DeserializationException: getCount field is null
	at com.hazelcast.webmonitor.utils.JsonUtil.mandatoryMember(JsonUtil.java:75)
	at com.hazelcast.webmonitor.utils.JsonUtil.getMandatoryLong(JsonUtil.java:44)
	at com.hazelcast.webmonitor.model.hz.req.state.LocalMapStats.<init>(LocalMapStats.java:67)
	at com.hazelcast.webmonitor.utils.JsonUtil.putMembers(JsonUtil.java:84)
	at com.hazelcast.webmonitor.model.hz.req.state.MemberState.<init>(MemberState.java:60)
	at com.hazelcast.webmonitor.model.hz.req.state.TimedMemberState.<init>(TimedMemberState.java:41)
	at com.hazelcast.webmonitor.service.CentralManager.addMemberState(CentralManager.java:89)
	at com.hazelcast.webmonitor.service.MetricsConsumer.lambda$readMetrics$1(MetricsConsumer.java:55)
	at com.hazelcast.client.impl.ClientDelegatingFuture$WhenCompleteAdapter.apply(ClientDelegatingFuture.java:482)
	at com.hazelcast.client.impl.ClientDelegatingFuture$WhenCompleteAdapter.apply(ClientDelegatingFuture.java:469)
	at com.hazelcast.client.impl.spi.impl.ClientInvocationFuture$CallIdTrackingBiFunction.apply(ClientInvocationFuture.java:266)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$HandleNode.lambda$execute$0(AbstractInvocationFuture.java:1499)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Strangely this does not happen for us on MacOS.  This is happening on an Amazon EC2 linux instance.

Hazelcast v4.2 otherwise seems to be running ok.  We have log4j.logger.com.hazelcast=ERROR set in log4j.  Is there at least a way to suppress this warning from being logged once every second?  Or better yet a setting that will prevent the error from happening in the first place?

**Comment by APIANT** [comment]
Sorry, it seems this message is related to us not having updated the Hazelcast Management Center WAR from v4.0 to v4.2 on the Amazon instance.  Will install v4.2 and verify this error goes away.

**Comment by APIANT** [comment]
Upgrading the Hazelcast Management Center to v4.2 has resolved the issue.
