### ISSUE TITLE
Mastership fight after split cluster

### ISSUE THREAD

**Issue by WillEngFlow** [hazelcast/hazelcast#18582]
**Describe the bug**

A rogue node left the cluster and became the master of its own group. When it tried to rejoin the original cluster it was originally rejected by the other nodes. Eventually the master of the original cluster let it back in and the original master reports `java.lang.IllegalArgumentException: [10.1.0.70]:10081 claims mastership but it is not a member!` before becoming completely unresponsive and refusing all inbound network connections.

While this may be related [Split-Brain-Syndrome](https://docs.hazelcast.com/imdg/4.2/network-partitioning/network-partitioning.html) no recovery action appeared to be taken. No custom recovery behaviors have been specified.

**Expected behavior**

The expected behavior would be that the cluster recovers gracefully and the master resumes operation as normal after the rogue re-joins the cluster.

**Additional context**

***Environment***
| | |
|-|-|
|Hazelcast Version|4.0|
|Cluster Size|85|
|Number of clients|1|
|Java version| openjdk version "11.0.9.1" 2020-11-04<br />OpenJDK Runtime Environment (build 11.0.9.1+1-post-Debian-1deb10u2)<br />OpenJDK 64-Bit Server VM (build 11.0.9.1+1-post-Debian-1deb10u2, mixed mode, sharing)|
|Operating System|Debian 10|

***Timeline/Logs***

10.1.0.70 is the errant node and 10.1.0.216 is the master
<br /><br />
10.1.0.70 and 10.1.0.216 report the same cluster

10.1.0.70
```
Apr 20 00:01:17 ip-10-1-0-70 worker_service[1045]: Members {size:86, ver:1400} [
Apr 20 00:01:17 ip-10-1-0-70 worker_service[1045]:         Member [10.1.0.87]:10081 - d4be1de7-da19-4942-ad9c-fd2e762ac47c
Apr 20 00:01:17 ip-10-1-0-70 worker_service[1045]:         Member [10.1.0.5]:10081 - cf8e03d3-bc49-42a3-8136-3617bf18fc57
Apr 20 00:01:17 ip-10-1-0-70 worker_service[1045]:         Member [10.1.0.9]:10081 - 58eadcbf-af99-4b70-b977-fdffc0a198a8
...
Apr 20 00:01:17 ip-10-1-0-70 worker_service[1045]:         Member [10.1.0.70]:10081 - d81c951f-b8b3-4258-b0bc-0a14547a4896 this
...
Apr 20 00:01:17 ip-10-1-0-70 worker_service[1045]:         Member [10.1.0.216]:10081 - 7c25547c-490d-43db-be25-0aefca72dc07
```

10.1.0.216 (master)
```
Apr 20 01:40:28 ip-10-1-0-216 scheduler_service[16473]: Members {size:85, ver:1401} [
Apr 20 01:40:28 ip-10-1-0-216 scheduler_service[16473]:         Member [10.1.0.87]:10081 - d4be1de7-da19-4942-ad9c-fd2e762ac47c
Apr 20 01:40:28 ip-10-1-0-216 scheduler_service[16473]:         Member [10.1.0.5]:10081 - cf8e03d3-bc49-42a3-8136-3617bf18fc57
Apr 20 01:40:28 ip-10-1-0-216 scheduler_service[16473]:         Member [10.1.0.9]:10081 - 58eadcbf-af99-4b70-b977-fdffc0a198a8
...
Apr 20 01:40:28 ip-10-1-0-216 scheduler_service[16473]:         Member [10.1.0.70]:10081 - d81c951f-b8b3-4258-b0bc-0a14547a4896
...
Apr 20 01:40:28 ip-10-1-0-216 scheduler_service[16473]:         Member [10.1.0.216]:10081 - 7c25547c-490d-43db-be25-0aefca72dc07 this
```

<br /><br />
Next 10.1.0.70 starts reporting connection closed errors and refuses heartbeats from the other boxes.

10.1.0.70
```
Apr 20 01:45:08 ip-10-1-0-70 worker_service[1045]: W 2021-04-20 01:45:08.672 thread=hz.angry_colden.generic-operation.thread-0 [com.hazelcast.internal.cluster.impl.ClusterHeartbeatManager.null] [10.1.0.70]:10081 [common] [4.0] Ignoring heartbeat from Member [10.1.0.5]:10081 - cf8e03d3-bc49-42a3-8136-3617bf18fc57 since it is expired (now: 2021-04-20 01:40:28.841, timestamp: 2021-04-20 01:39:39.219)
```

<br /><br />
Meanwhile the master, 10.1.0.216 suspects 10.1.0.70 as dead and removes it.

10.1.0.216 (master)
```
Apr 20 01:40:37 ip-10-1-0-216 scheduler_service[16473]: W 2021-04-20 01:40:37.942 thread=hz.happy_joliot.cached.thread-17 [com.hazelcast.internal.cluster.impl.ClusterHeartbeatManager.null] [10.1.0.216]:10081 [common] [4.0] Suspecting Member [10.1.0.70]:10081 - d81c951f-b8b3-4258-b0bc-0a14547a4896 because it has not sent any heartbeats since 2021-04-20 01:39:36.097. Now: 2021-04-20 01:40:37.941, heartbeat timeout: 60000 ms, suspicion level: 1.00
Apr 20 01:40:37 ip-10-1-0-216 scheduler_service[16473]: W 2021-04-20 01:40:37.942 thread=hz.happy_joliot.cached.thread-17 [com.hazelcast.internal.cluster.impl.MembershipManager.null] [10.1.0.216]:10081 [common] [4.0] Member [10.1.0.70]:10081 - d81c951f-b8b3-4258-b0bc-0a14547a4896 is suspected to be dead for reason: Suspecting Member [10.1.0.70]:10081 - d81c951f-b8b3-4258-b0bc-0a14547a4896 because it has not sent any heartbeats since 2021-04-20 01:39:36.097. Now: 2021-04-20 01:40:37.941, heartbeat timeout: 60000 ms, suspicion level: 1.00
Apr 20 01:40:37 ip-10-1-0-216 scheduler_service[16473]: I 2021-04-20 01:40:37.942 thread=hz.happy_joliot.cached.thread-17 [com.hazelcast.internal.nio.tcp.TcpIpConnection.null] [10.1.0.216]:10081 [common] [4.0] Connection[id=22, /10.1.0.216:44235->/10.1.0.70:10081, qualifier=null, endpoint=[10.1.0.70]:10081, alive=false, connectionType=MEMBER] closed. Reason: Suspecting Member [10.1.0.70]:10081 - d81c951f-b8b3-4258-b0bc-0a14547a4896 because it has not sent any heartbeats since 2021-04-20 01:39:36.097. Now: 2021-04-20 01:40:37.941, heartbeat timeout: 60000 ms, suspicion level: 1.00
```

<br /><br />
The next member pool reports show that 10.1.0.70 has formed its own pool.

10.1.0.70
```
Apr 20 01:45:21 ip-10-1-0-70 worker_service[1045]: Members {size:1, ver:1402} [
Apr 20 01:45:21 ip-10-1-0-70 worker_service[1045]:         Member [10.1.0.70]:10081 - d81c951f-b8b3-4258-b0bc-0a14547a4896 this
Apr 20 01:45:21 ip-10-1-0-70 worker_service[1045]: ]
```

10.1.0.216 (master)
```
Apr 20 01:40:38 ip-10-1-0-216 scheduler_service[16473]: Members {size:84, ver:1402} [
Apr 20 01:40:38 ip-10-1-0-216 scheduler_service[16473]:         Member [10.1.0.87]:10081 - d4be1de7-da19-4942-ad9c-fd2e762ac47c
Apr 20 01:40:38 ip-10-1-0-216 scheduler_service[16473]:         Member [10.1.0.5]:10081 - cf8e03d3-bc49-42a3-8136-3617bf18fc57
Apr 20 01:40:38 ip-10-1-0-216 scheduler_service[16473]:         Member [10.1.0.9]:10081 - 58eadcbf-af99-4b70-b977-fdffc0a198a8
...
Apr 20 01:40:38 ip-10-1-0-216 scheduler_service[16473]:         Member [10.1.0.216]:10081 - 7c25547c-490d-43db-be25-0aefca72dc07 this
```

<br /><br />
Then, 10.1.0.70 reestablishes network connections to the cluster and tries to claim mastership of the entire cluster.

10.1.0.70
```
Apr 20 01:45:21 ip-10-1-0-70 worker_service[1045]: I 2021-04-20 01:45:21.197 thread=hz.angry_colden.IO.thread-in-1 [com.hazelcast.internal.nio.tcp.TcpIpConnection.null] [10.1.0.70]:10081 [common] [4.0] Initialized new cluster connection between /10.1.0.7
0:47297 and /10.1.0.147:10081
...
Apr 20 01:45:21 ip-10-1-0-70 worker_service[1045]: I 2021-04-20 01:45:21.360 thread=hz.angry_colden.migration [com.hazelcast.internal.partition.InternalPartitionService.null] [10.1.0.70]:10081 [common] [4.0] Most recent partition table version: 49727
Apr 20 01:45:21 ip-10-1-0-70 worker_service[1045]: W 2021-04-20 01:45:21.363 thread=hz.angry_colden.migration [com.hazelcast.internal.partition.impl.MigrationManager.null] [10.1.0.70]:10081 [common] [4.0] partitionId=0 is completely lost!
```

10.1.0.216 (master)
```
Apr 20 01:45:08 ip-10-1-0-216 scheduler_service[16473]: I 2021-04-20 01:45:08.603 thread=hz.happy_joliot.IO.thread-in-1 [com.hazelcast.internal.nio.tcp.TcpIpConnection.null] [10.1.0.216]:10081 [common] [4.0] Initialized new cluster connection between /10.1.0.216:53151 and /10.1.0.70:10081
Apr 20 01:45:08 ip-10-1-0-216 scheduler_service[16473]: I 2021-04-20 01:45:08.826 thread=hz.happy_joliot.IO.thread-in-0 [com.hazelcast.internal.nio.tcp.TcpIpConnection.null] [10.1.0.216]:10081 [common] [4.0] Initialized new cluster connection between /10.1.0.216:10081 and /10.1.0.70:48067
...
Apr 20 01:45:11 ip-10-1-0-216 scheduler_service[16473]: S 2021-04-20 01:45:11.106 thread=hz.happy_joliot.generic-operation.thread-0 [com.hazelcast.internal.cluster.impl.operations.FetchMembersViewOp.null] [10.1.0.216]:10081 [common] [4.0] [10.1.0.70]:10081 claims mastership but it is not a member!
Apr 20 01:45:11 ip-10-1-0-216 scheduler_service[16473]: java.lang.IllegalArgumentException: [10.1.0.70]:10081 claims mastership but it is not a member!
Apr 20 01:45:11 ip-10-1-0-216 scheduler_service[16473]:         at com.hazelcast.internal.util.Preconditions.checkTrue(Preconditions.java:327)
Apr 20 01:45:11 ip-10-1-0-216 scheduler_service[16473]:         at com.hazelcast.internal.cluster.impl.ClusterServiceImpl.handleMastershipClaim(ClusterServiceImpl.java:257)
Apr 20 01:45:11 ip-10-1-0-216 scheduler_service[16473]:         at com.hazelcast.internal.cluster.impl.operations.FetchMembersViewOp.run(FetchMembersViewOp.java:60)
Apr 20 01:45:11 ip-10-1-0-216 scheduler_service[16473]:         at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:184)
Apr 20 01:45:11 ip-10-1-0-216 scheduler_service[16473]:         at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:228)
Apr 20 01:45:11 ip-10-1-0-216 scheduler_service[16473]:         at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:217)
Apr 20 01:45:11 ip-10-1-0-216 scheduler_service[16473]:         at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:433)
Apr 20 01:45:11 ip-10-1-0-216 scheduler_service[16473]:         at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:166)
Apr 20 01:45:11 ip-10-1-0-216 scheduler_service[16473]:         at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:136)
Apr 20 01:45:11 ip-10-1-0-216 scheduler_service[16473]:         at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:123)
```

<br /><br />
Finally 10.1.0.70 appears to have re-joined the cluster.

10.1.0.70
```
Apr 20 01:46:17 ip-10-1-0-70 worker_service[1045]: Members {size:85, ver:1405} [
Apr 20 01:46:17 ip-10-1-0-70 worker_service[1045]:         Member [10.1.0.87]:10081 - d4be1de7-da19-4942-ad9c-fd2e762ac47c
Apr 20 01:46:17 ip-10-1-0-70 worker_service[1045]:         Member [10.1.0.5]:10081 - cf8e03d3-bc49-42a3-8136-3617bf18fc57
Apr 20 01:46:17 ip-10-1-0-70 worker_service[1045]:         Member [10.1.0.9]:10081 - 58eadcbf-af99-4b70-b977-fdffc0a198a8
...
Apr 20 01:46:17 ip-10-1-0-70 worker_service[1045]:         Member [10.1.0.216]:10081 - 7c25547c-490d-43db-be25-0aefca72dc07
...
Apr 20 01:46:17 ip-10-1-0-70 worker_service[1045]:         Member [10.1.0.70]:10081 - 99cecfb5-8cb7-4183-bde3-df43b8d33879 this
Apr 20 01:46:17 ip-10-1-0-70 worker_service[1045]: ]
```

10.1.0.216 (master)
```
Apr 20 01:46:17 ip-10-1-0-216 scheduler_service[16473]: Members {size:85, ver:1405} [
Apr 20 01:46:17 ip-10-1-0-216 scheduler_service[16473]:         Member [10.1.0.87]:10081 - d4be1de7-da19-4942-ad9c-fd2e762ac47c
Apr 20 01:46:17 ip-10-1-0-216 scheduler_service[16473]:         Member [10.1.0.5]:10081 - cf8e03d3-bc49-42a3-8136-3617bf18fc57
Apr 20 01:46:17 ip-10-1-0-216 scheduler_service[16473]:         Member [10.1.0.9]:10081 - 58eadcbf-af99-4b70-b977-fdffc0a198a8
...
Apr 20 01:46:17 ip-10-1-0-216 scheduler_service[16473]:         Member [10.1.0.216]:10081 - 7c25547c-490d-43db-be25-0aefca72dc07 this
...
Apr 20 01:46:17 ip-10-1-0-216 scheduler_service[16473]:         Member [10.1.0.70]:10081 - 99cecfb5-8cb7-4183-bde3-df43b8d33879
Apr 20 01:46:17 ip-10-1-0-216 scheduler_service[16473]: ]
```

<br /><br />
But 10.1.0.216 refuses all inbound TCP connections.

**Comment by vbekiaris** [comment]
@WillEngFlow thanks for the detailed issue report. The cluster's oldest member is on top of the member list, so in the logs you posted `10.1.0.87` seems to be the cluster's leader. That member's logs may have more information about what went wrong and cluster merge didn't happen.

In Hazelcast 4.1 there have been [improvements around partial member disconnection](https://github.com/hazelcast/hazelcast/blob/master/docs/design/cluster/02-partial-member-disconnection-resolution.md). Since you are running a fairly large number of nodes, please consider upgrading.

**Comment by WillEngFlow** [comment]
@vbekiaris Thanks for the response!

That's good to know, due to our topology I assumed `10.1.0.216` was the master. Unfortunately I don't directly manage this cluster so I don't know if we'll be able to get the logs from 10.1.0.87 for this incident.

I am trying to repro on another cluster and will let you know if I can find some solid repro steps. I'll also look into 4.1 and see if that alleviates the issue.
