### ISSUE TITLE
multiple ClientClusterProxyTest test failures

### ISSUE THREAD

**Issue by alex-dukhno** [hazelcast/hazelcast#18608]
Failed on commit https://github.com/hazelcast/hazelcast/pull/18067/commits/735c5564554b0dbf1c8bedfc0fb73d551c7800fc of the PR https://github.com/hazelcast/hazelcast/pull/18067

Failed on INSERT_PLATFORM_INFORMATION_HERE: [Jenkins](http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/4825/testReport/junit/com.hazelcast.client.impl.proxy/ClientClusterProxyTest/)

failed tests:
```
com.hazelcast.client.impl.proxy.ClientClusterProxyTest.changeClusterStateWithOptions
com.hazelcast.client.impl.proxy.ClientClusterProxyTest.getClusterState
com.hazelcast.client.impl.proxy.ClientClusterProxyTest.getClusterTime
com.hazelcast.client.impl.proxy.ClientClusterProxyTest.removeMembershipListener
```

**Error Message**
test timed out after 300000 milliseconds
**Stacktrace**
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.lang.Thread.setPriority0(Native Method)
	at java.lang.Thread.setPriority(Thread.java:1095)
	at java.lang.Thread.init(Thread.java:417)
	at java.lang.Thread.init(Thread.java:349)
	at java.lang.Thread.<init>(Thread.java:551)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.<init>(HazelcastManagedThread.java:50)
	at com.hazelcast.internal.util.executor.PoolExecutorThreadFactory$ManagedThread.<init>(PoolExecutorThreadFactory.java:56)
	at com.hazelcast.internal.util.executor.PoolExecutorThreadFactory.createThread(PoolExecutorThreadFactory.java:48)
	at com.hazelcast.internal.util.executor.PoolExecutorThreadFactory.createThread(PoolExecutorThreadFactory.java:44)
	at com.hazelcast.internal.util.executor.AbstractExecutorThreadFactory.newThread(AbstractExecutorThreadFactory.java:31)
	at java.util.concurrent.ThreadPoolExecutor$Worker.<init>(ThreadPoolExecutor.java:619)
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:932)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1378)
	at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate.addNewWorkerIfRequired(CachedExecutorServiceDelegate.java:140)
	at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate.execute(CachedExecutorServiceDelegate.java:110)
	at com.hazelcast.spi.impl.executionservice.impl.ExecutionServiceImpl.execute(ExecutionServiceImpl.java:245)
	at com.hazelcast.internal.cluster.impl.MembershipManager.sendMembershipEventNotifications(MembershipManager.java:826)
	at com.hazelcast.internal.cluster.impl.MembershipManager.sendMembershipEvents(MembershipManager.java:799)
	at com.hazelcast.internal.cluster.impl.ClusterServiceImpl.sendLocalMembershipEvent(ClusterServiceImpl.java:170)
	at com.hazelcast.instance.impl.Node.start(Node.java:450)
	at com.hazelcast.instance.impl.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:124)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:211)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:190)
	at com.hazelcast.test.TestHazelcastInstanceFactory.newHazelcastInstance(TestHazelcastInstanceFactory.java:224)
	at com.hazelcast.client.impl.proxy.ClientClusterProxyTest.client(ClientClusterProxyTest.java:58)
	at com.hazelcast.client.impl.proxy.ClientClusterProxyTest.removeMembershipListener(ClientClusterProxyTest.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by sancar** [comment]
Investigated the logs. Nothing seems out of ordinary except the timeout itself. Looks like a temporary environment problem. 
I will close this issue for now. If it happens again we will take a closer look.
