### ISSUE TITLE
MCTrustedInterfacesTest failure

### ISSUE THREAD

**Issue by alex-dukhno** [hazelcast/hazelcast#18609]
Failed on commit https://github.com/hazelcast/hazelcast/pull/18067/commits/735c5564554b0dbf1c8bedfc0fb73d551c7800fc of the PR https://github.com/hazelcast/hazelcast/pull/18067

Failed on INSERT_PLATFORM_INFORMATION_HERE: [Jenkins](http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/4825/testReport/junit/com.hazelcast.client.impl.proxy/ClientClusterProxyTest/removeMembershipListener/)

Stacktrace:
```
java.util.concurrent.TimeoutException
	at com.hazelcast.client.impl.spi.impl.ClientInvocationFuture.newTimeoutException(ClientInvocationFuture.java:63)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:656)
	at com.hazelcast.client.impl.management.MCTrustedInterfacesTest.assertFailureOnUntrustedInterface(MCTrustedInterfacesTest.java:310)
	at com.hazelcast.client.impl.management.MCTrustedInterfacesTest.testHotRestartTriggerForceStartMessageTask(MCTrustedInterfacesTest.java:225)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```
Standard output:
```
09:11:57,885  INFO |testPromoteLiteMemberMessageTask| - [ClientEndpointManager] hz.charming_cohen.event-4109 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Destroying ClientEndpoint{connection=MockedNodeConnection{ remoteAddress = [127.0.0.1]:40001, localAddress = [127.0.0.1]:5701, connectionId = 1}, clientUuid='7172a269-a17c-4fe4-b311-5307af1f3adc, authenticated=true, clientVersion=5.0-SNAPSHOT, creationTime=1619601115110, latest clientAttributes=null, labels=[]}
09:11:57,925  WARN |testPromoteLiteMemberMessageTask| - [TwoWayBlockableExecutor] pool-724-thread-1 - Dropping incoming runnable since other end closed. Server Closed EOF. MockedClientConnection{localAddress=[127.0.0.1]:40001, super=ClientConnection{alive=false, connectionId=1, channel=null, remoteAddress=[127.0.0.1]:5701, lastReadTime=2021-04-28 09:11:57.778, lastWriteTime=2021-04-28 09:11:57.686, closedTime=2021-04-28 09:11:57.852, connected server version=5.0-SNAPSHOT}}
09:11:57,926 TRACE |testRunConsoleCommandMessageTask| - [ClientListenerService] hz.client_256.eventRegistration- - hz.client_256 [dev] [5.0-SNAPSHOT] [5.0-SNAPSHOT] Register attempt of ClientListenerRegistration{codec=com.hazelcast.client.impl.spi.impl.ClientInvocationServiceImpl$1@780e036e, handler=com.hazelcast.client.impl.spi.impl.ClientInvocationServiceImpl$BackupEventHandler@b8a0e7b} to MockedClientConnection{localAddress=[127.0.0.1]:40001, super=ClientConnection{alive=true, connectionId=1, channel=null, remoteAddress=[127.0.0.1]:5701, lastReadTime=2021-04-28 09:11:57.760, lastWriteTime=2021-04-28 09:11:57.583, closedTime=never, connected server version=5.0-SNAPSHOT}}
09:11:57,928 TRACE |testRunConsoleCommandMessageTask| - [ClientListenerService] hz.client_256.eventRegistration- - hz.client_256 [dev] [5.0-SNAPSHOT] [5.0-SNAPSHOT] Registered ClientListenerRegistration{codec=com.hazelcast.client.impl.spi.impl.ClientInvocationServiceImpl$1@780e036e, handler=com.hazelcast.client.impl.spi.impl.ClientInvocationServiceImpl$BackupEventHandler@b8a0e7b} to MockedClientConnection{localAddress=[127.0.0.1]:40001, super=ClientConnection{alive=true, connectionId=1, channel=null, remoteAddress=[127.0.0.1]:5701, lastReadTime=2021-04-28 09:11:57.928, lastWriteTime=2021-04-28 09:11:57.927, closedTime=never, connected server version=5.0-SNAPSHOT}}
09:11:57,929  INFO |testRunConsoleCommandMessageTask| - [ClientStatisticsService] Thread-4529 - Client statistics is enabled with period 5 seconds.
Finished Running Test: testGetClusterMetadataMessageTask in 1198.932 seconds.
09:11:57,941 DEBUG |testPromoteLiteMemberMessageTask| - [JobCoordinationService] hz.charming_cohen.cached.thread-15 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
09:11:57,960 DEBUG |testRunConsoleCommandMessageTask| - [JobCoordinationService] hz.zen_cohen.cached.thread-42 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
09:11:57,982  INFO |testHotRestartTriggerForceStartMessageTask| - [LifecycleService] Thread-4526 - hz.client_254 [dev] [5.0-SNAPSHOT] [5.0-SNAPSHOT] HazelcastClient 5.0-SNAPSHOT (20210428 - a214661) is SHUTDOWN
09:11:57,982  INFO |testPromoteLiteMemberMessageTask| - [LifecycleService] Thread-4528 - hz.client_255 [dev] [5.0-SNAPSHOT] [5.0-SNAPSHOT] HazelcastClient 5.0-SNAPSHOT (20210428 - a214661) is SHUTDOWN
09:11:57,982 DEBUG |testHotRestartTriggerForceStartMessageTask| - [JobCoordinationService] hz.vigorous_cohen.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
09:11:57,983  INFO |testHotRestartTriggerForceStartMessageTask| - [LifecycleService] Thread-4526 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
09:11:57,986  INFO |testPromoteLiteMemberMessageTask| - [LifecycleService] Thread-4528 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
09:11:57,986 DEBUG |testPromoteLiteMemberMessageTask| - [JobCoordinationService] Thread-4528 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Added a shutting-down member: 835ce135-b254-4e66-b5de-ac903264b469
09:11:57,987 DEBUG |testHotRestartTriggerForceStartMessageTask| - [JobCoordinationService] Thread-4526 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Added a shutting-down member: 66d72dcb-25da-40dc-8746-886930990fcf
09:11:57,987  INFO |testPromoteLiteMemberMessageTask| - [Node] Thread-4528 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Shutting down connection manager...
09:11:57,987  INFO |testPromoteLiteMemberMessageTask| - [Node] Thread-4528 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Shutting down node engine...
09:11:57,987  INFO |testHotRestartTriggerForceStartMessageTask| - [Node] Thread-4526 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Shutting down connection manager...
09:11:57,987  INFO |testHotRestartTriggerForceStartMessageTask| - [Node] Thread-4526 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Shutting down node engine...
Started Running Test: testPromoteToCPMemberMessageTask
09:11:58,060 DEBUG |testRunConsoleCommandMessageTask| - [JobCoordinationService] hz.zen_cohen.cached.thread-42 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
09:11:58,099  INFO |testHotRestartTriggerForceStartMessageTask| - [NodeExtension] Thread-4526 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Destroying node NodeExtension.
09:11:58,100  INFO |testHotRestartTriggerForceStartMessageTask| - [Node] Thread-4526 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Hazelcast Shutdown is completed in 115 ms.
09:11:58,104  INFO |testHotRestartTriggerForceStartMessageTask| - [LifecycleService] Thread-4526 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
BuildInfo right after testHotRestartTriggerForceStartMessageTask(com.hazelcast.client.impl.management.MCTrustedInterfacesTest): BuildInfo{version='5.0-SNAPSHOT', build='20210428', buildNumber=20210428, revision=a214661, enterprise=false, serializationVersion=1, jet=JetBuildInfo{version='5.0-SNAPSHOT', build='20210428', revision='a214661'}}
```

**Comment by erosb** [comment]
Currently on `master` this test passes on CI, and locally as well.

It can be a source of confusion that if the `LOCAL` maven profile is not activated in IntelliJ, then the test will fail:  it won't use mock networking, and the test will not use `222.222.222.222` as a fake client IP, but it uses `127.0.0.1`, which is not listed as a trusted interface, therefore the client call gets rejected.

Closing the issue. (cc @mmedenjak  )
