### ISSUE TITLE
MCMessageTasksTest

### ISSUE THREAD

**Issue by alex-dukhno** [hazelcast/hazelcast#18610]
Failed on commit https://github.com/hazelcast/hazelcast/pull/18067/commits/735c5564554b0dbf1c8bedfc0fb73d551c7800fc of the PR https://github.com/hazelcast/hazelcast/pull/18067

Failed on INSERT_PLATFORM_INFORMATION_HERE: [Jenkins](http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/4825/testReport/junit/com.hazelcast.client.impl.management/MCMessageTasksTest/testRemoveCPMemberMessageTask/)

Error Message
```
Could not get initial member list from cluster!
```
Stacktrace
```
java.lang.IllegalStateException: Could not get initial member list from cluster!
	at com.hazelcast.client.impl.spi.impl.ClientClusterServiceImpl.waitInitialMemberListFetched(ClientClusterServiceImpl.java:203)
	at com.hazelcast.client.impl.clientside.HazelcastClientInstanceImpl.waitForInitialMembershipEvents(HazelcastClientInstanceImpl.java:858)
	at com.hazelcast.client.impl.clientside.HazelcastClientInstanceImpl.start(HazelcastClientInstanceImpl.java:398)
	at com.hazelcast.client.test.TestHazelcastFactory.newHazelcastClient(TestHazelcastFactory.java:93)
	at com.hazelcast.client.test.TestHazelcastFactory.newHazelcastClient(TestHazelcastFactory.java:70)
	at com.hazelcast.client.test.TestHazelcastFactory.newHazelcastClient(TestHazelcastFactory.java:66)
	at com.hazelcast.client.impl.management.MCMessageTasksTest.setUp(MCMessageTasksTest.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:393)
	at com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37)
	at com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:104)
	at com.hazelcast.test.metrics.MetricsRule$1.evaluate(MetricsRule.java:62)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at com.hazelcast.test.HazelcastParallelClassRunner.access$301(HazelcastParallelClassRunner.java:49)
	at com.hazelcast.test.HazelcastParallelClassRunner$TestRunner.run(HazelcastParallelClassRunner.java:162)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by promanenko** [comment]
Can't reproduce
