### ISSUE TITLE
SQL can not return array of Portable as response

### ISSUE THREAD

**Issue by sancar** [hazelcast/hazelcast#18615]
Sql trying to serialize an array of Portable to Data when returning as column type which is Portable Array. And it is not supported at the moment by the serialization service. Serialization Service treats any array of object as Java Serializable which we don't expect as the response. 

A solution to the issue https://github.com/hazelcast/hazelcast/issues/18595 can potentially fix this one as well. I have created a separate issue for now because the root causes are different and we may choose different approaches to fix this.

**Comment by srknzl** [comment]
My test in js
```js
it.skip('should be able to decode/serialize nested portable array', async function () {
        const classroom = new Classroom('asd', [
            new Student(long.fromNumber(12), 123.23),
            new Student(long.fromNumber(13), 123.23)
        ]);

        await someMap.put(0, classroom);
        const result = client.getSqlService().execute(`SELECT * FROM ${mapName}`);

        const rowMetadata = await result.getRowMetadata(); // response throws error
        rowMetadata.getColumnByIndex(rowMetadata.findColumn('students')).type.should.be.eq(SqlColumnType.OBJECT);
        rowMetadata.getColumnByIndex(rowMetadata.findColumn('className')).type.should.be.eq(SqlColumnType.VARCHAR);

        const row = (await result.next()).value;
        row['className'].should.be.eq(classroom.className);
        row['students'].should.be.eq(classroom.students);
        row['__key'].should.be.eq(0);
    });
```

Stack trace:
```
java.io.NotSerializableException: Student
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
	at java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1378)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1174)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at com.hazelcast.internal.serialization.impl.defaultserializers.JavaDefaultSerializers$JavaSerializer.write(JavaDefaultSerializers.java:118)
	at com.hazelcast.internal.serialization.impl.defaultserializers.JavaDefaultSerializers$JavaSerializer.write(JavaDefaultSerializers.java:111)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.write(StreamSerializerAdapter.java:39)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:175)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:154)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toData(AbstractSerializationService.java:139)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toData(AbstractSerializationService.java:127)
	at com.hazelcast.sql.impl.client.SqlPage$RowsetColumnIterator.next(SqlPage.java:305)
	at com.hazelcast.client.impl.protocol.codec.builtin.ListMultiFrameCodec.encode(ListMultiFrameCodec.java:41)
	at com.hazelcast.client.impl.protocol.codec.builtin.SqlPageCodec.encode(SqlPageCodec.java:146)
	at com.hazelcast.client.impl.protocol.codec.builtin.CodecUtil.encodeNullable(CodecUtil.java:50)
	at com.hazelcast.client.impl.protocol.codec.SqlExecuteCodec.encodeResponse(SqlExecuteCodec.java:160)
	at com.hazelcast.sql.impl.client.SqlExecuteMessageTask.encodeResponse(SqlExecuteMessageTask.java:84)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.sendResponse(AbstractMessageTask.java:243)
	at com.hazelcast.client.impl.protocol.task.AbstractCallableMessageTask.processMessage(AbstractCallableMessageTask.java:36)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:153)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:116)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
```

**Comment by srknzl** [comment]
The similar thing happens to identified serialization. The problem is similar, arrays are not treated as identified arrays but regular arrays. 

Error:
```
Error: Failed to resolve value metadata: Problem while reading DataSerializable, namespace: 66, ID: 102, class: 'null', exception: com.hazelcast.core.HazelcastJsonValue cannot be cast to [LStreet;
```
Example usage:
```js
const street1 = new Street('a');
const street2 = new Street('b');
const street3 = new Street('c');
const addresses1 = new Addresses([street1, street2], 2);
const addresses2 = new Addresses([street1, street3], 3);
const addresses3 = new Addresses([street2, street3], 4);

await someMap.put(0, addresses1);
await someMap.put(1, addresses2);
await someMap.put(2, addresses3);

const result = client.getSqlService().execute(`SELECT * FROM ${mapName} WHERE zipCode > ? AND zipCode < ?`,
    [long.fromNumber(2), long.fromNumber(5)]);
```

**Comment by viliam-durina** [comment]
Consider this class:
```
class Outer implements IDS/Portable { 
    public Inner[] innerArray;
    // writeData(), readData()...
}
```

If the class is IDS and the query selects `innerArray`, we have to deserialize the whole `Outer` instance, extract `innerArray` field, and then send the `Inner[]` instance to the client. But we don't know how the outer class would serialize it, whether as a java array or as an IDS array. And we even should not care - we send a tuple of values, `Inner[]` is just `Inner[]` regardless where it comes from. It can be even non-serializable, if the outer class handles the serialization. SQL engine, once we support SQL arrays, will have its own format defined by the `SqlPage` and `SqlPageCodec`. Until we have that, I'm reluctant to add some preliminary support because there will be an expectation of b-w compatibility.

The situation is similar for Portable I think. Portable allows us to extract individual fields without deserializing the whole `Outer` instance. We can extract the strip of bytes from the whole serialized `Outer` instance pertaining to `innerArray`, but I'm not sure we can use the strip for anything out of context of the `Outer` deserialization. I'm not sure this is the way to go.

The `innerArray` field is mapped as OBJECT. For this type the rule should be "serde the same way as if it was used for IMap value". E.g. consider you have `IMap<Integer, Inner[]>` - would the non-java client be able to handle it?

**Comment by sancar** [comment]
> The innerArray field is mapped as OBJECT. For this type the rule should be "serde the same way as if it was used for IMap value". E.g. consider you have IMap<Integer, Inner[]> - would the non-java client be able to handle it?

We need to think about the backward compatibility in more detail(I see no problem as I am writing), but I was thinking the fix it on the IMap level.
More specifically when we say serializationService.toData(inner_array) , Inner[] will be mapped to `PORTABLE_ARRAY` which we will introduce as new root type instead of `OBJECT`.
Same goes for IdentifiedDataSerializable and DataSerializable. 

@viliam-durina Wdyt ?

**Comment by viliam-durina** [comment]
@sancar we're discussing exactly this: #19154 :)
