### ISSUE TITLE
ClientExecutorServiceCancelTest test failure

### ISSUE THREAD

**Issue by alex-dukhno** [hazelcast/hazelcast#18611]
Failed on commit https://github.com/hazelcast/hazelcast/pull/18067/commits/735c5564554b0dbf1c8bedfc0fb73d551c7800fc of the PR https://github.com/hazelcast/hazelcast/pull/18067

Failed on INSERT_PLATFORM_INFORMATION_HERE:[Jenkins](http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/4825/testReport/junit/com.hazelcast.client.executor/ClientExecutorServiceCancelTest/testCancel_submitToMember1_withSmartRouting_WaitTaskStart/)

Error Message
```
test timed out after 300000 milliseconds
```
Stacktrace
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at com.sun.org.apache.xpath.internal.compiler.XPathParser.lookahead(XPathParser.java:305)
	at com.sun.org.apache.xpath.internal.compiler.XPathParser.NodeTest(XPathParser.java:1882)
	at com.sun.org.apache.xpath.internal.compiler.XPathParser.Basis(XPathParser.java:1797)
	at com.sun.org.apache.xpath.internal.compiler.XPathParser.Step(XPathParser.java:1733)
	at com.sun.org.apache.xpath.internal.compiler.XPathParser.RelativeLocationPath(XPathParser.java:1637)
	at com.sun.org.apache.xpath.internal.compiler.XPathParser.LocationPath(XPathParser.java:1608)
	at com.sun.org.apache.xpath.internal.compiler.XPathParser.PathExpr(XPathParser.java:1328)
	at com.sun.org.apache.xpath.internal.compiler.XPathParser.UnionExpr(XPathParser.java:1247)
	at com.sun.org.apache.xpath.internal.compiler.XPathParser.UnaryExpr(XPathParser.java:1153)
	at com.sun.org.apache.xpath.internal.compiler.XPathParser.MultiplicativeExpr(XPathParser.java:1074)
	at com.sun.org.apache.xpath.internal.compiler.XPathParser.AdditiveExpr(XPathParser.java:1016)
	at com.sun.org.apache.xpath.internal.compiler.XPathParser.RelationalExpr(XPathParser.java:941)
	at com.sun.org.apache.xpath.internal.compiler.XPathParser.EqualityExpr(XPathParser.java:881)
	at com.sun.org.apache.xpath.internal.compiler.XPathParser.AndExpr(XPathParser.java:845)
	at com.sun.org.apache.xpath.internal.compiler.XPathParser.OrExpr(XPathParser.java:818)
	at com.sun.org.apache.xpath.internal.compiler.XPathParser.Expr(XPathParser.java:801)
	at com.sun.org.apache.xpath.internal.compiler.XPathParser.initXPath(XPathParser.java:133)
	at com.sun.org.apache.xpath.internal.XPath.<init>(XPath.java:178)
	at com.sun.org.apache.xpath.internal.XPath.<init>(XPath.java:268)
	at com.sun.org.apache.xpath.internal.jaxp.XPathImpl.eval(XPathImpl.java:189)
	at com.sun.org.apache.xpath.internal.jaxp.XPathImpl.evaluate(XPathImpl.java:271)
	at com.hazelcast.config.AbstractXmlConfigBuilder.replaceVariables(AbstractXmlConfigBuilder.java:115)
	at com.hazelcast.config.AbstractXmlConfigBuilder.replaceImports(AbstractXmlConfigBuilder.java:131)
	at com.hazelcast.config.AbstractXmlConfigBuilder.process(AbstractXmlConfigBuilder.java:99)
	at com.hazelcast.client.config.XmlClientConfigBuilder.parseAndBuildConfig(XmlClientConfigBuilder.java:171)
	at com.hazelcast.client.config.XmlClientConfigBuilder.build(XmlClientConfigBuilder.java:154)
	at com.hazelcast.client.config.XmlClientConfigBuilder.build(XmlClientConfigBuilder.java:147)
	at com.hazelcast.client.config.XmlClientConfigBuilder.build(XmlClientConfigBuilder.java:142)
	at com.hazelcast.client.executor.ClientExecutorServiceCancelTest.createClient(ClientExecutorServiceCancelTest.java:88)
	at com.hazelcast.client.executor.ClientExecutorServiceCancelTest.testCancel_submitToMember(ClientExecutorServiceCancelTest.java:173)
	at com.hazelcast.client.executor.ClientExecutorServiceCancelTest.testCancel_submitToMember1_withSmartRouting_WaitTaskStart(ClientExecutorServiceCancelTest.java:135)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by mmedenjak** [comment]
Looks like the test timed out while parsing the config. I suggest we close this one until next failure.

**Comment by mmedenjak** [comment]
The pauses on the test are really immense, the CPU load is at 100%, clock jumps, multiple tests failing, everything. Closing since there's nothing we can do really. If it happens again, we have to evaluate how to decrease the loads on the machines.
