### ISSUE TITLE
BootstrappedInstance doesn't start in the platform package

### ISSUE THREAD

**Issue by vladoschreiner** [hazelcast/hazelcast#18627]
**Describe the bug**

Starting Jet Instance using fails with a misleading error. E.g.

`Jet.bootstrappedInstance();`

Compiles but fails during startup with:

```
/Library/Java/JavaVirtualMachines/jdk1.8.0_161.jdk/Contents/Home/bin/java -javaagent:/Applications/IntelliJ IDEA CE.app/Contents/lib/idea_rt.jar=49445:/Applications/IntelliJ IDEA CE.app/Contents/bin -Dfile.encoding=UTF-8 -classpath /Library/Java/JavaVirtualMachines/jdk1.8.0_161.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_161.jdk/Contents/Home/jre/lib/deploy.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_161.jdk/Contents/Home/jre/lib/ext/cldrdata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_161.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_161.jdk/Contents/Home/jre/lib/ext/jaccess.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_161.jdk/Contents/Home/jre/lib/ext/jfxrt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_161.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_161.jdk/Contents/Home/jre/lib/ext/nashorn.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_161.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_161.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_161.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_161.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_161.jdk/Contents/Home/jre/lib/javaws.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_161.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_161.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_161.jdk/Contents/Home/jre/lib/jfxswt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_161.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_161.jdk/Contents/Home/jre/lib/management-agent.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_161.jdk/Contents/Home/jre/lib/plugin.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_161.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_161.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_161.jdk/Contents/Home/lib/ant-javafx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_161.jdk/Contents/Home/lib/dt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_161.jdk/Contents/Home/lib/javafx-mx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_161.jdk/Contents/Home/lib/jconsole.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_161.jdk/Contents/Home/lib/packager.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_161.jdk/Contents/Home/lib/sa-jdi.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_161.jdk/Contents/Home/lib/tools.jar:/Users/vladimir/Documents/IdeaProjects/hazelcast-jet-training/essentials/target/classes:/Users/vladimir/.m2/repository/com/hazelcast/hazelcast/5.0-SNAPSHOT/hazelcast-5.0-20210503.090100-135.jar:/Users/vladimir/.m2/repository/log4j/log4j/1.2.17/log4j-1.2.17.jar solutions.Solution6
09:22:33.307 [ INFO] [c.h.c.Hazelcast] Bootstrapped instance requested but application wasn't called from jet submit script. Creating a standalone Jet instance instead.
09:22:33.523 [ INFO] [c.h.i.c.AbstractConfigLocator] Loading 'hazelcast.yml' from the classpath.
Exception in thread "main" java.lang.IllegalArgumentException: instanceName must contain text
	at com.hazelcast.internal.util.Preconditions.checkHasText(Preconditions.java:43)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.getOrCreateHazelcastInstance(HazelcastInstanceFactory.java:94)
	at com.hazelcast.core.Hazelcast.getOrCreateHazelcastInstance(Hazelcast.java:165)
	at com.hazelcast.jet.impl.JetBootstrap.createStandaloneInstance(JetBootstrap.java:249)
	at com.hazelcast.jet.impl.JetBootstrap.lambda$getInstance$4(JetBootstrap.java:224)
	at com.hazelcast.jet.impl.util.ConcurrentMemoizingSupplier.get(ConcurrentMemoizingSupplier.java:50)
	at com.hazelcast.jet.impl.JetBootstrap.getInstance(JetBootstrap.java:226)
	at com.hazelcast.jet.Jet.bootstrappedInstance(Jet.java:106)
	at solutions.Solution6.main(Solution6.java:36)

Process finished with exit code 1
```

**Expected behavior**

The API works as in Jet 4.5 or I should be given migration instructions.

**To Reproduce**

Use `Hazelcast 5.0-SNAPSHOT` package.

Start Jet using 
`Jet.bootstrappedInstance();`

**Comment by mmedenjak** [comment]
Related: https://hazelcast.atlassian.net/browse/PLAT-39
