### ISSUE TITLE
GracefulShutdown[*]Test fails sporadically on a mac

### ISSUE THREAD

**Issue by lprimak** [hazelcast/hazelcast#18640]
In master branch as of May 5th,
fails on GracefulShutdownTest, GracefulShutdownCorrectnessTest, etc. at random
This is on a mac with -PparallelTest

Stacktrace:
```
[ERROR] Tests run: 12, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 166.401 s <<< FAILURE! - in com.hazelcast.internal.partition.GracefulShutdownCorrectnessTest
[ERROR] testPartitionData_whenNodesStartedShutdown_whileOperationsOngoing[backups:0,nodes:2,shutdown:1](com.hazelcast.internal.partition.GracefulShutdownCorrectnessTest)  Time elapsed: 162.432 s  <<< ERROR!
java.util.concurrent.CompletionException: com.hazelcast.core.OperationTimeoutException: TestPutOperation invocation failed to complete due to operation-heartbeat-timeout. Current time: 2021-05-05 22:08:04.554. Start time: 2021-05-05 22:06:04.000. Total elapsed time: 120554 ms. Last operation heartbeat: never. Last operation heartbeat from member: never. Invocation{op=com.hazelcast.internal.partition.service.TestPutOperation{serviceName='TestMigrationAwareService', identityHash=116323780, partitionId=62, replicaIndex=0, callId=-7284, invocationTime=1620270364000 (2021-05-05 22:06:04.000), waitTimeout=-1, callTimeout=60000, tenantControl=com.hazelcast.spi.impl.tenantcontrol.NoopTenantControl@0}, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=60000, firstInvocationTimeMs=1620270364000, firstInvocationTime='2021-05-05 22:06:04.000', lastHeartbeatMillis=0, lastHeartbeatTime='1969-12-31 18:00:00.000', target=[127.0.0.1]:5705, pendingResponse={VOID}, backupsAcksExpected=-1, backupsAcksReceived=0, connection=null}
	at com.hazelcast.spi.impl.AbstractInvocationFuture.returnOrThrowWithJoinConventions(AbstractInvocationFuture.java:819)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.resolveAndThrowWithJoinConvention(AbstractInvocationFuture.java:835)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.join(AbstractInvocationFuture.java:553)
	at com.hazelcast.internal.partition.AbstractGracefulShutdownCorrectnessTest.testPartitionData_whenNodesStartedShutdown_whileOperationsOngoing(AbstractGracefulShutdownCorrectnessTest.java:147)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.hazelcast.core.OperationTimeoutException: TestPutOperation invocation failed to complete due to operation-heartbeat-timeout. Current time: 2021-05-05 22:08:04.554. Start time: 2021-05-05 22:06:04.000. Total elapsed time: 120554 ms. Last operation heartbeat: never. Last operation heartbeat from member: never. Invocation{op=com.hazelcast.internal.partition.service.TestPutOperation{serviceName='TestMigrationAwareService', identityHash=116323780, partitionId=62, replicaIndex=0, callId=-7284, invocationTime=1620270364000 (2021-05-05 22:06:04.000), waitTimeout=-1, callTimeout=60000, tenantControl=com.hazelcast.spi.impl.tenantcontrol.NoopTenantControl@0}, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=60000, firstInvocationTimeMs=1620270364000, firstInvocationTime='2021-05-05 22:06:04.000', lastHeartbeatMillis=0, lastHeartbeatTime='1969-12-31 18:00:00.000', target=[127.0.0.1]:5705, pendingResponse={VOID}, backupsAcksExpected=-1, backupsAcksReceived=0, connection=null}
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.newOperationTimeoutException(InvocationFuture.java:194)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:136)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.resolveAndThrowWithJoinConvention(AbstractInvocationFuture.java:834)
	... 14 more
```

Another one:

```
[ERROR] Tests run: 6, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 172.82 s <<< FAILURE! - in com.hazelcast.internal.partition.PartitionAssignmentsCorrectnessTest
[ERROR] testPartitionAssignments_whenNodesStartedTerminated[backups:3,nodes:4](com.hazelcast.internal.partition.PartitionAssignmentsCorrectnessTest)  Time elapsed: 152.598 s  <<< FAILURE!
java.lang.AssertionError: On Member [127.0.0.1]:5702 - fd92ffef-77f2-4ac9-ac53-6705beb07383 this, Not member: [127.0.0.1]:5703 - 9f91763b-5b41-4682-b9c6-c1017fb540a7
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertNotNull(Assert.java:713)
	at com.hazelcast.internal.partition.PartitionCorrectnessTestSupport.assertPartitionAssignments(PartitionCorrectnessTestSupport.java:205)
	at com.hazelcast.internal.partition.AbstractPartitionAssignmentsCorrectnessTest$1.run(AbstractPartitionAssignmentsCorrectnessTest.java:83)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1248)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1350)
	at com.hazelcast.internal.partition.AbstractPartitionAssignmentsCorrectnessTest.assertPartitionAssignmentsEventually(AbstractPartitionAssignmentsCorrectnessTest.java:80)
	at com.hazelcast.internal.partition.AbstractPartitionAssignmentsCorrectnessTest.assertPartitionAssignmentsEventually(AbstractPartitionAssignmentsCorrectnessTest.java:76)
	at com.hazelcast.internal.partition.AbstractPartitionAssignmentsCorrectnessTest.testPartitionAssignments_whenNodesStartedTerminated(AbstractPartitionAssignmentsCorrectnessTest.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by mmedenjak** [comment]
Possibly related - https://github.com/hazelcast/hazelcast/issues/8065 and https://github.com/hazelcast/hazelcast/issues/18163.

The first error doesn't tell much. It's possible that the JVM process stalled, and then the operation failed to execute in the expected time. Not much to conclude other than that without inspecting more into the rest of the logs.

The other error is a bit more interesting, but it may be already covered by the above mentioned two issues.

**Comment by mmedenjak** [comment]
Closing as we have other two issues on the same test class, and I just noticed that the second test ran for a long time as well (`Time elapsed: 152.598 s`) so it might have been also stalled. Also, I suspect we can't fetch the full logs anymore and we can reassess after we've fixed the linked issues.
