### ISSUE TITLE
ClientCacheThroughHazelcastInstanceTest.getCache_whenOwnerInstanceIsShutdown_thenOperateOnCacheFails

### ISSUE THREAD

**Issue by mdumandag** [hazelcast/hazelcast#18656]
Failed on the PR builder of #18650 (Although the PR is against the 4.2.z branch, the same problem applies to the 5.0)

[Jenkins URL
](http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/4937/testReport/junit/com.hazelcast.client.cache.instance/ClientCacheThroughHazelcastInstanceTest/getCache_whenOwnerInstanceIsShutdown_thenOperateOnCacheFails/)

com.hazelcast.client.cache.instance.ClientCacheThroughHazelcastInstanceTest.getCache_whenOwnerInstanceIsShutdown_thenOperateOnCacheFails

Stacktrace:
```
java.lang.AssertionError: Expected exception type: class com.hazelcast.client.HazelcastClientNotActiveException, but actual exception type: class com.hazelcast.spi.exception.TargetDisconnectedException
	at org.junit.Assert.fail(Assert.java:89)
	at com.hazelcast.cache.instance.CacheThroughHazelcastInstanceTest.whenOwnerInstanceIsShutdown_thenOperateOnCacheFails(CacheThroughHazelcastInstanceTest.java:352)
	at com.hazelcast.cache.instance.CacheThroughHazelcastInstanceTest.getCache_whenOwnerInstanceIsShutdown_thenOperateOnCacheFails(CacheThroughHazelcastInstanceTest.java:324)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)```

**Comment by olukas** [comment]
Reopening this issue for `4.2.z` branch, it failed on that branch on Sonar build (Oracle JDK 8): http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-4.maintenance-sonar/879/testReport/com.hazelcast.client.cache.instance/ClientCacheThroughHazelcastInstanceTest/getCache_whenOwnerInstanceIsShutdown_thenOperateOnCacheFails/ 

It can be probably fixed by backporting https://github.com/hazelcast/hazelcast/pull/18658 to maintenance branch.

**Comment by mmedenjak** [comment]
Closing as fixed by https://github.com/hazelcast/hazelcast/pull/19195. @mdumandag feel free to reopen if that's not the case.

**Comment by frant-hartm** [comment]
Failure older than April 1st. Closing.
