### ISSUE TITLE
No DataSerializerFactory registered for namespace: -2000 (version 4.1 - as Hibernate 2nd level cache - native client mode - using HazelcastLocalCacheRegionFactory)

### ISSUE THREAD

**Issue by imadabdan** [hazelcast/hazelcast#18657]
Hello, 
I am trying to use Hazelcast 4.1 as Hibernate's 2nd level cache provider in native client mode, I installed Hazelcast cluster v 4.1 from the corresponding docker image without any specific serialization configuration.

my persistence.xml related properties look like this:

```xml
<property name="hibernate.cache.use_second_level_cache" value="true"/>
<property name="hibernate.cache.use_query_cache" value="true"/>
<property name="hibernate.cache.region.factory_class" value="com.hazelcast.hibernate.HazelcastLocalCacheRegionFactory"/>
<property name="hibernate.session_factory_name" value="com.hazelcast.hibernate.HazelcastLocalCacheRegionFactory"/>
<property name="hibernate.cache.hazelcast.use_native_client" value="true"/>
<property name="hibernate.cache.hazelcast.native_client_address" value="127.0.0.1:5701"/>
<property name="hibernate.cache.hazelcast.native_client_group" value="dev"/>
<property name="hibernate.cache.hazelcast.native_client_password" value=""/>
```

Note: I am deploying the app on Payara Server V5.2021.2

the application is running successfully and the invalidation topics are created on the Hazelcast cluster side, but whenever any entity is created/updated I get this exception:
 ```yaml
 hz.client_1 [dev] [4.1] hz.client_1.event-9 caught an exception while processing:com.hazelcast.client.impl.spi.impl.listener.ClientListenerServiceImpl$ClientEventProcessor@35eb4fba
com.hazelcast.nio.serialization.HazelcastSerializationException: No DataSerializerFactory registered for namespace: -2000
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.readInternal(DataSerializableSerializer.java:139)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:106)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:51)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:44)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:205)
	at com.hazelcast.topic.impl.DataAwareMessage.getMessageObject(DataAwareMessage.java:44)
	at com.hazelcast.hibernate.local.LocalRegionCache.lambda$createMessageListener$0(LocalRegionCache.java:247)
	at com.hazelcast.client.impl.proxy.ClientTopicProxy$TopicItemHandler.handleTopicEvent(ClientTopicProxy.java:132)
	at com.hazelcast.client.impl.protocol.codec.TopicAddMessageListenerCodec$AbstractEventHandler.handle(TopicAddMessageListenerCodec.java:139)
	at com.hazelcast.client.impl.proxy.ClientTopicProxy$TopicItemHandler.handle(ClientTopicProxy.java:120)
	at com.hazelcast.client.impl.spi.impl.listener.ClientListenerServiceImpl.handleEventMessageOnCallingThread(ClientListenerServiceImpl.java:189)
	at com.hazelcast.client.impl.spi.impl.listener.ClientListenerServiceImpl$ClientEventProcessor.run(ClientListenerServiceImpl.java:356)
	at com.hazelcast.internal.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:245)
	at com.hazelcast.internal.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:228)
```

**Libraries:**
Hibernate:5.4.12.Final
hazelcast:4.1
hazelcast-hibernate53:2.2.0

**Environment:**
JDK 11
Payara Server 5.2021.2

no exceptions in the Hazelcast cluster's log.

Thanks,

**Comment by mmedenjak** [comment]
@imadabdan thank you for your report. @pivovarit @enozcan any ideas about this issue?

**Comment by imadabdan** [comment]
After I changed the log level to **FINE** I got this:
`Failed to load com.hazelcast.hibernate.serialization.HibernateDataSerializerHook by com.hazelcast [403]. This indicates a classloading issue. It can happen in a runtime with a complicated classloading model (OSGi, Java EE, etc)`

**Comment by imadabdan** [comment]
I found out the issue, it was caused by the way of class-loading in the **Payara** server. Since **Payara** is already shipped with Hazelcast, the **Payara**'s classloader is loading the **hazelcast.jar** available in the glassfish/modules folder, while `HibernateDataSerializerHook` is available in another jar which is **hazelcast-hibernate53-2.2.0**, this jar is included in our war and not available in **Payara**, so it is loaded with the war classloader (which is different from the one that loaded **hazelcast.jar**), and that is causing the problem.
You can check [this link](https://docs.payara.fish/community/docs/5.2021.2/documentation/payara-server/classloading.html#default-class-and-library-loading) and I quote from them:

> Payara Server Community has included many standard Java libraries and packages, for example Jackson, Nimbus JOSE, Logback, and others to use. These libraries are located on the ${PAYARA_INSTALL_DIR}/modules directory.
> 
> The default class loading mechanism of Payara Server Community works like this: When loading classes that belong to a library or framework that is included in the server, the server will always load those classes even if the application itself includes different versions.

The solution was to add `<class-loader delegate="false"/>` to your **glassfish-web.xml** file.

**Comment by mmedenjak** [comment]
Great, thanks for the analysis and happy that you managed to solve it. Closing as I don't see any improvement on our end.
