### ISSUE TITLE
State for job is intermittently corrupted after forceful terminate

### ISSUE THREAD

**Issue by viliam-durina** [hazelcast/hazelcast#18675]
Migrated from hazelcast/hazelcast-jet#2842

State for job is intermittently corrupted if one of members is terminated forcefully and job is restarted from snapshot. It means long running job can fail with that. It fails with exception like:

```
ERROR || - [MasterJobContext] hz.kind_pasteur.cached.thread-11 - Execution of job 'JMS Test source to middle queue', execution 059c-7a24-756f-0002 failed
        Start time: 2021-01-20T17:56:27.305
        Duration: 00:00:00.046
        To see additional job metrics enable JobConfig.storeMetricsAfterJobCompletion
com.hazelcast.jet.JetException: State for job 'JMS Test source to middle queue', execution 059c-7a24-756f-0002 in IMap '__jet.snapshot.059b-def0-66c0-0002.0' is corrupted: it should have 8 entries, but has 7
        at com.hazelcast.jet.impl.SnapshotValidator.validateSnapshot(SnapshotValidator.java:60) ~[hazelcast-jet-enterprise-4.4.jar:?]
        at com.hazelcast.jet.impl.MasterJobContext.rewriteDagWithSnapshotRestore(MasterJobContext.java:361) ~[hazelcast-jet-enterprise-4.4.jar:?]
        at com.hazelcast.jet.impl.MasterJobContext.lambda$tryStartJob$2(MasterJobContext.java:210) ~[hazelcast-jet-enterprise-4.4.jar:?]
        at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$46(JobCoordinationService.java:1039) ~[hazelcast-jet-enterprise-4.4.jar:?]
        at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$47(JobCoordinationService.java:1060) ~[hazelcast-jet-enterprise-4.4.jar:?]
        at com.hazelcast.internal.util.executor.CompletableFutureTask.run(CompletableFutureTask.java:64) [hazelcast-jet-enterprise-4.4.jar:?]
        at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217) [hazelcast-jet-enterprise-4.4.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_272]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_272]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_272]
        at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76) [hazelcast-jet-enterprise-4.4.jar:?]
        at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) [hazelcast-jet-enterprise-4.4.jar:?]
```

We haven't observed this issue with graceful shutdown.

We hit this issue in following soak tests:

-    `jms-test`
-    `stateful-map-test`
-    `snapshot-jms-sink-test`
-    `snapshot-jdbc-test`

**Comment by Holmistr** [comment]
Moving it to 5.2 as we should take a look at it.

**Comment by k-jamroz** [comment]
Underlying cause is that `IMap.put` used for snapshot map returns success also in case of backup timeout (after `hazelcast.operation.backup.timeout.millis` in `BaseInvocation.detectAndHandleBackupTimeout`). This means that in case of master failure snapshot may be corrupted because not all partitions are actually replicated.

**Comment by k-jamroz** [comment]
A kind of workaround, but with wide impact on all `IMap` operations and possibly also other structures as well, is setting `hazelcast.operation.fail.on.indeterminate.state=true`.
