### ISSUE TITLE
OS to EE rolling restart  Node could not join cluster HazelcastSerializationException

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#18680]
http://jenkins.hazelcast.com/view/rollup/job/rollup-os-ee/

/disk1/workspace/rollup-os-ee/5.0-SNAPSHOT/2021_05_13-13_27_55/os-ee

```
May 13, 2021 1:29:20 PM com.hazelcast.cp.internal.raftop.metadata.PublishActiveCPMembersOp
WARNING: [10.0.0.185]:5701 [HZ] [5.0-SNAPSHOT] com.hazelcast.spi.exception.CallerNotMemberException: Not Member! this: [10.0.0.185]:5701, caller: [10.0.0.98]:5701, partitionId: -1, operation: com.hazelcast.cp.internal.raftop.metadata.PublishActiveCPMembersOp, service: hz:core:raft
May 13, 2021 1:29:20 PM com.hazelcast.internal.cluster.impl.operations.FinalizeJoinOp
SEVERE: [10.0.0.185]:5701 [HZ] [5.0-SNAPSHOT] Node could not join cluster.
com.hazelcast.nio.serialization.HazelcastSerializationException: java.lang.IllegalStateException: Field count[-1393754107] in stream does not match ClassDefinition{factoryId=-1, classId=173, version=0, fieldDefinitions=[]}
	at com.hazelcast.internal.serialization.impl.SerializationUtil.handleException(SerializationUtil.java:103)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.readObject(AbstractSerializationService.java:295)
	at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readObject(ByteArrayObjectDataInput.java:592)
	at com.hazelcast.cache.impl.PreJoinCacheConfig.readTenant(PreJoinCacheConfig.java:89)
	at com.hazelcast.config.CacheConfig.readData(CacheConfig.java:556)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.readIdentifiedDataSerializable(EnterpriseDataSerializableSerializer.java:161)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.doRead(EnterpriseDataSerializableSerializer.java:130)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.read(EnterpriseDataSerializableSerializer.java:124)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.read(EnterpriseDataSerializableSerializer.java:52)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:44)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.readObject(AbstractSerializationService.java:289)
	at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readObject(ByteArrayObjectDataInput.java:592)
	at com.hazelcast.cache.impl.operation.OnJoinCacheOperation.readInternal(OnJoinCacheOperation.java:96)
	at com.hazelcast.spi.impl.operationservice.Operation.readData(Operation.java:755)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.readIdentifiedDataSerializable(EnterpriseDataSerializableSerializer.java:161)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.doRead(EnterpriseDataSerializableSerializer.java:130)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.read(EnterpriseDataSerializableSerializer.java:124)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.read(EnterpriseDataSerializableSerializer.java:52)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:44)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.readObject(AbstractSerializationService.java:289)
	at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readObject(ByteArrayObjectDataInput.java:592)
	at com.hazelcast.internal.serialization.impl.SerializationUtil.readList(SerializationUtil.java:392)
	at com.hazelcast.internal.serialization.impl.SerializationUtil.readCollection(SerializationUtil.java:372)
	at com.hazelcast.internal.cluster.impl.operations.OnJoinOp.readInternal(OnJoinOp.java:140)
	at com.hazelcast.spi.impl.operationservice.Operation.readData(Operation.java:755)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.readIdentifiedDataSerializable(EnterpriseDataSerializableSerializer.java:161)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.doRead(EnterpriseDataSerializableSerializer.java:130)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.read(EnterpriseDataSerializableSerializer.java:124)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.read(EnterpriseDataSerializableSerializer.java:52)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:44)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.readObject(AbstractSerializationService.java:289)
	at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readObject(ByteArrayObjectDataInput.java:592)
	at com.hazelcast.internal.cluster.impl.operations.FinalizeJoinOp.readOnJoinOp(FinalizeJoinOp.java:185)
	at com.hazelcast.internal.cluster.impl.operations.FinalizeJoinOp.readInternalImpl(FinalizeJoinOp.java:175)
	at com.hazelcast.internal.cluster.impl.operations.MembersUpdateOp.readInternal(MembersUpdateOp.java:123)
	at com.hazelcast.spi.impl.operationservice.Operation.readData(Operation.java:755)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.readIdentifiedDataSerializable(EnterpriseDataSerializableSerializer.java:161)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.doRead(EnterpriseDataSerializableSerializer.java:130)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.read(EnterpriseDataSerializableSerializer.java:124)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.read(EnterpriseDataSerializableSerializer.java:52)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:44)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:208)
	at com.hazelcast.spi.impl.NodeEngineImpl.toObject(NodeEngineImpl.java:355)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:454)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:197)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:137)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
Caused by: java.lang.IllegalStateException: Field count[-1393754107] in stream does not match ClassDefinition{factoryId=-1, classId=173, version=0, fieldDefinitions=[]}
	at com.hazelcast.internal.serialization.impl.portable.PortableInternalGenericRecord.<init>(PortableInternalGenericRecord.java:85)
	at com.hazelcast.internal.serialization.impl.portable.PortableSerializer.readPortableGenericRecord(PortableSerializer.java:338)
	at com.hazelcast.internal.serialization.impl.portable.PortableSerializer.read(PortableSerializer.java:102)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:44)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.readObject(AbstractSerializationService.java:289)
	... 46 more

May 13, 2021 1:29:20 PM com.hazelcast.instance.impl.Node
WARNING: [10.0.0.185]:5701 [HZ] [5.0-SNAPSHOT] Terminating forcefully...
May 13, 2021 1:29:20 PM com.hazelcast.instance.impl.Node
INFO: [10.0.0.185]:5701 [HZ] [5.0-SNAPSHOT] Shutting down connection manager...
May 13, 2021 1:29:20 PM com.hazelcast.internal.server.tcp.TcpServerConnection
INFO: [10.0.0.185]:5701 [HZ] [5.0-SNAPSHOT] Connection[id=2, /10.0.0.185:60961->/10.0.0.229:5701, qualifier=null, endpoint=[10.0.0.229]:5701, alive=false, connectionType=MEMBER, planeIndex=0] closed. Reason: TcpServer is stopping
May 13, 2021 1:29:20 PM com.hazelcast.internal.server.tcp.TcpServerConnection
INFO: [10.0.0.185]:5701 [HZ] [5.0-SNAPSHOT] Connection[id=1, /10.0.0.185:60793->/10.0.0.5:5701, qualifier=null, endpoint=[10.0.0.5]:5701, alive=false, connectionType=MEMBER, planeIndex=0] closed. Reason: TcpServer is stopping
May 13, 2021 1:29:20 PM com.hazelcast.internal.server.tcp.TcpServerConnection
INFO: [10.0.0.185]:5701 [HZ] [5.0-SNAPSHOT] Connection[id=3, /10.0.0.185:38803->/10.0.0.98:5701, qualifier=null, endpoint=[10.0.0.98]:5701, alive=false, connectionType=MEMBER, planeIndex=0] closed. Reason: TcpServer is stopping
May 13, 2021 1:29:20 PM com.hazelcast.instance.impl.Node
INFO: [10.0.0.185]:5701 [HZ] [5.0-SNAPSHOT] Shutting down node engine...
May 13, 2021 1:29:20 PM com.hazelcast.instance.impl.NodeExtension
INFO: [10.0.0.185]:5701 [HZ] [5.0-SNAPSHOT] Destroying node NodeExtension.
May 13, 2021 1:29:20 PM com.hazelcast.instance.impl.Node
INFO: [10.0.0.185]:5701 [HZ] [5.0-SNAPSHOT] Hazelcast Shutdown is completed in 24 ms.
May 13, 2021 1:29:24 PM com.hazelcast.instance.impl.Node
SEVERE: [10.0.0.185]:5701 [HZ] [5.0-SNAPSHOT] Could not join cluster. Shutting down now!
May 13, 2021 1:29:24 PM com.hazelcast.core.LifecycleService
INFO: [10.0.0.185]:5701 [HZ] [5.0-SNAPSHOT] [10.0.0.185]:5701 is SHUTTING_DOWN
May 13, 2021 1:29:24 PM com.hazelcast.instance.impl.Node
INFO: [10.0.0.185]:5701 [HZ] [5.0-SNAPSHOT] Node is already shutting down... Waiting for shutdown process to complete...
May 13, 2021 1:29:24 PM com.hazelcast.core.LifecycleService
INFO: [10.0.0.185]:5701 [HZ] [5.0-SNAPSHOT] [10.0.0.185]:5701 is SHUTDOWN
May 13, 2021 1:29:24 PM com.hazelcast.instance.impl.Node
INFO: [10.0.0.185]:5701 [HZ] [5.0-SNAPSHOT] Node is already shutting down... Waiting for shutdown process to complete...
java.lang.IllegalStateException: Node failed to start!
```

**Comment by mmedenjak** [comment]
Moving to backlog. RU was not designed with this requirement in mind but I had suspected it might work. It doesn't but we may invest in the future into making it happen.
