### ISSUE TITLE
Inconsistent cast of temporal value types

### ISSUE THREAD

**Issue by AyberkSorgun** [hazelcast/hazelcast#18698]
this query works if I sent `LocalTime` object as value

`select cast(? as TIMESTAMP) from map`

this query doesn’t work

`select cast(CAST('13:00' as TIME) as TIMESTAMP) from map`

it throws `ClassCastException`

`Caused by: java.lang.ClassCastException: java.util.GregorianCalendar cannot be cast to java.time.LocalTime
at com.hazelcast.sql.impl.type.converter.LocalTimeConverter.cast(LocalTimeConverter.java:73)
at com.hazelcast.sql.impl.type.converter.LocalTimeConverter.asTimestamp(LocalTimeConverter.java:53)
at com.hazelcast.sql.impl.type.converter.LocalDateTimeConverter.convertToSelf(LocalDateTimeConverter.java:69)
at com.hazelcast.sql.impl.calcite.HazelcastSqlToRelConverter.convertCast(HazelcastSqlToRelConverter.java:169)
... 49 more`

First point to investigate if calcite eliminates this cast in the sql-to-rel conversion phase

**Comment by mmedenjak** [comment]
@viliam-durina can you take a look, is this something that needs to be fixed in 5.0?

**Comment by gierlachg** [comment]
🤔  it works for me/now. Not sure whether anything has changed in the meantime. @AyberkSorgun can we close it?

**Comment by mmedenjak** [comment]
Looks like neither Neil nor Jaromir opened it. I'm out of ideas. I suggest that if when Ayberk comes back next week and if we can't remember who's the author to check - just close it.
