### ISSUE TITLE
hazelcast OperationTimeoutException on 4.0.3

### ISSUE THREAD

**Issue by kulsagar325** [hazelcast/hazelcast#18709]
Hello,
**Describe the bug**
I am using hazelcast server/client version 4.0.3 in our production environment, this cluster consists of 4 nodes, with default configuration.  
and sometimes we faced issue of com.hazelcast.core.OperationTimeoutException during connection. 
To resolve the issue, I have to take restart of all the hazelcast server nodes which is causing lot of trouble, as my server go down as it looses the connection to hazelcast server.

Its observed only during the deployment. When we shutdown the entire nodes and bring them back again, and try connecting the client. 

- Logs and stack traces, 
```
Constructor threw exception; nested exception is com.hazelcast.core.OperationTimeoutException: ClientInvocation{clientMessage = ClientMessage{connection=null, length=561, operation=Cache.CreateConfig, isRetryable=true, correlationId=519, messageType=130600, isEvent=false, isfragmented=false}, objectName = /hz/ff4jFeatures, target = partition 45, sendConnection = ClientConnection{alive=true, connectionId=1, channel=NioChannel{/X.X.X.X:YYYYY->/X.X.X.X:YYYYY}, remoteEndpoint=[X.X.X.X]:YYYYY, lastReadTime=2021-03-25 12:42:26.185, lastWriteTime=2021-03-25 12:42:22.349, closedTime=never, connected server version=4.0.3}} timed out because exception occurred after client invocation timeout 120000 ms. Current time: 2021-03-25 12:42:26.187. Start time: 2021-03-25 12:39:31.185. Total elapsed time: 175002 ms.

  at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:586) ~[spring-beans-4.3.25.RELEASE.jar:4.3.25.RELEASE]
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:87) ~[spring-beans-4.3.25.RELEASE.jar:4.3.25.RELEASE]
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:364) ~[spring-beans-4.3.25.RELEASE.jar:4.3.25.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1268) ~[spring-beans-4.3.25.RELEASE.jar:4.3.25.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:551) ~[spring-beans-4.3.25.RELEASE.jar:4.3.25.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:481) ~[spring-beans-4.3.25.RELEASE.jar:4.3.25.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312) ~[spring-beans-4.3.25.RELEASE.jar:4.3.25.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.25.RELEASE.jar:4.3.25.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308) ~[spring-beans-4.3.25.RELEASE.jar:4.3.25.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.25.RELEASE.jar:4.3.25.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:756) ~[spring-beans-4.3.25.RELEASE.jar:4.3.25.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867) ~[spring-context-4.3.25.RELEASE.jar:4.3.25.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542) ~[spring-context-4.3.25.RELEASE.jar:4.3.25.RELEASE]
        at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:443) ~[spring-web-4.3.22.RELEASE.jar:4.3.22.RELEASE]
        at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:325) [spring-web-4.3.22.RELEASE.jar:4.3.22.RELEASE]
        at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107) [spring-web-4.3.22.RELEASE.jar:4.3.22.RELEASE]
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4689) [catalina.jar:8.5.57]
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5155) [catalina.jar:8.5.57]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [catalina.jar:8.5.57]
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:743) [catalina.jar:8.5.57]
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:719) [catalina.jar:8.5.57]
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705) [catalina.jar:8.5.57]
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:970) [catalina.jar:8.5.57]
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1840) [catalina.jar:8.5.57]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_265]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_265]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_265]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_265]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
```

I found these 2 issues, related to above issue, 
https://github.com/hazelcast/hazelcast/issues/2778
https://github.com/hazelcast/hazelcast/issues/2516

Can someone confirm this issue still exists in 4.0.3 version ? and if yes, how can we mitigate it.
Thanks in advance. 

**To Reproduce**
Not available

Further details - 
- Hazelcast version- 4.0.3
- Hazelcast client version- 4.0.3
- integration module versions - tomcat 8, spring-boot-2.2.2.RELEASE 
- Cluster size - 4
- Number of the clients - 8
- Version of Java. - zulu1.8.0_265
- Operating system. -
```
bash-4.2$ lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: OracleServer
Description:    Oracle Linux Server release 7.9
Release:        7.9
Codename:       n/a
```

```
bash-4.2$ lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                8
On-line CPU(s) list:   0-7
Thread(s) per core:    1
Core(s) per socket:    4
Socket(s):             2
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 63
Model name:            Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz
Stepping:              0
CPU MHz:               2499.998
BogoMIPS:              4999.99
Virtualization:        VT-x
Hypervisor vendor:     VMware
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              30720K
NUMA node0 CPU(s):     0-7
```

**Comment by mmedenjak** [comment]
@kulsagar325 `OperationTimeoutException` is a rather generic problem - a message was sent but there was no response. There might be tens of different reasons why it happens. It's really hard to tell which one exactly.

Can you attach both the member and client logs during the time of this exception? By inspecting member logs, we may detect if there is some problem on the member side.
