### ISSUE TITLE
ExecutionLifecycleTest.when_processorProcessThrows_then_failJob

### ISSUE THREAD

**Issue by kwart** [hazelcast/hazelcast#18707]
The `ExecutionLifecycleTest.when_processorProcessThrows_then_failJob` failed in PR builder on `master` branch:
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/5119/

Stacktrace:
```
java.lang.AssertionError: expected:<4> but was:<6>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at com.hazelcast.jet.core.ExecutionLifecycleTest.assertPClosedWithError(ExecutionLifecycleTest.java:765)
	at com.hazelcast.jet.core.ExecutionLifecycleTest.when_processorProcessThrows_then_failJob(ExecutionLifecycleTest.java:327)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by viliam-durina** [comment]
I guess this is related: https://github.com/hazelcast/hazelcast/pull/18712#issuecomment-843973816
