### ISSUE TITLE
com.hazelcast.internal.cluster.impl.MembershipUpdateTest.connectionsToRemovedMember_shouldBeClosed

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#18708]
_4.2.z_ (commit e22aab3cffbb36863a91276dd2506b4fcf4a7f6c)

Failed on CorrettoJDK11: http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-4.maintenance-CorrettoJDK11/132/testReport/com.hazelcast.internal.cluster.impl/MembershipUpdateTest/connectionsToRemovedMember_shouldBeClosed/

Stacktrace:
```
java.lang.AssertionError: Cluster size is not correct. Expected: 3, actual: 1, instance index: 0
	at org.junit.Assert.fail(Assert.java:89)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSize(HazelcastTestSupport.java:1034)
	at com.hazelcast.test.HazelcastTestSupport$11.run(HazelcastTestSupport.java:1062)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1247)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1264)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:1059)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:1047)
	at com.hazelcast.internal.cluster.impl.MembershipUpdateTest.connectionsToRemovedMember_shouldBeClosed(MembershipUpdateTest.java:796)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Standard output:
```
3:52:33,832  INFO |connectionsToRemovedMember_shouldBeClosed| - [HealthMonitor] hz.silly_neumann.HealthMonitor - [127.0.0.1]:5702 [dev] [4.2.1-SNAPSHOT] processors=72, physical.memory.total=377.6G, physical.memory.free=143.0G, swap.space.total=4.0G, swap.space.free=2.0G, heap.memory.used=1.2G, heap.memory.free=2.8G, heap.memory.total=4.0G, heap.memory.max=4.0G, heap.memory.used/total=29.86%, heap.memory.used/max=29.86%, minor.gc.count=74, minor.gc.time=12252ms, major.gc.count=4, major.gc.time=1837ms, load.process=0.00%, load.system=76.19%, load.systemAverage=5320.42, thread.count=581, thread.peakCount=9764, cluster.timeDiff=0, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=47, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=0, clientEndpoint.count=0, connection.active.count=0, client.connection.count=0, connection.count=0
03:52:43,217  INFO |connectionsToRemovedMember_shouldBeClosed| - [HealthMonitor] hz.vigorous_neumann.HealthMonitor - [127.0.0.1]:5701 [dev] [4.2.1-SNAPSHOT] processors=72, physical.memory.total=377.6G, physical.memory.free=142.5G, swap.space.total=4.0G, swap.space.free=2.0G, heap.memory.used=1.2G, heap.memory.free=2.8G, heap.memory.total=4.0G, heap.memory.max=4.0G, heap.memory.used/total=30.11%, heap.memory.used/max=30.11%, minor.gc.count=74, minor.gc.time=12252ms, major.gc.count=4, major.gc.time=1837ms, load.process=0.00%, load.system=85.71%, load.systemAverage=4594.41, thread.count=580, thread.peakCount=9764, cluster.timeDiff=0, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=59, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=0, clientEndpoint.count=0, connection.active.count=0, client.connection.count=0, connection.count=0
03:52:53,835  INFO |connectionsToRemovedMember_shouldBeClosed| - [HealthMonitor] hz.silly_neumann.HealthMonitor - [127.0.0.1]:5702 [dev] [4.2.1-SNAPSHOT] processors=72, physical.memory.total=377.6G, physical.memory.free=143.0G, swap.space.total=4.0G, swap.space.free=2.0G, heap.memory.used=1.2G, heap.memory.free=2.8G, heap.memory.total=4.0G, heap.memory.max=4.0G, heap.memory.used/total=30.39%, heap.memory.used/max=30.39%, minor.gc.count=74, minor.gc.time=12252ms, major.gc.count=4, major.gc.time=1837ms, load.process=0.00%, load.system=92.31%, load.systemAverage=4223.81, thread.count=570, thread.peakCount=9764, cluster.timeDiff=0, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=47, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=0, clientEndpoint.count=0, connection.active.count=0, client.connection.count=0, connection.count=0
03:52:55,317  INFO |connectionsToRemovedMember_shouldBeClosed| - [HealthMonitor] hz.naughty_neumann.HealthMonitor - [127.0.0.1]:5703 [dev] [4.2.1-SNAPSHOT] processors=72, physical.memory.total=377.6G, physical.memory.free=142.7G, swap.space.total=4.0G, swap.space.free=2.0G, heap.memory.used=1.2G, heap.memory.free=2.8G, heap.memory.total=4.0G, heap.memory.max=4.0G, heap.memory.used/total=30.43%, heap.memory.used/max=30.43%, minor.gc.count=74, minor.gc.time=12252ms, major.gc.count=4, major.gc.time=1837ms, load.process=0.00%, load.system=100.00%, load.systemAverage=3977.11, thread.count=570, thread.peakCount=9764, cluster.timeDiff=0, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=85, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=0, clientEndpoint.count=0, connection.active.count=0, client.connection.count=0, connection.count=0
03:53:03,220  INFO |connectionsToRemovedMember_shouldBeClosed| - [HealthMonitor] hz.vigorous_neumann.HealthMonitor - [127.0.0.1]:5701 [dev] [4.2.1-SNAPSHOT] processors=72, physical.memory.total=377.6G, physical.memory.free=142.1G, swap.space.total=4.0G, swap.space.free=2.0G, heap.memory.used=1.2G, heap.memory.free=2.8G, heap.memory.total=4.0G, heap.memory.max=4.0G, heap.memory.used/total=30.63%, heap.memory.used/max=30.63%, minor.gc.count=74, minor.gc.time=12252ms, major.gc.count=4, major.gc.time=1837ms, load.process=0.00%, load.system=92.86%, load.systemAverage=3873.96, thread.count=570, thread.peakCount=9764, cluster.timeDiff=0, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=59, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=0, clientEndpoint.count=0, connection.active.count=0, client.connection.count=0, connection.count=0
03:53:13,838  INFO |connectionsToRemovedMember_shouldBeClosed| - [HealthMonitor] hz.silly_neumann.HealthMonitor - [127.0.0.1]:5702 [dev] [4.2.1-SNAPSHOT] processors=72, physical.memory.total=377.6G, physical.memory.free=141.0G, swap.space.total=4.0G, swap.space.free=2.0G, heap.memory.used=1.2G, heap.memory.free=2.8G, heap.memory.total=4.0G, heap.memory.max=4.0G, heap.memory.used/total=30.90%, heap.memory.used/max=30.90%, minor.gc.count=74, minor.gc.time=12252ms, major.gc.count=4, major.gc.time=1837ms, load.process=0.00%, load.system=100.00%, load.systemAverage=3462.08, thread.count=568, thread.peakCount=9764, cluster.timeDiff=0, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=47, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=0, clientEndpoint.count=0, connection.active.count=0, client.connection.count=0, connection.count=0
03:53:15,771  INFO |connectionsToRemovedMember_shouldBeClosed| - [HealthMonitor] hz.naughty_neumann.HealthMonitor - [127.0.0.1]:5703 [dev] [4.2.1-SNAPSHOT] processors=72, physical.memory.total=377.6G, physical.memory.free=141.0G, swap.space.total=4.0G, swap.space.free=2.0G, heap.memory.used=1.2G, heap.memory.free=2.8G, heap.memory.total=4.0G, heap.memory.max=4.0G, heap.memory.used/total=30.96%, heap.memory.used/max=30.96%, minor.gc.count=74, minor.gc.time=12252ms, major.gc.count=4, major.gc.time=1837ms, load.process=0.00%, load.system=92.31%, load.systemAverage=3215.75, thread.count=567, thread.peakCount=9764, cluster.timeDiff=0, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=85, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=0, clientEndpoint.count=0, connection.active.count=0, client.connection.count=0, connection.count=0
03:53:15,840  INFO |connectionsToRemovedMember_shouldBeClosed| - [LifecycleService] Thread-6869 - [127.0.0.1]:5703 [dev] [4.2.1-SNAPSHOT] [127.0.0.1]:5703 is SHUTTING_DOWN
03:53:15,840  WARN |connectionsToRemovedMember_shouldBeClosed| - [Node] Thread-6869 - [127.0.0.1]:5703 [dev] [4.2.1-SNAPSHOT] Terminating forcefully...
03:53:15,841  INFO |connectionsToRemovedMember_shouldBeClosed| - [Node] Thread-6869 - [127.0.0.1]:5703 [dev] [4.2.1-SNAPSHOT] Shutting down connection manager...
03:53:15,841  INFO |connectionsToRemovedMember_shouldBeClosed| - [Node] Thread-6869 - [127.0.0.1]:5703 [dev] [4.2.1-SNAPSHOT] Shutting down node engine...
03:53:16,174  INFO |connectionsToRemovedMember_shouldBeClosed| - [NodeExtension] Thread-6869 - [127.0.0.1]:5703 [dev] [4.2.1-SNAPSHOT] Destroying node NodeExtension.
03:53:16,175  INFO |connectionsToRemovedMember_shouldBeClosed| - [Node] Thread-6869 - [127.0.0.1]:5703 [dev] [4.2.1-SNAPSHOT] Hazelcast Shutdown is completed in 335 ms.
03:53:16,175  INFO |connectionsToRemovedMember_shouldBeClosed| - [LifecycleService] Thread-6869 - [127.0.0.1]:5703 [dev] [4.2.1-SNAPSHOT] [127.0.0.1]:5703 is SHUTDOWN
03:53:16,175  INFO |connectionsToRemovedMember_shouldBeClosed| - [LifecycleService] Thread-6869 - [127.0.0.1]:5702 [dev] [4.2.1-SNAPSHOT] [127.0.0.1]:5702 is SHUTTING_DOWN
03:53:16,175  WARN |connectionsToRemovedMember_shouldBeClosed| - [Node] Thread-6869 - [127.0.0.1]:5702 [dev] [4.2.1-SNAPSHOT] Terminating forcefully...
03:53:16,175  INFO |connectionsToRemovedMember_shouldBeClosed| - [Node] Thread-6869 - [127.0.0.1]:5702 [dev] [4.2.1-SNAPSHOT] Shutting down connection manager...
03:53:16,175  INFO |connectionsToRemovedMember_shouldBeClosed| - [Node] Thread-6869 - [127.0.0.1]:5702 [dev] [4.2.1-SNAPSHOT] Shutting down node engine...
03:53:16,268  INFO |connectionsToRemovedMember_shouldBeClosed| - [NodeExtension] Thread-6869 - [127.0.0.1]:5702 [dev] [4.2.1-SNAPSHOT] Destroying node NodeExtension.
03:53:16,268  INFO |connectionsToRemovedMember_shouldBeClosed| - [Node] Thread-6869 - [127.0.0.1]:5702 [dev] [4.2.1-SNAPSHOT] Hazelcast Shutdown is completed in 93 ms.
03:53:16,275  INFO |connectionsToRemovedMember_shouldBeClosed| - [LifecycleService] Thread-6869 - [127.0.0.1]:5702 [dev] [4.2.1-SNAPSHOT] [127.0.0.1]:5702 is SHUTDOWN
03:53:16,275  INFO |connectionsToRemovedMember_shouldBeClosed| - [LifecycleService] Thread-6869 - [127.0.0.1]:5701 [dev] [4.2.1-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
03:53:16,285  WARN |connectionsToRemovedMember_shouldBeClosed| - [Node] Thread-6869 - [127.0.0.1]:5701 [dev] [4.2.1-SNAPSHOT] Terminating forcefully...
03:53:16,285  INFO |connectionsToRemovedMember_shouldBeClosed| - [Node] Thread-6869 - [127.0.0.1]:5701 [dev] [4.2.1-SNAPSHOT] Shutting down connection manager...
03:53:16,285  INFO |connectionsToRemovedMember_shouldBeClosed| - [Node] Thread-6869 - [127.0.0.1]:5701 [dev] [4.2.1-SNAPSHOT] Shutting down node engine...
03:53:16,442  INFO |connectionsToRemovedMember_shouldBeClosed| - [NodeExtension] Thread-6869 - [127.0.0.1]:5701 [dev] [4.2.1-SNAPSHOT] Destroying node NodeExtension.
03:53:16,444  INFO |connectionsToRemovedMember_shouldBeClosed| - [Node] Thread-6869 - [127.0.0.1]:5701 [dev] [4.2.1-SNAPSHOT] Hazelcast Shutdown is completed in 159 ms.
03:53:16,444  INFO |connectionsToRemovedMember_shouldBeClosed| - [LifecycleService] Thread-6869 - [127.0.0.1]:5701 [dev] [4.2.1-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
BuildInfo right after connectionsToRemovedMember_shouldBeClosed(com.hazelcast.internal.cluster.impl.MembershipUpdateTest): BuildInfo{version='4.2.1-SNAPSHOT', build='20210519', buildNumber=20210519, revision=e22aab3, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'connectionsToRemovedMember_shouldBeClosed(com.hazelcast.internal.cluster.impl.MembershipUpdateTest):'
03:49:40, accumulated pauses: 769 ms, max pause: 437 ms, pauses over 1000 ms: 0
03:49:45, accumulated pauses: 467 ms, max pause: 21 ms, pauses over 1000 ms: 0
03:49:50, accumulated pauses: 1523 ms, max pause: 1137 ms, pauses over 1000 ms: 1
03:49:55, accumulated pauses: 8670 ms, max pause: 8304 ms, pauses over 1000 ms: 1
03:50:05, accumulated pauses: 272 ms, max pause: 9 ms, pauses over 1000 ms: 0
03:50:10, accumulated pauses: 9237 ms, max pause: 9186 ms, pauses over 1000 ms: 1
03:50:15, accumulated pauses: 45 ms, max pause: 8 ms, pauses over 1000 ms: 0
03:50:20, accumulated pauses: 7393 ms, max pause: 7361 ms, pauses over 1000 ms: 1
03:50:25, accumulated pauses: 261 ms, max pause: 9 ms, pauses over 1000 ms: 0
03:50:30, accumulated pauses: 747 ms, max pause: 14 ms, pauses over 1000 ms: 0
03:50:35, accumulated pauses: 1633 ms, max pause: 392 ms, pauses over 1000 ms: 0
03:50:40, accumulated pauses: 594 ms, max pause: 11 ms, pauses over 1000 ms: 0
03:50:45, accumulated pauses: 869 ms, max pause: 10 ms, pauses over 1000 ms: 0
03:50:50, accumulated pauses: 1688 ms, max pause: 1298 ms, pauses over 1000 ms: 1
03:50:55, accumulated pauses: 510 ms, max pause: 10 ms, pauses over 1000 ms: 0
03:51:00, accumulated pauses: 728 ms, max pause: 12 ms, pauses over 1000 ms: 0
03:51:05, accumulated pauses: 5209 ms, max pause: 5094 ms, pauses over 1000 ms: 1
03:51:10, accumulated pauses: 167 ms, max pause: 5 ms, pauses over 1000 ms: 0
03:51:15, accumulated pauses: 5356 ms, max pause: 5271 ms, pauses over 1000 ms: 1
03:51:20, accumulated pauses: 390 ms, max pause: 22 ms, pauses over 1000 ms: 0
03:51:25, accumulated pauses: 2249 ms, max pause: 1719 ms, pauses over 1000 ms: 1
03:51:30, accumulated pauses: 814 ms, max pause: 25 ms, pauses over 1000 ms: 0
03:51:35, accumulated pauses: 3592 ms, max pause: 3186 ms, pauses over 1000 ms: 1
03:51:40, accumulated pauses: 620 ms, max pause: 22 ms, pauses over 1000 ms: 0
03:51:45, accumulated pauses: 3494 ms, max pause: 3380 ms, pauses over 1000 ms: 1
03:51:50, accumulated pauses: 217 ms, max pause: 6 ms, pauses over 1000 ms: 0
03:51:55, accumulated pauses: 644 ms, max pause: 438 ms, pauses over 1000 ms: 0
03:52:00, accumulated pauses: 217 ms, max pause: 7 ms, pauses over 1000 ms: 0
03:52:05, accumulated pauses: 4020 ms, max pause: 3858 ms, pauses over 1000 ms: 1
03:52:10, accumulated pauses: 149 ms, max pause: 5 ms, pauses over 1000 ms: 0
03:52:15, accumulated pauses: 2574 ms, max pause: 2425 ms, pauses over 1000 ms: 1
03:52:20, accumulated pauses: 948 ms, max pause: 548 ms, pauses over 1000 ms: 0
03:52:25, accumulated pauses: 203 ms, max pause: 5 ms, pauses over 1000 ms: 0
03:52:30, accumulated pauses: 200 ms, max pause: 11 ms, pauses over 1000 ms: 0
03:52:35, accumulated pauses: 67 ms, max pause: 6 ms, pauses over 1000 ms: 0
03:52:40, accumulated pauses: 48 ms, max pause: 1 ms, pauses over 1000 ms: 0
03:52:45, accumulated pauses: 81 ms, max pause: 5 ms, pauses over 1000 ms: 0
03:52:50, accumulated pauses: 179 ms, max pause: 31 ms, pauses over 1000 ms: 0
03:52:55, accumulated pauses: 226 ms, max pause: 25 ms, pauses over 1000 ms: 0
03:53:00, accumulated pauses: 185 ms, max pause: 19 ms, pauses over 1000 ms: 0
03:53:05, accumulated pauses: 66 ms, max pause: 7 ms, pauses over 1000 ms: 0
03:53:10, accumulated pauses: 79 ms, max pause: 5 ms, pauses over 1000 ms: 0
03:53:15, accumulated pauses: 623 ms, max pause: 579 ms, pauses over 1000 ms: 0
```

**Comment by olukas** [comment]
Failed also with Zulu JDK 15: http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-4.maintenance-ZuluJDK15/46/testReport/com.hazelcast.internal.cluster.impl/MembershipUpdateTest/connectionsToRemovedMember_shouldBeClosed/

**Comment by olukas** [comment]
Closing this issue because:
- it hasn't occurred since we configured `CPU shares = 8` for Docker container which runs the test.
- it seems to be related to big hiccups or timeout issue

We will reopen the issue if it fails again in the future.
