### ISSUE TITLE
com.hazelcast.jet.kinesis.KinesisFailureTest.com.hazelcast.jet.kinesis.KinesisFailureTest

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#18718]
_master_ (commit 333a1b9168df26f7fdcb95b833f2b417f3e4dbca)

Failed on OracleJDK 8 with nightly profile: http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-OracleJDK8-nightly/845/testReport/com.hazelcast.jet.kinesis/KinesisFailureTest/com_hazelcast_jet_kinesis_KinesisFailureTest/

Stacktrace:
```
org.testcontainers.containers.ContainerLaunchException: Container startup failed
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:330)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:311)
	at org.testcontainers.containers.GenericContainer.starting(GenericContainer.java:1022)
	at org.testcontainers.containers.FailureDetectingExternalResource$1.evaluate(FailureDetectingExternalResource.java:29)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.testcontainers.containers.FailureDetectingExternalResource$1.evaluate(FailureDetectingExternalResource.java:30)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.testcontainers.containers.ContainerFetchException: Can't get Docker image: RemoteDockerImage(imageName=localstack/localstack:localstack/localstack, imagePullPolicy=DefaultPullPolicy())
	at org.testcontainers.containers.GenericContainer.getDockerImageName(GenericContainer.java:1279)
	at org.testcontainers.containers.GenericContainer.logger(GenericContainer.java:613)
	at org.testcontainers.containers.localstack.LocalStackContainer.configure(LocalStackContainer.java:69)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:316)
	... 9 more
Caused by: com.github.dockerjava.api.exception.BadRequestException: {"message":"no such image: localstack/localstack:localstack/localstack: invalid reference format"}

	at com.github.dockerjava.okhttp.OkHttpInvocationBuilder.execute(OkHttpInvocationBuilder.java:283)
	at com.github.dockerjava.okhttp.OkHttpInvocationBuilder.execute(OkHttpInvocationBuilder.java:271)
	at com.github.dockerjava.okhttp.OkHttpInvocationBuilder.get(OkHttpInvocationBuilder.java:239)
	at com.github.dockerjava.okhttp.OkHttpInvocationBuilder.get(OkHttpInvocationBuilder.java:89)
	at com.github.dockerjava.core.exec.InspectImageCmdExec.execute(InspectImageCmdExec.java:28)
	at com.github.dockerjava.core.exec.InspectImageCmdExec.execute(InspectImageCmdExec.java:13)
	at com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21)
	at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
	at com.github.dockerjava.core.command.InspectImageCmdImpl.exec(InspectImageCmdImpl.java:40)
	at org.testcontainers.images.LocalImagesCache.refreshCache(LocalImagesCache.java:42)
	at org.testcontainers.images.AbstractImagePullPolicy.shouldPull(AbstractImagePullPolicy.java:24)
	at org.testcontainers.images.RemoteDockerImage.resolve(RemoteDockerImage.java:59)
	at org.testcontainers.images.RemoteDockerImage.resolve(RemoteDockerImage.java:26)
	at org.testcontainers.utility.LazyFuture.getResolvedValue(LazyFuture.java:20)
	at org.testcontainers.utility.LazyFuture.get(LazyFuture.java:27)
	at org.testcontainers.containers.GenericContainer.getDockerImageName(GenericContainer.java:1277)
	... 12 more
```

Standard output:
```
2021-05-19 09:06:21,619 [ INFO] [Time-limited test] [o.t.d.DockerClientProviderStrategy]: Loaded org.testcontainers.dockerclient.EnvironmentAndSystemPropertyClientProviderStrategy from ~/.testcontainers.properties, will try it first
2021-05-19 09:06:22,257 [ INFO] [Time-limited test] [o.t.d.EnvironmentAndSystemPropertyClientProviderStrategy]: Found docker client settings from environment
2021-05-19 09:06:22,257 [ INFO] [Time-limited test] [o.t.d.DockerClientProviderStrategy]: Found Docker environment with Environment variables, system properties and defaults. Resolved dockerHost=unix:///var/run/docker.sock
2021-05-19 09:06:22,411 [ INFO] [Time-limited test] [o.t.DockerClientFactory]: Docker host IP address is 172.17.0.1
2021-05-19 09:06:22,444 [ INFO] [Time-limited test] [o.t.DockerClientFactory]: Connected to docker: 
  Server Version: 18.06.1-ce
  API Version: 1.38
  Operating System: Red Hat Enterprise Linux
  Total Memory: 386667 MB
2021-05-19 09:06:22,583 [ WARN] [Time-limited test] [o.t.u.RegistryAuthLocator]: Failure when attempting to lookup auth config (dockerImageName: testcontainersofficial/ryuk:0.3.0, configFile: /home/jenkins/.docker/config.json. Falling back to docker-java default behaviour. Exception message: /home/jenkins/.docker/config.json (No such file or directory)
2021-05-19 09:06:23,607 [ INFO] [Time-limited test] [o.t.DockerClientFactory]: Ryuk started - will monitor and terminate Testcontainers containers on JVM exit
2021-05-19 09:06:23,608 [ INFO] [Time-limited test] [o.t.DockerClientFactory]: Checking the system...
2021-05-19 09:06:23,608 [ INFO] [Time-limited test] [o.t.DockerClientFactory]: ?? Docker server version should be at least 1.6.0
2021-05-19 09:06:23,730 [ INFO] [Time-limited test] [o.t.DockerClientFactory]: ?? Docker environment should have more than 2GB free disk space
2021-05-19 09:06:23,866 [ INFO] [Time-limited test] [d.1.0]]: Creating container for image: shopify/toxiproxy:2.1.0
2021-05-19 09:06:24,300 [ INFO] [Time-limited test] [d.1.0]]: Starting container with ID: f2ad078aef87c2746e563bfd0bfaa2f7fb3a9fc604185039970f85e73a7d8456
2021-05-19 09:06:25,249 [ INFO] [Time-limited test] [d.1.0]]: Container shopify/toxiproxy:2.1.0 is starting: f2ad078aef87c2746e563bfd0bfaa2f7fb3a9fc604185039970f85e73a7d8456
2021-05-19 09:06:25,262 [ INFO] [Time-limited test] [o.t.c.w.s.HttpWaitStrategy]: /nostalgic_euclid: Waiting for 60 seconds for URL: http://172.17.0.1:42287/version
2021-05-19 09:06:25,273 [ INFO] [Time-limited test] [d.1.0]]: Container shopify/toxiproxy:2.1.0 started in PT3.676S
```

**Comment by olukas** [comment]
Closing this issue because:
- it hasn't occurred since we configured `CPU shares = 8` for Docker container which runs the test.
- it seems to be related to big hiccups or timeout issue

We will reopen the issue if it fails again in the future.
