### ISSUE TITLE
com.hazelcast.jet.server.JetCommandLineTest

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#18725]
_master_ (commit f5b83a3b84271cab596824df534d82fb1847e69d)

Failed on Sonar run (Oracle JDK 11): http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/871/testReport/com.hazelcast.jet.server/JetCommandLineTest/

Following tests from `com.hazelcast.jet.server.JetCommandLineTest` failed:
- `test_submit_clientShutdownWhenDone`
- `test_submit_withWrongClassName`
- `test_submit_nameUsed`
- `testTargetsAfterCommandTakesPrecedence`
- `testTargetsMixin`
- `test_submit_argsPassing`
- `test_submit`
- `test_submit_withClassName`

Stacktrace (`test_submit_clientShutdownWhenDone`):
```
picocli.CommandLine$ExecutionException: Error while calling command (public void com.hazelcast.jet.server.JetCommandLine.submit(com.hazelcast.jet.server.JetCommandLine$Verbosity,com.hazelcast.jet.server.JetCommandLine$TargetsMixin,java.lang.String,java.lang.String,java.lang.String,java.io.File,java.util.List) throws java.lang.Exception): java.lang.IllegalStateException: Supplier of JetInstance was already set. This method should not be called outside the Jet command line.
	at picocli.CommandLine.execute(CommandLine.java:1207)
	at picocli.CommandLine.access$800(CommandLine.java:141)
	at picocli.CommandLine$RunAll.handle(CommandLine.java:1416)
	at picocli.CommandLine$RunAll.handle(CommandLine.java:1376)
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1243)
	at picocli.CommandLine.parseWithHandlers(CommandLine.java:1526)
	at com.hazelcast.jet.server.JetCommandLine.runCommandLine(JetCommandLine.java:782)
	at com.hazelcast.jet.server.JetCommandLineTest.run(JetCommandLineTest.java:668)
	at com.hazelcast.jet.server.JetCommandLineTest.test_submit_clientShutdownWhenDone(JetCommandLineTest.java:456)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalStateException: Supplier of JetInstance was already set. This method should not be called outside the Jet command line.
	at com.hazelcast.jet.impl.JetBootstrap.executeJar(JetBootstrap.java:104)
	at com.hazelcast.jet.server.JetCommandLine.submit(JetCommandLine.java:334)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at picocli.CommandLine.execute(CommandLine.java:1189)
	... 20 more
```

Stacktrace (`test_submit_withWrongClassName`):
```
java.lang.AssertionError: 

Expected: exception with message a string containing "ClassNotFoundException"
     but: message was "Error while calling command (public void com.hazelcast.jet.server.JetCommandLine.submit(com.hazelcast.jet.server.JetCommandLine$Verbosity,com.hazelcast.jet.server.JetCommandLine$TargetsMixin,java.lang.String,java.lang.String,java.lang.String,java.io.File,java.util.List) throws java.lang.Exception): java.lang.IllegalStateException: Supplier of JetInstance was already set. This method should not be called outside the Jet command line."
Stacktrace was: picocli.CommandLine$ExecutionException: Error while calling command (public void com.hazelcast.jet.server.JetCommandLine.submit(com.hazelcast.jet.server.JetCommandLine$Verbosity,com.hazelcast.jet.server.JetCommandLine$TargetsMixin,java.lang.String,java.lang.String,java.lang.String,java.io.File,java.util.List) throws java.lang.Exception): java.lang.IllegalStateException: Supplier of JetInstance was already set. This method should not be called outside the Jet command line.
	at picocli.CommandLine.execute(CommandLine.java:1207)
	at picocli.CommandLine.access$800(CommandLine.java:141)
	at picocli.CommandLine$RunAll.handle(CommandLine.java:1416)
	at picocli.CommandLine$RunAll.handle(CommandLine.java:1376)
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1243)
	at picocli.CommandLine.parseWithHandlers(CommandLine.java:1526)
	at com.hazelcast.jet.server.JetCommandLine.runCommandLine(JetCommandLine.java:782)
	at com.hazelcast.jet.server.JetCommandLineTest.run(JetCommandLineTest.java:668)
	at com.hazelcast.jet.server.JetCommandLineTest.test_submit_withWrongClassName(JetCommandLineTest.java:483)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalStateException: Supplier of JetInstance was already set. This method should not be called outside the Jet command line.
	at com.hazelcast.jet.impl.JetBootstrap.executeJar(JetBootstrap.java:104)
	at com.hazelcast.jet.server.JetCommandLine.submit(JetCommandLine.java:334)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at picocli.CommandLine.execute(CommandLine.java:1189)
	... 20 more

	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:964)
	at org.junit.Assert.assertThat(Assert.java:930)
	at org.junit.rules.ExpectedException.handleException(ExpectedException.java:271)
	at org.junit.rules.ExpectedException.access$000(ExpectedException.java:111)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:260)
	at com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37)
	at com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:104)
	at com.hazelcast.test.metrics.MetricsRule$1.evaluate(MetricsRule.java:62)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:50)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:29)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at com.hazelcast.test.AbstractHazelcastClassRunner$1.evaluate(AbstractHazelcastClassRunner.java:306)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Stacktrace (`test_submit_nameUsed`):
```
picocli.CommandLine$ExecutionException: Error while calling command (public void com.hazelcast.jet.server.JetCommandLine.submit(com.hazelcast.jet.server.JetCommandLine$Verbosity,com.hazelcast.jet.server.JetCommandLine$TargetsMixin,java.lang.String,java.lang.String,java.lang.String,java.io.File,java.util.List) throws java.lang.Exception): java.lang.IllegalStateException: Supplier of JetInstance was already set. This method should not be called outside the Jet command line.
	at picocli.CommandLine.execute(CommandLine.java:1207)
	at picocli.CommandLine.access$800(CommandLine.java:141)
	at picocli.CommandLine$RunAll.handle(CommandLine.java:1416)
	at picocli.CommandLine$RunAll.handle(CommandLine.java:1376)
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1243)
	at picocli.CommandLine.parseWithHandlers(CommandLine.java:1526)
	at com.hazelcast.jet.server.JetCommandLine.runCommandLine(JetCommandLine.java:782)
	at com.hazelcast.jet.server.JetCommandLineTest.run(JetCommandLineTest.java:668)
	at com.hazelcast.jet.server.JetCommandLineTest.test_submit_nameUsed(JetCommandLineTest.java:465)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalStateException: Supplier of JetInstance was already set. This method should not be called outside the Jet command line.
	at com.hazelcast.jet.impl.JetBootstrap.executeJar(JetBootstrap.java:104)
	at com.hazelcast.jet.server.JetCommandLine.submit(JetCommandLine.java:334)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at picocli.CommandLine.execute(CommandLine.java:1189)
	... 20 more
```

Stacktrace (`testTargetsAfterCommandTakesPrecedence`):
```
java.lang.NullPointerException
	at com.hazelcast.jet.server.JetCommandLineTest.testTargetsCommandCluster(JetCommandLineTest.java:566)
	at com.hazelcast.jet.server.JetCommandLineTest.testTargetsCommand(JetCommandLineTest.java:549)
	at com.hazelcast.jet.server.JetCommandLineTest.testTargetsAfterCommandTakesPrecedence(JetCommandLineTest.java:530)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Stacktrace (`testTargetsMixin`):
```
java.lang.NullPointerException
	at com.hazelcast.jet.server.JetCommandLineTest.testTargetsCommandCluster(JetCommandLineTest.java:566)
	at com.hazelcast.jet.server.JetCommandLineTest.testTargetsCommand(JetCommandLineTest.java:549)
	at com.hazelcast.jet.server.JetCommandLineTest.testTargetsMixin(JetCommandLineTest.java:520)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Stacktrace (`test_submit_argsPassing`):
```
picocli.CommandLine$ExecutionException: Error while calling command (public void com.hazelcast.jet.server.JetCommandLine.submit(com.hazelcast.jet.server.JetCommandLine$Verbosity,com.hazelcast.jet.server.JetCommandLine$TargetsMixin,java.lang.String,java.lang.String,java.lang.String,java.io.File,java.util.List) throws java.lang.Exception): java.lang.IllegalStateException: Supplier of JetInstance was already set. This method should not be called outside the Jet command line.
	at picocli.CommandLine.execute(CommandLine.java:1207)
	at picocli.CommandLine.access$800(CommandLine.java:141)
	at picocli.CommandLine$RunAll.handle(CommandLine.java:1416)
	at picocli.CommandLine$RunAll.handle(CommandLine.java:1376)
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1243)
	at picocli.CommandLine.parseWithHandlers(CommandLine.java:1526)
	at com.hazelcast.jet.server.JetCommandLine.runCommandLine(JetCommandLine.java:782)
	at com.hazelcast.jet.server.JetCommandLineTest.run(JetCommandLineTest.java:668)
	at com.hazelcast.jet.server.JetCommandLineTest.test_submit_argsPassing(JetCommandLineTest.java:488)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalStateException: Supplier of JetInstance was already set. This method should not be called outside the Jet command line.
	at com.hazelcast.jet.impl.JetBootstrap.executeJar(JetBootstrap.java:104)
	at com.hazelcast.jet.server.JetCommandLine.submit(JetCommandLine.java:334)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at picocli.CommandLine.execute(CommandLine.java:1189)
	... 20 more
```

Stacktrace (`test_submit`):
```
picocli.CommandLine$ExecutionException: Error while calling command (public void com.hazelcast.jet.server.JetCommandLine.submit(com.hazelcast.jet.server.JetCommandLine$Verbosity,com.hazelcast.jet.server.JetCommandLine$TargetsMixin,java.lang.String,java.lang.String,java.lang.String,java.io.File,java.util.List) throws java.lang.Exception): java.lang.IllegalStateException: Supplier of JetInstance was already set. This method should not be called outside the Jet command line.
	at picocli.CommandLine.execute(CommandLine.java:1207)
	at picocli.CommandLine.access$800(CommandLine.java:141)
	at picocli.CommandLine$RunAll.handle(CommandLine.java:1416)
	at picocli.CommandLine$RunAll.handle(CommandLine.java:1376)
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1243)
	at picocli.CommandLine.parseWithHandlers(CommandLine.java:1526)
	at com.hazelcast.jet.server.JetCommandLine.runCommandLine(JetCommandLine.java:782)
	at com.hazelcast.jet.server.JetCommandLineTest.run(JetCommandLineTest.java:668)
	at com.hazelcast.jet.server.JetCommandLineTest.test_submit(JetCommandLineTest.java:447)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalStateException: Supplier of JetInstance was already set. This method should not be called outside the Jet command line.
	at com.hazelcast.jet.impl.JetBootstrap.executeJar(JetBootstrap.java:104)
	at com.hazelcast.jet.server.JetCommandLine.submit(JetCommandLine.java:334)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at picocli.CommandLine.execute(CommandLine.java:1189)
	... 20 more
```

Stacktrace (`test_submit_withClassName`):
```
picocli.CommandLine$ExecutionException: Error while calling command (public void com.hazelcast.jet.server.JetCommandLine.submit(com.hazelcast.jet.server.JetCommandLine$Verbosity,com.hazelcast.jet.server.JetCommandLine$TargetsMixin,java.lang.String,java.lang.String,java.lang.String,java.io.File,java.util.List) throws java.lang.Exception): java.lang.IllegalStateException: Supplier of JetInstance was already set. This method should not be called outside the Jet command line.
	at picocli.CommandLine.execute(CommandLine.java:1207)
	at picocli.CommandLine.access$800(CommandLine.java:141)
	at picocli.CommandLine$RunAll.handle(CommandLine.java:1416)
	at picocli.CommandLine$RunAll.handle(CommandLine.java:1376)
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1243)
	at picocli.CommandLine.parseWithHandlers(CommandLine.java:1526)
	at com.hazelcast.jet.server.JetCommandLine.runCommandLine(JetCommandLine.java:782)
	at com.hazelcast.jet.server.JetCommandLineTest.run(JetCommandLineTest.java:668)
	at com.hazelcast.jet.server.JetCommandLineTest.test_submit_withClassName(JetCommandLineTest.java:473)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalStateException: Supplier of JetInstance was already set. This method should not be called outside the Jet command line.
	at com.hazelcast.jet.impl.JetBootstrap.executeJar(JetBootstrap.java:104)
	at com.hazelcast.jet.server.JetCommandLine.submit(JetCommandLine.java:334)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at picocli.CommandLine.execute(CommandLine.java:1189)
	... 20 more
```

Logs can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts?region=us-east-1&prefix=Hazelcast-master-sonar/871/&showversions=false

**Comment by olukas** [comment]
Closed since it has been already fixed.
