### ISSUE TITLE
ConcurentModificationException when Checking inactive sessions  [HZ-2947]

### ISSUE THREAD

**Issue by sancar** [hazelcast/hazelcast#18721]
**Describe the bug**

Periodic task `CheckInactiveSessions` throws `ConccurentModificationException`. stack trace is as follows:

```
ERROR hz.partition-operation.thread-12 com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl - [] [10.105.234.101]:41000 [rcs-arcs] [4.1.1] Failed to process: PartitionSpecificRunnableAdaptor{task=com.hazelcast.cp.internal.session.RaftSessionService$$Lambda$1701/0x0000000800b1b840@27c76bff, partitionId=204} on: hz.22346.partition-operation.thread-12
java.util.ConcurrentModificationException
at java.base/java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719)
at java.base/java.util.LinkedHashMap$LinkedValueIterator.next(LinkedHashMap.java:746)
at com.hazelcast.cp.internal.datastructures.spi.blocking.BlockingResource.collectAttachedSessions(BlockingResource.java:151)
at com.hazelcast.cp.internal.datastructures.spi.blocking.ResourceRegistry.getAttachedSessions(ResourceRegistry.java:203)
at com.hazelcast.cp.internal.datastructures.spi.blocking.AbstractBlockingService.getAttachedSessions(AbstractBlockingService.java:217)
at com.hazelcast.cp.internal.session.RaftSessionService.lambda$getInactiveSessions$2(RaftSessionService.java:380)
at com.hazelcast.cp.internal.util.PartitionSpecificRunnableAdaptor.run(PartitionSpecificRunnableAdaptor.java:41)
at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:192)
at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:172)
at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:140)
at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123)
at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
```

**Expected behavior**
We should not see the ConcurrentModificationException on this path.

**Comment by Holmistr** [comment]
Moving it to 5.2 as we'll have some time for CP subsystem improvements there.
