### ISSUE TITLE
com.hazelcast.jet.cdc.OperationTest.com.hazelcast.jet.cdc.OperationTest

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#18726]
_master_ (commit f5b83a3b84271cab596824df534d82fb1847e69d)

Failed on Sonar run (Oracle JDK 11): http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/871/testReport/com.hazelcast.jet.cdc/OperationTest/com_hazelcast_jet_cdc_OperationTest/

Stacktrace:
```
java.lang.IllegalStateException: Instances haven't been shut down: [HazelcastInstance{name='objective_liskov', node=[127.0.0.1]:5703}, HazelcastInstance{name='confident_liskov', node=[127.0.0.1]:5702}]
	at com.hazelcast.test.AbstractHazelcastClassRunner$1.evaluate(AbstractHazelcastClassRunner.java:313)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:107)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:83)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
```

Standard output:
```
23:22:35,712  INFO |deleteFromRemoteMap_ViaValueProjection[1: mode=client]| - [TcpServerConnector] hz.objective_liskov.cached.thread-1 - [127.0.0.1]:5703 [8580f454-d04a-4583-9223-9c3edd650422] [5.0-SNAPSHOT] Connecting to /127.0.0.1:5701, timeout: 10000, bind-any: true
23:22:35,713  INFO |deleteFromRemoteMap_ViaValueProjection[1: mode=client]| - [TcpServerConnector] hz.objective_liskov.cached.thread-1 - [127.0.0.1]:5703 [8580f454-d04a-4583-9223-9c3edd650422] [5.0-SNAPSHOT] Could not connect to: /127.0.0.1:5701. Reason: IOException[Connection refused to address /127.0.0.1:5701]
23:22:35,713  INFO || - [LifecycleService] main - [127.0.0.1]:5702 [6d3daf69-3dfa-4f10-9426-2c6889ae5fad] [5.0-SNAPSHOT] [127.0.0.1]:5702 is SHUTTING_DOWN
23:22:35,714  INFO |deleteFromRemoteMap_ViaValueProjection[0: mode=member]| - [MigrationManager] hz.confident_liskov.cached.thread-1 - [127.0.0.1]:5702 [6d3daf69-3dfa-4f10-9426-2c6889ae5fad] [5.0-SNAPSHOT] Shutdown request of Member [127.0.0.1]:5702 - 32df6b1e-2fae-48e7-b51e-761fc5ac973c this is handled
23:22:35,714  INFO |deleteFromRemoteMap_ViaValueProjection[1: mode=client]| - [TcpServerConnector] hz.objective_liskov.cached.thread-1 - [127.0.0.1]:5703 [8580f454-d04a-4583-9223-9c3edd650422] [5.0-SNAPSHOT] Connecting to /127.0.0.1:5701, timeout: 10000, bind-any: true
23:22:35,714  INFO |deleteFromRemoteMap_ViaValueProjection[1: mode=client]| - [TcpServerConnector] hz.objective_liskov.cached.thread-1 - [127.0.0.1]:5703 [8580f454-d04a-4583-9223-9c3edd650422] [5.0-SNAPSHOT] Could not connect to: /127.0.0.1:5701. Reason: IOException[Connection refused to address /127.0.0.1:5701]
23:22:35,715  INFO || - [Node] main - [127.0.0.1]:5702 [6d3daf69-3dfa-4f10-9426-2c6889ae5fad] [5.0-SNAPSHOT] Shutting down multicast service...
23:22:35,715  INFO || - [Node] main - [127.0.0.1]:5702 [6d3daf69-3dfa-4f10-9426-2c6889ae5fad] [5.0-SNAPSHOT] Shutting down connection manager...
23:22:35,716  INFO || - [Node] main - [127.0.0.1]:5702 [6d3daf69-3dfa-4f10-9426-2c6889ae5fad] [5.0-SNAPSHOT] Shutting down node engine...
23:22:35,721  INFO || - [NodeExtension] main - [127.0.0.1]:5702 [6d3daf69-3dfa-4f10-9426-2c6889ae5fad] [5.0-SNAPSHOT] Destroying node NodeExtension.
23:22:35,722  INFO || - [Node] main - [127.0.0.1]:5702 [6d3daf69-3dfa-4f10-9426-2c6889ae5fad] [5.0-SNAPSHOT] Hazelcast Shutdown is completed in 9 ms.
23:22:35,722  INFO || - [LifecycleService] main - [127.0.0.1]:5702 [6d3daf69-3dfa-4f10-9426-2c6889ae5fad] [5.0-SNAPSHOT] [127.0.0.1]:5702 is SHUTDOWN
23:22:35,722  INFO || - [LifecycleService] main - [127.0.0.1]:5703 [8580f454-d04a-4583-9223-9c3edd650422] [5.0-SNAPSHOT] [127.0.0.1]:5703 is SHUTTING_DOWN
23:22:35,723  INFO |deleteFromRemoteMap_ViaValueProjection[1: mode=client]| - [TcpServerConnector] hz.objective_liskov.cached.thread-1 - [127.0.0.1]:5703 [8580f454-d04a-4583-9223-9c3edd650422] [5.0-SNAPSHOT] Connecting to /127.0.0.1:5701, timeout: 10000, bind-any: true
23:22:35,723  INFO |deleteFromRemoteMap_ViaValueProjection[1: mode=client]| - [TcpServerConnector] hz.objective_liskov.cached.thread-1 - [127.0.0.1]:5703 [8580f454-d04a-4583-9223-9c3edd650422] [5.0-SNAPSHOT] Could not connect to: /127.0.0.1:5701. Reason: IOException[Connection refused to address /127.0.0.1:5701]
23:22:35,813  INFO |deleteFromRemoteMap_ViaValueProjection[1: mode=client]| - [TcpServerConnector] hz.objective_liskov.cached.thread-1 - [127.0.0.1]:5703 [8580f454-d04a-4583-9223-9c3edd650422] [5.0-SNAPSHOT] Connecting to /127.0.0.1:5701, timeout: 10000, bind-any: true
23:22:35,814  INFO |deleteFromRemoteMap_ViaValueProjection[1: mode=client]| - [TcpServerConnector] hz.objective_liskov.cached.thread-1 - [127.0.0.1]:5703 [8580f454-d04a-4583-9223-9c3edd650422] [5.0-SNAPSHOT] Could not connect to: /127.0.0.1:5701. Reason: IOException[Connection refused to address /127.0.0.1:5701]
23:22:35,815  INFO |deleteFromRemoteMap_ViaValueProjection[1: mode=client]| - [TcpServerConnector] hz.objective_liskov.cached.thread-3 - [127.0.0.1]:5703 [8580f454-d04a-4583-9223-9c3edd650422] [5.0-SNAPSHOT] Connecting to /127.0.0.1:5701, timeout: 10000, bind-any: true
23:22:35,815  INFO |deleteFromRemoteMap_ViaValueProjection[1: mode=client]| - [TcpServerConnector] hz.objective_liskov.cached.thread-3 - [127.0.0.1]:5703 [8580f454-d04a-4583-9223-9c3edd650422] [5.0-SNAPSHOT] Could not connect to: /127.0.0.1:5701. Reason: IOException[Connection refused to address /127.0.0.1:5701]
23:22:35,823  INFO |deleteFromRemoteMap_ViaValueProjection[1: mode=client]| - [TcpServerConnector] hz.objective_liskov.cached.thread-8 - [127.0.0.1]:5703 [8580f454-d04a-4583-9223-9c3edd650422] [5.0-SNAPSHOT] Connecting to /127.0.0.1:5701, timeout: 10000, bind-any: true
23:22:35,823  INFO |deleteFromRemoteMap_ViaValueProjection[1: mode=client]| - [TcpServerConnector] hz.objective_liskov.cached.thread-8 - [127.0.0.1]:5703 [8580f454-d04a-4583-9223-9c3edd650422] [5.0-SNAPSHOT] Could not connect to: /127.0.0.1:5701. Reason: IOException[Connection refused to address /127.0.0.1:5701]
23:22:35,914  INFO |deleteFromRemoteMap_ViaValueProjection[1: mode=client]| - [TcpServerConnector] hz.objective_liskov.cached.thread-8 - [127.0.0.1]:5703 [8580f454-d04a-4583-9223-9c3edd650422] [5.0-SNAPSHOT] Connecting to /127.0.0.1:5701, timeout: 10000, bind-any: true
23:22:35,914  INFO |deleteFromRemoteMap_ViaValueProjection[1: mode=client]| - [TcpServerConnector] hz.objective_liskov.cached.thread-8 - [127.0.0.1]:5703 [8580f454-d04a-4583-9223-9c3edd650422] [5.0-SNAPSHOT] Could not connect to: /127.0.0.1:5701. Reason: IOException[Connection refused to address /127.0.0.1:5701]
23:22:35,915  WARN |deleteFromRemoteMap_ViaValueProjection[1: mode=client]| - [TcpServerConnectionErrorHandler] hz.objective_liskov.cached.thread-8 - [127.0.0.1]:5703 [8580f454-d04a-4583-9223-9c3edd650422] [5.0-SNAPSHOT] Removing connection to endpoint [127.0.0.1]:5701 Cause => java.io.IOException {Connection refused to address /127.0.0.1:5701}, Error-Count: 5
23:22:35,915  INFO |deleteFromRemoteMap_ViaValueProjection[1: mode=client]| - [TcpServerConnector] hz.objective_liskov.cached.thread-8 - [127.0.0.1]:5703 [8580f454-d04a-4583-9223-9c3edd650422] [5.0-SNAPSHOT] Connecting to /127.0.0.1:5701, timeout: 10000, bind-any: true
23:22:35,915  WARN |deleteFromRemoteMap_ViaValueProjection[1: mode=client]| - [MembershipManager] hz.objective_liskov.cached.thread-3 - [127.0.0.1]:5703 [8580f454-d04a-4583-9223-9c3edd650422] [5.0-SNAPSHOT] Member [127.0.0.1]:5701 - feb8b1f3-aee0-48d1-8d45-6aa372634b25 is suspected to be dead for reason: No connection
23:22:35,915  INFO |deleteFromRemoteMap_ViaValueProjection[1: mode=client]| - [MembershipManager] hz.objective_liskov.cached.thread-3 - [127.0.0.1]:5703 [8580f454-d04a-4583-9223-9c3edd650422] [5.0-SNAPSHOT] Starting mastership claim process...
23:22:35,915  INFO |deleteFromRemoteMap_ViaValueProjection[1: mode=client]| - [MembershipManager] hz.objective_liskov.cached.thread-3 - [127.0.0.1]:5703 [8580f454-d04a-4583-9223-9c3edd650422] [5.0-SNAPSHOT] Local MembersView{version=2, members=[MemberInfo{address=[127.0.0.1]:5701, uuid=feb8b1f3-aee0-48d1-8d45-6aa372634b25, liteMember=false, memberListJoinVersion=1}, MemberInfo{address=[127.0.0.1]:5703, uuid=fe262bc0-e2c4-4f7e-a4b5-271006ea302d, liteMember=false, memberListJoinVersion=2}]} with suspected members: [Member [127.0.0.1]:5701 - feb8b1f3-aee0-48d1-8d45-6aa372634b25] and initial addresses to ask: []
23:22:35,915  INFO |deleteFromRemoteMap_ViaValueProjection[1: mode=client]| - [TcpServerConnector] hz.objective_liskov.cached.thread-8 - [127.0.0.1]:5703 [8580f454-d04a-4583-9223-9c3edd650422] [5.0-SNAPSHOT] Could not connect to: /127.0.0.1:5701. Reason: IOException[Connection refused to address /127.0.0.1:5701]
23:22:35,916  INFO |deleteFromRemoteMap_ViaValueProjection[1: mode=client]| - [ClusterService] hz.objective_liskov.cached.thread-6 - [127.0.0.1]:5703 [8580f454-d04a-4583-9223-9c3edd650422] [5.0-SNAPSHOT] 

Members {size:1, ver:3} [
	Member [127.0.0.1]:5703 - fe262bc0-e2c4-4f7e-a4b5-271006ea302d this
]

23:22:35,916  INFO |deleteFromRemoteMap_ViaValueProjection[1: mode=client]| - [MembershipManager] hz.objective_liskov.cached.thread-6 - [127.0.0.1]:5703 [8580f454-d04a-4583-9223-9c3edd650422] [5.0-SNAPSHOT] Mastership is claimed with: MembersView{version=3, members=[MemberInfo{address=[127.0.0.1]:5703, uuid=fe262bc0-e2c4-4f7e-a4b5-271006ea302d, liteMember=false, memberListJoinVersion=2}]}
23:22:35,916  WARN |deleteFromRemoteMap_ViaValueProjection[1: mode=client]| - [JetService] ForkJoinPool.commonPool-worker-5 - [127.0.0.1]:5703 [8580f454-d04a-4583-9223-9c3edd650422] [5.0-SNAPSHOT] Failed to notify master member that this member is shutting down, will retry in 5 seconds
com.hazelcast.core.MemberLeftException: Member [127.0.0.1]:5701 - feb8b1f3-aee0-48d1-8d45-6aa372634b25 has left cluster!
	at com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor$OnMemberLeftTask.onTargetLoss(InvocationMonitor.java:429) ~[hazelcast-5.0-SNAPSHOT.jar:5.0-SNAPSHOT]
	at com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor$OnMemberLeftTask.run0(InvocationMonitor.java:396) ~[hazelcast-5.0-SNAPSHOT.jar:5.0-SNAPSHOT]
	at com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor$MonitorTask.run(InvocationMonitor.java:255) ~[hazelcast-5.0-SNAPSHOT.jar:5.0-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) ~[?:?]
23:22:36,166  INFO |deleteFromRemoteMap_ViaValueProjection[1: mode=client]| - [InternalPartitionService] hz.objective_liskov.migration - [127.0.0.1]:5703 [8580f454-d04a-4583-9223-9c3edd650422] [5.0-SNAPSHOT] Fetching partition tables from cluster to determine the most recent one... Local stamp: -565914400620444322
23:22:36,166  INFO |deleteFromRemoteMap_ViaValueProjection[1: mode=client]| - [InternalPartitionService] hz.objective_liskov.migration - [127.0.0.1]:5703 [8580f454-d04a-4583-9223-9c3edd650422] [5.0-SNAPSHOT] Most recent partition table is determined.
23:22:36,166  INFO |deleteFromRemoteMap_ViaValueProjection[1: mode=client]| - [InternalPartitionService] hz.objective_liskov.migration - [127.0.0.1]:5703 [8580f454-d04a-4583-9223-9c3edd650422] [5.0-SNAPSHOT] Applying the most recent of partition state...
23:22:36,167  INFO |deleteFromRemoteMap_ViaValueProjection[1: mode=client]| - [MigrationManager] hz.objective_liskov.migration - [127.0.0.1]:5703 [8580f454-d04a-4583-9223-9c3edd650422] [5.0-SNAPSHOT] Partition balance is ok, no need to repartition.
23:22:40,919  INFO |deleteFromRemoteMap_ViaValueProjection[1: mode=client]| - [MigrationManager] hz.objective_liskov.cached.thread-6 - [127.0.0.1]:5703 [8580f454-d04a-4583-9223-9c3edd650422] [5.0-SNAPSHOT] Shutdown request of Member [127.0.0.1]:5703 - fe262bc0-e2c4-4f7e-a4b5-271006ea302d this is handled
23:22:40,919  INFO || - [Node] main - [127.0.0.1]:5703 [8580f454-d04a-4583-9223-9c3edd650422] [5.0-SNAPSHOT] Shutting down multicast service...
23:22:40,920  INFO || - [Node] main - [127.0.0.1]:5703 [8580f454-d04a-4583-9223-9c3edd650422] [5.0-SNAPSHOT] Shutting down connection manager...
23:22:40,922  INFO || - [Node] main - [127.0.0.1]:5703 [8580f454-d04a-4583-9223-9c3edd650422] [5.0-SNAPSHOT] Shutting down node engine...
23:22:40,926  INFO || - [NodeExtension] main - [127.0.0.1]:5703 [8580f454-d04a-4583-9223-9c3edd650422] [5.0-SNAPSHOT] Destroying node NodeExtension.
23:22:40,926  INFO || - [Node] main - [127.0.0.1]:5703 [8580f454-d04a-4583-9223-9c3edd650422] [5.0-SNAPSHOT] Hazelcast Shutdown is completed in 5204 ms.
23:22:40,927  INFO || - [LifecycleService] main - [127.0.0.1]:5703 [8580f454-d04a-4583-9223-9c3edd650422] [5.0-SNAPSHOT] [127.0.0.1]:5703 is SHUTDOWN
```

**Comment by olukas** [comment]
Failed even after setting `CPU shares = 8` for docker container. Failed with Sonar nightly build (Oracle JDK 11): http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/877/testReport/com.hazelcast.jet.cdc/OperationTest/com_hazelcast_jet_cdc_OperationTest/

**Comment by olukas** [comment]
Failed even after setting `CPU shares = 8` for docker container. 

It failed for example with following JDKs:
- IBM JDK 8: http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-IbmJDK8/132/testReport/com.hazelcast.jet.cdc/OperationTest/com_hazelcast_jet_cdc_OperationTest/
- Zulu JDK 8: http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZuluJDK8/136/testReport/com.hazelcast.jet.cdc/OperationTest/com_hazelcast_jet_cdc_OperationTest/
- Oracle JDK 11: http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-OracleJDK11/270/testReport/com.hazelcast.jet.cdc/OperationTest/com_hazelcast_jet_cdc_OperationTest/
