### ISSUE TITLE
com.hazelcast.internal.partition.impl.InternalPartitionServiceLiteMemberTest

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#18739]
_master_ (commit c3c641fc6af0924ccc140f24d98e37f7f8dd66b1)

Failed on IBM JDK 8: http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-IbmJDK8/131/testReport/com.hazelcast.internal.partition.impl/InternalPartitionServiceLiteMemberTest/

Following tests from `com.hazelcast.internal.partition.impl.InternalPartitionServiceLiteMemberTest` failed with the same exception:
- `test_liteMemberCanTerminate_whenDataMemberExistsInCluster`
- `test_dataMemberCanShutdownSafely_whenOnlyLiteMemberExistsInCluster`
- `test_liteMemberCanShutdownSafely_whenDataMemberExistsInCluster`
- `test_liteMemberCanTerminate_withClusterSize2`
- `test_dataMemberCanTerminate_whenOnlyLiteMemberExistsInCluster` 

Stacktrace (for `test_liteMemberCanTerminate_whenDataMemberExistsInCluster`):
```
org.junit.runners.model.TestTimedOutException: test timed out after 120000 milliseconds
	at java.lang.Thread.startImpl(Native Method)
	at java.lang.Thread.start(Thread.java:992)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.startAll(OperationExecutorImpl.java:527)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.start(OperationExecutorImpl.java:521)
	at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.start(OperationServiceImpl.java:488)
	at com.hazelcast.spi.impl.NodeEngineImpl.start(NodeEngineImpl.java:227)
	at com.hazelcast.instance.impl.Node.start(Node.java:447)
	at com.hazelcast.instance.impl.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:124)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:211)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:190)
	at com.hazelcast.test.TestHazelcastInstanceFactory.newHazelcastInstance(TestHazelcastInstanceFactory.java:224)
	at com.hazelcast.test.TestHazelcastInstanceFactory.newHazelcastInstance(TestHazelcastInstanceFactory.java:106)
	at com.hazelcast.internal.partition.impl.InternalPartitionServiceLiteMemberTest.test_liteMemberCanTerminate_whenDataMemberExistsInCluster(InternalPartitionServiceLiteMemberTest.java:330)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.lang.Thread.run(Thread.java:822)
```

Standard output can be downloaded here - https://s3.console.aws.amazon.com/s3/object/j-artifacts?region=us-east-1&prefix=Hazelcast-master-IbmJDK8/131/Hazelcast-master-IbmJDK8-131.tar

**Comment by olukas** [comment]
Closing this issue because:
- it hasn't occurred since we configured `CPU shares = 8` for Docker container which runs the test.
- it seems to be related to big hiccups or timeout issue

We will reopen the issue if it fails again in the future.
