### ISSUE TITLE
com.hazelcast.client.map.impl.mapstore.EntryLoaderClientSimpleTest.testGetAllLoadsEntriesWithExpiration[inMemoryFormat: BINARY]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#18746]
_4.2.z_ (commit e22aab3cffbb36863a91276dd2506b4fcf4a7f6c)

Failed on Zulu JDK 8: http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-4.maintenance-ZuluJDK8/145/testReport/com.hazelcast.client.map.impl.mapstore/EntryLoaderClientSimpleTest/testGetAllLoadsEntriesWithExpiration_inMemoryFormat__BINARY_/

Stacktrace:
```
java.lang.AssertionError: expected:<val0> but was:<null>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:120)
	at org.junit.Assert.assertEquals(Assert.java:146)
	at com.hazelcast.map.impl.mapstore.EntryLoaderSimpleTest.testGetAllLoadsEntriesWithExpiration(EntryLoaderSimpleTest.java:184)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

Standard output:
```
07:26:48,188  INFO |testGetAllLoadsEntriesWithExpiration[inMemoryFormat: BINARY]| - [ClientConnectionManager] Thread-2094 - hz.client_372 [dev] [4.2.1-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5701:2558c151-5ecf-4cc8-96b1-d1ab93bf6c1d, connection: MockedClientConnection{localAddress=[127.0.0.1]:40001, super=ClientConnection{alive=false, connectionId=1, channel=null, remoteAddress=[127.0.0.1]:5701, lastReadTime=2021-05-23 07:26:45.126, lastWriteTime=2021-05-23 07:26:44.479, closedTime=2021-05-23 07:26:48.178, connected server version=4.2.1-SNAPSHOT}}
07:26:48,188  INFO |testGetAllLoadsEntriesWithExpiration[inMemoryFormat: BINARY]| - [LifecycleService] Thread-2094 - hz.client_372 [dev] [4.2.1-SNAPSHOT] HazelcastClient 4.2.1-SNAPSHOT (20210523 - e22aab3) is CLIENT_DISCONNECTED
07:26:48,189  WARN |testGetAllLoadsEntriesWithExpiration[inMemoryFormat: BINARY]| - [TestClientRegistry$MockedServerConnection] pool-933-thread-1 - Server connection closed: null
07:26:48,195  INFO |testGetAllLoadsEntriesWithExpiration[inMemoryFormat: BINARY]| - [MockServer] pool-933-thread-1 - [127.0.0.1]:5701 [dev] [4.2.1-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:40001, connection: MockedNodeConnection{ remoteAddress = [127.0.0.1]:40001, localAddress = [127.0.0.1]:5701, connectionId = 1}
07:26:48,197  WARN |testGetAllLoadsEntriesWithExpiration[inMemoryFormat: BINARY]| - [TwoWayBlockableExecutor] pool-933-thread-1 - Dropping incoming runnable since other end closed. Server Closed EOF. MockedClientConnection{localAddress=[127.0.0.1]:40001, super=ClientConnection{alive=false, connectionId=1, channel=null, remoteAddress=[127.0.0.1]:5701, lastReadTime=2021-05-23 07:26:45.126, lastWriteTime=2021-05-23 07:26:44.479, closedTime=2021-05-23 07:26:48.178, connected server version=4.2.1-SNAPSHOT}}
07:26:48,208  INFO |testGetAllLoadsEntriesWithExpiration[inMemoryFormat: BINARY]| - [LifecycleService] Thread-2094 - hz.client_372 [dev] [4.2.1-SNAPSHOT] HazelcastClient 4.2.1-SNAPSHOT (20210523 - e22aab3) is SHUTDOWN
07:26:48,209  INFO |testGetAllLoadsEntriesWithExpiration[inMemoryFormat: BINARY]| - [LifecycleService] Thread-2094 - [127.0.0.1]:5701 [dev] [4.2.1-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
07:26:48,209  WARN |testGetAllLoadsEntriesWithExpiration[inMemoryFormat: BINARY]| - [Node] Thread-2094 - [127.0.0.1]:5701 [dev] [4.2.1-SNAPSHOT] Terminating forcefully...
07:26:48,209  INFO |testGetAllLoadsEntriesWithExpiration[inMemoryFormat: BINARY]| - [Node] Thread-2094 - [127.0.0.1]:5701 [dev] [4.2.1-SNAPSHOT] Shutting down connection manager...
07:26:48,209  INFO |testGetAllLoadsEntriesWithExpiration[inMemoryFormat: BINARY]| - [Node] Thread-2094 - [127.0.0.1]:5701 [dev] [4.2.1-SNAPSHOT] Shutting down node engine...
07:26:48,198  INFO |testGetAllLoadsEntriesWithExpiration[inMemoryFormat: BINARY]| - [ClientEndpointManager] hz.gifted_taussig.event-2252 - [127.0.0.1]:5701 [dev] [4.2.1-SNAPSHOT] Destroying ClientEndpoint{connection=MockedNodeConnection{ remoteAddress = [127.0.0.1]:40001, localAddress = [127.0.0.1]:5701, connectionId = 1}, clientUuid='771fbae2-270a-420a-a1dd-960e60f4f2f7, authenticated=true, clientVersion=4.2.1-SNAPSHOT, creationTime=1621754780474, latest clientAttributes=lastStatisticsCollectionTime=1621754804451,enterprise=false,clientType=JVM,clientVersion=4.2.1-SNAPSHOT,clusterConnectionTimestamp=1621754780474,clientAddress=127.0.0.1,clientName=hz.client_372,credentials.principal=null,os.committedVirtualMemorySize=47669227520,os.freePhysicalMemorySize=151504879616,os.freeSwapSpaceSize=2326573056,os.maxFileDescriptorCount=120000,os.openFileDescriptorCount=121,os.processCpuTime=918310000000,os.systemLoadAverage=6486.18,os.totalPhysicalMemorySize=405449981952,os.totalSwapSpaceSize=4294963200,runtime.availableProcessors=72,runtime.freeMemory=3443812704,runtime.maxMemory=3941597184,runtime.totalMemory=3941597184,runtime.uptime=1087942,runtime.usedMemory=497784480, labels=[]}
07:26:48,362  INFO |testGetAllLoadsEntriesWithExpiration[inMemoryFormat: BINARY]| - [NodeExtension] Thread-2094 - [127.0.0.1]:5701 [dev] [4.2.1-SNAPSHOT] Destroying node NodeExtension.
07:26:48,363  INFO |testGetAllLoadsEntriesWithExpiration[inMemoryFormat: BINARY]| - [Node] Thread-2094 - [127.0.0.1]:5701 [dev] [4.2.1-SNAPSHOT] Hazelcast Shutdown is completed in 154 ms.
07:26:48,363  INFO |testGetAllLoadsEntriesWithExpiration[inMemoryFormat: BINARY]| - [LifecycleService] Thread-2094 - [127.0.0.1]:5701 [dev] [4.2.1-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
BuildInfo right after testGetAllLoadsEntriesWithExpiration[inMemoryFormat: BINARY](com.hazelcast.client.map.impl.mapstore.EntryLoaderClientSimpleTest): BuildInfo{version='4.2.1-SNAPSHOT', build='20210523', buildNumber=20210523, revision=e22aab3, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'testGetAllLoadsEntriesWithExpiration[inMemoryFormat: BINARY](com.hazelcast.client.map.impl.mapstore.EntryLoaderClientSimpleTest):'
07:26:10, accumulated pauses: 660 ms, max pause: 437 ms, pauses over 1000 ms: 0
07:26:15, accumulated pauses: 684 ms, max pause: 33 ms, pauses over 1000 ms: 0
07:26:20, accumulated pauses: 722 ms, max pause: 31 ms, pauses over 1000 ms: 0
07:26:25, accumulated pauses: 1708 ms, max pause: 1077 ms, pauses over 1000 ms: 1
07:26:30, accumulated pauses: 3211 ms, max pause: 1734 ms, pauses over 1000 ms: 1
07:26:35, accumulated pauses: 1706 ms, max pause: 620 ms, pauses over 1000 ms: 0
07:26:40, accumulated pauses: 1804 ms, max pause: 675 ms, pauses over 1000 ms: 0
07:26:45, accumulated pauses: 555 ms, max pause: 132 ms, pauses over 1000 ms: 0
```

**Comment by olukas** [comment]
Closing this issue because:
- it hasn't occurred since we configured `CPU shares = 8` for Docker container which runs the test.
- it seems to be related to big hiccups or timeout issue

We will reopen the issue if it fails again in the future.
