### ISSUE TITLE
com.hazelcast.client.map.MapPreconditionsTest

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#18745]
_4.2.z_ (commit e22aab3cffbb36863a91276dd2506b4fcf4a7f6c)

Failed on Zulu JDK 8: http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-4.maintenance-ZuluJDK8/145/testReport/com.hazelcast.client.map/MapPreconditionsTest/

Following tests from `com.hazelcast.client.map.MapPreconditionsTest` failed with the same exception (timed out):
- `testLocalKeySet`
- `testValuesWitPredicate`
- `testLocalKeySetWithNullPredicate`
- `testKeySet`

Stacktrace (for `testLocalKeySet`):
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:304)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.manageParking(AbstractInvocationFuture.java:693)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:615)
	at com.hazelcast.client.impl.spi.ClientProxy.invokeOnPartition(ClientProxy.java:188)
	at com.hazelcast.client.impl.spi.ClientProxy.invoke(ClientProxy.java:182)
	at com.hazelcast.client.impl.proxy.ClientMapProxy.putInternal(ClientMapProxy.java:534)
	at com.hazelcast.client.impl.proxy.ClientMapProxy.put(ClientMapProxy.java:266)
	at com.hazelcast.client.map.MapPreconditionsTest.testLocalKeySet(MapPreconditionsTest.java:573)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

Standard output (for `testLocalKeySet`):
```
07:39:06,567  INFO |testLocalKeySet| - [NodeExtension] Thread-2479 - [127.0.0.1]:5701 [dev] [4.2.1-SNAPSHOT] Destroying node NodeExtension.
07:39:06,574  INFO |testLocalKeySet| - [Node] Thread-2479 - [127.0.0.1]:5701 [dev] [4.2.1-SNAPSHOT] Hazelcast Shutdown is completed in 2942 ms.
07:39:06,574  INFO |testLocalKeySet| - [LifecycleService] Thread-2479 - [127.0.0.1]:5701 [dev] [4.2.1-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
BuildInfo right after testLocalKeySet(com.hazelcast.client.map.MapPreconditionsTest): BuildInfo{version='4.2.1-SNAPSHOT', build='20210523', buildNumber=20210523, revision=e22aab3, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'testLocalKeySet(com.hazelcast.client.map.MapPreconditionsTest):'
07:32:05, accumulated pauses: 9954 ms, max pause: 9819 ms, pauses over 1000 ms: 1
07:32:15, accumulated pauses: 10198 ms, max pause: 9824 ms, pauses over 1000 ms: 1
07:32:25, accumulated pauses: 13394 ms, max pause: 13289 ms, pauses over 1000 ms: 1
07:32:40, accumulated pauses: 353 ms, max pause: 16 ms, pauses over 1000 ms: 0
07:32:45, accumulated pauses: 8364 ms, max pause: 8032 ms, pauses over 1000 ms: 1
07:32:55, accumulated pauses: 859 ms, max pause: 35 ms, pauses over 1000 ms: 0
07:33:00, accumulated pauses: 1096 ms, max pause: 20 ms, pauses over 1000 ms: 0
07:33:05, accumulated pauses: 8299 ms, max pause: 8032 ms, pauses over 1000 ms: 1
07:33:15, accumulated pauses: 3887 ms, max pause: 3648 ms, pauses over 1000 ms: 1
07:33:20, accumulated pauses: 776 ms, max pause: 82 ms, pauses over 1000 ms: 0
07:33:25, accumulated pauses: 824 ms, max pause: 56 ms, pauses over 1000 ms: 0
07:33:30, accumulated pauses: 7993 ms, max pause: 7956 ms, pauses over 1000 ms: 1
07:33:35, accumulated pauses: 147 ms, max pause: 13 ms, pauses over 1000 ms: 0
07:33:40, accumulated pauses: 12489 ms, max pause: 12114 ms, pauses over 1000 ms: 1
07:33:55, accumulated pauses: 914 ms, max pause: 20 ms, pauses over 1000 ms: 0
07:34:00, accumulated pauses: 3263 ms, max pause: 2279 ms, pauses over 1000 ms: 1
07:34:05, accumulated pauses: 1966 ms, max pause: 1050 ms, pauses over 1000 ms: 1
07:34:10, accumulated pauses: 1740 ms, max pause: 1021 ms, pauses over 1000 ms: 1
07:34:15, accumulated pauses: 504 ms, max pause: 18 ms, pauses over 1000 ms: 0
07:34:20, accumulated pauses: 4601 ms, max pause: 4534 ms, pauses over 1000 ms: 1
07:34:25, accumulated pauses: 1197 ms, max pause: 747 ms, pauses over 1000 ms: 0
07:34:30, accumulated pauses: 313 ms, max pause: 17 ms, pauses over 1000 ms: 0
07:34:35, accumulated pauses: 574 ms, max pause: 26 ms, pauses over 1000 ms: 0
07:34:40, accumulated pauses: 452 ms, max pause: 24 ms, pauses over 1000 ms: 0
07:34:45, accumulated pauses: 696 ms, max pause: 322 ms, pauses over 1000 ms: 0
07:34:50, accumulated pauses: 208 ms, max pause: 23 ms, pauses over 1000 ms: 0
07:34:55, accumulated pauses: 14464 ms, max pause: 14463 ms, pauses over 1000 ms: 1
07:35:05, accumulated pauses: 70 ms, max pause: 10 ms, pauses over 1000 ms: 0
07:35:10, accumulated pauses: 2706 ms, max pause: 2311 ms, pauses over 1000 ms: 1
07:35:15, accumulated pauses: 801 ms, max pause: 12 ms, pauses over 1000 ms: 0
07:35:20, accumulated pauses: 1714 ms, max pause: 1068 ms, pauses over 1000 ms: 1
07:35:25, accumulated pauses: 4604 ms, max pause: 3294 ms, pauses over 1000 ms: 1
07:35:30, accumulated pauses: 383 ms, max pause: 14 ms, pauses over 1000 ms: 0
07:35:35, accumulated pauses: 1154 ms, max pause: 27 ms, pauses over 1000 ms: 0
07:35:40, accumulated pauses: 2901 ms, max pause: 1985 ms, pauses over 1000 ms: 1
07:35:45, accumulated pauses: 11302 ms, max pause: 10462 ms, pauses over 1000 ms: 1
07:35:55, accumulated pauses: 335 ms, max pause: 16 ms, pauses over 1000 ms: 0
07:36:00, accumulated pauses: 7255 ms, max pause: 6914 ms, pauses over 1000 ms: 1
07:36:10, accumulated pauses: 691 ms, max pause: 395 ms, pauses over 1000 ms: 0
07:36:15, accumulated pauses: 647 ms, max pause: 6 ms, pauses over 1000 ms: 0
07:36:20, accumulated pauses: 2003 ms, max pause: 826 ms, pauses over 1000 ms: 0
07:36:25, accumulated pauses: 3817 ms, max pause: 1196 ms, pauses over 1000 ms: 2
07:36:30, accumulated pauses: 516 ms, max pause: 15 ms, pauses over 1000 ms: 0
07:36:35, accumulated pauses: 2047 ms, max pause: 1567 ms, pauses over 1000 ms: 1
07:36:40, accumulated pauses: 537 ms, max pause: 13 ms, pauses over 1000 ms: 0
07:36:45, accumulated pauses: 611 ms, max pause: 14 ms, pauses over 1000 ms: 0
07:36:50, accumulated pauses: 1024 ms, max pause: 48 ms, pauses over 1000 ms: 0
07:36:55, accumulated pauses: 361 ms, max pause: 53 ms, pauses over 1000 ms: 0
07:37:00, accumulated pauses: 1308 ms, max pause: 688 ms, pauses over 1000 ms: 0
07:37:05, accumulated pauses: 878 ms, max pause: 25 ms, pauses over 1000 ms: 0
07:37:10, accumulated pauses: 687 ms, max pause: 25 ms, pauses over 1000 ms: 0
07:37:15, accumulated pauses: 504 ms, max pause: 10 ms, pauses over 1000 ms: 0
07:37:20, accumulated pauses: 765 ms, max pause: 16 ms, pauses over 1000 ms: 0
07:37:25, accumulated pauses: 1382 ms, max pause: 755 ms, pauses over 1000 ms: 0
07:37:30, accumulated pauses: 694 ms, max pause: 25 ms, pauses over 1000 ms: 0
07:37:35, accumulated pauses: 872 ms, max pause: 11 ms, pauses over 1000 ms: 0
07:37:40, accumulated pauses: 690 ms, max pause: 11 ms, pauses over 1000 ms: 0
07:37:45, accumulated pauses: 920 ms, max pause: 59 ms, pauses over 1000 ms: 0
07:37:50, accumulated pauses: 773 ms, max pause: 16 ms, pauses over 1000 ms: 0
07:37:55, accumulated pauses: 1082 ms, max pause: 515 ms, pauses over 1000 ms: 0
07:38:00, accumulated pauses: 879 ms, max pause: 44 ms, pauses over 1000 ms: 0
07:38:05, accumulated pauses: 367 ms, max pause: 9 ms, pauses over 1000 ms: 0
07:38:10, accumulated pauses: 459 ms, max pause: 7 ms, pauses over 1000 ms: 0
07:38:15, accumulated pauses: 415 ms, max pause: 12 ms, pauses over 1000 ms: 0
07:38:20, accumulated pauses: 416 ms, max pause: 25 ms, pauses over 1000 ms: 0
07:38:25, accumulated pauses: 821 ms, max pause: 567 ms, pauses over 1000 ms: 0
07:38:30, accumulated pauses: 532 ms, max pause: 28 ms, pauses over 1000 ms: 0
07:38:35, accumulated pauses: 614 ms, max pause: 40 ms, pauses over 1000 ms: 0
07:38:40, accumulated pauses: 460 ms, max pause: 12 ms, pauses over 1000 ms: 0
07:38:45, accumulated pauses: 634 ms, max pause: 60 ms, pauses over 1000 ms: 0
07:38:50, accumulated pauses: 1419 ms, max pause: 43 ms, pauses over 1000 ms: 0
07:38:55, accumulated pauses: 927 ms, max pause: 30 ms, pauses over 1000 ms: 0
07:39:00, accumulated pauses: 1742 ms, max pause: 553 ms, pauses over 1000 ms: 0
07:39:05, accumulated pauses: 279 ms, max pause: 16 ms, pauses over 1000 ms: 0
```

**Comment by olukas** [comment]
Failed also with Openj9-16: http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-4.maintenance-Openj9-16/lastCompletedBuild/testReport/com.hazelcast.client.map/MapPreconditionsTest/

**Comment by olukas** [comment]
Closing this issue because:
- it hasn't occurred since we configured `CPU shares = 8` for Docker container which runs the test.
- it seems to be related to big hiccups or timeout issue

We will reopen the issue if it fails again in the future.
