### ISSUE TITLE
com.hazelcast.internal.cluster.impl.MembershipUpdateTest.shouldNotProcessStaleJoinRequest and shouldNotProcessStaleJoinRequest_whenMasterChanges

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#18749]
_4.2.z_ (commit e22aab3cffbb36863a91276dd2506b4fcf4a7f6c)

Failed on Zulu JDK 8:
- http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-4.maintenance-ZuluJDK8/145/testReport/com.hazelcast.internal.cluster.impl/MembershipUpdateTest/shouldNotProcessStaleJoinRequest/
- http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-4.maintenance-ZuluJDK8/145/testReport/com.hazelcast.internal.cluster.impl/MembershipUpdateTest/shouldNotProcessStaleJoinRequest_whenMasterChanges/

Stacktrace for `shouldNotProcessStaleJoinRequest`:
```
java.lang.AssertionError: Cluster size is not correct. Expected: 1, actual: 2, instance index: 0
	at org.junit.Assert.fail(Assert.java:89)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSize(HazelcastTestSupport.java:1034)
	at com.hazelcast.internal.cluster.impl.MembershipUpdateTest.lambda$shouldNotProcessStaleJoinRequest$12(MembershipUpdateTest.java:639)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueAllTheTime(HazelcastTestSupport.java:1205)
	at com.hazelcast.internal.cluster.impl.MembershipUpdateTest.shouldNotProcessStaleJoinRequest(MembershipUpdateTest.java:635)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

Stacktrace for `shouldNotProcessStaleJoinRequest_whenMasterChanges`:
```
java.lang.AssertionError: Cluster size is not correct. Expected: 1, actual: 2, instance index: 0
	at org.junit.Assert.fail(Assert.java:89)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSize(HazelcastTestSupport.java:1034)
	at com.hazelcast.internal.cluster.impl.MembershipUpdateTest.lambda$shouldNotProcessStaleJoinRequest_whenMasterChanges$13(MembershipUpdateTest.java:659)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueAllTheTime(HazelcastTestSupport.java:1205)
	at com.hazelcast.internal.cluster.impl.MembershipUpdateTest.shouldNotProcessStaleJoinRequest_whenMasterChanges(MembershipUpdateTest.java:655)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

Standard output for `shouldNotProcessStaleJoinRequest`:
```
11:08:46,629  INFO |shouldNotProcessStaleJoinRequest| - [LifecycleService] Thread-37717 - [127.0.0.1]:5702 [dev] [4.2.1-SNAPSHOT] [127.0.0.1]:5702 is SHUTTING_DOWN
11:08:46,629  INFO |shouldNotProcessStaleJoinRequest| - [Node] Thread-37717 - [127.0.0.1]:5702 [dev] [4.2.1-SNAPSHOT] Node is already shutting down... Waiting for shutdown process to complete...
11:08:46,629  INFO |shouldNotProcessStaleJoinRequest| - [LifecycleService] Thread-37717 - [127.0.0.1]:5702 [dev] [4.2.1-SNAPSHOT] [127.0.0.1]:5702 is SHUTDOWN
11:08:46,629  INFO |shouldNotProcessStaleJoinRequest| - [LifecycleService] Thread-37717 - [127.0.0.1]:5701 [dev] [4.2.1-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
11:08:46,629  WARN |shouldNotProcessStaleJoinRequest| - [Node] Thread-37717 - [127.0.0.1]:5701 [dev] [4.2.1-SNAPSHOT] Terminating forcefully...
11:08:46,629  INFO |shouldNotProcessStaleJoinRequest| - [Node] Thread-37717 - [127.0.0.1]:5701 [dev] [4.2.1-SNAPSHOT] Shutting down connection manager...
11:08:46,629  INFO |shouldNotProcessStaleJoinRequest| - [Node] Thread-37717 - [127.0.0.1]:5701 [dev] [4.2.1-SNAPSHOT] Shutting down node engine...
11:08:46,841  INFO |shouldNotProcessStaleJoinRequest| - [NodeExtension] Thread-37717 - [127.0.0.1]:5701 [dev] [4.2.1-SNAPSHOT] Destroying node NodeExtension.
11:08:46,947  INFO |shouldNotProcessStaleJoinRequest| - [Node] Thread-37717 - [127.0.0.1]:5701 [dev] [4.2.1-SNAPSHOT] Hazelcast Shutdown is completed in 318 ms.
11:08:46,948  INFO |shouldNotProcessStaleJoinRequest| - [LifecycleService] Thread-37717 - [127.0.0.1]:5701 [dev] [4.2.1-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
BuildInfo right after shouldNotProcessStaleJoinRequest(com.hazelcast.internal.cluster.impl.MembershipUpdateTest): BuildInfo{version='4.2.1-SNAPSHOT', build='20210523', buildNumber=20210523, revision=e22aab3, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'shouldNotProcessStaleJoinRequest(com.hazelcast.internal.cluster.impl.MembershipUpdateTest):'
11:05:45, accumulated pauses: 646 ms, max pause: 228 ms, pauses over 1000 ms: 0
11:05:50, accumulated pauses: 11821 ms, max pause: 9997 ms, pauses over 1000 ms: 2
11:06:00, accumulated pauses: 153 ms, max pause: 6 ms, pauses over 1000 ms: 0
11:06:05, accumulated pauses: 10365 ms, max pause: 9936 ms, pauses over 1000 ms: 1
11:06:15, accumulated pauses: 715 ms, max pause: 14 ms, pauses over 1000 ms: 0
11:06:20, accumulated pauses: 1131 ms, max pause: 8 ms, pauses over 1000 ms: 0
11:06:25, accumulated pauses: 7060 ms, max pause: 7030 ms, pauses over 1000 ms: 1
11:06:30, accumulated pauses: 373 ms, max pause: 10 ms, pauses over 1000 ms: 0
11:06:35, accumulated pauses: 6097 ms, max pause: 5767 ms, pauses over 1000 ms: 1
11:06:40, accumulated pauses: 459 ms, max pause: 16 ms, pauses over 1000 ms: 0
11:06:45, accumulated pauses: 6356 ms, max pause: 5927 ms, pauses over 1000 ms: 1
11:06:50, accumulated pauses: 345 ms, max pause: 9 ms, pauses over 1000 ms: 0
11:06:55, accumulated pauses: 849 ms, max pause: 385 ms, pauses over 1000 ms: 0
11:07:00, accumulated pauses: 1921 ms, max pause: 1469 ms, pauses over 1000 ms: 1
11:07:05, accumulated pauses: 741 ms, max pause: 6 ms, pauses over 1000 ms: 0
11:07:10, accumulated pauses: 7212 ms, max pause: 4311 ms, pauses over 1000 ms: 2
11:07:15, accumulated pauses: 1663 ms, max pause: 1590 ms, pauses over 1000 ms: 1
11:07:20, accumulated pauses: 597 ms, max pause: 7 ms, pauses over 1000 ms: 0
11:07:25, accumulated pauses: 4946 ms, max pause: 3854 ms, pauses over 1000 ms: 1
11:07:30, accumulated pauses: 366 ms, max pause: 7 ms, pauses over 1000 ms: 0
11:07:35, accumulated pauses: 685 ms, max pause: 26 ms, pauses over 1000 ms: 0
11:07:40, accumulated pauses: 614 ms, max pause: 15 ms, pauses over 1000 ms: 0
11:07:45, accumulated pauses: 686 ms, max pause: 20 ms, pauses over 1000 ms: 0
11:07:50, accumulated pauses: 2952 ms, max pause: 2488 ms, pauses over 1000 ms: 1
11:07:55, accumulated pauses: 749 ms, max pause: 13 ms, pauses over 1000 ms: 0
11:08:00, accumulated pauses: 841 ms, max pause: 15 ms, pauses over 1000 ms: 0
11:08:05, accumulated pauses: 3648 ms, max pause: 2823 ms, pauses over 1000 ms: 1
11:08:10, accumulated pauses: 340 ms, max pause: 24 ms, pauses over 1000 ms: 0
11:08:15, accumulated pauses: 1436 ms, max pause: 1042 ms, pauses over 1000 ms: 1
11:08:20, accumulated pauses: 536 ms, max pause: 17 ms, pauses over 1000 ms: 0
11:08:25, accumulated pauses: 727 ms, max pause: 15 ms, pauses over 1000 ms: 0
11:08:30, accumulated pauses: 1472 ms, max pause: 642 ms, pauses over 1000 ms: 0
11:08:35, accumulated pauses: 560 ms, max pause: 6 ms, pauses over 1000 ms: 0
11:08:40, accumulated pauses: 1974 ms, max pause: 1633 ms, pauses over 1000 ms: 1
11:08:45, accumulated pauses: 138 ms, max pause: 15 ms, pauses over 1000 ms: 0
```

Standard output for `shouldNotProcessStaleJoinRequest_whenMasterChanges`:
```
11:08:47,439  INFO |shouldNotProcessStaleJoinRequest_whenMasterChanges| - [NodeExtension] Thread-37743 - [127.0.0.1]:5702 [dev] [4.2.1-SNAPSHOT] Destroying node NodeExtension.
11:08:47,440  INFO |shouldNotProcessStaleJoinRequest_whenMasterChanges| - [Node] Thread-37743 - [127.0.0.1]:5702 [dev] [4.2.1-SNAPSHOT] Hazelcast Shutdown is completed in 487 ms.
11:08:47,440  INFO |shouldNotProcessStaleJoinRequest_whenMasterChanges| - [LifecycleService] Thread-37743 - [127.0.0.1]:5702 [dev] [4.2.1-SNAPSHOT] [127.0.0.1]:5702 is SHUTDOWN
11:08:47,440  INFO |shouldNotProcessStaleJoinRequest_whenMasterChanges| - [LifecycleService] Thread-37743 - [127.0.0.1]:5701 [dev] [4.2.1-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
11:08:47,440  INFO |shouldNotProcessStaleJoinRequest_whenMasterChanges| - [Node] Thread-37743 - [127.0.0.1]:5701 [dev] [4.2.1-SNAPSHOT] Node is already shutting down... Waiting for shutdown process to complete...
11:08:47,442  INFO |shouldNotProcessStaleJoinRequest_whenMasterChanges| - [LifecycleService] Thread-37743 - [127.0.0.1]:5701 [dev] [4.2.1-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
BuildInfo right after shouldNotProcessStaleJoinRequest_whenMasterChanges(com.hazelcast.internal.cluster.impl.MembershipUpdateTest): BuildInfo{version='4.2.1-SNAPSHOT', build='20210523', buildNumber=20210523, revision=e22aab3, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'shouldNotProcessStaleJoinRequest_whenMasterChanges(com.hazelcast.internal.cluster.impl.MembershipUpdateTest):'
11:05:45, accumulated pauses: 646 ms, max pause: 228 ms, pauses over 1000 ms: 0
11:05:50, accumulated pauses: 11821 ms, max pause: 9997 ms, pauses over 1000 ms: 2
11:06:00, accumulated pauses: 153 ms, max pause: 6 ms, pauses over 1000 ms: 0
11:06:05, accumulated pauses: 10365 ms, max pause: 9936 ms, pauses over 1000 ms: 1
11:06:15, accumulated pauses: 715 ms, max pause: 14 ms, pauses over 1000 ms: 0
11:06:20, accumulated pauses: 1131 ms, max pause: 8 ms, pauses over 1000 ms: 0
11:06:25, accumulated pauses: 7060 ms, max pause: 7030 ms, pauses over 1000 ms: 1
11:06:30, accumulated pauses: 373 ms, max pause: 10 ms, pauses over 1000 ms: 0
11:06:35, accumulated pauses: 6097 ms, max pause: 5767 ms, pauses over 1000 ms: 1
11:06:40, accumulated pauses: 459 ms, max pause: 16 ms, pauses over 1000 ms: 0
11:06:45, accumulated pauses: 6356 ms, max pause: 5927 ms, pauses over 1000 ms: 1
11:06:50, accumulated pauses: 345 ms, max pause: 9 ms, pauses over 1000 ms: 0
11:06:55, accumulated pauses: 849 ms, max pause: 385 ms, pauses over 1000 ms: 0
11:07:00, accumulated pauses: 1921 ms, max pause: 1469 ms, pauses over 1000 ms: 1
11:07:05, accumulated pauses: 741 ms, max pause: 6 ms, pauses over 1000 ms: 0
11:07:10, accumulated pauses: 7212 ms, max pause: 4311 ms, pauses over 1000 ms: 2
11:07:15, accumulated pauses: 1663 ms, max pause: 1590 ms, pauses over 1000 ms: 1
11:07:20, accumulated pauses: 597 ms, max pause: 7 ms, pauses over 1000 ms: 0
11:07:25, accumulated pauses: 4946 ms, max pause: 3854 ms, pauses over 1000 ms: 1
11:07:30, accumulated pauses: 366 ms, max pause: 7 ms, pauses over 1000 ms: 0
11:07:35, accumulated pauses: 685 ms, max pause: 26 ms, pauses over 1000 ms: 0
11:07:40, accumulated pauses: 614 ms, max pause: 15 ms, pauses over 1000 ms: 0
11:07:45, accumulated pauses: 686 ms, max pause: 20 ms, pauses over 1000 ms: 0
11:07:50, accumulated pauses: 2952 ms, max pause: 2488 ms, pauses over 1000 ms: 1
11:07:55, accumulated pauses: 749 ms, max pause: 13 ms, pauses over 1000 ms: 0
11:08:00, accumulated pauses: 841 ms, max pause: 15 ms, pauses over 1000 ms: 0
11:08:05, accumulated pauses: 3648 ms, max pause: 2823 ms, pauses over 1000 ms: 1
11:08:10, accumulated pauses: 340 ms, max pause: 24 ms, pauses over 1000 ms: 0
11:08:15, accumulated pauses: 1436 ms, max pause: 1042 ms, pauses over 1000 ms: 1
11:08:20, accumulated pauses: 536 ms, max pause: 17 ms, pauses over 1000 ms: 0
11:08:25, accumulated pauses: 727 ms, max pause: 15 ms, pauses over 1000 ms: 0
11:08:30, accumulated pauses: 1472 ms, max pause: 642 ms, pauses over 1000 ms: 0
11:08:35, accumulated pauses: 560 ms, max pause: 6 ms, pauses over 1000 ms: 0
11:08:40, accumulated pauses: 1974 ms, max pause: 1633 ms, pauses over 1000 ms: 1
11:08:45, accumulated pauses: 180 ms, max pause: 15 ms, pauses over 1000 ms: 0
```

**Comment by olukas** [comment]
Closing this issue because:
- it hasn't occurred since we configured `CPU shares = 8` for Docker container which runs the test.
- it seems to be related to big hiccups or timeout issue

We will reopen the issue if it fails again in the future.

**Comment by Patras3** [comment]
Reopening as issue occurred again on: _master_ (commit c9bcf1afcf43e3a5e15d652e520ce7dcb6edc928)
with microsoft-17: https://jenkins.hazelcast.com/job/Hazelcast-master-MicrosoftJDK17/43/testReport/junit/com.hazelcast.internal.cluster.impl/MembershipUpdateTest/shouldNotProcessStaleJoinRequest/
<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: Cluster size is not correct. Expected: 1, actual: 2, instance index: 0
	at org.junit.Assert.fail(Assert.java:89)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSize(HazelcastTestSupport.java:1058)
	at com.hazelcast.internal.cluster.impl.MembershipUpdateTest.lambda$shouldNotProcessStaleJoinRequest$12(MembershipUpdateTest.java:643)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueAllTheTime(HazelcastTestSupport.java:1228)
	at com.hazelcast.internal.cluster.impl.MembershipUpdateTest.shouldNotProcessStaleJoinRequest(MembershipUpdateTest.java:639)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)

```
</details>


<details><summary>Standard output:</summary>

```
Finished Running Test: memberListsConverge_whenFinalizeJoinAndMembershipUpdatesSent_outOfOrder in 55.518 seconds.


```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-MicrosoftJDK17/43/

**Comment by arodionov** [comment]
Should be fixed by https://github.com/hazelcast/hazelcast/pull/23281

**Comment by olukas** [comment]
Reopening as issue occurred again on: _master_ (commit cae25cf53c3847ea2c3387651a66da08f78c1853)
with oracle-11 (little-endian): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-little-endian/281/testReport/com.hazelcast.internal.cluster.impl/MembershipUpdateTest/shouldNotProcessStaleJoinRequest_whenMasterChanges/
<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: Cluster size is not correct. Expected: 1, actual: 2, instance index: 0
	at org.junit.Assert.fail(Assert.java:89)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSize(HazelcastTestSupport.java:1015)
	at com.hazelcast.internal.cluster.impl.MembershipUpdateTest.lambda$shouldNotProcessStaleJoinRequest_whenMasterChanges$8(MembershipUpdateTest.java:666)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueAllTheTime(HazelcastTestSupport.java:1161)
	at com.hazelcast.internal.cluster.impl.MembershipUpdateTest.shouldNotProcessStaleJoinRequest_whenMasterChanges(MembershipUpdateTest.java:662)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)

```
</details>



Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-little-endian/281/

**Comment by Patras3** [comment]
Failed again on _master_ with microsoft-11: https://jenkins.hazelcast.com/job/Hazelcast-master-MicrosoftJDK11/94/testReport/com.hazelcast.internal.cluster.impl/MembershipUpdateTest/shouldNotProcessStaleJoinRequest/

**Comment by Patras3** [comment]
Failed again on _master_ with openjdk-17: https://jenkins.hazelcast.com/job/Hazelcast-master-ZuluJDK17/127/testReport/junit/com.hazelcast.internal.cluster.impl/MembershipUpdateTest/

**Comment by olukas** [comment]
Closing the test failure - it doesn't seem to be related to `master` or the latest maintenance stream `5.5.z` and it hasn't fail in the last 3 months. Feel free to reopen test failure if it occurs on `master` or on the latest maintenance stream.
