### ISSUE TITLE
com.hazelcast.jet.impl.connector.StreamFilesPTest.when_writeTwoFiles_then_seeAllLines failed on Solaris

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#18758]
_master_ (commit c3c641fc6af0924ccc140f24d98e37f7f8dd66b1)

Failed on Solaris with Oracle JDK 8: http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Solaris-OracleJDK8/310/com.hazelcast$hazelcast/testReport/com.hazelcast.jet.impl.connector/StreamFilesPTest/when_writeTwoFiles_then_seeAllLines/

Stacktrace:
```
java.lang.AssertionError: emittedCount=1000, expected=2000
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at com.hazelcast.jet.impl.connector.StreamFilesPTest.lambda$assertEmittedCountEventually$6(StreamFilesPTest.java:347)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1248)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1265)
	at com.hazelcast.jet.impl.connector.StreamFilesPTest.assertEmittedCountEventually(StreamFilesPTest.java:347)
	at com.hazelcast.jet.impl.connector.StreamFilesPTest.when_writeTwoFiles_then_seeAllLines(StreamFilesPTest.java:149)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

Standard output:
```
14:34:28,378  WARN || - [ClientConnectionManager] hz.client_4243.internal-10 - hz.client_4243 [7f79d202-1588-4383-a147-5ad1dc28ee7b] [5.0-SNAPSHOT] [5.0-SNAPSHOT] Could not connect to member 52488b06-2f19-4e71-b093-0419c9aeb57d, reason com.hazelcast.core.HazelcastException: java.io.IOException: Connection refused to address /127.0.0.1:5701
14:34:28,378  WARN || - [ClientConnectionManager] hz.client_4242.internal-10 - hz.client_4242 [7f79d202-1588-4383-a147-5ad1dc28ee7b] [5.0-SNAPSHOT] [5.0-SNAPSHOT] Could not connect to member 52488b06-2f19-4e71-b093-0419c9aeb57d, reason com.hazelcast.core.HazelcastException: java.io.IOException: Connection refused to address /127.0.0.1:5701
14:34:28,715  WARN || - [ClientConnectionManager] hz.client_4260.internal-4 - hz.client_4260 [7f79d202-1588-4383-a147-5ad1dc28ee7b] [5.0-SNAPSHOT] [5.0-SNAPSHOT] Could not connect to member 52488b06-2f19-4e71-b093-0419c9aeb57d, reason com.hazelcast.core.HazelcastException: java.io.IOException: Connection refused to address /127.0.0.1:5701
14:34:28,715  WARN || - [ClientConnectionManager] hz.client_4261.internal-4 - hz.client_4261 [7f79d202-1588-4383-a147-5ad1dc28ee7b] [5.0-SNAPSHOT] [5.0-SNAPSHOT] Could not connect to member 52488b06-2f19-4e71-b093-0419c9aeb57d, reason com.hazelcast.core.HazelcastException: java.io.IOException: Connection refused to address /127.0.0.1:5701
14:34:29,343  INFO || - [ClientConnectionManager] hz.client_4243.internal-1 - hz.client_4243 [7f79d202-1588-4383-a147-5ad1dc28ee7b] [5.0-SNAPSHOT] [5.0-SNAPSHOT] Trying to connect to Member [127.0.0.1]:5701 - 52488b06-2f19-4e71-b093-0419c9aeb57d
14:34:29,343  WARN || - [ClientConnectionManager] hz.client_4243.internal-1 - hz.client_4243 [7f79d202-1588-4383-a147-5ad1dc28ee7b] [5.0-SNAPSHOT] [5.0-SNAPSHOT] Exception during initial connection to Member [127.0.0.1]:5701 - 52488b06-2f19-4e71-b093-0419c9aeb57d: com.hazelcast.core.HazelcastException: java.io.IOException: Connection refused to address /127.0.0.1:5701
14:34:29,343  WARN || - [ClientConnectionManager] hz.client_4243.internal-1 - hz.client_4243 [7f79d202-1588-4383-a147-5ad1dc28ee7b] [5.0-SNAPSHOT] [5.0-SNAPSHOT] Unable to get live cluster connection, retry in 3364 ms, attempt: 26, cluster connect timeout: INFINITE, max backoff: 30000 ms
14:34:29,345  INFO || - [ClientConnectionManager] hz.client_4261.internal-3 - hz.client_4261 [7f79d202-1588-4383-a147-5ad1dc28ee7b] [5.0-SNAPSHOT] [5.0-SNAPSHOT] Trying to connect to Member [127.0.0.1]:5701 - 52488b06-2f19-4e71-b093-0419c9aeb57d
14:34:29,345  INFO || - [ClientConnectionManager] hz.client_4242.internal-1 - hz.client_4242 [7f79d202-1588-4383-a147-5ad1dc28ee7b] [5.0-SNAPSHOT] [5.0-SNAPSHOT] Trying to connect to Member [127.0.0.1]:5701 - 52488b06-2f19-4e71-b093-0419c9aeb57d
14:34:29,346  WARN || - [ClientConnectionManager] hz.client_4261.internal-3 - hz.client_4261 [7f79d202-1588-4383-a147-5ad1dc28ee7b] [5.0-SNAPSHOT] [5.0-SNAPSHOT] Exception during initial connection to Member [127.0.0.1]:5701 - 52488b06-2f19-4e71-b093-0419c9aeb57d: com.hazelcast.core.HazelcastException: java.io.IOException: Connection refused to address /127.0.0.1:5701
14:34:29,346  WARN || - [ClientConnectionManager] hz.client_4261.internal-3 - hz.client_4261 [7f79d202-1588-4383-a147-5ad1dc28ee7b] [5.0-SNAPSHOT] [5.0-SNAPSHOT] Unable to get live cluster connection, retry in 3364 ms, attempt: 26, cluster connect timeout: INFINITE, max backoff: 30000 ms
14:34:29,346  WARN || - [ClientConnectionManager] hz.client_4242.internal-1 - hz.client_4242 [7f79d202-1588-4383-a147-5ad1dc28ee7b] [5.0-SNAPSHOT] [5.0-SNAPSHOT] Exception during initial connection to Member [127.0.0.1]:5701 - 52488b06-2f19-4e71-b093-0419c9aeb57d: com.hazelcast.core.HazelcastException: java.io.IOException: Connection refused to address /127.0.0.1:5701
14:34:29,346  WARN || - [ClientConnectionManager] hz.client_4242.internal-1 - hz.client_4242 [7f79d202-1588-4383-a147-5ad1dc28ee7b] [5.0-SNAPSHOT] [5.0-SNAPSHOT] Unable to get live cluster connection, retry in 3364 ms, attempt: 26, cluster connect timeout: INFINITE, max backoff: 30000 ms
14:34:29,346  INFO || - [ClientConnectionManager] hz.client_4260.internal-3 - hz.client_4260 [7f79d202-1588-4383-a147-5ad1dc28ee7b] [5.0-SNAPSHOT] [5.0-SNAPSHOT] Trying to connect to Member [127.0.0.1]:5701 - 52488b06-2f19-4e71-b093-0419c9aeb57d
14:34:29,346  WARN || - [ClientConnectionManager] hz.client_4260.internal-3 - hz.client_4260 [7f79d202-1588-4383-a147-5ad1dc28ee7b] [5.0-SNAPSHOT] [5.0-SNAPSHOT] Exception during initial connection to Member [127.0.0.1]:5701 - 52488b06-2f19-4e71-b093-0419c9aeb57d: com.hazelcast.core.HazelcastException: java.io.IOException: Connection refused to address /127.0.0.1:5701
14:34:29,346  WARN || - [ClientConnectionManager] hz.client_4260.internal-3 - hz.client_4260 [7f79d202-1588-4383-a147-5ad1dc28ee7b] [5.0-SNAPSHOT] [5.0-SNAPSHOT] Unable to get live cluster connection, retry in 3364 ms, attempt: 26, cluster connect timeout: INFINITE, max backoff: 30000 ms
14:34:29,378  WARN || - [ClientConnectionManager] hz.client_4242.internal-2 - hz.client_4242 [7f79d202-1588-4383-a147-5ad1dc28ee7b] [5.0-SNAPSHOT] [5.0-SNAPSHOT] Could not connect to member 52488b06-2f19-4e71-b093-0419c9aeb57d, reason com.hazelcast.core.HazelcastException: java.io.IOException: Connection refused to address /127.0.0.1:5701
14:34:29,378  WARN || - [ClientConnectionManager] hz.client_4243.internal-2 - hz.client_4243 [7f79d202-1588-4383-a147-5ad1dc28ee7b] [5.0-SNAPSHOT] [5.0-SNAPSHOT] Could not connect to member 52488b06-2f19-4e71-b093-0419c9aeb57d, reason com.hazelcast.core.HazelcastException: java.io.IOException: Connection refused to address /127.0.0.1:5701
14:34:29,715  WARN || - [ClientConnectionManager] hz.client_4260.internal-1 - hz.client_4260 [7f79d202-1588-4383-a147-5ad1dc28ee7b] [5.0-SNAPSHOT] [5.0-SNAPSHOT] Could not connect to member 52488b06-2f19-4e71-b093-0419c9aeb57d, reason com.hazelcast.core.HazelcastException: java.io.IOException: Connection refused to address /127.0.0.1:5701
14:34:29,715  WARN || - [ClientConnectionManager] hz.client_4261.internal-1 - hz.client_4261 [7f79d202-1588-4383-a147-5ad1dc28ee7b] [5.0-SNAPSHOT] [5.0-SNAPSHOT] Could not connect to member 52488b06-2f19-4e71-b093-0419c9aeb57d, reason com.hazelcast.core.HazelcastException: java.io.IOException: Connection refused to address /127.0.0.1:5701
14:34:30,378  WARN || - [ClientConnectionManager] hz.client_4242.internal-4 - hz.client_4242 [7f79d202-1588-4383-a147-5ad1dc28ee7b] [5.0-SNAPSHOT] [5.0-SNAPSHOT] Could not connect to member 52488b06-2f19-4e71-b093-0419c9aeb57d, reason com.hazelcast.core.HazelcastException: java.io.IOException: Connection refused to address /127.0.0.1:5701
14:34:30,378  WARN || - [ClientConnectionManager] hz.client_4243.internal-4 - hz.client_4243 [7f79d202-1588-4383-a147-5ad1dc28ee7b] [5.0-SNAPSHOT] [5.0-SNAPSHOT] Could not connect to member 52488b06-2f19-4e71-b093-0419c9aeb57d, reason com.hazelcast.core.HazelcastException: java.io.IOException: Connection refused to address /127.0.0.1:5701
14:34:30,715  WARN || - [ClientConnectionManager] hz.client_4260.internal-7 - hz.client_4260 [7f79d202-1588-4383-a147-5ad1dc28ee7b] [5.0-SNAPSHOT] [5.0-SNAPSHOT] Could not connect to member 52488b06-2f19-4e71-b093-0419c9aeb57d, reason com.hazelcast.core.HazelcastException: java.io.IOException: Connection refused to address /127.0.0.1:5701
14:34:30,715  WARN || - [ClientConnectionManager] hz.client_4261.internal-2 - hz.client_4261 [7f79d202-1588-4383-a147-5ad1dc28ee7b] [5.0-SNAPSHOT] [5.0-SNAPSHOT] Could not connect to member 52488b06-2f19-4e71-b093-0419c9aeb57d, reason com.hazelcast.core.HazelcastException: java.io.IOException: Connection refused to address /127.0.0.1:5701
14:34:31,378  WARN || - [ClientConnectionManager] hz.client_4243.internal-9 - hz.client_4243 [7f79d202-1588-4383-a147-5ad1dc28ee7b] [5.0-SNAPSHOT] [5.0-SNAPSHOT] Could not connect to member 52488b06-2f19-4e71-b093-0419c9aeb57d, reason com.hazelcast.core.HazelcastException: java.io.IOException: Connection refused to address /127.0.0.1:5701
14:34:31,378  WARN || - [ClientConnectionManager] hz.client_4242.internal-9 - hz.client_4242 [7f79d202-1588-4383-a147-5ad1dc28ee7b] [5.0-SNAPSHOT] [5.0-SNAPSHOT] Could not connect to member 52488b06-2f19-4e71-b093-0419c9aeb57d, reason com.hazelcast.core.HazelcastException: java.io.IOException: Connection refused to address /127.0.0.1:5701
14:34:31,715  WARN || - [ClientConnectionManager] hz.client_4260.internal-5 - hz.client_4260 [7f79d202-1588-4383-a147-5ad1dc28ee7b] [5.0-SNAPSHOT] [5.0-SNAPSHOT] Could not connect to member 52488b06-2f19-4e71-b093-0419c9aeb57d, reason com.hazelcast.core.HazelcastException: java.io.IOException: Connection refused to address /127.0.0.1:5701
14:34:31,715  WARN || - [ClientConnectionManager] hz.client_4261.internal-10 - hz.client_4261 [7f79d202-1588-4383-a147-5ad1dc28ee7b] [5.0-SNAPSHOT] [5.0-SNAPSHOT] Could not connect to member 52488b06-2f19-4e71-b093-0419c9aeb57d, reason com.hazelcast.core.HazelcastException: java.io.IOException: Connection refused to address /127.0.0.1:5701
14:34:32,379  WARN || - [ClientConnectionManager] hz.client_4242.internal-3 - hz.client_4242 [7f79d202-1588-4383-a147-5ad1dc28ee7b] [5.0-SNAPSHOT] [5.0-SNAPSHOT] Could not connect to member 52488b06-2f19-4e71-b093-0419c9aeb57d, reason com.hazelcast.core.HazelcastException: java.io.IOException: Connection refused to address /127.0.0.1:5701
14:34:32,379  WARN || - [ClientConnectionManager] hz.client_4243.internal-6 - hz.client_4243 [7f79d202-1588-4383-a147-5ad1dc28ee7b] [5.0-SNAPSHOT] [5.0-SNAPSHOT] Could not connect to member 52488b06-2f19-4e71-b093-0419c9aeb57d, reason com.hazelcast.core.HazelcastException: java.io.IOException: Connection refused to address /127.0.0.1:5701
14:34:34,164  INFO || - [ClientConnectionManager] hz.client_4242.internal-1 - hz.client_4242 [7f79d202-1588-4383-a147-5ad1dc28ee7b] [5.0-SNAPSHOT] [5.0-SNAPSHOT] Trying to connect to Member [127.0.0.1]:5701 - 52488b06-2f19-4e71-b093-0419c9aeb57d
14:34:34,164  INFO || - [ClientConnectionManager] hz.client_4260.internal-3 - hz.client_4260 [7f79d202-1588-4383-a147-5ad1dc28ee7b] [5.0-SNAPSHOT] [5.0-SNAPSHOT] Trying to connect to Member [127.0.0.1]:5701 - 52488b06-2f19-4e71-b093-0419c9aeb57d
14:34:34,164  INFO || - [ClientConnectionManager] hz.client_4261.internal-3 - hz.client_4261 [7f79d202-1588-4383-a147-5ad1dc28ee7b] [5.0-SNAPSHOT] [5.0-SNAPSHOT] Trying to connect to Member [127.0.0.1]:5701 - 52488b06-2f19-4e71-b093-0419c9aeb57d
14:34:34,164  INFO || - [ClientConnectionManager] hz.client_4243.internal-1 - hz.client_4243 [7f79d202-1588-4383-a147-5ad1dc28ee7b] [5.0-SNAPSHOT] [5.0-SNAPSHOT] Trying to connect to Member [127.0.0.1]:5701 - 52488b06-2f19-4e71-b093-0419c9aeb57d
14:34:34,166  WARN || - [ClientConnectionManager] hz.client_4243.internal-7 - hz.client_4243 [7f79d202-1588-4383-a147-5ad1dc28ee7b] [5.0-SNAPSHOT] [5.0-SNAPSHOT] Could not connect to member 52488b06-2f19-4e71-b093-0419c9aeb57d, reason com.hazelcast.core.HazelcastException: java.io.IOException: Connection refused to address /127.0.0.1:5701
14:34:34,166  WARN || - [ClientConnectionManager] hz.client_4261.internal-3 - hz.client_4261 [7f79d202-1588-4383-a147-5ad1dc28ee7b] [5.0-SNAPSHOT] [5.0-SNAPSHOT] Exception during initial connection to Member [127.0.0.1]:5701 - 52488b06-2f19-4e71-b093-0419c9aeb57d: com.hazelcast.core.HazelcastException: java.io.IOException: Connection refused to address /127.0.0.1:5701
14:34:34,166  WARN || - [ClientConnectionManager] hz.client_4261.internal-8 - hz.client_4261 [7f79d202-1588-4383-a147-5ad1dc28ee7b] [5.0-SNAPSHOT] [5.0-SNAPSHOT] Could not connect to member 52488b06-2f19-4e71-b093-0419c9aeb57d, reason com.hazelcast.core.HazelcastException: java.io.IOException: Connection refused to address /127.0.0.1:5701
14:34:34,166  WARN || - [ClientConnectionManager] hz.client_4242.internal-7 - hz.client_4242 [7f79d202-1588-4383-a147-5ad1dc28ee7b] [5.0-SNAPSHOT] [5.0-SNAPSHOT] Could not connect to member 52488b06-2f19-4e71-b093-0419c9aeb57d, reason com.hazelcast.core.HazelcastException: java.io.IOException: Connection refused to address /127.0.0.1:5701
14:34:34,166  WARN || - [ClientConnectionManager] hz.client_4260.internal-10 - hz.client_4260 [7f79d202-1588-4383-a147-5ad1dc28ee7b] [5.0-SNAPSHOT] [5.0-SNAPSHOT] Could not connect to member 52488b06-2f19-4e71-b093-0419c9aeb57d, reason com.hazelcast.core.HazelcastException: java.io.IOException: Connection refused to address /127.0.0.1:5701
14:34:34,166  WARN || - [ClientConnectionManager] hz.client_4260.internal-3 - hz.client_4260 [7f79d202-1588-4383-a147-5ad1dc28ee7b] [5.0-SNAPSHOT] [5.0-SNAPSHOT] Exception during initial connection to Member [127.0.0.1]:5701 - 52488b06-2f19-4e71-b093-0419c9aeb57d: com.hazelcast.core.HazelcastException: java.io.IOException: Connection refused to address /127.0.0.1:5701
14:34:34,166  WARN || - [ClientConnectionManager] hz.client_4261.internal-3 - hz.client_4261 [7f79d202-1588-4383-a147-5ad1dc28ee7b] [5.0-SNAPSHOT] [5.0-SNAPSHOT] Unable to get live cluster connection, retry in 3532 ms, attempt: 27, cluster connect timeout: INFINITE, max backoff: 30000 ms
14:34:34,166  WARN || - [ClientConnectionManager] hz.client_4243.internal-1 - hz.client_4243 [7f79d202-1588-4383-a147-5ad1dc28ee7b] [5.0-SNAPSHOT] [5.0-SNAPSHOT] Exception during initial connection to Member [127.0.0.1]:5701 - 52488b06-2f19-4e71-b093-0419c9aeb57d: com.hazelcast.core.HazelcastException: java.io.IOException: Connection refused to address /127.0.0.1:5701
14:34:34,166  WARN || - [ClientConnectionManager] hz.client_4242.internal-1 - hz.client_4242 [7f79d202-1588-4383-a147-5ad1dc28ee7b] [5.0-SNAPSHOT] [5.0-SNAPSHOT] Exception during initial connection to Member [127.0.0.1]:5701 - 52488b06-2f19-4e71-b093-0419c9aeb57d: com.hazelcast.core.HazelcastException: java.io.IOException: Connection refused to address /127.0.0.1:5701
14:34:34,166  WARN || - [ClientConnectionManager] hz.client_4260.internal-3 - hz.client_4260 [7f79d202-1588-4383-a147-5ad1dc28ee7b] [5.0-SNAPSHOT] [5.0-SNAPSHOT] Unable to get live cluster connection, retry in 3532 ms, attempt: 27, cluster connect timeout: INFINITE, max backoff: 30000 ms
14:34:34,166  WARN || - [ClientConnectionManager] hz.client_4243.internal-1 - hz.client_4243 [7f79d202-1588-4383-a147-5ad1dc28ee7b] [5.0-SNAPSHOT] [5.0-SNAPSHOT] Unable to get live cluster connection, retry in 3532 ms, attempt: 27, cluster connect timeout: INFINITE, max backoff: 30000 ms
14:34:34,166  WARN || - [ClientConnectionManager] hz.client_4242.internal-1 - hz.client_4242 [7f79d202-1588-4383-a147-5ad1dc28ee7b] [5.0-SNAPSHOT] [5.0-SNAPSHOT] Unable to get live cluster connection, retry in 3532 ms, attempt: 27, cluster connect timeout: INFINITE, max backoff: 30000 ms
BuildInfo right after when_writeTwoFiles_then_seeAllLines(com.hazelcast.jet.impl.connector.StreamFilesPTest): BuildInfo{version='5.0-SNAPSHOT', build='20210522', buildNumber=20210522, revision=c3c641f, enterprise=false, serializationVersion=1, jet=JetBuildInfo{version='5.0-SNAPSHOT', build='20210522', revision='c3c641f'}}
Hiccups measured while running test 'when_writeTwoFiles_then_seeAllLines(com.hazelcast.jet.impl.connector.StreamFilesPTest):'
14:34:20, accumulated pauses: 4490 ms, max pause: 9 ms, pauses over 1000 ms: 0
14:34:25, accumulated pauses: 4490 ms, max pause: 9 ms, pauses over 1000 ms: 0
14:34:30, accumulated pauses: 3950 ms, max pause: 1751 ms, pauses over 1000 ms: 1
```

**Comment by olukas** [comment]
Failed again, but again with high hiccups: http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Solaris-OracleJDK8-without-checkstyle/4/com.hazelcast$hazelcast/testReport/com.hazelcast.jet.impl.connector/StreamFilesPTest/when_writeTwoFiles_then_seeAllLines/

Hiccups:
```
Hiccups measured while running test 'when_writeTwoFiles_then_seeAllLines(com.hazelcast.jet.impl.connector.StreamFilesPTest):'
05:27:30, accumulated pauses: 4482 ms, max pause: 9 ms, pauses over 1000 ms: 0
05:27:35, accumulated pauses: 4480 ms, max pause: 8 ms, pauses over 1000 ms: 0
05:27:40, accumulated pauses: 4987 ms, max pause: 1297 ms, pauses over 1000 ms: 1
05:27:45, accumulated pauses: 0 ms, max pause: 0 ms, pauses over 1000 ms: 0
```

**Comment by slavagithub** [comment]
The same for when_lineAddedInChunks_then_readAtOnce  test on the same job

**Comment by olukas** [comment]
Solaris is supported on a one-off, best effort, case-by-case basis => closing this test failure.
