### ISSUE TITLE
com.hazelcast.internal.cluster.impl.AdvancedClusterStateTest

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#18752]
_master_  (commit c3c641fc6af0924ccc140f24d98e37f7f8dd66b1)

Failed on IBM JDK 8 nightly run: http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-IbmJDK8-nightly/1/testReport/com.hazelcast.internal.cluster.impl/AdvancedClusterStateTest/

Almost all tests from `com.hazelcast.internal.cluster.impl.AdvancedClusterStateTest` (only `changeClusterState_shouldFail_whenStartupIsNotCompleted` passed without failures) failed with the same exception (timed out).

Stacktrace (for `testPromoteToRaftMember` as an example):
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.lang.Thread.startImpl(Native Method)
	at java.lang.Thread.start(Thread.java:992)
	at com.hazelcast.internal.partition.impl.MigrationManager.start(MigrationManager.java:702)
	at com.hazelcast.internal.partition.impl.InternalPartitionServiceImpl.init(InternalPartitionServiceImpl.java:189)
	at com.hazelcast.spi.impl.servicemanager.impl.ServiceManagerImpl.initService(ServiceManagerImpl.java:234)
	at com.hazelcast.spi.impl.servicemanager.impl.ServiceManagerImpl.initServices(ServiceManagerImpl.java:210)
	at com.hazelcast.spi.impl.servicemanager.impl.ServiceManagerImpl.start(ServiceManagerImpl.java:102)
	at com.hazelcast.spi.impl.NodeEngineImpl.start(NodeEngineImpl.java:225)
	at com.hazelcast.instance.impl.Node.start(Node.java:447)
	at com.hazelcast.instance.impl.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:124)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:211)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:190)
	at com.hazelcast.test.TestHazelcastInstanceFactory.newHazelcastInstance(TestHazelcastInstanceFactory.java:224)
	at com.hazelcast.cp.internal.HazelcastRaftTestSupport.newInstances(HazelcastRaftTestSupport.java:114)
	at com.hazelcast.cp.internal.CPMemberAddRemoveTest.testPromoteToRaftMember(CPMemberAddRemoveTest.java:107)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.lang.Thread.run(Thread.java:822)
```

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts?region=us-east-1&prefix=Hazelcast-master-IbmJDK8-nightly/1/&showversions=false

**Comment by olukas** [comment]
Closing this issue because:
- it hasn't occurred since we configured `CPU shares = 8` for Docker container which runs the test.
- it seems to be related to big hiccups or timeout issue

We will reopen the issue if it fails again in the future.
