### ISSUE TITLE
com.hazelcast.cp.internal.datastructures.atomiclong.AtomicLongBasicTest

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#18769]
_master_ (commit 737e470cd5a7d4b8e2866b76f681596058ddcd73)

Failed on Zulu JDK 16: http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZuluJDK16/28/testReport/com.hazelcast.cp.internal.datastructures.atomiclong/AtomicLongBasicTest/

All tests from `com.hazelcast.cp.internal.datastructures.atomiclong.AtomicLongBasicTest` failed with various exceptions. The most often exception was `java.lang.AssertionError: Cluster size is not correct. Expected: 4, actual: 1, instance index: 0`.

Stacktrace for `testAlterAndGetAsync` as an example of aforementioned exception:
```
java.lang.AssertionError: Cluster size is not correct. Expected: 4, actual: 1, instance index: 0
	at org.junit.Assert.fail(Assert.java:89)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSize(HazelcastTestSupport.java:1035)
	at com.hazelcast.test.HazelcastTestSupport$11.run(HazelcastTestSupport.java:1063)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1248)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1265)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:1060)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:1048)
	at com.hazelcast.cp.internal.HazelcastRaftTestSupport.newInstances(HazelcastRaftTestSupport.java:117)
	at com.hazelcast.cp.internal.datastructures.atomiclong.AtomicLongBasicTest.createInstances(AtomicLongBasicTest.java:48)
	at com.hazelcast.cp.internal.datastructures.atomiclong.AbstractAtomicLongBasicTest.setup(AbstractAtomicLongBasicTest.java:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:393)
	at com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37)
	at com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:104)
	at com.hazelcast.test.metrics.MetricsRule$1.evaluate(MetricsRule.java:62)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at com.hazelcast.test.HazelcastParallelClassRunner.access$301(HazelcastParallelClassRunner.java:49)
	at com.hazelcast.test.HazelcastParallelClassRunner$TestRunner.run(HazelcastParallelClassRunner.java:162)
	at java.base/java.lang.Thread.run(Thread.java:831)
```

Standard output and the rest stacktraces can be found here - https://s3.console.aws.amazon.com/s3/object/j-artifacts?region=us-east-1&prefix=Hazelcast-master-ZuluJDK16/28/Hazelcast-master-ZuluJDK16-28.tar

**Comment by vbekiaris** [comment]
Machine load related failure (see https://github.com/hazelcast/hazelcast/issues/18770#issuecomment-847854628). Jenkins job configuration was updated with `8` CPU limit and seems to behave better. Closing for now.
