### ISSUE TITLE
com.hazelcast.cp.internal.MetadataRaftGroupTest (maintenance branch)

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#18772]
_4.2.z_ (commit e22aab3cffbb36863a91276dd2506b4fcf4a7f6c)

Failed on Zulu JDK 11: http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-4.maintenance-ZuluJDK11/1/testReport/com.hazelcast.cp.internal/MetadataRaftGroupTest/

Following test from `com.hazelcast.cp.internal.MetadataRaftGroupTest` failed with `java.lang.AssertionError: expected:<SHUT_DOWN> but was:<ACTIVE>`:
- `when_membersLeaveDuringInitialDiscovery_thenAllMembersTerminate`

Following tests from `com.hazelcast.cp.internal.MetadataRaftGroupTest` failed with `org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds` (timed out):
- `when_nonMetadataRaftGroupLosesMajority_then_itCanBeForceDestroyed`
- `when_nonReachableEndpointsExist_createRaftGroupPrefersReachableEndpoints`
- `when_memberIsShutdown_then_itIsRemovedFromRaftGroups`
- `when_raftGroupIsCreatedFromNonCPNode_then_raftNodeIsCreatedOnOnlyTheSelectedEndpoints`
- `when_membersLeaveDuringDiscoveryAfterCPSubsystemRestart_then_discoveryIsCancelled`

Stacktrace for `when_membersLeaveDuringInitialDiscovery_thenAllMembersTerminate`:
```
java.lang.AssertionError: expected:<SHUT_DOWN> but was:<ACTIVE>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:120)
	at org.junit.Assert.assertEquals(Assert.java:146)
	at com.hazelcast.cp.internal.MetadataRaftGroupTest.lambda$when_membersLeaveDuringInitialDiscovery_thenAllMembersTerminate$26(MetadataRaftGroupTest.java:641)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1247)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1349)
	at com.hazelcast.cp.internal.MetadataRaftGroupTest.when_membersLeaveDuringInitialDiscovery_thenAllMembersTerminate(MetadataRaftGroupTest.java:639)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Stacktrace for `when_raftGroupIsCreatedFromNonCPNode_then_raftNodeIsCreatedOnOnlyTheSelectedEndpoints`:
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.base@11.0.8/java.lang.Thread.start0(Native Method)
	at java.base@11.0.8/java.lang.Thread.start(Thread.java:803)
	at java.base@11.0.8/java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:937)
	at java.base@11.0.8/java.util.concurrent.ThreadPoolExecutor.ensurePrestart(ThreadPoolExecutor.java:1583)
	at java.base@11.0.8/java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:346)
	at java.base@11.0.8/java.util.concurrent.ScheduledThreadPoolExecutor.scheduleAtFixedRate(ScheduledThreadPoolExecutor.java:632)
	at app//com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor.start(InvocationMonitor.java:225)
	at app//com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.start(OperationServiceImpl.java:487)
	at app//com.hazelcast.spi.impl.NodeEngineImpl.start(NodeEngineImpl.java:227)
	at app//com.hazelcast.instance.impl.Node.start(Node.java:447)
	at app//com.hazelcast.instance.impl.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:123)
	at app//com.hazelcast.instance.impl.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:211)
	at app//com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:190)
	at app//com.hazelcast.test.TestHazelcastInstanceFactory.newHazelcastInstance(TestHazelcastInstanceFactory.java:224)
	at app//com.hazelcast.cp.internal.HazelcastRaftTestSupport.newInstances(HazelcastRaftTestSupport.java:114)
	at app//com.hazelcast.cp.internal.MetadataRaftGroupTest.when_raftGroupIsCreatedWithSomeCPNodes_then_raftNodeIsCreatedOnOnlyTheSelectedEndpoints(MetadataRaftGroupTest.java:231)
	at app//com.hazelcast.cp.internal.MetadataRaftGroupTest.when_raftGroupIsCreatedFromNonCPNode_then_raftNodeIsCreatedOnOnlyTheSelectedEndpoints(MetadataRaftGroupTest.java:224)
	at java.base@11.0.8/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@11.0.8/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base@11.0.8/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@11.0.8/java.lang.reflect.Method.invoke(Method.java:566)
	at app//org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at app//org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at app//org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at app//org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at app//com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at app//com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base@11.0.8/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base@11.0.8/java.lang.Thread.run(Thread.java:834)
```

Standard output can be found here - https://s3.console.aws.amazon.com/s3/object/j-artifacts?region=us-east-1&prefix=Hazelcast-4.maintenance-ZuluJDK11/1/Hazelcast-4.maintenance-ZuluJDK11-1.tar

**Comment by olukas** [comment]
Closing this issue because:
- it hasn't occurred since we configured `CPU shares = 8` for Docker container which runs the test.
- it seems to be related to big hiccups or timeout issue

We will reopen the issue if it fails again in the future.
