### ISSUE TITLE
com.hazelcast.instance.impl.HazelcastBootstrapTest.bootstrappedInstance

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#18771]
_master_ (commit 737e470cd5a7d4b8e2866b76f681596058ddcd73)

Failed on Sonar nightly build (Oracle JDK 11): http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/876/testReport/com.hazelcast.instance.impl/HazelcastBootstrapTest/bootstrappedInstance/

Stacktrace:
```
com.hazelcast.core.HazelcastInstanceNotActiveException: HazelcastInstance[[127.0.0.1]:5701] is not active!
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyRegistry.getService(ProxyRegistry.java:79)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyRegistry.<init>(ProxyRegistry.java:61)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyServiceImpl.lambda$new$0(ProxyServiceImpl.java:84)
	at com.hazelcast.internal.util.ConcurrencyUtil.getOrPutIfAbsent(ConcurrencyUtil.java:154)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyServiceImpl.getOrCreateRegistry(ProxyServiceImpl.java:144)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyServiceImpl.getDistributedObject(ProxyServiceImpl.java:152)
	at com.hazelcast.instance.impl.HazelcastInstanceImpl.getDistributedObject(HazelcastInstanceImpl.java:355)
	at com.hazelcast.instance.impl.HazelcastInstanceImpl.getFlakeIdGenerator(HazelcastInstanceImpl.java:269)
	at com.hazelcast.jet.impl.JobRepository.lambda$new$5(JobRepository.java:196)
	at com.hazelcast.jet.impl.util.ConcurrentMemoizingSupplier.get(ConcurrentMemoizingSupplier.java:50)
	at com.hazelcast.jet.impl.JobRepository.newJobId(JobRepository.java:270)
	at com.hazelcast.jet.impl.AbstractJetInstance.newJobId(AbstractJetInstance.java:71)
	at com.hazelcast.jet.impl.AbstractJetInstance.newJob(AbstractJetInstance.java:88)
	at com.hazelcast.instance.impl.HazelcastBootstrap$BootstrappedJetProxy.newJob(HazelcastBootstrap.java:595)
	at com.hazelcast.jet.JetInstance.newJob(JetInstance.java:103)
	at com.hazelcast.instance.impl.HazelcastBootstrapTest.bootstrappedInstance(HazelcastBootstrapTest.java:47)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by gurbuzali** [comment]
this [commit](https://github.com/hazelcast/hazelcast/pull/18664/commits/70cf5cc73363831d1f296b18767bdc02f3b121b8) in my PR https://github.com/hazelcast/hazelcast/pull/18664 addresses this issue.

**Comment by mmedenjak** [comment]
@gurbuzali can we then close the issue?

**Comment by gurbuzali** [comment]
yes we can close it
