### ISSUE TITLE
com.hazelcast.replicatedmap.ReplicatedMapReorderedReplicationTest.testNonConvergingReplicatedMaps

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#18782]
_4.2.z_ (commit e22aab3cffbb36863a91276dd2506b4fcf4a7f6c)

Failed on Zulu JDK 16: http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-4.maintenance-ZuluJDK16-nightly/2/testReport/com.hazelcast.replicatedmap/ReplicatedMapReorderedReplicationTest/testNonConvergingReplicatedMaps/

Stacktrace:
```
java.lang.NoSuchFieldException: modifiers
	at java.base/java.lang.Class.getDeclaredField(Class.java:2549)
	at com.hazelcast.replicatedmap.ReplicatedMapReorderedReplicationTest.updateFactory(ReplicatedMapReorderedReplicationTest.java:157)
	at com.hazelcast.replicatedmap.ReplicatedMapReorderedReplicationTest.testNonConvergingReplicatedMaps(ReplicatedMapReorderedReplicationTest.java:78)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:831)
```

Standard output:
```
BuildInfo right after testNonConvergingReplicatedMaps(com.hazelcast.replicatedmap.ReplicatedMapReorderedReplicationTest): BuildInfo{version='4.2.1-SNAPSHOT', build='20210526', buildNumber=20210526, revision=e22aab3, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'testNonConvergingReplicatedMaps(com.hazelcast.replicatedmap.ReplicatedMapReorderedReplicationTest):'
16:43:45, accumulated pauses: 827 ms, max pause: 582 ms, pauses over 1000 ms: 0
```

**Comment by olukas** [comment]
Failed also on `master` with Zulu JDK 16: http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZuluJDK16-nightly/2/testReport/com.hazelcast.replicatedmap/ReplicatedMapReorderedReplicationTest/testNonConvergingReplicatedMaps/

**Comment by olukas** [comment]
Failed again on `4.2.z` branch with Zulu JDK 16 (it seems to be related to this JDK - I haven't seen it failed on any other JDK): http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-4.maintenance-ZuluJDK16-nightly/4/testReport/com.hazelcast.replicatedmap/ReplicatedMapReorderedReplicationTest/testNonConvergingReplicatedMaps/
