### ISSUE TITLE
com.hazelcast.client.starter.HazelcastClientStarterTest.testClientLifecycle

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#18783]
_4.2.z_ (commit e22aab3cffbb36863a91276dd2506b4fcf4a7f6c)

Failed on Sonar nightly build (Oracle JDK 11): http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-4.maintenance-sonar/824/testReport/com.hazelcast.client.starter/HazelcastClientStarterTest/testClientLifecycle/

Stacktrace:
```
com.hazelcast.test.starter.GuardianException: java.net.NoRouteToHostException: No route to host (Host unreachable)
	at com.hazelcast.test.starter.HazelcastStarterUtils.rethrowGuardianException(HazelcastStarterUtils.java:53)
	at com.hazelcast.test.starter.HazelcastVersionLocator.downloadFile(HazelcastVersionLocator.java:125)
	at com.hazelcast.test.starter.HazelcastVersionLocator.downloadMainArtifact(HazelcastVersionLocator.java:96)
	at com.hazelcast.test.starter.HazelcastVersionLocator.locateMainArtifact(HazelcastVersionLocator.java:78)
	at com.hazelcast.test.starter.HazelcastVersionLocator.locateVersion(HazelcastVersionLocator.java:63)
	at com.hazelcast.test.starter.HazelcastStarter$HazelcastVersionClassloaderFuture.get(HazelcastStarter.java:343)
	at com.hazelcast.test.starter.HazelcastStarter.getTargetVersionClassloader(HazelcastStarter.java:210)
	at com.hazelcast.client.starter.HazelcastClientStarter.newHazelcastClient(HazelcastClientStarter.java:46)
	at com.hazelcast.client.starter.HazelcastClientStarter.newHazelcastClient(HazelcastClientStarter.java:40)
	at com.hazelcast.client.starter.HazelcastClientStarterTest.testClientLifecycle(HazelcastClientStarterTest.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.net.NoRouteToHostException: No route to host (Host unreachable)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:285)
	at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265)
	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1181)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1075)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1581)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:245)
	at java.base/java.net.URL.openStream(URL.java:1117)
	at com.hazelcast.test.starter.HazelcastVersionLocator.downloadFile(HazelcastVersionLocator.java:119)
	... 20 more
```

Standard output:
```
Started Running Test: testClientLifecycle
class com.hazelcast.instance.impl.HazelcastInstanceFactory loaded by HazelcastAPIDelegatingClassloader{urls = "[file:/tmp/1622072100295-0/4.0.3/hazelcast-4.0.3.jar, file:/tmp/1622072100295-0/4.0.3/hazelcast-4.0.3-tests.jar]"}
02:09:14,817  INFO |testClientLifecycle| - [MetricsConfigHelper] testClientLifecycle - [LOCAL] [dev] [4.0.3] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
02:09:14,817  INFO |testClientLifecycle| - [AddressPicker] testClientLifecycle - [LOCAL] [dev] [4.0.3] Picked [127.0.0.1]:5701, using socket ServerSocket[addr=/0.0.0.0,localport=5701], bind any local is true
02:09:14,819  INFO |testClientLifecycle| - [system] testClientLifecycle - [127.0.0.1]:5701 [dev] [4.0.3] Hazelcast 4.0.3 (20200921 - 59ae831) starting at [127.0.0.1]:5701
02:09:14,819  INFO |testClientLifecycle| - [system] testClientLifecycle - [127.0.0.1]:5701 [dev] [4.0.3] Copyright (c) 2008-2020, Hazelcast, Inc. All Rights Reserved.
02:09:14,820  INFO |testClientLifecycle| - [MetricsConfigHelper] testClientLifecycle - [127.0.0.1]:5701 [dev] [4.0.3] Collecting debug metrics and sending to diagnostics is enabled
02:09:14,820  INFO |testClientLifecycle| - [BackpressureRegulator] testClientLifecycle - [127.0.0.1]:5701 [dev] [4.0.3] Backpressure is disabled
02:09:14,828  WARN |testClientLifecycle| - [Node] testClientLifecycle - [127.0.0.1]:5701 [dev] [4.0.3] Hazelcast is bound to 127.0.0.1 and loop-back mode is disabled in the configuration. This could cause multicast auto-discovery issues and render it unable to work. Check your network connectivity, try to enable the loopback mode and/or force -Djava.net.preferIPv4Stack=true on your JVM.
02:09:14,828  INFO |testClientLifecycle| - [Node] testClientLifecycle - [127.0.0.1]:5701 [dev] [4.0.3] Creating MulticastJoiner
02:09:14,828  WARN |testClientLifecycle| - [CPSubsystem] testClientLifecycle - [127.0.0.1]:5701 [dev] [4.0.3] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
02:09:14,845  INFO |testClientLifecycle| - [OperationExecutorImpl] testClientLifecycle - [127.0.0.1]:5701 [dev] [4.0.3] Starting 8 partition threads and 5 generic threads (1 dedicated for priority tasks)
02:09:14,846  INFO |testClientLifecycle| - [Diagnostics] testClientLifecycle - [127.0.0.1]:5701 [dev] [4.0.3] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
02:09:14,846  INFO |testClientLifecycle| - [LifecycleService] testClientLifecycle - [127.0.0.1]:5701 [dev] [4.0.3] [127.0.0.1]:5701 is STARTING
02:09:16,884  INFO |testClientLifecycle| - [ClusterService] testClientLifecycle - [127.0.0.1]:5701 [dev] [4.0.3] 

Members {size:1, ver:1} [
	Member [127.0.0.1]:5701 - eb3739f9-97a6-44aa-9dfb-59a2e6dbb46a this
]

02:09:16,885  INFO |testClientLifecycle| - [LifecycleService] testClientLifecycle - [127.0.0.1]:5701 [dev] [4.0.3] [127.0.0.1]:5701 is STARTED
Starting client 4.0.1
02:09:27,479  INFO |testClientLifecycle| - [LifecycleService] main - [127.0.0.1]:5701 [dev] [4.0.3] [127.0.0.1]:5701 is SHUTTING_DOWN
02:09:27,480  INFO |testClientLifecycle| - [Node] main - [127.0.0.1]:5701 [dev] [4.0.3] Shutting down multicast service...
02:09:27,480  INFO |testClientLifecycle| - [Node] main - [127.0.0.1]:5701 [dev] [4.0.3] Shutting down connection manager...
02:09:27,481  INFO |testClientLifecycle| - [Node] main - [127.0.0.1]:5701 [dev] [4.0.3] Shutting down node engine...
02:09:27,488  INFO |testClientLifecycle| - [NodeExtension] main - [127.0.0.1]:5701 [dev] [4.0.3] Destroying node NodeExtension.
02:09:27,489  INFO |testClientLifecycle| - [Node] main - [127.0.0.1]:5701 [dev] [4.0.3] Hazelcast Shutdown is completed in 10 ms.
02:09:27,490  INFO |testClientLifecycle| - [LifecycleService] main - [127.0.0.1]:5701 [dev] [4.0.3] [127.0.0.1]:5701 is SHUTDOWN
```

**Comment by sancar** [comment]
Moving to 5.0 to check in stabilization period.

**Comment by frant-hartm** [comment]
The test failed to download other Hazelcast jars for testing the infrastructure used for compatibility test. Likely due to a network glitch.

We could either add retry logic to the download code, or maybe make maven download the dependencies beforehand so they are cached in local maven repository. We can't use regular dependencies though becase we would polute the classpath with previous version(s). We could add executions of the dependencies plugin (https://maven.apache.org/plugins/maven-dependency-plugin/usage.html#dependency:get) for required versions, maybe in some profiles. @vbekiaris wdyt?

**Comment by vbekiaris** [comment]
> We could add executions of the dependencies plugin (https://maven.apache.org/plugins/maven-dependency-plugin/usage.html#dependency:get) for required versions, maybe in some profiles.

Yes, we could add that to profiles that execute the `SlowTest`s. Still, wouldn't that also fail in case of network issues? Or is the maven dependency plugin doing something smarter like checking alternate repositories/mirrors?

**Comment by frant-hartm** [comment]
Maven dependency plugin has built in retries, so it would work in case of a brief network glitch. It would also be reported as a build failure, not a test failure.

But after more thought - because this is (supposedly) a rare failure I proposed to close this issue and address it only if it happens again.
