### ISSUE TITLE
com.hazelcast.jet.python.PythonInitCleanupTest

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#18801]
_master_ (commit e19ab8c4bea1cb2a78d91d7da9fb3daf9f637404)

Failed on Zulu JDK 16: http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZuluJDK16-nightly/2/testReport/com.hazelcast.jet.python/PythonInitCleanupTest/

All tests from `com.hazelcast.jet.python.PythonInitCleanupTest` failed with the same exception.

Stacktrace (for `initRunsBeforeJob` as an example):
```
com.hazelcast.jet.JetException: The JobConfig contains resources to upload, but the resource upload is disabled. Either remove the resources from the job config or enabled resource uploading, see JetConfig#setResourceUploadEnabled.
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitJob$1(JobCoordinationService.java:208)
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$47(JobCoordinationService.java:1075)
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$48(JobCoordinationService.java:1096)
	at com.hazelcast.internal.util.executor.CompletableFutureTask.run(CompletableFutureTask.java:64)
	at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
```

Standard output:
```
07:40:15,238  INFO || - [MetricsConfigHelper] Time-limited test - [LOCAL] [dev] [5.0-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
07:40:15,276  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] 
	o  o   O   o---o o--o o      o-o   O    o-o  o-O-o     o--o  o       O  o-O-o o--o  o-o  o--o  o   o 
	|  |  / \     /  |    |     /     / \  |       |       |   | |      / \   |   |    o   o |   | |\ /| 
	O--O o---o  -O-  O-o  |    O     o---o  o-o    |       O--o  |     o---o  |   O-o  |   | O-Oo  | O | 
	|  | |   |  /    |    |     \    |   |     |   |       |     |     |   |  |   |    o   o |  \  |   | 
	o  o o   o o---o o--o O---o  o-o o   o o--o    o       o     O---o o   o  o   o     o-o  o   o o   o
07:40:15,276  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Copyright (c) 2008-2021, Hazelcast, Inc. All Rights Reserved.
07:40:15,276  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Hazelcast Platform 5.0-SNAPSHOT (20210528 - e19ab8c) starting at [127.0.0.1]:5701
07:40:15,276  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Cluster name: dev
07:40:15,468  INFO || - [MetricsConfigHelper] Time-limited test - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
07:40:15,720  WARN || - [CPSubsystem] Time-limited test - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
07:40:15,934  INFO || - [JetService] Time-limited test - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Setting number of cooperative threads and default parallelism to 2
07:40:15,946  INFO || - [Diagnostics] Time-limited test - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
07:40:15,952  INFO || - [LifecycleService] Time-limited test - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] [127.0.0.1]:5701 is STARTING
07:40:15,962  INFO || - [JetExtension] Time-limited test - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Jet extension is enabled after the cluster version upgrade.
07:40:15,962  INFO || - [ClusterService] Time-limited test - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] 

Members {size:1, ver:1} [
	Member [127.0.0.1]:5701 - aa7a83a2-62ef-4674-8bd5-a46a9ab9c98f this
]

07:40:15,962 DEBUG || - [JobCoordinationService] hz.naughty_swanson.cached.thread-1 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
07:40:15,969  INFO || - [JetExtension] Time-limited test - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Jet extension is enabled
07:40:15,969 DEBUG || - [JobCoordinationService] hz.naughty_swanson.cached.thread-1 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
07:40:15,970  INFO || - [LifecycleService] Time-limited test - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] [127.0.0.1]:5701 is STARTED
07:40:15,971  INFO || - [MetricsConfigHelper] Time-limited test - [LOCAL] [dev] [5.0-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
07:40:15,972  INFO || - [system] Time-limited test - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] 
	o  o   O   o---o o--o o      o-o   O    o-o  o-O-o     o--o  o       O  o-O-o o--o  o-o  o--o  o   o 
	|  |  / \     /  |    |     /     / \  |       |       |   | |      / \   |   |    o   o |   | |\ /| 
	O--O o---o  -O-  O-o  |    O     o---o  o-o    |       O--o  |     o---o  |   O-o  |   | O-Oo  | O | 
	|  | |   |  /    |    |     \    |   |     |   |       |     |     |   |  |   |    o   o |  \  |   | 
	o  o o   o o---o o--o O---o  o-o o   o o--o    o       o     O---o o   o  o   o     o-o  o   o o   o
07:40:15,972  INFO || - [system] Time-limited test - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Copyright (c) 2008-2021, Hazelcast, Inc. All Rights Reserved.
07:40:15,972  INFO || - [system] Time-limited test - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Hazelcast Platform 5.0-SNAPSHOT (20210528 - e19ab8c) starting at [127.0.0.1]:5702
07:40:15,973  INFO || - [system] Time-limited test - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Cluster name: dev
07:40:15,977  INFO || - [MetricsConfigHelper] Time-limited test - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
07:40:15,983  WARN || - [CPSubsystem] Time-limited test - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
07:40:15,991  INFO || - [JetService] Time-limited test - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Setting number of cooperative threads and default parallelism to 2
07:40:15,994  INFO || - [Diagnostics] Time-limited test - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
07:40:15,999  INFO || - [LifecycleService] Time-limited test - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] [127.0.0.1]:5702 is STARTING
07:40:16,006  INFO || - [MockServer] Time-limited test - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Created connection to endpoint: [127.0.0.1]:5701, connection: MockConnection{localEndpoint=[127.0.0.1]:5702, remoteEndpoint=[127.0.0.1]:5701, alive=true}
07:40:16,012  INFO || - [HealthMonitor] hz.naughty_swanson.HealthMonitor - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] processors=8, physical.memory.total=377.6G, physical.memory.free=107.8G, swap.space.total=4.0G, swap.space.free=2.4G, heap.memory.used=48.3M, heap.memory.free=4.0G, heap.memory.total=4.0G, heap.memory.max=4.0G, heap.memory.used/total=1.18%, heap.memory.used/max=1.18%, minor.gc.count=1, minor.gc.time=2ms, major.gc.count=0, major.gc.time=0ms, load.process=5.26%, load.system=100.00%, load.systemAverage=29.10, thread.count=55, thread.peakCount=55, cluster.timeDiff=0, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=0, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=1, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=0, clientEndpoint.count=0, connection.active.count=0, client.connection.count=0, connection.count=0
07:40:16,016  INFO || - [MockServer] hz.naughty_swanson.generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Created connection to endpoint: [127.0.0.1]:5702, connection: MockConnection{localEndpoint=[127.0.0.1]:5701, remoteEndpoint=[127.0.0.1]:5702, alive=true}
07:40:16,020  INFO || - [ClusterService] hz.naughty_swanson.generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] 

Members {size:2, ver:2} [
	Member [127.0.0.1]:5701 - aa7a83a2-62ef-4674-8bd5-a46a9ab9c98f this
	Member [127.0.0.1]:5702 - 63481a63-d2f2-4bd3-b7ce-31bd3fd1b2de
]

07:40:16,063 DEBUG || - [JobCoordinationService] hz.naughty_swanson.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
07:40:16,069 DEBUG || - [JobCoordinationService] hz.naughty_swanson.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
07:40:16,109  INFO || - [JetExtension] hz.amazing_swanson.generic-operation.thread-1 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Jet extension is enabled after the cluster version upgrade.
07:40:16,113  INFO || - [ClusterService] hz.amazing_swanson.generic-operation.thread-1 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] 

Members {size:2, ver:2} [
	Member [127.0.0.1]:5701 - aa7a83a2-62ef-4674-8bd5-a46a9ab9c98f
	Member [127.0.0.1]:5702 - 63481a63-d2f2-4bd3-b7ce-31bd3fd1b2de this
]

07:40:16,113  INFO || - [JetExtension] Time-limited test - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Jet extension is enabled
07:40:16,114  INFO || - [LifecycleService] Time-limited test - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] [127.0.0.1]:5702 is STARTED
Started Running Test: initRunsBeforeJob
07:40:16,119  INFO || - [HealthMonitor] hz.amazing_swanson.HealthMonitor - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] processors=8, physical.memory.total=377.6G, physical.memory.free=107.8G, swap.space.total=4.0G, swap.space.free=2.4G, heap.memory.used=53.3M, heap.memory.free=3.9G, heap.memory.total=4.0G, heap.memory.max=4.0G, heap.memory.used/total=1.28%, heap.memory.used/max=1.28%, minor.gc.count=2, minor.gc.time=7ms, major.gc.count=0, major.gc.time=0ms, load.process=7.41%, load.system=100.00%, load.systemAverage=29.10, thread.count=57, thread.peakCount=57, cluster.timeDiff=-2, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=17, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=0, clientEndpoint.count=0, connection.active.count=0, client.connection.count=0, connection.count=0
07:40:16,164 DEBUG || - [JobCoordinationService] hz.naughty_swanson.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
07:40:16,169 DEBUG || - [JobCoordinationService] hz.naughty_swanson.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
07:40:16,210  INFO |initRunsBeforeJob| - [PartitionStateManager] initRunsBeforeJob - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Initializing cluster partition table arrangement...
07:40:16,276 DEBUG || - [JobRepository] hz.naughty_swanson.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 7ms
07:40:16,276 DEBUG || - [JobRepository] hz.naughty_swanson.cached.thread-1 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 5ms
07:40:16,289  WARN || - [JobCoordinationService] hz.naughty_swanson.cached.thread-1 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] null
com.hazelcast.jet.JetException: The JobConfig contains resources to upload, but the resource upload is disabled. Either remove the resources from the job config or enabled resource uploading, see JetConfig#setResourceUploadEnabled.
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitJob$1(JobCoordinationService.java:208) ~[hazelcast-5.0-SNAPSHOT.jar:5.0-SNAPSHOT]
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$47(JobCoordinationService.java:1075) ~[hazelcast-5.0-SNAPSHOT.jar:5.0-SNAPSHOT]
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$48(JobCoordinationService.java:1096) ~[hazelcast-5.0-SNAPSHOT.jar:5.0-SNAPSHOT]
	at com.hazelcast.internal.util.executor.CompletableFutureTask.run(CompletableFutureTask.java:64) [hazelcast-5.0-SNAPSHOT.jar:5.0-SNAPSHOT]
	at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217) [hazelcast-5.0-SNAPSHOT.jar:5.0-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76) [hazelcast-5.0-SNAPSHOT.jar:5.0-SNAPSHOT]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) [hazelcast-5.0-SNAPSHOT.jar:5.0-SNAPSHOT]
07:40:16,325  INFO |initRunsBeforeJob| - [SimpleTestInClusterSupport] Time-limited test - Ditching 0 jobs in SimpleTestInClusterSupport.@After: []
07:40:16,326  INFO |initRunsBeforeJob| - [SimpleTestInClusterSupport] Time-limited test - Destroying 3 distributed objects in SimpleTestInClusterSupport.@After: [hz:impl:mapService/__jet.results, hz:impl:mapService/__jet.resources.0640-b985-eec0-0001, hz:impl:flakeIdGeneratorService/__jet.ids]
BuildInfo right after initRunsBeforeJob(com.hazelcast.jet.python.PythonInitCleanupTest): BuildInfo{version='5.0-SNAPSHOT', build='20210528', buildNumber=20210528, revision=e19ab8c, enterprise=false, serializationVersion=1, jet=JetBuildInfo{version='5.0-SNAPSHOT', build='20210528', revision='e19ab8c'}}
Hiccups measured while running test 'initRunsBeforeJob(com.hazelcast.jet.python.PythonInitCleanupTest):'
07:40:15, accumulated pauses: 10 ms, max pause: 10 ms, pauses over 1000 ms: 0
```

**Comment by olukas** [comment]
Failed also with IBM JDK 8: http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-IbmJDK8-nightly/2/testReport/com.hazelcast.jet.python/PythonInitCleanupTest/

**Comment by PavloBida** [comment]
Also fails on Zulu JDK16: http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZuluJDK16-nightly/5/
