### ISSUE TITLE
[4.1.z] SqlErrorClientTest.testMemberDisconnect_fetch failed

### ISSUE THREAD

**Issue by kwart** [hazelcast/hazelcast#18822]
The `SqlErrorClientTest.testMemberDisconnect_fetch` failded on PR builder for `4.1.z`:
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/5317/

**Stacktrace:**
```
junit.framework.AssertionFailedError: -1: java.io.IOException: Packet not sent to [127.0.0.1]:5701 ClientMessage{connection=null, length=76, operation=Sql.Fetch, isRetryable=false, correlationId=7, messageType=210200, isEvent=false, isfragmented=false} expected:<1001> but was:<-1>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at junit.framework.TestCase.assertEquals(TestCase.java:377)
	at com.hazelcast.sql.SqlErrorAbstractTest.assertErrorCode(SqlErrorAbstractTest.java:321)
	at com.hazelcast.sql.SqlErrorClientTest.testMemberDisconnect_fetch(SqlErrorClientTest.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by sancar** [comment]
Moving to 5.0 to check in stabilization period.
