### ISSUE TITLE
Warning being logger: Missing responseHandler for com.hazelcast.spi.impl.operationparker.impl.WaitSetEntry

### ISSUE THREAD

**Issue by jerrinot** [hazelcast/hazelcast#18899]
@olukas reported that under some circumstances he observed this warning in a server log:
```
2021-06-10T09:29:29.116920577Z WARNING: [172.28.1.1]:5701 [scalingCluster] [5.0-SNAPSHOT] Missing responseHandler for com.hazelcast.spi.impl.operationparker.impl.WaitSetEntry{serviceName='hz:impl:mapService', identityHash=1597720371, partitionId=171, replicaIndex=0, callId=0, invocationTime=-1 (1969-12-31 23:59:59.999), waitTimeout=-1, callTimeout=9223372036854775807, tenantControl=com.hazelcast.spi.impl.tenantcontrol.NoopTenantControl@0, op=com.hazelcast.map.impl.journal.MapEventJournalReadOperation{serviceName='hz:impl:mapService', identityHash=973043488, partitionId=171, replicaIndex=0, callId=404, invocationTime=1623317308362 (2021-06-10 09:28:28.362), waitTimeout=-1, callTimeout=60000, tenantControl=com.hazelcast.spi.impl.tenantcontrol.NoopTenantControl@0}, expirationTimeMs=-1, valid=true}
2021-06-10T09:29:29.116933485Z com.hazelcast.spi.exception.PartitionMigratingException: Partition is migrating! this: [172.28.1.1]:5701, partitionId: 171, operation: com.hazelcast.spi.impl.operationparker.impl.WaitSetEntry, service: hz:impl:mapService
2021-06-10T09:29:29.116939804Z  at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.ensureNoPartitionProblems(OperationRunnerImpl.java:384)
2021-06-10T09:29:29.116945678Z  at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:241)
2021-06-10T09:29:29.116950716Z  at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:213)
2021-06-10T09:29:29.116955672Z  at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:175)
2021-06-10T09:29:29.116961202Z  at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:139)
2021-06-10T09:29:29.116974369Z  at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123)
2021-06-10T09:29:29.116979565Z  at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
```

I managed to create a reproducer:
```
package com.hazelcast;

import com.hazelcast.config.Config;
import com.hazelcast.core.HazelcastInstance;
import com.hazelcast.internal.partition.MigrationInfo;
import com.hazelcast.internal.partition.impl.InternalPartitionServiceImpl;
import com.hazelcast.internal.partition.impl.MigrationInterceptor;
import com.hazelcast.internal.util.UuidUtil;
import com.hazelcast.map.IMap;
import com.hazelcast.spi.properties.ClusterProperty;
import com.hazelcast.test.Accessors;
import com.hazelcast.test.HazelcastParallelClassRunner;
import com.hazelcast.test.HazelcastTestSupport;
import com.hazelcast.test.TestHazelcastInstanceFactory;
import com.hazelcast.test.annotation.ParallelJVMTest;
import com.hazelcast.test.annotation.QuickTest;
import org.junit.Test;
import org.junit.experimental.categories.Category;
import org.junit.runner.RunWith;

import java.util.concurrent.CountDownLatch;
import java.util.concurrent.TimeUnit;

@RunWith(HazelcastParallelClassRunner.class)
@Category({QuickTest.class, ParallelJVMTest.class})
public class WaitSetTest extends HazelcastTestSupport {

    private static final String SOURCE_MAP = "sourceMap";
    private static final int INSTANCE_COUNT = 3;
    private static final int ENTRY_COUNT = 1000;
    private static final int PARTITION_COUNT = 1;

    @Test
    public void bar() throws Exception {
        TestHazelcastInstanceFactory instanceFactory = createHazelcastInstanceFactory(INSTANCE_COUNT);
        HazelcastInstance driver = startNewInstance(instanceFactory);
        populateMap(driver, ENTRY_COUNT);

        String[] keys = new String[PARTITION_COUNT];
        for (int i = 0; i < PARTITION_COUNT; i++) {
            keys[i] = generateKeyForPartition(driver, i);
        }

        IMap<String, ?> map = driver.getMap(SOURCE_MAP);
        for (int i = 0; i < PARTITION_COUNT; i++) {
            map.lock(keys[i]);
        }

        CountDownLatch latch = new CountDownLatch(PARTITION_COUNT);
        for (int i = 0; i < PARTITION_COUNT; i++) {
            int finalI = i;
            new Thread(() -> {
                for (;;) {
                    try {
                        long startingTime = System.nanoTime();
                        map.tryLock(keys[finalI], 100, TimeUnit.MILLISECONDS);
                        long durationNanos = System.nanoTime() - startingTime;
                        System.out.println("Took " + TimeUnit.NANOSECONDS.toMillis(durationNanos) + " ms.");
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                    latch.countDown();
                }
            }).start();
        }
        scaleUp(instanceFactory);
        assertOpenEventually(latch);
    }

    private void scaleUp(TestHazelcastInstanceFactory instanceFactory) throws InterruptedException {
        for (int i = 0; i < INSTANCE_COUNT - 1; i++) {
            startNewInstance(instanceFactory);
            Thread.sleep(15_000);
        }
    }

    private HazelcastInstance startNewInstance(TestHazelcastInstanceFactory instanceFactory) {
        HazelcastInstance instance = instanceFactory.newHazelcastInstance(newConfig());
        InternalPartitionServiceImpl partitionService = (InternalPartitionServiceImpl) Accessors.getPartitionService(instance);
        partitionService.setMigrationInterceptor(new MigrationInterceptor() {
            @Override
            public void onMigrationCommit(MigrationParticipant participant, MigrationInfo migration) {
                sleepAtLeastMillis(1500);
            }
        });

        return instance;
    }

    private void populateMap(HazelcastInstance driver, int entryCount) {
        IMap<String, String> map = driver.getMap(SOURCE_MAP);
        for (int i = 0; i < entryCount; i++) {
            map.set(UuidUtil.newUnsecureUuidString(), UuidUtil.newUnsecureUuidString());
        }
    }

    private Config newConfig() {
        Config config = new Config();
        config.setProperty(ClusterProperty.PARTITION_COUNT.getName(), String.valueOf(PARTITION_COUNT));
        config.getMapConfig(SOURCE_MAP).getEventJournalConfig().setEnabled(true);
        return config;
    }
}
```

**Comment by mmedenjak** [comment]
Moving into 5.1 based on the current scope of 5.0. Feel free to reach out to me if you consider this critical.

**Comment by Holmistr** [comment]
Let's keep it in the 5.1 scope as it already has a PR but in case the PR review is very time consuming, we can move it to 5.2.
