### ISSUE TITLE
java.lang.IllegalThreadStateException:  cannot make remote call: com.hazelcast.map.impl.operation.EvictBatchBackupOperation

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#18912]
```
16:06:01 Installing core
16:06:01 installing /home/ec2-user/.m2/repository/com/hazelcast/hazelcast-enterprise/5.0-SNAPSHOT/hazelcast-enterprise-5.0-SNAPSHOT.jar
16:06:01 installing /home/ec2-user/.m2/repository/com/hazelcast/hazelcast-sql/5.0-SNAPSHOT/hazelcast-sql-5.0-SNAPSHOT.jar
16:06:01 HzMember2HZ Started 10.0.0.44 2046@ip-10-0-0-44.ec2.internal /home/ec2-user/hz-root/hz-lib/5.0-SNAPSHOT 
16:06:01 HzMember3HZ Started 10.0.0.7 2099@ip-10-0-0-7.ec2.internal /home/ec2-user/hz-root/hz-lib/5.0-SNAPSHOT 
16:06:01 HzMember1HZ Started 10.0.0.173 2010@ip-10-0-0-173.ec2.internal /home/ec2-user/hz-root/hz-lib/5.0-SNAPSHOT 
16:06:01 personMapBak1BINGet hzcmd.map.Get driver=.* threads=2 duration=0 bench=Roll interval=0 name=personMapBak1BIN
16:06:01 personMapBak1OBJSet hzcmd.map.Set driver=.* threads=2 duration=0 bench=Roll interval=0 name=personMapBak1OBJ valueSetSize=10 valueType=PersonRandom
16:06:01 personMapBak1HDSetRem hzcmd.map.SetRemove driver=.* threads=2 duration=0 bench=Roll interval=0 name=personMapBak1HD valueSetSize=10 valueType=PersonRandom
16:06:01 personMapBak1OBJSetRem hzcmd.map.SetRemove driver=.* threads=2 duration=0 bench=Roll interval=0 name=personMapBak1OBJ valueSetSize=10 valueType=PersonRandom
16:06:01 personMapBak1HDGet hzcmd.map.Get driver=.* threads=2 duration=0 bench=Roll interval=0 name=personMapBak1HD
16:06:01 personMapBak1HDSetTtl hzcmd.map.PutTtlWaitGet driver=.* threads=2 duration=0 bench=Roll interval=0 name=personMapBak1HD valueSetSize=10 valueType=PersonRandom
16:06:01 personMapBak1BINSet hzcmd.map.Set driver=.* threads=2 duration=0 bench=Roll interval=0 name=personMapBak1BIN valueSetSize=10 valueType=PersonRandom
16:06:01 personMapBak1BINSetRem hzcmd.map.SetRemove driver=.* threads=2 duration=0 bench=Roll interval=0 name=personMapBak1BIN valueSetSize=10 valueType=PersonRandom
16:06:01 personMapBak1BINSetTtl hzcmd.map.PutTtlWaitGet driver=.* threads=2 duration=0 bench=Roll interval=0 name=personMapBak1BIN valueSetSize=10 valueType=PersonRandom
16:06:01 personMapBak1OBJGet hzcmd.map.Get driver=.* threads=2 duration=0 bench=Roll interval=0 name=personMapBak1OBJ
16:06:01 personMapBak1HDSet hzcmd.map.Set driver=.* threads=2 duration=0 bench=Roll interval=0 name=personMapBak1HD valueSetSize=10 valueType=PersonRandom
16:06:01 personMapBak1OBJSetTtl hzcmd.map.PutTtlWaitGet driver=.* threads=2 duration=0 bench=Roll interval=0 name=personMapBak1OBJ valueSetSize=10 valueType=PersonRandom
16:06:01 fail HzMember3HZ personMapBak1HDSetRem hzcmd.map.SetRemove threadId=0 java.lang.IllegalThreadStateException: Thread[hz.happy_pasteur.partition-operation.thread-0,5,main] cannot make remote call: com.hazelcast.map.impl.operation.EvictBatchBackupOperation{serviceName='hz:impl:mapService', identityHash=726518038, partitionId=2, replicaIndex=1, callId=0, invocationTime=-1 (1969-12-31 23:59:59.999), waitTimeout=-1, callTimeout=60000, tenantControl=com.hazelcast.spi.impl.tenantcontrol.NoopTenantControl@0, name=personMapBak1HD} 
16:06:01 fail HzMember1HZ personMapBak1HDSetTtl hzcmd.map.PutTtlWaitGet threadId=0 java.lang.IllegalThreadStateException: Thread[hz.happy_pasteur.partition-operation.thread-1,5,main] cannot make remote call: com.hazelcast.map.impl.operation.EvictBatchBackupOperation{serviceName='hz:impl:mapService', identityHash=1593523581, partitionId=1, replicaIndex=1, callId=0, invocationTime=-1 (1969-12-31 23:59:59.999), waitTimeout=-1, callTimeout=60000, tenantControl=com.hazelcast.spi.impl.tenantcontrol.NoopTenantControl@0, name=personMapBak1HD} 
16:06:01 fail HzMember1HZ personMapBak1HDSet hzcmd.map.Set threadId=1 java.lang.IllegalThreadStateException: Thread[hz.happy_pasteur.partition-operation.thread-0,5,main] cannot make remote call: com.hazelcast.map.impl.operation.EvictBatchBackupOperation{serviceName='hz:impl:mapService', identityHash=794462703, partitionId=2, replicaIndex=1, callId=0, invocationTime=-1 (1969-12-31 23:59:59.999), waitTimeout=-1, callTimeout=60000, tenantControl=com.hazelcast.spi.impl.tenantcontrol.NoopTenantControl@0, name=personMapBak1HD} 
16:06:01 personMapBak1BINSet Done
16:06:01 personMapBak1OBJGet Done
16:06:01 personMapBak1BINGet Done
16:06:01 personMapBak1OBJSetTtl Done
16:06:01 personMapBak1HDGet Done
16:06:01 personMapBak1BINSetTtl Done
16:06:01 personMapBak1BINSetRem Done
16:06:01 personMapBak1OBJSet Done
16:06:01 personMapBak1OBJSetRem Done
16:06:01 hz-root/HzMember1HZ/exception.txt
16:06:01 
16:06:01 hz-root/HzMember3HZ/exception.txt
```

after about 1 hour of running   http://jenkins.hazelcast.com/view/hot-restart/job/hot-x/52/console.
all HD operations  resulting in evection failed,  but all OBJ and BIN seamed ok

```
java.lang.IllegalThreadStateException: Thread[hz.happy_pasteur.partition-operation.thread-0,5,main] cannot make remote call: com.hazelcast.map.impl.operation.EvictBatchBackupOperation{serviceName='hz:impl:mapService', identityHash=726518038, partitionId=2, replicaIndex=1, callId=0, invocationTime=-1 (1969-12-31 23:59:59.999), waitTimeout=-1, callTimeout=60000, tenantControl=com.hazelcast.spi.impl.tenantcontrol.NoopTenantControl@0, name=personMapBak1HD} 
```

```
java.lang.IllegalThreadStateException: Thread[hz.happy_pasteur.partition-operation.thread-0,5,main] cannot make remote call: com.hazelcast.map.impl.operation.EvictBatchBackupOperation{serviceName='hz:impl:mapService', identityHash=726518038, partitionId=2, replicaIndex=1, callId=0, invocationTime=-1 (1969-12-31 23:59:59.999), waitTimeout=-1, callTimeout=60000, tenantControl=com.hazelcast.spi.impl.tenantcontrol.NoopTenantControl@0, name=personMapBak1HD}
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:538)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:240)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:59)
	at com.hazelcast.internal.eviction.ToBackupSender.invokeBackupExpiryOperation(ToBackupSender.java:94)
	at com.hazelcast.internal.eviction.ToBackupSender.trySendExpiryOp(ToBackupSender.java:85)
	at com.hazelcast.map.impl.eviction.MapClearExpiredRecordsTask.tryToSendBackupExpiryOp(MapClearExpiredRecordsTask.java:136)
	at com.hazelcast.map.impl.eviction.MapClearExpiredRecordsTask.tryToSendBackupExpiryOp(MapClearExpiredRecordsTask.java:85)
	at com.hazelcast.map.impl.recordstore.expiry.ExpirySystem.accumulateOrSendExpiredKey(ExpirySystem.java:383)
	at com.hazelcast.map.impl.recordstore.AbstractEvictableRecordStore.doPostEvictionOperations(AbstractEvictableRecordStore.java:158)
	at com.hazelcast.map.impl.eviction.HDEvictorImpl.evictRecordStore(HDEvictorImpl.java:87)
	at com.hazelcast.map.impl.eviction.HDEvictorImpl.forceEvictByPercentage(HDEvictorImpl.java:71)
	at com.hazelcast.map.impl.operation.MultipleRecordStoreForcedEviction.forceEvictAndRun(MultipleRecordStoreForcedEviction.java:64)
	at com.hazelcast.map.impl.operation.ForcedEviction.runWithForcedEvictionStrategies(ForcedEviction.java:51)
	at com.hazelcast.map.impl.operation.MapOperation.rerunWithForcedEviction(MapOperation.java:128)
	at com.hazelcast.map.impl.operation.MapOperation.run(MapOperation.java:117)
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:189)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:272)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:248)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:469)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:197)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:137)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
	at ------ submitted from ------.()
	at com.hazelcast.internal.util.ExceptionUtil.cloneExceptionWithFixedAsyncStackTrace(ExceptionUtil.java:279)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.returnOrThrowWithGetConventions(InvocationFuture.java:112)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:100)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:617)
	at com.hazelcast.map.impl.proxy.MapProxySupport.invokeOperation(MapProxySupport.java:478)
	at com.hazelcast.map.impl.proxy.MapProxySupport.setInternal(MapProxySupport.java:555)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.set(MapProxyImpl.java:252)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.set(MapProxyImpl.java:242)
	at hzcmd.map.SetRemove.timeStep(SetRemove.java:12)
```

/disk1/workspace/hot-x/5.0-SNAPSHOT/2021_06_15-11_32_51/persist-ru

Vassilis Bekiaris  

my guess is that HD hits some point that it needs to force-evict and at the same time the buffer of eviction operations for backups is filled (default 100 ops can be batched) -> it is time to send the backup operations to the respective members -> a partition thread attempts to send the eviction operations to backups and fails because we don’t allow network operations from partition threads

I guess you can make it fail more quickly by making HD hit forced eviction more frequently and reducing the backup eviction ops batch size, let me find the property name for that. it’s hard coded to 100

issue to fix the forced eviction case that results in sending out networks ops from partition thread

**Comment by Danny-Hazelcast** [comment]
```
function ops() {
  for t in HD BIN OBJ ; do
    hz go -f personMapBak1${t}Set    hzcmd.map.Set           name=personMapBak1${t} threads=2 valueSetSize=10 valueType=PersonRandom &
    hz go -f personMapBak1${t}SetTtl hzcmd.map.PutTtlWaitGet name=personMapBak1${t} threads=2 valueSetSize=10 valueType=PersonRandom &
    hz go -f personMapBak1${t}SetRem hzcmd.map.SetRemove     name=personMapBak1${t} threads=2 valueSetSize=10 valueType=PersonRandom &
    hz go -f personMapBak1${t}Get    hzcmd.map.Get           name=personMapBak1${t} threads=2 &
  done
}

ops="$ops -Dhazelcast.enterprise.license.key=${HAZELCAST_EE_KEY}"
ops="$ops -Dhazelcast.slow.operation.detector.stacktrace.logging.enabled=true"
ops="$ops -ea"
hz memberOps "-Xms4G -Xmx4G ${ops}"
hz cluster -size M3 -v ${version} -ee


ops
```

**Comment by Danny-Hazelcast** [comment]
```
<map name="personMapBak1HD*">
        <backup-count>1</backup-count>
        <in-memory-format>NATIVE</in-memory-format>
        <indexes>
            <index name="a" type="SORTED">
                <attributes>
                    <attribute>personId</attribute>
                </attributes>
            </index>
        </indexes>
        <merkle-tree enabled="true" ></merkle-tree>
        <hot-restart enabled="true">
            <fsync>false</fsync>
        </hot-restart>
        <eviction eviction-policy="LRU" max-size-policy="USED_NATIVE_MEMORY_PERCENTAGE" size="99"/>
        <max-idle-seconds>1</max-idle-seconds>
    </map>

    <map name="personMapBak1BIN*">
        <backup-count>1</backup-count>
        <in-memory-format>BINARY</in-memory-format>
        <indexes>
            <index name="a" type="SORTED">
                <attributes>
                    <attribute>personId</attribute>
                </attributes>
            </index>
        </indexes>
        <merkle-tree enabled="true" ></merkle-tree>
        <hot-restart enabled="true">
            <fsync>false</fsync>
        </hot-restart>
        <eviction eviction-policy="LRU" max-size-policy="USED_HEAP_PERCENTAGE" size="50"/>
        <max-idle-seconds>1</max-idle-seconds>
    </map>

    <map name="personMapBak1OBJ*">
        <backup-count>1</backup-count>
        <in-memory-format>OBJECT</in-memory-format>
        <indexes>
            <index name="a" type="SORTED">
                <attributes>
                    <attribute>personId</attribute>
                </attributes>
            </index>
        </indexes>
        <merkle-tree enabled="true" ></merkle-tree>
        <hot-restart enabled="true">
            <fsync>false</fsync>
        </hot-restart>
        <eviction eviction-policy="LRU" max-size-policy="USED_HEAP_PERCENTAGE" size="50"/>
        <max-idle-seconds>1</max-idle-seconds>
    </map>

```

**Comment by Danny-Hazelcast** [comment]
the test is making these operations:
set, remove, putTTL, get,  on HD, BIN, OBJ maps

**Comment by Danny-Hazelcast** [comment]
```
fail HzMember3HZ personMapBak1HDSetTtl hzcmd.map.PutTtlWaitGet threadId=0 java.lang.IllegalThreadStateException: Thread[hz.musing_lewin.partition-operation.thread-0,5,main] cannot make remote call: com.hazelcast.map.impl.operation.EvictBatchBackupOperation{serviceName='hz:impl:mapService', identityHash=2143596002, partitionId=10, replicaIndex=1, callId=0, invocationTime=-1 (1969-12-31 23:59:59.999), waitTimeout=-1, callTimeout=60000, tenantControl=com.hazelcast.spi.impl.tenantcontrol.NoopTenantControl@0, name=personMapBak1HD}
fail HzMember1HZ personMapBak1HDSet hzcmd.map.Set threadId=1 java.lang.IllegalThreadStateException: Thread[hz.musing_lewin.partition-operation.thread-1,5,main] cannot make remote call: com.hazelcast.map.impl.operation.EvictBatchBackupOperation{serviceName='hz:impl:mapService', identityHash=854201764, partitionId=9, replicaIndex=1, callId=0, invocationTime=-1 (1969-12-31 23:59:59.999), waitTimeout=-1, callTimeout=60000, tenantControl=com.hazelcast.spi.impl.tenantcontrol.NoopTenantControl@0, name=personMapBak1HD}
fail HzMember2HZ personMapBak1HDSetRem hzcmd.map.SetRemove threadId=0 java.lang.IllegalThreadStateException: Thread[hz.boring_clifford.partition-operation.thread-3,5,main] cannot make remote call: com.hazelcast.map.impl.operation.EvictBatchBackupOperation{serviceName='hz:impl:mapService', identityHash=536812372, partitionId=7, replicaIndex=1, callId=0, invocationTime=-1 (1969-12-31 23:59:59.999), waitTimeout=-1, callTimeout=60000, tenantControl=com.hazelcast.spi.impl.tenantcontrol.NoopTenantControl@0, name=personMapBak1HD}

```

http://jenkins.hazelcast.com/view/hot-restart/job/hot-x/54/console

/disk1/workspace/hot-x/5.0-SNAPSHOT/2021_06_21-12_34_30/persist-ru


cat ./output/HZ/HzMember1HZ/out.txt | grep starting
INFO: [10.0.0.221]:5701 [HZ] [5.0-SNAPSHOT] Hazelcast Platform Enterprise 5.0-SNAPSHOT (20210621 - 3b2b90b, 6d89281) starting at [10.0.0.221]:5701
