### ISSUE TITLE
SQL Exceptions are not as informative as other HazelcastExceptions

### ISSUE THREAD

**Issue by sancar** [hazelcast/hazelcast#18917]
When a remote exception occurs as a result of an invocation, we try to delegate that to the caller including the local stack trace happened. 

These type of informations help especially us a lot when debugging user problems. 
This an an important feature for us, and time to time it was broken due to internal changes an restored back.
You can see an example fix here:
https://github.com/hazelcast/hazelcast/pull/17546

What is missing in SQL Exceptions ? 

- [ ] We don't have any stacktrace of remote exceptions. We have only message string. It could be obvious to the implementer of that part, but it is hard for others to find the where the exception is thrown from. 
- [ ] The caller side exceptions looks like appeared out of nowhere. We can not trace it back to the users calling site. 

Example:
```
		Hazelcast.newHazelcastInstance();
        HazelcastInstance client = HazelcastClient.newHazelcastClient();
        SqlService sql = client.getSql();
        SqlResult result = sql.execute("SELECT * FROM map WHERE id == 5");
        Iterator<SqlRow> iterator = result.iterator();
```       
This throws the following exception. As you can see 
1. there is no remote(member-side) stack trace
2. and it is not clear which method of the user throws this exception. 
```
Exception in thread "main" com.hazelcast.sql.HazelcastSqlException: Cannot execute SQL query because "hazelcast-sql" module is not in the classpath.
	at com.hazelcast.sql.impl.client.SqlClientService.handleResponseError(SqlClientService.java:264)
	at com.hazelcast.sql.impl.client.SqlClientService.handleExecuteResponse(SqlClientService.java:133)
	at com.hazelcast.sql.impl.client.SqlClientService.lambda$execute$0(SqlClientService.java:111)
	at com.hazelcast.internal.util.ExceptionUtil.lambda$withTryCatch$1(ExceptionUtil.java:207)
	at com.hazelcast.client.impl.spi.impl.ClientInvocationFuture$CallIdTrackingBiConsumer.accept(ClientInvocationFuture.java:268)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$WhenCompleteNode.lambda$execute$0(AbstractInvocationFuture.java:1563)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec$$$capture(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
```

**Comment by srknzl** [comment]
Because invocation is done asynchronously in `execute`, is it possible to trace errors to the user's calling site? What is your suggestion?

**Comment by viliam-durina** [comment]
I agree this is an issue. Even if `execute` is async, it needs to be wrapped in another exception.

**Comment by sancar** [comment]
@srknzl It is possible. I am suggesting to apply the same fixes we have applied for other hazelcast exceptions. 
The fix I have shared a good example to async case. #17546
If you throw the exception to user at some point from an async operation, it should include the stacktrace of the calling side. Of course, if the exception is occurred another thread and user was not waiting for response, there is nothing to do. That is not the use-case I am trying to address.
