### ISSUE TITLE
ClientTransactionalSetSplitBrainProtectionReadTest failed

### ISSUE THREAD

**Issue by kwart** [hazelcast/hazelcast#18930]
The `com.hazelcast.client.splitbrainprotection.set.ClientTransactionalSetSplitBrainProtectionReadTest` failed on `master` branch during PR builder run http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/5637/

Build artifacts: https://console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/5637/

Stacktrace:
```
com.hazelcast.splitbrainprotection.SplitBrainProtectionException: Split brain protection exception: threeNodeSplitBrainProtectionRuleREAD has failed!
	at com.hazelcast.splitbrainprotection.impl.SplitBrainProtectionImpl.newSplitBrainProtectionException(SplitBrainProtectionImpl.java:279)
	at com.hazelcast.splitbrainprotection.impl.SplitBrainProtectionImpl.ensureNoSplitBrain(SplitBrainProtectionImpl.java:274)
	at com.hazelcast.splitbrainprotection.impl.SplitBrainProtectionImpl.ensureNoSplitBrain(SplitBrainProtectionImpl.java:269)
	at com.hazelcast.splitbrainprotection.impl.SplitBrainProtectionServiceImpl.ensureNoSplitBrain(SplitBrainProtectionServiceImpl.java:232)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.ensureNoSplitBrain(OperationRunnerImpl.java:338)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:243)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:469)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:197)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:137)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
	at ------ submitted from ------.()
	at com.hazelcast.internal.util.ExceptionUtil.cloneExceptionWithFixedAsyncStackTrace(ExceptionUtil.java:279)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.returnOrThrowWithGetConventions(InvocationFuture.java:112)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:100)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:617)
	at com.hazelcast.collection.impl.queue.QueueProxySupport.invokeAndGet(QueueProxySupport.java:179)
	at com.hazelcast.collection.impl.queue.QueueProxySupport.invokeAndGet(QueueProxySupport.java:172)
	at com.hazelcast.collection.impl.queue.QueueProxySupport.size(QueueProxySupport.java:110)
	at com.hazelcast.collection.impl.queue.QueueProxyImpl.size(QueueProxyImpl.java:43)
	at com.hazelcast.splitbrainprotection.AbstractSplitBrainProtectionTest.initCluster(AbstractSplitBrainProtectionTest.java:247)
	at com.hazelcast.splitbrainprotection.AbstractSplitBrainProtectionTest.initTestEnvironment(AbstractSplitBrainProtectionTest.java:105)
	at com.hazelcast.client.splitbrainprotection.set.ClientTransactionalSetSplitBrainProtectionReadTest.setUp(ClientTransactionalSetSplitBrainProtectionReadTest.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeLazy(JUnitCoreWrapper.java:119)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:87)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
```

**Comment by mmedenjak** [comment]
All of these seem related:
https://github.com/hazelcast/hazelcast/issues/18950
https://github.com/hazelcast/hazelcast/issues/18777
https://github.com/hazelcast/hazelcast/issues/18766
https://github.com/hazelcast/hazelcast/issues/18765
https://github.com/hazelcast/hazelcast/issues/18764
