### ISSUE TITLE
Error when enabling CDC on table with missing primary key is not helpful in diagnosing issue 

### ISSUE THREAD

**Issue by myawnhc** [hazelcast/hazelcast#18938]
https://github.com/hazelcast/hazelcast/blob/2797c7ad3cecffa673e2d6f7ae276777885ad155/extensions/cdc-debezium/src/main/java/com/hazelcast/jet/cdc/impl/ChangeRecordImpl.java#L52

When I enable CDC for a database and one of the tables doesn't have a primary key defined, I get an obscure error message that doesn't point me to the issue:

09:28:40.619 [ WARN] [c.h.j.i.e.TaskletExecutionService] Exception in ProcessorTasklet{InventoryService.CDCPipeline/invservice#0}
com.hazelcast.jet.JetException: Failed to connect to database: keyJson
	at com.hazelcast.jet.cdc.impl.CdcSourceP.reconnect(CdcSourceP.java:213)
	at com.hazelcast.jet.cdc.impl.CdcSourceP.complete(CdcSourceP.java:193)

The message makes it look like it's trying to connect to a database named 'keyJson', and that name doesn't refer to any database, table, or anything else in user code.  

Not sure how much context is available to the code at this point to craft a more useful message, but something indicating that the key being used to access the data source is null would be much more helpful, and if it was possible to name the table involved that would be even better. (In my case it was a secondary table and not the primary so I was looking in the wrong place).

**Comment by jerrinot** [comment]
it's a bad interaction between https://github.com/hazelcast/hazelcast/blob/2797c7ad3cecffa673e2d6f7ae276777885ad155/extensions/cdc-debezium/src/main/java/com/hazelcast/jet/cdc/impl/ChangeRecordImpl.java#L52 which produces NPE with "keyJson" as a message
and
https://github.com/hazelcast/hazelcast/blob/5ae4aba7250f47aa54d5725d5f917d6c5aec6b1c/extensions/cdc-debezium/src/main/java/com/hazelcast/jet/cdc/impl/CdcSourceP.java#L213
which takes a just message from an exception and appends it to "Failed to connect to database:"

**Comment by Holmistr** [comment]
The CDC integration will require more work. This should be taken as part of it. Moving it to 5.2.
