### ISSUE TITLE
Unable to use digits-only String values in the YAML config

### ISSUE THREAD

**Issue by kwart** [hazelcast/hazelcast#18939]
YAML schema validation doesn't handle properly String values containing only digits (in `5.0-SNAPSHOT`).

Reproducer:
```yaml
hazelcast:
  cluster-name: '1234'
```

**Fails with the following stacktrace:**
```expected type: String, found: Integer
  instance location: #/hazelcast/cluster-name
  keyword location: #/properties/hazelcast/properties/cluster-name

	at com.hazelcast.internal.config.YamlConfigSchemaValidator.wrap(YamlConfigSchemaValidator.java:55)
	at com.hazelcast.internal.config.YamlConfigSchemaValidator.validate(YamlConfigSchemaValidator.java:82)
	at com.hazelcast.config.YamlConfigBuilder.parseAndBuildConfig(YamlConfigBuilder.java:163)
	at com.hazelcast.config.YamlConfigBuilder.build(YamlConfigBuilder.java:134)
	at com.hazelcast.config.YamlConfigBuilder.build(YamlConfigBuilder.java:127)
	at com.hazelcast.config.YamlConfigBuilderTest.buildConfig(YamlConfigBuilderTest.java:1825)
	at com.hazelcast.config.YamlConfigBuilderTest.testClusterName(YamlConfigBuilderTest.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by kwart** [comment]
@erosb Could you have a look, it seems as a problem on the validator side.

**Comment by kwart** [comment]
Similar problem with other type(s):

```yaml
hazelcast:
  cluster-name: 'true'
```
