### ISSUE TITLE
'Can't assign requested address' exception

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast#18941]
Using 5.0-SNAPSHOT (`20210621 - d8ee81f`)

If I run `Hazelcast.newHazelcastInstance();`

I get 

```
INFO: [...]:5701 [dev] [5.0-SNAPSHOT] No discovery strategy is applicable for auto-detection
Jun 21, 2021 9:26:07 AM com.hazelcast.instance.impl.Node
SEVERE: [...]:5701 [dev] [5.0-SNAPSHOT] Can't assign requested address
java.net.SocketException: Can't assign requested address
	at java.net.PlainDatagramSocketImpl.join(Native Method)
	at java.net.AbstractPlainDatagramSocketImpl.join(AbstractPlainDatagramSocketImpl.java:178)
	at java.net.MulticastSocket.joinGroup(MulticastSocket.java:323)
	at com.hazelcast.internal.cluster.impl.MulticastService.configureMulticastSocket(MulticastService.java:169)
	at com.hazelcast.internal.cluster.impl.MulticastService.createMulticastService(MulticastService.java:114)
	at com.hazelcast.instance.impl.Node.<init>(Node.java:274)
	at com.hazelcast.instance.impl.HazelcastInstanceImpl.createNode(HazelcastInstanceImpl.java:149)
	at com.hazelcast.instance.impl.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:118)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:211)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:190)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:128)
	at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:95)
```

**Comment by neilstevenson** [comment]
This doesn't occur with 4.2

**Comment by neilstevenson** [comment]
Occurs with JDK 8 and 5.0-SNAPHOT, but not with JDK 11 or 4.2

**Comment by mmedenjak** [comment]
@vbekiaris nailed it down to recent changes in 5.0 - https://hazelcast.slack.com/archives/C034YQBTG/p1624345987229400?thread_ts=1624264124.217600&cid=C034YQBTG

**Comment by mmedenjak** [comment]
Closing this in favour of https://github.com/hazelcast/hazelcast/issues/19192, which has more logs and info and is basically the same issue.
