### ISSUE TITLE
SQL exception with maven-assembly-plugin : "No DataSerializerFactory registered for namespace:"

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast#18959]
Using only `com.hazelcast:hazelcast:5.0-SNAPSHOT` and `com.hazelcast:hazelcast-sql:5.0-SNAPSHOT`

I get an SQL exception from the following code:

```
    public static void main(String[] args) throws Exception {
    	HazelcastInstance hazelcastInstance = Hazelcast.newHazelcastInstance();		
    	String MAPPING = "CREATE MAPPING m TYPE IMap  OPTIONS ("
    			+ "'keyFormat' = 'java', 'keyJavaClass' = 'java.lang.String', "
    			+ "'valueFormat' = 'java', 'valueJavaClass' = 'java.lang.String' )";
    	hazelcastInstance.getSql().execute(MAPPING);
	hazelcastInstance.shutdown();
    }
``` 

If packaged using 
```
			<plugin>
				<artifactId>maven-assembly-plugin</artifactId>
				<version>3.3.0</version>
				<configuration>
					<archive>
						<manifest>
							<mainClass>neil.Application</mainClass>
						</manifest>
					</archive>
					<descriptorRefs>
						<descriptorRef>jar-with-dependencies</descriptorRef>
					</descriptorRefs>
				</configuration>
				<executions>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>single</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
```

And run with `java -jar` I get this exception:
```
Exception in thread "main" com.hazelcast.sql.HazelcastSqlException: No DataSerializerFactory registered for namespace: -41
	at com.hazelcast.sql.impl.QueryUtils.toPublicException(QueryUtils.java:78)
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:233)
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:199)
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:195)
	at com.hazelcast.sql.SqlService.execute(SqlService.java:146)
	at neil.Application.main(Application.java:15)
Caused by: com.hazelcast.nio.serialization.HazelcastSerializationException: No DataSerializerFactory registered for namespace: -41
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.readInternal(DataSerializableSerializer.java:139)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:106)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:51)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:44)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:208)
	at com.hazelcast.spi.impl.NodeEngineImpl.toObject(NodeEngineImpl.java:378)
	at com.hazelcast.replicatedmap.impl.record.ObjectReplicatedRecordStorage.marshall(ObjectReplicatedRecordStorage.java:41)
	at com.hazelcast.replicatedmap.impl.record.AbstractReplicatedRecordStore.put(AbstractReplicatedRecordStore.java:174)
	at com.hazelcast.replicatedmap.impl.record.AbstractReplicatedRecordStore.put(AbstractReplicatedRecordStore.java:149)
	at com.hazelcast.replicatedmap.impl.operation.PutOperation.run(PutOperation.java:63)
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:189)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:272)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:248)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:213)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:175)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:139)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
	at ------ submitted from ------.()
	at com.hazelcast.internal.util.ExceptionUtil.cloneExceptionWithFixedAsyncStackTrace(ExceptionUtil.java:279)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.wrapRuntimeException(AbstractInvocationFuture.java:1968)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.wrapOrPeel(AbstractInvocationFuture.java:1949)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$ExceptionalResult.wrapForJoinInternal(AbstractInvocationFuture.java:1431)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.resolveAndThrowForJoinInternal(AbstractInvocationFuture.java:600)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.joinInternal(AbstractInvocationFuture.java:584)
	at com.hazelcast.replicatedmap.impl.ReplicatedMapProxy.put(ReplicatedMapProxy.java:273)
	at java.base/java.util.Map.putIfAbsent(Map.java:775)
	at com.hazelcast.jet.sql.impl.schema.MappingStorage.putIfAbsent(MappingStorage.java:63)
	at com.hazelcast.jet.sql.impl.schema.MappingCatalog.createMapping(MappingCatalog.java:99)
	at com.hazelcast.jet.sql.impl.JetPlanExecutor.execute(JetPlanExecutor.java:77)
	at com.hazelcast.jet.sql.impl.JetPlan$CreateMappingPlan.execute(JetPlan.java:104)
	at com.hazelcast.jet.sql.impl.JetSqlCoreBackendImpl.execute(JetSqlCoreBackendImpl.java:88)
	at com.hazelcast.sql.impl.SqlServiceImpl.executeJet(SqlServiceImpl.java:342)
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:331)
	at com.hazelcast.sql.impl.SqlServiceImpl.query0(SqlServiceImpl.java:274)
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:220)
	... 4 more
```

Doesn't occur with `java -cp`

**Comment by viliam-durina** [comment]
-41 is for `JetSqlSerializerHook`. Looks like `hazelcast-sql/src/main/resources/META-INF/services/com.hazelcast.DataSerializerHook` is not properly placed...

**Comment by gierlachg** [comment]
Most probably SQL `com.hazelcast.DataSerializerHook` is overridden by top HZ one while assembling the target jar.
