### ISSUE TITLE
com.hazelcast.client.splitbrainprotection.queue.ClientQueueSplitBrainProtectionWriteTest.remove_splitBrainProtection

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#18950]
_4.2.z_ (commit b80b074928b3cd452b166d8cf69cc5813120f32f)

Failed on Zulu JDK 11: http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-4.maintenance-ZuluJDK11/5/testReport/com.hazelcast.client.splitbrainprotection.queue/ClientQueueSplitBrainProtectionWriteTest/remove_splitBrainProtection_splitBrainProtectionType_READ_WRITE_/

It failed with option `[splitBrainProtectionType:READ_WRITE]`.

Stacktrace:
```
java.util.NoSuchElementException: Queue is empty!
	at com.hazelcast.client.impl.proxy.ClientQueueProxy.remove(ClientQueueProxy.java:266)
	at com.hazelcast.splitbrainprotection.queue.QueueSplitBrainProtectionWriteTest.remove_splitBrainProtection(QueueSplitBrainProtectionWriteTest.java:112)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Standard output:
```
Started Running Test: remove_splitBrainProtection[splitBrainProtectionType:READ_WRITE]
22:21:27,907  INFO || - [InternalPartitionService] hz.vibrant_panini.migration - [127.0.0.1]:5704 [naesadsuvj] [4.2.1-SNAPSHOT] Fetching partition tables from cluster to determine the most recent one... Local stamp: -7939033747391728028
22:21:27,909  INFO || - [InternalPartitionService] hz.vibrant_panini.migration - [127.0.0.1]:5704 [naesadsuvj] [4.2.1-SNAPSHOT] Most recent partition table is determined.
22:21:27,909  INFO || - [InternalPartitionService] hz.vibrant_panini.migration - [127.0.0.1]:5704 [naesadsuvj] [4.2.1-SNAPSHOT] Applying the most recent of partition state...
22:21:27,909  WARN || - [InternalPartitionService] hz.vibrant_panini.migration - [127.0.0.1]:5704 [naesadsuvj] [4.2.1-SNAPSHOT] Following unknown addresses are found in partition table sent from master[[127.0.0.1]:5704]. (Probably they have recently joined or left the cluster.) {
	[127.0.0.1]:5702 - e000bb9c-932e-47a0-b300-7e3580741193
	[127.0.0.1]:5701 - a4d7ad68-4ea0-4069-8ade-b09b59fea57b
	[127.0.0.1]:5703 - 981ac892-3b57-4690-9237-29717ee0d801
}
22:21:27,910  WARN || - [InternalPartitionService] hz.sharp_panini.priority-generic-operation.thread-0 - [127.0.0.1]:5705 [naesadsuvj] [4.2.1-SNAPSHOT] Following unknown addresses are found in partition table sent from master[[127.0.0.1]:5704]. (Probably they have recently joined or left the cluster.) {
	[127.0.0.1]:5702 - e000bb9c-932e-47a0-b300-7e3580741193
	[127.0.0.1]:5701 - a4d7ad68-4ea0-4069-8ade-b09b59fea57b
	[127.0.0.1]:5703 - 981ac892-3b57-4690-9237-29717ee0d801
}
22:21:27,913  INFO || - [MigrationManager] hz.vibrant_panini.migration - [127.0.0.1]:5704 [naesadsuvj] [4.2.1-SNAPSHOT] Repartitioning cluster data. Migration tasks count: 10
BuildInfo right after remove_splitBrainProtection[splitBrainProtectionType:READ_WRITE](com.hazelcast.client.splitbrainprotection.queue.ClientQueueSplitBrainProtectionWriteTest): BuildInfo{version='4.2.1-SNAPSHOT', build='20210621', buildNumber=20210621, revision=b80b074, enterprise=false, serializationVersion=1}
22:21:27,929  INFO || - [MigrationManager] hz.vibrant_panini.migration - [127.0.0.1]:5704 [naesadsuvj] [4.2.1-SNAPSHOT] All migration tasks have been completed. (repartitionTime=Mon Jun 21 22:21:27 UTC 2021, plannedMigrations=10, completedMigrations=10, remainingMigrations=0, totalCompletedMigrations=10, elapsedMigrationOperationTime=128ms, totalElapsedMigrationOperationTime=128ms, elapsedDestinationCommitTime=1ms, totalElapsedDestinationCommitTime=1ms, elapsedMigrationTime=130ms, totalElapsedMigrationTime=130ms)
Hiccups measured while running test 'remove_splitBrainProtection[splitBrainProtectionType:READ_WRITE](com.hazelcast.client.splitbrainprotection.queue.ClientQueueSplitBrainProtectionWriteTest):'
22:21:25, accumulated pauses: 734 ms, max pause: 718 ms, pauses over 1000 ms: 0
```

**Comment by sancar** [comment]
Moving to 5.0 to check in stabilization period.

**Comment by mmedenjak** [comment]
All of these seem related:
https://github.com/hazelcast/hazelcast/issues/18950
https://github.com/hazelcast/hazelcast/issues/18777
https://github.com/hazelcast/hazelcast/issues/18766
https://github.com/hazelcast/hazelcast/issues/18765
https://github.com/hazelcast/hazelcast/issues/18764

**Comment by mmedenjak** [comment]
Also this - https://github.com/hazelcast/hazelcast/issues/18930
