### ISSUE TITLE
Deploying User Code on the Member cannot work under custom Serialization

### ISSUE THREAD

**Issue by wubumihuo** [hazelcast/hazelcast#18997]
My hazelcast cluster version is 4.2, and cluster has 3 instance.
**Describe the bug**
I have configed the Deploying User Code on the Member, that is：

**Expected behavior**

**To Reproduce**

3. ...

**Additional context**

**Comment by mmedenjak** [comment]
@wubumihuo thank you for the report. @asimarslan @sancar can you take a look and comment on why this is so?

**Comment by sancar** [comment]
@wubumihuo Can you share the full stacktrace of `ClassDefNotFound` ?
Specifically, in which operation you are getting the `ClassDefNotFound` error ? 
Is it map.put/get , or map.values(Predicate) ?

Are you using clients ? Are all your instance Members ?

**Comment by wubumihuo** [comment]
> Are all your instance Members ?

Ths for answer very much,now I give the full detail of my error. 
(1) I have a cluster with three point, and the cluster in-memory-format is binary.  only point 1 user-lib has my custom jar
I use hazelcast-client to put/query.  My java client config contains :
` SerializerConfig sc = (new SerializerConfig()).setImplementation(new BaseBOByteArraySerializer()).setTypeClass(BaseBO.class);
        clientConfig.getSerializationConfig().addSerializerConfig(sc);` 
It keeps same as the cluster. When I instance.put(key,RDSBondBO), it works.  But when user addIndex or map.values(Predicate),it may deserialize in cluster, the error happened . 
  
 
(2)the full stacktrace:
Caused by: com.hazelcast.nio.serialization.HazelcastSerializationException: com.esotericsoftware.kryo.KryoException: Unable to find class: com.*.nats.model.rds.instrument.RDSBondBO
	at com.hazelcast.internal.serialization.impl.SerializationUtil.handleException(SerializationUtil.java:103)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:214)
	at com.hazelcast.map.impl.record.Records.tryStoreIntoCache(Records.java:203)
	at com.hazelcast.map.impl.record.Records.getValueOrCachedValue(Records.java:170)
	at com.hazelcast.map.impl.operation.AddIndexOperation.lambda$runInternal$0(AddIndexOperation.java:102)
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.forEach(DefaultRecordStore.java:278)
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.forEach(DefaultRecordStore.java:261)
	at com.hazelcast.map.impl.operation.AddIndexOperation.runInternal(AddIndexOperation.java:101)
	at com.hazelcast.map.impl.operation.MapOperation.run(MapOperation.java:115)
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:189)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:272)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:248)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:213)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:175)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:139)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
	at ------ submitted from ------.()
	at com.hazelcast.internal.util.ExceptionUtil.cloneExceptionWithFixedAsyncStackTrace(ExceptionUtil.java:279)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.returnOrThrowWithGetConventions(InvocationFuture.java:112)
	at com.hazelcast.client.impl.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:95)
	at com.hazelcast.client.impl.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:40)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:617)
	at com.hazelcast.client.impl.spi.ClientProxy.invoke(ClientProxy.java:215)
	at com.hazelcast.client.impl.proxy.ClientMapProxy.addIndex(ClientMapProxy.java:1329)
	at com.*.nats.datahub.bopub.hazelcast.HazelcastPerformance.insertData(HazelcastPerformance.java:135)
	... 5 common frames omitted
Caused by: com.esotericsoftware.kryo.KryoException: Unable to find class: com.*.nats.model.rds.instrument.RDSBondBO
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readName(DefaultClassResolver.java:160)
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:133)
	at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:693)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:804)
	at com.*.nats.model.BaseBOByteArraySerializer.read(BaseBOByteArraySerializer.java:79)
	at com.*.nats.model.BaseBOByteArraySerializer.read(BaseBOByteArraySerializer.java:19)
	at com.hazelcast.internal.serialization.impl.ByteArraySerializerAdapter.read(ByteArraySerializerAdapter.java:49)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:208)
	at com.hazelcast.map.impl.record.Records.tryStoreIntoCache(Records.java:203)
	at com.hazelcast.map.impl.record.Records.getValueOrCachedValue(Records.java:170)
	at com.hazelcast.map.impl.operation.AddIndexOperation.lambda$runInternal$0(AddIndexOperation.java:102)
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.forEach(DefaultRecordStore.java:278)
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.forEach(DefaultRecordStore.java:261)
	at com.hazelcast.map.impl.operation.AddIndexOperation.runInternal(AddIndexOperation.java:101)
	at com.hazelcast.map.impl.operation.MapOperation.run(MapOperation.java:115)
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:189)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:272)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:248)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:213)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:175)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:139)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
Caused by: java.lang.ClassNotFoundException: com.*.nats.model.rds.instrument.RDSBondBO
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readName(DefaultClassResolver.java:154)
	... 22 common frames omitted

**Comment by sancar** [comment]
@wubumihuo 
Map.put/get does not require classes available on the server when in memory format is binary
,but addIndex requires the classes on the server.
So it feels like you haven't deployed your classes (like RDSBondBO) to the cluster from the client.
You need to use user code deployment config from the client. The client requires manual registration of classes as opposed to members. See:
https://docs.hazelcast.com/imdg/4.2/clusters/deploying-code-from-clients.html

Do you have these configs on your clientConfig or client.xml?
