### ISSUE TITLE
SQL Date sent as string does not work

### ISSUE THREAD

**Issue by srknzl** [hazelcast/hazelcast#19019]
**Describe the bug**
Seems like string to date conversion is problematic

**Expected behavior**
Expect it to work

**To Reproduce**

```java
import com.hazelcast.client.config.ClientConfig;
import com.hazelcast.client.HazelcastClient;
import com.hazelcast.core.HazelcastInstance;
import com.hazelcast.map.IMap;
import com.hazelcast.sql.SqlResult;
import com.hazelcast.sql.SqlRow;

import java.time.LocalDate;

public class Main {
    public static void main(String[] args) {
        ClientConfig c = new ClientConfig();
        HazelcastInstance h = HazelcastClient.newHazelcastClient(c);
        IMap<Integer, LocalDate> m = h.getMap("a");
        for (int key = 1; key < 12; key++) {
            m.put(key, LocalDate.of(key + 2, key + 1, key));
        }


        try (SqlResult result = h.getSql().execute("SELECT * FROM a WHERE this > CAST(? AS DATE) AND this < CAST(? AS DATE)", "0001-01-01", "0005-05-05");) {
            for (SqlRow row : result) {
                System.out.println(row);
            }
        }
    }
}

```
**Additional context**

Hazelcast version: 5.0 SNAPSHOT (via docker)
Hazelcast client version: 4.2.1

Stacktrace:
```
java.time.DateTimeException: Invalid value for MonthOfYear (valid values 1 - 12): 0
	at java.time.temporal.ValueRange.checkValidValue(ValueRange.java:311)
	at java.time.temporal.ChronoField.checkValidValue(ChronoField.java:703)
	at java.time.LocalDate.of(LocalDate.java:267)
	at com.hazelcast.client.impl.protocol.codec.builtin.FixedSizeTypesCodec.decodeLocalDate(FixedSizeTypesCodec.java:195)
	at com.hazelcast.client.impl.protocol.codec.builtin.ListCNFixedSizeCodec.decode(ListCNFixedSizeCodec.java:135)
	at com.hazelcast.client.impl.protocol.codec.builtin.ListCNLocalDateCodec.decode(ListCNLocalDateCodec.java:40)
	at com.hazelcast.client.impl.protocol.codec.builtin.ListCNLocalDateCodec.decode(ListCNLocalDateCodec.java:36)
	at com.hazelcast.client.impl.protocol.codec.builtin.SqlPageCodec.decode(SqlPageCodec.java:221)
	at com.hazelcast.client.impl.protocol.codec.builtin.CodecUtil.decodeNullable(CodecUtil.java:55)
	at com.hazelcast.client.impl.protocol.codec.SqlExecuteCodec.decodeResponse(SqlExecuteCodec.java:171)
	at com.hazelcast.sql.impl.client.SqlClientService.handleExecuteResponse(SqlClientService.java:131)
	at com.hazelcast.sql.impl.client.SqlClientService.lambda$execute$0(SqlClientService.java:111)
	at com.hazelcast.internal.util.ExceptionUtil.lambda$withTryCatch$1(ExceptionUtil.java:207)
	at com.hazelcast.client.impl.spi.impl.ClientInvocationFuture$CallIdTrackingBiConsumer.accept(ClientInvocationFuture.java:268)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$WhenCompleteNode.lambda$execute$0(AbstractInvocationFuture.java:1563)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)


```

Note: It works with 5.0-SNAPSHOT client

**Comment by srknzl** [comment]
Related to https://github.com/hazelcast/hazelcast/pull/18984 so this is expected, not a bug
