### ISSUE TITLE
NPE for invalid client Yaml

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast#19039]
With 5.0-SNAPSHOT (20210712) if I do

```
new YamlClientConfigBuilder("application.yml").build();
```

And the YAML file contains no `hazelcast-client:` ssection I get an NPE instead of a helpful diagnostic

```
Caused by: java.lang.NullPointerException
	at com.hazelcast.internal.config.YamlConfigSchemaValidator.lambda$validate$0(YamlConfigSchemaValidator.java:72) ~[hazelcast-enterprise-5.0-SNAPSHOT.jar!/:5.0-SNAPSHOT]
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:?]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.ReduceOps$5.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.ReduceOps$5.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.count(Unknown Source) ~[?:?]
	at com.hazelcast.internal.config.YamlConfigSchemaValidator.validate(YamlConfigSchemaValidator.java:73) ~[hazelcast-enterprise-5.0-SNAPSHOT.jar!/:5.0-SNAPSHOT]
	at com.hazelcast.client.config.YamlClientConfigBuilder.parseAndBuildConfig(YamlClientConfigBuilder.java:160) ~[hazelcast-enterprise-5.0-SNAPSHOT.jar!/:5.0-SNAPSHOT]
	at com.hazelcast.client.config.YamlClientConfigBuilder.build(YamlClientConfigBuilder.java:132) ~[hazelcast-enterprise-5.0-SNAPSHOT.jar!/:5.0-SNAPSHOT]
	at com.hazelcast.client.config.YamlClientConfigBuilder.build(YamlClientConfigBuilder.java:120) ~[hazelcast-enterprise-5.0-SNAPSHOT.jar!/:5.0-SNAPSHOT]
	at com.hazelcast.client.config.YamlClientConfigBuilder.build(YamlClientConfigBuilder.java:115) ~[hazelcast-enterprise-5.0-SNAPSHOT.jar!/:5.0-SNAPSHOT]
```

**Comment by fbarotov** [comment]
Can you please share content of the `application.yaml` you used? I tried the following and it does not throw an NPE

     @Test
    public void clientConfigTest() {
        try {
            File clientConfigFile = File.createTempFile("application", ".yml");
            clientConfigFile.deleteOnExit();
            ClientConfig clientConfig = new YamlClientConfigBuilder(clientConfigFile).build();

            PrintWriter printWriter = new PrintWriter(clientConfigFile);
            printWriter.println("hazelcast-client: ");
            printWriter.flush();

            clientConfig = new YamlClientConfigBuilder(clientConfigFile).build();
        } catch (IOException | InvalidConfigurationException ignored) {

        }
    }

**Comment by neilstevenson** [comment]
Try
```
server.port: 0
```

**Comment by fbarotov** [comment]
Tried the following 

    @Test
    public void clientConfigTest() {
        try {
            File clientConfigFile = File.createTempFile("application", ".yml");
            clientConfigFile.deleteOnExit();
            ClientConfig clientConfig = new YamlClientConfigBuilder(clientConfigFile).build();

            PrintWriter printWriter = new PrintWriter(clientConfigFile);
            printWriter.println("server.port: 0");
            printWriter.flush();

            assertEquals("server.port: 0", new Scanner(clientConfigFile).next());

            clientConfig = new YamlClientConfigBuilder(clientConfigFile).build();
        } catch (IOException | InvalidConfigurationException ignored) {

        }
    }

Does not throw NPE.

**Comment by neilstevenson** [comment]
That's odd.
This fails for me
```
    public static void main(String[] args) throws Exception {
    	new YamlClientConfigBuilder("application.yml").build();
    }
```
with `src/main/resources/application.yml` 

Verified today, 5.0-SNAPSHOT and Java 11.

```
Exception in thread "main" java.lang.NullPointerException
	at com.hazelcast.internal.config.YamlConfigSchemaValidator.lambda$validate$0(YamlConfigSchemaValidator.java:72)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.ReduceOps$5.evaluateSequential(ReduceOps.java:257)
	at java.base/java.util.stream.ReduceOps$5.evaluateSequential(ReduceOps.java:248)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.count(ReferencePipeline.java:605)
	at com.hazelcast.internal.config.YamlConfigSchemaValidator.validate(YamlConfigSchemaValidator.java:73)
	at com.hazelcast.client.config.YamlClientConfigBuilder.parseAndBuildConfig(YamlClientConfigBuilder.java:160)
	at com.hazelcast.client.config.YamlClientConfigBuilder.build(YamlClientConfigBuilder.java:132)
	at com.hazelcast.client.config.YamlClientConfigBuilder.build(YamlClientConfigBuilder.java:120)
	at com.hazelcast.client.config.YamlClientConfigBuilder.build(YamlClientConfigBuilder.java:115)
	at neil.Application.main(Application.java:10)
```
