### ISSUE TITLE
java.lang.IllegalArgumentException: Size must be positive: -1005578636

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#19045]
/disk1/workspace/split-all/5.0-SNAPSHOT/2021_07_09-14_34_02/stable/persist

```
java.lang.IllegalArgumentException: Size must be positive: -1005578636
	at com.hazelcast.internal.memory.AbstractPoolingMemoryManager.getAddressQueue(AbstractPoolingMemoryManager.java:175)
	at com.hazelcast.internal.memory.AbstractPoolingMemoryManager.allocate(AbstractPoolingMemoryManager.java:57)
	at com.hazelcast.internal.monitor.impl.HDGlobalPerIndexStats$MemoryAllocatorWithStats.allocate(HDGlobalPerIndexStats.java:70)
	at com.hazelcast.internal.bplustree.DefaultBPlusTreeKeyAccessor.cloneNativeMemory(DefaultBPlusTreeKeyAccessor.java:81)
	at com.hazelcast.internal.bplustree.HDBTreeInnerNodeAccessor.clonedEntryKeyAddr(HDBTreeInnerNodeAccessor.java:238)
	at com.hazelcast.internal.bplustree.HDBPlusTree.splitLockedLeafWithParentLocked(HDBPlusTree.java:496)
	at com.hazelcast.internal.bplustree.HDBPlusTree.splitLockedNodeWithParentLocked(HDBPlusTree.java:446)
	at com.hazelcast.internal.bplustree.HDBPlusTree.insert(HDBPlusTree.java:344)
	at com.hazelcast.internal.bplustree.HDBPlusTree.insert(HDBPlusTree.java:296)
	at com.hazelcast.query.impl.HDBPlusTreeIndex.put(HDBPlusTreeIndex.java:42)
	at com.hazelcast.query.impl.HDBaseConcurrentIndexStore.mapAttributeToEntry(HDBaseConcurrentIndexStore.java:126)
	at com.hazelcast.query.impl.HDBaseConcurrentIndexStore.insertInternal(HDBaseConcurrentIndexStore.java:64)
	at com.hazelcast.query.impl.BaseSingleValueIndexStore.unwrapAndInsertToIndex(BaseSingleValueIndexStore.java:130)
	at com.hazelcast.query.impl.BaseSingleValueIndexStore.insert(BaseSingleValueIndexStore.java:86)
	at com.hazelcast.query.impl.AbstractIndex.putEntry(AbstractIndex.java:131)
	at com.hazelcast.query.impl.Indexes.putEntry(Indexes.java:354)
	at com.hazelcast.query.impl.Indexes.putEntry(Indexes.java:307)
	at com.hazelcast.map.impl.recordstore.IndexingMutationObserver.saveIndex(IndexingMutationObserver.java:170)
	at com.hazelcast.map.impl.recordstore.IndexingMutationObserver.onPutRecord(IndexingMutationObserver.java:52)
```

./output/HZ/HzMember3HZBB/hs_err_pid18522.log
./output/HZ/HzMember2HZAA/hs_err_pid31686.log
./output/HZ/HzMember5HZBB/hs_err_pid17715.log
./output/HZ/HzMember4HZBB/hs_err_pid17862.log
./output/HZ/HzMember1HZAA/hs_err_pid535.log

**Comment by Danny-Hazelcast** [comment]
http://jenkins.hazelcast.com/view/split/job/split-x/48/console

**Comment by Danny-Hazelcast** [comment]
```
(base) [ec2-user@ip-10-0-0-189 persist]$ more output/HZ/HzMember1HZAA/hs_err_pid2054.log
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000ffff78942268, pid=2054, tid=2101
#
# JRE version: OpenJDK Runtime Environment Corretto-11.0.9.11.1 (11.0.9+11) (build 11.0.9+11-LTS)
# Java VM: OpenJDK 64-Bit Server VM Corretto-11.0.9.11.1 (11.0.9+11-LTS, mixed mode, tiered, compressed oops, g1 gc, linux-aarch64)
# Problematic frame:
# v  ~StubRoutines::forward_copy_longs
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
#

---------------  S U M M A R Y ------------

Command Line: -DMQIP=3.87.100.12 -DQ=/disk1/workspace/split-x/5.0-SNAPSHOT/2021_07_12-12_04_09/persist/HzMember1HZAA -DID=HzMember1HZAA -DVENDOR_LIB=/home/ec2-user/hz-root/hz-lib/5.0-SNAPSHOT -XX:+HeapDum
pOnOutOfMemoryError -XX:HeapDumpPath=HzMember1HZAA.hprof -XX:OnOutOfMemoryError= date >> HzMember1HZAA.oome -Xlog:gc*,gc+ref=debug,gc+heap=debug,gc+age=trace:file=verbosegc.log:tags,uptime,time,level:file
count=1,filesize=900m --add-modules=java.se --add-exports=java.base/jdk.internal.ref=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.bas
e/sun.nio.ch=ALL-UNNAMED --add-opens=java.management/sun.management=ALL-UNNAMED --add-opens=jdk.management/com.ibm.lang.management.internal=ALL-UNNAMED --add-opens=jdk.management/com.sun.management.intern
al=ALL-UNNAMED -Xms2G -Xmx2G -Dhazelcast.enterprise.license.key=HazelcastEnterpriseHD#9999Nodes#RiUHNE1lOrwITY7F5K3VAm539qt3h099W999C99999xn999PsQ1Pv19q39h0 -Dhazelcast.diagnostics.enabled=true -Dhazelcas
t.diagnostics.metric.level=DEBUG -Dhazelcast.slow.operation.detector.stacktrace.logging.enabled=true -Dhazelcast.slow.operation.detector.enabled=true vendor.hz.java.HzMember

Host: AArch64, 4 cores, 15G, Amazon Linux release 2 (Karoo)
Time: Mon Jul 12 12:10:34 2021 UTC elapsed time: 332.963902 seconds (0d 0h 5m 32s)

---------------  T H R E A D  ---------------

Current thread (0x0000ffff913db800):  JavaThread "hz.eloquent_mayer.partition-operation.thread-2" [_thread_in_Java, id=2101, stack(0x0000fffeefc00000,0x0000fffeefe00000)]

Stack: [0x0000fffeefc00000,0x0000fffeefe00000],  sp=0x0000fffeefdfd870,  free space=2038k
Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
v  ~StubRoutines::forward_copy_longs


siginfo: si_signo: 11 (SIGSEGV), si_code: 2 (SEGV_ACCERR), si_addr: 0x0000ffff228d4000

Register to memory mapping:

R0=0x0000ffff228d3ff0
R1=0x0000fffeaf336048
R2=0x0000000000020000
R3=0x0000000000000000
R4=0x0000000000000000
R5=0x0000000000000000
R6=0x0000000000000000
R7=0x0000000000000000
R8=0xffffffff8ca62098
R9=0x000000000000cbe8
R10=0x0000000000000000
R11=0x0000000000000000
R12=0x0000000000000000
R13=0x00000000200575e1
R14=0x0000000000000000
R15=0x0000ffff96b65000
R16=0x0000ffff135c49e0
R17=0x000000010001b608
R18=0x000000000000000c
R19=0x00000000f6f6db18
R20=0x00000000200575e1
R21=0x0000000020d63794
R22=0x0000000000100000
R23=0x0000000000000000
R24=0x0000fffeaf29c018
R25=0x0000ffff22839f80
R26=0x0000000000100000
R27=0x0000000000000000
R28=0x0000ffff913db800
R29=0x0000fffeefdfd870
R30=0x0000ffff789434cc


Registers:
R0 =0x0000ffff228d3ff0 points into unknown readable memory: 00 00 00 00 00 00 00 00
R1 =0x0000fffeaf336048 points into unknown readable memory: 00 00 00 00 00 00 00 00
R2 =0x0000000000020000 is an unknown value
R3 =0x0 is NULL
R4 =0x0 is NULL
R5 =0x0 is NULL
R6 =0x0 is NULL
R7 =0x0 is NULL
R8 =0xffffffff8ca62098 is an unknown value
R9 =0x000000000000cbe8 is an unknown value
R10=0x0 is NULL
R11=0x0 is NULL
R12=0x0 is NULL
R13=537228769 is a compressed pointer to class: 0x00000001002baf08
com.hazelcast.internal.memory.impl.AlignmentAwareMemoryAccessor {0x00000001002baf08}
R14=0x0 is NULL
R15=0x0000ffff96b65000 points into unknown readable memory: 00 00 00 00 00 00 00 00
R16={method} {0x0000ffff135c49e0} 'putIntVolatile' '(Ljava/lang/Object;JI)V' in 'com/hazelcast/internal/memory/ConcurrentHeapMemoryAccessor'
R17=0x000000010001b608 is a pointer to class:
java.util.concurrent.ConcurrentHashMap$Node {0x000000010001b608}
R18=0x000000000000000c is an unknown value
R19=0x00000000f6f6db18 is an oop: com.hazelcast.internal.serialization.impl.NativeMemoryData
{0x00000000f6f6db18} - klass: 'com/hazelcast/internal/serialization/impl/NativeMemoryData'
R20=537228769 is a compressed pointer to class: 0x00000001002baf08
com.hazelcast.internal.memory.impl.AlignmentAwareMemoryAccessor {0x00000001002baf08}
R21=0x0000000020d63794 is an unknown value
R22=0x0000000000100000 is an unknown value
R23=0x0 is NULL
R24=0x0000fffeaf29c018 points into unknown readable memory: b0 44 47 22 ff ff 00 00
R25=0x0000ffff22839f80 points into unknown readable memory: b0 44 47 22 ff ff 00 00
R26=0x0000000000100000 is an unknown value
R27=0x0 is NULL
R28=0x0000ffff913db800 is a thread
R29=0x0000fffeefdfd870 is pointing into the stack for thread: 0x0000ffff913db800
R30=0x0000ffff789434cc is at begin+204 in a stub
StubRoutines::arrayof_jlong_disjoint_arraycopy [0x0000ffff78943400, 0x0000ffff789434e8[ (232 bytes)
```
