### ISSUE TITLE
com.hazelcast.kubernetes.RestClientTest fails on Oracle JDK 8, Solaris

### ISSUE THREAD

**Issue by slavagithub** [hazelcast/hazelcast#19079]
master, rev. d3724067fe40cfc05192b9fe5a2fd7301fa2d282

Failed on Oracle JDK 8, Solaris, http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Solaris-OracleJDK8-without-checkstyle/17/testReport/

Reproduced for tests:
PostSuccess
GetSussess
GetFailure
GetWithHeaderSuccess

Stacktrace:
```
java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedConstructorAccessor739.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.github.tomakehurst.wiremock.jetty9.JettyHttpServerFactory.buildHttpServer(JettyHttpServerFactory.java:63)
	at com.github.tomakehurst.wiremock.WireMockServer.<init>(WireMockServer.java:76)
	at com.github.tomakehurst.wiremock.junit.WireMockRule.<init>(WireMockRule.java:43)
	at com.github.tomakehurst.wiremock.junit.WireMockRule.<init>(WireMockRule.java:39)
	at com.hazelcast.kubernetes.RestClientTest.<init>(RestClientTest.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:250)
	at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:260)
	at org.junit.runners.BlockJUnit4ClassRunner$2.runReflectiveCall(BlockJUnit4ClassRunner.java:309)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:107)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:83)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
Caused by: java.lang.IllegalStateException: No Server ALPNProcessors!
	at wiremock.org.eclipse.jetty.alpn.server.ALPNServerConnectionFactory.<init>(ALPNServerConnectionFactory.java:52)
	at com.github.tomakehurst.wiremock.jetty94.Jetty94HttpServer.createHttpsConnector(Jetty94HttpServer.java:43)
	at com.github.tomakehurst.wiremock.jetty9.JettyHttpServer.<init>(JettyHttpServer.java:91)
	at com.github.tomakehurst.wiremock.jetty94.Jetty94HttpServer.<init>(Jetty94HttpServer.java:21)
	... 47 more
	Suppressed: java.lang.UnsatisfiedLinkError: no conscrypt_openjdk_jni-sunos-sparc_64 in java.library.path
		at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1860)
		at java.lang.Runtime.loadLibrary0(Runtime.java:871)
		at java.lang.System.loadLibrary(System.java:1122)
		at org.conscrypt.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:54)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.conscrypt.NativeLibraryLoader$1.run(NativeLibraryLoader.java:297)
		at org.conscrypt.NativeLibraryLoader$1.run(NativeLibraryLoader.java:289)
		at java.security.AccessController.doPrivileged(Native Method)
		at org.conscrypt.NativeLibraryLoader.loadLibraryFromHelperClassloader(NativeLibraryLoader.java:289)
		at org.conscrypt.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:262)
		at org.conscrypt.NativeLibraryLoader.load(NativeLibraryLoader.java:162)
		at org.conscrypt.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:106)
		at org.conscrypt.NativeCryptoJni.init(NativeCryptoJni.java:50)
		at org.conscrypt.NativeCrypto.<clinit>(NativeCrypto.java:63)
		at org.conscrypt.OpenSSLProvider.<init>(OpenSSLProvider.java:58)
		at org.conscrypt.OpenSSLProvider.<init>(OpenSSLProvider.java:51)
		at org.conscrypt.OpenSSLProvider.<init>(OpenSSLProvider.java:47)
		at wiremock.org.eclipse.jetty.alpn.conscrypt.server.ConscryptServerALPNProcessor.init(ConscryptServerALPNProcessor.java:46)
		at wiremock.org.eclipse.jetty.alpn.server.ALPNServerConnectionFactory.<init>(ALPNServerConnectionFactory.java:72)
		... 50 more
		Suppressed: java.lang.UnsatisfiedLinkError: no conscrypt_openjdk_jni-sunos-sparc_64 in java.library.path
			at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1860)
			at java.lang.Runtime.loadLibrary0(Runtime.java:871)
			at java.lang.System.loadLibrary(System.java:1122)
			at org.conscrypt.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:54)
			at org.conscrypt.NativeLibraryLoader.loadLibraryFromCurrentClassloader(NativeLibraryLoader.java:318)
			at org.conscrypt.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:273)
			... 59 more
		Suppressed: java.lang.UnsatisfiedLinkError: no conscrypt_openjdk_jni in java.library.path
			... 72 more
		Suppressed: java.lang.UnsatisfiedLinkError: no conscrypt_openjdk_jni in java.library.path
			at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1860)
			at java.lang.Runtime.loadLibrary0(Runtime.java:871)
			at java.lang.System.loadLibrary(System.java:1122)
			at org.conscrypt.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:54)
			at org.conscrypt.NativeLibraryLoader.loadLibraryFromCurrentClassloader(NativeLibraryLoader.java:318)
			at org.conscrypt.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:273)
			... 59 more
		Suppressed: java.lang.UnsatisfiedLinkError: no conscrypt in java.library.path
			... 72 more
		Suppressed: java.lang.UnsatisfiedLinkError: no conscrypt in java.library.path
			at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1860)
			at java.lang.Runtime.loadLibrary0(Runtime.java:871)
			at java.lang.System.loadLibrary(System.java:1122)
			at org.conscrypt.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:54)
			at org.conscrypt.NativeLibraryLoader.loadLibraryFromCurrentClassloader(NativeLibraryLoader.java:318)
			at org.conscrypt.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:273)
			... 59 more
```

Standard output:
```
no std
```

**Comment by olukas** [comment]
Solaris is supported on a one-off, best effort, case-by-case basis => closing this test failure.
