### ISSUE TITLE
SEVERE: HazelcastSerializationException: Problem while reading IdentifiedDataSerializable, namespace: -18, classId: 6, exception: null

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#19086]
http://jenkins.hazelcast.com/view/rollup/job/rollup-x2/8/console

/disk1/workspace/rollup-x2/5.0-SNAPSHOT/2021_07_14-10_56_13/projection Failed

fail HzClient5HZ _idx-heavy_sql_queryTargetTxnId_mapBak1HDSqlIdx hzcmd.map.sql.predicate.txn.model.queryTargetTxnId threadId=7 global.AssertionException: map mapBak1HDSqlIdx_sql_idx-heavy key=5411 value==null 

```
SEVERE: [10.0.0.76]:5701 [HZ] [4.2] Failed to process: Packet{partitionId=23, frameLength=53229, conn=Connection[id=14, /10.0.0.76:5701->/10.0.0.42:38173, qualifier=null, endpoint=[10.0.0.42]:5701, alive=true, connectionType=MEMBER, planeIndex=0], rawFlags=10010001, isUrgent=true, packetType=OPERATION, typeSpecificFlags=[isResponse=false, isOpControl=false]} on: hz.affectionate_rubin.partition-operation.thread-3
com.hazelcast.nio.serialization.HazelcastSerializationException: Problem while reading IdentifiedDataSerializable, namespace: -18, classId: 6, exception: null
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.rethrowIdsReadException(EnterpriseDataSerializableSerializer.java:315)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.readIdentifiedDataSerializable(EnterpriseDataSerializableSerializer.java:168)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.doRead(EnterpriseDataSerializableSerializer.java:130)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.read(EnterpriseDataSerializableSerializer.java:124)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.read(EnterpriseDataSerializableSerializer.java:52)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:44)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.readObject(AbstractSerializationService.java:289)
	at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readObject(ByteArrayObjectDataInput.java:592)
	at com.hazelcast.internal.partition.ReplicaFragmentMigrationState.readData(ReplicaFragmentMigrationState.java:97)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.readIdentifiedDataSerializable(EnterpriseDataSerializableSerializer.java:161)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.doRead(EnterpriseDataSerializableSerializer.java:130)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.read(EnterpriseDataSerializableSerializer.java:124)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.read(EnterpriseDataSerializableSerializer.java:52)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:44)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.readObject(AbstractSerializationService.java:289)
	at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readObject(ByteArrayObjectDataInput.java:592)
	at com.hazelcast.internal.partition.operation.MigrationOperation.readInternal(MigrationOperation.java:249)
	at com.hazelcast.spi.impl.operationservice.Operation.readData(Operation.java:755)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.readIdentifiedDataSerializable(EnterpriseDataSerializableSerializer.java:161)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.doRead(EnterpriseDataSerializableSerializer.java:130)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.read(EnterpriseDataSerializableSerializer.java:124)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.read(EnterpriseDataSerializableSerializer.java:52)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:44)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:208)
	at com.hazelcast.spi.impl.NodeEngineImpl.toObject(NodeEngineImpl.java:355)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:454)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:197)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:137)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
Caused by: java.lang.NullPointerException
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.readIdentifiedDataSerializable(EnterpriseDataSerializableSerializer.java:161)
	... 28 more
```

**Comment by Danny-Hazelcast** [comment]
/disk1/workspace/rollup-x/5.0-SNAPSHOT/2021_07_14-11_15_31/sql/bit-map


```
WARNING: [10.0.0.148]:5701 [HZ] [5.0-SNAPSHOT] Failure while executing MigrationInfo{uuid=78d44de1-772e-4522-a565-cd8e1d89722d, partitionId=126, source=[10.0.0.148]:5701 - 1373ce95-eaa4-4f77-bb69-bb9f4f95de8a, sourceCurrentReplicaIndex=0, sourceNewReplicaIndex=-1, destination=[10.0.0.164]:5701 - 3467ce37-b25e-4fb1-8ae1-825f735b1786, destinationCurrentReplicaIndex=3, destinationNewReplicaIndex=0, master=[10.0.0.164]:5701, initialPartitionVersion=212, partitionVersionIncrement=2, status=ACTIVE}
com.hazelcast.nio.serialization.HazelcastSerializationException: Problem while reading IdentifiedDataSerializable, namespace: -18, classId: 6, exception: null
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.rethrowIdsReadException(EnterpriseDataSerializableSerializer.java:315)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.readIdentifiedDataSerializable(EnterpriseDataSerializableSerializer.java:168)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.doRead(EnterpriseDataSerializableSerializer.java:130)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.read(EnterpriseDataSerializableSerializer.java:124)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.read(EnterpriseDataSerializableSerializer.java:52)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:44)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.readObject(AbstractSerializationService.java:289)
	at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readObject(ByteArrayObjectDataInput.java:592)
	at com.hazelcast.internal.partition.ReplicaFragmentMigrationState.readData(ReplicaFragmentMigrationState.java:97)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.readIdentifiedDataSerializable(EnterpriseDataSerializableSerializer.java:161)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.doRead(EnterpriseDataSerializableSerializer.java:130)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.read(EnterpriseDataSerializableSerializer.java:124)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.read(EnterpriseDataSerializableSerializer.java:52)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:44)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.readObject(AbstractSerializationService.java:289)
	at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readObject(ByteArrayObjectDataInput.java:592)
	at com.hazelcast.internal.partition.operation.MigrationOperation.readInternal(MigrationOperation.java:249)
	at com.hazelcast.spi.impl.operationservice.Operation.readData(Operation.java:755)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.readIdentifiedDataSerializable(EnterpriseDataSerializableSerializer.java:161)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.doRead(EnterpriseDataSerializableSerializer.java:130)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.read(EnterpriseDataSerializableSerializer.java:124)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.read(EnterpriseDataSerializableSerializer.java:52)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:44)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:208)
	at com.hazelcast.spi.impl.NodeEngineImpl.toObject(NodeEngineImpl.java:355)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:454)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:197)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:137)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
Caused by: java.lang.NullPointerException
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.readIdentifiedDataSerializable(EnterpriseDataSerializableSerializer.java:161)
	... 28 more
```

**Comment by Danny-Hazelcast** [comment]
```
Jul 13, 2021 1:49:25 PM com.hazelcast.internal.partition.operation.MigrationRequestOperation
WARNING: [10.0.0.80]:5701 [HZ] [5.0-SNAPSHOT] Failure while executing MigrationInfo{uuid=110f51aa-d7d2-4b0c-9f85-193d17249a73, partitionId=59, source=[10.0.0.33]:5701 - ac5138fd-e7a5-4e0f-8654-26fc0619591e, sourceCurrentReplicaIndex=1, sourceNewReplicaIndex=-1, destination=[10.0.0.26]:5701 - d050b8be-c10d-4e4e-ad42-e1c281053d65, destinationCurrentReplicaIndex=3, destinationNewReplicaIndex=1, master=[10.0.0.26]:5701, initialPartitionVersion=17, partitionVersionIncrement=2, status=ACTIVE}
com.hazelcast.nio.serialization.HazelcastSerializationException: Problem while reading IdentifiedDataSerializable, namespace: -18, classId: 6, exception: null
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.rethrowIdsReadException(EnterpriseDataSerializableSerializer.java:315)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.readIdentifiedDataSerializable(EnterpriseDataSerializableSerializer.java:168)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.doRead(EnterpriseDataSerializableSerializer.java:130)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.read(EnterpriseDataSerializableSerializer.java:124)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.read(EnterpriseDataSerializableSerializer.java:52)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:44)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.readObject(AbstractSerializationService.java:289)
	at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readObject(ByteArrayObjectDataInput.java:592)
	at com.hazelcast.internal.partition.ReplicaFragmentMigrationState.readData(ReplicaFragmentMigrationState.java:97)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.readIdentifiedDataSerializable(EnterpriseDataSerializableSerializer.java:161)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.doRead(EnterpriseDataSerializableSerializer.java:130)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.read(EnterpriseDataSerializableSerializer.java:124)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.read(EnterpriseDataSerializableSerializer.java:52)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:44)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.readObject(AbstractSerializationService.java:289)
	at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readObject(ByteArrayObjectDataInput.java:592)
	at com.hazelcast.internal.partition.operation.MigrationOperation.readInternal(MigrationOperation.java:249)
	at com.hazelcast.spi.impl.operationservice.Operation.readData(Operation.java:755)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.readIdentifiedDataSerializable(EnterpriseDataSerializableSerializer.java:161)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.doRead(EnterpriseDataSerializableSerializer.java:130)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.read(EnterpriseDataSerializableSerializer.java:124)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.read(EnterpriseDataSerializableSerializer.java:52)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:44)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:208)
	at com.hazelcast.spi.impl.NodeEngineImpl.toObject(NodeEngineImpl.java:355)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:454)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:197)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:137)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
Caused by: java.lang.NullPointerException
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.readIdentifiedDataSerializable(EnterpriseDataSerializableSerializer.java:161)
	... 28 more
```

**Comment by ivanthescientist** [comment]
Not sure if this is of any help, but looks like this is an issue with the Enterprise: 
`ENTERPRISE_MAP_DS_FACTORY_ID` - this is the factory used and the operation that fails is `ENTERPRISE_MAP_REPLICATION_OPERATION`.

This operation was introduced in this PR: 
https://github.com/hazelcast/hazelcast-enterprise/pull/4124

**Comment by mmedenjak** [comment]
@vbekiaris I remember you saw this issue on slack before, do you know if it has already been addressed?

**Comment by vbekiaris** [comment]
No, it's not yet addressed. It affects 4.2->5.0 rolling upgrade, so should be resolved for GA.

**Comment by Danny-Hazelcast** [comment]
https://github.com/hazelcast/hazelcast/issues/19261

**Comment by mmedenjak** [comment]
Fix was merged, feel free to retest @Danny-Hazelcast
