### ISSUE TITLE
Classpath issues in the 5.0 distribution

### ISSUE THREAD

**Issue by nfrankel** [hazelcast/hazelcast#19092]
As a user, I want to be able to submit a Jet job and expect it to work on the cluster in the same way as locally.
  
**Describe the bug**

ATM, two Hazelcast distributions are available: default and `slim`. Obviously, most users - including myself - aim for the most straightforward path and use the former.

The full-fledged default distribution aims to make it easy to run Jet jobs by providing a lot of Jet connectors in the `lib` folder (`/opt/hazelcast/lib/` in the Docker image) _e.g._ `hazelcast-jet-s3-5.0-BETA-1.jar`. But those JARs are **fat** JARs: they contain more than `com.hazelcast` classes. For example, `hazelcast-jet-s3-5.0-BETA-1.jar` contains Netty-related classes.

Running my job that uses Netty HTTP client, versions don't match, and I get this:

```
hazelcast_1      | java.lang.NoSuchMethodError: 'org.eclipse.jetty.client.api.Request org.eclipse.jetty.client.api.Request.onResponseContentDemanded(org.eclipse.jetty.client.api.Response$DemandedContentListener)'
hazelcast_1      | 	at org.eclipse.jetty.reactive.client.ReactiveRequest.<init>(ReactiveRequest.java:88) ~[?:?]
hazelcast_1      | 	at org.eclipse.jetty.reactive.client.ReactiveRequest$Builder.build(ReactiveRequest.java:194) ~[?:?]
hazelcast_1      | 	at org.springframework.http.client.reactive.JettyClientHttpConnector.connect(JettyClientHttpConnector.java:126) ~[?:?]
hazelcast_1      | 	at org.springframework.web.reactive.function.client.ExchangeFunctions$DefaultExchangeFunction.exchange(ExchangeFunctions.java:103) ~[?:?]
hazelcast_1      | 	at org.springframework.web.reactive.function.client.DefaultWebClient$DefaultRequestBodyUriSpec.lambda$exchange$7(DefaultWebClient.java:431) ~[?:?]
hazelcast_1      | 	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44) ~[?:?]
hazelcast_1      | 	at reactor.core.publisher.Flux.subscribe(Flux.java:8235) ~[?:?]
hazelcast_1      | 	at reactor.core.publisher.Flux.subscribeWith(Flux.java:8408) ~[?:?]
hazelcast_1      | 	at reactor.core.publisher.Flux.subscribe(Flux.java:8205) ~[?:?]
hazelcast_1      | 	at reactor.core.publisher.Flux.subscribe(Flux.java:8129) ~[?:?]
hazelcast_1      | 	at reactor.core.publisher.Flux.subscribe(Flux.java:8072) ~[?:?]
hazelcast_1      | 	at org.hazelcast.wikipedia.WikipediaSourceKt$context$1.applyEx(WikipediaSource.kt:20) ~[?:?]
hazelcast_1      | 	at org.hazelcast.wikipedia.WikipediaSourceKt$context$1.applyEx(WikipediaSource.kt) ~[?:?]
hazelcast_1      | 	at com.hazelcast.function.FunctionEx.apply(FunctionEx.java:48) ~[hazelcast-5.0-SNAPSHOT.jar:5.0-SNAPSHOT]
hazelcast_1      | 	at com.hazelcast.jet.impl.connector.ConvenientSourceP.init(ConvenientSourceP.java:111) ~[hazelcast-5.0-SNAPSHOT.jar:5.0-SNAPSHOT]
hazelcast_1      | 	at com.hazelcast.jet.core.AbstractProcessor.init(AbstractProcessor.java:82) ~[hazelcast-5.0-SNAPSHOT.jar:5.0-SNAPSHOT]
hazelcast_1      | 	at com.hazelcast.jet.impl.execution.ProcessorTasklet.lambda$init$2f647568$1(ProcessorTasklet.java:243) ~[hazelcast-5.0-SNAPSHOT.jar:5.0-SNAPSHOT]
hazelcast_1      | 	at com.hazelcast.jet.function.RunnableEx.run(RunnableEx.java:31) ~[hazelcast-5.0-SNAPSHOT.jar:5.0-SNAPSHOT]
hazelcast_1      | 	at com.hazelcast.jet.impl.util.Util.doWithClassLoader(Util.java:498) ~[hazelcast-5.0-SNAPSHOT.jar:5.0-SNAPSHOT]
hazelcast_1      | 	at com.hazelcast.jet.impl.execution.ProcessorTasklet.init(ProcessorTasklet.java:243) ~[hazelcast-5.0-SNAPSHOT.jar:5.0-SNAPSHOT]
hazelcast_1      | 	at com.hazelcast.jet.impl.execution.TaskletExecutionService$BlockingWorker.run(TaskletExecutionService.java:294) [hazelcast-5.0-SNAPSHOT.jar:5.0-SNAPSHOT]
hazelcast_1      | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
hazelcast_1      | 	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
hazelcast_1      | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
hazelcast_1      | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
hazelcast_1      | 	at java.lang.Thread.run(Thread.java:834) [?:?]
hazelcast_1      | 2021-07-13 14:50:55,098 [ERROR] [hz.serene_williams.cached.thread-6] [c.h.j.i.MasterJobContext]: [172.28.0.3]:5701 [dev] [5.0-SNAPSHOT] Execution of job '067c-5531-5880-0001', execution 067c-53fb-81c1-0001 failed
hazelcast_1      | 	Start time: 2021-07-13T14:50:54.737
hazelcast_1      | 	Duration: 00:00:00.361
hazelcast_1      | 	To see additional job metrics enable JobConfig.storeMetricsAfterJobCompletion
hazelcast_1      | com.hazelcast.jet.JetException: Exception in ProcessorTasklet{067c-5531-5880-0001/wikipedia#0}: java.lang.NoSuchMethodError: 'org.eclipse.jetty.client.api.Request org.eclipse.jetty.client.api.Request.onResponseContentDemanded(org.eclipse.jetty.client.api.Response$DemandedContentListener)'
hazelcast_1      | 	at com.hazelcast.jet.impl.execution.TaskletExecutionService$BlockingWorker.run(TaskletExecutionService.java:309) ~[hazelcast-5.0-SNAPSHOT.jar:5.0-SNAPSHOT]
hazelcast_1      | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
hazelcast_1      | 	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
hazelcast_1      | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
hazelcast_1      | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
hazelcast_1      | 	at java.lang.Thread.run(Thread.java:834) ~[?:?]
hazelcast_1      | Caused by: java.lang.NoSuchMethodError: 'org.eclipse.jetty.client.api.Request org.eclipse.jetty.client.api.Request.onResponseContentDemanded(org.eclipse.jetty.client.api.Response$DemandedContentListener)'
hazelcast_1      | 	at org.eclipse.jetty.reactive.client.ReactiveRequest.<init>(ReactiveRequest.java:88) ~[?:?]
hazelcast_1      | 	at org.eclipse.jetty.reactive.client.ReactiveRequest$Builder.build(ReactiveRequest.java:194) ~[?:?]
hazelcast_1      | 	at org.springframework.http.client.reactive.JettyClientHttpConnector.connect(JettyClientHttpConnector.java:126) ~[?:?]
hazelcast_1      | 	at org.springframework.web.reactive.function.client.ExchangeFunctions$DefaultExchangeFunction.exchange(ExchangeFunctions.java:103) ~[?:?]
hazelcast_1      | 	at org.springframework.web.reactive.function.client.DefaultWebClient$DefaultRequestBodyUriSpec.lambda$exchange$7(DefaultWebClient.java:431) ~[?:?]
hazelcast_1      | 	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44) ~[?:?]
hazelcast_1      | 	at reactor.core.publisher.Flux.subscribe(Flux.java:8235) ~[?:?]
hazelcast_1      | 	at reactor.core.publisher.Flux.subscribeWith(Flux.java:8408) ~[?:?]
hazelcast_1      | 	at reactor.core.publisher.Flux.subscribe(Flux.java:8205) ~[?:?]
hazelcast_1      | 	at reactor.core.publisher.Flux.subscribe(Flux.java:8129) ~[?:?]
hazelcast_1      | 	at reactor.core.publisher.Flux.subscribe(Flux.java:8072) ~[?:?]
hazelcast_1      | 	at org.hazelcast.wikipedia.WikipediaSourceKt$context$1.applyEx(WikipediaSource.kt:20) ~[?:?]
hazelcast_1      | 	at org.hazelcast.wikipedia.WikipediaSourceKt$context$1.applyEx(WikipediaSource.kt) ~[?:?]
hazelcast_1      | 	at com.hazelcast.function.FunctionEx.apply(FunctionEx.java:48) ~[hazelcast-5.0-SNAPSHOT.jar:5.0-SNAPSHOT]
hazelcast_1      | 	at com.hazelcast.jet.impl.connector.ConvenientSourceP.init(ConvenientSourceP.java:111) ~[hazelcast-5.0-SNAPSHOT.jar:5.0-SNAPSHOT]
hazelcast_1      | 	at com.hazelcast.jet.core.AbstractProcessor.init(AbstractProcessor.java:82) ~[hazelcast-5.0-SNAPSHOT.jar:5.0-SNAPSHOT]
hazelcast_1      | 	at com.hazelcast.jet.impl.execution.ProcessorTasklet.lambda$init$2f647568$1(ProcessorTasklet.java:243) ~[hazelcast-5.0-SNAPSHOT.jar:5.0-SNAPSHOT]
hazelcast_1      | 	at com.hazelcast.jet.function.RunnableEx.run(RunnableEx.java:31) ~[hazelcast-5.0-SNAPSHOT.jar:5.0-SNAPSHOT]
hazelcast_1      | 	at com.hazelcast.jet.impl.util.Util.doWithClassLoader(Util.java:498) ~[hazelcast-5.0-SNAPSHOT.jar:5.0-SNAPSHOT]
hazelcast_1      | 	at com.hazelcast.jet.impl.execution.ProcessorTasklet.init(ProcessorTasklet.java:243) ~[hazelcast-5.0-SNAPSHOT.jar:5.0-SNAPSHOT]
hazelcast_1      | 	at com.hazelcast.jet.impl.execution.TaskletExecutionService$BlockingWorker.run(TaskletExecutionService.java:294) ~[hazelcast-5.0-SNAPSHOT.jar:5.0-SNAPSHOT]
hazelcast_1      | 	... 5 more
```

**Expected behavior**

The job runs to completion successfully

**To Reproduce**

1. Use the default full distribution
2. Send a job that depends on a library already present on the classpath
3. Weep

** Proposal **

1. ASAP, make the slim distribution the default and prefix the full one as `-full`
2. The problem is very similar to those of application servers and shared libraries. IMHO, we should offer classloading isolation at the job level. This is "a bit" involved, though.

**Comment by mmedenjak** [comment]
cc @Holmistr @vladoschreiner as discussed on [slack](https://hazelcast.slack.com/archives/C034YQBTG/p1626263941322000), this was quite surprising behaviour, given that the whole point of the "fat" docker distribution is the ease-of-use for newcomers (not having to add any dependency, everything being on classpath).

**Comment by cangencer** [comment]
@mmedenjak I asked @jerrinot to have a look - maybe he'll have some time before 5.0 at least to do a diagnosis.

**Comment by Holmistr** [comment]
Ok, let's see what @jerrinot comes up with and what we could do in 5.0. I absolutely understand the hassle and I agree that it should be addresses somehow rather sooner than later.

**Comment by jerrinot** [comment]
This is a complicated matter. I think the solution has multiple parts:

1. Documentation. 
Our documentation should stress the default image is for quick experiments / new users. It has all connectors included. You probably do not want this for production deployments due to security reasons (attach surface). And I would assume advanced users will choose the slim image even for toying. Simply because it gives them more control. Nicolas stubled upon the problem, because he implemented his own source and the impl uses a Netty library. This is NOT the problem *new users* will face. 

The documentation should also list 3rd party dependencies being shaded, with the exact version. Possible issue: How to keep it up-to-date? 

Timing: We should do this documentation exercise in 5.0. 

2. Class relocation
When we shade transitive dependencies into a connector JAR then we should relocate them whenever it's possible. Some libraries are not relocation friendly (think of native libs). If that's the case then we should NOT shade them. 

This will complicate deployment of the connector into the Slim package, but it provides user more visibility into the exact version being used. Optionally we could provide tooling to simplify deployments of connectors with external (non-shaded) dependencies. 

Timing: It's questionable whether it's doable in 5.0. Need more input from PM/Eng leads. 

3. Isolation
The idea of isolation is already being explored in the context of "Hazelcast Applications", this activity is driven by @vladoschreiner . It sounds like the right solution, but there still are many unknowns. 

Timing: Long term, definitely not doable in 5.0.

**Comment by mmedenjak** [comment]
Re: class relocation, I guess it is desirable from the aspect of the JDK module system

**Comment by Holmistr** [comment]
This came up during the hackathon again. I'll be following up on this soon. Thanks @nfrankel and @jerrinot for raising this!

**Comment by Holmistr** [comment]
This seems similar to https://hazelcast.atlassian.net/browse/HZ-745
