### ISSUE TITLE
NPE on Jet job scaling 5.0-BETA-1 from 3 to 1 nodes via Kubernetes

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast#19103]
Using 5.0-BETA-1, in a 3-node cluster with running Jet jobs

If I can scaling from 3 to 1, I get this message

```
Members {size:3, ver:3} [
	Member [10.104.3.7]:5701 - 6c18b2b3-5d89-401d-99d9-cf304b1ce9dd this
	Member [10.104.0.9]:5701 - c6c0b289-64d6-4c6b-92ae-f066d0a4afa7
	Member [10.104.1.5]:5701 - b45e96c9-63a9-4486-8efe-f542a7905913
]
 
12:37:29.717 INFO  hz.hardcore_galois.event-3 c.h.p.d.b.t.MyMembershipListener - ------------------------------------- 
12:37:29.717 INFO  hz.hardcore_galois.event-3 c.h.p.d.b.t.MyMembershipListener - Cluster increased to 3 members 
12:37:29.718 INFO  hz.hardcore_galois.event-3 c.h.p.d.b.t.MyMembershipListener - ------------------------------------- 
12:37:29.718 INFO  hz.hardcore_galois.event-3 c.h.p.d.b.t.MyMembershipListener -  10.104.3.7:5701 - 2 processors 
12:37:29.718 INFO  hz.hardcore_galois.event-3 c.h.p.d.b.t.MyMembershipListener -  10.104.0.9:5701 - 2 processors 
12:37:29.718 INFO  hz.hardcore_galois.event-3 c.h.p.d.b.t.MyMembershipListener -  10.104.1.5:5701 - 2 processors 
12:37:29.718 INFO  hz.hardcore_galois.event-3 c.h.p.d.b.t.MyMembershipListener - ------------------------------------- 
12:37:29.718 INFO  hz.hardcore_galois.event-3 c.h.p.d.b.t.MyMembershipListener - Total processors 6 
12:37:29.718 INFO  hz.hardcore_galois.event-3 c.h.p.d.b.t.MyMembershipListener - ------------------------------------- 
12:37:29.946 INFO  hz.hardcore_galois.migration c.h.i.partition.impl.MigrationManager - [10.104.3.7]:5701 [grid] [5.0-BETA-1] Repartitioning cluster data. Migration tasks count: 271 
12:37:33.250 INFO  hz.hardcore_galois.migration c.h.i.partition.impl.MigrationManager - [10.104.3.7]:5701 [grid] [5.0-BETA-1] All migration tasks have been completed. (repartitionTime=Thu Jul 15 12:37:29 UTC 2021, plannedMigrations=271, completedMigrations=271, remainingMigrations=0, totalCompletedMigrations=542) 
12:37:39.715 INFO  hz.hardcore_galois.cached.thread-7 com.hazelcast.jet.impl.MasterJobContext - [10.104.3.7]:5701 [grid] [5.0-BETA-1] Requested restart of job 'IngestTrades', execution 067e-c77a-aac4-0001 to make use of added member(s). Job was running on 2 members, cluster now has 3 data members with assigned partitions 
12:37:39.748 INFO  hz.hardcore_galois.cached.thread-7 com.hazelcast.jet.impl.MasterJobContext - [10.104.3.7]:5701 [grid] [5.0-BETA-1] Requested restart of job 'AggregateQuery', execution 067e-c77a-aac5-0001 to make use of added member(s). Job was running on 2 members, cluster now has 3 data members with assigned partitions 
12:37:39.921 INFO  hz.hardcore_galois.cached.thread-6 com.hazelcast.jet.impl.MasterJobContext - [10.104.3.7]:5701 [grid] [5.0-BETA-1] About to restore the state of job 'IngestTrades', execution 067e-c9e7-7380-0001 from snapshot 63, mapName = __jet.snapshot.067e-c77a-aac0-0001.1 
12:37:39.921 INFO  hz.hardcore_galois.cached.thread-5 com.hazelcast.jet.impl.MasterJobContext - [10.104.3.7]:5701 [grid] [5.0-BETA-1] About to restore the state of job 'AggregateQuery', execution 067e-c9e7-7381-0001 from snapshot 62, mapName = __jet.snapshot.067e-c77a-aac2-0001.0 
12:37:39.922 INFO  hz.hardcore_galois.cached.thread-6 com.hazelcast.jet.impl.MasterJobContext - [10.104.3.7]:5701 [grid] [5.0-BETA-1] Start executing job 'IngestTrades', execution 067e-c9e7-7380-0001, execution graph in DOT format:
digraph DAG {
	"kafkaSource(kf_trades)" [localParallelism=2];
	"filter_every_100000" [localParallelism=2];
	"loggerSink" [localParallelism=1];
	"mapSink(trades)" [localParallelism=1];
	"kafkaSource(kf_trades)" -> "mapSink(trades)" [label="partitioned", taillabel=0, queueSize=1024];
	"kafkaSource(kf_trades)" -> "filter_every_100000" [taillabel=1, queueSize=1024];
	"filter_every_100000" -> "loggerSink" [queueSize=1024];
}
HINT: You can use graphviz or http://viz-js.com to visualize the printed graph. 
12:37:39.922 INFO  hz.hardcore_galois.cached.thread-5 com.hazelcast.jet.impl.MasterJobContext - [10.104.3.7]:5701 [grid] [5.0-BETA-1] Start executing job 'AggregateQuery', execution 067e-c9e7-7381-0001, execution graph in DOT format:
digraph DAG {
	"kafkaSource(kf_trades)" [localParallelism=2];
	"mapUsingIMap" [localParallelism=2];
	"aggregate by symbol" [localParallelism=2];
	"filter_every_100000" [localParallelism=2];
	"loggerSink" [localParallelism=1];
	"mapSink(AggregateQuery_results)" [localParallelism=1];
	"kafkaSource(kf_trades)" -> "mapUsingIMap" [queueSize=1024];
	"mapUsingIMap" -> "aggregate by symbol" [label="distributed-partitioned", queueSize=1024];
	"aggregate by symbol" -> "mapSink(AggregateQuery_results)" [label="partitioned", taillabel=0, queueSize=1024];
	"aggregate by symbol" -> "filter_every_100000" [taillabel=1, queueSize=1024];
	"filter_every_100000" -> "loggerSink" [queueSize=1024];
}
HINT: You can use graphviz or http://viz-js.com to visualize the printed graph. 
12:37:40.315 INFO  hz.hardcore_galois.jet.blocking.thread-0 c.h.jet.impl.connector.WriteLoggerP - [10.104.3.7]:5701 [grid] [5.0-BETA-1] [IngestTrades/loggerSink#1] 063a170c-afea-4908-8ec0-ebaa0a1cc031={"id": "063a170c-afea-4908-8ec0-ebaa0a1cc031","timestamp": 1626352659838,"symbol": "FFHL","price": 2505,"quantity": 9109} 
12:37:40.316 INFO  hz.hardcore_galois.jet.blocking.thread-0 c.h.jet.impl.connector.WriteLoggerP - [10.104.3.7]:5701 [grid] [5.0-BETA-1] [IngestTrades/loggerSink#1] 68c3c4cc-8883-4cb3-80c1-c72a4c8e4272={"id": "68c3c4cc-8883-4cb3-80c1-c72a4c8e4272","timestamp": 1626352660011,"symbol": "ESGU","price": 2499,"quantity": 6472} 
12:37:40.368 INFO  hz.hardcore_galois.jet.blocking.thread-3 c.h.jet.impl.connector.WriteLoggerP - [10.104.3.7]:5701 [grid] [5.0-BETA-1] [AggregateQuery/loggerSink#1] FFHL=(67, 831109778, 2505) 
12:38:13.590 INFO  hz.hardcore_galois.priority-generic-operation.thread-0 c.h.i.partition.impl.MigrationManager - [10.104.3.7]:5701 [grid] [5.0-BETA-1] Shutdown request of Member [10.104.1.5]:5701 - b45e96c9-63a9-4486-8efe-f542a7905913 is handled 
12:38:13.593 INFO  hz.hardcore_galois.migration c.h.i.partition.impl.MigrationManager - [10.104.3.7]:5701 [grid] [5.0-BETA-1] Repartitioning cluster data. Migration tasks count: 180 
12:38:14.616 INFO  hz.hardcore_galois.migration c.h.i.partition.impl.MigrationManager - [10.104.3.7]:5701 [grid] [5.0-BETA-1] All migration tasks have been completed. (repartitionTime=Thu Jul 15 12:38:13 UTC 2021, plannedMigrations=180, completedMigrations=180, remainingMigrations=0, totalCompletedMigrations=722) 
12:38:14.622 INFO  hz.hardcore_galois.cached.thread-7 c.h.i.server.tcp.TcpServerConnector - [10.104.3.7]:5701 [grid] [5.0-BETA-1] Connecting to /10.104.1.5:5701, timeout: 10000, bind-any: true 
12:38:14.623 INFO  hz.hardcore_galois.cached.thread-7 c.h.i.server.tcp.TcpServerConnector - [10.104.3.7]:5701 [grid] [5.0-BETA-1] Could not connect to: /10.104.1.5:5701. Reason: IOException[Connection refused to address /10.104.1.5:5701] 
12:38:14.723 INFO  hz.hardcore_galois.cached.thread-3 c.h.i.server.tcp.TcpServerConnector - [10.104.3.7]:5701 [grid] [5.0-BETA-1] Connecting to /10.104.1.5:5701, timeout: 10000, bind-any: true 
12:38:14.724 INFO  hz.hardcore_galois.cached.thread-3 c.h.i.server.tcp.TcpServerConnector - [10.104.3.7]:5701 [grid] [5.0-BETA-1] Could not connect to: /10.104.1.5:5701. Reason: IOException[Connection refused to address /10.104.1.5:5701] 
12:38:14.824 INFO  hz.hardcore_galois.cached.thread-6 c.h.i.server.tcp.TcpServerConnector - [10.104.3.7]:5701 [grid] [5.0-BETA-1] Connecting to /10.104.1.5:5701, timeout: 10000, bind-any: true 
12:38:19.291 INFO  hz.hardcore_galois.priority-generic-operation.thread-0 c.h.i.partition.impl.MigrationManager - [10.104.3.7]:5701 [grid] [5.0-BETA-1] Shutdown request of Member [10.104.0.9]:5701 - c6c0b289-64d6-4c6b-92ae-f066d0a4afa7 is handled 
12:38:19.294 INFO  hz.hardcore_galois.migration c.h.i.partition.impl.MigrationManager - [10.104.3.7]:5701 [grid] [5.0-BETA-1] Repartitioning cluster data. Migration tasks count: 135 
12:38:20.413 INFO  hz.hardcore_galois.migration c.h.i.partition.impl.MigrationManager - [10.104.3.7]:5701 [grid] [5.0-BETA-1] All migration tasks have been completed. (repartitionTime=Thu Jul 15 12:38:19 UTC 2021, plannedMigrations=135, completedMigrations=135, remainingMigrations=0, totalCompletedMigrations=857) 
12:38:20.417 INFO  hz.hardcore_galois.cached.thread-4 c.h.i.server.tcp.TcpServerConnector - [10.104.3.7]:5701 [grid] [5.0-BETA-1] Connecting to /10.104.0.9:5701, timeout: 10000, bind-any: true 
12:38:20.418 INFO  hz.hardcore_galois.cached.thread-4 c.h.i.server.tcp.TcpServerConnector - [10.104.3.7]:5701 [grid] [5.0-BETA-1] Could not connect to: /10.104.0.9:5701. Reason: IOException[Connection refused to address /10.104.0.9:5701] 
12:38:20.518 INFO  hz.hardcore_galois.cached.thread-4 c.h.i.server.tcp.TcpServerConnector - [10.104.3.7]:5701 [grid] [5.0-BETA-1] Connecting to /10.104.0.9:5701, timeout: 10000, bind-any: true 
12:38:20.519 INFO  hz.hardcore_galois.cached.thread-4 c.h.i.server.tcp.TcpServerConnector - [10.104.3.7]:5701 [grid] [5.0-BETA-1] Could not connect to: /10.104.0.9:5701. Reason: IOException[Connection refused to address /10.104.0.9:5701] 
12:38:20.619 INFO  hz.hardcore_galois.cached.thread-4 c.h.i.server.tcp.TcpServerConnector - [10.104.3.7]:5701 [grid] [5.0-BETA-1] Connecting to /10.104.0.9:5701, timeout: 10000, bind-any: true 
12:38:24.833 INFO  hz.hardcore_galois.cached.thread-6 c.h.i.server.tcp.TcpServerConnector - [10.104.3.7]:5701 [grid] [5.0-BETA-1] Could not connect to: /10.104.1.5:5701. Reason: IOException[null to address /10.104.1.5:5701] 
12:38:24.933 INFO  hz.hardcore_galois.cached.thread-6 c.h.i.server.tcp.TcpServerConnector - [10.104.3.7]:5701 [grid] [5.0-BETA-1] Connecting to /10.104.1.5:5701, timeout: 10000, bind-any: true 
12:38:30.433 INFO  hz.hardcore_galois.priority-generic-operation.thread-0 c.h.c.i.p.task.AuthenticationMessageTask - [10.104.3.7]:5701 [grid] [5.0-BETA-1] Received auth from Connection[id=139, /10.104.3.7:5701->/10.104.4.14:34097, qualifier=null, endpoint=[10.104.4.14]:34097, alive=true, connectionType=JVM, planeIndex=-1], successfully authenticated, clientUuid: ba221647-d976-4bd8-a2c1-3845e1c09553, client version: 5.0-BETA-1 
12:38:30.630 INFO  hz.hardcore_galois.cached.thread-4 c.h.i.server.tcp.TcpServerConnector - [10.104.3.7]:5701 [grid] [5.0-BETA-1] Could not connect to: /10.104.0.9:5701. Reason: IOException[null to address /10.104.0.9:5701] 
12:38:30.730 INFO  hz.hardcore_galois.cached.thread-4 c.h.i.server.tcp.TcpServerConnector - [10.104.3.7]:5701 [grid] [5.0-BETA-1] Connecting to /10.104.0.9:5701, timeout: 10000, bind-any: true 
12:38:34.943 INFO  hz.hardcore_galois.cached.thread-6 c.h.i.server.tcp.TcpServerConnector - [10.104.3.7]:5701 [grid] [5.0-BETA-1] Could not connect to: /10.104.1.5:5701. Reason: IOException[null to address /10.104.1.5:5701] 
12:38:34.944 WARN  hz.hardcore_galois.cached.thread-6 c.h.i.s.t.TcpServerConnectionErrorHandler - [10.104.3.7]:5701 [grid] [5.0-BETA-1] Removing connection to endpoint [10.104.1.5]:5701 Cause => java.io.IOException {null to address /10.104.1.5:5701}, Error-Count: 5 
12:38:34.944 INFO  hz.hardcore_galois.cached.thread-6 c.h.i.cluster.impl.MembershipManager - [10.104.3.7]:5701 [grid] [5.0-BETA-1] Removing Member [10.104.1.5]:5701 - b45e96c9-63a9-4486-8efe-f542a7905913 
12:38:34.946 INFO  hz.hardcore_galois.cached.thread-6 c.h.internal.cluster.ClusterService - [10.104.3.7]:5701 [grid] [5.0-BETA-1] 

Members {size:2, ver:4} [
	Member [10.104.3.7]:5701 - 6c18b2b3-5d89-401d-99d9-cf304b1ce9dd this
	Member [10.104.0.9]:5701 - c6c0b289-64d6-4c6b-92ae-f066d0a4afa7
]
 
12:38:34.947 INFO  hz.hardcore_galois.migration c.h.i.partition.impl.MigrationManager - [10.104.3.7]:5701 [grid] [5.0-BETA-1] Partition balance is ok, no need to repartition. 
12:38:34.950 INFO  hz.hardcore_galois.cached.thread-1 c.h.t.TransactionManagerService - [10.104.3.7]:5701 [grid] [5.0-BETA-1] Committing/rolling-back live transactions of [10.104.1.5]:5701, UUID: b45e96c9-63a9-4486-8efe-f542a7905913 
12:38:40.741 INFO  hz.hardcore_galois.cached.thread-4 c.h.i.server.tcp.TcpServerConnector - [10.104.3.7]:5701 [grid] [5.0-BETA-1] Could not connect to: /10.104.0.9:5701. Reason: IOException[null to address /10.104.0.9:5701] 
12:38:40.741 WARN  hz.hardcore_galois.cached.thread-4 c.h.i.s.t.TcpServerConnectionErrorHandler - [10.104.3.7]:5701 [grid] [5.0-BETA-1] Removing connection to endpoint [10.104.0.9]:5701 Cause => java.io.IOException {null to address /10.104.0.9:5701}, Error-Count: 5 
12:38:40.741 INFO  hz.hardcore_galois.cached.thread-4 c.h.i.cluster.impl.MembershipManager - [10.104.3.7]:5701 [grid] [5.0-BETA-1] Removing Member [10.104.0.9]:5701 - c6c0b289-64d6-4c6b-92ae-f066d0a4afa7 
12:38:40.742 INFO  hz.hardcore_galois.cached.thread-4 c.h.internal.cluster.ClusterService - [10.104.3.7]:5701 [grid] [5.0-BETA-1] 

Members {size:1, ver:5} [
	Member [10.104.3.7]:5701 - 6c18b2b3-5d89-401d-99d9-cf304b1ce9dd this
]
 
12:38:40.743 INFO  hz.hardcore_galois.migration c.h.i.partition.impl.MigrationManager - [10.104.3.7]:5701 [grid] [5.0-BETA-1] Partition balance is ok, no need to repartition. 
12:38:40.743 INFO  hz.hardcore_galois.cached.thread-5 c.h.t.TransactionManagerService - [10.104.3.7]:5701 [grid] [5.0-BETA-1] Committing/rolling-back live transactions of [10.104.0.9]:5701, UUID: c6c0b289-64d6-4c6b-92ae-f066d0a4afa7 
12:38:40.746 WARN  hz.hardcore_galois.event-3 c.h.p.d.b.t.MyMembershipListener - Abandon reporting, exception on member Member [10.104.0.9]:5701 - c6c0b289-64d6-4c6b-92ae-f066d0a4afa7: Member [10.104.0.9]:5701 - c6c0b289-64d6-4c6b-92ae-f066d0a4afa7 has left cluster! 
12:38:40.747 INFO  hz.hardcore_galois.event-3 c.h.p.d.b.t.MyMembershipListener - ------------------------------------- 
12:38:40.747 INFO  hz.hardcore_galois.event-3 c.h.p.d.b.t.MyMembershipListener - Cluster decreased to 1 members 
12:38:40.747 INFO  hz.hardcore_galois.event-3 c.h.p.d.b.t.MyMembershipListener - ------------------------------------- 
12:38:40.748 INFO  hz.hardcore_galois.event-3 c.h.p.d.b.t.MyMembershipListener -  10.104.3.7:5701 - 2 processors 
12:38:40.749 INFO  hz.hardcore_galois.event-3 c.h.p.d.b.t.MyMembershipListener - ------------------------------------- 
12:38:40.750 INFO  hz.hardcore_galois.event-3 c.h.p.d.b.t.MyMembershipListener - Total processors 2 
12:38:40.750 INFO  hz.hardcore_galois.event-3 c.h.p.d.b.t.MyMembershipListener - ------------------------------------- 
12:38:41.596 INFO  hz.hardcore_galois.cached.thread-6 com.hazelcast.jet.impl.MasterJobContext - [10.104.3.7]:5701 [grid] [5.0-BETA-1] About to restore the state of job 'IngestTrades', execution 067e-c9e7-7382-0001 from snapshot 67, mapName = __jet.snapshot.067e-c77a-aac0-0001.1 
12:38:41.597 INFO  hz.hardcore_galois.cached.thread-6 com.hazelcast.jet.impl.MasterJobContext - [10.104.3.7]:5701 [grid] [5.0-BETA-1] Start executing job 'IngestTrades', execution 067e-c9e7-7382-0001, execution graph in DOT format:
digraph DAG {
	"kafkaSource(kf_trades)" [localParallelism=2];
	"mapSink(trades)" [localParallelism=1];
	"filter_every_100000" [localParallelism=2];
	"loggerSink" [localParallelism=1];
	"kafkaSource(kf_trades)" -> "mapSink(trades)" [label="partitioned", taillabel=0, queueSize=1024];
	"kafkaSource(kf_trades)" -> "filter_every_100000" [taillabel=1, queueSize=1024];
	"filter_every_100000" -> "loggerSink" [queueSize=1024];
}
HINT: You can use graphviz or http://viz-js.com to visualize the printed graph. 
12:38:41.604 INFO  hz.hardcore_galois.cached.thread-1 com.hazelcast.jet.impl.MasterJobContext - [10.104.3.7]:5701 [grid] [5.0-BETA-1] About to restore the state of job 'AggregateQuery', execution 067e-c9e7-7383-0001 from snapshot 66, mapName = __jet.snapshot.067e-c77a-aac2-0001.0 
12:38:41.605 INFO  hz.hardcore_galois.cached.thread-1 com.hazelcast.jet.impl.MasterJobContext - [10.104.3.7]:5701 [grid] [5.0-BETA-1] Start executing job 'AggregateQuery', execution 067e-c9e7-7383-0001, execution graph in DOT format:
digraph DAG {
	"kafkaSource(kf_trades)" [localParallelism=2];
	"mapUsingIMap" [localParallelism=2];
	"aggregate by symbol" [localParallelism=2];
	"mapSink(AggregateQuery_results)" [localParallelism=1];
	"filter_every_100000" [localParallelism=2];
	"loggerSink" [localParallelism=1];
	"kafkaSource(kf_trades)" -> "mapUsingIMap" [queueSize=1024];
	"mapUsingIMap" -> "aggregate by symbol" [label="distributed-partitioned", queueSize=1024];
	"aggregate by symbol" -> "mapSink(AggregateQuery_results)" [label="partitioned", taillabel=0, queueSize=1024];
	"aggregate by symbol" -> "filter_every_100000" [taillabel=1, queueSize=1024];
	"filter_every_100000" -> "loggerSink" [queueSize=1024];
}
HINT: You can use graphviz or http://viz-js.com to visualize the printed graph. 
12:38:41.729 INFO  hz.hardcore_galois.jet.blocking.thread-4 c.h.jet.impl.connector.WriteLoggerP - [10.104.3.7]:5701 [grid] [5.0-BETA-1] [IngestTrades/loggerSink#0] 01f94f59-5d1e-48b3-90a8-2ae6a7ff8419={"id": "01f94f59-5d1e-48b3-90a8-2ae6a7ff8419","timestamp": 1626352694881,"symbol": "KRNT","price": 2490,"quantity": 6869} 
12:38:41.731 INFO  hz.hardcore_galois.jet.blocking.thread-0 c.h.jet.impl.connector.WriteLoggerP - [10.104.3.7]:5701 [grid] [5.0-BETA-1] [AggregateQuery/loggerSink#0] AKBA=(63, 706686476, 2497) 
12:38:51.942 ERROR Thread-1243494 com.hazelcast.jet.impl.MasterContext - [10.104.3.7]:5701 [grid] [5.0-BETA-1] Exception during callback 
java.lang.NullPointerException: null
	at com.hazelcast.jet.impl.exception.JobTerminateRequestedException.<init>(JobTerminateRequestedException.java:28)
	at com.hazelcast.jet.impl.MasterJobContext.getErrorFromResponses(MasterJobContext.java:546)
	at com.hazelcast.jet.impl.MasterJobContext.lambda$invokeStartExecution$6(MasterJobContext.java:472)
	at com.hazelcast.jet.impl.MasterContext.lambda$invokeOnParticipant$3(MasterContext.java:312)
	at com.hazelcast.jet.impl.util.ExceptionUtil.lambda$withTryCatch$0(ExceptionUtil.java:172)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$WhenCompleteNode.lambda$execute$0(AbstractInvocationFuture.java:1563)
	at java.base/java.lang.Thread.run(Thread.java:829)
12:38:52.796 ERROR Thread-1250574 com.hazelcast.jet.impl.MasterContext - [10.104.3.7]:5701 [grid] [5.0-BETA-1] Exception during callback 
java.lang.NullPointerException: null
	at com.hazelcast.jet.impl.exception.JobTerminateRequestedException.<init>(JobTerminateRequestedException.java:28)
	at com.hazelcast.jet.impl.MasterJobContext.getErrorFromResponses(MasterJobContext.java:546)
	at com.hazelcast.jet.impl.MasterJobContext.lambda$invokeStartExecution$6(MasterJobContext.java:472)
	at com.hazelcast.jet.impl.MasterContext.lambda$invokeOnParticipant$3(MasterContext.java:312)
	at com.hazelcast.jet.impl.util.ExceptionUtil.lambda$withTryCatch$0(ExceptionUtil.java:172)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$WhenCompleteNode.lambda$execute$0(AbstractInvocationFuture.java:1563)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by leszko** [comment]
@neilstevenson 
1. What is the simplest way to reproduce this issue?
2. Can you try to reproduce it locally? If you kill 2 members out of 3, don't you get this exception?

I think we need someone from Jet/Core to look into this. Not sure what can cause it.

**Comment by neilstevenson** [comment]
I tried today and it's didn't recur, so it's not deterministic.
I've not managed to make it occur locally either. So far I have only seen once on Kubernetes.
My suspicion is when two nodes leave the cluster in rapid succession, but when I tried `kill -9` locally it didn't cause this.
