### ISSUE TITLE
com.hazelcast.jet.sql.impl.connector.file.SqlHadoopTest fails on Solaris, JDK 8 

### ISSUE THREAD

**Issue by slavagithub** [hazelcast/hazelcast#19131]
master, rev e6bd62e0036c9bf93a2d3d7494707f3da33b304f
Failed on Solaris, Oracle JDK 8
Failed tests:
com.hazelcast.jet.hadoop.file.ParquetFileFormatTest
com.hazelcast.jet.sql.impl.connector.file.SqlHadoopTest

http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Solaris-OracleJDK8-without-checkstyle/com.hazelcast$hazelcast-sql/19/
http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Solaris-OracleJDK8-without-checkstyle/com.hazelcast.jet$hazelcast-jet-hadoop-core/19/testReport/junit/com.hazelcast.jet.hadoop.file/ParquetFileFormatTest/
Stacktrace:
```
java.lang.NoClassDefFoundError: Could not initialize class org.xerial.snappy.Snappy
	at org.apache.parquet.hadoop.codec.SnappyCompressor.compress(SnappyCompressor.java:67)
	at org.apache.hadoop.io.compress.CompressorStream.compress(CompressorStream.java:81)
	at org.apache.hadoop.io.compress.CompressorStream.finish(CompressorStream.java:92)
	at org.apache.parquet.hadoop.CodecFactory$HeapBytesCompressor.compress(CodecFactory.java:167)
	at org.apache.parquet.hadoop.ColumnChunkPageWriteStore$ColumnChunkPageWriter.writePage(ColumnChunkPageWriteStore.java:168)
	at org.apache.parquet.column.impl.ColumnWriterV1.writePage(ColumnWriterV1.java:59)
	at org.apache.parquet.column.impl.ColumnWriterBase.writePage(ColumnWriterBase.java:387)
	at org.apache.parquet.column.impl.ColumnWriteStoreBase.flush(ColumnWriteStoreBase.java:186)
	at org.apache.parquet.column.impl.ColumnWriteStoreV1.flush(ColumnWriteStoreV1.java:29)
	at org.apache.parquet.hadoop.InternalParquetRecordWriter.flushRowGroupToStore(InternalParquetRecordWriter.java:185)
	at org.apache.parquet.hadoop.InternalParquetRecordWriter.close(InternalParquetRecordWriter.java:124)
	at org.apache.parquet.hadoop.ParquetWriter.close(ParquetWriter.java:319)
	at com.hazelcast.jet.sql.impl.connector.file.FileUtil.writeParquetPayloadTo(FileUtil.java:152)
	at com.hazelcast.jet.sql.impl.connector.file.SqlHadoopTest.storeParquet(SqlHadoopTest.java:447)
	at com.hazelcast.jet.sql.impl.connector.file.SqlHadoopTest.test_parquet_nulls(SqlHadoopTest.java:211)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

Standard output:
```
Finished Running Test: test_csv in 1.047 seconds.
07:33:17,401 ERROR || - [EventServiceImpl] hz.pensive_heisenberg.event-78 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] hz.pensive_heisenberg.event-78 caught an exception while processing:com.hazelcast.spi.impl.eventservice.impl.LocalEventDispatcher@7f8d1f7e
java.lang.UnsupportedOperationException: SQL catalog must never be cleared - MapEvent{entryEventType=CLEAR_ALL, member=Member [127.0.0.1]:5701 - 82d8597e-9207-4fdf-9cc8-bd826db956b8 this, name='__sql.catalog', numberOfEntriesAffected=1}
	at com.hazelcast.jet.sql.impl.schema.MappingStorage$EntryListenerAdapter.mapCleared(MappingStorage.java:160) ~[classes/:?]
	at com.hazelcast.replicatedmap.impl.ReplicatedMapEventPublishingService.dispatchEvent(ReplicatedMapEventPublishingService.java:132) ~[hazelcast-5.0-SNAPSHOT.jar:5.0-SNAPSHOT]
	at com.hazelcast.replicatedmap.impl.ReplicatedMapService.dispatchEvent(ReplicatedMapService.java:232) ~[hazelcast-5.0-SNAPSHOT.jar:5.0-SNAPSHOT]
	at com.hazelcast.spi.impl.eventservice.impl.LocalEventDispatcher.run(LocalEventDispatcher.java:64) ~[hazelcast-5.0-SNAPSHOT.jar:5.0-SNAPSHOT]
	at com.hazelcast.internal.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:245) [hazelcast-5.0-SNAPSHOT.jar:5.0-SNAPSHOT]
	at com.hazelcast.internal.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:228) [hazelcast-5.0-SNAPSHOT.jar:5.0-SNAPSHOT]
Started Running Test: test_parquet_nulls
07:33:17,504  INFO || - [audit] IPC Server handler 5 on default port 40529 - allowed=true	ugi=jenkins (auth:SIMPLE)	ip=/127.0.0.1	cmd=create	src=/parquet-nulls/file.parquet	dst=null	perm=jenkins:supergroup:rw-r--r--	proto=rpc
07:33:18,214  INFO |test_parquet_nulls| - [SqlTestSupport] Listener at localhost/50423 - Removing 0 cached plans in SqlTestSupport.@After
07:33:18,215  INFO |test_parquet_nulls| - [SimpleTestInClusterSupport] Listener at localhost/50423 - Ditching 0 jobs in SimpleTestInClusterSupport.@After: []
07:33:18,215  INFO |test_parquet_nulls| - [SimpleTestInClusterSupport] Listener at localhost/50423 - Destroying 0 distributed objects in SimpleTestInClusterSupport.@After: []
BuildInfo right after test_parquet_nulls(com.hazelcast.jet.sql.impl.connector.file.SqlHadoopTest): BuildInfo{version='5.0-SNAPSHOT', build='20210717', buildNumber=20210717, revision=e6bd62e, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'test_parquet_nulls(com.hazelcast.jet.sql.impl.connector.file.SqlHadoopTest):'
07:33:15, accumulated pauses: 2912 ms, max pause: 191 ms, pauses over 1000 ms: 0
```

**Comment by olukas** [comment]
Solaris is supported on a one-off, best effort, case-by-case basis => closing this test failure.
