### ISSUE TITLE
Better error handling in jet enabled/disabled mixed cluster setup

### ISSUE THREAD

**Issue by zhmaeff** [hazelcast/hazelcast#19136]
I have 2 members cluster of HZ 5.0-SNAPSHOT.
One member (5016 port) has jet enabled in its XML config.
Another member (5017 port) has jet disabled.

I submit a simple jet pipeline to a member with enabled Jet.
```java
Pipeline p = Pipeline.create();
p.readFrom(TestSources.itemStream(1))
                .withoutTimestamps()
                .setName("filter out odd numbers")
                .writeTo(Sinks.logger());

ClientConfig clientConfig = new ClientConfig()
                .setClusterName("cluster-for-test-HazelcastWithOnlyOneMemberWithEnabledJet#testStreamingSupport")
                .setNetworkConfig(new ClientNetworkConfig().addAddress("127.0.0.1:5016"));
HazelcastInstance jetServer = HazelcastClient.newHazelcastClient(clientConfig);
jetServer.getJet().newJob(p);

```

Member accepts submitted job but execution fails immeadiately. See logs below:
```
 Jul 19, 2021 6:14:30 PM com.hazelcast.jet.impl.JobCoordinationService
 INFO: [127.0.0.1]:5016 [cluster-for-test-HazelcastWithOnlyOneMemberWithEnabledJet#testStreamingSupport] [5.0-SNAPSHOT] Starting job 0684-1428-f580-0001 based on submit request
 Jul 19, 2021 6:14:30 PM com.hazelcast.jet.impl.MasterJobContext
 INFO: [127.0.0.1]:5016 [cluster-for-test-HazelcastWithOnlyOneMemberWithEnabledJet#testStreamingSupport] [5.0-SNAPSHOT] Didn't find any snapshot to restore for job '0684-1428-f580-0001', execution 0684-1429-1a00-0001
 Jul 19, 2021 6:14:30 PM com.hazelcast.jet.impl.MasterJobContext
 INFO: [127.0.0.1]:5016 [cluster-for-test-HazelcastWithOnlyOneMemberWithEnabledJet#testStreamingSupport] [5.0-SNAPSHOT] Start executing job '0684-1428-f580-0001', execution 0684-1429-1a00-0001, execution graph in DOT format:
 digraph DAG {
 	"filter out odd numbers" [localParallelism=1];
 	"loggerSink" [localParallelism=1];
 	"filter out odd numbers" -> "loggerSink" [queueSize=1024];
 }
 HINT: You can use graphviz or http://viz-js.com to visualize the printed graph.
 Jul 19, 2021 6:14:30 PM com.hazelcast.jet.impl.JobExecutionService
 INFO: [127.0.0.1]:5016 [cluster-for-test-HazelcastWithOnlyOneMemberWithEnabledJet#testStreamingSupport] [5.0-SNAPSHOT] Execution plan for jobId=0684-1428-f580-0001, jobName='0684-1428-f580-0001', executionId=0684-1429-1a00-0001 initialized
 Jul 19, 2021 6:14:30 PM com.hazelcast.jet.impl.MasterJobContext
 SEVERE: [127.0.0.1]:5016 [cluster-for-test-HazelcastWithOnlyOneMemberWithEnabledJet#testStreamingSupport] [5.0-SNAPSHOT] job '0684-1428-f580-0001', execution 0684-1429-1a00-0001: some TerminateExecutionOperation invocations failed, execution might remain stuck: [MemberInfo{address=[127.0.0.1]:5017, uuid=924b0d0c-35e0-4074-a9fc-cad2aebf91a1, liteMember=false, memberListJoinVersion=2}=java.lang.IllegalArgumentException: Jet is disabled, see JetConfig#setEnabled., MemberInfo{address=[127.0.0.1]:5016, uuid=7f1a7f8f-67ce-4aae-a255-503544f87026, liteMember=false, memberListJoinVersion=1}=null]
 Jul 19, 2021 6:14:30 PM com.hazelcast.jet.impl.MasterJobContext
 SEVERE: [127.0.0.1]:5016 [cluster-for-test-HazelcastWithOnlyOneMemberWithEnabledJet#testStreamingSupport] [5.0-SNAPSHOT] Execution of job '0684-1428-f580-0001', execution 0684-1429-1a00-0001 failed
 	Start time: 2021-07-19T18:14:30.105
 	Duration: 00:00:00.055
 	To see additional job metrics enable JobConfig.storeMetricsAfterJobCompletion
 java.lang.IllegalArgumentException: Jet is disabled, see JetConfig#setEnabled.
 	at com.hazelcast.jet.impl.operation.AsyncOperation.getJetServiceBackend(AsyncOperation.java:100)
 	at com.hazelcast.jet.impl.operation.AsyncOperation.beforeRun(AsyncOperation.java:45)
 	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:248)
 	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:470)
 	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:197)
 	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:137)
 	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123)
 	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
```

> java.lang.IllegalArgumentException: Jet is disabled, see JetConfig#setEnabled.

Exception message is a bit confusing in this situation, because member which throws that exception actually has enabled Jet.
Also, could we fail earlier and throw smth meaningful even before accepting a submitted job?

**Comment by mmedenjak** [comment]
Moving out of scope. We could apply the same reasoning to other HZ features that require coordination - WAN replication, CP subsystem and any feature of any data structure which requires coordination between members. We don't validate that the configuration matches (or is compatible) in any case. The only validation that we do is on member join where we assert that the cluster names and partition counts match. And forbidding members to join if configs don't match is a tricky ordeal since we actually want to allow members of different configurations to join in some cases (e.g. rolling restart, rolling upgrade).

Moving to backlog. If more people complain about it, we'll introduce a check when the jet service starts being used.
