### ISSUE TITLE
NPE from TcpServerConnectionChannelErrorHandler

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast#19152]
5.0-SNAPSHOT (`20210722 - 97e59fa`) is throwing NPEs that 5.0-BETA-1 doesn't

```
09:08:00.569 ERROR hz.practical_khorana.IO.thread-in-0 c.h.i.s.t.TcpServerConnectionChannelErrorHandler - [10.104.3.7]:5701 [grid] [5.0-SNAPSHOT] null 
java.lang.NullPointerException: null
	at com.hazelcast.internal.util.AddressUtil.getAliases(AddressUtil.java:368)
	at com.hazelcast.internal.server.tcp.TcpServerConnection.addressAliases(TcpServerConnection.java:273)
	at com.hazelcast.internal.server.tcp.TcpServerConnection.close(TcpServerConnection.java:255)
	at com.hazelcast.internal.server.tcp.TcpServerConnectionChannelErrorHandler.onError(TcpServerConnectionChannelErrorHandler.java:51)
	at com.hazelcast.internal.networking.nio.NioPipeline.onError(NioPipeline.java:277)
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKey(NioThread.java:385)
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKeys(NioThread.java:368)
	at com.hazelcast.internal.networking.nio.NioThread.selectLoop(NioThread.java:294)
	at com.hazelcast.internal.networking.nio.NioThread.executeRun(NioThread.java:249)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
```

**Comment by neilstevenson** [comment]
This seems only to occur on Kubernetes.

**Comment by mmedenjak** [comment]
@neilstevenson do you have a reproducer for this?

**Comment by neilstevenson** [comment]
I do have a reproducer, but it's not minimal. Try https://github.com/hazelcast/hazelcast-platform-demos/tree/maintenance/banking/trade-monitor/hazelcast-node (in the `maintenance` branch, and just change from `5.0-BETA-1` to `5.0-SNAPSHOT`).

I think all you really need is `com.hazelcast:hazelcast:5.0-SNAPSHOT` and `com.hazelcast:hazelcast-kubernetes:jar:2.2.3`
and
```
  network:
    join:
      auto-detection:
        enabled: false
      multicast:
        enabled: false
      kubernetes:
        enabled: true
        service-dns: '@docker.image.prefix@-@my.cluster1.name@-hazelcast.default.svc.cluster.local'
    rest-api:
      enabled: true
      endpoint-groups:
        HEALTH_CHECK:
          enabled: true
```

**Comment by neilstevenson** [comment]
@mmedenjak Still occurs today, using above mentioned reproduce

```
09:41:44.094 INFO  main com.hazelcast.system - [10.104.3.14]:5701 [grid] [5.0-SNAPSHOT] Hazelcast Platform 5.0-SNAPSHOT (20210726 - 3972c6f) starting at [10.104.3.14]:5701 
```

& 

```
09:41:53.627 ERROR hz.confident_allen.IO.thread-in-0 c.h.i.s.t.TcpServerConnectionChannelErrorHandler - [10.104.3.14]:5701 [grid] [5.0-SNAPSHOT] null 
java.lang.NullPointerException: null
	at com.hazelcast.internal.util.AddressUtil.getAliases(AddressUtil.java:368)
	at com.hazelcast.internal.server.tcp.TcpServerConnection.addressAliases(TcpServerConnection.java:273)
	at com.hazelcast.internal.server.tcp.TcpServerConnection.close(TcpServerConnection.java:255)
	at com.hazelcast.internal.server.tcp.TcpServerConnectionChannelErrorHandler.onError(TcpServerConnectionChannelErrorHandler.java:51)
	at com.hazelcast.internal.networking.nio.NioPipeline.onError(NioPipeline.java:277)
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKey(NioThread.java:385)
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKeys(NioThread.java:368)
	at com.hazelcast.internal.networking.nio.NioThread.selectLoop(NioThread.java:294)
	at com.hazelcast.internal.networking.nio.NioThread.executeRun(NioThread.java:249)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
```

**Comment by mmedenjak** [comment]
Great, thanks.

**Comment by mmedenjak** [comment]
More discussion - https://hazelcast.slack.com/archives/C0356BG4R/p1627552634289300
