### ISSUE TITLE
Exception "Future.complete(Object) on completed future." on the attempt to shut down HZ instance or client.

### ISSUE THREAD

**Issue by slavagithub** [hazelcast/hazelcast#19164]
Exception "Future.complete(Object) on completed future." on the attempt to shut down HZ instance or client.

Reproduces in 30% of attempts.

Steps to reproduce:
1. Form cluster
2. Connect client or member
3. Call hz.shutdown() 

Result:
" Future.complete(Object) on completed future" exception in the log. Instance quits after some time finally.

Please see test result:
http://jenkins.hazelcast.com/view/Integration%20Tests/job/hostnames-fix-tests/25/testReport/junit/com.hazelcast.qe/HostnamesTest/testClusterWhenMembersSpecifiedViaHostnamesClientConnects/

Please find reproducer:
https://github.com/slavagithub/hazelcast-qe/blob/master/platform-it/hostnames-test/runner/src/test/java/com/hazelcast/qe/issues/Issue_5_FutureCompleteFailOnConnectionClose.java

Please see related issues:
https://github.com/hazelcast/hazelcast/issues/18862
https://github.com/hazelcast/hazelcast/pull/18870

Detailed log
Jul 23, 2021 10:18:36 AM com.hazelcast.client.impl.connection.tcp.TcpClientConnection
INFO: hz.client_1 [hostname-test] [5.0-SNAPSHOT] ClientConnection{alive=false, connectionId=1, channel=NioChannel{/127.0.0.1:51950->/127.0.0.1:5701}, remoteAddress=[172.28.1.1]:5701, lastReadTime=2021-07-23 10:18:32.490, lastWriteTime=2021-07-23 10:18:32.488, closedTime=2021-07-23 10:18:36.115, connected server version=5.0-SNAPSHOT} closed. Reason: Connection closed by the other side
Jul 23, 2021 10:18:36 AM com.hazelcast.client.impl.spi.ClientInvocationService
WARNING: hz.client_1 [hostname-test] [5.0-SNAPSHOT] Future.complete(Object) on completed future. Request: ClientMessage{connection=null, length=95, operation=Map.Put, isRetryable=false, correlationId=7, messageType=10100, isEvent=false, isfragmented=false}, current value: ExceptionalResult{cause=java.lang.InterruptedException}, offered value: ExceptionalResult{cause=com.hazelcast.spi.exception.TargetDisconnectedException: Connection closed by the other side}
java.lang.Exception
	at com.hazelcast.spi.impl.AbstractInvocationFuture.warnIfSuspiciousDoubleCompletion(AbstractInvocationFuture.java:1253)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.complete0(AbstractInvocationFuture.java:1230)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.completeExceptionallyInternal(AbstractInvocationFuture.java:1223)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.completeExceptionally(AbstractInvocationFuture.java:709)
	at com.hazelcast.client.impl.spi.impl.ClientInvocation.completeExceptionally(ClientInvocation.java:296)
	at com.hazelcast.client.impl.spi.impl.ClientInvocation.notifyExceptionWithOwnedPermission(ClientInvocation.java:323)
	at com.hazelcast.client.impl.spi.impl.ClientInvocationServiceImpl.onConnectionClose(ClientInvocationServiceImpl.java:221)
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.onConnectionClose(TcpClientConnectionManager.java:756)
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnection.close(TcpClientConnection.java:191)
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager$ClientConnectionChannelErrorHandler.onError(TcpClientConnectionManager.java:1138)
	at com.hazelcast.internal.networking.nio.NioPipeline.onError(NioPipeline.java:277)
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKey(NioThread.java:385)
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKeys(NioThread.java:368)
	at com.hazelcast.internal.networking.nio.NioThread.selectLoop(NioThread.java:294)
	at com.hazelcast.internal.networking.nio.NioThread.executeRun(NioThread.java:249)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)

Jul 23, 2021 10:18:36 AM com.hazelcast.client.impl.connection.ClientConnectionManager

**Comment by mmedenjak** [comment]
I believe I've been seeing this for a longer period - even in 4.2. @vbekiaris can you confirm this is a known issue?

**Comment by vbekiaris** [comment]
The double completion warning is logged commonly on member/client shut down and it has been this way since 3.x. On shutdown, pending invocation futures are completed exceptionally and it may be the case that another thread completes the future in the meanwhile -> double completion warning is logged. However these warnings are benign and they are not the cause of test failures.

@slavagithub in order to figure out what's wrong, I would change this line in `sanity(HazelcastInstance hz, int count)`:
```
System.out.println("Sanity fails with "+ ex.getMessage());
```

to print out the whole stack trace of the exception, not just the message. This way we can figure out why the `map.put` operation was interrupted in the first place.

**Comment by slavagithub** [comment]
Sure, make sense. Let me double-check

**Comment by slavagithub** [comment]
@vbekiaris please find a log with stack trace:
[awaitility-thread] ERROR com.hazelcast.qe.HostnamesTest - Sanity chek failed: 
com.hazelcast.core.HazelcastException: java.lang.InterruptedException
	at com.hazelcast.internal.util.ExceptionUtil.lambda$static$0(ExceptionUtil.java:56)
	at com.hazelcast.internal.util.ExceptionUtil.peel(ExceptionUtil.java:134)
	at com.hazelcast.internal.util.ExceptionUtil.peel(ExceptionUtil.java:77)
	at com.hazelcast.internal.util.ExceptionUtil.rethrow(ExceptionUtil.java:139)
	at com.hazelcast.client.impl.spi.ClientProxy.invokeOnPartition(ClientProxy.java:190)
	at com.hazelcast.client.impl.spi.ClientProxy.invoke(ClientProxy.java:182)
	at com.hazelcast.client.impl.proxy.ClientMapProxy.putInternal(ClientMapProxy.java:534)
	at com.hazelcast.client.impl.proxy.ClientMapProxy.put(ClientMapProxy.java:266)
	at com.hazelcast.qe.HostnamesTest.isDataExchangeAvailable(HostnamesTest.java:173)
	at com.hazelcast.qe.HostnamesTest.sanity(HostnamesTest.java:154)
	at com.hazelcast.qe.HostnamesTest.lambda$waitForClusterSanity$0(HostnamesTest.java:190)
	at org.awaitility.core.AssertionCondition$1.eval(AssertionCondition.java:55)
	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:190)
	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:177)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.InterruptedException
	at com.hazelcast.client.impl.spi.impl.ClientInvocationFuture.onInterruptDetected(ClientInvocationFuture.java:68)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:620)
	at com.hazelcast.client.impl.spi.ClientProxy.invokeOnPartition(ClientProxy.java:188)
	... 13 more
Stopping testclusterwhenmembersspecifiedviahostn
