### ISSUE TITLE
"java.util.NoSuchElementException" exception in the log on attempt to form TCP-IP cluster with incorrect "Public address" configuration. Second node can't start

### ISSUE THREAD

**Issue by slavagithub** [hazelcast/hazelcast#19166]
`java.util.NoSuchElementException` exception in the log on an attempt to form TCP-IP cluster with incorrect "Public address" configuration. The second node can't start

Steps to reproduce:
1. Set up  hz_1 node to use TCP-IP and  "Public IP"  set to 172.28.1.2. but the actual IP is 172.28.1.1
2. Set up hz_2 tries to use TCP-IP with member 172.28.1.1
3. Start instances

ACTUAL RESULT: 
hz_1: "java.util.NoSuchElementException" exception but it started
HZ_2: "java.lang.IllegalStateException: Node failed to start!"

EXPECTED RESULT:
hz_1 is not started with an error.
hz_2 started correctly.

REPRODUCER:
https://github.com/slavagithub/hazelcast-qe/blob/master/platform-it/hostnames-test/runner/src/test/java/com/hazelcast/qe/issues/Issue_3_Misconfiguration_ClusterIsNotFormedWIthStrangeError.java

Full log:
```
Creating network "resources_shared-2" with driver "bridge"
Creating resources_hz-1_1 ... done
Creating resources_hz-2_1 ... done
Attaching to resources_hz-2_1, resources_hz-1_1
hz-2_1  | 2021-07-21-16:15:56 [INFO] com.hazelcast.internal.config.AbstractConfigLocator Loading 'hazelcast.yml' from the working directory.
hz-2_1  | 2021-07-21-16:15:56 [WARNING] com.hazelcast.instance.AddressPicker [LOCAL] [hostname-test] [5.0-SNAPSHOT] Cannot resolve hostname: '4.internal'
hz-2_1  | 2021-07-21-16:15:56 [WARNING] com.hazelcast.instance.AddressPicker [LOCAL] [hostname-test] [5.0-SNAPSHOT] Cannot resolve hostname: '3.internal'
hz-2_1  | 2021-07-21-16:15:56 [WARNING] com.hazelcast.instance.AddressPicker [LOCAL] [hostname-test] [5.0-SNAPSHOT] You configured your member address as host name. Please be aware of that your dns can be spoofed. Make sure that your dns configurations are correct.
hz-2_1  | 2021-07-21-16:15:56 [INFO] com.hazelcast.instance.AddressPicker [LOCAL] [hostname-test] [5.0-SNAPSHOT] Resolving domain name '2.internal' to address(es): [172.29.1.1]
hz-2_1  | 2021-07-21-16:15:56 [INFO] com.hazelcast.instance.AddressPicker [LOCAL] [hostname-test] [5.0-SNAPSHOT] Interfaces is disabled, trying to pick one address from TCP-IP config addresses: [2.internal/172.29.1.1]
hz-2_1  | 2021-07-21-16:15:56 [WARNING] com.hazelcast.instance.AddressPicker [LOCAL] [hostname-test] [5.0-SNAPSHOT] Could not find a matching address to start with! Picking one of non-loopback addresses.
hz-2_1  | 2021-07-21-16:15:56 [INFO] com.hazelcast.system.logo [172.29.1.2]:5701 [hostname-test] [5.0-SNAPSHOT]
hz-2_1  |       +       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
hz-2_1  |       + +   + +  |    |    / \       /  |      |     /         / \    |         |
hz-2_1  |       + + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |
hz-2_1  |       + +   + +  |    |  /     \   /    |      |     \       /     \       |    |
hz-2_1  |       +       +  o    o o       o o---o o----o o----o o---o o       o o----o    o
hz-2_1  | 2021-07-21-16:15:56 [INFO] com.hazelcast.system [172.29.1.2]:5701 [hostname-test] [5.0-SNAPSHOT] Copyright (c) 2008-2021, Hazelcast, Inc. All Rights Reserved.
hz-2_1  | 2021-07-21-16:15:56 [INFO] com.hazelcast.system [172.29.1.2]:5701 [hostname-test] [5.0-SNAPSHOT] Hazelcast Platform 5.0-SNAPSHOT (20210720 - 6fc79c2) starting at [172.29.1.2]:5701
hz-2_1  | 2021-07-21-16:15:56 [INFO] com.hazelcast.system [172.29.1.2]:5701 [hostname-test] [5.0-SNAPSHOT] Cluster name: hostname-test
hz-2_1  | 2021-07-21-16:15:56 [INFO] com.hazelcast.system [172.29.1.2]:5701 [hostname-test] [5.0-SNAPSHOT] Jet is disabled. Enable it by setting the "hz.jet.enabled" property to true.
hz-1_1  | 2021-07-21-16:15:56 [INFO] com.hazelcast.internal.config.AbstractConfigLocator Loading 'hazelcast.yml' from the working directory.
hz-2_1  | 2021-07-21-16:15:57 [INFO] com.hazelcast.instance.impl.Node [172.29.1.2]:5701 [hostname-test] [5.0-SNAPSHOT] Using TCP/IP discovery
hz-2_1  | 2021-07-21-16:15:57 [WARNING] com.hazelcast.cp.CPSubsystem [172.29.1.2]:5701 [hostname-test] [5.0-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
hz-1_1  | 2021-07-21-16:15:57 [INFO] com.hazelcast.instance.AddressPicker [LOCAL] [hostname-test] [5.0-SNAPSHOT] Interfaces is disabled, trying to pick one address from TCP-IP config addresses: []
hz-1_1  | 2021-07-21-16:15:57 [WARNING] com.hazelcast.instance.AddressPicker [LOCAL] [hostname-test] [5.0-SNAPSHOT] Could not find a matching address to start with! Picking one of non-loopback addresses.
hz-1_1  | 2021-07-21-16:15:57 [INFO] com.hazelcast.instance.AddressPicker [LOCAL] [hostname-test] [5.0-SNAPSHOT] Using public address: [172.29.1.2]:5701
hz-1_1  | 2021-07-21-16:15:57 [INFO] com.hazelcast.system.logo [172.29.1.2]:5701 [hostname-test] [5.0-SNAPSHOT]
hz-1_1  |       +       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
hz-1_1  |       + +   + +  |    |    / \       /  |      |     /         / \    |         |
hz-1_1  |       + + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |
hz-1_1  |       + +   + +  |    |  /     \   /    |      |     \       /     \       |    |
hz-1_1  |       +       +  o    o o       o o---o o----o o----o o---o o       o o----o    o
hz-1_1  | 2021-07-21-16:15:57 [INFO] com.hazelcast.system [172.29.1.2]:5701 [hostname-test] [5.0-SNAPSHOT] Copyright (c) 2008-2021, Hazelcast, Inc. All Rights Reserved.
hz-1_1  | 2021-07-21-16:15:57 [INFO] com.hazelcast.system [172.29.1.2]:5701 [hostname-test] [5.0-SNAPSHOT] Hazelcast Platform 5.0-SNAPSHOT (20210720 - 6fc79c2) starting at [172.29.1.2]:5701
hz-1_1  | 2021-07-21-16:15:57 [INFO] com.hazelcast.system [172.29.1.2]:5701 [hostname-test] [5.0-SNAPSHOT] Cluster name: hostname-test
hz-1_1  | 2021-07-21-16:15:57 [INFO] com.hazelcast.system [172.29.1.2]:5701 [hostname-test] [5.0-SNAPSHOT] Jet is disabled. Enable it by setting the "hz.jet.enabled" property to true.
hz-2_1  | 2021-07-21-16:15:57 [INFO] com.hazelcast.internal.diagnostics.Diagnostics [172.29.1.2]:5701 [hostname-test] [5.0-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
hz-2_1  | 2021-07-21-16:15:57 [INFO] com.hazelcast.core.LifecycleService [172.29.1.2]:5701 [hostname-test] [5.0-SNAPSHOT] [172.29.1.2]:5701 is STARTING
hz-2_1  | 2021-07-21-16:15:57 [WARNING] com.hazelcast.internal.cluster.impl.TcpIpJoiner [172.29.1.2]:5701 [hostname-test] [5.0-SNAPSHOT] Cannot resolve hostname '4.internal'. Please make sure host is valid and reachable.
hz-2_1  | 2021-07-21-16:15:57 [WARNING] com.hazelcast.internal.cluster.impl.TcpIpJoiner [172.29.1.2]:5701 [hostname-test] [5.0-SNAPSHOT] Cannot resolve hostname '3.internal'. Please make sure host is valid and reachable.
hz-2_1  | 2021-07-21-16:15:57 [INFO] com.hazelcast.internal.cluster.impl.TcpIpJoiner [172.29.1.2]:5701 [hostname-test] [5.0-SNAPSHOT] [2.internal]:5703 is added to the blacklist.
hz-2_1  | 2021-07-21-16:15:57 [INFO] com.hazelcast.internal.cluster.impl.TcpIpJoiner [172.29.1.2]:5701 [hostname-test] [5.0-SNAPSHOT] [2.internal]:5702 is added to the blacklist.
hz-1_1  | 2021-07-21-16:15:57 [INFO] com.hazelcast.instance.impl.Node [172.29.1.2]:5701 [hostname-test] [5.0-SNAPSHOT] Using TCP/IP discovery
hz-1_1  | 2021-07-21-16:15:57 [WARNING] com.hazelcast.cp.CPSubsystem [172.29.1.2]:5701 [hostname-test] [5.0-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
hz-1_1  | 2021-07-21-16:15:57 [INFO] com.hazelcast.internal.diagnostics.Diagnostics [172.29.1.2]:5701 [hostname-test] [5.0-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
hz-1_1  | 2021-07-21-16:15:57 [INFO] com.hazelcast.core.LifecycleService [172.29.1.2]:5701 [hostname-test] [5.0-SNAPSHOT] [172.29.1.2]:5701 is STARTING
hz-1_1  | 2021-07-21-16:15:58 [INFO] com.hazelcast.internal.cluster.ClusterService [172.29.1.2]:5701 [hostname-test] [5.0-SNAPSHOT]
hz-1_1  |
hz-1_1  | Members {size:1, ver:1} [
hz-1_1  |       Member [172.29.1.2]:5701 - 29202fd0-955d-46d5-983e-9435a9c675dd this
hz-1_1  | ]
hz-1_1  |
hz-1_1  | 2021-07-21-16:15:58 [INFO] com.hazelcast.core.LifecycleService [172.29.1.2]:5701 [hostname-test] [5.0-SNAPSHOT] [172.29.1.2]:5701 is STARTED
hz-1_1  | 2021-07-21-16:15:58 [INFO] com.hazelcast.internal.server.tcp.TcpServerConnection [172.29.1.2]:5701 [hostname-test] [5.0-SNAPSHOT] Initialized new cluster connection between /172.29.1.1:5701 and /172.29.1.2:37853
hz-2_1  | 2021-07-21-16:15:58 [INFO] com.hazelcast.internal.server.tcp.TcpServerConnection [172.29.1.2]:5701 [hostname-test] [5.0-SNAPSHOT] Initialized new cluster connection between /172.29.1.2:37853 and 2.internal/172.29.1.1:5701
hz-1_1  | 2021-07-21-16:15:58 [WARNING] com.hazelcast.internal.cluster.impl.ClusterJoinManager [172.29.1.2]:5701 [hostname-test] [5.0-SNAPSHOT] New join request has been received from an existing endpoint Member [172.29.1.2]:5701 - 29202fd0-955d-46d5-983e-9435a9c675dd this. Removing old member and processing join request...
hz-1_1  | 2021-07-21-16:15:58 [INFO] com.hazelcast.internal.cluster.impl.MembershipManager [172.29.1.2]:5701 [hostname-test] [5.0-SNAPSHOT] Removing Member [172.29.1.2]:5701 - 29202fd0-955d-46d5-983e-9435a9c675dd this
hz-1_1  | 2021-07-21-16:15:58 [INFO] com.hazelcast.internal.partition.InternalPartitionService [172.29.1.2]:5701 [hostname-test] [5.0-SNAPSHOT] Fetching partition tables from cluster to determine the most recent one... Local stamp: 0
hz-1_1  | 2021-07-21-16:15:58 [INFO] com.hazelcast.internal.cluster.ClusterService [172.29.1.2]:5701 [hostname-test] [5.0-SNAPSHOT]
hz-1_1  |
hz-1_1  | Members {size:0, ver:2} [
hz-1_1  | ]
hz-1_1  |
hz-1_1  | 2021-07-21-16:15:58 [INFO] com.hazelcast.internal.partition.InternalPartitionService [172.29.1.2]:5701 [hostname-test] [5.0-SNAPSHOT] Most recent partition table is determined.
hz-1_1  | 2021-07-21-16:15:58 [INFO] com.hazelcast.transaction.TransactionManagerService [172.29.1.2]:5701 [hostname-test] [5.0-SNAPSHOT] Committing/rolling-back live transactions of [172.29.1.2]:5701, UUID: 29202fd0-955d-46d5-983e-9435a9c675dd
hz-1_1  | Exception in thread "hz.determined_saha.cached.thread-1" java.util.NoSuchElementException
hz-1_1  |       at com.hazelcast.internal.cluster.impl.MemberSelectingCollection$MemberSelectingIterator.next(MemberSelectingCollection.java:182)
hz-1_1  |       at com.hazelcast.internal.cluster.impl.MemberSelectingCollection$MemberSelectingIterator.next(MemberSelectingCollection.java:156)
hz-1_1  |       at com.hazelcast.internal.crdt.CRDTMigrationTask.run(CRDTMigrationTask.java:54)
hz-1_1  |       at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217)
hz-1_1  |       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
hz-1_1  |       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
hz-1_1  |       at java.base/java.lang.Thread.run(Thread.java:829)
hz-1_1  |       at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
hz-1_1  |       at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
hz-1_1  | 2021-07-21-16:16:02 [SEVERE] com.hazelcast.internal.cluster.impl.operations.JoinMastershipClaimOp [172.29.1.2]:5701 [hostname-test] [5.0-SNAPSHOT] Target is this node! -> [172.29.1.2]:5701
hz-1_1  | java.lang.IllegalArgumentException: Target is this node! -> [172.29.1.2]:5701
hz-1_1  |       at com.hazelcast.spi.impl.operationservice.impl.OutboundResponseHandler.checkTarget(OutboundResponseHandler.java:226)
hz-1_1  |       at com.hazelcast.spi.impl.operationservice.impl.OutboundResponseHandler.sendNormalResponse(OutboundResponseHandler.java:125)
hz-1_1  |       at com.hazelcast.spi.impl.operationservice.impl.OutboundResponseHandler.sendResponse(OutboundResponseHandler.java:101)
hz-1_1  |       at com.hazelcast.spi.impl.operationservice.Operation.sendResponse(Operation.java:506)
hz-1_1  |       at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:283)
hz-1_1  |       at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:249)
hz-1_1  |       at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:470)
hz-1_1  |       at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:197)
hz-1_1  |       at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:137)
hz-1_1  |       at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123)
hz-1_1  |       at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
hz-1_1  |

...

hz-1_1  |
hz-1_1  | 2021-07-21-16:20:47 [WARNING] com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl [172.29.1.2]:5701 [hostname-test] [5.0-SNAPSHOT] While sending op error... op: com.hazelcast.internal.cluster.impl.operations.JoinMastershipClaimOp{serviceName='hz:core:clusterService', identityHash=1421821617, partitionId=-1, replicaIndex=0, callId=20, invocationTime=1626884447555 (2021-07-21 16:20:47.555), waitTimeout=-1, callTimeout=60000, tenantControl=com.hazelcast.spi.impl.tenantcontrol.NoopTenantControl@0}, error: java.lang.IllegalArgumentException: Target is this node! -> [172.29.1.2]:5701
hz-1_1  | java.lang.IllegalArgumentException: Target is this node! -> [172.29.1.2]:5701, response: ErrorResponse{callId=20, urgent=true, cause=java.lang.IllegalArgumentException: Target is this node! -> [172.29.1.2]:5701}
hz-1_1  |       at com.hazelcast.spi.impl.operationservice.impl.OutboundResponseHandler.send(OutboundResponseHandler.java:113)
hz-1_1  |       at com.hazelcast.spi.impl.operationservice.impl.OutboundResponseHandler.sendResponse(OutboundResponseHandler.java:96)
hz-1_1  |       at com.hazelcast.spi.impl.operationservice.Operation.sendResponse(Operation.java:506)
hz-1_1  |       at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.sendResponseAfterOperationError(OperationRunnerImpl.java:426)
hz-1_1  |       at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.handleOperationError(OperationRunnerImpl.java:420)
hz-1_1  |       at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:254)
hz-1_1  |       at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:470)
hz-1_1  |       at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:197)
hz-1_1  |       at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:137)
hz-1_1  |       at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123)
hz-1_1  |       at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
hz-1_1  |
hz-2_1  | 2021-07-21-16:20:48 [INFO] com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor [172.29.1.2]:5701 [hostname-test] [5.0-SNAPSHOT] Invocations:9 timeouts:1 backup-timeouts:0
hz-2_1  | 2021-07-21-16:20:57 [SEVERE] com.hazelcast.instance.impl.Node [172.29.1.2]:5701 [hostname-test] [5.0-SNAPSHOT] Could not join cluster. Shutting down now!
hz-2_1  | 2021-07-21-16:20:57 [INFO] com.hazelcast.core.LifecycleService [172.29.1.2]:5701 [hostname-test] [5.0-SNAPSHOT] [172.29.1.2]:5701 is SHUTTING_DOWN
hz-2_1  | 2021-07-21-16:20:57 [WARNING] com.hazelcast.instance.impl.Node [172.29.1.2]:5701 [hostname-test] [5.0-SNAPSHOT] Terminating forcefully...
hz-2_1  | 2021-07-21-16:20:57 [INFO] com.hazelcast.instance.impl.Node [172.29.1.2]:5701 [hostname-test] [5.0-SNAPSHOT] Shutting down connection manager...
hz-2_1  | 2021-07-21-16:20:57 [INFO] com.hazelcast.internal.server.tcp.TcpServerConnection [172.29.1.2]:5701 [hostname-test] [5.0-SNAPSHOT] Connection[id=1, /172.29.1.2:37853->2.internal/172.29.1.1:5701, qualifier=null, endpoint=[2.internal]:5701, alive=false, connectionType=MEMBER, planeIndex=0] closed. Reason: TcpServer is stopping
hz-1_1  | 2021-07-21-16:20:57 [INFO] com.hazelcast.internal.server.tcp.TcpServerConnection [172.29.1.2]:5701 [hostname-test] [5.0-SNAPSHOT] Connection[id=1, /172.29.1.1:5701->/172.29.1.2:37853, qualifier=null, endpoint=[172.29.1.2]:5701, alive=false, connectionType=MEMBER, planeIndex=0] closed. Reason: Connection closed by the other side
hz-2_1  | 2021-07-21-16:20:57 [INFO] com.hazelcast.instance.impl.Node [172.29.1.2]:5701 [hostname-test] [5.0-SNAPSHOT] Shutting down node engine...
hz-2_1  | 2021-07-21-16:20:57 [INFO] com.hazelcast.instance.impl.NodeExtension [172.29.1.2]:5701 [hostname-test] [5.0-SNAPSHOT] Destroying node NodeExtension.
hz-2_1  | 2021-07-21-16:20:57 [INFO] com.hazelcast.instance.impl.Node [172.29.1.2]:5701 [hostname-test] [5.0-SNAPSHOT] Hazelcast Shutdown is completed in 29 ms.
hz-2_1  | 2021-07-21-16:20:57 [INFO] com.hazelcast.core.LifecycleService [172.29.1.2]:5701 [hostname-test] [5.0-SNAPSHOT] [172.29.1.2]:5701 is SHUTDOWN
hz-2_1  | 2021-07-21-16:20:57 [WARNING] com.hazelcast.internal.util.phonehome.PhoneHome [172.29.1.2]:5701 [hostname-test] [5.0-SNAPSHOT] Could not schedule phone home task! Most probably Hazelcast failed to start.
hz-2_1  | 2021-07-21-16:20:57 [INFO] com.hazelcast.instance.impl.Node [172.29.1.2]:5701 [hostname-test] [5.0-SNAPSHOT] Node is already shutting down... Waiting for shutdown process to complete...
hz-2_1  | Exception in thread "main" java.lang.IllegalStateException: Node failed to start!
hz-2_1  |       at com.hazelcast.instance.impl.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:126)
hz-2_1  |       at com.hazelcast.instance.impl.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:211)
hz-2_1  |       at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:190)
hz-2_1  |       at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:128)
hz-2_1  |       at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:95)
hz-2_1  |       at com.hazelcast.core.server.HazelcastMemberStarter.main(HazelcastMemberStarter.java:47)
resources_hz-2_1 exited with code 1
```

**Comment by fbarotov** [comment]
@slavagithub this seems like a duplicate of https://github.com/hazelcast/hazelcast/issues/19203
Shall we close it, or is there anything I missed?

**Comment by slavagithub** [comment]
@fbarotov yes, it seems it is dupulicating. Closing this one
