### ISSUE TITLE
com.hazelcast.jet.impl.deployment.ProcessorClassLoaderCleanupTest.processorClassLoaderRemovedAfterJobFinished fails on Windows, Oracle JDK 8

### ISSUE THREAD

**Issue by slavagithub** [hazelcast/hazelcast#19174]
mater, revafbee062bba410a246fd2b865360fe789824867a
Failed on Windows, Oracle JDK 8
http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Windows-OracleJDK8/302/testReport/

Stacktrace:
```
java.nio.file.InvalidPathException: Illegal char <:> at index 9: null\file:/C:/Jenkins/workspace/Hazelcast-master-Windows-OracleJDK8/hazelcast/target/classes/
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at java.nio.file.Paths.get(Paths.java:84)
	at com.hazelcast.jet.impl.JobExecutionService.lambda$createProcessorClassLoaders$5(JobExecutionService.java:228)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.hazelcast.jet.impl.JobExecutionService.createProcessorClassLoaders(JobExecutionService.java:234)
	at com.hazelcast.jet.impl.JobExecutionService.lambda$getProcessorClassLoaders$4(JobExecutionService.java:217)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at com.hazelcast.jet.impl.JobExecutionService.getProcessorClassLoaders(JobExecutionService.java:217)
	at com.hazelcast.jet.impl.JobExecutionService.prepareProcessorClassLoaders(JobExecutionService.java:199)
	at com.hazelcast.jet.impl.JobCoordinationService.deserializeJobDefinition(JobCoordinationService.java:1050)
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitJob$1(JobCoordinationService.java:238)
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$52(JobCoordinationService.java:1222)
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$53(JobCoordinationService.java:1243)
	at com.hazelcast.internal.util.executor.CompletableFutureTask.run(CompletableFutureTask.java:64)
	at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
```

Standard output:
```
15:23:33,486  INFO |processorClassLoaderRemovedAfterJobFinished| - [MetricsConfigHelper] Time-limited test - [LOCAL] [dev] [5.0-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
15:23:33,487  INFO |processorClassLoaderRemovedAfterJobFinished| - [logo] Time-limited test - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
15:23:33,487  INFO |processorClassLoaderRemovedAfterJobFinished| - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Copyright (c) 2008-2021, Hazelcast, Inc. All Rights Reserved.
15:23:33,487  INFO |processorClassLoaderRemovedAfterJobFinished| - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Hazelcast Platform 5.0-SNAPSHOT (20210725 - afbee06) starting at [127.0.0.1]:5701
15:23:33,487  INFO |processorClassLoaderRemovedAfterJobFinished| - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Cluster name: dev
15:23:33,493  INFO |processorClassLoaderRemovedAfterJobFinished| - [MetricsConfigHelper] Time-limited test - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
15:23:33,500  WARN |processorClassLoaderRemovedAfterJobFinished| - [CPSubsystem] Time-limited test - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
15:23:33,503  INFO |processorClassLoaderRemovedAfterJobFinished| - [JetServiceBackend] Time-limited test - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Setting number of cooperative threads and default parallelism to 2
15:23:33,504  INFO |processorClassLoaderRemovedAfterJobFinished| - [Diagnostics] Time-limited test - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
15:23:33,504  INFO |processorClassLoaderRemovedAfterJobFinished| - [LifecycleService] Time-limited test - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] [127.0.0.1]:5701 is STARTING
15:23:33,504  INFO |processorClassLoaderRemovedAfterJobFinished| - [ClusterService] Time-limited test - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] 

Members {size:1, ver:1} [
	Member [127.0.0.1]:5701 - 7c51c6ff-7c22-4ebd-87d8-27559f02e4ad this
]

15:23:33,504  INFO |processorClassLoaderRemovedAfterJobFinished| - [JetExtension] Time-limited test - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Jet is enabled
15:23:33,504  INFO |processorClassLoaderRemovedAfterJobFinished| - [LifecycleService] Time-limited test - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] [127.0.0.1]:5701 is STARTED
15:23:33,506 DEBUG |processorClassLoaderRemovedAfterJobFinished| - [JobCoordinationService] hz.sweet_rubin.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
15:23:33,515  INFO |processorClassLoaderRemovedAfterJobFinished| - [PartitionStateManager] hz.sweet_rubin.cached.thread-1 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Initializing cluster partition table arrangement...
15:23:33,517  WARN |processorClassLoaderRemovedAfterJobFinished| - [JobCoordinationService] hz.sweet_rubin.cached.thread-1 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] null
java.nio.file.InvalidPathException: Illegal char <:> at index 9: null\file:/C:/Jenkins/workspace/Hazelcast-master-Windows-OracleJDK8/hazelcast/target/classes/
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182) ~[?:1.8.0_172]
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153) ~[?:1.8.0_172]
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77) ~[?:1.8.0_172]
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94) ~[?:1.8.0_172]
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255) ~[?:1.8.0_172]
	at java.nio.file.Paths.get(Paths.java:84) ~[?:1.8.0_172]
	at com.hazelcast.jet.impl.JobExecutionService.lambda$createProcessorClassLoaders$5(JobExecutionService.java:228) ~[classes/:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_172]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:1.8.0_172]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_172]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_172]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_172]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_172]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_172]
	at com.hazelcast.jet.impl.JobExecutionService.createProcessorClassLoaders(JobExecutionService.java:234) ~[classes/:?]
	at com.hazelcast.jet.impl.JobExecutionService.lambda$getProcessorClassLoaders$4(JobExecutionService.java:217) ~[classes/:?]
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660) ~[?:1.8.0_172]
	at com.hazelcast.jet.impl.JobExecutionService.getProcessorClassLoaders(JobExecutionService.java:217) ~[classes/:?]
	at com.hazelcast.jet.impl.JobExecutionService.prepareProcessorClassLoaders(JobExecutionService.java:199) ~[classes/:?]
	at com.hazelcast.jet.impl.JobCoordinationService.deserializeJobDefinition(JobCoordinationService.java:1050) ~[classes/:?]
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitJob$1(JobCoordinationService.java:238) ~[classes/:?]
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$52(JobCoordinationService.java:1222) ~[classes/:?]
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$53(JobCoordinationService.java:1243) ~[classes/:?]
	at com.hazelcast.internal.util.executor.CompletableFutureTask.run(CompletableFutureTask.java:64) [classes/:?]
	at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217) [classes/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_172]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_172]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76) [classes/:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) [classes/:?]
15:23:33,898 DEBUG |processorClassLoaderRemovedAfterJobFinished| - [JobRepository] hz.sweet_rubin.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
15:23:33,904  INFO |processorClassLoaderRemovedAfterJobFinished| - [JetTestSupport] Time-limited test - Terminating instanceFactory in JetTestSupport.@After
15:23:33,904  INFO |processorClassLoaderRemovedAfterJobFinished| - [LifecycleService] Thread-44308 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
15:23:33,904  WARN |processorClassLoaderRemovedAfterJobFinished| - [Node] Thread-44308 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Terminating forcefully...
15:23:33,904  INFO |processorClassLoaderRemovedAfterJobFinished| - [Node] Thread-44308 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Shutting down connection manager...
15:23:33,904  INFO |processorClassLoaderRemovedAfterJobFinished| - [Node] Thread-44308 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Shutting down node engine...
15:23:33,906  INFO |processorClassLoaderRemovedAfterJobFinished| - [NodeExtension] Thread-44308 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Destroying node NodeExtension.
15:23:33,906  INFO |processorClassLoaderRemovedAfterJobFinished| - [Node] Thread-44308 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Hazelcast Shutdown is completed in 2 ms.
15:23:33,906  INFO |processorClassLoaderRemovedAfterJobFinished| - [LifecycleService] Thread-44308 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
BuildInfo right after processorClassLoaderRemovedAfterJobFinished(com.hazelcast.jet.impl.deployment.ProcessorClassLoaderCleanupTest): BuildInfo{version='5.0-SNAPSHOT', build='20210725', buildNumber=20210725, revision=afbee06, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'processorClassLoaderRemovedAfterJobFinished(com.hazelcast.jet.impl.deployment.ProcessorClassLoaderCleanupTest):'
15:23:30, accumulated pauses: 3865 ms, max pause: 387 ms, pauses over 1000 ms: 0

```

**Comment by mmedenjak** [comment]
@frant-hartm can you check this out?
