### ISSUE TITLE
com.hazelcast.map.impl.query.QueryIndexMigrationTest.testIndexCleanupOnMigration[copyBehavior: COPY_ON_READ] [HZ-1850]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#19178]
_master_ (commit afbee062bba410a246fd2b865360fe789824867a)

Failed on IBM JDK 8 and fips: http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-IbmJDK8-fips-nightly/315/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration_copyBehavior__COPY_ON_READ_/

Stacktrace:
```
java.util.concurrent.ExecutionException: java.lang.AssertionError: expected:<1> but was:<0>
	at java.util.concurrent.FutureTask.report(FutureTask.java:133)
	at java.util.concurrent.FutureTask.get(FutureTask.java:203)
	at com.hazelcast.map.impl.query.QueryIndexMigrationTest.testIndexCleanupOnMigration(QueryIndexMigrationTest.java:209)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.lang.Thread.run(Thread.java:822)
Caused by: java.lang.AssertionError: expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at com.hazelcast.map.impl.query.QueryIndexMigrationTest.updateMapAndRunQuery(QueryIndexMigrationTest.java:277)
	at com.hazelcast.map.impl.query.QueryIndexMigrationTest.access$100(QueryIndexMigrationTest.java:71)
	at com.hazelcast.map.impl.query.QueryIndexMigrationTest$3.run(QueryIndexMigrationTest.java:203)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:522)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	... 1 more
```

Standard output - no output, only `Metrics recorded during the test`

**Comment by olukas** [comment]
It failed also on `5.0.z` branch with IbmJDK8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-IbmJDK8-nightly/11/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration_copyBehavior__COPY_ON_READ_/

**Comment by slavagithub** [comment]
Test com.hazelcast.map.impl.query.QueryIndexMigrationTest.testQueryDuringAndAfterMigrationWithIndex fails with similar reason on IBM JDK8 fips - http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-IbmJDK8-fips-nightly/366/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testQueryDuringAndAfterMigrationWithIndex_copyBehavior__COPY_ON_READ_/

**Comment by slavagithub** [comment]
fails on master, Ibm JDK8 -http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-IbmJDK8-fips-nightly/388/testReport/junit/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration_copyBehavior__COPY_ON_READ_/

**Comment by olukas** [comment]
Failed on `master` on Ibm JDK 8 in FIPS mode: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-IbmJDK8-fips-nightly/425/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration_copyBehavior__COPY_ON_READ_/

**Comment by olukas** [comment]
Failed on `master` on Ibm JDK 8 in FIPS mode:
- https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-IbmJDK8-fips-nightly/437/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration_copyBehavior__COPY_ON_READ_/
- https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-IbmJDK8-fips-nightly/437/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testQueryDuringAndAfterMigrationWithIndex_copyBehavior__COPY_ON_READ_/

**Comment by ahmetmircik** [comment]
closing this by relying on latest cached partitions fix: https://github.com/hazelcast/hazelcast/pull/22725

**Comment by olukas** [comment]
Failed again on _master_ with ibm-11: https://jenkins.hazelcast.com/job/Hazelcast-master-Openj9-11-nightly/137/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testQueryDuringAndAfterMigrationWithIndex/

**Comment by AleksPeychev** [comment]
Failed in a different variant (testQueryWithIndexesWhileMigrating) on _master_ with oracle-17 (sonar build): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/525/testReport/junit/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testQueryWithIndexesWhileMigrating_copyBehavior__COPY_ON_READ_/

**Comment by Patras3** [comment]
This comment was automatically generated to summarize test results for the last 30 days.

```

For branch: master
Builds between : 2024-07-03 03:15 - 2024-07-31 03:15
Jobs: 11, Runs: 44, Passed: 38, Failed: 6, Skipped: 0, Fail Ratio: 13.64%
Run on:
+--------------------------------------------------+
| JDK        | PASSED | FAILED | SKIPPED |  RATIO  |
+--------------------------------------------------+
| unknown    |   12   |   4    |    0    |  25.00% |
| zing-21    |   3    |   1    |    0    |  25.00% |
| oracle-17  |   9    |   1    |    0    |  10.00% |
| openj9-21  |   3    |   0    |    0    |   0.00% |
| oracle-21  |   4    |   0    |    0    |   0.00% |
| zing-17    |   3    |   0    |    0    |   0.00% |
| openjdk-17 |   4    |   0    |    0    |   0.00% |
+--------------------------------------------------+
Note: Passing since 2024-07-24 03:15

Builds Timeline:
2024-07-31 03:15 - PASSED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK17-nightly-Esxi7/99/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration[copyBehavior: COPY_ON_READ]/
2024-07-31 03:08 - PASSED (oracle-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-OracleJDK21-nightly/28/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration[copyBehavior: COPY_ON_READ]/
2024-07-29 03:12 - PASSED (openj9-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-Openj9-21-nightly/29/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration[copyBehavior: COPY_ON_READ]/
2024-07-28 18:11 - PASSED (zing-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK21-nightly/32/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration[copyBehavior: COPY_ON_READ]/
2024-07-28 12:12 - PASSED (oracle-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-nightly-force-offload/111/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration[copyBehavior: COPY_ON_READ]/
2024-07-27 00:07 - PASSED (oracle-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-nightly-little-endian/89/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration[copyBehavior: COPY_ON_READ]/
2024-07-26 18:06 - PASSED (zing-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK17-nightly/91/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration[copyBehavior: COPY_ON_READ]/
2024-07-26 03:14 - PASSED (openjdk-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-ZuluJDK17-nightly/128/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration[copyBehavior: COPY_ON_READ]/
2024-07-24 21:52 - PASSED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-CorrettoJDK17-arm64-nightly/26/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration[copyBehavior: COPY_ON_READ]/
2024-07-24 03:15 - FIXED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK17-nightly-Esxi7/98/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration[copyBehavior: COPY_ON_READ]/
2024-07-24 03:08 - PASSED (oracle-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-OracleJDK21-nightly/27/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration[copyBehavior: COPY_ON_READ]/
2024-07-22 03:12 - PASSED (openj9-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-Openj9-21-nightly/28/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration[copyBehavior: COPY_ON_READ]/
2024-07-21 18:11 - FIXED (zing-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK21-nightly/31/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration[copyBehavior: COPY_ON_READ]/
2024-07-20 00:07 - FIXED (oracle-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-nightly-little-endian/88/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration[copyBehavior: COPY_ON_READ]/
2024-07-19 18:06 - PASSED (zing-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK17-nightly/90/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration[copyBehavior: COPY_ON_READ]/
2024-07-19 03:14 - PASSED (openjdk-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-ZuluJDK17-nightly/127/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration[copyBehavior: COPY_ON_READ]/
2024-07-17 03:15 - REGRESSION (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK17-nightly-Esxi7/97/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration[copyBehavior: COPY_ON_READ]/
2024-07-14 23:35 - FAILED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-sonar/539/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration[copyBehavior: COPY_ON_READ]/
2024-07-14 18:11 - REGRESSION (zing-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK21-nightly/30/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration[copyBehavior: COPY_ON_READ]/
2024-07-13 23:35 - FAILED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-sonar/538/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration[copyBehavior: COPY_ON_READ]/
2024-07-13 00:07 - REGRESSION (oracle-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-nightly-little-endian/87/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration[copyBehavior: COPY_ON_READ]/
2024-07-12 23:35 - REGRESSION (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-sonar/537/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration[copyBehavior: COPY_ON_READ]/
2024-07-12 03:14 - PASSED (openjdk-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-ZuluJDK17-nightly/126/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration[copyBehavior: COPY_ON_READ]/
2024-07-12 02:43 - PASSED (oracle-17):
    https://jenkins.hazelcast.com/job/Hazelcast-mono-OS-master-sonar/214/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration[copyBehavior: COPY_ON_READ]/
2024-07-11 23:35 - PASSED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-sonar/536/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration[copyBehavior: COPY_ON_READ]/
2024-07-11 02:43 - PASSED (oracle-17):
    https://jenkins.hazelcast.com/job/Hazelcast-mono-OS-master-sonar/213/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration[copyBehavior: COPY_ON_READ]/
2024-07-10 23:35 - PASSED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-sonar/535/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration[copyBehavior: COPY_ON_READ]/
2024-07-10 21:52 - PASSED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-CorrettoJDK17-arm64-nightly/24/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration[copyBehavior: COPY_ON_READ]/
2024-07-10 09:10 - PASSED (zing-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK21-nightly/29/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration[copyBehavior: COPY_ON_READ]/
2024-07-10 03:15 - PASSED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK17-nightly-Esxi7/96/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration[copyBehavior: COPY_ON_READ]/
2024-07-10 03:08 - PASSED (oracle-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-OracleJDK21-nightly/25/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration[copyBehavior: COPY_ON_READ]/
2024-07-10 02:43 - PASSED (oracle-17):
    https://jenkins.hazelcast.com/job/Hazelcast-mono-OS-master-sonar/212/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration[copyBehavior: COPY_ON_READ]/
2024-07-09 23:35 - PASSED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-sonar/534/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration[copyBehavior: COPY_ON_READ]/
2024-07-09 02:43 - PASSED (oracle-17):
    https://jenkins.hazelcast.com/job/Hazelcast-mono-OS-master-sonar/211/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration[copyBehavior: COPY_ON_READ]/
2024-07-08 23:35 - PASSED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-sonar/533/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration[copyBehavior: COPY_ON_READ]/
2024-07-08 03:12 - PASSED (openj9-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-Openj9-21-nightly/26/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration[copyBehavior: COPY_ON_READ]/
2024-07-08 02:43 - PASSED (oracle-17):
    https://jenkins.hazelcast.com/job/Hazelcast-mono-OS-master-sonar/210/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration[copyBehavior: COPY_ON_READ]/
2024-07-07 23:35 - PASSED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-sonar/532/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration[copyBehavior: COPY_ON_READ]/
2024-07-06 00:07 - PASSED (oracle-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-nightly-little-endian/86/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration[copyBehavior: COPY_ON_READ]/
2024-07-05 18:06 - PASSED (zing-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK17-nightly/88/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration[copyBehavior: COPY_ON_READ]/
2024-07-05 03:14 - PASSED (openjdk-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-ZuluJDK17-nightly/125/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration[copyBehavior: COPY_ON_READ]/
2024-07-03 21:52 - PASSED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-CorrettoJDK17-arm64-nightly/23/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration[copyBehavior: COPY_ON_READ]/
2024-07-03 03:28 - PASSED (oracle-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-OracleJDK21-nightly/24/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration[copyBehavior: COPY_ON_READ]/
2024-07-03 03:15 - PASSED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK17-nightly-Esxi7/95/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration[copyBehavior: COPY_ON_READ]/

----------------------------------------

For branch: 5.5.z
Builds between : 2024-07-31 18:08 - 2024-07-31 18:08
Jobs: 1, Runs: 1, Passed: 1, Failed: 0, Skipped: 0, Fail Ratio: 0.00%
Run on:
+--------------------------------------------------+
| JDK        | PASSED | FAILED | SKIPPED |  RATIO  |
+--------------------------------------------------+
| openjdk-17 |   1    |   0    |    0    |   0.00% |
+--------------------------------------------------+

Builds Timeline:
2024-07-31 18:08 - PASSED (openjdk-17):
    https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-ZuluJDK17-nightly/128/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration[copyBehavior: COPY_ON_READ]/

----------------------------------------

For branch: 5.4.z
Builds between : 2024-07-03 18:08 - 2024-07-29 18:02
Jobs: 3, Runs: 12, Passed: 12, Failed: 0, Skipped: 0, Fail Ratio: 0.00%
Run on:
+--------------------------------------------------+
| JDK        | PASSED | FAILED | SKIPPED |  RATIO  |
+--------------------------------------------------+
| openjdk-17 |   4    |   0    |    0    |   0.00% |
| oracle-21  |   4    |   0    |    0    |   0.00% |
| openj9-21  |   4    |   0    |    0    |   0.00% |
+--------------------------------------------------+

Builds Timeline:
2024-07-29 18:02 - PASSED (oracle-21):
    https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-OracleJDK21-nightly/14/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration[copyBehavior: COPY_ON_READ]/
2024-07-27 18:06 - PASSED (openj9-21):
    https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-Openj9-21-nightly/13/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration[copyBehavior: COPY_ON_READ]/
2024-07-24 18:08 - PASSED (openjdk-17):
    https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-ZuluJDK17-nightly/127/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration[copyBehavior: COPY_ON_READ]/
2024-07-22 18:02 - PASSED (oracle-21):
    https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-OracleJDK21-nightly/13/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration[copyBehavior: COPY_ON_READ]/
2024-07-20 18:06 - PASSED (openj9-21):
    https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-Openj9-21-nightly/12/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration[copyBehavior: COPY_ON_READ]/
2024-07-17 18:08 - PASSED (openjdk-17):
    https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-ZuluJDK17-nightly/126/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration[copyBehavior: COPY_ON_READ]/
2024-07-15 18:02 - PASSED (oracle-21):
    https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-OracleJDK21-nightly/12/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration[copyBehavior: COPY_ON_READ]/
2024-07-13 18:06 - PASSED (openj9-21):
    https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-Openj9-21-nightly/11/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration[copyBehavior: COPY_ON_READ]/
2024-07-10 18:08 - PASSED (openjdk-17):
    https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-ZuluJDK17-nightly/125/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration[copyBehavior: COPY_ON_READ]/
2024-07-08 18:02 - PASSED (oracle-21):
    https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-OracleJDK21-nightly/11/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration[copyBehavior: COPY_ON_READ]/
2024-07-06 18:06 - PASSED (openj9-21):
    https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-Openj9-21-nightly/10/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration[copyBehavior: COPY_ON_READ]/
2024-07-03 18:08 - PASSED (openjdk-17):
    https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-ZuluJDK17-nightly/124/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration[copyBehavior: COPY_ON_READ]/

----------------------------------------

For branch: 5.2.z
Builds between : 2024-07-06 03:10 - 2024-07-27 03:10
Jobs: 1, Runs: 4, Passed: 4, Failed: 0, Skipped: 0, Fail Ratio: 0.00%
Run on:
+------------------------------------------------+
| JDK      | PASSED | FAILED | SKIPPED |  RATIO  |
+------------------------------------------------+
| oracle-8 |   4    |   0    |    0    |   0.00% |
+------------------------------------------------+

Builds Timeline:
2024-07-27 03:10 - PASSED (oracle-8):
    https://jenkins.hazelcast.com/job/Hazelcast-5.2.z-OracleJDK8-nightly/63/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration[copyBehavior: COPY_ON_READ]/
2024-07-20 03:10 - PASSED (oracle-8):
    https://jenkins.hazelcast.com/job/Hazelcast-5.2.z-OracleJDK8-nightly/62/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration[copyBehavior: COPY_ON_READ]/
2024-07-13 03:10 - PASSED (oracle-8):
    https://jenkins.hazelcast.com/job/Hazelcast-5.2.z-OracleJDK8-nightly/61/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration[copyBehavior: COPY_ON_READ]/
2024-07-06 03:10 - PASSED (oracle-8):
    https://jenkins.hazelcast.com/job/Hazelcast-5.2.z-OracleJDK8-nightly/60/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration[copyBehavior: COPY_ON_READ]/

----------------------------------------

For branch: 4.2.z
Builds between : 2024-07-07 12:14 - 2024-07-28 12:14
Jobs: 1, Runs: 4, Passed: 4, Failed: 0, Skipped: 0, Fail Ratio: 0.00%
Run on:
+------------------------------------------------+
| JDK      | PASSED | FAILED | SKIPPED |  RATIO  |
+------------------------------------------------+
| oracle-8 |   4    |   0    |    0    |   0.00% |
+------------------------------------------------+

Builds Timeline:
2024-07-28 12:14 - PASSED (oracle-8):
    https://jenkins.hazelcast.com/job/Hazelcast-4.maintenance-OracleJDK8-nightly/1040/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration[copyBehavior: COPY_ON_READ]/
2024-07-21 12:14 - PASSED (oracle-8):
    https://jenkins.hazelcast.com/job/Hazelcast-4.maintenance-OracleJDK8-nightly/1039/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration[copyBehavior: COPY_ON_READ]/
2024-07-14 12:14 - PASSED (oracle-8):
    https://jenkins.hazelcast.com/job/Hazelcast-4.maintenance-OracleJDK8-nightly/1038/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration[copyBehavior: COPY_ON_READ]/
2024-07-07 12:14 - PASSED (oracle-8):
    https://jenkins.hazelcast.com/job/Hazelcast-4.maintenance-OracleJDK8-nightly/1037/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration[copyBehavior: COPY_ON_READ]/

----------------------------------------

For branch: 5.3.z
Builds between : 2024-07-08 03:11 - 2024-07-29 03:11
Jobs: 1, Runs: 4, Passed: 4, Failed: 0, Skipped: 0, Fail Ratio: 0.00%
Run on:
+------------------------------------------------+
| JDK      | PASSED | FAILED | SKIPPED |  RATIO  |
+------------------------------------------------+
| oracle-8 |   4    |   0    |    0    |   0.00% |
+------------------------------------------------+

Builds Timeline:
2024-07-29 03:11 - PASSED (oracle-8):
    https://jenkins.hazelcast.com/job/Hazelcast-5.3.z-OracleJDK8-nightly/13/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration[copyBehavior: COPY_ON_READ]/
2024-07-22 03:11 - PASSED (oracle-8):
    https://jenkins.hazelcast.com/job/Hazelcast-5.3.z-OracleJDK8-nightly/12/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration[copyBehavior: COPY_ON_READ]/
2024-07-15 03:11 - PASSED (oracle-8):
    https://jenkins.hazelcast.com/job/Hazelcast-5.3.z-OracleJDK8-nightly/11/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration[copyBehavior: COPY_ON_READ]/
2024-07-08 03:11 - PASSED (oracle-8):
    https://jenkins.hazelcast.com/job/Hazelcast-5.3.z-OracleJDK8-nightly/10/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration[copyBehavior: COPY_ON_READ]/

----------------------------------------
```

**Comment by AleksPeychev** [comment]
Failed again on _master_ with oracle-17 (sonar build): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-mono-OS-master-sonar/339/testReport/junit/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testQueryWithIndexesWhileMigrating_copyBehavior__COPY_ON_READ_/
