### ISSUE TITLE
Internal Error (classLoader.cpp:1217), pid=1983, tid=1984 guarantee(JImageResourcePath != NULL) failed: function JIMAGE_ResourcePath not found

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#19188]
did we hit a jvm bug ?

http://jenkins.hazelcast.com/view/hot-restart/job/hot-snapshot/176/console

/disk1/workspace/hot-snapshot/5.0-SNAPSHOT/2021_07_27-11_35_21/snapshot

```
(base) [ec2-user@ip-10-0-0-189 snapshot]$ find . -name out.txt | xargs grep starting
./out.txt:Timeout starting Jvm
./output/HzMember2HZ/out.txt:# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
./output/HzMember4HZ/out.txt:INFO: [10.0.0.90]:5701 [HZ] [5.0-SNAPSHOT] Hazelcast Enterprise 5.0-SNAPSHOT (20210727 - fe36bca, 4203898) starting at [10.0.0.90]:5701
./output/HzMember1HZ/out.txt:# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
```

hazelcast-use git@github.com:vbekiaris/hazelcast.git fixes/5.0b/beta-test-failures git@github.com:vbekiaris/hazelcast-enterprise.git fixes/5.0b/beta-test-failures

```
14:50:54 Installing core
14:50:54 installing /home/ec2-user/.m2/repository/com/hazelcast/hazelcast-enterprise/5.0-SNAPSHOT/hazelcast-enterprise-5.0-SNAPSHOT.jar
14:50:54 installing /home/ec2-user/.m2/repository/com/hazelcast/hazelcast-sql/5.0-SNAPSHOT/hazelcast-sql-5.0-SNAPSHOT.jar
14:50:54 HzMember4HZ Started 10.0.0.90 1980@ip-10-0-0-90.ec2.internal /home/ec2-user/hz-root/hz-lib/5.0-SNAPSHOT 
14:50:54 Timeout starting Jvm
14:50:55 /disk1/workspace/hot-snapshot/5.0-SNAPSHOT/2021_07_27-11_35_21/snapshot Passed
14:50:55 http://3.87.100.12/~workspace/hot-snapshot/5.0-SNAPSHOT/2021_07_27-11_35_21/snapshot

14:50:59 ./snapshot/output/HzMember2HZ/hs_err_pid1966.log
14:50:59 ./snapshot/output/HzMember1HZ/hs_err_pid1983.log
```

```
(base) [ec2-user@ip-10-0-0-189 snapshot]$ cat output/HzMember1HZ/hs_err_pid1983.log | more
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (classLoader.cpp:1217), pid=1983, tid=1984
#  guarantee(JImageResourcePath != NULL) failed: function JIMAGE_ResourcePath not found
#
# JRE version:  (11.0.12+7) (build )
# Java VM: OpenJDK 64-Bit Server VM (11.0.9+11-LTS, mixed mode, sharing, tiered, unknown gc, linux-aarch64)
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
#

---------------  S U M M A R Y ------------

Command Line:

Host: AArch64, 4 cores, 15G, Amazon Linux release 2 (Karoo)
Time: Tue Jul 27 11:35:54 2021 UTC elapsed time: 0.020248 seconds (0d 0h 0m 0s)

---------------  T H R E A D  ---------------

Current thread is native thread

Stack: [0x0000ffffa54ef000,0x0000ffffa56ef000],  sp=0x0000ffffa56e9c20,  free space=2027k
Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [libjvm.so+0xc7bae0]  VMError::report_and_die(int, char const*, char const*, std::__va_list, Thread*, unsigned char*, void*, void*, char const*, int, unsigned long)+0x2dc
V  [libjvm.so+0xc7c650]  VMError::report_and_die(Thread*, void*, char const*, int, char const*, char const*, std::__va_list)+0x50
V  [libjvm.so+0x5577c4]  report_vm_error(char const*, int, char const*, char const*, ...)+0xf4
V  [libjvm.so+0x496754]  ClassLoader::load_jimage_library()+0x3d4
V  [libjvm.so+0x497680]  ClassLoader::lookup_vm_options()+0x40
V  [libjvm.so+0x318674]  Arguments::parse(JavaVMInitArgs const*)+0x170
V  [libjvm.so+0xc100d4]  Threads::create_vm(JavaVMInitArgs*, bool*)+0xb0
V  [libjvm.so+0x7b3c60]  JNI_CreateJavaVM+0x70
C  [libjli.so+0x4d50]  JavaMain+0x80
C  [libjli.so+0x8dcc]  ThreadJavaMain+0xc
C  [libpthread.so.0+0x71ec]  start_thread+0xac

```

**Comment by Danny-Hazelcast** [comment]
maybe related ?

passing run 
http://jenkins.hazelcast.com/view/hot-restart/job/hot-bounce/321/console


failing run  
http://jenkins.hazelcast.com/view/hot-restart/job/hot-bounce/322/console

/disk1/workspace/hot-bounce/5.0-SNAPSHOT/2021_07_27-11_58_41/bounce

fail HzMember3HZ java.lang.IllegalStateException: Node failed to start!

```
java.lang.IllegalStateException: Node failed to start!
	at com.hazelcast.instance.impl.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:126)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:211)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:190)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:128)
	at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:61)
```


```
12:14:11 ERROR NodeExtension [main]:57 [10.0.0.78]:5701 [HZ] [5.0-SNAPSHOT] Hot Restart procedure failed
com.hazelcast.hotrestart.HotRestartException: Unexpected member is joined: Member [10.0.0.55]:5701 - 723f1ca4-89d8-4d8e-bd28-c7a77cb2010c. Restored members: [Member [10.0.0.73]:5701 - 57bd9c50-d308-4343-b92e-33a40d951105, Member [10.0.0.78]:5701 - 5082c695-5f58-4898-bc66-24cf65ece8b3 this]
	at com.hazelcast.internal.hotrestart.cluster.ClusterMetadataManager.failIfUnexpectedMemberJoins(ClusterMetadataManager.java:1112)
	at com.hazelcast.internal.hotrestart.cluster.ClusterMetadataManager.awaitUntilExpectedMembersJoin(ClusterMetadataManager.java:1092)
	at com.hazelcast.internal.hotrestart.cluster.ClusterMetadataManager.validate(ClusterMetadataManager.java:267)
	at com.hazelcast.internal.hotrestart.cluster.ClusterMetadataManager.start(ClusterMetadataManager.java:233)
	at com.hazelcast.internal.hotrestart.HotRestartIntegrationService.start(HotRestartIntegrationService.java:362)
	at com.hazelcast.instance.impl.EnterpriseNodeExtension.afterStart(EnterpriseNodeExtension.java:514)
	at com.hazelcast.instance.impl.Node.start(Node.java:480)
	at com.hazelcast.instance.impl.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:124)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:211)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:190)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:128)
	at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:61)
	at vendor.hz.java.HzControler.init(HzControler.java:31)
	at remote.main.Controler.startEmbeddedObject(Controler.java:52)
	at remote.command.StartEmbeddedObjectCmd.exicute(StartEmbeddedObjectCmd.java:18)
	at remote.main.Controler.run(Controler.java:184)
	at vendor.hz.java.HzMember.main(HzMember.java:9)
12:14:11 ERROR ClusterMetadataManager [hz.inspiring_spence.priority-generic-operation.thread-0]:57 [10.0.0.78]:5701 [HZ] [5.0-SNAPSHOT] Invalid expected members are received from master: [10.0.0.55]:5701, 723f1ca4-89d8-4d8e-bd28-c7a77cb2010c doesn't exist in restored members: [Member [10.0.0.73]:5701 - 57bd9c50-d308-4343-b92e-33a40d951105, Member [10.0.0.78]:5701 - 5082c695-5f58-4898-bc66-24cf65ece8b3 this]
12:14:11 INFO  HotRestartIntegrationService [main]:57 [10.0.0.78]:5701 [HZ] [5.0-SNAPSHOT] Shutting down hot-restart service.
12:14:11 WARN  Node [main]:57 [10.0.0.78]:5701 [HZ] [5.0-SNAPSHOT] Terminating forcefully...
12:14:11 DEBUG ClusterService [main]:57 [10.0.0.78]:5701 [HZ] [5.0-SNAPSHOT] Setting master address to null
12:14:11 INFO  Node [main]:57 [10.0.0.78]:5701 [HZ] [5.0-SNAPSHOT] Shutting down connection manager...
12:14:11 INFO  TcpServerConnection [main]:57 [10.0.0.78]:5701 [HZ] [5.0-SNAPSHOT] Connection[id=7, /10.0.0.78:5701->/10.0.0.55:52531, qualifier=null, endpoint=[10.0.0.55]:5701, alive=false, connectionType=MEMBER, planeIndex=0] closed. Reason: TcpServer is stopping
12:14:11 INFO  TcpServerConnection [main]:57 [10.0.0.78]:5701 [HZ] [5.0-SNAPSHOT] Connection[id=8, /10.0.0.78:5701->/10.0.0.73:47921, qualifier=null, endpoint=[10.0.0.73]:5701, alive=false, connectionType=MEMBER, planeIndex=0] closed. Reason: TcpServer is stopping
12:14:11 INFO  TcpServerConnection [main]:57 [10.0.0.78]:5701 [HZ] [5.0-SNAPSHOT] Connection[id=1, /10.0.0.78:5701->/10.0.0.78:49937, qualifier=null, endpoint=null, alive=false, connectionType=JVM, planeIndex=-1] closed. Reason: TcpServer is stopping
12:14:11 INFO  TcpServerConnection [main]:57 [10.0.0.78]:5701 [HZ] [5.0-SNAPSHOT] Connection[id=2, /10.0.0.78:5701->/10.0.0.55:52183, qualifier=null, endpoint=null, alive=false, connectionType=JVM, planeIndex=-1] closed. Reason: TcpServer is stopping
12:14:11 INFO  TcpServerConnection [main]:57 [10.0.0.78]:5701 [HZ] [5.0-SNAPSHOT] Connection[id=3, /10.0.0.78:5701->/10.0.0.73:41461, qualifier=null, endpoint=null, alive=false, connectionType=JVM, planeIndex=-1] closed. Reason: TcpServer is stopping
12:14:11 INFO  TcpServerConnection [main]:57 [10.0.0.78]:5701 [HZ] [5.0-SNAPSHOT] Connection[id=4, /10.0.0.78:5701->/10.0.0.78:41819, qualifier=null, endpoint=null, alive=false, connectionType=JVM, planeIndex=-1] closed. Reason: TcpServer is stopping
12:14:11 INFO  TcpServerConnection [main]:57 [10.0.0.78]:5701 [HZ] [5.0-SNAPSHOT] Connection[id=5, /10.0.0.78:5701->/10.0.0.73:58563, qualifier=null, endpoint=null, alive=false, connectionType=JVM, planeIndex=-1] closed. Reason: TcpServer is stopping
12:14:11 INFO  TcpServerConnection [main]:57 [10.0.0.78]:5701 [HZ] [5.0-SNAPSHOT] Connection[id=6, /10.0.0.78:5701->/10.0.0.55:51501, qualifier=null, endpoint=null, alive=false, connectionType=JVM, planeIndex=-1] closed. Reason: TcpServer is stopping
12:14:11 INFO  Node [main]:57 [10.0.0.78]:5701 [HZ] [5.0-SNAPSHOT] Shutting down node engine...
12:14:11 DEBUG ClusterService [main]:57 [10.0.0.78]:5701 [HZ] [5.0-SNAPSHOT] Setting master address to null
12:14:11 INFO  NodeExtension [main]:57 [10.0.0.78]:5701 [HZ] [5.0-SNAPSHOT] Destroying node NodeExtension.
12:14:11 INFO  Node [main]:57 [10.0.0.78]:5701 [HZ] [5.0-SNAPSHOT] Hazelcast Shutdown is completed in 18 ms.
12:14:11 INFO  Node [main]:57 [10.0.0.78]:5701 [HZ] [5.0-SNAPSHOT] Node is already shutting down... Waiting for shutdown process to complete...
java.lang.IllegalStateException: Node failed to start!
```

**Comment by Danny-Hazelcast** [comment]
java updated in aws AMI updated while starting jvm
