### ISSUE TITLE
Hazelcast 5.0-BETA-1 fails to start on MacOS

### ISSUE THREAD

**Issue by dbrimley** [hazelcast/hazelcast#19192]
**Describe the bug**
1. Downloaded the hazelcast 5.0-BETA-1 zip file.
2. start a member using bin/hz-start using the default XML files in /config

Error is thrown to the console...

```
java.net.SocketException: Can't assign requested address
	at java.net.PlainDatagramSocketImpl.join(Native Method) ~[?:1.8.0_162]
	at java.net.AbstractPlainDatagramSocketImpl.join(AbstractPlainDatagramSocketImpl.java:178) ~[?:1.8.0_162]
	at java.net.MulticastSocket.joinGroup(MulticastSocket.java:323) ~[?:1.8.0_162]
	at com.hazelcast.internal.cluster.impl.MulticastService.configureMulticastSocket(MulticastService.java:169) ~[hazelcast-5.0-BETA-1.jar:5.0-BETA-1]
	at com.hazelcast.internal.cluster.impl.MulticastService.createMulticastService(MulticastService.java:114) [hazelcast-5.0-BETA-1.jar:5.0-BETA-1]
	at com.hazelcast.instance.impl.Node.<init>(Node.java:265) [hazelcast-5.0-BETA-1.jar:5.0-BETA-1]
	at com.hazelcast.instance.impl.HazelcastInstanceImpl.createNode(HazelcastInstanceImpl.java:149) [hazelcast-5.0-BETA-1.jar:5.0-BETA-1]
	at com.hazelcast.instance.impl.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:118) [hazelcast-5.0-BETA-1.jar:5.0-BETA-1]
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:211) [hazelcast-5.0-BETA-1.jar:5.0-BETA-1]
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:190) [hazelcast-5.0-BETA-1.jar:5.0-BETA-1]
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:128) [hazelcast-5.0-BETA-1.jar:5.0-BETA-1]
	at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:95) [hazelcast-5.0-BETA-1.jar:5.0-BETA-1]
	at com.hazelcast.core.server.HazelcastMemberStarter.main(HazelcastMemberStarter.java:47) [hazelcast-5.0-BETA-1.jar:5.0-BETA-1]
```

[logs.txt](https://github.com/hazelcast/hazelcast/files/6886259/logs.txt)

I am using

Java 8 on MacOS Catalina v 10.15.7

I downloaded the latest 4.2.1 and used `start.sh` and it works fine.

**Comment by neilstevenson** [comment]
Related - https://github.com/hazelcast/hazelcast/issues/18941

**Comment by mmedenjak** [comment]
possibly related to changes in 5.0 - https://hazelcast.slack.com/archives/C034YQBTG/p1624345987229400?thread_ts=1624264124.217600&cid=C034YQBTG

**Comment by slavagithub** [comment]
java 8, MacOS 10.14.6
The same exception but node is correctly started:
Members {size:1, ver:1} [
	Member [10.212.134.150]:5701 - 2c39d798-e878-4bde-85c5-8fd557fca936 this
]

2021-07-28 11:27:26,267 [ INFO] [main] [c.h.i.i.JetExtension]: [10.212.134.150]:5701 [dev] [5.0-BETA-1] Jet is enabled
2021-07-28 11:27:26,269 [ INFO] [main] [c.h.c.LifecycleService]: [10.212.134.150]:5701 [dev] [5.0-BETA-1] [10.212.134.150]:5701 is STARTED

**Comment by dbrimley** [comment]
@slavagithub What happens when you try to form a cluster with a second node.  I found it started ok, but then wouldn't form a cluster.

**Comment by slavagithub** [comment]
@dbrimley the same - secod note is started but cluster is not formed!

**Comment by ahmetmircik** [comment]
with jdk-15.0.1, i see no error and nodes form cluster.

**Comment by kwart** [comment]
The problem here is that the `MulticastSocket.setInterface` is not called. It can be workarounded by setting the attribute value `loopbackModeEnabled` to `false` (in multicast join configuration). Or by forcing the call by using the System property `-Dhazelcast.multicast.socket.set.interface=true`

The simplest fix could be to change the `MulticastConfig.DEFAULT_LOOPBACK_MODE_ENABLED` value to `false`.

As always with the multicast - any fix chosen deserves proper testing on all platforms...
