### ISSUE TITLE
com.hazelcast.map.EvictionMaxSizePolicyTest.testPerNodePolicy_afterGracefulShutdown

### ISSUE THREAD

**Issue by mdumandag** [hazelcast/hazelcast#19206]
Failed on PR builder against 4.2.z http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/6374/testReport/junit/com.hazelcast.map/EvictionMaxSizePolicyTest/testPerNodePolicy_afterGracefulShutdown/

Stacktrace:
```
java.lang.AssertionError: initialMapSize=2971, evictedKeyCount=874, map size is 2097 and it should be smaller than maxPartitionSize * PARTITION_COUNT which is 3000
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at com.hazelcast.map.EvictionMaxSizePolicyTest.lambda$testPerNodePolicy_afterGracefulShutdown$1(EvictionMaxSizePolicyTest.java:131)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1247)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1349)
	at com.hazelcast.map.EvictionMaxSizePolicyTest.testPerNodePolicy_afterGracefulShutdown(EvictionMaxSizePolicyTest.java:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

Standard output:
```
Finished Running Test: testOwnerAndBackupEntryCountsAreEqualAfterEviction_whenPerNodeMaxSizePolicyIsUsed in 0.979 seconds.
07:36:13,757  INFO |testPerNodePolicy_afterGracefulShutdown| - [MockServer] testPerNodePolicy_afterGracefulShutdown - [127.0.0.1]:5703 [dev] [4.2.2-SNAPSHOT] Created connection to endpoint: [127.0.0.1]:5702, connection: MockConnection{localEndpoint=[127.0.0.1]:5703, remoteEndpoint=[127.0.0.1]:5702, alive=true}
07:36:13,758  INFO |testPerNodePolicy_afterGracefulShutdown| - [LifecycleService] testPerNodePolicy_afterGracefulShutdown - [127.0.0.1]:5703 [dev] [4.2.2-SNAPSHOT] [127.0.0.1]:5703 is STARTED
07:36:13,758  INFO |testPerNodePolicy_afterGracefulShutdown| - [PartitionStateManager] hz.youthful_edison.priority-generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [4.2.2-SNAPSHOT] Initializing cluster partition table arrangement...
07:36:14,461  INFO |testPerNodePolicy_afterGracefulShutdown| - [LifecycleService] testPerNodePolicy_afterGracefulShutdown - [127.0.0.1]:5703 [dev] [4.2.2-SNAPSHOT] [127.0.0.1]:5703 is SHUTTING_DOWN
07:36:14,461  INFO |testPerNodePolicy_afterGracefulShutdown| - [MigrationManager] hz.youthful_edison.priority-generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [4.2.2-SNAPSHOT] Shutdown request of Member [127.0.0.1]:5703 - 2e126951-3463-4e56-9463-2fde841a803b is handled
07:36:14,482  INFO |testPerNodePolicy_afterGracefulShutdown| - [MigrationManager] hz.youthful_edison.migration - [127.0.0.1]:5701 [dev] [4.2.2-SNAPSHOT] Repartitioning cluster data. Migration tasks count: 181
07:36:14,623  INFO |testPerNodePolicy_afterGracefulShutdown| - [MigrationManager] hz.youthful_edison.migration - [127.0.0.1]:5701 [dev] [4.2.2-SNAPSHOT] All migration tasks have been completed. (repartitionTime=Wed Jul 28 07:36:14 UTC 2021, plannedMigrations=181, completedMigrations=181, remainingMigrations=0, totalCompletedMigrations=181, elapsedMigrationOperationTime=552ms, totalElapsedMigrationOperationTime=552ms, elapsedDestinationCommitTime=247ms, totalElapsedDestinationCommitTime=247ms, elapsedMigrationTime=1290ms, totalElapsedMigrationTime=1290ms)
07:36:14,624  INFO |testPerNodePolicy_afterGracefulShutdown| - [Node] testPerNodePolicy_afterGracefulShutdown - [127.0.0.1]:5703 [dev] [4.2.2-SNAPSHOT] Shutting down connection manager...
07:36:14,624  INFO |testPerNodePolicy_afterGracefulShutdown| - [MockServer] testPerNodePolicy_afterGracefulShutdown - [127.0.0.1]:5702 [dev] [4.2.2-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5703, connection: MockConnection{localEndpoint=[127.0.0.1]:5702, remoteEndpoint=[127.0.0.1]:5703, alive=false}
07:36:14,624  INFO |testPerNodePolicy_afterGracefulShutdown| - [MockServer] testPerNodePolicy_afterGracefulShutdown - [127.0.0.1]:5703 [dev] [4.2.2-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5702, connection: MockConnection{localEndpoint=[127.0.0.1]:5703, remoteEndpoint=[127.0.0.1]:5702, alive=false}
07:36:14,624  INFO |testPerNodePolicy_afterGracefulShutdown| - [MockServer] testPerNodePolicy_afterGracefulShutdown - [127.0.0.1]:5701 [dev] [4.2.2-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5703, connection: MockConnection{localEndpoint=[127.0.0.1]:5701, remoteEndpoint=[127.0.0.1]:5703, alive=false}
07:36:14,624  INFO |testPerNodePolicy_afterGracefulShutdown| - [MockServer] testPerNodePolicy_afterGracefulShutdown - [127.0.0.1]:5703 [dev] [4.2.2-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5701, connection: MockConnection{localEndpoint=[127.0.0.1]:5703, remoteEndpoint=[127.0.0.1]:5701, alive=false}
07:36:14,624  WARN |testPerNodePolicy_afterGracefulShutdown| - [MembershipManager] testPerNodePolicy_afterGracefulShutdown - [127.0.0.1]:5702 [dev] [4.2.2-SNAPSHOT] Member [127.0.0.1]:5703 - 2e126951-3463-4e56-9463-2fde841a803b is suspected to be dead for reason: Connection manager is stopped on Member [127.0.0.1]:5703 - 2e126951-3463-4e56-9463-2fde841a803b this
07:36:14,624  INFO |testPerNodePolicy_afterGracefulShutdown| - [MembershipManager] testPerNodePolicy_afterGracefulShutdown - [127.0.0.1]:5701 [dev] [4.2.2-SNAPSHOT] Removing Member [127.0.0.1]:5703 - 2e126951-3463-4e56-9463-2fde841a803b
07:36:14,624  INFO |testPerNodePolicy_afterGracefulShutdown| - [ClusterService] testPerNodePolicy_afterGracefulShutdown - [127.0.0.1]:5701 [dev] [4.2.2-SNAPSHOT] 

Members {size:2, ver:4} [
	Member [127.0.0.1]:5701 - 45d194be-c19d-46a3-99cd-dc8063e32272 this
	Member [127.0.0.1]:5702 - b69f8cbf-c9c6-407c-86c1-068a849af8cf
]

07:36:14,624  INFO |testPerNodePolicy_afterGracefulShutdown| - [TransactionManagerService] hz.youthful_edison.cached.thread-5 - [127.0.0.1]:5701 [dev] [4.2.2-SNAPSHOT] Committing/rolling-back live transactions of [127.0.0.1]:5703, UUID: 2e126951-3463-4e56-9463-2fde841a803b
07:36:14,624  INFO |testPerNodePolicy_afterGracefulShutdown| - [Node] testPerNodePolicy_afterGracefulShutdown - [127.0.0.1]:5703 [dev] [4.2.2-SNAPSHOT] Shutting down node engine...
07:36:14,625  INFO |testPerNodePolicy_afterGracefulShutdown| - [ClusterService] hz.musing_edison.priority-generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [4.2.2-SNAPSHOT] 

Members {size:2, ver:4} [
	Member [127.0.0.1]:5701 - 45d194be-c19d-46a3-99cd-dc8063e32272
	Member [127.0.0.1]:5702 - b69f8cbf-c9c6-407c-86c1-068a849af8cf this
]

07:36:14,625  INFO |testPerNodePolicy_afterGracefulShutdown| - [TransactionManagerService] hz.musing_edison.cached.thread-2 - [127.0.0.1]:5702 [dev] [4.2.2-SNAPSHOT] Committing/rolling-back live transactions of [127.0.0.1]:5703, UUID: 2e126951-3463-4e56-9463-2fde841a803b
07:36:14,635  INFO |testPerNodePolicy_afterGracefulShutdown| - [NodeExtension] testPerNodePolicy_afterGracefulShutdown - [127.0.0.1]:5703 [dev] [4.2.2-SNAPSHOT] Destroying node NodeExtension.
07:36:14,635  INFO |testPerNodePolicy_afterGracefulShutdown| - [Node] testPerNodePolicy_afterGracefulShutdown - [127.0.0.1]:5703 [dev] [4.2.2-SNAPSHOT] Hazelcast Shutdown is completed in 174 ms.
07:36:14,635  INFO |testPerNodePolicy_afterGracefulShutdown| - [LifecycleService] testPerNodePolicy_afterGracefulShutdown - [127.0.0.1]:5703 [dev] [4.2.2-SNAPSHOT] [127.0.0.1]:5703 is SHUTDOWN
07:36:14,640  INFO |testPerNodePolicy_afterGracefulShutdown| - [MigrationManager] hz.youthful_edison.migration - [127.0.0.1]:5701 [dev] [4.2.2-SNAPSHOT] Partition balance is ok, no need to repartition.
07:36:33,249  INFO |testPerNodePolicy_afterGracefulShutdown| - [HealthMonitor] hz.musing_edison.HealthMonitor - [127.0.0.1]:5702 [dev] [4.2.2-SNAPSHOT] processors=16, physical.memory.total=377.6G, physical.memory.free=53.6G, swap.space.total=4.0G, swap.space.free=4.0G, heap.memory.used=835.4M, heap.memory.free=819.1M, heap.memory.total=1.6G, heap.memory.max=1.8G, heap.memory.used/total=50.49%, heap.memory.used/max=45.89%, minor.gc.count=267, minor.gc.time=9198ms, major.gc.count=5, major.gc.time=1342ms, load.process=0.00%, load.system=33.33%, load.systemAverage=26.40, thread.count=131, thread.peakCount=1305, cluster.timeDiff=-1, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=19013, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=1, clientEndpoint.count=0, connection.active.count=0, client.connection.count=0, connection.count=0
07:37:53,255  INFO |testPerNodePolicy_afterGracefulShutdown| - [HealthMonitor] hz.musing_edison.HealthMonitor - [127.0.0.1]:5702 [dev] [4.2.2-SNAPSHOT] processors=16, physical.memory.total=377.6G, physical.memory.free=62.5G, swap.space.total=4.0G, swap.space.free=4.0G, heap.memory.used=845.6M, heap.memory.free=816.4M, heap.memory.total=1.6G, heap.memory.max=1.8G, heap.memory.used/total=50.88%, heap.memory.used/max=46.45%, minor.gc.count=268, minor.gc.time=9215ms, major.gc.count=5, major.gc.time=1342ms, load.process=0.00%, load.system=50.00%, load.systemAverage=28.33, thread.count=138, thread.peakCount=1305, cluster.timeDiff=-8, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=82956, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=1, clientEndpoint.count=0, connection.active.count=0, client.connection.count=0, connection.count=0
07:38:14,909  INFO |testPerNodePolicy_afterGracefulShutdown| - [LifecycleService] Thread-4899 - [127.0.0.1]:5703 [dev] [4.2.2-SNAPSHOT] [127.0.0.1]:5703 is SHUTTING_DOWN
07:38:14,909  INFO |testPerNodePolicy_afterGracefulShutdown| - [Node] Thread-4899 - [127.0.0.1]:5703 [dev] [4.2.2-SNAPSHOT] Node is already shutting down... Waiting for shutdown process to complete...
07:38:14,909  INFO |testPerNodePolicy_afterGracefulShutdown| - [LifecycleService] Thread-4899 - [127.0.0.1]:5703 [dev] [4.2.2-SNAPSHOT] [127.0.0.1]:5703 is SHUTDOWN
07:38:14,909  INFO |testPerNodePolicy_afterGracefulShutdown| - [LifecycleService] Thread-4899 - [127.0.0.1]:5702 [dev] [4.2.2-SNAPSHOT] [127.0.0.1]:5702 is SHUTTING_DOWN
07:38:14,909  WARN |testPerNodePolicy_afterGracefulShutdown| - [Node] Thread-4899 - [127.0.0.1]:5702 [dev] [4.2.2-SNAPSHOT] Terminating forcefully...
07:38:14,909  INFO |testPerNodePolicy_afterGracefulShutdown| - [Node] Thread-4899 - [127.0.0.1]:5702 [dev] [4.2.2-SNAPSHOT] Shutting down connection manager...
07:38:14,909  INFO |testPerNodePolicy_afterGracefulShutdown| - [MockServer] Thread-4899 - [127.0.0.1]:5701 [dev] [4.2.2-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5702, connection: MockConnection{localEndpoint=[127.0.0.1]:5701, remoteEndpoint=[127.0.0.1]:5702, alive=false}
07:38:14,909  INFO |testPerNodePolicy_afterGracefulShutdown| - [MockServer] Thread-4899 - [127.0.0.1]:5702 [dev] [4.2.2-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5701, connection: MockConnection{localEndpoint=[127.0.0.1]:5702, remoteEndpoint=[127.0.0.1]:5701, alive=false}
07:38:14,909  INFO |testPerNodePolicy_afterGracefulShutdown| - [MembershipManager] Thread-4899 - [127.0.0.1]:5701 [dev] [4.2.2-SNAPSHOT] Removing Member [127.0.0.1]:5702 - b69f8cbf-c9c6-407c-86c1-068a849af8cf
07:38:14,910  INFO |testPerNodePolicy_afterGracefulShutdown| - [ClusterService] Thread-4899 - [127.0.0.1]:5701 [dev] [4.2.2-SNAPSHOT] 

Members {size:1, ver:5} [
	Member [127.0.0.1]:5701 - 45d194be-c19d-46a3-99cd-dc8063e32272 this
]

07:38:14,910  INFO |testPerNodePolicy_afterGracefulShutdown| - [Node] Thread-4899 - [127.0.0.1]:5702 [dev] [4.2.2-SNAPSHOT] Shutting down node engine...
07:38:14,910  INFO |testPerNodePolicy_afterGracefulShutdown| - [TransactionManagerService] hz.youthful_edison.cached.thread-7 - [127.0.0.1]:5701 [dev] [4.2.2-SNAPSHOT] Committing/rolling-back live transactions of [127.0.0.1]:5702, UUID: b69f8cbf-c9c6-407c-86c1-068a849af8cf
07:38:14,919  INFO |testPerNodePolicy_afterGracefulShutdown| - [NodeExtension] Thread-4899 - [127.0.0.1]:5702 [dev] [4.2.2-SNAPSHOT] Destroying node NodeExtension.
07:38:14,919  INFO |testPerNodePolicy_afterGracefulShutdown| - [Node] Thread-4899 - [127.0.0.1]:5702 [dev] [4.2.2-SNAPSHOT] Hazelcast Shutdown is completed in 10 ms.
07:38:14,919  INFO |testPerNodePolicy_afterGracefulShutdown| - [LifecycleService] Thread-4899 - [127.0.0.1]:5702 [dev] [4.2.2-SNAPSHOT] [127.0.0.1]:5702 is SHUTDOWN
07:38:14,919  INFO |testPerNodePolicy_afterGracefulShutdown| - [LifecycleService] Thread-4899 - [127.0.0.1]:5701 [dev] [4.2.2-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
07:38:14,920  WARN |testPerNodePolicy_afterGracefulShutdown| - [Node] Thread-4899 - [127.0.0.1]:5701 [dev] [4.2.2-SNAPSHOT] Terminating forcefully...
07:38:14,920  INFO |testPerNodePolicy_afterGracefulShutdown| - [Node] Thread-4899 - [127.0.0.1]:5701 [dev] [4.2.2-SNAPSHOT] Shutting down connection manager...
07:38:14,920  INFO |testPerNodePolicy_afterGracefulShutdown| - [Node] Thread-4899 - [127.0.0.1]:5701 [dev] [4.2.2-SNAPSHOT] Shutting down node engine...
07:38:14,921  WARN |testPerNodePolicy_afterGracefulShutdown| - [InternalPartitionService] hz.youthful_edison.priority-generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [4.2.2-SNAPSHOT] Ignoring received partition table, startup is not completed yet. Sender: [127.0.0.1]:5701
07:38:14,921 ERROR |testPerNodePolicy_afterGracefulShutdown| - [PromotionCommitOperation] hz.youthful_edison.priority-generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [4.2.2-SNAPSHOT] Promotion of 132 partitions failed. . Promotion partition state stamp: -6766174281841707288, current partition state stamp: 3286181170250441367
07:38:14,925  INFO |testPerNodePolicy_afterGracefulShutdown| - [NodeExtension] Thread-4899 - [127.0.0.1]:5701 [dev] [4.2.2-SNAPSHOT] Destroying node NodeExtension.
07:38:14,925  INFO |testPerNodePolicy_afterGracefulShutdown| - [Node] Thread-4899 - [127.0.0.1]:5701 [dev] [4.2.2-SNAPSHOT] Hazelcast Shutdown is completed in 5 ms.
07:38:14,926  INFO |testPerNodePolicy_afterGracefulShutdown| - [LifecycleService] Thread-4899 - [127.0.0.1]:5701 [dev] [4.2.2-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
BuildInfo right after testPerNodePolicy_afterGracefulShutdown(com.hazelcast.map.EvictionMaxSizePolicyTest): BuildInfo{version='4.2.2-SNAPSHOT', build='20210728', buildNumber=20210728, revision=4252001, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'testPerNodePolicy_afterGracefulShutdown(com.hazelcast.map.EvictionMaxSizePolicyTest):'
07:36:10, accumulated pauses: 128 ms, max pause: 72 ms, pauses over 1000 ms: 0
07:36:15, accumulated pauses: 869 ms, max pause: 59 ms, pauses over 1000 ms: 0
07:36:20, accumulated pauses: 268 ms, max pause: 39 ms, pauses over 1000 ms: 0
07:36:25, accumulated pauses: 207 ms, max pause: 37 ms, pauses over 1000 ms: 0
07:36:30, accumulated pauses: 154 ms, max pause: 30 ms, pauses over 1000 ms: 0
07:36:35, accumulated pauses: 131 ms, max pause: 36 ms, pauses over 1000 ms: 0
07:36:40, accumulated pauses: 38 ms, max pause: 4 ms, pauses over 1000 ms: 0
07:36:45, accumulated pauses: 49 ms, max pause: 8 ms, pauses over 1000 ms: 0
07:36:50, accumulated pauses: 43 ms, max pause: 6 ms, pauses over 1000 ms: 0
07:36:55, accumulated pauses: 64 ms, max pause: 31 ms, pauses over 1000 ms: 0
07:37:00, accumulated pauses: 34 ms, max pause: 1 ms, pauses over 1000 ms: 0
07:37:05, accumulated pauses: 33 ms, max pause: 0 ms, pauses over 1000 ms: 0
07:37:10, accumulated pauses: 38 ms, max pause: 7 ms, pauses over 1000 ms: 0
07:37:15, accumulated pauses: 42 ms, max pause: 7 ms, pauses over 1000 ms: 0
07:37:20, accumulated pauses: 66 ms, max pause: 7 ms, pauses over 1000 ms: 0
07:37:25, accumulated pauses: 32 ms, max pause: 0 ms, pauses over 1000 ms: 0
07:37:30, accumulated pauses: 53 ms, max pause: 4 ms, pauses over 1000 ms: 0
07:37:35, accumulated pauses: 37 ms, max pause: 3 ms, pauses over 1000 ms: 0
07:37:40, accumulated pauses: 64 ms, max pause: 6 ms, pauses over 1000 ms: 0
07:37:45, accumulated pauses: 58 ms, max pause: 9 ms, pauses over 1000 ms: 0
07:37:50, accumulated pauses: 128 ms, max pause: 21 ms, pauses over 1000 ms: 0
07:37:55, accumulated pauses: 68 ms, max pause: 24 ms, pauses over 1000 ms: 0
07:38:00, accumulated pauses: 125 ms, max pause: 45 ms, pauses over 1000 ms: 0
07:38:05, accumulated pauses: 31 ms, max pause: 0 ms, pauses over 1000 ms: 0
07:38:10, accumulated pauses: 259 ms, max pause: 230 ms, pauses over 1000 ms: 0
```

**Comment by ahmetmircik** [comment]
Assertion is problematic, it should be relaxed a bit.
