### ISSUE TITLE
NPE from SQL

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast#19221]
Using 5.0-BETA-1, the following code throws a NullPointerException

```
    public static void main(String[] args) throws Exception {
        Config config = new Config();
        HazelcastInstance hazelcastInstance = Hazelcast.newHazelcastInstance(config);
        String sql = "CREATE OR REPLACE MAPPING \"neil\" "
                + "TYPE IMap "
                + " OPTIONS ( "
                + " 'keyFormat' = 'java',"
                + " 'keyJavaClass' = '" + Integer.class.getCanonicalName() + "',"
                + " 'valueFormat' = 'java',"
                + " 'valueJavaClass' = '" + Integer.class.getCanonicalName() + "'"
                + " )";
        hazelcastInstance.getSql().execute(sql);
        hazelcastInstance.shutdown();
    }
```
classpath is
```
[INFO] +- com.hazelcast:hazelcast:jar:5.0-BETA-1:compile
[INFO] \- com.hazelcast:hazelcast-sql:jar:5.0-BETA-1:compile
```

With 5.0-BETA-1 I get
```
Exception in thread "main" com.hazelcast.sql.HazelcastSqlException
	at com.hazelcast.sql.impl.QueryUtils.toPublicException(QueryUtils.java:79)
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:233)
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:199)
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:195)
	at com.hazelcast.sql.SqlService.execute(SqlService.java:146)
	at neil.Application.main(Application.java:20)
Caused by: com.hazelcast.sql.impl.QueryException
	at com.hazelcast.sql.impl.QueryException.error(QueryException.java:60)
	at com.hazelcast.sql.impl.calcite.parse.QueryParser.parse(QueryParser.java:86)
	at com.hazelcast.sql.impl.calcite.OptimizerContext.parse(OptimizerContext.java:136)
	at com.hazelcast.sql.impl.calcite.CalciteSqlOptimizer.prepare(CalciteSqlOptimizer.java:127)
	at com.hazelcast.sql.impl.SqlServiceImpl.prepare(SqlServiceImpl.java:287)
	at com.hazelcast.sql.impl.SqlServiceImpl.query0(SqlServiceImpl.java:268)
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:220)
	... 4 more
Caused by: java.lang.NullPointerException
	at com.hazelcast.sql.impl.calcite.parse.QueryParser.parse(QueryParser.java:91)
	at com.hazelcast.sql.impl.calcite.parse.QueryParser.parse(QueryParser.java:76)
	... 9 more
```

5.0-SNAPSHOT (`20210729 - 12d65bd`) gives a different error
```
Exception in thread "main" com.hazelcast.sql.HazelcastSqlException: Encountered "CREATE" at line 1, column 1.
	at com.hazelcast.sql.impl.QueryUtils.toPublicException(QueryUtils.java:79)
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:238)
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:200)
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:196)
	at com.hazelcast.sql.SqlService.execute(SqlService.java:146)
	at neil.Application.main(Application.java:20)
Caused by: com.hazelcast.sql.impl.QueryException: Encountered "CREATE" at line 1, column 1.
	at com.hazelcast.sql.impl.QueryException.error(QueryException.java:60)
	at com.hazelcast.sql.impl.calcite.parse.QueryParser.parse(QueryParser.java:95)
	at com.hazelcast.sql.impl.calcite.OptimizerContext.parse(OptimizerContext.java:140)
	at com.hazelcast.sql.impl.calcite.CalciteSqlOptimizer.prepare(CalciteSqlOptimizer.java:127)
	at com.hazelcast.sql.impl.SqlServiceImpl.prepare(SqlServiceImpl.java:292)
	at com.hazelcast.sql.impl.SqlServiceImpl.query0(SqlServiceImpl.java:273)
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:225)
	... 4 more
Caused by: com.hazelcast.org.apache.calcite.sql.parser.SqlParseException: Encountered "CREATE" at line 1, column 1.
Was expecting one of:
    "ABS" ...
    "ALTER" ...
    "ARRAY" ...
    "AVG" ...
    "CALL" ...
    "CARDINALITY" ...
    "CASE" ...
    "CAST" ...
    "CEIL" ...
    "CEILING" ...
    "CHAR_LENGTH" ...
    "CHARACTER_LENGTH" ...
    "CLASSIFIER" ...
    "COALESCE" ...
    "COLLECT" ...
    "CONVERT" ...
    "COUNT" ...
    "COVAR_POP" ...
    "COVAR_SAMP" ...
    "CUME_DIST" ...
```

`CREATE` isn't listed, so not sure if this is a true defect or due to beta changes

**Comment by neilstevenson** [comment]
For 5.0-SNAPSHOT, Jet is disabled, added
```
config.getJetConfig().setEnabled(true);```

and it works for 5.0-SNAPSHOT

Since 5.0-SNAPSHOT supercedes 5.0-BETA-1, I see no value in this ticket

**Comment by mmedenjak** [comment]
@neilstevenson did you not get the error that you should enable jet even with the latest snapshot? Did you guess that you needed to enable jet? I would like for the error to be clear.
