### ISSUE TITLE
Cannot enable Jet Engine with client permissions

### ISSUE THREAD

**Issue by mmedenjak** [hazelcast/hazelcast#19239]
Migrated from https://hazelcast.atlassian.net/browse/HZ-487

I am getting NPE during 5.0-SNAPSHOT startup within Java context with Jet Engine enabled as below;
```
20:06:13.966 [main] ERROR c.h.c.h.a.ContainerApplication - Cluster #1773 failed to start: null
java.lang.NullPointerException: null
	at com.hazelcast.jet.impl.EnterpriseJetServiceBackend.configureJetInternalObjects(EnterpriseJetServiceBackend.java:67)
	at com.hazelcast.instance.impl.JetExtension.beforeStart(JetExtension.java:67)
	at com.hazelcast.instance.impl.DefaultNodeExtension.beforeStart(DefaultNodeExtension.java:213)
	at com.hazelcast.instance.impl.EnterpriseNodeExtension.beforeStart(EnterpriseNodeExtension.java:243)
	at com.hazelcast.instance.impl.Node.<init>(Node.java:238)
	at com.hazelcast.instance.impl.HazelcastInstanceImpl.createNode(HazelcastInstanceImpl.java:149)
	at com.hazelcast.instance.impl.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:118)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:211)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:190)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:128)
	at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:61)
	at com.hazelcast.cloud.hazelcastcontainer.service.HazelcastServiceImpl.<init>(HazelcastServiceImpl.java:48)
	at com.hazelcast.cloud.hazelcastcontainer.application.ContainerApplication.start(ContainerApplication.java:95)
	at com.hazelcast.cloud.hazelcastcontainer.ContainerEntryPoint.main(ContainerEntryPoint.java:25)
```

When I check related code line, I see client permission name is compared by a constant, but not all client permissions have a name;
```java
for (PermissionConfig clientPermissionConfig : clientPermissionConfigs) {
            if (clientPermissionConfig.getName().startsWith(INTERNAL_JET_OBJECTS_PREFIX)) {
                throw new IllegalArgumentException("Explicitly configuring internal Jet data-structures is forbidden");
            }
```

I am using following notation for client permissions;
```xml
<client-permissions>
<all-permissions principal="de-1773">
</all-permissions>
</client-permissions>
```

**Comment by mmedenjak** [comment]
@gurbuzali is this a duplicate of https://github.com/hazelcast/hazelcast-enterprise/issues/4145?

**Comment by gurbuzali** [comment]
@mmedenjak yes
