### ISSUE TITLE
5.0-BETA-1 Management Center shows Remote cluster members as 127.0.0.1

### ISSUE THREAD

**Issue by robinroos** [hazelcast/hazelcast#19256]
Using Hazelcast Management Center 5.0-BETA-1 against a 4-node cluster (also 5.0-BETA-1) on a remote machine.

Hazelcast connects to the cache.  In the Dashboard page it lists 4 members.  But each is listed as 127.0.0.1 (they are not running locally, but are on a remote machine).  Also, memory and cpu stats are available only for the first member (:5701) and not for the others (:5702-4).

![image](https://user-images.githubusercontent.com/13133023/128030274-ec589f40-9fdf-4c6c-92e1-ffe6469a32b0.png)

**Comment by robinroos** [comment]
```
2021-08-03 15:07:17,125 [ INFO] [main] [c.h.w.s.ClusterManager]: Connecting to 2 enabled cluster(s) on startup.
2021-08-03 15:07:17,763 [ INFO] [MC-Client-cache-rhel.lifecycle-1] [c.h.w.s.MCClientManager]: MC Client connected to cluster cache-rhel.
2021-08-03 15:07:17,785 [ INFO] [MC-Client-cache-rhel.event-6] [c.h.w.s.MCClientManager]: Started communication with member: Member [127.0.0.1]:5701 - b846ad34-c02c-4044-a323-5bbe6e8f9779
2021-08-03 15:07:17,786 [ INFO] [MC-Client-cache-rhel.event-6] [c.h.w.s.MCClientManager]: Started communication with member: Member [127.0.0.1]:5702 - 4e23e129-43eb-4903-8b4e-0c0299070642
2021-08-03 15:07:17,789 [ INFO] [MC-Client-cache-rhel.event-6] [c.h.w.s.MCClientManager]: Started communication with member: Member [127.0.0.1]:5703 - fd8ecada-e7c4-47aa-9264-666739cb210a
2021-08-03 15:07:17,790 [ INFO] [MC-Client-cache-rhel.event-6] [c.h.w.s.MCClientManager]: Started communication with member: Member [127.0.0.1]:5704 - 67649a18-bdfb-488c-9d8f-ef1761a2dc29
2021-08-03 15:07:18,298 [ INFO] [main] [c.h.w.Launcher]:

Hazelcast Management Center successfully started at http://localhost:8080/

2021-08-03 15:08:18,037 [ERROR] [AsyncExecutor-2] [c.h.w.s.m.DefaultMemberConfigService]: com.hazelcast.webmonitor.controller.exception.OperationFailedApiException: failed to get remote config: null
com.google.common.util.concurrent.UncheckedExecutionException: com.hazelcast.webmonitor.controller.exception.OperationFailedApiException: failed to get remote config: null
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2051) ~[hazelcast-management-center-5.0-BETA-1.jar:?]
        at com.google.common.cache.LocalCache.get(LocalCache.java:3962) ~[hazelcast-management-center-5.0-BETA-1.jar:?]
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3985) ~[hazelcast-management-center-5.0-BETA-1.jar:?]
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4946) ~[hazelcast-management-center-5.0-BETA-1.jar:?]
        at com.hazelcast.webmonitor.service.memberconfig.DefaultMemberConfigService.getMemberConfig(DefaultMemberConfigService.java:216) [hazelcast-management-center-5.0-BETA-1.jar:?]
        at com.hazelcast.webmonitor.service.memberconfig.DefaultMemberConfigService$$Lambda$1535/0x00000000eafd67a8.accept(Unknown Source) [hazelcast-management-center-5.0-BETA-1.jar:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) [?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) [?:?]
        at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1694) [?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:497) [?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:487) [?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) [?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) [?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:239) [?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) [?:?]
        at com.hazelcast.webmonitor.service.memberconfig.DefaultMemberConfigService.memberStateAdded(DefaultMemberConfigService.java:205) [hazelcast-management-center-5.0-BETA-1.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344) [hazelcast-management-center-5.0-BETA-1.jar:?]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198) [hazelcast-management-center-5.0-BETA-1.jar:?]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) [hazelcast-management-center-5.0-BETA-1.jar:?]
        at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115) [hazelcast-management-center-5.0-BETA-1.jar:?]
        at org.springframework.aop.interceptor.AsyncExecutionInterceptor$$Lambda$1532/0x00000000eafd5ec8.call(Unknown Source) [hazelcast-management-center-5.0-BETA-1.jar:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at java.lang.Thread.run(Thread.java:845) [?:?]
Caused by: com.hazelcast.webmonitor.controller.exception.OperationFailedApiException: failed to get remote config: null
        at com.hazelcast.webmonitor.service.OperationDispatcher.wrapException(OperationDispatcher.java:36) ~[hazelcast-management-center-5.0-BETA-1.jar:?]
        at com.hazelcast.webmonitor.service.OperationDispatcher.executeOnMember(OperationDispatcher.java:51) ~[hazelcast-management-center-5.0-BETA-1.jar:?]
        at com.hazelcast.webmonitor.service.memberconfig.DefaultMemberConfigService.doGetMemberConfig(DefaultMemberConfigService.java:164) ~[hazelcast-management-center-5.0-BETA-1.jar:?]
        at com.hazelcast.webmonitor.service.memberconfig.DefaultMemberConfigService.access$000(DefaultMemberConfigService.java:45) ~[hazelcast-management-center-5.0-BETA-1.jar:?]
        at com.hazelcast.webmonitor.service.memberconfig.DefaultMemberConfigService$1.load(DefaultMemberConfigService.java:187) ~[hazelcast-management-center-5.0-BETA-1.jar:?]
        at com.hazelcast.webmonitor.service.memberconfig.DefaultMemberConfigService$1.load(DefaultMemberConfigService.java:183) ~[hazelcast-management-center-5.0-BETA-1.jar:?]
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529) ~[hazelcast-management-center-5.0-BETA-1.jar:?]
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278) ~[hazelcast-management-center-5.0-BETA-1.jar:?]
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155) ~[hazelcast-management-center-5.0-BETA-1.jar:?]
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045) ~[hazelcast-management-center-5.0-BETA-1.jar:?]
        ... 28 more
Caused by: java.util.concurrent.TimeoutException
        at com.hazelcast.client.impl.spi.impl.ClientInvocationFuture.newTimeoutException(ClientInvocationFuture.java:63) ~[hazelcast-management-center-5.0-BETA-1.jar:?]
        at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:656) ~[hazelcast-management-center-5.0-BETA-1.jar:?]
        at com.hazelcast.spi.impl.DelegatingCompletableFuture.get(DelegatingCompletableFuture.java:118) ~[hazelcast-management-center-5.0-BETA-1.jar:?]
        at com.hazelcast.webmonitor.service.OperationDispatcher.lambda$executeOnMember$1(OperationDispatcher.java:56) ~[hazelcast-management-center-5.0-BETA-1.jar:?]
        at com.hazelcast.webmonitor.service.OperationDispatcher$$Lambda$1547/0x00000000eafe4130.call(Unknown Source) ~[?:?]
        at com.hazelcast.webmonitor.service.OperationDispatcher.wrapException(OperationDispatcher.java:34) ~[hazelcast-management-center-5.0-BETA-1.jar:?]
        at com.hazelcast.webmonitor.service.OperationDispatcher.executeOnMember(OperationDispatcher.java:51) ~[hazelcast-management-center-5.0-BETA-1.jar:?]
        at com.hazelcast.webmonitor.service.memberconfig.DefaultMemberConfigService.doGetMemberConfig(DefaultMemberConfigService.java:164) ~[hazelcast-management-center-5.0-BETA-1.jar:?]
        at com.hazelcast.webmonitor.service.memberconfig.DefaultMemberConfigService.access$000(DefaultMemberConfigService.java:45) ~[hazelcast-management-center-5.0-BETA-1.jar:?]
        at com.hazelcast.webmonitor.service.memberconfig.DefaultMemberConfigService$1.load(DefaultMemberConfigService.java:187) ~[hazelcast-management-center-5.0-BETA-1.jar:?]
        at com.hazelcast.webmonitor.service.memberconfig.DefaultMemberConfigService$1.load(DefaultMemberConfigService.java:183) ~[hazelcast-management-center-5.0-BETA-1.jar:?]
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529) ~[hazelcast-management-center-5.0-BETA-1.jar:?]
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278) ~[hazelcast-management-center-5.0-BETA-1.jar:?]
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155) ~[hazelcast-management-center-5.0-BETA-1.jar:?]
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045) ~[hazelcast-management-center-5.0-BETA-1.jar:?]
        ... 28 more
```

**Comment by emre-aydin** [comment]
Hi @robinroos, can you please share how you configure your cluster on the Management Center?

**Comment by robinroos** [comment]
Here is the config of the "cache-rhel" cluser in Management Center.

![image](https://user-images.githubusercontent.com/13133023/128506914-c9aadbba-b609-40b0-b546-fa27ae1aefa1.png)

**Comment by emre-aydin** [comment]
@robinroos do you have the Management Center and the members in the same network?

**Comment by robinroos** [comment]
Management Center is running on my PC host.  I believe this is the same network.  I can ping anl-cmi22 fro my PC host without adding any suffixes to the hostname.

**Comment by mmedenjak** [comment]
@robinroos have you managed to try out the suggestion above and any info for us?

**Comment by mohammedr99** [comment]
@mmedenjak - I am also facing the same issue. I am using stable version of MC 5.1.1. Connection strategy used is tcp/ip and advanced network config isn't used instead network config is used

**Comment by mohammedr99** [comment]
Hi @mmedenjak - I am also facing the same issue. MC stable version v5.1.1 used. Connection strategy is tcp/ip. Advanced network config isn't used, instead network config is used. Please advise
