### ISSUE TITLE
com.hazelcast.jet.impl.JobRepositoryTest.test_maxNumberOfJobResults

### ISSUE THREAD

**Issue by mdumandag** [hazelcast/hazelcast#19253]
Failed on PR builder http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/6468/testReport/junit/com.hazelcast.jet.impl/JobRepositoryTest/test_maxNumberOfJobResults/ but I am able to reproduce this in the master as well, simply by running the test couple of times.

Stacktrace:
```
java.lang.AssertionError: expected:<2> but was:<3>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at com.hazelcast.jet.impl.JobRepositoryTest.test_maxNumberOfJobResults(JobRepositoryTest.java:201)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

Standard output:

```
Finished Running Test: when_jobFileUploadFails_then_jobResourcesCleanedUp in 0.450 seconds.
Finished Running Test: when_jobJarUploadFails_then_jobResourcesCleanedUp in 0.450 seconds.
Started Running Test: when_jobZipUploadFails_then_jobResourcesCleanedUp
Started Running Test: when_onlyJobResourcesExist_then_jobResourcesClearedAfterExpiration
07:28:26,096  INFO |when_onlyJobResourcesExist_then_jobResourcesClearedAfterExpiration| - [MetricsConfigHelper] Thread-4525 - [LOCAL] [dev] [5.0-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
07:28:26,096  INFO |when_jobZipUploadFails_then_jobResourcesCleanedUp| - [MetricsConfigHelper] Thread-4524 - [LOCAL] [dev] [5.0-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
07:28:26,098  INFO |when_onlyJobResourcesExist_then_jobResourcesClearedAfterExpiration| - [logo] Thread-4525 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
07:28:26,099  INFO |test_maxNumberOfJobResults| - [JetTestSupport] Thread-4514 - Terminating instanceFactory in JetTestSupport.@After
07:28:26,099  INFO |when_jobZipUploadFails_then_jobResourcesCleanedUp| - [logo] Thread-4524 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
07:28:26,099  INFO |when_onlyJobResourcesExist_then_jobResourcesClearedAfterExpiration| - [system] Thread-4525 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Copyright (c) 2008-2021, Hazelcast, Inc. All Rights Reserved.
07:28:26,099  INFO |when_jobZipUploadFails_then_jobResourcesCleanedUp| - [system] Thread-4524 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Copyright (c) 2008-2021, Hazelcast, Inc. All Rights Reserved.
07:28:26,099  INFO |when_jobZipUploadFails_then_jobResourcesCleanedUp| - [system] Thread-4524 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Hazelcast Platform 5.0-SNAPSHOT (20210803 - f521098) starting at [127.0.0.1]:5701
07:28:26,099  INFO |when_onlyJobResourcesExist_then_jobResourcesClearedAfterExpiration| - [system] Thread-4525 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Hazelcast Platform 5.0-SNAPSHOT (20210803 - f521098) starting at [127.0.0.1]:5701
07:28:26,099  INFO |when_jobZipUploadFails_then_jobResourcesCleanedUp| - [system] Thread-4524 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Cluster name: dev
07:28:26,099  INFO |when_onlyJobResourcesExist_then_jobResourcesClearedAfterExpiration| - [system] Thread-4525 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Cluster name: dev
07:28:26,099  INFO |test_maxNumberOfJobResults| - [LifecycleService] Thread-4526 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
07:28:26,099  WARN |test_maxNumberOfJobResults| - [Node] Thread-4526 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Terminating forcefully...
07:28:26,099  INFO |test_maxNumberOfJobResults| - [Node] Thread-4526 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Shutting down connection manager...
07:28:26,099  INFO |test_maxNumberOfJobResults| - [Node] Thread-4526 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Shutting down node engine...
07:28:26,106  INFO |test_maxNumberOfJobResults| - [NodeExtension] Thread-4526 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Destroying node NodeExtension.
07:28:26,106  INFO |test_maxNumberOfJobResults| - [Node] Thread-4526 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Hazelcast Shutdown is completed in 7 ms.
07:28:26,106  INFO |test_maxNumberOfJobResults| - [LifecycleService] Thread-4526 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
BuildInfo right after test_maxNumberOfJobResults(com.hazelcast.jet.impl.JobRepositoryTest): BuildInfo{version='5.0-SNAPSHOT', build='20210803', buildNumber=20210803, revision=f521098, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'test_maxNumberOfJobResults(com.hazelcast.jet.impl.JobRepositoryTest):'
07:28:25, accumulated pauses: 362 ms, max pause: 316 ms, pauses over 1000 ms: 0


No metrics recorded during the test
07:28:26,108  INFO |when_jobZipUploadFails_then_jobResourcesCleanedUp| - [MetricsConfigHelper] Thread-4524 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
07:28:26,108  INFO |when_onlyJobResourcesExist_then_jobResourcesClearedAfterExpiration| - [MetricsConfigHelper] Thread-4525 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
```

**Comment by yamanogluberk** [comment]
I had the same one: http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/6466/testReport/junit/com.hazelcast.jet.impl/JobRepositoryTest/test_maxNumberOfJobResults/ 

Stacktrace: 

`java.lang.AssertionError: expected:<2> but was:<3>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at com.hazelcast.jet.impl.JobRepositoryTest.test_maxNumberOfJobResults(JobRepositoryTest.java:201)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by ramizdundar** [comment]
another one http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/6471/testReport/com.hazelcast.jet.impl/JobRepositoryTest/test_maxNumberOfJobResults/

```
java.lang.AssertionError: expected:<2> but was:<3>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at com.hazelcast.jet.impl.JobRepositoryTest.test_maxNumberOfJobResults(JobRepositoryTest.java:201)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by gurbuzali** [comment]
failed on my PR too, I've added a fix to it https://github.com/hazelcast/hazelcast/pull/19249/commits/3a96e720a377cd07e72f284d57595e4655505458

**Comment by ramizdundar** [comment]
cc @gurbuzali should this be closed now since your PR is merged?
