### ISSUE TITLE
BeanInstantiationException: Failed to instantiate [com.hazelcast.core.HazelcastInstance]

### ISSUE THREAD

**Issue by baphuc1998** [hazelcast/hazelcast#19263]
**Describe the bug**
Hi everyone, I am facing this issue after restarting my pod in Kubernetes. The previous times spring boot was working fine, I was surprised when I got this error for the first time

application.properties:
```
spring.cache.type=hazelcast
spring.hazelcast.config=classpath:hazelcast.xml
spring.session.store-type=HAZELCAST
```
hazelcast.xml:
```
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<hazelcast xmlns="http://www.hazelcast.com/schema/config"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="https://hazelcast.com/schema/config
           https://hazelcast.com/schema/config/hazelcast-config-3.12.xsd">
    <group>
        <name>name</name>
    </group>
    <management-center enabled="false">http://localhost:8080/hazelcast-mancenter</management-center>
    <network>
        <port auto-increment="true" port-count="10">5701</port>
        <outbound-ports>
            <!--
            Allowed port range when connecting to other nodes.
            0 or * means use system provided port.
            -->
            <ports>0</ports>
        </outbound-ports>
        <join>
            <multicast enabled="false">
                <multicast-group>224.2.2.3</multicast-group>
                <multicast-port>54327</multicast-port>
            </multicast>
            <tcp-ip enabled="true">
                <member>127.0.0.1</member>
            </tcp-ip>
            <kubernetes enabled="false">
                <namespace>development</namespace>
                <service-name>service-name</service-name>
            </kubernetes>
        </join>
    </network>
</hazelcast>
```
and dependencies:
```
implementation 'com.hazelcast:hazelcast-kubernetes:2.0'
implementation 'com.hazelcast:hazelcast-spring'
```
Stack Trace:
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hazelcastInstance' defined in class path resource [org/springframework/boot/autoconfigure/hazelcast/HazelcastServerConfiguration$HazelcastServerConfigFileConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.hazelcast.core.HazelcastInstance]: Factory method 'hazelcastInstance' threw exception; nested exception is com.hazelcast.config.InvalidConfigurationException: Your xsd schema couldn't be loaded
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:658) ~[spring-beans-5.3.2.jar!/:5.3.2]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:638) ~[spring-beans-5.3.2.jar!/:5.3.2]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1336) ~[spring-beans-5.3.2.jar!/:5.3.2]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1179) ~[spring-beans-5.3.2.jar!/:5.3.2]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:571) ~[spring-beans-5.3.2.jar!/:5.3.2]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:531) ~[spring-beans-5.3.2.jar!/:5.3.2]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.2.jar!/:5.3.2]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.2.jar!/:5.3.2]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.2.jar!/:5.3.2]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.2.jar!/:5.3.2]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944) ~[spring-beans-5.3.2.jar!/:5.3.2]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:923) ~[spring-context-5.3.2.jar!/:5.3.2]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:588) ~[spring-context-5.3.2.jar!/:5.3.2]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144) ~[spring-boot-2.4.1.jar!/:2.4.1]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:767) ~[spring-boot-2.4.1.jar!/:2.4.1]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759) ~[spring-boot-2.4.1.jar!/:2.4.1]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:426) ~[spring-boot-2.4.1.jar!/:2.4.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:326) ~[spring-boot-2.4.1.jar!/:2.4.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1309) ~[spring-boot-2.4.1.jar!/:2.4.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1298) ~[spring-boot-2.4.1.jar!/:2.4.1]
	at Application.main(Application.java:10) ~[classes!/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[svc-chatbotadm-1.0.0-alpha.1.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:107) ~[svc-chatbotadm-1.0.0-alpha.1.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[svc-chatbotadm-1.0.0-alpha.1.jar:na]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[svc-chatbotadm-1.0.0-alpha.1.jar:na]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.hazelcast.core.HazelcastInstance]: Factory method 'hazelcastInstance' threw exception; nested exception is com.hazelcast.config.InvalidConfigurationException: Your xsd schema couldn't be loaded
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.3.2.jar!/:5.3.2]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653) ~[spring-beans-5.3.2.jar!/:5.3.2]
	... 28 common frames omitted
Caused by: com.hazelcast.config.InvalidConfigurationException: Your xsd schema couldn't be loaded
	at com.hazelcast.config.AbstractXmlConfigHelper.loadSchemaFile(AbstractXmlConfigHelper.java:136) ~[hazelcast-4.0.3.jar!/:4.0.3]
	at com.hazelcast.config.AbstractXmlConfigHelper.schemaValidation(AbstractXmlConfigHelper.java:96) ~[hazelcast-4.0.3.jar!/:4.0.3]
	at com.hazelcast.config.XmlConfigBuilder.parseAndBuildConfig(XmlConfigBuilder.java:169) ~[hazelcast-4.0.3.jar!/:4.0.3]
	at com.hazelcast.config.XmlConfigBuilder.build(XmlConfigBuilder.java:151) ~[hazelcast-4.0.3.jar!/:4.0.3]
	at com.hazelcast.config.XmlConfigBuilder.build(XmlConfigBuilder.java:144) ~[hazelcast-4.0.3.jar!/:4.0.3]
	at org.springframework.boot.autoconfigure.hazelcast.HazelcastInstanceFactory.createConfig(HazelcastInstanceFactory.java:80) ~[spring-boot-autoconfigure-2.4.1.jar!/:2.4.1]
	at org.springframework.boot.autoconfigure.hazelcast.HazelcastInstanceFactory.getConfig(HazelcastInstanceFactory.java:65) ~[spring-boot-autoconfigure-2.4.1.jar!/:2.4.1]
	at org.springframework.boot.autoconfigure.hazelcast.HazelcastInstanceFactory.<init>(HazelcastInstanceFactory.java:51) ~[spring-boot-autoconfigure-2.4.1.jar!/:2.4.1]
	at org.springframework.boot.autoconfigure.hazelcast.HazelcastServerConfiguration$HazelcastServerConfigFileConfiguration.hazelcastInstance(HazelcastServerConfiguration.java:53) ~[spring-boot-autoconfigure-2.4.1.jar!/:2.4.1]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.3.2.jar!/:5.3.2]
	... 29 common frames omitted
```

**Comment by mmedenjak** [comment]
@baphuc1998 are you still getting the error? Is it reproducible? Maybe there was some temporary issue with the network. It's hard to tell from just this exception what's the actual root cause.
