### ISSUE TITLE
hz-cli 5.0-SNAPSHOT exception for Enterprise jar

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast#19288]
Using `hz-cli` compiled from source today.

If my pom.xml has
```
		<dependency>
			<groupId>com.hazelcast</groupId>
			<artifactId>hazelcast</artifactId>
			<scope>provided</scope>
		</dependency>
```
job submission works fine.

If my pom.xml has 
```
		<dependency>
			<groupId>com.hazelcast</groupId>
			<artifactId>hazelcast-enterprise</artifactId>
			<scope>provided</scope>
		</dependency>
```
(note scope is provided),
then I get this exception
```
09:55:38.870 [ INFO] [c.h.i.c.AbstractConfigLocator] Loading 'hazelcast-client-default.xml' from the classpath.
picocli.CommandLine$ExecutionException: Error while calling command (public void com.hazelcast.client.console.HazelcastCommandLine.submit(com.hazelcast.client.console.HazelcastCommandLine$Verbosity,com.hazelcast.client.console.HazelcastCommandLine$TargetsMixin,java.lang.String,java.lang.String,java.lang.String,java.io.File,java.util.List) throws java.lang.Exception): java.lang.reflect.InvocationTargetException
	at picocli.CommandLine.execute(CommandLine.java:1207)
	at picocli.CommandLine.access$800(CommandLine.java:141)
	at picocli.CommandLine$RunAll.handle(CommandLine.java:1416)
	at picocli.CommandLine$RunAll.handle(CommandLine.java:1376)
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1243)
	at picocli.CommandLine.parseWithHandlers(CommandLine.java:1526)
	at com.hazelcast.client.console.HazelcastCommandLine.runCommandLine(HazelcastCommandLine.java:553)
	at com.hazelcast.client.console.HazelcastCommandLine.main(HazelcastCommandLine.java:133)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.hazelcast.instance.impl.HazelcastBootstrap.executeJar(HazelcastBootstrap.java:169)
	at com.hazelcast.client.console.HazelcastCommandLine.submit(HazelcastCommandLine.java:197)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at picocli.CommandLine.execute(CommandLine.java:1189)
	... 7 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
	... 18 more
Caused by: java.lang.IllegalAccessError: failed to access class com.hazelcast.client.impl.clientside.HazelcastClientManagedContext from class com.hazelcast.client.impl.clientside.EnterpriseClientExtension (com.hazelcast.client.impl.clientside.HazelcastClientManagedContext is in unnamed module of loader 'app'; com.hazelcast.client.impl.clientside.EnterpriseClientExtension is in unnamed module of loader org.springframework.boot.loader.LaunchedURLClassLoader @5cee5251)
	at com.hazelcast.client.impl.clientside.EnterpriseClientExtension.createSerializationService(EnterpriseClientExtension.java:85)
	at com.hazelcast.client.impl.clientside.HazelcastClientInstanceImpl.<init>(HazelcastClientInstanceImpl.java:246)
	at com.hazelcast.client.HazelcastClient.constructHazelcastClient(HazelcastClient.java:458)
	at com.hazelcast.client.HazelcastClient.newHazelcastClientInternal(HazelcastClient.java:416)
	at com.hazelcast.client.HazelcastClient.newHazelcastClient(HazelcastClient.java:136)
	at com.hazelcast.client.console.HazelcastCommandLine.lambda$getHazelcastClient$6(HazelcastCommandLine.java:474)
	at com.hazelcast.jet.impl.util.Util.uncheckCall(Util.java:125)
	at com.hazelcast.client.console.HazelcastCommandLine.getHazelcastClient(HazelcastCommandLine.java:474)
	at com.hazelcast.client.console.HazelcastCommandLine.lambda$submit$0(HazelcastCommandLine.java:198)
	at com.hazelcast.instance.impl.HazelcastBootstrap.lambda$executeJar$0(HazelcastBootstrap.java:140)
	at com.hazelcast.jet.impl.util.ConcurrentMemoizingSupplier.get(ConcurrentMemoizingSupplier.java:50)
	at com.hazelcast.instance.impl.HazelcastBootstrap.getInstance(HazelcastBootstrap.java:257)
	at com.hazelcast.core.Hazelcast.bootstrappedInstance(Hazelcast.java:261)
	at demo.Application.main(Application.java:41)
```

**Comment by frant-hartm** [comment]
@neilstevenson 
- what distribution are you using? OS/EE? Regular/slim?
- how do you package your jar? Do you have a project somewhere?

**Comment by frant-hartm** [comment]
I see some Spring classloader in the exception message : `org.springframework.boot.loader.LaunchedURLClassLoader`

@neilstevenson please share a full reproducer.
