### ISSUE TITLE
5.0-BETA-1 Management Center in OpenShift fails to terminate

### ISSUE THREAD

**Issue by robinroos** [hazelcast/hazelcast#19291]
I have 5.0-BETA-1 Management Center running as a Stateful Set in OpenShift.

Something is wrong, and an exception is reported.  After this, I am unable to cause the Pod to terminate so that it can be restarted.

**Comment by robinroos** [comment]
```
2021-08-09 10:09:00,514 [[31mERROR[m] [[36mAsyncExecutor-4[m] [[34mc.h.w.s.MemberManager[m]: Could not persist member Member [127.0.0.1]:5701 - 59621652-5933-480b-9398-ebd963669c93 data.
org.jdbi.v3.core.ConnectionException: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30000ms.
	at org.jdbi.v3.core.Jdbi.open(Jdbi.java:319) ~[hazelcast-management-center-5.0-BETA-1.jar:?]
	at org.jdbi.v3.core.Jdbi.withHandle(Jdbi.java:340) ~[hazelcast-management-center-5.0-BETA-1.jar:?]
	at org.jdbi.v3.core.Jdbi.useHandle(Jdbi.java:358) ~[hazelcast-management-center-5.0-BETA-1.jar:?]
	at org.jdbi.v3.core.Jdbi.useTransaction(Jdbi.java:391) ~[hazelcast-management-center-5.0-BETA-1.jar:?]
	at com.hazelcast.webmonitor.repositories.sql.MemberDAO.insertOrUpdate(MemberDAO.java:46) ~[hazelcast-management-center-5.0-BETA-1.jar:?]
	at com.hazelcast.webmonitor.service.MemberManager.onMemberJoined(MemberManager.java:352) ~[hazelcast-management-center-5.0-BETA-1.jar:?]
	at com.hazelcast.webmonitor.service.MemberManager$$FastClassBySpringCGLIB$$7b279106.invoke(<generated>) ~[?:?]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[hazelcast-management-center-5.0-BETA-1.jar:?]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779) ~[hazelcast-management-center-5.0-BETA-1.jar:?]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[hazelcast-management-center-5.0-BETA-1.jar:?]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750) ~[hazelcast-management-center-5.0-BETA-1.jar:?]
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115) ~[hazelcast-management-center-5.0-BETA-1.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30000ms.
	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:696) ~[hazelcast-management-center-5.0-BETA-1.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:197) ~[hazelcast-management-center-5.0-BETA-1.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:162) ~[hazelcast-management-center-5.0-BETA-1.jar:?]
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128) ~[hazelcast-management-center-5.0-BETA-1.jar:?]
	at org.jdbi.v3.core.Jdbi.open(Jdbi.java:303) ~[hazelcast-management-center-5.0-BETA-1.jar:?]
	... 15 more
```

**Comment by mmedenjak** [comment]
@robinroos thank you for the report. @leszko can someone take a look if it's an issue on MC side?

**Comment by leszko** [comment]
no idea. @emre-aydin any idea what this stacktrace points to?

**Comment by emre-aydin** [comment]
@zhmaeff can you please take a look?
