### ISSUE TITLE
Support CompactSerializer in SQL

### ISSUE THREAD

**Issue by Holmistr** [hazelcast/hazelcast#19302]
Provide ability to query maps which have values stored using the new (in Beta state) Compact serialization. Right now it gives:

```
Exception in thread "main" com.hazelcast.sql.HazelcastSqlException: Failed to resolve value metadata: CompactSerializer(BETA feature) is not enabled
	at com.hazelcast.sql.impl.client.SqlClientService.handleResponseError(SqlClientService.java:255)
	at com.hazelcast.sql.impl.client.SqlClientService.handleExecuteResponse(SqlClientService.java:125)
	at com.hazelcast.sql.impl.client.SqlClientService.lambda$execute$0(SqlClientService.java:103)
	at com.hazelcast.internal.util.ExceptionUtil.lambda$withTryCatch$1(ExceptionUtil.java:207)
	at com.hazelcast.client.impl.spi.impl.ClientInvocationFuture$CallIdTrackingBiConsumer.accept(ClientInvocationFuture.java:268)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$WhenCompleteNode.lambda$execute$0(AbstractInvocationFuture.java:1563)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1429)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by viliam-durina** [comment]
Resolved by #19362
