### ISSUE TITLE
SQL Query with Portable using remote controller "Failed to extract map entry value field `age`"

### ISSUE THREAD

**Issue by srknzl** [hazelcast/hazelcast#19309]
**Describe the bug**
A nodejs test started to fail. 

Test logic:
1. create a client with portable factory
1. add sorted index to the map on age property
1. add 3 students to map with put
1. run query SELECT * FROM mapName WHERE age > ? AND age < ? ORDER BY age DESC  with two longs as params
1. do assertions

Full test code and portable class:

```js
    it('should be able to decode/serialize OBJECT(portable) without server config', async function () {
        const SqlColumnType = TestUtil.getSqlColumnType();
        client = await testFactory.newHazelcastClient({
            clusterName: cluster.id,
            serialization: {
                portableFactories: {
                    666: portableFactory
                }
            },
            network: {
                clusterMembers: [`127.0.0.1:${member.port}`]
            }
        });
        TestUtil.markServerVersionAtLeast(this, client, '4.2');
        mapName = TestUtil.randomString(10);
        someMap = await client.getMap(mapName);
        await someMap.addIndex({
            type: 'SORTED',
            attributes: ['age']
        });

        const student1 = new Student(long.fromNumber(12), 123.23);
        const student2 = new Student(long.fromNumber(15), null);
        const student3 = new Student(long.fromNumber(17), null);
        await someMap.put(0, student1);
        await someMap.put(1, student2);
        await someMap.put(2, student3);

        const result = TestUtil.getSql(client).execute(
            `SELECT * FROM ${mapName} WHERE age > ? AND age < ? ORDER BY age DESC`,
            [long.fromNumber(13), long.fromNumber(18)]
        );

        const rowMetadata = await result.getRowMetadata();
        rowMetadata.getColumn(rowMetadata.findColumn('age')).type.should.be.eq(SqlColumnType.BIGINT);
        rowMetadata.getColumn(rowMetadata.findColumn('height')).type.should.be.eq(SqlColumnType.REAL);

        const rows = [];

        for await (const row of result) {
            rows.push(row);
        }

        const expectedKeys = [2, 1];
        const expectedValues = [student3, student2];

        rows.length.should.be.eq(expectedValues.length);

        for (let i = 0; i < rows.length; i++) {
            (rows[i]['age'].eq(expectedValues[i].age)).should.be.true;
            (rows[i]['height'] - expectedValues[i].height).should.be.lessThan(1e-5);
            rows[i]['__key'].should.be.eq(expectedKeys[i]);
        }
    });
```

Portable class:
```js
class Student {
    constructor(age, height) {
        this.age = age;
        this.height = height;
        this.factoryId = 666;
        this.classId = 1;
    }

    readPortable(reader) {
        this.age = reader.readLong('age');
        this.height = reader.readFloat('height');
    }

    writePortable(writer) {
        writer.writeLong('age', this.age);
        writer.writeFloat('height', this.height);
    }
}

```

Stack trace of Nodejs client:
```
     Error: The Jet SQL job failed: Execution on a member failed: com.hazelcast.jet.JetException: Exception in ProcessorTasklet{06a1-aebe-160d-0001/Index(IMap[partitioned.bpdekrcasc])#0}: com.hazelcast.sql.impl.QueryException: Failed to extract map entry value field "age": java.lang.UnsupportedOperationException
      at new HazelcastSqlException (lib/core/HazelcastError.js:378:9)
      at Function.handleExecuteResponse (lib/sql/SqlService.js:46:32)
      at invocationService.invokeOnConnection.then.clientMessage (lib/sql/SqlService.js:176:32)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

Stack trace in server:
```
WARNING: [localhost]:5701 [dev] [5.0-SNAPSHOT] Exception in ProcessorTasklet{06a1-b648-3b41-0001/Index(IMap[partitioned.mapName])#0}
com.hazelcast.sql.impl.QueryException: Failed to extract map entry value field "age": java.lang.UnsupportedOperationException
	at com.hazelcast.sql.impl.QueryException.error(QueryException.java:60)
	at com.hazelcast.sql.impl.QueryException.dataException(QueryException.java:99)
	at com.hazelcast.sql.impl.extract.GenericFieldExtractor.get(GenericFieldExtractor.java:56)
	at com.hazelcast.sql.impl.exec.scan.MapScanRow.get(MapScanRow.java:89)
	at com.hazelcast.sql.impl.expression.ColumnExpression.eval(ColumnExpression.java:68)
	at com.hazelcast.jet.sql.impl.ExpressionUtil.evaluate(ExpressionUtil.java:229)
	at com.hazelcast.jet.sql.impl.ExpressionUtil.evaluate(ExpressionUtil.java:219)
	at com.hazelcast.jet.sql.impl.connector.map.MapIndexScanP$Split.projectAndFilter(MapIndexScanP.java:340)
	at com.hazelcast.jet.sql.impl.connector.map.MapIndexScanP$Split.peek(MapIndexScanP.java:308)
	at com.hazelcast.jet.sql.impl.connector.map.MapIndexScanP$Split.access$200(MapIndexScanP.java:255)
	at com.hazelcast.jet.sql.impl.connector.map.MapIndexScanP.runSortedIndex(MapIndexScanP.java:162)
	at com.hazelcast.jet.sql.impl.connector.map.MapIndexScanP.complete(MapIndexScanP.java:141)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.complete(ProcessorTasklet.java:491)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:385)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:255)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:388)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:895)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.run(TaskletExecutionService.java:356)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.hazelcast.query.QueryException: java.lang.UnsupportedOperationException
	at com.hazelcast.query.impl.getters.Extractors.extract(Extractors.java:83)
	at com.hazelcast.sql.impl.extract.GenericFieldExtractor.get(GenericFieldExtractor.java:49)
	... 16 more
Caused by: java.lang.UnsupportedOperationException
	at com.hazelcast.jet.impl.serialization.DelegatingSerializationService.readAsInternalGenericRecord(DelegatingSerializationService.java:109)
	at com.hazelcast.query.impl.getters.PortableGetter.getValue(PortableGetter.java:39)
	at com.hazelcast.query.impl.getters.Getter.getValue(Getter.java:48)
	at com.hazelcast.query.impl.getters.Extractors.extract(Extractors.java:81)
	... 17 more
```

**Expected behavior**

It should work

**To Reproduce**

See the test logic and code above

**Additional context**

The test started to fail today 11th August 2021

Same result with Java client.

**NOTE: This test passes on server that started without remote controller, it only fails with remote controller.**

**Comment by srknzl** [comment]
Update: works on os jar with remote controller, not with enterprise jar. I guess enterprise snapshot jar is old.

**Comment by srknzl** [comment]
Related to enterprise jar not being regenerated after an os change, closing
