### ISSUE TITLE
com.hazelcast.sql_slow.SqlBasicClientSlowTest.testSelect

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#19343]
_master_ (commit 3dd85ea80cdd4e3ecd65708929c039053bc12040)

Failed on IBM JDK 8: http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-IbmJDK8-nightly/13/testReport/com.hazelcast.sql_slow/SqlBasicClientSlowTest/

Failed with variants:
- `[cursorBufferSize:1, dataSetSize:1, serializationMode:DATA_SERIALIZABLE, inMemoryFormat:OBJECT]`
- `[cursorBufferSize:1, dataSetSize:1, serializationMode:DATA_SERIALIZABLE, inMemoryFormat:BINARY]`
- `[cursorBufferSize:1, dataSetSize:1, serializationMode:PORTABLE, inMemoryFormat:BINARY]`
- `[cursorBufferSize:16, dataSetSize:1, serializationMode:IDENTIFIED_DATA_SERIALIZABLE, inMemoryFormat:BINARY]`
- `[cursorBufferSize:256, dataSetSize:1, serializationMode:PORTABLE, inMemoryFormat:OBJECT]`
- `[cursorBufferSize:256, dataSetSize:1, serializationMode:PORTABLE, inMemoryFormat:BINARY]`
- `[cursorBufferSize:256, dataSetSize:256, serializationMode:SERIALIZABLE, inMemoryFormat:BINARY]`
- `[cursorBufferSize:4,096, dataSetSize:1, serializationMode:SERIALIZABLE, inMemoryFormat:BINARY]`
- `[cursorBufferSize:4,096, dataSetSize:1, serializationMode:IDENTIFIED_DATA_SERIALIZABLE, inMemoryFormat:BINARY]`
- `[cursorBufferSize:4,096, dataSetSize:1, serializationMode:PORTABLE, inMemoryFormat:OBJECT]`
- `[cursorBufferSize:4,096, dataSetSize:256, serializationMode:SERIALIZABLE, inMemoryFormat:BINARY]`

All tests failed with `expected:<1> but was:<0>`

Stacktrace for `[cursorBufferSize:1, dataSetSize:1, serializationMode:DATA_SERIALIZABLE, inMemoryFormat:OBJECT]` as an example:
```
java.lang.AssertionError: expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at com.hazelcast.sql.SqlBasicTest.testSelect(SqlBasicTest.java:299)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.lang.Thread.run(Thread.java:822)
```

Standard output for `[cursorBufferSize:1, dataSetSize:1, serializationMode:DATA_SERIALIZABLE, inMemoryFormat:OBJECT]` as an example:
```
08:08:51,638 DEBUG || - [JetSqlBackend] hz.zealous_nightingale.client-query.thread-1 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Before logical opt:
LogicalProject(key=[$0], booleanVal=[$3], tinyIntVal=[$16], smallIntVal=[$13], intVal=[$9], bigIntVal=[$2], realVal=[$12], doubleVal=[$8], decimalBigIntegerVal=[$6], decimalVal=[$7], charVal=[$4], varcharVal=[$22], dateVal=[$5], timeVal=[$14], timestampVal=[$15], tsTzDateVal=[$18], tsTzCalendarVal=[$17], tsTzInstantVal=[$19], tsTzOffsetDateTimeVal=[$20], tsTzZonedDateTimeVal=[$21], objectVal=[$11], nullVal=[$10])
  LogicalTableScan(table=[[hazelcast, partitioned, map_object[projects=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]]]])

08:08:51,639 DEBUG || - [JetSqlBackend] hz.zealous_nightingale.client-query.thread-1 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] After logical opt:
FullScanLogicalRel(table=[[hazelcast, partitioned, map_object[projects=[0, 3, 16, 13, 9, 2, 12, 8, 6, 7, 4, 22, 5, 14, 15, 18, 17, 19, 20, 21, 11, 10]]]])

08:08:51,640 DEBUG || - [JetSqlBackend] hz.zealous_nightingale.client-query.thread-1 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] After physical opt:
FullScanPhysicalRel(table=[[hazelcast, partitioned, map_object[projects=[0, 3, 16, 13, 9, 2, 12, 8, 6, 7, 4, 22, 5, 14, 15, 18, 17, 19, 20, 21, 11, 10]]]])

08:08:51,642 DEBUG || - [LightMasterContext] hz.zealous_nightingale.client-query.thread-1 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Start executing light job 06a7-bf41-2e00-0001, execution graph in DOT format:
digraph DAG {
	"IMap[partitioned.map_object]" [localParallelism=1];
	"Project(IMap[partitioned.map_object])" [localParallelism=default];
	"ClientSink" [localParallelism=1];
	"IMap[partitioned.map_object]" -> "Project(IMap[partitioned.map_object])" [label="isolated", queueSize=1024];
	"Project(IMap[partitioned.map_object])" -> "ClientSink" [label="distributed to [127.0.0.1]:5701-partitioned", queueSize=1024];
}
HINT: You can use graphviz or http://viz-js.com to visualize the printed graph.
08:08:51,642 DEBUG || - [LightMasterContext] hz.zealous_nightingale.client-query.thread-1 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Building execution plan for 06a7-bf41-2e00-0001
08:08:51,642 DEBUG || - [LightMasterContext] hz.zealous_nightingale.client-query.thread-1 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Built execution plans for 06a7-bf41-2e00-0001
08:08:51,642 DEBUG || - [InitExecutionOperation] hz.zealous_nightingale.client-query.thread-1 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Initializing execution plan for job 06a7-bf41-2e00-0001, execution 06a7-bf41-2e00-0001 from [127.0.0.1]:5701
08:08:51,643 DEBUG || - [JobExecutionService] hz.zealous_nightingale.client-query.thread-1 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Execution plan for light job ID=06a7-bf41-2e00-0001, jobName='06a7-bf41-2e00-0001', executionId=06a7-bf41-2e00-0001 initialized, will start the execution
08:08:51,644 DEBUG || - [InitExecutionOperation] hz.naughty_nightingale.generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Initializing execution plan for job 06a7-bf41-2e00-0001, execution 06a7-bf41-2e00-0001 from [127.0.0.1]:5701
08:08:51,647 DEBUG || - [JobExecutionService] hz.naughty_nightingale.generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Execution plan for light job ID=06a7-bf41-2e00-0001, jobName='06a7-bf41-2e00-0001', executionId=06a7-bf41-2e00-0001 initialized, will start the execution
08:08:51,648 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-3 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Completed execution of job '06a7-bf41-2e00-0001', execution 06a7-bf41-2e00-0001
08:08:51,648 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-2 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Completed execution of job '06a7-bf41-2e00-0001', execution 06a7-bf41-2e00-0001
08:08:51,648 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-3 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Execution of job '06a7-bf41-2e00-0001', execution 06a7-bf41-2e00-0001 completed
08:08:51,648 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-2 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Execution of job '06a7-bf41-2e00-0001', execution 06a7-bf41-2e00-0001 completed
08:08:51,705 DEBUG || - [LightMasterContext] hz.naughty_nightingale.client-query.thread-3 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Start executing light job 06a7-bf40-f602-0002, execution graph in DOT format:
digraph DAG {
	"IMap[partitioned.map_object]" [localParallelism=1];
	"Project(IMap[partitioned.map_object])" [localParallelism=default];
	"ClientSink" [localParallelism=1];
	"IMap[partitioned.map_object]" -> "Project(IMap[partitioned.map_object])" [label="isolated", queueSize=1024];
	"Project(IMap[partitioned.map_object])" -> "ClientSink" [label="distributed to [127.0.0.1]:5702-partitioned", queueSize=1024];
}
HINT: You can use graphviz or http://viz-js.com to visualize the printed graph.
08:08:51,706 DEBUG || - [LightMasterContext] hz.naughty_nightingale.client-query.thread-3 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Building execution plan for 06a7-bf40-f602-0002
08:08:51,706 DEBUG || - [LightMasterContext] hz.naughty_nightingale.client-query.thread-3 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Built execution plans for 06a7-bf40-f602-0002
08:08:51,708 DEBUG || - [InitExecutionOperation] hz.zealous_nightingale.generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Initializing execution plan for job 06a7-bf40-f602-0002, execution 06a7-bf40-f602-0002 from [127.0.0.1]:5702
08:08:51,708 DEBUG || - [InitExecutionOperation] hz.naughty_nightingale.client-query.thread-3 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Initializing execution plan for job 06a7-bf40-f602-0002, execution 06a7-bf40-f602-0002 from [127.0.0.1]:5702
08:08:51,709 DEBUG || - [JobExecutionService] hz.naughty_nightingale.client-query.thread-3 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Execution plan for light job ID=06a7-bf40-f602-0002, jobName='06a7-bf40-f602-0002', executionId=06a7-bf40-f602-0002 initialized, will start the execution
08:08:51,709 DEBUG || - [JobExecutionService] hz.zealous_nightingale.generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Execution plan for light job ID=06a7-bf40-f602-0002, jobName='06a7-bf40-f602-0002', executionId=06a7-bf40-f602-0002 initialized, will start the execution
08:08:51,713 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-2 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Completed execution of job '06a7-bf40-f602-0002', execution 06a7-bf40-f602-0002
08:08:51,713 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-2 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Execution of job '06a7-bf40-f602-0002', execution 06a7-bf40-f602-0002 completed
08:08:51,713 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-2 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Completed execution of job '06a7-bf40-f602-0002', execution 06a7-bf40-f602-0002
08:08:51,713 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-2 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Execution of job '06a7-bf40-f602-0002', execution 06a7-bf40-f602-0002 completed
BuildInfo right after testSelect[cursorBufferSize:1, dataSetSize:1, serializationMode:DATA_SERIALIZABLE, inMemoryFormat:OBJECT](com.hazelcast.sql_slow.SqlBasicClientSlowTest): BuildInfo{version='5.0-SNAPSHOT', build='20210816', buildNumber=20210816, revision=3dd85ea, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'testSelect[cursorBufferSize:1, dataSetSize:1, serializationMode:DATA_SERIALIZABLE, inMemoryFormat:OBJECT](com.hazelcast.sql_slow.SqlBasicClientSlowTest):'
08:08:50, accumulated pauses: 185 ms, max pause: 171 ms, pauses over 1000 ms: 0
```

**Comment by olukas** [comment]
Failed also on Sonar build (Oracle JDK 11): http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/955/testReport/com.hazelcast.sql_slow/SqlBasicClientSlowTest/

Failed in variants:
- `[cursorBufferSize:1, dataSetSize:1, serializationMode:SERIALIZABLE, inMemoryFormat:BINARY]`
- `[cursorBufferSize:256, dataSetSize:1, serializationMode:IDENTIFIED_DATA_SERIALIZABLE, inMemoryFormat:BINARY]`
- `[cursorBufferSize:4,096, dataSetSize:1, serializationMode:SERIALIZABLE, inMemoryFormat:BINARY]`

**Comment by gierlachg** [comment]
I tried to reproduce it without luck unfortunately (Jenkins builds don't exist anymore either...). Let's reopen if it pops up again.

**Comment by mmedenjak** [comment]
Even though jenkins prunes older builds, the build logs from failed builds are (almost always) archived in S3:

https://console.aws.amazon.com/s3/object/j-artifacts?region=us-east-1&prefix=Hazelcast-master-IbmJDK8-nightly/13/Hazelcast-master-IbmJDK8-nightly-13.tar

https://console.aws.amazon.com/s3/buckets/j-artifacts?region=us-east-1&prefix=Hazelcast-master-sonar/955/&showversions=false

And both jobs still exist:
- http://jenkins.hazelcast.com/job/Hazelcast-master-IbmJDK8-nightly
- http://jenkins.hazelcast.com/job/Hazelcast-master-sonar
