### ISSUE TITLE
com.hazelcast.sql_slow.ComparisonPredicateIntegrationSlowTest

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#19363]
_master_ (commit a8f10450501d1f5be4d1cdf187571171a66e0cb9)

Failed on Sonar (Oracle JDK 11): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/956/testReport/com.hazelcast.sql_slow/ComparisonPredicateIntegrationSlowTest/

Almost all tests from `ComparisonPredicateIntegrationSlowTest` failed due to `Hazelcast instance is not active!` (only `testCompare_LocalDateTime_with_String[mode:EQ]` and `testCompare_LocalTime_with_LocalTime[mode:EQ]` passed)

Stacktrace for `testNumeric[mode:EQ]` as an example:
```
com.hazelcast.sql.HazelcastSqlException: The Jet SQL job failed: Hazelcast instance is not active!
	at com.hazelcast.sql.impl.QueryUtils.toPublicException(QueryUtils.java:79)
	at com.hazelcast.jet.sql.impl.JetSqlResultImpl$RowToSqlRowIterator.hasNext(JetSqlResultImpl.java:131)
	at com.hazelcast.sql.impl.SqlTestSupport.executeStatement(SqlTestSupport.java:224)
	at com.hazelcast.sql.impl.SqlTestSupport.execute(SqlTestSupport.java:217)
	at com.hazelcast.sql.impl.expression.ExpressionTestSupport.checkValue0(ExpressionTestSupport.java:186)
	at com.hazelcast.sql.impl.expression.predicate.ComparisonPredicateIntegrationTest.check(ComparisonPredicateIntegrationTest.java:676)
	at com.hazelcast.sql.impl.expression.predicate.ComparisonPredicateIntegrationTest.checkCommute(ComparisonPredicateIntegrationTest.java:663)
	at com.hazelcast.sql.impl.expression.predicate.ComparisonPredicateIntegrationTest.putCheckCommute(ComparisonPredicateIntegrationTest.java:658)
	at com.hazelcast.sql.impl.expression.predicate.ComparisonPredicateIntegrationTest.checkNumeric(ComparisonPredicateIntegrationTest.java:546)
	at com.hazelcast.sql.impl.expression.predicate.ComparisonPredicateIntegrationTest.testNumeric(ComparisonPredicateIntegrationTest.java:206)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.hazelcast.sql.impl.QueryException: The Jet SQL job failed: Hazelcast instance is not active!
	at com.hazelcast.sql.impl.QueryException.error(QueryException.java:60)
	at com.hazelcast.jet.sql.impl.JetPlanExecutor.lambda$execute$2(JetPlanExecutor.java:225)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at com.hazelcast.jet.impl.util.NonCompletableFuture.internalCompleteExceptionally(NonCompletableFuture.java:72)
	at com.hazelcast.jet.impl.AbstractJobProxy$CallbackBase.accept(AbstractJobProxy.java:367)
	at com.hazelcast.jet.impl.AbstractJobProxy$CallbackBase.accept(AbstractJobProxy.java:350)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$WhenCompleteNode.lambda$execute$0(AbstractInvocationFuture.java:1563)
	at com.hazelcast.test.TestLoggingUtils$CustomTestNameAwareForkJoinPool$TestNameAwareRunnable.run(TestLoggingUtils.java:104)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: com.hazelcast.core.HazelcastInstanceNotActiveException: Hazelcast instance is not active!
	at com.hazelcast.spi.impl.operationservice.impl.InvocationRegistry.shutdown(InvocationRegistry.java:229)
	at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.shutdownInvocations(OperationServiceImpl.java:534)
	at com.hazelcast.spi.impl.NodeEngineImpl.shutdown(NodeEngineImpl.java:541)
	at com.hazelcast.instance.impl.Node.shutdownServices(Node.java:589)
	at com.hazelcast.instance.impl.Node.shutdown(Node.java:528)
	at com.hazelcast.instance.impl.LifecycleServiceImpl.shutdown(LifecycleServiceImpl.java:101)
	at com.hazelcast.instance.impl.LifecycleServiceImpl.shutdown(LifecycleServiceImpl.java:84)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.shutdownAll(HazelcastInstanceFactory.java:300)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.shutdownAll(HazelcastInstanceFactory.java:274)
	at com.hazelcast.core.Hazelcast.shutdownAll(Hazelcast.java:44)
	at com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:45)
	at com.hazelcast.test.OverridePropertyRule$1.evaluate(OverridePropertyRule.java:66)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by Fly-Style** [comment]
Fixed by https://github.com/hazelcast/hazelcast/pull/19412.
