### ISSUE TITLE
Persistence's auto-remove-stale-data configuration is not permitted

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#19373]
When I start hot-restart enabled 5.0-BETA-2 cluster with this yaml config:
```
hazelcast:
  hot-restart-persistence:
    enabled: true
    auto-remove-stale-data: true
```
I encounter error below:
```
Exception in thread "main" extraneous key [auto-remove-stale-data] is not permitted
  instance location: #/hazelcast/persistence
  keyword location: #/definitions/Persistence

	at com.hazelcast.internal.config.YamlConfigSchemaValidator.wrap(YamlConfigSchemaValidator.java:66)
	at com.hazelcast.internal.config.YamlConfigSchemaValidator.validate(YamlConfigSchemaValidator.java:97)
	at com.hazelcast.config.YamlConfigBuilder.parseAndBuildConfig(YamlConfigBuilder.java:163)
	at com.hazelcast.config.YamlConfigBuilder.build(YamlConfigBuilder.java:134)
	at com.hazelcast.config.YamlConfigBuilder.build(YamlConfigBuilder.java:127)
	at com.hazelcast.config.Config.loadFromFile(Config.java:245)
	at com.hazelcast.config.Config.load(Config.java:224)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:125)
	at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:95)
	at test.Server.main(Server.java:12)
```

**Comment by mmedenjak** [comment]
See also [discussion on slack](https://hazelcast.slack.com/archives/C01JU7ZJYGP/p1629363416245600).

**Comment by mmedenjak** [comment]
When fixing this, please consider adding a test which will prevent issues like this in the future.
