### ISSUE TITLE
com.hazelcast.map.LocalIndexStatsTest.testInsertsTracking [HZ-1792]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#19375]
_master_ (commit a8f10450501d1f5be4d1cdf187571171a66e0cb9)

Failed on Zing JDK 8: http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZingJDK8/330/testReport/com.hazelcast.map/LocalIndexStatsTest/testInsertsTracking_format_OBJECT_/

Failed with option `[format:OBJECT]`.

Stacktrace:
```
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at com.hazelcast.map.LocalIndexStatsTest.testInsertsTracking(LocalIndexStatsTest.java:489)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

Standard output:
```
09:40:06,498  INFO |testIndexStatsAfterMapDestroy[format:OBJECT]| - [LifecycleService] Thread-48399 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
09:40:06,498  WARN |testIndexStatsAfterMapDestroy[format:OBJECT]| - [Node] Thread-48399 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Terminating forcefully...
09:40:06,498  INFO |testIndexStatsAfterMapDestroy[format:OBJECT]| - [Node] Thread-48399 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Shutting down connection manager...
09:40:06,498  INFO |testIndexStatsAfterMapDestroy[format:OBJECT]| - [Node] Thread-48399 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Shutting down node engine...
09:40:06,521  INFO |testInsertsTracking[format:OBJECT]| - [NodeExtension] Thread-48391 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Destroying node NodeExtension.
09:40:06,521  INFO |testInsertsTracking[format:OBJECT]| - [Node] Thread-48391 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Hazelcast Shutdown is completed in 41 ms.
09:40:06,521  INFO |testInsertsTracking[format:OBJECT]| - [LifecycleService] Thread-48391 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
BuildInfo right after testInsertsTracking[format:OBJECT](com.hazelcast.map.LocalIndexStatsTest): BuildInfo{version='5.0-SNAPSHOT', build='20210819', buildNumber=20210819, revision=a8f1045, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'testInsertsTracking[format:OBJECT](com.hazelcast.map.LocalIndexStatsTest):'
09:40:05, accumulated pauses: 1500 ms, max pause: 25 ms, pauses over 1000 ms: 0
```

**Comment by olukas** [comment]
Failed on `5.1.z` on ZingJDK8 in variant `[format:BINARY]`: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-ZingJDK8/89/testReport/com.hazelcast.map/LocalIndexStatsTest/testInsertsTracking_format_BINARY_/
