### ISSUE TITLE
NullPointerException in JobExecutionService

### ISSUE THREAD

**Issue by gierlachg** [hazelcast/hazelcast#19394]
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/6809/testReport/junit/com.hazelcast.jet.sql/SqlFilterProjectTest/test_dynamicParameterMetadata/

```
java.lang.NullPointerException
	at com.hazelcast.jet.impl.JobExecutionService.parentClassLoader(JobExecutionService.java:188)
	at com.hazelcast.jet.impl.JobExecutionService.lambda$null$2(JobExecutionService.java:179)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.hazelcast.jet.impl.JobExecutionService.lambda$getClassLoader$3(JobExecutionService.java:177)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at com.hazelcast.jet.impl.JobExecutionService.getClassLoader(JobExecutionService.java:176)
	at com.hazelcast.jet.impl.execution.ExecutionContext.completeExecution(ExecutionContext.java:254)
	at com.hazelcast.jet.impl.JobExecutionService.lambda$completeExecution$559b0d71$1(JobExecutionService.java:525)
	at com.hazelcast.jet.function.RunnableEx.run(RunnableEx.java:31)
	at com.hazelcast.jet.impl.util.Util.doWithClassLoader(Util.java:507)
	at com.hazelcast.jet.impl.JobExecutionService.completeExecution(JobExecutionService.java:525)
	at com.hazelcast.jet.impl.JobExecutionService.terminateExecution0(JobExecutionService.java:713)
	at com.hazelcast.jet.impl.JobExecutionService.cancelAllExecutions(JobExecutionService.java:297)
	at com.hazelcast.jet.SimpleTestInClusterSupport.supportAfter(SimpleTestInClusterSupport.java:102)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:381)
	at com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37)
	at com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:104)
	at com.hazelcast.test.metrics.MetricsRule$1.evaluate(MetricsRule.java:62)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:50)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:29)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:39)
	at com.hazelcast.test.OverridePropertyRule$1.evaluate(OverridePropertyRule.java:66)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Danny-Hazelcast** [comment]
same issue

http://jenkins.hazelcast.com/view/split/job/split-x3/43/console
/disk1/workspace/split-x3/5.0-SNAPSHOT/2021_08_24-12_21_16/sql/bit-map

also the cluster failed to merge after split

```
SEVERE: [10.0.0.77]:5701 [HZ] [5.0-SNAPSHOT] Failed to query live light executions: java.lang.NullPointerException
java.lang.NullPointerException
	at com.hazelcast.jet.impl.JobExecutionService.parentClassLoader(JobExecutionService.java:188)
	at com.hazelcast.jet.impl.JobExecutionService.lambda$null$2(JobExecutionService.java:179)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.hazelcast.jet.impl.JobExecutionService.lambda$getClassLoader$3(JobExecutionService.java:177)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1737)
	at com.hazelcast.jet.impl.JobExecutionService.getClassLoader(JobExecutionService.java:176)
	at com.hazelcast.jet.impl.execution.ExecutionContext.completeExecution(ExecutionContext.java:254)
	at com.hazelcast.jet.impl.JobExecutionService.lambda$completeExecution$559b0d71$1(JobExecutionService.java:525)
	at com.hazelcast.jet.function.RunnableEx.run(RunnableEx.java:31)
	at com.hazelcast.jet.impl.util.Util.doWithClassLoader(Util.java:507)
	at com.hazelcast.jet.impl.JobExecutionService.completeExecution(JobExecutionService.java:525)
	at com.hazelcast.jet.impl.JobExecutionService.terminateExecution0(JobExecutionService.java:713)
	at com.hazelcast.jet.impl.JobExecutionService.checkLightExecutions(JobExecutionService.java:635)
	at com.hazelcast.spi.impl.executionservice.impl.DelegateAndSkipOnConcurrentExecutionDecorator$DelegateDecorator.run(DelegateAndSkipOnConcurrentExecutionDecorator.java:77)
	at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
```
