### ISSUE TITLE
JetException: Cannot do this task on non-master  jobId  Master address: null

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#19406]
client calling  jet.newJob(p);  on cluster with members being shutdown and restarted,  client throws below exception.  probably expected ?

com.hazelcast.jet.JetException: Cannot do this task on non-master. jobId=06b2-cddc-52dd-000e. Master address: null
	at com.hazelcast.jet.impl.JobCoordinationService.assertIsMaster(JobCoordinationService.java:1208)
	at com.hazelcast.jet.impl.JobCoordinationService.callWithJob(JobCoordinationService.java:823)
	at com.hazelcast.jet.impl.JobCoordinationService.getJobStatus(JobCoordinationService.java:573)
	at com.hazelcast.jet.impl.operation.GetJobStatusOperation.doRun(GetJobStatusOperation.java:36)
	at com.hazelcast.jet.impl.operation.AsyncOperation.run(AsyncOperation.java:54)
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:196)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:273)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:249)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:470)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:197)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:137)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
	at ------ submitted from ------.()
	at com.hazelcast.internal.util.ExceptionUtil.cloneExceptionWithFixedAsyncStackTrace(ExceptionUtil.java:279)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.returnOrThrowWithGetConventions(InvocationFuture.java:112)
	at com.hazelcast.client.impl.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:95)
	at com.hazelcast.client.impl.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:40)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:617)
	at com.hazelcast.jet.impl.ClientJobProxy.lambda$getStatus0$0(ClientJobProxy.java:86)
	at com.hazelcast.jet.impl.ClientJobProxy.callAndRetryIfTargetNotFound(ClientJobProxy.java:232)
	at com.hazelcast.jet.impl.ClientJobProxy.getStatus0(ClientJobProxy.java:84)
	at com.hazelcast.jet.impl.AbstractJobProxy.getStatus(AbstractJobProxy.java:180)

operation should be retried with the new master... So it could be improved.

**Comment by frant-hartm** [comment]
`jet.newJob(p);` doesn't correspond to `AbstractJobProxy.getStatus` in the stack trace.

@Danny-Hazelcast confirmed the test also calls `getStatus` on the returned job instance, resulting in the stack trace.

**Comment by Danny-Hazelcast** [comment]
should getStatus() be retried with the new master ?

if not we can close this issue

**Comment by viliam-durina** [comment]
I'd like to ask if there are any split-brain merges happening in the test? Because the client has information that some member is a master, before the member itself knows it's a master. This could happen during split-brain merge when a member is master and stops being master, but not otherwise. But I'm not very familiar about this process, so maybe there's another scenario.

**Comment by viliam-durina** [comment]
>should getStatus() be retried with the new master?
It definitely should. We actually retry it, but only for a set of specific reasons. The one in this issue is not among them. Since `getStatus()` is read-only, it's probably safe to retry it for any failure, except for JobNotFoundException or client-not-connected and such. It's not safe to retry `newJob()` for any failure because it's not idempotent, even though we can include the exception in this issue in the list I think.
