### ISSUE TITLE
NullPointerException (Target is required! Preconditions.java:59). (SenderTasklet.call(SenderTasklet.java:114).  (JobTerminateRequestedException.java:28) (ProcessorTasklet.java:629)

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#19428]
5.0-SNAPSHOT (20210827 - 7e99ac3, 4dadc2d) starting
#### Remaining Ones
jet split brain test /disk1/workspace/split-x/5.0-SNAPSHOT/2021_08_27-09_37_33/jet
```
./output/HZ/HzMember2HZAA/out.txt-SEVERE: [10.0.0.144]:5701 [HZ] [5.0-SNAPSHOT] Target is required!
./output/HZ/HzMember2HZAA/out.txt:java.lang.NullPointerException: Target is required!
./output/HZ/HzMember2HZAA/out.txt:	at com.hazelcast.internal.util.Preconditions.checkNotNull(Preconditions.java:59)
./output/HZ/HzMember2HZAA/out.txt-	at com.hazelcast.spi.impl.operationservice.impl.OutboundOperationHandler.send(OutboundOperationHandler.java:45)
./output/HZ/HzMember2HZAA/out.txt-	at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.send(OperationServiceImpl.java:466)
./output/HZ/HzMember2HZAA/out.txt-	at com.hazelcast.jet.impl.JobExecutionService.verifyClusterInformation(JobExecutionService.java:456)
./output/HZ/HzMember2HZAA/out.txt-	at com.hazelcast.jet.impl.JobExecutionService.runLightJob(JobExecutionService.java:329)
./output/HZ/HzMember2HZAA/out.txt-	at com.hazelcast.jet.impl.operation.InitExecutionOperation.doRun(InitExecutionOperation.java:93)
./output/HZ/HzMember2HZAA/out.txt-	at com.hazelcast.jet.impl.operation.AsyncOperation.run(AsyncOperation.java:54)
./output/HZ/HzMember2HZAA/out.txt-	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:196)
./output/HZ/HzMember2HZAA/out.txt-	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:273)
./output/HZ/HzMember2HZAA/out.txt-	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:249)
./output/HZ/HzMember2HZAA/out.txt-	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:214)
./output/HZ/HzMember2HZAA/out.txt-	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:411)
./output/HZ/HzMember2HZAA/out.txt-	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:438)
./output/HZ/HzMember2HZAA/out.txt-	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:600)
./output/HZ/HzMember2HZAA/out.txt-	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:579)
./output/HZ/HzMember2HZAA/out.txt-	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:540)
./output/HZ/HzMember2HZAA/out.txt-	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:240)
./output/HZ/HzMember2HZAA/out.txt-	at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:59)
./output/HZ/HzMember2HZAA/out.txt-	at com.hazelcast.jet.impl.LightMasterContext.invokeOnParticipant(LightMasterContext.java:220)
./output/HZ/HzMember2HZAA/out.txt-	at com.hazelcast.jet.impl.LightMasterContext.invokeOnParticipants(LightMasterContext.java:206)
./output/HZ/HzMember2HZAA/out.txt-	at com.hazelcast.jet.impl.LightMasterContext.<init>(LightMasterContext.java:137)
```

```
SEVERE: [10.0.0.91]:5701 [HZ] [5.0-SNAPSHOT] job '06b5-fdbb-8a25-0005', execution 06b5-fdbb-8a25-0005 encountered an exception in Processor.close(), ignoring it
java.lang.NullPointerException
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.close(ProcessorTasklet.java:629)
	at com.hazelcast.jet.impl.execution.ExecutionContext.completeExecution(ExecutionContext.java:246)
	at com.hazelcast.jet.impl.JobExecutionService.lambda$completeExecution$559b0d71$1(JobExecutionService.java:528)
	at com.hazelcast.jet.function.RunnableEx.run(RunnableEx.java:31)
	at com.hazelcast.jet.impl.util.Util.doWithClassLoader(Util.java:516)
	at com.hazelcast.jet.impl.JobExecutionService.completeExecution(JobExecutionService.java:528)
	at com.hazelcast.jet.impl.JobExecutionService.lambda$beginExecution0$14(JobExecutionService.java:593)
	at com.hazelcast.jet.impl.util.ExceptionUtil.lambda$withTryCatch$0(ExceptionUtil.java:172)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

#### Resolved Ones

```
Aug 27, 2021 9:41:57 AM com.hazelcast.jet.impl.EnterpriseMasterContext
SEVERE: [10.0.0.91]:5701 [HZ] [5.0-SNAPSHOT] Exception during callback
java.lang.NullPointerException
	at com.hazelcast.jet.impl.exception.JobTerminateRequestedException.<init>(JobTerminateRequestedException.java:28)
	at com.hazelcast.jet.impl.MasterJobContext.onStartExecutionComplete(MasterJobContext.java:602)
	at com.hazelcast.jet.impl.MasterJobContext.lambda$invokeStartExecution$6(MasterJobContext.java:473)
	at com.hazelcast.jet.impl.MasterContext.lambda$invokeOnParticipant$3(MasterContext.java:312)
	at com.hazelcast.jet.impl.util.ExceptionUtil.lambda$withTryCatch$0(ExceptionUtil.java:172)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$WhenCompleteNode.lambda$execute$0(AbstractInvocationFuture.java:1563)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```
 which is addressed on #19460

```
Aug 27, 2021 10:31:37 AM com.hazelcast.jet.impl.execution.TaskletExecutionService
WARNING: [10.0.0.64]:5701 [HZ] [5.0-SNAPSHOT] Exception in SenderTasklet{ordinal=0, destinationAddress=[10.0.0.204]:5701, sourceVertexName='Index(IMap[partitioned.mapBak1HD_put-addidx])'}
java.lang.NullPointerException
	at com.hazelcast.jet.impl.execution.SenderTasklet.call(SenderTasklet.java:114)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:388)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.run(TaskletExecutionService.java:356)
	at java.base/java.lang.Thread.run(Thread.java:829)
``` 
which is addressed on #19471 (I think it's ready to merge)

**Comment by ufukyilmaz** [comment]
```
SEVERE: [10.0.0.91]:5701 [HZ] [5.0-SNAPSHOT] Exception during callback
java.lang.NullPointerException
	at com.hazelcast.jet.impl.exception.JobTerminateRequestedException.<init>(JobTerminateRequestedException.java:28)
	at com.hazelcast.jet.impl.MasterJobContext.onStartExecutionComplete(MasterJobContext.java:602)
	at com.hazelcast.jet.impl.MasterJobContext.lambda$invokeStartExecution$6(MasterJobContext.java:473)
	at com.hazelcast.jet.impl.MasterContext.lambda$invokeOnParticipant$3(MasterContext.java:312)
	....
```

We get this NPE if the job execution in some member is removed through [JobExecutionService#onMemberRemoved](https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/jet/impl/JobExecutionService.java#L313-L317) call right after an execution InitExecution is performed and before StartExecutionOperation is performed on this member.

**Comment by Danny-Hazelcast** [comment]
Hazelcast Enterprise 5.0-SNAPSHOT (20210907 - ed9b06e, e00b788) starting


```
./output/HZ/HzMember1HZAA/out.txt-SEVERE: [10.0.0.55]:5701 [HZ] [5.0-SNAPSHOT] Exception during callback
./output/HZ/HzMember1HZAA/out.txt:java.lang.NullPointerException
./output/HZ/HzMember1HZAA/out.txt-	at com.hazelcast.jet.impl.exception.JobTerminateRequestedException.<init>(JobTerminateRequestedException.java:28)
./output/HZ/HzMember1HZAA/out.txt-	at com.hazelcast.jet.impl.MasterJobContext.onStartExecutionComplete(MasterJobContext.java:602)
./output/HZ/HzMember1HZAA/out.txt-	at com.hazelcast.jet.impl.MasterJobContext.lambda$invokeStartExecution$6(MasterJobContext.java:473)
./output/HZ/HzMember1HZAA/out.txt-	at com.hazelcast.jet.impl.MasterContext.lambda$invokeOnParticipant$3(MasterContext.java:312)
./output/HZ/HzMember1HZAA/out.txt-	at com.hazelcast.jet.impl.util.ExceptionUtil.lambda$withTryCatch$0(ExceptionUtil.java:172)
./output/HZ/HzMember1HZAA/out.txt-	at com.hazelcast.spi.impl.AbstractInvocationFuture$WhenCompleteNode.lambda$execute$0(AbstractInvocationFuture.java:1563)
./output/HZ/HzMember1HZAA/out.txt-	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
./output/HZ/HzMember1HZAA/out.txt-	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
./output/HZ/HzMember1HZAA/out.txt-	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
./output/HZ/HzMember1HZAA/out.txt-	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
--
./output/HZ/HzMember1HZAA/out.txt-SEVERE: [10.0.0.55]:5701 [HZ] [5.0-SNAPSHOT] Target is required!
./output/HZ/HzMember1HZAA/out.txt:java.lang.NullPointerException: Target is required!
./output/HZ/HzMember1HZAA/out.txt-	at com.hazelcast.internal.util.Preconditions.checkNotNull(Preconditions.java:59)
./output/HZ/HzMember1HZAA/out.txt-	at com.hazelcast.spi.impl.operationservice.impl.OutboundOperationHandler.send(OutboundOperationHandler.java:45)
./output/HZ/HzMember1HZAA/out.txt-	at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.send(OperationServiceImpl.java:466)
./output/HZ/HzMember1HZAA/out.txt-	at com.hazelcast.jet.impl.JobExecutionService.verifyClusterInformation(JobExecutionService.java:456)
./output/HZ/HzMember1HZAA/out.txt-	at com.hazelcast.jet.impl.JobExecutionService.runLightJob(JobExecutionService.java:329)
./output/HZ/HzMember1HZAA/out.txt-	at com.hazelcast.jet.impl.operation.InitExecutionOperation.doRun(InitExecutionOperation.java:93)
./output/HZ/HzMember1HZAA/out.txt-	at com.hazelcast.jet.impl.operation.AsyncOperation.run(AsyncOperation.java:54)
./output/HZ/HzMember1HZAA/out.txt-	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:196)
./output/HZ/HzMember1HZAA/out.txt-	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:273)
./output/HZ/HzMember1HZAA/out.txt-	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:249)
```


hanging at 
```
cat hangers.txt
./output/HZ/HzClient3HZBB/out.txt:	at hzcmd.jet.QuickJob.timeStep(QuickJob.java:19)
./output/HZ/HzClient3HZBB/out.txt:	at hzcmd.jet.QuickJob.timeStep(QuickJob.java:19)
./output/HZ/HzMember2HZAA/out.txt:	at hzcmd.jet.QuickLiteJob.timeStep(QuickLiteJob.java:17)
./output/HZ/HzMember2HZAA/out.txt:	at hzcmd.jet.QuickLiteJob.timeStep(QuickLiteJob.java:17)
./output/HZ/HzMember2HZAA/out.txt:	at hzcmd.jet.QuickLiteJob.timeStep(QuickLiteJob.java:17)
./output/HZ/HzMember2HZAA/out.txt:	at hzcmd.jet.LiteJobAndCancle.timeStep(LiteJobAndCancle.java:18)
./output/HZ/HzMember4HZBB/out.txt:	at hzcmd.jet.QuickJob.timeStep(QuickJob.java:19)
./output/HZ/HzClient4HZBB/out.txt:	at hzcmd.jet.QuickJob.timeStep(QuickJob.java:19)
./output/HZ/HzMember1HZAA/out.txt:	at hzcmd.jet.QuickLiteJob.timeStep(QuickLiteJob.java:17)
```

**Comment by mmedenjak** [comment]
There's also [this issue](https://github.com/hazelcast/hazelcast/issues/19103). Is it a duplicate?

**Comment by mmedenjak** [comment]
I also suggest we close this issue and open a new one, since we're now reusing this issue for different NPE's and it's getting confusing what was fixed and what isn't.

**Comment by ufukyilmaz** [comment]
#19103 is similar issue but it is not exactly same with:
```
java.lang.NullPointerException
	at com.hazelcast.jet.impl.exception.JobTerminateRequestedException.<init>(JobTerminateRequestedException.java:28)
	at com.hazelcast.jet.impl.MasterJobContext.onStartExecutionComplete(MasterJobContext.java:602)
	at com.hazelcast.jet.impl.MasterJobContext.lambda$invokeStartExecution$6(MasterJobContext.java:473)
	at com.hazelcast.jet.impl.MasterContext.lambda$invokeOnParticipant$3(MasterContext.java:312)
	....
```

**Comment by mmedenjak** [comment]
Ok, let's merge https://github.com/hazelcast/hazelcast/pull/19471 and keep this issue closed, and start opening new ones.
