### ISSUE TITLE
SQL job is hanging

### ISSUE THREAD

**Issue by viliam-durina** [hazelcast/hazelcast#19472]
Originally reported by @Danny-Hazelcast in #19319

http://jenkins.hazelcast.com/view/freeze/job/freeze-x2/32/console

/disk1/workspace/freeze-x2/5.0-SNAPSHOT/2021_08_19-09_39_54/simple-sql

hanging at
at hzcmd.map.sql.predicate.PersonIdRange.timeStep(PersonIdRange.java:23).        map.values(sqlPredicate);
at hzcmd.map.sql.service.PersonIdRange.timeStep(PersonIdRange.java:16).            sqlService.execute(sqlStatement);

```
find . -name out.txt | xargs grep Null
./output/HZ/HzMember2HZ/out.txt:java.lang.NullPointerException
./output/HZ/HzMember2HZ/out.txt:java.lang.NullPointerException
./output/HZ/HzMember1HZ/out.txt:	at com.hazelcast.spi.impl.operationservice.impl.Invocation.newTargetNullException(Invocation.java:317)
./output/HZ/HzMember1HZ/out.txt:	at com.hazelcast.spi.impl.operationservice.impl.Invocation.newTargetNullException(Invocation.java:317)
./output/HZ/HzMember1HZ/out.txt:	at com.hazelcast.spi.impl.operationservice.impl.Invocation.newTargetNullException(Invocation.java:317)
./output/HZ/HzMember1HZ/out.txt:	at com.hazelcast.spi.impl.operationservice.impl.Invocation.newTargetNullException(Invocation.java:317)
./output/HZ/HzMember1HZ/out.txt:	at com.hazelcast.spi.impl.operationservice.impl.Invocation.newTargetNullException(Invocation.java:317)
./output/HZ/HzMember1HZ/out.txt:	at com.hazelcast.spi.impl.operationservice.impl.Invocation.newTargetNullException(Invocation.java:317)
./output/HZ/HzMember1HZ/out.txt:	at com.hazelcast.spi.impl.operationservice.impl.Invocation.newTargetNullException(Invocation.java:317)
./output/HZ/HzMember1HZ/out.txt:	at com.hazelcast.spi.impl.operationservice.impl.Invocation.newTargetNullException(Invocation.java:317)
./output/HZ/HzMember1HZ/out.txt:	at com.hazelcast.spi.impl.operationservice.impl.Invocation.newTargetNullException(Invocation.java:317)
./output/HZ/HzMember1HZ/out.txt:	at com.hazelcast.spi.impl.operationservice.impl.Invocation.newTargetNullException(Invocation.java:317)
./output/HZ/HzMember1HZ/out.txt:	at com.hazelcast.spi.impl.operationservice.impl.Invocation.newTargetNullException(Invocation.java:317)
./output/HZ/HzMember1HZ/out.txt:	at com.hazelcast.spi.impl.operationservice.impl.Invocation.newTargetNullException(Invocation.java:317)
./output/HZ/HzMember1HZ/out.txt:	at com.hazelcast.spi.impl.operationservice.impl.Invocation.newTargetNullException(Invocation.java:317)
./output/HZ/HzMember1HZ/out.txt:	at com.hazelcast.spi.impl.operationservice.impl.Invocation.newTargetNullException(Invocation.java:317)
./output/HZ/HzMember1HZ/out.txt:	at com.hazelcast.spi.impl.operationservice.impl.Invocation.newTargetNullException(Invocation.java:317)
./output/HZ/HzMember1HZ/out.txt:	at com.hazelcast.spi.impl.operationservice.impl.Invocation.newTargetNullException(Invocation.java:317)
./output/HZ/HzMember1HZ/out.txt:	at com.hazelcast.spi.impl.operationservice.impl.Invocation.newTargetNullException(Invocation.java:317)
./output/HZ/HzMember1HZ/out.txt:	at com.hazelcast.spi.impl.operationservice.impl.Invocation.newTargetNullException(Invocation.java:317)
./output/HZ/HzMember1HZ/out.txt:	at com.hazelcast.spi.impl.operationservice.impl.Invocation.newTargetNullException(Invocation.java:317)
./output/HZ/HzMember1HZ/out.txt:	at com.hazelcast.spi.impl.operationservice.impl.Invocation.newTargetNullException(Invocation.java:317)
./output/HZ/HzMember1HZ/out.txt:	at com.hazelcast.spi.impl.operationservice.impl.Invocation.newTargetNullException(Invocation.java:317)
./output/HZ/HzMember1HZ/out.txt:	at com.hazelcast.spi.impl.operationservice.impl.Invocation.newTargetNullException(Invocation.java:317)
./output/HZ/HzMember1HZ/out.txt:	at com.hazelcast.spi.impl.operationservice.impl.Invocation.newTargetNullException(Invocation.java:317)
./output/HZ/HzMember1HZ/out.txt:	at com.hazelcast.spi.impl.operationservice.impl.Invocation.newTargetNullException(Invocation.java:317)
./output/HZ/HzMember1HZ/out.txt:	at com.hazelcast.spi.impl.operationservice.impl.Invocation.newTargetNullException(Invocation.java:317)
./output/HZ/HzMember1HZ/out.txt:	at com.hazelcast.spi.impl.operationservice.impl.Invocation.newTargetNullException(Invocation.java:317)
./output/HZ/HzMember1HZ/out.txt:	at com.hazelcast.spi.impl.operationservice.impl.Invocation.newTargetNullException(Invocation.java:317)
./output/HZ/HzMember1HZ/out.txt:	at com.hazelcast.spi.impl.operationservice.impl.Invocation.newTargetNullException(Invocation.java:317)
./output/HZ/HzMember1HZ/out.txt:	at com.hazelcast.spi.impl.operationservice.impl.Invocation.newTargetNullException(Invocation.java:317)
./output/HZ/HzMember1HZ/out.txt:	at com.hazelcast.spi.impl.operationservice.impl.Invocation.newTargetNullException(Invocation.java:317)
./output/HZ/HzMember1HZ/out.txt:	at com.hazelcast.spi.impl.operationservice.impl.Invocation.newTargetNullException(Invocation.java:317)
./output/HZ/HzMember1HZ/out.txt:	at com.hazelcast.spi.impl.operationservice.impl.Invocation.newTargetNullException(Invocation.java:317)
./output/HZ/HzMember1HZ/out.txt:	at com.hazelcast.spi.impl.operationservice.impl.Invocation.newTargetNullException(Invocation.java:317)
./output/HZ/HzMember1HZ/out.txt:	at com.hazelcast.spi.impl.operationservice.impl.Invocation.newTargetNullException(Invocation.java:317)
./output/HZ/HzMember1HZ/out.txt:	at com.hazelcast.spi.impl.operationservice.impl.Invocation.newTargetNullException(Invocation.java:317)
./output/HZ/HzMember1HZ/out.txt:	at com.hazelcast.spi.impl.operationservice.impl.Invocation.newTargetNullException(Invocation.java:317)
./output/HZ/HzMember1HZ/out.txt:	at com.hazelcast.spi.impl.operationservice.impl.Invocation.newTargetNullException(Invocation.java:317)
./output/HZ/HzMember1HZ/out.txt:	at com.hazelcast.spi.impl.operationservice.impl.Invocation.newTargetNullException(Invocation.java:317)
./output/HZ/HzMember1HZ/out.txt:	at com.hazelcast.spi.impl.operationservice.impl.Invocation.newTargetNullException(Invocation.java:317)
./output/HZ/HzMember1HZ/out.txt:	at com.hazelcast.spi.impl.operationservice.impl.Invocation.newTargetNullException(Invocation.java:317)
./output/HZ/HzMember1HZ/out.txt:	at com.hazelcast.spi.impl.operationservice.impl.Invocation.newTargetNullException(Invocation.java:317)
./output/HZ/HzMember1HZ/out.txt:	at com.hazelcast.spi.impl.operationservice.impl.Invocation.newTargetNullException(Invocation.java:317)
./output/HZ/HzMember1HZ/out.txt:	at com.hazelcast.spi.impl.operationservice.impl.Invocation.newTargetNullException(Invocation.java:317)
./output/HZ/HzMember1HZ/out.txt:	at com.hazelcast.spi.impl.operationservice.impl.Invocation.newTargetNullException(Invocation.java:317)
./output/HZ/HzMember1HZ/out.txt:	at com.hazelcast.spi.impl.operationservice.impl.Invocation.newTargetNullException(Invocation.java:317)
./output/HZ/HzMember1HZ/out.txt:	at com.hazelcast.spi.impl.operationservice.impl.Invocation.newTargetNullException(Invocation.java:317)
./output/HZ/HzMember1HZ/out.txt:	at com.hazelcast.spi.impl.operationservice.impl.Invocation.newTargetNullException(Invocation.java:317)
./output/HZ/HzMember3HZ/out.txt:java.lang.NullPointerException
```

cat ./output/HZ/HzMember3HZ/out.txt | grep Null -A15 -B15

```
WARNING: [10.0.0.140]:5701 [HZ] [5.0-SNAPSHOT] Exception in ReceiverTasklet
com.hazelcast.jet.RestartableException: The member was reconnected: [10.0.0.207]:5701
	at com.hazelcast.jet.impl.execution.ReceiverTasklet.call(ReceiverTasklet.java:150)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:388)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.run(TaskletExecutionService.java:356)
	at java.base/java.lang.Thread.run(Thread.java:829)

Aug 19, 2021 9:48:55 AM com.hazelcast.jet.impl.execution.TaskletExecutionService
WARNING: [10.0.0.140]:5701 [HZ] [5.0-SNAPSHOT] Exception in SenderTasklet{ordinal=0, destinationAddress=[10.0.0.207]:5701, sourceVertexName='Index(IMap[partitioned.mapBak1HDSqlIdx])'}
java.lang.NullPointerException
	at com.hazelcast.jet.impl.execution.SenderTasklet.call(SenderTasklet.java:114)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:388)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.run(TaskletExecutionService.java:356)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by viliam-durina** [comment]
@Danny-Hazelcast can you provide more information to this? 
```
hanging at
at hzcmd.map.sql.predicate.PersonIdRange.timeStep(PersonIdRange.java:23)
```
where's that code?

**Comment by Danny-Hazelcast** [comment]
https://github.com/hazelcast/hzCmd-bench/blob/zeta/src/main/java/hzcmd/map/sql/predicate/PersonIdRange.java#L23
https://github.com/hazelcast/hzCmd-bench/blob/zeta/src/main/java/hzcmd/map/sql/service/PersonIdRange.java#L16

**Comment by viliam-durina** [comment]
Then this is for the old Predicate API, changed the `Module` label.

**Comment by Danny-Hazelcast** [comment]
@viliam-durina  both the sql service and Predicate api are hanging.

predicate
https://github.com/hazelcast/hzCmd-bench/blob/zeta/src/main/java/hzcmd/map/sql/predicate/PersonIdRange.java#L23

Sql
https://github.com/hazelcast/hzCmd-bench/blob/zeta/src/main/java/hzcmd/map/sql/service/PersonIdRange.java#L16

**Comment by viliam-durina** [comment]
Do you have any more details? Like thread dump. Where exactly is it hanging? The jenkins link from the first post in this issue is 404.

**Comment by Danny-Hazelcast** [comment]
for issue https://github.com/hazelcast/hazelcast/issues/19472 SQL job is hanging #19472
latest hanging run is http://jenkins.hazelcast.com/view/freeze/job/freeze-x2/38/console
path to logs
/disk1/workspace/freeze-x2/5.0-SNAPSHOT/2021_09_09-15_41_56/simple-sql
while the test is running member jvm process are frozen and unfrozen.

**Comment by Danny-Hazelcast** [comment]
other examples of sql job hanging at http://jenkins.hazelcast.com/view/freeze/job/freeze-x3/15/console

**Comment by Danny-Hazelcast** [comment]
other examples of sql job hanging in split brain test http://jenkins.hazelcast.com/view/split/job/split-x3/54/console

**Comment by Danny-Hazelcast** [comment]
sql hanging in split brain test, with stack trace taken during the tests 
http://jenkins.hazelcast.com/view/stable/job/split-sql/83/console

**Comment by Danny-Hazelcast** [comment]
only sql service running, split brain, sql hanging,  stack trace collected 
http://jenkins.hazelcast.com/view/stable/job/split-sql-service/59/console
/disk1/workspace/split-sql-service/5.0-SNAPSHOT/2021_09_11-21_41_01/split-sql-service

**Comment by Danny-Hazelcast** [comment]
interestingly i now see the same test, which was hanging is now passing 
http://jenkins.hazelcast.com/view/stable/job/stable-sqlService/
on 5.1-SNAPSHOT

**Comment by viliam-durina** [comment]
>only sql service running, split brain, sql hanging, stack trace collected
