### ISSUE TITLE
NullPointerException Target is required! OutboundOperationHandler.java:45 Preconditions.java:59

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#19486]
http://jenkins.hazelcast.com/view/split/job/split-x3/50/console
/disk1/workspace/split-x3/5.0-SNAPSHOT/2021_09_08-08_18_13/jet

```
./output/HZ/HzMember1HZAA/out.txt-SEVERE: [10.0.0.49]:5701 [HZ] [5.0-SNAPSHOT] Target is required!
./output/HZ/HzMember1HZAA/out.txt:java.lang.NullPointerException: Target is required!
./output/HZ/HzMember1HZAA/out.txt:	at com.hazelcast.internal.util.Preconditions.checkNotNull(Preconditions.java:59)
./output/HZ/HzMember1HZAA/out.txt-	at com.hazelcast.spi.impl.operationservice.impl.OutboundOperationHandler.send(OutboundOperationHandler.java:45)
./output/HZ/HzMember1HZAA/out.txt-	at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.send(OperationServiceImpl.java:466)
./output/HZ/HzMember1HZAA/out.txt-	at com.hazelcast.jet.impl.JobExecutionService.verifyClusterInformation(JobExecutionService.java:456)
./output/HZ/HzMember1HZAA/out.txt-	at com.hazelcast.jet.impl.JobExecutionService.runLightJob(JobExecutionService.java:329)
./output/HZ/HzMember1HZAA/out.txt-	at com.hazelcast.jet.impl.operation.InitExecutionOperation.doRun(InitExecutionOperation.java:93)
./output/HZ/HzMember1HZAA/out.txt-	at com.hazelcast.jet.impl.operation.AsyncOperation.run(AsyncOperation.java:54)
./output/HZ/HzMember1HZAA/out.txt-	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:196)
./output/HZ/HzMember1HZAA/out.txt-	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:273)
./output/HZ/HzMember1HZAA/out.txt-	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:249)
./output/HZ/HzMember1HZAA/out.txt-	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:214)
./output/HZ/HzMember1HZAA/out.txt-	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:411)
./output/HZ/HzMember1HZAA/out.txt-	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:438)
./output/HZ/HzMember1HZAA/out.txt-	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:600)
./output/HZ/HzMember1HZAA/out.txt-	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:579)
./output/HZ/HzMember1HZAA/out.txt-	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:540)
```

**Comment by viliam-durina** [comment]
Fixed in #19660
