### ISSUE TITLE
ConcurrentConveyorException: Queue drainer has already left  ConcurrentConveyor.java:367

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#19490]
http://jenkins.hazelcast.com/view/shutdown/job/shutdown-x2/38/console

hz-bench-run-jenkins-shutdown hz/stable/persist 0 4 M4C4

/disk1/workspace/shutdown-x2/5.0-SNAPSHOT/2021_09_08-12_49_17/persist

split brain / freeze versions of this test don't see this ConcurrentConveyorException exceptions 

```
com.hazelcast.internal.util.concurrent.ConcurrentConveyorException: Queue drainer has already left
	at com.hazelcast.internal.util.concurrent.ConcurrentConveyor.checkDrainerGone(ConcurrentConveyor.java:367)
	at com.hazelcast.internal.util.concurrent.ConcurrentConveyor.submit(ConcurrentConveyor.java:260)
	at com.hazelcast.internal.util.concurrent.ConcurrentConveyorSingleQueue.submit(ConcurrentConveyorSingleQueue.java:59)
	at com.hazelcast.internal.hotrestart.impl.ConcurrentHotRestartStore.submitAndProceedWhenAllowed(ConcurrentHotRestartStore.java:141)
	at com.hazelcast.internal.hotrestart.impl.ConcurrentHotRestartStore.put(ConcurrentHotRestartStore.java:82)
	at com.hazelcast.map.impl.recordstore.HotRestartStorageImpl.putToHotRestart(HotRestartStorageImpl.java:187)
	at com.hazelcast.map.impl.recordstore.HotRestartStorageImpl.put(HotRestartStorageImpl.java:78)
	at com.hazelcast.map.impl.recordstore.HotRestartStorageImpl.put(HotRestartStorageImpl.java:28)
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.putNewRecord(DefaultRecordStore.java:924)
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.putInternal(DefaultRecordStore.java:906)
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.set(DefaultRecordStore.java:826)
	at com.hazelcast.map.impl.operation.SetOperation.runInternal(SetOperation.java:40)
	at com.hazelcast.map.impl.operation.MapOperation.run(MapOperation.java:115)
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:196)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:273)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:249)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:214)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:411)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:438)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:600)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:579)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:540)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:240)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:59)
	at com.hazelcast.client.impl.protocol.task.AbstractPartitionMessageTask.processInternal(AbstractPartitionMessageTask.java:51)
	at com.hazelcast.client.impl.protocol.task.AbstractAsyncMessageTask.processMessage(AbstractAsyncMessageTask.java:71)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:153)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:116)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:193)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:207)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:141)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
	at ------ submitted from ------.()
	at com.hazelcast.internal.util.ExceptionUtil.cloneExceptionWithFixedAsyncStackTrace(ExceptionUtil.java:279)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.returnOrThrowWithGetConventions(InvocationFuture.java:112)
	at com.hazelcast.client.impl.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:95)
	at com.hazelcast.client.impl.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:40)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:617)
	at com.hazelcast.client.impl.spi.ClientProxy.invokeOnPartition(ClientProxy.java:188)
	at com.hazelcast.client.impl.spi.ClientProxy.invoke(ClientProxy.java:182)
	at com.hazelcast.client.impl.proxy.ClientMapProxy.setInternal(ClientMapProxy.java:687)
	at com.hazelcast.client.impl.proxy.ClientMapProxy.set(ClientMapProxy.java:661)
	at com.hazelcast.client.impl.proxy.ClientMapProxy.set(ClientMapProxy.java:1553)
```

**Comment by jerrinot** [comment]
is there any suspicious exception before? this is just a consequence of some other error which is not propagated to a caller.

**Comment by vbekiaris** [comment]
Is the issue reproducible reliably? If so, can you try reverting EE to https://github.com/hazelcast/hazelcast-enterprise/commit/76b302a28fc41570c36e9805876f8f02dbc2963a and running the test again?

**Comment by Danny-Hazelcast** [comment]
reverting hazelcast/hazelcast-enterprise@76b302a EE wil not compile.
i see it was committed only 2 days ago,  i believe i have seen an occurrence of this issue before then.

**Comment by mmedenjak** [comment]
We might create a branch where the OS commit is reverted, together with the EE "quick fix" commit, and rerun with that.

**Comment by fbarotov** [comment]
Not sure if it is a bug or a feature, for example the test below passes but also throws an exception same as the one above

```
15:46:32,636  WARN |testSingleMemberCrash[memoryFormat:BINARY fsync:true encrypted:false clusterSize:3 merkleTree:false]| - [Node] testSingleMemberCrash - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Terminating forcefully...
15:46:32,636  INFO |testSingleMemberCrash[memoryFormat:BINARY fsync:true encrypted:false clusterSize:3 merkleTree:false]| - [Node] testSingleMemberCrash - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Shutting down connection manager...
15:46:32,637  INFO |testSingleMemberCrash[memoryFormat:BINARY fsync:true encrypted:false clusterSize:3 merkleTree:false]| - [MockServer] testSingleMemberCrash - [127.0.0.1]:5703 [dev] [5.0-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5702, connection: MockConnection{localEndpoint=[127.0.0.1]:5703, remoteEndpoint=[127.0.0.1]:5702, alive=false}
Exception in thread "Thread-7" com.hazelcast.internal.util.concurrent.ConcurrentConveyorException: Queue drainer has already left
	at com.hazelcast.internal.util.concurrent.ConcurrentConveyor.checkDrainerGone(ConcurrentConveyor.java:367)
ConcurrentConveyor.java:367
	at com.hazelcast.internal.hotrestart.impl.ConcurrentHotRestartStore.submitAndProceedWhenAllowed(ConcurrentHotRestartStore.java:147)
ConcurrentHotRestartStore.java:147
	at com.hazelcast.internal.hotrestart.impl.ConcurrentHotRestartStore.put(ConcurrentHotRestartStore.java:82)
ConcurrentHotRestartStore.java:82
	at com.hazelcast.map.impl.recordstore.HotRestartStorageImpl.putToHotRestart(HotRestartStorageImpl.java:187)
HotRestartStorageImpl.java:187
	at com.hazelcast.map.impl.recordstore.HotRestartStorageImpl.put(HotRestartStorageImpl.java:78)
HotRestartStorageImpl.java:78
	at com.hazelcast.map.impl.recordstore.HotRestartStorageImpl.put(HotRestartStorageImpl.java:1)
HotRestartStorageImpl.java:1
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.putNewRecord(DefaultRecordStore.java:925)
DefaultRecordStore.java:925
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.putInternal(DefaultRecordStore.java:907)
DefaultRecordStore.java:907
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.set(DefaultRecordStore.java:827)
	at com.hazelcast.map.impl.operation.SetOperation.runInternal(SetOperation.java:40)
SetOperation.java:40
	at com.hazelcast.map.impl.operation.MapOperation.run(MapOperation.java:115)
MapOperation.java:115
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:196)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:273)
OperationRunnerImpl.java:273
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:249)
OperationRunnerImpl.java:249
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:470)
OperationRunnerImpl.java:470
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:197)
OperationThread.java:197
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:137)
OperationThread.java:137
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123)
OperationThread.java:123
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
HazelcastManagedThread.java:102
	at ------ submitted from ------.()
	at com.hazelcast.internal.util.ExceptionUtil.cloneExceptionWithFixedAsyncStackTrace(ExceptionUtil.java:279)
ExceptionUtil.java:279
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.returnOrThrowWithGetConventions(InvocationFuture.java:112)
InvocationFuture.java:112
1
```

and the test `MapCrashRecoveryTest#testSingleMemberCrash `

```java
    @Test
    public void testSingleMemberCrash() {
        HazelcastInstance[] instances = restartInstances(clusterSize);
        IMap<String, Integer> map = createMap(instances[0]);
        for (int i = 0; i < KEY_COUNT; i++) {
            map.set("" + i, i);
        }
        assertEquals(KEY_COUNT, map.size());

        final int n = 500_000;

        final List<String> keys = Stream.generate(() -> generateKeyOwnedBy(instances[1]))
                .limit(n)
                .collect(Collectors.toList());

        Thread thread = new Thread(() -> {
            for (String key : keys) {
                map.set(key, 0, 1, TimeUnit.MILLISECONDS);
            }
        });
        thread.start();

        // terminate a single member
        Address terminatedMemberAddress = getNode(instances[1]).getThisAddress();
        instances[1].getLifecycleService().terminate();
        waitClusterForSafeState(instances[0]);

        // restart terminated member
        instances[1] = startHazelcastInstances(terminatedMemberAddress, makeConfig(1));
        waitClusterForSafeState(instances[0]);

        try {
            thread.join();
        } catch (InterruptedException e) {
            e.printStackTrace();
        }

        assertTrueEventually(() -> {
            assertEquals(KEY_COUNT, map.size());
        });
    }
```

**Comment by mmedenjak** [comment]
Generally the `ConcurrentConveyorException: Queue drainer has already left` is a generic exception that stems from the fact that there are two separate threads - the partition thread and the persistence thread. The persistence thread dies because of some reason (e.g. no more HD memory) but user operations will always get `ConcurrentConveyorException: Queue drainer has already left` with no additional information. A bit more [here](https://hazelcast.slack.com/archives/C01JU7ZJYGP/p1631106261135000).

So the first question I always ask when presented with this exception is - what are the other exceptions in the logs that you see? Can you take a look at the whole log? It is very much possible that Danny's test and your test fail with the same user error but have very different root causes.

**Comment by mmedenjak** [comment]
There seems to be some race on shutting down the member - hot restart store is already shut down, but some migrations are still ongoing:
```
Sep 08, 2021 12:50:44 PM com.hazelcast.internal.hotrestart.cluster.ClusterMetadataManager
INFO: [10.0.0.54]:5701 [HZ] [5.0-SNAPSHOT] Local Hot Restart procedure completed with success.
Sep 08, 2021 12:50:44 PM com.hazelcast.internal.hotrestart.cluster.ClusterMetadataManager
INFO: [10.0.0.54]:5701 [HZ] [5.0-SNAPSHOT] Shortcutting cluster start to success as there is no hot restart data on disk.
Sep 08, 2021 12:50:44 PM com.hazelcast.internal.hotrestart.cluster.ClusterMetadataManager
INFO: [10.0.0.54]:5701 [HZ] [5.0-SNAPSHOT] Setting final cluster state to: ACTIVE
Sep 08, 2021 12:50:44 PM com.hazelcast.internal.hotrestart.cluster.ClusterMetadataManager
INFO: [10.0.0.54]:5701 [HZ] [5.0-SNAPSHOT] Completed hot restart with final cluster state: ACTIVE
Sep 08, 2021 12:50:44 PM com.hazelcast.internal.hotrestart.cluster.ClusterMetadataManager
INFO: [10.0.0.54]:5701 [HZ] [5.0-SNAPSHOT] All cluster members have transitioned to the final cluster state
Sep 08, 2021 12:50:45 PM com.hazelcast.internal.hotrestart.HotRestartIntegrationService
INFO: [10.0.0.54]:5701 [HZ] [5.0-SNAPSHOT] Hot Restart procedure completed in 1 seconds
Sep 08, 2021 12:50:45 PM com.hazelcast.core.LifecycleService
INFO: [10.0.0.54]:5701 [HZ] [5.0-SNAPSHOT] [10.0.0.54]:5701 is STARTED
...

Sep 08, 2021 12:51:58 PM com.hazelcast.core.LifecycleService
INFO: [10.0.0.54]:5701 [HZ] [5.0-SNAPSHOT] [10.0.0.54]:5701 is SHUTTING_DOWN
Sep 08, 2021 12:51:58 PM com.hazelcast.internal.hotrestart.HotRestartIntegrationService
INFO: [10.0.0.54]:5701 [HZ] [5.0-SNAPSHOT] Shutting down hot-restart service.
Sep 08, 2021 12:51:59 PM com.hazelcast.internal.partition.operation.FinalizeMigrationOperation
WARNING: [10.0.0.54]:5701 [HZ] [5.0-SNAPSHOT] Error while finalizing migration -> PartitionMigrationEvent{migrationEndpoint=SOURCE, partitionId=152, currentReplicaIndex=0, newReplicaIndex=-1, uuid=291c2a9c-e63f-4d72-9f49-a87bd0cbcc8f}
com.hazelcast.internal.util.concurrent.ConcurrentConveyorException: Queue drainer has already left
```

Full member logs are here - [out.txt](https://github.com/hazelcast/hazelcast/files/7169523/out.txt)

**Comment by fbarotov** [comment]
Great, thanks a lot @mmedenjak. I thought that part of the log was a normal / expected warning, but I see it is not :)
