### ISSUE TITLE
Migration operation is received before startup is completed

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast#19551]
Using Hazelcast Enterprise 5.0-SNAPSHOT (20210915 - e0793e4, 9ae3a4b)
I see migration warnings in a 2 node cluster

```
10:26:21.887 [hz.thirsty_stonebraker.async.thread-2] WARN  com.hazelcast.internal.partition.operation.MigrationRequestOperation - [10.172.4.17]:5701 [blue] [5.0-SNAPSHOT] Failure while executing MigrationInfo{uuid=0ddebdfd-92cf-4ca2-8759-8079e9784384, partitionId=2, source=[10.172.4.17]:5701 - f276b208-9b37-4ee1-b9a5-5db7475cba20, sourceCurrentReplicaIndex=0, sourceNewReplicaIndex=1, destination=[10.172.0.11]:5701 - 8dd9443c-d859-4866-ab50-ccf59d9aea7a, destinationCurrentReplicaIndex=-1, destinationNewReplicaIndex=0, master=[10.172.4.17]:5701, initialPartitionVersion=1, partitionVersionIncrement=2, status=ACTIVE}
 java.lang.IllegalStateException: Migration operation is received before startup is completed. Sender: [10.172.4.17]:5701
	at com.hazelcast.internal.partition.operation.BaseMigrationOperation.verifyNodeStarted(BaseMigrationOperation.java:109) ~[hazelcast-enterprise-5.0-SNAPSHOT.jar!/:5.0-SNAPSHOT]
	at com.hazelcast.internal.partition.operation.BaseMigrationOperation.beforeRun(BaseMigrationOperation.java:91) ~[hazelcast-enterprise-5.0-SNAPSHOT.jar!/:5.0-SNAPSHOT]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:248) ~[hazelcast-enterprise-5.0-SNAPSHOT.jar!/:5.0-SNAPSHOT]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:470) ~[hazelcast-enterprise-5.0-SNAPSHOT.jar!/:5.0-SNAPSHOT]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:197) ~[hazelcast-enterprise-5.0-SNAPSHOT.jar!/:5.0-SNAPSHOT]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:137) ~[hazelcast-enterprise-5.0-SNAPSHOT.jar!/:5.0-SNAPSHOT]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123) ~[hazelcast-enterprise-5.0-SNAPSHOT.jar!/:5.0-SNAPSHOT]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) [hazelcast-enterprise-5.0-SNAPSHOT.jar!/:5.0-SNAPSHOT]
```
and
```
10:26:21.874 [hz.practical_kare.partition-operation.thread-0] WARN  com.hazelcast.internal.partition.operation.MigrationOperation - [10.172.0.11]:5701 [blue] [5.0-SNAPSHOT] Migration operation is received before startup is completed. Sender: [10.172.4.17]:5701
10:26:21.874 [hz.practical_kare.partition-operation.thread-1] WARN  com.hazelcast.internal.partition.operation.MigrationOperation - [10.172.0.11]:5701 [blue] [5.0-SNAPSHOT] Migration operation is received before startup is completed. Sender: [10.172.4.17]:5701
10:26:21.875 [hz.practical_kare.partition-operation.thread-1] WARN  com.hazelcast.internal.partition.operation.MigrationOperation - [10.172.0.11]:5701 [blue] [5.0-SNAPSHOT] Migration operation is received before startup is completed. Sender: [10.172.4.17]:5701
10:26:21.875 [hz.practical_kare.partition-operation.thread-0] WARN  com.hazelcast.internal.partition.operation.MigrationOperation - [10.172.0.11]:5701 [blue] [5.0-SNAPSHOT] Migration operation is received before startup is completed. Sender: [10.172.4.17]:5701
10:26:21.876 [hz.practical_kare.partition-operation.thread-0] WARN  com.hazelcast.internal.partition.operation.MigrationOperation - [10.172.0.11]:5701 [blue] [5.0-SNAPSHOT] Migration operation is received before startup is completed. Sender: [10.172.4.17]:5701
10:26:21.876 [hz.practical_kare.partition-operation.thread-1] WARN  com.hazelcast.internal.partition.operation.MigrationOperation - [10.172.0.11]:5701 [blue] [5.0-SNAPSHOT] Migration operation is received before startup is completed. Sender: [10.172.4.17]:5701
10:26:21.900 [hz.practical_kare.priority-generic-operation.thread-0] WARN  com.hazelcast.internal.partition.InternalPartitionService - [10.172.0.11]:5701 [blue] [5.0-SNAPSHOT] Ignoring received partition table, startup is not completed yet. Sender: [10.172.4.17]:5701
10:26:21.902 [hz.practical_kare.generic-operation.thread-1] WARN  com.hazelcast.internal.partition.InternalPartitionService - [10.172.0.11]:5701 [blue] [5.0-SNAPSHOT] Ignoring received partition table, startup is not completed yet. Sender: [10.172.4.17]:5701
10:26:21.903 [hz.practical_kare.generic-operation.thread-0] WARN  com.hazelcast.internal.partition.InternalPartitionService - [10.172.0.11]:5701 [blue] [5.0-SNAPSHOT] Ignoring received partition table, startup is not completed yet. Sender: [10.172.4.17]:5701
10:26:21.904 [hz.practical_kare.generic-operation.thread-1] WARN  com.hazelcast.internal.partition.InternalPartitionService - [10.172.0.11]:5701 [blue] [5.0-SNAPSHOT] Ignoring received partition table, startup is not completed yet. Sender: [10.172.4.17]:5701
10:26:21.905 [hz.practical_kare.priority-generic-operation.thread-0] WARN  com.hazelcast.internal.partition.InternalPartitionService - [10.172.0.11]:5701 [blue] [5.0-SNAPSHOT] Ignoring received partition table, startup is not completed yet. Sender: [10.172.4.17]:5701
10:26:21.907 [hz.practical_kare.priority-generic-operation.thread-0] WARN  com.hazelcast.internal.partition.InternalPartitionService - [10.172.0.11]:5701 [blue] [5.0-SNAPSHOT] Ignoring received partition table, startup is not completed yet. Sender: [10.172.4.17]:5701
10:26:21.908 [hz.practical_kare.priority-generic-operation.thread-0] WARN  com.hazelcast.internal.partition.InternalPartitionService - [10.172.0.11]:5701 [blue] [5.0-SNAPSHOT] Ignoring received partition table, startup is not completed yet. Sender: [10.172.4.17]:5701
10:26:21.909 [hz.practical_kare.generic-operation.thread-1] WARN  com.hazelcast.internal.partition.InternalPartitionService - [10.172.0.11]:5701 [blue] [5.0-SNAPSHOT] Ignoring received partition table, startup is not completed yet. Sender: [10.172.4.17]:5701
```

**Comment by mmedenjak** [comment]
@vbekiaris @ahmetmircik can you check this out once you have time?

**Comment by AyberkSorgun** [comment]
Will be fixed in 5.2
