### ISSUE TITLE
Hz3 connector is not able to enrich the data if it is serialized with a Portable, DS, IDS serializer 

### ISSUE THREAD

**Issue by slavagithub** [hazelcast/hazelcast#19581]
Hz3 connector is not able to enrich the data if it is serialized with a Portable, DS, IDS serializer 
**STEPS TO REPRODUCE:**
1. Hz3 side: add IMap<Integer, TestItemPortable> to the cluster and put some items in it (TestItemPortable implements Portable)
2. HZ5 side: Register Portable factory. Try to enrich using a Hz3 connector.
**RESULT:**
Job failed with an exception
```
com.hazelcast.nio.serialization.HazelcastSerializationException: Could not find PortableFactory for factory-id: 222
```
**REPRODUCER:**
**Enrichment:**
```
IList<Integer> list = hz5.getList("list");
list.add(1);
list.add(2);
list.add(3);

IList<TestItemPortable> results = hz5.getList("result-list");

Pipeline p = Pipeline.create();

ServiceFactory<Hz3MapAdapter, AsyncMap<Integer, TestItemPortable>> hz3MapSF =
        hz3MapServiceFactory(Hz3MapNames.PORTABLE, H3ClientXml.config);

BiFunctionEx<? super Map<Integer, TestItemPortable>, ? super Integer, TestItemPortable> mapFn =
        mapUsingIMap(FunctionEx.identity(), (Integer i, TestItemPortable s) -> s);

BatchStage<TestItemPortable> mapStage = p.readFrom(Sources.list(list))
        .mapUsingService(
                hz3MapSF,
                mapFn
        );
mapStage.writeTo(Sinks.list(results));

JobConfig config = getJobConfig(mapStage.name());
hz5.getJet().newJob(p, config).join();
```
**config:**
```
cfg.getSerializationConfig().addPortableFactory(TestItemPortable.SERIALIZATION_ID,
        (int id) -> (id == TestItemPortable.SERIALIZATION_ID) ? new TestItemPortable() : null);
```
**Test object:**
```
Public class TestItemPortable extends TestItem implements Portable {
    public static final Integer SERIALIZATION_ID  =222;

    public TestItemPortable() {
    }

    public TestItemPortable(Integer id) {
        super(id);
    }

    @Override
    public int getFactoryId() {
        return SERIALIZATION_ID;
    }

    @Override
    public int getClassId() {
        return SERIALIZATION_ID;
    }

    @Override
    public void writePortable(PortableWriter portableWriter) throws IOException {
        portableWriter.writeInt( "id", getItemId() );

    }

    @Override
    public void readPortable(PortableReader portableReader) throws IOException {
        setItemId(portableReader.readInt("id"));
    }
}
```
**Full exception:**
```
WARNING: [192.168.31.136]:5702 [dev] [5.0-SNAPSHOT] Exception in ProcessorTasklet{06d5-03a9-a3c0-0001/mapUsingService#0}
com.hazelcast.nio.serialization.HazelcastSerializationException: Could not find PortableFactory for factory-id: 222
	at com.hazelcast.internal.serialization.impl.PortableSerializer.createNewPortableInstance(PortableSerializer.java:111)
	at com.hazelcast.internal.serialization.impl.PortableSerializer.read(PortableSerializer.java:87)
	at com.hazelcast.internal.serialization.impl.PortableSerializer.read(PortableSerializer.java:81)
	at com.hazelcast.internal.serialization.impl.PortableSerializer.read(PortableSerializer.java:34)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:187)
	at com.hazelcast.client.spi.ClientProxy.toObject(ClientProxy.java:102)
	at com.hazelcast.client.proxy.ClientMapProxy.get(ClientMapProxy.java:318)
	at com.hazelcast.connector.map.impl.AsyncMapImpl.get(AsyncMapImpl.java:173)
	at com.hazelcast.connector.Hz3Enrichment.lambda$mapUsingIMap$5cd598b5$1(Hz3Enrichment.java:147)
	at com.hazelcast.function.BiFunctionEx.apply(BiFunctionEx.java:49)
	at com.hazelcast.jet.core.processor.Processors.lambda$mapUsingServiceP$26d41dd1$1(Processors.java:869)
	at com.hazelcast.jet.function.TriFunction.apply(TriFunction.java:52)
	at com.hazelcast.jet.impl.processor.TransformUsingServiceP.tryProcess(TransformUsingServiceP.java:63)
	at com.hazelcast.jet.core.AbstractProcessor.tryProcess0(AbstractProcessor.java:187)
	at com.hazelcast.jet.core.AbstractProcessor.process0(AbstractProcessor.java:590)
	at com.hazelcast.jet.core.AbstractProcessor.process(AbstractProcessor.java:108)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.lambda$processInbox$2f647568$2(ProcessorTasklet.java:440)
	at com.hazelcast.jet.function.RunnableEx.run(RunnableEx.java:31)
	at com.hazelcast.jet.impl.util.Util.doWithClassLoader(Util.java:516)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.processInbox(ProcessorTasklet.java:440)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:305)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:300)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:281)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:255)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:388)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:895)
	at com.h

**Comment by mmedenjak** [comment]
@frant-hartm can you check this out and share your thoughts?

**Comment by frant-hartm** [comment]
This is a bug, ideally should go to 5.0.1.
