### ISSUE TITLE
SqlCompactTest.test_schemaEvolution_fieldAdded and SqlCompactTest.test_schemaEvolution_fieldRemoved

### ISSUE THREAD

**Issue by slavagithub** [hazelcast/hazelcast#19598]
com.hazelcast.jet.sql.impl.connector.map.SqlCompactTest.test_schemaEvolution_fieldAdded and com.hazelcast.jet.sql.impl.connector.map.SqlCompactTest.test_schemaEvolution_fieldRemoved fail with assertion error "expecting []"

Master / 5.1 (462045c)
Master Sonar
http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/985/testReport/

Stacktrace:
```
java.lang.AssertionError: 

Expecting:
  <[]>
to contain exactly in any order:
  <[Row{[1, Alice]}, Row{[2, Bob]}]>
but could not find the following elements:
  <[Row{[1, Alice]}, Row{[2, Bob]}]>

	at com.hazelcast.jet.sql.SqlTestSupport.assertRowsAnyOrder(SqlTestSupport.java:210)
	at com.hazelcast.jet.sql.SqlTestSupport.assertRowsAnyOrder(SqlTestSupport.java:190)
	at com.hazelcast.jet.sql.impl.connector.map.SqlCompactTest.test_schemaEvolution_fieldRemoved(SqlCompactTest.java:312)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Standard output:
```
Finished Running Test: test_writingToTopLevelWhileNestedFieldMapped_implicit in 0.162 seconds.
Started Running Test: test_schemaEvolution_fieldRemoved
22:40:54,003 DEBUG || - [CalciteSqlOptimizer] hz.naughty_dijkstra.client-query.thread-6 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Before logical opt:
LogicalTableSink(table=[[hazelcast, public, o_a9658d08_7ac8_4013_8d31_d0a7259b2b47[projects=[0, 1, 2, 3, 4]]]], operation=[INSERT], flattened=[false])
  LogicalProject(id=[1], __key=[null:OBJECT], name=[_UTF-16LE'Alice':VARCHAR CHARACTER SET "UTF-16LE"], ssn=[123456789:BIGINT(63)], this=[null:OBJECT])
    LogicalValues(tuples=[[{ 0 }]])

22:40:54,004 DEBUG || - [CalciteSqlOptimizer] hz.naughty_dijkstra.client-query.thread-6 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] After logical opt:
SinkMapLogicalRel(table=[[hazelcast, public, o_a9658d08_7ac8_4013_8d31_d0a7259b2b47[projects=[0, 1, 2, 3, 4]]]], values=[[{projection=[ConstantExpression{type=QueryDataType {family=INTEGER}, value=1}, ConstantExpression{type=QueryDataType {family=OBJECT}, value=null}, ConstantExpression{type=QueryDataType {family=VARCHAR}, value=Alice}, ConstantExpression{type=QueryDataType {family=BIGINT}, value=123456789}, ConstantExpression{type=QueryDataType {family=OBJECT}, value=null}], values=[{expressions=[[ConstantExpression{type=QueryDataType {family=INTEGER}, value=0}]]}]}]])

22:40:54,004 DEBUG || - [CalciteSqlOptimizer] hz.naughty_dijkstra.client-query.thread-6 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] After physical opt:
SinkMapPhysicalRel(table=[[hazelcast, public, o_a9658d08_7ac8_4013_8d31_d0a7259b2b47[projects=[0, 1, 2, 3, 4]]]], values=[[{projection=[ConstantExpression{type=QueryDataType {family=INTEGER}, value=1}, ConstantExpression{type=QueryDataType {family=OBJECT}, value=null}, ConstantExpression{type=QueryDataType {family=VARCHAR}, value=Alice}, ConstantExpression{type=QueryDataType {family=BIGINT}, value=123456789}, ConstantExpression{type=QueryDataType {family=OBJECT}, value=null}], values=[{expressions=[[ConstantExpression{type=QueryDataType {family=INTEGER}, value=0}]]}]}]])

22:40:54,009 DEBUG || - [CalciteSqlOptimizer] hz.naughty_dijkstra.client-query.thread-8 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Before logical opt:
LogicalTableSink(table=[[hazelcast, public, o_a9658d08_7ac8_4013_8d31_d0a7259b2b47[projects=[0, 1, 2, 3]]]], operation=[INSERT], flattened=[false])
  LogicalProject(id=[2], __key=[null:OBJECT], name=[_UTF-16LE'Bob':VARCHAR CHARACTER SET "UTF-16LE"], this=[null:OBJECT])
    LogicalValues(tuples=[[{ 0 }]])

22:40:54,010 DEBUG || - [CalciteSqlOptimizer] hz.naughty_dijkstra.client-query.thread-8 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] After logical opt:
SinkMapLogicalRel(table=[[hazelcast, public, o_a9658d08_7ac8_4013_8d31_d0a7259b2b47[projects=[0, 1, 2, 3]]]], values=[[{projection=[ConstantExpression{type=QueryDataType {family=INTEGER}, value=2}, ConstantExpression{type=QueryDataType {family=OBJECT}, value=null}, ConstantExpression{type=QueryDataType {family=VARCHAR}, value=Bob}, ConstantExpression{type=QueryDataType {family=OBJECT}, value=null}], values=[{expressions=[[ConstantExpression{type=QueryDataType {family=INTEGER}, value=0}]]}]}]])

22:40:54,011 DEBUG || - [CalciteSqlOptimizer] hz.naughty_dijkstra.client-query.thread-8 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] After physical opt:
SinkMapPhysicalRel(table=[[hazelcast, public, o_a9658d08_7ac8_4013_8d31_d0a7259b2b47[projects=[0, 1, 2, 3]]]], values=[[{projection=[ConstantExpression{type=QueryDataType {family=INTEGER}, value=2}, ConstantExpression{type=QueryDataType {family=OBJECT}, value=null}, ConstantExpression{type=QueryDataType {family=VARCHAR}, value=Bob}, ConstantExpression{type=QueryDataType {family=OBJECT}, value=null}], values=[{expressions=[[ConstantExpression{type=QueryDataType {family=INTEGER}, value=0}]]}]}]])

22:40:54,013 DEBUG |test_schemaEvolution_fieldRemoved| - [CalciteSqlOptimizer] test_schemaEvolution_fieldRemoved - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Before logical opt:
LogicalProject(id=[$0], name=[$2])
  LogicalTableScan(table=[[hazelcast, public, o_a9658d08_7ac8_4013_8d31_d0a7259b2b47[projects=[0, 1, 2, 3]]]])

22:40:54,013 DEBUG |test_schemaEvolution_fieldRemoved| - [CalciteSqlOptimizer] test_schemaEvolution_fieldRemoved - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] After logical opt:
FullScanLogicalRel(table=[[hazelcast, public, o_a9658d08_7ac8_4013_8d31_d0a7259b2b47[projects=[0, 2]]]])

22:40:54,013 DEBUG |test_schemaEvolution_fieldRemoved| - [CalciteSqlOptimizer] test_schemaEvolution_fieldRemoved - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] After physical opt:
FullScanPhysicalRel(table=[[hazelcast, public, o_a9658d08_7ac8_4013_8d31_d0a7259b2b47[projects=[0, 2]]]])

22:40:54,014 DEBUG |test_schemaEvolution_fieldRemoved| - [LightMasterContext] test_schemaEvolution_fieldRemoved - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Start executing light job 06d1-b9b8-f282-0001, execution graph in DOT format:
digraph DAG {
	"IMap[public.o_a9658d08_7ac8_4013_8d31_d0a7259b2b47]" [localParallelism=1];
	"Project(IMap[public.o_a9658d08_7ac8_4013_8d31_d0a7259b2b47])" [localParallelism=default];
	"ClientSink" [localParallelism=1];
	"IMap[public.o_a9658d08_7ac8_4013_8d31_d0a7259b2b47]" -> "Project(IMap[public.o_a9658d08_7ac8_4013_8d31_d0a7259b2b47])" [label="isolated", queueSize=1024];
	"Project(IMap[public.o_a9658d08_7ac8_4013_8d31_d0a7259b2b47])" -> "ClientSink" [label="distributed to [127.0.0.1]:5701-partitioned", queueSize=1024];
}
HINT: You can use graphviz or http://viz-js.com to visualize the printed graph.
22:40:54,014 DEBUG |test_schemaEvolution_fieldRemoved| - [LightMasterContext] test_schemaEvolution_fieldRemoved - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Building execution plan for 06d1-b9b8-f282-0001
22:40:54,015 DEBUG |test_schemaEvolution_fieldRemoved| - [LightMasterContext] test_schemaEvolution_fieldRemoved - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Built execution plans for 06d1-b9b8-f282-0001
22:40:54,015 DEBUG |test_schemaEvolution_fieldRemoved| - [InitExecutionOperation] test_schemaEvolution_fieldRemoved - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Initializing execution plan for job 06d1-b9b8-f282-0001, execution 06d1-b9b8-f282-0001 from [127.0.0.1]:5701
22:40:54,015 DEBUG |test_schemaEvolution_fieldRemoved| - [JobExecutionService] test_schemaEvolution_fieldRemoved - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Execution plan for light job ID=06d1-b9b8-f282-0001, jobName='06d1-b9b8-f282-0001', executionId=06d1-b9b8-f282-0001 initialized, will start the execution
22:40:54,047  WARN || - [JobClassLoaderService] ForkJoinPool.commonPool-worker-5 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] JobClassLoaders for jobId=06d1-b9b8-f282-0001 already removed
22:40:54,048 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-5 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Completed execution of job '06d1-b9b8-f282-0001', execution 06d1-b9b8-f282-0001
22:40:54,048 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-5 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Execution of job '06d1-b9b8-f282-0001', execution 06d1-b9b8-f282-0001 completed
22:40:54,164  INFO |test_schemaEvolution_fieldRemoved| - [SqlTestSupport] Time-limited test - Removing 2 cached plans in SqlTestSupport.@After
22:40:54,164  INFO |test_schemaEvolution_fieldRemoved| - [SimpleTestInClusterSupport] Time-limited test - Ditching 0 jobs in SimpleTestInClusterSupport.@After: []
22:40:54,166  INFO |test_schemaEvolution_fieldRemoved| - [SimpleTestInClusterSupport] Time-limited test - Destroying 2 distributed objects in SimpleTestInClusterSupport.@After: [hz:impl:replicatedMapService/__sql.catalog, hz:impl:mapService/o_a9658d08_7ac8_4013_8d31_d0a7259b2b47]
22:40:54,166 ERROR || - [EventServiceImpl] hz.naughty_dijkstra.event-22 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] hz.naughty_dijkstra.event-22 caught an exception while processing:com.hazelcast.spi.impl.eventservice.impl.LocalEventDispatcher@1a1d8a3f
java.lang.UnsupportedOperationException: SQL catalog must never be cleared - MapEvent{entryEventType=CLEAR_ALL, member=Member [127.0.0.1]:5701 - 13ba42d0-3198-4384-8456-7a667126187f this, name='__sql.catalog', numberOfEntriesAffected=1}
	at com.hazelcast.jet.sql.impl.schema.MappingStorage$EntryListenerAdapter.mapCleared(MappingStorage.java:160) ~[classes/:?]
	at com.hazelcast.replicatedmap.impl.ReplicatedMapEventPublishingService.dispatchEvent(ReplicatedMapEventPublishingService.java:132) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.replicatedmap.impl.ReplicatedMapService.dispatchEvent(ReplicatedMapService.java:232) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.spi.impl.eventservice.impl.LocalEventDispatcher.run(LocalEventDispatcher.java:64) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.internal.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:245) [hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.internal.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:228) [hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
BuildInfo right after test_schemaEvolution_fieldRemoved(com.hazelcast.jet.sql.impl.connector.map.SqlCompactTest): BuildInfo{version='5.1-SNAPSHOT', build='20210917', buildNumber=20210917, revision=462045c, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'test_schemaEvolution_fieldRemoved(com.hazelcast.jet.sql.impl.connector.map.SqlCompactTest):'
22:40:50, accumulated pauses: 518 ms, max pause: 104 ms, pauses over 1000 ms: 0
```

**Comment by mmedenjak** [comment]
@sancar @mdumandag can you take a look?

**Comment by mdumandag** [comment]
This is also fixed by https://github.com/hazelcast/hazelcast/pull/19569.
The reasoning is the same with https://github.com/hazelcast/hazelcast/issues/19597#issuecomment-929206233
