### ISSUE TITLE
SqlCompactTest.test_fieldsMapping and SqlCompactTest.test_allTypes

### ISSUE THREAD

**Issue by slavagithub** [hazelcast/hazelcast#19597]
com.hazelcast.jet.sql.impl.connector.map.SqlCompactTest.test_fieldsMapping and com.hazelcast.jet.sql.impl.connector.map.SqlCompactTest.test_allTypes fails with "java.util.NoSuchElementException: No value present"

Master / 5.1 (462045c)
Master Sonar
http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/985/testReport/

Stacktrace:
```
java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.get(Optional.java:148)
	at com.hazelcast.jet.sql.impl.connector.map.SqlCompactTest.randomEntryFrom(SqlCompactTest.java:498)
	at com.hazelcast.jet.sql.impl.connector.map.SqlCompactTest.test_allTypes(SqlCompactTest.java:357)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Standard output:
```
Finished Running Test: when_explicitTopLevelField_then_fail_this in 0.003 seconds.
Started Running Test: test_allTypes
22:40:54,350 DEBUG || - [CalciteSqlOptimizer] hz.naughty_dijkstra.client-query.thread-2 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Before logical opt:
LogicalTableSink(table=[[hazelcast, public, o_873dc252_2d9a_4bd2_9a2e_ca08aa2915c9[projects=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]]]], operation=[INSERT], flattened=[false])
  LogicalProject(id=[13], __key=[null:OBJECT], character=[_UTF-16LE'a':VARCHAR CHARACTER SET "UTF-16LE"], string=[$0], boolean=[$1], byte=[$2], short=[$3], int=[$4], long=[$5], float=[$6], double=[$7], decimal=[$8], time=[$9], date=[$10], timestamp=[$11], timestampTz=[$12], this=[null:OBJECT])
    LogicalTableScan(table=[[hazelcast, public, o_92291d0c_e1ee_43a6_a76e_f05b59acbecf[projects=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]]]])

22:40:54,351 DEBUG || - [CalciteSqlOptimizer] hz.naughty_dijkstra.client-query.thread-2 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] After logical opt:
SinkLogicalRel(table=[[hazelcast, public, o_873dc252_2d9a_4bd2_9a2e_ca08aa2915c9[projects=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]]]], operation=[INSERT], flattened=[false])
  ProjectLogicalRel(id=[13], __key=[null:OBJECT], character=[_UTF-16LE'a':VARCHAR CHARACTER SET "UTF-16LE"], string=[$0], boolean=[$1], byte=[$2], short=[$3], int=[$4], long=[$5], float=[$6], double=[$7], decimal=[$8], time=[$9], date=[$10], timestamp=[$11], timestampTz=[$12], this=[null:OBJECT])
    FullScanLogicalRel(table=[[hazelcast, public, o_92291d0c_e1ee_43a6_a76e_f05b59acbecf[projects=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]]]])

22:40:54,352 DEBUG || - [CalciteSqlOptimizer] hz.naughty_dijkstra.client-query.thread-2 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] After physical opt:
SinkPhysicalRel(table=[[hazelcast, public, o_873dc252_2d9a_4bd2_9a2e_ca08aa2915c9[projects=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]]]], operation=[INSERT], flattened=[false])
  ProjectPhysicalRel(id=[13], __key=[null:OBJECT], character=[_UTF-16LE'a':VARCHAR CHARACTER SET "UTF-16LE"], string=[$0], boolean=[$1], byte=[$2], short=[$3], int=[$4], long=[$5], float=[$6], double=[$7], decimal=[$8], time=[$9], date=[$10], timestamp=[$11], timestampTz=[$12], this=[null:OBJECT])
    FullScanPhysicalRel(table=[[hazelcast, public, o_92291d0c_e1ee_43a6_a76e_f05b59acbecf[projects=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]]]])

22:40:54,354 DEBUG || - [LightMasterContext] hz.naughty_dijkstra.client-query.thread-2 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Start executing light job 06d1-b9b8-f284-0001, execution graph in DOT format:
digraph DAG {
	"AllTypes[public.o_92291d0c_e1ee_43a6_a76e_f05b59acbecf]" [localParallelism=1];
	"Project" [localParallelism=default];
	"Project(IMap[public.o_873dc252_2d9a_4bd2_9a2e_ca08aa2915c9])" [localParallelism=default];
	"IMap[public.o_873dc252_2d9a_4bd2_9a2e_ca08aa2915c9]" [localParallelism=1];
	"AllTypes[public.o_92291d0c_e1ee_43a6_a76e_f05b59acbecf]" -> "Project" [queueSize=1024];
	"Project" -> "Project(IMap[public.o_873dc252_2d9a_4bd2_9a2e_ca08aa2915c9])" [queueSize=1024];
	"Project(IMap[public.o_873dc252_2d9a_4bd2_9a2e_ca08aa2915c9])" -> "IMap[public.o_873dc252_2d9a_4bd2_9a2e_ca08aa2915c9]" [queueSize=1024];
}
HINT: You can use graphviz or http://viz-js.com to visualize the printed graph.
22:40:54,354 DEBUG || - [LightMasterContext] hz.naughty_dijkstra.client-query.thread-2 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Building execution plan for 06d1-b9b8-f284-0001
22:40:54,354 DEBUG || - [LightMasterContext] hz.naughty_dijkstra.client-query.thread-2 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Built execution plans for 06d1-b9b8-f284-0001
22:40:54,355 DEBUG || - [InitExecutionOperation] hz.naughty_dijkstra.client-query.thread-2 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Initializing execution plan for job 06d1-b9b8-f284-0001, execution 06d1-b9b8-f284-0001 from [127.0.0.1]:5701
22:40:54,358 DEBUG || - [JobExecutionService] hz.naughty_dijkstra.client-query.thread-2 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Execution plan for light job ID=06d1-b9b8-f284-0001, jobName='06d1-b9b8-f284-0001', executionId=06d1-b9b8-f284-0001 initialized, will start the execution
22:40:54,361  WARN || - [TaskletExecutionService] hz.naughty_dijkstra.jet.cooperative.thread-0 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Exception in ProcessorTasklet{06d1-b9b8-f284-0001/IMap[public.o_873dc252_2d9a_4bd2_9a2e_ca08aa2915c9]#0}
com.hazelcast.nio.serialization.HazelcastSerializationException: Failed to serialize 'com.hazelcast.internal.serialization.impl.compact.DeserializedGenericRecord'
	at com.hazelcast.internal.serialization.impl.SerializationUtil.handleSerializeException(SerializationUtil.java:129) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:238) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:214) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toData(AbstractSerializationService.java:199) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.map.impl.proxy.MapProxySupport.toDataWithStrategy(MapProxySupport.java:1320) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.map.impl.proxy.MapProxySupport.putAllInternal(MapProxySupport.java:997) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.map.impl.proxy.MapProxyImpl.putAllAsync(MapProxyImpl.java:498) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.map.impl.proxy.MapProxyImpl.putAllAsync(MapProxyImpl.java:112) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.jet.impl.connector.WriteMapP.submitPending(WriteMapP.java:139) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.jet.impl.connector.WriteMapP.processInternal(WriteMapP.java:124) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.jet.impl.connector.AsyncHazelcastWriterP.process(AsyncHazelcastWriterP.java:75) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.lambda$processInbox$2f647568$2(ProcessorTasklet.java:440) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.jet.function.RunnableEx.run(RunnableEx.java:31) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.jet.impl.util.Util.doWithClassLoader(Util.java:516) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.processInbox(ProcessorTasklet.java:440) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:305) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:300) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:281) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:255) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:388) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:803) [?:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.run(TaskletExecutionService.java:356) [hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.UnsupportedOperationException: The BETA compact format can only be used with 5.0 cluster
	at com.hazelcast.internal.serialization.impl.compact.schema.MemberSchemaService.putAsync(MemberSchemaService.java:136) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.internal.serialization.impl.compact.schema.MemberSchemaService.put(MemberSchemaService.java:131) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.internal.serialization.impl.compact.CompactStreamSerializer.putToSchemaService(CompactStreamSerializer.java:155) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.internal.serialization.impl.compact.CompactStreamSerializer.writeGenericRecord(CompactStreamSerializer.java:137) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.internal.serialization.impl.compact.CompactStreamSerializer.write(CompactStreamSerializer.java:128) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.internal.serialization.impl.compact.CompactStreamSerializer.write(CompactStreamSerializer.java:123) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.write(StreamSerializerAdapter.java:39) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:235) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	... 21 more
22:40:54,362  WARN || - [JobClassLoaderService] ForkJoinPool.commonPool-worker-5 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] JobClassLoaders for jobId=06d1-b9b8-f284-0001 already removed
22:40:54,362 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-5 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Completed execution of job '06d1-b9b8-f284-0001', execution 06d1-b9b8-f284-0001
22:40:54,362 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-5 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Execution of job '06d1-b9b8-f284-0001', execution 06d1-b9b8-f284-0001 completed with failure
java.util.concurrent.CompletionException: com.hazelcast.jet.JetException: Exception in ProcessorTasklet{06d1-b9b8-f284-0001/IMap[public.o_873dc252_2d9a_4bd2_9a2e_ca08aa2915c9]#0}: com.hazelcast.nio.serialization.HazelcastSerializationException: Failed to serialize 'com.hazelcast.internal.serialization.impl.compact.DeserializedGenericRecord'
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:870) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088) ~[?:?]
	at com.hazelcast.jet.impl.util.NonCompletableFuture.internalCompleteExceptionally(NonCompletableFuture.java:72) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$ExecutionTracker.taskletDone(TaskletExecutionService.java:489) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.dismissTasklet(TaskletExecutionService.java:420) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:406) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:803) ~[?:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.run(TaskletExecutionService.java:356) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:834) ~[?:?]
Caused by: com.hazelcast.jet.JetException: Exception in ProcessorTasklet{06d1-b9b8-f284-0001/IMap[public.o_873dc252_2d9a_4bd2_9a2e_ca08aa2915c9]#0}: com.hazelcast.nio.serialization.HazelcastSerializationException: Failed to serialize 'com.hazelcast.internal.serialization.impl.compact.DeserializedGenericRecord'
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:400) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	... 3 more
Caused by: com.hazelcast.nio.serialization.HazelcastSerializationException: Failed to serialize 'com.hazelcast.internal.serialization.impl.compact.DeserializedGenericRecord'
	at com.hazelcast.internal.serialization.impl.SerializationUtil.handleSerializeException(SerializationUtil.java:129) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:238) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:214) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toData(AbstractSerializationService.java:199) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.map.impl.proxy.MapProxySupport.toDataWithStrategy(MapProxySupport.java:1320) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.map.impl.proxy.MapProxySupport.putAllInternal(MapProxySupport.java:997) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.map.impl.proxy.MapProxyImpl.putAllAsync(MapProxyImpl.java:498) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.map.impl.proxy.MapProxyImpl.putAllAsync(MapProxyImpl.java:112) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.jet.impl.connector.WriteMapP.submitPending(WriteMapP.java:139) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.jet.impl.connector.WriteMapP.processInternal(WriteMapP.java:124) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.jet.impl.connector.AsyncHazelcastWriterP.process(AsyncHazelcastWriterP.java:75) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.lambda$processInbox$2f647568$2(ProcessorTasklet.java:440) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.jet.function.RunnableEx.run(RunnableEx.java:31) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.jet.impl.util.Util.doWithClassLoader(Util.java:516) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.processInbox(ProcessorTasklet.java:440) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:305) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:300) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:281) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:255) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:388) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	... 3 more
Caused by: java.lang.UnsupportedOperationException: The BETA compact format can only be used with 5.0 cluster
	at com.hazelcast.internal.serialization.impl.compact.schema.MemberSchemaService.putAsync(MemberSchemaService.java:136) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.internal.serialization.impl.compact.schema.MemberSchemaService.put(MemberSchemaService.java:131) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.internal.serialization.impl.compact.CompactStreamSerializer.putToSchemaService(CompactStreamSerializer.java:155) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.internal.serialization.impl.compact.CompactStreamSerializer.writeGenericRecord(CompactStreamSerializer.java:137) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.internal.serialization.impl.compact.CompactStreamSerializer.write(CompactStreamSerializer.java:128) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.internal.serialization.impl.compact.CompactStreamSerializer.write(CompactStreamSerializer.java:123) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.write(StreamSerializerAdapter.java:39) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:235) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:214) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toData(AbstractSerializationService.java:199) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.map.impl.proxy.MapProxySupport.toDataWithStrategy(MapProxySupport.java:1320) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.map.impl.proxy.MapProxySupport.putAllInternal(MapProxySupport.java:997) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.map.impl.proxy.MapProxyImpl.putAllAsync(MapProxyImpl.java:498) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.map.impl.proxy.MapProxyImpl.putAllAsync(MapProxyImpl.java:112) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.jet.impl.connector.WriteMapP.submitPending(WriteMapP.java:139) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.jet.impl.connector.WriteMapP.processInternal(WriteMapP.java:124) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.jet.impl.connector.AsyncHazelcastWriterP.process(AsyncHazelcastWriterP.java:75) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.lambda$processInbox$2f647568$2(ProcessorTasklet.java:440) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.jet.function.RunnableEx.run(RunnableEx.java:31) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.jet.impl.util.Util.doWithClassLoader(Util.java:516) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.processInbox(ProcessorTasklet.java:440) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:305) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:300) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:281) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:255) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:388) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	... 3 more
22:40:54,477  INFO |test_allTypes| - [SqlTestSupport] Time-limited test - Removing 1 cached plans in SqlTestSupport.@After
22:40:54,478  INFO |test_allTypes| - [SimpleTestInClusterSupport] Time-limited test - Ditching 0 jobs in SimpleTestInClusterSupport.@After: []
22:40:54,478  INFO |test_allTypes| - [SimpleTestInClusterSupport] Time-limited test - Destroying 2 distributed objects in SimpleTestInClusterSupport.@After: [hz:impl:replicatedMapService/__sql.catalog, hz:impl:mapService/o_873dc252_2d9a_4bd2_9a2e_ca08aa2915c9]
22:40:54,478 ERROR || - [EventServiceImpl] hz.naughty_dijkstra.event-22 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] hz.naughty_dijkstra.event-22 caught an exception while processing:com.hazelcast.spi.impl.eventservice.impl.LocalEventDispatcher@1ef292f9
java.lang.UnsupportedOperationException: SQL catalog must never be cleared - MapEvent{entryEventType=CLEAR_ALL, member=Member [127.0.0.1]:5701 - 13ba42d0-3198-4384-8456-7a667126187f this, name='__sql.catalog', numberOfEntriesAffected=2}
	at com.hazelcast.jet.sql.impl.schema.MappingStorage$EntryListenerAdapter.mapCleared(MappingStorage.java:160) ~[classes/:?]
	at com.hazelcast.replicatedmap.impl.ReplicatedMapEventPublishingService.dispatchEvent(ReplicatedMapEventPublishingService.java:132) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.replicatedmap.impl.ReplicatedMapService.dispatchEvent(ReplicatedMapService.java:232) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.spi.impl.eventservice.impl.LocalEventDispatcher.run(LocalEventDispatcher.java:64) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.internal.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:245) [hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.internal.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:228) [hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
BuildInfo right after test_allTypes(com.hazelcast.jet.sql.impl.connector.map.SqlCompactTest): BuildInfo{version='5.1-SNAPSHOT', build='20210917', buildNumber=20210917, revision=462045c, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'test_allTypes(com.hazelcast.jet.sql.impl.connector.map.SqlCompactTest):'
22:40:50, accumulated pauses: 732 ms, max pause: 108 ms, pauses over 1000 ms: 0


No metrics recorded during the test
```

**Comment by mmedenjak** [comment]
@sancar @mdumandag can you take a look?

**Comment by mdumandag** [comment]
It is one of those tests that are fixed by https://github.com/hazelcast/hazelcast/pull/19569
Basically, the tests are failed because the cluster version was 5.1, but the compact schema service was expecting it to be 5.0, which is fixed by the PR above.
