### ISSUE TITLE
XmlYamlClientConfigBuilderEqualsTest, ClientFailoverConfigResolutionTest and XmlClientFailoverConfigBuilderConfigResolutionTest failures

### ISSUE THREAD

**Issue by slavagithub** [hazelcast/hazelcast#19592]
com.hazelcast.client.config.ClientFailoverConfigResolutionTest, com.hazelcast.client.config.XmlClientFailoverConfigBuilderConfigResolutionTest and com.hazelcast.client.config.XmlYamlClientConfigBuilderEqualsTest.testFullClientFailoverConfig fails with "org.xml.sax.SAXParseException; schema_reference.4: Failed to read schema document 'null'" exception

master / 5.1 (rev 462045ca037af733bded32375ea4d7e96b52628a )
Failed on Zing JDK 8
http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZingJDK8/340/testReport/

Stacktrace:
```
com.hazelcast.core.HazelcastException: org.xml.sax.SAXParseException; schema_reference.4: Failed to read schema document 'null', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.
	at com.hazelcast.internal.util.ExceptionUtil.lambda$static$0(ExceptionUtil.java:56)
	at com.hazelcast.internal.util.ExceptionUtil.peel(ExceptionUtil.java:134)
	at com.hazelcast.internal.util.ExceptionUtil.peel(ExceptionUtil.java:77)
	at com.hazelcast.internal.util.ExceptionUtil.rethrow(ExceptionUtil.java:139)
	at com.hazelcast.client.config.XmlClientFailoverConfigBuilder.build(XmlClientFailoverConfigBuilder.java:152)
	at com.hazelcast.client.config.ClientFailoverClasspathXmlConfig.<init>(ClientFailoverClasspathXmlConfig.java:84)
	at com.hazelcast.client.config.ClientFailoverClasspathXmlConfig.<init>(ClientFailoverClasspathXmlConfig.java:60)
	at com.hazelcast.client.config.ClientFailoverClasspathXmlConfig.<init>(ClientFailoverClasspathXmlConfig.java:46)
	at com.hazelcast.client.config.XmlYamlClientConfigBuilderEqualsTest.testFullClientFailoverConfig(XmlYamlClientConfigBuilderEqualsTest.java:98)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.xml.sax.SAXParseException; schema_reference.4: Failed to read schema document 'null', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:134)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:396)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:306)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.reportSchemaErr(XSDHandler.java:4158)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.reportSchemaError(XSDHandler.java:4141)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.getSchemaDocument1(XSDHandler.java:2485)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.getSchemaDocument(XSDHandler.java:2193)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.parseSchema(XSDHandler.java:578)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadSchema(XMLSchemaLoader.java:610)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadGrammar(XMLSchemaLoader.java:569)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadGrammar(XMLSchemaLoader.java:535)
	at com.sun.org.apache.xerces.internal.jaxp.validation.XMLSchemaFactory.newSchema(XMLSchemaFactory.java:254)
	at com.hazelcast.config.AbstractXmlConfigHelper.schemaValidation(AbstractXmlConfigHelper.java:114)
	at com.hazelcast.client.config.XmlClientFailoverConfigBuilder.parseAndBuildConfig(XmlClientFailoverConfigBuilder.java:170)
	at com.hazelcast.client.config.XmlClientFailoverConfigBuilder.build(XmlClientFailoverConfigBuilder.java:150)
```

Standard output:
```
Started Running Test: testFullClientFailoverConfig
07:54:10,983  INFO |testFullClientFailoverConfig| - [ClientFailoverClasspathXmlConfig] testFullClientFailoverConfig - Configuring Hazelcast Client Failover from 'hazelcast-client-failover-full-example.xml'.
07:54:10,990  WARN |testFullClientFailoverConfig| - [AbstractXmlConfigHelper] testFullClientFailoverConfig - Name of the hazelcast schema location[http://www.hazelcast.com/schema/client-config/hazelcast-client-failover-config-5.0.xsd] is incorrect, using default
Started Running Test: testDefaultClientConfig
```

**Comment by ldziedziul** [comment]
Should be fixed by https://github.com/hazelcast/hazelcast/pull/19569, could you double-check?

**Comment by slavagithub** [comment]
Shure, let me close once job re-run

**Comment by mmedenjak** [comment]
Looks like it was fixed. Thank you for the fix @ldziedziul !
