### ISSUE TITLE
com.hazelcast.internal.serialization.impl.compact.extractor.ExtractionInArraySpecTest

### ISSUE THREAD

**Issue by slavagithub** [hazelcast/hazelcast#19594]
_master_ / _3.0-maintenance_ (commit INSERT_COMMIT_ID_HERE)

master / 5.1 (rev 462045c )
Failed on Zing JDK 8
http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZingJDK8/340/testReport/

Stacktrace:
```
com.hazelcast.nio.serialization.HazelcastSerializationException: Failed to serialize 'com.hazelcast.internal.serialization.impl.compact.extractor.ComplexTestDataStructure$Person'
	at com.hazelcast.internal.serialization.impl.SerializationUtil.handleSerializeException(SerializationUtil.java:129)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:238)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:214)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toData(AbstractSerializationService.java:199)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toData(AbstractSerializationService.java:154)
	at com.hazelcast.spi.impl.NodeEngineImpl.toData(NodeEngineImpl.java:381)
	at com.hazelcast.spi.impl.AbstractDistributedObject.toData(AbstractDistributedObject.java:78)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.put(MapProxyImpl.java:137)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.put(MapProxyImpl.java:128)
	at com.hazelcast.internal.serialization.impl.compact.extractor.AbstractExtractionTest.putTestDataToMap(AbstractExtractionTest.java:146)
	at com.hazelcast.internal.serialization.impl.compact.extractor.AbstractExtractionTest.execute(AbstractExtractionTest.java:165)
	at com.hazelcast.internal.serialization.impl.compact.extractor.ExtractionInArraySpecTest.comparable_primitive_reduced_comparedToNull_matching(ExtractionInArraySpecTest.java:273)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37)
	at com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:104)
	at com.hazelcast.test.metrics.MetricsRule$1.evaluate(MetricsRule.java:62)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:39)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:107)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:83)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
Caused by: java.lang.UnsupportedOperationException: The BETA compact format can only be used with 5.0 cluster
	at com.hazelcast.internal.serialization.impl.compact.schema.MemberSchemaService.putAsync(MemberSchemaService.java:136)
	at com.hazelcast.internal.serialization.impl.compact.schema.MemberSchemaService.put(MemberSchemaService.java:131)
	at com.hazelcast.internal.serialization.impl.compact.CompactStreamSerializer.putToSchemaService(CompactStreamSerializer.java:155)
	at com.hazelcast.internal.serialization.impl.compact.CompactStreamSerializer.writeObject(CompactStreamSerializer.java:168)
	at com.hazelcast.internal.serialization.impl.compact.CompactStreamSerializer.write(CompactStreamSerializer.java:130)
	at com.hazelcast.internal.serialization.impl.compact.CompactStreamSerializer.write(CompactStreamSerializer.java:123)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.write(StreamSerializerAdapter.java:39)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:235)
	... 62 more
```

Standard output:
```
09:04:55,933  INFO || - [MetricsConfigHelper] main - [LOCAL] [dev] [5.1-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
09:04:55,935  INFO || - [logo] main - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
09:04:55,935  INFO || - [system] main - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Copyright (c) 2008-2021, Hazelcast, Inc. All Rights Reserved.
09:04:55,935  INFO || - [system] main - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Hazelcast Platform 5.1-SNAPSHOT (20210919 - 462045c) starting at [127.0.0.1]:5701
09:04:55,935  INFO || - [system] main - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Cluster name: dev
09:04:55,935  INFO || - [system] main - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] The Jet engine is disabled.
To enable the Jet engine on the members, please do one of the following:
  - Change member config using Java API: config.getJetConfig().setEnabled(true);
  - Change XML/YAML configuration property: Set hazelcast.jet.enabled to true
  - Add system property: -Dhz.jet.enabled=true
  - Add environment variable: HZ_JET_ENABLED=true
09:04:55,945  INFO || - [MetricsConfigHelper] main - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
09:04:55,954  WARN || - [CPSubsystem] main - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
09:04:55,962  INFO || - [Diagnostics] main - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
09:04:55,962  INFO || - [LifecycleService] main - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] [127.0.0.1]:5701 is STARTING
09:04:55,962  INFO || - [ClusterService] main - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] 

Members {size:1, ver:1} [
	Member [127.0.0.1]:5701 - e65f89c5-b4d6-4fd7-8926-eafd9c49deb8 this
]

09:04:55,963  INFO || - [LifecycleService] main - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] [127.0.0.1]:5701 is STARTED
09:04:55,964  INFO || - [LifecycleService] main - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
09:04:55,964  WARN || - [Node] main - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Terminating forcefully...
09:04:55,964  INFO || - [Node] main - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Shutting down connection manager...
09:04:55,964  INFO || - [Node] main - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Shutting down node engine...
09:04:55,966  INFO || - [NodeExtension] main - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Destroying node NodeExtension.
09:04:55,967  INFO || - [Node] main - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Hazelcast Shutdown is completed in 3 ms.
09:04:55,967  INFO || - [LifecycleService] main - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
BuildInfo right after comparable_primitive_reduced_comparedToNull_matching[0: NO_INDEX](com.hazelcast.internal.serialization.impl.compact.extractor.ExtractionInArraySpecTest): BuildInfo{version='5.1-SNAPSHOT', build='20210919', buildNumber=20210919, revision=462045c, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'comparable_primitive_reduced_comparedToNull_matching[0: NO_INDEX](com.hazelcast.internal.serialization.impl.compact.extractor.ExtractionInArraySpecTest):'
09:04:55, accumulated pauses: 32 ms, max pause: 0 ms, pauses over 1000 ms: 0
```

**Comment by ldziedziul** [comment]
Should be fixed by https://github.com/hazelcast/hazelcast/pull/19569, could you double-check? ;)

**Comment by slavagithub** [comment]
Should be fixed, I'll close once job re-run

**Comment by mmedenjak** [comment]
Seems to be fixed. Thank you for the fix @ldziedziul !
