### ISSUE TITLE
SqlCompactTest.test_writingToTopLevelWhileNestedFieldMapped_implicit and SqlCompactTest.test_topLevelFieldExtraction

### ISSUE THREAD

**Issue by slavagithub** [hazelcast/hazelcast#19599]
_master_ / _3.0-maintenance_ (commit INSERT_COMMIT_ID_HERE)

Master / 5.1 (462045c)
Master Sonar
http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/985/testReport/
Stacktrace:
```
java.util.NoSuchElementException
	at com.hazelcast.sql.impl.client.SqlClientResult$ClientIterator.next(SqlClientResult.java:348)
	at com.hazelcast.sql.impl.client.SqlClientResult$ClientIterator.next(SqlClientResult.java:314)
	at com.hazelcast.jet.sql.impl.connector.map.SqlCompactTest.test_topLevelFieldExtraction(SqlCompactTest.java:444)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Standard output:
```
Finished Running Test: test_nulls in 0.113 seconds.
Started Running Test: test_topLevelFieldExtraction
22:40:53,699 DEBUG || - [CalciteSqlOptimizer] hz.naughty_dijkstra.client-query.thread-6 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Before logical opt:
LogicalTableSink(table=[[hazelcast, public, o_305129a4_3484_4b37_aa47_e74d15e26c9f[projects=[0, 1, 2, 3]]]], operation=[INSERT], flattened=[false])
  LogicalProject(id=[1], __key=[null:OBJECT], name=[_UTF-16LE'Alice':VARCHAR CHARACTER SET "UTF-16LE"], this=[null:OBJECT])
    LogicalValues(tuples=[[{ 0 }]])

22:40:53,700 DEBUG || - [CalciteSqlOptimizer] hz.naughty_dijkstra.client-query.thread-6 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] After logical opt:
SinkMapLogicalRel(table=[[hazelcast, public, o_305129a4_3484_4b37_aa47_e74d15e26c9f[projects=[0, 1, 2, 3]]]], values=[[{projection=[ConstantExpression{type=QueryDataType {family=INTEGER}, value=1}, ConstantExpression{type=QueryDataType {family=OBJECT}, value=null}, ConstantExpression{type=QueryDataType {family=VARCHAR}, value=Alice}, ConstantExpression{type=QueryDataType {family=OBJECT}, value=null}], values=[{expressions=[[ConstantExpression{type=QueryDataType {family=INTEGER}, value=0}]]}]}]])

22:40:53,700 DEBUG || - [CalciteSqlOptimizer] hz.naughty_dijkstra.client-query.thread-6 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] After physical opt:
SinkMapPhysicalRel(table=[[hazelcast, public, o_305129a4_3484_4b37_aa47_e74d15e26c9f[projects=[0, 1, 2, 3]]]], values=[[{projection=[ConstantExpression{type=QueryDataType {family=INTEGER}, value=1}, ConstantExpression{type=QueryDataType {family=OBJECT}, value=null}, ConstantExpression{type=QueryDataType {family=VARCHAR}, value=Alice}, ConstantExpression{type=QueryDataType {family=OBJECT}, value=null}], values=[{expressions=[[ConstantExpression{type=QueryDataType {family=INTEGER}, value=0}]]}]}]])

22:40:53,704 DEBUG || - [CalciteSqlOptimizer] hz.naughty_dijkstra.client-query.thread-7 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Before logical opt:
LogicalProject(__key=[$1], this=[$3])
  LogicalTableScan(table=[[hazelcast, public, o_305129a4_3484_4b37_aa47_e74d15e26c9f[projects=[0, 1, 2, 3]]]])

22:40:53,705 DEBUG || - [CalciteSqlOptimizer] hz.naughty_dijkstra.client-query.thread-7 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] After logical opt:
FullScanLogicalRel(table=[[hazelcast, public, o_305129a4_3484_4b37_aa47_e74d15e26c9f[projects=[1, 3]]]])

22:40:53,705 DEBUG || - [CalciteSqlOptimizer] hz.naughty_dijkstra.client-query.thread-7 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] After physical opt:
FullScanPhysicalRel(table=[[hazelcast, public, o_305129a4_3484_4b37_aa47_e74d15e26c9f[projects=[1, 3]]]])

22:40:53,707 DEBUG || - [LightMasterContext] hz.naughty_dijkstra.client-query.thread-7 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Start executing light job 06d1-b9b8-f280-0001, execution graph in DOT format:
digraph DAG {
	"IMap[public.o_305129a4_3484_4b37_aa47_e74d15e26c9f]" [localParallelism=1];
	"Project(IMap[public.o_305129a4_3484_4b37_aa47_e74d15e26c9f])" [localParallelism=default];
	"ClientSink" [localParallelism=1];
	"IMap[public.o_305129a4_3484_4b37_aa47_e74d15e26c9f]" -> "Project(IMap[public.o_305129a4_3484_4b37_aa47_e74d15e26c9f])" [label="isolated", queueSize=1024];
	"Project(IMap[public.o_305129a4_3484_4b37_aa47_e74d15e26c9f])" -> "ClientSink" [label="distributed to [127.0.0.1]:5701-partitioned", queueSize=1024];
}
HINT: You can use graphviz or http://viz-js.com to visualize the printed graph.
22:40:53,707 DEBUG || - [LightMasterContext] hz.naughty_dijkstra.client-query.thread-7 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Building execution plan for 06d1-b9b8-f280-0001
22:40:53,707 DEBUG || - [LightMasterContext] hz.naughty_dijkstra.client-query.thread-7 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Built execution plans for 06d1-b9b8-f280-0001
22:40:53,707 DEBUG || - [InitExecutionOperation] hz.naughty_dijkstra.client-query.thread-7 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Initializing execution plan for job 06d1-b9b8-f280-0001, execution 06d1-b9b8-f280-0001 from [127.0.0.1]:5701
22:40:53,708 DEBUG || - [JobExecutionService] hz.naughty_dijkstra.client-query.thread-7 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Execution plan for light job ID=06d1-b9b8-f280-0001, jobName='06d1-b9b8-f280-0001', executionId=06d1-b9b8-f280-0001 initialized, will start the execution
22:40:53,719  WARN || - [JobClassLoaderService] ForkJoinPool.commonPool-worker-7 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] JobClassLoaders for jobId=06d1-b9b8-f280-0001 already removed
22:40:53,719 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-7 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Completed execution of job '06d1-b9b8-f280-0001', execution 06d1-b9b8-f280-0001
22:40:53,719 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-7 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Execution of job '06d1-b9b8-f280-0001', execution 06d1-b9b8-f280-0001 completed
22:40:53,828  INFO |test_topLevelFieldExtraction| - [SqlTestSupport] Time-limited test - Removing 2 cached plans in SqlTestSupport.@After
22:40:53,829  INFO |test_topLevelFieldExtraction| - [SimpleTestInClusterSupport] Time-limited test - Ditching 0 jobs in SimpleTestInClusterSupport.@After: []
22:40:53,829  INFO |test_topLevelFieldExtraction| - [SimpleTestInClusterSupport] Time-limited test - Destroying 3 distributed objects in SimpleTestInClusterSupport.@After: [hz:impl:replicatedMapService/__sql.catalog, hz:impl:mapService/o_305129a4_3484_4b37_aa47_e74d15e26c9f, hz:impl:flakeIdGeneratorService/__jet.ids]
22:40:53,829 ERROR || - [EventServiceImpl] hz.naughty_dijkstra.event-22 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] hz.naughty_dijkstra.event-22 caught an exception while processing:com.hazelcast.spi.impl.eventservice.impl.LocalEventDispatcher@6e7e2156
java.lang.UnsupportedOperationException: SQL catalog must never be cleared - MapEvent{entryEventType=CLEAR_ALL, member=Member [127.0.0.1]:5701 - 13ba42d0-3198-4384-8456-7a667126187f this, name='__sql.catalog', numberOfEntriesAffected=1}
	at com.hazelcast.jet.sql.impl.schema.MappingStorage$EntryListenerAdapter.mapCleared(MappingStorage.java:160) ~[classes/:?]
	at com.hazelcast.replicatedmap.impl.ReplicatedMapEventPublishingService.dispatchEvent(ReplicatedMapEventPublishingService.java:132) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.replicatedmap.impl.ReplicatedMapService.dispatchEvent(ReplicatedMapService.java:232) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.spi.impl.eventservice.impl.LocalEventDispatcher.run(LocalEventDispatcher.java:64) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.internal.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:245) [hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.internal.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:228) [hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
BuildInfo right after test_topLevelFieldExtraction(com.hazelcast.jet.sql.impl.connector.map.SqlCompactTest): BuildInfo{version='5.1-SNAPSHOT', build='20210917', buildNumber=20210917, revision=462045c, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'test_topLevelFieldExtraction(com.hazelcast.jet.sql.impl.connector.map.SqlCompactTest):'
22:40:50, accumulated pauses: 313 ms, max pause: 96 ms, pauses over 1000 ms: 0
```

**Comment by slavagithub** [comment]
This failure might be related to https://github.com/hazelcast/hazelcast/issues/19427

**Comment by mdumandag** [comment]
This is also fixed by https://github.com/hazelcast/hazelcast/pull/19569.
The reasoning is the same with https://github.com/hazelcast/hazelcast/issues/19597#issuecomment-929206233
