### ISSUE TITLE
com.hazelcast.internal.nio.ascii.TextProtocolsConfigTest

### ISSUE THREAD

**Issue by slavagithub** [hazelcast/hazelcast#19593]
com.hazelcast.internal.nio.ascii.TextProtocolsConfigTest fails because it expects 5.0 version

master / 5.1 (rev 462045c )
Failed on Zing JDK 8
http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZingJDK8/340/testReport/

Stacktrace:
```
java.lang.AssertionError: 
TestUrl [restEndpointGroup=CLUSTER_READ, method=GET, requestUri=/hazelcast/rest/management/cluster/version, expectedSubstring=5.0]
Expected: a string containing "5.0"
     but: was "HTTP/1.1 200 OK
Content-Type: application/json
Content-Length: 36

{"status":"success","version":"5.1"}"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:964)
	at com.hazelcast.internal.nio.ascii.AbstractTextProtocolsTestBase$1.run(AbstractTextProtocolsTestBase.java:51)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1260)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1277)
	at com.hazelcast.internal.nio.ascii.RestApiConfigTestBase.assertTextProtocolResponse(RestApiConfigTestBase.java:135)
	at com.hazelcast.internal.nio.ascii.TextProtocolsConfigTest.testRestApiCallEnabledGroupsEnabled(TextProtocolsConfigTest.java:122)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

Standard output:
```
Finished Running Test: testEnabledRestApiCallWithGroupDefaults in 10.608 seconds.
09:46:49,099  INFO |testRestApiCallEnabledGroupsEnabled| - [LifecycleService] Thread-38461 - [127.0.0.1]:5082 [testRestApiCallEnabledGroupsEnabled] [5.1-SNAPSHOT] [127.0.0.1]:5082 is SHUTTING_DOWN
09:46:49,099  WARN |testRestApiCallEnabledGroupsEnabled| - [Node] Thread-38461 - [127.0.0.1]:5082 [testRestApiCallEnabledGroupsEnabled] [5.1-SNAPSHOT] Terminating forcefully...
09:46:49,099  INFO |testRestApiCallEnabledGroupsEnabled| - [TextCommandServiceImpl] Thread-38461 - [127.0.0.1]:5082 [testRestApiCallEnabledGroupsEnabled] [5.1-SNAPSHOT] Stopping text command service...
09:46:49,099  INFO |testRestApiCallEnabledGroupsEnabled| - [Node] Thread-38461 - [127.0.0.1]:5082 [testRestApiCallEnabledGroupsEnabled] [5.1-SNAPSHOT] Shutting down connection manager...
09:46:49,100  INFO |testRestApiCallEnabledGroupsEnabled| - [Node] Thread-38461 - [127.0.0.1]:5082 [testRestApiCallEnabledGroupsEnabled] [5.1-SNAPSHOT] Shutting down node engine...
09:46:49,103  INFO |testRestApiCallEnabledGroupsEnabled| - [NodeExtension] Thread-38461 - [127.0.0.1]:5082 [testRestApiCallEnabledGroupsEnabled] [5.1-SNAPSHOT] Destroying node NodeExtension.
09:46:49,103  INFO |testRestApiCallEnabledGroupsEnabled| - [Node] Thread-38461 - [127.0.0.1]:5082 [testRestApiCallEnabledGroupsEnabled] [5.1-SNAPSHOT] Hazelcast Shutdown is completed in 4 ms.
09:46:49,103  INFO |testRestApiCallEnabledGroupsEnabled| - [LifecycleService] Thread-38461 - [127.0.0.1]:5082 [testRestApiCallEnabledGroupsEnabled] [5.1-SNAPSHOT] [127.0.0.1]:5082 is SHUTDOWN
```

**Comment by ldziedziul** [comment]
Should be fixed by https://github.com/hazelcast/hazelcast/pull/19569, could you double-check?

**Comment by slavagithub** [comment]
I'll close once job re-run and test passed

**Comment by mmedenjak** [comment]
Seems to be fixed. Thank you for the fix @ldziedziul !

**Comment by slavagithub** [comment]
came back on master, Corretto, JDK8 - http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-CorrettoJDK8/166/testReport/com.hazelcast.internal.nio.ascii/TextProtocolsConfigTest/testEnabledRestApiCallWithGroupDefaults/

**Comment by slavagithub** [comment]
the same on master Oracle, JDK8 - http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-OracleJDK8/186/testReport/com.hazelcast.internal.nio.ascii/TextProtocolsConfigTest/testEnabledRestApiCallWithGroupDefaults/

**Comment by slavagithub** [comment]
The same for Master, Zulu, JDK8 - http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZuluJDK8/175/testReport/com.hazelcast.internal.nio.ascii/TextProtocolsConfigTest/testEnabledRestApiCallWithGroupDefaults/

**Comment by olukas** [comment]
Closing since this seems to be relevant only for `5.1` version. We have similar issue for `5.3` which will be reported in separate issue.
