### ISSUE TITLE
Hz3EnrichmentTest, Hz3SinksTest, Hz3SourcesTest, Hazelcast3StarterTest failures

### ISSUE THREAD

**Issue by slavagithub** [hazelcast/hazelcast#19608]
com.hazelcast.connector.Hz3EnrichmentTest, com.hazelcast.connector.Hz3SinksTest, com.hazelcast.connector.Hz3SourcesTest, com.hazelcast.test.starter.hz3.Hazelcast3StarterTest fail with "URI is not hierarchical" error

master /5.1 (rev. 462045ca037af733bded32375ea4d7e96b52628a)

Failed on Windows, Oracle JDK 8
http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Windows-OracleJDK8/323/testReport/

Stacktrace:
```
java.lang.IllegalArgumentException: URI is not hierarchical
	at java.io.File.<init>(File.java:418)
	at com.hazelcast.jet.impl.deployment.ChildFirstClassLoader.<init>(ChildFirstClassLoader.java:51)
	at com.hazelcast.test.starter.hz3.Hazelcast3Proxy.newHazelcastInstance(Hazelcast3Proxy.java:64)
	at com.hazelcast.test.starter.hz3.Hazelcast3Starter.newHazelcastInstance(Hazelcast3Starter.java:34)
	at com.hazelcast.connector.BaseHz3Test.setUp(BaseHz3Test.java:107)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37)
	at com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:104)
	at com.hazelcast.test.metrics.MetricsRule$1.evaluate(MetricsRule.java:62)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:107)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:83)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:157)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
```

Standard output:
```
BuildInfo right after when_tryToReadFromHz5Cluster_then_shouldThrowJetException(com.hazelcast.connector.Hz3SourcesTest): BuildInfo{version='5.1-SNAPSHOT', build='20210919', buildNumber=20210919, revision=462045c, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'when_tryToReadFromHz5Cluster_then_shouldThrowJetException(com.hazelcast.connector.Hz3SourcesTest):'
14:50:30, accumulated pauses: 1231 ms, max pause: 122 ms, pauses over 1000 ms: 0


No metrics recorded during the test
```

**Comment by olukas** [comment]
Fails also on `5.0.z` branch on Windows with Oracle JDK 8: http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-Windows-OracleJDK8/1/testReport/com.hazelcast.connector/

**Comment by mmedenjak** [comment]
@frant-hartm can you take a look?
