### ISSUE TITLE
SqlCompactTest.test_nulls

### ISSUE THREAD

**Issue by slavagithub** [hazelcast/hazelcast#19600]
com.hazelcast.jet.sql.impl.connector.map.SqlCompactTest.test_nulls fails with Failed to serialize 'com.hazelcast.internal.serialization.impl.compact.DeserializedGenericRecord' error

Master / 5.1 (462045c)
Master Sonar
http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/985/testReport/

Stacktrace:
```
com.hazelcast.sql.HazelcastSqlException: Failed to serialize 'com.hazelcast.internal.serialization.impl.compact.DeserializedGenericRecord'
	at com.hazelcast.sql.impl.client.SqlClientService.handleResponseError(SqlClientService.java:276)
	at com.hazelcast.sql.impl.client.SqlClientService.handleExecuteResponse(SqlClientService.java:135)
	at com.hazelcast.sql.impl.client.SqlClientService.lambda$execute$0(SqlClientService.java:108)
	at com.hazelcast.internal.util.ExceptionUtil.lambda$withTryCatch$1(ExceptionUtil.java:207)
	at com.hazelcast.client.impl.spi.impl.ClientInvocationFuture$CallIdTrackingBiConsumer.accept(ClientInvocationFuture.java:268)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$WhenCompleteNode.lambda$execute$0(AbstractInvocationFuture.java:1563)
	at com.hazelcast.test.TestLoggingUtils$CustomTestNameAwareForkJoinPool$TestNameAwareRunnable.run(TestLoggingUtils.java:104)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

Standard output:
```
Finished Running Test: test_fieldsMapping in 0.148 seconds.
Started Running Test: test_nulls
22:40:53,586 DEBUG || - [CalciteSqlOptimizer] hz.naughty_dijkstra.client-query.thread-4 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Before logical opt:
LogicalTableSink(table=[[hazelcast, public, o_e72c2210_1a2b_43a4_a2e4_112f2f3b8323[projects=[0, 1, 2, 3]]]], operation=[INSERT], flattened=[false])
  LogicalProject(key_id=[1], __key=[null:OBJECT], name=[null:VARCHAR CHARACTER SET "UTF-16LE"], this=[null:OBJECT])
    LogicalValues(tuples=[[{ 0 }]])

22:40:53,586 DEBUG || - [CalciteSqlOptimizer] hz.naughty_dijkstra.client-query.thread-4 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] After logical opt:
SinkMapLogicalRel(table=[[hazelcast, public, o_e72c2210_1a2b_43a4_a2e4_112f2f3b8323[projects=[0, 1, 2, 3]]]], values=[[{projection=[ConstantExpression{type=QueryDataType {family=INTEGER}, value=1}, ConstantExpression{type=QueryDataType {family=OBJECT}, value=null}, ConstantExpression{type=QueryDataType {family=VARCHAR}, value=null}, ConstantExpression{type=QueryDataType {family=OBJECT}, value=null}], values=[{expressions=[[ConstantExpression{type=QueryDataType {family=INTEGER}, value=0}]]}]}]])

22:40:53,587 DEBUG || - [CalciteSqlOptimizer] hz.naughty_dijkstra.client-query.thread-4 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] After physical opt:
SinkMapPhysicalRel(table=[[hazelcast, public, o_e72c2210_1a2b_43a4_a2e4_112f2f3b8323[projects=[0, 1, 2, 3]]]], values=[[{projection=[ConstantExpression{type=QueryDataType {family=INTEGER}, value=1}, ConstantExpression{type=QueryDataType {family=OBJECT}, value=null}, ConstantExpression{type=QueryDataType {family=VARCHAR}, value=null}, ConstantExpression{type=QueryDataType {family=OBJECT}, value=null}], values=[{expressions=[[ConstantExpression{type=QueryDataType {family=INTEGER}, value=0}]]}]}]])

22:40:53,691  INFO |test_nulls| - [SqlTestSupport] Time-limited test - Removing 1 cached plans in SqlTestSupport.@After
22:40:53,692  INFO |test_nulls| - [SimpleTestInClusterSupport] Time-limited test - Ditching 0 jobs in SimpleTestInClusterSupport.@After: []
22:40:53,692  INFO |test_nulls| - [SimpleTestInClusterSupport] Time-limited test - Destroying 2 distributed objects in SimpleTestInClusterSupport.@After: [hz:impl:replicatedMapService/__sql.catalog, hz:impl:mapService/o_e72c2210_1a2b_43a4_a2e4_112f2f3b8323]
22:40:53,692 ERROR || - [EventServiceImpl] hz.naughty_dijkstra.event-22 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] hz.naughty_dijkstra.event-22 caught an exception while processing:com.hazelcast.spi.impl.eventservice.impl.LocalEventDispatcher@6a41a8c6
java.lang.UnsupportedOperationException: SQL catalog must never be cleared - MapEvent{entryEventType=CLEAR_ALL, member=Member [127.0.0.1]:5701 - 13ba42d0-3198-4384-8456-7a667126187f this, name='__sql.catalog', numberOfEntriesAffected=1}
	at com.hazelcast.jet.sql.impl.schema.MappingStorage$EntryListenerAdapter.mapCleared(MappingStorage.java:160) ~[classes/:?]
	at com.hazelcast.replicatedmap.impl.ReplicatedMapEventPublishingService.dispatchEvent(ReplicatedMapEventPublishingService.java:132) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.replicatedmap.impl.ReplicatedMapService.dispatchEvent(ReplicatedMapService.java:232) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.spi.impl.eventservice.impl.LocalEventDispatcher.run(LocalEventDispatcher.java:64) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.internal.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:245) [hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.internal.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:228) [hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
BuildInfo right after test_nulls(com.hazelcast.jet.sql.impl.connector.map.SqlCompactTest): BuildInfo{version='5.1-SNAPSHOT', build='20210917', buildNumber=20210917, revision=462045c, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'test_nulls(com.hazelcast.jet.sql.impl.connector.map.SqlCompactTest):'
22:40:50, accumulated pauses: 216 ms, max pause: 93 ms, pauses over 1000 ms: 0
```

**Comment by mmedenjak** [comment]
@sancar @mdumandag can you take a look?

**Comment by mdumandag** [comment]
This is also fixed by https://github.com/hazelcast/hazelcast/pull/19569.
The reasoning is the same with https://github.com/hazelcast/hazelcast/issues/19597#issuecomment-929206233
