### ISSUE TITLE
auto-disposable tasks for ScheduledExecutor only works for Callable

### ISSUE THREAD

**Issue by yquest** [hazelcast/hazelcast#19622]
Hello guys I did a test with the autodisposable method of TaskUtils like this:

```java
        public class RunnableExample implements Serializable, Runnable{
            @Override
            public void run() {
                System.out.println("running "+getClass().getName());
            }
        }

        Config config = new Config();
        config.getScheduledExecutorConfig(RUNNABLES).setCapacity(2);
        hazelcast = Hazelcast.newHazelcastInstance(config);
        IScheduledExecutorService runnables = hazelcast.getScheduledExecutorService(RUNNABLES);

        for (int i = 0; i < 4; i++) {
            runnables.schedule(TaskUtils.autoDisposable(new RunnableExample()), 1, TimeUnit.SECONDS);
            Thread.sleep(1000);
        }

```

This implementations throws the error:
```
java.util.concurrent.RejectedExecutionException: Maximum capacity (2) of tasks reached for this member and scheduled executor (runnables). Reminder, that tasks must be disposed if not needed.
	at com.hazelcast.scheduledexecutor.impl.MemberCapacityPermit.acquire(MemberCapacityPermit.java:41)
	at com.hazelcast.scheduledexecutor.impl.ScheduledExecutorContainer.acquirePermit(ScheduledExecutorContainer.java:349)
	at com.hazelcast.scheduledexecutor.impl.ScheduledExecutorContainer.schedule(ScheduledExecutorContainer.java:128)
	at com.hazelcast.scheduledexecutor.impl.operations.ScheduleTaskOperation.run(ScheduleTaskOperation.java:45)
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:189)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:272)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:248)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:213)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:175)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:139)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
```

If I do that with Callable<Void> instead of Runnable this doesn't happen.

You can check this out on my repository project [issue-hazelcast-autodisposable](https://github.com/yquest/issue-hazelcast-autodisposable)

**Comment by yquest** [comment]
The java exception on (maven build)[https://github.com/yquest/issue-hazelcast-autodisposable/runs/3688212402?check_suite_focus=true]

**Comment by peterjot** [comment]
Hey, I will fix this. Thanks for reporting this bug 👍

**Comment by yquest** [comment]
Your welcome, it's pleasant to be helpful to you guys 🙂

Obter o Outlook para Android<https://aka.ms/ghei36>
________________________________
