### ISSUE TITLE
ExecutionLifecycleTest.when_psGetThrows_then_jobFails

### ISSUE THREAD

**Issue by srknzl** [hazelcast/hazelcast#19627]
_master_  (commit 4a2912a2d496c044395c3ee96669b64fc32a889d)

Failed on PR Builder: http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/7572/testReport/junit/com.hazelcast.jet.core/ExecutionLifecycleTest/when_psGetThrows_then_jobFails_useLightJob_true_/

Stacktrace:
```
java.lang.AssertionError: close not called
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at com.hazelcast.jet.core.ExecutionLifecycleTest.assertPmsClosedWithError(ExecutionLifecycleTest.java:765)
	at com.hazelcast.jet.core.ExecutionLifecycleTest.when_psGetThrows_then_jobFails(ExecutionLifecycleTest.java:256)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)

```

Standard output:
```
Finished Running Test: when_psInitThrows_then_jobFails[useLightJob=true] in 0.006 seconds.
Started Running Test: when_psGetThrows_then_jobFails[useLightJob=true]
10:54:45,950 DEBUG |when_psGetThrows_then_jobFails[useLightJob=true]| - [LightMasterContext] when_psGetThrows_then_jobFails - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Start executing light job 06da-1b37-a888-0001, execution graph in DOT format:
digraph DAG {
	"faulty" [localParallelism=default];
}
HINT: You can use graphviz or http://viz-js.com to visualize the printed graph.
10:54:45,950 DEBUG |when_psGetThrows_then_jobFails[useLightJob=true]| - [LightMasterContext] when_psGetThrows_then_jobFails - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Building execution plan for 06da-1b37-a888-0001
10:54:45,950 DEBUG |when_psGetThrows_then_jobFails[useLightJob=true]| - [LightMasterContext] when_psGetThrows_then_jobFails - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Built execution plans for 06da-1b37-a888-0001
10:54:45,951 DEBUG || - [InitExecutionOperation] hz.optimistic_hawking.generic-operation.thread-1 - [127.0.0.1]:5702 [dev] [5.1-SNAPSHOT] Initializing execution plan for job 06da-1b37-a888-0001, execution 06da-1b37-a888-0001 from [127.0.0.1]:5701
10:54:45,951 DEBUG |when_psGetThrows_then_jobFails[useLightJob=true]| - [InitExecutionOperation] when_psGetThrows_then_jobFails - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Initializing execution plan for job 06da-1b37-a888-0001, execution 06da-1b37-a888-0001 from [127.0.0.1]:5701
10:54:45,951 ERROR |when_psGetThrows_then_jobFails[useLightJob=true]| - [ExecutionContext] when_psGetThrows_then_jobFails - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] job '06da-1b37-a888-0001', execution 06da-1b37-a888-0001 encountered an exception in ProcessorSupplier.close(), ignoring it
java.lang.AssertionError: Close called without init being called on all the nodes. Init count: 1 node count: 2
	at org.junit.Assert.fail(Assert.java:89) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.Assert.assertTrue(Assert.java:42) ~[junit-4.13.2.jar:4.13.2]
	at com.hazelcast.jet.core.TestProcessors$MockPS.close(TestProcessors.java:278) ~[test-classes/:?]
	at com.hazelcast.jet.impl.execution.ExecutionContext.lambda$null$689bdc39$1(ExecutionContext.java:260) ~[classes/:?]
	at com.hazelcast.jet.function.RunnableEx.run(RunnableEx.java:31) ~[classes/:?]
	at com.hazelcast.jet.impl.util.Util.doWithClassLoader(Util.java:516) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.ExecutionContext.lambda$completeExecution$e411c726$1(ExecutionContext.java:260) ~[classes/:?]
	at com.hazelcast.jet.function.RunnableEx.run(RunnableEx.java:31) ~[classes/:?]
	at com.hazelcast.jet.impl.util.Util.doWithClassLoader(Util.java:516) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.ExecutionContext.completeExecution(ExecutionContext.java:255) ~[classes/:?]
	at com.hazelcast.jet.impl.JobExecutionService.lambda$completeExecution$559b0d71$1(JobExecutionService.java:461) ~[classes/:?]
	at com.hazelcast.jet.function.RunnableEx.run(RunnableEx.java:31) [classes/:?]
	at com.hazelcast.jet.impl.util.Util.doWithClassLoader(Util.java:516) [classes/:?]
	at com.hazelcast.jet.impl.JobExecutionService.completeExecution(JobExecutionService.java:461) [classes/:?]
	at com.hazelcast.jet.impl.JobExecutionService.runLightJob(JobExecutionService.java:256) [classes/:?]
	at com.hazelcast.jet.impl.operation.InitExecutionOperation.doRun(InitExecutionOperation.java:94) [classes/:?]
	at com.hazelcast.jet.impl.operation.AsyncOperation.run(AsyncOperation.java:54) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:189) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:272) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:248) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:213) [classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:411) [classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:438) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:600) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:579) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:540) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:240) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:59) [classes/:?]
	at com.hazelcast.jet.impl.LightMasterContext.invokeOnParticipant(LightMasterContext.java:220) [classes/:?]
	at com.hazelcast.jet.impl.LightMasterContext.invokeOnParticipants(LightMasterContext.java:206) [classes/:?]
	at com.hazelcast.jet.impl.LightMasterContext.<init>(LightMasterContext.java:137) [classes/:?]
	at com.hazelcast.jet.impl.JobCoordinationService.submitLightJob(JobCoordinationService.java:336) [classes/:?]
	at com.hazelcast.jet.impl.operation.SubmitJobOperation.doRun(SubmitJobOperation.java:57) [classes/:?]
	at com.hazelcast.jet.impl.operation.AsyncOperation.run(AsyncOperation.java:54) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:189) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:272) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:248) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:213) [classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:411) [classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:438) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:600) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:579) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:540) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:240) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:59) [classes/:?]
	at com.hazelcast.jet.impl.JobProxy.invokeOp(JobProxy.java:192) [classes/:?]
	at com.hazelcast.jet.impl.JobProxy.invokeSubmitJob(JobProxy.java:110) [classes/:?]
	at com.hazelcast.jet.impl.AbstractJobProxy.doSubmitJob(AbstractJobProxy.java:317) [classes/:?]
	at com.hazelcast.jet.impl.AbstractJobProxy.<init>(AbstractJobProxy.java:104) [classes/:?]
	at com.hazelcast.jet.impl.JobProxy.<init>(JobProxy.java:65) [classes/:?]
	at com.hazelcast.jet.impl.JetInstanceImpl.newJobProxy(JetInstanceImpl.java:155) [classes/:?]
	at com.hazelcast.jet.impl.AbstractJetInstance.newJobInt(AbstractJetInstance.java:144) [classes/:?]
	at com.hazelcast.jet.impl.AbstractJetInstance.newLightJob(AbstractJetInstance.java:198) [classes/:?]
	at com.hazelcast.jet.JetService.newLightJob(JetService.java:198) [classes/:?]
	at com.hazelcast.jet.core.ExecutionLifecycleTest.newJob(ExecutionLifecycleTest.java:730) [test-classes/:?]
	at com.hazelcast.jet.core.ExecutionLifecycleTest.runJobExpectFailure(ExecutionLifecycleTest.java:744) [test-classes/:?]
	at com.hazelcast.jet.core.ExecutionLifecycleTest.when_psGetThrows_then_jobFails(ExecutionLifecycleTest.java:252) [test-classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_251]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_251]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_251]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59) [junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56) [junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) [junit-4.13.2.jar:4.13.2]
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115) [test-classes/:?]
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107) [test-classes/:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_251]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]
10:54:45,952 DEBUG |when_psGetThrows_then_jobFails[useLightJob=true]| - [JobExecutionService] when_psGetThrows_then_jobFails - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Completed execution of job '06da-1b37-a888-0001', execution 06da-1b37-a888-0001
10:54:45,952 ERROR |when_psGetThrows_then_jobFails[useLightJob=true]| - [InitExecutionOperation] when_psGetThrows_then_jobFails - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] mock error
java.lang.AssertionError: mock error
	at com.hazelcast.jet.core.ExecutionLifecycleTest.<clinit>(ExecutionLifecycleTest.java:110) ~[test-classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_251]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_251]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_251]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.Parameterized$RunnersFactory.allParameters(Parameterized.java:424) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.Parameterized$RunnersFactory.<init>(Parameterized.java:375) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.Parameterized$RunnersFactory.<init>(Parameterized.java:360) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.Parameterized.<init>(Parameterized.java:303) ~[junit-4.13.2.jar:4.13.2]
	at com.hazelcast.test.HazelcastParametrizedRunner.<init>(HazelcastParametrizedRunner.java:31) ~[test-classes/:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_251]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_251]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_251]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_251]
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:70) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:37) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runner.Computer.getRunner(Computer.java:50) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runner.Computer$1.runnerForClass(Computer.java:31) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:70) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.model.RunnerBuilder.runners(RunnerBuilder.java:125) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.model.RunnerBuilder.runners(RunnerBuilder.java:111) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.Suite.<init>(Suite.java:81) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runner.Computer$2.<init>(Computer.java:33) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runner.Computer.getSuite(Computer.java:28) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runner.Request.classes(Request.java:77) ~[junit-4.13.2.jar:4.13.2]
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:126) ~[surefire-junit47-2.22.2.jar:2.22.2]
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeLazy(JUnitCoreWrapper.java:119) ~[surefire-junit47-2.22.2.jar:2.22.2]
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:87) ~[surefire-junit47-2.22.2.jar:2.22.2]
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75) ~[surefire-junit47-2.22.2.jar:2.22.2]
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158) ~[surefire-junit47-2.22.2.jar:2.22.2]
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384) ~[surefire-booter-2.22.2.jar:2.22.2]
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345) ~[surefire-booter-2.22.2.jar:2.22.2]
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126) ~[surefire-booter-2.22.2.jar:2.22.2]
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418) ~[surefire-booter-2.22.2.jar:2.22.2]
10:54:45,952 DEBUG || - [JobExecutionService] hz.optimistic_hawking.generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.1-SNAPSHOT] job '06da-1b37-a888-0001', execution 06da-1b37-a888-0001 calling completeExecution because execution terminated before it started
10:54:45,952 DEBUG || - [JobExecutionService] hz.optimistic_hawking.generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.1-SNAPSHOT] Completed execution of job '06da-1b37-a888-0001', execution 06da-1b37-a888-0001
10:54:45,953 DEBUG || - [JobExecutionService] hz.optimistic_hawking.generic-operation.thread-1 - [127.0.0.1]:5702 [dev] [5.1-SNAPSHOT] Completed execution of job '06da-1b37-a888-0001', execution 06da-1b37-a888-0001
10:54:45,953 ERROR || - [InitExecutionOperation] hz.optimistic_hawking.generic-operation.thread-1 - [127.0.0.1]:5702 [dev] [5.1-SNAPSHOT] mock error
java.lang.AssertionError: mock error
	at com.hazelcast.jet.core.ExecutionLifecycleTest.<clinit>(ExecutionLifecycleTest.java:110) ~[test-classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_251]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_251]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_251]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.Parameterized$RunnersFactory.allParameters(Parameterized.java:424) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.Parameterized$RunnersFactory.<init>(Parameterized.java:375) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.Parameterized$RunnersFactory.<init>(Parameterized.java:360) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.Parameterized.<init>(Parameterized.java:303) ~[junit-4.13.2.jar:4.13.2]
	at com.hazelcast.test.HazelcastParametrizedRunner.<init>(HazelcastParametrizedRunner.java:31) ~[test-classes/:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_251]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_251]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_251]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_251]
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:70) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:37) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runner.Computer.getRunner(Computer.java:50) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runner.Computer$1.runnerForClass(Computer.java:31) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:70) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.model.RunnerBuilder.runners(RunnerBuilder.java:125) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.model.RunnerBuilder.runners(RunnerBuilder.java:111) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.Suite.<init>(Suite.java:81) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runner.Computer$2.<init>(Computer.java:33) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runner.Computer.getSuite(Computer.java:28) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runner.Request.classes(Request.java:77) ~[junit-4.13.2.jar:4.13.2]
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:126) ~[surefire-junit47-2.22.2.jar:2.22.2]
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeLazy(JUnitCoreWrapper.java:119) ~[surefire-junit47-2.22.2.jar:2.22.2]
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:87) ~[surefire-junit47-2.22.2.jar:2.22.2]
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75) ~[surefire-junit47-2.22.2.jar:2.22.2]
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158) ~[surefire-junit47-2.22.2.jar:2.22.2]
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384) ~[surefire-booter-2.22.2.jar:2.22.2]
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345) ~[surefire-booter-2.22.2.jar:2.22.2]
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126) ~[surefire-booter-2.22.2.jar:2.22.2]
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418) ~[surefire-booter-2.22.2.jar:2.22.2]
10:54:45,953 ERROR || - [LightMasterContext] ForkJoinPool.commonPool-worker-12 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] 06da-1b37-a888-0001 encountered an exception in ProcessorMetaSupplier.complete(), ignoring it
java.lang.AssertionError: all PS that have been init should have been closed at this point expected:<2> but was:<1>
	at org.junit.Assert.fail(Assert.java:89) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.Assert.failNotEquals(Assert.java:835) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.Assert.assertEquals(Assert.java:647) ~[junit-4.13.2.jar:4.13.2]
	at com.hazelcast.jet.core.TestProcessors$MockPMS.close(TestProcessors.java:201) ~[test-classes/:?]
	at com.hazelcast.jet.impl.LightMasterContext.finalizeJob(LightMasterContext.java:151) ~[classes/:?]
	at com.hazelcast.jet.impl.LightMasterContext.lambda$new$2(LightMasterContext.java:138) ~[classes/:?]
	at com.hazelcast.jet.impl.LightMasterContext.lambda$invokeOnParticipant$5(LightMasterContext.java:238) ~[classes/:?]
	at com.hazelcast.spi.impl.AbstractInvocationFuture$WhenCompleteNode.lambda$execute$0(AbstractInvocationFuture.java:1563) ~[classes/:?]
	at com.hazelcast.test.TestLoggingUtils$CustomTestNameAwareForkJoinPool$TestNameAwareRunnable.run(TestLoggingUtils.java:104) [test-classes/:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) [?:1.8.0_251]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_251]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_251]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_251]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_251]
10:54:46,070  INFO |when_psGetThrows_then_jobFails[useLightJob=true]| - [SimpleTestInClusterSupport] Time-limited test - Ditching 0 jobs in SimpleTestInClusterSupport.@After: []
10:54:46,070  INFO |when_psGetThrows_then_jobFails[useLightJob=true]| - [SimpleTestInClusterSupport] Time-limited test - Destroying 0 distributed objects in SimpleTestInClusterSupport.@After: []
BuildInfo right after when_psGetThrows_then_jobFails[useLightJob=true](com.hazelcast.jet.core.ExecutionLifecycleTest): BuildInfo{version='5.1-SNAPSHOT', build='20210924', buildNumber=20210924, revision=352db4a, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'when_psGetThrows_then_jobFails[useLightJob=true](com.hazelcast.jet.core.ExecutionLifecycleTest):'
10:54:45, accumulated pauses: 106 ms, max pause: 100 ms, pauses over 1000 ms: 0


No metrics recorded during the test
```

**Comment by frant-hartm** [comment]
Jet tests using MockPMS/MockPS/MockP may fail due to threads executing on the fork-join pool. Sometimes we execute cleanup after an instance is terminated and another test already started - we basically have tests running in parallel despite using `HazelcastSerialClassRunner`.

I know these 2 issues are caused by this:
#19627
#19326

The fix is tracked in Jira: HZ-658 (Don't use FJP), HZ-542 (Define executor shutdown behaviour)

**Comment by srknzl** [comment]
also in https://github.com/hazelcast/hazelcast/pull/21838#issuecomment-1204451963

**Comment by AyberkSorgun** [comment]
Last failure older than Nov 1st, closing for now
