### ISSUE TITLE
com.hazelcast.client.console.HazelcastCommandLineTest.test_submit_job_with_hazelcast_classes

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#19636]
_master_ (commit 886628968ce05e1cd9073f9147b0f7e0c080a48f)

Failed on Windows with OracleJDK8: http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Windows-OracleJDK8/325/testReport/com.hazelcast.client.console/HazelcastCommandLineTest/test_submit_job_with_hazelcast_classes/

It fails also on `5.0.z` branch, please backport the fix also into that branch.

Stacktrace:
```
java.lang.AssertionError: 

Expecting:
 <"WARNING: Hazelcast code detected in the jar: com\hazelcast\jet\testjob\HazelcastBootstrap.class. Hazelcast dependency should be set with the 'provided' scope or equivalent.
">
to contain:
 <"WARNING: Hazelcast code detected in the jar: com/hazelcast/jet/testjob/HazelcastBootstrap.class. Hazelcast dependency should be set with the 'provided' scope or equivalent."> 
	at com.hazelcast.client.console.HazelcastCommandLineTest.test_submit_job_with_hazelcast_classes(HazelcastCommandLineTest.java:516)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by ufukyilmaz** [comment]
Fixed by #19640
