### ISSUE TITLE
com.hazelcast.internal.ascii.RestClusterMultiendpointTest [HZ-755]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#19634]
_5.0.z_ (commit c27a594c4b8835e0e05abb84587ad72fc37011c0)

Failed on Correto JDK 8: http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-CorrettoJDK8/1/testReport/com.hazelcast.internal.ascii/RestClusterMultiendpointTest/testChangeClusterVersion/

Stacktrace:
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:280)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:153)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:254)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
	at com.hazelcast.internal.ascii.HTTPCommunicator.doPost(HTTPCommunicator.java:501)
	at com.hazelcast.internal.ascii.HTTPCommunicator.changeClusterVersion(HTTPCommunicator.java:298)
	at com.hazelcast.internal.ascii.RestClusterTest.testChangeClusterVersion(RestClusterTest.java:185)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

Standard output:
```
05:10:43,320  INFO |testChangeClusterVersion| - [LifecycleService] Thread-38353 - [127.0.0.1]:5219 [testChangeClusterVersion] [5.0.1-SNAPSHOT] [127.0.0.1]:5219 is SHUTTING_DOWN
05:10:43,321  WARN |testChangeClusterVersion| - [Node] Thread-38353 - [127.0.0.1]:5219 [testChangeClusterVersion] [5.0.1-SNAPSHOT] Terminating forcefully...
05:10:43,321  INFO |testChangeClusterVersion| - [TextCommandServiceImpl] Thread-38353 - [127.0.0.1]:5219 [testChangeClusterVersion] [5.0.1-SNAPSHOT] Stopping text command service...
05:10:43,321  INFO |testChangeClusterVersion| - [Node] Thread-38353 - [127.0.0.1]:5219 [testChangeClusterVersion] [5.0.1-SNAPSHOT] Shutting down connection manager...
05:10:43,322  INFO |testChangeClusterVersion| - [Node] Thread-38353 - [127.0.0.1]:5219 [testChangeClusterVersion] [5.0.1-SNAPSHOT] Shutting down node engine...
05:10:43,326  INFO |testChangeClusterVersion| - [NodeExtension] Thread-38353 - [127.0.0.1]:5219 [testChangeClusterVersion] [5.0.1-SNAPSHOT] Destroying node NodeExtension.
05:10:43,326  INFO |testChangeClusterVersion| - [Node] Thread-38353 - [127.0.0.1]:5219 [testChangeClusterVersion] [5.0.1-SNAPSHOT] Hazelcast Shutdown is completed in 5 ms.
05:10:43,326  INFO |testChangeClusterVersion| - [LifecycleService] Thread-38353 - [127.0.0.1]:5219 [testChangeClusterVersion] [5.0.1-SNAPSHOT] [127.0.0.1]:5219 is SHUTDOWN
```

**Comment by olukas** [comment]
`com.hazelcast.internal.ascii.RestClusterMultiendpointTest.testHeadRequest_ClusterInfo` failed on Zulu JDK 11 on `master` also with `TestTimedOutException`: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZuluJDK11/158/testReport/com.hazelcast.internal.ascii/RestClusterMultiendpointTest/testHeadRequest_ClusterInfo/ 

Since the cause can be the same I'm putting it into this issue and change milestone to `5.1`.

Stacktrace:
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.base@11.0.13/java.net.SocketInputStream.socketRead0(Native Method)
	at java.base@11.0.13/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
	at java.base@11.0.13/java.net.SocketInputStream.read(SocketInputStream.java:168)
	at java.base@11.0.13/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at app//org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
	at app//org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
	at app//org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:280)
	at app//org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140)
	at app//org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
	at app//org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
	at app//org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
	at app//org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:153)
	at app//org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
	at app//org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
	at app//org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:254)
	at app//org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
	at app//org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
	at app//org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
	at app//org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at app//org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at app//org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
	at app//com.hazelcast.internal.ascii.HTTPCommunicator.doHead(HTTPCommunicator.java:455)
	at app//com.hazelcast.internal.ascii.HTTPCommunicator.headRequestToClusterInfoURI(HTTPCommunicator.java:580)
	at app//com.hazelcast.internal.ascii.RestClusterTest.testHeadRequest_ClusterInfo(RestClusterTest.java:322)
	at java.base@11.0.13/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@11.0.13/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base@11.0.13/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@11.0.13/java.lang.reflect.Method.invoke(Method.java:566)
	at app//org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at app//org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at app//org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at app//org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at app//com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at app//com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base@11.0.13/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base@11.0.13/java.lang.Thread.run(Thread.java:829)
```

Standard output:
```
Finished Running Test: testClusterShutdown in 5.172 seconds.
23:04:29,467  INFO |testHeadRequest_ClusterInfo| - [LifecycleService] Thread-41989 - [127.0.0.1]:5185 [testHeadRequest_ClusterInfo] [5.1-SNAPSHOT] [127.0.0.1]:5185 is SHUTTING_DOWN
23:04:29,467  WARN |testHeadRequest_ClusterInfo| - [Node] Thread-41989 - [127.0.0.1]:5185 [testHeadRequest_ClusterInfo] [5.1-SNAPSHOT] Terminating forcefully...
23:04:29,467  INFO |testHeadRequest_ClusterInfo| - [TextCommandServiceImpl] Thread-41989 - [127.0.0.1]:5185 [testHeadRequest_ClusterInfo] [5.1-SNAPSHOT] Stopping text command service...
23:04:29,467  INFO |testHeadRequest_ClusterInfo| - [Node] Thread-41989 - [127.0.0.1]:5185 [testHeadRequest_ClusterInfo] [5.1-SNAPSHOT] Shutting down connection manager...
23:04:29,468  INFO |testHeadRequest_ClusterInfo| - [Node] Thread-41989 - [127.0.0.1]:5185 [testHeadRequest_ClusterInfo] [5.1-SNAPSHOT] Shutting down node engine...
23:04:29,469  INFO |testHeadRequest_ClusterInfo| - [RetryExec] testHeadRequest_ClusterInfo - I/O exception (java.net.SocketException) caught when processing request to {}->http://127.0.0.1:5703: Connection reset
23:04:29,470  INFO |testHeadRequest_ClusterInfo| - [RetryExec] testHeadRequest_ClusterInfo - Retrying request to {}->http://127.0.0.1:5703
23:04:29,470  INFO |testHeadRequest_ClusterInfo| - [NodeExtension] Thread-41989 - [127.0.0.1]:5185 [testHeadRequest_ClusterInfo] [5.1-SNAPSHOT] Destroying node NodeExtension.
23:04:29,470  INFO |testHeadRequest_ClusterInfo| - [Node] Thread-41989 - [127.0.0.1]:5185 [testHeadRequest_ClusterInfo] [5.1-SNAPSHOT] Hazelcast Shutdown is completed in 3 ms.
23:04:29,470  INFO |testHeadRequest_ClusterInfo| - [LifecycleService] Thread-41989 - [127.0.0.1]:5185 [testHeadRequest_ClusterInfo] [5.1-SNAPSHOT] [127.0.0.1]:5185 is SHUTDOWN
```

**Comment by kwart** [comment]
One suspect is the `TextEncoder` class. It's not thread-safe and it's obviously accessed from multiple threads:

**hz.xenodochial_ganguly.IO.thread-out-0**
```
        at com.hazelcast.internal.nio.ascii.TextEncoder.onWrite(TextEncoder.java:89) [classes/:?]
        at com.hazelcast.internal.networking.nio.NioOutboundPipeline.process(NioOutboundPipeline.java:312) [classes/:?]
        at com.hazelcast.internal.networking.nio.NioPipeline.run(NioPipeline.java:230) [classes/:?]
        at com.hazelcast.internal.networking.nio.NioThread.processTaskQueue(NioThread.java:355) [classes/:?]
        at com.hazelcast.internal.networking.nio.NioThread.selectLoop(NioThread.java:290) [classes/:?]
        at com.hazelcast.internal.networking.nio.NioThread.executeRun(NioThread.java:249) [classes/:?]
        at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) [classes/:?]
```

**hz.xenodochial_ganguly.ascii.service.response**
```
        at com.hazelcast.internal.nio.ascii.TextEncoder.onWrite(TextEncoder.java:89) [classes/:?]
        at com.hazelcast.internal.networking.nio.NioOutboundPipeline.process(NioOutboundPipeline.java:312) [classes/:?]
        at com.hazelcast.internal.networking.nio.NioOutboundPipeline.executePipeline(NioOutboundPipeline.java:240) [classes/:?]
        at com.hazelcast.internal.networking.nio.NioOutboundPipeline.write(NioOutboundPipeline.java:218) [classes/:?]
        at com.hazelcast.internal.networking.nio.NioChannel.write(NioChannel.java:79) [classes/:?]
        at com.hazelcast.internal.server.tcp.TcpServerConnection.write(TcpServerConnection.java:197) [classes/:?]
        at com.hazelcast.internal.nio.ascii.TextEncoder.enqueue(TextEncoder.java:63) [classes/:?]
        at com.hazelcast.internal.ascii.TextCommandServiceImpl$ResponseThreadRunnable.run(TextCommandServiceImpl.java:429) [classes/:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
```

**Comment by degerhz** [comment]
The last failure was almost a year old. Closing the issues.
