### ISSUE TITLE
Intermittent failure on MapUsingService(PythonTransforms)

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast#19661]
Using 5.0 GA, I see this sometimes

```
com.hazelcast.core.HazelcastException: JobClassLoaders for jobId=06e0-7fc1-1400-0003 requested, but it does not exists
	at com.hazelcast.jet.impl.JobClassLoaderService.getProcessorClassLoader(JobClassLoaderService.java:187)
	at com.hazelcast.jet.impl.execution.init.ExecutionPlan.initProcSuppliers(ExecutionPlan.java:333)
	at com.hazelcast.jet.impl.execution.init.ExecutionPlan.initialize(ExecutionPlan.java:173)
	at com.hazelcast.jet.impl.execution.ExecutionContext.initialize(ExecutionContext.java:161)
	at com.hazelcast.jet.impl.JobExecutionService.lambda$initExecution$6(JobExecutionService.java:296)
	at com.hazelcast.jet.impl.util.Util.doWithClassLoader(Util.java:531)
	at com.hazelcast.jet.impl.JobExecutionService.initExecution(JobExecutionService.java:296)
	at com.hazelcast.jet.impl.operation.InitExecutionOperation.doRun(InitExecutionOperation.java:97)
	at com.hazelcast.jet.impl.operation.AsyncOperation.run(AsyncOperation.java:54)
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:189)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:272)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:248)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:469)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:197)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:137)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
```

However, only sometimes, so the job config is in general correct

**Comment by frant-hartm** [comment]
@neilstevenson shared the following at the time:

```
08:25:59.883 [hz.objective_murdock.cached.thread-9] WARN  com.hazelcast.jet.impl.execution.ExecutionContext - [10.172.3.32]:5701 [green] [5.0] Failed to delete temporary directory /tmp/jet-objective_murdock-06e1-b293-8100-0003-_tmp_randomforest_predict47028289921342862899694780

08:26:07.841 [hz.objective_murdock.generic-operation.thread-1] WARN  com.hazelcast.jet.impl.processor.ProcessorSupplierWithService - [10.172.3.32]:5701 [green] [5.0] [RandomForestValidation@2@1632990127932@2021-09-30T08:22:07.932/randomforest_predict#PS] PythonService context creation failed, will retry
 com.hazelcast.jet.JetException: PythonService initialization failed: java.lang.Exception: Initialization script finished with non-zero exit code: 1
        at com.hazelcast.jet.python.PythonServiceContext.<init>(PythonServiceContext.java:110) ~[hazelcast-jet-python-5.0.jar!/:?]
        at com.hazelcast.jet.python.PythonService.createContextWithRetry(PythonService.java:110) ~[hazelcast-jet-python-5.0.jar!/:?]
        at com.hazelcast.jet.python.PythonService.lambda$factory$9a0f8f23$1(PythonService.java:90) ~[hazelcast-jet-python-5.0.jar!/:?]
        at com.hazelcast.function.FunctionEx.apply(FunctionEx.java:48) ~[hazelcast-enterprise-5.0.jar!/:5.0]
        at com.hazelcast.jet.impl.processor.ProcessorSupplierWithService.init(ProcessorSupplierWithService.java:59) ~[hazelcast-enterprise-5.0.jar!/:5.0]
        at com.hazelcast.jet.impl.execution.init.ExecutionPlan.lambda$initProcSuppliers$bf6409b6$1(ExecutionPlan.java:338) ~[hazelcast-enterprise-5.0.jar!/:5.0]
        at com.hazelcast.jet.function.RunnableEx.run(RunnableEx.java:31) ~[hazelcast-enterprise-5.0.jar!/:5.0]
        at com.hazelcast.jet.impl.util.Util.doWithClassLoader(Util.java:516) ~[hazelcast-enterprise-5.0.jar!/:5.0]
        at com.hazelcast.jet.impl.execution.init.ExecutionPlan.initProcSuppliers(ExecutionPlan.java:337) ~[hazelcast-enterprise-5.0.jar!/:5.0]
        at com.hazelcast.jet.impl.execution.init.ExecutionPlan.initialize(ExecutionPlan.java:173) ~[hazelcast-enterprise-5.0.jar!/:5.0]
        at com.hazelcast.jet.impl.execution.ExecutionContext.initialize(ExecutionContext.java:161) ~[hazelcast-enterprise-5.0.jar!/:5.0]
        at com.hazelcast.jet.impl.JobExecutionService.lambda$initExecution$6(JobExecutionService.java:296) ~[hazelcast-enterprise-5.0.jar!/:5.0]
        at com.hazelcast.jet.impl.util.Util.doWithClassLoader(Util.java:531) [hazelcast-enterprise-5.0.jar!/:5.0]
        at com.hazelcast.jet.impl.JobExecutionService.initExecution(JobExecutionService.java:296) [hazelcast-enterprise-5.0.jar!/:5.0]
        at com.hazelcast.jet.impl.operation.InitExecutionOperation.doRun(InitExecutionOperation.java:97) [hazelcast-enterprise-5.0.jar!/:5.0]
        at com.hazelcast.jet.impl.operation.AsyncOperation.run(AsyncOperation.java:54) [hazelcast-enterprise-5.0.jar!/:5.0]
        at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:189) [hazelcast-enterprise-5.0.jar!/:5.0]
        at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:272) [hazelcast-enterprise-5.0.jar!/:5.0]
        at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:248) [hazelcast-enterprise-5.0.jar!/:5.0]
        at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:469) [hazelcast-enterprise-5.0.jar!/:5.0]
        at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:197) [hazelcast-enterprise-5.0.jar!/:5.0]
        at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:137) [hazelcast-enterprise-5.0.jar!/:5.0]
        at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123) [hazelcast-enterprise-5.0.jar!/:5.0]
        at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) [hazelcast-enterprise-5.0.jar!/:5.0]
Caused by: java.lang.Exception: Initialization script finished with non-zero exit code: 1
        at com.hazelcast.jet.python.PythonServiceContext.<init>(PythonServiceContext.java:101) ~[hazelcast-jet-python-5.0.jar!/:?]
        ... 23 more
```
and
```
Downloads/turquoise-green-hazelcast-1.log:08:26:33.483 [hz.objective_murdock.generic-operation.thread-1] INFO  com.hazelcast.jet.impl.processor.ProcessorSupplierWithService - [10.172.3.32]:5701 [green] [5.0] [RandomForestValidation@2@1632990127932@2021-09-30T08:22:07.932/randomforest_predict#PS] Initialization script took 24,633 ms
Downloads/turquoise-green-hazelcast-1.log:08:26:33.485 [hz.objective_murdock.generic-operation.thread-1] ERROR com.hazelcast.jet.impl.operation.InitExecutionOperation - [10.172.3.32]:5701 [green] [5.0] JobClassLoaders for jobId=06e1-b293-8100-0003 requested, but it does not exists
```
However, it wasn't possible to run it with TRACE logging.

This is probably not strictly related to python, but to an exception in job initialization. Moving to Backlog until we have a reliable reproducer.
