### ISSUE TITLE
Hazelcast hangs in REPLICA_NOT_SYNC state [HZ-1013]

### ISSUE THREAD

**Issue by dreis2211** [hazelcast/hazelcast#19672]
**Describe the bug**
Unfortunately, I don't have too much information I can share and also no reproduction case. We're experiencing problems with our Hazelcast nodes that seem to hang in `REPLICA_NOT_SYNC` state and even get unresponsive as it seems. Especially when starting the cluster we notice this. We're doing health checks each second that try to call `IPartitionService.isMemberStateSafe`. When we remove that from that from the health check our cluster seems to be fine after startup.

**Expected behavior**
Member state recovers to SAFE eventually and application does not hang.

**To Reproduce**
Unfortunately, no reproduction available. Calling `IPartitionService.isMemberStateSafe` concurrently might be a way.

**Additional context**
Hazelcast 4.1.5
JDK 11.0.12
Linux
Cluster size: 2
Application is not under load when this happens.
Might be related to https://github.com/hazelcast/hazelcast/issues/18778#issuecomment-86761475

**Excerpt of thread dump**
```
"ForkJoinPool.commonPool-worker-5" #114 daemon prio=5 os_prio=0 cpu=924.45ms elapsed=4695.40s tid=0x00007f3cb8203800 nid=0x1d0b waiting on condition  [0x00007f3c9a0d7000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@11.0.12/Native Method)
	- parking to wait for  <0x00000007f170f5c8> (a java.util.concurrent.Semaphore$NonfairSync)
	at java.util.concurrent.locks.LockSupport.parkNanos(java.base@11.0.12/LockSupport.java:234)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(java.base@11.0.12/AbstractQueuedSynchronizer.java:1079)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(java.base@11.0.12/AbstractQueuedSynchronizer.java:1369)
	at java.util.concurrent.Semaphore.tryAcquire(java.base@11.0.12/Semaphore.java:592)
	at com.hazelcast.internal.partition.impl.PartitionReplicaStateChecker.checkAndTriggerReplicaSync(PartitionReplicaStateChecker.java:238)
	at com.hazelcast.internal.partition.impl.PartitionReplicaStateChecker.getPartitionServiceState(PartitionReplicaStateChecker.java:107)
	at com.hazelcast.internal.partition.impl.InternalPartitionServiceImpl.isMemberStateSafe(InternalPartitionServiceImpl.java:1107)


"ForkJoinPool.commonPool-worker-7" #120 daemon prio=5 os_prio=0 cpu=940.15ms elapsed=4695.04s tid=0x00007f3cf800b000 nid=0x1d11 waiting on condition  [0x00007f3c9a5dc000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@11.0.12/Native Method)
	- parking to wait for  <0x00000007f21c61c0> (a java.util.concurrent.Semaphore$NonfairSync)
	at java.util.concurrent.locks.LockSupport.parkNanos(java.base@11.0.12/LockSupport.java:234)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(java.base@11.0.12/AbstractQueuedSynchronizer.java:1079)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(java.base@11.0.12/AbstractQueuedSynchronizer.java:1369)
	at java.util.concurrent.Semaphore.tryAcquire(java.base@11.0.12/Semaphore.java:592)
	at com.hazelcast.internal.partition.impl.PartitionReplicaStateChecker.checkAndTriggerReplicaSync(PartitionReplicaStateChecker.java:238)
	at com.hazelcast.internal.partition.impl.PartitionReplicaStateChecker.getPartitionServiceState(PartitionReplicaStateChecker.java:107)
	at com.hazelcast.internal.partition.impl.InternalPartitionServiceImpl.isMemberStateSafe(InternalPartitionServiceImpl.java:1107)
```

**Comment by vbekiaris** [comment]
One way for the issue to manifest:
- `isClusterSafe` is executed on `FJP#commonPool` (probably initiated over JMX via `PartitionServiceMBean`?)
- `checkAndTriggerReplicaSync` waits to acquire semaphore permits
- semaphore permits are released from `ReplicaSyncResponseCallback` that should be executed after `PartitionBackupReplicaAntiEntropyOperation` (call path https://github.com/hazelcast/hazelcast/blob/14ef0dbefa4a6fa00a50a8873aeea02ec6c3f5e4/hazelcast/src/main/java/com/hazelcast/internal/partition/impl/CheckPartitionReplicaVersionTask.java#L63)
- however callback execution uses `whenCompleteAsync(BiConsumer)` -> fails to execute because all `FJP#commonPool` threads are busy waiting for semaphore permits -> deadlock.
