### ISSUE TITLE
com.hazelcast.sql.HazelcastSqlException: property 'com.hazelcast.org.apache.calcite.sql.validate.SqlValidator$Config#TypeCoercionRules' is required and has no default value 

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#19699]
http://jenkins.hazelcast.com/view/stable/job/trial-1/67/console

fail HzClient3HZ rangeHDIdx hzcmd.map.sql.service.PersonIdRange threadId=1 com.hazelcast.sql.HazelcastSqlException: property 'com.hazelcast.org.apache.calcite.sql.validate.SqlValidator$Config#TypeCoercionRules' is required and has no default value 

/disk1/workspace/trial-1/2021_10_04-07_11_48

```
com.hazelcast.sql.HazelcastSqlException: property 'com.hazelcast.org.apache.calcite.sql.validate.SqlValidator$Config#TypeCoercionRules' is required and has no default value
	at com.hazelcast.sql.impl.QueryUtils.toPublicException(QueryUtils.java:74)
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:211)
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:162)
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:158)
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:154)
	at hzcmd.map.sql.service.PersonIdRange.timeStep(PersonIdRange.java:16)
	at remote.bench.marker.RollMarker.flatOut(RollMarker.java:72)
	at remote.bench.marker.RollMarker.bench(RollMarker.java:59)
	at remote.bench.BenchThread.call(BenchThread.java:41)
	at remote.bench.BenchThread.call(BenchThread.java:14)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IllegalArgumentException: property 'com.hazelcast.org.apache.calcite.sql.validate.SqlValidator$Config#TypeCoercionRules' is required and has no default value
	at com.hazelcast.org.apache.calcite.util.ImmutableBeans.lambda$makeDef$0(ImmutableBeans.java:168)
	at com.hazelcast.org.apache.calcite.util.ImmutableBeans$BeanImpl.invoke(ImmutableBeans.java:480)
	at com.sun.proxy.$Proxy17.typeCoercionRules(Unknown Source)
	at com.hazelcast.org.apache.calcite.sql.validate.SqlValidatorImpl.<init>(SqlValidatorImpl.java:311)
	at com.hazelcast.org.apache.calcite.sql.validate.SqlValidatorImplBridge.<init>(SqlValidatorImplBridge.java:35)
	at com.hazelcast.jet.sql.impl.validate.HazelcastSqlValidator.<init>(HazelcastSqlValidator.java:114)
	at com.hazelcast.jet.sql.impl.OptimizerContext.create(OptimizerContext.java:115)
	at com.hazelcast.jet.sql.impl.OptimizerContext.create(OptimizerContext.java:102)
	at com.hazelcast.jet.sql.impl.CalciteSqlOptimizer.prepare(CalciteSqlOptimizer.java:210)
	at com.hazelcast.sql.impl.SqlServiceImpl.prepare(SqlServiceImpl.java:261)
	at com.hazelcast.sql.impl.SqlServiceImpl.query0(SqlServiceImpl.java:241)
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:198)
	... 14 more
```

**Comment by gierlachg** [comment]
Seems #19701 will fix it
