### ISSUE TITLE
ReflectiveCompactSerializer unable to serialize null LocalDate

### ISSUE THREAD

**Issue by lukasherman** [hazelcast/hazelcast#19712]
`ReflectiveCompactSerializer` fails with NPE at `IOUtil.writeLocalDate` serializing object with null `LocalDate` field.

Stack trace:
```
Caused by: java.lang.NullPointerException
	at com.hazelcast.internal.nio.IOUtil.writeLocalDate(IOUtil.java:175)
	at com.hazelcast.internal.serialization.impl.compact.DefaultCompactWriter.writeDate(DefaultCompactWriter.java:290)
	at com.hazelcast.internal.serialization.impl.compact.ReflectiveCompactSerializer.lambda$createFastReadWriteCaches$25(ReflectiveCompactSerializer.java:275)
	at com.hazelcast.internal.serialization.impl.compact.ReflectiveCompactSerializer.writeFast(ReflectiveCompactSerializer.java:109)
	at com.hazelcast.internal.serialization.impl.compact.ReflectiveCompactSerializer.write(ReflectiveCompactSerializer.java:95)
	at com.hazelcast.internal.serialization.impl.compact.CompactStreamSerializer.writeObject(CompactStreamSerializer.java:173)
````

**Expected behavior**
It is expected that object is serialized with null `LocalDate` value. Some other date/timestamp types are affected too.

**To Reproduce**
Simple unit test:
```
public class TestObject {
    LocalDate localDate;

    public LocalDate getLocalDate() {
        return localDate;
    }

    public void setLocalDate(LocalDate localDate) {
        this.localDate = localDate;
    }
}
----
@Test
public void testSerialize() {
    TestObject testObject = new TestObject();
    hazelcastInstance.getMap("testMap").set("id", testObject);
}
```

**Additional context**
Hazelcast version 5.0

**Comment by TomaszGaweda** [comment]
Hi, it was fixed in commit https://github.com/hazelcast/hazelcast/commit/51859ec7b136c42d35f1973610cc200ca384a424

@sancar Can you please take a look and close this issue if I'm correct?

**Comment by sancar** [comment]
@TomaszGaweda You are right. It is fixed by https://github.com/hazelcast/hazelcast/pull/19619
