### ISSUE TITLE
Double metric collection when starting a both members within a second

### ISSUE THREAD

**Issue by NZ-Jaybird** [hazelcast/hazelcast#19767]
**Describe the bug**
Double metric collection error reported when starting both members within a second. It occurs because there are two distinct connections in TcpServerConnectionManager that resolve to the same remote address, presumably because the two members accept each others connections.

**Expected behavior**
If the two nodes are allowed to connect to each other when starting up within a second, I would expect it not to report an error.

**To Reproduce**

1. Start two hazelcast nodes at the same time

**Additional context**
```
java.lang.AssertionError: metric '[endpoint=[localhost]:3000,unit=enum,metric=tcp.connection.connectionType,excludedTargets={}]' was rendered twice. Present value: 1, new value: 1
        at com.hazelcast.internal.metrics.jmx.JmxPublisher.assertDoubleRendering(JmxPublisher.java:123)
        at com.hazelcast.internal.metrics.jmx.JmxPublisher.publishNumber(JmxPublisher.java:110)
        at com.hazelcast.internal.metrics.jmx.JmxPublisher.publishLong(JmxPublisher.java:87)
        at com.hazelcast.internal.metrics.impl.PublisherMetricsCollector.collectLong(PublisherMetricsCollector.java:62)
        at com.hazelcast.internal.metrics.impl.MetricsCollectionCycle.collectLong(MetricsCollectionCycle.java:168)
        at com.hazelcast.internal.metrics.impl.MetricsCollectionCycle.collect(MetricsCollectionCycle.java:145)
        at com.hazelcast.internal.metrics.impl.MetricsCollectionCycle.extractAndCollectDynamicMetrics(MetricsCollectionCycle.java:119)
        at com.hazelcast.internal.metrics.impl.MetricsCollectionCycle.access$200(MetricsCollectionCycle.java:45)
        at com.hazelcast.internal.metrics.impl.MetricsCollectionCycle$MetricsContext.collect(MetricsCollectionCycle.java:181)
        at com.hazelcast.internal.server.tcp.TcpServerConnectionManager.provideDynamicMetrics(TcpServerConnectionManager.java:313)
        at com.hazelcast.internal.server.tcp.TcpServer$MetricsProvider.provideDynamicMetrics(TcpServer.java:341)
        at com.hazelcast.internal.metrics.impl.MetricsCollectionCycle.collectDynamicMetrics(MetricsCollectionCycle.java:88)
        at com.hazelcast.internal.metrics.impl.MetricsRegistryImpl.collect(MetricsRegistryImpl.java:316)
        at com.hazelcast.internal.metrics.impl.MetricsService.collectMetrics(MetricsService.java:160)
        at com.hazelcast.internal.metrics.impl.MetricsService.collectMetrics(MetricsService.java:154)
        at com.hazelcast.spi.impl.executionservice.impl.DelegateAndSkipOnConcurrentExecutionDecorator$DelegateDecorator.run(DelegateAndSkipOnConcurrentExecutionDecorator.java:77)
        at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
        at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
        at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
```

- Hazelcast 5.0
- Cluster size, two members
- Version of Java. 8
- Operating system. Fedora 34

**Comment by mmedenjak** [comment]
Thank you for the report! @ufukyilmaz can you take a look?

**Comment by AyberkSorgun** [comment]
@ufukyilmaz does your fix handle this issue?

**Comment by ufukyilmaz** [comment]
No, my 5.2 changes won't fix this issue. The root cause of this issue is that https://github.com/hazelcast/hazelcast/issues/18877.

Actually in my 5.1 task, I was trying to fix this duplicate connection issue (note that this issue has no major harm.) by setting an order among these concurrently initiated connections and then close the second connection with respect to that defined ordering. But closing the connection that started to be used, caused problems such as packet loss and packet reordering. 
I had to somehow block the connections to started to be used until making sure it won't be closed later/there will no connection ahead of this connection (wrt. that defined ordering) will be opened after that point. But, I couldn't manage to do it.
This packet loss/ordering was causing critical problems. E.g. when one of the migration operation packets was lost, it was leaving the cluster in the unsafe state for a long time (since timeout of this migration op. is very long). So, I avoided the change.
