### ISSUE TITLE
Hazelcast CLI starts a MySQL cleaner thread

### ISSUE THREAD

**Issue by jerrinot** [hazelcast/hazelcast#19777]
Hazelcast 5.0 CLI console starts a mysql cleaner thread for some reason:

```
$ jps|grep CommandLine
77801 HazelcastCommandLine

$ jstack 77801|grep -A 4 mysql  
"mysql-cj-abandoned-connection-cleanup" #11 daemon prio=5 os_prio=0 tid=0x00007fbc40540000 nid=0x13000 in Object.wait() [0x00007fbc1c96f000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144)
	- locked <0x00000003d644a9a0> (a java.lang.ref.ReferenceQueue$Lock)
	at com.mysql.cj.jdbc.AbandonedConnectionCleanupThread.run(AbandonedConnectionCleanupThread.java:85)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Holmistr** [comment]
Moving to backlog. We'll consider it during the next release planning.
