### ISSUE TITLE
com.hazelcast.client.executor.ClientExecutorServiceTest.testSubmitFailingCallableException_withExecutionCallback [API-1397]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#19784]
_master_ (commit c7d5d4ed0150e9e927af1541e2e0da730df401f5)

Failed on Sonar build (Oracle JDK 11): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/1008/testReport/com.hazelcast.client.executor/ClientExecutorServiceTest/testSubmitFailingCallableException_withExecutionCallback/

<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at com.hazelcast.client.executor.ClientExecutorServiceTest.testSubmitFailingCallableException_withExecutionCallback(ClientExecutorServiceTest.java:230)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

</details>

<details><summary>Standard output:</summary>

```
23:03:35,367  INFO |testSubmitFailingCallableException_withExecutionCallback| - [PartitionStateManager] Thread-17316 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Storing snapshot of partition assignments while removing UUID 23c89fa7-2af9-4f4a-ab8f-08ff638af0fa
23:03:35,368  INFO |testSubmitFailingCallableException_withExecutionCallback| - [ClusterService] Thread-17316 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] 

Members {size:1, ver:7} [
	Member [127.0.0.1]:5701 - d1ca9bcd-65de-4e03-a6a8-cce9ce1c948c this
]

23:03:35,368  INFO |testSubmitFailingCallableException_withExecutionCallback| - [TransactionManagerService] hz.angry_ardinghelli.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Committing/rolling-back live transactions of [127.0.0.1]:5704, UUID: 23c89fa7-2af9-4f4a-ab8f-08ff638af0fa
23:03:35,368  INFO |testSubmitFailingCallableException_withExecutionCallback| - [Node] Thread-17316 - [127.0.0.1]:5704 [dev] [5.1-SNAPSHOT] Shutting down node engine...
23:03:35,369  WARN |testSubmitFailingCallableException_withExecutionCallback| - [MigrationManager] hz.angry_ardinghelli.migration - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Cannot commit promotions. Destination [127.0.0.1]:5704 - 23c89fa7-2af9-4f4a-ab8f-08ff638af0fa is not a member anymore
23:03:35,370  INFO |testSubmitFailingCallableException_withExecutionCallback| - [NodeExtension] Thread-17316 - [127.0.0.1]:5704 [dev] [5.1-SNAPSHOT] Destroying node NodeExtension.
23:03:35,370  INFO |testSubmitFailingCallableException_withExecutionCallback| - [Node] Thread-17316 - [127.0.0.1]:5704 [dev] [5.1-SNAPSHOT] Hazelcast Shutdown is completed in 58 ms.
23:03:35,370  INFO |testSubmitFailingCallableException_withExecutionCallback| - [LifecycleService] Thread-17316 - [127.0.0.1]:5704 [dev] [5.1-SNAPSHOT] [127.0.0.1]:5704 is SHUTDOWN
23:03:35,370  INFO |testSubmitFailingCallableException_withExecutionCallback| - [LifecycleService] Thread-17316 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
23:03:35,370  WARN |testSubmitFailingCallableException_withExecutionCallback| - [Node] Thread-17316 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Terminating forcefully...
23:03:35,370  INFO |testSubmitFailingCallableException_withExecutionCallback| - [Node] Thread-17316 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Shutting down connection manager...
23:03:35,371  INFO |testSubmitFailingCallableException_withExecutionCallback| - [Node] Thread-17316 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Shutting down node engine...
23:03:35,384  WARN |testSubmitFailingCallableException_withExecutionCallback| - [MigrationManager] hz.angry_ardinghelli.migration - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Cannot commit promotions. Destination [127.0.0.1]:5702 - 879404ce-aeb6-4ef1-8555-c3ceff90ebac is not a member anymore
23:03:35,409  INFO |testSubmitFailingCallableException_withExecutionCallback| - [NodeExtension] Thread-17316 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Destroying node NodeExtension.
23:03:35,409  INFO |testSubmitFailingCallableException_withExecutionCallback| - [Node] Thread-17316 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Hazelcast Shutdown is completed in 39 ms.
23:03:35,409  INFO |testSubmitFailingCallableException_withExecutionCallback| - [LifecycleService] Thread-17316 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
23:03:35,410  WARN |testFutureAfterCancellationAwareTaskTimeOut| - [MigrationManager] hz.youthful_ardinghelli.migration - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Cannot commit promotions. Destination [127.0.0.1]:5702 - e7bc6f8a-0aba-4a7a-9b4b-8c4506badfeb is not a member anymore
```

</details>

**Comment by olukas** [comment]
It happened again on Sonar build (Oracle JDK 11): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/1043/testReport/com.hazelcast.client.executor/ClientExecutorServiceTest/testSubmitFailingCallableException_withExecutionCallback/

**Comment by olukas** [comment]
Failed again on Sonar build: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/1088/testReport/com.hazelcast.client.executor/ClientExecutorServiceTest/testSubmitFailingCallableException_withExecutionCallback/

**Comment by olukas** [comment]
Failed again on Sonar build: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/1090/testReport/com.hazelcast.client.executor/ClientExecutorServiceTest/testSubmitFailingCallableException_withExecutionCallback/

**Comment by olukas** [comment]
Failed again on Sonar build (Oracle JDK 11): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/1157/testReport/com.hazelcast.client.executor/ClientExecutorServiceTest/testSubmitFailingCallableException_withExecutionCallback/

**Comment by olukas** [comment]
Failed on `5.1.z` branch on Sonar build (Oracle JDK 11): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-sonar/176/testReport/com.hazelcast.client.executor/ClientExecutorServiceTest/testSubmitFailingCallableException_withExecutionCallback/

**Comment by olukas** [comment]
Failed on `master` on Sonar build (Oracle JDK 11): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/1193/testReport/com.hazelcast.client.executor/ClientExecutorServiceTest/testSubmitFailingCallableException_withExecutionCallback/

**Comment by olukas** [comment]
Failed on `master` on Sonar build (Oracle JDK 11): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/1207/testReport/com.hazelcast.client.executor/ClientExecutorServiceTest/testSubmitFailingCallableException_withExecutionCallback/
