### ISSUE TITLE
SnapshotPhase2Operation exception on 5.0.1-SNAPSHOT

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast#19840]
Using Hazelcast Platform 5.0.1-SNAPSHOT (20211022 - aafdf51)

I get
```
16:31:08.499 WARN  hz.naughty_cartwright.cached.thread-6 c.h.jet.impl.MasterSnapshotContext - [10.172.3.5]:5701 [grid] [5.0.1-SNAPSHOT] SnapshotPhase2Operation for snapshot 28 in job 'SlackSQLJob', execution 06fe-73a2-78c8-0001 failed on member: MemberInfo{address=[10.172.0.5]:5701, uuid=54de9756-8659-402c-b745-b8e628b2535d, liteMember=false, memberListJoinVersion=2}=com.hazelcast.jet.impl.exception.ExecutionNotFoundException: job 06fe-73a2-78c4-0001, execution 06fe-73a2-78c8-0001 not found for coordinator [10.172.3.5]:5701 for 'SnapshotPhase2Operation' 
com.hazelcast.jet.impl.exception.ExecutionNotFoundException: job 06fe-73a2-78c4-0001, execution 06fe-73a2-78c8-0001 not found for coordinator [10.172.3.5]:5701 for 'SnapshotPhase2Operation'
	at com.hazelcast.jet.impl.JobExecutionService.assertExecutionContext(JobExecutionService.java:441)
	at com.hazelcast.jet.impl.operation.SnapshotPhase2Operation.doRun(SnapshotPhase2Operation.java:54)
	at com.hazelcast.jet.impl.operation.AsyncOperation.run(AsyncOperation.java:54)
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:189)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:272)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:248)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:469)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:197)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:137)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
```

I have a (huge!) reproducer project. DM me for details

**Comment by neilstevenson** [comment]
On `Hazelcast Platform 5.1-SNAPSHOT (20211202 - c03d61a)` still occurring, every 10 seconds

Master node
```
08:54:57.409 WARN  hz.jolly_joliot.cached.thread-10 c.h.jet.impl.MasterSnapshotContext - [10.172.3.11]:5701 [grid] [5.1-SNAPSHOT] SnapshotPhase2Operation for snapshot 75 in job 'SlackSQLJob', execution 0734-1c31-d9c8-0001 failed on member: MemberInfo{address=[10.172.2.9]:5701, uuid=52a01b32-3faf-4535-ab91-9773357e472c, liteMember=false, memberListJoinVersion=2}=com.hazelcast.jet.impl.exception.ExecutionNotFoundException: job 0734-1c31-d9c4-0001, execution 0734-1c31-d9c8-0001 not found for coordinator [10.172.3.11]:5701 for 'SnapshotPhase2Operation' 
com.hazelcast.jet.impl.exception.ExecutionNotFoundException: job 0734-1c31-d9c4-0001, execution 0734-1c31-d9c8-0001 not found for coordinator [10.172.3.11]:5701 for 'SnapshotPhase2Operation'
	at com.hazelcast.jet.impl.JobExecutionService.assertExecutionContext(JobExecutionService.java:495)
	at com.hazelcast.jet.impl.operation.SnapshotPhase2Operation.doRun(SnapshotPhase2Operation.java:54)
	at com.hazelcast.jet.impl.operation.AsyncOperation.run(AsyncOperation.java:54)
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:189)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:272)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:248)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:469)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:197)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:137)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
```

The other node, 2 node cluster, also mentions SnapshotPhase1Operation

```
08:54:47.400 WARN  hz.jolly_joliot.cached.thread-6 c.h.jet.impl.MasterSnapshotContext - [10.172.3.11]:5701 [grid] [5.1-SNAPSHOT] SnapshotPhase2Operation for snapshot 74 in job 'SlackSQLJob', execution 0734-1c31-d9c8-0001 failed on member: MemberInfo{address=[10.172.2.9]:5701, uuid=52a01b32-3faf-4535-ab91-9773357e472c, liteMember=false, memberListJoinVersion=2}=com.hazelcast.jet.impl.exception.ExecutionNotFoundException: job 0734-1c31-d9c4-0001, execution 0734-1c31-d9c8-0001 not found for coordinator [10.172.3.11]:5701 for 'SnapshotPhase2Operation' 
com.hazelcast.jet.impl.exception.ExecutionNotFoundException: job 0734-1c31-d9c4-0001, execution 0734-1c31-d9c8-0001 not found for coordinator [10.172.3.11]:5701 for 'SnapshotPhase2Operation'
	at com.hazelcast.jet.impl.JobExecutionService.assertExecutionContext(JobExecutionService.java:495)
	at com.hazelcast.jet.impl.operation.SnapshotPhase2Operation.doRun(SnapshotPhase2Operation.java:54)
	at com.hazelcast.jet.impl.operation.AsyncOperation.run(AsyncOperation.java:54)
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:189)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:272)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:248)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:469)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:197)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:137)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
08:54:57.409 WARN  hz.jolly_joliot.cached.thread-10 c.h.jet.impl.MasterSnapshotContext - [10.172.3.11]:5701 [grid] [5.1-SNAPSHOT] SnapshotPhase2Operation for snapshot 75 in job 'SlackSQLJob', execution 0734-1c31-d9c8-0001 failed on member: MemberInfo{address=[10.172.2.9]:5701, uuid=52a01b32-3faf-4535-ab91-9773357e472c, liteMember=false, memberListJoinVersion=2}=com.hazelcast.jet.impl.exception.ExecutionNotFoundException: job 0734-1c31-d9c4-0001, execution 0734-1c31-d9c8-0001 not found for coordinator [10.172.3.11]:5701 for 'SnapshotPhase2Operation' 
com.hazelcast.jet.impl.exception.ExecutionNotFoundException: job 0734-1c31-d9c4-0001, execution 0734-1c31-d9c8-0001 not found for coordinator [10.172.3.11]:5701 for 'SnapshotPhase2Operation'
	at com.hazelcast.jet.impl.JobExecutionService.assertExecutionContext(JobExecutionService.java:495)
	at com.hazelcast.jet.impl.operation.SnapshotPhase2Operation.doRun(SnapshotPhase2Operation.java:54)
	at com.hazelcast.jet.impl.operation.AsyncOperation.run(AsyncOperation.java:54)
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:189)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:272)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:248)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:469)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:197)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:137)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
```

**Comment by neilstevenson** [comment]
Also, this only seems to be originating from 1 job of the 4 running in the cluster, `SlackSQLJob`

**Comment by viliam-durina** [comment]
Is 10 seconds your snapshot interval? It guess it happens when the job completes on that member - it has only non-distributed source and no distributed edge. I guess we should move this logging to FINE level.

**Comment by neilstevenson** [comment]
I haven't configured snapshot interval, so it'll be defaulting.
It's this job https://github.com/hazelcast/hazelcast-platform-demos/blob/master/utils/slack/src/main/java/com/hazelcast/platform/demos/utils/UtilsSlackSQLJob.java

**Comment by viliam-durina** [comment]
@Holmistr Yes, it's just logging level. 10 secs is the default snapshot interval. In one of the 4 jobs there's probably a non-distributed source and no distributed edge, so the execution completes immediately on all but 1 member. And it's logged on the `MaseterSnapshotContext`, that means only on the master member.
