### ISSUE TITLE
com.hazelcast.nio.IOUtilTest.testTouch_failsWhenLastModifiedCannotBeSet [HZ-667]

### ISSUE THREAD

**Issue by slavagithub** [hazelcast/hazelcast#19875]
Master (rev. e817a03)

Failed on Zulu, JDK17: http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZuluJDK17/5/testReport/

<details><summary>Stacktrace:</summary>

```
java.lang.Exception: Unexpected exception, expected<com.hazelcast.core.HazelcastException> but was<java.lang.NullPointerException>
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:30)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NullPointerException: Cannot invoke "String.indexOf(int)" because "this.path" is null
	at java.base/java.io.File.isInvalid(File.java:187)
	at java.base/java.io.File.setLastModified(File.java:1499)
	at com.hazelcast.nio.IOUtilTest.testTouch_failsWhenLastModifiedCannotBeSet(IOUtilTest.java:402)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)
```

</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: testDeleteQuietly in 0.002 seconds.
BuildInfo right after testTouch_failsWhenLastModifiedCannotBeSet(com.hazelcast.nio.IOUtilTest): BuildInfo{version='5.1-SNAPSHOT', build='20211029', buildNumber=20211029, revision=3ddd37c, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'testTouch_failsWhenLastModifiedCannotBeSet(com.hazelcast.nio.IOUtilTest):'
11:52:20, accumulated pauses: 1138 ms, max pause: 1021 ms, pauses over 1000 ms: 1


No metrics recorded during the test
```

</details>

**Comment by Holmistr** [comment]
Should be fixed by https://github.com/hazelcast/hazelcast/pull/19921
