### ISSUE TITLE
com.hazelcast.internal.nearcache.impl.preloader.NearCachePreloaderLockTest [HZ-669]

### ISSUE THREAD

**Issue by slavagithub** [hazelcast/hazelcast#19873]
Master (rev. e817a03)

Failed on Zulu, JDK17: http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZuluJDK17/5/testReport/

<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: 

Expected: (an instance of com.hazelcast.core.HazelcastException and exception with message a string containing "File is already being used by another Hazelcast instance.")
     but: an instance of com.hazelcast.core.HazelcastException <org.junit.internal.runners.model.MultipleFailureException: There were 2 errors:
  java.lang.NullPointerException(Cannot enter synchronized block because "this.closeLock" is null)
  java.lang.NullPointerException(Cannot enter synchronized block because "this.closeLock" is null)> is a org.junit.internal.runners.model.MultipleFailureException
Stacktrace was: java.lang.NullPointerException: Cannot enter synchronized block because "this.closeLock" is null
	at java.base/java.nio.channels.spi.AbstractInterruptibleChannel.close(AbstractInterruptibleChannel.java:108)
	at com.hazelcast.internal.nio.IOUtil.closeResource(IOUtil.java:396)
	at com.hazelcast.internal.nearcache.impl.preloader.NearCachePreloaderLock.acquireLock(NearCachePreloaderLock.java:85)
	at com.hazelcast.internal.nearcache.impl.preloader.NearCachePreloaderLockTest.testAcquireLock_whenTryLockReturnsNull_thenThrowHazelcastException(NearCachePreloaderLockTest.java:89)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)
java.lang.NullPointerException: Cannot enter synchronized block because "this.closeLock" is null
	at java.base/java.nio.channels.spi.AbstractInterruptibleChannel.close(AbstractInterruptibleChannel.java:108)
	at com.hazelcast.internal.nio.IOUtil.closeResource(IOUtil.java:396)
	at com.hazelcast.internal.nearcache.impl.preloader.NearCachePreloaderLockTest.tearDown(NearCachePreloaderLockTest.java:70)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:381)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:258)
	at com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37)
	at com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:104)
	at com.hazelcast.test.metrics.MetricsRule$1.evaluate(MetricsRule.java:62)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at com.hazelcast.test.HazelcastParallelClassRunner.access$301(HazelcastParallelClassRunner.java:49)
	at com.hazelcast.test.HazelcastParallelClassRunner$TestRunner.run(HazelcastParallelClassRunner.java:162)
	at java.base/java.lang.Thread.run(Thread.java:833)

	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:964)
	at org.junit.Assert.assertThat(Assert.java:930)
	at org.junit.rules.ExpectedException.handleException(ExpectedException.java:271)
	at org.junit.rules.ExpectedException.access$000(ExpectedException.java:111)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:260)
	at com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37)
	at com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:104)
	at com.hazelcast.test.metrics.MetricsRule$1.evaluate(MetricsRule.java:62)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at com.hazelcast.test.HazelcastParallelClassRunner.access$301(HazelcastParallelClassRunner.java:49)
	at com.hazelcast.test.HazelcastParallelClassRunner$TestRunner.run(HazelcastParallelClassRunner.java:162)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

</details>

<details><summary>Standard output:</summary>

```
Started Running Test: testRelease
Started Running Test: testAcquireLock_whenTryLockReturnsNull_thenThrowHazelcastException
Started Running Test: testAcquireLock_whenTryLockThrowsIOException_thenThrowHazelcastException
BuildInfo right after testRelease(com.hazelcast.internal.nearcache.impl.preloader.NearCachePreloaderLockTest): BuildInfo{version='5.1-SNAPSHOT', build='20211029', buildNumber=20211029, revision=3ddd37c, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'testRelease(com.hazelcast.internal.nearcache.impl.preloader.NearCachePreloaderLockTest):'
11:57:25, accumulated pauses: 8 ms, max pause: 0 ms, pauses over 1000 ms: 0


No metrics recorded during the test
Finished Running Test: testRelease in 0.041 seconds.
BuildInfo right after testAcquireLock_whenTryLockThrowsOverlappingFileLockException_thenThrowHazelcastException(com.hazelcast.internal.nearcache.impl.preloader.NearCachePreloaderLockTest): BuildInfo{version='5.1-SNAPSHOT', build='20211029', buildNumber=20211029, revision=3ddd37c, enterprise=false, serializationVersion=1}
BuildInfo right after testAcquireLock_whenTryLockThrowsIOException_thenThrowHazelcastException(com.hazelcast.internal.nearcache.impl.preloader.NearCachePreloaderLockTest): BuildInfo{version='5.1-SNAPSHOT', build='20211029', buildNumber=20211029, revision=3ddd37c, enterprise=false, serializationVersion=1}
BuildInfo right after testAcquireLock_whenTryLockReturnsNull_thenThrowHazelcastException(com.hazelcast.internal.nearcache.impl.preloader.NearCachePreloaderLockTest): BuildInfo{version='5.1-SNAPSHOT', build='20211029', buildNumber=20211029, revision=3ddd37c, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'testAcquireLock_whenTryLockThrowsOverlappingFileLockException_thenThrowHazelcastException(com.hazelcast.internal.nearcache.impl.preloader.NearCachePreloaderLockTest):'
11:57:25, accumulated pauses: 8 ms, max pause: 0 ms, pauses over 1000 ms: 0

Hiccups measured while running test 'testAcquireLock_whenTryLockThrowsIOException_thenThrowHazelcastException(com.hazelcast.internal.nearcache.impl.preloader.NearCachePreloaderLockTest):'
11:57:25, accumulated pauses: 8 ms, max pause: 0 ms, pauses over 1000 ms: 0


No metrics recorded during the test
Hiccups measured while running test 'testAcquireLock_whenTryLockReturnsNull_thenThrowHazelcastException(com.hazelcast.internal.nearcache.impl.preloader.NearCachePreloaderLockTest):'
11:57:25, accumulated pauses: 8 ms, max pause: 0 ms, pauses over 1000 ms: 0


No metrics recorded during the test

No metrics recorded during the test
Finished Running Test: testAcquireLock_whenTryLockThrowsIOException_thenThrowHazelcastException in 0.044 seconds.
Finished Running Test: testAcquireLock_whenTryLockThrowsOverlappingFileLockException_thenThrowHazelcastException in 0.045 seconds.
Finished Running Test: testAcquireLock_whenTryLockReturnsNull_thenThrowHazelcastException in 0.044 seconds.
Started Running Test: no_repairing_handler_created_when_invalidations_disabled
Started Running Test: repairing_handler_created_when_invalidations_enabled
```

</details>

**Comment by ldziedziul** [comment]
Fixed with https://github.com/hazelcast/hazelcast/pull/20295
