### ISSUE TITLE
com.hazelcast.jet.sql_slow.JetSqlSlowIndexTest

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#19884]
_5.0.z_ (commit dce2abb3485d5ccd7658b69d0b5a952031f741bf)

Failed on Sonar build (Oracle JDK 11): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-sonar/40/testReport/com.hazelcast.jet.sql_slow/JetSqlSlowIndexTest/com_hazelcast_jet_sql_slow_JetSqlSlowIndexTest/

<details><summary>Stacktrace:</summary>

```
java.lang.IllegalStateException: Instances haven't been shut down: [HazelcastInstance{name='tender_almeida', node=[127.0.0.1]:5733}]
	at com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:46)
	at com.hazelcast.test.OverridePropertyRule$1.evaluate(OverridePropertyRule.java:66)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: test[indexType:HASH, composite:false, field1:Character, field2:Character] in 1.393 seconds.
02:29:25,232  INFO || - [SimpleTestInClusterSupport] Time-limited test - Terminating instance factory in SimpleTestInClusterSupport.@AfterClass
02:29:25,232  INFO || - [LifecycleService] Thread-1648 - [127.0.0.1]:5702 [dev] [5.0.1-SNAPSHOT] [127.0.0.1]:5702 is SHUTTING_DOWN
02:29:25,232  WARN || - [Node] Thread-1648 - [127.0.0.1]:5702 [dev] [5.0.1-SNAPSHOT] Terminating forcefully...
02:29:25,232  INFO || - [Node] Thread-1648 - [127.0.0.1]:5702 [dev] [5.0.1-SNAPSHOT] Shutting down connection manager...
02:29:25,233  INFO || - [MockServer] Thread-1648 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5702, connection: MockConnection{localEndpoint=[127.0.0.1]:5701, remoteEndpoint=[127.0.0.1]:5702, alive=false}
02:29:25,233  INFO || - [MockServer] Thread-1648 - [127.0.0.1]:5702 [dev] [5.0.1-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5701, connection: MockConnection{localEndpoint=[127.0.0.1]:5702, remoteEndpoint=[127.0.0.1]:5701, alive=false}
02:29:25,233  INFO || - [MembershipManager] Thread-1648 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Removing Member [127.0.0.1]:5702 - 711b3499-4d96-4f37-b152-701d535319fa
02:29:25,233  INFO || - [PartitionStateManager] Thread-1648 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Storing snapshot of partition assignments while removing UUID 711b3499-4d96-4f37-b152-701d535319fa
02:29:25,233  INFO || - [ClusterService] Thread-1648 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] 

Members {size:1, ver:3} [
	Member [127.0.0.1]:5701 - bc0998e9-eb17-4a3d-a6ea-5288b6073185 this
]

02:29:25,233  INFO |test[indexType:SORTED, composite:true, field1:Byte, field2:Long]| - [TransactionManagerService] hz.sad_almeida.cached.thread-13 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Committing/rolling-back live transactions of [127.0.0.1]:5702, UUID: 711b3499-4d96-4f37-b152-701d535319fa
02:29:25,233  INFO || - [Node] Thread-1648 - [127.0.0.1]:5702 [dev] [5.0.1-SNAPSHOT] Shutting down node engine...
02:29:25,235  INFO || - [MigrationManager] hz.sad_almeida.migration - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Partition balance is ok, no need to repartition.
02:29:25,237  INFO || - [NodeExtension] Thread-1648 - [127.0.0.1]:5702 [dev] [5.0.1-SNAPSHOT] Destroying node NodeExtension.
02:29:25,237  INFO || - [Node] Thread-1648 - [127.0.0.1]:5702 [dev] [5.0.1-SNAPSHOT] Hazelcast Shutdown is completed in 5 ms.
02:29:25,237  INFO || - [LifecycleService] Thread-1648 - [127.0.0.1]:5702 [dev] [5.0.1-SNAPSHOT] [127.0.0.1]:5702 is SHUTDOWN
02:29:25,237  INFO || - [LifecycleService] Thread-1648 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
02:29:25,237  WARN || - [Node] Thread-1648 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Terminating forcefully...
02:29:25,237  INFO || - [Node] Thread-1648 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Shutting down connection manager...
02:29:25,237  INFO || - [Node] Thread-1648 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Shutting down node engine...
02:29:25,238 DEBUG |stressTest_sorted| - [JobCoordinationService] hz.tender_almeida.cached.thread-17 - [127.0.0.1]:5733 [dev] [5.0.1-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:29:25,239  INFO || - [NodeExtension] Thread-1648 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Destroying node NodeExtension.
02:29:25,239  INFO || - [Node] Thread-1648 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Hazelcast Shutdown is completed in 2 ms.
02:29:25,239  INFO || - [LifecycleService] Thread-1648 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
02:29:25,241  INFO || - [LifecycleService] Time-limited test - [127.0.0.1]:5733 [dev] [5.0.1-SNAPSHOT] [127.0.0.1]:5733 is SHUTTING_DOWN
02:29:25,241 DEBUG || - [JobCoordinationService] Time-limited test - [127.0.0.1]:5733 [dev] [5.0.1-SNAPSHOT] Added a shutting-down member: 22e3ecc4-1220-44b5-9c5f-3d1e03404bb4
02:29:25,241  INFO || - [Node] Time-limited test - [127.0.0.1]:5733 [dev] [5.0.1-SNAPSHOT] Shutting down connection manager...
02:29:25,241  INFO || - [Node] Time-limited test - [127.0.0.1]:5733 [dev] [5.0.1-SNAPSHOT] Shutting down node engine...
02:29:28,243  INFO || - [NodeExtension] Time-limited test - [127.0.0.1]:5733 [dev] [5.0.1-SNAPSHOT] Destroying node NodeExtension.
02:29:28,243  INFO || - [Node] Time-limited test - [127.0.0.1]:5733 [dev] [5.0.1-SNAPSHOT] Hazelcast Shutdown is completed in 3002 ms.
02:29:28,243  INFO || - [LifecycleService] Time-limited test - [127.0.0.1]:5733 [dev] [5.0.1-SNAPSHOT] [127.0.0.1]:5733 is SHUTDOWN
```

</details>

**Comment by slavagithub** [comment]
The same for IBM JDK 8 fips for tests:
- com.hazelcast.jet.sql_slow.SqlSlowIndexTest.com.hazelcast.jet.sql_slow.SqlSlowIndexTest
- com.hazelcast.jet.sql_slow.SqlOrderBySlowTest.com.hazelcast.jet.sql_slow.SqlOrderBySlowTest
- com.hazelcast.jet.sql_slow.SqlBasicSlowTest.com.hazelcast.jet.sql_slow.SqlBasicSlowTest
- com.hazelcast.jet.sql_slow.SqlBasicClientSlowTest.com.hazelcast.jet.sql_slow.SqlBasicClientSlowTest
- com.hazelcast.jet.sql_slow.MapScanMigrationStressTest.com.hazelcast.jet.sql_slow.MapScanMigrationStressTest
- com.hazelcast.jet.sql_slow.ComparisonPredicateIntegrationSlowTest.com.hazelcast.jet.sql_slow.ComparisonPredicateIntegrationSlowTest
See http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-IbmJDK8-fips-nightly/361/testReport/

**Comment by slavagithub** [comment]
The same for master on sonar - http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/1067/testReport/
