### ISSUE TITLE
QueueStatisticsTest.testAge[comparatorClassName= null]

### ISSUE THREAD

**Issue by srknzl** [hazelcast/hazelcast#19909]
failed on https://github.com/hazelcast/hazelcast/pull/19892

srknzl:compactable-api-doc-fix (commit https://github.com/hazelcast/hazelcast/pull/19892/commits/d94bd9dcf90f859de5cb9c3f581acc5314b9ce29 )

Failed on Hazelcast-pr-builder: http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/8174/testReport/com.hazelcast.collection.impl.queue/QueueStatisticsTest/testAge_comparatorClassName__null_/

<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: expected:<4611686018427387903> but was:<0>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at com.hazelcast.collection.impl.queue.QueueStatisticsTest.testAge(QueueStatisticsTest.java:170)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: testPollOperationCount[comparatorClassName: null] in 0.021 seconds.
Started Running Test: testAge[comparatorClassName: null]
07:53:34,611  INFO |testAge[comparatorClassName: null]| - [MetricsConfigHelper] testAge - [LOCAL] [dev] [5.1-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
07:53:34,612  INFO |testAge[comparatorClassName: null]| - [logo] testAge - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
07:53:34,612  INFO |testAge[comparatorClassName: null]| - [system] testAge - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Copyright (c) 2008-2021, Hazelcast, Inc. All Rights Reserved.
07:53:34,612  INFO |testAge[comparatorClassName: null]| - [system] testAge - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Hazelcast Platform 5.1-SNAPSHOT (20211108 - 14a5e83) starting at [127.0.0.1]:5701
07:53:34,612  INFO |testAge[comparatorClassName: null]| - [system] testAge - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Cluster name: dev
07:53:34,619  INFO |testAge[comparatorClassName: null]| - [MetricsConfigHelper] testAge - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
07:53:34,625  WARN |testAge[comparatorClassName: null]| - [CPSubsystem] testAge - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
07:53:34,629  INFO |testAge[comparatorClassName: null]| - [JetServiceBackend] testAge - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Setting number of cooperative threads and default parallelism to 2
07:53:34,631  INFO |testAge[comparatorClassName: null]| - [Diagnostics] testAge - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
07:53:34,631  INFO |testAge[comparatorClassName: null]| - [LifecycleService] testAge - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] [127.0.0.1]:5701 is STARTING
07:53:34,632  INFO |testAge[comparatorClassName: null]| - [JetExtension] testAge - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Jet is enabled
07:53:34,632  INFO |testAge[comparatorClassName: null]| - [ClusterService] testAge - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] 

Members {size:1, ver:1} [
	Member [127.0.0.1]:5701 - 5447e850-e150-42b1-acf3-c38775db4388 this
]

07:53:34,632 DEBUG |testAge[comparatorClassName: null]| - [JobCoordinationService] hz.gracious_nobel.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
07:53:34,632  INFO |testAge[comparatorClassName: null]| - [LifecycleService] testAge - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] [127.0.0.1]:5701 is STARTED
07:53:34,632  INFO |testAge[comparatorClassName: null]| - [PartitionStateManager] testAge - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Initializing cluster partition table arrangement...
07:53:34,883 DEBUG |testAge[comparatorClassName: null]| - [JobRepository] hz.gracious_nobel.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Job cleanup took 0ms
07:53:34,885  INFO |testAge[comparatorClassName: null]| - [HealthMonitor] hz.gracious_nobel.HealthMonitor - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] processors=16, physical.memory.total=755.6G, physical.memory.free=596.8G, swap.space.total=4.0G, swap.space.free=4.0G, heap.memory.used=613.7M, heap.memory.free=814.3M, heap.memory.total=1.4G, heap.memory.max=1.8G, heap.memory.used/total=42.94%, heap.memory.used/max=33.68%, minor.gc.count=242, minor.gc.time=6783ms, major.gc.count=4, major.gc.time=754ms, load.process=2.63%, load.system=100.00%, load.systemAverage=25.57, thread.count=69, thread.peakCount=1848, cluster.timeDiff=0, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=4, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=1, clientEndpoint.count=0, connection.active.count=0, client.connection.count=0, connection.count=0
07:53:34,889  INFO |testAge[comparatorClassName: null]| - [LifecycleService] Thread-6648 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
07:53:34,889  WARN |testAge[comparatorClassName: null]| - [Node] Thread-6648 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Terminating forcefully...
07:53:34,889  INFO |testAge[comparatorClassName: null]| - [Node] Thread-6648 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Shutting down connection manager...
07:53:34,889  INFO |testAge[comparatorClassName: null]| - [Node] Thread-6648 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Shutting down node engine...
07:53:34,892  INFO |testAge[comparatorClassName: null]| - [NodeExtension] Thread-6648 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Destroying node NodeExtension.
07:53:34,892  INFO |testAge[comparatorClassName: null]| - [Node] Thread-6648 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Hazelcast Shutdown is completed in 3 ms.
07:53:34,893  INFO |testAge[comparatorClassName: null]| - [LifecycleService] Thread-6648 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
BuildInfo right after testAge[comparatorClassName: null](com.hazelcast.collection.impl.queue.QueueStatisticsTest): BuildInfo{version='5.1-SNAPSHOT', build='20211108', buildNumber=20211108, revision=14a5e83, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'testAge[comparatorClassName: null](com.hazelcast.collection.impl.queue.QueueStatisticsTest):'
07:53:30, accumulated pauses: 354 ms, max pause: 249 ms, pauses over 1000 ms: 0


No metrics recorded during the test
```

</details>

**Comment by mmedenjak** [comment]
Potentially related: https://github.com/hazelcast/hazelcast/issues/19911
