### ISSUE TITLE
QueueStatisticsTest.testAge[comparatorClassName=  com.hazelcast.collection.impl.queue.model.VersionedObjectComparator]

### ISSUE THREAD

**Issue by srknzl** [hazelcast/hazelcast#19911]
srknzl:compactable-api-doc-fix (commit https://github.com/hazelcast/hazelcast/pull/19892/commits/8a2808efc81365019e1ac92a9580ff35ae560637)

Failed on Hazelcast pr builder: https://jenkins.hazelcast.com/job/Hazelcast-pr-builder/8181/testReport/junit/com.hazelcast.collection.impl.queue/QueueStatisticsTest/testAge_comparatorClassName__com_hazelcast_collection_impl_queue_model_VersionedObjectComparator_/

<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: expected:<4611686018427387903> but was:<0>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at com.hazelcast.collection.impl.queue.QueueStatisticsTest.testAge(QueueStatisticsTest.java:170)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: testEventOperationCount[comparatorClassName: com.hazelcast.collection.impl.queue.model.VersionedObjectComparator] in 0.014 seconds.

No metrics recorded during the test
```

</details>

**Comment by mmedenjak** [comment]
Potentially related: https://github.com/hazelcast/hazelcast/issues/19909
