### ISSUE TITLE
Partial map name reporting when querying unmapped IMap

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast#19912]
Using `Hazelcast Platform 5.0.1-SNAPSHOT (20211105 - 74bf4d8)`

If I run this SQL
```
SELECT * FROM hello.world
```
and the mapping doesn't exist, the reported error doesn't quote the full map name

```
com.hazelcast.sql.HazelcastSqlException: Object 'hello' not found, did you forget to CREATE MAPPING?
	at com.hazelcast.sql.impl.client.SqlClientService.handleExecuteResponse(SqlClientService.java:131)
	at com.hazelcast.sql.impl.client.SqlClientService.execute(SqlClientService.java:105)
	at com.hazelcast.sql.SqlService.execute(SqlService.java:89)
	at hazelcast.platform.demos.industry.iiot.ApplicationRunner.initialize3(ApplicationRunner.java:157)
	at hazelcast.platform.demos.industry.iiot.ApplicationRunner.lambda$commandLineRunner$0(ApplicationRunner.java:78)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:791)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:775)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:345)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332)
	at hazelcast.platform.demos.industry.iiot.Application.main(Application.java:30)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
```

**Comment by viliam-durina** [comment]
It's the same issue as in #19915. The `.` has special meaning in SQL (in this case to separate object and schema names). Schema name is also just an object that you can create, therefore the error says "object 'hello' not found".

To interpred the `.` literally, enclose the table name in `"`:
```sql
SELECT * FROM "hello.world"
```
