### ISSUE TITLE
StreamEventJournalP NPE in DataCodec.encode

### ISSUE THREAD

**Issue by lukasherman** [hazelcast/hazelcast#19920]
**Describe the bug**
Client application streaming data from remote cluster via StreamEventJournalP throws exception on evict event.

**Expected behavior**
It is expected that evict event is streamed to client application.

**To Reproduce**
Set up Jet client application to stream data from remote cluster. Configure eviction on remote map. Place item to remote map and observe that item is processed, eventually exception is thrown on item eviction.

**Stack trace**
```
Caused by: java.lang.NullPointerException: null
	at com.hazelcast.client.impl.protocol.codec.builtin.DataCodec.encode(DataCodec.java:32) ~[hazelcast-5.0.jar:5.0]
	at com.hazelcast.client.impl.protocol.codec.builtin.ListMultiFrameCodec.encode(ListMultiFrameCodec.java:42) ~[hazelcast-5.0.jar:5.0]
	at com.hazelcast.client.impl.protocol.codec.MapEventJournalReadCodec.encodeResponse(MapEventJournalReadCodec.java:159) ~[hazelcast-5.0.jar:5.0]
	at com.hazelcast.client.impl.protocol.task.map.MapEventJournalReadTask.encodeResponse(MapEventJournalReadTask.java:88) ~[hazelcast-5.0.jar:5.0]
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.sendResponse(AbstractMessageTask.java:243) ~[hazelcast-5.0.jar:5.0]
	at com.hazelcast.client.impl.protocol.task.AbstractAsyncMessageTask.sendResponseOrHandleFailure(AbstractAsyncMessageTask.java:79) ~[hazelcast-5.0.jar:5.0]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[na:na]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[na:na]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[na:na]
	at com.hazelcast.internal.util.ConcurrencyUtil$1.execute(ConcurrencyUtil.java:39) ~[hazelcast-5.0.jar:5.0]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568) ~[na:na]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:850) ~[na:na]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[na:na]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[na:na]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073) ~[na:na]
	at com.hazelcast.spi.impl.AbstractInvocationFuture$ApplyNode.lambda$execute$0(AbstractInvocationFuture.java:1484) ~[hazelcast-5.0.jar:5.0]
	at com.hazelcast.internal.util.ConcurrencyUtil$1.execute(ConcurrencyUtil.java:39) ~[hazelcast-5.0.jar:5.0]
	at com.hazelcast.spi.impl.AbstractInvocationFuture$ApplyNode.execute(AbstractInvocationFuture.java:1482) ~[hazelcast-5.0.jar:5.0]
	at com.hazelcast.spi.impl.AbstractInvocationFuture.unblockOtherNode(AbstractInvocationFuture.java:797) ~[hazelcast-5.0.jar:5.0]
	at com.hazelcast.spi.impl.AbstractInvocationFuture.unblockAll(AbstractInvocationFuture.java:759) ~[hazelcast-5.0.jar:5.0]
	at com.hazelcast.spi.impl.AbstractInvocationFuture.unblockAll(AbstractInvocationFuture.java:756) ~[hazelcast-5.0.jar:5.0]
	at com.hazelcast.spi.impl.AbstractInvocationFuture.complete0(AbstractInvocationFuture.java:1235) ~[hazelcast-5.0.jar:5.0]
	at com.hazelcast.spi.impl.AbstractInvocationFuture.complete(AbstractInvocationFuture.java:1219) ~[hazelcast-5.0.jar:5.0]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.complete(Invocation.java:672) ~[hazelcast-5.0.jar:5.0]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.sendResponse(Invocation.java:235) ~[hazelcast-5.0.jar:5.0]
	at com.hazelcast.spi.impl.operationservice.Operation.sendResponse(Operation.java:475) ~[hazelcast-5.0.jar:5.0]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:282) ~[hazelcast-5.0.jar:5.0]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:248) ~[hazelcast-5.0.jar:5.0]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:213) ~[hazelcast-5.0.jar:5.0]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:411) ~[hazelcast-5.0.jar:5.0]
	at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.run(OperationServiceImpl.java:308) ~[hazelcast-5.0.jar:5.0]
	at com.hazelcast.spi.impl.operationparker.impl.WaitSet.unpark(WaitSet.java:107) ~[hazelcast-5.0.jar:5.0]
	at com.hazelcast.spi.impl.operationparker.impl.OperationParkerImpl.unpark(OperationParkerImpl.java:110) ~[hazelcast-5.0.jar:5.0]
	at com.hazelcast.map.impl.journal.RingbufferMapEventJournalImpl.addToEventRingbuffer(RingbufferMapEventJournalImpl.java:185) ~[hazelcast-5.0.jar:5.0]
	at com.hazelcast.map.impl.journal.RingbufferMapEventJournalImpl.writeEvictEvent(RingbufferMapEventJournalImpl.java:84) ~[hazelcast-5.0.jar:5.0]
	at com.hazelcast.map.impl.recordstore.EventJournalWriterMutationObserver.onEvictRecord(EventJournalWriterMutationObserver.java:66) ~[hazelcast-5.0.jar:5.0]
	at com.hazelcast.map.impl.recordstore.CompositeMutationObserver.onEvictRecord(CompositeMutationObserver.java:171) ~[hazelcast-5.0.jar:5.0]
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.evict(DefaultRecordStore.java:524) ~[hazelcast-5.0.jar:5.0]
	at com.hazelcast.map.impl.recordstore.AbstractEvictableRecordStore.evictExpiredEntryAndPublishExpiryEvent(AbstractEvictableRecordStore.java:127) ~[hazelcast-5.0.jar:5.0]
	at com.hazelcast.map.impl.recordstore.expiry.ExpirySystem.evictExpiredKeys(ExpirySystem.java:402) ~[hazelcast-5.0.jar:5.0]
	at com.hazelcast.map.impl.recordstore.expiry.ExpirySystem.evictExpiredEntries(ExpirySystem.java:325) ~[hazelcast-5.0.jar:5.0]
	at com.hazelcast.map.impl.recordstore.AbstractEvictableRecordStore.evictExpiredEntries(AbstractEvictableRecordStore.java:77) ~[hazelcast-5.0.jar:5.0]
	at com.hazelcast.map.impl.operation.MapClearExpiredOperation.run(MapClearExpiredOperation.java:68) ~[hazelcast-5.0.jar:5.0]
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:189) ~[hazelcast-5.0.jar:5.0]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:272) ~[hazelcast-5.0.jar:5.0]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:248) ~[hazelcast-5.0.jar:5.0]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:213) ~[hazelcast-5.0.jar:5.0]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:175) ~[hazelcast-5.0.jar:5.0]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:139) ~[hazelcast-5.0.jar:5.0]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123) ~[hazelcast-5.0.jar:5.0]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) ~[hazelcast-5.0.jar:5.0]
	at ------ submitted from ------.() ~[na:na]
	at com.hazelcast.internal.util.ExceptionUtil.cloneExceptionWithFixedAsyncStackTrace(ExceptionUtil.java:279) ~[hazelcast-5.0.jar:5.0]
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.returnOrThrowWithGetConventions(InvocationFuture.java:112) ~[hazelcast-5.0.jar:5.0]
	at com.hazelcast.client.impl.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:95) ~[hazelcast-5.0.jar:5.0]
	at com.hazelcast.client.impl.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:40) ~[hazelcast-5.0.jar:5.0]
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:609) ~[hazelcast-5.0.jar:5.0]
	at com.hazelcast.spi.impl.DelegatingCompletableFuture.get(DelegatingCompletableFuture.java:109) ~[hazelcast-5.0.jar:5.0]
	at customized.StreamEventJournalP.toResultSet(StreamEventJournalP.java:277) ~[classes/:na]
	at customized.StreamEventJournalP.tryGetNextResultSet(StreamEventJournalP.java:250) ~[classes/:na]
	at customized.StreamEventJournalP.complete(StreamEventJournalP.java:156) ~[classes/:na]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.complete(ProcessorTasklet.java:491) ~[hazelcast-5.0.jar:5.0]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:385) ~[hazelcast-5.0.jar:5.0]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:255) ~[hazelcast-5.0.jar:5.0]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:388) ~[hazelcast-5.0.jar:5.0]
```
**Custom changes**
` customized.StreamEventJournalP` is a clone of `StreamEventJournalP` with existing `HazelcastInstance` injected during initialization due to issues with serialized client xml. Core processor functionality is unchanged.

**Comment by lukasherman** [comment]
Closing now. There are some client parts working correctly, and some other not working at all. Will investigate locally and get back if something is wrong.

**Comment by lukasherman** [comment]
OK so the workaround for https://github.com/hazelcast/hazelcast/issues/13498 to filter out items inside projectionFn
does not work in client mode. Projection function returning null causes this issue.
