### ISSUE TITLE
Client failover doesn't work and put operation hangs when Compact serialization is used

### ISSUE THREAD

**Issue by frant-hartm** [hazelcast/hazelcast#19962]
**Describe the bug**
When compact serialization is enabled, objects are inserted to a map the failover doesn't work correctly - the operations hang indefinitely.

Enabling compact serialization itself doesn't cause the issue, the object must be serialized using the compact serializer for the operation to hang.

**Expected behavior**
The client should correctly failover.

**To Reproduce**

1. Start 2 clusters, with compact serialization enabled
2. Create failover client for the 2 clusters, with compact serialization enabled
3. Keep inserting data into a map, e.g. simple `map.put(key, compactSerializedObject);`
4. kill first cluster

**Additional context**
I get the following exception in the logs after killing the first cluster:

```
com.hazelcast.core.OperationTimeoutException: ClientInvocation{clientMessage = ClientMessage{connection=null, length=253, operation=Client.SendAllSchemas, isRetryable=false, correlationId=1214, messageType=1500, isEvent=false, isfragmented=false}, objectName = schema-service, target = random, sentConnection = null} timed out because exception occurred after client invocation timeout 120000 ms. Current time: 2021-11-18 11:53:40.384. Start time: 2021-11-18 11:51:40.225. Total elapsed time: 120159 ms. 
	at com.hazelcast.client.impl.spi.impl.ClientInvocation.notifyExceptionWithOwnedPermission(ClientInvocation.java:341) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.client.impl.spi.impl.ClientInvocation.invokeOnSelection(ClientInvocation.java:211) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.client.impl.spi.impl.ClientInvocation.retry(ClientInvocation.java:237) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.client.impl.spi.impl.ClientInvocation.run(ClientInvocation.java:218) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at ------ submitted from ------.() ~[na:na]
	at com.hazelcast.internal.util.ExceptionUtil.cloneExceptionWithFixedAsyncStackTrace(ExceptionUtil.java:279) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.spi.impl.AbstractInvocationFuture.wrapRuntimeException(AbstractInvocationFuture.java:1968) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.spi.impl.AbstractInvocationFuture.wrapOrPeel(AbstractInvocationFuture.java:1949) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.spi.impl.AbstractInvocationFuture$ExceptionalResult.wrapForJoinInternal(AbstractInvocationFuture.java:1431) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.spi.impl.AbstractInvocationFuture.resolveAndThrowForJoinInternal(AbstractInvocationFuture.java:600) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.spi.impl.AbstractInvocationFuture.joinInternal(AbstractInvocationFuture.java:584) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.client.impl.clientside.ClientSchemaService.sendAllSchemas(ClientSchemaService.java:110) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.client.impl.clientside.HazelcastClientInstanceImpl.sendStateToCluster(HazelcastClientInstanceImpl.java:867) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.initializeClientOnCluster(TcpClientConnectionManager.java:1101) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.lambda$onAuthenticated$6(TcpClientConnectionManager.java:938) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
Caused by: java.io.IOException: No connection found to cluster.
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.checkInvocationAllowed(TcpClientConnectionManager.java:552) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.client.impl.spi.impl.ClientInvocationServiceImpl.checkInvocationAllowed(ClientInvocationServiceImpl.java:294) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.client.impl.spi.impl.ClientInvocation.invokeOnSelection(ClientInvocation.java:180) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.client.impl.spi.impl.ClientInvocation.retry(ClientInvocation.java:237) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.client.impl.spi.impl.ClientInvocation.run(ClientInvocation.java:218) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	... 8 common frames omitted
```
And the following thread in the threaddump:
```
"hz.client_3.internal-10" #126 prio=5 os_prio=0 cpu=1,57ms elapsed=169,10s tid=0x00007f3c38001000 nid=0x33cf waiting on condition  [0x00007f3cc0aa2000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@11.0.11/Native Method)
	at java.util.concurrent.locks.LockSupport.park(java.base@11.0.11/LockSupport.java:323)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.manageParking(AbstractInvocationFuture.java:693)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.joinInternal(AbstractInvocationFuture.java:582)
	at com.hazelcast.client.impl.clientside.ClientSchemaService.sendAllSchemas(ClientSchemaService.java:110)
	at com.hazelcast.client.impl.clientside.HazelcastClientInstanceImpl.sendStateToCluster(HazelcastClientInstanceImpl.java:867)
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.initializeClientOnCluster(TcpClientConnectionManager.java:1101)
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.lambda$initializeClientOnCluster$7(TcpClientConnectionManager.java:1126)
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager$$Lambda$1533/0x0000000840601440.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(java.base@11.0.11/Executors.java:515)
	at java.util.concurrent.FutureTask.run(java.base@11.0.11/FutureTask.java:264)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(java.base@11.0.11/ScheduledThreadPoolExecutor.java:304)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.11/ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.11/ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(java.base@11.0.11/Thread.java:829)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)

```

**Comment by mdumandag** [comment]
This issue has been fixed with https://github.com/hazelcast/hazelcast/pull/20564

We don't allow invocations to go out of the client, while the client is not in a particular state. With the fix I shared above, the compact schema registration to the new cluster is converted to an urgent invocation, which is exempt from the client state check I mentioned. So, this invocation is now able to go out of the client and we successfully switch clusters when the compact serialization is enabled, and we have a schema to register to a new cluster.
