### ISSUE TITLE
com.hazelcast.logging.Log4jLoggerTest.logEvent_withLogLevelOff_shouldNotLog

### ISSUE THREAD

**Issue by srknzl** [hazelcast/hazelcast#19976]
srknzl:fixMemoryLeakGetDistrObject (commit 67c97dc6e6c5a73b6b7a4de25919023b02c547d7)

Failed on Hazelcast PR Builder: [INSERT_LINK_TO_JENKINS_TEST_RESULT_HERE](https://jenkins.hazelcast.com/job/Hazelcast-pr-builder/8339/testReport/junit/com.hazelcast.logging/Log4jLoggerTest/logEvent_withLogLevelOff_shouldNotLog/)

<details><summary>Stacktrace:</summary>

```
org.opentest4j.AssertionFailedError: 
[Expected 0 log events but got 1] 
Expecting:
 <1>
to be equal to:
 <0>
but was not.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at com.hazelcast.logging.Log4jTrackingAppender.assertNumberOfLoggedEvents(Log4jTrackingAppender.java:58)
	at com.hazelcast.logging.Log4jTrackingAppender.assertNoLoggedEvents(Log4jTrackingAppender.java:62)
	at com.hazelcast.logging.Log4jLoggerTest.logEvent_withLogLevelOff_shouldNotLog(Log4jLoggerTest.java:131)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: isLoggable_whenLevelOff_shouldReturnFalse in 0.003 seconds.
BuildInfo right after logEvent_withLogLevelOff_shouldNotLog(com.hazelcast.logging.Log4jLoggerTest): BuildInfo{version='5.1-SNAPSHOT', build='20211123', buildNumber=20211123, revision=a5e8499, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'logEvent_withLogLevelOff_shouldNotLog(com.hazelcast.logging.Log4jLoggerTest):'
12:44:15, accumulated pauses: 119 ms, max pause: 117 ms, pauses over 1000 ms: 0


No metrics recorded during the test

```

</details>

**Comment by slavagithub** [comment]
failed on Corretto, JDK 8 -http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-CorrettoJDK8/153/testReport/com.hazelcast.logging/Log4jLoggerTest/logEvent_withLogLevelOff_shouldNotLog/

**Comment by slavagithub** [comment]
The same for Master, Zing JDK8 - http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZingJDK8/367/testReport/junit/com.hazelcast.logging/Log4jLoggerTest/logEvent_withLogLevelOff_shouldNotLog/
