### ISSUE TITLE
com.hazelcast.jet.kinesis.KinesisFailureTest.com.hazelcast.jet.kinesis.KinesisFailureTest

### ISSUE THREAD

**Issue by slavagithub** [hazelcast/hazelcast#20025]
The same for **com.hazelcast.jet.kinesis.KinesisIntegrationTest.com.hazelcast.jet.kinesis.KinesisIntegrationTest** test

_master_5.1_ (commit 0f734dd0617deedb4b9a69598206075ff758042f)

Failed on MacOS, Zulu, JDK 8: [test failures report](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-MacOS-ZuluJDK8/15/testReport/)

<details><summary>Stacktrace:</summary>

```
java.lang.ExceptionInInitializerError
	at sun.misc.Unsafe.ensureClassInitialized(Native Method)
	at sun.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:43)
	at sun.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:156)
	at java.lang.reflect.Field.acquireFieldAccessor(Field.java:1088)
	at java.lang.reflect.Field.getFieldAccessor(Field.java:1069)
	at java.lang.reflect.Field.get(Field.java:393)
	at org.junit.runners.model.FrameworkField.get(FrameworkField.java:92)
	at org.junit.runners.model.TestClass.collectAnnotatedFieldValues(TestClass.java:249)
	at org.junit.runners.ParentRunner.classRules(ParentRunner.java:280)
	at org.junit.runners.ParentRunner.withClassRules(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.classBlock(ParentRunner.java:217)
	at com.hazelcast.test.AbstractParameterizedHazelcastClassRunner.classBlock(AbstractParameterizedHazelcastClassRunner.java:139)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:412)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:107)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:83)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
Caused by: java.lang.IllegalStateException: Previous attempts to find a Docker environment failed. Will not retry. Please see logs and check configuration
	at org.testcontainers.dockerclient.DockerClientProviderStrategy.getFirstValidStrategy(DockerClientProviderStrategy.java:109)
	at org.testcontainers.DockerClientFactory.getOrInitializeStrategy(DockerClientFactory.java:136)
	at org.testcontainers.DockerClientFactory.getTransportConfig(DockerClientFactory.java:142)
	at org.testcontainers.DockerClientFactory.getRemoteDockerUnixSocketPath(DockerClientFactory.java:152)
	at org.testcontainers.containers.localstack.LocalStackContainer.<init>(LocalStackContainer.java:96)
	at org.testcontainers.containers.localstack.LocalStackContainer.<init>(LocalStackContainer.java:82)
	at com.hazelcast.jet.kinesis.KinesisIntegrationTest.<clinit>(KinesisIntegrationTest.java:74)
	... 32 more
```

</details>

<details><summary>Standard output:</summary>

```
Started Running Test: serializable_classes_should_have_valid_serialVersionUID
```

</details>

**Comment by olukas** [comment]
It started to fail since this change - https://github.com/hazelcast/hazelcast/commit/5ddaea340b93164a06713d4a5899f1aa099db4d6#diff-27cde4725dad87fcd9546840846fdfbb4dc42b738bdf2b2dd717082374325402R60

**Comment by ufukyilmaz** [comment]
These tests are failing because there is no docker support in the test environment.

In the mentioned commit, we changed the category of `AbstractKinesisTest` from
`SlowTest` to `QuickTest` (https://github.com/hazelcast/hazelcast/commit/5ddaea340b93164a06713d4a5899f1aa099db4d6#diff-27cde4725dad87fcd9546840846fdfbb4dc42b738bdf2b2dd717082374325402L60-L61).
This causes the test to run in more different environments that some of these
are lack of docker support. It can be resolved by skipping these tests in such
environments by adding:
```    
    @BeforeClass
    public static void beforeClassCheckDocker() {
        assumeTrue(DockerClientFactory.instance().isDockerAvailable());
    }
```
 to `AbstractKinesisTest`.  We applied this skipping approach before with this pr:
  https://github.com/hazelcast/hazelcast/pull/19445.

**Comment by slavagithub** [comment]
The same on master, Windows, Oracle JDK 8 - http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Windows-OracleJDK8/353/testReport/com.hazelcast.jet.kinesis/KinesisFailureTest/com_hazelcast_jet_kinesis_KinesisFailureTest/

**Comment by olukas** [comment]
It's still failing on Windows and MacOS:
- https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Windows-OracleJDK8/361/testReport/com.hazelcast.jet.kinesis/KinesisFailureTest/com_hazelcast_jet_kinesis_KinesisFailureTest/
- https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-MacOS-ZuluJDK8/26/testReport/com.hazelcast.jet.kinesis/KinesisFailureTest/com_hazelcast_jet_kinesis_KinesisFailureTest/
