### ISSUE TITLE
com.hazelcast.internal.partition.impl.MigrationInterceptorTest.shouldInvokeInternalMigrationListenerOnSuccessfulMigration [HZ-1004]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#20050]
_master_ (commit b519cd720716d863ad3defbbaf2114d3fc0b1c36)

Failed on Openj9-16: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Openj9-16/38/testReport/com.hazelcast.internal.partition.impl/MigrationInterceptorTest/shouldInvokeInternalMigrationListenerOnSuccessfulMigration/

<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: Migration Notifications: [MigrationProgressNotification{event=START, participant=DESTINATION, migrationInfo=MigrationInfo{uuid=e1581d0b-82af-4589-ae24-239ccda46d1b, partitionId=1, source=null, sourceCurrentReplicaIndex=-1, sourceNewReplicaIndex=-1, destination=[127.0.0.1]:5702 - 9735bb8b-cbc0-4b8d-8881-61cd31ea1dba, destinationCurrentReplicaIndex=-1, destinationNewReplicaIndex=1, master=[127.0.0.1]:5701, initialPartitionVersion=1, partitionVersionIncrement=1, status=ACTIVE}, success=true}, MigrationProgressNotification{event=START, participant=DESTINATION, migrationInfo=MigrationInfo{uuid=a01f22fd-712f-4d31-9bce-392060a13c8a, partitionId=0, source=[127.0.0.1]:5701 - 4fac831e-f0f2-4ba4-8dff-98f777797a75, sourceCurrentReplicaIndex=0, sourceNewReplicaIndex=1, destination=[127.0.0.1]:5702 - 9735bb8b-cbc0-4b8d-8881-61cd31ea1dba, destinationCurrentReplicaIndex=-1, destinationNewReplicaIndex=0, master=[127.0.0.1]:5701, initialPartitionVersion=1, partitionVersionIncrement=2, status=ACTIVE}, success=true}, MigrationProgressNotification{event=START, participant=DESTINATION, migrationInfo=MigrationInfo{uuid=146e0ad3-e54b-4af4-998f-16de762c5f88, partitionId=1, source=null, sourceCurrentReplicaIndex=-1, sourceNewReplicaIndex=-1, destination=[127.0.0.1]:5702 - 9735bb8b-cbc0-4b8d-8881-61cd31ea1dba, destinationCurrentReplicaIndex=-1, destinationNewReplicaIndex=1, master=[127.0.0.1]:5701, initialPartitionVersion=3, partitionVersionIncrement=1, status=SUCCESS}, success=true}, MigrationProgressNotification{event=START, participant=DESTINATION, migrationInfo=MigrationInfo{uuid=f5f82e33-3ec4-4c7b-a232-803255c5ae0d, partitionId=0, source=[127.0.0.1]:5701 - 4fac831e-f0f2-4ba4-8dff-98f777797a75, sourceCurrentReplicaIndex=0, sourceNewReplicaIndex=1, destination=[127.0.0.1]:5702 - 9735bb8b-cbc0-4b8d-8881-61cd31ea1dba, destinationCurrentReplicaIndex=-1, destinationNewReplicaIndex=0, master=[127.0.0.1]:5701, initialPartitionVersion=4, partitionVersionIncrement=2, status=SUCCESS}, success=true}, MigrationProgressNotification{event=COMPLETE, participant=DESTINATION, migrationInfo=MigrationInfo{uuid=f5f82e33-3ec4-4c7b-a232-803255c5ae0d, partitionId=0, source=[127.0.0.1]:5701 - 4fac831e-f0f2-4ba4-8dff-98f777797a75, sourceCurrentReplicaIndex=0, sourceNewReplicaIndex=1, destination=[127.0.0.1]:5702 - 9735bb8b-cbc0-4b8d-8881-61cd31ea1dba, destinationCurrentReplicaIndex=-1, destinationNewReplicaIndex=0, master=[127.0.0.1]:5701, initialPartitionVersion=4, partitionVersionIncrement=2, status=ACTIVE}, success=true}, MigrationProgressNotification{event=COMPLETE, participant=DESTINATION, migrationInfo=MigrationInfo{uuid=146e0ad3-e54b-4af4-998f-16de762c5f88, partitionId=1, source=null, sourceCurrentReplicaIndex=-1, sourceNewReplicaIndex=-1, destination=[127.0.0.1]:5702 - 9735bb8b-cbc0-4b8d-8881-61cd31ea1dba, destinationCurrentReplicaIndex=-1, destinationNewReplicaIndex=1, master=[127.0.0.1]:5701, initialPartitionVersion=3, partitionVersionIncrement=1, status=ACTIVE}, success=true}, MigrationProgressNotification{event=COMMIT, participant=DESTINATION, migrationInfo=MigrationInfo{uuid=f5f82e33-3ec4-4c7b-a232-803255c5ae0d, partitionId=0, source=[127.0.0.1]:5701 - 4fac831e-f0f2-4ba4-8dff-98f777797a75, sourceCurrentReplicaIndex=0, sourceNewReplicaIndex=1, destination=[127.0.0.1]:5702 - 9735bb8b-cbc0-4b8d-8881-61cd31ea1dba, destinationCurrentReplicaIndex=-1, destinationNewReplicaIndex=0, master=[127.0.0.1]:5701, initialPartitionVersion=4, partitionVersionIncrement=2, status=SUCCESS}, success=true}, MigrationProgressNotification{event=COMMIT, participant=DESTINATION, migrationInfo=MigrationInfo{uuid=146e0ad3-e54b-4af4-998f-16de762c5f88, partitionId=1, source=null, sourceCurrentReplicaIndex=-1, sourceNewReplicaIndex=-1, destination=[127.0.0.1]:5702 - 9735bb8b-cbc0-4b8d-8881-61cd31ea1dba, destinationCurrentReplicaIndex=-1, destinationNewReplicaIndex=1, master=[127.0.0.1]:5701, initialPartitionVersion=3, partitionVersionIncrement=1, status=SUCCESS}, success=true}] expected:<6> but was:<8>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at com.hazelcast.internal.partition.impl.MigrationInterceptorTest.shouldInvokeInternalMigrationListenerOnSuccessfulMigration(MigrationInterceptorTest.java:81)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:883)
```

</details>

<details><summary>Standard output:</summary>

```
04:57:56,578  INFO |shouldInvokeInternalMigrationListenerOnSuccessfulMigration| - [MetricsConfigHelper] shouldInvokeInternalMigrationListenerOnSuccessfulMigration - [LOCAL] [dev] [5.1-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
04:57:56,613  INFO |shouldInvokeInternalMigrationListenerOnSuccessfulMigration| - [logo] shouldInvokeInternalMigrationListenerOnSuccessfulMigration - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
04:57:56,613  INFO |shouldInvokeInternalMigrationListenerOnSuccessfulMigration| - [system] shouldInvokeInternalMigrationListenerOnSuccessfulMigration - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Copyright (c) 2008-2021, Hazelcast, Inc. All Rights Reserved.
04:57:56,613  INFO |shouldInvokeInternalMigrationListenerOnSuccessfulMigration| - [system] shouldInvokeInternalMigrationListenerOnSuccessfulMigration - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Hazelcast Platform 5.1-SNAPSHOT (20211209 - b519cd7) starting at [127.0.0.1]:5701
04:57:56,613  INFO |shouldInvokeInternalMigrationListenerOnSuccessfulMigration| - [system] shouldInvokeInternalMigrationListenerOnSuccessfulMigration - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Cluster name: dev
04:57:56,613  INFO |shouldInvokeInternalMigrationListenerOnSuccessfulMigration| - [system] shouldInvokeInternalMigrationListenerOnSuccessfulMigration - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] The Jet engine is disabled.
To enable the Jet engine on the members, please do one of the following:
  - Change member config using Java API: config.getJetConfig().setEnabled(true);
  - Change XML/YAML configuration property: Set hazelcast.jet.enabled to true
  - Add system property: -Dhz.jet.enabled=true
  - Add environment variable: HZ_JET_ENABLED=true
04:57:57,664  INFO |shouldInvokeInternalMigrationListenerOnSuccessfulMigration| - [MetricsConfigHelper] shouldInvokeInternalMigrationListenerOnSuccessfulMigration - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
04:57:58,439  WARN |shouldInvokeInternalMigrationListenerOnSuccessfulMigration| - [CPSubsystem] shouldInvokeInternalMigrationListenerOnSuccessfulMigration - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
04:57:59,079  INFO |shouldInvokeInternalMigrationListenerOnSuccessfulMigration| - [Diagnostics] shouldInvokeInternalMigrationListenerOnSuccessfulMigration - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
04:57:59,086  INFO |shouldInvokeInternalMigrationListenerOnSuccessfulMigration| - [LifecycleService] shouldInvokeInternalMigrationListenerOnSuccessfulMigration - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] [127.0.0.1]:5701 is STARTING
04:57:59,105  INFO |shouldInvokeInternalMigrationListenerOnSuccessfulMigration| - [ClusterService] shouldInvokeInternalMigrationListenerOnSuccessfulMigration - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] 

Members {size:1, ver:1} [
	Member [127.0.0.1]:5701 - 4fac831e-f0f2-4ba4-8dff-98f777797a75 this
]

04:57:59,106  INFO |shouldInvokeInternalMigrationListenerOnSuccessfulMigration| - [LifecycleService] shouldInvokeInternalMigrationListenerOnSuccessfulMigration - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] [127.0.0.1]:5701 is STARTED
04:57:59,239  INFO |shouldInvokeInternalMigrationListenerOnSuccessfulMigration| - [PartitionStateManager] shouldInvokeInternalMigrationListenerOnSuccessfulMigration - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Initializing cluster partition table arrangement...
04:57:59,324  INFO |shouldInvokeInternalMigrationListenerOnSuccessfulMigration| - [MetricsConfigHelper] shouldInvokeInternalMigrationListenerOnSuccessfulMigration - [LOCAL] [dev] [5.1-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
04:57:59,325  INFO |shouldInvokeInternalMigrationListenerOnSuccessfulMigration| - [logo] shouldInvokeInternalMigrationListenerOnSuccessfulMigration - [127.0.0.1]:5702 [dev] [5.1-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
04:57:59,325  INFO |shouldInvokeInternalMigrationListenerOnSuccessfulMigration| - [system] shouldInvokeInternalMigrationListenerOnSuccessfulMigration - [127.0.0.1]:5702 [dev] [5.1-SNAPSHOT] Copyright (c) 2008-2021, Hazelcast, Inc. All Rights Reserved.
04:57:59,325  INFO |shouldInvokeInternalMigrationListenerOnSuccessfulMigration| - [system] shouldInvokeInternalMigrationListenerOnSuccessfulMigration - [127.0.0.1]:5702 [dev] [5.1-SNAPSHOT] Hazelcast Platform 5.1-SNAPSHOT (20211209 - b519cd7) starting at [127.0.0.1]:5702
04:57:59,325  INFO |shouldInvokeInternalMigrationListenerOnSuccessfulMigration| - [system] shouldInvokeInternalMigrationListenerOnSuccessfulMigration - [127.0.0.1]:5702 [dev] [5.1-SNAPSHOT] Cluster name: dev
04:57:59,326  INFO |shouldInvokeInternalMigrationListenerOnSuccessfulMigration| - [system] shouldInvokeInternalMigrationListenerOnSuccessfulMigration - [127.0.0.1]:5702 [dev] [5.1-SNAPSHOT] The Jet engine is disabled.
To enable the Jet engine on the members, please do one of the following:
  - Change member config using Java API: config.getJetConfig().setEnabled(true);
  - Change XML/YAML configuration property: Set hazelcast.jet.enabled to true
  - Add system property: -Dhz.jet.enabled=true
  - Add environment variable: HZ_JET_ENABLED=true
04:57:59,332  INFO |shouldInvokeInternalMigrationListenerOnSuccessfulMigration| - [MetricsConfigHelper] shouldInvokeInternalMigrationListenerOnSuccessfulMigration - [127.0.0.1]:5702 [dev] [5.1-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
04:57:59,343  WARN |shouldInvokeInternalMigrationListenerOnSuccessfulMigration| - [CPSubsystem] shouldInvokeInternalMigrationListenerOnSuccessfulMigration - [127.0.0.1]:5702 [dev] [5.1-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
04:57:59,356  INFO |shouldInvokeInternalMigrationListenerOnSuccessfulMigration| - [Diagnostics] shouldInvokeInternalMigrationListenerOnSuccessfulMigration - [127.0.0.1]:5702 [dev] [5.1-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
04:57:59,356  INFO |shouldInvokeInternalMigrationListenerOnSuccessfulMigration| - [LifecycleService] shouldInvokeInternalMigrationListenerOnSuccessfulMigration - [127.0.0.1]:5702 [dev] [5.1-SNAPSHOT] [127.0.0.1]:5702 is STARTING
04:57:59,552  INFO |shouldInvokeInternalMigrationListenerOnSuccessfulMigration| - [MockServer] shouldInvokeInternalMigrationListenerOnSuccessfulMigration - [127.0.0.1]:5702 [dev] [5.1-SNAPSHOT] Created connection to endpoint: [127.0.0.1]:5701, connection: MockConnection{localEndpoint=[127.0.0.1]:5702, remoteEndpoint=[127.0.0.1]:5701, alive=true}
04:57:59,553  INFO |shouldInvokeInternalMigrationListenerOnSuccessfulMigration| - [MockServer] hz.pedantic_wozniak.priority-generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Created connection to endpoint: [127.0.0.1]:5702, connection: MockConnection{localEndpoint=[127.0.0.1]:5701, remoteEndpoint=[127.0.0.1]:5702, alive=true}
04:57:59,628  INFO |shouldInvokeInternalMigrationListenerOnSuccessfulMigration| - [ClusterService] hz.pedantic_wozniak.priority-generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] 

Members {size:2, ver:2} [
	Member [127.0.0.1]:5701 - 4fac831e-f0f2-4ba4-8dff-98f777797a75 this
	Member [127.0.0.1]:5702 - 9735bb8b-cbc0-4b8d-8881-61cd31ea1dba
]

04:57:59,879  INFO |shouldInvokeInternalMigrationListenerOnSuccessfulMigration| - [MigrationManager] hz.pedantic_wozniak.migration - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Repartitioning cluster data. Migration tasks count: 2
04:57:59,919  INFO |shouldInvokeInternalMigrationListenerOnSuccessfulMigration| - [ClusterService] hz.unruffled_wozniak.generic-operation.thread-3 - [127.0.0.1]:5702 [dev] [5.1-SNAPSHOT] 

Members {size:2, ver:2} [
	Member [127.0.0.1]:5701 - 4fac831e-f0f2-4ba4-8dff-98f777797a75
	Member [127.0.0.1]:5702 - 9735bb8b-cbc0-4b8d-8881-61cd31ea1dba this
]

04:57:59,919  INFO |shouldInvokeInternalMigrationListenerOnSuccessfulMigration| - [LifecycleService] shouldInvokeInternalMigrationListenerOnSuccessfulMigration - [127.0.0.1]:5702 [dev] [5.1-SNAPSHOT] [127.0.0.1]:5702 is STARTED
04:57:59,927  WARN |shouldInvokeInternalMigrationListenerOnSuccessfulMigration| - [MigrationRequestOperation] hz.pedantic_wozniak.async.thread-1 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Failure while executing MigrationInfo{uuid=e1581d0b-82af-4589-ae24-239ccda46d1b, partitionId=1, source=null, sourceCurrentReplicaIndex=-1, sourceNewReplicaIndex=-1, destination=[127.0.0.1]:5702 - 9735bb8b-cbc0-4b8d-8881-61cd31ea1dba, destinationCurrentReplicaIndex=-1, destinationNewReplicaIndex=1, master=[127.0.0.1]:5701, initialPartitionVersion=1, partitionVersionIncrement=1, status=ACTIVE}
com.hazelcast.internal.partition.PartitionStateVersionMismatchException: Local partition stamp is not equal to master's stamp! Local: 0, Master: 1
	at com.hazelcast.internal.partition.operation.BaseMigrationOperation.verifyPartitionVersion(BaseMigrationOperation.java:143) ~[classes/:?]
	at com.hazelcast.internal.partition.operation.BaseMigrationOperation.beforeRun(BaseMigrationOperation.java:96) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:247) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:469) ~[classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:197) ~[classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:137) ~[classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123) ~[classes/:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) [classes/:?]
04:57:59,930  WARN |shouldInvokeInternalMigrationListenerOnSuccessfulMigration| - [MigrationRequestOperation] hz.pedantic_wozniak.async.thread-2 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Failure while executing MigrationInfo{uuid=a01f22fd-712f-4d31-9bce-392060a13c8a, partitionId=0, source=[127.0.0.1]:5701 - 4fac831e-f0f2-4ba4-8dff-98f777797a75, sourceCurrentReplicaIndex=0, sourceNewReplicaIndex=1, destination=[127.0.0.1]:5702 - 9735bb8b-cbc0-4b8d-8881-61cd31ea1dba, destinationCurrentReplicaIndex=-1, destinationNewReplicaIndex=0, master=[127.0.0.1]:5701, initialPartitionVersion=1, partitionVersionIncrement=2, status=ACTIVE}
com.hazelcast.internal.partition.PartitionStateVersionMismatchException: Local partition stamp is not equal to master's stamp! Local: 0, Master: 1
	at com.hazelcast.internal.partition.operation.BaseMigrationOperation.verifyPartitionVersion(BaseMigrationOperation.java:143) ~[classes/:?]
	at com.hazelcast.internal.partition.operation.BaseMigrationOperation.beforeRun(BaseMigrationOperation.java:96) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:247) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:469) ~[classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:197) ~[classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:137) ~[classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123) ~[classes/:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) [classes/:?]
04:57:59,931  WARN |shouldInvokeInternalMigrationListenerOnSuccessfulMigration| - [MigrationManager] hz.pedantic_wozniak.async.thread-4 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Migration failed: MigrationInfo{uuid=e1581d0b-82af-4589-ae24-239ccda46d1b, partitionId=1, source=null, sourceCurrentReplicaIndex=-1, sourceNewReplicaIndex=-1, destination=[127.0.0.1]:5702 - 9735bb8b-cbc0-4b8d-8881-61cd31ea1dba, destinationCurrentReplicaIndex=-1, destinationNewReplicaIndex=1, master=[127.0.0.1]:5701, initialPartitionVersion=1, partitionVersionIncrement=1, status=ACTIVE}
04:57:59,936  WARN |shouldInvokeInternalMigrationListenerOnSuccessfulMigration| - [MigrationManager] hz.pedantic_wozniak.async.thread-6 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Migration failed: MigrationInfo{uuid=a01f22fd-712f-4d31-9bce-392060a13c8a, partitionId=0, source=[127.0.0.1]:5701 - 4fac831e-f0f2-4ba4-8dff-98f777797a75, sourceCurrentReplicaIndex=0, sourceNewReplicaIndex=1, destination=[127.0.0.1]:5702 - 9735bb8b-cbc0-4b8d-8881-61cd31ea1dba, destinationCurrentReplicaIndex=-1, destinationNewReplicaIndex=0, master=[127.0.0.1]:5701, initialPartitionVersion=1, partitionVersionIncrement=2, status=ACTIVE}
04:58:00,035  INFO |shouldInvokeInternalMigrationListenerOnSuccessfulMigration| - [MigrationManager] hz.pedantic_wozniak.migration - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Rebalance process was failed. Ignoring remaining migrations. Will recalculate the new migration plan. (repartitionTime=Thu Dec 09 04:57:59 UTC 2021, plannedMigrations=2, completedMigrations=2, remainingMigrations=0, totalCompletedMigrations=2, elapsedMigrationOperationTime=63ms, totalElapsedMigrationOperationTime=63ms, elapsedDestinationCommitTime=0ms, totalElapsedDestinationCommitTime=0ms, elapsedMigrationTime=265ms, totalElapsedMigrationTime=265ms)
04:58:03,037  INFO |shouldInvokeInternalMigrationListenerOnSuccessfulMigration| - [MigrationManager] hz.pedantic_wozniak.migration - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Repartitioning cluster data. Migration tasks count: 2
04:58:03,284  INFO |shouldInvokeInternalMigrationListenerOnSuccessfulMigration| - [MigrationManager] hz.pedantic_wozniak.migration - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] All migration tasks have been completed. (repartitionTime=Thu Dec 09 04:58:03 UTC 2021, plannedMigrations=2, completedMigrations=2, remainingMigrations=0, totalCompletedMigrations=4, elapsedMigrationOperationTime=491ms, totalElapsedMigrationOperationTime=554ms, elapsedDestinationCommitTime=0ms, totalElapsedDestinationCommitTime=0ms, elapsedMigrationTime=492ms, totalElapsedMigrationTime=758ms)
04:58:03,664  INFO |shouldInvokeInternalMigrationListenerOnSuccessfulMigration| - [LifecycleService] main - [127.0.0.1]:5702 [dev] [5.1-SNAPSHOT] [127.0.0.1]:5702 is SHUTTING_DOWN
04:58:03,770  WARN |shouldInvokeInternalMigrationListenerOnSuccessfulMigration| - [Node] main - [127.0.0.1]:5702 [dev] [5.1-SNAPSHOT] Terminating forcefully...
04:58:03,800  INFO |shouldInvokeInternalMigrationListenerOnSuccessfulMigration| - [Node] main - [127.0.0.1]:5702 [dev] [5.1-SNAPSHOT] Shutting down connection manager...
04:58:03,800  INFO |shouldInvokeInternalMigrationListenerOnSuccessfulMigration| - [MockServer] main - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5702, connection: MockConnection{localEndpoint=[127.0.0.1]:5701, remoteEndpoint=[127.0.0.1]:5702, alive=false}
04:58:03,800  INFO |shouldInvokeInternalMigrationListenerOnSuccessfulMigration| - [MockServer] main - [127.0.0.1]:5702 [dev] [5.1-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5701, connection: MockConnection{localEndpoint=[127.0.0.1]:5702, remoteEndpoint=[127.0.0.1]:5701, alive=false}
04:58:03,815  INFO |shouldInvokeInternalMigrationListenerOnSuccessfulMigration| - [MembershipManager] main - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Removing Member [127.0.0.1]:5702 - 9735bb8b-cbc0-4b8d-8881-61cd31ea1dba
04:58:03,824  INFO |shouldInvokeInternalMigrationListenerOnSuccessfulMigration| - [PartitionStateManager] main - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Storing snapshot of partition assignments while removing UUID 9735bb8b-cbc0-4b8d-8881-61cd31ea1dba
04:58:03,824  INFO |shouldInvokeInternalMigrationListenerOnSuccessfulMigration| - [ClusterService] main - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] 

Members {size:1, ver:3} [
	Member [127.0.0.1]:5701 - 4fac831e-f0f2-4ba4-8dff-98f777797a75 this
]

04:58:03,824  INFO |shouldInvokeInternalMigrationListenerOnSuccessfulMigration| - [Node] main - [127.0.0.1]:5702 [dev] [5.1-SNAPSHOT] Shutting down node engine...
04:58:03,824  INFO |shouldInvokeInternalMigrationListenerOnSuccessfulMigration| - [TransactionManagerService] hz.pedantic_wozniak.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Committing/rolling-back live transactions of [127.0.0.1]:5702, UUID: 9735bb8b-cbc0-4b8d-8881-61cd31ea1dba
04:58:03,825  INFO |shouldInvokeInternalMigrationListenerOnSuccessfulMigration| - [MigrationManager] hz.pedantic_wozniak.migration - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Partition balance is ok, no need to repartition.
04:58:03,861  INFO |shouldInvokeInternalMigrationListenerOnSuccessfulMigration| - [NodeExtension] main - [127.0.0.1]:5702 [dev] [5.1-SNAPSHOT] Destroying node NodeExtension.
04:58:03,861  INFO |shouldInvokeInternalMigrationListenerOnSuccessfulMigration| - [Node] main - [127.0.0.1]:5702 [dev] [5.1-SNAPSHOT] Hazelcast Shutdown is completed in 91 ms.
04:58:03,861  INFO |shouldInvokeInternalMigrationListenerOnSuccessfulMigration| - [LifecycleService] main - [127.0.0.1]:5702 [dev] [5.1-SNAPSHOT] [127.0.0.1]:5702 is SHUTDOWN
04:58:03,861  INFO |shouldInvokeInternalMigrationListenerOnSuccessfulMigration| - [LifecycleService] main - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
04:58:03,861  WARN |shouldInvokeInternalMigrationListenerOnSuccessfulMigration| - [Node] main - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Terminating forcefully...
04:58:03,861  INFO |shouldInvokeInternalMigrationListenerOnSuccessfulMigration| - [Node] main - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Shutting down connection manager...
04:58:03,861  INFO |shouldInvokeInternalMigrationListenerOnSuccessfulMigration| - [Node] main - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Shutting down node engine...
04:58:03,870  INFO |shouldInvokeInternalMigrationListenerOnSuccessfulMigration| - [NodeExtension] main - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Destroying node NodeExtension.
04:58:03,870  INFO |shouldInvokeInternalMigrationListenerOnSuccessfulMigration| - [Node] main - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Hazelcast Shutdown is completed in 9 ms.
04:58:03,870  INFO |shouldInvokeInternalMigrationListenerOnSuccessfulMigration| - [LifecycleService] main - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
BuildInfo right after shouldInvokeInternalMigrationListenerOnSuccessfulMigration(com.hazelcast.internal.partition.impl.MigrationInterceptorTest): BuildInfo{version='5.1-SNAPSHOT', build='20211209', buildNumber=20211209, revision=b519cd7, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'shouldInvokeInternalMigrationListenerOnSuccessfulMigration(com.hazelcast.internal.partition.impl.MigrationInterceptorTest):'
04:57:55, accumulated pauses: 190 ms, max pause: 6 ms, pauses over 1000 ms: 0
04:58:00, accumulated pauses: 177 ms, max pause: 86 ms, pauses over 1000 ms: 0
```

</details>

**Comment by olukas** [comment]
Failed on `5.1.z` branch on Openj9-17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-Openj9-17/1/testReport/com.hazelcast.internal.partition.impl/MigrationInterceptorTest/shouldInvokeInternalMigrationListenerOnSuccessfulMigration/
