### ISSUE TITLE
com.hazelcast.client.txn.ClientTxnTest.testTxnRollback

### ISSUE THREAD

**Issue by slavagithub** [hazelcast/hazelcast#20173]
_master_ (commit f32cb642bee7191c7769876a00b5e1b78f1762cf)

Failed on Corretto, JDK8: INSERT_LINK_TO_JENKINS_TEST_RESULT_HERE

<details><summary>Stacktrace:</summary>

```
com.hazelcast.spi.exception.TargetDisconnectedException: Mocked Remote socket closed
	at com.hazelcast.client.impl.spi.impl.ClientInvocationServiceImpl.onConnectionClose(ClientInvocationServiceImpl.java:220)
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.onConnectionClose(TcpClientConnectionManager.java:762)
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnection.close(TcpClientConnection.java:191)
	at com.hazelcast.client.test.TestClientRegistry$MockedTcpClientConnection$4.run(TestClientRegistry.java:307)
	at com.hazelcast.client.test.TwoWayBlockableExecutor$BlockableRunnable.run(TwoWayBlockableExecutor.java:98)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at ------ submitted from ------.()
	at com.hazelcast.internal.util.ExceptionUtil.cloneExceptionWithFixedAsyncStackTrace(ExceptionUtil.java:279)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.returnOrThrowWithGetConventions(InvocationFuture.java:112)
	at com.hazelcast.client.impl.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:95)
	at com.hazelcast.client.impl.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:40)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:617)
	at com.hazelcast.client.impl.proxy.txn.ClientTransactionUtil.invoke(ClientTransactionUtil.java:52)
	at com.hazelcast.client.impl.proxy.txn.TransactionProxy.commit(TransactionProxy.java:107)
	at com.hazelcast.client.impl.proxy.txn.TransactionContextProxy.commitTransaction(TransactionContextProxy.java:85)
	at com.hazelcast.client.txn.ClientTxnTest.testTxnRollback(ClientTxnTest.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.hazelcast.spi.exception.TargetDisconnectedException: Mocked Remote socket closed
	at com.hazelcast.client.test.TestClientRegistry$MockedTcpClientConnection$4.run(TestClientRegistry.java:307)
	at com.hazelcast.client.test.TwoWayBlockableExecutor$BlockableRunnable.run(TwoWayBlockableExecutor.java:98)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
```

</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: testTxnRollbackOnServerCrash in 0.344 seconds.
16:35:44,099  INFO |testTxnRollback| - [MigrationManager] hz.nervous_mayer.migration - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] All migration tasks have been completed. (repartitionTime=Sun Dec 12 16:35:43 UTC 2021, plannedMigrations=135, completedMigrations=135, remainingMigrations=0, totalCompletedMigrations=135, elapsedMigrationOperationTime=478ms, totalElapsedMigrationOperationTime=478ms, elapsedDestinationCommitTime=99ms, totalElapsedDestinationCommitTime=99ms, elapsedMigrationTime=649ms, totalElapsedMigrationTime=649ms)
16:35:44,112  INFO |testTxnRollback| - [Node] testTxnRollback - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Shutting down connection manager...
16:35:44,112  INFO |testTxnRollback| - [MockServer] testTxnRollback - [127.0.0.1]:5702 [dev] [5.1-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5701, connection: MockConnection{localEndpoint=[127.0.0.1]:5702, remoteEndpoint=[127.0.0.1]:5701, alive=false}
16:35:44,112  INFO |testTxnRollback| - [MockServer] testTxnRollback - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5702, connection: MockConnection{localEndpoint=[127.0.0.1]:5701, remoteEndpoint=[127.0.0.1]:5702, alive=false}
16:35:44,112  WARN |testTxnRollback| - [TestClientRegistry$MockedServerConnection] testTxnRollback - Server connection closed: null
16:35:44,113  INFO |testTxnRollback| - [MockServer] testTxnRollback - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:40001, connection: MockedNodeConnection{ remoteAddress = [127.0.0.1]:40001, localAddress = [127.0.0.1]:5701, connectionId = 1}
16:35:44,113  WARN |testTxnRollback| - [MembershipManager] testTxnRollback - [127.0.0.1]:5702 [dev] [5.1-SNAPSHOT] Member [127.0.0.1]:5701 - 5ece8c4c-dc95-4d10-9220-abc65e6306c8 is suspected to be dead for reason: Connection manager is stopped on Member [127.0.0.1]:5701 - 5ece8c4c-dc95-4d10-9220-abc65e6306c8 this
16:35:44,113  INFO |testTxnRollback| - [MembershipManager] testTxnRollback - [127.0.0.1]:5702 [dev] [5.1-SNAPSHOT] Starting mastership claim process...
16:35:44,113  INFO |testTxnRollback| - [MembershipManager] testTxnRollback - [127.0.0.1]:5702 [dev] [5.1-SNAPSHOT] Local MembersView{version=2, members=[MemberInfo{address=[127.0.0.1]:5701, uuid=5ece8c4c-dc95-4d10-9220-abc65e6306c8, liteMember=false, memberListJoinVersion=1}, MemberInfo{address=[127.0.0.1]:5702, uuid=ec67d207-5f0f-4501-8ba9-3cd2af00b252, liteMember=false, memberListJoinVersion=2}]} with suspected members: [Member [127.0.0.1]:5701 - 5ece8c4c-dc95-4d10-9220-abc65e6306c8] and initial addresses to ask: []
16:35:44,113  INFO |testTxnRollback| - [Node] testTxnRollback - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Shutting down node engine...
16:35:44,124  INFO |testTxnRollback| - [TransactionManagerService] hz.sweet_mayer.cached.thread-1 - [127.0.0.1]:5702 [dev] [5.1-SNAPSHOT] Committing/rolling-back live transactions of [127.0.0.1]:5701, UUID: 5ece8c4c-dc95-4d10-9220-abc65e6306c8
16:35:44,124  INFO |testTxnRollback| - [ClusterService] hz.sweet_mayer.cached.thread-2 - [127.0.0.1]:5702 [dev] [5.1-SNAPSHOT] 

Members {size:1, ver:3} [
	Member [127.0.0.1]:5702 - ec67d207-5f0f-4501-8ba9-3cd2af00b252 this
]

16:35:44,127  INFO |testTxnRollback| - [MembershipManager] hz.sweet_mayer.cached.thread-2 - [127.0.0.1]:5702 [dev] [5.1-SNAPSHOT] Mastership is claimed with: MembersView{version=3, members=[MemberInfo{address=[127.0.0.1]:5702, uuid=ec67d207-5f0f-4501-8ba9-3cd2af00b252, liteMember=false, memberListJoinVersion=2}]}
16:35:44,154  INFO |testTxnRollback| - [NodeExtension] testTxnRollback - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Destroying node NodeExtension.
16:35:44,154  INFO |testTxnRollback| - [Node] testTxnRollback - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Hazelcast Shutdown is completed in 212 ms.
16:35:44,155  INFO |testTxnRollback| - [LifecycleService] testTxnRollback - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
16:35:44,155  WARN |testTxnRollback| - [TwoWayBlockableExecutor] testTxnRollback - Dropping outgoing runnable since other end closed. Runnable message ClientMessage{connection=null, length=47, operation=Transaction.Commit, isRetryable=false, correlationId=8, messageType=150100, isEvent=false, isfragmented=false}, MockedClientConnection{localAddress=[127.0.0.1]:40001, super=ClientConnection{alive=true, connectionId=1, channel=null, remoteAddress=[127.0.0.1]:5701, lastReadTime=2021-12-12 16:35:43.941, lastWriteTime=2021-12-12 16:35:43.924, closedTime=never, connected server version=5.1-SNAPSHOT}}
16:35:44,207  INFO |testTxnRollback| - [InternalPartitionService] hz.sweet_mayer.migration - [127.0.0.1]:5702 [dev] [5.1-SNAPSHOT] Fetching partition tables from cluster to determine the most recent one... Local stamp: -3822423072622700633
16:35:44,207  INFO |testTxnRollback| - [InternalPartitionService] hz.sweet_mayer.migration - [127.0.0.1]:5702 [dev] [5.1-SNAPSHOT] Most recent partition table is determined.
16:35:44,208  INFO |testTxnRollback| - [InternalPartitionService] hz.sweet_mayer.migration - [127.0.0.1]:5702 [dev] [5.1-SNAPSHOT] Applying the most recent of partition state...
16:35:44,238  WARN |testTxnRollback| - [TcpClientConnection] pool-10918-thread-1 - hz.client_3670 [dev] [5.1-SNAPSHOT] MockedClientConnection{localAddress=[127.0.0.1]:40001, super=ClientConnection{alive=false, connectionId=1, channel=null, remoteAddress=[127.0.0.1]:5701, lastReadTime=2021-12-12 16:35:43.941, lastWriteTime=2021-12-12 16:35:43.924, closedTime=2021-12-12 16:35:44.238, connected server version=5.1-SNAPSHOT}} closed. Reason: com.hazelcast.spi.exception.TargetDisconnectedException[Mocked Remote socket closed]
com.hazelcast.spi.exception.TargetDisconnectedException: Mocked Remote socket closed
	at com.hazelcast.client.test.TestClientRegistry$MockedTcpClientConnection$4.run(TestClientRegistry.java:307) [test-classes/:?]
	at com.hazelcast.client.test.TwoWayBlockableExecutor$BlockableRunnable.run(TwoWayBlockableExecutor.java:98) [test-classes/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_312]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_312]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
16:35:44,239  WARN |testTxnRollback| - [TwoWayBlockableExecutor] pool-10918-thread-1 - Dropping outgoing runnable since other end closed. Client Closed EOF. MockedClientConnection{localAddress=[127.0.0.1]:40001, super=ClientConnection{alive=false, connectionId=1, channel=null, remoteAddress=[127.0.0.1]:5701, lastReadTime=2021-12-12 16:35:43.941, lastWriteTime=2021-12-12 16:35:43.924, closedTime=2021-12-12 16:35:44.238, connected server version=5.1-SNAPSHOT}}
16:35:44,241  INFO |testTxnRollback| - [ClientConnectionManager] pool-10918-thread-1 - hz.client_3670 [dev] [5.1-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5701:5ece8c4c-dc95-4d10-9220-abc65e6306c8, connection: MockedClientConnection{localAddress=[127.0.0.1]:40001, super=ClientConnection{alive=false, connectionId=1, channel=null, remoteAddress=[127.0.0.1]:5701, lastReadTime=2021-12-12 16:35:43.941, lastWriteTime=2021-12-12 16:35:43.924, closedTime=2021-12-12 16:35:44.238, connected server version=5.1-SNAPSHOT}}
16:35:44,241  INFO |testTxnRollback| - [LifecycleService] pool-10918-thread-1 - hz.client_3670 [dev] [5.1-SNAPSHOT] HazelcastClient 5.1-SNAPSHOT (20211212 - f32cb64) is CLIENT_DISCONNECTED
16:35:44,250  INFO |testTxnRollback| - [MigrationManager] hz.sweet_mayer.migration - [127.0.0.1]:5702 [dev] [5.1-SNAPSHOT] Partition balance is ok, no need to repartition.
16:35:44,520  INFO |testTxnRollback| - [ClientConnectionManager] hz.client_3670.internal-1 - hz.client_3670 [dev] [5.1-SNAPSHOT] Trying to connect to cluster: dev
16:35:44,520  INFO |testTxnRollback| - [ClientConnectionManager] hz.client_3670.internal-1 - hz.client_3670 [dev] [5.1-SNAPSHOT] Trying to connect to Member [127.0.0.1]:5702 - ec67d207-5f0f-4501-8ba9-3cd2af00b252
16:35:44,520  INFO |testTxnRollback| - [HazelcastClient] hz.client_3670.internal-1 - Created connection to endpoint: [127.0.0.1]:5702, connection: MockedClientConnection{localAddress=[127.0.0.1]:40002, super=ClientConnection{alive=true, connectionId=2, channel=null, remoteAddress=null, lastReadTime=never, lastWriteTime=never, closedTime=never, connected server version=null}}
16:35:44,521 DEBUG |testTxnRollback| - [AuthenticationMessageTask] hz.sweet_mayer.priority-generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.1-SNAPSHOT] Processing authentication with clientUuid 99f586e2-f541-401c-b00d-3b49cbb033fa and clientName hz.client_3670
16:35:44,521  INFO |testTxnRollback| - [AuthenticationMessageTask] hz.sweet_mayer.priority-generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.1-SNAPSHOT] Received auth from MockedNodeConnection{ remoteAddress = [127.0.0.1]:40002, localAddress = [127.0.0.1]:5702, connectionId = 2}, successfully authenticated, clientUuid: 99f586e2-f541-401c-b00d-3b49cbb033fa, client name: hz.client_3670, client version: 5.1-SNAPSHOT
16:35:44,521  INFO |testTxnRollback| - [LifecycleService] hz.client_3670.internal-1 - hz.client_3670 [dev] [5.1-SNAPSHOT] HazelcastClient 5.1-SNAPSHOT (20211212 - f32cb64) is CLIENT_CONNECTED
16:35:44,521  INFO |testTxnRollback| - [ClientConnectionManager] hz.client_3670.internal-1 - hz.client_3670 [dev] [5.1-SNAPSHOT] Authenticated with server [127.0.0.1]:5702:ec67d207-5f0f-4501-8ba9-3cd2af00b252, server version: 5.1-SNAPSHOT, local address: /127.0.0.1:40002
16:35:44,521 TRACE |testTxnRollback| - [ClientListenerService] hz.client_3670.internal-2 - hz.client_3670 [dev] [5.1-SNAPSHOT] Register attempt of ClusterViewListenerHandler to MockedClientConnection{localAddress=[127.0.0.1]:40002, super=ClientConnection{alive=true, connectionId=2, channel=null, remoteAddress=[127.0.0.1]:5702, lastReadTime=2021-12-12 16:35:44.521, lastWriteTime=2021-12-12 16:35:44.521, closedTime=never, connected server version=5.1-SNAPSHOT}}
16:35:44,521 TRACE |testTxnRollback| - [ClientListenerService] hz.client_3670.eventRegistration- - hz.client_3670 [dev] [5.1-SNAPSHOT] Register attempt of ClientListenerRegistration{codec=com.hazelcast.client.impl.spi.impl.ClientInvocationServiceImpl$1@69009a50, handler=com.hazelcast.client.impl.spi.impl.ClientInvocationServiceImpl$BackupEventHandler@5486772d} to MockedClientConnection{localAddress=[127.0.0.1]:40002, super=ClientConnection{alive=true, connectionId=2, channel=null, remoteAddress=[127.0.0.1]:5702, lastReadTime=2021-12-12 16:35:44.521, lastWriteTime=2021-12-12 16:35:44.521, closedTime=never, connected server version=5.1-SNAPSHOT}}
16:35:44,521 TRACE |testTxnRollback| - [ClientListenerService] hz.client_3670.eventRegistration- - hz.client_3670 [dev] [5.1-SNAPSHOT] Registered ClientListenerRegistration{codec=com.hazelcast.client.impl.spi.impl.ClientInvocationServiceImpl$1@69009a50, handler=com.hazelcast.client.impl.spi.impl.ClientInvocationServiceImpl$BackupEventHandler@5486772d} to MockedClientConnection{localAddress=[127.0.0.1]:40002, super=ClientConnection{alive=true, connectionId=2, channel=null, remoteAddress=[127.0.0.1]:5702, lastReadTime=2021-12-12 16:35:44.521, lastWriteTime=2021-12-12 16:35:44.521, closedTime=never, connected server version=5.1-SNAPSHOT}}
16:35:44,521  INFO |testTxnRollback| - [ClientClusterService] hz.client_3670.event-38609 - hz.client_3670 [dev] [5.1-SNAPSHOT] 

Members [1] {
	Member [127.0.0.1]:5702 - ec67d207-5f0f-4501-8ba9-3cd2af00b252
}

16:35:44,522 TRACE |testTxnRollback| - [ClientListenerService] ForkJoinPool.commonPool-worker-3 - hz.client_3670 [dev] [5.1-SNAPSHOT] Registered ClusterViewListenerHandler to MockedClientConnection{localAddress=[127.0.0.1]:40002, super=ClientConnection{alive=true, connectionId=2, channel=null, remoteAddress=[127.0.0.1]:5702, lastReadTime=2021-12-12 16:35:44.521, lastWriteTime=2021-12-12 16:35:44.521, closedTime=never, connected server version=5.1-SNAPSHOT}}
16:35:44,530  INFO |testTxnRollback| - [LifecycleService] Thread-30286 - hz.client_3670 [dev] [5.1-SNAPSHOT] HazelcastClient 5.1-SNAPSHOT (20211212 - f32cb64) is SHUTTING_DOWN
16:35:44,530  INFO |testTxnRollback| - [ClientConnectionManager] Thread-30286 - hz.client_3670 [dev] [5.1-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5702:ec67d207-5f0f-4501-8ba9-3cd2af00b252, connection: MockedClientConnection{localAddress=[127.0.0.1]:40002, super=ClientConnection{alive=false, connectionId=2, channel=null, remoteAddress=[127.0.0.1]:5702, lastReadTime=2021-12-12 16:35:44.521, lastWriteTime=2021-12-12 16:35:44.521, closedTime=2021-12-12 16:35:44.530, connected server version=5.1-SNAPSHOT}}
16:35:44,530  WARN |testTxnRollback| - [TestClientRegistry$MockedServerConnection] pool-10923-thread-1 - Server connection closed: null
16:35:44,530  INFO |testTxnRollback| - [LifecycleService] Thread-30286 - hz.client_3670 [dev] [5.1-SNAPSHOT] HazelcastClient 5.1-SNAPSHOT (20211212 - f32cb64) is CLIENT_DISCONNECTED
16:35:44,530  INFO |testTxnRollback| - [MockServer] pool-10923-thread-1 - [127.0.0.1]:5702 [dev] [5.1-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:40002, connection: MockedNodeConnection{ remoteAddress = [127.0.0.1]:40002, localAddress = [127.0.0.1]:5702, connectionId = 2}
16:35:44,530  WARN |testTxnRollback| - [TwoWayBlockableExecutor] pool-10923-thread-1 - Dropping incoming runnable since other end closed. Server Closed EOF. MockedClientConnection{localAddress=[127.0.0.1]:40002, super=ClientConnection{alive=false, connectionId=2, channel=null, remoteAddress=[127.0.0.1]:5702, lastReadTime=2021-12-12 16:35:44.521, lastWriteTime=2021-12-12 16:35:44.521, closedTime=2021-12-12 16:35:44.530, connected server version=5.1-SNAPSHOT}}
16:35:44,530  INFO |testTxnRollback| - [ClientEndpointManager] hz.sweet_mayer.event-38618 - [127.0.0.1]:5702 [dev] [5.1-SNAPSHOT] Destroying ClientEndpoint{connection=MockedNodeConnection{ remoteAddress = [127.0.0.1]:40002, localAddress = [127.0.0.1]:5702, connectionId = 2}, clientUuid=99f586e2-f541-401c-b00d-3b49cbb033fa, clientName=hz.client_3670, authenticated=true, clientVersion=5.1-SNAPSHOT, creationTime=1639326944521, latest clientAttributes=null, labels=[]}
16:35:44,531  INFO |testTxnRollback| - [LifecycleService] Thread-30286 - hz.client_3670 [dev] [5.1-SNAPSHOT] HazelcastClient 5.1-SNAPSHOT (20211212 - f32cb64) is SHUTDOWN
16:35:44,531  INFO |testTxnRollback| - [LifecycleService] Thread-30286 - [127.0.0.1]:5702 [dev] [5.1-SNAPSHOT] [127.0.0.1]:5702 is SHUTTING_DOWN
16:35:44,531  WARN |testTxnRollback| - [Node] Thread-30286 - [127.0.0.1]:5702 [dev] [5.1-SNAPSHOT] Terminating forcefully...
16:35:44,531  INFO |testTxnRollback| - [Node] Thread-30286 - [127.0.0.1]:5702 [dev] [5.1-SNAPSHOT] Shutting down connection manager...
16:35:44,531  INFO |testTxnRollback| - [Node] Thread-30286 - [127.0.0.1]:5702 [dev] [5.1-SNAPSHOT] Shutting down node engine...
16:35:44,532  INFO |testTxnRollback| - [NodeExtension] Thread-30286 - [127.0.0.1]:5702 [dev] [5.1-SNAPSHOT] Destroying node NodeExtension.
16:35:44,532  INFO |testTxnRollback| - [Node] Thread-30286 - [127.0.0.1]:5702 [dev] [5.1-SNAPSHOT] Hazelcast Shutdown is completed in 1 ms.
16:35:44,532  INFO |testTxnRollback| - [LifecycleService] Thread-30286 - [127.0.0.1]:5702 [dev] [5.1-SNAPSHOT] [127.0.0.1]:5702 is SHUTDOWN
16:35:44,532  INFO |testTxnRollback| - [LifecycleService] Thread-30286 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
16:35:44,532  INFO |testTxnRollback| - [Node] Thread-30286 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Node is already shutting down... Waiting for shutdown process to complete...
16:35:44,532  INFO |testTxnRollback| - [LifecycleService] Thread-30286 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
BuildInfo right after testTxnRollback(com.hazelcast.client.txn.ClientTxnTest): BuildInfo{version='5.1-SNAPSHOT', build='20211212', buildNumber=20211212, revision=f32cb64, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'testTxnRollback(com.hazelcast.client.txn.ClientTxnTest):'
16:35:40, accumulated pauses: 1471 ms, max pause: 805 ms, pauses over 1000 ms: 0


No metrics recorded during the test
```

</details>

**Comment by AleksPeychev** [comment]
Failed again on _master_ with OpenJDK17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-OpenJDK17-Esxi7/83/testReport/junit/com.hazelcast.client.txn/ClientTxnTest/testTxnRollback/
