### ISSUE TITLE
Provide more helpful error message how to enable user code deployment

### ISSUE THREAD

**Issue by Holmistr** [hazelcast/hazelcast#20253]
**Description of the problem**
When you try to do user code deployment from a client, but you didn't enable it on the server, you'll get:
```
java.lang.IllegalStateException: User Code Deployment is not enabled.
	at com.hazelcast.internal.usercodedeployment.UserCodeDeploymentService.defineClasses(UserCodeDeploymentService.java:72) ~[hazelcast-5.0.jar:5.0]
	at com.hazelcast.internal.usercodedeployment.impl.operation.DeployClassesOperation.run(DeployClassesOperation.java:49) ~[hazelcast-5.0.jar:5.0]
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:189) [hazelcast-5.0.jar:5.0]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:272) [hazelcast-5.0.jar:5.0]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:248) [hazelcast-5.0.jar:5.0]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:213) [hazelcast-5.0.jar:5.0]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:411) [hazelcast-5.0.jar:5.0]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:438) [hazelcast-5.0.jar:5.0]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:600) [hazelcast-5.0.jar:5.0]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:579) [hazelcast-5.0.jar:5.0]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:540) [hazelcast-5.0.jar:5.0]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:240) [hazelcast-5.0.jar:5.0]
	at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:59) [hazelcast-5.0.jar:5.0]
	at com.hazelcast.client.impl.protocol.task.AbstractMultiTargetMessageTask.processInternal(AbstractMultiTargetMessageTask.java:70) [hazelcast-5.0.jar:5.0]
	at com.hazelcast.client.impl.protocol.task.AbstractAsyncMessageTask.processMessage(AbstractAsyncMessageTask.java:71) [hazelcast-5.0.jar:5.0]
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:153) [hazelcast-5.0.jar:5.0]
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:116) [hazelcast-5.0.jar:5.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_261]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_261]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_261]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76) [hazelcast-5.0.jar:5.0]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) [hazelcast-5.0.jar:5.0]
```

While this precisely describes what's wrong, it might be even more helpful to tell you how to enable it. A briliant example is what happens when you try to access REST API when it's disabled: https://github.com/hazelcast/hazelcast/blob/66c4fbf4932cb0f7ee1b1ae9be116d2fa9b040d8/hazelcast/src/main/java/com/hazelcast/internal/server/tcp/UnifiedProtocolDecoder.java#L106-L112

I propose exactly the same thing as it's really helpful and enhances the user experience.

**Comment by Holmistr** [comment]
Took a shot with the fix proposal: https://github.com/hazelcast/hazelcast/pull/20254

**Comment by Holmistr** [comment]
Moving it to 5.1 as it's a trivial change but we can definitely throw it away if there's no time. It's not urgent.
