### ISSUE TITLE
NPEs when connecting with Mancenter to Cluster

### ISSUE THREAD

**Issue by Mixermachine** [hazelcast/hazelcast#20355]
**Describe the bug**
Connecting with the mancenter to a node only partionally works.
After connecting to my cluster I get NPEs.
![image](https://user-images.githubusercontent.com/1538187/149143171-fdfe686a-adff-44da-9f91-04b84d90c3af.png)

```
2022-01-12 12:39:56,856 [ERROR] [qtp1077072774-44] [c.h.w.c.e.ApiExceptionHandler]: null

java.lang.NullPointerException: null

at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936) ~[?:?]

at com.hazelcast.internal.config.ConfigUtils.getByNameOrNew(ConfigUtils.java:138) ~[hazelcast-management-center-4.2022.01.jar:?]

at com.hazelcast.internal.config.MemberDomConfigProcessor.handleMap(MemberDomConfigProcessor.java:1717) ~[hazelcast-management-center-4.2022.01.jar:?]

at com.hazelcast.internal.config.MemberDomConfigProcessor.handleNode(MemberDomConfigProcessor.java:290) ~[hazelcast-management-center-4.2022.01.jar:?]

at com.hazelcast.internal.config.MemberDomConfigProcessor.buildConfig(MemberDomConfigProcessor.java:255) ~[hazelcast-management-center-4.2022.01.jar:?]

at com.hazelcast.config.XmlConfigBuilder.parseAndBuildConfig(XmlConfigBuilder.java:172) ~[hazelcast-management-center-4.2022.01.jar:?]

at com.hazelcast.config.XmlConfigBuilder.build(XmlConfigBuilder.java:151) ~[hazelcast-management-center-4.2022.01.jar:?]

at com.hazelcast.config.XmlConfigBuilder.build(XmlConfigBuilder.java:144) ~[hazelcast-management-center-4.2022.01.jar:?]

at com.hazelcast.webmonitor.service.memberconfig.MemberConfig.lambda$new$0(MemberConfig.java:74) ~[hazelcast-management-center-4.2022.01.jar:?]

at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:167) ~[hazelcast-management-center-4.2022.01.jar:?]

at com.hazelcast.webmonitor.service.memberconfig.MemberConfig.lambda$new$1(MemberConfig.java:78) ~[hazelcast-management-center-4.2022.01.jar:?]

at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:167) ~[hazelcast-management-center-4.2022.01.jar:?]

at com.hazelcast.webmonitor.service.memberconfig.MemberConfig.parse(MemberConfig.java:90) ~[hazelcast-management-center-4.2022.01.jar:?]

at com.hazelcast.webmonitor.service.MapManager.getMaps(MapManager.java:171) ~[hazelcast-management-center-4.2022.01.jar:?]

at com.hazelcast.webmonitor.controller.internal.MapController.getMaps(MapController.java:100) ~[hazelcast-management-center-4.2022.01.jar:?]

at com.hazelcast.webmonitor.controller.internal.MapController$$FastClassBySpringCGLIB$$4684be05.invoke(<generated>) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688) ~[hazelcast-management-center-4.2022.01.jar:?]

at com.hazelcast.webmonitor.controller.internal.MapController$$EnhancerBySpringCGLIB$$5a438f6f_2.getMaps(<generated>) ~[hazelcast-management-center-4.2022.01.jar:?]

at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]

at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]

at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]

at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]

at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:894) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1063) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898) ~[hazelcast-management-center-4.2022.01.jar:?]

at javax.servlet.http.HttpServlet.service(HttpServlet.java:687) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[hazelcast-management-center-4.2022.01.jar:?]

at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.eclipse.jetty.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1459) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1626) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:327) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:115) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:81) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:121) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:115) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:126) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:81) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:105) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[hazelcast-management-center-4.2022.01.jar:?]

at com.hazelcast.webmonitor.security.DevModeAuthenticationFilter.doFilter(DevModeAuthenticationFilter.java:42) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:149) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:218) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:212) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.springframework.security.web.session.ConcurrentSessionFilter.doFilter(ConcurrentSessionFilter.java:147) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.springframework.security.web.session.ConcurrentSessionFilter.doFilter(ConcurrentSessionFilter.java:125) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:103) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:89) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.springframework.security.web.csrf.CsrfFilter.doFilterInternal(CsrfFilter.java:117) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:110) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:80) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:113) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:55) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:211) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:183) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:201) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:602) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:59) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.eclipse.jetty.server.Server.handle(Server.java:516) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388) ~[hazelcast-management-center-4.2022.01.jar:?]

at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633) [hazelcast-management-center-4.2022.01.jar:?]

at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380) [hazelcast-management-center-4.2022.01.jar:?]

at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277) [hazelcast-management-center-4.2022.01.jar:?]

at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) [hazelcast-management-center-4.2022.01.jar:?]

at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) [hazelcast-management-center-4.2022.01.jar:?]

at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) [hazelcast-management-center-4.2022.01.jar:?]

at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338) [hazelcast-management-center-4.2022.01.jar:?]

at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315) [hazelcast-management-center-4.2022.01.jar:?]

at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173) [hazelcast-management-center-4.2022.01.jar:?]

at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131) [hazelcast-management-center-4.2022.01.jar:?]

at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:386) [hazelcast-management-center-4.2022.01.jar:?]

at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883) [hazelcast-management-center-4.2022.01.jar:?]

at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034) [hazelcast-management-center-4.2022.01.jar:?]

at java.lang.Thread.run(Thread.java:829) [?:?]
```

**Expected behavior**
After connecting to my cluster I don't expect NPEs.

**To Reproduce**

1. Go to Mancenter
2. Create cluster config
3. Connect

**Additional context**

We are using jHipster 7.4. with Spring Boot 2.5.7
Hazelcast versions:
```
...
    implementation "com.hazelcast:hazelcast:4.2.4"
    implementation "com.hazelcast:hazelcast-hibernate53:2.2.1"
    implementation "com.hazelcast:hazelcast-spring:4.2.4"
...
```

Hazelcast mancenter version: 4.2022.01

Am I doing something wrong?

**Comment by promanenko** [comment]
@Mixermachine could you please share your Hazelcast configuration?
And also try MC 5.1.3 instead of 4.2022.01?
MC 5.1 is compatible with 4.2 Hazelcast cluster.
