### ISSUE TITLE
IndexOutOfBoundsException Source offset: 4, length: 164182932, size: 5536 MemoryBlock.copyTo(MemoryBlock.java:201)

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#20411]
more ./output/HZ/HzMember9HZ/exception.txt
```
java.lang.IndexOutOfBoundsException: Source offset: 4, length: 164182932, size: 5536
	at com.hazelcast.internal.memory.MemoryBlock.copyTo(MemoryBlock.java:201)
	at com.hazelcast.internal.serialization.impl.NativeMemoryData.toByteArray(NativeMemoryData.java:77)
	at com.hazelcast.internal.serialization.impl.EnterpriseSerializationServiceV1.convertDataInternal(EnterpriseSerializationServiceV1.java:181)
	at com.hazelcast.internal.serialization.impl.EnterpriseSerializationServiceV1.convertData(EnterpriseSerializationServiceV1.java:148)
	at com.hazelcast.internal.serialization.impl.EnterpriseSerializationServiceV1.toDataInternal(EnterpriseSerializationServiceV1.java:94)
	at com.hazelcast.internal.serialization.impl.EnterpriseSerializationServiceV1.toData(EnterpriseSerializationServiceV1.java:64)
	at com.hazelcast.map.impl.EnterpriseMapServiceContextImpl.toData(EnterpriseMapServiceContextImpl.java:192)
	at com.hazelcast.map.impl.operation.PutOperation.runInternal(PutOperation.java:36)
	at com.hazelcast.map.impl.operation.MapOperation.run(MapOperation.java:117)
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:189)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:276)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:249)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:474)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:197)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:137)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
	at ------ submitted from ------.()
	at com.hazelcast.internal.util.ExceptionUtil.cloneExceptionWithFixedAsyncStackTrace(ExceptionUtil.java:336)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.returnOrThrowWithGetConventions(InvocationFuture.java:112)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:100)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:617)
	at com.hazelcast.map.impl.proxy.MapProxySupport.invokeOperation(MapProxySupport.java:478)
	at com.hazelcast.map.impl.proxy.MapProxySupport.putInternal(MapProxySupport.java:416)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.put(MapProxyImpl.java:138)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.put(MapProxyImpl.java:128)
```

```
WARNING: HybridLog 'imap/mapBak1HDtstore/p197' - Allocation stall 02eba3d8-c1d3-4f7f-9ad2-4db54d174658
Jan 17, 2022 1:51:23 PM com.hazelcast.internal.tstore.hybridlog.impl.HybridLogImpl
WARNING: HybridLog 'imap/mapBak1BINtstore/p220' - Allocation stall 4518b8f7-cbb2-4d64-98c7-0400526aae69
Jan 17, 2022 1:51:23 PM com.hazelcast.internal.tstore.hybridlog.impl.HybridLogImpl
WARNING: HybridLog 'imap/mapBak1HDtstore/p197' - Duration of the 02eba3d8-c1d3-4f7f-9ad2-4db54d174658 allocation stall was 2739936 ns
Jan 17, 2022 1:51:23 PM com.hazelcast.internal.tstore.hybridlog.impl.HybridLogImpl
WARNING: HybridLog 'imap/mapBak1BINtstore/p220' - Duration of the 4518b8f7-cbb2-4d64-98c7-0400526aae69 allocation stall was 200575 ns
java.lang.IndexOutOfBoundsException: Source offset: 4, length: 164182932, size: 5536
	at com.hazelcast.internal.memory.MemoryBlock.copyTo(MemoryBlock.java:201)
	at com.hazelcast.internal.serialization.impl.NativeMemoryData.toByteArray(NativeMemoryData.java:77)
	at com.hazelcast.internal.serialization.impl.EnterpriseSerializationServiceV1.convertDataInternal(EnterpriseSerializationServiceV1.java:181)
	at com.hazelcast.internal.serialization.impl.EnterpriseSerializationServiceV1.convertData(EnterpriseSerializationServiceV1.java:148)
	at com.hazelcast.internal.serialization.impl.EnterpriseSerializationServiceV1.toDataInternal(EnterpriseSerializationServiceV1.java:94)
	at com.hazelcast.internal.serialization.impl.EnterpriseSerializationServiceV1.toData(EnterpriseSerializationServiceV1.java:64)
	at com.hazelcast.map.impl.EnterpriseMapServiceContextImpl.toData(EnterpriseMapServiceContextImpl.java:192)
	at com.hazelcast.map.impl.operation.PutOperation.runInternal(PutOperation.java:36)
	at com.hazelcast.map.impl.operation.MapOperation.run(MapOperation.java:117)
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:189)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:276)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:249)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:474)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:197)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:137)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
	at ------ submitted from ------.()
	at com.hazelcast.internal.util.ExceptionUtil.cloneExceptionWithFixedAsyncStackTrace(ExceptionUtil.java:336)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.returnOrThrowWithGetConventions(InvocationFuture.java:112)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:100)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:617)
	at com.hazelcast.map.impl.proxy.MapProxySupport.invokeOperation(MapProxySupport.java:478)
	at com.hazelcast.map.impl.proxy.MapProxySupport.putInternal(MapProxySupport.java:416)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.put(MapProxyImpl.java:138)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.put(MapProxyImpl.java:128)
	at hzcmd.map.Put.timeStep(Put.java:11)
	at remote.bench.marker.RollMarker.flatOut(RollMarker.java:72)
	at remote.bench.marker.RollMarker.bench(RollMarker.java:59)
	at remote.bench.BenchThread.call(BenchThread.java:41)
	at remote.bench.BenchThread.call(BenchThread.java:14)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Jan 17, 2022 1:51:23 PM com.hazelcast.internal.tstore.hybridlog.impl.HybridLogImpl
WARNING: HybridLog 'imap/mapBak1BINtstore/p209' - Allocation stall 04beca9b-838c-4a7c-b96d-ae6adf3eb9d5
Jan 17, 2022 1:51:23 PM com.hazelcast.internal.tstore.hybridlog.impl.HybridLogImpl
WARNING: HybridLog 'imap/mapBak1BINtstore/p209' - Duration of the 04beca9b-838c-4a7c-b96d-ae6adf3eb9d5 allocation stall was 117934 ns
java.lang.IndexOutOfBoundsException: Source offset: 4, length: 164182932, size: 5536
	at com.hazelcast.internal.memory.MemoryBlock.copyTo(MemoryBlock.java:201)
	at com.hazelcast.internal.serialization.impl.NativeMemoryData.toByteArray(NativeMemoryData.java:77)
	at com.hazelcast.internal.serialization.impl.EnterpriseSerializationServiceV1.convertDataInternal(EnterpriseSerializationServiceV1.java:181)
	at com.hazelcast.internal.serialization.impl.EnterpriseSerializationServiceV1.convertData(EnterpriseSerializationServiceV1.java:148)
	at com.hazelcast.internal.serialization.impl.EnterpriseSerializationServiceV1.toDataInternal(EnterpriseSerializationServiceV1.java:94)
	at com.hazelcast.internal.serialization.impl.EnterpriseSerializationServiceV1.toData(EnterpriseSerializationServiceV1.java:64)
	at com.hazelcast.map.impl.EnterpriseMapServiceContextImpl.toData(EnterpriseMapServiceContextImpl.java:192)
	at com.hazelcast.map.impl.operation.PutOperation.runInternal(PutOperation.java:36)
	at com.hazelcast.map.impl.operation.MapOperation.run(MapOperation.java:117)
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:189)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:276)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:249)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:474)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:197)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:137)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
	at ------ submitted from ------.()
	at com.hazelcast.internal.util.ExceptionUtil.cloneExceptionWithFixedAsyncStackTrace(ExceptionUtil.java:336)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.returnOrThrowWithGetConventions(InvocationFuture.java:112)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:100)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:617)
	at com.hazelcast.map.impl.proxy.MapProxySupport.invokeOperation(MapProxySupport.java:478)
	at com.hazelcast.map.impl.proxy.MapProxySupport.putInternal(MapProxySupport.java:416)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.put(MapProxyImpl.java:138)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.put(MapProxyImpl.java:128)
	at hzcmd.map.Put.timeStep(Put.java:11)
	at remote.bench.marker.RollMarker.flatOut(RollMarker.java:72)
	at remote.bench.marker.RollMarker.bench(RollMarker.java:59)
	at remote.bench.BenchThread.call(BenchThread.java:41)
	at remote.bench.BenchThread.call(BenchThread.java:14)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Jan 17, 2022 1:51:23 PM com.hazelcast.internal.tstore.hybridlog.impl.HybridLogImpl
WARNING: HybridLog 'imap/mapBak1BINtstore/p227' - Allocation stall 1f1a158c-eec2-4150-9761-05a1b601ee4a
Jan 17, 2022 1:51:23 PM com.hazelcast.internal.tstore.hybridlog.impl.HybridLogImpl
WARNING: HybridLog 'imap/mapBak1BINtstore/p227' - Duration of the 1f1a158c-eec2-4150-9761-05a1b601ee4a allocation stall was 102506 ns
Jan 17, 2022 1:51:23 PM com.hazelcast.internal.tstore.hybridlog.impl.HybridLogImpl


```

/nfs/danny/output-tstore-issueQ

 ls -lah ./output/HZ/HzClient2HZ/HzClient2HZ.hprof
-rw------- 1 danny danny 9.7M Jan 17 13:51 ./output/HZ/HzClient2HZ/HzClient2HZ.hprof
cat ./output/HZ/HzClient2HZ/out.txt

```
Jan 17, 2022 1:50:56 PM com.hazelcast.client.impl.connection.ClientConnectionManager
INFO: hz.client_1 [HZ] [5.1-SNAPSHOT] Authenticated with server [10.212.40.101]:5701:488ab889-91e5-46c3-a890-f061e04839b7, server version: 5.1-SNAPSHOT, local address: /10.212.40.102:54670
Jan 17, 2022 1:50:56 PM com.hazelcast.client.impl.connection.ClientConnectionManager
INFO: hz.client_1 [HZ] [5.1-SNAPSHOT] Authenticated with server [10.212.40.108]:5701:9aa5ea4c-c781-4202-8dd9-0976ea0df208, server version: 5.1-SNAPSHOT, local address: /10.212.40.102:43694
java.lang.OutOfMemoryError: Java heap space
Dumping heap to HzClient2HZ.hprof ...
Heap dump file created [10150827 bytes in 0.037 secs]
#
# java.lang.OutOfMemoryError: Java heap space
# -XX:OnOutOfMemoryError=" date >> HzClient2HZ.oome"
#   Executing /bin/sh -c "date >> HzClient2HZ.oome"...
Jan 17, 2022 1:50:56 PM com.hazelcast.client.impl.connection.ClientConnectionManager
SEVERE: hz.client_1 [HZ] [5.1-SNAPSHOT] Java heap space
java.lang.OutOfMemoryError: Java heap space
	at com.hazelcast.client.impl.protocol.ClientMessageReader.readFrame(ClientMessageReader.java:95)
	at com.hazelcast.client.impl.protocol.ClientMessageReader.readFrom(ClientMessageReader.java:43)
	at com.hazelcast.client.impl.protocol.util.ClientMessageDecoder.onRead(ClientMessageDecoder.java:80)
	at com.hazelcast.internal.networking.nio.NioInboundPipeline.process(NioInboundPipeline.java:136)
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKey(NioThread.java:383)
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKeys(NioThread.java:368)
	at com.hazelcast.internal.networking.nio.NioThread.selectLoop(NioThread.java:294)
	at com.hazelcast.internal.networking.nio.NioThread.executeRun(NioThread.java:249)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)

Jan 17, 2022 1:50:56 PM com.hazelcast.client.impl.connection.tcp.TcpClientConnection
WARNING: hz.client_1 [HZ] [5.1-SNAPSHOT] ClientConnection{alive=false, connectionId=4, channel=NioChannel{/10.212.40.102:58535->/10.212.40.107:5701}, remoteAddress=null, lastReadTime=2022-01-17 13:50:56.729, lastWriteTime=2022-01-17 13:50:56.710, closedTime=2022-01-17 13:50:56.821, connected server version=null} closed. Reason: Exception in ClientConnection{alive=true, connectionId=4, channel=NioChannel{/10.212.40.102:58535->/10.212.40.107:5701}, remoteAddress=null, lastReadTime=2022-01-17 13:50:56.729, lastWriteTime=2022-01-17 13:50:56.710, closedTime=never, connected server version=null}, thread=hz.hz.client_1.IO.thread-in-0
java.lang.OutOfMemoryError: Java heap space
	at com.hazelcast.client.impl.protocol.ClientMessageReader.readFrame(ClientMessageReader.java:95)
	at com.hazelcast.client.impl.protocol.ClientMessageReader.readFrom(ClientMessageReader.java:43)
	at com.hazelcast.client.impl.protocol.util.ClientMessageDecoder.onRead(ClientMessageDecoder.java:80)
	at com.hazelcast.internal.networking.nio.NioInboundPipeline.process(NioInboundPipeline.java:136)
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKey(NioThread.java:383)
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKeys(NioThread.java:368)
	at com.hazelcast.internal.networking.nio.NioThread.selectLoop(NioThread.java:294)
	at com.hazelcast.internal.networking.nio.NioThread.executeRun(NioThread.java:249)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)

Jan 17, 2022 1:50:56 PM com.hazelcast.client.impl.connection.ClientConnectionManager
INFO: hz.client_1 [HZ] [5.1-SNAPSHOT] Authenticated with server [10.212.40.109]:5701:a6a876de-cc44-40ee-bad4-52e1b38c1146, server version: 5.1-SNAPSHOT, local address: /10.212.40.102:36764
```

**Comment by Danny-Hazelcast** [comment]
hz-ssh 'cd  /datadisk/danny; du -hs * | sort -h'
ssh danny@10.212.1.101 'cd  /datadisk/danny; du -hs * | sort -h'
54G	tiered-store

ssh danny@10.212.1.102 'cd  /datadisk/danny; du -hs * | sort -h'
155G	tiered-store

ssh danny@10.212.1.103 'cd  /datadisk/danny; du -hs * | sort -h'
159G	tiered-store

ssh danny@10.212.1.104 'cd  /datadisk/danny; du -hs * | sort -h'
162G	tiered-store

ssh danny@10.212.1.105 'cd  /datadisk/danny; du -hs * | sort -h'
162G	tiered-store

ssh danny@10.212.1.106 'cd  /datadisk/danny; du -hs * | sort -h'
156G	tiered-store

ssh danny@10.212.1.107 'cd  /datadisk/danny; du -hs * | sort -h'
156G	tiered-store

ssh danny@10.212.1.108 'cd  /datadisk/danny; du -hs * | sort -h'
157G	tiered-store

ssh danny@10.212.1.109 'cd  /datadisk/danny; du -hs * | sort -h'
159G	tiered-store

**Comment by Danny-Hazelcast** [comment]
/nfs/danny/output-tstore-issueQ

**Comment by Danny-Hazelcast** [comment]
5.1-SNAPSHOT (20220116 - dbfcd9d, f373d8e)
