### ISSUE TITLE
ShowStatementTest.test_showJobsEmpty

### ISSUE THREAD

**Issue by mdumandag** [hazelcast/hazelcast#20426]
PR builder against master (commit 58bcc8925f55ca806a180a003cf725ccbbbc9758)

https://jenkins.hazelcast.com/job/Hazelcast-pr-builder/9276/testReport/junit/com.hazelcast.jet.sql.impl/ShowStatementTest/test_showJobsEmpty/

<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: 

Expecting:
  <[Row{[testJob]}]>
to contain exactly (and in same order):
  <[]>
but some elements were not expected:
  <[Row{[testJob]}]>

	at com.hazelcast.jet.sql.SqlTestSupport.assertRowsOrdered(SqlTestSupport.java:279)
	at com.hazelcast.jet.sql.impl.ShowStatementTest.test_showJobsEmpty(ShowStatementTest.java:115)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: test_showJobs in 0.053 seconds.
Started Running Test: test_showJobsEmpty
BuildInfo right after test_showJobsEmpty(com.hazelcast.jet.sql.impl.ShowStatementTest): BuildInfo{version='5.1-SNAPSHOT', build='20220119', buildNumber=20220119, revision=3a2aafc, enterprise=false, serializationVersion=1}
11:06:00,577 ERROR || - [EventServiceImpl] hz.happy_bhabha.event-34 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] hz.happy_bhabha.event-34 caught an exception while processing:com.hazelcast.spi.impl.eventservice.impl.LocalEventDispatcher@50270f54
java.lang.UnsupportedOperationException: SQL catalog must never be cleared - MapEvent{entryEventType=CLEAR_ALL, member=Member [127.0.0.1]:5701 - 78f8f138-1e6f-48e6-b7b7-d53d90d6da25 this, name='__sql.catalog', numberOfEntriesAffected=0}
	at com.hazelcast.jet.sql.impl.schema.TablesStorage$EntryListenerAdapter.mapCleared(TablesStorage.java:202) ~[classes/:?]
	at com.hazelcast.replicatedmap.impl.ReplicatedMapEventPublishingService.dispatchEvent(ReplicatedMapEventPublishingService.java:132) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.replicatedmap.impl.ReplicatedMapService.dispatchEvent(ReplicatedMapService.java:232) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.spi.impl.eventservice.impl.LocalEventDispatcher.run(LocalEventDispatcher.java:64) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.internal.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:245) [hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.internal.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:228) [hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
Hiccups measured while running test 'test_showJobsEmpty(com.hazelcast.jet.sql.impl.ShowStatementTest):'
11:06:00, accumulated pauses: 343 ms, max pause: 263 ms, pauses over 1000 ms: 0
```

</details>

**Comment by Fly-Style** [comment]
It sounds like a glitch coupled with some parallel Jet job ... Didn't reproduce it, will close an issue.
I will re-open it if failure happens again.

**Comment by olukas** [comment]
Reopeninng since it failed again in PR builder: https://jenkins.hazelcast.com/job/Hazelcast-pr-builder/10106/testReport/com.hazelcast.jet.sql.impl/ShowStatementTest/when_unnamedJob_then_notListed/
