### ISSUE TITLE
Future.complete(Object) on completed future when canceling task with FencedLock

### ISSUE THREAD

**Issue by roytmana** [hazelcast/hazelcast#20462]
Output for the code below:
```
Locking  Thread[pool-1-thread-1,5,main]
24 Locked  Thread[pool-1-thread-1,5,main]
2011 Canceling Task 1
2011 Task 1 Canceled
2011 Sleep interrupted  Thread[pool-1-thread-1,5,main]
Jan 21, 2022 3:54:46 PM com.hazelcast.client.impl.spi.ClientInvocationService
WARNING: hz.client_1 [racdw] [5.0.2] Future.complete(Object) on completed future. Request: ClientMessage{connection=null, length=115, operation=FencedLock.Unlock, isRetryable=true, correlationId=14, messageType=70300, isEvent=false, isfragmented=false}, current value: ExceptionalResult{cause=java.lang.InterruptedException}, offered value: ClientMessage{connection=ClientConnection{alive=true, connectionId=1, channel=NioChannel{/127.0.0.1:56858->/127.0.0.1:5701}, remoteAddress=[10.0.75.1]:5701, lastReadTime=2022-01-21 15:54:46.550, lastWriteTime=2022-01-21 15:54:46.550, closedTime=never, connected server version=5.0.2}, length=20, operation=null, isRetryable=false, correlationId=14, messageType=70301, isEvent=false, isfragmented=false}
java.lang.Exception
	at com.hazelcast.spi.impl.AbstractInvocationFuture.warnIfSuspiciousDoubleCompletion(AbstractInvocationFuture.java:1253)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.complete0(AbstractInvocationFuture.java:1230)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.complete(AbstractInvocationFuture.java:1219)
	at com.hazelcast.client.impl.spi.impl.ClientInvocation.complete(ClientInvocation.java:290)
	at com.hazelcast.spi.impl.operationservice.impl.BaseInvocation.notifyResponse(BaseInvocation.java:106)
	at com.hazelcast.client.impl.spi.impl.ClientInvocation.notify(ClientInvocation.java:255)
	at com.hazelcast.client.impl.spi.impl.ClientResponseHandlerSupplier.handleResponse(ClientResponseHandlerSupplier.java:166)
	at com.hazelcast.client.impl.spi.impl.ClientResponseHandlerSupplier.process(ClientResponseHandlerSupplier.java:141)
	at com.hazelcast.client.impl.spi.impl.ClientResponseHandlerSupplier.access$300(ClientResponseHandlerSupplier.java:60)
	at com.hazelcast.client.impl.spi.impl.ClientResponseHandlerSupplier$DynamicResponseHandler.accept(ClientResponseHandlerSupplier.java:251)
	at com.hazelcast.client.impl.spi.impl.ClientResponseHandlerSupplier$DynamicResponseHandler.accept(ClientResponseHandlerSupplier.java:243)
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnection.handleClientMessage(TcpClientConnection.java:245)
	at com.hazelcast.client.impl.protocol.util.ClientMessageDecoder.handleMessage(ClientMessageDecoder.java:133)
	at com.hazelcast.client.impl.protocol.util.ClientMessageDecoder.onRead(ClientMessageDecoder.java:88)
	at com.hazelcast.internal.networking.nio.NioInboundPipeline.process(NioInboundPipeline.java:136)
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKey(NioThread.java:383)
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKeys(NioThread.java:368)
	at com.hazelcast.internal.networking.nio.NioThread.selectLoop(NioThread.java:294)
	at com.hazelcast.internal.networking.nio.NioThread.executeRun(NioThread.java:249)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)

task1=Cancelled
```

```
void threadLockTest() throws InterruptedException, ExecutionException {
    long startTime = System.currentTimeMillis();
    final Callable<Boolean> callable1 = new ThreadLockTestCallable(startTime);
    final Future<Boolean> task1 = executorService.submit(callable1);
    Thread.sleep(1000);
    System.out.println((System.currentTimeMillis()-startTime)+" Canceling Task 1");
    task1.cancel(true);
    System.out.println((System.currentTimeMillis()-startTime)+" Task 1 Canceled");
    Thread.sleep(1000);
    System.out.println("task1=" + (task1.isCancelled() ? "Cancelled" : task1.get()));
  }
```

```
  private class ThreadLockTestCallable implements Callable<Boolean> {
    private final long startTime;

    public ThreadLockTestCallable(long startTime) {
      this.startTime = startTime;
    }

    @Override public Boolean call() throws Exception {
      System.out.println("Locking  " + Thread.currentThread());
      final FencedLock hz1Lock = hz1.getCPSubsystem().getLock("/test/1");
      try {
        hz1Lock.lock();
      } catch (HazelcastException e) {
        if (e.getCause() instanceof  InterruptedException) {
          Thread.currentThread().interrupt();
          System.out.println((System.currentTimeMillis() - startTime) + " Lock interrupted  " + Thread.currentThread());
          return false;
        }
        throw e;
      }
      try {
        System.out.println((System.currentTimeMillis() - startTime) + " Locked  " + Thread.currentThread());
        try {
          Thread.sleep(10000);
        } catch (InterruptedException e) {
          System.out.println((System.currentTimeMillis() - startTime) + " Sleep interrupted  " + Thread.currentThread());
          Thread.currentThread().interrupt();
          return false;
        }
      } finally {
        hz1Lock.unlock();
        System.out.println((System.currentTimeMillis() - startTime) + " Unlocked  " + Thread.currentThread());
      }
      return true;
    }
  }
```

**Comment by Holmistr** [comment]
@sancar Any thoughts?
