### ISSUE TITLE
com.hazelcast.instance.impl.DefaultAddressPickerTest.testBindAddress_withDefaultPortAndLoopbackAddress

### ISSUE THREAD

**Issue by slavagithub** [hazelcast/hazelcast#20470]
_5.0.z_ (commit 66205d3ebb195e129fb552d88a11730c16ca0851)

Failed on Zulu, JDK16 : [test failure](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-ZuluJDK16/18/testReport/com.hazelcast.instance.impl/DefaultAddressPickerTest/testBindAddress_withDefaultPortAndLoopbackAddress/)

<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: expected:<[127.0.0.1]:5701> but was:<[127.0.0.1]:5702>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:120)
	at org.junit.Assert.assertEquals(Assert.java:146)
	at com.hazelcast.instance.impl.DefaultAddressPickerTest.testBindAddress(DefaultAddressPickerTest.java:171)
	at com.hazelcast.instance.impl.DefaultAddressPickerTest.testBindAddress_withDefaultPortAndLoopbackAddress(DefaultAddressPickerTest.java:99)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:831)
```

</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: testBindAddress_withEphemeralPort in 0.001 seconds.
Started Running Test: testBindAddress_withDefaultPortAndLoopbackAddress
```

</details>

**Comment by vbekiaris** [comment]
Seems similar to #19856 test failure but on `5.0.z` branch.
