### ISSUE TITLE
com.hazelcast.internal.serialization.impl.ObjectDataInputStreamFinalMethodsTest [HZ-915]

### ISSUE THREAD

**Issue by slavagithub** [hazelcast/hazelcast#20505]
_master_ (commit efcf053337828559160eb217231c7f0c914b8005)

Failed on Oracle, JDK11: [failure report](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/1111/testReport/com.hazelcast.internal.serialization.impl/ObjectDataInputStreamFinalMethodsTest/testReadBooleanArray/)

<details><summary>Stacktrace:</summary>

```
java.lang.reflect.InaccessibleObjectException: Unable to make field protected int java.io.ByteArrayInputStream.count accessible: module java.base does not "opens java.io" to unnamed module @149494d8
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:340)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:280)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:176)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:170)
	at org.powermock.reflect.internal.WhiteboxImpl.getField(WhiteboxImpl.java:210)
	at org.powermock.core.MockGateway.fieldCall(MockGateway.java:95)
	at com.hazelcast.internal.serialization.impl.ObjectDataInputStreamFinalMethodsTest$InitableByteArrayInputStream.position(ObjectDataInputStreamFinalMethodsTest.java:362)
	at com.hazelcast.internal.serialization.impl.ObjectDataInputStreamFinalMethodsTest.testReadBooleanArray(ObjectDataInputStreamFinalMethodsTest.java:168)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.internal.runners.TestMethod.invoke(TestMethod.java:68)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.runTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:326)
	at org.junit.internal.runners.MethodRoadie$2.run(MethodRoadie.java:89)
	at org.junit.internal.runners.MethodRoadie.runBeforesThenTestThenAfters(MethodRoadie.java:97)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.executeTest(PowerMockJUnit44RunnerDelegateImpl.java:310)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTestInSuper(PowerMockJUnit47RunnerDelegateImpl.java:131)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.access$100(PowerMockJUnit47RunnerDelegateImpl.java:59)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner$TestExecutorStatement.evaluate(PowerMockJUnit47RunnerDelegateImpl.java:147)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.evaluateStatement(PowerMockJUnit47RunnerDelegateImpl.java:107)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTest(PowerMockJUnit47RunnerDelegateImpl.java:82)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.runBeforesThenTestThenAfters(PowerMockJUnit44RunnerDelegateImpl.java:298)
	at org.junit.internal.runners.MethodRoadie.runTest(MethodRoadie.java:87)
	at org.junit.internal.runners.MethodRoadie.run(MethodRoadie.java:50)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.invokeTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:218)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.runMethods(PowerMockJUnit44RunnerDelegateImpl.java:160)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$1.run(PowerMockJUnit44RunnerDelegateImpl.java:134)
	at org.junit.internal.runners.ClassRoadie.runUnprotected(ClassRoadie.java:34)
	at org.junit.internal.runners.ClassRoadie.runProtected(ClassRoadie.java:44)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.run(PowerMockJUnit44RunnerDelegateImpl.java:136)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.run(JUnit4TestSuiteChunkerImpl.java:117)
	at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.run(AbstractCommonPowerMockRunner.java:57)
	at org.powermock.modules.junit4.PowerMockRunner.run(PowerMockRunner.java:59)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:107)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:83)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
```

</details>

<details><summary>Standard output:</summary>

```
2022-01-26 01:07:27,041 main ERROR Could not reconfigure JMX java.lang.LinkageError: loader constraint violation: loader org.powermock.core.classloader.javassist.JavassistMockClassLoader @2e0ac425 (instance of org.powermock.core.classloader.javassist.JavassistMockClassLoader, child of 'app' jdk.internal.loader.ClassLoaders$AppClassLoader) wants to load interface javax.management.MBeanServer. A different interface with the same name was previously loaded by 'bootstrap'.
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at org.powermock.core.classloader.javassist.JavassistMockClassLoader.loadUnmockedClass(JavassistMockClassLoader.java:90)
	at org.powermock.core.classloader.MockClassLoader.loadClassByThisClassLoader(MockClassLoader.java:104)
	at org.powermock.core.classloader.DeferSupportingClassLoader.loadClass1(DeferSupportingClassLoader.java:147)
	at org.powermock.core.classloader.DeferSupportingClassLoader.loadClass(DeferSupportingClassLoader.java:98)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at org.apache.logging.log4j.core.jmx.Server.unregisterAllMatching(Server.java:337)
	at org.apache.logging.log4j.core.jmx.Server.unregisterLoggerContext(Server.java:261)
	at org.apache.logging.log4j.core.jmx.Server.reregisterMBeansAfterReconfigure(Server.java:165)
	at org.apache.logging.log4j.core.jmx.Server.reregisterMBeansAfterReconfigure(Server.java:141)
	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:637)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:699)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:716)
	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:270)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:245)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:47)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:240)
	at com.hazelcast.test.TestLoggerFactory.createLogger(TestLoggerFactory.java:83)
	at com.hazelcast.internal.util.ConcurrencyUtil.getOrPutIfAbsent(ConcurrencyUtil.java:154)
	at com.hazelcast.logging.LoggerFactorySupport.getLogger(LoggerFactorySupport.java:42)
	at com.hazelcast.logging.Logger.getLoggerInternal(Logger.java:88)
	at com.hazelcast.logging.Logger.getLogger(Logger.java:69)
	at com.hazelcast.internal.util.JavaVersion.detectCurrentVersion(JavaVersion.java:103)
	at com.hazelcast.internal.util.JavaVersion.<clinit>(JavaVersion.java:51)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at javassist.runtime.Desc.getClassObject(Desc.java:72)
	at javassist.runtime.Desc.getClazz(Desc.java:81)
	at com.hazelcast.internal.serialization.impl.ObjectDataInputStreamFinalMethodsTest.before(ObjectDataInputStreamFinalMethodsTest.java:66)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.internal.runners.MethodRoadie.runBefores(MethodRoadie.java:133)
	at org.junit.internal.runners.MethodRoadie.runBeforesThenTestThenAfters(MethodRoadie.java:96)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.executeTest(PowerMockJUnit44RunnerDelegateImpl.java:310)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTestInSuper(PowerMockJUnit47RunnerDelegateImpl.java:131)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.access$100(PowerMockJUnit47RunnerDelegateImpl.java:59)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner$TestExecutorStatement.evaluate(PowerMockJUnit47RunnerDelegateImpl.java:147)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.evaluateStatement(PowerMockJUnit47RunnerDelegateImpl.java:107)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTest(PowerMockJUnit47RunnerDelegateImpl.java:82)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.runBeforesThenTestThenAfters(PowerMockJUnit44RunnerDelegateImpl.java:298)
	at org.junit.internal.runners.MethodRoadie.runTest(MethodRoadie.java:87)
	at org.junit.internal.runners.MethodRoadie.run(MethodRoadie.java:50)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.invokeTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:218)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.runMethods(PowerMockJUnit44RunnerDelegateImpl.java:160)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$1.run(PowerMockJUnit44RunnerDelegateImpl.java:134)
	at org.junit.internal.runners.ClassRoadie.runUnprotected(ClassRoadie.java:34)
	at org.junit.internal.runners.ClassRoadie.runProtected(ClassRoadie.java:44)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.run(PowerMockJUnit44RunnerDelegateImpl.java:136)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.run(JUnit4TestSuiteChunkerImpl.java:117)
	at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.run(AbstractCommonPowerMockRunner.java:57)
	at org.powermock.modules.junit4.PowerMockRunner.run(PowerMockRunner.java:59)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:107)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:83)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)

Started Running Test: testLoad_withParametrizedConstructor
```

</details>

**Comment by slavagithub** [comment]
the same issue for java.util on  JKD11 for com.hazelcast.internal.serialization.impl.ObjectDataInputStreamFinalMethodsTest.testSkipBytes - http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/1111/testReport/com.hazelcast.internal.serialization.impl/ObjectDataInputStreamFinalMethodsTest/testSkipBytes/

**Comment by slavagithub** [comment]
The same for Zulu, JDK11 - http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZuluJDK11/170/testReport/

**Comment by slavagithub** [comment]
The same for RedHat, JDK11 - http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-RedHatJDK11/16/testReport/
@ldziedziul just FYI, this is regarding java.io not opened

**Comment by slavagithub** [comment]
and one test fails due to not opening java.util - com.hazelcast.internal.serialization.impl.ObjectDataInputStreamFinalMethodsTest.testSkipBytes - http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-RedHatJDK11/16/testReport/com.hazelcast.internal.serialization.impl/ObjectDataInputStreamFinalMethodsTest/testSkipBytes/

**Comment by slavagithub** [comment]
Also failed on Corretto, JDK11 - http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-CorrettoJDK11/155/testReport/

**Comment by olukas** [comment]
11 tests from `com.hazelcast.internal.serialization.impl.ObjectDataInputStreamFinalMethodsTest` Fail also on:
- OracleJDK11 - https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-OracleJDK11/307/testReport/com.hazelcast.internal.serialization.impl/ObjectDataInputStreamFinalMethodsTest/
- Sonar build (OracleJDK11) - https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/1116/testReport/com.hazelcast.internal.serialization.impl/ObjectDataInputStreamFinalMethodsTest/
- Openj9-11 - https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Openj9-11/64/testReport/com.hazelcast.internal.serialization.impl/ObjectDataInputStreamFinalMethodsTest/

**Comment by olukas** [comment]
Failed on Corretto JDK 11: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-CorrettoJDK11/156/testReport/com.hazelcast.internal.serialization.impl/ObjectDataInputStreamFinalMethodsTest/

**Comment by olukas** [comment]
Failed on:
- ZuluJDK11: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZuluJDK11/171/testReport/com.hazelcast.internal.serialization.impl/ObjectDataInputStreamFinalMethodsTest/
- Sonar build (Oracle JDK 11): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/1118/testReport/com.hazelcast.internal.serialization.impl/ObjectDataInputStreamFinalMethodsTest/

**Comment by olukas** [comment]
Failed on:
- Sonar build (Oracle JDK 11): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/1123/testReport/com.hazelcast.internal.serialization.impl/ObjectDataInputStreamFinalMethodsTest/
- Oracle JDK 11: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-OracleJDK11/308/testReport/com.hazelcast.internal.serialization.impl/ObjectDataInputStreamFinalMethodsTest/
- Openj9-11: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Openj9-11/65/testReport/com.hazelcast.internal.serialization.impl/ObjectDataInputStreamFinalMethodsTest/

**Comment by slavagithub** [comment]
still failed for RedHat, JDK11 - http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-RedHatJDK11/19/testReport/

**Comment by slavagithub** [comment]
failed on master, Corretto JDK11 - http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-CorrettoJDK11/159/testReport/

**Comment by slavagithub** [comment]
failed on master, Oracle, JDK11 - http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/1137/testReport/com.hazelcast.internal.serialization.impl/ObjectDataInputStreamFinalMethodsTest/testReadIntArray/

**Comment by slavagithub** [comment]
failed on Zulu, JDK11 - http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZuluJDK11/174/testReport/com.hazelcast.internal.serialization.impl/ObjectDataInputStreamFinalMethodsTest/testReadLongArray/
