### ISSUE TITLE
Failure in SqlKafkaAggregateTest

### ISSUE THREAD

**Issue by frant-hartm** [hazelcast/hazelcast#20507]
commit f9002e8bbc5aa31f71e4a292b76ab58268a6f33b

Failed on pr builder https://github.com/hazelcast/hazelcast/pull/20458#issuecomment-1022166655

<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: 

Expecting:
  <[Row{[0, 2, 1]}]>
to contain exactly in any order:
  <[Row{[0, 2, 2]}, Row{[2, 4, 1]}]>
elements not found:
  <[Row{[0, 2, 2]}, Row{[2, 4, 1]}]>
and elements not expected:
  <[Row{[0, 2, 1]}]>

	at com.hazelcast.jet.sql.SqlTestSupport.assertRowsEventuallyInAnyOrder(SqlTestSupport.java:194)
	at com.hazelcast.jet.sql.SqlTestSupport.assertRowsEventuallyInAnyOrder(SqlTestSupport.java:147)
	at com.hazelcast.jet.sql.impl.connector.kafka.SqlKafkaAggregateTest.test(SqlKafkaAggregateTest.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)

```

</details>

<details><summary>Standard output:</summary>

```
12:45:24,128  INFO || - [MetricsConfigHelper] Time-limited test - [LOCAL] [dev] [5.1-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
12:45:24,130  INFO || - [logo] Time-limited test - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
12:45:24,130  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Copyright (c) 2008-2021, Hazelcast, Inc. All Rights Reserved.
12:45:24,130  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Hazelcast Platform 5.1-SNAPSHOT (20220126 - b7681b1) starting at [127.0.0.1]:5701
12:45:24,130  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Cluster name: dev
12:45:24,130  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed.
To enable integrity checker do one of the following: 
  - Change member config using Java API: config.setIntegrityCheckerEnabled(true);;
  - Change XML/YAML configuration property: Set hazelcast.integrity-checker.enabled to true
  - Add system property: -Dhz.integritychecker.enabled=true
  - Add environment variable: HZ_INTEGRITYCHECKER_ENABLED=true
12:45:24,130  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Jet is enabled
12:45:24,135  INFO || - [MetricsConfigHelper] Time-limited test - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
12:45:24,141  WARN || - [CPSubsystem] Time-limited test - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
12:45:24,147  INFO || - [JetServiceBackend] Time-limited test - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Setting number of cooperative threads and default parallelism to 2
12:45:24,149  INFO || - [Diagnostics] Time-limited test - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
12:45:24,149  INFO || - [LifecycleService] Time-limited test - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] [127.0.0.1]:5701 is STARTING
12:45:24,150  INFO || - [ClusterService] Time-limited test - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] 

Members {size:1, ver:1} [
	Member [127.0.0.1]:5701 - e4c3b490-e244-4633-9219-d884c9aaa576 this
]

12:45:24,150  INFO || - [JobCoordinationService] Time-limited test - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Jet started scanning for jobs
12:45:24,150 DEBUG || - [JobCoordinationService] hz.hungry_ellis.cached.thread-1 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
12:45:24,150  INFO || - [LifecycleService] Time-limited test - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] [127.0.0.1]:5701 is STARTED
12:45:24,153  INFO || - [HealthMonitor] hz.hungry_ellis.HealthMonitor - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] processors=16, physical.memory.total=377.6G, physical.memory.free=91.2G, swap.space.total=4.0G, swap.space.free=3.9G, heap.memory.used=220.8M, heap.memory.free=888.2M, heap.memory.total=1.1G, heap.memory.max=1.8G, heap.memory.used/total=19.81%, heap.memory.used/max=12.07%, minor.gc.count=10, minor.gc.time=527ms, major.gc.count=4, major.gc.time=878ms, load.process=6.67%, load.system=100.00%, load.systemAverage=38.23, thread.count=47, thread.peakCount=138, cluster.timeDiff=0, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=0, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=1, clientEndpoint.count=0, connection.active.count=0, client.connection.count=0, connection.count=0
12:45:24,250 DEBUG || - [JobCoordinationService] hz.hungry_ellis.cached.thread-1 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
Started Running Test: test
12:45:24,330  INFO |test| - [PartitionStateManager] test - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Initializing cluster partition table arrangement...
12:45:24,338 DEBUG |test| - [CalciteSqlOptimizer] test - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Before logical opt:
LogicalTableInsert(table=[[hazelcast, public, o_c2ab65c5_3f74_4ac2_930e_8a94e585acda[projects=[0, 1]]]], operation=[INSERT], flattened=[false])
  LogicalValues(tuples=[[{ 0, _UTF-16LE'value-0' }, { 1, _UTF-16LE'value-1' }, { 2, _UTF-16LE'value-2' }, { 10, _UTF-16LE'value-10' }]])

12:45:24,339 DEBUG |test| - [CalciteSqlOptimizer] test - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] After logical opt:
InsertLogicalRel(table=[[hazelcast, public, o_c2ab65c5_3f74_4ac2_930e_8a94e585acda[projects=[0, 1]]]], operation=[INSERT], flattened=[false])
  ValuesLogicalRel(values=[{expressions=[[ConstantExpression{type=QueryDataType {family=INTEGER}, value=0}, ConstantExpression{type=QueryDataType {family=VARCHAR}, value=value-0}], [ConstantExpression{type=QueryDataType {family=INTEGER}, value=1}, ConstantExpression{type=QueryDataType {family=VARCHAR}, value=value-1}], [ConstantExpression{type=QueryDataType {family=INTEGER}, value=2}, ConstantExpression{type=QueryDataType {family=VARCHAR}, value=value-2}], [ConstantExpression{type=QueryDataType {family=INTEGER}, value=10}, ConstantExpression{type=QueryDataType {family=VARCHAR}, value=value-10}]]}])

12:45:24,340 DEBUG |test| - [CalciteSqlOptimizer] test - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] After physical opt:
InsertPhysicalRel(table=[[hazelcast, public, o_c2ab65c5_3f74_4ac2_930e_8a94e585acda[projects=[0, 1]]]], operation=[INSERT], flattened=[false])
  ValuesPhysicalRel(values=[{expressions=[[ConstantExpression{type=QueryDataType {family=INTEGER}, value=0}, ConstantExpression{type=QueryDataType {family=VARCHAR}, value=value-0}], [ConstantExpression{type=QueryDataType {family=INTEGER}, value=1}, ConstantExpression{type=QueryDataType {family=VARCHAR}, value=value-1}], [ConstantExpression{type=QueryDataType {family=INTEGER}, value=2}, ConstantExpression{type=QueryDataType {family=VARCHAR}, value=value-2}], [ConstantExpression{type=QueryDataType {family=INTEGER}, value=10}, ConstantExpression{type=QueryDataType {family=VARCHAR}, value=value-10}]]}])

12:45:24,342 DEBUG |test| - [LightMasterContext] test - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Start executing light job 0779-d9b1-fd40-0001, execution graph in DOT format:
digraph DAG {
	"Values" [localParallelism=1];
	"Project(Kafka[public.o_c2ab65c5_3f74_4ac2_930e_8a94e585acda])" [localParallelism=default];
	"Kafka[public.o_c2ab65c5_3f74_4ac2_930e_8a94e585acda]" [localParallelism=1];
	"Values" -> "Project(Kafka[public.o_c2ab65c5_3f74_4ac2_930e_8a94e585acda])" [queueSize=1024];
	"Project(Kafka[public.o_c2ab65c5_3f74_4ac2_930e_8a94e585acda])" -> "Kafka[public.o_c2ab65c5_3f74_4ac2_930e_8a94e585acda]" [queueSize=1024];
}
HINT: You can use graphviz or http://viz-js.com to visualize the printed graph.
12:45:24,342 DEBUG |test| - [LightMasterContext] test - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Building execution plan for 0779-d9b1-fd40-0001
12:45:24,343 DEBUG |test| - [LightMasterContext] test - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Built execution plans for 0779-d9b1-fd40-0001
12:45:24,343 DEBUG |test| - [InitExecutionOperation] test - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Initializing execution plan for job 0779-d9b1-fd40-0001, execution 0779-d9b1-fd40-0001 from [127.0.0.1]:5701
12:45:24,345 DEBUG |test| - [JobExecutionService] test - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Execution plan for light job ID=0779-d9b1-fd40-0001, jobName='0779-d9b1-fd40-0001', executionId=0779-d9b1-fd40-0001 initialized, will start the execution
12:45:24,346 DEBUG |test| - [WriteKafkaP] hz.hungry_ellis.jet.blocking.thread-1 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] [0779-d9b1-fd40-0001/Kafka[public.o_c2ab65c5_3f74_4ac2_930e_8a94e585acda]#0] Actual pool size used: 1
12:45:24,351 DEBUG || - [JobRepository] hz.hungry_ellis.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Job cleanup took 0ms
12:45:24,362 DEBUG |test| - [WriteKafkaP] hz.hungry_ellis.jet.blocking.thread-1 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] [0779-d9b1-fd40-0001/Kafka[public.o_c2ab65c5_3f74_4ac2_930e_8a94e585acda]#0] release null
12:45:24,363 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-2 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Completed execution of job '0779-d9b1-fd40-0001', execution 0779-d9b1-fd40-0001
12:45:24,363 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-2 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Execution of job '0779-d9b1-fd40-0001', execution 0779-d9b1-fd40-0001 completed
12:45:24,430 DEBUG |test| - [CalciteSqlOptimizer] Thread-71 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Before logical opt:
LogicalAggregate(group=[{0, 1}], EXPR$2=[COUNT()])
  LogicalProject(window_start=[$2], window_end=[$3])
    LogicalTableFunctionScan(invocation=[TUMBLE($1, DESCRIPTOR($0), 2:TINYINT(2))], rowType=[RecordType(INTEGER __key, VARCHAR this, INTEGER window_start, INTEGER window_end)])
      LogicalProject(__key=[$0], this=[$1])
        LogicalTableFunctionScan(invocation=[IMPOSE_ORDER($1, DESCRIPTOR($0), 2:TINYINT(2))], rowType=[RecordType(INTEGER __key, VARCHAR this)])
          LogicalProject(__key=[$0], this=[$1])
            LogicalTableScan(table=[[hazelcast, public, o_c2ab65c5_3f74_4ac2_930e_8a94e585acda[projects=[0, 1]]]])

12:45:24,437 DEBUG |test| - [CalciteSqlOptimizer] Thread-71 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] After logical opt:
AggregateLogicalRel(group=[{0, 1}], EXPR$2=[COUNT()])
  ProjectLogicalRel(window_start=[$2], window_end=[$3])
    SlidingWindowLogicalRel(invocation=[TUMBLE($1, DESCRIPTOR($0), 2:TINYINT(2))], rowType=[RecordType(INTEGER __key, VARCHAR this, INTEGER window_start, INTEGER window_end)])
      FullScanLogicalRel(table=[[hazelcast, public, o_c2ab65c5_3f74_4ac2_930e_8a94e585acda[projects=[0, 1]]]], eventTimePolicyProvider=[com.hazelcast.jet.sql.impl.opt.logical.WatermarkRules$1$$Lambda$4000/1930066457@37463708])

12:45:24,463 DEBUG |test| - [CalciteSqlOptimizer] Thread-71 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] After physical opt:
SlidingWindowAggregateCombineByKeyPhysicalRel(group=[{0, 1}], EXPR$2=[COUNT()])
  SlidingWindowAggregateAccumulateByKeyPhysicalRel(group=[{0, 1}])
    ProjectPhysicalRel(window_start=[$2], window_end=[$3])
      SlidingWindowPhysicalRel(invocation=[TUMBLE($1, DESCRIPTOR($0), 2:TINYINT(2))], rowType=[RecordType(INTEGER __key, VARCHAR this, INTEGER window_start, INTEGER window_end)])
        FullScanPhysicalRel(table=[[hazelcast, public, o_c2ab65c5_3f74_4ac2_930e_8a94e585acda[projects=[0, 1]]]], eventTimePolicyProvider=[com.hazelcast.jet.sql.impl.opt.logical.WatermarkRules$1$$Lambda$4000/1930066457@37463708])

12:45:24,484 DEBUG |test| - [LightMasterContext] Thread-71 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Start executing light job 0779-d9b1-fd41-0001, execution graph in DOT format:
digraph DAG {
	"Kafka[public.o_c2ab65c5_3f74_4ac2_930e_8a94e585acda]" [localParallelism=4];
	"Sliding-Window" [localParallelism=default];
	"Project" [localParallelism=default];
	"Sliding-Window-AccumulateByKey" [localParallelism=default];
	"Sliding-Window-CombineByKey" [localParallelism=default];
	"ClientSink" [localParallelism=1];
	"Kafka[public.o_c2ab65c5_3f74_4ac2_930e_8a94e585acda]" -> "Sliding-Window" [queueSize=1024];
	"Sliding-Window" -> "Project" [queueSize=1024];
	"Project" -> "Sliding-Window-AccumulateByKey" [label="partitioned", queueSize=1024];
	"Sliding-Window-AccumulateByKey" -> "Sliding-Window-CombineByKey" [label="distributed-partitioned", queueSize=1024];
	"Sliding-Window-CombineByKey" -> "ClientSink" [label="distributed to [127.0.0.1]:5701-partitioned", queueSize=1024];
}
HINT: You can use graphviz or http://viz-js.com to visualize the printed graph.
12:45:24,484 DEBUG |test| - [LightMasterContext] Thread-71 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Building execution plan for 0779-d9b1-fd41-0001
12:45:24,484 DEBUG |test| - [LightMasterContext] Thread-71 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Built execution plans for 0779-d9b1-fd41-0001
12:45:24,491 DEBUG |test| - [InitExecutionOperation] Thread-71 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Initializing execution plan for job 0779-d9b1-fd41-0001, execution 0779-d9b1-fd41-0001 from [127.0.0.1]:5701
12:45:24,501 DEBUG |test| - [JobExecutionService] Thread-71 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Execution plan for light job ID=0779-d9b1-fd41-0001, jobName='0779-d9b1-fd41-0001', executionId=0779-d9b1-fd41-0001 initialized, will start the execution
12:45:24,530  INFO |test| - [StreamKafkaP] hz.hungry_ellis.jet.blocking.thread-1 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] [0779-d9b1-fd41-0001/Kafka[public.o_c2ab65c5_3f74_4ac2_930e_8a94e585acda]#0] New partition(s) assigned: [o_c2ab65c5_3f74_4ac2_930e_8a94e585acda-0]
12:45:24,576  INFO || - [SlidingWindowP] hz.hungry_ellis.jet.cooperative.thread-0 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] [0779-d9b1-fd41-0001/Sliding-Window-AccumulateByKey#0] Late event dropped. currentWatermark=Watermark{ts=00:00:00.010}, event=[2, HeapData{type=-7, hashCode=-919423505, partitionHash=-919423505, totalSize=12, dataSize=4, heapCost=44}]
12:45:24,577  INFO || - [SlidingWindowP] hz.hungry_ellis.jet.cooperative.thread-0 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] [0779-d9b1-fd41-0001/Sliding-Window-AccumulateByKey#0] Late event dropped. currentWatermark=Watermark{ts=00:00:00.010}, event=[0, HeapData{type=-7, hashCode=-832990049, partitionHash=-832990049, totalSize=12, dataSize=4, heapCost=44}]
12:45:29,351 DEBUG |test| - [JobRepository] hz.hungry_ellis.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Job cleanup took 0ms
12:45:34,350 DEBUG |test| - [JobRepository] hz.hungry_ellis.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Job cleanup took 0ms
12:45:34,365 DEBUG || - [TaskletExecutionService] hz.hungry_ellis.jet.cooperative.thread-0 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Job was cancelled by the user.
12:45:34,381 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-2 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Completed execution of job '0779-d9b1-fd41-0001', execution 0779-d9b1-fd41-0001
12:45:34,381 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-2 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Execution of job '0779-d9b1-fd41-0001', execution 0779-d9b1-fd41-0001 completed with failure
java.util.concurrent.CompletionException: java.util.concurrent.CancellationException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292) ~[?:1.8.0_311]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308) ~[?:1.8.0_311]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:783) ~[?:1.8.0_311]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) ~[?:1.8.0_311]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) ~[?:1.8.0_311]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) ~[?:1.8.0_311]
	at com.hazelcast.jet.impl.util.NonCompletableFuture.internalCompleteExceptionally(NonCompletableFuture.java:72) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$ExecutionTracker.taskletDone(TaskletExecutionService.java:495) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$BlockingWorker.run(TaskletExecutionService.java:330) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_311]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_311]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_311]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_311]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_311]
Caused by: java.util.concurrent.CancellationException
	at com.hazelcast.jet.sql.impl.processors.RootResultConsumerSink.tryProcess(RootResultConsumerSink.java:91) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.lambda$stateMachineStep$2(ProcessorTasklet.java:297) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.jet.impl.util.Util.doWithClassLoader(Util.java:533) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:297) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:281) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:255) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:401) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:895) ~[?:1.8.0_311]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.run(TaskletExecutionService.java:369) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	... 1 more
BuildInfo right after test(com.hazelcast.jet.sql.impl.connector.kafka.SqlKafkaAggregateTest): BuildInfo{version='5.1-SNAPSHOT', build='20220126', buildNumber=20220126, revision=b7681b1, enterprise=false, serializationVersion=1}
12:45:34,542 ERROR || - [EventServiceImpl] hz.hungry_ellis.event-23 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] hz.hungry_ellis.event-23 caught an exception while processing:com.hazelcast.spi.impl.eventservice.impl.LocalEventDispatcher@46af45e6
java.lang.UnsupportedOperationException: SQL catalog must never be cleared - MapEvent{entryEventType=CLEAR_ALL, member=Member [127.0.0.1]:5701 - e4c3b490-e244-4633-9219-d884c9aaa576 this, name='__sql.catalog', numberOfEntriesAffected=1}
	at com.hazelcast.jet.sql.impl.schema.TablesStorage$EntryListenerAdapter.mapCleared(TablesStorage.java:202) ~[classes/:?]
	at com.hazelcast.replicatedmap.impl.ReplicatedMapEventPublishingService.dispatchEvent(ReplicatedMapEventPublishingService.java:132) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.replicatedmap.impl.ReplicatedMapService.dispatchEvent(ReplicatedMapService.java:232) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.spi.impl.eventservice.impl.LocalEventDispatcher.run(LocalEventDispatcher.java:64) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.internal.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:245) [hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.internal.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:228) [hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
Hiccups measured while running test 'test(com.hazelcast.jet.sql.impl.connector.kafka.SqlKafkaAggregateTest):'
12:45:20, accumulated pauses: 229 ms, max pause: 28 ms, pauses over 1000 ms: 0
12:45:25, accumulated pauses: 578 ms, max pause: 60 ms, pauses over 1000 ms: 0
12:45:30, accumulated pauses: 535 ms, max pause: 147 ms, pauses over 1000 ms: 0

```

</details>

**Comment by viliam-durina** [comment]
Root cause is that the INSERT command might insert the rows into the kafka topic in a different order, and that might cause that expected items are dropped as late.
