### ISSUE TITLE
com.hazelcast.internal.metrics.metricsets.OperatingSystemMetricSetTest

### ISSUE THREAD

**Issue by slavagithub** [hazelcast/hazelcast#20521]
_master_ (commit 4de7ce00ce6aed69738ba4e1603267bf00608db8)

Failed on Openj9-16: [failure report](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Openj9-16/45/testReport/com.hazelcast.internal.metrics.metricsets/OperatingSystemMetricSetTest/testComSunManagementOperatingSystemMXBean/)

<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: sensor: os.committedVirtualMemorySize is not found
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at com.hazelcast.internal.metrics.metricsets.OperatingSystemMetricSetTest.assertContainsSensor(OperatingSystemMetricSetTest.java:101)
	at com.hazelcast.internal.metrics.metricsets.OperatingSystemMetricSetTest.testComSunManagementOperatingSystemMXBean(OperatingSystemMetricSetTest.java:85)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:883)
```

</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: registerMethod_whenNotExist in 0.001 seconds.
Started Running Test: testComSunManagementOperatingSystemMXBean
BuildInfo right after testComSunManagementOperatingSystemMXBean(com.hazelcast.internal.metrics.metricsets.OperatingSystemMetricSetTest): BuildInfo{version='5.1-SNAPSHOT', build='20220127', buildNumber=20220127, revision=4de7ce0, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'testComSunManagementOperatingSystemMXBean(com.hazelcast.internal.metrics.metricsets.OperatingSystemMetricSetTest):'
05:19:00, accumulated pauses: 40 ms, max pause: 24 ms, pauses over 1000 ms: 0


No metrics recorded during the test
```

</details>

**Comment by olukas** [comment]
Failed also on Openj9-11: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Openj9-11/64/testReport/com.hazelcast.internal.metrics.metricsets/OperatingSystemMetricSetTest/

<details><summary>Stacktrace for testComSunManagementOperatingSystemMXBean:</summary>

```
java.lang.AssertionError: sensor: os.committedVirtualMemorySize is not found
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at com.hazelcast.internal.metrics.metricsets.OperatingSystemMetricSetTest.assertContainsSensor(OperatingSystemMetricSetTest.java:101)
	at com.hazelcast.internal.metrics.metricsets.OperatingSystemMetricSetTest.testComSunManagementOperatingSystemMXBean(OperatingSystemMetricSetTest.java:85)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:866)
```

</details>

<details><summary>Stacktrace for testComSunManagementUnixOperatingSystemMXBean:</summary>

```
java.lang.AssertionError: sensor: os.maxFileDescriptorCount is not found
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at com.hazelcast.internal.metrics.metricsets.OperatingSystemMetricSetTest.assertContainsSensor(OperatingSystemMetricSetTest.java:101)
	at com.hazelcast.internal.metrics.metricsets.OperatingSystemMetricSetTest.testComSunManagementUnixOperatingSystemMXBean(OperatingSystemMetricSetTest.java:76)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:866)
```

</details>
