### ISSUE TITLE
com.hazelcast.jet.cdc.mysql.MySqlCdcNetworkIntegrationTest

### ISSUE THREAD

**Issue by slavagithub** [hazelcast/hazelcast#20536]
Java opening issue - "module java.base does not "opens java.util""
The same for com.hazelcast.jet.cdc.postgres.PostgresCdcNetworkIntegrationTest

_master_ (commit 756a3de3603d068b7a504e9b228017e03235e0a9)

Failed on Zulu, JDK16: [failure report](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZuluJDK16-nightly/37/testReport/)

<details><summary>Stacktrace:</summary>

```
java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.util.Map java.util.Collections$UnmodifiableMap.m accessible: module java.base does not "opens java.util" to unnamed module @77b52d12
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:177)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:171)
	at org.junit.contrib.java.lang.system.EnvironmentVariables.getFieldValue(EnvironmentVariables.java:188)
	at org.junit.contrib.java.lang.system.EnvironmentVariables.getEditableMapOfVariables(EnvironmentVariables.java:150)
	at org.junit.contrib.java.lang.system.EnvironmentVariables.access$200(EnvironmentVariables.java:49)
	at org.junit.contrib.java.lang.system.EnvironmentVariables$EnvironmentVariablesStatement.restoreOriginalVariables(EnvironmentVariables.java:134)
	at org.junit.contrib.java.lang.system.EnvironmentVariables$EnvironmentVariablesStatement.evaluate(EnvironmentVariables.java:125)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37)
	at com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:104)
	at com.hazelcast.test.metrics.MetricsRule$1.evaluate(MetricsRule.java:63)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:50)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:29)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:39)
	at com.hazelcast.test.OverridePropertyRule$1.evaluate(OverridePropertyRule.java:66)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:831)
```

</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: when_databaseShutdownDuringSnapshotting[fail] in 0.001 seconds.
Started Running Test: when_networkDisconnectDuringBinlogRead_then_connectorReconnectsInternally[fail]
BuildInfo right after when_networkDisconnectDuringBinlogRead_then_connectorReconnectsInternally[fail](com.hazelcast.jet.cdc.mysql.MySqlCdcNetworkIntegrationTest): BuildInfo{version='5.1-SNAPSHOT', build='20220128', buildNumber=20220128, revision=756a3de, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'when_networkDisconnectDuringBinlogRead_then_connectorReconnectsInternally[fail](com.hazelcast.jet.cdc.mysql.MySqlCdcNetworkIntegrationTest):'
07:09:15, accumulated pauses: 3480 ms, max pause: 10 ms, pauses over 1000 ms: 0


No metrics recorded during the test
```

</details>

**Comment by slavagithub** [comment]
@lukasblu FYI, java.util opening issue for JDK16

**Comment by olukas** [comment]
Failed again on Zulu JDK 16:
- `MySqlCdcNetworkIntegrationTest`: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZuluJDK16-nightly/38/testReport/com.hazelcast.jet.cdc.mysql/MySqlCdcNetworkIntegrationTest/
- `PostgresCdcNetworkIntegrationTest`: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZuluJDK16-nightly/38/testReport/com.hazelcast.jet.cdc.postgres/PostgresCdcNetworkIntegrationTest/
