### ISSUE TITLE
All hazelcast map operations hanging indefinitely

### ISSUE THREAD

**Issue by dimejiogunyoye** [hazelcast/hazelcast#20542]
**Describe the bug**
All map operations being made to hazelcast are not returning and are hung on a future `.get()` call.
I wrote a small "debugging" hz client, which connects to the affected instance and queries the size of an existing map. The query method call does not complete. This is snapshot of a thread dump from the debugging client:

```
"main" #1 prio=5 os_prio=0 cpu=664.98ms elapsed=21.94s tid=0x00007f77e4014800 nid=0x307a waiting on condition  [0x00007f77ebf1e000]
   java.lang.Thread.State: WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@11.0.6/Native Method)
        at java.util.concurrent.locks.LockSupport.park(java.base@11.0.6/LockSupport.java:323)
        at com.hazelcast.spi.impl.AbstractInvocationFuture.manageParking(AbstractInvocationFuture.java:693)
        at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:615)
        at com.hazelcast.client.impl.spi.ClientProxy.invoke(ClientProxy.java:215)
        at com.hazelcast.client.impl.proxy.ClientMapProxy.size(ClientMapProxy.java:1559)
        at hzdebugger.HazelcastDebugger.main(HazelcastDebugger.java:16)
```

**Expected behavior**
The future to complete and not hang indefinitely.

**To Reproduce**
No clear steps to reproduce this unfortunately. This has reproduced in our production environment a number of times, though nothing (from what I've seen) to really correlate separate common factors between reproductions.

**Additional context**
Observed in Hazelcast 4.2 and 4.0.3

Running Java 11:
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.6+10, mixed mode)

This has occurred in a 2 node cluster, but has also reproduced (strangely enough) in a single node cluster
I've attached a thread dump from the process running the hz instance.

We've left the affected environment untouched (so the issue is still present on there). If there are tools/commands that I could run to retrieve more information, I'm happy to comply.

Thanks in advance,
Dimeji

[hz-hung.txt](https://github.com/hazelcast/hazelcast/files/7959383/hz-hung.txt)

**Comment by ahmetmircik** [comment]
Hi @dimejiogunyoye, possibly you hit this issue: https://github.com/hazelcast/hazelcast/issues/17959
Just to spot the issue, any difference you see if you set `java.util.concurrent.ForkJoinPool.common.parallelism` to `1`?

**Comment by dimejiogunyoye** [comment]
> Hi @dimejiogunyoye, possibly you hit this issue: #17959 Just to spot the issue, any difference you see if you set `java.util.concurrent.ForkJoinPool.common.parallelism` to `1`?

Hi Ahmet, thanks for getting back to me. I've just run my debugging client against the affected server with the property `-Djava.util.concurrent.ForkJoinPool.common.parallelism=1` - this didn't resolve the issue unfortunately.

It feels as if this is a problem originating on the hz instance. Some how it manages to get into a state where it no longer responds to operations. Perhaps important to note that it often takes some time to reproduce though however long this is, is unknown. On start-up, everything functions as expected

**Comment by ahmetmircik** [comment]
Just for clarification, did you set `Djava.util.concurrent.ForkJoinPool.common.parallelism=1` on both server and client JVMs?

**Comment by dimejiogunyoye** [comment]
I set the command on my debugging client, not the server. I'd have to restart my server with the cmdline property - a restart always resolves the problem up until it reproduces under unknown conditions. Additionally, your fix was added in 4.2 which my problem also occurs on

**Comment by ahmetmircik** [comment]
It can be that my fix doesn't cover all cases. Somehow we need to replicate your setup to reproduce the issue if you don't want to restart.

**Comment by dimejiogunyoye** [comment]
Thanks, reproducing this is tricky as steps aren't apparent - this has always happened seemingly randomly. I'll take a look at your fix to see if the same problem might be manifesting, but in a different perspective.

I should be able to run another instance of our service with the parallelism=1 system property, so I'd like to keep the affected server in its current state just in case there are any suggested JVM tools/commands to debug this further.

Thanks

**Comment by dimejiogunyoye** [comment]
Admittedly without knowing the fundamentals of hazelcast too much, in what circumstances could we ever expect a hz instance to not respond to a map operation from a client?

**Comment by dimejiogunyoye** [comment]
Can anyone provide pointers on the above? ^
This issue happens far too randomly for me to be able to pinpoint an exact reproducer. I've still got the affected instance up, so I can gather thread dumps/heap dumps, etc which may help diagnose on my side

**Comment by vbekiaris** [comment]
Hanging indefinitely is unexpected and common pool threads in your thread dump are not blocked, so it doesn't look like #17959. Could you share more details about your environment (# of cores, memory) and use case?

**Comment by dimejiogunyoye** [comment]
Thanks @vbekiaris.

We use Hazelcast internally as part of our product ([Diffusion](https://www.pushtechnology.com/product-overview/)). We allow our customers to set up multiple Diffusion instances and form a cluster, in order to share data amongst them (using Hazelcast maps). We have an on-prem and Cloud offering of our product, so far this has only been observed in our Cloud offering but nothing to suggest it does not also reside in our on-prem product.

The system this occurred on has 4 cores and 12GiB memory.

Out of pure coincidence, this has just reproduced again in a different production environment:

`[dev] [4.0.3] processors=4, physical.memory.total=30.6G, physical.memory.free=11.3G, swap.space.total=0, swap.space.free=0, heap.memory.used=12.2G, heap.memory.free=1.4G, heap.memory.total=13.6G, heap.memory.max=13.6G, heap.memory.used/total=89.47%, heap.memory.used/max=89.47%, minor.gc.count=753, minor.gc.time=16107ms, major.gc.count=0, major.gc.time=0ms, load.process=0.82%, load.system=0.91%, load.systemAverage=0.07, thread.count=107, thread.peakCount=116, cluster.timeDiff=0, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=3632754, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=11, clientEndpoint.count=0, connection.active.count=0, client.connection.count=0, connection.count=0|com.hazelcast.internal.diagnostics.HealthMonitor`

I ran my debugging client and it blocked indefinitely in the same place:

`"main" #1 prio=5 os_prio=0 cpu=627.20ms elapsed=22.70s tid=0x00007f62b8014800 nid=0x3263 waiting on condition  [0x00007f62bd514000]
   java.lang.Thread.State: WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@11.0.6/Native Method)
        at java.util.concurrent.locks.LockSupport.park(java.base@11.0.6/LockSupport.java:323)
        at com.hazelcast.spi.impl.AbstractInvocationFuture.manageParking(AbstractInvocationFuture.java:693)
        at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:615)
        at com.hazelcast.client.impl.spi.ClientProxy.invoke(ClientProxy.java:215)
        at com.hazelcast.client.impl.proxy.ClientMapProxy.size(ClientMapProxy.java:1559)
        at hzdebugger.HazelcastDebugger.main(HazelcastDebugger.java:19)`

I've attached a thread dump of the server. As you can see, the background thread pool threads aren't blocked yet in the same manner as what I posted previously. This is because a client needs to be disconnected for that to occur (onSessionClosed). But the hz instance is definitely hanging

[dump.txt](https://github.com/hazelcast/hazelcast/files/7985933/dump.txt)

**Comment by dimejiogunyoye** [comment]
I've restarted the server this was occurring on earlier.
I've kept a server this is reproducing on alive, so any debugging tools that might shed some light on this issue can be used.

I can take (and have taken) heap dumps of our server, so if there are any particular classes of interest in there that might give more information, I'd be happy to look into it

**Comment by Holmistr** [comment]
Hi @dimejiogunyoye , thanks for sharing this.  Let me circle back with the team whether we can find some time for investigation in the next sprint.

**Comment by dimejiogunyoye** [comment]
Hi @Holmistr - thanks for looking into this. This is currently our biggest item to resolve and has a direct impact on our customers in production. Any time you can dedicate to this would be greatly appreciated. I'm happy to assist in any way I can.

**Comment by hfsugar** [comment]
@Holmistr Hi, I met similar circumstances as follows. Hazelcast map get operation hangs in Hazelcast 4.0.3.
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/4880121/166917448-127efa4f-3126-4212-9d27-ed28bdb56d1a.png">

How's the progress now?

**Comment by vbekiaris** [comment]
The thread dumps previously shared by @dimejiogunyoye show no signs of member-side threads being stalled. The issue can be anywhere in invocation system of member or client and there is currently no indication of why or where the issue occurs.

My suggestion would be to try using the latest stable Hazelcast version 5.1.1 to find out if the issue persists (see the [docs](https://docs.hazelcast.com/hazelcast/latest/migrate/upgrading-from-imdg-4) about upgrading -- there were few if any breaking changes from 4.x to 5.x). If you'd rather avoid trying 5.x, I would suggest to try out the latest 4.2.5 release -- 4.0 is anyway out of support.

**Comment by dimejiogunyoye** [comment]
Hi @hfsugar, have you encountered this since? Can you also share details about the environment this reproduces in? It would be ideal to know if it has similarities to ours

**Comment by atindramardikar** [comment]
Hello folks,
We encountered similar issue to this as well but on putTransient operation-
`java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:304)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.manageParking(AbstractInvocationFuture.java:693)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:615)
	at com.hazelcast.client.impl.spi.ClientProxy.invokeOnPartition(ClientProxy.java:188)
	at com.hazelcast.client.impl.spi.ClientProxy.invoke(ClientProxy.java:182)
	at com.hazelcast.client.impl.proxy.ClientMapProxy.putTransientInternal(ClientMapProxy.java:575)
	at com.hazelcast.client.impl.proxy.ClientMapProxy.**putTransient**(ClientMapProxy.java:547)
	at com.ebay.app.enums.HazelcastFunction.replicatedOperation(HazelcastFunction.java:35)
	at com.ebay.app.config.FederatedHazelcastInstance.replicatedFunction(FederatedHazelcastInstance.java:261)
	at com.ebay.app.config.FederatedHazelcastInstance.mergeAndPut(FederatedHazelcastInstance.java:205)
	at com.ebay.app.controller.DataController.lambda$bulkWrite$4(DataController.java:445)
	at com.ebay.app.controller.DataController$$Lambda$2442/779126416.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)`
	
A cluster restart seemed to have solved it. This is our production cluster and this is the first time we saw since our implementation which was early this year.

This is the configuration for our cluster:
Cluster size: 22
Hazelcast version: 5.1.5
Java version : 8

**Comment by johrishashank11** [comment]
Was anybody able to resolve this issue? I am also facing the same issue. Below is my environment:-
JDK 11
Hazelcast 5.3.2

I am attaching JFR files from my application and hazelcast here for more visibility.
[Uploading JFR Files.zip…]()

**Comment by yakuninv** [comment]
Hi any clue about RC of the issue? 

JDK 11
Hzelcast 5.3.6

During our testing we observed this issue as well trying to obtain distributed lock via non-blocking FencedLock.tryLock(). 

We tested on three node hazelcast cluster, where only one was alive (cluster of size: 1). Our application used hazelcast client to tryLock() and it thread got stuck. Bringing up two remaining hazelcast members, while app being stuck, didn't have any influence. I think this is serious issue making whole CP system not very reliable.

See stack trace below:

`"HAZELCAST_LOCK_LIVENESS" #100 prio=5 os_prio=0 cpu=3.37ms elapsed=176.21s tid=0x00007fd48f986000 nid=0x757 waiting on condition  [0x00007fd3b8da7000]
   java.lang.Thread.State: WAITING (parking)
        at jdk.internal.misc.Unsafe.park([java.base@11.0.19/Native](mailto:java.base@11.0.19/Native) Method)
        at java.util.concurrent.locks.LockSupport.park([java.base@11.0.19/LockSupport.java:323](mailto:java.base@11.0.19/LockSupport.java:323))
        at com.hazelcast.spi.impl.AbstractInvocationFuture.manageParking(AbstractInvocationFuture.java:694)
        at com.hazelcast.spi.impl.AbstractInvocationFuture.joinInternal(AbstractInvocationFuture.java:583)
        at com.hazelcast.client.cp.internal.session.ClientProxySessionManager.requestNewSession(ClientProxySessionManager.java:67)
        at com.hazelcast.cp.internal.session.AbstractProxySessionManager.createNewSession(AbstractProxySessionManager.java:215)
        - locked <0x0000000797de3b28> (a java.lang.Object)
        at com.hazelcast.cp.internal.session.AbstractProxySessionManager.getOrCreateSession(AbstractProxySessionManager.java:203)
        - locked <0x0000000797de3b28> (a java.lang.Object)
        at com.hazelcast.cp.internal.session.AbstractProxySessionManager.acquireSession(AbstractProxySessionManager.java:120)
        at com.hazelcast.cp.internal.session.SessionAwareProxy.acquireSession(SessionAwareProxy.java:47)
        at com.hazelcast.cp.internal.datastructures.lock.proxy.AbstractFencedLockProxy.tryLockAndGetFence(AbstractFencedLockProxy.java:172)
        at com.hazelcast.cp.internal.datastructures.lock.proxy.AbstractFencedLockProxy.tryLockAndGetFence(AbstractFencedLockProxy.java:152)
        at com.hazelcast.cp.internal.datastructures.lock.proxy.AbstractFencedLockProxy.tryLock(AbstractFencedLockProxy.java:147)
        at com.hazelcast.client.cp.internal.datastructures.lock.FencedLockProxy.tryLock(FencedLockProxy.java:79)
        at org.dett.router.ha.hazelcast.DistributedLock.tryAcquire(DistributedLock.java:18)
        at org.dett.router.ha.hazelcast.DistributedLockSwitchChecker.checkLockLiveness(DistributedLockSwitchChecker.java:277)
        at org.dett.router.ha.hazelcast.DistributedLockSwitchChecker$$Lambda$2037/0x0000000840d17840.run(Unknown Source)
        at org.dett.common.concurrent.BasicThreadFactory.lambda$createImpl$0(BasicThreadFactory.java:31)
        at org.dett.common.concurrent.BasicThreadFactory$$Lambda$456/0x00000008406acc40.run(Unknown Source)
        at java.lang.Thread.run([java.base@11.0.19/Thread.java:829](mailto:java.base@11.0.19/Thread.java:829))

`
