### ISSUE TITLE
com.hazelcast.map.DynamicMapConfigTest.testMapConfigUpdate_reflectedToRecordStore [HZ-960]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#20589]
_5.0.z_ (commit 66205d3ebb195e129fb552d88a11730c16ca0851)

Failed on Zing JDK 8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-ZingJDK8/38/testReport/com.hazelcast.map/DynamicMapConfigTest/testMapConfigUpdate_reflectedToRecordStore/

<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: RecordStore should be expirable and evictable after MapConfig update
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at com.hazelcast.map.DynamicMapConfigTest.testMapConfigUpdate_reflectedToRecordStore(DynamicMapConfigTest.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

</details>

<details><summary>Standard output:</summary>

```
21:02:50,227  INFO |testMapConfigUpdate_reflectedToRecordStore| - [MetricsConfigHelper] testMapConfigUpdate_reflectedToRecordStore - [LOCAL] [dev] [5.0.3-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
21:02:50,230  INFO |testMapConfigUpdate_reflectedToRecordStore| - [logo] testMapConfigUpdate_reflectedToRecordStore - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
21:02:50,230  INFO |testMapConfigUpdate_reflectedToRecordStore| - [system] testMapConfigUpdate_reflectedToRecordStore - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] Copyright (c) 2008-2021, Hazelcast, Inc. All Rights Reserved.
21:02:50,230  INFO |testMapConfigUpdate_reflectedToRecordStore| - [system] testMapConfigUpdate_reflectedToRecordStore - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] Hazelcast Platform 5.0.3-SNAPSHOT (20220202 - 66205d3) starting at [127.0.0.1]:5701
21:02:50,230  INFO |testMapConfigUpdate_reflectedToRecordStore| - [system] testMapConfigUpdate_reflectedToRecordStore - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] Cluster name: dev
21:02:50,256  INFO |testMapConfigUpdate_reflectedToRecordStore| - [MetricsConfigHelper] testMapConfigUpdate_reflectedToRecordStore - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
21:02:50,270  WARN |testMapConfigUpdate_reflectedToRecordStore| - [CPSubsystem] testMapConfigUpdate_reflectedToRecordStore - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
21:02:50,276  INFO |testMapConfigUpdate_reflectedToRecordStore| - [JetServiceBackend] testMapConfigUpdate_reflectedToRecordStore - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] Setting number of cooperative threads and default parallelism to 4
21:02:50,280  INFO |testMapConfigUpdate_reflectedToRecordStore| - [Diagnostics] testMapConfigUpdate_reflectedToRecordStore - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
21:02:50,280  INFO |testMapConfigUpdate_reflectedToRecordStore| - [LifecycleService] testMapConfigUpdate_reflectedToRecordStore - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] [127.0.0.1]:5701 is STARTING
21:02:50,280  INFO |testMapConfigUpdate_reflectedToRecordStore| - [JetExtension] testMapConfigUpdate_reflectedToRecordStore - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] Jet is enabled
21:02:50,280  INFO |testMapConfigUpdate_reflectedToRecordStore| - [ClusterService] testMapConfigUpdate_reflectedToRecordStore - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] 

Members {size:1, ver:1} [
	Member [127.0.0.1]:5701 - a5efa2eb-b576-4163-bb2d-cef16e0bc327 this
]

21:02:50,280  INFO |testMapConfigUpdate_reflectedToRecordStore| - [LifecycleService] testMapConfigUpdate_reflectedToRecordStore - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] [127.0.0.1]:5701 is STARTED
21:02:50,281  INFO |testMapConfigUpdate_reflectedToRecordStore| - [PartitionStateManager] testMapConfigUpdate_reflectedToRecordStore - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] Initializing cluster partition table arrangement...
21:02:50,282  INFO |testMapConfigUpdate_reflectedToRecordStore| - [HealthMonitor] hz.fervent_herschel.HealthMonitor - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] processors=4, physical.memory.total=29.8G, physical.memory.free=12.9G, swap.space.total=0, swap.space.free=0, heap.memory.used=3.3G, heap.memory.free=0, heap.memory.total=3.3G, heap.memory.max=3.3G, heap.memory.used/total=100.00%, heap.memory.used/max=101.02%, minor.gc.count=0, minor.gc.time=0ms, major.gc.count=0, major.gc.time=0ms, load.process=60.42%, load.system=100.00%, load.systemAverage=12.48, thread.count=151, thread.peakCount=1637, cluster.timeDiff=0, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=1, executor.q.priorityOperation.size=0, operations.completed.count=0, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=1, clientEndpoint.count=0, connection.active.count=0, client.connection.count=0, connection.count=0
21:02:50,324  INFO |testMapConfigUpdate_reflectedToRecordStore| - [LifecycleService] Thread-52631 - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
21:02:50,324  WARN |testMapConfigUpdate_reflectedToRecordStore| - [Node] Thread-52631 - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] Terminating forcefully...
21:02:50,324  INFO |testMapConfigUpdate_reflectedToRecordStore| - [Node] Thread-52631 - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] Shutting down connection manager...
21:02:50,324  INFO |testMapConfigUpdate_reflectedToRecordStore| - [Node] Thread-52631 - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] Shutting down node engine...
21:02:50,369  INFO |testMapConfigUpdate_reflectedToRecordStore| - [NodeExtension] Thread-52631 - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] Destroying node NodeExtension.
21:02:50,370  INFO |testMapConfigUpdate_reflectedToRecordStore| - [Node] Thread-52631 - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] Hazelcast Shutdown is completed in 46 ms.
21:02:50,370  INFO |testMapConfigUpdate_reflectedToRecordStore| - [LifecycleService] Thread-52631 - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
BuildInfo right after testMapConfigUpdate_reflectedToRecordStore(com.hazelcast.map.DynamicMapConfigTest): BuildInfo{version='5.0.3-SNAPSHOT', build='20220202', buildNumber=20220202, revision=66205d3, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'testMapConfigUpdate_reflectedToRecordStore(com.hazelcast.map.DynamicMapConfigTest):'
21:02:50, accumulated pauses: 61 ms, max pause: 8 ms, pauses over 1000 ms: 0
```

</details>

**Comment by olukas** [comment]
Reopening since it happened again on `master` on ZingJDK8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZingJDK8/414/testReport/com.hazelcast.map/DynamicMapConfigTest/testMapConfigUpdate_reflectedToRecordStore/

Stacktrace:
```
java.lang.AssertionError: RecordStore should be expirable and evictable after MapConfig update
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at com.hazelcast.map.DynamicMapConfigTest.testMapConfigUpdate_reflectedToRecordStore(DynamicMapConfigTest.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by olukas** [comment]
Failed on `master` on ZingJDK8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZingJDK8/431/testReport/com.hazelcast.map/DynamicMapConfigTest/testMapConfigUpdate_reflectedToRecordStore/
