### ISSUE TITLE
com.hazelcast.client.ClientRegressionWithMockNetworkTest [HZ-1836]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#20590]
_5.0.z_ (commit 66205d3ebb195e129fb552d88a11730c16ca0851)

Failed on Zing JDK 8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-ZingJDK8/38/testReport/com.hazelcast.client/ClientRegressionWithMockNetworkTest/com_hazelcast_client_ClientRegressionWithMockNetworkTest/

It failed in the same run as https://github.com/hazelcast/hazelcast/issues/20589 - those issues can be related.

<details><summary>Stacktrace:</summary>

```
java.lang.IllegalStateException: Instances haven't been shut down: [HazelcastInstance{name='gracious_turing', node=[127.0.0.1]:5701}]
	at com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:46)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:107)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:83)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
```

</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: testOperationRedo in 8.444 seconds.
19:09:46,219  INFO || - [LifecycleService] main - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
19:09:46,219 DEBUG || - [JobCoordinationService] main - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] Added a shutting-down member: f474fd28-7ca1-497b-b26b-aa0f7e3598da
19:09:46,220  INFO || - [Node] main - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] Shutting down connection manager...
19:09:46,220  INFO || - [Node] main - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] Shutting down node engine...
19:09:46,234  INFO || - [NodeExtension] main - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] Destroying node NodeExtension.
19:09:46,237  INFO || - [Node] main - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] Hazelcast Shutdown is completed in 18 ms.
19:09:46,237  INFO || - [LifecycleService] main - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
```

</details>

**Comment by vbekiaris** [comment]
Bumping to 5.0.4, this is an "Instances haven't been shut down" kind of failure (some other test may be leaking HZ instances?).

**Comment by olukas** [comment]
Failed on `master` on ZuluJDK11: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZuluJDK11/194/testReport/com.hazelcast.client/ClientRegressionWithMockNetworkTest/com_hazelcast_client_ClientRegressionWithMockNetworkTest/

No other test failed in this job run.

**Comment by olukas** [comment]
Failed on `master` on CorrettoJDK17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-CorrettoJDK17/18/testReport/com.hazelcast.client/ClientRegressionWithMockNetworkTest/com_hazelcast_client_ClientRegressionWithMockNetworkTest/

**Comment by kwart** [comment]
Failed on PR builder (`master`): https://jenkins.hazelcast.com/job/Hazelcast-pr-builder/12774/testReport/junit/com.hazelcast.client/ClientRegressionWithMockNetworkTest/com_hazelcast_client_ClientRegressionWithMockNetworkTest/

**Comment by mdumandag** [comment]
Failed on PR builder (`master`): https://jenkins.hazelcast.com/job/Hazelcast-pr-builder/13257/testReport/junit/com.hazelcast.client/ClientRegressionWithMockNetworkTest/com_hazelcast_client_ClientRegressionWithMockNetworkTest/

**Comment by olukas** [comment]
Failed on `5.1.z` on OracleJDK17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-OracleJDK17/30/testReport/com.hazelcast.client/ClientRegressionWithMockNetworkTest/com_hazelcast_client_ClientRegressionWithMockNetworkTest/

**Comment by mdumandag** [comment]
@srknzl is this also fixed by https://github.com/hazelcast/hazelcast/pull/22012 for master? if so, we can backport it 5.1.z (just to latest maintenance) and close this issue

**Comment by srknzl** [comment]
@mdumandag We only used random cluster names in that PR. I don't think it will fix leaking instances.

**Comment by vbekiaris** [comment]
new failure in PR builder for `master` branch: https://jenkins.hazelcast.com/job/Hazelcast-pr-builder/13728/

**Comment by Patras3** [comment]
Reopening as issue occurred again on: _5.2.z_ (commit 13f1cebcb9b7fe768ec2c9be56524d9f0f355114)
with zing-11: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-ZingJDK11/4/testReport/junit/com.hazelcast.client/ClientRegressionWithMockNetworkTest/com_hazelcast_client_ClientRegressionWithMockNetworkTest/
<details><summary>Stacktrace:</summary>

```
java.lang.IllegalStateException: Instances haven't been shut down: [HazelcastInstance{name='musing_minsky', node=[127.0.0.1]:5701}]
	at com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:47)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:107)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:83)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)

```
</details>


<details><summary>Standard output:</summary>

```
Finished Running Test: testIssue821 in 6.087 seconds.
19:50:34,667 DEBUG |testClientReconnect_thenCheckRequestsAreRetriedWithoutException| - [JobCoordinationService] hz.musing_minsky.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.2.2-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
19:50:34,668  INFO || - [LifecycleService] main - [127.0.0.1]:5701 [dev] [5.2.2-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
19:50:34,669  WARN || - [Node] main - [127.0.0.1]:5701 [dev] [5.2.2-SNAPSHOT] Terminating forcefully...
19:50:34,669  INFO || - [Node] main - [127.0.0.1]:5701 [dev] [5.2.2-SNAPSHOT] Shutting down connection manager...
19:50:34,669  INFO || - [Node] main - [127.0.0.1]:5701 [dev] [5.2.2-SNAPSHOT] Shutting down node engine...
19:50:34,675  INFO || - [NodeExtension] main - [127.0.0.1]:5701 [dev] [5.2.2-SNAPSHOT] Destroying node NodeExtension.
19:50:34,675  INFO || - [Node] main - [127.0.0.1]:5701 [dev] [5.2.2-SNAPSHOT] Hazelcast Shutdown is completed in 6 ms.
19:50:34,675  INFO || - [LifecycleService] main - [127.0.0.1]:5701 [dev] [5.2.2-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-5.maintenance-ZingJDK11/4/

@TomaszGaweda We need backport

**Comment by sumnerib** [comment]
Failed again on _5.2.z_ with oracle-11: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-sonar-new/35/testReport/junit/com.hazelcast.client/ClientRegressionWithMockNetworkTest/com_hazelcast_client_ClientRegressionWithMockNetworkTest/

**Comment by olukas** [comment]
Failed again on _5.2.z_ with oracle-17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-OracleJDK17/48/testReport/com.hazelcast.client/ClientRegressionWithMockNetworkTest/com_hazelcast_client_ClientRegressionWithMockNetworkTest/

**Comment by olukas** [comment]
@TomaszGaweda all latest failures are on 5.2.z branch. Could you please backport the fix to `5.2.z` branch?

**Comment by Patras3** [comment]
Failed again on _5.2.z_ with openjdk-11: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-ZuluJDK11/76/testReport/junit/com.hazelcast.client/ClientRegressionWithMockNetworkTest/com_hazelcast_client_ClientRegressionWithMockNetworkTest/

**Comment by Patras3** [comment]
Failed again on _5.2.z_ with openjdk-11: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-ZuluJDK11/79/testReport/junit/com.hazelcast.client/ClientRegressionWithMockNetworkTest/com_hazelcast_client_ClientRegressionWithMockNetworkTest/

**Comment by mdumandag** [comment]
closing this one as I have backported the change into 5.2.z branch.
