### ISSUE TITLE
com.hazelcast.client.cache.ClientCacheConfigTest.cacheCacheManagerByLocationJarFileTest

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#20617]
_master_ (commit d2b84ffcc5d0ceb35282231737bd55c19499f37d)

Failed on Windows with OracleJDK8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Windows-OracleJDK8/373/testReport/com.hazelcast.client.cache/ClientCacheConfigTest/cacheCacheManagerByLocationJarFileTest/

<details><summary>Stacktrace:</summary>

```
java.net.URISyntaxException: Illegal character in opaque part at index 11: jar:file:C:\Users\Administrator\AppData\Local\Temp\jcache_config_6267592182379058229.jar!/hazelcast-client-c1.xml
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parse(URI.java:3058)
	at java.net.URI.<init>(URI.java:588)
	at com.hazelcast.client.cache.ClientCacheConfigTest.cacheCacheManagerByLocationJarFileTest(ClientCacheConfigTest.java:119)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

</details>

<details><summary>Standard output:</summary>

```
11:41:31,563  INFO |cacheCacheManagerByLocationJarFileTest| - [MetricsConfigHelper] main - [LOCAL] [cluster1] [5.1-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
11:41:31,564  INFO |cacheCacheManagerByLocationJarFileTest| - [logo] main - [127.0.0.1]:5701 [cluster1] [5.1-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
11:41:31,564  INFO |cacheCacheManagerByLocationJarFileTest| - [system] main - [127.0.0.1]:5701 [cluster1] [5.1-SNAPSHOT] Copyright (c) 2008-2021, Hazelcast, Inc. All Rights Reserved.
11:41:31,564  INFO |cacheCacheManagerByLocationJarFileTest| - [system] main - [127.0.0.1]:5701 [cluster1] [5.1-SNAPSHOT] Hazelcast Platform 5.1-SNAPSHOT (20220204 - d2b84ff) starting at [127.0.0.1]:5701
11:41:31,564  INFO |cacheCacheManagerByLocationJarFileTest| - [system] main - [127.0.0.1]:5701 [cluster1] [5.1-SNAPSHOT] Cluster name: cluster1
11:41:31,564  INFO |cacheCacheManagerByLocationJarFileTest| - [system] main - [127.0.0.1]:5701 [cluster1] [5.1-SNAPSHOT] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed.
To enable integrity checker do one of the following: 
  - Change member config using Java API: config.setIntegrityCheckerEnabled(true);;
  - Change XML/YAML configuration property: Set hazelcast.integrity-checker.enabled to true
  - Add system property: -Dhz.integritychecker.enabled=true
  - Add environment variable: HZ_INTEGRITYCHECKER_ENABLED=true
11:41:31,564  INFO |cacheCacheManagerByLocationJarFileTest| - [system] main - [127.0.0.1]:5701 [cluster1] [5.1-SNAPSHOT] The Jet engine is disabled.
To enable the Jet engine on the members, please do one of the following:
  - Change member config using Java API: config.getJetConfig().setEnabled(true);;
  - Change XML/YAML configuration property: Set Set hazelcast.jet.enabled to true
  - Add system property: -Dhz.jet.enabled=true
  - Add environment variable: HZ_JET_ENABLED=true
11:41:31,569  INFO |cacheCacheManagerByLocationJarFileTest| - [MetricsConfigHelper] main - [127.0.0.1]:5701 [cluster1] [5.1-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
11:41:31,581  WARN |cacheCacheManagerByLocationJarFileTest| - [CPSubsystem] main - [127.0.0.1]:5701 [cluster1] [5.1-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
11:41:31,585  INFO |cacheCacheManagerByLocationJarFileTest| - [Diagnostics] main - [127.0.0.1]:5701 [cluster1] [5.1-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
11:41:31,585  INFO |cacheCacheManagerByLocationJarFileTest| - [LifecycleService] main - [127.0.0.1]:5701 [cluster1] [5.1-SNAPSHOT] [127.0.0.1]:5701 is STARTING
11:41:31,588  WARN |cacheCacheManagerByLocationJarFileTest| - [Node] main - [127.0.0.1]:5701 [cluster1] [5.1-SNAPSHOT] No join method is enabled! Starting standalone.
11:41:31,589  INFO |cacheCacheManagerByLocationJarFileTest| - [LifecycleService] main - [127.0.0.1]:5701 [cluster1] [5.1-SNAPSHOT] [127.0.0.1]:5701 is STARTED
11:41:31,590  INFO |cacheCacheManagerByLocationJarFileTest| - [MetricsConfigHelper] main - [LOCAL] [cluster2] [5.1-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
11:41:31,591  INFO |cacheCacheManagerByLocationJarFileTest| - [logo] main - [127.0.0.1]:5702 [cluster2] [5.1-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
11:41:31,591  INFO |cacheCacheManagerByLocationJarFileTest| - [system] main - [127.0.0.1]:5702 [cluster2] [5.1-SNAPSHOT] Copyright (c) 2008-2021, Hazelcast, Inc. All Rights Reserved.
11:41:31,591  INFO |cacheCacheManagerByLocationJarFileTest| - [system] main - [127.0.0.1]:5702 [cluster2] [5.1-SNAPSHOT] Hazelcast Platform 5.1-SNAPSHOT (20220204 - d2b84ff) starting at [127.0.0.1]:5702
11:41:31,591  INFO |cacheCacheManagerByLocationJarFileTest| - [system] main - [127.0.0.1]:5702 [cluster2] [5.1-SNAPSHOT] Cluster name: cluster2
11:41:31,591  INFO |cacheCacheManagerByLocationJarFileTest| - [system] main - [127.0.0.1]:5702 [cluster2] [5.1-SNAPSHOT] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed.
To enable integrity checker do one of the following: 
  - Change member config using Java API: config.setIntegrityCheckerEnabled(true);;
  - Change XML/YAML configuration property: Set hazelcast.integrity-checker.enabled to true
  - Add system property: -Dhz.integritychecker.enabled=true
  - Add environment variable: HZ_INTEGRITYCHECKER_ENABLED=true
11:41:31,591  INFO |cacheCacheManagerByLocationJarFileTest| - [system] main - [127.0.0.1]:5702 [cluster2] [5.1-SNAPSHOT] The Jet engine is disabled.
To enable the Jet engine on the members, please do one of the following:
  - Change member config using Java API: config.getJetConfig().setEnabled(true);;
  - Change XML/YAML configuration property: Set Set hazelcast.jet.enabled to true
  - Add system property: -Dhz.jet.enabled=true
  - Add environment variable: HZ_JET_ENABLED=true
11:41:31,595  INFO |cacheCacheManagerByLocationJarFileTest| - [MetricsConfigHelper] main - [127.0.0.1]:5702 [cluster2] [5.1-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
11:41:31,608  WARN |cacheCacheManagerByLocationJarFileTest| - [CPSubsystem] main - [127.0.0.1]:5702 [cluster2] [5.1-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
11:41:31,612  INFO |cacheCacheManagerByLocationJarFileTest| - [Diagnostics] main - [127.0.0.1]:5702 [cluster2] [5.1-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
11:41:31,612  INFO |cacheCacheManagerByLocationJarFileTest| - [LifecycleService] main - [127.0.0.1]:5702 [cluster2] [5.1-SNAPSHOT] [127.0.0.1]:5702 is STARTING
11:41:31,616  WARN |cacheCacheManagerByLocationJarFileTest| - [Node] main - [127.0.0.1]:5702 [cluster2] [5.1-SNAPSHOT] No join method is enabled! Starting standalone.
11:41:31,616  INFO |cacheCacheManagerByLocationJarFileTest| - [LifecycleService] main - [127.0.0.1]:5702 [cluster2] [5.1-SNAPSHOT] [127.0.0.1]:5702 is STARTED
11:41:32,043  INFO |cacheCacheManagerByLocationJarFileTest| - [LifecycleService] main - [127.0.0.1]:5702 [cluster2] [5.1-SNAPSHOT] [127.0.0.1]:5702 is SHUTTING_DOWN
11:41:32,043  INFO |cacheCacheManagerByLocationJarFileTest| - [Node] main - [127.0.0.1]:5702 [cluster2] [5.1-SNAPSHOT] Shutting down connection manager...
11:41:32,045  INFO |cacheCacheManagerByLocationJarFileTest| - [Node] main - [127.0.0.1]:5702 [cluster2] [5.1-SNAPSHOT] Shutting down node engine...
11:41:32,049  INFO |cacheCacheManagerByLocationJarFileTest| - [NodeExtension] main - [127.0.0.1]:5702 [cluster2] [5.1-SNAPSHOT] Destroying node NodeExtension.
11:41:32,049  INFO |cacheCacheManagerByLocationJarFileTest| - [Node] main - [127.0.0.1]:5702 [cluster2] [5.1-SNAPSHOT] Hazelcast Shutdown is completed in 6 ms.
11:41:32,049  INFO |cacheCacheManagerByLocationJarFileTest| - [LifecycleService] main - [127.0.0.1]:5702 [cluster2] [5.1-SNAPSHOT] [127.0.0.1]:5702 is SHUTDOWN
11:41:32,049  INFO |cacheCacheManagerByLocationJarFileTest| - [LifecycleService] main - [127.0.0.1]:5701 [cluster1] [5.1-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
11:41:32,049  INFO |cacheCacheManagerByLocationJarFileTest| - [Node] main - [127.0.0.1]:5701 [cluster1] [5.1-SNAPSHOT] Shutting down connection manager...
11:41:32,050  INFO |cacheCacheManagerByLocationJarFileTest| - [Node] main - [127.0.0.1]:5701 [cluster1] [5.1-SNAPSHOT] Shutting down node engine...
11:41:32,053  INFO |cacheCacheManagerByLocationJarFileTest| - [NodeExtension] main - [127.0.0.1]:5701 [cluster1] [5.1-SNAPSHOT] Destroying node NodeExtension.
11:41:32,053  INFO |cacheCacheManagerByLocationJarFileTest| - [Node] main - [127.0.0.1]:5701 [cluster1] [5.1-SNAPSHOT] Hazelcast Shutdown is completed in 4 ms.
11:41:32,053  INFO |cacheCacheManagerByLocationJarFileTest| - [LifecycleService] main - [127.0.0.1]:5701 [cluster1] [5.1-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
BuildInfo right after cacheCacheManagerByLocationJarFileTest(com.hazelcast.client.cache.ClientCacheConfigTest): BuildInfo{version='5.1-SNAPSHOT', build='20220204', buildNumber=20220204, revision=d2b84ff, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'cacheCacheManagerByLocationJarFileTest(com.hazelcast.client.cache.ClientCacheConfigTest):'
11:41:30, accumulated pauses: 626 ms, max pause: 396 ms, pauses over 1000 ms: 0
```

</details>

**Comment by olukas** [comment]
Failed again on Windows with OracleJDK8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Windows-OracleJDK8/374/testReport/com.hazelcast.client.cache/ClientCacheConfigTest/cacheCacheManagerByLocationJarFileTest/
