### ISSUE TITLE
com.hazelcast.jet.hadoop.file.CsvFileFormatTest.shouldThrowWhenWrongFormatting

### ISSUE THREAD

**Issue by viliam-durina** [hazelcast/hazelcast#20664]
Failed on PR builder for https://github.com/hazelcast/hazelcast/pull/20658: 
https://jenkins.hazelcast.com/job/Hazelcast-pr-builder/9835/testReport/junit/com.hazelcast.jet.hadoop.file/CsvFileFormatTest/shouldThrowWhenWrongFormatting_1__useHadoop_false_/
https://jenkins.hazelcast.com/job/Hazelcast-pr-builder/9835/testReport/junit/com.hazelcast.jet.hadoop.file/CsvFileFormatTest/shouldThrowWhenWrongFormatting_0__useHadoop_true_/

<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: 

Expecting:
 <"java.util.concurrent.CompletionException: com.hazelcast.jet.JetException: Exception in ProcessorTasklet{078c-2577-6700-0001/files(path=/home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/extensions/hadoop/src/test/resources, glob=file-invalid.csv, hadoop=true#0}: com.fasterxml.jackson.databind.RuntimeJsonMappingException: Too many entries: expected at most 3 (value #3 (2 chars) "14")
 at [Source: (org.apache.hadoop.fs.ChecksumFileSystem$FSDataBoundedInputStream); line: 3, column: 10]
	at java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:375)
	at java.util.concurrent.CompletableFuture.join(CompletableFuture.java:1947)
	at com.hazelcast.jet.Job.join(Job.java:78)
	at com.hazelcast.jet.hadoop.file.BaseFileFormatTest.lambda$assertJobFailed$0(BaseFileFormatTest.java:113)
	at org.assertj.core.api.ThrowableAssert.catchThrowable(ThrowableAssert.java:62)
	at org.assertj.core.api.AssertionsForClassTypes.catchThrowable(AssertionsForClassTypes.java:750)
	at org.assertj.core.api.Assertions.catchThrowable(Assertions.java:1179)
	at org.assertj.core.api.Assertions.assertThatThrownBy(Assertions.java:1051)
	at com.hazelcast.jet.hadoop.file.BaseFileFormatTest.assertJobFailed(BaseFileFormatTest.java:113)
	at com.hazelcast.jet.hadoop.file.CsvFileFormatTest.shouldThrowWhenWrongFormatting(CsvFileFormatTest.java:130)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37)
	at com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:104)
	at com.hazelcast.test.metrics.MetricsRule$1.evaluate(MetricsRule.java:63)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:39)
	at com.hazelcast.test.OverridePropertyRule$1.evaluate(OverridePropertyRule.java:66)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.hazelcast.jet.JetException: Exception in ProcessorTasklet{078c-2577-6700-0001/files(path=/home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/extensions/hadoop/src/test/resources, glob=file-invalid.csv, hadoop=true#0}: com.fasterxml.jackson.databind.RuntimeJsonMappingException: Too many entries: expected at most 3 (value #3 (2 chars) "14")
 at [Source: (org.apache.hadoop.fs.ChecksumFileSystem$FSDataBoundedInputStream); line: 3, column: 10]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService.handleTaskletExecutionError(TaskletExecutionService.java:286)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService.access$600(TaskletExecutionService.java:80)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$BlockingWorker.run(TaskletExecutionService.java:325)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
Caused by: com.fasterxml.jackson.databind.RuntimeJsonMappingException: Too many entries: expected at most 3 (value #3 (2 chars) "14")
 at [Source: (org.apache.hadoop.fs.ChecksumFileSystem$FSDataBoundedInputStream); line: 3, column: 10]
	at com.fasterxml.jackson.databind.MappingIterator._handleMappingException(MappingIterator.java:416)
	at com.fasterxml.jackson.databind.MappingIterator.next(MappingIterator.java:201)
	at com.hazelcast.jet.hadoop.impl.CsvInputFormat$1.nextKeyValue(CsvInputFormat.java:103)
	at com.hazelcast.jet.hadoop.impl.ReadHadoopNewApiP$HadoopFileTraverser.lambda$traverseSplit$1(ReadHadoopNewApiP.java:336)
	at com.hazelcast.jet.impl.util.FlatMappingTraverser.next(FlatMappingTraverser.java:51)
	at com.hazelcast.jet.hadoop.impl.ReadHadoopNewApiP$HadoopFileTraverser.next(ReadHadoopNewApiP.java:352)
	at com.hazelcast.jet.core.AbstractProcessor.emitFromTraverser(AbstractProcessor.java:407)
	at com.hazelcast.jet.core.AbstractProcessor.emitFromTraverser(AbstractProcessor.java:421)
	at com.hazelcast.jet.hadoop.impl.ReadHadoopNewApiP.complete(ReadHadoopNewApiP.java:122)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.complete(ProcessorTasklet.java:491)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:385)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:255)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$BlockingWorker.run(TaskletExecutionService.java:315)
	... 5 more
Caused by: com.fasterxml.jackson.dataformat.csv.CsvReadException: Too many entries: expected at most 3 (value #3 (2 chars) "14")
 at [Source: (org.apache.hadoop.fs.ChecksumFileSystem$FSDataBoundedInputStream); line: 3, column: 10]
	at com.fasterxml.jackson.dataformat.csv.CsvReadException.from(CsvReadException.java:25)
	at com.fasterxml.jackson.dataformat.csv.CsvParser._reportCsvMappingError(CsvParser.java:1331)
	at com.fasterxml.jackson.dataformat.csv.CsvParser._handleExtraColumn(CsvParser.java:1079)
	at com.fasterxml.jackson.dataformat.csv.CsvParser._handleNextEntry(CsvParser.java:931)
	at com.fasterxml.jackson.dataformat.csv.CsvParser.nextFieldName(CsvParser.java:727)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:320)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:176)
	at com.fasterxml.jackson.databind.MappingIterator.nextValue(MappingIterator.java:283)
	at com.fasterxml.jackson.databind.MappingIterator.next(MappingIterator.java:199)
	... 16 more
">
to contain:
 <"com.fasterxml.jackson.dataformat.csv.CsvMappingException"> 
	at com.hazelcast.jet.hadoop.file.BaseFileFormatTest.assertJobFailed(BaseFileFormatTest.java:116)
	at com.hazelcast.jet.hadoop.file.CsvFileFormatTest.shouldThrowWhenWrongFormatting(CsvFileFormatTest.java:130)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37)
	at com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:104)
	at com.hazelcast.test.metrics.MetricsRule$1.evaluate(MetricsRule.java:63)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:39)
	at com.hazelcast.test.OverridePropertyRule$1.evaluate(OverridePropertyRule.java:66)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

</details>

<details><summary>Standard output:</summary>

```
17:49:07,070  INFO || - [FileInputFormat] hz.flamboyant_kepler.cached.thread-1 - Total input files to process : 1
BuildInfo right after shouldThrowWhenWrongFormatting[0: useHadoop=true](com.hazelcast.jet.hadoop.file.CsvFileFormatTest): BuildInfo{version='5.1-SNAPSHOT', build='20220209', buildNumber=20220209, revision=7763e03, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'shouldThrowWhenWrongFormatting[0: useHadoop=true](com.hazelcast.jet.hadoop.file.CsvFileFormatTest):'
17:49:05, accumulated pauses: 589 ms, max pause: 60 ms, pauses over 1000 ms: 0
```

</details>

**Comment by ufukyilmaz** [comment]
It started to fail after this version update: https://github.com/hazelcast/hazelcast/commit/e3f5669d806443128b23c6cf043bdb3825902de7

**Comment by olukas** [comment]
Failed also on:
- Sonar build (Oracle JDK 11): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/1126/testReport/com.hazelcast.jet.hadoop.file/CsvFileFormatTest/shouldThrowWhenWrongFormatting_0__useHadoop_true_/
- RedHat JDK 11: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-RedHatJDK11/18/testReport/com.hazelcast.jet.hadoop.file/CsvFileFormatTest/shouldThrowWhenWrongFormatting_0__useHadoop_true_/
- Openj9-16: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Openj9-16/47/testReport/com.hazelcast.jet.hadoop.file/CsvFileFormatTest/shouldThrowWhenWrongFormatting_0__useHadoop_true_/

**Comment by kwart** [comment]
Pity, the PR builder didn't reveal it in the #20224.
 We can try a downgrade to the 2.12.6 Jackson version.

**Comment by frant-hartm** [comment]
This has been caused by a change in a thrown exception, it is probably safe to change the exception from `CsvMappingException` to `CsvReadException`.
