### ISSUE TITLE
java.lang.UnsupportedOperationException: SQL catalog must never be cleared 

### ISSUE THREAD

**Issue by petrpleshachkov** [hazelcast/hazelcast#20691]
Many sql test generate this error in the console

```
15:34:17,980 ERROR || - [EventServiceImpl] hz.focused_matsumoto.event-1 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] hz.focused_matsumoto.event-1 caught an exception while processing:com.hazelcast.spi.impl.eventservice.impl.LocalEventDispatcher@5107b847
java.lang.UnsupportedOperationException: SQL catalog must never be cleared - MapEvent{entryEventType=CLEAR_ALL, member=Member [127.0.0.1]:5701 - 1cda8c57-b78a-459b-8ed4-06ba0c3ebf24 this, name='__sql.catalog', numberOfEntriesAffected=1}
	at com.hazelcast.jet.sql.impl.schema.TablesStorage$EntryListenerAdapter.mapCleared(TablesStorage.java:202) ~[classes/:?]
	at com.hazelcast.replicatedmap.impl.ReplicatedMapEventPublishingService.dispatchEvent(ReplicatedMapEventPublishingService.java:132) ~[classes/:?]
	at com.hazelcast.replicatedmap.impl.ReplicatedMapService.dispatchEvent(ReplicatedMapService.java:232) ~[classes/:?]
	at com.hazelcast.spi.impl.eventservice.impl.LocalEventDispatcher.run(LocalEventDispatcher.java:64) ~[classes/:?]
	at com.hazelcast.internal.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:245) [classes/:?]
	at com.hazelcast.internal.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:228) [classes/:?]
```

**Comment by k-jamroz** [comment]
In 5.2 and 5.3 we do not use ReplicatedMap for SQL catalog anymore, so the issue should not happen anymore.
