### ISSUE TITLE
com.hazelcast.jet.sql.impl.aggregate.SqlInsertWindowBoundsTest

### ISSUE THREAD

**Issue by slavagithub** [hazelcast/hazelcast#20709]
_master_ (commit b5fa1da109a1ee8c17e31ad0d4480ba1f5c6cf19)

Failed on Corretto, JDK8: [failure report](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-CorrettoJDK8/165/testReport/com.hazelcast.jet.sql.impl.aggregate/SqlInsertWindowBoundsTest/test_windowBoundsSameTypeAsDescriptor_INT/)

<details><summary>Stacktrace:</summary>

```
com.hazelcast.sql.HazelcastSqlException: 
Encountered "(" at line 1, column 96.
Was expecting one of:
    <BRACKET_QUOTED_IDENTIFIER> ...
    <QUOTED_IDENTIFIER> ...
    <BACK_QUOTED_IDENTIFIER> ...
    <BIG_QUERY_BACK_QUOTED_IDENTIFIER> ...
    <HYPHENATED_IDENTIFIER> ...
    <IDENTIFIER> ...
    <UNICODE_QUOTED_IDENTIFIER> ...
    
	at com.hazelcast.sql.impl.QueryUtils.toPublicException(QueryUtils.java:72)
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:206)
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:161)
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:157)
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:153)
	at com.hazelcast.sql.SqlService.execute(SqlService.java:89)
	at com.hazelcast.jet.sql.impl.aggregate.SqlInsertWindowBoundsTest.test_windowBoundsSameTypeAsDescriptor_INT(SqlInsertWindowBoundsTest.java:130)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.hazelcast.sql.impl.QueryException: Encountered "(" at line 1, column 96.
Was expecting one of:
    <BRACKET_QUOTED_IDENTIFIER> ...
    <QUOTED_IDENTIFIER> ...
    <BACK_QUOTED_IDENTIFIER> ...
    <BIG_QUERY_BACK_QUOTED_IDENTIFIER> ...
    <HYPHENATED_IDENTIFIER> ...
    <IDENTIFIER> ...
    <UNICODE_QUOTED_IDENTIFIER> ...
    
	at com.hazelcast.sql.impl.QueryException.error(QueryException.java:65)
	at com.hazelcast.jet.sql.impl.parse.QueryParser.parse(QueryParser.java:68)
	at com.hazelcast.jet.sql.impl.OptimizerContext.parse(OptimizerContext.java:137)
	at com.hazelcast.jet.sql.impl.CalciteSqlOptimizer.prepare(CalciteSqlOptimizer.java:239)
	at com.hazelcast.sql.impl.SqlServiceImpl.prepare(SqlServiceImpl.java:256)
	at com.hazelcast.sql.impl.SqlServiceImpl.query0(SqlServiceImpl.java:236)
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:193)
	... 17 more
Caused by: org.apache.calcite.sql.parser.SqlParseException: Encountered "(" at line 1, column 96.
Was expecting one of:
    <BRACKET_QUOTED_IDENTIFIER> ...
    <QUOTED_IDENTIFIER> ...
    <BACK_QUOTED_IDENTIFIER> ...
    <BIG_QUERY_BACK_QUOTED_IDENTIFIER> ...
    <HYPHENATED_IDENTIFIER> ...
    <IDENTIFIER> ...
    <UNICODE_QUOTED_IDENTIFIER> ...
    
	at com.hazelcast.jet.sql.impl.calcite.parser.HazelcastSqlParser.convertException(HazelcastSqlParser.java:414)
	at com.hazelcast.jet.sql.impl.calcite.parser.HazelcastSqlParser.normalizeException(HazelcastSqlParser.java:178)
	at org.apache.calcite.sql.parser.SqlParser.handleException(SqlParser.java:145)
	at org.apache.calcite.sql.parser.SqlParser.parseStmtList(SqlParser.java:200)
	at com.hazelcast.jet.sql.impl.parse.QueryParser.parse0(QueryParser.java:74)
	at com.hazelcast.jet.sql.impl.parse.QueryParser.parse(QueryParser.java:57)
	... 22 more
Caused by: com.hazelcast.jet.sql.impl.calcite.parser.ParseException: Encountered "(" at line 1, column 96.
Was expecting one of:
    <BRACKET_QUOTED_IDENTIFIER> ...
    <QUOTED_IDENTIFIER> ...
    <BACK_QUOTED_IDENTIFIER> ...
    <BIG_QUERY_BACK_QUOTED_IDENTIFIER> ...
    <HYPHENATED_IDENTIFIER> ...
    <IDENTIFIER> ...
    <UNICODE_QUOTED_IDENTIFIER> ...
    
	at com.hazelcast.jet.sql.impl.calcite.parser.HazelcastSqlParser.generateParseException(HazelcastSqlParser.java:39600)
	at com.hazelcast.jet.sql.impl.calcite.parser.HazelcastSqlParser.jj_consume_token(HazelcastSqlParser.java:39411)
	at com.hazelcast.jet.sql.impl.calcite.parser.HazelcastSqlParser.IdentifierSegment(HazelcastSqlParser.java:23672)
	at com.hazelcast.jet.sql.impl.calcite.parser.HazelcastSqlParser.CompoundIdentifier(HazelcastSqlParser.java:24154)
	at com.hazelcast.jet.sql.impl.calcite.parser.HazelcastSqlParser.ExplicitTable(HazelcastSqlParser.java:12003)
	at com.hazelcast.jet.sql.impl.calcite.parser.HazelcastSqlParser.LeafQuery(HazelcastSqlParser.java:664)
	at com.hazelcast.jet.sql.impl.calcite.parser.HazelcastSqlParser.LeafQueryOrExpr(HazelcastSqlParser.java:17876)
	at com.hazelcast.jet.sql.impl.calcite.parser.HazelcastSqlParser.QueryOrExpr(HazelcastSqlParser.java:17314)
	at com.hazelcast.jet.sql.impl.calcite.parser.HazelcastSqlParser.OrderedQueryOrExpr(HazelcastSqlParser.java:530)
	at com.hazelcast.jet.sql.impl.calcite.parser.HazelcastSqlParser.Arg0(HazelcastSqlParser.java:2338)
	at com.hazelcast.jet.sql.impl.calcite.parser.HazelcastSqlParser.NamedRoutineCall(HazelcastSqlParser.java:8001)
	at com.hazelcast.jet.sql.impl.calcite.parser.HazelcastSqlParser.TableFunctionCall(HazelcastSqlParser.java:11975)
	at com.hazelcast.jet.sql.impl.calcite.parser.HazelcastSqlParser.TableRef2(HazelcastSqlParser.java:11030)
	at com.hazelcast.jet.sql.impl.calcite.parser.HazelcastSqlParser.TableRef(HazelcastSqlParser.java:10905)
	at com.hazelcast.jet.sql.impl.calcite.parser.HazelcastSqlParser.FromClause(HazelcastSqlParser.java:10795)
	at com.hazelcast.jet.sql.impl.calcite.parser.HazelcastSqlParser.SqlSelect(HazelcastSqlParser.java:5956)
	at com.hazelcast.jet.sql.impl.calcite.parser.HazelcastSqlParser.LeafQuery(HazelcastSqlParser.java:656)
	at com.hazelcast.jet.sql.impl.calcite.parser.HazelcastSqlParser.LeafQueryOrExpr(HazelcastSqlParser.java:17876)
	at com.hazelcast.jet.sql.impl.calcite.parser.HazelcastSqlParser.QueryOrExpr(HazelcastSqlParser.java:17314)
	at com.hazelcast.jet.sql.impl.calcite.parser.HazelcastSqlParser.OrderedQueryOrExpr(HazelcastSqlParser.java:530)
	at com.hazelcast.jet.sql.impl.calcite.parser.HazelcastSqlParser.ParenthesizedQueryOrCommaList(HazelcastSqlParser.java:738)
	at com.hazelcast.jet.sql.impl.calcite.parser.HazelcastSqlParser.Expression3(HazelcastSqlParser.java:18304)
	at com.hazelcast.jet.sql.impl.calcite.parser.HazelcastSqlParser.Expression2b(HazelcastSqlParser.java:17922)
	at com.hazelcast.jet.sql.impl.calcite.parser.HazelcastSqlParser.Expression2(HazelcastSqlParser.java:17963)
	at com.hazelcast.jet.sql.impl.calcite.parser.HazelcastSqlParser.Expression(HazelcastSqlParser.java:17893)
	at com.hazelcast.jet.sql.impl.calcite.parser.HazelcastSqlParser.LeafQueryOrExpr(HazelcastSqlParser.java:17870)
	at com.hazelcast.jet.sql.impl.calcite.parser.HazelcastSqlParser.QueryOrExpr(HazelcastSqlParser.java:17314)
	at com.hazelcast.jet.sql.impl.calcite.parser.HazelcastSqlParser.OrderedQueryOrExpr(HazelcastSqlParser.java:530)
	at com.hazelcast.jet.sql.impl.calcite.parser.HazelcastSqlParser.Arg0(HazelcastSqlParser.java:2338)
	at com.hazelcast.jet.sql.impl.calcite.parser.HazelcastSqlParser.NamedRoutineCall(HazelcastSqlParser.java:8001)
	at com.hazelcast.jet.sql.impl.calcite.parser.HazelcastSqlParser.TableFunctionCall(HazelcastSqlParser.java:11975)
	at com.hazelcast.jet.sql.impl.calcite.parser.HazelcastSqlParser.TableRef2(HazelcastSqlParser.java:11030)
	at com.hazelcast.jet.sql.impl.calcite.parser.HazelcastSqlParser.TableRef(HazelcastSqlParser.java:10905)
	at com.hazelcast.jet.sql.impl.calcite.parser.HazelcastSqlParser.FromClause(HazelcastSqlParser.java:10795)
	at com.hazelcast.jet.sql.impl.calcite.parser.HazelcastSqlParser.SqlSelect(HazelcastSqlParser.java:5956)
	at com.hazelcast.jet.sql.impl.calcite.parser.HazelcastSqlParser.LeafQuery(HazelcastSqlParser.java:656)
	at com.hazelcast.jet.sql.impl.calcite.parser.HazelcastSqlParser.LeafQueryOrExpr(HazelcastSqlParser.java:17876)
	at com.hazelcast.jet.sql.impl.calcite.parser.HazelcastSqlParser.QueryOrExpr(HazelcastSqlParser.java:17314)
	at com.hazelcast.jet.sql.impl.calcite.parser.HazelcastSqlParser.OrderedQueryOrExpr(HazelcastSqlParser.java:530)
	at com.hazelcast.jet.sql.impl.calcite.parser.HazelcastSqlParser.SqlStmt(HazelcastSqlParser.java:3893)
	at com.hazelcast.jet.sql.impl.calcite.parser.HazelcastSqlParser.SqlStmtList(HazelcastSqlParser.java:2878)
	at com.hazelcast.jet.sql.impl.calcite.parser.HazelcastSqlParser.parseSqlStmtList(HazelcastSqlParser.java:230)
	at org.apache.calcite.sql.parser.SqlParser.parseStmtList(SqlParser.java:198)
	... 24 more
```

</details>

<details><summary>Standard output:</summary>

```
CREATE MAPPING o_3f06109c_6ed0_4f92_ab39_6dcd31c2a822 TYPE TestStream OPTIONS ('names'='ts,name', 'types'='INTEGER,VARCHAR', 'values'='1,Alice
10,null', 'streaming'='true')
18:17:16,912  INFO |test_windowBoundsSameTypeAsDescriptor_INT| - [PartitionStateManager] test_windowBoundsSameTypeAsDescriptor_INT - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Initializing cluster partition table arrangement...
18:17:17,122 DEBUG || - [JobRepository] hz.affectionate_visvesvaraya.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Job cleanup took 2ms
18:17:17,127  INFO |test_windowBoundsSameTypeAsDescriptor_INT| - [SqlTestSupport] Time-limited test - Removing 0 cached plans in SqlTestSupport.@After
18:17:17,128  INFO |test_windowBoundsSameTypeAsDescriptor_INT| - [SimpleTestInClusterSupport] Time-limited test - Ditching 0 jobs in SimpleTestInClusterSupport.@After: []
18:17:17,128  INFO |test_windowBoundsSameTypeAsDescriptor_INT| - [SimpleTestInClusterSupport] Time-limited test - Destroying 1 distributed objects in SimpleTestInClusterSupport.@After: [hz:impl:replicatedMapService/__sql.catalog]
18:17:17,128 ERROR || - [EventServiceImpl] hz.affectionate_visvesvaraya.event-58 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] hz.affectionate_visvesvaraya.event-58 caught an exception while processing:com.hazelcast.spi.impl.eventservice.impl.LocalEventDispatcher@465a1bda
java.lang.UnsupportedOperationException: SQL catalog must never be cleared - MapEvent{entryEventType=CLEAR_ALL, member=Member [127.0.0.1]:5701 - 517e03a4-3ed4-43a4-9c12-fe893730e09c this, name='__sql.catalog', numberOfEntriesAffected=1}
	at com.hazelcast.jet.sql.impl.schema.TablesStorage$EntryListenerAdapter.mapCleared(TablesStorage.java:202) ~[classes/:?]
	at com.hazelcast.replicatedmap.impl.ReplicatedMapEventPublishingService.dispatchEvent(ReplicatedMapEventPublishingService.java:132) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.replicatedmap.impl.ReplicatedMapService.dispatchEvent(ReplicatedMapService.java:232) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.spi.impl.eventservice.impl.LocalEventDispatcher.run(LocalEventDispatcher.java:64) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.internal.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:245) [hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.internal.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:228) [hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
BuildInfo right after test_windowBoundsSameTypeAsDescriptor_INT(com.hazelcast.jet.sql.impl.aggregate.SqlInsertWindowBoundsTest): BuildInfo{version='5.1-SNAPSHOT', build='20220213', buildNumber=20220213, revision=b5fa1da, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'test_windowBoundsSameTypeAsDescriptor_INT(com.hazelcast.jet.sql.impl.aggregate.SqlInsertWindowBoundsTest):'
18:17:15, accumulated pauses: 217 ms, max pause: 203 ms, pauses over 1000 ms: 0


No metrics recorded during the test
```

</details>

**Comment by slavagithub** [comment]
the same for master, IBM Jdk8 - http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-IbmJDK8/170/testReport/

**Comment by slavagithub** [comment]
fails on Corretto, JDK11 - http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-CorrettoJDK11/158/testReport/

**Comment by viliam-durina** [comment]
It's a syntax error in SQL, fails consistently. But it seems that this test doesn't run as a part of PR builder, any idea why?
