### ISSUE TITLE
com.hazelcast.internal.management.operation.GetMapConfigOperationTest.testMapWithPreconfiguredIndex_addedIndex

### ISSUE THREAD

**Issue by slavagithub** [hazelcast/hazelcast#20710]
_master_ (commit b5fa1da109a1ee8c17e31ad0d4480ba1f5c6cf19)

Failed on sonar: [report faiure](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/1130/testReport/com.hazelcast.internal.management.operation/GetMapConfigOperationTest/testMapWithPreconfiguredIndex_addedIndex/)

<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: 

Actual and expected have the same elements but not in the same order, at index 0 actual element was:
  <IndexConfig{name=map-with-index_hash_second, type=HASH, attributes=[second]}>
whereas expected element was:
  <IndexConfig{name=null, type=SORTED, attributes=[first]}>
when comparing values using field/property by field/property comparator on all fields/properties except ["name"]
Comparators used:
- for elements fields (by type): {Double -> DoubleComparator[precision=1.0E-15], Float -> FloatComparator[precision=1.0E-6]}
- for elements (by type): {Double -> DoubleComparator[precision=1.0E-15], Float -> FloatComparator[precision=1.0E-6]}
	at com.hazelcast.internal.management.operation.GetMapConfigOperationTest.testMapWithPreconfiguredIndex_addedIndex(GetMapConfigOperationTest.java:92)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: mapWithPreconfiguredIndex_empty in 0.046 seconds.
01:01:00,306 DEBUG |testMapWithPreconfiguredIndex_addedIndex| - [JobRepository] hz.youthful_ride.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Job cleanup took 0ms
01:01:00,346  INFO |testMapWithPreconfiguredIndex_addedIndex| - [LifecycleService] Thread-60627 - hz.client_6486 [dev] [5.1-SNAPSHOT] HazelcastClient 5.1-SNAPSHOT (20220213 - b5fa1da) is SHUTTING_DOWN
01:01:00,346  INFO |testMapWithPreconfiguredIndex_addedIndex| - [ClientConnectionManager] Thread-60627 - hz.client_6486 [dev] [5.1-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5701:a56c421b-88f3-445e-801c-f971db3f3eb8, connection: MockedClientConnection{localAddress=[127.0.0.1]:40001, super=ClientConnection{alive=false, connectionId=1, channel=null, remoteAddress=[127.0.0.1]:5701, lastReadTime=2022-02-14 01:01:00.306, lastWriteTime=2022-02-14 01:01:00.005, closedTime=2022-02-14 01:01:00.346, connected server version=5.1-SNAPSHOT}}
01:01:00,346  INFO |testMapWithPreconfiguredIndex_addedIndex| - [LifecycleService] Thread-60627 - hz.client_6486 [dev] [5.1-SNAPSHOT] HazelcastClient 5.1-SNAPSHOT (20220213 - b5fa1da) is CLIENT_DISCONNECTED
01:01:00,346  WARN |testMapWithPreconfiguredIndex_addedIndex| - [TestClientRegistry$MockedServerConnection] pool-19818-thread-1 - Server connection closed: null
01:01:00,346  INFO |testMapWithPreconfiguredIndex_addedIndex| - [MockServer] pool-19818-thread-1 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Removed connection to endpoint: [address=[127.0.0.1]:40001, uuid=85c98ed7-ff59-49cb-9f70-106617343533], connection: MockedNodeConnection{ remoteAddress = [127.0.0.1]:40001, localAddress = [127.0.0.1]:5701, connectionId = 1}
01:01:00,346  WARN |testMapWithPreconfiguredIndex_addedIndex| - [TwoWayBlockableExecutor] pool-19818-thread-1 - Dropping incoming runnable since other end closed. Server Closed EOF. MockedClientConnection{localAddress=[127.0.0.1]:40001, super=ClientConnection{alive=false, connectionId=1, channel=null, remoteAddress=[127.0.0.1]:5701, lastReadTime=2022-02-14 01:01:00.306, lastWriteTime=2022-02-14 01:01:00.005, closedTime=2022-02-14 01:01:00.346, connected server version=5.1-SNAPSHOT}}
01:01:00,346  INFO |testMapWithPreconfiguredIndex_addedIndex| - [ClientEndpointManager] hz.youthful_ride.event-91738 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Destroying ClientEndpoint{connection=MockedNodeConnection{ remoteAddress = [127.0.0.1]:40001, localAddress = [127.0.0.1]:5701, connectionId = 1}, clientUuid=85c98ed7-ff59-49cb-9f70-106617343533, clientName=hz.client_6486, authenticated=true, clientVersion=5.1-SNAPSHOT, creationTime=1644800459999, latest clientAttributes=lastStatisticsCollectionTime=1644800460001,enterprise=false,clientType=JVM,clientVersion=5.1-SNAPSHOT,clusterConnectionTimestamp=1644800459999,clientAddress=127.0.0.1,clientName=hz.client_6486,credentials.principal=null,os.committedVirtualMemorySize=26573066240,os.freePhysicalMemorySize=724643758080,os.freeSwapSpaceSize=4294963200,os.maxFileDescriptorCount=1048576,os.openFileDescriptorCount=643,os.processCpuTime=27255090000000,os.systemLoadAverage=6.13,os.totalPhysicalMemorySize=811309408256,os.totalSwapSpaceSize=4294963200,runtime.availableProcessors=8,runtime.freeMemory=789027360,runtime.maxMemory=2147483648,runtime.totalMemory=2125463552,runtime.uptime=12136188,runtime.usedMemory=1336436192, labels=[]}
01:01:00,346  INFO |testMapWithPreconfiguredIndex_addedIndex| - [LifecycleService] Thread-60627 - hz.client_6486 [dev] [5.1-SNAPSHOT] HazelcastClient 5.1-SNAPSHOT (20220213 - b5fa1da) is SHUTDOWN
01:01:00,346  INFO |testMapWithPreconfiguredIndex_addedIndex| - [LifecycleService] Thread-60627 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
01:01:00,347 DEBUG |testMapWithPreconfiguredIndex_addedIndex| - [JobCoordinationService] Thread-60627 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Added a shutting-down member: a56c421b-88f3-445e-801c-f971db3f3eb8
01:01:00,347  INFO |testMapWithPreconfiguredIndex_addedIndex| - [MigrationManager] hz.youthful_ride.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Shutdown request of Member [127.0.0.1]:5701 - a56c421b-88f3-445e-801c-f971db3f3eb8 this is handled
01:01:00,347  INFO |testMapWithPreconfiguredIndex_addedIndex| - [Node] Thread-60627 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Shutting down connection manager...
01:01:00,347  INFO |testMapWithPreconfiguredIndex_addedIndex| - [Node] Thread-60627 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Shutting down node engine...
01:01:00,348  INFO |testMapWithPreconfiguredIndex_addedIndex| - [NodeExtension] Thread-60627 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Destroying node NodeExtension.
01:01:00,348  INFO |testMapWithPreconfiguredIndex_addedIndex| - [Node] Thread-60627 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Hazelcast Shutdown is completed in 1 ms.
01:01:00,348  INFO |testMapWithPreconfiguredIndex_addedIndex| - [LifecycleService] Thread-60627 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
BuildInfo right after testMapWithPreconfiguredIndex_addedIndex(com.hazelcast.internal.management.operation.GetMapConfigOperationTest): BuildInfo{version='5.1-SNAPSHOT', build='20220213', buildNumber=20220213, revision=b5fa1da, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'testMapWithPreconfiguredIndex_addedIndex(com.hazelcast.internal.management.operation.GetMapConfigOperationTest):'
01:00:55, accumulated pauses: 49 ms, max pause: 7 ms, pauses over 1000 ms: 0
01:01:00, accumulated pauses: 279 ms, max pause: 268 ms, pauses over 1000 ms: 0


No metrics recorded during the test
```

</details>

**Comment by krzysztofslusarski** [comment]
Fixed in https://github.com/hazelcast/hazelcast/pull/20655

**Comment by olukas** [comment]
Failed also on `5.1` release branch on Sonar build (Oracle JDK 11): https://jenkins.hazelcast.com/view/Security%20and%20Compliance/job/hazelcast-sonar-release-4.x/7/testReport/com.hazelcast.internal.management.operation/GetMapConfigOperationTest/testMapWithPreconfiguredIndex_addedIndex/

**Comment by bpoplawski** [comment]
Failed also  on maintenance branch 5.1.1 OracleJDK11 :
https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-OracleJDK11/23/testReport/com.hazelcast.internal.management.operation/GetMapConfigOperationTest/testMapWithPreconfiguredIndex_addedIndex/

**Comment by olukas** [comment]
Failed on `5.1.z` branch with OracleJDK8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-OracleJDK8/24/testReport/com.hazelcast.internal.management.operation/GetMapConfigOperationTest/testMapWithPreconfiguredIndex_addedIndex/

**Comment by olukas** [comment]
Failed on `master` on CorrettoJDK17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-CorrettoJDK17/27/testReport/com.hazelcast.internal.management.operation/GetMapConfigOperationTest/testMapWithPreconfiguredIndex_addedIndex/

**Comment by olukas** [comment]
Failed on `master` on CorrettoJDK8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-CorrettoJDK8/169/testReport/com.hazelcast.internal.management.operation/GetMapConfigOperationTest/testMapWithPreconfiguredIndex_addedIndex/

**Comment by olukas** [comment]
Failed on `5.1.z` branch on ZuluJDK8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-ZuluJDK8/25/testReport/com.hazelcast.internal.management.operation/GetMapConfigOperationTest/testMapWithPreconfiguredIndex_addedIndex/

**Comment by ufukyilmaz** [comment]
Closing it since it's fixed.
