### ISSUE TITLE
com.hazelcast.map.LocalIndexStatsTest.testRemoveTracking

### ISSUE THREAD

**Issue by slavagithub** [hazelcast/hazelcast#20732]
5.0.z (commit https://github.com/hazelcast/hazelcast/commit/2bb01b82c684e8b568df70d0b19a4630a32116b7)

Failed on Zing, JDK8: [failure report](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-ZingJDK8/42/testReport/junit/com.hazelcast.map/LocalIndexStatsTest/testRemoveTracking_format_OBJECT_/)

<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at com.hazelcast.map.LocalIndexStatsTest.testRemoveTracking(LocalIndexStatsTest.java:549)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

</details>

<details><summary>Standard output:</summary>

```
21:07:12,763  INFO |testRemoveTracking[format:OBJECT]| - [LifecycleService] Thread-53360 - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
21:07:12,763  WARN |testRemoveTracking[format:OBJECT]| - [Node] Thread-53360 - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] Terminating forcefully...
21:07:12,763  INFO |testRemoveTracking[format:OBJECT]| - [Node] Thread-53360 - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] Shutting down connection manager...
21:07:12,763  INFO |testRemoveTracking[format:OBJECT]| - [Node] Thread-53360 - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] Shutting down node engine...
Finished Running Test: testQueryCounting_WhenTwoMapsUseIndexesNamedTheSame[format:OBJECT] in 0.312 seconds.
21:07:12,812  INFO |testHitAndQueryCounting_WhenSingleIndexHit[format:OBJECT]| - [LifecycleService] Thread-53357 - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
21:07:12,812  WARN |testHitAndQueryCounting_WhenSingleIndexHit[format:OBJECT]| - [Node] Thread-53357 - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] Terminating forcefully...
21:07:12,812  INFO |testHitAndQueryCounting_WhenSingleIndexHit[format:OBJECT]| - [Node] Thread-53357 - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] Shutting down connection manager...
21:07:12,812  INFO |testHitAndQueryCounting_WhenSingleIndexHit[format:OBJECT]| - [Node] Thread-53357 - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] Shutting down node engine...
21:07:12,848  INFO |testAverageQuerySelectivityCalculation_WhenAllPartitionsArePopulated[format:OBJECT]| - [Diagnostics] Thread-53369 - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
21:07:12,849  INFO |testAverageQuerySelectivityCalculation_WhenAllPartitionsArePopulated[format:OBJECT]| - [LifecycleService] Thread-53369 - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] [127.0.0.1]:5701 is STARTING
21:07:12,849  INFO |testAverageQuerySelectivityCalculation_WhenAllPartitionsArePopulated[format:OBJECT]| - [JetExtension] Thread-53369 - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] Jet is enabled
21:07:12,849  INFO |testAverageQuerySelectivityCalculation_WhenAllPartitionsArePopulated[format:OBJECT]| - [ClusterService] Thread-53369 - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] 

Members {size:1, ver:1} [
	Member [127.0.0.1]:5701 - 1cbba201-902e-4633-a10c-c8f3c5b22bcc this
]

21:07:12,849 DEBUG |testAverageQuerySelectivityCalculation_WhenAllPartitionsArePopulated[format:OBJECT]| - [JobCoordinationService] hz.awesome_mclean.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
21:07:12,849  INFO |testAverageQuerySelectivityCalculation_WhenAllPartitionsArePopulated[format:OBJECT]| - [LifecycleService] Thread-53369 - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] [127.0.0.1]:5701 is STARTED
21:07:12,850  WARN |testQueryCounting[format:OBJECT]| - [CPSubsystem] Thread-53371 - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
21:07:12,857  INFO |testQueryCounting[format:OBJECT]| - [JetServiceBackend] Thread-53371 - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] Setting number of cooperative threads and default parallelism to 2
21:07:12,859  INFO |testQueryCounting[format:OBJECT]| - [Diagnostics] Thread-53371 - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
21:07:12,859  INFO |testQueryCounting[format:OBJECT]| - [LifecycleService] Thread-53371 - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] [127.0.0.1]:5701 is STARTING
21:07:12,860  INFO |testQueryCounting[format:OBJECT]| - [JetExtension] Thread-53371 - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] Jet is enabled
21:07:12,860  INFO |testQueryCounting[format:OBJECT]| - [ClusterService] Thread-53371 - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] 

Members {size:1, ver:1} [
	Member [127.0.0.1]:5701 - f6748800-a399-415d-af0e-ebb890b750ae this
]

21:07:12,871  INFO |testQueryCounting[format:OBJECT]| - [LifecycleService] Thread-53371 - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] [127.0.0.1]:5701 is STARTED
Started Running Test: testUpdateTracking[format:OBJECT]
21:07:12,879  INFO |testUpdateTracking[format:OBJECT]| - [MetricsConfigHelper] Thread-53374 - [LOCAL] [dev] [5.0.3-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
21:07:12,888  INFO |testUpdateTracking[format:OBJECT]| - [logo] Thread-53374 - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
21:07:12,888  INFO |testUpdateTracking[format:OBJECT]| - [system] Thread-53374 - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] Copyright (c) 2008-2021, Hazelcast, Inc. All Rights Reserved.
21:07:12,889  INFO |testUpdateTracking[format:OBJECT]| - [system] Thread-53374 - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] Hazelcast Platform 5.0.3-SNAPSHOT (20220214 - 2bb01b8) starting at [127.0.0.1]:5701
21:07:12,889  INFO |testUpdateTracking[format:OBJECT]| - [system] Thread-53374 - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] Cluster name: dev
21:07:12,890  INFO |testRemoveTracking[format:OBJECT]| - [NodeExtension] Thread-53360 - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] Destroying node NodeExtension.
21:07:12,891  INFO |testRemoveTracking[format:OBJECT]| - [Node] Thread-53360 - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] Hazelcast Shutdown is completed in 128 ms.
21:07:12,891  INFO |testRemoveTracking[format:OBJECT]| - [LifecycleService] Thread-53360 - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
BuildInfo right after testRemoveTracking[format:OBJECT](com.hazelcast.map.LocalIndexStatsTest): BuildInfo{version='5.0.3-SNAPSHOT', build='20220214', buildNumber=20220214, revision=2bb01b8, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'testRemoveTracking[format:OBJECT](com.hazelcast.map.LocalIndexStatsTest):'
21:07:10, accumulated pauses: 2832 ms, max pause: 34 ms, pauses over 1000 ms: 0


No metrics recorded during the test
```

</details>

**Comment by TomaszGaweda** [comment]
Didn't happen since February, cannot reproduce locally after many attempts.
