### ISSUE TITLE
com.hazelcast.client.map.ClientIndexStatsTest.testInsertsTracking

### ISSUE THREAD

**Issue by slavagithub** [hazelcast/hazelcast#20731]
_5.0.z_ (commit 2bb01b82c684e8b568df70d0b19a4630a32116b7)

Failed on Zing, JDK8: [failure report](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-ZingJDK8/42/testReport/junit/com.hazelcast.client.map/ClientIndexStatsTest/testInsertsTracking_format_BINARY_/)

<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at com.hazelcast.map.LocalIndexStatsTest.testInsertsTracking(LocalIndexStatsTest.java:489)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: testHitAndQueryCounting_WhenSingleIndexHit[format:BINARY] in 3.752 seconds.
18:21:56,599  WARN |testRemoveTracking[format:BINARY]| - [TwoWayBlockableExecutor] pool-3438-thread-1 - Dropping incoming runnable since other end closed. Server Closed EOF. MockedClientConnection{localAddress=[127.0.0.1]:40001, super=ClientConnection{alive=false, connectionId=1, channel=null, remoteAddress=[127.0.0.1]:5702, lastReadTime=2022-02-14 18:21:56.495, lastWriteTime=2022-02-14 18:21:56.494, closedTime=2022-02-14 18:21:56.510, connected server version=5.0.3-SNAPSHOT}}
18:21:56,514  WARN |testRemoveTracking[format:BINARY]| - [TestClientRegistry$MockedServerConnection] pool-3440-thread-1 - Server connection closed: null
18:21:56,600  INFO |testRemoveTracking[format:BINARY]| - [MockServer] pool-3440-thread-1 - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:40002, connection: MockedNodeConnection{ remoteAddress = [127.0.0.1]:40002, localAddress = [127.0.0.1]:5701, connectionId = 2}
18:21:56,603  WARN |testRemoveTracking[format:BINARY]| - [TwoWayBlockableExecutor] pool-3440-thread-1 - Dropping incoming runnable since other end closed. Server Closed EOF. MockedClientConnection{localAddress=[127.0.0.1]:40002, super=ClientConnection{alive=false, connectionId=2, channel=null, remoteAddress=[127.0.0.1]:5701, lastReadTime=2022-02-14 18:21:56.495, lastWriteTime=2022-02-14 18:21:56.493, closedTime=2022-02-14 18:21:56.509, connected server version=5.0.3-SNAPSHOT}}
18:21:56,592 DEBUG |testAverageQuerySelectivityCalculation_ChangingNumberOfIndex[format:BINARY]| - [JobCoordinationService] hz.keen_mcclintock.cached.thread-6 - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
18:21:56,561  WARN |testUpdateTracking[format:BINARY]| - [TestClientRegistry$MockedServerConnection] pool-3436-thread-1 - Server connection closed: null
18:21:56,604  INFO |testUpdateTracking[format:BINARY]| - [MockServer] pool-3436-thread-1 - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:40002, connection: MockedNodeConnection{ remoteAddress = [127.0.0.1]:40002, localAddress = [127.0.0.1]:5701, connectionId = 2}
18:21:56,561  INFO |testAverageQueryLatencyTracking[format:BINARY]| - [ClientInvocationService] Thread-3422 - hz.client_1544 [dev] [5.0.3-SNAPSHOT] Running with 2 response threads, dynamic=true
18:21:56,603  INFO |testRemoveTracking[format:BINARY]| - [ClientEndpointManager] hz.friendly_mcclintock.event-12547 - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] Destroying ClientEndpoint{connection=MockedNodeConnection{ remoteAddress = [127.0.0.1]:40002, localAddress = [127.0.0.1]:5701, connectionId = 2}, clientUuid=3a4f63b9-288c-401d-a907-902e204d7b76, clientName=hz.client_1541, authenticated=true, clientVersion=5.0.3-SNAPSHOT, creationTime=1644862916032, latest clientAttributes=lastStatisticsCollectionTime=1644862916049,enterprise=false,clientType=JVM,clientVersion=5.0.3-SNAPSHOT,clusterConnectionTimestamp=1644862916024,clientAddress=127.0.0.1,clientName=hz.client_1541,credentials.principal=null,os.committedVirtualMemorySize=35705152839680,os.freePhysicalMemorySize=19518021632,os.freeSwapSpaceSize=0,os.maxFileDescriptorCount=65535,os.openFileDescriptorCount=301,os.processCpuTime=5080870000000,os.systemLoadAverage=9.78,os.totalPhysicalMemorySize=31992725504,os.totalSwapSpaceSize=0,runtime.availableProcessors=4,runtime.freeMemory=2457858048,runtime.maxMemory=3491753984,runtime.totalMemory=3491753984,runtime.uptime=2100457,runtime.usedMemory=1033895936, labels=[]}
18:21:56,608 DEBUG |testAverageQueryLatencyTracking[format:BINARY]| - [JobCoordinationService] hz.pedantic_mcclintock.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
18:21:56,599  INFO |testRemoveTracking[format:BINARY]| - [ClientEndpointManager] hz.focused_mcclintock.event-12548 - [127.0.0.1]:5702 [dev] [5.0.3-SNAPSHOT] Destroying ClientEndpoint{connection=MockedNodeConnection{ remoteAddress = [127.0.0.1]:40001, localAddress = [127.0.0.1]:5702, connectionId = 1}, clientUuid=3a4f63b9-288c-401d-a907-902e204d7b76, clientName=hz.client_1541, authenticated=true, clientVersion=5.0.3-SNAPSHOT, creationTime=1644862915981, latest clientAttributes=null, labels=[]}
18:21:56,608 TRACE |testQueryCounting_WhenPartitionPredicateIsUsed[format:BINARY]| - [ClientListenerService] ForkJoinPool.commonPool-worker-2 - hz.client_1543 [dev] [5.0.3-SNAPSHOT] Registered ClusterViewListenerHandler to MockedClientConnection{localAddress=[127.0.0.1]:40001, super=ClientConnection{alive=true, connectionId=1, channel=null, remoteAddress=[127.0.0.1]:5702, lastReadTime=2022-02-14 18:21:56.608, lastWriteTime=2022-02-14 18:21:56.485, closedTime=never, connected server version=5.0.3-SNAPSHOT}}
18:21:56,609  INFO |testUpdateTracking[format:BINARY]| - [ClientConnectionManager] Thread-3409 - hz.client_1540 [dev] [5.0.3-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5701:df42c16b-9c4f-4a1b-b580-a3a9daf73346, connection: MockedClientConnection{localAddress=[127.0.0.1]:40002, super=ClientConnection{alive=false, connectionId=2, channel=null, remoteAddress=[127.0.0.1]:5701, lastReadTime=2022-02-14 18:21:56.413, lastWriteTime=2022-02-14 18:21:56.413, closedTime=2022-02-14 18:21:56.561, connected server version=5.0.3-SNAPSHOT}}
18:21:56,609  INFO |testUpdateTracking[format:BINARY]| - [LifecycleService] Thread-3409 - hz.client_1540 [dev] [5.0.3-SNAPSHOT] HazelcastClient 5.0.3-SNAPSHOT (20220214 - 2bb01b8) is CLIENT_DISCONNECTED
18:21:56,610  WARN |testUpdateTracking[format:BINARY]| - [TwoWayBlockableExecutor] pool-3436-thread-1 - Dropping incoming runnable since other end closed. Server Closed EOF. MockedClientConnection{localAddress=[127.0.0.1]:40002, super=ClientConnection{alive=false, connectionId=2, channel=null, remoteAddress=[127.0.0.1]:5701, lastReadTime=2022-02-14 18:21:56.413, lastWriteTime=2022-02-14 18:21:56.413, closedTime=2022-02-14 18:21:56.561, connected server version=5.0.3-SNAPSHOT}}
18:21:56,611  INFO |testUpdateTracking[format:BINARY]| - [ClientEndpointManager] hz.sweet_mcclintock.event-12545 - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] Destroying ClientEndpoint{connection=MockedNodeConnection{ remoteAddress = [127.0.0.1]:40002, localAddress = [127.0.0.1]:5701, connectionId = 2}, clientUuid=fa685137-1366-4cf4-b2ca-e0ef60320065, clientName=hz.client_1540, authenticated=true, clientVersion=5.0.3-SNAPSHOT, creationTime=1644862915923, latest clientAttributes=null, labels=[]}
18:21:56,622 DEBUG |testQueryCounting_WhenPartitionPredicateIsUsed[format:BINARY]| - [JobCoordinationService] hz.jovial_mcclintock.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
18:21:56,642  INFO |testQueryCounting_WhenPartitionPredicateIsUsed[format:BINARY]| - [ClientClusterService] hz.client_1543.event-12585 - hz.client_1543 [dev] [5.0.3-SNAPSHOT] 

Members [2] {
	Member [127.0.0.1]:5701 - 29d8e384-3d9c-4c60-a670-426d1f932e10
	Member [127.0.0.1]:5702 - d8e59e99-c036-4379-998f-599b6aa3e23e
}

18:21:56,652  INFO |testQueryCounting_WhenPartitionPredicateIsUsed[format:BINARY]| - [HazelcastClient] Thread-3417 - Created connection to endpoint: [127.0.0.1]:5701, connection: MockedClientConnection{localAddress=[127.0.0.1]:40002, super=ClientConnection{alive=true, connectionId=2, channel=null, remoteAddress=null, lastReadTime=never, lastWriteTime=never, closedTime=never, connected server version=null}}
18:21:56,686  INFO |testRemoveTracking[format:BINARY]| - [LifecycleService] Thread-3412 - [127.0.0.1]:5702 [dev] [5.0.3-SNAPSHOT] [127.0.0.1]:5702 is SHUTTING_DOWN
18:21:56,686  WARN |testRemoveTracking[format:BINARY]| - [Node] Thread-3412 - [127.0.0.1]:5702 [dev] [5.0.3-SNAPSHOT] Terminating forcefully...
18:21:56,686  INFO |testRemoveTracking[format:BINARY]| - [Node] Thread-3412 - [127.0.0.1]:5702 [dev] [5.0.3-SNAPSHOT] Shutting down connection manager...
18:21:56,686  INFO |testRemoveTracking[format:BINARY]| - [MockServer] Thread-3412 - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5702, connection: MockConnection{localEndpoint=[127.0.0.1]:5701, remoteEndpoint=[127.0.0.1]:5702, alive=false}
18:21:56,686  INFO |testRemoveTracking[format:BINARY]| - [MockServer] Thread-3412 - [127.0.0.1]:5702 [dev] [5.0.3-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5701, connection: MockConnection{localEndpoint=[127.0.0.1]:5702, remoteEndpoint=[127.0.0.1]:5701, alive=false}
18:21:56,686  INFO |testRemoveTracking[format:BINARY]| - [MembershipManager] Thread-3412 - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] Removing Member [127.0.0.1]:5702 - 2a994a78-8df6-4026-adc8-b29546b391e6
18:21:56,686  INFO |testRemoveTracking[format:BINARY]| - [PartitionStateManager] Thread-3412 - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] Storing snapshot of partition assignments while removing UUID 2a994a78-8df6-4026-adc8-b29546b391e6
18:21:56,687  INFO |testRemoveTracking[format:BINARY]| - [ClusterService] Thread-3412 - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] 

Members {size:1, ver:3} [
	Member [127.0.0.1]:5701 - e6c300d7-8264-4865-bcf5-360fa8abbcb1 this
]

18:21:56,687  INFO |testRemoveTracking[format:BINARY]| - [Node] Thread-3412 - [127.0.0.1]:5702 [dev] [5.0.3-SNAPSHOT] Shutting down node engine...
18:21:56,689  INFO |testInsertsTracking[format:BINARY]| - [Node] Thread-3405 - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] Hazelcast Shutdown is completed in 175 ms.
18:21:56,689  INFO |testInsertsTracking[format:BINARY]| - [LifecycleService] Thread-3405 - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
BuildInfo right after testInsertsTracking[format:BINARY](com.hazelcast.client.map.ClientIndexStatsTest): BuildInfo{version='5.0.3-SNAPSHOT', build='20220214', buildNumber=20220214, revision=2bb01b8, enterprise=false, serializationVersion=1}
18:21:56,690  INFO |testRemoveTracking[format:BINARY]| - [TransactionManagerService] hz.friendly_mcclintock.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] Committing/rolling-back live transactions of [127.0.0.1]:5702, UUID: 2a994a78-8df6-4026-adc8-b29546b391e6
Hiccups measured while running test 'testInsertsTracking[format:BINARY](com.hazelcast.client.map.ClientIndexStatsTest):'
18:21:50, accumulated pauses: 4922 ms, max pause: 28 ms, pauses over 1000 ms: 0
18:21:55, accumulated pauses: 1656 ms, max pause: 27 ms, pauses over 1000 ms: 0


No metrics recorded during the test
18:21:56,695  INFO |testAverageQueryLatencyTracking[format:BINARY]| - [LifecycleService] Thread-3422 - hz.client_1544 [dev] [5.0.3-SNAPSHOT] HazelcastClient 5.0.3-SNAPSHOT (20220214 - 2bb01b8) is STARTING
18:21:56,703  INFO |testAverageQueryLatencyTracking[format:BINARY]| - [LifecycleService] Thread-3422 - hz.client_1544 [dev] [5.0.3-SNAPSHOT] HazelcastClient 5.0.3-SNAPSHOT (20220214 - 2bb01b8) is STARTED
18:21:56,704  INFO |testAverageQueryLatencyTracking[format:BINARY]| - [ClientConnectionManager] Thread-3422 - hz.client_1544 [dev] [5.0.3-SNAPSHOT] Trying to connect to cluster: dev
18:21:56,704  INFO |testAverageQueryLatencyTracking[format:BINARY]| - [ClientConnectionManager] Thread-3422 - hz.client_1544 [dev] [5.0.3-SNAPSHOT] Trying to connect to [127.0.0.1]:5702
18:21:56,704  INFO |testAverageQueryLatencyTracking[format:BINARY]| - [HazelcastClient] Thread-3422 - Created connection to endpoint: [127.0.0.1]:5702, connection: MockedClientConnection{localAddress=[127.0.0.1]:40001, super=ClientConnection{alive=true, connectionId=1, channel=null, remoteAddress=null, lastReadTime=never, lastWriteTime=never, closedTime=never, connected server version=null}}
18:21:56,704  INFO |testUpdateTracking[format:BINARY]| - [LifecycleService] Thread-3409 - hz.client_1540 [dev] [5.0.3-SNAPSHOT] HazelcastClient 5.0.3-SNAPSHOT (20220214 - 2bb01b8) is SHUTDOWN
18:21:56,705 DEBUG |testAverageQuerySelectivityCalculation_ChangingNumberOfIndex[format:BINARY]| - [JobCoordinationService] hz.keen_mcclintock.cached.thread-6 - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
18:21:56,707  INFO |testUpdateTracking[format:BINARY]| - [LifecycleService] Thread-3409 - [127.0.0.1]:5702 [dev] [5.0.3-SNAPSHOT] [127.0.0.1]:5702 is SHUTTING_DOWN
18:21:56,707  WARN |testUpdateTracking[format:BINARY]| - [Node] Thread-3409 - [127.0.0.1]:5702 [dev] [5.0.3-SNAPSHOT] Terminating forcefully...
18:21:56,707  INFO |testUpdateTracking[format:BINARY]| - [Node] Thread-3409 - [127.0.0.1]:5702 [dev] [5.0.3-SNAPSHOT] Shutting down connection manager...
18:21:56,707  INFO |testUpdateTracking[format:BINARY]| - [MockServer] Thread-3409 - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5702, connection: MockConnection{localEndpoint=[127.0.0.1]:5701, remoteEndpoint=[127.0.0.1]:5702, alive=false}
18:21:56,707  INFO |testUpdateTracking[format:BINARY]| - [MockServer] Thread-3409 - [127.0.0.1]:5702 [dev] [5.0.3-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5701, connection: MockConnection{localEndpoint=[127.0.0.1]:5702, remoteEndpoint=[127.0.0.1]:5701, alive=false}
18:21:56,707  INFO |testUpdateTracking[format:BINARY]| - [MembershipManager] Thread-3409 - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] Removing Member [127.0.0.1]:5702 - ee34ea13-d2a6-46fb-9fb6-ed8eddd708e6
18:21:56,707  INFO |testUpdateTracking[format:BINARY]| - [PartitionStateManager] Thread-3409 - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] Storing snapshot of partition assignments while removing UUID ee34ea13-d2a6-46fb-9fb6-ed8eddd708e6
18:21:56,708  INFO |testUpdateTracking[format:BINARY]| - [ClusterService] Thread-3409 - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] 

Members {size:1, ver:3} [
	Member [127.0.0.1]:5701 - df42c16b-9c4f-4a1b-b580-a3a9daf73346 this
]

18:21:56,708  INFO |testUpdateTracking[format:BINARY]| - [Node] Thread-3409 - [127.0.0.1]:5702 [dev] [5.0.3-SNAPSHOT] Shutting down node engine...
18:21:56,709 DEBUG |testAverageQueryLatencyTracking[format:BINARY]| - [JobCoordinationService] hz.pedantic_mcclintock.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
18:21:56,714  INFO |testUpdateTracking[format:BINARY]| - [TransactionManagerService] hz.sweet_mcclintock.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] Committing/rolling-back live transactions of [127.0.0.1]:5702, UUID: ee34ea13-d2a6-46fb-9fb6-ed8eddd708e6
18:21:56,723 DEBUG |testQueryCounting_WhenPartitionPredicateIsUsed[format:BINARY]| - [JobCoordinationService] hz.jovial_mcclintock.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
18:21:56,728  INFO |testRemoveTracking[format:BINARY]| - [NodeExtension] Thread-3412 - [127.0.0.1]:5702 [dev] [5.0.3-SNAPSHOT] Destroying node NodeExtension.
18:21:56,728  INFO |testRemoveTracking[format:BINARY]| - [Node] Thread-3412 - [127.0.0.1]:5702 [dev] [5.0.3-SNAPSHOT] Hazelcast Shutdown is completed in 42 ms.
18:21:56,728  INFO |testRemoveTracking[format:BINARY]| - [LifecycleService] Thread-3412 - [127.0.0.1]:5702 [dev] [5.0.3-SNAPSHOT] [127.0.0.1]:5702 is SHUTDOWN
18:21:56,728  INFO |testRemoveTracking[format:BINARY]| - [LifecycleService] Thread-3412 - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
18:21:56,728  WARN |testRemoveTracking[format:BINARY]| - [Node] Thread-3412 - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] Terminating forcefully...
18:21:56,728  INFO |testRemoveTracking[format:BINARY]| - [Node] Thread-3412 - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] Shutting down connection manager...
18:21:56,728  INFO |testRemoveTracking[format:BINARY]| - [Node] Thread-3412 - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] Shutting down node engine...
18:21:56,729  INFO |testUpdateTracking[format:BINARY]| - [NodeExtension] Thread-3409 - [127.0.0.1]:5702 [dev] [5.0.3-SNAPSHOT] Destroying node NodeExtension.
18:21:56,732  INFO |testUpdateTracking[format:BINARY]| - [Node] Thread-3409 - [127.0.0.1]:5702 [dev] [5.0.3-SNAPSHOT] Hazelcast Shutdown is completed in 25 ms.
18:21:56,732  INFO |testUpdateTracking[format:BINARY]| - [LifecycleService] Thread-3409 - [127.0.0.1]:5702 [dev] [5.0.3-SNAPSHOT] [127.0.0.1]:5702 is SHUTDOWN
18:21:56,732  INFO |testUpdateTracking[format:BINARY]| - [LifecycleService] Thread-3409 - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
18:21:56,732  WARN |testUpdateTracking[format:BINARY]| - [Node] Thread-3409 - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] Terminating forcefully...
18:21:56,732  INFO |testUpdateTracking[format:BINARY]| - [Node] Thread-3409 - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] Shutting down connection manager...
18:21:56,732  INFO |testUpdateTracking[format:BINARY]| - [Node] Thread-3409 - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] Shutting down node engine...
18:21:56,733  WARN |testRemoveTracking[format:BINARY]| - [Invocation] hz.friendly_mcclintock.priority-generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] Future.complete(Object) on completed future. Request: Invocation{op=com.hazelcast.internal.partition.operation.PromotionCommitOperation{serviceName='hz:core:partitionService', identityHash=908575064, partitionId=-1, replicaIndex=0, callId=-147, invocationTime=1644862916693 (2022-02-14 18:21:56.693), waitTimeout=-1, callTimeout=60000, tenantControl=com.hazelcast.spi.impl.tenantcontrol.NoopTenantControl@0}, tryCount=2147483647, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=60000, firstInvocationTimeMs=1644862916693, firstInvocationTime='2022-02-14 18:21:56.693', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 00:00:00.000', target=[127.0.0.1]:5701, pendingResponse={VOID}, backupsAcksExpected=-1, backupsAcksReceived=0, connection=null}, current value: ExceptionalResult{cause=com.hazelcast.core.HazelcastInstanceNotActiveException: Hazelcast instance is not active!}, offered value: true
java.lang.Exception: null
	at com.hazelcast.spi.impl.AbstractInvocationFuture.warnIfSuspiciousDoubleCompletion(AbstractInvocationFuture.java:1253) [classes/:?]
	at com.hazelcast.spi.impl.AbstractInvocationFuture.complete0(AbstractInvocationFuture.java:1230) [classes/:?]
	at com.hazelcast.spi.impl.AbstractInvocationFuture.complete(AbstractInvocationFuture.java:1219) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.complete(Invocation.java:672) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.sendResponse(Invocation.java:235) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.Operation.sendResponse(Operation.java:475) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:282) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:248) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:213) [classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:175) [classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:139) [classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123) [classes/:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) [classes/:?]
```

</details>

**Comment by olukas** [comment]
Failed on `5.1.z` on ZingJDK8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-ZingJDK8/89/testReport/com.hazelcast.client.map/ClientIndexStatsTest/testInsertsTracking_format_OBJECT_/

**Comment by orcunc** [comment]
This issue is probably related to LocalIndexStatsTest.testInsertsTracking https://github.com/hazelcast/hazelcast/issues/19375 
ClientIndexStatsTest test inherits from LocalIndexStatsTest, so if LocalIndexStatsTest is resolved, this test case may also be fixed
