### ISSUE TITLE
com.hazelcast.jet.sql.impl.aggregate.SqlHopTest.test_groupByHaving

### ISSUE THREAD

**Issue by slavagithub** [hazelcast/hazelcast#20759]
_master_ (commit a893a4333d3d2de11854d977f569810a248a29f8)

Failed on Oracle 11: [failure report](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/1134/testReport/com.hazelcast.jet.sql.impl.aggregate/SqlHopTest/test_groupByHaving/)

<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: 

Actual and expected have the same elements but not in the same order, at index 1 actual element was:
  <Row{[1970-01-01T00:00:00.004Z, Alice-s]}>
whereas expected element was:
  <Row{[1970-01-01T00:00Z, Alice-s]}>

	at com.hazelcast.jet.sql.SqlTestSupport.assertTipOfStream(SqlTestSupport.java:246)
	at com.hazelcast.jet.sql.impl.aggregate.SqlHopTest.test_groupByHaving(SqlHopTest.java:429)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: test_validArguments_time in 0.009 seconds.
Started Running Test: test_groupByHaving
03:34:05,246 ERROR || - [EventServiceImpl] hz.epic_almeida.event-1709 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] hz.epic_almeida.event-1709 caught an exception while processing:com.hazelcast.spi.impl.eventservice.impl.LocalEventDispatcher@803c369
java.lang.UnsupportedOperationException: SQL catalog must never be cleared - MapEvent{entryEventType=CLEAR_ALL, member=Member [127.0.0.1]:5701 - 87844f6b-634e-4756-bcfb-b26e23c4f7d0 this, name='__sql.catalog', numberOfEntriesAffected=1}
	at com.hazelcast.jet.sql.impl.schema.TablesStorage$EntryListenerAdapter.mapCleared(TablesStorage.java:202) ~[classes/:?]
	at com.hazelcast.replicatedmap.impl.ReplicatedMapEventPublishingService.dispatchEvent(ReplicatedMapEventPublishingService.java:132) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.replicatedmap.impl.ReplicatedMapService.dispatchEvent(ReplicatedMapService.java:232) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.spi.impl.eventservice.impl.LocalEventDispatcher.run(LocalEventDispatcher.java:64) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.internal.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:245) [hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.internal.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:228) [hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
CREATE MAPPING o_f061c60f_3b1a_476d_a04f_006511f84ceb TYPE TestStream OPTIONS ('names'='ts,name,distance', 'types'='TIMESTAMP_WITH_TIME_ZONE,VARCHAR,INTEGER', 'values'='1970-01-01T00:00Z,Alice,1
1970-01-01T00:00:00.001Z,Alice,1
1970-01-01T00:00:00.002Z,Bob,1
1970-01-01T00:00:00.007Z,Alice,1
1970-01-01T00:00:00.010Z,Alice,1', 'streaming'='true')
03:34:05,251 DEBUG |test_groupByHaving| - [CalciteSqlOptimizer] Thread-1346 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Before logical opt:
LogicalProject(window_start=[$0], n=[||($1, _UTF-16LE'-s':VARCHAR CHARACTER SET "UTF-16LE")])
  LogicalFilter(condition=[>(LENGTH(||($1, _UTF-16LE'-s':VARCHAR CHARACTER SET "UTF-16LE")), 5)])
    LogicalAggregate(group=[{0, 1}])
      LogicalProject(window_start=[$3], name=[$1])
        LogicalTableFunctionScan(invocation=[HOP($2, DESCRIPTOR($0), 4:INTERVAL DAY TO SECOND, 2:INTERVAL DAY TO SECOND)], rowType=[RecordType(TIMESTAMP WITH TIME ZONE ts, VARCHAR name, INTEGER distance, TIMESTAMP WITH TIME ZONE window_start, TIMESTAMP WITH TIME ZONE window_end)])
          LogicalProject(ts=[$0], name=[$1], distance=[$2])
            LogicalTableFunctionScan(invocation=[IMPOSE_ORDER($2, DESCRIPTOR($0), 2:INTERVAL DAY TO SECOND)], rowType=[RecordType(TIMESTAMP WITH TIME ZONE ts, VARCHAR name, INTEGER distance)])
              LogicalProject(ts=[$0], name=[$1], distance=[$2])
                LogicalTableScan(table=[[hazelcast, public, o_f061c60f_3b1a_476d_a04f_006511f84ceb[projects=[$0, $1, $2]]]])

03:34:05,253 DEBUG |test_groupByHaving| - [CalciteSqlOptimizer] Thread-1346 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] After logical opt:
ProjectLogicalRel(window_start=[$0], n=[||($1, _UTF-16LE'-s':VARCHAR CHARACTER SET "UTF-16LE")])
  AggregateLogicalRel(group=[{0, 1}])
    ProjectLogicalRel(window_start=[$3], name=[$1])
      SlidingWindowLogicalRel(invocation=[HOP($2, DESCRIPTOR($0), 4:INTERVAL DAY TO SECOND, 2:INTERVAL DAY TO SECOND)], rowType=[RecordType(TIMESTAMP WITH TIME ZONE ts, VARCHAR name, INTEGER distance, TIMESTAMP WITH TIME ZONE window_start, TIMESTAMP WITH TIME ZONE window_end)])
        FullScanLogicalRel(table=[[hazelcast, public, o_f061c60f_3b1a_476d_a04f_006511f84ceb[projects=[$0, $1, $2], filter=>(LENGTH(||($1, _UTF-16LE'-s':VARCHAR CHARACTER SET "UTF-16LE")), 5)]]], eventTimePolicyProvider=[com.hazelcast.jet.sql.impl.opt.logical.WatermarkRules$1$$Lambda$3114/0x0000000100cb3840@7703accb], watermarkedColumnIndex=[0])

03:34:05,254 DEBUG |test_groupByHaving| - [CalciteSqlOptimizer] Thread-1346 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] After physical opt:
ProjectPhysicalRel(window_start=[$0], n=[||($1, _UTF-16LE'-s':VARCHAR CHARACTER SET "UTF-16LE")])
  SlidingWindowAggregatePhysicalRel(group=[{0, 1}])
    ProjectPhysicalRel(window_start=[$0], name=[$1])
      FullScanPhysicalRel(table=[[hazelcast, public, o_f061c60f_3b1a_476d_a04f_006511f84ceb[projects=[$0, $1, $2], filter=>(LENGTH(||($1, _UTF-16LE'-s':VARCHAR CHARACTER SET "UTF-16LE")), 5)]]], eventTimePolicyProvider=[com.hazelcast.jet.sql.impl.opt.logical.WatermarkRules$1$$Lambda$3114/0x0000000100cb3840@7703accb], watermarkedColumnIndex=[0])

03:34:05,256 DEBUG |test_groupByHaving| - [LightMasterContext] Thread-1346 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Start executing light job 0796-f80a-ade8-0001, execution graph in DOT format:
digraph DAG {
	"TestStream[public.o_f061c60f_3b1a_476d_a04f_006511f84ceb]" [localParallelism=1];
	"Project-2" [localParallelism=default];
	"Sliding-Window-AccumulateByKey" [localParallelism=default];
	"Sliding-Window-CombineByKey" [localParallelism=default];
	"Project" [localParallelism=default];
	"ClientSink" [localParallelism=1];
	"TestStream[public.o_f061c60f_3b1a_476d_a04f_006511f84ceb]" -> "Project-2" [queueSize=1024];
	"Project-2" -> "Sliding-Window-AccumulateByKey" [label="partitioned", queueSize=1024];
	"Sliding-Window-AccumulateByKey" -> "Sliding-Window-CombineByKey" [label="distributed-partitioned", queueSize=1024];
	"Sliding-Window-CombineByKey" -> "Project" [queueSize=1024];
	"Project" -> "ClientSink" [label="distributed to [127.0.0.1]:5701-partitioned", queueSize=1024];
}
HINT: You can use graphviz or http://viz-js.com/ to visualize the printed graph.
03:34:05,256 DEBUG |test_groupByHaving| - [LightMasterContext] Thread-1346 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Building execution plan for 0796-f80a-ade8-0001
03:34:05,256 DEBUG |test_groupByHaving| - [LightMasterContext] Thread-1346 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Built execution plans for 0796-f80a-ade8-0001
03:34:05,256 DEBUG |test_groupByHaving| - [InitExecutionOperation] Thread-1346 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Initializing execution plan for job 0796-f80a-ade8-0001, execution 0796-f80a-ade8-0001 from [127.0.0.1]:5701
03:34:05,257 DEBUG |test_groupByHaving| - [JobExecutionService] Thread-1346 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Execution plan for light job ID=0796-f80a-ade8-0001, jobName='0796-f80a-ade8-0001', executionId=0796-f80a-ade8-0001 initialized, will start the execution
03:34:05,259 DEBUG || - [TaskletExecutionService] hz.epic_almeida.jet.cooperative.thread-0 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Job was cancelled by the user.
03:34:05,384 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-5 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Completed execution of job '0796-f80a-ade8-0001', execution 0796-f80a-ade8-0001
03:34:05,384 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-5 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Execution of job '0796-f80a-ade8-0001', execution 0796-f80a-ade8-0001 completed with failure
java.util.concurrent.CompletionException: java.util.concurrent.CancellationException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:870) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088) ~[?:?]
	at com.hazelcast.jet.impl.util.NonCompletableFuture.internalCompleteExceptionally(NonCompletableFuture.java:72) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$ExecutionTracker.taskletDone(TaskletExecutionService.java:495) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$BlockingWorker.run(TaskletExecutionService.java:330) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) ~[?:?]
Caused by: java.util.concurrent.CancellationException
	at com.hazelcast.jet.sql.impl.processors.RootResultConsumerSink.tryProcess(RootResultConsumerSink.java:97) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.lambda$stateMachineStep$2(ProcessorTasklet.java:297) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.jet.impl.util.Util.doWithClassLoader(Util.java:536) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:297) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:255) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:401) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807) ~[?:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.run(TaskletExecutionService.java:369) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	... 1 more
BuildInfo right after test_groupByHaving(com.hazelcast.jet.sql.impl.aggregate.SqlHopTest): BuildInfo{version='5.1-SNAPSHOT', build='20220217', buildNumber=20220217, revision=a893a43, enterprise=false, serializationVersion=1}
03:34:05,388 ERROR || - [EventServiceImpl] hz.epic_almeida.event-1709 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] hz.epic_almeida.event-1709 caught an exception while processing:com.hazelcast.spi.impl.eventservice.impl.LocalEventDispatcher@6b22d334
java.lang.UnsupportedOperationException: SQL catalog must never be cleared - MapEvent{entryEventType=CLEAR_ALL, member=Member [127.0.0.1]:5701 - 87844f6b-634e-4756-bcfb-b26e23c4f7d0 this, name='__sql.catalog', numberOfEntriesAffected=1}
	at com.hazelcast.jet.sql.impl.schema.TablesStorage$EntryListenerAdapter.mapCleared(TablesStorage.java:202) ~[classes/:?]
	at com.hazelcast.replicatedmap.impl.ReplicatedMapEventPublishingService.dispatchEvent(ReplicatedMapEventPublishingService.java:132) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.replicatedmap.impl.ReplicatedMapService.dispatchEvent(ReplicatedMapService.java:232) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.spi.impl.eventservice.impl.LocalEventDispatcher.run(LocalEventDispatcher.java:64) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.internal.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:245) [hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.internal.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:228) [hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
Hiccups measured while running test 'test_groupByHaving(com.hazelcast.jet.sql.impl.aggregate.SqlHopTest):'
03:34:05, accumulated pauses: 116 ms, max pause: 115 ms, pauses over 1000 ms: 0


No metrics recorded during the test
```

</details>

**Comment by olukas** [comment]
Moving this into `5.1` milestone. This seems to be stable failure (it failed in every release testsuite run). 
@Fly-Style can you please send the fox also to `5.1` branch and to `5.1.z` branch?
