### ISSUE TITLE
com.hazelcast.client.config.ClientFailoverConfigResolutionTest

### ISSUE THREAD

**Issue by slavagithub** [hazelcast/hazelcast#20785]
_master_ (commit e3b1f61efe9f94214e70788126520e6393b19a71)

Failed on Corretto, JDK8: [failure report](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-CorrettoJDK8/166/testReport/com.hazelcast.client.config/ClientFailoverConfigResolutionTest/testResolveSystemProperty_classpath_xml_loadedAsXml/)

<details><summary>Stacktrace:</summary>

```
com.hazelcast.core.HazelcastException: org.xml.sax.SAXParseException; schema_reference.4: Failed to read schema document 'null', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.
	at com.hazelcast.internal.util.ExceptionUtil.lambda$static$0(ExceptionUtil.java:47)
	at com.hazelcast.internal.util.ExceptionUtil.peel(ExceptionUtil.java:125)
	at com.hazelcast.internal.util.ExceptionUtil.peel(ExceptionUtil.java:68)
	at com.hazelcast.internal.util.ExceptionUtil.rethrow(ExceptionUtil.java:130)
	at com.hazelcast.client.config.XmlClientFailoverConfigBuilder.build(XmlClientFailoverConfigBuilder.java:152)
	at com.hazelcast.client.config.XmlClientFailoverConfigBuilder.build(XmlClientFailoverConfigBuilder.java:145)
	at com.hazelcast.client.config.ClientFailoverConfig.load(ClientFailoverConfig.java:80)
	at com.hazelcast.client.config.ClientFailoverConfigResolutionTest.testResolveSystemProperty_classpath_xml_loadedAsXml(ClientFailoverConfigResolutionTest.java:72)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.xml.sax.SAXParseException; schema_reference.4: Failed to read schema document 'null', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:134)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:396)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:306)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.reportSchemaErr(XSDHandler.java:4158)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.reportSchemaError(XSDHandler.java:4141)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.getSchemaDocument1(XSDHandler.java:2485)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.getSchemaDocument(XSDHandler.java:2193)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.parseSchema(XSDHandler.java:578)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadSchema(XMLSchemaLoader.java:610)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadGrammar(XMLSchemaLoader.java:569)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadGrammar(XMLSchemaLoader.java:535)
	at com.sun.org.apache.xerces.internal.jaxp.validation.XMLSchemaFactory.newSchema(XMLSchemaFactory.java:254)
	at com.hazelcast.config.AbstractXmlConfigHelper.schemaValidation(AbstractXmlConfigHelper.java:114)
	at com.hazelcast.client.config.XmlClientFailoverConfigBuilder.parseAndBuildConfig(XmlClientFailoverConfigBuilder.java:170)
	at com.hazelcast.client.config.XmlClientFailoverConfigBuilder.build(XmlClientFailoverConfigBuilder.java:150)
	... 15 more
```

</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: testResolveClasspath_xml in 0.338 seconds.
Started Running Test: testResolveSystemProperty_classpath_xml_loadedAsXml
16:26:44,205  INFO |testResolveSystemProperty_classpath_xml_loadedAsXml| - [AbstractConfigLocator] testResolveSystemProperty_classpath_xml_loadedAsXml - Loading configuration 'classpath:foo.xml' from System property 'hazelcast.client.failover.config'
16:26:44,205  INFO |testResolveSystemProperty_classpath_xml_loadedAsXml| - [AbstractConfigLocator] testResolveSystemProperty_classpath_xml_loadedAsXml - Using classpath resource at foo.xml
```

</details>

**Comment by slavagithub** [comment]
The same issue for 
- com.hazelcast.client.config.XmlClientFailoverConfigBuilderConfigResolutionTest
- - com.hazelcast.client.config.XmlClientFailoverConfigBuilderTest
- - com.hazelcast.client.config.XmlYamlClientConfigBuilderEqualsTest

**Comment by slavagithub** [comment]
The same for MacOS, Zulu, JDK8, master - http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-MacOS-ZuluJDK8/41/testReport/
