### ISSUE TITLE
A lot of test failures with "Failed to serialize" error

### ISSUE THREAD

**Issue by slavagithub** [hazelcast/hazelcast#20786]
_master_ (commit e3b1f61efe9f94214e70788126520e6393b19a71)

failed tests:
com.hazelcast.jet.sql.SqlClientCompactQueryTest
com.hazelcast.jet.sql.impl.connector.map.SqlCompactTest
com.hazelcast.internal.serialization.impl.compact.extractor.ExtractionInArraySpecTest
com.hazelcast.internal.serialization.impl.compact.extractor.ExtractionInCompactStreamSerializerSpecTest
com.hazelcast.internal.serialization.impl.compact.extractor.ExtractionWithExtractorsSpecTest
com.hazelcast.internal.serialization.impl.compact.extractor.QueryTest
com.hazelcast.internal.serialization.impl.compact.integration.ClientCompactTest
com.hazelcast.internal.serialization.impl.compact.integration.LiteMemberCompactTest

Failed on master, Corretto, JDK8: [test results](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-CorrettoJDK8/166/testReport/)

<details><summary>Stacktrace:</summary>

```
com.hazelcast.nio.serialization.HazelcastSerializationException: Failed to serialize 'com.hazelcast.internal.serialization.impl.compact.extractor.ComplexTestDataStructure$Person'
	at com.hazelcast.internal.serialization.impl.SerializationUtil.handleSerializeException(SerializationUtil.java:129)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:238)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:214)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toData(AbstractSerializationService.java:199)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toData(AbstractSerializationService.java:154)
	at com.hazelcast.spi.impl.NodeEngineImpl.toData(NodeEngineImpl.java:380)
	at com.hazelcast.spi.impl.AbstractDistributedObject.toData(AbstractDistributedObject.java:78)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.put(MapProxyImpl.java:137)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.put(MapProxyImpl.java:128)
	at com.hazelcast.internal.serialization.impl.compact.extractor.AbstractExtractionTest.putTestDataToMap(AbstractExtractionTest.java:146)
	at com.hazelcast.internal.serialization.impl.compact.extractor.AbstractExtractionTest.execute(AbstractExtractionTest.java:165)
	at com.hazelcast.internal.serialization.impl.compact.extractor.ExtractionInArraySpecTest.comparable_primitive_reduced_attribute_comparedToNull_matching2(ExtractionInArraySpecTest.java:280)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37)
	at com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:104)
	at com.hazelcast.test.metrics.MetricsRule$1.evaluate(MetricsRule.java:63)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:39)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:107)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:83)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
Caused by: java.lang.UnsupportedOperationException: The BETA compact format can only be used with 5.1 cluster
	at com.hazelcast.internal.serialization.impl.compact.schema.MemberSchemaService.putAsync(MemberSchemaService.java:136)
	at com.hazelcast.internal.serialization.impl.compact.schema.MemberSchemaService.put(MemberSchemaService.java:131)
	at com.hazelcast.internal.serialization.impl.compact.CompactStreamSerializer.putToSchemaService(CompactStreamSerializer.java:157)
	at com.hazelcast.internal.serialization.impl.compact.CompactStreamSerializer.writeObject(CompactStreamSerializer.java:168)
	at com.hazelcast.internal.serialization.impl.compact.CompactStreamSerializer.write(CompactStreamSerializer.java:132)
	at com.hazelcast.internal.serialization.impl.compact.CompactStreamSerializer.write(CompactStreamSerializer.java:125)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.write(StreamSerializerAdapter.java:39)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:235)
	... 62 more
```

</details>

<details><summary>Standard output:</summary>

```
17:03:51,962  INFO || - [MetricsConfigHelper] main - [LOCAL] [dev] [5.2-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
17:03:51,962  INFO || - [logo] main - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
17:03:51,962  INFO || - [system] main - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Copyright (c) 2008-2022, Hazelcast, Inc. All Rights Reserved.
17:03:51,963  INFO || - [system] main - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Hazelcast Platform 5.2-SNAPSHOT (20220220 - e3b1f61) starting at [127.0.0.1]:5701
17:03:51,963  INFO || - [system] main - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Cluster name: dev
17:03:51,963  INFO || - [system] main - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed.
To enable integrity checker do one of the following: 
  - Change member config using Java API: config.setIntegrityCheckerEnabled(true);;
  - Change XML/YAML configuration property: Set hazelcast.integrity-checker.enabled to true
  - Add system property: -Dhz.integritychecker.enabled=true
  - Add environment variable: HZ_INTEGRITYCHECKER_ENABLED=true (recommended when running container/docker image)
17:03:51,963  INFO || - [system] main - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] The Jet engine is disabled.
To enable the Jet engine on the members, please do one of the following:
  - Change member config using Java API: config.getJetConfig().setEnabled(true);;
  - Change XML/YAML configuration property: Set Set hazelcast.jet.enabled to true
  - Add system property: -Dhz.jet.enabled=true
  - Add environment variable: HZ_JET_ENABLED=true (recommended when running container/docker image)
17:03:51,967  INFO || - [MetricsConfigHelper] main - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
17:03:51,972  WARN || - [CPSubsystem] main - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
17:03:51,976  INFO || - [Diagnostics] main - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
17:03:51,976  INFO || - [LifecycleService] main - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] [127.0.0.1]:5701 is STARTING
17:03:51,977  INFO || - [ClusterService] main - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] 

Members {size:1, ver:1} [
	Member [127.0.0.1]:5701 - 25bb7a69-bede-4707-90d6-147c11005e90 this
]

17:03:51,977  INFO || - [LifecycleService] main - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] [127.0.0.1]:5701 is STARTED
17:03:51,977  INFO || - [PartitionStateManager] main - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Initializing cluster partition table arrangement...
17:03:51,980  INFO || - [LifecycleService] main - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
17:03:51,980  WARN || - [Node] main - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Terminating forcefully...
17:03:51,980  INFO || - [Node] main - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Shutting down connection manager...
17:03:51,980  INFO || - [Node] main - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Shutting down node engine...
17:03:51,981  INFO || - [NodeExtension] main - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Destroying node NodeExtension.
17:03:51,981  INFO || - [Node] main - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Hazelcast Shutdown is completed in 1 ms.
17:03:51,981  INFO || - [LifecycleService] main - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
BuildInfo right after comparable_primitive_reduced_attribute_comparedToNull_matching2[1: HASH](com.hazelcast.internal.serialization.impl.compact.extractor.ExtractionInArraySpecTest): BuildInfo{version='5.2-SNAPSHOT', build='20220220', buildNumber=20220220, revision=e3b1f61, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'comparable_primitive_reduced_attribute_comparedToNull_matching2[1: HASH](com.hazelcast.internal.serialization.impl.compact.extractor.ExtractionInArraySpecTest):'
17:03:50, accumulated pauses: 14 ms, max pause: 0 ms, pauses over 1000 ms: 0
```

</details>

**Comment by slavagithub** [comment]
the same for IBM, Jdk8 - http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-IbmJDK8/171/testReport/

**Comment by slavagithub** [comment]
the same for MacOS, Zulu JDK8 - http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-MacOS-ZuluJDK8/41/testReport/
