### ISSUE TITLE
ConcurrentModificationException for loading YAML configuration

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#20835]
Following ConcurrentModificationException was thrown during starting HZ node configured from YAML:
```
INFO: Loading configuration '/home/ec2-user/ansible/hazelcast-enterprise-5.1-SNAPSHOT/config/hazelcast-isolated.yaml' from System property 'hazelcast.config'
Feb 25, 2022 5:29:15 PM com.hazelcast.internal.config.AbstractConfigLocator
INFO: Using configuration file at /home/ec2-user/ansible/hazelcast-enterprise-5.1-SNAPSHOT/config/hazelcast-isolated.yaml
Exception in thread "main" java.util.ConcurrentModificationException
        at java.util.Hashtable$Enumerator.next(Hashtable.java:1387)
        at java.util.Hashtable.putAll(Hashtable.java:523)
        at com.hazelcast.spi.properties.HazelcastProperties.<init>(HazelcastProperties.java:75)
        at com.hazelcast.internal.config.YamlConfigSchemaValidator.validate(YamlConfigSchemaValidator.java:95)
        at com.hazelcast.config.YamlConfigBuilder.parseAndBuildConfig(YamlConfigBuilder.java:166)
        at com.hazelcast.config.YamlConfigBuilder.build(YamlConfigBuilder.java:137)
        at com.hazelcast.config.YamlConfigBuilder.build(YamlConfigBuilder.java:130)
        at com.hazelcast.config.Config.loadFromFile(Config.java:276)
        at com.hazelcast.config.Config.load(Config.java:240)
        at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:131)
        at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:95)
        at com.hazelcast.core.server.HazelcastMemberStarter.main(HazelcastMemberStarter.java:45)
```

Test used following yaml config:
```
hazelcast:
  cluster-name: jet-isolated
  license-key: *****
  properties:
    hazelcast.partition.count: 64
    hazelcast.phone.home.enabled: false
    hazelcast.logging.type: log4j2
    hazelcast.slow.operation.detector.stacktrace.logging.enabled: true
    hazelcast.shutdownhook.policy: GRACEFUL
    hazelcast.diagnostics.metric.distributed.datastructures: true
  network:
    port:
      auto-increment: true
      port-count: 100
      port: 5701
    join:
      multicast:
        enabled: false
      tcp-ip:
        enabled: true
        member-list:
          - 10.0.0.133:5701
          - 10.0.0.128:5701
          - 10.0.0.124:5701
          - 10.0.0.178:5701
    ssl:
      enabled: false
      factory-class-name: com.hazelcast.nio.ssl.BasicSSLContextFactory
      properties:
        keyStore: /home/ec2-user/ansible/hazelcast-enterprise-5.1-SNAPSHOT/hazelcast-jet.ks
        keyStorePassword: soak-test
        trustStore: /home/ec2-user/ansible/hazelcast-enterprise-5.1-SNAPSHOT/hazelcast-jet.ts
        trustStorePassword: soak-test
    rest-api:
      enabled: true
      endpoint-groups:
        HEALTH_CHECK:
          enabled: true
        DATA:
          enabled: true
        CLUSTER_READ:
          enabled: true
        CLUSTER_WRITE:
          enabled: true
  security:
    enabled: False
    realms:
      - name: simpleRealm
        authentication:
          simple:
            users:
              - username: hzUser
                password: hzPassword
                roles:
                  - hzRole
    client-authentication:
      realm: simpleRealm
    client-permissions:
      job:
        - principal: "hzRole"
          actions:
            - all
      connector:
        # snapshot-file-test
        - name: file:/tmp/file_sink_directory
          principal: "hzRole"
          actions:
            - write
        # snapshot-jms-sink-test
        - name: jms:JmsSinkTest_sinkDynamic-JmsSinkTest
          principal: "hzRole"
          actions:
            - write
        # snapshot-jms-source-test
        - name: jms:JmsSourceTest_sourceDynamic-JmsSourceTest
          principal: "hzRole"
          actions:
            - read
        # jms-test
        - name: jms:sourceDynamic-JmsTest
          principal: "hzRole"
          actions:
            - read
        - name: jms:middleDynamic-JmsTest
          principal: "hzRole"
          actions:
            - read
            - write
        - name: jms:sinkDynamic-JmsTest
          principal: "hzRole"
          actions:
            - write
        # temp - snapshot-jdbc-test - https://github.com/hazelcast/hazelcast-enterprise/issues/4233
        - name: "jdbc:"
          principal: "hzRole"
          actions:
            - write
      map:
        # cdc-source-test
        - name: CdcSourceTest_latestCounters
          principal: "hzRole"
          actions:
            - create
            - put
            - read
        # kinesis-test
        - name: KinesisTest_latestCounters
          principal: "hzRole"
          actions:
            - create
            - put
            - read
        # snapshot-jms-source-test
        - name: JmsSourceTest_latestCounter
          principal: "hzRole"
          actions:
            - create
            - put
            - read
  hot-restart-persistence:
    enabled: true
    base-dir: /home/ec2-user/ansible/hazelcast-enterprise-5.1-SNAPSHOT/hot-restart
    parallelism: 2

  jet:
    enabled: true
    resource-upload-enabled: true
    instance:
      lossless-restart-enabled: true
```

**Comment by vbekiaris** [comment]
`HazelcastProperties` constructor uses `Properties#putAll` (inherited from `Hashtable`) to copy existing Properties object to `HazelcastProperties` -> does not take into account `Properties` specifics (and may result in a "compromised" properties object). Instead, this version of the `HazelcastProperties(Properties)` constructor avoids throwing a `ConcurrentModificationException`:

```
public HazelcastProperties(Properties nullableProperties) {
        if (nullableProperties != null) {
            for (String propertyName : nullableProperties.stringPropertyNames()) {
                String value = nullableProperties.getProperty(propertyName);
                if (value != null) {
                    properties.setProperty(propertyName, value);
                }
            }
        }

        this.keys = unmodifiableSet((Set) properties.keySet());
    }
```

The part of `Properties#stringPropertyNames` that gathers property names is `synchronized`, as is `Properties#setProperty` so it is guaranteed that there won't be any concurrent modification while gathering property names.  It is possible that after property names are gathered, a modification removes a property, that's why we still need to check for existence of `value` in the copy loop.
That said, there is further properties processing (eg in `com.hazelcast.internal.config.override.ConfigOverrideValidator.findDuplicateEntries`) that may still fail in the face of concurrent modification of system properties.
