### ISSUE TITLE
com.hazelcast.jet.sql_nightly.SqlSplitBrainTest

### ISSUE THREAD

**Issue by bpoplawski** [hazelcast/hazelcast#20859]
_5.0.z_ (commit 3b5559b908b2c782213a7ee469af62674c1a8e26 )

Failed on IbmJDK8: http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-IbmJDK8-nightly/23/testReport/junit/com.hazelcast.jet.sql/SqlSplitBrainTest/com_hazelcast_jet_sql_SqlSplitBrainTest/

<details><summary>Stacktrace:</summary>

```
org.junit.runners.model.TestTimedOutException: test timed out after 900 seconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
	at java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1718)
	at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3345)
	at java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1753)
	at java.util.concurrent.CompletableFuture.join(CompletableFuture.java:1958)
	at com.hazelcast.jet.Job.join(Job.java:78)
	at com.hazelcast.jet.core.JetTestSupport.ditchJob(JetTestSupport.java:415)
	at com.hazelcast.jet.core.JetTestSupport.shutdownJobsAndGetLeakedClassLoaders(JetTestSupport.java:127)
	at com.hazelcast.jet.core.JetTestSupport.shutdownFactory(JetTestSupport.java:99)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:381)
	at com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37)
	at com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:104)
	at com.hazelcast.test.metrics.MetricsRule$1.evaluate(MetricsRule.java:62)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:50)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:29)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:39)
	at com.hazelcast.test.OverridePropertyRule$1.evaluate(OverridePropertyRule.java:66)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.lang.Thread.run(Thread.java:825)
```

</details>

<details><summary>Standard output:</summary>

```
Started Running Test: test_indexScan
22:31:24,641  INFO |test_indexScan| - [MetricsConfigHelper] test_indexScan - [LOCAL] [dev] [5.0.3-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
22:31:24,677  INFO |test_indexScan| - [logo] test_indexScan - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
22:31:24,678  INFO |test_indexScan| - [system] test_indexScan - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] Copyright (c) 2008-2021, Hazelcast, Inc. All Rights Reserved.
22:31:24,678  INFO |test_indexScan| - [system] test_indexScan - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] Hazelcast Platform 5.0.3-SNAPSHOT (20220226 - 3b5559b) starting at [127.0.0.1]:5701
22:31:24,678  INFO |test_indexScan| - [system] test_indexScan - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] Cluster name: dev
22:31:24,702  INFO |test_indexScan| - [MetricsConfigHelper] test_indexScan - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
22:31:24,993  WARN |test_indexScan| - [CPSubsystem] test_indexScan - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
22:31:25,206  INFO |test_indexScan| - [JetServiceBackend] test_indexScan - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] Setting number of cooperative threads and default parallelism to 4
22:31:25,244  INFO |test_indexScan| - [Diagnostics] test_indexScan - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
22:31:25,249  INFO |test_indexScan| - [LifecycleService] test_indexScan - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] [127.0.0.1]:5701 is STARTING
22:31:25,257  INFO |test_indexScan| - [JetExtension] test_indexScan - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] Jet is enabled
22:31:25,257  INFO |test_indexScan| - [ClusterService] test_indexScan - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] 

Members {size:1, ver:1} [
	Member [127.0.0.1]:5701 - 2a0512df-c200-496b-9832-55c8c68982f0 this
]
```

</details>

Note thread dump avilable for job with above link

**Comment by ufukyilmaz** [comment]
Resolved by https://github.com/hazelcast/hazelcast/pull/20902.
