### ISSUE TITLE
Race when recreating index after a split-brain merge [HZ-956]

### ISSUE THREAD

**Issue by viliam-durina** [hazelcast/hazelcast#20876]
After a split-brain merge, there seems to be a concurrent process removing partitions from indexes (because the member is reset) and also a process of migration (because new members handle new partitions). It can happen, that a partition is deleted after it's migrated to a member, which causes that some partition isn't indexed at all.

This causes a stuck job in SQL because the index reader tries to read a partition, finds out it's not indexed, so it gets the new owner from `PartitionService` and tries again, forever. This doesn't cause functional issue in the Predicate API because it [falls back to not using the index if it doesn't contain all the expected partitions](https://github.com/hazelcast/hazelcast/blob/1d8665ad40d82b404f665f9cbe5f92848689e802/hazelcast/src/main/java/com/hazelcast/query/impl/Indexes.java#L482), however it causes performance regression because the index isn't used.

The issue can be reproduced by running `SqlSplitBrainTest.test_indexScan()`. To increase the likelihood of failure, increase the thread count on the first line of the test. In my env, I use 16 threads (i have 16 cpus), and it fails in ~20% of runs.

Here are stack traces logged in the `IndexImpl.markPartitionAsUnindexed()` and `IndexImpl.markPartitionAsIndexed()`, after the cluster heals:
```
16:29:32,522  INFO |test_indexScan| - [JetSplitBrainTestSupport] test_indexScan - Going to heal split-brain...
16:29:32,605  INFO |test_indexScan| - [IndexImpl] hz.nervous_greider.partition-operation.thread-0 - aaa partition added, partitionId=4, index=IndexImpl{identityHash=113662842, partitionTracker=GlobalIndexPartitionTracker{partitionCount=11, state=State{stamp=16, indexedPartitions={size=8, partitions=[0, 1, 2, 3, 4, 5, 7, 9]}, pending=0}}} AbstractIndex{config=IndexConfig{name=m_sorted_this, type=SORTED, attributes=[this]}}
java.lang.Exception: null
	at com.hazelcast.query.impl.IndexImpl.markPartitionAsIndexed(IndexImpl.java:87) [classes/:?]
	at com.hazelcast.query.impl.Indexes.markPartitionAsIndexed(Indexes.java:121) [classes/:?]
	at com.hazelcast.map.impl.MapMigrationAwareService.populateIndexes(MapMigrationAwareService.java:326) [classes/:?]
	at com.hazelcast.map.impl.MapMigrationAwareService.commitMigration(MapMigrationAwareService.java:173) [classes/:?]
	at com.hazelcast.spi.impl.CountingMigrationAwareService.commitMigration(CountingMigrationAwareService.java:86) [classes/:?]
	at com.hazelcast.map.impl.MapService.commitMigration(MapService.java:179) [classes/:?]
	at com.hazelcast.internal.partition.operation.FinalizePromotionOperation.commitServices(FinalizePromotionOperation.java:142) [classes/:?]
	at com.hazelcast.internal.partition.operation.FinalizePromotionOperation.run(FinalizePromotionOperation.java:78) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:189) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:273) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:248) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:213) [classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:175) [classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:139) [classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123) [classes/:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) [classes/:?]
16:29:33,851  INFO |test_indexScan| - [IndexImpl] hz.nervous_greider.partition-operation.thread-0 - aaa partition removed, partitionId=4, index=IndexImpl{identityHash=113662842, partitionTracker=GlobalIndexPartitionTracker{partitionCount=11, state=State{stamp=35, indexedPartitions={size=5, partitions=[6, 7, 8, 9, 10]}, pending=1}}} AbstractIndex{config=IndexConfig{name=m_sorted_this, type=SORTED, attributes=[this]}}
java.lang.Exception: null
	at com.hazelcast.query.impl.IndexImpl.markPartitionAsUnindexed(IndexImpl.java:93) [classes/:?]
	at com.hazelcast.query.impl.Indexes.markPartitionAsUnindexed(Indexes.java:133) [classes/:?]
	at com.hazelcast.map.impl.recordstore.IndexingMutationObserver.fullScanLocalDataToClear(IndexingMutationObserver.java:156) [classes/:?]
	at com.hazelcast.map.impl.recordstore.IndexingMutationObserver.clearGlobalIndexes(IndexingMutationObserver.java:118) [classes/:?]
	at com.hazelcast.map.impl.recordstore.IndexingMutationObserver.onDestroy(IndexingMutationObserver.java:102) [classes/:?]
	at com.hazelcast.map.impl.MapSplitBrainHandlerService.onStoreCollection(MapSplitBrainHandlerService.java:62) [classes/:?]
	at com.hazelcast.map.impl.MapSplitBrainHandlerService.onStoreCollection(MapSplitBrainHandlerService.java:29) [classes/:?]
	at com.hazelcast.spi.impl.merge.AbstractSplitBrainHandlerService$StoreCollector.run(AbstractSplitBrainHandlerService.java:108) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:192) [classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:207) [classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:141) [classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123) [classes/:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) [classes/:?]
16:29:34,405  INFO |test_indexScan| - [IndexImpl] hz.nervous_greider.partition-operation.thread-0 - aaa partition removed, partitionId=4, index=IndexImpl{identityHash=113662842, partitionTracker=GlobalIndexPartitionTracker{partitionCount=11, state=State{stamp=68, indexedPartitions={size=0, partitions=[]}, pending=0}}} AbstractIndex{config=IndexConfig{name=m_sorted_this, type=SORTED, attributes=[this]}}
java.lang.Exception: null
	at com.hazelcast.query.impl.IndexImpl.markPartitionAsUnindexed(IndexImpl.java:93) [classes/:?]
	at com.hazelcast.query.impl.Indexes.markPartitionAsUnindexed(Indexes.java:133) [classes/:?]
	at com.hazelcast.map.impl.recordstore.IndexingMutationObserver.fullScanLocalDataToClear(IndexingMutationObserver.java:156) [classes/:?]
	at com.hazelcast.map.impl.recordstore.IndexingMutationObserver.clearGlobalIndexes(IndexingMutationObserver.java:118) [classes/:?]
	at com.hazelcast.map.impl.recordstore.IndexingMutationObserver.onReset(IndexingMutationObserver.java:90) [classes/:?]
	at com.hazelcast.map.impl.recordstore.CompositeMutationObserver.onReset(CompositeMutationObserver.java:197) [classes/:?]
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.reset(DefaultRecordStore.java:1399) [classes/:?]
	at com.hazelcast.map.impl.operation.MapChunk.initializeRecordStore(MapChunk.java:166) [classes/:?]
	at com.hazelcast.map.impl.operation.MapChunk.run(MapChunk.java:125) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:189) [classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.OperationRunner.runDirect(OperationRunner.java:169) [classes/:?]
	at com.hazelcast.internal.partition.operation.MigrationOperation.runMigrationOperation(MigrationOperation.java:139) [classes/:?]
	at com.hazelcast.internal.partition.operation.MigrationOperation.doRun(MigrationOperation.java:115) [classes/:?]
	at com.hazelcast.internal.partition.operation.MigrationOperation.run(MigrationOperation.java:95) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:189) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:273) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:248) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:471) [classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:197) [classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:137) [classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123) [classes/:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) [classes/:?]
16:29:34,454  INFO |test_indexScan| - [IndexImpl] hz.nervous_greider.partition-operation.thread-0 - aaa partition added, partitionId=4, index=IndexImpl{identityHash=113662842, partitionTracker=GlobalIndexPartitionTracker{partitionCount=11, state=State{stamp=81, indexedPartitions={size=2, partitions=[2, 4]}, pending=1}}} AbstractIndex{config=IndexConfig{name=m_sorted_this, type=SORTED, attributes=[this]}}
java.lang.Exception: null
	at com.hazelcast.query.impl.IndexImpl.markPartitionAsIndexed(IndexImpl.java:87) [classes/:?]
	at com.hazelcast.query.impl.Indexes.markPartitionAsIndexed(Indexes.java:121) [classes/:?]
	at com.hazelcast.map.impl.MapMigrationAwareService.populateIndexes(MapMigrationAwareService.java:326) [classes/:?]
	at com.hazelcast.map.impl.MapMigrationAwareService.commitMigration(MapMigrationAwareService.java:173) [classes/:?]
	at com.hazelcast.spi.impl.CountingMigrationAwareService.commitMigration(CountingMigrationAwareService.java:86) [classes/:?]
	at com.hazelcast.map.impl.MapService.commitMigration(MapService.java:179) [classes/:?]
	at com.hazelcast.internal.partition.operation.FinalizeMigrationOperation.finishMigration(FinalizeMigrationOperation.java:225) [classes/:?]
	at com.hazelcast.internal.partition.operation.FinalizeMigrationOperation.notifyServices(FinalizeMigrationOperation.java:127) [classes/:?]
	at com.hazelcast.internal.partition.operation.FinalizeMigrationOperation.run(FinalizeMigrationOperation.java:92) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:189) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:273) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:248) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:213) [classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:175) [classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:139) [classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123) [classes/:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) [classes/:?]
16:29:34,544  INFO |test_indexScan| - [JetSplitBrainTestSupport] test_indexScan - Split-brain healed
16:29:34,602  INFO |test_indexScan| - [IndexImpl] hz.nervous_greider.partition-operation.thread-0 - aaa partition removed, partitionId=4, index=IndexImpl{identityHash=113662842, partitionTracker=GlobalIndexPartitionTracker{partitionCount=11, state=State{stamp=102, indexedPartitions={size=3, partitions=[0, 1, 3]}, pending=0}}} AbstractIndex{config=IndexConfig{name=m_sorted_this, type=SORTED, attributes=[this]}}
java.lang.Exception: null
	at com.hazelcast.query.impl.IndexImpl.markPartitionAsUnindexed(IndexImpl.java:93) [classes/:?]
	at com.hazelcast.query.impl.Indexes.markPartitionAsUnindexed(Indexes.java:133) [classes/:?]
	at com.hazelcast.map.impl.recordstore.IndexingMutationObserver.fullScanLocalDataToClear(IndexingMutationObserver.java:156) [classes/:?]
	at com.hazelcast.map.impl.recordstore.IndexingMutationObserver.clearGlobalIndexes(IndexingMutationObserver.java:118) [classes/:?]
	at com.hazelcast.map.impl.recordstore.IndexingMutationObserver.onReset(IndexingMutationObserver.java:90) [classes/:?]
	at com.hazelcast.map.impl.recordstore.IndexingMutationObserver.onClear(IndexingMutationObserver.java:96) [classes/:?]
	at com.hazelcast.map.impl.recordstore.CompositeMutationObserver.onClear(CompositeMutationObserver.java:50) [classes/:?]
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.clearStorage(DefaultRecordStore.java:1462) [classes/:?]
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.destroyStorageAfterClear(DefaultRecordStore.java:1456) [classes/:?]
	at com.hazelcast.map.impl.MapSplitBrainHandlerService.destroyStore(MapSplitBrainHandlerService.java:69) [classes/:?]
	at com.hazelcast.map.impl.MapSplitBrainHandlerService.destroyStore(MapSplitBrainHandlerService.java:29) [classes/:?]
	at com.hazelcast.spi.impl.merge.AbstractSplitBrainHandlerService$1.run(AbstractSplitBrainHandlerService.java:123) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:192) [classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:207) [classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:141) [classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123) [classes/:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) [classes/:?]
16:29:34,603  INFO |test_indexScan| - [IndexImpl] hz.nervous_greider.partition-operation.thread-0 - aaa partition removed, partitionId=4, index=IndexImpl{identityHash=113662842, partitionTracker=GlobalIndexPartitionTracker{partitionCount=11, state=State{stamp=104, indexedPartitions={size=3, partitions=[0, 1, 3]}, pending=0}}} AbstractIndex{config=IndexConfig{name=m_sorted_this, type=SORTED, attributes=[this]}}
java.lang.Exception: null
	at com.hazelcast.query.impl.IndexImpl.markPartitionAsUnindexed(IndexImpl.java:93) [classes/:?]
	at com.hazelcast.query.impl.Indexes.markPartitionAsUnindexed(Indexes.java:133) [classes/:?]
	at com.hazelcast.map.impl.recordstore.IndexingMutationObserver.fullScanLocalDataToClear(IndexingMutationObserver.java:156) [classes/:?]
	at com.hazelcast.map.impl.recordstore.IndexingMutationObserver.clearGlobalIndexes(IndexingMutationObserver.java:118) [classes/:?]
	at com.hazelcast.map.impl.recordstore.IndexingMutationObserver.onDestroy(IndexingMutationObserver.java:102) [classes/:?]
	at com.hazelcast.map.impl.recordstore.CompositeMutationObserver.onDestroy(CompositeMutationObserver.java:179) [classes/:?]
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.destroyStorageImmediate(DefaultRecordStore.java:1440) [classes/:?]
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.destroyStorageAfterClear(DefaultRecordStore.java:1457) [classes/:?]
	at com.hazelcast.map.impl.MapSplitBrainHandlerService.destroyStore(MapSplitBrainHandlerService.java:69) [classes/:?]
	at com.hazelcast.map.impl.MapSplitBrainHandlerService.destroyStore(MapSplitBrainHandlerService.java:29) [classes/:?]
	at com.hazelcast.spi.impl.merge.AbstractSplitBrainHandlerService$1.run(AbstractSplitBrainHandlerService.java:123) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:192) [classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:207) [classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:141) [classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123) [classes/:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) [classes/:?]
```

This issue is the root cause in #20859, very likely also in #20853 and perhaps also in #20781.

**Comment by ahmetmircik** [comment]
Failure reason is assumptions of `AbstractSplitBrainHandlerService#asyncDestroyStores` method. It assumes all previous state is isolated and can be destroyed safely in an async manner but in reality it is not like that. For instance, index-state is still shared and after split-heal it is still in use. I will think a proper fix for this.
