### ISSUE TITLE
com.hazelcast.internal.util.phonehome.PhoneHomeCPSubsystemTest.testCountdownLatchesCount [HZ-1039]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#20903]
_5.1.z_ (commit 56d28803b4c636318555373c3f5236e88b0c0690)

Failed on ZingJDK8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-ZingJDK8/48/testReport/com.hazelcast.internal.util.phonehome/PhoneHomeCPSubsystemTest/testCountdownLatchesCount/

<details><summary>Stacktrace:</summary>

```
org.junit.ComparisonFailure: expected:<"[3]"> but was:<"[2]">
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at com.hazelcast.internal.util.phonehome.PhoneHomeCPSubsystemTest.testCountdownLatchesCount(PhoneHomeCPSubsystemTest.java:125)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

</details>

**Comment by olukas** [comment]
Failed again on ZingJDK8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-ZingJDK8/50/testReport/com.hazelcast.internal.util.phonehome/PhoneHomeCPSubsystemTest/testCountdownLatchesCount/
