### ISSUE TITLE
RaftSessionService on remote causes java.util.ConcurrentModificationException: null [HZ-1097]

### ISSUE THREAD

**Issue by cstamas** [hazelcast/hazelcast#20917]
**Describe the bug**

Am using HZ 5.0.2 provided sessionless ISemaphore instances from CP subsystem, and during load testing we are getting errors like these from HZ:

```
jvm 1    | 2022-03-08 21:09:16,204+0000 ERROR [hz.hostxxx.partition-operation.thread-29] *SYSTEM com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl - [x.x.x.x]:5701 [main_green] [5.0.2] Failed to process: PartitionSpecificRunnableAdaptor{task=com.hazelcast.cp.internal.session.RaftSessionService$$Lambda$2540/0x0000000801745c40@6df21cc, partitionId=29} on:hz.hostxxx.partition-operation.thread-29
jvm 1    | java.util.ConcurrentModificationException: null
jvm 1    |      at java.base/java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719)
jvm 1    |      at java.base/java.util.LinkedHashMap$LinkedValueIterator.next(LinkedHashMap.java:746)
jvm 1    |      at com.hazelcast.cp.internal.datastructures.spi.blocking.BlockingResource.collectAttachedSessions(BlockingResource.java:151)
jvm 1    |      at com.hazelcast.cp.internal.datastructures.spi.blocking.ResourceRegistry.getAttachedSessions(ResourceRegistry.java:203)
jvm 1    |      at com.hazelcast.cp.internal.datastructures.spi.blocking.AbstractBlockingService.getAttachedSessions(AbstractBlockingService.java:217)
jvm 1    |      at com.hazelcast.cp.internal.session.RaftSessionService.lambda$getInactiveSessions$2(RaftSessionService.java:380)
jvm 1    |      at com.hazelcast.cp.internal.util.PartitionSpecificRunnableAdaptor.run(PartitionSpecificRunnableAdaptor.java:41)
jvm 1    |      at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:192)
jvm 1    |      at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:207)
jvm 1    |      at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:141)
jvm 1    |      at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123)
jvm 1    |      at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)

```

Semaphore config:

```java
    config.getCPSubsystemConfig().addSemaphoreConfig(
        new SemaphoreConfig(
            SEMAPHORE_PREFIX + "*",
            true,
            Integer.MAX_VALUE
        )
    );
```

Semaphores uses non-default group, and this error happens on load test start, so maybe the group init is not thread safe?

Hazelcast version: 5.0.2
Java version: "11.0.11" 2021-04-20 LTS Zulu
OS: Linux CentOS 7.9 kernel 3.10.0-1160.25.1.el7.x86_64
Cluster size: 4 (4 members, no clients used)

**Comment by Holmistr** [comment]
Hi @cstamas , thanks for reporting this!

@arodionov Would you mind taking a quick look? Especially on:
> maybe the group init is not thread safe?

Based on that, we might invest some more time.

**Comment by arodionov** [comment]
This issue is related to concurrent access to `LinkedHashMap`
 
https://github.com/hazelcast/hazelcast/blob/14ef0dbefa4a6fa00a50a8873aeea02ec6c3f5e4/hazelcast/src/main/java/com/hazelcast/cp/internal/datastructures/spi/blocking/BlockingResource.java#L47

The periodically scheduled `CheckInactiveSessions` task intersects with `waitKeys` modification:
https://github.com/hazelcast/hazelcast/blob/14ef0dbefa4a6fa00a50a8873aeea02ec6c3f5e4/hazelcast/src/main/java/com/hazelcast/cp/internal/session/RaftSessionService.java#L120
