### ISSUE TITLE
com.hazelcast.internal.util.phonehome.PhoneHomeCPSubsystemTest [HZ-1038]

### ISSUE THREAD

**Issue by bpoplawski** [hazelcast/hazelcast#21014]
_5.1.z_ (commit 454a06d3aff6a9731edf6d686c791cc29b8d2f2f )

Failed on ZING, JDK8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-ZingJDK8/53/testReport/junit/com.hazelcast.internal.util.phonehome/PhoneHomeCPSubsystemTest/testAtomicLongsCount/

<details><summary>Stacktrace:</summary>

```
org.junit.ComparisonFailure: expected:<"[3]"> but was:<"[2]">
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at com.hazelcast.internal.util.phonehome.PhoneHomeCPSubsystemTest.testAtomicLongsCount(PhoneHomeCPSubsystemTest.java:139)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: testFencedLocksCount in 11.207 seconds.
19:52:58,962  INFO |testAtomicLongsCount| - [NodeExtension] Thread-42493 - [127.0.0.1]:5701 [dev] [5.1.2-SNAPSHOT] Destroying node NodeExtension.
19:52:58,962  INFO |testAtomicLongsCount| - [Node] Thread-42493 - [127.0.0.1]:5701 [dev] [5.1.2-SNAPSHOT] Hazelcast Shutdown is completed in 97 ms.
19:52:58,962  INFO |testAtomicLongsCount| - [LifecycleService] Thread-42493 - [127.0.0.1]:5701 [dev] [5.1.2-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
BuildInfo right after testAtomicLongsCount(com.hazelcast.internal.util.phonehome.PhoneHomeCPSubsystemTest): BuildInfo{version='5.1.2-SNAPSHOT', build='20220320', buildNumber=20220320, revision=454a06d, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'testAtomicLongsCount(com.hazelcast.internal.util.phonehome.PhoneHomeCPSubsystemTest):'
19:52:45, accumulated pauses: 4920 ms, max pause: 20 ms, pauses over 1000 ms: 0
19:52:50, accumulated pauses: 4917 ms, max pause: 25 ms, pauses over 1000 ms: 0
19:52:55, accumulated pauses: 3897 ms, max pause: 18 ms, pauses over 1000 ms: 0
```

</details>

**Comment by bpoplawski** [comment]
Another similar one found for Master, IBM JDK8

com.hazelcast.internal.util.phonehome.PhoneHomeCPSubsystemTest.testSemaphoresCount

https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-IbmJDK8/175/testReport/com.hazelcast.internal.util.phonehome/PhoneHomeCPSubsystemTest/testSemaphoresCount/

**Comment by bpoplawski** [comment]
Another similar found for Master, Zing JDK8

com.hazelcast.internal.util.phonehome.PhoneHomeCPSubsystemTest.testGroupsCount_createdGroups

http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZingJDK8/406/testReport/com.hazelcast.internal.util.phonehome/PhoneHomeCPSubsystemTest/testGroupsCount_createdGroups/
