### ISSUE TITLE
com.hazelcast.instance.impl.DefaultAddressPickerTest.testBindAddress_withDefaultPortAndLoopbackAddress [HZ-1042]

### ISSUE THREAD

**Issue by bpoplawski** [hazelcast/hazelcast#21022]
_master_ (commit 21da2b291ba336b4d2bd1a9e58e6388f37e50a29 )

Failed on Corretto, JDK11 http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-CorrettoJDK11/163/testReport/junit/com.hazelcast.instance.impl/DefaultAddressPickerTest/testBindAddress_withDefaultPortAndLoopbackAddress/

<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: expected:<[127.0.0.1]:5701> but was:<[127.0.0.1]:5702>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:120)
	at org.junit.Assert.assertEquals(Assert.java:146)
	at com.hazelcast.instance.impl.DefaultAddressPickerTest.testBindAddress(DefaultAddressPickerTest.java:176)
	at com.hazelcast.instance.impl.DefaultAddressPickerTest.testBindAddress_withDefaultPortAndLoopbackAddress(DefaultAddressPickerTest.java:104)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: testPublicAddress_withDefaultPortAndLocalhost in 0.001 seconds.
Started Running Test: testBindAddress_withDefaultPortAndLoopbackAddress
05:40:24,372 TRACE |testBindAddress_withDefaultPortAndLoopbackAddress| - [AddressPicker] testBindAddress_withDefaultPortAndLoopbackAddress - inet reuseAddress:true
05:40:24,372 DEBUG |testBindAddress_withDefaultPortAndLoopbackAddress| - [AddressPicker] testBindAddress_withDefaultPortAndLoopbackAddress - Trying to bind inet socket address: 0.0.0.0/0.0.0.0:5701
05:40:24,372 TRACE |testBindAddress_withDefaultPortAndLoopbackAddress| - [AddressPicker] testBindAddress_withDefaultPortAndLoopbackAddress - Cannot bind socket address 0.0.0.0/0.0.0.0:5701
java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method) ~[?:?]
	at sun.nio.ch.Net.bind(Net.java:455) ~[?:?]
	at sun.nio.ch.Net.bind(Net.java:447) ~[?:?]
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:227) ~[?:?]
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:80) ~[?:?]
	at com.hazelcast.instance.impl.ServerSocketHelper.openServerSocketChannel(ServerSocketHelper.java:136) ~[classes/:?]
	at com.hazelcast.instance.impl.ServerSocketHelper.tryOpenServerSocketChannel(ServerSocketHelper.java:101) [classes/:?]
	at com.hazelcast.instance.impl.ServerSocketHelper.createServerSocketChannel(ServerSocketHelper.java:76) [classes/:?]
	at com.hazelcast.instance.impl.DefaultAddressPicker.getPublicAddressByPortSearch(DefaultAddressPicker.java:147) [classes/:?]
	at com.hazelcast.instance.impl.DefaultAddressPicker.pickAddress(DefaultAddressPicker.java:121) [classes/:?]
	at com.hazelcast.instance.impl.DefaultAddressPickerTest.testBindAddress(DefaultAddressPickerTest.java:173) [test-classes/:?]
	at com.hazelcast.instance.impl.DefaultAddressPickerTest.testBindAddress_withDefaultPortAndLoopbackAddress(DefaultAddressPickerTest.java:104) [test-classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59) [junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56) [junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) [junit-4.13.2.jar:4.13.2]
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115) [test-classes/:?]
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107) [test-classes/:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
05:40:24,372 DEBUG |testBindAddress_withDefaultPortAndLoopbackAddress| - [AddressPicker] testBindAddress_withDefaultPortAndLoopbackAddress - Trying to bind inet socket address: 0.0.0.0/0.0.0.0:5702
05:40:24,372 DEBUG |testBindAddress_withDefaultPortAndLoopbackAddress| - [AddressPicker] testBindAddress_withDefaultPortAndLoopbackAddress - Bind successful to inet socket address: /0.0.0.0:5702
05:40:24,372 DEBUG |testBindAddress_withDefaultPortAndLoopbackAddress| - [AddressPicker] testBindAddress_withDefaultPortAndLoopbackAddress - Picked [127.0.0.1]:5702, using socket ServerSocket[addr=/0.0.0.0,localport=5702], bind any local is true
05:40:24,372 TRACE |testBindAddress_withDefaultPortAndLoopbackAddress| - [AddressPicker] testBindAddress_withDefaultPortAndLoopbackAddress - Using public address the same as the bind address: [127.0.0.1]:5702
Standard Error
```

</details>

**Comment by frant-hartm** [comment]
@ufukyilmaz You were looking at this failure recently, right?

**Comment by ufukyilmaz** [comment]
Yes, I had added more logging to this test previously. But, when I look at the
current logs, I couldn't understand the cause completely. The server socket,
which was bound to `0.0.0.0:5701` in the previous serial test, seems that not to
closed completely when we're running the failing test. It didn't throw any
exception in the cleanup step (I added log for this cleanup exceptions but there
is no exception) but if we try to bind to the same address in this failing test,
socket can't bind. I expect such a problem in concurrent server socket
creations, but these are serial tests. I don't understand the cause. 

See the logs: 
```
Started Running Test: testPublicAddress_withDefaultPortAndLocalhost
05:40:24,371 DEBUG |testPublicAddress_withDefaultPortAndLocalhost| - [AddressPicker] testPublicAddress_withDefaultPortAndLocalhost - Prefer IPv4 stack is true, prefer IPv6 addresses is false
05:40:24,371 TRACE |testPublicAddress_withDefaultPortAndLocalhost| - [AddressPicker] testPublicAddress_withDefaultPortAndLocalhost - inet reuseAddress:true
05:40:24,371 DEBUG |testPublicAddress_withDefaultPortAndLocalhost| - [AddressPicker] testPublicAddress_withDefaultPortAndLocalhost - Trying to bind inet socket address: 0.0.0.0/0.0.0.0:5701
05:40:24,371 DEBUG |testPublicAddress_withDefaultPortAndLocalhost| - [AddressPicker] testPublicAddress_withDefaultPortAndLocalhost - Bind successful to inet socket address: /0.0.0.0:5701
05:40:24,371 DEBUG |testPublicAddress_withDefaultPortAndLocalhost| - [AddressPicker] testPublicAddress_withDefaultPortAndLocalhost - Picked [172.17.0.2]:5701, using socket ServerSocket[addr=/0.0.0.0,localport=5701], bind any local is true
05:40:24,371  INFO |testPublicAddress_withDefaultPortAndLocalhost| - [AddressPicker] testPublicAddress_withDefaultPortAndLocalhost - Using public address: [localhost]:5701
Finished Running Test: testPublicAddress_withDefaultPortAndLocalhost in 0.001 seconds.
Started Running Test: testBindAddress_withDefaultPortAndLoopbackAddress
05:40:24,372 TRACE |testBindAddress_withDefaultPortAndLoopbackAddress| - [AddressPicker] testBindAddress_withDefaultPortAndLoopbackAddress - inet reuseAddress:true
05:40:24,372 DEBUG |testBindAddress_withDefaultPortAndLoopbackAddress| - [AddressPicker] testBindAddress_withDefaultPortAndLoopbackAddress - Trying to bind inet socket address: 0.0.0.0/0.0.0.0:5701
05:40:24,372 TRACE |testBindAddress_withDefaultPortAndLoopbackAddress| - [AddressPicker] testBindAddress_withDefaultPortAndLoopbackAddress - Cannot bind socket address 0.0.0.0/0.0.0.0:5701
java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method) ~[?:?]
	at sun.nio.ch.Net.bind(Net.java:455) ~[?:?]
	at sun.nio.ch.Net.bind(Net.java:447) ~[?:?]
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:227) ~[?:?]
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:80) ~[?:?]
	at com.hazelcast.instance.impl.ServerSocketHelper.openServerSocketChannel(ServerSocketHelper.java:136) ~[classes/:?]
	at com.hazelcast.instance.impl.ServerSocketHelper.tryOpenServerSocketChannel(ServerSocketHelper.java:101) [classes/:?]
	at com.hazelcast.instance.impl.ServerSocketHelper.createServerSocketChannel(ServerSocketHelper.java:76) [classes/:?]
	at com.hazelcast.instance.impl.DefaultAddressPicker.getPublicAddressByPortSearch(DefaultAddressPicker.java:147) [classes/:?]
	at com.hazelcast.instance.impl.DefaultAddressPicker.pickAddress(DefaultAddressPicker.java:121) [classes/:?]
	at com.hazelcast.instance.impl.DefaultAddressPickerTest.testBindAddress(DefaultAddressPickerTest.java:173) [test-classes/:?]
	at com.hazelcast.instance.impl.DefaultAddressPickerTest.testBindAddress_withDefaultPortAndLoopbackAddress(DefaultAddressPickerTest.java:104) [test-classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59) [junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56) [junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) [junit-4.13.2.jar:4.13.2]
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115) [test-classes/:?]
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107) [test-classes/:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

**Comment by frant-hartm** [comment]
Previously there were failures of this test 
#19856
#20470

**Comment by AyberkSorgun** [comment]
Haven't observed for a long time, will reopen if it fails again.
