### ISSUE TITLE
com.hazelcast.jet.sql_slow.MapScanMigrationStressTest.com.hazelcast.jet.sql_slow.MapScanMigrationStressTest

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#21082]
_5.1.z_ (commit a4619cf8522b6ce6b9fcb23db62d86bf62484acd)

**_It can have the same root cause as some other test failures from com.hazelcast.jet.sql_slow package._** 

Failed on Sonar (Oracle JDK 11): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-sonar/177/testReport/com.hazelcast.jet.sql_slow/MapScanMigrationStressTest/com_hazelcast_jet_sql_slow_MapScanMigrationStressTest/

<details><summary>Stacktrace:</summary>

```
org.junit.runners.model.TestTimedOutException: test timed out after 900 seconds
	at java.base@11.0.13/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@11.0.13/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
	at java.base@11.0.13/java.util.concurrent.FutureTask.awaitDone(FutureTask.java:444)
	at java.base@11.0.13/java.util.concurrent.FutureTask.get(FutureTask.java:203)
	at app//com.hazelcast.test.FailOnTimeoutStatement.getResult(FailOnTimeoutStatement.java:80)
	at app//com.hazelcast.test.FailOnTimeoutStatement.evaluate(FailOnTimeoutStatement.java:58)
	at app//org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at app//com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:365)
	at app//com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37)
	at app//com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:104)
	at app//com.hazelcast.test.metrics.MetricsRule$1.evaluate(MetricsRule.java:63)
	at app//org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at app//org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at app//org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at app//org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at app//com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:50)
	at app//com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:29)
	at app//org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at app//org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at app//org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at app//org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at app//org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at app//com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:39)
	at app//com.hazelcast.test.OverridePropertyRule$1.evaluate(OverridePropertyRule.java:66)
	at app//org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at app//org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.base@11.0.13/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base@11.0.13/java.lang.Thread.run(Thread.java:834)
```

</details>

Standard output is available at https://console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-5.maintenance-sonar/177/

**Comment by olukas** [comment]
Failed on `5.1.z` on Sonar build (Oracle JDK 11): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-sonar/335/testReport/com.hazelcast.jet.sql_slow/MapScanMigrationStressTest/com_hazelcast_jet_sql_slow_MapScanMigrationStressTest/
