### ISSUE TITLE
com.hazelcast.client.ClientRegressionWithRealNetworkTest.testOperationsContinueWhenClientDisconnected_reconnectModeAsync [API-1391]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#21094]
_master_ (commit 5eb350c32a03cbe378a2726bf58be880a5b8f21d)

Failed on Sonar build (Oracle JDK 11): http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/1171/testReport/com.hazelcast.client/ClientRegressionWithRealNetworkTest/testOperationsContinueWhenClientDisconnected_reconnectModeAsync/

It can have the same root cause as https://github.com/hazelcast/hazelcast/issues/19757

<details><summary>Stacktrace:</summary>

```
com.hazelcast.client.HazelcastClientOfflineException: No connection found to cluster
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.checkInvocationAllowed(TcpClientConnectionManager.java:546)
	at com.hazelcast.client.impl.spi.impl.ClientInvocationServiceImpl.checkInvocationAllowed(ClientInvocationServiceImpl.java:294)
	at com.hazelcast.client.impl.spi.impl.ClientInvocation.invokeOnSelection(ClientInvocation.java:178)
	at com.hazelcast.client.impl.spi.impl.ClientInvocation.invoke(ClientInvocation.java:156)
	at com.hazelcast.client.impl.spi.ClientProxy.invokeOnPartition(ClientProxy.java:187)
	at com.hazelcast.client.impl.spi.ClientProxy.invoke(ClientProxy.java:182)
	at com.hazelcast.client.impl.proxy.ClientMapProxy.putInternal(ClientMapProxy.java:537)
	at com.hazelcast.client.impl.proxy.ClientMapProxy.put(ClientMapProxy.java:269)
	at com.hazelcast.client.ClientRegressionWithRealNetworkTest.testOperationsContinueWhenClientDisconnected(ClientRegressionWithRealNetworkTest.java:261)
	at com.hazelcast.client.ClientRegressionWithRealNetworkTest.testOperationsContinueWhenClientDisconnected_reconnectModeAsync(ClientRegressionWithRealNetworkTest.java:209)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at ------ submitted from ------.()
	at com.hazelcast.internal.util.ExceptionUtil.cloneExceptionWithFixedAsyncStackTrace(ExceptionUtil.java:336)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.returnOrThrowWithGetConventions(InvocationFuture.java:112)
	at com.hazelcast.client.impl.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:95)
	at com.hazelcast.client.impl.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:40)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:609)
	at com.hazelcast.client.impl.spi.ClientProxy.invokeOnPartition(ClientProxy.java:188)
	at com.hazelcast.client.impl.spi.ClientProxy.invoke(ClientProxy.java:182)
	at com.hazelcast.client.impl.proxy.ClientMapProxy.putInternal(ClientMapProxy.java:537)
	at com.hazelcast.client.impl.proxy.ClientMapProxy.put(ClientMapProxy.java:269)
	at com.hazelcast.client.ClientRegressionWithRealNetworkTest.testOperationsContinueWhenClientDisconnected(ClientRegressionWithRealNetworkTest.java:261)
	at com.hazelcast.client.ClientRegressionWithRealNetworkTest.testOperationsContinueWhenClientDisconnected_reconnectModeAsync(ClientRegressionWithRealNetworkTest.java:209)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

</details>

Standart output can be downloaded from https://console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-sonar/1171/

**Comment by srknzl** [comment]
Stdout:

[com.hazelcast.client.ClientRegressionWithRealNetworkTest-output.txt](https://github.com/hazelcast/hazelcast/files/9354758/com.hazelcast.client.ClientRegressionWithRealNetworkTest-output.txt)
