### ISSUE TITLE
com.hazelcast.cache.CachePartitionLostListenerStressTest.testCachePartitionLostListener

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#21118]
_master_ (commit 9b3d845cb26e6b1cea1c09e9f50ab90afbc319fa)

Failed on ZuluJDK17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZuluJDK17-nightly/9/testReport/com.hazelcast.cache/CachePartitionLostListenerStressTest/testCachePartitionLostListener_numberOfNodesToCrash_3_withData_true_nodeLeaveType_TERMINATE_shouldExpectPartitionLostEvents_true_/

It failed in variant `[numberOfNodesToCrash:3,withData:true,nodeLeaveType:TERMINATE,shouldExpectPartitionLostEvents:true]`.

<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: Instances not in safe state! {[127.0.0.1]:5702=REPLICA_NOT_OWNED, [127.0.0.1]:5701=REPLICA_NOT_OWNED}
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at com.hazelcast.test.HazelcastTestSupport.assertAllInSafeState(HazelcastTestSupport.java:783)
	at com.hazelcast.test.HazelcastTestSupport$1.run(HazelcastTestSupport.java:748)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1226)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1243)
	at com.hazelcast.test.HazelcastTestSupport.waitAllForSafeState(HazelcastTestSupport.java:746)
	at com.hazelcast.test.HazelcastTestSupport.waitAllForSafeState(HazelcastTestSupport.java:742)
	at com.hazelcast.cache.CachePartitionLostListenerStressTest.testCachePartitionLostListener(CachePartitionLostListenerStressTest.java:117)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

</details>

Standard output can be downloaded from https://console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-ZuluJDK17-nightly/9/

**Comment by AyberkSorgun** [comment]
Last failure older than Nov 1st, closing for now
