### ISSUE TITLE
NotifyMemberShutdownOperation on shutdown from Spring Boot

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast#21123]
Using 5.2-SNAPSHOT (20220331 - 9b3d845)

I get an error when I try to shut the process, shutdown hooks out of order perhaps?

If I start a Spring Boot (2.6.5) process using `mvn spring-boot:run` or with `java -jar` and have this
```
    @Bean
    public HazelcastInstance hazelcastInstance() throws Exception {
        Config config = new Config();
        config.getJetConfig().setEnabled(true);
        config.getNetworkConfig().getJoin().getAutoDetectionConfig().setEnabled(false);
        config.getNetworkConfig().getJoin().getMulticastConfig().setEnabled(false);
        config.getNetworkConfig().getJoin().getTcpIpConfig().setEnabled(true).setMembers(List.of("127.0.0.1"));
        return Hazelcast.newHazelcastInstance(config);
    }
```
and then hit Ctrl-C I get a shutdown sequencing error

```
^C10:45:12.079 [hz.ShutdownThread] INFO  com.hazelcast.instance.impl.Node - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Running shutdown hook... Current state: ACTIVE
10:45:12.080 [hz.ShutdownThread] INFO  com.hazelcast.core.LifecycleService - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
10:45:12.083 [hz.ShutdownThread] WARN  com.hazelcast.instance.impl.Node - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Terminating forcefully...
10:45:12.083 [hz.ShutdownThread] INFO  com.hazelcast.instance.impl.Node - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Shutting down connection manager...
10:45:12.086 [hz.ShutdownThread] INFO  com.hazelcast.instance.impl.Node - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Shutting down node engine...
10:45:12.091 [hz.ShutdownThread] INFO  com.hazelcast.instance.impl.NodeExtension - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Destroying node NodeExtension.
10:45:12.092 [hz.ShutdownThread] INFO  com.hazelcast.instance.impl.Node - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Hazelcast Shutdown is completed in 9 ms.
10:45:12.092 [hz.ShutdownThread] INFO  com.hazelcast.core.LifecycleService - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
10:45:12.092 [SpringApplicationShutdownHook] INFO  com.hazelcast.core.LifecycleService - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
10:45:12.094 [ForkJoinPool.commonPool-worker-1] WARN  com.hazelcast.jet.impl.JetServiceBackend - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Failed to notify master member that this member is shutting down, will retry in 5 seconds
 com.hazelcast.core.HazelcastInstanceNotActiveException: State: SHUT_DOWN Operation: class com.hazelcast.jet.impl.operation.NotifyMemberShutdownOperation
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.engineActive(Invocation.java:513) ~[hazelcast-5.2-SNAPSHOT.jar:5.2-SNAPSHOT]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:551) ~[hazelcast-5.2-SNAPSHOT.jar:5.2-SNAPSHOT]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:541) ~[hazelcast-5.2-SNAPSHOT.jar:5.2-SNAPSHOT]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:241) ~[hazelcast-5.2-SNAPSHOT.jar:5.2-SNAPSHOT]
	at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.invokeOnTarget(OperationServiceImpl.java:365) ~[hazelcast-5.2-SNAPSHOT.jar:5.2-SNAPSHOT]
	at com.hazelcast.jet.impl.JetServiceBackend.notifyMasterWeAreShuttingDown(JetServiceBackend.java:181) ~[hazelcast-5.2-SNAPSHOT.jar:5.2-SNAPSHOT]
	at com.hazelcast.jet.impl.JetServiceBackend.shutDownJobs(JetServiceBackend.java:164) ~[hazelcast-5.2-SNAPSHOT.jar:5.2-SNAPSHOT]
	at com.hazelcast.instance.impl.DefaultNodeExtension.beforeShutdown(DefaultNodeExtension.java:474) ~[hazelcast-5.2-SNAPSHOT.jar:5.2-SNAPSHOT]
	at com.hazelcast.instance.impl.Node.shutdown(Node.java:508) ~[hazelcast-5.2-SNAPSHOT.jar:5.2-SNAPSHOT]
	at com.hazelcast.instance.impl.LifecycleServiceImpl.shutdown(LifecycleServiceImpl.java:101) ~[hazelcast-5.2-SNAPSHOT.jar:5.2-SNAPSHOT]
	at com.hazelcast.instance.impl.LifecycleServiceImpl.shutdown(LifecycleServiceImpl.java:84) ~[hazelcast-5.2-SNAPSHOT.jar:5.2-SNAPSHOT]
	at com.hazelcast.instance.impl.HazelcastInstanceProxy.shutdown(HazelcastInstanceProxy.java:311) ~[hazelcast-5.2-SNAPSHOT.jar:5.2-SNAPSHOT]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.springframework.beans.factory.support.DisposableBeanAdapter.invokeCustomDestroyMethod(DisposableBeanAdapter.java:319) ~[spring-beans-5.3.17.jar:5.3.17]
	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:253) ~[spring-beans-5.3.17.jar:5.3.17]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:587) ~[spring-beans-5.3.17.jar:5.3.17]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:559) ~[spring-beans-5.3.17.jar:5.3.17]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:1161) ~[spring-beans-5.3.17.jar:5.3.17]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:520) ~[spring-beans-5.3.17.jar:5.3.17]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:1154) ~[spring-beans-5.3.17.jar:5.3.17]
	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1106) ~[spring-context-5.3.17.jar:5.3.17]
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1075) ~[spring-context-5.3.17.jar:5.3.17]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.doClose(ServletWebServerApplicationContext.java:172) ~[spring-boot-2.6.5.jar:2.6.5]
	at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:1021) ~[spring-context-5.3.17.jar:5.3.17]
	at org.springframework.boot.SpringApplicationShutdownHook.closeAndWait(SpringApplicationShutdownHook.java:145) ~[spring-boot-2.6.5.jar:2.6.5]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at org.springframework.boot.SpringApplicationShutdownHook.run(SpringApplicationShutdownHook.java:114) ~[spring-boot-2.6.5.jar:2.6.5]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
10:45:22.096 [SpringApplicationShutdownHook] ERROR com.hazelcast.jet.impl.JetServiceBackend - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Shutdown jobs timeout
 java.util.concurrent.TimeoutException: null
	at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1960) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2095) ~[?:?]
	at com.hazelcast.jet.impl.JetServiceBackend.shutDownJobs(JetServiceBackend.java:168) ~[hazelcast-5.2-SNAPSHOT.jar:5.2-SNAPSHOT]
	at com.hazelcast.instance.impl.DefaultNodeExtension.beforeShutdown(DefaultNodeExtension.java:474) ~[hazelcast-5.2-SNAPSHOT.jar:5.2-SNAPSHOT]
	at com.hazelcast.instance.impl.Node.shutdown(Node.java:508) ~[hazelcast-5.2-SNAPSHOT.jar:5.2-SNAPSHOT]
	at com.hazelcast.instance.impl.LifecycleServiceImpl.shutdown(LifecycleServiceImpl.java:101) ~[hazelcast-5.2-SNAPSHOT.jar:5.2-SNAPSHOT]
	at com.hazelcast.instance.impl.LifecycleServiceImpl.shutdown(LifecycleServiceImpl.java:84) ~[hazelcast-5.2-SNAPSHOT.jar:5.2-SNAPSHOT]
	at com.hazelcast.instance.impl.HazelcastInstanceProxy.shutdown(HazelcastInstanceProxy.java:311) ~[hazelcast-5.2-SNAPSHOT.jar:5.2-SNAPSHOT]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.springframework.beans.factory.support.DisposableBeanAdapter.invokeCustomDestroyMethod(DisposableBeanAdapter.java:319) ~[spring-beans-5.3.17.jar:5.3.17]
	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:253) ~[spring-beans-5.3.17.jar:5.3.17]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:587) ~[spring-beans-5.3.17.jar:5.3.17]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:559) ~[spring-beans-5.3.17.jar:5.3.17]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:1161) ~[spring-beans-5.3.17.jar:5.3.17]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:520) ~[spring-beans-5.3.17.jar:5.3.17]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:1154) ~[spring-beans-5.3.17.jar:5.3.17]
	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1106) ~[spring-context-5.3.17.jar:5.3.17]
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1075) ~[spring-context-5.3.17.jar:5.3.17]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.doClose(ServletWebServerApplicationContext.java:172) ~[spring-boot-2.6.5.jar:2.6.5]
	at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:1021) ~[spring-context-5.3.17.jar:5.3.17]
	at org.springframework.boot.SpringApplicationShutdownHook.closeAndWait(SpringApplicationShutdownHook.java:145) ~[spring-boot-2.6.5.jar:2.6.5]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at org.springframework.boot.SpringApplicationShutdownHook.run(SpringApplicationShutdownHook.java:114) ~[spring-boot-2.6.5.jar:2.6.5]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
10:45:22.097 [SpringApplicationShutdownHook] INFO  com.hazelcast.instance.impl.Node - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Node is already shutting down... Waiting for shutdown process to complete...
10:45:22.098 [SpringApplicationShutdownHook] INFO  com.hazelcast.core.LifecycleService - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
```

**Comment by frant-hartm** [comment]
I would say this is misconfiguration (which we can definitely handle much better).

The problem is that you have 2 shutdown hooks:
- Hazelcast shutdown hook, which calls terminate by default
- Spring shutdown hook, which will call `shutdown` method on your `HazelcastInstance` bean (the `shutdown` method is auto-detected) - this will be graceful shutdown

The order of shutdown hooks is not specified, they run in arbitrary order, so when the Hz hook runs first (terminate) and Spring second (graceful) this happens, and can be reproduced by calling terminate and shutdown from 2 different threads quickly.

Generally, you should disable Hazelcast shutdown hook when using Spring Boot - we need to document this better - the reason is that the Spring let's the servlet container finish the current requests, if you shutdown Hz at concurrently and any of the requests touches Hazelcast you will get `HazelcastInstance is not active` exception.

Additionally, we should either handle or prevent calling both terminate and shutdown at the same time.

**Comment by neilstevenson** [comment]
Should this be an issue and a PR for Spring Boot then ?
When Spring Boot detects a Hazelcast Bean exists.
