### ISSUE TITLE
Dynamic Configuration addMapConfig method's some nullable fields are not nullable [HZ-1171]

### ISSUE THREAD

**Issue by mtyazici** [hazelcast/hazelcast#21182]
**Describe the bug**
I generated the codecs for the [DynamicConfig.addMapConfig](https://github.com/hazelcast/hazelcast-client-protocol/blob/master/protocol-definitions/DynamicConfig.yaml#L699-L887=) using the Go codec generator in [hazelcast-client-protocol](https://github.com/hazelcast/hazelcast-client-protocol). In the method inputs `HotRestartConfig`, `EventJournalConfig` and `MerkleTreeConfig` are defined to be nullable. However, when I try to give null values to them, Hazelcast member returns an error. like the following:

```
panic: invoking: got exception from server:
 java.lang.NullPointerException: MerkleTreeConfig cannot be null
 
 com.hazelcast.internal.util.Preconditions.checkNotNull(Preconditions.java:59)
 com.hazelcast.config.MapConfig.setMerkleTreeConfig(MapConfig.java:743)
 com.hazelcast.client.impl.protocol.task.dynamicconfig.AddMapConfigMessageTask.getConfig(AddMapConfigMessageTask.java:66)
 com.hazelcast.client.impl.protocol.task.dynamicconfig.AbstractAddConfigMessageTask.processMessage(AbstractAddConfigMessageTask.java:71)
 com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:153)
 com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:116)
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
 java.lang.Thread.run(Thread.java:829)
 com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
 com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102): MerkleTreeConfig cannot be null

goroutine 1 [running]:
main.main()
        /home/mty/Whz/hazelcast-enterprise-operator/main.go:304 +0x5eb
exit status 2
make: *** [Makefile:162: run] Error 1
```

The errors for  `HotRestartConfig`, `EventJournalConfig` are pretty much the same.

I also got an error when setting up the [MapStoreConfigHolder](https://github.com/hazelcast/hazelcast-client-protocol/blob/master/protocol-definitions/custom/Custom.yaml#L209-L251=) field. It has 5 required files. However, when I do not define the `properties` field, which is not a required field, Hazelcast member returns an error:
```
panic: invoking: got exception from server:
 java.lang.NullPointerException: 
 
 java.util.concurrent.ConcurrentHashMap.putAll(ConcurrentHashMap.java:1087)
 java.util.Properties.putAll(Properties.java:1350)
 com.hazelcast.client.impl.protocol.util.PropertiesUtil.fromMap(PropertiesUtil.java:31)
 com.hazelcast.client.impl.protocol.task.dynamicconfig.MapStoreConfigHolder.asMapStoreConfig(MapStoreConfigHolder.java:152)
 com.hazelcast.client.impl.protocol.task.dynamicconfig.AddMapConfigMessageTask.getConfig(AddMapConfigMessageTask.java:76)
 com.hazelcast.client.impl.protocol.task.dynamicconfig.AbstractAddConfigMessageTask.processMessage(AbstractAddConfigMessageTask.java:71)
 com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:153)
 com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:116)
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
 java.lang.Thread.run(Thread.java:829)
 com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
 com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102): 
```
Also when `mapStoreConfigHolder` is enabled, `className` must also be given even though it is nullable. I am not sure if this one is a problem but just wanted to add. 

**Expected behavior**
Mentioned input fields should work as defined in the client protocol. 
- `HotRestartConfig`, `EventJournalConfig` and `MerkleTreeConfig` should be nullable. 
- `properties` field in `MapStoreConfigHolder` should also be nullable. 

**To Reproduce**

1. Generate codec for the `DynamicConfig.addMapConfig` method in Go client and use the internal client exposed in https://github.com/hazelcast/hazelcast-go-client/pull/754.
2. Send the request to a Hazelcast member with the mentioned fields.

**Comment by mtyazici** [comment]
Today, I also faced with an issue with [IndexConfigs](https://github.com/hazelcast/hazelcast-client-protocol/blob/master/protocol-definitions/DynamicConfig.yaml#L824=) field. When I create an indexConfig with following properties ` IndexConfig{name=index, type=SORTED, attributes=[]}` there is no error in the response. However, in the Hazelcast side I see the following error.

```
2022-04-12 08:15:13,391 [ERROR] [hz.competent_morse.client-blocking-tasks.thread-3] [c.h.s.i.p.i.o.InitializeDistributedObjectOperation]: [172.17.0.3]:5701 [dev] [5.1.1] Index must have at least one attribute: IndexConfig{name=index, type=SORTED, attributes=[]}
java.lang.IllegalArgumentException: Index must have at least one attribute: IndexConfig{name=index, type=SORTED, attributes=[]}
	at com.hazelcast.query.impl.IndexUtils.validateAndNormalize(IndexUtils.java:70) ~[hazelcast-5.1.1.jar:5.1.1]
	at com.hazelcast.map.impl.proxy.MapProxySupport.addIndex(MapProxySupport.java:1334) ~[hazelcast-5.1.1.jar:5.1.1]
	at com.hazelcast.map.impl.proxy.MapProxyImpl.addIndex(MapProxyImpl.java:112) ~[hazelcast-5.1.1.jar:5.1.1]
	at com.hazelcast.map.impl.proxy.MapProxySupport.initializeIndexes(MapProxySupport.java:321) ~[hazelcast-5.1.1.jar:5.1.1]
	at com.hazelcast.map.impl.proxy.MapProxySupport.initialize(MapProxySupport.java:264) ~[hazelcast-5.1.1.jar:5.1.1]
	at com.hazelcast.map.impl.proxy.MapProxyImpl.initialize(MapProxyImpl.java:112) ~[hazelcast-5.1.1.jar:5.1.1]
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyRegistry.doCreateProxy(ProxyRegistry.java:266) ~[hazelcast-5.1.1.jar:5.1.1]
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyRegistry.createProxy(ProxyRegistry.java:235) ~[hazelcast-5.1.1.jar:5.1.1]
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyServiceImpl.initializeDistributedObject(ProxyServiceImpl.java:139) ~[hazelcast-5.1.1.jar:5.1.1]
	at com.hazelcast.spi.impl.proxyservice.impl.operations.InitializeDistributedObjectOperation.run(InitializeDistributedObjectOperation.java:44) ~[hazelcast-5.1.1.jar:5.1.1]
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:189) [hazelcast-5.1.1.jar:5.1.1]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:273) [hazelcast-5.1.1.jar:5.1.1]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:248) [hazelcast-5.1.1.jar:5.1.1]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:213) [hazelcast-5.1.1.jar:5.1.1]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:411) [hazelcast-5.1.1.jar:5.1.1]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:438) [hazelcast-5.1.1.jar:5.1.1]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:601) [hazelcast-5.1.1.jar:5.1.1]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:580) [hazelcast-5.1.1.jar:5.1.1]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:541) [hazelcast-5.1.1.jar:5.1.1]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:241) [hazelcast-5.1.1.jar:5.1.1]
	at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:61) [hazelcast-5.1.1.jar:5.1.1]
	at com.hazelcast.client.impl.protocol.task.AbstractInvocationMessageTask.processInternal(AbstractInvocationMessageTask.java:38) [hazelcast-5.1.1.jar:5.1.1]
	at com.hazelcast.client.impl.protocol.task.AbstractAsyncMessageTask.processMessage(AbstractAsyncMessageTask.java:71) [hazelcast-5.1.1.jar:5.1.1]
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:153) [hazelcast-5.1.1.jar:5.1.1]
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:116) [hazelcast-5.1.1.jar:5.1.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76) [hazelcast-5.1.1.jar:5.1.1]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) [hazelcast-5.1.1.jar:5.1.1]
```
