### ISSUE TITLE
com.hazelcast.jet.sql.SqlUnionTest.watermarkedStreamUnionAllTest

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#21218]
_master_ (commit 8195305736c4c34fae0d4846449fdb9c9c3b58be)

Failed on Sonar build (Oracle JDK 11): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/1185/testReport/com.hazelcast.jet.sql/SqlUnionTest/watermarkedStreamUnionAllTest/

<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: 

Actual and expected have the same elements but not in the same order, at index 0 actual element was:
  <Row{[1970-01-01T00:00:00.012Z, 2]}>
whereas expected element was:
  <Row{[1970-01-01T00:00:00.010Z, 1]}>

	at com.hazelcast.jet.sql.SqlTestSupport.assertTipOfStream(SqlTestSupport.java:247)
	at com.hazelcast.jet.sql.SqlUnionTest.watermarkedStreamUnionAllTest(SqlUnionTest.java:230)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

</details>

<details><summary>Standard output:</summary>

```
CREATE MAPPING o_cbf3740e_6abc_4946_96de_c94ce9781732 TYPE TestStream OPTIONS ('names'='ts,id', 'types'='TIMESTAMP_WITH_TIME_ZONE,INTEGER', 'values'='1970-01-01T00:00:00.010Z,1
1970-01-01T00:00:00.012Z,2
1970-01-01T00:00:00.014Z,3
1970-01-01T00:00Z,4', 'streaming'='true')
03:46:24,250 DEBUG |watermarkedStreamUnionAllTest| - [CalciteSqlOptimizer] Thread-1998 - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Before logical opt:
LogicalUnion(all=[true])
  LogicalTableFunctionScan(invocation=[IMPOSE_ORDER($1, DESCRIPTOR($0), 1:INTERVAL DAY TO SECOND)], rowType=[RecordType(TIMESTAMP WITH TIME ZONE ts, INTEGER id)])
    LogicalTableScan(table=[[hazelcast, public, o_cbf3740e_6abc_4946_96de_c94ce9781732[projects=[$0, $1]]]])
  LogicalTableFunctionScan(invocation=[IMPOSE_ORDER($1, DESCRIPTOR($0), 1:INTERVAL DAY TO SECOND)], rowType=[RecordType(TIMESTAMP WITH TIME ZONE ts, INTEGER id)])
    LogicalTableScan(table=[[hazelcast, public, o_cbf3740e_6abc_4946_96de_c94ce9781732[projects=[$0, $1]]]])

03:46:24,250 DEBUG |watermarkedStreamUnionAllTest| - [CalciteSqlOptimizer] Thread-1998 - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] After logical opt:
DropLateItemsLogicalRel(traitSet=[LOGICAL.[].ANY])
  UnionLogicalRel(all=[true])
    FullScanLogicalRel(table=[[hazelcast, public, o_cbf3740e_6abc_4946_96de_c94ce9781732[projects=[$0, $1]]]], eventTimePolicyProvider=[com.hazelcast.jet.sql.impl.opt.logical.WatermarkRules$1$$Lambda$3113/0x0000000100d01c40@7571497e], watermarkedColumnIndex=[0])
    FullScanLogicalRel(table=[[hazelcast, public, o_cbf3740e_6abc_4946_96de_c94ce9781732[projects=[$0, $1]]]], eventTimePolicyProvider=[com.hazelcast.jet.sql.impl.opt.logical.WatermarkRules$1$$Lambda$3113/0x0000000100d01c40@7571497e], watermarkedColumnIndex=[0])

03:46:24,251 DEBUG |watermarkedStreamUnionAllTest| - [CalciteSqlOptimizer] Thread-1998 - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] After physical opt:
DropLateItemsPhysicalRel(traitSet=[PHYSICAL.[].ANY])
  UnionPhysicalRel(all=[true])
    FullScanPhysicalRel(table=[[hazelcast, public, o_cbf3740e_6abc_4946_96de_c94ce9781732[projects=[$0, $1]]]], eventTimePolicyProvider=[com.hazelcast.jet.sql.impl.opt.logical.WatermarkRules$1$$Lambda$3113/0x0000000100d01c40@7571497e], watermarkedColumnIndex=[0])
    FullScanPhysicalRel(table=[[hazelcast, public, o_cbf3740e_6abc_4946_96de_c94ce9781732[projects=[$0, $1]]]], eventTimePolicyProvider=[com.hazelcast.jet.sql.impl.opt.logical.WatermarkRules$1$$Lambda$3113/0x0000000100d01c40@7571497e], watermarkedColumnIndex=[0])

03:46:24,251 DEBUG |watermarkedStreamUnionAllTest| - [LightMasterContext] Thread-1998 - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Start executing light job 07dc-80be-da01-0001, execution graph in DOT format:
digraph DAG {
	"TestStream[public.o_cbf3740e_6abc_4946_96de_c94ce9781732]" [localParallelism=1];
	"TestStream[public.o_cbf3740e_6abc_4946_96de_c94ce9781732]-2" [localParallelism=1];
	"UnionMerger" [localParallelism=2];
	"Drop-Late-Items" [localParallelism=2];
	"ClientSink" [localParallelism=1];
	"TestStream[public.o_cbf3740e_6abc_4946_96de_c94ce9781732]" -> "UnionMerger" [label="isolated", headlabel=0, queueSize=1024];
	"TestStream[public.o_cbf3740e_6abc_4946_96de_c94ce9781732]-2" -> "UnionMerger" [label="isolated", headlabel=1, queueSize=1024];
	"UnionMerger" -> "Drop-Late-Items" [label="isolated", queueSize=1024];
	"Drop-Late-Items" -> "ClientSink" [label="distributed to [127.0.0.1]:5701-partitioned", queueSize=1024];
}
HINT: You can use graphviz or http://viz-js.com/ to visualize the printed graph.
03:46:24,251 DEBUG |watermarkedStreamUnionAllTest| - [LightMasterContext] Thread-1998 - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Building execution plan for 07dc-80be-da01-0001
03:46:24,252 DEBUG |watermarkedStreamUnionAllTest| - [LightMasterContext] Thread-1998 - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Built execution plans for 07dc-80be-da01-0001
03:46:24,252 DEBUG |watermarkedStreamUnionAllTest| - [InitExecutionOperation] Thread-1998 - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Initializing execution plan for job 07dc-80be-da01-0001, execution 07dc-80be-da01-0001 from [127.0.0.1]:5701
03:46:24,253 DEBUG |watermarkedStreamUnionAllTest| - [JobExecutionService] Thread-1998 - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Execution plan for light job ID=07dc-80be-da01-0001, jobName='07dc-80be-da01-0001', executionId=07dc-80be-da01-0001 initialized, will start the execution
03:46:24,253  INFO || - [LateItemsDropP] hz.lucid_sanderson.jet.cooperative.thread-1 - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] [07dc-80be-da01-0001/Drop-Late-Items#1] Late event dropped. currentWatermark=Watermark{ts=00:00:00.013}, event=[1970-01-01T00:00Z, 4]
03:46:24,253  INFO || - [LateItemsDropP] hz.lucid_sanderson.jet.cooperative.thread-1 - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] [07dc-80be-da01-0001/Drop-Late-Items#1] Late event dropped. currentWatermark=Watermark{ts=00:00:00.013}, event=[1970-01-01T00:00Z, 4]
03:46:24,254 DEBUG || - [TaskletExecutionService] hz.lucid_sanderson.jet.cooperative.thread-0 - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Job was cancelled by the user.
03:46:24,254 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-11 - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Completed execution of job '07dc-80be-da01-0001', execution 07dc-80be-da01-0001
03:46:24,339 DEBUG |multipleUnionAllTest| - [JobRepository] hz.lucid_sanderson.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Job cleanup took 0ms
03:46:24,254 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-11 - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Execution of job '07dc-80be-da01-0001', execution 07dc-80be-da01-0001 completed with failure
java.util.concurrent.CompletionException: java.util.concurrent.CancellationException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:870) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088) ~[?:?]
	at com.hazelcast.jet.impl.util.NonCompletableFuture.internalCompleteExceptionally(NonCompletableFuture.java:72) ~[hazelcast-5.2-SNAPSHOT.jar:5.2-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$ExecutionTracker.taskletDone(TaskletExecutionService.java:495) ~[hazelcast-5.2-SNAPSHOT.jar:5.2-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.dismissTasklet(TaskletExecutionService.java:426) ~[hazelcast-5.2-SNAPSHOT.jar:5.2-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:412) ~[hazelcast-5.2-SNAPSHOT.jar:5.2-SNAPSHOT]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807) ~[?:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.run(TaskletExecutionService.java:369) ~[hazelcast-5.2-SNAPSHOT.jar:5.2-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:834) ~[?:?]
Caused by: java.util.concurrent.CancellationException
	at com.hazelcast.jet.sql.impl.processors.RootResultConsumerSink.tryProcess(RootResultConsumerSink.java:97) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.lambda$stateMachineStep$2(ProcessorTasklet.java:297) ~[hazelcast-5.2-SNAPSHOT.jar:5.2-SNAPSHOT]
	at com.hazelcast.jet.impl.util.Util.doWithClassLoader(Util.java:540) ~[hazelcast-5.2-SNAPSHOT.jar:5.2-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:297) ~[hazelcast-5.2-SNAPSHOT.jar:5.2-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:281) ~[hazelcast-5.2-SNAPSHOT.jar:5.2-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:255) ~[hazelcast-5.2-SNAPSHOT.jar:5.2-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:401) ~[hazelcast-5.2-SNAPSHOT.jar:5.2-SNAPSHOT]
	... 3 more
03:46:24,343 ERROR || - [EventServiceImpl] hz.lucid_sanderson.event-2160 - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] hz.lucid_sanderson.event-2160 caught an exception while processing:com.hazelcast.spi.impl.eventservice.impl.LocalEventDispatcher@4f935db2
java.lang.UnsupportedOperationException: SQL catalog must never be cleared - MapEvent{entryEventType=CLEAR_ALL, member=Member [127.0.0.1]:5701 - f7cc5b95-1de9-4038-8331-4dc7e8e429a7 this, name='__sql.catalog', numberOfEntriesAffected=1}
	at com.hazelcast.jet.sql.impl.schema.TablesStorage$EntryListenerAdapter.mapCleared(TablesStorage.java:202) ~[classes/:?]
	at com.hazelcast.replicatedmap.impl.ReplicatedMapEventPublishingService.dispatchEvent(ReplicatedMapEventPublishingService.java:132) ~[hazelcast-5.2-SNAPSHOT.jar:5.2-SNAPSHOT]
	at com.hazelcast.replicatedmap.impl.ReplicatedMapService.dispatchEvent(ReplicatedMapService.java:232) ~[hazelcast-5.2-SNAPSHOT.jar:5.2-SNAPSHOT]
	at com.hazelcast.spi.impl.eventservice.impl.LocalEventDispatcher.run(LocalEventDispatcher.java:64) ~[hazelcast-5.2-SNAPSHOT.jar:5.2-SNAPSHOT]
	at com.hazelcast.internal.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:245) [hazelcast-5.2-SNAPSHOT.jar:5.2-SNAPSHOT]
	at com.hazelcast.internal.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:228) [hazelcast-5.2-SNAPSHOT.jar:5.2-SNAPSHOT]
BuildInfo right after watermarkedStreamUnionAllTest(com.hazelcast.jet.sql.SqlUnionTest): BuildInfo{version='5.2-SNAPSHOT', build='20220412', buildNumber=20220412, revision=8195305, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'watermarkedStreamUnionAllTest(com.hazelcast.jet.sql.SqlUnionTest):'
03:46:20, accumulated pauses: 108 ms, max pause: 75 ms, pauses over 1000 ms: 0
```

</details>

**Comment by olukas** [comment]
Failed again on:
- Sonar build (Oracle JDK 11): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/1191/testReport/com.hazelcast.jet.sql/SqlUnionTest/watermarkedStreamUnionAllTest/
- Zulu JDK 17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZuluJDK17/28/testReport/com.hazelcast.jet.sql/SqlUnionTest/watermarkedStreamUnionAllTest/
- Windows with Oracle JDK 8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Windows-OracleJDK8/391/testReport/com.hazelcast.jet.sql/SqlUnionTest/watermarkedStreamUnionAllTest/
- MacOS with Zulu JDK 8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-MacOS-ZuluJDK8/59/testReport/com.hazelcast.jet.sql/SqlUnionTest/watermarkedStreamUnionAllTest/
- RedHat JDK 8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-RedHatJDK8/34/testReport/com.hazelcast.jet.sql/SqlUnionTest/watermarkedStreamUnionAllTest/
- Openj9-17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Openj9-17/9/testReport/com.hazelcast.jet.sql/SqlUnionTest/watermarkedStreamUnionAllTest/
- RedHat JDK 11: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-RedHatJDK11/27/testReport/com.hazelcast.jet.sql/SqlUnionTest/watermarkedStreamUnionAllTest/
