### ISSUE TITLE
Hazelcast test support depends on JUnit 4 (undeclared)

### ISSUE THREAD

**Issue by joschi** [hazelcast/hazelcast#21226]
**Describe the bug**

`com.hazelcast:hazelcast:5.1.1:tests` depends on JUnit 4 but doesn't declare this dependency.

This leads to errors during test runtime when classes such as `MockServer` are being used and JUnit 4 is not on the classpath:
```
java.lang.NoClassDefFoundError: junit/framework/AssertionFailedError
	at com.hazelcast.test.mocknetwork.MockServer.stop(MockServer.java:490)
	at com.hazelcast.test.mocknetwork.MockServer.shutdown(MockServer.java:505)
	at com.hazelcast.internal.server.FirewallingServer.shutdown(FirewallingServer.java:121)
	at com.hazelcast.instance.impl.Node.shutdownServices(Node.java:600)
	at com.hazelcast.instance.impl.Node.shutdown(Node.java:541)
	at com.hazelcast.instance.impl.LifecycleServiceImpl.shutdown(LifecycleServiceImpl.java:101)
	at com.hazelcast.instance.impl.LifecycleServiceImpl.shutdown(LifecycleServiceImpl.java:84)
	at com.hazelcast.test.mocknetwork.TestNodeRegistry.shutdown(TestNodeRegistry.java:141)
	at com.hazelcast.test.mocknetwork.TestNodeRegistry.shutdown(TestNodeRegistry.java:125)
	at com.hazelcast.test.TestHazelcastInstanceFactory.shutdownAll(TestHazelcastInstanceFactory.java:364)
```

**Expected behavior**

`com.hazelcast:hazelcast:*:tests` should have an explicit dependency on JUnit 4 and explicitly mention the exact version in the documentation:

https://docs.hazelcast.com/hazelcast/5.1/test/testing

**Additional context**

Our project is using JUnit 5 exclusively and we in fact prevent JUnit 4 from being imported accidentally to avoid a mix of different major versions of JUnit.

Ideally, Hazelcast test support would either not depend on any specific test framework or have variants for JUnit 4 and 5.

**Comment by olukas** [comment]
I think there shouldn't be any problem to declare it in hazelcast/hazelcast module and take the version from parent (@frant-hartm - do you see some problem there?). However we're currently using JUnit `4.13.2`.

**Comment by frant-hartm** [comment]
I don't think we can do this without restructuring our artifacts.

The test jar `com.hazelcast:hazelcast:5.1.1:tests` is a jar with a classifier, it shares the pom with our main jar - `com.hazelcast:hazelcast`.

We already declare a dependency on junit in the test scope for our main artifact (not directly in `hazelcast/pom.xml`, but inherit from the root pom.xml). **The cause of the problem here is that test dependencies don't propagate transitively**.

The solution would be to extract our test code into a separate module and publish as a regular artifact without a classifier with junit as a dependency with compile scope. But that would require quite a few changes in many places in our testing infrastructure.

We can certainly improve the documentation though.

**Comment by Holmistr** [comment]
Wouldn't a workaround be to not just declare the dependcy in the root `pom.xml` but copy paste it to the modules as well? 
I know that it's a code duplication but if it would fix user's problem, I think it's worth considering. The ultimate solution of separating the artifacts is definitely much bigger effort and we have more urgent things to be done. I'm just trying to find some workaround/way out for @joschi .

WDYT?

**Comment by frant-hartm** [comment]
No, the problem is not between our `hazelcast/pom.xml` and the root pom, but between the user's pom.xml and `hazelcast/pom.xml`.

Basically, if you, in your own project, declare a dependency on `com.hazelcast:hazelcast:5.1.1`  (or `com.hazelcast:hazelcast:5.1.1:tests`, doesn't matter) you get transitive dependencies, but `test` scoped dependencies are excluded from this.

https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#dependency-scope
>test
>This scope indicates that the dependency is not required for normal use of the application, and is only available for the test compilation and execution phases. This scope is not transitive.  ...


I am not sure if we can resolve @joschi's problem easily, we depend on JUnit 4 classes in our test infrastructure, the solution is easy - add junit 4 on classpath, but they don't want to do that:

> Our project is using JUnit 5 exclusively and we in fact prevent JUnit 4 from being imported accidentally to avoid a mix of different major versions of JUnit.

**Comment by Holmistr** [comment]
I see, thanks @frant-hartm .

@joschi Given the explanations and above information, unfortunately we won't prioritize this further at this point. Our resources are limited and this doesn't seem to me like a common case. I'm sure at some point, we'll move to JUnit 5 which will, to my understanding, solve your issue as well. 

I'll keep this issue opened to let you when when that happens, but unfortunately, I cannot give you a precise timeline.

**Comment by MartinHatas** [comment]
+1
