### ISSUE TITLE
com.hazelcast.client.internal.metrics.ClientJmxMetricsTest.testNoMBeanLeak [HZ-1092]

### ISSUE THREAD

**Issue by bpoplawski** [hazelcast/hazelcast#21245]
Similar issue was found in the past on 4.2. In same code line - (Assert.java:89). Possibly back port needed see 
https://github.com/hazelcast/hazelcast/issues/18723

_4.1.9_ (commit 4652d92b64688689a0f78d2002bb423bc0e932d0 )

Failed on SONAR: http://jenkins.hazelcast.com/job/hazelcast-sonar-release-maintenance-4.x/13/consoleFull

<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: expected:<0> but was:<10>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at com.hazelcast.internal.metrics.jmx.JmxPublisherTestHelper.assertNoMBeans(JmxPublisherTestHelper.java:60)
	at com.hazelcast.client.internal.metrics.ClientJmxMetricsTest.testNoMBeanLeak(ClientJmxMetricsTest.java:52)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

</details>

<details><summary>Standard output:</summary>

```
10:41:25,767  INFO |testNoMBeanLeak| - [JmxPublisherTestHelper] testNoMBeanLeak - Dangling metrics MBeans created by 253@66d6447b1475: [Metric[com.hazelcast:type=Metrics,instance=hz.client_5046,prefix=gc], Metric[com.hazelcast:type=Metrics,instance=hz.client_5046,prefix=invocations], Metric[com.hazelcast:type=Metrics,instance=hz.client_5046,prefix=os], Metric[com.hazelcast:type=Metrics,instance=hz.client_5046,prefix=file.partition,tag0="dir=user.home"], Metric[com.hazelcast:type=Metrics,instance=hz.client_5046,prefix=thread], Metric[com.hazelcast:type=Metrics,instance=hz.client_5046,prefix=listeners], Metric[com.hazelcast:type=Metrics,instance=hz.client_5046,prefix=classloading], Metric[com.hazelcast:type=Metrics,instance=hz.client_5046,prefix=test-jvm-253@66d6447b1475], Metric[com.hazelcast:type=Metrics,instance=hz.client_5046,prefix=runtime], Metric[com.hazelcast:type=Metrics,instance=hz.client_5046,prefix=memory]]
10:41:26,390  WARN |testBlockingAsync| - [ClientConnectionManager] hz.client_5046.internal-4 - hz.client_5046 [dev] [4.1.9-SNAPSHOT] Could not connect to member 1cbef18b-c73e-44b6-90e0-5b9fb7a25cd7, reason com.hazelcast.core.HazelcastException: java.io.IOException: Can not connected to [127.0.0.1]:5701: instance does not exist
BuildInfo right after testNoMBeanLeak(com.hazelcast.client.internal.metrics.ClientJmxMetricsTest): BuildInfo{version='4.1.9-SNAPSHOT', build='20220415', buildNumber=20220415, revision=4652d92, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'testNoMBeanLeak(com.hazelcast.client.internal.metrics.ClientJmxMetricsTest):'
10:41:25, accumulated pauses: 620 ms, max pause: 616 ms, pauses over 1000 ms: 0
```

</details>

**Comment by ldziedziul** [comment]
Fixed with https://github.com/hazelcast/hazelcast/pull/21289
