### ISSUE TITLE
AIOOB when expanding star in JOIN with USING

### ISSUE THREAD

**Issue by viliam-durina** [hazelcast/hazelcast#21325]
The following test:
```java
public class FooTest extends SqlTestSupport {

    @Test
    public void test() {
        HazelcastInstance inst = createHazelcastInstance();
        createMapping(inst, "Hzl_Transaction", Long.class, Transaction.class);
        createMapping(inst, "Hzl_Account", Long.class, Account.class);

        inst.getSql().execute("select * from Hzl_Transaction JOIN Hzl_Account USING(bankId, accountNumber)");
    }

    public static class Transaction implements Serializable {
        public String bankId, accountNumber;
        public int amount;
    }

    public static class Account implements Serializable {
        public String bankId, accountNumber;
        public int balance;
    }
}
```
fails with:
```
com.hazelcast.sql.impl.QueryException: Index 8 out of bounds for length 8
	at com.hazelcast.sql.impl.QueryException.error(QueryException.java:65)
	at com.hazelcast.jet.sql.impl.parse.QueryParser.parse(QueryParser.java:67)
	at com.hazelcast.jet.sql.impl.OptimizerContext.parse(OptimizerContext.java:151)
	at com.hazelcast.jet.sql.impl.CalciteSqlOptimizer.prepare(CalciteSqlOptimizer.java:236)
	at com.hazelcast.sql.impl.SqlServiceImpl.prepare(SqlServiceImpl.java:252)
	at com.hazelcast.sql.impl.SqlServiceImpl.query0(SqlServiceImpl.java:236)
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:193)
	... 17 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 8 out of bounds for length 8
	at com.google.common.collect.RegularImmutableList.get(RegularImmutableList.java:75)
	at org.apache.calcite.sql.validate.SqlValidatorImpl$Permute.permute(SqlValidatorImpl.java:7106)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.expandStar(SqlValidatorImpl.java:664)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.expandSelectItem(SqlValidatorImpl.java:426)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateSelectList(SqlValidatorImpl.java:4409)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateSelect(SqlValidatorImpl.java:3652)
	at org.apache.calcite.sql.validate.SelectNamespace.validateImpl(SelectNamespace.java:64)
	at org.apache.calcite.sql.validate.AbstractNamespace.validate(AbstractNamespace.java:89)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateNamespace(SqlValidatorImpl.java:1100)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateQuery(SqlValidatorImpl.java:1071)
	at com.hazelcast.jet.sql.impl.validate.HazelcastSqlValidator.validateQuery(HazelcastSqlValidator.java:170)
	at org.apache.calcite.sql.SqlSelect.validate(SqlSelect.java:247)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateScopedExpression(SqlValidatorImpl.java:1046)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validate(SqlValidatorImpl.java:752)
	at com.hazelcast.jet.sql.impl.validate.HazelcastSqlValidator.validate(HazelcastSqlValidator.java:165)
	at com.hazelcast.jet.sql.impl.parse.QueryParser.parse0(QueryParser.java:80)
	at com.hazelcast.jet.sql.impl.parse.QueryParser.parse(QueryParser.java:56)
	... 22 more
```

**Comment by viliam-durina** [comment]
It is caused by this calcite issue: https://issues.apache.org/jira/browse/CALCITE-4923
