### ISSUE TITLE
Race condition with SQL JOIN, Hazelcast instance is not active!

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast#21339]
**Describe the bug**
I get the exception below if I call `shutdown()` immediately after sql execution.
```
Exception in ProcessorTasklet{07f1-c324-8080-0001/Join(Predicate-IMap[public.map])#1}
com.hazelcast.core.HazelcastInstanceNotActiveException: Hazelcast instance is not active!
	at com.hazelcast.spi.impl.operationservice.impl.InvocationRegistry.register(InvocationRegistry.java:140)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:570)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:541)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:241)
	at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.invokeOnPartition(OperationServiceImpl.java:330)
	at com.hazelcast.map.impl.query.QueryEngineImpl.dispatchPartitionScanQueryOnOwnerMemberOnPartitionThread(QueryEngineImpl.java:341)
	at com.hazelcast.map.impl.query.QueryEngineImpl.lambda$dispatchPartitionScanQueryOnOwnerMemberOnPartitionThread$1(QueryEngineImpl.java:333)
	at java.base/java.util.PrimitiveIterator$OfInt.forEachRemaining(PrimitiveIterator.java:116)
	at com.hazelcast.map.impl.query.QueryEngineImpl.dispatchPartitionScanQueryOnOwnerMemberOnPartitionThread(QueryEngineImpl.java:332)
	at com.hazelcast.map.impl.query.QueryEngineImpl.doRunOnPartitionThreads(QueryEngineImpl.java:198)
	at com.hazelcast.map.impl.query.QueryEngineImpl.runOnGivenPartitions(QueryEngineImpl.java:144)
	at com.hazelcast.map.impl.query.QueryEngineImpl.execute(QueryEngineImpl.java:119)
	at com.hazelcast.map.impl.proxy.MapProxySupport.executeQueryInternal(MapProxySupport.java:1416)
	at com.hazelcast.map.impl.proxy.MapProxySupport.executeQueryInternal(MapProxySupport.java:1384)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.executePredicate(MapProxyImpl.java:796)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.entrySet(MapProxyImpl.java:762)
	at com.hazelcast.jet.sql.impl.connector.map.JoinByEquiJoinProcessorSupplier.lambda$joinFn$3544ee34$1(JoinByEquiJoinProcessorSupplier.java:156)
	at com.hazelcast.function.FunctionEx.apply(FunctionEx.java:49)
	at com.hazelcast.jet.core.AbstractProcessor$FlatMapper.tryProcess(AbstractProcessor.java:566)
	at com.hazelcast.jet.impl.processor.TransformP.tryProcess(TransformP.java:45)
	at com.hazelcast.jet.core.AbstractProcessor.tryProcess0(AbstractProcessor.java:187)
	at com.hazelcast.jet.core.AbstractProcessor.process0(AbstractProcessor.java:590)
	at com.hazelcast.jet.core.AbstractProcessor.process(AbstractProcessor.java:108)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.lambda$processInbox$2f647568$2(ProcessorTasklet.java:440)
	at com.hazelcast.jet.function.RunnableEx.run(RunnableEx.java:31)
	at com.hazelcast.jet.impl.util.Util.doWithClassLoader(Util.java:525)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.processInbox(ProcessorTasklet.java:440)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:305)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:300)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:281)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:255)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$BlockingWorker.run(TaskletExecutionService.java:315)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
	at ------ submitted from ------.()
	at com.hazelcast.internal.util.ExceptionUtil.cloneExceptionWithFixedAsyncStackTrace(ExceptionUtil.java:336)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.returnOrThrowWithGetConventions(InvocationFuture.java:112)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:100)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:609)
	at com.hazelcast.map.impl.query.QueryEngineImpl.addResultsOfPredicate(QueryEngineImpl.java:214)
	at com.hazelcast.map.impl.query.QueryEngineImpl.doRunOnPartitionThreads(QueryEngineImpl.java:200)
	at com.hazelcast.map.impl.query.QueryEngineImpl.runOnGivenPartitions(QueryEngineImpl.java:144)
	at com.hazelcast.map.impl.query.QueryEngineImpl.execute(QueryEngineImpl.java:119)
	at com.hazelcast.map.impl.proxy.MapProxySupport.executeQueryInternal(MapProxySupport.java:1416)
	at com.hazelcast.map.impl.proxy.MapProxySupport.executeQueryInternal(MapProxySupport.java:1384)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.executePredicate(MapProxyImpl.java:796)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.entrySet(MapProxyImpl.java:762)
	at com.hazelcast.jet.sql.impl.connector.map.JoinByEquiJoinProcessorSupplier.lambda$joinFn$3544ee34$1(JoinByEquiJoinProcessorSupplier.java:156)
	at com.hazelcast.function.FunctionEx.apply(FunctionEx.java:49)
	at com.hazelcast.jet.core.AbstractProcessor$FlatMapper.tryProcess(AbstractProcessor.java:566)
	at com.hazelcast.jet.impl.processor.TransformP.tryProcess(TransformP.java:45)
	at com.hazelcast.jet.core.AbstractProcessor.tryProcess0(AbstractProcessor.java:187)
	at com.hazelcast.jet.core.AbstractProcessor.process0(AbstractProcessor.java:590)
	at com.hazelcast.jet.core.AbstractProcessor.process(AbstractProcessor.java:108)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.lambda$processInbox$2f647568$2(ProcessorTasklet.java:440)
	at com.hazelcast.jet.function.RunnableEx.run(RunnableEx.java:31)
	at com.hazelcast.jet.impl.util.Util.doWithClassLoader(Util.java:525)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.processInbox(ProcessorTasklet.java:440)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:305)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:300)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:281)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:255)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$BlockingWorker.run(TaskletExecutionService.java:315)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)```


**Expected behavior**
No exception.

**To Reproduce**
```
	public static void main(String[] args) throws Exception {
		String mapName = "map";

		Config config = new Config();
		config.getJetConfig().setEnabled(true);
		HazelcastInstance hazelcastInstance = Hazelcast.newHazelcastInstance(config);

		String mapping = "CREATE MAPPING " + mapName
				+ " TYPE IMap OPTIONS ( "
		        + " 'keyFormat' = 'java',"
		        + " 'keyJavaClass' = '" + Integer.class.getName() + "',"
		        + " 'valueFormat' = 'java',"
		        + " 'valueJavaClass' = '" + Integer.class.getName() + "'"
                + " )";
		hazelcastInstance.getSql().execute(mapping);

		IMap<Integer, Integer> map = hazelcastInstance.getMap(mapName);
		for (int i = 0; i < 100; i++) {
			map.set(i, i);
		}

		String sql = "SELECT * FROM " + mapName + " AS l, "+ mapName + " AS r"
				+ " WHERE CAST(l.this AS INTEGER) = CAST(r.this AS INTEGER)";
		hazelcastInstance.getSql().execute(sql).iterator();

		hazelcastInstance.shutdown();
	}
```

**Additional context**
Tested with `Hazelcast Platform 5.2-SNAPSHOT (20220428 - 3f239e3)`

**Comment by viliam-durina** [comment]
Just getting the iterator still leaves the server cursor open. When you then shut down the member, the query is still active, and the error is a normal and expected consequence.

If you iterated all the rows from the cursor, there won't be such error. If you closed the result, you still could get it, because the cancellation is async.
