### ISSUE TITLE
com.hazelcast.collection.impl.queue.QueueAdvancedTest.test_continues_ownership_changes_does_not_leak_backup_memory [HZ-1844]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#21345]
_5.1.z_ (commit ce56585fff5f4ae636ea91d2c9357836a3c0c39e)

Failed on IbmJDK8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-IbmJDK8/31/testReport/com.hazelcast.collection.impl.queue/QueueAdvancedTest/test_continues_ownership_changes_does_not_leak_backup_memory_comparatorClassName__com_hazelcast_collection_impl_queue_model_VersionedObjectComparator_/

Failed with variant: `[comparatorClassName: com.hazelcast.collection.impl.queue.model.VersionedObjectComparator]`

<details><summary>Stacktrace:</summary>

```
com.hazelcast.spi.exception.TargetNotMemberException: Not Member! target: [127.0.0.1]:5703 - 411b188c-e12e-40d4-a033-9e3253071ca5, partitionId: 4, operation: com.hazelcast.collection.impl.queue.operations.OfferOperation, service: hz:impl:queueService
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.initInvocationTarget(Invocation.java:291)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:563)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.access$400(Invocation.java:100)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation$InvocationRetryTask.run(Invocation.java:805)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:522)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:191)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:825)
	at ------ submitted from ------.()
	at com.hazelcast.internal.util.ExceptionUtil.cloneExceptionWithFixedAsyncStackTrace(ExceptionUtil.java:336)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.returnOrThrowWithGetConventions(InvocationFuture.java:112)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:100)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:617)
	at com.hazelcast.collection.impl.queue.QueueProxySupport.invokeAndGet(QueueProxySupport.java:179)
	at com.hazelcast.collection.impl.queue.QueueProxySupport.offerInternal(QueueProxySupport.java:100)
	at com.hazelcast.collection.impl.queue.QueueProxyImpl.offer(QueueProxyImpl.java:85)
	at com.hazelcast.collection.impl.queue.QueueProxyImpl.offer(QueueProxyImpl.java:65)
	at com.hazelcast.collection.impl.queue.QueueAdvancedTest.test_continues_ownership_changes_does_not_leak_backup_memory(QueueAdvancedTest.java:677)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.lang.Thread.run(Thread.java:825)
```

</details>

Standard output can be downloaded from https://console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-5.maintenance-IbmJDK8/31/

**Comment by olukas** [comment]
Failed on `5.1.z` on ZuluJDK11 in variant `[comparatorClassName: null]`: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-ZuluJDK11/52/testReport/com.hazelcast.collection.impl.queue/QueueAdvancedTest/test_continues_ownership_changes_does_not_leak_backup_memory_comparatorClassName__null_/

However stacktrace is different:
```
java.lang.AssertionError: Failed at step :0 (0 is first step) [itemAdded=true, QueueContainer{name='itemQueue, isPriorityQueue=false, idGenerator=2, itemQueue=0, backupMap=0, txMap=0, dataMap=0, minAge=269, maxAge=269, totalAge=269, totalAgedCount=1, isEvictionScheduled=false, lastIdLoaded=0}] expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at com.hazelcast.collection.impl.queue.QueueAdvancedTest.test_continues_ownership_changes_does_not_leak_backup_memory(QueueAdvancedTest.java:680)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by olukas** [comment]
Failed on `master` in variant `[comparatorClassName: com.hazelcast.collection.impl.queue.model.VersionedObjectComparator]` on IbmJDK8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-IbmJDK8/204/testReport/com.hazelcast.collection.impl.queue/QueueAdvancedTest/test_continues_ownership_changes_does_not_leak_backup_memory_comparatorClassName__com_hazelcast_collection_impl_queue_model_VersionedObjectComparator_/

However stacktrace is different:
```
com.hazelcast.spi.exception.TargetNotMemberException: Not Member! target: [127.0.0.1]:5703 - 2aea75ed-b6e2-4eb1-8a22-e44b98aa33f3, partitionId: 4, operation: com.hazelcast.collection.impl.queue.operations.OfferOperation, service: hz:impl:queueService
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.initInvocationTarget(Invocation.java:291)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:563)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.access$400(Invocation.java:100)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation$InvocationRetryTask.run(Invocation.java:806)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:522)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:191)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:825)
	at ------ submitted from ------.()
	at com.hazelcast.internal.util.ExceptionUtil.cloneExceptionWithFixedAsyncStackTrace(ExceptionUtil.java:348)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.returnOrThrowWithGetConventions(InvocationFuture.java:112)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:100)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:617)
	at com.hazelcast.collection.impl.queue.QueueProxySupport.invokeAndGet(QueueProxySupport.java:179)
	at com.hazelcast.collection.impl.queue.QueueProxySupport.offerInternal(QueueProxySupport.java:100)
	at com.hazelcast.collection.impl.queue.QueueProxyImpl.offer(QueueProxyImpl.java:85)
	at com.hazelcast.collection.impl.queue.QueueProxyImpl.offer(QueueProxyImpl.java:65)
	at com.hazelcast.collection.impl.queue.QueueAdvancedTest.test_continues_ownership_changes_does_not_leak_backup_memory(QueueAdvancedTest.java:677)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.lang.Thread.run(Thread.java:825)
```

**Comment by olukas** [comment]
Failed again on _master_ with IbmJDK8-fips: https://jenkins.hazelcast.com/job/Hazelcast-master-IbmJDK8-fips/30/testReport/com.hazelcast.collection.impl.queue/QueueAdvancedTest/test_continues_ownership_changes_does_not_leak_backup_memory_comparatorClassName__com_hazelcast_collection_impl_queue_model_VersionedObjectComparator_/

**Comment by Patras3** [comment]
Failed again on _master_ with IbmJDK8: https://jenkins.hazelcast.com/job/Hazelcast-master-IbmJDK8/211/testReport/junit/com.hazelcast.collection.impl.queue/QueueAdvancedTest/test_continues_ownership_changes_does_not_leak_backup_memory_comparatorClassName__com_hazelcast_collection_impl_queue_model_VersionedObjectComparator_/
