### ISSUE TITLE
Hazelcast encounter OutOfMemoryError

### ISSUE THREAD

**Issue by nianxiaoyi** [hazelcast/hazelcast#21359]
Hi, 
my online service is using hazelcast distributed cache. After it runs five days, it encounters OutofMemeryError when hazelcast clear expired operation. the detailed exception logs shows below. I am not completely sure whether it is related to hazelcast. But it seems other service not useing hazelcast run normally. How could I investigate the problem furthor?

 [hz.UserCenter.partition-operation.thread-3],com.hazelcast.map.impl.operation.ClearExpiredOperation - [TID:N/A] - [10.113.82.150]:13782 [dev] [3.6.5] GC overhead limit exceeded
java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.util.concurrent.ConcurrentHashMap$ValuesView.iterator(ConcurrentHashMap.java:4683)
        at com.hazelcast.map.impl.recordstore.AbstractEvictableRecordStore.initExpirationIterator(AbstractEvictableRecordStore.java:164)
        at com.hazelcast.map.impl.recordstore.AbstractEvictableRecordStore.evictExpiredEntriesInternal(AbstractEvictableRecordStore.java:147)
        at com.hazelcast.map.impl.recordstore.AbstractEvictableRecordStore.evictExpiredEntries(AbstractEvictableRecordStore.java:111)
        at com.hazelcast.map.impl.recordstore.DefaultRecordStore.evictExpiredEntries(DefaultRecordStore.java:66)
        at com.hazelcast.map.impl.operation.ClearExpiredOperation.run(ClearExpiredOperation.java:60)
        at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:172)
        at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.processOperation(OperationThread.java:198)
        at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.process(OperationThread.java:132)
        at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.doRun(OperationThread.java:124)
        at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.run(OperationThread.java:99)

After the exception occurs.  hazelcast instance become not active. the logs show below

2022-05-04 14:46:36.848 INFO  - [hz.UserCenter.partition-operation.thread-3],com.hazelcast.instance.Node - [TID:N/A] - [10.113.82.150]:13782 [dev] [3.6.5] Shutting down node engine...

2022-05-04 14:46:36.860 WARN  - [hz.UserCenter.generic-operation.thread-0],com.hazelcast.partition.impl.PartitionStateOperation
 - [TID:N/A] - [10.113.82.150]:13782 [dev] [3.6.5] com.hazelcast.spi.exception.RetryableHazelcastException: HazelcastInstance[A
ddress[10.113.82.150]:13782] is not active!

and then hazelcast didn't recovery by self

**Comment by frant-hartm** [comment]
It seems that the JVM doesn't have enough memory headroom leading to the `GC overhead limit exceeded`. You can try increasing the memory given to the JVM or turn on the JVM option `-XX:+HeapDumpOnOutOfMemoryError` and investigate the heap dump to see what takes up your memory.

From the logs, it seems that you are using version `3.6.5`. This is a really old version and is no longer supported. If you find out that the issue is indeed in Hazelcast please try to reproduce it on and newer version (at least 4.2.x or ideally latest 5.x) and reopen this with more info.
