### ISSUE TITLE
com.hazelcast.client.map.impl.querycache.ClientQueryCacheSimpleStressTest.testStress

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#21352]
_master_ (commit 74132cefd0c6f77e63d96c666fb5864481079815)

Failed on Sonar (Oracle JDK 11): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/1205/testReport/com.hazelcast.client.map.impl.querycache/ClientQueryCacheSimpleStressTest/testStress/

<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: expected:<10000> but was:<9019>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at com.hazelcast.client.map.impl.querycache.ClientQueryCacheSimpleStressTest$2.run(ClientQueryCacheSimpleStressTest.java:105)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1226)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1328)
	at com.hazelcast.client.map.impl.querycache.ClientQueryCacheSimpleStressTest.assertQueryCacheSizeEventually(ClientQueryCacheSimpleStressTest.java:109)
	at com.hazelcast.client.map.impl.querycache.ClientQueryCacheSimpleStressTest.testStress(ClientQueryCacheSimpleStressTest.java:98)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

</details>

Standard output can be downloaded from https://console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-sonar/1205/

**Comment by olukas** [comment]
Failed on `master` on Sonar build (Oracle JDK 11): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/1247/testReport/com.hazelcast.client.map.impl.querycache/ClientQueryCacheSimpleStressTest/testStress/

<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: expected:<10000> but was:<199>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at com.hazelcast.client.map.impl.querycache.ClientQueryCacheSimpleStressTest$2.run(ClientQueryCacheSimpleStressTest.java:105)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1226)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1328)
	at com.hazelcast.client.map.impl.querycache.ClientQueryCacheSimpleStressTest.assertQueryCacheSizeEventually(ClientQueryCacheSimpleStressTest.java:109)
	at com.hazelcast.client.map.impl.querycache.ClientQueryCacheSimpleStressTest.testStress(ClientQueryCacheSimpleStressTest.java:98)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

</details>

**Comment by orcunc** [comment]
The test is failing not because of the test but because of the environment. Some messages from the logs are
`New join request has been received from current master address. The UUID in the join request (2a8cf963-6d5e-4ce8-9871-215bac20e177) is different from the known master one (f9077622-fc6e-4116-80da-90ea20e73034). Suspecting the master address: [127.0.0.1]:5701`
But 5701 is already the master
Then
`Committing/rolling-back live transactions of [127.0.0.1]:5702, UUID: e8e06041-64af-4352-a9cf-d2fc5f15c8b2`
And then the events are lost
`Event lost detected for queryCache=`ec3b4022-bcad-4a34-b8df-c42ac0c1f7fc`: 
  partitionId=208, expectedSequence=33, foundSequence=1, cacheSize=8460`

There is nothing to be fixed in the test.
