### ISSUE TITLE
Cluster topology exception on 1-node cluster

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast#21360]
**Describe the bug**
Cluster topology exception on 1-node cluster. Topology didn't change.

```
Caused by: com.hazelcast.sql.impl.QueryException: Cluster topology changed while a query was executed: Member cannot be reached: [10.172.4.11]:5701
	at com.hazelcast.sql.impl.QueryException.error(QueryException.java:61) ~[hazelcast-5.2-SNAPSHOT.jar!/:5.2-SNAPSHOT]
	at com.hazelcast.sql.impl.QueryException.memberConnection(QueryException.java:81) ~[hazelcast-5.2-SNAPSHOT.jar!/:5.2-SNAPSHOT]
	at com.hazelcast.sql.impl.client.SqlClientService.rethrow(SqlClientService.java:266) ~[hazelcast-5.2-SNAPSHOT.jar!/:5.2-SNAPSHOT]
	... 19 more
```

**Expected behavior**
No exception

**To Reproduce**
Difficult, but it seems to be related to Kubernetes
If the client starts first and keeps retrying, eventually it finds the server
but then SQL fails with a topology change exception 

**Additional context**
Tested with Hazelcast Platform 5.2-SNAPSHOT (20220503 - bcf7074)
I have logs which I can send on, too big to attach

**Comment by neilstevenson** [comment]
I have not seen this recur, and no longer have the (huge) logs
