### ISSUE TITLE
com.hazelcast.internal.partition.MigrationCorrectnessTest.testPartitionData_whenBackupNodesStartedTerminated_withSafetyCheckAfterTerminate

### ISSUE THREAD

**Issue by bpoplawski** [hazelcast/hazelcast#21386]
_master_ (commit a455adc7f88b386d9f3769aae97a16a55f39e4b6 )

Failed on IBM JDK8: http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-IbmJDK8/lastCompletedBuild/testReport/com.hazelcast.internal.partition/MigrationCorrectnessTest/testPartitionData_whenBackupNodesStartedTerminated_withSafetyCheckAfterTerminate_backups_3_nodes_4_fragmented_false_/

<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: 
On Member [127.0.0.1]:5711 - 40e31ac0-d0ae-45a4-86e6-e0ee68a6a104 this, Partition 0 versions don't match: Partition {ID: 0, Version: 29} [
	0:[127.0.0.1]:5712 - 968acf50-374e-468e-b897-de58d7bf0466
	1:[127.0.0.1]:5710 - e7407afc-a99b-4025-98b2-3b80a827f374
	2:[127.0.0.1]:5713 - 8214fc82-73df-4079-baaf-c2e8a80e3e49
	3:[127.0.0.1]:5705 - f1574c2f-4a8d-4c37-bf94-e4c8c9c033eb
	4:[127.0.0.1]:5709 - e5acd04c-4291-4977-a56a-149143cf3c15
	5:[127.0.0.1]:5708 - d2a5bb26-64ec-4278-b1df-0a4129802742
	6:[127.0.0.1]:5711 - 40e31ac0-d0ae-45a4-86e6-e0ee68a6a104
] expected:<30> but was:<29>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at com.hazelcast.internal.partition.PartitionCorrectnessTestSupport.assertPartitionAssignments(PartitionCorrectnessTestSupport.java:199)
	at com.hazelcast.internal.partition.PartitionCorrectnessTestSupport.assertPartitionAssignments(PartitionCorrectnessTestSupport.java:173)
	at com.hazelcast.internal.partition.PartitionCorrectnessTestSupport.assertSizeAndData(PartitionCorrectnessTestSupport.java:231)
	at com.hazelcast.internal.partition.PartitionCorrectnessTestSupport.access$000(PartitionCorrectnessTestSupport.java:66)
	at com.hazelcast.internal.partition.PartitionCorrectnessTestSupport$AssertSizeAndDataTask.run(PartitionCorrectnessTestSupport.java:402)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1226)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1328)
	at com.hazelcast.internal.partition.PartitionCorrectnessTestSupport.assertSizeAndDataEventually(PartitionCorrectnessTestSupport.java:219)
	at com.hazelcast.internal.partition.PartitionCorrectnessTestSupport.assertSizeAndDataEventually(PartitionCorrectnessTestSupport.java:215)
	at com.hazelcast.internal.partition.AbstractMigrationCorrectnessTest.testPartitionData_whenBackupNodesStartedTerminated(AbstractMigrationCorrectnessTest.java:104)
	at com.hazelcast.internal.partition.AbstractMigrationCorrectnessTest.testPartitionData_whenBackupNodesStartedTerminated_withSafetyCheckAfterTerminate(AbstractMigrationCorrectnessTest.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.lang.Thread.run(Thread.java:825)
```

</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: testPartitionData_whenBackupNodesStartedTerminated[backups:3,nodes:4,fragmented:false] in 9.270 seconds.
23:03:17,644 DEBUG |testPartitionData_whenBackupNodesStartedTerminated_withSafetyCheckAfterTerminate[backups:3,nodes:4,fragmented:false]| - [ClusterService] hz.boring_yalow.priority-generic-operation.thread-0 - [127.0.0.1]:5708 [dev] [5.2-SNAPSHOT] Setting cluster time diff to -1ms.
23:03:17,644 DEBUG |testPartitionData_whenBackupNodesStartedTerminated_withSafetyCheckAfterTerminate[backups:3,nodes:4,fragmented:false]| - [ClusterService] hz.elated_yalow.generic-operation.thread-1 - [127.0.0.1]:5711 [dev] [5.2-SNAPSHOT] Setting cluster time diff to -1ms.
23:03:17,644 DEBUG |testPartitionData_whenBackupNodesStartedTerminated_withSafetyCheckAfterTerminate[backups:3,nodes:4,fragmented:false]| - [ClusterService] hz.eager_yalow.priority-generic-operation.thread-0 - [127.0.0.1]:5712 [dev] [5.2-SNAPSHOT] Setting cluster time diff to -1ms.
23:03:22,643  INFO |testPartitionData_whenBackupNodesStartedTerminated_withSafetyCheckAfterTerminate[backups:3,nodes:4,fragmented:false]| - [InternalPartitionService] hz.fervent_yalow.cached.thread-8 - [127.0.0.1]:5705 [dev] [5.2-SNAPSHOT] Remaining migration tasks: 2. (repartitionTime=Fri May 06 23:03:10 UTC 2022, plannedMigrations=450, completedMigrations=450, remainingMigrations=0, totalCompletedMigrations=1597, elapsedMigrationOperationTime=564ms, totalElapsedMigrationOperationTime=1312ms, elapsedDestinationCommitTime=385ms, totalElapsedDestinationCommitTime=746ms, elapsedMigrationTime=1452ms, totalElapsedMigrationTime=3403ms)
23:03:22,644 DEBUG |testPartitionData_whenBackupNodesStartedTerminated_withSafetyCheckAfterTerminate[backups:3,nodes:4,fragmented:false]| - [ClusterService] hz.boring_yalow.priority-generic-operation.thread-0 - [127.0.0.1]:5708 [dev] [5.2-SNAPSHOT] Setting cluster time diff to -1ms.
23:03:22,644 DEBUG |testPartitionData_whenBackupNodesStartedTerminated_withSafetyCheckAfterTerminate[backups:3,nodes:4,fragmented:false]| - [ClusterService] hz.elated_yalow.generic-operation.thread-0 - [127.0.0.1]:5711 [dev] [5.2-SNAPSHOT] Setting cluster time diff to -1ms.
23:03:22,644 DEBUG |testPartitionData_whenBackupNodesStartedTerminated_withSafetyCheckAfterTerminate[backups:3,nodes:4,fragmented:false]| - [ClusterService] hz.eager_yalow.priority-generic-operation.thread-0 - [127.0.0.1]:5712 [dev] [5.2-SNAPSHOT] Setting cluster time diff to -1ms.
23:03:27,644 DEBUG |testPartitionData_whenBackupNodesStartedTerminated_withSafetyCheckAfterTerminate[backups:3,nodes:4,fragmented:false]| - [ClusterService] hz.eager_yalow.priority-generic-operation.thread-0 - [127.0.0.1]:5712 [dev] [5.2-SNAPSHOT] Setting cluster time diff to -1ms.
23:03:27,644 DEBUG |testPartitionData_whenBackupNodesStartedTerminated_withSafetyCheckAfterTerminate[backups:3,nodes:4,fragmented:false]| - [ClusterService] hz.elated_yalow.generic-operation.thread-1 - [127.0.0.1]:5711 [dev] [5.2-SNAPSHOT] Setting cluster time diff to -1ms.
23:03:27,644 DEBUG |testPartitionData_whenBackupNodesStartedTerminated_withSafetyCheckAfterTerminate[backups:3,nodes:4,fragmented:false]| - [ClusterService] hz.boring_yalow.priority-generic-operation.thread-0 - [127.0.0.1]:5708 [dev] [5.2-SNAPSHOT] Setting cluster time diff to -1ms.
23:03:32,644 DEBUG |testPartitionData_whenBackupNodesStartedTerminated_withSafetyCheckAfterTerminate[backups:3,nodes:4,fragmented:false]| - [ClusterService] hz.eager_yalow.priority-generic-operation.thread-0 - [127.0.0.1]:5712 [dev] [5.2-SNAPSHOT] Setting cluster time diff to -1ms.
23:03:32,644 DEBUG |testPartitionData_whenBackupNodesStartedTerminated_withSafetyCheckAfterTerminate[backups:3,nodes:4,fragmented:false]| - [ClusterService] hz.boring_yalow.priority-generic-operation.thread-0 - [127.0.0.1]:5708 [dev] [5.2-SNAPSHOT] Setting cluster time diff to -1ms.
23:03:32,644 DEBUG |testPartitionData_whenBackupNodesStartedTerminated_withSafetyCheckAfterTerminate[backups:3,nodes:4,fragmented:false]| - [ClusterService] hz.elated_yalow.priority-generic-operation.thread-0 - [127.0.0.1]:5711 [dev] [5.2-SNAPSHOT] Setting cluster time diff to -1ms.
23:03:37,643  INFO |testPartitionData_whenBackupNodesStartedTerminated_withSafetyCheckAfterTerminate[backups:3,nodes:4,fragmented:false]| - [InternalPartitionService] hz.fervent_yalow.cached.thread-5 - [127.0.0.1]:5705 [dev] [5.2-SNAPSHOT] Remaining migration tasks: 2. (repartitionTime=Fri May 06 23:03:10 UTC 2022, plannedMigrations=450, completedMigrations=450, remainingMigrations=0, totalCompletedMigrations=1597, elapsedMigrationOperationTime=564ms, totalElapsedMigrationOperationTime=1312ms, elapsedDestinationCommitTime=385ms, totalElapsedDestinationCommitTime=746ms, elapsedMigrationTime=1452ms, totalElapsedMigrationTime=3403ms)
23:03:37,649 DEBUG |testPartitionData_whenBackupNodesStartedTerminated_withSafetyCheckAfterTerminate[backups:3,nodes:4,fragmented:false]| - [ClusterService] hz.eager_yalow.priority-generic-operation.thread-0 - [127.0.0.1]:5712 [dev] [5.2-SNAPSHOT] Setting cluster time diff to -2ms.
23:03:37,649 DEBUG |testPartitionData_whenBackupNodesStartedTerminated_withSafetyCheckAfterTerminate[backups:3,nodes:4,fragmented:false]| - [ClusterService] hz.elated_yalow.generic-operation.thread-1 - [127.0.0.1]:5711 [dev] [5.2-SNAPSHOT] Setting cluster time diff to -2ms.
23:03:37,649 DEBUG |testPartitionData_whenBackupNodesStartedTerminated_withSafetyCheckAfterTerminate[backups:3,nodes:4,fragmented:false]| - [ClusterService] hz.boring_yalow.generic-operation.thread-0 - [127.0.0.1]:5708 [dev] [5.2-SNAPSHOT] Setting cluster time diff to -2ms.
23:03:42,644 DEBUG |testPartitionData_whenBackupNodesStartedTerminated_withSafetyCheckAfterTerminate[backups:3,nodes:4,fragmented:false]| - [ClusterService] hz.elated_yalow.generic-operation.thread-0 - [127.0.0.1]:5711 [dev] [5.2-SNAPSHOT] Setting cluster time diff to -1ms.
23:03:42,644 DEBUG |testPartitionData_whenBackupNodesStartedTerminated_withSafetyCheckAfterTerminate[backups:3,nodes:4,fragmented:false]| - [ClusterService] hz.eager_yalow.priority-generic-operation.thread-0 - [127.0.0.1]:5712 [dev] [5.2-SNAPSHOT] Setting cluster time diff to -1ms.
23:03:42,644 DEBUG |testPartitionData_whenBackupNodesStartedTerminated_withSafetyCheckAfterTerminate[backups:3,nodes:4,fragmented:false]| - [ClusterService] hz.boring_yalow.priority-generic-operation.thread-0 - [127.0.0.1]:5708 [dev] [5.2-SNAPSHOT] Setting cluster time diff to -1ms.
23:03:47,644 DEBUG |testPartitionData_whenBackupNodesStartedTerminated_withSafetyCheckAfterTerminate[backups:3,nodes:4,fragmented:false]| - [ClusterService] hz.eager_yalow.generic-operation.thread-1 - [127.0.0.1]:5712 [dev] [5.2-SNAPSHOT] Setting cluster time diff to -1ms.
23:03:47,644 DEBUG |testPartitionData_whenBackupNodesStartedTerminated_withSafetyCheckAfterTerminate[backups:3,nodes:4,fragmented:false]| - [ClusterService] hz.boring_yalow.priority-generic-operation.thread-0 - [127.0.0.1]:5708 [dev] [5.2-SNAPSHOT] Setting cluster time diff to -1ms.
23:03:47,644 DEBUG |testPartitionData_whenBackupNodesStartedTerminated_withSafetyCheckAfterTerminate[backups:3,nodes:4,fragmented:false]| - [ClusterService] hz.elated_yalow.generic-operation.thread-1 - [127.0.0.1]:5711 [dev] [5.2-SNAPSHOT] Setting cluster time diff to -1ms.
23:03:47,802  INFO |testPartitionData_whenBackupNodesStartedTerminated_withSafetyCheckAfterTerminate[backups:3,nodes:4,fragmented:false]| - [HealthMonitor] hz.fervent_yalow.HealthMonitor - [127.0.0.1]:5705 [dev] [5.2-SNAPSHOT] processors=8, physical.memory.total=377.6G, physical.memory.free=91.0G, swap.space.total=4.0G, swap.space.free=4.0G, heap.memory.used=1.0G, heap.memory.free=3.0G, heap.memory.total=4.0G, heap.memory.max=4.0G, heap.memory.used/total=25.49%, heap.memory.used/max=25.49%, minor.gc.count=417, minor.gc.time=12063ms, major.gc.count=2, major.gc.time=809ms, load.process=0.09%, load.system=72.09%, load.systemAverage=9.54, thread.count=242, thread.peakCount=1896, cluster.timeDiff=-1, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=3620, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=0, clientEndpoint.count=0, connection.active.count=0, client.connection.count=0, connection.count=0
23:03:49,034  INFO |testPartitionData_whenBackupNodesStartedTerminated_withSafetyCheckAfterTerminate[backups:3,nodes:4,fragmented:false]| - [HealthMonitor] hz.boring_yalow.HealthMonitor - [127.0.0.1]:5708 [dev] [5.2-SNAPSHOT] processors=8, physical.memory.total=377.6G, physical.memory.free=90.8G, swap.space.total=4.0G, swap.space.free=4.0G, heap.memory.used=1.0G, heap.memory.free=3.0G, heap.memory.total=4.0G, heap.memory.max=4.0G, heap.memory.used/total=25.77%, heap.memory.used/max=25.77%, minor.gc.count=417, minor.gc.time=12063ms, major.gc.count=2, major.gc.time=809ms, load.process=0.20%, load.system=74.64%, load.systemAverage=9.54, thread.count=242, thread.peakCount=1896, cluster.timeDiff=-1, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=3318, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=0, clientEndpoint.count=0, connection.active.count=0, client.connection.count=0, connection.count=0
23:03:52,643  INFO |testPartitionData_whenBackupNodesStartedTerminated_withSafetyCheckAfterTerminate[backups:3,nodes:4,fragmented:false]| - [InternalPartitionService] hz.fervent_yalow.cached.thread-12 - [127.0.0.1]:5705 [dev] [5.2-SNAPSHOT] Remaining migration tasks: 2. (repartitionTime=Fri May 06 23:03:10 UTC 2022, plannedMigrations=450, completedMigrations=450, remainingMigrations=0, totalCompletedMigrations=1597, elapsedMigrationOperationTime=564ms, totalElapsedMigrationOperationTime=1312ms, elapsedDestinationCommitTime=385ms, totalElapsedDestinationCommitTime=746ms, elapsedMigrationTime=1452ms, totalElapsedMigrationTime=3403ms)
23:03:52,644 DEBUG |testPartitionData_whenBackupNodesStartedTerminated_withSafetyCheckAfterTerminate[backups:3,nodes:4,fragmented:false]| - [ClusterService] hz.eager_yalow.priority-generic-operation.thread-0 - [127.0.0.1]:5712 [dev] [5.2-SNAPSHOT] Setting cluster time diff to -1ms.
23:03:52,644 DEBUG |testPartitionData_whenBackupNodesStartedTerminated_withSafetyCheckAfterTerminate[backups:3,nodes:4,fragmented:false]| - [ClusterService] hz.boring_yalow.priority-generic-operation.thread-0 - [127.0.0.1]:5708 [dev] [5.2-SNAPSHOT] Setting cluster time diff to -1ms.
23:03:52,644 DEBUG |testPartitionData_whenBackupNodesStartedTerminated_withSafetyCheckAfterTerminate[backups:3,nodes:4,fragmented:false]| - [ClusterService] hz.elated_yalow.priority-generic-operation.thread-0 - [127.0.0.1]:5711 [dev] [5.2-SNAPSHOT] Setting cluster time diff to -1ms.
23:03:57,644 DEBUG |testPartitionData_whenBackupNodesStartedTerminated_withSafetyCheckAfterTerminate[backups:3,nodes:4,fragmented:false]| - [ClusterService] hz.elated_yalow.priority-generic-operation.thread-0 - [127.0.0.1]:5711 [dev] [5.2-SNAPSHOT] Setting cluster time diff to -1ms.
23:03:57,644 DEBUG |testPartitionData_whenBackupNodesStartedTerminated_withSafetyCheckAfterTerminate[backups:3,nodes:4,fragmented:false]| - [ClusterService] hz.boring_yalow.priority-generic-operation.thread-0 - [127.0.0.1]:5708 [dev] [5.2-SNAPSHOT] Setting cluster time diff to -1ms.
23:03:57,644 DEBUG |testPartitionData_whenBackupNodesStartedTerminated_withSafetyCheckAfterTerminate[backups:3,nodes:4,fragmented:false]| - [ClusterService] hz.eager_yalow.priority-generic-operation.thread-0 - [127.0.0.1]:5712 [dev] [5.2-SNAPSHOT] Setting cluster time diff to -1ms.
23:04:02,644 DEBUG |testPartitionData_whenBackupNodesStartedTerminated_withSafetyCheckAfterTerminate[backups:3,nodes:4,fragmented:false]| - [ClusterService] hz.boring_yalow.priority-generic-operation.thread-0 - [127.0.0.1]:5708 [dev] [5.2-SNAPSHOT] Setting cluster time diff to -1ms.
23:04:02,644 DEBUG |testPartitionData_whenBackupNodesStartedTerminated_withSafetyCheckAfterTerminate[backups:3,nodes:4,fragmented:false]| - [ClusterService] hz.eager_yalow.priority-generic-operation.thread-0 - [127.0.0.1]:5712 [dev] [5.2-SNAPSHOT] Setting cluster time diff to -1ms.
23:04:02,644 DEBUG |testPartitionData_whenBackupNodesStartedTerminated_withSafetyCheckAfterTerminate[backups:3,nodes:4,fragmented:false]| - [ClusterService] hz.elated_yalow.priority-generic-operation.thread-0 - [127.0.0.1]:5711 [dev] [5.2-SNAPSHOT] Setting cluster time diff to -1ms.
23:04:07,643  INFO |testPartitionData_whenBackupNodesStartedTerminated_withSafetyCheckAfterTerminate[backups:3,nodes:4,fragmented:false]| - [InternalPartitionService] hz.fervent_yalow.cached.thread-4 - [127.0.0.1]:5705 [dev] [5.2-SNAPSHOT] Remaining migration tasks: 2. (repartitionTime=Fri May 06 23:03:10 UTC 2022, plannedMigrations=450, completedMigrations=450, remainingMigrations=0, totalCompletedMigrations=1597, elapsedMigrationOperationTime=564ms, totalElapsedMigrationOperationTime=1312ms, elapsedDestinationCommitTime=385ms, totalElapsedDestinationCommitTime=746ms, elapsedMigrationTime=1452ms, totalElapsedMigrationTime=3403ms)
23:04:07,644 DEBUG |testPartitionData_whenBackupNodesStartedTerminated_withSafetyCheckAfterTerminate[backups:3,nodes:4,fragmented:false]| - [MembershipManager] hz.fervent_yalow.cached.thread-11 - [127.0.0.1]:5705 [dev] [5.2-SNAPSHOT] Sending member list to the non-master nodes: 

Members {size:4, ver:21} [
	Member [127.0.0.1]:5705 - f1574c2f-4a8d-4c37-bf94-e4c8c9c033eb this
	Member [127.0.0.1]:5708 - d2a5bb26-64ec-4278-b1df-0a4129802742
	Member [127.0.0.1]:5712 - 968acf50-374e-468e-b897-de58d7bf0466
	Member [127.0.0.1]:5711 - 40e31ac0-d0ae-45a4-86e6-e0ee68a6a104
]

```

</details>

**Comment by olukas** [comment]
Failed on `5.1.z` branch on ZuluJDK8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-ZuluJDK8/47/testReport/com.hazelcast.internal.partition/MigrationCorrectnessTest/testPartitionData_whenBackupNodesStartedTerminated_withSafetyCheckAfterTerminate_backups_3_nodes_4_fragmented_false_/

**Comment by olukas** [comment]
Failed again on: _master_ (commit f9582ab312d18ab4f689b6ad329d5c3d32a044b0)
with openj9-17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Openj9-17/55/testReport/com.hazelcast.internal.partition/MigrationCorrectnessTest/testPartitionData_whenBackupNodesStartedTerminated_withSafetyCheckAfterTerminate_backups_3_nodes_4_fragmented_false_/

However stacktrace is different.

<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: 
Partition: 6 is leaking on [127.0.0.1]:5711 - dcf9ad01-10fc-4cd7-b87f-2ca5955dad3b
Expected: (a value equal to or greater than <0> and a value less than or equal to <3>)
     but: a value less than or equal to <3> <4> was greater than <3>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:964)
	at com.hazelcast.internal.partition.PartitionCorrectnessTestSupport.assertNoLeakingData(PartitionCorrectnessTestSupport.java:283)
	at com.hazelcast.internal.partition.PartitionCorrectnessTestSupport.assertSizeAndData(PartitionCorrectnessTestSupport.java:251)
	at com.hazelcast.internal.partition.PartitionCorrectnessTestSupport.access$000(PartitionCorrectnessTestSupport.java:66)
	at com.hazelcast.internal.partition.PartitionCorrectnessTestSupport$AssertSizeAndDataTask.run(PartitionCorrectnessTestSupport.java:402)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1278)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1382)
	at com.hazelcast.internal.partition.PartitionCorrectnessTestSupport.assertSizeAndDataEventually(PartitionCorrectnessTestSupport.java:219)
	at com.hazelcast.internal.partition.PartitionCorrectnessTestSupport.assertSizeAndDataEventually(PartitionCorrectnessTestSupport.java:215)
	at com.hazelcast.internal.partition.AbstractMigrationCorrectnessTest.testPartitionData_whenBackupNodesStartedTerminated(AbstractMigrationCorrectnessTest.java:104)
	at com.hazelcast.internal.partition.AbstractMigrationCorrectnessTest.testPartitionData_whenBackupNodesStartedTerminated_withSafetyCheckAfterTerminate(AbstractMigrationCorrectnessTest.java:82)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:858)

```
</details>



Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-Openj9-17/55/

**Comment by olukas** [comment]
Failed again on _5.3.z_ with oracle-8 (force-offload): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-force-offload/27/testReport/com.hazelcast.internal.partition/MigrationCorrectnessTest/testPartitionData_whenBackupNodesStartedTerminated_withSafetyCheckAfterTerminate_backups_3_nodes_4_fragmented_true_/

**Comment by olukas** [comment]
Failed again on _5.3.z_ with openjdk-8: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-ZuluJDK8/104/testReport/com.hazelcast.internal.partition/MigrationCorrectnessTest/testPartitionData_whenBackupNodesStartedTerminated_withSafetyCheckAfterTerminate_backups_3_nodes_4_fragmented_false_/

**Comment by sumnerib** [comment]
Failed again on _5.3.z_ with openjdk-8: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-ZuluJDK8/105/testReport/com.hazelcast.internal.partition/MigrationCorrectnessTest/testPartitionData_whenBackupNodesStartedTerminated_withSafetyCheckAfterTerminate_backups_3_nodes_4_fragmented_false_/

**Comment by olukas** [comment]
Failed again on _master_ with openj9-11: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Openj9-11/159/testReport/com.hazelcast.internal.partition/MigrationCorrectnessTest/testPartitionData_whenBackupNodesStartedTerminated_withSafetyCheckAfterTerminate_2/

**Comment by Patras3** [comment]
Failed again on _5.4.z_ with oracle-17: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-sonar/477/testReport/junit/com.hazelcast.internal.partition/MigrationCorrectnessTest/____8/

**Comment by olukas** [comment]
Closing the test failure - it doesn't seem to be related to `master` or the latest maintenance stream `5.5.z` and it hasn't fail in the last 3 months. Feel free to reopen test failure if it occurs on `master` or on the latest maintenance stream.
