### ISSUE TITLE
com.hazelcast.test.starter.test.HazelcastProxyFactoryTest.testProxyHazelcastInstanceClasses_ofSameVersion_areSame [HZ-1802]

### ISSUE THREAD

**Issue by bpoplawski** [hazelcast/hazelcast#21401]
master (commit adccb4a3e241df205d0cbda53a438ef8d81936bf )

Failed on sonar : http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/1213/consoleFull

<details><summary>Stacktrace:</summary>

```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.base@11.0.13/java.net.SocketInputStream.socketRead0(Native Method)
	at java.base@11.0.13/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
	at java.base@11.0.13/java.net.SocketInputStream.read(SocketInputStream.java:168)
	at java.base@11.0.13/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at java.base@11.0.13/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:478)
	at java.base@11.0.13/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472)
	at java.base@11.0.13/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:70)
	at java.base@11.0.13/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1318)
	at java.base@11.0.13/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:959)
	at java.base@11.0.13/java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
	at java.base@11.0.13/java.io.BufferedInputStream.read1(BufferedInputStream.java:292)
	at java.base@11.0.13/java.io.BufferedInputStream.read(BufferedInputStream.java:351)
	at java.base@11.0.13/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:746)
	at java.base@11.0.13/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:689)
	at java.base@11.0.13/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1615)
	at java.base@11.0.13/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base@11.0.13/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
	at java.base@11.0.13/java.net.URL.openStream(URL.java:1165)
	at app//com.hazelcast.test.starter.HazelcastVersionLocator.downloadFile(HazelcastVersionLocator.java:119)
	at app//com.hazelcast.test.starter.HazelcastVersionLocator.downloadMainArtifact(HazelcastVersionLocator.java:96)
	at app//com.hazelcast.test.starter.HazelcastVersionLocator.locateMainArtifact(HazelcastVersionLocator.java:78)
	at app//com.hazelcast.test.starter.HazelcastVersionLocator.locateVersion(HazelcastVersionLocator.java:63)
	at app//com.hazelcast.test.starter.HazelcastStarter$HazelcastVersionClassloaderFuture.get(HazelcastStarter.java:400)
	at app//com.hazelcast.test.starter.HazelcastStarter.getTargetVersionClassloader(HazelcastStarter.java:264)
	at app//com.hazelcast.test.starter.HazelcastStarter.newHazelcastInstance(HazelcastStarter.java:122)
	at app//com.hazelcast.test.starter.HazelcastStarter.newHazelcastInstance(HazelcastStarter.java:103)
	at app//com.hazelcast.test.starter.HazelcastStarter.newHazelcastInstance(HazelcastStarter.java:72)
	at app//com.hazelcast.test.starter.test.HazelcastProxyFactoryTest.testProxyHazelcastInstanceClasses_ofSameVersion_areSame(HazelcastProxyFactoryTest.java:67)
	at java.base@11.0.13/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@11.0.13/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base@11.0.13/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@11.0.13/java.lang.reflect.Method.invoke(Method.java:566)
	at app//org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at app//org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at app//org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at app//org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at app//com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at app//com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base@11.0.13/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base@11.0.13/java.lang.Thread.run(Thread.java:834)
```

</details>

<details><summary>Standard output:</summary>

```
THREAD DUMP FOR TEST FAILURE: "test timed out after 300000 milliseconds" at "testProxyHazelcastInstanceClasses_ofSameVersion_areSame"

"Reference Handler" 
	java.lang.Thread.State: RUNNABLE, cpu=1500149283 nsecs, usr=1350000000 nsecs, blocked=141 msecs, waited=0 msecs
		at java.base@11.0.13/java.lang.ref.Reference.waitForReferencePendingList(Native Method)
		at java.base@11.0.13/java.lang.ref.Reference.processPendingReferences(Reference.java:241)
		at java.base@11.0.13/java.lang.ref.Reference$ReferenceHandler.run(Reference.java:213)

"Finalizer" 
	java.lang.Thread.State: WAITING, on lock=java.lang.ref.ReferenceQueue$Lock@4dd38825, cpu=81815438 nsecs, usr=50000000 nsecs, blocked=23 msecs, waited=10180926 msecs
		at java.base@11.0.13/java.lang.Object.wait(Native Method)
		at java.base@11.0.13/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155)
		at java.base@11.0.13/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:176)
		at java.base@11.0.13/java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:170)

"Signal Dispatcher" 
	java.lang.Thread.State: RUNNABLE, cpu=78488 nsecs, usr=0 nsecs, blocked=0 msecs, waited=0 msecs

"Common-Cleaner" 
	java.lang.Thread.State: TIMED_WAITING, on lock=java.lang.ref.ReferenceQueue$Lock@6717f35f, cpu=381347929 nsecs, usr=240000000 nsecs, blocked=35 msecs, waited=10180610 msecs
		at java.base@11.0.13/java.lang.Object.wait(Native Method)
		at java.base@11.0.13/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155)
		at java.base@11.0.13/jdk.internal.ref.CleanerImpl.run(CleanerImpl.java:148)
		at java.base@11.0.13/java.lang.Thread.run(Thread.java:834)
		at java.base@11.0.13/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:134)

"surefire-forkedjvm-ping-30s" 
	java.lang.Thread.State: TIMED_WAITING, on lock=java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@7fa5271d, cpu=5525926754 nsecs, usr=3030000000 nsecs, blocked=1311 msecs, waited=10089535 msecs
		at java.base@11.0.13/jdk.internal.misc.Unsafe.park(Native Method)
		at java.base@11.0.13/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
		at java.base@11.0.13/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2123)
		at java.base@11.0.13/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1182)
		at java.base@11.0.13/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899)
		at java.base@11.0.13/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1054)
		at java.base@11.0.13/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114)
		at java.base@11.0.13/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
		at java.base@11.0.13/java.lang.Thread.run(Thread.java:834)

"process reaper" 
	java.lang.Thread.State: TIMED_WAITING, on lock=java.util.concurrent.SynchronousQueue$TransferStack@b443458, cpu=6231137089 nsecs, usr=480000000 nsecs, blocked=1187 msecs, waited=10119757 msecs
		at java.base@11.0.13/jdk.internal.misc.Unsafe.park(Native Method)
		at java.base@11.0.13/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
		at java.base@11.0.13/java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:462)
		at java.base@11.0.13/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:361)
		at java.base@11.0.13/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:937)
		at java.base@11.0.13/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1053)
		at java.base@11.0.13/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114)
		at java.base@11.0.13/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
		at java.base@11.0.13/java.lang.Thread.run(Thread.java:834)

"JitterThread" 
	java.lang.Thread.State: TIMED_WAITING, cpu=20105385302 nsecs, usr=11350000000 nsecs, blocked=0 msecs, waited=10165552 msecs
		at java.base@11.0.13/jdk.internal.misc.Unsafe.park(Native Method)
		at java.base@11.0.13/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:357)
		at app//com.hazelcast.test.jitter.JitterThread.sleepNanos(JitterThread.java:56)
		at app//com.hazelcast.test.jitter.JitterThread.run(JitterThread.java:41)

"ForkJoinPool.commonPool-worker-3" 
	java.lang.Thread.State: WAITING, on lock=java.util.concurrent.ForkJoinPool@5311a364, cpu=9718812728 nsecs, usr=9590000000 nsecs, blocked=0 msecs, waited=10138309 msecs
		at java.base@11.0.13/jdk.internal.misc.Unsafe.park(Native Method)
		at java.base@11.0.13/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
		at java.base@11.0.13/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1628)
		at java.base@11.0.13/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

"ForkJoinPool.commonPool-worker-9" 
	java.lang.Thread.State: WAITING, on lock=java.util.concurrent.ForkJoinPool@5311a364, cpu=2776201732 nsecs, usr=2680000000 nsecs, blocked=2 msecs, waited=10111158 msecs
		at java.base@11.0.13/jdk.internal.misc.Unsafe.park(Native Method)
		at java.base@11.0.13/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
		at java.base@11.0.13/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1628)
		at java.base@11.0.13/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

"ForkJoinPool.commonPool-worker-11" 
	java.lang.Thread.State: WAITING, on lock=java.util.concurrent.ForkJoinPool@5311a364, cpu=3919856747 nsecs, usr=3820000000 nsecs, blocked=0 msecs, waited=9869087 msecs
		at java.base@11.0.13/jdk.internal.misc.Unsafe.park(Native Method)
		at java.base@11.0.13/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
		at java.base@11.0.13/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1628)
		at java.base@11.0.13/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

"ForkJoinPool.commonPool-worker-15" 
	java.lang.Thread.State: WAITING, on lock=java.util.concurrent.ForkJoinPool@5311a364, cpu=2946535216 nsecs, usr=2800000000 nsecs, blocked=84 msecs, waited=9592111 msecs
		at java.base@11.0.13/jdk.internal.misc.Unsafe.park(Native Method)
		at java.base@11.0.13/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
		at java.base@11.0.13/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1628)
		at java.base@11.0.13/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

"hz.serene_booth.async.thread-4" 
	java.lang.Thread.State: WAITING, on lock=java.util.concurrent.CompletableFuture$Signaller@7584665d, cpu=510708 nsecs, usr=0 nsecs, blocked=0 msecs, waited=9374257 msecs
		at java.base@11.0.13/jdk.internal.misc.Unsafe.park(Native Method)
```

</details>

**Comment by olukas** [comment]
Failed on `master` on Sonar build (Oracle JDK 11): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/1250/testReport/com.hazelcast.test.starter.test/HazelcastProxyFactoryTest/testProxyHazelcastInstanceClasses_ofSameVersion_areSame/
