### ISSUE TITLE
IMap.get gets blocked forever when Cassandra NoNodeAvailableException is thrown from the MapStore [API-1387]

### ISSUE THREAD

**Issue by szokebarnabas** [hazelcast/hazelcast#21414]
**Describe the bug**
The IMap.get() call will be blocked forever  when a `com.datastax.oss.driver.api.core.NoNodeAvailableException` is thrown from the MapStore.

**Setup:**
Hazelcast v5.1.1
Cassandra SDK v4.14.1
Client-server setup
Read through cache, Cassandra DB gets called on a cache miss.
 
**Test scenario: Read through cache, Cassandra server is down:**

We tested the scenario when the Cassandra datastore is down and the client tries to load an entry from the cache and there's a cache miss. It turned out that Hazelcast incorrectly handles the exception from Cassandra as it assumes that there will be always a cause property from the exception that comes from the data store in case of an issue. When the Cassandra cluster is down Hazelcast receives a `com.datastax.oss.driver.api.core.NoNodeAvailableException`, it tries to clone this exception and call the initCause on a Throwable that throws an exception as the cause cannot be null.

Exception thrown:

```
java.lang.RuntimeException: Exception creation failed 
	at com.hazelcast.internal.util.ExceptionUtil.cloneException(ExceptionUtil.java:250) ~[hazelcast-5.1.1.jar:5.1.1]
	at com.hazelcast.internal.util.ExceptionUtil.tryCreateExceptionWithMessageAndCause(ExceptionUtil.java:225) ~[hazelcast-5.1.1.jar:5.1.1]
	at com.hazelcast.client.impl.protocol.ClientExceptionFactory.createException(ClientExceptionFactory.java:345) ~[hazelcast-5.1.1.jar:5.1.1]
	at com.hazelcast.client.impl.protocol.ClientExceptionFactory.createException(ClientExceptionFactory.java:330) ~[hazelcast-5.1.1.jar:5.1.1]
	at com.hazelcast.client.impl.spi.impl.ClientResponseHandlerSupplier.handleResponse(ClientResponseHandlerSupplier.java:164) ~[hazelcast-5.1.1.jar:5.1.1]
	at com.hazelcast.client.impl.spi.impl.ClientResponseHandlerSupplier.process(ClientResponseHandlerSupplier.java:141) ~[hazelcast-5.1.1.jar:5.1.1]
	at com.hazelcast.client.impl.spi.impl.ClientResponseHandlerSupplier.access$300(ClientResponseHandlerSupplier.java:60) ~[hazelcast-5.1.1.jar:5.1.1]
	at com.hazelcast.client.impl.spi.impl.ClientResponseHandlerSupplier$DynamicResponseHandler.accept(ClientResponseHandlerSupplier.java:251) ~[hazelcast-5.1.1.jar:5.1.1]
	at com.hazelcast.client.impl.spi.impl.ClientResponseHandlerSupplier$DynamicResponseHandler.accept(ClientResponseHandlerSupplier.java:243) ~[hazelcast-5.1.1.jar:5.1.1]
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnection.handleClientMessage(TcpClientConnection.java:245) ~[hazelcast-5.1.1.jar:5.1.1]
	at com.hazelcast.client.impl.protocol.util.ClientMessageDecoder.handleMessage(ClientMessageDecoder.java:135) ~[hazelcast-5.1.1.jar:5.1.1]
	at com.hazelcast.client.impl.protocol.util.ClientMessageDecoder.onRead(ClientMessageDecoder.java:89) ~[hazelcast-5.1.1.jar:5.1.1]
	at com.hazelcast.internal.networking.nio.NioInboundPipeline.process(NioInboundPipeline.java:136) ~[hazelcast-5.1.1.jar:5.1.1]
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKey(NioThread.java:383) ~[hazelcast-5.1.1.jar:5.1.1]
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKeys(NioThread.java:368) ~[hazelcast-5.1.1.jar:5.1.1]
	at com.hazelcast.internal.networking.nio.NioThread.selectLoop(NioThread.java:294) ~[hazelcast-5.1.1.jar:5.1.1]
	at com.hazelcast.internal.networking.nio.NioThread.executeRun(NioThread.java:249) ~[hazelcast-5.1.1.jar:5.1.1]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) ~[hazelcast-5.1.1.jar:5.1.1]
Caused by: java.lang.IllegalStateException: Can't overwrite cause with a null
	at java.base/java.lang.Throwable.initCause(Throwable.java:462) ~[na:na]
	at com.hazelcast.internal.util.ExceptionUtil$ConstructorMethod$4.cloneWith(ExceptionUtil.java:314) ~[hazelcast-5.1.1.jar:5.1.1]
	at com.hazelcast.internal.util.ExceptionUtil.cloneException(ExceptionUtil.java:246) ~[hazelcast-5.1.1.jar:5.1.1]
	... 17 common frames omitted
Caused by: com.datastax.oss.driver.api.core.NoNodeAvailableException: No node was available to execute the query
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:710) ~[na:na]
	at com.hazelcast.internal.util.ExceptionUtil$ConstructorMethod$4.cloneWith(ExceptionUtil.java:313) ~[hazelcast-5.1.1.jar:5.1.1]
	... 18 common frames omitted
```

Hazelcast's ExceptionUtil.java - tryCreateExceptionWithMessageAndCause():
```
        try {
            constructor = LOOKUP.findConstructor(exceptionClass, MT_INIT);
            T clone = (T) constructor.invokeWithArguments();
            clone.initCause(cause);
            return clone;
        } catch (ClassCastException | WrongMethodTypeException...)
```

Throwable.java:
```
    public synchronized Throwable initCause(Throwable cause) {
        if (this.cause != this)
            **throw new IllegalStateException("Can't overwrite cause with " +
                                            Objects.toString(cause, "a null"), this);**
        if (cause == this)
            throw new IllegalArgumentException("Self-causation not permitted", this);
        this.cause = cause;
        return this;
    }
``` 

**Current workaround:**
Catch the NoNodeAvailableException in the MapStore's load method and throw a different runtime exception.
    
**Expected behavior**
The `ExceptionUtil.cloneException()` should handle the scenario when an exception type is thrown without a cause property and should not block the client forever but fail fast.

**To Reproduce**

1. Create a MapStore like this
```
public class FooStore implements MapStore<String, String> {

    @Override
    public String load(String key) {
        throw new com.datastax.oss.driver.api.core.NoNodeAvailableException();
    }
```
2. Call a HazelcastClientProxy.get()

**Comment by ahmetmircik** [comment]
@szokebarnabas thanks for the detailed analysis.  We will try to address this.

**Comment by ahmetmircik** [comment]
another similar issue: https://github.com/hazelcast/hazelcast/issues/19731

**Comment by szokebarnabas** [comment]
@ahmetmircik please find the source here: https://github.com/datastax/java-driver/blob/4.x/core/src/main/java/com/datastax/oss/driver/api/core/NoNodeAvailableException.java

**Comment by srknzl** [comment]
This problem happens because `NoNodeAvailableException` sets its own cause to `null`. I will add a try/catch block around `initCause` to fix the problem.
