### ISSUE TITLE
Kafka tests which using docker fail on MacOS

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#21431]
_master_ (commit 504ac9f2f3e2a561087708436085d9fb83b3ace5)

Failed on MacOS with Zulu JDK 8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-MacOS-ZuluJDK8/69/testReport/

Following tests failed:
- `com.hazelcast.jet.kafka.impl.StreamKafkaPTest`
- `com.hazelcast.jet.kafka.impl.StreamKafkaP_TimestampModesTest`
- `com.hazelcast.jet.kafka.impl.WriteKafkaPTest`
- `com.hazelcast.jet.sql.impl.connector.kafka.SqlAvroTest`
- `com.hazelcast.jet.sql.impl.connector.kafka.SqlJsonTest`
- `com.hazelcast.jet.sql.impl.connector.kafka.SqlKafkaAggregateTest`
- `com.hazelcast.jet.sql.impl.connector.kafka.SqlPlanCacheTest`
- `com.hazelcast.jet.sql.impl.connector.kafka.SqlPojoTest`
- `com.hazelcast.jet.sql.impl.connector.kafka.SqlPrimitiveTest`
- `com.hazelcast.jet.kafka.impl.StreamKafkaP_StandaloneKafkaTest.when_cancelledAfterBrokerDown_then_cancelsPromptly`

<details><summary>Stacktrace (for com.hazelcast.jet.kafka.impl.StreamKafkaPTest as an example):</summary>

```
org.testcontainers.containers.ContainerLaunchException: Container startup failed
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:345)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:326)
	at com.hazelcast.jet.kafka.impl.DockerizedKafkaTestSupport.createKafkaCluster(DockerizedKafkaTestSupport.java:40)
	at com.hazelcast.jet.kafka.impl.StreamKafkaPTest.beforeClass(StreamKafkaPTest.java:104)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:39)
	at com.hazelcast.test.OverridePropertyRule$1.evaluate(OverridePropertyRule.java:66)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:338)
	... 19 more
Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:537)
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:340)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
	... 20 more
Caused by: com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"error creating overlay mount to /var/lib/docker/overlay2/921b2fee71256ca489aa52084cd7b3f498c8d1ecdec514988941195365611508-init/merged: invalid argument"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247)
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.post(DefaultInvocationBuilder.java:124)
	at org.testcontainers.shaded.com.github.dockerjava.core.exec.CreateContainerCmdExec.execute(CreateContainerCmdExec.java:37)
	at org.testcontainers.shaded.com.github.dockerjava.core.exec.CreateContainerCmdExec.execute(CreateContainerCmdExec.java:13)
	at org.testcontainers.shaded.com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21)
	at org.testcontainers.shaded.com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
	at org.testcontainers.shaded.com.github.dockerjava.core.command.CreateContainerCmdImpl.exec(CreateContainerCmdImpl.java:608)
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:423)
	... 22 more
```

</details>

<details><summary>Standard output (for com.hazelcast.jet.kafka.impl.StreamKafkaPTest as an example):</summary>

```
20:27:07,357  INFO || - [ImageNameSubstitutor] Time-limited test - Image name substitution will be performed by: DefaultImageNameSubstitutor (composite of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitutor')
20:27:07,417  INFO || - [DockerClientProviderStrategy] Time-limited test - Loaded org.testcontainers.dockerclient.UnixSocketClientProviderStrategy from ~/.testcontainers.properties, will try it first
20:27:07,956  INFO || - [DockerClientProviderStrategy] Time-limited test - Found Docker environment with local Unix socket (unix:///var/run/docker.sock)
20:27:07,958  INFO || - [DockerClientFactory] Time-limited test - Docker host IP address is localhost
20:27:08,009  INFO || - [DockerClientFactory] Time-limited test - Connected to docker: 
  Server Version: 20.10.13
  API Version: 1.41
  Operating System: Docker Desktop
  Total Memory: 7859 MB
20:27:08,246  INFO || - [RegistryAuthLocator] Time-limited test - Credential helper/store (docker-credential-desktop) does not have credentials for index.docker.io
20:27:09,124  INFO || - [RyukResourceReaper] Time-limited test - Ryuk started - will monitor and terminate Testcontainers containers on JVM exit
20:27:09,125  INFO || - [DockerClientFactory] Time-limited test - Checking the system...
20:27:09,125  INFO || - [DockerClientFactory] Time-limited test - ?? Docker server version should be at least 1.6.0
20:27:09,252  INFO || - [DockerClientFactory] Time-limited test - ?? Docker environment should have more than 2GB free disk space
20:27:09,253  INFO || - [1]] Time-limited test - Creating container for image: confluentinc/cp-kafka:7.1.1
20:27:09,287 ERROR || - [1]] Time-limited test - Could not start container
com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"error creating overlay mount to /var/lib/docker/overlay2/921b2fee71256ca489aa52084cd7b3f498c8d1ecdec514988941195365611508-init/merged: invalid argument"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.1.jar:?]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.post(DefaultInvocationBuilder.java:124) ~[testcontainers-1.17.1.jar:?]
	at org.testcontainers.shaded.com.github.dockerjava.core.exec.CreateContainerCmdExec.execute(CreateContainerCmdExec.java:37) ~[testcontainers-1.17.1.jar:?]
	at org.testcontainers.shaded.com.github.dockerjava.core.exec.CreateContainerCmdExec.execute(CreateContainerCmdExec.java:13) ~[testcontainers-1.17.1.jar:?]
	at org.testcontainers.shaded.com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21) ~[testcontainers-1.17.1.jar:?]
	at org.testcontainers.shaded.com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35) ~[testcontainers-1.17.1.jar:?]
	at org.testcontainers.shaded.com.github.dockerjava.core.command.CreateContainerCmdImpl.exec(CreateContainerCmdImpl.java:608) ~[testcontainers-1.17.1.jar:?]
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:423) ~[testcontainers-1.17.1.jar:?]
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:340) ~[testcontainers-1.17.1.jar:?]
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81) [duct-tape-1.0.8.jar:?]
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:338) [testcontainers-1.17.1.jar:?]
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:326) [testcontainers-1.17.1.jar:?]
	at com.hazelcast.jet.kafka.impl.DockerizedKafkaTestSupport.createKafkaCluster(DockerizedKafkaTestSupport.java:40) [test-classes/:?]
	at com.hazelcast.jet.kafka.impl.StreamKafkaPTest.beforeClass(StreamKafkaPTest.java:104) [test-classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_302]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_302]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_302]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_302]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59) [junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56) [junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33) [junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24) [junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27) [junit-4.13.2.jar:4.13.2]
	at com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:39) [hazelcast-5.2-SNAPSHOT-tests.jar:5.2-SNAPSHOT]
	at com.hazelcast.test.OverridePropertyRule$1.evaluate(OverridePropertyRule.java:66) [hazelcast-5.2-SNAPSHOT-tests.jar:5.2-SNAPSHOT]
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299) [junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293) [junit-4.13.2.jar:4.13.2]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_302]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_302]
```

</details>

**Comment by TomaszGaweda** [comment]
@olukas Do you know what filesystem we use as backing filesystem? According to issue https://github.com/moby/moby/issues/23930 we may try:
1. Changing backing filesystem to ext4 (from xfs, if it was used)
2. Change overlay2 to devicemapper in dockerd configuration.

I've seen few similar posts and most of them suggested the devicemapper, but changing xfs->ext4 may be more transparent for other uses.

**Comment by olukas** [comment]
From `docker info`:
```
 Storage Driver: overlay2
  Backing Filesystem: extfs
```
@kwart you configured the machine, could you please take a look at it?

**Comment by ldziedziul** [comment]
I've reset docker desktop on the mac box to the factory defaults and it seems to be working: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-MacOS-ZuluJDK8/103:
<img width="1022" alt="image" src="https://user-images.githubusercontent.com/1242724/185176000-0942fca0-5daa-4990-89d4-2462c6951d1f.png">
