### ISSUE TITLE
com.hazelcast.multimap.LocalMultiMapStatsTest.testPutAllAndHitsGeneratedMap

### ISSUE THREAD

**Issue by bpoplawski** [hazelcast/hazelcast#21465]
_master_ (commit 5797f4d1ecb6318352916578717f7539f9d7a0bd )

Failed on 5.1.z IBM JDK8: http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-IbmJDK8/34/testReport/junit/com.hazelcast.multimap/LocalMultiMapStatsTest/testPutAllAndHitsGeneratedMap/

<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: expected:<100> but was:<0>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at com.hazelcast.multimap.LocalMultiMapStatsTest.testPutAllAndHitsGeneratedTemplateVerify(LocalMultiMapStatsTest.java:131)
	at com.hazelcast.multimap.LocalMultiMapStatsTest.testPutAllAndHitsGeneratedTemplate(LocalMultiMapStatsTest.java:123)
	at com.hazelcast.multimap.LocalMultiMapStatsTest.testPutAllAndHitsGeneratedMap(LocalMultiMapStatsTest.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.lang.Thread.run(Thread.java:825)
```

</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: testHitsGenerated_updatedConcurrently in 0.327 seconds.

No metrics recorded during the test
```

</details>

**Comment by olukas** [comment]
Failed on `5.1.z` on IbmJDK8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-IbmJDK8/50/testReport/com.hazelcast.multimap/LocalMultiMapStatsTest/testPutAllAndHitsGeneratedMap/

**Comment by olukas** [comment]
Failed on `master` on IbmJDK8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-IbmJDK8/204/testReport/com.hazelcast.multimap/LocalMultiMapStatsTest/testPutAllAndHitsGeneratedMap/

**Comment by mdumandag** [comment]
This should also be fixed by https://github.com/hazelcast/hazelcast/pull/22836
