### ISSUE TITLE
job failure - Hazelcast-master-WIndows-MicrosoftJDK11 - Remote call on windows-java-and-clients failed. The channel is closing down or has closed down

### ISSUE THREAD

**Issue by bpoplawski** [hazelcast/hazelcast#21464]
_master_ (commit f24be7c6a4d5e56b7648ac3c4489489624dad592 )

Failed on Windows Microsoft JDK11: http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Windows-MicrosoftJDK11/12/consoleFull

<details><summary>Stacktrace:</summary>

```
20:22:11 [INFO] Running com.hazelcast.jet.sql.impl.connector.generator.SqlStreamGeneratorTest
20:22:11 [908.750s][info][gc] GC(499) Pause Young (Normal) (G1 Evacuation Pause) 1234M->582M(1421M) 18.849ms
20:22:13 FATAL: command execution failed
20:28:16 java.io.EOFException
20:28:16 	at java.base/java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2905)
20:28:16 	at java.base/java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3400)
20:28:16 	at java.base/java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:936)
20:28:16 	at java.base/java.io.ObjectInputStream.<init>(ObjectInputStream.java:379)
20:28:16 	at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:49)
20:28:16 	at hudson.remoting.Command.readFrom(Command.java:142)
20:28:16 	at hudson.remoting.Command.readFrom(Command.java:128)
20:28:16 	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:35)
20:28:16 	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:61)
20:28:16 Caused: java.io.IOException: Unexpected termination of the channel
20:28:16 	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:75)
20:28:16 Caused: java.io.IOException: Backing channel 'windows-java-and-clients' is disconnected.
20:28:16 	at hudson.remoting.RemoteInvocationHandler.channelOrFail(RemoteInvocationHandler.java:215)
20:28:16 	at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:285)
20:28:16 	at com.sun.proxy.$Proxy105.isAlive(Unknown Source)
20:28:16 	at hudson.Launcher$RemoteLauncher$ProcImpl.isAlive(Launcher.java:1215)
20:28:16 	at hudson.Launcher$RemoteLauncher$ProcImpl.join(Launcher.java:1207)
20:28:16 	at hudson.tasks.CommandInterpreter.join(CommandInterpreter.java:195)
20:28:16 	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:145)
20:28:16 	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:92)
20:28:16 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
20:28:16 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:814)
20:28:16 	at hudson.model.Build$BuildExecution.build(Build.java:199)
20:28:16 	at hudson.model.Build$BuildExecution.doRun(Build.java:164)
20:28:16 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:522)
20:28:16 	at hudson.model.Run.execute(Run.java:1896)
20:28:16 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:44)
20:28:16 	at hudson.model.ResourceController.execute(ResourceController.java:101)
20:28:16 	at hudson.model.Executor.run(Executor.java:442)
20:28:16 FATAL: Unable to delete script file C:\Users\Administrator\AppData\Local\Temp\jenkins1990632380202880925.bat
20:28:16 java.io.EOFException
20:28:16 	at java.base/java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2905)
20:28:16 	at java.base/java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3400)
20:28:16 	at java.base/java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:936)
20:28:16 	at java.base/java.io.ObjectInputStream.<init>(ObjectInputStream.java:379)
20:28:16 	at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:49)
20:28:16 	at hudson.remoting.Command.readFrom(Command.java:142)
20:28:16 	at hudson.remoting.Command.readFrom(Command.java:128)
20:28:16 	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:35)
20:28:16 	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:61)
20:28:16 Caused: java.io.IOException: Unexpected termination of the channel
20:28:16 	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:75)
20:28:16 Caused: hudson.remoting.ChannelClosedException: Channel "hudson.remoting.Channel@c447040:windows-java-and-clients": Remote call on windows-java-and-clients failed. The channel is closing down or has closed down
20:28:16 	at hudson.remoting.Channel.call(Channel.java:993)
20:28:16 	at hudson.FilePath.act(FilePath.java:1194)
20:28:16 	at hudson.FilePath.act(FilePath.java:1183)
20:28:16 	at hudson.FilePath.delete(FilePath.java:1730)
20:28:16 	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:163)
20:28:16 	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:92)
20:28:16 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
20:28:16 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:814)
20:28:16 	at hudson.model.Build$BuildExecution.build(Build.java:199)
20:28:16 	at hudson.model.Build$BuildExecution.doRun(Build.java:164)
20:28:16 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:522)
20:28:16 	at hudson.model.Run.execute(Run.java:1896)
20:28:16 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:44)
20:28:16 	at hudson.model.ResourceController.execute(ResourceController.java:101)
20:28:16 	at hudson.model.Executor.run(Executor.java:442)
20:28:16 Build step 'Execute Windows batch command' marked build as failure
20:28:16 ERROR: Step ‘Publish JUnit test result report’ failed: no workspace for Hazelcast-master-Windows-MicrosoftJDK11 #12
20:28:16 ERROR: Step ‘Publish artifacts to S3 Bucket’ failed: no workspace for Hazelcast-master-Windows-MicrosoftJDK11 #12
20:28:16 [Slack Notifications] found #11 as previous completed, non-aborted build
20:28:16 ERROR: Step ‘Delete workspace when build is done’ failed: no workspace for Hazelcast-master-Windows-MicrosoftJDK11 #12
20:28:16 Finished: FAILURE
```

</details>

<details><summary>Standard output:</summary>

```
:11:39 [INFO]  T E S T S
20:11:39 [INFO] -------------------------------------------------------
20:11:39 [WARNING] Corrupted STDOUT by directly writing to native stream in forked JVM 1. See FAQ web page and the dump file C:\Jenkins\workspace\Hazelcast-master-Windows-MicrosoftJDK11\hazelcast\target\surefire-reports\2022-05-19T18-07-35_636-jvmRun1.dumpstream
20:11:48 [INFO] 
20:11:48 [INFO] Results:
20:11:48 [INFO] 
20:11:48 [INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
20:11:48 [INFO] 
20:11:48 
[ERROR] There are test failures.
20:11:48 
20:11:48 Please refer to C:\Jenkins\workspace\Hazelcast-master-Windows-MicrosoftJDK11\hazelcast\target\surefire-reports for the individual test results.
20:11:48 Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
20:11:48 There was an error in the forked process
20:11:48 com\hazelcast\test\package-info (wrong name: com/hazelcast/test/package-info)
20:11:48 org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process
20:11:48 com\hazelcast\test\package-info (wrong name: com/hazelcast/test/package-info)
20:11:48 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:656)
20:11:48 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:282)
20:11:48 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:245)
20:11:48 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1183)
20:11:48 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1011)
20:11:48 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:857)
20:11:48 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
20:11:48 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
20:11:48 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
20:11:48 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
20:11:48 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
20:11:48 	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:190)
20:11:48 	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:186)
20:11:48 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
20:11:48 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
20:11:48 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
20:11:48 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
20:11:48 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
20:11:48 	at java.base/java.lang.Thread.run(Thread.java:829)
20:11:48 
20:11:48 [INFO] 
20:11:48 [INFO] --- maven-jar-plugin:3.2.2:jar (default-jar) @ hazelcast ---
20:11:54 [INFO] Building jar: C:\Jenkins\workspace\Hazelcast-master-Windows-MicrosoftJDK11\hazelcast\target\hazelcast-5.2-SNAPSHOT.jar
```

</details>

**Comment by orcunc** [comment]
This looks like Hudson/Jenkins failure rather than test failure. So I am closing it
