### ISSUE TITLE
com.hazelcast.client.map.ClientMapReplaceAllTest.testReplaceAllWithStaticSerializableFunction

### ISSUE THREAD

**Issue by bpoplawski** [hazelcast/hazelcast#21470]
master (commit 291d05bd085211a4f647a5776146742d40b13752 )

Failed on IBM JDK8 : http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-IbmJDK8-nightly/54/testReport/junit/com.hazelcast.client.map/ClientMapReplaceAllTest/testReplaceAllWithStaticSerializableFunction/

javax.net.ssl.SSLException: Couldn't kickstart handshaking

<details><summary>Stacktrace:</summary>

```
com.hazelcast.test.starter.GuardianException: javax.net.ssl.SSLException: Couldn't kickstart handshaking
	at com.hazelcast.test.starter.HazelcastStarterUtils.rethrowGuardianException(HazelcastStarterUtils.java:53)
	at com.hazelcast.test.starter.HazelcastVersionLocator.downloadFile(HazelcastVersionLocator.java:125)
	at com.hazelcast.test.starter.HazelcastVersionLocator.downloadMainArtifact(HazelcastVersionLocator.java:96)
	at com.hazelcast.test.starter.HazelcastVersionLocator.locateMainArtifact(HazelcastVersionLocator.java:78)
	at com.hazelcast.test.starter.HazelcastVersionLocator.locateVersion(HazelcastVersionLocator.java:63)
	at com.hazelcast.test.starter.HazelcastStarter$HazelcastVersionClassloaderFuture.get(HazelcastStarter.java:400)
	at com.hazelcast.test.starter.HazelcastStarter.getTargetVersionClassloader(HazelcastStarter.java:264)
	at com.hazelcast.test.starter.HazelcastStarter.newHazelcastInstance(HazelcastStarter.java:122)
	at com.hazelcast.test.starter.HazelcastStarter.newHazelcastInstance(HazelcastStarter.java:103)
	at com.hazelcast.test.starter.HazelcastStarter.newHazelcastInstance(HazelcastStarter.java:72)
	at com.hazelcast.client.map.ClientMapReplaceAllTest.startHazelcastInstances(ClientMapReplaceAllTest.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:365)
	at com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37)
	at com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:104)
	at com.hazelcast.test.metrics.MetricsRule$1.evaluate(MetricsRule.java:63)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:50)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:29)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:39)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:107)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:83)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
Caused by: javax.net.ssl.SSLException: Couldn't kickstart handshaking
	at com.ibm.jsse2.g.a(g.java:16)
	at com.ibm.jsse2.bb.a(bb.java:163)
	at com.ibm.jsse2.bb.a(bb.java:81)
	at com.ibm.jsse2.bj.a(bj.java:473)
	at com.ibm.jsse2.bj.startHandshake(bj.java:20)
	at com.ibm.net.ssl.www2.protocol.https.c.afterConnect(c.java:23)
	at com.ibm.net.ssl.www2.protocol.https.d.connect(d.java:28)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1582)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1510)
	at com.ibm.net.ssl.www2.protocol.https.b.getInputStream(b.java:10)
	at java.net.URL.openStream(URL.java:1079)
	at com.hazelcast.test.starter.HazelcastVersionLocator.downloadFile(HazelcastVersionLocator.java:119)
	... 55 more
	Suppressed: java.net.SocketException: Broken pipe (Write failed)
		at java.net.SocketOutputStream.socketWrite0(Native Method)
		at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:122)
		at java.net.SocketOutputStream.write(SocketOutputStream.java:166)
		at com.ibm.jsse2.f.a(f.java:44)
		at com.ibm.jsse2.bb.a(bb.java:110)
		... 65 more
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:126)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:166)
	at com.ibm.jsse2.f.flush(f.java:169)
	at com.ibm.jsse2.c.flush(c.java:32)
	at com.ibm.jsse2.G$c.a(G$c.java:75)
	at com.ibm.jsse2.p.a(p.java:79)
	at com.ibm.jsse2.ab.b(ab.java:47)
	at com.ibm.jsse2.bb.a(bb.java:44)
	at com.ibm.jsse2.bj.a(bj.java:478)
	... 63 more
```

</details>

<details><summary>Standard output:</summary>

```
BuildInfo right after testReplaceAllWithStaticSerializableFunction(com.hazelcast.client.map.ClientMapReplaceAllTest): BuildInfo{version='5.2-SNAPSHOT', build='20220523', buildNumber=20220523, revision=291d05b, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'testReplaceAllWithStaticSerializableFunction(com.hazelcast.client.map.ClientMapReplaceAllTest):'
01:35:30, accumulated pauses: 31 ms, max pause: 22 ms, pauses over 1000 ms: 0


No metrics recorded during the test
```

</details>

**Comment by orcunc** [comment]
This test is related to https://github.com/hazelcast/hazelcast/issues/21401 - com.hazelcast.test.starter.test.HazelcastProxyFactoryTest.testProxyHazelcastInstanceClasses_ofSameVersion_areSame - 
and https://github.com/hazelcast/hazelcast/issues/21570 - com.hazelcast.test.starter.test.HazelcastVersionLocatorTest.testDownloadVersion

All of them are failing due to connectivity issue to maven central.

**Comment by orcunc** [comment]
Fixed by https://github.com/hazelcast/hazelcast/pull/22955
