### ISSUE TITLE
UnsafeRaftReplicateOp  IllegalStateException: No session: 1 for CP group: CPGroupId

### ISSUE THREAD

**Issue by pavelorehov** [hazelcast/hazelcast#21488]
HZ 5.1.1 running 3 nodes, 9 clients, in unsafe mode and clients uses CP subsystem locks and semaphores.

See flooding of below exception in logs:
29 00:35:55,966 [hz.silly_visvesvaraya.partition-operation.thread-0] ERROR c.h.c.i.o.u.UnsafeRaftReplicateOp - [10.244.131.51]:570
1 [main] [5.1.1] No session: 1 for CP group: CPGroupId{name='DeviceLock_720807', seed=0, groupId=24}
java.lang.IllegalStateException: No session: 1 for CP group: CPGroupId{name='DeviceLock_720807', seed=0, groupId=24}
        at com.hazelcast.cp.internal.session.RaftSessionService.heartbeat(RaftSessionService.java:239) ~[hazelcast-5.1.1.jar!/:5.1.1]
        at com.hazelcast.cp.internal.session.operation.HeartbeatSessionOp.run(HeartbeatSessionOp.java:49) ~[hazelcast-5.1.1.jar!/:5.1.1]
        at com.hazelcast.cp.internal.operation.unsafe.AbstractUnsafeRaftOp.call(AbstractUnsafeRaftOp.java:67) ~[hazelcast-5.1.1.jar!/:5.1.1]
        at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:273) ~[hazelcast-5.1.1.jar!/:5.1.1]
        at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:248) ~[hazelcast-5.1.1.jar!/:5.1.1]
        at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:471) ~[hazelcast-5.1.1.jar!/:5.1.1]
        at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:197) ~[hazelcast-5.1.1.jar!/:5.1.1]
        at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:137) ~[hazelcast-5.1.1.jar!/:5.1.1]
        at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123) ~[hazelcast-5.1.1.jar!/:5.1.1]
        at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) ~[hazelcast-5.1.1.jar!/:5.1.1]

**Comment by vbekiaris** [comment]
hello @pavelorehov , can you share what your hazelcast members & clients config looks like?

**Comment by pavelorehov** [comment]
Below is node client connection log:
14 17:20:10,526 [hz.blissful_turing.generic-operation.thread-1] INFO  c.h.c.i.p.t.AuthenticationMessageTask - [10.244.217.13]:5701 [main] [5.1.1] Recei
ved auth from Connection[id=4, /10.244.217.13:5701->/10.244.217.38:56981, qualifier=null, endpoint=[10.244.217.38]:56981, remoteUuid=ffb6958f-d2eb-447d
-b0cf-2e2d4d07eb37, alive=true, connectionType=JVM, planeIndex=-1], successfully authenticated, clientUuid: ffb6958f-d2eb-447d-b0cf-2e2d4d07eb37, clien
t name: main, client version: 4.1.1

Below is one of the nodes config:
Config{configurationUrl=null, configurationFile=null, classLoader=null, properties={hazelcast.prefer.ipv4.stack=false, hazelcast.shutdownhook.enabled=false, hazelcast.logging.type=slf4j, hazelcast.phone.home.enabled=false, hazelcast.discovery.enabled=true}, instanceName='null', clusterName='main', networkConfig=NetworkConfig{publicAddress='null', port=5701, portCount=100, portAutoIncrement=true, join=JoinConfig{multicastConfig=MulticastConfig [enabled=false, multicastGroup=224.2.2.3, multicastPort=54327, multicastTimeToLive=32, multicastTimeoutSeconds=2, trustedInterfaces=[], loopbackModeEnabled=null], tcpIpConfig=TcpIpConfig [enabled=false, connectionTimeoutSeconds=5, members=[], requiredMember=null], awsConfig=AliasedDiscoveryConfig{tag='aws', enabled=false, usePublicIp=false, properties={}}, gcpConfig=AliasedDiscoveryConfig{tag='gcp', enabled=false, usePublicIp=false, properties={}}, azureConfig=AliasedDiscoveryConfig{tag='azure', enabled=false, usePublicIp=false, properties={}}, kubernetesConfig=AliasedDiscoveryConfig{tag='kubernetes', enabled=false, usePublicIp=false, properties={}}, eurekaConfig=AliasedDiscoveryConfig{tag='eureka', enabled=false, usePublicIp=false, properties={}}, discoveryConfig=DiscoveryConfig{discoveryStrategyConfigs=[DiscoveryStrategyConfig{properties={etcd-username=u, etcd-url=http://etcd:2379, etcd-service-name=hz-discovery-main-cluster, etcd-, etcd-availability-timeout-sec=600, etcd-discovery-delay-ms=10000}, className='null', discoveryStrategyFactory=my.EtcdDiscoveryStrategyFactory@6e6943de}], discoveryServiceProvider=null, nodeFilter=null, nodeFilterClass='null'}, autoDetectionConfig=AutoDetectionConfig{enabled=true}}, interfaces=InterfacesConfig{enabled=false, interfaces=[]}, sslConfig=null, socketInterceptorConfig=null, symmetricEncryptionConfig=null, icmpFailureDetectorConfig=null, restApiConfig=RestApiConfig{enabled=false, enabledGroups=[HEALTH_CHECK, CLUSTER_READ]}, memcacheProtocolConfig=MemcacheProtocolConfig{enabled=false}}, configPatternMatcher=com.hazelcast.config.matcher.MatchingPointConfigPatternMatcher@e46bc91, mapConfigs={default=MapConfig{name='default', inMemoryFormat='BINARY', metadataPolicy=CREATE_ON_UPDATE, backupCount=1, asyncBackupCount=0, timeToLiveSeconds=0, maxIdleSeconds=0, readBackupData=false, evictionConfig=EvictionConfig{size=2147483647, maxSizePolicy=PER_NODE, evictionPolicy=NONE, comparatorClassName=null, comparator=null}, merkleTree=MerkleTreeConfig{enabled=null, depth=10}, eventJournal=EventJournalConfig{enabled=false, capacity=10000, timeToLiveSeconds=0}, hotRestart=HotRestartConfig{enabled=false, fsync=false}, dataPersistenceConfig=DataPersistenceConfig{enabled=false, fsync=false}, nearCacheConfig=null, mapStoreConfig=MapStoreConfig{enabled=false, className='null', factoryClassName='null', writeDelaySeconds=0, writeBatchSize=1, implementation=null, factoryImplementation=null, properties={}, initialLoadMode=LAZY, writeCoalescing=true}, mergePolicyConfig=MergePolicyConfig{policy='com.hazelcast.spi.merge.PutIfAbsentMergePolicy', batchSize=100}, wanReplicationRef=null, entryListenerConfigs=[], indexConfigs=[], attributeConfigs=[], splitBrainProtectionName=null, queryCacheConfigs=[], cacheDeserializedValues=INDEX_ONLY, statisticsEnabled=true, entryStatsEnabled=false, tieredStoreConfig=TieredStoreConfig{enabled=false, memoryTierConfig=MemoryTierConfig{capacity=256 MEGABYTES}, diskTierConfig=DiskTierConfig{enabled=false, deviceName='default-tiered-store-device'}}}}, cacheConfigs={}, topicConfigs={}, reliableTopicConfigs={}, queueConfigs={}, multiMapConfigs={}, listConfigs={}, setConfigs={default=SetConfig{name='default', listenerConfigs=[], backupCount=1, asyncBackupCount=0, maxSize=0, statisticsEnabled=true, splitBrainProtectionName='null', mergePolicyConfig='MergePolicyConfig{policy='com.hazelcast.spi.merge.PutIfAbsentMergePolicy', batchSize=100}'}}, executorConfigs={default=ExecutorConfig{name='default', poolSize=16, queueCapacity=2147483647, splitBrainProtectionName=null}}, durableExecutorConfigs={}, scheduledExecutorConfigs={default=ScheduledExecutorConfig{name='default', durability=1, poolSize=16, capacity=100, capacityPolicy=PER_NODE, statisticsEnabled=true, splitBrainProtectionName=null, mergePolicyConfig=MergePolicyConfig{policy='com.hazelcast.spi.merge.PutIfAbsentMergePolicy', batchSize=100}}}, replicatedMapConfigs={}, wanReplicationConfigs={}, splitBrainProtectionConfigs={}, ringbufferConfigs={}, cardinalityEstimatorConfigs={}, flakeIdGeneratorConfigMap={}, pnCounterConfigs={}, advancedNetworkConfig=AdvancedNetworkConfig{isEnabled=false, join=JoinConfig{multicastConfig=MulticastConfig [enabled=false, multicastGroup=224.2.2.3, multicastPort=54327, multicastTimeToLive=32, multicastTimeoutSeconds=2, trustedInterfaces=[], loopbackModeEnabled=null], tcpIpConfig=TcpIpConfig [enabled=false, connectionTimeoutSeconds=5, members=[], requiredMember=null], awsConfig=AliasedDiscoveryConfig{tag='aws', enabled=false, usePublicIp=false, properties={}}, gcpConfig=AliasedDiscoveryConfig{tag='gcp', enabled=false, usePublicIp=false, properties={}}, azureConfig=AliasedDiscoveryConfig{tag='azure', enabled=false, usePublicIp=false, properties={}}, kubernetesConfig=AliasedDiscoveryConfig{tag='kubernetes', enabled=false, usePublicIp=false, properties={}}, eurekaConfig=AliasedDiscoveryConfig{tag='eureka', enabled=false, usePublicIp=false, properties={}}, discoveryConfig=DiscoveryConfig{discoveryStrategyConfigs=[], discoveryServiceProvider=null, nodeFilter=null, nodeFilterClass='null'}, autoDetectionConfig=AutoDetectionConfig{enabled=true}}, memberAddressProvider=MemberAddressProviderConfig{enabled=false, className='null', properties={}, implementation=null}, endpointConfigs={EndpointQualifier{type='MEMBER'}=EndpointConfig{protocolType=MEMBER, name=null, port=5701, portCount=100, portAutoIncrement=true, publicAddress=null, interfaces=InterfacesConfig{enabled=false, interfaces=[]}, sslConfig=null, socketInterceptorConfig=null}}, icmpFailureDetectorConfig=null}, servicesConfig=ServicesConfig{enableDefaults=true, services={}}, securityConfig=SecurityConfig [enabled=false, securityInterceptorConfigs=[], clientPolicyConfig=PermissionPolicyConfig{className='null', implementation=null, properties={}}, clientPermissionConfigs=[], realmConfigs={}, memberRealm=null, clientRealm=null, clientBlockUnmappedActions=true, onJoinPermissionOperation=RECEIVE], listenerConfigs=[], partitionGroupConfig=PartitionGroupConfig{enabled=false, groupType=PER_MEMBER, memberGroupConfigs=[]}, managementCenterConfig=ManagementCenterConfig{scriptingEnabled=falsetrustedInterfaces=[]}, serializationConfig=SerializationConfig{portableVersion=0, dataSerializableFactoryClasses={}, dataSerializableFactories={}, portableFactoryClasses={}, portableFactories={}, globalSerializerConfig=GlobalSerializerConfig{className='info.jerrinot.subzero.Serializer', implementation=null, overrideJavaSerialization=true}, serializerConfigs=[], checkClassDefErrors=true, classDefinitions=[], byteOrder=BIG_ENDIAN, useNativeByteOrder=false, javaSerializationFilterConfig=null, allowOverrideDefaultSerializers=false}, managedContext=null, userContext={}, memberAttributeConfig=com.hazelcast.config.MemberAttributeConfig@1f, nativeMemoryConfig=NativeMemoryConfig{enabled=false, size=512 MEGABYTES, allocatorType=POOLED, minBlockSize=16, pageSize=4194304, metadataSpacePercentage=12.5, persistentMemoryConfig=PersistentMemoryConfig{enabled=false, mode=MOUNTED, directoryConfigs=[]}}, hotRestartPersistenceConfig=HotRestartPersistenceConfig{enabled=false, baseDir=persistence, backupDir=null, parallelism=1, validationTimeoutSeconds=120, dataLoadTimeoutSeconds=900, clusterDataRecoveryPolicy=FULL_RECOVERY_ONLY, autoRemoveStaleData=true, encryptionAtRestConfig=EncryptionAtRestConfig{enabled=false, algorithm='AES/CBC/PKCS5Padding', salt='***', keySize=0, secureStoreConfig=com.hazelcast.config.EncryptionAtRestConfig$NoSecureStoreConfig@0}}, persistenceConfig=PersistenceConfig{enabled=false, baseDir=persistence, backupDir=null, parallelism=1, validationTimeoutSeconds=120, dataLoadTimeoutSeconds=900, rebalanceDelaySeconds=900, clusterDataRecoveryPolicy=FULL_RECOVERY_ONLY, autoRemoveStaleData=true, encryptionAtRestConfig=EncryptionAtRestConfig{enabled=false, algorithm='AES/CBC/PKCS5Padding', salt='***', keySize=0, secureStoreConfig=com.hazelcast.config.EncryptionAtRestConfig$NoSecureStoreConfig@0}}, userCodeDeploymentConfig=com.hazelcast.config.UserCodeDeploymentConfig@10adb8c8, crdtReplicationConfig=com.hazelcast.config.CRDTReplicationConfig@7cda, liteMember=false, cpSubsystemConfig=CPSubsystemConfig{cpMemberCount=0, groupSize=0, sessionTimeToLiveSeconds=300, sessionHeartbeatIntervalSeconds=5, missingCPMemberAutoRemovalSeconds=14400, failOnIndeterminateOperationState=false, raftAlgorithmConfig=RaftAlgorithmConfig{leaderElectionTimeoutInMillis=2000, leaderHeartbeatPeriodInMillis=5000, maxMissedLeaderHeartbeatCount=5, appendRequestMaxEntryCount=100, commitIndexAdvanceCountToSnapshot=10000, uncommittedEntryCountToRejectNewAppends=100, appendRequestBackoffTimeoutInMillis=100}, semaphoreConfigs={}, lockConfigs={}}, sqlConfig=SqlConfig{statementTimeoutMillis=0}, metricsConfig=MetricsConfig{enabled=false, managementCenterConfig=MetricsManagementCenterConfig{enabled=true, retentionSeconds=5}, jmxConfig=MetricsJmxConfig{enabled=true}, collectionFrequencySeconds=5}, auditlogConfig=AuditlogConfig{factoryClassName='null', enabled=false, properties={}}, jetConfig=com.hazelcast.jet.config.JetConfig@bebd956b, deviceConfigs={default-tiered-store-device=LocalDeviceConfig{name='default-tiered-store-device', baseDir=/opt/my/bin/tiered-store, capacity=256 GIGABYTES, blockSize=4096, readIOThreadCount=4, writeIOThreadCount=4}}, integrityCheckerConfig=com.hazelcast.config.IntegrityCheckerConfig@319146e9}

**Comment by pavelorehov** [comment]
Is that planned to be fixed for 5.x.x releases ?

**Comment by pavelorehov** [comment]
Is that planned to be fixed in any future releases ?

**Comment by vbekiaris** [comment]
@pavelorehov we are improving CP subsystem, but we are focusing on better support for the CP enabled==true case, not unsafe mode.
Could you test if the issue persists when you upgrade both member & client to latest stable version (5.3.1)?

**Comment by pavelorehov** [comment]
We are not planning to enable CP for now but will definitely test with 5.3.1.
There is no easy way to reproduce the issue, so we will give it some time to run and if see similar issues will update here.
Thanks for your support.
