### ISSUE TITLE
Clients connection messages' differences than java client 

### ISSUE THREAD

**Issue by alisengul53** [hazelcast/hazelcast#21534]
All clients connection messages should be compatible with java.
Here is an example of connection, and exception of connection message of java client with Hazelcast Cloud

`INFO: hz.client_1 [ua-1651] [5.1-SNAPSHOT] HazelcastClient 5.1-SNAPSHOT (20220221 - 303417e, 7a48ef5) is STARTING
Mar 19, 2022 10:14:41 PM com.hazelcast.core.LifecycleService
INFO: hz.client_1 [ua-1651] [5.1-SNAPSHOT] HazelcastClient 5.1-SNAPSHOT (20220221 - 303417e, 7a48ef5) is STARTED
Mar 19, 2022 10:14:41 PM com.hazelcast.client.impl.connection.ClientConnectionManager
INFO: hz.client_1 [ua-1651] [5.1-SNAPSHOT] Trying to connect to cluster: ua-1651
Mar 19, 2022 10:14:41 PM com.hazelcast.client.impl.connection.ClientConnectionManager
INFO: hz.client_1 [ua-1651] [5.1-SNAPSHOT] Trying to connect to [100.119.172.247]:42006
Mar 19, 2022 10:14:42 PM com.hazelcast.client.impl.connection.tcp.TcpClientConnection
WARNING: hz.client_1 [ua-1651] [5.1-SNAPSHOT] ClientConnection{alive=false, connectionId=1, channel=NioChannel{/10.1.0.72:34621->/34.214.61.120:30029}, remoteAddress=null, lastReadTime=1969-12-31 23:59:59.999, lastWriteTime=2022-03-19 22:14:41.929, closedTime=2022-03-19 22:14:42.037, connected server version=null} closed. Reason: Exception in ClientConnection{alive=true, connectionId=1, channel=NioChannel{/10.1.0.72:34621->/34.214.61.120:30029}, remoteAddress=null, lastReadTime=1969-12-31 23:59:59.999, lastWriteTime=2022-03-19 22:14:41.929, closedTime=never, connected server version=null}, thread=hz.hz.client_1.IO.thread-in-0
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:197)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:379)
	at com.hazelcast.internal.networking.nio.NioInboundPipeline.process(NioInboundPipeline.java:114)
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKey(NioThread.java:383)
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKeys(NioThread.java:368)
	at com.hazelcast.internal.networking.nio.NioThread.selectLoop(NioThread.java:294)
	at com.hazelcast.internal.networking.nio.NioThread.executeRun(NioThread.java:249)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)

Mar 19, 2022 10:14:42 PM com.hazelcast.client.impl.connection.ClientConnectionManager
WARNING: hz.client_1 [ua-1651] [5.1-SNAPSHOT] Exception during initial connection to [100.119.172.247]:42006: com.hazelcast.spi.exception.TargetDisconnectedException: Exception in ClientConnection{alive=true, connectionId=1, channel=NioChannel{/10.1.0.72:34621->/34.214.61.120:30029}, remoteAddress=null, lastReadTime=1969-12-31 23:59:59.999, lastWriteTime=2022-03-19 22:14:41.929, closedTime=never, connected server version=null}, thread=hz.hz.client_1.IO.thread-in-0`

**Comment by srknzl** [comment]
🤔 I wonder why this issue is opened in the Java repo. as I guess it is for fixing non-Java clients right?

**Comment by srknzl** [comment]
the label on issues does not create issues for other clients
