### ISSUE TITLE
Size mismatch -> header: 32, param: 16   AbstractPoolingMemoryManager.free(AbstractPoolingMemoryManager.java:105)

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#21545]
exception during member jvm freeze stress tests.

```
SEVERE: [10.0.0.233]:5701 [HZ] [5.2-SNAPSHOT] Size mismatch -> header: 32, param: 16
java.lang.AssertionError: Size mismatch -> header: 32, param: 16
	at com.hazelcast.internal.memory.AbstractPoolingMemoryManager.free(AbstractPoolingMemoryManager.java:105)
	at com.hazelcast.internal.memory.PoolingMemoryManager.free(PoolingMemoryManager.java:190)
	at com.hazelcast.internal.serialization.impl.EnterpriseSerializationServiceV1.disposeDataInternal(EnterpriseSerializationServiceV1.java:208)
	at com.hazelcast.internal.serialization.impl.EnterpriseSerializationServiceV1.disposeData(EnterpriseSerializationServiceV1.java:198)
	at com.hazelcast.internal.hidensity.impl.AbstractHiDensityRecordAccessor.disposeData(AbstractHiDensityRecordAccessor.java:127)
	at com.hazelcast.internal.hidensity.impl.DefaultHiDensityRecordProcessor.disposeData(DefaultHiDensityRecordProcessor.java:110)
	at com.hazelcast.internal.hidensity.impl.DefaultHiDensityRecordProcessor.disposeDeferredBlocks(DefaultHiDensityRecordProcessor.java:197)
	at com.hazelcast.map.impl.recordstore.HDStorageImpl.disposeDeferredBlocks(HDStorageImpl.java:222)
	at com.hazelcast.map.impl.recordstore.AbstractRecordStore.disposeDeferredBlocks(AbstractRecordStore.java:219)
	at com.hazelcast.map.impl.recordstore.AbstractEvictableRecordStore.disposeDeferredBlocks(AbstractEvictableRecordStore.java:51)
	at com.hazelcast.map.impl.operation.MapOperation.disposeDeferredBlocks(MapOperation.java:214)
	at com.hazelcast.map.impl.operation.MapOperation.evict(MapOperation.java:296)
	at com.hazelcast.map.impl.operation.BasePutOperation.afterRunInternal(BasePutOperation.java:49)
	at com.hazelcast.map.impl.operation.MapOperation.afterRun(MapOperation.java:139)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.afterRun(OperationRunnerImpl.java:353)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:287)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:248)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:213)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:175)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:139)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
```

(base) [ec2-user@ip-10-0-0-252 structs]$ pwd
/disk1/workspace/freeze-all/5.2-SNAPSHOT/2022_06_03-18_20_01/stable/structs

**Comment by Danny-Hazelcast** [comment]
(base) [ec2-user@ip-10-0-0-252 structs]$
/home/ec2-user/workspace/issue-21545/
