### ISSUE TITLE
com.hazelcast.test.starter.test.HazelcastVersionLocatorTest.testDownloadVersion

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#21570]
_master_ (commit ef4d1ed82c62b3e8647b17469818323546291b5f)

Failed on Sonar build (Oracle JDK 11): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/1241/testReport/com.hazelcast.test.starter.test/HazelcastVersionLocatorTest/testDownloadVersion/

<details><summary>Stacktrace:</summary>

```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.base@11.0.13/java.net.SocketInputStream.socketRead0(Native Method)
	at java.base@11.0.13/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
	at java.base@11.0.13/java.net.SocketInputStream.read(SocketInputStream.java:168)
	at java.base@11.0.13/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at java.base@11.0.13/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:478)
	at java.base@11.0.13/sun.security.ssl.SSLSocketInputRecord.readFully(SSLSocketInputRecord.java:461)
	at java.base@11.0.13/sun.security.ssl.SSLSocketInputRecord.decodeInputRecord(SSLSocketInputRecord.java:243)
	at java.base@11.0.13/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:181)
	at java.base@11.0.13/sun.security.ssl.SSLTransport.decode(SSLTransport.java:110)
	at java.base@11.0.13/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1372)
	at java.base@11.0.13/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1339)
	at java.base@11.0.13/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:959)
	at java.base@11.0.13/java.io.BufferedInputStream.read1(BufferedInputStream.java:290)
	at java.base@11.0.13/java.io.BufferedInputStream.read(BufferedInputStream.java:351)
	at java.base@11.0.13/sun.net.www.MeteredStream.read(MeteredStream.java:134)
	at java.base@11.0.13/java.io.FilterInputStream.read(FilterInputStream.java:133)
	at java.base@11.0.13/sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3510)
	at java.base@11.0.13/java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
	at java.base@11.0.13/java.io.BufferedInputStream.read1(BufferedInputStream.java:292)
	at java.base@11.0.13/java.io.BufferedInputStream.read(BufferedInputStream.java:351)
	at java.base@11.0.13/java.io.FilterInputStream.read(FilterInputStream.java:107)
	at app//com.hazelcast.internal.nio.IOUtil.drainTo(IOUtil.java:771)
	at app//com.hazelcast.test.starter.HazelcastVersionLocator.downloadFile(HazelcastVersionLocator.java:121)
	at app//com.hazelcast.test.starter.HazelcastVersionLocator.downloadMainArtifact(HazelcastVersionLocator.java:96)
	at app//com.hazelcast.test.starter.HazelcastVersionLocator.locateMainArtifact(HazelcastVersionLocator.java:78)
	at app//com.hazelcast.test.starter.HazelcastVersionLocator.locateVersion(HazelcastVersionLocator.java:63)
	at app//com.hazelcast.test.starter.test.HazelcastVersionLocatorTest.testDownloadVersion(HazelcastVersionLocatorTest.java:52)
	at java.base@11.0.13/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@11.0.13/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base@11.0.13/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@11.0.13/java.lang.reflect.Method.invoke(Method.java:566)
	at app//org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at app//org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at app//org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at app//org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at app//com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at app//com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base@11.0.13/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base@11.0.13/java.lang.Thread.run(Thread.java:834)
```

</details>

**Comment by olukas** [comment]
Failed on Sonar build (Oracle JDK 11): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/1248/testReport/com.hazelcast.test.starter.test/HazelcastVersionLocatorTest/testDownloadVersion/

**Comment by olukas** [comment]
Failed on Sonar build (Oracle JDK 11): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/1254/testReport/com.hazelcast.test.starter.test/HazelcastVersionLocatorTest/testDownloadVersion/

<details><summary>Stacktrace:</summary>

```
com.hazelcast.test.starter.GuardianException: javax.net.ssl.SSLException: Connection reset
	at com.hazelcast.test.starter.HazelcastStarterUtils.rethrowGuardianException(HazelcastStarterUtils.java:53)
	at com.hazelcast.test.starter.HazelcastVersionLocator.downloadFile(HazelcastVersionLocator.java:125)
	at com.hazelcast.test.starter.HazelcastVersionLocator.downloadTestsArtifact(HazelcastVersionLocator.java:103)
	at com.hazelcast.test.starter.HazelcastVersionLocator.locateTestsArtifact(HazelcastVersionLocator.java:88)
	at com.hazelcast.test.starter.HazelcastVersionLocator.locateVersion(HazelcastVersionLocator.java:67)
	at com.hazelcast.test.starter.test.HazelcastVersionLocatorTest.testDownloadVersion(HazelcastVersionLocatorTest.java:52)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: javax.net.ssl.SSLException: Connection reset
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:127)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:369)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:312)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:307)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:144)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1369)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1278)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:401)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:373)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:197)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
	at java.base/java.net.URL.openStream(URL.java:1165)
	at com.hazelcast.test.starter.HazelcastVersionLocator.downloadFile(HazelcastVersionLocator.java:119)
	... 16 more
	Suppressed: java.net.SocketException: Broken pipe (Write failed)
		at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
		at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110)
		at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:150)
		at java.base/sun.security.ssl.SSLSocketOutputRecord.encodeAlert(SSLSocketOutputRecord.java:83)
		at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:400)
		... 30 more
Caused by: java.net.SocketException: Connection reset
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:186)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:478)
	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472)
	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:110)
	... 27 more
```

</details>

**Comment by orcunc** [comment]
This test is related to https://github.com/hazelcast/hazelcast/issues/21401 - com.hazelcast.test.starter.test.HazelcastProxyFactoryTest.testProxyHazelcastInstanceClasses_ofSameVersion_areSame - both of them are failing due to connectivity issue to maven central. If https://github.com/hazelcast/hazelcast/issues/21401 is fixed then this failure will also be fixed

**Comment by orcunc** [comment]
https://github.com/hazelcast/hazelcast/pull/22955
