### ISSUE TITLE
com.hazelcast.internal.partition.impl.MigrationCommitTest.shouldCommitMigrationWhenSourceFailsDuringCommit [HZ-1881]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#21580]
_5.1.z_ (commit 3cbd4fc0574620486a7712ec98e28f3301ed9a1b)

Failed on ZingJDK8: http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-ZingJDK8/76/testReport/com.hazelcast.internal.partition.impl/MigrationCommitTest/shouldCommitMigrationWhenSourceFailsDuringCommit/

<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertFalse(Assert.java:65)
	at org.junit.Assert.assertFalse(Assert.java:75)
	at com.hazelcast.internal.partition.impl.MigrationCommitTest.shouldCommitMigrationWhenSourceFailsDuringCommit(MigrationCommitTest.java:313)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

</details>

**Comment by orcunc** [comment]
The problem is master response is processed after PartitionStateOperation. Excerpt from the logs

> 19:43:01,349  WARN |shouldCommitMigrationWhenSourceFailsDuringCommit| - [PartitionStateOperation] hz.adoring_varahamihira.generic-operation.thread-0 - [127.0.0.1]:5703 [dev] [5.1.3-SNAPSHOT] com.hazelcast.spi.exception.CallerNotMemberException: Not Member! this: [127.0.0.1]:5703, caller: [127.0.0.1]:5701, partitionId: -1, operation: com.hazelcast.internal.partition.operation.PartitionStateOperation, service: hz:core:partitionService
> ...
> 
> 19:43:01,417 DEBUG |shouldCommitMigrationWhenSourceFailsDuringCommit| - [ClusterJoinManager] hz.adoring_varahamihira.priority-generic-operation.thread-0 - [127.0.0.1]:5703 [dev] [5.1.3-SNAPSHOT] Handling master response [127.0.0.1]:5701 from [127.0.0.1]:5701
> 19:43:01,417 DEBUG |shouldCommitMigrationWhenSourceFailsDuringCommit| - [ClusterService] hz.adoring_varahamihira.priority-generic-operation.thread-0 - [127.0.0.1]:5703 [dev] [5.1.3-SNAPSHOT] Setting master address to [127.0.0.1]:5701
> 19:43:01,418 DEBUG |shouldCommitMigrationWhenSourceFailsDuringCommit| - [MockJoiner] shouldCommitMigrationWhenSourceFailsDuringCommit - [127.0.0.1]:5703 [dev] [5.1.3-SNAPSHOT] Known master address is: [127.0.0.1]:5701
> 19:43:01,418 DEBUG |shouldCommitMigrationWhenSourceFailsDuringCommit| - [MockJoiner] shouldCommitMigrationWhenSourceFailsDuringCommit - [127.0.0.1]:5703 [dev] [5.1.3-SNAPSHOT] Sending join request to [127.0.0.1]:5701
> 

So for some reason the priority thread is blocked or paused

**Comment by orcunc** [comment]
Another related issue is https://github.com/hazelcast/hazelcast-enterprise/issues/4375#issuecomment-1339104322
