### ISSUE TITLE
com.hazelcast.spi.impl.operationservice.impl.RepartitioningStressTest.replaceUpdatesAtLeastOnce [HZ-1868]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#21613]
_master_ (commit 7235c3dd77f3fa03f4f105d31963c546e1db48ef)

Failed on IbmJDK8 in FIPS mode: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-IbmJDK8-fips-nightly/430/testReport/com.hazelcast.spi.impl.operationservice.impl/RepartitioningStressTest/replaceUpdatesAtLeastOnce/

<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: Unexpected count of updates seen in listener, expected: 4160685, actual 4160684, tolerance for duplicates: 10
	at org.junit.Assert.fail(Assert.java:89)
	at com.hazelcast.spi.impl.operationservice.impl.RepartitioningStressTest.assertEqualsWithDuplicatesTolerance(RepartitioningStressTest.java:184)
	at com.hazelcast.spi.impl.operationservice.impl.RepartitioningStressTest.replaceUpdatesAtLeastOnce(RepartitioningStressTest.java:127)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.lang.Thread.run(Thread.java:822)
```

</details>

Standard output can be downloaded from https://console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-IbmJDK8-fips-nightly/430/

**Comment by Patras3** [comment]
Failed again on _5.2.0_ with oracle-8: https://jenkins.hazelcast.com/view/Release/job/Hazelcast-5.releaseBranch-nightly/15/testReport/com.hazelcast.spi.impl.operationservice.impl/RepartitioningStressTest/replaceUpdatesAtLeastOnce/

**Comment by Patras3** [comment]
Failed again on _master_ with OpenJDK19: https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK19-nightly/5/testReport/com.hazelcast.spi.impl.operationservice.impl/RepartitioningStressTest/replaceUpdatesAtLeastOnce/
