### ISSUE TITLE
com.hazelcast.scheduledexecutor.impl.ScheduledExecutorServiceBasicTest.scheduleOnMember_whenAutoDisposable_thenGet

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#21638]
_5.1.z_ (commit 96c368f2329b2b7dcb5483a1da28186ff0544ae6)

Failed on Openj9-11: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-Openj9-11/39/testReport/com.hazelcast.scheduledexecutor.impl/ScheduledExecutorServiceBasicTest/scheduleOnMember_whenAutoDisposable_thenGet/

<details><summary>Stacktrace:</summary>

```
junit.framework.AssertionFailedError: Expected com.hazelcast.scheduledexecutor.StaleTaskException to be thrown, but nothing was thrown.
	at com.hazelcast.test.HazelcastTestSupport.assertThrows(HazelcastTestSupport.java:1430)
	at com.hazelcast.scheduledexecutor.impl.ScheduledExecutorServiceBasicTest.lambda$assertTaskHasBeenDestroyedEventually$2(ScheduledExecutorServiceBasicTest.java:997)
	at com.hazelcast.scheduledexecutor.impl.ScheduledExecutorServiceBasicTest$$Lambda$6583/0x0000000000000000.run(Unknown Source)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1226)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1243)
	at com.hazelcast.scheduledexecutor.impl.ScheduledExecutorServiceBasicTest.assertTaskHasBeenDestroyedEventually(ScheduledExecutorServiceBasicTest.java:997)
	at com.hazelcast.scheduledexecutor.impl.ScheduledExecutorServiceBasicTest.scheduleOnMember_whenAutoDisposable_thenGet(ScheduledExecutorServiceBasicTest.java:982)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:866)
```

</details>

<details><summary>Standard output:</summary>

```
03:32:46,972  INFO |scheduleOnMember_whenAutoDisposable_thenGet| - [LifecycleService] Thread-64295 - [127.0.0.1]:5702 [dev] [5.1.3-SNAPSHOT] [127.0.0.1]:5702 is SHUTTING_DOWN
03:32:46,973  WARN |scheduleOnMember_whenAutoDisposable_thenGet| - [Node] Thread-64295 - [127.0.0.1]:5702 [dev] [5.1.3-SNAPSHOT] Terminating forcefully...
03:32:46,973  INFO |scheduleOnMember_whenAutoDisposable_thenGet| - [Node] Thread-64295 - [127.0.0.1]:5702 [dev] [5.1.3-SNAPSHOT] Shutting down connection manager...
03:32:46,973  INFO |scheduleOnMember_whenAutoDisposable_thenGet| - [MockServer] Thread-64295 - [127.0.0.1]:5701 [dev] [5.1.3-SNAPSHOT] Removed connection to endpoint: [address=[127.0.0.1]:5702, uuid=1ba9fa23-b10b-4b47-a7e6-d9430695029b], connection: MockConnection{localEndpoint=[address=[127.0.0.1]:5701, uuid=ab44867b-6f73-439c-ba2b-ae9f3b095da8], remoteEndpoint=[address=[127.0.0.1]:5702, uuid=1ba9fa23-b10b-4b47-a7e6-d9430695029b], alive=false}
03:32:46,973  INFO |scheduleOnMember_whenAutoDisposable_thenGet| - [MockServer] Thread-64295 - [127.0.0.1]:5702 [dev] [5.1.3-SNAPSHOT] Removed connection to endpoint: [address=[127.0.0.1]:5701, uuid=ab44867b-6f73-439c-ba2b-ae9f3b095da8], connection: MockConnection{localEndpoint=[address=[127.0.0.1]:5702, uuid=1ba9fa23-b10b-4b47-a7e6-d9430695029b], remoteEndpoint=[address=[127.0.0.1]:5701, uuid=ab44867b-6f73-439c-ba2b-ae9f3b095da8], alive=false}
03:32:46,973  INFO |scheduleOnMember_whenAutoDisposable_thenGet| - [MembershipManager] Thread-64295 - [127.0.0.1]:5701 [dev] [5.1.3-SNAPSHOT] Removing Member [127.0.0.1]:5702 - 1ba9fa23-b10b-4b47-a7e6-d9430695029b
03:32:46,973  INFO |scheduleOnMember_whenAutoDisposable_thenGet| - [ClusterService] Thread-64295 - [127.0.0.1]:5701 [dev] [5.1.3-SNAPSHOT] 

Members {size:1, ver:3} [
	Member [127.0.0.1]:5701 - ab44867b-6f73-439c-ba2b-ae9f3b095da8 this
]

03:32:46,973  INFO |scheduleOnMember_whenAutoDisposable_thenGet| - [Node] Thread-64295 - [127.0.0.1]:5702 [dev] [5.1.3-SNAPSHOT] Shutting down node engine...
03:32:46,973  INFO |scheduleOnMember_whenAutoDisposable_thenGet| - [TransactionManagerService] hz.sharp_dhawan.cached.thread-22 - [127.0.0.1]:5701 [dev] [5.1.3-SNAPSHOT] Committing/rolling-back live transactions of [127.0.0.1]:5702, UUID: 1ba9fa23-b10b-4b47-a7e6-d9430695029b
03:32:46,985  INFO |scheduleOnMember_whenAutoDisposable_thenGet| - [NodeExtension] Thread-64295 - [127.0.0.1]:5702 [dev] [5.1.3-SNAPSHOT] Destroying node NodeExtension.
03:32:46,986  INFO |scheduleOnMember_whenAutoDisposable_thenGet| - [Node] Thread-64295 - [127.0.0.1]:5702 [dev] [5.1.3-SNAPSHOT] Hazelcast Shutdown is completed in 13 ms.
03:32:46,986  INFO |scheduleOnMember_whenAutoDisposable_thenGet| - [LifecycleService] Thread-64295 - [127.0.0.1]:5702 [dev] [5.1.3-SNAPSHOT] [127.0.0.1]:5702 is SHUTDOWN
03:32:46,986  INFO |scheduleOnMember_whenAutoDisposable_thenGet| - [LifecycleService] Thread-64295 - [127.0.0.1]:5701 [dev] [5.1.3-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
03:32:46,986  WARN |scheduleOnMember_whenAutoDisposable_thenGet| - [Node] Thread-64295 - [127.0.0.1]:5701 [dev] [5.1.3-SNAPSHOT] Terminating forcefully...
03:32:46,986  INFO |scheduleOnMember_whenAutoDisposable_thenGet| - [Node] Thread-64295 - [127.0.0.1]:5701 [dev] [5.1.3-SNAPSHOT] Shutting down connection manager...
03:32:46,986  INFO |scheduleOnMember_whenAutoDisposable_thenGet| - [Node] Thread-64295 - [127.0.0.1]:5701 [dev] [5.1.3-SNAPSHOT] Shutting down node engine...
03:32:46,997  INFO |scheduleOnMember_whenAutoDisposable_thenGet| - [NodeExtension] Thread-64295 - [127.0.0.1]:5701 [dev] [5.1.3-SNAPSHOT] Destroying node NodeExtension.
03:32:46,999  INFO |scheduleOnMember_whenAutoDisposable_thenGet| - [Node] Thread-64295 - [127.0.0.1]:5701 [dev] [5.1.3-SNAPSHOT] Hazelcast Shutdown is completed in 13 ms.
03:32:46,999  INFO |scheduleOnMember_whenAutoDisposable_thenGet| - [LifecycleService] Thread-64295 - [127.0.0.1]:5701 [dev] [5.1.3-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
BuildInfo right after scheduleOnMember_whenAutoDisposable_thenGet(com.hazelcast.scheduledexecutor.impl.ScheduledExecutorServiceBasicTest): BuildInfo{version='5.1.3-SNAPSHOT', build='20220620', buildNumber=20220620, revision=96c368f, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'scheduleOnMember_whenAutoDisposable_thenGet(com.hazelcast.scheduledexecutor.impl.ScheduledExecutorServiceBasicTest):'
03:31:50, accumulated pauses: 239 ms, max pause: 174 ms, pauses over 1000 ms: 0
03:31:55, accumulated pauses: 1134 ms, max pause: 300 ms, pauses over 1000 ms: 0
03:32:00, accumulated pauses: 2324 ms, max pause: 424 ms, pauses over 1000 ms: 0
03:32:05, accumulated pauses: 1307 ms, max pause: 90 ms, pauses over 1000 ms: 0
03:32:10, accumulated pauses: 1262 ms, max pause: 111 ms, pauses over 1000 ms: 0
03:32:15, accumulated pauses: 1844 ms, max pause: 396 ms, pauses over 1000 ms: 0
03:32:20, accumulated pauses: 2292 ms, max pause: 425 ms, pauses over 1000 ms: 0
03:32:25, accumulated pauses: 1670 ms, max pause: 290 ms, pauses over 1000 ms: 0
03:32:30, accumulated pauses: 1421 ms, max pause: 353 ms, pauses over 1000 ms: 0
03:32:35, accumulated pauses: 1689 ms, max pause: 326 ms, pauses over 1000 ms: 0
03:32:40, accumulated pauses: 835 ms, max pause: 285 ms, pauses over 1000 ms: 0
03:32:45, accumulated pauses: 11 ms, max pause: 0 ms, pauses over 1000 ms: 0
```

</details>

**Comment by olukas** [comment]
Closing for now. Hiccups were pretty high and CPU usage for docker container was not configured properly after Jenkins restart. I will reopen it if this test will fail again.
