### ISSUE TITLE
HazelcastSerializationException: Failed to serialize.   Serializer has been already registered for type:

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#21648]
I see the exception thrown out, on a random basis.  many times i do not see the exception on every run.

could there be some race in registering serialisers ?

http://jenkins.hazelcast.com/view/stable/job/stable-x4/95/console

hz-bench-run-jenkins-stable hz/stress/swiss 

 
logs 1 failed run 
(base) [ec2-user@ip-10-0-0-252 swiss]$ ls  ~/workspace/issue-serialiser

```
com.hazelcast.nio.serialization.HazelcastSerializationException: Failed to serialize 'hzcmd.model.person.PersonExternalizable'
	at com.hazelcast.internal.serialization.impl.SerializationUtil.handleSerializeException(SerializationUtil.java:129)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:238)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:214)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toData(AbstractSerializationService.java:199)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toData(AbstractSerializationService.java:154)
	at com.hazelcast.client.impl.spi.ClientProxy.toData(ClientProxy.java:76)
	at com.hazelcast.client.impl.proxy.ClientMapProxy.putAllInternal(ClientMapProxy.java:1623)
	at com.hazelcast.client.impl.proxy.ClientMapProxy.setAll(ClientMapProxy.java:1587)
	at hzcmd.map.multi.SetAllStrPerson.timeStep(SetAllStrPerson.java:23)
	at remote.bench.marker.RollMarker.flatOut(RollMarker.java:72)
	at remote.bench.marker.RollMarker.bench(RollMarker.java:59)
	at remote.bench.BenchThread.call(BenchThread.java:41)
	at remote.bench.BenchThread.call(BenchThread.java:14)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IllegalStateException: Serializer[com.hazelcast.internal.serialization.impl.defaultserializers.JavaDefaultSerializers$ExternalizableSerializer@61a61e5a] has been already registered for type: class hzcmd.model.person.P
ersonExternalizable
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.safeRegister(AbstractSerializationService.java:501)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.registerFromSuperType(AbstractSerializationService.java:527)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.lookupCustomSerializer(AbstractSerializationService.java:635)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.serializerFor(AbstractSerializationService.java:572)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:227)
	... 17 more
com.hazelcast.nio.serialization.HazelcastSerializationException: Failed to serialize 'hzcmd.model.person.PersonExternalizable'
	at com.hazelcast.internal.serialization.impl.SerializationUtil.handleSerializeException(SerializationUtil.java:129)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:238)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:214)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toData(AbstractSerializationService.java:199)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toData(AbstractSerializationService.java:154)
	at com.hazelcast.client.impl.spi.ClientProxy.toData(ClientProxy.java:76)
	at com.hazelcast.client.impl.proxy.ClientMapProxy.putAllInternal(ClientMapProxy.java:1623)
	at com.hazelcast.client.impl.proxy.ClientMapProxy.setAll(ClientMapProxy.java:1587)
	at hzcmd.map.multi.SetAllStrPerson.timeStep(SetAllStrPerson.java:23)
	at remote.bench.marker.RollMarker.flatOut(RollMarker.java:72)
	at remote.bench.marker.RollMarker.bench(RollMarker.java:59)
	at remote.bench.BenchThread.call(BenchThread.java:41)
	at remote.bench.BenchThread.call(BenchThread.java:14)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IllegalStateException: Serializer[com.hazelcast.internal.serialization.impl.defaultserializers.JavaDefaultSerializers$ExternalizableSerializer@61a61e5a] has been already registered for type: class hzcmd.model.person.P
ersonExternalizable
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.safeRegister(AbstractSerializationService.java:501)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.registerFromSuperType(AbstractSerializationService.java:527)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.lookupCustomSerializer(AbstractSerializationService.java:635)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.serializerFor(AbstractSerializationService.java:572)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:227)
	... 17 more
```

**Comment by Danny-Hazelcast** [comment]
duplicate of https://github.com/hazelcast/hazelcast/issues/18408
