### ISSUE TITLE
com.hazelcast.internal.server.tcp.TcpServerConnectionManager_MemoryLeakTest.test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#21662]
_master_ (commit e8370b2db3b3ad114de71d6f5ff47a0751389b91)

Failed on Sonar build (Oracle JDK 11): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/1254/testReport/com.hazelcast.internal.server.tcp/TcpServerConnectionManager_MemoryLeakTest/test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet/

<details><summary>Stacktrace:</summary>

```
ava.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at com.hazelcast.internal.server.tcp.TcpServerConnectionManager_MemoryLeakTest.test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet(TcpServerConnectionManager_MemoryLeakTest.java:89)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

</details>

<details><summary>Standard output:</summary>

```
02:00:52,422  INFO |test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet| - [AbstractConfigLocator] test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet - Loading 'hazelcast-default.xml' from the classpath.
02:00:52,439  INFO |test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet| - [ExternalConfigurationOverride] test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet - Detected external configuration entries in environment variables: []
02:00:52,439  WARN |test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet| - [ExternalConfigurationOverride] test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet - Unrecognized environment variables configuration entries: [hazelcast.test.aws.instance.private.ip]
02:00:52,439  INFO |test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet| - [MetricsConfigHelper] test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet - [LOCAL] [dev] [5.2-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
02:00:52,440  INFO |test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet| - [logo] test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
02:00:52,440  INFO |test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet| - [system] test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Copyright (c) 2008-2022, Hazelcast, Inc. All Rights Reserved.
02:00:52,440  INFO |test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet| - [system] test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Hazelcast Platform 5.2-SNAPSHOT (20220621 - e8370b2) starting at [127.0.0.1]:5701
02:00:52,440  INFO |test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet| - [system] test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Cluster name: dev
02:00:52,440  INFO |test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet| - [system] test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed. For more information, see the documentation for Integrity Checker.
02:00:52,440  INFO |test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet| - [system] test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] The Jet engine is disabled.
To enable the Jet engine on the members, do one of the following:
  - Change member config using Java API: config.getJetConfig().setEnabled(true)
  - Change XML/YAML configuration property: Set hazelcast.jet.enabled to true
  - Add system property: -Dhz.jet.enabled=true (for Hazelcast embedded, works only when loading config via Config.load)
  - Add environment variable: HZ_JET_ENABLED=true (recommended when running container image. For Hazelcast embedded, works only when loading config via Config.load)
02:00:52,450  INFO |test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet| - [MetricsConfigHelper] test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
02:00:52,455  INFO |test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet| - [Node] test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Using Multicast discovery
02:00:52,455  WARN |test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet| - [CPSubsystem] test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
02:00:52,458  INFO |test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet| - [Diagnostics] test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
02:00:52,458  INFO |test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet| - [LifecycleService] test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] [127.0.0.1]:5701 is STARTING
02:00:54,846  INFO |test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet| - [ClusterService] test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] 

Members {size:1, ver:1} [
	Member [127.0.0.1]:5701 - b428f722-f98f-411b-8185-3643998a115e this
]

02:00:54,847  INFO |test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet| - [LifecycleService] test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] [127.0.0.1]:5701 is STARTED
02:00:54,848  INFO |test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet| - [AbstractConfigLocator] test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet - Loading 'hazelcast-default.xml' from the classpath.
02:00:54,877  INFO |test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet| - [ExternalConfigurationOverride] test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet - Detected external configuration entries in environment variables: []
02:00:54,877  WARN |test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet| - [ExternalConfigurationOverride] test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet - Unrecognized environment variables configuration entries: [hazelcast.test.aws.instance.private.ip]
02:00:54,878  INFO |test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet| - [MetricsConfigHelper] test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet - [LOCAL] [dev] [5.2-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
02:00:54,879  INFO |test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet| - [logo] test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
02:00:54,879  INFO |test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet| - [system] test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Copyright (c) 2008-2022, Hazelcast, Inc. All Rights Reserved.
02:00:54,879  INFO |test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet| - [system] test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Hazelcast Platform 5.2-SNAPSHOT (20220621 - e8370b2) starting at [127.0.0.1]:5702
02:00:54,879  INFO |test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet| - [system] test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Cluster name: dev
02:00:54,879  INFO |test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet| - [system] test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed. For more information, see the documentation for Integrity Checker.
02:00:54,879  INFO |test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet| - [system] test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] The Jet engine is disabled.
To enable the Jet engine on the members, do one of the following:
  - Change member config using Java API: config.getJetConfig().setEnabled(true)
  - Change XML/YAML configuration property: Set hazelcast.jet.enabled to true
  - Add system property: -Dhz.jet.enabled=true (for Hazelcast embedded, works only when loading config via Config.load)
  - Add environment variable: HZ_JET_ENABLED=true (recommended when running container image. For Hazelcast embedded, works only when loading config via Config.load)
02:00:54,884  INFO |test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet| - [MetricsConfigHelper] test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
02:00:54,892  INFO |test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet| - [Node] test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Using Multicast discovery
02:00:54,892  WARN |test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet| - [CPSubsystem] test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
02:00:54,900  INFO |test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet| - [Diagnostics] test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
02:00:54,900  INFO |test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet| - [LifecycleService] test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] [127.0.0.1]:5702 is STARTING
02:00:55,064  INFO |test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet| - [MulticastJoiner] test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Trying to join to discovered node: [127.0.0.1]:5701
02:00:55,065  INFO |test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet| - [TcpServerConnection] hz.condescending_spence.IO.thread-in-0 - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Initialized new cluster connection between /127.0.0.1:5701 and /127.0.0.1:39831
02:00:55,065  INFO |test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet| - [TcpServerConnection] hz.crazy_spence.IO.thread-in-0 - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Initialized new cluster connection between /0.0.0.0:39831 and /127.0.0.1:5701
02:00:56,166  INFO |test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet| - [ClusterService] hz.condescending_spence.priority-generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] 

Members {size:2, ver:2} [
	Member [127.0.0.1]:5701 - b428f722-f98f-411b-8185-3643998a115e this
	Member [127.0.0.1]:5702 - 7f12dff9-ccd2-4be9-90e7-cb7e2b30ad15
]

02:00:56,166  INFO |test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet| - [ClusterService] hz.crazy_spence.priority-generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] 

Members {size:2, ver:2} [
	Member [127.0.0.1]:5701 - b428f722-f98f-411b-8185-3643998a115e
	Member [127.0.0.1]:5702 - 7f12dff9-ccd2-4be9-90e7-cb7e2b30ad15 this
]

02:00:56,167  INFO |test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet| - [LifecycleService] test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] [127.0.0.1]:5702 is STARTED
02:00:56,167  INFO |test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet| - [LifecycleService] test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] [127.0.0.1]:5702 is SHUTTING_DOWN
02:00:56,168  INFO |test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet| - [Node] test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Shutting down multicast service...
02:00:56,168  INFO |test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet| - [Node] test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Shutting down connection manager...
02:00:56,169  INFO |test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet| - [TcpServerConnection] test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Connection[id=1, /0.0.0.0:39831->/127.0.0.1:5701, qualifier=null, endpoint=[127.0.0.1]:5701, remoteUuid=b428f722-f98f-411b-8185-3643998a115e, alive=false, connectionType=MEMBER, planeIndex=0] closed. Reason: TcpServer is stopping
02:00:56,169  INFO |test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet| - [TcpServerConnection] hz.condescending_spence.IO.thread-in-0 - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Connection[id=1, /127.0.0.1:5701->/127.0.0.1:39831, qualifier=null, endpoint=[127.0.0.1]:5702, remoteUuid=7f12dff9-ccd2-4be9-90e7-cb7e2b30ad15, alive=false, connectionType=MEMBER, planeIndex=-1] closed. Reason: Connection closed by the other side
02:00:56,169  INFO |test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet| - [Node] test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Shutting down node engine...
02:00:56,170  INFO |test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet| - [TcpServerConnector] hz.condescending_spence.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Connecting to /127.0.0.1:5702, timeout: 10000, bind-any: true
02:00:56,171  INFO |test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet| - [TcpServerConnector] hz.condescending_spence.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Could not connect to: /127.0.0.1:5702. Reason: IOException[Connection refused to address /127.0.0.1:5702]
02:00:56,173  INFO |test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet| - [NodeExtension] test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Destroying node NodeExtension.
02:00:56,173  INFO |test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet| - [Node] test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Hazelcast Shutdown is completed in 6 ms.
02:00:56,173  INFO |test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet| - [LifecycleService] test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] [127.0.0.1]:5702 is SHUTDOWN
02:00:56,271  INFO |test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet| - [TcpServerConnector] hz.condescending_spence.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Connecting to /127.0.0.1:5702, timeout: 10000, bind-any: true
02:00:56,271  INFO |test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet| - [TcpServerConnector] hz.condescending_spence.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Could not connect to: /127.0.0.1:5702. Reason: IOException[Connection refused to address /127.0.0.1:5702]
02:00:56,372  INFO |test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet| - [TcpServerConnector] hz.condescending_spence.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Connecting to /127.0.0.1:5702, timeout: 10000, bind-any: true
02:00:56,372  INFO |test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet| - [TcpServerConnector] hz.condescending_spence.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Could not connect to: /127.0.0.1:5702. Reason: IOException[Connection refused to address /127.0.0.1:5702]
02:00:56,472  INFO |test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet| - [TcpServerConnector] hz.condescending_spence.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Connecting to /127.0.0.1:5702, timeout: 10000, bind-any: true
02:00:56,473  INFO |test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet| - [TcpServerConnector] hz.condescending_spence.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Could not connect to: /127.0.0.1:5702. Reason: IOException[Connection refused to address /127.0.0.1:5702]
02:00:56,473  WARN |test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet| - [TcpServerConnectionErrorHandler] hz.condescending_spence.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Removing connection to endpoint [127.0.0.1]:5702 Cause => java.io.IOException {Connection refused to address /127.0.0.1:5702}, Error-Count: 5
02:00:56,473  INFO |test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet| - [MembershipManager] hz.condescending_spence.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Removing Member [127.0.0.1]:5702 - 7f12dff9-ccd2-4be9-90e7-cb7e2b30ad15
02:00:56,473  INFO |test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet| - [ClusterService] hz.condescending_spence.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] 

Members {size:1, ver:3} [
	Member [127.0.0.1]:5701 - b428f722-f98f-411b-8185-3643998a115e this
]

02:00:56,473  INFO |test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet| - [TransactionManagerService] hz.condescending_spence.cached.thread-1 - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Committing/rolling-back live transactions of [127.0.0.1]:5702, UUID: 7f12dff9-ccd2-4be9-90e7-cb7e2b30ad15
02:00:57,059  INFO |test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet| - [LifecycleService] main - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
02:00:57,059  INFO |test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet| - [Node] main - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Shutting down multicast service...
02:00:57,059  INFO |test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet| - [Node] main - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Shutting down connection manager...
02:00:57,060  INFO |test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet| - [Node] main - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Shutting down node engine...
02:00:57,064  INFO |test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet| - [NodeExtension] main - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Destroying node NodeExtension.
02:00:57,064  INFO |test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet| - [Node] main - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Hazelcast Shutdown is completed in 5 ms.
02:00:57,064  INFO |test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet| - [LifecycleService] main - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
BuildInfo right after test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet(com.hazelcast.internal.server.tcp.TcpServerConnectionManager_MemoryLeakTest): BuildInfo{version='5.2-SNAPSHOT', build='20220621', buildNumber=20220621, revision=e8370b2, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet(com.hazelcast.internal.server.tcp.TcpServerConnectionManager_MemoryLeakTest):'
02:00:50, accumulated pauses: 54 ms, max pause: 3 ms, pauses over 1000 ms: 0
02:00:55, accumulated pauses: 452 ms, max pause: 436 ms, pauses over 1000 ms: 0
```

</details>

**Comment by olukas** [comment]
Failed on IbmJDK8 in FIPS mode: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-IbmJDK8-fips-nightly/432/testReport/com.hazelcast.internal.server.tcp/TcpServerConnectionManager_MemoryLeakTest/test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet/

**Comment by olukas** [comment]
Failed on Sonar build (Oracle JDK 11): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/1259/testReport/com.hazelcast.internal.server.tcp/TcpServerConnectionManager_MemoryLeakTest/test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet/
