### ISSUE TITLE
Node fails to start when the other node in cluster is not running 

### ISSUE THREAD

**Issue by arushi315** [hazelcast/hazelcast#21677]
**Describe the bug**
I have a vertx application using Hazelcast clustering. 
I recently upgraded to vertx version 4.3.1 and so hazelcast version 4.2.2. 
I am deploying my service with clustering enabled for 2 nodes using tcpConfig with IP addresses added (multicast disabled). I bring up the service on the first node while service on the second node is not yet enabled. The service fails to start on the first node. 

Here is the log snippet: 
```
022-06-24 16:38:35.788+0000 ruag DEBUG (vert.x-worker-thread-0) [c.h.i.c.i.TcpIpJoiner] - [172.16.68.141]:5701 [myservice-acd778be-525a-4bfd-a5e2-2a248b729505-2.23.0-1] [4.2.2] Claiming myself as master node! Asking to endpoints: [[172.16.70.174]:5701]
2022-06-24 16:38:35.788+0000 ruag DEBUG (vert.x-worker-thread-0) [c.h.i.s.t.TcpServerConnectionManager] - [172.16.68.141]:5701 [myservice-acd778be-525a-4bfd-a5e2-2a248b729505-2.23.0-1] [4.2.2] Connection to: [172.16.70.174]:5701 streamId:-1 is already in progress
2022-06-24 16:38:35.788+0000 ruag DEBUG (vert.x-worker-thread-0) [c.h.i.s.t.TcpServerConnectionManager] - [172.16.68.141]:5701 [myservice-acd778be-525a-4bfd-a5e2-2a248b729505-2.23.0-1] [4.2.2] Connection to: [172.16.70.174]:5701 streamId:-1 is already in progress
2022-06-24 16:38:35.790+0000 ruag DEBUG (hz.crazy_tu.TcpServer.thread-1) [c.h.i.s.t.TcpServerConnectionManager] - [172.16.68.141]:5701 [myservice-acd778be-525a-4bfd-a5e2-2a248b729505-2.23.0-1] [4.2.2] Connection to: [172.16.70.174]:5701 streamId:-1 is already in progress
2022-06-24 16:38:35.888+0000 ruag DEBUG (hz.crazy_tu.TcpServer.thread-3) [c.h.i.s.t.TcpServerConnectionManager] - [172.16.68.141]:5701 [myservice-acd778be-525a-4bfd-a5e2-2a248b729505-2.23.0-1] [4.2.2] Connection to: [172.16.70.174]:5701 streamId:-1 is already in progress
2022-06-24 16:38:36.089+0000 ruag DEBUG (hz.crazy_tu.TcpServer.thread-3) [c.h.i.s.t.TcpServerConnectionManager] - [172.16.68.141]:5701 [myservice-acd778be-525a-4bfd-a5e2-2a248b729505-2.23.0-1] [4.2.2] Connection to: [172.16.70.174]:5701 streamId:-1 is already in progress
2022-06-24 16:38:36.389+0000 ruag DEBUG (hz.crazy_tu.TcpServer.thread-1) [c.h.i.s.t.TcpServerConnectionManager] - [172.16.68.141]:5701 [myservice-acd778be-525a-4bfd-a5e2-2a248b729505-2.23.0-1] [4.2.2] Connection to: [172.16.70.174]:5701 streamId:-1 is already in progress
2022-06-24 16:38:36.690+0000 ruag DEBUG (hz.crazy_tu.InvocationMonitorThread) [c.h.s.i.o.i.InvocationMonitor] - [172.16.68.141]:5701 [myservice-acd778be-525a-4bfd-a5e2-2a248b729505-2.23.0-1] [4.2.2] Invocations:2 timeouts:0 backup-timeouts:0
2022-06-24 16:38:36.790+0000 ruag DEBUG (hz.crazy_tu.TcpServer.thread-1) [c.h.i.s.t.TcpServerConnectionManager] - [172.16.68.141]:5701 [myservice-acd778be-525a-4bfd-a5e2-2a248b729505-2.23.0-1] [4.2.2] Connection to: [172.16.70.174]:5701 streamId:-1 is already in progress
2022-06-24 16:38:37.690+0000 ruag DEBUG (hz.crazy_tu.InvocationMonitorThread) [c.h.s.i.o.i.InvocationMonitor] - [172.16.68.141]:5701 [myservice-acd778be-525a-4bfd-a5e2-2a248b729505-2.23.0-1] [4.2.2] Invocations:2 timeouts:0 backup-timeouts:0
2022-06-24 16:38:38.690+0000 ruag DEBUG (hz.crazy_tu.InvocationMonitorThread) [c.h.s.i.o.i.InvocationMonitor] - [172.16.68.141]:5701 [myservice-acd778be-525a-4bfd-a5e2-2a248b729505-2.23.0-1] [4.2.2] Invocations:2 timeouts:0 backup-timeouts:0
2022-06-24 16:38:39.690+0000 ruag DEBUG (hz.crazy_tu.InvocationMonitorThread) [c.h.s.i.o.i.InvocationMonitor] - [172.16.68.141]:5701 [myservice-acd778be-525a-4bfd-a5e2-2a248b729505-2.23.0-1] [4.2.2] Invocations:2 timeouts:0 backup-timeouts:0
2022-06-24 16:38:40.690+0000 ruag DEBUG (hz.crazy_tu.InvocationMonitorThread) [c.h.s.i.o.i.InvocationMonitor] - [172.16.68.141]:5701 [myservice-acd778be-525a-4bfd-a5e2-2a248b729505-2.23.0-1] [4.2.2] Invocations:2 timeouts:0 backup-timeouts:0
2022-06-24 16:38:41.690+0000 ruag DEBUG (hz.crazy_tu.InvocationMonitorThread) [c.h.s.i.o.i.InvocationMonitor] - [172.16.68.141]:5701 [myservice-acd778be-525a-4bfd-a5e2-2a248b729505-2.23.0-1] [4.2.2] Invocations:2 timeouts:0 backup-timeouts:0
2022-06-24 16:38:42.690+0000 ruag DEBUG (hz.crazy_tu.InvocationMonitorThread) [c.h.s.i.o.i.InvocationMonitor] - [172.16.68.141]:5701 [myservice-acd778be-525a-4bfd-a5e2-2a248b729505-2.23.0-1] [4.2.2] Invocations:2 timeouts:0 backup-timeouts:0
2022-06-24 16:38:43.690+0000 ruag DEBUG (hz.crazy_tu.InvocationMonitorThread) [c.h.s.i.o.i.InvocationMonitor] - [172.16.68.141]:5701 [myservice-acd778be-525a-4bfd-a5e2-2a248b729505-2.23.0-1] [4.2.2] Invocations:2 timeouts:0 backup-timeouts:0
2022-06-24 16:38:44.690+0000 ruag DEBUG (hz.crazy_tu.InvocationMonitorThread) [c.h.s.i.o.i.InvocationMonitor] - [172.16.68.141]:5701 [myservice-acd778be-525a-4bfd-a5e2-2a248b729505-2.23.0-1] [4.2.2] Invocations:2 timeouts:0 backup-timeouts:0
2022-06-24 16:38:45.690+0000 ruag DEBUG (hz.crazy_tu.InvocationMonitorThread) [c.h.s.i.o.i.InvocationMonitor] - [172.16.68.141]:5701 [myservice-acd778be-525a-4bfd-a5e2-2a248b729505-2.23.0-1] [4.2.2] Invocations:2 timeouts:0 backup-timeouts:0
2022-06-24 16:38:45.789+0000 ruag DEBUG (vert.x-worker-thread-0) [c.h.i.c.i.TcpIpJoiner] - [172.16.68.141]:5701 [myservice-acd778be-525a-4bfd-a5e2-2a248b729505-2.23.0-1] [4.2.2] java.util.concurrent.TimeoutException: JoinMastershipClaimOp failed to complete within 9999991909 NANOSECONDS. Invocation{op=com.hazelcast.internal.cluster.impl.operations.JoinMastershipClaimOp{serviceName='hz:core:clusterService', identityHash=1854415116, partitionId=-1, replicaIndex=0, callId=2, invocationTime=1656088715788 (2022-06-24 16:38:35.788), waitTimeout=-1, callTimeout=60000, tenantControl=com.hazelcast.spi.impl.tenantcontrol.NoopTenantControl@0}, tryCount=1, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=60000, firstInvocationTimeMs=1656088715788, firstInvocationTime='2022-06-24 16:38:35.788', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 00:00:00.000', target=[172.16.70.174]:5701, pendingResponse={VOID}, backupsAcksExpected=-1, backupsAcksReceived=0, connection=null}
com.hazelcast.core.HazelcastException: java.util.concurrent.TimeoutException: JoinMastershipClaimOp failed to complete within 9999991909 NANOSECONDS. Invocation{op=com.hazelcast.internal.cluster.impl.operations.JoinMastershipClaimOp{serviceName='hz:core:clusterService', identityHash=1854415116, partitionId=-1, replicaIndex=0, callId=2, invocationTime=1656088715788 (2022-06-24 16:38:35.788), waitTimeout=-1, callTimeout=60000, tenantControl=com.hazelcast.spi.impl.tenantcontrol.NoopTenantControl@0}, tryCount=1, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=60000, firstInvocationTimeMs=1656088715788, firstInvocationTime='2022-06-24 16:38:35.788', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 00:00:00.000', target=[172.16.70.174]:5701, pendingResponse={VOID}, backupsAcksExpected=-1, backupsAcksReceived=0, connection=null}
	at com.hazelcast.internal.util.ExceptionUtil.lambda$static$0(ExceptionUtil.java:56)
	at com.hazelcast.internal.util.ExceptionUtil.peel(ExceptionUtil.java:134)
	at com.hazelcast.internal.util.ExceptionUtil.peel(ExceptionUtil.java:77)
	at com.hazelcast.internal.util.ExceptionUtil.rethrow(ExceptionUtil.java:139)
	at com.hazelcast.internal.util.FutureUtil$1.handleException(FutureUtil.java:53)
	at com.hazelcast.internal.util.FutureUtil.returnWithDeadline(FutureUtil.java:275)
	at com.hazelcast.internal.util.FutureUtil.returnWithDeadline(FutureUtil.java:240)
	at com.hazelcast.internal.cluster.impl.TcpIpJoiner.claimMastership(TcpIpJoiner.java:214)
	at com.hazelcast.internal.cluster.impl.TcpIpJoiner.tryClaimMastership(TcpIpJoiner.java:169)
	at com.hazelcast.internal.cluster.impl.TcpIpJoiner.joinViaPossibleMembers(TcpIpJoiner.java:155)
	at com.hazelcast.internal.cluster.impl.TcpIpJoiner.doJoin(TcpIpJoiner.java:96)
	at com.hazelcast.internal.cluster.impl.AbstractJoiner.join(AbstractJoiner.java:137)
	at com.hazelcast.instance.impl.Node.join(Node.java:810)
	at com.hazelcast.instance.impl.Node.start(Node.java:473)
	at com.hazelcast.instance.impl.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:123)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:211)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:190)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:128)
	at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:57)
	at io.vertx.spi.cluster.hazelcast.HazelcastClusterManager.lambda$join$1(HazelcastClusterManager.java:131)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$0(ContextImpl.java:159)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:101)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.util.concurrent.TimeoutException: JoinMastershipClaimOp failed to complete within 9999991909 NANOSECONDS. Invocation{op=com.hazelcast.internal.cluster.impl.operations.JoinMastershipClaimOp{serviceName='hz:core:clusterService', identityHash=1854415116, partitionId=-1, replicaIndex=0, callId=2, invocationTime=1656088715788 (2022-06-24 16:38:35.788), waitTimeout=-1, callTimeout=60000, tenantControl=com.hazelcast.spi.impl.tenantcontrol.NoopTenantControl@0}, tryCount=1, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=60000, firstInvocationTimeMs=1656088715788, firstInvocationTime='2022-06-24 16:38:35.788', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 00:00:00.000', target=[172.16.70.174]:5701, pendingResponse={VOID}, backupsAcksExpected=-1, backupsAcksReceived=0, connection=null}
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.newTimeoutException(InvocationFuture.java:85)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:656)
	at com.hazelcast.internal.util.FutureUtil.executeWithDeadline(FutureUtil.java:389)
	at com.hazelcast.internal.util.FutureUtil.returnWithDeadline(FutureUtil.java:270)
	... 22 common frames omitted
```

I tested the same scenario on previous version when the service was using vertx version 3.9.7 and Hazlecast version 3.12.2.
In this case, the service on the first node starts up fine. 

Log snippet: 
```
2022-06-25 22:36:08.190 uag-b39e40e0-563c-417f-ac9a-1e08a36ffa0e INFO (hz._hzInstance_1_SEG-abeb5ab2-8160-4161-b51d-17a3d03601d2-2.20.0.1-1.cached.thread-2) [c.h.n.t.TcpIpConnector] - [172.16.70.180]:5701 [myservice-abeb5ab2-8160-4161-b51d-17a3d03601d2-2.20.0.1-1] [3.12.2] Could not connect to: /172.16.70.177:5701. Reason: SocketException[Connection timed out to address /172.16.70.177:5701]
2022-06-25 22:36:08.193 uag-b39e40e0-563c-417f-ac9a-1e08a36ffa0e INFO (hz._hzInstance_1_SEG-abeb5ab2-8160-4161-b51d-17a3d03601d2-2.20.0.1-1.cached.thread-2) [c.h.c.i.TcpIpJoiner] - [172.16.70.180]:5701 [myservice-abeb5ab2-8160-4161-b51d-17a3d03601d2-2.20.0.1-1] [3.12.2] [172.16.70.177]:5701 is added to the blacklist.
2022-06-25 22:36:08.710 uag-b39e40e0-563c-417f-ac9a-1e08a36ffa0e DEBUG (vert.x-worker-thread-0) [c.h.c.i.TcpIpJoiner] - [172.16.70.180]:5701 [myservice-abeb5ab2-8160-4161-b51d-17a3d03601d2-2.20.0.1-1] [3.12.2] This node will assume master role since none of the possible members accepted join request.
2022-06-25 22:36:08.710 uag-b39e40e0-563c-417f-ac9a-1e08a36ffa0e DEBUG (vert.x-worker-thread-0) [c.h.i.c.ClusterService] - [172.16.70.180]:5701 [myservice-abeb5ab2-8160-4161-b51d-17a3d03601d2-2.20.0.1-1] [3.12.2] Setting master address to [172.16.70.180]:5701
```
 
**In both the versions, we set the property as `hazelcast.socket.connect.timeout.seconds=0`.**

**To Reproduce**

1. Create hazelcast configuration for 2 nodes with tcpConfig using IP addresses and set hazelcast.socket.connect.timeout.seconds=0. 
2. Start hazelcast on first node without starting it on the second node. 

Would appreciate any feedback and guidance on this. Please let me know if there is any other information that you require. 

Versions: 
Java - 11.0.15
Hazelcast - 4.2.2
Vertx - 4.3.1

**Comment by csongs** [comment]
I use hazelcast=5.2.2 and vertx=4.4.0 is work
But Use hazelcast=5.3.5 and vertx=4.5.7 is not work
I deploy on K8S 1.26
Use KUBERNETES_API
This is log
```
2024-04-22 10:00:31 INFO [vert.x-worker-thread-0] - [172.31.18.87]:5701 [dev] [5.3.5] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
2024-04-22 10:00:31 INFO [vert.x-worker-thread-0] - [172.31.18.87]:5701 [dev] [5.3.5] Copyright (c) 2008-2023, Hazelcast, Inc. All Rights Reserved.
2024-04-22 10:00:31 INFO [vert.x-worker-thread-0] - [172.31.18.87]:5701 [dev] [5.3.5] Hazelcast Platform 5.3.5 (20231024 - 0a8cc63) starting at [172.31.18.87]:5701
2024-04-22 10:00:31 INFO [vert.x-worker-thread-0] - [172.31.18.87]:5701 [dev] [5.3.5] Cluster name: dev
2024-04-22 10:00:31 INFO [vert.x-worker-thread-0] - [172.31.18.87]:5701 [dev] [5.3.5] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed. For more information, see the documentation for Integrity Checker.
2024-04-22 10:00:31 INFO [vert.x-worker-thread-0] - [172.31.18.87]:5701 [dev] [5.3.5] The Jet engine is disabled.
To enable the Jet engine on the members, do one of the following:
  - Change member config using Java API: config.getJetConfig().setEnabled(true)
  - Change XML/YAML configuration property: Set hazelcast.jet.enabled to true
  - Add system property: -Dhz.jet.enabled=true (for Hazelcast embedded, works only when loading config via Config.load)
  - Add environment variable: HZ_JET_ENABLED=true (recommended when running container image. For Hazelcast embedded, works only when loading config via Config.load)
2024-04-22 10:00:31 INFO [vert.x-worker-thread-0] - [172.31.18.87]:5701 [dev] [5.3.5] TPC: disabled
2024-04-22 10:00:32 INFO [vert.x-worker-thread-0] - [172.31.18.87]:5701 [dev] [5.3.5] Kubernetes Discovery properties: { service-dns: null, service-dns-timeout: 5, service-name: null, service-port: 0, service-label: null, service-label-value: true, namespace: onesch, pod-label: app, pod-label-value: onesch-app-dev, resolve-not-ready-addresses: true, expose-externally-mode: AUTO, use-node-name-as-external-address: false, service-per-pod-label: null, service-per-pod-label-value: null, kubernetes-api-retries: 3, kubernetes-master: https://kubernetes.default.svc}
2024-04-22 10:00:32 INFO [vert.x-worker-thread-0] - [172.31.18.87]:5701 [dev] [5.3.5] Kubernetes Discovery activated with mode: KUBERNETES_API
2024-04-22 10:00:32 INFO [vert.x-worker-thread-0] - [172.31.18.87]:5701 [dev] [5.3.5] Enable DEBUG/FINE log level for log category com.hazelcast.system.security  or use -Dhazelcast.security.recommendations system property to see 🔒 security recommendations and the status of current config.
2024-04-22 10:00:32 INFO [vert.x-worker-thread-0] - [172.31.18.87]:5701 [dev] [5.3.5] Using Discovery SPI
2024-04-22 10:00:32 WARN [vert.x-worker-thread-0] - [172.31.18.87]:5701 [dev] [5.3.5] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
2024-04-22 10:00:33 INFO [vert.x-worker-thread-0] - [172.31.18.87]:5701 [dev] [5.3.5] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
2024-04-22 10:00:33 INFO [vert.x-worker-thread-0] - [172.31.18.87]:5701 [dev] [5.3.5] [172.31.18.87]:5701 is STARTING
2024-04-22 10:00:33 INFO [vert.x-worker-thread-0] - [172.31.18.87]:5701 [dev] [5.3.5] Cannot fetch the current zone, ZONE_AWARE feature is disabled
2024-04-22 10:00:33 INFO [vert.x-worker-thread-0] - [172.31.18.87]:5701 [dev] [5.3.5] Kubernetes plugin discovered node name: XXXXXXX
2024-04-22 10:00:34 WARN [vert.x-worker-thread-0] - Cannot fetch public IPs of Hazelcast Member PODs, you won't be able to use Hazelcast Smart Client from outside of the Kubernetes network
2024-04-22 10:00:34 INFO [hz.onesch-worker-dev-5767f4d5f9-zp9br.cached.thread-2] - [172.31.18.87]:5701 [dev] [5.3.5] [172.31.18.87]:8081 is added to the blacklist.
```

**Comment by csongs** [comment]
I find it...

- k8s deployment
- before
  ```yaml
          ports:
          - containerPort: 8080
          - containerPort: 5701
  ```
- after
  ```yaml
        ports:
        - containerPort: 5701
        - containerPort: 8080
  ```
To run smoothly, 5701 port needs to be placed first. So, it's unrelated to Vert.x.
