### ISSUE TITLE
SQL exception defining mapping for static class

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast#21687]
**Describe the bug**
SQL Exception thrown
```
Exception in thread "main" com.hazelcast.sql.HazelcastSqlException: Unable to load class: 'neil.demo.Application.Data'
	at com.hazelcast.sql.impl.QueryUtils.toPublicException(QueryUtils.java:72)
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:206)
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:161)
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:157)
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:153)
	at com.hazelcast.sql.SqlService.execute(SqlService.java:89)
	at neil.demo.Application.main(Application.java:45)
```

**Expected behavior**
Mapping should be accepted.

**To Reproduce**

```
package neil.demo;

import java.io.Serializable;

import com.hazelcast.config.Config;
import com.hazelcast.core.Hazelcast;
import com.hazelcast.core.HazelcastInstance;

public class Application {
	private static final String MAP_NAME = "m";

	public static void main(String[] args) throws Exception {
		Config config = new Config();
		config.getJetConfig().setEnabled(true);
		HazelcastInstance hazelcastInstance = Hazelcast.newHazelcastInstance(config);

		String mapping = "CREATE MAPPING " + MAP_NAME
				+ " TYPE IMap "
                + " OPTIONS ( "
                + " 'keyFormat' = 'java',"
                + " 'keyJavaClass' = '" + String.class.getCanonicalName() + "',"
                + " 'valueFormat' = 'java',"
                + " 'valueJavaClass' = '" + Data.class.getCanonicalName() + "'"
                + " )";
		
		hazelcastInstance.getSql().execute(mapping);
		
		hazelcastInstance.shutdown();
	}
		
	@SuppressWarnings("serial")
	public static class Data implements Serializable {
		private int i;

		public int getI() {
			return i;
		}

		public void setI(int i) {
			this.i = i;
		}
	}
```

**Additional context**
Tested on above with 5.1.2

**Comment by viliam-durina** [comment]
Use `Data.class.getName()` instead of `Data.class.getCanonicalName()`. It returns `neil.demo.Application$Data` instead of `neil.demo.Application.Data`, which is what java reflection expects.
