### ISSUE TITLE
com.hazelcast.collection.impl.queue.QueueDestroyTest.checkStatsMapEntryRemovedWhenQueueDestroyed

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#21696]
_master_ (commit 68b73ea697ff72cd210b19f41479d07029455776)

Failed on Sonar build (Oracle JDK 11): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/1260/testReport/com.hazelcast.collection.impl.queue/QueueDestroyTest/checkStatsMapEntryRemovedWhenQueueDestroyed_instance_com_hazelcast_collection_impl_queue_QueueDestroyTest$$Lambda$273_0x00000001009fc040_26213322_/

It failed in variant `[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$273/0x00000001009fc040@26213322]`.

<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: expected:<0> but was:<1>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at com.hazelcast.collection.impl.queue.QueueDestroyTest.checkStatsMapEntryRemovedWhenQueueDestroyed(QueueDestroyTest.java:78)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

</details>

<details><summary>Standard output:</summary>

```
Started Running Test: checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$273/0x00000001009fc040@26213322]
21:56:50,130  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$273/0x00000001009fc040@26213322]| - [MetricsConfigHelper] checkStatsMapEntryRemovedWhenQueueDestroyed - [LOCAL] [dev] [5.2-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
21:56:50,131  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$273/0x00000001009fc040@26213322]| - [logo] checkStatsMapEntryRemovedWhenQueueDestroyed - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
21:56:50,131  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$273/0x00000001009fc040@26213322]| - [system] checkStatsMapEntryRemovedWhenQueueDestroyed - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Copyright (c) 2008-2022, Hazelcast, Inc. All Rights Reserved.
21:56:50,131  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$273/0x00000001009fc040@26213322]| - [system] checkStatsMapEntryRemovedWhenQueueDestroyed - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Hazelcast Platform 5.2-SNAPSHOT (20220627 - 68b73ea) starting at [127.0.0.1]:5702
21:56:50,131  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$273/0x00000001009fc040@26213322]| - [system] checkStatsMapEntryRemovedWhenQueueDestroyed - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Cluster name: dev
21:56:50,131  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$273/0x00000001009fc040@26213322]| - [system] checkStatsMapEntryRemovedWhenQueueDestroyed - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed. For more information, see the documentation for Integrity Checker.
21:56:50,131  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$273/0x00000001009fc040@26213322]| - [system] checkStatsMapEntryRemovedWhenQueueDestroyed - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Jet is enabled
21:56:50,134  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$273/0x00000001009fc040@26213322]| - [MetricsConfigHelper] checkStatsMapEntryRemovedWhenQueueDestroyed - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
21:56:50,137  WARN |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$273/0x00000001009fc040@26213322]| - [CPSubsystem] checkStatsMapEntryRemovedWhenQueueDestroyed - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
21:56:50,140  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$273/0x00000001009fc040@26213322]| - [JetServiceBackend] checkStatsMapEntryRemovedWhenQueueDestroyed - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Setting number of cooperative threads and default parallelism to 2
21:56:50,141  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$273/0x00000001009fc040@26213322]| - [Diagnostics] checkStatsMapEntryRemovedWhenQueueDestroyed - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
21:56:50,141  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$273/0x00000001009fc040@26213322]| - [LifecycleService] checkStatsMapEntryRemovedWhenQueueDestroyed - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] [127.0.0.1]:5702 is STARTING
21:56:50,141  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$273/0x00000001009fc040@26213322]| - [ClusterService] checkStatsMapEntryRemovedWhenQueueDestroyed - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] 

Members {size:1, ver:1} [
	Member [127.0.0.1]:5702 - 65248012-52c5-4a7e-89a2-fd4601f99e45 this
]

21:56:50,141  WARN |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$273/0x00000001009fc040@26213322]| - [Node] checkStatsMapEntryRemovedWhenQueueDestroyed - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Config seed port is 5701 and cluster size is 1. Some of the ports seem occupied!
21:56:50,141  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$273/0x00000001009fc040@26213322]| - [JobCoordinationService] checkStatsMapEntryRemovedWhenQueueDestroyed - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Jet started scanning for jobs
21:56:50,141 DEBUG |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$273/0x00000001009fc040@26213322]| - [JobCoordinationService] hz.hungry_golick.cached.thread-1 - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
21:56:50,141  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$273/0x00000001009fc040@26213322]| - [LifecycleService] checkStatsMapEntryRemovedWhenQueueDestroyed - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] [127.0.0.1]:5702 is STARTED
21:56:50,142  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$273/0x00000001009fc040@26213322]| - [MetricsConfigHelper] checkStatsMapEntryRemovedWhenQueueDestroyed - [LOCAL] [dev] [5.2-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
21:56:50,142  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$273/0x00000001009fc040@26213322]| - [logo] checkStatsMapEntryRemovedWhenQueueDestroyed - [127.0.0.1]:5703 [dev] [5.2-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
21:56:50,142  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$273/0x00000001009fc040@26213322]| - [system] checkStatsMapEntryRemovedWhenQueueDestroyed - [127.0.0.1]:5703 [dev] [5.2-SNAPSHOT] Copyright (c) 2008-2022, Hazelcast, Inc. All Rights Reserved.
21:56:50,142  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$273/0x00000001009fc040@26213322]| - [system] checkStatsMapEntryRemovedWhenQueueDestroyed - [127.0.0.1]:5703 [dev] [5.2-SNAPSHOT] Hazelcast Platform 5.2-SNAPSHOT (20220627 - 68b73ea) starting at [127.0.0.1]:5703
21:56:50,142  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$273/0x00000001009fc040@26213322]| - [system] checkStatsMapEntryRemovedWhenQueueDestroyed - [127.0.0.1]:5703 [dev] [5.2-SNAPSHOT] Cluster name: dev
21:56:50,142  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$273/0x00000001009fc040@26213322]| - [system] checkStatsMapEntryRemovedWhenQueueDestroyed - [127.0.0.1]:5703 [dev] [5.2-SNAPSHOT] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed. For more information, see the documentation for Integrity Checker.
21:56:50,142  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$273/0x00000001009fc040@26213322]| - [system] checkStatsMapEntryRemovedWhenQueueDestroyed - [127.0.0.1]:5703 [dev] [5.2-SNAPSHOT] Jet is enabled
21:56:50,147  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$273/0x00000001009fc040@26213322]| - [MetricsConfigHelper] checkStatsMapEntryRemovedWhenQueueDestroyed - [127.0.0.1]:5703 [dev] [5.2-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
21:56:50,154  WARN |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$273/0x00000001009fc040@26213322]| - [CPSubsystem] checkStatsMapEntryRemovedWhenQueueDestroyed - [127.0.0.1]:5703 [dev] [5.2-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
21:56:50,159  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$273/0x00000001009fc040@26213322]| - [JetServiceBackend] checkStatsMapEntryRemovedWhenQueueDestroyed - [127.0.0.1]:5703 [dev] [5.2-SNAPSHOT] Setting number of cooperative threads and default parallelism to 2
21:56:50,161  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$273/0x00000001009fc040@26213322]| - [Diagnostics] checkStatsMapEntryRemovedWhenQueueDestroyed - [127.0.0.1]:5703 [dev] [5.2-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
21:56:50,161  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$273/0x00000001009fc040@26213322]| - [LifecycleService] checkStatsMapEntryRemovedWhenQueueDestroyed - [127.0.0.1]:5703 [dev] [5.2-SNAPSHOT] [127.0.0.1]:5703 is STARTING
21:56:50,162  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$273/0x00000001009fc040@26213322]| - [MockServer] checkStatsMapEntryRemovedWhenQueueDestroyed - [127.0.0.1]:5703 [dev] [5.2-SNAPSHOT] Created connection to endpoint: [127.0.0.1]:5702-65248012-52c5-4a7e-89a2-fd4601f99e45, connection: MockConnection{localEndpoint=[address=[127.0.0.1]:5703, uuid=aab0a255-2807-41a2-ba8e-879c188cf962], remoteEndpoint=[address=[127.0.0.1]:5702, uuid=65248012-52c5-4a7e-89a2-fd4601f99e45], alive=true}
21:56:50,162  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$273/0x00000001009fc040@26213322]| - [MockServer] hz.hungry_golick.priority-generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Created connection to endpoint: [127.0.0.1]:5703-aab0a255-2807-41a2-ba8e-879c188cf962, connection: MockConnection{localEndpoint=[address=[127.0.0.1]:5702, uuid=65248012-52c5-4a7e-89a2-fd4601f99e45], remoteEndpoint=[address=[127.0.0.1]:5703, uuid=aab0a255-2807-41a2-ba8e-879c188cf962], alive=true}
21:56:50,163  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$273/0x00000001009fc040@26213322]| - [ClusterService] hz.hungry_golick.priority-generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] 

Members {size:2, ver:2} [
	Member [127.0.0.1]:5702 - 65248012-52c5-4a7e-89a2-fd4601f99e45 this
	Member [127.0.0.1]:5703 - aab0a255-2807-41a2-ba8e-879c188cf962
]

21:56:50,241 DEBUG |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$273/0x00000001009fc040@26213322]| - [JobCoordinationService] hz.hungry_golick.cached.thread-3 - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
21:56:50,263  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$273/0x00000001009fc040@26213322]| - [ClusterService] hz.distracted_golick.generic-operation.thread-1 - [127.0.0.1]:5703 [dev] [5.2-SNAPSHOT] 

Members {size:2, ver:2} [
	Member [127.0.0.1]:5702 - 65248012-52c5-4a7e-89a2-fd4601f99e45
	Member [127.0.0.1]:5703 - aab0a255-2807-41a2-ba8e-879c188cf962 this
]

21:56:50,263  WARN |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$273/0x00000001009fc040@26213322]| - [Node] checkStatsMapEntryRemovedWhenQueueDestroyed - [127.0.0.1]:5703 [dev] [5.2-SNAPSHOT] Config seed port is 5701 and cluster size is 2. Some of the ports seem occupied!
21:56:50,263  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$273/0x00000001009fc040@26213322]| - [JobCoordinationService] checkStatsMapEntryRemovedWhenQueueDestroyed - [127.0.0.1]:5703 [dev] [5.2-SNAPSHOT] Jet started scanning for jobs
21:56:50,264  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$273/0x00000001009fc040@26213322]| - [LifecycleService] checkStatsMapEntryRemovedWhenQueueDestroyed - [127.0.0.1]:5703 [dev] [5.2-SNAPSHOT] [127.0.0.1]:5703 is STARTED
21:56:50,264  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$273/0x00000001009fc040@26213322]| - [PartitionStateManager] hz.hungry_golick.generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Initializing cluster partition table arrangement...
21:56:50,265  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$273/0x00000001009fc040@26213322]| - [HealthMonitor] hz.distracted_golick.HealthMonitor - [127.0.0.1]:5703 [dev] [5.2-SNAPSHOT] processors=8, physical.memory.total=755.8G, physical.memory.free=238.5G, swap.space.total=8.0G, swap.space.free=8.0G, heap.memory.used=294.3M, heap.memory.free=367.7M, heap.memory.total=662.0M, heap.memory.max=2.0G, heap.memory.used/total=44.43%, heap.memory.used/max=14.36%, minor.gc.count=145, minor.gc.time=2374ms, major.gc.count=0, major.gc.time=0ms, load.process=0.00%, load.system=0.00%, load.systemAverage=8.45, thread.count=67, thread.peakCount=1796, cluster.timeDiff=-1, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=20, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=1, clientEndpoint.count=0, connection.active.count=0, client.connection.count=0, connection.count=0
21:56:50,605 DEBUG |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$273/0x00000001009fc040@26213322]| - [JobRepository] hz.hungry_golick.cached.thread-3 - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Job cleanup took 0ms
21:56:50,607  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$273/0x00000001009fc040@26213322]| - [LifecycleService] main - [127.0.0.1]:5703 [dev] [5.2-SNAPSHOT] [127.0.0.1]:5703 is SHUTTING_DOWN
21:56:50,607  WARN |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$273/0x00000001009fc040@26213322]| - [Node] main - [127.0.0.1]:5703 [dev] [5.2-SNAPSHOT] Terminating forcefully...
21:56:50,607  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$273/0x00000001009fc040@26213322]| - [Node] main - [127.0.0.1]:5703 [dev] [5.2-SNAPSHOT] Shutting down connection manager...
21:56:50,608  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$273/0x00000001009fc040@26213322]| - [MockServer] main - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Removed connection to endpoint: [address=[127.0.0.1]:5703, uuid=aab0a255-2807-41a2-ba8e-879c188cf962], connection: MockConnection{localEndpoint=[address=[127.0.0.1]:5702, uuid=65248012-52c5-4a7e-89a2-fd4601f99e45], remoteEndpoint=[address=[127.0.0.1]:5703, uuid=aab0a255-2807-41a2-ba8e-879c188cf962], alive=false}
21:56:50,608  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$273/0x00000001009fc040@26213322]| - [MockServer] main - [127.0.0.1]:5703 [dev] [5.2-SNAPSHOT] Removed connection to endpoint: [address=[127.0.0.1]:5702, uuid=65248012-52c5-4a7e-89a2-fd4601f99e45], connection: MockConnection{localEndpoint=[address=[127.0.0.1]:5703, uuid=aab0a255-2807-41a2-ba8e-879c188cf962], remoteEndpoint=[address=[127.0.0.1]:5702, uuid=65248012-52c5-4a7e-89a2-fd4601f99e45], alive=false}
21:56:50,608  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$273/0x00000001009fc040@26213322]| - [MembershipManager] main - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Removing Member [127.0.0.1]:5703 - aab0a255-2807-41a2-ba8e-879c188cf962
21:56:50,608  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$273/0x00000001009fc040@26213322]| - [PartitionStateManager] main - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Storing snapshot of partition assignments while removing UUID aab0a255-2807-41a2-ba8e-879c188cf962
21:56:50,608  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$273/0x00000001009fc040@26213322]| - [ClusterService] main - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] 

Members {size:1, ver:3} [
	Member [127.0.0.1]:5702 - 65248012-52c5-4a7e-89a2-fd4601f99e45 this
]

21:56:50,608  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$273/0x00000001009fc040@26213322]| - [Node] main - [127.0.0.1]:5703 [dev] [5.2-SNAPSHOT] Shutting down node engine...
21:56:50,608  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$273/0x00000001009fc040@26213322]| - [TransactionManagerService] hz.hungry_golick.cached.thread-3 - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Committing/rolling-back live transactions of [127.0.0.1]:5703, UUID: aab0a255-2807-41a2-ba8e-879c188cf962
21:56:50,610  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$273/0x00000001009fc040@26213322]| - [MigrationManager] hz.hungry_golick.migration - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Partition balance is ok, no need to repartition.
21:56:50,611  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$273/0x00000001009fc040@26213322]| - [NodeExtension] main - [127.0.0.1]:5703 [dev] [5.2-SNAPSHOT] Destroying node NodeExtension.
21:56:50,611  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$273/0x00000001009fc040@26213322]| - [Node] main - [127.0.0.1]:5703 [dev] [5.2-SNAPSHOT] Hazelcast Shutdown is completed in 4 ms.
21:56:50,611  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$273/0x00000001009fc040@26213322]| - [LifecycleService] main - [127.0.0.1]:5703 [dev] [5.2-SNAPSHOT] [127.0.0.1]:5703 is SHUTDOWN
21:56:50,611  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$273/0x00000001009fc040@26213322]| - [LifecycleService] main - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] [127.0.0.1]:5702 is SHUTTING_DOWN
21:56:50,611  WARN |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$273/0x00000001009fc040@26213322]| - [Node] main - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Terminating forcefully...
21:56:50,611  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$273/0x00000001009fc040@26213322]| - [Node] main - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Shutting down connection manager...
21:56:50,611  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$273/0x00000001009fc040@26213322]| - [Node] main - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Shutting down node engine...
21:56:50,613  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$273/0x00000001009fc040@26213322]| - [NodeExtension] main - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Destroying node NodeExtension.
21:56:50,613  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$273/0x00000001009fc040@26213322]| - [Node] main - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Hazelcast Shutdown is completed in 2 ms.
21:56:50,613  INFO |checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$273/0x00000001009fc040@26213322]| - [LifecycleService] main - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] [127.0.0.1]:5702 is SHUTDOWN
BuildInfo right after checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$273/0x00000001009fc040@26213322](com.hazelcast.collection.impl.queue.QueueDestroyTest): BuildInfo{version='5.2-SNAPSHOT', build='20220627', buildNumber=20220627, revision=68b73ea, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'checkStatsMapEntryRemovedWhenQueueDestroyed[instance=com.hazelcast.collection.impl.queue.QueueDestroyTest$$Lambda$273/0x00000001009fc040@26213322](com.hazelcast.collection.impl.queue.QueueDestroyTest):'
21:56:50, accumulated pauses: 263 ms, max pause: 261 ms, pauses over 1000 ms: 0
```

</details>

**Comment by olukas** [comment]
Failed on Sonar build (Oracle JDK 11): http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/1293/testReport/com.hazelcast.collection.impl.queue/QueueDestroyTest/checkStatsMapEntryRemovedWhenQueueDestroyed_instance_com_hazelcast_collection_impl_queue_QueueDestroyTest$$Lambda$1013_0x0000000100f49440_494810cc_/

**Comment by olukas** [comment]
Failed on `5.1.z` branch on OracleJDK17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-OracleJDK17/23/testReport/com.hazelcast.collection.impl.queue/QueueDestroyTest/checkStatsMapEntryRemovedWhenQueueDestroyed_instance_com_hazelcast_collection_impl_queue_QueueDestroyTest$$Lambda$995_0x00000008016927a0_50d02417_/

**Comment by ahmetmircik** [comment]
failed again for 5.1.z branch: https://github.com/hazelcast/hazelcast/pull/23105#issuecomment-1340814838

**Comment by ahmetmircik** [comment]
@krzysztofslusarski can you please backport your fix to 5.1.z?

**Comment by krzysztofslusarski** [comment]
@ahmetmircik https://github.com/hazelcast/hazelcast/pull/23147, enjoy

**Comment by ahmetmircik** [comment]
closed by https://github.com/hazelcast/hazelcast/pull/23147
