### ISSUE TITLE
com.hazelcast.internal.ascii.RestNodeStateTest.testNodeStateAvailable_whenOtherMemberUnavailable

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#21793]
_master_ (commit 318dfa882360ff196956c820c95f04b6b3590d29)

Failed on OracleJDK11: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-OracleJDK11/329/testReport/com.hazelcast.internal.ascii/RestNodeStateTest/testNodeStateAvailable_whenOtherMemberUnavailable/

<details><summary>Stacktrace:</summary>

```
org.junit.runners.model.TestTimedOutException: test timed out after 30000 milliseconds
	at java.base@11.0.13/java.lang.Thread.sleep(Native Method)
	at app//com.hazelcast.internal.cluster.impl.MulticastJoiner.findMasterWithMulticast(MulticastJoiner.java:184)
	at app//com.hazelcast.internal.cluster.impl.MulticastJoiner.doJoin(MulticastJoiner.java:68)
	at app//com.hazelcast.internal.cluster.impl.AbstractJoiner.join(AbstractJoiner.java:139)
	at app//com.hazelcast.instance.impl.Node.join(Node.java:826)
	at app//com.hazelcast.instance.impl.Node.start(Node.java:484)
	at app//com.hazelcast.instance.impl.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:124)
	at app//com.hazelcast.instance.impl.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:217)
	at app//com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:196)
	at app//com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:134)
	at app//com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:61)
	at app//com.hazelcast.internal.ascii.RestNodeStateTest.testNodeStateAvailable_whenOtherMemberUnavailable(RestNodeStateTest.java:106)
	at java.base@11.0.13/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@11.0.13/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base@11.0.13/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@11.0.13/java.lang.reflect.Method.invoke(Method.java:566)
	at app//org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at app//org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at app//org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at app//org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at app//com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at app//com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base@11.0.13/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base@11.0.13/java.lang.Thread.run(Thread.java:834)
```

</details>

<details><summary>Standard output:</summary>

```
23:56:29,348  INFO |testNodeStateAvailable_whenOtherMemberUnavailable| - [MetricsConfigHelper] testNodeStateAvailable_whenOtherMemberUnavailable - [LOCAL] [dev] [5.2-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
23:56:29,349  INFO |testNodeStateAvailable_whenOtherMemberUnavailable| - [logo] testNodeStateAvailable_whenOtherMemberUnavailable - [127.0.0.1]:5600 [dev] [5.2-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
23:56:29,349  INFO |testNodeStateAvailable_whenOtherMemberUnavailable| - [system] testNodeStateAvailable_whenOtherMemberUnavailable - [127.0.0.1]:5600 [dev] [5.2-SNAPSHOT] Copyright (c) 2008-2022, Hazelcast, Inc. All Rights Reserved.
23:56:29,349  INFO |testNodeStateAvailable_whenOtherMemberUnavailable| - [system] testNodeStateAvailable_whenOtherMemberUnavailable - [127.0.0.1]:5600 [dev] [5.2-SNAPSHOT] Hazelcast Platform 5.2-SNAPSHOT (20220716 - 318dfa8) starting at [127.0.0.1]:5600
23:56:29,350  INFO |testNodeStateAvailable_whenOtherMemberUnavailable| - [system] testNodeStateAvailable_whenOtherMemberUnavailable - [127.0.0.1]:5600 [dev] [5.2-SNAPSHOT] Cluster name: dev
23:56:29,350  INFO |testNodeStateAvailable_whenOtherMemberUnavailable| - [system] testNodeStateAvailable_whenOtherMemberUnavailable - [127.0.0.1]:5600 [dev] [5.2-SNAPSHOT] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed. For more information, see the documentation for Integrity Checker.
23:56:29,350  INFO |testNodeStateAvailable_whenOtherMemberUnavailable| - [system] testNodeStateAvailable_whenOtherMemberUnavailable - [127.0.0.1]:5600 [dev] [5.2-SNAPSHOT] Jet is enabled
23:56:29,354  INFO |testNodeStateAvailable_whenOtherMemberUnavailable| - [MetricsConfigHelper] testNodeStateAvailable_whenOtherMemberUnavailable - [127.0.0.1]:5600 [dev] [5.2-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
23:56:29,360  INFO |testNodeStateAvailable_whenOtherMemberUnavailable| - [Node] testNodeStateAvailable_whenOtherMemberUnavailable - [127.0.0.1]:5600 [dev] [5.2-SNAPSHOT] Using Multicast discovery
23:56:29,360  WARN |testNodeStateAvailable_whenOtherMemberUnavailable| - [CPSubsystem] testNodeStateAvailable_whenOtherMemberUnavailable - [127.0.0.1]:5600 [dev] [5.2-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
23:56:29,363  INFO |testNodeStateAvailable_whenOtherMemberUnavailable| - [JetServiceBackend] testNodeStateAvailable_whenOtherMemberUnavailable - [127.0.0.1]:5600 [dev] [5.2-SNAPSHOT] Setting number of cooperative threads and default parallelism to 2
23:56:29,365  INFO |testNodeStateAvailable_whenOtherMemberUnavailable| - [Diagnostics] testNodeStateAvailable_whenOtherMemberUnavailable - [127.0.0.1]:5600 [dev] [5.2-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
23:56:29,365  INFO |testNodeStateAvailable_whenOtherMemberUnavailable| - [LifecycleService] testNodeStateAvailable_whenOtherMemberUnavailable - [127.0.0.1]:5600 [dev] [5.2-SNAPSHOT] [127.0.0.1]:5600 is STARTING
23:56:44,020  INFO |testNodeStateAvailable_whenOtherMemberUnavailable| - [MulticastJoiner] testNodeStateAvailable_whenOtherMemberUnavailable - [127.0.0.1]:5600 [dev] [5.2-SNAPSHOT] Trying to join to discovered node: [127.0.0.1]:5701
23:56:44,021  INFO |testNodeStateAvailable_whenOtherMemberUnavailable| - [MulticastJoiner] hz.friendly_moser.cached.thread-3 - [127.0.0.1]:5600 [dev] [5.2-SNAPSHOT] [127.0.0.1]:5701 is added to the blacklist.
23:56:59,348  WARN |testNodeStateAvailable_whenOtherMemberUnavailable| - [MulticastJoiner] testNodeStateAvailable_whenOtherMemberUnavailable - [127.0.0.1]:5600 [dev] [5.2-SNAPSHOT] sleep interrupted
java.lang.InterruptedException: sleep interrupted
	at java.lang.Thread.sleep(Native Method) ~[?:?]
	at com.hazelcast.internal.cluster.impl.MulticastJoiner.findMasterWithMulticast(MulticastJoiner.java:184) [classes/:?]
	at com.hazelcast.internal.cluster.impl.MulticastJoiner.doJoin(MulticastJoiner.java:68) [classes/:?]
	at com.hazelcast.internal.cluster.impl.AbstractJoiner.join(AbstractJoiner.java:139) [classes/:?]
	at com.hazelcast.instance.impl.Node.join(Node.java:826) [classes/:?]
	at com.hazelcast.instance.impl.Node.start(Node.java:484) [classes/:?]
	at com.hazelcast.instance.impl.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:124) [classes/:?]
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:217) [classes/:?]
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:196) [classes/:?]
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:134) [classes/:?]
	at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:61) [classes/:?]
	at com.hazelcast.internal.ascii.RestNodeStateTest.testNodeStateAvailable_whenOtherMemberUnavailable(RestNodeStateTest.java:106) [test-classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59) [junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56) [junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) [junit-4.13.2.jar:4.13.2]
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115) [test-classes/:?]
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107) [test-classes/:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
23:56:59,765  INFO |testNodeStateAvailable_whenOtherMemberUnavailable| - [ClusterService] testNodeStateAvailable_whenOtherMemberUnavailable - [127.0.0.1]:5600 [dev] [5.2-SNAPSHOT] 

Members {size:1, ver:1} [
	Member [127.0.0.1]:5600 - 51e4d09f-db5b-4855-9335-0135de223cb8 this
]

23:56:59,765  INFO |testNodeStateAvailable_whenOtherMemberUnavailable| - [JobCoordinationService] testNodeStateAvailable_whenOtherMemberUnavailable - [127.0.0.1]:5600 [dev] [5.2-SNAPSHOT] Jet started scanning for jobs
23:56:59,767 DEBUG |testNodeStateAvailable_whenOtherMemberUnavailable| - [JobCoordinationService] hz.friendly_moser.cached.thread-10 - [127.0.0.1]:5600 [dev] [5.2-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
23:56:59,767  INFO |testNodeStateAvailable_whenOtherMemberUnavailable| - [LifecycleService] testNodeStateAvailable_whenOtherMemberUnavailable - [127.0.0.1]:5600 [dev] [5.2-SNAPSHOT] [127.0.0.1]:5600 is STARTED
23:56:59,769  INFO |testNodeStateAvailable_whenOtherMemberUnavailable| - [MetricsConfigHelper] testNodeStateAvailable_whenOtherMemberUnavailable - [LOCAL] [dev] [5.2-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
23:56:59,770  INFO |testNodeStateAvailable_whenOtherMemberUnavailable| - [logo] testNodeStateAvailable_whenOtherMemberUnavailable - [127.0.0.1]:5601 [dev] [5.2-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
23:56:59,770  INFO |testNodeStateAvailable_whenOtherMemberUnavailable| - [system] testNodeStateAvailable_whenOtherMemberUnavailable - [127.0.0.1]:5601 [dev] [5.2-SNAPSHOT] Copyright (c) 2008-2022, Hazelcast, Inc. All Rights Reserved.
23:56:59,770  INFO |testNodeStateAvailable_whenOtherMemberUnavailable| - [system] testNodeStateAvailable_whenOtherMemberUnavailable - [127.0.0.1]:5601 [dev] [5.2-SNAPSHOT] Hazelcast Platform 5.2-SNAPSHOT (20220716 - 318dfa8) starting at [127.0.0.1]:5601
23:56:59,770  INFO |testNodeStateAvailable_whenOtherMemberUnavailable| - [system] testNodeStateAvailable_whenOtherMemberUnavailable - [127.0.0.1]:5601 [dev] [5.2-SNAPSHOT] Cluster name: dev
23:56:59,770  INFO |testNodeStateAvailable_whenOtherMemberUnavailable| - [system] testNodeStateAvailable_whenOtherMemberUnavailable - [127.0.0.1]:5601 [dev] [5.2-SNAPSHOT] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed. For more information, see the documentation for Integrity Checker.
23:56:59,770  INFO |testNodeStateAvailable_whenOtherMemberUnavailable| - [system] testNodeStateAvailable_whenOtherMemberUnavailable - [127.0.0.1]:5601 [dev] [5.2-SNAPSHOT] Jet is enabled
23:56:59,771 DEBUG |testNodeStateAvailable_whenOtherMemberUnavailable| - [JobCoordinationService] hz.friendly_moser.cached.thread-5 - [127.0.0.1]:5600 [dev] [5.2-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
23:56:59,776  INFO |testNodeStateAvailable_whenOtherMemberUnavailable| - [MetricsConfigHelper] testNodeStateAvailable_whenOtherMemberUnavailable - [127.0.0.1]:5601 [dev] [5.2-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
23:56:59,781  INFO |testNodeStateAvailable_whenOtherMemberUnavailable| - [Node] testNodeStateAvailable_whenOtherMemberUnavailable - [127.0.0.1]:5601 [dev] [5.2-SNAPSHOT] Using Multicast discovery
23:56:59,781  WARN |testNodeStateAvailable_whenOtherMemberUnavailable| - [CPSubsystem] testNodeStateAvailable_whenOtherMemberUnavailable - [127.0.0.1]:5601 [dev] [5.2-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
23:56:59,783  INFO |testNodeStateAvailable_whenOtherMemberUnavailable| - [JetServiceBackend] testNodeStateAvailable_whenOtherMemberUnavailable - [127.0.0.1]:5601 [dev] [5.2-SNAPSHOT] Setting number of cooperative threads and default parallelism to 2
23:56:59,784  INFO |testNodeStateAvailable_whenOtherMemberUnavailable| - [Diagnostics] testNodeStateAvailable_whenOtherMemberUnavailable - [127.0.0.1]:5601 [dev] [5.2-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
23:56:59,785  INFO |testNodeStateAvailable_whenOtherMemberUnavailable| - [LifecycleService] testNodeStateAvailable_whenOtherMemberUnavailable - [127.0.0.1]:5601 [dev] [5.2-SNAPSHOT] [127.0.0.1]:5601 is STARTING
23:56:59,845  INFO |testNodeStateAvailable_whenOtherMemberUnavailable| - [MulticastJoiner] testNodeStateAvailable_whenOtherMemberUnavailable - [127.0.0.1]:5601 [dev] [5.2-SNAPSHOT] Trying to join to discovered node: [127.0.0.1]:5600
23:56:59,846  INFO |testNodeStateAvailable_whenOtherMemberUnavailable| - [TcpServerConnection] hz.friendly_moser.IO.thread-in-2 - [127.0.0.1]:5600 [dev] [5.2-SNAPSHOT] Initialized new cluster connection between /127.0.0.1:5600 and /127.0.0.1:50613
23:56:59,846  INFO |testNodeStateAvailable_whenOtherMemberUnavailable| - [TcpServerConnection] hz.unruffled_moser.IO.thread-in-0 - [127.0.0.1]:5601 [dev] [5.2-SNAPSHOT] Initialized new cluster connection between /0.0.0.0:50613 and /127.0.0.1:5600
23:56:59,871 DEBUG |testNodeStateAvailable_whenOtherMemberUnavailable| - [JobCoordinationService] hz.friendly_moser.cached.thread-9 - [127.0.0.1]:5600 [dev] [5.2-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
23:56:59,971 DEBUG |testNodeStateAvailable_whenOtherMemberUnavailable| - [JobCoordinationService] hz.friendly_moser.cached.thread-9 - [127.0.0.1]:5600 [dev] [5.2-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
23:57:00,071 DEBUG |testNodeStateAvailable_whenOtherMemberUnavailable| - [JobCoordinationService] hz.friendly_moser.cached.thread-9 - [127.0.0.1]:5600 [dev] [5.2-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
23:57:00,171 DEBUG |testNodeStateAvailable_whenOtherMemberUnavailable| - [JobCoordinationService] hz.friendly_moser.cached.thread-9 - [127.0.0.1]:5600 [dev] [5.2-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
23:57:00,271 DEBUG |testNodeStateAvailable_whenOtherMemberUnavailable| - [JobCoordinationService] hz.friendly_moser.cached.thread-9 - [127.0.0.1]:5600 [dev] [5.2-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
23:57:00,371 DEBUG |testNodeStateAvailable_whenOtherMemberUnavailable| - [JobCoordinationService] hz.friendly_moser.cached.thread-7 - [127.0.0.1]:5600 [dev] [5.2-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
23:57:00,471 DEBUG |testNodeStateAvailable_whenOtherMemberUnavailable| - [JobCoordinationService] hz.friendly_moser.cached.thread-7 - [127.0.0.1]:5600 [dev] [5.2-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
23:57:00,572 DEBUG |testNodeStateAvailable_whenOtherMemberUnavailable| - [JobCoordinationService] hz.friendly_moser.cached.thread-7 - [127.0.0.1]:5600 [dev] [5.2-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
23:57:00,672 DEBUG |testNodeStateAvailable_whenOtherMemberUnavailable| - [JobCoordinationService] hz.friendly_moser.cached.thread-7 - [127.0.0.1]:5600 [dev] [5.2-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
23:57:00,772 DEBUG |testNodeStateAvailable_whenOtherMemberUnavailable| - [JobCoordinationService] hz.friendly_moser.cached.thread-7 - [127.0.0.1]:5600 [dev] [5.2-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
23:57:00,872 DEBUG |testNodeStateAvailable_whenOtherMemberUnavailable| - [JobCoordinationService] hz.friendly_moser.cached.thread-6 - [127.0.0.1]:5600 [dev] [5.2-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
23:57:00,947  INFO |testNodeStateAvailable_whenOtherMemberUnavailable| - [ClusterService] hz.friendly_moser.priority-generic-operation.thread-0 - [127.0.0.1]:5600 [dev] [5.2-SNAPSHOT] 

Members {size:2, ver:2} [
	Member [127.0.0.1]:5600 - 51e4d09f-db5b-4855-9335-0135de223cb8 this
	Member [127.0.0.1]:5601 - 6b95b9c7-518d-4356-9eab-0ef51131bcf4
]

23:57:00,948  INFO |testNodeStateAvailable_whenOtherMemberUnavailable| - [ClusterService] hz.unruffled_moser.priority-generic-operation.thread-0 - [127.0.0.1]:5601 [dev] [5.2-SNAPSHOT] 

Members {size:2, ver:2} [
	Member [127.0.0.1]:5600 - 51e4d09f-db5b-4855-9335-0135de223cb8
	Member [127.0.0.1]:5601 - 6b95b9c7-518d-4356-9eab-0ef51131bcf4 this
]

23:57:00,948  INFO |testNodeStateAvailable_whenOtherMemberUnavailable| - [JobCoordinationService] testNodeStateAvailable_whenOtherMemberUnavailable - [127.0.0.1]:5601 [dev] [5.2-SNAPSHOT] Jet started scanning for jobs
23:57:00,949  INFO |testNodeStateAvailable_whenOtherMemberUnavailable| - [LifecycleService] testNodeStateAvailable_whenOtherMemberUnavailable - [127.0.0.1]:5601 [dev] [5.2-SNAPSHOT] [127.0.0.1]:5601 is STARTED
23:57:00,950  INFO |testNodeStateAvailable_whenOtherMemberUnavailable| - [LifecycleService] main - [127.0.0.1]:5600 [dev] [5.2-SNAPSHOT] [127.0.0.1]:5600 is SHUTTING_DOWN
23:57:00,950  WARN |testNodeStateAvailable_whenOtherMemberUnavailable| - [Node] main - [127.0.0.1]:5600 [dev] [5.2-SNAPSHOT] Terminating forcefully...
23:57:00,950  INFO |testNodeStateAvailable_whenOtherMemberUnavailable| - [Node] main - [127.0.0.1]:5600 [dev] [5.2-SNAPSHOT] Shutting down multicast service...
23:57:00,950  INFO |testNodeStateAvailable_whenOtherMemberUnavailable| - [Node] main - [127.0.0.1]:5600 [dev] [5.2-SNAPSHOT] Shutting down connection manager...
23:57:00,951  INFO |testNodeStateAvailable_whenOtherMemberUnavailable| - [TcpServerConnection] main - [127.0.0.1]:5600 [dev] [5.2-SNAPSHOT] Connection[id=1, /127.0.0.1:5600->/127.0.0.1:50613, qualifier=null, endpoint=[127.0.0.1]:5601, remoteUuid=6b95b9c7-518d-4356-9eab-0ef51131bcf4, alive=false, connectionType=MEMBER, planeIndex=0] closed. Reason: TcpServer is stopping
23:57:00,951  INFO |testNodeStateAvailable_whenOtherMemberUnavailable| - [TcpServerConnection] hz.unruffled_moser.IO.thread-in-0 - [127.0.0.1]:5601 [dev] [5.2-SNAPSHOT] Connection[id=1, /0.0.0.0:50613->/127.0.0.1:5600, qualifier=null, endpoint=[127.0.0.1]:5600, remoteUuid=51e4d09f-db5b-4855-9335-0135de223cb8, alive=false, connectionType=MEMBER, planeIndex=0] closed. Reason: Connection closed by the other side
23:57:00,951  INFO |testNodeStateAvailable_whenOtherMemberUnavailable| - [Node] main - [127.0.0.1]:5600 [dev] [5.2-SNAPSHOT] Shutting down node engine...
23:57:00,953  INFO |testNodeStateAvailable_whenOtherMemberUnavailable| - [TcpServerConnector] hz.unruffled_moser.cached.thread-8 - [127.0.0.1]:5601 [dev] [5.2-SNAPSHOT] Connecting to /127.0.0.1:5600, timeout: 10000, bind-any: true
23:57:00,954  INFO |testNodeStateAvailable_whenOtherMemberUnavailable| - [TcpServerConnector] hz.unruffled_moser.cached.thread-8 - [127.0.0.1]:5601 [dev] [5.2-SNAPSHOT] Could not connect to: /127.0.0.1:5600. Reason: IOException[Connection refused to address /127.0.0.1:5600]
23:57:00,957  INFO |testNodeStateAvailable_whenOtherMemberUnavailable| - [NodeExtension] main - [127.0.0.1]:5600 [dev] [5.2-SNAPSHOT] Destroying node NodeExtension.
23:57:00,957  INFO |testNodeStateAvailable_whenOtherMemberUnavailable| - [Node] main - [127.0.0.1]:5600 [dev] [5.2-SNAPSHOT] Hazelcast Shutdown is completed in 7 ms.
23:57:00,957  INFO |testNodeStateAvailable_whenOtherMemberUnavailable| - [LifecycleService] main - [127.0.0.1]:5600 [dev] [5.2-SNAPSHOT] [127.0.0.1]:5600 is SHUTDOWN
23:57:00,957  INFO |testNodeStateAvailable_whenOtherMemberUnavailable| - [LifecycleService] main - [127.0.0.1]:5601 [dev] [5.2-SNAPSHOT] [127.0.0.1]:5601 is SHUTTING_DOWN
23:57:00,957  WARN |testNodeStateAvailable_whenOtherMemberUnavailable| - [Node] main - [127.0.0.1]:5601 [dev] [5.2-SNAPSHOT] Terminating forcefully...
23:57:00,957  INFO |testNodeStateAvailable_whenOtherMemberUnavailable| - [TextCommandServiceImpl] main - [127.0.0.1]:5601 [dev] [5.2-SNAPSHOT] Stopping text command service...
23:57:01,054  INFO |testNodeStateAvailable_whenOtherMemberUnavailable| - [TcpServerConnector] hz.unruffled_moser.cached.thread-7 - [127.0.0.1]:5601 [dev] [5.2-SNAPSHOT] Connecting to /127.0.0.1:5600, timeout: 10000, bind-any: true
23:57:01,055  INFO |testNodeStateAvailable_whenOtherMemberUnavailable| - [TcpServerConnector] hz.unruffled_moser.cached.thread-7 - [127.0.0.1]:5601 [dev] [5.2-SNAPSHOT] Could not connect to: /127.0.0.1:5600. Reason: IOException[Connection refused to address /127.0.0.1:5600]
23:57:01,055  INFO |testNodeStateAvailable_whenOtherMemberUnavailable| - [MulticastJoiner] hz.unruffled_moser.cached.thread-7 - [127.0.0.1]:5601 [dev] [5.2-SNAPSHOT] [127.0.0.1]:5600 is added to the blacklist.
23:57:01,957  INFO |testNodeStateAvailable_whenOtherMemberUnavailable| - [Node] main - [127.0.0.1]:5601 [dev] [5.2-SNAPSHOT] Shutting down multicast service...
23:57:01,957  INFO |testNodeStateAvailable_whenOtherMemberUnavailable| - [Node] main - [127.0.0.1]:5601 [dev] [5.2-SNAPSHOT] Shutting down connection manager...
23:57:01,958  INFO |testNodeStateAvailable_whenOtherMemberUnavailable| - [Node] main - [127.0.0.1]:5601 [dev] [5.2-SNAPSHOT] Shutting down node engine...
23:57:01,961  INFO |testNodeStateAvailable_whenOtherMemberUnavailable| - [NodeExtension] main - [127.0.0.1]:5601 [dev] [5.2-SNAPSHOT] Destroying node NodeExtension.
23:57:01,961  INFO |testNodeStateAvailable_whenOtherMemberUnavailable| - [Node] main - [127.0.0.1]:5601 [dev] [5.2-SNAPSHOT] Hazelcast Shutdown is completed in 1004 ms.
23:57:01,961  INFO |testNodeStateAvailable_whenOtherMemberUnavailable| - [LifecycleService] main - [127.0.0.1]:5601 [dev] [5.2-SNAPSHOT] [127.0.0.1]:5601 is SHUTDOWN
```

</details>

**Comment by orcunc** [comment]
When the test starts, the very first hazelcast node is created but **it is discovering a node which should not exist**. We can see in the logs these lines
```
[127.0.0.1]:5600 is STARTING
MulticastJoiner] testNodeStateAvailable_whenOtherMemberUnavailable - [127.0.0.1]:5600 [dev] [5.2-SNAPSHOT] Trying to join to discovered node: [127.0.0.1]:5701
```
So my node has port 5600 and it discovers a node at port 5701. And then 5701 is blacklisted. 
`127.0.0.1]:5701 is added to the blacklist.`
So the test will timeout trying to join 5701
