### ISSUE TITLE
com.hazelcast.jet.pipeline.SourceBuilderTest.stream_socketSource_withTimestamps_andLateness

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#21831]
_5.1.z_ (commit 24c12a8e2a54dc771c833e183ff1edf9f2dce888)

Failed on Windows with OracleJDK8: 
- `[0: mode=member]`: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-Windows-OracleJDK8/76/testReport/com.hazelcast.jet.pipeline/SourceBuilderTest/stream_socketSource_withTimestamps_andLateness_0__mode_member_/
- `[1: mode=client]`: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-Windows-OracleJDK8/76/testReport/com.hazelcast.jet.pipeline/SourceBuilderTest/stream_socketSource_withTimestamps_andLateness_1__mode_client_/

<details><summary>Stacktrace for [0: mode=member]:</summary>

```
java.lang.AssertionError: expected:<[WindowResult{start=00:00:00.000, end=00:00:00.001, value='1', isEarly=false}, WindowResult{start=00:00:00.001, end=00:00:00.002, value='1', isEarly=false}, WindowResult{start=00:00:00.002, end=00:00:00.003, value='1', isEarly=false}, WindowResult{start=00:00:00.003, end=00:00:00.004, value='1', isEarly=false}, WindowResult{start=00:00:00.004, end=00:00:00.005, value='1', isEarly=false}, WindowResult{start=00:00:00.005, end=00:00:00.006, value='1', isEarly=false}, WindowResult{start=00:00:00.006, end=00:00:00.007, value='1', isEarly=false}, WindowResult{start=00:00:00.007, end=00:00:00.008, value='1', isEarly=false}, WindowResult{start=00:00:00.008, end=00:00:00.009, value='1', isEarly=false}, WindowResult{start=00:00:00.009, end=00:00:00.010, value='1', isEarly=false}, WindowResult{start=00:00:00.010, end=00:00:00.011, value='1', isEarly=false}, WindowResult{start=00:00:00.011, end=00:00:00.012, value='1', isEarly=false}, 
...
WindowResult{start=00:00:01.010, end=00:00:01.011, value='1', isEarly=false}, WindowResult{start=00:00:01.011, end=00:00:01.012, value='1', isEarly=false}, WindowResult{start=00:00:01.012, end=00:00:01.013, value='1', isEarly=false}]> but was:<[WindowResult{start=00:00:00.000, end=00:00:00.001, value='1', isEarly=false}, WindowResult{start=00:00:00.001, end=00:00:00.002, value='1', isEarly=false}, WindowResult{start=00:00:00.002, end=00:00:00.003, value='1', isEarly=false}, WindowResult{start=00:00:00.003, end=00:00:00.004, value='1', isEarly=false}, WindowResult{start=00:00:00.004, end=00:00:00.005, value='1', isEarly=false}, WindowResult{start=00:00:00.005, end=00:00:00.006, value='1', isEarly=false}, WindowResult{start=00:00:00.006, end=00:00:00.007, value='1', isEarly=false}
...
WindowResult{start=00:00:00.655, end=00:00:00.656, value='1', isEarly=false}, WindowResult{start=00:00:00.656, end=00:00:00.657, value='1', isEarly=false}, WindowResult{start=00:00:00.657, end=00:00:00.658, value='1', isEarly=false}, WindowResult{start=00:00:00.658, end=00:00:00.659, value='1', isEarly=false}]>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:120)
	at org.junit.Assert.assertEquals(Assert.java:146)
	at com.hazelcast.jet.pipeline.SourceBuilderTest.lambda$stream_socketSource_withTimestamps_andLateness$8(SourceBuilderTest.java:280)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1226)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1243)
	at com.hazelcast.jet.pipeline.SourceBuilderTest.stream_socketSource_withTimestamps_andLateness(SourceBuilderTest.java:280)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

</details>

<details><summary>Standard output for [0: mode=member]:</summary>

```
01:21:27,212  INFO |stream_socketSource_withTimestamps_andLateness[0: mode=member]| - [CacheService] Time-limited test - [127.0.0.1]:5701 [dev] [5.1.3-SNAPSHOT] Added cache config: CacheConfig{name='journaledMap.2c92b50d-c75f-4cf2-ae65-0a62ea722839', managerPrefix='/hz/', inMemoryFormat=BINARY, backupCount=1, hotRestart=HotRestartConfig{enabled=false, fsync=false}, dataPersistenceConfig=DataPersistenceConfig{enabled=false, fsync=false}, wanReplicationRef=null, merkleTreeConfig=MerkleTreeConfig{enabled=null, depth=10}}
01:21:27,212  INFO || - [CacheService] hz.upbeat_pike.generic-operation.thread-1 - [127.0.0.1]:5702 [dev] [5.1.3-SNAPSHOT] Added cache config: CacheConfig{name='journaledMap.2c92b50d-c75f-4cf2-ae65-0a62ea722839', managerPrefix='/hz/', inMemoryFormat=BINARY, backupCount=1, hotRestart=HotRestartConfig{enabled=false, fsync=false}, dataPersistenceConfig=DataPersistenceConfig{enabled=false, fsync=false}, wanReplicationRef=null, merkleTreeConfig=MerkleTreeConfig{enabled=null, depth=10}}
01:21:27,212 DEBUG || - [JobClassLoaderService] hz.gallant_pike.cached.thread-6 - [127.0.0.1]:5701 [dev] [5.1.3-SNAPSHOT] Creating job classLoader for job 085f-b1ac-7c45-0001
01:21:27,212 DEBUG || - [JobClassLoaderService] hz.gallant_pike.cached.thread-6 - [127.0.0.1]:5701 [dev] [5.1.3-SNAPSHOT] Create processor classloader map for job 085f-b1ac-7c45-0001
01:21:27,212 DEBUG || - [Planner] hz.gallant_pike.cached.thread-6 - Watermarks in the pipeline will be throttled to 1
01:21:27,228  INFO || - [JobCoordinationService] hz.gallant_pike.cached.thread-6 - [127.0.0.1]:5701 [dev] [5.1.3-SNAPSHOT] Starting job 085f-b1ac-7c45-0001 based on submit request
01:21:27,228  INFO || - [MasterJobContext] hz.gallant_pike.cached.thread-6 - [127.0.0.1]:5701 [dev] [5.1.3-SNAPSHOT] Didn't find any snapshot to restore for job '085f-b1ac-7c45-0001', execution 085f-b1ac-7c46-0001
01:21:27,228  INFO || - [MasterJobContext] hz.gallant_pike.cached.thread-6 - [127.0.0.1]:5701 [dev] [5.1.3-SNAPSHOT] Start executing job '085f-b1ac-7c45-0001', execution 085f-b1ac-7c46-0001, execution graph in DOT format:
digraph DAG {
	"socket-source-with-timestamps" [localParallelism=1];
	"sliding-window-prepare" [localParallelism=2];
	"sliding-window" [localParallelism=1];
	"listSink(04d30f81-bb16-4e21-ba61-3ee025c9e0bb)" [localParallelism=1];
	"socket-source-with-timestamps" -> "sliding-window-prepare" [queueSize=1024];
	subgraph cluster_0 {
		"sliding-window-prepare" -> "sliding-window" [label="distributed-partitioned", queueSize=1024];
	}
	"sliding-window" -> "listSink(04d30f81-bb16-4e21-ba61-3ee025c9e0bb)" [queueSize=1024];
}
HINT: You can use graphviz or http://viz-js.com/ to visualize the printed graph.
01:21:27,228 DEBUG || - [MasterJobContext] hz.gallant_pike.cached.thread-6 - [127.0.0.1]:5701 [dev] [5.1.3-SNAPSHOT] Building execution plan for job '085f-b1ac-7c45-0001', execution 085f-b1ac-7c46-0001
01:21:27,228 DEBUG || - [MasterJobContext] hz.gallant_pike.cached.thread-6 - [127.0.0.1]:5701 [dev] [5.1.3-SNAPSHOT] Built execution plans for job '085f-b1ac-7c45-0001', execution 085f-b1ac-7c46-0001
01:21:27,228 DEBUG || - [InitExecutionOperation] hz.gallant_pike.cached.thread-6 - [127.0.0.1]:5701 [dev] [5.1.3-SNAPSHOT] Initializing execution plan for job 085f-b1ac-7c45-0001, execution 085f-b1ac-7c46-0001 from [127.0.0.1]:5701
01:21:27,228  INFO || - [JobExecutionService] hz.gallant_pike.cached.thread-6 - [127.0.0.1]:5701 [dev] [5.1.3-SNAPSHOT] Execution plan for jobId=085f-b1ac-7c45-0001, jobName='085f-b1ac-7c45-0001', executionId=085f-b1ac-7c46-0001 initialized
01:21:27,228 DEBUG || - [InitExecutionOperation] hz.upbeat_pike.generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.1.3-SNAPSHOT] Initializing execution plan for job 085f-b1ac-7c45-0001, execution 085f-b1ac-7c46-0001 from [127.0.0.1]:5701
01:21:27,228 DEBUG || - [JobClassLoaderService] hz.upbeat_pike.generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.1.3-SNAPSHOT] Creating job classLoader for job 085f-b1ac-7c45-0001
01:21:27,228 DEBUG || - [JobClassLoaderService] hz.upbeat_pike.generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.1.3-SNAPSHOT] Create processor classloader map for job 085f-b1ac-7c45-0001
01:21:27,228  INFO || - [JobExecutionService] hz.upbeat_pike.generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.1.3-SNAPSHOT] Execution plan for jobId=085f-b1ac-7c45-0001, jobName='085f-b1ac-7c45-0001', executionId=085f-b1ac-7c46-0001 initialized
01:21:27,228 DEBUG || - [MasterJobContext] hz.gallant_pike.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.1.3-SNAPSHOT] Init of job '085f-b1ac-7c45-0001', execution 085f-b1ac-7c46-0001 was successful
01:21:27,228 DEBUG || - [MasterJobContext] hz.gallant_pike.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.1.3-SNAPSHOT] Executing job '085f-b1ac-7c45-0001', execution 085f-b1ac-7c46-0001
01:21:27,228  INFO || - [JobExecutionService] hz.gallant_pike.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.1.3-SNAPSHOT] Start execution of job '085f-b1ac-7c45-0001', execution 085f-b1ac-7c46-0001 from coordinator [127.0.0.1]:5701
01:21:27,228  INFO || - [JobExecutionService] hz.upbeat_pike.generic-operation.thread-1 - [127.0.0.1]:5702 [dev] [5.1.3-SNAPSHOT] Start execution of job '085f-b1ac-7c45-0001', execution 085f-b1ac-7c46-0001 from coordinator [127.0.0.1]:5701
Accepted connection from 49351
line1014
line1015
line1016
line1017
line1018
line1019
line1020
line1021
line1022
line1023
01:21:31,790 DEBUG || - [JobRepository] hz.gallant_pike.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.1.3-SNAPSHOT] Job cleanup took 0ms
01:21:36,806 DEBUG || - [JobRepository] hz.gallant_pike.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.1.3-SNAPSHOT] Job cleanup took 0ms
01:21:37,400  WARN |stream_socketSource_withTimestamps_andLateness[0: mode=member]| - [JetTestSupport] Thread-42833 - Spawned Runnable failed
java.net.SocketException: socket closed
	at java.net.TwoStacksPlainSocketImpl.socketAccept(Native Method) ~[?:1.8.0_172]
	at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409) ~[?:1.8.0_172]
	at java.net.PlainSocketImpl.accept(PlainSocketImpl.java:199) ~[?:1.8.0_172]
	at java.net.ServerSocket.implAccept(ServerSocket.java:545) ~[?:1.8.0_172]
	at java.net.ServerSocket.accept(ServerSocket.java:513) ~[?:1.8.0_172]
	at com.hazelcast.jet.pipeline.SourceBuilderTest.lambda$startServer$90bd162$1(SourceBuilderTest.java:565) ~[test-classes/:?]
	at com.hazelcast.jet.core.JetTestSupport.lambda$spawnSafe$3(JetTestSupport.java:337) ~[test-classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_172]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_172]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
01:21:37,806 DEBUG |stream_socketSource_withTimestamps_andLateness[0: mode=member]| - [AbstractJobProxy] Thread-42835 - [127.0.0.1]:5701 [dev] [5.1.3-SNAPSHOT] Sending CANCEL_FORCEFUL request for job 085f-b1ac-7c45-0001 (name ??)
01:21:37,821 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-2 - [127.0.0.1]:5701 [dev] [5.1.3-SNAPSHOT] Completed execution of job '085f-b1ac-7c45-0001', execution 085f-b1ac-7c46-0001
01:21:37,821 DEBUG || - [JobClassLoaderService] ForkJoinPool.commonPool-worker-0 - [127.0.0.1]:5702 [dev] [5.1.3-SNAPSHOT] Finish JobClassLoaders phaseCount = 0, removing classloaders for jobId=085f-b1ac-7c45-0001
01:21:37,821 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-0 - [127.0.0.1]:5702 [dev] [5.1.3-SNAPSHOT] Completed execution of job '085f-b1ac-7c45-0001', execution 085f-b1ac-7c46-0001
01:21:37,821 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-0 - [127.0.0.1]:5702 [dev] [5.1.3-SNAPSHOT] Execution of job '085f-b1ac-7c45-0001', execution 085f-b1ac-7c46-0001 completed with failure
java.util.concurrent.CompletionException: com.hazelcast.jet.impl.exception.JobTerminateRequestedException: CANCEL_FORCEFUL
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292) ~[?:1.8.0_172]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308) ~[?:1.8.0_172]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:769) ~[?:1.8.0_172]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736) ~[?:1.8.0_172]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[?:1.8.0_172]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977) ~[?:1.8.0_172]
	at com.hazelcast.jet.impl.util.NonCompletableFuture.internalCompleteExceptionally(NonCompletableFuture.java:72) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$ExecutionTracker.taskletDone(TaskletExecutionService.java:495) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.dismissTasklet(TaskletExecutionService.java:426) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:412) ~[classes/:?]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891) ~[?:1.8.0_172]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.run(TaskletExecutionService.java:369) ~[classes/:?]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_172]
Caused by: com.hazelcast.jet.impl.exception.JobTerminateRequestedException: CANCEL_FORCEFUL
	at com.hazelcast.jet.impl.execution.ExecutionContext.terminateExecution(ExecutionContext.java:296) ~[classes/:?]
	at com.hazelcast.jet.impl.JobExecutionService.terminateExecution0(JobExecutionService.java:696) ~[classes/:?]
	at com.hazelcast.jet.impl.JobExecutionService.terminateExecution(JobExecutionService.java:692) ~[classes/:?]
	at com.hazelcast.jet.impl.operation.TerminateExecutionOperation.run(TerminateExecutionOperation.java:58) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:189) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:273) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:248) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:471) ~[classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:197) ~[classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:137) ~[classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123) ~[classes/:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) ~[classes/:?]
01:21:37,821 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-2 - [127.0.0.1]:5701 [dev] [5.1.3-SNAPSHOT] Execution of job '085f-b1ac-7c45-0001', execution 085f-b1ac-7c46-0001 completed with failure
java.util.concurrent.CompletionException: com.hazelcast.jet.impl.exception.JobTerminateRequestedException: CANCEL_FORCEFUL
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292) ~[?:1.8.0_172]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308) ~[?:1.8.0_172]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:769) ~[?:1.8.0_172]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736) ~[?:1.8.0_172]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[?:1.8.0_172]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977) ~[?:1.8.0_172]
	at com.hazelcast.jet.impl.util.NonCompletableFuture.internalCompleteExceptionally(NonCompletableFuture.java:72) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$ExecutionTracker.taskletDone(TaskletExecutionService.java:495) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$BlockingWorker.run(TaskletExecutionService.java:330) ~[classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_172]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_172]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_172]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_172]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_172]
Caused by: com.hazelcast.jet.impl.exception.JobTerminateRequestedException: CANCEL_FORCEFUL
	at com.hazelcast.jet.impl.execution.ExecutionContext.terminateExecution(ExecutionContext.java:296) ~[classes/:?]
	at com.hazelcast.jet.impl.JobExecutionService.terminateExecution0(JobExecutionService.java:696) ~[classes/:?]
	at com.hazelcast.jet.impl.JobExecutionService.terminateExecution(JobExecutionService.java:692) ~[classes/:?]
	at com.hazelcast.jet.impl.operation.TerminateExecutionOperation.run(TerminateExecutionOperation.java:58) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:189) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:273) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:248) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:213) ~[classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:411) ~[classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:438) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:601) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:580) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:541) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:241) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:61) ~[classes/:?]
	at com.hazelcast.jet.impl.MasterContext.invokeOnParticipant(MasterContext.java:294) ~[classes/:?]
	at com.hazelcast.jet.impl.MasterContext.invokeOnParticipants(MasterContext.java:277) ~[classes/:?]
	at com.hazelcast.jet.impl.MasterJobContext.lambda$cancelExecutionInvocations$17(MasterJobContext.java:618) ~[classes/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_172]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_172]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_172]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76) ~[classes/:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) ~[classes/:?]
01:21:37,821 DEBUG || - [MasterJobContext] ForkJoinPool.commonPool-worker-2 - [127.0.0.1]:5701 [dev] [5.1.3-SNAPSHOT] job '085f-b1ac-7c45-0001', execution 085f-b1ac-7c46-0001 received response to StartExecutionOperation from [127.0.0.1]:5701: com.hazelcast.jet.impl.exception.JobTerminateRequestedException: CANCEL_FORCEFUL
01:21:37,821 DEBUG || - [MasterJobContext] ForkJoinPool.commonPool-worker-0 - [127.0.0.1]:5701 [dev] [5.1.3-SNAPSHOT] job '085f-b1ac-7c45-0001', execution 085f-b1ac-7c46-0001 received response to StartExecutionOperation from [127.0.0.1]:5702: com.hazelcast.jet.impl.exception.JobTerminateRequestedException: CANCEL_FORCEFUL
01:21:37,821 DEBUG || - [MasterJobContext] ForkJoinPool.commonPool-worker-0 - [127.0.0.1]:5701 [dev] [5.1.3-SNAPSHOT] job '085f-b1ac-7c45-0001', execution 085f-b1ac-7c46-0001 to be cancelled after Execution
01:21:37,821 DEBUG || - [JobClassLoaderService] hz.gallant_pike.cached.thread-10 - [127.0.0.1]:5701 [dev] [5.1.3-SNAPSHOT] Finish JobClassLoaders phaseCount = 0, removing classloaders for jobId=085f-b1ac-7c45-0001
01:21:37,821  INFO || - [MasterJobContext] hz.gallant_pike.cached.thread-10 - [127.0.0.1]:5701 [dev] [5.1.3-SNAPSHOT] Execution of job '085f-b1ac-7c45-0001', execution 085f-b1ac-7c46-0001 got terminated, reason=java.util.concurrent.CancellationException
	Start time: 2022-07-24T01:21:27.228
	Duration: 00:00:10.593
	To see additional job metrics enable JobConfig.storeMetricsAfterJobCompletion
01:21:37,821 DEBUG || - [JobCoordinationService] hz.gallant_pike.cached.thread-10 - [127.0.0.1]:5701 [dev] [5.1.3-SNAPSHOT] job '085f-b1ac-7c45-0001', execution 085f-b1ac-7c46-0001 is completed
01:21:37,821  INFO |stream_socketSource_withTimestamps_andLateness[0: mode=member]| - [CacheService] Thread-42835 - [127.0.0.1]:5701 [dev] [5.1.3-SNAPSHOT] Removed cache config: CacheConfig{name='journaledMap.2c92b50d-c75f-4cf2-ae65-0a62ea722839', managerPrefix='/hz/', inMemoryFormat=BINARY, backupCount=1, hotRestart=HotRestartConfig{enabled=false, fsync=false}, dataPersistenceConfig=DataPersistenceConfig{enabled=false, fsync=false}, wanReplicationRef=null, merkleTreeConfig=MerkleTreeConfig{enabled=null, depth=10}}
01:21:37,821  INFO || - [CacheService] hz.upbeat_pike.generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.1.3-SNAPSHOT] Removed cache config: CacheConfig{name='journaledMap.2c92b50d-c75f-4cf2-ae65-0a62ea722839', managerPrefix='/hz/', inMemoryFormat=BINARY, backupCount=1, hotRestart=HotRestartConfig{enabled=false, fsync=false}, dataPersistenceConfig=DataPersistenceConfig{enabled=false, fsync=false}, wanReplicationRef=null, merkleTreeConfig=MerkleTreeConfig{enabled=null, depth=10}}
BuildInfo right after stream_socketSource_withTimestamps_andLateness[0: mode=member](com.hazelcast.jet.pipeline.SourceBuilderTest): BuildInfo{version='5.1.3-SNAPSHOT', build='20220724', buildNumber=20220724, revision=24c12a8, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'stream_socketSource_withTimestamps_andLateness[0: mode=member](com.hazelcast.jet.pipeline.SourceBuilderTest):'
01:21:25, accumulated pauses: 4985 ms, max pause: 31 ms, pauses over 1000 ms: 0
01:21:30, accumulated pauses: 4985 ms, max pause: 31 ms, pauses over 1000 ms: 0
01:21:35, accumulated pauses: 2805 ms, max pause: 404 ms, pauses over 1000 ms: 0
```

</details>

**Comment by TomaszGaweda** [comment]
Seems like an error after keyed watermarks - similar issues with streaming aggregations were seen, later it was fixed by Viliam.
