### ISSUE TITLE
Map Clear exception - "SQL catalog must never be cleared" [HZ-1336]

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast#21834]
**Describe the bug**
The below appears in the logs, I can't see how triggered from my code, on the 2nd node of a 2 node cluster.

```
09:40:26.922 [hz.wizardly_hellman.event-1] ERROR com.hazelcast.spi.impl.eventservice.impl.EventServiceImpl - [10.172.3.8]:5701 [sanmateo] [5.2-SNAPSHOT] hz.wizardly_hellman.event-1 caught an exception while processing:com.hazelcast.spi.impl.eventservice.impl.LocalEventDispatcher@23c1d6b2
 java.lang.UnsupportedOperationException: SQL catalog must never be cleared - MapEvent{entryEventType=CLEAR_ALL, member=Member [10.172.3.8]:5701 - 554bc266-fdc9-4d0b-bc8f-72d781029519 this, name='__sql.catalog', numberOfEntriesAffected=0}
	at com.hazelcast.jet.sql.impl.schema.TablesStorage$EntryListenerAdapter.mapCleared(TablesStorage.java:262) ~[hazelcast-sql-5.2-SNAPSHOT.jar!/:5.2-SNAPSHOT]
	at com.hazelcast.replicatedmap.impl.ReplicatedMapEventPublishingService.dispatchEvent(ReplicatedMapEventPublishingService.java:132) ~[hazelcast-enterprise-5.2-SNAPSHOT.jar!/:5.2-SNAPSHOT]
	at com.hazelcast.replicatedmap.impl.ReplicatedMapService.dispatchEvent(ReplicatedMapService.java:232) ~[hazelcast-enterprise-5.2-SNAPSHOT.jar!/:5.2-SNAPSHOT]
	at com.hazelcast.spi.impl.eventservice.impl.LocalEventDispatcher.run(LocalEventDispatcher.java:64) ~[hazelcast-enterprise-5.2-SNAPSHOT.jar!/:5.2-SNAPSHOT]
	at com.hazelcast.internal.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:245) ~[hazelcast-enterprise-5.2-SNAPSHOT.jar!/:5.2-SNAPSHOT]
	at com.hazelcast.internal.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:228) ~[hazelcast-enterprise-5.2-SNAPSHOT.jar!/:5.2-SNAPSHOT]
```

**Expected behavior**
Should not occur

**To Reproduce**
Happens every time on my (large) example. Not sure what is causing it, so can't yet simplify.

**Additional context**
Using the enterprise build, `Hazelcast Enterprise 5.2-SNAPSHOT (20220725 - 151b1c6, a12b871) ` but SQL is

**Comment by viliam-durina** [comment]
Something triggered the `EntryListener.mapCleared()`  event. It's normal in tests where we destroy all maps, but should not happen otherwise.

**Comment by neilstevenson** [comment]
Reproducer 
```
	private static final String MAPNAME1 = "m1";
	
	public static void main(String[] args) throws Exception {
		Config config = new Config();

		config.getJetConfig().setEnabled(true);
		
		HazelcastInstance hazelcastInstance1 = Hazelcast.newHazelcastInstance(config);
		HazelcastInstance hazelcastInstance2 = Hazelcast.newHazelcastInstance(config);
		
		hazelcastInstance1.getMap(MAPNAME1);
		
        String mapping = "CREATE MAPPING " + MAPNAME1
        + " TYPE IMap "
        + " OPTIONS ( "
        + " 'keyFormat' = 'java',"
        + " 'keyJavaClass' = 'java.lang.Integer',"
        + " 'valueFormat' = 'java',"
        + " 'valueJavaClass' = 'java.lang.Integer'"
        + " )";
        hazelcastInstance1.getSql().execute(mapping);

        Hazelcast.shutdownAll();
	}
```

**Comment by neilstevenson** [comment]
Triggered by https://github.com/hazelcast/hazelcast/blob/master/hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/schema/TablesStorage.java#L178

**Comment by neilstevenson** [comment]
Note this is a 5.2-SNAPSHOT cluster, so the `ReplicatedMap` oldStore shouldn't exist, hence shouldn't be deleted.
Although this is not true in general, so perhaps not throwing an exception when `getNumberOfEntriesAffected() > 0` is an answer in general
