### ISSUE TITLE
com.hazelcast.jet.pipeline.SourceBuilder_TopologyChangeTest.test_restartJob_nodeTerminated [HZ-1394]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#21908]
_master_ (commit 98551638971b0badced3013beea408f4d68b16e1)

Failed on OracleJDK17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-OracleJDK17/41/testReport/com.hazelcast.jet.pipeline/SourceBuilder_TopologyChangeTest/test_restartJob_nodeTerminated/

<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: expected:<100> but was:<101>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at com.hazelcast.jet.pipeline.SourceBuilder_TopologyChangeTest.testTopologyChange(SourceBuilder_TopologyChangeTest.java:135)
	at com.hazelcast.jet.pipeline.SourceBuilder_TopologyChangeTest.test_restartJob_nodeTerminated(SourceBuilder_TopologyChangeTest.java:62)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

</details>

Standard output can be downloaded from https://console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-OracleJDK17/41/

**Comment by arodionov** [comment]
Got the same build failure https://jenkins.hazelcast.com/job/Hazelcast-pr-builder/12424/display/redirect
Log https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/12424/Hazelcast-pr-builder-12424.zip

**Comment by olukas** [comment]
Failed on `master` on Openj9-17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Openj9-17/27/testReport/com.hazelcast.jet.pipeline/SourceBuilder_TopologyChangeTest/test_restartJob_nodeTerminated/

**Comment by kwart** [comment]
PR builder failure: https://jenkins.hazelcast.com/job/Hazelcast-pr-builder/12825/testReport/junit/com.hazelcast.jet.pipeline/SourceBuilder_TopologyChangeTest/test_restartJob_nodeTerminated/

**Comment by srknzl** [comment]
Failed again at https://jenkins.hazelcast.com/job/Hazelcast-pr-builder/12978/display/redirect with commit https://github.com/hazelcast/hazelcast/pull/21838/commits/c6d2a8878bbf579f9cd813ccfb639500a9e3179d

**Comment by olukas** [comment]
Failed on `ZingJDK8`: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZingJDK8/462/testReport/com.hazelcast.jet.pipeline/SourceBuilder_TopologyChangeTest/test_restartJob_nodeTerminated/
