### ISSUE TITLE
When a single node starts a cluster, this exception will be thrown after running for a period of time, and then the cluster function will fail

### ISSUE THREAD

**Issue by 1ssqq1lxr** [hazelcast/hazelcast#21922]
config:
 "network": {
      "tcpIp": {
        "members": [
          "127.0.0.1"
        ]
      },
      "trustedIps":["192.168.8.57"]
    },

exception:
WARNING: [127.0.0.1]:5701 [base_old] [4.2.5] Future.complete(Object) on completed future. Request: Invocation{op=com.hazelcast.internal.metrics.managementcenter.ReadMetricsOperation{serviceName='hz:impl:metricsService', identityHash=1479810253, partitionId=-1, replicaIndex=0, callId=-1682996, invocationTime=1659811293705 (2022-08-07 02:41:33.705), waitTimeout=-1, callTimeout=60000, tenantControl=com.hazelcast.spi.impl.tenantcontrol.NoopTenantControl@0}, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=60000, firstInvocationTimeMs=1659811293705, firstInvocationTime='2022-08-07 02:41:33.705', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 08:00:00.000', target=[127.0.0.1]:5701, pendingResponse={VOID}, backupsAcksExpected=-1, backupsAcksReceived=0, connection=null}, current value: ExceptionalResult{cause=com.hazelcast.core.MemberLeftException: Member [127.0.0.1]:5701 - 361c4d32-1267-479f-a45a-3511f0a9dcaa this has left cluster!}, offered value: com.hazelcast.internal.metrics.managementcenter.ConcurrentArrayRingbuffer$RingbufferSlice@56f3f9bb
java.lang.Exception
        at com.hazelcast.spi.impl.AbstractInvocationFuture.warnIfSuspiciousDoubleCompletion(AbstractInvocationFuture.java:1253)
        at com.hazelcast.spi.impl.AbstractInvocationFuture.complete0(AbstractInvocationFuture.java:1230)
        at com.hazelcast.spi.impl.AbstractInvocationFuture.complete(AbstractInvocationFuture.java:1219)

**Comment by 1ssqq1lxr** [comment]
When I operate the cache, I throw the following exception: Target of invocation cannot be found! Partition owner is null but partitions can't be assigned since all nodes in the cluster are lite members.

**Comment by 1ssqq1lxr** [comment]
We use version 4.2.5
