### ISSUE TITLE
SQL JOB incorrect default processing guarantee for "INSERT INTO"

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast#21932]
**Describe the bug**
`INSERT INTO` with no processing guarantee configured fails on a rebalance.
Occurs, at least, for Kafka source.

**Expected behavior**
No exception when scaling

**To Reproduce**
1. Run this SQL
```
CREATE JOB IF NOT EXISTS kafka2IMap AS  INSERT INTO audit_log SELECT * FROM kf_alerts
```
read from a kafka stream, write to a map.
2. Scale the cluster up

**Additional context**
Tested using `Hazelcast Enterprise 5.2-SNAPSHOT (20220808 - 21e2f74, f4d3d27) `

Gives
```
Exception in ProcessorTasklet{kafka2IMap/IMap[public.audit_log]#2}: com.hazelcast.sql.impl.QueryException: Duplicate key
	at com.hazelcast.jet.impl.execution.TaskletExecutionService.handleTaskletExecutionError(TaskletExecutionService.java:286)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService.access$600(TaskletExecutionService.java:80)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:410)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.run(TaskletExecutionService.java:369)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.hazelcast.sql.impl.QueryException: Duplicate key
	at com.hazelcast.sql.impl.QueryException.error(QueryException.java:65)
	at com.hazelcast.sql.impl.QueryException.error(QueryException.java:57)
	at com.hazelcast.sql.impl.QueryException.error(QueryException.java:53)
	at com.hazelcast.jet.sql.impl.connector.map.InsertProcessorSupplier$InsertP.tryFlushQueue(InsertProcessorSupplier.java:169)
	at com.hazelcast.jet.sql.impl.connector.map.InsertProcessorSupplier$InsertP.tryProcess(InsertProcessorSupplier.java:127)
	at com.hazelcast.jet.core.AbstractProcessor.tryProcess0(AbstractProcessor.java:187)
	at com.hazelcast.jet.core.AbstractProcessor.process0(AbstractProcessor.java:601)
	at com.hazelcast.jet.core.AbstractProcessor.process(AbstractProcessor.java:108)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.lambda$processInbox$2f647568$2(ProcessorTasklet.java:489)
	at com.hazelcast.jet.function.RunnableEx.run(RunnableEx.java:31)
	at com.hazelcast.jet.impl.util.Util.doWithClassLoader(Util.java:537)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.processInbox(ProcessorTasklet.java:489)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:340)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:335)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:327)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:290)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:404)
	... 3 more
```

What I presume is happening is the job goes back to an earlier checkpoint, replays, and `INSERT INTO` fails with duplicate key.
(`SINK INTO` works fine)

Since scaling cannot be controlled, eg. a node crashes, this represents a latent problem with an `INSERT INTO` job.
It may run fine for weeks, then fail.

For `INSERT INTO` we should not allow a processing guarantee that is problematic to be specifed or defaulted.

**Comment by k-jamroz** [comment]
Default processing guarantee (NONE) offers the best performance. To avoid problems with duplicates in `INSERT` we would have to use `EXACTLY_ONCE` which is the most costly one. Much better solution is to use `SINK INTO` instead of `INSERT INTO`.

IMO there is no good solution that that will protect users from doing risky things (as in many cases in programming). We could generate warning if someone uses INSERT without `EXACTLY_ONCE`, but nobody will read it anyway.
