### ISSUE TITLE
com.hazelcast.jet.sql.SqlClientCompactQueryTest.testQueryOnPrimitive

### ISSUE THREAD

**Issue by mdumandag** [hazelcast/hazelcast#21940]
com.hazelcast.jet.sql.SqlClientCompactQueryTest.testQueryOnPrimitive[inMemoryFormat:OBJECT, clusterHaveUserClasses:true]

Failed on the PR builder

https://jenkins.hazelcast.com/job/Hazelcast-pr-builder/12485/testReport/junit/com.hazelcast.jet.sql/SqlClientCompactQueryTest/testQueryOnPrimitive_inMemoryFormat_OBJECT__clusterHaveUserClasses_true_/

<details><summary>Stacktrace:</summary>

```
com.hazelcast.sql.HazelcastSqlException: Proxy [hz:impl:replicatedMapService:__sql.catalog] was destroyed while being created. This may result in incomplete cleanup of resources.
	at com.hazelcast.sql.impl.client.SqlClientService.handleExecuteResponse(SqlClientService.java:280)
	at com.hazelcast.sql.impl.client.SqlClientService.execute(SqlClientService.java:128)
	at com.hazelcast.sql.SqlService.execute(SqlService.java:89)
	at com.hazelcast.jet.sql.SqlClientCompactQueryTest.testQueryOnPrimitive(SqlClientCompactQueryTest.java:119)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by krzysztofslusarski** [comment]
Fixed by #21671
