### ISSUE TITLE
com.hazelcast.jet.core.TopologyChangeTest.when_coordinatorLeavesDuringExecution_then_jobCompletes

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#21966]
_master_ (commit ea78d8acc79852e841af4d135b2c7083caf109bd)

Failed on Sonar build (Oracle JDK 11): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/1308/testReport/com.hazelcast.jet.core/TopologyChangeTest/when_coordinatorLeavesDuringExecution_then_jobCompletes_liteMemberFlags_0__/

It failed in variants `[liteMemberFlags(0)]`, `[liteMemberFlags(1)]` and `[liteMemberFlags(2)]`.

<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: unexpected exc: com.hazelcast.core.MemberLeftException: Member [127.0.0.1]:5701 - 73dfabf8-771b-4c95-afe7-690c5d8444a0 has left cluster!
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at com.hazelcast.jet.core.TopologyChangeTest.lambda$when_coordinatorLeavesDuringExecution_then_jobCompletes$4(TopologyChangeTest.java:311)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1236)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1338)
	at com.hazelcast.jet.core.TopologyChangeTest.when_coordinatorLeavesDuringExecution_then_jobCompletes(TopologyChangeTest.java:307)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

</details>

<details><summary>Hiccups were really high:</summary>

```
Hiccups measured while running test 'when_coordinatorLeavesDuringExecution_then_jobCompletes[liteMemberFlags(0)](com.hazelcast.jet.core.TopologyChangeTest):'
02:47:30, accumulated pauses: 4989 ms, max pause: 115 ms, pauses over 1000 ms: 0
02:47:35, accumulated pauses: 4985 ms, max pause: 18 ms, pauses over 1000 ms: 0
02:47:40, accumulated pauses: 4988 ms, max pause: 10 ms, pauses over 1000 ms: 0
02:47:45, accumulated pauses: 4983 ms, max pause: 23 ms, pauses over 1000 ms: 0
02:47:50, accumulated pauses: 4995 ms, max pause: 17 ms, pauses over 1000 ms: 0
02:47:55, accumulated pauses: 4982 ms, max pause: 10 ms, pauses over 1000 ms: 0
02:48:00, accumulated pauses: 4990 ms, max pause: 15 ms, pauses over 1000 ms: 0
02:48:05, accumulated pauses: 4983 ms, max pause: 13 ms, pauses over 1000 ms: 0
02:48:10, accumulated pauses: 4982 ms, max pause: 13 ms, pauses over 1000 ms: 0
02:48:15, accumulated pauses: 4988 ms, max pause: 15 ms, pauses over 1000 ms: 0
02:48:20, accumulated pauses: 4984 ms, max pause: 10 ms, pauses over 1000 ms: 0
02:48:25, accumulated pauses: 4993 ms, max pause: 10 ms, pauses over 1000 ms: 0
02:48:30, accumulated pauses: 4985 ms, max pause: 10 ms, pauses over 1000 ms: 0
02:48:35, accumulated pauses: 4984 ms, max pause: 14 ms, pauses over 1000 ms: 0
02:48:40, accumulated pauses: 4985 ms, max pause: 13 ms, pauses over 1000 ms: 0
02:48:45, accumulated pauses: 4985 ms, max pause: 15 ms, pauses over 1000 ms: 0
02:48:50, accumulated pauses: 4985 ms, max pause: 10 ms, pauses over 1000 ms: 0
02:48:55, accumulated pauses: 4990 ms, max pause: 11 ms, pauses over 1000 ms: 0
02:49:00, accumulated pauses: 4989 ms, max pause: 10 ms, pauses over 1000 ms: 0
02:49:05, accumulated pauses: 4979 ms, max pause: 10 ms, pauses over 1000 ms: 0
02:49:10, accumulated pauses: 4988 ms, max pause: 15 ms, pauses over 1000 ms: 0
02:49:15, accumulated pauses: 4987 ms, max pause: 10 ms, pauses over 1000 ms: 0
02:49:20, accumulated pauses: 4987 ms, max pause: 11 ms, pauses over 1000 ms: 0
02:49:25, accumulated pauses: 4988 ms, max pause: 19 ms, pauses over 1000 ms: 0
02:49:30, accumulated pauses: 4986 ms, max pause: 10 ms, pauses over 1000 ms: 0
02:49:35, accumulated pauses: 3298 ms, max pause: 288 ms, pauses over 1000 ms: 0
```

</details>

Cluster standard output can be found here - https://console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-sonar/1308/

**Comment by olukas** [comment]
It failed 7 times in row for Sonar build.

**Comment by olukas** [comment]
Failed also on:
- `OracleJDK8`: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-OracleJDK8-nightly/909/testReport/com.hazelcast.jet.core/TopologyChangeTest/when_coordinatorLeavesDuringExecution_then_jobCompletes_liteMemberFlags_0__/
- `ZuluJDK17`: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZuluJDK17-nightly/28/testReport/com.hazelcast.jet.core/TopologyChangeTest/when_coordinatorLeavesDuringExecution_then_jobCompletes_liteMemberFlags_0__/
- `IbmJDK8 in FIPS mode`: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-IbmJDK8-fips-nightly/450/testReport/com.hazelcast.jet.core/TopologyChangeTest/when_coordinatorLeavesDuringExecution_then_jobCompletes_liteMemberFlags_0__/
