### ISSUE TITLE
com.hazelcast.jet.core.SplitBrainTest

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#21969]
_master_ (commit d6a48525859512f2762d073a8cdfc220a0b9979b)

Failed on OracleJDK8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-OracleJDK8-nightly/909/testReport/com.hazelcast.jet.core/SplitBrainTest/when_quorumIsLostOnBothSides_then_jobRestartsAfterMerge/

Following tests failed with the similar exception:
- `com.hazelcast.jet.core.SplitBrainTest.when_quorumIsLostOnBothSides_then_jobRestartsAfterMerge`
- `com.hazelcast.jet.core.SplitBrainTest.when_quorumIsLostOnMinority_then_jobDoesNotRestartOnMinorityAndCancelledAfterMerge`
- `com.hazelcast.jet.core.SplitBrainTest.when_splitBrainProtectionIsDisabled_then_jobCompletesOnBothSides`
- `com.hazelcast.jet.core.SplitBrainTest.when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge`

<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: received com.hazelcast.core.MemberLeftException: Member [127.0.0.1]:5703 - 5ec53084-b6c1-4370-b68b-f2e0a52311d9 has left cluster!
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at com.hazelcast.jet.core.SplitBrainTest.lambda$null$14(SplitBrainTest.java:184)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:895)
	at com.hazelcast.jet.core.SplitBrainTest.lambda$when_quorumIsLostOnBothSides_then_jobRestartsAfterMerge$15(SplitBrainTest.java:184)
	at com.hazelcast.jet.core.JetSplitBrainTestSupport.testSplitBrain(JetSplitBrainTestSupport.java:128)
	at com.hazelcast.jet.core.SplitBrainTest.when_quorumIsLostOnBothSides_then_jobRestartsAfterMerge(SplitBrainTest.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

</details>

Standard output can be found here - https://console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-OracleJDK8-nightly/909/

**Comment by olukas** [comment]
Failed also on:
- `ZuluJDK17`: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZuluJDK17-nightly/28/testReport/com.hazelcast.jet.core/SplitBrainTest/when_splitBrainProtectionIsDisabled_then_jobCompletesOnBothSides/
- `IbmJDK8 in FIPS mode`: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-IbmJDK8-fips-nightly/450/testReport/com.hazelcast.jet.core/SplitBrainTest/when_splitBrainProtectionIsDisabled_then_jobCompletesOnBothSides/
