### ISSUE TITLE
com.hazelcast.client.ClientConnectionProcessListenerTest.clientNotAllowedInCluster

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#21970]
_master_ (commit f4d3d274bc7af9b10ed78d9bcbcfb176d5173d23)

Failed on CorrettoJDK11: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-CorrettoJDK11/183/testReport/com.hazelcast.client/ClientConnectionProcessListenerTest/clientNotAllowedInCluster/

<details><summary>Stacktrace:</summary>

```
Wanted but not invoked:
clientConnectionProcessListener.clientNotAllowedInCluster(
    [127.0.0.1]:5701
);
-> at com.hazelcast.client.ClientConnectionProcessListenerTest.clientNotAllowedInCluster(ClientConnectionProcessListenerTest.java:238)

However, there were exactly 3 interactions with this mock:
clientConnectionProcessListener.possibleAddressesCollected(
    [[127.0.0.1]:5701, [127.0.0.1]:5702, [127.0.0.1]:5703]
);
-> at com.hazelcast.client.impl.connection.tcp.ExceptionCatchingConnectionProcessListener.lambda$possibleAddressesCollected$3(ExceptionCatchingConnectionProcessListener.java:61)

clientConnectionProcessListener.attemptingToConnectToAddress(
    [127.0.0.1]:5701
);
-> at com.hazelcast.client.impl.connection.tcp.ExceptionCatchingConnectionProcessListener.lambda$attemptingToConnectToAddress$0(ExceptionCatchingConnectionProcessListener.java:46)

clientConnectionProcessListener.clusterConnectionFailed(
    "clientNotAllowedInCluster"
);
-> at com.hazelcast.client.impl.connection.tcp.ExceptionCatchingConnectionProcessListener.lambda$clusterConnectionFailed$7(ExceptionCatchingConnectionProcessListener.java:81)


	at com.hazelcast.client.ClientConnectionProcessListenerTest.clientNotAllowedInCluster(ClientConnectionProcessListenerTest.java:238)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

</details>

<details><summary>Standard output:</summary>

```
05:19:33,223  INFO |clientNotAllowedInCluster| - [MetricsConfigHelper] clientNotAllowedInCluster - [LOCAL] [clientNotAllowedInCluster] [5.2-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
05:19:33,231  INFO |clientNotAllowedInCluster| - [logo] clientNotAllowedInCluster - [127.0.0.1]:5701 [clientNotAllowedInCluster] [5.2-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
05:19:33,232  INFO |clientNotAllowedInCluster| - [system] clientNotAllowedInCluster - [127.0.0.1]:5701 [clientNotAllowedInCluster] [5.2-SNAPSHOT] Copyright (c) 2008-2022, Hazelcast, Inc. All Rights Reserved.
05:19:33,232  INFO |clientNotAllowedInCluster| - [system] clientNotAllowedInCluster - [127.0.0.1]:5701 [clientNotAllowedInCluster] [5.2-SNAPSHOT] Hazelcast Platform 5.2-SNAPSHOT (20220809 - f4d3d27) starting at [127.0.0.1]:5701
05:19:33,232  INFO |clientNotAllowedInCluster| - [system] clientNotAllowedInCluster - [127.0.0.1]:5701 [clientNotAllowedInCluster] [5.2-SNAPSHOT] Cluster name: clientNotAllowedInCluster
05:19:33,232  INFO |clientNotAllowedInCluster| - [system] clientNotAllowedInCluster - [127.0.0.1]:5701 [clientNotAllowedInCluster] [5.2-SNAPSHOT] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed. For more information, see the documentation for Integrity Checker.
05:19:33,232  INFO |clientNotAllowedInCluster| - [system] clientNotAllowedInCluster - [127.0.0.1]:5701 [clientNotAllowedInCluster] [5.2-SNAPSHOT] The Jet engine is disabled.
To enable the Jet engine on the members, do one of the following:
  - Change member config using Java API: config.getJetConfig().setEnabled(true)
  - Change XML/YAML configuration property: Set hazelcast.jet.enabled to true
  - Add system property: -Dhz.jet.enabled=true (for Hazelcast embedded, works only when loading config via Config.load)
  - Add environment variable: HZ_JET_ENABLED=true (recommended when running container image. For Hazelcast embedded, works only when loading config via Config.load)
05:19:33,275  INFO |clientNotAllowedInCluster| - [MetricsConfigHelper] clientNotAllowedInCluster - [127.0.0.1]:5701 [clientNotAllowedInCluster] [5.2-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
05:19:33,323  INFO |clientNotAllowedInCluster| - [Node] clientNotAllowedInCluster - [127.0.0.1]:5701 [clientNotAllowedInCluster] [5.2-SNAPSHOT] Using Multicast discovery
05:19:33,324  WARN |clientNotAllowedInCluster| - [CPSubsystem] clientNotAllowedInCluster - [127.0.0.1]:5701 [clientNotAllowedInCluster] [5.2-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
05:19:33,374  INFO |clientNotAllowedInCluster| - [Diagnostics] clientNotAllowedInCluster - [127.0.0.1]:5701 [clientNotAllowedInCluster] [5.2-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
05:19:33,374  INFO |clientNotAllowedInCluster| - [LifecycleService] clientNotAllowedInCluster - [127.0.0.1]:5701 [clientNotAllowedInCluster] [5.2-SNAPSHOT] [127.0.0.1]:5701 is STARTING
05:19:35,644  INFO |clientNotAllowedInCluster| - [ClusterService] clientNotAllowedInCluster - [127.0.0.1]:5701 [clientNotAllowedInCluster] [5.2-SNAPSHOT] 

Members {size:1, ver:1} [
	Member [127.0.0.1]:5701 - a1a1a078-4e22-4315-8350-021ba8413b33 this
]

05:19:35,646  INFO |clientNotAllowedInCluster| - [LifecycleService] clientNotAllowedInCluster - [127.0.0.1]:5701 [clientNotAllowedInCluster] [5.2-SNAPSHOT] [127.0.0.1]:5701 is STARTED
05:19:35,665  INFO |clientNotAllowedInCluster| - [HealthMonitor] hz.brave_villani.HealthMonitor - [127.0.0.1]:5701 [clientNotAllowedInCluster] [5.2-SNAPSHOT] processors=8, physical.memory.total=377.8G, physical.memory.free=100.9G, swap.space.total=8.0G, swap.space.free=8.0G, heap.memory.used=928.3M, heap.memory.free=3.1G, heap.memory.total=4.0G, heap.memory.max=4.0G, heap.memory.used/total=22.66%, heap.memory.used/max=22.66%, minor.gc.count=143, minor.gc.time=8720ms, major.gc.count=1, major.gc.time=292ms, load.process=0.00%, load.system=96.43%, load.systemAverage=57.37, thread.count=355, thread.peakCount=1847, cluster.timeDiff=0, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=0, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=0, clientEndpoint.count=0, connection.active.count=0, client.connection.count=0, connection.count=0
05:19:35,680  INFO |clientNotAllowedInCluster| - [ClientInvocationService] clientNotAllowedInCluster - hz.client_4270 [clientNotAllowedInCluster] [5.2-SNAPSHOT] Running with 2 response threads, dynamic=true
05:19:35,684  INFO |clientNotAllowedInCluster| - [LifecycleService] clientNotAllowedInCluster - hz.client_4270 [clientNotAllowedInCluster] [5.2-SNAPSHOT] HazelcastClient 5.2-SNAPSHOT (20220809 - f4d3d27) is STARTING
05:19:35,686  INFO |clientNotAllowedInCluster| - [LifecycleService] clientNotAllowedInCluster - hz.client_4270 [clientNotAllowedInCluster] [5.2-SNAPSHOT] HazelcastClient 5.2-SNAPSHOT (20220809 - f4d3d27) is STARTED
05:19:35,689  INFO |clientNotAllowedInCluster| - [ClientConnectionManager] clientNotAllowedInCluster - hz.client_4270 [clientNotAllowedInCluster] [5.2-SNAPSHOT] Trying to connect to cluster: clientNotAllowedInCluster
05:19:35,689 ERROR |clientNotAllowedInCluster| - [ClientConnectionManager] clientNotAllowedInCluster - hz.client_4270 [clientNotAllowedInCluster] [5.2-SNAPSHOT] exception thrown by ClientConnectionProcessListener
java.lang.RuntimeException: null
	at com.hazelcast.client.ClientConnectionProcessListenerTest$ExceptionThrowingListener.possibleAddressesCollected(ClientConnectionProcessListenerTest.java:79) ~[test-classes/:?]
	at com.hazelcast.client.impl.connection.tcp.ExceptionCatchingConnectionProcessListener.lambda$possibleAddressesCollected$3(ExceptionCatchingConnectionProcessListener.java:61) ~[classes/:?]
	at com.hazelcast.client.impl.connection.tcp.ExceptionCatchingConnectionProcessListener.runSafely(ExceptionCatchingConnectionProcessListener.java:38) ~[classes/:?]
	at com.hazelcast.client.impl.connection.tcp.ExceptionCatchingConnectionProcessListener.possibleAddressesCollected(ExceptionCatchingConnectionProcessListener.java:61) ~[classes/:?]
	at com.hazelcast.client.impl.management.ListenerAggregate.lambda$possibleAddressesCollected$3(ClientConnectionProcessListener.java:53) ~[classes/:?]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807) ~[?:?]
	at com.hazelcast.client.impl.management.ListenerAggregate.possibleAddressesCollected(ClientConnectionProcessListener.java:53) ~[classes/:?]
	at com.hazelcast.client.impl.spi.impl.DefaultAddressProvider.loadAddresses(DefaultAddressProvider.java:67) ~[classes/:?]
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.getPossibleMemberAddresses(TcpClientConnectionManager.java:591) ~[classes/:?]
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.doConnectToCandidateCluster(TcpClientConnectionManager.java:532) ~[classes/:?]
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.doConnectToCluster(TcpClientConnectionManager.java:425) ~[classes/:?]
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.connectToCluster(TcpClientConnectionManager.java:386) ~[classes/:?]
	at com.hazelcast.client.impl.clientside.HazelcastClientInstanceImpl.start(HazelcastClientInstanceImpl.java:389) ~[classes/:?]
	at com.hazelcast.client.HazelcastClient.constructHazelcastClient(HazelcastClient.java:472) ~[classes/:?]
	at com.hazelcast.client.HazelcastClient.newHazelcastClientInternal(HazelcastClient.java:420) ~[classes/:?]
	at com.hazelcast.client.HazelcastClient.newHazelcastFailoverClient(HazelcastClient.java:188) ~[classes/:?]
	at com.hazelcast.client.ClientConnectionProcessListenerTest.clientNotAllowedInCluster(ClientConnectionProcessListenerTest.java:228) ~[test-classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) ~[junit-4.13.2.jar:4.13.2]
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115) ~[test-classes/:?]
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107) ~[test-classes/:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
05:19:35,690 ERROR |clientNotAllowedInCluster| - [ClientConnectionManager] clientNotAllowedInCluster - hz.client_4270 [clientNotAllowedInCluster] [5.2-SNAPSHOT] exception thrown by ClientConnectionProcessListener
java.lang.RuntimeException: null
	at com.hazelcast.client.ClientConnectionProcessListenerTest$ExceptionThrowingListener.attemptingToConnectToAddress(ClientConnectionProcessListenerTest.java:64) ~[test-classes/:?]
	at com.hazelcast.client.impl.connection.tcp.ExceptionCatchingConnectionProcessListener.lambda$attemptingToConnectToAddress$0(ExceptionCatchingConnectionProcessListener.java:46) ~[classes/:?]
	at com.hazelcast.client.impl.connection.tcp.ExceptionCatchingConnectionProcessListener.runSafely(ExceptionCatchingConnectionProcessListener.java:38) ~[classes/:?]
	at com.hazelcast.client.impl.connection.tcp.ExceptionCatchingConnectionProcessListener.attemptingToConnectToAddress(ExceptionCatchingConnectionProcessListener.java:46) ~[classes/:?]
	at com.hazelcast.client.impl.management.ListenerAggregate.lambda$attemptingToConnectToAddress$0(ClientConnectionProcessListener.java:38) ~[classes/:?]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807) ~[?:?]
	at com.hazelcast.client.impl.management.ListenerAggregate.attemptingToConnectToAddress(ClientConnectionProcessListener.java:38) ~[classes/:?]
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.reportAddressConnectionAttempt(TcpClientConnectionManager.java:768) ~[classes/:?]
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.doConnectToCandidateCluster(TcpClientConnectionManager.java:538) ~[classes/:?]
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.doConnectToCluster(TcpClientConnectionManager.java:425) ~[classes/:?]
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.connectToCluster(TcpClientConnectionManager.java:386) ~[classes/:?]
	at com.hazelcast.client.impl.clientside.HazelcastClientInstanceImpl.start(HazelcastClientInstanceImpl.java:389) ~[classes/:?]
	at com.hazelcast.client.HazelcastClient.constructHazelcastClient(HazelcastClient.java:472) ~[classes/:?]
	at com.hazelcast.client.HazelcastClient.newHazelcastClientInternal(HazelcastClient.java:420) ~[classes/:?]
	at com.hazelcast.client.HazelcastClient.newHazelcastFailoverClient(HazelcastClient.java:188) ~[classes/:?]
	at com.hazelcast.client.ClientConnectionProcessListenerTest.clientNotAllowedInCluster(ClientConnectionProcessListenerTest.java:228) ~[test-classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) ~[junit-4.13.2.jar:4.13.2]
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115) ~[test-classes/:?]
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107) ~[test-classes/:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
05:19:35,690  INFO |clientNotAllowedInCluster| - [ClientConnectionManager] clientNotAllowedInCluster - hz.client_4270 [clientNotAllowedInCluster] [5.2-SNAPSHOT] Trying to connect to [127.0.0.1]:5701
05:19:35,692 DEBUG |clientNotAllowedInCluster| - [AuthenticationMessageTask] hz.brave_villani.priority-generic-operation.thread-0 - [127.0.0.1]:5701 [clientNotAllowedInCluster] [5.2-SNAPSHOT] Processing authentication with clientUuid 69e60754-1dbb-4afb-861f-51dcef85fc24 and clientName hz.client_4270
05:19:35,693  INFO |clientNotAllowedInCluster| - [AuthenticationMessageTask] hz.brave_villani.priority-generic-operation.thread-0 - [127.0.0.1]:5701 [clientNotAllowedInCluster] [5.2-SNAPSHOT] Received auth from Connection[id=1, /127.0.0.1:5701->/127.0.0.1:47601, qualifier=null, endpoint=[127.0.0.1]:47601, remoteUuid=69e60754-1dbb-4afb-861f-51dcef85fc24, alive=true, connectionType=JVM, planeIndex=-1], successfully authenticated, clientUuid: 69e60754-1dbb-4afb-861f-51dcef85fc24, client name: hz.client_4270, client version: 5.2-SNAPSHOT
05:19:35,693  WARN |clientNotAllowedInCluster| - [ClientConnectionManager] clientNotAllowedInCluster - hz.client_4270 [clientNotAllowedInCluster] [5.2-SNAPSHOT] Cluster does not support failover. This feature is available in Hazelcast Enterprise
05:19:35,694  WARN |clientNotAllowedInCluster| - [TcpClientConnection] clientNotAllowedInCluster - hz.client_4270 [clientNotAllowedInCluster] [5.2-SNAPSHOT] ClientConnection{alive=false, connectionId=1, channel=NioChannel{/127.0.0.1:47601->/127.0.0.1:5701}, remoteAddress=null, lastReadTime=2022-08-09 05:19:35.693, lastWriteTime=2022-08-09 05:19:35.691, closedTime=2022-08-09 05:19:35.694, connected server version=null} closed. Reason: Failed to authenticate connection
com.hazelcast.client.ClientNotAllowedInClusterException: Client is not allowed in the cluster
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.checkAuthenticationResponse(TcpClientConnectionManager.java:1054) ~[classes/:?]
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.onAuthenticated(TcpClientConnectionManager.java:948) ~[classes/:?]
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.getOrConnectToAddress(TcpClientConnectionManager.java:651) ~[classes/:?]
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.lambda$doConnectToCandidateCluster$3(TcpClientConnectionManager.java:540) ~[classes/:?]
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.connect(TcpClientConnectionManager.java:475) ~[classes/:?]
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.doConnectToCandidateCluster(TcpClientConnectionManager.java:539) ~[classes/:?]
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.doConnectToCluster(TcpClientConnectionManager.java:425) ~[classes/:?]
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.connectToCluster(TcpClientConnectionManager.java:386) ~[classes/:?]
	at com.hazelcast.client.impl.clientside.HazelcastClientInstanceImpl.start(HazelcastClientInstanceImpl.java:389) ~[classes/:?]
	at com.hazelcast.client.HazelcastClient.constructHazelcastClient(HazelcastClient.java:472) ~[classes/:?]
	at com.hazelcast.client.HazelcastClient.newHazelcastClientInternal(HazelcastClient.java:420) ~[classes/:?]
	at com.hazelcast.client.HazelcastClient.newHazelcastFailoverClient(HazelcastClient.java:188) ~[classes/:?]
	at com.hazelcast.client.ClientConnectionProcessListenerTest.clientNotAllowedInCluster(ClientConnectionProcessListenerTest.java:228) ~[test-classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) ~[junit-4.13.2.jar:4.13.2]
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115) ~[test-classes/:?]
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107) ~[test-classes/:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
05:19:35,694  WARN |clientNotAllowedInCluster| - [ClientConnectionManager] clientNotAllowedInCluster - hz.client_4270 [clientNotAllowedInCluster] [5.2-SNAPSHOT] Exception during initial connection to [127.0.0.1]:5701: com.hazelcast.client.ClientNotAllowedInClusterException: Client is not allowed in the cluster
05:19:35,694  WARN |clientNotAllowedInCluster| - [ClientConnectionManager] clientNotAllowedInCluster - hz.client_4270 [clientNotAllowedInCluster] [5.2-SNAPSHOT] Stopped trying on the cluster: clientNotAllowedInCluster reason: Client is not allowed in the cluster
05:19:35,694 ERROR |clientNotAllowedInCluster| - [ClientConnectionManager] clientNotAllowedInCluster - hz.client_4270 [clientNotAllowedInCluster] [5.2-SNAPSHOT] exception thrown by ClientConnectionProcessListener
java.lang.RuntimeException: null
	at com.hazelcast.client.ClientConnectionProcessListenerTest$ExceptionThrowingListener.clusterConnectionFailed(ClientConnectionProcessListenerTest.java:99) ~[test-classes/:?]
	at com.hazelcast.client.impl.connection.tcp.ExceptionCatchingConnectionProcessListener.lambda$clusterConnectionFailed$7(ExceptionCatchingConnectionProcessListener.java:81) ~[classes/:?]
	at com.hazelcast.client.impl.connection.tcp.ExceptionCatchingConnectionProcessListener.runSafely(ExceptionCatchingConnectionProcessListener.java:38) ~[classes/:?]
	at com.hazelcast.client.impl.connection.tcp.ExceptionCatchingConnectionProcessListener.clusterConnectionFailed(ExceptionCatchingConnectionProcessListener.java:81) ~[classes/:?]
	at com.hazelcast.client.impl.management.ListenerAggregate.lambda$clusterConnectionFailed$7(ClientConnectionProcessListener.java:73) ~[classes/:?]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807) ~[?:?]
	at com.hazelcast.client.impl.management.ListenerAggregate.clusterConnectionFailed(ClientConnectionProcessListener.java:73) ~[classes/:?]
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.doConnectToCandidateCluster(TcpClientConnectionManager.java:557) ~[classes/:?]
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.doConnectToCluster(TcpClientConnectionManager.java:425) ~[classes/:?]
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.connectToCluster(TcpClientConnectionManager.java:386) ~[classes/:?]
	at com.hazelcast.client.impl.clientside.HazelcastClientInstanceImpl.start(HazelcastClientInstanceImpl.java:389) ~[classes/:?]
	at com.hazelcast.client.HazelcastClient.constructHazelcastClient(HazelcastClient.java:472) ~[classes/:?]
	at com.hazelcast.client.HazelcastClient.newHazelcastClientInternal(HazelcastClient.java:420) ~[classes/:?]
	at com.hazelcast.client.HazelcastClient.newHazelcastFailoverClient(HazelcastClient.java:188) ~[classes/:?]
	at com.hazelcast.client.ClientConnectionProcessListenerTest.clientNotAllowedInCluster(ClientConnectionProcessListenerTest.java:228) ~[test-classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) ~[junit-4.13.2.jar:4.13.2]
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115) ~[test-classes/:?]
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107) ~[test-classes/:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
05:19:35,694  INFO |clientNotAllowedInCluster| - [ClientConnectionManager] clientNotAllowedInCluster - hz.client_4270 [clientNotAllowedInCluster] [5.2-SNAPSHOT] Unable to connect to any address from the cluster with name: clientNotAllowedInCluster. The following addresses were tried: []
05:19:35,694  INFO |clientNotAllowedInCluster| - [LifecycleService] clientNotAllowedInCluster - hz.client_4270 [clientNotAllowedInCluster] [5.2-SNAPSHOT] HazelcastClient 5.2-SNAPSHOT (20220809 - f4d3d27) is SHUTTING_DOWN
05:19:35,694  INFO |clientNotAllowedInCluster| - [TcpServerConnection] hz.brave_villani.IO.thread-in-0 - [127.0.0.1]:5701 [clientNotAllowedInCluster] [5.2-SNAPSHOT] Connection[id=1, /127.0.0.1:5701->/127.0.0.1:47601, qualifier=null, endpoint=[127.0.0.1]:47601, remoteUuid=69e60754-1dbb-4afb-861f-51dcef85fc24, alive=false, connectionType=JVM, planeIndex=-1] closed. Reason: Connection closed by the other side
05:19:35,695  INFO |clientNotAllowedInCluster| - [ClientEndpointManager] hz.brave_villani.event-45651 - [127.0.0.1]:5701 [clientNotAllowedInCluster] [5.2-SNAPSHOT] Destroying ClientEndpoint{connection=Connection[id=1, /127.0.0.1:5701->/127.0.0.1:47601, qualifier=null, endpoint=[127.0.0.1]:47601, remoteUuid=69e60754-1dbb-4afb-861f-51dcef85fc24, alive=false, connectionType=JVM, planeIndex=-1], clientUuid=69e60754-1dbb-4afb-861f-51dcef85fc24, clientName=hz.client_4270, authenticated=true, clientVersion=5.2-SNAPSHOT, creationTime=1660022375692, latest clientAttributes=null, labels=[]}
05:19:35,695  INFO |clientNotAllowedInCluster| - [LifecycleService] clientNotAllowedInCluster - hz.client_4270 [clientNotAllowedInCluster] [5.2-SNAPSHOT] HazelcastClient 5.2-SNAPSHOT (20220809 - f4d3d27) is SHUTDOWN
05:19:36,219  INFO |clientNotAllowedInCluster| - [LifecycleService] main - [127.0.0.1]:5701 [clientNotAllowedInCluster] [5.2-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
05:19:36,219  INFO |clientNotAllowedInCluster| - [Node] main - [127.0.0.1]:5701 [clientNotAllowedInCluster] [5.2-SNAPSHOT] Shutting down multicast service...
05:19:36,219  INFO |clientNotAllowedInCluster| - [Node] main - [127.0.0.1]:5701 [clientNotAllowedInCluster] [5.2-SNAPSHOT] Shutting down connection manager...
05:19:36,221  INFO |clientNotAllowedInCluster| - [Node] main - [127.0.0.1]:5701 [clientNotAllowedInCluster] [5.2-SNAPSHOT] Shutting down node engine...
05:19:36,224  INFO |clientNotAllowedInCluster| - [NodeExtension] main - [127.0.0.1]:5701 [clientNotAllowedInCluster] [5.2-SNAPSHOT] Destroying node NodeExtension.
05:19:36,224  INFO |clientNotAllowedInCluster| - [Node] main - [127.0.0.1]:5701 [clientNotAllowedInCluster] [5.2-SNAPSHOT] Hazelcast Shutdown is completed in 5 ms.
05:19:36,224  INFO |clientNotAllowedInCluster| - [LifecycleService] main - [127.0.0.1]:5701 [clientNotAllowedInCluster] [5.2-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
BuildInfo right after clientNotAllowedInCluster(com.hazelcast.client.ClientConnectionProcessListenerTest): BuildInfo{version='5.2-SNAPSHOT', build='20220809', buildNumber=20220809, revision=f4d3d27, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'clientNotAllowedInCluster(com.hazelcast.client.ClientConnectionProcessListenerTest):'
05:19:30, accumulated pauses: 111 ms, max pause: 8 ms, pauses over 1000 ms: 0
05:19:35, accumulated pauses: 493 ms, max pause: 473 ms, pauses over 1000 ms: 0
```

</details>

**Comment by arodionov** [comment]
Failed during PR build: 
https://jenkins.hazelcast.com/job/Hazelcast-pr-builder/12931/testReport/com.hazelcast.client.impl.management/ClientConnectionProcessListenerTest/clientNotAllowedInCluster/
