### ISSUE TITLE
classloading.ThreadLeakTest.testThreadLeakUtils [HZ-1702]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#21991]
_master_ (commit 5bcb6c0fa7d5f3ea4b5f8ad912d87a6be8fb60f8)

Failed on ZingJDK8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZingJDK8/453/testReport/classloading/ThreadLeakTest/testThreadLeakUtils/

<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: Expected exactly one running thread expected:<1> but was:<2>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at classloading.ThreadLeakTest.testThreadLeakUtils(ThreadLeakTest.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

</details>

<details><summary>Standard output:</summary>

```
10:58:50,581 ERROR |testThreadLeakUtils| - [ThreadLeakTestUtils] testThreadLeakUtils - There should be one thread running!
-> leaking-thread (id: 984650) (group: main) (daemon: true) (alive: true) (interrupted: false) (state: WAITING)
[sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(LockSupport.java:175), java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836), java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997), java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304), java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231), classloading.ThreadLeakTest$1.run(ThreadLeakTest.java:65)]

-> HikariPool-3 connection adder (id: 984651) (group: main) (daemon: true) (alive: true) (interrupted: false) (state: TIMED_WAITING)
[org.h2.engine.Engine.openSession(Engine.java:49), org.h2.engine.Engine.openSession(Engine.java:222), org.h2.engine.Engine.createSession(Engine.java:201), org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338), org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122), org.h2.Driver.connect(Driver.java:59), com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:121), com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364), com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206), com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476), com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71), com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:726), com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712), java.util.concurrent.FutureTask.run(FutureTask.java:266), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624), java.lang.Thread.run(Thread.java:748)]
```

</details>

**Comment by olukas** [comment]
Failed on ZuluJDK17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZuluJDK17/47/testReport/classloading/ThreadLeakTest/testThreadLeakUtils/

However stacktrace is different.
<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: Expected to get null, but found running threads expected null, but was:<[Ljava.lang.Thread;@32d4ade5>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotNull(Assert.java:756)
	at org.junit.Assert.assertNull(Assert.java:738)
	at classloading.ThreadLeakTest.testThreadLeakUtils(ThreadLeakTest.java:81)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

</details>

<details><summary>Standard output:</summary>

```
21:29:52,003 ERROR |testThreadLeakUtils| - [ThreadLeakTestUtils] testThreadLeakUtils - There should be one thread running!
-> leaking-thread (id: 1091516) (group: main) (daemon: true) (alive: true) (interrupted: false) (state: WAITING)
[java.base@17/jdk.internal.misc.Unsafe.park(Native Method), java.base@17/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211), java.base@17/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:715), java.base@17/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1047), java.base@17/java.util.concurrent.CountDownLatch.await(CountDownLatch.java:230), app//classloading.ThreadLeakTest$1.run(ThreadLeakTest.java:65)]

21:29:52,023 ERROR |testThreadLeakUtils| - [ThreadLeakTestUtils] testThreadLeakUtils - There should be no threads running!
-> HikariPool-3 connection adder (id: 1091518) (group: main) (daemon: true) (alive: true) (interrupted: false) (state: TIMED_WAITING)
[java.base@17/jdk.internal.misc.Unsafe.park(Native Method), java.base@17/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252), java.base@17/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:1672), java.base@17/java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:460), java.base@17/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1061), java.base@17/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122), java.base@17/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@17/java.lang.Thread.run(Thread.java:833)]

-> HikariPool-3 connection adder (id: 1091517) (group: main) (daemon: true) (alive: true) (interrupted: false) (state: TIMED_WAITING)
[java.base@17/jdk.internal.misc.Unsafe.park(Native Method), java.base@17/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252), java.base@17/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:1672), java.base@17/java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:460), java.base@17/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1061), java.base@17/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122), java.base@17/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@17/java.lang.Thread.run(Thread.java:833)]
```

</details>

**Comment by olukas** [comment]
Failed on MicrosoftJDK11: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-MicrosoftJDK11/28/testReport/classloading/ThreadLeakTest/testThreadLeakUtils/

**Comment by olukas** [comment]
Failed on:
- `ZingJDK8`: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZingJDK8/462/testReport/classloading/ThreadLeakTest/testThreadLeakUtils/
- `ZuluJDK8`: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZuluJDK8/204/testReport/classloading/ThreadLeakTest/testThreadLeakUtils/

**Comment by olukas** [comment]
Failed on MicrosoftJDK11: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-MicrosoftJDK11/30/testReport/classloading/ThreadLeakTest/testThreadLeakUtils/

**Comment by olukas** [comment]
Failed on ZuluJDK8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZuluJDK8/206/testReport/classloading/ThreadLeakTest/testThreadLeakUtils/

**Comment by ahmetmircik** [comment]
closed by https://github.com/hazelcast/hazelcast/pull/22372

**Comment by ahmetmircik** [comment]
reopening since https://github.com/hazelcast/hazelcast/pull/22372 was reverted.

**Comment by ahmetmircik** [comment]
closed via https://github.com/hazelcast/hazelcast/pull/22422

**Comment by Patras3** [comment]
Reopening as issue occurred again on: _master_ (commit 285517dcd7b6c95a2d751f97140a1f046230adca)
with Openj9-17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Openj9-11/100/testReport/junit/classloading/ThreadLeakTest/testThreadLeakUtils/
<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: Expected to get null, but found running threads expected null, but was:<[Ljava.lang.Thread;@33ef61d1>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotNull(Assert.java:756)
	at org.junit.Assert.assertNull(Assert.java:738)
	at classloading.ThreadLeakTest.testThreadLeakUtils(ThreadLeakTest.java:81)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:866)

```
</details>
<details><summary>Standard output:</summary>

```
09:33:58,663 ERROR |testThreadLeakUtils| - [ThreadLeakTestUtils] testThreadLeakUtils - There should be one thread running!
-> leaking-thread (id: 1104170) (group: main) (daemon: true) (alive: true) (interrupted: false) (state: WAITING)
[java.base/jdk.internal.misc.Unsafe.park(Native Method), java.base/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194), java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:885), java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1039), java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1345), java.base/java.util.concurrent.CountDownLatch.await(CountDownLatch.java:232), classloading.ThreadLeakTest$1.run(ThreadLeakTest.java:65)]

09:33:58,712 ERROR |testThreadLeakUtils| - [ThreadLeakTestUtils] testThreadLeakUtils - There should be no threads running!
-> HikariPool-3 connection adder (id: 1104172) (group: main) (daemon: true) (alive: true) (interrupted: false) (state: TIMED_WAITING)
[org.h2.command.Tokenizer.readIdentifierOrKeyword(Tokenizer.java:1006), org.h2.command.Tokenizer.readC(Tokenizer.java:609), org.h2.command.Tokenizer.tokenize(Tokenizer.java:375), org.h2.command.Parser.initialize(Parser.java:5877), org.h2.command.Parser.parse(Parser.java:657), org.h2.command.Parser.prepareCommand(Parser.java:569), org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:631), org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:554), org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1120), org.h2.jdbc.JdbcConnection.isReadOnly(JdbcConnection.java:537), com.zaxxer.hikari.pool.PoolBase.setupConnection(PoolBase.java:408), com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:369), com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206), com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476), com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71), com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:726), com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712), java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264), java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128), java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628), java.base/java.lang.Thread.run(Thread.java:866)]

-> HikariPool-3 connection adder (id: 1104171) (group: main) (daemon: true) (alive: true) (interrupted: false) (state: TIMED_WAITING)
[java.base/java.util.concurrent.ConcurrentHashMap.replaceNode(ConcurrentHashMap.java:1111), java.base/java.util.concurrent.ConcurrentHashMap.remove(ConcurrentHashMap.java:1102), java.base/java.util.Properties.remove(Properties.java:1345), org.h2.engine.ConnectionInfo.removeProperty(ConnectionInfo.java:443), org.h2.engine.ConnectionInfo.removeProperty(ConnectionInfo.java:429), org.h2.engine.Engine.openSession(Engine.java:51), org.h2.engine.Engine.openSession(Engine.java:222), org.h2.engine.Engine.createSession(Engine.java:201), org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338), org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122), org.h2.Driver.connect(Driver.java:59), com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:121), com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364), com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206), com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476), com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71), com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:726), com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712), java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264), java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128), java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628), java.base/java.lang.Thread.run(Thread.java:866)]


```
</details>

**Comment by Patras3** [comment]
`Expected to get null, but found running threads expected null, but was:<[Ljava.lang.Thread;@71516254>`
Failed again on _master_ with CorrettoJDK17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-CorrettoJDK17/59/testReport/junit/classloading/ThreadLeakTest/testThreadLeakUtils/

**Comment by Patras3** [comment]
Failed again on: _5.2.z_ with CorrettoJDK8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-CorrettoJDK8/56/testReport/classloading/ThreadLeakTest/testThreadLeakUtils/
`java.lang.AssertionError: Expected exactly one running thread expected:<1> but was:<3>`

**Comment by olukas** [comment]
Failed again on _5.2.z_ with CorrettoJDK8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-CorrettoJDK8/57/testReport/classloading/ThreadLeakTest/testThreadLeakUtils/
