### ISSUE TITLE
com.hazelcast.mapstore.GenericMapStoreTest.whenStoreAll_thenTableContainsRow

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#21992]
_master_ (commit 5bcb6c0fa7d5f3ea4b5f8ad912d87a6be8fb60f8)

Failed on ZingJDK8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZingJDK8/453/testReport/com.hazelcast.mapstore/GenericMapStoreTest/whenStoreAll_thenTableContainsRow/

<details><summary>Stacktrace:</summary>

```
com.hazelcast.core.HazelcastException: MapStore init failed for map: people_o_1862a3bd_e575_41e5_acb5_91d93265ab4a
	at com.hazelcast.mapstore.GenericMapStore.awaitInitFinished(GenericMapStore.java:551)
	at com.hazelcast.mapstore.GenericMapStore.storeAll(GenericMapStore.java:508)
	at com.hazelcast.mapstore.GenericMapStoreTest.whenStoreAll_thenTableContainsRow(GenericMapStoreTest.java:469)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

</details>

<details><summary>Standard output:</summary>

```
11:48:49,241  WARN || - [HazelcastInstanceFactory] Time-limited test - WARNING: Classpath misconfiguration: found multiple META-INF/services/com.hazelcast.instance.impl.NodeExtension resources: jar:file:/home/ec2-user/~/jenkins/workspace/Hazelcast-master-ZingJDK8/hazelcast/target/hazelcast-5.2-SNAPSHOT.jar!/META-INF/services/com.hazelcast.instance.impl.NodeExtension, jar:file:/home/ec2-user/~/jenkins/workspace/Hazelcast-master-ZingJDK8/hazelcast/target/hazelcast-5.2-SNAPSHOT-tests.jar!/META-INF/services/com.hazelcast.instance.impl.NodeExtension
11:48:49,385  INFO || - [MetricsConfigHelper] Time-limited test - [LOCAL] [dev] [5.2-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
11:48:49,528  INFO || - [logo] Time-limited test - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
11:48:49,528  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Copyright (c) 2008-2022, Hazelcast, Inc. All Rights Reserved.
11:48:49,528  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Hazelcast Platform 5.2-SNAPSHOT (20220816 - 5bcb6c0) starting at [127.0.0.1]:5701
11:48:49,528  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Cluster name: dev
11:48:49,529  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed. For more information, see the documentation for Integrity Checker.
11:48:49,529  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Jet is enabled
11:48:49,607  INFO || - [MetricsConfigHelper] Time-limited test - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
11:48:51,497  WARN || - [CPSubsystem] Time-limited test - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
11:48:52,407  INFO || - [JetServiceBackend] Time-limited test - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Setting number of cooperative threads and default parallelism to 2
11:48:52,617  INFO || - [Diagnostics] Time-limited test - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
11:48:52,635  INFO || - [LifecycleService] Time-limited test - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] [127.0.0.1]:5701 is STARTING
11:48:52,678  INFO || - [ClusterService] Time-limited test - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] 

Members {size:1, ver:1} [
	Member [127.0.0.1]:5701 - 50cf386c-8a72-4b50-8c7f-a7028e87ed09 this
]

11:48:52,704  INFO || - [JobCoordinationService] Time-limited test - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Jet started scanning for jobs
11:48:52,710  INFO || - [LifecycleService] Time-limited test - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] [127.0.0.1]:5701 is STARTED
11:48:52,858  INFO || - [MetricsConfigHelper] Time-limited test - [LOCAL] [dev] [5.2-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
11:48:52,861  INFO || - [logo] Time-limited test - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
11:48:52,861  INFO || - [system] Time-limited test - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Copyright (c) 2008-2022, Hazelcast, Inc. All Rights Reserved.
11:48:52,861  INFO || - [system] Time-limited test - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Hazelcast Platform 5.2-SNAPSHOT (20220816 - 5bcb6c0) starting at [127.0.0.1]:5702
11:48:52,861  INFO || - [system] Time-limited test - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Cluster name: dev
11:48:52,861  INFO || - [system] Time-limited test - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed. For more information, see the documentation for Integrity Checker.
11:48:52,861  INFO || - [system] Time-limited test - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Jet is enabled
11:48:52,877  INFO || - [MetricsConfigHelper] Time-limited test - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
11:48:52,904  WARN || - [CPSubsystem] Time-limited test - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
11:48:52,938  INFO || - [JetServiceBackend] Time-limited test - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Setting number of cooperative threads and default parallelism to 2
11:48:53,034  INFO || - [Diagnostics] Time-limited test - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
11:48:53,035  INFO || - [LifecycleService] Time-limited test - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] [127.0.0.1]:5702 is STARTING
11:48:53,078  INFO || - [MockServer] Time-limited test - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Created connection to endpoint: [127.0.0.1]:5701-50cf386c-8a72-4b50-8c7f-a7028e87ed09, connection: MockConnection{localEndpoint=[address=[127.0.0.1]:5702, uuid=7d4c3bd2-0da0-4137-92ab-f3f1d8a35d89], remoteEndpoint=[address=[127.0.0.1]:5701, uuid=50cf386c-8a72-4b50-8c7f-a7028e87ed09], alive=true}
11:48:53,101  INFO || - [MockServer] hz.condescending_dubinsky.priority-generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Created connection to endpoint: [127.0.0.1]:5702-7d4c3bd2-0da0-4137-92ab-f3f1d8a35d89, connection: MockConnection{localEndpoint=[address=[127.0.0.1]:5701, uuid=50cf386c-8a72-4b50-8c7f-a7028e87ed09], remoteEndpoint=[address=[127.0.0.1]:5702, uuid=7d4c3bd2-0da0-4137-92ab-f3f1d8a35d89], alive=true}
11:48:53,119  INFO || - [ClusterService] hz.condescending_dubinsky.priority-generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] 

Members {size:2, ver:2} [
	Member [127.0.0.1]:5701 - 50cf386c-8a72-4b50-8c7f-a7028e87ed09 this
	Member [127.0.0.1]:5702 - 7d4c3bd2-0da0-4137-92ab-f3f1d8a35d89
]

11:48:53,194  INFO || - [ClusterService] hz.priceless_dubinsky.priority-generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] 

Members {size:2, ver:2} [
	Member [127.0.0.1]:5701 - 50cf386c-8a72-4b50-8c7f-a7028e87ed09
	Member [127.0.0.1]:5702 - 7d4c3bd2-0da0-4137-92ab-f3f1d8a35d89 this
]

11:48:53,194  INFO || - [JobCoordinationService] Time-limited test - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Jet started scanning for jobs
11:48:53,195  INFO || - [LifecycleService] Time-limited test - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] [127.0.0.1]:5702 is STARTED
11:48:53,205  INFO || - [PartitionStateManager] hz.condescending_dubinsky.generic-operation.thread-1 - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Initializing cluster partition table arrangement...
Started Running Test: whenStoreAll_thenTableContainsRow
11:48:53,328  INFO || - [HealthMonitor] hz.priceless_dubinsky.HealthMonitor - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] processors=4, physical.memory.total=29.8G, physical.memory.free=9.4G, swap.space.total=0, swap.space.free=0, heap.memory.used=280.0M, heap.memory.free=3.0G, heap.memory.total=3.3G, heap.memory.max=3.3G, heap.memory.used/total=8.35%, heap.memory.used/max=8.35%, minor.gc.count=0, minor.gc.time=0ms, major.gc.count=0, major.gc.time=0ms, unknown.gc.count=2, unknown.gc.time=621ms, load.process=42.86%, load.system=96.55%, load.systemAverage=4.91, thread.count=68, thread.peakCount=68, cluster.timeDiff=-2, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=15, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=2, clientEndpoint.count=0, connection.active.count=0, client.connection.count=0, connection.count=0
11:48:53,490 DEBUG || - [GenericMapStore] hz.condescending_dubinsky.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Initializing for map people_o_1862a3bd_e575_41e5_acb5_91d93265ab4a
11:48:53,518 ERROR || - [EventServiceImpl] hz.condescending_dubinsky.event-1 - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] hz.condescending_dubinsky.event-1 caught an exception while processing:com.hazelcast.spi.impl.eventservice.impl.LocalEventDispatcher@382aed32
java.lang.UnsupportedOperationException: SQL catalog must never be cleared - MapEvent{entryEventType=CLEAR_ALL, member=Member [127.0.0.1]:5701 - 50cf386c-8a72-4b50-8c7f-a7028e87ed09 this, name='__sql.catalog', numberOfEntriesAffected=0}
	at com.hazelcast.jet.sql.impl.schema.TablesStorage$EntryListenerAdapter.mapCleared(TablesStorage.java:262) ~[hazelcast-sql-5.2-SNAPSHOT.jar:5.2-SNAPSHOT]
	at com.hazelcast.replicatedmap.impl.ReplicatedMapEventPublishingService.dispatchEvent(ReplicatedMapEventPublishingService.java:132) ~[hazelcast-5.2-SNAPSHOT.jar:5.2-SNAPSHOT]
	at com.hazelcast.replicatedmap.impl.ReplicatedMapService.dispatchEvent(ReplicatedMapService.java:232) ~[hazelcast-5.2-SNAPSHOT.jar:5.2-SNAPSHOT]
	at com.hazelcast.spi.impl.eventservice.impl.LocalEventDispatcher.run(LocalEventDispatcher.java:64) ~[hazelcast-5.2-SNAPSHOT.jar:5.2-SNAPSHOT]
	at com.hazelcast.internal.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:245) ~[hazelcast-5.2-SNAPSHOT.jar:5.2-SNAPSHOT]
	at com.hazelcast.internal.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:228) ~[hazelcast-5.2-SNAPSHOT.jar:5.2-SNAPSHOT]
11:48:58,802  INFO |whenStoreAll_thenTableContainsRow| - [SqlTestSupport] Time-limited test - Removing 0 cached plans in SqlTestSupport.@After
11:48:58,803  INFO |whenStoreAll_thenTableContainsRow| - [SqlTestSupport] Time-limited test - Removing 0 cached plans in SqlTestSupport.@After
11:48:58,847  INFO |whenStoreAll_thenTableContainsRow| - [SimpleTestInClusterSupport] Time-limited test - Ditching 0 jobs in SimpleTestInClusterSupport.@After: []
11:48:58,848  INFO |whenStoreAll_thenTableContainsRow| - [SimpleTestInClusterSupport] Time-limited test - Destroying 1 distributed objects in SimpleTestInClusterSupport.@After: [hz:impl:mapService/__sql.catalog]
BuildInfo right after whenStoreAll_thenTableContainsRow(com.hazelcast.mapstore.GenericMapStoreTest): BuildInfo{version='5.2-SNAPSHOT', build='20220816', buildNumber=20220816, revision=5bcb6c0, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'whenStoreAll_thenTableContainsRow(com.hazelcast.mapstore.GenericMapStoreTest):'
11:48:50, accumulated pauses: 1649 ms, max pause: 20 ms, pauses over 1000 ms: 0
11:48:55, accumulated pauses: 3847 ms, max pause: 24 ms, pauses over 1000 ms: 0
```

</details>

**Comment by olukas** [comment]
`com.hazelcast.mapstore.GenericMapStoreTest.whenDeleteAllWithNoIds_thenDoNothing` failed on ZingJDK8 and seems to have the same cause (so I reported here as well): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZingJDK8/463/testReport/com.hazelcast.mapstore/GenericMapStoreTest/whenDeleteAllWithNoIds_thenDoNothing/

It seems to be the same issue as https://github.com/hazelcast/hazelcast/issues/22079 which is closed (I don't reopen it since it seems to be the same issue so we can have just one GH issue for it, cc @ldziedziul )

**Comment by olukas** [comment]
`com.hazelcast.mapstore.GenericMapStoreTest.whenDeleteAllWithNoIds_thenDoNothing` failed on ZuluJDK11: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZuluJDK11/206/testReport/com.hazelcast.mapstore/GenericMapStoreTest/whenDeleteAllWithNoIds_thenDoNothing/

<details><summary>However stacktrace is different:</summary>

```
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at com.hazelcast.jet.impl.JobExecutionService.cancelAllExecutions(JobExecutionService.java:249)
	at com.hazelcast.jet.SimpleTestInClusterSupport.supportAfter(SimpleTestInClusterSupport.java:114)
	at jdk.internal.reflect.GeneratedMethodAccessor19.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:381)
	at com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37)
	at com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:104)
	at com.hazelcast.test.metrics.MetricsRule$1.evaluate(MetricsRule.java:63)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:50)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:29)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:39)
	at com.hazelcast.test.OverridePropertyRule$1.evaluate(OverridePropertyRule.java:66)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

</details>
