### ISSUE TITLE
com.hazelcast.internal.dynamicconfig.DynamicConfigYamlGeneratorTest.testIfSensitiveDataIsMasked_whenMaskingEnabled

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#22005]
_master_ (commit 7b0b3b67500f5d5500fc4ab3b63041c497901f97)

Failed on MacOS with ZuluJDK8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-MacOS-ZuluJDK8/103/testReport/com.hazelcast.internal.dynamicconfig/DynamicConfigYamlGeneratorTest/testIfSensitiveDataIsMasked_whenMaskingEnabled/

<details><summary>Stacktrace:</summary>

```
org.junit.ComparisonFailure: expected:<[Hazelcast]> but was:<[****]>
	at org.junit.Assert.assertEquals(Assert.java:117)
	at org.junit.Assert.assertEquals(Assert.java:146)
	at com.hazelcast.internal.dynamicconfig.DynamicConfigYamlGeneratorTest.testIfSensitiveDataIsMasked_whenMaskingEnabled(DynamicConfigYamlGeneratorTest.java:102)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

</details>

<details><summary>Standard output:</summary>

```
BuildInfo right after testIfSensitiveDataIsMasked_whenMaskingEnabled(com.hazelcast.internal.dynamicconfig.DynamicConfigYamlGeneratorTest): BuildInfo{version='5.2-SNAPSHOT', build='20220817', buildNumber=20220817, revision=7b0b3b6, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'testIfSensitiveDataIsMasked_whenMaskingEnabled(com.hazelcast.internal.dynamicconfig.DynamicConfigYamlGeneratorTest):'
07:36:30, accumulated pauses: 257 ms, max pause: 112 ms, pauses over 1000 ms: 0


No metrics recorded during the test
07:36:30,737  INFO |testAdvancedNetworkTcpIpMemberList| - [InMemoryYamlConfig] testAdvancedNetworkTcpIpMemberList - Configuring Hazelcast from 'in-memory YAML'.
07:36:30,738  INFO |testFlakeIdGeneratorConfigGenerator| - [InMemoryYamlConfig] testFlakeIdGeneratorConfigGenerator - Configuring Hazelcast from 'in-memory YAML'.
07:36:30,738  INFO |testEndpointConfig_completeConfiguration| - [InMemoryYamlConfig] testEndpointConfig_completeConfiguration - Configuring Hazelcast from 'in-memory YAML'.
07:36:30,738  INFO |testRingbufferWithStoreImplementation| - [InMemoryYamlConfig] testRingbufferWithStoreImplementation - Configuring Hazelcast from 'in-memory YAML'.
07:36:30,738  INFO |testReliableTopic| - [InMemoryYamlConfig] testReliableTopic - Configuring Hazelcast from 'in-memory YAML'.
07:36:30,739  INFO |testQueueWithStoreClass| - [InMemoryYamlConfig] testQueueWithStoreClass - Configuring Hazelcast from 'in-memory YAML'.
07:36:30,739  INFO |testCacheFactoryAttributes| - [InMemoryYamlConfig] testCacheFactoryAttributes - Configuring Hazelcast from 'in-memory YAML'.
07:36:30,739  INFO |testMapWithEnabledMerkleTreeConfig| - [InMemoryYamlConfig] testMapWithEnabledMerkleTreeConfig - Configuring Hazelcast from 'in-memory YAML'.
```

</details>

**Comment by ramizdundar** [comment]
I don't think this test will fail again. A static field is modified in this test code. Previous to https://github.com/hazelcast/hazelcast/pull/21985 it was non-volatile and this was the reason. And this failure is from commit `7b0b3b6` which is before that PR. I suggest closing this and re open if needed. WDYT?

**Comment by olukas** [comment]
@ramizdundar thanks. In that case let's close it. If it will happen again we can reopen it. Closing.
