### ISSUE TITLE
Client YAML import fails if metric enabled - "only 1 subschema matches out of 2"

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast#22025]
**Describe the bug**
If client configuration uses YAML, and one YAML file imports another, configuration fails if `metrics.enabled: true` 

**Expected behavior**
Metrics should be configurable when using imports

**To Reproduce**

`hazelcast-client.yaml`
```
hazelcast-client:
  import:
    - client-labels.yml
  metrics:
    enabled:true
```

`client-labels.yml`
```
hazelcast-client:
  client-labels:
    - normal
#  metrics:
#    enabled:true    
```

and
```
	public static void main(String[] args) throws Exception {
		ClientConfig clientConfig = new YamlClientConfigBuilder("hazelcast-client.yaml").build();
		System.out.println(clientConfig.getMetricsConfig().isEnabled());
	}
```

gives

```
Exception in thread "main" #: only 1 subschema matches out of 2
  instance location: #/hazelcast-client/metrics
  keyword location: #/definitions/ClientMetrics
  expected type: JSONObject, found: String
    instance location: #/hazelcast-client/metrics
    keyword location: #/definitions/BaseMetrics

	at com.hazelcast.internal.config.YamlConfigSchemaValidator.wrap(YamlConfigSchemaValidator.java:76)
	at com.hazelcast.internal.config.YamlConfigSchemaValidator.validate(YamlConfigSchemaValidator.java:120)
	at com.hazelcast.client.config.YamlClientConfigBuilder.parseAndBuildConfig(YamlClientConfigBuilder.java:160)
	at com.hazelcast.client.config.YamlClientConfigBuilder.build(YamlClientConfigBuilder.java:133)
	at com.hazelcast.client.config.YamlClientConfigBuilder.build(YamlClientConfigBuilder.java:121)
	at com.hazelcast.client.config.YamlClientConfigBuilder.build(YamlClientConfigBuilder.java:116)
	at neil.Application.main(Application.java:9)
```
**Additional context**
Tested with 5.1.3 and 5.2-SNAPSHOT (20220819 - 111323f)

**Comment by JackPGreen** [comment]
@neilstevenson 

the problem is reproducible without any imports:

```
hazelcast-client:
  metrics:
    enabled:true
```

The YML syntax in `hazelcast-client.yaml` is wrong, a space is required after the colon, between `enabled:true`

I.E.:
```
hazelcast-client:
  metrics:
    enabled: true
```

The parser is interpreting the input as:
```
hazelcast-client:
  metrics: enabled:true
```

And then the error kind of makes sense:
```
instance location: #/hazelcast-client/metrics
{...}
expected type: JSONObject, found: String
```
