### ISSUE TITLE
com.hazelcast.mapstore.GenericMapStoreTest.whenDeleteAll_thenRowsRemovedFromTable [HZ-1430]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#22079]
_master_ (commit 311a51b8d3a269a53edc94b09f02faaf7fc65da6)

Failed on ZingJDK8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZingJDK8/457/testReport/com.hazelcast.mapstore/GenericMapStoreTest/whenDeleteAll_thenRowsRemovedFromTable/

<details><summary>Stacktrace:</summary>

```
com.hazelcast.core.HazelcastException: MapStore init failed for map: people_o_e5a43020_ca9f_4790_992a_f01118b63b12
	at com.hazelcast.mapstore.GenericMapStore.awaitInitFinished(GenericMapStore.java:543)
	at com.hazelcast.mapstore.GenericMapStore.deleteAll(GenericMapStore.java:523)
	at com.hazelcast.mapstore.GenericMapStoreTest.whenDeleteAll_thenRowsRemovedFromTable(GenericMapStoreTest.java:526)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

</details>

<details><summary>Standard output:</summary>

```
11:48:51,697  WARN || - [HazelcastInstanceFactory] Time-limited test - WARNING: Classpath misconfiguration: found multiple META-INF/services/com.hazelcast.instance.impl.NodeExtension resources: jar:file:/home/ec2-user/~/jenkins/workspace/Hazelcast-master-ZingJDK8/hazelcast/target/hazelcast-5.2-SNAPSHOT.jar!/META-INF/services/com.hazelcast.instance.impl.NodeExtension, jar:file:/home/ec2-user/~/jenkins/workspace/Hazelcast-master-ZingJDK8/hazelcast/target/hazelcast-5.2-SNAPSHOT-tests.jar!/META-INF/services/com.hazelcast.instance.impl.NodeExtension
11:48:51,895  INFO || - [MetricsConfigHelper] Time-limited test - [LOCAL] [dev] [5.2-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
11:48:52,028  INFO || - [logo] Time-limited test - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
11:48:52,028  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Copyright (c) 2008-2022, Hazelcast, Inc. All Rights Reserved.
11:48:52,028  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Hazelcast Platform 5.2-SNAPSHOT (20220828 - 311a51b) starting at [127.0.0.1]:5701
11:48:52,029  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Cluster name: dev
11:48:52,029  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed. For more information, see the documentation for Integrity Checker.
11:48:52,029  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Jet is enabled
11:48:52,104  INFO || - [MetricsConfigHelper] Time-limited test - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
11:48:53,997  WARN || - [CPSubsystem] Time-limited test - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
11:48:54,973  INFO || - [JetServiceBackend] Time-limited test - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Setting number of cooperative threads and default parallelism to 2
11:48:55,238  INFO || - [Diagnostics] Time-limited test - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
11:48:55,254  INFO || - [LifecycleService] Time-limited test - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] [127.0.0.1]:5701 is STARTING
11:48:55,292  INFO || - [ClusterService] Time-limited test - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] 

Members {size:1, ver:1} [
	Member [127.0.0.1]:5701 - 295a425a-53a4-4e93-a15b-5342695b9c49 this
]

11:48:55,337  INFO || - [JobCoordinationService] Time-limited test - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Jet started scanning for jobs
11:48:55,343  INFO || - [LifecycleService] Time-limited test - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] [127.0.0.1]:5701 is STARTED
11:48:55,492  INFO || - [MetricsConfigHelper] Time-limited test - [LOCAL] [dev] [5.2-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
11:48:55,494  INFO || - [logo] Time-limited test - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
11:48:55,494  INFO || - [system] Time-limited test - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Copyright (c) 2008-2022, Hazelcast, Inc. All Rights Reserved.
11:48:55,494  INFO || - [system] Time-limited test - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Hazelcast Platform 5.2-SNAPSHOT (20220828 - 311a51b) starting at [127.0.0.1]:5702
11:48:55,494  INFO || - [system] Time-limited test - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Cluster name: dev
11:48:55,494  INFO || - [system] Time-limited test - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed. For more information, see the documentation for Integrity Checker.
11:48:55,494  INFO || - [system] Time-limited test - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Jet is enabled
11:48:55,511  INFO || - [MetricsConfigHelper] Time-limited test - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
11:48:55,531  WARN || - [CPSubsystem] Time-limited test - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
11:48:55,575  INFO || - [JetServiceBackend] Time-limited test - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Setting number of cooperative threads and default parallelism to 2
11:48:55,582  INFO || - [Diagnostics] Time-limited test - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
11:48:55,583  INFO || - [LifecycleService] Time-limited test - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] [127.0.0.1]:5702 is STARTING
11:48:55,598  INFO || - [MockServer] Time-limited test - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Created connection to endpoint: [127.0.0.1]:5701-295a425a-53a4-4e93-a15b-5342695b9c49, connection: MockConnection{localEndpoint=[address=[127.0.0.1]:5702, uuid=6b830b33-0ddd-4165-8b25-7b0ae6c0dd58], remoteEndpoint=[address=[127.0.0.1]:5701, uuid=295a425a-53a4-4e93-a15b-5342695b9c49], alive=true}
11:48:55,609  INFO || - [MockServer] hz.modest_dhawan.priority-generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Created connection to endpoint: [127.0.0.1]:5702-6b830b33-0ddd-4165-8b25-7b0ae6c0dd58, connection: MockConnection{localEndpoint=[address=[127.0.0.1]:5701, uuid=295a425a-53a4-4e93-a15b-5342695b9c49], remoteEndpoint=[address=[127.0.0.1]:5702, uuid=6b830b33-0ddd-4165-8b25-7b0ae6c0dd58], alive=true}
11:48:55,620  INFO || - [ClusterService] hz.modest_dhawan.priority-generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] 

Members {size:2, ver:2} [
	Member [127.0.0.1]:5701 - 295a425a-53a4-4e93-a15b-5342695b9c49 this
	Member [127.0.0.1]:5702 - 6b830b33-0ddd-4165-8b25-7b0ae6c0dd58
]

11:48:55,718  INFO || - [ClusterService] hz.condescending_dhawan.priority-generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] 

Members {size:2, ver:2} [
	Member [127.0.0.1]:5701 - 295a425a-53a4-4e93-a15b-5342695b9c49
	Member [127.0.0.1]:5702 - 6b830b33-0ddd-4165-8b25-7b0ae6c0dd58 this
]

11:48:55,722  INFO || - [JobCoordinationService] Time-limited test - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Jet started scanning for jobs
11:48:55,722  INFO || - [LifecycleService] Time-limited test - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] [127.0.0.1]:5702 is STARTED
11:48:55,760  INFO || - [HealthMonitor] hz.condescending_dhawan.HealthMonitor - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] processors=4, physical.memory.total=29.8G, physical.memory.free=9.4G, swap.space.total=0, swap.space.free=0, heap.memory.used=262.0M, heap.memory.free=3.0G, heap.memory.total=3.3G, heap.memory.max=3.3G, heap.memory.used/total=7.81%, heap.memory.used/max=7.81%, minor.gc.count=0, minor.gc.time=0ms, major.gc.count=0, major.gc.time=0ms, unknown.gc.count=2, unknown.gc.time=649ms, load.process=50.00%, load.system=100.00%, load.systemAverage=5.11, thread.count=63, thread.peakCount=63, cluster.timeDiff=-11, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=21, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=1, clientEndpoint.count=0, connection.active.count=0, client.connection.count=0, connection.count=0
Started Running Test: whenDeleteAll_thenRowsRemovedFromTable
11:48:55,959 DEBUG || - [GenericMapStore] hz.modest_dhawan.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Initializing for map people_o_e5a43020_ca9f_4790_992a_f01118b63b12
11:48:56,016  INFO || - [PartitionStateManager] hz.modest_dhawan.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Initializing cluster partition table arrangement...
11:49:01,022  INFO |whenDeleteAll_thenRowsRemovedFromTable| - [SqlTestSupport] Time-limited test - Removing 1 cached plans in SqlTestSupport.@After
11:49:01,022  INFO |whenDeleteAll_thenRowsRemovedFromTable| - [SqlTestSupport] Time-limited test - Removing 0 cached plans in SqlTestSupport.@After
11:49:01,082  INFO |whenDeleteAll_thenRowsRemovedFromTable| - [SimpleTestInClusterSupport] Time-limited test - Ditching 0 jobs in SimpleTestInClusterSupport.@After: []
11:49:01,126  INFO |whenDeleteAll_thenRowsRemovedFromTable| - [SimpleTestInClusterSupport] Time-limited test - Destroying 2 distributed objects in SimpleTestInClusterSupport.@After: [hz:impl:mapService/__sql.catalog, hz:impl:flakeIdGeneratorService/__jet.ids]
BuildInfo right after whenDeleteAll_thenRowsRemovedFromTable(com.hazelcast.mapstore.GenericMapStoreTest): BuildInfo{version='5.2-SNAPSHOT', build='20220828', buildNumber=20220828, revision=311a51b, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'whenDeleteAll_thenRowsRemovedFromTable(com.hazelcast.mapstore.GenericMapStoreTest):'
11:48:55, accumulated pauses: 4141 ms, max pause: 23 ms, pauses over 1000 ms: 0
11:49:00, accumulated pauses: 1136 ms, max pause: 21 ms, pauses over 1000 ms: 0
```

</details>

**Comment by olukas** [comment]
`com.hazelcast.mapstore.GenericMapStoreTest.whenDeleteAllWithNoIds_thenDoNothing` failed on ZingJDK8 and seems to have the same cause (so I reported here as well): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZingJDK8/458/testReport/com.hazelcast.mapstore/GenericMapStoreTest/whenDeleteAllWithNoIds_thenDoNothing/

Also issue https://github.com/hazelcast/hazelcast/issues/21992 seems to be related (I'm closing it as duplicate of this issue)
