### ISSUE TITLE
com.hazelcast.client.map.ClientPartitionIndexingTest.testOnProgrammaticallyAddedIndexes [API-1668] [HZ-1794]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#22090]
_5.1.z_ (commit 33febf2601a78d3c1efbeb2a7d49675405d832b8)

Failed on Sonar build (Oracle JDK 11): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-sonar/315/testReport/com.hazelcast.client.map/ClientPartitionIndexingTest/testOnProgrammaticallyAddedIndexes_format_OBJECT_/

Failed in variant `[format:OBJECT]`.

<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: map_hash_this is missing 1 partitions expected:<101> but was:<100>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at com.hazelcast.query.impl.PartitionIndexingTest.assertPartitionsIndexedCorrectly(PartitionIndexingTest.java:220)
	at com.hazelcast.query.impl.PartitionIndexingTest.testOnProgrammaticallyAddedIndexes(PartitionIndexingTest.java:173)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

</details>

Standard output can be found here - https://console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-5.maintenance-sonar/315/

**Comment by vbekiaris** [comment]
This seems like it's not a client-related test failure: after migrations were done, a partition remained unindexed.

**Comment by vbekiaris** [comment]
Closed with additional logging in https://github.com/hazelcast/hazelcast/pull/23113

**Comment by sumnerib** [comment]
Failed again on _master_ with ZuluJDK8: https://jenkins.hazelcast.com/job/Hazelcast-master-ZuluJDK8/217/testReport/junit/com.hazelcast.query.impl/PartitionIndexingTest/testOnProgrammaticallyAddedIndexes_format_OBJECT_/

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-ZuluJDK8/217/

**Comment by srknzl** [comment]
I don't know assertTrueEventually makes sense for this test but opened a fix PR here https://github.com/hazelcast/hazelcast/pull/23179.
