### ISSUE TITLE
Serialization exception for Aggregator, java.security.PrivilegedActionException

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast#22094]
**Describe the bug**
Submitting a job *from a client* that uses a custom aggregator fails with a serialization exception.

**Expected behavior**
Job submitted

**To Reproduce**
Run these two classes

```
public class Application implements Serializable {
    private static final long serialVersionUID = 1L;

	public static void main(String[] args) throws Exception {
		HazelcastInstance hazelcastInstance = HazelcastClient.newHazelcastClient();
		
		AggregateOperation1<Object, Fails, String> failingAggregator =
				AggregateOperation
				.withCreate(Fails::new)
				.andAccumulate0((fails, item) -> fails.accumulate0(item))
				.andExportFinish(Fails::exportFinish);
		
		Pipeline workingPipeline = Pipeline.create()
				.readFrom(TestSources.itemStream(1))
				.withNativeTimestamps(0)
				.writeTo(Sinks.logger())
				.getPipeline();

		Pipeline failingPipeline = Pipeline.create()
				.readFrom(TestSources.itemStream(1))
				.withNativeTimestamps(0)
				.window(WindowDefinition.tumbling(5))
				.aggregate(failingAggregator)
				.writeTo(Sinks.logger())
				.getPipeline();
		
		JobConfig workingConfig = new JobConfig();
		workingConfig.addClass(Application.class);
		
		JobConfig failingConfig = new JobConfig();
		failingConfig.addClass(Application.class);
		failingConfig.addClass(Fails.class);

		hazelcastInstance.getJet().newJob(workingPipeline, workingConfig);
		TimeUnit.SECONDS.sleep(5L);
		hazelcastInstance.getJet().newJob(failingPipeline, failingConfig);
		
		hazelcastInstance.shutdown();
		System.exit(0);
	}

}
```

Aggregator
```
public class Fails implements Serializable {
    private static final long serialVersionUID = 1L;

    Fails accumulate0(Object arg0) {
    	return this;
    }

    String exportFinish() {
    	return "hello from " + this;
    }
}
```

**Additional context**
Tested with 5.2-BETA-1

Stacktrace
```
INFO: Client statistics is enabled with period 5 seconds.
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
Caused by: com.hazelcast.nio.serialization.HazelcastSerializationException: java.lang.RuntimeException: Exception in SerializedLambda.readResolve
	at com.hazelcast.internal.serialization.impl.SerializationUtil.handleException(SerializationUtil.java:111)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:277)
	at com.hazelcast.jet.impl.execution.init.CustomClassLoadedObject.deserializeWithCustomClassLoader(CustomClassLoadedObject.java:66)
	at com.hazelcast.jet.impl.JobCoordinationService.deserializeJobDefinition(JobCoordinationService.java:1107)
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitJob$2(JobCoordinationService.java:250)
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$54(JobCoordinationService.java:1297)
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$55(JobCoordinationService.java:1318)
	at com.hazelcast.internal.util.executor.CompletableFutureTask.run(CompletableFutureTask.java:64)
	at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:833)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
Caused by: java.lang.RuntimeException: Exception in SerializedLambda.readResolve
	at java.lang.invoke.SerializedLambda.readResolve(SerializedLambda.java:288)
	at jdk.internal.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at java.io.ObjectStreamClass.invokeReadResolve(ObjectStreamClass.java:1321)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2251)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1742)
	at java.io.ObjectInputStream.readArray(ObjectInputStream.java:2142)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1730)
	at java.io.ObjectInputStream$FieldValues.<init>(ObjectInputStream.java:2584)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2442)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2242)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1742)
	at java.io.ObjectInputStream.readArray(ObjectInputStream.java:2142)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1730)
	at java.io.ObjectInputStream$FieldValues.<init>(ObjectInputStream.java:2584)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2442)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2242)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1742)
	at java.io.ObjectInputStream$FieldValues.<init>(ObjectInputStream.java:2584)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2442)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2242)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1742)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:514)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:472)
	at java.util.ArrayList.readObject(ArrayList.java:899)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1231)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2408)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2242)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1742)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:514)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:472)
	at java.util.HashMap.readObject(HashMap.java:1546)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1231)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2408)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2242)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1742)
	at java.io.ObjectInputStream$FieldValues.<init>(ObjectInputStream.java:2584)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2442)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2242)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1742)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:514)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:472)
	at com.hazelcast.internal.serialization.impl.defaultserializers.JavaDefaultSerializers$JavaSerializer.read(JavaDefaultSerializers.java:92)
	at com.hazelcast.internal.serialization.impl.defaultserializers.JavaDefaultSerializers$JavaSerializer.read(JavaDefaultSerializers.java:85)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:44)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:271)
	... 12 more
Caused by: com.hazelcast.client.UndefinedErrorCodeException: Class name: java.security.PrivilegedActionException, Message: null
	at java.security.AccessController.doPrivileged(AccessController.java:573)
	at java.lang.invoke.SerializedLambda.readResolve(SerializedLambda.java:269)
	... 66 more
```

I have the full example I can send on, just as for `zzz65`

**Comment by neilstevenson** [comment]
My JAVA_OPTS

```
JAVA_OPTS="--add-modules java.se --add-exports java.base/jdk.internal.ref=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.management/sun.management=ALL-UNNAMED --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED"
```

I'm using
```
openjdk 17 2021-09-14
OpenJDK Runtime Environment Temurin-17+35 (build 17+35)
OpenJDK 64-Bit Server VM Temurin-17+35 (build 17+35, mixed mode, sharing)
```

**Comment by neilstevenson** [comment]
If I change to this, it works

*Application.java*
```
public class Application implements Serializable {
    private static final long serialVersionUID = 1L;

	public static void main(String[] args) throws Exception {
		HazelcastInstance hazelcastInstance = HazelcastClient.newHazelcastClient();
		
		/*
		AggregateOperation1<Object, Fails, String> failingAggregator =
				AggregateOperation
				.withCreate(Fails::new)
				.andAccumulate0((fails, item) -> fails.accumulate0(item))
				.andExportFinish(Fails::exportFinish);
				*/
		
		Pipeline workingPipeline = Pipeline.create()
				.readFrom(TestSources.itemStream(1))
				.withNativeTimestamps(0)
				.writeTo(Sinks.logger())
				.getPipeline();

		/*
		Pipeline failingPipeline = Pipeline.create()
				.readFrom(TestSources.itemStream(1))
				.withNativeTimestamps(0)
				.window(WindowDefinition.tumbling(5))
				.aggregate(failingAggregator)
				.writeTo(Sinks.logger())
				.getPipeline();
				*/
		Pipeline failingPipeline = Build.build();
		
		JobConfig workingConfig = new JobConfig();
		workingConfig.addClass(Application.class);
		
		JobConfig failingConfig = new JobConfig();
		failingConfig.addClass(Application.class);
		failingConfig.addClass(Fails.class);
		failingConfig.addClass(Build.class);

		hazelcastInstance.getJet().newJob(workingPipeline, workingConfig);
		TimeUnit.SECONDS.sleep(5L);
		hazelcastInstance.getJet().newJob(failingPipeline, failingConfig);
		
		hazelcastInstance.shutdown();
		System.exit(0);
	}

}
```

and
*Build.java*
```
public class Build {

	public static Pipeline build() {
		AggregateOperation1<Object, Fails, String> failingAggregator =
				AggregateOperation
				.withCreate(Fails::new)
				.andAccumulate0((fails, item) -> fails.accumulate0(item))
				.andExportFinish(Fails::exportFinish);
		
		return Pipeline.create()
				.readFrom(TestSources.itemStream(1))
				.withNativeTimestamps(0)
				.window(WindowDefinition.tumbling(5))
				.aggregate(failingAggregator)
				.writeTo(Sinks.logger())
				.getPipeline();
	}
}
```

So is this a bug, user error, or ... ?

**Comment by frant-hartm** [comment]
@neilstevenson 
How are you running the server?
Are you using beta for both server and client?
Are you using the JDK17 for both client and server? 
Can you try with never JDK 17, the one listed is rather old. Also does this happen on e.g. JDK11?

**Comment by frant-hartm** [comment]
Discussed with @neilstevenson on Slack. His demo had 2 different classes called Application in the same package. One started a member, the other submitted a job using a client (see above), the class contains lamba, during its deserialization it uses the Application from the member CP to deserialize and fails.

I don't think we should support this case.
