### ISSUE TITLE
com.hazelcast.sql.impl.client.SqlResubmissionTimeoutTest.when_totalTimeOfResubmissionEnds_then_fail

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#22123]
_master_ (commit 57a4812b084123aea80216889392f8cb365a4b12)

Failed on IbmJDK8 in FIPS mode: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-IbmJDK8-fips-nightly/457/testReport/com.hazelcast.sql.impl.client/SqlResubmissionTimeoutTest/when_totalTimeOfResubmissionEnds_then_fail/

<details><summary>Stacktrace:</summary>

```
junit.framework.AssertionFailedError: Expected com.hazelcast.sql.HazelcastSqlException to be thrown, but nothing was thrown.
	at com.hazelcast.test.HazelcastTestSupport.assertThrows(HazelcastTestSupport.java:1440)
	at com.hazelcast.sql.impl.client.SqlResubmissionTimeoutTest.when_totalTimeOfResubmissionEnds_then_fail(SqlResubmissionTimeoutTest.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.lang.Thread.run(Thread.java:822)
```

</details>

Standard output can be found here - https://console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-IbmJDK8-fips-nightly/457/

**Comment by olukas** [comment]
Failed on Sonar build (Oracle JDK 11): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/1353/testReport/com.hazelcast.sql.impl.client/SqlResubmissionTimeoutTest/when_totalTimeOfResubmissionEnds_then_fail/

**Comment by olukas** [comment]
Failed on IbmJDK8 in FIPS mode: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-IbmJDK8-fips-nightly/467/testReport/com.hazelcast.sql.impl.client/SqlResubmissionTimeoutTest/when_totalTimeOfResubmissionEnds_then_fail/

**Comment by olukas** [comment]
Failed on IbmJDK8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-IbmJDK8-nightly/73/testReport/com.hazelcast.sql.impl.client/SqlResubmissionTimeoutTest/when_totalTimeOfResubmissionEnds_then_fail/

**Comment by Patras3** [comment]
Failed again on _5.2.z_ with IbmJDK8-nightly: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-IbmJDK8-nightly/54/testReport/junit/com.hazelcast.sql.impl.client/SqlResubmissionTimeoutTest/when_totalTimeOfResubmissionEnds_then_fail/
