### ISSUE TITLE
cp system RU test,  com.hazelcast.cp.exception.NotLeaderException: null is not LEADER of null. Known leader is: N/A

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#22136]
5.1. ---> 5.2-SANPSHOT
http://jenkins.hazelcast.com/view/cp-system/job/cp-all-rollup/2/console

/disk1/workspace/cp-all-rollup/5.2-SNAPSHOT/2022_09_02-11_21_57/cp/latch/set-and-countDown

and multi other RU test all fail with 

com.hazelcast.cp.exception.NotLeaderException: null is not LEADER of null. Known leader is: N/A

```
com.hazelcast.cp.exception.NotLeaderException: null is not LEADER of null. Known leader is: N/A
	at com.hazelcast.cp.exception.NotLeaderException.wrap(NotLeaderException.java:42)
	at com.hazelcast.cp.exception.NotLeaderException.wrap(NotLeaderException.java:28)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.wrapRuntimeException(AbstractInvocationFuture.java:1967)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.wrapOrPeel(AbstractInvocationFuture.java:1950)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$ExceptionalResult.wrapForJoinInternal(AbstractInvocationFuture.java:1432)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.resolveAndThrowForJoinInternal(AbstractInvocationFuture.java:600)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.joinInternal(AbstractInvocationFuture.java:584)
	at com.hazelcast.client.cp.internal.datastructures.countdownlatch.CountDownLatchProxy.getRound(CountDownLatchProxy.java:85)
	at com.hazelcast.client.cp.internal.datastructures.countdownlatch.CountDownLatchProxy.countDown(CountDownLatchProxy.java:70)

```

also same issue's for 5.0 ---> 5.1
http://jenkins.hazelcast.com/view/cp-system/job/cp-x1-rollup/1/console

**Comment by Danny-Hazelcast** [comment]
settings never removes member from cp system,   
     <missing-cp-member-auto-removal-seconds>0</missing-cp-member-auto-removal-seconds>
