### ISSUE TITLE
com.hazelcast.jet.sql.impl.type.BasicNestedFieldsTest.test_mixedModeUpsert

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#22184]
_master_ (commit 4252b4f340beedefaea4aec193d60e93a2ea9c28)

Failed on Windows with MicrosoftJDK11: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Windows-MicrosoftJDK11/28/testReport/com.hazelcast.jet.sql.impl.type/BasicNestedFieldsTest/test_mixedModeUpsert_useClient_true_/

Failed in variant `[useClient:true]`.

<details><summary>Stacktrace:</summary>

```
com.hazelcast.sql.HazelcastSqlException: Duplicate key
	at com.hazelcast.sql.impl.client.SqlClientService.handleExecuteResponse(SqlClientService.java:280)
	at com.hazelcast.sql.impl.client.SqlClientService.execute(SqlClientService.java:128)
	at com.hazelcast.sql.SqlService.execute(SqlService.java:89)
	at com.hazelcast.jet.sql.impl.type.BasicNestedFieldsTest.execute(BasicNestedFieldsTest.java:580)
	at com.hazelcast.jet.sql.impl.type.BasicNestedFieldsTest.execute(BasicNestedFieldsTest.java:576)
	at com.hazelcast.jet.sql.impl.type.BasicNestedFieldsTest.test_mixedModeUpsert(BasicNestedFieldsTest.java:321)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

</details>

<details><summary>Standard output:</summary>

```
18:25:45,267 DEBUG || - [CalciteSqlOptimizer] hz.hardcore_ganguly.client-query.thread-3 - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Before logical opt:
LogicalTableInsert(table=[[hazelcast, public, test[projects=[$0, $1, $2, $3]]]], operation=[INSERT], flattened=[false])
  LogicalCalc(expr#0=[{inputs}], expr#1=[1:BIGINT(63)], expr#2=[_UTF-16LE'parent':VARCHAR CHARACTER SET "UTF-16LE"], expr#3=[_UTF-16LE'child':VARCHAR CHARACTER SET "UTF-16LE"], expr#4=[ROW($t1, $t3)], expr#5=[null:OBJECT], __key=[$t1], name=[$t2], child=[$t4], this=[$t5])
    LogicalValues(tuples=[[{ 0 }]])

18:25:45,268 DEBUG || - [CalciteSqlOptimizer] hz.hardcore_ganguly.client-query.thread-3 - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] After logical opt:
InsertMapLogicalRel(table=[[hazelcast, public, test[projects=[$0, $1, $2, $3]]]], values=[{projection=[ConstantExpression{type=QueryDataType {family=BIGINT}, value=1}, ConstantExpression{type=QueryDataType {family=VARCHAR}, value=parent}, RowExpression{operand=[ConstantExpression{type=QueryDataType {family=BIGINT}, value=1}, ConstantExpression{type=QueryDataType {family=VARCHAR}, value=child}], resultType=QueryDataType {family=ROW}}, ConstantExpression{type=QueryDataType {family=OBJECT}, value=null}], values=[{expressions=[[ConstantExpression{type=QueryDataType {family=INTEGER}, value=0}]]}]}])

18:25:45,268 DEBUG || - [CalciteSqlOptimizer] hz.hardcore_ganguly.client-query.thread-3 - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] After physical opt:
InsertMapPhysicalRel(table=[[hazelcast, public, test[projects=[$0, $1, $2, $3]]]], values=[{projection=[ConstantExpression{type=QueryDataType {family=BIGINT}, value=1}, ConstantExpression{type=QueryDataType {family=VARCHAR}, value=parent}, RowExpression{operand=[ConstantExpression{type=QueryDataType {family=BIGINT}, value=1}, ConstantExpression{type=QueryDataType {family=VARCHAR}, value=child}], resultType=QueryDataType {family=ROW}}, ConstantExpression{type=QueryDataType {family=OBJECT}, value=null}], values=[{expressions=[[ConstantExpression{type=QueryDataType {family=INTEGER}, value=0}]]}]}])

18:25:45,269 DEBUG || - [SqlExecuteMessageTask] hz.hardcore_ganguly.client-query.thread-3 - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Client SQL error: com.hazelcast.sql.HazelcastSqlException: Duplicate key
18:25:45,697  INFO |test_mixedModeUpsert[useClient:true]| - [SqlTestSupport] Time-limited test - Removing 0 cached plans in SqlTestSupport.@After
18:25:45,697  INFO |test_mixedModeUpsert[useClient:true]| - [SqlTestSupport] Time-limited test - Removing 1 cached plans in SqlTestSupport.@After
18:25:45,697  INFO |test_mixedModeUpsert[useClient:true]| - [SqlTestSupport] Time-limited test - Removing 0 cached plans in SqlTestSupport.@After
18:25:45,699  INFO |test_mixedModeUpsert[useClient:true]| - [SimpleTestInClusterSupport] Time-limited test - Ditching 0 jobs in SimpleTestInClusterSupport.@After: []
18:25:45,699  INFO |test_mixedModeUpsert[useClient:true]| - [SimpleTestInClusterSupport] Time-limited test - Destroying 2 distributed objects in SimpleTestInClusterSupport.@After: [hz:impl:mapService/test, hz:impl:mapService/__sql.catalog]
BuildInfo right after test_mixedModeUpsert[useClient:true](com.hazelcast.jet.sql.impl.type.BasicNestedFieldsTest): BuildInfo{version='5.2-SNAPSHOT', build='20220908', buildNumber=20220908, revision=4252b4f, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'test_mixedModeUpsert[useClient:true](com.hazelcast.jet.sql.impl.type.BasicNestedFieldsTest):'
18:25:45, accumulated pauses: 458 ms, max pause: 418 ms, pauses over 1000 ms: 0
```

</details>

**Comment by kwart** [comment]
Failed in PR builder on `master`: https://jenkins.hazelcast.com/job/Hazelcast-pr-builder/13119/

**Comment by olukas** [comment]
`com.hazelcast.jet.sql.impl.type.BasicNestedFieldsTest.test_typeCoercionUpserts[useClient:true]` failed with the same issue on RedHatJDK11: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-RedHatJDK11/49/testReport/com.hazelcast.jet.sql.impl.type/BasicNestedFieldsTest/test_typeCoercionUpserts_useClient_true_/

**Comment by olukas** [comment]
`com.hazelcast.jet.sql.impl.type.BasicNestedFieldsTest.test_mixedModeUpsert[useClient:true]` failed on ZuluJDK8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZuluJDK8/205/testReport/com.hazelcast.jet.sql.impl.type/BasicNestedFieldsTest/test_mixedModeUpsert_useClient_true_/

**Comment by frant-hartm** [comment]
Failed in PR builder https://github.com/hazelcast/hazelcast/pull/22242
