### ISSUE TITLE
com.hazelcast.scheduledexecutor.impl.ScheduledExecutorServiceBasicTest.schedule_withMapChanges_durable

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#22196]
_5.1.z_ (commit 21a222c14f80e87803937dddd499d72e03bd7541)

Failed on Openj9-11: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-Openj9-11/51/testReport/com.hazelcast.scheduledexecutor.impl/ScheduledExecutorServiceBasicTest/schedule_withMapChanges_durable/

<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: CountDownLatch failed to complete within 120 seconds, count left: 1
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:1107)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:1096)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:1084)
	at com.hazelcast.scheduledexecutor.impl.ScheduledExecutorServiceBasicTest.schedule_withMapChanges_durable(ScheduledExecutorServiceBasicTest.java:874)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:866)
```

</details>

<details><summary>Standard output:</summary>

```
03:24:40,219  WARN |scheduledAtFixedRate_does_not_generate_statistics_when_stats_disabled| - [ScheduledExecutorContainer] hz.tender_johnson.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.1.4-SNAPSHOT] [Scheduler: s][Partition: 7][Task: 4236700c-c4d6-47c0-9ebd-2dc3741ac402] Unexpected exception during afterRun occurred
com.hazelcast.core.HazelcastInstanceNotActiveException: Hazelcast instance is not active!
	at com.hazelcast.spi.impl.operationservice.impl.InvocationRegistry.register(InvocationRegistry.java:140) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:570) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:541) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:241) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:61) ~[classes/:?]
	at com.hazelcast.scheduledexecutor.impl.ScheduledExecutorContainer.publishTaskState(ScheduledExecutorContainer.java:434) ~[classes/:?]
	at com.hazelcast.scheduledexecutor.impl.TaskRunner.afterRun(TaskRunner.java:142) ~[classes/:?]
	at com.hazelcast.scheduledexecutor.impl.TaskRunner.call(TaskRunner.java:88) ~[classes/:?]
	at com.hazelcast.scheduledexecutor.impl.TaskRunner.run(TaskRunner.java:104) ~[classes/:?]
	at com.hazelcast.spi.impl.executionservice.impl.DelegateAndSkipOnConcurrentExecutionDecorator$DelegateDecorator.run(DelegateAndSkipOnConcurrentExecutionDecorator.java:77) ~[classes/:?]
	at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217) ~[classes/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:866) ~[?:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76) ~[classes/:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) ~[classes/:?]
	at ------ submitted from ------.() ~[?:?]
	at com.hazelcast.internal.util.ExceptionUtil.cloneExceptionWithFixedAsyncStackTrace(ExceptionUtil.java:336) ~[classes/:?]
	at com.hazelcast.spi.impl.AbstractInvocationFuture.wrapRuntimeException(AbstractInvocationFuture.java:1968) ~[classes/:?]
	at com.hazelcast.spi.impl.AbstractInvocationFuture.wrapOrPeel(AbstractInvocationFuture.java:1949) ~[classes/:?]
	at com.hazelcast.spi.impl.AbstractInvocationFuture$ExceptionalResult.wrapForJoinInternal(AbstractInvocationFuture.java:1431) ~[classes/:?]
	at com.hazelcast.spi.impl.AbstractInvocationFuture.resolveAndThrowForJoinInternal(AbstractInvocationFuture.java:600) ~[classes/:?]
	at com.hazelcast.spi.impl.AbstractInvocationFuture.joinInternal(AbstractInvocationFuture.java:576) ~[classes/:?]
	at com.hazelcast.scheduledexecutor.impl.ScheduledExecutorContainer.publishTaskState(ScheduledExecutorContainer.java:435) [classes/:?]
	at com.hazelcast.scheduledexecutor.impl.TaskRunner.afterRun(TaskRunner.java:142) [classes/:?]
	at com.hazelcast.scheduledexecutor.impl.TaskRunner.call(TaskRunner.java:88) [classes/:?]
	at com.hazelcast.scheduledexecutor.impl.TaskRunner.run(TaskRunner.java:104) [classes/:?]
	at com.hazelcast.spi.impl.executionservice.impl.DelegateAndSkipOnConcurrentExecutionDecorator$DelegateDecorator.run(DelegateAndSkipOnConcurrentExecutionDecorator.java:77) [classes/:?]
	at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217) [classes/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:866) [?:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76) [classes/:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) [classes/:?]
03:26:27,905  INFO |schedule_withMapChanges_durable| - [LifecycleService] Thread-55163 - [127.0.0.1]:5702 [dev] [5.1.4-SNAPSHOT] [127.0.0.1]:5702 is SHUTTING_DOWN
03:26:27,905  WARN |schedule_withMapChanges_durable| - [Node] Thread-55163 - [127.0.0.1]:5702 [dev] [5.1.4-SNAPSHOT] Terminating forcefully...
03:26:27,905  INFO |schedule_withMapChanges_durable| - [Node] Thread-55163 - [127.0.0.1]:5702 [dev] [5.1.4-SNAPSHOT] Shutting down connection manager...
03:26:27,905  INFO |schedule_withMapChanges_durable| - [Node] Thread-55163 - [127.0.0.1]:5702 [dev] [5.1.4-SNAPSHOT] Shutting down node engine...
03:26:27,912  INFO |schedule_withMapChanges_durable| - [NodeExtension] Thread-55163 - [127.0.0.1]:5702 [dev] [5.1.4-SNAPSHOT] Destroying node NodeExtension.
03:26:27,912  INFO |schedule_withMapChanges_durable| - [Node] Thread-55163 - [127.0.0.1]:5702 [dev] [5.1.4-SNAPSHOT] Hazelcast Shutdown is completed in 7 ms.
03:26:27,913  INFO |schedule_withMapChanges_durable| - [LifecycleService] Thread-55163 - [127.0.0.1]:5702 [dev] [5.1.4-SNAPSHOT] [127.0.0.1]:5702 is SHUTDOWN
03:26:27,913  INFO |schedule_withMapChanges_durable| - [LifecycleService] Thread-55163 - [127.0.0.1]:5701 [dev] [5.1.4-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
03:26:27,913  INFO |schedule_withMapChanges_durable| - [Node] Thread-55163 - [127.0.0.1]:5701 [dev] [5.1.4-SNAPSHOT] Node is already shutting down... Waiting for shutdown process to complete...
03:26:27,913  INFO |schedule_withMapChanges_durable| - [LifecycleService] Thread-55163 - [127.0.0.1]:5701 [dev] [5.1.4-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
BuildInfo right after schedule_withMapChanges_durable(com.hazelcast.scheduledexecutor.impl.ScheduledExecutorServiceBasicTest): BuildInfo{version='5.1.4-SNAPSHOT', build='20220912', buildNumber=20220912, revision=21a222c, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'schedule_withMapChanges_durable(com.hazelcast.scheduledexecutor.impl.ScheduledExecutorServiceBasicTest):'
03:24:25, accumulated pauses: 298 ms, max pause: 55 ms, pauses over 1000 ms: 0
03:24:30, accumulated pauses: 277 ms, max pause: 11 ms, pauses over 1000 ms: 0
03:24:35, accumulated pauses: 248 ms, max pause: 108 ms, pauses over 1000 ms: 0
03:24:40, accumulated pauses: 167 ms, max pause: 6 ms, pauses over 1000 ms: 0
03:24:45, accumulated pauses: 190 ms, max pause: 6 ms, pauses over 1000 ms: 0
03:24:50, accumulated pauses: 145 ms, max pause: 4 ms, pauses over 1000 ms: 0
03:24:55, accumulated pauses: 178 ms, max pause: 6 ms, pauses over 1000 ms: 0
03:25:00, accumulated pauses: 183 ms, max pause: 10 ms, pauses over 1000 ms: 0
03:25:05, accumulated pauses: 214 ms, max pause: 3 ms, pauses over 1000 ms: 0
03:25:10, accumulated pauses: 132 ms, max pause: 3 ms, pauses over 1000 ms: 0
03:25:15, accumulated pauses: 159 ms, max pause: 6 ms, pauses over 1000 ms: 0
03:25:20, accumulated pauses: 102 ms, max pause: 3 ms, pauses over 1000 ms: 0
03:25:25, accumulated pauses: 148 ms, max pause: 7 ms, pauses over 1000 ms: 0
03:25:30, accumulated pauses: 113 ms, max pause: 20 ms, pauses over 1000 ms: 0
03:25:35, accumulated pauses: 92 ms, max pause: 4 ms, pauses over 1000 ms: 0
03:25:40, accumulated pauses: 182 ms, max pause: 11 ms, pauses over 1000 ms: 0
03:25:45, accumulated pauses: 114 ms, max pause: 5 ms, pauses over 1000 ms: 0
03:25:50, accumulated pauses: 211 ms, max pause: 5 ms, pauses over 1000 ms: 0
03:25:55, accumulated pauses: 187 ms, max pause: 4 ms, pauses over 1000 ms: 0
03:26:00, accumulated pauses: 173 ms, max pause: 33 ms, pauses over 1000 ms: 0
03:26:05, accumulated pauses: 148 ms, max pause: 3 ms, pauses over 1000 ms: 0
03:26:10, accumulated pauses: 131 ms, max pause: 14 ms, pauses over 1000 ms: 0
03:26:15, accumulated pauses: 170 ms, max pause: 3 ms, pauses over 1000 ms: 0
03:26:20, accumulated pauses: 92 ms, max pause: 3 ms, pauses over 1000 ms: 0
03:26:25, accumulated pauses: 169 ms, max pause: 61 ms, pauses over 1000 ms: 0
```

</details>

**Comment by AyberkSorgun** [comment]
Last failure older than Nov 1st, closing for now
