### ISSUE TITLE
RU 5.1 -> 5.2   com.hazelcast.core.HazelcastException: Cluster topology was not stable for 100 retries, invoke on stable cluster failed 

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#22198]
com.hazelcast.core.HazelcastException: Cluster topology was not stable for 100 retries, invoke on stable cluster failed 

http://jenkins.hazelcast.com/view/rollup/job/rollup-topic/199/console

/disk1/workspace/rollup-topic/5.2-SNAPSHOT/2022_09_12-09_27_17/topic 

```
com.hazelcast.core.HazelcastException: Cluster topology was not stable for 100 retries, invoke on stable cluster failed
	at com.hazelcast.internal.util.iterator.RestartingMemberIterator.retry(RestartingMemberIterator.java:93)
	at com.hazelcast.internal.util.iterator.RestartingMemberIterator.advance(RestartingMemberIterator.java:81)
	at com.hazelcast.internal.util.iterator.RestartingMemberIterator.hasNext(RestartingMemberIterator.java:75)
	at com.hazelcast.internal.util.IterableUtil$1.hasNext(IterableUtil.java:57)
	at com.hazelcast.internal.util.futures.ChainingFuture.advanceOrComplete(ChainingFuture.java:65)
	at com.hazelcast.internal.util.futures.ChainingFuture.lambda$registerCallback$0(ChainingFuture.java:55)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
	at ------ submitted from ------.()
	at com.hazelcast.internal.util.ExceptionUtil.cloneExceptionWithFixedAsyncStackTrace(ExceptionUtil.java:338)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.wrapRuntimeException(AbstractInvocationFuture.java:1969)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.wrapOrPeel(AbstractInvocationFuture.java:1950)
	at com.hazelcast.spi.impl.InternalCompletableFuture.joinInternal(InternalCompletableFuture.java:72)
	at com.hazelcast.internal.dynamicconfig.ClusterWideConfigurationService.broadcastConfig(ClusterWideConfigurationService.java:210)
	at com.hazelcast.internal.dynamicconfig.DynamicConfigurationAwareConfig.addMapConfig(DynamicConfigurationAwareConfig.java:265)
	at com.hazelcast.jet.sql.impl.schema.TablesStorage.initializeWithListener(TablesStorage.java:210)
	at com.hazelcast.jet.sql.impl.schema.TableResolverImpl.lambda$new$4(TableResolverImpl.java:99)
	at com.hazelcast.instance.impl.LifecycleServiceImpl.fireLifecycleEvent(LifecycleServiceImpl.java:72)
	at com.hazelcast.instance.impl.LifecycleServiceImpl.fireLifecycleEvent(LifecycleServiceImpl.java:66)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:241)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:196)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:134)
	at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:95)

```

**Comment by Danny-Hazelcast** [comment]
duplicate issue https://github.com/hazelcast/hazelcast/pull/22105
