### ISSUE TITLE
Hazelcast.newHazelcastInstance llegalStateException: Cluster is in PASSIVE state! Operation:  AddDynamicConfigOperation [HZ-1470]

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#22200]
8th aug passing run http://jenkins.hazelcast.com/view/hot-restart/job/hot-v-nodeShutdown/70/console

12 sep failing run http://jenkins.hazelcast.com/view/hot-restart/job/hot-v-nodeShutdown/72/console

```
java.lang.IllegalStateException: Cluster is in PASSIVE state! Operation: com.hazelcast.internal.dynamicconfig.AddDynamicConfigOperation{serviceName='hz:configurationService', identityHash=1269909484, partitionId=-1, replicaIndex=0, callId
=0, invocationTime=-1 (1969-12-31 23:59:59.999), waitTimeout=-1, callTimeout=60000, tenantControl=com.hazelcast.spi.impl.tenantcontrol.NoopTenantControl@0}
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.engineActive(Invocation.java:518)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:551)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:541)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:241)
	at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.invokeOnTarget(OperationServiceImpl.java:365)
	at com.hazelcast.internal.util.InvocationUtil$InvokeOnMemberFunction.invokeOnMember(InvocationUtil.java:156)
	at com.hazelcast.internal.util.InvocationUtil$InvokeOnMemberFunction.apply(InvocationUtil.java:133)
	at com.hazelcast.internal.util.InvocationUtil$InvokeOnMemberFunction.apply(InvocationUtil.java:113)
	at com.hazelcast.internal.util.IterableUtil$1.next(IterableUtil.java:62)
	at com.hazelcast.internal.util.futures.ChainingFuture.<init>(ChainingFuture.java:42)
	at com.hazelcast.internal.util.InvocationUtil.invokeOnStableClusterSerial(InvocationUtil.java:82)
	at com.hazelcast.internal.dynamicconfig.ClusterWideConfigurationService.broadcastConfigAsync(ClusterWideConfigurationService.java:235)
	at com.hazelcast.internal.dynamicconfig.ClusterWideConfigurationService.broadcastConfig(ClusterWideConfigurationService.java:209)
	at com.hazelcast.internal.dynamicconfig.DynamicConfigurationAwareConfig.addMapConfig(DynamicConfigurationAwareConfig.java:265)
	at com.hazelcast.jet.sql.impl.schema.TablesStorage.initializeWithListener(TablesStorage.java:210)
	at com.hazelcast.jet.sql.impl.schema.TableResolverImpl.lambda$new$4(TableResolverImpl.java:99)
	at com.hazelcast.instance.impl.LifecycleServiceImpl.fireLifecycleEvent(LifecycleServiceImpl.java:72)
	at com.hazelcast.instance.impl.LifecycleServiceImpl.fireLifecycleEvent(LifecycleServiceImpl.java:66)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:241)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:196)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:134)
	at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:95)
```

**Comment by krzysztofslusarski** [comment]
Probably fixed by https://github.com/hazelcast/hazelcast/pull/22105

**Comment by krzysztofslusarski** [comment]
https://github.com/hazelcast/hazelcast/pull/22105
