### ISSUE TITLE
com.hazelcast.map.impl.query.QueryIndexMigrationTest.testQueryWithIndexesWhileMigrating [HZ-1831]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#22235]
_5.1.z_ (commit 4c57ecce5cec43884ce3ada5a551d6f26d8d7459)

Failed on ZuluJDK17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-ZuluJDK17-nightly/29/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testQueryWithIndexesWhileMigrating_copyBehavior__COPY_ON_WRITE_/

Failed in variant `[copyBehavior: COPY_ON_WRITE]`.

<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: expected:<30> but was:<28>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at com.hazelcast.map.impl.query.QueryIndexMigrationTest.testQueryWithIndexesWhileMigrating(QueryIndexMigrationTest.java:182)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

</details>

Standard output can be found here - https://console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-5.maintenance-ZuluJDK17-nightly/29/

**Comment by olukas** [comment]
Failed again on _master_ with little-endian (Oracle JDK 8): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-nightly-little-endian/1/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testQueryWithIndexesWhileMigrating_copyBehavior__NEVER_/

**Comment by vbekiaris** [comment]
Query with indexes while migrating seems to be also the culprit in #21283.
Probably related test failure: #22090 (seems like a partition was missing from index after migrations)

**Comment by vbekiaris** [comment]
Closed with additional logging in https://github.com/hazelcast/hazelcast/pull/23113

**Comment by olukas** [comment]
Failed again on _master_ with ibm-8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-IbmJDK8-fips-nightly/527/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testQueryWithIndexesWhileMigrating_copyBehavior__NEVER_/

**Comment by olukas** [comment]
Failed again on _master_ with openjdk-19: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-OpenJDK-sts-nightly/28/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testQueryWithIndexesWhileMigrating_copyBehavior__NEVER_/

**Comment by Patras3** [comment]
Failed again on _5.3.z_ with oracle-8 in variant `[copyBehavior: COPY_ON_READ]`: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-OracleJDK8-nightly/99/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testQueryWithIndexesWhileMigrating_copyBehavior__COPY_ON_READ_/

**Comment by Patras3** [comment]
Failed again on _5.3.z_ with openjdk-17: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-ZuluJDK17-nightly/83/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testQueryWithIndexesWhileMigrating_copyBehavior__NEVER_/

**Comment by olukas** [comment]
Failed again on _master_ with openjdk-sts (openjdk-20): https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK-sts-nightly/67/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testQueryWithIndexesWhileMigrating_3/

**Comment by olukas** [comment]
Failed again on _master_ with IbmJDK8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-IbmJDK8-nightly/123/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testQueryWithIndexesWhileMigrating_copyBehavior__COPY_ON_WRITE_/

**Comment by Patras3** [comment]
Failed again on _master_ with oracle-17 (little-endian): https://jenkins.hazelcast.com/job/Hazelcast-master-nightly-little-endian/68/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testQueryWithIndexesWhileMigrating_copyBehavior__COPY_ON_READ_/

**Comment by sumnerib** [comment]
Failed again on _master_ with openj9-21: https://jenkins.hazelcast.com/job/Hazelcast-master-Openj9-21-nightly/10/testReport/junit/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testQueryWithIndexesWhileMigrating_copyBehavior__COPY_ON_WRITE_/

**Comment by sumnerib** [comment]
Failed again on _5.3.z_ with ibm-8: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-IbmJDK8-nightly/132/testReport/junit/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testQueryWithIndexesWhileMigrating_copyBehavior__NEVER_/

**Comment by Patras3** [comment]
Failed again on _5.1.z_ with oracle-8: https://jenkins.hazelcast.com/job/Hazelcast-5.1.z-OracleJDK8-nightly/50/testReport/junit/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testQueryWithIndexesWhileMigrating_copyBehavior__NEVER_/

**Comment by AleksPeychev** [comment]
Failed again on _master_ with oracle-17 (force-offload): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-nightly-force-offload/103/testReport/junit/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testQueryWithIndexesWhileMigrating_copyBehavior__COPY_ON_WRITE_/

**Comment by olukas** [comment]
Failed again on _master_ with oracle-17 (sonar build): https://jenkins.hazelcast.com/job/Hazelcast-master-sonar/535/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testQueryWithIndexesWhileMigrating_copyBehavior__COPY_ON_READ_/

**Comment by olukas** [comment]
Failed again on _master_ with oracle-17 (sonar build): https://jenkins.hazelcast.com/job/Hazelcast-mono-OS-master-sonar/225/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testQueryWithIndexesWhileMigrating_copyBehavior__NEVER_/

**Comment by olukas** [comment]
Failed again on _master_ with CorrettoJDK17: https://jenkins.hazelcast.com/job/Hazelcast-master-CorrettoJDK17-arm64-nightly/30/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testQueryWithIndexesWhileMigrating_copyBehavior__COPY_ON_WRITE_/

**Comment by olukas** [comment]
Failed again on _5.5.z_ with openj9-21: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-Openj9-21-nightly/22/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testQueryWithIndexesWhileMigrating_copyBehavior__NEVER_/

**Comment by AleksPeychev** [comment]
Failed again on _master_ with CorrettoJDK17 (arm64): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-CorrettoJDK17-arm64-nightly/45/testReport/junit/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testQueryWithIndexesWhileMigrating_copyBehavior__NEVER_/
