### ISSUE TITLE
java.lang.IllegalArgumentException: name when import resouce in springboot executable jar

### ISSUE THREAD

**Issue by trydofor** [hazelcast/hazelcast#22245]
**Describe the bug**

* java openjdk 11.0.2
* spring boot 2.6.6
* hazelcast IMDG 4.2.4

```log
Caused by: java.lang.IllegalArgumentException: name
	at java.base/jdk.internal.loader.URLClassPath$Loader.findResource(URLClassPath.java:600) ~[na:na]
	at java.base/jdk.internal.loader.URLClassPath.findResource(URLClassPath.java:291) ~[na:na]
	at java.base/java.net.URLClassLoader$2.run(URLClassLoader.java:655) ~[na:na]
	at java.base/java.net.URLClassLoader$2.run(URLClassLoader.java:653) ~[na:na]
	at java.base/java.security.AccessController.doPrivileged(Native Method) ~[na:na]
	at java.base/java.net.URLClassLoader.findResource(URLClassLoader.java:652) ~[na:na]
	at org.springframework.boot.loader.LaunchedURLClassLoader.findResource(LaunchedURLClassLoader.java:100) ~[winx-devops-2.6.6-SNAPSHOT.jar-4bf8de7802ab8e51110890b78be3a1c8:2.6.6-SNAPSHOT]
	at java.base/java.lang.ClassLoader.getResource(ClassLoader.java:1400) ~[na:na]
	at com.hazelcast.internal.config.ConfigLoader.asResource(ConfigLoader.java:100) ~[hazelcast-4.2.4.jar!/:4.2.4]
	at com.hazelcast.internal.config.ConfigLoader.locateConfig(ConfigLoader.java:56) ~[hazelcast-4.2.4.jar!/:4.2.4]
	at com.hazelcast.config.AbstractXmlConfigBuilder.replaceImports(AbstractXmlConfigBuilder.java:145) ~[hazelcast-4.2.4.jar!/:4.2.4]
	at com.hazelcast.config.AbstractXmlConfigBuilder.process(AbstractXmlConfigBuilder.java:99) ~[hazelcast-4.2.4.jar!/:4.2.4]
	at com.hazelcast.config.XmlConfigBuilder.parseAndBuildConfig(XmlConfigBuilder.java:167) ~[hazelcast-4.2.4.jar!/:4.2.4]
	at com.hazelcast.config.XmlConfigBuilder.build(XmlConfigBuilder.java:151) ~[hazelcast-4.2.4.jar!/:4.2.4]
	at com.hazelcast.config.XmlConfigBuilder.build(XmlConfigBuilder.java:144) ~[hazelcast-4.2.4.jar!/:4.2.4]

```

**Expected behavior**

should start up application

**To Reproduce**

① use import resource `classpath:` in config
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!--suppress HttpUrlsUsage -->
<hazelcast xmlns="http://www.hazelcast.com/schema/config"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.hazelcast.com/schema/config
           http://www.hazelcast.com/schema/config/hazelcast-config-4.2.xsd">

    <import resource="classpath:extra-conf/hazelcast-server.xml"/>
    <import resource="classpath:extra-conf/hazelcast-server-session.xml"/>
</hazelcast>
```

② `mvn package` springboot executable jar
③ start the boot jar

**Additional context**

if remove `classpath:` prefix, then it works

```xml
<import resource="extra-conf/hazelcast-server.xml"/>
<import resource="extra-conf/hazelcast-server-session.xml"/>
```

because the `ConfigLoader#locateConfig` handle `classpath:` at the last,
but Exception thrown at line 56.

should call `extractPathOrNull()` before `asResource()` line 56

```java
if (url == null) {
    url = asResource(path); // line 56
}
if (url == null) {
    String extractedPath = extractPathOrNull(path);
    if (extractedPath == null) {
        return null;
    }
    url = asResource(extractedPath);
}
```

**Comment by konikvranik** [comment]
Is the fix planed in the near future?

**Comment by trydofor** [comment]
in the latest code, no changes yet

https://github.com/hazelcast/hazelcast/blob/7c3894b1474dba56648cf10ad8441615486fcdea/hazelcast/src/main/java/com/hazelcast/internal/config/ConfigLoader.java#L47-L66
