### ISSUE TITLE
Suspending a job prints the following error log with an exception into the log [HZ-1484]

### ISSUE THREAD

**Issue by frant-hartm** [hazelcast/hazelcast#22254]
**Describe the bug**

Suspending a job prints the following error log with an exception into the log.

**Expected behavior**

No exception is printed. (This is the state in 5.1.4).

**To Reproduce**

1. Submit any streaming job (e.g. hello-world job from https://github.com/hazelcast/hazelcast-code-samples/tree/master/jet/hello-world)

2. Suspend the job
```
bin/hz-cli suspend hello-world
```

3. In the log there is the following exception:
```
2022-09-16 11:20:16,267 [ERROR] [ForkJoinPool.commonPool-worker-9] [c.h.j.i.o.StartExecutionOperation]: [172.17.0.2]:5701 [dev] [5.2-SNAPSHOT] null
com.hazelcast.jet.impl.exception.TerminatedWithSnapshotException: null
	at com.hazelcast.jet.impl.execution.ExecutionContext.lambda$beginExecution$3(ExecutionContext.java:240) ~[hazelcast-5.2-SNAPSHOT.jar:5.2-SNAPSHOT]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073) ~[?:?]
	at com.hazelcast.jet.impl.util.NonCompletableFuture.internalComplete(NonCompletableFuture.java:68) ~[hazelcast-5.2-SNAPSHOT.jar:5.2-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$ExecutionTracker.taskletDone(TaskletExecutionService.java:496) ~[hazelcast-5.2-SNAPSHOT.jar:5.2-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.dismissTasklet(TaskletExecutionService.java:429) ~[hazelcast-5.2-SNAPSHOT.jar:5.2-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:406) ~[hazelcast-5.2-SNAPSHOT.jar:5.2-SNAPSHOT]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807) ~[?:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.run(TaskletExecutionService.java:369) ~[hazelcast-5.2-SNAPSHOT.jar:5.2-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
```

**Additional context**

Latest 5.2-SNAPSHOT (85fcced)

Marking as critical because of the amount of support tickets / questions that would be raised if we leave this unattended.

**Comment by TomaszGaweda** [comment]
BTW., `cancel` will throw CancellationException. I was once told it's by design, because jobs - especially streams - are not supposed to be suspended/cancelled. I don't think it's a good UX, leaving open question for 5.3 ;)
