### ISSUE TITLE
Activator start error in bundle com.hazelcast

### ISSUE THREAD

**Issue by foreverdeepak** [hazelcast/hazelcast#2233]
We are facing following issue when we try to install the Hazelcast in OSGi container. We are using JBoss Fuse version 6.
# 

java.lang.Exception: Could not start bundle mvn:com.hazelcast/hazelcast/3.2 in feature(s) sm-core-0.0.1-SNAPSHOT: Activator start error in bundle com.hazelcast [248].
    at org.apache.karaf.features.internal.FeaturesServiceImpl.installFeatures(FeaturesServiceImpl.java:460)[22:org.apache.karaf.features.core:2.3.0.redhat-60024]
    at org.apache.karaf.features.internal.FeaturesServiceImpl.installFeature(FeaturesServiceImpl.java:387)[22:org.apache.karaf.features.core:2.3.0.redhat-60024]
    at org.apache.karaf.features.internal.FeaturesServiceImpl.installFeature(FeaturesServiceImpl.java:383)[22:org.apache.karaf.features.core:2.3.0.redhat-60024]
    at org.apache.karaf.features.command.InstallFeatureCommand.doExecute(InstallFeatureCommand.java:62)[37:org.apache.karaf.features.command:2.3.0.redhat-60024]
    at org.apache.karaf.features.command.FeaturesCommandSupport.doExecute(FeaturesCommandSupport.java:41)[37:org.apache.karaf.features.command:2.3.0.redhat-60024]
    at org.apache.karaf.shell.console.OsgiCommandSupport.execute(OsgiCommandSupport.java:38)[15:org.apache.karaf.shell.console:2.3.0.redhat-60024]
    at org.apache.felix.gogo.commands.basic.AbstractCommand.execute(AbstractCommand.java:35)[15:org.apache.karaf.shell.console:2.3.0.redhat-60024]
    at org.apache.felix.gogo.runtime.CommandProxy.execute(CommandProxy.java:78)[15:org.apache.karaf.shell.console:2.3.0.redhat-60024]
    at org.apache.felix.gogo.runtime.Closure.executeCmd(Closure.java:474)[15:org.apache.karaf.shell.console:2.3.0.redhat-60024]
    at org.apache.felix.gogo.runtime.Closure.executeStatement(Closure.java:400)[15:org.apache.karaf.shell.console:2.3.0.redhat-60024]
    at org.apache.felix.gogo.runtime.Pipe.run(Pipe.java:108)[15:org.apache.karaf.shell.console:2.3.0.redhat-60024]
    at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:183)[15:org.apache.karaf.shell.console:2.3.0.redhat-60024]
    at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:120)[15:org.apache.karaf.shell.console:2.3.0.redhat-60024]
    at org.apache.felix.gogo.runtime.CommandSessionImpl.execute(CommandSessionImpl.java:89)[15:org.apache.karaf.shell.console:2.3.0.redhat-60024]
    at org.apache.karaf.shell.console.jline.Console.run(Console.java:176)[15:org.apache.karaf.shell.console:2.3.0.redhat-60024]
    at org.apache.karaf.shell.console.jline.DelayedStarted.run(DelayedStarted.java:61)[15:org.apache.karaf.shell.console:2.3.0.redhat-60024]
Caused by: org.osgi.framework.BundleException: Activator start error in bundle com.hazelcast [248].
    at org.apache.felix.framework.Felix.doActivateBundle(Felix.java:2367)[org.apache.felix.framework-4.0.3.redhat-60024.jar:]
    at org.apache.felix.framework.Felix$7.call(Felix.java:2255)[org.apache.felix.framework-4.0.3.redhat-60024.jar:]
    at org.apache.felix.framework.Felix$6.call(Felix.java:2199)[org.apache.felix.framework-4.0.3.redhat-60024.jar:]
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)[:1.6.0_65]
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)[:1.6.0_65]
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)[:1.6.0_65]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)[:1.6.0_65]
    at java.lang.Thread.run(Thread.java:695)[:1.6.0_65]
Caused by: java.lang.NoSuchMethodError: javax.script.ScriptEngineManager.setBindings(Ljavax/script/Bindings;)V
    at com.hazelcast.osgi.OSGiScriptEngineManager.createScriptEngineManager(OSGiScriptEngineManager.java:263)
    at com.hazelcast.osgi.OSGiScriptEngineManager.findManagers(OSGiScriptEngineManager.java:236)
    at com.hazelcast.osgi.OSGiScriptEngineManager.<init>(OSGiScriptEngineManager.java:88)
    at com.hazelcast.osgi.Activator.start(Activator.java:45)
    at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:645)
#     at org.apache.felix.framework.Felix.doActivateBundle(Felix.java:2317)

For workaround, I have removed the bundle activator from MANIFEST.MF. 

Please let us know the correct solution to fix this issue.

**Comment by thomasmodeneis** [comment]
Sorry for reviving the death here, but I'm also facing the same problem with Java7 + Fuse 6.1, even after enabling the javax.script on jre.properties the bundle won't start, I'm not sure how to deal with this yet but if I happen to find a solution I will get back here.
