### ISSUE TITLE
com.hazelcast.jet.sql_slow.MapScanMigrationStressTest.stressTest_sortedIndex [HZ-1537]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#22358]
_master_ (commit f61564859c808033ab4f49ea6de52e7bc5b0b3d3)

Failed on Sonar build (Oracle JDK 11): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/1354/testReport/com.hazelcast.jet.sql_slow/MapScanMigrationStressTest/stressTest_sortedIndex/

<details><summary>Stacktrace:</summary>

```
com.hazelcast.sql.HazelcastSqlException: The Jet SQL job failed: Execution on a member failed: com.hazelcast.jet.JetException: Exception in ProcessorTasklet{08b6-281a-4840-0001/Index(IMap[public.map])#0}: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.hazelcast.spi.exception.RetryableHazelcastException: Index is being rebuilt
	at com.hazelcast.sql.impl.QueryUtils.toPublicException(QueryUtils.java:74)
	at com.hazelcast.jet.sql.impl.SqlResultImpl$RowToSqlRowIterator.hasNext(SqlResultImpl.java:108)
	at com.hazelcast.jet.sql_slow.MapScanMigrationStressTest.executeAndGetResult(MapScanMigrationStressTest.java:219)
	at com.hazelcast.jet.sql_slow.MapScanMigrationStressTest.assertRowsOrdered(MapScanMigrationStressTest.java:202)
	at com.hazelcast.jet.sql_slow.MapScanMigrationStressTest.stressTest_sortedIndex(MapScanMigrationStressTest.java:155)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.hazelcast.sql.impl.QueryException: The Jet SQL job failed: Execution on a member failed: com.hazelcast.jet.JetException: Exception in ProcessorTasklet{08b6-281a-4840-0001/Index(IMap[public.map])#0}: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.hazelcast.spi.exception.RetryableHazelcastException: Index is being rebuilt
	at com.hazelcast.sql.impl.QueryException.error(QueryException.java:65)
	at com.hazelcast.jet.sql.impl.PlanExecutor.lambda$execute$2(PlanExecutor.java:375)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at com.hazelcast.jet.impl.util.NonCompletableFuture.internalCompleteExceptionally(NonCompletableFuture.java:72)
	at com.hazelcast.jet.impl.AbstractJobProxy$CallbackBase.accept(AbstractJobProxy.java:363)
	at com.hazelcast.jet.impl.AbstractJobProxy$CallbackBase.accept(AbstractJobProxy.java:346)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$WhenCompleteNode.lambda$execute$0(AbstractInvocationFuture.java:1564)
	at com.hazelcast.test.TestLoggingUtils$CustomTestNameAwareForkJoinPool$TestNameAwareRunnable.run(TestLoggingUtils.java:104)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: com.hazelcast.jet.JetException: Execution on a member failed: com.hazelcast.jet.JetException: Exception in ProcessorTasklet{08b6-281a-4840-0001/Index(IMap[public.map])#0}: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.hazelcast.spi.exception.RetryableHazelcastException: Index is being rebuilt
	at com.hazelcast.jet.impl.LightMasterContext.findError(LightMasterContext.java:310)
	at com.hazelcast.jet.impl.LightMasterContext.lambda$createContext$2(LightMasterContext.java:164)
	at com.hazelcast.jet.impl.LightMasterContext.lambda$invokeOnParticipant$8(LightMasterContext.java:281)
	... 8 more
Caused by: com.hazelcast.jet.JetException: Exception in ProcessorTasklet{08b6-281a-4840-0001/Index(IMap[public.map])#0}: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.hazelcast.spi.exception.RetryableHazelcastException: Index is being rebuilt
	at com.hazelcast.jet.impl.execution.TaskletExecutionService.handleTaskletExecutionError(TaskletExecutionService.java:286)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService.access$600(TaskletExecutionService.java:80)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:410)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.run(TaskletExecutionService.java:369)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.hazelcast.spi.exception.RetryableHazelcastException: Index is being rebuilt
	at com.hazelcast.jet.sql.impl.connector.map.MapIndexScanP$Split.peek(MapIndexScanP.java:338)
	at com.hazelcast.jet.sql.impl.connector.map.MapIndexScanP$Split.access$200(MapIndexScanP.java:286)
	at com.hazelcast.jet.sql.impl.connector.map.MapIndexScanP.runSortedIndex(MapIndexScanP.java:170)
	at com.hazelcast.jet.sql.impl.connector.map.MapIndexScanP.complete(MapIndexScanP.java:149)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.complete(ProcessorTasklet.java:541)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:421)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:291)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:404)
	... 3 more
Caused by: java.util.concurrent.ExecutionException: com.hazelcast.spi.exception.RetryableHazelcastException: Index is being rebuilt
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.returnOrThrowWithGetConventions(InvocationFuture.java:121)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:100)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:609)
	at com.hazelcast.jet.impl.connector.AbstractIndexReader.toBatchResult(AbstractIndexReader.java:59)
	at com.hazelcast.jet.sql.impl.connector.map.MapIndexScanP$Split.peek(MapIndexScanP.java:331)
	... 10 more
Caused by: com.hazelcast.spi.exception.RetryableHazelcastException: Index is being rebuilt
	at com.hazelcast.map.impl.operation.MapFetchIndexOperation.runInternal(MapFetchIndexOperation.java:103)
	at com.hazelcast.map.impl.operation.MapOperation.run(MapOperation.java:153)
	at com.hazelcast.map.impl.operation.MapOperation.call(MapOperation.java:173)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:281)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:256)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:217)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:175)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:139)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
	at ------ submitted from ------.()
	at com.hazelcast.internal.util.ExceptionUtil.cloneExceptionWithFixedAsyncStackTrace(ExceptionUtil.java:348)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.returnOrThrowWithGetConventions(InvocationFuture.java:112)
	... 14 more
```

</details>

Standard output can be found here - https://console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-sonar/1354/

**Comment by krzysztofslusarski** [comment]
This is just a test failure, I will try to redesign the test.

**Comment by krzysztofslusarski** [comment]
Fixed in https://github.com/hazelcast/hazelcast/pull/22368
