### ISSUE TITLE
com.hazelcast.internal.serialization.impl.compact.integration.CompactFormatSplitBrainTest [API-1760]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#22353]
_master_ (commit 40701e7d06bfd9feff165c04fd0744f2ff365f29)

Failed on Sonar build (Oracle JDK 11): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/1353/testReport/com.hazelcast.internal.serialization.impl.compact.integration/CompactFormatSplitBrainTest/testSplitBrainHealing_whenBothClusterHaveSameSchemas/

<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: Cluster size is not correct. Expected: 2, actual: 1, instance index: 0
	at org.junit.Assert.fail(Assert.java:89)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSize(HazelcastTestSupport.java:1021)
	at com.hazelcast.test.HazelcastTestSupport.lambda$assertClusterSizeEventually$9(HazelcastTestSupport.java:1056)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1236)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1253)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:1056)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:1034)
	at com.hazelcast.internal.serialization.impl.compact.integration.CompactFormatSplitBrainTest.splitCluster(CompactFormatSplitBrainTest.java:171)
	at com.hazelcast.internal.serialization.impl.compact.integration.CompactFormatSplitBrainTest.testSplitBrainHealing_whenBothClusterHaveSameSchemas(CompactFormatSplitBrainTest.java:120)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

</details>

Standard output can be found here - https://console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-sonar/1353/

**Comment by Patras3** [comment]
The same issue for another test case (testSplitBrainHealing_whenSmallerClusterHasNoSchemas):
* on _5.2.z_ with Openj9-17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-Openj9-17/33/testReport/junit/com.hazelcast.internal.serialization.impl.compact.integration/CompactFormatSplitBrainTest/testSplitBrainHealing_whenSmallerClusterHasNoSchemas/

**Comment by Patras3** [comment]
Failed again on _master_ with OpenJDK20: https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK20/11/testReport/junit/com.hazelcast.internal.serialization.impl.compact.integration/CompactFormatSplitBrainTest/testSplitBrainHealing_whenBothClusterHaveSameSchemas/

**Comment by frant-hartm** [comment]
Failed on master PR builder
https://github.com/hazelcast/hazelcast/pull/22996#issuecomment-1330366330
https://jenkins.hazelcast.com/job/Hazelcast-pr-builder/14574/
