### ISSUE TITLE
com.hazelcast.datastore.impl.ExternalDataStoreServiceImplTest and com.hazelcast.datastore.JdbcDataStoreFactoryTest

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#22416]
_master_ (commit ee8ce2f87e78086c74d71b339d30eec110e28cde)

Failed on OracleJDK17: 
- https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-OracleJDK17/50/testReport/com.hazelcast.datastore/JdbcDataStoreFactoryTest/should_close_shared_datasource_on_close/
- https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-OracleJDK17/50/testReport/com.hazelcast.datastore/JdbcDataStoreFactoryTest/should_return_closing_datastore_when_not_shared/
- https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-OracleJDK17/50/testReport/com.hazelcast.datastore.impl/ExternalDataStoreServiceImplTest/should_close_factories/

Following tests failed with the same exception:
- `com.hazelcast.datastore.JdbcDataStoreFactoryTest.should_close_shared_datasource_on_close`
- `com.hazelcast.datastore.JdbcDataStoreFactoryTest.should_return_closing_datastore_when_not_shared`
- `com.hazelcast.datastore.impl.ExternalDataStoreServiceImplTest.should_close_factories`

<details><summary>Stacktrace (for com.hazelcast.datastore.JdbcDataStoreFactoryTest.should_close_shared_datasource_on_close as an example):</summary>

```
java.lang.AssertionError: 

Expecting message to be:
  <"HikariDataSource HikariDataSource (HikariPool-1) has been closed.">
but was:
  <"HikariDataSource HikariDataSource (HikariPool-3) has been closed.">

Throwable that failed the check:

java.sql.SQLException: HikariDataSource HikariDataSource (HikariPool-3) has been closed.
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:96)
	at com.hazelcast.datastore.JdbcDataStoreFactoryTest.executeQuery(JdbcDataStoreFactoryTest.java:143)
	at com.hazelcast.datastore.JdbcDataStoreFactoryTest.lambda$should_close_shared_datasource_on_close$1(JdbcDataStoreFactoryTest.java:137)
	at org.assertj.core.api.ThrowableAssert.catchThrowable(ThrowableAssert.java:62)
	at org.assertj.core.api.AssertionsForClassTypes.catchThrowable(AssertionsForClassTypes.java:750)
	at org.assertj.core.api.Assertions.catchThrowable(Assertions.java:1179)
	at org.assertj.core.api.Assertions.assertThatThrownBy(Assertions.java:1051)
	at com.hazelcast.datastore.JdbcDataStoreFactoryTest.should_close_shared_datasource_on_close(JdbcDataStoreFactoryTest.java:137)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)

	at com.hazelcast.datastore.JdbcDataStoreFactoryTest.should_close_shared_datasource_on_close(JdbcDataStoreFactoryTest.java:139)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

</details>

**Comment by ldziedziul** [comment]
It was reverted due to ongoing release so it's no longer the case. 

I've recreated a PR to be merge after the 5.2.0 release, but added the fix: https://github.com/hazelcast/hazelcast/pull/22422
