### ISSUE TITLE
com.hazelcast.wan.impl.WanPublisherMigrationTest.testMigration [HZ-1853]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#22434]
_5.1.z_ (commit 9299b3e2d86875556945dbe047cca99ee65958e5)

Failed on ZuluJDK8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-ZuluJDK8/53/testReport/com.hazelcast.wan.impl/WanPublisherMigrationTest/testMigration_failMigrations_false_/

<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: not expected migrationCommit count (MigrationCountingWanPublisher{failMigration=false, migrationStart=6, migrationCommit=4, migrationRollback=0, migrationProcess=6}) expected:<6> but was:<4>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at com.hazelcast.wan.impl.WanPublisherMigrationTest.testMigration(WanPublisherMigrationTest.java:128)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

</details>

<details><summary>Standard output:</summary>

```
09:33:22,017  INFO |testMigration[failMigrations:false]| - [MetricsConfigHelper] testMigration - [LOCAL] [dev] [5.1.5-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
09:33:22,018  INFO |testMigration[failMigrations:false]| - [logo] testMigration - [127.0.0.1]:5701 [dev] [5.1.5-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
09:33:22,018  INFO |testMigration[failMigrations:false]| - [system] testMigration - [127.0.0.1]:5701 [dev] [5.1.5-SNAPSHOT] Copyright (c) 2008-2022, Hazelcast, Inc. All Rights Reserved.
09:33:22,018  INFO |testMigration[failMigrations:false]| - [system] testMigration - [127.0.0.1]:5701 [dev] [5.1.5-SNAPSHOT] Hazelcast Platform 5.1.5-SNAPSHOT (20221009 - 9299b3e) starting at [127.0.0.1]:5701
09:33:22,018  INFO |testMigration[failMigrations:false]| - [system] testMigration - [127.0.0.1]:5701 [dev] [5.1.5-SNAPSHOT] Cluster name: dev
09:33:22,018  INFO |testMigration[failMigrations:false]| - [system] testMigration - [127.0.0.1]:5701 [dev] [5.1.5-SNAPSHOT] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed.
To enable integrity checker do one of the following: 
  - Change member config using Java API: config.setIntegrityCheckerEnabled(true);
  - Change XML/YAML configuration property: Set hazelcast.integrity-checker.enabled to true
  - Add system property: -Dhz.integritychecker.enabled=true (for Hazelcast embedded, works only when loading config via Config.load)
  - Add environment variable: HZ_INTEGRITYCHECKER_ENABLED=true (recommended when running container image. For Hazelcast embedded, works only when loading config via Config.load)
09:33:22,018  INFO |testMigration[failMigrations:false]| - [system] testMigration - [127.0.0.1]:5701 [dev] [5.1.5-SNAPSHOT] Jet is enabled
09:33:22,022  INFO |testMigration[failMigrations:false]| - [MetricsConfigHelper] testMigration - [127.0.0.1]:5701 [dev] [5.1.5-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
09:33:22,027  WARN |testMigration[failMigrations:false]| - [CPSubsystem] testMigration - [127.0.0.1]:5701 [dev] [5.1.5-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
09:33:22,029  INFO |testMigration[failMigrations:false]| - [JetServiceBackend] testMigration - [127.0.0.1]:5701 [dev] [5.1.5-SNAPSHOT] Setting number of cooperative threads and default parallelism to 2
09:33:22,030  INFO |testMigration[failMigrations:false]| - [Diagnostics] testMigration - [127.0.0.1]:5701 [dev] [5.1.5-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
09:33:22,030  INFO |testMigration[failMigrations:false]| - [LifecycleService] testMigration - [127.0.0.1]:5701 [dev] [5.1.5-SNAPSHOT] [127.0.0.1]:5701 is STARTING
09:33:22,030  INFO |testMigration[failMigrations:false]| - [ClusterService] testMigration - [127.0.0.1]:5701 [dev] [5.1.5-SNAPSHOT] 

Members {size:1, ver:1} [
	Member [127.0.0.1]:5701 - 1538dff9-9c4f-45c1-b2f5-472a60571b12 this
]

09:33:22,030  INFO |testMigration[failMigrations:false]| - [JobCoordinationService] testMigration - [127.0.0.1]:5701 [dev] [5.1.5-SNAPSHOT] Jet started scanning for jobs
09:33:22,030 DEBUG |testMigration[failMigrations:false]| - [JobCoordinationService] hz.cool_blackburn.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.1.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
09:33:22,031  INFO |testMigration[failMigrations:false]| - [LifecycleService] testMigration - [127.0.0.1]:5701 [dev] [5.1.5-SNAPSHOT] [127.0.0.1]:5701 is STARTED
09:33:22,031  INFO |testMigration[failMigrations:false]| - [HealthMonitor] hz.cool_blackburn.HealthMonitor - [127.0.0.1]:5701 [dev] [5.1.5-SNAPSHOT] processors=8, physical.memory.total=377.8G, physical.memory.free=187.5G, swap.space.total=8.0G, swap.space.free=6.7G, heap.memory.used=3.6G, heap.memory.free=277.6M, heap.memory.total=3.9G, heap.memory.max=3.9G, heap.memory.used/total=93.00%, heap.memory.used/max=93.00%, minor.gc.count=1140, minor.gc.time=108692ms, major.gc.count=12, major.gc.time=12926ms, load.process=0.42%, load.system=27.59%, load.systemAverage=8.78, thread.count=152, thread.peakCount=1922, cluster.timeDiff=0, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=0, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=0, clientEndpoint.count=0, connection.active.count=0, client.connection.count=0, connection.count=0
09:33:22,031  INFO |testMigration[failMigrations:false]| - [MetricsConfigHelper] testMigration - [LOCAL] [dev] [5.1.5-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
09:33:22,032  INFO |testMigration[failMigrations:false]| - [logo] testMigration - [127.0.0.1]:5702 [dev] [5.1.5-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
09:33:22,032  INFO |testMigration[failMigrations:false]| - [system] testMigration - [127.0.0.1]:5702 [dev] [5.1.5-SNAPSHOT] Copyright (c) 2008-2022, Hazelcast, Inc. All Rights Reserved.
09:33:22,032  INFO |testMigration[failMigrations:false]| - [system] testMigration - [127.0.0.1]:5702 [dev] [5.1.5-SNAPSHOT] Hazelcast Platform 5.1.5-SNAPSHOT (20221009 - 9299b3e) starting at [127.0.0.1]:5702
09:33:22,032  INFO |testMigration[failMigrations:false]| - [system] testMigration - [127.0.0.1]:5702 [dev] [5.1.5-SNAPSHOT] Cluster name: dev
09:33:22,032  INFO |testMigration[failMigrations:false]| - [system] testMigration - [127.0.0.1]:5702 [dev] [5.1.5-SNAPSHOT] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed.
To enable integrity checker do one of the following: 
  - Change member config using Java API: config.setIntegrityCheckerEnabled(true);
  - Change XML/YAML configuration property: Set hazelcast.integrity-checker.enabled to true
  - Add system property: -Dhz.integritychecker.enabled=true (for Hazelcast embedded, works only when loading config via Config.load)
  - Add environment variable: HZ_INTEGRITYCHECKER_ENABLED=true (recommended when running container image. For Hazelcast embedded, works only when loading config via Config.load)
09:33:22,032  INFO |testMigration[failMigrations:false]| - [system] testMigration - [127.0.0.1]:5702 [dev] [5.1.5-SNAPSHOT] Jet is enabled
09:33:22,037  INFO |testMigration[failMigrations:false]| - [MetricsConfigHelper] testMigration - [127.0.0.1]:5702 [dev] [5.1.5-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
09:33:22,041  WARN |testMigration[failMigrations:false]| - [CPSubsystem] testMigration - [127.0.0.1]:5702 [dev] [5.1.5-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
09:33:22,044  INFO |testMigration[failMigrations:false]| - [JetServiceBackend] testMigration - [127.0.0.1]:5702 [dev] [5.1.5-SNAPSHOT] Setting number of cooperative threads and default parallelism to 2
09:33:22,045  INFO |testMigration[failMigrations:false]| - [Diagnostics] testMigration - [127.0.0.1]:5702 [dev] [5.1.5-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
09:33:22,045  INFO |testMigration[failMigrations:false]| - [LifecycleService] testMigration - [127.0.0.1]:5702 [dev] [5.1.5-SNAPSHOT] [127.0.0.1]:5702 is STARTING
09:33:22,045  INFO |testMigration[failMigrations:false]| - [MockServer] testMigration - [127.0.0.1]:5702 [dev] [5.1.5-SNAPSHOT] Created connection to endpoint: [127.0.0.1]:5701-1538dff9-9c4f-45c1-b2f5-472a60571b12, connection: MockConnection{localEndpoint=[address=[127.0.0.1]:5702, uuid=75002e11-bb2c-4a7c-91d6-4524c01537db], remoteEndpoint=[address=[127.0.0.1]:5701, uuid=1538dff9-9c4f-45c1-b2f5-472a60571b12], alive=true}
09:33:22,046  INFO |testMigration[failMigrations:false]| - [MockServer] hz.cool_blackburn.priority-generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [5.1.5-SNAPSHOT] Created connection to endpoint: [127.0.0.1]:5702-75002e11-bb2c-4a7c-91d6-4524c01537db, connection: MockConnection{localEndpoint=[address=[127.0.0.1]:5701, uuid=1538dff9-9c4f-45c1-b2f5-472a60571b12], remoteEndpoint=[address=[127.0.0.1]:5702, uuid=75002e11-bb2c-4a7c-91d6-4524c01537db], alive=true}
09:33:22,046  INFO |testMigration[failMigrations:false]| - [ClusterService] hz.cool_blackburn.priority-generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [5.1.5-SNAPSHOT] 

Members {size:2, ver:2} [
	Member [127.0.0.1]:5701 - 1538dff9-9c4f-45c1-b2f5-472a60571b12 this
	Member [127.0.0.1]:5702 - 75002e11-bb2c-4a7c-91d6-4524c01537db
]

09:33:22,131 DEBUG |testMigration[failMigrations:false]| - [JobCoordinationService] hz.cool_blackburn.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.1.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
09:33:22,147  INFO |testMigration[failMigrations:false]| - [ClusterService] hz.zen_blackburn.generic-operation.thread-1 - [127.0.0.1]:5702 [dev] [5.1.5-SNAPSHOT] 

Members {size:2, ver:2} [
	Member [127.0.0.1]:5701 - 1538dff9-9c4f-45c1-b2f5-472a60571b12
	Member [127.0.0.1]:5702 - 75002e11-bb2c-4a7c-91d6-4524c01537db this
]

09:33:22,147  INFO |testMigration[failMigrations:false]| - [JobCoordinationService] testMigration - [127.0.0.1]:5702 [dev] [5.1.5-SNAPSHOT] Jet started scanning for jobs
09:33:22,147  INFO |testMigration[failMigrations:false]| - [LifecycleService] testMigration - [127.0.0.1]:5702 [dev] [5.1.5-SNAPSHOT] [127.0.0.1]:5702 is STARTED
09:33:22,147  INFO |testMigration[failMigrations:false]| - [PartitionStateManager] testMigration - [127.0.0.1]:5701 [dev] [5.1.5-SNAPSHOT] Initializing cluster partition table arrangement...
09:33:22,148  INFO |testMigration[failMigrations:false]| - [HealthMonitor] hz.zen_blackburn.HealthMonitor - [127.0.0.1]:5702 [dev] [5.1.5-SNAPSHOT] processors=8, physical.memory.total=377.8G, physical.memory.free=187.5G, swap.space.total=8.0G, swap.space.free=6.7G, heap.memory.used=3.6G, heap.memory.free=270.5M, heap.memory.total=3.9G, heap.memory.max=3.9G, heap.memory.used/total=93.18%, heap.memory.used/max=93.18%, minor.gc.count=1140, minor.gc.time=108692ms, major.gc.count=12, major.gc.time=12926ms, load.process=0.36%, load.system=12.13%, load.systemAverage=8.78, thread.count=176, thread.peakCount=1922, cluster.timeDiff=0, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=17, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=1, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=1, clientEndpoint.count=0, connection.active.count=0, client.connection.count=0, connection.count=0
09:33:22,163  INFO |testMigration[failMigrations:false]| - [LifecycleService] testMigration - [127.0.0.1]:5701 [dev] [5.1.5-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
09:33:22,164 DEBUG |testMigration[failMigrations:false]| - [JobCoordinationService] testMigration - [127.0.0.1]:5701 [dev] [5.1.5-SNAPSHOT] Added a shutting-down member: 1538dff9-9c4f-45c1-b2f5-472a60571b12
09:33:22,164  INFO |testMigration[failMigrations:false]| - [MigrationManager] hz.cool_blackburn.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.1.5-SNAPSHOT] Shutdown request of Member [127.0.0.1]:5701 - 1538dff9-9c4f-45c1-b2f5-472a60571b12 this is handled
09:33:22,165  INFO |testMigration[failMigrations:false]| - [MigrationManager] hz.cool_blackburn.migration - [127.0.0.1]:5701 [dev] [5.1.5-SNAPSHOT] Repartitioning cluster data. Migration tasks count: 6
09:33:22,168  INFO |testMigration[failMigrations:false]| - [MigrationManager] hz.cool_blackburn.migration - [127.0.0.1]:5701 [dev] [5.1.5-SNAPSHOT] All migration tasks have been completed. (repartitionTime=Sun Oct 09 09:33:22 UTC 2022, plannedMigrations=6, completedMigrations=6, remainingMigrations=0, totalCompletedMigrations=6, elapsedMigrationOperationTime=17ms, totalElapsedMigrationOperationTime=17ms, elapsedDestinationCommitTime=1ms, totalElapsedDestinationCommitTime=1ms, elapsedMigrationTime=18ms, totalElapsedMigrationTime=18ms)
09:33:22,169  INFO |testMigration[failMigrations:false]| - [Node] testMigration - [127.0.0.1]:5701 [dev] [5.1.5-SNAPSHOT] Shutting down connection manager...
09:33:22,169  WARN |testMigration[failMigrations:false]| - [OutboundResponseHandler] hz.zen_blackburn.priority-generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.1.5-SNAPSHOT] Cannot send response: true to [127.0.0.1]:5701. com.hazelcast.internal.partition.operation.PublishCompletedMigrationsOperation{serviceName='hz:core:partitionService', identityHash=127346548, partitionId=-1, replicaIndex=0, callId=144, invocationTime=1665308002168 (2022-10-09 09:33:22.168), waitTimeout=-1, callTimeout=60000, tenantControl=com.hazelcast.spi.impl.tenantcontrol.NoopTenantControl@0}
09:33:22,169  INFO |testMigration[failMigrations:false]| - [MockServer] testMigration - [127.0.0.1]:5702 [dev] [5.1.5-SNAPSHOT] Removed connection to endpoint: [address=[127.0.0.1]:5701, uuid=1538dff9-9c4f-45c1-b2f5-472a60571b12], connection: MockConnection{localEndpoint=[address=[127.0.0.1]:5702, uuid=75002e11-bb2c-4a7c-91d6-4524c01537db], remoteEndpoint=[address=[127.0.0.1]:5701, uuid=1538dff9-9c4f-45c1-b2f5-472a60571b12], alive=false}
09:33:22,169  INFO |testMigration[failMigrations:false]| - [MockServer] testMigration - [127.0.0.1]:5701 [dev] [5.1.5-SNAPSHOT] Removed connection to endpoint: [address=[127.0.0.1]:5702, uuid=75002e11-bb2c-4a7c-91d6-4524c01537db], connection: MockConnection{localEndpoint=[address=[127.0.0.1]:5701, uuid=1538dff9-9c4f-45c1-b2f5-472a60571b12], remoteEndpoint=[address=[127.0.0.1]:5702, uuid=75002e11-bb2c-4a7c-91d6-4524c01537db], alive=false}
09:33:22,169  WARN |testMigration[failMigrations:false]| - [MembershipManager] testMigration - [127.0.0.1]:5702 [dev] [5.1.5-SNAPSHOT] Member [127.0.0.1]:5701 - 1538dff9-9c4f-45c1-b2f5-472a60571b12 is suspected to be dead for reason: Connection manager is stopped on Member [127.0.0.1]:5701 - 1538dff9-9c4f-45c1-b2f5-472a60571b12 this
09:33:22,169  INFO |testMigration[failMigrations:false]| - [MembershipManager] testMigration - [127.0.0.1]:5702 [dev] [5.1.5-SNAPSHOT] Starting mastership claim process...
09:33:22,169  INFO |testMigration[failMigrations:false]| - [MembershipManager] testMigration - [127.0.0.1]:5702 [dev] [5.1.5-SNAPSHOT] Local MembersView{version=2, members=[MemberInfo{address=[127.0.0.1]:5701, uuid=1538dff9-9c4f-45c1-b2f5-472a60571b12, liteMember=false, memberListJoinVersion=1}, MemberInfo{address=[127.0.0.1]:5702, uuid=75002e11-bb2c-4a7c-91d6-4524c01537db, liteMember=false, memberListJoinVersion=2}]} with suspected members: [Member [127.0.0.1]:5701 - 1538dff9-9c4f-45c1-b2f5-472a60571b12] and initial addresses to ask: []
09:33:22,169  INFO |testMigration[failMigrations:false]| - [Node] testMigration - [127.0.0.1]:5701 [dev] [5.1.5-SNAPSHOT] Shutting down node engine...
09:33:22,169  INFO |testMigration[failMigrations:false]| - [ClusterService] hz.zen_blackburn.cached.thread-1 - [127.0.0.1]:5702 [dev] [5.1.5-SNAPSHOT] 

Members {size:1, ver:3} [
	Member [127.0.0.1]:5702 - 75002e11-bb2c-4a7c-91d6-4524c01537db this
]

09:33:22,169  INFO |testMigration[failMigrations:false]| - [MembershipManager] hz.zen_blackburn.cached.thread-1 - [127.0.0.1]:5702 [dev] [5.1.5-SNAPSHOT] Mastership is claimed with: MembersView{version=3, members=[MemberInfo{address=[127.0.0.1]:5702, uuid=75002e11-bb2c-4a7c-91d6-4524c01537db, liteMember=false, memberListJoinVersion=2}]}
09:33:22,169  INFO |testMigration[failMigrations:false]| - [TransactionManagerService] hz.zen_blackburn.cached.thread-3 - [127.0.0.1]:5702 [dev] [5.1.5-SNAPSHOT] Committing/rolling-back live transactions of [127.0.0.1]:5701, UUID: 1538dff9-9c4f-45c1-b2f5-472a60571b12
09:33:22,170  INFO |testMigration[failMigrations:false]| - [NodeExtension] testMigration - [127.0.0.1]:5701 [dev] [5.1.5-SNAPSHOT] Destroying node NodeExtension.
09:33:22,170  INFO |testMigration[failMigrations:false]| - [Node] testMigration - [127.0.0.1]:5701 [dev] [5.1.5-SNAPSHOT] Hazelcast Shutdown is completed in 6 ms.
09:33:22,170  INFO |testMigration[failMigrations:false]| - [LifecycleService] testMigration - [127.0.0.1]:5701 [dev] [5.1.5-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
09:33:23,897  INFO |testMigration[failMigrations:false]| - [InternalPartitionService] hz.zen_blackburn.migration - [127.0.0.1]:5702 [dev] [5.1.5-SNAPSHOT] Fetching partition tables from cluster to determine the most recent one... Local stamp: 3221439404905705215
09:33:23,897  INFO |testMigration[failMigrations:false]| - [InternalPartitionService] hz.zen_blackburn.migration - [127.0.0.1]:5702 [dev] [5.1.5-SNAPSHOT] Most recent partition table is determined.
09:33:23,897  INFO |testMigration[failMigrations:false]| - [InternalPartitionService] hz.zen_blackburn.migration - [127.0.0.1]:5702 [dev] [5.1.5-SNAPSHOT] Applying the most recent of partition state...
09:33:23,897  INFO |testMigration[failMigrations:false]| - [MigrationManager] hz.zen_blackburn.migration - [127.0.0.1]:5702 [dev] [5.1.5-SNAPSHOT] Partition balance is ok, no need to repartition.
09:33:23,911  INFO |testMigration[failMigrations:false]| - [LifecycleService] Thread-59396 - [127.0.0.1]:5702 [dev] [5.1.5-SNAPSHOT] [127.0.0.1]:5702 is SHUTTING_DOWN
09:33:23,911  WARN |testMigration[failMigrations:false]| - [Node] Thread-59396 - [127.0.0.1]:5702 [dev] [5.1.5-SNAPSHOT] Terminating forcefully...
09:33:23,911  INFO |testMigration[failMigrations:false]| - [Node] Thread-59396 - [127.0.0.1]:5702 [dev] [5.1.5-SNAPSHOT] Shutting down connection manager...
09:33:23,911  INFO |testMigration[failMigrations:false]| - [Node] Thread-59396 - [127.0.0.1]:5702 [dev] [5.1.5-SNAPSHOT] Shutting down node engine...
09:33:23,915  INFO |testMigration[failMigrations:false]| - [NodeExtension] Thread-59396 - [127.0.0.1]:5702 [dev] [5.1.5-SNAPSHOT] Destroying node NodeExtension.
09:33:23,915  INFO |testMigration[failMigrations:false]| - [Node] Thread-59396 - [127.0.0.1]:5702 [dev] [5.1.5-SNAPSHOT] Hazelcast Shutdown is completed in 4 ms.
09:33:23,915  INFO |testMigration[failMigrations:false]| - [LifecycleService] Thread-59396 - [127.0.0.1]:5702 [dev] [5.1.5-SNAPSHOT] [127.0.0.1]:5702 is SHUTDOWN
09:33:23,915  INFO |testMigration[failMigrations:false]| - [LifecycleService] Thread-59396 - [127.0.0.1]:5701 [dev] [5.1.5-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
09:33:23,915  INFO |testMigration[failMigrations:false]| - [Node] Thread-59396 - [127.0.0.1]:5701 [dev] [5.1.5-SNAPSHOT] Node is already shutting down... Waiting for shutdown process to complete...
09:33:23,915  INFO |testMigration[failMigrations:false]| - [LifecycleService] Thread-59396 - [127.0.0.1]:5701 [dev] [5.1.5-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
BuildInfo right after testMigration[failMigrations:false](com.hazelcast.wan.impl.WanPublisherMigrationTest): BuildInfo{version='5.1.5-SNAPSHOT', build='20221009', buildNumber=20221009, revision=9299b3e, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'testMigration[failMigrations:false](com.hazelcast.wan.impl.WanPublisherMigrationTest):'
09:33:20, accumulated pauses: 1760 ms, max pause: 1717 ms, pauses over 1000 ms: 1
```

</details>

**Comment by kwart** [comment]
Failed on `master` too:
https://jenkins.hazelcast.com/job/Hazelcast-pr-builder/13866/
