### ISSUE TITLE
com.hazelcast.internal.nio.ascii.TextProtocolsConfigTest

### ISSUE THREAD

**Issue by Patras3** [hazelcast/hazelcast#22477]
_master_ (commit eef85cf6c332fe4f63455b8f06f51138f820b762)
Failed on RedHatJDK11: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-RedHatJDK11/53/testReport/com.hazelcast.internal.nio.ascii/TextProtocolsConfigTest/

Below tests failed:
* `testRestApiCallEnabledGroupsEnabled`
* `testEnabledRestApiCallWithGroupDefaults`

<details><summary>Stacktrace for testRestApiCallEnabledGroupsEnabled as an example (issue seems be the same):</summary>

```
java.lang.AssertionError: 
TestUrl [restEndpointGroup=CLUSTER_READ, method=GET, requestUri=/hazelcast/rest/management/cluster/version, expectedSubstring=5.2]
Expected: a string containing "5.2"
     but: was "HTTP/1.1 200 OK
Content-Type: application/json
Content-Length: 36

{"status":"success","version":"5.3"}"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:964)
	at com.hazelcast.internal.nio.ascii.AbstractTextProtocolsTestBase$1.run(AbstractTextProtocolsTestBase.java:51)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1236)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1253)
	at com.hazelcast.internal.nio.ascii.RestApiConfigTestBase.assertTextProtocolResponse(RestApiConfigTestBase.java:135)
	at com.hazelcast.internal.nio.ascii.TextProtocolsConfigTest.testRestApiCallEnabledGroupsEnabled(TextProtocolsConfigTest.java:122)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
</details>

Similar issue we had for previous version:  https://github.com/hazelcast/hazelcast/issues/19593

**Comment by ldziedziul** [comment]
Probably fixed with https://github.com/hazelcast/hazelcast/pull/22461. Could you re-check?

**Comment by olukas** [comment]
Seems to be fixed, closing. We will reopen it if it fails again.
