### ISSUE TITLE
com.hazelcast.client.ClientReconnectTest.testCallbackAfterServerShutdown [API-1653]

### ISSUE THREAD

**Issue by Patras3** [hazelcast/hazelcast#22516]
_5.2.z_ (commit ecf1b1a7c4572a759b5b4d0f277b646e2a9ccfab)
Failed on CorrettoJDK8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-CorrettoJDK8/55/testReport/junit/com.hazelcast.client/ClientReconnectTest/testCallbackAfterServerShutdown/
<details><summary>Stacktrace:</summary>

```
java.lang.NullPointerException
	at com.hazelcast.client.test.ClientTestSupport.lambda$makeSureDisconnectedFromServer$0(ClientTestSupport.java:93)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1236)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1338)
	at com.hazelcast.client.test.ClientTestSupport.makeSureDisconnectedFromServer(ClientTestSupport.java:92)
	at com.hazelcast.client.ClientReconnectTest.testCallbackAfterServerShutdown(ClientReconnectTest.java:147)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)

```
</details>
<details><summary>Standard output:</summary>

```
Finished Running Test: testExceptionAfterClientShutdown in 2.687 seconds.
04:47:00,135  INFO |testClientReconnectOnClusterDown| - [MetricsConfigHelper] testClientReconnectOnClusterDown - [LOCAL] [dev] [5.2.1-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
04:47:00,136  INFO |testCallbackAfterServerShutdown| - [LifecycleService] Thread-32618 - [127.0.0.1]:5701 [dev] [5.2.1-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
04:47:00,136  INFO |testCallbackAfterServerShutdown| - [Node] Thread-32618 - [127.0.0.1]:5701 [dev] [5.2.1-SNAPSHOT] Node is already shutting down... Waiting for shutdown process to complete...
04:47:00,136  INFO |testCallbackAfterServerShutdown| - [LifecycleService] Thread-32618 - [127.0.0.1]:5701 [dev] [5.2.1-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
BuildInfo right after testCallbackAfterServerShutdown(com.hazelcast.client.ClientReconnectTest): BuildInfo{version='5.2.1-SNAPSHOT', build='20221015', buildNumber=20221015, revision=ecf1b1a, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'testCallbackAfterServerShutdown(com.hazelcast.client.ClientReconnectTest):'
04:46:55, accumulated pauses: 2535 ms, max pause: 2287 ms, pauses over 1000 ms: 1
04:47:00, accumulated pauses: 0 ms, max pause: 0 ms, pauses over 1000 ms: 0

04:47:00,137  INFO |testClientReconnectOnClusterDown| - [logo] testClientReconnectOnClusterDown - [127.0.0.1]:5702 [dev] [5.2.1-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
04:47:00,137  INFO |testClientReconnectOnClusterDown| - [system] testClientReconnectOnClusterDown - [127.0.0.1]:5702 [dev] [5.2.1-SNAPSHOT] Copyright (c) 2008-2022, Hazelcast, Inc. All Rights Reserved.
04:47:00,137  INFO |testClientReconnectOnClusterDown| - [system] testClientReconnectOnClusterDown - [127.0.0.1]:5702 [dev] [5.2.1-SNAPSHOT] Hazelcast Platform 5.2.1-SNAPSHOT (20221015 - ecf1b1a) starting at [127.0.0.1]:5702
04:47:00,137  INFO |testClientReconnectOnClusterDown| - [system] testClientReconnectOnClusterDown - [127.0.0.1]:5702 [dev] [5.2.1-SNAPSHOT] Cluster name: dev
04:47:00,137  INFO |testClientReconnectOnClusterDown| - [system] testClientReconnectOnClusterDown - [127.0.0.1]:5702 [dev] [5.2.1-SNAPSHOT] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed. For more information, see the documentation for Integrity Checker.
04:47:00,137  INFO |testClientReconnectOnClusterDown| - [system] testClientReconnectOnClusterDown - [127.0.0.1]:5702 [dev] [5.2.1-SNAPSHOT] Jet is enabled

No metrics recorded during the test
04:47:00,146  INFO |testClientReconnectOnClusterDown| - [MetricsConfigHelper] testClientReconnectOnClusterDown - [127.0.0.1]:5702 [dev] [5.2.1-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled

```
</details>

**Comment by olukas** [comment]
Failed on release branch _5.2.1_ with OracleJDK8: https://jenkins.hazelcast.com/view/Release/job/Hazelcast-5.releaseBranch-OracleJDK8/22/testReport/com.hazelcast.client/ClientReconnectTest/testCallbackAfterServerShutdown/

**Comment by olukas** [comment]
@krzysztofslusarski could you please back-port the fix to `5.2.z` branch. Thanks.

**Comment by krzysztofslusarski** [comment]
It is not fixed in master. I send a PR, but @mdumandag pointed that it is not a valid solution so I closed it.

**Comment by olukas** [comment]
I see, ok. Thanks for the info. I'm moving it back to `5.3 Backlog`.

**Comment by sumnerib** [comment]
Failed again on _5.2.z_ with Openj9-11: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-Openj9-11/60/testReport/junit/com.hazelcast.client/ClientReconnectTest/testCallbackAfterServerShutdown/
