### ISSUE TITLE
com.hazelcast.kubernetes.KubernetesClientTest + HazelcastKubernetesDiscoveryStrategyFactoryTest.createDiscoveryStrategy

### ISSUE THREAD

**Issue by Patras3** [hazelcast/hazelcast#22511]
_master_ (commit 285517dcd7b6c95a2d751f97140a1f046230adca)
27 test cases failed on MacOS due to the same reason.
Attaching one as example:
https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-MacOS-ZuluJDK8/123/testReport/com.hazelcast.kubernetes/HazelcastKubernetesDiscoveryStrategyFactoryTest/createDiscoveryStrategy/

<details><summary>Stacktrace:</summary>

```
java.lang.NullPointerException
	at com.hazelcast.kubernetes.KubernetesClient.extractStsName(KubernetesClient.java:268)
	at com.hazelcast.kubernetes.KubernetesClient.<init>(KubernetesClient.java:99)
	at com.hazelcast.kubernetes.HazelcastKubernetesDiscoveryStrategy.buildKubernetesClient(HazelcastKubernetesDiscoveryStrategy.java:67)
	at com.hazelcast.kubernetes.HazelcastKubernetesDiscoveryStrategy.<init>(HazelcastKubernetesDiscoveryStrategy.java:47)
	at com.hazelcast.kubernetes.HazelcastKubernetesDiscoveryStrategyFactory.newDiscoveryStrategy(HazelcastKubernetesDiscoveryStrategyFactory.java:88)
	at com.hazelcast.kubernetes.HazelcastKubernetesDiscoveryStrategyFactoryTest.createDiscoveryStrategy(HazelcastKubernetesDiscoveryStrategyFactoryTest.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)

```
</details>
<details><summary>Standard output:</summary>

```
Finished Running Test: autoDetection in 0.001 seconds.
Finished Running Test: checkDiscoveryStrategyType in 0.001 seconds.

```
</details>

The same issue was reproduced by me on Windows with temurin-1.8.0_345

**Comment by Patras3** [comment]
The same issue (27 failed cases) occurred also on Windows - MicrosoftJDK17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Windows-MicrosoftJDK17/31/testReport/

**Comment by ldziedziul** [comment]
I think I've addressed that here: https://github.com/hazelcast/hazelcast/pull/22512 (waiting for review and merge)

**Comment by Patras3** [comment]
Failed again on _master_ with Windows - OracleJDK8 as https://github.com/hazelcast/hazelcast/pull/22512 was not merged yet: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Windows-OracleJDK8/417/testReport/com.hazelcast.kubernetes/HazelcastKubernetesDiscoveryStrategyFactoryTest/createDiscoveryStrategy/

**Comment by ldziedziul** [comment]
It was merged an hour ago
