### ISSUE TITLE
Unable to store records with GenericMapStore when mapping a subset of columns

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hazelcast#22527]
**Describe the bug**
When using the `GenericMapStore` with a `columns` setting that only includes a subset of the table columns, `HazelcastSerializationException` are thrown when trying to put/insert a record. For example:

```
com.hazelcast.nio.serialization.HazelcastSerializationException: Invalid field name: 'other for Schema { className = people_o_d300f3a4_1260_42ad_a921_3a0ef3c41e18, numberOfComplexFields = 1, primitivesLength = 4, map = {name=FieldDescriptor{name='name', kind=STRING, index=0, offset=-1, bitOffset=-1}, id=FieldDescriptor{name='id', kind=INT32, index=-1, offset=0, bitOffset=-1}}}

	at com.hazelcast.internal.serialization.impl.compact.DeserializedGenericRecord.check(DeserializedGenericRecord.java:547)
	at com.hazelcast.internal.serialization.impl.compact.DeserializedGenericRecord.get(DeserializedGenericRecord.java:540)
	at com.hazelcast.internal.serialization.impl.compact.DeserializedGenericRecord.getString(DeserializedGenericRecord.java:177)
	at com.hazelcast.mapstore.GenericMapStore.store(GenericMapStore.java:433)
...
```
Default value(s) for missing columns have been defined.

**Expected behavior**
Records should be inserted successfully when defaults are defined for the missing columns.

**To Reproduce**

1. Start a HZ member w/ map config(s) like below example
2. Try to put a record into the map like `map.put(key, GenericRecordBuilder.compact(typeName).setX("fieldName", fieldVal).build())`
3. Operation fails with exception like above

```
    <map name="people">
        <map-store enabled="true">
            <class-name>com.hazelcast.mapstore.GenericMapStore</class-name> 
            <properties>
                <property name="external-data-store-ref">postgres</property> 
                <property name="columns">id,name</property>
            </properties>
        </map-store>
    </map>
```

**Additional context**

I think this unit test captures the behavior. It can be added to `com.hazelcast.mapstore.GenericMapStoreTest`

```
    @Test
    public void givenColumnPropSubset_whenStore_thenTableContainsRow() throws SQLException {
        createTable(mapName, "id INT PRIMARY KEY", "name VARCHAR(100)", "other VARCHAR(100) DEFAULT 'def'");
        try (Connection conn = DriverManager.getConnection(dbConnectionUrl);
             Statement stmt = conn.createStatement()
        ) {
            stmt.execute("INSERT INTO " + mapName + " (id, name) VALUES(0, 'name-0')");
        }

        Properties properties = new Properties();
        properties.setProperty(EXTERNAL_REF_ID_PROPERTY, TEST_DATABASE_REF);

        properties.setProperty("columns", "id,name");
        GenericMapStore<Integer> mapStore = createMapStore(properties, hz);

        GenericRecord person = GenericRecordBuilder.compact(mapName)
                .setInt32("id", 1)
                .setString("name", "name-1")
                .build();
        mapStore.store(1, person);


        assertJdbcRowsAnyOrder(mapName,
                new Row(0, "name-0"),
                new Row(1, "name-1")
        );
    }
```

Side note: listing column names like `column1, column2, column3` causes `Caused by: com.hazelcast.core.HazelcastException: Column ' column2' not found`. A UX improvement might be to allow spaces between the listed columns for the `columns` property.

**Comment by sumnerib** [comment]
Please un-ignore the following unit test when fixing this issue: https://github.com/hazelcast/hazelcast/blob/1103c1eb49cf67f3db610fdec12450f1efde86e1/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreTest.java#L597
