### ISSUE TITLE
NPE when using map.executeOnEntries() w/ GenericMapStore [HZ-1640]

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hazelcast#22570]
**Describe the bug**
Given an `IMap` with a `GenericMapStore` configured, when calling `map.executeOnEntries()`, a `NullPointerException` is thrown on the member side:

```
Oct 21, 2022 1:06:27 PM com.hazelcast.map.impl.operation.PartitionWideEntryOperation
SEVERE: [10.0.0.29]:5701 [dev] [5.3.0-SNAPSHOT] null
java.lang.NullPointerException
        at com.hazelcast.map.impl.operation.steps.PartitionWideOpSteps$1.processInternal(PartitionWideOpSteps.java:142)
        at com.hazelcast.map.impl.operation.steps.PartitionWideOpSteps$1.lambda$runWithPartitionScan$1(PartitionWideOpSteps.java:117)
        at com.hazelcast.map.impl.recordstore.DefaultRecordStore.forEach(DefaultRecordStore.java:318)
        at com.hazelcast.map.impl.recordstore.DefaultRecordStore.forEach(DefaultRecordStore.java:301)
        at com.hazelcast.map.impl.operation.steps.PartitionWideOpSteps$1.runWithPartitionScan(PartitionWideOpSteps.java:116)
        at com.hazelcast.map.impl.operation.steps.PartitionWideOpSteps$1.runStep(PartitionWideOpSteps.java:52)
        at com.hazelcast.map.impl.operation.steps.PartitionWideOpSteps$1.runStep(PartitionWideOpSteps.java:44)
        at com.hazelcast.map.impl.operation.steps.engine.StepSupplier.runStepWithState(StepSupplier.java:152)
        at com.hazelcast.map.impl.operation.steps.engine.StepSupplier.access$100(StepSupplier.java:40)
        at com.hazelcast.map.impl.operation.steps.engine.StepSupplier$2.run(StepSupplier.java:117)
        at com.hazelcast.map.impl.operation.steps.engine.StepRunner.runDirect(StepRunner.java:196)
        at com.hazelcast.map.impl.operation.steps.engine.StepRunner.run0(StepRunner.java:153)
        at com.hazelcast.map.impl.operation.steps.engine.StepRunner.run(StepRunner.java:118)
        at com.hazelcast.map.impl.operation.steps.engine.StepRunner.start(StepRunner.java:93)
        at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:307)
```

**Expected behavior**
The `EntryProcessor` works based on it's implementation, and interactions with the `MapStore` work as described [here](https://docs.hazelcast.com/hazelcast/5.2-snapshot/mapstore/mapstore-triggers).

**To Reproduce**

Paste and run the following test method in `com.hazelcast.mapstore.GenericMapStoreIntegrationTest`:

```
    @Test
    public void testExecuteOnEntriesNPE() {
        HazelcastInstance client = client();
        IMap<Integer, Person> map = client.getMap(tableName);
        map.loadAll(false);

        map.executeOnEntries(i -> i);

        assertJdbcRowsAnyOrder(tableName,
                new Row(0, "name-0")
        );
    }
```

**Additional context**

Also tested with other EP implementations besides the above example (do more than just return the entry), and the NPE still occurs.

**Comment by sumnerib** [comment]
I also confirmed that this affects maps with custom `MapStore` implementations (i.e. not just `GenericMapStore`). Setting `offload` to `false` is a workaround in this case.
