### ISSUE TITLE
NullPointerException on SQL SELECT from an empty Kafka topic (5.1.z)

### ISSUE THREAD

**Issue by kwart** [hazelcast/hazelcast#22576]
SQL select on empty Kafka topic fails on `5.1.4` (also `5.1.3`). It seems to be OK on `5.2.1-SNAPSHOT`.

E.g.

```sql
CREATE MAPPING trades (
    id BIGINT,
    ticker VARCHAR,
    price DECIMAL,
    amount BIGINT)
TYPE Kafka
OPTIONS (
    'valueFormat' = 'json-flat',
    'bootstrap.servers' = 'broker.kerberos.example:9092',
    'sasl.mechanism' = 'GSSAPI',
    'security.protocol' = 'SASL_PLAINTEXT',
    'sasl.kerberos.service.name' = 'kafka',
    'sasl.jaas.config' = 'com.sun.security.auth.module.Krb5LoginModule required useTicketCache=true useKeyTab=true storeKey=true keyTab="/mnt/jduke.keytab" principal="jduke@KERBEROS.EXAMPLE";'
);

SELECT ticker, ROUND(price * 100) AS price_cents, amount
  FROM trades
  WHERE price * amount > 100;
```

executed within `hz-cli sql` results in:

```
+--------------------+-------------------------+--------------------+
|ticker              |              price_cents|              amount|
+--------------------+-------------------------+--------------------+
The Jet SQL job failed: Execution on a member failed: com.hazelcast.jet.JetException: Exception in ProcessorTasklet{08d4-1d58-d180-0001/Kafka[public.trades]#2}: java.lang.NullPointerException
```

Member log contains:
```
2022-10-22 11:35:26,466 [ INFO] [hz.priceless_chatelet.jet.blocking.thread-2] [c.h.j.i.e.TaskletExecutionService]: [172.20.0.7]:5701 [dev] [5.1.3] Exception in ProcessorTasklet{08d4-1d58-d180-0001/Kafka[public.trades]#2}
java.lang.NullPointerException: null
	at com.hazelcast.jet.kafka.impl.StreamKafkaP.assignPartitions(StreamKafkaP.java:130) ~[hazelcast-jet-kafka-5.1.3.jar:?]
	at com.hazelcast.jet.kafka.impl.StreamKafkaP.complete(StreamKafkaP.java:186) ~[hazelcast-jet-kafka-5.1.3.jar:?]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.complete(ProcessorTasklet.java:491) ~[hazelcast-5.1.3.jar:5.1.3]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:385) ~[hazelcast-5.1.3.jar:5.1.3]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:255) ~[hazelcast-5.1.3.jar:5.1.3]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$BlockingWorker.run(TaskletExecutionService.java:315) [hazelcast-5.1.3.jar:5.1.3]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
2022-10-22 11:35:26,488 [ INFO] [hz.priceless_chatelet.jet.blocking.thread-0] [o.a.k.c.Metadata]: Cluster ID: 8vHuI83vSSCF51VsDsFFpw
```

**To Reproduce**

Docker compose to reproduce:
[test-app-kafka-with-kerberos.zip](https://github.com/hazelcast/hazelcast/files/9844237/test-app-kafka-with-kerberos.zip)

use `docker compose up`

once containers are started use `docker exec -it hazelcast bin/hz-cli sql` and run the 2 SQL commands listed earlier.

**Comment by TomaszGaweda** [comment]
On master it's fixed by 3cb8ce1fc3bb848aced6c87a30bf7b31aec16cf7
