### ISSUE TITLE
"hz-k8s-sts-monitor" REST exception in non-persistent DNS Kubernetes

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast#22577]
**Describe the bug**
Exception
```
Exception in thread "hz-k8s-sts-monitor" com.hazelcast.spi.exception.RestClientException: Failure in executing REST call
	at com.hazelcast.spi.utils.RestClient.call(RestClient.java:167)
	at com.hazelcast.spi.utils.RestClient.lambda$callWithRetries$0(RestClient.java:134)
	at com.hazelcast.spi.utils.RetryUtils.retry(RetryUtils.java:65)
	at com.hazelcast.spi.utils.RetryUtils.retry(RetryUtils.java:51)
	at com.hazelcast.spi.utils.RestClient.callWithRetries(RestClient.java:134)
	at com.hazelcast.spi.utils.RestClient.get(RestClient.java:126)
	at com.hazelcast.kubernetes.KubernetesClient.lambda$callGet$0(KubernetesClient.java:545)
	at com.hazelcast.spi.utils.RetryUtils.retry(RetryUtils.java:65)
	at com.hazelcast.kubernetes.KubernetesClient.callGet(KubernetesClient.java:541)
	at com.hazelcast.kubernetes.KubernetesClient.access$200(KubernetesClient.java:53)
	at com.hazelcast.kubernetes.KubernetesClient$StsMonitor.run(KubernetesClient.java:711)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:371)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:314)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:309)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1357)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1232)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1175)
	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:458)
	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:201)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1500)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1415)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:450)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:421)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:580)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:183)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:529)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:308)
	at com.hazelcast.spi.utils.RestClient.checkResponseCode(RestClient.java:218)
	at com.hazelcast.spi.utils.RestClient.call(RestClient.java:164)
	... 11 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439)
	at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306)
	at java.base/sun.security.validator.Validator.validate(Validator.java:264)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:231)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1341)
	... 30 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)
	... 35 more
```

**Expected behavior**
No exception

**To Reproduce**
Using this YAML - DNS discovery, no persistence

Kubernetes is enabled by Java and `service-name` set.

```
hazelcast:
  # Replaced by Docker
  cluster-name: '${CLUSTER_NAME}'
  # Replaced by Maven
  license-key: 'redacted'

  properties:
    # Graceful shutdown is helpful for Kubernetes scale-down.
    hazelcast.member.naming.moby.enabled: true
    hazelcast.shutdownhook.policy: GRACEFUL

  # Assuming Kubernetes, but override from Java code if we detect otherwise
  network:
    join:
      auto-detection:
        enabled: false
      multicast:
        enabled: false
      kubernetes:
        enabled: false
        service-dns: '???.default.svc.cluster.local'
    rest-api:
      enabled: true
      endpoint-groups:
        HEALTH_CHECK:
          enabled: true
  # Resource upload for ML
  jet:
    enabled: true
    resource-upload-enabled: true
```

**Additional context**
Tested using a local build of 5.2.0-SNAPSHOT, may not exactly match the official branch -- so *could* be user error.

See https://github.com/hazelcast/hazelcast/issues/22538

**Comment by neilstevenson** [comment]
I do have the amended `KubernetesClient.java` in my branch from https://github.com/hazelcast/hazelcast/pull/22539/files

**Comment by kwart** [comment]
This doesn't seem like a bug. It only says the client (Hazelcast) doesn't trust the kuberenetes master certificate when accessing the REST endpoint over the HTTPs.

You should either configure the `caCertificates` or use a plain HTTP master URL.

**Comment by vbekiaris** [comment]
It is unexpected that we start the kubernetes monitor thread by default while persistence is not enabled. @neilstevenson can you try setting cluster property `hazelcast.persistence.auto.cluster.state` to `false` and see if this fixes your issue?

**Comment by neilstevenson** [comment]
The workaround works 👍

**Comment by neilstevenson** [comment]
User error! Persistence is enabled. Sorry! The drawback of having config in `yaml` which is then mutated by Java.
https://github.com/hazelcast/hazelcast-platform-demos/blob/5.2-stage/retail/clickstream/hazelcast/src/main/java/com/hazelcast/platform/demos/retail/clickstream/ApplicationConfig.java#L232

**Comment by vbekiaris** [comment]
thanks for the heads up!
