### ISSUE TITLE
Migration failed on 5.2.0

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast#22609]
**Describe the bug**
This in the logs

```
17:34:18.849 [hz.eager_keller.async.thread-1] WARN  com.hazelcast.internal.partition.impl.MigrationManager - [10.56.1.5]:5701 [blue] [5.2.0] Migration failed: MigrationInfo{uuid=a95a7f3a-03bd-4bb2-ab11-17676a6922a9, partitionId=5, source=[10.56.4.7]:5701 - a84223e2-3d78-4431-b000-33b3c6ec7558, sourceCurrentReplicaIndex=0, sourceNewReplicaIndex=2, destination=[10.56.3.7]:5701 - 17f62d03-340d-474f-95b7-01dd259fa257, destinationCurrentReplicaIndex=-1, destinationNewReplicaIndex=0, master=[10.56.1.5]:5701, initialPartitionVersion=3, partitionVersionIncrement=2, status=ACTIVE}
17:34:18.850 [hz.eager_keller.async.thread-2] WARN  com.hazelcast.internal.partition.impl.MigrationManager - [10.56.1.5]:5701 [blue] [5.2.0] Migration failed: MigrationInfo{uuid=5c22d1a6-4512-4523-b7e8-7ceb31cc85c0, partitionId=7, source=[10.56.4.7]:5701 - a84223e2-3d78-4431-b000-33b3c6ec7558, sourceCurrentReplicaIndex=0, sourceNewReplicaIndex=2, destination=[10.56.3.7]:5701 - 17f62d03-340d-474f-95b7-01dd259fa257, destinationCurrentReplicaIndex=-1, destinationNewReplicaIndex=0, master=[10.56.1.5]:5701, initialPartitionVersion=3, partitionVersionIncrement=2, status=ACTIVE}
17:34:18.851 [hz.eager_keller.async.thread-1] WARN  com.hazelcast.internal.partition.impl.MigrationManager - [10.56.1.5]:5701 [blue] [5.2.0] Migration failed: MigrationInfo{uuid=63b2f9fa-8d79-457e-aafc-7002d356772b, partitionId=9, source=[10.56.4.7]:5701 - a84223e2-3d78-4431-b000-33b3c6ec7558, sourceCurrentReplicaIndex=0, sourceNewReplicaIndex=2, destination=[10.56.3.7]:5701 - 17f62d03-340d-474f-95b7-01dd259fa257, destinationCurrentReplicaIndex=-1, destinationNewReplicaIndex=0, master=[10.56.1.5]:5701, initialPartitionVersion=3, partitionVersionIncrement=2, status=ACTIVE}
```

**Expected behavior**
No failed migrations

**To Reproduce**
Not sure

**Additional context**
5 node cluster on Kubernetes

**Comment by neilstevenson** [comment]
Retried, same error and again 264 remaining
```
18:03:03.740 [hz.infallible_bartik.cached.thread-3] INFO  com.hazelcast.internal.partition.InternalPartitionService - [10.56.5.8]:5701 [blue] [5.2.0] Remaining migration tasks: 264. (repartitionTime=Tue Oct 25 18:01:45 UTC 2022, plannedMigrations=271, completedMigrations=0, remainingMigrations=271, totalCompletedMigrations=271)```

Retried again,  also 264
```
18:07:17.907 [hz.trusting_swirles.cached.thread-2] INFO  com.hazelcast.internal.partition.InternalPartitionService - [10.56.1.8]:5701 [blue] [5.2.0] Remaining migration tasks: 264. (repartitionTime=Tue Oct 25 18:06:15 UTC 2022, plannedMigrations=271, completedMigrations=0, remainingMigrations=271, totalCompletedMigrations=271)
```

**Comment by neilstevenson** [comment]
If I change my config to *not* have
```
hazelcast.persistence.auto.cluster.state: false
```
and *not have*
```
        config.getPersistenceConfig()
        .setEnabled(true)
        .setBaseDir(new File(MyConstants.PERSISTENCE_BASEDIR));
```
the problem goes away... on the first test

**Comment by mtyazici** [comment]
I faced the same problem in 5.1.4 in Kubernetes with 3 members.
```
[10.76.0.31]:5701 [dev] [5.1.4] Failure while executing MigrationInfo{uuid=4213defb-0120-4fcf-b375-3ddba352a8a4, partitionId=1, source=[10.76.0.31]:5701 - c823a95b-35be-4494-a35e-a18b6e00ed2c, sourceCurrentReplicaIndex=0, sourceNewReplicaIndex=2, destination=[10.76.0.34]:5701 - ad124efe-c1d1-43ec-a67f-600a80979069, destinationCurrentReplicaIndex=-1, destinationNewReplicaIndex=0, master=[10.76.0.31]:5701, initialPartitionVersion=2, partitionVersionIncrement=2, status=ACTIVE} com.hazelcast.internal.partition.PartitionStateVersionMismatchException: Local partition stamp is not equal to master's stamp! Local: 0, Master: 2
	at com.hazelcast.internal.partition.operation.BaseMigrationOperation.verifyPartitionVersion(BaseMigrationOperation.java:143) ~[hazelcast-enterprise-5.1.4.jar:5.1.4]
	at com.hazelcast.internal.partition.operation.BaseMigrationOperation.beforeRun(BaseMigrationOperation.java:96) ~[hazelcast-enterprise-5.1.4.jar:5.1.4]
	at com.hazelcast.internal.partition.operation.MigrationOperation.beforeRun(MigrationOperation.java:57) ~[hazelcast-enterprise-5.1.4.jar:5.1.4]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:247) ~[hazelcast-enterprise-5.1.4.jar:5.1.4]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:471) ~[hazelcast-enterprise-5.1.4.jar:5.1.4]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:197) ~[hazelcast-enterprise-5.1.4.jar:5.1.4]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:137) ~[hazelcast-enterprise-5.1.4.jar:5.1.4]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123) ~[hazelcast-enterprise-5.1.4.jar:5.1.4]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) [hazelcast-enterprise-5.1.4.jar:5.1.4]
[10.76.0.31]:5701 [dev] [5.1.4] Failure while executing MigrationInfo{uuid=42d4a3b8-5912-451d-97b3-3e4abb5cff96, partitionId=0, source=[10.76.0.31]:5701 - c823a95b-35be-4494-a35e-a18b6e00ed2c, sourceCurrentReplicaIndex=0, sourceNewReplicaIndex=2, destination=[10.76.0.34]:5701 - ad124efe-c1d1-43ec-a67f-600a80979069, destinationCurrentReplicaIndex=-1, destinationNewReplicaIndex=0, master=[10.76.0.31]:5701, initialPartitionVersion=2, partitionVersionIncrement=2, status=ACTIVE} com.hazelcast.internal.partition.PartitionStateVersionMismatchException: Local partition stamp is not equal to master's stamp! Local: 0, Master: 2
	at com.hazelcast.internal.partition.operation.BaseMigrationOperation.verifyPartitionVersion(BaseMigrationOperation.java:143) ~[hazelcast-enterprise-5.1.4.jar:5.1.4]
	at com.hazelcast.internal.partition.operation.BaseMigrationOperation.beforeRun(BaseMigrationOperation.java:96) ~[hazelcast-enterprise-5.1.4.jar:5.1.4]
	at com.hazelcast.internal.partition.operation.MigrationOperation.beforeRun(MigrationOperation.java:57) ~[hazelcast-enterprise-5.1.4.jar:5.1.4]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:247) ~[hazelcast-enterprise-5.1.4.jar:5.1.4]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:471) ~[hazelcast-enterprise-5.1.4.jar:5.1.4]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:197) ~[hazelcast-enterprise-5.1.4.jar:5.1.4]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:137) ~[hazelcast-enterprise-5.1.4.jar:5.1.4]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123) ~[hazelcast-enterprise-5.1.4.jar:5.1.4]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) [hazelcast-enterprise-5.1.4.jar:5.1.4]
[10.76.0.31]:5701 [dev] [5.1.4] Migration failed: MigrationInfo{uuid=4213defb-0120-4fcf-b375-3ddba352a8a4, partitionId=1, source=[10.76.0.31]:5701 - c823a95b-35be-4494-a35e-a18b6e00ed2c, sourceCurrentReplicaIndex=0, sourceNewReplicaIndex=2, destination=[10.76.0.34]:5701 - ad124efe-c1d1-43ec-a67f-600a80979069, destinationCurrentReplicaIndex=-1, destinationNewReplicaIndex=0, master=[10.76.0.31]:5701, initialPartitionVersion=2, partitionVersionIncrement=2, status=ACTIVE} 
[10.76.0.31]:5701 [dev] [5.1.4] Migration failed: MigrationInfo{uuid=42d4a3b8-5912-451d-97b3-3e4abb5cff96, partitionId=0, source=[10.76.0.31]:5701 - c823a95b-35be-4494-a35e-a18b6e00ed2c, sourceCurrentReplicaIndex=0, sourceNewReplicaIndex=2, destination=[10.76.0.34]:5701 - ad124efe-c1d1-43ec-a67f-600a80979069, destinationCurrentReplicaIndex=-1, destinationNewReplicaIndex=0, master=[10.76.0.31]:5701, initialPartitionVersion=2, partitionVersionIncrement=2, status=ACTIVE} 
```
