### ISSUE TITLE
com.hazelcast.client.stress.MapStableReadStressTest

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#22626]
_master_ (commit f92b5f3a3455d7e5e71053850831a710a6f0f462)

Failed on ZingJDK8: 
- https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZingJDK8-nightly/3/testReport/com.hazelcast.client.stress/MapStableReadStressTest/testFixedCluster/
- https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZingJDK8-nightly/3/testReport/com.hazelcast.client.stress/MapStableReadStressTest/testChangingCluster/

Tests `com.hazelcast.client.stress.MapStableReadStressTest.testFixedCluster` and `com.hazelcast.client.stress.MapStableReadStressTest.testChangingCluster` failed with the same exception.

<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: com.hazelcast.client.stress.MapStableReadStressTest$StressThread1 encountered an error expected null, but was:<java.lang.NullPointerException>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotNull(Assert.java:756)
	at org.junit.Assert.assertNull(Assert.java:738)
	at com.hazelcast.client.stress.StressTestSupport$TestThread.assertNoError(StressTestSupport.java:187)
	at com.hazelcast.client.stress.StressTestSupport.assertNoErrors(StressTestSupport.java:138)
	at com.hazelcast.client.stress.StressTestSupport.joinAll(StressTestSupport.java:159)
	at com.hazelcast.client.stress.MapStableReadStressTest.test(MapStableReadStressTest.java:91)
	at com.hazelcast.client.stress.MapStableReadStressTest.testFixedCluster(MapStableReadStressTest.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:807)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-ZingJDK8-nightly/3/Hazelcast-master-ZingJDK8-nightly-3.zip

**Comment by k-jamroz** [comment]
According to logs NPE occurs in MapStableReadStressTest.java:119 which is:
```java
int value = map.get(key);
```

`map` never should be null...

**Comment by k-jamroz** [comment]
But the key may be not present in the map. In such case, map.get returns null and unboxing fails with NPE. This may be some kind of race condition with replication of initial data (they are not changed afterwards).

**Comment by k-jamroz** [comment]
The test does not work in CP mode so, if I am correct, does not guarantee that all nodes will see all inserted data immediately.
