### ISSUE TITLE
com.hazelcast.cp.internal.MetadataRaftGroupTest.when_cpSubsystemReset_then_cpGroupIsCreatedWithDifferentGroupId [HZ-3111]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#22647]
_master_ (commit 470f95b02543901406fa5e3b232545b5faf8b7c8)

Failed on MacOS: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-MacOS-ZuluJDK8/127/testReport/com.hazelcast.cp.internal/MetadataRaftGroupTest/when_cpSubsystemReset_then_cpGroupIsCreatedWithDifferentGroupId/

<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at com.hazelcast.cp.internal.HazelcastRaftTestSupport.lambda$waitUntilCPDiscoveryCompleted$1(HazelcastRaftTestSupport.java:93)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1236)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1338)
	at com.hazelcast.cp.internal.HazelcastRaftTestSupport.waitUntilCPDiscoveryCompleted(HazelcastRaftTestSupport.java:91)
	at com.hazelcast.cp.internal.MetadataRaftGroupTest.when_cpSubsystemReset_then_cpGroupIsCreatedWithDifferentGroupId(MetadataRaftGroupTest.java:705)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-MacOS-ZuluJDK8/127/

**Comment by arodionov** [comment]
Probably, has the same cause  https://github.com/hazelcast/hazelcast/issues/22333

**Comment by Patras3** [comment]
Failed again on _5.3.z_ with oracle-11: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-sonar/212/testReport/junit/com.hazelcast.cp.internal/MetadataRaftGroupTest/when_cpSubsystemReset_then_cpGroupIsCreatedWithDifferentGroupId/

**Comment by gbarnett-hz** [comment]
Spent the afternoon trying to reproduce the failure under Oracle 11 + 5.3.z with no luck ;-( Test LGTM - didn't see anything that seemed obvious as to how we'd see same group ID for recreated CP group after CP reset.
