### ISSUE TITLE
All SQL queries fail when external store used in JDBC mapping is disconnected/down [HZ-1686]

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hazelcast#22651]
**Describe the bug**
Given an existing JDBC mapping to a table in an external store (i.e. MySQL), when the cluster members are unable to connect to this external store, all new SQL queries will fail. This includes queries that should be unrelated to the faulty external store such as `SHOW MAPPINGS` and `SELECT * FROM TABLE(generate_series(x, y))`. The same error is returned in all cases:

`Could not determine dialect for externalDataStoreRef: <ref-name>` 

**Expected behavior**
Queries that are unrelated to the faulty external store should not be affected.

**To Reproduce**

1. Create a JDBC mapping to an external table, such as described [here](https://docs.hazelcast.com/hazelcast/5.2/sql/mapping-to-jdbc#creating-a-jdbc-mapping)
2. Confirm HZ is able to access the external store (i.e. `SELECT * FROM external-mapping`)
3. Shutdown the external store (i.e. `docker stop my-mysql-container` if using Docker)
4. Try executing an unrelated query like `SHOW MAPPINGS` or some other mapping that doesn't use this external store

The result will eventually be `Could not determine dialect for externalDataStoreRef: <ref-name>` 

**Additional context**

In some cases, a query that was executed successfully before the external store goes down can also run successfully afterwards. Maybe this is related to the SQL caching mechanism.

A JUnit test demonstrating the behavior is attached: 
[JdbcSqlConnectorStabilityTest.txt](https://github.com/hazelcast/hazelcast/files/9903568/JdbcSqlConnectorStabilityTest.txt)

**Comment by krzysztofslusarski** [comment]
```
Exception in thread "admiring_wilson-query-state-checker" com.hazelcast.core.HazelcastException: Could not determine dialect for externalDataStoreRef: test-database-ref
	at com.hazelcast.jet.sql.impl.connector.jdbc.JdbcSqlConnector.resolveDialect(JdbcSqlConnector.java:271)
	at com.hazelcast.jet.sql.impl.connector.jdbc.JdbcSqlConnector.createTable(JdbcSqlConnector.java:236)
	at com.hazelcast.jet.sql.impl.schema.TableResolverImpl.toTable(TableResolverImpl.java:270)
	at com.hazelcast.jet.sql.impl.schema.TableResolverImpl.getTables(TableResolverImpl.java:246)
	at com.hazelcast.sql.impl.schema.SqlCatalog.<init>(SqlCatalog.java:42)
	at com.hazelcast.sql.impl.plan.cache.PlanCacheChecker.check(PlanCacheChecker.java:56)
	at com.hazelcast.sql.impl.state.QueryStateRegistryUpdater$Worker.checkPlans(QueryStateRegistryUpdater.java:139)
	at com.hazelcast.sql.impl.state.QueryStateRegistryUpdater$Worker.run(QueryStateRegistryUpdater.java:117)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by sumnerib** [comment]
Please un-ignore the following test when fixing this issue: https://github.com/hazelcast/hazelcast/blob/1103c1eb49cf67f3db610fdec12450f1efde86e1/hazelcast-sql/src/test/java/com/hazelcast/jet/sql/impl/connector/jdbc/JdbcSqlConnectorStabilityTest.java#L85
