### ISSUE TITLE
SQL nested querying with `OBJECT` field returns null

### ISSUE THREAD

**Issue by srknzl** [hazelcast/hazelcast#22668]
**Describe the bug**

In nested querying, if a field is added as OBJECT to the deepest type, selects like `a.b.c` that selects the field with the `OBJECT` type returns null when the value is not null. Selecting `a` returns that field as nonnull and correct.

**Expected behavior**
I expect it to return the OBJECT type as nonnull, maybe as GenericRecord or User class I don't know.

**To Reproduce**

I modified CompactNestedFieldsTest to be as follows. Copy the code below to the file and run the test `testNestedCompactQueryReturnsArrayFieldDeserialized`

<details>
  <summary>Click me</summary>
  
```java
/*
 * Copyright 2021 Hazelcast Inc.
 *
 * Licensed under the Hazelcast Community License (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://hazelcast.com/hazelcast-community-license
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.hazelcast.jet.sql.impl.type;

import com.hazelcast.config.Config;
import com.hazelcast.internal.serialization.impl.compact.DeserializedGenericRecord;
import com.hazelcast.jet.sql.SqlTestSupport;
import com.hazelcast.map.IMap;
import com.hazelcast.sql.SqlResult;
import com.hazelcast.sql.SqlRow;
import com.hazelcast.test.HazelcastSerialClassRunner;
import org.junit.BeforeClass;
import org.junit.Test;
import org.junit.runner.RunWith;

import java.util.ArrayList;

import static com.hazelcast.spi.properties.ClusterProperty.SQL_CUSTOM_TYPES_ENABLED;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.junit.Assert.assertEquals;


class Office {
    long id;
    String name;

    public Office(long id, String name) {
        this.id = id;
        this.name = name;
    }
}

class Organization {
    long id;
    String name;
    Office[] offices;

    public Organization(long id, String name, Office[] offices) {
        this.id = id;
        this.name = name;
        this.offices = offices;
    }
}

class OrganizationAndLong {
    long id;
    long l;
    Organization organization;

    public OrganizationAndLong(long id, long l, Organization organization) {
        this.id = id;
        this.l = l;
        this.organization = organization;
    }
}

class UserCompactType {
    long id;
    String name;
    OrganizationAndLong organizationAndLong;

    public UserCompactType(long id, String name, OrganizationAndLong organizationAndLong) {
        this.id = id;
        this.name = name;
        this.organizationAndLong = organizationAndLong;
    }
}

@RunWith(HazelcastSerialClassRunner.class)
public class CompactNestedFieldsTest extends SqlTestSupport {

    @BeforeClass
    public static void beforeClass() {
        final Config config = new Config();
        config.getJetConfig().setEnabled(true);
        config.setProperty(SQL_CUSTOM_TYPES_ENABLED.getName(), "true");
        config.getSerializationConfig().getCompactSerializationConfig().addClass(UserCompactType.class);

        initializeWithClient(3, config, null);
    }

    @Test
    public void test_basicQuerying() {
        client().getSql().execute("CREATE TYPE Office ("
                + "id BIGINT, "
                + "name VARCHAR "
                + ") OPTIONS ('format'='compact', 'compactTypeName'='OfficeCompactType')");

        client().getSql().execute("CREATE TYPE Organization ("
                + "id BIGINT, "
                + "name VARCHAR, "
                + "office Office"
                + ") OPTIONS ('format'='compact', 'compactTypeName'='OrganizationCompactType')");

        client().getSql().execute(
                "CREATE MAPPING test ("
                        + "__key BIGINT,"
                        + "id BIGINT, "
                        + "name VARCHAR, "
                        + "organization Organization"
                        + ")"
                        + "TYPE IMap "
                        + "OPTIONS ("
                        + "'keyFormat'='bigint',"
                        + "'valueFormat'='compact',"
                        + "'valueCompactTypeName'='UserCompactType'"
                        + ")");

        client().getSql().execute("INSERT INTO test VALUES (1, 1, 'user1', (1, 'organization1', (1, 'office1')))");
        assertRowsAnyOrder("SELECT (organization).office.name FROM test", rows(1, "office1"));
    }

    @Test
    public void testNestedCompactQueryReturnsDeserialized() {
        client().getSql().execute("CREATE TYPE Office ("
                + "id BIGINT, "
                + "name VARCHAR "
                + ") OPTIONS ('format'='compact', 'compactTypeName'='OfficeCompactType')");

        client().getSql().execute("CREATE TYPE Organization ("
                + "id BIGINT, "
                + "name VARCHAR, "
                + "office Office"
                + ") OPTIONS ('format'='compact', 'compactTypeName'='OrganizationCompactType')");

        client().getSql().execute("CREATE TYPE OrganizationAndLong ("
                + "id BIGINT, "
                + "l BIGINT, "
                + "organization Organization"
                + ") OPTIONS ('format'='compact', 'compactTypeName'='OrganizationAndLongCompactType')");

        client().getSql().execute(
                "CREATE MAPPING test ("
                        + "__key BIGINT,"
                        + "id BIGINT, "
                        + "name VARCHAR, "
                        + "organizationAndLong OrganizationAndLong"
                        + ")"
                        + "TYPE IMap "
                        + "OPTIONS ("
                        + "'keyFormat'='bigint',"
                        + "'valueFormat'='compact',"
                        + "'valueCompactTypeName'='UserCompactType'"
                        + ")");

        client().getSql().execute("INSERT INTO test VALUES (1, 1, 'user1', (1, 1, (1, 'organization1', (1, 'office1'))))");
        SqlResult result = client().getSql().execute("SELECT (organizationAndLong).organization.office FROM test");
        ArrayList<SqlRow> rows = new ArrayList<>();
        for (SqlRow row : result) {
            rows.add(row);
        }
        assertEquals(1, rows.size());
        assertInstanceOf(DeserializedGenericRecord.class, rows.get(0).getObject(0));
    }

    @Test
    public void testNestedCompactQueryReturnsArrayFieldDeserialized() {
        // We will use the OBJECT field type for the array of compact field because arrays are not supported
        // in the nested querying right now.
        // TODO: Change this when array support is added.
        client().getSql().execute("CREATE TYPE Organization ("
                + "id BIGINT, "
                + "name VARCHAR, "
                + "offices OBJECT"
                + ") OPTIONS ('format'='compact', 'compactTypeName'='com.hazelcast.jet.sql.impl.type.Organization')");

        client().getSql().execute("CREATE TYPE OrganizationAndLong ("
                + "id BIGINT, "
                + "l BIGINT, "
                + "organization Organization"
                + ") OPTIONS ('format'='compact', 'compactTypeName'='com.hazelcast.jet.sql.impl.type.OrganizationAndLong')");

        client().getSql().execute(
                "CREATE MAPPING test ("
                        + "__key BIGINT,"
                        + "id BIGINT, "
                        + "name VARCHAR, "
                        + "organizationAndLong OrganizationAndLong"
                        + ")"
                        + "TYPE IMap "
                        + "OPTIONS ("
                        + "'keyFormat'='bigint',"
                        + "'valueFormat'='compact',"
                        + "'valueCompactTypeName'='com.hazelcast.jet.sql.impl.type.UserCompactType'"
                        + ")");

        // We cannot use INSERT INTO to add an entry because OBJECT's format is not known to the member.
        // So we use map.put
        IMap<Long, UserCompactType> map = client().getMap("test");
        map.put(1L, new UserCompactType(1, "user1",
                new OrganizationAndLong(1, 1,
                        new Organization(1, "organization1",
                                new Office[]{new Office(1, "office1"), new Office(2, "office2")}))));

        SqlResult result = client().getSql().execute("SELECT (organizationAndLong).organization.offices FROM test");
        ArrayList<SqlRow> rows = new ArrayList<>();
        for (SqlRow row : result) {
            rows.add(row);
        }
        assertEquals(1, rows.size());
        Object obj = rows.get(0).getObject(0);
        assertInstanceOf(DeserializedGenericRecord[].class, obj);
        DeserializedGenericRecord[] array = (DeserializedGenericRecord[]) obj;
        assertEquals(array.length, 2);
        assertInstanceOf(DeserializedGenericRecord.class, array[0]);
        assertInstanceOf(DeserializedGenericRecord.class, array[1]);
    }

    @Test
    public void test_emptyColumnList() {
        assertThatThrownBy(() -> client().getSql()
                .execute("CREATE TYPE Office OPTIONS ('format'='compact', 'compactTypeName'='OfficeCompactType')"))
                .hasMessageContaining("Column list is required to create Compact-based Types");
    }
}
```
</details>

**Comment by srknzl** [comment]
Another reproducer where the classes made public to enable field access but the java class field name does not match the compact Schema field name: 

<details>

```java
/*
 * Copyright 2021 Hazelcast Inc.
 *
 * Licensed under the Hazelcast Community License (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://hazelcast.com/hazelcast-community-license
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.hazelcast.jet.sql.impl.type;

import com.hazelcast.config.Config;
import com.hazelcast.internal.serialization.impl.compact.DeserializedGenericRecord;
import com.hazelcast.jet.sql.SqlTestSupport;
import com.hazelcast.map.IMap;
import com.hazelcast.nio.serialization.compact.CompactReader;
import com.hazelcast.nio.serialization.compact.CompactSerializer;
import com.hazelcast.nio.serialization.compact.CompactWriter;
import com.hazelcast.sql.SqlResult;
import com.hazelcast.sql.SqlRow;
import com.hazelcast.test.HazelcastSerialClassRunner;
import org.jetbrains.annotations.NotNull;
import org.junit.BeforeClass;
import org.junit.Test;
import org.junit.runner.RunWith;

import java.io.Serializable;
import java.util.ArrayList;

import static com.hazelcast.spi.properties.ClusterProperty.SQL_CUSTOM_TYPES_ENABLED;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.junit.Assert.assertEquals;


@RunWith(HazelcastSerialClassRunner.class)
public class CompactNestedFieldsTest extends SqlTestSupport {

    @BeforeClass
    public static void beforeClass() {
        final Config config = new Config();
        config.getJetConfig().setEnabled(true);
        config.setProperty(SQL_CUSTOM_TYPES_ENABLED.getName(), "true");
        config.getSerializationConfig().getCompactSerializationConfig().addClass(UserCompactType.class);
        config.getSerializationConfig().getCompactSerializationConfig().addSerializer(new OrganizationSerializer());

        initializeWithClient(3, config, null);
    }

    @Test
    public void test_basicQuerying() {
        client().getSql().execute("CREATE TYPE Office ("
                + "id BIGINT, "
                + "name VARCHAR "
                + ") OPTIONS ('format'='compact', 'compactTypeName'='OfficeCompactType')");

        client().getSql().execute("CREATE TYPE Organization ("
                + "id BIGINT, "
                + "name VARCHAR, "
                + "office Office"
                + ") OPTIONS ('format'='compact', 'compactTypeName'='OrganizationCompactType')");

        client().getSql().execute(
                "CREATE MAPPING test ("
                        + "__key BIGINT,"
                        + "id BIGINT, "
                        + "name VARCHAR, "
                        + "organization Organization"
                        + ")"
                        + "TYPE IMap "
                        + "OPTIONS ("
                        + "'keyFormat'='bigint',"
                        + "'valueFormat'='compact',"
                        + "'valueCompactTypeName'='UserCompactType'"
                        + ")");

        client().getSql().execute("INSERT INTO test VALUES (1, 1, 'user1', (1, 'organization1', (1, 'office1')))");
        assertRowsAnyOrder("SELECT (organization).office.name FROM test", rows(1, "office1"));
    }

    @Test
    public void testNestedCompactQueryReturnsDeserialized() {
        client().getSql().execute("CREATE TYPE Office ("
                + "id BIGINT, "
                + "name VARCHAR "
                + ") OPTIONS ('format'='compact', 'compactTypeName'='OfficeCompactType')");

        client().getSql().execute("CREATE TYPE Organization ("
                + "id BIGINT, "
                + "name VARCHAR, "
                + "office Office"
                + ") OPTIONS ('format'='compact', 'compactTypeName'='OrganizationCompactType')");

        client().getSql().execute("CREATE TYPE OrganizationAndLong ("
                + "id BIGINT, "
                + "l BIGINT, "
                + "organization Organization"
                + ") OPTIONS ('format'='compact', 'compactTypeName'='OrganizationAndLongCompactType')");

        client().getSql().execute(
                "CREATE MAPPING test ("
                        + "__key BIGINT,"
                        + "id BIGINT, "
                        + "name VARCHAR, "
                        + "organizationAndLong OrganizationAndLong"
                        + ")"
                        + "TYPE IMap "
                        + "OPTIONS ("
                        + "'keyFormat'='bigint',"
                        + "'valueFormat'='compact',"
                        + "'valueCompactTypeName'='UserCompactType'"
                        + ")");

        client().getSql().execute("INSERT INTO test VALUES (1, 1, 'user1', (1, 1, (1, 'organization1', (1, 'office1'))))");
        SqlResult result = client().getSql().execute("SELECT (organizationAndLong).organization.office FROM test");
        ArrayList<SqlRow> rows = new ArrayList<>();
        for (SqlRow row : result) {
            rows.add(row);
        }
        assertEquals(1, rows.size());
        assertInstanceOf(DeserializedGenericRecord.class, rows.get(0).getObject(0));
    }

    @Test
    public void testNestedCompactQueryReturnsArrayFieldDeserialized() {
        // We will use the OBJECT field type for the array of compact field because arrays are not supported
        // in the nested querying right now.
        // TODO: Change this when array support is added.
        client().getSql().execute("CREATE TYPE Organization ("
                + "id BIGINT, "
                + "name VARCHAR, "
                + "different OBJECT"
                + ") OPTIONS ('format'='compact', 'compactTypeName'='com.hazelcast.jet.sql.impl.type.CompactNestedFieldsTest.Organization')");

        client().getSql().execute("CREATE TYPE OrganizationAndLong ("
                + "id BIGINT, "
                + "l BIGINT, "
                + "organization Organization"
                + ") OPTIONS ('format'='compact', 'compactTypeName'='com.hazelcast.jet.sql.impl.type.CompactNestedFieldsTest.OrganizationAndLong')");

        client().getSql().execute(
                "CREATE MAPPING test ("
                        + "__key BIGINT,"
                        + "id BIGINT, "
                        + "name VARCHAR, "
                        + "organizationAndLong OrganizationAndLong"
                        + ")"
                        + "TYPE IMap "
                        + "OPTIONS ("
                        + "'keyFormat'='bigint',"
                        + "'valueFormat'='compact',"
                        + "'valueCompactTypeName'='com.hazelcast.jet.sql.impl.type.CompactNestedFieldsTest.UserCompactType'"
                        + ")");

        // We cannot use INSERT INTO to add an entry because OBJECT's format is not known to the member.
        // So we use map.put
        IMap<Long, UserCompactType> map = client().getMap("test");
        map.put(1L, new UserCompactType(1, "user1",
                new OrganizationAndLong(1, 1,
                        new Organization(1, "organization1",
                                new Office[]{new Office(1, "office1"), new Office(2, "office2")}))));

        SqlResult result = client().getSql().execute("SELECT (organizationAndLong).organization.different FROM test");
        ArrayList<SqlRow> rows = new ArrayList<>();
        for (SqlRow row : result) {
            rows.add(row);
        }
        assertEquals(1, rows.size());
        Object obj = rows.get(0).getObject(0);
        // obj is null
        assertInstanceOf(DeserializedGenericRecord[].class, obj);
        DeserializedGenericRecord[] array = (DeserializedGenericRecord[]) obj;
        assertEquals(array.length, 2);
        assertInstanceOf(DeserializedGenericRecord.class, array[0]);
        assertInstanceOf(DeserializedGenericRecord.class, array[1]);
    }

    @Test
    public void test_emptyColumnList() {
        assertThatThrownBy(() -> client().getSql()
                .execute("CREATE TYPE Office OPTIONS ('format'='compact', 'compactTypeName'='OfficeCompactType')"))
                .hasMessageContaining("Column list is required to create Compact-based Types");
    }

    public static class Office implements Serializable {
        public long id;
        public String name;

        public Office(long id, String name) {
            this.id = id;
            this.name = name;
        }
    }

    public static class OrganizationSerializer implements CompactSerializer<Organization> {

        @NotNull
        @Override
        public Organization read(@NotNull CompactReader reader) {
            long id = reader.readInt64("id");
            String name = reader.readString("name");
            Office[] office = reader.readArrayOfCompact("different", Office.class);
            return new Organization(id, name, office);
        }

        @Override
        public void write(@NotNull CompactWriter writer, @NotNull Organization object) {
            writer.writeInt64("id", object.id);
            writer.writeString("name", object.name);
            writer.writeArrayOfCompact("different", object.offices);
        }

        @NotNull
        @Override
        public String getTypeName() {
            return "com.hazelcast.jet.sql.impl.type.CompactNestedFieldsTest.Organization";
        }

        @NotNull
        @Override
        public Class<Organization> getCompactClass() {
            return Organization.class;
        }
    }

    public static class Organization implements Serializable {
        public long id;
        public String name;
        public Office[] offices;

        public Organization(long id, String name, Office[] offices) {
            this.id = id;
            this.name = name;
            this.offices = offices;
        }
    }

    public static class OrganizationAndLong implements Serializable {
        public long id;
        public long l;
        public Organization organization;

        public OrganizationAndLong(long id, long l, Organization organization) {
            this.id = id;
            this.l = l;
            this.organization = organization;
        }
    }

    public static class UserCompactType implements Serializable {
        public long id;
        public String name;
        public OrganizationAndLong organizationAndLong;

        public UserCompactType(long id, String name, OrganizationAndLong organizationAndLong) {
            this.id = id;
            this.name = name;
            this.organizationAndLong = organizationAndLong;
        }
    }
}

```
</details>

**Comment by srknzl** [comment]
When I use GenericRecordBuilder to put data to the map, the select query fails with 

```

com.hazelcast.sql.HazelcastSqlException: Failed to serialize '[Lcom.hazelcast.nio.serialization.genericrecord.GenericRecord;'

	at com.hazelcast.sql.impl.client.SqlClientService.handleExecuteResponse(SqlClientService.java:282)
	at com.hazelcast.sql.impl.client.SqlClientService.execute(SqlClientService.java:129)
	at com.hazelcast.sql.SqlService.execute(SqlService.java:89)
	at com.hazelcast.jet.sql.impl.type.CompactNestedFieldsTest.testNestedCompactQueryReturnsArrayFieldDeserialized(CompactNestedFieldsTest.java:172)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:750)
```

I debugged it. It is because not being able to serialize DeserializedGenericRecord via Java serialization. GenericRecord[] is tried to be serialized via Java serialization while trying to serialize JetSqlRow to send it in intermember communications. 

<details>

```java
/*
 * Copyright 2021 Hazelcast Inc.
 *
 * Licensed under the Hazelcast Community License (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://hazelcast.com/hazelcast-community-license
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.hazelcast.jet.sql.impl.type;

import com.hazelcast.config.Config;
import com.hazelcast.internal.serialization.impl.compact.DeserializedGenericRecord;
import com.hazelcast.jet.sql.SqlTestSupport;
import com.hazelcast.map.IMap;
import com.hazelcast.nio.serialization.genericrecord.GenericRecord;
import com.hazelcast.nio.serialization.genericrecord.GenericRecordBuilder;
import com.hazelcast.sql.SqlResult;
import com.hazelcast.sql.SqlRow;
import com.hazelcast.test.HazelcastSerialClassRunner;
import org.junit.BeforeClass;
import org.junit.Test;
import org.junit.runner.RunWith;

import java.util.ArrayList;

import static com.hazelcast.spi.properties.ClusterProperty.SQL_CUSTOM_TYPES_ENABLED;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.junit.Assert.assertEquals;

@RunWith(HazelcastSerialClassRunner.class)
public class CompactNestedFieldsTest extends SqlTestSupport {

    @BeforeClass
    public static void beforeClass() {
        final Config config = new Config();
        config.getJetConfig().setEnabled(true);
        config.setProperty(SQL_CUSTOM_TYPES_ENABLED.getName(), "true");

        initializeWithClient(3, config, null);
    }

    @Test
    public void test_basicQuerying() {
        client().getSql().execute("CREATE TYPE Office ("
                + "id BIGINT, "
                + "name VARCHAR "
                + ") OPTIONS ('format'='compact', 'compactTypeName'='OfficeCompactType')");

        client().getSql().execute("CREATE TYPE Organization ("
                + "id BIGINT, "
                + "name VARCHAR, "
                + "office Office"
                + ") OPTIONS ('format'='compact', 'compactTypeName'='OrganizationCompactType')");

        client().getSql().execute(
                "CREATE MAPPING test ("
                        + "__key BIGINT,"
                        + "id BIGINT, "
                        + "name VARCHAR, "
                        + "organization Organization"
                        + ")"
                        + "TYPE IMap "
                        + "OPTIONS ("
                        + "'keyFormat'='bigint',"
                        + "'valueFormat'='compact',"
                        + "'valueCompactTypeName'='UserCompactType'"
                        + ")");

        client().getSql().execute("INSERT INTO test VALUES (1, 1, 'user1', (1, 'organization1', (1, 'office1')))");
        assertRowsAnyOrder("SELECT (organization).office.name FROM test", rows(1, "office1"));
    }

    @Test
    public void testNestedCompactQueryReturnsDeserialized() {
        client().getSql().execute("CREATE TYPE Office ("
                + "id BIGINT, "
                + "name VARCHAR "
                + ") OPTIONS ('format'='compact', 'compactTypeName'='OfficeCompactType')");

        client().getSql().execute("CREATE TYPE Organization ("
                + "id BIGINT, "
                + "name VARCHAR, "
                + "office Office"
                + ") OPTIONS ('format'='compact', 'compactTypeName'='OrganizationCompactType')");

        client().getSql().execute("CREATE TYPE OrganizationAndLong ("
                + "id BIGINT, "
                + "l BIGINT, "
                + "organization Organization"
                + ") OPTIONS ('format'='compact', 'compactTypeName'='OrganizationAndLongCompactType')");

        client().getSql().execute(
                "CREATE MAPPING test ("
                        + "__key BIGINT,"
                        + "id BIGINT, "
                        + "name VARCHAR, "
                        + "organizationAndLong OrganizationAndLong"
                        + ")"
                        + "TYPE IMap "
                        + "OPTIONS ("
                        + "'keyFormat'='bigint',"
                        + "'valueFormat'='compact',"
                        + "'valueCompactTypeName'='UserCompactType'"
                        + ")");

        client().getSql().execute("INSERT INTO test VALUES (1, 1, 'user1', (1, 1, (1, 'organization1', (1, 'office1'))))");
        SqlResult result = client().getSql().execute("SELECT (organizationAndLong).organization.office FROM test");
        ArrayList<SqlRow> rows = new ArrayList<>();
        for (SqlRow row : result) {
            rows.add(row);
        }
        assertEquals(1, rows.size());
        assertInstanceOf(DeserializedGenericRecord.class, rows.get(0).getObject(0));
    }

    @Test
    public void testNestedCompactQueryReturnsArrayFieldDeserialized() {
        // We will use the OBJECT field type for the array of compact field because arrays are not supported
        // in the nested querying right now.
        // TODO: Change this when array support is added.
        client().getSql().execute("CREATE TYPE Organization ("
                + "id BIGINT, "
                + "name VARCHAR, "
                + "offices OBJECT"
                + ") OPTIONS ('format'='compact', 'compactTypeName'='Organization')");

        client().getSql().execute("CREATE TYPE OrganizationAndLong ("
                + "id BIGINT, "
                + "l BIGINT, "
                + "organization Organization"
                + ") OPTIONS ('format'='compact', 'compactTypeName'='OrganizationAndLong')");

        client().getSql().execute(
                "CREATE MAPPING test ("
                        + "__key BIGINT,"
                        + "id BIGINT, "
                        + "name VARCHAR, "
                        + "organizationAndLong OrganizationAndLong"
                        + ")"
                        + "TYPE IMap "
                        + "OPTIONS ("
                        + "'keyFormat'='bigint',"
                        + "'valueFormat'='compact',"
                        + "'valueCompactTypeName'='UserCompactType'"
                        + ")");

        // We cannot use INSERT INTO to add an entry because OBJECT's format is not known to the member.
        // So we use map.put
        IMap<Long, GenericRecord> map = client().getMap("test");
        map.put(1L, GenericRecordBuilder.compact("UserCompactType")
                .setInt64("id", 1)
                .setString("name", "user1")
                .setGenericRecord("organizationAndLong", GenericRecordBuilder.compact("OrganizationAndLong").setInt64("id", 1).setInt64("l", 1)
                        .setGenericRecord("organization",
                                GenericRecordBuilder.compact("Organization")
                                        .setInt64("id", 1)
                                        .setString("name", "organization1")
                                        .setArrayOfGenericRecord("offices", new GenericRecord[] {
                                                GenericRecordBuilder.compact("Office").setInt64("id", 1).setString("name", "office1").build(),
                                                GenericRecordBuilder.compact("Office").setInt64("id", 2).setString("name", "office2").build()
                                        }).build()).build())
                .build());

        SqlResult result = client().getSql().execute("SELECT (organizationAndLong).organization.offices FROM test");
        ArrayList<SqlRow> rows = new ArrayList<>();
        for (SqlRow row : result) {
            rows.add(row);
        }
        assertEquals(1, rows.size());
        Object obj = rows.get(0).getObject(0);
        assertInstanceOf(DeserializedGenericRecord[].class, obj);
        DeserializedGenericRecord[] array = (DeserializedGenericRecord[]) obj;
        assertEquals(array.length, 2);
        assertInstanceOf(DeserializedGenericRecord.class, array[0]);
        assertInstanceOf(DeserializedGenericRecord.class, array[1]);
    }

    @Test
    public void test_emptyColumnList() {
        assertThatThrownBy(() -> client().getSql()
                .execute("CREATE TYPE Office OPTIONS ('format'='compact', 'compactTypeName'='OfficeCompactType')"))
                .hasMessageContaining("Column list is required to create Compact-based Types");
    }
}
```
</details>
