### ISSUE TITLE
com.hazelcast.jet.sql.LogExceptionSqlTest.when_limitInQueryReached_then_noExceptionIsThrown [HZ-1732]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#22729]
_master_ (commit 031327e6f4eb0aea4394414fafce7a49972e5159)

Failed on oracle-11 (sonar build): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/1385/testReport/com.hazelcast.jet.sql/LogExceptionSqlTest/when_limitInQueryReached_then_noExceptionIsThrown/
<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: 

Expecting empty but was:<[com.hazelcast.jet.core.JobNotFoundException: Job with id 08e8-4eee-9500-0001 not found]>
	at com.hazelcast.jet.sql.LogExceptionSqlTest.when_limitInQueryReached_then_noExceptionIsThrown(LogExceptionSqlTest.java:75)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)

```
</details>
<details><summary>Standard output:</summary>

```
04:01:41,452  INFO |when_limitInQueryReached_then_noExceptionIsThrown| - [PartitionStateManager] when_limitInQueryReached_then_noExceptionIsThrown - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Initializing cluster partition table arrangement...
04:01:41,457 DEBUG |when_limitInQueryReached_then_noExceptionIsThrown| - [CalciteSqlOptimizer] when_limitInQueryReached_then_noExceptionIsThrown - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Before logical opt:
LogicalSort(fetch=[2:TINYINT(2)])
  LogicalTableFunctionScan(invocation=[GENERATE_STREAM(5)], rowType=[RecordType:peek(BIGINT v)])

04:01:41,459 DEBUG |when_limitInQueryReached_then_noExceptionIsThrown| - [CalciteSqlOptimizer] when_limitInQueryReached_then_noExceptionIsThrown - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] After logical opt:
SortLogicalRel(fetch=[2:TINYINT(2)])
  FullScanLogicalRel(table=[[hazelcast, stream, stream_5caf8333_2bb1_4f66_8e92_784bc7df93c0[projects=[$0]]]])

04:01:41,460 DEBUG |when_limitInQueryReached_then_noExceptionIsThrown| - [CalciteSqlOptimizer] when_limitInQueryReached_then_noExceptionIsThrown - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] After physical opt:
SortPhysicalRel(fetch=[2:TINYINT(2)], requiresSort=[false])
  FullScanPhysicalRel(table=[[hazelcast, stream, stream_5caf8333_2bb1_4f66_8e92_784bc7df93c0[projects=[$0]]]], discriminator=[0])

04:01:41,461 DEBUG |when_limitInQueryReached_then_noExceptionIsThrown| - [LightMasterContext] when_limitInQueryReached_then_noExceptionIsThrown - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Start executing light job 08e8-4eee-9500-0001, execution graph in DOT format:
digraph DAG {
	"Stream[stream.stream_5caf8333_2bb1_4f66_8e92_784bc7df93c0]" [localParallelism=1];
	"ClientSink" [localParallelism=1];
	"Stream[stream.stream_5caf8333_2bb1_4f66_8e92_784bc7df93c0]" -> "ClientSink" [label="distributed to [127.0.0.1]:5701-partitioned", queueSize=1024];
}
HINT: You can use graphviz or http://viz-js.com to visualize the printed graph.
04:01:41,461 DEBUG |when_limitInQueryReached_then_noExceptionIsThrown| - [LightMasterContext] when_limitInQueryReached_then_noExceptionIsThrown - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Building execution plan for 08e8-4eee-9500-0001
04:01:41,461 DEBUG || - [LightMasterContext] hz.unruffled_rosalind.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Built execution plans for 08e8-4eee-9500-0001
04:01:41,462 DEBUG || - [InitExecutionOperation] hz.charming_rosalind.generic-operation.thread-1 - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Initializing execution plan for job 08e8-4eee-9500-0001, execution 08e8-4eee-9500-0001 from [127.0.0.1]:5701
04:01:41,462 DEBUG || - [InitExecutionOperation] hz.unruffled_rosalind.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Initializing execution plan for job 08e8-4eee-9500-0001, execution 08e8-4eee-9500-0001 from [127.0.0.1]:5701
04:01:41,462 DEBUG || - [JobExecutionService] hz.unruffled_rosalind.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Execution plan for light job ID=08e8-4eee-9500-0001, jobName='08e8-4eee-9500-0001', executionId=08e8-4eee-9500-0001 initialized, will start the execution
04:01:41,462 DEBUG || - [JobExecutionService] hz.charming_rosalind.cached.thread-4 - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Execution plan for light job ID=08e8-4eee-9500-0001, jobName='08e8-4eee-9500-0001', executionId=08e8-4eee-9500-0001 initialized, will start the execution
04:01:41,506 DEBUG || - [JobRepository] hz.unruffled_rosalind.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Job cleanup took 0ms
04:01:41,865 DEBUG || - [TaskletExecutionService] hz.unruffled_rosalind.jet.cooperative.thread-0 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] SQL LIMIT reached.
04:01:41,867 DEBUG || - [JobExecutionService] hz.unruffled_rosalind.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Completed execution of job '08e8-4eee-9500-0001', execution 08e8-4eee-9500-0001
04:01:41,867 DEBUG || - [JobExecutionService] hz.unruffled_rosalind.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Execution of job '08e8-4eee-9500-0001', execution 08e8-4eee-9500-0001 completed with failure
java.util.concurrent.CompletionException: com.hazelcast.sql.impl.ResultLimitReachedException: Done by reaching the item number in SQL LIMIT clause
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:870) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088) ~[?:?]
	at com.hazelcast.jet.impl.util.NonCompletableFuture.internalCompleteExceptionally(NonCompletableFuture.java:72) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$ExecutionTracker.taskletDone(TaskletExecutionService.java:498) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.dismissTasklet(TaskletExecutionService.java:429) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:415) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807) ~[?:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.run(TaskletExecutionService.java:369) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:834) ~[?:?]
Caused by: com.hazelcast.sql.impl.ResultLimitReachedException: Done by reaching the item number in SQL LIMIT clause
04:01:41,871 DEBUG || - [JobExecutionService] hz.charming_rosalind.cached.thread-2 - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Completed execution of job '08e8-4eee-9500-0001', execution 08e8-4eee-9500-0001
04:01:41,872 DEBUG || - [JobExecutionService] hz.charming_rosalind.cached.thread-2 - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Execution of job '08e8-4eee-9500-0001', execution 08e8-4eee-9500-0001 completed with failure
java.util.concurrent.CompletionException: com.hazelcast.jet.impl.exception.JobTerminateRequestedException: CANCEL_FORCEFUL
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:870) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088) ~[?:?]
	at com.hazelcast.jet.impl.util.NonCompletableFuture.internalCompleteExceptionally(NonCompletableFuture.java:72) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$ExecutionTracker.taskletDone(TaskletExecutionService.java:498) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$BlockingWorker.run(TaskletExecutionService.java:330) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) ~[?:?]
Caused by: com.hazelcast.jet.impl.exception.JobTerminateRequestedException: CANCEL_FORCEFUL
	at com.hazelcast.jet.impl.execution.ExecutionContext.terminateExecution(ExecutionContext.java:318) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.jet.impl.JobExecutionService.terminateExecution0(JobExecutionService.java:722) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.jet.impl.JobExecutionService.terminateExecution(JobExecutionService.java:718) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.jet.impl.operation.TerminateExecutionOperation.doRun(TerminateExecutionOperation.java:59) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.jet.impl.operation.AsyncOperation.run(AsyncOperation.java:55) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:190) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:283) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:258) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:486) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:197) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:137) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
04:01:41,883 ERROR |when_limitInQueryReached_then_noExceptionIsThrown| - [JoinSubmittedJobOperation] when_limitInQueryReached_then_noExceptionIsThrown - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Job with id 08e8-4eee-9500-0001 not found
com.hazelcast.jet.core.JobNotFoundException: Job with id 08e8-4eee-9500-0001 not found
	at com.hazelcast.jet.impl.JobCoordinationService.joinLightJob(JobCoordinationService.java:469) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.jet.impl.operation.JoinSubmittedJobOperation.doRun(JoinSubmittedJobOperation.java:41) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.jet.impl.operation.AsyncOperation.run(AsyncOperation.java:55) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:190) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:283) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:258) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:219) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:411) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:438) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:601) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:580) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:541) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:241) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:61) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.jet.impl.JobProxy.invokeOp(JobProxy.java:201) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.jet.impl.JobProxy.invokeJoinJob(JobProxy.java:124) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.jet.impl.AbstractJobProxy.doInvokeJoinJob(AbstractJobProxy.java:331) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.jet.impl.AbstractJobProxy.getFuture(AbstractJobProxy.java:162) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.jet.SimpleTestInClusterSupport.lambda$assertNoJobsLeftEventually$0(SimpleTestInClusterSupport.java:89) ~[hazelcast-5.3.0-SNAPSHOT-tests.jar:5.3.0-SNAPSHOT]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
	at com.hazelcast.jet.SimpleTestInClusterSupport.lambda$assertNoJobsLeftEventually$1(SimpleTestInClusterSupport.java:90) ~[hazelcast-5.3.0-SNAPSHOT-tests.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1236) ~[hazelcast-5.3.0-SNAPSHOT-tests.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1338) ~[hazelcast-5.3.0-SNAPSHOT-tests.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.jet.SimpleTestInClusterSupport.assertNoJobsLeftEventually(SimpleTestInClusterSupport.java:87) ~[hazelcast-5.3.0-SNAPSHOT-tests.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.jet.sql.LogExceptionSqlTest.when_limitInQueryReached_then_noExceptionIsThrown(LogExceptionSqlTest.java:71) ~[test-classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) ~[junit-4.13.2.jar:4.13.2]
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115) ~[hazelcast-5.3.0-SNAPSHOT-tests.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107) ~[hazelcast-5.3.0-SNAPSHOT-tests.jar:5.3.0-SNAPSHOT]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) ~[?:?]
04:01:41,890 ERROR |when_limitInQueryReached_then_noExceptionIsThrown| - [AbstractJobProxy] ForkJoinPool.commonPool-worker-3 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Exception during callback
java.lang.IllegalStateException: job already completed
	at com.hazelcast.jet.impl.AbstractJobProxy.lambda$doInvokeJoinJob$0(AbstractJobProxy.java:334) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.jet.impl.util.ExceptionUtil.lambda$withTryCatch$0(ExceptionUtil.java:178) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.spi.impl.AbstractInvocationFuture.lambda$unblockWhenComplete$3(AbstractInvocationFuture.java:914) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.test.TestLoggingUtils$CustomTestNameAwareForkJoinPool$TestNameAwareRunnable.run(TestLoggingUtils.java:104) ~[hazelcast-5.3.0-SNAPSHOT-tests.jar:5.3.0-SNAPSHOT]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?]
04:01:42,972  INFO |when_limitInQueryReached_then_noExceptionIsThrown| - [SimpleTestInClusterSupport] Time-limited test - Ditching 0 jobs in SimpleTestInClusterSupport.@After: []
04:01:42,972  INFO |when_limitInQueryReached_then_noExceptionIsThrown| - [SimpleTestInClusterSupport] Time-limited test - Destroying 2 distributed objects in SimpleTestInClusterSupport.@After: [hz:impl:mapService/__sql.catalog, hz:impl:flakeIdGeneratorService/__jet.ids]
BuildInfo right after when_limitInQueryReached_then_noExceptionIsThrown(com.hazelcast.jet.sql.LogExceptionSqlTest): BuildInfo{version='5.3.0-SNAPSHOT', build='20221106', buildNumber=20221106, revision=031327e, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'when_limitInQueryReached_then_noExceptionIsThrown(com.hazelcast.jet.sql.LogExceptionSqlTest):'
04:01:40, accumulated pauses: 882 ms, max pause: 846 ms, pauses over 1000 ms: 0


No metrics recorded during the test

```
</details>

**Comment by olukas** [comment]
Failed again on _master_ with: 
- `CorrettoJDK8`: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-CorrettoJDK8/202/testReport/com.hazelcast.jet.sql/LogExceptionSqlTest/when_limitInQueryReached_then_noExceptionIsThrown/
- `OracleJDK11`: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-OracleJDK11/345/testReport/com.hazelcast.jet.sql/LogExceptionSqlTest/when_limitInQueryReached_then_noExceptionIsThrown/
- `MicrosoftJDK17`: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Windows-MicrosoftJDK17/34/testReport/com.hazelcast.jet.sql/LogExceptionSqlTest/when_limitInQueryReached_then_noExceptionIsThrown/
- `ZuluJDK8`: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZuluJDK8/212/testReport/com.hazelcast.jet.sql/LogExceptionSqlTest/when_limitInQueryReached_then_noExceptionIsThrown/
- MacOS with `ZuluJDK8`: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-MacOS-ZuluJDK8/129/testReport/com.hazelcast.jet.sql/LogExceptionSqlTest/when_limitInQueryReached_then_noExceptionIsThrown/
