### ISSUE TITLE
com.hazelcast.cache.impl.journal.CacheEventJournalBounceTest.testBouncingEventJournal

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#22732]
_4.2.z_ (commit ae449adad49018b3198876c04aba438ada3ee3e6)

Failed on OracleJDK8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-4.maintenance-OracleJDK8-nightly/950/testReport/com.hazelcast.cache.impl.journal/CacheEventJournalBounceTest/testBouncingEventJournal/
<details><summary>Stacktrace:</summary>

```
com.hazelcast.core.OperationTimeoutException: CacheEventJournalSubscribeOperation invocation failed to complete due to operation-heartbeat-timeout. Current time: 2022-11-06 14:03:58.166. Start time: 2022-11-06 14:01:58.045. Total elapsed time: 120121 ms. Last operation heartbeat: never. Last operation heartbeat from member: never. Invocation{op=com.hazelcast.cache.impl.journal.CacheEventJournalSubscribeOperation{serviceName='hz:impl:cacheService', identityHash=1911624991, partitionId=8, replicaIndex=0, callId=-13794, invocationTime=1667743318045 (2022-11-06 14:01:58.045), waitTimeout=-1, callTimeout=60000, tenantControl=com.hazelcast.spi.impl.tenantcontrol.NoopTenantControl@0, name=/hz/eventJournalTestCache}, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=60000, firstInvocationTimeMs=1667743318045, firstInvocationTime='2022-11-06 14:01:58.045', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 00:00:00.000', target=[127.0.0.1]:5711, pendingResponse={VOID}, backupsAcksExpected=-1, backupsAcksReceived=25, connection=null}
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.newOperationTimeoutException(InvocationFuture.java:194)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:136)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:99)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:617)
	at com.hazelcast.journal.AbstractEventJournalBounceTest.getEventJournalEvents(AbstractEventJournalBounceTest.java:118)
	at com.hazelcast.journal.AbstractEventJournalBounceTest.access$000(AbstractEventJournalBounceTest.java:47)
	at com.hazelcast.journal.AbstractEventJournalBounceTest$EventJournalReadRunnable.run(AbstractEventJournalBounceTest.java:108)
	at com.hazelcast.test.bounce.BounceMemberRule$TestTaskRunnable.run(BounceMemberRule.java:605)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
	at ------ submitted from ------.()
	at com.hazelcast.internal.util.ExceptionUtil.cloneExceptionWithFixedAsyncStackTrace(ExceptionUtil.java:289)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.returnOrThrowWithGetConventions(InvocationFuture.java:112)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:100)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:617)
	at com.hazelcast.journal.AbstractEventJournalBounceTest.getEventJournalEvents(AbstractEventJournalBounceTest.java:118)
	at com.hazelcast.journal.AbstractEventJournalBounceTest.access$000(AbstractEventJournalBounceTest.java:47)
	at com.hazelcast.journal.AbstractEventJournalBounceTest$EventJournalReadRunnable.run(AbstractEventJournalBounceTest.java:108)
	at com.hazelcast.test.bounce.BounceMemberRule$TestTaskRunnable.run(BounceMemberRule.java:605)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-4.maintenance-OracleJDK8-nightly/950/

**Comment by Patras3** [comment]
This comment was automatically generated to summarize test results for the last 30 days.

```

For branch: master
Builds between : 2024-07-03 03:15 - 2024-07-31 03:15
Jobs: 11, Runs: 41, Passed: 38, Failed: 3, Skipped: 0, Fail Ratio: 7.32%
Run on:
+--------------------------------------------------+
| JDK        | PASSED | FAILED | SKIPPED |  RATIO  |
+--------------------------------------------------+
| zing-21    |   3    |   1    |    0    |  25.00% |
| oracle-17  |   9    |   1    |    0    |  10.00% |
| unknown    |   12   |   1    |    0    |   7.69% |
| openj9-21  |   3    |   0    |    0    |   0.00% |
| oracle-21  |   4    |   0    |    0    |   0.00% |
| zing-17    |   3    |   0    |    0    |   0.00% |
| openjdk-17 |   4    |   0    |    0    |   0.00% |
+--------------------------------------------------+
Note: Passing since 2024-07-24 03:15

Builds Timeline:
2024-07-31 03:15 - PASSED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK17-nightly-Esxi7/99/testReport/com.hazelcast.cache.impl.journal/CacheEventJournalBounceTest/testBouncingEventJournal/
2024-07-31 03:08 - PASSED (oracle-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-OracleJDK21-nightly/28/testReport/com.hazelcast.cache.impl.journal/CacheEventJournalBounceTest/testBouncingEventJournal/
2024-07-29 03:12 - PASSED (openj9-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-Openj9-21-nightly/29/testReport/com.hazelcast.cache.impl.journal/CacheEventJournalBounceTest/testBouncingEventJournal/
2024-07-28 18:11 - PASSED (zing-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK21-nightly/32/testReport/com.hazelcast.cache.impl.journal/CacheEventJournalBounceTest/testBouncingEventJournal/
2024-07-28 12:12 - PASSED (oracle-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-nightly-force-offload/111/testReport/com.hazelcast.cache.impl.journal/CacheEventJournalBounceTest/testBouncingEventJournal/
2024-07-27 00:07 - PASSED (oracle-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-nightly-little-endian/89/testReport/com.hazelcast.cache.impl.journal/CacheEventJournalBounceTest/testBouncingEventJournal/
2024-07-26 18:06 - PASSED (zing-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK17-nightly/91/testReport/com.hazelcast.cache.impl.journal/CacheEventJournalBounceTest/testBouncingEventJournal/
2024-07-26 03:14 - PASSED (openjdk-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-ZuluJDK17-nightly/128/testReport/com.hazelcast.cache.impl.journal/CacheEventJournalBounceTest/testBouncingEventJournal/
2024-07-24 21:52 - PASSED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-CorrettoJDK17-arm64-nightly/26/testReport/com.hazelcast.cache.impl.journal/CacheEventJournalBounceTest/testBouncingEventJournal/
2024-07-24 03:15 - FIXED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK17-nightly-Esxi7/98/testReport/com.hazelcast.cache.impl.journal/CacheEventJournalBounceTest/testBouncingEventJournal/
2024-07-24 03:08 - PASSED (oracle-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-OracleJDK21-nightly/27/testReport/com.hazelcast.cache.impl.journal/CacheEventJournalBounceTest/testBouncingEventJournal/
2024-07-22 03:12 - PASSED (openj9-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-Openj9-21-nightly/28/testReport/com.hazelcast.cache.impl.journal/CacheEventJournalBounceTest/testBouncingEventJournal/
2024-07-21 18:11 - FIXED (zing-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK21-nightly/31/testReport/com.hazelcast.cache.impl.journal/CacheEventJournalBounceTest/testBouncingEventJournal/
2024-07-20 00:07 - FIXED (oracle-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-nightly-little-endian/88/testReport/com.hazelcast.cache.impl.journal/CacheEventJournalBounceTest/testBouncingEventJournal/
2024-07-19 18:06 - PASSED (zing-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK17-nightly/90/testReport/com.hazelcast.cache.impl.journal/CacheEventJournalBounceTest/testBouncingEventJournal/
2024-07-19 03:14 - PASSED (openjdk-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-ZuluJDK17-nightly/127/testReport/com.hazelcast.cache.impl.journal/CacheEventJournalBounceTest/testBouncingEventJournal/
2024-07-17 03:15 - REGRESSION (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK17-nightly-Esxi7/97/testReport/com.hazelcast.cache.impl.journal/CacheEventJournalBounceTest/testBouncingEventJournal/
2024-07-14 18:11 - REGRESSION (zing-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK21-nightly/30/testReport/com.hazelcast.cache.impl.journal/CacheEventJournalBounceTest/testBouncingEventJournal/
2024-07-13 00:07 - REGRESSION (oracle-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-nightly-little-endian/87/testReport/com.hazelcast.cache.impl.journal/CacheEventJournalBounceTest/testBouncingEventJournal/
2024-07-12 03:14 - PASSED (openjdk-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-ZuluJDK17-nightly/126/testReport/com.hazelcast.cache.impl.journal/CacheEventJournalBounceTest/testBouncingEventJournal/
2024-07-12 02:43 - PASSED (oracle-17):
    https://jenkins.hazelcast.com/job/Hazelcast-mono-OS-master-sonar/214/testReport/com.hazelcast.cache.impl.journal/CacheEventJournalBounceTest/testBouncingEventJournal/
2024-07-11 23:35 - PASSED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-sonar/536/testReport/com.hazelcast.cache.impl.journal/CacheEventJournalBounceTest/testBouncingEventJournal/
2024-07-11 02:43 - PASSED (oracle-17):
    https://jenkins.hazelcast.com/job/Hazelcast-mono-OS-master-sonar/213/testReport/com.hazelcast.cache.impl.journal/CacheEventJournalBounceTest/testBouncingEventJournal/
2024-07-10 23:35 - PASSED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-sonar/535/testReport/com.hazelcast.cache.impl.journal/CacheEventJournalBounceTest/testBouncingEventJournal/
2024-07-10 21:52 - PASSED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-CorrettoJDK17-arm64-nightly/24/testReport/com.hazelcast.cache.impl.journal/CacheEventJournalBounceTest/testBouncingEventJournal/
2024-07-10 09:10 - PASSED (zing-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK21-nightly/29/testReport/com.hazelcast.cache.impl.journal/CacheEventJournalBounceTest/testBouncingEventJournal/
2024-07-10 03:15 - PASSED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK17-nightly-Esxi7/96/testReport/com.hazelcast.cache.impl.journal/CacheEventJournalBounceTest/testBouncingEventJournal/
2024-07-10 03:08 - PASSED (oracle-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-OracleJDK21-nightly/25/testReport/com.hazelcast.cache.impl.journal/CacheEventJournalBounceTest/testBouncingEventJournal/
2024-07-10 02:43 - PASSED (oracle-17):
    https://jenkins.hazelcast.com/job/Hazelcast-mono-OS-master-sonar/212/testReport/com.hazelcast.cache.impl.journal/CacheEventJournalBounceTest/testBouncingEventJournal/
2024-07-09 23:35 - PASSED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-sonar/534/testReport/com.hazelcast.cache.impl.journal/CacheEventJournalBounceTest/testBouncingEventJournal/
2024-07-09 02:43 - PASSED (oracle-17):
    https://jenkins.hazelcast.com/job/Hazelcast-mono-OS-master-sonar/211/testReport/com.hazelcast.cache.impl.journal/CacheEventJournalBounceTest/testBouncingEventJournal/
2024-07-08 23:35 - PASSED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-sonar/533/testReport/com.hazelcast.cache.impl.journal/CacheEventJournalBounceTest/testBouncingEventJournal/
2024-07-08 03:12 - PASSED (openj9-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-Openj9-21-nightly/26/testReport/com.hazelcast.cache.impl.journal/CacheEventJournalBounceTest/testBouncingEventJournal/
2024-07-08 02:43 - PASSED (oracle-17):
    https://jenkins.hazelcast.com/job/Hazelcast-mono-OS-master-sonar/210/testReport/com.hazelcast.cache.impl.journal/CacheEventJournalBounceTest/testBouncingEventJournal/
2024-07-07 23:35 - PASSED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-sonar/532/testReport/com.hazelcast.cache.impl.journal/CacheEventJournalBounceTest/testBouncingEventJournal/
2024-07-06 00:07 - PASSED (oracle-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-nightly-little-endian/86/testReport/com.hazelcast.cache.impl.journal/CacheEventJournalBounceTest/testBouncingEventJournal/
2024-07-05 18:06 - PASSED (zing-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK17-nightly/88/testReport/com.hazelcast.cache.impl.journal/CacheEventJournalBounceTest/testBouncingEventJournal/
2024-07-05 03:14 - PASSED (openjdk-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-ZuluJDK17-nightly/125/testReport/com.hazelcast.cache.impl.journal/CacheEventJournalBounceTest/testBouncingEventJournal/
2024-07-03 21:52 - PASSED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-CorrettoJDK17-arm64-nightly/23/testReport/com.hazelcast.cache.impl.journal/CacheEventJournalBounceTest/testBouncingEventJournal/
2024-07-03 03:28 - PASSED (oracle-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-OracleJDK21-nightly/24/testReport/com.hazelcast.cache.impl.journal/CacheEventJournalBounceTest/testBouncingEventJournal/
2024-07-03 03:15 - PASSED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK17-nightly-Esxi7/95/testReport/com.hazelcast.cache.impl.journal/CacheEventJournalBounceTest/testBouncingEventJournal/

----------------------------------------

For branch: 5.5.z
Builds between : 2024-07-31 18:08 - 2024-07-31 18:08
Jobs: 1, Runs: 1, Passed: 1, Failed: 0, Skipped: 0, Fail Ratio: 0.00%
Run on:
+--------------------------------------------------+
| JDK        | PASSED | FAILED | SKIPPED |  RATIO  |
+--------------------------------------------------+
| openjdk-17 |   1    |   0    |    0    |   0.00% |
+--------------------------------------------------+

Builds Timeline:
2024-07-31 18:08 - PASSED (openjdk-17):
    https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-ZuluJDK17-nightly/128/testReport/com.hazelcast.cache.impl.journal/CacheEventJournalBounceTest/testBouncingEventJournal/

----------------------------------------

For branch: 5.4.z
Builds between : 2024-07-03 18:08 - 2024-07-29 18:02
Jobs: 3, Runs: 12, Passed: 12, Failed: 0, Skipped: 0, Fail Ratio: 0.00%
Run on:
+--------------------------------------------------+
| JDK        | PASSED | FAILED | SKIPPED |  RATIO  |
+--------------------------------------------------+
| openjdk-17 |   4    |   0    |    0    |   0.00% |
| oracle-21  |   4    |   0    |    0    |   0.00% |
| openj9-21  |   4    |   0    |    0    |   0.00% |
+--------------------------------------------------+

Builds Timeline:
2024-07-29 18:02 - PASSED (oracle-21):
    https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-OracleJDK21-nightly/14/testReport/com.hazelcast.cache.impl.journal/CacheEventJournalBounceTest/testBouncingEventJournal/
2024-07-27 18:06 - PASSED (openj9-21):
    https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-Openj9-21-nightly/13/testReport/com.hazelcast.cache.impl.journal/CacheEventJournalBounceTest/testBouncingEventJournal/
2024-07-24 18:08 - PASSED (openjdk-17):
    https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-ZuluJDK17-nightly/127/testReport/com.hazelcast.cache.impl.journal/CacheEventJournalBounceTest/testBouncingEventJournal/
2024-07-22 18:02 - PASSED (oracle-21):
    https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-OracleJDK21-nightly/13/testReport/com.hazelcast.cache.impl.journal/CacheEventJournalBounceTest/testBouncingEventJournal/
2024-07-20 18:06 - PASSED (openj9-21):
    https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-Openj9-21-nightly/12/testReport/com.hazelcast.cache.impl.journal/CacheEventJournalBounceTest/testBouncingEventJournal/
2024-07-17 18:08 - PASSED (openjdk-17):
    https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-ZuluJDK17-nightly/126/testReport/com.hazelcast.cache.impl.journal/CacheEventJournalBounceTest/testBouncingEventJournal/
2024-07-15 18:02 - PASSED (oracle-21):
    https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-OracleJDK21-nightly/12/testReport/com.hazelcast.cache.impl.journal/CacheEventJournalBounceTest/testBouncingEventJournal/
2024-07-13 18:06 - PASSED (openj9-21):
    https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-Openj9-21-nightly/11/testReport/com.hazelcast.cache.impl.journal/CacheEventJournalBounceTest/testBouncingEventJournal/
2024-07-10 18:08 - PASSED (openjdk-17):
    https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-ZuluJDK17-nightly/125/testReport/com.hazelcast.cache.impl.journal/CacheEventJournalBounceTest/testBouncingEventJournal/
2024-07-08 18:02 - PASSED (oracle-21):
    https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-OracleJDK21-nightly/11/testReport/com.hazelcast.cache.impl.journal/CacheEventJournalBounceTest/testBouncingEventJournal/
2024-07-06 18:06 - PASSED (openj9-21):
    https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-Openj9-21-nightly/10/testReport/com.hazelcast.cache.impl.journal/CacheEventJournalBounceTest/testBouncingEventJournal/
2024-07-03 18:08 - PASSED (openjdk-17):
    https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-ZuluJDK17-nightly/124/testReport/com.hazelcast.cache.impl.journal/CacheEventJournalBounceTest/testBouncingEventJournal/

----------------------------------------

For branch: 5.2.z
Builds between : 2024-07-06 03:10 - 2024-07-27 03:10
Jobs: 1, Runs: 4, Passed: 4, Failed: 0, Skipped: 0, Fail Ratio: 0.00%
Run on:
+------------------------------------------------+
| JDK      | PASSED | FAILED | SKIPPED |  RATIO  |
+------------------------------------------------+
| oracle-8 |   4    |   0    |    0    |   0.00% |
+------------------------------------------------+

Builds Timeline:
2024-07-27 03:10 - PASSED (oracle-8):
    https://jenkins.hazelcast.com/job/Hazelcast-5.2.z-OracleJDK8-nightly/63/testReport/com.hazelcast.cache.impl.journal/CacheEventJournalBounceTest/testBouncingEventJournal/
2024-07-20 03:10 - PASSED (oracle-8):
    https://jenkins.hazelcast.com/job/Hazelcast-5.2.z-OracleJDK8-nightly/62/testReport/com.hazelcast.cache.impl.journal/CacheEventJournalBounceTest/testBouncingEventJournal/
2024-07-13 03:10 - PASSED (oracle-8):
    https://jenkins.hazelcast.com/job/Hazelcast-5.2.z-OracleJDK8-nightly/61/testReport/com.hazelcast.cache.impl.journal/CacheEventJournalBounceTest/testBouncingEventJournal/
2024-07-06 03:10 - PASSED (oracle-8):
    https://jenkins.hazelcast.com/job/Hazelcast-5.2.z-OracleJDK8-nightly/60/testReport/com.hazelcast.cache.impl.journal/CacheEventJournalBounceTest/testBouncingEventJournal/

----------------------------------------

For branch: 4.2.z
Builds between : 2024-07-07 12:14 - 2024-07-28 12:14
Jobs: 1, Runs: 4, Passed: 4, Failed: 0, Skipped: 0, Fail Ratio: 0.00%
Run on:
+------------------------------------------------+
| JDK      | PASSED | FAILED | SKIPPED |  RATIO  |
+------------------------------------------------+
| oracle-8 |   4    |   0    |    0    |   0.00% |
+------------------------------------------------+

Builds Timeline:
2024-07-28 12:14 - PASSED (oracle-8):
    https://jenkins.hazelcast.com/job/Hazelcast-4.maintenance-OracleJDK8-nightly/1040/testReport/com.hazelcast.cache.impl.journal/CacheEventJournalBounceTest/testBouncingEventJournal/
2024-07-21 12:14 - PASSED (oracle-8):
    https://jenkins.hazelcast.com/job/Hazelcast-4.maintenance-OracleJDK8-nightly/1039/testReport/com.hazelcast.cache.impl.journal/CacheEventJournalBounceTest/testBouncingEventJournal/
2024-07-14 12:14 - PASSED (oracle-8):
    https://jenkins.hazelcast.com/job/Hazelcast-4.maintenance-OracleJDK8-nightly/1038/testReport/com.hazelcast.cache.impl.journal/CacheEventJournalBounceTest/testBouncingEventJournal/
2024-07-07 12:14 - PASSED (oracle-8):
    https://jenkins.hazelcast.com/job/Hazelcast-4.maintenance-OracleJDK8-nightly/1037/testReport/com.hazelcast.cache.impl.journal/CacheEventJournalBounceTest/testBouncingEventJournal/

----------------------------------------

For branch: 5.3.z
Builds between : 2024-07-08 03:11 - 2024-07-29 03:11
Jobs: 1, Runs: 4, Passed: 4, Failed: 0, Skipped: 0, Fail Ratio: 0.00%
Run on:
+------------------------------------------------+
| JDK      | PASSED | FAILED | SKIPPED |  RATIO  |
+------------------------------------------------+
| oracle-8 |   4    |   0    |    0    |   0.00% |
+------------------------------------------------+

Builds Timeline:
2024-07-29 03:11 - PASSED (oracle-8):
    https://jenkins.hazelcast.com/job/Hazelcast-5.3.z-OracleJDK8-nightly/13/testReport/com.hazelcast.cache.impl.journal/CacheEventJournalBounceTest/testBouncingEventJournal/
2024-07-22 03:11 - PASSED (oracle-8):
    https://jenkins.hazelcast.com/job/Hazelcast-5.3.z-OracleJDK8-nightly/12/testReport/com.hazelcast.cache.impl.journal/CacheEventJournalBounceTest/testBouncingEventJournal/
2024-07-15 03:11 - PASSED (oracle-8):
    https://jenkins.hazelcast.com/job/Hazelcast-5.3.z-OracleJDK8-nightly/11/testReport/com.hazelcast.cache.impl.journal/CacheEventJournalBounceTest/testBouncingEventJournal/
2024-07-08 03:11 - PASSED (oracle-8):
    https://jenkins.hazelcast.com/job/Hazelcast-5.3.z-OracleJDK8-nightly/10/testReport/com.hazelcast.cache.impl.journal/CacheEventJournalBounceTest/testBouncingEventJournal/

----------------------------------------
```

**Comment by olukas** [comment]
Closing the test failure - it doesn't seem to be related to `master` or the latest maintenance stream `5.5.z` and it hasn't fail in the last 3 months. Feel free to reopen test failure if it occurs on `master` or on the latest maintenance stream.
