### ISSUE TITLE
com.hazelcast.it.hibernate.HibernateIT.testInsertLoad [HZ-1791]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#22730]
_master_ (commit 031327e6f4eb0aea4394414fafce7a49972e5159)

Failed on OpenJDK19: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-OpenJDK19-nightly/2/testReport/com.hazelcast.it.hibernate/HibernateIT/testInsertLoad_cacheRegionFactory__class_com_hazelcast_hibernate_HazelcastLocalCacheRegionFactory_/

Failed in variant `[cacheRegionFactory: class com.hazelcast.hibernate.HazelcastLocalCacheRegionFactory]`.

<details><summary>Stacktrace:</summary>

```
org.junit.ComparisonFailure: expected:<[10]L> but was:<[9]L>
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at distribution.it@5.3.0-SNAPSHOT/com.hazelcast.it.hibernate.HibernateIT.testInsertLoad(HibernateIT.java:99)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.lang.Thread.run(Thread.java:1589)

```
</details>
<details><summary>Standard output:</summary>

```
Finished Running Test: testInsertLoad[cacheRegionFactory: class com.hazelcast.hibernate.HazelcastCacheRegionFactory] in 4.502 seconds.
Started Running Test: testInsertLoad[cacheRegionFactory: class com.hazelcast.hibernate.HazelcastLocalCacheRegionFactory]
19:50:10,636  WARN |testInsertLoad[cacheRegionFactory: class com.hazelcast.hibernate.HazelcastLocalCacheRegionFactory]| - [pooling] main - HHH10001002: Using Hibernate built-in connection pool (not for production use!)
19:50:10,636  INFO |testInsertLoad[cacheRegionFactory: class com.hazelcast.hibernate.HazelcastLocalCacheRegionFactory]| - [pooling] main - HHH10001005: using driver [org.hsqldb.jdbcDriver] at URL [jdbc:hsqldb:mem:testdb]
19:50:10,637  INFO |testInsertLoad[cacheRegionFactory: class com.hazelcast.hibernate.HazelcastLocalCacheRegionFactory]| - [pooling] main - HHH10001001: Connection properties: {password=****, user=sa}
19:50:10,637  INFO |testInsertLoad[cacheRegionFactory: class com.hazelcast.hibernate.HazelcastLocalCacheRegionFactory]| - [pooling] main - HHH10001003: Autocommit mode: false
19:50:10,637  INFO |testInsertLoad[cacheRegionFactory: class com.hazelcast.hibernate.HazelcastLocalCacheRegionFactory]| - [DriverManagerConnectionProviderImpl] main - HHH000115: Hibernate connection pool size: 2 (min=1)
19:50:10,638  INFO |testInsertLoad[cacheRegionFactory: class com.hazelcast.hibernate.HazelcastLocalCacheRegionFactory]| - [Dialect] main - HHH000400: Using dialect: org.hibernate.dialect.HSQLDialect
19:50:10,646  INFO |testInsertLoad[cacheRegionFactory: class com.hazelcast.hibernate.HazelcastLocalCacheRegionFactory]| - [HazelcastLocalCacheRegionFactory] main - Starting up HazelcastLocalCacheRegionFactory
19:50:10,651  INFO |testInsertLoad[cacheRegionFactory: class com.hazelcast.hibernate.HazelcastLocalCacheRegionFactory]| - [ClientInvocationService] main - hz.client_3 [HibernateIT_b1b08081-3471-4e3c-be13-97a4f04de544] [5.3.0-SNAPSHOT] Running with 2 response threads, dynamic=true
19:50:10,653  INFO |testInsertLoad[cacheRegionFactory: class com.hazelcast.hibernate.HazelcastLocalCacheRegionFactory]| - [LifecycleService] main - hz.client_3 [HibernateIT_b1b08081-3471-4e3c-be13-97a4f04de544] [5.3.0-SNAPSHOT] HazelcastClient 5.3.0-SNAPSHOT (20221105 - 031327e) is STARTING
19:50:10,654  INFO |testInsertLoad[cacheRegionFactory: class com.hazelcast.hibernate.HazelcastLocalCacheRegionFactory]| - [LifecycleService] main - hz.client_3 [HibernateIT_b1b08081-3471-4e3c-be13-97a4f04de544] [5.3.0-SNAPSHOT] HazelcastClient 5.3.0-SNAPSHOT (20221105 - 031327e) is STARTED
19:50:10,656  INFO |testInsertLoad[cacheRegionFactory: class com.hazelcast.hibernate.HazelcastLocalCacheRegionFactory]| - [ClientConnectionManager] main - hz.client_3 [HibernateIT_b1b08081-3471-4e3c-be13-97a4f04de544] [5.3.0-SNAPSHOT] Trying to connect to cluster: HibernateIT_b1b08081-3471-4e3c-be13-97a4f04de544
19:50:10,656  INFO |testInsertLoad[cacheRegionFactory: class com.hazelcast.hibernate.HazelcastLocalCacheRegionFactory]| - [ClientConnectionManager] main - hz.client_3 [HibernateIT_b1b08081-3471-4e3c-be13-97a4f04de544] [5.3.0-SNAPSHOT] Trying to connect to [localhost]:5701
19:50:10,657  WARN |testInsertLoad[cacheRegionFactory: class com.hazelcast.hibernate.HazelcastLocalCacheRegionFactory]| - [ClientConnectionManager] main - hz.client_3 [HibernateIT_b1b08081-3471-4e3c-be13-97a4f04de544] [5.3.0-SNAPSHOT] Exception during initial connection to [localhost]:5701: com.hazelcast.core.HazelcastException: java.io.IOException: Connection refused to address localhost/127.0.0.1:5701
19:50:10,657  INFO |testInsertLoad[cacheRegionFactory: class com.hazelcast.hibernate.HazelcastLocalCacheRegionFactory]| - [ClientConnectionManager] main - hz.client_3 [HibernateIT_b1b08081-3471-4e3c-be13-97a4f04de544] [5.3.0-SNAPSHOT] Trying to connect to [localhost]:5703
19:50:10,657  WARN |testInsertLoad[cacheRegionFactory: class com.hazelcast.hibernate.HazelcastLocalCacheRegionFactory]| - [ClientConnectionManager] main - hz.client_3 [HibernateIT_b1b08081-3471-4e3c-be13-97a4f04de544] [5.3.0-SNAPSHOT] Exception during initial connection to [localhost]:5703: com.hazelcast.core.HazelcastException: java.io.IOException: Connection refused to address localhost/127.0.0.1:5703
19:50:10,657  INFO |testInsertLoad[cacheRegionFactory: class com.hazelcast.hibernate.HazelcastLocalCacheRegionFactory]| - [ClientConnectionManager] main - hz.client_3 [HibernateIT_b1b08081-3471-4e3c-be13-97a4f04de544] [5.3.0-SNAPSHOT] Trying to connect to [localhost]:5702
19:50:10,658  WARN |testInsertLoad[cacheRegionFactory: class com.hazelcast.hibernate.HazelcastLocalCacheRegionFactory]| - [ClientConnectionManager] main - hz.client_3 [HibernateIT_b1b08081-3471-4e3c-be13-97a4f04de544] [5.3.0-SNAPSHOT] Exception during initial connection to [localhost]:5702: com.hazelcast.core.HazelcastException: java.io.IOException: Connection refused to address localhost/127.0.0.1:5702
19:50:10,658  WARN |testInsertLoad[cacheRegionFactory: class com.hazelcast.hibernate.HazelcastLocalCacheRegionFactory]| - [ClientConnectionManager] main - hz.client_3 [HibernateIT_b1b08081-3471-4e3c-be13-97a4f04de544] [5.3.0-SNAPSHOT] Unable to get live cluster connection, retry in 2000 ms, attempt: 1, cluster connect timeout: 2147483647 ms, max backoff: 35000 ms
19:50:12,658  INFO |testInsertLoad[cacheRegionFactory: class com.hazelcast.hibernate.HazelcastLocalCacheRegionFactory]| - [ClientConnectionManager] main - hz.client_3 [HibernateIT_b1b08081-3471-4e3c-be13-97a4f04de544] [5.3.0-SNAPSHOT] Trying to connect to [localhost]:5701
19:50:13,827  INFO |testInsertLoad[cacheRegionFactory: class com.hazelcast.hibernate.HazelcastLocalCacheRegionFactory]| - [LifecycleService] main - hz.client_3 [HibernateIT_b1b08081-3471-4e3c-be13-97a4f04de544] [5.3.0-SNAPSHOT] HazelcastClient 5.3.0-SNAPSHOT (20221105 - 031327e) is CLIENT_CONNECTED
19:50:13,829  INFO |testInsertLoad[cacheRegionFactory: class com.hazelcast.hibernate.HazelcastLocalCacheRegionFactory]| - [ClientConnectionManager] main - hz.client_3 [HibernateIT_b1b08081-3471-4e3c-be13-97a4f04de544] [5.3.0-SNAPSHOT] Authenticated with server [127.0.0.1]:5701:275cae4e-6444-4501-bb7b-3faa892cb232, server version: 5.3.0-SNAPSHOT, local address: /127.0.0.1:41625
19:50:13,834  INFO |testInsertLoad[cacheRegionFactory: class com.hazelcast.hibernate.HazelcastLocalCacheRegionFactory]| - [Diagnostics] main - hz.client_3 [HibernateIT_b1b08081-3471-4e3c-be13-97a4f04de544] [5.3.0-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
19:50:13,836 TRACE |testInsertLoad[cacheRegionFactory: class com.hazelcast.hibernate.HazelcastLocalCacheRegionFactory]| - [ClientListenerService] hz.client_3.internal-1 - hz.client_3 [HibernateIT_b1b08081-3471-4e3c-be13-97a4f04de544] [5.3.0-SNAPSHOT] Register attempt of ClusterViewListenerHandler to ClientConnection{alive=true, connectionId=1, channel=NioChannel{/127.0.0.1:41625->localhost/127.0.0.1:5701}, remoteAddress=[127.0.0.1]:5701, lastReadTime=2022-11-05 19:50:13.825, lastWriteTime=2022-11-05 19:50:13.786, closedTime=never, connected server version=null}
19:50:13,881  INFO |testInsertLoad[cacheRegionFactory: class com.hazelcast.hibernate.HazelcastLocalCacheRegionFactory]| - [ClientClusterService] hz.client_3.event-11 - hz.client_3 [HibernateIT_b1b08081-3471-4e3c-be13-97a4f04de544] [5.3.0-SNAPSHOT] 

Members [1] {
	Member [127.0.0.1]:5701 - 275cae4e-6444-4501-bb7b-3faa892cb232
}

19:50:13,893 TRACE |testInsertLoad[cacheRegionFactory: class com.hazelcast.hibernate.HazelcastLocalCacheRegionFactory]| - [ClientListenerService] ForkJoinPool.commonPool-worker-1 - hz.client_3 [HibernateIT_b1b08081-3471-4e3c-be13-97a4f04de544] [5.3.0-SNAPSHOT] Registered ClusterViewListenerHandler to ClientConnection{alive=true, connectionId=1, channel=NioChannel{/127.0.0.1:41625->localhost/127.0.0.1:5701}, remoteAddress=[127.0.0.1]:5701, lastReadTime=2022-11-05 19:50:13.887, lastWriteTime=2022-11-05 19:50:13.837, closedTime=never, connected server version=null}
19:50:13,903 TRACE |testInsertLoad[cacheRegionFactory: class com.hazelcast.hibernate.HazelcastLocalCacheRegionFactory]| - [ClientListenerService] hz.client_3.eventRegistration- - hz.client_3 [HibernateIT_b1b08081-3471-4e3c-be13-97a4f04de544] [5.3.0-SNAPSHOT] Register attempt of ClientListenerRegistration{codec=com.hazelcast.client.impl.spi.impl.ClientInvocationServiceImpl$1@62b5150f, handler=com.hazelcast.client.impl.spi.impl.ClientInvocationServiceImpl$BackupEventHandler@343b7a6f} to ClientConnection{alive=true, connectionId=1, channel=NioChannel{/127.0.0.1:41625->localhost/127.0.0.1:5701}, remoteAddress=[127.0.0.1]:5701, lastReadTime=2022-11-05 19:50:13.887, lastWriteTime=2022-11-05 19:50:13.837, closedTime=never, connected server version=null}
19:50:13,924 TRACE |testInsertLoad[cacheRegionFactory: class com.hazelcast.hibernate.HazelcastLocalCacheRegionFactory]| - [ClientListenerService] hz.client_3.eventRegistration- - hz.client_3 [HibernateIT_b1b08081-3471-4e3c-be13-97a4f04de544] [5.3.0-SNAPSHOT] Registered ClientListenerRegistration{codec=com.hazelcast.client.impl.spi.impl.ClientInvocationServiceImpl$1@62b5150f, handler=com.hazelcast.client.impl.spi.impl.ClientInvocationServiceImpl$BackupEventHandler@343b7a6f} to ClientConnection{alive=true, connectionId=1, channel=NioChannel{/127.0.0.1:41625->localhost/127.0.0.1:5701}, remoteAddress=[127.0.0.1]:5701, lastReadTime=2022-11-05 19:50:13.923, lastWriteTime=2022-11-05 19:50:13.906, closedTime=never, connected server version=null}
19:50:13,924  INFO |testInsertLoad[cacheRegionFactory: class com.hazelcast.hibernate.HazelcastLocalCacheRegionFactory]| - [ClientStatisticsService] main - Client statistics is enabled with period 5 seconds.
19:50:13,941 TRACE |testInsertLoad[cacheRegionFactory: class com.hazelcast.hibernate.HazelcastLocalCacheRegionFactory]| - [ClientListenerService] hz.client_3.eventRegistration- - hz.client_3 [HibernateIT_b1b08081-3471-4e3c-be13-97a4f04de544] [5.3.0-SNAPSHOT] Register attempt of ClientListenerRegistration{codec=com.hazelcast.client.impl.proxy.ClientTopicProxy$Codec@14467db6, handler=com.hazelcast.client.impl.proxy.ClientTopicProxy$TopicItemHandler@4af045f4} to ClientConnection{alive=true, connectionId=1, channel=NioChannel{/127.0.0.1:41625->localhost/127.0.0.1:5701}, remoteAddress=[127.0.0.1]:5701, lastReadTime=2022-11-05 19:50:13.939, lastWriteTime=2022-11-05 19:50:13.936, closedTime=never, connected server version=null}
19:50:13,944 TRACE |testInsertLoad[cacheRegionFactory: class com.hazelcast.hibernate.HazelcastLocalCacheRegionFactory]| - [ClientListenerService] hz.client_3.eventRegistration- - hz.client_3 [HibernateIT_b1b08081-3471-4e3c-be13-97a4f04de544] [5.3.0-SNAPSHOT] Registered ClientListenerRegistration{codec=com.hazelcast.client.impl.proxy.ClientTopicProxy$Codec@14467db6, handler=com.hazelcast.client.impl.proxy.ClientTopicProxy$TopicItemHandler@4af045f4} to ClientConnection{alive=true, connectionId=1, channel=NioChannel{/127.0.0.1:41625->localhost/127.0.0.1:5701}, remoteAddress=[127.0.0.1]:5701, lastReadTime=2022-11-05 19:50:13.944, lastWriteTime=2022-11-05 19:50:13.941, closedTime=never, connected server version=null}
19:50:13,947 TRACE |testInsertLoad[cacheRegionFactory: class com.hazelcast.hibernate.HazelcastLocalCacheRegionFactory]| - [ClientListenerService] hz.client_3.eventRegistration- - hz.client_3 [HibernateIT_b1b08081-3471-4e3c-be13-97a4f04de544] [5.3.0-SNAPSHOT] Register attempt of ClientListenerRegistration{codec=com.hazelcast.client.impl.proxy.ClientTopicProxy$Codec@6c9dfe5c, handler=com.hazelcast.client.impl.proxy.ClientTopicProxy$TopicItemHandler@1bee67ec} to ClientConnection{alive=true, connectionId=1, channel=NioChannel{/127.0.0.1:41625->localhost/127.0.0.1:5701}, remoteAddress=[127.0.0.1]:5701, lastReadTime=2022-11-05 19:50:13.947, lastWriteTime=2022-11-05 19:50:13.946, closedTime=never, connected server version=null}
19:50:13,948 TRACE |testInsertLoad[cacheRegionFactory: class com.hazelcast.hibernate.HazelcastLocalCacheRegionFactory]| - [ClientListenerService] hz.client_3.eventRegistration- - hz.client_3 [HibernateIT_b1b08081-3471-4e3c-be13-97a4f04de544] [5.3.0-SNAPSHOT] Registered ClientListenerRegistration{codec=com.hazelcast.client.impl.proxy.ClientTopicProxy$Codec@6c9dfe5c, handler=com.hazelcast.client.impl.proxy.ClientTopicProxy$TopicItemHandler@1bee67ec} to ClientConnection{alive=true, connectionId=1, channel=NioChannel{/127.0.0.1:41625->localhost/127.0.0.1:5701}, remoteAddress=[127.0.0.1]:5701, lastReadTime=2022-11-05 19:50:13.948, lastWriteTime=2022-11-05 19:50:13.947, closedTime=never, connected server version=null}
19:50:13,959 TRACE |testInsertLoad[cacheRegionFactory: class com.hazelcast.hibernate.HazelcastLocalCacheRegionFactory]| - [ClientListenerService] hz.client_3.eventRegistration- - hz.client_3 [HibernateIT_b1b08081-3471-4e3c-be13-97a4f04de544] [5.3.0-SNAPSHOT] Register attempt of ClientListenerRegistration{codec=com.hazelcast.client.impl.proxy.ClientTopicProxy$Codec@3c6212ea, handler=com.hazelcast.client.impl.proxy.ClientTopicProxy$TopicItemHandler@74f53f77} to ClientConnection{alive=true, connectionId=1, channel=NioChannel{/127.0.0.1:41625->localhost/127.0.0.1:5701}, remoteAddress=[127.0.0.1]:5701, lastReadTime=2022-11-05 19:50:13.959, lastWriteTime=2022-11-05 19:50:13.954, closedTime=never, connected server version=null}
19:50:13,960 TRACE |testInsertLoad[cacheRegionFactory: class com.hazelcast.hibernate.HazelcastLocalCacheRegionFactory]| - [ClientListenerService] hz.client_3.eventRegistration- - hz.client_3 [HibernateIT_b1b08081-3471-4e3c-be13-97a4f04de544] [5.3.0-SNAPSHOT] Registered ClientListenerRegistration{codec=com.hazelcast.client.impl.proxy.ClientTopicProxy$Codec@3c6212ea, handler=com.hazelcast.client.impl.proxy.ClientTopicProxy$TopicItemHandler@74f53f77} to ClientConnection{alive=true, connectionId=1, channel=NioChannel{/127.0.0.1:41625->localhost/127.0.0.1:5701}, remoteAddress=[127.0.0.1]:5701, lastReadTime=2022-11-05 19:50:13.960, lastWriteTime=2022-11-05 19:50:13.959, closedTime=never, connected server version=null}
Hibernate: drop table ANNOTATED_ENTITIES if exists
19:50:13,973  INFO |testInsertLoad[cacheRegionFactory: class com.hazelcast.hibernate.HazelcastLocalCacheRegionFactory]| - [access] main - HHH10001501: Connection obtained from JdbcConnectionAccess [org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator$ConnectionProviderJdbcConnectionAccess@28e48b65] for (non-JTA) DDL execution was not in auto-commit mode; the Connection 'local transaction' will be committed and the Connection will be set into auto-commit mode.
Hibernate: create table ANNOTATED_ENTITIES (id bigint not null, title varchar(255), primary key (id))
19:50:13,974  INFO |testInsertLoad[cacheRegionFactory: class com.hazelcast.hibernate.HazelcastLocalCacheRegionFactory]| - [access] main - HHH10001501: Connection obtained from JdbcConnectionAccess [org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator$ConnectionProviderJdbcConnectionAccess@6cde0c69] for (non-JTA) DDL execution was not in auto-commit mode; the Connection 'local transaction' will be committed and the Connection will be set into auto-commit mode.
Hibernate: alter table ANNOTATED_ENTITIES add constraint UK_i39a1dcevg71h47myxau8936s unique (title)
19:50:13,975  INFO |testInsertLoad[cacheRegionFactory: class com.hazelcast.hibernate.HazelcastLocalCacheRegionFactory]| - [SchemaCreatorImpl] main - HHH000476: Executing import script 'org.hibernate.tool.schema.internal.exec.ScriptSourceInputNonExistentImpl@3eee08f5'
Hibernate: select max(id) from ANNOTATED_ENTITIES
Hibernate: insert into ANNOTATED_ENTITIES (title, id) values (?, ?)
Hibernate: select annotatede0_.id as id1_0_0_, annotatede0_.title as title2_0_0_ from ANNOTATED_ENTITIES annotatede0_ where annotatede0_.id=?
19:50:13,998 ERROR |testInsertLoad[cacheRegionFactory: class com.hazelcast.hibernate.HazelcastLocalCacheRegionFactory]| - [ClientListenerService] hz.client_3.event-14 - hz.client_3 [HibernateIT_b1b08081-3471-4e3c-be13-97a4f04de544] [5.3.0-SNAPSHOT] hz.client_3.event-14 caught an exception while processing:com.hazelcast.client.impl.spi.impl.listener.ClientListenerServiceImpl$ClientEventProcessor@662bca3b
java.lang.UnsupportedOperationException: Client has no local member!
	at com.hazelcast.client.impl.proxy.ClientClusterProxy.getLocalMember(ClientClusterProxy.java:69) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.hibernate.local.LocalRegionCache.lambda$createMessageListener$0(LocalRegionCache.java:252) ~[hazelcast-hibernate53-2.2.1.jar:2.2.1]
	at com.hazelcast.client.impl.proxy.ClientTopicProxy$TopicItemHandler.handleTopicEvent(ClientTopicProxy.java:132) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.client.impl.protocol.codec.TopicAddMessageListenerCodec$AbstractEventHandler.handle(TopicAddMessageListenerCodec.java:139) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.client.impl.proxy.ClientTopicProxy$TopicItemHandler.handle(ClientTopicProxy.java:120) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.client.impl.spi.impl.listener.ClientListenerServiceImpl.handleEventMessageOnCallingThread(ClientListenerServiceImpl.java:190) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.client.impl.spi.impl.listener.ClientListenerServiceImpl$ClientEventProcessor.run(ClientListenerServiceImpl.java:361) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.internal.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:245) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.internal.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:228) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
19:50:14,005 ERROR |testInsertLoad[cacheRegionFactory: class com.hazelcast.hibernate.HazelcastLocalCacheRegionFactory]| - [ClientListenerService] hz.client_3.event-14 - hz.client_3 [HibernateIT_b1b08081-3471-4e3c-be13-97a4f04de544] [5.3.0-SNAPSHOT] hz.client_3.event-14 caught an exception while processing:com.hazelcast.client.impl.spi.impl.listener.ClientListenerServiceImpl$ClientEventProcessor@24b973d1
java.lang.UnsupportedOperationException: Client has no local member!
	at com.hazelcast.client.impl.proxy.ClientClusterProxy.getLocalMember(ClientClusterProxy.java:69) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.hibernate.local.LocalRegionCache.lambda$createMessageListener$0(LocalRegionCache.java:252) ~[hazelcast-hibernate53-2.2.1.jar:2.2.1]
	at com.hazelcast.client.impl.proxy.ClientTopicProxy$TopicItemHandler.handleTopicEvent(ClientTopicProxy.java:132) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.client.impl.protocol.codec.TopicAddMessageListenerCodec$AbstractEventHandler.handle(TopicAddMessageListenerCodec.java:139) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.client.impl.proxy.ClientTopicProxy$TopicItemHandler.handle(ClientTopicProxy.java:120) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.client.impl.spi.impl.listener.ClientListenerServiceImpl.handleEventMessageOnCallingThread(ClientListenerServiceImpl.java:190) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.client.impl.spi.impl.listener.ClientListenerServiceImpl$ClientEventProcessor.run(ClientListenerServiceImpl.java:361) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.internal.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:245) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.internal.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:228) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
19:50:14,085  INFO |testInsertLoad[cacheRegionFactory: class com.hazelcast.hibernate.HazelcastLocalCacheRegionFactory]| - [SchemaDropperImpl$DelayedDropActionImpl] main - HHH000477: Starting delayed evictData of schema as part of SessionFactory shut-down'
Hibernate: drop table ANNOTATED_ENTITIES if exists
19:50:14,086  INFO |testInsertLoad[cacheRegionFactory: class com.hazelcast.hibernate.HazelcastLocalCacheRegionFactory]| - [access] main - HHH10001501: Connection obtained from JdbcConnectionAccess [org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator$ConnectionProviderJdbcConnectionAccess@457692cb] for (non-JTA) DDL execution was not in auto-commit mode; the Connection 'local transaction' will be committed and the Connection will be set into auto-commit mode.
19:50:14,086  INFO |testInsertLoad[cacheRegionFactory: class com.hazelcast.hibernate.HazelcastLocalCacheRegionFactory]| - [pooling] main - HHH10001008: Cleaning up connection pool [jdbc:hsqldb:mem:testdb]
19:50:14,088  INFO |testInsertLoad[cacheRegionFactory: class com.hazelcast.hibernate.HazelcastLocalCacheRegionFactory]| - [HazelcastLocalCacheRegionFactory] main - Shutting down HazelcastLocalCacheRegionFactory
19:50:14,088  INFO |testInsertLoad[cacheRegionFactory: class com.hazelcast.hibernate.HazelcastLocalCacheRegionFactory]| - [LifecycleService] main - hz.client_3 [HibernateIT_b1b08081-3471-4e3c-be13-97a4f04de544] [5.3.0-SNAPSHOT] HazelcastClient 5.3.0-SNAPSHOT (20221105 - 031327e) is SHUTTING_DOWN
19:50:14,090  INFO |testInsertLoad[cacheRegionFactory: class com.hazelcast.hibernate.HazelcastLocalCacheRegionFactory]| - [ClientConnectionManager] main - hz.client_3 [HibernateIT_b1b08081-3471-4e3c-be13-97a4f04de544] [5.3.0-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5701:275cae4e-6444-4501-bb7b-3faa892cb232, connection: ClientConnection{alive=false, connectionId=1, channel=NioChannel{/127.0.0.1:41625->localhost/127.0.0.1:5701}, remoteAddress=[127.0.0.1]:5701, lastReadTime=2022-11-05 19:50:14.087, lastWriteTime=2022-11-05 19:50:14.087, closedTime=2022-11-05 19:50:14.088, connected server version=null}
19:50:14,090  INFO |testInsertLoad[cacheRegionFactory: class com.hazelcast.hibernate.HazelcastLocalCacheRegionFactory]| - [LifecycleService] main - hz.client_3 [HibernateIT_b1b08081-3471-4e3c-be13-97a4f04de544] [5.3.0-SNAPSHOT] HazelcastClient 5.3.0-SNAPSHOT (20221105 - 031327e) is CLIENT_DISCONNECTED
19:50:14,092  INFO |testInsertLoad[cacheRegionFactory: class com.hazelcast.hibernate.HazelcastLocalCacheRegionFactory]| - [LifecycleService] main - hz.client_3 [HibernateIT_b1b08081-3471-4e3c-be13-97a4f04de544] [5.3.0-SNAPSHOT] HazelcastClient 5.3.0-SNAPSHOT (20221105 - 031327e) is SHUTDOWN
19:50:14,092  INFO |testInsertLoad[cacheRegionFactory: class com.hazelcast.hibernate.HazelcastLocalCacheRegionFactory]| - [HibernateIT] main - Destroying Hazelcast process
BuildInfo right after testInsertLoad[cacheRegionFactory: class com.hazelcast.hibernate.HazelcastLocalCacheRegionFactory](com.hazelcast.it.hibernate.HibernateIT): BuildInfo{version='5.3.0-SNAPSHOT', build='20221105', buildNumber=20221105, revision=031327e, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'testInsertLoad[cacheRegionFactory: class com.hazelcast.hibernate.HazelcastLocalCacheRegionFactory](com.hazelcast.it.hibernate.HibernateIT):'
19:50:10, accumulated pauses: 106 ms, max pause: 58 ms, pauses over 1000 ms: 0


No metrics recorded during the test

```
</details>

**Comment by ldziedziul** [comment]
Maybe related to https://github.com/hazelcast/hazelcast-hibernate/issues/328 ?

**Comment by Patras3** [comment]
Reopening as issue occurred again on:
* _5.2.z_ (commit 2e7e17f5cd4dd20dcff4df4af82c989f2feafe43)
with IbmJDK8-nightly: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-IbmJDK8-nightly/60/testReport/junit/com.hazelcast.it.hibernate/HibernateIT/
* _master_ (commit 4b12ab0342a9f2844e653a55eea2d3b47edb02df)
with OpenJDK19: https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK19-nightly/5/testReport/junit/com.hazelcast.it.hibernate/HibernateIT/
