### ISSUE TITLE
Various exceptions when using GenericMapStore show as UndefinedErrorCodeException on the client-side [HZ-1737]

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hazelcast#22740]
**Describe the bug**
In some cases, if there is a server-side exception when using a map w/ a `GenericMapStore`, on the client-side the exception is observed as `com.hazelcast.client.UndefinedErrorCodeException`:

```
Exception in thread "main" com.hazelcast.client.UndefinedErrorCodeException: Class name: com.hazelcast.sql.HazelcastSqlException, Message: Object '__map-store.people' not found, did you forget to CREATE MAPPING?
        at com.hazelcast.client.UndefinedErrorCodeException.wrap(UndefinedErrorCodeException.java:64)
        at com.hazelcast.client.UndefinedErrorCodeException.wrap(UndefinedErrorCodeException.java:34)
        at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.returnOrThrowWithGetConventions(InvocationFuture.java:110)
        at com.hazelcast.client.impl.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:95)
        at com.hazelcast.client.impl.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:40)
        at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:617)
        at com.hazelcast.client.impl.spi.ClientProxy.invokeOnPartition(ClientProxy.java:188)
        at com.hazelcast.client.impl.spi.ClientProxy.invoke(ClientProxy.java:182)
        at com.hazelcast.client.impl.proxy.ClientMapProxy.putInternal(ClientMapProxy.java:537)
        at com.hazelcast.client.impl.proxy.ClientMapProxy.put(ClientMapProxy.java:269)
        at com.qe.TimerClient.main(TimerClient.java:109)
```

Also see #22567

**Expected behavior**
A defined exception should be thrown such as `com.hazelcast.sql.HazelcastSqlException`, which can be handled accordingly by the user.

**To Reproduce**

To reproduce the behavior, perform steps described in #22567 or the following:

1. Start a member with a map configured w/ `GenericMapStore` and a corresponding `external-data-store`
2. Trigger map loading with `map.loadAll()` or some other method so that the internal `__map-store.<map-name>` mapping is created
3. Via SQL, drop the internal mapping (i.e. `DROP MAPPING "__map-store.myMap"`)
4. From a HZ client, perform `map.put()` or some other op to trigger `GenericMapStore` method
5. Observe `UndefinedErrorCodeException` on the client-side

**Additional context**

The following JUnit test also captures the behavior. It can be added to `com.hazelcast.mapstore.GenericMapStoreIntegrationTest`

```
    @Test
    public void testPutWhenInternalMappingDropped() {
        HazelcastInstance client = client();
        IMap<Integer, Person> map = client.getMap(tableName);
        map.loadAll(false);

        execute("DROP MAPPING \"__map-store." + tableName + "\"");
        assertThatThrownBy(() -> map.put(42, new Person(42, "name-42")))
                .isInstanceOf(HazelcastSqlException.class)
                .hasMessageContaining("did you forget to CREATE MAPPING?");
        assertThat(map.size()).isEqualTo(1);
    }
```

**Comment by sumnerib** [comment]
Please un-ignore the following test when fixing this issue: https://github.com/hazelcast/hazelcast/blob/1103c1eb49cf67f3db610fdec12450f1efde86e1/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreIntegrationTest.java#L314
