### ISSUE TITLE
com.hazelcast.datastore.JdbcDataStoreFactoryTest and com.hazelcast.datastore.impl.ExternalDataStoreServiceImplTest [HZ-1746]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#22747]
_master_ (commit fc4c03a51be9af8410bb9e4871c45a019e316bfb)

Failed on oracle-11 (sonar build): 
- https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/1386/testReport/com.hazelcast.datastore/JdbcDataStoreFactoryTest/
- https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/1386/testReport/com.hazelcast.datastore.impl/ExternalDataStoreServiceImplTest/

All tests in `com.hazelcast.datastore.JdbcDataStoreFactoryTest` and `com.hazelcast.datastore.impl.ExternalDataStoreServiceImplTest` failed with the same exception.

<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: Expecting no elements of:  <[Thread[pool-19538-thread-3,5,main],    Thread[Catalina-utility-2,1,main],    Thread[d75892e3-33a2-4b45-a985-2cdcc567c03e1,5,main],    Thread[pool-20500-thread-9,5,main],    Thread[pool-19883-thread-2,5,main],    Thread[pool-20456-thread-10,5,main],    Thread[pool-20456-thread-1,5,main],    Thread[pool-20500-thread-5,5,main],    Thread[ForkJoinPool.commonPool-worker-37,5,main],    Thread[pool-21345-thread-2,5,main],    Thread[hz.determined_chebyshev.async.thread-2,5,main],    Thread[hz.sad_agnesi.async.thread-8,5,main],    Thread[hz.silly_agnesi.async.thread-3,5,main],    Thread[hz.nostalgic_nash.async.thread-6,5,main],    Thread[pool-18311-thread-2,5,main],    Thread[pool-1626-thread-1,5,main],    Thread[pool-2617-thread-1,5,main],    Thread[FileSystemWatchService,5,main],    Thread[Thread-54630,5,main],    Thread[hz.sad_agnesi.async.thread-6,5,main],    Thread[hz.priceless_agnesi.async.thread-2,5,main],    Thread[pool-19881-thread-1,5,main],    Thread[hz.priceless_agnesi.async.thread-5,5,main],    Thread[hz.sleepy_matsumoto.async.thread-4,5,main],    Thread[hz.silly_agnesi.async.thread-1,5,main],    Thread[pool-20499-thread-7,5,main],    Thread[Finalizer,8,system],    Thread[pool-19880-thread-2,5,main],    Thread[pool-20494-thread-1,5,main],    Thread[pool-11667-thread-2,5,main],    Thread[Thread-78225,5,main],    Thread[FileSystemWatchService,5,main],    Thread[pool-20456-thread-4,5,main],    Thread[FileSystemWatchService,5,main],    Thread[pool-19883-thread-1,5,main],    Thread[pool-20499-thread-3,5,main],    Thread[process reaper,10,system],    hz.hz.client_413.IO.thread-out-0,    Thread[pool-20456-thread-5,5,main],    Thread[hz.modest_bhabha.async.thread-3,5,main],    Thread[pool-15628-thread-4,5,main],    Thread[pool-20500-thread-4,5,main],    Thread[ForkJoinPool.commonPool-worker-43,5,main],    Thread[pool-20500-thread-2,5,main],    Thread[hz.nostalgic_nash.async.thread-1,5,main],    Thread[pool-15628-thread-10,5,main],    Thread[Catalina-utility-1,1,main],    Thread[pool-20499-thread-4,5,main],    Thread[pool-15628-thread-2,5,main],    Thread[pool-20492-thread-1,5,main],    Thread[hz.sad_agnesi.async.thread-4,5,main],    Thread[hz.sleepy_matsumoto.async.thread-5,5,main],    Thread[pool-4277-thread-1,5,main],    Thread[pool-5130-thread-1,5,main],    Thread[pool-20491-thread-1,5,main],    Thread[FileSystemWatchService,5,main],    Thread[pool-20488-thread-1,5,main],    Thread[pool-1960-thread-1,5,main],    Thread[main,5,main],    Thread[pool-19538-thread-5,5,main],    Thread[FileSystemWatchService,5,main],    Thread[hz.client_413-NioNetworking-closeListenerExecutor,5,main],    Thread[pool-15628-thread-9,5,main],    Thread[FileSystemWatchService,5,main],    Thread[hz.nifty_robinson.async.thread-6,5,main],    Thread[hz.determined_chebyshev.async.thread-1,5,main],    Thread[pool-20496-thread-1,5,main],    Thread[pool-19538-thread-4,5,main],    Thread[pool-19882-thread-1,5,main],    Thread[hz.thirsty_cerf.async.thread-4,5,main],    Thread[Thread-78226,5,main],    Thread[pool-19880-thread-1,5,main],    Thread[HikariPool-3 housekeeper,5,main],    Thread[pool-2087-thread-1,5,main],    Thread[FileSystemWatchService,5,main],    Thread[Thread-25787,5,main],    Thread[pool-15628-thread-6,5,main],    Thread[pool-4916-thread-1,5,main],    Thread[HikariPool-3 connection adder,5,main],    Thread[pool-20456-thread-9,5,main],    Thread[pool-19538-thread-1,5,main],    Thread[pool-13027-thread-1,5,main],    Thread[pool-20501-thread-1,5,main],    Thread[hz.modest_bhabha.async.thread-8,5,main],    Thread[pool-11667-thread-5,5,main],    Thread[-66954,5,main],    Thread[pool-20499-thread-9,5,main],    Thread[hz.adoring_lamport.async.thread-4,5,main],    Thread[pool-20456-thread-7,5,main],    Thread[pool-20456-thread-8,5,main],    Thread[Common-Cleaner,8,InnocuousThreadGroup],    Thread[pool-20456-thread-6,5,main],    Thread[pool-20500-thread-8,5,main],    Thread[64525d90-20ca-431f-af95-e95416e188ae1,5,main],    Thread[hz.determined_chebyshev.async.thread-3,5,main],    Thread[pool-20489-thread-1,5,main],    Thread[hz.determined_chebyshev.async.thread-5,5,main],    Thread[pool-19538-thread-6,5,main],    Thread[JNA Cleaner,5,main],    Thread[pool-4855-thread-1,5,main],    Thread[hz.modest_cerf.async.thread-4,5,main],    Thread[pool-4632-thread-1,5,main],    Thread[hz.nostalgic_nash.async.thread-5,5,main],    Thread[hz.stoic_matsumoto.async.thread-1,5,main],    Thread[pool-21345-thread-3,5,main],    Thread[FileSystemWatchService,5,main],    Thread[pool-20495-thread-1,5,main],    Thread[pool-20497-thread-1,5,main],    Thread[pool-2248-thread-1,5,main],    Thread[hz.trusting_williamson.async.thread-7,5,main],    Thread[hz.nifty_blackwell.async.thread-5,5,main],    Thread[pool-20499-thread-10,5,main],    Thread[pool-2466-thread-1,5,main],    Thread[ForkJoinPool.commonPool-worker-23,5,main],    Thread[pool-1773-thread-1,5,main],    Thread[hz.reverent_yonath.async.thread-2,5,main],    Thread[pool-20493-thread-1,5,main],    Thread[pool-19885-thread-1,5,main],    Thread[pool-20499-thread-2,5,main],    hz.hz.client_413.IO.thread-in-0,    Thread[JitterThread,5,main],    Thread[pool-11667-thread-4,5,main],    Thread[pool-15628-thread-1,5,main],    Thread[pool-19879-thread-1,5,main],    Thread[-66953,5,main],    Thread[-66956,5,main],    Thread[ForkJoinPool.commonPool-worker-55,5,main],    Thread[pool-19885-thread-2,5,main],    Thread[hz.friendly_hofstadter.async.thread-2,5,main],    Thread[pool-20498-thread-1,5,main],    Thread[pool-20500-thread-10,5,main],    Thread[testcontainers-ryuk,5,testcontainers],    Thread[pool-1601-thread-1,5,main],    Thread[hz.stoic_matsumoto.async.thread-2,5,main],    Thread[Thread-78223,5,main],    Thread[pool-21345-thread-5,5,main],    Thread[pool-19538-thread-2,5,main],    Thread[hz.reverent_yonath.async.thread-3,5,main],    Thread[Thread-70198,5,main],    Thread[FileSystemWatchService,5,main],    hz.hz.client_412.IO.thread-out-0,    Thread[hz.silly_agnesi.async.thread-8,5,main],    Thread[hz.stoic_matsumoto.async.thread-3,5,main],    Thread[hz.sad_agnesi.async.thread-5,5,main],    Thread[pool-15628-thread-8,5,main],    Thread[pool-5233-thread-1,5,main],    Thread[pool-19882-thread-2,5,main],    Thread[pool-18044-thread-1,5,main],    Thread[hz.priceless_agnesi.async.thread-1,5,main],    Thread[pool-5404-thread-1,5,main],    Thread[pool-20500-thread-3,5,main],    Thread[pool-20499-thread-6,5,main],    Thread[hz.modest_bhabha.async.thread-1,5,main],    Thread[pool-12996-thread-1,5,main],    Thread[hz.modest_carver.async.thread-4,5,main],    hz.hz.client_414.IO.thread-in-0,    Thread[hz.client_413.internal-1,5,main],    Thread[hz.sad_agnesi.async.thread-7,5,main],    Thread[hz.determined_chebyshev.async.thread-4,5,main],    Thread[pool-15628-thread-7,5,main],    Thread[pool-5605-thread-1,5,main],    Thread[Thread-54540,5,main],    Thread[pool-19538-thread-7,5,main],    Thread[pool-18034-thread-1,5,main],    Thread[pool-20456-thread-2,5,main],    Thread[hz.sleepy_matsumoto.async.thread-3,5,main],    Thread[hz.stoic_matsumoto.async.thread-4,5,main],    Thread[pool-21345-thread-4,5,main],    Thread[hz.keen_stonebraker.async.thread-2,5,main],    Thread[pool-15628-thread-5,5,main],    Thread[hz.trusting_williamson.async.thread-6,5,main],    Thread[hz.client_415.internal-1,5,main],    Thread[surefire-forkedjvm-ping-30s,5,main],    Thread[hz.priceless_agnesi.async.thread-4,5,main],    hz.hz.client_415.IO.thread-out-0,    Thread[hz.priceless_agnesi.async.thread-3,5,main],    Thread[hz.reverent_yonath.async.thread-1,5,main],    Thread[hz.client_415-NioNetworking-closeListenerExecutor,5,main],    Thread[pool-21345-thread-1,5,main],    Thread[pool-19879-thread-2,5,main],    Thread[pool-2291-thread-1,5,main],    Thread[pool-20500-thread-1,5,main],    Thread[pool-20490-thread-1,5,main],    Thread[pool-11667-thread-3,5,main],    Thread[pool-11667-thread-1,5,main],    Thread[pool-19881-thread-2,5,main],    Thread[hz.silly_agnesi.async.thread-6,5,main],    Thread[pool-20500-thread-7,5,main],    Thread[pool-19538-thread-8,5,main],    Thread[Thread-78227,5,main],    Thread[pool-19884-thread-1,5,main],    Thread[43c4cf25-0065-4722-9c1d-5a7bf75cf06a1,5,main],    Thread[pool-20499-thread-5,5,main],    Thread[hz.dreamy_nash.async.thread-5,5,main],    Thread[Signal Dispatcher,9,system],    hz.hz.client_412.IO.thread-in-0,    Thread[Thread-78224,5,main],    Thread[hz.sleepy_matsumoto.async.thread-2,5,main],    hz.hz.client_415.IO.thread-in-0,    Thread[pool-20499-thread-1,5,main],    Thread[hz.sad_agnesi.async.thread-1,5,main],    Thread[pool-20456-thread-3,5,main],    Thread[Reference Handler,10,system],    Thread[pool-19884-thread-2,5,main],    Thread[hz.sad_agnesi.async.thread-3,5,main],    Thread[hz.sleepy_matsumoto.async.thread-1,5,main],    Thread[pool-20499-thread-8,5,main],    Thread[hz.keen_williamson.async.thread-7,5,main],    Thread[-66952,5,main],    Thread[pool-18048-thread-1,5,main],    Thread[pool-15628-thread-3,5,main],    Thread[ForkJoinPool.commonPool-worker-63,5,main],    hz.hz.client_414.IO.thread-out-0,    Thread[pool-20500-thread-6,5,main],    Thread[Thread-25823,5,main],    Thread[pool-18311-thread-1,5,main],    Thread[-66955,5,main],    Thread[pool-4132-thread-1,5,main],    Thread[pool-3943-thread-1,5,main]]>to match given predicate but this element did:  <Thread[HikariPool-3 housekeeper,5,main]>	at java.base/java.util.Optional.ifPresent(Optional.java:183)	at com.hazelcast.datastore.JdbcDataStoreFactoryTest.lambda$tearDown$1(JdbcDataStoreFactoryTest.java:51)	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1236)	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1258)	at com.hazelcast.datastore.JdbcDataStoreFactoryTest.tearDown(JdbcDataStoreFactoryTest.java:51)	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)	at java.base/java.lang.reflect.Method.invoke(Method.java:566)	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)	at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:381)	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)	at com.hazelcast.test.HazelcastParallelClassRunner.access$301(HazelcastParallelClassRunner.java:49)	at com.hazelcast.test.HazelcastParallelClassRunner$TestRunner.run(HazelcastParallelClassRunner.java:162)	at java.base/java.lang.Thread.run(Thread.java:834)
```
</details>
<details><summary>Standard output:</summary>

```
Started Running Test: should_return_closing_datastore_when_not_shared
Started Running Test: should_return_same_datastore_when_shared
Started Running Test: should_NOT_return_closing_datastore_when_shared
Started Running Test: should_close_shared_datasource_on_close

```
</details>

**Comment by olukas** [comment]
Failed again on _master_ with oracle-11 (sonar build): 
- https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/1389/testReport/com.hazelcast.datastore/JdbcDataStoreFactoryTest/
- https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/1389/testReport/com.hazelcast.datastore.impl/ExternalDataStoreServiceImplTest/

**Comment by sumnerib** [comment]
Failed again on _master_ with oracle-11 (sonar build): 

- https://jenkins.hazelcast.com/job/Hazelcast-master-sonar/1398/testReport/junit/com.hazelcast.datastore/JdbcDataStoreFactoryTest
- https://jenkins.hazelcast.com/job/Hazelcast-master-sonar/1398/testReport/junit/com.hazelcast.datastore.impl/ExternalDataStoreServiceImplTest

**Comment by olukas** [comment]
Failed again on _master_ with oracle-11 (sonar build): 
- https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/1401/testReport/com.hazelcast.datastore/JdbcDataStoreFactoryTest/
- https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/1401/testReport/com.hazelcast.datastore.impl/ExternalDataStoreServiceImplTest/
