### ISSUE TITLE
com.hazelcast.mapstore.GenericMapStoreTest.givenRow_whenStore_thenRowIsUpdated

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#22758]
_5.2.z_ (commit 120772354180e55cd461797f5d874635e1108264)

Failed on oracle-11 (sonar build): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-sonar/369/testReport/com.hazelcast.mapstore/GenericMapStoreTest/givenRow_whenStore_thenRowIsUpdated/
<details><summary>Stacktrace:</summary>

It can be related to https://github.com/hazelcast/hazelcast/issues/22205.

```
com.hazelcast.core.HazelcastException: MapStore init for map: people_o_23766c61_a1b4_4d4d_a863_2c5f67c4a17a timed out after 5000 ms
	at com.hazelcast.mapstore.GenericMapStore.awaitInitFinished(GenericMapStore.java:541)
	at com.hazelcast.mapstore.GenericMapStore.store(GenericMapStore.java:422)
	at com.hazelcast.mapstore.GenericMapStoreTest.givenRow_whenStore_thenRowIsUpdated(GenericMapStoreTest.java:427)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)

```
</details>
<details><summary>Standard output:</summary>

```
07:17:11,817  WARN || - [HazelcastInstanceFactory] Time-limited test - WARNING: Classpath misconfiguration: found multiple META-INF/services/com.hazelcast.instance.impl.NodeExtension resources: jar:file:/home/jenkins/jenkins_slave/workspace/Hazelcast-5.maintenance-sonar/hazelcast/hazelcast/target/hazelcast-5.2.2-SNAPSHOT.jar!/META-INF/services/com.hazelcast.instance.impl.NodeExtension, jar:file:/home/jenkins/jenkins_slave/workspace/Hazelcast-5.maintenance-sonar/hazelcast/hazelcast/target/hazelcast-5.2.2-SNAPSHOT-tests.jar!/META-INF/services/com.hazelcast.instance.impl.NodeExtension
07:17:11,909  INFO || - [MetricsConfigHelper] Time-limited test - [LOCAL] [dev] [5.2.2-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
07:17:12,006  INFO || - [logo] Time-limited test - [127.0.0.1]:5701 [dev] [5.2.2-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
07:17:12,007  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.2.2-SNAPSHOT] Copyright (c) 2008-2022, Hazelcast, Inc. All Rights Reserved.
07:17:12,007  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.2.2-SNAPSHOT] Hazelcast Platform 5.2.2-SNAPSHOT (20221108 - 1207723) starting at [127.0.0.1]:5701
07:17:12,007  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.2.2-SNAPSHOT] Cluster name: dev
07:17:12,007  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.2.2-SNAPSHOT] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed. For more information, see the documentation for Integrity Checker.
07:17:12,007  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.2.2-SNAPSHOT] Jet is enabled
07:17:12,057  INFO || - [MetricsConfigHelper] Time-limited test - [127.0.0.1]:5701 [dev] [5.2.2-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
07:17:14,182  WARN || - [CPSubsystem] Time-limited test - [127.0.0.1]:5701 [dev] [5.2.2-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
07:17:14,932  INFO || - [JetServiceBackend] Time-limited test - [127.0.0.1]:5701 [dev] [5.2.2-SNAPSHOT] Setting number of cooperative threads and default parallelism to 2
07:17:15,173  INFO || - [Diagnostics] Time-limited test - [127.0.0.1]:5701 [dev] [5.2.2-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
07:17:15,201  INFO || - [LifecycleService] Time-limited test - [127.0.0.1]:5701 [dev] [5.2.2-SNAPSHOT] [127.0.0.1]:5701 is STARTING
07:17:15,275  INFO || - [ClusterService] Time-limited test - [127.0.0.1]:5701 [dev] [5.2.2-SNAPSHOT] 

Members {size:1, ver:1} [
	Member [127.0.0.1]:5701 - 71ebb11f-05f5-4ccf-82eb-fe0429d04104 this
]

07:17:15,317  INFO || - [JobCoordinationService] Time-limited test - [127.0.0.1]:5701 [dev] [5.2.2-SNAPSHOT] Jet started scanning for jobs
07:17:15,329  INFO || - [LifecycleService] Time-limited test - [127.0.0.1]:5701 [dev] [5.2.2-SNAPSHOT] [127.0.0.1]:5701 is STARTED
07:17:15,485  INFO || - [MetricsConfigHelper] Time-limited test - [LOCAL] [dev] [5.2.2-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
07:17:15,493  INFO || - [logo] Time-limited test - [127.0.0.1]:5702 [dev] [5.2.2-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
07:17:15,495  INFO || - [system] Time-limited test - [127.0.0.1]:5702 [dev] [5.2.2-SNAPSHOT] Copyright (c) 2008-2022, Hazelcast, Inc. All Rights Reserved.
07:17:15,495  INFO || - [system] Time-limited test - [127.0.0.1]:5702 [dev] [5.2.2-SNAPSHOT] Hazelcast Platform 5.2.2-SNAPSHOT (20221108 - 1207723) starting at [127.0.0.1]:5702
07:17:15,496  INFO || - [system] Time-limited test - [127.0.0.1]:5702 [dev] [5.2.2-SNAPSHOT] Cluster name: dev
07:17:15,496  INFO || - [system] Time-limited test - [127.0.0.1]:5702 [dev] [5.2.2-SNAPSHOT] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed. For more information, see the documentation for Integrity Checker.
07:17:15,497  INFO || - [system] Time-limited test - [127.0.0.1]:5702 [dev] [5.2.2-SNAPSHOT] Jet is enabled
07:17:15,531  INFO || - [MetricsConfigHelper] Time-limited test - [127.0.0.1]:5702 [dev] [5.2.2-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
07:17:15,582  WARN || - [CPSubsystem] Time-limited test - [127.0.0.1]:5702 [dev] [5.2.2-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
07:17:15,629  INFO || - [JetServiceBackend] Time-limited test - [127.0.0.1]:5702 [dev] [5.2.2-SNAPSHOT] Setting number of cooperative threads and default parallelism to 2
07:17:15,686  INFO || - [Diagnostics] Time-limited test - [127.0.0.1]:5702 [dev] [5.2.2-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
07:17:15,689  INFO || - [LifecycleService] Time-limited test - [127.0.0.1]:5702 [dev] [5.2.2-SNAPSHOT] [127.0.0.1]:5702 is STARTING
07:17:15,726  INFO || - [MockServer] Time-limited test - [127.0.0.1]:5702 [dev] [5.2.2-SNAPSHOT] Created connection to endpoint: [127.0.0.1]:5701-71ebb11f-05f5-4ccf-82eb-fe0429d04104, connection: MockConnection{localEndpoint=[address=[127.0.0.1]:5702, uuid=edc74ac9-181d-4ac9-aebc-0fb4e258cf87], remoteEndpoint=[address=[127.0.0.1]:5701, uuid=71ebb11f-05f5-4ccf-82eb-fe0429d04104], alive=true}
07:17:15,766  INFO || - [MockServer] hz.sleepy_tu.priority-generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [5.2.2-SNAPSHOT] Created connection to endpoint: [127.0.0.1]:5702-edc74ac9-181d-4ac9-aebc-0fb4e258cf87, connection: MockConnection{localEndpoint=[address=[127.0.0.1]:5701, uuid=71ebb11f-05f5-4ccf-82eb-fe0429d04104], remoteEndpoint=[address=[127.0.0.1]:5702, uuid=edc74ac9-181d-4ac9-aebc-0fb4e258cf87], alive=true}
07:17:15,786  INFO || - [ClusterService] hz.sleepy_tu.priority-generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [5.2.2-SNAPSHOT] 

Members {size:2, ver:2} [
	Member [127.0.0.1]:5701 - 71ebb11f-05f5-4ccf-82eb-fe0429d04104 this
	Member [127.0.0.1]:5702 - edc74ac9-181d-4ac9-aebc-0fb4e258cf87
]

07:17:15,901  INFO || - [ClusterService] hz.recursing_tu.priority-generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.2.2-SNAPSHOT] 

Members {size:2, ver:2} [
	Member [127.0.0.1]:5701 - 71ebb11f-05f5-4ccf-82eb-fe0429d04104
	Member [127.0.0.1]:5702 - edc74ac9-181d-4ac9-aebc-0fb4e258cf87 this
]

07:17:15,903  INFO || - [JobCoordinationService] Time-limited test - [127.0.0.1]:5702 [dev] [5.2.2-SNAPSHOT] Jet started scanning for jobs
07:17:15,904  INFO || - [LifecycleService] Time-limited test - [127.0.0.1]:5702 [dev] [5.2.2-SNAPSHOT] [127.0.0.1]:5702 is STARTED
Started Running Test: givenRow_whenStore_thenRowIsUpdated
07:17:15,991 DEBUG || - [GenericMapStore] hz.sleepy_tu.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.2.2-SNAPSHOT] Initializing for map people_o_23766c61_a1b4_4d4d_a863_2c5f67c4a17a
07:17:16,043  INFO || - [PartitionStateManager] hz.sleepy_tu.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.2.2-SNAPSHOT] Initializing cluster partition table arrangement...
07:17:21,144  INFO |givenRow_whenStore_thenRowIsUpdated| - [SqlTestSupport] Time-limited test - Removing 1 cached plans in SqlTestSupport.@After
07:17:21,144  INFO |givenRow_whenStore_thenRowIsUpdated| - [SqlTestSupport] Time-limited test - Removing 0 cached plans in SqlTestSupport.@After
07:17:21,158  INFO |givenRow_whenStore_thenRowIsUpdated| - [SimpleTestInClusterSupport] Time-limited test - Ditching 0 jobs in SimpleTestInClusterSupport.@After: []
07:17:21,159  INFO |givenRow_whenStore_thenRowIsUpdated| - [SimpleTestInClusterSupport] Time-limited test - Destroying 2 distributed objects in SimpleTestInClusterSupport.@After: [hz:impl:mapService/__sql.catalog, hz:impl:flakeIdGeneratorService/__jet.ids]
BuildInfo right after givenRow_whenStore_thenRowIsUpdated(com.hazelcast.mapstore.GenericMapStoreTest): BuildInfo{version='5.2.2-SNAPSHOT', build='20221108', buildNumber=20221108, revision=1207723, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'givenRow_whenStore_thenRowIsUpdated(com.hazelcast.mapstore.GenericMapStoreTest):'
07:17:15, accumulated pauses: 133 ms, max pause: 27 ms, pauses over 1000 ms: 0
07:17:20, accumulated pauses: 148 ms, max pause: 83 ms, pauses over 1000 ms: 0


No metrics recorded during the test

```
</details>

**Comment by TomaszGaweda** [comment]
Should be fixed by this PR: https://github.com/hazelcast/hazelcast/pull/22868

**Comment by TomaszGaweda** [comment]
Closed by https://github.com/hazelcast/hazelcast/pull/22868
