### ISSUE TITLE
com.hazelcast.jet.sql.impl.expression.SearchableExpressionCompatibilityTest.when_deserializingPreviousPatchVersion

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#22791]
_5.1.5_ release branch (commit 1e9a306e2282689e0ea09495c22f084d865054f3)

Failed on Sonar (Oracle JDK 11): https://jenkins.hazelcast.com/view/Security%20and%20Compliance/job/hazelcast-sonar-release-maintenance-4.x/25/testReport/com.hazelcast.jet.sql.impl.expression/SearchableExpressionCompatibilityTest/when_deserializingPreviousPatchVersion/
<details><summary>Stacktrace:</summary>

```
com.hazelcast.nio.serialization.HazelcastSerializationException: Error deserializing edge 'Project(IMap[public.test])' -> 'ClientSink': com.hazelcast.nio.serialization.HazelcastSerializationException: java.io.InvalidClassException: com.hazelcast.function.FunctionEx; local class incompatible: stream classdesc serialVersionUID = -8952148900708351577, local class serialVersionUID = 1484068542310087845
	at com.hazelcast.jet.core.Edge.readData(Edge.java:634)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.readInternal(DataSerializableSerializer.java:160)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:106)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:51)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:44)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.readObject(AbstractSerializationService.java:349)
	at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readObject(ByteArrayObjectDataInput.java:600)
	at com.hazelcast.jet.core.DAG.readData(DAG.java:586)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.readInternal(DataSerializableSerializer.java:160)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:106)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:51)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:44)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:268)
	at com.hazelcast.jet.sql.impl.expression.SearchableExpressionCompatibilityTest.when_deserializingPreviousPatchVersion(SearchableExpressionCompatibilityTest.java:59)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.hazelcast.nio.serialization.HazelcastSerializationException: java.io.InvalidClassException: com.hazelcast.function.FunctionEx; local class incompatible: stream classdesc serialVersionUID = -8952148900708351577, local class serialVersionUID = 1484068542310087845
	at com.hazelcast.internal.serialization.impl.SerializationUtil.handleException(SerializationUtil.java:111)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.readObject(AbstractSerializationService.java:355)
	at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readObject(ByteArrayObjectDataInput.java:600)
	at com.hazelcast.jet.impl.execution.init.CustomClassLoadedObject.read(CustomClassLoadedObject.java:57)
	at com.hazelcast.jet.core.Edge.readData(Edge.java:631)
	... 25 more
Caused by: java.io.InvalidClassException: com.hazelcast.function.FunctionEx; local class incompatible: stream classdesc serialVersionUID = -8952148900708351577, local class serialVersionUID = 1484068542310087845
	at java.base/java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:689)
	at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2042)
	at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1892)
	at java.base/java.io.ObjectInputStream.readClass(ObjectInputStream.java:1855)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1680)
	at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2518)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2412)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2250)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1709)
	at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2518)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2412)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2250)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1709)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:500)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:458)
	at com.hazelcast.jet.impl.execution.init.CustomClassLoadedObject$Serializer.read(CustomClassLoadedObject.java:120)
	at com.hazelcast.jet.impl.execution.init.CustomClassLoadedObject$Serializer.read(CustomClassLoadedObject.java:92)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:44)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.readObject(AbstractSerializationService.java:349)
	... 28 more

```
</details>
<details><summary>Standard output:</summary>

```
00:19:28,477  INFO |when_deserializingPreviousPatchVersion| - [AbstractConfigLocator] when_deserializingPreviousPatchVersion - Loading 'hazelcast-default.xml' from the classpath.
00:19:29,055  INFO |when_deserializingPreviousPatchVersion| - [MetricsConfigHelper] when_deserializingPreviousPatchVersion - [LOCAL] [dev] [5.1.5-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
00:19:29,056  INFO |when_deserializingPreviousPatchVersion| - [logo] when_deserializingPreviousPatchVersion - [127.0.0.1]:5701 [dev] [5.1.5-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
00:19:29,056  INFO |when_deserializingPreviousPatchVersion| - [system] when_deserializingPreviousPatchVersion - [127.0.0.1]:5701 [dev] [5.1.5-SNAPSHOT] Copyright (c) 2008-2022, Hazelcast, Inc. All Rights Reserved.
00:19:29,056  INFO |when_deserializingPreviousPatchVersion| - [system] when_deserializingPreviousPatchVersion - [127.0.0.1]:5701 [dev] [5.1.5-SNAPSHOT] Hazelcast Platform 5.1.5-SNAPSHOT (20221110 - 1e9a306) starting at [127.0.0.1]:5701
00:19:29,056  INFO |when_deserializingPreviousPatchVersion| - [system] when_deserializingPreviousPatchVersion - [127.0.0.1]:5701 [dev] [5.1.5-SNAPSHOT] Cluster name: dev
00:19:29,056  INFO |when_deserializingPreviousPatchVersion| - [system] when_deserializingPreviousPatchVersion - [127.0.0.1]:5701 [dev] [5.1.5-SNAPSHOT] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed.
To enable integrity checker do one of the following: 
  - Change member config using Java API: config.setIntegrityCheckerEnabled(true);
  - Change XML/YAML configuration property: Set hazelcast.integrity-checker.enabled to true
  - Add system property: -Dhz.integritychecker.enabled=true (for Hazelcast embedded, works only when loading config via Config.load)
  - Add environment variable: HZ_INTEGRITYCHECKER_ENABLED=true (recommended when running container image. For Hazelcast embedded, works only when loading config via Config.load)
00:19:29,056  INFO |when_deserializingPreviousPatchVersion| - [system] when_deserializingPreviousPatchVersion - [127.0.0.1]:5701 [dev] [5.1.5-SNAPSHOT] Jet is enabled
00:19:29,064  INFO |when_deserializingPreviousPatchVersion| - [MetricsConfigHelper] when_deserializingPreviousPatchVersion - [127.0.0.1]:5701 [dev] [5.1.5-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
00:19:29,071  WARN |when_deserializingPreviousPatchVersion| - [CPSubsystem] when_deserializingPreviousPatchVersion - [127.0.0.1]:5701 [dev] [5.1.5-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
00:19:29,078  INFO |when_deserializingPreviousPatchVersion| - [JetServiceBackend] when_deserializingPreviousPatchVersion - [127.0.0.1]:5701 [dev] [5.1.5-SNAPSHOT] Setting number of cooperative threads and default parallelism to 8
00:19:29,080  INFO |when_deserializingPreviousPatchVersion| - [Diagnostics] when_deserializingPreviousPatchVersion - [127.0.0.1]:5701 [dev] [5.1.5-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
00:19:29,080  INFO |when_deserializingPreviousPatchVersion| - [LifecycleService] when_deserializingPreviousPatchVersion - [127.0.0.1]:5701 [dev] [5.1.5-SNAPSHOT] [127.0.0.1]:5701 is STARTING
00:19:29,081  INFO |when_deserializingPreviousPatchVersion| - [ClusterService] when_deserializingPreviousPatchVersion - [127.0.0.1]:5701 [dev] [5.1.5-SNAPSHOT] 

Members {size:1, ver:1} [
	Member [127.0.0.1]:5701 - 4222694c-7f37-425e-b417-22f0ee6f7324 this
]

00:19:29,081  INFO |when_deserializingPreviousPatchVersion| - [JobCoordinationService] when_deserializingPreviousPatchVersion - [127.0.0.1]:5701 [dev] [5.1.5-SNAPSHOT] Jet started scanning for jobs
00:19:29,081 DEBUG |when_deserializingPreviousPatchVersion| - [JobCoordinationService] hz.compassionate_sinoussi.cached.thread-1 - [127.0.0.1]:5701 [dev] [5.1.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
00:19:29,082  INFO |when_deserializingPreviousPatchVersion| - [LifecycleService] when_deserializingPreviousPatchVersion - [127.0.0.1]:5701 [dev] [5.1.5-SNAPSHOT] [127.0.0.1]:5701 is STARTED
00:19:29,197 DEBUG |when_deserializingPreviousPatchVersion| - [JobCoordinationService] hz.compassionate_sinoussi.cached.thread-1 - [127.0.0.1]:5701 [dev] [5.1.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
00:19:29,206  INFO |when_deserializingPreviousPatchVersion| - [LifecycleService] Thread-505 - [127.0.0.1]:5701 [dev] [5.1.5-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
00:19:29,206  WARN |when_deserializingPreviousPatchVersion| - [Node] Thread-505 - [127.0.0.1]:5701 [dev] [5.1.5-SNAPSHOT] Terminating forcefully...
00:19:29,206  INFO |when_deserializingPreviousPatchVersion| - [Node] Thread-505 - [127.0.0.1]:5701 [dev] [5.1.5-SNAPSHOT] Shutting down connection manager...
00:19:29,206  INFO |when_deserializingPreviousPatchVersion| - [Node] Thread-505 - [127.0.0.1]:5701 [dev] [5.1.5-SNAPSHOT] Shutting down node engine...
00:19:29,210  INFO |when_deserializingPreviousPatchVersion| - [NodeExtension] Thread-505 - [127.0.0.1]:5701 [dev] [5.1.5-SNAPSHOT] Destroying node NodeExtension.
00:19:29,210  INFO |when_deserializingPreviousPatchVersion| - [Node] Thread-505 - [127.0.0.1]:5701 [dev] [5.1.5-SNAPSHOT] Hazelcast Shutdown is completed in 4 ms.
00:19:29,210  INFO |when_deserializingPreviousPatchVersion| - [LifecycleService] Thread-505 - [127.0.0.1]:5701 [dev] [5.1.5-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
BuildInfo right after when_deserializingPreviousPatchVersion(com.hazelcast.jet.sql.impl.expression.SearchableExpressionCompatibilityTest): BuildInfo{version='5.1.5-SNAPSHOT', build='20221110', buildNumber=20221110, revision=1e9a306, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'when_deserializingPreviousPatchVersion(com.hazelcast.jet.sql.impl.expression.SearchableExpressionCompatibilityTest):'
00:19:25, accumulated pauses: 308 ms, max pause: 103 ms, pauses over 1000 ms: 0


No metrics recorded during the test

```
</details>

**Comment by Fly-Style** [comment]
Closed with #22798
