### ISSUE TITLE
com.hazelcast.client.impl.spi.impl.discovery.ClientToMemberDiscoveryTest

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hazelcast#22863]
_master_ (commit 80c7071fe4165606c7cb410b51fcb6338a3bb502)

Failed on MacOS: https://jenkins.hazelcast.com/job/Hazelcast-master-MacOS-ZuluJDK8/133/testReport/junit/com.hazelcast.client.impl.spi.impl.discovery/ClientToMemberDiscoveryTest

Multiple tests/variants w/ the same exception:

- clientTest
  - [0: safeSerialization: null]
  - [1: safeSerialization: false]
  - [2: safeSerialization: true]
- clientSerializationMismatchTest
  - [1: safeSerialization: false]
  - [2: safeSerialization: true]

<details><summary>Stacktrace:</summary>

```
com.hazelcast.core.HazelcastException: java.net.SocketException: Can't assign requested address
	at com.hazelcast.internal.util.ExceptionUtil.lambda$static$0(ExceptionUtil.java:48)
	at com.hazelcast.internal.util.ExceptionUtil.peel(ExceptionUtil.java:126)
	at com.hazelcast.internal.util.ExceptionUtil.peel(ExceptionUtil.java:69)
	at com.hazelcast.internal.util.ExceptionUtil.rethrow(ExceptionUtil.java:131)
	at com.hazelcast.spi.discovery.multicast.MulticastDiscoveryStrategy.initializeMulticastSocket(MulticastDiscoveryStrategy.java:106)
	at com.hazelcast.spi.discovery.multicast.MulticastDiscoveryStrategy.start(MulticastDiscoveryStrategy.java:112)
	at com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.start(DefaultDiscoveryService.java:64)
	at com.hazelcast.instance.impl.Node.start(Node.java:493)
	at com.hazelcast.instance.impl.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:124)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:217)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:196)
	at com.hazelcast.test.TestHazelcastInstanceFactory.newHazelcastInstance(TestHazelcastInstanceFactory.java:235)
	at com.hazelcast.client.impl.spi.impl.discovery.ClientToMemberDiscoveryTest.clientTest(ClientToMemberDiscoveryTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketException: Can't assign requested address
	at java.net.PlainDatagramSocketImpl.join(Native Method)
	at java.net.AbstractPlainDatagramSocketImpl.join(AbstractPlainDatagramSocketImpl.java:178)
	at java.net.MulticastSocket.joinGroup(MulticastSocket.java:323)
	at com.hazelcast.spi.discovery.multicast.MulticastDiscoveryStrategy.initializeMulticastSocket(MulticastDiscoveryStrategy.java:97)
	... 20 more

```
</details>
<details><summary>Standard output:</summary>

```
Finished Running Test: clientSerializationMismatchTest[0: safeSerialization: null] in 0.010 seconds.
Started Running Test: clientTest[0: safeSerialization: null]
20:04:14,020  WARN |clientTest[0: safeSerialization: null]| - [AbstractXmlConfigHelper] main - Name of the hazelcast schema location[http://www.hazelcast.com/schema/config/hazelcast-config-5.2.xsd] is incorrect, using default
20:04:14,026  WARN |clientTest[0: safeSerialization: null]| - [AbstractXmlConfigHelper] main - Name of the hazelcast schema location[http://www.hazelcast.com/schema/client-config/hazelcast-client-config-5.2.xsd] is incorrect, using default
20:04:14,028  INFO |clientTest[0: safeSerialization: null]| - [MetricsConfigHelper] clientTest - [LOCAL] [dev] [5.3.0-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
20:04:14,028  INFO |clientTest[0: safeSerialization: null]| - [logo] clientTest - [127.0.0.1]:6001 [dev] [5.3.0-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
20:04:14,028  INFO |clientTest[0: safeSerialization: null]| - [system] clientTest - [127.0.0.1]:6001 [dev] [5.3.0-SNAPSHOT] Copyright (c) 2008-2022, Hazelcast, Inc. All Rights Reserved.
20:04:14,028  INFO |clientTest[0: safeSerialization: null]| - [system] clientTest - [127.0.0.1]:6001 [dev] [5.3.0-SNAPSHOT] Hazelcast Platform 5.3.0-SNAPSHOT (20221116 - 80c7071) starting at [127.0.0.1]:6001
20:04:14,028  INFO |clientTest[0: safeSerialization: null]| - [system] clientTest - [127.0.0.1]:6001 [dev] [5.3.0-SNAPSHOT] Cluster name: dev
20:04:14,028  INFO |clientTest[0: safeSerialization: null]| - [system] clientTest - [127.0.0.1]:6001 [dev] [5.3.0-SNAPSHOT] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed. For more information, see the documentation for Integrity Checker.
20:04:14,028  INFO |clientTest[0: safeSerialization: null]| - [system] clientTest - [127.0.0.1]:6001 [dev] [5.3.0-SNAPSHOT] The Jet engine is disabled.
To enable the Jet engine on the members, do one of the following:
  - Change member config using Java API: config.getJetConfig().setEnabled(true)
  - Change XML/YAML configuration property: Set hazelcast.jet.enabled to true
  - Add system property: -Dhz.jet.enabled=true (for Hazelcast embedded, works only when loading config via Config.load)
  - Add environment variable: HZ_JET_ENABLED=true (recommended when running container image. For Hazelcast embedded, works only when loading config via Config.load)
20:04:14,031  INFO |clientTest[0: safeSerialization: null]| - [MetricsConfigHelper] clientTest - [127.0.0.1]:6001 [dev] [5.3.0-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
20:04:14,033  WARN |clientTest[0: safeSerialization: null]| - [CPSubsystem] clientTest - [127.0.0.1]:6001 [dev] [5.3.0-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
20:04:14,036  INFO |clientTest[0: safeSerialization: null]| - [Diagnostics] clientTest - [127.0.0.1]:6001 [dev] [5.3.0-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
20:04:14,036  INFO |clientTest[0: safeSerialization: null]| - [LifecycleService] clientTest - [127.0.0.1]:6001 [dev] [5.3.0-SNAPSHOT] [127.0.0.1]:6001 is STARTING
20:04:14,036  WARN |clientTest[0: safeSerialization: null]| - [DiscoveryService] clientTest - [127.0.0.1]:6001 [dev] [5.3.0-SNAPSHOT] The MulticastDiscoveryStrategy Hazelcast member discovery strategy is configured without the safe-serialization parameter enabled. Set the safe-serialization property to 'true' in the strategy configuration to protect the cluster against untrusted deserialization attacks.
20:04:14,036  WARN |clientTest[0: safeSerialization: null]| - [Node] clientTest - [127.0.0.1]:6001 [dev] [5.3.0-SNAPSHOT] Terminating forcefully...
20:04:14,036  INFO |clientTest[0: safeSerialization: null]| - [Node] clientTest - [127.0.0.1]:6001 [dev] [5.3.0-SNAPSHOT] Shutting down connection manager...
20:04:14,036  INFO |clientTest[0: safeSerialization: null]| - [Node] clientTest - [127.0.0.1]:6001 [dev] [5.3.0-SNAPSHOT] Shutting down node engine...
20:04:14,038  INFO |clientTest[0: safeSerialization: null]| - [NodeExtension] clientTest - [127.0.0.1]:6001 [dev] [5.3.0-SNAPSHOT] Destroying node NodeExtension.
20:04:14,038  INFO |clientTest[0: safeSerialization: null]| - [Node] clientTest - [127.0.0.1]:6001 [dev] [5.3.0-SNAPSHOT] Hazelcast Shutdown is completed in 2 ms.
BuildInfo right after clientTest[0: safeSerialization: null](com.hazelcast.client.impl.spi.impl.discovery.ClientToMemberDiscoveryTest): BuildInfo{version='5.3.0-SNAPSHOT', build='20221116', buildNumber=20221116, revision=80c7071, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'clientTest[0: safeSerialization: null](com.hazelcast.client.impl.spi.impl.discovery.ClientToMemberDiscoveryTest):'
20:04:10, accumulated pauses: 1006 ms, max pause: 85 ms, pauses over 1000 ms: 0


No metrics recorded during the test

```
</details>

**Comment by orcunc** [comment]
The default multicast group is 224.2.2.3. When the OS does not have Ipv4 but only Ipv6 enabled, this case is happening. So with default settings -as in the test case - IPv4 needs to be enabled

**Comment by orcunc** [comment]
This is the full stack trace

> java.net.BindException: Can't assign requested address
	at java.base/sun.nio.ch.Net.joinOrDrop6(Native Method)
	at java.base/sun.nio.ch.Net.join6(Net.java:741)
	at java.base/sun.nio.ch.DatagramChannelImpl.innerJoin(DatagramChannelImpl.java:1576)
	at java.base/sun.nio.ch.DatagramChannelImpl.join(DatagramChannelImpl.java:1612)
	at java.base/sun.nio.ch.DatagramSocketAdaptor.joinGroup(DatagramSocketAdaptor.java:546)
	at java.base/sun.nio.ch.DatagramSocketAdaptor.joinGroup(DatagramSocketAdaptor.java:492)
	at java.base/java.net.MulticastSocket.joinGroup(MulticastSocket.java:324)
	at com.hazelcast.spi.discovery.multicast.MulticastDiscoveryStrategy.initializeMulticastSocket(MulticastDiscoveryStrategy.java:97)
	at com.hazelcast.spi.discovery.multicast.MulticastDiscoveryStrategy.start(MulticastDiscoveryStrategy.java:113)
	at com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.start(DefaultDiscoveryService.java:64)
	at com.hazelcast.instance.impl.Node.start(Node.java:493)
	at com.hazelcast.instance.impl.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:124)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:217)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:196)
	at com.hazelcast.test.TestHazelcastInstanceFactory.newHazelcastInstance(TestHazelcastInstanceFactory.java:235)
	at com.hazelcast.client.impl.spi.impl.discovery.ClientToMemberDiscoveryTest.clientTest(ClientToMemberDiscoveryTest.java:85)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at `java.base/java.lang.Thread.run(Thread.java:1589)`
