### ISSUE TITLE
com.hazelcast.cluster.MulticastDeserializationTest.testWithoutFilter

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hazelcast#22864]
_master_ (commit 80c7071fe4165606c7cb410b51fcb6338a3bb502)

Failed on MacOS: https://jenkins.hazelcast.com/job/Hazelcast-master-MacOS-ZuluJDK8/133/testReport/junit/com.hazelcast.cluster/MulticastDeserializationTest/testWithoutFilter/
<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: Object was not deserialized
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at com.hazelcast.cluster.MulticastDeserializationTest.lambda$testWithoutFilter$0(MulticastDeserializationTest.java:104)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1236)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1338)
	at com.hazelcast.cluster.MulticastDeserializationTest.testWithoutFilter(MulticastDeserializationTest.java:104)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-MacOS-ZuluJDK8/133/

**Comment by ramizdundar** [comment]
This failure is probably related to macos selecting IPv6 stack. See https://github.com/hazelcast/hazelcast/issues/22863#issuecomment-1319867366. It's also probably resolved now.
