### ISSUE TITLE
com.hazelcast.map.impl.journal.MapEventJournalBounceTest.testBouncingEventJournal [HZ-2556]

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hazelcast#22886]
_master_ (commit 1cb1e05d2b84fdb0289f8d64b4c42bacb70b101e)

Failed on IbmJDK8-fips: https://jenkins.hazelcast.com/job/Hazelcast-master-IbmJDK8-fips-nightly/482/testReport/junit/com.hazelcast.map.impl.journal/MapEventJournalBounceTest/testBouncingEventJournal/
<details><summary>Stacktrace:</summary>

```
com.hazelcast.core.OperationTimeoutException: MapEventJournalReadOperation invocation failed to complete due to operation-heartbeat-timeout. Current time: 2022-11-17 22:39:49.045. Start time: 2022-11-17 22:37:48.101. Total elapsed time: 120945 ms. Last operation heartbeat: never. Last operation heartbeat from member: never. Invocation{op=com.hazelcast.map.impl.journal.MapEventJournalReadOperation{serviceName='hz:impl:mapService', identityHash=1190148233, partitionId=5, replicaIndex=0, callId=-99286, invocationTime=1668724668101 (2022-11-17 22:37:48.101), waitTimeout=-1, callTimeout=60000, tenantControl=com.hazelcast.spi.impl.tenantcontrol.NoopTenantControl@0}, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=60000, firstInvocationTimeMs=1668724668101, firstInvocationTime='2022-11-17 22:37:48.101', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 00:00:00.000', target=[127.0.0.1]:5725, pendingResponse={VOID}, backupsAcksExpected=-1, backupsAcksReceived=22, connection=null}
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.newOperationTimeoutException(InvocationFuture.java:194)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:136)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:99)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:617)
	at com.hazelcast.journal.AbstractEventJournalBounceTest.getEventJournalEvents(AbstractEventJournalBounceTest.java:122)
	at com.hazelcast.journal.AbstractEventJournalBounceTest.access$000(AbstractEventJournalBounceTest.java:47)
	at com.hazelcast.journal.AbstractEventJournalBounceTest$EventJournalReadRunnable.run(AbstractEventJournalBounceTest.java:108)
	at com.hazelcast.test.bounce.BounceMemberRule$TestTaskRunnable.run(BounceMemberRule.java:605)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:522)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:825)
	at ------ submitted from ------.()
	at com.hazelcast.internal.util.ExceptionUtil.cloneExceptionWithFixedAsyncStackTrace(ExceptionUtil.java:348)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.returnOrThrowWithGetConventions(InvocationFuture.java:112)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:100)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:617)
	at com.hazelcast.journal.AbstractEventJournalBounceTest.getEventJournalEvents(AbstractEventJournalBounceTest.java:122)
	at com.hazelcast.journal.AbstractEventJournalBounceTest.access$000(AbstractEventJournalBounceTest.java:47)
	at com.hazelcast.journal.AbstractEventJournalBounceTest$EventJournalReadRunnable.run(AbstractEventJournalBounceTest.java:108)
	at com.hazelcast.test.bounce.BounceMemberRule$TestTaskRunnable.run(BounceMemberRule.java:605)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:522)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:825)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-IbmJDK8-fips-nightly/482/

**Comment by JamesHazelcast** [comment]
The stacktrace for this error shows a `MapEventJournalReadOperation` which has not completed a heartbeat within the timeout period (120s); this operation is destined for member `[127.0.0.1]:5725` and further examination of the S3 logs shows it was being invoked by member `[127.0.0.1]:5706` (as that is the owning member of the operation thread throwing this error). The operation was invoked at `22:37:48.101`.

Member `[127.0.0.1]:5706` is a stable member in this bouncing test, and is not shutdown during the test. Member `[127.0.0.1]:5725` however is not and begins shutdown at `22:37:48,051`, removing its connection to member `:5706` at `22:37:48,108` - 7ms after the operation had been invoked from the caller. It is also worth noting that this 120s timeout exception was thrown <1s before the test was finished with teardown - with this bouncing test only lasting 3 minutes, it's reasonable to have only encountered this niche edge case a handful of times.

This exact scenario has been observed before, and on December 12th 2022 @ramizdundar [made a commit which prevents this circumstances from occurring](https://github.com/hazelcast/hazelcast/commit/887c36d669efef9d62f4fd55bc667f9e06f7882b). This commit was made after this test failure was recorded, and no further failures have occurred since Ramiz's commit.

Given all of this, I believe this test failure has already been resolved and this issue can be closed.
