### ISSUE TITLE
Lots of JVM's on EC2 causes connection problems

### ISSUE THREAD

**Issue by pveentjer** [hazelcast/hazelcast#2289]
When I create a big number of JVM's on EC2, then I get connection problems. I'm not making use of AWS discovery btw.. I just generate the Hazelcast xml file. 

Perhaps it is a new issue, or it is an EC2 issue, because last year I could easily do 50 JVM's on our test cluster per machine. 

```
/start-small
./manager --managerHzFile manager-hazelcast.xml --duration 60 --traineeVmCount 10 ../workouts/lock-workout.properties  --traineeHzFile trainee-hazelcast.xml  --cleanGym
```

```
WARN  2014-04-15 06:32:26,903 [hz.client_0_coach.cluster-listener] com.hazelcast.client.spi.ClientClusterService: Error while listening cluster events! -> ClientConnection{live=true, writeHandler=com.hazelcast.client.connection.nio.ClientWriteHandler@4bc2fdde, readHandler=com.hazelcast.client.connection.nio.ClientReadHandler@6ea920ad, connectionId=1, socketChannel=DefaultSocketChannelWrapper{socketChannel=java.nio.channels.SocketChannel[connected local=/10.72.134.107:46810 remote=/10.215.101.140:8701]}, remoteEndpoint=Address[10.215.101.140]:8701}
java.io.EOFException: Remote socket closed!
    at com.hazelcast.client.connection.nio.ClientConnection.read(ClientConnection.java:174)
    at com.hazelcast.client.spi.impl.ClientClusterServiceImpl$ClusterListenerThread.listenMembershipEvents(ClientClusterServiceImpl.java:309)
    at com.hazelcast.client.spi.impl.ClientClusterServiceImpl$ClusterListenerThread.run(ClientClusterServiceImpl.java:233)
WARN  2014-04-15 06:32:26,905 [InSelector] com.hazelcast.client.connection.nio.ClientReadHandler: InSelector Closing socket to endpoint Address[10.215.101.140]:8701, Cause:java.io.IOException: Connection reset by peer
WARN  2014-04-15 06:32:26,910 [hz.client_0_coach.cluster-listener] com.hazelcast.client.connection.nio.ClientConnection: Connection [null] lost. Reason: Socket explicitly closed
INFO  2014-04-15 06:32:26,911 [hz.client_0_coach.cluster-listener] com.hazelcast.core.LifecycleService: HazelcastClient[hz.client_0_coach][3.2.1-SNAPSHOT] is CLIENT_DISCONNECTED
FATAL 2014-04-15 06:32:27,013 [main] com.hazelcast.stabilizer.Manager: Failed to run workout
com.hazelcast.core.HazelcastException: java.net.ConnectException: Connection refused
    at com.hazelcast.util.ExceptionUtil.rethrow(ExceptionUtil.java:45)
    at com.hazelcast.client.spi.ClientProxy.invoke(ClientProxy.java:114)
    at com.hazelcast.client.proxy.ClientTopicProxy.invoke(ClientTopicProxy.java:85)
    at com.hazelcast.client.proxy.ClientTopicProxy.publish(ClientTopicProxy.java:49)
    at com.hazelcast.stabilizer.Manager.getAllFutures(Manager.java:427)
    at com.hazelcast.stabilizer.Manager.getAllFutures(Manager.java:414)
    at com.hazelcast.stabilizer.Manager.submitToAllAndWait(Manager.java:410)
    at com.hazelcast.stabilizer.Manager.startTrainees(Manager.java:375)
    at com.hazelcast.stabilizer.Manager.runWorkout(Manager.java:230)
    at com.hazelcast.stabilizer.Manager.run(Manager.java:160)
    at com.hazelcast.stabilizer.Manager.main(Manager.java:558)
Caused by: java.net.ConnectException: Connection refused
    at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
    at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
    at sun.nio.ch.SocketAdaptor.connect(SocketAdaptor.java:117)
    at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.connect(ClientConnectionManagerImpl.java:294)
    at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.getOrConnect(ClientConnectionManagerImpl.java:268)
    at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.tryToConnect(ClientConnectionManagerImpl.java:211)
    at com.hazelcast.client.spi.impl.ClientInvocationServiceImpl.send(ClientInvocationServiceImpl.java:149)
    at com.hazelcast.client.spi.impl.ClientInvocationServiceImpl.invokeOnTarget(ClientInvocationServiceImpl.java:59)
    at com.hazelcast.client.spi.impl.ClientInvocationServiceImpl.invokeOnKeyOwner(ClientInvocationServiceImpl.java:66)
    at com.hazelcast.client.spi.ClientProxy.invoke(ClientProxy.java:111)
    ... 9 more
```

Contact me to reproduce this issue.

**Comment by AyberkSorgun** [comment]
Peter: "We have retested with large number of clients.. Doesn't seem to be an issue any longer"
