### ISSUE TITLE
com.hazelcast.jet.impl.connector.WriteJdbcPTest.test_transactional_withRestarts_graceful_atLeastOnce [HZ-1835]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#22931]
_master_ (commit 584804e286409b8585a4514de59bd44ae72e3f3c)

Failed on oracle-11 (sonar build): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/1405/testReport/com.hazelcast.jet.impl.connector/WriteJdbcPTest/test_transactional_withRestarts_graceful_atLeastOnce/

It can be related to https://github.com/hazelcast/hazelcast/issues/21994 but stacktrace is different. 

There are some other failures in `com.hazelcast.jet.impl.connector.WriteJdbcPTest` but all of them are like `Hazelcast instance is not active!` so `com.hazelcast.jet.impl.connector.WriteJdbcPTest.test_transactional_withRestarts_graceful_atLeastOnce` is probably culprit.

<details><summary>Stacktrace:</summary>

```
java.lang.RuntimeException: 10 attempts to cancel the job failed, shut down the cluster
	at com.hazelcast.jet.core.JetTestSupport.ditchJob0(JetTestSupport.java:487)
	at com.hazelcast.jet.core.JetTestSupport.ditchJob(JetTestSupport.java:408)
	at com.hazelcast.jet.SimpleTestInClusterSupport.supportAfter(SimpleTestInClusterSupport.java:113)
	at jdk.internal.reflect.GeneratedMethodAccessor760.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:381)
	at com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37)
	at com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:104)
	at com.hazelcast.test.metrics.MetricsRule$1.evaluate(MetricsRule.java:63)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:50)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:29)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:40)
	at org.testcontainers.containers.FailureDetectingExternalResource$1.evaluate(FailureDetectingExternalResource.java:29)
	at com.hazelcast.test.OverridePropertyRule$1.evaluate(OverridePropertyRule.java:66)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-sonar/1405/

**Comment by olukas** [comment]
Failed again on _master_ with ZuluJDK17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZuluJDK17-nightly/43/testReport/com.hazelcast.jet.impl.connector/WriteJdbcPTest/test_transactional_withRestarts_graceful_atLeastOnce/

**Comment by Patras3** [comment]
Reopening as test just failed on:
 _master_ (commit a1a408fb13042306419c27a006a2b886fcbb8768)
with OracleJDK8: https://jenkins.hazelcast.com/job/Hazelcast-master-OracleJDK8-nightly/925/testReport/com.hazelcast.jet.impl.connector/WriteJdbcPTest/
`The column index is out of range: 0, number of columns: 20.`

It fails now in the code added by #22968.
@TomaszGaweda please take a look.
