### ISSUE TITLE
com.hazelcast.map.impl.mapstore.writebehind.TransactionsWithWriteBehind_whenNoCoalescingQueueIsFullTest.stress [HZ-1819]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#22954]
_master_ (commit 6f2603e9fcbd8acb08e3181b802b036f4056eff3)

Failed on RedHatJDK8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-RedHatJDK8/66/testReport/com.hazelcast.map.impl.mapstore.writebehind/TransactionsWithWriteBehind_whenNoCoalescingQueueIsFullTest/stress/

It can be related to https://github.com/hazelcast/hazelcast/issues/22674

<details><summary>Stacktrace:</summary>

```
java.lang.IllegalStateException: Not terminated yet...
	at com.hazelcast.map.impl.mapstore.writebehind.TransactionsWithWriteBehind_whenNoCoalescingQueueIsFullTest.stress(TransactionsWithWriteBehind_whenNoCoalescingQueueIsFullTest.java:331)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-RedHatJDK8/66/

**Comment by Patras3** [comment]
Failed again on _master_ with oracle-11 (sonar build): https://jenkins.hazelcast.com/job/Hazelcast-master-sonar/1409/testReport/junit/com.hazelcast.map.impl.mapstore.writebehind/TransactionsWithWriteBehind_whenNoCoalescingQueueIsFullTest/stress/

**Comment by frant-hartm** [comment]
Failed also here https://github.com/hazelcast/hazelcast/pull/22990#issuecomment-1332388530
