### ISSUE TITLE
Classcast exception on hz-cli job submission

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast#22978]
**Describe the bug**
Using 5.3.0-SNAPSHOT, `hz-cli` mainly works, but job submission throws a class cast exception

**Expected behavior**
No exception, job submitted

**To Reproduce**
`hz-cli -v -t grid1@127.0.0.1 submit path-to-jar` seems to be enough.

**Additional context**
I'm using `Hazelcast Platform 5.3.0-SNAPSHOT (20221128 - f35a6f1) ` on my server.

Gives me
```
10:26:17.221 [ INFO] [c.h.c.LifecycleService] hz.client_1 [grid1] [5.3.0-SNAPSHOT] HazelcastClient 5.3.0-SNAPSHOT (20221128 - f35a6f1) is CLIENT_DISCONNECTED
10:26:17.222 [ INFO] [c.h.c.LifecycleService] hz.client_1 [grid1] [5.3.0-SNAPSHOT] HazelcastClient 5.3.0-SNAPSHOT (20221128 - f35a6f1) is SHUTDOWN
picocli.CommandLine$ExecutionException: Error while calling command (public void com.hazelcast.client.console.HazelcastCommandLine.submit(com.hazelcast.client.console.HazelcastCommandLine$GlobalMixin,java.lang.String,java.lang.String,java.lang.String,java.io.File,java.util.List) throws java.lang.Exception): java.lang.reflect.InvocationTargetException
	at picocli.CommandLine.executeUserObject(CommandLine.java:1986)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunAll.recursivelyExecuteUserObject(CommandLine.java:2431)
	at picocli.CommandLine$RunAll.recursivelyExecuteUserObject(CommandLine.java:2433)
	at picocli.CommandLine$RunAll.handle(CommandLine.java:2428)
	at picocli.CommandLine$RunAll.handle(CommandLine.java:2389)
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:2172)
	at picocli.CommandLine.parseWithHandlers(CommandLine.java:2559)
	at com.hazelcast.client.console.HazelcastCommandLine.runCommandLine(HazelcastCommandLine.java:553)
	at com.hazelcast.client.console.HazelcastCommandLine.main(HazelcastCommandLine.java:133)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at com.hazelcast.instance.impl.HazelcastBootstrap.executeJar(HazelcastBootstrap.java:170)
	at com.hazelcast.client.console.HazelcastCommandLine.submit(HazelcastCommandLine.java:192)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1972)
	... 9 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:95)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	... 15 more
Caused by: java.lang.RuntimeException: Exception while calling findClassLoaderOrder for com.hazelcast.nonapi.io.github.classgraph.classloaderhandler.URLClassLoaderHandler
	at com.hazelcast.nonapi.io.github.classgraph.classloaderhandler.ClassLoaderHandlerRegistry$ClassLoaderHandlerRegistryEntry.findClasspathOrder(ClassLoaderHandlerRegistry.java:239)
	at com.hazelcast.nonapi.io.github.classgraph.classpath.ClasspathFinder.<init>(ClasspathFinder.java:273)
	at com.hazelcast.io.github.classgraph.Scanner.<init>(Scanner.java:166)
	at com.hazelcast.io.github.classgraph.ClassGraph.scanAsync(ClassGraph.java:1531)
	at com.hazelcast.io.github.classgraph.ClassGraph.scanAsync(ClassGraph.java:1559)
	at com.hazelcast.io.github.classgraph.ClassGraph.scan(ClassGraph.java:1584)
	at com.hazelcast.io.github.classgraph.ClassGraph.scan(ClassGraph.java:1623)
	at com.hazelcast.io.github.classgraph.ClassGraph.scan(ClassGraph.java:1636)
	at com.hazelcast.jet.impl.util.ReflectionUtils.nestedClassesOf(ReflectionUtils.java:232)
	at com.hazelcast.jet.config.JobConfig.addClass(JobConfig.java:307)
	at hazelcast.platform.demos.banking.transactionmonitor.Application.main(Application.java:51)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	... 21 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:110)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at com.hazelcast.nonapi.io.github.classgraph.classloaderhandler.ClassLoaderHandlerRegistry$ClassLoaderHandlerRegistryEntry.findClasspathOrder(ClassLoaderHandlerRegistry.java:236)
	... 32 more
Caused by: java.lang.ClassCastException: class java.net.URL cannot be cast to class java.nio.file.Path (java.net.URL and java.nio.file.Path are in module java.base of loader 'bootstrap')
	at com.hazelcast.nonapi.io.github.classgraph.classpath.ClasspathOrder.addClasspathEntry(ClasspathOrder.java:299)
	at com.hazelcast.nonapi.io.github.classgraph.classloaderhandler.URLClassLoaderHandler.findClasspathOrder(URLClassLoaderHandler.java:92)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	... 34 more
```

**Comment by frant-hartm** [comment]
@neilstevenson is this still reproducible on the current master?
Could you add more detailed steps to reproduce - simple hello world job submission works fine for me.

**Comment by neilstevenson** [comment]
Now ok again, was failing last week but ok as of today
