### ISSUE TITLE
Python failure - Initialization script finished with non-zero exit code: 127

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast#22980]
**Describe the bug**
Python service fails with 5.3.0-SNAPSHOT (20221128 - f35a6f1), works with 5.2.1

**Expected behavior**
Python service works

**To Reproduce**
Java
```
package neil.demo;

import java.io.File;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.util.List;

import com.hazelcast.config.Config;
import com.hazelcast.core.Hazelcast;
import com.hazelcast.core.HazelcastInstance;
import com.hazelcast.jet.pipeline.Pipeline;
import com.hazelcast.jet.pipeline.Sinks;
import com.hazelcast.jet.pipeline.test.TestSources;
import com.hazelcast.jet.python.PythonServiceConfig;
import com.hazelcast.jet.python.PythonTransforms;

public class Application {
	
    public static void main(String[] args) throws Exception {
        Config config = new Config();
        config.getNetworkConfig().getJoin().getMulticastConfig().setEnabled(false);
        config.getJetConfig().setResourceUploadEnabled(true).setEnabled(true);

        HazelcastInstance hazelcastInstance = Hazelcast.newHazelcastInstance(config);

        PythonServiceConfig pythonServiceConfig = getPythonServiceConfig("neil");
        
        Pipeline pipeline = 
        		Pipeline.create()
        		.readFrom(TestSources.items(List.of("hello", "world")))
        		.apply(PythonTransforms.mapUsingPythonBatch(pythonServiceConfig)).setLocalParallelism(1)
        		.writeTo(Sinks.logger())
        		.getPipeline();

        hazelcastInstance.getJet().newJob(pipeline).join();
        
        hazelcastInstance.shutdown();
    }    
    
    protected static PythonServiceConfig getPythonServiceConfig(String name) throws Exception {
        File temporaryDir = getTemporaryDir(name);

        PythonServiceConfig pythonServiceConfig = new PythonServiceConfig();
        pythonServiceConfig.setBaseDir(temporaryDir.toString());
        pythonServiceConfig.setHandlerFunction("handle");
        pythonServiceConfig.setHandlerModule(name);

        return pythonServiceConfig;
    }
    
    protected static File getTemporaryDir(String name) throws Exception {

        Path targetDirectory = Files.createTempDirectory(name);
        targetDirectory.toFile().deleteOnExit();

        ClassLoader classLoader = Thread.currentThread().getContextClassLoader();

        String resourceToCopy = name + ".py";
        try (InputStream inputStream = classLoader.getResourceAsStream(resourceToCopy)) {
            if (inputStream == null) {
                System.out.println(resourceToCopy + ": not found in Jar's src/main/resources");
            } else {
                Path targetFile = Paths.get(targetDirectory + File.separator + resourceToCopy);
                Files.copy(inputStream, targetFile, StandardCopyOption.REPLACE_EXISTING);
            }
        }

        return targetDirectory.toFile();
    }
}
```

Python (`neil.py`)
```
def handle(items):
    results = []

    for item in items:
      results.append(str(len(item)))

    return results
```

**Additional context**
Gives
```
Nov 28, 2022 12:28:04 PM com.hazelcast.jet.impl.processor.ProcessorSupplierWithService
WARNING: [xxx.xxx.xxx.xxx]:5701 [dev] [5.3.0-SNAPSHOT] [0903-cc35-5e80-0001/mapUsingPythonBatch#PS] PythonService context creation failed, will retry
com.hazelcast.jet.JetException: PythonService initialization failed: java.lang.Exception: Initialization script finished with non-zero exit code: 127
	at com.hazelcast.jet.python.PythonServiceContext.<init>(PythonServiceContext.java:114)
	at com.hazelcast.jet.python.PythonService.createContextWithRetry(PythonService.java:109)
	at com.hazelcast.jet.python.PythonService.lambda$factory$9a0f8f23$1(PythonService.java:89)
	at com.hazelcast.function.FunctionEx.apply(FunctionEx.java:49)
	at com.hazelcast.jet.impl.processor.ProcessorSupplierWithService.init(ProcessorSupplierWithService.java:59)
	at com.hazelcast.jet.impl.execution.init.ExecutionPlan.lambda$null$9c5eb802$1(ExecutionPlan.java:456)
	at com.hazelcast.jet.function.RunnableEx.run(RunnableEx.java:31)
	at com.hazelcast.jet.impl.util.Util.doWithClassLoader(Util.java:532)
	at com.hazelcast.jet.impl.execution.init.ExecutionPlan.lambda$initProcSuppliers$10beb6ff$1(ExecutionPlan.java:455)
	at com.hazelcast.jet.function.RunnableEx.run(RunnableEx.java:31)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
Caused by: java.lang.Exception: Initialization script finished with non-zero exit code: 127
	at com.hazelcast.jet.python.PythonServiceContext.<init>(PythonServiceContext.java:105)
	... 16 more
```

**Comment by frant-hartm** [comment]
@neilstevenson can' reproduce it, I get:

```
INFO: [10.212.134.152]:5701 [dev] [5.3.0-SNAPSHOT] [090e-05d9-9c80-0001/loggerSink#0] 5
Dec 06, 2022 12:04:48 PM com.hazelcast.jet.impl.connector.WriteLoggerP
INFO: [10.212.134.152]:5701 [dev] [5.3.0-SNAPSHOT] [090e-05d9-9c80-0001/loggerSink#0] 5
```

Could you also add debug log for `com.hazelcast.jet` and share more details - Java version, dependencies, Python version, OS, architecture? Thanks

**Comment by neilstevenson** [comment]
I'm on macOS 13.0.1. It's

```
./jet_to_python_init.sh: line 9: flock: command not found
```

Flock isn't installed by default on Mac.

**Comment by frant-hartm** [comment]
Yes this is new. 

We use it to handle parallel `pip install ...` from multiple processes (e.g. when you have local parallelism for the service >1). Please install flock.

I will keep this open so we provide a better error message.

**Comment by neilstevenson** [comment]
`brew install flock` made it work for me.
