### ISSUE TITLE
com.hazelcast.aggregation.AggregationMemberBounceTest.aggregationReturnsCorrectResultWhenBouncing

### ISSUE THREAD

**Issue by Patras3** [hazelcast/hazelcast#23000]
_4.2.z_ (commit 89d55ea9ee1fb84f21cf561a685f805fe5074bcd)

Failed on OracleJDK8: https://jenkins.hazelcast.com/job/Hazelcast-4.maintenance-OracleJDK8-nightly/953/testReport/com.hazelcast.aggregation/AggregationMemberBounceTest/aggregationReturnsCorrectResultWhenBouncing/
<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: expected:<500.0> but was:<500.87863590772315>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:120)
	at org.junit.Assert.assertEquals(Assert.java:146)
	at com.hazelcast.aggregation.AggregatorsSpecTest.assertAverageAggregators(AggregatorsSpecTest.java:237)
	at com.hazelcast.aggregation.AggregationMemberBounceTest$1.run(AggregationMemberBounceTest.java:76)
	at com.hazelcast.test.bounce.BounceMemberRule$TestTaskRunnable.run(BounceMemberRule.java:605)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-4.maintenance-OracleJDK8-nightly/953/

It can be related to #21758, but here fails on average, not sum assertion.

**Comment by ahmetmircik** [comment]
closed by https://github.com/hazelcast/hazelcast/pull/23001
