### ISSUE TITLE
JobNotFoundException accessing submission time

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast#23054]
**Describe the bug**
JobNotFoundException accessing job returned by `hazelcastInstance.getJet().getJobs()`

**Expected behavior**
No exception

**To Reproduce**
Not sure. Code is valid
```
        hazelcastInstance.getJet().getJobs().forEach(job -> {
            try {
                JobConfig jobConfig = job.getConfig();
                Object originalSql =
                        jobConfig.getArgument(JobConfigArguments.KEY_SQL_QUERY_TEXT);
                if (originalSql != null) {
                    LOGGER.info(" Original SQL: {}", originalSql);
                }
            } catch (Exception e) {
                LOGGER.info("JobConfig", e);
            }
        });
```

**Additional context**
Using `5.3.0-SNAPSHOT (20221201 - a515112, 2e15289)`
Gives
```
Exception in thread "main" com.hazelcast.jet.core.JobNotFoundException: Job with id 0908-d98b-f582-0003 not found
	at com.hazelcast.jet.impl.JobCoordinationService.getJobSubmissionTime(JobCoordinationService.java:673)
	at com.hazelcast.jet.impl.operation.GetJobSubmissionTimeOperation.doRun(GetJobSubmissionTimeOperation.java:41)
	at com.hazelcast.jet.impl.operation.AsyncOperation.run(AsyncOperation.java:55)
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:192)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:283)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:258)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:219)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:411)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:438)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:601)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:580)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:541)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:241)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:71)
	at com.hazelcast.client.impl.protocol.task.AbstractInvocationMessageTask.processInternal(AbstractInvocationMessageTask.java:38)
	at com.hazelcast.client.impl.protocol.task.AbstractAsyncMessageTask.processMessage(AbstractAsyncMessageTask.java:71)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:153)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:116)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:833)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
	at ------ submitted from ------.()
	at com.hazelcast.internal.util.ExceptionUtil.cloneExceptionWithFixedAsyncStackTrace(ExceptionUtil.java:348)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.returnOrThrowWithGetConventions(InvocationFuture.java:112)
	at com.hazelcast.client.impl.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:95)
	at com.hazelcast.client.impl.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:40)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:617)
	at com.hazelcast.jet.impl.ClientJobProxy.lambda$doGetJobSubmissionTime$6(ClientJobProxy.java:185)
	at com.hazelcast.jet.impl.ClientJobProxy.callAndRetryIfTargetNotFound(ClientJobProxy.java:233)
	at com.hazelcast.jet.impl.ClientJobProxy.doGetJobSubmissionTime(ClientJobProxy.java:183)
	at com.hazelcast.jet.impl.util.ConcurrentMemoizingSupplier.get(ConcurrentMemoizingSupplier.java:50)
	at com.hazelcast.jet.impl.AbstractJobProxy.getSubmissionTime(AbstractJobProxy.java:185)
	at hazelcast.platform.demos.banking.transactionmonitor.CommonIdempotentInitialization.lambda$logJobs$8(CommonIdempotentInitialization.java:1047)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at hazelcast.platform.demos.banking.transactionmonitor.CommonIdempotentInitialization.logJobs(CommonIdempotentInitialization.java:1044)
	at hazelcast.platform.demos.banking.transactionmonitor.CommonIdempotentInitialization.logStuff(CommonIdempotentInitialization.java:1032)
	at hazelcast.platform.demos.banking.transactionmonitor.ApplicationRunner.run(ApplicationRunner.java:147)
	at hazelcast.platform.demos.banking.transactionmonitor.Application.main(Application.java:94)
```

**Comment by k-jamroz** [comment]
Getting list of jobs is one request to the server and getting attributes of a given `Job`, like `getConfig()` or `getJobSubmissionTime()` is another, separate request to the server. The attributes are not "cached" in `Job` returned by `getJobs()`.

If the SQL query finishes between `getJobs()` and `job.getJobSubmissionTime()` you will get `JobNotFoundException` because technically the job no longer exists.

**Comment by k-jamroz** [comment]
There also exists `getJobAndSqlSummaryList` operation which returns jobs with all details ready without need for additional requests to the the server, but currently it is not a part of public API.

**Comment by neilstevenson** [comment]
Closing as "_user error_". Jobs can be deleted
