### ISSUE TITLE
com.hazelcast.internal.serialization.impl.compact.schema.CompactSchemaReplicationTest.testSchemaReplication_whenAMemberThrows_duringPreparationPhase

### ISSUE THREAD

**Issue by Patras3** [hazelcast/hazelcast#23060]
_master_ (commit 2e152898593c1c9d0960524b1d43b118df4739ba)

Failed on oracle-11 (sonar build): https://jenkins.hazelcast.com/job/Hazelcast-master-sonar/1413/testReport/junit/com.hazelcast.internal.serialization.impl.compact.schema/CompactSchemaReplicationTest/testSchemaReplication_whenAMemberThrows_duringPreparationPhase/
<details><summary>Stacktrace:</summary>

```
org.mockito.exceptions.misusing.UnfinishedStubbingException: 

Unfinished stubbing detected here:
-> at com.hazelcast.internal.serialization.impl.compact.schema.CompactSchemaReplicationTest.testSchemaReplication_whenAMemberThrows_duringPreparationPhase(CompactSchemaReplicationTest.java:68)

E.g. thenReturn() may be missing.
Examples of correct stubbing:
    when(mock.isOk()).thenReturn(true);
    when(mock.isOk()).thenThrow(exception);
    doThrow(exception).when(mock).someVoidMethod();
Hints:
 1. missing thenReturn()
 2. you are trying to stub a final method, which is not supported
 3. you are stubbing the behaviour of another mock inside before 'thenReturn' instruction is completed

	at com.hazelcast.internal.serialization.impl.compact.schema.CompactSchemaReplicationTest.testSchemaReplication_whenAMemberThrows_duringPreparationPhase(CompactSchemaReplicationTest.java:70)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)

```
</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: testSchemaReplication_whenAMemberThrowsRetryableExceptionForSomeTime_duringAcknowledgmentPhase in 2.276 seconds.
02:19:17,514 DEBUG |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [JobCoordinationService] hz.infallible_swirles.cached.thread-14 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:19:17,620 DEBUG |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [JobCoordinationService] hz.infallible_swirles.cached.thread-14 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:19:17,758 DEBUG |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [JobCoordinationService] hz.infallible_swirles.cached.thread-15 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:19:17,899 DEBUG |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [JobCoordinationService] hz.infallible_swirles.cached.thread-15 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:19:18,001 DEBUG |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [JobCoordinationService] hz.infallible_swirles.cached.thread-16 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:19:18,115 DEBUG |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [JobCoordinationService] hz.infallible_swirles.cached.thread-15 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:19:18,434 DEBUG |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [JobCoordinationService] hz.infallible_swirles.cached.thread-13 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:19:18,558 DEBUG |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [JobCoordinationService] hz.infallible_swirles.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:19:18,669 DEBUG |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [JobCoordinationService] hz.infallible_swirles.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:19:18,785 DEBUG |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [JobCoordinationService] hz.infallible_swirles.cached.thread-13 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:19:19,032 DEBUG |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [JobCoordinationService] hz.infallible_swirles.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:19:19,250 DEBUG |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [JobCoordinationService] hz.infallible_swirles.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:19:19,394 DEBUG |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [JobCoordinationService] hz.infallible_swirles.cached.thread-16 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:19:19,532 DEBUG |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [JobCoordinationService] hz.infallible_swirles.cached.thread-16 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:19:19,661 DEBUG |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [JobCoordinationService] hz.infallible_swirles.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:19:19,814 DEBUG |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [JobCoordinationService] hz.infallible_swirles.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:19:19,965 DEBUG |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [JobCoordinationService] hz.infallible_swirles.cached.thread-17 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:19:20,204 DEBUG |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [JobCoordinationService] hz.infallible_swirles.cached.thread-17 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:19:20,318 DEBUG |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [JobCoordinationService] hz.infallible_swirles.cached.thread-16 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:19:20,489 DEBUG |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [JobCoordinationService] hz.infallible_swirles.cached.thread-1 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:19:20,589 DEBUG |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [JobCoordinationService] hz.infallible_swirles.cached.thread-16 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:19:20,739 DEBUG |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [JobCoordinationService] hz.infallible_swirles.cached.thread-17 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:19:20,944 DEBUG |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [JobCoordinationService] hz.infallible_swirles.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:19:21,058 DEBUG |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [JobCoordinationService] hz.infallible_swirles.cached.thread-1 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:19:21,182 DEBUG |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [JobCoordinationService] hz.infallible_swirles.cached.thread-1 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:19:21,315 DEBUG |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [JobCoordinationService] hz.infallible_swirles.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:19:21,492 DEBUG |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [JobCoordinationService] hz.infallible_swirles.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:19:21,592  INFO |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [LifecycleService] Thread-70321 - [127.0.0.1]:5703 [dev] [5.3.0-SNAPSHOT] [127.0.0.1]:5703 is SHUTTING_DOWN
02:19:21,592 DEBUG |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [JobCoordinationService] hz.infallible_swirles.cached.thread-10 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:19:21,592  WARN |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [Node] Thread-70321 - [127.0.0.1]:5703 [dev] [5.3.0-SNAPSHOT] Terminating forcefully...
02:19:21,592  INFO |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [Node] Thread-70321 - [127.0.0.1]:5703 [dev] [5.3.0-SNAPSHOT] Shutting down connection manager...
02:19:21,592  INFO |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [MockServer] Thread-70321 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Removed connection to endpoint: [address=[127.0.0.1]:5703, uuid=d97526b3-c4ab-49d4-bda0-d089161d705c], connection: MockConnection{localEndpoint=[address=[127.0.0.1]:5701, uuid=0efcb126-1369-4d90-bcaa-db93b5382a36], remoteEndpoint=[address=[127.0.0.1]:5703, uuid=d97526b3-c4ab-49d4-bda0-d089161d705c], alive=false}
02:19:21,592  INFO |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [MockServer] Thread-70321 - [127.0.0.1]:5703 [dev] [5.3.0-SNAPSHOT] Removed connection to endpoint: [address=[127.0.0.1]:5701, uuid=0efcb126-1369-4d90-bcaa-db93b5382a36], connection: MockConnection{localEndpoint=[address=[127.0.0.1]:5703, uuid=d97526b3-c4ab-49d4-bda0-d089161d705c], remoteEndpoint=[address=[127.0.0.1]:5701, uuid=0efcb126-1369-4d90-bcaa-db93b5382a36], alive=false}
02:19:21,592  INFO |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [MockServer] Thread-70321 - [127.0.0.1]:5704 [dev] [5.3.0-SNAPSHOT] Removed connection to endpoint: [address=[127.0.0.1]:5703, uuid=d97526b3-c4ab-49d4-bda0-d089161d705c], connection: MockConnection{localEndpoint=[address=[127.0.0.1]:5704, uuid=964777ef-6dde-4835-af05-a1a8efd9deb2], remoteEndpoint=[address=[127.0.0.1]:5703, uuid=d97526b3-c4ab-49d4-bda0-d089161d705c], alive=false}
02:19:21,592  INFO |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [MockServer] Thread-70321 - [127.0.0.1]:5703 [dev] [5.3.0-SNAPSHOT] Removed connection to endpoint: [address=[127.0.0.1]:5704, uuid=964777ef-6dde-4835-af05-a1a8efd9deb2], connection: MockConnection{localEndpoint=[address=[127.0.0.1]:5703, uuid=d97526b3-c4ab-49d4-bda0-d089161d705c], remoteEndpoint=[address=[127.0.0.1]:5704, uuid=964777ef-6dde-4835-af05-a1a8efd9deb2], alive=false}
02:19:21,592  INFO |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [MockServer] Thread-70321 - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Removed connection to endpoint: [address=[127.0.0.1]:5703, uuid=d97526b3-c4ab-49d4-bda0-d089161d705c], connection: MockConnection{localEndpoint=[address=[127.0.0.1]:5702, uuid=861f0e70-cf92-408a-9b49-3f084cc658b6], remoteEndpoint=[address=[127.0.0.1]:5703, uuid=d97526b3-c4ab-49d4-bda0-d089161d705c], alive=false}
02:19:21,592  INFO |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [MockServer] Thread-70321 - [127.0.0.1]:5703 [dev] [5.3.0-SNAPSHOT] Removed connection to endpoint: [address=[127.0.0.1]:5702, uuid=861f0e70-cf92-408a-9b49-3f084cc658b6], connection: MockConnection{localEndpoint=[address=[127.0.0.1]:5703, uuid=d97526b3-c4ab-49d4-bda0-d089161d705c], remoteEndpoint=[address=[127.0.0.1]:5702, uuid=861f0e70-cf92-408a-9b49-3f084cc658b6], alive=false}
02:19:21,592  WARN |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [MembershipManager] Thread-70321 - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Member [127.0.0.1]:5703 - d97526b3-c4ab-49d4-bda0-d089161d705c is suspected to be dead for reason: Connection manager is stopped on Member [127.0.0.1]:5703 - d97526b3-c4ab-49d4-bda0-d089161d705c this
02:19:21,592  WARN |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [MembershipManager] Thread-70321 - [127.0.0.1]:5704 [dev] [5.3.0-SNAPSHOT] Member [127.0.0.1]:5703 - d97526b3-c4ab-49d4-bda0-d089161d705c is suspected to be dead for reason: Connection manager is stopped on Member [127.0.0.1]:5703 - d97526b3-c4ab-49d4-bda0-d089161d705c this
02:19:21,592  INFO |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [MembershipManager] Thread-70321 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Removing Member [127.0.0.1]:5703 - d97526b3-c4ab-49d4-bda0-d089161d705c
02:19:21,593  INFO |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [TransactionManagerService] hz.laughing_swirles.cached.thread-8 - [127.0.0.1]:5704 [dev] [5.3.0-SNAPSHOT] Committing/rolling-back live transactions of [127.0.0.1]:5703, UUID: d97526b3-c4ab-49d4-bda0-d089161d705c
02:19:21,593  INFO |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [ClusterService] hz.laughing_swirles.priority-generic-operation.thread-0 - [127.0.0.1]:5704 [dev] [5.3.0-SNAPSHOT] 

Members {size:3, ver:5} [
	Member [127.0.0.1]:5701 - 0efcb126-1369-4d90-bcaa-db93b5382a36
	Member [127.0.0.1]:5702 - 861f0e70-cf92-408a-9b49-3f084cc658b6
	Member [127.0.0.1]:5704 - 964777ef-6dde-4835-af05-a1a8efd9deb2 this
]

02:19:21,593  INFO |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [TransactionManagerService] hz.trusting_swirles.cached.thread-12 - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Committing/rolling-back live transactions of [127.0.0.1]:5703, UUID: d97526b3-c4ab-49d4-bda0-d089161d705c
02:19:21,593  INFO |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [ClusterService] hz.trusting_swirles.priority-generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] 

Members {size:3, ver:5} [
	Member [127.0.0.1]:5701 - 0efcb126-1369-4d90-bcaa-db93b5382a36
	Member [127.0.0.1]:5702 - 861f0e70-cf92-408a-9b49-3f084cc658b6 this
	Member [127.0.0.1]:5704 - 964777ef-6dde-4835-af05-a1a8efd9deb2
]

02:19:21,593  INFO |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [ClusterService] Thread-70321 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] 

Members {size:3, ver:5} [
	Member [127.0.0.1]:5701 - 0efcb126-1369-4d90-bcaa-db93b5382a36 this
	Member [127.0.0.1]:5702 - 861f0e70-cf92-408a-9b49-3f084cc658b6
	Member [127.0.0.1]:5704 - 964777ef-6dde-4835-af05-a1a8efd9deb2
]

02:19:21,594  INFO |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [Node] Thread-70321 - [127.0.0.1]:5703 [dev] [5.3.0-SNAPSHOT] Shutting down node engine...
02:19:21,594  INFO |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [TransactionManagerService] hz.infallible_swirles.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Committing/rolling-back live transactions of [127.0.0.1]:5703, UUID: d97526b3-c4ab-49d4-bda0-d089161d705c
02:19:21,598  INFO |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [NodeExtension] Thread-70321 - [127.0.0.1]:5703 [dev] [5.3.0-SNAPSHOT] Destroying node NodeExtension.
02:19:21,598  INFO |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [Node] Thread-70321 - [127.0.0.1]:5703 [dev] [5.3.0-SNAPSHOT] Hazelcast Shutdown is completed in 6 ms.
02:19:21,599  INFO |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [LifecycleService] Thread-70321 - [127.0.0.1]:5703 [dev] [5.3.0-SNAPSHOT] [127.0.0.1]:5703 is SHUTDOWN
02:19:21,599  INFO |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [LifecycleService] Thread-70321 - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] [127.0.0.1]:5702 is SHUTTING_DOWN
02:19:21,599  WARN |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [Node] Thread-70321 - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Terminating forcefully...
02:19:21,599  INFO |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [Node] Thread-70321 - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Shutting down connection manager...
02:19:21,599  INFO |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [MockServer] Thread-70321 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Removed connection to endpoint: [address=[127.0.0.1]:5702, uuid=861f0e70-cf92-408a-9b49-3f084cc658b6], connection: MockConnection{localEndpoint=[address=[127.0.0.1]:5701, uuid=0efcb126-1369-4d90-bcaa-db93b5382a36], remoteEndpoint=[address=[127.0.0.1]:5702, uuid=861f0e70-cf92-408a-9b49-3f084cc658b6], alive=false}
02:19:21,599  INFO |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [MockServer] Thread-70321 - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Removed connection to endpoint: [address=[127.0.0.1]:5701, uuid=0efcb126-1369-4d90-bcaa-db93b5382a36], connection: MockConnection{localEndpoint=[address=[127.0.0.1]:5702, uuid=861f0e70-cf92-408a-9b49-3f084cc658b6], remoteEndpoint=[address=[127.0.0.1]:5701, uuid=0efcb126-1369-4d90-bcaa-db93b5382a36], alive=false}
02:19:21,599  INFO |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [MockServer] Thread-70321 - [127.0.0.1]:5704 [dev] [5.3.0-SNAPSHOT] Removed connection to endpoint: [address=[127.0.0.1]:5702, uuid=861f0e70-cf92-408a-9b49-3f084cc658b6], connection: MockConnection{localEndpoint=[address=[127.0.0.1]:5704, uuid=964777ef-6dde-4835-af05-a1a8efd9deb2], remoteEndpoint=[address=[127.0.0.1]:5702, uuid=861f0e70-cf92-408a-9b49-3f084cc658b6], alive=false}
02:19:21,599  INFO |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [MockServer] Thread-70321 - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Removed connection to endpoint: [address=[127.0.0.1]:5704, uuid=964777ef-6dde-4835-af05-a1a8efd9deb2], connection: MockConnection{localEndpoint=[address=[127.0.0.1]:5702, uuid=861f0e70-cf92-408a-9b49-3f084cc658b6], remoteEndpoint=[address=[127.0.0.1]:5704, uuid=964777ef-6dde-4835-af05-a1a8efd9deb2], alive=false}
02:19:21,599  WARN |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [MembershipManager] Thread-70321 - [127.0.0.1]:5704 [dev] [5.3.0-SNAPSHOT] Member [127.0.0.1]:5702 - 861f0e70-cf92-408a-9b49-3f084cc658b6 is suspected to be dead for reason: Connection manager is stopped on Member [127.0.0.1]:5702 - 861f0e70-cf92-408a-9b49-3f084cc658b6 this
02:19:21,599  INFO |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [MembershipManager] Thread-70321 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Removing Member [127.0.0.1]:5702 - 861f0e70-cf92-408a-9b49-3f084cc658b6
02:19:21,599  INFO |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [ClusterService] Thread-70321 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] 

Members {size:2, ver:6} [
	Member [127.0.0.1]:5701 - 0efcb126-1369-4d90-bcaa-db93b5382a36 this
	Member [127.0.0.1]:5704 - 964777ef-6dde-4835-af05-a1a8efd9deb2
]

02:19:21,599  INFO |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [TransactionManagerService] hz.infallible_swirles.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Committing/rolling-back live transactions of [127.0.0.1]:5702, UUID: 861f0e70-cf92-408a-9b49-3f084cc658b6
02:19:21,599  INFO |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [Node] Thread-70321 - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Shutting down node engine...
02:19:21,600  INFO |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [TransactionManagerService] hz.laughing_swirles.cached.thread-5 - [127.0.0.1]:5704 [dev] [5.3.0-SNAPSHOT] Committing/rolling-back live transactions of [127.0.0.1]:5702, UUID: 861f0e70-cf92-408a-9b49-3f084cc658b6
02:19:21,600  INFO |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [ClusterService] hz.laughing_swirles.priority-generic-operation.thread-0 - [127.0.0.1]:5704 [dev] [5.3.0-SNAPSHOT] 

Members {size:2, ver:6} [
	Member [127.0.0.1]:5701 - 0efcb126-1369-4d90-bcaa-db93b5382a36
	Member [127.0.0.1]:5704 - 964777ef-6dde-4835-af05-a1a8efd9deb2 this
]

02:19:21,603  INFO |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [NodeExtension] Thread-70321 - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Destroying node NodeExtension.
02:19:21,603  INFO |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [Node] Thread-70321 - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Hazelcast Shutdown is completed in 4 ms.
02:19:21,603  INFO |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [LifecycleService] Thread-70321 - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] [127.0.0.1]:5702 is SHUTDOWN
02:19:21,603  INFO |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [LifecycleService] Thread-70321 - [127.0.0.1]:5704 [dev] [5.3.0-SNAPSHOT] [127.0.0.1]:5704 is SHUTTING_DOWN
02:19:21,603  WARN |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [Node] Thread-70321 - [127.0.0.1]:5704 [dev] [5.3.0-SNAPSHOT] Terminating forcefully...
02:19:21,603  INFO |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [Node] Thread-70321 - [127.0.0.1]:5704 [dev] [5.3.0-SNAPSHOT] Shutting down connection manager...
02:19:21,603  INFO |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [MockServer] Thread-70321 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Removed connection to endpoint: [address=[127.0.0.1]:5704, uuid=964777ef-6dde-4835-af05-a1a8efd9deb2], connection: MockConnection{localEndpoint=[address=[127.0.0.1]:5701, uuid=0efcb126-1369-4d90-bcaa-db93b5382a36], remoteEndpoint=[address=[127.0.0.1]:5704, uuid=964777ef-6dde-4835-af05-a1a8efd9deb2], alive=false}
02:19:21,603  INFO |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [MockServer] Thread-70321 - [127.0.0.1]:5704 [dev] [5.3.0-SNAPSHOT] Removed connection to endpoint: [address=[127.0.0.1]:5701, uuid=0efcb126-1369-4d90-bcaa-db93b5382a36], connection: MockConnection{localEndpoint=[address=[127.0.0.1]:5704, uuid=964777ef-6dde-4835-af05-a1a8efd9deb2], remoteEndpoint=[address=[127.0.0.1]:5701, uuid=0efcb126-1369-4d90-bcaa-db93b5382a36], alive=false}
02:19:21,603  INFO |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [MembershipManager] Thread-70321 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Removing Member [127.0.0.1]:5704 - 964777ef-6dde-4835-af05-a1a8efd9deb2
02:19:21,603  INFO |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [TransactionManagerService] hz.infallible_swirles.cached.thread-10 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Committing/rolling-back live transactions of [127.0.0.1]:5704, UUID: 964777ef-6dde-4835-af05-a1a8efd9deb2
02:19:21,603  INFO |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [ClusterService] Thread-70321 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] 

Members {size:1, ver:7} [
	Member [127.0.0.1]:5701 - 0efcb126-1369-4d90-bcaa-db93b5382a36 this
]

02:19:21,603  INFO |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [Node] Thread-70321 - [127.0.0.1]:5704 [dev] [5.3.0-SNAPSHOT] Shutting down node engine...
02:19:21,607  INFO |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [NodeExtension] Thread-70321 - [127.0.0.1]:5704 [dev] [5.3.0-SNAPSHOT] Destroying node NodeExtension.
02:19:21,607  INFO |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [Node] Thread-70321 - [127.0.0.1]:5704 [dev] [5.3.0-SNAPSHOT] Hazelcast Shutdown is completed in 4 ms.
02:19:21,607  INFO |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [LifecycleService] Thread-70321 - [127.0.0.1]:5704 [dev] [5.3.0-SNAPSHOT] [127.0.0.1]:5704 is SHUTDOWN
02:19:21,607  INFO |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [LifecycleService] Thread-70321 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
02:19:21,607  WARN |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [Node] Thread-70321 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Terminating forcefully...
02:19:21,607  INFO |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [Node] Thread-70321 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Shutting down connection manager...
02:19:21,607  INFO |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [Node] Thread-70321 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Shutting down node engine...
02:19:21,609  INFO |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [NodeExtension] Thread-70321 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Destroying node NodeExtension.
02:19:21,609  INFO |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [Node] Thread-70321 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Hazelcast Shutdown is completed in 2 ms.
02:19:21,609  INFO |testSchemaReplication_whenAMemberThrows_duringPreparationPhase| - [LifecycleService] Thread-70321 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
BuildInfo right after testSchemaReplication_whenAMemberThrows_duringPreparationPhase(com.hazelcast.internal.serialization.impl.compact.schema.CompactSchemaReplicationTest): BuildInfo{version='5.3.0-SNAPSHOT', build='20221201', buildNumber=20221201, revision=2e15289, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'testSchemaReplication_whenAMemberThrows_duringPreparationPhase(com.hazelcast.internal.serialization.impl.compact.schema.CompactSchemaReplicationTest):'
02:19:15, accumulated pauses: 4989 ms, max pause: 1523 ms, pauses over 1000 ms: 1
02:19:20, accumulated pauses: 1592 ms, max pause: 10 ms, pauses over 1000 ms: 0


No metrics recorded during the test

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-sonar/1413/

**Comment by mdumandag** [comment]
Possibly related to this one https://github.com/hazelcast/hazelcast/issues/22175
