### ISSUE TITLE
com.hazelcast.jet.mongodb.MongoDB* tests fail with "Could not find a valid Docker environment."

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hazelcast#23202]
_master_ (commit 4f848dc1a2f740dcda30c7f9ce36aec5ed9ce52e)

Failed on Windows - MicrosoftJDK11: https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK11/43/

Example stacktrace and stdout from `com.hazelcast.jet.mongodb.MongoDBSinkTest.test_whenServerNotAvailable`
<details><summary>Stacktrace:</summary>

```
java.lang.IllegalStateException: Could not find a valid Docker environment. Please see logs and check configuration
	at org.testcontainers.dockerclient.DockerClientProviderStrategy.lambda$getFirstValidStrategy$7(DockerClientProviderStrategy.java:256)
	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
	at org.testcontainers.dockerclient.DockerClientProviderStrategy.getFirstValidStrategy(DockerClientProviderStrategy.java:247)
	at org.testcontainers.DockerClientFactory.getOrInitializeStrategy(DockerClientFactory.java:150)
	at org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:186)
	at org.testcontainers.DockerClientFactory$1.getDockerClient(DockerClientFactory.java:104)
	at com.github.dockerjava.api.DockerClientDelegate.authConfig(DockerClientDelegate.java:108)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:321)
	at org.testcontainers.containers.GenericContainer.starting(GenericContainer.java:1094)
	at org.testcontainers.containers.FailureDetectingExternalResource$1.evaluate(FailureDetectingExternalResource.java:28)
	at com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37)
	at com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:104)
	at com.hazelcast.test.metrics.MetricsRule$1.evaluate(MetricsRule.java:63)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at com.hazelcast.test.OverridePropertyRule$1.evaluate(OverridePropertyRule.java:66)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:829)

```
</details>
<details><summary>Standard output:</summary>

```
BuildInfo right after test_whenServerNotAvailable(com.hazelcast.jet.mongodb.MongoDBSinkTest): BuildInfo{version='5.3.0-SNAPSHOT', build='20221215', buildNumber=20221215, revision=4f848dc, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'test_whenServerNotAvailable(com.hazelcast.jet.mongodb.MongoDBSinkTest):'
20:50:55, accumulated pauses: 23 ms, max pause: 6 ms, pauses over 1000 ms: 0


No metrics recorded during the test

```
</details>

**Comment by TomaszGaweda** [comment]
assumeDockerEnabled() is missing. It will be fixed once MongoDB read/write processors PR is merged

**Comment by olukas** [comment]
Still fails on _master_ with Windows - MicrosoftJDK11: https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK11/52/testReport/com.hazelcast.jet.mongodb/MongoDBSinkTest/___/
