### ISSUE TITLE
com.hazelcast.internal.crdt.pncounter.PNCounterConsistencyLostTest.consistencyLostExceptionIsThrownWhenTargetReplicaDisappears

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hazelcast#23203]
_master_ (commit 4f848dc1a2f740dcda30c7f9ce36aec5ed9ce52e)

Failed on OpenJDK: https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK-sts/17/testReport/junit/com.hazelcast.internal.crdt.pncounter/PNCounterConsistencyLostTest/consistencyLostExceptionIsThrownWhenTargetReplicaDisappears/
<details><summary>Stacktrace:</summary>

```
java.lang.Exception: Unexpected exception, expected<com.hazelcast.core.ConsistencyLostException> but was<java.lang.IllegalStateException>
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:30)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: java.lang.IllegalStateException: Attempt to reuse the same operation in multiple invocations. Operation is com.hazelcast.internal.crdt.pncounter.operations.AddOperation{serviceName='hz:impl:PNCounterService', identityHash=1136223929, partitionId=-1, replicaIndex=0, callId=-4, invocationTime=1671124688343 (2022-12-15 17:18:08.343), waitTimeout=-1, callTimeout=60000, tenantControl=com.hazelcast.spi.impl.tenantcontrol.NoopTenantControl@0, name=counter}
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:545)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:241)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:71)
	at com.hazelcast.internal.crdt.pncounter.PNCounterProxy.invokeInternal(PNCounterProxy.java:195)
	at com.hazelcast.internal.crdt.pncounter.PNCounterProxy.invokeInternal(PNCounterProxy.java:205)
	at com.hazelcast.internal.crdt.pncounter.PNCounterProxy.invoke(PNCounterProxy.java:159)
	at com.hazelcast.internal.crdt.pncounter.PNCounterProxy.addAndGet(PNCounterProxy.java:100)
	at com.hazelcast.internal.crdt.pncounter.PNCounterConsistencyLostTest.mutate(PNCounterConsistencyLostTest.java:80)
	at com.hazelcast.internal.crdt.pncounter.AbstractPNCounterConsistencyLostTest.consistencyLostExceptionIsThrownWhenTargetReplicaDisappears(AbstractPNCounterConsistencyLostTest.java:44)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)
	... 4 more

```
</details>
<details><summary>Standard output:</summary>

```
Finished Running Test: driverCanContinueSessionByCallingReset in 0.449 seconds.
17:18:08,566  INFO |consistencyLostExceptionIsThrownWhenTargetReplicaDisappears| - [LifecycleService] Thread-42559 - [127.0.0.1]:5703 [dev] [5.3.0-SNAPSHOT] [127.0.0.1]:5703 is SHUTTING_DOWN
17:18:08,566  WARN |consistencyLostExceptionIsThrownWhenTargetReplicaDisappears| - [Node] Thread-42559 - [127.0.0.1]:5703 [dev] [5.3.0-SNAPSHOT] Terminating forcefully...
17:18:08,566  INFO |consistencyLostExceptionIsThrownWhenTargetReplicaDisappears| - [Node] Thread-42559 - [127.0.0.1]:5703 [dev] [5.3.0-SNAPSHOT] Shutting down connection manager...
17:18:08,566  INFO |consistencyLostExceptionIsThrownWhenTargetReplicaDisappears| - [MockServer] Thread-42559 - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Removed connection to endpoint: [address=[127.0.0.1]:5703, uuid=28862ca1-f11e-4910-bb80-75ff45b14919], connection: MockConnection{localEndpoint=[address=[127.0.0.1]:5702, uuid=2f268ffd-c35a-49d0-9be7-af98830b3f5d], remoteEndpoint=[address=[127.0.0.1]:5703, uuid=28862ca1-f11e-4910-bb80-75ff45b14919], alive=false}
17:18:08,566  INFO |consistencyLostExceptionIsThrownWhenTargetReplicaDisappears| - [MockServer] Thread-42559 - [127.0.0.1]:5703 [dev] [5.3.0-SNAPSHOT] Removed connection to endpoint: [address=[127.0.0.1]:5702, uuid=2f268ffd-c35a-49d0-9be7-af98830b3f5d], connection: MockConnection{localEndpoint=[address=[127.0.0.1]:5703, uuid=28862ca1-f11e-4910-bb80-75ff45b14919], remoteEndpoint=[address=[127.0.0.1]:5702, uuid=2f268ffd-c35a-49d0-9be7-af98830b3f5d], alive=false}
17:18:08,566  INFO |consistencyLostExceptionIsThrownWhenTargetReplicaDisappears| - [MembershipManager] Thread-42559 - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Removing Member [127.0.0.1]:5703 - 28862ca1-f11e-4910-bb80-75ff45b14919 lite
17:18:08,566  INFO |consistencyLostExceptionIsThrownWhenTargetReplicaDisappears| - [ClusterService] Thread-42559 - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] 

Members {size:1, ver:5} [
	Member [127.0.0.1]:5702 - 2f268ffd-c35a-49d0-9be7-af98830b3f5d this
]

17:18:08,566  INFO |consistencyLostExceptionIsThrownWhenTargetReplicaDisappears| - [Node] Thread-42559 - [127.0.0.1]:5703 [dev] [5.3.0-SNAPSHOT] Shutting down node engine...
17:18:08,566  INFO |consistencyLostExceptionIsThrownWhenTargetReplicaDisappears| - [TransactionManagerService] hz.PNCounterConsistencyLostTest_recursing_clifford.cached.thread-4 - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Committing/rolling-back live transactions of [127.0.0.1]:5703, UUID: 28862ca1-f11e-4910-bb80-75ff45b14919
17:18:08,567  INFO |consistencyLostExceptionIsThrownWhenTargetReplicaDisappears| - [NodeExtension] Thread-42559 - [127.0.0.1]:5703 [dev] [5.3.0-SNAPSHOT] Destroying node NodeExtension.
17:18:08,568  INFO |consistencyLostExceptionIsThrownWhenTargetReplicaDisappears| - [Node] Thread-42559 - [127.0.0.1]:5703 [dev] [5.3.0-SNAPSHOT] Hazelcast Shutdown is completed in 2 ms.
17:18:08,568  INFO |consistencyLostExceptionIsThrownWhenTargetReplicaDisappears| - [LifecycleService] Thread-42559 - [127.0.0.1]:5703 [dev] [5.3.0-SNAPSHOT] [127.0.0.1]:5703 is SHUTDOWN
17:18:08,568  INFO |consistencyLostExceptionIsThrownWhenTargetReplicaDisappears| - [LifecycleService] Thread-42559 - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] [127.0.0.1]:5702 is SHUTTING_DOWN
17:18:08,568  WARN |consistencyLostExceptionIsThrownWhenTargetReplicaDisappears| - [Node] Thread-42559 - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Terminating forcefully...
17:18:08,568  INFO |consistencyLostExceptionIsThrownWhenTargetReplicaDisappears| - [Node] Thread-42559 - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Shutting down connection manager...
17:18:08,568  INFO |consistencyLostExceptionIsThrownWhenTargetReplicaDisappears| - [Node] Thread-42559 - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Shutting down node engine...
17:18:08,570  INFO |consistencyLostExceptionIsThrownWhenTargetReplicaDisappears| - [NodeExtension] Thread-42559 - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Destroying node NodeExtension.
17:18:08,570  INFO |consistencyLostExceptionIsThrownWhenTargetReplicaDisappears| - [Node] Thread-42559 - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Hazelcast Shutdown is completed in 2 ms.
17:18:08,570  INFO |consistencyLostExceptionIsThrownWhenTargetReplicaDisappears| - [LifecycleService] Thread-42559 - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] [127.0.0.1]:5702 is SHUTDOWN
17:18:08,570  INFO |consistencyLostExceptionIsThrownWhenTargetReplicaDisappears| - [LifecycleService] Thread-42559 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
17:18:08,570  INFO |consistencyLostExceptionIsThrownWhenTargetReplicaDisappears| - [Node] Thread-42559 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Node is already shutting down... Waiting for shutdown process to complete...
17:18:08,570  INFO |consistencyLostExceptionIsThrownWhenTargetReplicaDisappears| - [LifecycleService] Thread-42559 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
BuildInfo right after consistencyLostExceptionIsThrownWhenTargetReplicaDisappears(com.hazelcast.internal.crdt.pncounter.PNCounterConsistencyLostTest): BuildInfo{version='5.3.0-SNAPSHOT', build='20221215', buildNumber=20221215, revision=4f848dc, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'consistencyLostExceptionIsThrownWhenTargetReplicaDisappears(com.hazelcast.internal.crdt.pncounter.PNCounterConsistencyLostTest):'
17:18:05, accumulated pauses: 236 ms, max pause: 191 ms, pauses over 1000 ms: 0


No metrics recorded during the test

```
</details>

**Comment by vbekiaris** [comment]
`PNCounter` operation retries should not reuse the same `operation` instance [here](https://github.com/hazelcast/hazelcast/blob/7c3894b1474dba56648cf10ad8441615486fcdea/hazelcast/src/main/java/com/hazelcast/internal/crdt/pncounter/PNCounterProxy.java#L205)

**Comment by sumnerib** [comment]
Failed again on _5.2.z_ with oracle-8: https://jenkins.hazelcast.com/job/Hazelcast-5.2.z-OracleJDK8/17/testReport/junit/com.hazelcast.internal.crdt.pncounter/PNCounterConsistencyLostTest/consistencyLostExceptionIsThrownWhenTargetReplicaDisappears/
