### ISSUE TITLE
com.hazelcast.internal.cluster.impl.MembershipUpdateTest.testListenerRegistrationWhileANewMemberJoining [HZ-2219]

### ISSUE THREAD

**Issue by Patras3** [hazelcast/hazelcast#23214]
_master_ (commit 890f941868313e6827d1b0b8feb57130846bc232)

Failed on zing-8: https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK8/475/testReport/junit/com.hazelcast.internal.cluster.impl/MembershipUpdateTest/testListenerRegistrationWhileANewMemberJoining/
<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: CountDownLatch failed to complete within 120 seconds, count left: 1
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:1154)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:1139)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:1127)
	at com.hazelcast.internal.cluster.impl.MembershipUpdateTest.testListenerRegistrationWhileANewMemberJoining(MembershipUpdateTest.java:760)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:807)

```
</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: noOperationExecuted_beforePreJoinOpIsDone in 15.090 seconds.
02:05:19,653  INFO |testListenerRegistrationWhileANewMemberJoining| - [HealthMonitor] hz.MembershipUpdateTest_goofy_brahmagupta.HealthMonitor - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] processors=8, physical.memory.total=754.6G, physical.memory.free=642.4G, swap.space.total=8.0G, swap.space.free=8.0G, heap.memory.used=4.6G, heap.memory.free=3.4G, heap.memory.total=8.0G, heap.memory.max=8.0G, heap.memory.used/total=57.42%, heap.memory.used/max=57.42%, minor.gc.count=0, minor.gc.time=0ms, major.gc.count=0, major.gc.time=0ms, unknown.gc.count=303, unknown.gc.time=118858ms, load.process=0.00%, load.system=0.00%, load.systemAverage=23.02, thread.count=143, thread.peakCount=1524, cluster.timeDiff=0, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=2749, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=1, clientEndpoint.count=0, connection.active.count=0, client.connection.count=0, connection.count=0
02:05:39,654  INFO |testListenerRegistrationWhileANewMemberJoining| - [HealthMonitor] hz.MembershipUpdateTest_goofy_brahmagupta.HealthMonitor - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] processors=8, physical.memory.total=754.6G, physical.memory.free=642.2G, swap.space.total=8.0G, swap.space.free=8.0G, heap.memory.used=4.7G, heap.memory.free=3.3G, heap.memory.total=8.0G, heap.memory.max=8.0G, heap.memory.used/total=58.15%, heap.memory.used/max=58.15%, minor.gc.count=0, minor.gc.time=0ms, major.gc.count=0, major.gc.time=0ms, unknown.gc.count=303, unknown.gc.time=118858ms, load.process=0.00%, load.system=0.00%, load.systemAverage=19.01, thread.count=144, thread.peakCount=1524, cluster.timeDiff=0, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=5474, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=1, clientEndpoint.count=0, connection.active.count=0, client.connection.count=0, connection.count=0
02:06:59,288  INFO |testListenerRegistrationWhileANewMemberJoining| - [HealthMonitor] hz.MembershipUpdateTest_admiring_brahmagupta.HealthMonitor - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] processors=8, physical.memory.total=754.6G, physical.memory.free=641.7G, swap.space.total=8.0G, swap.space.free=8.0G, heap.memory.used=4.9G, heap.memory.free=3.1G, heap.memory.total=8.0G, heap.memory.max=8.0G, heap.memory.used/total=61.13%, heap.memory.used/max=61.13%, minor.gc.count=0, minor.gc.time=0ms, major.gc.count=0, major.gc.time=0ms, unknown.gc.count=303, unknown.gc.time=118858ms, load.process=0.00%, load.system=0.00%, load.systemAverage=17.96, thread.count=147, thread.peakCount=1524, cluster.timeDiff=0, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=16101, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=1, clientEndpoint.count=0, connection.active.count=0, client.connection.count=0, connection.count=0
02:06:59,689  INFO |testListenerRegistrationWhileANewMemberJoining| - [LifecycleService] Thread-41617 - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] [127.0.0.1]:5702 is SHUTTING_DOWN
02:06:59,690  WARN |testListenerRegistrationWhileANewMemberJoining| - [Node] Thread-41617 - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Terminating forcefully...
02:06:59,690  INFO |testListenerRegistrationWhileANewMemberJoining| - [Node] Thread-41617 - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Shutting down connection manager...
02:06:59,690  INFO |testListenerRegistrationWhileANewMemberJoining| - [MockServer] Thread-41617 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Removed connection to endpoint: [address=[127.0.0.1]:5702, uuid=9c31a230-4c95-47d2-815b-8de285bc41c6], connection: MockConnection{localEndpoint=[address=[127.0.0.1]:5701, uuid=bb041305-50e1-479f-97ff-5516ad2ecb1e], remoteEndpoint=[address=[127.0.0.1]:5702, uuid=9c31a230-4c95-47d2-815b-8de285bc41c6], alive=false}
02:06:59,690  INFO |testListenerRegistrationWhileANewMemberJoining| - [MockServer] Thread-41617 - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Removed connection to endpoint: [address=[127.0.0.1]:5701, uuid=bb041305-50e1-479f-97ff-5516ad2ecb1e], connection: MockConnection{localEndpoint=[address=[127.0.0.1]:5702, uuid=9c31a230-4c95-47d2-815b-8de285bc41c6], remoteEndpoint=[address=[127.0.0.1]:5701, uuid=bb041305-50e1-479f-97ff-5516ad2ecb1e], alive=false}
02:06:59,690  INFO |testListenerRegistrationWhileANewMemberJoining| - [MembershipManager] Thread-41617 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Removing Member [127.0.0.1]:5702 - 9c31a230-4c95-47d2-815b-8de285bc41c6
02:06:59,690  INFO |testListenerRegistrationWhileANewMemberJoining| - [PartitionStateManager] Thread-41617 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Storing snapshot of partition assignments while removing UUID 9c31a230-4c95-47d2-815b-8de285bc41c6
02:06:59,690  INFO |testListenerRegistrationWhileANewMemberJoining| - [ClusterService] Thread-41617 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] 

Members {size:1, ver:3} [
	Member [127.0.0.1]:5701 - bb041305-50e1-479f-97ff-5516ad2ecb1e this
]

02:06:59,690  INFO |testListenerRegistrationWhileANewMemberJoining| - [Node] Thread-41617 - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Shutting down node engine...
02:06:59,695  INFO |testListenerRegistrationWhileANewMemberJoining| - [TransactionManagerService] hz.MembershipUpdateTest_admiring_brahmagupta.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Committing/rolling-back live transactions of [127.0.0.1]:5702, UUID: 9c31a230-4c95-47d2-815b-8de285bc41c6
02:06:59,731  INFO |testListenerRegistrationWhileANewMemberJoining| - [NodeExtension] Thread-41617 - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Destroying node NodeExtension.
02:06:59,731  INFO |testListenerRegistrationWhileANewMemberJoining| - [Node] Thread-41617 - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Hazelcast Shutdown is completed in 41 ms.
02:06:59,731  INFO |testListenerRegistrationWhileANewMemberJoining| - [LifecycleService] Thread-41617 - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] [127.0.0.1]:5702 is SHUTDOWN
02:06:59,731  INFO |testListenerRegistrationWhileANewMemberJoining| - [LifecycleService] Thread-41617 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
02:06:59,731  WARN |testListenerRegistrationWhileANewMemberJoining| - [Node] Thread-41617 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Terminating forcefully...
02:06:59,731  INFO |testListenerRegistrationWhileANewMemberJoining| - [Node] Thread-41617 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Shutting down connection manager...
02:06:59,731  INFO |testListenerRegistrationWhileANewMemberJoining| - [Node] Thread-41617 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Shutting down node engine...
02:06:59,739  INFO |testListenerRegistrationWhileANewMemberJoining| - [MigrationManager] hz.MembershipUpdateTest_admiring_brahmagupta.migration - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Partition balance is ok, no need to repartition.
02:06:59,743  INFO |testListenerRegistrationWhileANewMemberJoining| - [NodeExtension] Thread-41617 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Destroying node NodeExtension.
02:06:59,743  INFO |testListenerRegistrationWhileANewMemberJoining| - [Node] Thread-41617 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Hazelcast Shutdown is completed in 12 ms.
02:06:59,744  INFO |testListenerRegistrationWhileANewMemberJoining| - [LifecycleService] Thread-41617 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
BuildInfo right after testListenerRegistrationWhileANewMemberJoining(com.hazelcast.internal.cluster.impl.MembershipUpdateTest): BuildInfo{version='5.3.0-SNAPSHOT', build='20221219', buildNumber=20221219, revision=890f941, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'testListenerRegistrationWhileANewMemberJoining(com.hazelcast.internal.cluster.impl.MembershipUpdateTest):'
02:04:55, accumulated pauses: 4970 ms, max pause: 16 ms, pauses over 1000 ms: 0
02:05:00, accumulated pauses: 4965 ms, max pause: 16 ms, pauses over 1000 ms: 0
02:05:05, accumulated pauses: 4975 ms, max pause: 13 ms, pauses over 1000 ms: 0
02:05:10, accumulated pauses: 4969 ms, max pause: 16 ms, pauses over 1000 ms: 0
02:05:15, accumulated pauses: 4965 ms, max pause: 10 ms, pauses over 1000 ms: 0
02:05:20, accumulated pauses: 4963 ms, max pause: 10 ms, pauses over 1000 ms: 0
02:05:25, accumulated pauses: 4973 ms, max pause: 10 ms, pauses over 1000 ms: 0
02:05:30, accumulated pauses: 4972 ms, max pause: 13 ms, pauses over 1000 ms: 0
02:05:35, accumulated pauses: 4967 ms, max pause: 10 ms, pauses over 1000 ms: 0
02:05:40, accumulated pauses: 4966 ms, max pause: 10 ms, pauses over 1000 ms: 0
02:05:45, accumulated pauses: 4968 ms, max pause: 10 ms, pauses over 1000 ms: 0
02:05:50, accumulated pauses: 4969 ms, max pause: 10 ms, pauses over 1000 ms: 0
02:05:55, accumulated pauses: 4967 ms, max pause: 10 ms, pauses over 1000 ms: 0
02:06:00, accumulated pauses: 4971 ms, max pause: 10 ms, pauses over 1000 ms: 0
02:06:05, accumulated pauses: 4974 ms, max pause: 10 ms, pauses over 1000 ms: 0
02:06:10, accumulated pauses: 4967 ms, max pause: 13 ms, pauses over 1000 ms: 0
02:06:15, accumulated pauses: 4970 ms, max pause: 11 ms, pauses over 1000 ms: 0
02:06:20, accumulated pauses: 4967 ms, max pause: 10 ms, pauses over 1000 ms: 0
02:06:25, accumulated pauses: 4967 ms, max pause: 10 ms, pauses over 1000 ms: 0
02:06:30, accumulated pauses: 4968 ms, max pause: 14 ms, pauses over 1000 ms: 0
02:06:35, accumulated pauses: 4967 ms, max pause: 13 ms, pauses over 1000 ms: 0
02:06:40, accumulated pauses: 4969 ms, max pause: 10 ms, pauses over 1000 ms: 0
02:06:45, accumulated pauses: 4972 ms, max pause: 10 ms, pauses over 1000 ms: 0
02:06:50, accumulated pauses: 4973 ms, max pause: 10 ms, pauses over 1000 ms: 0
02:06:55, accumulated pauses: 4697 ms, max pause: 23 ms, pauses over 1000 ms: 0



```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-ZingJDK8/475/

**Comment by sumnerib** [comment]
Failed again on _master_ with microsoft-11: https://jenkins.hazelcast.com/job/Hazelcast-master-MicrosoftJDK11/46/testReport/junit/com.hazelcast.internal.cluster.impl/MembershipUpdateTest/testListenerRegistrationWhileANewMemberJoining/

**Comment by orcunc** [comment]
This test requires to HZ instances to start but according to test output only 1 HZ instance has started. Hence the test failed

**Comment by Patras3** [comment]
Failed again on _master_ with openjdk-8: https://jenkins.hazelcast.com/job/Hazelcast-master-ZuluJDK8/225/testReport/junit/com.hazelcast.internal.cluster.impl/MembershipUpdateTest/testListenerRegistrationWhileANewMemberJoining/

**Comment by olukas** [comment]
Failed again on _master_ with Windows - MicrosoftJDK17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Windows-MicrosoftJDK17/50/testReport/com.hazelcast.internal.cluster.impl/MembershipUpdateTest/testListenerRegistrationWhileANewMemberJoining/

**Comment by olukas** [comment]
Failed again on _master_ with Windows - OracleJDK8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Windows-OracleJDK8/436/testReport/com.hazelcast.internal.cluster.impl/MembershipUpdateTest/testListenerRegistrationWhileANewMemberJoining/

**Comment by Fly-Style** [comment]
Failed again on that PR : https://github.com/hazelcast/hazelcast/pull/23595

**Comment by olukas** [comment]
Reopening as issue occurred again on: _master_ (commit bdd14813949602290d6364d1ad9862194e740462)
with Windows - MicrosoftJDK11: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Windows-MicrosoftJDK11/62/testReport/com.hazelcast.internal.cluster.impl/MembershipUpdateTest/testListenerRegistrationWhileANewMemberJoining/
<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: CountDownLatch failed to complete within 120 seconds, count left: 1
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:1167)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:1152)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:1140)
	at com.hazelcast.internal.cluster.impl.MembershipUpdateTest.testListenerRegistrationWhileANewMemberJoining(MembershipUpdateTest.java:817)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:829)

```
</details>



Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-Windows-MicrosoftJDK11/62/

**Comment by olukas** [comment]
Failed again on _master_ with Windows - OracleJDK8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Windows-OracleJDK8/444/testReport/com.hazelcast.internal.cluster.impl/MembershipUpdateTest/testListenerRegistrationWhileANewMemberJoining/

**Comment by olukas** [comment]
Failed again on _master_ with corretto-8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-CorrettoJDK8/226/testReport/com.hazelcast.internal.cluster.impl/MembershipUpdateTest/testListenerRegistrationWhileANewMemberJoining/

**Comment by olukas** [comment]
Failed again on _master_ with Windows - MicrosoftJDK11: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Windows-MicrosoftJDK11/65/testReport/com.hazelcast.internal.cluster.impl/MembershipUpdateTest/testListenerRegistrationWhileANewMemberJoining/
