### ISSUE TITLE
com.hazelcast.jet.core.metrics.JobMetrics_StressTest.suspend_resume_stressTest

### ISSUE THREAD

**Issue by Patras3** [hazelcast/hazelcast#23222]
_master_ (commit 8aff0fed4d43802ce82cae88c90d33518388d7bd)

Failed on openjdk-19: https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK-sts-nightly/8/testReport/junit/com.hazelcast.jet.core.metrics/JobMetrics_StressTest/suspend_resume_stressTest/
<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: expected:<704> but was:<640>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at com.hazelcast.jet.core.metrics.JobMetrics_StressTest$ObtainMetricsThread.lambda$run$0(JobMetrics_StressTest.java:229)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1273)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1290)
	at com.hazelcast.jet.core.metrics.JobMetrics_StressTest$ObtainMetricsThread.run(JobMetrics_StressTest.java:224)
	at java.base/java.lang.Thread.run(Thread.java:1589)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-OpenJDK-sts-nightly/8/

**Comment by olukas** [comment]
Failed again on _master_ with openjdk-17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZuluJDK17-nightly/90/testReport/com.hazelcast.jet.core.metrics/JobMetrics_StressTest/suspend_resume_stressTest/

**Comment by k-jamroz** [comment]
I suspect this may be caused by glitch when colllecting metrics. The test assumes that metrics will be collected after 1,2s (when configured period is 1s) but in case of high load this might not happen. See `WAIT_FOR_METRICS_COLLECTION_TIME`

**Comment by olukas** [comment]
Failed again on _master_ with oracle-17 (force-offload): https://jenkins.hazelcast.com/job/Hazelcast-master-nightly-force-offload/91/testReport/com.hazelcast.jet.core.metrics/JobMetrics_StressTest/suspend_resume_stressTest/

**Comment by AleksPeychev** [comment]
Failed again on _master_ with openjdk-17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZuluJDK17-nightly/117/testReport/junit/com.hazelcast.jet.core.metrics/JobMetrics_StressTest/suspend_resume_stressTest/

**Comment by sumnerib** [comment]
Failed again on _5.4.z_ with openjdk-17: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-ZuluJDK17-nightly/122/testReport/com.hazelcast.jet.core.metrics/JobMetrics_StressTest/suspend_resume_stressTest/

**Comment by AleksPeychev** [comment]
Failed again on _master_ with zing-21: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZingJDK21-nightly/27/testReport/junit/com.hazelcast.jet.core.metrics/JobMetrics_StressTest/suspend_resume_stressTest/

**Comment by olukas** [comment]
Failed again on _5.4.z_ with oracle-21: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-OracleJDK21-nightly/11/testReport/com.hazelcast.jet.core.metrics/JobMetrics_StressTest/suspend_resume_stressTest/

**Comment by olukas** [comment]
Failed again on _5.5.0_ with oracle --version-by-pom: https://jenkins.hazelcast.com/view/Release/job/Hazelcast-5.releaseBranch-nightly/10/testReport/com.hazelcast.jet.core.metrics/JobMetrics_StressTest/suspend_resume_stressTest/

**Comment by sumnerib** [comment]
Failed again on _master_ with openjdk-17: https://jenkins.hazelcast.com/job/Hazelcast-master-ZuluJDK17-nightly/128/testReport/junit/com.hazelcast.jet.core.metrics/JobMetrics_StressTest/suspend_resume_stressTest/

**Comment by Patras3** [comment]
This comment was automatically generated to summarize test results for the last 30 days.

```

For branch: master
Builds between : 2024-07-03 03:15 - 2024-07-31 03:15
Jobs: 9, Runs: 30, Passed: 27, Failed: 3, Skipped: 0, Fail Ratio: 10.00%
Run on:
+--------------------------------------------------+
| JDK        | PASSED | FAILED | SKIPPED |  RATIO  |
+--------------------------------------------------+
| zing-21    |   3    |   1    |    0    |  25.00% |
| openjdk-17 |   3    |   1    |    0    |  25.00% |
| oracle-17  |   4    |   1    |    0    |  20.00% |
| unknown    |   7    |   0    |    0    |   0.00% |
| openj9-21  |   3    |   0    |    0    |   0.00% |
| oracle-21  |   4    |   0    |    0    |   0.00% |
| zing-17    |   3    |   0    |    0    |   0.00% |
+--------------------------------------------------+
Note: Passing since 2024-07-26 03:14

Builds Timeline:
2024-07-31 03:15 - PASSED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK17-nightly-Esxi7/99/testReport/com.hazelcast.jet.core.metrics/JobMetrics_StressTest/suspend_resume_stressTest/
2024-07-31 03:08 - PASSED (oracle-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-OracleJDK21-nightly/28/testReport/com.hazelcast.jet.core.metrics/JobMetrics_StressTest/suspend_resume_stressTest/
2024-07-29 03:12 - PASSED (openj9-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-Openj9-21-nightly/29/testReport/com.hazelcast.jet.core.metrics/JobMetrics_StressTest/suspend_resume_stressTest/
2024-07-28 18:11 - PASSED (zing-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK21-nightly/32/testReport/com.hazelcast.jet.core.metrics/JobMetrics_StressTest/suspend_resume_stressTest/
2024-07-28 12:12 - PASSED (oracle-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-nightly-force-offload/111/testReport/com.hazelcast.jet.core.metrics/JobMetrics_StressTest/suspend_resume_stressTest/
2024-07-27 00:07 - PASSED (oracle-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-nightly-little-endian/89/testReport/com.hazelcast.jet.core.metrics/JobMetrics_StressTest/suspend_resume_stressTest/
2024-07-26 18:06 - PASSED (zing-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK17-nightly/91/testReport/com.hazelcast.jet.core.metrics/JobMetrics_StressTest/suspend_resume_stressTest/
2024-07-26 03:14 - REGRESSION (openjdk-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-ZuluJDK17-nightly/128/testReport/com.hazelcast.jet.core.metrics/JobMetrics_StressTest/suspend_resume_stressTest/
2024-07-24 21:52 - PASSED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-CorrettoJDK17-arm64-nightly/26/testReport/com.hazelcast.jet.core.metrics/JobMetrics_StressTest/suspend_resume_stressTest/
2024-07-24 03:15 - PASSED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK17-nightly-Esxi7/98/testReport/com.hazelcast.jet.core.metrics/JobMetrics_StressTest/suspend_resume_stressTest/
2024-07-24 03:08 - PASSED (oracle-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-OracleJDK21-nightly/27/testReport/com.hazelcast.jet.core.metrics/JobMetrics_StressTest/suspend_resume_stressTest/
2024-07-22 03:12 - PASSED (openj9-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-Openj9-21-nightly/28/testReport/com.hazelcast.jet.core.metrics/JobMetrics_StressTest/suspend_resume_stressTest/
2024-07-21 18:11 - FIXED (zing-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK21-nightly/31/testReport/com.hazelcast.jet.core.metrics/JobMetrics_StressTest/suspend_resume_stressTest/
2024-07-20 00:07 - FIXED (oracle-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-nightly-little-endian/88/testReport/com.hazelcast.jet.core.metrics/JobMetrics_StressTest/suspend_resume_stressTest/
2024-07-19 18:06 - PASSED (zing-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK17-nightly/90/testReport/com.hazelcast.jet.core.metrics/JobMetrics_StressTest/suspend_resume_stressTest/
2024-07-19 03:14 - PASSED (openjdk-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-ZuluJDK17-nightly/127/testReport/com.hazelcast.jet.core.metrics/JobMetrics_StressTest/suspend_resume_stressTest/
2024-07-14 18:11 - REGRESSION (zing-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK21-nightly/30/testReport/com.hazelcast.jet.core.metrics/JobMetrics_StressTest/suspend_resume_stressTest/
2024-07-13 00:07 - REGRESSION (oracle-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-nightly-little-endian/87/testReport/com.hazelcast.jet.core.metrics/JobMetrics_StressTest/suspend_resume_stressTest/
2024-07-12 03:14 - PASSED (openjdk-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-ZuluJDK17-nightly/126/testReport/com.hazelcast.jet.core.metrics/JobMetrics_StressTest/suspend_resume_stressTest/
2024-07-10 21:52 - PASSED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-CorrettoJDK17-arm64-nightly/24/testReport/com.hazelcast.jet.core.metrics/JobMetrics_StressTest/suspend_resume_stressTest/
2024-07-10 09:10 - PASSED (zing-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK21-nightly/29/testReport/com.hazelcast.jet.core.metrics/JobMetrics_StressTest/suspend_resume_stressTest/
2024-07-10 03:15 - PASSED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK17-nightly-Esxi7/96/testReport/com.hazelcast.jet.core.metrics/JobMetrics_StressTest/suspend_resume_stressTest/
2024-07-10 03:08 - PASSED (oracle-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-OracleJDK21-nightly/25/testReport/com.hazelcast.jet.core.metrics/JobMetrics_StressTest/suspend_resume_stressTest/
2024-07-08 03:12 - PASSED (openj9-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-Openj9-21-nightly/26/testReport/com.hazelcast.jet.core.metrics/JobMetrics_StressTest/suspend_resume_stressTest/
2024-07-06 00:07 - PASSED (oracle-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-nightly-little-endian/86/testReport/com.hazelcast.jet.core.metrics/JobMetrics_StressTest/suspend_resume_stressTest/
2024-07-05 18:06 - PASSED (zing-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK17-nightly/88/testReport/com.hazelcast.jet.core.metrics/JobMetrics_StressTest/suspend_resume_stressTest/
2024-07-05 03:14 - PASSED (openjdk-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-ZuluJDK17-nightly/125/testReport/com.hazelcast.jet.core.metrics/JobMetrics_StressTest/suspend_resume_stressTest/
2024-07-03 21:52 - PASSED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-CorrettoJDK17-arm64-nightly/23/testReport/com.hazelcast.jet.core.metrics/JobMetrics_StressTest/suspend_resume_stressTest/
2024-07-03 03:28 - PASSED (oracle-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-OracleJDK21-nightly/24/testReport/com.hazelcast.jet.core.metrics/JobMetrics_StressTest/suspend_resume_stressTest/
2024-07-03 03:15 - PASSED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK17-nightly-Esxi7/95/testReport/com.hazelcast.jet.core.metrics/JobMetrics_StressTest/suspend_resume_stressTest/

----------------------------------------

For branch: 5.5.z
Builds between : 2024-07-31 18:08 - 2024-07-31 18:08
Jobs: 1, Runs: 1, Passed: 1, Failed: 0, Skipped: 0, Fail Ratio: 0.00%
Run on:
+--------------------------------------------------+
| JDK        | PASSED | FAILED | SKIPPED |  RATIO  |
+--------------------------------------------------+
| openjdk-17 |   1    |   0    |    0    |   0.00% |
+--------------------------------------------------+

Builds Timeline:
2024-07-31 18:08 - PASSED (openjdk-17):
    https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-ZuluJDK17-nightly/128/testReport/com.hazelcast.jet.core.metrics/JobMetrics_StressTest/suspend_resume_stressTest/

----------------------------------------

For branch: 5.4.z
Builds between : 2024-07-03 18:08 - 2024-07-29 18:02
Jobs: 3, Runs: 12, Passed: 11, Failed: 1, Skipped: 0, Fail Ratio: 8.33%
Run on:
+--------------------------------------------------+
| JDK        | PASSED | FAILED | SKIPPED |  RATIO  |
+--------------------------------------------------+
| oracle-21  |   3    |   1    |    0    |  25.00% |
| openjdk-17 |   4    |   0    |    0    |   0.00% |
| openj9-21  |   4    |   0    |    0    |   0.00% |
+--------------------------------------------------+
Note: Passing since 2024-07-15 18:02

Builds Timeline:
2024-07-29 18:02 - PASSED (oracle-21):
    https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-OracleJDK21-nightly/14/testReport/com.hazelcast.jet.core.metrics/JobMetrics_StressTest/suspend_resume_stressTest/
2024-07-27 18:06 - PASSED (openj9-21):
    https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-Openj9-21-nightly/13/testReport/com.hazelcast.jet.core.metrics/JobMetrics_StressTest/suspend_resume_stressTest/
2024-07-24 18:08 - PASSED (openjdk-17):
    https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-ZuluJDK17-nightly/127/testReport/com.hazelcast.jet.core.metrics/JobMetrics_StressTest/suspend_resume_stressTest/
2024-07-22 18:02 - PASSED (oracle-21):
    https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-OracleJDK21-nightly/13/testReport/com.hazelcast.jet.core.metrics/JobMetrics_StressTest/suspend_resume_stressTest/
2024-07-20 18:06 - PASSED (openj9-21):
    https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-Openj9-21-nightly/12/testReport/com.hazelcast.jet.core.metrics/JobMetrics_StressTest/suspend_resume_stressTest/
2024-07-17 18:08 - PASSED (openjdk-17):
    https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-ZuluJDK17-nightly/126/testReport/com.hazelcast.jet.core.metrics/JobMetrics_StressTest/suspend_resume_stressTest/
2024-07-15 18:02 - FIXED (oracle-21):
    https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-OracleJDK21-nightly/12/testReport/com.hazelcast.jet.core.metrics/JobMetrics_StressTest/suspend_resume_stressTest/
2024-07-13 18:06 - PASSED (openj9-21):
    https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-Openj9-21-nightly/11/testReport/com.hazelcast.jet.core.metrics/JobMetrics_StressTest/suspend_resume_stressTest/
2024-07-10 18:08 - PASSED (openjdk-17):
    https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-ZuluJDK17-nightly/125/testReport/com.hazelcast.jet.core.metrics/JobMetrics_StressTest/suspend_resume_stressTest/
2024-07-08 18:02 - REGRESSION (oracle-21):
    https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-OracleJDK21-nightly/11/testReport/com.hazelcast.jet.core.metrics/JobMetrics_StressTest/suspend_resume_stressTest/
2024-07-06 18:06 - PASSED (openj9-21):
    https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-Openj9-21-nightly/10/testReport/com.hazelcast.jet.core.metrics/JobMetrics_StressTest/suspend_resume_stressTest/
2024-07-03 18:08 - PASSED (openjdk-17):
    https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-ZuluJDK17-nightly/124/testReport/com.hazelcast.jet.core.metrics/JobMetrics_StressTest/suspend_resume_stressTest/

----------------------------------------

For branch: 5.2.z
Builds between : 2024-07-06 03:10 - 2024-07-27 03:10
Jobs: 1, Runs: 4, Passed: 4, Failed: 0, Skipped: 0, Fail Ratio: 0.00%
Run on:
+------------------------------------------------+
| JDK      | PASSED | FAILED | SKIPPED |  RATIO  |
+------------------------------------------------+
| oracle-8 |   4    |   0    |    0    |   0.00% |
+------------------------------------------------+

Builds Timeline:
2024-07-27 03:10 - PASSED (oracle-8):
    https://jenkins.hazelcast.com/job/Hazelcast-5.2.z-OracleJDK8-nightly/63/testReport/com.hazelcast.jet.core.metrics/JobMetrics_StressTest/suspend_resume_stressTest/
2024-07-20 03:10 - PASSED (oracle-8):
    https://jenkins.hazelcast.com/job/Hazelcast-5.2.z-OracleJDK8-nightly/62/testReport/com.hazelcast.jet.core.metrics/JobMetrics_StressTest/suspend_resume_stressTest/
2024-07-13 03:10 - PASSED (oracle-8):
    https://jenkins.hazelcast.com/job/Hazelcast-5.2.z-OracleJDK8-nightly/61/testReport/com.hazelcast.jet.core.metrics/JobMetrics_StressTest/suspend_resume_stressTest/
2024-07-06 03:10 - PASSED (oracle-8):
    https://jenkins.hazelcast.com/job/Hazelcast-5.2.z-OracleJDK8-nightly/60/testReport/com.hazelcast.jet.core.metrics/JobMetrics_StressTest/suspend_resume_stressTest/

----------------------------------------

For branch: 5.3.z
Builds between : 2024-07-08 03:11 - 2024-07-29 03:11
Jobs: 1, Runs: 4, Passed: 4, Failed: 0, Skipped: 0, Fail Ratio: 0.00%
Run on:
+------------------------------------------------+
| JDK      | PASSED | FAILED | SKIPPED |  RATIO  |
+------------------------------------------------+
| oracle-8 |   4    |   0    |    0    |   0.00% |
+------------------------------------------------+

Builds Timeline:
2024-07-29 03:11 - PASSED (oracle-8):
    https://jenkins.hazelcast.com/job/Hazelcast-5.3.z-OracleJDK8-nightly/13/testReport/com.hazelcast.jet.core.metrics/JobMetrics_StressTest/suspend_resume_stressTest/
2024-07-22 03:11 - PASSED (oracle-8):
    https://jenkins.hazelcast.com/job/Hazelcast-5.3.z-OracleJDK8-nightly/12/testReport/com.hazelcast.jet.core.metrics/JobMetrics_StressTest/suspend_resume_stressTest/
2024-07-15 03:11 - PASSED (oracle-8):
    https://jenkins.hazelcast.com/job/Hazelcast-5.3.z-OracleJDK8-nightly/11/testReport/com.hazelcast.jet.core.metrics/JobMetrics_StressTest/suspend_resume_stressTest/
2024-07-08 03:11 - PASSED (oracle-8):
    https://jenkins.hazelcast.com/job/Hazelcast-5.3.z-OracleJDK8-nightly/10/testReport/com.hazelcast.jet.core.metrics/JobMetrics_StressTest/suspend_resume_stressTest/

----------------------------------------
```

**Comment by olukas** [comment]
Failed again on _5.5.z_ with openj9-21: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-Openj9-21-nightly/15/testReport/com.hazelcast.jet.core.metrics/JobMetrics_StressTest/suspend_resume_stressTest/

**Comment by olukas** [comment]
Failed again on _master_ with zing-17: https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK17-nightly/97/testReport/com.hazelcast.jet.core.metrics/JobMetrics_StressTest/suspend_resume_stressTest/

**Comment by AleksPeychev** [comment]
Failed again on _master_ with oracle-21: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-OracleJDK21-nightly/37/testReport/junit/com.hazelcast.jet.core.metrics/JobMetrics_StressTest/suspend_resume_stressTest/

**Comment by sumnerib** [comment]
Failed again on _master_ with OpenJDK17 (Esxi7): https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK17-nightly-Esxi7/110/testReport/com.hazelcast.jet.core.metrics/JobMetrics_StressTest/suspend_resume_stressTest/

**Comment by sumnerib** [comment]
Failed again on _master_ with zing-17: https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK17-nightly/106/testReport/com.hazelcast.jet.core.metrics/JobMetrics_StressTest/suspend_resume_stressTest/

**Comment by AleksPeychev** [comment]
Failed again on _5.5.z_ with openj9-21: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-Openj9-21-nightly/29/testReport/junit/com.hazelcast.jet.core.metrics/JobMetrics_StressTest/suspend_resume_stressTest/
