### ISSUE TITLE
Metrics collector throws NullPointerException when metrics are disabled on client

### ISSUE THREAD

**Issue by Guardian-Development** [hazelcast/hazelcast#23229]
**Describe the bug**
When using a hazelcast client, setting the following property:
```
  <metrics enabled="false">
      <jmx enabled="false"/>
  </metrics>
```
causes a null pointer exception to be thrown during any metric collection:
`java.lang.NullPointerException: Cannot invoke "com.hazelcast.internal.metrics.collectors.MetricsCollector.collectException(com.hazelcast.internal.metrics.MetricDescriptor, java.lang.Exception)" because "collector" is null
	at com.hazelcast.internal.metrics.impl.CompositeMetricsCollector.collectException(CompositeMetricsCollector.java:47) ~[streaming-server-nio-0.0.1-SNAPSHOT-0.0.1.jar:?]
	at com.hazelcast.internal.metrics.impl.MetricsCollectionCycle.collectLong(MetricsCollectionCycle.java:177) ~[streaming-server-nio-0.0.1-SNAPSHOT-0.0.1.jar:?]
	at com.hazelcast.internal.metrics.impl.MetricsCollectionCycle.collectStaticMetrics(MetricsCollectionCycle.java:82) ~[streaming-server-nio-0.0.1-SNAPSHOT-0.0.1.jar:?]
	at com.hazelcast.internal.metrics.impl.MetricsRegistryImpl.collect(MetricsRegistryImpl.java:319) ~[streaming-server-nio-0.0.1-SNAPSHOT-0.0.1.jar:?]
	at com.hazelcast.client.impl.statistics.ClientStatisticsService.collectAndSendStats(ClientStatisticsService.java:144) ~[streaming-server-nio-0.0.1-SNAPSHOT-0.0.1.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76) ~[streaming-server-nio-0.0.1-SNAPSHOT-0.0.1.jar:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) ~[streaming-server-nio-0.0.1-SNAPSHOT-0.0.1.jar:?]`

it looks like the ClientStatisticsService property -> publisherMetricsCollector is null when it is passed into the CompositeMetricsCollector constructor, which causes the issue.

**Expected behavior**
I can disable metrics on the client, and not see hazelcast exceptions during normal execution of the service. 

**To Reproduce**

1. Use version 5.2.1 of hazelcast client.
2. Disable jmx metrics with the mentioned config
3. Run the client for a period of time.

**Additional context**

I can see in ClientStatisticsService it returns early on the start method, not setting the publisherMetricsCollector if its not enabled. Possibly, there would be no attempt to collect any metrics if no metrics are enabled, or the collect and send stats method should return early also, if its not enabled. For context, we disable all client metrics due to the performance implications on our GC, as we run Java in a low-latency environment with real-time deadlines.

**Comment by neilstevenson** [comment]
@Guardian-Development 's analysis is correct. https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/client/impl/statistics/ClientStatisticsService.java is flawed

`publisherMetricsCollector` is set only if Metrics are enabled

However, (public) method `collectAndSendStatsNow()` invokes (private) method `collectAndSendStats()` which makes use of `publisherMetricsCollector`

If
https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/client/impl/statistics/ClientStatisticsService.java
invokes
https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/client/impl/clientside/HazelcastClientInstanceImpl.java#L894
which invokes
https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/client/impl/clientside/HazelcastClientInstanceImpl.java#L894
whch invokes
https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/client/impl/statistics/ClientStatisticsService.java#L109
then an NPE will occur if metrics are not enabled.

**Comment by mdumandag** [comment]
Seems like it is introduced after https://github.com/hazelcast/hazelcast/pull/21807. I will send a fix for it
