### ISSUE TITLE
NPE in BinaryMapEntryCostEstimator.calculateEntryCost

### ISSUE THREAD

**Issue by vladykin** [hazelcast/hazelcast#23237]
**Describe the bug**
Occasionally seeing the following NPE in Hazelcast member log:
```
2022-12-20 05:56:30,871 SEVERE [com.haz.map.imp.ope.EntryOperation] (hz.flamboyant_lehmann.partition-operation.thread-6) [10.21.82.163]:5701 [dev] [5.2.0] null: java.lang.NullPointerException
	at com.hazelcast.map.impl.BinaryMapEntryCostEstimator.calculateEntryCost(BinaryMapEntryCostEstimator.java:77)
	at com.hazelcast.map.impl.BinaryMapEntryCostEstimator.calculateEntryCost(BinaryMapEntryCostEstimator.java:29)
	at com.hazelcast.map.impl.recordstore.StorageImpl.removeRecord(StorageImpl.java:135)
	at com.hazelcast.map.impl.recordstore.StorageImpl.removeRecord(StorageImpl.java:45)
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.removeRecord0(DefaultRecordStore.java:1237)
	at com.hazelcast.map.impl.operation.steps.DeleteOpSteps$3.runStep(DeleteOpSteps.java:82)
	at com.hazelcast.map.impl.operation.steps.DeleteOpSteps$3.runStep(DeleteOpSteps.java:77)
	at com.hazelcast.map.impl.operation.steps.EntryOpSteps$10.runStep(EntryOpSteps.java:270)
	at com.hazelcast.map.impl.operation.steps.EntryOpSteps$10.runStep(EntryOpSteps.java:267)
	at com.hazelcast.map.impl.operation.steps.engine.StepSupplier.runStepWithState(StepSupplier.java:152)
	at com.hazelcast.map.impl.operation.steps.engine.StepSupplier.access$100(StepSupplier.java:40)
	at com.hazelcast.map.impl.operation.steps.engine.StepSupplier$2.run(StepSupplier.java:117)
	at com.hazelcast.map.impl.operation.steps.engine.StepRunner.runDirect(StepRunner.java:196)
	at com.hazelcast.map.impl.operation.steps.engine.StepRunner.run0(StepRunner.java:153)
	at com.hazelcast.map.impl.operation.steps.engine.StepRunner.run(StepRunner.java:118)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:198)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:207)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:141)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
```

**Expected behavior**
Expect Hazelcast to work without NPEs.

**To Reproduce**
This seems to correlate with deleting entries from IMap, backed by a MapStore, implemented on top of relational DB.
Deletion is initiated by means of an EntryProcessor, which does `entry.setValue(null)`, or using `IMap.removeAsync`.

**Additional context**

Hazelcast is embedded in a Quarkus application. Quarkus version 2.12.3.Final. Java 11.

Application is running in kubernetes. App image is built on top of azul/zulu-openjdk-centos:11.0.12.

Hazelcast cluster is small, just 1-2 members.

**Comment by ahmetmircik** [comment]
reproducer: https://gist.github.com/ahmetmircik/4df3c3a57353412363c1b8336ce9fee8

I have created a reproducer and able to reproduce this issue with 5.2.0 then i re-run my reproducer with 5.2.2-SNAPSHOT, which is current 5.2.z branch in hazelcast repo, there seems no occurrence of the issue. I will close your issue based on this finding since we did many fixes for offload case after 5.2.0. If you still see issue even with 5.2.2-SNAPSHOT, please re-open it.

**Comment by Settis** [comment]
The issue appears on 5.2.2 too:
```
Caused by: java.lang.NullPointerException
	at com.hazelcast.map.impl.BinaryMapEntryCostEstimator.calculateEntryCost(BinaryMapEntryCostEstimator.java:77)
	at com.hazelcast.map.impl.BinaryMapEntryCostEstimator.calculateEntryCost(BinaryMapEntryCostEstimator.java:29)
	at com.hazelcast.map.impl.recordstore.StorageImpl.removeRecord(StorageImpl.java:135)
	at com.hazelcast.map.impl.recordstore.StorageImpl.removeRecord(StorageImpl.java:45)
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.removeRecord0(DefaultRecordStore.java:1240)
	at com.hazelcast.map.impl.operation.steps.DeleteOpSteps$3.runStep(DeleteOpSteps.java:82)
	at com.hazelcast.map.impl.operation.steps.DeleteOpSteps$3.runStep(DeleteOpSteps.java:77)
	at com.hazelcast.map.impl.operation.steps.EntryOpSteps$10.runStep(EntryOpSteps.java:301)
	at com.hazelcast.map.impl.operation.steps.EntryOpSteps$10.runStep(EntryOpSteps.java:298)
	at com.hazelcast.map.impl.operation.steps.engine.StepSupplier.runStepWithState(StepSupplier.java:148)
	at com.hazelcast.map.impl.operation.steps.engine.StepSupplier.access$100(StepSupplier.java:39)
	at com.hazelcast.map.impl.operation.steps.engine.StepSupplier$2.run(StepSupplier.java:116)
	at com.hazelcast.map.impl.operation.steps.engine.StepRunner.runDirect(StepRunner.java:220)
	at com.hazelcast.map.impl.operation.steps.engine.StepRunner.run(StepRunner.java:174)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:198)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:207)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:141)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123)
	... 1 more

2023-03-31 10:26:40,782 SEVERE [com.haz.map.imp.ope.EntryOperation] (hz.naughty_galois.partition-operation.thread-3) [10.21.79.197]:5701 [cloud-native-compiler] [5.2.2] null: java.lang.NullPointerException
```

**Comment by Settis** [comment]
Unfortunatelly no, but I'll try to find something.

**Comment by vladykin** [comment]
@ahmetmircik, I have a hypothesis.

According to the stacktrace, the NPE happens in BinaryMapEntryCostEstimator.calculateEntryCost, line 77:
```java
        totalMapEntryCost += value.getCost();
```

null value can only get here from DeleteOpSteps:
```java
    ON_DELETE() {
        @Override
        public void runStep(State state) {
            DefaultRecordStore recordStore = (DefaultRecordStore) state.getRecordStore();
            Record record = recordStore.getRecord(state.getKey()); // "record" can be null here
            recordStore.removeRecord0(state.getKey(), record, false); // "record" is the value passed to BinaryMapEntryCostEstimator down the call stack
            recordStore.onStore(record);
        }
```

Not sure if anything prevents `recordStore.getRecord(state.getKey())` from returning null.
E.g. the record existed in memory at the first step of the delete operation, but was evicted somewhere in the middle - before the ON_DELETE step accessed it again.

Other invocations of `recordStore.getRecord()` in the codebase tend to check the result for null.
Notably, the ON_DELETE step of the very similar RemoveOpSteps:
```java

    ON_DELETE() {
        @Override
        public void runStep(State state) {
            DefaultRecordStore recordStore = (DefaultRecordStore) state.getRecordStore();
            Record record = recordStore.getRecord(state.getKey());
            if (record == null) {
                return;
            }
            recordStore.removeRecord0(state.getKey(), record, false);
            recordStore.onStore(record);
        }
```

So, can it be just the missing null check of `result`?
