### ISSUE TITLE
com.hazelcast.map.impl.mapstore.MapStoreForceOffloadAllOperationTest.metrics_show_offloaded_operation_count_when_forced_offload_enabled

### ISSUE THREAD

**Issue by Patras3** [hazelcast/hazelcast#23265]
_master_ (commit 243a1d829096f523291fcc04cd8b94292034ca20)

Failed on Windows - MicrosoftJDK17: https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK17/43/testReport/junit/com.hazelcast.map.impl.mapstore/MapStoreForceOffloadAllOperationTest/metrics_show_offloaded_operation_count_when_forced_offload_enabled/
<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at com.hazelcast.map.impl.mapstore.MapStoreForceOffloadAllOperationTest.lambda$metrics_show_offloaded_operation_count_when_forced_offload_enabled$0(MapStoreForceOffloadAllOperationTest.java:86)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1273)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1375)
	at com.hazelcast.map.impl.mapstore.MapStoreForceOffloadAllOperationTest.metrics_show_offloaded_operation_count_when_forced_offload_enabled(MapStoreForceOffloadAllOperationTest.java:81)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)

```
</details>

<details><summary>Standard output:</summary>

```
20:05:46,017  INFO |metrics_show_offloaded_operation_count_when_forced_offload_enabled| - [MetricsConfigHelper] Thread-55502 - [LOCAL] [dev] [5.3.0-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
20:05:46,018  INFO |metrics_show_offloaded_operation_count_when_forced_offload_enabled| - [logo] Thread-55502 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
20:05:46,018  INFO |metrics_show_offloaded_operation_count_when_forced_offload_enabled| - [system] Thread-55502 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Copyright (c) 2008-2022, Hazelcast, Inc. All Rights Reserved.
20:05:46,018  INFO |metrics_show_offloaded_operation_count_when_forced_offload_enabled| - [system] Thread-55502 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Hazelcast Platform 5.3.0-SNAPSHOT (20221224 - 243a1d8) starting at [127.0.0.1]:5701
20:05:46,018  INFO |metrics_show_offloaded_operation_count_when_forced_offload_enabled| - [system] Thread-55502 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Cluster name: dev
20:05:46,018  INFO |metrics_show_offloaded_operation_count_when_forced_offload_enabled| - [system] Thread-55502 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed. For more information, see the documentation for Integrity Checker.
20:05:46,018  INFO |metrics_show_offloaded_operation_count_when_forced_offload_enabled| - [system] Thread-55502 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Jet is enabled
20:05:46,022  INFO |metrics_show_offloaded_operation_count_when_forced_offload_enabled| - [MetricsConfigHelper] Thread-55502 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
20:05:46,025  WARN |metrics_show_offloaded_operation_count_when_forced_offload_enabled| - [CPSubsystem] Thread-55502 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
20:05:46,026  INFO |metrics_show_offloaded_operation_count_when_forced_offload_enabled| - [MapServiceContextImpl] Thread-55502 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Force offload is enabled for all maps. This means all map operations will run as if they have map-store configured. The intended usage for this flag is testing purposes.
20:05:46,028  INFO |metrics_show_offloaded_operation_count_when_forced_offload_enabled| - [JetServiceBackend] Thread-55502 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Setting number of cooperative threads and default parallelism to 2
20:05:46,029  INFO |metrics_show_offloaded_operation_count_when_forced_offload_enabled| - [Diagnostics] Thread-55502 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
20:05:46,029  INFO |metrics_show_offloaded_operation_count_when_forced_offload_enabled| - [LifecycleService] Thread-55502 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] [127.0.0.1]:5701 is STARTING
20:05:46,029  INFO |metrics_show_offloaded_operation_count_when_forced_offload_enabled| - [ClusterService] Thread-55502 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] 

Members {size:1, ver:1} [
	Member [127.0.0.1]:5701 - 51171eb8-1adf-4d1d-97a4-6115f0181c84 this
]

20:05:46,029  INFO |metrics_show_offloaded_operation_count_when_forced_offload_enabled| - [JobCoordinationService] Thread-55502 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Jet started scanning for jobs
20:05:46,029  INFO |metrics_show_offloaded_operation_count_when_forced_offload_enabled| - [LifecycleService] Thread-55502 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] [127.0.0.1]:5701 is STARTED
20:05:46,030 DEBUG |metrics_show_offloaded_operation_count_when_forced_offload_enabled| - [JobCoordinationService] hz.MapStoreForceOffloadAllOperationTest_jolly_joliot.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
20:05:46,030  INFO |metrics_show_offloaded_operation_count_when_forced_offload_enabled| - [PartitionStateManager] metrics_show_offloaded_operation_count_when_forced_offload_enabled - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Initializing cluster partition table arrangement...
20:05:46,135 DEBUG |metrics_show_offloaded_operation_count_when_forced_offload_enabled| - [JobRepository] hz.MapStoreForceOffloadAllOperationTest_jolly_joliot.cached.thread-18 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Job cleanup took 0ms
20:05:51,136 DEBUG |metrics_show_offloaded_operation_count_when_forced_offload_enabled| - [JobRepository] hz.MapStoreForceOffloadAllOperationTest_jolly_joliot.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Job cleanup took 0ms
20:05:56,137 DEBUG |metrics_show_offloaded_operation_count_when_forced_offload_enabled| - [JobRepository] hz.MapStoreForceOffloadAllOperationTest_jolly_joliot.cached.thread-15 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Job cleanup took 0ms
20:06:01,138 DEBUG |metrics_show_offloaded_operation_count_when_forced_offload_enabled| - [JobRepository] hz.MapStoreForceOffloadAllOperationTest_jolly_joliot.cached.thread-15 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Job cleanup took 0ms
20:06:06,047  INFO |metrics_show_offloaded_operation_count_when_forced_offload_enabled| - [HealthMonitor] hz.MapStoreForceOffloadAllOperationTest_jolly_joliot.HealthMonitor - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] processors=4, physical.memory.total=16.0G, physical.memory.free=407.9M, swap.space.total=28.5G, swap.space.free=9.0G, heap.memory.used=4.2G, heap.memory.free=1.8G, heap.memory.total=6.0G, heap.memory.max=6.0G, heap.memory.used/total=70.13%, heap.memory.used/max=70.13%, minor.gc.count=244, minor.gc.time=13209ms, major.gc.count=6, major.gc.time=2541ms, load.process=1.77%, load.system=0.15%, load.systemAverage=n/a thread.count=251, thread.peakCount=1497, cluster.timeDiff=0, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=10000, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=1, clientEndpoint.count=0, connection.active.count=0, client.connection.count=0, connection.count=0
20:06:06,139 DEBUG |metrics_show_offloaded_operation_count_when_forced_offload_enabled| - [JobRepository] hz.MapStoreForceOffloadAllOperationTest_jolly_joliot.cached.thread-15 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Job cleanup took 0ms
20:06:11,140 DEBUG |metrics_show_offloaded_operation_count_when_forced_offload_enabled| - [JobRepository] hz.MapStoreForceOffloadAllOperationTest_jolly_joliot.cached.thread-16 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Job cleanup took 0ms
20:06:16,141 DEBUG |metrics_show_offloaded_operation_count_when_forced_offload_enabled| - [JobRepository] hz.MapStoreForceOffloadAllOperationTest_jolly_joliot.cached.thread-9 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Job cleanup took 0ms
20:06:21,142 DEBUG |metrics_show_offloaded_operation_count_when_forced_offload_enabled| - [JobRepository] hz.MapStoreForceOffloadAllOperationTest_jolly_joliot.cached.thread-16 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Job cleanup took 0ms
20:06:26,054  INFO |metrics_show_offloaded_operation_count_when_forced_offload_enabled| - [HealthMonitor] hz.MapStoreForceOffloadAllOperationTest_jolly_joliot.HealthMonitor - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] processors=4, physical.memory.total=16.0G, physical.memory.free=407.9M, swap.space.total=28.5G, swap.space.free=9.0G, heap.memory.used=4.2G, heap.memory.free=1.8G, heap.memory.total=6.0G, heap.memory.max=6.0G, heap.memory.used/total=70.40%, heap.memory.used/max=70.40%, minor.gc.count=244, minor.gc.time=13209ms, major.gc.count=6, major.gc.time=2541ms, load.process=1.32%, load.system=1.36%, load.systemAverage=n/a thread.count=251, thread.peakCount=1497, cluster.timeDiff=0, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=10000, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=1, clientEndpoint.count=0, connection.active.count=0, client.connection.count=0, connection.count=0
20:06:26,143 DEBUG |metrics_show_offloaded_operation_count_when_forced_offload_enabled| - [JobRepository] hz.MapStoreForceOffloadAllOperationTest_jolly_joliot.cached.thread-12 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Job cleanup took 0ms
20:06:31,145 DEBUG |metrics_show_offloaded_operation_count_when_forced_offload_enabled| - [JobRepository] hz.MapStoreForceOffloadAllOperationTest_jolly_joliot.cached.thread-15 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Job cleanup took 0ms
20:06:36,146 DEBUG |metrics_show_offloaded_operation_count_when_forced_offload_enabled| - [JobRepository] hz.MapStoreForceOffloadAllOperationTest_jolly_joliot.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Job cleanup took 0ms
20:06:41,148 DEBUG |metrics_show_offloaded_operation_count_when_forced_offload_enabled| - [JobRepository] hz.MapStoreForceOffloadAllOperationTest_jolly_joliot.cached.thread-9 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Job cleanup took 0ms
20:06:46,061  INFO |metrics_show_offloaded_operation_count_when_forced_offload_enabled| - [HealthMonitor] hz.MapStoreForceOffloadAllOperationTest_jolly_joliot.HealthMonitor - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] processors=4, physical.memory.total=16.0G, physical.memory.free=409.5M, swap.space.total=28.5G, swap.space.free=9.0G, heap.memory.used=4.2G, heap.memory.free=1.8G, heap.memory.total=6.0G, heap.memory.max=6.0G, heap.memory.used/total=70.70%, heap.memory.used/max=70.70%, minor.gc.count=244, minor.gc.time=13209ms, major.gc.count=6, major.gc.time=2541ms, load.process=0.62%, load.system=0.00%, load.systemAverage=n/a thread.count=251, thread.peakCount=1497, cluster.timeDiff=0, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=10000, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=1, clientEndpoint.count=0, connection.active.count=0, client.connection.count=0, connection.count=0
20:06:46,149 DEBUG |metrics_show_offloaded_operation_count_when_forced_offload_enabled| - [JobRepository] hz.MapStoreForceOffloadAllOperationTest_jolly_joliot.cached.thread-9 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Job cleanup took 0ms
20:06:51,150 DEBUG |metrics_show_offloaded_operation_count_when_forced_offload_enabled| - [JobRepository] hz.MapStoreForceOffloadAllOperationTest_jolly_joliot.cached.thread-9 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Job cleanup took 0ms
20:06:56,152 DEBUG |metrics_show_offloaded_operation_count_when_forced_offload_enabled| - [JobRepository] hz.MapStoreForceOffloadAllOperationTest_jolly_joliot.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Job cleanup took 0ms
20:07:01,154 DEBUG |metrics_show_offloaded_operation_count_when_forced_offload_enabled| - [JobRepository] hz.MapStoreForceOffloadAllOperationTest_jolly_joliot.cached.thread-6 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Job cleanup took 0ms
20:07:06,068  INFO |metrics_show_offloaded_operation_count_when_forced_offload_enabled| - [HealthMonitor] hz.MapStoreForceOffloadAllOperationTest_jolly_joliot.HealthMonitor - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] processors=4, physical.memory.total=16.0G, physical.memory.free=409.6M, swap.space.total=28.5G, swap.space.free=9.0G, heap.memory.used=4.3G, heap.memory.free=1.7G, heap.memory.total=6.0G, heap.memory.max=6.0G, heap.memory.used/total=70.98%, heap.memory.used/max=70.98%, minor.gc.count=244, minor.gc.time=13209ms, major.gc.count=6, major.gc.time=2541ms, load.process=0.63%, load.system=0.93%, load.systemAverage=n/a thread.count=243, thread.peakCount=1497, cluster.timeDiff=0, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=10000, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=1, clientEndpoint.count=0, connection.active.count=0, client.connection.count=0, connection.count=0
20:07:06,155 DEBUG |metrics_show_offloaded_operation_count_when_forced_offload_enabled| - [JobRepository] hz.MapStoreForceOffloadAllOperationTest_jolly_joliot.cached.thread-9 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Job cleanup took 0ms
20:07:11,157 DEBUG |metrics_show_offloaded_operation_count_when_forced_offload_enabled| - [JobRepository] hz.MapStoreForceOffloadAllOperationTest_jolly_joliot.cached.thread-9 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Job cleanup took 0ms
20:07:16,158 DEBUG |metrics_show_offloaded_operation_count_when_forced_offload_enabled| - [JobRepository] hz.MapStoreForceOffloadAllOperationTest_jolly_joliot.cached.thread-9 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Job cleanup took 0ms
20:07:21,160 DEBUG |metrics_show_offloaded_operation_count_when_forced_offload_enabled| - [JobRepository] hz.MapStoreForceOffloadAllOperationTest_jolly_joliot.cached.thread-6 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Job cleanup took 0ms
20:07:26,074  INFO |metrics_show_offloaded_operation_count_when_forced_offload_enabled| - [HealthMonitor] hz.MapStoreForceOffloadAllOperationTest_jolly_joliot.HealthMonitor - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] processors=4, physical.memory.total=16.0G, physical.memory.free=409.6M, swap.space.total=28.5G, swap.space.free=9.0G, heap.memory.used=4.3G, heap.memory.free=1.7G, heap.memory.total=6.0G, heap.memory.max=6.0G, heap.memory.used/total=71.26%, heap.memory.used/max=71.26%, minor.gc.count=244, minor.gc.time=13209ms, major.gc.count=6, major.gc.time=2541ms, load.process=0.63%, load.system=0.46%, load.systemAverage=n/a thread.count=243, thread.peakCount=1497, cluster.timeDiff=0, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=10000, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=1, clientEndpoint.count=0, connection.active.count=0, client.connection.count=0, connection.count=0
20:07:26,162 DEBUG |metrics_show_offloaded_operation_count_when_forced_offload_enabled| - [JobRepository] hz.MapStoreForceOffloadAllOperationTest_jolly_joliot.cached.thread-12 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Job cleanup took 0ms
20:07:31,163 DEBUG |metrics_show_offloaded_operation_count_when_forced_offload_enabled| - [JobRepository] hz.MapStoreForceOffloadAllOperationTest_jolly_joliot.cached.thread-1 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Job cleanup took 0ms
20:07:36,164 DEBUG |metrics_show_offloaded_operation_count_when_forced_offload_enabled| - [JobRepository] hz.MapStoreForceOffloadAllOperationTest_jolly_joliot.cached.thread-9 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Job cleanup took 0ms
20:07:41,165 DEBUG |metrics_show_offloaded_operation_count_when_forced_offload_enabled| - [JobRepository] hz.MapStoreForceOffloadAllOperationTest_jolly_joliot.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Job cleanup took 0ms
20:07:46,084  INFO |metrics_show_offloaded_operation_count_when_forced_offload_enabled| - [HealthMonitor] hz.MapStoreForceOffloadAllOperationTest_jolly_joliot.HealthMonitor - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] processors=4, physical.memory.total=16.0G, physical.memory.free=409.8M, swap.space.total=28.5G, swap.space.free=9.0G, heap.memory.used=4.3G, heap.memory.free=1.7G, heap.memory.total=6.0G, heap.memory.max=6.0G, heap.memory.used/total=71.58%, heap.memory.used/max=71.58%, minor.gc.count=244, minor.gc.time=13209ms, major.gc.count=6, major.gc.time=2541ms, load.process=1.20%, load.system=0.40%, load.systemAverage=n/a thread.count=244, thread.peakCount=1497, cluster.timeDiff=0, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=10000, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=1, clientEndpoint.count=0, connection.active.count=0, client.connection.count=0, connection.count=0
20:07:46,166 DEBUG |metrics_show_offloaded_operation_count_when_forced_offload_enabled| - [JobRepository] hz.MapStoreForceOffloadAllOperationTest_jolly_joliot.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Job cleanup took 0ms
20:07:47,410  INFO |metrics_show_offloaded_operation_count_when_forced_offload_enabled| - [LifecycleService] Thread-55502 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
20:07:47,410  WARN |metrics_show_offloaded_operation_count_when_forced_offload_enabled| - [Node] Thread-55502 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Terminating forcefully...
20:07:47,410  INFO |metrics_show_offloaded_operation_count_when_forced_offload_enabled| - [Node] Thread-55502 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Shutting down connection manager...
20:07:47,410  INFO |metrics_show_offloaded_operation_count_when_forced_offload_enabled| - [Node] Thread-55502 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Shutting down node engine...
20:07:47,413  INFO |metrics_show_offloaded_operation_count_when_forced_offload_enabled| - [NodeExtension] Thread-55502 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Destroying node NodeExtension.
20:07:47,413  INFO |metrics_show_offloaded_operation_count_when_forced_offload_enabled| - [Node] Thread-55502 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Hazelcast Shutdown is completed in 3 ms.
20:07:47,413  INFO |metrics_show_offloaded_operation_count_when_forced_offload_enabled| - [LifecycleService] Thread-55502 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
BuildInfo right after metrics_show_offloaded_operation_count_when_forced_offload_enabled(com.hazelcast.map.impl.mapstore.MapStoreForceOffloadAllOperationTest): BuildInfo{version='5.3.0-SNAPSHOT', build='20221224', buildNumber=20221224, revision=243a1d8, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'metrics_show_offloaded_operation_count_when_forced_offload_enabled(com.hazelcast.map.impl.mapstore.MapStoreForceOffloadAllOperationTest):'
20:05:45, accumulated pauses: 4879 ms, max pause: 13 ms, pauses over 1000 ms: 0
20:05:50, accumulated pauses: 4876 ms, max pause: 10 ms, pauses over 1000 ms: 0
20:05:55, accumulated pauses: 4881 ms, max pause: 10 ms, pauses over 1000 ms: 0
20:06:00, accumulated pauses: 4882 ms, max pause: 10 ms, pauses over 1000 ms: 0
20:06:05, accumulated pauses: 4871 ms, max pause: 10 ms, pauses over 1000 ms: 0
20:06:10, accumulated pauses: 4883 ms, max pause: 10 ms, pauses over 1000 ms: 0
20:06:15, accumulated pauses: 4880 ms, max pause: 10 ms, pauses over 1000 ms: 0
20:06:20, accumulated pauses: 4874 ms, max pause: 10 ms, pauses over 1000 ms: 0
20:06:25, accumulated pauses: 4873 ms, max pause: 10 ms, pauses over 1000 ms: 0
20:06:30, accumulated pauses: 4884 ms, max pause: 10 ms, pauses over 1000 ms: 0
20:06:35, accumulated pauses: 4870 ms, max pause: 10 ms, pauses over 1000 ms: 0
20:06:40, accumulated pauses: 4882 ms, max pause: 10 ms, pauses over 1000 ms: 0
20:06:45, accumulated pauses: 4877 ms, max pause: 10 ms, pauses over 1000 ms: 0
20:06:50, accumulated pauses: 4875 ms, max pause: 10 ms, pauses over 1000 ms: 0
20:06:55, accumulated pauses: 4882 ms, max pause: 10 ms, pauses over 1000 ms: 0
20:07:00, accumulated pauses: 4877 ms, max pause: 10 ms, pauses over 1000 ms: 0
20:07:05, accumulated pauses: 4874 ms, max pause: 10 ms, pauses over 1000 ms: 0
20:07:10, accumulated pauses: 4877 ms, max pause: 10 ms, pauses over 1000 ms: 0
20:07:15, accumulated pauses: 4887 ms, max pause: 10 ms, pauses over 1000 ms: 0
20:07:20, accumulated pauses: 4870 ms, max pause: 10 ms, pauses over 1000 ms: 0
20:07:25, accumulated pauses: 4876 ms, max pause: 10 ms, pauses over 1000 ms: 0
20:07:30, accumulated pauses: 4881 ms, max pause: 10 ms, pauses over 1000 ms: 0
20:07:35, accumulated pauses: 4880 ms, max pause: 10 ms, pauses over 1000 ms: 0
20:07:40, accumulated pauses: 4876 ms, max pause: 10 ms, pauses over 1000 ms: 0
20:07:45, accumulated pauses: 2366 ms, max pause: 1092 ms, pauses over 1000 ms: 1



```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-Windows-MicrosoftJDK17/43/

**Comment by Patras3** [comment]
Failed again on _master_ with Windows - MicrosoftJDK17: https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK17/49/testReport/com.hazelcast.map.impl.mapstore.offload/MapStoreForceOffloadAllOperationTest/metrics_show_offloaded_operation_count_when_forced_offload_enabled/

**Comment by mdumandag** [comment]
Failed on a PR builder against master https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/17991/Hazelcast-pr-builder-17991.zip

https://github.com/hazelcast/hazelcast/pull/24271#issuecomment-1516042254

**Comment by kwart** [comment]
Another PR builder failure on `master`: https://jenkins.hazelcast.com/job/Hazelcast-pr-builder/18004/testReport/

**Comment by ahmetmircik** [comment]
closed in favor of https://github.com/hazelcast/hazelcast/issues/24335
