### ISSUE TITLE
com.hazelcast.map.IndexStatsChangingNumberOfMembersTest.testIndexStatsOperationChangingNumberOfMembers[format:OBJECT]

### ISSUE THREAD

**Issue by Patras3** [hazelcast/hazelcast#23266]
_master_ (commit 243a1d829096f523291fcc04cd8b94292034ca20)

Failed on openjdk-8: https://jenkins.hazelcast.com/job/Hazelcast-master-ZuluJDK8/219/testReport/junit/com.hazelcast.map/IndexStatsChangingNumberOfMembersTest/testIndexStatsOperationChangingNumberOfMembers_format_OBJECT_/
<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: MemberPartitions={size=3, partitions=[0, 3, 4]}, IndexImpl{partitionTracker=GlobalIndexPartitionTracker{partitionCount=11, state=State{stamp=10, indexedPartitions={size=2, partitions=[3, 4]}, pending=0}}} AbstractIndex{config=IndexConfig{name=this, type=HASH, attributes=[this], bTreeIndexConfig=BTreeIndexConfig{pageSize=16 KILOBYTES, memoryTierConfig=MemoryTierConfig{capacity=256 MEGABYTES}}}}, notIndexed= expected:<[0, 3, 4]> but was:<[3, 4]>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:120)
	at com.hazelcast.map.IndexStatsChangingNumberOfMembersTest.lambda$awaitStable$0(IndexStatsChangingNumberOfMembersTest.java:455)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1273)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1375)
	at com.hazelcast.map.IndexStatsChangingNumberOfMembersTest.awaitStable(IndexStatsChangingNumberOfMembersTest.java:441)
	at com.hazelcast.map.IndexStatsChangingNumberOfMembersTest.testIndexStatsOperationChangingNumberOfMembers(IndexStatsChangingNumberOfMembersTest.java:310)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:750)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-ZuluJDK8/219/

**Comment by ahmetmircik** [comment]
re-opened previous issue and closed this one not to lose history: https://github.com/hazelcast/hazelcast/issues/17460
