### ISSUE TITLE
com.hazelcast.instance.impl.HazelcastInstanceFactoryTest

### ISSUE THREAD

**Issue by Patras3** [hazelcast/hazelcast#23286]
_master_ (commit 4df237fa5ba17f2b1db5ec0a55b9eb5dc8a007c4)

Failed on oracle-11: https://jenkins.hazelcast.com/job/Hazelcast-master-sonar/1441/testReport/junit/com.hazelcast.instance.impl/HazelcastInstanceFactoryTest/___/
<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: Timeout waiting for thread HikariPool-2 connection adder to terminate
	at org.junit.Assert.fail(Assert.java:89)
	at com.hazelcast.test.HazelcastTestSupport.assertJoinable(HazelcastTestSupport.java:983)
	at classloading.ThreadLeakTestUtils.assertHazelcastThreadShutdown(ThreadLeakTestUtils.java:75)
	at classloading.ThreadLeakTestUtils.assertHazelcastThreadShutdown(ThreadLeakTestUtils.java:65)
	at com.hazelcast.instance.impl.HazelcastInstanceFactoryTest.cleanUp(HazelcastInstanceFactoryTest.java:70)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunAfters.invokeMethod(RunAfters.java:46)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:41)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:107)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:83)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)

```
</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: mobyNameGeneratedIfSystemPropertyEnabled in 39.721 seconds.
01:13:30,630 ERROR || - [ThreadLeakTestUtils] main - There are still Hazelcast threads running after shutdown!
-> HikariPool-2 connection adder (id: 974328) (group: main) (daemon: true) (alive: true) (interrupted: false) (state: TIMED_WAITING)
[java.base@11.0.17/java.lang.Thread.sleep(Native Method), app//com.zaxxer.hikari.util.UtilityElf.quietlySleep(UtilityElf.java:54), app//com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:738), app//com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712), java.base@11.0.17/java.util.concurrent.FutureTask.run(FutureTask.java:264), java.base@11.0.17/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128), java.base@11.0.17/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628), java.base@11.0.17/java.lang.Thread.run(Thread.java:834)]

01:18:30,635 ERROR || - [ThreadLeakTestUtils] main - There are threads which survived assertJoinable()!
-> HikariPool-2 connection adder (id: 974328) (group: main) (daemon: true) (alive: true) (interrupted: false) (state: TIMED_WAITING)
[java.base@11.0.17/java.lang.Thread.sleep(Native Method), app//com.zaxxer.hikari.util.UtilityElf.quietlySleep(UtilityElf.java:54), app//com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:738), app//com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712), java.base@11.0.17/java.util.concurrent.FutureTask.run(FutureTask.java:264), java.base@11.0.17/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128), java.base@11.0.17/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628), java.base@11.0.17/java.lang.Thread.run(Thread.java:834)]


```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-sonar/1441/

**Comment by olukas** [comment]
Failed again on _5.2.z_ with oracle-11: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-sonar/397/testReport/com.hazelcast.instance.impl/HazelcastInstanceFactoryTest/com_hazelcast_instance_impl_HazelcastInstanceFactoryTest/

**Comment by frant-hartm** [comment]
We have reworked the bits using the HikariPool quite substantially, please reopen if we see it again.

**Comment by Patras3** [comment]
Reopening as issue occurred again on: _5.2.z_ (commit 769926d4ea3c850f7b9543efcf4bb4d633b5d624)
with oracle-8: https://jenkins.hazelcast.com/job/Hazelcast-5.2.z-OracleJDK8-nightly/3/testReport/junit/com.hazelcast.instance.impl/HazelcastInstanceFactoryTest/com_hazelcast_instance_impl_HazelcastInstanceFactoryTest/
<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: Timeout waiting for thread HikariPool-2 connection adder to terminate
	at org.junit.Assert.fail(Assert.java:89)
	at com.hazelcast.test.HazelcastTestSupport.assertJoinable(HazelcastTestSupport.java:957)
	at classloading.ThreadLeakTestUtils.assertHazelcastThreadShutdown(ThreadLeakTestUtils.java:75)
	at classloading.ThreadLeakTestUtils.assertHazelcastThreadShutdown(ThreadLeakTestUtils.java:65)
	at com.hazelcast.instance.impl.HazelcastInstanceFactoryTest.cleanUp(HazelcastInstanceFactoryTest.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunAfters.invokeMethod(RunAfters.java:46)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:40)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:107)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:83)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)

```
</details>


<details><summary>Standard output:</summary>

```
Finished Running Test: fixedNameGeneratedIfPropertyDisabled in 39.363 seconds.
05:30:12,201 ERROR || - [ThreadLeakTestUtils] main - There are still Hazelcast threads running after shutdown!
-> HikariPool-2 connection closer (id: 287815) (group: main) (daemon: true) (alive: true) (interrupted: false) (state: TIMED_WAITING)
[sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078), java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467), java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1073), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624), java.lang.Thread.run(Thread.java:750)]

-> HikariPool-2 connection adder (id: 287812) (group: main) (daemon: true) (alive: true) (interrupted: false) (state: TIMED_WAITING)
[java.lang.Thread.sleep(Native Method), com.zaxxer.hikari.util.UtilityElf.quietlySleep(UtilityElf.java:54), com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:738), com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712), java.util.concurrent.FutureTask.run(FutureTask.java:266), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624), java.lang.Thread.run(Thread.java:750)]

05:35:12,205 ERROR || - [ThreadLeakTestUtils] main - There are threads which survived assertJoinable()!
-> HikariPool-2 connection adder (id: 287812) (group: main) (daemon: true) (alive: true) (interrupted: false) (state: TIMED_WAITING)
[java.lang.Thread.sleep(Native Method), com.zaxxer.hikari.util.UtilityElf.quietlySleep(UtilityElf.java:54), com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:738), com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712), java.util.concurrent.FutureTask.run(FutureTask.java:266), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624), java.lang.Thread.run(Thread.java:750)]


```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-5.2.z-OracleJDK8-nightly/3/

**Comment by sumnerib** [comment]
Failed again on _5.2.z_ with oracle-8: https://jenkins.hazelcast.com/job/Hazelcast-5.2.z-OracleJDK8-nightly/17/testReport/junit/com.hazelcast.instance.impl/HazelcastInstanceFactoryTest/com_hazelcast_instance_impl_HazelcastInstanceFactoryTest/

**Comment by olukas** [comment]
Closing the test failure - it doesn't seem to be related to `master` or the latest maintenance stream `5.5.z` and it hasn't fail in the last 3 months. Feel free to reopen test failure if it occurs on `master` or on the latest maintenance stream.
