### ISSUE TITLE
com.hazelcast.map.merge.MapInternalStateSplitBrainTest.testSplitBrain

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#23299]
_master_ (commit 4df237fa5ba17f2b1db5ec0a55b9eb5dc8a007c4)

Failed on oracle-8 and `force-offload`: https://jenkins.hazelcast.com/job/Hazelcast-master-force-offload/25/testReport/com.hazelcast.map.merge/MapInternalStateSplitBrainTest/testSplitBrain_format_OBJECT_/

Failed in variant `[format:OBJECT]`.

<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: 

mapName=mapNameA,  pId:3 size:921 uuid:6966ba08-8c1a-440c-8fdd-404db36d4658
 pId:4 size:945 uuid:6966ba08-8c1a-440c-8fdd-404db36d4658
 pId:6 size:846 uuid:6966ba08-8c1a-440c-8fdd-404db36d4658
 pId:7 size:939 uuid:6966ba08-8c1a-440c-8fdd-404db36d4658
 pId:8 size:951 uuid:6966ba08-8c1a-440c-8fdd-404db36d4658
 pId:9 size:916 uuid:6966ba08-8c1a-440c-8fdd-404db36d4658

mapName=mapNameB,  pId:3 size:921 uuid:6966ba08-8c1a-440c-8fdd-404db36d4658
 pId:4 size:945 uuid:6966ba08-8c1a-440c-8fdd-404db36d4658
 pId:6 size:846 uuid:6966ba08-8c1a-440c-8fdd-404db36d4658
 pId:7 size:939 uuid:6966ba08-8c1a-440c-8fdd-404db36d4658
 pId:8 size:951 uuid:6966ba08-8c1a-440c-8fdd-404db36d4658
 pId:9 size:916 uuid:6966ba08-8c1a-440c-8fdd-404db36d4658

mapName=mapNameA,  pId:6 size:846 uuid:6b4eadb5-24f2-4d1e-9a62-aecb159a94ca
 pId:7 size:939 uuid:6b4eadb5-24f2-4d1e-9a62-aecb159a94ca
 pId:8 size:951 uuid:6b4eadb5-24f2-4d1e-9a62-aecb159a94ca
 pId:10 size:860 uuid:6b4eadb5-24f2-4d1e-9a62-aecb159a94ca

mapName=mapNameB,  pId:6 size:846 uuid:6b4eadb5-24f2-4d1e-9a62-aecb159a94ca
 pId:7 size:939 uuid:6b4eadb5-24f2-4d1e-9a62-aecb159a94ca
 pId:8 size:951 uuid:6b4eadb5-24f2-4d1e-9a62-aecb159a94ca
 pId:10 size:860 uuid:6b4eadb5-24f2-4d1e-9a62-aecb159a94ca

mapName=mapNameA,  pId:2 size:892 uuid:c84ccff5-3980-41ce-8e6b-29dec76d295a
 pId:5 size:889 uuid:c84ccff5-3980-41ce-8e6b-29dec76d295a
 pId:9 size:916 uuid:c84ccff5-3980-41ce-8e6b-29dec76d295a
 pId:10 size:860 uuid:c84ccff5-3980-41ce-8e6b-29dec76d295a

mapName=mapNameB,  pId:2 size:892 uuid:c84ccff5-3980-41ce-8e6b-29dec76d295a
 pId:5 size:889 uuid:c84ccff5-3980-41ce-8e6b-29dec76d295a
 pId:9 size:916 uuid:c84ccff5-3980-41ce-8e6b-29dec76d295a
 pId:10 size:860 uuid:c84ccff5-3980-41ce-8e6b-29dec76d295a

mapName=mapNameA,  pId:0 size:909 uuid:d39f540a-d820-4950-8bf0-e99ec17d4631
 pId:1 size:932 uuid:d39f540a-d820-4950-8bf0-e99ec17d4631
 pId:3 size:921 uuid:d39f540a-d820-4950-8bf0-e99ec17d4631
 pId:5 size:889 uuid:d39f540a-d820-4950-8bf0-e99ec17d4631

mapName=mapNameB,  pId:0 size:909 uuid:d39f540a-d820-4950-8bf0-e99ec17d4631
 pId:1 size:932 uuid:d39f540a-d820-4950-8bf0-e99ec17d4631
 pId:3 size:921 uuid:d39f540a-d820-4950-8bf0-e99ec17d4631
 pId:5 size:889 uuid:d39f540a-d820-4950-8bf0-e99ec17d4631

mapName=mapNameA,  pId:0 size:909 uuid:9f16b23a-41b2-4d6e-96e7-c65088d3e80f
 pId:1 size:932 uuid:9f16b23a-41b2-4d6e-96e7-c65088d3e80f
 pId:2 size:892 uuid:9f16b23a-41b2-4d6e-96e7-c65088d3e80f
 pId:4 size:945 uuid:9f16b23a-41b2-4d6e-96e7-c65088d3e80f

mapName=mapNameB,  pId:0 size:909 uuid:9f16b23a-41b2-4d6e-96e7-c65088d3e80f
 pId:1 size:932 uuid:9f16b23a-41b2-4d6e-96e7-c65088d3e80f
 pId:2 size:892 uuid:9f16b23a-41b2-4d6e-96e7-c65088d3e80f
 pId:4 size:945 uuid:9f16b23a-41b2-4d6e-96e7-c65088d3e80f


c84ccff5-3980-41ce-8e6b-29dec76d295a --> [5, 10], [PartitionStamp{stamp=20, partitions=[5, 10]}, PartitionStamp{stamp=20, partitions=[5, 10]}]
d39f540a-d820-4950-8bf0-e99ec17d4631 --> [0, 3], [PartitionStamp{stamp=12, partitions=[0, 3]}, PartitionStamp{stamp=12, partitions=[0, 3]}]
9f16b23a-41b2-4d6e-96e7-c65088d3e80f --> [1, 2], [null, PartitionStamp{stamp=10, partitions=[1, 2]}]
6966ba08-8c1a-440c-8fdd-404db36d4658 --> [4, 6, 9], [PartitionStamp{stamp=26, partitions=[4, 6, 9]}, PartitionStamp{stamp=26, partitions=[4, 6, 9]}]
6b4eadb5-24f2-4d1e-9a62-aecb159a94ca --> [7, 8], [PartitionStamp{stamp=26, partitions=[7, 8]}, PartitionStamp{stamp=26, partitions=[7, 8]}]

	at com.hazelcast.map.merge.MapInternalStateSplitBrainTest.onAfterSplitBrainHealed(MapInternalStateSplitBrainTest.java:142)
	at com.hazelcast.test.SplitBrainTestSupport.doIteration(SplitBrainTestSupport.java:207)
	at com.hazelcast.test.SplitBrainTestSupport.testSplitBrain(SplitBrainTestSupport.java:195)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.AssertionError: ownedPartitionsAfterHeal={c84ccff5-3980-41ce-8e6b-29dec76d295a=[5, 10], d39f540a-d820-4950-8bf0-e99ec17d4631=[0, 3], 9f16b23a-41b2-4d6e-96e7-c65088d3e80f=[1, 2], 6966ba08-8c1a-440c-8fdd-404db36d4658=[4, 6, 9], 6b4eadb5-24f2-4d1e-9a62-aecb159a94ca=[7, 8]}, [4, 6, 9][7, 8][5, 10][0, 3]null, but expected [6, 9][7, 8][1, 5][0, 2, 4][3, 10] expected:<9> but was:<11>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at com.hazelcast.map.merge.MapInternalStateSplitBrainTest.lambda$onAfterSplitBrainHealed$0(MapInternalStateSplitBrainTest.java:135)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1273)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1375)
	at com.hazelcast.map.merge.MapInternalStateSplitBrainTest.onAfterSplitBrainHealed(MapInternalStateSplitBrainTest.java:127)
	... 14 more

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-force-offload/25/

**Comment by olukas** [comment]
Closing the test failure - it doesn't seem to be related to `master` or the latest maintenance stream `5.5.z` and it hasn't fail in the last 3 months. Feel free to reopen test failure if it occurs on `master` or on the latest maintenance stream.
