### ISSUE TITLE
com.hazelcast.cluster.Address cannot be created for unknown hostname [HZ-1943]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#23311]
**Description**
Constructor `public Address(String host, int port)` of `com.hazelcast.cluster.Address` uses `InetAddress.getByName(host)` which throws `java.net.UnknownHostException` if unknown hostname is used.

**Where it causes troubles**
It can cause troubles for example for deserialization of `com.hazelcast.cp.internal.CPMemberInfo` (but I guess there can also be other classes with similar problem). 

Let's consider following scenario - users want to get list of all `CPMember` of given `CPGroup`. They can use following `Callable` which is sent by unisocket client and executed on server side:
```
    @Override
    public Collection<CPMember> call() throws Exception {
        CompletionStage<CPGroup> cpGroup = hazelcastInstance.getCPSubsystem().getCPSubsystemManagementService().getCPGroup(cpGroupName);
        CPGroup get = cpGroup.toCompletableFuture().get();
        return get.members();
    }
```
In case when members are using internal hostnames which are not known for the client then deserialization of `Collection<CPMember>` will fail on client side with `java.net.UnknownHostException` since the hostname is unknown. However there's no reason why client needs to know given hostnames which are used for forming a cluster. 

**Thrown Exception**
```
java.net.UnknownHostException: hz0
	at java.net.InetAddress.getAllByName0(InetAddress.java:1281)
	at java.net.InetAddress.getAllByName(InetAddress.java:1193)
	at java.net.InetAddress.getAllByName(InetAddress.java:1127)
	at java.net.InetAddress.getByName(InetAddress.java:1077)
	at com.hazelcast.cluster.Address.<init>(Address.java:55)
	at com.hazelcast.cp.internal.CPMemberInfo.readObject(CPMemberInfo.java:89)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1185)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2319)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2210)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1690)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:508)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:466)
	at java.util.HashSet.readObject(HashSet.java:341)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1185)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2319)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2210)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1690)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2428)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2352)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2210)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1690)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:508)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:466)
	at com.hazelcast.internal.serialization.impl.defaultserializers.JavaDefaultSerializers$JavaSerializer.read(JavaDefaultSerializers.java:92)
	at com.hazelcast.internal.serialization.impl.defaultserializers.JavaDefaultSerializers$JavaSerializer.read(JavaDefaultSerializers.java:85)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:44)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:271)
```

**Workaround**
It works fine if given hostnames are added to `/etc/hosts` on client side but it's far from optimal solution.

**Comment by vbekiaris** [comment]
Just for the sake of completeness: in the context of client-member communication, Hazelcast clients deal properly with `Address` deserialization with a custom type factory that does not try hostname resolution.

The root cause of this issue is that the `Callable` returns `Collection<com.hazelcast.cp.internal.CPMemberInfo>` -> it is using IDS serde for `CPMemberInfo` -> address resolution is attempted during deserialization of `Callable`'s result on the client side.
