### ISSUE TITLE
INSERT INTO Kafka mapping w/ 'valueFormat'='jsonFlat' causes java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hazelcast#23393]
**Describe the bug**
HZ throws a `java.lang.ClassNotFoundException` for `com/fasterxml/jackson/annotation/JsonView` when trying to execute an `INSERT` into a Kafka mapping whose value format is `json-flat`.

<details><summary>Stacktrace</summary>

```
SEVERE: [10.0.0.29]:5701 [dev] [5.3.0-SNAPSHOT] com/fasterxml/jackson/annotation/JsonView
java.lang.NoClassDefFoundError: com/fasterxml/jackson/annotation/JsonView
	at com.hazelcast.shaded.com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector.<clinit>(JacksonAnnotationIntrospector.java:37)
	at com.hazelcast.shaded.com.fasterxml.jackson.databind.ObjectMapper.<clinit>(ObjectMapper.java:375)
	at com.hazelcast.jet.sql.impl.inject.JsonUpsertTarget.<clinit>(JsonUpsertTarget.java:38)
	at com.hazelcast.jet.sql.impl.inject.JsonUpsertTargetDescriptor.create(JsonUpsertTargetDescriptor.java:32)
	at com.hazelcast.jet.sql.impl.connector.keyvalue.KvProjector$Supplier.get(KvProjector.java:153)
	at com.hazelcast.jet.sql.impl.connector.keyvalue.KvProcessors$EntryProjectorProcessorSupplier.get(KvProcessors.java:95)
	at com.hazelcast.jet.impl.execution.init.ExecutionPlan.createProcessors(ExecutionPlan.java:503)
	at com.hazelcast.jet.impl.execution.init.ExecutionPlan.lambda$null$1(ExecutionPlan.java:215)
	at com.hazelcast.jet.impl.util.Util.doWithClassLoader(Util.java:547)
	at com.hazelcast.jet.impl.execution.init.ExecutionPlan.lambda$initialize$3(ExecutionPlan.java:213)
	at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:753)
	at java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:731)
	at java.base/java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2108)
	at com.hazelcast.jet.impl.execution.init.ExecutionPlan.initialize(ExecutionPlan.java:191)
	at com.hazelcast.jet.impl.execution.ExecutionContext.initialize(ExecutionContext.java:170)
	at com.hazelcast.jet.impl.JobExecutionService.runLightJob(JobExecutionService.java:302)
	at com.hazelcast.jet.impl.operation.InitExecutionOperation.doRun(InitExecutionOperation.java:95)
	at com.hazelcast.jet.impl.operation.AsyncOperation.run(AsyncOperation.java:55)
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:192)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:295)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:270)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:219)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:411)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:438)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:618)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:597)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:558)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:241)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:71)
	at com.hazelcast.jet.impl.LightMasterContext.invokeOnParticipant(LightMasterContext.java:263)
	at com.hazelcast.jet.impl.LightMasterContext.invokeOnParticipants(LightMasterContext.java:249)
	at com.hazelcast.jet.impl.LightMasterContext.lambda$createContext$4(LightMasterContext.java:163)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:907)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.annotation.JsonView
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 41 more
```

</details>

**Expected behavior**
Records are inserted into the Kafka topic.

**To Reproduce**

The following code snippet can be used to reproduce the issue:
```
        Config config = new Config();
        config.getJetConfig().setEnabled(true);
        HazelcastInstance hz = Hazelcast.newHazelcastInstance(config);
        hz.getSql().execute(
                "CREATE MAPPING my_topic(\n" +
                "    __key BIGINT,\n" +
                "    ticker VARCHAR,\n" +
                "    amount INT)\n" +
                "TYPE Kafka\n" +
                "OPTIONS (\n" +
                "    'keyFormat' = 'bigint',\n" +
                "    'valueFormat' = 'json-flat',\n" +
                "    'bootstrap.servers' = '127.0.0.1:9092')"
        );

        hz.getSql().execute("INSERT INTO my_topic VALUES " +
                "(1, 'v-1', 1 ), (2, 'v-2',2), (3, 'v-3', 3)");

        hz.shutdown();
```

**Additional context**

Adding the following to my project's `pom.xml` resolves the issue, however the docs don't mention this as a requirement for inserting into Kafka via SQL.

```
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
            <version>2.11.0</version>
        </dependency>
```

Version: `Hazelcast Platform 5.3.0-SNAPSHOT (20230113 - e466a66)`

**Comment by k-jamroz** [comment]
@frant-hartm should `hazelcast-jet-kafka` have this dependency?
@sumnerib is that only SQL+Kafka+`json-flat`+`INSERT` combination require this dependency? Do other uses of `json-flat` require it as well?

**Comment by k-jamroz** [comment]
Definitely worth fixing

**Comment by sumnerib** [comment]
@k-jamroz I've also experienced it using `SINK` (other parameters the same).

**Comment by k-jamroz** [comment]
Inserted/sinks into json-flat use `JsonUpsertTarget` class (belonging to hazelcast-sql module) which in turn requires `jackson-annotations`, so the problem is not Kafka specific.
