### ISSUE TITLE
com.hazelcast.jet.mongodb.MongoDBSourceTest.testStream_whenServerDown [HZ-2557]

### ISSUE THREAD

**Issue by Patras3** [hazelcast/hazelcast#23414]
_master_ (commit 696daf1ec3181f88501e50e5a09dac86e3f03227)

Failed on MacOS: https://jenkins.hazelcast.com/job/Hazelcast-master-MacOS-ZuluJDK8/155/testReport/junit/com.hazelcast.jet.mongodb/MongoDBSourceTest/testStream_whenServerDown/
<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: expected:<40000> but was:<2391>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at com.hazelcast.jet.mongodb.MongoDBSourceTest.lambda$testStream_whenServerDown$1(MongoDBSourceTest.java:89)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1273)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1375)
	at com.hazelcast.jet.mongodb.MongoDBSourceTest.testStream_whenServerDown(MongoDBSourceTest.java:88)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.testcontainers.containers.FailureDetectingExternalResource$1.evaluate(FailureDetectingExternalResource.java:29)
	at com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37)
	at com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:104)
	at com.hazelcast.test.metrics.MetricsRule$1.evaluate(MetricsRule.java:63)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at com.hazelcast.test.OverridePropertyRule$1.evaluate(OverridePropertyRule.java:66)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)

```
</details>

<details><summary>Standard output:</summary>

```
BuildInfo right after testStream_whenServerDown(com.hazelcast.jet.mongodb.MongoDBSourceTest): BuildInfo{version='5.3.0-SNAPSHOT', build='20230116', buildNumber=20230116, revision=696daf1, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'testStream_whenServerDown(com.hazelcast.jet.mongodb.MongoDBSourceTest):'
20:33:20, accumulated pauses: 847 ms, max pause: 6 ms, pauses over 1000 ms: 0
20:33:25, accumulated pauses: 747 ms, max pause: 8 ms, pauses over 1000 ms: 0
20:33:30, accumulated pauses: 574 ms, max pause: 7 ms, pauses over 1000 ms: 0
20:33:35, accumulated pauses: 681 ms, max pause: 7 ms, pauses over 1000 ms: 0
20:33:40, accumulated pauses: 712 ms, max pause: 10 ms, pauses over 1000 ms: 0
20:33:45, accumulated pauses: 666 ms, max pause: 8 ms, pauses over 1000 ms: 0
20:33:50, accumulated pauses: 636 ms, max pause: 7 ms, pauses over 1000 ms: 0
20:33:55, accumulated pauses: 579 ms, max pause: 8 ms, pauses over 1000 ms: 0
20:34:00, accumulated pauses: 826 ms, max pause: 8 ms, pauses over 1000 ms: 0
20:34:05, accumulated pauses: 792 ms, max pause: 6 ms, pauses over 1000 ms: 0
20:34:10, accumulated pauses: 872 ms, max pause: 7 ms, pauses over 1000 ms: 0
20:34:15, accumulated pauses: 863 ms, max pause: 7 ms, pauses over 1000 ms: 0
20:34:20, accumulated pauses: 924 ms, max pause: 4 ms, pauses over 1000 ms: 0
20:34:25, accumulated pauses: 891 ms, max pause: 5 ms, pauses over 1000 ms: 0
20:34:30, accumulated pauses: 1001 ms, max pause: 9 ms, pauses over 1000 ms: 0
20:34:35, accumulated pauses: 711 ms, max pause: 5 ms, pauses over 1000 ms: 0
20:34:40, accumulated pauses: 901 ms, max pause: 4 ms, pauses over 1000 ms: 0
20:34:45, accumulated pauses: 857 ms, max pause: 7 ms, pauses over 1000 ms: 0
20:34:50, accumulated pauses: 649 ms, max pause: 5 ms, pauses over 1000 ms: 0
20:34:55, accumulated pauses: 756 ms, max pause: 5 ms, pauses over 1000 ms: 0
20:35:00, accumulated pauses: 911 ms, max pause: 8 ms, pauses over 1000 ms: 0
20:35:05, accumulated pauses: 830 ms, max pause: 9 ms, pauses over 1000 ms: 0
20:35:10, accumulated pauses: 782 ms, max pause: 8 ms, pauses over 1000 ms: 0
20:35:15, accumulated pauses: 882 ms, max pause: 5 ms, pauses over 1000 ms: 0
20:35:20, accumulated pauses: 910 ms, max pause: 7 ms, pauses over 1000 ms: 0
20:35:25, accumulated pauses: 941 ms, max pause: 5 ms, pauses over 1000 ms: 0
20:35:30, accumulated pauses: 977 ms, max pause: 5 ms, pauses over 1000 ms: 0
20:35:35, accumulated pauses: 855 ms, max pause: 5 ms, pauses over 1000 ms: 0
20:35:40, accumulated pauses: 94 ms, max pause: 4 ms, pauses over 1000 ms: 0


No metrics recorded during the test

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-MacOS-ZuluJDK8/155/

**Comment by TomaszGaweda** [comment]
Test no longer exist
