### ISSUE TITLE
com.hazelcast.client.protocol.ClientMessageProtectionTest.testExceededMessageSize [API-1995]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#23467]
_5.2.z_ (commit b6cc95f09c59153b2f4d5a4fd91dbb411290183c)

Failed on redhat-8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-RedHatJDK8/68/testReport/com.hazelcast.client.protocol/ClientMessageProtectionTest/testExceededMessageSize/
<details><summary>Stacktrace:</summary>

```
java.net.SocketException: Connection reset
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:115)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:143)
	at com.hazelcast.client.impl.clientside.ClientTestUtil.writeClientMessage(ClientTestUtil.java:53)
	at com.hazelcast.client.protocol.ClientMessageProtectionTest.testExceededMessageSize(ClientMessageProtectionTest.java:153)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)

```
</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: testLimitsRemovedAfterAValidAuthentication in 0.526 seconds.
04:58:12,523  INFO |testExceededMessageSize| - [LifecycleService] Thread-43127 - [127.0.0.1]:5004 [testExceededMessageSize] [5.2.2-SNAPSHOT] [127.0.0.1]:5004 is SHUTTING_DOWN
04:58:12,523  WARN |testExceededMessageSize| - [Node] Thread-43127 - [127.0.0.1]:5004 [testExceededMessageSize] [5.2.2-SNAPSHOT] Terminating forcefully...
04:58:12,523  INFO |testExceededMessageSize| - [Node] Thread-43127 - [127.0.0.1]:5004 [testExceededMessageSize] [5.2.2-SNAPSHOT] Shutting down connection manager...
04:58:12,524  INFO |testExceededMessageSize| - [Node] Thread-43127 - [127.0.0.1]:5004 [testExceededMessageSize] [5.2.2-SNAPSHOT] Shutting down node engine...
04:58:12,532  INFO |testExceededMessageSize| - [NodeExtension] Thread-43127 - [127.0.0.1]:5004 [testExceededMessageSize] [5.2.2-SNAPSHOT] Destroying node NodeExtension.
04:58:12,532  INFO |testExceededMessageSize| - [Node] Thread-43127 - [127.0.0.1]:5004 [testExceededMessageSize] [5.2.2-SNAPSHOT] Hazelcast Shutdown is completed in 9 ms.
04:58:12,532  INFO |testExceededMessageSize| - [LifecycleService] Thread-43127 - [127.0.0.1]:5004 [testExceededMessageSize] [5.2.2-SNAPSHOT] [127.0.0.1]:5004 is SHUTDOWN

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-5.maintenance-RedHatJDK8/68/

**Comment by olukas** [comment]
Failed again on _5.2.2 release branch_ with oracle-8: https://jenkins.hazelcast.com/view/Release/job/Hazelcast-5.releaseBranch-OracleJDK8/26/testReport/com.hazelcast.client.protocol/ClientMessageProtectionTest/testExceededMessageSize/

**Comment by sumnerib** [comment]
Reopening as issue occurred again on: _5.1.z_ (commit 24d4fd466c6500c94ff7b2b506e2d86f5f187f93)
with oracle-8: https://jenkins.hazelcast.com/job/Hazelcast-5.1.z-OracleJDK8/12/testReport/junit/com.hazelcast.client.protocol/ClientMessageProtectionTest/testExceededMessageSize/

<details><summary>Stacktrace:</summary>

```
java.net.SocketException: Broken pipe (Write failed)
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:143)
	at com.hazelcast.client.protocol.ClientMessageProtectionTest.writeClientMessage(ClientMessageProtectionTest.java:244)
	at com.hazelcast.client.protocol.ClientMessageProtectionTest.testExceededMessageSize(ClientMessageProtectionTest.java:153)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:750)

```

</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: testLimitsRemovedAfterAValidAuthentication in 0.229 seconds.
22:20:55,527  INFO |testExceededMessageSize| - [LifecycleService] Thread-24003 - [127.0.0.1]:5010 [testExceededMessageSize] [5.1.8-SNAPSHOT] [127.0.0.1]:5010 is SHUTTING_DOWN
22:20:55,527  WARN |testExceededMessageSize| - [Node] Thread-24003 - [127.0.0.1]:5010 [testExceededMessageSize] [5.1.8-SNAPSHOT] Terminating forcefully...
22:20:55,527  INFO |testExceededMessageSize| - [Node] Thread-24003 - [127.0.0.1]:5010 [testExceededMessageSize] [5.1.8-SNAPSHOT] Shutting down connection manager...
22:20:55,529  INFO |testExceededMessageSize| - [Node] Thread-24003 - [127.0.0.1]:5010 [testExceededMessageSize] [5.1.8-SNAPSHOT] Shutting down node engine...
22:20:55,530  INFO |testExceededMessageSize| - [NodeExtension] Thread-24003 - [127.0.0.1]:5010 [testExceededMessageSize] [5.1.8-SNAPSHOT] Destroying node NodeExtension.
22:20:55,530  INFO |testExceededMessageSize| - [Node] Thread-24003 - [127.0.0.1]:5010 [testExceededMessageSize] [5.1.8-SNAPSHOT] Hazelcast Shutdown is completed in 3 ms.
22:20:55,530  INFO |testExceededMessageSize| - [LifecycleService] Thread-24003 - [127.0.0.1]:5010 [testExceededMessageSize] [5.1.8-SNAPSHOT] [127.0.0.1]:5010 is SHUTDOWN

```

</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-5.1.z-OracleJDK8/12/

**Comment by olukas** [comment]
Closing the test failure - it doesn't seem to be related to `master` or the latest maintenance stream `5.5.z` and it hasn't fail in the last 3 months. Feel free to reopen test failure if it occurs on `master` or on the latest maintenance stream.
