### ISSUE TITLE
com.hazelcast.sql.impl.client.SqlResubmissionTest.when_failingUpdate

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#23466]
_master_ (commit 74134e54b476ce07f4cf47c8682b43d9090e573f)

Failed on oracle-8 (force-offload): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-nightly-force-offload/30/testReport/com.hazelcast.sql.impl.client/SqlResubmissionTest/when_failingUpdate_clusterFailure_NodeShutdownClusterFailure__mode_RETRY_ALL_/

It failed in variant `[clusterFailure:NodeShutdownClusterFailure, mode:RETRY_ALL]`.

<details><summary>Stacktrace:</summary>

```
com.hazelcast.jet.JetException: Async operation completed exceptionally: java.util.concurrent.ExecutionException: com.hazelcast.core.OperationTimeoutException: MultipleEntryOperation invocation failed to complete due to operation-heartbeat-timeout. Current time: 2023-01-22 17:06:12.842. Start time: 2023-01-22 17:04:12.025. Total elapsed time: 120817 ms. Last operation heartbeat: never. Last operation heartbeat from member: 2023-01-22 17:06:11.842. Invocation{op=com.hazelcast.map.impl.operation.MultipleEntryOperation{serviceName='hz:impl:mapService', identityHash=182690655, partitionId=4, replicaIndex=0, callId=71, invocationTime=1674407052034 (2023-01-22 17:04:12.034), waitTimeout=-1, callTimeout=60000, tenantControl=com.hazelcast.spi.impl.tenantcontrol.NoopTenantControl@0, name=o_5926aebe_fb47_48d1_bc1a_4ebb510a7783}, tryCount=250, tryPauseMillis=500, invokeCount=7, callTimeoutMillis=60000, firstInvocationTimeMs=1674407052025, firstInvocationTime='2023-01-22 17:04:12.025', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 00:00:00.000', targetAddress=[127.0.0.1]:5747, targetMember=Member [127.0.0.1]:5747 - bc08f817-a9fc-4206-a0bb-53adb8fb429a this, memberListVersion=3, pendingResponse={VOID}, backupsAcksExpected=-1, backupsAcksReceived=0, connection=com.hazelcast.internal.server.FirewallingServer$FirewallingConnection@2ce5aa97}
	at com.hazelcast.jet.impl.processor.AsyncTransformUsingServiceOrderedP.tryFlushQueue(AsyncTransformUsingServiceOrderedP.java:205) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.jet.impl.processor.AsyncTransformUsingServiceOrderedP.complete(AsyncTransformUsingServiceOrderedP.java:151) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.complete(ProcessorTasklet.java:541) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:421) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:291) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:404) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:895) ~[?:1.8.0_351]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.run(TaskletExecutionService.java:369) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_351]
Caused by: java.util.concurrent.ExecutionException: com.hazelcast.core.OperationTimeoutException: MultipleEntryOperation invocation failed to complete due to operation-heartbeat-timeout. Current time: 2023-01-22 17:06:12.842. Start time: 2023-01-22 17:04:12.025. Total elapsed time: 120817 ms. Last operation heartbeat: never. Last operation heartbeat from member: 2023-01-22 17:06:11.842. Invocation{op=com.hazelcast.map.impl.operation.MultipleEntryOperation{serviceName='hz:impl:mapService', identityHash=182690655, partitionId=4, replicaIndex=0, callId=71, invocationTime=1674407052034 (2023-01-22 17:04:12.034), waitTimeout=-1, callTimeout=60000, tenantControl=com.hazelcast.spi.impl.tenantcontrol.NoopTenantControl@0, name=o_5926aebe_fb47_48d1_bc1a_4ebb510a7783}, tryCount=250, tryPauseMillis=500, invokeCount=7, callTimeoutMillis=60000, firstInvocationTimeMs=1674407052025, firstInvocationTime='2023-01-22 17:04:12.025', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 00:00:00.000', targetAddress=[127.0.0.1]:5747, targetMember=Member [127.0.0.1]:5747 - bc08f817-a9fc-4206-a0bb-53adb8fb429a this, memberListVersion=3, pendingResponse={VOID}, backupsAcksExpected=-1, backupsAcksReceived=0, connection=com.hazelcast.internal.server.FirewallingServer$FirewallingConnection@2ce5aa97}
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) ~[?:1.8.0_351]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908) ~[?:1.8.0_351]
	at com.hazelcast.jet.impl.processor.AsyncTransformUsingServiceOrderedP.tryFlushQueue(AsyncTransformUsingServiceOrderedP.java:200) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	... 8 more
Caused by: com.hazelcast.core.OperationTimeoutException: MultipleEntryOperation invocation failed to complete due to operation-heartbeat-timeout. Current time: 2023-01-22 17:06:12.842. Start time: 2023-01-22 17:04:12.025. Total elapsed time: 120817 ms. Last operation heartbeat: never. Last operation heartbeat from member: 2023-01-22 17:06:11.842. Invocation{op=com.hazelcast.map.impl.operation.MultipleEntryOperation{serviceName='hz:impl:mapService', identityHash=182690655, partitionId=4, replicaIndex=0, callId=71, invocationTime=1674407052034 (2023-01-22 17:04:12.034), waitTimeout=-1, callTimeout=60000, tenantControl=com.hazelcast.spi.impl.tenantcontrol.NoopTenantControl@0, name=o_5926aebe_fb47_48d1_bc1a_4ebb510a7783}, tryCount=250, tryPauseMillis=500, invokeCount=7, callTimeoutMillis=60000, firstInvocationTimeMs=1674407052025, firstInvocationTime='2023-01-22 17:04:12.025', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 00:00:00.000', targetAddress=[127.0.0.1]:5747, targetMember=Member [127.0.0.1]:5747 - bc08f817-a9fc-4206-a0bb-53adb8fb429a this, memberListVersion=3, pendingResponse={VOID}, backupsAcksExpected=-1, backupsAcksReceived=0, connection=com.hazelcast.internal.server.FirewallingServer$FirewallingConnection@2ce5aa97}
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.newOperationTimeoutException(InvocationFuture.java:194) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:136) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.spi.impl.AbstractInvocationFuture.unblockOtherNode(AbstractInvocationFuture.java:795) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.spi.impl.AbstractInvocationFuture.unblockAll(AbstractInvocationFuture.java:759) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.spi.impl.AbstractInvocationFuture.complete0(AbstractInvocationFuture.java:1235) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.spi.impl.AbstractInvocationFuture.complete(AbstractInvocationFuture.java:1219) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.complete(Invocation.java:690) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.detectAndHandleTimeout(Invocation.java:449) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor$MonitorInvocationsTask.run0(InvocationMonitor.java:326) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor$FixedRateMonitorTask.run(InvocationMonitor.java:282) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_351]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[?:1.8.0_351]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_351]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[?:1.8.0_351]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_351]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_351]
	... 1 more


```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-nightly-force-offload/30/

**Comment by olukas** [comment]
Failed again on _master_ with oracle-8 (force-offload): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-nightly-force-offload/35/testReport/com.hazelcast.sql.impl.client/SqlResubmissionTest/when_failingUpdate_clusterFailure_NodeShutdownClusterFailure__mode_RETRY_ALL_/

**Comment by Patras3** [comment]
Failed again on _master_ with oracle-11 (little-endian): https://jenkins.hazelcast.com/job/Hazelcast-master-nightly-little-endian/42/testReport/com.hazelcast.sql.impl.client/SqlResubmissionTest/when_failingUpdate/

**Comment by olukas** [comment]
Closing the test failure - it doesn't seem to be related to `master` or the latest maintenance stream `5.5.z` and it hasn't fail in the last 3 months. Feel free to reopen test failure if it occurs on `master` or on the latest maintenance stream.
