### ISSUE TITLE
java.util.concurrent.CancellationException when loading from GenericMapStore [HZ-1994]

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hazelcast#23489]
**Describe the bug**
Given a configured `external-data-store` and corresponding `map-store` for connecting a DB such as Postgres or MySQL, when loading the data from the external store (i.e. by calling `hz.getMap()`), some warnings for `java.util.concurrent.CancellationException` are logged. They may be unnecessary and confusing, because it implies that a query/job was canceled by the user (which is not the case).

Data is still loaded successfully in the map.

Example:
```
Jan 26, 2023 7:29:42 AM com.hazelcast.jet.impl.operation.InitExecutionOperation
WARNING: [10.0.0.29]:5701 [dev] [5.3.0-SNAPSHOT] null
java.util.concurrent.CancellationException
        at com.hazelcast.jet.sql.impl.processors.RootResultConsumerSink.tryProcess(RootResultConsumerSink.java:97)
        at com.hazelcast.jet.impl.execution.ProcessorTasklet.lambda$stateMachineStep$2(ProcessorTasklet.java:334)
        at com.hazelcast.jet.impl.util.Util.doWithClassLoader(Util.java:547)
        at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:334)
        at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:328)
        at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:291)
        at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:404)
        at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:895)
        at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.run(TaskletExecutionService.java:369)
        at java.lang.Thread.run(Thread.java:750)
```

**Expected behavior**
`java.util.concurrent.CancellationException` are not logged when successfully loading from the external store. 

**To Reproduce**

Config and code snippets of a reporoducer:

hazelcast.xml:
```
...
    <external-data-store name="postgres">
        <class-name>com.hazelcast.datastore.JdbcDataStoreFactory</class-name>
        <properties>
            <property name="jdbcUrl">jdbc:postgresql://127.0.0.1:5432/test</property>
            <property name="username">postgres</property>
            <property name="password">****</property>
        </properties>
    </external-data-store>
...
    <map name="people">
        <map-store enabled="true">
            <class-name>com.hazelcast.mapstore.GenericMapStore</class-name> 
            <properties>
                <property name="external-data-store-ref">postgres</property> 
            </properties>
        </map-store>
    </map>
...
```

HZ member code:
```
HazelcastInstance hz = Hazelcast.newHazelcastInstance();
IMap<Integer, GenericRecord> map = hz.getMap("people");
map.values().stream().forEach(v -> System.out.println(v));
System.out.println(">>>>>>>>>>> DONE");
hz.shutdown();
```

**Additional context**

The issue seems to be related to [this method](https://github.com/hazelcast/hazelcast/blob/fc2271c3a19a6a048c26613152870d4c85fa222b/extensions/mapstore/src/main/java/com/hazelcast/mapstore/GenericMapStore.java#L255) in `GenericMapStore`. The `SqlResult` is closed without consuming the iterator. Similar behavior can be triggered from a client/embedded member with:

```
try (SqlResult result = hz.getSql().execute("SELECT * FROM people")) {
    SqlRowMetadata rowMetadata = result.getRowMetadata();
    System.out.println(rowMetadata);
}
```

**Comment by sumnerib** [comment]
fixed by: https://github.com/hazelcast/hazelcast-mono/pull/661
