### ISSUE TITLE
com.hazelcast.datastore.impl.ExternalDataStoreServiceImplTest.test_connection_should_throw_when_no_db_is_present and com.hazelcast.datalink.impl.DataLinkServiceImplTest.test_connection_should_throw_when_no_db_is_present

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#23498]
_master_ (commit 65933d5f0689250b39ad958322ee6fb77baaf936)

Failed on Windows - MicrosoftJDK11: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Windows-MicrosoftJDK11/49/testReport/com.hazelcast.datastore.impl/ExternalDataStoreServiceImplTest/test_connection_should_throw_when_no_db_is_present/
<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: 

Expecting throwable message:
  <"Failed to initialize pool: Database "C:/random/path" not found, and IFEXISTS=true, so we cant auto-create it [90146-214]">
to contain:
  <"Database "/random/path" not found">
but did not.

Throwable that failed the check:

com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Database "C:/random/path" not found, and IFEXISTS=true, so we cant auto-create it [90146-214]
	at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:596)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:582)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at com.hazelcast.datastore.JdbcDataStoreFactory.doCreateDataSource(JdbcDataStoreFactory.java:81)
	at com.hazelcast.datastore.JdbcDataStoreFactory.init(JdbcDataStoreFactory.java:55)
	at com.hazelcast.datastore.impl.ExternalDataStoreServiceImpl.createFactory(ExternalDataStoreServiceImpl.java:52)
	at com.hazelcast.datastore.impl.ExternalDataStoreServiceImpl.testConnection(ExternalDataStoreServiceImpl.java:69)
	at com.hazelcast.datastore.impl.ExternalDataStoreServiceImplTest.lambda$test_connection_should_throw_when_no_db_is_present$0(ExternalDataStoreServiceImplTest.java:86)
	at org.assertj.core.api.ThrowableAssert.catchThrowable(ThrowableAssert.java:62)
	at org.assertj.core.api.AssertionsForClassTypes.catchThrowable(AssertionsForClassTypes.java:750)
	at org.assertj.core.api.Assertions.catchThrowable(Assertions.java:1179)
	at org.assertj.core.api.Assertions.assertThatThrownBy(Assertions.java:1051)
	at com.hazelcast.datastore.impl.ExternalDataStoreServiceImplTest.test_connection_should_throw_when_no_db_is_present(ExternalDataStoreServiceImplTest.java:86)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database "C:/random/path" not found, and IFEXISTS=true, so we cant auto-create it [90146-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:678)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.engine.Engine.throwNotFound(Engine.java:186)
	at org.h2.engine.Engine.openSession(Engine.java:72)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
	at org.h2.Driver.connect(Driver.java:59)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:121)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
	... 24 more

	at com.hazelcast.datastore.impl.ExternalDataStoreServiceImplTest.test_connection_should_throw_when_no_db_is_present(ExternalDataStoreServiceImplTest.java:87)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:829)

```
</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: should_return_working_datastore in 0.115 seconds.
Started Running Test: test_connection_should_throw_when_no_db_is_present
19:21:38,727  INFO |test_connection_should_throw_when_no_db_is_present| - [MetricsConfigHelper] main - [LOCAL] [dev] [5.3.0-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
19:21:38,729  INFO |test_connection_should_throw_when_no_db_is_present| - [logo] main - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
19:21:38,729  INFO |test_connection_should_throw_when_no_db_is_present| - [system] main - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Copyright (c) 2008-2023, Hazelcast, Inc. All Rights Reserved.
19:21:38,729  INFO |test_connection_should_throw_when_no_db_is_present| - [system] main - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Hazelcast Platform 5.3.0-SNAPSHOT (20230126 - 65933d5) starting at [127.0.0.1]:5701
19:21:38,729  INFO |test_connection_should_throw_when_no_db_is_present| - [system] main - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Cluster name: dev
19:21:38,729  INFO |test_connection_should_throw_when_no_db_is_present| - [system] main - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed. For more information, see the documentation for Integrity Checker.
19:21:38,729  INFO |test_connection_should_throw_when_no_db_is_present| - [system] main - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Jet is enabled
19:21:38,736  INFO |test_connection_should_throw_when_no_db_is_present| - [MetricsConfigHelper] main - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
19:21:38,744  WARN |test_connection_should_throw_when_no_db_is_present| - [CPSubsystem] main - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
19:21:38,747  INFO |test_connection_should_throw_when_no_db_is_present| - [JetServiceBackend] main - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Setting number of cooperative threads and default parallelism to 2
19:21:38,752  INFO |test_connection_should_throw_when_no_db_is_present| - [Diagnostics] main - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
19:21:38,752  INFO |test_connection_should_throw_when_no_db_is_present| - [LifecycleService] main - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] [127.0.0.1]:5701 is STARTING
19:21:38,752  INFO |test_connection_should_throw_when_no_db_is_present| - [ClusterService] main - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] 

Members {size:1, ver:1} [
	Member [127.0.0.1]:5701 - 3667a04f-d8a6-4537-b303-83ea1ebaad19 this
]

19:21:38,752  INFO |test_connection_should_throw_when_no_db_is_present| - [JobCoordinationService] main - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Jet started scanning for jobs
19:21:38,753  INFO |test_connection_should_throw_when_no_db_is_present| - [LifecycleService] main - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] [127.0.0.1]:5701 is STARTED
19:21:38,753 DEBUG |test_connection_should_throw_when_no_db_is_present| - [JobCoordinationService] hz.ExternalDataStoreServiceImplTest_vigilant_borg.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
19:21:38,764  INFO |test_connection_should_throw_when_no_db_is_present| - [HealthMonitor] hz.ExternalDataStoreServiceImplTest_vigilant_borg.HealthMonitor - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] processors=4, physical.memory.total=16.0G, physical.memory.free=521.3M, swap.space.total=28.5G, swap.space.free=10.9G, heap.memory.used=2.8G, heap.memory.free=3.2G, heap.memory.total=6.0G, heap.memory.max=6.0G, heap.memory.used/total=46.07%, heap.memory.used/max=46.07%, minor.gc.count=178, minor.gc.time=9517ms, major.gc.count=2, major.gc.time=704ms, load.process=51.28%, load.system=78.86%, load.systemAverage=n/a thread.count=72, thread.peakCount=1429, cluster.timeDiff=0, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=0, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=0, clientEndpoint.count=0, connection.active.count=0, client.connection.count=0, connection.count=0
19:21:38,854 DEBUG |test_connection_should_throw_when_no_db_is_present| - [JobCoordinationService] hz.ExternalDataStoreServiceImplTest_vigilant_borg.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
19:21:38,956 DEBUG |test_connection_should_throw_when_no_db_is_present| - [JobCoordinationService] hz.ExternalDataStoreServiceImplTest_vigilant_borg.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
19:21:39,058 DEBUG |test_connection_should_throw_when_no_db_is_present| - [JobCoordinationService] hz.ExternalDataStoreServiceImplTest_vigilant_borg.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
19:21:39,159 DEBUG |test_connection_should_throw_when_no_db_is_present| - [JobCoordinationService] hz.ExternalDataStoreServiceImplTest_vigilant_borg.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
19:21:39,260 DEBUG |test_connection_should_throw_when_no_db_is_present| - [JobCoordinationService] hz.ExternalDataStoreServiceImplTest_vigilant_borg.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
19:21:39,362 DEBUG |test_connection_should_throw_when_no_db_is_present| - [JobCoordinationService] hz.ExternalDataStoreServiceImplTest_vigilant_borg.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
19:21:39,464 DEBUG |test_connection_should_throw_when_no_db_is_present| - [JobCoordinationService] hz.ExternalDataStoreServiceImplTest_vigilant_borg.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
19:21:39,565 DEBUG |test_connection_should_throw_when_no_db_is_present| - [JobCoordinationService] hz.ExternalDataStoreServiceImplTest_vigilant_borg.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
19:21:39,667 DEBUG |test_connection_should_throw_when_no_db_is_present| - [JobCoordinationService] hz.ExternalDataStoreServiceImplTest_vigilant_borg.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
19:21:39,768 DEBUG |test_connection_should_throw_when_no_db_is_present| - [JobCoordinationService] hz.ExternalDataStoreServiceImplTest_vigilant_borg.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
19:21:41,132 DEBUG |test_connection_should_throw_when_no_db_is_present| - [JobCoordinationService] hz.ExternalDataStoreServiceImplTest_vigilant_borg.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
19:21:41,135  INFO |test_connection_should_throw_when_no_db_is_present| - [LifecycleService] main - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
19:21:41,135 DEBUG |test_connection_should_throw_when_no_db_is_present| - [JobCoordinationService] main - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Added a shutting-down member: 3667a04f-d8a6-4537-b303-83ea1ebaad19
19:21:41,136  INFO |test_connection_should_throw_when_no_db_is_present| - [Node] main - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Shutting down connection manager...
19:21:41,136  INFO |test_connection_should_throw_when_no_db_is_present| - [Node] main - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Shutting down node engine...
19:21:41,151  INFO |test_connection_should_throw_when_no_db_is_present| - [NodeExtension] main - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Destroying node NodeExtension.
19:21:41,151  INFO |test_connection_should_throw_when_no_db_is_present| - [Node] main - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Hazelcast Shutdown is completed in 16 ms.
19:21:41,151  INFO |test_connection_should_throw_when_no_db_is_present| - [LifecycleService] main - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
BuildInfo right after test_connection_should_throw_when_no_db_is_present(com.hazelcast.datastore.impl.ExternalDataStoreServiceImplTest): BuildInfo{version='5.3.0-SNAPSHOT', build='20230126', buildNumber=20230126, revision=65933d5, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'test_connection_should_throw_when_no_db_is_present(com.hazelcast.datastore.impl.ExternalDataStoreServiceImplTest):'
19:21:35, accumulated pauses: 4791 ms, max pause: 1317 ms, pauses over 1000 ms: 1
19:21:40, accumulated pauses: 7 ms, max pause: 7 ms, pauses over 1000 ms: 0



```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-Windows-MicrosoftJDK11/49/

**Comment by sumnerib** [comment]
Failed again on _master_ with Windows - MicrosoftJDK17: https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK17/48/testReport/junit/com.hazelcast.datastore.impl/ExternalDataStoreServiceImplTest/test_connection_should_throw_when_no_db_is_present/

**Comment by Patras3** [comment]
Failed again on _master_ with Windows - MicrosoftJDK17: https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK17/49/testReport/com.hazelcast.datastore.impl/ExternalDataStoreServiceImplTest/test_connection_should_throw_when_no_db_is_present/

**Comment by olukas** [comment]
Failed again on _master_ with Windows - MicrosoftJDK17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Windows-MicrosoftJDK17/50/testReport/com.hazelcast.datalink.impl/DataLinkServiceImplTest/test_connection_should_throw_when_no_db_is_present/

**Comment by sumnerib** [comment]
Failed again on _master_ with Windows - OracleJDK8: https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-OracleJDK8/435/testReport/junit/com.hazelcast.datalink.impl/DataLinkServiceImplTest/test_connection_should_throw_when_no_db_is_present/

**Comment by olukas** [comment]
Failed again on _master_ with Windows - MicrosoftJDK17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Windows-MicrosoftJDK17/52/testReport/com.hazelcast.datalink.impl/DataLinkServiceImplTest/test_connection_should_throw_when_no_db_is_present/
