### ISSUE TITLE
com.hazelcast.internal.json.JsonValue_Test.writeTo_doesNotCloseWriter [HZ-2411]

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hazelcast#23519]
_master_ (commit 26fee11245a7d88ae5aada0ee84f30505e34e7e4)

Failed on zing-17: https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK17/10/testReport/junit/com.hazelcast.internal.json/JsonValue_Test/writeTo_doesNotCloseWriter/
<details><summary>Stacktrace:</summary>

```
java.lang.NullPointerException: Cannot invoke "java.lang.StringBuffer.append(char[], int, int)" because "this.buf" is null
	at java.base/java.io.StringWriter.write(StringWriter.java:99)
	at com.hazelcast.internal.json.WritingBuffer.flush(WritingBuffer.java:88)
	at com.hazelcast.internal.json.JsonValue.writeTo(JsonValue.java:299)
	at com.hazelcast.internal.json.JsonValue.writeTo(JsonValue.java:274)
	at com.hazelcast.internal.json.JsonValue_Test.writeTo_doesNotCloseWriter(JsonValue_Test.java:91)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:107)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:83)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-ZingJDK17/10/

**Comment by Patras3** [comment]
Failed again on _master_ with openj9-11: https://jenkins.hazelcast.com/job/Hazelcast-master-Openj9-11/116/testReport/junit/com.hazelcast.internal.json/JsonValue_Test/writeTo_doesNotCloseWriter/

**Comment by olukas** [comment]
Failed again on _master_ with ibm-8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-IbmJDK8/222/testReport/com.hazelcast.internal.json/JsonValue_Test/writeTo_doesNotCloseWriter/

**Comment by sumnerib** [comment]
Failed again on _master_ with ibm-8: https://jenkins.hazelcast.com/job/Hazelcast-master-IbmJDK8-fips/63/testReport/junit/com.hazelcast.internal.json/JsonValue_Test/writeTo_doesNotCloseWriter/

New stacktrace:
```
java.lang.NullPointerException
	at java.io.StringWriter.write(StringWriter.java:105)
	at com.hazelcast.internal.json.WritingBuffer.flush(WritingBuffer.java:88)
	at com.hazelcast.internal.json.JsonValue.writeTo(JsonValue.java:299)
	at com.hazelcast.internal.json.JsonValue.writeTo(JsonValue.java:274)
	at com.hazelcast.internal.json.JsonValue_Test.writeTo_doesNotCloseWriter(JsonValue_Test.java:91)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
```

**Comment by Patras3** [comment]
Failed again on _master_ with openj9-11: https://jenkins.hazelcast.com/job/Hazelcast-master-Openj9-11/119/testReport/com.hazelcast.internal.json/JsonValue_Test/writeTo_doesNotCloseWriter/

**Comment by olukas** [comment]
Failed again on _master_ with ibm-8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-IbmJDK8-fips/65/testReport/com.hazelcast.internal.json/JsonValue_Test/writeTo_doesNotCloseWriter/

**Comment by sumnerib** [comment]
Failed again on _master_ with openj9-17: https://jenkins.hazelcast.com/job/Hazelcast-master-Openj9-17/57/testReport/junit/com.hazelcast.internal.json/JsonValue_Test/writeTo_doesNotCloseWriter/

**Comment by olukas** [comment]
Failed again on _master_ with ibm-8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-IbmJDK8-fips/72/testReport/com.hazelcast.internal.json/JsonValue_Test/writeTo_doesNotCloseWriter/

**Comment by olukas** [comment]
Failed again on _master_ with ibm-8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-IbmJDK8-fips/82/testReport/com.hazelcast.internal.json/JsonValue_Test/writeTo_doesNotCloseWriter/

**Comment by olukas** [comment]
Failed again on _master_ with openj9-17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Openj9-17/63/testReport/com.hazelcast.internal.json/JsonValue_Test/writeTo_doesNotCloseWriter/

<details><summary>However stacktrace is different:</summary>

```
java.lang.NullPointerException: Cannot read field "buf" because "this" is null
	at java.base/java.io.StringWriter.write(StringWriter.java:99)
	at com.hazelcast.internal.json.WritingBuffer.flush(WritingBuffer.java:88)
	at com.hazelcast.internal.json.JsonValue.writeTo(JsonValue.java:299)
	at com.hazelcast.internal.json.JsonValue.writeTo(JsonValue.java:274)
	at com.hazelcast.internal.json.JsonValue_Test.writeTo_doesNotCloseWriter(JsonValue_Test.java:91)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:49)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:120)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:95)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:69)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:146)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
```
</details>

**Comment by olukas** [comment]
Failed again on _master_ with ibm-8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-IbmJDK8-fips/84/testReport/com.hazelcast.internal.json/JsonValue_Test/writeTo_doesNotCloseWriter/

**Comment by olukas** [comment]
Failed again on _master_ with ibm-8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-IbmJDK8-fips/86/testReport/com.hazelcast.internal.json/JsonValue_Test/writeTo_doesNotCloseWriter/
