### ISSUE TITLE
Many tests failed in JUnit 'Before' on ZingJDK [HZ-2552] [HZG-223]

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hazelcast#23517]
_master_ (commit 26fee11245a7d88ae5aada0ee84f30505e34e7e4)

Failed on zing-8: https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK8/481/

<details><summary>Example Stacktrace from `OperationExecutorImpl_RunTest`:</summary>

```
java.lang.NullPointerException
	at com.hazelcast.instance.impl.Node.getLogger(Node.java:736)
	at com.hazelcast.instance.impl.DefaultNodeExtension.<init>(DefaultNodeExtension.java:159)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl_AbstractTest.setup(OperationExecutorImpl_AbstractTest.java:84)
	at sun.reflect.GeneratedMethodAccessor2040.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:365)
	at com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37)
	at com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:104)
	at com.hazelcast.test.metrics.MetricsRule$1.evaluate(MetricsRule.java:63)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:50)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:29)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:41)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:107)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:83)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)

```
</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: test_whenPartitionOperation_andCallingFromIOThread in 0.014 seconds.
Started Running Test: test_whenGenericOperation_andCallingFromPartitionThread
BuildInfo right after test_whenGenericOperation_andCallingFromPartitionThread(com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl_RunTest): BuildInfo{version='5.3.0-SNAPSHOT', build='20230130', buildNumber=20230130, revision=26fee11, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'test_whenGenericOperation_andCallingFromPartitionThread(com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl_RunTest):'
03:34:50, accumulated pauses: 4833 ms, max pause: 16 ms, pauses over 1000 ms: 0


No metrics recorded during the test

```
</details>

Another example from `TcpServerContextTest.testGetOutboundPorts_acceptsSemicolonAsASeparator`
<details><summary>Stacktrace:</summary>

```
java.lang.NullPointerException
	at com.hazelcast.internal.server.tcp.TcpServerContext.initRestApiConfig(TcpServerContext.java:81)
	at com.hazelcast.internal.server.tcp.TcpServerContext.<init>(TcpServerContext.java:76)
	at com.hazelcast.internal.server.tcp.TcpServerContextTest.setUp(TcpServerContextTest.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:365)
	at com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37)
	at com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:104)
	at com.hazelcast.test.metrics.MetricsRule$1.evaluate(MetricsRule.java:63)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at com.hazelcast.test.HazelcastParallelClassRunner.access$301(HazelcastParallelClassRunner.java:49)
	at com.hazelcast.test.HazelcastParallelClassRunner$TestRunner.run(HazelcastParallelClassRunner.java:162)
	at java.lang.Thread.run(Thread.java:807)

```
</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: testGetOutboundPorts_acceptsSpaceAsASeparator in 0.010 seconds.
BuildInfo right after testGetOutboundPorts_acceptsSemicolonAsASeparator(com.hazelcast.internal.server.tcp.TcpServerContextTest): BuildInfo{version='5.3.0-SNAPSHOT', build='20230130', buildNumber=20230130, revision=26fee11, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'testGetOutboundPorts_acceptsSemicolonAsASeparator(com.hazelcast.internal.server.tcp.TcpServerContextTest):'
02:07:50, accumulated pauses: 4397 ms, max pause: 15 ms, pauses over 1000 ms: 0


No metrics recorded during the test

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-ZingJDK8/481/

**Comment by sumnerib** [comment]
Failed again on master with zing-17 : https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK17/10/

**Comment by JamesHazelcast** [comment]
The stacktraces provided show the code encountering `NullPointerException`s when referencing objects which are `final` and instantiated with class creation (they should essentially be guaranteed non-null); these failures have also only occurred on Zing JVMs, which use their own proprietary Garbage Collector and has been known to cause some anomalous failures in the past. This particular test also encountered large GC usage during its operation (4400-4800ms per 5s), further supporting an out of the ordinary circumstance.

Given this information, combined with the fact this failure occurred just over a week after our Mockito upgrade on January 19th (which caused a variety of failures, all related to Mockito instability issues), and hasn't occurred since - I am going to close this failure as an anomaly.

**Comment by JackPGreen** [comment]
Re-occured on [Hazelcast-master-ZingJDK21](https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK21/10/):
```
java.lang.NullPointerException: Cannot invoke "com.hazelcast.config.Config.getAdvancedNetworkConfig()" because "config" is null
	at com.hazelcast.internal.server.tcp.TcpServerContext.initRestApiConfig(TcpServerContext.java:81)
	at com.hazelcast.internal.server.tcp.TcpServerContext.<init>(TcpServerContext.java:76)
	at com.hazelcast.internal.server.tcp.TcpServerContextTest.setUp(TcpServerContextTest.java:57)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:365)
	at com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37)
	at com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:104)
	at com.hazelcast.test.metrics.MetricsRule$1.evaluate(MetricsRule.java:63)
	at com.hazelcast.test.HazelcastParallelClassRunner.access$101(HazelcastParallelClassRunner.java:52)
	at com.hazelcast.test.HazelcastParallelClassRunner$TestRunner.run(HazelcastParallelClassRunner.java:168)
	at java.base/java.lang.Thread.run(Thread.java:1584)
```
```
java.lang.NullPointerException: Cannot invoke "com.hazelcast.logging.impl.LoggingServiceImpl.getLogger(java.lang.Class)" because "this.loggingService" is null
	at com.hazelcast.instance.impl.Node.getLogger(Node.java:770)
	at com.hazelcast.internal.cluster.impl.ClusterStateManager.<init>(ClusterStateManager.java:87)
	at com.hazelcast.internal.cluster.impl.ClusterStateManagerTest.setup(ClusterStateManagerTest.java:101)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:365)
	at com.hazelcast.test.HazelcastParallelClassRunner.access$101(HazelcastParallelClassRunner.java:52)
	at com.hazelcast.test.HazelcastParallelClassRunner$TestRunner.run(HazelcastParallelClassRunner.java:168)
	at java.base/java.lang.Thread.run(Thread.java:1584)
```

**Comment by AleksPeychev** [comment]
Failed again on _master_ with zing-17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZingJDK17/46/testReport/junit/com.hazelcast.internal.cluster.impl/ClusterStateManagerTest/test_defaultState/
 - https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZingJDK17/46/testReport/junit/com.hazelcast.internal.cluster.impl/ClusterStateManagerTest/test_initialClusterState_rejected/
 - https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZingJDK17/46/testReport/junit/com.hazelcast.internal.cluster.impl/ClusterStateManagerTest/test_changeLocalClusterState_success/
 - https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZingJDK17/46/testReport/junit/com.hazelcast.internal.cluster.impl/ClusterStateManagerTest/test_unlockClusterState_success/
 - https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZingJDK17/46/testReport/junit/com.hazelcast.internal.cluster.impl/ClusterStateManagerTest/test_lockClusterState_forPassiveState_whenHasOnGoingMigration/
 - https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZingJDK17/46/testReport/junit/com.hazelcast.internal.cluster.impl/ClusterStateManagerTest/test_lockClusterState_success/
 - https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZingJDK17/46/testReport/junit/com.hazelcast.internal.cluster.impl/ClusterStateManagerTest/test_lockClusterState_nullInitiator/
 - https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZingJDK17/46/testReport/junit/com.hazelcast.internal.cluster.impl/ClusterStateManagerTest/test_unlockClusterState_fail_whenLockedByElse/
 - https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZingJDK17/46/testReport/junit/com.hazelcast.internal.cluster.impl/ClusterStateManagerTest/changeLocalClusterState_shouldRemoveMembersDeadWhileFrozen_whenStateBecomes_ACTIVE/
 - https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZingJDK17/46/testReport/junit/com.hazelcast.internal.cluster.impl/ClusterStateManagerTest/test_lockClusterState_nullTransactionId/

**Comment by AleksPeychev** [comment]
Failed again on _master_ with zing-21: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZingJDK21/12/testReport/junit/com.hazelcast.internal.cluster.impl/ClusterStateManagerTest/

**Comment by olukas** [comment]
Failed again on _master_ with ZingJDK21: 
- https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZingJDK21/13/testReport/com.hazelcast.internal.cluster.impl/ClusterStateManagerTest/
- https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZingJDK21/lastCompletedBuild/testReport/com.hazelcast.internal.server.tcp/TcpServerContextTest/
- https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZingJDK21/13/testReport/com.hazelcast.spi.impl.operationexecutor.impl/

**Comment by Patras3** [comment]
Failed again on master with zing-17:
https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK17/51/testReport/

**Comment by sumnerib** [comment]
Failed again on _master_ with zing-17: https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK17/54/testReport/

**Comment by AleksPeychev** [comment]
Failed again on _master_ with zing-21: https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK21/25/testReport/

_master_ (commit 99b6aac3d3ee0aea38c27fabe44927f64ec2a023)

Failed on zing-21: 
 - https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK21/25/testReport/junit/com.hazelcast.query.impl.predicates/CompositeIndexVisitorTest/testUnoptimizablePredicates/
 
 - https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK21/25/testReport/junit/com.hazelcast.query.impl.predicates/CompositeIndexVisitorTest/testOptimizablePredicates/
 
<details><summary>Stacktrace:</summary>

```
java.lang.NullPointerException: Cannot read the array length because "compositeIndexes" is null
	at com.hazelcast.query.impl.predicates.CompositeIndexVisitor.visit(CompositeIndexVisitor.java:51)
	at com.hazelcast.query.impl.predicates.VisitorTestSupport.check(VisitorTestSupport.java:79)
	at com.hazelcast.query.impl.predicates.CompositeIndexVisitorTest.testOptimizablePredicates(CompositeIndexVisitorTest.java:108)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.lang.Thread.run(Thread.java:1584)

```
</details>


<details><summary>Standard output:</summary>

```
Started Running Test: testOptimizablePredicates
Started Running Test: testUnoptimizablePredicates

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-ZingJDK21/25/

--------------------------------------------------------------------------------------------------

_master_ (commit 99b6aac3d3ee0aea38c27fabe44927f64ec2a023)

Failed on zing-21: 
 - https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK21/25/testReport/junit/com.hazelcast.query.impl.predicates/EvaluateVisitorTest/testOptimizablePredicates/
 - https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK21/25/testReport/junit/com.hazelcast.query.impl.predicates/EvaluateVisitorTest/testUnoptimizablePredicates/
<details><summary>Stacktrace:</summary>

```
java.lang.NullPointerException: Cannot invoke "com.hazelcast.query.impl.AttributeIndexRegistry.match(String, com.hazelcast.query.impl.QueryContext$IndexMatchHint)" because "this.evaluateOnlyAttributeIndexRegistry" is null
	at com.hazelcast.query.impl.IndexRegistry.matchIndex(IndexRegistry.java:539)
	at com.hazelcast.query.impl.predicates.EvaluateVisitor.visit(EvaluateVisitor.java:216)
	at com.hazelcast.query.impl.predicates.EqualPredicate.accept(EqualPredicate.java:62)
	at com.hazelcast.query.impl.predicates.EvaluateVisitorTest.optimize(EvaluateVisitorTest.java:375)
	at com.hazelcast.query.impl.predicates.EvaluateVisitorTest.assertNoOptimization(EvaluateVisitorTest.java:198)
	at com.hazelcast.query.impl.predicates.EvaluateVisitorTest.testUnoptimizablePredicates(EvaluateVisitorTest.java:139)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.lang.Thread.run(Thread.java:1584)

```
</details>


<details><summary>Standard output:</summary>

```
Started Running Test: testOptimizablePredicates
Started Running Test: testUnoptimizablePredicates

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-ZingJDK21/25/

------------------------------------------------------------------------------------------------

_master_ (commit 99b6aac3d3ee0aea38c27fabe44927f64ec2a023)

Failed on zing-21: https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK21/25/testReport/junit/com.hazelcast.query.impl.predicates/RangeVisitorTest/
<details><summary>Stacktrace:</summary>

```
java.lang.NullPointerException: Cannot invoke "com.hazelcast.query.impl.ConverterCache.get(String)" because "this.converterCache" is null
	at com.hazelcast.query.impl.IndexRegistry.getConverter(IndexRegistry.java:567)
	at com.hazelcast.query.impl.predicates.RangeVisitor.visit(RangeVisitor.java:64)
	at com.hazelcast.query.impl.predicates.RangeVisitorTest.testBetweenPredicateOptimization(RangeVisitorTest.java:144)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.lang.Thread.run(Thread.java:1584)

```
</details>


<details><summary>Standard output:</summary>

```
Started Running Test: testBetweenPredicateOptimization
Started Running Test: testUnsatisfiablePredicates
Started Running Test: testUnoptimizablePredicates
Started Running Test: testOptimizablePredicates
Started Running Test: testNullsHandling
Started Running Test: testDuplicatesHandling

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-ZingJDK21/25/

**Comment by Patras3** [comment]
Failed again: https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK17/65/testReport/

**Comment by Patras3** [comment]
Failed again on _master_ with zing-21: https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK21/29/testReport

**Comment by olukas** [comment]
Failed again on _master_ with ZingJDK17: https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK17/66/testReport/

**Comment by olukas** [comment]
Failed again on master with:
- ZingJDK17: https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK17/67/testReport/

**Comment by olukas** [comment]
Failed again on master with:
- ZingJDK17: https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK17/68/testReport/

Failed again on 5.5.z with ZingJDK21: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-ZingJDK21/16/testReport/

**Comment by Patras3** [comment]
Failed again on master with:
* ZingJDK21: https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK21/33/testReport/
* ZingJDK17: https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK17/69/testReport/

**Comment by olukas** [comment]
Failed again on master with:
- ZingJDK17: https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK17/70/testReport/

**Comment by olukas** [comment]
Failed again on 5.5.z with ZingJDK21: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-ZingJDK21/19/testReport/

**Comment by olukas** [comment]
Failed again on master with:
- ZingJDK17: https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK17/72/testReport/

**Comment by olukas** [comment]
Failed again on master with:
- ZingJDK17: https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK17/74/testReport/
- ZingJDK21: https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK21/37/testReport/

**Comment by AleksPeychev** [comment]
Failed again on _master_ with zing-17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZingJDK17/75/testReport/

**Comment by AleksPeychev** [comment]
Fails constantly on master with `zing-17`

**Comment by sumnerib** [comment]
Failed again on _master_ with zing-21: https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK21/41/testReport/com.hazelcast.internal.server.tcp/TcpServerContextTest/

**Comment by sumnerib** [comment]
Failed again on _master_ with zing-21: https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK21/42/testReport/com.hazelcast.internal.server.tcp/TcpServerContextTest/

**Comment by AleksPeychev** [comment]
Anomalous failures caused by Mockito on Zing JDK 17 and 21 tracked https://github.com/hazelcast/hazelcast/issues/23517
