### ISSUE TITLE
Suppress sqlResult.close() exception

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast#23524]
**Please describe the problem you are trying to solve**
In 5.3.0-SNAPSHOT (`(20230131 - 535ab5c)`), using `sqlResult.close()` results in an exception in the logs that is difficult to associate with the query being cancelled -- will cause confusion.

This code
```
	private static final String MAP_NAME = "m";
	
    public static void main(String[] args) throws Exception {
    	Config config = new Config();
    	config.getJetConfig().setEnabled(true);
    	HazelcastInstance hazelcastInstance = Hazelcast.newHazelcastInstance(config);

    	// Two entries
    	hazelcastInstance.getMap(MAP_NAME).put(1, 1);
    	hazelcastInstance.getMap(MAP_NAME).put(2, 2);
    	
    	String mapping = "CREATE MAPPING " + MAP_NAME
                + " TYPE IMap"
                + " OPTIONS ("
                + "  'keyFormat' = 'java',"
                + "  'keyJavaClass' = '" + Integer.class.getName() + "',"
                + "  'valueFormat' = 'java',"
                + "  'valueJavaClass' = '" + Integer.class.getName() + "'"
                + " )";
    	hazelcastInstance.getSql().execute(mapping);
    	
    	String query = "SELECT * FROM " + MAP_NAME;
    	SqlResult sqlResult = hazelcastInstance.getSql().execute(query);
    	Iterator<SqlRow> iterator = sqlResult.iterator();
    	SqlRow first = iterator.next();
    	System.out.println(first);
    	
    	// Close before iterator exhausted
    	sqlResult.close();
    	
    	TimeUnit.MINUTES.sleep(1L);
    	hazelcastInstance.shutdown();
    }
```
gives
```
Jan 31, 2023 10:17:40 AM com.hazelcast.jet.impl.operation.SubmitJobOperation
WARNING: [xxx.xxx.xxx.xxx]:5701 [dev] [5.3.0-SNAPSHOT] null
java.util.concurrent.CancellationException
	at com.hazelcast.jet.sql.impl.processors.RootResultConsumerSink.tryProcess(RootResultConsumerSink.java:97)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.lambda$stateMachineStep$2(ProcessorTasklet.java:334)
	at com.hazelcast.jet.impl.util.Util.doWithClassLoader(Util.java:547)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:334)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:328)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:291)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:404)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.run(TaskletExecutionService.java:369)
	at java.base/java.lang.Thread.run(Thread.java:1589)
```

...

**Please describe the desired behavior**
...
Ideally, suppress the exception for this case, there is no fault to closing the result set after processing enough of the input but not all of it.

**Describe alternatives you've considered**
...
Rather than `null`, alternatively the SQL could be listed.

**Comment by viliam-durina** [comment]
Error handling should be as simple as possible, because it's the less tested part of each code base, and yet it's very important if there's some problem. `SqlResult.close` cancels the underlying job, so the cancellation exception is just fine I'd say.
