### ISSUE TITLE
com.hazelcast.map.impl.mapstore.offload.MapStoreOffloadingBouncingNodeTest.stress [HZ-2343]

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hazelcast#23526]
_5.2.z_ (commit a43b66809cad8db3a54737d2026e4b3e6091370d)

Failure for variant `[writeBehindEnabled: true]`

Failed on openjdk-11: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-ZuluJDK11/71/testReport/junit/com.hazelcast.map.impl.mapstore.offload/MapStoreOffloadingBouncingNodeTest/stress_writeBehindEnabled__true_/
<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: expected:<0> but was:<1>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at com.hazelcast.map.impl.mapstore.offload.MapStoreOffloadingBouncingNodeTest.lambda$stress$2(MapStoreOffloadingBouncingNodeTest.java:163)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1247)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1349)
	at com.hazelcast.map.impl.mapstore.offload.MapStoreOffloadingBouncingNodeTest.stress(MapStoreOffloadingBouncingNodeTest.java:160)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:829)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-5.maintenance-ZuluJDK11/71/

**Comment by olukas** [comment]
Failed again on _master_ with Windows - MicrosoftJDK17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Windows-MicrosoftJDK17/50/testReport/com.hazelcast.map.impl.mapstore.offload/MapStoreOffloadingBouncingNodeTest/stress_writeBehindEnabled__true_/

**Comment by olukas** [comment]
Failed again on _master_ with openjdk-8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZuluJDK8/231/testReport/com.hazelcast.map.impl.mapstore.offload/MapStoreOffloadingBouncingNodeTest/stress_writeBehindEnabled__true_/

**Comment by olukas** [comment]
Failed again on _master_ with Windows - MicrosoftJDK11: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Windows-MicrosoftJDK11/60/testReport/com.hazelcast.map.impl.mapstore.offload/MapStoreOffloadingBouncingNodeTest/stress_writeBehindEnabled__true_/

**Comment by olukas** [comment]
Failed again on _5.2.z_ with oracle-11: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-sonar-new/76/testReport/com.hazelcast.map.impl.mapstore.offload/MapStoreOffloadingBouncingNodeTest/stress_writeBehindEnabled__true_/
