### ISSUE TITLE
com.hazelcast.map.EntryProcessorBouncingNodesTest.testEntryProcessorWhileTwoNodesAreBouncing [HZ-2226]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#23648]
_master_ (commit 77671d7d4dd4fe68b1a1cc36a90ac6a45a7cc941)

Failed on oracle-11 (sonar): 
- https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar-new/47/testReport/com.hazelcast.map/EntryProcessorBouncingNodesTest/testEntryProcessorWhileTwoNodesAreBouncing_withPredicate_true__withIndex_false_/
- https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar-new/47/testReport/com.hazelcast.map/EntryProcessorBouncingNodesTest/testEntryProcessorWhileTwoNodesAreBouncing_withPredicate_true__withIndex_true_/

If failed with variants:
- `[withPredicate=true, withIndex=false]`
- `[withPredicate=true, withIndex=true]`

<details><summary>Stacktrace:</summary>

```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.base@11.0.17/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@11.0.17/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
	at java.base@11.0.17/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1796)
	at java.base@11.0.17/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3128)
	at java.base@11.0.17/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1823)
	at java.base@11.0.17/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1998)
	at app//com.hazelcast.spi.impl.operationservice.impl.InvokeOnPartitions.invoke(InvokeOnPartitions.java:87)
	at app//com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.invokeOnAllPartitions(OperationServiceImpl.java:434)
	at app//com.hazelcast.map.impl.proxy.MapProxySupport.executeOnEntriesInternal(MapProxySupport.java:1311)
	at app//com.hazelcast.map.impl.proxy.MapProxyImpl.executeOnEntriesInternal(MapProxyImpl.java:112)
	at app//com.hazelcast.map.impl.proxy.MapProxyImpl.executeOnEntries(MapProxyImpl.java:876)
	at app//com.hazelcast.map.EntryProcessorBouncingNodesTest.testEntryProcessorWhileTwoNodesAreBouncing(EntryProcessorBouncingNodesTest.java:118)
	at java.base@11.0.17/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@11.0.17/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base@11.0.17/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@11.0.17/java.lang.reflect.Method.invoke(Method.java:566)
	at app//org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at app//org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at app//org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at app//org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at app//com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at app//com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base@11.0.17/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base@11.0.17/java.lang.Thread.run(Thread.java:834)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-sonar-new/47/

**Comment by olukas** [comment]
Failed again on _master_ with oracle-11 (sonar): 
- https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar-new/48/testReport/com.hazelcast.map/EntryProcessorBouncingNodesTest/testEntryProcessorWhileTwoNodesAreBouncing_withPredicate_true__withIndex_false_/
- https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar-new/48/testReport/com.hazelcast.map/EntryProcessorBouncingNodesTest/testEntryProcessorWhileTwoNodesAreBouncing_withPredicate_true__withIndex_true_/

**Comment by sumnerib** [comment]
Failed again on _master_ with oracle-11: https://jenkins.hazelcast.com/job/Hazelcast-master-sonar-new/55/testReport/junit/com.hazelcast.map/EntryProcessorBouncingNodesTest/

**Comment by olukas** [comment]
Failed again on _master_ with oracle-11: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar-new/61/testReport/com.hazelcast.map/EntryProcessorBouncingNodesTest/testEntryProcessorWhileTwoNodesAreBouncing_withPredicate_true__withIndex_false_/

**Comment by Patras3** [comment]
Failed again on _master_ with oracle-11: https://jenkins.hazelcast.com/job/Hazelcast-master-sonar-new/69/testReport/com.hazelcast.map/EntryProcessorBouncingNodesTest/testEntryProcessorWhileTwoNodesAreBouncing_withPredicate_true__withIndex_false_/

**Comment by Patras3** [comment]
Failed again on _master_ with oracle-11: https://jenkins.hazelcast.com/job/Hazelcast-master-sonar-new/72/testReport/com.hazelcast.map/EntryProcessorBouncingNodesTest/

**Comment by sumnerib** [comment]
Failed again on _master_ with oracle-11: https://jenkins.hazelcast.com/job/Hazelcast-master-sonar-new/75/testReport/junit/com.hazelcast.map/EntryProcessorBouncingNodesTest/

**Comment by olukas** [comment]
Failed again on _master_ with oracle-11: https://jenkins.hazelcast.com/job/Hazelcast-master-sonar-new/82/testReport/com.hazelcast.map/EntryProcessorBouncingNodesTest/testEntryProcessorWhileTwoNodesAreBouncing_withPredicate_true__withIndex_false_/

**Comment by Patras3** [comment]
Failed again on _master_ with oracle-11: https://jenkins.hazelcast.com/job/Hazelcast-master-sonar-new/91/testReport/com.hazelcast.map/EntryProcessorBouncingNodesTest/

**Comment by Patras3** [comment]
Failed again on _master_ with oracle-11: https://jenkins.hazelcast.com/job/Hazelcast-master-sonar-new/92/testReport/com.hazelcast.map/EntryProcessorBouncingNodesTest/

**Comment by olukas** [comment]
Failed again on _master_ with oracle-11: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar-new/95/testReport/com.hazelcast.map/EntryProcessorBouncingNodesTest/

**Comment by olukas** [comment]
Failed again on _master_ with oracle-11: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar-new/99/testReport/com.hazelcast.map/EntryProcessorBouncingNodesTest/

**Comment by olukas** [comment]
Failed again on _master_ with oracle-11: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar-new/103/testReport/com.hazelcast.map/EntryProcessorBouncingNodesTest/

**Comment by olukas** [comment]
Failed again on _master_ with oracle-11: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar-new/110/testReport/com.hazelcast.map/EntryProcessorBouncingNodesTest/

**Comment by olukas** [comment]
Failed again on _master_ with oracle-11: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/119/testReport/com.hazelcast.map/EntryProcessorBouncingNodesTest/

**Comment by vbekiaris** [comment]
The test is making slow progress when executed with a predicate and only manages to complete ~80-85 iterations until 5 minute timeout is reached in the sonar build
