### ISSUE TITLE
Mapstore and mongodb tests which use Docker cannot be run on Windows 

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#23650]
_master_ (commit 77671d7d4dd4fe68b1a1cc36a90ac6a45a7cc941)

Failed on Windows - MicrosoftJDK17: 
- https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Windows-MicrosoftJDK17/50/testReport/com.hazelcast.mapstore.mariadb/MariaDBGenericMapStoreIntegrationTest/___/
- https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Windows-MicrosoftJDK17/50/testReport/com.hazelcast.mapstore.mssql/MSSQLGenericMapStoreIntegrationTest/___/
- https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Windows-MicrosoftJDK17/50/testReport/com.hazelcast.mapstore.mysql/MySQLGenericMapStoreIntegrationTest/___/
- https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Windows-MicrosoftJDK17/50/testReport/com.hazelcast.mapstore.postgres/PostgreSQLGenericMapStoreIntegrationTest/___/

Following mapstore tests need to be ignored on Windows since they're using Docker environment:
- `com.hazelcast.mapstore.mariadb.MariaDBGenericMapStoreIntegrationTest`
- `com.hazelcast.mapstore.mssql.MSSQLGenericMapStoreIntegrationTest`
- `com.hazelcast.mapstore.mysql.MySQLGenericMapStoreIntegrationTest`
- `com.hazelcast.mapstore.postgres.PostgreSQLGenericMapStoreIntegrationTest`

<details><summary>Stacktrace:</summary>

```
java.lang.IllegalStateException: Could not find a valid Docker environment. Please see logs and check configuration
	at org.testcontainers.dockerclient.DockerClientProviderStrategy.lambda$getFirstValidStrategy$7(DockerClientProviderStrategy.java:256)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at org.testcontainers.dockerclient.DockerClientProviderStrategy.getFirstValidStrategy(DockerClientProviderStrategy.java:247)
	at org.testcontainers.DockerClientFactory.getOrInitializeStrategy(DockerClientFactory.java:150)
	at org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:186)
	at org.testcontainers.DockerClientFactory$1.getDockerClient(DockerClientFactory.java:104)
	at com.github.dockerjava.api.DockerClientDelegate.authConfig(DockerClientDelegate.java:108)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:321)
	at org.testcontainers.jdbc.ContainerDatabaseDriver.connect(ContainerDatabaseDriver.java:124)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:252)
	at com.hazelcast.test.jdbc.TestDatabaseProvider.waitForDb(TestDatabaseProvider.java:45)
	at com.hazelcast.test.jdbc.MariaDBDatabaseProvider.createDatabase(MariaDBDatabaseProvider.java:30)
	at com.hazelcast.mapstore.GenericMapStoreIntegrationTest.initializeBeforeClass(GenericMapStoreIntegrationTest.java:64)
	at com.hazelcast.mapstore.mariadb.MariaDBGenericMapStoreIntegrationTest.beforeClass(MariaDBGenericMapStoreIntegrationTest.java:34)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:41)
	at com.hazelcast.test.OverridePropertyRule$1.evaluate(OverridePropertyRule.java:66)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)

```
</details>

**Comment by sumnerib** [comment]
Failed again on _master_ with Windows - OracleJDK8: https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-OracleJDK8/435/

[com.hazelcast.mapstore.mariadb.MariaDBGenericMapStoreIntegrationTest.(?)](https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-OracleJDK8/lastSuccessfulBuild/testReport/junit/com.hazelcast.mapstore.mariadb/MariaDBGenericMapStoreIntegrationTest/___/)
[com.hazelcast.mapstore.mssql.MSSQLGenericMapStoreIntegrationTest.(?)](https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-OracleJDK8/lastSuccessfulBuild/testReport/junit/com.hazelcast.mapstore.mssql/MSSQLGenericMapStoreIntegrationTest/___/)
[com.hazelcast.mapstore.mysql.MySQLGenericMapStoreIntegrationTest.(?)](https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-OracleJDK8/lastSuccessfulBuild/testReport/junit/com.hazelcast.mapstore.mysql/MySQLGenericMapStoreIntegrationTest/___/)
[com.hazelcast.mapstore.postgres.PostgreSQLGenericMapStoreIntegrationTest.(?)](https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-OracleJDK8/lastSuccessfulBuild/testReport/junit/com.hazelcast.mapstore.postgres/PostgreSQLGenericMapStoreIntegrationTest/___/)
[com.hazelcast.jet.mongodb.MongoDBSinkTest.(?)](https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-OracleJDK8/lastSuccessfulBuild/testReport/junit/com.hazelcast.jet.mongodb/MongoDBSinkTest/___/)
[com.hazelcast.jet.mongodb.MongoDBSourceTest.(?)](https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-OracleJDK8/lastSuccessfulBuild/testReport/junit/com.hazelcast.jet.mongodb/MongoDBSourceTest/___/)

**Comment by sumnerib** [comment]
Failed again on _master_ with Windows - MicrosoftJDK17: https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK17/54/

[com.hazelcast.jet.sql.impl.connector.mongodb.AllTypesInsertMongoSqlConnectorTest.(?)](https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK17/lastSuccessfulBuild/testReport/junit/com.hazelcast.jet.sql.impl.connector.mongodb/AllTypesInsertMongoSqlConnectorTest/___/)
[com.hazelcast.jet.sql.impl.connector.mongodb.AllTypesSelectMongoSqlConnectorTest.(?)](https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK17/lastSuccessfulBuild/testReport/junit/com.hazelcast.jet.sql.impl.connector.mongodb/AllTypesSelectMongoSqlConnectorTest/___/)
[com.hazelcast.jet.sql.impl.connector.mongodb.FieldResolverTest.(?)](https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK17/lastSuccessfulBuild/testReport/junit/com.hazelcast.jet.sql.impl.connector.mongodb/FieldResolverTest/___/)
[com.hazelcast.jet.sql.impl.connector.mongodb.MongoBatchSqlConnectorTest.(?)](https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK17/lastSuccessfulBuild/testReport/junit/com.hazelcast.jet.sql.impl.connector.mongodb/MongoBatchSqlConnectorTest/___/)
[com.hazelcast.jet.sql.impl.connector.mongodb.MongoStreamSqlConnectorTest.(?)](https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK17/lastSuccessfulBuild/testReport/junit/com.hazelcast.jet.sql.impl.connector.mongodb/MongoStreamSqlConnectorTest/___/)
[com.hazelcast.jet.impl.connector.WriteJdbcPTest.(?)](https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK17/lastSuccessfulBuild/testReport/junit/com.hazelcast.jet.impl.connector/WriteJdbcPTest/___/)
[com.hazelcast.mapstore.mariadb.MariaDBGenericMapStoreIntegrationTest.(?)](https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK17/lastSuccessfulBuild/testReport/junit/com.hazelcast.mapstore.mariadb/MariaDBGenericMapStoreIntegrationTest/___/)
[com.hazelcast.mapstore.mssql.MSSQLGenericMapStoreIntegrationTest.(?)](https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK17/lastSuccessfulBuild/testReport/junit/com.hazelcast.mapstore.mssql/MSSQLGenericMapStoreIntegrationTest/___/)
[com.hazelcast.mapstore.mysql.MySQLGenericMapStoreIntegrationTest.(?)](https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK17/lastSuccessfulBuild/testReport/junit/com.hazelcast.mapstore.mysql/MySQLGenericMapStoreIntegrationTest/___/)
[com.hazelcast.mapstore.postgres.PostgreSQLGenericMapStoreIntegrationTest.(?)](https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK17/lastSuccessfulBuild/testReport/junit/com.hazelcast.mapstore.postgres/PostgreSQLGenericMapStoreIntegrationTest/___/)

**Comment by olukas** [comment]
Failed again on master with Windows - MicrosoftJDK17 https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Windows-MicrosoftJDK17/55/testReport/

**Comment by olukas** [comment]
Reopening as issue still occurs on: _master_ (commit dee4a19a2afcc14da031c1f59ee8224b74dc1d8e)
with Windows - MicrosoftJDK11: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Windows-MicrosoftJDK11/58/testReport/

Following tests failed with `Could not find a valid Docker environment. Please see logs and check configuration`:
- `com.hazelcast.mapstore.mariadb.MariaDBGenericMapStoreIntegrationTest.(?)`
- `com.hazelcast.mapstore.mongodb.MongoGenericMapStoreTest.(?)`
- `com.hazelcast.mapstore.mongodb.MongoGenericMapStoreTest.(?)`
- `com.hazelcast.mapstore.mssql.MSSQLGenericMapStoreIntegrationTest.(?)`
- `com.hazelcast.mapstore.mysql.MySQLGenericMapStoreIntegrationTest.(?)`
- `com.hazelcast.mapstore.postgres.PostgreSQLGenericMapStoreIntegrationTest.(?)`

**Comment by Patras3** [comment]
For mongo this failure looks like is related to AfterClass section:
`java.lang.NullPointerException: Cannot invoke "com.mongodb.client.MongoClient.close()" because "com.hazelcast.mapstore.mongodb.MongoGenericMapStoreTest.mongoClient" is null
	at com.hazelcast.mapstore.mongodb.MongoGenericMapStoreTest.afterClass(MongoGenericMapStoreTest.java:105)`
https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK17/56/testReport/com.hazelcast.mapstore.mongodb/MongoGenericMapStoreTest/____2/

**Comment by Patras3** [comment]
Failed again on _master_ with Windows - OracleJDK8: https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-OracleJDK8/440/testReport/com.hazelcast.mapstore.mssql/MSSQLGenericMapStoreIntegrationTest/___/

**Comment by olukas** [comment]
Failed again on _master_ with Windows - MicrosoftJDK17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Windows-MicrosoftJDK17/57/testReport/

Following tests failed with `Could not find a valid Docker environment. Please see logs and check configuration`:
- `com.hazelcast.mapstore.mariadb.MariaDBGenericMapStoreIntegrationTest.(?)`
- `com.hazelcast.mapstore.mssql.MSSQLGenericMapStoreIntegrationTest.(?)`
- `com.hazelcast.mapstore.mysql.MySQLGenericMapStoreIntegrationTest.(?)`
- `com.hazelcast.mapstore.postgres.PostgreSQLGenericMapStoreIntegrationTest.(?)`

`com.hazelcast.mapstore.mongodb.MongoGenericMapStoreTest.(?)` failed with `Cannot invoke "com.mongodb.client.MongoClient.close()" because "com.hazelcast.mapstore.mongodb.MongoGenericMapStoreTest.mongoClient" is null`.
