### ISSUE TITLE
Enhancement: support BIGSERIAL in generic map store

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast#23699]
**Please describe the problem you are trying to solve**
Using 5.2.2, a Postgres db with
```
 id                                 BIGSERIAL NOT NULL PRIMARY KEY,
```

results in
```
Caused by: java.lang.IllegalArgumentException: Unknown column type: bigserial
	at com.hazelcast.jet.sql.impl.connector.jdbc.JdbcSqlConnector.resolveType(JdbcSqlConnector.java:434) ~[hazelcast-sql-5.2.2.jar:5.2.2]
	at com.hazelcast.jet.sql.impl.connector.jdbc.JdbcSqlConnector.resolveAndValidateFields(JdbcSqlConnector.java:101) ~[hazelcast-sql-5.2.2.jar:5.2.2]
	at com.hazelcast.jet.sql.impl.schema.TableResolverImpl.resolveMapping(TableResolverImpl.java:139) ~[hazelcast-sql-5.2.2.jar:5.2.2]
	at com.hazelcast.jet.sql.impl.schema.TableResolverImpl.createMapping(TableResolverImpl.java:121) ~[hazelcast-sql-5.2.2.jar:5.2.2]
	at com.hazelcast.jet.sql.impl.PlanExecutor.execute(PlanExecutor.java:137) ~[hazelcast-sql-5.2.2.jar:5.2.2]
	at com.hazelcast.jet.sql.impl.SqlPlanImpl$CreateMappingPlan.execute(SqlPlanImpl.java:146) ~[hazelcast-sql-5.2.2.jar:5.2.2]
	at com.hazelcast.sql.impl.SqlServiceImpl.query0(SqlServiceImpl.java:269) ~[hazelcast-enterprise-5.2.2.jar:5.2.2]
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:207) ~[hazelcast-enterprise-5.2.2.jar:5.2.2]
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:175) ~[hazelcast-enterprise-5.2.2.jar:5.2.2]
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:171) ~[hazelcast-enterprise-5.2.2.jar:5.2.2]
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:167) ~[hazelcast-enterprise-5.2.2.jar:5.2.2]
	at com.hazelcast.sql.SqlService.execute(SqlService.java:89) ~[hazelcast-enterprise-5.2.2.jar:5.2.2]
	at com.hazelcast.mapstore.GenericMapStore.createMapping(GenericMapStore.java:243) ~[hazelcast-mapstore-5.2.2.jar:?]
	at com.hazelcast.mapstore.GenericMapStore.resolveMappingColumns(GenericMapStore.java:229) ~[hazelcast-mapstore-5.2.2.jar:?]
	at com.hazelcast.mapstore.GenericMapStore.createMappingForMapStore(GenericMapStore.java:180) ~[hazelcast-mapstore-5.2.2.jar:?]
	at com.hazelcast.mapstore.GenericMapStore.lambda$init$0(GenericMapStore.java:160) ~[hazelcast-mapstore-5.2.2.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
```

**Please describe the desired behavior**
`BIGSERIAL` to be supported

**Describe alternatives you've considered**
Not feasible to change the PK column on an existing table

**Comment by neilstevenson** [comment]
(Same for `SERIAL`)
