### ISSUE TITLE
tstore:  NullPointerException pinSegment LocalStorageDevice TieredStorageImpl (Jet SQL job failed)

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#23704]
using the lab and laster master

com.hazelcast.sql.HazelcastSqlException: The Jet SQL job failed: Execution on a member failed: com.hazelcast.jet.JetException: Exception in ProcessorTasklet{0971-09f0-f709-0001/IMap[public.mapBak1HDtstore1]#0}: java.lang.NullPointerException
	at com.hazelcast.sql.impl.QueryUtils.toPublicException(QueryUtils.java:74)
	at com.hazelcast.jet.sql.impl.SqlResultImpl$RowToSqlRowIterator.hasNext(SqlResultImpl.java:108)

Caused by: com.hazelcast.sql.impl.QueryException: The Jet SQL job failed: Execution on a member failed: com.hazelcast.jet.JetException: Exception in ProcessorTasklet{0971-09f0-f709-0001/IMap[public.mapBak1HDtstore1]#0}: java.lang.NullPointerException
	at com.hazelcast.sql.impl.QueryException.error(QueryException.java:69)

Caused by: com.hazelcast.jet.JetException: Execution on a member failed: com.hazelcast.jet.JetException: Exception in ProcessorTasklet{0971-09f0-f709-0001/IMap[public.mapBak1HDtstore1]#0}: java.lang.NullPointerException
	at com.hazelcast.jet.impl.LightMasterContext.findError(LightMasterContext.java:315)

Caused by: com.hazelcast.jet.JetException: Exception in ProcessorTasklet{0971-09f0-f709-0001/IMap[public.mapBak1HDtstore1]#0}: java.lang.NullPointerException
	at com.hazelcast.jet.impl.execution.TaskletExecutionService.handleTaskletExecutionError(TaskletExecutionService.java:286)

Caused by: java.lang.NullPointerException
	at com.hazelcast.internal.tstore.device.local.LocalStorageDevice.pinSegment(LocalStorageDevice.java:636)
	at com.hazelcast.map.impl.recordstore.TieredStorageImpl$IndexDependencies.pinSegment(TieredStorageImpl.java:680)
	at com.hazelcast.internal.tstore.index.Index.pinSegments(Index.java:1085)
	at com.hazelcast.internal.tstore.index.Index.handlePendingRecords(Index.java:1068)
	at com.hazelcast.internal.tstore.index.Index.fetchEntries(Index.java:1055)
	at com.hazelcast.map.impl.recordstore.TieredStorageImpl.fetchEntries(TieredStorageImpl.java:435)

/nfs/danny/output-21Feb-tstore-sql
HZ/HzMember1HZ/exception.txt

interestingly i don’t see this issue in the aws ec2 version of this test.

**Comment by petrpleshachkov** [comment]
We NPE on trying to pin segment which is GCed already. That is a sympotom of invalid address issue. We get a list of logical addresses from the Index not refreshing the epoch. After that under protection of the same epoch we try to find the corresponding Segment and fail. So, Index returns already invalid addresses.
