### ISSUE TITLE
com.hazelcast.client.starter.HazelcastClientStarterTest.testClientLifecycle [API-1997]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#23764]
_5.2.z_ (commit 644a0050c0feaf6bd6ff842729e0f47a537e7a37)

Failed on ibm-8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-IbmJDK8-nightly/73/testReport/com.hazelcast.client.starter/HazelcastClientStarterTest/testClientLifecycle/
<details><summary>Stacktrace:</summary>

```
com.hazelcast.test.starter.GuardianException: java.net.SocketTimeoutException: Read timed out
	at com.hazelcast.test.starter.HazelcastStarterUtils.rethrowGuardianException(HazelcastStarterUtils.java:53)
	at com.hazelcast.test.starter.HazelcastVersionLocator.downloadFile(HazelcastVersionLocator.java:129)
	at com.hazelcast.test.starter.HazelcastVersionLocator.downloadArtifact(HazelcastVersionLocator.java:102)
	at com.hazelcast.test.starter.HazelcastVersionLocator.locateArtifact(HazelcastVersionLocator.java:94)
	at com.hazelcast.test.starter.HazelcastVersionLocator.locateVersion(HazelcastVersionLocator.java:77)
	at com.hazelcast.test.starter.HazelcastStarter$HazelcastVersionClassloaderFuture.get(HazelcastStarter.java:402)
	at com.hazelcast.test.starter.HazelcastStarter.getTargetVersionClassloader(HazelcastStarter.java:265)
	at com.hazelcast.client.starter.HazelcastClientStarter.newHazelcastClient(HazelcastClientStarter.java:54)
	at com.hazelcast.client.starter.HazelcastClientStarter.newHazelcastClient(HazelcastClientStarter.java:48)
	at com.hazelcast.client.starter.HazelcastClientStarter.newHazelcastClient(HazelcastClientStarter.java:43)
	at com.hazelcast.client.starter.HazelcastClientStarterTest.testClientLifecycle(HazelcastClientStarterTest.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.lang.Thread.run(Thread.java:825)
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:127)
	at java.net.SocketInputStream.read(SocketInputStream.java:182)
	at java.net.SocketInputStream.read(SocketInputStream.java:152)
	at com.ibm.jsse2.ak.a(ak.java:141)
	at com.ibm.jsse2.ak.g(ak.java:155)
	at com.ibm.jsse2.ak.d(ak.java:79)
	at com.ibm.jsse2.bj.a(bj.java:333)
	at com.ibm.jsse2.bj.access$300(bj.java:429)
	at com.ibm.jsse2.bj$b.read(bj$b.java:95)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:257)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:297)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:356)
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:766)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:709)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1605)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1510)
	at com.ibm.net.ssl.www2.protocol.https.b.getInputStream(b.java:20)
	at com.hazelcast.test.starter.HazelcastVersionLocator.downloadFile(HazelcastVersionLocator.java:123)
	... 21 more

```
</details>

<details><summary>Standard output:</summary>

```
class com.hazelcast.instance.impl.HazelcastInstanceFactory loaded by HazelcastAPIDelegatingClassloader{urls = "[file:/home/jenkins/.m2/repository/com/hazelcast/hazelcast/4.0.3/hazelcast-4.0.3-tests.jar, file:/home/jenkins/tmp/1677342865727-0/4.0.3/hazelcast-4.0.3.jar]"}
16:40:42,199  INFO |testClientLifecycle| - [MetricsConfigHelper] testClientLifecycle - [LOCAL] [dev] [4.0.3] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
16:40:42,199  INFO |testClientLifecycle| - [AddressPicker] testClientLifecycle - [LOCAL] [dev] [4.0.3] Picked [127.0.0.1]:5701, using socket ServerSocket[addr=/0.0.0.0,localport=5701], bind any local is true
16:40:42,199  INFO |testClientLifecycle| - [system] testClientLifecycle - [127.0.0.1]:5701 [dev] [4.0.3] Hazelcast 4.0.3 (20200921 - 59ae831) starting at [127.0.0.1]:5701
16:40:42,199  INFO |testClientLifecycle| - [system] testClientLifecycle - [127.0.0.1]:5701 [dev] [4.0.3] Copyright (c) 2008-2020, Hazelcast, Inc. All Rights Reserved.
16:40:42,201  INFO |testClientLifecycle| - [MetricsConfigHelper] testClientLifecycle - [127.0.0.1]:5701 [dev] [4.0.3] Collecting debug metrics and sending to diagnostics is enabled
16:40:42,201  INFO |testClientLifecycle| - [BackpressureRegulator] testClientLifecycle - [127.0.0.1]:5701 [dev] [4.0.3] Backpressure is disabled
16:40:42,207  WARN |testClientLifecycle| - [Node] testClientLifecycle - [127.0.0.1]:5701 [dev] [4.0.3] Hazelcast is bound to 127.0.0.1 and loop-back mode is disabled in the configuration. This could cause multicast auto-discovery issues and render it unable to work. Check your network connectivity, try to enable the loopback mode and/or force -Djava.net.preferIPv4Stack=true on your JVM.
16:40:42,207  INFO |testClientLifecycle| - [Node] testClientLifecycle - [127.0.0.1]:5701 [dev] [4.0.3] Creating MulticastJoiner
16:40:42,207  WARN |testClientLifecycle| - [CPSubsystem] testClientLifecycle - [127.0.0.1]:5701 [dev] [4.0.3] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
16:40:42,214  INFO |testClientLifecycle| - [OperationExecutorImpl] testClientLifecycle - [127.0.0.1]:5701 [dev] [4.0.3] Starting 8 partition threads and 5 generic threads (1 dedicated for priority tasks)
16:40:42,215  INFO |testClientLifecycle| - [Diagnostics] testClientLifecycle - [127.0.0.1]:5701 [dev] [4.0.3] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
16:40:42,215  INFO |testClientLifecycle| - [LifecycleService] testClientLifecycle - [127.0.0.1]:5701 [dev] [4.0.3] [127.0.0.1]:5701 is STARTING
16:40:44,167  INFO |testClientLifecycle| - [ClusterService] testClientLifecycle - [127.0.0.1]:5701 [dev] [4.0.3] 

Members {size:1, ver:1} [
	Member [127.0.0.1]:5701 - fea0f5b0-b96d-4351-899f-75fa185face6 this
]

16:40:44,168  INFO |testClientLifecycle| - [LifecycleService] testClientLifecycle - [127.0.0.1]:5701 [dev] [4.0.3] [127.0.0.1]:5701 is STARTED
Starting client 4.0.1
16:40:50,958  INFO |testClientLifecycle| - [LifecycleService] main - [127.0.0.1]:5701 [dev] [4.0.3] [127.0.0.1]:5701 is SHUTTING_DOWN
16:40:50,959  INFO |testClientLifecycle| - [Node] main - [127.0.0.1]:5701 [dev] [4.0.3] Shutting down multicast service...
16:40:50,959  INFO |testClientLifecycle| - [Node] main - [127.0.0.1]:5701 [dev] [4.0.3] Shutting down connection manager...
16:40:50,960  INFO |testClientLifecycle| - [Node] main - [127.0.0.1]:5701 [dev] [4.0.3] Shutting down node engine...
16:40:50,965  INFO |testClientLifecycle| - [NodeExtension] main - [127.0.0.1]:5701 [dev] [4.0.3] Destroying node NodeExtension.
16:40:50,965  INFO |testClientLifecycle| - [Node] main - [127.0.0.1]:5701 [dev] [4.0.3] Hazelcast Shutdown is completed in 7 ms.
16:40:50,965  INFO |testClientLifecycle| - [LifecycleService] main - [127.0.0.1]:5701 [dev] [4.0.3] [127.0.0.1]:5701 is SHUTDOWN

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-5.maintenance-IbmJDK8-nightly/73/

**Comment by mdumandag** [comment]
We have failed to download the artifact in the test, I believe the fix in the https://github.com/hazelcast/hazelcast/pull/23126 would also help here. I will backport it to 5.2.z

**Comment by mdumandag** [comment]
Fixed by https://github.com/hazelcast/hazelcast/pull/24192
