### ISSUE TITLE
com.hazelcast.jet.mongodb.MongoDBSinkResilienceTest.testSink_networkTimeout [HZ-2559]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#23763]
_master_ (commit 66094111c244d948f883e9b5dd5ae56bae082c1b)

Failed on oracle-8 (little-endian): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-nightly-little-endian/15/testReport/com.hazelcast.jet.mongodb/MongoDBSinkResilienceTest/testSink_networkTimeout/
<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: expected:<169> but was:<33>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at com.hazelcast.jet.mongodb.MongoDBSinkResilienceTest.lambda$sinkNetworkTest$4(MongoDBSinkResilienceTest.java:240)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1277)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1381)
	at com.hazelcast.jet.mongodb.MongoDBSinkResilienceTest.sinkNetworkTest(MongoDBSinkResilienceTest.java:239)
	at com.hazelcast.jet.mongodb.MongoDBSinkResilienceTest.testSink_networkTimeout(MongoDBSinkResilienceTest.java:171)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:750)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-nightly-little-endian/15/

**Comment by TomaszGaweda** [comment]
Test no longer exist
