### ISSUE TITLE
AWS: IMDSv2 and ECS-EC2 Discovery

### ISSUE THREAD

**Issue by afriedrichsen-cal** [hazelcast/hazelcast#23778]
**Describe the bug**
IMDSv1/v2 are not available to ECS EC2 containers running `awsvpc` networking mode. [Recent changes](https://github.com/hazelcast/hazelcast/compare/v5.2.1...v5.2.2#diff-4e70491c4d78f5c6bd4a05b9066e0ac29a47e5ed7b57edb553ba12a549462810) merged into release `5.2.2` appear to force usage of EC2 metadata/token endpoints that are unavailable to ECS tasks running VPC networking. Previously this worked in version `5.2.1`

**Expected behavior**
Hazelcast containers running as ECS/EC2 tasks in `awsvpc` networking should instead respect/leverage `AWS_CONTAINER_CREDENTIALS_RELATIVE_URI`

**To Reproduce**

1. Run `hazelcast:5.2.2` as an ECS EC2 task with `awsvpc` networking mode
2. Alternatively, run standard container (ex. `ubuntu:latest`) as an ECS EC2 task and test web request to `EC2_METADATA_TOKEN_ENDPOINT` 

**Stack Trace (3 Container Cluster running on ECS-EC2)**
```
Feb 28, 2023 8:58:04 PM com.hazelcast.internal.config.override.ExternalConfigurationOverride
INFO: Detected external configuration entries in environment variables: [hazelcast.network.join.aws.region=us-east-2,hazelcast.network.join.aws.enabled=true,hazelcast.clustername=WFO_LockGrid,hazelcast.network.join.aws.servicename=hazelcast,hazelcast.network.join.multicast.enabled=false,hazelcast.network.port.port=5701,hazelcast.network.join.aws.hzport=5701-5708,hazelcast.partitiongroup.grouptype=ZONE_AWARE,hazelcast.cpsubsystem.cpmembercount=3,hazelcast.network.interfaces.enabled=true,hazelcast.partitiongroup.enabled=true]
Feb 28, 2023 8:58:05 PM com.hazelcast.instance.AddressPicker
INFO: [LOCAL] [WFO_LockGrid] [5.2.2] Interfaces is enabled, trying to pick one address matching to one of: [10.0.*.*]
Feb 28, 2023 8:58:05 PM com.hazelcast.system.logo
INFO: [X.X.X.X]:5701 [WFO_LockGrid] [5.2.2]
'+ + o o o o---o o----o o o---o o o----o o--o--o
'+ + + + | | / \ / | | / / \ | |
'+ + + + + o----o o o o o----o | o o o o----o |
'+ + + + | | / \ / | | \ / \ | |
'+ + o o o o o---o o----o o----o o---o o o o----o o
Feb 28, 2023 8:58:05 PM com.hazelcast.system
INFO: [X.X.X.X]:5701 [WFO_LockGrid] [5.2.2] Copyright (c) 2008-2022, Hazelcast, Inc. All Rights Reserved.
Feb 28, 2023 8:58:05 PM com.hazelcast.system
INFO: [X.X.X.X]:5701 [WFO_LockGrid] [5.2.2] Hazelcast Platform 5.2.2 (20230215 - a221adc) starting at [X.X.X.X]:5701
Feb 28, 2023 8:58:05 PM com.hazelcast.system
INFO: [X.X.X.X]:5701 [WFO_LockGrid] [5.2.2] Cluster name: WFO_LockGrid
Feb 28, 2023 8:58:05 PM com.hazelcast.system
INFO: [X.X.X.X]:5701 [WFO_LockGrid] [5.2.2] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed. For more information, see the documentation for Integrity Checker.
Feb 28, 2023 8:58:05 PM com.hazelcast.system
INFO: [X.X.X.X]:5701 [WFO_LockGrid] [5.2.2] The Jet engine is disabled.
To enable the Jet engine on the members, do one of the following:
'- Change member config using Java API: config.getJetConfig().setEnabled(true)
'- Change XML/YAML configuration property: Set hazelcast.jet.enabled to true
'- Add system property: -Dhz.jet.enabled=true (for Hazelcast embedded, works only when loading config via Config.load)
'- Add environment variable: HZ_JET_ENABLED=true (recommended when running container image. For Hazelcast embedded, works only when loading config via Config.load)
Feb 28, 2023 8:58:05 PM com.hazelcast.aws.AwsDiscoveryStrategy
INFO: Using AWS discovery plugin with configuration: AwsConfig{accessKey='***', secretKey='***', iamRole='null', region='us-east-2', hostHeader='null', securityGroupName='null', tags='[]', hzPort=5701-5708, cluster='null', family='null', serviceName='hazelcast', connectionTimeoutSeconds=10, connectionRetries=3, readTimeoutSeconds=10, discoveryMode=Member}
Feb 28, 2023 8:58:05 PM com.hazelcast.aws.AwsCredentialsProvider
INFO: Using IAM Task Role attached to ECS Task
Feb 28, 2023 8:58:05 PM com.hazelcast.spi.utils.RetryUtils
WARNING: Couldn't connect to the service, [1] retrying in 1 seconds...
Feb 28, 2023 8:58:06 PM com.hazelcast.spi.utils.RetryUtils
WARNING: Couldn't connect to the service, [2] retrying in 2 seconds...
Feb 28, 2023 8:58:09 PM com.hazelcast.spi.utils.RetryUtils
WARNING: Couldn't connect to the service, [3] retrying in 3 seconds...
Feb 28, 2023 8:58:12 PM com.hazelcast.instance.impl.Node
SEVERE: [X.X.X.X]:5701 [WFO_LockGrid] [5.2.2] Node creation failed
java.lang.RuntimeException: Failed to configure discovery strategies
at com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.loadDiscoveryStrategies(DefaultDiscoveryService.java:161)
at com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.<init>(DefaultDiscoveryService.java:58)
at com.hazelcast.spi.discovery.impl.DefaultDiscoveryServiceProvider.newDiscoveryService(DefaultDiscoveryServiceProvider.java:29)
at com.hazelcast.instance.impl.Node.createDiscoveryService(Node.java:360)
at com.hazelcast.instance.impl.Node.<init>(Node.java:281)
at com.hazelcast.instance.impl.HazelcastInstanceImpl.createNode(HazelcastInstanceImpl.java:149)
at com.hazelcast.instance.impl.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:118)
at com.hazelcast.instance.impl.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:217)
at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:196)
at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:134)
at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:95)
at com.hazelcast.core.server.HazelcastMemberStarter.main(HazelcastMemberStarter.java:45)
at com.hazelcast.commandline.HazelcastServerCommandLine.lambda$new$2f647568$1(HazelcastServerCommandLine.java:44)
at com.hazelcast.jet.function.RunnableEx.run(RunnableEx.java:31)
at com.hazelcast.commandline.HazelcastServerCommandLine.start(HazelcastServerCommandLine.java:101)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at picocli.CommandLine.executeUserObject(CommandLine.java:1972)
at picocli.CommandLine.access$1300(CommandLine.java:145)
at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
at picocli.CommandLine.execute(CommandLine.java:2078)
at com.hazelcast.commandline.HazelcastServerCommandLine.runCommandLine(HazelcastServerCommandLine.java:63)
at com.hazelcast.commandline.HazelcastServerCommandLine.main(HazelcastServerCommandLine.java:52)
Caused by: com.hazelcast.spi.exception.RestClientException: Failure in executing REST call
at com.hazelcast.spi.utils.RestClient.call(RestClient.java:171)
at com.hazelcast.spi.utils.RestClient.lambda$callWithRetries$0(RestClient.java:138)
at com.hazelcast.spi.utils.RetryUtils.retry(RetryUtils.java:65)
at com.hazelcast.spi.utils.RetryUtils.retry(RetryUtils.java:51)
at com.hazelcast.spi.utils.RestClient.callWithRetries(RestClient.java:138)
at com.hazelcast.spi.utils.RestClient.put(RestClient.java:134)
at com.hazelcast.aws.AwsMetadataApi.retrieveToken(AwsMetadataApi.java:178)
at com.hazelcast.aws.AwsMetadataApi.metadataToken(AwsMetadataApi.java:170)
at com.hazelcast.aws.AwsMetadataApi.metadataClient(AwsMetadataApi.java:165)
at com.hazelcast.aws.AwsMetadataApi.getTaskMetadata(AwsMetadataApi.java:134)
at com.hazelcast.aws.AwsMetadataApi.clusterEcs(AwsMetadataApi.java:97)
at com.hazelcast.aws.AwsClientConfigurator.resolveCluster(AwsClientConfigurator.java:144)
at com.hazelcast.aws.AwsClientConfigurator.createAwsClient(AwsClientConfigurator.java:67)
at com.hazelcast.aws.AwsDiscoveryStrategy.<init>(AwsDiscoveryStrategy.java:91)
at com.hazelcast.aws.AwsDiscoveryStrategyFactory.newDiscoveryStrategy(AwsDiscoveryStrategyFactory.java:52)
at com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.buildDiscoveryStrategy(DefaultDiscoveryService.java:195)
at com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.loadDiscoveryStrategies(DefaultDiscoveryService.java:141)
... 28 more
Caused by: java.net.ConnectException: Invalid argument (connect failed)
at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
at java.base/java.net.Socket.connect(Socket.java:609)
at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:177)
at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:507)
at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:602)
at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:275)
at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:374)
at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:395)
at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1253)
at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1015)
at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592)
at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
at com.hazelcast.spi.utils.RestClient.checkResponseCode(RestClient.java:224)
at com.hazelcast.spi.utils.RestClient.call(RestClient.java:168)
... 44 more
Feb 28, 2023 8:58:12 PM com.hazelcast.instance.impl.Node
INFO: [X.X.X.X]:5701 [WFO_LockGrid] [5.2.2] Shutting down connection manager...
Feb 28, 2023 8:58:12 PM com.hazelcast.instance.impl.Node
INFO: [X.X.X.X]:5701 [WFO_LockGrid] [5.2.2] Shutting down node engine...
Feb 28, 2023 8:58:12 PM com.hazelcast.instance.impl.NodeExtension
INFO: [X.X.X.X]:5701 [WFO_LockGrid] [5.2.2] Destroying node NodeExtension.
Failed to configure discovery strategies
Usage: hz start [-hV] [-c=<file>] [-i=<interface>] [-p=<port>]
Starts a new Hazelcast member
'-h, --help Show this help message and exit.
'-V, --version Print version information and exit.
'-c, --config=<file> Use <file> for Hazelcast configuration. Accepted
formats are XML and YAML.
'-p, --port=<port> Bind to the specified <port>. Please note that if the
specified port is in use, it will auto-increment to
the first free port. (default: 5701)
'-i, --interface=<interface>
Bind to the specified <interface>.
```

**hazelcast.yaml**
```
hazelcast:
  network:
      port: 5701
    join:
      multicast:
        enabled: false
      aws:
        enabled: true
        host-header: ecs
    interfaces:
      enabled: true
      interfaces:
        - 10.0.*.*
```

**Comment by hasancelik** [comment]
Closing... fixed by https://github.com/hazelcast/hazelcast/pull/23939 at 5.2.3 release.
