### ISSUE TITLE
com.hazelcast.jet.kafka.connect.KafkaConnectCouchbaseIntegrationTest.(?) [HZ-2214]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#23779]
_master_ (commit 7efc0243e13a0b0c9a00afcb98cdb44da84ef924)

Failed on oracle-11: https://jenkins.hazelcast.com/job/Hazelcast-master-sonar-new/63/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectCouchbaseIntegrationTest/___/
<details><summary>Stacktrace:</summary>

```
org.testcontainers.containers.ContainerLaunchException: Container startup failed
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:349)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322)
	at org.testcontainers.containers.GenericContainer.starting(GenericContainer.java:1094)
	at org.testcontainers.containers.FailureDetectingExternalResource$1.evaluate(FailureDetectingExternalResource.java:28)
	at com.hazelcast.test.OverridePropertyRule$1.evaluate(OverridePropertyRule.java:66)
	at com.hazelcast.test.OverridePropertyRule$1.evaluate(OverridePropertyRule.java:66)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:334)
	... 9 more
Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:542)
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:344)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
	... 10 more
Caused by: java.lang.RuntimeException: Could not perform request against couchbase HTTP endpoint 
	at org.testcontainers.couchbase.CouchbaseContainer.doHttpRequest(CouchbaseContainer.java:790)
	at org.testcontainers.couchbase.CouchbaseContainer.renameNode(CouchbaseContainer.java:400)
	at org.testcontainers.couchbase.CouchbaseContainer.timePhase(CouchbaseContainer.java:802)
	at org.testcontainers.couchbase.CouchbaseContainer.containerIsStarting(CouchbaseContainer.java:341)
	at org.testcontainers.containers.GenericContainer.containerIsStarting(GenericContainer.java:692)
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:474)
	... 12 more
Caused by: java.io.IOException: unexpected end of stream on http://172.17.0.1:41599/...
	at org.testcontainers.shaded.okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:202)
	at org.testcontainers.shaded.okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106)
	at org.testcontainers.shaded.okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79)
	at org.testcontainers.shaded.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at org.testcontainers.shaded.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
	at org.testcontainers.shaded.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at org.testcontainers.shaded.okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at org.testcontainers.shaded.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at org.testcontainers.shaded.okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at org.testcontainers.shaded.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at org.testcontainers.shaded.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at org.testcontainers.shaded.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at org.testcontainers.shaded.okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at org.testcontainers.shaded.okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at org.testcontainers.couchbase.CouchbaseContainer.doHttpRequest(CouchbaseContainer.java:788)
	... 17 more
	Suppressed: java.io.IOException: unexpected end of stream on http://172.17.0.1:41599/...
		... 32 more
	Caused by: java.io.EOFException: \n not found: limit=0 content=…
		at org.testcontainers.shaded.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:332)
		at org.testcontainers.shaded.okhttp3.internal.http1.HeadersReader.readLine(HeadersReader.kt:29)
		at org.testcontainers.shaded.okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:178)
		... 31 more
Caused by: java.io.EOFException: \n not found: limit=0 content=…
	at org.testcontainers.shaded.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:332)
	at org.testcontainers.shaded.okhttp3.internal.http1.HeadersReader.readLine(HeadersReader.kt:29)
	at org.testcontainers.shaded.okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:178)
	... 31 more

```
</details>

<details><summary>Standard output:</summary>

```
04:46:03,371  INFO || - [34]] Time-limited test - Creating container for image: mysql:5.7.34
04:46:04,118  INFO || - [34]] Time-limited test - Container mysql:5.7.34 is starting: d55da07e1ebc7ed370f56bcdc661f382a74c833a2fcb7da6fe04c5e9de0e1838
04:46:04,694  INFO || - [34]] Time-limited test - Waiting for database connection to become available at jdbc:mysql://172.17.0.1:41600/test using query 'SELECT 1'
04:46:14,080  INFO || - [34]] Time-limited test - Container is started (JDBC URL: jdbc:mysql://172.17.0.1:41600/test)
04:46:14,080  INFO || - [34]] Time-limited test - Container mysql:5.7.34 started in PT10.709519S

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-sonar-new/63/

**Comment by Patras3** [comment]
Failed again on _master_ with oracle-11: https://jenkins.hazelcast.com/job/Hazelcast-master-sonar-new/72/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectCouchbaseIntegrationTest/___/

**Comment by sumnerib** [comment]
Failed again on _master_ with openjdk-19: https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK-sts-nightly/20/testReport/junit/com.hazelcast.jet.kafka.connect/KafkaConnectCouchbaseIntegrationTest/___/

**Comment by olukas** [comment]
Failed again on _master_ with oracle-11: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar-new/81/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectCouchbaseIntegrationTest/___/

**Comment by olukas** [comment]
Reopening as issue occurred again on: _master_ (commit 336728cfb054666fb5e4c4c93f74feaebeec4dc4)
with openjdk-19: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-OpenJDK-sts-nightly/23/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectCouchbaseIntegrationTest/___/
<details><summary>Stacktrace:</summary>

```
org.testcontainers.containers.ContainerLaunchException: Container startup failed
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:349)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322)
	at com.hazelcast.jet.kafka.connect.KafkaConnectCouchbaseIntegrationTest.setUpDocker(KafkaConnectCouchbaseIntegrationTest.java:90)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:41)
	at com.hazelcast.test.OverridePropertyRule$1.evaluate(OverridePropertyRule.java:66)
	at com.hazelcast.test.OverridePropertyRule$1.evaluate(OverridePropertyRule.java:66)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:334)
	... 17 more
Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:542)
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:344)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
	... 18 more
Caused by: java.lang.RuntimeException: Could not perform request against couchbase HTTP endpoint 
	at org.testcontainers.couchbase.CouchbaseContainer.doHttpRequest(CouchbaseContainer.java:790)
	at org.testcontainers.couchbase.CouchbaseContainer.renameNode(CouchbaseContainer.java:400)
	at org.testcontainers.couchbase.CouchbaseContainer.timePhase(CouchbaseContainer.java:802)
	at org.testcontainers.couchbase.CouchbaseContainer.containerIsStarting(CouchbaseContainer.java:341)
	at org.testcontainers.containers.GenericContainer.containerIsStarting(GenericContainer.java:692)
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:474)
	... 20 more
Caused by: java.io.IOException: unexpected end of stream on http://172.17.0.1:59766/...
	at org.testcontainers.shaded.okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:202)
	at org.testcontainers.shaded.okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106)
	at org.testcontainers.shaded.okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79)
	at org.testcontainers.shaded.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at org.testcontainers.shaded.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
	at org.testcontainers.shaded.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at org.testcontainers.shaded.okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at org.testcontainers.shaded.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at org.testcontainers.shaded.okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at org.testcontainers.shaded.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at org.testcontainers.shaded.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at org.testcontainers.shaded.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at org.testcontainers.shaded.okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at org.testcontainers.shaded.okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at org.testcontainers.couchbase.CouchbaseContainer.doHttpRequest(CouchbaseContainer.java:788)
	... 25 more
	Suppressed: java.io.IOException: unexpected end of stream on http://172.17.0.1:59766/...
		... 40 more
	Caused by: java.io.EOFException: \n not found: limit=0 content=…
		at org.testcontainers.shaded.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:332)
		at org.testcontainers.shaded.okhttp3.internal.http1.HeadersReader.readLine(HeadersReader.kt:29)
		at org.testcontainers.shaded.okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:178)
		... 39 more
Caused by: java.io.EOFException: \n not found: limit=0 content=…
	at org.testcontainers.shaded.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:332)
	at org.testcontainers.shaded.okhttp3.internal.http1.HeadersReader.readLine(HeadersReader.kt:29)
	at org.testcontainers.shaded.okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:178)
	... 39 more

```
</details>

**Comment by olukas** [comment]
Failed again on _master_ with oracle-11: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar-new/96/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectCouchbaseIntegrationTest/___/

**Comment by arodionov** [comment]
Failed on nightly test https://jenkins.hazelcast.com/job/Hazelcast-pr-nightly-tests/68/testReport/junit/com.hazelcast.jet.kafka.connect/KafkaConnectCouchbaseIntegrationTest/___/

**Comment by ldziedziul** [comment]
@olukas Could you re-run it with this PR merged https://github.com/hazelcast/hazelcast/pull/24169 ?

**Comment by olukas** [comment]
@ldziedziul Thanks, I ran the job which runs only `KafkaConnectCouchbaseIntegrationTest` test and it passed. Closing this issue, we can reopen it if it would happen again.
