### ISSUE TITLE
com.hazelcast.mapstore.mysql.MySQLGenericMapStoreIntegrationTest.(?) [HZ-2307]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#23782]
_master_ (commit 4121505b3ab10249d37d6fbb7efc53a7c5b3d58a)

Failed on MacOS: https://jenkins.hazelcast.com/job/Hazelcast-master-MacOS-ZuluJDK8/171/testReport/com.hazelcast.mapstore.mysql/MySQLGenericMapStoreIntegrationTest/___/
<details><summary>Stacktrace:</summary>

```
org.testcontainers.containers.ContainerLaunchException: Container startup failed
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:349)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322)
	at org.testcontainers.jdbc.ContainerDatabaseDriver.connect(ContainerDatabaseDriver.java:124)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at com.hazelcast.test.jdbc.TestDatabaseProvider.waitForDb(TestDatabaseProvider.java:45)
	at com.hazelcast.test.jdbc.MySQLDatabaseProvider.createDatabase(MySQLDatabaseProvider.java:30)
	at com.hazelcast.mapstore.GenericMapStoreIntegrationTest.initializeBeforeClass(GenericMapStoreIntegrationTest.java:67)
	at com.hazelcast.mapstore.mysql.MySQLGenericMapStoreIntegrationTest.beforeClass(MySQLGenericMapStoreIntegrationTest.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:41)
	at com.hazelcast.test.OverridePropertyRule$1.evaluate(OverridePropertyRule.java:66)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:334)
	... 24 more
Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:542)
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:344)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
	... 25 more
Caused by: com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"error creating overlay mount to /var/lib/docker/overlay2/78c4f23119c1a5624a0cc28895272088065c52c957c725486ba3509c7952f5f0-init/merged: invalid argument"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247)
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.post(DefaultInvocationBuilder.java:124)
	at org.testcontainers.shaded.com.github.dockerjava.core.exec.CreateContainerCmdExec.execute(CreateContainerCmdExec.java:37)
	at org.testcontainers.shaded.com.github.dockerjava.core.exec.CreateContainerCmdExec.execute(CreateContainerCmdExec.java:13)
	at org.testcontainers.shaded.com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21)
	at org.testcontainers.shaded.com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
	at org.testcontainers.shaded.com.github.dockerjava.core.command.CreateContainerCmdImpl.exec(CreateContainerCmdImpl.java:608)
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:427)
	... 27 more

```
</details>

<details><summary>Standard output:</summary>

```
09:58:25,379  INFO || - [MetricsConfigHelper] Time-limited test - [LOCAL] [dev] [5.3.0-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
09:58:25,379  INFO || - [logo] Time-limited test - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
09:58:25,379  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Copyright (c) 2008-2023, Hazelcast, Inc. All Rights Reserved.
09:58:25,379  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Hazelcast Platform 5.3.0-SNAPSHOT (20230301 - 4121505) starting at [127.0.0.1]:5701
09:58:25,379  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Cluster name: dev
09:58:25,379  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed. For more information, see the documentation for Integrity Checker.
09:58:25,379  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Jet is enabled
09:58:25,382  INFO || - [MetricsConfigHelper] Time-limited test - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
09:58:25,385  WARN || - [CPSubsystem] Time-limited test - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
09:58:25,386  INFO || - [JetServiceBackend] Time-limited test - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Setting number of cooperative threads and default parallelism to 2
09:58:25,387  INFO || - [Diagnostics] Time-limited test - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
09:58:25,387  INFO || - [LifecycleService] Time-limited test - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] [127.0.0.1]:5701 is STARTING
09:58:25,388  INFO || - [ClusterService] Time-limited test - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] 

Members {size:1, ver:1} [
	Member [127.0.0.1]:5701 - e56173dc-115b-49f7-943d-13c47f257a9c this
]

09:58:25,388  INFO || - [JobCoordinationService] Time-limited test - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Jet started scanning for jobs
09:58:25,388  INFO || - [LifecycleService] Time-limited test - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] [127.0.0.1]:5701 is STARTED
09:58:25,388  INFO || - [MetricsConfigHelper] Time-limited test - [LOCAL] [dev] [5.3.0-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
09:58:25,388  INFO || - [logo] Time-limited test - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
09:58:25,388  INFO || - [system] Time-limited test - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Copyright (c) 2008-2023, Hazelcast, Inc. All Rights Reserved.
09:58:25,388  INFO || - [system] Time-limited test - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Hazelcast Platform 5.3.0-SNAPSHOT (20230301 - 4121505) starting at [127.0.0.1]:5702
09:58:25,388  INFO || - [system] Time-limited test - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Cluster name: dev
09:58:25,388  INFO || - [system] Time-limited test - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed. For more information, see the documentation for Integrity Checker.
09:58:25,388  INFO || - [system] Time-limited test - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Jet is enabled
09:58:25,390  INFO || - [MetricsConfigHelper] Time-limited test - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
09:58:25,393  WARN || - [CPSubsystem] Time-limited test - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
09:58:25,394  INFO || - [JetServiceBackend] Time-limited test - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Setting number of cooperative threads and default parallelism to 2
09:58:25,395  INFO || - [Diagnostics] Time-limited test - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
09:58:25,395  INFO || - [LifecycleService] Time-limited test - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] [127.0.0.1]:5702 is STARTING
09:58:25,395  INFO || - [MockServer] Time-limited test - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Created connection to endpoint: [127.0.0.1]:5701-e56173dc-115b-49f7-943d-13c47f257a9c, connection: MockConnection{localEndpoint=[address=[127.0.0.1]:5702, uuid=dbd84a2c-7520-48bd-9836-62c986f52b96], remoteEndpoint=[address=[127.0.0.1]:5701, uuid=e56173dc-115b-49f7-943d-13c47f257a9c], alive=true}
09:58:25,396  INFO || - [MockServer] hz.GenericMapStoreTest_vibrant_jackson.priority-generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Created connection to endpoint: [127.0.0.1]:5702-dbd84a2c-7520-48bd-9836-62c986f52b96, connection: MockConnection{localEndpoint=[address=[127.0.0.1]:5701, uuid=e56173dc-115b-49f7-943d-13c47f257a9c], remoteEndpoint=[address=[127.0.0.1]:5702, uuid=dbd84a2c-7520-48bd-9836-62c986f52b96], alive=true}
09:58:25,396  INFO || - [ClusterService] hz.GenericMapStoreTest_vibrant_jackson.priority-generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] 

Members {size:2, ver:2} [
	Member [127.0.0.1]:5701 - e56173dc-115b-49f7-943d-13c47f257a9c this
	Member [127.0.0.1]:5702 - dbd84a2c-7520-48bd-9836-62c986f52b96
]

09:58:25,503  INFO || - [ClusterService] hz.GenericMapStoreTest_elated_jackson.generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] 

Members {size:2, ver:2} [
	Member [127.0.0.1]:5701 - e56173dc-115b-49f7-943d-13c47f257a9c
	Member [127.0.0.1]:5702 - dbd84a2c-7520-48bd-9836-62c986f52b96 this
]

09:58:25,503  INFO || - [JobCoordinationService] Time-limited test - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Jet started scanning for jobs
09:58:25,503  INFO || - [LifecycleService] Time-limited test - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] [127.0.0.1]:5702 is STARTED
Started Running Test: whenSetNonExistingColumnOnSecondMapStore_thenFailToInitialize

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-MacOS-ZuluJDK8/171/

**Comment by olukas** [comment]
Failed again on _master_ with MacOS: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-MacOS-ZuluJDK8/189/testReport/com.hazelcast.mapstore.mysql/MySQLGenericMapStoreIntegrationTest/___/

**Comment by Patras3** [comment]
Failed again on _master_ with MacOS: https://jenkins.hazelcast.com/job/Hazelcast-master-MacOS-ZuluJDK8/191/testReport/com.hazelcast.mapstore.mysql/MySQLGenericMapStoreIntegrationTest/___/

**Comment by olukas** [comment]
Failed again on _master_ with MacOS with ZuluJDK8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-MacOS-ZuluJDK8/192/testReport/com.hazelcast.mapstore.mysql/MySQLGenericMapStoreIntegrationTest/___/

**Comment by olukas** [comment]
Failed again on _master_ with MacOS: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-MacOS-ZuluJDK8/195/testReport/com.hazelcast.mapstore.mysql/MySQLGenericMapStoreIntegrationTest/___/

**Comment by olukas** [comment]
It seems to fail consistently on MacOS.

**Comment by olukas** [comment]
Failed again on _master_ with MacOS: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-MacOS-ZuluJDK8/197/testReport/com.hazelcast.mapstore.mysql/MySQLGenericMapStoreIntegrationTest/___/

**Comment by olukas** [comment]
Failed again on _master_ with MacOS with ZuluJDK8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-MacOS-ZuluJDK8/201/testReport/com.hazelcast.mapstore.mysql/MySQLGenericMapStoreIntegrationTest/___/

**Comment by ldziedziul** [comment]
Tried to start mysql:8.0.32 and seems to be working:
![image](https://user-images.githubusercontent.com/1242724/234281414-224eca99-8d97-4452-9460-3b3b7364ccec.png)
