### ISSUE TITLE
PostgreSQLGenericMapStoreIntegrationTest>GenericMapStoreIntegrationTest.testExceptionIsConstructable

### ISSUE THREAD

**Issue by arodionov** [hazelcast/hazelcast#23811]
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/16672/Hazelcast-pr-builder-16672.zip), [artifacts](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/16672/Hazelcast-pr-builder-16672.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   PostgreSQLGenericMapStoreIntegrationTest>GenericMapStoreIntegrationTest.testExceptionIsConstructable:310 
Expecting actual throwable to be an instance of:
  com.hazelcast.sql.HazelcastSqlException
but was:
  java.lang.NullPointerException
	at com.hazelcast.mapstore.GenericMapStore.load(GenericMapStore.java:306)
	at com.hazelcast.mapstore.GenericMapStore.load(GenericMapStore.java:98)
	at com.hazelcast.map.impl.MapStoreWrapper.load(MapStoreWrapper.java:164)
	...(44 remaining lines not displayed - this can be changed with Assertions.setMaxStackTraceElementsDisplayed)
[INFO] 
[ERROR] Tests run: 140, Failures: 1, Errors: 0, Skipped: 1
[INFO] 

[ERROR] There are test failures.
</pre>
</details>

_Originally posted by @hz-devops-test in https://github.com/hazelcast/hazelcast/issues/23604#issuecomment-1451711694_

**Comment by orcunc** [comment]
Duplicate of https://github.com/hazelcast/hazelcast/issues/23846
