### ISSUE TITLE
com.hazelcast.internal.tpcengine.nio.NioAsyncSocket_LargePayloadTest_Nightly

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#23823]
_master_ (commit f90c4fb7cb4eaa22364aecf2cc6c927dbc26cbae)

Failed on ibm-8 (fips): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-IbmJDK8-fips-nightly/518/testReport/junit/com.hazelcast.internal.tpc.nio/NioAsyncSocket_LargePayloadTest_Nightly/

All tests in `NioAsyncSocket_LargePayloadTest_Nightly` failed with the same exception.

<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at com.hazelcast.internal.tpc.TpcTestSupport.lambda$assertOpenEventually$1(TpcTestSupport.java:126)
	at com.hazelcast.internal.tpc.TpcTestSupport.assertTrueEventually(TpcTestSupport.java:156)
	at com.hazelcast.internal.tpc.TpcTestSupport.assertTrueEventually(TpcTestSupport.java:185)
	at com.hazelcast.internal.tpc.TpcTestSupport.assertOpenEventually(TpcTestSupport.java:124)
	at com.hazelcast.internal.tpc.TpcTestSupport.assertOpenEventually(TpcTestSupport.java:120)
	at com.hazelcast.internal.tpc.AsyncSocket_LargePayloadTest.test(AsyncSocket_LargePayloadTest.java:217)
	at com.hazelcast.internal.tpc.AsyncSocket_LargePayloadTest.test_concurrency_10_payload_0B(AsyncSocket_LargePayloadTest.java:130)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:107)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:83)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)

```
</details>

<details><summary>Standard output:</summary>

```
[WARNING] Couldn't load group class 'com.hazelcast.test.annotation.SlowTest' in Surefire|Failsafe plugin. The group class is ignored!
Starting

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-IbmJDK8-fips-nightly/518/

**Comment by Patras3** [comment]
Failed again on _master_ with zing-8 (two tests): 
* https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK8-nightly/21/testReport/junit/com.hazelcast.internal.tpc.nio/NioAsyncSocket_LargePayloadTest_Nightly/test_concurrency_1_payload_2MB/
* https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK8-nightly/21/testReport/junit/com.hazelcast.internal.tpc.nio/NioAsyncSocket_LargePayloadTest_Nightly/test_concurrency_1_payload_2MB/

**Comment by sumnerib** [comment]
Failed again on _master_ with oracle-8 (little-endian): https://jenkins.hazelcast.com/job/Hazelcast-master-nightly-little-endian/17/testReport/junit/com.hazelcast.internal.tpc.nio/NioAsyncSocket_LargePayloadTest_Nightly/test_concurrency_10_payload_2MB/

**Comment by olukas** [comment]
Failed again on _master_ with ibm-8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-IbmJDK8-fips-nightly/524/testReport/com.hazelcast.internal.tpcengine.nio/NioAsyncSocket_LargePayloadTest_Nightly/test_concurrency_10_payload_0B/

**Comment by Patras3** [comment]
Failed again on _master_ with ibm-8: https://jenkins.hazelcast.com/job/Hazelcast-master-IbmJDK8-fips-nightly/524/testReport/com.hazelcast.internal.tpcengine.nio/NioAsyncSocket_LargePayloadTest_Nightly/

**Comment by olukas** [comment]
Failed again on _master_ with:
- ibm-8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-IbmJDK8-nightly/98/testReport/com.hazelcast.internal.tpcengine.nio/NioAsyncSocket_LargePayloadTest_Nightly/
- ibm-8 in FIPS mode: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-IbmJDK8-fips-nightly/527/testReport/com.hazelcast.internal.tpcengine.nio/NioAsyncSocket_LargePayloadTest_Nightly/

**Comment by ramizdundar** [comment]
Closed by:

- https://github.com/hazelcast/hazelcast/pull/24267
- https://github.com/hazelcast/hazelcast/pull/24319
