### ISSUE TITLE
com.hazelcast.internal.util.ThreadAffinityTest

### ISSUE THREAD

**Issue by Patras3** [hazelcast/hazelcast#23836]
_master_ (commit 83371a644146617653c1e5a83c72a04264b4175c)

Failed on openj9-11: https://jenkins.hazelcast.com/job/Hazelcast-master-Openj9-11/121/testReport/junit/com.hazelcast.internal.util/ThreadAffinityTest in five tests with the same reason:
```Thread affinity support is not available```:
* [whenComplex](https://jenkins.hazelcast.com/job/Hazelcast-master-Openj9-11/121/testReport/junit/com.hazelcast.internal.util/ThreadAffinityTest/whenComplex)
* [whenGroup](https://jenkins.hazelcast.com/job/Hazelcast-master-Openj9-11/121/testReport/junit/com.hazelcast.internal.util/ThreadAffinityTest/whenGroup)
* [whenGroupAndThreadCount](https://jenkins.hazelcast.com/job/Hazelcast-master-Openj9-11/121/testReport/junit/com.hazelcast.internal.util/ThreadAffinityTest/whenGroupAndThreadCount)
* [whenIndividualCores](https://jenkins.hazelcast.com/job/Hazelcast-master-Openj9-11/121/testReport/junit/com.hazelcast.internal.util/ThreadAffinityTest/whenIndividualCores)
* [whenRange](https://jenkins.hazelcast.com/job/Hazelcast-master-Openj9-11/121/testReport/junit/com.hazelcast.internal.util/ThreadAffinityTest/whenRange)

Details for _whenComplex_ test:  
<details><summary>Stacktrace:</summary>

```
java.lang.RuntimeException: Can't use affinity '1,3-4,[5-8]:2,10,[20,21,32]:2'. Thread affinity support is not available.
	at com.hazelcast.internal.util.ThreadAffinity.<init>(ThreadAffinity.java:51)
	at com.hazelcast.internal.util.ThreadAffinityTest.whenComplex(ThreadAffinityTest.java:143)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:107)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:83)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)

```
</details>

<details><summary>Standard output:</summary>

```
08:31:49,660  WARN || - [ThreadAffinityHelper] main - The OpenHFT Affinity jar isn't available: net/openhft/affinity/Affinity

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-Openj9-11/121/

**Comment by pveentjer** [comment]
This functionality comes from the hazelcast module. No clue why this now starts to fail.
