### ISSUE TITLE
com.hazelcast.mapstore.postgres.PostgreSQLGenericMapStoreIntegrationTest.testExceptionIsConstructable [HZ-2225]

### ISSUE THREAD

**Issue by Patras3** [hazelcast/hazelcast#23846]
_master_ (commit 83371a644146617653c1e5a83c72a04264b4175c)

Failed on corretto-8: https://jenkins.hazelcast.com/job/Hazelcast-master-CorrettoJDK8/218/testReport/junit/com.hazelcast.mapstore.postgres/PostgreSQLGenericMapStoreIntegrationTest/testExceptionIsConstructable/
<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: 

Expecting code to raise a throwable.
	at com.hazelcast.mapstore.GenericMapStoreIntegrationTest.testExceptionIsConstructable(GenericMapStoreIntegrationTest.java:309)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:750)

```
</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: testPutAll in 0.078 seconds.
Started Running Test: testExceptionIsConstructable
19:00:17,028 DEBUG || - [GenericMapLoader] hz.PostgreSQLGenericMapStoreIntegrationTest_eager_roentgen.cached.thread-14 - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Initializing for map table_o_044ed218_be17_4fea_bfc0_6f4f975d4482
19:00:17,029  INFO || - [DefaultRecordStore] hz.PostgreSQLGenericMapStoreIntegrationTest_eager_roentgen.partition-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Starting to load all keys for map table_o_044ed218_be17_4fea_bfc0_6f4f975d4482 on partitionId=0
19:00:17,042  WARN || - [InitExecutionOperation] hz.PostgreSQLGenericMapStoreIntegrationTest_eager_roentgen.cached.thread-13 - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] null
java.util.concurrent.CancellationException: null
	at com.hazelcast.jet.sql.impl.processors.RootResultConsumerSink.tryProcess(RootResultConsumerSink.java:97) ~[hazelcast-sql-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.lambda$stateMachineStep$2(ProcessorTasklet.java:334) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.jet.impl.util.Util.doWithClassLoader(Util.java:547) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:334) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:328) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:291) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:404) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:895) ~[?:1.8.0_352]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.run(TaskletExecutionService.java:369) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_352]
19:00:17,050 DEBUG || - [GenericMapLoader] hz.PostgreSQLGenericMapStoreIntegrationTest_jolly_roentgen.cached.thread-13 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Initializing for map table_o_044ed218_be17_4fea_bfc0_6f4f975d4482
19:00:17,065  WARN || - [InitExecutionOperation] hz.PostgreSQLGenericMapStoreIntegrationTest_jolly_roentgen.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] null
java.util.concurrent.CancellationException: null
	at com.hazelcast.jet.sql.impl.processors.RootResultConsumerSink.tryProcess(RootResultConsumerSink.java:97) ~[hazelcast-sql-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.lambda$stateMachineStep$2(ProcessorTasklet.java:334) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.jet.impl.util.Util.doWithClassLoader(Util.java:547) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:334) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:328) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:291) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:404) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:895) ~[?:1.8.0_352]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.run(TaskletExecutionService.java:369) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_352]
19:00:17,065  WARN || - [SubmitJobOperation] hz.PostgreSQLGenericMapStoreIntegrationTest_jolly_roentgen.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] null
java.util.concurrent.CancellationException: null
	at com.hazelcast.jet.sql.impl.processors.RootResultConsumerSink.tryProcess(RootResultConsumerSink.java:97) ~[hazelcast-sql-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.lambda$stateMachineStep$2(ProcessorTasklet.java:334) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.jet.impl.util.Util.doWithClassLoader(Util.java:547) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:334) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:328) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:291) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:404) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:895) ~[?:1.8.0_352]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.run(TaskletExecutionService.java:369) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_352]
19:00:18,142  INFO |testExceptionIsConstructable| - [SqlTestSupport] Time-limited test - Removing 0 cached plans in SqlTestSupport.@After
19:00:18,142  INFO |testExceptionIsConstructable| - [SqlTestSupport] Time-limited test - Removing 0 cached plans in SqlTestSupport.@After
19:00:18,143  INFO |testExceptionIsConstructable| - [SimpleTestInClusterSupport] Time-limited test - Ditching 0 jobs in SimpleTestInClusterSupport.@After: []
19:00:18,143  INFO |testExceptionIsConstructable| - [SimpleTestInClusterSupport] Time-limited test - Destroying 2 distributed objects in SimpleTestInClusterSupport.@After: [hz:impl:mapService/table_o_044ed218_be17_4fea_bfc0_6f4f975d4482, hz:impl:mapService/__sql.catalog]
19:00:18,143  INFO || - [GenericMapLoader] hz.PostgreSQLGenericMapStoreIntegrationTest_jolly_roentgen.cached.thread-12 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Dropping mapping __map-store.table_o_044ed218_be17_4fea_bfc0_6f4f975d4482
19:00:18,144  INFO || - [GenericMapLoader] hz.PostgreSQLGenericMapStoreIntegrationTest_eager_roentgen.cached.thread-17 - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Dropping mapping __map-store.table_o_044ed218_be17_4fea_bfc0_6f4f975d4482
BuildInfo right after testExceptionIsConstructable(com.hazelcast.mapstore.postgres.PostgreSQLGenericMapStoreIntegrationTest): BuildInfo{version='5.3.0-SNAPSHOT', build='20230305', buildNumber=20230305, revision=83371a6, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'testExceptionIsConstructable(com.hazelcast.mapstore.postgres.PostgreSQLGenericMapStoreIntegrationTest):'
19:00:15, accumulated pauses: 1050 ms, max pause: 1037 ms, pauses over 1000 ms: 1


No metrics recorded during the test

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-CorrettoJDK8/218/

**Comment by olukas** [comment]
Failed again on _master_ with openjdk-19: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-OpenJDK-sts/31/testReport/com.hazelcast.mapstore.postgres/PostgreSQLGenericMapStoreIntegrationTest/testExceptionIsConstructable/

**Comment by Patras3** [comment]
Failed again on _master_ with oracle-11: https://jenkins.hazelcast.com/job/Hazelcast-master-sonar-new/88/testReport/com.hazelcast.mapstore.postgres/PostgreSQLGenericMapStoreIntegrationTest/testExceptionIsConstructable/

**Comment by olukas** [comment]
`com.hazelcast.mapstore.mysql.MySQLGenericMapStoreIntegrationTest.testExceptionIsConstructable` failed again on _master_ with redhat-11: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-RedHatJDK11/78/testReport/com.hazelcast.mapstore.mysql/MySQLGenericMapStoreIntegrationTest/testExceptionIsConstructable/

**Comment by olukas** [comment]
Failed again on _master_ with oracle-11: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-OracleJDK11/368/testReport/com.hazelcast.mapstore.postgres/PostgreSQLGenericMapStoreIntegrationTest/testExceptionIsConstructable/

**Comment by Patras3** [comment]
Failed again on _master_ with oracle-11: https://jenkins.hazelcast.com/job/Hazelcast-master-mysql-5.7/14/testReport/junit/com.hazelcast.mapstore.mysql/MySQLGenericMapStoreIntegrationTest/testExceptionIsConstructable/

**Comment by olukas** [comment]
Closing the test failure - it doesn't seem to be related to `master` or the latest maintenance stream `5.5.z` and it hasn't fail in the last 3 months. Feel free to reopen test failure if it occurs on `master` or on the latest maintenance stream.
