### ISSUE TITLE
[TPC] com.hazelcast.internal.tpcengine.nio.NioAsyncSocket_ReadableTest.test

### ISSUE THREAD

**Issue by Patras3** [hazelcast/hazelcast#23841]
_master_ (commit 83371a644146617653c1e5a83c72a04264b4175c)

Failed on ibm-8: https://jenkins.hazelcast.com/job/Hazelcast-master-IbmJDK8/225/testReport/junit/com.hazelcast.internal.tpc.nio/NioAsyncSocket_ReadableTest/test/
<details><summary>Stacktrace:</summary>

```
java.util.concurrent.CompletionException: java.nio.channels.CancelledKeyException
	at java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:386)
	at java.util.concurrent.CompletableFuture.join(CompletableFuture.java:1958)
	at com.hazelcast.internal.tpc.nio.NioAsyncSocket.setReadable(NioAsyncSocket.java:145)
	at com.hazelcast.internal.tpc.AsyncSocket_ReadableTest.test(AsyncSocket_ReadableTest.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:107)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:83)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
Caused by: java.nio.channels.CancelledKeyException
	at sun.nio.ch.SelectionKeyImpl.ensureValid(SelectionKeyImpl.java:85)
	at sun.nio.ch.SelectionKeyImpl.interestOps(SelectionKeyImpl.java:89)
	at com.hazelcast.internal.tpc.nio.NioAsyncSocket.setReadable0(NioAsyncSocket.java:153)
	at com.hazelcast.internal.tpc.nio.NioAsyncSocket.lambda$setReadable$0(NioAsyncSocket.java:137)
	at com.hazelcast.internal.tpc.Eventloop.runExternalTasks(Eventloop.java:166)
	at com.hazelcast.internal.tpc.nio.NioEventloop.run(NioEventloop.java:91)
	at com.hazelcast.internal.tpc.Reactor$StartEventloopTask.run(Reactor.java:380)
	at java.lang.Thread.run(Thread.java:825)

```
</details>

<details><summary>Standard output:</summary>

```
Mar 03, 2023 10:12:09 PM com.hazelcast.internal.tpc.logging.JulLoggerFactory$JulLogger info
INFO: Thread-48 Binding to /127.0.0.1:5000
Mar 03, 2023 10:12:09 PM com.hazelcast.internal.tpc.logging.JulLoggerFactory$JulLogger info
INFO: /127.0.0.1:5000 started accepting
Mar 03, 2023 10:12:09 PM com.hazelcast.internal.tpc.logging.JulLoggerFactory$JulLogger info
INFO: Connecting to address:/127.0.0.1:5000
Mar 03, 2023 10:12:09 PM com.hazelcast.internal.tpc.logging.JulLoggerFactory$JulLogger info
INFO: NioAsyncServerSocket[/127.0.0.1:5000] accepted: /127.0.0.1:51460->/127.0.0.1:5000
Mar 03, 2023 10:12:09 PM com.hazelcast.internal.tpc.logging.JulLoggerFactory$JulLogger info
INFO: Connection established NioAsyncSocket[/127.0.0.1:51460->/127.0.0.1:5000]
Mar 03, 2023 10:12:09 PM com.hazelcast.internal.tpc.logging.JulLoggerFactory$JulLogger info
INFO: Connection established NioAsyncSocket[/127.0.0.1:51460->/127.0.0.1:5000]
Mar 03, 2023 10:12:09 PM com.hazelcast.internal.tpc.logging.JulLoggerFactory$JulLogger info
INFO: Closing NioAsyncSocket[/127.0.0.1:51460->/127.0.0.1:5000] due to Reactor-1 is terminating.
Mar 03, 2023 10:12:09 PM com.hazelcast.internal.tpc.logging.JulLoggerFactory$JulLogger severe
SEVERE: java.lang.NullPointerException
java.lang.NullPointerException
	at com.hazelcast.internal.tpc.nio.NioAsyncSocket$Handler.handleConnect(NioAsyncSocket.java:448)
	at com.hazelcast.internal.tpc.nio.NioAsyncSocket$Handler.handle(NioAsyncSocket.java:388)
	at com.hazelcast.internal.tpc.nio.NioEventloop.run(NioEventloop.java:84)
	at com.hazelcast.internal.tpc.Reactor$StartEventloopTask.run(Reactor.java:380)
	at java.lang.Thread.run(Thread.java:825)

Mar 03, 2023 10:12:09 PM com.hazelcast.internal.tpc.logging.JulLoggerFactory$JulLogger info
INFO: Closing NioAsyncSocket[/127.0.0.1:5000->/127.0.0.1:51460] due to Remote socket closed!
Mar 03, 2023 10:12:09 PM com.hazelcast.internal.tpc.logging.JulLoggerFactory$JulLogger info
INFO: Thread-47 terminated
Mar 03, 2023 10:12:09 PM com.hazelcast.internal.tpc.logging.JulLoggerFactory$JulLogger warning
WARNING: java.nio.channels.CancelledKeyException
java.nio.channels.CancelledKeyException
	at sun.nio.ch.SelectionKeyImpl.ensureValid(SelectionKeyImpl.java:85)
	at sun.nio.ch.SelectionKeyImpl.interestOps(SelectionKeyImpl.java:89)
	at com.hazelcast.internal.tpc.nio.NioAsyncSocket.setReadable0(NioAsyncSocket.java:153)
	at com.hazelcast.internal.tpc.nio.NioAsyncSocket.lambda$setReadable$0(NioAsyncSocket.java:137)
	at com.hazelcast.internal.tpc.Eventloop.runExternalTasks(Eventloop.java:166)
	at com.hazelcast.internal.tpc.nio.NioEventloop.run(NioEventloop.java:91)
	at com.hazelcast.internal.tpc.Reactor$StartEventloopTask.run(Reactor.java:380)
	at java.lang.Thread.run(Thread.java:825)

Mar 03, 2023 10:12:09 PM com.hazelcast.internal.tpc.logging.JulLoggerFactory$JulLogger info
INFO: Closing NioAsyncServerSocket[/127.0.0.1:5000] due to Reactor-1 is terminating.
Mar 03, 2023 10:12:09 PM com.hazelcast.internal.tpc.logging.JulLoggerFactory$JulLogger info
INFO: Thread-48 terminated

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-IbmJDK8/225/

**Comment by olukas** [comment]
Failed again on _master_ with ibm-8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-IbmJDK8/225/testReport/junit/com.hazelcast.internal.tpc.nio/NioAsyncSocket_ReadableTest/test/

**Comment by olukas** [comment]
Failed again on: _master_ (commit 2b08d23caa99a542700755b6063007f2fa67bc00)
with ibm-8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-IbmJDK8/226/testReport/com.hazelcast.internal.tpc.nio/NioAsyncSocket_ReadableTest/test/
<details><summary>But stacktrace was different:</summary>

```
java.lang.AssertionError: expected:<8> but was:<0>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at com.hazelcast.internal.tpc.AsyncSocket_ReadableTest.lambda$test$2(AsyncSocket_ReadableTest.java:90)
	at com.hazelcast.internal.tpc.TpcTestSupport.assertTrueEventually(TpcTestSupport.java:156)
	at com.hazelcast.internal.tpc.TpcTestSupport.assertTrueEventually(TpcTestSupport.java:144)
	at com.hazelcast.internal.tpc.AsyncSocket_ReadableTest.test(AsyncSocket_ReadableTest.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:107)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:83)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)

```
</details>


<details><summary>Standard output:</summary>

```
Mar 10, 2023 10:12:11 PM com.hazelcast.internal.tpc.logging.JulLoggerFactory$JulLogger info
INFO: Thread-54 Binding to /127.0.0.1:5000
Mar 10, 2023 10:12:11 PM com.hazelcast.internal.tpc.logging.JulLoggerFactory$JulLogger info
INFO: /127.0.0.1:5000 started accepting
Mar 10, 2023 10:12:11 PM com.hazelcast.internal.tpc.logging.JulLoggerFactory$JulLogger info
INFO: Connecting to address:/127.0.0.1:5000
Mar 10, 2023 10:12:11 PM com.hazelcast.internal.tpc.logging.JulLoggerFactory$JulLogger info
INFO: NioAsyncServerSocket[/127.0.0.1:5000] accepted: /127.0.0.1:40580->/127.0.0.1:5000
Mar 10, 2023 10:12:11 PM com.hazelcast.internal.tpc.logging.JulLoggerFactory$JulLogger info
INFO: Connection established NioAsyncSocket[/127.0.0.1:40580->/127.0.0.1:5000]
Mar 10, 2023 10:12:11 PM com.hazelcast.internal.tpc.logging.JulLoggerFactory$JulLogger info
INFO: Connection established NioAsyncSocket[/127.0.0.1:40580->/127.0.0.1:5000]
Mar 10, 2023 10:12:11 PM com.hazelcast.internal.tpc.logging.JulLoggerFactory$JulLogger warning
WARNING: Closing  NioAsyncSocket[/127.0.0.1:40580->/127.0.0.1:5000]
java.lang.NullPointerException
	at com.hazelcast.internal.tpc.nio.NioAsyncSocket$Handler.handleConnect(NioAsyncSocket.java:456)
	at com.hazelcast.internal.tpc.nio.NioAsyncSocket$Handler.handle(NioAsyncSocket.java:390)
	at com.hazelcast.internal.tpc.nio.NioEventloop.run(NioEventloop.java:86)
	at com.hazelcast.internal.tpc.Reactor$StartEventloopTask.run(Reactor.java:381)
	at java.lang.Thread.run(Thread.java:825)

Mar 10, 2023 10:12:11 PM com.hazelcast.internal.tpc.logging.JulLoggerFactory$JulLogger warning
WARNING: java.nio.channels.ClosedChannelException
java.nio.channels.ClosedChannelException
	at sun.nio.ch.SocketChannelImpl.ensureWriteOpen(SocketChannelImpl.java:284)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:475)
	at com.hazelcast.internal.tpc.nio.NioAsyncSocket$Handler.handleWrite(NioAsyncSocket.java:420)
	at com.hazelcast.internal.tpc.nio.NioAsyncSocket$Handler.run(NioAsyncSocket.java:355)
	at com.hazelcast.internal.tpc.Eventloop.runExternalTasks(Eventloop.java:167)
	at com.hazelcast.internal.tpc.nio.NioEventloop.run(NioEventloop.java:93)
	at com.hazelcast.internal.tpc.Reactor$StartEventloopTask.run(Reactor.java:381)
	at java.lang.Thread.run(Thread.java:825)

Mar 10, 2023 10:12:13 PM com.hazelcast.internal.tpc.logging.JulLoggerFactory$JulLogger info
INFO: Closing NioAsyncSocket[/127.0.0.1:5000->/127.0.0.1:40580] due to Remote socket closed!
Mar 10, 2023 10:14:13 PM com.hazelcast.internal.tpc.logging.JulLoggerFactory$JulLogger info
INFO: Closing NioAsyncServerSocket[/127.0.0.1:5000] due to Reactor-1 is terminating.
Mar 10, 2023 10:14:13 PM com.hazelcast.internal.tpc.logging.JulLoggerFactory$JulLogger info
INFO: Thread-53 terminated
Mar 10, 2023 10:14:13 PM com.hazelcast.internal.tpc.logging.JulLoggerFactory$JulLogger info
INFO: Thread-54 terminated

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-IbmJDK8/226/

**Comment by olukas** [comment]
Failed again on _master_ with ibm-8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-IbmJDK8-fips/72/testReport/com.hazelcast.internal.tpcengine.nio/NioAsyncSocket_ReadableTest/test/

**Comment by Patras3** [comment]
Failed again on _master_ with ibm-8: https://jenkins.hazelcast.com/job/Hazelcast-master-IbmJDK8/228/testReport/com.hazelcast.internal.tpcengine.nio/NioAsyncSocket_ReadableTest/test/

**Comment by arodionov** [comment]
Failed on ibm-8 https://jenkins.hazelcast.com/job/Hazelcast-pr-builder-with-ibm-jdk-8/13/testReport/junit/com.hazelcast.internal.tpcengine.nio/NioAsyncSocket_ReadableTest/test/

**Comment by olukas** [comment]
Failed again on _master_ with ibm-8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-IbmJDK8/230/testReport/com.hazelcast.internal.tpcengine.nio/NioAsyncSocket_ReadableTest/test/

**Comment by olukas** [comment]
Failed again on _master_ with ibm-8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-IbmJDK8/231/testReport/com.hazelcast.internal.tpcengine.nio/NioAsyncSocket_ReadableTest/test/

**Comment by olukas** [comment]
Failed again on _master_ with ibm-8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-IbmJDK8/232/testReport/com.hazelcast.internal.tpcengine.nio/NioAsyncSocket_ReadableTest/test/

**Comment by olukas** [comment]
Closing the test failure - it doesn't seem to be related to `master` or the latest maintenance stream `5.5.z` and it hasn't fail in the last 3 months. Feel free to reopen test failure if it occurs on `master` or on the latest maintenance stream.
