### ISSUE TITLE
com.hazelcast.HazelcastCompletableFutureAsyncUsageTest.noClassUsesCompletableFuture

### ISSUE THREAD

**Issue by Patras3** [hazelcast/hazelcast#23866]
_master_ (commit 3494b1c8024518584b41bfaee51e5ab66f4df033)

Failed on redhat-17: https://jenkins.hazelcast.com/job/Hazelcast-master-RedHatJDK17/55/testReport/junit/com.hazelcast/HazelcastCompletableFutureAsyncUsageTest/noClassUsesCompletableFuture/
<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: 
Architecture Violation [Priority: MEDIUM] - Rule 'classes should use only CompletableFuture async methods with explicit executor service' was violated (6 times):
com.hazelcast.client.impl.spi.impl.listener.ClientListenerServiceImpl.deregisterListenerInternal(java.util.UUID):338 calls CompletableFuture.exceptionally
com.hazelcast.cp.internal.RaftInvocationManager.invokeGetMembersToCreateRaftGroup(java.lang.String, int, com.hazelcast.spi.impl.InternalCompletableFuture):143 calls CompletableFuture.exceptionally
com.hazelcast.cp.internal.session.AbstractProxySessionManager$HeartbeatTask.run():319 calls CompletableFuture.exceptionally
com.hazelcast.internal.serialization.impl.compact.schema.SchemaReplicator.doReplicate(com.hazelcast.internal.serialization.impl.compact.Schema, com.hazelcast.spi.impl.InternalCompletableFuture):285 calls CompletableFuture.exceptionally
com.hazelcast.internal.serialization.impl.compact.schema.SchemaReplicator.doReplicatePreparedSchema(com.hazelcast.internal.serialization.impl.compact.Schema, com.hazelcast.spi.impl.InternalCompletableFuture):306 calls CompletableFuture.exceptionally
com.hazelcast.spi.impl.AbstractInvocationFuture$AbstractBiNode.execute(java.util.concurrent.Executor, java.lang.Object):1726 calls CompletableFuture.exceptionally
	at com.tngtech.archunit.lang.ArchRule$Assertions.assertNoViolation(ArchRule.java:94)
	at com.tngtech.archunit.lang.ArchRule$Assertions.check(ArchRule.java:86)
	at com.tngtech.archunit.lang.ArchRule$Factory$SimpleArchRule.check(ArchRule.java:165)
	at com.tngtech.archunit.lang.syntax.ObjectsShouldInternal.check(ObjectsShouldInternal.java:81)
	at com.hazelcast.HazelcastCompletableFutureAsyncUsageTest.noClassUsesCompletableFuture(HazelcastCompletableFutureAsyncUsageTest.java:40)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:107)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:83)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)

```
</details>

<details><summary>Standard output:</summary>

```
Started Running Test: testSerializableSingleton_naturalOrder
Started Running Test: when_nullsFirstComparator
Started Running Test: testSerializable_comparing_keyExtractor_keyComparator
Started Running Test: when_nullsLastComparator
Started Running Test: testSerializable_comparing_keyExtractor
Started Running Test: testSerializable_nullsLast
Started Running Test: testSerializable_thenComparing_keyExtractor
Started Running Test: testSerializable_reverseOrder

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-RedHatJDK17/55/

**Comment by Patras3** [comment]
Failed again on _master_ with openjdk-17: https://jenkins.hazelcast.com/job/Hazelcast-master-ZuluJDK17/75/testReport/junit/com.hazelcast/HazelcastCompletableFutureAsyncUsageTest/noClassUsesCompletableFuture/
