### ISSUE TITLE
com.hazelcast.internal.tpc.nio.NioAsyncSocket_LargePayloadTest

### ISSUE THREAD

**Issue by Patras3** [hazelcast/hazelcast#23867]
_master_ (commit 3494b1c8024518584b41bfaee51e5ab66f4df033)

Failed on Windows - OracleJDK8: https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-OracleJDK8/437/testReport/com.hazelcast.internal.tpc.nio/NioAsyncSocket_LargePayloadTest/

In four tests with the same error:
* [test_concurrency_10_payload_16KB](https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-OracleJDK8/437/testReport/com.hazelcast.internal.tpc.nio/NioAsyncSocket_LargePayloadTest/test_concurrency_10_payload_16KB/) 
* [test_concurrency_10_payload_2MB](https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-OracleJDK8/437/testReport/com.hazelcast.internal.tpc.nio/NioAsyncSocket_LargePayloadTest/test_concurrency_10_payload_2MB/)
* [test_concurrency_10_payload_32KB](https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-OracleJDK8/437/testReport/com.hazelcast.internal.tpc.nio/NioAsyncSocket_LargePayloadTest/test_concurrency_10_payload_32KB/)
* [test_concurrency_10_payload_64KB](https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-OracleJDK8/437/testReport/com.hazelcast.internal.tpc.nio/NioAsyncSocket_LargePayloadTest/test_concurrency_10_payload_64KB/)

Details for: `test_concurrency_10_payload_16KB`
<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at com.hazelcast.internal.tpc.TpcTestSupport.lambda$assertOpenEventually$1(TpcTestSupport.java:126)
	at com.hazelcast.internal.tpc.TpcTestSupport.assertTrueEventually(TpcTestSupport.java:156)
	at com.hazelcast.internal.tpc.TpcTestSupport.assertTrueEventually(TpcTestSupport.java:185)
	at com.hazelcast.internal.tpc.TpcTestSupport.assertOpenEventually(TpcTestSupport.java:124)
	at com.hazelcast.internal.tpc.TpcTestSupport.assertOpenEventually(TpcTestSupport.java:120)
	at com.hazelcast.internal.tpc.AsyncSocket_LargePayloadTest.test(AsyncSocket_LargePayloadTest.java:217)
	at com.hazelcast.internal.tpc.AsyncSocket_LargePayloadTest.test_concurrency_10_payload_16KB(AsyncSocket_LargePayloadTest.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:107)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:83)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)

```
</details>

<details><summary>Standard output:</summary>

```
Starting
client round:0
client round:0
client round:0
client round:0
client round:0

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-Windows-OracleJDK8/437/

**Comment by pveentjer** [comment]
@Patras3 I do not see any files I can download.

**Comment by Patras3** [comment]
Apologize @pveentjer - you are right. 
Unfortunately, because the build was finished with a timeout, nothing was pushed to S3 bucket.

**Comment by Patras3** [comment]
Failed again on _master_ with Windows - MicrosoftJDK11: https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK11/56/testReport/com.hazelcast.internal.tpc.nio/NioAsyncSocket_LargePayloadTest/ in all tests - unfortunately, again no details except in Jenkins error details - due to timeout.

**Comment by olukas** [comment]
Failed again on _master_ with MacOS: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-MacOS-ZuluJDK8/189/testReport/com.hazelcast.internal.tpcengine.nio/NioAsyncSocket_LargePayloadTest/

Following tests failed:
- `test_concurrency_10_payload_128KB`
- `test_concurrency_10_payload_16KB`
- `test_concurrency_10_payload_256KB`
- `test_concurrency_10_payload_2MB`
- `test_concurrency_10_payload_32KB`
- `test_concurrency_10_payload_512KB`
- `test_concurrency_10_payload_64KB`

@pveentjer logs are available here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-MacOS-ZuluJDK8/189/

**Comment by olukas** [comment]
Failed again on _master_ with Windows - MicrosoftJDK11: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Windows-MicrosoftJDK11/58/testReport/com.hazelcast.internal.tpcengine.nio/NioAsyncSocket_LargePayloadTest/

**Comment by Patras3** [comment]
Failed again on _master_ with MacOS: https://jenkins.hazelcast.com/job/Hazelcast-master-MacOS-ZuluJDK8/190/testReport/com.hazelcast.internal.tpcengine.nio/NioAsyncSocket_LargePayloadTest/

**Comment by arodionov** [comment]
Failed on ibm-jdk-8 https://jenkins.hazelcast.com/job/Hazelcast-pr-builder-with-ibm-jdk-8/13/#showFailuresLink

**Comment by olukas** [comment]
Failed again on _master_ with MacOS: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-MacOS-ZuluJDK8/195/testReport/com.hazelcast.internal.tpcengine.nio/NioAsyncSocket_LargePayloadTest/test_concurrency_10_payload_1MB/

**Comment by olukas** [comment]
Failed again on _master_ with MacOS with ZuluJDK8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-MacOS-ZuluJDK8/197/testReport/com.hazelcast.internal.tpcengine.nio/NioAsyncSocket_LargePayloadTest/

**Comment by olukas** [comment]
Failed again on _master_ with ibm-8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-IbmJDK8/232/testReport/com.hazelcast.internal.tpcengine.nio/NioAsyncSocket_LargePayloadTest/

**Comment by ramizdundar** [comment]
Closed by:

- https://github.com/hazelcast/hazelcast/pull/24267
- https://github.com/hazelcast/hazelcast/pull/24319
