### ISSUE TITLE
error while migration from 3.12.6 to 4.0.3

### ISSUE THREAD

**Issue by pawar-kapil** [hazelcast/hazelcast#23870]
**Describe the bug**
This is the error that we are facing while creating a node. 
```
20:26:10.930 [main] ERROR com.hazelcast.instance.impl.Node - [192.168.29.196]:5701 [dev] [4.0.3] Node creation failed
hazelcast-hazelcast_main-1     | java.lang.NoSuchMethodError: 'void com.hazelcast.internal.serialization.impl.ArrayDataSerializableFactory.<init>(com.hazelcast.util.ConstructorFunction[])'
hazelcast-hazelcast_main-1     | 	at com.hazelcast.mapreduce.impl.MapReduceDataSerializerHook.createFactory(MapReduceDataSerializerHook.java:234)
hazelcast-hazelcast_main-1     | 	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.<init>(DataSerializableSerializer.java:68)
hazelcast-hazelcast_main-1     | 	at com.hazelcast.internal.serialization.impl.SerializationServiceV1.<init>(SerializationServiceV1.java:120)
hazelcast-hazelcast_main-1     | 	at com.hazelcast.internal.serialization.impl.SerializationServiceV1$Builder.build(SerializationServiceV1.java:375)
hazelcast-hazelcast_main-1     | 	at com.hazelcast.internal.serialization.impl.DefaultSerializationServiceBuilder.createSerializationService(DefaultSerializationServiceBuilder.java:299)
hazelcast-hazelcast_main-1     | 	at com.hazelcast.internal.serialization.impl.DefaultSerializationServiceBuilder.build(DefaultSerializationServiceBuilder.java:236)
hazelcast-hazelcast_main-1     | 	at com.hazelcast.internal.serialization.impl.DefaultSerializationServiceBuilder.build(DefaultSerializationServiceBuilder.java:55)
hazelcast-hazelcast_main-1     | 	at com.hazelcast.instance.impl.DefaultNodeExtension.createSerializationService(DefaultNodeExtension.java:252)
hazelcast-hazelcast_main-1     | 	at com.hazelcast.instance.impl.Node.<init>(Node.java:252)
hazelcast-hazelcast_main-1     | 	at com.hazelcast.instance.impl.HazelcastInstanceImpl.createNode(HazelcastInstanceImpl.java:147)
hazelcast-hazelcast_main-1     | 	at com.hazelcast.instance.impl.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:116)
hazelcast-hazelcast_main-1     | 	at com.hazelcast.instance.impl.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:211)
hazelcast-hazelcast_main-1     | 	at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:190)
hazelcast-hazelcast_main-1     | 	at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:128)
hazelcast-hazelcast_main-1     | 	at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:91)
hazelcast-hazelcast_main-1     | 	at com.hazelcast.core.server.HazelcastMemberStarter.main(HazelcastMemberStarter.java:46)
```
we have checked and cleared the classpath as well there's no dependency on 3.12.6 anymore. From where it is trying to access `MapReduceDataSerializerHook` which was present in 3.12.6 but is no longer there in 4.0.3?

**Expected behavior**
node creation should be successful.

**Comment by pveentjer** [comment]
Map reduce functionality has been deprecated and removed. So that would explain your problem.
