### ISSUE TITLE
ExtractFunctionIntegrationTest fails

### ISSUE THREAD

**Issue by pveentjer** [hazelcast/hazelcast#23923]
This test run into the following problem when running from master.

```
OpenJDK 64-Bit Server VM warning: Ignoring option --illegal-access=deny; support was removed in 17.0
OpenJDK 64-Bit Server VM warning: Ignoring option --illegal-access=deny; support was removed in 17.0
WARNING: package com.ibm.lang.management.internal not in jdk.management
Started Running Test: test_equality
BuildInfo right after test_equality(com.hazelcast.jet.sql.impl.expression.datetime.ExtractFunctionIntegrationTest$NormalTests): BuildInfo{version='5.3.0-SNAPSHOT', build='20230310', buildNumber=20230310, revision=e5babc7, enterprise=false, serializationVersion=1}

No metrics recorded during the test

java.lang.ClassCastException: class com.hazelcast.internal.server.tcp.TcpServerConnectionManager cannot be cast to class com.hazelcast.internal.server.FirewallingServer$FirewallingServerConnectionManager (com.hazelcast.internal.server.tcp.TcpServerConnectionManager and com.hazelcast.internal.server.FirewallingServer$FirewallingServerConnectionManager are in unnamed module of loader 'app')

	at com.hazelcast.test.PacketFiltersUtil.getConnectionManager(PacketFiltersUtil.java:48)
	at com.hazelcast.test.PacketFiltersUtil.resetPacketFiltersFrom(PacketFiltersUtil.java:52)
	at com.hazelcast.jet.SimpleTestInClusterSupport.supportAfter(SimpleTestInClusterSupport.java:104)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunAfters.invokeMethod(RunAfters.java:46)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37)
	at com.hazelcast.test.metrics.MetricsRule$1.evaluate(MetricsRule.java:63)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:50)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:29)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:41)
	at com.hazelcast.test.OverridePropertyRule$1.evaluate(OverridePropertyRule.java:66)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

Also one of my PR's is failing because of this failure
https://jenkins.hazelcast.com/job/Hazelcast-pr-builder/17012/

The weird thing is that it doesn't fail on every machine. There are also engineers (Linux/OSX) where the test runs fine.

**Comment by pveentjer** [comment]
Apparently there was a problem in the past:

https://github.com/hazelcast/hazelcast/issues/20572

**Comment by aditya-32** [comment]
i'm facing this issue when the profile used is `pr builder`

**Comment by mojunneng** [comment]
I am also facing the same issue when I try to run testcase on Idea
