### ISSUE TITLE
NPE at AddressCodec.encode(AddressCodec.java:39) when running on K8S

### ISSUE THREAD

**Issue by florekkkk** [hazelcast/hazelcast#23922]
We're trying to achieve a setup where some HZ mbembers are in K8S, and some are located outside of the K8S cluster on bare metal machines. We're using HZ 4.2.7 (doing an experiment with latest 5.x version in parallel).
We're now at the stage, where cluster is formed between bare metal and K8S HZ members - however we can see some exceptions in the K8S node. 
Now, when HZ client on K8S connects to HZ member on the same K8S, the client throws simillar exception.

So the node throws NPE when forming a cluster with other members.
```
java.lang.NullPointerException: null
        at com.hazelcast.client.impl.protocol.codec.custom.AddressCodec.encode(AddressCodec.java:39) ~[hazelcast-all-4.2.7.jar:4.2.7]
        at com.hazelcast.client.impl.protocol.codec.custom.MemberInfoCodec.encode(MemberInfoCodec.java:44) ~[hazelcast-all-4.2.7.jar:4.2.7]
        at com.hazelcast.client.impl.protocol.codec.builtin.ListMultiFrameCodec.encode(ListMultiFrameCodec.java:42) ~[hazelcast-all-4.2.7.jar:4.2.7]
        at com.hazelcast.client.impl.protocol.codec.ClientAddClusterViewListenerCodec.encodeMembersViewEvent(ClientAddClusterViewListenerCodec.java:91) ~[hazelcast-all-4.2.7.jar:4.2.7]
        at com.hazelcast.client.impl.ClusterViewListenerService.getMemberListViewMessage(ClusterViewListenerService.java:172) ~[hazelcast-all-4.2.7.jar:4.2.7]
        at com.hazelcast.client.impl.ClusterViewListenerService.onMemberListChange(ClusterViewListenerService.java:100) ~[hazelcast-all-4.2.7.jar:4.2.7]
        at com.hazelcast.instance.impl.DefaultNodeExtension.onMemberListChange(DefaultNodeExtension.java:447) ~[hazelcast-all-4.2.7.jar:4.2.7]
        at com.hazelcast.internal.cluster.impl.MembershipManager.sendMembershipEvents(MembershipManager.java:792) ~[hazelcast-all-4.2.7.jar:4.2.7]
        at com.hazelcast.internal.cluster.impl.MembershipManager.updateMembers(MembershipManager.java:361) ~[hazelcast-all-4.2.7.jar:4.2.7]
        at com.hazelcast.internal.cluster.impl.ClusterServiceImpl.finalizeJoin(ClusterServiceImpl.java:401) ~[hazelcast-all-4.2.7.jar:4.2.7]
        at com.hazelcast.internal.cluster.impl.operations.FinalizeJoinOp.run(FinalizeJoinOp.java:90) ~[hazelcast-all-4.2.7.jar:4.2.7]
        at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:189) ~[hazelcast-all-4.2.7.jar:4.2.7]
        at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:272) ~[hazelcast-all-4.2.7.jar:4.2.7]
        at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:248) ~[hazelcast-all-4.2.7.jar:4.2.7]
        at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:469) ~[hazelcast-all-4.2.7.jar:4.2.7]
        at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:197) ~[hazelcast-all-4.2.7.jar:4.2.7]
        at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:137) ~[hazelcast-all-4.2.7.jar:4.2.7]
        at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123) ~[hazelcast-all-4.2.7.jar:4.2.7]
        at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) ~[hazelcast-all-4.2.7.jar:4.2.7]

```

The client throws NPE when connecting to member (note that binaries were altered with printstacktrace...)
```
FINEST: XXX-client [XXX] [4.2.4] Invocation got an exception ClientInvocation{clientMessage = ClientMessage{connection=null, length=22, operation=Client.AddClusterViewListener, isRetryable=false, correlationId=2, messageType=300, isEvent=false, isfragmented=false}, objectName = null, target = connection ClientConnection{alive=true, connectionId=1, channel=NioChannel{/10.233.124.57:53025->/10.233.17.46:5702}, remoteAddress=[10.233.113.123]:5702, lastReadTime=2023-03-10 12:39:55.685, lastWriteTime=2023-03-10 12:39:55.685, closedTime=never, connected server version=4.2.7}, sentConnection = null}, invoke count : 1, exception : class java.lang.NullPointerException, message : null
java.lang.NullPointerException
        at com.hazelcast.client.impl.protocol.codec.custom.AddressCodec.encode(AddressCodec.java:39)
        at com.hazelcast.client.impl.protocol.codec.custom.MemberInfoCodec.encode(MemberInfoCodec.java:44)
        at com.hazelcast.client.impl.protocol.codec.builtin.ListMultiFrameCodec.encode(ListMultiFrameCodec.java:42)
        at com.hazelcast.client.impl.protocol.codec.ClientAddClusterViewListenerCodec.encodeMembersViewEvent(ClientAddClusterViewListenerCodec.java:91)
        at com.hazelcast.client.impl.ClusterViewListenerService.getMemberListViewMessage(ClusterViewListenerService.java:172)
        at com.hazelcast.client.impl.ClusterViewListenerService.registerListener(ClusterViewListenerService.java:130)
        at com.hazelcast.client.impl.protocol.task.AddClusterViewListenerMessageTask.call(AddClusterViewListenerMessageTask.java:44)
        at com.hazelcast.client.impl.protocol.task.AbstractCallableMessageTask.processMessage(AbstractCallableMessageTask.java:35)
        at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:153)
        at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:116)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.lang.Thread.run(Thread.java:829)
        at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
        at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)

```
HZ service is exposed via K8S loadbalancer. Still HZ node start on the K8S internal IP.

Do you have any suggestion of what could be the reason of such behavior?  

[node.log](https://github.com/hazelcast/hazelcast/files/10942404/node.log)
[client.log](https://github.com/hazelcast/hazelcast/files/10942406/client.log)

**Comment by ihsandemir** [comment]
Can it be same root cause as https://github.com/hazelcast/hazelcast/issues/25032?

**Comment by ihsandemir** [comment]
@florekkkk I like to generate your case. I need your server configurations and k8s config if possible. Can you share them? Do you use advance networking config for Hazelcast?
