### ISSUE TITLE
com.hazelcast.jet.sql.impl.SqlDataLinkStatementTest.when_createDataLinkWithoutType_then_throws [HZ-2197]

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hazelcast#23945]
_master_ (commit 2b08d23caa99a542700755b6063007f2fa67bc00)

Failed on Windows - MicrosoftJDK17: https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK17/54/testReport/junit/com.hazelcast.jet.sql.impl/SqlDataLinkStatementTest/when_createDataLinkWithoutType_then_throws/
<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: 

Expecting throwable message:
  "Encountered "<EOF>" at line 1, column 55.
Was expecting one of:
    "TYPE" ...
    "." ...
    "
to contain:
  "Was expecting one of:
    "TYPE" ..."
but did not.

Throwable that failed the check:

com.hazelcast.sql.HazelcastSqlException: Encountered "<EOF>" at line 1, column 55.
Was expecting one of:
    "TYPE" ...
    "." ...
    
	at com.hazelcast.sql.impl.QueryUtils.toPublicException(QueryUtils.java:77)
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:224)
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:175)
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:171)
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:167)
	at com.hazelcast.sql.SqlService.execute(SqlService.java:89)
	at com.hazelcast.jet.sql.impl.SqlDataLinkStatementTest.lambda$when_createDataLinkWithoutType_then_throws$3(SqlDataLinkStatementTest.java:105)
	at org.assertj.core.api.ThrowableAssert.catchThrowable(ThrowableAssert.java:63)
	at org.assertj.core.api.AssertionsForClassTypes.catchThrowable(AssertionsForClassTypes.java:892)
	at org.assertj.core.api.Assertions.catchThrowable(Assertions.java:1366)
	at org.assertj.core.api.Assertions.assertThatThrownBy(Assertions.java:1210)
	at com.hazelcast.jet.sql.impl.SqlDataLinkStatementTest.when_createDataLinkWithoutType_then_throws(SqlDataLinkStatementTest.java:104)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.hazelcast.sql.impl.QueryException: Encountered "<EOF>" at line 1, column 55.
Was expecting one of:
    "TYPE" ...
    "." ...
    
	at com.hazelcast.sql.impl.QueryException.error(QueryException.java:69)
	at com.hazelcast.jet.sql.impl.parse.QueryParser.parse(QueryParser.java:67)
	at com.hazelcast.jet.sql.impl.OptimizerContext.parse(OptimizerContext.java:155)
	at com.hazelcast.jet.sql.impl.CalciteSqlOptimizer.prepare(CalciteSqlOptimizer.java:291)
	at com.hazelcast.sql.impl.SqlServiceImpl.prepare(SqlServiceImpl.java:278)
	at com.hazelcast.sql.impl.SqlServiceImpl.query0(SqlServiceImpl.java:262)
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:207)
	... 22 more
Caused by: org.apache.calcite.sql.parser.SqlParseException: Encountered "<EOF>" at line 1, column 55.
Was expecting one of:
    "TYPE" ...
    "." ...
    
	at com.hazelcast.jet.sql.impl.calcite.parser.HazelcastSqlParser.convertException(HazelcastSqlParser.java:430)
	at com.hazelcast.jet.sql.impl.calcite.parser.HazelcastSqlParser.normalizeException(HazelcastSqlParser.java:183)
	at org.apache.calcite.sql.parser.SqlParser.handleException(SqlParser.java:156)
	at org.apache.calcite.sql.parser.SqlParser.parseStmtList(SqlParser.java:211)
	at com.hazelcast.jet.sql.impl.parse.QueryParser.parse0(QueryParser.java:73)
	at com.hazelcast.jet.sql.impl.parse.QueryParser.parse(QueryParser.java:56)
	... 27 more
Caused by: com.hazelcast.jet.sql.impl.calcite.parser.ParseException: Encountered "<EOF>" at line 1, column 55.
Was expecting one of:
    "TYPE" ...
    "." ...
    
	at com.hazelcast.jet.sql.impl.calcite.parser.HazelcastSqlParser.generateParseException(HazelcastSqlParser.java:42038)
	at com.hazelcast.jet.sql.impl.calcite.parser.HazelcastSqlParser.jj_consume_token(HazelcastSqlParser.java:41849)
	at com.hazelcast.jet.sql.impl.calcite.parser.HazelcastSqlParser.SqlCreateDataLink(HazelcastSqlParser.java:4193)
	at com.hazelcast.jet.sql.impl.calcite.parser.HazelcastSqlParser.SqlCreate(HazelcastSqlParser.java:21743)
	at com.hazelcast.jet.sql.impl.calcite.parser.HazelcastSqlParser.SqlStmt(HazelcastSqlParser.java:3576)
	at com.hazelcast.jet.sql.impl.calcite.parser.HazelcastSqlParser.SqlStmtList(HazelcastSqlParser.java:3036)
	at com.hazelcast.jet.sql.impl.calcite.parser.HazelcastSqlParser.parseSqlStmtList(HazelcastSqlParser.java:239)
	at org.apache.calcite.sql.parser.SqlParser.parseStmtList(SqlParser.java:209)
	... 29 more

	at com.hazelcast.jet.sql.impl.SqlDataLinkStatementTest.when_createDataLinkWithoutType_then_throws(SqlDataLinkStatementTest.java:107)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)

```
</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: when_createDataLinkInWrongNameSpace_then_throws in 0.002 seconds.
Started Running Test: when_createDataLinkWithoutType_then_throws
21:19:49,290 DEBUG || - [JobRepository] hz.SqlDataLinkStatementTest_reverent_villani.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Job cleanup took 0ms
21:19:49,294  INFO |when_createDataLinkWithoutType_then_throws| - [SqlTestSupport] Time-limited test - Removing 0 cached plans in SqlTestSupport.@After
21:19:49,294  INFO |when_createDataLinkWithoutType_then_throws| - [SimpleTestInClusterSupport] Time-limited test - Ditching 0 jobs in SimpleTestInClusterSupport.@After: []
21:19:49,294  INFO |when_createDataLinkWithoutType_then_throws| - [SimpleTestInClusterSupport] Time-limited test - Destroying 1 distributed objects in SimpleTestInClusterSupport.@After: [hz:impl:mapService/__sql.catalog]
BuildInfo right after when_createDataLinkWithoutType_then_throws(com.hazelcast.jet.sql.impl.SqlDataLinkStatementTest): BuildInfo{version='5.3.0-SNAPSHOT', build='20230311', buildNumber=20230311, revision=2b08d23, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'when_createDataLinkWithoutType_then_throws(com.hazelcast.jet.sql.impl.SqlDataLinkStatementTest):'
21:19:45, accumulated pauses: 1629 ms, max pause: 196 ms, pauses over 1000 ms: 0


No metrics recorded during the test

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-Windows-MicrosoftJDK17/54/

**Comment by olukas** [comment]
Test `com.hazelcast.jet.sql.impl.SqlDataLinkStatementTest.when_createDataLinkWithoutOptions_then_throws` failed again on _master_ with Windows - MicrosoftJDK11: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Windows-MicrosoftJDK11/58/testReport/com.hazelcast.jet.sql.impl/SqlDataLinkStatementTest/when_createDataLinkWithoutOptions_then_throws/
