### ISSUE TITLE
Various tests on Windows with ''SO_REUSEPORT' not supported"

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hazelcast#23946]
_master_ (commit 2b08d23caa99a542700755b6063007f2fa67bc00)

Failed on Windows - MicrosoftJDK17: https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK17/54/
<details><summary>Example Stacktrace:</summary>

```
java.lang.UnsupportedOperationException: 'SO_REUSEPORT' not supported
	at java.base/sun.nio.ch.ServerSocketChannelImpl.setOption(ServerSocketChannelImpl.java:212)
	at com.hazelcast.internal.tpc.nio.NioAsyncServerSocketOptions.set(NioAsyncServerSocketOptions.java:70)
	at com.hazelcast.internal.tpc.nio.NioAsyncServerSocketBuilder.set(NioAsyncServerSocketBuilder.java:67)
	at com.hazelcast.internal.tpc.nio.NioAsyncServerSocketBuilder.set(NioAsyncServerSocketBuilder.java:36)
	at com.hazelcast.internal.bootstrap.AltoServerBootstrap.openServerSockets(AltoServerBootstrap.java:203)
	at com.hazelcast.internal.bootstrap.AltoServerBootstrap.start(AltoServerBootstrap.java:183)
	at com.hazelcast.spi.impl.NodeEngineImpl.start(NodeEngineImpl.java:267)
	at com.hazelcast.instance.impl.Node.start(Node.java:483)
	at com.hazelcast.instance.impl.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:124)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:217)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:196)
	at com.hazelcast.test.TestHazelcastInstanceFactory.newHazelcastInstance(TestHazelcastInstanceFactory.java:235)
	at com.hazelcast.test.HazelcastTestSupport.createHazelcastInstance(HazelcastTestSupport.java:254)
	at com.hazelcast.config.alto.AltoConfigTest.testSystemProperties(AltoConfigTest.java:76)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)

```
</details>

<details><summary>Example Standard output:</summary>

```
19:01:20,304  INFO |testSystemProperties| - [MetricsConfigHelper] testSystemProperties - [LOCAL] [dev] [5.3.0-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
19:01:20,305  INFO |testSystemProperties| - [logo] testSystemProperties - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
19:01:20,305  INFO |testSystemProperties| - [system] testSystemProperties - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Copyright (c) 2008-2023, Hazelcast, Inc. All Rights Reserved.
19:01:20,305  INFO |testSystemProperties| - [system] testSystemProperties - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Hazelcast Platform 5.3.0-SNAPSHOT (20230311 - 2b08d23) starting at [127.0.0.1]:5701
19:01:20,305  INFO |testSystemProperties| - [system] testSystemProperties - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Cluster name: dev
19:01:20,305  INFO |testSystemProperties| - [system] testSystemProperties - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed. For more information, see the documentation for Integrity Checker.
19:01:20,305  INFO |testSystemProperties| - [system] testSystemProperties - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Jet is enabled
19:01:20,308  INFO |testSystemProperties| - [MetricsConfigHelper] testSystemProperties - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
19:01:20,309  INFO |testSystemProperties| - [AltoServerBootstrap] testSystemProperties - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Alto: enabled
19:01:20,319  WARN |testSystemProperties| - [CPSubsystem] testSystemProperties - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
19:01:20,322  INFO |testSystemProperties| - [JetServiceBackend] testSystemProperties - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Setting number of cooperative threads and default parallelism to 2
19:01:20,335  INFO |testSystemProperties| - [AltoServerBootstrap] testSystemProperties - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Starting AltoServerBootstrap
19:01:20,335  INFO |testSystemProperties| - [TpcEngine] testSystemProperties - Starting 3 reactors of type [NIO]
19:01:20,336  WARN |testSystemProperties| - [Node] testSystemProperties - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Terminating forcefully...
19:01:20,336  INFO |testSystemProperties| - [Node] testSystemProperties - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Shutting down connection manager...
19:01:20,336  INFO |testSystemProperties| - [Node] testSystemProperties - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Shutting down node engine...
19:01:20,337  INFO |testSystemProperties| - [AltoServerBootstrap] testSystemProperties - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] TcpBootstrap shutdown
19:01:20,338  INFO |testSystemProperties| - [NioReactor] hz.AltoConfigTest_relaxed_mccarthy.partition-operation.thread-0 - hz.AltoConfigTest_relaxed_mccarthy.partition-operation.thread-0 terminated
19:01:20,338  INFO |testSystemProperties| - [NioReactor] hz.AltoConfigTest_relaxed_mccarthy.partition-operation.thread-1 - hz.AltoConfigTest_relaxed_mccarthy.partition-operation.thread-1 terminated
19:01:20,338  INFO |testSystemProperties| - [NioReactor] hz.AltoConfigTest_relaxed_mccarthy.partition-operation.thread-2 - hz.AltoConfigTest_relaxed_mccarthy.partition-operation.thread-2 terminated
19:01:20,338  INFO |testSystemProperties| - [AltoServerBootstrap] testSystemProperties - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] TcpBootstrap terminated
19:01:20,338  INFO |testSystemProperties| - [NodeExtension] testSystemProperties - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Destroying node NodeExtension.
19:01:20,338  INFO |testSystemProperties| - [Node] testSystemProperties - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Hazelcast Shutdown is completed in 2 ms.
BuildInfo right after testSystemProperties(com.hazelcast.config.alto.AltoConfigTest): BuildInfo{version='5.3.0-SNAPSHOT', build='20230311', buildNumber=20230311, revision=2b08d23, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'testSystemProperties(com.hazelcast.config.alto.AltoConfigTest):'
19:01:20, accumulated pauses: 946 ms, max pause: 628 ms, pauses over 1000 ms: 0


No metrics recorded during the test

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-Windows-MicrosoftJDK17/54/

List of affected tests:

[com.hazelcast.internal.networking.nio.AdvancedNetworkIntegrationTest.testTPCPortsWithAdvancedNetwork](https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK17/lastSuccessfulBuild/testReport/junit/com.hazelcast.internal.networking.nio/AdvancedNetworkIntegrationTest/testTPCPortsWithAdvancedNetwork/)
[com.hazelcast.internal.tpc.nio.NioAsyncServerSocketConfigTest.test_SO_REUSE_PORT](https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK17/lastSuccessfulBuild/testReport/junit/com.hazelcast.internal.tpc.nio/NioAsyncServerSocketConfigTest/test_SO_REUSE_PORT/)
[com.hazelcast.internal.tpc.nio.NioAsyncServerSocketTest.test_createCloseLoop_withNewReactor](https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK17/lastSuccessfulBuild/testReport/junit/com.hazelcast.internal.tpc.nio/NioAsyncServerSocketTest/test_createCloseLoop_withNewReactor/)
[com.hazelcast.internal.tpc.nio.NioAsyncServerSocketTest.test_createCloseLoop_withSameReactor](https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK17/lastSuccessfulBuild/testReport/junit/com.hazelcast.internal.tpc.nio/NioAsyncServerSocketTest/test_createCloseLoop_withSameReactor/)
[com.hazelcast.internal.tpc.nio.NioAsyncSocketOptionsTest.test_TCP_KEEPIDLE](https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK17/lastSuccessfulBuild/testReport/junit/com.hazelcast.internal.tpc.nio/NioAsyncSocketOptionsTest/test_TCP_KEEPIDLE/)
[com.hazelcast.internal.tpc.nio.NioAsyncSocketOptionsTest.test_TCP_KEEPINTERVAL](https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK17/lastSuccessfulBuild/testReport/junit/com.hazelcast.internal.tpc.nio/NioAsyncSocketOptionsTest/test_TCP_KEEPINTERVAL/)
[com.hazelcast.internal.tpc.nio.NioAsyncSocketOptionsTest.test_TCP_KEEPCOUNT](https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK17/lastSuccessfulBuild/testReport/junit/com.hazelcast.internal.tpc.nio/NioAsyncSocketOptionsTest/test_TCP_KEEPCOUNT/)
[com.hazelcast.internal.tpc.nio.NioReactorTest.test_shutdown_thenAsyncServerSocketsClosed](https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK17/lastSuccessfulBuild/testReport/junit/com.hazelcast.internal.tpc.nio/NioReactorTest/test_shutdown_thenAsyncServerSocketsClosed/)
[com.hazelcast.internal.tpc.nio.NioReactorTest.test_shutdown_thenAsyncSocketClosed](https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK17/lastSuccessfulBuild/testReport/junit/com.hazelcast.internal.tpc.nio/NioReactorTest/test_shutdown_thenAsyncSocketClosed/)
[com.hazelcast.config.alto.AltoConfigTest.testSystemProperties](https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK17/lastSuccessfulBuild/testReport/junit/com.hazelcast.config.alto/AltoConfigTest/testSystemProperties/)
[com.hazelcast.config.alto.AltoConfigTest.testEventloopCountDefault](https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK17/lastSuccessfulBuild/testReport/junit/com.hazelcast.config.alto/AltoConfigTest/testEventloopCountDefault/)
[com.hazelcast.config.alto.AltoConfigTest.testConfigProperties](https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK17/lastSuccessfulBuild/testReport/junit/com.hazelcast.config.alto/AltoConfigTest/testConfigProperties/)
[com.hazelcast.config.alto.AltoConfigTest.testEventloopCount](https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK17/lastSuccessfulBuild/testReport/junit/com.hazelcast.config.alto/AltoConfigTest/testEventloopCount/)
[com.hazelcast.config.alto.AltoSocketConfigTest.testCreatingHazelcastInstanceThrows_whenPortRangeMatchesButDecreasing](https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK17/lastSuccessfulBuild/testReport/junit/com.hazelcast.config.alto/AltoSocketConfigTest/testCreatingHazelcastInstanceThrows_whenPortRangeMatchesButDecreasing/)
[com.hazelcast.config.alto.AltoSocketConfigTest.testClientPortsWith3Members](https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK17/lastSuccessfulBuild/testReport/junit/com.hazelcast.config.alto/AltoSocketConfigTest/testClientPortsWith3Members/)
[com.hazelcast.config.alto.AltoSocketConfigTest.testClientPortsNotEnough](https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK17/lastSuccessfulBuild/testReport/junit/com.hazelcast.config.alto/AltoSocketConfigTest/testClientPortsNotEnough/)
[com.hazelcast.config.alto.AltoSocketConfigTest.testReceiveSize](https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK17/lastSuccessfulBuild/testReport/junit/com.hazelcast.config.alto/AltoSocketConfigTest/testReceiveSize/)
[com.hazelcast.config.alto.AltoSocketConfigTest.testClientPortDefaults](https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK17/lastSuccessfulBuild/testReport/junit/com.hazelcast.config.alto/AltoSocketConfigTest/testClientPortDefaults/)
[com.hazelcast.config.alto.AltoSocketConfigTest.testSendSize](https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK17/lastSuccessfulBuild/testReport/junit/com.hazelcast.config.alto/AltoSocketConfigTest/testSendSize/)
[com.hazelcast.config.alto.AltoSocketConfigTest.testClientPorts](https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK17/lastSuccessfulBuild/testReport/junit/com.hazelcast.config.alto/AltoSocketConfigTest/testClientPorts/)

**Comment by pveentjer** [comment]
The following PR should get rid of most of these failures:

https://github.com/hazelcast/hazelcast/pull/23924

**Comment by zpqrtbnk** [comment]
Update: this issue prevented me from running an hazelcast cluster entirely on some Windows machine. I can confirm that removing the line as per #23951 is also the fixed I had to apply to fix the issue and get the cluster to start running.

**Comment by vbekiaris** [comment]
Fixed by #23924 - these tests did not fail in the [subsequent Windows build](https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK17/55/#showFailuresLink)
