### ISSUE TITLE
com.hazelcast.jet.sql.impl.connector.mongodb.MongoStreamSqlConnectorTest.readsFromMongo_withoutId_twoSteps

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#24005]
Failed on pr-builder (oracle-11): https://jenkins.hazelcast.com/job/Hazelcast-pr-builder/17222/testReport/junit/com.hazelcast.jet.sql.impl.connector.mongodb/MongoStreamSqlConnectorTest/readsFromMongo_withoutId_twoSteps/
<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: 

Expecting actual:
  [Row{[Anakin, Skywalker, insert]}]
to contain exactly in any order:
  [Row{[Luke, Skywalker, insert]}, Row{[Anakin, Skywalker, insert]}]
but could not find the following elements:
  [Row{[Luke, Skywalker, insert]}]

	at com.hazelcast.jet.sql.SqlTestSupport.assertRowsEventuallyInAnyOrder(SqlTestSupport.java:289)
	at com.hazelcast.jet.sql.impl.connector.mongodb.MongoStreamSqlConnectorTest.readsFromMongo(MongoStreamSqlConnectorTest.java:109)
	at com.hazelcast.jet.sql.impl.connector.mongodb.MongoStreamSqlConnectorTest.readsFromMongo_withoutId_twoSteps(MongoStreamSqlConnectorTest.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:750)

```
</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: readsFromMongo_withId_oneStep in 2.736 seconds.
Started Running Test: readsFromMongo_withoutId_twoSteps
09:01:31,980 DEBUG |readsFromMongo_withoutId_twoSteps| - [CalciteSqlOptimizer] Thread-17 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Before logical opt:
LogicalCalc(expr#0..4=[{inputs}], expr#5=[?0], expr#6=[=($t2, $t5)], expr#7=[CAST($t3):VARCHAR CHARACTER SET "UTF-16LE"], expr#8=[_UTF-16LE'true':VARCHAR CHARACTER SET "UTF-16LE"], expr#9=[=($t7, $t8)], expr#10=[AND($t6, $t3, $t9)], firstName=[$t1], lastName=[$t2], operation=[$t4], $condition=[$t10])
  LogicalTableScan(table=[[hazelcast, public, readsFromMongo_withoutId_twoSteps[projects=[$0, $1, $2, $3, $4]]]])

09:01:31,988 DEBUG |readsFromMongo_withoutId_twoSteps| - [CalciteSqlOptimizer] Thread-17 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] After logical opt:
FullScanLogicalRel(table=[[hazelcast, public, readsFromMongo_withoutId_twoSteps[projects=[$1, $2, $4], filter=AND(=($2, ?0), $3, =(CAST($3):VARCHAR CHARACTER SET "UTF-16LE", _UTF-16LE'true'))]]])

09:01:32,003 DEBUG |readsFromMongo_withoutId_twoSteps| - [CalciteSqlOptimizer] Thread-17 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] After physical opt:
FullScanPhysicalRel(table=[[hazelcast, public, readsFromMongo_withoutId_twoSteps[projects=[$1, $2, $4], filter=AND(=($2, ?0), $3, =(CAST($3):VARCHAR CHARACTER SET "UTF-16LE", _UTF-16LE'true'))]]], discriminator=[0])

09:01:32,077 DEBUG |readsFromMongo_withoutId_twoSteps| - [LightMasterContext] Thread-17 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Start executing light job 098e-a8a3-f781-0001, execution graph in DOT format:
digraph DAG {
	"Select (readsFromMongo_withoutId_twoSteps)" [localParallelism=2];
	"ProjectAndFilter(MongoTable{databaseName='sqlConnectorTest', collectionName='readsFromMongo_withoutId_twoSteps', connectionString='mongodb://172.17.0.1:51403', options={connectionString=mongodb://172.17.0.1:51403, database=sqlConnectorTest, collection=readsFromMongo_withoutId_twoSteps, startAt=now}, streaming=true})" [localParallelism=2];
	"ClientSink" [localParallelism=1];
	"Select (readsFromMongo_withoutId_twoSteps)" -> "ProjectAndFilter(MongoTable{databaseName='sqlConnectorTest', collectionName='readsFromMongo_withoutId_twoSteps', connectionString='mongodb://172.17.0.1:51403', options={connectionString=mongodb://172.17.0.1:51403, database=sqlConnectorTest, collection=readsFromMongo_withoutId_twoSteps, startAt=now}, streaming=true})" [label="isolated", queueSize=1024];
	"ProjectAndFilter(MongoTable{databaseName='sqlConnectorTest', collectionName='readsFromMongo_withoutId_twoSteps', connectionString='mongodb://172.17.0.1:51403', options={connectionString=mongodb://172.17.0.1:51403, database=sqlConnectorTest, collection=readsFromMongo_withoutId_twoSteps, startAt=now}, streaming=true})" -> "ClientSink" [label="distributed to [127.0.0.1]:5701-partitioned", queueSize=1024];
}
HINT: You can use graphviz or http://viz-js.com to visualize the printed graph.
09:01:32,077 DEBUG |readsFromMongo_withoutId_twoSteps| - [LightMasterContext] Thread-17 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Building execution plan for 098e-a8a3-f781-0001
09:01:32,077 DEBUG || - [LightMasterContext] hz.MongoStreamSqlConnectorTest_hardcore_benz.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Built execution plans for 098e-a8a3-f781-0001
09:01:32,086 DEBUG || - [InitExecutionOperation] hz.MongoStreamSqlConnectorTest_hardcore_benz.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Initializing execution plan for job 098e-a8a3-f781-0001, execution 098e-a8a3-f781-0001 from [127.0.0.1]:5701
09:01:32,098 DEBUG || - [JobExecutionService] hz.MongoStreamSqlConnectorTest_hardcore_benz.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Execution plan for light job ID=098e-a8a3-f781-0001, jobName='098e-a8a3-f781-0001', executionId=098e-a8a3-f781-0001 initialized, will start the execution
09:01:32,101  INFO || - [ReadMongoP] hz.MongoStreamSqlConnectorTest_hardcore_benz.jet.blocking.thread-0 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] [098e-a8a3-f781-0001/Select (readsFromMongo_withoutId_twoSteps)#1] (Re)connecting to MongoDB
09:01:32,116  INFO || - [ReadMongoP] hz.MongoStreamSqlConnectorTest_hardcore_benz.jet.blocking.thread-1 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] [098e-a8a3-f781-0001/Select (readsFromMongo_withoutId_twoSteps)#0] (Re)connecting to MongoDB
09:01:32,855  WARN || - [ManagementCenterPublisher] hz.MongoStreamSqlConnectorTest_hardcore_benz.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Too long value in the metric descriptor found, maximum is 255: ProjectAndFilter(MongoTable{databaseName='sqlConnectorTest', collectionName='readsFromMongo_withoutId_twoSteps', connectionString='mongodb://172.17.0.1:51403', options={connectionString=mongodb://172.17.0.1:51403, database=sqlConnectorTest, collection=readsFromMongo_withoutId_twoSteps, startAt=now}, streaming=true})
09:01:34,268 DEBUG || - [JobRepository] hz.MongoStreamSqlConnectorTest_hardcore_benz.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Job cleanup took 5ms
09:01:39,263 DEBUG || - [JobRepository] hz.MongoStreamSqlConnectorTest_hardcore_benz.cached.thread-9 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Job cleanup took 0ms
09:01:41,916 DEBUG || - [TaskletExecutionService] hz.MongoStreamSqlConnectorTest_hardcore_benz.jet.cooperative.thread-1 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Job was cancelled by the user.
09:01:42,262  INFO |readsFromMongo_withoutId_twoSteps| - [SqlTestSupport] Time-limited test - Removing 1 cached plans in SqlTestSupport.@After
09:01:42,266  INFO |readsFromMongo_withoutId_twoSteps| - [SimpleTestInClusterSupport] Time-limited test - Ditching 1 jobs in SimpleTestInClusterSupport.@After: [098e-a8a3-f781-0001]
09:01:42,266 DEBUG |readsFromMongo_withoutId_twoSteps| - [AbstractJobProxy] Time-limited test - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Sending CANCEL_FORCEFUL request for job 098e-a8a3-f781-0001 (name ??)
09:01:42,275 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-4 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Completed execution of job '098e-a8a3-f781-0001', execution 098e-a8a3-f781-0001
09:01:42,275 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-4 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Execution of job '098e-a8a3-f781-0001', execution 098e-a8a3-f781-0001 completed with failure
java.util.concurrent.CompletionException: java.util.concurrent.CancellationException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292) ~[?:1.8.0_351]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308) ~[?:1.8.0_351]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:783) ~[?:1.8.0_351]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) ~[?:1.8.0_351]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) ~[?:1.8.0_351]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) ~[?:1.8.0_351]
	at com.hazelcast.jet.impl.util.NonCompletableFuture.internalCompleteExceptionally(NonCompletableFuture.java:72) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$ExecutionTracker.taskletDone(TaskletExecutionService.java:498) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$BlockingWorker.run(TaskletExecutionService.java:330) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_351]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_351]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_351]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_351]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_351]
Caused by: java.util.concurrent.CancellationException
	at com.hazelcast.jet.sql.impl.processors.RootResultConsumerSink.tryProcess(RootResultConsumerSink.java:97) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.lambda$stateMachineStep$2(ProcessorTasklet.java:334) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.jet.impl.util.Util.doWithClassLoader(Util.java:547) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:334) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:328) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:291) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:404) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:895) ~[?:1.8.0_351]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.run(TaskletExecutionService.java:369) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	... 1 more
09:01:42,276  WARN || - [InitExecutionOperation] ForkJoinPool.commonPool-worker-4 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] null
java.util.concurrent.CancellationException: null
	at com.hazelcast.jet.sql.impl.processors.RootResultConsumerSink.tryProcess(RootResultConsumerSink.java:97) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.lambda$stateMachineStep$2(ProcessorTasklet.java:334) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.jet.impl.util.Util.doWithClassLoader(Util.java:547) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:334) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:328) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:291) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:404) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:895) ~[?:1.8.0_351]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.run(TaskletExecutionService.java:369) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_351]
09:01:42,277  WARN || - [JoinSubmittedJobOperation] hz.MongoStreamSqlConnectorTest_hardcore_benz.cached.thread-1 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] null
java.util.concurrent.CancellationException: null
	at com.hazelcast.jet.sql.impl.processors.RootResultConsumerSink.tryProcess(RootResultConsumerSink.java:97) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.lambda$stateMachineStep$2(ProcessorTasklet.java:334) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.jet.impl.util.Util.doWithClassLoader(Util.java:547) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:334) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:328) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:291) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:404) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:895) ~[?:1.8.0_351]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.run(TaskletExecutionService.java:369) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_351]
09:01:42,277  WARN || - [SubmitJobOperation] hz.MongoStreamSqlConnectorTest_hardcore_benz.cached.thread-1 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] null
java.util.concurrent.CancellationException: null
	at com.hazelcast.jet.sql.impl.processors.RootResultConsumerSink.tryProcess(RootResultConsumerSink.java:97) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.lambda$stateMachineStep$2(ProcessorTasklet.java:334) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.jet.impl.util.Util.doWithClassLoader(Util.java:547) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:334) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:328) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:291) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:404) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:895) ~[?:1.8.0_351]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.run(TaskletExecutionService.java:369) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_351]
09:01:42,278  WARN || - [JobCoordinationService] hz.MongoStreamSqlConnectorTest_hardcore_benz.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] null
com.hazelcast.jet.core.JobNotFoundException: Job with id 098e-a8a3-f781-0001 not found
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$callWithJob$49(JobCoordinationService.java:1025) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.jet.impl.JobCoordinationService.submitToCoordinatorThread(JobCoordinationService.java:1439) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.jet.impl.JobCoordinationService.callWithJob(JobCoordinationService.java:977) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$getJobIds$21(JobCoordinationService.java:542) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$58(JobCoordinationService.java:1451) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.internal.util.executor.CompletableFutureTask.run(CompletableFutureTask.java:64) [hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217) [hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_351]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_351]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_351]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76) [hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:111) [hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
09:01:42,278  WARN || - [JobCoordinationService] hz.MongoStreamSqlConnectorTest_hardcore_benz.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] null
com.hazelcast.jet.core.JobNotFoundException: Job with id 098e-a8a3-f781-0001 not found
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$callWithJob$49(JobCoordinationService.java:1025) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.jet.impl.JobCoordinationService.submitToCoordinatorThread(JobCoordinationService.java:1439) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.jet.impl.JobCoordinationService.callWithJob(JobCoordinationService.java:977) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$getJobIds$21(JobCoordinationService.java:542) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$58(JobCoordinationService.java:1451) ~[hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.internal.util.executor.CompletableFutureTask.run(CompletableFutureTask.java:64) [hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217) [hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_351]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_351]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_351]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76) [hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:111) [hazelcast-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
09:01:42,279  INFO |readsFromMongo_withoutId_twoSteps| - [SimpleTestInClusterSupport] Time-limited test - Destroying 1 distributed objects in SimpleTestInClusterSupport.@After: [hz:impl:mapService/__sql.catalog]
BuildInfo right after readsFromMongo_withoutId_twoSteps(com.hazelcast.jet.sql.impl.connector.mongodb.MongoStreamSqlConnectorTest): BuildInfo{version='5.3.0-SNAPSHOT', build='20230316', buildNumber=20230316, revision=a4f86ee, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'readsFromMongo_withoutId_twoSteps(com.hazelcast.jet.sql.impl.connector.mongodb.MongoStreamSqlConnectorTest):'
09:01:30, accumulated pauses: 128 ms, max pause: 12 ms, pauses over 1000 ms: 0
09:01:35, accumulated pauses: 181 ms, max pause: 9 ms, pauses over 1000 ms: 0
09:01:40, accumulated pauses: 370 ms, max pause: 307 ms, pauses over 1000 ms: 0


No metrics recorded during the test

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/17222/

**Comment by TomaszGaweda** [comment]
Should be fixed in 2e48297cf26d9938d0d805f8f6beb12803318a33
