### ISSUE TITLE
com.hazelcast.spi.impl.operationservice.impl.Invocation_ArbitraryArityConstructionTest.testAnyOf_whenSomeTimeout [HZ-2244]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#24049]
_master_ (commit 2e48297cf26d9938d0d805f8f6beb12803318a33)

Failed on microsoft-17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-MicrosoftJDK17/55/testReport/com.hazelcast.spi.impl.operationservice.impl/Invocation_ArbitraryArityConstructionTest/testAnyOf_whenSomeTimeout/
<details><summary>Stacktrace:</summary>

```
junit.framework.AssertionFailedError: 
Unexpected java.util.concurrent.CompletionException exception type thrown with message:
com.hazelcast.core.OperationTimeoutException: DummyOperation got rejected before execution due to not starting within the operation-call-timeout of: 200 ms. Current time: 2023-03-22 03:41:25.288. Start time: 2023-03-22 03:41:24.888. Total elapsed time: 400 ms. Invocation{op=com.hazelcast.spi.impl.operationservice.impl.DummyOperation{serviceName='null', identityHash=1730390951, partitionId=2, replicaIndex=0, callId=11, invocationTime=1679456484888 (2023-03-22 03:41:24.888), waitTimeout=-1, callTimeout=200, tenantControl=com.hazelcast.spi.impl.tenantcontrol.NoopTenantControl@0}, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=200, firstInvocationTimeMs=1679456484888, firstInvocationTime='2023-03-22 03:41:24.888', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 00:00:00.000', targetAddress=[127.0.0.1]:5702, targetMember=Member [127.0.0.1]:5702 - a81f3456-e83a-46a9-9a9f-c7d84ac63fc8, memberListVersion=2, pendingResponse={VOID}, backupsAcksExpected=-1, backupsAcksReceived=0, connection=com.hazelcast.internal.server.FirewallingServer$FirewallingConnection@123f7e2c}
	at com.hazelcast.test.HazelcastTestSupport.assertThrows(HazelcastTestSupport.java:1478)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation_ArbitraryArityConstructionTest.testAnyOf_whenSomeTimeout(Invocation_ArbitraryArityConstructionTest.java:99)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)

```
</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: testAnyOf_whenAllTimeout in 5.727 seconds.
03:41:30,494  INFO |testAnyOf_whenSomeTimeout| - [LifecycleService] Thread-67721 - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] [127.0.0.1]:5702 is SHUTTING_DOWN
03:41:30,494  WARN |testAnyOf_whenSomeTimeout| - [Node] Thread-67721 - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Terminating forcefully...
03:41:30,494  INFO |testAnyOf_whenSomeTimeout| - [Node] Thread-67721 - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Shutting down connection manager...
03:41:30,494  INFO |testAnyOf_whenSomeTimeout| - [MockServer] Thread-67721 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Removed connection to endpoint: [address=[127.0.0.1]:5702, uuid=a81f3456-e83a-46a9-9a9f-c7d84ac63fc8], connection: MockConnection{localEndpoint=[address=[127.0.0.1]:5701, uuid=98b00c9a-2d5b-471a-828b-732f476cd10c], remoteEndpoint=[address=[127.0.0.1]:5702, uuid=a81f3456-e83a-46a9-9a9f-c7d84ac63fc8], alive=false}
03:41:30,494  INFO |testAnyOf_whenSomeTimeout| - [MockServer] Thread-67721 - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Removed connection to endpoint: [address=[127.0.0.1]:5701, uuid=98b00c9a-2d5b-471a-828b-732f476cd10c], connection: MockConnection{localEndpoint=[address=[127.0.0.1]:5702, uuid=a81f3456-e83a-46a9-9a9f-c7d84ac63fc8], remoteEndpoint=[address=[127.0.0.1]:5701, uuid=98b00c9a-2d5b-471a-828b-732f476cd10c], alive=false}
03:41:30,494  INFO |testAnyOf_whenSomeTimeout| - [MembershipManager] Thread-67721 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Removing Member [127.0.0.1]:5702 - a81f3456-e83a-46a9-9a9f-c7d84ac63fc8
03:41:30,494  INFO |testAnyOf_whenSomeTimeout| - [PartitionStateManager] Thread-67721 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Storing snapshot of partition assignments while removing UUID a81f3456-e83a-46a9-9a9f-c7d84ac63fc8
03:41:30,494  INFO |testAnyOf_whenSomeTimeout| - [ClusterService] Thread-67721 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] 

Members {size:1, ver:3} [
	Member [127.0.0.1]:5701 - 98b00c9a-2d5b-471a-828b-732f476cd10c this
]

03:41:30,494  INFO |testAnyOf_whenSomeTimeout| - [Node] Thread-67721 - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Shutting down node engine...
03:41:30,494  INFO |testAnyOf_whenSomeTimeout| - [TransactionManagerService] hz.Invocation_ArbitraryArityConstructionTest_clever_shaw.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Committing/rolling-back live transactions of [127.0.0.1]:5702, UUID: a81f3456-e83a-46a9-9a9f-c7d84ac63fc8
03:41:30,496  INFO |testAnyOf_whenSomeTimeout| - [NodeExtension] Thread-67721 - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Destroying node NodeExtension.
03:41:30,496  INFO |testAnyOf_whenSomeTimeout| - [Node] Thread-67721 - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Hazelcast Shutdown is completed in 2 ms.
03:41:30,496  INFO |testAnyOf_whenSomeTimeout| - [LifecycleService] Thread-67721 - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] [127.0.0.1]:5702 is SHUTDOWN
03:41:30,496  INFO |testAnyOf_whenSomeTimeout| - [LifecycleService] Thread-67721 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
03:41:30,496  WARN |testAnyOf_whenSomeTimeout| - [Node] Thread-67721 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Terminating forcefully...
03:41:30,496  INFO |testAnyOf_whenSomeTimeout| - [Node] Thread-67721 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Shutting down connection manager...
03:41:30,496  INFO |testAnyOf_whenSomeTimeout| - [Node] Thread-67721 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Shutting down node engine...
03:41:30,496  INFO |testAnyOf_whenSomeTimeout| - [MigrationManager] hz.Invocation_ArbitraryArityConstructionTest_clever_shaw.migration - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Partition balance is ok, no need to repartition.
03:41:30,506  INFO |testAnyOf_whenSomeTimeout| - [NodeExtension] Thread-67721 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Destroying node NodeExtension.
03:41:30,506  INFO |testAnyOf_whenSomeTimeout| - [Node] Thread-67721 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Hazelcast Shutdown is completed in 10 ms.
03:41:30,506  INFO |testAnyOf_whenSomeTimeout| - [LifecycleService] Thread-67721 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
BuildInfo right after testAnyOf_whenSomeTimeout(com.hazelcast.spi.impl.operationservice.impl.Invocation_ArbitraryArityConstructionTest): BuildInfo{version='5.3.0-SNAPSHOT', build='20230322', buildNumber=20230322, revision=2e48297, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'testAnyOf_whenSomeTimeout(com.hazelcast.spi.impl.operationservice.impl.Invocation_ArbitraryArityConstructionTest):'
03:41:20, accumulated pauses: 116 ms, max pause: 34 ms, pauses over 1000 ms: 0
03:41:25, accumulated pauses: 5147 ms, max pause: 5144 ms, pauses over 1000 ms: 1
03:41:30, accumulated pauses: 0 ms, max pause: 0 ms, pauses over 1000 ms: 0


No metrics recorded during the test

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-MicrosoftJDK17/55/

**Comment by Patras3** [comment]
Failed again on _master_ with openj9-11: https://jenkins.hazelcast.com/job/Hazelcast-master-Openj9-11/124/testReport/com.hazelcast.spi.impl.operationservice.impl/Invocation_ArbitraryArityConstructionTest/testAnyOf_whenSomeTimeout/
