### ISSUE TITLE
[TPC] com.hazelcast.internal.tpcengine.nio.NioAsyncSocket_RpcTest

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#24076]
_master_ (commit 5392e4dd9da8f8ca259ed09623bb2e025eb19b2c)

Failed on MacOS: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-MacOS-ZuluJDK8/189/testReport/com.hazelcast.internal.tpcengine.nio/NioAsyncSocket_RpcTest/

Following tests failed with similar exception:
- `com.hazelcast.internal.tpcengine.nio.NioAsyncSocket_RpcTest.test_concurrency_10_payload_1MB`
- `com.hazelcast.internal.tpcengine.nio.NioAsyncSocket_RpcTest.test_concurrency_10_payload_4KB`
- `com.hazelcast.internal.tpcengine.nio.NioAsyncSocket_RpcTest.test_concurrency_100_payload_128KB`
- `com.hazelcast.internal.tpcengine.nio.NioAsyncSocket_RpcTest.test_concurrency_100_payload_2KB`
- `com.hazelcast.internal.tpcengine.nio.NioAsyncSocket_RpcTest.test_concurrency_100_payload_4KB`
- `com.hazelcast.internal.tpcengine.nio.NioAsyncSocket_RpcTest.test_concurrency_100_payload_64KB`
- `com.hazelcast.internal.tpcengine.nio.NioAsyncSocket_RpcTest.test_concurrency_10_payload_128KB`
- `com.hazelcast.internal.tpcengine.nio.NioAsyncSocket_RpcTest.test_concurrency_10_payload_256KB`
- `com.hazelcast.internal.tpcengine.nio.NioAsyncSocket_RpcTest.test_concurrency_10_payload_512KB`
- `com.hazelcast.internal.tpcengine.nio.NioAsyncSocket_RpcTest.test_concurrency_10_payload_32KB`
- `com.hazelcast.internal.tpcengine.nio.NioAsyncSocket_RpcTest.test_concurrency_10_payload_64KB`

<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: Timeout waiting for thread Thread-54 to terminate
	at org.junit.Assert.fail(Assert.java:89)
	at com.hazelcast.internal.tpcengine.TpcTestSupport.assertJoinable(TpcTestSupport.java:98)
	at com.hazelcast.internal.tpcengine.AsyncSocket_RpcTest.test(AsyncSocket_RpcTest.java:245)
	at com.hazelcast.internal.tpcengine.AsyncSocket_RpcTest.test_concurrency_10_payload_1MB(AsyncSocket_RpcTest.java:193)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:49)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:120)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:95)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:69)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:146)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-MacOS-ZuluJDK8/189/

**Comment by olukas** [comment]
Failed again on _master_ with Windows - MicrosoftJDK11: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Windows-MicrosoftJDK11/58/testReport/com.hazelcast.internal.tpcengine.nio/NioAsyncSocket_RpcTest/

**Comment by pveentjer** [comment]
This is an important snippet from the log:

```
java.lang.AssertionError
	at com.hazelcast.internal.tpcengine.nio.NioAsyncSocket$Handler.handleWrite(NioAsyncSocket.java:393)
	at com.hazelcast.internal.tpcengine.nio.NioAsyncSocket$Handler.handle(NioAsyncSocket.java:368)
	at com.hazelcast.internal.tpcengine.nio.NioEventloop.run(NioEventloop.java:86)
	at com.hazelcast.internal.tpcengine.Reactor$StartEventloopTask.run(Reactor.java:408)
	at java.lang.Thread.run(Thread.java:748)
```

That should be triggered by this assert:
```
 private void handleWrite() throws IOException {
            assert flushThread.get() != null;

            metrics.incWriteEvents();

           ....
        }```
        
So apparently the NioAsyncSocket.Handler is run with the flush thread being set.

**Comment by Patras3** [comment]
Failed again on _master_ with MacOS: https://jenkins.hazelcast.com/job/Hazelcast-master-MacOS-ZuluJDK8/190/testReport/com.hazelcast.internal.tpcengine.nio/NioAsyncSocket_RpcTest/

**Comment by pveentjer** [comment]
The Handler.run is also called when the key is cancelled and it can happen the the assert throws an error. So the assert should be removed.

This doesn't explain the failing test because this happens when the socket is closed. And there is something else going on with the test.

**Comment by olukas** [comment]
Failed again on _master_ with ibm-8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-IbmJDK8/229/testReport/com.hazelcast.internal.tpcengine.nio/NioAsyncSocket_RpcTest/

**Comment by olukas** [comment]
Failed again on _master_ with ibm-8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-IbmJDK8/230/testReport/com.hazelcast.internal.tpcengine.nio/NioAsyncSocket_RpcTest/

**Comment by olukas** [comment]
Failed again on _master_ with ibm-8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-IbmJDK8/231/testReport/com.hazelcast.internal.tpcengine.nio/NioAsyncSocket_RpcTest/

**Comment by olukas** [comment]
Failed again on _master_ with ibm-8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-IbmJDK8/232/testReport/com.hazelcast.internal.tpcengine.nio/NioAsyncSocket_RpcTest/

**Comment by ramizdundar** [comment]
Closed by:

- https://github.com/hazelcast/hazelcast/pull/24267
- https://github.com/hazelcast/hazelcast/pull/24319
