### ISSUE TITLE
[TPC] com.hazelcast.internal.tpcengine.nio.NioAsyncSocketTest

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#24087]
_master_ (commit e5873252f705d65b3f78df96a742c7448127821f)

Failed on ibm-8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-IbmJDK8-fips/72/testReport/com.hazelcast.internal.tpcengine.nio/NioAsyncSocketTest/

Following tests failed with the same exception:
- `com.hazelcast.internal.tpcengine.nio.NioAsyncSocketTest.test_readable`
- `com.hazelcast.internal.tpcengine.nio.NioAsyncSocketTest.test_connect`

<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: expected:</127.0.0.1:33099> but was:<null>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:120)
	at org.junit.Assert.assertEquals(Assert.java:146)
	at com.hazelcast.internal.tpcengine.AsyncSocketTest.test_readable(AsyncSocketTest.java:195)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:49)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:120)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:95)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:69)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:146)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)

```
</details>

<details><summary>Standard output:</summary>

```
Mar 23, 2023 2:01:44 PM com.hazelcast.internal.tpcengine.logging.JulLoggerFactory$JulLogger info
INFO: Thread-954 Binding to /127.0.0.1:0
Mar 23, 2023 2:01:44 PM com.hazelcast.internal.tpcengine.logging.JulLoggerFactory$JulLogger info
INFO: /127.0.0.1:33099 started accepting
Mar 23, 2023 2:01:44 PM com.hazelcast.internal.tpcengine.logging.JulLoggerFactory$JulLogger info
INFO: Connecting to address:/127.0.0.1:33099
Mar 23, 2023 2:01:44 PM com.hazelcast.internal.tpcengine.logging.JulLoggerFactory$JulLogger info
INFO: NioAsyncServerSocket[/127.0.0.1:33099] accepted: /127.0.0.1:50914->/127.0.0.1:33099
Mar 23, 2023 2:01:44 PM com.hazelcast.internal.tpcengine.logging.JulLoggerFactory$JulLogger info
INFO: Connection established NioAsyncSocket[/127.0.0.1:50914->/127.0.0.1:33099]
Mar 23, 2023 2:01:44 PM com.hazelcast.internal.tpcengine.logging.JulLoggerFactory$JulLogger info
INFO: Connection established NioAsyncSocket[/127.0.0.1:50914->/127.0.0.1:33099]
Mar 23, 2023 2:01:44 PM com.hazelcast.internal.tpcengine.logging.JulLoggerFactory$JulLogger warning
WARNING: Closing  NioAsyncSocket[/127.0.0.1:50914->/127.0.0.1:33099]
java.lang.NullPointerException
	at com.hazelcast.internal.tpcengine.nio.NioAsyncSocket$Handler.handleConnect(NioAsyncSocket.java:438)
	at com.hazelcast.internal.tpcengine.nio.NioAsyncSocket$Handler.handle(NioAsyncSocket.java:372)
	at com.hazelcast.internal.tpcengine.nio.NioEventloop.run(NioEventloop.java:86)
	at com.hazelcast.internal.tpcengine.Reactor$StartEventloopTask.run(Reactor.java:408)
	at java.lang.Thread.run(Thread.java:825)

Mar 23, 2023 2:01:44 PM com.hazelcast.internal.tpcengine.logging.JulLoggerFactory$JulLogger info
INFO: Closing NioAsyncSocket[/127.0.0.1:33099->/127.0.0.1:50914] due to Remote socket closed!
Mar 23, 2023 2:01:44 PM com.hazelcast.internal.tpcengine.logging.JulLoggerFactory$JulLogger info
INFO: Closing NioAsyncServerSocket[/127.0.0.1:33099] due to Reactor-1 is terminating.
Mar 23, 2023 2:01:44 PM com.hazelcast.internal.tpcengine.logging.JulLoggerFactory$JulLogger info
INFO: Thread-954 terminated
Mar 23, 2023 2:01:44 PM com.hazelcast.internal.tpcengine.logging.JulLoggerFactory$JulLogger info
INFO: Connecting to address:/127.0.0.1:5000
Mar 23, 2023 2:01:44 PM com.hazelcast.internal.tpcengine.logging.JulLoggerFactory$JulLogger warning
WARNING: Closing  NioAsyncSocket[null->null]
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:731)
	at com.hazelcast.internal.tpcengine.nio.NioAsyncSocket$Handler.handleConnect(NioAsyncSocket.java:428)
	at com.hazelcast.internal.tpcengine.nio.NioAsyncSocket$Handler.handle(NioAsyncSocket.java:372)
	at com.hazelcast.internal.tpcengine.nio.NioEventloop.run(NioEventloop.java:86)
	at com.hazelcast.internal.tpcengine.Reactor$StartEventloopTask.run(Reactor.java:408)
	at java.lang.Thread.run(Thread.java:825)

Mar 23, 2023 2:01:44 PM com.hazelcast.internal.tpcengine.logging.JulLoggerFactory$JulLogger info
INFO: Thread-955 terminated
Mar 23, 2023 2:01:44 PM com.hazelcast.internal.tpcengine.logging.JulLoggerFactory$JulLogger info
INFO: Closing NioAsyncSocket[null->null] due to Reactor-1 is terminating.
Mar 23, 2023 2:01:44 PM com.hazelcast.internal.tpcengine.logging.JulLoggerFactory$JulLogger info
INFO: Thread-956 terminated
Mar 23, 2023 2:01:44 PM com.hazelcast.internal.tpcengine.logging.JulLoggerFactory$JulLogger info
INFO: Closing NioAsyncSocket[null->null] due to Reactor-1 is terminating.
Mar 23, 2023 2:01:44 PM com.hazelcast.internal.tpcengine.logging.JulLoggerFactory$JulLogger info
INFO: Thread-957 terminated
Mar 23, 2023 2:01:44 PM com.hazelcast.internal.tpcengine.logging.JulLoggerFactory$JulLogger info
INFO: Thread-958 Binding to /127.0.0.1:0
Mar 23, 2023 2:01:44 PM com.hazelcast.internal.tpcengine.logging.JulLoggerFactory$JulLogger info
INFO: /127.0.0.1:37617 started accepting
Mar 23, 2023 2:01:44 PM com.hazelcast.internal.tpcengine.logging.JulLoggerFactory$JulLogger info
INFO: Connecting to address:/127.0.0.1:37617
Mar 23, 2023 2:01:44 PM com.hazelcast.internal.tpcengine.logging.JulLoggerFactory$JulLogger info
INFO: NioAsyncServerSocket[/127.0.0.1:37617] accepted: /127.0.0.1:37442->/127.0.0.1:37617
Mar 23, 2023 2:01:44 PM com.hazelcast.internal.tpcengine.logging.JulLoggerFactory$JulLogger info
INFO: Connection established NioAsyncSocket[/127.0.0.1:37442->/127.0.0.1:37617]
Mar 23, 2023 2:01:44 PM com.hazelcast.internal.tpcengine.logging.JulLoggerFactory$JulLogger info
INFO: Connection established NioAsyncSocket[/127.0.0.1:37442->/127.0.0.1:37617]
Mar 23, 2023 2:01:44 PM com.hazelcast.internal.tpcengine.logging.JulLoggerFactory$JulLogger warning
WARNING: Closing  NioAsyncSocket[/127.0.0.1:37442->/127.0.0.1:37617]
java.lang.NullPointerException
	at com.hazelcast.internal.tpcengine.nio.NioAsyncSocket$Handler.handleConnect(NioAsyncSocket.java:438)
	at com.hazelcast.internal.tpcengine.nio.NioAsyncSocket$Handler.handle(NioAsyncSocket.java:372)
	at com.hazelcast.internal.tpcengine.nio.NioEventloop.run(NioEventloop.java:86)
	at com.hazelcast.internal.tpcengine.Reactor$StartEventloopTask.run(Reactor.java:408)
	at java.lang.Thread.run(Thread.java:825)

Mar 23, 2023 2:01:44 PM com.hazelcast.internal.tpcengine.logging.JulLoggerFactory$JulLogger info
INFO: Closing NioAsyncSocket[/127.0.0.1:37617->/127.0.0.1:37442] due to Remote socket closed!
Mar 23, 2023 2:01:45 PM com.hazelcast.internal.tpcengine.logging.JulLoggerFactory$JulLogger info
INFO: Closing NioAsyncServerSocket[/127.0.0.1:37617] due to Reactor-1 is terminating.
Mar 23, 2023 2:01:45 PM com.hazelcast.internal.tpcengine.logging.JulLoggerFactory$JulLogger info
INFO: Thread-958 terminated
Mar 23, 2023 2:01:45 PM com.hazelcast.internal.tpcengine.logging.JulLoggerFactory$JulLogger info
INFO: Closing  NioAsyncSocket[null->null]
Mar 23, 2023 2:01:45 PM com.hazelcast.internal.tpcengine.logging.JulLoggerFactory$JulLogger info
INFO: Thread-959 terminated
Mar 23, 2023 2:01:45 PM com.hazelcast.internal.tpcengine.logging.JulLoggerFactory$JulLogger info
INFO: Closing  NioAsyncSocket[null->null]
Mar 23, 2023 2:01:45 PM com.hazelcast.internal.tpcengine.logging.JulLoggerFactory$JulLogger info
INFO: Thread-960 terminated
Mar 23, 2023 2:01:45 PM com.hazelcast.internal.tpcengine.logging.JulLoggerFactory$JulLogger info
INFO: Closing NioAsyncSocket[null->null] due to Reactor-1 is terminating.
Mar 23, 2023 2:01:45 PM com.hazelcast.internal.tpcengine.logging.JulLoggerFactory$JulLogger info
INFO: Thread-961 terminated
Mar 23, 2023 2:01:45 PM com.hazelcast.internal.tpcengine.logging.JulLoggerFactory$JulLogger warning
WARNING: java.lang.IllegalStateException: NioAsyncSocket[null->null] is already started
java.lang.IllegalStateException: NioAsyncSocket[null->null] is already started
	at com.hazelcast.internal.tpcengine.nio.NioAsyncSocket.start0(NioAsyncSocket.java:183)
	at com.hazelcast.internal.tpcengine.nio.NioAsyncSocket.lambda$start$2(NioAsyncSocket.java:170)
	at com.hazelcast.internal.tpcengine.Eventloop.runExternalTasks(Eventloop.java:167)
	at com.hazelcast.internal.tpcengine.nio.NioEventloop.run(NioEventloop.java:93)
	at com.hazelcast.internal.tpcengine.Reactor$StartEventloopTask.run(Reactor.java:408)
	at java.lang.Thread.run(Thread.java:825)

Mar 23, 2023 2:01:45 PM com.hazelcast.internal.tpcengine.logging.JulLoggerFactory$JulLogger info
INFO: Closing NioAsyncSocket[null->null] due to Reactor-1 is terminating.
Mar 23, 2023 2:01:45 PM com.hazelcast.internal.tpcengine.logging.JulLoggerFactory$JulLogger info
INFO: Thread-962 terminated

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-IbmJDK8-fips/72/

**Comment by pveentjer** [comment]
I'm going to close this ticket for the time being. The following PR resolves various connect-related problems:

https://github.com/hazelcast/hazelcast/pull/24088

If the issue persists, the ticket needs to be reopened.
