### ISSUE TITLE
com.hazelcast.datalink.impl.DataLinkConsistencyCheckerTest.test_missingDataLinkWasAddedToDataLinkService

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#24086]
_master_ (commit dee4a19a2afcc14da031c1f59ee8224b74dc1d8e)

Failed on Windows - MicrosoftJDK11: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Windows-MicrosoftJDK11/58/testReport/com.hazelcast.datalink.impl/DataLinkConsistencyCheckerTest/test_missingDataLinkWasAddedToDataLinkService/
<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at com.hazelcast.datalink.impl.DataLinkConsistencyCheckerTest.test_missingDataLinkWasAddedToDataLinkService(DataLinkConsistencyCheckerTest.java:81)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:829)

```
</details>

<details><summary>Standard output:</summary>

```
BuildInfo right after test_missingDataLinkWasAddedToDataLinkService(com.hazelcast.datalink.impl.DataLinkConsistencyCheckerTest): BuildInfo{version='5.3.0-SNAPSHOT', build='20230323', buildNumber=20230323, revision=dee4a19, enterprise=false, serializationVersion=1}
Finished Running Test: test_outdatedDataLinkWasAlteredInDataLinkService in 1.332 seconds.
Hiccups measured while running test 'test_missingDataLinkWasAddedToDataLinkService(com.hazelcast.datalink.impl.DataLinkConsistencyCheckerTest):'
21:20:00, accumulated pauses: 1632 ms, max pause: 1300 ms, pauses over 1000 ms: 1


No metrics recorded during the test

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-Windows-MicrosoftJDK11/58/

**Comment by orcunc** [comment]
When the test failed there was code to remove the Datalink as below
```
@Override
public void removeDataLink(String name) {
  dataLinks.computeIfPresent(name, (k, v) -> {
    if (CONFIG.equals(v.source)) {
      throw new HazelcastException("Data link '" + name + "' is configured via Config and can't be removed");
    }
    v.instance.release();
    return null;
     });
}
```

That code does not exist anymore. The dataConnections map does not support remove operation anymore. So the test should be fixed by other changes.

**Comment by olukas** [comment]
Closing the test failure - it doesn't seem to be related to `master` or the latest maintenance stream `5.5.z` and it hasn't fail in the last 3 months. Feel free to reopen test failure if it occurs on `master` or on the latest maintenance stream.
