### ISSUE TITLE
com.hazelcast.mapstore.GenericMapStoreIntegrationTest.testInstanceShutdown [HZ-2224]

### ISSUE THREAD

**Issue by Patras3** [hazelcast/hazelcast#24097]
_master_ (commit 1ba198bccce5686191b2cbcb67d4eaf0775fff5d)

Failed on oracle-8: https://jenkins.hazelcast.com/job/Hazelcast-master-OracleJDK8/243/testReport/junit/com.hazelcast.mapstore/GenericMapStoreIntegrationTest/testInstanceShutdown/
<details><summary>Stacktrace:</summary>

```
org.junit.ComparisonFailure: 

Expecting actual:
  "Hazelcast instance is not active!"
not to contain:
  "is not active!"
 expected:<"[]is not active!"> but was:<"[Hazelcast instance ]is not active!">
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at com.hazelcast.mapstore.GenericMapStoreIntegrationTest.testInstanceShutdown(GenericMapStoreIntegrationTest.java:362)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:750)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-OracleJDK8/243/

**Comment by Patras3** [comment]
Failed again on _master_ with corretto-8: https://jenkins.hazelcast.com/job/Hazelcast-master-CorrettoJDK8/221/testReport/junit/com.hazelcast.mapstore/GenericMapStoreIntegrationTest/testInstanceShutdown/

**Comment by Patras3** [comment]
Failed again on _5.3.z_ with corretto-11: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-CorrettoJDK11/92/testReport/junit/com.hazelcast.mapstore/GenericMapStoreIntegrationTest/testInstanceShutdown/

**Comment by Patras3** [comment]
Failed again on _5.3.z_ with redhat-8: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-RedHatJDK8/93/testReport/junit/com.hazelcast.mapstore/GenericMapStoreIntegrationTest/testInstanceShutdown/

**Comment by Patras3** [comment]
Failed again on _master_ with openj9-17: https://jenkins.hazelcast.com/job/Hazelcast-master-Openj9-17/78/testReport/junit/com.hazelcast.mapstore/GenericMapStoreIntegrationTest/testInstanceShutdown/

**Comment by sumnerib** [comment]
Failed again on _5.3.z_ with redhat-8: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-RedHatJDK8/96/testReport/junit/com.hazelcast.mapstore/GenericMapStoreIntegrationTest/testInstanceShutdown/

**Comment by olukas** [comment]
Failed again on _master_ with redhat-17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-RedHatJDK17/80/testReport/com.hazelcast.mapstore/GenericMapStoreIntegrationTest/testInstanceShutdown/

**Comment by Patras3** [comment]
This comment was automatically generated to summarize test results for the last 30 days.

```

For branch: 5.3.z
Builds between : 2024-07-05 21:09 - 2024-07-26 21:09
Jobs: 1, Runs: 4, Passed: 4, Failed: 0, Skipped: 0, Fail Ratio: 0.00%
Run on:
+------------------------------------------------+
| JDK      | PASSED | FAILED | SKIPPED |  RATIO  |
+------------------------------------------------+
| oracle-8 |   4    |   0    |    0    |   0.00% |
+------------------------------------------------+

Builds Timeline:
2024-07-26 21:09 - PASSED (oracle-8):
    https://jenkins.hazelcast.com/job/Hazelcast-5.3.z-OracleJDK8/13/testReport/com.hazelcast.mapstore/GenericMapStoreIntegrationTest/testInstanceShutdown/
2024-07-19 21:09 - PASSED (oracle-8):
    https://jenkins.hazelcast.com/job/Hazelcast-5.3.z-OracleJDK8/12/testReport/com.hazelcast.mapstore/GenericMapStoreIntegrationTest/testInstanceShutdown/
2024-07-12 21:09 - PASSED (oracle-8):
    https://jenkins.hazelcast.com/job/Hazelcast-5.3.z-OracleJDK8/11/testReport/com.hazelcast.mapstore/GenericMapStoreIntegrationTest/testInstanceShutdown/
2024-07-05 21:09 - PASSED (oracle-8):
    https://jenkins.hazelcast.com/job/Hazelcast-5.3.z-OracleJDK8/10/testReport/com.hazelcast.mapstore/GenericMapStoreIntegrationTest/testInstanceShutdown/

----------------------------------------
```

**Comment by olukas** [comment]
Closing the test failure - it doesn't seem to be related to `master` or the latest maintenance stream `5.5.z` and it hasn't fail in the last 3 months. Feel free to reopen test failure if it occurs on `master` or on the latest maintenance stream.
