### ISSUE TITLE
DataLink issues

### ISSUE THREAD

**Issue by viliam-durina** [hazelcast/hazelcast#24112]
- the type should be case insensitive. The type is already insensitive in CREATE MAPPING
- the type list should be the same as in SQL's mapping
- incorrect type doesn't fail, but creates no data link. Background checker is broken since then.
```
com.hazelcast.core.HazelcastException: Data link 'o_d3d1dd8e_1bd3_4824_a98d_9b0c13cc02a2' misconfigured: class 'dummy' not found
	at com.hazelcast.datalink.impl.DataLinkServiceImpl.createDataLinkInstance(DataLinkServiceImpl.java:152) ~[classes/:?]
	at com.hazelcast.datalink.impl.DataLinkServiceImpl.lambda$put$2(DataLinkServiceImpl.java:102) ~[classes/:?]
	at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1916) ~[?:?]
	at com.hazelcast.datalink.impl.DataLinkServiceImpl.put(DataLinkServiceImpl.java:82) ~[classes/:?]
	at com.hazelcast.datalink.impl.DataLinkServiceImpl.replaceSqlDataLink(DataLinkServiceImpl.java:108) ~[classes/:?]
	at com.hazelcast.datalink.impl.DataLinkConsistencyChecker.check(DataLinkConsistencyChecker.java:79) ~[classes/:?]
	at com.hazelcast.sql.impl.state.QueryStateRegistryUpdater$Worker.checkDataLinksConsistency(QueryStateRegistryUpdater.java:160) [classes/:?]
	at com.hazelcast.sql.impl.state.QueryStateRegistryUpdater$Worker.run(QueryStateRegistryUpdater.java:131) [classes/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassNotFoundException: dummy
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at com.hazelcast.datalink.impl.DataLinkServiceImpl.getDataLinkClass(DataLinkServiceImpl.java:164) ~[classes/:?]
	at com.hazelcast.datalink.impl.DataLinkServiceImpl.createDataLinkInstance(DataLinkServiceImpl.java:142) ~[classes/:?]
	... 8 more
```

- we should allow type nape or class name, but not both
- the usage of "type" and "class name" is confusing in code: sometimes it's `type`, sometimes it's `className`, and they store either. If they store either, the name should be `typeOrClassName` - this will help to spot the previous issues in code

**Comment by Fly-Style** [comment]
> the type should be case insensitive. The type is already insensitive in CREATE MAPPING

Done in #24500.

> the type list should be the same as in SQL's mapping

Re-designed, done with `InternalDataConnectionService#classForDataConnectionType`

> incorrect type doesn't fail, but creates no data link. Background checker is broken since then.

Fixed in #24500.

> we should allow type nape or class name, but not both

Re-designed, done with `InternalDataConnectionService#classForDataConnectionType`, now it works only with type name. 

> the usage of "type" and "class name" is confusing in code: sometimes it's type, sometimes it's className, and they store either. If they store either, the name should be typeOrClassName - this will help to spot the previous issues in code.

Refactored by @frant-hartm .
