### ISSUE TITLE
Classes are missing on classpath when jar submitted by hz-cli uses more threads [HZ-2227]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#24143]
**This issue is a regression against Hazelcast 5.2.x and against Hazelcast 5.3.0-BETA-1** (i.e. it works fine in Hazelcast 5.2.x and Hazelcast 5.3.0-BETA-1). It's caused by https://github.com/hazelcast/hazelcast/commit/6fe4045265f82503b3dcb7bee77605be0d6672e7.

In case when jar with Jet Pipeline definition is submitted through `hz-cli` and it uses more threads then classes are missing in the other threads. 

<details><summary>This leads to Exception like following:</summary>

```
Class containing the lambda probably missing from class path, did you add it using JobConfig.addClass()?: com.hazelcast.nio.serialization.HazelcastSerializationException: java.lang.ClassCastException: cannot assign instance of java.lang.invoke.SerializedLambda to field com.hazelcast.jet.impl.pipeline.transform.MapTransform.mapFn of type com.hazelcast.function.FunctionEx in instance of com.hazelcast.jet.impl.pipeline.transform.MapTransform
com.hazelcast.jet.JetException: Class containing the lambda probably missing from class path, did you add it using JobConfig.addClass()?: com.hazelcast.nio.serialization.HazelcastSerializationException: java.lang.ClassCastException: cannot assign instance of java.lang.invoke.SerializedLambda to field com.hazelcast.jet.impl.pipeline.transform.MapTransform.mapFn of type com.hazelcast.function.FunctionEx in instance of com.hazelcast.jet.impl.pipeline.transform.MapTransform
	at com.hazelcast.jet.impl.util.ExceptionUtil.handleSerializedLambdaCce(ExceptionUtil.java:216)
	at com.hazelcast.jet.impl.execution.init.CustomClassLoadedObject.deserializeWithCustomClassLoader(CustomClassLoadedObject.java:68)
	at com.hazelcast.jet.impl.JobCoordinationService.deserializeJobDefinition(JobCoordinationService.java:1218)
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitJob$2(JobCoordinationService.java:254)
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$57(JobCoordinationService.java:1430)
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$58(JobCoordinationService.java:1451)
	at com.hazelcast.internal.util.executor.CompletableFutureTask.run(CompletableFutureTask.java:64)
	at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:111)
Caused by: com.hazelcast.nio.serialization.HazelcastSerializationException: java.lang.ClassCastException: cannot assign instance of java.lang.invoke.SerializedLambda to field com.hazelcast.jet.impl.pipeline.transform.MapTransform.mapFn of type com.hazelcast.function.FunctionEx in instance of com.hazelcast.jet.impl.pipeline.transform.MapTransform
	at com.hazelcast.internal.serialization.impl.SerializationUtil.handleException(SerializationUtil.java:111)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:277)
	at com.hazelcast.jet.impl.execution.init.CustomClassLoadedObject.deserializeWithCustomClassLoader(CustomClassLoadedObject.java:66)
	... 11 more
Caused by: java.lang.ClassCastException: cannot assign instance of java.lang.invoke.SerializedLambda to field com.hazelcast.jet.impl.pipeline.transform.MapTransform.mapFn of type com.hazelcast.function.FunctionEx in instance of com.hazelcast.jet.impl.pipeline.transform.MapTransform
	at java.io.ObjectStreamClass$FieldReflector.setObjFieldValues(ObjectStreamClass.java:2302)
	at java.io.ObjectStreamClass.setObjFieldValues(ObjectStreamClass.java:1432)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2434)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2352)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2210)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1690)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:508)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:466)
	at java.util.ArrayList.readObject(ArrayList.java:799)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1185)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2319)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2210)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1690)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:508)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:466)
	at java.util.HashMap.readObject(HashMap.java:1419)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1185)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2319)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2210)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1690)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2428)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2352)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2210)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1690)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:508)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:466)
	at com.hazelcast.internal.serialization.impl.defaultserializers.JavaDefaultSerializers$JavaSerializer.read(JavaDefaultSerializers.java:92)
	at com.hazelcast.internal.serialization.impl.defaultserializers.JavaDefaultSerializers$JavaSerializer.read(JavaDefaultSerializers.java:85)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:44)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:271)
	at com.hazelcast.jet.impl.execution.init.CustomClassLoadedObject.deserializeWithCustomClassLoader(CustomClassLoadedObject.java:66)
	... 11 more
```

</details>

This behavior is fine for the new Jet job submission which are executed on server side (https://hazelcast.atlassian.net/browse/HZ-1455) but it's a regression for `hz-cli` where jar is executed on client side.

This issue is also blocker for Jet soak tests.

**How to reproduce:**
Submit jar with following code to Hazelcast through `hz-cli submit $PATH_TO_JAR`:
```
public static void main(String[] args) throws Exception {
    HazelcastInstance hz = Hazelcast.bootstrappedInstance();
    ExecutorService executorService = Executors.newFixedThreadPool(1);
    executorService.submit(() -> runPipeline(hz));
    // just wait for job submission
    Thread.sleep(5_000);
}

private static void runPipeline(HazelcastInstance hz) {
    Pipeline p = Pipeline.create();
    p.readFrom(Sources.map("map"))
            .map(t -> t)
            .writeTo(Sinks.map("secondMap"));
    hz.getJet().newJob(p).join();
}
```

**Comment by olukas** [comment]
Fixed by https://github.com/hazelcast/hazelcast/pull/24152
