### ISSUE TITLE
com.hazelcast.jet.sql.impl.SqlDataLinkStatementTest.when_createDefaultSharingDataLink_then_success

### ISSUE THREAD

**Issue by Patras3** [hazelcast/hazelcast#24145]
_master_ (commit f84172bae23aa53d42370eba55b30e07238adad1)

Failed on microsoft-17: https://jenkins.hazelcast.com/job/Hazelcast-master-MicrosoftJDK17/56/testReport/junit/com.hazelcast.jet.sql.impl/SqlDataLinkStatementTest/when_createDefaultSharingDataLink_then_success/
<details><summary>Stacktrace:</summary>

```
org.junit.ComparisonFailure: expected:<"[com.hazelcast.datalink.impl.DataLinkTestUtil$DummyDataLink]"> but was:<"[DUMMY]">
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at com.hazelcast.jet.sql.impl.SqlDataLinkStatementTest.when_createDefaultSharingDataLink_then_success(SqlDataLinkStatementTest.java:101)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)

```
</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: when_createDataLinkIfAlreadyExists_then_throws in 0.003 seconds.
Started Running Test: when_createDefaultSharingDataLink_then_success
04:02:55,776 DEBUG || - [JobRepository] hz.SqlDataLinkStatementTest_condescending_yonath.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Job cleanup took 0ms
04:02:55,781  INFO |when_createDefaultSharingDataLink_then_success| - [SqlTestSupport] Time-limited test - Removing 0 cached plans in SqlTestSupport.@After
04:02:55,781  INFO |when_createDefaultSharingDataLink_then_success| - [SqlTestSupport] Time-limited test - Removing 0 cached plans in SqlTestSupport.@After
04:02:55,782  INFO |when_createDefaultSharingDataLink_then_success| - [SimpleTestInClusterSupport] Time-limited test - Ditching 0 jobs in SimpleTestInClusterSupport.@After: []
04:02:55,782  INFO |when_createDefaultSharingDataLink_then_success| - [SimpleTestInClusterSupport] Time-limited test - Destroying 1 distributed objects in SimpleTestInClusterSupport.@After: [hz:impl:mapService/__sql.catalog]
BuildInfo right after when_createDefaultSharingDataLink_then_success(com.hazelcast.jet.sql.impl.SqlDataLinkStatementTest): BuildInfo{version='5.3.0-SNAPSHOT', build='20230329', buildNumber=20230329, revision=f84172b, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'when_createDefaultSharingDataLink_then_success(com.hazelcast.jet.sql.impl.SqlDataLinkStatementTest):'
04:02:55, accumulated pauses: 334 ms, max pause: 135 ms, pauses over 1000 ms: 0


No metrics recorded during the test

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-MicrosoftJDK17/56/

**Comment by Patras3** [comment]
Failed again on _master_ with openjdk-11: https://jenkins.hazelcast.com/job/Hazelcast-master-ZuluJDK11/231/testReport/junit/com.hazelcast.jet.sql.impl/SqlDataLinkStatementTest/when_createDefaultSharingDataLink_then_success/
