### ISSUE TITLE
Kafka connect - Failed to serialize for writing into Map sink

### ISSUE THREAD

**Issue by Patras3** [hazelcast/hazelcast#24147]
There is `Failed to serialize 'org.apache.kafka.connect.source.SourceRecord'` issue during writing into map Sinks
  
**To Reproduce**

Replace list sink in `KafkaConnectNeo4jIntegrationTest#testReadFromNeo4jConnector` with:
```
                .map(e -> Util.entry(e, e))
                .writeTo(Sinks.map(randomMapName()));
```
and run the test.

<details><summary>Stacktrace</summary>

```

14:21:27,721  INFO || - [TaskletExecutionService] hz.KafkaConnectNeo4jIntegrationTest_recursing_swanson.jet.cooperative.thread-1 - [192.168.50.12]:5701 [dev] [5.3.0-SNAPSHOT] Exception in ProcessorTasklet{09a0-dca2-6b80-0001/mapSink(58625806-c7b7-418c-8892-346179e64ea4)#0}
com.hazelcast.nio.serialization.HazelcastSerializationException: Failed to serialize 'org.apache.kafka.connect.source.SourceRecord'
	at com.hazelcast.internal.serialization.impl.SerializationUtil.handleSerializeException(SerializationUtil.java:129) ~[classes/:?]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:241) ~[classes/:?]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:217) ~[classes/:?]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toData(AbstractSerializationService.java:202) ~[classes/:?]
	at com.hazelcast.map.impl.proxy.MapProxySupport.toDataWithStrategy(MapProxySupport.java:1333) ~[classes/:?]
	at com.hazelcast.map.impl.proxy.MapProxySupport.putAllInternal(MapProxySupport.java:1005) ~[classes/:?]
	at com.hazelcast.map.impl.proxy.MapProxyImpl.putAllAsync(MapProxyImpl.java:499) ~[classes/:?]
	at com.hazelcast.map.impl.proxy.MapProxyImpl.putAllAsync(MapProxyImpl.java:112) ~[classes/:?]
	at com.hazelcast.jet.impl.connector.WriteMapP.submitPending(WriteMapP.java:139) ~[classes/:?]
	at com.hazelcast.jet.impl.connector.WriteMapP.processInternal(WriteMapP.java:124) ~[classes/:?]
	at com.hazelcast.jet.impl.connector.AsyncHazelcastWriterP.process(AsyncHazelcastWriterP.java:75) ~[classes/:?]
	at com.hazelcast.jet.impl.processor.ProcessorWrapper.process(ProcessorWrapper.java:97) ~[classes/:?]
	at com.hazelcast.jet.impl.pipeline.FunctionAdapter$AdaptingProcessor.process(FunctionAdapter.java:226) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.lambda$processInbox$2f647568$2(ProcessorTasklet.java:490) ~[classes/:?]
	at com.hazelcast.jet.function.RunnableEx.run(RunnableEx.java:31) ~[classes/:?]
	at com.hazelcast.jet.impl.util.Util.doWithClassLoader(Util.java:532) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.processInbox(ProcessorTasklet.java:490) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:341) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:336) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:328) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:291) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:404) ~[classes/:?]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:895) [?:1.8.0_345]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.run(TaskletExecutionService.java:369) [classes/:?]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_345]
Caused by: com.hazelcast.nio.serialization.HazelcastSerializationException: Expected type arguments of type java.util.Map<java.lang.String, ?> to be classes
	at com.hazelcast.internal.serialization.impl.compact.zeroconfig.ValueReaderWriters.getTupleComponentTypes(ValueReaderWriters.java:300) ~[classes/:?]
	at com.hazelcast.internal.serialization.impl.compact.zeroconfig.ValueReaderWriters.readerWriterFor(ValueReaderWriters.java:196) ~[classes/:?]
	at com.hazelcast.internal.serialization.impl.compact.ReflectiveCompactSerializer.createFastReadWriteCaches(ReflectiveCompactSerializer.java:299) ~[classes/:?]
	at com.hazelcast.internal.serialization.impl.compact.ReflectiveCompactSerializer.write(ReflectiveCompactSerializer.java:82) ~[classes/:?]
	at com.hazelcast.internal.serialization.impl.compact.CompactStreamSerializer.buildSchema(CompactStreamSerializer.java:379) ~[classes/:?]
	at com.hazelcast.internal.serialization.impl.compact.CompactStreamSerializer.writeObject(CompactStreamSerializer.java:147) ~[classes/:?]
	at com.hazelcast.internal.serialization.impl.compact.CompactStreamSerializer.write(CompactStreamSerializer.java:116) ~[classes/:?]
	at com.hazelcast.internal.serialization.impl.compact.CompactStreamSerializer.write(CompactStreamSerializer.java:109) ~[classes/:?]
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.write(StreamSerializerAdapter.java:39) ~[classes/:?]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:238) ~[classes/:?]
	... 23 more
14:21:28,693  INFO || - [Neo4jSinkTask] ForkJoinPool.commonPool-worker-9 - Stop() - Closing Neo4j Source Service.
14:21:28,941  INFO || - [Neo4jSourceService] ForkJoinPool.commonPool-worker-9 - Neo4j Source Service closed successfully

```

</details>

**Comment by Patras3** [comment]
I checked https://github.com/hazelcast/hazelcast/pull/24203 and there still is problem with serialization of map from SourceRecords:
```
10:58:41,624 ERROR |testReading| - [StartExecutionOperation] hz.KafkaConnectMongoIntegrationTest_gallant_hopper.cached.thread-56 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Exception in ProcessorTasklet{09b1-69a2-4640-0001/mapSink(test)#0}: com.hazelcast.nio.serialization.HazelcastSerializationException: Failed to serialize 'org.apache.kafka.connect.source.SourceRecord'
com.hazelcast.jet.JetException: Exception in ProcessorTasklet{09b1-69a2-4640-0001/mapSink(test)#0}: com.hazelcast.nio.serialization.HazelcastSerializationException: Failed to serialize 'org.apache.kafka.connect.source.SourceRecord'
	at com.hazelcast.jet.impl.execution.TaskletExecutionService.handleTaskletExecutionError(TaskletExecutionService.java:286) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService.access$600(TaskletExecutionService.java:80) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:410) ~[classes/:?]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807) ~[?:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.run(TaskletExecutionService.java:369) ~[classes/:?]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
Caused by: com.hazelcast.nio.serialization.HazelcastSerializationException: Failed to serialize 'org.apache.kafka.connect.source.SourceRecord'
	at com.hazelcast.internal.serialization.impl.SerializationUtil.handleSerializeException(SerializationUtil.java:129) ~[classes/:?]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:241) ~[classes/:?]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:217) ~[classes/:?]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toData(AbstractSerializationService.java:202) ~[classes/:?]
	at com.hazelcast.map.impl.proxy.MapProxySupport.toDataWithStrategy(MapProxySupport.java:1334) ~[classes/:?]
	at com.hazelcast.map.impl.proxy.MapProxySupport.putAllInternal(MapProxySupport.java:1006) ~[classes/:?]
	at com.hazelcast.map.impl.proxy.MapProxyImpl.putAllAsync(MapProxyImpl.java:499) ~[classes/:?]
	at com.hazelcast.map.impl.proxy.MapProxyImpl.putAllAsync(MapProxyImpl.java:112) ~[classes/:?]
	at com.hazelcast.jet.impl.connector.WriteMapP.submitPending(WriteMapP.java:139) ~[classes/:?]
	at com.hazelcast.jet.impl.connector.WriteMapP.processInternal(WriteMapP.java:124) ~[classes/:?]
	at com.hazelcast.jet.impl.connector.AsyncHazelcastWriterP.process(AsyncHazelcastWriterP.java:75) ~[classes/:?]
	at com.hazelcast.jet.impl.processor.ProcessorWrapper.process(ProcessorWrapper.java:97) ~[classes/:?]
	at com.hazelcast.jet.impl.pipeline.FunctionAdapter$AdaptingProcessor.process(FunctionAdapter.java:226) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.lambda$processInbox$2f647568$2(ProcessorTasklet.java:490) ~[classes/:?]
	at com.hazelcast.jet.function.RunnableEx.run(RunnableEx.java:31) ~[classes/:?]
	at com.hazelcast.jet.impl.util.Util.doWithClassLoader(Util.java:532) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.processInbox(ProcessorTasklet.java:490) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:341) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:336) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:328) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:291) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:404) ~[classes/:?]
	... 3 more
Caused by: com.hazelcast.nio.serialization.HazelcastSerializationException: Expected type arguments of type java.util.Map<java.lang.String, ?> to be classes
	at com.hazelcast.internal.serialization.impl.compact.zeroconfig.ValueReaderWriters.getTupleComponentTypes(ValueReaderWriters.java:300) ~[classes/:?]
	at com.hazelcast.internal.serialization.impl.compact.zeroconfig.ValueReaderWriters.readerWriterFor(ValueReaderWriters.java:196) ~[classes/:?]
	at com.hazelcast.internal.serialization.impl.compact.ReflectiveCompactSerializer.createFastReadWriteCaches(ReflectiveCompactSerializer.java:299) ~[classes/:?]
	at com.hazelcast.internal.serialization.impl.compact.ReflectiveCompactSerializer.write(ReflectiveCompactSerializer.java:82) ~[classes/:?]
	at com.hazelcast.internal.serialization.impl.compact.CompactStreamSerializer.buildSchema(CompactStreamSerializer.java:379) ~[classes/:?]
	at com.hazelcast.internal.serialization.impl.compact.CompactStreamSerializer.writeObject(CompactStreamSerializer.java:147) ~[classes/:?]
	at com.hazelcast.internal.serialization.impl.compact.CompactStreamSerializer.write(CompactStreamSerializer.java:116) ~[classes/:?]
	at com.hazelcast.internal.serialization.impl.compact.CompactStreamSerializer.write(CompactStreamSerializer.java:109) ~[classes/:?]
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.write(StreamSerializerAdapter.java:39) ~[classes/:?]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:238) ~[classes/:?]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:217) ~[classes/:?]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toData(AbstractSerializationService.java:202) ~[classes/:?]
	at com.hazelcast.map.impl.proxy.MapProxySupport.toDataWithStrategy(MapProxySupport.java:1334) ~[classes/:?]
	at com.hazelcast.map.impl.proxy.MapProxySupport.putAllInternal(MapProxySupport.java:1006) ~[classes/:?]
	at com.hazelcast.map.impl.proxy.MapProxyImpl.putAllAsync(MapProxyImpl.java:499) ~[classes/:?]
	at com.hazelcast.map.impl.proxy.MapProxyImpl.putAllAsync(MapProxyImpl.java:112) ~[classes/:?]
	at com.hazelcast.jet.impl.connector.WriteMapP.submitPending(WriteMapP.java:139) ~[classes/:?]
	at com.hazelcast.jet.impl.connector.WriteMapP.processInternal(WriteMapP.java:124) ~[classes/:?]
	at com.hazelcast.jet.impl.connector.AsyncHazelcastWriterP.process(AsyncHazelcastWriterP.java:75) ~[classes/:?]
	at com.hazelcast.jet.impl.processor.ProcessorWrapper.process(ProcessorWrapper.java:97) ~[classes/:?]
	at com.hazelcast.jet.impl.pipeline.FunctionAdapter$AdaptingProcessor.process(FunctionAdapter.java:226) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.lambda$processInbox$2f647568$2(ProcessorTasklet.java:490) ~[classes/:?]
	at com.hazelcast.jet.function.RunnableEx.run(RunnableEx.java:31) ~[classes/:?]
	at com.hazelcast.jet.impl.util.Util.doWithClassLoader(Util.java:532) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.processInbox(ProcessorTasklet.java:490) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:341) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:336) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:328) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:291) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:404) ~[classes/:?]
```

![image](https://user-images.githubusercontent.com/20545793/231406794-d3123586-0b70-4719-ab2a-41f1dab5ad12.png)
![image](https://user-images.githubusercontent.com/20545793/231407094-2fde49d0-4cdf-4cb8-9567-7c424ea5f48d.png)
![image](https://user-images.githubusercontent.com/20545793/231407164-703ed968-e524-4e6d-9e0e-346da72436f9.png)
![image](https://user-images.githubusercontent.com/20545793/231407234-649afdff-f00f-4027-9ed0-e1781dad4eb9.png)

![image](https://user-images.githubusercontent.com/20545793/231408433-4e20e926-cc15-4c64-aa6c-afc5de2ea378.png)

I'm not sure if we can fix that somehow.

**Comment by ldziedziul** [comment]
We can't write SourceRecord directly to the map sink, we need to use `projectionFn` or `.map` method to convert it to something Serializable
