### ISSUE TITLE
com.hazelcast.mapstore.GenericMapStoreIntegrationTest.(?) [HZ-2345]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#24165]
_master_ (commit 336728cfb054666fb5e4c4c93f74feaebeec4dc4)

Failed on oracle-8 (little-endian): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-little-endian/247/testReport/com.hazelcast.mapstore/GenericMapStoreIntegrationTest/___/
<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: 
[There should be no running instances] 
Expecting empty but was: [HazelcastInstance{name='MSSQLGenericMapStoreIntegrationTest_clever_chatelet', node=[127.0.0.1]:5701}]
	at com.hazelcast.test.HazelcastTestSupport.assertNoRunningInstances(HazelcastTestSupport.java:819)
	at com.hazelcast.jet.SimpleTestInClusterSupport.initialize(SimpleTestInClusterSupport.java:61)
	at com.hazelcast.jet.SimpleTestInClusterSupport.initializeWithClient(SimpleTestInClusterSupport.java:85)
	at com.hazelcast.mapstore.GenericMapStoreIntegrationTest.initializeBeforeClass(GenericMapStoreIntegrationTest.java:81)
	at com.hazelcast.mapstore.GenericMapStoreIntegrationTest.beforeClass(GenericMapStoreIntegrationTest.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:41)
	at com.hazelcast.test.OverridePropertyRule$1.evaluate(OverridePropertyRule.java:66)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:750)

```
</details>

<details><summary>Standard output:</summary>

```
Apr 01, 2023 10:16:02 AM com.microsoft.sqlserver.jdbc.SQLServerConnection prelogin
WARNING: ConnectionID:111 ClientConnectionId: 0be3b091-f7c0-46d1-b4ae-fb70dade8bb4 Prelogin error: host 172.17.0.1 port 42137 Error reading prelogin response: Connection reset ClientConnectionId:0be3b091-f7c0-46d1-b4ae-fb70dade8bb4
10:16:13,643  INFO || - [NodeExtension] Thread-13 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Destroying node NodeExtension.
10:16:13,644  INFO || - [Node] Thread-13 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Hazelcast Shutdown is completed in 50806 ms.
10:16:13,645  INFO || - [LifecycleService] Thread-13 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
10:16:16,546  INFO || - [MetricsConfigHelper] Time-limited test - [LOCAL] [dev] [5.3.0-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
10:16:16,548  INFO || - [logo] Time-limited test - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
10:16:16,548  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Copyright (c) 2008-2023, Hazelcast, Inc. All Rights Reserved.
10:16:16,548  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Hazelcast Platform 5.3.0-SNAPSHOT (20230401 - 336728c) starting at [127.0.0.1]:5701
10:16:16,549  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Cluster name: dev
10:16:16,549  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed. For more information, see the documentation for Integrity Checker.
10:16:16,549  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Jet is enabled
10:16:16,585  INFO || - [MetricsConfigHelper] Time-limited test - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
10:16:16,586  INFO || - [TpcServerBootstrap] Time-limited test - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] TPC: disabled
10:16:17,464  WARN || - [CPSubsystem] Time-limited test - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
10:16:17,475  INFO || - [JetServiceBackend] Time-limited test - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Setting number of cooperative threads and default parallelism to 2
10:16:17,478  INFO || - [Diagnostics] Time-limited test - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
10:16:17,478  INFO || - [LifecycleService] Time-limited test - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] [127.0.0.1]:5701 is STARTING
10:16:17,479  INFO || - [ClusterService] Time-limited test - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] 

Members {size:1, ver:1} [
	Member [127.0.0.1]:5701 - 244faa68-19e2-4a97-9855-06890a209dba this
]

10:16:17,479  INFO || - [JobCoordinationService] Time-limited test - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Jet started scanning for jobs
10:16:17,479  INFO || - [LifecycleService] Time-limited test - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] [127.0.0.1]:5701 is STARTED
10:16:17,481  INFO || - [MetricsConfigHelper] Time-limited test - [LOCAL] [dev] [5.3.0-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
10:16:17,482  INFO || - [logo] Time-limited test - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
10:16:17,482  INFO || - [system] Time-limited test - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Copyright (c) 2008-2023, Hazelcast, Inc. All Rights Reserved.
10:16:17,482  INFO || - [system] Time-limited test - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Hazelcast Platform 5.3.0-SNAPSHOT (20230401 - 336728c) starting at [127.0.0.1]:5702
10:16:17,482  INFO || - [system] Time-limited test - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Cluster name: dev
10:16:17,482  INFO || - [system] Time-limited test - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed. For more information, see the documentation for Integrity Checker.
10:16:17,482  INFO || - [system] Time-limited test - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Jet is enabled
10:16:17,490  INFO || - [MetricsConfigHelper] Time-limited test - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
10:16:17,490  INFO || - [TpcServerBootstrap] Time-limited test - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] TPC: disabled
10:16:17,505  WARN || - [CPSubsystem] Time-limited test - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
10:16:17,509  INFO || - [JetServiceBackend] Time-limited test - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Setting number of cooperative threads and default parallelism to 2
10:16:17,512  INFO || - [Diagnostics] Time-limited test - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
10:16:17,512  INFO || - [LifecycleService] Time-limited test - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] [127.0.0.1]:5702 is STARTING
10:16:17,512  INFO || - [MockServer] Time-limited test - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Created connection to endpoint: [127.0.0.1]:5701-244faa68-19e2-4a97-9855-06890a209dba, connection: MockConnection{localEndpoint=[address=[127.0.0.1]:5702, uuid=56cf4ef5-49b9-4bab-8ef5-7204e916e2b4], remoteEndpoint=[address=[127.0.0.1]:5701, uuid=244faa68-19e2-4a97-9855-06890a209dba], alive=true}
10:16:17,514  INFO || - [MockServer] hz.MySQLGenericMapStoreIntegrationTest_goofy_chatelet.priority-generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Created connection to endpoint: [127.0.0.1]:5702-56cf4ef5-49b9-4bab-8ef5-7204e916e2b4, connection: MockConnection{localEndpoint=[address=[127.0.0.1]:5701, uuid=244faa68-19e2-4a97-9855-06890a209dba], remoteEndpoint=[address=[127.0.0.1]:5702, uuid=56cf4ef5-49b9-4bab-8ef5-7204e916e2b4], alive=true}
10:16:17,515  INFO || - [ClusterService] hz.MySQLGenericMapStoreIntegrationTest_goofy_chatelet.priority-generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] 

Members {size:2, ver:2} [
	Member [127.0.0.1]:5701 - 244faa68-19e2-4a97-9855-06890a209dba this
	Member [127.0.0.1]:5702 - 56cf4ef5-49b9-4bab-8ef5-7204e916e2b4
]

10:16:17,616  INFO || - [ClusterService] hz.MySQLGenericMapStoreIntegrationTest_vigilant_chatelet.generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] 

Members {size:2, ver:2} [
	Member [127.0.0.1]:5701 - 244faa68-19e2-4a97-9855-06890a209dba
	Member [127.0.0.1]:5702 - 56cf4ef5-49b9-4bab-8ef5-7204e916e2b4 this
]

10:16:17,616  INFO || - [JobCoordinationService] Time-limited test - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Jet started scanning for jobs
10:16:17,617  INFO || - [LifecycleService] Time-limited test - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] [127.0.0.1]:5702 is STARTED
10:16:17,625  INFO || - [ClientInvocationService] Time-limited test - hz.client_2 [dev] [5.3.0-SNAPSHOT] Running with 2 response threads, dynamic=true
10:16:17,626  INFO || - [LifecycleService] Time-limited test - hz.client_2 [dev] [5.3.0-SNAPSHOT] HazelcastClient 5.3.0-SNAPSHOT (20230401 - 336728c) is STARTING
10:16:17,626  INFO || - [LifecycleService] Time-limited test - hz.client_2 [dev] [5.3.0-SNAPSHOT] HazelcastClient 5.3.0-SNAPSHOT (20230401 - 336728c) is STARTED
10:16:17,627  INFO || - [ClientConnectionManager] Time-limited test - hz.client_2 [dev] [5.3.0-SNAPSHOT] Trying to connect to cluster: dev
10:16:17,627  INFO || - [ClientConnectionManager] Time-limited test - hz.client_2 [dev] [5.3.0-SNAPSHOT] Trying to connect to [127.0.0.1]:5701
10:16:17,628  INFO || - [HazelcastClient] Time-limited test - Created connection to endpoint: [127.0.0.1]:5701, connection: MockedClientConnection{localAddress=[127.0.0.1]:40001, super=ClientConnection{alive=true, connectionId=1, channel=null, remoteAddress=null, lastReadTime=never, lastWriteTime=never, closedTime=never}}
10:16:17,629  INFO || - [AuthenticationMessageTask] hz.MySQLGenericMapStoreIntegrationTest_goofy_chatelet.generic-operation.thread-1 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Received auth from MockedNodeConnection{ remoteAddress = [127.0.0.1]:40001, localAddress = [127.0.0.1]:5701, connectionId = 1}, successfully authenticated, clientUuid: 3f1a4bf9-0bc3-43d5-80d7-b36f2d7dea86, client name: hz.client_2, client version: 5.3.0-SNAPSHOT
10:16:17,630  INFO || - [LifecycleService] Time-limited test - hz.client_2 [dev] [5.3.0-SNAPSHOT] HazelcastClient 5.3.0-SNAPSHOT (20230401 - 336728c) is CLIENT_CONNECTED
10:16:17,630  INFO || - [ClientConnectionManager] Time-limited test - hz.client_2 [dev] [5.3.0-SNAPSHOT] Authenticated with server [127.0.0.1]:5701:244faa68-19e2-4a97-9855-06890a209dba, server version: 5.3.0-SNAPSHOT, local address: /127.0.0.1:40001
10:16:17,630  INFO || - [Diagnostics] Time-limited test - hz.client_2 [dev] [5.3.0-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
10:16:17,632  INFO || - [ClientClusterService] hz.client_2.event-16 - hz.client_2 [dev] [5.3.0-SNAPSHOT] 

Members [2] {
	Member [127.0.0.1]:5701 - 244faa68-19e2-4a97-9855-06890a209dba
	Member [127.0.0.1]:5702 - 56cf4ef5-49b9-4bab-8ef5-7204e916e2b4
}

10:16:17,632  INFO || - [HazelcastClient] Time-limited test - Created connection to endpoint: [127.0.0.1]:5702, connection: MockedClientConnection{localAddress=[127.0.0.1]:40002, super=ClientConnection{alive=true, connectionId=2, channel=null, remoteAddress=null, lastReadTime=never, lastWriteTime=never, closedTime=never}}
10:16:17,633  INFO || - [AuthenticationMessageTask] hz.MySQLGenericMapStoreIntegrationTest_vigilant_chatelet.priority-generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Received auth from MockedNodeConnection{ remoteAddress = [127.0.0.1]:40002, localAddress = [127.0.0.1]:5702, connectionId = 2}, successfully authenticated, clientUuid: 3f1a4bf9-0bc3-43d5-80d7-b36f2d7dea86, client name: hz.client_2, client version: 5.3.0-SNAPSHOT
10:16:17,633  INFO || - [ClientConnectionManager] Time-limited test - hz.client_2 [dev] [5.3.0-SNAPSHOT] Authenticated with server [127.0.0.1]:5702:56cf4ef5-49b9-4bab-8ef5-7204e916e2b4, server version: 5.3.0-SNAPSHOT, local address: /127.0.0.1:40002
10:16:17,636  INFO || - [ClientStatisticsService] Time-limited test - Client statistics is enabled with period 5 seconds.
Started Running Test: testPutAll

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-little-endian/247/

**Comment by frant-hartm** [comment]
The likely cause was fixed, if we see this again with 
```
Expecting empty but was: [HazelcastInstance{name='MSSQLGenericMapStoreIntegrationTest_clever_chatelet',
```
Please reopen, otherwise create a new issue.
