### ISSUE TITLE
Mongo Connector improvements  [HZ-2237]

### ISSUE THREAD

**Issue by Patras3** [hazelcast/hazelcast#24167]
Group issue of improvements for Mongo Connector:
1.  Improve logs messages - currently from the client side error is:
```
java.lang.NullPointerException: unable to connect to Mongo
	at java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:375)
	at java.util.concurrent.CompletableFuture.join(CompletableFuture.java:1947)
	at com.hazelcast.jet.Job.join(Job.java:80)
	at com.mycompany.simple.hz.app.Main.main(Main.java:53)
Caused by: com.hazelcast.jet.JetException: Exception in ProcessorTasklet{09a2-21ad-f1c0-0001/abc#0}: java.lang.NullPointerException: unable to connect to Mongo
	at com.hazelcast.jet.impl.execution.TaskletExecutionService.handleTaskletExecutionError(TaskletExecutionService.java:286)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService.access$600(TaskletExecutionService.java:80)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$BlockingWorker.run(TaskletExecutionService.java:325)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: unable to connect to Mongo
	at com.hazelcast.internal.util.Preconditions.checkNotNull(Preconditions.java:60)
	at com.hazelcast.jet.mongodb.impl.ReadMongoP$StreamMongoReader.nextChunkTraverser(ReadMongoP.java:433)
```

but from the sever it was:
```
023-03-31 14:01:28,215 [ WARN] [hz.festive_darwin.jet.blocking.thread-1] [.h.j.m.i.ReadMongoP]: [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] [09a2-21ad-f1c0-0001/abc#1] Could not connect to MongoDB
com.mongodb.MongoCommandException: Command failed with error 40573 (Location40573): 'The $changeStream stage is only supported on replica sets' on server localhost:27017. The full response is {"ok": 0.0, "errmsg": "The $changeStream stage is only supported on replica sets", "code": 40573, "codeName": "Location40573"}
        at com.mongodb.internal.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java:205) ~[hazelcast-jet-mongodb-5.3.0-SNAPSHOT.jar:?]
        at com.mongodb.internal.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:443) ~[hazelcast-jet-mongodb-5.3.0-SNAPSHOT.jar:?]
```

We should propagate this kind of errors from server to the client. Error `"unable to connect to Mongo"` hides real problem which can be fixed by someone who will see `"The $changeStream stage is only supported on replica sets"`.

2. There is no check if collection already exists for the source.
3. "name" param for MongoSinks is redundant - you san use pipeline API to name your sink like:
```
.writeTo(mongodb(dataLinkRef("mongoDB"), defaultDatabase(), testName.getMethodName()))
.setName(SINK_NAME)
```

**Comment by TomaszGaweda** [comment]
Ad 2.:
> There is no check if collection already exists for the source.

If it doesn't exist, `getCollection` will create it. May be used as "read from now, may not exist  yet, but read as soon as we put anything". I'm not sure what is better approach, WDYT @Patras3  @frant-hartm @ldziedziul @olukas?

**Comment by TomaszGaweda** [comment]
ok, so in linked PR I've added parameter to configure this. By default it will throw an error, but if you want it can create such collection for you

**Comment by sumnerib** [comment]
I'm still hitting this issue with the latest SNAPSHOT:

> We should propagate this kind of errors from server to the client. Error "unable to connect to Mongo" hides real problem...

In my case it's `'$function not allowed in this atlas tier'`, but this error is still hidden from the client-side and instead only the NPE is shown:

```
Exception in thread "main" com.hazelcast.sql.HazelcastSqlException: The Jet SQL job failed: Execution on a member failed: com.hazelcast.jet.JetException: Exception in ProcessorTasklet{09c5-0203-7a42-0001/Select (person)#1}: java.lang.NullPointerException: unable to connect to Mongo
        at com.hazelcast.sql.impl.client.SqlClientService.handleExecuteResponse(SqlClientService.java:303)
        at com.hazelcast.sql.impl.client.SqlClientService.execute(SqlClientService.java:145)
        at com.hazelcast.sql.SqlService.execute(SqlService.java:89)
        at com.qe.TimerClient.main(TimerClient.java:140)
```

Reproducer:

Given a running HZ cluster, the following can be executed on the client to reproduce the issue:

```
HazelcastInstance hz = HazelcastClient.newHazelcastClient(clientConfig);
hz.getSql().execute(
    "CREATE OR REPLACE DATA CONNECTION atlas " 
    + "TYPE mongo "
    + "OPTIONS ( "
    + "'connectionString' = '<your Atlas connectionString>' "
    + ")"
);

hz.getSql().execute(
    "CREATE OR REPLACE MAPPING person EXTERNAL NAME Hazelcast.person "
    + "DATA CONNECTION atlas " 
    + "OPTIONS( "
    + "'database' = 'Hazelcast' "
    + ")"
);

try (SqlResult res = hz.getSql().execute("SELECT * FROM person")) {
    for (SqlRow row : res) {
        System.out.println(row);
    }
}
```

This is especially important in Viridian, otherwise the user needs to download the member logs to find the root cause.

**Comment by frant-hartm** [comment]
@sumnerib If we see the correct message in the member, then we already have this issue #24389 to propagate the info to the user
