### ISSUE TITLE
com.hazelcast.jet.mongodb.MongoSinkResilienceTest.testSink_networkTimeout

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#24164]
_master_ (commit 336728cfb054666fb5e4c4c93f74feaebeec4dc4)

Failed on openjdk-19: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-OpenJDK-sts-nightly/23/testReport/com.hazelcast.jet.mongodb/MongoSinkResilienceTest/testSink_networkTimeout/
<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: expected:<165> but was:<35>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at com.hazelcast.jet.mongodb.MongoSinkResilienceTest.lambda$sinkNetworkTest$4(MongoSinkResilienceTest.java:240)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1288)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1392)
	at com.hazelcast.jet.mongodb.MongoSinkResilienceTest.sinkNetworkTest(MongoSinkResilienceTest.java:239)
	at com.hazelcast.jet.mongodb.MongoSinkResilienceTest.testSink_networkTimeout(MongoSinkResilienceTest.java:171)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.lang.Thread.run(Thread.java:1589)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-OpenJDK-sts-nightly/23/

**Comment by TomaszGaweda** [comment]
Test no longer exist, replaced by EE test
