### ISSUE TITLE
Hazelcast 5.1.1 SlowOperation

### ISSUE THREAD

**Issue by tc792617871** [hazelcast/hazelcast#24230]
When we used Hazelcast5.1.1 and JDK17 for pressure testing, we encountered many slowoperation, but in JDK8 has not found.

SlowOpertion logs as follows：
java.base@17.0.4.1/java.util.HashMap.putVal(HashMap.java:629) 
java.base@17.0.4.1/java.util.HashMap.putMapEntries(HashMap.java:514) 
java.base@17.0.4.1/java.util.HashMap.<init>(HashMap.java:484) 
app//com.hazelcast.query.impl.BaseIndexStore$CopyInputFunctor.invoke(BaseIndexStore.java:154) 
app//com.hazelcast.query.impl.BaseIndexStore.copyToMultiResultSet(BaseIndexStore.java:95) 
app//com.hazelcast.query.impl.OrderedIndexStore.getRecords(OrderedIndexStore.java:351) 
app//com.hazelcast.query.impl.AbstractIndex.getRecords(AbstractIndex.java:315) 
app//com.hazelcast.query.impl.GlobalQueryContextWithStats$QueryTrackingIndex.getRecords(GlobalQueryContextWithStats.java:241) 
app//com.hazelcast.query.impl.predicates.GreaterLessPredicate.filter(GreaterLessPredicate.java:82) 
app//com.hazelcast.query.impl.predicates.AndPredicate.filter(AndPredicate.java:84) 
app//com.hazelcast.query.impl.Indexes.query(Indexes.java:445) 
app//com.hazelcast.map.impl.query.QueryRunner.runUsingGlobalIndexSafely(QueryRunner.java:280) 
app//com.hazelcast.map.impl.query.QueryRunner.runIndexOrPartitionScanQueryOnOwnedPartitions(QueryRunner.java:141) 
app//com.hazelcast.map.impl.query.QueryRunner.runIndexOrPartitionScanQueryOnOwnedPartitions(QueryRunner.java:109) 
app//com.hazelcast.map.impl.query.QueryOperation.callInternal(QueryOperation.java:89) 
app//com.hazelcast.map.impl.query.QueryOperation.call(QueryOperation.java:78) 
app//com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:273) 
app//com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:248) 
app//com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:471) 
app//com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:197) 
app//com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:137) 
app//com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123) 
app//com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)

**Comment by vbekiaris** [comment]
@tc792617871 thanks for reporting this issue. I assume you mean that with everything else being the same, just switching from JDK8 to JDK17 you observe slow operations in your logs, correct?

Can you please provide more details like:
- these slow operations, do they look like they are stuck or are they taking longer to complete (e.g. latency spikes?)?
- what is your Hazelcast configuration? I see you are using indexes, can you share your full config yaml/xml?
- are you running hazelcast embedded or client-server?
- what is your test scenario? a mix of gets/puts? queries with predicates?

**Comment by tc792617871** [comment]
- these slow operations are taking longer to recover, look from jmeter is Performance degradation.

- Hazelcast configuration as follows:
`<hazelcast xmlns="http://www.hazelcast.com/schema/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.hazelcast.com/schema/config http://www.hazelcast.com/schema/config/hazelcast-config-5.1.xsd">
     <license-key>****</license-key>
     <cluster-name>business</cluster-name>
     <management-center scripting-enabled="true" console-enabled="true" data-access-enabled="true"/>
     <properties>
          <property name="hazelcast.socket.bind.any">false</property>
     </properties>
     <security enabled="false">
          <client-block-unmapped-actions>true</client-block-unmapped-actions>
     </security>
     <network>
          <port port-count="100" auto-increment="true">5701</port>
          <reuse-address>true</reuse-address>
          <outbound-ports>
               <ports>0</ports>
          </outbound-ports>
          <join>
               <auto-detection enabled="false"/>
               <multicast enabled="false">
                    <multicast-group>xxxx</multicast-group>
                    <multicast-port>54327</multicast-port>
                    <multicast-timeout-seconds>2</multicast-timeout-seconds>
                    <multicast-time-to-live>32</multicast-time-to-live>
               </multicast>
               <tcp-ip enabled="true" connection-timeout-seconds="5">
                    <member-list>
                         <member>168.xxx.xxx.1</member>
                         <member>168.xxx.xxx.2</member>
                         <member>168.xxx.xxx.3</member>
                    </member-list>
               </tcp-ip>
               <aws enabled="false"/>
               <gcp enabled="false"/>
               <azure enabled="false"/>
               <kubernetes enabled="false"/>
               <eureka enabled="false">
                    <namespace>hazelcast</namespace>
                    <self-registration>true</self-registration>
               </eureka>
               <discovery-strategies/>
          </join>
          <interfaces enabled="true">
               <interface>168.xxx.xxx.1</interface>
          </interfaces>
          <ssl enabled="false"/>
          <socket-interceptor enabled="false"/>
          <failure-detector>
               <icmp enabled="false">
                    <ttl>255</ttl>
                    <interval-milliseconds>1000</interval-milliseconds>
                    <max-attempts>2</max-attempts>
                    <timeout-milliseconds>1000</timeout-milliseconds>
                    <fail-fast-on-startup>true</fail-fast-on-startup>
                    <parallel-mode>true</parallel-mode>
               </icmp>
          </failure-detector>
          <rest-api enabled="false">
               <endpoint-group name="CLUSTER_READ" enabled="false"/>
               <endpoint-group name="CLUSTER_WRITE" enabled="false"/>
               <endpoint-group name="HEALTH_CHECK" enabled="true"/>
               <endpoint-group name="PERSISTENCE" enabled="false"/>
               <endpoint-group name="HOT_RESTART" enabled="false"/>
               <endpoint-group name="WAN" enabled="false"/>
               <endpoint-group name="DATA" enabled="false"/>
               <endpoint-group name="CP" enabled="false"/>
          </rest-api>
          <memcache-protocol enabled="false"/>
     </network>
     <replicatedmap name="default">
          <in-memory-format>OBJECT</in-memory-format>
          <async-fillup>true</async-fillup>
          <statistics-enabled>true</statistics-enabled>
          <merge-policy batch-size="100">com.hazelcast.spi.merge.PutIfAbsentMergePolicy</merge-policy>
     </replicatedmap>
     <map name="default">
          <in-memory-format>BINARY</in-memory-format>
          <statistics-enabled>true</statistics-enabled>
          <per-entry-stats-enabled>true</per-entry-stats-enabled>
          <cache-deserialized-values>INDEX-ONLY</cache-deserialized-values>
          <backup-count>1</backup-count>
          <async-backup-count>0</async-backup-count>
          <time-to-live-seconds>0</time-to-live-seconds>
          <max-idle-seconds>0</max-idle-seconds>
          <merge-policy batch-size="100">com.hazelcast.spi.merge.PutIfAbsentMergePolicy</merge-policy>
          <read-backup-data>false</read-backup-data>
          <metadata-policy>CREATE_ON_UPDATE</metadata-policy>
          <eviction size="2147483647" max-size-policy="PER_NODE" eviction-policy="NONE"/>
          <event-journal enabled="false">
               <capacity>10000</capacity>
               <time-to-live-seconds>0</time-to-live-seconds>
          </event-journal>
          <data-persistence enabled="false">
               <fsync>false</fsync>
          </data-persistence>
          <map-store enabled="false" initial-mode="LAZY">
               <write-coalescing>true</write-coalescing>
               <write-delay-seconds>0</write-delay-seconds>
               <write-batch-size>1</write-batch-size>
          </map-store>
          <tiered-store enabled="false">
               <memory-tier>
                    <capacity unit="MEGABYTES" value="256"/>
               </memory-tier>
               <disk-tier enabled="false" device-name="default-tiered-store-device"/>
          </tiered-store>
     </map>
     <map name="__jet.*">
          <in-memory-format>BINARY</in-memory-format>
          <statistics-enabled>true</statistics-enabled>
          <per-entry-stats-enabled>false</per-entry-stats-enabled>
          <cache-deserialized-values>INDEX-ONLY</cache-deserialized-values>
          <backup-count>1</backup-count>
          <async-backup-count>0</async-backup-count>
          <time-to-live-seconds>0</time-to-live-seconds>
          <max-idle-seconds>0</max-idle-seconds>
          <merge-policy batch-size="100">com.hazelcast.spi.merge.DiscardMergePolicy</merge-policy>
          <read-backup-data>false</read-backup-data>
          <metadata-policy>CREATE_ON_UPDATE</metadata-policy>
          <eviction size="2147483647" max-size-policy="PER_NODE" eviction-policy="NONE"/>
          <event-journal enabled="false">
               <capacity>10000</capacity>
               <time-to-live-seconds>0</time-to-live-seconds>
          </event-journal>
          <data-persistence enabled="false">
               <fsync>false</fsync>
          </data-persistence>
          <map-store enabled="false" initial-mode="LAZY">
               <write-coalescing>true</write-coalescing>
               <write-delay-seconds>0</write-delay-seconds>
               <write-batch-size>1</write-batch-size>
          </map-store>
          <tiered-store enabled="false">
               <memory-tier>
                    <capacity unit="MEGABYTES" value="256"/>
               </memory-tier>
               <disk-tier enabled="false" device-name="default-tiered-store-device"/>
          </tiered-store>
     </map>
     <map name="__jet.results">
          <in-memory-format>BINARY</in-memory-format>
          <statistics-enabled>true</statistics-enabled>
          <per-entry-stats-enabled>false</per-entry-stats-enabled>
          <cache-deserialized-values>INDEX-ONLY</cache-deserialized-values>
          <backup-count>1</backup-count>
          <async-backup-count>0</async-backup-count>
          <time-to-live-seconds>604800</time-to-live-seconds>
          <max-idle-seconds>0</max-idle-seconds>
          <merge-policy batch-size="100">com.hazelcast.spi.merge.DiscardMergePolicy</merge-policy>
          <read-backup-data>false</read-backup-data>
          <metadata-policy>CREATE_ON_UPDATE</metadata-policy>
          <eviction size="2147483647" max-size-policy="PER_NODE" eviction-policy="NONE"/>
          <event-journal enabled="false">
               <capacity>10000</capacity>
               <time-to-live-seconds>0</time-to-live-seconds>
          </event-journal>
          <data-persistence enabled="false">
               <fsync>false</fsync>
          </data-persistence>
          <map-store enabled="false" initial-mode="LAZY">
               <write-coalescing>true</write-coalescing>
               <write-delay-seconds>0</write-delay-seconds>
               <write-batch-size>1</write-batch-size>
          </map-store>
          <tiered-store enabled="false">
               <memory-tier>
                    <capacity unit="MEGABYTES" value="256"/>
               </memory-tier>
               <disk-tier enabled="false" device-name="default-tiered-store-device"/>
          </tiered-store>
     </map>
     <map name="__jet.results.metrics">
          <in-memory-format>BINARY</in-memory-format>
          <statistics-enabled>true</statistics-enabled>
          <per-entry-stats-enabled>false</per-entry-stats-enabled>
          <cache-deserialized-values>INDEX-ONLY</cache-deserialized-values>
          <backup-count>1</backup-count>
          <async-backup-count>0</async-backup-count>
          <time-to-live-seconds>604800</time-to-live-seconds>
          <max-idle-seconds>0</max-idle-seconds>
          <merge-policy batch-size="100">com.hazelcast.spi.merge.DiscardMergePolicy</merge-policy>
          <read-backup-data>false</read-backup-data>
          <metadata-policy>CREATE_ON_UPDATE</metadata-policy>
          <eviction size="2147483647" max-size-policy="PER_NODE" eviction-policy="NONE"/>
          <event-journal enabled="false">
               <capacity>10000</capacity>
               <time-to-live-seconds>0</time-to-live-seconds>
          </event-journal>
          <data-persistence enabled="false">
               <fsync>false</fsync>
          </data-persistence>
          <map-store enabled="false" initial-mode="LAZY">
               <write-coalescing>true</write-coalescing>
               <write-delay-seconds>0</write-delay-seconds>
               <write-batch-size>1</write-batch-size>
          </map-store>
          <tiered-store enabled="false">
               <memory-tier>
                    <capacity unit="MEGABYTES" value="256"/>
               </memory-tier>
               <disk-tier enabled="false" device-name="default-tiered-store-device"/>
          </tiered-store>
     </map>
     <queue name="default">
          <statistics-enabled>true</statistics-enabled>
          <max-size>2147483647</max-size>
          <backup-count>1</backup-count>
          <async-backup-count>0</async-backup-count>
          <empty-queue-ttl>-1</empty-queue-ttl>
          <merge-policy batch-size="100">com.hazelcast.spi.merge.PutIfAbsentMergePolicy</merge-policy>
     </queue>
     <multimap name="default">
          <backup-count>1</backup-count>
          <async-backup-count>0</async-backup-count>
          <statistics-enabled>true</statistics-enabled>
          <binary>true</binary>
          <value-collection-type>SET</value-collection-type>
          <merge-policy batch-size="100">com.hazelcast.spi.merge.PutIfAbsentMergePolicy</merge-policy>
     </multimap>
     <list name="default">
          <statistics-enabled>true</statistics-enabled>
          <max-size>2147483647</max-size>
          <backup-count>1</backup-count>
          <async-backup-count>0</async-backup-count>
          <merge-policy batch-size="100">com.hazelcast.spi.merge.PutIfAbsentMergePolicy</merge-policy>
     </list>
     <set name="default">
          <statistics-enabled>true</statistics-enabled>
          <max-size>2147483647</max-size>
          <backup-count>1</backup-count>
          <async-backup-count>0</async-backup-count>
          <merge-policy batch-size="100">com.hazelcast.spi.merge.PutIfAbsentMergePolicy</merge-policy>
     </set>
     <ringbuffer name="default">
          <capacity>10000</capacity>
          <time-to-live-seconds>0</time-to-live-seconds>
          <backup-count>1</backup-count>
          <async-backup-count>0</async-backup-count>
          <in-memory-format>BINARY</in-memory-format>
          <ringbuffer-store enabled="false"/>
          <merge-policy batch-size="100">com.hazelcast.spi.merge.PutIfAbsentMergePolicy</merge-policy>
     </ringbuffer>
     <executor-service name="default">
          <statistics-enabled>true</statistics-enabled>
          <pool-size>16</pool-size>
          <queue-capacity>0</queue-capacity>
     </executor-service>
     <durable-executor-service name="default">
          <pool-size>16</pool-size>
          <durability>1</durability>
          <capacity>100</capacity>
          <statistics-enabled>true</statistics-enabled>
     </durable-executor-service>
     <scheduled-executor-service name="default">
          <pool-size>16</pool-size>
          <durability>1</durability>
          <capacity>100</capacity>
          <capacity-policy>PER_NODE</capacity-policy>
          <merge-policy batch-size="100">com.hazelcast.spi.merge.PutIfAbsentMergePolicy</merge-policy>
          <statistics-enabled>true</statistics-enabled>
     </scheduled-executor-service>
     <partition-group enabled="false" group-type="PER_MEMBER"/>
     <cardinality-estimator name="default">
          <backup-count>1</backup-count>
          <async-backup-count>0</async-backup-count>
          <merge-policy batch-size="100">HyperLogLogMergePolicy</merge-policy>
     </cardinality-estimator>
     <serialization>
          <portable-version>0</portable-version>
          <use-native-byte-order>false</use-native-byte-order>
          <byte-order>BIG_ENDIAN</byte-order>
          <enable-compression>false</enable-compression>
          <enable-shared-object>true</enable-shared-object>
          <allow-unsafe>false</allow-unsafe>
          <allow-override-default-serializers>true</allow-override-default-serializers>
          <serializers>
               <serializer type-class="com.huatai.nats.model.BaseBO" class-name="com.huatai.nats.model.BaseBOByteArraySerializer"/>
          </serializers>
          <check-class-def-errors>true</check-class-def-errors>
     </serialization>
     <reliable-topic name="default">
          <statistics-enabled>true</statistics-enabled>
          <read-batch-size>10</read-batch-size>
          <topic-overload-policy>BLOCK</topic-overload-policy>
     </reliable-topic>
     <lite-member enabled="false"/>
     <native-memory enabled="false" allocator-type="POOLED">
          <size unit="MEGABYTES" value="512"/>
          <min-block-size>16</min-block-size>
          <page-size>4194304</page-size>
          <metadata-space-percentage>12.5</metadata-space-percentage>
          <persistent-memory enabled="false" mode="MOUNTED"/>
     </native-memory>
     <persistence enabled="false">
          <base-dir>/app/hazelcast/bin/persistence</base-dir>
          <parallelism>1</parallelism>
          <validation-timeout-seconds>120</validation-timeout-seconds>
          <data-load-timeout-seconds>900</data-load-timeout-seconds>
          <cluster-data-recovery-policy>FULL_RECOVERY_ONLY</cluster-data-recovery-policy>
          <auto-remove-stale-data>true</auto-remove-stale-data>
          <rebalance-delay-seconds>0</rebalance-delay-seconds>
          <encryption-at-rest enabled="false">
               <key-size>0</key-size>
               <algorithm>AES/CBC/PKCS5Padding</algorithm>
               <salt>****</salt>
               <secure-store/>
          </encryption-at-rest>
     </persistence>
     <dynamic-configuration>
          <persistence-enabled>false</persistence-enabled>
          <backup-dir>/app/hazelcast/bin/dynamic-configuration-backups</backup-dir>
          <backup-count>5</backup-count>
     </dynamic-configuration>
     <local-device name="default-tiered-store-device">
          <base-dir>/app/hazelcast/bin/tiered-store</base-dir>
          <capacity unit="GIGABYTES" value="256"/>
          <block-size>4096</block-size>
          <read-io-thread-count>4</read-io-thread-count>
          <write-io-thread-count>4</write-io-thread-count>
     </local-device>
     <flake-id-generator name="default">
          <prefetch-count>100</prefetch-count>
          <prefetch-validity-millis>600000</prefetch-validity-millis>
          <epoch-start>1514764800000</epoch-start>
          <node-id-offset>0</node-id-offset>
          <bits-sequence>6</bits-sequence>
          <bits-node-id>16</bits-node-id>
          <allowed-future-millis>15000</allowed-future-millis>
          <statistics-enabled>true</statistics-enabled>
     </flake-id-generator>
     <crdt-replication>
          <replication-period-millis>1000</replication-period-millis>
          <max-concurrent-replication-targets>1</max-concurrent-replication-targets>
     </crdt-replication>
     <pn-counter name="default">
          <replica-count>2147483647</replica-count>
          <statistics-enabled>true</statistics-enabled>
     </pn-counter>
     <cp-subsystem>
          <cp-member-count>3</cp-member-count>
          <group-size>3</group-size>
          <session-time-to-live-seconds>300</session-time-to-live-seconds>
          <session-heartbeat-interval-seconds>5</session-heartbeat-interval-seconds>
          <missing-cp-member-auto-removal-seconds>14400</missing-cp-member-auto-removal-seconds>
          <fail-on-indeterminate-operation-state>false</fail-on-indeterminate-operation-state>
          <persistence-enabled>false</persistence-enabled>
          <base-dir>/app/hazelcast/bin/cp-data</base-dir>
          <data-load-timeout-seconds>120</data-load-timeout-seconds>
          <raft-algorithm>
               <leader-election-timeout-in-millis>2000</leader-election-timeout-in-millis>
               <leader-heartbeat-period-in-millis>5000</leader-heartbeat-period-in-millis>
               <max-missed-leader-heartbeat-count>5</max-missed-leader-heartbeat-count>
               <append-request-max-entry-count>100</append-request-max-entry-count>
               <commit-index-advance-count-to-snapshot>10000</commit-index-advance-count-to-snapshot>
               <uncommitted-entry-count-to-reject-new-appends>100</uncommitted-entry-count-to-reject-new-appends>
               <append-request-backoff-timeout-in-millis>100</append-request-backoff-timeout-in-millis>
          </raft-algorithm>
          <semaphores/>
          <locks/>
     </cp-subsystem>
     <metrics enabled="true">
          <management-center enabled="true">
               <retention-seconds>5</retention-seconds>
          </management-center>
          <jmx enabled="true"/>
          <collection-frequency-seconds>5</collection-frequency-seconds>
     </metrics>
     <instance-tracking enabled="false"/>
     <sql>
          <statement-timeout-millis>0</statement-timeout-millis>
     </sql>
     <jet enabled="true" resource-upload-enabled="true">
          <cooperative-thread-count>8</cooperative-thread-count>
          <flow-control-period>100</flow-control-period>
          <backup-count>1</backup-count>
          <scale-up-delay-millis>10000</scale-up-delay-millis>
          <lossless-restart-enabled>false</lossless-restart-enabled>
          <max-processor-accumulated-records>9223372036854775807</max-processor-accumulated-records>
          <edge-defaults>
               <queue-size>1024</queue-size>
               <packet-size-limit>16384</packet-size-limit>
               <receive-window-multiplier>3</receive-window-multiplier>
          </edge-defaults>
     </jet>
     <auditlog enabled="false"/>
     <user-code-deployment enabled="false">
          <class-cache-mode>ETERNAL</class-cache-mode>
          <provider-mode>LOCAL_AND_CACHED_CLASSES</provider-mode>
     </user-code-deployment>
     <integrity-checker enabled="false"/>
</hazelcast>
`
- we are running hazelcast platform cluster
- we are using predicate for query,  test scenario is only query someone Map

**Comment by tc792617871** [comment]
> @tc792617871 thanks for reporting this issue. I assume you mean that with everything else being the same, just switching from JDK8 to JDK17 you observe slow operations in your logs, correct?
> 
> Can you please provide more details like:
> 
> * these slow operations, do they look like they are stuck or are they taking longer to complete (e.g. latency spikes?)?
> * what is your Hazelcast configuration? I see you are using indexes, can you share your full config yaml/xml?
> * are you running hazelcast embedded or client-server?
> * what is your test scenario? a mix of gets/puts? queries with predicates?

From Jstack log , we find hz thread , cpu take up a lot of time，jstack log as follows：
`"hz.vibrant_shaw.partition-operation.thread-1" #24 prio=5 os_prio=0 cpu=23975.23ms elapsed=1358.66s tid=0x00007fde25251210 nid=0x6f57 waiting on condition  [0x00007fdb824f3000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@17.0.4.1/Native Method)
	at java.util.concurrent.locks.LockSupport.park(java.base@17.0.4.1/LockSupport.java:341)
	at com.hazelcast.internal.util.concurrent.MPSCQueue.takeAll(MPSCQueue.java:229)
	at com.hazelcast.internal.util.concurrent.MPSCQueue.take(MPSCQueue.java:151)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationQueueImpl.take(OperationQueueImpl.java:85)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:118)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)

   Locked ownable synchronizers:
	- None

"hz.vibrant_shaw.partition-operation.thread-2" #25 prio=5 os_prio=0 cpu=22018.26ms elapsed=1358.66s tid=0x00007fde25252040 nid=0x6f58 waiting on condition  [0x00007fdb823f2000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@17.0.4.1/Native Method)
	at java.util.concurrent.locks.LockSupport.park(java.base@17.0.4.1/LockSupport.java:341)
	at com.hazelcast.internal.util.concurrent.MPSCQueue.takeAll(MPSCQueue.java:229)
	at com.hazelcast.internal.util.concurrent.MPSCQueue.take(MPSCQueue.java:151)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationQueueImpl.take(OperationQueueImpl.java:85)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:118)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)

   Locked ownable synchronizers:
	- None

"hz.vibrant_shaw.partition-operation.thread-3" #26 prio=5 os_prio=0 cpu=22563.28ms elapsed=1358.66s tid=0x00007fde25253280 nid=0x6f5c waiting on condition  [0x00007fdb822f1000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@17.0.4.1/Native Method)
	at java.util.concurrent.locks.LockSupport.park(java.base@17.0.4.1/LockSupport.java:341)
	at com.hazelcast.internal.util.concurrent.MPSCQueue.takeAll(MPSCQueue.java:229)
	at com.hazelcast.internal.util.concurrent.MPSCQueue.take(MPSCQueue.java:151)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationQueueImpl.take(OperationQueueImpl.java:85)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:118)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)

   Locked ownable synchronizers:
	- None

"hz.vibrant_shaw.partition-operation.thread-4" #27 prio=5 os_prio=0 cpu=21553.63ms elapsed=1358.66s tid=0x00007fde25257050 nid=0x6f5f waiting on condition  [0x00007fdb821f0000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@17.0.4.1/Native Method)
	at java.util.concurrent.locks.LockSupport.park(java.base@17.0.4.1/LockSupport.java:341)
	at com.hazelcast.internal.util.concurrent.MPSCQueue.takeAll(MPSCQueue.java:229)
	at com.hazelcast.internal.util.concurrent.MPSCQueue.take(MPSCQueue.java:151)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationQueueImpl.take(OperationQueueImpl.java:85)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:118)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)

   Locked ownable synchronizers:
	- None`
