### ISSUE TITLE
com.hazelcast.jet.mongodb.MongoSinkResilienceTest.testSink_networkCutoff [HZ-2306]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#24240]
_master_ (commit 68d95b261950a1dfdc55d205065a1cc430b2345e)

Failed on ibm-8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-IbmJDK8-nightly/99/testReport/com.hazelcast.jet.mongodb/MongoSinkResilienceTest/testSink_networkCutoff/
<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: expected:<148> but was:<20>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at com.hazelcast.jet.mongodb.MongoSinkResilienceTest.lambda$sinkNetworkTest$4(MongoSinkResilienceTest.java:242)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1288)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1392)
	at com.hazelcast.jet.mongodb.MongoSinkResilienceTest.sinkNetworkTest(MongoSinkResilienceTest.java:241)
	at com.hazelcast.jet.mongodb.MongoSinkResilienceTest.testSink_networkCutoff(MongoSinkResilienceTest.java:165)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.lang.Thread.run(Thread.java:825)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-IbmJDK8-nightly/99/

**Comment by olukas** [comment]
Failed again on _master_ with oracle-8 (force-offload): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-nightly-force-offload/42/testReport/com.hazelcast.jet.mongodb/MongoSinkResilienceTest/testSink_networkCutoff/
