### ISSUE TITLE
com.hazelcast.jet.sql.impl.connector.jdbc.mysql.MySQLDeleteJdbcSqlConnectorTest and com.hazelcast.jet.sql.impl.connector.jdbc.mysql.MySQLSelectJdbcSqlConnectorTest [HZ-2299]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#24244]
_master_ (commit 765cc352c833d7f27d3a438c18a4027b0a3158aa)

Failed on oracle-8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-OracleJDK8-nightly/943/testReport/com.hazelcast.jet.sql.impl.connector.jdbc.mysql/MySQLDeleteJdbcSqlConnectorTest/

Following tests failed with various exceptions:
- `com.hazelcast.jet.sql.impl.connector.jdbc.mysql.MySQLDeleteJdbcSqlConnectorTest.deleteFromWithQuotedColumnInWhere`
- `com.hazelcast.jet.sql.impl.connector.jdbc.mysql.MySQLSelectJdbcSqlConnectorTest.selectConcatExpressionFromTable`
- `com.hazelcast.jet.sql.impl.connector.jdbc.mysql.MySQLUpdateJdbcSqlConnectorTest.updateMappingWithQuotedColumnInSet`
- `com.hazelcast.jet.sql.impl.connector.jdbc.mysql.MySQLUpdateJdbcSqlConnectorTest.updateTableSetUsingTableColumnWithExternalName`
- `com.hazelcast.jet.sql.impl.connector.jdbc.mysql.MySQLUpdateJdbcSqlConnectorTest.updateTableSetUsingExpressionWithTableColumn`
- `com.hazelcast.jet.sql.impl.connector.jdbc.mysql.MySQLUpdateJdbcSqlConnectorTest.updateMappingWithQuotedColumnInWhere`

<details><summary>Stacktrace (for deleteFromWithQuotedColumnInWhere):</summary>

```
java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '"person-id" INT PRIMARY KEY, name VARCHAR(100))' at line 1
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:763)
	at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:648)
	at com.hazelcast.jet.sql.impl.connector.jdbc.JdbcSqlTestSupport.executeJdbc(JdbcSqlTestSupport.java:138)
	at com.hazelcast.jet.sql.impl.connector.jdbc.JdbcSqlTestSupport.createTable(JdbcSqlTestSupport.java:110)
	at com.hazelcast.jet.sql.impl.connector.jdbc.DeleteJdbcSqlConnectorTest.deleteFromWithQuotedColumnInWhere(DeleteJdbcSqlConnectorTest.java:163)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:750)

```
</details>

<details><summary>Standard output (for deleteFromWithQuotedColumnInWhere):</summary>

```
Finished Running Test: deleteFromWithMultiplePKColumns in 0.060 seconds.
Started Running Test: deleteFromWithQuotedColumnInWhere
08:20:30,857  INFO |deleteFromWithQuotedColumnInWhere| - [SqlTestSupport] Time-limited test - Removing 0 cached plans in SqlTestSupport.@After
08:20:30,857  INFO |deleteFromWithQuotedColumnInWhere| - [SqlTestSupport] Time-limited test - Removing 0 cached plans in SqlTestSupport.@After
08:20:30,858  INFO |deleteFromWithQuotedColumnInWhere| - [SimpleTestInClusterSupport] Time-limited test - Ditching 0 jobs in SimpleTestInClusterSupport.@After: []
08:20:30,858  INFO |deleteFromWithQuotedColumnInWhere| - [SimpleTestInClusterSupport] Time-limited test - Destroying 0 distributed objects in SimpleTestInClusterSupport.@After: []
BuildInfo right after deleteFromWithQuotedColumnInWhere(com.hazelcast.jet.sql.impl.connector.jdbc.mysql.MySQLDeleteJdbcSqlConnectorTest): BuildInfo{version='5.3.0-SNAPSHOT', build='20230412', buildNumber=20230412, revision=765cc35, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'deleteFromWithQuotedColumnInWhere(com.hazelcast.jet.sql.impl.connector.jdbc.mysql.MySQLDeleteJdbcSqlConnectorTest):'
08:20:30, accumulated pauses: 560 ms, max pause: 556 ms, pauses over 1000 ms: 0


No metrics recorded during the test

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-OracleJDK8-nightly/943/

**Comment by olukas** [comment]
Failed again on _master_ with oracle-8 (force-offload): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-nightly-force-offload/41/testReport/com.hazelcast.jet.sql.impl.connector.jdbc.mysql/MySQLDeleteJdbcSqlConnectorTest/
