### ISSUE TITLE
com.hazelcast.jet.kafka.connect.KafkaConnectCouchbaseIntegrationTest.(?)

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#24245]
_master_ (commit 68d95b261950a1dfdc55d205065a1cc430b2345e)

Failed on openjdk-19: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-OpenJDK-sts-nightly/24/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectCouchbaseIntegrationTest/___/
<details><summary>Stacktrace:</summary>

```
org.testcontainers.containers.ContainerLaunchException: Container startup failed for image couchbase/server:7.1.1
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:349)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322)
	at com.hazelcast.jet.kafka.connect.KafkaConnectCouchbaseIntegrationTest.setUpDocker(KafkaConnectCouchbaseIntegrationTest.java:90)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:41)
	at com.hazelcast.test.OverridePropertyRule$1.evaluate(OverridePropertyRule.java:66)
	at com.hazelcast.test.OverridePropertyRule$1.evaluate(OverridePropertyRule.java:66)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:334)
	... 17 more
Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:553)
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:344)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
	... 18 more
Caused by: java.lang.RuntimeException: Could not perform request against couchbase HTTP endpoint 
	at org.testcontainers.couchbase.CouchbaseContainer.doHttpRequest(CouchbaseContainer.java:790)
	at org.testcontainers.couchbase.CouchbaseContainer.renameNode(CouchbaseContainer.java:400)
	at org.testcontainers.couchbase.CouchbaseContainer.timePhase(CouchbaseContainer.java:802)
	at org.testcontainers.couchbase.CouchbaseContainer.containerIsStarting(CouchbaseContainer.java:341)
	at org.testcontainers.containers.GenericContainer.containerIsStarting(GenericContainer.java:703)
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:479)
	... 20 more
Caused by: java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:313)
	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:340)
	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:789)
	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:1025)
	at org.testcontainers.shaded.okio.InputStreamSource.read(JvmOkio.kt:94)
	at org.testcontainers.shaded.okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:125)
	at org.testcontainers.shaded.okio.RealBufferedSource.indexOf(RealBufferedSource.kt:427)
	at org.testcontainers.shaded.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:320)
	at org.testcontainers.shaded.okhttp3.internal.http1.HeadersReader.readLine(HeadersReader.kt:29)
	at org.testcontainers.shaded.okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:178)
	at org.testcontainers.shaded.okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106)
	at org.testcontainers.shaded.okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79)
	at org.testcontainers.shaded.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at org.testcontainers.shaded.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
	at org.testcontainers.shaded.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at org.testcontainers.shaded.okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at org.testcontainers.shaded.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at org.testcontainers.shaded.okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at org.testcontainers.shaded.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at org.testcontainers.shaded.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at org.testcontainers.shaded.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at org.testcontainers.shaded.okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at org.testcontainers.shaded.okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at org.testcontainers.couchbase.CouchbaseContainer.doHttpRequest(CouchbaseContainer.java:788)
	... 25 more
	Suppressed: java.io.IOException: unexpected end of stream on http://172.17.0.1:37477/...
		at org.testcontainers.shaded.okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:202)
		... 39 more
	Caused by: java.io.EOFException: \n not found: limit=0 content=…
		at org.testcontainers.shaded.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:332)
		at org.testcontainers.shaded.okhttp3.internal.http1.HeadersReader.readLine(HeadersReader.kt:29)
		at org.testcontainers.shaded.okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:178)
		... 39 more

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-OpenJDK-sts-nightly/24/

**Comment by olukas** [comment]
Failed again on _master_ with:
- oracle-11: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar-new/100/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectCouchbaseIntegrationTest/___/
- oracle-8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-OracleJDK8-nightly/943/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectCouchbaseIntegrationTest/___/

**Comment by olukas** [comment]
Failed again on _master_ with oracle-8: https://jenkins.hazelcast.com/job/Hazelcast-master-OracleJDK8-nightly/944/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectCouchbaseIntegrationTest/___/

**Comment by olukas** [comment]
Failed again on _master_ with oracle-11: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar-new/110/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectCouchbaseIntegrationTest/___/

**Comment by olukas** [comment]
Failed again on _master_ with oracle-11: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/122/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectCouchbaseIntegrationTest/___/

**Comment by olukas** [comment]
Failed again on _master_ with oracle-8 (force-offload): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-nightly-force-offload/47/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectCouchbaseIntegrationTest/___/

**Comment by olukas** [comment]
Failed again on _master_ with oracle-11 (force-offload): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-nightly-force-offload/49/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectCouchbaseIntegrationTest/___/

**Comment by sumnerib** [comment]
Failed again on _5.3.z_ with ibm-8: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-IbmJDK8-nightly/88/testReport/junit/com.hazelcast.jet.kafka.connect/KafkaConnectCouchbaseIntegrationTest/___/

**Comment by TomaszGaweda** [comment]
Related: https://github.com/testcontainers/testcontainers-java/issues/6938

**Comment by sumnerib** [comment]
Reopening as issue occurred again on: _5.3.z_ (commit c93e1cca30ac94ad008f27c300db5edc58b59954)
with ibm-8: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-IbmJDK8-nightly/118/testReport/junit/com.hazelcast.jet.kafka.connect/KafkaConnectCouchbaseIntegrationTest/___/
<details><summary>Stacktrace:</summary>

```
org.testcontainers.containers.ContainerLaunchException: Container startup failed for image couchbase/server:7.1.1
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:349)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322)
	at com.hazelcast.jet.kafka.connect.KafkaConnectCouchbaseIntegrationTest.setUpDocker(KafkaConnectCouchbaseIntegrationTest.java:89)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:41)
	at com.hazelcast.test.OverridePropertyRule$1.evaluate(OverridePropertyRule.java:66)
	at com.hazelcast.test.OverridePropertyRule$1.evaluate(OverridePropertyRule.java:66)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.lang.Thread.run(Thread.java:825)
Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:334)
	... 19 more
Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:553)
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:344)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
	... 20 more
Caused by: java.lang.RuntimeException: Could not perform request against couchbase HTTP endpoint 
	at org.testcontainers.couchbase.CouchbaseContainer.doHttpRequest(CouchbaseContainer.java:790)
	at org.testcontainers.couchbase.CouchbaseContainer.renameNode(CouchbaseContainer.java:400)
	at org.testcontainers.couchbase.CouchbaseContainer.timePhase(CouchbaseContainer.java:802)
	at org.testcontainers.couchbase.CouchbaseContainer.containerIsStarting(CouchbaseContainer.java:341)
	at org.testcontainers.containers.GenericContainer.containerIsStarting(GenericContainer.java:703)
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:479)
	... 22 more
Caused by: java.io.IOException: unexpected end of stream on http://172.17.0.1:46225/...
	at org.testcontainers.shaded.okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:202)
	at org.testcontainers.shaded.okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106)
	at org.testcontainers.shaded.okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79)
	at org.testcontainers.shaded.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at org.testcontainers.shaded.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
	at org.testcontainers.shaded.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at org.testcontainers.shaded.okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at org.testcontainers.shaded.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at org.testcontainers.shaded.okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at org.testcontainers.shaded.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at org.testcontainers.shaded.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at org.testcontainers.shaded.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at org.testcontainers.shaded.okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at org.testcontainers.shaded.okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at org.testcontainers.couchbase.CouchbaseContainer.doHttpRequest(CouchbaseContainer.java:788)
	... 27 more
	Suppressed: java.io.IOException: unexpected end of stream on http://172.17.0.1:46225/...
		... 42 more
	Caused by: java.io.EOFException: \n not found: limit=0 content=…
		at org.testcontainers.shaded.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:332)
		at org.testcontainers.shaded.okhttp3.internal.http1.HeadersReader.readLine(HeadersReader.kt:29)
		at org.testcontainers.shaded.okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:178)
		... 41 more
Caused by: java.io.EOFException: \n not found: limit=0 content=…
	at org.testcontainers.shaded.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:332)
	at org.testcontainers.shaded.okhttp3.internal.http1.HeadersReader.readLine(HeadersReader.kt:29)
	at org.testcontainers.shaded.okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:178)
	... 41 more

```
</details>

**Comment by Patras3** [comment]
Failed again on _5.3.z_ with openjdk-17: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-ZuluJDK17-nightly/99/testReport/junit/com.hazelcast.jet.kafka.connect/KafkaConnectCouchbaseIntegrationTest/___/

**Comment by olukas** [comment]
Failed again on _5.3.z_ with IbmJDK8-nightly: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-IbmJDK8-nightly/122/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectCouchbaseIntegrationTest/___/

**Comment by olukas** [comment]
Failed again on 5.3.z with IbmJDK8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-IbmJDK8-nightly/123/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectCouchbaseIntegrationTest/___/

**Comment by AleksPeychev** [comment]
Failed again on _5.3.z_ with openjdk-17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-ZuluJDK17-nightly/105/testReport/junit/com.hazelcast.jet.kafka.connect/KafkaConnectCouchbaseIntegrationTest/___/

**Comment by Patras3** [comment]
Failed again on _5.3.z_ with ibm-8: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-IbmJDK8-nightly/126/testReport/junit/com.hazelcast.jet.kafka.connect/KafkaConnectCouchbaseIntegrationTest/___/

**Comment by AleksPeychev** [comment]
Failed again on _5.3.z_ with ibm-8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-IbmJDK8-nightly/130/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectCouchbaseIntegrationTest/___/

**Comment by Patras3** [comment]
This comment was automatically generated to summarize test results for the last 90 days.

```

For branch: 5.3.z
Builds between : 2024-07-01 03:11 - 2024-07-01 03:11
Jobs: 1, Runs: 1, Passed: 0, Failed: 1, Skipped: 0, Fail Ratio: 100.00%
Run on:
+------------------------------------------------+
| JDK      | PASSED | FAILED | SKIPPED |  RATIO  |
+------------------------------------------------+
| oracle-8 |   0    |   1    |    0    | 100.00% |
+------------------------------------------------+

Builds Timeline:
2024-07-01 03:11 - FAILED (oracle-8):
    https://jenkins.hazelcast.com/job/Hazelcast-5.3.z-OracleJDK8-nightly/9/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectCouchbaseIntegrationTest/(?)/

----------------------------------------
```

More details can be generated here: [Run jenkins build (Click Proceed -> Back to previous page -> Click job name -> Find new build)](https://jenkins.hazelcast.com/job/test-failure-summary/buildWithParameters?TEST=com.hazelcast.jet.kafka.connect.KafkaConnectCouchbaseIntegrationTest.(?)&SINCE=90%20days%20ago%20at%20midnight)

**Comment by olukas** [comment]
Closing the test failure - it doesn't seem to be related to `master` or the latest maintenance stream `5.5.z`. Feel free to reopen test failure if it occurs on `master` or on the latest maintenance stream.
