### ISSUE TITLE
com.hazelcast.internal.partition.AntiEntropyCleanupTest.testCleanup [HZ-2360]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#24277]
_master_ (commit f7242148a89972cb339dbf927502859f3c2220dd)

Failed on oracle-11 (Sonar build): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar-new/101/testReport/com.hazelcast.internal.partition/AntiEntropyCleanupTest/testCleanup_nodeCount_1_/

Failed in variant `[nodeCount:1]`.

<details><summary>Stacktrace:</summary>

```
java.util.ConcurrentModificationException
	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1510)
	at java.base/java.util.HashMap$KeyIterator.next(HashMap.java:1533)
	at java.base/java.util.Collections$UnmodifiableCollection$1.next(Collections.java:1047)
	at com.hazelcast.internal.partition.AntiEntropyCleanupTest$1.run(AntiEntropyCleanupTest.java:85)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1288)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1392)
	at com.hazelcast.internal.partition.AntiEntropyCleanupTest.testCleanup(AntiEntropyCleanupTest.java:81)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-sonar-new/101/

**Comment by vbekiaris** [comment]
`PartitionReplicaVersions.getNamespaces()` returns an unmodifiable collection that is not safe to use for iteration, because changes to the backing collection will cause iterator to throw `ConcurrentModificationException`. Needs to be fixed in production and test code, but not a new regression in 5.3.0.

**Comment by olukas** [comment]
Closing the test failure - it hasn't failed in the last 3 months.
