### ISSUE TITLE
com.hazelcast.internal.partition.impl.PartitionStateGeneratorTest

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#24287]
_master_ (commit ba36217314220bbd9fa955ab82b7e4a4c9adb51b)

Failed on openj9-11: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Openj9-11/127/testReport/com.hazelcast.internal.partition.impl/PartitionStateGeneratorTest/testHostAwarePartitionStateGenerator/

Following tests failed:
- `testHostAwarePartitionStateGenerator`
- `testRandomPartitionGenerator`

<details><summary>Stacktrace:</summary>

```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.base/java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
	at org.mockito.internal.creation.bytebuddy.inject.MockMethodDispatcher.get(MockMethodDispatcher.java:38)
	at java.base/java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
	at org.mockito.internal.util.concurrent.WeakConcurrentMap.get(WeakConcurrentMap.java:57)
	at org.mockito.internal.util.concurrent.WeakConcurrentMap$WithInlinedExpunction.get(WeakConcurrentMap.java:259)
	at org.mockito.internal.util.concurrent.DetachedThreadLocal.get(DetachedThreadLocal.java:45)
	at org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.lambda$new$2(InlineByteBuddyMockMaker.java:251)
	at org.mockito.internal.creation.bytebuddy.MockMethodAdvice.isConstructorMock(MockMethodAdvice.java:220)
	at org.mockito.internal.creation.bytebuddy.inject.MockMethodDispatcher.isConstructorMock(MockMethodDispatcher.java:57)
	at java.base/java.util.concurrent.ConcurrentHashMap.<init>(ConcurrentHashMap.java)
	at com.hazelcast.cluster.impl.AbstractMember.<init>(AbstractMember.java:47)
	at com.hazelcast.cluster.impl.MemberImpl.<init>(MemberImpl.java:81)
	at com.hazelcast.cluster.impl.MemberImpl.<init>(MemberImpl.java:61)
	at com.hazelcast.internal.partition.impl.PartitionStateGeneratorTest.checkTestResult(PartitionStateGeneratorTest.java:347)
	at com.hazelcast.internal.partition.impl.PartitionStateGeneratorTest.test(PartitionStateGeneratorTest.java:246)
	at com.hazelcast.internal.partition.impl.PartitionStateGeneratorTest.testHostAwarePartitionStateGenerator(PartitionStateGeneratorTest.java:81)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:840)

```
</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: testConfigCustomPartitionStateGenerator in 53.592 seconds.

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-Openj9-11/127/

**Comment by ramizdundar** [comment]
This test failure is probably Mockito related.

- This test doesn't use mocking.
- It still fails due to mocked CHM in `AbstractMember`.
- I think mockito issue in another test somehow leaked to this one.

**Comment by vbekiaris** [comment]
Bumping to 5.4

**Comment by olukas** [comment]
Failed again on _5.3.z_ with ibm-8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-IbmJDK8/86/testReport/com.hazelcast.internal.partition.impl/PartitionStateGeneratorTest/

**Comment by olukas** [comment]
Failed again on _5.3.z_ with ibm-8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-IbmJDK8/109/testReport/com.hazelcast.internal.partition.impl/PartitionStateGeneratorTest/

**Comment by Patras3** [comment]
Failed again on _5.3.z_ with ibm-8: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-IbmJDK8/114/testReport/com.hazelcast.internal.partition.impl/PartitionStateGeneratorTest/

**Comment by Patras3** [comment]
Failed again on _5.3.z_ with openj9-11: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-Openj9-11/121/testReport/junit/com.hazelcast.internal.partition.impl/PartitionStateGeneratorTest/

**Comment by olukas** [comment]
Failed again on _5.3.z_ with IbmJDK8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-IbmJDK8/123/testReport/com.hazelcast.internal.partition.impl/PartitionStateGeneratorTest/

**Comment by Patras3** [comment]
Failed again on _5.3.z_ with ibm-8: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-IbmJDK8/126/testReport/com.hazelcast.internal.partition.impl/PartitionStateGeneratorTest/

**Comment by olukas** [comment]
Closing the test failure - it doesn't seem to be related to `master` or the latest maintenance stream `5.5.z` and it hasn't fail in the last 3 months. Feel free to reopen test failure if it occurs on `master` or on the latest maintenance stream.
