### ISSUE TITLE
The Future.set method can only be called once

### ISSUE THREAD

**Issue by dimas** [hazelcast/hazelcast#2429]
Sometimes I get

```
java.lang.IllegalStateException: Cannot get initial partitions!
    at com.hazelcast.client.spi.impl.ClientPartitionServiceImpl.getInitialPartitions(ClientPartitionServiceImpl.java:100)
    at com.hazelcast.client.spi.impl.ClientPartitionServiceImpl.start(ClientPartitionServiceImpl.java:60)
    at com.hazelcast.client.HazelcastClient.start(HazelcastClient.java:223)
    at com.hazelcast.client.HazelcastClient.newHazelcastClient(HazelcastClient.java:186)
    at com.alertme.zoo.service.test.HazelcastIT$HazelcastTask.connect(HazelcastIT.java:212)
    at com.alertme.zoo.service.test.HazelcastIT$BaseTask.run(HazelcastIT.java:156)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
    at java.util.concurrent.FutureTask.run(FutureTask.java:166)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:701)
```

and

```
Exception in thread "hz.client_414_dev.internal-2" java.lang.IllegalArgumentException: The Future.set method can only be called once
    at com.hazelcast.client.spi.impl.ClientCallFuture.setResponse(ClientCallFuture.java:131)
    at com.hazelcast.client.spi.impl.ClientCallFuture.notify(ClientCallFuture.java:125)
    at com.hazelcast.client.connection.nio.ClientConnection.cleanResources(ClientConnection.java:320)
    at com.hazelcast.client.connection.nio.ClientConnection.access$200(ClientConnection.java:55)
    at com.hazelcast.client.connection.nio.ClientConnection$CleanResourcesTask.run(ClientConnection.java:292)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:701)
    at com.hazelcast.util.executor.PoolExecutorThreadFactory$ManagedThread.run(PoolExecutorThreadFactory.java:59)
Exception in thread "hz.client_414_dev.cached-5" java.lang.IllegalArgumentException: The Future.set method can only be called once
    at com.hazelcast.client.spi.impl.ClientCallFuture.setResponse(ClientCallFuture.java:131)
    at com.hazelcast.client.spi.impl.ClientCallFuture.access$400(ClientCallFuture.java:42)
    at com.hazelcast.client.spi.impl.ClientCallFuture$ReSendTask.run(ClientCallFuture.java:232)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:701)
    at com.hazelcast.util.executor.PoolExecutorThreadFactory$ManagedThread.run(PoolExecutorThreadFactory.java:59)
```

2 clients were generating data against 2 node cluster (with backup-count=0)
Do not have reproducible test case yet, reporting as per Peter request on Skype.

**Comment by innokenty-shuvalov** [comment]
Hi, I'm facing a similar issue under version 3.5. I've got a 2-node cluster and two nodes that connect with a client. When I suddenly terminate one hazelcast node I get a huge amount of these warnings, last time it was 22940 in 1.5 hours to be precise. That is approximately 4.3 message a second. Can you please explain why can that possibly occur? I'm pretty sure, my application that uses the client doesn't make so many calls.

**Comment by innokenty** [comment]
Hmmm, ping? The issue is still there. Under v.3.5.

**Comment by sancar** [comment]
Hi, @innokenty Can you reproduce the problem with a small setup? We need more info to investigate further.
What kind of operations is client doing during the terminate of a node?
 And are you using any special configuration on client?

**Comment by sancar** [comment]
And if you can open a new issue related to your findings with your setup, it will be a lot easier to track.

**Comment by innokenty** [comment]
Okay, I'll try later. Client is pretty standard I believe, a normal Java-client. It performs a lot of tryLock/get/put/unlock/forceUnlock operation for map entries.
