### ISSUE TITLE
com.hazelcast.jet.kafka.connect.KafkaConnectCouchbaseIntegrationTest.testReading [HZ-3923]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#24290]
_master_ (commit ba36217314220bbd9fa955ab82b7e4a4c9adb51b)

Failed on zing-17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZingJDK17-nightly/21/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectCouchbaseIntegrationTest/testReading/
<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: Job was expected to complete with AssertionCompletedException, but completed with: com.hazelcast.jet.JetException: Exception in ProcessorTasklet{09b4-b762-1dc0-0001/assertCollectedEventually#0}: java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at com.hazelcast.jet.kafka.connect.KafkaConnectCouchbaseIntegrationTest.testReading(KafkaConnectCouchbaseIntegrationTest.java:145)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:891)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-ZingJDK17-nightly/21/

**Comment by olukas** [comment]
Failed again on _master_ with zing-8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZingJDK8-nightly/27/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectCouchbaseIntegrationTest/testReading/

**Comment by TomaszGaweda** [comment]
Does not happen anymore & there was a major rework, so it's likely that the issue is gone.
