### ISSUE TITLE
PublisherMetricsCollector IOException write beyond end of stream [HZ-2316]

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#24312]
new style of Error printed in member logs   ?

13:11:02 ERROR PublisherMetricsCollector [hz.sleepy_khayyam.cached.thread-23]:57 Error completing publication for publisher Job Metrics Publisher
java.lang.RuntimeException: java.io.IOException: write beyond end of stream
	at com.hazelcast.internal.metrics.impl.MetricsCompressor.getRenderedBlob(MetricsCompressor.java:369)
	at com.hazelcast.internal.metrics.impl.MetricsCompressor.getBlobAndReset(MetricsCompressor.java:272)
	at com.hazelcast.jet.impl.metrics.JobMetricsPublisher.whenComplete(JobMetricsPublisher.java:85)
	at com.hazelcast.internal.metrics.impl.PublisherMetricsCollector.publishCollectedMetrics(PublisherMetricsCollector.java:42)
	at com.hazelcast.internal.metrics.impl.MetricsService.collectMetrics(MetricsService.java:155)
	at com.hazelcast.spi.impl.executionservice.impl.DelegateAndSkipOnConcurrentExecutionDecorator$DelegateDecorator.run(DelegateAndSkipOnConcurrentExecutionDecorator.java:77)
	at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:111)
Caused by: java.io.IOException: write beyond end of stream
	at java.util.zip.DeflaterOutputStream.write(DeflaterOutputStream.java:201)
	at java.util.zip.DeflaterOutputStream.write(DeflaterOutputStream.java:188)
	at java.io.DataOutputStream.writeInt(DataOutputStream.java:197)
	at com.hazelcast.internal.metrics.impl.MetricsCompressor.writeDictionary(MetricsCompressor.java:289)
	at com.hazelcast.internal.metrics.impl.MetricsCompressor.getRenderedBlob(MetricsCompressor.java:365)

**Comment by k-jamroz** [comment]
caused by bug in #24225
