### ISSUE TITLE
com.hazelcast.jet.sql.impl.connector.jdbc.mysql.MySQLSchemaJdbcSqlConnectorTest [HZ-2353]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#24323]
_master_ (commit a7a5206ef973a8918db149f3050368a1262af093)

Failed on oracle-8: https://jenkins.hazelcast.com/job/Hazelcast-master-OracleJDK8-nightly/944/testReport/com.hazelcast.jet.sql.impl.connector.jdbc.mysql/MySQLSchemaJdbcSqlConnectorTest/

Following tests failed:
- `sinkIntoTableWithSchema[4: schemaName=schema1, tableName=table.with.dot, externalTableName="schema1"."table.with.dot"]`
- `deleteFromTableWithSchema[4: schemaName=schema1, tableName=table.with.dot, externalTableName="schema1"."table.with.dot"]`
- `updateTableWithSchema[4: schemaName=schema1, tableName=table.with.dot, externalTableName="schema1"."table.with.dot"]`
- `selectFromTableWithSchema[4: schemaName=schema1, tableName=table.with.dot, externalTableName="schema1"."table.with.dot"]`
- `insertIntoTableWithSchema[4: schemaName=schema1, tableName=table.with.dot, externalTableName="schema1"."table.with.dot"]`

<details><summary>Stacktrace:</summary>

```
com.hazelcast.sql.HazelcastSqlException: Could not execute readDbFields for table com.hazelcast.jet.sql.impl.connector.jdbc.JdbcSqlConnector$ExternalJdbcTableName@6a566a97
	at com.hazelcast.sql.impl.CoreQueryUtils.toPublicException(CoreQueryUtils.java:62)
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:221)
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:172)
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:168)
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:164)
	at com.hazelcast.sql.SqlService.execute(SqlService.java:89)
	at com.hazelcast.jet.sql.impl.connector.jdbc.JdbcSqlTestSupport.execute(JdbcSqlTestSupport.java:175)
	at com.hazelcast.jet.sql.impl.connector.jdbc.SchemaJdbcConnectorTest.myCreateMapping(SchemaJdbcConnectorTest.java:120)
	at com.hazelcast.jet.sql.impl.connector.jdbc.SchemaJdbcConnectorTest.sinkIntoTableWithSchema(SchemaJdbcConnectorTest.java:180)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37)
	at com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:104)
	at com.hazelcast.test.metrics.MetricsRule$1.evaluate(MetricsRule.java:63)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:41)
	at com.hazelcast.test.OverridePropertyRule$1.evaluate(OverridePropertyRule.java:66)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:750)
Caused by: com.hazelcast.core.HazelcastException: Could not execute readDbFields for table com.hazelcast.jet.sql.impl.connector.jdbc.JdbcSqlConnector$ExternalJdbcTableName@6a566a97
	at com.hazelcast.jet.sql.impl.connector.jdbc.JdbcSqlConnector.readDbFields(JdbcSqlConnector.java:151)
	at com.hazelcast.jet.sql.impl.connector.jdbc.JdbcSqlConnector.resolveAndValidateFields(JdbcSqlConnector.java:97)
	at com.hazelcast.jet.sql.impl.schema.TableResolverImpl.resolveMapping(TableResolverImpl.java:151)
	at com.hazelcast.jet.sql.impl.schema.TableResolverImpl.createMapping(TableResolverImpl.java:126)
	at com.hazelcast.jet.sql.impl.PlanExecutor.execute(PlanExecutor.java:169)
	at com.hazelcast.jet.sql.impl.SqlPlanImpl$CreateMappingPlan.execute(SqlPlanImpl.java:151)
	at com.hazelcast.sql.impl.SqlServiceImpl.query0(SqlServiceImpl.java:266)
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:204)
	... 46 more
Caused by: com.hazelcast.core.HazelcastException: Could not find table "schema1"."table.with.dot"
	at com.hazelcast.jet.sql.impl.connector.jdbc.JdbcSqlConnector.checkTableExists(JdbcSqlConnector.java:172)
	at com.hazelcast.jet.sql.impl.connector.jdbc.JdbcSqlConnector.readDbFields(JdbcSqlConnector.java:147)
	... 53 more

```
</details>

<details><summary>Standard output:</summary>

```
08:14:31,360  INFO || - [MySQLSchemaJdbcSqlConnectorTest] Time-limited test - Could not create schema
java.sql.SQLException: Can't create database 'schema1'; database exists
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:763) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:648) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.hazelcast.jet.sql.impl.connector.jdbc.JdbcSqlTestSupport.executeJdbc(JdbcSqlTestSupport.java:117) ~[test-classes/:?]
	at com.hazelcast.jet.sql.impl.connector.jdbc.SchemaJdbcConnectorTest.setUp(SchemaJdbcConnectorTest.java:103) [test-classes/:?]
	at sun.reflect.GeneratedMethodAccessor138.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_351]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_351]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59) [junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56) [junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33) [junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24) [junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27) [junit-4.13.2.jar:4.13.2]
	at com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37) [hazelcast-5.3.0-SNAPSHOT-tests.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:104) [hazelcast-5.3.0-SNAPSHOT-tests.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.test.metrics.MetricsRule$1.evaluate(MetricsRule.java:63) [hazelcast-5.3.0-SNAPSHOT-tests.jar:5.3.0-SNAPSHOT]
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.Suite.runChild(Suite.java:128) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.Suite.runChild(Suite.java:27) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293) [junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26) [junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27) [junit-4.13.2.jar:4.13.2]
	at com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:41) [hazelcast-5.3.0-SNAPSHOT-tests.jar:5.3.0-SNAPSHOT]
	at com.hazelcast.test.OverridePropertyRule$1.evaluate(OverridePropertyRule.java:66) [hazelcast-5.3.0-SNAPSHOT-tests.jar:5.3.0-SNAPSHOT]
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299) [junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293) [junit-4.13.2.jar:4.13.2]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_351]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_351]
08:14:31,416  INFO || - [SqlTestSupport] Time-limited test - Removing 0 cached plans in SqlTestSupport.@After
08:14:31,416  INFO || - [SqlTestSupport] Time-limited test - Removing 0 cached plans in SqlTestSupport.@After
08:14:31,417  INFO || - [SimpleTestInClusterSupport] Time-limited test - Ditching 0 jobs in SimpleTestInClusterSupport.@After: []
08:14:31,417  INFO || - [SimpleTestInClusterSupport] Time-limited test - Destroying 1 distributed objects in SimpleTestInClusterSupport.@After: [hz:impl:mapService/__sql.catalog]
BuildInfo right after sinkIntoTableWithSchema[4: schemaName=schema1, tableName=table.with.dot, externalTableName="schema1"."table.with.dot"](com.hazelcast.jet.sql.impl.connector.jdbc.mysql.MySQLSchemaJdbcSqlConnectorTest): BuildInfo{version='5.3.0-SNAPSHOT', build='20230419', buildNumber=20230419, revision=a7a5206, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'sinkIntoTableWithSchema[4: schemaName=schema1, tableName=table.with.dot, externalTableName="schema1"."table.with.dot"](com.hazelcast.jet.sql.impl.connector.jdbc.mysql.MySQLSchemaJdbcSqlConnectorTest):'
08:14:30, accumulated pauses: 12 ms, max pause: 0 ms, pauses over 1000 ms: 0


No metrics recorded during the test

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-OracleJDK8-nightly/944/

**Comment by olukas** [comment]
Failed again on _master_ with:
- oracle-8 (force-offload): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-nightly-force-offload/43/testReport/com.hazelcast.jet.sql.impl.connector.jdbc.mysql/MySQLSchemaJdbcSqlConnectorTest/
- openjdk-19: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-OpenJDK-sts-nightly/26/testReport/com.hazelcast.jet.sql.impl.connector.jdbc.mysql/MySQLSchemaJdbcSqlConnectorTest/
- oracle-8 (little-endian): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-nightly-little-endian/23/testReport/com.hazelcast.jet.sql.impl.connector.jdbc.mysql/MySQLSchemaJdbcSqlConnectorTest/
- openjdk-17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZuluJDK17-nightly/64/testReport/com.hazelcast.jet.sql.impl.connector.jdbc.mysql/MySQLSchemaJdbcSqlConnectorTest/

**Comment by olukas** [comment]
It seems it fails constantly.
