### ISSUE TITLE
com.hazelcast.internal.partition.GracefulShutdownTest got stuck [HZ-2368]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#24334]
_master_ (commit bdd14813949602290d6364d1ad9862194e740462)

Failed on OpenJDK 19: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-OpenJDK-sts/35/console

<details><summary>Standard output:</summary>

```
19:07:21 [INFO] Running com.hazelcast.internal.partition.GracefulShutdownTest
23:12:46 Build timed out (after 300 minutes). Marking the build as failed.
23:12:46 Stopping Docker container after build completion
23:12:48 Build was aborted
```

</details>

S3 Bucket for stdout: https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-OpenJDK-sts/35/

**Comment by arodionov** [comment]
"test timed out after 300000 milliseconds" at "shutdownMasterAndTerminateSlaveMember_concurrently"

**Comment by arodionov** [comment]
The following stack trace looks suspicious:

```
java.lang.Thread.State: WAITING, on lock=java.util.concurrent.locks.ReentrantLock$NonfairSync@5c8c56cd, cpu=36513862 nsecs, usr=20000000 nsecs, blocked=0 msecs, waited=300203 msecs
		at java.base@19.0.1/jdk.internal.misc.Unsafe.park(Native Method)
		at java.base@19.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:221)
		at java.base@19.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:715)
		at java.base@19.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:938)
		at java.base@19.0.1/java.util.concurrent.locks.ReentrantLock$Sync.lock(ReentrantLock.java:153)
		at java.base@19.0.1/java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:322)
		at java.base@19.0.1/java.lang.ref.ReferenceQueue.poll(ReferenceQueue.java:182)
		at app//org.mockito.internal.util.concurrent.WeakConcurrentMap.expungeStaleEntries(WeakConcurrentMap.java:130)
		at app//org.mockito.internal.util.concurrent.WeakConcurrentMap$WithInlinedExpunction.containsKey(WeakConcurrentMap.java:264)
		at app//org.mockito.internal.creation.bytebuddy.MockMethodAdvice.isMock(MockMethodAdvice.java:183)
		at app//org.mockito.internal.creation.bytebuddy.MockMethodAdvice.isMocked(MockMethodAdvice.java:188)
		at java.base@19.0.1/java.lang.Thread.isVirtual(Thread.java:1518) 
```

**Comment by arodionov** [comment]
I can guess that failure related to old Mockito behaviour on JDK 19

**Comment by olukas** [comment]
Closing the test failure - it doesn't seem to be related to `master` or the latest maintenance stream `5.5.z` and it hasn't fail in the last 3 months. Feel free to reopen test failure if it occurs on `master` or on the latest maintenance stream.
