### ISSUE TITLE
com.hazelcast.map.impl.mapstore.offload.MapStoreForceOffloadAllOperationTest.metrics_show_offloaded_operation_count_when_forced_offload_enabled [HZ-2331]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#24335]
_master_ (commit 39e432b6a492a6b1abd390e5fa397c9ed9d8fb8c)

Failed on openj9-17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Openj9-17/62/testReport/com.hazelcast.map.impl.mapstore.offload/MapStoreForceOffloadAllOperationTest/metrics_show_offloaded_operation_count_when_forced_offload_enabled/
<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at com.hazelcast.map.impl.mapstore.offload.MapStoreForceOffloadAllOperationTest.lambda$metrics_show_offloaded_operation_count_when_forced_offload_enabled$0(MapStoreForceOffloadAllOperationTest.java:86)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1288)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1392)
	at com.hazelcast.map.impl.mapstore.offload.MapStoreForceOffloadAllOperationTest.metrics_show_offloaded_operation_count_when_forced_offload_enabled(MapStoreForceOffloadAllOperationTest.java:81)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:858)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-Openj9-17/62/

**Comment by olukas** [comment]
Failed again on _master_ with Windows - MicrosoftJDK11: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Windows-MicrosoftJDK11/62/testReport/com.hazelcast.map.impl.mapstore.offload/MapStoreForceOffloadAllOperationTest/metrics_show_offloaded_operation_count_when_forced_offload_enabled/

**Comment by olukas** [comment]
Failed again on _master_ with:
- corretto-8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-CorrettoJDK8/225/testReport/com.hazelcast.map.impl.mapstore.offload/MapStoreForceOffloadAllOperationTest/metrics_show_offloaded_operation_count_when_forced_offload_enabled/
- Windows - MicrosoftJDK17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Windows-MicrosoftJDK17/60/testReport/com.hazelcast.map.impl.mapstore.offload/MapStoreForceOffloadAllOperationTest/metrics_show_offloaded_operation_count_when_forced_offload_enabled/
