### ISSUE TITLE
Job writing to JDBC sink using 2-phase commit failed with 'The XID already exists' after forceful termination of the node

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#24330]
Job `Dynamic-JdbcSinkTest` from snapshot-jdbc-test (https://github.com/hazelcast/hazelcast-jet-ansible-tests/tree/master/snapshot-jdbc-test) failed with `java.sql.SQLException: XAER_DUPID: The XID already exists`. It happened when one of node was terminated (node `10.0.0.21` in the logs). Server was configured to use forceful termination (`hazelcast.shutdownhook.policy=TERMINATE`). 

<details><summary>Stacktrace:</summary>

```
09:30:27,406 ERROR || - [MasterJobContext] hz.compassionate_bhaskara.cached.thread-22 - [10.0.0.146]:5701 [jet-isolated] [5.3.0-SNAPSHOT] Execution of job 'Dynamic-JdbcSinkTest', execution 09b9-2bbb-ebca-0002 failed
        Start time: 2023-04-18T09:30:27.165
        Duration: 00:00:00.241
        To see additional job metrics enable JobConfig.storeMetricsAfterJobCompletion
com.hazelcast.jet.JetException: Exception in ProcessorTasklet{Dynamic-JdbcSinkTest/jdbcSink#2}: com.mysql.cj.jdbc.MysqlXAException: XAER_DUPID: The XID already exists
        at com.hazelcast.jet.impl.execution.TaskletExecutionService.handleTaskletExecutionError(TaskletExecutionService.java:286) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at com.hazelcast.jet.impl.execution.TaskletExecutionService.access$600(TaskletExecutionService.java:80) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at com.hazelcast.jet.impl.execution.TaskletExecutionService$BlockingWorker.run(TaskletExecutionService.java:325) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_312]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_312]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_312]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_312]
        at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_312]
Caused by: com.mysql.cj.jdbc.MysqlXAException: XAER_DUPID: The XID already exists
        at com.mysql.cj.jdbc.MysqlXAConnection.mapXAExceptionFromSQLException(MysqlXAConnection.java:344) ~[hazelcast-jet-cdc-mysql-5.3.0-SNAPSHOT-jar-with-dependencies.jar:?]
        at com.mysql.cj.jdbc.MysqlXAConnection.dispatchCommand(MysqlXAConnection.java:329) ~[hazelcast-jet-cdc-mysql-5.3.0-SNAPSHOT-jar-with-dependencies.jar:?]
        at com.mysql.cj.jdbc.MysqlXAConnection.start(MysqlXAConnection.java:290) ~[hazelcast-jet-cdc-mysql-5.3.0-SNAPSHOT-jar-with-dependencies.jar:?]
        at com.hazelcast.jet.impl.connector.XaSinkProcessorBase$XaTransaction.begin(XaSinkProcessorBase.java:224) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at com.hazelcast.jet.impl.processor.TwoPhaseSnapshotCommitUtility$LoggingNonThrowingResource.begin(TwoPhaseSnapshotCommitUtility.java:383) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at com.hazelcast.jet.impl.processor.TransactionPoolSnapshotUtility.activeTransaction(TransactionPoolSnapshotUtility.java:131) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at com.hazelcast.jet.impl.connector.WriteJdbcP.process(WriteJdbcP.java:210) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at com.hazelcast.jet.impl.processor.ProcessorWrapper.process(ProcessorWrapper.java:97) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at com.hazelcast.jet.impl.pipeline.FunctionAdapter$AdaptingProcessor.process(FunctionAdapter.java:226) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at com.hazelcast.jet.impl.execution.ProcessorTasklet.lambda$processInbox$2f647568$2(ProcessorTasklet.java:490) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at com.hazelcast.jet.function.RunnableEx.run(RunnableEx.java:31) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at com.hazelcast.jet.impl.util.Util.doWithClassLoader(Util.java:532) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at com.hazelcast.jet.impl.execution.ProcessorTasklet.processInbox(ProcessorTasklet.java:490) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:341) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:336) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:328) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:291) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at com.hazelcast.jet.impl.execution.TaskletExecutionService$BlockingWorker.run(TaskletExecutionService.java:315) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        ... 5 more
Caused by: java.sql.SQLException: XAER_DUPID: The XID already exists
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129) ~[hazelcast-jet-cdc-mysql-5.3.0-SNAPSHOT-jar-with-dependencies.jar:?]
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[hazelcast-jet-cdc-mysql-5.3.0-SNAPSHOT-jar-with-dependencies.jar:?]
        at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:763) ~[hazelcast-jet-cdc-mysql-5.3.0-SNAPSHOT-jar-with-dependencies.jar:?]
        at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:648) ~[hazelcast-jet-cdc-mysql-5.3.0-SNAPSHOT-jar-with-dependencies.jar:?]
        at com.mysql.cj.jdbc.MysqlXAConnection.dispatchCommand(MysqlXAConnection.java:323) ~[hazelcast-jet-cdc-mysql-5.3.0-SNAPSHOT-jar-with-dependencies.jar:?]
        at com.mysql.cj.jdbc.MysqlXAConnection.start(MysqlXAConnection.java:290) ~[hazelcast-jet-cdc-mysql-5.3.0-SNAPSHOT-jar-with-dependencies.jar:?]
        at com.hazelcast.jet.impl.connector.XaSinkProcessorBase$XaTransaction.begin(XaSinkProcessorBase.java:224) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at com.hazelcast.jet.impl.processor.TwoPhaseSnapshotCommitUtility$LoggingNonThrowingResource.begin(TwoPhaseSnapshotCommitUtility.java:383) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at com.hazelcast.jet.impl.processor.TransactionPoolSnapshotUtility.activeTransaction(TransactionPoolSnapshotUtility.java:131) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at com.hazelcast.jet.impl.connector.WriteJdbcP.process(WriteJdbcP.java:210) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at com.hazelcast.jet.impl.processor.ProcessorWrapper.process(ProcessorWrapper.java:97) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at com.hazelcast.jet.impl.pipeline.FunctionAdapter$AdaptingProcessor.process(FunctionAdapter.java:226) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at com.hazelcast.jet.impl.execution.ProcessorTasklet.lambda$processInbox$2f647568$2(ProcessorTasklet.java:490) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at com.hazelcast.jet.function.RunnableEx.run(RunnableEx.java:31) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at com.hazelcast.jet.impl.util.Util.doWithClassLoader(Util.java:532) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at com.hazelcast.jet.impl.execution.ProcessorTasklet.processInbox(ProcessorTasklet.java:490) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:341) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:336) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:328) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:291) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at com.hazelcast.jet.impl.execution.TaskletExecutionService$BlockingWorker.run(TaskletExecutionService.java:315) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        ... 5 more

```
</details>

See attached logs for more details - [logs.zip](https://github.com/hazelcast/hazelcast/files/11284885/logs.zip)

**Comment by olukas** [comment]
`Dynamic-JdbcSinkTest` failed in the same scenario but with the different exception (`XAER_RMFAIL: The command cannot be executed when global transaction is in the  NON-EXISTING state`).

<details><summary>Stacktrace:</summary>

```
21:29:58,191 ERROR || - [MasterJobContext] hz.stupefied_clifford.cached.thread-17 - [10.0.0.91]:5701 [jet-isolated] [5.3.0-SNAPSHOT] Execution of job 'Dynamic-JdbcSinkTest', execution 09bc-6245-fafd-0001 failed
        Start time: 2023-04-20T21:29:57.975
        Duration: 00:00:00.216
        To see additional job metrics enable JobConfig.storeMetricsAfterJobCompletion
com.hazelcast.jet.JetException: Exception in ProcessorTasklet{Dynamic-JdbcSinkTest/jdbcSink#0}: com.hazelcast.jet.JetException: Failed to commit XID restored from the snapshot, XA error code: -7. Data loss is possible. Transaction ID: XaTransactionId{jobId=09bb-d864-c980-0001, jobNameHash=5057648937613316999, vertexIdHash=-3801245025844213929, processorIndex=0, transactionIndex=0}, cause: com.mysql.cj.jdbc.MysqlXAException: XAER_RMFAIL: The command cannot be executed when global transaction is in the  NON-EXISTING state
        at com.hazelcast.jet.impl.execution.TaskletExecutionService.handleTaskletExecutionError(TaskletExecutionService.java:286) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at com.hazelcast.jet.impl.execution.TaskletExecutionService.access$600(TaskletExecutionService.java:80) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at com.hazelcast.jet.impl.execution.TaskletExecutionService$BlockingWorker.run(TaskletExecutionService.java:325) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_312]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_312]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_312]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_312]
        at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_312]
Caused by: com.hazelcast.jet.JetException: Failed to commit XID restored from the snapshot, XA error code: -7. Data loss is possible. Transaction ID: XaTransactionId{jobId=09bb-d864-c980-0001, jobNameHash=5057648937613316999, vertexIdHash=-3801245025844213929, processorIndex=0, transactionIndex=0}, cause: com.mysql.cj.jdbc.MysqlXAException: XAER_RMFAIL: The command cannot be executed when global transaction is in the  NON-EXISTING state
        at com.hazelcast.jet.impl.connector.XaSinkProcessorBase.recoverTransaction(XaSinkProcessorBase.java:173) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at com.hazelcast.function.ConsumerEx.accept(ConsumerEx.java:47) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at com.hazelcast.jet.impl.processor.TransactionPoolSnapshotUtility.restoreFromSnapshot(TransactionPoolSnapshotUtility.java:241) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at com.hazelcast.jet.impl.processor.TwoPhaseSnapshotCommitUtility.restoreFromSnapshot(TwoPhaseSnapshotCommitUtility.java:178) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at com.hazelcast.jet.impl.connector.XaSinkProcessorBase.restoreFromSnapshot(XaSinkProcessorBase.java:109) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at com.hazelcast.jet.impl.processor.ProcessorWrapper.restoreFromSnapshot(ProcessorWrapper.java:142) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at com.hazelcast.jet.impl.execution.ProcessorTasklet.lambda$processInbox$2f647568$1(ProcessorTasklet.java:488) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at com.hazelcast.jet.function.RunnableEx.run(RunnableEx.java:31) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at com.hazelcast.jet.impl.util.Util.doWithClassLoader(Util.java:532) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at com.hazelcast.jet.impl.execution.ProcessorTasklet.processInbox(ProcessorTasklet.java:488) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:341) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:336) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:328) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:291) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at com.hazelcast.jet.impl.execution.TaskletExecutionService$BlockingWorker.run(TaskletExecutionService.java:315) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        ... 5 more
Caused by: com.mysql.cj.jdbc.MysqlXAException: XAER_RMFAIL: The command cannot be executed when global transaction is in the  NON-EXISTING state
        at com.mysql.cj.jdbc.MysqlXAConnection.mapXAExceptionFromSQLException(MysqlXAConnection.java:344) ~[hazelcast-jet-cdc-mysql-5.3.0-SNAPSHOT-jar-with-dependencies.jar:?]
        at com.mysql.cj.jdbc.MysqlXAConnection.dispatchCommand(MysqlXAConnection.java:329) ~[hazelcast-jet-cdc-mysql-5.3.0-SNAPSHOT-jar-with-dependencies.jar:?]
        at com.mysql.cj.jdbc.MysqlXAConnection.commit(MysqlXAConnection.java:306) ~[hazelcast-jet-cdc-mysql-5.3.0-SNAPSHOT-jar-with-dependencies.jar:?]
        at com.hazelcast.jet.impl.connector.XaSinkProcessorBase.recoverTransaction(XaSinkProcessorBase.java:143) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at com.hazelcast.function.ConsumerEx.accept(ConsumerEx.java:47) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at com.hazelcast.jet.impl.processor.TransactionPoolSnapshotUtility.restoreFromSnapshot(TransactionPoolSnapshotUtility.java:241) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at com.hazelcast.jet.impl.processor.TwoPhaseSnapshotCommitUtility.restoreFromSnapshot(TwoPhaseSnapshotCommitUtility.java:178) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at com.hazelcast.jet.impl.connector.XaSinkProcessorBase.restoreFromSnapshot(XaSinkProcessorBase.java:109) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at com.hazelcast.jet.impl.processor.ProcessorWrapper.restoreFromSnapshot(ProcessorWrapper.java:142) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at com.hazelcast.jet.impl.execution.ProcessorTasklet.lambda$processInbox$2f647568$1(ProcessorTasklet.java:488) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at com.hazelcast.jet.function.RunnableEx.run(RunnableEx.java:31) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at com.hazelcast.jet.impl.util.Util.doWithClassLoader(Util.java:532) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at com.hazelcast.jet.impl.execution.ProcessorTasklet.processInbox(ProcessorTasklet.java:488) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:341) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:336) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:328) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:291) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at com.hazelcast.jet.impl.execution.TaskletExecutionService$BlockingWorker.run(TaskletExecutionService.java:315) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        ... 5 more
Caused by: java.sql.SQLException: XAER_RMFAIL: The command cannot be executed when global transaction is in the  NON-EXISTING state
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129) ~[hazelcast-jet-cdc-mysql-5.3.0-SNAPSHOT-jar-with-dependencies.jar:?]
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[hazelcast-jet-cdc-mysql-5.3.0-SNAPSHOT-jar-with-dependencies.jar:?]
        at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:763) ~[hazelcast-jet-cdc-mysql-5.3.0-SNAPSHOT-jar-with-dependencies.jar:?]
        at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:648) ~[hazelcast-jet-cdc-mysql-5.3.0-SNAPSHOT-jar-with-dependencies.jar:?]
        at com.mysql.cj.jdbc.MysqlXAConnection.dispatchCommand(MysqlXAConnection.java:323) ~[hazelcast-jet-cdc-mysql-5.3.0-SNAPSHOT-jar-with-dependencies.jar:?]
        at com.mysql.cj.jdbc.MysqlXAConnection.commit(MysqlXAConnection.java:306) ~[hazelcast-jet-cdc-mysql-5.3.0-SNAPSHOT-jar-with-dependencies.jar:?]
        at com.hazelcast.jet.impl.connector.XaSinkProcessorBase.recoverTransaction(XaSinkProcessorBase.java:143) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at com.hazelcast.function.ConsumerEx.accept(ConsumerEx.java:47) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at com.hazelcast.jet.impl.processor.TransactionPoolSnapshotUtility.restoreFromSnapshot(TransactionPoolSnapshotUtility.java:241) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at com.hazelcast.jet.impl.processor.TwoPhaseSnapshotCommitUtility.restoreFromSnapshot(TwoPhaseSnapshotCommitUtility.java:178) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at com.hazelcast.jet.impl.connector.XaSinkProcessorBase.restoreFromSnapshot(XaSinkProcessorBase.java:109) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at com.hazelcast.jet.impl.processor.ProcessorWrapper.restoreFromSnapshot(ProcessorWrapper.java:142) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at com.hazelcast.jet.impl.execution.ProcessorTasklet.lambda$processInbox$2f647568$1(ProcessorTasklet.java:488) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at com.hazelcast.jet.function.RunnableEx.run(RunnableEx.java:31) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at com.hazelcast.jet.impl.util.Util.doWithClassLoader(Util.java:532) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at com.hazelcast.jet.impl.execution.ProcessorTasklet.processInbox(ProcessorTasklet.java:488) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:341) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:336) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:328) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:291) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        at com.hazelcast.jet.impl.execution.TaskletExecutionService$BlockingWorker.run(TaskletExecutionService.java:315) ~[hazelcast-enterprise-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
        ... 5 more
```
</details>

See attached logs for more details - [logs2.zip](https://github.com/hazelcast/hazelcast/files/11292686/logs2.zip)
