### ISSUE TITLE
com.hazelcast.jet.core.SplitBrainTest.when_splitBrainProtectionEnabledLater_then_jobDoesNotRestartOnMinority [HZ-2347]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#24344]
_master_ (commit b2b4e628040928f6c81146d0695114919c0cbffe)

Failed on oracle-8 (force-offload): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-nightly-force-offload/43/testReport/com.hazelcast.jet.core/SplitBrainTest/when_splitBrainProtectionEnabledLater_then_jobDoesNotRestartOnMinority/
<details><summary>Stacktrace:</summary>

```
org.junit.ComparisonFailure: expected:<[Quorum is absent]> but was:<[com.hazelcast.jet.core.TopologyChangedException: Causes from members: [[127.0.0.1]:5701=com.hazelcast.jet.impl.execution.ExecutionCancellationException: Member [127.0.0.1]:5702 - bbe02eaa-4dba-4378-a5c1-3e06c31b8316 has left cluster!, [127.0.0.1]:5702=com.hazelcast.core.MemberLeftException: Member [127.0.0.1]:5702 - bbe02eaa-4dba-4378-a5c1-3e06c31b8316 has left cluster!]]>
	at org.junit.Assert.assertEquals(Assert.java:117)
	at org.junit.Assert.assertEquals(Assert.java:146)
	at com.hazelcast.test.HazelcastTestSupport.lambda$assertEqualsEventually$10(HazelcastTestSupport.java:1055)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1288)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1392)
	at com.hazelcast.test.HazelcastTestSupport.assertEqualsEventually(HazelcastTestSupport.java:1055)
	at com.hazelcast.jet.core.SplitBrainTest.when_splitBrainProtectionEnabledLater_then_jobDoesNotRestartOnMinority(SplitBrainTest.java:426)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:750)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-nightly-force-offload/43/

**Comment by olukas** [comment]
Failed again on _master_ with:
- openjdk-19: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-OpenJDK-sts-nightly/26/testReport/com.hazelcast.jet.core/SplitBrainTest/when_splitBrainProtectionEnabledLater_then_jobDoesNotRestartOnMinority/
- oracle-8 (little-endian): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-nightly-little-endian/23/testReport/com.hazelcast.jet.core/SplitBrainTest/when_splitBrainProtectionEnabledLater_then_jobDoesNotRestartOnMinority/
- openjdk-17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZuluJDK17-nightly/64/testReport/com.hazelcast.jet.core/SplitBrainTest/when_splitBrainProtectionEnabledLater_then_jobDoesNotRestartOnMinority/
