### ISSUE TITLE
TpcSocketConfigTest.testClientPortDefaults

### ISSUE THREAD

**Issue by frant-hartm** [hazelcast/hazelcast#24350]
PR to master
https://github.com/hazelcast/hazelcast/pull/24318
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/17999/testReport/junit/com.hazelcast.config.tpc/TpcSocketConfigTest/testClientPortDefaults/

<details><summary>Stacktrace:</summary>

```
java.io.UncheckedIOException: Failed to bind to /127.0.0.1:11004
	at com.hazelcast.internal.tpcengine.nio.NioAsyncServerSocket.bind(NioAsyncServerSocket.java:106)
	at com.hazelcast.internal.tpcengine.net.AsyncServerSocket.bind(AsyncServerSocket.java:102)
	at com.hazelcast.internal.tpc.TpcServerBootstrap.bind(TpcServerBootstrap.java:273)
	at com.hazelcast.internal.tpc.TpcServerBootstrap.openServerSockets(TpcServerBootstrap.java:223)
	at com.hazelcast.internal.tpc.TpcServerBootstrap.start(TpcServerBootstrap.java:189)
	at com.hazelcast.spi.impl.NodeEngineImpl.start(NodeEngineImpl.java:289)
	at com.hazelcast.instance.impl.Node.start(Node.java:483)
	at com.hazelcast.instance.impl.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:124)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:217)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:196)
	at com.hazelcast.test.TestHazelcastInstanceFactory.newHazelcastInstance(TestHazelcastInstanceFactory.java:235)
	at com.hazelcast.test.HazelcastTestSupport.createHazelcastInstance(HazelcastTestSupport.java:254)
	at com.hazelcast.config.tpc.TpcSocketConfigTest.testClientPortDefaults(TpcSocketConfigTest.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.net.SocketException: Invalid argument
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:438)
	at sun.nio.ch.Net.bind(Net.java:430)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:225)
	at com.hazelcast.internal.tpcengine.nio.NioAsyncServerSocket.bind(NioAsyncServerSocket.java:104)
	... 24 more
```

</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: testEqualsAndHashCode in 0.046 seconds.
Started Running Test: testClientPortDefaults
10:18:20,155  INFO |testClientPortDefaults| - [MetricsConfigHelper] testClientPortDefaults - [LOCAL] [dev] [5.3.0-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
10:18:20,156  INFO |testClientPortDefaults| - [logo] testClientPortDefaults - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
10:18:20,156  INFO |testClientPortDefaults| - [system] testClientPortDefaults - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Copyright (c) 2008-2023, Hazelcast, Inc. All Rights Reserved.
10:18:20,156  INFO |testClientPortDefaults| - [system] testClientPortDefaults - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Hazelcast Platform 5.3.0-SNAPSHOT (20230420 - 80b8168) starting at [127.0.0.1]:5701
10:18:20,156  INFO |testClientPortDefaults| - [system] testClientPortDefaults - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Cluster name: dev
10:18:20,156  INFO |testClientPortDefaults| - [system] testClientPortDefaults - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed. For more information, see the documentation for Integrity Checker.
10:18:20,156  INFO |testClientPortDefaults| - [system] testClientPortDefaults - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Jet is enabled
10:18:20,162  INFO |testClientPortDefaults| - [MetricsConfigHelper] testClientPortDefaults - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
10:18:20,162  INFO |testClientPortDefaults| - [TpcServerBootstrap] testClientPortDefaults - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] TPC: enabled
10:18:20,177  WARN |testClientPortDefaults| - [CPSubsystem] testClientPortDefaults - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
10:18:20,207  INFO |testClientPortDefaults| - [JetServiceBackend] testClientPortDefaults - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Setting number of cooperative threads and default parallelism to 2
10:18:20,214  INFO |testClientPortDefaults| - [TpcServerBootstrap] testClientPortDefaults - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Starting TpcServerBootstrap
10:18:20,239  INFO |testClientPortDefaults| - [TpcEngine] testClientPortDefaults - Starting 4 reactors of type [NIO]
10:18:20,249  INFO |testClientPortDefaults| - [NioAsyncServerSocket] testClientPortDefaults - hz.TpcSocketConfigTest_sweet_allen.partition-operation.thread-0 Binding to /127.0.0.1:11000
10:18:20,253  INFO |testClientPortDefaults| - [NioAsyncServerSocket] testClientPortDefaults - hz.TpcSocketConfigTest_sweet_allen.partition-operation.thread-0 Binding to /127.0.0.1:11004
10:18:20,253  WARN |testClientPortDefaults| - [Node] testClientPortDefaults - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Terminating forcefully...
10:18:20,253  INFO |testClientPortDefaults| - [Node] testClientPortDefaults - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Shutting down connection manager...
10:18:20,253  INFO |testClientPortDefaults| - [Node] testClientPortDefaults - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Shutting down node engine...
10:18:20,258  INFO |testClientPortDefaults| - [TpcServerBootstrap] testClientPortDefaults - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] TpcServerBootstrap shutdown
10:18:20,260  INFO |testClientPortDefaults| - [NioAsyncServerSocket] hz.TpcSocketConfigTest_sweet_allen.partition-operation.thread-0 - Closing NioAsyncServerSocket[null] due to Reactor-1 is terminating.
10:18:20,260  INFO |testClientPortDefaults| - [NioReactor] hz.TpcSocketConfigTest_sweet_allen.partition-operation.thread-1 - hz.TpcSocketConfigTest_sweet_allen.partition-operation.thread-1 terminated
10:18:20,261  INFO |testClientPortDefaults| - [NioReactor] hz.TpcSocketConfigTest_sweet_allen.partition-operation.thread-2 - hz.TpcSocketConfigTest_sweet_allen.partition-operation.thread-2 terminated
10:18:20,261  INFO |testClientPortDefaults| - [NioReactor] hz.TpcSocketConfigTest_sweet_allen.partition-operation.thread-3 - hz.TpcSocketConfigTest_sweet_allen.partition-operation.thread-3 terminated
10:18:20,262  INFO |testClientPortDefaults| - [NioReactor] hz.TpcSocketConfigTest_sweet_allen.partition-operation.thread-0 - hz.TpcSocketConfigTest_sweet_allen.partition-operation.thread-0 terminated
10:18:20,262  INFO |testClientPortDefaults| - [TpcServerBootstrap] testClientPortDefaults - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] TpcServerBootstrap terminated
10:18:20,262  INFO |testClientPortDefaults| - [NodeExtension] testClientPortDefaults - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Destroying node NodeExtension.
10:18:20,262  INFO |testClientPortDefaults| - [Node] testClientPortDefaults - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Hazelcast Shutdown is completed in 9 ms.
BuildInfo right after testClientPortDefaults(com.hazelcast.config.tpc.TpcSocketConfigTest): BuildInfo{version='5.3.0-SNAPSHOT', build='20230420', buildNumber=20230420, revision=80b8168, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'testClientPortDefaults(com.hazelcast.config.tpc.TpcSocketConfigTest):'
10:18:20, accumulated pauses: 353 ms, max pause: 342 ms, pauses over 1000 ms: 0


No metrics recorded during the test
```

</details>

**Comment by olukas** [comment]
Closing the test failure - it doesn't seem to be related to `master` or the latest maintenance stream `5.5.z` and it hasn't fail in the last 3 months. Feel free to reopen test failure if it occurs on `master` or on the latest maintenance stream.
