### ISSUE TITLE
com.hazelcast.jet.core.SplitBrainTest.when_quorumIsLostOnMinority_then_jobDoesNotRestartOnMinorityAndCancelledAfterMerge [HZ-2346]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#24376]
_master_ (commit b2b4e628040928f6c81146d0695114919c0cbffe)

Failed on ibm-8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-IbmJDK8-nightly/101/testReport/com.hazelcast.jet.core/SplitBrainTest/when_quorumIsLostOnMinority_then_jobDoesNotRestartOnMinorityAndCancelledAfterMerge/
<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: 

Expecting
  <CompletableFutureTask[Completed: false]>
to be completed.
Be aware that the state of the future in this message might not reflect the one at the time when the assertion was performed as it is evaluated later on
	at com.hazelcast.jet.core.SplitBrainTest.lambda$when_quorumIsLostOnMinority_then_jobDoesNotRestartOnMinorityAndCancelledAfterMerge$6(SplitBrainTest.java:112)
	at com.hazelcast.jet.core.JetSplitBrainTestSupport.testSplitBrain(JetSplitBrainTestSupport.java:120)
	at com.hazelcast.jet.core.SplitBrainTest.when_quorumIsLostOnMinority_then_jobDoesNotRestartOnMinorityAndCancelledAfterMerge(SplitBrainTest.java:139)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.lang.Thread.run(Thread.java:825)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-IbmJDK8-nightly/101/

**Comment by vbekiaris** [comment]
build logs are missing from s3, no 101 folder under `Hazelcast-master-IbmJDK8-nightly`. Has this test failed again @olukas ?

**Comment by olukas** [comment]
@vbekiaris seems that log is missing in S3 because build was aborted (I'll take a look at it whether we can improve it). It didn't fail in the next run (however it can be common intermittent failure which fails time to time).
