### ISSUE TITLE
com.hazelcast.sql.impl.schema.IMapResolverTest.smokeTest

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#24411]
_master_ (commit 86db568380dcc4265fed490d2ed6d206895ee535)

Failed on openj9-17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Openj9-17/63/testReport/com.hazelcast.sql.impl.schema/IMapResolverTest/smokeTest/
<details><summary>Stacktrace:</summary>

```
java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.toString()" because "actual" is null
	at org.assertj.core.internal.Strings.normalizeNewlines(Strings.java:685)
	at org.assertj.core.internal.Strings.assertIsEqualToNormalizingNewlines(Strings.java:677)
	at org.assertj.core.api.AbstractCharSequenceAssert.isEqualToNormalizingNewlines(AbstractCharSequenceAssert.java:1796)
	at com.hazelcast.sql.impl.schema.IMapResolverTest.smokeTest(IMapResolverTest.java:63)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:858)

```
</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: testCompactSerialization in 0.026 seconds.
08:23:32,531  INFO |smokeTest| - [SqlTestSupport] Thread-1367 - Removing 0 cached plans in SqlTestSupport.@After
08:23:32,531  INFO |smokeTest| - [SimpleTestInClusterSupport] Thread-1367 - Ditching 0 jobs in SimpleTestInClusterSupport.@After: []
08:23:32,531  INFO |smokeTest| - [SimpleTestInClusterSupport] Thread-1367 - Destroying 0 distributed objects in SimpleTestInClusterSupport.@After: []
BuildInfo right after smokeTest(com.hazelcast.sql.impl.schema.IMapResolverTest): BuildInfo{version='5.3.0-SNAPSHOT', build='20230427', buildNumber=20230427, revision=86db568, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'smokeTest(com.hazelcast.sql.impl.schema.IMapResolverTest):'
08:23:30, accumulated pauses: 36 ms, max pause: 13 ms, pauses over 1000 ms: 0


No metrics recorded during the test

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-Openj9-17/63/

**Comment by olukas** [comment]
Failed again on _master_ with microsoft-11: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-MicrosoftJDK11/62/testReport/com.hazelcast.sql.impl.schema/IMapResolverTest/smokeTest/
