### ISSUE TITLE
com.hazelcast.dataconnection.impl.ListResourcesTest.shouldListResourcesDefaultAndNonDefaultSchema [HZ-2407]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#24414]
_master_ (commit a299ee144766053cc53c801241719e526d6a7ce4)

Failed on Windows - MicrosoftJDK11: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Windows-MicrosoftJDK11/63/testReport/com.hazelcast.dataconnection.impl/ListResourcesTest/

Failed in variants:
- `[provider == com.hazelcast.test.jdbc.PostgresDatabaseProvider@4a3516fd]`
- `[provider == com.hazelcast.test.jdbc.MySQLDatabaseProvider@3ba96967]`

<details><summary>Stacktrace:</summary>

```
java.lang.IllegalStateException: Could not find a valid Docker environment. Please see logs and check configuration
	at org.testcontainers.dockerclient.DockerClientProviderStrategy.lambda$getFirstValidStrategy$7(DockerClientProviderStrategy.java:256)
	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
	at org.testcontainers.dockerclient.DockerClientProviderStrategy.getFirstValidStrategy(DockerClientProviderStrategy.java:247)
	at org.testcontainers.DockerClientFactory.getOrInitializeStrategy(DockerClientFactory.java:150)
	at org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:186)
	at org.testcontainers.DockerClientFactory$1.getDockerClient(DockerClientFactory.java:104)
	at com.github.dockerjava.api.DockerClientDelegate.authConfig(DockerClientDelegate.java:109)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:321)
	at com.hazelcast.test.jdbc.PostgresDatabaseProvider.createDatabase(PostgresDatabaseProvider.java:35)
	at com.hazelcast.dataconnection.impl.ListResourcesTest.shouldListResourcesDefaultAndNonDefaultSchema(ListResourcesTest.java:84)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:829)

```
</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: shouldListResourcesDefaultAndNonDefaultSchema[provider == com.hazelcast.test.jdbc.H2DatabaseProvider@55c20a91] in 0.012 seconds.
Started Running Test: shouldListResourcesDefaultAndNonDefaultSchema[provider == com.hazelcast.test.jdbc.PostgresDatabaseProvider@4a3516fd]

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-Windows-MicrosoftJDK11/63/

**Comment by olukas** [comment]
Failed again on _master_ with Windows - OracleJDK8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Windows-OracleJDK8/445/testReport/com.hazelcast.dataconnection.impl/ListResourcesTest/

**Comment by olukas** [comment]
Failed again on _master_ with Windows - OracleJDK8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Windows-OracleJDK8/446/testReport/com.hazelcast.dataconnection.impl/ListResourcesTest/

**Comment by olukas** [comment]
Seems to fail constantly on Windows.
