### ISSUE TITLE
com.hazelcast.mapstore.GenericMapStoreIntegrationTest.testDestroy [HZ-2745]

### ISSUE THREAD

**Issue by kwart** [hazelcast/hazelcast#24428]
PR builder failed on `master`

https://jenkins.hazelcast.com/job/Hazelcast-pr-builder/18260/testReport/junit/com.hazelcast.mapstore/GenericMapStoreIntegrationTest/testDestroy/

<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: 

Expecting
  [Row{[__map-store.generic_testdestroy]},
    Row{[__map-store.generic_testget]},
    Row{[__map-store.generic_testloadallkeys_disabled]},
    Row{[__map-store.generic_testputall]},
    Row{[__map-store.generic_testremovewhenexistsintableonly]},
    Row{[__map-store.table_o_6de1375f_3c9e_425f_b195_25a327890e7d]}]
not to contain
  [Row{[__map-store.generic_testdestroy]}]
but found
  [Row{[__map-store.generic_testdestroy]}]

	at com.hazelcast.jet.sql.SqlTestSupport.assertDoesNotContainRow(SqlTestSupport.java:389)
	at com.hazelcast.mapstore.GenericMapStoreIntegrationTest.lambda$testDestroy$3(GenericMapStoreIntegrationTest.java:389)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1277)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1296)
	at com.hazelcast.mapstore.GenericMapStoreIntegrationTest.testDestroy(GenericMapStoreIntegrationTest.java:389)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:750)
```

</details>

<details><summary>Standard output:</summary>

```
Started Running Test: testDestroy
13:30:49,828 DEBUG || - [GenericMapLoader] hz.GenericMapStoreIntegrationTest_magical_cerf.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Initializing for map generic_testdestroy
13:30:49,828  INFO || - [DefaultRecordStore] hz.GenericMapStoreIntegrationTest_magical_cerf.partition-operation.thread-1 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Starting to load all keys for map generic_testdestroy on partitionId=1
13:30:49,862 DEBUG || - [GenericMapLoader] hz.GenericMapStoreIntegrationTest_confident_cerf.cached.thread-8 - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Initializing for map generic_testdestroy
13:30:49,865 DEBUG || - [GenericMapLoader] hz.GenericMapStoreIntegrationTest_confident_cerf.cached.thread-8 - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Reading existing mapping for mapgeneric_testdestroy
13:30:49,901  INFO || - [GenericMapLoader] hz.GenericMapStoreIntegrationTest_magical_cerf.cached.thread-13 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Dropping mapping __map-store.generic_testdestroy
13:30:49,901  INFO || - [GenericMapLoader] hz.GenericMapStoreIntegrationTest_confident_cerf.cached.thread-22 - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Dropping mapping __map-store.generic_testdestroy
13:30:49,903 DEBUG || - [GenericMapLoader] hz.GenericMapStoreIntegrationTest_magical_cerf.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Initializing for map generic_testdestroy
13:30:54,334 DEBUG || - [GenericMapLoader] hz.GenericMapStoreIntegrationTest_confident_cerf.cached.thread-18 - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Initializing for map generic_testget
13:30:54,374 DEBUG || - [GenericMapLoader] hz.GenericMapStoreIntegrationTest_magical_cerf.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Initializing for map generic_testget
13:30:54,378 DEBUG || - [GenericMapLoader] hz.GenericMapStoreIntegrationTest_magical_cerf.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Reading existing mapping for mapgeneric_testget
13:30:54,459 DEBUG || - [GenericMapLoader] hz.GenericMapStoreIntegrationTest_confident_cerf.cached.thread-17 - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Initializing for map table_o_6de1375f_3c9e_425f_b195_25a327890e7d
13:30:54,497 DEBUG || - [GenericMapLoader] hz.GenericMapStoreIntegrationTest_magical_cerf.cached.thread-9 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Initializing for map table_o_6de1375f_3c9e_425f_b195_25a327890e7d
13:30:54,501 DEBUG || - [GenericMapLoader] hz.GenericMapStoreIntegrationTest_magical_cerf.cached.thread-9 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Reading existing mapping for maptable_o_6de1375f_3c9e_425f_b195_25a327890e7d
13:30:54,588 DEBUG || - [GenericMapLoader] hz.GenericMapStoreIntegrationTest_magical_cerf.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Initializing for map generic_testloadallkeys_disabled
13:30:54,589 DEBUG || - [GenericMapLoader] hz.GenericMapStoreIntegrationTest_confident_cerf.cached.thread-5 - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Initializing for map generic_testloadallkeys_disabled
13:30:54,595 DEBUG || - [GenericMapLoader] hz.GenericMapStoreIntegrationTest_confident_cerf.cached.thread-5 - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Reading existing mapping for mapgeneric_testloadallkeys_disabled
13:30:54,642 DEBUG || - [GenericMapLoader] hz.GenericMapStoreIntegrationTest_confident_cerf.cached.thread-17 - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Initializing for map generic_testputall
13:30:54,681 DEBUG || - [GenericMapLoader] hz.GenericMapStoreIntegrationTest_magical_cerf.cached.thread-10 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Initializing for map generic_testputall
13:30:54,684 DEBUG || - [GenericMapLoader] hz.GenericMapStoreIntegrationTest_magical_cerf.cached.thread-10 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Reading existing mapping for mapgeneric_testputall
13:30:54,706 DEBUG || - [GenericMapLoader] hz.GenericMapStoreIntegrationTest_confident_cerf.cached.thread-19 - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Initializing for map generic_testremovewhenexistsintableonly
13:30:54,746 DEBUG || - [GenericMapLoader] hz.GenericMapStoreIntegrationTest_magical_cerf.cached.thread-13 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Initializing for map generic_testremovewhenexistsintableonly
13:30:54,751 DEBUG || - [GenericMapLoader] hz.GenericMapStoreIntegrationTest_magical_cerf.cached.thread-13 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Reading existing mapping for mapgeneric_testremovewhenexistsintableonly
13:31:20,535  INFO |testDestroy| - [SqlTestSupport] Time-limited test - Removing 0 cached plans in SqlTestSupport.@After
13:31:20,536  INFO |testDestroy| - [SqlTestSupport] Time-limited test - Removing 0 cached plans in SqlTestSupport.@After
13:31:20,537  INFO |testDestroy| - [SimpleTestInClusterSupport] Time-limited test - Ditching 0 jobs in SimpleTestInClusterSupport.@After: []
13:31:20,538  INFO |testDestroy| - [SimpleTestInClusterSupport] Time-limited test - Destroying 1 distributed objects in SimpleTestInClusterSupport.@After: [hz:impl:mapService/__sql.catalog]
BuildInfo right after testDestroy(com.hazelcast.mapstore.GenericMapStoreIntegrationTest): BuildInfo{version='5.3.0-SNAPSHOT', build='20230502', buildNumber=20230502, revision=69e67a0, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'testDestroy(com.hazelcast.mapstore.GenericMapStoreIntegrationTest):'
13:30:45, accumulated pauses: 100 ms, max pause: 41 ms, pauses over 1000 ms: 0
13:30:50, accumulated pauses: 47 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:30:55, accumulated pauses: 49 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:31:00, accumulated pauses: 47 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:31:05, accumulated pauses: 48 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:31:10, accumulated pauses: 50 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:31:15, accumulated pauses: 529 ms, max pause: 488 ms, pauses over 1000 ms: 0
13:31:20, accumulated pauses: 0 ms, max pause: 0 ms, pauses over 1000 ms: 0
```

</details>

**Comment by frant-hartm** [comment]
Destroy on IMaps doesn't have well-defined lifecycle anyway, so this has low priority. Moving to 5.4 cycle.

**Comment by Patras3** [comment]
Failed again on _master_ with corretto-17: https://jenkins.hazelcast.com/job/Hazelcast-master-CorrettoJDK17/97/testReport/junit/com.hazelcast.mapstore/GenericMapStoreIntegrationTest/testDestroy/

**Comment by frant-hartm** [comment]
Reproduced locally, the map gets re-created with the following stacktrace:

```
java.lang.RuntimeException
	at com.hazelcast.mapstore.GenericMapLoader.init(GenericMapLoader.java:171)
	at com.hazelcast.map.impl.MapStoreWrapper.init(MapStoreWrapper.java:87)
	at com.hazelcast.map.impl.mapstore.BasicMapStoreContext.callLifecycleSupportInit(BasicMapStoreContext.java:164)
	at com.hazelcast.map.impl.mapstore.BasicMapStoreContext.create(BasicMapStoreContext.java:137)
	at com.hazelcast.map.impl.mapstore.MapStoreContextFactory.createMapStoreContext(MapStoreContextFactory.java:48)
	at com.hazelcast.map.impl.MapContainer.<init>(MapContainer.java:150)
	at com.hazelcast.map.impl.MapServiceContextImpl.createMapContainer(MapServiceContextImpl.java:224)
	at com.hazelcast.map.impl.MapServiceContextImpl.lambda$createMapConstructor$0(MapServiceContextImpl.java:215)
	at com.hazelcast.internal.util.ConcurrencyUtil.getOrPutSynchronized(ConcurrencyUtil.java:140)
	at com.hazelcast.map.impl.MapServiceContextImpl.getMapContainer(MapServiceContextImpl.java:306)
	at com.hazelcast.map.impl.LocalMapStatsProvider.addIndexStats(LocalMapStatsProvider.java:353)
	at com.hazelcast.map.impl.LocalMapStatsProvider.createAllLocalMapStats(LocalMapStatsProvider.java:155)
	at com.hazelcast.map.impl.MapStatisticsAwareService.getStats(MapStatisticsAwareService.java:42)
	at com.hazelcast.map.impl.MapService.getStats(MapService.java:246)
	at com.hazelcast.map.impl.MapService.provideDynamicMetrics(MapService.java:318)
	at com.hazelcast.internal.metrics.impl.MetricsCollectionCycle.collectDynamicMetrics(MetricsCollectionCycle.java:94)
	at com.hazelcast.internal.metrics.impl.MetricsRegistryImpl.collect(MetricsRegistryImpl.java:320)
	at com.hazelcast.internal.metrics.impl.MetricsService.collectMetrics(MetricsService.java:160)
	at com.hazelcast.internal.metrics.impl.MetricsService.collectMetrics(MetricsService.java:154)
	at com.hazelcast.spi.impl.executionservice.impl.DelegateAndSkipOnConcurrentExecutionDecorator$DelegateDecorator.run(DelegateAndSkipOnConcurrentExecutionDecorator.java:77)
	at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:111)
```
