### ISSUE TITLE
com.hazelcast.jet.sql.impl.connector.jdbc.mysql.MySqlDownTest.showDataConnectionsShouldReturnQuickly [HZ-2384]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#24421]
_master_ (commit 61f6bc146d77e3c5117ef62574becf258b43f4fe)

Failed on ibm-8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-IbmJDK8-nightly/102/testReport/com.hazelcast.jet.sql.impl.connector.jdbc.mysql/MySqlDownTest/showDataConnectionsShouldReturnQuickly/
<details><summary>Stacktrace:</summary>

```
org.junit.ComparisonFailure: 

Expecting actual:
  [Row{[mysql, [Table]]}, Row{[testDatabaseRef, [Table]]}]
to contain exactly (and in same order):
  [Row{[mysql]}, Row{[testDatabaseRef]}]
but some elements were not found:
  [Row{[mysql]}, Row{[testDatabaseRef]}]
and others were not expected:
  [Row{[mysql, [Table]]}, Row{[testDatabaseRef, [Table]]}]
 expected:<[Row{[mysql[]}, Row{[testDatabaseRef]]}]> but was:<[Row{[mysql[, [Table]]}, Row{[testDatabaseRef, [Table]]]}]>
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:83)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:57)
	at com.hazelcast.jet.sql.impl.connector.jdbc.mysql.MySqlDownTest.showDataConnectionsShouldReturnQuickly(MySqlDownTest.java:93)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.lang.Thread.run(Thread.java:825)

```
</details>

<details><summary>Standard output:</summary>

```
09:22:25,507  INFO |showDataConnectionsShouldReturnQuickly| - [0] Time-limited test - Creating container for image: ghcr.io/shopify/toxiproxy:2.5.0
09:22:25,508  INFO |showDataConnectionsShouldReturnQuickly| - [RegistryAuthLocator] Time-limited test - Failure when attempting to lookup auth config. Please ignore if you don't have images in an authenticated registry. Details: (dockerImageName: ghcr.io/shopify/toxiproxy:2.5.0, configFile: /home/jenkins/.docker/config.json, configEnv: DOCKER_AUTH_CONFIG). Falling back to docker-java default behaviour. Exception message: Status 404: No config supplied. Checked in order: /home/jenkins/.docker/config.json (file not found), DOCKER_AUTH_CONFIG (not set)
09:22:25,567 DEBUG || - [JobCoordinationService] hz.MySqlDownTest_youthful_yonath.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
09:22:25,667 DEBUG || - [JobCoordinationService] hz.MySqlDownTest_youthful_yonath.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
09:22:25,767 DEBUG || - [JobCoordinationService] hz.MySqlDownTest_youthful_yonath.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
09:22:25,867 DEBUG || - [JobCoordinationService] hz.MySqlDownTest_youthful_yonath.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
09:22:25,967 DEBUG || - [JobCoordinationService] hz.MySqlDownTest_youthful_yonath.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
09:22:26,007  INFO |showDataConnectionsShouldReturnQuickly| - [0] Time-limited test - Container ghcr.io/shopify/toxiproxy:2.5.0 is starting: a59d71b4b601878a3fd04dd180b0a926ce65bba85940c2533eaa704a61738b7e
09:22:26,068 DEBUG || - [JobCoordinationService] hz.MySqlDownTest_youthful_yonath.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
09:22:26,168 DEBUG || - [JobCoordinationService] hz.MySqlDownTest_youthful_yonath.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
09:22:26,268 DEBUG || - [JobCoordinationService] hz.MySqlDownTest_youthful_yonath.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
09:22:26,368 DEBUG || - [JobCoordinationService] hz.MySqlDownTest_youthful_yonath.cached.thread-6 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
09:22:26,468 DEBUG || - [JobCoordinationService] hz.MySqlDownTest_youthful_yonath.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
09:22:26,568 DEBUG || - [JobCoordinationService] hz.MySqlDownTest_youthful_yonath.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
09:22:26,668 DEBUG || - [JobCoordinationService] hz.MySqlDownTest_youthful_yonath.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
09:22:26,769 DEBUG || - [JobCoordinationService] hz.MySqlDownTest_youthful_yonath.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
09:22:26,869 DEBUG || - [JobCoordinationService] hz.MySqlDownTest_youthful_yonath.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
09:22:26,969 DEBUG || - [JobCoordinationService] hz.MySqlDownTest_youthful_yonath.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
09:22:27,069 DEBUG || - [JobCoordinationService] hz.MySqlDownTest_youthful_yonath.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
09:22:27,170 DEBUG || - [JobCoordinationService] hz.MySqlDownTest_youthful_yonath.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
09:22:27,218  INFO |showDataConnectionsShouldReturnQuickly| - [HttpWaitStrategy] Time-limited test - /friendly_herschel: Waiting for 60 seconds for URL: http://172.17.0.1:54525/version (where port 54525 maps to container port 8474)
09:22:27,236  INFO |showDataConnectionsShouldReturnQuickly| - [0] Time-limited test - Container ghcr.io/shopify/toxiproxy:2.5.0 started in PT1.729S
09:22:27,270 DEBUG || - [JobCoordinationService] hz.MySqlDownTest_youthful_yonath.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
09:22:27,370 DEBUG || - [JobCoordinationService] hz.MySqlDownTest_youthful_yonath.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
09:22:27,373  INFO |showDataConnectionsShouldReturnQuickly| - [PartitionStateManager] showDataConnectionsShouldReturnQuickly - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Initializing cluster partition table arrangement...
09:22:27,379  INFO |showDataConnectionsShouldReturnQuickly| - [HikariDataSource] showDataConnectionsShouldReturnQuickly - HikariPool-26-mysql - Starting...
09:22:27,397  INFO |showDataConnectionsShouldReturnQuickly| - [HikariDataSource] showDataConnectionsShouldReturnQuickly - HikariPool-26-mysql - Start completed.
09:22:27,473 DEBUG || - [JobRepository] hz.MySqlDownTest_youthful_yonath.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Job cleanup took 0ms
09:22:29,350  INFO |showDataConnectionsShouldReturnQuickly| - [SqlTestSupport] Time-limited test - Removing 0 cached plans in SqlTestSupport.@After
09:22:29,350  INFO |showDataConnectionsShouldReturnQuickly| - [SqlTestSupport] Time-limited test - Removing 0 cached plans in SqlTestSupport.@After
09:22:29,351  INFO |showDataConnectionsShouldReturnQuickly| - [SimpleTestInClusterSupport] Time-limited test - Ditching 0 jobs in SimpleTestInClusterSupport.@After: []
09:22:29,352  INFO |showDataConnectionsShouldReturnQuickly| - [SimpleTestInClusterSupport] Time-limited test - Destroying 1 distributed objects in SimpleTestInClusterSupport.@After: [hz:impl:mapService/__sql.catalog]
BuildInfo right after showDataConnectionsShouldReturnQuickly(com.hazelcast.jet.sql.impl.connector.jdbc.mysql.MySqlDownTest): BuildInfo{version='5.3.0-SNAPSHOT', build='20230501', buildNumber=20230501, revision=61f6bc1, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'showDataConnectionsShouldReturnQuickly(com.hazelcast.jet.sql.impl.connector.jdbc.mysql.MySqlDownTest):'
09:22:25, accumulated pauses: 38 ms, max pause: 1 ms, pauses over 1000 ms: 0


No metrics recorded during the test

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-IbmJDK8-nightly/102/

**Comment by olukas** [comment]
Failed again on _master_ with:
- zing-8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZingJDK8-nightly/29/testReport/com.hazelcast.jet.sql.impl.connector.jdbc.mysql/MySqlDownTest/showDataConnectionsShouldReturnQuickly/
- oracle-8 (little-endian): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-nightly-little-endian/24/testReport/com.hazelcast.jet.sql.impl.connector.jdbc.mysql/MySqlDownTest/showDataConnectionsShouldReturnQuickly/
- ibm-8 in FIPS mode: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-IbmJDK8-fips-nightly/537/testReport/com.hazelcast.jet.sql.impl.connector.jdbc.mysql/MySqlDownTest/showDataConnectionsShouldReturnQuickly/
- oracle-8 (force-offload): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-nightly-force-offload/45/testReport/com.hazelcast.jet.sql.impl.connector.jdbc.mysql/MySqlDownTest/showDataConnectionsShouldReturnQuickly/
- openjdk-19: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-OpenJDK-sts-nightly/27/testReport/com.hazelcast.jet.sql.impl.connector.jdbc.mysql/MySqlDownTest/showDataConnectionsShouldReturnQuickly/

**Comment by olukas** [comment]
Reopening as issue (with slightly different exception) occurred again on _master_ (commit f1f6e5efe9ebf76a9ebc02b791d7bd77a4854426)
with oracle-8 (little-endian): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-nightly-little-endian/26/testReport/com.hazelcast.jet.sql.impl.connector.jdbc.mysql/MySqlDownTest/showDataConnectionsShouldReturnQuickly/

<details><summary>Stacktrace:</summary>

```
org.junit.ComparisonFailure: 

Expecting actual:
  [Row{[mysql, jdbc, ["Table"]]}, Row{[testDatabaseRef, jdbc, ["Table"]]}]
to contain exactly (and in same order):
  [Row{[mysql, Jdbc, ["Table"]]}, Row{[testDatabaseRef, jdbc, ["Table"]]}]
but some elements were not found:
  [Row{[mysql, Jdbc, ["Table"]]}]
and others were not expected:
  [Row{[mysql, jdbc, ["Table"]]}]
 expected:<[Row{[mysql, [J]dbc, ["Table"]]}, Ro...> but was:<[Row{[mysql, [j]dbc, ["Table"]]}, Ro...>
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at com.hazelcast.jet.sql.impl.connector.jdbc.mysql.MySqlDownTest.showDataConnectionsShouldReturnQuickly(MySqlDownTest.java:94)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:750)

```
</details>


<details><summary>Standard output:</summary>

```
05:25:54,488  INFO || - [0] Time-limited test - Creating container for image: ghcr.io/shopify/toxiproxy:2.5.0
05:25:54,488  INFO || - [RegistryAuthLocator] Time-limited test - Failure when attempting to lookup auth config. Please ignore if you don't have images in an authenticated registry. Details: (dockerImageName: ghcr.io/shopify/toxiproxy:2.5.0, configFile: /home/jenkins/.docker/config.json, configEnv: DOCKER_AUTH_CONFIG). Falling back to docker-java default behaviour. Exception message: Status 404: No config supplied. Checked in order: /home/jenkins/.docker/config.json (file not found), DOCKER_AUTH_CONFIG (not set)
05:25:54,546 DEBUG || - [JobCoordinationService] hz.MySqlDownTest_focused_blackwell.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
05:25:54,646 DEBUG || - [JobCoordinationService] hz.MySqlDownTest_focused_blackwell.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
05:25:54,746 DEBUG || - [JobCoordinationService] hz.MySqlDownTest_focused_blackwell.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
05:25:54,846 DEBUG || - [JobCoordinationService] hz.MySqlDownTest_focused_blackwell.cached.thread-1 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
05:25:54,946 DEBUG || - [JobCoordinationService] hz.MySqlDownTest_focused_blackwell.cached.thread-1 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
05:25:55,046 DEBUG || - [JobCoordinationService] hz.MySqlDownTest_focused_blackwell.cached.thread-1 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
05:25:55,146 DEBUG || - [JobCoordinationService] hz.MySqlDownTest_focused_blackwell.cached.thread-1 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
05:25:55,219  INFO || - [0] Time-limited test - Container ghcr.io/shopify/toxiproxy:2.5.0 is starting: b2790494a32b9e508ee7a0ec449888e0b8807d73d94e712ed2cbd60a2b0b4193
05:25:55,246 DEBUG || - [JobCoordinationService] hz.MySqlDownTest_focused_blackwell.cached.thread-1 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
05:25:55,346 DEBUG || - [JobCoordinationService] hz.MySqlDownTest_focused_blackwell.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
05:25:55,446 DEBUG || - [JobCoordinationService] hz.MySqlDownTest_focused_blackwell.cached.thread-1 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
05:25:55,546 DEBUG || - [JobCoordinationService] hz.MySqlDownTest_focused_blackwell.cached.thread-1 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
05:25:55,646 DEBUG || - [JobCoordinationService] hz.MySqlDownTest_focused_blackwell.cached.thread-1 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
05:25:55,746 DEBUG || - [JobCoordinationService] hz.MySqlDownTest_focused_blackwell.cached.thread-1 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
05:25:55,846 DEBUG || - [JobCoordinationService] hz.MySqlDownTest_focused_blackwell.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
05:25:55,946 DEBUG || - [JobCoordinationService] hz.MySqlDownTest_focused_blackwell.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
05:25:56,046 DEBUG || - [JobCoordinationService] hz.MySqlDownTest_focused_blackwell.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
05:25:56,147 DEBUG || - [JobCoordinationService] hz.MySqlDownTest_focused_blackwell.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
05:25:56,148  INFO || - [HttpWaitStrategy] Time-limited test - /funny_bassi: Waiting for 60 seconds for URL: http://172.17.0.1:57771/version (where port 57771 maps to container port 8474)
05:25:56,247 DEBUG || - [JobCoordinationService] hz.MySqlDownTest_focused_blackwell.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
05:25:56,347 DEBUG || - [JobCoordinationService] hz.MySqlDownTest_focused_blackwell.cached.thread-1 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
05:25:56,447 DEBUG || - [JobCoordinationService] hz.MySqlDownTest_focused_blackwell.cached.thread-1 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
05:25:56,548 DEBUG || - [JobCoordinationService] hz.MySqlDownTest_focused_blackwell.cached.thread-1 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
05:25:56,648 DEBUG || - [JobCoordinationService] hz.MySqlDownTest_focused_blackwell.cached.thread-1 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
05:25:56,748 DEBUG || - [JobCoordinationService] hz.MySqlDownTest_focused_blackwell.cached.thread-1 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
05:25:56,848 DEBUG || - [JobCoordinationService] hz.MySqlDownTest_focused_blackwell.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
05:25:56,949 DEBUG || - [JobCoordinationService] hz.MySqlDownTest_focused_blackwell.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
05:25:57,049 DEBUG || - [JobCoordinationService] hz.MySqlDownTest_focused_blackwell.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
05:25:57,149 DEBUG || - [JobCoordinationService] hz.MySqlDownTest_focused_blackwell.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
05:25:57,171  INFO || - [0] Time-limited test - Container ghcr.io/shopify/toxiproxy:2.5.0 started in PT2.684S
05:25:57,249 DEBUG || - [JobCoordinationService] hz.MySqlDownTest_focused_blackwell.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
05:25:57,334  INFO |showDataConnectionsShouldReturnQuickly| - [PartitionStateManager] showDataConnectionsShouldReturnQuickly - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Initializing cluster partition table arrangement...
05:25:57,345  INFO || - [HikariDataSource] showDataConnectionsShouldReturnQuickly - HikariPool-6-mysql - Starting...
05:25:57,351 DEBUG || - [JobRepository] hz.MySqlDownTest_focused_blackwell.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
05:25:57,359  INFO || - [HikariDataSource] showDataConnectionsShouldReturnQuickly - HikariPool-6-mysql - Start completed.
05:26:02,351 DEBUG || - [JobRepository] hz.MySqlDownTest_focused_blackwell.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
05:26:03,267  INFO |showDataConnectionsShouldReturnQuickly| - [SqlTestSupport] Time-limited test - Removing 0 cached plans in SqlTestSupport.@After
05:26:03,267  INFO |showDataConnectionsShouldReturnQuickly| - [SqlTestSupport] Time-limited test - Removing 0 cached plans in SqlTestSupport.@After
05:26:03,267  INFO |showDataConnectionsShouldReturnQuickly| - [SimpleTestInClusterSupport] Time-limited test - Ditching 0 jobs in SimpleTestInClusterSupport.@After: []
05:26:03,267  INFO |showDataConnectionsShouldReturnQuickly| - [SimpleTestInClusterSupport] Time-limited test - Destroying 1 distributed objects in SimpleTestInClusterSupport.@After: [hz:impl:mapService/__sql.catalog]
BuildInfo right after showDataConnectionsShouldReturnQuickly(com.hazelcast.jet.sql.impl.connector.jdbc.mysql.MySqlDownTest): BuildInfo{version='5.3.0-SNAPSHOT', build='20230512', buildNumber=20230512, revision=f1f6e5e, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'showDataConnectionsShouldReturnQuickly(com.hazelcast.jet.sql.impl.connector.jdbc.mysql.MySqlDownTest):'
05:25:50, accumulated pauses: 54 ms, max pause: 0 ms, pauses over 1000 ms: 0
05:25:55, accumulated pauses: 1348 ms, max pause: 1300 ms, pauses over 1000 ms: 1
05:26:00, accumulated pauses: 37 ms, max pause: 0 ms, pauses over 1000 ms: 0


No metrics recorded during the test

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-nightly-little-endian/26/

**Comment by olukas** [comment]
Failed again on _master_ with:
- zing-8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZingJDK8-nightly/31/testReport/com.hazelcast.jet.sql.impl.connector.jdbc.mysql/MySqlDownTest/showDataConnectionsShouldReturnQuickly/
- oracle-8 (force-offload): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-nightly-force-offload/47/testReport/com.hazelcast.jet.sql.impl.connector.jdbc.mysql/MySqlDownTest/showDataConnectionsShouldReturnQuickly/
- oracle-11 and MySQL 8.0: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-mysql-8.0/2/testReport/com.hazelcast.jet.sql.impl.connector.jdbc.mysql/MySqlDownTest/showDataConnectionsShouldReturnQuickly/

It seems to fail almost constantly (even locally).
