### ISSUE TITLE
com.hazelcast.cluster.JoinStressTest.testTCPIPJoinWithManyNodesMultipleGroups

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#24471]
_master_ (commit 57ad412834ac32d5b3ef022505a7266032b53521)

Failed on zing-17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZingJDK17-nightly/24/testReport/com.hazelcast.cluster/JoinStressTest/testTCPIPJoinWithManyNodesMultipleGroups/
<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertNotNull(Assert.java:713)
	at org.junit.Assert.assertNotNull(Assert.java:723)
	at com.hazelcast.cluster.JoinStressTest.testJoinWithManyNodesMultipleGroups(JoinStressTest.java:206)
	at com.hazelcast.cluster.JoinStressTest.testTCPIPJoinWithManyNodesMultipleGroups(JoinStressTest.java:159)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:891)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-ZingJDK17-nightly/24/

**Comment by arodionov** [comment]
Two members from the same group established the connection, but couldn't finish the joining process, because are blocked by CountDownLatch (for some unknown reason):

```
"pool-8623-thread-9" 
	java.lang.Thread.State: TIMED_WAITING, on lock=java.util.concurrent.CountDownLatch$Sync@3df8db5d, cpu=60142244 nsecs, usr=40000000 nsecs, blocked=0 msecs, waited=199720 msecs
		at java.base@17.0.4.1/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252)
		at java.base@17.0.4.1/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:717)
		at java.base@17.0.4.1/java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1074)
		at java.base@17.0.4.1/java.util.concurrent.CountDownLatch.await(CountDownLatch.java:276)
		at app//com.hazelcast.internal.cluster.impl.ClusterServiceImpl.blockOnJoin(ClusterServiceImpl.java:1098)
		at app//com.hazelcast.internal.cluster.impl.TcpIpJoiner.tryJoinAddresses(TcpIpJoiner.java:292)
		at app//com.hazelcast.internal.cluster.impl.TcpIpJoiner.joinViaPossibleMembers(TcpIpJoiner.java:159)
		at app//com.hazelcast.internal.cluster.impl.TcpIpJoiner.doJoin(TcpIpJoiner.java:112)
		at app//com.hazelcast.internal.cluster.impl.AbstractJoiner.join(AbstractJoiner.java:139)
		at app//com.hazelcast.instance.impl.Node.join(Node.java:912)
		at app//com.hazelcast.instance.impl.Node.start(Node.java:509)
		at app//com.hazelcast.instance.impl.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:124)
		at app//com.hazelcast.instance.impl.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:217)
		at app//com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:196)
		at app//com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:134)
		at app//com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:61)
		at app//com.hazelcast.cluster.JoinStressTest.lambda$testJoinWithManyNodesMultipleGroups$2(JoinStressTest.java:193)
		at app//com.hazelcast.cluster.JoinStressTest$$Lambda$lambda$testJoinWithManyNodesMultipleGroups$2$1259049636/0x0000000000012a56.run(Unknown Source)
		at java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
		at java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
		at java.base@17.0.4.1/java.lang.Thread.run(Thread.java:891)

"pool-8623-thread-8" 
	java.lang.Thread.State: TIMED_WAITING, on lock=java.util.concurrent.CountDownLatch$Sync@4632a5f6, cpu=33820135 nsecs, usr=20000000 nsecs, blocked=2 msecs, waited=199929 msecs
		at java.base@17.0.4.1/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252)
		at java.base@17.0.4.1/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:717)
		at java.base@17.0.4.1/java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1074)
		at java.base@17.0.4.1/java.util.concurrent.CountDownLatch.await(CountDownLatch.java:276)
		at app//com.hazelcast.internal.cluster.impl.ClusterServiceImpl.blockOnJoin(ClusterServiceImpl.java:1098)
		at app//com.hazelcast.internal.cluster.impl.TcpIpJoiner.tryJoinAddresses(TcpIpJoiner.java:292)
		at app//com.hazelcast.internal.cluster.impl.TcpIpJoiner.joinViaPossibleMembers(TcpIpJoiner.java:159)
		at app//com.hazelcast.internal.cluster.impl.TcpIpJoiner.doJoin(TcpIpJoiner.java:112)
		at app//com.hazelcast.internal.cluster.impl.AbstractJoiner.join(AbstractJoiner.java:139)
		at app//com.hazelcast.instance.impl.Node.join(Node.java:912)
		at app//com.hazelcast.instance.impl.Node.start(Node.java:509)
		at app//com.hazelcast.instance.impl.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:124)
		at app//com.hazelcast.instance.impl.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:217)
		at app//com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:196)
		at app//com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:134)
		at app//com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:61)
		at app//com.hazelcast.cluster.JoinStressTest.lambda$testJoinWithManyNodesMultipleGroups$2(JoinStressTest.java:193)
		at app//com.hazelcast.cluster.JoinStressTest$$Lambda$lambda$testJoinWithManyNodesMultipleGroups$2$1259049636/0x0000000000012a56.run(Unknown Source)
		at java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
		at java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
		at java.base@17.0.4.1/java.lang.Thread.run(Thread.java:891)
```

Also in the thread dump, there are leaked threads from previous tests (which should be fixed by https://github.com/hazelcast/hazelcast/pull/24528)

**Comment by arodionov** [comment]
Vassilis's comment:

> There is a known rare issue (since 3.x) with duplicate member-to-member connections being created roughly at the same time and it seems that we hit it in this test. Maybe also related to the build machine being very stressed - hiccups were 4930+ millis per each 5sec measurement bucket, so there was little room for the test to make much progress.

**Comment by olukas** [comment]
Closing the test failure - it doesn't seem to be related to `master` or the latest maintenance stream `5.5.z` and it hasn't fail in the last 3 months. Feel free to reopen test failure if it occurs on `master` or on the latest maintenance stream.
