### ISSUE TITLE
ASYNC_EXECUTOR thread leaks after node shutdown  [HZ-2414]

### ISSUE THREAD

**Issue by arodionov** [hazelcast/hazelcast#24484]
The thread-dump lists threads from the test that finished a couple of hours before.
`EnterpriseSystemLogPluginTest`, `TieredStoreMapSlowTest` and `TieredStoreMapTest` tests’ thread dumps contain the following thread:
```
"hz.HDClientTransactionalMapSplitBrainProtectionWriteTest_lucid_pike.async.thread-2" 
	java.lang.Thread.State: WAITING, on lock=java.util.concurrent.CompletableFuture$Signaller@24aac74, cpu=1370944 nsecs, usr=0 nsecs, blocked=0 msecs, waited=6268059 msecs
		at java.base@11.0.18/jdk.internal.misc.Unsafe.park(Native Method)
		at java.base@11.0.18/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
		at java.base@11.0.18/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1796)
		at java.base@11.0.18/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3128)
		at java.base@11.0.18/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1823)
		at java.base@11.0.18/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2043)
		at app//com.hazelcast.spi.impl.InternalCompletableFuture.joinInternal(InternalCompletableFuture.java:69)
		at app//com.hazelcast.internal.partition.operation.AbstractPartitionOperation.createNonFragmentedReplicationOperations(AbstractPartitionOperation.java:73)
		at app//com.hazelcast.internal.partition.operation.MigrationRequestOperation.createNonFragmentedReplicaFragmentMigrationState(MigrationRequestOperation.java:330)
		at app//com.hazelcast.internal.partition.operation.MigrationRequestOperation.createNextReplicaFragmentMigrationState(MigrationRequestOperation.java:265)
		at app//com.hazelcast.internal.partition.operation.MigrationRequestOperation.trySendNewFragment(MigrationRequestOperation.java:191)
		at app//com.hazelcast.internal.partition.operation.MigrationRequestOperation.access$900(MigrationRequestOperation.java:86)
		at app//com.hazelcast.internal.partition.operation.MigrationRequestOperation$MigrationCallback.lambda$accept$0(MigrationRequestOperation.java:441)
		at app//com.hazelcast.internal.partition.operation.MigrationRequestOperation$MigrationCallback$$Lambda$4569/0x0000000800ddbc40.run(Unknown Source)
		at java.base@11.0.18/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
		at java.base@11.0.18/java.util.concurrent.FutureTask.run(FutureTask.java:264)
		at java.base@11.0.18/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
		at java.base@11.0.18/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
		at java.base@11.0.18/java.lang.Thread.run(Thread.java:834)
		at app//com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
		at app//com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:111)
```
The test `HDClientTransactionalMapSplitBrainProtectionWriteTest` has been successfully passed a couple of hours before

_Originally posted by @arodionov in https://github.com/hazelcast/hazelcast-mono/issues/1567

**Comment by arodionov** [comment]
This behaviour could be reproduced by the following test:
```
HazelcastInstance hz = Hazelcast.newHazelcastInstance(config);

Node node = getNode(hz);
Future<?> submitted = node.getNodeEngine().getExecutionService().submit(ExecutionService.ASYNC_EXECUTOR,
        () -> { 
    InternalCompletableFuture<String> future = new InternalCompletableFuture<>();
    PartitionSpecificRunnable task = new PartitionSpecificRunnable() {
                @Override
                public void run() {
                    future.complete("X");
                }

                @Override
                public int getPartitionId() {
                    return -1;
                }
            };

           hz.shutdown();
           node.getNodeEngine().getOperationService().execute(task);
           future.joinInternal();
        });
assertTrueEventually(() -> assertTrue(submitted.isDone()));
```
