### ISSUE TITLE
com.hazelcast.jet.sql.impl.connector.jdbc.postgres.PostgresMappingJdbcSqlConnectorTest.when_dataConnectionIsDropped_then_cachedPlansAreInvalidated

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#24527]
_master_ (commit 816c4499514e0c87f67720599d00f5e797a175b7)

Failed on oracle-11 with Postgres 11.19: https://jenkins.hazelcast.com/view/JDBC/job/Hazelcast-master-postgres-11/1/testReport/com.hazelcast.jet.sql.impl.connector.jdbc.postgres/PostgresMappingJdbcSqlConnectorTest/when_dataConnectionIsDropped_then_cachedPlansAreInvalidated/
<details><summary>Stacktrace:</summary>

```
org.junit.ComparisonFailure: expected:<[1]> but was:<[0]>
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at com.hazelcast.jet.sql.impl.connector.jdbc.MappingJdbcSqlConnectorTest.when_dataConnectionIsDropped_then_cachedPlansAreInvalidated(MappingJdbcSqlConnectorTest.java:396)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)

```
</details>

<details><summary>Standard output:</summary>

```
12:02:19,160  INFO || - [ImageNameSubstitutor] Time-limited test - Image name substitution will be performed by: DefaultImageNameSubstitutor (composite of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitutor')
12:02:19,753  INFO || - [DockerClientProviderStrategy] Time-limited test - Found Docker environment with local Unix socket (unix:///var/run/docker.sock)
12:02:19,776  INFO || - [DockerClientFactory] Time-limited test - Docker host IP address is 172.17.0.1
12:02:19,792  INFO || - [DockerClientFactory] Time-limited test - Connected to docker: 
  Server Version: 20.10.22
  API Version: 1.41
  Operating System: Ubuntu 22.04.1 LTS
  Total Memory: 771157 MB
12:02:19,894  INFO || - [0] Time-limited test - Creating container for image: testcontainers/ryuk:0.4.0
12:02:19,899  INFO || - [RegistryAuthLocator] Time-limited test - Failure when attempting to lookup auth config. Please ignore if you don't have images in an authenticated registry. Details: (dockerImageName: testcontainers/ryuk:0.4.0, configFile: /home/jenkins/.docker/config.json, configEnv: DOCKER_AUTH_CONFIG). Falling back to docker-java default behaviour. Exception message: Status 404: No config supplied. Checked in order: /home/jenkins/.docker/config.json (file not found), DOCKER_AUTH_CONFIG (not set)
12:02:20,673  INFO || - [0] Time-limited test - Container testcontainers/ryuk:0.4.0 is starting: 1fc23c6477ce37c12462172d53e34a02d629b8939d9d779a37d9f94798f71cf3
12:02:21,324  INFO || - [0] Time-limited test - Container testcontainers/ryuk:0.4.0 started in PT1.523831S
12:02:21,331  INFO || - [RyukResourceReaper] Time-limited test - Ryuk started - will monitor and terminate Testcontainers containers on JVM exit
12:02:21,331  INFO || - [DockerClientFactory] Time-limited test - Checking the system...
12:02:21,331  INFO || - [DockerClientFactory] Time-limited test - ?? Docker server version should be at least 1.6.0
12:02:21,332  INFO || - [19-bullseye] Time-limited test - Creating container for image: postgres:11.19-bullseye
12:02:22,137  INFO || - [19-bullseye] Time-limited test - Container postgres:11.19-bullseye is starting: ffd131788ac47ef9fa4382e7f9af4e2f49e1157694000f15420fe0f33c341a66
12:02:25,789  INFO || - [19-bullseye] Time-limited test - Container postgres:11.19-bullseye started in PT4.456971S
12:02:25,790  INFO || - [19-bullseye] Time-limited test - Container is started (JDBC URL: jdbc:postgresql://172.17.0.1:55628/com.hazelcast.jet.sql.impl.connector.jdbc.JdbcSqlTestSupport?password=test&loggerLevel=OFF&user=test)
12:02:26,046  WARN || - [HazelcastInstanceFactory] Time-limited test - WARNING: Classpath misconfiguration: found multiple META-INF/services/com.hazelcast.instance.impl.NodeExtension resources: jar:file:/home/jenkins/.m2/repository/com/hazelcast/hazelcast/5.3.0-SNAPSHOT/hazelcast-5.3.0-SNAPSHOT.jar!/META-INF/services/com.hazelcast.instance.impl.NodeExtension, jar:file:/home/jenkins/.m2/repository/com/hazelcast/hazelcast/5.3.0-SNAPSHOT/hazelcast-5.3.0-SNAPSHOT-tests.jar!/META-INF/services/com.hazelcast.instance.impl.NodeExtension
12:02:26,159  INFO || - [MetricsConfigHelper] Time-limited test - [LOCAL] [dev] [5.3.0-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
12:02:26,192  INFO || - [logo] Time-limited test - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
12:02:26,192  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Copyright (c) 2008-2023, Hazelcast, Inc. All Rights Reserved.
12:02:26,192  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Hazelcast Platform 5.3.0-SNAPSHOT (20230511 - 816c449) starting at [127.0.0.1]:5701
12:02:26,192  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Cluster name: dev
12:02:26,192  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed. For more information, see the documentation for Integrity Checker.
12:02:26,193  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Jet is enabled
12:02:26,214  INFO || - [MetricsConfigHelper] Time-limited test - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
12:02:26,228  INFO || - [TpcServerBootstrap] Time-limited test - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] TPC: disabled
12:02:26,452  WARN || - [CPSubsystem] Time-limited test - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
12:02:26,667  INFO || - [JetServiceBackend] Time-limited test - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Setting number of cooperative threads and default parallelism to 2
12:02:26,741  INFO || - [Diagnostics] Time-limited test - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
12:02:26,748  INFO || - [LifecycleService] Time-limited test - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] [127.0.0.1]:5701 is STARTING
12:02:26,761  INFO || - [ClusterService] Time-limited test - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] 

Members {size:1, ver:1} [
	Member [127.0.0.1]:5701 - 8fa699cc-2aa4-4da9-8f9d-d24ac75d554e this
]

12:02:26,769  INFO || - [JobCoordinationService] Time-limited test - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Jet started scanning for jobs
12:02:26,770 DEBUG || - [JobCoordinationService] hz.PostgresMappingJdbcSqlConnectorTest_friendly_vaughan.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
12:02:26,772  INFO || - [LifecycleService] Time-limited test - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] [127.0.0.1]:5701 is STARTED
12:02:26,809  INFO || - [MetricsConfigHelper] Time-limited test - [LOCAL] [dev] [5.3.0-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
12:02:26,810  INFO || - [logo] Time-limited test - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
12:02:26,811  INFO || - [system] Time-limited test - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Copyright (c) 2008-2023, Hazelcast, Inc. All Rights Reserved.
12:02:26,811  INFO || - [system] Time-limited test - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Hazelcast Platform 5.3.0-SNAPSHOT (20230511 - 816c449) starting at [127.0.0.1]:5702
12:02:26,811  INFO || - [system] Time-limited test - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Cluster name: dev
12:02:26,811  INFO || - [system] Time-limited test - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed. For more information, see the documentation for Integrity Checker.
12:02:26,811  INFO || - [system] Time-limited test - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Jet is enabled
12:02:26,817  INFO || - [MetricsConfigHelper] Time-limited test - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
12:02:26,818  INFO || - [TpcServerBootstrap] Time-limited test - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] TPC: disabled
12:02:26,826  WARN || - [CPSubsystem] Time-limited test - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
12:02:26,833  INFO || - [JetServiceBackend] Time-limited test - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Setting number of cooperative threads and default parallelism to 2
12:02:26,835  INFO || - [Diagnostics] Time-limited test - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
12:02:26,835  INFO || - [LifecycleService] Time-limited test - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] [127.0.0.1]:5702 is STARTING
12:02:26,840  INFO || - [MockServer] Time-limited test - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Created connection to endpoint: [127.0.0.1]:5701-8fa699cc-2aa4-4da9-8f9d-d24ac75d554e, connection: MockConnection{localEndpoint=[address=[127.0.0.1]:5702, uuid=de70d42b-f5eb-4460-b721-f33a60701d81], remoteEndpoint=[address=[127.0.0.1]:5701, uuid=8fa699cc-2aa4-4da9-8f9d-d24ac75d554e], alive=true}
12:02:26,848  INFO || - [MockServer] hz.PostgresMappingJdbcSqlConnectorTest_friendly_vaughan.priority-generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Created connection to endpoint: [127.0.0.1]:5702-de70d42b-f5eb-4460-b721-f33a60701d81, connection: MockConnection{localEndpoint=[address=[127.0.0.1]:5701, uuid=8fa699cc-2aa4-4da9-8f9d-d24ac75d554e], remoteEndpoint=[address=[127.0.0.1]:5702, uuid=de70d42b-f5eb-4460-b721-f33a60701d81], alive=true}
12:02:26,851  INFO || - [ClusterService] hz.PostgresMappingJdbcSqlConnectorTest_friendly_vaughan.priority-generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] 

Members {size:2, ver:2} [
	Member [127.0.0.1]:5701 - 8fa699cc-2aa4-4da9-8f9d-d24ac75d554e this
	Member [127.0.0.1]:5702 - de70d42b-f5eb-4460-b721-f33a60701d81
]

12:02:26,869 DEBUG || - [JobCoordinationService] hz.PostgresMappingJdbcSqlConnectorTest_friendly_vaughan.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
12:02:26,956  INFO || - [ClusterService] hz.PostgresMappingJdbcSqlConnectorTest_sleepy_vaughan.priority-generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] 

Members {size:2, ver:2} [
	Member [127.0.0.1]:5701 - 8fa699cc-2aa4-4da9-8f9d-d24ac75d554e
	Member [127.0.0.1]:5702 - de70d42b-f5eb-4460-b721-f33a60701d81 this
]

12:02:26,959  INFO || - [JobCoordinationService] Time-limited test - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Jet started scanning for jobs
12:02:26,959  INFO || - [LifecycleService] Time-limited test - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] [127.0.0.1]:5702 is STARTED
Started Running Test: when_dataConnectionIsDropped_then_cachedPlansAreInvalidated
12:02:26,969 DEBUG || - [JobCoordinationService] hz.PostgresMappingJdbcSqlConnectorTest_friendly_vaughan.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
12:02:27,039  INFO |when_dataConnectionIsDropped_then_cachedPlansAreInvalidated| - [PartitionStateManager] when_dataConnectionIsDropped_then_cachedPlansAreInvalidated - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Initializing cluster partition table arrangement...
12:02:27,106 DEBUG || - [JobRepository] hz.PostgresMappingJdbcSqlConnectorTest_friendly_vaughan.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Job cleanup took 0ms
12:02:28,464 DEBUG |when_dataConnectionIsDropped_then_cachedPlansAreInvalidated| - [CalciteSqlOptimizer] when_dataConnectionIsDropped_then_cachedPlansAreInvalidated - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Before logical opt:
LogicalAggregate(group=[{}], EXPR$0=[COUNT()])
  LogicalTableScan(table=[[hazelcast, public, o_fcedb521_073f_405f_a1fd_5600e517372f[projects=[$0, $1]]]])

12:02:28,599 DEBUG |when_dataConnectionIsDropped_then_cachedPlansAreInvalidated| - [CalciteSqlOptimizer] when_dataConnectionIsDropped_then_cachedPlansAreInvalidated - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] After logical opt:
AggregateLogicalRel(group=[{}], EXPR$0=[COUNT()])
  FullScanLogicalRel(table=[[hazelcast, public, o_fcedb521_073f_405f_a1fd_5600e517372f[projects=[$0, $1]]]])

12:02:28,666 DEBUG |when_dataConnectionIsDropped_then_cachedPlansAreInvalidated| - [CalciteSqlOptimizer] when_dataConnectionIsDropped_then_cachedPlansAreInvalidated - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] After physical opt:
AggregateCombinePhysicalRel(group=[{}], EXPR$0=[COUNT()])
  AggregateAccumulatePhysicalRel
    FullScanPhysicalRel(table=[[hazelcast, public, o_fcedb521_073f_405f_a1fd_5600e517372f[projects=[$0, $1]]]], discriminator=[0])

12:02:28,750 DEBUG |when_dataConnectionIsDropped_then_cachedPlansAreInvalidated| - [LightMasterContext] when_dataConnectionIsDropped_then_cachedPlansAreInvalidated - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Start executing light job 09d6-eb18-c140-0001, execution graph in DOT format:
digraph DAG {
	"Select([o_fcedb521_073f_405f_a1fd_5600e517372f])" [localParallelism=1];
	"Accumulate" [localParallelism=2];
	"Combine" [localParallelism=1];
	"ClientSink" [localParallelism=1];
	"Select([o_fcedb521_073f_405f_a1fd_5600e517372f])" -> "Accumulate" [label="isolated", queueSize=1024];
	"Accumulate" -> "Combine" [label="distributed to [127.0.0.1]:5701-partitioned", queueSize=1024];
	"Combine" -> "ClientSink" [label="distributed to [127.0.0.1]:5701-partitioned", queueSize=1024];
}
HINT: You can use graphviz or http://viz-js.com to visualize the printed graph.
12:02:28,750 DEBUG |when_dataConnectionIsDropped_then_cachedPlansAreInvalidated| - [LightMasterContext] when_dataConnectionIsDropped_then_cachedPlansAreInvalidated - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Building execution plan for 09d6-eb18-c140-0001
12:02:28,768 DEBUG || - [LightMasterContext] hz.PostgresMappingJdbcSqlConnectorTest_friendly_vaughan.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Built execution plans for 09d6-eb18-c140-0001
12:02:28,783 DEBUG || - [InitExecutionOperation] hz.PostgresMappingJdbcSqlConnectorTest_friendly_vaughan.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Initializing execution plan for job 09d6-eb18-c140-0001, execution 09d6-eb18-c140-0001 from [127.0.0.1]:5701
12:02:28,866 DEBUG || - [JobExecutionService] hz.PostgresMappingJdbcSqlConnectorTest_friendly_vaughan.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Execution plan for light job ID=09d6-eb18-c140-0001, jobName='09d6-eb18-c140-0001', executionId=09d6-eb18-c140-0001 initialized, will start the execution
12:02:28,881 DEBUG || - [InitExecutionOperation] hz.PostgresMappingJdbcSqlConnectorTest_sleepy_vaughan.generic-operation.thread-1 - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Initializing execution plan for job 09d6-eb18-c140-0001, execution 09d6-eb18-c140-0001 from [127.0.0.1]:5701
12:02:28,890 DEBUG || - [JobExecutionService] hz.PostgresMappingJdbcSqlConnectorTest_sleepy_vaughan.cached.thread-1 - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Execution plan for light job ID=09d6-eb18-c140-0001, jobName='09d6-eb18-c140-0001', executionId=09d6-eb18-c140-0001 initialized, will start the execution
12:02:28,896 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-3 - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Completed execution of job '09d6-eb18-c140-0001', execution 09d6-eb18-c140-0001
12:02:28,896 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-3 - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Execution of job '09d6-eb18-c140-0001', execution 09d6-eb18-c140-0001 completed
12:02:28,897 DEBUG || - [JobExecutionService] hz.PostgresMappingJdbcSqlConnectorTest_friendly_vaughan.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Completed execution of job '09d6-eb18-c140-0001', execution 09d6-eb18-c140-0001
12:02:28,897 DEBUG || - [JobExecutionService] hz.PostgresMappingJdbcSqlConnectorTest_friendly_vaughan.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Execution of job '09d6-eb18-c140-0001', execution 09d6-eb18-c140-0001 completed
12:02:28,987  INFO |when_dataConnectionIsDropped_then_cachedPlansAreInvalidated| - [SqlTestSupport] Time-limited test - Removing 0 cached plans in SqlTestSupport.@After
12:02:28,989  INFO |when_dataConnectionIsDropped_then_cachedPlansAreInvalidated| - [SqlTestSupport] Time-limited test - Removing 0 cached plans in SqlTestSupport.@After
12:02:29,005  INFO |when_dataConnectionIsDropped_then_cachedPlansAreInvalidated| - [SimpleTestInClusterSupport] Time-limited test - Ditching 0 jobs in SimpleTestInClusterSupport.@After: []
12:02:29,006  INFO |when_dataConnectionIsDropped_then_cachedPlansAreInvalidated| - [SimpleTestInClusterSupport] Time-limited test - Destroying 2 distributed objects in SimpleTestInClusterSupport.@After: [hz:impl:mapService/__sql.catalog, hz:impl:flakeIdGeneratorService/__jet.ids]
BuildInfo right after when_dataConnectionIsDropped_then_cachedPlansAreInvalidated(com.hazelcast.jet.sql.impl.connector.jdbc.postgres.PostgresMappingJdbcSqlConnectorTest): BuildInfo{version='5.3.0-SNAPSHOT', build='20230511', buildNumber=20230511, revision=816c449, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'when_dataConnectionIsDropped_then_cachedPlansAreInvalidated(com.hazelcast.jet.sql.impl.connector.jdbc.postgres.PostgresMappingJdbcSqlConnectorTest):'
12:02:25, accumulated pauses: 96 ms, max pause: 46 ms, pauses over 1000 ms: 0


No metrics recorded during the test

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-postgres-11/1/

**Comment by frant-hartm** [comment]
Fixed by #24546
