### ISSUE TITLE
com.hazelcast.client.connectionstrategy.ConfiguredBehaviourTest.testAsyncStartTrueShouldNotBlock_whenThereIsClientStateToSend

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#24538]
_master_ (commit cce29cec0527e3d6051242b2dcb568050d0d9e8f)

Failed on corretto-17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-CorrettoJDK17/88/testReport/com.hazelcast.client.connectionstrategy/ConfiguredBehaviourTest/testAsyncStartTrueShouldNotBlock_whenThereIsClientStateToSend/
<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: CountDownLatch failed to complete within 120 seconds, count left: 1
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:1164)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:1149)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:1137)
	at com.hazelcast.client.connectionstrategy.ConfiguredBehaviourTest.testAsyncStartTrueShouldNotBlock_whenThereIsClientStateToSend(ConfiguredBehaviourTest.java:147)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)

```
</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: testReconnectModeASYNCTwoMembers in 2.415 seconds.
22:15:54,637  INFO |testAsyncStartTrueShouldNotBlock_whenThereIsClientStateToSend| - [LifecycleService] Thread-1291 - hz.client_786 [dev] [5.3.0-SNAPSHOT] HazelcastClient 5.3.0-SNAPSHOT (20230511 - cce29ce) is SHUTTING_DOWN
22:15:54,638  INFO |testAsyncStartTrueShouldNotBlock_whenThereIsClientStateToSend| - [ClientConnectionManager] Thread-1291 - hz.client_786 [dev] [5.3.0-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5701:55ba9d4e-1974-4076-ae17-825e687c82a0, connection: MockedClientConnection{localAddress=[127.0.0.1]:40002, super=ClientConnection{alive=false, connectionId=2, channel=null, remoteAddress=[127.0.0.1]:5701, lastReadTime=2023-05-11 22:15:54.625, lastWriteTime=2023-05-11 22:15:54.624, closedTime=2023-05-11 22:15:54.638}}
22:15:54,638  INFO |testAsyncStartTrueShouldNotBlock_whenThereIsClientStateToSend| - [ClientConnectionManager] Thread-1291 - hz.client_786 [dev] [5.3.0-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5702:8a319c45-9298-4f0e-9ef3-f3f73f44ca58, connection: MockedClientConnection{localAddress=[127.0.0.1]:40001, super=ClientConnection{alive=false, connectionId=1, channel=null, remoteAddress=[127.0.0.1]:5702, lastReadTime=2023-05-11 22:15:53.661, lastWriteTime=2023-05-11 22:15:48.665, closedTime=2023-05-11 22:15:54.638}}
22:15:54,638  INFO |testAsyncStartTrueShouldNotBlock_whenThereIsClientStateToSend| - [LifecycleService] Thread-1291 - hz.client_786 [dev] [5.3.0-SNAPSHOT] HazelcastClient 5.3.0-SNAPSHOT (20230511 - cce29ce) is CLIENT_DISCONNECTED
22:15:54,638  WARN |testAsyncStartTrueShouldNotBlock_whenThereIsClientStateToSend| - [TestClientRegistry$MockedServerConnection] pool-2783-thread-1 - Server connection closed: null
22:15:54,638  INFO |testAsyncStartTrueShouldNotBlock_whenThereIsClientStateToSend| - [MockServer] pool-2783-thread-1 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Removed connection to endpoint: [address=[127.0.0.1]:40002, uuid=cbbb5711-bc85-4efa-ad4c-6958133bd9a8], connection: MockedNodeConnection{ remoteAddress = [127.0.0.1]:40002, localAddress = [127.0.0.1]:5701, connectionId = 2}
22:15:54,639  INFO |testAsyncStartTrueShouldNotBlock_whenThereIsClientStateToSend| - [ClientEndpointManager] hz.ConfiguredBehaviourTest_pensive_gates.event-9977 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Destroying ClientEndpoint{connection=MockedNodeConnection{ remoteAddress = [127.0.0.1]:40002, localAddress = [127.0.0.1]:5701, connectionId = 2}, clientUuid=cbbb5711-bc85-4efa-ad4c-6958133bd9a8, clientName=hz.client_786, authenticated=true, clientVersion=5.3.0-SNAPSHOT, creationTime=1683843234660, latest clientAttributes=lastStatisticsCollectionTime=1683843353663,enterprise=false,clientType=JVM,clientVersion=5.3.0-SNAPSHOT,clusterConnectionTimestamp=1683843234659,clientAddress=127.0.0.1,clientName=hz.client_786,credentials.principal=null,os.committedVirtualMemorySize=32335745024,os.freePhysicalMemorySize=484272955392,os.freeSwapSpaceSize=8589930496,os.maxFileDescriptorCount=1048576,os.openFileDescriptorCount=348,os.processCpuTime=421400000000,os.systemLoadAverage=2.12,os.totalPhysicalMemorySize=810200530944,os.totalSwapSpaceSize=8589930496,runtime.availableProcessors=8,runtime.freeMemory=4232974384,runtime.maxMemory=8589934592,runtime.totalMemory=8589934592,runtime.uptime=662015,runtime.usedMemory=4356960208, labels=[]}
22:15:54,639  WARN |testAsyncStartTrueShouldNotBlock_whenThereIsClientStateToSend| - [TwoWayBlockableExecutor] pool-2783-thread-1 - Dropping incoming runnable since other end closed. Server Closed EOF. MockedClientConnection{localAddress=[127.0.0.1]:40002, super=ClientConnection{alive=false, connectionId=2, channel=null, remoteAddress=[127.0.0.1]:5701, lastReadTime=2023-05-11 22:15:54.625, lastWriteTime=2023-05-11 22:15:54.624, closedTime=2023-05-11 22:15:54.638}}
22:15:54,639  WARN |testAsyncStartTrueShouldNotBlock_whenThereIsClientStateToSend| - [TestClientRegistry$MockedServerConnection] pool-2773-thread-1 - Server connection closed: null
22:15:54,639  INFO |testAsyncStartTrueShouldNotBlock_whenThereIsClientStateToSend| - [MockServer] pool-2773-thread-1 - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Removed connection to endpoint: [address=[127.0.0.1]:40001, uuid=cbbb5711-bc85-4efa-ad4c-6958133bd9a8], connection: MockedNodeConnection{ remoteAddress = [127.0.0.1]:40001, localAddress = [127.0.0.1]:5702, connectionId = 1}
22:15:54,639  INFO |testAsyncStartTrueShouldNotBlock_whenThereIsClientStateToSend| - [ClientEndpointManager] hz.ConfiguredBehaviourTest_optimistic_gates.event-10013 - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Destroying ClientEndpoint{connection=MockedNodeConnection{ remoteAddress = [127.0.0.1]:40001, localAddress = [127.0.0.1]:5702, connectionId = 1}, clientUuid=cbbb5711-bc85-4efa-ad4c-6958133bd9a8, clientName=hz.client_786, authenticated=true, clientVersion=5.3.0-SNAPSHOT, creationTime=1683843233660, latest clientAttributes=lastStatisticsCollectionTime=1683843348663,enterprise=false,clientType=JVM,clientVersion=5.3.0-SNAPSHOT,clusterConnectionTimestamp=1683843233659,clientAddress=127.0.0.1,clientName=hz.client_786,credentials.principal=null,os.committedVirtualMemorySize=32335745024,os.freePhysicalMemorySize=484272181248,os.freeSwapSpaceSize=8589930496,os.maxFileDescriptorCount=1048576,os.openFileDescriptorCount=348,os.processCpuTime=420200000000,os.systemLoadAverage=2.13,os.totalPhysicalMemorySize=810200530944,os.totalSwapSpaceSize=8589930496,runtime.availableProcessors=8,runtime.freeMemory=4239807560,runtime.maxMemory=8589934592,runtime.totalMemory=8589934592,runtime.uptime=656056,runtime.usedMemory=4350127032, labels=[]}
22:15:54,639  WARN |testAsyncStartTrueShouldNotBlock_whenThereIsClientStateToSend| - [TwoWayBlockableExecutor] pool-2773-thread-1 - Dropping incoming runnable since other end closed. Server Closed EOF. MockedClientConnection{localAddress=[127.0.0.1]:40001, super=ClientConnection{alive=false, connectionId=1, channel=null, remoteAddress=[127.0.0.1]:5702, lastReadTime=2023-05-11 22:15:53.661, lastWriteTime=2023-05-11 22:15:48.665, closedTime=2023-05-11 22:15:54.638}}
22:15:54,640  INFO |testAsyncStartTrueShouldNotBlock_whenThereIsClientStateToSend| - [LifecycleService] Thread-1291 - hz.client_786 [dev] [5.3.0-SNAPSHOT] HazelcastClient 5.3.0-SNAPSHOT (20230511 - cce29ce) is SHUTDOWN
22:15:54,640  INFO |testAsyncStartTrueShouldNotBlock_whenThereIsClientStateToSend| - [LifecycleService] Thread-1291 - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] [127.0.0.1]:5702 is SHUTTING_DOWN
22:15:54,640  WARN |testAsyncStartTrueShouldNotBlock_whenThereIsClientStateToSend| - [Node] Thread-1291 - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Terminating forcefully...
22:15:54,641  INFO |testAsyncStartTrueShouldNotBlock_whenThereIsClientStateToSend| - [Node] Thread-1291 - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Shutting down connection manager...
22:15:54,641  INFO |testAsyncStartTrueShouldNotBlock_whenThereIsClientStateToSend| - [MockServer] Thread-1291 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Removed connection to endpoint: [address=[127.0.0.1]:5702, uuid=8a319c45-9298-4f0e-9ef3-f3f73f44ca58], connection: MockConnection{localEndpoint=[address=[127.0.0.1]:5701, uuid=55ba9d4e-1974-4076-ae17-825e687c82a0], remoteEndpoint=[address=[127.0.0.1]:5702, uuid=8a319c45-9298-4f0e-9ef3-f3f73f44ca58], alive=false}
22:15:54,641  INFO |testAsyncStartTrueShouldNotBlock_whenThereIsClientStateToSend| - [MockServer] Thread-1291 - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Removed connection to endpoint: [address=[127.0.0.1]:5701, uuid=55ba9d4e-1974-4076-ae17-825e687c82a0], connection: MockConnection{localEndpoint=[address=[127.0.0.1]:5702, uuid=8a319c45-9298-4f0e-9ef3-f3f73f44ca58], remoteEndpoint=[address=[127.0.0.1]:5701, uuid=55ba9d4e-1974-4076-ae17-825e687c82a0], alive=false}
22:15:54,641  INFO |testAsyncStartTrueShouldNotBlock_whenThereIsClientStateToSend| - [MembershipManager] Thread-1291 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Removing Member [127.0.0.1]:5702 - 8a319c45-9298-4f0e-9ef3-f3f73f44ca58
22:15:54,641  INFO |testAsyncStartTrueShouldNotBlock_whenThereIsClientStateToSend| - [ClusterService] Thread-1291 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] 

Members {size:1, ver:3} [
	Member [127.0.0.1]:5701 - 55ba9d4e-1974-4076-ae17-825e687c82a0 this
]

22:15:54,641  INFO |testAsyncStartTrueShouldNotBlock_whenThereIsClientStateToSend| - [Node] Thread-1291 - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Shutting down node engine...
22:15:54,642  INFO |testAsyncStartTrueShouldNotBlock_whenThereIsClientStateToSend| - [TransactionManagerService] hz.ConfiguredBehaviourTest_pensive_gates.cached.thread-9 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Committing/rolling-back live transactions of [127.0.0.1]:5702, UUID: 8a319c45-9298-4f0e-9ef3-f3f73f44ca58
22:15:54,645  INFO |testAsyncStartTrueShouldNotBlock_whenThereIsClientStateToSend| - [NodeExtension] Thread-1291 - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Destroying node NodeExtension.
22:15:54,645  INFO |testAsyncStartTrueShouldNotBlock_whenThereIsClientStateToSend| - [Node] Thread-1291 - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Hazelcast Shutdown is completed in 5 ms.
22:15:54,645  INFO |testAsyncStartTrueShouldNotBlock_whenThereIsClientStateToSend| - [LifecycleService] Thread-1291 - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] [127.0.0.1]:5702 is SHUTDOWN
22:15:54,645  INFO |testAsyncStartTrueShouldNotBlock_whenThereIsClientStateToSend| - [LifecycleService] Thread-1291 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
22:15:54,645  WARN |testAsyncStartTrueShouldNotBlock_whenThereIsClientStateToSend| - [Node] Thread-1291 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Terminating forcefully...
22:15:54,645  INFO |testAsyncStartTrueShouldNotBlock_whenThereIsClientStateToSend| - [Node] Thread-1291 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Shutting down connection manager...
22:15:54,645  INFO |testAsyncStartTrueShouldNotBlock_whenThereIsClientStateToSend| - [Node] Thread-1291 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Shutting down node engine...
22:15:54,648  INFO |testAsyncStartTrueShouldNotBlock_whenThereIsClientStateToSend| - [NodeExtension] Thread-1291 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Destroying node NodeExtension.
22:15:54,648  INFO |testAsyncStartTrueShouldNotBlock_whenThereIsClientStateToSend| - [Node] Thread-1291 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Hazelcast Shutdown is completed in 3 ms.
22:15:54,648  INFO |testAsyncStartTrueShouldNotBlock_whenThereIsClientStateToSend| - [LifecycleService] Thread-1291 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
BuildInfo right after testAsyncStartTrueShouldNotBlock_whenThereIsClientStateToSend(com.hazelcast.client.connectionstrategy.ConfiguredBehaviourTest): BuildInfo{version='5.3.0-SNAPSHOT', build='20230511', buildNumber=20230511, revision=cce29ce, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'testAsyncStartTrueShouldNotBlock_whenThereIsClientStateToSend(com.hazelcast.client.connectionstrategy.ConfiguredBehaviourTest):'
22:13:50, accumulated pauses: 54 ms, max pause: 3 ms, pauses over 1000 ms: 0
22:13:55, accumulated pauses: 55 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:14:00, accumulated pauses: 56 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:14:05, accumulated pauses: 56 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:14:10, accumulated pauses: 56 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:14:15, accumulated pauses: 57 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:14:20, accumulated pauses: 55 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:14:25, accumulated pauses: 56 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:14:30, accumulated pauses: 55 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:14:35, accumulated pauses: 55 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:14:40, accumulated pauses: 55 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:14:45, accumulated pauses: 56 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:14:50, accumulated pauses: 55 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:14:55, accumulated pauses: 55 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:15:00, accumulated pauses: 56 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:15:05, accumulated pauses: 56 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:15:10, accumulated pauses: 55 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:15:15, accumulated pauses: 56 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:15:20, accumulated pauses: 58 ms, max pause: 3 ms, pauses over 1000 ms: 0
22:15:25, accumulated pauses: 56 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:15:30, accumulated pauses: 54 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:15:35, accumulated pauses: 54 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:15:40, accumulated pauses: 53 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:15:45, accumulated pauses: 53 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:15:50, accumulated pauses: 996 ms, max pause: 952 ms, pauses over 1000 ms: 0


No metrics recorded during the test

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-CorrettoJDK17/88/

**Comment by olukas** [comment]
Failed again on _master_ with corretto-8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-CorrettoJDK8/228/testReport/com.hazelcast.client.connectionstrategy/ConfiguredBehaviourTest/testAsyncStartTrueShouldNotBlock_whenThereIsClientStateToSend/

**Comment by olukas** [comment]
Failed again on _5.3.0_ release branch with oracle-11 (sonar build): https://jenkins.hazelcast.com/view/Security%20and%20Compliance/job/Hazelcast-sonar-custom-branch/15/testReport/com.hazelcast.client.connectionstrategy/ConfiguredBehaviourTest/testAsyncStartTrueShouldNotBlock_whenThereIsClientStateToSend/
