### ISSUE TITLE
com.hazelcast.jet.sql_slow.SqlSlowIndexResolutionTest.testIndexResolution

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#24552]
_master_ (commit 2c4a58080658e67df87d0c2284fba037d8dbad38)

Failed on zing-17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZingJDK17-nightly/25/testReport/com.hazelcast.jet.sql_slow/SqlSlowIndexResolutionTest/

104 variant of `com.hazelcast.jet.sql_slow.SqlSlowIndexResolutionTest.testIndexResolution` failed.

<details><summary>Stacktrace:</summary>

```
java.lang.IllegalArgumentException: The given HazelcastInstance is not an active HazelcastInstanceImpl: class com.hazelcast.instance.impl.HazelcastInstanceProxy
	at com.hazelcast.instance.impl.TestUtil.getHazelcastInstanceImpl(TestUtil.java:109)
	at com.hazelcast.instance.impl.TestUtil.getNode(TestUtil.java:83)
	at com.hazelcast.test.Accessors.getNode(Accessors.java:64)
	at com.hazelcast.test.PacketFiltersUtil.getConnectionManager(PacketFiltersUtil.java:47)
	at com.hazelcast.test.PacketFiltersUtil.resetPacketFiltersFrom(PacketFiltersUtil.java:52)
	at com.hazelcast.jet.SimpleTestInClusterSupport.supportAfter(SimpleTestInClusterSupport.java:106)
	at jdk.internal.reflect.GeneratedMethodAccessor102.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:381)
	at com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37)
	at com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:104)
	at com.hazelcast.test.metrics.MetricsRule$1.evaluate(MetricsRule.java:63)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at com.hazelcast.test.HazelcastParallelClassRunner.access$301(HazelcastParallelClassRunner.java:49)
	at com.hazelcast.test.HazelcastParallelClassRunner$TestRunner.run(HazelcastParallelClassRunner.java:162)
	at java.base/java.lang.Thread.run(Thread.java:891)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-ZingJDK17-nightly/25/

**Comment by olukas** [comment]
Failed again on _master_ with zing-17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZingJDK17-nightly/26/testReport/com.hazelcast.jet.sql_slow/SqlSlowIndexResolutionTest/

**Comment by olukas** [comment]
Failed again on _master_ with zing-17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZingJDK17-nightly/30/testReport/com.hazelcast.jet.sql_slow/SqlSlowIndexResolutionTest/

**Comment by Patras3** [comment]
Failed again on _master_ with zing-17: https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK17-nightly/34/testReport/com.hazelcast.jet.sql_slow/SqlSlowIndexResolutionTest/

**Comment by k-jamroz** [comment]
First failure was caused by https://github.com/hazelcast/hazelcast/issues/24862#issuecomment-1724042722, I assume others also.

**Comment by k-jamroz** [comment]
Checked the last - the same cause.
