### ISSUE TITLE
com.hazelcast.internal.tpcengine.nio.NioAsyncServerSocketOptionsTest.test_set [HZ-2543]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#24663]
_master_ (commit cc01fe64c531ff21a260e29db43c8598521ef694)

Failed on Windows - MicrosoftJDK11: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Windows-MicrosoftJDK11/67/testReport/com.hazelcast.internal.tpcengine.nio/NioAsyncServerSocketOptionsTest/test_set/
<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at com.hazelcast.internal.tpcengine.net.AsyncServerSocketOptionsTest.test_set(AsyncServerSocketOptionsTest.java:76)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:49)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:120)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:95)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:69)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:146)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)

```
</details>

<details><summary>Standard output:</summary>

```
May 25, 2023 6:07:32 PM com.hazelcast.internal.tpcengine.logging.JulLoggerFactory$JulLogger info
INFO: Closing NioAsyncServerSocket[null] due to Reactor-1 is terminating.
May 25, 2023 6:07:32 PM com.hazelcast.internal.tpcengine.logging.JulLoggerFactory$JulLogger info
INFO: Thread-9 terminated
May 25, 2023 6:07:32 PM com.hazelcast.internal.tpcengine.logging.JulLoggerFactory$JulLogger info
INFO: Closing NioAsyncServerSocket[null] due to Reactor-1 is terminating.
May 25, 2023 6:07:32 PM com.hazelcast.internal.tpcengine.logging.JulLoggerFactory$JulLogger info
INFO: Thread-10 terminated
May 25, 2023 6:07:32 PM com.hazelcast.internal.tpcengine.logging.JulLoggerFactory$JulLogger info
INFO: Closing NioAsyncServerSocket[null] due to Reactor-1 is terminating.
May 25, 2023 6:07:32 PM com.hazelcast.internal.tpcengine.logging.JulLoggerFactory$JulLogger info
INFO: Thread-11 terminated
May 25, 2023 6:07:32 PM com.hazelcast.internal.tpcengine.logging.JulLoggerFactory$JulLogger info
INFO: Closing NioAsyncServerSocket[null] due to Reactor-1 is terminating.
May 25, 2023 6:07:32 PM com.hazelcast.internal.tpcengine.logging.JulLoggerFactory$JulLogger info
INFO: Thread-12 terminated
May 25, 2023 6:07:32 PM com.hazelcast.internal.tpcengine.logging.JulLoggerFactory$JulLogger info
INFO: Closing NioAsyncServerSocket[null] due to Reactor-1 is terminating.
May 25, 2023 6:07:32 PM com.hazelcast.internal.tpcengine.logging.JulLoggerFactory$JulLogger info
INFO: Thread-13 terminated
May 25, 2023 6:07:32 PM com.hazelcast.internal.tpcengine.logging.JulLoggerFactory$JulLogger info
INFO: Closing NioAsyncServerSocket[null] due to Reactor-1 is terminating.
May 25, 2023 6:07:32 PM com.hazelcast.internal.tpcengine.logging.JulLoggerFactory$JulLogger info
INFO: Thread-14 terminated
May 25, 2023 6:07:32 PM com.hazelcast.internal.tpcengine.logging.JulLoggerFactory$JulLogger info
INFO: Closing NioAsyncServerSocket[null] due to Reactor-1 is terminating.
May 25, 2023 6:07:32 PM com.hazelcast.internal.tpcengine.logging.JulLoggerFactory$JulLogger info
INFO: Thread-15 terminated
May 25, 2023 6:07:32 PM com.hazelcast.internal.tpcengine.logging.JulLoggerFactory$JulLogger info
INFO: Closing NioAsyncServerSocket[null] due to Reactor-1 is terminating.
May 25, 2023 6:07:32 PM com.hazelcast.internal.tpcengine.logging.JulLoggerFactory$JulLogger info
INFO: Thread-16 terminated
May 25, 2023 6:07:32 PM com.hazelcast.internal.tpcengine.logging.JulLoggerFactory$JulLogger info
INFO: Closing NioAsyncServerSocket[null] due to Reactor-1 is terminating.
May 25, 2023 6:07:32 PM com.hazelcast.internal.tpcengine.logging.JulLoggerFactory$JulLogger info
INFO: Thread-17 terminated

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-Windows-MicrosoftJDK11/67/

**Comment by olukas** [comment]
Failed again on _master_ with Windows - MicrosoftJDK17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Windows-MicrosoftJDK17/65/testReport/com.hazelcast.internal.tpcengine.nio/NioAsyncServerSocketOptionsTest/test_set/

**Comment by Patras3** [comment]
Failed again on _master_ with Windows - MicrosoftJDK17: https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK17/66/testReport/com.hazelcast.internal.tpcengine.nio/NioAsyncServerSocketOptionsTest/test_set/
