### ISSUE TITLE
com.hazelcast.jet.sql_slow.ComparisonPredicateIntegrationSlowTest.testNumeric[mode:NEQ]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#24664]
_master_ (commit cc01fe64c531ff21a260e29db43c8598521ef694)

Failed on openj9-11 (FIPS mode): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Openj9-11-fips-nightly/544/testReport/com.hazelcast.jet.sql_slow/ComparisonPredicateIntegrationSlowTest/testNumeric_mode_NEQ_/
<details><summary>Stacktrace:</summary>

```
org.junit.runners.model.TestTimedOutException: test timed out after 600000 milliseconds
	at org.apache.logging.log4j.core.appender.OutputStreamManager.writeBytes(OutputStreamManager.java:352)
	at org.apache.logging.log4j.core.layout.TextEncoderHelper.writeEncodedText(TextEncoderHelper.java:94)
	at org.apache.logging.log4j.core.layout.TextEncoderHelper.encodeText(TextEncoderHelper.java:63)
	at org.apache.logging.log4j.core.layout.StringBuilderEncoder.encode(StringBuilderEncoder.java:67)
	at org.apache.logging.log4j.core.layout.StringBuilderEncoder.encode(StringBuilderEncoder.java:32)
	at org.apache.logging.log4j.core.layout.PatternLayout.encode(PatternLayout.java:227)
	at org.apache.logging.log4j.core.layout.PatternLayout.encode(PatternLayout.java:59)
	at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.directEncodeEvent(AbstractOutputStreamAppender.java:215)
	at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.tryAppend(AbstractOutputStreamAppender.java:208)
	at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.append(AbstractOutputStreamAppender.java:199)
	at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:161)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:134)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:125)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:89)
	at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:683)
	at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:641)
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:624)
	at org.apache.logging.log4j.core.config.LoggerConfig.logParent(LoggerConfig.java:674)
	at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:643)
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:624)
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:560)
	at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:82)
	at org.apache.logging.log4j.core.Logger.log(Logger.java:163)
	at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2168)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2122)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2105)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:1980)
	at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1946)
	at com.hazelcast.logging.Log4j2Factory$Log4j2Logger.log(Log4j2Factory.java:69)
	at com.hazelcast.test.TestLoggerFactory$DelegatingTestLogger.log(TestLoggerFactory.java:258)
	at com.hazelcast.logging.impl.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:263)
	at com.hazelcast.logging.impl.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:251)
	at com.hazelcast.logging.AbstractLogger.fine(AbstractLogger.java:49)
	at com.hazelcast.jet.impl.util.LoggingUtil.logFine(LoggingUtil.java:37)
	at com.hazelcast.jet.impl.LightMasterContext.createContext(LightMasterContext.java:152)
	at com.hazelcast.jet.impl.JobCoordinationService.submitLightJob(JobCoordinationService.java:347)
	at com.hazelcast.jet.impl.operation.SubmitJobOperation.doRun(SubmitJobOperation.java:67)
	at com.hazelcast.jet.impl.operation.AsyncOperation.run(AsyncOperation.java:55)
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:193)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:299)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:270)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:219)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:454)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:511)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:618)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:597)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:558)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:241)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:71)
	at com.hazelcast.jet.impl.JobProxy.invokeOp(JobProxy.java:236)
	at com.hazelcast.jet.impl.JobProxy.invokeSubmitJob(JobProxy.java:144)
	at com.hazelcast.jet.impl.AbstractJobProxy.doSubmitJob(AbstractJobProxy.java:416)
	at com.hazelcast.jet.impl.AbstractJobProxy.<init>(AbstractJobProxy.java:118)
	at com.hazelcast.jet.impl.JobProxy.<init>(JobProxy.java:74)
	at com.hazelcast.jet.impl.JetInstanceImpl.newJobProxy(JetInstanceImpl.java:186)
	at com.hazelcast.jet.impl.AbstractJetInstance.newJobInt(AbstractJetInstance.java:144)
	at com.hazelcast.jet.impl.AbstractJetInstance.newLightJob(AbstractJetInstance.java:203)
	at com.hazelcast.jet.sql.impl.PlanExecutor.execute(PlanExecutor.java:511)
	at com.hazelcast.jet.sql.impl.SqlPlanImpl$SelectPlan.execute(SqlPlanImpl.java:1125)
	at com.hazelcast.sql.impl.SqlServiceImpl.query0(SqlServiceImpl.java:266)
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:204)
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:172)
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:168)
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:164)
	at com.hazelcast.jet.sql.impl.expression.ExpressionTestSupport.executeStatement(ExpressionTestSupport.java:286)
	at com.hazelcast.jet.sql.impl.expression.ExpressionTestSupport.execute(ExpressionTestSupport.java:281)
	at com.hazelcast.jet.sql.impl.expression.ExpressionTestSupport.execute(ExpressionTestSupport.java:273)
	at com.hazelcast.jet.sql.impl.expression.ExpressionTestSupport.checkValue0(ExpressionTestSupport.java:144)
	at com.hazelcast.jet.sql.impl.expression.predicate.ComparisonPredicateIntegrationTest.check(ComparisonPredicateIntegrationTest.java:677)
	at com.hazelcast.jet.sql.impl.expression.predicate.ComparisonPredicateIntegrationTest.checkCommute(ComparisonPredicateIntegrationTest.java:663)
	at com.hazelcast.jet.sql.impl.expression.predicate.ComparisonPredicateIntegrationTest.putCheckCommute(ComparisonPredicateIntegrationTest.java:659)
	at com.hazelcast.jet.sql.impl.expression.predicate.ComparisonPredicateIntegrationTest.checkNumeric(ComparisonPredicateIntegrationTest.java:547)
	at com.hazelcast.jet.sql.impl.expression.predicate.ComparisonPredicateIntegrationTest.testNumeric(ComparisonPredicateIntegrationTest.java:207)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:839)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-Openj9-11-fips-nightly/544/

**Comment by k-jamroz** [comment]
Yet another false positive due to https://github.com/hazelcast/hazelcast/issues/24862#issuecomment-1724042722

```
 <testcase name="" classname="com.hazelcast.jet.sql_nightly.SqlSTSInnerNonEquiJoinFaultToleranceStressTest" time="889.875">
    <error message="test timed out after 900 seconds" type="org.junit.runners.model.TestTimedOutException"><![CDATA[org.junit.runners.model.TestTimedOutException: test timed out after 900 seconds
```
