### ISSUE TITLE
com.hazelcast.jet.JobStatusListenerTest.testListenerDeregistration[onMaster] [HZ-2573]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#24665]
_master_ (commit cc01fe64c531ff21a260e29db43c8598521ef694)

Failed on openj9-11 (FIPS mode): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Openj9-11-fips-nightly/544/testReport/com.hazelcast.jet/JobStatusListenerTest/testListenerDeregistration_onMaster_/
<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: expected:<[Jet: STARTING -> RUNNING]> but was:<[User: STARTING -> FAILED (Cancel)]>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:120)
	at org.junit.Assert.assertEquals(Assert.java:146)
	at com.hazelcast.jet.JobStatusListenerTest.lambda$assertTailEqualsEventually$20(JobStatusListenerTest.java:352)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1285)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1389)
	at com.hazelcast.jet.JobStatusListenerTest.assertTailEqualsEventually(JobStatusListenerTest.java:348)
	at com.hazelcast.jet.JobStatusListenerTest.lambda$testListenerDeregistration$8(JobStatusListenerTest.java:205)
	at com.hazelcast.jet.JobStatusListenerTest.testListener(JobStatusListenerTest.java:334)
	at com.hazelcast.jet.JobStatusListenerTest.testListener(JobStatusListenerTest.java:293)
	at com.hazelcast.jet.JobStatusListenerTest.testListener(JobStatusListenerTest.java:297)
	at com.hazelcast.jet.JobStatusListenerTest.testListenerDeregistration(JobStatusListenerTest.java:197)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:839)

```
</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: testListener_suspend_resume_restart_cancelJob[onMaster] in 0.852 seconds.
Started Running Test: testListenerDeregistration[onMaster]
18:28:45,925 DEBUG || - [JobClassLoaderService] hz.JobStatusListenerTest_reverent_euclid.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Creating job classLoader for job 09e9-49c3-e784-0001
18:28:45,925 DEBUG || - [JobClassLoaderService] hz.JobStatusListenerTest_reverent_euclid.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Create processor classloader map for job 09e9-49c3-e784-0001
18:28:45,926 DEBUG || - [Planner] hz.JobStatusListenerTest_reverent_euclid.cached.thread-8 - Watermarks in the pipeline will be throttled to 1000
18:28:45,927  INFO || - [JobCoordinationService] hz.JobStatusListenerTest_reverent_euclid.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Starting job 09e9-49c3-e784-0001 based on submit request
18:28:45,928  INFO || - [MasterJobContext] hz.JobStatusListenerTest_reverent_euclid.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Didn't find any snapshot to restore for job '09e9-49c3-e784-0001', execution 09e9-49c3-e785-0001
18:28:45,928  INFO || - [MasterJobContext] hz.JobStatusListenerTest_reverent_euclid.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Start executing job '09e9-49c3-e784-0001', execution 09e9-49c3-e785-0001, execution graph in DOT format:
digraph DAG {
	"streamSource" [localParallelism=1];
	"noop" [localParallelism=1];
	"streamSource" -> "noop" [queueSize=1024];
}
HINT: You can use graphviz or http://viz-js.com to visualize the printed graph.
18:28:45,928 DEBUG || - [MasterJobContext] hz.JobStatusListenerTest_reverent_euclid.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Building execution plan for job '09e9-49c3-e784-0001', execution 09e9-49c3-e785-0001
18:28:45,928 DEBUG || - [MasterJobContext] hz.JobStatusListenerTest_reverent_euclid.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Built execution plans for job '09e9-49c3-e784-0001', execution 09e9-49c3-e785-0001
18:28:45,928 DEBUG || - [InitExecutionOperation] hz.JobStatusListenerTest_youthful_euclid.generic-operation.thread-1 - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] Initializing execution plan for job 09e9-49c3-e784-0001, execution 09e9-49c3-e785-0001 from [127.0.0.1]:5701
18:28:45,929 DEBUG || - [InitExecutionOperation] hz.JobStatusListenerTest_reverent_euclid.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Initializing execution plan for job 09e9-49c3-e784-0001, execution 09e9-49c3-e785-0001 from [127.0.0.1]:5701
18:28:45,929 DEBUG || - [JobClassLoaderService] hz.JobStatusListenerTest_youthful_euclid.generic-operation.thread-1 - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] Creating job classLoader for job 09e9-49c3-e784-0001
18:28:45,929 DEBUG || - [JobClassLoaderService] hz.JobStatusListenerTest_youthful_euclid.generic-operation.thread-1 - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] Create processor classloader map for job 09e9-49c3-e784-0001
18:28:45,929  INFO || - [JobExecutionService] hz.JobStatusListenerTest_reverent_euclid.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Execution plan for jobId=09e9-49c3-e784-0001, jobName='09e9-49c3-e784-0001', executionId=09e9-49c3-e785-0001 initialized
18:28:45,930 DEBUG |testListenerDeregistration[onMaster]| - [Job] testListenerDeregistration - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Sending CANCEL_FORCEFUL request for job 09e9-49c3-e784-0001 (name ??)
18:28:45,931  INFO || - [JobExecutionService] hz.JobStatusListenerTest_youthful_euclid.cached.thread-6 - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] Execution plan for jobId=09e9-49c3-e784-0001, jobName='09e9-49c3-e784-0001', executionId=09e9-49c3-e785-0001 initialized
18:28:45,931 DEBUG || - [MasterJobContext] hz.JobStatusListenerTest_reverent_euclid.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] job '09e9-49c3-e784-0001', execution 09e9-49c3-e785-0001 to be cancelled after Init
18:28:45,931 DEBUG || - [JobExecutionService] hz.JobStatusListenerTest_youthful_euclid.generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] job '09e9-49c3-e784-0001', execution 09e9-49c3-e785-0001 calling completeExecution because execution terminated before it started
18:28:45,931 DEBUG || - [JobExecutionService] hz.JobStatusListenerTest_reverent_euclid.async.thread-1 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] job '09e9-49c3-e784-0001', execution 09e9-49c3-e785-0001 calling completeExecution because execution terminated before it started
18:28:45,931 DEBUG || - [JobClassLoaderService] hz.JobStatusListenerTest_youthful_euclid.generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] Finish JobClassLoaders phaseCount = 0, removing classloaders for jobId=09e9-49c3-e784-0001
18:28:45,931 DEBUG || - [JobExecutionService] hz.JobStatusListenerTest_youthful_euclid.generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] Completed execution of job '09e9-49c3-e784-0001', execution 09e9-49c3-e785-0001
18:28:45,931 DEBUG || - [JobExecutionService] hz.JobStatusListenerTest_reverent_euclid.async.thread-1 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Completed execution of job '09e9-49c3-e784-0001', execution 09e9-49c3-e785-0001
18:28:45,931 DEBUG || - [JobClassLoaderService] hz.JobStatusListenerTest_reverent_euclid.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Finish JobClassLoaders phaseCount = 0, removing classloaders for jobId=09e9-49c3-e784-0001
18:28:45,931  INFO || - [MasterJobContext] hz.JobStatusListenerTest_reverent_euclid.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Execution of job '09e9-49c3-e784-0001', execution 09e9-49c3-e785-0001 got terminated, reason=com.hazelcast.jet.impl.exception.CancellationByUserException
	Start time: 2023-05-25T18:28:45.927
	Duration: 00:00:00.004
	To see additional job metrics enable JobConfig.storeMetricsAfterJobCompletion
18:28:45,932 DEBUG || - [JobCoordinationService] hz.JobStatusListenerTest_reverent_euclid.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] job '09e9-49c3-e784-0001', execution 09e9-49c3-e785-0001 is completed
18:28:45,932  WARN || - [JoinSubmittedJobOperation] hz.JobStatusListenerTest_reverent_euclid.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] null
com.hazelcast.jet.impl.exception.CancellationByUserException: null
	at com.hazelcast.jet.impl.MasterJobContext.createCancellationException(MasterJobContext.java:211) ~[classes/:?]
	at com.hazelcast.jet.impl.MasterJobContext.getErrorFromResponses(MasterJobContext.java:626) ~[classes/:?]
	at com.hazelcast.jet.impl.MasterJobContext.lambda$onInitStepCompleted$9(MasterJobContext.java:548) ~[classes/:?]
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$60(JobCoordinationService.java:1452) ~[classes/:?]
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$61(JobCoordinationService.java:1473) ~[classes/:?]
	at com.hazelcast.internal.util.executor.CompletableFutureTask.run(CompletableFutureTask.java:64) [classes/:?]
	at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217) [classes/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:839) [?:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76) [classes/:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:111) [classes/:?]
18:28:50,116 DEBUG || - [JobRepository] hz.JobStatusListenerTest_reverent_euclid.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
18:28:55,117 DEBUG || - [JobRepository] hz.JobStatusListenerTest_reverent_euclid.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
18:29:00,119 DEBUG || - [JobRepository] hz.JobStatusListenerTest_reverent_euclid.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
18:29:05,118 DEBUG || - [JobRepository] hz.JobStatusListenerTest_reverent_euclid.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
18:29:10,117 DEBUG || - [JobRepository] hz.JobStatusListenerTest_reverent_euclid.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
18:29:15,118 DEBUG || - [JobRepository] hz.JobStatusListenerTest_reverent_euclid.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
18:29:20,118 DEBUG || - [JobRepository] hz.JobStatusListenerTest_reverent_euclid.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
18:29:25,117 DEBUG || - [JobRepository] hz.JobStatusListenerTest_reverent_euclid.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
18:29:30,118 DEBUG || - [JobRepository] hz.JobStatusListenerTest_reverent_euclid.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
18:29:35,118 DEBUG || - [JobRepository] hz.JobStatusListenerTest_reverent_euclid.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
18:29:40,117 DEBUG || - [JobRepository] hz.JobStatusListenerTest_reverent_euclid.cached.thread-10 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
18:29:45,117 DEBUG || - [JobRepository] hz.JobStatusListenerTest_reverent_euclid.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
18:29:50,118 DEBUG || - [JobRepository] hz.JobStatusListenerTest_reverent_euclid.cached.thread-9 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
18:29:55,118 DEBUG || - [JobRepository] hz.JobStatusListenerTest_reverent_euclid.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
18:30:00,117 DEBUG || - [JobRepository] hz.JobStatusListenerTest_reverent_euclid.cached.thread-1 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
18:30:05,118 DEBUG || - [JobRepository] hz.JobStatusListenerTest_reverent_euclid.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
18:30:10,119 DEBUG || - [JobRepository] hz.JobStatusListenerTest_reverent_euclid.cached.thread-1 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
18:30:15,118 DEBUG || - [JobRepository] hz.JobStatusListenerTest_reverent_euclid.cached.thread-11 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
18:30:20,119 DEBUG || - [JobRepository] hz.JobStatusListenerTest_reverent_euclid.cached.thread-10 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
18:30:25,120 DEBUG || - [JobRepository] hz.JobStatusListenerTest_reverent_euclid.cached.thread-10 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
18:30:30,120 DEBUG || - [JobRepository] hz.JobStatusListenerTest_reverent_euclid.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
18:30:35,119 DEBUG || - [JobRepository] hz.JobStatusListenerTest_reverent_euclid.cached.thread-1 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
18:30:40,120 DEBUG || - [JobRepository] hz.JobStatusListenerTest_reverent_euclid.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
18:30:45,120 DEBUG || - [JobRepository] hz.JobStatusListenerTest_reverent_euclid.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
18:30:46,094  INFO |testListenerDeregistration[onMaster]| - [SimpleTestInClusterSupport] Time-limited test - Ditching 1 jobs in SimpleTestInClusterSupport.@After: [09e9-49c3-e784-0001]
18:30:46,096  INFO |testListenerDeregistration[onMaster]| - [SimpleTestInClusterSupport] Time-limited test - Destroying 1 distributed objects in SimpleTestInClusterSupport.@After: [hz:impl:mapService/advanceCount]
BuildInfo right after testListenerDeregistration[onMaster](com.hazelcast.jet.JobStatusListenerTest): BuildInfo{version='5.4.0-SNAPSHOT', build='20230525', buildNumber=20230525, revision=cc01fe6, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'testListenerDeregistration[onMaster](com.hazelcast.jet.JobStatusListenerTest):'
18:28:45, accumulated pauses: 45 ms, max pause: 0 ms, pauses over 1000 ms: 0
18:28:50, accumulated pauses: 50 ms, max pause: 1 ms, pauses over 1000 ms: 0
18:28:55, accumulated pauses: 44 ms, max pause: 0 ms, pauses over 1000 ms: 0
18:29:00, accumulated pauses: 46 ms, max pause: 0 ms, pauses over 1000 ms: 0
18:29:05, accumulated pauses: 45 ms, max pause: 1 ms, pauses over 1000 ms: 0
18:29:10, accumulated pauses: 44 ms, max pause: 0 ms, pauses over 1000 ms: 0
18:29:15, accumulated pauses: 45 ms, max pause: 0 ms, pauses over 1000 ms: 0
18:29:20, accumulated pauses: 56 ms, max pause: 3 ms, pauses over 1000 ms: 0
18:29:25, accumulated pauses: 50 ms, max pause: 0 ms, pauses over 1000 ms: 0
18:29:30, accumulated pauses: 46 ms, max pause: 0 ms, pauses over 1000 ms: 0
18:29:35, accumulated pauses: 49 ms, max pause: 1 ms, pauses over 1000 ms: 0
18:29:40, accumulated pauses: 47 ms, max pause: 2 ms, pauses over 1000 ms: 0
18:29:45, accumulated pauses: 47 ms, max pause: 0 ms, pauses over 1000 ms: 0
18:29:50, accumulated pauses: 46 ms, max pause: 0 ms, pauses over 1000 ms: 0
18:29:55, accumulated pauses: 53 ms, max pause: 4 ms, pauses over 1000 ms: 0
18:30:00, accumulated pauses: 52 ms, max pause: 3 ms, pauses over 1000 ms: 0
18:30:05, accumulated pauses: 48 ms, max pause: 0 ms, pauses over 1000 ms: 0
18:30:10, accumulated pauses: 45 ms, max pause: 0 ms, pauses over 1000 ms: 0
18:30:15, accumulated pauses: 47 ms, max pause: 0 ms, pauses over 1000 ms: 0
18:30:20, accumulated pauses: 47 ms, max pause: 0 ms, pauses over 1000 ms: 0
18:30:25, accumulated pauses: 49 ms, max pause: 0 ms, pauses over 1000 ms: 0
18:30:30, accumulated pauses: 47 ms, max pause: 0 ms, pauses over 1000 ms: 0
18:30:35, accumulated pauses: 52 ms, max pause: 2 ms, pauses over 1000 ms: 0
18:30:40, accumulated pauses: 50 ms, max pause: 1 ms, pauses over 1000 ms: 0
18:30:45, accumulated pauses: 10 ms, max pause: 0 ms, pauses over 1000 ms: 0


No metrics recorded during the test

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-Openj9-11-fips-nightly/544/

**Comment by olukas** [comment]
Failed again on _5.3.3_ release branch with oracle-11: https://jenkins.hazelcast.com/view/Security%20and%20Compliance/job/Hazelcast-sonar-custom-branch/25/testReport/com.hazelcast.jet/JobStatusListenerTest/testListenerDeregistration_onNonMaster_/
