### ISSUE TITLE
com.hazelcast.map.impl.mapstore.offload.MapStoreOffloadingBouncingNodeTest.stress

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#24675]
_master_ (commit 02e4cbb450e037bd8946f1498293ea3b375da93e)

Failed on oracle-11: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/143/testReport/com.hazelcast.map.impl.mapstore.offload/MapStoreOffloadingBouncingNodeTest/stress_writeBehindEnabled__false_/

Failed in variant `[writeBehindEnabled: false]`.

<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: Found asyncOperationsCount=1 {[com.hazelcast.map.impl.operation.ReplaceOperation{serviceName='hz:impl:mapService', identityHash=2025681272, partitionId=0, replicaIndex=0, callId=-29374, invocationTime=1685322805829 (2023-05-29 01:13:25.829), waitTimeout=-1, callTimeout=120000, tenantControl=com.hazelcast.spi.impl.tenantcontrol.NoopTenantControl@0, name=map-name}]} expected:<0> but was:<1>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at com.hazelcast.map.impl.mapstore.offload.MapStoreOffloadingBouncingNodeTest.lambda$stress$2(MapStoreOffloadingBouncingNodeTest.java:122)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1285)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1389)
	at com.hazelcast.map.impl.mapstore.offload.MapStoreOffloadingBouncingNodeTest.stress(MapStoreOffloadingBouncingNodeTest.java:115)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-sonar/143/

**Comment by Patras3** [comment]
Failed again on _master_ with openj9-11 and variant `[writeBehindEnabled: true]` : https://jenkins.hazelcast.com/job/Hazelcast-master-Openj9-11/134/testReport/com.hazelcast.map.impl.mapstore.offload/MapStoreOffloadingBouncingNodeTest/stress_writeBehindEnabled__true_/

**Comment by sumnerib** [comment]
Failed again on _5.3.z_ with microsoft-11: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-MicrosoftJDK11/36/testReport/junit/com.hazelcast.map.impl.mapstore.offload/MapStoreOffloadingBouncingNodeTest/stress_writeBehindEnabled__true_/

**Comment by olukas** [comment]
Failed again on _master_ with Windows - MicrosoftJDK17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Windows-MicrosoftJDK17/68/testReport/com.hazelcast.map.impl.mapstore.offload/MapStoreOffloadingBouncingNodeTest/stress_writeBehindEnabled__true_/

**Comment by olukas** [comment]
Failed again on _5.3.z_ with oracle-8: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-OracleJDK8/91/testReport/com.hazelcast.map.impl.mapstore.offload/MapStoreOffloadingBouncingNodeTest/stress_writeBehindEnabled__true_/

**Comment by sumnerib** [comment]
Failed again on _master_ with Windows - MicrosoftJDK17: https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK17/75/testReport/junit/com.hazelcast.map.impl.mapstore.offload/MapStoreOffloadingBouncingNodeTest/stress_writeBehindEnabled__true_/

**Comment by sumnerib** [comment]
Failed again on _5.3.z_ with redhat-8: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-RedHatJDK8/98/testReport/junit/com.hazelcast.map.impl.mapstore.offload/MapStoreOffloadingBouncingNodeTest/stress_writeBehindEnabled__true_/

**Comment by olukas** [comment]
Failed again on _master_ with oracle-11: https://jenkins.hazelcast.com/job/Hazelcast-master-OracleJDK11/392/testReport/com.hazelcast.map.impl.mapstore.offload/MapStoreOffloadingBouncingNodeTest/stress/

**Comment by olukas** [comment]
Closing the test failure - it doesn't seem to be related to `master` or the latest maintenance stream `5.5.z` and it hasn't fail in the last 3 months. Feel free to reopen test failure if it occurs on `master` or on the latest maintenance stream.

**Comment by olukas** [comment]
Reopening as issue occurred again on: _master_ (commit 2a24a3fc3bdd4bff3be06b2bbe5b8057120a1f52)
with redhat-21: https://jenkins.hazelcast.com/job/Hazelcast-master-RedHatJDK21/32/testReport/com.hazelcast.map.impl.mapstore.offload/MapStoreOffloadingBouncingNodeTest/stress_writeBehindEnabled__true_/
<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: Found asyncOperationsCount=1 {[com.hazelcast.map.impl.operation.ClearOperation{serviceName='hz:impl:mapService', identityHash=1499257331, partitionId=4, replicaIndex=0, callId=-60958, invocationTime=1724258606193 (2024-08-21 16:43:26.193), waitTimeout=-1, callTimeout=60000, tenantControl=com.hazelcast.spi.impl.tenantcontrol.NoopTenantControl@0, name=map-name}]} expected:<0> but was:<1>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at com.hazelcast.map.impl.mapstore.offload.MapStoreOffloadingBouncingNodeTest.lambda$stress$2(MapStoreOffloadingBouncingNodeTest.java:121)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1215)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1320)
	at com.hazelcast.map.impl.mapstore.offload.MapStoreOffloadingBouncingNodeTest.stress(MapStoreOffloadingBouncingNodeTest.java:114)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.lang.Thread.run(Thread.java:1583)

```
</details>



Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-RedHatJDK21/32/
