### ISSUE TITLE
serializable_classes_should_have_valid_serialVersionUID (JDK21 early access)

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#24677]
_master_ (commit 02e4cbb450e037bd8946f1498293ea3b375da93e)

Failed on openjdk-ea (openjdk-21): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-OpenJDK-ea/37/testReport/

Following tests failed:
- `com.hazelcast.jet.avro.AvroSerializableTest.serializable_classes_should_have_valid_serialVersionUID`
- `com.hazelcast.jet.cdc.CdcDebeziumSerializableTest.serializable_classes_should_have_valid_serialVersionUID`
- `com.hazelcast.jet.cdc.mysql.CdcMysqlSerializableTest.serializable_classes_should_have_valid_serialVersionUID`
- `com.hazelcast.jet.cdc.postgres.CdcPostgresSerializableTest.serializable_classes_should_have_valid_serialVersionUID`
- `com.hazelcast.jet.csv.CsvSerializableTest.serializable_classes_should_have_valid_serialVersionUID`
- `com.hazelcast.jet.elastic.Elastic6SerializableTest.serializable_classes_should_have_valid_serialVersionUID`
- `com.hazelcast.jet.elastic.Elastic7SerializableTest.serializable_classes_should_have_valid_serialVersionUID`
- `com.hazelcast.jet.grpc.GrpcSerializableTest.serializable_classes_should_have_valid_serialVersionUID`
- `com.hazelcast.jet.hadoop.HadoopSerializableTest.serializable_classes_should_have_valid_serialVersionUID`
- `com.hazelcast.connector.Hz3SerializableTest.serializable_classes_should_have_valid_serialVersionUID`
- `com.hazelcast.internal.serialization.impl.Hz3ImplSerializableTest.serializable_classes_should_have_valid_serialVersionUID`
- `com.hazelcast.jet.kafka.KafkaSerializableTest.serializable_classes_should_have_valid_serialVersionUID`
- `com.hazelcast.jet.kinesis.KinesisSerializableTest.serializable_classes_should_have_valid_serialVersionUID`
- `com.hazelcast.jet.python.PythonSerializableTest.serializable_classes_should_have_valid_serialVersionUID`
- `com.hazelcast.jet.s3.S3SerializableTest.serializable_classes_should_have_valid_serialVersionUID`
- `com.hazelcast.jet.JetSerializableTest.serializable_classes_should_have_valid_serialVersionUID`

<details><summary>Stacktrace:</summary>

```
java.lang.ExceptionInInitializerError
	at com.hazelcast.test.archunit.ArchUnitRules.<clinit>(ArchUnitRules.java:48)
	at com.hazelcast.jet.avro.AvroSerializableTest.serializable_classes_should_have_valid_serialVersionUID(AvroSerializableTest.java:41)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.util.NoSuchElementException
	at com.tngtech.archunit.thirdparty.com.google.common.collect.AbstractIndexedListIterator.next(AbstractIndexedListIterator.java:80)
	at com.tngtech.archunit.thirdparty.com.google.common.collect.Iterators.getOnlyElement(Iterators.java:309)
	at com.tngtech.archunit.thirdparty.com.google.common.collect.Iterables.getOnlyElement(Iterables.java:263)
	at com.tngtech.archunit.core.importer.ClassFileImporter.importClass(ClassFileImporter.java:262)
	at com.hazelcast.test.archunit.CompletableFutureUsageCondition.<clinit>(CompletableFutureUsageCondition.java:53)
	... 12 more

```
</details>

<details><summary>Standard output:</summary>

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
THREAD DUMP FOR TEST FAILURE: "null" at "serializable_classes_should_have_valid_serialVersionUID"

"main" 
	java.lang.Thread.State: TIMED_WAITING, cpu=1420485572 nsecs, usr=1260000000 nsecs, blocked=0 msecs, waited=1603 msecs
		at java.base@21-ea/java.lang.Thread.sleep0(Native Method)
		at java.base@21-ea/java.lang.Thread.sleep(Thread.java:509)
		at app//com.hazelcast.test.HazelcastParallelClassRunner$1.evaluate(HazelcastParallelClassRunner.java:135)
		at app//com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:41)
		at app//org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
		at app//org.junit.runners.ParentRunner.run(ParentRunner.java:413)
		at app//org.junit.runners.Suite.runChild(Suite.java:128)
		at app//org.junit.runners.Suite.runChild(Suite.java:27)
		at app//org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
		at app//org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
		at app//org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
		at app//org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
		at app//org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
		at app//org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
		at app//org.junit.runners.ParentRunner.run(ParentRunner.java:413)
		at app//org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:49)
		at app//org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:120)
		at app//org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:95)
		at app//org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
		at app//org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:69)
		at app//org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:146)
		at app//org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
		at app//org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
		at app//org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
		at app//org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)

"Reference Handler" 
	java.lang.Thread.State: RUNNABLE, cpu=1902685 nsecs, usr=0 nsecs, blocked=0 msecs, waited=0 msecs
		at java.base@21-ea/java.lang.ref.Reference.waitForReferencePendingList(Native Method)
		at java.base@21-ea/java.lang.ref.Reference.processPendingReferences(Reference.java:246)
		at java.base@21-ea/java.lang.ref.Reference$ReferenceHandler.run(Reference.java:208)

"Finalizer" 
	java.lang.Thread.State: WAITING, on lock=java.lang.ref.NativeReferenceQueue$Lock@7320291b, cpu=230249 nsecs, usr=0 nsecs, blocked=0 msecs, waited=0 msecs
		at java.base@21-ea/java.lang.Object.wait0(Native Method)
		at java.base@21-ea/java.lang.Object.wait(Object.java:366)
		at java.base@21-ea/java.lang.Object.wait(Object.java:339)
		at java.base@21-ea/java.lang.ref.NativeReferenceQueue.await(NativeReferenceQueue.java:48)
		at java.base@21-ea/java.lang.ref.ReferenceQueue.remove0(ReferenceQueue.java:158)
		at java.base@21-ea/java.lang.ref.NativeReferenceQueue.remove(NativeReferenceQueue.java:89)
		at java.base@21-ea/java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:173)

"Signal Dispatcher" 
	java.lang.Thread.State: RUNNABLE, cpu=56920 nsecs, usr=0 nsecs, blocked=0 msecs, waited=0 msecs

"Common-Cleaner" 
	java.lang.Thread.State: TIMED_WAITING, on lock=java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@52244ba3, cpu=1863595 nsecs, usr=0 nsecs, blocked=0 msecs, waited=396 msecs
		at java.base@21-ea/jdk.internal.misc.Unsafe.park(Native Method)
		at java.base@21-ea/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:269)
		at java.base@21-ea/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1847)
		at java.base@21-ea/java.lang.ref.ReferenceQueue.await(ReferenceQueue.java:71)
		at java.base@21-ea/java.lang.ref.ReferenceQueue.remove0(ReferenceQueue.java:143)
		at java.base@21-ea/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:218)
		at java.base@21-ea/jdk.internal.ref.CleanerImpl.run(CleanerImpl.java:140)
		at java.base@21-ea/java.lang.Thread.runWith(Thread.java:1596)
		at java.base@21-ea/java.lang.Thread.run(Thread.java:1583)
		at java.base@21-ea/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:186)

"Notification Thread" 
	java.lang.Thread.State: RUNNABLE, cpu=134485 nsecs, usr=0 nsecs, blocked=0 msecs, waited=0 msecs

"pool-1-thread-1" 
	java.lang.Thread.State: WAITING, on lock=java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@3c5d37cf, cpu=919075 nsecs, usr=0 nsecs, blocked=0 msecs, waited=0 msecs
		at java.base@21-ea/jdk.internal.misc.Unsafe.park(Native Method)
		at java.base@21-ea/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
		at java.base@21-ea/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:519)
		at java.base@21-ea/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3780)
		at java.base@21-ea/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3725)
		at java.base@21-ea/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1707)
		at java.base@21-ea/java.util.concurrent.ArrayBlockingQueue.take(ArrayBlockingQueue.java:420)
		at java.base@21-ea/sun.nio.ch.EPollPort$EventHandlerTask.run(EPollPort.java:274)
		at java.base@21-ea/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:113)
		at java.base@21-ea/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
		at java.base@21-ea/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
		at java.base@21-ea/java.lang.Thread.runWith(Thread.java:1596)
		at java.base@21-ea/java.lang.Thread.run(Thread.java:1583)

"pool-1-thread-2" 
	java.lang.Thread.State: RUNNABLE, cpu=1062127 nsecs, usr=0 nsecs, blocked=0 msecs, waited=0 msecs
		at java.base@21-ea/sun.nio.ch.EPoll.wait(Native Method)
		at java.base@21-ea/sun.nio.ch.EPollPort$EventHandlerTask.poll(EPollPort.java:199)
		at java.base@21-ea/sun.nio.ch.EPollPort$EventHandlerTask.run(EPollPort.java:280)
		at java.base@21-ea/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:113)
		at java.base@21-ea/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
		at java.base@21-ea/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
		at java.base@21-ea/java.lang.Thread.runWith(Thread.java:1596)
		at java.base@21-ea/java.lang.Thread.run(Thread.java:1583)

"surefire-forkedjvm-stream-flusher" 
	java.lang.Thread.State: TIMED_WAITING, on lock=java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@3f594da3, cpu=4328103 nsecs, usr=0 nsecs, blocked=0 msecs, waited=2539 msecs
		at java.base@21-ea/jdk.internal.misc.Unsafe.park(Native Method)
		at java.base@21-ea/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:269)
		at java.base@21-ea/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:1758)
		at java.base@21-ea/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1182)
		at java.base@21-ea/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899)
		at java.base@21-ea/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070)
		at java.base@21-ea/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
		at java.base@21-ea/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
		at java.base@21-ea/java.lang.Thread.runWith(Thread.java:1596)
		at java.base@21-ea/java.lang.Thread.run(Thread.java:1583)

"surefire-forkedjvm-command-thread" 
	java.lang.Thread.State: WAITING, on lock=java.util.concurrent.CountDownLatch$Sync@687c5bc3, cpu=4258962 nsecs, usr=0 nsecs, blocked=0 msecs, waited=0 msecs
		at java.base@21-ea/jdk.internal.misc.Unsafe.park(Native Method)
		at java.base@21-ea/java.util.concurrent.locks.LockSupport.park(LockSupport.java:221)
		at java.base@21-ea/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:754)
		at java.base@21-ea/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1099)
		at java.base@21-ea/java.util.concurrent.CountDownLatch.await(CountDownLatch.java:230)
		at java.base@21-ea/sun.nio.ch.PendingFuture.get(PendingFuture.java:178)
		at app//org.apache.maven.surefire.api.util.internal.Channels$2.read(Channels.java:127)
		at java.base@21-ea/java.io.BufferedInputStream.fill(BufferedInputStream.java:291)
		at java.base@21-ea/java.io.BufferedInputStream.read1(BufferedInputStream.java:347)
		at java.base@21-ea/java.io.BufferedInputStream.implRead(BufferedInputStream.java:420)
		at java.base@21-ea/java.io.BufferedInputStream.read(BufferedInputStream.java:399)
		at app//org.apache.maven.surefire.api.util.internal.Channels$3.readImpl(Channels.java:169)
		at app//org.apache.maven.surefire.api.util.internal.AbstractNoninterruptibleReadableChannel.read(AbstractNoninterruptibleReadableChannel.java:50)
		at app//org.apache.maven.surefire.api.stream.AbstractStreamDecoder.read(AbstractStreamDecoder.java:430)
		at app//org.apache.maven.surefire.api.stream.AbstractStreamDecoder.read(AbstractStreamDecoder.java:419)
		at app//org.apache.maven.surefire.api.stream.AbstractStreamDecoder.readMessageType(AbstractStreamDecoder.java:116)
		at app//org.apache.maven.surefire.booter.stream.CommandDecoder.decode(CommandDecoder.java:77)
		at app//org.apache.maven.surefire.booter.spi.CommandChannelDecoder.decode(CommandChannelDecoder.java:60)
		at app//org.apache.maven.surefire.booter.CommandReader$CommandRunnable.run(CommandReader.java:290)
		at java.base@21-ea/java.lang.Thread.runWith(Thread.java:1596)
		at java.base@21-ea/java.lang.Thread.run(Thread.java:1583)


Finished Running Test: serializable_classes_should_have_valid_serialVersionUID in 1.561 seconds.
Started Running Test: testGenericWriter
Started Running Test: testSpecificWriter

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-OpenJDK-ea/37/

**Comment by Patras3** [comment]
Failed again on _master_ with openjdk-ea (openjdk-21): https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK-ea/38/testReport
