### ISSUE TITLE
com.hazelcast.sql.impl.client.SqlResubmissionStreamTest.when_failingSelectAfterSomeDataIsFetched

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#24682]
_master_ (commit 02e4cbb450e037bd8946f1498293ea3b375da93e)

Failed on zing-11: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZingJDK11-nightly/33/testReport/com.hazelcast.sql.impl.client/SqlResubmissionStreamTest/

Almost all variant in test `com.hazelcast.sql.impl.client.SqlResubmissionStreamTest.when_failingSelectAfterSomeDataIsFetched` failed. 

<details><summary>Stacktrace:</summary>

```
org.junit.runners.model.TestTimedOutException: test timed out after 10000 milliseconds
	at app//org.apache.logging.log4j.core.appender.OutputStreamManager.writeBytes(OutputStreamManager.java:353)
	at app//org.apache.logging.log4j.core.layout.TextEncoderHelper.writeEncodedText(TextEncoderHelper.java:94)
	at app//org.apache.logging.log4j.core.layout.TextEncoderHelper.encodeText(TextEncoderHelper.java:63)
	at app//org.apache.logging.log4j.core.layout.StringBuilderEncoder.encode(StringBuilderEncoder.java:67)
	at app//org.apache.logging.log4j.core.layout.StringBuilderEncoder.encode(StringBuilderEncoder.java:32)
	at app//org.apache.logging.log4j.core.layout.PatternLayout.encode(PatternLayout.java:227)
	at app//org.apache.logging.log4j.core.layout.PatternLayout.encode(PatternLayout.java:59)
	at app//org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.directEncodeEvent(AbstractOutputStreamAppender.java:215)
	at app//org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.tryAppend(AbstractOutputStreamAppender.java:208)
	at app//org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.append(AbstractOutputStreamAppender.java:199)
	at app//org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:161)
	at app//org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:134)
	at app//org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:125)
	at app//org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:89)
	at app//org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:683)
	at app//org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:641)
	at app//org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:624)
	at app//org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:560)
	at app//org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:82)
	at app//org.apache.logging.log4j.core.Logger.log(Logger.java:163)
	at app//org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2168)
	at app//org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2122)
	at app//org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2105)
	at app//org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:1980)
	at app//org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1946)
	at app//com.hazelcast.logging.Log4j2Factory$Log4j2Logger.log(Log4j2Factory.java:69)
	at app//com.hazelcast.test.TestLoggerFactory$DelegatingTestLogger.log(TestLoggerFactory.java:258)
	at app//com.hazelcast.logging.impl.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:263)
	at app//com.hazelcast.logging.impl.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:251)
	at app//com.hazelcast.logging.AbstractLogger.info(AbstractLogger.java:69)
	at app//com.hazelcast.internal.metrics.impl.MetricsConfigHelper.memberMetricsLevel(MetricsConfigHelper.java:145)
	at app//com.hazelcast.spi.impl.NodeEngineImpl.newMetricRegistry(NodeEngineImpl.java:254)
	at app//com.hazelcast.spi.impl.NodeEngineImpl.<init>(NodeEngineImpl.java:151)
	at app//com.hazelcast.instance.impl.Node.<init>(Node.java:264)
	at app//com.hazelcast.instance.impl.HazelcastInstanceImpl.createNode(HazelcastInstanceImpl.java:149)
	at app//com.hazelcast.instance.impl.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:118)
	at app//com.hazelcast.instance.impl.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:217)
	at app//com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:196)
	at app//com.hazelcast.test.TestHazelcastInstanceFactory.newHazelcastInstance(TestHazelcastInstanceFactory.java:235)
	at app//com.hazelcast.test.ClusterFailureTestSupport$NodeReplacementClusterFailure.fail(ClusterFailureTestSupport.java:113)
	at app//com.hazelcast.sql.impl.client.SqlResubmissionStreamTest.when_failingSelectAfterSomeDataIsFetched(SqlResubmissionStreamTest.java:99)
	at java.base@11.0.19/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@11.0.19/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base@11.0.19/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@11.0.19/java.lang.reflect.Method.invoke(Method.java:566)
	at app//org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at app//org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at app//org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at app//org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at app//com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at app//com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base@11.0.19/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base@11.0.19/java.lang.Thread.run(Thread.java:887)

```
</details>

**Comment by olukas** [comment]
Failed again on _master_ with zing-11: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZingJDK11-nightly/36/testReport/com.hazelcast.sql.impl.client/SqlResubmissionStreamTest/

**Comment by Patras3** [comment]
Failed again on _master_ with zing-11: https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK11-nightly/39/testReport/com.hazelcast.sql.impl.client/SqlResubmissionStreamTest/

**Comment by olukas** [comment]
Failed again on _master_ with zing-11: https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK11-nightly/47/testReport/com.hazelcast.sql.impl.client/SqlResubmissionStreamTest/

**Comment by AleksPeychev** [comment]
Failed again on _master_ with openj9-21: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Openj9-21-nightly/11/testReport/junit/com.hazelcast.sql.impl.client/SqlResubmissionStreamTest/when_failingSelectAfterSomeDataIsFetched_clusterFailure_NodeShutdownClusterFailure__mode_RETRY_SELECTS_ALLOW_DUPLICATES_/

**Comment by olukas** [comment]
Failed again on _master_ with oracle-17 (sonar build): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-mono-OS-master-sonar/139/testReport/com.hazelcast.sql.impl.client/SqlResubmissionStreamTest/when_failingSelectAfterSomeDataIsFetched_clusterFailure_NetworkProblemClusterFailure__mode_RETRY_SELECTS_/

**Comment by sumnerib** [comment]
Failed again on _master_ with oracle-17 (sonar build): https://jenkins.hazelcast.com/job/Hazelcast-master-sonar/479/testReport/junit/com.hazelcast.sql.impl.client/SqlResubmissionStreamTest/when_failingSelectAfterSomeDataIsFetched_clusterFailure_NetworkProblemClusterFailure__mode_RETRY_SELECTS_/

**Comment by olukas** [comment]
Failed again on _master_ with oracle-17 (sonar build): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-mono-OS-master-sonar/168/testReport/com.hazelcast.sql.impl.client/SqlResubmissionStreamTest/when_failingSelectAfterSomeDataIsFetched_clusterFailure_NetworkProblemClusterFailure__mode_RETRY_SELECTS_/

**Comment by AleksPeychev** [comment]
Failed again on _master_ with oracle-17 (sonar build): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-mono-OS-master-sonar/176/testReport/junit/com.hazelcast.sql.impl.client/SqlResubmissionStreamTest/when_failingSelectAfterSomeDataIsFetched_clusterFailure_NetworkProblemClusterFailure__mode_RETRY_SELECTS_/

**Comment by sumnerib** [comment]
Failed again on _master_ with oracle-17 (sonar build): https://jenkins.hazelcast.com/job/Hazelcast-mono-OS-master-sonar/192/testReport/com.hazelcast.sql.impl.client/SqlResubmissionStreamTest/

**Comment by olukas** [comment]
Failed again on _master_ with oracle-17 (sonar build): https://jenkins.hazelcast.com/job/Hazelcast-mono-OS-master-sonar/232/testReport/com.hazelcast.sql.impl.client/SqlResubmissionStreamTest/when_failingSelectAfterSomeDataIsFetched_clusterFailure_NetworkProblemClusterFailure__mode_RETRY_SELECTS_/

**Comment by olukas** [comment]
Failed again on _master_ with oracle-17 (sonar build): https://jenkins.hazelcast.com/job/Hazelcast-mono-OS-master-sonar/260/testReport/com.hazelcast.sql.impl.client/SqlResubmissionStreamTest/when_failingSelectAfterSomeDataIsFetched_clusterFailure_NetworkProblemClusterFailure__mode_RETRY_SELECTS_/
