### ISSUE TITLE
com.hazelcast.jet.sql_slow.SqlSlowIndexResolutionTest

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#24680]
_master_ (commit 02e4cbb450e037bd8946f1498293ea3b375da93e)

Failed on zing-17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZingJDK17-nightly/27/testReport/com.hazelcast.jet.sql_slow/SqlSlowIndexResolutionTest/___/
<details><summary>Stacktrace:</summary>

```
java.lang.NullPointerException: Cannot invoke "com.hazelcast.client.test.TestHazelcastFactory.newHazelcastInstance(com.hazelcast.config.Config)" because "com.hazelcast.jet.SimpleTestInClusterSupport.factory" is null
	at com.hazelcast.jet.SimpleTestInClusterSupport.initialize(SimpleTestInClusterSupport.java:73)
	at com.hazelcast.jet.sql_slow.SqlSlowIndexResolutionTest.beforeClass(SqlSlowIndexResolutionTest.java:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:41)
	at com.hazelcast.test.OverridePropertyRule$1.evaluate(OverridePropertyRule.java:66)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:891)

```
</details>

<details><summary>Standard output:</summary>

```
22:56:56,181  INFO || - [LifecycleService] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
22:56:56,181  WARN || - [Node] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Terminating forcefully...
22:56:56,181  INFO || - [Node] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Shutting down connection manager...
22:56:56,181  INFO || - [Node] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Shutting down node engine...
22:56:56,183  INFO || - [HealthMonitor] hz.SqlSlowIndexResolutionTest_gracious_wilson.HealthMonitor - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] processors=8, physical.memory.total=377.8G, physical.memory.free=138.0G, swap.space.total=8.0G, swap.space.free=4.7G, heap.memory.used=4.8G, heap.memory.free=3.2G, heap.memory.total=8.0G, heap.memory.max=8.0G, heap.memory.used/total=59.42%, heap.memory.used/max=59.42%, minor.gc.count=0, minor.gc.time=0ms, major.gc.count=0, major.gc.time=0ms, unknown.gc.count=182, unknown.gc.time=30590ms, load.process=69.58%, load.system=84.78%, load.systemAverage=7.30, thread.count=34, thread.peakCount=563, cluster.timeDiff=0, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=1, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=0, clientEndpoint.count=0, connection.active.count=0, client.connection.count=0, connection.count=0
22:56:56,185  INFO || - [MetricsConfigHelper] Time-limited test - [LOCAL] [dev] [5.4.0-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
22:56:56,185  INFO || - [logo] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
22:56:56,185  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Copyright (c) 2008-2023, Hazelcast, Inc. All Rights Reserved.
22:56:56,185  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Hazelcast Platform 5.4.0-SNAPSHOT (20230526 - 02e4cbb) starting at [127.0.0.1]:5701
22:56:56,185  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Cluster name: dev
22:56:56,185  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed. For more information, see the documentation for Integrity Checker.
22:56:56,185  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Jet is enabled
22:56:56,187  INFO || - [NodeExtension] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Destroying node NodeExtension.
22:56:56,187  INFO || - [Node] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Hazelcast Shutdown is completed in 6 ms.
22:56:56,187  INFO || - [LifecycleService] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
22:56:56,190  INFO || - [MetricsConfigHelper] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
Exception in thread "hz.SqlSlowIndexResolutionTest_gracious_wilson.cached.thread-6" 22:56:56,192  INFO || - [TpcServerBootstrap] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] TPC: disabled
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@f34705c[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@f347050[Wrapped task = DelegateDecorator{executor=com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate@7983f215, runnable=com.hazelcast.jet.impl.JobCoordinationService$$Lambda$scanJobs$636937061/0x0000000000003761@f3470b0}]] rejected from com.hazelcast.internal.util.executor.LoggingScheduledExecutor@7983f3bb[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 6]
	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2065)
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:833)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:340)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:562)
	at com.hazelcast.spi.impl.executionservice.impl.DelegatingTaskScheduler.schedule(DelegatingTaskScheduler.java:49)
	at com.hazelcast.spi.impl.executionservice.impl.ExecutionServiceImpl.schedule(ExecutionServiceImpl.java:273)
	at com.hazelcast.jet.impl.JobCoordinationService.scanJobs(JobCoordinationService.java:1402)
	at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:891)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:111)
22:56:56,200  WARN || - [CPSubsystem] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
22:56:56,203  INFO || - [JetServiceBackend] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Setting number of cooperative threads and default parallelism to 2
22:56:56,204  INFO || - [Diagnostics] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
22:56:56,204  INFO || - [LifecycleService] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] [127.0.0.1]:5701 is STARTING
22:56:56,205  INFO || - [ClusterService] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] 

Members {size:1, ver:1} [
	Member [127.0.0.1]:5701 - b45f9ebe-54cc-4652-839d-9466dace4af4 this
]

22:56:56,205  INFO || - [JobCoordinationService] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Jet started scanning for jobs
22:56:56,205  INFO || - [LifecycleService] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] [127.0.0.1]:5701 is STARTED
Started Running Test: testCompare_LocalDateTime_with_LocalDateTime[mode:EQ]

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-ZingJDK17-nightly/27/

**Comment by sumnerib** [comment]
Failed again on _master_ with zing-17: https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK17-nightly/37/testReport/junit/com.hazelcast.jet.sql_slow/SqlSlowIndexResolutionTest/___/
