### ISSUE TITLE
com.hazelcast.sql.impl.client.SqlResubmissionTimeoutTest.when_totalTimeOfResubmissionEnds_then_fail

### ISSUE THREAD

**Issue by Patras3** [hazelcast/hazelcast#24717]
_master_ (commit 5f414fa3ad03417e0b9078c8d9f249904003c936)

Failed on openjdk-17: https://jenkins.hazelcast.com/job/Hazelcast-master-ZuluJDK17-nightly/70/testReport/com.hazelcast.sql.impl.client/SqlResubmissionTimeoutTest/when_totalTimeOfResubmissionEnds_then_fail_timeout_10_/  in variants:
`[timeout:1]` `[timeout:10]` `[timeout:30]` with similar stacktrace

<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: Expected 'timeout' to be greater than or equal to 10, but was 4
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at com.hazelcast.test.HazelcastTestSupport.assertGreaterOrEquals(HazelcastTestSupport.java:1438)
	at com.hazelcast.sql.impl.client.SqlResubmissionTimeoutTest.when_totalTimeOfResubmissionEnds_then_fail(SqlResubmissionTimeoutTest.java:67)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)

```
</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: when_totalTimeOfResubmissionEnds_then_fail[timeout:30] in 2.689 seconds.
Started Running Test: when_failingSelectAfterSomeDataIsFetched[clusterFailure:NodeReplacementClusterFailure, mode:NEVER]

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-ZuluJDK17-nightly/70/

**Comment by olukas** [comment]
Failed again on _master_ with openjdk-17: https://jenkins.hazelcast.com/job/Hazelcast-master-ZuluJDK17-nightly/73/testReport/com.hazelcast.sql.impl.client/SqlResubmissionTimeoutTest/

**Comment by Patras3** [comment]
Failed again on _master_ with openjdk-17: https://jenkins.hazelcast.com/job/Hazelcast-master-ZuluJDK17-nightly/74/testReport/com.hazelcast.sql.impl.client/SqlResubmissionTimeoutTest/when_totalTimeOfResubmissionEnds_then_fail_timeout_30_/

**Comment by sumnerib** [comment]
Failed again on _master_ with openjdk-17: https://jenkins.hazelcast.com/job/Hazelcast-master-ZuluJDK17-nightly/78/testReport/junit/com.hazelcast.sql.impl.client/SqlResubmissionTimeoutTest/

**Comment by sumnerib** [comment]
Failed again on _master_ with openjdk-17: https://jenkins.hazelcast.com/job/Hazelcast-master-ZuluJDK17-nightly/80/testReport/junit/com.hazelcast.sql.impl.client/SqlResubmissionTimeoutTest/

**Comment by sumnerib** [comment]
Failed again on _master_ with openjdk-17: https://jenkins.hazelcast.com/job/Hazelcast-master-ZuluJDK17-nightly/81/testReport/junit/com.hazelcast.sql.impl.client/SqlResubmissionTimeoutTest/

**Comment by sumnerib** [comment]
Failed again on _master_ with openjdk-17: https://jenkins.hazelcast.com/job/Hazelcast-master-ZuluJDK17-nightly/85/testReport/junit/com.hazelcast.sql.impl.client/SqlResubmissionTimeoutTest/

**Comment by k-jamroz** [comment]
checked some executions - likely a false positive due to https://github.com/hazelcast/hazelcast/issues/24862#issuecomment-1724042722

however, there is slight chance that such errors (when there are no timeouts in preceding tests) might be caused by difference in time measurement. Test uses `currentTimeMillis` and retry logic `nanoTime`. This however is extremely unlikely as the timeouts are 1, 10 and 30 seconds, so the clock drift would have to be huge.
