### ISSUE TITLE
com.hazelcast.jet.sql_slow.SqlBasicClientSlowTest.(?)

### ISSUE THREAD

**Issue by Patras3** [hazelcast/hazelcast#24713]
_master_ (commit f5984a1e6ffc821789c7616b17d897d1c42b08cb)

Failed on oracle-11 (force-offload): https://jenkins.hazelcast.com/job/Hazelcast-master-nightly-force-offload/50/testReport/com.hazelcast.jet.sql_slow/SqlBasicClientSlowTest/___/
<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: already initialized
	at com.hazelcast.jet.SimpleTestInClusterSupport.initialize(SimpleTestInClusterSupport.java:64)
	at com.hazelcast.jet.SimpleTestInClusterSupport.initializeWithClient(SimpleTestInClusterSupport.java:86)
	at com.hazelcast.jet.sql.SqlBasicTest.beforeClass(SqlBasicTest.java:146)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:41)
	at com.hazelcast.test.OverridePropertyRule$1.evaluate(OverridePropertyRule.java:66)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)

```
</details>

<details><summary>Standard output:</summary>

```
16:57:16,676  INFO || - [MetricsConfigHelper] Time-limited test - [LOCAL] [dev] [5.4.0-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
16:57:16,676  INFO || - [logo] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
16:57:16,676  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Copyright (c) 2008-2023, Hazelcast, Inc. All Rights Reserved.
16:57:16,676  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Hazelcast Platform 5.4.0-SNAPSHOT (20230604 - f5984a1) starting at [127.0.0.1]:5701
16:57:16,677  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Cluster name: dev
16:57:16,677  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed. For more information, see the documentation for Integrity Checker.
16:57:16,677  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Jet is enabled
16:57:16,682  INFO || - [MetricsConfigHelper] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
16:57:16,682  INFO || - [TpcServerBootstrap] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] TPC: disabled
16:57:16,686  WARN || - [CPSubsystem] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
16:57:16,689  INFO || - [JetServiceBackend] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Setting number of cooperative threads and default parallelism to 2
16:57:16,696  INFO || - [Diagnostics] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
16:57:16,696  INFO || - [LifecycleService] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] [127.0.0.1]:5701 is STARTING
16:57:16,696  INFO || - [ClusterService] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] 

Members {size:1, ver:1} [
	Member [127.0.0.1]:5701 - dffdc17e-38c3-477c-8492-f7f5234fcac3 this
]

16:57:16,696  INFO || - [JobCoordinationService] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Jet started scanning for jobs
16:57:16,696 DEBUG || - [JobCoordinationService] hz.SqlBasicSlowTest_inspiring_ardinghelli.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
16:57:16,696  INFO || - [LifecycleService] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] [127.0.0.1]:5701 is STARTED
16:57:16,697  INFO || - [MetricsConfigHelper] Time-limited test - [LOCAL] [dev] [5.4.0-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
16:57:16,697  INFO || - [logo] Time-limited test - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
16:57:16,698  INFO || - [system] Time-limited test - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] Copyright (c) 2008-2023, Hazelcast, Inc. All Rights Reserved.
16:57:16,698  INFO || - [system] Time-limited test - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] Hazelcast Platform 5.4.0-SNAPSHOT (20230604 - f5984a1) starting at [127.0.0.1]:5702
16:57:16,698  INFO || - [system] Time-limited test - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] Cluster name: dev
16:57:16,698  INFO || - [system] Time-limited test - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed. For more information, see the documentation for Integrity Checker.
16:57:16,698  INFO || - [system] Time-limited test - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] Jet is enabled
16:57:16,700  INFO || - [MetricsConfigHelper] Time-limited test - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
16:57:16,701  INFO || - [TpcServerBootstrap] Time-limited test - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] TPC: disabled
16:57:16,704  WARN || - [CPSubsystem] Time-limited test - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
16:57:16,706  INFO || - [JetServiceBackend] Time-limited test - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] Setting number of cooperative threads and default parallelism to 2
16:57:16,708  INFO || - [Diagnostics] Time-limited test - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
16:57:16,708  INFO || - [LifecycleService] Time-limited test - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] [127.0.0.1]:5702 is STARTING
16:57:16,708  INFO || - [MockServer] Time-limited test - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] Created connection to endpoint: [127.0.0.1]:5701-dffdc17e-38c3-477c-8492-f7f5234fcac3, connection: MockConnection{localEndpoint=[address=[127.0.0.1]:5702, uuid=17e28fff-e6f9-4454-b036-ebca87d50f8e], remoteEndpoint=[address=[127.0.0.1]:5701, uuid=dffdc17e-38c3-477c-8492-f7f5234fcac3], alive=true}
16:57:16,709  INFO || - [MockServer] hz.SqlBasicSlowTest_inspiring_ardinghelli.generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Created connection to endpoint: [127.0.0.1]:5702-17e28fff-e6f9-4454-b036-ebca87d50f8e, connection: MockConnection{localEndpoint=[address=[127.0.0.1]:5701, uuid=dffdc17e-38c3-477c-8492-f7f5234fcac3], remoteEndpoint=[address=[127.0.0.1]:5702, uuid=17e28fff-e6f9-4454-b036-ebca87d50f8e], alive=true}
16:57:16,709  INFO || - [ClusterService] hz.SqlBasicSlowTest_inspiring_ardinghelli.generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] 

Members {size:2, ver:2} [
	Member [127.0.0.1]:5701 - dffdc17e-38c3-477c-8492-f7f5234fcac3 this
	Member [127.0.0.1]:5702 - 17e28fff-e6f9-4454-b036-ebca87d50f8e
]

16:57:16,796 DEBUG || - [JobCoordinationService] hz.SqlBasicSlowTest_inspiring_ardinghelli.cached.thread-1 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
16:57:16,798  WARN |stressTest[processingGuarantee:atLeastOnce, restartGraceful:false]| - [SqlSTSInnerNonEquiJoinFaultToleranceStressTest] Thread-205 - null
com.hazelcast.core.HazelcastInstanceNotActiveException: Hazelcast instance is not active!
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.serializerFor(AbstractSerializationService.java:558) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:230) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:217) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toData(AbstractSerializationService.java:202) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.map.impl.proxy.MapProxySupport.toDataWithStrategy(MapProxySupport.java:1334) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.map.impl.proxy.MapProxySupport.getInternal(MapProxySupport.java:410) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.map.impl.proxy.MapProxyImpl.get(MapProxyImpl.java:122) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.jet.impl.JobRepository.getJobExecutionRecord(JobRepository.java:615) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.jet.core.JetTestSupport.lambda$waitForNextSnapshot$4(JetTestSupport.java:393) ~[hazelcast-5.4.0-SNAPSHOT-tests.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1285) ~[hazelcast-5.4.0-SNAPSHOT-tests.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1304) ~[hazelcast-5.4.0-SNAPSHOT-tests.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.jet.core.JetTestSupport.waitForNextSnapshot(JetTestSupport.java:392) ~[hazelcast-5.4.0-SNAPSHOT-tests.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.jet.sql_nightly.SqlSTSInnerEquiJoinFaultToleranceStressTest$JobRestarter.run(SqlSTSInnerEquiJoinFaultToleranceStressTest.java:247) [test-classes/:?]
16:57:16,799  INFO |stressTest[processingGuarantee:atLeastOnce, restartGraceful:false]| - [SqlTestSupport] Time-limited test - Removing 0 cached plans in SqlTestSupport.@After
BuildInfo right after stressTest[processingGuarantee:atLeastOnce, restartGraceful:false](com.hazelcast.jet.sql_nightly.SqlSTSInnerNonEquiJoinFaultToleranceStressTest): BuildInfo{version='5.4.0-SNAPSHOT', build='20230604', buildNumber=20230604, revision=f5984a1, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'stressTest[processingGuarantee:atLeastOnce, restartGraceful:false](com.hazelcast.jet.sql_nightly.SqlSTSInnerNonEquiJoinFaultToleranceStressTest):'
16:57:00, accumulated pauses: 538 ms, max pause: 222 ms, pauses over 1000 ms: 0
16:57:05, accumulated pauses: 973 ms, max pause: 209 ms, pauses over 1000 ms: 0
16:57:10, accumulated pauses: 978 ms, max pause: 171 ms, pauses over 1000 ms: 0
16:57:15, accumulated pauses: 1489 ms, max pause: 1482 ms, pauses over 1000 ms: 1


No metrics recorded during the test

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-nightly-force-offload/50/

**Comment by Patras3** [comment]
Failed again on _5.3.z_ with openjdk-17: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-ZuluJDK17-nightly/67/testReport/com.hazelcast.jet.sql_nightly/SqlSTSInnerEquiJoinFaultToleranceStressTest/___/

**Comment by olukas** [comment]
Failed again on _master_ with ibm-11: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Openj9-11-nightly/109/testReport/com.hazelcast.jet.sql_nightly/SqlSTSInnerNonEquiJoinFaultToleranceStressTest/___/

Failed again on _5.3.z_ with oracle-8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-OracleJDK8-nightly/93/testReport/com.hazelcast.jet.sql_nightly/SqlSTSInnerNonEquiJoinFaultToleranceStressTest/___/

<details><summary>However stacktrace is different:</summary>

```
org.junit.runners.model.TestTimedOutException: test timed out after 900 seconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.FutureTask.awaitDone(FutureTask.java:426)
	at java.util.concurrent.FutureTask.get(FutureTask.java:204)
	at com.hazelcast.test.FailOnTimeoutStatement.getResult(FailOnTimeoutStatement.java:80)
	at com.hazelcast.test.FailOnTimeoutStatement.evaluate(FailOnTimeoutStatement.java:58)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:365)
	at com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37)
	at com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:104)
	at com.hazelcast.test.metrics.MetricsRule$1.evaluate(MetricsRule.java:63)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:50)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:29)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:41)
	at com.hazelcast.test.OverridePropertyRule$1.evaluate(OverridePropertyRule.java:66)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:750)
```
</details>

**Comment by olukas** [comment]
Failed again on _5.3.z_ with openjdk-17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-ZuluJDK17-nightly/69/testReport/com.hazelcast.jet.sql_nightly/SqlSTSInnerEquiJoinFaultToleranceStressTest/___/

**Comment by Patras3** [comment]
Failed again on _master_ with OpenJDK17: https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK17-nightly-Esxi7/41/testReport/com.hazelcast.jet.sql_nightly/SqlSTSInnerEquiJoinFaultToleranceStressTest/___/
