### ISSUE TITLE
com.hazelcast.jet.sql_slow.SqlOrderBySlowTest.testSelectWithOrderByAsc

### ISSUE THREAD

**Issue by Patras3** [hazelcast/hazelcast#24715]
_5.3.z_ (commit 4da3953b67b49884a3ef672aa75ee1592ddfb01a)

Failed on ibm-8: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-IbmJDK8-nightly/87/testReport/com.hazelcast.jet.sql_slow/SqlOrderBySlowTest/testSelectWithOrderByAsc_serializationMode_SERIALIZABLE__inMemoryFormat_OBJECT__membersCount_3_/ in variant `[serializationMode:SERIALIZABLE, inMemoryFormat:OBJECT, membersCount:3]`
<details><summary>Stacktrace:</summary>

```
com.hazelcast.core.HazelcastInstanceNotActiveException: Hazelcast instance is not active!
	at com.hazelcast.spi.impl.operationservice.impl.InvocationRegistry.shutdown(InvocationRegistry.java:229)
	at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.shutdownInvocations(OperationServiceImpl.java:562)
	at com.hazelcast.spi.impl.NodeEngineImpl.shutdown(NodeEngineImpl.java:587)
	at com.hazelcast.instance.impl.Node.shutdownServices(Node.java:630)
	at com.hazelcast.instance.impl.Node.shutdown(Node.java:566)
	at com.hazelcast.instance.impl.LifecycleServiceImpl.shutdown(LifecycleServiceImpl.java:101)
	at com.hazelcast.instance.impl.LifecycleServiceImpl.terminate(LifecycleServiceImpl.java:89)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.shutdownAll(HazelcastInstanceFactory.java:304)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.terminateAll(HazelcastInstanceFactory.java:284)
	at com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:47)
	at com.hazelcast.test.OverridePropertyRule$1.evaluate(OverridePropertyRule.java:66)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.lang.Thread.run(Thread.java:825)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-5.maintenance-IbmJDK8-nightly/87/

**Comment by sumnerib** [comment]
Failed again on _5.3.z_ with ibm-8: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-IbmJDK8-nightly/101/testReport/junit/com.hazelcast.jet.sql_slow/SqlOrderBySlowTest/testSelectWithOrderByAndFetchOffsetTail_serializationMode_SERIALIZABLE__inMemoryFormat_OBJECT__membersCount_3_/

Different method same variant: `testSelectWithOrderByAndFetchOffsetTail[serializationMode:SERIALIZABLE, inMemoryFormat:OBJECT, membersCount:3]`

**Comment by olukas** [comment]
Closing the test failure - it doesn't seem to be related to `master` or the latest maintenance stream `5.5.z` and it hasn't fail in the last 3 months. Feel free to reopen test failure if it occurs on `master` or on the latest maintenance stream.
