### ISSUE TITLE
com.hazelcast.internal.cluster.impl.MembershipUpdateTest.shouldNotProcessStaleJoinRequest_afterSplitBrainMerges_whenMasterChanges

### ISSUE THREAD

**Issue by Patras3** [hazelcast/hazelcast#24776]
_master_ (commit 70b645820d2668694fa09f23a2e3f17c28ea06a7)

Failed on openjdk-sts (openjdk-20): https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK-sts/44/testReport/com.hazelcast.internal.cluster.impl/MembershipUpdateTest/shouldNotProcessStaleJoinRequest_afterSplitBrainMerges_whenMasterChanges/
<details><summary>Stacktrace:</summary>

```
com.hazelcast.core.OperationTimeoutException: RegistrationOperation invocation failed to complete due to operation-heartbeat-timeout. Current time: 2023-06-08 17:15:59.370. Start time: 2023-06-08 17:13:58.374. Total elapsed time: 120996 ms. Last operation heartbeat: never. Last operation heartbeat from member: 2023-06-08 17:15:57.152. Invocation{op=com.hazelcast.spi.impl.eventservice.impl.operations.RegistrationOperation{serviceName='null', identityHash=1377124493, partitionId=-1, replicaIndex=0, callId=7, invocationTime=1686244438374 (2023-06-08 17:13:58.374), waitTimeout=-1, callTimeout=60000, tenantControl=com.hazelcast.spi.impl.tenantcontrol.NoopTenantControl@0}, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=60000, firstInvocationTimeMs=1686244438374, firstInvocationTime='2023-06-08 17:13:58.374', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 00:00:00.000', targetAddress=[127.0.0.1]:5702, targetMember=Member [127.0.0.1]:5702 - df1000f6-110f-4556-a34a-8ee994c8bb68, memberListVersion=5, pendingResponse={VOID}, backupsAcksExpected=-1, backupsAcksReceived=0, connection=null}
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.newOperationTimeoutException(InvocationFuture.java:203)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.toExceptionalResult(InvocationFuture.java:167)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:131)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.unblockOtherNode(AbstractInvocationFuture.java:796)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.unblockAll(AbstractInvocationFuture.java:760)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.complete0(AbstractInvocationFuture.java:1241)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.complete(AbstractInvocationFuture.java:1225)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.complete(Invocation.java:690)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.detectAndHandleTimeout(Invocation.java:449)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor$MonitorInvocationsTask.run0(InvocationMonitor.java:326)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor$FixedRateMonitorTask.run(InvocationMonitor.java:282)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1623)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-OpenJDK-sts/44/

**Comment by olukas** [comment]
Closing the test failure - it doesn't seem to be related to `master` or the latest maintenance stream `5.5.z` and it hasn't fail in the last 3 months. Feel free to reopen test failure if it occurs on `master` or on the latest maintenance stream.
