### ISSUE TITLE
com.hazelcast.cache.jsr.CacheExpiryTest/CacheMBStatisticsBeanTest/CacheManagerManagementTest/ClientServerTest - NoClassDefFoundError: org/hamcrest/...

### ISSUE THREAD

**Issue by Patras3** [hazelcast/hazelcast#24781]
_master_ (commit 70b645820d2668694fa09f23a2e3f17c28ea06a7)

Failed on oracle-11: https://jenkins.hazelcast.com/job/Hazelcast-master-sonar/154/testReport/com.hazelcast.cache.jsr/CacheExpiryTest/containsKeyShouldNotCallExpiryPolicyMethods/
<details><summary>Stacktrace:</summary>

```
java.lang.NoClassDefFoundError: org/hamcrest/Matchers
	at org.jsr107.tck.expiry.CacheExpiryTest.containsKeyShouldNotCallExpiryPolicyMethods(CacheExpiryTest.java:489)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)

```
</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: invokeSetValueShouldCallGetExpiry in 0.629 seconds.
Started Running Test: containsKeyShouldNotCallExpiryPolicyMethods
00:50:47,452  INFO |containsKeyShouldNotCallExpiryPolicyMethods| - [CacheService] containsKeyShouldNotCallExpiryPolicyMethods - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Added cache config: CacheConfig{name='com.hazelcast.cache.jsr.CacheExpiryTest', managerPrefix='/hz/', inMemoryFormat=BINARY, backupCount=1, hotRestart=HotRestartConfig{enabled=false, fsync=false}, dataPersistenceConfig=DataPersistenceConfig{enabled=false, fsync=false}, wanReplicationRef=null, merkleTreeConfig=MerkleTreeConfig{enabled=null, depth=10}}
00:50:48,073  INFO |containsKeyShouldNotCallExpiryPolicyMethods| - [CacheService] main - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Removed cache config: CacheConfig{name='com.hazelcast.cache.jsr.CacheExpiryTest', managerPrefix='/hz/', inMemoryFormat=BINARY, backupCount=1, hotRestart=HotRestartConfig{enabled=false, fsync=false}, dataPersistenceConfig=DataPersistenceConfig{enabled=false, fsync=false}, wanReplicationRef=null, merkleTreeConfig=MerkleTreeConfig{enabled=null, depth=10}}

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-sonar/154/

It is regression after https://github.com/hazelcast/hazelcast/pull/24662 and hamcrest dependency removal.

**Comment by Patras3** [comment]
Similar issues (40 failures for `com.hazelcast.client.cache.jsr.*`:
https://jenkins.hazelcast.com/job/Hazelcast-master-sonar/154/testReport/com.hazelcast.client.cache.jsr/
