### ISSUE TITLE
com.hazelcast.partition.PartitionMigrationComputeIntensiveTest.testMigrationStats_afterPartitionsLost_when_NO_MIGRATION [HZ-2623]

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hazelcast#24791]
_master_ (commit f4a36630f6621732d2d54a903334a554f6a835a8)
Failed on oracle-11: https://jenkins.hazelcast.com/job/Hazelcast-master-sonar/157/testReport/junit/com.hazelcast.partition/PartitionMigrationComputeIntensiveTest/testMigrationStats_afterPartitionsLost_when_NO_MIGRATION/
<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: The owner of Partition{partitionId=1698} could not be obtained after 15 retries.
	at org.junit.Assert.fail(Assert.java:89)
	at com.hazelcast.instance.impl.TestUtil.warmupPartitions(TestUtil.java:170)
	at com.hazelcast.instance.impl.TestUtil.warmUpPartitions(TestUtil.java:134)
	at com.hazelcast.test.HazelcastTestSupport.warmUpPartitions(HazelcastTestSupport.java:692)
	at com.hazelcast.partition.PartitionMigrationComputeIntensiveTest.testMigrationStats_afterPartitionsLost_when_NO_MIGRATION(PartitionMigrationComputeIntensiveTest.java:48)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-sonar/157/

**Comment by olukas** [comment]
Failed again on _master_ with oracle-11: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/167/testReport/com.hazelcast.partition/PartitionMigrationComputeIntensiveTest/testMigrationStats_afterPartitionsLost_when_NO_MIGRATION/

**Comment by JamesHazelcast** [comment]
Failure seems non-deterministic and based on machine load more than anything - regardless I have [submitted a PR](https://github.com/hazelcast/hazelcast/pull/24892) which adds logging and more useful information to use in the event of a future test failure.

**Comment by olukas** [comment]
Reopening as issue occurred again on: _master_ (commit c35d35e0d72b730c88934d0752210ad704124a20)
with oracle-11: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/173/testReport/com.hazelcast.partition/PartitionMigrationComputeIntensiveTest/testMigrationStats_afterPartitionsLost_when_NO_MIGRATION/

<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: The owner of Partition{partitionId=1702} could not be obtained after 15 retries.
	at org.junit.Assert.fail(Assert.java:89)
	at com.hazelcast.instance.impl.TestUtil.warmupPartitions(TestUtil.java:170)
	at com.hazelcast.instance.impl.TestUtil.warmUpPartitions(TestUtil.java:134)
	at com.hazelcast.test.HazelcastTestSupport.warmUpPartitions(HazelcastTestSupport.java:692)
	at com.hazelcast.partition.PartitionMigrationComputeIntensiveTest.testMigrationStats_afterPartitionsLost_when_NO_MIGRATION(PartitionMigrationComputeIntensiveTest.java:58)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-sonar/173/

**Comment by olukas** [comment]
Failed again on _master_ with oracle-11: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/175/testReport/com.hazelcast.partition/PartitionMigrationComputeIntensiveTest/testMigrationStats_afterPartitionsLost_when_NO_MIGRATION/
