### ISSUE TITLE
com.hazelcast.mapstore.mariadb.MariaDBGenericMapStoreIntegrationTest [HZ-2571]

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hazelcast#24801]
_master_ (commit 916af89543d2f4a8b274fd03ee1df8c749ed7d54)
Failed on openj9-11 (FIPS mode): https://jenkins.hazelcast.com/job/Hazelcast-master-Openj9-11-fips-nightly/549/testReport/junit/com.hazelcast.mapstore.mariadb/MariaDBGenericMapStoreIntegrationTest/

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-Openj9-11-fips-nightly/549/

Multiple tests fail for `MariaDBGenericMapStoreIntegrationTest`. Example stacktrace for `testExecuteOnEntries`:

<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: 

Expecting actual:
  [Row{[0, name-0]}]
to contain exactly in any order:
  [Row{[0, new-name-0]}]
elements not found:
  [Row{[0, new-name-0]}]
and elements not expected:
  [Row{[0, name-0]}]

	at com.hazelcast.jet.sql.impl.connector.jdbc.JdbcSqlTestSupport.assertJdbcRowsAnyOrder(JdbcSqlTestSupport.java:185)
	at com.hazelcast.mapstore.GenericMapStoreIntegrationTest.testExecuteOnEntries(GenericMapStoreIntegrationTest.java:249)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:839)

```
</details>

**Comment by sumnerib** [comment]
Failed again on _master_ with oracle-11 (force-offload): https://jenkins.hazelcast.com/job/Hazelcast-master-nightly-force-offload/58/testReport/junit/com.hazelcast.mapstore.mariadb/MariaDBGenericMapStoreIntegrationTest/testInstanceShutdown/

**Comment by sumnerib** [comment]
Failed again on _5.3.z_ with openjdk-17: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-ZuluJDK17-nightly/81/testReport/junit/com.hazelcast.mapstore.mariadb/MariaDBGenericMapStoreIntegrationTest/testInstanceShutdown/

**Comment by olukas** [comment]
Closing the test failure - it doesn't seem to be related to `master` or the latest maintenance stream `5.5.z` and it hasn't fail in the last 3 months. Feel free to reopen test failure if it occurs on `master` or on the latest maintenance stream.
