### ISSUE TITLE
com.hazelcast.cache.impl.operation.OnJoinCacheOperationTest.test_cachePostJoinOperationSucceeds_whenJCacheAvailable_noWarningIsLogged [HZ-4453]

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hazelcast#24812]
_master_ (commit a785f366b69f194bf09ed215ec968ac55fabcf84)
Failed on zing-11: https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK11/30/testReport/junit/com.hazelcast.cache.impl.operation/OnJoinCacheOperationTest/test_cachePostJoinOperationSucceeds_whenJCacheAvailable_noWarningIsLogged/

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-ZingJDK11/30/

<details><summary>Stacktrace:</summary>
```
Wanted but not invoked:
nodeEngine.getService(
    "hz:impl:cacheService"
);
-> at com.hazelcast.cache.impl.operation.OnJoinCacheOperationTest.test_cachePostJoinOperationSucceeds_whenJCacheAvailable_noWarningIsLogged(OnJoinCacheOperationTest.java:90)

However, there were exactly 2 interactions with this mock:
nodeEngine.getConfigClassLoader();
-> at com.hazelcast.cache.impl.operation.OnJoinCacheOperation.run(OnJoinCacheOperation.java:60)

nodeEngine.getLogger(
    class com.hazelcast.cache.impl.operation.OnJoinCacheOperation
);
-> at com.hazelcast.spi.impl.operationservice.Operation.getLogger(Operation.java:620)


	at com.hazelcast.cache.impl.operation.OnJoinCacheOperationTest.test_cachePostJoinOperationSucceeds_whenJCacheAvailable_noWarningIsLogged(OnJoinCacheOperationTest.java:90)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:258)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:49)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:120)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:95)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:69)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:146)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)

```
</details>

<details><summary>Standard output:</summary>
```
Started Running Test: sendsConfigObjectOverWire

```
</details>

**Comment by JamesHazelcast** [comment]
This is a Mockito related failure - the output suggests that this mock was not followed:
`mockedStatic.when(() -> JCacheDetector.isJCacheAvailable(any(ClassLoader.class))).thenReturn(true);`

This is suggested due to this output:
```
However, there were exactly 2 interactions with this mock:
nodeEngine.getConfigClassLoader();
-> at com.hazelcast.cache.impl.operation.OnJoinCacheOperation.run(OnJoinCacheOperation.java:60)

nodeEngine.getLogger(
    class com.hazelcast.cache.impl.operation.OnJoinCacheOperation
);
-> at com.hazelcast.spi.impl.operationservice.Operation.getLogger(Operation.java:620)
```

This suggests that within `OnJoinCacheOperation#run`, the first line's condition is checked:
`if (isJCacheAvailable(getNodeEngine().getConfigClassLoader())) `

however it must have failed this check and proceeded to the `else` block, which calls `getLogger()` - this explains both of the calls shown in the output above. For the `else` block to be reached here, the `JCacheDetector.isJCacheAvailable` static mock must have failed - thereby making this an inconsistent Mockito related failure.

Unfortunately we can't easily create an alternative for mocking this class, so I think we're best waiting for a Mockito update which resolves these inconsistent issues to resolve this inconsistent test failure. In the meantime, we should not be particularly worried about it.

**Comment by JamesHazelcast** [comment]
Related: https://github.com/hazelcast/hazelcast/issues/23663

I've just submitted PRs to bump our Mockito version to 5.4.0, which includes some fixes surrounding spied and serialized instances, which is where we've seen quite a few test failures since our upgrade from 3.X - once these PRs are merged, I'd like to see if this test continues to fail; if it does I will rework the test to not use Mockito and close this case.

https://github.com/hazelcast/hazelcast/pull/24889
https://github.com/hazelcast/hazelcast-enterprise/pull/6179

**Comment by sumnerib** [comment]
Failed again on _master_ with zing-11: https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK11/34/testReport/junit/com.hazelcast.cache.impl.operation/OnJoinCacheOperationTest/test_cachePostJoinOperationSucceeds_whenJCacheAvailable_noWarningIsLogged/
