### ISSUE TITLE
com.hazelcast.map.EntryProcessorBouncingNodesTest.testEntryProcessorWhileTwoNodesAreBouncing

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hazelcast#24811]
_master_ (commit a785f366b69f194bf09ed215ec968ac55fabcf84)
Failed on oracle-11: https://jenkins.hazelcast.com/job/Hazelcast-master-OracleJDK11-nightly/952/testReport/junit/com.hazelcast.map/EntryProcessorBouncingNodesTest

Variants:
- [withPredicate=false, withIndex=false]
- [withPredicate=true, withIndex=false]
- [withPredicate=true, withIndex=true]

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-OracleJDK11-nightly/952/

<details><summary>Stacktrace:</summary>
```
java.lang.AssertionError: Driver count can only be 1 when driver type is ALWAYS_UP_MEMBER but found 2
	at com.hazelcast.test.bounce.BounceMemberRule$Builder.build(BounceMemberRule.java:470)
	at com.hazelcast.map.EntryProcessorBouncingNodesTest.<init>(EntryProcessorBouncingNodesTest.java:91)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.lang.Class.newInstance(Class.java:584)
	at com.hazelcast.test.AbstractParameterizedHazelcastClassRunner.createTestUsingFieldInjection(AbstractParameterizedHazelcastClassRunner.java:100)
	at com.hazelcast.test.AbstractParameterizedHazelcastClassRunner.createTest(AbstractParameterizedHazelcastClassRunner.java:73)
	at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:260)
	at org.junit.runners.BlockJUnit4ClassRunner$2.runReflectiveCall(BlockJUnit4ClassRunner.java:309)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:306)
	at com.hazelcast.test.AbstractHazelcastClassRunner.methodBlock(AbstractHazelcastClassRunner.java:228)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:50)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:29)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:41)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:49)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:120)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:95)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:69)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:146)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)

```
</details>

<details><summary>Standard output:</summary>
```
Finished Running Test: testEntryProcessorWhileTwoNodesAreBouncing[withPredicate=false, withIndex=false] in 0.013 seconds.
Started Running Test: testEntryProcessorWhileTwoNodesAreBouncing[withPredicate=true, withIndex=false]
Finished Running Test: testEntryProcessorWhileTwoNodesAreBouncing[withPredicate=true, withIndex=false] in 0.001 seconds.
Started Running Test: testEntryProcessorWhileTwoNodesAreBouncing[withPredicate=true, withIndex=true]
Finished Running Test: testEntryProcessorWhileTwoNodesAreBouncing[withPredicate=true, withIndex=true] in 0.000 seconds.
Started Running Test: formClusterWithTwoMembersTest

```
</details>

**Comment by sumnerib** [comment]
Failed again on _master_ with OpenJDK17: https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK17-nightly-Esxi7/36/testReport/junit/com.hazelcast.map/EntryProcessorBouncingNodesTest
