### ISSUE TITLE
hazelcast map operation hanging indefinitely 

### ISSUE THREAD

**Issue by wuline123** [hazelcast/hazelcast#24832]
map.putIfAbsent are hung on a future .get() call, 
Running Java 8
Hazelcast 5.1.3
>"pool-6-thread-1" #286 prio=5 os_prio=0 tid=0x00007ff87df09000 nid=0x13d waiting on condition [0x00007ff565bfe000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:304)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.manageParking(AbstractInvocationFuture.java:693)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:615)
	at com.hazelcast.client.impl.spi.ClientProxy.invokeOnPartition(ClientProxy.java:188)
	at com.hazelcast.client.impl.spi.ClientProxy.invoke(ClientProxy.java:182)
	at com.hazelcast.client.impl.proxy.ClientMapProxy.putIfAbsentInternal(ClientMapProxy.java:620)
	at com.hazelcast.client.impl.proxy.ClientMapProxy.putIfAbsent(ClientMapProxy.java:592)
	at com.bee.fencho.match.biz.book.lock.CoinPairLock.tryHost(CoinPairLock.java:176)
	- locked <0x000000070500d6e8> (a java.lang.String)
	at com.bee.fencho.match.biz.book.lock.CoinPairLock.tryMakerLogLock(CoinPairLock.java:59)
	at com.bee.fencho.match.biz.book.MakerBook.writeSnapshot(MakerBook.java:260)
	at com.bee.fencho.match.biz.book.MakerBook.writeSnapshotAll(MakerBook.java:246)
	at com.bee.fencho.match.biz.book.MakerBook.initData(MakerBook.java:312)
	at com.bee.fencho.match.biz.book.CacheManger.getMakerBook(CacheManger.java:518)
	- locked <0x000000070627b648> (a java.lang.String)
	at com.bee.fencho.match.biz.book.CacheManger$1.run(CacheManger.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

**Comment by ahmetmircik** [comment]
Not expecting this happen in recent versions, please either try with java 11 or higher or with a newer hazelcast like 5.3.
