### ISSUE TITLE
com.hazelcast.jet.kafka.impl.StreamKafkaPTest.when_processingGuaranteeNone_then_continueFromBeginningAfterJobRestart [HZ-2779]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#24852]
_master_ (commit aab1256d2d6c2efbfa45fd270e1fb8019192fd6c)

Failed on Windows - MicrosoftJDK17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Windows-MicrosoftJDK17/68/testReport/com.hazelcast.jet.kafka.impl/StreamKafkaPTest/when_processingGuaranteeNone_then_continueFromBeginningAfterJobRestart/
<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: expected:<300> but was:<311>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at com.hazelcast.jet.kafka.impl.StreamKafkaPTest.lambda$testWithJobRestart$4(StreamKafkaPTest.java:350)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1165)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1184)
	at com.hazelcast.jet.kafka.impl.StreamKafkaPTest.testWithJobRestart(StreamKafkaPTest.java:350)
	at com.hazelcast.jet.kafka.impl.StreamKafkaPTest.testWithJobRestart(StreamKafkaPTest.java:315)
	at com.hazelcast.jet.kafka.impl.StreamKafkaPTest.when_processingGuaranteeNone_then_continueFromBeginningAfterJobRestart(StreamKafkaPTest.java:249)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-Windows-MicrosoftJDK17/68/

**Comment by vbekiaris** [comment]
Failed again in PR builder https://jenkins.hazelcast.com/job/Hazelcast-pr-builder/19086/

**Comment by k-jamroz** [comment]
This test is generally flawed because it assumes that with `ProcessingGuarantee.NONE` guarantees that the records are not lost. Maybe there are not lost on kafka endpoint, but records in-flight can still be lost. This can be demonstrated by injecting delays in async part of job termination and in the job (to increase number of in-flight elements):

```
Index: hazelcast/src/main/java/com/hazelcast/jet/impl/MasterJobContext.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/hazelcast/src/main/java/com/hazelcast/jet/impl/MasterJobContext.java b/hazelcast/src/main/java/com/hazelcast/jet/impl/MasterJobContext.java
--- a/hazelcast/src/main/java/com/hazelcast/jet/impl/MasterJobContext.java	(revision 9a8365f973ffe2aa8d6708267870383823db5d33)
+++ b/hazelcast/src/main/java/com/hazelcast/jet/impl/MasterJobContext.java	(date 1691763001168)
@@ -721,7 +721,13 @@
     }
 
     void cancelExecutionInvocations(long jobId, long executionId, TerminationMode mode, Runnable callback) {
-        mc.nodeEngine().getExecutionService().execute(ExecutionService.ASYNC_EXECUTOR, () ->
+        mc.nodeEngine().getExecutionService().execute(ExecutionService.ASYNC_EXECUTOR, () -> {
+        try {
+                Thread.sleep(1000);
+        } catch (InterruptedException e) {
+            throw new RuntimeException(e);
+        }
+        System.out.println("SENDING TERMINATE");
                 mc.invokeOnParticipants(plan -> new TerminateExecutionOperation(jobId, executionId, mode),
                         responses -> {
                             if (responses.stream()
@@ -735,7 +741,8 @@
                             if (callback != null) {
                                 callback.run();
                             }
-                        }, null, true));
+                        }, null, true);
+        });
     }
 
     void finalizeExecution(@Nullable Throwable failure) {
```

```
Index: extensions/kafka/src/test/java/com/hazelcast/jet/kafka/impl/StreamKafkaPTest.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/extensions/kafka/src/test/java/com/hazelcast/jet/kafka/impl/StreamKafkaPTest.java b/extensions/kafka/src/test/java/com/hazelcast/jet/kafka/impl/StreamKafkaPTest.java
--- a/extensions/kafka/src/test/java/com/hazelcast/jet/kafka/impl/StreamKafkaPTest.java	(revision 9a8365f973ffe2aa8d6708267870383823db5d33)
+++ b/extensions/kafka/src/test/java/com/hazelcast/jet/kafka/impl/StreamKafkaPTest.java	(date 1691762833424)
@@ -330,21 +330,31 @@
         Pipeline p = Pipeline.create();
         p.readFrom(KafkaSources.<Integer, String, String>kafka(kafkaProperties, ConsumerRecord::value, topicsConfig))
                 .withoutTimestamps()
+                .map(f -> {
+                    System.out.println("Sleep for " + f);
+                    Thread.sleep(500);
+                    return  f;})
                 .writeTo(Sinks.list("sink"));
 
         Job job = instance().getJet().newJob(p, new JobConfig().setProcessingGuarantee(processingGuarantee));
         sleepAtLeastSeconds(3);
 
-        assertTrueEventually(() -> assertEquals(expectedCountBeforeRestart, instance().getList("sink").size()), 5);
+        assertTrueEventually(() -> assertEquals(expectedCountBeforeRestart, instance().getList("sink").size()), 30);
 
         job.restart();
 
-        assertTrueEventually(() -> assertEquals(expectedCountAfterRestart, instance().getList("sink").size()), 5);
+        assertTrueEventually(() -> assertEquals(expectedCountAfterRestart, instance().getList("sink").size()), 30);
     }
 
     @Test
```

**Comment by olukas** [comment]
Failed again on _master_ with Windows - OracleJDK11: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Windows-OracleJDK11/462/testReport/com.hazelcast.jet.kafka.impl/StreamKafkaPTest/when_processingGuaranteeNone_then_continueFromBeginningAfterJobRestart/

**Comment by ihsandemir** [comment]
I got it failed on my PR run at [here](https://jenkins.hazelcast.com/job/Hazelcast-pr-builder/20782/testReport/junit/com.hazelcast.jet.kafka.impl/StreamKafkaPTest/when_processingGuaranteeNone_then_continueFromBeginningAfterJobRestart/)

```
java.lang.AssertionError: expected:<300> but was:<308>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at com.hazelcast.jet.kafka.impl.StreamKafkaPTest.lambda$testWithJobRestart$4(StreamKafkaPTest.java:345)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1165)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1269)
	at com.hazelcast.jet.kafka.impl.StreamKafkaPTest.testWithJobRestart(StreamKafkaPTest.java:345)
	at com.hazelcast.jet.kafka.impl.StreamKafkaPTest.testWithJobRestart(StreamKafkaPTest.java:314)
	at com.hazelcast.jet.kafka.impl.StreamKafkaPTest.when_processingGuaranteeNone_then_continueFromBeginningAfterJobRestart(StreamKafkaPTest.java:248)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by arodionov** [comment]
Failed again in a PR https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/21387/Hazelcast-pr-builder-21387.zip

**Comment by arodionov** [comment]
Failed again in PR https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/21397/Hazelcast-pr-builder-21397.zip

**Comment by olukas** [comment]
Failed again on _master_ with OpenJDK11: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-OpenJDK11-arm64/71/testReport/com.hazelcast.jet.kafka.impl/StreamKafkaPTest/when_processingGuaranteeNoneWithConsumerGroup_then_continueFromLastReadMessageAfterJobRestart/
