### ISSUE TITLE
com.hazelcast.connector.Hz3SerializableTest.serializable_classes_should_have_valid_serialVersionUID and com.hazelcast.internal.serialization.impl.Hz3ImplSerializableTest.serializable_classes_should_have_valid_serialVersionUID (JDK21 early access)

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#24853]
_master_ (commit aab1256d2d6c2efbfa45fd270e1fb8019192fd6c)

**This seems to be the same issue as https://github.com/hazelcast/hazelcast/issues/24677 but it happens only for `com.hazelcast.connector.Hz3SerializableTest` and `com.hazelcast.internal.serialization.impl.Hz3ImplSerializableTest`**

Failed on openjdk-ea (openjdk-21): 
- https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-OpenJDK-ea/40/testReport/com.hazelcast.connector/Hz3SerializableTest/serializable_classes_should_have_valid_serialVersionUID/
- https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-OpenJDK-ea/40/testReport/com.hazelcast.internal.serialization.impl/Hz3ImplSerializableTest/serializable_classes_should_have_valid_serialVersionUID/

<details><summary>Stacktrace:</summary>

```
java.lang.ExceptionInInitializerError
	at com.hazelcast.test.archunit.ArchUnitRules.<clinit>(ArchUnitRules.java:49)
	at com.hazelcast.connector.Hz3SerializableTest.serializable_classes_should_have_valid_serialVersionUID(Hz3SerializableTest.java:41)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.util.NoSuchElementException
	at com.tngtech.archunit.thirdparty.com.google.common.collect.AbstractIndexedListIterator.next(AbstractIndexedListIterator.java:80)
	at com.tngtech.archunit.thirdparty.com.google.common.collect.Iterators.getOnlyElement(Iterators.java:309)
	at com.tngtech.archunit.thirdparty.com.google.common.collect.Iterables.getOnlyElement(Iterables.java:263)
	at com.tngtech.archunit.core.importer.ClassFileImporter.importClass(ClassFileImporter.java:262)
	at com.hazelcast.test.archunit.CompletableFutureUsageCondition.<clinit>(CompletableFutureUsageCondition.java:53)
	... 12 more

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-OpenJDK-ea/40/

**Comment by olukas** [comment]
Failed again on _master_ with openjdk-ea (openjdk-21): 
- https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK-ea/41/testReport/com.hazelcast.connector/Hz3SerializableTest/serializable_classes_should_have_valid_serialVersionUID/
- https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK-ea/41/testReport/com.hazelcast.internal.serialization.impl/Hz3ImplSerializableTest/serializable_classes_should_have_valid_serialVersionUID/

**Comment by Patras3** [comment]
Failed again on _master_ with openjdk-ea (openjdk-21): https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK-ea/42/testReport/com.hazelcast.connector/Hz3SerializableTest/serializable_classes_should_have_valid_serialVersionUID/

**Comment by sumnerib** [comment]
Failed again on _master_ with openjdk-ea (openjdk-21): https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK-ea/43/testReport/junit/com.hazelcast.connector/Hz3SerializableTest/serializable_classes_should_have_valid_serialVersionUID/

**Comment by Patras3** [comment]
Failed again on _master_ with openjdk-ea (openjdk-21): https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK-ea/44/testReport/com.hazelcast.connector/Hz3SerializableTest/serializable_classes_should_have_valid_serialVersionUID/

**Comment by frant-hartm** [comment]
This test is removed in #25051
