### ISSUE TITLE
com.hazelcast.client.impl.spi.impl.ClientInvocationFutureTest [API-2115]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#24851]
_master_ (commit aab1256d2d6c2efbfa45fd270e1fb8019192fd6c)

Failed on OpenJDK17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-OpenJDK17-Esxi7/42/testReport/com.hazelcast.client.impl.spi.impl/ClientInvocationFutureTest/test_thenCombine/

Following tests failed with the same exception:
- `com.hazelcast.client.impl.spi.impl.ClientInvocationFutureTest.test_thenCombine`
- `com.hazelcast.client.impl.spi.impl.ClientInvocationFutureTest.test_applyEither`
- `com.hazelcast.client.impl.spi.impl.ClientInvocationFutureTest.test_acceptEither`
- `com.hazelcast.client.impl.spi.impl.ClientInvocationFutureTest.test_thenApply`
- `com.hazelcast.client.impl.spi.impl.ClientInvocationFutureTest.test_whenComplete`
- `com.hazelcast.client.impl.spi.impl.ClientInvocationFutureTest.test_thenAcceptBoth`
- `com.hazelcast.client.impl.spi.impl.ClientInvocationFutureTest.test_handle`
- `com.hazelcast.client.impl.spi.impl.ClientInvocationFutureTest.test_runAfterBoth`
- `com.hazelcast.client.impl.spi.impl.ClientInvocationFutureTest.test_runAfterEither`
- `com.hazelcast.client.impl.spi.impl.ClientInvocationFutureTest.test_thenCompose`
- `com.hazelcast.client.impl.spi.impl.ClientInvocationFutureTest.test_thenRun`
- `com.hazelcast.client.impl.spi.impl.ClientInvocationFutureTest.test_thenAccept`

<details><summary>Stacktrace:</summary>

```
java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1960)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2095)
	at com.hazelcast.client.impl.spi.impl.ClientInvocationFutureTest.test_thenCombine(ClientInvocationFutureTest.java:243)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)

```
</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: test_interruptionDuringJoin in 2.004 seconds.
Started Running Test: test_whenComplete

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-OpenJDK17-Esxi7/42/

**Comment by ihsandemir** [comment]
Examined the test case and it uses the `ForkJoinPool.commonPool()` for delivering the result of the future. If the pool is occupied while the Jenkins job is running multiple parallel tests, the response delivery may be delayed. The test depends on 10secs timeout which may be exceeded for such times where heavy load on the tests. Hence, theoretically this may happen. I am not able to reproduce the issue. I will send s PR to use the eventual timeout time(120secs) we use for most tests.
