### ISSUE TITLE
CP Subsystem/Raft: member fail to rejoin groups

### ISSUE THREAD

**Issue by lprimak** [hazelcast/hazelcast#24897]
**Describe the bug**
When restarting a CP member, the member doesn't get re-added to CP group and CP group is left in unstable state.

**Expected behavior**
CP member gets re-added to group and functions during Raft

**To Reproduce**
See #24896 for additional test that currently fails due to this issue

**Exception**
After the node rejoins, infinite loop trying to select a new CP leader is seen:
```
WARNING: [127.0.0.1]:5711 [dev] [5.4.0-SNAPSHOT] Retrying invocation: Invocation{op=com.hazelcast.cp.internal.operation.RaftQueryOp{serviceName='hz:core:raft', identityHash=1989326097, partitionId=0, replicaIndex=0, callId=464, invocationTime=1687454514104 (2023-06-22 13:21:54.104), waitTimeout=-1, callTimeout=60000, tenantControl=com.hazelcast.spi.impl.tenantcontrol.NoopTenantControl@0, op=com.hazelcast.cp.internal.raftop.metadata.GetActiveRaftGroupByNameOp{serviceName='hz:core:raft', groupName=default}, groupId=CPGroupId{name='METADATA', seed=0, groupId=0}, policy=LINEARIZABLE}, tryCount=250, tryPauseMillis=500, invokeCount=180, callTimeoutMillis=60000, firstInvocationTimeMs=1687454430092, firstInvocationTime='2023-06-22 13:20:30.092', lastHeartbeatMillis=0, lastHeartbeatTime='1969-12-31 19:00:00.000', targetAddress=null, targetMember=null, memberListVersion=0, pendingResponse={VOID}, backupsAcksExpected=-1, backupsAcksReceived=0, connection=null}, Reason: com.hazelcast.spi.exception.WrongTargetException: WrongTarget! local: Member [127.0.0.1]:5711 - 118e38ef-b2ae-4539-b8a9-93a49497fb58 this, expected-target: null, partitionId: 0, replicaIndex: 0, operation: com.hazelcast.cp.internal.operation.RaftQueryOp, service: hz:core:raft
```

**Additional context**
See slack conversations:
https://hazelcastcommunity.slack.com/archives/C015Q2TUBKL/p1687454583340749
https://hazelcastcommunity.slack.com/archives/C015Q2TUBKL/p1687530351955629

**Comment by vbekiaris** [comment]
CP membership, unlike Hazelcast cluster membership, is not dynamic. As discussed in [CP subsystem management](https://docs.hazelcast.com/imdg/4.2/cp-subsystem/management)

> Unlike the dynamic nature of Hazelcast clusters, CP Subsystem requires manual intervention while expanding/shrinking its size, or when a CP member crashes or becomes unreachable

So that's the expected behaviour of CP subsystem. In the context of [your test](https://github.com/hazelcast/hazelcast/pull/24896/files#diff-82f1c3b280c6c4105e90407cc4c82395ed33aacf7cba6fe461efbcbb65495b79R763), adding an explicit call to promote `hz4` instance is required to get CP members count to 3.

```
    CompletionStage promotionFuture = hz4.getCPSubsystem().getCPSubsystemManagementService().promoteToCPMember();
    // normally you would handle possible failures as discussed in promoteToCPMember javadoc
    promotionFuture.toCompletableFuture().join();
```

**Comment by lprimak** [comment]
Thank you!
This was quite buried in the docs :)
Is there room for enhancement here? I would think in a more 'realistic' dynamic clusters (think k8s) there is room for automation.
Perhaps an 'auto-upgrade' configuration parameter that 'fills' the missing slots in CP groups automatically?

**Comment by lprimak** [comment]
I have created (with great difficulty) code that work correctly to keep CP going while restarting nodes.
However, I've encountered more issues. I am in the process of recording them here by editing the description

**Comment by lprimak** [comment]
In general, the way I am testing this by running https://github.com/flowlogix/hazelcast-issues/ CacheTester, which is an interactive tool that exercises locking and maps (Hazelcast in general).
This is particularly good for uncovering all sorts of bugs :)

**Comment by lprimak** [comment]
Apparently, I am not the only one who is having this issue. Hopefully the test reproducers can shed some more light on this.

**Comment by arodionov** [comment]
This behaviour is by design. We shouldn’t allow the restarted member to join back the cluster automatically, because the cluster thinks that the old member is still present in a cluster, but temporarily became unavailable. 
If you would like to have an automated way that restarted members joining back to the cluster you should use CP persistent feature (that preserves the member state).

**Comment by arodionov** [comment]
> Perhaps an 'auto-upgrade' configuration parameter that 'fills' the missing slots in CP groups automatically?
We have such an option - after 4 hours if the missed member is not joined back to the cluster, it will be auto-removed and will be replaced by an additional member. 
Please take a look https://docs.hazelcast.com/hazelcast/5.3/cp-subsystem/configuration#remove

**Comment by arodionov** [comment]
> I would think in a more 'realistic' dynamic clusters (think k8s) there is room for automation.

Yes, we have a task in our backlog, to align k8s pods auto-restart and scaling up/down with CP members removal and promotion

**Comment by lprimak** [comment]
Thanks for your feedback @arodionov 

> This behaviour is by design. We shouldn’t allow the restarted member to join back the cluster automatically

My current CP use case is only for CP FencedLock. Therefore, the persistence feature does not bring any value.
I wrote the code to auto-promote to CP, however, it's not trivial and IMHO should be a Hazelcast feature. (see https://github.com/hazelcast/hazelcast/issues/24904)

>  because the cluster thinks that the old member is still present in a cluster, but temporarily became unavailable.

Above is incorrect, because nodes that shut down normally do not re-join the CP cluster upon restart either.
In fact, when, in a 3-node CP cluster, one shuts down, I can see there are only 2 nodes present in the logs.
When the 3rd restarts, it will not rejoin by default.

> We have such an option - after 4 hours if the missed member is not joined back to the cluster, it will be auto-removed 

There is an issue with this. See the description (https://github.com/hazelcast/hazelcast/issues/24897#issue-1772435747) - bullet point 2

> Yes, we have a task in our backlog, to align k8s pods auto-restart and scaling up/down with CP members removal and promotion

Can you link to the issue and / or PR so I can test it out?

**Comment by arodionov** [comment]
> In fact, when, in a 3-node CP cluster, one shuts down, I can see there are only 2 nodes present in the logs.

Yes, only in the case of a so-called graceful shutdown the CP member will be automatically removed from the CP subsystem, and in logs, there should be 2 CP members:
```
CP Group Members {groupId: default(6894), size:2, term:1, logIndex:4} [
	CPMember{uuid=791e078d-ef0e-4f56-9139-e03f607c9e4f, address=[192.168.1.13]:5703} - LEADER
	CPMember{uuid=da402e4e-a353-47a7-934c-0189c735f35c, address=[192.168.1.13]:5701} - FOLLOWER this
]
```
But if a CP member has been terminated or stopped responding, we can't distinguish if it's temporarily unavailable (due to network problems) or if it has crashed. In that case, in logs, there will be the only information about cluster status, but the CP subsystem will consider that this CP member is temporarily unavailable:
```
Members {size:2, ver:4} [
	Member [192.168.1.13]:5701 - da402e4e-a353-47a7-934c-0189c735f35c this
	Member [192.168.1.13]:5703 - 791e078d-ef0e-4f56-9139-e03f607c9e4f
] 
```

> Therefore, the persistence feature does not bring any value.
Yes, it will. The CP Persistence only persists the CP member's state in the form of a Raft log (there will be Meta-information about CP members, FencedLock owner, Raft sessions, etc)

**Comment by arodionov** [comment]
> The main critical issue is still (see description, bullet point 1) that cluster becomes unusable and needs to be restarted if CP goes down to one member (reproducer tests in https://github.com/hazelcast/hazelcast/pull/24903)

This is also by design -  if a cluster lost the majority of its members it will be blocked and should be recovered manually https://docs.hazelcast.com/hazelcast/5.3/cp-subsystem/management#handling-a-lost-majority

**Comment by lprimak** [comment]
> This is also by design - if a cluster lost the majority of its members it will be blocked and should be recovered manually

Just tested this scenario, and there is no "majority lost" event delivered in case of normal shutdown of two other members. I think you are referring to scenario if two other members "crash" The scenario I am talking about is normal shutdown of members, not crashes. This should not be any different from "initial state" of CP and should be able to accept new members. 

> Yes, it will. The CP Persistence only persists the CP member's state in the form of a Raft log

a matter of opinion, perhaps in some applications, but not in mine.

**Comment by lprimak** [comment]
Another issue... I have tried to auto-reset the subsystem via code when CP goes down to one member, but I get the below exception...

Currently, there is no way to run a CP system without some manual intervention for simple tasks...
I believe the design (it his is by design indeed) needs to be improved.

```
**** Gone Down to One Member, resetting CP...
Jun 27, 2023 5:37:08 PM com.hazelcast.spi.impl.eventservice.EventService
WARNING: [127.0.0.1]:5710 [dev] [5.3.1] Error while logging processing event
java.util.concurrent.CompletionException: java.lang.IllegalStateException: Not enough cluster members to reset CP Subsystem! Required: 3, available: 2
	at java.base/java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:413)
	at java.base/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2118)
	at com.hazelcast.spi.impl.DeserializingCompletableFuture.join(DeserializingCompletableFuture.java:99)
	at com.flowlogix.hazelcast.cachetester.CacheTester$2.memberRemoved(CacheTester.java:193)
	at com.hazelcast.cp.internal.RaftService.dispatchEvent(RaftService.java:1436)
	at com.hazelcast.cp.internal.RaftService.dispatchEvent(RaftService.java:160)
	at com.hazelcast.spi.impl.eventservice.impl.EventProcessor.process(EventProcessor.java:63)
	at com.hazelcast.spi.impl.eventservice.impl.RemoteEventProcessor.run(RemoteEventProcessor.java:48)
	at com.hazelcast.internal.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:245)
	at com.hazelcast.internal.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:228)
Caused by: java.lang.IllegalStateException: Not enough cluster members to reset CP Subsystem! Required: 3, available: 2
	at com.hazelcast.cp.internal.RaftService.resetCPSubsystem(RaftService.java:303)
	at com.hazelcast.cp.internal.CPSubsystemImpl$CPSubsystemManagementServiceImpl.reset(CPSubsystemImpl.java:214)
	at com.hazelcast.cp.internal.CPSubsystemImpl$CPSubsystemManagementServiceImpl.reset(CPSubsystemImpl.java:170)
	... 7 more
```

**Comment by lprimak** [comment]
Another one: shutdown is not possible in the "unusable" state. What that means in practice is that a CP cluster can't be cleanly and quickly shut down. It gets into the leader election loop again and won't exit.

**Comment by Anonymous-Coward** [comment]
This bug has plagued me for more than a year already, and I'm happy to see it finally documented. Never had time to investigate it in more depth myself, glad someone else did it.

Deploying apps on k8s is pretty widespread, these days, and k8s does move pods around quite frequently, for large and active clusters (like we operate - thousands of pods), in order to optimize load on nodes. Under those circumstances, 4h as a default for kicking pods/hazelcast nodes that no longer exist and not somehow using info from the k8s API to speed up the cleanup/recovery process after a node from a CP group vanishes are both less than ideal decisions re. hazelcast's implementation, IMO.

**Comment by lprimak** [comment]
@arodionov I have added a new test, `whenMemberExitsNormally_thenReceiveEvents` to hazelcast/src/test/java/com/hazelcast/cp/CPGroupAvailabilityListenerTest.java in https://github.com/hazelcast/hazelcast/pull/24903

This test is failing and clearly demonstrates incorrect behavior described here:  https://github.com/hazelcast/hazelcast/issues/24897#issuecomment-1610009241

**Comment by arodionov** [comment]
@lprimak have a PR for your test `whenMemberExitsNormally_thenReceiveEvents` https://github.com/hazelcast/hazelcast/pull/25490

**Comment by lprimak** [comment]
@arodionov Thanks! Looks great!

**Comment by lprimak** [comment]
Spoke too soon... test is not passing (yet?) hopefully soon!

**Comment by lprimak** [comment]
After some back-and-fourth, it's become clear that whenMemberExitsNormally_thenReceiveEvents is no longer necessary after the PR and is working correctly.

**Comment by ioandy** [comment]
I have encountered the same issue, using version 5.2.4. Has this issue been ultimately resolved?

**Comment by lprimak** [comment]
No. First step to fix it will be in Hazelcast 5.4 where the `majorityLost` event would be reliable. but the rest is not fixed yet.

**Comment by Anonymous-Coward** [comment]
After trying for months to get the CP subsystem behaving properly in the face of pod restarts in kubernetes, I finally gave up, and switched to a solution which doesn't use it at all. As far as I can tell, Hazelcast's CP subsystem is not at all a good fit for using in an environment where starting and stopping nodes isn't uncommon.
