### ISSUE TITLE
com.hazelcast.jet.kafka.connect.KafkaConnectIntegrationTest.test_reading_and_writing_to_map [HZ-3116]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#24905]
_master_ (commit cc3348851c1656cd1f77b67e2c23725931042d8d)

Failed on redhat-17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-RedHatJDK17/71/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectIntegrationTest/test_reading_and_writing_to_map/
<details><summary>Stacktrace:</summary>

```
com.hazelcast.jet.JetException: Job resource upload failed
	at com.hazelcast.jet.impl.JobRepository.uploadJobResources(JobRepository.java:261)
	at com.hazelcast.jet.impl.AbstractJetInstance.uploadResources(AbstractJetInstance.java:344)
	at com.hazelcast.jet.impl.AbstractJetInstance.newJobInt(AbstractJetInstance.java:142)
	at com.hazelcast.jet.impl.AbstractJetInstance.newJob(AbstractJetInstance.java:126)
	at com.hazelcast.jet.kafka.connect.KafkaConnectIntegrationTest.test_reading_and_writing_to_map(KafkaConnectIntegrationTest.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:323)
	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350)
	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803)
	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:966)
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:478)
	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472)
	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1500)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1415)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:450)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:421)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:580)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:183)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
	at java.base/java.net.URL.openStream(URL.java:1161)
	at com.hazelcast.jet.impl.JobRepository.loadJarsInZip(JobRepository.java:298)
	at com.hazelcast.jet.impl.JobRepository.uploadJobResources(JobRepository.java:254)
	... 16 more

```
</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: test_reading_without_timestamps in 5.272 seconds.
Started Running Test: test_reading_and_writing_to_map
00:50:24,723  INFO |test_reading_and_writing_to_map| - [MetricsConfigHelper] test_reading_and_writing_to_map - [LOCAL] [dev] [5.4.0-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
00:50:24,723  INFO |test_reading_and_writing_to_map| - [logo] test_reading_and_writing_to_map - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
00:50:24,724  INFO |test_reading_and_writing_to_map| - [system] test_reading_and_writing_to_map - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Copyright (c) 2008-2023, Hazelcast, Inc. All Rights Reserved.
00:50:24,724  INFO |test_reading_and_writing_to_map| - [system] test_reading_and_writing_to_map - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Hazelcast Platform 5.4.0-SNAPSHOT (20230626 - cc33488) starting at [127.0.0.1]:5701
00:50:24,724  INFO |test_reading_and_writing_to_map| - [system] test_reading_and_writing_to_map - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Cluster name: dev
00:50:24,724  INFO |test_reading_and_writing_to_map| - [system] test_reading_and_writing_to_map - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed. For more information, see the documentation for Integrity Checker.
00:50:24,724  INFO |test_reading_and_writing_to_map| - [system] test_reading_and_writing_to_map - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Jet is enabled
00:50:24,727  INFO |test_reading_and_writing_to_map| - [MetricsConfigHelper] test_reading_and_writing_to_map - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
00:50:24,728  INFO |test_reading_and_writing_to_map| - [TpcServerBootstrap] test_reading_and_writing_to_map - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] TPC: disabled
00:50:24,733  WARN |test_reading_and_writing_to_map| - [CPSubsystem] test_reading_and_writing_to_map - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
00:50:24,739  INFO |test_reading_and_writing_to_map| - [JetServiceBackend] test_reading_and_writing_to_map - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Setting number of cooperative threads and default parallelism to 2
00:50:24,739  INFO |test_reading_and_writing_to_map| - [Diagnostics] test_reading_and_writing_to_map - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
00:50:24,740  INFO |test_reading_and_writing_to_map| - [LifecycleService] test_reading_and_writing_to_map - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] [127.0.0.1]:5701 is STARTING
00:50:24,740  INFO |test_reading_and_writing_to_map| - [ClusterService] test_reading_and_writing_to_map - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] 

Members {size:1, ver:1} [
	Member [127.0.0.1]:5701 - b1b5d286-c239-4633-863d-039d679e0e71 this
]

00:50:24,740  INFO |test_reading_and_writing_to_map| - [JobCoordinationService] test_reading_and_writing_to_map - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Jet started scanning for jobs
00:50:24,740 DEBUG |test_reading_and_writing_to_map| - [JobCoordinationService] hz.KafkaConnectIntegrationTest_competent_mayer.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
00:50:24,741  INFO |test_reading_and_writing_to_map| - [LifecycleService] test_reading_and_writing_to_map - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] [127.0.0.1]:5701 is STARTED
00:50:24,835  INFO |test_reading_and_writing_to_map| - [JetTestSupport] Time-limited test - Terminating instanceFactory in JetTestSupport.@After
00:50:24,836  INFO |test_reading_and_writing_to_map| - [LifecycleService] Thread-5 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
00:50:24,836  WARN |test_reading_and_writing_to_map| - [Node] Thread-5 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Terminating forcefully...
00:50:24,836  INFO |test_reading_and_writing_to_map| - [Node] Thread-5 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Shutting down connection manager...
00:50:24,836  INFO |test_reading_and_writing_to_map| - [Node] Thread-5 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Shutting down node engine...
00:50:24,838  INFO |test_reading_and_writing_to_map| - [NodeExtension] Thread-5 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Destroying node NodeExtension.
00:50:24,838  INFO |test_reading_and_writing_to_map| - [Node] Thread-5 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Hazelcast Shutdown is completed in 2 ms.
00:50:24,838  INFO |test_reading_and_writing_to_map| - [LifecycleService] Thread-5 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
00:50:24,839  INFO |test_reading_and_writing_to_map| - [HazelcastTestSupport] Time-limited test - Shutting down node factory as @After action
BuildInfo right after test_reading_and_writing_to_map(com.hazelcast.jet.kafka.connect.KafkaConnectIntegrationTest): BuildInfo{version='5.4.0-SNAPSHOT', build='20230626', buildNumber=20230626, revision=cc33488, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'test_reading_and_writing_to_map(com.hazelcast.jet.kafka.connect.KafkaConnectIntegrationTest):'
00:50:20, accumulated pauses: 67 ms, max pause: 42 ms, pauses over 1000 ms: 0


No metrics recorded during the test

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-RedHatJDK17/71/

**Comment by AleksPeychev** [comment]
Failed again on _master_ with openjdk-17 (MacOS): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-MacOS-OpenJDK17/8/testReport/junit/com.hazelcast.jet.kafka.connect/KafkaConnectIT/test_reading_without_timestamps/

**Comment by Patras3** [comment]
This comment was automatically generated to summarize test results for the last 30 days.

```

For branch: 5.3.z
Builds between : 2024-07-05 21:09 - 2024-07-26 21:09
Jobs: 1, Runs: 4, Passed: 4, Failed: 0, Skipped: 0, Fail Ratio: 0.00%
Run on:
+------------------------------------------------+
| JDK      | PASSED | FAILED | SKIPPED |  RATIO  |
+------------------------------------------------+
| oracle-8 |   4    |   0    |    0    |   0.00% |
+------------------------------------------------+

Builds Timeline:
2024-07-26 21:09 - PASSED (oracle-8):
    https://jenkins.hazelcast.com/job/Hazelcast-5.3.z-OracleJDK8/13/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectIntegrationTest/test_reading_and_writing_to_map/
2024-07-19 21:09 - PASSED (oracle-8):
    https://jenkins.hazelcast.com/job/Hazelcast-5.3.z-OracleJDK8/12/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectIntegrationTest/test_reading_and_writing_to_map/
2024-07-12 21:09 - PASSED (oracle-8):
    https://jenkins.hazelcast.com/job/Hazelcast-5.3.z-OracleJDK8/11/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectIntegrationTest/test_reading_and_writing_to_map/
2024-07-05 21:09 - PASSED (oracle-8):
    https://jenkins.hazelcast.com/job/Hazelcast-5.3.z-OracleJDK8/10/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectIntegrationTest/test_reading_and_writing_to_map/

----------------------------------------
```

**Comment by olukas** [comment]
Closing the test failure - it doesn't seem to be related to `master` or the latest maintenance stream `5.5.z` and it hasn't fail in the last 3 months. Feel free to reopen test failure if it occurs on `master` or on the latest maintenance stream.
