### ISSUE TITLE
com.hazelcast.collection.impl.queue.QueueMigrationTest.testPromotion

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#24906]
_5.3.z_ (commit 5b075f1c5063be2ce3dd22b1004f477283bada32)

Failed on redhat-11: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-RedHatJDK11/90/testReport/com.hazelcast.collection.impl.queue/QueueMigrationTest/testPromotion_comparatorClassName__com_hazelcast_collection_impl_queue_model_VersionedObjectComparator_/

Failed in variant `[comparatorClassName: com.hazelcast.collection.impl.queue.model.VersionedObjectComparator]`.

<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: expected:<100> but was:<101>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at com.hazelcast.collection.impl.queue.QueueMigrationTest.testReplication(QueueMigrationTest.java:105)
	at com.hazelcast.collection.impl.queue.QueueMigrationTest.testPromotion(QueueMigrationTest.java:87)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:829)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-5.maintenance-RedHatJDK11/90/

**Comment by olukas** [comment]
Closing the test failure - it doesn't seem to be related to `master` or the latest maintenance stream `5.5.z` and it hasn't fail in the last 3 months. Feel free to reopen test failure if it occurs on `master` or on the latest maintenance stream.
