### ISSUE TITLE
Test serialization/deserialization on same JVM

### ISSUE THREAD

**Issue by hjohn** [hazelcast/hazelcast#24931]
# Problem

I'm putting custom objects in a map and one in a topic, and wrote an integration test which starts up two Hazelcast instances in the same JVM to verify this works.  The objects are passed along correctly, and the test passes.

However, when the two Hazelcast instances are on different JVM's, a serialization problem occurs (ArrayStoreException):

```
com.hazelcast.nio.serialization.HazelcastSerializationException: Failed to read the Java record
        at com.hazelcast.internal.serialization.impl.compact.record.JavaRecordReader.readRecord(JavaRecordReader.java:48) ~[hazelcast-5.3.0.jar:5.3.0]
        at com.hazelcast.internal.serialization.impl.compact.record.JavaRecordSerializer.read(JavaRecordSerializer.java:106) ~[hazelcast-5.3.0.jar:5.3.0]
        at com.hazelcast.internal.serialization.impl.compact.CompactStreamSerializer.read(CompactStreamSerializer.java:188) ~[hazelcast-5.3.0.jar:5.3.0]
        at com.hazelcast.internal.serialization.impl.compact.CompactStreamSerializer.read(CompactStreamSerializer.java:174) ~[hazelcast-5.3.0.jar:5.3.0]
        at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:44) ~[hazelcast-5.3.0.jar:5.3.0]
        at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:271) ~[hazelcast-5.3.0.jar:5.3.0]
        at com.hazelcast.topic.impl.DataAwareMessage.getMessageObject(DataAwareMessage.java:44) ~[hazelcast-5.3.0.jar:5.3.0]
        at com.***.EventConsumer$Worker.messageReceived(EventConsumer.java:193) ~[esl-hazelcast-1.1.0.jar:1.1.0]
        at com.hazelcast.topic.impl.TopicService.dispatchEvent(TopicService.java:151) ~[hazelcast-5.3.0.jar:5.3.0]
        at com.hazelcast.spi.impl.eventservice.impl.EventProcessor.process(EventProcessor.java:63) ~[hazelcast-5.3.0.jar:5.3.0]
        at com.hazelcast.spi.impl.eventservice.impl.RemoteEventProcessor.run(RemoteEventProcessor.java:48) ~[hazelcast-5.3.0.jar:5.3.0]
        at com.hazelcast.internal.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:245) ~[hazelcast-5.3.0.jar:5.3.0]
        at com.hazelcast.internal.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:228) ~[hazelcast-5.3.0.jar:5.3.0]
Caused by: java.lang.ArrayStoreException: com.hazelcast.internal.serialization.impl.compact.DeserializedGenericRecord
        at com.hazelcast.internal.serialization.impl.compact.CompactInternalGenericRecord.getArrayOfVariableSize(CompactInternalGenericRecord.java:834) ~[hazelcast-5.3.0.jar:5.3.0]
        at com.hazelcast.internal.serialization.impl.compact.CompactInternalGenericRecord.getArrayOfVariableSize(CompactInternalGenericRecord.java:850) ~[hazelcast-5.3.0.jar:5.3.0]
        at com.hazelcast.internal.serialization.impl.compact.CompactInternalGenericRecord.getArrayOfObject(CompactInternalGenericRecord.java:780) ~[hazelcast-5.3.0.jar:5.3.0]
        at com.hazelcast.internal.serialization.impl.compact.DefaultCompactReader.readArrayOfCompact(DefaultCompactReader.java:190) ~[hazelcast-5.3.0.jar:5.3.0]
        at com.hazelcast.internal.serialization.impl.compact.zeroconfig.ValueReaderWriters$CompactArrayReaderWriter.read(ValueReaderWriters.java:1274) ~[hazelcast-5.3.0.jar:5.3.0]
        at com.hazelcast.internal.serialization.impl.compact.zeroconfig.ValueReaderWriters$CompactArrayReaderWriter.read(ValueReaderWriters.java:1259) ~[hazelcast-5.3.0.jar:5.3.0]
        at com.hazelcast.internal.serialization.impl.compact.zeroconfig.ValueReaderWriters$ArrayListReaderWriter.read(ValueReaderWriters.java:1296) ~[hazelcast-5.3.0.jar:5.3.0]
        at com.hazelcast.internal.serialization.impl.compact.zeroconfig.ValueReaderWriters$ArrayListReaderWriter.read(ValueReaderWriters.java:1283) ~[hazelcast-5.3.0.jar:5.3.0]
        at com.hazelcast.internal.serialization.impl.compact.record.JavaRecordSerializer$ComponentReaderWriterAdapter.readComponent(JavaRecordSerializer.java:187) ~[hazelcast-5.3.0.jar:5.3.0]
        at com.hazelcast.internal.serialization.impl.compact.record.JavaRecordReader.readRecord(JavaRecordReader.java:44) ~[hazelcast-5.3.0.jar:5.3.0]
        ... 12 common frames omitted

```

# Desired

For testing purposes, it would be good if the above behavior and exception was detected while running the JUnit test. I think it isn't detected because Hazelcast when running two instances on the same JVM can avoid doing serialization.  It would be good if this could be forced somehow.

# Alternatives

Try writing the test with multiple JVM's or TestContainers.

**Comment by hjohn** [comment]
It seems this may actually have been a different issue, where the other JVM involved did not have one of the classes that was being serialized.  The `ArrayStoreException` is a bit confusing in this regard.  When the other JVM is provided with the correct class, the problem disappeared.
