### ISSUE TITLE
com.hazelcast.jet.impl.connector.PostgreReadJdbcPPropertiesTest and com.hazelcast.jet.impl.connector.MySQLReadJdbcPPropertiesTest

### ISSUE THREAD

**Issue by Patras3** [hazelcast/hazelcast#24946]
_master_ (commit e7514d2ef9f960f59694fb0534357f8b996a403b)

Failed on Windows - OracleJDK11: https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-OracleJDK11/454/testReport/com.hazelcast.jet.impl.connector/PostgreReadJdbcPPropertiesTest/___/
<details><summary>Stacktrace:</summary>

```
java.lang.IllegalStateException: Previous attempts to find a Docker environment failed. Will not retry. Please see logs and check configuration
	at org.testcontainers.dockerclient.DockerClientProviderStrategy.getFirstValidStrategy(DockerClientProviderStrategy.java:231)
	at org.testcontainers.DockerClientFactory.getOrInitializeStrategy(DockerClientFactory.java:150)
	at org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:191)
	at org.testcontainers.DockerClientFactory$1.getDockerClient(DockerClientFactory.java:104)
	at com.github.dockerjava.api.DockerClientDelegate.authConfig(DockerClientDelegate.java:109)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:321)
	at com.hazelcast.test.jdbc.PostgresDatabaseProvider.createDatabase(PostgresDatabaseProvider.java:35)
	at com.hazelcast.jet.impl.connector.ReadJdbcPPropertiesTest.initializeBeforeClass(ReadJdbcPPropertiesTest.java:57)
	at com.hazelcast.jet.impl.connector.PostgreReadJdbcPPropertiesTest.beforeClass(PostgreReadJdbcPPropertiesTest.java:33)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:41)
	at com.hazelcast.test.OverridePropertyRule$1.evaluate(OverridePropertyRule.java:66)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)

```
</details>

<details><summary>Standard output:</summary>

```
19:55:00,594  INFO || - [MetricsConfigHelper] Time-limited test - [LOCAL] [dev] [5.4.0-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
19:55:00,595  INFO || - [logo] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
19:55:00,595  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Copyright (c) 2008-2023, Hazelcast, Inc. All Rights Reserved.
19:55:00,595  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Hazelcast Platform 5.4.0-SNAPSHOT (20230703 - e7514d2) starting at [127.0.0.1]:5701
19:55:00,595  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Cluster name: dev
19:55:00,595  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed. For more information, see the documentation for Integrity Checker.
19:55:00,595  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Jet is enabled
19:55:00,599  INFO || - [MetricsConfigHelper] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
19:55:00,599  INFO || - [TpcServerBootstrap] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] TPC: disabled
19:55:00,604  WARN || - [CPSubsystem] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
19:55:00,607  INFO || - [JetServiceBackend] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Setting number of cooperative threads and default parallelism to 2
19:55:00,608  INFO || - [Diagnostics] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
19:55:00,608  INFO || - [LifecycleService] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] [127.0.0.1]:5701 is STARTING
19:55:00,608  INFO || - [ClusterService] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] 

Members {size:1, ver:1} [
	Member [127.0.0.1]:5701 - 0e3a349c-0182-4678-8add-414e55b0e88b this
]

19:55:00,608  INFO || - [JobCoordinationService] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Jet started scanning for jobs
19:55:00,608  INFO || - [LifecycleService] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] [127.0.0.1]:5701 is STARTED
Started Running Test: test_smallFiles
19:55:00,609 DEBUG || - [JobCoordinationService] hz.ReadFilesPTest_zen_vaughan.cached.thread-6 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-Windows-OracleJDK11/454/

The same problem is for MySQLReadJdbcPPropertiesTest test: https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-OracleJDK11/454/testReport/com.hazelcast.jet.impl.connector/MySQLReadJdbcPPropertiesTest/___/

Both tests must have:
`assumeDockerEnabled();`

**Comment by sumnerib** [comment]
Failed again on _master_ with Windows - MicrosoftJDK17: 

- https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK17/71/testReport/junit/com.hazelcast.jet.impl.connector/MySQLReadJdbcPPropertiesTest/___/
- https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK17/71/testReport/junit/com.hazelcast.jet.impl.connector/PostgreReadJdbcPPropertiesTest/___/
