### ISSUE TITLE
com.hazelcast.sql.impl.client.SqlResubmissionTest.when_failingSelectBeforeAnyDataIsFetched[clusterFailure:NodeTerminationClusterFailure, mode:RETRY_SELECTS]

### ISSUE THREAD

**Issue by Patras3** [hazelcast/hazelcast#25029]
_master_ (commit b90a0f3305945b416350f1e16b7841eb15f68e82)

Failed on ibm-11: https://jenkins.hazelcast.com/job/Hazelcast-master-Openj9-11-nightly/113/testReport/com.hazelcast.sql.impl.client/SqlResubmissionTest/when_failingSelectBeforeAnyDataIsFetched_clusterFailure_NodeTerminationClusterFailure__mode_RETRY_SELECTS_/
<details><summary>Stacktrace:</summary>

```
com.hazelcast.sql.HazelcastSqlException: Client is not connected
	at com.hazelcast.sql.impl.CoreQueryUtils.toPublicException(CoreQueryUtils.java:50)
	at com.hazelcast.sql.impl.client.SqlClientService.rethrow(SqlClientService.java:502)
	at com.hazelcast.sql.impl.client.SqlClientService.getQueryConnection(SqlClientService.java:381)
	at com.hazelcast.sql.impl.client.SqlClientService.execute(SqlClientService.java:112)
	at com.hazelcast.sql.impl.client.SqlResubmissionTest.executeInLoop(SqlResubmissionTest.java:136)
	at com.hazelcast.sql.impl.client.SqlResubmissionTest.testStatement(SqlResubmissionTest.java:120)
	at com.hazelcast.sql.impl.client.SqlResubmissionTest.when_failingSelectBeforeAnyDataIsFetched(SqlResubmissionTest.java:103)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: com.hazelcast.sql.impl.QueryException: Client is not connected
	at com.hazelcast.sql.impl.QueryException.error(QueryException.java:65)
	... 17 more

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-Openj9-11-nightly/113/

**Comment by k-jamroz** [comment]
Yet another false positive due to https://github.com/hazelcast/hazelcast/issues/24862#issuecomment-1724042722

```
  <testcase name="" classname="com.hazelcast.jet.sql_nightly.SqlSTSInnerNonEquiJoinFaultToleranceStressTest" time="883.622">
    <error message="test timed out after 900 seconds" type="org.junit.runners.model.TestTimedOutException">
```
