### ISSUE TITLE
NullPointerException in the AddressCodec.encode [API-2094]

### ISSUE THREAD

**Issue by kwart** [hazelcast/hazelcast#25032]
**Describe the bug**
Sometimes, `AddressCodec.encode` fails with a NPE

```
{"time":"2023-07-17T16:31:18Z","thread":"hz.musing_mestorf.scheduled.thread-","logger":"c.h.s.i.e.ExecutionService","level":"ERROR","msg":"[10.0.57.6]:5701 [de-g820ygmb] [5.3.0] Failed to execute java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@f178f63[Completed exceptionally: java.lang.NullPointerException] java.lang.NullPointerException: null
	at com.hazelcast.client.impl.protocol.codec.custom.AddressCodec.encode(AddressCodec.java:39) ~[hazelcast-enterprise-5.3.0-nlc.jar:5.3.0]
	at com.hazelcast.client.impl.protocol.codec.custom.MemberInfoCodec.encode(MemberInfoCodec.java:44) ~[hazelcast-enterprise-5.3.0-nlc.jar:5.3.0]
	at com.hazelcast.client.impl.protocol.codec.builtin.ListMultiFrameCodec.encode(ListMultiFrameCodec.java:42) ~[hazelcast-enterprise-5.3.0-nlc.jar:5.3.0]
	at com.hazelcast.client.impl.protocol.codec.ClientAddClusterViewListenerCodec.encodeMembersViewEvent(ClientAddClusterViewListenerCodec.java:89) ~[hazelcast-enterprise-5.3.0-nlc.jar:5.3.0]
	at com.hazelcast.client.impl.ClusterViewListenerService.getMemberListViewMessage(ClusterViewListenerService.java:176) ~[hazelcast-enterprise-5.3.0-nlc.jar:5.3.0]
	at com.hazelcast.client.impl.ClusterViewListenerService.pushView(ClusterViewListenerService.java:89) ~[hazelcast-enterprise-5.3.0-nlc.jar:5.3.0]
	at com.hazelcast.spi.impl.executionservice.impl.DelegateAndSkipOnConcurrentExecutionDecorator$DelegateDecorator.run(DelegateAndSkipOnConcurrentExecutionDecorator.java:77) ~[hazelcast-enterprise-5.3.0-nlc.jar:5.3.0]
	at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217) ~[hazelcast-enterprise-5.3.0-nlc.jar:5.3.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76) [hazelcast-enterprise-5.3.0-nlc.jar:5.3.0]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:111) [hazelcast-enterprise-5.3.0-nlc.jar:5.3.0]
"}
```

**Expected behavior**
No NPE in my member log. :smile: 

**To Reproduce**
Run this simple App (tested with 5.3.0). You should see the NPE in the log.

```java
import java.util.concurrent.TimeUnit;

import com.hazelcast.config.AdvancedNetworkConfig;
import com.hazelcast.config.Config;
import com.hazelcast.config.JoinConfig;
import com.hazelcast.config.ServerSocketEndpointConfig;
import com.hazelcast.core.Hazelcast;
import com.hazelcast.core.HazelcastInstance;

public class App2 {

    public static void main(String[] args) throws InterruptedException {
        for (int i = 1; i <= 3; i++) {
            Hazelcast.newHazelcastInstance(createConfig(i));
        }
        System.out.println(">>> Cluster started");
        TimeUnit.SECONDS.sleep(1);
        System.out.println(">>> Starting lite-member");
        Config c = new Config().setLiteMember(true);
        JoinConfig join = c.getAdvancedNetworkConfig().setEnabled(true).getJoin();
        join.getTcpIpConfig().setEnabled(true).addMember("localhost:5701");
        HazelcastInstance hz = Hazelcast.newHazelcastInstance(c);
        hz.getCluster().shutdown();
    }

    private static Config createConfig(int i) {
        Config c = new Config();
        AdvancedNetworkConfig advancedNetworkConfig = c.getAdvancedNetworkConfig();
        advancedNetworkConfig.setMemberEndpointConfig(new ServerSocketEndpointConfig().setPort(5700 + i).setPortAutoIncrement(false))
                .setClientEndpointConfig(new ServerSocketEndpointConfig().setPort(30000 + i).setPortAutoIncrement(false));
        JoinConfig join = advancedNetworkConfig.setEnabled(true).getJoin();
        join.getTcpIpConfig().setEnabled(true).addMember("localhost:5701").addMember("localhost:5702")
                .addMember("localhost:5703");
        return c;
    }

}
```

**Comment by ihsandemir** [comment]
I examined the issue. It seems like you missed the `setClientEndpointConfig` call when you prepared the lite member config, hence in the published member list it is missing the endpoint qualifier of type `CLIENT` and hence we can not determine the address. If you use the below code, it works for me. 

```
package com.hazelcast.client;

import java.util.concurrent.TimeUnit;

import com.hazelcast.config.AdvancedNetworkConfig;
import com.hazelcast.config.Config;
import com.hazelcast.config.JoinConfig;
import com.hazelcast.config.ServerSocketEndpointConfig;
import com.hazelcast.core.Hazelcast;
import com.hazelcast.core.HazelcastInstance;

public class App2 {

    public static void main(String[] args) throws InterruptedException {
        for (int i = 1; i <= 3; i++) {
            Hazelcast.newHazelcastInstance(createConfig(i));
        }
        System.out.println(">>> Cluster started");
        TimeUnit.SECONDS.sleep(1);
        System.out.println(">>> Starting lite-member");
        Config c = createConfig(4);
        c.setLiteMember(true);
/*
        JoinConfig join = c.getAdvancedNetworkConfig().setEnabled(true).getJoin();
        join.getTcpIpConfig().setEnabled(true).addMember("localhost:5701");
*/
        HazelcastInstance hz = Hazelcast.newHazelcastInstance(c);
        hz.getCluster().shutdown();
    }

    private static Config createConfig(int i) {
        Config c = new Config();
        AdvancedNetworkConfig advancedNetworkConfig = c.getAdvancedNetworkConfig();
        advancedNetworkConfig.setMemberEndpointConfig(new ServerSocketEndpointConfig().setPort(5700 + i).setPortAutoIncrement(false))
                .setClientEndpointConfig(new ServerSocketEndpointConfig().setPort(30000 + i).setPortAutoIncrement(false));
        JoinConfig join = advancedNetworkConfig.setEnabled(true).getJoin();
        join.getTcpIpConfig().setEnabled(true).addMember("localhost:5701").addMember("localhost:5702")
                .addMember("localhost:5703");
        return c;
    }

}
```

It is the `clientAddressOf` method at [this](https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/client/impl/ClusterViewListenerService.java#L173) line which returns null if the `CLIENT` endpoint qualifier is not in the member. 

Well, at `ClientClusterServideImpl` we have a fallback to the member address in such cases at [this](https://github.com/hazelcast/hazelcast/blob/v5.3.1/hazelcast/src/main/java/com/hazelcast/client/impl/spi/impl/ClientClusterServiceImpl.java#L234C23-L234C23) line. We can make a similar change as suggested at [this](https://github.com/hazelcast/hazelcast/pull/25097) draft PR, what do you think @kwart ?

**Comment by kwart** [comment]
It's a good question. Could the member address used there break things somewhere else?
That brings me to a question: Is having some members without the client endpoint OK? I guess so, users could use one member as the access point for client protocol, and only basic (non-smart) clients would connect through it. If we don't want to allow such scenarios, then it would rather deserve a config-check during member start. And fail fast.

**Comment by ihsandemir** [comment]
Whether to allow clients to so some members and not allow to others is NOT a feature we currently have. Even if we do not allow in the client by not using a fallback address, the user can still modify the code and connect to the server port hence it is not a security proven approach. Hence, if we want such a capability, we should rather disallow any client protocol requests which are identified by `Protocols.CLIENT_BINARY="CP2"` but we currently have no such feature. Hence, for the client point of view, it makes sense to try every possibility to connect to the server. If we need a security protection, it better be at the server side, right?

Hence, I think that our fix would be ok for the client point of view, what do you think?

**Comment by kwart** [comment]
Sounds reasonable. Thanks for the explanation.
