### ISSUE TITLE
java.lang.NoSuchMethodError: 'void com.hazelcast.internal.nio.IOUtil.closeResource(java.io.Closeable)'

### ISSUE THREAD

**Issue by sumeet610** [hazelcast/hazelcast#25058]
**Describe the bug**
We are using hazelcast-5.3.1.jar, upgraded from 5.2.3. After upgrade started seeing below stacktrace. We are also using hazelcast-kubernetes-2.3.3.jar. Hazelcast and hazelcast kubernetes both have com.hazelcast.kubernetes.KubernetesConfig java file.
The method com.hazelcast.kubernetes.KubernetesConfig#readFileContents() in hazelcast-kubernetes-2.2.3.jar is using
IOUtil.closeResource(is); This is passing InputStream as an argument which implements Closeable interface not AutoCloseable interface. But the method IOUtil.closeResource(AutoCloseable closeable) is changed from IOUtil.closeResource(Closeable closeable) in hazelcast-5.3.1.jar causing NoSuchMethodError

java.lang.NoSuchMethodError: 'void com.hazelcast.internal.nio.IOUtil.closeResource(java.io.Closeable)'
        at com.hazelcast.kubernetes.KubernetesConfig.readFileContents(KubernetesConfig.java:164)
        at com.hazelcast.kubernetes.KubernetesConfig.readAccountToken(KubernetesConfig.java:140)
        at com.hazelcast.kubernetes.KubernetesConfig.getApiToken(KubernetesConfig.java:125)
        at com.hazelcast.kubernetes.KubernetesConfig.<init>(KubernetesConfig.java:94)
        at com.hazelcast.kubernetes.HazelcastKubernetesDiscoveryStrategy.<init>(HazelcastKubernetesDiscoveryStrategy.java:42)
        at com.hazelcast.kubernetes.HazelcastKubernetesDiscoveryStrategyFactory.newDiscoveryStrategy(HazelcastKubernetesDiscoveryStrategyFactory.java:68)
        at com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.loadDiscoveryStrategies(DefaultDiscoveryService.java:151)
        at com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.<init>(DefaultDiscoveryService.java:58)
        at com.hazelcast.spi.discovery.impl.DefaultDiscoveryServiceProvider.newDiscoveryService(DefaultDiscoveryServiceProvider.java:29)
        at com.hazelcast.instance.impl.Node.createDiscoveryService(Node.java:363)
        at com.hazelcast.instance.impl.Node.<init>(Node.java:284)
        at com.hazelcast.instance.impl.HazelcastInstanceImpl.createNode(HazelcastInstanceImpl.java:149)
        at com.hazelcast.instance.impl.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:118)
        at com.hazelcast.instance.impl.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:217)
        at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:196)
        at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:134)
        at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:61)

**Expected behavior**
Should not throw NoSuchMethodError

**To Reproduce**

**Additional context**

Added the reference with code snippets.

Common details that we're often interested in:
Added the reference with code snippets.
![image](https://github.com/hazelcast/hazelcast/assets/6690088/8a584cc6-aabd-4c14-b62a-cc7bc5e204c7)

![image](https://github.com/hazelcast/hazelcast/assets/6690088/31beadc2-2ccb-4f71-8ed1-b249c2aef219)

**Comment by vbekiaris** [comment]
@sumeet610 the `hazelcast-kubernetes` artifact is now [deprecated](https://github.com/hazelcast/hazelcast-kubernetes#deprecated-hazelcast-kubernetes-plugin-has-been-merged-with-hazelcast). Starting with Hazelcast 5.0, several discovery plugins, including `hazelcast-kubernetes`, are included in the core `hazelcast` repository & artifact. 

You should remove the `hazelcast-kubernetes` dependency from your application and it should work just fine.

**Comment by sumeet610** [comment]
Thanks for the update
