### ISSUE TITLE
com.hazelcast.jet.sql.impl.opt.prunability.PartitionPruningIT

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hazelcast#25060]
_master_ (commit 086fb213ef8dbac5873e54d7e2a38a686b6933ad)
Failed on ibm-11: https://jenkins.hazelcast.com/job/Hazelcast-master-Openj9-11-nightly/114/testReport/junit/com.hazelcast.jet.sql.impl.opt.prunability/PartitionPruningIT/

<details><summary>Stacktrace:</summary>

```
java.lang.ClassCastException: com.hazelcast.internal.server.tcp.TcpServerConnectionManager incompatible with com.hazelcast.internal.server.FirewallingServer$FirewallingServerConnectionManager
	at com.hazelcast.test.PacketFiltersUtil.getConnectionManager(PacketFiltersUtil.java:48)
	at com.hazelcast.test.PacketFiltersUtil.resetPacketFiltersFrom(PacketFiltersUtil.java:52)
	at com.hazelcast.jet.SimpleTestInClusterSupport.supportAfter(SimpleTestInClusterSupport.java:116)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:381)
	at com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37)
	at com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:104)
	at com.hazelcast.test.metrics.MetricsRule$1.evaluate(MetricsRule.java:63)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:50)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:29)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:41)
	at com.hazelcast.test.OverridePropertyRule$1.evaluate(OverridePropertyRule.java:66)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:840)

```

</details>

Other failures
* `test_renamingKeyPruned`:
```
java.lang.NoSuchFieldError: com/hazelcast/jet/sql/impl/calcite/parser/HazelcastSqlParser.FACTORY
```
* `test_renamingKeyNotPruned`
```
java.lang.NoClassDefFoundError: com.hazelcast.jet.sql.impl.parse.QueryParser (initialization failure)
	at java.base/java.lang.J9VMInternals.initializationAlreadyFailed(J9VMInternals.java:172)
```

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-Openj9-11-nightly/114/

**Comment by sumnerib** [comment]
Failed again on _master_ with oracle-11: https://jenkins.hazelcast.com/job/Hazelcast-master-sonar/199/testReport/junit/com.hazelcast.jet.sql.impl.opt.prunability/PartitionPruningIT/

**Comment by sumnerib** [comment]
Fails constantly on `oracle-11`.

**Comment by Patras3** [comment]
Failed again on _master_ with ibm-11: https://jenkins.hazelcast.com/job/Hazelcast-master-Openj9-11-nightly/115/testReport/com.hazelcast.jet.sql.impl.opt.prunability/PartitionPruningIT/

**Comment by k-jamroz** [comment]
test no longer exits
