### ISSUE TITLE
Timeouts initializing testcontainers on MacOS

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hazelcast#25079]
_master_ (commit a18d597bb5cc1ca0f722e9167daabef428cc6780)
Failed on MacOS: https://jenkins.hazelcast.com/job/Hazelcast-master-MacOS-ZuluJDK11/233/

<details><summary>Example Stacktrace:</summary>

```
org.junit.runners.model.TestTimedOutException: test timed out after 900 seconds
	at app//org.testcontainers.DockerClientFactory.getOrInitializeStrategy(DockerClientFactory.java:143)
	at app//org.testcontainers.DockerClientFactory.getTransportConfig(DockerClientFactory.java:156)
	at app//org.testcontainers.DockerClientFactory.getRemoteDockerUnixSocketPath(DockerClientFactory.java:171)
	at app//org.testcontainers.containers.localstack.LocalStackContainer.<init>(LocalStackContainer.java:112)
	at app//org.testcontainers.containers.localstack.LocalStackContainer.<init>(LocalStackContainer.java:94)
	at app//com.hazelcast.jet.kinesis.KinesisIntegrationTest.beforeClass(KinesisIntegrationTest.java:102)
	at java.base@11.0.19/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@11.0.19/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base@11.0.19/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@11.0.19/java.lang.reflect.Method.invoke(Method.java:566)
	at app//org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at app//org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at app//org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at app//org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
	at app//org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at app//org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at app//com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:41)
	at app//com.hazelcast.test.OverridePropertyRule$1.evaluate(OverridePropertyRule.java:66)
	at app//org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at app//org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.base@11.0.19/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base@11.0.19/java.lang.Thread.run(Thread.java:829)

```
</details>

<details><summary>Example Standard output:</summary>

```
Started Running Test: serializable_classes_should_have_valid_serialVersionUID

```

</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-MacOS-ZuluJDK11/233/

Tests:

[com.hazelcast.jet.kinesis.KinesisFailureTest.(?)](https://jenkins.hazelcast.com/job/Hazelcast-master-MacOS-ZuluJDK11/lastSuccessfulBuild/testReport/junit/com.hazelcast.jet.kinesis/KinesisFailureTest/___/)
[com.hazelcast.jet.kinesis.KinesisIntegrationTest.(?)](https://jenkins.hazelcast.com/job/Hazelcast-master-MacOS-ZuluJDK11/lastSuccessfulBuild/testReport/junit/com.hazelcast.jet.kinesis/KinesisIntegrationTest/___/)
[com.hazelcast.mapstore.mongodb.MongoGenericMapStoreTest.(?)](https://jenkins.hazelcast.com/job/Hazelcast-master-MacOS-ZuluJDK11/lastSuccessfulBuild/testReport/junit/com.hazelcast.mapstore.mongodb/MongoGenericMapStoreTest/___/)
[com.hazelcast.jet.s3.S3MockTest.(?)](https://jenkins.hazelcast.com/job/Hazelcast-master-MacOS-ZuluJDK11/lastSuccessfulBuild/testReport/junit/com.hazelcast.jet.s3/S3MockTest/___/)

**Comment by ldziedziul** [comment]
The box could be overloaded. if it happen again re-open this and let me know
