### ISSUE TITLE
com.hazelcast.internal.crdt.pncounter.PNCounterConsistencyLostTest.driverCanContinueSessionByCallingReset [HZ-3481]

### ISSUE THREAD

**Issue by Patras3** [hazelcast/hazelcast#25106]
_5.3.z_ (commit 979fe347301b3eb7589708f510a40d17a7dcaf0f)

Failed on microsoft-17: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-MicrosoftJDK17/43/testReport/com.hazelcast.internal.crdt.pncounter/PNCounterConsistencyLostTest/driverCanContinueSessionByCallingReset/
<details><summary>Stacktrace:</summary>

```
java.lang.IllegalStateException: Attempt to reuse the same operation in multiple invocations. Operation is com.hazelcast.internal.crdt.pncounter.operations.AddOperation{serviceName='hz:impl:PNCounterService', identityHash=308350910, partitionId=-1, replicaIndex=0, callId=4, invocationTime=1690780704742 (2023-07-31 05:18:24.742), waitTimeout=-1, callTimeout=60000, tenantControl=com.hazelcast.spi.impl.tenantcontrol.NoopTenantControl@0, name=counter}
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:545)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:241)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:71)
	at com.hazelcast.internal.crdt.pncounter.PNCounterProxy.invokeInternal(PNCounterProxy.java:195)
	at com.hazelcast.internal.crdt.pncounter.PNCounterProxy.invokeInternal(PNCounterProxy.java:205)
	at com.hazelcast.internal.crdt.pncounter.PNCounterProxy.invoke(PNCounterProxy.java:159)
	at com.hazelcast.internal.crdt.pncounter.PNCounterProxy.addAndGet(PNCounterProxy.java:100)
	at com.hazelcast.internal.crdt.pncounter.PNCounterConsistencyLostTest.mutate(PNCounterConsistencyLostTest.java:80)
	at com.hazelcast.internal.crdt.pncounter.AbstractPNCounterConsistencyLostTest.driverCanContinueSessionByCallingReset(AbstractPNCounterConsistencyLostTest.java:56)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)

```
</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: consistencyLostExceptionIsThrownWhenTargetReplicaDisappears in 0.830 seconds.
05:18:25,326  INFO |driverCanContinueSessionByCallingReset| - [LifecycleService] Thread-42392 - [127.0.0.1]:5703 [dev] [5.3.2-SNAPSHOT] [127.0.0.1]:5703 is SHUTTING_DOWN
05:18:25,326  WARN |driverCanContinueSessionByCallingReset| - [Node] Thread-42392 - [127.0.0.1]:5703 [dev] [5.3.2-SNAPSHOT] Terminating forcefully...
05:18:25,326  INFO |driverCanContinueSessionByCallingReset| - [Node] Thread-42392 - [127.0.0.1]:5703 [dev] [5.3.2-SNAPSHOT] Shutting down connection manager...
05:18:25,326  INFO |driverCanContinueSessionByCallingReset| - [MockServer] Thread-42392 - [127.0.0.1]:5702 [dev] [5.3.2-SNAPSHOT] Removed connection to endpoint: [address=[127.0.0.1]:5703, uuid=4b31b2cc-ce1c-4752-bb30-b2ff7d8b60d3], connection: MockConnection{localEndpoint=[address=[127.0.0.1]:5702, uuid=011b555a-bb62-48e2-a03e-beea1da68cb6], remoteEndpoint=[address=[127.0.0.1]:5703, uuid=4b31b2cc-ce1c-4752-bb30-b2ff7d8b60d3], alive=false}
05:18:25,326  INFO |driverCanContinueSessionByCallingReset| - [MockServer] Thread-42392 - [127.0.0.1]:5703 [dev] [5.3.2-SNAPSHOT] Removed connection to endpoint: [address=[127.0.0.1]:5702, uuid=011b555a-bb62-48e2-a03e-beea1da68cb6], connection: MockConnection{localEndpoint=[address=[127.0.0.1]:5703, uuid=4b31b2cc-ce1c-4752-bb30-b2ff7d8b60d3], remoteEndpoint=[address=[127.0.0.1]:5702, uuid=011b555a-bb62-48e2-a03e-beea1da68cb6], alive=false}
05:18:25,326  INFO |driverCanContinueSessionByCallingReset| - [MembershipManager] Thread-42392 - [127.0.0.1]:5702 [dev] [5.3.2-SNAPSHOT] Removing Member [127.0.0.1]:5703 - 4b31b2cc-ce1c-4752-bb30-b2ff7d8b60d3 lite
05:18:25,326  INFO |driverCanContinueSessionByCallingReset| - [TransactionManagerService] hz.PNCounterConsistencyLostTest_silly_hellman.cached.thread-2 - [127.0.0.1]:5702 [dev] [5.3.2-SNAPSHOT] Committing/rolling-back live transactions of [127.0.0.1]:5703, UUID: 4b31b2cc-ce1c-4752-bb30-b2ff7d8b60d3
05:18:25,326  INFO |driverCanContinueSessionByCallingReset| - [ClusterService] Thread-42392 - [127.0.0.1]:5702 [dev] [5.3.2-SNAPSHOT] 

Members {size:1, ver:5} [
	Member [127.0.0.1]:5702 - 011b555a-bb62-48e2-a03e-beea1da68cb6 this
]

05:18:25,327  INFO |driverCanContinueSessionByCallingReset| - [Node] Thread-42392 - [127.0.0.1]:5703 [dev] [5.3.2-SNAPSHOT] Shutting down node engine...
05:18:25,330  INFO |driverCanContinueSessionByCallingReset| - [NodeExtension] Thread-42392 - [127.0.0.1]:5703 [dev] [5.3.2-SNAPSHOT] Destroying node NodeExtension.
05:18:25,330  INFO |driverCanContinueSessionByCallingReset| - [Node] Thread-42392 - [127.0.0.1]:5703 [dev] [5.3.2-SNAPSHOT] Hazelcast Shutdown is completed in 4 ms.
05:18:25,330  INFO |driverCanContinueSessionByCallingReset| - [LifecycleService] Thread-42392 - [127.0.0.1]:5703 [dev] [5.3.2-SNAPSHOT] [127.0.0.1]:5703 is SHUTDOWN
05:18:25,330  INFO |driverCanContinueSessionByCallingReset| - [LifecycleService] Thread-42392 - [127.0.0.1]:5702 [dev] [5.3.2-SNAPSHOT] [127.0.0.1]:5702 is SHUTTING_DOWN
05:18:25,330  WARN |driverCanContinueSessionByCallingReset| - [Node] Thread-42392 - [127.0.0.1]:5702 [dev] [5.3.2-SNAPSHOT] Terminating forcefully...
05:18:25,330  INFO |driverCanContinueSessionByCallingReset| - [Node] Thread-42392 - [127.0.0.1]:5702 [dev] [5.3.2-SNAPSHOT] Shutting down connection manager...
05:18:25,330  INFO |driverCanContinueSessionByCallingReset| - [Node] Thread-42392 - [127.0.0.1]:5702 [dev] [5.3.2-SNAPSHOT] Shutting down node engine...
05:18:25,333  INFO |driverCanContinueSessionByCallingReset| - [NodeExtension] Thread-42392 - [127.0.0.1]:5702 [dev] [5.3.2-SNAPSHOT] Destroying node NodeExtension.
05:18:25,333  INFO |driverCanContinueSessionByCallingReset| - [Node] Thread-42392 - [127.0.0.1]:5702 [dev] [5.3.2-SNAPSHOT] Hazelcast Shutdown is completed in 3 ms.
05:18:25,333  INFO |driverCanContinueSessionByCallingReset| - [LifecycleService] Thread-42392 - [127.0.0.1]:5702 [dev] [5.3.2-SNAPSHOT] [127.0.0.1]:5702 is SHUTDOWN
05:18:25,333  INFO |driverCanContinueSessionByCallingReset| - [LifecycleService] Thread-42392 - [127.0.0.1]:5701 [dev] [5.3.2-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
05:18:25,333  INFO |driverCanContinueSessionByCallingReset| - [Node] Thread-42392 - [127.0.0.1]:5701 [dev] [5.3.2-SNAPSHOT] Node is already shutting down... Waiting for shutdown process to complete...
05:18:25,333  INFO |driverCanContinueSessionByCallingReset| - [LifecycleService] Thread-42392 - [127.0.0.1]:5701 [dev] [5.3.2-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
BuildInfo right after driverCanContinueSessionByCallingReset(com.hazelcast.internal.crdt.pncounter.PNCounterConsistencyLostTest): BuildInfo{version='5.3.2-SNAPSHOT', build='20230731', buildNumber=20230731, revision=979fe34, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'driverCanContinueSessionByCallingReset(com.hazelcast.internal.crdt.pncounter.PNCounterConsistencyLostTest):'
05:18:20, accumulated pauses: 607 ms, max pause: 558 ms, pauses over 1000 ms: 0
05:18:25, accumulated pauses: 0 ms, max pause: 0 ms, pauses over 1000 ms: 0


No metrics recorded during the test

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-5.maintenance-MicrosoftJDK17/43/

**Comment by sumnerib** [comment]
Failed again on _5.3.z_ with openjdk-17: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-ZuluJDK17/75/testReport/junit/com.hazelcast.internal.crdt.pncounter/PNCounterConsistencyLostTest/
