### ISSUE TITLE
com.hazelcast.spi.tenantcontrol.TenantControlTest.basicMapTest[tenantControl: true]

### ISSUE THREAD

**Issue by Patras3** [hazelcast/hazelcast#25107]
_master_ (commit 36978579bebe58493739af202be657441a15e796)

Failed on OpenJDK17: https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK17-Esxi7/48/testReport/com.hazelcast.spi.tenantcontrol/TenantControlTest/basicMapTest_tenantControl__true_/
<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: expected:<1> but was:<6>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at com.hazelcast.spi.tenantcontrol.TenantControlTest.basicMapTest(TenantControlTest.java:185)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)

```
</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: testDestroyEventContext_destroyRemovesTenantControl[tenantControl: true] in 0.013 seconds.
Started Running Test: basicMapTest[tenantControl: true]
23:02:07,061  INFO |basicMapTest[tenantControl: true]| - [MetricsConfigHelper] basicMapTest - [LOCAL] [dev] [5.4.0-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
23:02:07,062  INFO |basicMapTest[tenantControl: true]| - [logo] basicMapTest - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
23:02:07,062  INFO |basicMapTest[tenantControl: true]| - [system] basicMapTest - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Copyright (c) 2008-2023, Hazelcast, Inc. All Rights Reserved.
23:02:07,062  INFO |basicMapTest[tenantControl: true]| - [system] basicMapTest - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Hazelcast Platform 5.4.0-SNAPSHOT (20230730 - 3697857) starting at [127.0.0.1]:5701
23:02:07,062  INFO |basicMapTest[tenantControl: true]| - [system] basicMapTest - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Cluster name: dev
23:02:07,062  INFO |basicMapTest[tenantControl: true]| - [system] basicMapTest - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed. For more information, see the documentation for Integrity Checker.
23:02:07,062  INFO |basicMapTest[tenantControl: true]| - [system] basicMapTest - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Jet is enabled
23:02:07,067  INFO |basicMapTest[tenantControl: true]| - [MetricsConfigHelper] basicMapTest - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
23:02:07,067  INFO |basicMapTest[tenantControl: true]| - [TpcServerBootstrap] basicMapTest - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] TPC: disabled
23:02:07,071  WARN |basicMapTest[tenantControl: true]| - [CPSubsystem] basicMapTest - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
23:02:07,073  INFO |basicMapTest[tenantControl: true]| - [JetServiceBackend] basicMapTest - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Setting number of cooperative threads and default parallelism to 2
23:02:07,074  INFO |basicMapTest[tenantControl: true]| - [Diagnostics] basicMapTest - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
23:02:07,074  INFO |basicMapTest[tenantControl: true]| - [LifecycleService] basicMapTest - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] [127.0.0.1]:5701 is STARTING
23:02:07,074  INFO |basicMapTest[tenantControl: true]| - [ClusterService] basicMapTest - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] 

Members {size:1, ver:1} [
	Member [127.0.0.1]:5701 - 7a3af42f-9c6a-432e-9e38-2a8b644f1652 this
]

23:02:07,074  INFO |basicMapTest[tenantControl: true]| - [JobCoordinationService] basicMapTest - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Jet started scanning for jobs
23:02:07,074  INFO |basicMapTest[tenantControl: true]| - [LifecycleService] basicMapTest - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] [127.0.0.1]:5701 is STARTED
23:02:07,074 DEBUG |basicMapTest[tenantControl: true]| - [JobCoordinationService] hz.TenantControlTest_wizardly_nightingale.cached.thread-6 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
23:02:07,075  INFO |basicMapTest[tenantControl: true]| - [PartitionStateManager] basicMapTest - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Initializing cluster partition table arrangement...
23:02:07,076  INFO |basicMapTest[tenantControl: true]| - [TenantControlTest] hz.TenantControlTest_wizardly_nightingale.event-42600 - Added: 1
23:02:10,119 DEBUG |basicMapTest[tenantControl: true]| - [JobRepository] hz.TenantControlTest_wizardly_nightingale.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
23:02:10,122  INFO |basicMapTest[tenantControl: true]| - [HazelcastTestSupport] main - Shutting down node factory as @After action
23:02:10,122  INFO |basicMapTest[tenantControl: true]| - [LifecycleService] main - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
23:02:10,122  WARN |basicMapTest[tenantControl: true]| - [Node] main - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Terminating forcefully...
23:02:10,122  INFO |basicMapTest[tenantControl: true]| - [Node] main - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Shutting down connection manager...
23:02:10,122  INFO |basicMapTest[tenantControl: true]| - [Node] main - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Shutting down node engine...
23:02:10,131  INFO |basicMapTest[tenantControl: true]| - [NodeExtension] main - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Destroying node NodeExtension.
23:02:10,131  INFO |basicMapTest[tenantControl: true]| - [Node] main - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Hazelcast Shutdown is completed in 9 ms.
23:02:10,131  INFO |basicMapTest[tenantControl: true]| - [LifecycleService] main - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
BuildInfo right after basicMapTest[tenantControl: true](com.hazelcast.spi.tenantcontrol.TenantControlTest): BuildInfo{version='5.4.0-SNAPSHOT', build='20230730', buildNumber=20230730, revision=3697857, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'basicMapTest[tenantControl: true](com.hazelcast.spi.tenantcontrol.TenantControlTest):'
23:02:05, accumulated pauses: 3067 ms, max pause: 3038 ms, pauses over 1000 ms: 1
23:02:10, accumulated pauses: 0 ms, max pause: 0 ms, pauses over 1000 ms: 0



```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-OpenJDK17-Esxi7/48/

**Comment by Patras3** [comment]
Failed again on _master_ with openjdk-ea (openjdk-21): https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK-ea/46/testReport/com.hazelcast.spi.tenantcontrol/TenantControlTest/basicMapTest_tenantControl__true_/

**Comment by vbekiaris** [comment]
This test failure seems to be a regression introduced by #25061 . Test did not fail after tens of thousands of executions with the previous commit d180dd51 but fails after ~100-200 repetitions with commit 36978579 . @ahmetmircik could you please take a look?

**Comment by sumnerib** [comment]
Failed again on _master_ with openjdk-ea (openjdk-21): https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK-ea/47/testReport/junit/com.hazelcast.spi.tenantcontrol/TenantControlTest/basicMapTest_tenantControl__true_/

**Comment by ahmetmircik** [comment]
@vbekiaris please see: https://github.com/hazelcast/hazelcast/pull/25159
