### ISSUE TITLE
com.hazelcast.map.MapContainerCreationUponDestroyStressTest.testNewRecordStores_sharesSameMapContainerInstance_afterMapDestroy [HZ-4305]

### ISSUE THREAD

**Issue by Patras3** [hazelcast/hazelcast#25112]
_master_ (commit 36978579bebe58493739af202be657441a15e796)

Failed on oracle-11 (little-endian): https://jenkins.hazelcast.com/job/Hazelcast-master-nightly-little-endian/37/testReport/com.hazelcast.map/MapContainerCreationUponDestroyStressTest/testNewRecordStores_sharesSameMapContainerInstance_afterMapDestroy/
<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: expected:<MapContainer{name='map', destroyed=false}> but was:<MapContainer{name='map', destroyed=true}>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:120)
	at org.junit.Assert.assertEquals(Assert.java:146)
	at com.hazelcast.map.MapContainerCreationUponDestroyStressTest.assertRecordStoresSharesSameMapContainerInstance(MapContainerCreationUponDestroyStressTest.java:113)
	at com.hazelcast.map.MapContainerCreationUponDestroyStressTest.testNewRecordStores_sharesSameMapContainerInstance_afterMapDestroy(MapContainerCreationUponDestroyStressTest.java:99)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-nightly-little-endian/37/

**Comment by Patras3** [comment]
Failed again on _master_ with ibm-11: https://jenkins.hazelcast.com/job/Hazelcast-master-Openj9-11-nightly/115/testReport/com.hazelcast.map/MapContainerCreationUponDestroyStressTest/testNewRecordStores_sharesSameMapContainerInstance_afterMapDestroy/

**Comment by Patras3** [comment]
Failed again on _master_ with oracle-21: https://jenkins.hazelcast.com/job/Hazelcast-master-OracleJDK21-nightly/2/testReport/com.hazelcast.map/MapContainerCreationUponDestroyStressTest/testNewRecordStores_sharesSameMapContainerInstance_afterMapDestroy/

**Comment by Patras3** [comment]
It's a constant test failure:
```
master
Builds between  : 2024-01-24 02:15 - 2024-01-28 17:13
Jobs: 12 Runs: 12, Passed: 0, Failed: 12, Ratio: 0.00%
Failed on:
* corretto-21 (1x)
* microsoft-21 (1x)
* oracle-17 (2x)
* openjdk-sts (1x)
* unknown (2x)
* oracle-21 (1x)
* redhat-21 (1x)
* zing-21 (1x)
* openjdk-17 (1x)
* openjdk-21 (1x)
```
