### ISSUE TITLE
com.hazelcast.ringbuffer.impl.RingbufferBasicDistributedTest.addAsync_whenOverwrite_andNoTTL and com.hazelcast.ringbuffer.impl.RingbufferBasicDistributedTest.addAsync_whenOverwrite_andTTL

### ISSUE THREAD

**Issue by Patras3** [hazelcast/hazelcast#25111]
_5.3.z_ (commit 979fe347301b3eb7589708f510a40d17a7dcaf0f)

Failed on openj9-11: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-Openj9-11/96/testReport/junit/com.hazelcast.ringbuffer.impl/RingbufferBasicDistributedTest/addAsync_whenOverwrite_andNoTTL/
<details><summary>Stacktrace:</summary>

```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.base/java.util.concurrent.ConcurrentHashMap.containsKey(ConcurrentHashMap.java:964)
	at org.mockito.internal.util.concurrent.WeakConcurrentMap.containsKey(WeakConcurrentMap.java:77)
	at org.mockito.internal.util.concurrent.WeakConcurrentMap$WithInlinedExpunction.containsKey(WeakConcurrentMap.java:265)
	at org.mockito.internal.creation.bytebuddy.MockMethodAdvice.isMock(MockMethodAdvice.java:183)
	at org.mockito.internal.creation.bytebuddy.MockMethodAdvice.isMocked(MockMethodAdvice.java:188)
	at java.base/java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
	at java.base/java.util.concurrent.ConcurrentHashMap.containsKey(ConcurrentHashMap.java:964)
	at com.hazelcast.internal.serialization.impl.compact.CompactStreamSerializer.isRegisteredAsCompact(CompactStreamSerializer.java:87)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.lookupDefaultSerializer(AbstractSerializationService.java:626)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.serializerForClass(AbstractSerializationService.java:584)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.serializerFor(AbstractSerializationService.java:578)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:230)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:217)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:208)
	at com.hazelcast.spi.impl.operationservice.impl.OutboundOperationHandler.toPacket(OutboundOperationHandler.java:69)
	at com.hazelcast.spi.impl.operationservice.impl.OutboundOperationHandler.send(OutboundOperationHandler.java:64)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeRemote(Invocation.java:629)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:599)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:558)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:241)
	at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.invokeOnPartition(OperationServiceImpl.java:367)
	at com.hazelcast.spi.impl.AbstractDistributedObject.invokeOnPartition(AbstractDistributedObject.java:86)
	at com.hazelcast.ringbuffer.impl.RingbufferProxy.tailSequence(RingbufferProxy.java:111)
	at com.hazelcast.ringbuffer.impl.RingbufferAbstractTest.addAsync_whenOverwrite(RingbufferAbstractTest.java:281)
	at com.hazelcast.ringbuffer.impl.RingbufferAbstractTest.addAsync_whenOverwrite_andNoTTL(RingbufferAbstractTest.java:262)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:840)

```
</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: addAsync_whenOverwrite_andTTL in 300.082 seconds.
BuildInfo right after addAsync_whenOverwrite_andNoTTL(com.hazelcast.ringbuffer.impl.RingbufferBasicDistributedTest): BuildInfo{version='5.3.2-SNAPSHOT', build='20230731', buildNumber=20230731, revision=979fe34, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'addAsync_whenOverwrite_andNoTTL(com.hazelcast.ringbuffer.impl.RingbufferBasicDistributedTest):'
02:48:35, accumulated pauses: 54 ms, max pause: 5 ms, pauses over 1000 ms: 0
02:48:40, accumulated pauses: 57 ms, max pause: 0 ms, pauses over 1000 ms: 0
02:48:45, accumulated pauses: 129 ms, max pause: 74 ms, pauses over 1000 ms: 0
02:48:50, accumulated pauses: 60 ms, max pause: 0 ms, pauses over 1000 ms: 0
02:48:55, accumulated pauses: 59 ms, max pause: 0 ms, pauses over 1000 ms: 0
02:49:00, accumulated pauses: 55 ms, max pause: 0 ms, pauses over 1000 ms: 0
02:49:05, accumulated pauses: 58 ms, max pause: 0 ms, pauses over 1000 ms: 0
02:49:10, accumulated pauses: 56 ms, max pause: 0 ms, pauses over 1000 ms: 0
02:49:15, accumulated pauses: 57 ms, max pause: 0 ms, pauses over 1000 ms: 0
02:49:20, accumulated pauses: 57 ms, max pause: 0 ms, pauses over 1000 ms: 0
02:49:25, accumulated pauses: 60 ms, max pause: 0 ms, pauses over 1000 ms: 0
02:49:30, accumulated pauses: 61 ms, max pause: 0 ms, pauses over 1000 ms: 0
02:49:35, accumulated pauses: 60 ms, max pause: 0 ms, pauses over 1000 ms: 0
02:49:40, accumulated pauses: 62 ms, max pause: 0 ms, pauses over 1000 ms: 0
02:49:45, accumulated pauses: 66 ms, max pause: 5 ms, pauses over 1000 ms: 0
02:49:50, accumulated pauses: 58 ms, max pause: 0 ms, pauses over 1000 ms: 0
02:49:55, accumulated pauses: 60 ms, max pause: 0 ms, pauses over 1000 ms: 0
02:50:00, accumulated pauses: 60 ms, max pause: 0 ms, pauses over 1000 ms: 0
02:50:05, accumulated pauses: 59 ms, max pause: 0 ms, pauses over 1000 ms: 0
02:50:10, accumulated pauses: 63 ms, max pause: 0 ms, pauses over 1000 ms: 0
02:50:15, accumulated pauses: 116 ms, max pause: 58 ms, pauses over 1000 ms: 0
02:50:20, accumulated pauses: 61 ms, max pause: 0 ms, pauses over 1000 ms: 0
02:50:25, accumulated pauses: 59 ms, max pause: 0 ms, pauses over 1000 ms: 0
02:50:30, accumulated pauses: 59 ms, max pause: 0 ms, pauses over 1000 ms: 0
02:50:35, accumulated pauses: 58 ms, max pause: 0 ms, pauses over 1000 ms: 0
02:50:40, accumulated pauses: 61 ms, max pause: 0 ms, pauses over 1000 ms: 0
02:50:45, accumulated pauses: 65 ms, max pause: 0 ms, pauses over 1000 ms: 0
02:50:50, accumulated pauses: 61 ms, max pause: 0 ms, pauses over 1000 ms: 0
02:50:55, accumulated pauses: 64 ms, max pause: 0 ms, pauses over 1000 ms: 0
02:51:00, accumulated pauses: 62 ms, max pause: 0 ms, pauses over 1000 ms: 0
02:51:05, accumulated pauses: 65 ms, max pause: 0 ms, pauses over 1000 ms: 0
02:51:10, accumulated pauses: 63 ms, max pause: 0 ms, pauses over 1000 ms: 0
02:51:15, accumulated pauses: 61 ms, max pause: 0 ms, pauses over 1000 ms: 0
02:51:20, accumulated pauses: 65 ms, max pause: 0 ms, pauses over 1000 ms: 0
02:51:25, accumulated pauses: 63 ms, max pause: 0 ms, pauses over 1000 ms: 0
02:51:30, accumulated pauses: 66 ms, max pause: 0 ms, pauses over 1000 ms: 0
02:51:35, accumulated pauses: 65 ms, max pause: 0 ms, pauses over 1000 ms: 0
02:51:40, accumulated pauses: 65 ms, max pause: 0 ms, pauses over 1000 ms: 0
02:51:45, accumulated pauses: 66 ms, max pause: 0 ms, pauses over 1000 ms: 0
02:51:50, accumulated pauses: 66 ms, max pause: 0 ms, pauses over 1000 ms: 0
02:51:55, accumulated pauses: 65 ms, max pause: 0 ms, pauses over 1000 ms: 0
02:52:00, accumulated pauses: 63 ms, max pause: 0 ms, pauses over 1000 ms: 0
02:52:05, accumulated pauses: 64 ms, max pause: 0 ms, pauses over 1000 ms: 0
02:52:10, accumulated pauses: 158 ms, max pause: 94 ms, pauses over 1000 ms: 0
02:52:15, accumulated pauses: 65 ms, max pause: 0 ms, pauses over 1000 ms: 0
02:52:20, accumulated pauses: 65 ms, max pause: 0 ms, pauses over 1000 ms: 0
02:52:25, accumulated pauses: 63 ms, max pause: 0 ms, pauses over 1000 ms: 0
02:52:30, accumulated pauses: 64 ms, max pause: 0 ms, pauses over 1000 ms: 0
02:52:35, accumulated pauses: 64 ms, max pause: 0 ms, pauses over 1000 ms: 0
02:52:40, accumulated pauses: 65 ms, max pause: 0 ms, pauses over 1000 ms: 0
02:52:45, accumulated pauses: 65 ms, max pause: 0 ms, pauses over 1000 ms: 0
02:52:50, accumulated pauses: 65 ms, max pause: 0 ms, pauses over 1000 ms: 0
02:52:55, accumulated pauses: 63 ms, max pause: 0 ms, pauses over 1000 ms: 0
02:53:00, accumulated pauses: 65 ms, max pause: 0 ms, pauses over 1000 ms: 0
02:53:05, accumulated pauses: 65 ms, max pause: 0 ms, pauses over 1000 ms: 0
02:53:10, accumulated pauses: 65 ms, max pause: 0 ms, pauses over 1000 ms: 0
02:53:15, accumulated pauses: 64 ms, max pause: 0 ms, pauses over 1000 ms: 0
02:53:20, accumulated pauses: 65 ms, max pause: 0 ms, pauses over 1000 ms: 0
02:53:25, accumulated pauses: 65 ms, max pause: 0 ms, pauses over 1000 ms: 0
02:53:30, accumulated pauses: 67 ms, max pause: 0 ms, pauses over 1000 ms: 0
02:53:35, accumulated pauses: 101 ms, max pause: 40 ms, pauses over 1000 ms: 0


No metrics recorded during the test

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-5.maintenance-Openj9-11/96/

**Comment by Patras3** [comment]
Failed again on _5.3.z_ with openj9-11: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-Openj9-11/96/testReport/junit/com.hazelcast.ringbuffer.impl/RingbufferBasicDistributedTest/addAsync_whenOverwrite_andTTL/

**Comment by olukas** [comment]
Failed again on _5.3.z_ with openj9-17: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-Openj9-17/96/testReport/com.hazelcast.ringbuffer.impl/RingbufferBasicDistributedTest/

**Comment by olukas** [comment]
Failed again on _5.4.z_ with openj9-17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-Openj9-17/114/testReport/com.hazelcast.ringbuffer.impl/RingbufferBasicDistributedTest/

**Comment by Patras3** [comment]
Failed again on _5.4.z_ with openj9-17: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-Openj9-17/116/testReport/junit/com.hazelcast.ringbuffer.impl/RingbufferBasicDistributedTest/

**Comment by AleksPeychev** [comment]
Failed again on _5.4.z_ with openj9-17: 
 - https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-Openj9-17/118/testReport/junit/com.hazelcast.ringbuffer.impl/RingbufferBasicDistributedTest/addAsync_whenOverwrite_andTTL/
 - https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-Openj9-17/118/testReport/junit/com.hazelcast.ringbuffer.impl/RingbufferBasicDistributedTest/addAsync_whenOverwrite_andNoTTL/

**Comment by olukas** [comment]
Closing the test failure - it doesn't seem to be related to `master` or the latest maintenance stream `5.5.z`. Feel free to reopen test failure if it occurs on `master` or on the latest maintenance stream.
