### ISSUE TITLE
com.hazelcast.jet.impl.execution.init.JetJobPrunabilityTest.test_simpleDag_takesMemberAndCoordinator

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hazelcast#25157]
_master_ (commit 427b85e76f1c0493409d0a2ab832fe740a19d8dc)
Failed on OpenJDK17: https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK17-Esxi7/49/testReport/junit/com.hazelcast.jet.impl.execution.init/JetJobPrunabilityTest/test_simpleDag_takesMemberAndCoordinator/

<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: 

Expecting ArrayList:
  [[], [0, 1, 1, 0], [], []]
to contain:
  [[0, 1, 0, 1]]
but could not find the following element(s):
  [[0, 1, 0, 1]]

	at com.hazelcast.jet.impl.execution.init.JetJobPrunabilityTest.test_simpleDag_takesMemberAndCoordinator(JetJobPrunabilityTest.java:144)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: test_dagWithBranching in 0.033 seconds.
Started Running Test: test_simpleDag_takesMemberAndCoordinator
00:23:48,584 DEBUG || - [JobClassLoaderService] hz.JetJobPrunabilityTest_competent_snyder.cached.thread-12 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Creating job classLoader for job 0a47-9717-0006-0001
00:23:48,584 DEBUG || - [JobClassLoaderService] hz.JetJobPrunabilityTest_competent_snyder.cached.thread-12 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Create processor classloader map for job 0a47-9717-0006-0001
00:23:48,586  INFO || - [JobCoordinationService] hz.JetJobPrunabilityTest_competent_snyder.cached.thread-12 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Starting job 0a47-9717-0006-0001 based on submit request
00:23:48,589  INFO || - [MasterJobContext] hz.JetJobPrunabilityTest_competent_snyder.cached.thread-12 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Didn't find any snapshot to restore for job '0a47-9717-0006-0001', execution 0a47-9717-0007-0001
00:23:48,589  INFO || - [MasterJobContext] hz.JetJobPrunabilityTest_competent_snyder.cached.thread-12 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Start executing job '0a47-9717-0006-0001', execution 0a47-9717-0007-0001, execution graph in DOT format:
digraph DAG {
	"Generator" [localParallelism=2];
	"Printer" [localParallelism=2];
	"Generator" -> "Printer" [label="distributed to [127.0.0.1]:5701-partitioned", queueSize=1024];
}
HINT: You can use graphviz or http://viz-js.com to visualize the printed graph.
00:23:48,589 DEBUG || - [MasterJobContext] hz.JetJobPrunabilityTest_competent_snyder.cached.thread-12 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Building execution plan for job '0a47-9717-0006-0001', execution 0a47-9717-0007-0001
00:23:48,589 DEBUG || - [ExecutionPlanBuilder] hz.JetJobPrunabilityTest_competent_snyder.cached.thread-12 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Adding required member [127.0.0.1]:5701 to partition-pruned job members
00:23:48,591 DEBUG || - [MasterJobContext] hz.JetJobPrunabilityTest_competent_snyder.cached.thread-12 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Built execution plans for job '0a47-9717-0006-0001', execution 0a47-9717-0007-0001
00:23:48,591 DEBUG || - [InitExecutionOperation] hz.JetJobPrunabilityTest_competent_snyder.cached.thread-12 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Initializing execution plan for job 0a47-9717-0006-0001, execution 0a47-9717-0007-0001 from [127.0.0.1]:5701
00:23:48,592 DEBUG || - [InitExecutionOperation] hz.JetJobPrunabilityTest_brave_snyder.generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] Initializing execution plan for job 0a47-9717-0006-0001, execution 0a47-9717-0007-0001 from [127.0.0.1]:5701
00:23:48,593 DEBUG || - [JobClassLoaderService] hz.JetJobPrunabilityTest_brave_snyder.generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] Creating job classLoader for job 0a47-9717-0006-0001
00:23:48,593 DEBUG || - [JobClassLoaderService] hz.JetJobPrunabilityTest_brave_snyder.generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] Create processor classloader map for job 0a47-9717-0006-0001
00:23:48,594  INFO || - [JobExecutionService] hz.JetJobPrunabilityTest_competent_snyder.cached.thread-13 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Execution plan for jobId=0a47-9717-0006-0001, jobName='0a47-9717-0006-0001', executionId=0a47-9717-0007-0001 initialized
00:23:48,595  INFO || - [JobExecutionService] hz.JetJobPrunabilityTest_brave_snyder.generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] Execution plan for jobId=0a47-9717-0006-0001, jobName='0a47-9717-0006-0001', executionId=0a47-9717-0007-0001 initialized
00:23:48,595 DEBUG || - [MasterJobContext] hz.JetJobPrunabilityTest_competent_snyder.cached.thread-13 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Init of job '0a47-9717-0006-0001', execution 0a47-9717-0007-0001 was successful
00:23:48,595 DEBUG || - [MasterJobContext] hz.JetJobPrunabilityTest_competent_snyder.cached.thread-13 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Executing job '0a47-9717-0006-0001', execution 0a47-9717-0007-0001
00:23:48,595  INFO || - [JobExecutionService] hz.JetJobPrunabilityTest_competent_snyder.cached.thread-13 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Start execution of job '0a47-9717-0006-0001', execution 0a47-9717-0007-0001 from coordinator [127.0.0.1]:5701
00:23:48,596  INFO || - [JobExecutionService] hz.JetJobPrunabilityTest_brave_snyder.generic-operation.thread-1 - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] Start execution of job '0a47-9717-0006-0001', execution 0a47-9717-0007-0001 from coordinator [127.0.0.1]:5701
00:23:48,597 DEBUG || - [JobClassLoaderService] hz.JetJobPrunabilityTest_brave_snyder.cached.thread-1 - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] Finish JobClassLoaders phaseCount = 0, removing classloaders for jobId=0a47-9717-0006-0001
00:23:48,597 DEBUG || - [JobExecutionService] hz.JetJobPrunabilityTest_brave_snyder.cached.thread-1 - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] Completed execution of job '0a47-9717-0006-0001', execution 0a47-9717-0007-0001
00:23:48,597 DEBUG || - [JobExecutionService] hz.JetJobPrunabilityTest_brave_snyder.cached.thread-1 - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] Execution of job '0a47-9717-0006-0001', execution 0a47-9717-0007-0001 completed
00:23:48,597 DEBUG || - [MasterJobContext] ForkJoinPool.commonPool-worker-31 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] job '0a47-9717-0006-0001', execution 0a47-9717-0007-0001 received response to StartExecutionOperation from [127.0.0.1]:5702: null
00:23:48,598 DEBUG || - [JobExecutionService] hz.JetJobPrunabilityTest_competent_snyder.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Completed execution of job '0a47-9717-0006-0001', execution 0a47-9717-0007-0001
00:23:48,598 DEBUG || - [JobExecutionService] hz.JetJobPrunabilityTest_competent_snyder.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Execution of job '0a47-9717-0006-0001', execution 0a47-9717-0007-0001 completed
00:23:48,598 DEBUG || - [MasterJobContext] ForkJoinPool.commonPool-worker-31 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] job '0a47-9717-0006-0001', execution 0a47-9717-0007-0001 received response to StartExecutionOperation from [127.0.0.1]:5701: null
00:23:48,598 DEBUG || - [MasterJobContext] ForkJoinPool.commonPool-worker-31 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Execution of job '0a47-9717-0006-0001', execution 0a47-9717-0007-0001 was successful
00:23:48,599 DEBUG || - [JobClassLoaderService] hz.JetJobPrunabilityTest_competent_snyder.cached.thread-10 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Finish JobClassLoaders phaseCount = 0, removing classloaders for jobId=0a47-9717-0006-0001
00:23:48,599  INFO || - [MasterJobContext] hz.JetJobPrunabilityTest_competent_snyder.cached.thread-10 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Execution of job '0a47-9717-0006-0001', execution 0a47-9717-0007-0001 completed successfully
	Start time: 2023-08-07T00:23:48.586
	Duration: 00:00:00.013
	To see additional job metrics enable JobConfig.storeMetricsAfterJobCompletion
00:23:48,600 DEBUG || - [JobCoordinationService] hz.JetJobPrunabilityTest_competent_snyder.cached.thread-10 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] job '0a47-9717-0006-0001', execution 0a47-9717-0007-0001 is completed
00:23:49,443  INFO |test_simpleDag_takesMemberAndCoordinator| - [SimpleTestInClusterSupport] Time-limited test - Ditching 3 jobs in SimpleTestInClusterSupport.@After: [0a47-9717-0002-0001, 0a47-9717-0004-0001, 0a47-9717-0006-0001]
00:23:49,466  INFO |test_simpleDag_takesMemberAndCoordinator| - [SimpleTestInClusterSupport] Time-limited test - Destroying 1 distributed objects in SimpleTestInClusterSupport.@After: [hz:impl:mapService/__jet.records]
00:23:49,467  INFO |test_simpleDag_takesMemberAndCoordinator| - [HazelcastTestSupport] Time-limited test - Shutting down node factory as @After action
BuildInfo right after test_simpleDag_takesMemberAndCoordinator(com.hazelcast.jet.impl.execution.init.JetJobPrunabilityTest): BuildInfo{version='5.4.0-SNAPSHOT', build='20230806', buildNumber=20230806, revision=427b85e, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'test_simpleDag_takesMemberAndCoordinator(com.hazelcast.jet.impl.execution.init.JetJobPrunabilityTest):'
00:23:45, accumulated pauses: 863 ms, max pause: 723 ms, pauses over 1000 ms: 0


No metrics recorded during the test

```

</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-OpenJDK17-Esxi7/49/

**Comment by sumnerib** [comment]
Failed again on _master_ with oracle-11: https://jenkins.hazelcast.com/job/Hazelcast-master-OracleJDK11/384/testReport/junit/com.hazelcast.jet.impl.execution.init/JetJobPrunabilityTest/test_simpleDag_takesMemberAndCoordinator/

**Comment by k-jamroz** [comment]
Should be already fixed by more robust assertions in `JetJobPrunabilityTest`
