### ISSUE TITLE
com.hazelcast.map.MapRemoveFailingBackupTest.testMapRemoveFailingBackupShouldNotLeadToStaleDataWhenReadBackupIsEnabled [HZ-3147]

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hazelcast#25158]
_master_ (commit 427b85e76f1c0493409d0a2ab832fe740a19d8dc)
Failed on oracle-11 (force-offload): https://jenkins.hazelcast.com/job/Hazelcast-master-force-offload/57/testReport/junit/com.hazelcast.map/MapRemoveFailingBackupTest/testMapRemoveFailingBackupShouldNotLeadToStaleDataWhenReadBackupIsEnabled/

<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: expected null, but was:<value2>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotNull(Assert.java:756)
	at org.junit.Assert.assertNull(Assert.java:738)
	at org.junit.Assert.assertNull(Assert.java:748)
	at com.hazelcast.map.MapRemoveFailingBackupTest$2.run(MapRemoveFailingBackupTest.java:96)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1165)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1184)
	at com.hazelcast.map.MapRemoveFailingBackupTest.testMapRemoveFailingBackupShouldNotLeadToStaleDataWhenReadBackupIsEnabled(MapRemoveFailingBackupTest.java:93)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-force-offload/57/

**Comment by sumnerib** [comment]
Failed again on _master_ with oracle-11 (force-offload): https://jenkins.hazelcast.com/job/Hazelcast-master-force-offload/60/testReport/com.hazelcast.map/MapRemoveFailingBackupTest/testMapRemoveFailingBackupShouldNotLeadToStaleDataWhenReadBackupIsEnabled/

**Comment by olukas** [comment]
Failed again on _master_ with oracle-11 (force-offload): https://jenkins.hazelcast.com/job/Hazelcast-master-force-offload/61/testReport/com.hazelcast.map/MapRemoveFailingBackupTest/testMapRemoveFailingBackupShouldNotLeadToStaleDataWhenReadBackupIsEnabled/

**Comment by Patras3** [comment]
Failed again on _master_ with oracle-11 (force-offload): https://jenkins.hazelcast.com/job/Hazelcast-master-force-offload/62/testReport/com.hazelcast.map/MapRemoveFailingBackupTest/testMapRemoveFailingBackupShouldNotLeadToStaleDataWhenReadBackupIsEnabled/

**Comment by sumnerib** [comment]
Failed again on _master_ with oracle-11 (force-offload): https://jenkins.hazelcast.com/job/Hazelcast-master-force-offload/63/testReport/com.hazelcast.map/MapRemoveFailingBackupTest/testMapRemoveFailingBackupShouldNotLeadToStaleDataWhenReadBackupIsEnabled/

**Comment by sumnerib** [comment]
Fails constantly on `oracle-11 (force-offload)`
