### ISSUE TITLE
com.hazelcast.partition.PartitionMigrationListenerTest.testMigrationListenerTotalElapsedTime [HZ-2939]

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hazelcast#25164]
_master_ (commit e9c339df395ce55741dd33b421ddc7de89b92ef0)
Failed on Windows - OracleJDK11: https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-OracleJDK11/459/testReport/junit/com.hazelcast.partition/PartitionMigrationListenerTest/testMigrationListenerTotalElapsedTime/
<details><summary>Stacktrace:</summary>

```

java.lang.AssertionError: With only one migration, totalElapsedMigrationTime (224,206,700) and elapsedMigrationTime (71,123,300) times should be equal expected:<224206700> but was:<71123300>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at com.hazelcast.partition.PartitionMigrationListenerTest.testMigrationListenerTotalElapsedTime(PartitionMigrationListenerTest.java:424)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-Windows-OracleJDK11/459/

**Comment by sumnerib** [comment]
Failed again on _master_ with Windows - MicrosoftJDK11: https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK11/78/testReport/junit/com.hazelcast.partition/PartitionMigrationListenerTest/testMigrationListenerTotalElapsedTime/

**Comment by JackPGreen** [comment]
Both failures are with same `With only one migration` assertion.

**Comment by JackPGreen** [comment]
@vbekiaris has highlighted the following exception in the logs:
```
20:41:30,959  WARN |testMigrationListenerTotalElapsedTime| - [MigrationRequestOperation] hz.PartitionMigrationListenerTest_gallant_jepsen.async.thread-3 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Failure while executing MigrationInfo{uuid=27d3a271-5d0d-4955-84f9-4001c2c14e9f, partitionId=2, source=[127.0.0.1]:5701 - 3b7279d6-4ff7-4458-9ea7-aeb8ee0c0ddf, sourceCurrentReplicaIndex=0, sourceNewReplicaIndex=1, destination=[127.0.0.1]:5702 - 19c03904-a54e-4bf5-b5ca-1190e8164b1b, destinationCurrentReplicaIndex=-1, destinationNewReplicaIndex=0, master=[127.0.0.1]:5701, initialPartitionVersion=1, partitionVersionIncrement=2, status=ACTIVE}
java.lang.IllegalStateException: Migration operation is received before startup is completed. Sender: [127.0.0.1]:5701
	at com.hazelcast.internal.partition.operation.BaseMigrationOperation.verifyNodeStarted(BaseMigrationOperation.java:108) ~[classes/:?]
	at com.hazelcast.internal.partition.operation.BaseMigrationOperation.beforeRun(BaseMigrationOperation.java:90) ~[classes/:?]
	at com.hazelcast.internal.partition.operation.MigrationOperation.beforeRun(MigrationOperation.java:57) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:269) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:502) ~[classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:202) ~[classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:142) ~[classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.loop(OperationThread.java:134) ~[classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:115) ~[classes/:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:111) [classes/:?]
```

Initial _indications_ are that:
1. `gc` pause delayed startup
2. Initial migration was rejected because member hadn't finished starting
3. This rejected migration is being counted in the timer

To be investigated.
