### ISSUE TITLE
Protracted startup causes `NullPointerException` in `AbstractGauge`

### ISSUE THREAD

**Issue by JackPGreen** [hazelcast/hazelcast#25290]
**Describe the bug**
While investigating #25164, a delay was added to the `FinalizeJoinOp`, and then the following exception was thrown:

```
java.lang.NullPointerException: Cannot invoke "com.hazelcast.internal.metrics.impl.AbstractGauge.onCollectionCompleted(long)" because "gauge" is null
	at com.hazelcast.internal.metrics.impl.MetricsCollectionCycle.notifyAllGauges(MetricsCollectionCycle.java:105) ~[classes/:?]
	at com.hazelcast.internal.metrics.impl.MetricsRegistryImpl.collect(MetricsRegistryImpl.java:321) ~[classes/:?]
	at com.hazelcast.internal.metrics.impl.MetricsService.collectMetrics(MetricsService.java:160) ~[classes/:?]
	at com.hazelcast.internal.metrics.impl.MetricsService.collectMetrics(MetricsService.java:154) ~[classes/:?]
	at com.hazelcast.spi.impl.executionservice.impl.DelegateAndSkipOnConcurrentExecutionDecorator$DelegateDecorator.run(DelegateAndSkipOnConcurrentExecutionDecorator.java:77) ~[classes/:?]
	at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217) ~[classes/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76) [classes/:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:111) [classes/:?]
```

**To Reproduce**
In `com.hazelcast.internal.cluster.impl.operations.FinalizeJoinOp.run()`, add a `Thread.sleep(5000)` immediately before the `finalized =` section.

Then run the `com.hazelcast.partition.PartitionMigrationListenerTest.testMigrationListenerTotalElapsedTime()` test.

**Comment by JackPGreen** [comment]
I believe the problem is that `gauages` uses a ConcurrentReferenceHashMap with weak values. As such, any values call should be null-safe.
