### ISSUE TITLE
com.hazelcast.client.map.impl.nearcache.ClientMapNearCacheEvictionTest

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#25312]
_5.3.z_ (commit cd3602cce88ca8c301b7f02edb84bddd9af6fd30)

Failed on ibm-8: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-IbmJDK8/99/testReport/com.hazelcast.client.map.impl.nearcache/ClientMapNearCacheEvictionTest/

Failed in following variants:
- `com.hazelcast.client.map.impl.nearcache.ClientMapNearCacheEvictionTest.no_more_entries_than_max_near_cache_size_when_eviction_policy_is_not_none`
- `com.hazelcast.client.map.impl.nearcache.ClientMapNearCacheEvictionTest.near_cache_size_equals_map_size_when_eviction_policy_is_none`

<details><summary>Stacktrace:</summary>

```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:315)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.manageParking(AbstractInvocationFuture.java:694)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:616)
	at com.hazelcast.client.impl.spi.ClientProxy.invokeOnPartition(ClientProxy.java:188)
	at com.hazelcast.client.impl.spi.ClientProxy.invoke(ClientProxy.java:182)
	at com.hazelcast.client.impl.proxy.ClientMapProxy.getInternal(ClientMapProxy.java:265)
	at com.hazelcast.client.map.impl.nearcache.NearCachedClientMapProxy.getInternal(NearCachedClientMapProxy.java:127)
	at com.hazelcast.client.impl.proxy.ClientMapProxy.get(ClientMapProxy.java:259)
	at com.hazelcast.client.map.impl.nearcache.ClientMapNearCacheEvictionTest.no_more_entries_than_max_near_cache_size_when_eviction_policy_is_not_none(ClientMapNearCacheEvictionTest.java:99)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.lang.Thread.run(Thread.java:825)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-5.maintenance-IbmJDK8/99/

**Comment by olukas** [comment]
Failed again on _5.3.z_ with ibm-8: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-IbmJDK8/104/testReport/com.hazelcast.client.map.impl.nearcache/ClientMapNearCacheEvictionTest/no_more_entries_than_max_near_cache_size_when_eviction_policy_is_not_none/

**Comment by olukas** [comment]
Failed again on _master_ with openj9-11: https://jenkins.hazelcast.com/job/Hazelcast-master-Openj9-11/154/testReport/com.hazelcast.client.map.impl.nearcache/ClientMapNearCacheEvictionTest/

**Comment by sumnerib** [comment]
Failed again on master with openj9-11: https://jenkins.hazelcast.com/job/Hazelcast-master-Openj9-11/155/

**Comment by Patras3** [comment]
Failed again on _5.3.z_ with ibm-8: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-IbmJDK8/111/testReport/com.hazelcast.client.map.impl.nearcache/ClientMapNearCacheEvictionTest/

**Comment by AleksPeychev** [comment]
Failed again on _5.3.z_ with ibm-8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-IbmJDK8/125/testReport/junit/com.hazelcast.client.map.impl.nearcache/ClientMapNearCacheEvictionTest/

Failed in following variants:

`com.hazelcast.client.map.impl.nearcache.ClientMapNearCacheEvictionTest.no_more_entries_than_max_near_cache_size_when_eviction_policy_is_not_none`
`com.hazelcast.client.map.impl.nearcache.ClientMapNearCacheEvictionTest.near_cache_size_equals_map_size_when_eviction_policy_is_none`

**Comment by AleksPeychev** [comment]
Failed again on _master_ with openj9-17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Openj9-17/122/testReport/junit/com.hazelcast.client.map.impl.nearcache/ClientMapNearCacheEvictionTest/

Failed in following variants:

`com.hazelcast.client.map.impl.nearcache.ClientMapNearCacheEvictionTest.no_more_entries_than_max_near_cache_size_when_eviction_policy_is_not_none`

`com.hazelcast.client.map.impl.nearcache.ClientMapNearCacheEvictionTest.near_cache_size_equals_map_size_when_eviction_policy_is_none`

**Comment by AleksPeychev** [comment]
Failed again on _master_ with openj9-17: https://jenkins.hazelcast.com/job/Hazelcast-master-Openj9-17/126/testReport/junit/com.hazelcast.client.map.impl.nearcache/ClientMapNearCacheEvictionTest/
