### ISSUE TITLE
AssertionError EventListenerCounter.decCounter(EventListenerCounter.java:56) [HZ-3070]

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#25327]
data structure create use destroy test while cluster members are frozen and unfrozen 

https://jenkins.hazelcast.com/view/freeze/job/freeze-all/70/console

```
01:30:14 /disk1/workspace/freeze-all/5.4.0-SNAPSHOT/2023_08_29-21_15_20/stable/destroy/create-use-destroy Failed
01:30:15 fail HzMember2HZ _create-use-destroy_createUseDestroy_mapBak1HD hzcmd.map.CreateUseDestroy threadId=0 java.lang.AssertionError 
```

```
java.lang.AssertionError
	at com.hazelcast.map.impl.EventListenerCounter.decCounter(EventListenerCounter.java:56)
	at com.hazelcast.map.impl.MapService.onDeregister(MapService.java:280)
	at com.hazelcast.spi.impl.eventservice.impl.EventServiceSegment.pingNotifiableEventListenerInternal(EventServiceSegment.java:122)
	at com.hazelcast.spi.impl.eventservice.impl.EventServiceSegment.pingNotifiableEventListener(EventServiceSegment.java:100)
	at com.hazelcast.spi.impl.eventservice.impl.EventServiceSegment.removeRegistrations(EventServiceSegment.java:206)
	at com.hazelcast.spi.impl.eventservice.impl.EventServiceImpl.deregisterAllLocalListeners(EventServiceImpl.java:405)
	at com.hazelcast.map.impl.MapServiceContextImpl.destroyMap(MapServiceContextImpl.java:443)
	at com.hazelcast.map.impl.MapRemoteService.destroyDistributedObject(MapRemoteService.java:67)
	at com.hazelcast.map.impl.MapService.destroyDistributedObject(MapService.java:205)
	at com.hazelcast.internal.services.RemoteService.destroyDistributedObject(RemoteService.java:68)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyServiceImpl.destroyLocalDistributedObject(ProxyServiceImpl.java:193)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyServiceImpl.destroyDistributedObject(ProxyServiceImpl.java:177)
	at com.hazelcast.spi.impl.AbstractDistributedObject.destroy(AbstractDistributedObject.java:76)
	at hzcmd.map.CreateUseDestroy.timeStep(CreateUseDestroy.java:18)
```

**Comment by Danny-Hazelcast** [comment]
https://jenkins.hazelcast.com/view/freeze/job/freeze-x3/27/console

/disk1/workspace/freeze-x3/5.4.0-SNAPSHOT/2023_09_27-11_58_42/create-use-destroy

```
java.lang.AssertionError
	at com.hazelcast.map.impl.EventListenerCounter.decCounter(EventListenerCounter.java:56)
	at com.hazelcast.map.impl.MapService.onDeregister(MapService.java:280)
	at com.hazelcast.spi.impl.eventservice.impl.EventServiceSegment.pingNotifiableEventListenerInternal(EventServiceSegment.java:122)
	at com.hazelcast.spi.impl.eventservice.impl.EventServiceSegment.pingNotifiableEventListener(EventServiceSegment.java:100)
	at com.hazelcast.spi.impl.eventservice.impl.EventServiceSegment.removeRegistrations(EventServiceSegment.java:206)
	at com.hazelcast.spi.impl.eventservice.impl.EventServiceImpl.deregisterAllLocalListeners(EventServiceImpl.java:405)
	at com.hazelcast.map.impl.MapServiceContextImpl.destroyMap(MapServiceContextImpl.java:443)
	at com.hazelcast.map.impl.MapRemoteService.destroyDistributedObject(MapRemoteService.java:67)
	at com.hazelcast.map.impl.MapService.destroyDistributedObject(MapService.java:205)
	at com.hazelcast.internal.services.RemoteService.destroyDistributedObject(RemoteService.java:68)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyServiceImpl.destroyLocalDistributedObject(ProxyServiceImpl.java:193)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyServiceImpl.destroyDistributedObject(ProxyServiceImpl.java:177)
	at com.hazelcast.spi.impl.AbstractDistributedObject.destroy(AbstractDistributedObject.java:76)
```

**Comment by vbekiaris** [comment]
@Danny-Hazelcast can you supply log output from `/disk1/workspace/freeze-x3/5.4.0-SNAPSHOT/2023_09_27-11_58_42/create-use-destroy` to @gareth-johnston (or set up access for him on the `stabilizer` machine so he can access them himself)?

**Comment by Danny-Hazelcast** [comment]
@vbekiaris i see gareth.johnston@hazelcast.com public key is all ready added to "stabilizer machine " 
https://jenkins.hazelcast.com/computer/hzcmd/
