### ISSUE TITLE
com.hazelcast.test.starter.hz3.Hazelcast3StarterTest.testTopicMessageListenerPublish and com.hazelcast.test.starter.hz3.Hazelcast3StarterTest.testMapPutGet [HZ-3404]

### ISSUE THREAD

**Issue by Patras3** [hazelcast/hazelcast#25363]
_5.3.z_ (commit 2d209c8f19e54b81a9a09dfc3de272a4888697c8)

Failed on Windows - OracleJDK8: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-Windows-OracleJDK8/135/testReport/junit/com.hazelcast.test.starter.hz3/Hazelcast3StarterTest/testTopicMessageListenerPublish/
<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: 

Expecting ArrayList:
  []
to contain:
  ["value"]
but could not find the following element(s):
  ["value"]

	at com.hazelcast.test.starter.hz3.Hazelcast3StarterTest.lambda$testTopicMessageListenerPublish$1(Hazelcast3StarterTest.java:73)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1285)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1304)
	at com.hazelcast.test.starter.hz3.Hazelcast3StarterTest.testTopicMessageListenerPublish(Hazelcast3StarterTest.java:72)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:49)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:120)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:95)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:69)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:146)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)

```
</details>

<details><summary>Standard output:</summary>

```
03:00:42.858 [&amp#27;[33m WARN&amp#27;[0m] [&amp#27;[34mc.h.i.Node&amp#27;[0m] [127.0.0.1]:3210 [dev] [3.12.13] No join method is enabled! Starting standalone.

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-5.maintenance-Windows-OracleJDK8/135/

**Comment by sumnerib** [comment]
Also `testMapPutGet`

Failed again on _master_ with oracle-17: https://jenkins.hazelcast.com/job/Hazelcast-master-OracleJDK17/99/testReport/junit/com.hazelcast.test.starter.hz3/Hazelcast3StarterTest/

**Comment by olukas** [comment]
Failed again on _master_ with:
- OpenJDK17: https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK17-Esxi7/55/testReport/com.hazelcast.test.starter.hz3/Hazelcast3StarterTest/
- oracle-11: https://jenkins.hazelcast.com/job/Hazelcast-master-OracleJDK11/390/testReport/com.hazelcast.test.starter.hz3/Hazelcast3StarterTest/
- oracle-11 (little-endian): https://jenkins.hazelcast.com/job/Hazelcast-master-little-endian/271/testReport/com.hazelcast.test.starter.hz3/Hazelcast3StarterTest/
- oracle-11 (force-offload): https://jenkins.hazelcast.com/job/Hazelcast-master-force-offload/64/testReport/com.hazelcast.test.starter.hz3/Hazelcast3StarterTest/
- Windows - MicrosoftJDK17: https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK17/81/testReport/com.hazelcast.test.starter.hz3/Hazelcast3StarterTest/
- openjdk-ea (openjdk-21): https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK-ea/53/testReport/com.hazelcast.test.starter.hz3/Hazelcast3StarterTest/
- oracle-11 (Sonar build): https://jenkins.hazelcast.com/job/Hazelcast-master-sonar/255/testReport/com.hazelcast.test.starter.hz3/Hazelcast3StarterTest/
