### ISSUE TITLE
JVM crash for Redpanda certification jobs [HZ-3168]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#25406]
_master_ (commit 875e31f51ac14bdf5e487b777a46e2af447c76a0)

Failed on Redpanda 23.2.7 with Oracle JDK 11: https://jenkins.hazelcast.com/view/Redpanda/job/Hazelcast-master-Redpanda-23.2.z/1/console

<details><summary>Console output:</summary>

```
23:21:10 [INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.050 s -- in com.hazelcast.jet.sql.impl.connector.kafka.SqlMappingTest
23:21:10 [INFO] Running com.hazelcast.jet.sql.impl.connector.kafka.SqlKafkaAggregateTest
23:21:13 [INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.728 s -- in com.hazelcast.jet.sql.impl.connector.kafka.SqlKafkaAggregateTest
23:21:13 [INFO] Running com.hazelcast.jet.sql.impl.connector.kafka.SqlAvroTest
23:21:15 [INFO] 
23:21:15 [INFO] Results:
23:21:15 [INFO] 
23:21:15 [INFO] Tests run: 101, Failures: 0, Errors: 0, Skipped: 0
23:21:15 [INFO] 
23:21:15 [INFO] ------------------------------------------------------------------------
23:21:15 [INFO] BUILD FAILURE
23:21:15 [INFO] ------------------------------------------------------------------------
23:21:15 [INFO] Total time:  01:17 min (Wall Clock)
23:21:15 [INFO] Finished at: 2023-09-03T21:21:15Z
23:21:15 [INFO] ------------------------------------------------------------------------
...
23:21:15 [ERROR] The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
23:21:15 [ERROR] Command was /bin/sh -c cd '/appdisk/jenkins/jenkins_slave/workspace/Hazelcast-master-Redpanda-23.2.z/hazelcast-sql' && '/usr/share/jdks/oracle-11/bin/java' '-Xms512m' '-Xmx2G' '--add-exports' 'java.base/jdk.internal.ref=ALL-UNNAMED' '--add-opens' 'jdk.management/com.sun.management.internal=ALL-UNNAMED' '--add-opens' 'java.base/sun.nio.ch=ALL-UNNAMED' '--add-opens' 'java.base/java.lang=ALL-UNNAMED' '--add-opens' 'java.management/sun.management=ALL-UNNAMED' '--illegal-access=deny' '-Dhazelcast.phone.home.enabled=false' '-Dhazelcast.test.use.network=false' '-Dlog4j.skipJansi=true' '-jar' '/appdisk/jenkins/jenkins_slave/workspace/Hazelcast-master-Redpanda-23.2.z/hazelcast-sql/target/surefire/surefirebooter-20230903212016847_3.jar' '/appdisk/jenkins/jenkins_slave/workspace/Hazelcast-master-Redpanda-23.2.z/hazelcast-sql/target/surefire' '2023-09-03T21-20-16_721-jvmRun1' 'surefire-20230903212016847_1tmp' 'surefire_0-20230903212016847_2tmp'
23:21:15 [ERROR] Error occurred in starting fork, check output in log
23:21:15 [ERROR] Process Exit Code: 1
23:21:15 [ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
23:21:15 [ERROR] Command was /bin/sh -c cd '/appdisk/jenkins/jenkins_slave/workspace/Hazelcast-master-Redpanda-23.2.z/hazelcast-sql' && '/usr/share/jdks/oracle-11/bin/java' '-Xms512m' '-Xmx2G' '--add-exports' 'java.base/jdk.internal.ref=ALL-UNNAMED' '--add-opens' 'jdk.management/com.sun.management.internal=ALL-UNNAMED' '--add-opens' 'java.base/sun.nio.ch=ALL-UNNAMED' '--add-opens' 'java.base/java.lang=ALL-UNNAMED' '--add-opens' 'java.management/sun.management=ALL-UNNAMED' '--illegal-access=deny' '-Dhazelcast.phone.home.enabled=false' '-Dhazelcast.test.use.network=false' '-Dlog4j.skipJansi=true' '-jar' '/appdisk/jenkins/jenkins_slave/workspace/Hazelcast-master-Redpanda-23.2.z/hazelcast-sql/target/surefire/surefirebooter-20230903212016847_3.jar' '/appdisk/jenkins/jenkins_slave/workspace/Hazelcast-master-Redpanda-23.2.z/hazelcast-sql/target/surefire' '2023-09-03T21-20-16_721-jvmRun1' 'surefire-20230903212016847_1tmp' 'surefire_0-20230903212016847_2tmp'
23:21:15 [ERROR] Error occurred in starting fork, check output in log
23:21:15 [ERROR] Process Exit Code: 1
23:21:15 [ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:643)
23:21:15 [ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:285)
23:21:15 [ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:250)
23:21:15 [ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1203)
23:21:15 [ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1055)
23:21:15 [ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:871)
23:21:15 [ERROR] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:126)
23:21:15 [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:342)
23:21:15 [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:330)
23:21:15 [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
23:21:15 [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:175)
23:21:15 [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.access$000(MojoExecutor.java:76)
23:21:15 [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor$1.run(MojoExecutor.java:163)
23:21:15 [ERROR] 	at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute(DefaultMojosExecutionStrategy.java:39)
23:21:15 [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:160)
23:21:15 [ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:105)
23:21:15 [ERROR] 	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:193)
23:21:15 [ERROR] 	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:180)
23:21:15 [ERROR] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
23:21:15 [ERROR] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
23:21:15 [ERROR] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
23:21:15 [ERROR] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
23:21:15 [ERROR] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
23:21:15 [ERROR] 	at java.base/java.lang.Thread.run(Thread.java:834)
```

</details>

<details><summary>Standard output:</summary>

```
...
21:21:14,741  INFO || - [AppInfoParser] Time-limited test - Kafka version: 3.4.1
21:21:14,741  INFO || - [AppInfoParser] Time-limited test - Kafka commitId: 8a516edc2755df89
21:21:14,741  INFO || - [AppInfoParser] Time-limited test - Kafka startTimeMs: 1693776074741
21:21:14,743  INFO || - [Metadata] Time-limited test - [Consumer clientId=KafkaStore-reader-_schemas, groupId=schema-registry-4c11aabebc7a-0] Cluster ID: redpanda.584f4083-6fc7-43c9-8f33-2373c705ed9f
21:21:14,744  INFO || - [KafkaConsumer] Time-limited test - [Consumer clientId=KafkaStore-reader-_schemas, groupId=schema-registry-4c11aabebc7a-0] Assigned to partition(s): _schemas-0
21:21:14,744  INFO || - [KafkaStoreReaderThread] Time-limited test - Seeking to beginning for all partitions
21:21:14,744  INFO || - [SubscriptionState] Time-limited test - [Consumer clientId=KafkaStore-reader-_schemas, groupId=schema-registry-4c11aabebc7a-0] Seeking to earliest offset of partition _schemas-0
21:21:14,744  INFO || - [KafkaStoreReaderThread] Time-limited test - Initialized last consumed offset to -1
21:21:14,745  INFO || - [KafkaStoreReaderThread] kafka-store-reader-thread-_schemas - [kafka-store-reader-thread-_schemas]: Starting
21:21:14,750  WARN || - [Sender] kafka-producer-network-thread | producer-92 - [Producer clientId=producer-92] Received invalid metadata error in produce request on partition _schemas-0 due to org.apache.kafka.common.errors.NotLeaderOrFollowerException: For requests intended only for the leader, this error indicates that the broker is not the current leader. For requests intended for any replica, this error indicates that the broker is not a replica of the topic partition.. Going to request metadata update now
21:21:14,750 ERROR || - [SchemaRegistryRestApplication] Time-limited test - Error starting the schema registry
io.confluent.kafka.schemaregistry.exceptions.SchemaRegistryInitializationException: Error initializing kafka store while initializing schema registry
	at io.confluent.kafka.schemaregistry.storage.KafkaSchemaRegistry.init(KafkaSchemaRegistry.java:352) ~[kafka-schema-registry-7.4.0.jar:?]
	at io.confluent.kafka.schemaregistry.rest.SchemaRegistryRestApplication.initSchemaRegistry(SchemaRegistryRestApplication.java:75) [kafka-schema-registry-7.4.0.jar:?]
	at io.confluent.kafka.schemaregistry.rest.SchemaRegistryRestApplication.configureBaseApplication(SchemaRegistryRestApplication.java:99) [kafka-schema-registry-7.4.0.jar:?]
	at io.confluent.rest.Application.configureHandler(Application.java:296) [rest-utils-7.4.0.jar:?]
	at io.confluent.rest.ApplicationServer.doStart(ApplicationServer.java:194) [rest-utils-7.4.0.jar:?]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73) [jetty-util-9.4.51.v20230217.jar:9.4.51.v20230217]
	at com.hazelcast.jet.kafka.impl.KafkaTestSupport.createSchemaRegistry(KafkaTestSupport.java:257) [hazelcast-jet-kafka-5.4.0-SNAPSHOT-tests.jar:?]
	at com.hazelcast.jet.sql.impl.connector.kafka.KafkaSqlTestSupport.createSchemaRegistry(KafkaSqlTestSupport.java:59) [test-classes/:?]
	at com.hazelcast.jet.sql.impl.connector.kafka.SqlAvroTest.initialize(SqlAvroTest.java:75) [test-classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59) [junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56) [junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33) [junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24) [junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27) [junit-4.13.2.jar:4.13.2]
	at com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:41) [hazelcast-5.4.0-SNAPSHOT-tests.jar:?]
	at com.hazelcast.test.OverridePropertyRule$1.evaluate(OverridePropertyRule.java:66) [hazelcast-5.4.0-SNAPSHOT-tests.jar:?]
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299) [junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293) [junit-4.13.2.jar:4.13.2]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: io.confluent.kafka.schemaregistry.storage.exceptions.StoreInitializationException: io.confluent.kafka.schemaregistry.storage.exceptions.StoreException: Failed to write Noop record to kafka store.
	at io.confluent.kafka.schemaregistry.storage.KafkaStore.init(KafkaStore.java:148) ~[kafka-schema-registry-7.4.0.jar:?]
	at io.confluent.kafka.schemaregistry.storage.KafkaSchemaRegistry.init(KafkaSchemaRegistry.java:350) ~[kafka-schema-registry-7.4.0.jar:?]
	... 24 more
Caused by: io.confluent.kafka.schemaregistry.storage.exceptions.StoreException: Failed to write Noop record to kafka store.
	at io.confluent.kafka.schemaregistry.storage.KafkaStore.getLatestOffset(KafkaStore.java:490) ~[kafka-schema-registry-7.4.0.jar:?]
	at io.confluent.kafka.schemaregistry.storage.KafkaStore.waitUntilKafkaReaderReachesLastOffset(KafkaStore.java:293) ~[kafka-schema-registry-7.4.0.jar:?]
	at io.confluent.kafka.schemaregistry.storage.KafkaStore.init(KafkaStore.java:146) ~[kafka-schema-registry-7.4.0.jar:?]
	at io.confluent.kafka.schemaregistry.storage.KafkaSchemaRegistry.init(KafkaSchemaRegistry.java:350) ~[kafka-schema-registry-7.4.0.jar:?]
	... 24 more
Caused by: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.NotLeaderOrFollowerException: For requests intended only for the leader, this error indicates that the broker is not the current leader. For requests intended for any replica, this error indicates that the broker is not a replica of the topic partition.
	at org.apache.kafka.clients.producer.internals.FutureRecordMetadata.valueOrError(FutureRecordMetadata.java:97) ~[kafka-clients-3.4.1.jar:?]
	at org.apache.kafka.clients.producer.internals.FutureRecordMetadata.get(FutureRecordMetadata.java:79) ~[kafka-clients-3.4.1.jar:?]
	at org.apache.kafka.clients.producer.internals.FutureRecordMetadata.get(FutureRecordMetadata.java:30) ~[kafka-clients-3.4.1.jar:?]
	at io.confluent.kafka.schemaregistry.storage.KafkaStore.getLatestOffset(KafkaStore.java:485) ~[kafka-schema-registry-7.4.0.jar:?]
	at io.confluent.kafka.schemaregistry.storage.KafkaStore.waitUntilKafkaReaderReachesLastOffset(KafkaStore.java:293) ~[kafka-schema-registry-7.4.0.jar:?]
	at io.confluent.kafka.schemaregistry.storage.KafkaStore.init(KafkaStore.java:146) ~[kafka-schema-registry-7.4.0.jar:?]
	at io.confluent.kafka.schemaregistry.storage.KafkaSchemaRegistry.init(KafkaSchemaRegistry.java:350) ~[kafka-schema-registry-7.4.0.jar:?]
	... 24 more
Caused by: org.apache.kafka.common.errors.NotLeaderOrFollowerException: For requests intended only for the leader, this error indicates that the broker is not the current leader. For requests intended for any replica, this error indicates that the broker is not a replica of the topic partition.
```

</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-Redpanda-23.2.z/1/

**Comment by ldziedziul** [comment]
Discussion https://hazelcast.slack.com/archives/C02JGKJD9NY/p1694181002356259

**Comment by Patras3** [comment]
Failed again: https://jenkins.hazelcast.com/job/Hazelcast-master-Redpanda-23.2.z/4/console

**Comment by olukas** [comment]
Failed again:
- https://jenkins.hazelcast.com/job/Hazelcast-master-Redpanda-23.2.z/5/console
- https://jenkins.hazelcast.com/job/Hazelcast-master-Redpanda-22.3.z/21/console

**Comment by Patras3** [comment]
Recent crash for reference:
https://jenkins.hazelcast.com/job/Hazelcast-master-Redpanda-23.1.z/39/console

**Comment by olukas** [comment]
Closing the test failure - it doesn't seem to be related to `master` or the latest maintenance stream `5.5.z` and it hasn't fail in the last 3 months. Feel free to reopen test failure if it occurs on `master` or on the latest maintenance stream.
