### ISSUE TITLE
[OOM] com.hazelcast.map.MapUnboundedReturnValues_StringKeyTest.testMap_SmallLimit_StringKey

### ISSUE THREAD

**Issue by Patras3** [hazelcast/hazelcast#25401]
_master_ (commit 74ecbf1f058df547bb083b994777fae9585b0f56)

Failed on OpenJDK17: https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK17-nightly-Esxi7/48/testReport/com.hazelcast.map/MapUnboundedReturnValues_StringKeyTest/testMap_SmallLimit_StringKey/
<details><summary>Stacktrace:</summary>

```
java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.HashMap.resize(HashMap.java:702)
	at java.base/java.util.HashMap.putVal(HashMap.java:627)
	at java.base/java.util.HashMap.put(HashMap.java:610)
	at java.base/java.util.HashSet.add(HashSet.java:221)
	at java.base/java.util.AbstractCollection.addAll(AbstractCollection.java:336)
	at java.base/java.util.HashSet.<init>(HashSet.java:121)
	at com.hazelcast.map.impl.query.QueryResultCollection.<init>(QueryResultCollection.java:45)
	at com.hazelcast.map.impl.query.QueryResultUtils.transformToSet(QueryResultUtils.java:44)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.executePredicate(MapProxyImpl.java:820)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.keySet(MapProxyImpl.java:727)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.keySet(MapProxyImpl.java:721)
	at com.hazelcast.map.MapUnboundedReturnValuesTestSupport.internalRunWithLowerBoundCheck(MapUnboundedReturnValuesTestSupport.java:235)
	at com.hazelcast.map.MapUnboundedReturnValuesTestSupport.runMapFullTest(MapUnboundedReturnValuesTestSupport.java:83)
	at com.hazelcast.map.MapUnboundedReturnValues_StringKeyTest.testMap_SmallLimit_StringKey(MapUnboundedReturnValues_StringKeyTest.java:31)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-OpenJDK17-nightly-Esxi7/48/

**Comment by olukas** [comment]
Closing the test failure - it doesn't seem to be related to `master` or the latest maintenance stream `5.5.z` and it hasn't fail in the last 3 months. Feel free to reopen test failure if it occurs on `master` or on the latest maintenance stream.
