### ISSUE TITLE
com.hazelcast.json.internal.JsonMetadataCreationTest

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hazelcast#25414]
_master_ (commit f065881cd880c7ff547bb54a5525ea014f85aa94)
Failed on OpenJDK17: https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK17-Esxi7/54/testReport/junit/com.hazelcast.json.internal/JsonMetadataCreationTest/

[com.hazelcast.json.internal.JsonMetadataCreationTest.testPutTransientCreatesMetadataForJson](https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK17-Esxi7/lastSuccessfulBuild/testReport/junit/com.hazelcast.json.internal/JsonMetadataCreationTest/testPutTransientCreatesMetadataForJson/)
[com.hazelcast.json.internal.JsonMetadataCreationTest.testMetadataIsntCreatedWhenKeyAndValueAreNotJson](https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK17-Esxi7/lastSuccessfulBuild/testReport/junit/com.hazelcast.json.internal/JsonMetadataCreationTest/testMetadataIsntCreatedWhenKeyAndValueAreNotJson/)
[com.hazelcast.json.internal.JsonMetadataCreationTest.testMetadataIsRemoved_whenValueBecomesNonJson](https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK17-Esxi7/lastSuccessfulBuild/testReport/junit/com.hazelcast.json.internal/JsonMetadataCreationTest/testMetadataIsRemoved_whenValueBecomesNonJson/)

<details><summary>Example Stacktrace:</summary>

```
java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "hz" is null
	at com.hazelcast.instance.impl.TestUtil.getNode(TestUtil.java:80)
	at com.hazelcast.test.Accessors.getNode(Accessors.java:64)
	at com.hazelcast.test.backup.MapBackupAccessor.getRecord(MapBackupAccessor.java:95)
	at com.hazelcast.json.internal.JsonMetadataCreationTest.assertMetadataCreated(JsonMetadataCreationTest.java:346)
	at com.hazelcast.json.internal.JsonMetadataCreationTest.assertMetadataCreated(JsonMetadataCreationTest.java:339)
	at com.hazelcast.json.internal.JsonMetadataCreationTest.testPutTransientCreatesMetadataForJson(JsonMetadataCreationTest.java:181)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-OpenJDK17-Esxi7/54/

**Comment by olukas** [comment]
Failed again on _master_ with OpenJDK17: https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK17-Esxi7/60/testReport/com.hazelcast.json.internal/JsonMetadataCreationTest/testPutTransientCreatesMetadataForJson_2/

**Comment by AleksPeychev** [comment]
Failed again on _master_ with OpenJDK17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-OpenJDK17-Esxi7/78/testReport/junit/com.hazelcast.json.internal/JsonMetadataCreationTest

Two tests are failing with similar Assertion message:

`com.hazelcast.json.internal.JsonMetadataCreationTest.testPutCreatesMetadataForJson_whenReplacingExisting[InMemoryFormat: BINARY]`

`com.hazelcast.json.internal.JsonMetadataCreationTest.testReplaceIfSameCreatesMetadataForJson[InMemoryFormat: BINARY]`

**Comment by olukas** [comment]
Closing the test failure - it doesn't seem to be related to `master` or the latest maintenance stream `5.5.z` and it hasn't fail in the last 3 months. Feel free to reopen test failure if it occurs on `master` or on the latest maintenance stream.

**Comment by olukas** [comment]
Reopening as issue occurred again on: _master_ (commit 5373f978349375b27cfd11b03a375fc5287ecd7a)
with OpenJDK17: https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK17-Esxi7/102/testReport/com.hazelcast.json.internal/JsonMetadataCreationTest/testPutDoesNotCreateMetadata_whenMetadataPolicyIsOff_InMemoryFormat__BINARY_/
<details><summary>Stacktrace:</summary>

```
java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "hz" is null
	at com.hazelcast.instance.impl.TestUtil.getNode(TestUtil.java:79)
	at com.hazelcast.test.Accessors.getNode(Accessors.java:63)
	at com.hazelcast.test.backup.MapBackupAccessor.getRecord(MapBackupAccessor.java:95)
	at com.hazelcast.json.internal.JsonMetadataCreationTest.assertMetadataNotCreated(JsonMetadataCreationTest.java:358)
	at com.hazelcast.json.internal.JsonMetadataCreationTest.assertMetadataNotCreated(JsonMetadataCreationTest.java:351)
	at com.hazelcast.json.internal.JsonMetadataCreationTest.testPutDoesNotCreateMetadata_whenMetadataPolicyIsOff(JsonMetadataCreationTest.java:146)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:840)

```
</details>



Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-OpenJDK17-Esxi7/102/
