### ISSUE TITLE
com.hazelcast.map.MapDestroyTest.destroyRepeatedly

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hazelcast#25420]
_master_ (commit e7c36f230fd88c0edf2fdd011aa4c53feba1c446)
Failed on oracle-11: https://jenkins.hazelcast.com/job/Hazelcast-master-sonar/249/testReport/junit/com.hazelcast.map/MapDestroyTest/destroyRepeatedly/

<details><summary>Stacktrace:</summary>

```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.base@11.0.18/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@11.0.18/java.util.concurrent.locks.LockSupport.park(LockSupport.java:323)
	at app//com.hazelcast.spi.impl.AbstractInvocationFuture.manageParking(AbstractInvocationFuture.java:694)
	at app//com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:616)
	at app//com.hazelcast.map.impl.proxy.MapProxySupport.invokeOperation(MapProxySupport.java:510)
	at app//com.hazelcast.map.impl.proxy.MapProxySupport.putInternal(MapProxySupport.java:446)
	at app//com.hazelcast.map.impl.proxy.MapProxyImpl.put(MapProxyImpl.java:137)
	at app//com.hazelcast.map.impl.proxy.MapProxyImpl.put(MapProxyImpl.java:127)
	at app//com.hazelcast.map.MapDestroyTest.createFillAndDestroyMap(MapDestroyTest.java:121)
	at app//com.hazelcast.map.MapDestroyTest.destroyRepeatedly(MapDestroyTest.java:105)
	at java.base@11.0.18/java.lang.reflect.Method.invoke(Method.java:566)
	at app//com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at app//com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base@11.0.18/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base@11.0.18/java.lang.Thread.run(Thread.java:834)

```

</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-sonar/249/

**Comment by sumnerib** [comment]
See https://github.com/hazelcast/hazelcast-enterprise/issues/6473

**Comment by sumnerib** [comment]
Failed again on _master_ with oracle-11: https://jenkins.hazelcast.com/job/Hazelcast-master-sonar/252/testReport/junit/com.hazelcast.map/MapDestroyTest/destroyRepeatedly/

**Comment by olukas** [comment]
Failed again on _master_ with oracle-11 (Sonar build): https://jenkins.hazelcast.com/job/Hazelcast-master-sonar/256/testReport/com.hazelcast.map/MapDestroyTest/destroyRepeatedly/

**Comment by k-jamroz** [comment]
This test is slow and should no longer run in sonar builds, as it was moved to NightlyTests in fc292a75ac26593c1137327b08a9cef5cec1aa8d
