### ISSUE TITLE
com.hazelcast.test.starter.test.HazelcastVersionLocatorTest.testDownloadVersion [HZ-3144]

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hazelcast#25451]
_master_ (commit 9143d090707ff1f48e4d3b4a655988046a58562b)
Failed on OpenJDK11: https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK11-arm64-nightly/30/testReport/junit/com.hazelcast.test.starter.test/HazelcastVersionLocatorTest/testDownloadVersion/

<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: File "/home/ec2-user/workspace/Hazelcast-master-OpenJDK11-arm64-nightly/hazelcast/[0.022s][info][gc] Using G1/com/hazelcast/hazelcast/4.0/hazelcast-4.0.jar" not found
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at com.hazelcast.test.starter.test.HazelcastVersionLocatorTest.assertHash(HazelcastVersionLocatorTest.java:67)
	at com.hazelcast.test.starter.test.HazelcastVersionLocatorTest.testDownloadVersion(HazelcastVersionLocatorTest.java:59)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:829)

```

</details>

<details><summary>Standard output:</summary>

```
Started Running Test: testDownloadVersion

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-OpenJDK11-arm64-nightly/30/

**Comment by JackPGreen** [comment]
It's likely I broke this in #25178

**Comment by JackPGreen** [comment]
I think I can understand what's going on:

We now extract the Maven repo location by running `mvn help:evaluate -Dexpression=settings.localRepository --quiet --batch-mode -DforceStdout`, which typically returns a single line, and we use that as the path.
But instead, `gc` information is also being logged *to the same line*, confusing things.

I *think* the build environment has additional `gc` logging turned on - and I *think* this only exists in Java 11.

I've replicated this by using Java 11:
`export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk-11.jdk/Contents/Home`
Adding the logging flags:
`export MAVEN_OPTS="-verbose:gc -XX:+PrintGC -Xlog:gc"`
Then run:
`mvn help:evaluate -Dexpression=settings.localRepository --quiet --batch-mode -DforceStdout`
And the following is produced:
```
[0.002s][warning][gc] -XX:+PrintGC is deprecated. Will use -Xlog:gc instead.
[0.005s][info   ][gc] Using G1
[0.383s][info   ][gc] GC(0) Pause Young (Normal) (G1 Evacuation Pause) 24M->3M(512M) 3.189ms
[0.679s][info   ][gc] GC(1) Pause Young (Concurrent Start) (Metadata GC Threshold) 60M->6M(512M) 4.503ms
[0.679s][info   ][gc] GC(2) Concurrent Cycle
[0.681s][info   ][gc] GC(2) Pause Remark 7M->7M(512M) 0.648ms
[0.681s][info   ][gc] GC(2) Pause Cleanup 7M->7M(512M) 0.044ms
[0.683s][info   ][gc] GC(2) Concurrent Cycle 4.159ms
/Users/jgreen/.m2/repository
```

I.E. not just one line.

To be investigated further...

**Comment by sumnerib** [comment]
Failed again on _master_ with openjdk-17: https://jenkins.hazelcast.com/job/Hazelcast-master-ZuluJDK17-nightly/85/testReport/junit/com.hazelcast.test.starter.test/HazelcastVersionLocatorTest/testDownloadVersion/

**Comment by olukas** [comment]
Failed again on _master_ with oracle-11: https://jenkins.hazelcast.com/job/Hazelcast-master-sonar/255/testReport/com.hazelcast.test.starter.test/HazelcastVersionLocatorTest/testDownloadVersion/
