### ISSUE TITLE
Multiple test failures due to 'java.lang.ClassNotFoundException: com.hazelcast.config.Config'

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hazelcast#25450]
_master_ (commit 9143d090707ff1f48e4d3b4a655988046a58562b)
Failed on oracle-11: https://jenkins.hazelcast.com/job/Hazelcast-master-sonar/251/

<details><summary>Example Stacktrace:</summary>

```
com.hazelcast.test.starter.GuardianException: java.lang.ClassNotFoundException: com.hazelcast.config.Config
	at com.hazelcast.test.starter.HazelcastStarterUtils.rethrowGuardianException(HazelcastStarterUtils.java:53)
	at com.hazelcast.test.starter.HazelcastStarter.createInstanceViaHazelcast(HazelcastStarter.java:318)
	at com.hazelcast.test.starter.HazelcastStarter.newHazelcastInstanceWithNetwork(HazelcastStarter.java:274)
	at com.hazelcast.test.starter.HazelcastStarter.newHazelcastInstance(HazelcastStarter.java:129)
	at com.hazelcast.test.starter.HazelcastStarter.newHazelcastInstance(HazelcastStarter.java:101)
	at com.hazelcast.test.starter.HazelcastStarter.newHazelcastInstance(HazelcastStarter.java:70)
	at com.hazelcast.client.map.ClientMapReplaceAllTest.startHazelcastInstances(ClientMapReplaceAllTest.java:62)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:365)
	at com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37)
	at com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:104)
	at com.hazelcast.test.metrics.MetricsRule$1.evaluate(MetricsRule.java:63)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:50)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:29)
	at com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:41)
Caused by: java.lang.ClassNotFoundException: com.hazelcast.config.Config
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
	at com.hazelcast.test.starter.HazelcastAPIDelegatingClassloader.loadClass(HazelcastAPIDelegatingClassloader.java:120)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at com.hazelcast.test.starter.HazelcastStarter.createInstanceViaHazelcast(HazelcastStarter.java:308)
	... 13 more

```

</details>

<details><summary>Example Standard output:</summary>

```
Started Running Test: testReplaceAllWithLambdaFunction
22:19:56,978  INFO |testReplaceAllWithLambdaFunction| - [HazelcastTestSupport] main - Shutting down node factory as @After action
BuildInfo right after testReplaceAllWithLambdaFunction(com.hazelcast.client.map.ClientMapReplaceAllTest): BuildInfo{version='5.4.0-SNAPSHOT', build='20230913', buildNumber=20230913, revision=9143d09, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'testReplaceAllWithLambdaFunction(com.hazelcast.client.map.ClientMapReplaceAllTest):'
22:19:45, accumulated pauses: 134 ms, max pause: 8 ms, pauses over 1000 ms: 0
22:19:50, accumulated pauses: 70 ms, max pause: 11 ms, pauses over 1000 ms: 0
22:19:55, accumulated pauses: 687 ms, max pause: 673 ms, pauses over 1000 ms: 0


No metrics recorded during the test

```

</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-sonar/251/

- `com.hazelcast.client.map.ClientMapReplaceAllTest`
- `com.hazelcast.client.starter.HazelcastClientStarterTest`
- `com.hazelcast.test.starter.test.HazelcastProxyFactoryTest`

**Comment by sumnerib** [comment]
Failed again on _master_ with OpenJDK11: https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK11-arm64-nightly/30/

**Comment by olukas** [comment]
Failed again on _master_ with oracle-11: https://jenkins.hazelcast.com/job/Hazelcast-master-sonar/255/testReport/

**Comment by olukas** [comment]
Closing the test failure - it doesn't seem to be related to `master` or the latest maintenance stream `5.5.z` and it hasn't fail in the last 3 months. Feel free to reopen test failure if it occurs on `master` or on the latest maintenance stream.
