### ISSUE TITLE
com.hazelcast.jet.sql.impl.opt.logical.LogicalSelectTest.(?)

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#25466]
_master_ (commit 0976dc2d899eaa53174c6f6e2c7b3c58d456113b)

Failed on openjdk-sts (openjdk-20): https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK-sts-nightly/47/testReport/com.hazelcast.jet.sql.impl.opt.logical/LogicalSelectTest/___/
<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: already initialized
	at com.hazelcast.jet.SimpleTestInClusterSupport.initialize(SimpleTestInClusterSupport.java:67)
	at com.hazelcast.jet.sql.impl.opt.logical.LogicalSelectTest.setUpClass(LogicalSelectTest.java:39)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at com.hazelcast.test.OverridePropertyRule$1.evaluate(OverridePropertyRule.java:66)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.lang.Thread.run(Thread.java:1623)

```
</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: stressTest[processingGuarantee:exactlyOnce, restartGraceful:false] in 0.185 seconds.
19:59:44,044  INFO || - [SimpleTestInClusterSupport] Time-limited test - Terminating instance factory in SimpleTestInClusterSupport.@AfterClass
19:59:44,044  INFO || - [LifecycleService] Thread-1087 - [127.0.0.1]:5703 [dev] [5.4.0-SNAPSHOT] [127.0.0.1]:5703 is SHUTTING_DOWN
19:59:44,044  INFO || - [Node] Thread-1087 - [127.0.0.1]:5703 [dev] [5.4.0-SNAPSHOT] Node is already shutting down... Waiting for shutdown process to complete...
19:59:44,045  INFO || - [LifecycleService] Thread-1087 - [127.0.0.1]:5703 [dev] [5.4.0-SNAPSHOT] [127.0.0.1]:5703 is SHUTDOWN
19:59:44,045  INFO || - [LifecycleService] Thread-1087 - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] [127.0.0.1]:5702 is SHUTTING_DOWN
19:59:44,045  INFO || - [Node] Thread-1087 - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] Node is already shutting down... Waiting for shutdown process to complete...
19:59:44,045  INFO || - [LifecycleService] Thread-1087 - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] [127.0.0.1]:5702 is SHUTDOWN
19:59:44,045  INFO || - [LifecycleService] Thread-1087 - [127.0.0.1]:5705 [dev] [5.4.0-SNAPSHOT] [127.0.0.1]:5705 is SHUTTING_DOWN
19:59:44,045  INFO || - [Node] Thread-1087 - [127.0.0.1]:5705 [dev] [5.4.0-SNAPSHOT] Node is already shutting down... Waiting for shutdown process to complete...
19:59:44,045  INFO || - [LifecycleService] Thread-1087 - [127.0.0.1]:5705 [dev] [5.4.0-SNAPSHOT] [127.0.0.1]:5705 is SHUTDOWN
19:59:44,045  INFO || - [LifecycleService] Thread-1087 - [127.0.0.1]:5704 [dev] [5.4.0-SNAPSHOT] [127.0.0.1]:5704 is SHUTTING_DOWN
19:59:44,045  INFO || - [Node] Thread-1087 - [127.0.0.1]:5704 [dev] [5.4.0-SNAPSHOT] Node is already shutting down... Waiting for shutdown process to complete...
19:59:44,045  INFO || - [LifecycleService] Thread-1087 - [127.0.0.1]:5704 [dev] [5.4.0-SNAPSHOT] [127.0.0.1]:5704 is SHUTDOWN
19:59:44,045  INFO || - [LifecycleService] Thread-1087 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
19:59:44,045  INFO || - [Node] Thread-1087 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Node is already shutting down... Waiting for shutdown process to complete...
19:59:44,045  INFO || - [LifecycleService] Thread-1087 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-OpenJDK-sts-nightly/47/

**Comment by k-jamroz** [comment]
Likely false positive caused by timeout in other tests inheriting from `SimpleTestInClusterSupport`, in particular `SqlSTSInnerNonEquiJoinFaultToleranceStressTest`
