### ISSUE TITLE
com.hazelcast.client.config.XmlYamlClientConfigBuilderEqualsTest.testFullExampleClientConfig [HZ-3261]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#25464]
_master_ (commit 0976dc2d899eaa53174c6f6e2c7b3c58d456113b)

Failed on Windows - MicrosoftJDK17: https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK17/81/testReport/com.hazelcast.client.config/XmlYamlClientConfigBuilderEqualsTest/testFullExampleClientConfig/
<details><summary>Stacktrace:</summary>

```
com.hazelcast.config.InvalidConfigurationException: Invalid byte 1 of 1-byte UTF-8 sequence.
	at com.hazelcast.client.config.XmlClientConfigBuilder.parse(XmlClientConfigBuilder.java:125)
	at com.hazelcast.client.config.XmlClientConfigBuilder.parseAndBuildConfig(XmlClientConfigBuilder.java:163)
	at com.hazelcast.client.config.XmlClientConfigBuilder.build(XmlClientConfigBuilder.java:154)
	at com.hazelcast.client.config.XmlClientConfigBuilder.build(XmlClientConfigBuilder.java:147)
	at com.hazelcast.client.config.XmlClientConfigBuilder.build(XmlClientConfigBuilder.java:142)
	at com.hazelcast.client.config.XmlYamlClientConfigBuilderEqualsTest.buildConfigFromXml(XmlYamlClientConfigBuilderEqualsTest.java:127)
	at com.hazelcast.client.config.XmlYamlClientConfigBuilderEqualsTest.testFullExampleClientConfig(XmlYamlClientConfigBuilderEqualsTest.java:60)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.xml.sax.SAXParseException; lineNumber: 259; columnNumber: 28; Invalid byte 1 of 1-byte UTF-8 sequence.
	at java.xml/com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:263)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:342)
	at java.xml/javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:122)
	at com.hazelcast.client.config.XmlClientConfigBuilder.parse(XmlClientConfigBuilder.java:119)
	... 11 more
Caused by: com.sun.org.apache.xerces.internal.impl.io.MalformedByteSequenceException: Invalid byte 1 of 1-byte UTF-8 sequence.
	at java.xml/com.sun.org.apache.xerces.internal.impl.io.UTF8Reader.invalidByte(UTF8Reader.java:702)
	at java.xml/com.sun.org.apache.xerces.internal.impl.io.UTF8Reader.read(UTF8Reader.java:568)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.load(XMLEntityScanner.java:1699)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.scanData(XMLEntityScanner.java:1256)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLScanner.scanComment(XMLScanner.java:800)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanComment(XMLDocumentFragmentScannerImpl.java:1079)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2914)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:542)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:889)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:825)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:247)
	... 14 more

```
</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: testFullClientFailoverConfig in 0.530 seconds.
18:26:17,563  WARN |testFullClientConfig| - [AbstractXmlConfigHelper] testFullClientConfig - Name of the hazelcast schema location[http://www.hazelcast.com/schema/client-config/hazelcast-client-config-5.3.xsd] is incorrect, using default

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-Windows-MicrosoftJDK17/81/

**Comment by olukas** [comment]
Failed again on _master_ with Windows - OracleJDK11: https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-OracleJDK11/465/testReport/com.hazelcast.client.config/XmlYamlClientConfigBuilderEqualsTest/testFullExampleClientConfig/

**Comment by Patras3** [comment]
Failed again on _master_ with Windows - OracleJDK11: https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-OracleJDK11/466/testReport/com.hazelcast.client.config/XmlYamlClientConfigBuilderEqualsTest/testFullExampleClientConfig/

**Comment by olukas** [comment]
Failed again on _master_ with Windows - MicrosoftJDK17: https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK17/83/testReport/com.hazelcast.client.config/XmlYamlClientConfigBuilderEqualsTest/testFullExampleClientConfig/
