### ISSUE TITLE
com.hazelcast.json.internal.JsonMetadataCreationTest.testPutCreatesMetadataForJson

### ISSUE THREAD

**Issue by Patras3** [hazelcast/hazelcast#25534]
_master_ (commit 8150451b5148a350f7428882fb2cb13778415547)

Failed on OpenJDK17: https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK17-Esxi7/56/testReport/junit/com.hazelcast.json.internal/JsonMetadataCreationTest/testPutCreatesMetadataForJson/
<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: Could not find backup member for partition 7
	at com.hazelcast.test.Accessors.getBackupInstance(Accessors.java:164)
	at com.hazelcast.json.internal.JsonMetadataCreationTest.getMetadata(JsonMetadataCreationTest.java:322)
	at com.hazelcast.json.internal.JsonMetadataCreationTest.assertMetadataCreated(JsonMetadataCreationTest.java:349)
	at com.hazelcast.json.internal.JsonMetadataCreationTest.assertMetadataCreated(JsonMetadataCreationTest.java:339)
	at com.hazelcast.json.internal.JsonMetadataCreationTest.testPutCreatesMetadataForJson(JsonMetadataCreationTest.java:111)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-OpenJDK17-Esxi7/56/

**Comment by Patras3** [comment]
Closing as duplicate of https://github.com/hazelcast/hazelcast/issues/25414

**Comment by Patras3** [comment]
Closing as duplicate of https://github.com/hazelcast/hazelcast/issues/25414
