### ISSUE TITLE
com.hazelcast.jet.sql_slow.SqlSlowIndexTest.(?) [HZ-3401]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#25578]
_master_ (commit cb35b49d4fe0c46058135170cc71c23ce9c1cf33)

Failed on oracle-11: https://jenkins.hazelcast.com/job/Hazelcast-master-sonar/268/testReport/com.hazelcast.jet.sql_slow/SqlSlowIndexTest/___/
<details><summary>Stacktrace:</summary>

```
org.junit.runners.model.TestTimedOutException: test timed out after 900 seconds
	at java.base@11.0.18/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@11.0.18/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
	at java.base@11.0.18/java.util.concurrent.FutureTask.awaitDone(FutureTask.java:444)
	at java.base@11.0.18/java.util.concurrent.FutureTask.get(FutureTask.java:203)
	at app//com.hazelcast.test.FailOnTimeoutStatement.getResult(FailOnTimeoutStatement.java:80)
	at app//com.hazelcast.test.FailOnTimeoutStatement.evaluate(FailOnTimeoutStatement.java:58)
	at app//com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:365)
	at app//org.assertj.core.api.SoftAssertionsStatement$1.evaluate(SoftAssertionsStatement.java:41)
	at app//com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37)
	at app//com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:104)
	at app//com.hazelcast.test.metrics.MetricsRule$1.evaluate(MetricsRule.java:63)
	at app//com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:50)
	at app//com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:29)
	at app//com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:41)
	at app//com.hazelcast.test.OverridePropertyRule$1.evaluate(OverridePropertyRule.java:66)
	at java.base@11.0.18/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base@11.0.18/java.lang.Thread.run(Thread.java:834)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-sonar/268/

**Comment by olukas** [comment]
Failed again on _master_ with oracle-11 (Sonar build): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/270/testReport/com.hazelcast.jet.sql_slow/SqlSlowIndexTest/___/

**Comment by olukas** [comment]
Failed again on _master_ with oracle-11: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/272/testReport/com.hazelcast.jet.sql_slow/SqlSlowIndexTest/___/

**Comment by olukas** [comment]
Failed again on _master_ with openjdk-sts (openjdk-20): https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK-sts-nightly/52/testReport/com.hazelcast.jet.sql_slow/SqlSlowIndexTest/___/

**Comment by olukas** [comment]
Failed again on _master_ with openjdk-sts (openjdk-20): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-OpenJDK-sts-nightly/54/testReport/com.hazelcast.jet.sql_slow/SqlSlowIndexTest/___/

**Comment by olukas** [comment]
Failed again on: _master_ (commit b9fba26c4c273f0a142699033cbdfc61042e5c5d)
with oracle-17 (sonar): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/305/testReport/com.hazelcast.jet.sql_slow/SqlSlowIndexTest/test/
<details><summary>Stacktrace:</summary>

```
Multiple Failures (1 failure)
-- failure 1 --
[Test failed for query SELECT __key FROM map1193 WHERE (field1<2) AND __key / 2 = 0] 
Expecting code not to raise a throwable but caught
  "com.hazelcast.sql.HazelcastSqlException: The Jet SQL job failed: CANCEL_FORCEFUL
	at com.hazelcast.sql.impl.CoreQueryUtils.toPublicException(CoreQueryUtils.java:50)
	at com.hazelcast.jet.sql.impl.SqlResultImpl$RowToSqlRowIterator.hasNext(SqlResultImpl.java:129)
	at com.hazelcast.jet.sql.impl.connector.map.index.SqlIndexAbstractTest.sqlKeys(SqlIndexAbstractTest.java:952)
	at com.hazelcast.jet.sql.impl.connector.map.index.SqlIndexAbstractTest.lambda$check0$9(SqlIndexAbstractTest.java:737)
	at org.assertj.core.api.ThrowableAssert.catchThrowable(ThrowableAssert.java:63)
	at org.assertj.core.api.AssertionsForClassTypes.catchThrowable(AssertionsForClassTypes.java:892)
	at org.assertj.core.api.Assertions.catchThrowable(Assertions.java:1366)
	at org.assertj.core.api.Java6StandardSoftAssertionsProvider.assertThatCode(Java6StandardSoftAssertionsProvider.java:958)
	at com.hazelcast.jet.sql.impl.connector.map.index.SqlIndexAbstractTest.check0(SqlIndexAbstractTest.java:732)
	at com.hazelcast.jet.sql.impl.connector.map.index.SqlIndexAbstractTest.check0(SqlIndexAbstractTest.java:723)
	at com.hazelcast.jet.sql.impl.connector.map.index.SqlIndexAbstractTest.check(SqlIndexAbstractTest.java:711)
	at com.hazelcast.jet.sql.impl.connector.map.index.SqlIndexAbstractTest.check(SqlIndexAbstractTest.java:690)
	at com.hazelcast.jet.sql.impl.connector.map.index.SqlIndexAbstractTest.checkFirstColumn(SqlIndexAbstractTest.java:308)
	at com.hazelcast.jet.sql.impl.connector.map.index.SqlIndexAbstractTest.test(SqlIndexAbstractTest.java:154)
	at jdk.internal.reflect.GeneratedMethodAccessor109.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.hazelcast.sql.impl.QueryException: The Jet SQL job failed: CANCEL_FORCEFUL
	at com.hazelcast.sql.impl.QueryException.error(QueryException.java:69)
	at com.hazelcast.jet.sql.impl.PlanExecutor.lambda$execute$5(PlanExecutor.java:556)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
	at com.hazelcast.jet.impl.util.NonCompletableFuture.internalCompleteExceptionally(NonCompletableFuture.java:72)
	at com.hazelcast.jet.impl.AbstractJobProxy$CallbackBase.accept(AbstractJobProxy.java:484)
	at com.hazelcast.jet.impl.AbstractJobProxy$CallbackBase.accept(AbstractJobProxy.java:467)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$WhenCompleteNode.lambda$execute$0(AbstractInvocationFuture.java:1570)
	at com.hazelcast.test.TestLoggingUtils$CustomTestNameAwareForkJoinPool$TestNameAwareRunnable.run(TestLoggingUtils.java:104)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.util.concurrent.CancellationException
	at com.hazelcast.jet.impl.LightMasterContext.lambda$finalizeJob$7(LightMasterContext.java:221)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:887)
	at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2325)
	at com.hazelcast.jet.impl.LightMasterContext.finalizeJob(LightMasterContext.java:206)
	at com.hazelcast.jet.impl.LightMasterContext.lambda$createContext$3(LightMasterContext.java:182)
	at com.hazelcast.jet.impl.LightMasterContext.lambda$invokeOnParticipant$9(LightMasterContext.java:326)
	... 8 more
Caused by: com.hazelcast.jet.impl.exception.JobTerminateRequestedException: CANCEL_FORCEFUL
	at com.hazelcast.jet.impl.execution.ExecutionContext.terminateExecution(ExecutionContext.java:318)
	at com.hazelcast.jet.impl.JobExecutionService.terminateExecution0(JobExecutionService.java:723)
	at com.hazelcast.jet.impl.JobExecutionService.terminateExecution(JobExecutionService.java:719)
	at com.hazelcast.jet.impl.operation.TerminateExecutionOperation.doRun(TerminateExecutionOperation.java:59)
	at com.hazelcast.jet.impl.operation.AsyncOperation.run(AsyncOperation.java:55)
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:193)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:294)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:265)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:216)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:454)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:511)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:618)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:597)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:558)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:241)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:71)
	at com.hazelcast.jet.impl.LightMasterContext.cancelInvocations(LightMasterContext.java:269)
	at com.hazelcast.jet.impl.LightMasterContext.requestTermination(LightMasterContext.java:362)
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$scheduleJobTimeoutTask$63(JobCoordinationService.java:1546)
	at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:111)
"
at SqlIndexAbstractTest.check0(SqlIndexAbstractTest.java:752)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37)
	at com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:104)
	at com.hazelcast.test.metrics.MetricsRule$1.evaluate(MetricsRule.java:63)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:53)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:32)
	at com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:41)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-sonar/305/

**Comment by sumnerib** [comment]
Failed again on _master_ with oracle-17: https://jenkins.hazelcast.com/job/Hazelcast-master-sonar/315/testReport/junit/com.hazelcast.jet.sql_slow/SqlSlowIndexTest/

**Comment by Patras3** [comment]
Failed again on _master_ with OpenJDK17: https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK17-nightly-Esxi7/59/testReport/com.hazelcast.jet.sql_slow/SqlSlowIndexTest/___/

**Comment by Patras3** [comment]
Crashed again:
https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK21-nightly/15/console
```
00:13:56 [INFO] Running com.hazelcast.jet.sql_slow.SqlSlowIndexTest
00:14:03 0: rip=0x00007fa050a8499b @rip=[0xffffffffffffffff] (os::print_hotspot_os_backtrace()+27) [gcc frame, calls gcc]
00:14:03 1: rip=0x00007fa05020165d @rip=[0x00007f9f22976da8] (jvm_unexpected_exception_handler+157) [gcc frame, calls gcc]
00:14:03 2: rip=0x00007fa050201705 @rip=[0x00007f9f22976e58] (jvm_unexpected_exception_helper+69) [gcc frame, calls gcc]
00:14:03 3: rip=0x00007fa04f9c3db8 @rip=[0x00007f9f22976e68] (signal_chain_handler+1912) [gcc frame, calls gcc]
00:14:03 4: rip=0x00007fa052726520 @rip=[0x00007f9f22976ff8] (libc.so.6+0) [gcc frame, calls gcc]
00:14:03 5: rip=0x00007fa0507cc03d @rip=[0x00007f9f22977d18] (StatSamplerTask::task()+61) [gcc frame, calls gcc]
00:14:03 6: rip=0x00007fa0507dc9f2 @rip=[0x00007f9f22977d48] (PeriodicTask::real_time_tick(unsigned long)+178) [gcc frame, calls gcc]
00:14:03 7: rip=0x00007fa0507de71b @rip=[0x00007f9f22977d88] (WatcherThread::run()+219) [gcc frame, calls gcc]
00:14:03 8: rip=0x00007fa0501fac90 @rip=[0x00007f9f22977e08] (_start_thread+208) [gcc frame, calls gcc]
00:14:03 9: rip=0x00007fa04f9c4ec3 @rip=[0x00007f9f22977e38] (preRun+35) [gcc frame, calls gcc]
00:14:03 #
00:14:03 # An unexpected error has been detected by Java Runtime Environment:
00:14:03 #
00:14:03 #  Bus error (0x7) at pc=0x7fa050795b9e, pid=56, tid=101
00:14:03 #
00:14:03 # Java VM: Zing 64-Bit Tiered VM Zing23.12.0.0+4 (21.0.1-zing_23.12.0.0-b4-product-linux-X86_64, mixed mode)
00:14:03 # Problematic frame:
00:14:03 # C  (nil)
00:14:03 #
00:14:03 _print_native_stack_used: 0
00:14:03 # An error report file with more information is saved as:
00:14:03 # /home/jenkins/jenkins_slave/workspace/Hazelcast-master-ZingJDK21-nightly/hs_err_pid56.log
```

**Comment by Patras3** [comment]
This comment was automatically generated to summarize test results for the last 90 days.

```

For branch: 5.3.z
Builds between : 2024-07-01 03:11 - 2024-07-01 03:11
Jobs: 1, Runs: 1, Passed: 0, Failed: 1, Skipped: 0, Fail Ratio: 100.00%
Run on:
+------------------------------------------------+
| JDK      | PASSED | FAILED | SKIPPED |  RATIO  |
+------------------------------------------------+
| oracle-8 |   0    |   1    |    0    | 100.00% |
+------------------------------------------------+

Builds Timeline:
2024-07-01 03:11 - FAILED (oracle-8):
    https://jenkins.hazelcast.com/job/Hazelcast-5.3.z-OracleJDK8-nightly/9/testReport/com.hazelcast.jet.sql_slow/SqlSlowIndexTest/(?)/

----------------------------------------
```

More details can be generated here: [Run jenkins build (Click Proceed -> Back to previous page -> Click job name -> Find new build)](https://jenkins.hazelcast.com/job/test-failure-summary/buildWithParameters?TEST=com.hazelcast.jet.sql_slow.SqlSlowIndexTest.(?)&SINCE=90%20days%20ago%20at%20midnight)

**Comment by olukas** [comment]
Closing the test failure - it doesn't seem to be related to `master` or the latest maintenance stream `5.5.z`. Feel free to reopen test failure if it occurs on `master` or on the latest maintenance stream.
