### ISSUE TITLE
Class cast exception during invocation of storeAll method of ringbuffer

### ISSUE THREAD

**Issue by nthed** [hazelcast/hazelcast#25587]
**Describe the bug**
From a  hazelcast client (5.3.1) we are accessing a remote ring buffer (hazelcast server 5.3.1) trying to insert a byte[] record. This procedure works as expected. 
In addition we have configured a storing mechanism for the items of the ring buffer by implementing the RingbufferStore<byte[]> interface so as to store the inserted items in the db. 
When we enqueue from the client one record at a time the solution works as expected. 
However when we enqueue multiple items at once, then the storeall operation of the RingBufferStore implementation is invoked, and an exception is thrown.
Our implementation is not reached at all, and a class cast exception is thrown during com.hazelcast.ringbuffer.impl.RingbufferStoreWrapper.storeAll

- From within the client we insert multiple items, by invoking ringbuffer.addAllAsync(myListofBytes, OverflowPolicy.OVERWRITE) with the first argument as a List<byte[]> and this operation succeeds but the following exception is thrown when storeall operation is invoked.
- When we try to insert one item, we invoke ringbuffer.add(byteItem) with the first argument as byte[] everything that works as expected

Stack trace and store all implementation below:
Do you see any issue in our implementation, or is it something that needs to be investigated by Hazelcast team?

**Expected behavior**
The store all operation should be invoked from the hazelcast engine without any class cast exception

**Additional context**

Log showing the exception below

_Caused by: java.lang.ClassCastException: class [Ljava.lang.Object; cannot be cast to class [[B ([Ljava.lang.Object; and [[B are in module java.base of loader 'bootstrap')
      at io.zeebe.hazelcast.exporter.TheRingBufferObjectStore.storeAll(TheRingBufferObjectStore.java:13) ~[?:?]
      at com.hazelcast.ringbuffer.impl.RingbufferStoreWrapper.storeAll(RingbufferStoreWrapper.java:194) ~[?:?]
      at com.hazelcast.ringbuffer.impl.RingbufferContainer.addAll(RingbufferContainer.java:327) ~[?:?]
      at com.hazelcast.ringbuffer.impl.operations.AddAllOperation.run(AddAllOperation.java:70) ~[?:?]
      at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:193) ~[?:?]
      at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:299) ~[?:?]
      at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:270) ~[?:?]
      at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:219) ~[?:?]
      at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:454) ~[?:?]
      at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:511) ~[?:?]
      at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:618) ~[?:?]
      at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:597) ~[?:?]
      at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:558) ~[?:?]
      at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:241) ~[?:?]
      at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:71) ~[?:?]
      at com.hazelcast.client.impl.protocol.task.AbstractPartitionMessageTask.processInternal(AbstractPartitionMessageTask.java:51) ~[?:?]
      at com.hazelcast.client.impl.protocol.task.AbstractAsyncMessageTask.processMessage(AbstractAsyncMessageTask.java:71) ~[?:?]
      at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:169) ~[?:?]
      at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:132) ~[?:?]
      at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:198) ~[?:?]
      at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:212) ~[?:?]
      at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:146) ~[?:?]
      at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.loop(OperationThread.java:134) ~[?:?]
      at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:115) ~[?:?]
      at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:111) ~[?:?]_

**Store all implementation below**

```
public class TheRingBufferObjectStore implements RingbufferStore<byte[]> 

       public void storeAll(long firstItemSequence, byte[][] items) {
              System.out.println("In store all");
              Connection connection = null;
              PreparedStatement statement = null;
              try {
                     connection = dataSource.getConnection();
                     statement = connection.prepareStatement(
                                  "INSERT INTO public.mytable (sequencehazelcast, recordhazelcast) VALUES(?, ?);");

                     for (byte[] data : items) {
                           statement.setLong(1, firstItemSequence);
                           statement.setBytes(2, data);
                           statement.addBatch();
                           firstItemSequence++;
                     }
               long start = System.currentTimeMillis();
               int[] inserted = statement.executeBatch();
               long end = System.currentTimeMillis();
              } catch (SQLException e) {
                     e.printStackTrace();
              } finally {
                     try {
                           connection.close();
                           statement.close();
                     } catch (SQLException e) {
                           e.printStackTrace();
                     }
                     
              }
       }
```

**Comment by vbekiaris** [comment]
hello @nthed, what is the configured in-memory format of your `Ringbuffer`?

**Comment by nthed** [comment]
Hi,

The ring buffer has the following config

	<ringbuffer name="default">
		<capacity>100000</capacity>
		<backup-count>1</backup-count>
		<async-backup-count>0</async-backup-count>
		<time-to-live-seconds>0</time-to-live-seconds>
		<in-memory-format>BINARY</in-memory-format>
		<merge-policy batch-size="100">com.hazelcast.spi.merge.PutIfAbsentMergePolicy</merge-policy>
       <ringbuffer-store>
            <class-name>io.zeebe.hazelcast.exporter.TheRingBufferObjectStore</class-name>
        </ringbuffer-store>
	</ringbuffer>

Thanks

**Comment by nthed** [comment]
@vbekiaris 
The same issue occurs even when we try to enqueue a wrapper object e.g. and configure the ring buffer with in-memory-format of OBJECT

`public class Event implements Serializable {

	private static final long serialVersionUID = -6382044077973677674L;
	
	private byte[] transformedRecord;

	public Event(byte[] transformedRecord) {
		super();
		this.transformedRecord = transformedRecord;
	}
	
	public byte[] getTransformedRecord() {
		return transformedRecord;
	}

	public void setTransformedRecord(byte[] transformedRecord) {
		this.transformedRecord = transformedRecord;
	}

}`

**Comment by JPMoresmau** [comment]
I ran into the same error using MEMORY representation. The interface define storeAll as taking a T[] but the code in RingbufferStoreWrapper always generate an Object[], which is incompatible. I had to define my store as taking Object as type parameter and not my real type.
