### ISSUE TITLE
com.hazelcast.client.tpc.ClientAsyncSocketReaderTest [HZ-4260]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#25723]
_master_ (commit 9ca2e4fd52c109e1040e8b1058b5adf46d80d87a)

Failed on oracle-11: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/284/testReport/com.hazelcast.client.tpc/ClientAsyncSocketReaderTest/

Following tests failed with the same exception:
- `com.hazelcast.client.tpc.ClientAsyncSocketReaderTest.testMessageSizeLimits_afterAuth`
- `com.hazelcast.client.tpc.ClientAsyncSocketReaderTest.testAuth_withNotFoundUuid`
- `com.hazelcast.client.tpc.ClientAsyncSocketReaderTest.testProtocolBytesAndAuth`
- `com.hazelcast.client.tpc.ClientAsyncSocketReaderTest.testValidProtocolBytes_whenSentPartByPart`

<details><summary>Stacktrace:</summary>

```
java.lang.NullPointerException
	at com.hazelcast.client.tpc.ClientAsyncSocketReaderTest.getTpcToken(ClientAsyncSocketReaderTest.java:234)
	at com.hazelcast.client.tpc.ClientAsyncSocketReaderTest.testMessageSizeLimits_afterAuth(ClientAsyncSocketReaderTest.java:139)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)

```
</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: testAuth_withMismatchedToken_forTpcDisabledClient in 2.311 seconds.
Started Running Test: testMessageSizeLimits_afterAuth
22:37:47,684  INFO |testMessageSizeLimits_afterAuth| - [MetricsConfigHelper] testMessageSizeLimits_afterAuth - [LOCAL] [dev] [5.4.0-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
22:37:47,685  INFO |testMessageSizeLimits_afterAuth| - [logo] testMessageSizeLimits_afterAuth - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
22:37:47,685  INFO |testMessageSizeLimits_afterAuth| - [system] testMessageSizeLimits_afterAuth - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Copyright (c) 2008-2023, Hazelcast, Inc. All Rights Reserved.
22:37:47,685  INFO |testMessageSizeLimits_afterAuth| - [system] testMessageSizeLimits_afterAuth - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Hazelcast Platform 5.4.0-SNAPSHOT (20231016 - 9ca2e4f) starting at [127.0.0.1]:5701
22:37:47,685  INFO |testMessageSizeLimits_afterAuth| - [system] testMessageSizeLimits_afterAuth - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Cluster name: dev
22:37:47,685  INFO |testMessageSizeLimits_afterAuth| - [system] testMessageSizeLimits_afterAuth - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed. For more information, see the documentation for Integrity Checker.
22:37:47,685  INFO |testMessageSizeLimits_afterAuth| - [system] testMessageSizeLimits_afterAuth - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] The Jet engine is disabled.
To enable the Jet engine on the members, do one of the following:
  - Change member config using Java API: config.getJetConfig().setEnabled(true)
  - Change XML/YAML configuration property: Set hazelcast.jet.enabled to true
  - Add system property: -Dhz.jet.enabled=true (for Hazelcast embedded, works only when loading config via Config.load)
  - Add environment variable: HZ_JET_ENABLED=true (recommended when running container image. For Hazelcast embedded, works only when loading config via Config.load)
22:37:47,688  INFO |testMessageSizeLimits_afterAuth| - [MetricsConfigHelper] testMessageSizeLimits_afterAuth - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
22:37:47,688  INFO |testMessageSizeLimits_afterAuth| - [TpcServerBootstrap] testMessageSizeLimits_afterAuth - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] TPC: enabled
22:37:47,693  INFO |testMessageSizeLimits_afterAuth| - [Node] testMessageSizeLimits_afterAuth - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Using Multicast discovery
22:37:47,693  WARN |testMessageSizeLimits_afterAuth| - [CPSubsystem] testMessageSizeLimits_afterAuth - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
22:37:47,704  INFO |testMessageSizeLimits_afterAuth| - [TpcServerBootstrap] testMessageSizeLimits_afterAuth - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Starting TpcServerBootstrap
22:37:47,705  INFO |testMessageSizeLimits_afterAuth| - [TpcEngine] testMessageSizeLimits_afterAuth - Starting 1 reactors of type [NIO]
22:37:47,705  INFO |testMessageSizeLimits_afterAuth| - [NioAsyncServerSocket] testMessageSizeLimits_afterAuth - hz.ClientMultiMapLockTest_wonderful_buck.partition-operation.thread-0 Binding to /127.0.0.1:11000
22:37:47,706  INFO |testMessageSizeLimits_afterAuth| - [NioAsyncServerSocket] hz.ClientMultiMapLockTest_wonderful_buck.partition-operation.thread-0 - /127.0.0.1:11000 started accepting
22:37:47,706  INFO |testMessageSizeLimits_afterAuth| - [Diagnostics] testMessageSizeLimits_afterAuth - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
22:37:47,706  INFO |testMessageSizeLimits_afterAuth| - [LifecycleService] testMessageSizeLimits_afterAuth - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] [127.0.0.1]:5701 is STARTING
22:37:49,721  INFO |testMessageSizeLimits_afterAuth| - [ClusterService] testMessageSizeLimits_afterAuth - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] 

Members {size:1, ver:1} [
	Member [127.0.0.1]:5701 - 7bfc2f4d-36bd-4b14-9095-d69442a1783b this
]

22:37:49,721  INFO |testMessageSizeLimits_afterAuth| - [LifecycleService] testMessageSizeLimits_afterAuth - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] [127.0.0.1]:5701 is STARTED
22:37:49,725  INFO |testMessageSizeLimits_afterAuth| - [ClientInvocationService] testMessageSizeLimits_afterAuth - hz.client_4789 [dev] [5.4.0-SNAPSHOT] Running with 2 response threads, dynamic=true
22:37:49,726  INFO |testMessageSizeLimits_afterAuth| - [LifecycleService] testMessageSizeLimits_afterAuth - hz.client_4789 [dev] [5.4.0-SNAPSHOT] HazelcastClient 5.4.0-SNAPSHOT (20231016 - 9ca2e4f) is STARTING
22:37:49,726  INFO |testMessageSizeLimits_afterAuth| - [LifecycleService] testMessageSizeLimits_afterAuth - hz.client_4789 [dev] [5.4.0-SNAPSHOT] HazelcastClient 5.4.0-SNAPSHOT (20231016 - 9ca2e4f) is STARTED
22:37:49,727  INFO |testMessageSizeLimits_afterAuth| - [ClientConnectionManager] testMessageSizeLimits_afterAuth - hz.client_4789 [dev] [5.4.0-SNAPSHOT] Trying to connect to cluster: dev
22:37:49,727  INFO |testMessageSizeLimits_afterAuth| - [ClientConnectionManager] testMessageSizeLimits_afterAuth - hz.client_4789 [dev] [5.4.0-SNAPSHOT] Trying to connect to [127.0.0.1]:5701
22:37:49,728 DEBUG |testMessageSizeLimits_afterAuth| - [AuthenticationMessageTask] hz.ClientMultiMapLockTest_wonderful_buck.priority-generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Processing authentication with clientUuid 563be694-d055-4416-b4d6-f58d59434a45 and clientName hz.client_4789
22:37:49,729  INFO |testMessageSizeLimits_afterAuth| - [AuthenticationMessageTask] hz.ClientMultiMapLockTest_wonderful_buck.priority-generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Received auth from Connection[id=1, /127.0.0.1:5701->/127.0.0.1:41109, qualifier=null, endpoint=[127.0.0.1]:41109, remoteUuid=563be694-d055-4416-b4d6-f58d59434a45, alive=true, connectionType=JVM, planeIndex=-1], successfully authenticated, clientUuid: 563be694-d055-4416-b4d6-f58d59434a45, client name: hz.client_4789, client version: 5.4.0-SNAPSHOT
22:37:49,730  INFO |testMessageSizeLimits_afterAuth| - [TpcChannelConnector] testMessageSizeLimits_afterAuth - hz.client_4789 [dev] [5.4.0-SNAPSHOT] Initiating connection attempts to TPC channels running on ports [11000] for ClientConnection{alive=true, connectionId=1, channel=NioChannel{/127.0.0.1:41109->/127.0.0.1:5701}, remoteAddress=[127.0.0.1]:5701, lastReadTime=2023-10-16 22:37:49.729, lastWriteTime=2023-10-16 22:37:49.728, closedTime=never}
22:37:49,730  INFO |testMessageSizeLimits_afterAuth| - [LifecycleService] testMessageSizeLimits_afterAuth - hz.client_4789 [dev] [5.4.0-SNAPSHOT] HazelcastClient 5.4.0-SNAPSHOT (20231016 - 9ca2e4f) is CLIENT_CONNECTED
22:37:49,730  INFO |testMessageSizeLimits_afterAuth| - [ClientConnectionManager] testMessageSizeLimits_afterAuth - hz.client_4789 [dev] [5.4.0-SNAPSHOT] Authenticated with server [127.0.0.1]:5701:7bfc2f4d-36bd-4b14-9095-d69442a1783b, server version: 5.4.0-SNAPSHOT, local address: /127.0.0.1:41109
22:37:49,730  INFO |testMessageSizeLimits_afterAuth| - [TpcChannelConnector] hz.client_4789.internal-1 - hz.client_4789 [dev] [5.4.0-SNAPSHOT] Trying to connect to TPC channel on port 11000 for ClientConnection{alive=true, connectionId=1, channel=NioChannel{/127.0.0.1:41109->/127.0.0.1:5701}, remoteAddress=[127.0.0.1]:5701, lastReadTime=2023-10-16 22:37:49.729, lastWriteTime=2023-10-16 22:37:49.728, closedTime=never}
22:37:49,730  INFO |testMessageSizeLimits_afterAuth| - [Diagnostics] testMessageSizeLimits_afterAuth - hz.client_4789 [dev] [5.4.0-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
22:37:49,730 TRACE |testMessageSizeLimits_afterAuth| - [ClientListenerService] hz.client_4789.internal-2 - hz.client_4789 [dev] [5.4.0-SNAPSHOT] Register attempt of ClusterViewListenerHandler to ClientConnection{alive=true, connectionId=1, channel=NioChannel{/127.0.0.1:41109->/127.0.0.1:5701}, remoteAddress=[127.0.0.1]:5701, lastReadTime=2023-10-16 22:37:49.729, lastWriteTime=2023-10-16 22:37:49.728, closedTime=never}
22:37:49,731  INFO |testMessageSizeLimits_afterAuth| - [NioAsyncServerSocket] hz.ClientMultiMapLockTest_wonderful_buck.partition-operation.thread-0 - NioAsyncServerSocket[/127.0.0.1:11000] accepted: /127.0.0.1:32779->/127.0.0.1:11000
22:37:49,731  INFO |testMessageSizeLimits_afterAuth| - [ClientClusterService] hz.client_4789.event-40142 - hz.client_4789 [dev] [5.4.0-SNAPSHOT] 

Members [1] {
	Member [127.0.0.1]:5701 - 7bfc2f4d-36bd-4b14-9095-d69442a1783b
}

22:37:49,731 TRACE |testMessageSizeLimits_afterAuth| - [ClientListenerService] ForkJoinPool.commonPool-worker-11 - hz.client_4789 [dev] [5.4.0-SNAPSHOT] Registered ClusterViewListenerHandler to ClientConnection{alive=true, connectionId=1, channel=NioChannel{/127.0.0.1:41109->/127.0.0.1:5701}, remoteAddress=[127.0.0.1]:5701, lastReadTime=2023-10-16 22:37:49.731, lastWriteTime=2023-10-16 22:37:49.730, closedTime=never}
22:37:49,731 ERROR |testMessageSizeLimits_afterAuth| - [ClientConnectionManager] hz.client_4789.internal-1 - hz.client_4789 [dev] [5.4.0-SNAPSHOT] Failed to execute java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@7d426abc[Completed exceptionally: java.lang.AssertionError]
java.lang.AssertionError: null
	at com.hazelcast.client.impl.protocol.ClientMessage$Frame.<init>(ClientMessage.java:466) ~[classes/:?]
	at com.hazelcast.client.impl.protocol.ClientMessage$Frame.<init>(ClientMessage.java:462) ~[classes/:?]
	at com.hazelcast.client.impl.protocol.codec.builtin.ByteArrayCodec.encode(ByteArrayCodec.java:27) ~[classes/:?]
	at com.hazelcast.client.impl.protocol.codec.ClientTpcAuthenticationCodec.encodeRequest(ClientTpcAuthenticationCodec.java:75) ~[classes/:?]
	at com.hazelcast.client.impl.connection.tcp.TpcChannelConnector.authenticate(TpcChannelConnector.java:132) ~[classes/:?]
	at com.hazelcast.client.impl.connection.tcp.TpcChannelConnector.connect(TpcChannelConnector.java:119) ~[classes/:?]
	at com.hazelcast.client.impl.connection.tcp.TpcChannelConnector.lambda$initiate$0(TpcChannelConnector.java:99) ~[classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76) [classes/:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:111) [classes/:?]
22:37:49,732 TRACE |testMessageSizeLimits_afterAuth| - [ClientListenerService] hz.client_4789.eventRegistration- - hz.client_4789 [dev] [5.4.0-SNAPSHOT] Register attempt of ClientListenerRegistration{codec=com.hazelcast.client.impl.spi.impl.ClientInvocationServiceImpl$1@4fa9433, handler=com.hazelcast.client.impl.spi.impl.ClientInvocationServiceImpl$BackupEventHandler@1e512838} to ClientConnection{alive=true, connectionId=1, channel=NioChannel{/127.0.0.1:41109->/127.0.0.1:5701}, remoteAddress=[127.0.0.1]:5701, lastReadTime=2023-10-16 22:37:49.731, lastWriteTime=2023-10-16 22:37:49.730, closedTime=never}
22:37:49,732 TRACE |testMessageSizeLimits_afterAuth| - [ClientListenerService] hz.client_4789.eventRegistration- - hz.client_4789 [dev] [5.4.0-SNAPSHOT] Registered ClientListenerRegistration{codec=com.hazelcast.client.impl.spi.impl.ClientInvocationServiceImpl$1@4fa9433, handler=com.hazelcast.client.impl.spi.impl.ClientInvocationServiceImpl$BackupEventHandler@1e512838} to ClientConnection{alive=true, connectionId=1, channel=NioChannel{/127.0.0.1:41109->/127.0.0.1:5701}, remoteAddress=[127.0.0.1]:5701, lastReadTime=2023-10-16 22:37:49.732, lastWriteTime=2023-10-16 22:37:49.732, closedTime=never}
22:37:49,733  INFO |testMessageSizeLimits_afterAuth| - [ClientStatisticsService] testMessageSizeLimits_afterAuth - Client statistics is enabled with period 5 seconds.
22:37:49,733  INFO |testMessageSizeLimits_afterAuth| - [NioAsyncServerSocket] hz.ClientMultiMapLockTest_wonderful_buck.partition-operation.thread-0 - NioAsyncServerSocket[/127.0.0.1:11000] accepted: /127.0.0.1:53712->/127.0.0.1:11000
22:37:50,797  INFO |testMessageSizeLimits_afterAuth| - [NioAsyncSocket] hz.ClientMultiMapLockTest_wonderful_buck.partition-operation.thread-0 - Closing NioAsyncSocket[/127.0.0.1:11000->/127.0.0.1:53712] due to Socket closed by peer
22:37:50,808  INFO |testMessageSizeLimits_afterAuth| - [LifecycleService] main - hz.client_4789 [dev] [5.4.0-SNAPSHOT] HazelcastClient 5.4.0-SNAPSHOT (20231016 - 9ca2e4f) is SHUTTING_DOWN
22:37:50,809  INFO |testMessageSizeLimits_afterAuth| - [ClientConnectionManager] main - hz.client_4789 [dev] [5.4.0-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5701:7bfc2f4d-36bd-4b14-9095-d69442a1783b, connection: ClientConnection{alive=false, connectionId=1, channel=NioChannel{/127.0.0.1:41109->/127.0.0.1:5701}, remoteAddress=[127.0.0.1]:5701, lastReadTime=2023-10-16 22:37:50.805, lastWriteTime=2023-10-16 22:37:50.804, closedTime=2023-10-16 22:37:50.808}
22:37:50,809  INFO |testMessageSizeLimits_afterAuth| - [LifecycleService] main - hz.client_4789 [dev] [5.4.0-SNAPSHOT] HazelcastClient 5.4.0-SNAPSHOT (20231016 - 9ca2e4f) is CLIENT_DISCONNECTED
22:37:50,809  INFO |testMessageSizeLimits_afterAuth| - [TcpServerConnection] hz.ClientMultiMapLockTest_wonderful_buck.IO.thread-in-0 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Connection[id=1, /127.0.0.1:5701->/127.0.0.1:41109, qualifier=null, endpoint=[127.0.0.1]:41109, remoteUuid=563be694-d055-4416-b4d6-f58d59434a45, alive=false, connectionType=JVM, planeIndex=-1] closed. Reason: Connection closed by the other side
22:37:50,809  INFO |testMessageSizeLimits_afterAuth| - [NioAsyncSocket] hz.ClientMultiMapLockTest_wonderful_buck.partition-operation.thread-0 - Closing NioAsyncSocket[/127.0.0.1:11000->/127.0.0.1:32779] due to Socket closed by peer
22:37:50,809  INFO |testMessageSizeLimits_afterAuth| - [ClientEndpointManager] hz.ClientMultiMapLockTest_wonderful_buck.event-40141 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Destroying ClientEndpoint{connection=Connection[id=1, /127.0.0.1:5701->/127.0.0.1:41109, qualifier=null, endpoint=[127.0.0.1]:41109, remoteUuid=563be694-d055-4416-b4d6-f58d59434a45, alive=false, connectionType=JVM, planeIndex=-1], clientUuid=563be694-d055-4416-b4d6-f58d59434a45, clientName=hz.client_4789, authenticated=true, clientVersion=5.4.0-SNAPSHOT, creationTime=1697495869728, latest clientAttributes=lastStatisticsCollectionTime=1697495869733,enterprise=false,clientType=JVM,clientVersion=5.4.0-SNAPSHOT,clusterConnectionTimestamp=1697495869728,clientAddress=127.0.0.1,clientName=hz.client_4789,credentials.principal=null,os.committedVirtualMemorySize=49465548800,os.freePhysicalMemorySize=123986849792,os.freeSwapSpaceSize=6276624384,os.maxFileDescriptorCount=1048576,os.openFileDescriptorCount=293,os.processCpuTime=7373330000000,os.systemLoadAverage=15.33,os.totalPhysicalMemorySize=405607223296,os.totalSwapSpaceSize=8589930496,runtime.availableProcessors=8,runtime.freeMemory=4933762224,runtime.maxMemory=8589934592,runtime.totalMemory=8589934592,runtime.uptime=3395228,runtime.usedMemory=3656172368, labels=[]}
22:37:50,809  INFO |testMessageSizeLimits_afterAuth| - [LifecycleService] main - hz.client_4789 [dev] [5.4.0-SNAPSHOT] HazelcastClient 5.4.0-SNAPSHOT (20231016 - 9ca2e4f) is SHUTDOWN
22:37:50,810  INFO |testMessageSizeLimits_afterAuth| - [LifecycleService] main - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
22:37:50,810  INFO |testMessageSizeLimits_afterAuth| - [Node] main - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Shutting down multicast service...
22:37:50,810  INFO |testMessageSizeLimits_afterAuth| - [Node] main - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Shutting down connection manager...
22:37:50,811  INFO |testMessageSizeLimits_afterAuth| - [Node] main - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Shutting down node engine...
22:37:50,812  INFO |testMessageSizeLimits_afterAuth| - [TpcServerBootstrap] main - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] TpcServerBootstrap shutdown
22:37:50,812  INFO |testMessageSizeLimits_afterAuth| - [NioAsyncServerSocket] hz.ClientMultiMapLockTest_wonderful_buck.partition-operation.thread-0 - Closing NioAsyncServerSocket[/127.0.0.1:11000] due to Reactor-1 is terminating.
22:37:50,812  INFO |testMessageSizeLimits_afterAuth| - [NioReactor] hz.ClientMultiMapLockTest_wonderful_buck.partition-operation.thread-0 - hz.ClientMultiMapLockTest_wonderful_buck.partition-operation.thread-0 terminated
22:37:50,812  INFO |testMessageSizeLimits_afterAuth| - [TpcServerBootstrap] main - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] TpcServerBootstrap terminated
22:37:50,812  INFO |testMessageSizeLimits_afterAuth| - [NodeExtension] main - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Destroying node NodeExtension.
22:37:50,813  INFO |testMessageSizeLimits_afterAuth| - [Node] main - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Hazelcast Shutdown is completed in 3 ms.
22:37:50,813  INFO |testMessageSizeLimits_afterAuth| - [LifecycleService] main - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-sonar/284/

**Comment by olukas** [comment]
Failed again on _master_ with oracle-11 (Sonar build): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/285/testReport/com.hazelcast.client.tpc/ClientAsyncSocketReaderTest/testValidProtocolBytes_whenSentPartByPart/

**Comment by olukas** [comment]
Failed again on _master_ with ibm-11: https://jenkins.hazelcast.com/job/Hazelcast-master-Openj9-11-nightly/127/testReport/com.hazelcast.client.tpc/ClientAsyncSocketReaderTest/

**Comment by sumnerib** [comment]
Failed again on _master_ with ibm-11: https://jenkins.hazelcast.com/job/Hazelcast-master-Openj9-11-nightly/128/testReport/junit/com.hazelcast.client.tpc/

**Comment by olukas** [comment]
Failed again on _master_ with oracle-17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/304/testReport/com.hazelcast.client.tpc/ClientAsyncSocketReaderTest/

**Comment by olukas** [comment]
Fails constantly on sonar and almost constantly on other platforms.
