### ISSUE TITLE
com.hazelcast.jet.sql_slow.SqlSlowIndexTest.test [HZ-3716]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#25726]
_master_ (commit 81de97058c70ee05f834a252646d966884cdbd30)

Failed on ibm-11: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Openj9-11-nightly/126/testReport/com.hazelcast.jet.sql_slow/SqlSlowIndexTest/test_3/
<details><summary>Stacktrace:</summary>

```
org.assertj.core.error.AssertJMultipleFailuresError: 

Multiple Failures (1 failure)
-- failure 1 --
[Test failed for query SELECT __key FROM map1160 WHERE ?<field1 ORDER BY field1 DESC] 
Expecting code not to raise a throwable but caught
  "com.hazelcast.sql.HazelcastSqlException: The Jet SQL job failed: CANCEL_FORCEFUL
	at com.hazelcast.sql.impl.CoreQueryUtils.toPublicException(CoreQueryUtils.java:50)
	at com.hazelcast.jet.sql.impl.SqlResultImpl$RowToSqlRowIterator.hasNext(SqlResultImpl.java:129)
	at com.hazelcast.jet.sql.impl.connector.map.index.SqlIndexAbstractTest.sqlKeys(SqlIndexAbstractTest.java:943)
	at com.hazelcast.jet.sql.impl.connector.map.index.SqlIndexAbstractTest.lambda$check0$9(SqlIndexAbstractTest.java:728)
	at org.assertj.core.api.ThrowableAssert.catchThrowable(ThrowableAssert.java:63)
	at org.assertj.core.api.AssertionsForClassTypes.catchThrowable(AssertionsForClassTypes.java:892)
	at org.assertj.core.api.Assertions.catchThrowable(Assertions.java:1366)
	at org.assertj.core.api.Java6StandardSoftAssertionsProvider.assertThatCode(Java6StandardSoftAssertionsProvider.java:958)
	at com.hazelcast.jet.sql.impl.connector.map.index.SqlIndexAbstractTest.check0(SqlIndexAbstractTest.java:723)
	at com.hazelcast.jet.sql.impl.connector.map.index.SqlIndexAbstractTest.check0(SqlIndexAbstractTest.java:714)
	at com.hazelcast.jet.sql.impl.connector.map.index.SqlIndexAbstractTest.check(SqlIndexAbstractTest.java:710)
	at com.hazelcast.jet.sql.impl.connector.map.index.SqlIndexAbstractTest.check(SqlIndexAbstractTest.java:681)
	at com.hazelcast.jet.sql.impl.connector.map.index.SqlIndexAbstractTest.checkFirstColumn(SqlIndexAbstractTest.java:286)
	at com.hazelcast.jet.sql.impl.connector.map.index.SqlIndexAbstractTest.test(SqlIndexAbstractTest.java:145)
	at jdk.internal.reflect.GeneratedMethodAccessor250.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: com.hazelcast.sql.impl.QueryException: The Jet SQL job failed: CANCEL_FORCEFUL
	at com.hazelcast.sql.impl.QueryException.error(QueryException.java:69)
	at com.hazelcast.jet.sql.impl.PlanExecutor.lambda$execute$5(PlanExecutor.java:562)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at com.hazelcast.jet.impl.util.NonCompletableFuture.internalCompleteExceptionally(NonCompletableFuture.java:72)
	at com.hazelcast.jet.impl.AbstractJobProxy$CallbackBase.accept(AbstractJobProxy.java:484)
	at com.hazelcast.jet.impl.AbstractJobProxy$CallbackBase.accept(AbstractJobProxy.java:467)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$WhenCompleteNode.lambda$execute$0(AbstractInvocationFuture.java:1570)
	at com.hazelcast.test.TestLoggingUtils$CustomTestNameAwareForkJoinPool$TestNameAwareRunnable.run(TestLoggingUtils.java:104)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.util.concurrent.CancellationException
	at com.hazelcast.jet.impl.LightMasterContext.lambda$finalizeJob$7(LightMasterContext.java:221)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:883)
	at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2251)
	at com.hazelcast.jet.impl.LightMasterContext.finalizeJob(LightMasterContext.java:206)
	at com.hazelcast.jet.impl.LightMasterContext.lambda$createContext$3(LightMasterContext.java:182)
	at com.hazelcast.jet.impl.LightMasterContext.lambda$invokeOnParticipant$9(LightMasterContext.java:326)
	... 8 more
Caused by: com.hazelcast.jet.impl.exception.JobTerminateRequestedException: CANCEL_FORCEFUL
	at com.hazelcast.jet.impl.execution.ExecutionContext.terminateExecution(ExecutionContext.java:318)
	at com.hazelcast.jet.impl.JobExecutionService.terminateExecution0(JobExecutionService.java:723)
	at com.hazelcast.jet.impl.JobExecutionService.terminateExecution(JobExecutionService.java:719)
	at com.hazelcast.jet.impl.operation.TerminateExecutionOperation.doRun(TerminateExecutionOperation.java:59)
	at com.hazelcast.jet.impl.operation.AsyncOperation.run(AsyncOperation.java:55)
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:193)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:294)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:265)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:216)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:454)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:511)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:618)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:597)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:558)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:241)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:71)
	at com.hazelcast.jet.impl.LightMasterContext.cancelInvocations(LightMasterContext.java:269)
	at com.hazelcast.jet.impl.LightMasterContext.requestTermination(LightMasterContext.java:362)
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$scheduleJobTimeoutTask$63(JobCoordinationService.java:1546)
	at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:840)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:111)
"
at SqlIndexAbstractTest.check0(SqlIndexAbstractTest.java:743)
	at com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37)
	at com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:104)
	at com.hazelcast.test.metrics.MetricsRule$1.evaluate(MetricsRule.java:63)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:50)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:29)
	at com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:41)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:840)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-Openj9-11-nightly/126/

**Comment by olukas** [comment]
Failed again on _master_ with zing-17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZingJDK17-nightly/47/testReport/com.hazelcast.jet.sql_slow/SqlSlowIndexTest/test_5/

**Comment by sumnerib** [comment]
Failed again on _master_ with ibm-11: https://jenkins.hazelcast.com/job/Hazelcast-master-Openj9-11-nightly/128/testReport/junit/com.hazelcast.jet.sql_slow/SqlSlowIndexTest/test/

Different stacktrace:

```
java.lang.NullPointerException
	at com.hazelcast.jet.SimpleTestInClusterSupport.instance(SimpleTestInClusterSupport.java:220)
	at com.hazelcast.jet.sql.SqlTestSupport.createMapping(SqlTestSupport.java:531)
	at com.hazelcast.jet.sql.impl.connector.map.index.SqlIndexAbstractTest.before(SqlIndexAbstractTest.java:135)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:365)
	at org.assertj.core.api.SoftAssertionsStatement$1.evaluate(SoftAssertionsStatement.java:41)
	at com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37)
	at com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:104)
	at com.hazelcast.test.metrics.MetricsRule$1.evaluate(MetricsRule.java:63)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:53)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:32)
	at com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:41)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by olukas** [comment]
Failed again on _master_ with:
- oracle-17 (sonar): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/305/testReport/com.hazelcast.jet.sql_slow/
- ibm-11: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Openj9-11-nightly/129/testReport/com.hazelcast.jet.sql_slow/

**Comment by sumnerib** [comment]
Failed again on _master_ with oracle-17: https://jenkins.hazelcast.com/job/Hazelcast-master-sonar/314/testReport/junit/com.hazelcast.jet.sql_slow/

**Comment by k-jamroz** [comment]
@Patras3 I will increase the timeouts again.

Could we get a report from tests with parameter values? After JUnit5 upgrade they are not available in jenkins. They might be helpful to check the most problematic parameter value combinations.

**Comment by k-jamroz** [comment]
Let's see if #26012 will be sufficient

**Comment by Patras3** [comment]
> Let's see if #26012 will be sufficient

Recently, tests passed in 40 minutes. Thanks a lot!
https://jenkins.hazelcast.com/job/Hazelcast-master-ZuluJDK17-nightly/93/testReport/com.hazelcast.jet.sql_slow/SqlSlowIndexTest/

**Comment by Patras3** [comment]
> Could we get a report from tests with parameter values? After JUnit5 upgrade they are not available in jenkins. They might be helpful to check the most problematic parameter value combinations.

It will work again after merging https://github.com/hazelcast/hazelcast-mono/pull/760 :tada:
