### ISSUE TITLE
com.hazelcast.cp.internal.CPMemberAutoRemoveTest.when_missingCPNodeReplacedByNewNode_then_itIsAutomaticallyRemoved [HZ-3588]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#25806]
_5.3.z_ (commit e94205f5468352f7798c13f3be87d2826f80a39f)

Failed on openj9-11: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-Openj9-11/108/testReport/com.hazelcast.cp.internal/CPMemberAutoRemoveTest/when_missingCPNodeReplacedByNewNode_then_itIsAutomaticallyRemoved/
<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: 

Expecting
  [CPMember{uuid=0f98f9a9-f5ba-4c57-9065-bdb0e683d025, address=[127.0.0.1]:5701},
    CPMember{uuid=44f23def-5403-4d75-a050-646de945b7ff, address=[127.0.0.1]:5702},
    CPMember{uuid=73fdde6c-5c6b-4380-a66c-79bcf1afff04, address=[127.0.0.1]:5703}]
not to contain
  [CPMember{uuid=73fdde6c-5c6b-4380-a66c-79bcf1afff04, address=[127.0.0.1]:5703}]
but found
  [CPMember{uuid=73fdde6c-5c6b-4380-a66c-79bcf1afff04, address=[127.0.0.1]:5703}]

	at com.hazelcast.cp.internal.CPMemberAutoRemoveTest.lambda$when_missingCPNodeReplacedByNewNode_then_itIsAutomaticallyRemoved$1(CPMemberAutoRemoveTest.java:76)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1285)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1389)
	at com.hazelcast.cp.internal.CPMemberAutoRemoveTest.when_missingCPNodeReplacedByNewNode_then_itIsAutomaticallyRemoved(CPMemberAutoRemoveTest.java:73)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:840)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-5.maintenance-Openj9-11/108/

**Comment by arodionov** [comment]
**Test-failure analysis** 
The issue happens because the new member started faster than the terminated member has been added to the `missingMembers` list.

We are looking for CP members who are not among cluster members: 
https://github.com/hazelcast/hazelcast/blob/c15043352a2ec157ccf36458e767c935ecadcafb/hazelcast/src/main/java/com/hazelcast/cp/internal/RaftService.java#L663-L671

Because we are using IP `Addresse`s to compare members, we can't distinguish a terminated member from a newly started member
