### ISSUE TITLE
classloading.JavaXCacheDependencyTest and classloading.JavaXCacheDependencyClientTest

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#25834]
_master_ (commit ac460ebcd4e3c0db9538731df1133b1d415bf8aa)

Following tests failed with the same exception:
- `classloading.JavaXCacheDependencyClientTest.createHazelcastInstance_getCache`
- `classloading.JavaXCacheDependencyClientTest.createHazelcastInstance_getCacheManager`
- `classloading.JavaXCacheDependencyClientTest.createHazelcastInstance`
- `classloading.JavaXCacheDependencyTest.createHazelcastInstance_getCache`
- `classloading.JavaXCacheDependencyTest.createHazelcastInstance_getCacheManager`
- `classloading.JavaXCacheDependencyTest.createHazelcastInstance`

Failed on oracle-11: https://jenkins.hazelcast.com/job/Hazelcast-master-OracleJDK11-nightly/971/testReport/classloading/
<details><summary>Stacktrace:</summary>

```
java.lang.reflect.InvocationTargetException
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at classloading.AbstractJavaXCacheDependencyTest.createHazelcastInstance(AbstractJavaXCacheDependencyTest.java:99)
	at classloading.AbstractJavaXCacheDependencyTest.createHazelcastInstance_getCache(AbstractJavaXCacheDependencyTest.java:72)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NoClassDefFoundError: javax/cache/CacheException
	at com.hazelcast.cache.impl.CacheDataSerializerHook.createFactory(CacheDataSerializerHook.java:193)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.<init>(DataSerializableSerializer.java:71)
	at com.hazelcast.internal.serialization.impl.SerializationServiceV1.<init>(SerializationServiceV1.java:159)
	at com.hazelcast.internal.serialization.impl.SerializationServiceV1$Builder.build(SerializationServiceV1.java:471)
	at com.hazelcast.internal.serialization.impl.DefaultSerializationServiceBuilder.createSerializationService(DefaultSerializationServiceBuilder.java:309)
	at com.hazelcast.internal.serialization.impl.DefaultSerializationServiceBuilder.build(DefaultSerializationServiceBuilder.java:241)
	at com.hazelcast.internal.serialization.impl.DefaultSerializationServiceBuilder.build(DefaultSerializationServiceBuilder.java:57)
	at com.hazelcast.client.impl.clientside.DefaultClientExtension.createSerializationService(DefaultClientExtension.java:146)
	at com.hazelcast.client.impl.clientside.HazelcastClientInstanceImpl.<init>(HazelcastClientInstanceImpl.java:254)
	at com.hazelcast.client.HazelcastClient.constructHazelcastClient(HazelcastClient.java:471)
	at com.hazelcast.client.HazelcastClient.newHazelcastClientInternal(HazelcastClient.java:421)
	at com.hazelcast.client.HazelcastClient.newHazelcastClient(HazelcastClient.java:137)
	... 8 more

```
</details>

<details><summary>Standard output:</summary>

```
01:19:30,545  INFO || - [AbstractConfigLocator] main - Loading 'hazelcast-default.xml' from the classpath.
01:19:30,595  WARN || - [AbstractXmlConfigHelper] main - Name of the hazelcast schema location[http://www.hazelcast.com/schema/config/hazelcast-config-5.3.xsd] is incorrect, using default
01:19:30,707  INFO || - [ExternalConfigurationOverride] main - Detected external configuration entries in environment variables: []
01:19:30,707  WARN || - [ExternalConfigurationOverride] main - Unrecognized environment variables configuration entries: [hazelcast.test.aws.instance.private.ip]
01:19:30,719  INFO || - [MetricsConfigHelper] main - [LOCAL] [dev] [5.4.0-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
01:19:30,728  INFO || - [logo] main - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
01:19:30,728  INFO || - [system] main - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Copyright (c) 2008-2023, Hazelcast, Inc. All Rights Reserved.
01:19:30,729  INFO || - [system] main - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Hazelcast Platform 5.4.0-SNAPSHOT (20231025 - ac460eb) starting at [127.0.0.1]:5701
01:19:30,729  INFO || - [system] main - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Cluster name: dev
01:19:30,729  INFO || - [system] main - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed. For more information, see the documentation for Integrity Checker.
01:19:30,729  INFO || - [system] main - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] The Jet engine is disabled.
To enable the Jet engine on the members, do one of the following:
  - Change member config using Java API: config.getJetConfig().setEnabled(true)
  - Change XML/YAML configuration property: Set hazelcast.jet.enabled to true
  - Add system property: -Dhz.jet.enabled=true (for Hazelcast embedded, works only when loading config via Config.load)
  - Add environment variable: HZ_JET_ENABLED=true (recommended when running container image. For Hazelcast embedded, works only when loading config via Config.load)
01:19:30,739  INFO || - [MetricsConfigHelper] main - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
01:19:30,746  INFO || - [TpcServerBootstrap] main - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] TPC: disabled
01:19:30,961  INFO || - [Node] main - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Using Multicast discovery
01:19:30,963  WARN || - [CPSubsystem] main - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
01:19:31,128  INFO || - [Diagnostics] main - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
01:19:31,134  INFO || - [LifecycleService] main - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] [127.0.0.1]:5701 is STARTING
01:19:33,205  INFO || - [ClusterService] main - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] 

Members {size:1, ver:1} [
	Member [127.0.0.1]:5701 - 64e4964b-544e-476e-97b6-c883765f90ce this
]

01:19:33,210  INFO || - [LifecycleService] main - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] [127.0.0.1]:5701 is STARTED
Started Running Test: createHazelcastInstance_getCache

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-OracleJDK11-nightly/971/

**Comment by olukas** [comment]
Failed again on _master_ with OpenJDK17 (esxi7): https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK17-nightly-Esxi7/55/testReport/classloading/

**Comment by JackPGreen** [comment]
Introduced in https://github.com/hazelcast/hazelcast/pull/25785
