### ISSUE TITLE
wrong entry is given to extractor

### ISSUE THREAD

**Issue by kgignatyev** [hazelcast/hazelcast#25851]
Hazelcast 5.3.5 
**Describe the bug**
Custom serializer throws exception
```
com.hazelcast.query.QueryException: java.lang.ClassCastException: class com.hazelcast.internal.serialization.impl.GenericRecordQueryReader cannot be cast to class com.kgignatyev.benchmarks.hazelcastbenchmark.BMCompany (com.hazelcast.internal.serialization.impl.GenericRecordQueryReader and com.kgignatyev.benchmarks.hazelcastbenchmark.BMCompany are in unnamed module of loader 'app')
	at com.hazelcast.query.impl.getters.Extractors.extract(Extractors.java:88) ~[hazelcast-5.3.5.jar:5.3.5]
	at com.hazelcast.query.impl.getters.Extractors.extract(Extractors.java:75) ~[hazelcast-5.3.5.jar:5.3.5]
	at com.hazelcast.query.impl.QueryableEntry.extractAttributeValue(QueryableEntry.java:116) ~[hazelcast-5.3.5.jar:5.3.5]
	at com.hazelcast.query.impl.QueryableEntry.getAttributeValue(QueryableEntry.java:62) ~[hazelcast-5.3.5.jar:5.3.5]
	at com.hazelcast.query.impl.predicates.AbstractPredicate.readAttributeValue(AbstractPredicate.java:156) ~[hazelcast-5.3.5.jar:5.3.5]
	at com.hazelcast.query.impl.predicates.AbstractPredicate.apply(AbstractPredicate.java:64) ~[hazelcast-5.3.5.jar:5.3.5]
	at com.hazelcast.query.impl.predicates.AndPredicate.apply(AndPredicate.java:136) ~[hazelcast-5.3.5.jar:5.3.5]
	at com.hazelcast.query.impl.predicates.PagingPredicateImpl.apply(PagingPredicateImpl.java:234) ~[hazelcast-5.3.5.jar:5.3.5]
	at com.hazelcast.map.impl.query.PartitionScanRunner$1.accept(PartitionScanRunner.java:104) ~[hazelcast-5.3.5.jar:5.3.5]
	at com.hazelcast.map.impl.query.PartitionScanRunner$1.accept(PartitionScanRunner.java:89) ~[hazelcast-5.3.5.jar:5.3.5]
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.forEach(DefaultRecordStore.java:332) ~[hazelcast-5.3.5.jar:5.3.5]
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.forEach(DefaultRecordStore.java:315) ~[hazelcast-5.3.5.jar:5.3.5]
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.forEachAfterLoad(DefaultRecordStore.java:345) ~[hazelcast-5.3.5.jar:5.3.5]
	at com.hazelcast.map.impl.query.PartitionScanRunner.run(PartitionScanRunner.java:89) ~[hazelcast-5.3.5.jar:5.3.5]
	at com.hazelcast.map.impl.query.CallerRunsPartitionScanExecutor.execute(CallerRunsPartitionScanExecutor.java:43) ~[hazelcast-5.3.5.jar:5.3.5]
	at com.hazelcast.map.impl.query.QueryRunner.runPartitionIndexOrPartitionScanQueryOnGivenOwnedPartition(QueryRunner.java:236) ~[hazelcast-5.3.5.jar:5.3.5]
	at com.hazelcast.map.impl.query.QueryPartitionOperation.runInternal(QueryPartitionOperation.java:46) ~[hazelcast-5.3.5.jar:5.3.5]
	at com.hazelcast.map.impl.operation.MapOperation.run(MapOperation.java:187) ~[hazelcast-5.3.5.jar:5.3.5]
	at com.hazelcast.map.impl.operation.MapOperation.call(MapOperation.java:207) ~[hazelcast-5.3.5.jar:5.3.5]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:299) ~[hazelcast-5.3.5.jar:5.3.5]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:270) ~[hazelcast-5.3.5.jar:5.3.5]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:219) ~[hazelcast-5.3.5.jar:5.3.5]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:180) ~[hazelcast-5.3.5.jar:5.3.5]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:144) ~[hazelcast-5.3.5.jar:5.3.5]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.loop(OperationThread.java:134) ~[hazelcast-5.3.5.jar:5.3.5]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:115) ~[hazelcast-5.3.5.jar:5.3.5]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:111) ~[hazelcast-5.3.5.jar:5.3.5]
Caused by: java.lang.ClassCastException: class com.hazelcast.internal.serialization.impl.GenericRecordQueryReader cannot be cast to class com.kgignatyev.benchmarks.hazelcastbenchmark.BMCompany (com.hazelcast.internal.serialization.impl.GenericRecordQueryReader and com.kgignatyev.benchmarks.hazelcastbenchmark.BMCompany are in unnamed module of loader 'app')
	at com.kgignatyev.benchmarks.hazelcastbenchmark.EmployeeNamesExtractorForObject.extract(Extractors.kt:7) ~[classes/:na]
	at com.hazelcast.query.impl.getters.ExtractorGetter.getValue(ExtractorGetter.java:49) ~[hazelcast-5.3.5.jar:5.3.5]
	at com.hazelcast.query.impl.getters.Getter.getValue(Getter.java:40) ~[hazelcast-5.3.5.jar:5.3.5]
	at com.hazelcast.query.impl.getters.Getter.getValue(Getter.java:48) ~[hazelcast-5.3.5.jar:5.3.5]
	at com.hazelcast.query.impl.getters.Extractors.extract(Extractors.java:86) ~[hazelcast-5.3.5.jar:5.3.5]

```

**Expected behavior**
Extractor should get instance of object when map is configured with InMemoryFormat.OBJECT and CacheDeserializedValues.ALWAYS

Configuration and relevant pieces
```Kotlin

class EmployeeNamesExtractorForObject: ValueExtractor<BMCompany, String> {
    override fun extract(target: BMCompany?, argument: String?, collector: ValueCollector<Any>) {
        if( target == null ) return
        target.employees.forEach {
            collector.addObject( it.fullName )
        }

    }
}



    @Bean
    fun hazelcastConfig(): Config {
        val config = Config.loadFromClasspath(this::class.java.classLoader, "base-hazelcast.yaml")

        val employeeNameAttrConfigForObjects = AttributeConfig("employeeNames", EmployeeNamesExtractorForObject::class.java.canonicalName)

        config.addMapConfig(MapConfig().apply {
            name = allInMemoryCacheName
            backupCount = 1
            inMemoryFormat = InMemoryFormat.OBJECT
            cacheDeserializedValues = CacheDeserializedValues.ALWAYS
            attributeConfigs.add(employeeNameAttrConfigForObjects)
       })
        return config
    }



class BMCompany {
    var id: String = ""
    var name: String = ""
    var industry: String = ""
    var url: String = ""
    var catchPhrase: String = ""
    var employees: MutableList<BMEmployee> = mutableListOf()
}

class BMEmployee {
    var fullName:String = ""
    var title:String = ""
}


```

It looks like Hazelcast gets confused because it picks default compact serializer and it causes line #217 to be true and getValueData() method is used to supply  value rather than getValue()
<img width="1510" alt="image" src="https://github.com/hazelcast/hazelcast/assets/868783/57ca8f3f-2026-4da9-bc28-f9850552bb25">

**Comment by vbekiaris** [comment]
@srknzl can you please have a look?

**Comment by kgignatyev** [comment]
As a workaround I have defined custom serializer for the class, and extractor now gets the proper value, but seems like wrong and very non-obvious interdependency

**Comment by srknzl** [comment]
The "Custom serializer throws exception" seems like a wrong description to me. Extractor throws exception maybe?

**Comment by srknzl** [comment]
I'll work on investigation of this
