### ISSUE TITLE
com.hazelcast.jet.sql instances not shut down

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hazelcast#25861]
_5.0.z_ (commit 65d997fab42359d60dc4c8013ed06ae5969d3008)
Failed on oracle-8: https://jenkins.hazelcast.com/job/Hazelcast-5.0.z-OracleJDK8-nightly/25/

<details><summary>Example Stacktrace:</summary>

```
java.lang.IllegalStateException: Instances haven't been shut down: [HazelcastInstance{name='kind_kowalevski', node=[127.0.0.1]:5701}, HazelcastInstance{name='wizardly_kowalevski', node=[127.0.0.1]:5702}]
	at com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:47)
	at com.hazelcast.test.OverridePropertyRule$1.evaluate(OverridePropertyRule.java:66)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:750)

```

</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-5.0.z-OracleJDK8-nightly/25/

[com.hazelcast.jet.sql_slow.ComparisonPredicateIntegrationSlowTest.com.hazelcast.jet.sql_slow.ComparisonPredicateIntegrationSlowTest](https://jenkins.hazelcast.com/job/Hazelcast-5.0.z-OracleJDK8-nightly/lastSuccessfulBuild/testReport/junit/com.hazelcast.jet.sql_slow/ComparisonPredicateIntegrationSlowTest/com_hazelcast_jet_sql_slow_ComparisonPredicateIntegrationSlowTest/)
[com.hazelcast.jet.sql_slow.JetSqlSlowIndexTest.com.hazelcast.jet.sql_slow.JetSqlSlowIndexTest](https://jenkins.hazelcast.com/job/Hazelcast-5.0.z-OracleJDK8-nightly/lastSuccessfulBuild/testReport/junit/com.hazelcast.jet.sql_slow/JetSqlSlowIndexTest/com_hazelcast_jet_sql_slow_JetSqlSlowIndexTest/)
[com.hazelcast.jet.sql.SqlSplitBrainTest.test_indexScan](https://jenkins.hazelcast.com/job/Hazelcast-5.0.z-OracleJDK8-nightly/lastSuccessfulBuild/testReport/junit/com.hazelcast.jet.sql/SqlSplitBrainTest/test_indexScan/)
[com.hazelcast.jet.sql.SqlSplitBrainTest.test_indexScan](https://jenkins.hazelcast.com/job/Hazelcast-5.0.z-OracleJDK8-nightly/lastSuccessfulBuild/testReport/junit/com.hazelcast.jet.sql/SqlSplitBrainTest/test_indexScan_2/)
[com.hazelcast.jet.sql_slow.MapScanMigrationStressTest.stressTest_sortedIndex](https://jenkins.hazelcast.com/job/Hazelcast-5.0.z-OracleJDK8-nightly/lastSuccessfulBuild/testReport/junit/com.hazelcast.jet.sql_slow/MapScanMigrationStressTest/stressTest_sortedIndex/)
[com.hazelcast.jet.sql_slow.SqlBasicClientSlowTest.com.hazelcast.jet.sql_slow.SqlBasicClientSlowTest](https://jenkins.hazelcast.com/job/Hazelcast-5.0.z-OracleJDK8-nightly/lastSuccessfulBuild/testReport/junit/com.hazelcast.jet.sql_slow/SqlBasicClientSlowTest/com_hazelcast_jet_sql_slow_SqlBasicClientSlowTest/)
[com.hazelcast.jet.sql_slow.SqlBasicSlowTest.com.hazelcast.jet.sql_slow.SqlBasicSlowTest](https://jenkins.hazelcast.com/job/Hazelcast-5.0.z-OracleJDK8-nightly/lastSuccessfulBuild/testReport/junit/com.hazelcast.jet.sql_slow/SqlBasicSlowTest/com_hazelcast_jet_sql_slow_SqlBasicSlowTest/)
[com.hazelcast.jet.sql_slow.SqlOrderBySlowTest.com.hazelcast.jet.sql_slow.SqlOrderBySlowTest](https://jenkins.hazelcast.com/job/Hazelcast-5.0.z-OracleJDK8-nightly/lastSuccessfulBuild/testReport/junit/com.hazelcast.jet.sql_slow/SqlOrderBySlowTest/com_hazelcast_jet_sql_slow_SqlOrderBySlowTest/)

**Comment by sumnerib** [comment]
Failed again on _5.0.z_ with oracle-8: https://jenkins.hazelcast.com/job/Hazelcast-5.0.z-OracleJDK8-nightly/27/testReport/junit/com.hazelcast.jet.sql/

Different stacktrace: 

```
java.lang.AssertionError: some threads were stuck
	at org.junit.Assert.fail(Assert.java:89)
	at com.hazelcast.jet.sql.SqlSplitBrainTest.test_indexScan(SqlSplitBrainTest.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:750)
```

**Comment by sumnerib** [comment]
Failed again on _master_ with oracle-11 (force-offload): https://jenkins.hazelcast.com/job/Hazelcast-master-nightly-force-offload/74/testReport/junit/com.hazelcast.jet.sql_slow/MapScanMigrationStressTest/stressTest_sortedIndex/

**Comment by k-jamroz** [comment]
AFAIK 5.0 is no longer supported, failure on master was probably caused by timeout in `SqlSTSInnerNonEquiJoinFaultToleranceStressTest`
