### ISSUE TITLE
MongoDB mapstore and connector test failures [HZ-4258]

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hazelcast#25880]
_master_ (commit 06337b77d4b376fe1144309a99ba159975d57bd4)
Failed on microsoft-17: https://jenkins.hazelcast.com/job/Hazelcast-master-MicrosoftJDK17/87/

<details><summary>Example Stacktrace:</summary>

```
java.lang.ClassCastException: class com.hazelcast.internal.server.tcp.TcpServerConnectionManager cannot be cast to class com.hazelcast.internal.server.FirewallingServer$FirewallingServerConnectionManager (com.hazelcast.internal.server.tcp.TcpServerConnectionManager and com.hazelcast.internal.server.FirewallingServer$FirewallingServerConnectionManager are in unnamed module of loader 'app')
	at com.hazelcast.test.PacketFiltersUtil.getConnectionManager(PacketFiltersUtil.java:48)
	at com.hazelcast.test.PacketFiltersUtil.resetPacketFiltersFrom(PacketFiltersUtil.java:52)
	at com.hazelcast.jet.SimpleTestInClusterSupport.supportAfter(SimpleTestInClusterSupport.java:126)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:381)
	at com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37)
	at com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:104)
	at com.hazelcast.test.metrics.MetricsRule$1.evaluate(MetricsRule.java:63)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:53)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:32)
	at com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:41)
	at com.hazelcast.test.OverridePropertyRule$1.evaluate(OverridePropertyRule.java:66)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

</details>

<details><summary>Example Standard output:</summary>

```
03:58:34,872  WARN || - [HazelcastInstanceFactory] Time-limited test - WARNING: Classpath misconfiguration: found multiple META-INF/services/com.hazelcast.instance.impl.NodeExtension resources: jar:file:/home/jenkins/jenkins_slave/workspace/Hazelcast-master-MicrosoftJDK17/hazelcast/target/hazelcast-5.4.0-SNAPSHOT.jar!/META-INF/services/com.hazelcast.instance.impl.NodeExtension, jar:file:/home/jenkins/jenkins_slave/workspace/Hazelcast-master-MicrosoftJDK17/hazelcast/target/hazelcast-5.4.0-SNAPSHOT-tests.jar!/META-INF/services/com.hazelcast.instance.impl.NodeExtension
03:58:34,964  INFO || - [MetricsConfigHelper] Time-limited test - [LOCAL] [dev] [5.4.0-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
03:58:35,009  INFO || - [logo] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
03:58:35,009  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Copyright (c) 2008-2023, Hazelcast, Inc. All Rights Reserved.
03:58:35,013  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Hazelcast Platform 5.4.0-SNAPSHOT (20231101 - 06337b7) starting at [127.0.0.1]:5701
03:58:35,013  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Cluster name: dev
03:58:35,014  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed. For more information, see the documentation for Integrity Checker.
03:58:35,014  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Jet is enabled
03:58:35,035  INFO || - [MetricsConfigHelper] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
03:58:35,052  INFO || - [TpcServerBootstrap] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] TPC: disabled
03:58:35,292  INFO || - [Node] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Using Multicast discovery
03:58:35,296  WARN || - [CPSubsystem] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
03:58:35,497  INFO || - [JetServiceBackend] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Setting number of cooperative threads and default parallelism to 2
03:58:35,562  INFO || - [Diagnostics] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
03:58:35,569  INFO || - [LifecycleService] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] [127.0.0.1]:5701 is STARTING
03:58:38,071  INFO || - [ClusterService] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] 

Members {size:1, ver:1} [
	Member [127.0.0.1]:5701 - e145e406-32c5-46cf-abcf-25dbad169619 this
]

03:58:38,084  INFO || - [JobCoordinationService] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Jet started scanning for jobs
03:58:38,089  INFO || - [LifecycleService] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] [127.0.0.1]:5701 is STARTED
03:58:38,137  INFO || - [MetricsConfigHelper] Time-limited test - [LOCAL] [dev] [5.4.0-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
03:58:38,140  INFO || - [logo] Time-limited test - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
03:58:38,141  INFO || - [system] Time-limited test - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] Copyright (c) 2008-2023, Hazelcast, Inc. All Rights Reserved.
03:58:38,141  INFO || - [system] Time-limited test - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] Hazelcast Platform 5.4.0-SNAPSHOT (20231101 - 06337b7) starting at [127.0.0.1]:5702
03:58:38,141  INFO || - [system] Time-limited test - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] Cluster name: dev
03:58:38,142  INFO || - [system] Time-limited test - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed. For more information, see the documentation for Integrity Checker.
03:58:38,142  INFO || - [system] Time-limited test - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] Jet is enabled
03:58:38,159  INFO || - [MetricsConfigHelper] Time-limited test - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
03:58:38,160  INFO || - [TpcServerBootstrap] Time-limited test - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] TPC: disabled
03:58:38,178  INFO || - [Node] Time-limited test - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] Using Multicast discovery
03:58:38,178  WARN || - [CPSubsystem] Time-limited test - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
03:58:38,194  INFO || - [JetServiceBackend] Time-limited test - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] Setting number of cooperative threads and default parallelism to 2
03:58:38,198  INFO || - [Diagnostics] Time-limited test - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
03:58:38,199  INFO || - [LifecycleService] Time-limited test - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] [127.0.0.1]:5702 is STARTING
03:58:38,305  INFO || - [MulticastJoiner] Time-limited test - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] Trying to join to discovered node: [127.0.0.1]:5701
03:58:38,331  INFO || - [TcpServerConnection] hz.MongoGenericMapStoreIT_gallant_wing.IO.thread-in-0 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Initialized new cluster connection between /127.0.0.1:5701 and /127.0.0.1:46801
03:58:38,333  INFO || - [TcpServerConnection] hz.MongoGenericMapStoreIT_crazy_wing.IO.thread-in-0 - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] Initialized new cluster connection between /0.0.0.0:46801 and /127.0.0.1:5701
03:58:38,422  INFO || - [ClusterService] hz.MongoGenericMapStoreIT_gallant_wing.generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] 

Members {size:2, ver:2} [
	Member [127.0.0.1]:5701 - e145e406-32c5-46cf-abcf-25dbad169619 this
	Member [127.0.0.1]:5702 - 499b9ae7-45c2-4b3b-881c-e5835fa2aac8
]

03:58:38,438  INFO || - [ClusterService] hz.MongoGenericMapStoreIT_crazy_wing.generic-operation.thread-1 - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] 

Members {size:2, ver:2} [
	Member [127.0.0.1]:5701 - e145e406-32c5-46cf-abcf-25dbad169619
	Member [127.0.0.1]:5702 - 499b9ae7-45c2-4b3b-881c-e5835fa2aac8 this
]

03:58:38,439  INFO || - [JobCoordinationService] Time-limited test - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] Jet started scanning for jobs
03:58:38,440  INFO || - [LifecycleService] Time-limited test - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] [127.0.0.1]:5702 is STARTED
03:58:38,515  INFO || - [ClientInvocationService] Time-limited test - hz.client_1 [dev] [5.4.0-SNAPSHOT] Running with 2 response threads, dynamic=true
03:58:38,533  INFO || - [LifecycleService] Time-limited test - hz.client_1 [dev] [5.4.0-SNAPSHOT] HazelcastClient 5.4.0-SNAPSHOT (20231101 - 06337b7) is STARTING
03:58:38,534  INFO || - [LifecycleService] Time-limited test - hz.client_1 [dev] [5.4.0-SNAPSHOT] HazelcastClient 5.4.0-SNAPSHOT (20231101 - 06337b7) is STARTED
03:58:38,544  INFO || - [ClientConnectionManager] Time-limited test - hz.client_1 [dev] [5.4.0-SNAPSHOT] Trying to connect to cluster: dev
03:58:38,546  INFO || - [ClientConnectionManager] Time-limited test - hz.client_1 [dev] [5.4.0-SNAPSHOT] Trying to connect to [127.0.0.1]:5701
03:58:38,565  INFO || - [AuthenticationMessageTask] hz.MongoGenericMapStoreIT_gallant_wing.generic-operation.thread-1 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Received auth from Connection[id=2, /127.0.0.1:5701->/127.0.0.1:47337, qualifier=null, endpoint=[127.0.0.1]:47337, remoteUuid=b0111d2b-018f-4f67-93fb-62931d8a0ef9, alive=true, connectionType=JVM, planeIndex=-1], successfully authenticated, clientUuid: b0111d2b-018f-4f67-93fb-62931d8a0ef9, client name: hz.client_1, client version: 5.4.0-SNAPSHOT
03:58:38,570  INFO || - [LifecycleService] Time-limited test - hz.client_1 [dev] [5.4.0-SNAPSHOT] HazelcastClient 5.4.0-SNAPSHOT (20231101 - 06337b7) is CLIENT_CONNECTED
03:58:38,570  INFO || - [ClientConnectionManager] Time-limited test - hz.client_1 [dev] [5.4.0-SNAPSHOT] Authenticated with server [127.0.0.1]:5701:e145e406-32c5-46cf-abcf-25dbad169619, server version: 5.4.0-SNAPSHOT, local address: /127.0.0.1:47337
03:58:38,572  INFO || - [Diagnostics] Time-limited test - hz.client_1 [dev] [5.4.0-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
03:58:38,585  INFO || - [ClientClusterService] hz.client_1.event-3 - hz.client_1 [dev] [5.4.0-SNAPSHOT] 

Members [2] {
	Member [127.0.0.1]:5701 - e145e406-32c5-46cf-abcf-25dbad169619
	Member [127.0.0.1]:5702 - 499b9ae7-45c2-4b3b-881c-e5835fa2aac8
}

03:58:38,589  INFO || - [AuthenticationMessageTask] hz.MongoGenericMapStoreIT_crazy_wing.priority-generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] Received auth from Connection[id=2, /127.0.0.1:5702->/127.0.0.1:50361, qualifier=null, endpoint=[127.0.0.1]:50361, remoteUuid=b0111d2b-018f-4f67-93fb-62931d8a0ef9, alive=true, connectionType=JVM, planeIndex=-1], successfully authenticated, clientUuid: b0111d2b-018f-4f67-93fb-62931d8a0ef9, client name: hz.client_1, client version: 5.4.0-SNAPSHOT
03:58:38,590  INFO || - [ClientConnectionManager] Time-limited test - hz.client_1 [dev] [5.4.0-SNAPSHOT] Authenticated with server [127.0.0.1]:5702:499b9ae7-45c2-4b3b-881c-e5835fa2aac8, server version: 5.4.0-SNAPSHOT, local address: /127.0.0.1:50361
03:58:38,626  INFO || - [ClientStatisticsService] Time-limited test - Client statistics is enabled with period 5 seconds.
Started Running Test: testPut
03:58:38,789  INFO || - [PartitionStateManager] hz.MongoGenericMapStoreIT_gallant_wing.partition-operation.thread-0 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Initializing cluster partition table arrangement...
03:58:38,990 DEBUG || - [GenericMapLoader] hz.MongoGenericMapStoreIT_crazy_wing.cached.thread-3 - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] Initializing for map 190aefc7-73d6-4ec5-9e6c-78854e22b8da
03:58:39,038 DEBUG || - [GenericMapLoader] hz.MongoGenericMapStoreIT_gallant_wing.cached.thread-1 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Initializing for map 190aefc7-73d6-4ec5-9e6c-78854e22b8da
03:58:39,558 DEBUG || - [GenericMapLoader] hz.MongoGenericMapStoreIT_crazy_wing.cached.thread-3 - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] Reading existing mapping for map 190aefc7-73d6-4ec5-9e6c-78854e22b8da
03:58:41,352  INFO |testPut| - [HazelcastTestSupport] Time-limited test - Shutting down node factory as @After action
BuildInfo right after testPut(com.hazelcast.mapstore.mongodb.MongoGenericMapStoreIT): BuildInfo{version='5.4.0-SNAPSHOT', build='20231101', buildNumber=20231101, revision=06337b7, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'testPut(com.hazelcast.mapstore.mongodb.MongoGenericMapStoreIT):'
03:58:35, accumulated pauses: 38 ms, max pause: 33 ms, pauses over 1000 ms: 0
03:58:40, accumulated pauses: 11 ms, max pause: 4 ms, pauses over 1000 ms: 0


No metrics recorded during the test

```

</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-MicrosoftJDK17/87/

Affected packages:
```
com.hazelcast.mapstore.mongodb
com.hazelcast.jet.sql.impl.connector.mongodb
```

**Comment by olukas** [comment]
It seems to fail constantly.

**Comment by olukas** [comment]
Seems to be fixed. Feel free to reopen if it will fail again (and remote `constant-test-failure` label unless it fails constantly).
