### ISSUE TITLE
com.hazelcast.mapstore.* 'NoClassDefFoundError' [HZ-3660]

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hazelcast#25895]
_master_ (commit 0d36189619cd30230e4a68818658c2183c427337)
Failed on oracle-11: https://jenkins.hazelcast.com/job/Hazelcast-master-postgres-16/2/testReport/junit/com.hazelcast.mapstore.postgres/

<details><summary>Example Stacktrace:</summary>

```
java.lang.NoClassDefFoundError: com/hazelcast/shaded/org/apache/calcite/rex/RexVisitor
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3137)
	at java.base/java.lang.Class.getConstructor0(Class.java:3342)
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2553)
	at com.hazelcast.internal.util.ServiceLoader$NewInstanceIterator.next(ServiceLoader.java:293)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at com.hazelcast.jet.sql.impl.connector.SqlConnectorCache.<init>(SqlConnectorCache.java:38)
	at com.hazelcast.jet.sql.impl.CalciteSqlOptimizer.<init>(CalciteSqlOptimizer.java:248)
	at com.hazelcast.sql.impl.SqlServiceImpl.start(SqlServiceImpl.java:95)
	at com.hazelcast.spi.impl.NodeEngineImpl.start(NodeEngineImpl.java:292)
	at com.hazelcast.instance.impl.Node.start(Node.java:483)
	at com.hazelcast.instance.impl.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:125)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:218)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:197)
	at com.hazelcast.test.TestHazelcastInstanceFactory.newHazelcastInstance(TestHazelcastInstanceFactory.java:236)
	at com.hazelcast.jet.SimpleTestInClusterSupport.initializeWitSupplier(SimpleTestInClusterSupport.java:80)
	at com.hazelcast.jet.SimpleTestInClusterSupport.initialize(SimpleTestInClusterSupport.java:68)
	at com.hazelcast.jet.sql.impl.connector.jdbc.JdbcSqlTestSupport.initialize(JdbcSqlTestSupport.java:78)
	at com.hazelcast.jet.sql.impl.connector.jdbc.JdbcSqlTestSupport.initialize(JdbcSqlTestSupport.java:65)
	at com.hazelcast.mapstore.postgres.PostgresGenericMapStoreTest.beforeClass(PostgresGenericMapStoreTest.java:30)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:41)
	at com.hazelcast.test.OverridePropertyRule$1.evaluate(OverridePropertyRule.java:66)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: com.hazelcast.shaded.org.apache.calcite.rex.RexVisitor
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 25 more

```

</details>

<details><summary>Standard output:</summary>

```
11:03:58,970  INFO || - [MetricsConfigHelper] Time-limited test - [LOCAL] [dev] [5.4.0-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
11:03:58,972  INFO || - [logo] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
11:03:58,972  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Copyright (c) 2008-2023, Hazelcast, Inc. All Rights Reserved.
11:03:58,972  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Hazelcast Platform 5.4.0-SNAPSHOT (20231102 - 0d36189) starting at [127.0.0.1]:5701
11:03:58,972  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Cluster name: dev
11:03:58,972  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed. For more information, see the documentation for Integrity Checker.
11:03:58,973  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Jet is enabled
11:03:58,983  INFO || - [MetricsConfigHelper] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
11:03:58,984  INFO || - [TpcServerBootstrap] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] TPC: disabled
11:03:58,998  WARN || - [CPSubsystem] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
11:03:59,019  INFO || - [JetServiceBackend] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Setting number of cooperative threads and default parallelism to 2
11:03:59,055  WARN || - [Node] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Terminating forcefully...
11:03:59,055  INFO || - [Node] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Shutting down connection manager...
11:03:59,055  INFO || - [Node] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Shutting down node engine...
11:03:59,061  INFO || - [NodeExtension] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Destroying node NodeExtension.
11:03:59,061  INFO || - [Node] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Hazelcast Shutdown is completed in 6 ms.
11:03:59,577  INFO || - [SimpleTestInClusterSupport] Time-limited test - Terminating instance factory in SimpleTestInClusterSupport.@AfterClass

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-postgres-16/2/

[com.hazelcast.mapstore.postgres.PostgreGenericMapStoreIntegrationTest.(?)](https://jenkins.hazelcast.com/job/Hazelcast-master-postgres-16/lastSuccessfulBuild/testReport/junit/com.hazelcast.mapstore.postgres/PostgreGenericMapStoreIntegrationTest/___/)
[com.hazelcast.mapstore.postgres.PostgresGenericMapStoreTest.(?)](https://jenkins.hazelcast.com/job/Hazelcast-master-postgres-16/lastSuccessfulBuild/testReport/junit/com.hazelcast.mapstore.postgres/PostgresGenericMapStoreTest/___/)
[com.hazelcast.mapstore.mysql.MySQLGenericMapStoreIntegrationTest.(?)](https://jenkins.hazelcast.com/job/Hazelcast-master-mysql-8.2/lastSuccessfulBuild/testReport/junit/com.hazelcast.mapstore.mysql/MySQLGenericMapStoreIntegrationTest/___/)
[com.hazelcast.mapstore.mysql.MySQLGenericMapStoreTest.(?)](https://jenkins.hazelcast.com/job/Hazelcast-master-mysql-8.2/lastSuccessfulBuild/testReport/junit/com.hazelcast.mapstore.mysql/MySQLGenericMapStoreTest/___/)

**Comment by sumnerib** [comment]
Related: https://github.com/hazelcast/hazelcast-enterprise/issues/6763

**Comment by sumnerib** [comment]
Failed again on _master_ with oracle-11: https://jenkins.hazelcast.com/job/Hazelcast-master-mysql-5.7/30/testReport/junit/com.hazelcast.mapstore.mysql/

**Comment by sumnerib** [comment]
Failed again on _master_ with oracle-11: https://jenkins.hazelcast.com/job/Hazelcast-master-postgres-15/27/testReport/junit/com.hazelcast.mapstore.postgres/

**Comment by olukas** [comment]
Failed again on _master_ with:
-  oracle-11: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-postgres-11/27/testReport/com.hazelcast.mapstore.postgres/
- oracle-11 (postgres 13): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-postgres-13/27/testReport/com.hazelcast.mapstore.postgres/
- oracle-11 (MySQL 8.0): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-mysql-8.0/28/testReport/com.hazelcast.mapstore.mysql/

**Comment by sumnerib** [comment]
Failed again on _master_ with oracle-11: https://jenkins.hazelcast.com/job/Hazelcast-master-postgres-11/28/testReport/junit/com.hazelcast.mapstore.postgres/

**Comment by sumnerib** [comment]
Related errors in `enterprise-sql-it`: https://jenkins.hazelcast.com/job/Hazelcast-EE-master-ZingJDK17-nightly/50/

**Comment by sumnerib** [comment]
Failed again on _master_ with oracle-11 (pg-13): https://jenkins.hazelcast.com/job/Hazelcast-master-postgres-13/28/testReport/junit/com.hazelcast.mapstore.postgres/

**Comment by sumnerib** [comment]
Failed again on _master_ with openjdk-sts (openjdk-20): https://jenkins.hazelcast.com/job/Hazelcast-EE-master-OpenJDK-sts-nightly/54/testReport/junit/com.hazelcast.it.sql/

**Comment by Patras3** [comment]
Failed again on _master_ with oracle-11: https://jenkins.hazelcast.com/job/Hazelcast-master-postgres-11/29/testReport/com.hazelcast.mapstore.postgres/

**Comment by Patras3** [comment]
Reopening as issue occurred again on: _master_ (commit 1dfbd0992f66dbf8747aee16dfead6d953db4d9d)
with oracle-11: https://jenkins.hazelcast.com/job/Hazelcast-master-postgres-14/30/testReport/com.hazelcast.mapstore.postgres/PostgreGenericMapStoreIntegrationTest/___/
<details><summary>Stacktrace:</summary>

```
java.lang.NoClassDefFoundError: com/hazelcast/shaded/org/apache/calcite/rex/RexVisitor
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3137)
	at java.base/java.lang.Class.getConstructor0(Class.java:3342)
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2553)
	at com.hazelcast.internal.util.ServiceLoader$NewInstanceIterator.next(ServiceLoader.java:293)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at com.hazelcast.jet.sql.impl.connector.SqlConnectorCache.<init>(SqlConnectorCache.java:38)
	at com.hazelcast.jet.sql.impl.CalciteSqlOptimizer.<init>(CalciteSqlOptimizer.java:250)
	at com.hazelcast.sql.impl.SqlServiceImpl.start(SqlServiceImpl.java:95)
	at com.hazelcast.spi.impl.NodeEngineImpl.start(NodeEngineImpl.java:292)
	at com.hazelcast.instance.impl.Node.start(Node.java:483)
	at com.hazelcast.instance.impl.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:124)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:218)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:197)
	at com.hazelcast.test.TestHazelcastInstanceFactory.newHazelcastInstance(TestHazelcastInstanceFactory.java:236)
	at com.hazelcast.jet.SimpleTestInClusterSupport.initializeWitSupplier(SimpleTestInClusterSupport.java:80)
	at com.hazelcast.jet.SimpleTestInClusterSupport.initializeWithClientAndConfigSupplier(SimpleTestInClusterSupport.java:99)
	at com.hazelcast.jet.SimpleTestInClusterSupport.initializeWithClient(SimpleTestInClusterSupport.java:90)
	at com.hazelcast.mapstore.GenericMapStoreIntegrationTest.initializeBeforeClass(GenericMapStoreIntegrationTest.java:106)
	at com.hazelcast.mapstore.postgres.PostgreGenericMapStoreIntegrationTest.beforeClass(PostgreGenericMapStoreIntegrationTest.java:35)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:41)
	at com.hazelcast.test.OverridePropertyRule$1.evaluate(OverridePropertyRule.java:66)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: com.hazelcast.shaded.org.apache.calcite.rex.RexVisitor
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 25 more

```
</details>


<details><summary>Standard output:</summary>

```
13:53:50,017  INFO || - [MetricsConfigHelper] Time-limited test - [LOCAL] [dev] [5.4.0-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
13:53:50,066  INFO || - [logo] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
13:53:50,066  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Copyright (c) 2008-2023, Hazelcast, Inc. All Rights Reserved.
13:53:50,080  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Hazelcast Platform 5.4.0-SNAPSHOT (20231121 - 1dfbd09) starting at [127.0.0.1]:5701
13:53:50,080  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Cluster name: dev
13:53:50,080  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed. For more information, see the documentation for Integrity Checker.
13:53:50,081  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Jet is enabled
13:53:50,099  INFO || - [MetricsConfigHelper] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
13:53:50,116  INFO || - [TpcServerBootstrap] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] TPC: disabled
13:53:50,358  WARN || - [CPSubsystem] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
13:53:50,635  INFO || - [JetServiceBackend] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Setting number of cooperative threads and default parallelism to 8
13:53:50,674  WARN || - [Node] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Terminating forcefully...
13:53:50,676  INFO || - [Node] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Shutting down connection manager...
13:53:50,676  INFO || - [Node] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Shutting down node engine...
13:53:50,688  INFO || - [NodeExtension] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Destroying node NodeExtension.
13:53:50,688  INFO || - [Node] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Hazelcast Shutdown is completed in 14 ms.
13:53:51,339  INFO || - [SimpleTestInClusterSupport] Time-limited test - Terminating instance factory in SimpleTestInClusterSupport.@AfterClass

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-postgres-14/30/
^ Build was triggered 20m ago, so for sure after merged fix.

**Comment by TomaszGaweda** [comment]
https://giphy.com/gifs/equipedefrance-allezlesbleues-frustre-3owypkSIpM8xw6p7W0/fullscreen

**Comment by olukas** [comment]
Reopening as issue occurred again on: _master_ (commit cae25cf53c3847ea2c3387651a66da08f78c1853)
with oracle-11: 
- https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-mysql-8.0/31/testReport/com.hazelcast.mapstore.mysql/MySQLGenericMapStoreIT/___/
- https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-mysql-8.0/31/testReport/com.hazelcast.mapstore.mysql/MySQLGenericMapStoreTest/___/

<details><summary>Stacktrace:</summary>

```
java.lang.NoClassDefFoundError: com/hazelcast/shaded/org/apache/calcite/rex/RexVisitor
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3137)
	at java.base/java.lang.Class.getConstructor0(Class.java:3342)
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2553)
	at com.hazelcast.internal.util.ServiceLoader$NewInstanceIterator.next(ServiceLoader.java:293)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at com.hazelcast.jet.sql.impl.connector.SqlConnectorCache.<init>(SqlConnectorCache.java:38)
	at com.hazelcast.jet.sql.impl.CalciteSqlOptimizer.<init>(CalciteSqlOptimizer.java:254)
	at com.hazelcast.sql.impl.SqlServiceImpl.start(SqlServiceImpl.java:95)
	at com.hazelcast.spi.impl.NodeEngineImpl.start(NodeEngineImpl.java:292)
	at com.hazelcast.instance.impl.Node.start(Node.java:483)
	at com.hazelcast.instance.impl.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:124)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:218)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:197)
	at com.hazelcast.test.TestHazelcastInstanceFactory.newHazelcastInstance(TestHazelcastInstanceFactory.java:236)
	at com.hazelcast.jet.SimpleTestInClusterSupport.initializeWitSupplier(SimpleTestInClusterSupport.java:100)
	at com.hazelcast.jet.SimpleTestInClusterSupport.initializeWithClientAndConfigSupplier(SimpleTestInClusterSupport.java:119)
	at com.hazelcast.jet.SimpleTestInClusterSupport.initializeWithClient(SimpleTestInClusterSupport.java:110)
	at com.hazelcast.mapstore.GenericMapStoreIT.initializeBeforeClass(GenericMapStoreIT.java:106)
	at com.hazelcast.mapstore.mysql.MySQLGenericMapStoreIT.beforeClass(MySQLGenericMapStoreIT.java:35)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:41)
	at com.hazelcast.test.OverridePropertyRule$1.evaluate(OverridePropertyRule.java:66)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: com.hazelcast.shaded.org.apache.calcite.rex.RexVisitor
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 25 more

```
</details>


<details><summary>Standard output:</summary>

```
21:23:37,366  INFO || - [MetricsConfigHelper] Time-limited test - [LOCAL] [dev] [5.4.0-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
21:23:37,426  INFO || - [logo] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
21:23:37,427  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Copyright (c) 2008-2023, Hazelcast, Inc. All Rights Reserved.
21:23:37,444  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Hazelcast Platform 5.4.0-SNAPSHOT (20231125 - cae25cf) starting at [127.0.0.1]:5701
21:23:37,444  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Cluster name: dev
21:23:37,444  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed. For more information, see the documentation for Integrity Checker.
21:23:37,445  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Jet is enabled
21:23:37,470  INFO || - [MetricsConfigHelper] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
21:23:37,494  INFO || - [TpcServerBootstrap] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] TPC: disabled
21:23:37,896  WARN || - [CPSubsystem] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
21:23:38,221  INFO || - [JetServiceBackend] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Setting number of cooperative threads and default parallelism to 8
21:23:38,254  WARN || - [Node] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Terminating forcefully...
21:23:38,255  INFO || - [Node] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Shutting down connection manager...
21:23:38,255  INFO || - [Node] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Shutting down node engine...
21:23:38,274  INFO || - [NodeExtension] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Destroying node NodeExtension.
21:23:38,275  INFO || - [Node] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Hazelcast Shutdown is completed in 22 ms.
21:23:38,916  INFO || - [SimpleTestInClusterSupport] Time-limited test - Terminating instance factory in SimpleTestInClusterSupport.@AfterClass

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-mysql-8.0/31/

**Comment by olukas** [comment]
Failed again on _master_ with oracle-11:
- https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-mysql-8.2/5/testReport/com.hazelcast.mapstore.mysql/MySQLGenericMapStoreIT/___/
- https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-mysql-8.2/5/testReport/com.hazelcast.mapstore.mysql/MySQLGenericMapStoreTest/___/

**Comment by sumnerib** [comment]
Failed again on _master_ with oracle-11: https://jenkins.hazelcast.com/job/Hazelcast-master-mysql-8.0/32/testReport/junit/com.hazelcast.mapstore.mysql/

**Comment by TomaszGaweda** [comment]
Are there any other tests that rely on MapStore module? It will need to be reconfigured as well. 
@sumnerib @Patras3

**Comment by sumnerib** [comment]
@TomaszGaweda We have a GMS soak test: https://github.com/hazelcast/hazelcast-jet-ansible-tests/blob/f3395e6f64b666ccfadab8efc123c21940c0409f/generic-map-store-test/pom.xml#L95
