### ISSUE TITLE
com.hazelcast.test.starter.test.HazelcastVersionLocatorTest

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#25919]
_master_ (commit e9cbf6836fb2408580b3bd2275b96789c0e7f240)

Failed on Windows - OracleJDK11: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Windows-OracleJDK11/472/testReport/com.hazelcast.test.starter.test/HazelcastVersionLocatorTest/___/
<details><summary>Stacktrace:</summary>

```
java.lang.IllegalStateException: Maven dependency:get failed
	at com.hazelcast.internal.util.Preconditions.checkState(Preconditions.java:355)
	at com.hazelcast.test.starter.HazelcastVersionLocator$Artifact.downloadArtifact(HazelcastVersionLocator.java:129)
	at com.hazelcast.test.starter.HazelcastVersionLocator$Artifact.locateArtifact(HazelcastVersionLocator.java:107)
	at com.hazelcast.test.starter.HazelcastVersionLocator.lambda$locateVersion$0(HazelcastVersionLocator.java:176)
	at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:178)
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.base/java.util.stream.SpinedBuffer$1Splitr.forEachRemaining(SpinedBuffer.java:364)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.hazelcast.test.starter.HazelcastVersionLocator.locateVersion(HazelcastVersionLocator.java:176)
	at com.hazelcast.test.starter.test.HazelcastVersionLocatorTest.setUp(HazelcastVersionLocatorTest.java:53)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)

```
</details>

<details><summary>Standard output:</summary>

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-Windows-OracleJDK11/472/

**Comment by JackPGreen** [comment]
```
[INFO] Running com.hazelcast.test.starter.test.HazelcastVersionLocatorTest
[0.004s][warning][gc] -Xloggc is deprecated. Will use -Xlog:gc:C:\Jenkins\workspace\Hazelcast-master-Windows-OracleJDK11\maven_gc.log instead.
Could not rename log file 'C:\Jenkins\workspace\Hazelcast-master-Windows-OracleJDK11\maven_gc.log' to 'C:\Jenkins\workspace\Hazelcast-master-Windows-OracleJDK11\maven_gc.log.0' (Permission denied).
Java HotSpot(TM) 64-Bit Server VM warning: INFO: os::commit_memory(0x0000000640000000, 7516192768, 0) failed; error='The paging file is too small for this operation to complete' (DOS error/errno=1455)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 7516192768 bytes for Failed to commit area from 0x0000000640000000 to 0x0000000800000000 of length 7516192768.
# An error report file with more information is saved as:
# C:\Jenkins\workspace\Hazelcast-master-Windows-OracleJDK11\hazelcast\hs_err_pid30384.log
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.463 s <<< FAILURE! -- in com.hazelcast.test.starter.test.HazelcastVersionLocatorTest
[ERROR] com.hazelcast.test.starter.test.HazelcastVersionLocatorTest -- Time elapsed: 0.463 s <<< ERROR!
java.lang.IllegalStateException: Maven dependency:get failed
	at com.hazelcast.internal.util.Preconditions.checkState(Preconditions.java:355)
	at com.hazelcast.test.starter.HazelcastVersionLocator$Artifact.downloadArtifact(HazelcastVersionLocator.java:129)
	at com.hazelcast.test.starter.HazelcastVersionLocator$Artifact.locateArtifact(HazelcastVersionLocator.java:107)
	at com.hazelcast.test.starter.HazelcastVersionLocator.lambda$locateVersion$0(HazelcastVersionLocator.java:176)
	at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:178)
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.base/java.util.stream.SpinedBuffer$1Splitr.forEachRemaining(SpinedBuffer.java:364)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.hazelcast.test.starter.HazelcastVersionLocator.locateVersion(HazelcastVersionLocator.java:176)
	at com.hazelcast.test.starter.test.HazelcastVersionLocatorTest.setUp(HazelcastVersionLocatorTest.java:53)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
```

**Comment by olukas** [comment]
Failed again on _master_ with Windows - MicrosoftJDK11: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Windows-MicrosoftJDK11/91/testReport/com.hazelcast.test.starter.test/HazelcastVersionLocatorTest/___/

**Comment by JackPGreen** [comment]
Has come up at least twice today:

- https://github.com/hazelcast/hazelcast-mono/pull/268#issuecomment-1865490507
- https://github.com/hazelcast/hazelcast-mono/pull/258#issuecomment-1865966076
