### ISSUE TITLE
com.hazelcast.internal.cluster.impl.DemoteDataMemberTest.dataMember_shouldFailWhenLastDataMember

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#25950]
_master_ (commit a8c82b948e984f4b3c2cdc5c2c410c1d8f558b3f)

Failed on oracle-17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/307/testReport/com.hazelcast.internal.cluster.impl/DemoteDataMemberTest/dataMember_shouldFailWhenLastDataMember/
<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at com.hazelcast.internal.cluster.impl.DemoteDataMemberTest.dataMember_shouldFailWhenLastDataMember(DemoteDataMemberTest.java:258)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-sonar/307/

**Comment by sumnerib** [comment]
Failed again on _master_ with oracle-17 (sonar build): https://jenkins.hazelcast.com/job/Hazelcast-mono-OS-master-sonar/190/testReport/com.hazelcast.internal.cluster.impl/DemoteDataMemberTest/dataMember_shouldFailWhenLastDataMember/

**Comment by olukas** [comment]
Failed again on _master_ with oracle-17 (sonar build): https://jenkins.hazelcast.com/job/Hazelcast-mono-OS-master-sonar/214/testReport/com.hazelcast.internal.cluster.impl/DemoteDataMemberTest/dataMember_shouldFailWhenLastDataMember/

**Comment by AleksPeychev** [comment]
Failed again on _5.5.z_ with oracle-17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-sonar/797/testReport/junit/com.hazelcast.internal.cluster.impl/DemoteDataMemberTest/dataMember_shouldFailWhenLastDataMember/
