### ISSUE TITLE
com.hazelcast.internal.tpcengine.nio.NioAsyncSocket_RpcTest_Nightly crashed JVM

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#25951]
_master_ (commit a8c82b948e984f4b3c2cdc5c2c410c1d8f558b3f)

Failed on OpenJDK11 on arm64: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-OpenJDK11-arm64-nightly/38/console

<details><summary>Console output:</summary>

```
20:42:06 [INFO] Running com.hazelcast.internal.tpcengine.nio.NioAsyncSocket_RpcTest_Nightly
20:47:09 /bin/sh: line 1: 23761 Killed                  '/usr/lib/jvm/java-11-openjdk-11.0.19.0.7-1.amzn2.0.1.aarch64/bin/java' '-Xmx8G' '-Xms8G' '--add-exports' 'java.base/jdk.internal.ref=ALL-UNNAMED' '--add-opens' 'jdk.management/com.sun.management.internal=ALL-UNNAMED' '--add-opens' 'java.base/sun.nio.ch=ALL-UNNAMED' '--add-opens' 'java.base/java.lang=ALL-UNNAMED' '--add-opens' 'java.management/sun.management=ALL-UNNAMED' '--illegal-access=deny' '-Dhazelcast.phone.home.enabled=false' '-Dhazelcast.logging.type=none' '-Dhazelcast.test.use.network=false' '-Dlog4j.skipJansi=true' '-verbose:gc' '-Xlog:gc:maven_gc.log' '-XX:+HeapDumpOnOutOfMemoryError' '-XX:HeapDumpPath=/home/ec2-user/workspace/Hazelcast-master-OpenJDK11-arm64-nightly/test.hprof' '-jar' '/home/ec2-user/workspace/Hazelcast-master-OpenJDK11-arm64-nightly/hazelcast-tpc-engine/target/surefire/surefirebooter-20231108193651538_6.jar' '/home/ec2-user/workspace/Hazelcast-master-OpenJDK11-arm64-nightly/hazelcast-tpc-engine/target/surefire' '2023-11-08T19-36-45_557-jvmRun1' 'surefire-20231108193651538_4tmp' 'surefire_1-20231108193651538_5tmp'
...
20:47:09 [ERROR] Command was /bin/sh -c cd '/home/ec2-user/workspace/Hazelcast-master-OpenJDK11-arm64-nightly/hazelcast-tpc-engine' && '/usr/lib/jvm/java-11-openjdk-11.0.19.0.7-1.amzn2.0.1.aarch64/bin/java' '-Xmx8G' '-Xms8G' '--add-exports' 'java.base/jdk.internal.ref=ALL-UNNAMED' '--add-opens' 'jdk.management/com.sun.management.internal=ALL-UNNAMED' '--add-opens' 'java.base/sun.nio.ch=ALL-UNNAMED' '--add-opens' 'java.base/java.lang=ALL-UNNAMED' '--add-opens' 'java.management/sun.management=ALL-UNNAMED' '--illegal-access=deny' '-Dhazelcast.phone.home.enabled=false' '-Dhazelcast.logging.type=none' '-Dhazelcast.test.use.network=false' '-Dlog4j.skipJansi=true' '-verbose:gc' '-Xlog:gc:maven_gc.log' '-XX:+HeapDumpOnOutOfMemoryError' '-XX:HeapDumpPath=/home/ec2-user/workspace/Hazelcast-master-OpenJDK11-arm64-nightly/test.hprof' '-jar' '/home/ec2-user/workspace/Hazelcast-master-OpenJDK11-arm64-nightly/hazelcast-tpc-engine/target/surefire/surefirebooter-20231108193651538_6.jar' '/home/ec2-user/workspace/Hazelcast-master-OpenJDK11-arm64-nightly/hazelcast-tpc-engine/target/surefire' '2023-11-08T19-36-45_557-jvmRun1' 'surefire-20231108193651538_4tmp' 'surefire_1-20231108193651538_5tmp'
20:47:09 [ERROR] Error occurred in starting fork, check output in log
20:47:09 [ERROR] Process Exit Code: 137
20:47:09 [ERROR] Crashed tests:
20:47:09 [ERROR] com.hazelcast.internal.tpcengine.nio.NioAsyncSocket_RpcTest_Nightly
20:47:09 [ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
20:47:09 [ERROR] Command was /bin/sh -c cd '/home/ec2-user/workspace/Hazelcast-master-OpenJDK11-arm64-nightly/hazelcast-tpc-engine' && '/usr/lib/jvm/java-11-openjdk-11.0.19.0.7-1.amzn2.0.1.aarch64/bin/java' '-Xmx8G' '-Xms8G' '--add-exports' 'java.base/jdk.internal.ref=ALL-UNNAMED' '--add-opens' 'jdk.management/com.sun.management.internal=ALL-UNNAMED' '--add-opens' 'java.base/sun.nio.ch=ALL-UNNAMED' '--add-opens' 'java.base/java.lang=ALL-UNNAMED' '--add-opens' 'java.management/sun.management=ALL-UNNAMED' '--illegal-access=deny' '-Dhazelcast.phone.home.enabled=false' '-Dhazelcast.logging.type=none' '-Dhazelcast.test.use.network=false' '-Dlog4j.skipJansi=true' '-verbose:gc' '-Xlog:gc:maven_gc.log' '-XX:+HeapDumpOnOutOfMemoryError' '-XX:HeapDumpPath=/home/ec2-user/workspace/Hazelcast-master-OpenJDK11-arm64-nightly/test.hprof' '-jar' '/home/ec2-user/workspace/Hazelcast-master-OpenJDK11-arm64-nightly/hazelcast-tpc-engine/target/surefire/surefirebooter-20231108193651538_6.jar' '/home/ec2-user/workspace/Hazelcast-master-OpenJDK11-arm64-nightly/hazelcast-tpc-engine/target/surefire' '2023-11-08T19-36-45_557-jvmRun1' 'surefire-20231108193651538_4tmp' 'surefire_1-20231108193651538_5tmp'
20:47:09 [ERROR] Error occurred in starting fork, check output in log
20:47:09 [ERROR] Process Exit Code: 137
20:47:09 [ERROR] Crashed tests:
20:47:09 [ERROR] com.hazelcast.internal.tpcengine.nio.NioAsyncSocket_RpcTest_Nightly
20:47:09 [ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:643)
20:47:09 [ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:285)
20:47:09 [ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:250)
20:47:09 [ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1240)
20:47:09 [ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1089)
20:47:09 [ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:905)
20:47:09 [ERROR] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
20:47:09 [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
20:47:09 [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
20:47:09 [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
20:47:09 [ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
20:47:09 [ERROR] 	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:190)
20:47:09 [ERROR] 	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:186)
20:47:09 [ERROR] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
20:47:09 [ERROR] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
20:47:09 [ERROR] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
20:47:09 [ERROR] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
20:47:09 [ERROR] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
20:47:09 [ERROR] 	at java.base/java.lang.Thread.run(Thread.java:829)
```

</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-OpenJDK11-arm64-nightly/38/

**Comment by sumnerib** [comment]
Crashed again: https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK11-arm64-nightly/39/consoleFull

**Comment by olukas** [comment]
Closing the test failure - it doesn't seem to be related to `master` or the latest maintenance stream `5.5.z` and it hasn't fail in the last 3 months. Feel free to reopen test failure if it occurs on `master` or on the latest maintenance stream.
