### ISSUE TITLE
com.hazelcast.jet.elastic.impl.ElasticCatClientTest and com.hazelcast.jet.elastic.impl.ElasticSourcePTest

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#25955]
_master_ (commit 9301cde01ebec894a71922ee341aebe1c2b61829)

Failed on Windows - MicrosoftJDK11: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Windows-MicrosoftJDK11/91/testReport/com.hazelcast.jet.elastic.impl/

Following tests failed:
- `com.hazelcast.jet.elastic.impl.ElasticCatClientTest.shouldRetryOnShards`
- `com.hazelcast.jet.elastic.impl.ElasticCatClientTest.shards`
- `com.hazelcast.jet.elastic.impl.ElasticCatClientTest.shouldFailAfterFiveAttemptsShards`
- `com.hazelcast.jet.elastic.impl.ElasticSourcePTest.when_runProcessorWithCoLocation_then_useLocalNodeOnly`
- `com.hazelcast.jet.elastic.impl.ElasticSourcePTest.when_runProcessorWithCoLocation_thenSearchShardsWithPreference`
- `com.hazelcast.jet.elastic.impl.ElasticSourcePTest.when_runProcessorWithOptionsFn_then_shouldUseOptionsFnForScrollRequest`
- `com.hazelcast.jet.elastic.impl.ElasticSourcePTest.when_runProcessor_then_executeSearchRequestWithScroll`
- `com.hazelcast.jet.elastic.impl.ElasticSourcePTest.given_singleHit_when_runProcessor_then_produceSingleHit`
- `com.hazelcast.jet.elastic.impl.ElasticSourcePTest.when_runProcessorWithOptionsFn_then_shouldUseOptionsFnForSearchRequest`
- `com.hazelcast.jet.elastic.impl.ElasticSourcePTest.when_runProcessorWithParallelism_thenUseSlicingBasedOnGlobalValues`
- `com.hazelcast.jet.elastic.impl.ElasticSourcePTest.givenMultipleResults_when_runProcessor_then_useScrollIdInFollowupScrollRequest`
- `com.hazelcast.jet.elastic.impl.ElasticSourcePTest.when_runProcessorWithCoLocationAndSlicing_thenUseSlicingBasedOnLocalValues`

<details><summary>Stacktrace:</summary>

```
java.lang.IllegalStateException: Could not initialize plugin: interface org.mockito.plugins.MockMaker (alternate: null)
	at org.mockito.internal.configuration.plugins.PluginLoader$1.invoke(PluginLoader.java:84)
	at com.sun.proxy.$Proxy76.isTypeMockable(Unknown Source)
	at org.mockito.internal.util.MockUtil.typeMockabilityOf(MockUtil.java:78)
	at org.mockito.internal.util.MockCreationValidator.validateType(MockCreationValidator.java:22)
	at org.mockito.internal.creation.MockSettingsImpl.validatedSettings(MockSettingsImpl.java:274)
	at org.mockito.internal.creation.MockSettingsImpl.build(MockSettingsImpl.java:235)
	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:86)
	at org.mockito.Mockito.mock(Mockito.java:2101)
	at org.mockito.internal.configuration.MockAnnotationProcessor.processAnnotationForMock(MockAnnotationProcessor.java:79)
	at org.mockito.internal.configuration.MockAnnotationProcessor.process(MockAnnotationProcessor.java:28)
	at org.mockito.internal.configuration.MockAnnotationProcessor.process(MockAnnotationProcessor.java:25)
	at org.mockito.internal.configuration.IndependentAnnotationEngine.createMockFor(IndependentAnnotationEngine.java:44)
	at org.mockito.internal.configuration.IndependentAnnotationEngine.process(IndependentAnnotationEngine.java:72)
	at org.mockito.internal.configuration.InjectingAnnotationEngine.processIndependentAnnotations(InjectingAnnotationEngine.java:62)
	at org.mockito.internal.configuration.InjectingAnnotationEngine.process(InjectingAnnotationEngine.java:47)
	at org.mockito.MockitoAnnotations.openMocks(MockitoAnnotations.java:81)
	at org.mockito.internal.runners.DefaultInternalRunner$1$1.evaluate(DefaultInternalRunner.java:50)
	at org.mockito.internal.runners.DefaultInternalRunner$1.run(DefaultInternalRunner.java:100)
	at org.mockito.internal.runners.DefaultInternalRunner.run(DefaultInternalRunner.java:107)
	at org.mockito.internal.runners.StrictRunner.run(StrictRunner.java:42)
	at org.mockito.junit.MockitoJUnitRunner.run(MockitoJUnitRunner.java:163)
Caused by: java.lang.IllegalStateException: Failed to load interface org.mockito.plugins.MockMaker implementation declared in java.lang.CompoundEnumeration@3d62c6e6
	at org.mockito.internal.configuration.plugins.PluginInitializer.loadImpl(PluginInitializer.java:56)
	at org.mockito.internal.configuration.plugins.PluginLoader.loadPlugin(PluginLoader.java:65)
	at org.mockito.internal.configuration.plugins.PluginLoader.loadPlugin(PluginLoader.java:50)
	at org.mockito.internal.configuration.plugins.PluginRegistry.<init>(PluginRegistry.java:27)
	at org.mockito.internal.configuration.plugins.Plugins.<clinit>(Plugins.java:22)
	at org.mockito.internal.MockitoCore.<clinit>(MockitoCore.java:73)
	at org.mockito.Mockito.<clinit>(Mockito.java:1683)
	at com.hazelcast.jet.elastic.ElasticSinkBuilderTest.lambda$when_writeToFailingSink_then_shouldCloseClient$3a92cd9$1(ElasticSinkBuilderTest.java:46)
	at com.hazelcast.function.SupplierEx.get(SupplierEx.java:45)
	at com.hazelcast.jet.elastic.ElasticSinkBuilder.lambda$build$e4b6d868$1(ElasticSinkBuilder.java:208)
	at com.hazelcast.function.FunctionEx.apply(FunctionEx.java:49)
	at com.hazelcast.jet.impl.connector.WriteBufferedP.init(WriteBufferedP.java:62)
	at com.hazelcast.jet.impl.processor.ProcessorWrapper.init(ProcessorWrapper.java:67)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.lambda$init$2f647568$1(ProcessorTasklet.java:279)
	at com.hazelcast.jet.function.RunnableEx.run(RunnableEx.java:31)
	at com.hazelcast.jet.impl.util.Util.doWithClassLoader(Util.java:574)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.init(ProcessorTasklet.java:279)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$BlockingWorker.run(TaskletExecutionService.java:315)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.mockito.internal.configuration.plugins.PluginInitializer.loadImpl(PluginInitializer.java:51)
	... 22 more
Caused by: org.mockito.exceptions.base.MockitoInitializationException: 
Could not initialize inline Byte Buddy mock maker.

It appears as if your JDK does not supply a working agent attachment mechanism.
Java               : 11
JVM vendor name    : Microsoft
JVM vendor version : 11.0.14+9-LTS
JVM name           : OpenJDK 64-Bit Server VM
JVM version        : 11.0.14+9-LTS
JVM info           : mixed mode
OS name            : Windows Server 2016
OS version         : 10.0

	at org.mockito.internal.creation.bytebuddy.InlineDelegateByteBuddyMockMaker.<init>(InlineDelegateByteBuddyMockMaker.java:260)
	at org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.<init>(InlineByteBuddyMockMaker.java:23)
	... 24 more
Caused by: java.lang.IllegalStateException: Could not self-attach to current VM using external process
	at net.bytebuddy.agent.ByteBuddyAgent.installExternal(ByteBuddyAgent.java:706)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:636)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:616)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:568)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:545)
	at org.mockito.internal.creation.bytebuddy.InlineDelegateByteBuddyMockMaker.<clinit>(InlineDelegateByteBuddyMockMaker.java:133)
	... 25 more

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-Windows-MicrosoftJDK11/91/

**Comment by olukas** [comment]
Closing the test failure - it doesn't seem to be related to `master` or the latest maintenance stream `5.5.z` and it hasn't fail in the last 3 months. Feel free to reopen test failure if it occurs on `master` or on the latest maintenance stream.

**Comment by AleksPeychev** [comment]
Failed again on _5.5.z_ with MicrosoftJDK17 (Windows): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-Windows-MicrosoftJDK17/29/testReport/junit/com.hazelcast.jet.elastic.impl/ElasticSourcePTest/
