### ISSUE TITLE
com.hazelcast.jet.sql.impl.connector.map.index.SqlIndexSmallFetchSizeTest

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hazelcast#25995]
_master_ (commit fa1657f88a5a3cd1241fe20e79d94307c504c871)
Failed on Windows - MicrosoftJDK11: https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK11/92/testReport/junit/com.hazelcast.jet.sql.impl.connector.map.index/SqlIndexSmallFetchSizeTest/___/

<details><summary>Stacktrace:</summary>

```
org.junit.runners.model.TestTimedOutException: test timed out after 900 seconds
	at java.base@11.0.14/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@11.0.14/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
	at java.base@11.0.14/java.util.concurrent.FutureTask.awaitDone(FutureTask.java:444)
	at java.base@11.0.14/java.util.concurrent.FutureTask.get(FutureTask.java:203)
	at app//com.hazelcast.test.FailOnTimeoutStatement.getResult(FailOnTimeoutStatement.java:80)
	at app//com.hazelcast.test.FailOnTimeoutStatement.evaluate(FailOnTimeoutStatement.java:58)
	at app//com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:365)
	at app//org.assertj.core.api.SoftAssertionsStatement$1.evaluate(SoftAssertionsStatement.java:41)
	at app//com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37)
	at app//com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:104)
	at app//com.hazelcast.test.metrics.MetricsRule$1.evaluate(MetricsRule.java:63)
	at app//com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:53)
	at app//com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:32)
	at app//com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:41)
	at app//com.hazelcast.test.OverridePropertyRule$1.evaluate(OverridePropertyRule.java:66)
	at app//com.hazelcast.test.OverridePropertyRule$1.evaluate(OverridePropertyRule.java:66)
	at java.base@11.0.14/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base@11.0.14/java.lang.Thread.run(Thread.java:829)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-Windows-MicrosoftJDK11/92/

**Comment by k-jamroz** [comment]
Such NPE should be impossible - the code is generated by compiler. Similar happened also in https://github.com/hazelcast/hazelcast/issues/26289 (also OpenJ9)

**Comment by k-jamroz** [comment]
Also https://github.com/hazelcast/hazelcast/issues/26333

**Comment by sumnerib** [comment]
Failed again on _master_ with openj9-21: https://jenkins.hazelcast.com/job/Hazelcast-master-Openj9-21-nightly/28/testReport/junit/com.hazelcast.jet.sql.impl.connector.map.index/SqlIndexSmallFetchSizeTest/

**Comment by olukas** [comment]
Failed again on _master_ with openj9-21: https://jenkins.hazelcast.com/job/Hazelcast-master-Openj9-21-nightly/30/testReport/com.hazelcast.jet.sql.impl.connector.map.index/SqlIndexSmallFetchSizeTest/

**Comment by olukas** [comment]
Failed again on _master_ with openj9-21: https://jenkins.hazelcast.com/job/Hazelcast-master-Openj9-21-nightly/31/testReport/com.hazelcast.jet.sql.impl.connector.map.index/SqlIndexSmallFetchSizeTest/testOrderBy_indexType_SORTED__composite_false__field1_Integer__field2_Integer_/

**Comment by olukas** [comment]
Failed again on _master_ with openj9-21: https://jenkins.hazelcast.com/job/Hazelcast-master-Openj9-21-nightly/32/testReport/com.hazelcast.jet.sql.impl.connector.map.index/SqlIndexSmallFetchSizeTest/testDisjunctionOverlappingRange_indexType_SORTED__composite_false__field1_Integer__field2_Integer_/

**Comment by Patras3** [comment]
Failed again on _5.5.z_ with openj9-21: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-Openj9-21-nightly/17/testReport/com.hazelcast.jet.sql.impl.connector.map.index/SqlIndexSmallFetchSizeTest/

**Comment by JackPGreen** [comment]
> There seems to be related issue in OpenJ9: [eclipse-openj9/openj9#19369](https://github.com/eclipse-openj9/openj9/issues/19369)

I _think_ this is the same issue reported [here](https://github.com/hazelcast/hazelcast/issues/26327#issuecomment-2104426731).

_Hopefully_ fixed as part of https://github.com/hazelcast/DevOps/pull/285

Of note, this was _originally_ reported against Microsoft JDK which is unrelated.
