### ISSUE TITLE
'AttributePartitioningStrategy' does not work with Compact/Portable classes other than 'GenericRecord's [HZ-3837]

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hazelcast#25993]
**Describe the bug**
Given a map configuration with a `partition-attribute` config, when trying to load data into said map with keys whose types are explicitly serialized as Compact or Portable (or zero-config Compact), the member will throw an exception like the following:

```
Exception in thread "main" com.hazelcast.nio.serialization.HazelcastSerializationException: com.hazelcast.nio.serialization.HazelcastSerializationException: Failed to serialize 'com.qe.Vehicle'
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:600)
        at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:678)
        at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:737)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfInt.evaluateParallel(ForEachOps.java:188)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
        at java.base/java.util.stream.IntPipeline.forEach(IntPipeline.java:439)
        at java.base/java.util.stream.IntPipeline$Head.forEach(IntPipeline.java:596)
        at com.qe.App.main(App.java:99)
Caused by: com.hazelcast.nio.serialization.HazelcastSerializationException: Failed to serialize 'com.qe.Vehicle'
        at com.hazelcast.internal.serialization.impl.SerializationUtil.handleSerializeException(SerializationUtil.java:129)
        at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:241)
        at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:217)
        at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toData(AbstractSerializationService.java:202)
        at com.hazelcast.map.impl.proxy.MapProxySupport.toDataWithStrategy(MapProxySupport.java:1341)
        at com.hazelcast.map.impl.proxy.MapProxySupport.setInternal(MapProxySupport.java:595)
        at com.hazelcast.map.impl.proxy.MapProxyImpl.set(MapProxyImpl.java:251)
        at com.hazelcast.map.impl.proxy.MapProxyImpl.set(MapProxyImpl.java:241)
        at com.qe.App.lambda$0(App.java:106)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfInt.accept(ForEachOps.java:204)
        at java.base/java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104)
        at java.base/java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:699)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
        at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: com.hazelcast.core.HazelcastException: Cannot extract attributes from the key
        at com.hazelcast.partition.strategy.AttributePartitioningStrategy.getPartitionKey(AttributePartitioningStrategy.java:55)
        at com.hazelcast.internal.serialization.impl.AbstractSerializationService.calculatePartitionHash(AbstractSerializationService.java:490)
        at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:232)
        ... 18 more
```

**Expected behavior**
The partition key is able to be extracted by the `AttributePartitioningStrategy` and the entry can be put into the map.

**To Reproduce**

The issue can be reproduced by modifying and adding a test case to `com.hazelcast.partition.strategy.AttributePartitioningStrategyIntegrationTest`.

Modify the `beforeClass` method like:
```
    @BeforeClass
    public static void beforeClass() {
        Config config = smallInstanceConfig().setProperty(PARTITION_COUNT.getName(), "3");
        config.getMapConfig("test").getPartitioningAttributeConfigs()
                .add(new PartitioningAttributeConfig("org"));
        config.getMapConfig("test2").getPartitioningAttributeConfigs()
                .add(new PartitioningAttributeConfig("d"));

        config.getSerializationConfig()
                .getCompactSerializationConfig()
                .addSerializer(new FixedSizeFieldsDTOSerializer());

        initializeWithClient(3, config, null);
    }
```

... and add the following test method:
```
    @Test
    public void testCompactPojo() {
        double partitionAttrValue = 2.0;
        final IMap<FixedSizeFieldsDTO, Long> map = instance().getMap("test2");

        for (long i = 0; i < 100; i++) {
            map.put(new FixedSizeFieldsDTO((byte) 0, true, (short) 1,1, i, 1.0F, partitionAttrValue), i);
        }

        final HazelcastInstance owner = getOwner(partitionAttrValue);
        final List<HazelcastInstance> nonOwners = getNonOwners(owner);

        assertEquals(100, owner.getMap("test2").getLocalMapStats().getOwnedEntryCount());
        assertEquals(0, nonOwners.get(0).getMap("test2").getLocalMapStats().getOwnedEntryCount());
        assertEquals(0, nonOwners.get(1).getMap("test2").getLocalMapStats().getOwnedEntryCount());
    }
``` 

**Additional context**

Looks like the `AttributePartitioningStrategy` is expecting a `InternalGenericRecord` explicitly as part of the serialization path:  https://github.com/hazelcast/hazelcast/blob/fa1657f88a5a3cd1241fe20e79d94307c504c871/hazelcast/src/main/java/com/hazelcast/partition/strategy/AttributePartitioningStrategy.java#L48 

At this point, the object is still the user key type (i.e. a domain class). The existing test cases don't catch this because they explicitly use `GenericRecordBuilder` to generate the key objects

**Comment by sumnerib** [comment]
It looks like this behavior is expected based on the unit tests: https://github.com/hazelcast/hazelcast/blob/25cec84ecb9334abfeb9685f7c0e5c8ea227c433/hazelcast/src/test/java/com/hazelcast/partition/strategy/AttributePartitioningStrategyTest.java#L62

If so, then this behavior should be clearly documented here: https://docs.hazelcast.com/hazelcast/5.3/performance/data-affinity#attribute-based-partitioning-strategy
