### ISSUE TITLE
com.hazelcast.jet.sql_nightly.SqlSTSInnerEquiJoinFaultToleranceStressTest.(?) - Container startup failed for image confluentinc/cp-kafka:7.4.0)

### ISSUE THREAD

**Issue by Patras3** [hazelcast/hazelcast#26036]
_master_ (commit b1241aedfa9e0d7d96c8a1e6821954ede7a793d2)

Failed on OpenJDK17: https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK17-nightly-Esxi7/59/testReport/com.hazelcast.jet.sql_nightly/SqlSTSInnerEquiJoinFaultToleranceStressTest/___/

During this build, there was a timeout for other test, but from the logs looks like this issue is not connected with mentioned timeout.
<details><summary>Stacktrace:</summary>

```
org.testcontainers.containers.ContainerLaunchException: Container startup failed for image confluentinc/cp-kafka:7.4.0
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:362)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:333)
	at com.hazelcast.jet.kafka.impl.DockerizedKafkaTestSupport.createKafkaCluster0(DockerizedKafkaTestSupport.java:40)
	at com.hazelcast.jet.kafka.impl.KafkaTestSupport.createKafkaCluster(KafkaTestSupport.java:102)
	at com.hazelcast.jet.sql_nightly.SqlSTSInnerEquiJoinFaultToleranceStressTest.beforeClass(SqlSTSInnerEquiJoinFaultToleranceStressTest.java:114)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:41)
	at com.hazelcast.test.OverridePropertyRule$1.evaluate(OverridePropertyRule.java:66)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:347)
	... 9 more
Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:566)
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:357)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
	... 10 more
Caused by: java.lang.NullPointerException: containerId was not specified
	at java.base/java.util.Objects.requireNonNull(Objects.java:235)
	at org.testcontainers.shaded.com.github.dockerjava.core.command.InspectContainerCmdImpl.withContainerId(InspectContainerCmdImpl.java:30)
	at org.testcontainers.shaded.com.github.dockerjava.core.command.InspectContainerCmdImpl.<init>(InspectContainerCmdImpl.java:20)
	at org.testcontainers.shaded.com.github.dockerjava.core.DockerClientImpl.inspectContainerCmd(DockerClientImpl.java:400)
	at com.github.dockerjava.api.DockerClientDelegate.inspectContainerCmd(DockerClientDelegate.java:219)
	at com.github.dockerjava.api.DockerClientDelegate.inspectContainerCmd(DockerClientDelegate.java:219)
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:508)
	... 12 more

```
</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: stressTest[processingGuarantee:exactlyOnce, restartGraceful:false] in 0.001 seconds.

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-OpenJDK17-nightly-Esxi7/59/

**Comment by EugeneAbramchuk** [comment]
Failed again on _master_ with oracle-17 (little-endian): https://jenkins.hazelcast.com/job/Hazelcast-master-nightly-little-endian/82/testReport/com.hazelcast.jet.sql_nightly/SqlSTSInnerEquiJoinFaultToleranceStressTest/___/

**Comment by olukas** [comment]
Failed again on _5.5.0_ with oracle --version-by-pom: https://jenkins.hazelcast.com/view/Release/job/Hazelcast-5.releaseBranch-nightly/10/testReport/com.hazelcast.jet.sql_nightly/SqlSTSInnerEquiJoinFaultToleranceStressTest/___/

**Comment by olukas** [comment]
Failed again on _master_ with openjdk-17: https://jenkins.hazelcast.com/job/Hazelcast-master-ZuluJDK17-nightly/131/testReport/com.hazelcast.jet.sql_nightly/SqlSTSInnerEquiJoinFaultToleranceStressTest/___/

**Comment by AleksPeychev** [comment]
Failed again on _5.5.6_ with oracle --version-by-pom: https://jenkins.hazelcast.com/view/Release/job/Hazelcast-5.releaseBranch-nightly/23/testReport/junit/com.hazelcast.jet.sql_nightly/SqlSTSInnerEquiJoinFaultToleranceStressTest/___/
