### ISSUE TITLE
com.hazelcast.jet.sql.impl.connector.infoschema.MappingsTableTest.test_rows_security_enabled

### ISSUE THREAD

**Issue by Patras3** [hazelcast/hazelcast#26063]
_master_ (commit 02a156be4151ff173c81676fc444c2059bbedf21)

Failed on oracle-17: https://jenkins.hazelcast.com/job/Hazelcast-master-sonar/322/testReport/com.hazelcast.jet.sql.impl.connector.infoschema/MappingsTableTest/test_rows_security_enabled/
<details><summary>Stacktrace:</summary>

```
com.hazelcast.spi.exception.DistributedObjectDestroyedException: Proxy [hz:impl:mapService:__jet.executionRecords] was destroyed while being created. This may result in incomplete cleanup of resources.
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyRegistry.destroyProxy(ProxyRegistry.java:320)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyServiceImpl.destroyLocalDistributedObject(ProxyServiceImpl.java:189)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyServiceImpl.destroyDistributedObject(ProxyServiceImpl.java:177)
	at com.hazelcast.spi.impl.AbstractDistributedObject.destroy(AbstractDistributedObject.java:76)
	at com.hazelcast.jet.SimpleTestInClusterSupport.lambda$supportAfter$6(SimpleTestInClusterSupport.java:210)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at com.hazelcast.jet.SimpleTestInClusterSupport.supportAfter(SimpleTestInClusterSupport.java:210)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:381)
	at com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37)
	at com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:104)
	at com.hazelcast.test.metrics.MetricsRule$1.evaluate(MetricsRule.java:63)
	at com.hazelcast.test.HazelcastParallelClassRunner.access$101(HazelcastParallelClassRunner.java:52)
	at com.hazelcast.test.HazelcastParallelClassRunner$TestRunner.run(HazelcastParallelClassRunner.java:165)
	at java.base/java.lang.Thread.run(Thread.java:833)

```
</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: test_rows_dataconnection in 0.005 seconds.
BuildInfo right after test_rows_security_enabled(com.hazelcast.jet.sql.impl.connector.infoschema.MappingsTableTest): BuildInfo{version='5.4.0-SNAPSHOT', build='20231123', buildNumber=20231123, revision=02a156b, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'test_rows_security_enabled(com.hazelcast.jet.sql.impl.connector.infoschema.MappingsTableTest):'
03:52:20, accumulated pauses: 7 ms, max pause: 0 ms, pauses over 1000 ms: 0


No metrics recorded during the test

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-sonar/322/

**Comment by sumnerib** [comment]
Failed again on _master_ with openj9-11: https://jenkins.hazelcast.com/job/Hazelcast-master-Openj9-11/160/testReport/junit/com.hazelcast.jet.sql.impl.connector.infoschema/MappingsTableTest/test_rows_dataconnection/
