### ISSUE TITLE
com.hazelcast.jet.sql.impl.schema.SqlMappingTest.when_mapExistsButMappingIsNotCreated_then_suggestDdl [HZ-3941]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#26082]
_master_ (commit ed063c769f450eb3a9aac1b0463309e4ebd643b9)

Failed on Windows - OracleJDK11: https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-OracleJDK11/475/testReport/com.hazelcast.jet.sql.impl.schema/SqlMappingTest/when_mapExistsButMappingIsNotCreated_then_suggestDdl/
<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: 

Expecting throwable message:
  "Object 'map' not found, did you forget to CREATE MAPPING? If you want to use the IMap named 'map', execute this command first: CREATE OR REPLACE EXTERNAL MAPPING "hazelcast"."public"."map" EXTERNAL NAME "map"
TYPE "IMap"
OPTIONS (
  'keyFormat'='java',
  'keyJavaClass'='java.lang.Integer',
  'valueFormat'='java',
  'valueJavaClass'='java.lang.Integer'
)"
to contain:
  "CREATE OR REPLACE EXTERNAL MAPPING "hazelcast"."public"."map" EXTERNAL NAME "map"
TYPE "IMap"
OPTIONS (
  'keyFormat'='java',
  'keyJavaClass'='java.lang.Integer',
  'valueFormat'='java',
  'valueJavaClass'='java.lang.Integer'
)"
but did not.

Throwable that failed the check:

com.hazelcast.sql.HazelcastSqlException: Object 'map' not found, did you forget to CREATE MAPPING? If you want to use the IMap named 'map', execute this command first: CREATE OR REPLACE EXTERNAL MAPPING "hazelcast"."public"."map" EXTERNAL NAME "map"
TYPE "IMap"
OPTIONS (
  'keyFormat'='java',
  'keyJavaClass'='java.lang.Integer',
  'valueFormat'='java',
  'valueJavaClass'='java.lang.Integer'
)
	at com.hazelcast.sql.impl.client.SqlClientService.handleExecuteResponse(SqlClientService.java:308)
	at com.hazelcast.sql.impl.client.SqlClientService.execute(SqlClientService.java:146)
	at com.hazelcast.sql.SqlService.execute(SqlService.java:89)
	at com.hazelcast.jet.sql.impl.schema.SqlMappingTest.lambda$when_mapExistsButMappingIsNotCreated_then_suggestDdl$3(SqlMappingTest.java:85)
	at org.assertj.core.api.ThrowableAssert.catchThrowable(ThrowableAssert.java:63)
	at org.assertj.core.api.AssertionsForClassTypes.catchThrowable(AssertionsForClassTypes.java:892)
	at org.assertj.core.api.Assertions.catchThrowable(Assertions.java:1366)
	at org.assertj.core.api.Assertions.assertThatThrownBy(Assertions.java:1210)
	at com.hazelcast.jet.sql.impl.schema.SqlMappingTest.when_mapExistsButMappingIsNotCreated_then_suggestDdl(SqlMappingTest.java:85)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.Exception: com.hazelcast.sql.HazelcastSqlException: Object 'map' not found, did you forget to CREATE MAPPING? If you want to use the IMap named 'map', execute this command first: CREATE OR REPLACE EXTERNAL MAPPING "hazelcast"."public"."map" EXTERNAL NAME "map"
TYPE "IMap"
OPTIONS (
  'keyFormat'='java',
  'keyJavaClass'='java.lang.Integer',
  'valueFormat'='java',
  'valueJavaClass'='java.lang.Integer'
)
	at com.hazelcast.sql.impl.CoreQueryUtils.toPublicException(CoreQueryUtils.java:50)
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:227)
	at com.hazelcast.sql.impl.client.SqlExecuteMessageTask.call(SqlExecuteMessageTask.java:61)
	at com.hazelcast.client.impl.protocol.task.AbstractCallableMessageTask.processMessage(AbstractCallableMessageTask.java:35)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:169)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:132)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:111)
Caused by: com.hazelcast.sql.impl.QueryException: Object 'map' not found, did you forget to CREATE MAPPING? If you want to use the IMap named 'map', execute this command first: CREATE OR REPLACE EXTERNAL MAPPING "hazelcast"."public"."map" EXTERNAL NAME "map"
TYPE "IMap"
OPTIONS (
  'keyFormat'='java',
  'keyJavaClass'='java.lang.Integer',
  'valueFormat'='java',
  'valueJavaClass'='java.lang.Integer'
)
	at com.hazelcast.sql.impl.QueryException.error(QueryException.java:73)
	at com.hazelcast.jet.sql.impl.validate.HazelcastSqlValidator.newValidationError(HazelcastSqlValidator.java:570)
	at org.apache.calcite.sql.validate.IdentifierNamespace.resolveImpl(IdentifierNamespace.java:183)
	at org.apache.calcite.sql.validate.IdentifierNamespace.validateImpl(IdentifierNamespace.java:188)
	at org.apache.calcite.sql.validate.AbstractNamespace.validate(AbstractNamespace.java:88)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateNamespace(SqlValidatorImpl.java:1144)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateQuery(SqlValidatorImpl.java:1115)
	at com.hazelcast.jet.sql.impl.validate.HazelcastSqlValidator.validateQuery(HazelcastSqlValidator.java:204)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateFrom(SqlValidatorImpl.java:3456)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateFrom(SqlValidatorImpl.java:3435)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateSelect(SqlValidatorImpl.java:3792)
	at org.apache.calcite.sql.validate.SelectNamespace.validateImpl(SelectNamespace.java:61)
	at org.apache.calcite.sql.validate.AbstractNamespace.validate(AbstractNamespace.java:88)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateNamespace(SqlValidatorImpl.java:1144)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateQuery(SqlValidatorImpl.java:1115)
	at com.hazelcast.jet.sql.impl.validate.HazelcastSqlValidator.validateQuery(HazelcastSqlValidator.java:204)
	at org.apache.calcite.sql.SqlSelect.validate(SqlSelect.java:282)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateScopedExpression(SqlValidatorImpl.java:1090)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validate(SqlValidatorImpl.java:796)
	at com.hazelcast.jet.sql.impl.validate.HazelcastSqlValidator.validate(HazelcastSqlValidator.java:199)
	at com.hazelcast.jet.sql.impl.parse.QueryParser.parse0(QueryParser.java:89)
	at com.hazelcast.jet.sql.impl.parse.QueryParser.parse(QueryParser.java:60)
	at com.hazelcast.jet.sql.impl.OptimizerContext.parse(OptimizerContext.java:166)
	at com.hazelcast.jet.sql.impl.CalciteSqlOptimizer.prepare(CalciteSqlOptimizer.java:335)
	at com.hazelcast.sql.impl.SqlServiceImpl.prepare(SqlServiceImpl.java:286)
	at com.hazelcast.sql.impl.SqlServiceImpl.query0(SqlServiceImpl.java:265)
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:210)
	... 9 more
Caused by: org.apache.calcite.runtime.CalciteContextException: From line 1, column 15 to line 1, column 17: Object 'map' not found, did you forget to CREATE MAPPING?
	at jdk.internal.reflect.GeneratedConstructorAccessor190.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.apache.calcite.runtime.Resources$ExInstWithCause.ex(Resources.java:505)
	at org.apache.calcite.sql.SqlUtil.newContextException(SqlUtil.java:948)
	at org.apache.calcite.sql.SqlUtil.newContextException(SqlUtil.java:933)
	at com.hazelcast.jet.sql.impl.validate.HazelcastSqlValidator.newValidationError(HazelcastSqlValidator.java:563)
	... 34 more
Caused by: org.apache.calcite.sql.validate.SqlValidatorException: Object 'map' not found, did you forget to CREATE MAPPING?
	at jdk.internal.reflect.GeneratedConstructorAccessor189.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.apache.calcite.runtime.Resources$ExInstWithCause.ex(Resources.java:505)
	at org.apache.calcite.runtime.Resources$ExInst.ex(Resources.java:599)
	... 37 more

	at com.hazelcast.sql.impl.client.SqlClientService.handleExecuteResponse(SqlClientService.java:301)
	... 20 more

	at com.hazelcast.jet.sql.impl.schema.SqlMappingTest.when_mapExistsButMappingIsNotCreated_then_suggestDdl(SqlMappingTest.java:86)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)

```
</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: test_alias_dec_decimal_numeric in 0.005 seconds.
Started Running Test: when_mapExistsButMappingIsNotCreated_then_suggestDdl
21:24:55,558 DEBUG || - [SqlExecuteMessageTask] hz.SqlMappingTest_fervent_yonath.client-query.thread-1 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Client SQL error: com.hazelcast.sql.HazelcastSqlException: Object 'map' not found, did you forget to CREATE MAPPING? If you want to use the IMap named 'map', execute this command first: CREATE OR REPLACE EXTERNAL MAPPING "hazelcast"."public"."map" EXTERNAL NAME "map"
TYPE "IMap"
OPTIONS (
  'keyFormat'='java',
  'keyJavaClass'='java.lang.Integer',
  'valueFormat'='java',
  'valueJavaClass'='java.lang.Integer'
)
com.hazelcast.sql.HazelcastSqlException: Object 'map' not found, did you forget to CREATE MAPPING? If you want to use the IMap named 'map', execute this command first: CREATE OR REPLACE EXTERNAL MAPPING "hazelcast"."public"."map" EXTERNAL NAME "map"
TYPE "IMap"
OPTIONS (
  'keyFormat'='java',
  'keyJavaClass'='java.lang.Integer',
  'valueFormat'='java',
  'valueJavaClass'='java.lang.Integer'
)
	at com.hazelcast.sql.impl.CoreQueryUtils.toPublicException(CoreQueryUtils.java:50) ~[hazelcast-5.4.0-SNAPSHOT.jar:?]
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:227) ~[classes/:?]
	at com.hazelcast.sql.impl.client.SqlExecuteMessageTask.call(SqlExecuteMessageTask.java:61) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.client.impl.protocol.task.AbstractCallableMessageTask.processMessage(AbstractCallableMessageTask.java:35) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:169) [hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:132) [hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.base/java.lang.Thread.run(Thread.java:834) [?:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76) [hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:111) [hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
Caused by: com.hazelcast.sql.impl.QueryException: Object 'map' not found, did you forget to CREATE MAPPING? If you want to use the IMap named 'map', execute this command first: CREATE OR REPLACE EXTERNAL MAPPING "hazelcast"."public"."map" EXTERNAL NAME "map"
TYPE "IMap"
OPTIONS (
  'keyFormat'='java',
  'keyJavaClass'='java.lang.Integer',
  'valueFormat'='java',
  'valueJavaClass'='java.lang.Integer'
)
	at com.hazelcast.sql.impl.QueryException.error(QueryException.java:73) ~[hazelcast-5.4.0-SNAPSHOT.jar:?]
	at com.hazelcast.jet.sql.impl.validate.HazelcastSqlValidator.newValidationError(HazelcastSqlValidator.java:570) ~[classes/:?]
	at org.apache.calcite.sql.validate.IdentifierNamespace.resolveImpl(IdentifierNamespace.java:183) ~[calcite-core-1.35.0.jar:1.35.0]
	at org.apache.calcite.sql.validate.IdentifierNamespace.validateImpl(IdentifierNamespace.java:188) ~[calcite-core-1.35.0.jar:1.35.0]
	at org.apache.calcite.sql.validate.AbstractNamespace.validate(AbstractNamespace.java:88) ~[calcite-core-1.35.0.jar:1.35.0]
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateNamespace(SqlValidatorImpl.java:1144) ~[calcite-core-1.35.0.jar:1.35.0]
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateQuery(SqlValidatorImpl.java:1115) ~[calcite-core-1.35.0.jar:1.35.0]
	at com.hazelcast.jet.sql.impl.validate.HazelcastSqlValidator.validateQuery(HazelcastSqlValidator.java:204) ~[classes/:?]
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateFrom(SqlValidatorImpl.java:3456) ~[calcite-core-1.35.0.jar:1.35.0]
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateFrom(SqlValidatorImpl.java:3435) ~[calcite-core-1.35.0.jar:1.35.0]
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateSelect(SqlValidatorImpl.java:3792) ~[calcite-core-1.35.0.jar:1.35.0]
	at org.apache.calcite.sql.validate.SelectNamespace.validateImpl(SelectNamespace.java:61) ~[calcite-core-1.35.0.jar:1.35.0]
	at org.apache.calcite.sql.validate.AbstractNamespace.validate(AbstractNamespace.java:88) ~[calcite-core-1.35.0.jar:1.35.0]
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateNamespace(SqlValidatorImpl.java:1144) ~[calcite-core-1.35.0.jar:1.35.0]
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateQuery(SqlValidatorImpl.java:1115) ~[calcite-core-1.35.0.jar:1.35.0]
	at com.hazelcast.jet.sql.impl.validate.HazelcastSqlValidator.validateQuery(HazelcastSqlValidator.java:204) ~[classes/:?]
	at org.apache.calcite.sql.SqlSelect.validate(SqlSelect.java:282) ~[calcite-core-1.35.0.jar:1.35.0]
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateScopedExpression(SqlValidatorImpl.java:1090) ~[calcite-core-1.35.0.jar:1.35.0]
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validate(SqlValidatorImpl.java:796) ~[calcite-core-1.35.0.jar:1.35.0]
	at com.hazelcast.jet.sql.impl.validate.HazelcastSqlValidator.validate(HazelcastSqlValidator.java:199) ~[classes/:?]
	at com.hazelcast.jet.sql.impl.parse.QueryParser.parse0(QueryParser.java:89) ~[classes/:?]
	at com.hazelcast.jet.sql.impl.parse.QueryParser.parse(QueryParser.java:60) ~[classes/:?]
	at com.hazelcast.jet.sql.impl.OptimizerContext.parse(OptimizerContext.java:166) ~[classes/:?]
	at com.hazelcast.jet.sql.impl.CalciteSqlOptimizer.prepare(CalciteSqlOptimizer.java:335) ~[classes/:?]
	at com.hazelcast.sql.impl.SqlServiceImpl.prepare(SqlServiceImpl.java:286) ~[classes/:?]
	at com.hazelcast.sql.impl.SqlServiceImpl.query0(SqlServiceImpl.java:265) ~[classes/:?]
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:210) ~[classes/:?]
	... 9 more
Caused by: org.apache.calcite.runtime.CalciteContextException: From line 1, column 15 to line 1, column 17: Object 'map' not found, did you forget to CREATE MAPPING?
	at jdk.internal.reflect.GeneratedConstructorAccessor190.newInstance(Unknown Source) ~[?:?]
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at org.apache.calcite.runtime.Resources$ExInstWithCause.ex(Resources.java:505) ~[calcite-core-1.35.0.jar:1.35.0]
	at org.apache.calcite.sql.SqlUtil.newContextException(SqlUtil.java:948) ~[calcite-core-1.35.0.jar:1.35.0]
	at org.apache.calcite.sql.SqlUtil.newContextException(SqlUtil.java:933) ~[calcite-core-1.35.0.jar:1.35.0]
	at com.hazelcast.jet.sql.impl.validate.HazelcastSqlValidator.newValidationError(HazelcastSqlValidator.java:563) ~[classes/:?]
	at org.apache.calcite.sql.validate.IdentifierNamespace.resolveImpl(IdentifierNamespace.java:183) ~[calcite-core-1.35.0.jar:1.35.0]
	at org.apache.calcite.sql.validate.IdentifierNamespace.validateImpl(IdentifierNamespace.java:188) ~[calcite-core-1.35.0.jar:1.35.0]
	at org.apache.calcite.sql.validate.AbstractNamespace.validate(AbstractNamespace.java:88) ~[calcite-core-1.35.0.jar:1.35.0]
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateNamespace(SqlValidatorImpl.java:1144) ~[calcite-core-1.35.0.jar:1.35.0]
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateQuery(SqlValidatorImpl.java:1115) ~[calcite-core-1.35.0.jar:1.35.0]
	at com.hazelcast.jet.sql.impl.validate.HazelcastSqlValidator.validateQuery(HazelcastSqlValidator.java:204) ~[classes/:?]
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateFrom(SqlValidatorImpl.java:3456) ~[calcite-core-1.35.0.jar:1.35.0]
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateFrom(SqlValidatorImpl.java:3435) ~[calcite-core-1.35.0.jar:1.35.0]
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateSelect(SqlValidatorImpl.java:3792) ~[calcite-core-1.35.0.jar:1.35.0]
	at org.apache.calcite.sql.validate.SelectNamespace.validateImpl(SelectNamespace.java:61) ~[calcite-core-1.35.0.jar:1.35.0]
	at org.apache.calcite.sql.validate.AbstractNamespace.validate(AbstractNamespace.java:88) ~[calcite-core-1.35.0.jar:1.35.0]
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateNamespace(SqlValidatorImpl.java:1144) ~[calcite-core-1.35.0.jar:1.35.0]
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateQuery(SqlValidatorImpl.java:1115) ~[calcite-core-1.35.0.jar:1.35.0]
	at com.hazelcast.jet.sql.impl.validate.HazelcastSqlValidator.validateQuery(HazelcastSqlValidator.java:204) ~[classes/:?]
	at org.apache.calcite.sql.SqlSelect.validate(SqlSelect.java:282) ~[calcite-core-1.35.0.jar:1.35.0]
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateScopedExpression(SqlValidatorImpl.java:1090) ~[calcite-core-1.35.0.jar:1.35.0]
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validate(SqlValidatorImpl.java:796) ~[calcite-core-1.35.0.jar:1.35.0]
	at com.hazelcast.jet.sql.impl.validate.HazelcastSqlValidator.validate(HazelcastSqlValidator.java:199) ~[classes/:?]
	at com.hazelcast.jet.sql.impl.parse.QueryParser.parse0(QueryParser.java:89) ~[classes/:?]
	at com.hazelcast.jet.sql.impl.parse.QueryParser.parse(QueryParser.java:60) ~[classes/:?]
	at com.hazelcast.jet.sql.impl.OptimizerContext.parse(OptimizerContext.java:166) ~[classes/:?]
	at com.hazelcast.jet.sql.impl.CalciteSqlOptimizer.prepare(CalciteSqlOptimizer.java:335) ~[classes/:?]
	at com.hazelcast.sql.impl.SqlServiceImpl.prepare(SqlServiceImpl.java:286) ~[classes/:?]
	at com.hazelcast.sql.impl.SqlServiceImpl.query0(SqlServiceImpl.java:265) ~[classes/:?]
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:210) ~[classes/:?]
	... 9 more
Caused by: org.apache.calcite.sql.validate.SqlValidatorException: Object 'map' not found, did you forget to CREATE MAPPING?
	at jdk.internal.reflect.GeneratedConstructorAccessor189.newInstance(Unknown Source) ~[?:?]
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at org.apache.calcite.runtime.Resources$ExInstWithCause.ex(Resources.java:505) ~[calcite-core-1.35.0.jar:1.35.0]
	at org.apache.calcite.runtime.Resources$ExInst.ex(Resources.java:599) ~[calcite-core-1.35.0.jar:1.35.0]
	at org.apache.calcite.sql.SqlUtil.newContextException(SqlUtil.java:948) ~[calcite-core-1.35.0.jar:1.35.0]
	at org.apache.calcite.sql.SqlUtil.newContextException(SqlUtil.java:933) ~[calcite-core-1.35.0.jar:1.35.0]
	at com.hazelcast.jet.sql.impl.validate.HazelcastSqlValidator.newValidationError(HazelcastSqlValidator.java:563) ~[classes/:?]
	at org.apache.calcite.sql.validate.IdentifierNamespace.resolveImpl(IdentifierNamespace.java:183) ~[calcite-core-1.35.0.jar:1.35.0]
	at org.apache.calcite.sql.validate.IdentifierNamespace.validateImpl(IdentifierNamespace.java:188) ~[calcite-core-1.35.0.jar:1.35.0]
	at org.apache.calcite.sql.validate.AbstractNamespace.validate(AbstractNamespace.java:88) ~[calcite-core-1.35.0.jar:1.35.0]
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateNamespace(SqlValidatorImpl.java:1144) ~[calcite-core-1.35.0.jar:1.35.0]
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateQuery(SqlValidatorImpl.java:1115) ~[calcite-core-1.35.0.jar:1.35.0]
	at com.hazelcast.jet.sql.impl.validate.HazelcastSqlValidator.validateQuery(HazelcastSqlValidator.java:204) ~[classes/:?]
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateFrom(SqlValidatorImpl.java:3456) ~[calcite-core-1.35.0.jar:1.35.0]
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateFrom(SqlValidatorImpl.java:3435) ~[calcite-core-1.35.0.jar:1.35.0]
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateSelect(SqlValidatorImpl.java:3792) ~[calcite-core-1.35.0.jar:1.35.0]
	at org.apache.calcite.sql.validate.SelectNamespace.validateImpl(SelectNamespace.java:61) ~[calcite-core-1.35.0.jar:1.35.0]
	at org.apache.calcite.sql.validate.AbstractNamespace.validate(AbstractNamespace.java:88) ~[calcite-core-1.35.0.jar:1.35.0]
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateNamespace(SqlValidatorImpl.java:1144) ~[calcite-core-1.35.0.jar:1.35.0]
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateQuery(SqlValidatorImpl.java:1115) ~[calcite-core-1.35.0.jar:1.35.0]
	at com.hazelcast.jet.sql.impl.validate.HazelcastSqlValidator.validateQuery(HazelcastSqlValidator.java:204) ~[classes/:?]
	at org.apache.calcite.sql.SqlSelect.validate(SqlSelect.java:282) ~[calcite-core-1.35.0.jar:1.35.0]
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateScopedExpression(SqlValidatorImpl.java:1090) ~[calcite-core-1.35.0.jar:1.35.0]
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validate(SqlValidatorImpl.java:796) ~[calcite-core-1.35.0.jar:1.35.0]
	at com.hazelcast.jet.sql.impl.validate.HazelcastSqlValidator.validate(HazelcastSqlValidator.java:199) ~[classes/:?]
	at com.hazelcast.jet.sql.impl.parse.QueryParser.parse0(QueryParser.java:89) ~[classes/:?]
	at com.hazelcast.jet.sql.impl.parse.QueryParser.parse(QueryParser.java:60) ~[classes/:?]
	at com.hazelcast.jet.sql.impl.OptimizerContext.parse(OptimizerContext.java:166) ~[classes/:?]
	at com.hazelcast.jet.sql.impl.CalciteSqlOptimizer.prepare(CalciteSqlOptimizer.java:335) ~[classes/:?]
	at com.hazelcast.sql.impl.SqlServiceImpl.prepare(SqlServiceImpl.java:286) ~[classes/:?]
	at com.hazelcast.sql.impl.SqlServiceImpl.query0(SqlServiceImpl.java:265) ~[classes/:?]
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:210) ~[classes/:?]
	... 9 more
21:24:56,301  INFO |when_mapExistsButMappingIsNotCreated_then_suggestDdl| - [SqlTestSupport] Time-limited test - Removing 0 cached plans in SqlTestSupport.@After
21:24:56,302  INFO |when_mapExistsButMappingIsNotCreated_then_suggestDdl| - [SimpleTestInClusterSupport] Time-limited test - Ditching 0 jobs in SimpleTestInClusterSupport.@After: []
21:24:56,302  INFO |when_mapExistsButMappingIsNotCreated_then_suggestDdl| - [SimpleTestInClusterSupport] Time-limited test - Destroying 2 distributed objects in SimpleTestInClusterSupport.@After: [hz:impl:mapService/__sql.catalog, hz:impl:mapService/map]
21:24:56,503  INFO |when_mapExistsButMappingIsNotCreated_then_suggestDdl| - [HazelcastTestSupport] Time-limited test - Shutting down node factory as @After action
BuildInfo right after when_mapExistsButMappingIsNotCreated_then_suggestDdl(com.hazelcast.jet.sql.impl.schema.SqlMappingTest): BuildInfo{version='5.4.0-SNAPSHOT', build='20231127', buildNumber=20231127, revision=ed063c7, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'when_mapExistsButMappingIsNotCreated_then_suggestDdl(com.hazelcast.jet.sql.impl.schema.SqlMappingTest):'
21:24:55, accumulated pauses: 838 ms, max pause: 732 ms, pauses over 1000 ms: 0


No metrics recorded during the test

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-Windows-OracleJDK11/475/

**Comment by k-jamroz** [comment]
@shultseva line endings

**Comment by olukas** [comment]
Failed again on _master_ with Windows - MicrosoftJDK11: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Windows-MicrosoftJDK11/94/testReport/com.hazelcast.jet.sql.impl.schema/SqlMappingTest/when_mapExistsButMappingIsNotCreated_then_suggestDdl/
