### ISSUE TITLE
com.hazelcast.jet.sql.impl.connector.jdbc.mysql.MySQLJdbcFullScanJoinTest.thetaJoinByPrimaryKey_traverser_is_closed [HZ-4180]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#26104]
_master_ (commit 9807f546e5f90c182a58cd9479f61de7810f11f5)

Failed on oracle-11 (with mysql-5.7): https://jenkins.hazelcast.com/job/Hazelcast-master-mysql-5.7/34/testReport/com.hazelcast.jet.sql.impl.connector.jdbc.mysql/MySQLJdbcFullScanJoinTest/thetaJoinByPrimaryKey_traverser_is_closed/
<details><summary>Stacktrace:</summary>

```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.base@11.0.18/java.net.SocketInputStream.socketRead0(Native Method)
	at java.base@11.0.18/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
	at java.base@11.0.18/java.net.SocketInputStream.read(SocketInputStream.java:168)
	at java.base@11.0.18/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at java.base@11.0.18/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:478)
	at java.base@11.0.18/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472)
	at java.base@11.0.18/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160)
	at java.base@11.0.18/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
	at java.base@11.0.18/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1383)
	at java.base@11.0.18/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1296)
	at java.base@11.0.18/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:416)
	at java.base@11.0.18/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:388)
	at app//com.mysql.cj.protocol.ExportControlled.performTlsHandshake(ExportControlled.java:215)
	at app//com.mysql.cj.protocol.StandardSocketFactory.performTlsHandshake(StandardSocketFactory.java:192)
	at app//com.mysql.cj.protocol.a.NativeSocketConnection.performTlsHandshake(NativeSocketConnection.java:100)
	at app//com.mysql.cj.protocol.a.NativeProtocol.negotiateSSLConnection(NativeProtocol.java:371)
	at app//com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:208)
	at app//com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1428)
	at app//com.mysql.cj.NativeSession.connect(NativeSession.java:133)
	at app//com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:935)
	at app//com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:805)
	at app//com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:438)
	at app//com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241)
	at app//com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:189)
	at platform/java.sql@11.0.18/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at platform/java.sql@11.0.18/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at app//com.hazelcast.jet.sql.impl.connector.jdbc.JdbcSqlTestSupport.executeJdbc(JdbcSqlTestSupport.java:149)
	at app//com.hazelcast.jet.sql.impl.connector.jdbc.JdbcFullScanJoinTest.thetaJoinByPrimaryKey_traverser_is_closed(JdbcFullScanJoinTest.java:201)
	at java.base@11.0.18/java.lang.reflect.Method.invoke(Method.java:566)
	at app//com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at app//com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base@11.0.18/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base@11.0.18/java.lang.Thread.run(Thread.java:834)

```
</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: thetaJoin in 0.155 seconds.
Started Running Test: thetaJoinByPrimaryKey_traverser_is_closed
21:24:06,145 DEBUG || - [JobRepository] hz.MySQLJdbcFullScanJoinTest_gifted_khorana.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
21:24:11,141 DEBUG || - [JobRepository] hz.MySQLJdbcFullScanJoinTest_gifted_khorana.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
21:24:16,142 DEBUG || - [JobRepository] hz.MySQLJdbcFullScanJoinTest_gifted_khorana.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
21:24:21,143 DEBUG || - [JobRepository] hz.MySQLJdbcFullScanJoinTest_gifted_khorana.cached.thread-6 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
21:24:26,143 DEBUG || - [JobRepository] hz.MySQLJdbcFullScanJoinTest_gifted_khorana.cached.thread-10 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
21:24:31,143 DEBUG || - [JobRepository] hz.MySQLJdbcFullScanJoinTest_gifted_khorana.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
21:24:36,142 DEBUG || - [JobRepository] hz.MySQLJdbcFullScanJoinTest_gifted_khorana.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
21:24:41,143 DEBUG || - [JobRepository] hz.MySQLJdbcFullScanJoinTest_gifted_khorana.cached.thread-10 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
21:24:46,143 DEBUG || - [JobRepository] hz.MySQLJdbcFullScanJoinTest_gifted_khorana.cached.thread-10 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
21:24:51,144 DEBUG || - [JobRepository] hz.MySQLJdbcFullScanJoinTest_gifted_khorana.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
21:24:56,144 DEBUG || - [JobRepository] hz.MySQLJdbcFullScanJoinTest_gifted_khorana.cached.thread-9 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
21:25:01,145 DEBUG || - [JobRepository] hz.MySQLJdbcFullScanJoinTest_gifted_khorana.cached.thread-9 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
21:25:06,146 DEBUG || - [JobRepository] hz.MySQLJdbcFullScanJoinTest_gifted_khorana.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
21:25:11,146 DEBUG || - [JobRepository] hz.MySQLJdbcFullScanJoinTest_gifted_khorana.cached.thread-12 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
21:25:16,146 DEBUG || - [JobRepository] hz.MySQLJdbcFullScanJoinTest_gifted_khorana.cached.thread-10 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
21:25:21,146 DEBUG || - [JobRepository] hz.MySQLJdbcFullScanJoinTest_gifted_khorana.cached.thread-9 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
21:25:26,146 DEBUG || - [JobRepository] hz.MySQLJdbcFullScanJoinTest_gifted_khorana.cached.thread-12 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
21:25:31,147 DEBUG || - [JobRepository] hz.MySQLJdbcFullScanJoinTest_gifted_khorana.cached.thread-12 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
21:25:36,147 DEBUG || - [JobRepository] hz.MySQLJdbcFullScanJoinTest_gifted_khorana.cached.thread-11 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
21:25:41,147 DEBUG || - [JobRepository] hz.MySQLJdbcFullScanJoinTest_gifted_khorana.cached.thread-13 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
21:25:46,148 DEBUG || - [JobRepository] hz.MySQLJdbcFullScanJoinTest_gifted_khorana.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
21:25:51,148 DEBUG || - [JobRepository] hz.MySQLJdbcFullScanJoinTest_gifted_khorana.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
21:25:56,149 DEBUG || - [JobRepository] hz.MySQLJdbcFullScanJoinTest_gifted_khorana.cached.thread-9 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
21:26:01,149 DEBUG || - [JobRepository] hz.MySQLJdbcFullScanJoinTest_gifted_khorana.cached.thread-12 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
21:26:06,150 DEBUG || - [JobRepository] hz.MySQLJdbcFullScanJoinTest_gifted_khorana.cached.thread-6 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
21:26:11,149 DEBUG || - [JobRepository] hz.MySQLJdbcFullScanJoinTest_gifted_khorana.cached.thread-6 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
21:26:16,149 DEBUG || - [JobRepository] hz.MySQLJdbcFullScanJoinTest_gifted_khorana.cached.thread-6 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
21:26:21,150 DEBUG || - [JobRepository] hz.MySQLJdbcFullScanJoinTest_gifted_khorana.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
21:26:26,149 DEBUG || - [JobRepository] hz.MySQLJdbcFullScanJoinTest_gifted_khorana.cached.thread-6 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
21:26:31,149 DEBUG || - [JobRepository] hz.MySQLJdbcFullScanJoinTest_gifted_khorana.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
21:26:36,149 DEBUG || - [JobRepository] hz.MySQLJdbcFullScanJoinTest_gifted_khorana.cached.thread-6 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
21:26:41,149 DEBUG || - [JobRepository] hz.MySQLJdbcFullScanJoinTest_gifted_khorana.cached.thread-6 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
21:26:46,149 DEBUG || - [JobRepository] hz.MySQLJdbcFullScanJoinTest_gifted_khorana.cached.thread-13 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
21:26:51,149 DEBUG || - [JobRepository] hz.MySQLJdbcFullScanJoinTest_gifted_khorana.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
21:26:56,149 DEBUG || - [JobRepository] hz.MySQLJdbcFullScanJoinTest_gifted_khorana.cached.thread-9 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
21:27:01,149 DEBUG || - [JobRepository] hz.MySQLJdbcFullScanJoinTest_gifted_khorana.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
21:27:06,149 DEBUG || - [JobRepository] hz.MySQLJdbcFullScanJoinTest_gifted_khorana.cached.thread-9 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
21:27:11,149 DEBUG || - [JobRepository] hz.MySQLJdbcFullScanJoinTest_gifted_khorana.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
21:27:16,149 DEBUG || - [JobRepository] hz.MySQLJdbcFullScanJoinTest_gifted_khorana.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
21:27:21,149 DEBUG || - [JobRepository] hz.MySQLJdbcFullScanJoinTest_gifted_khorana.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
21:27:26,149 DEBUG || - [JobRepository] hz.MySQLJdbcFullScanJoinTest_gifted_khorana.cached.thread-11 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
21:27:31,150 DEBUG || - [JobRepository] hz.MySQLJdbcFullScanJoinTest_gifted_khorana.cached.thread-9 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
21:27:36,149 DEBUG || - [JobRepository] hz.MySQLJdbcFullScanJoinTest_gifted_khorana.cached.thread-6 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
21:27:41,149 DEBUG || - [JobRepository] hz.MySQLJdbcFullScanJoinTest_gifted_khorana.cached.thread-6 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
21:27:46,149 DEBUG || - [JobRepository] hz.MySQLJdbcFullScanJoinTest_gifted_khorana.cached.thread-1 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
21:27:51,151 DEBUG || - [JobRepository] hz.MySQLJdbcFullScanJoinTest_gifted_khorana.cached.thread-13 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
21:27:56,151 DEBUG || - [JobRepository] hz.MySQLJdbcFullScanJoinTest_gifted_khorana.cached.thread-13 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
21:28:01,151 DEBUG || - [JobRepository] hz.MySQLJdbcFullScanJoinTest_gifted_khorana.cached.thread-12 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
21:28:06,151 DEBUG || - [JobRepository] hz.MySQLJdbcFullScanJoinTest_gifted_khorana.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
21:28:11,151 DEBUG || - [JobRepository] hz.MySQLJdbcFullScanJoinTest_gifted_khorana.cached.thread-1 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
21:28:16,151 DEBUG || - [JobRepository] hz.MySQLJdbcFullScanJoinTest_gifted_khorana.cached.thread-1 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
21:28:21,151 DEBUG || - [JobRepository] hz.MySQLJdbcFullScanJoinTest_gifted_khorana.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
21:28:26,151 DEBUG || - [JobRepository] hz.MySQLJdbcFullScanJoinTest_gifted_khorana.cached.thread-11 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
21:28:31,151 DEBUG || - [JobRepository] hz.MySQLJdbcFullScanJoinTest_gifted_khorana.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
21:28:36,152 DEBUG || - [JobRepository] hz.MySQLJdbcFullScanJoinTest_gifted_khorana.cached.thread-9 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
21:28:41,152 DEBUG || - [JobRepository] hz.MySQLJdbcFullScanJoinTest_gifted_khorana.cached.thread-11 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
21:28:46,153 DEBUG || - [JobRepository] hz.MySQLJdbcFullScanJoinTest_gifted_khorana.cached.thread-13 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
21:28:51,154 DEBUG || - [JobRepository] hz.MySQLJdbcFullScanJoinTest_gifted_khorana.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
21:28:56,154 DEBUG || - [JobRepository] hz.MySQLJdbcFullScanJoinTest_gifted_khorana.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
21:29:01,154 DEBUG || - [JobRepository] hz.MySQLJdbcFullScanJoinTest_gifted_khorana.cached.thread-11 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
21:29:03,862  INFO |thetaJoinByPrimaryKey_traverser_is_closed| - [SqlTestSupport] Time-limited test - Removing 0 cached plans in SqlTestSupport.@After
21:29:03,862  INFO |thetaJoinByPrimaryKey_traverser_is_closed| - [SqlTestSupport] Time-limited test - Removing 0 cached plans in SqlTestSupport.@After
21:29:03,864  INFO |thetaJoinByPrimaryKey_traverser_is_closed| - [SimpleTestInClusterSupport] Time-limited test - Ditching 0 jobs in SimpleTestInClusterSupport.@After: []
21:29:03,864  INFO |thetaJoinByPrimaryKey_traverser_is_closed| - [SimpleTestInClusterSupport] Time-limited test - Destroying 1 distributed objects in SimpleTestInClusterSupport.@After: [hz:impl:mapService/__sql.catalog]
21:29:03,866  INFO |thetaJoinByPrimaryKey_traverser_is_closed| - [HazelcastTestSupport] Time-limited test - Shutting down node factory as @After action
BuildInfo right after thetaJoinByPrimaryKey_traverser_is_closed(com.hazelcast.jet.sql.impl.connector.jdbc.mysql.MySQLJdbcFullScanJoinTest): BuildInfo{version='5.4.0-SNAPSHOT', build='20231129', buildNumber=20231129, revision=9807f54, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'thetaJoinByPrimaryKey_traverser_is_closed(com.hazelcast.jet.sql.impl.connector.jdbc.mysql.MySQLJdbcFullScanJoinTest):'
21:24:00, accumulated pauses: 4972 ms, max pause: 10 ms, pauses over 1000 ms: 0
21:24:05, accumulated pauses: 4986 ms, max pause: 10 ms, pauses over 1000 ms: 0
21:24:10, accumulated pauses: 4975 ms, max pause: 10 ms, pauses over 1000 ms: 0
21:24:15, accumulated pauses: 4975 ms, max pause: 10 ms, pauses over 1000 ms: 0
21:24:20, accumulated pauses: 4975 ms, max pause: 10 ms, pauses over 1000 ms: 0
21:24:25, accumulated pauses: 4979 ms, max pause: 73 ms, pauses over 1000 ms: 0
21:24:30, accumulated pauses: 4974 ms, max pause: 10 ms, pauses over 1000 ms: 0
21:24:35, accumulated pauses: 4983 ms, max pause: 10 ms, pauses over 1000 ms: 0
21:24:40, accumulated pauses: 4975 ms, max pause: 10 ms, pauses over 1000 ms: 0
21:24:45, accumulated pauses: 4974 ms, max pause: 10 ms, pauses over 1000 ms: 0
21:24:50, accumulated pauses: 4975 ms, max pause: 10 ms, pauses over 1000 ms: 0
21:24:55, accumulated pauses: 4976 ms, max pause: 12 ms, pauses over 1000 ms: 0
21:25:00, accumulated pauses: 4975 ms, max pause: 11 ms, pauses over 1000 ms: 0
21:25:05, accumulated pauses: 4985 ms, max pause: 10 ms, pauses over 1000 ms: 0
21:25:10, accumulated pauses: 4968 ms, max pause: 13 ms, pauses over 1000 ms: 0
21:25:15, accumulated pauses: 4985 ms, max pause: 10 ms, pauses over 1000 ms: 0
21:25:20, accumulated pauses: 4974 ms, max pause: 10 ms, pauses over 1000 ms: 0
21:25:25, accumulated pauses: 4975 ms, max pause: 10 ms, pauses over 1000 ms: 0
21:25:30, accumulated pauses: 4984 ms, max pause: 10 ms, pauses over 1000 ms: 0
21:25:35, accumulated pauses: 4975 ms, max pause: 10 ms, pauses over 1000 ms: 0
21:25:40, accumulated pauses: 4972 ms, max pause: 10 ms, pauses over 1000 ms: 0
21:25:45, accumulated pauses: 4975 ms, max pause: 10 ms, pauses over 1000 ms: 0
21:25:50, accumulated pauses: 4982 ms, max pause: 10 ms, pauses over 1000 ms: 0
21:25:55, accumulated pauses: 4973 ms, max pause: 11 ms, pauses over 1000 ms: 0
21:26:00, accumulated pauses: 4981 ms, max pause: 10 ms, pauses over 1000 ms: 0
21:26:05, accumulated pauses: 4972 ms, max pause: 10 ms, pauses over 1000 ms: 0
21:26:10, accumulated pauses: 4978 ms, max pause: 10 ms, pauses over 1000 ms: 0
21:26:15, accumulated pauses: 4981 ms, max pause: 12 ms, pauses over 1000 ms: 0
21:26:20, accumulated pauses: 4972 ms, max pause: 10 ms, pauses over 1000 ms: 0
21:26:25, accumulated pauses: 4984 ms, max pause: 10 ms, pauses over 1000 ms: 0
21:26:30, accumulated pauses: 4975 ms, max pause: 10 ms, pauses over 1000 ms: 0
21:26:35, accumulated pauses: 4972 ms, max pause: 10 ms, pauses over 1000 ms: 0
21:26:40, accumulated pauses: 4983 ms, max pause: 10 ms, pauses over 1000 ms: 0
21:26:45, accumulated pauses: 4971 ms, max pause: 10 ms, pauses over 1000 ms: 0
21:26:50, accumulated pauses: 4981 ms, max pause: 10 ms, pauses over 1000 ms: 0
21:26:55, accumulated pauses: 4976 ms, max pause: 10 ms, pauses over 1000 ms: 0
21:27:00, accumulated pauses: 4972 ms, max pause: 10 ms, pauses over 1000 ms: 0
21:27:05, accumulated pauses: 4982 ms, max pause: 10 ms, pauses over 1000 ms: 0
21:27:10, accumulated pauses: 4976 ms, max pause: 10 ms, pauses over 1000 ms: 0
21:27:15, accumulated pauses: 4976 ms, max pause: 10 ms, pauses over 1000 ms: 0
21:27:20, accumulated pauses: 4980 ms, max pause: 10 ms, pauses over 1000 ms: 0
21:27:25, accumulated pauses: 4968 ms, max pause: 10 ms, pauses over 1000 ms: 0
21:27:30, accumulated pauses: 4982 ms, max pause: 10 ms, pauses over 1000 ms: 0
21:27:35, accumulated pauses: 4973 ms, max pause: 10 ms, pauses over 1000 ms: 0
21:27:40, accumulated pauses: 4975 ms, max pause: 10 ms, pauses over 1000 ms: 0
21:27:45, accumulated pauses: 4983 ms, max pause: 10 ms, pauses over 1000 ms: 0
21:27:50, accumulated pauses: 4975 ms, max pause: 10 ms, pauses over 1000 ms: 0
21:27:55, accumulated pauses: 4975 ms, max pause: 10 ms, pauses over 1000 ms: 0
21:28:00, accumulated pauses: 4974 ms, max pause: 10 ms, pauses over 1000 ms: 0
21:28:05, accumulated pauses: 4975 ms, max pause: 10 ms, pauses over 1000 ms: 0
21:28:10, accumulated pauses: 4986 ms, max pause: 10 ms, pauses over 1000 ms: 0
21:28:15, accumulated pauses: 4975 ms, max pause: 10 ms, pauses over 1000 ms: 0
21:28:20, accumulated pauses: 4974 ms, max pause: 10 ms, pauses over 1000 ms: 0
21:28:25, accumulated pauses: 4976 ms, max pause: 10 ms, pauses over 1000 ms: 0
21:28:30, accumulated pauses: 4975 ms, max pause: 10 ms, pauses over 1000 ms: 0
21:28:35, accumulated pauses: 4984 ms, max pause: 10 ms, pauses over 1000 ms: 0
21:28:40, accumulated pauses: 4973 ms, max pause: 10 ms, pauses over 1000 ms: 0
21:28:45, accumulated pauses: 4978 ms, max pause: 12 ms, pauses over 1000 ms: 0
21:28:50, accumulated pauses: 4972 ms, max pause: 10 ms, pauses over 1000 ms: 0
21:28:55, accumulated pauses: 4978 ms, max pause: 10 ms, pauses over 1000 ms: 0
21:29:00, accumulated pauses: 3840 ms, max pause: 2397 ms, pauses over 1000 ms: 1


No metrics recorded during the test

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-mysql-5.7/34/

**Comment by Patras3** [comment]
Failed again on _master_ with oracle-11: https://jenkins.hazelcast.com/job/Hazelcast-master-mysql-5.7/36/testReport/com.hazelcast.jet.sql.impl.connector.jdbc.mysql/MySQLJdbcFullScanJoinTest/thetaJoinByPrimaryKey_traverser_is_closed/

**Comment by olukas** [comment]
Failed again on _master_ with oracle-11: https://jenkins.hazelcast.com/job/Hazelcast-master-mysql-5.7/39/testReport/com.hazelcast.jet.sql.impl.connector.jdbc.mysql/MySQLJdbcFullScanJoinTest/thetaJoinByPrimaryKey_traverser_is_closed/

**Comment by sumnerib** [comment]
Failed again on _master_ with oracle-11: https://jenkins.hazelcast.com/job/Hazelcast-master-mysql-5.7/41/testReport/junit/com.hazelcast.jet.sql.impl.connector.jdbc.mysql/MySQLJdbcFullScanJoinTest/thetaJoinByPrimaryKey_traverser_is_closed/
