### ISSUE TITLE
com.hazelcast.jet.kafka.connect.KafkaConnectScalingIT.testScalingOfHazelcastDown

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#26115]
_master_ (commit 8085cd7e9ba5a422548d700e5681852ddd1da03d)

Failed on oracle-17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/329/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectScalingIT/testScalingOfHazelcastDown/
<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: 

Expected size: 12 but was: 10 in:
[0, 1, 2, 3, 4, 5, 6, 7, 8, 10]
	at com.hazelcast.jet.kafka.connect.KafkaConnectScalingIT.lambda$testScalingOfHazelcastDown$11(KafkaConnectScalingIT.java:337)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1183)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1288)
	at com.hazelcast.jet.kafka.connect.KafkaConnectScalingIT.testScalingOfHazelcastDown(KafkaConnectScalingIT.java:336)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-sonar/329/

**Comment by Patras3** [comment]
Failed again on _master_ with zing-17: https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK17-nightly/55/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectScalingIT/testScalingOfHazelcastDown/

**Comment by olukas** [comment]
Failed again on _master_ with oracle-17: https://jenkins.hazelcast.com/job/Hazelcast-master-sonar/346/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectScalingIT/testScalingOfHazelcastDown/

**Comment by olukas** [comment]
Failed again on _master_ with oracle-11 (little-endian): https://jenkins.hazelcast.com/job/Hazelcast-master-nightly-little-endian/59/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectScalingIT/testScalingOfHazelcastDown/

**Comment by sumnerib** [comment]
Failed again on _master_ with oracle-11 (force-offload): https://jenkins.hazelcast.com/job/Hazelcast-master-nightly-force-offload/82/testReport/junit/com.hazelcast.jet.kafka.connect/KafkaConnectScalingIT/testScalingOfHazelcastDown/

**Comment by Patras3** [comment]
Failed again on _master_ with ibm-11: https://jenkins.hazelcast.com/job/Hazelcast-master-Openj9-11-nightly/139/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectScalingIT/testScalingOfHazelcastDown/

**Comment by Patras3** [comment]
Failed again on _master_ with oracle-11 (force-offload): https://jenkins.hazelcast.com/job/Hazelcast-master-nightly-force-offload/84/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectScalingIT/testScalingOfHazelcastDown/

**Comment by Patras3** [comment]
Failed again on _master_ with Sonar build - oracle-17: https://jenkins.hazelcast.com/job/Hazelcast-master-sonar/386/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectScalingIT/testScalingOfHazelcastDown/

**Comment by olukas** [comment]
Failed again on _master_ with OracleJDK17 (sonar build): https://jenkins.hazelcast.com/job/Hazelcast-master-sonar/393/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectScalingIT/testScalingOfHazelcastDown/

**Comment by olukas** [comment]
Failed again on _master_ with oracle-17 (force-offload): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-nightly-force-offload/87/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectScalingIT/testScalingOfHazelcastDown/

**Comment by Patras3** [comment]
Failed again on _master_ with oracle-17 (force-offload): https://jenkins.hazelcast.com/job/Hazelcast-master-nightly-force-offload/90/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectScalingIT/testScalingOfHazelcastDown/

**Comment by olukas** [comment]
Failed again on _master_ with oracle-17 (force-offload): https://jenkins.hazelcast.com/job/Hazelcast-master-nightly-force-offload/91/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectScalingIT/testScalingOfHazelcastDown/

**Comment by sumnerib** [comment]
Failed again on _master_ with oracle-17 (sonar build): https://jenkins.hazelcast.com/job/Hazelcast-mono-OS-master-sonar/130/testReport/junit/com.hazelcast.jet.kafka.connect/KafkaConnectScalingIT/testScalingOfHazelcastUp/

**Comment by AleksPeychev** [comment]
Failed again on _master_ with oracle-17 (sonar build): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/471/testReport/junit/com.hazelcast.jet.kafka.connect/KafkaConnectScalingIT/testScalingOfHazelcastUp/

**Comment by sumnerib** [comment]
Failed again on _master_ with oracle-17 (sonar build): https://jenkins.hazelcast.com/job/Hazelcast-master-sonar/478/testReport/junit/com.hazelcast.jet.kafka.connect/KafkaConnectScalingIT/testScalingOfHazelcastUp/

**Comment by Patras3** [comment]
Failed again on _master_ with oracle-17 (sonar build): https://jenkins.hazelcast.com/job/Hazelcast-master-sonar/488/testReport/junit/com.hazelcast.jet.kafka.connect/KafkaConnectScalingIT/testScalingOfHazelcastUp/

**Comment by olukas** [comment]
Failed again on _master_ with oracle-17 (sonar build): https://jenkins.hazelcast.com/job/Hazelcast-master-sonar/534/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectScalingIT/testScalingOfHazelcastUp/

**Comment by olukas** [comment]
Failed again on _master_ with openj9-21: https://jenkins.hazelcast.com/job/Hazelcast-master-Openj9-21-nightly/31/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectScalingIT/testScalingOfHazelcastUp/

**Comment by olukas** [comment]
Failed again on _master_ with oracle-17 (sonar build): https://jenkins.hazelcast.com/job/Hazelcast-mono-OS-master-sonar/261/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectScalingIT/testScalingOfHazelcastDown/

**Comment by AleksPeychev** [comment]
Failed again on _master_ with oracle-17 (force-offload): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-nightly-force-offload/131/testReport/junit/com.hazelcast.jet.kafka.connect/KafkaConnectScalingIT/testScalingOfHazelcastUp/
