### ISSUE TITLE
com.hazelcast.jet.kafka.connect.KafkaConnectJdbcIntegrationTest.testDynamicReconfiguration

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hazelcast#26135]
_master_ (commit a404e908dc6af306bc6061f0a3b11491245453ba)
Failed on oracle-11 (force-offload): https://jenkins.hazelcast.com/job/Hazelcast-master-nightly-force-offload/77/testReport/junit/com.hazelcast.jet.kafka.connect/KafkaConnectJdbcIntegrationTest/testDynamicReconfiguration/

<details><summary>Stacktrace:</summary>

```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.base@11.0.18/java.net.SocketInputStream.socketRead0(Native Method)
	at java.base@11.0.18/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
	at java.base@11.0.18/java.net.SocketInputStream.read(SocketInputStream.java:168)
	at java.base@11.0.18/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at java.base@11.0.18/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:478)
	at java.base@11.0.18/sun.security.ssl.SSLSocketInputRecord.readFully(SSLSocketInputRecord.java:461)
	at java.base@11.0.18/sun.security.ssl.SSLSocketInputRecord.decodeInputRecord(SSLSocketInputRecord.java:243)
	at java.base@11.0.18/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:181)
	at java.base@11.0.18/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
	at java.base@11.0.18/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1386)
	at java.base@11.0.18/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1355)
	at java.base@11.0.18/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:977)
	at java.base@11.0.18/java.io.BufferedInputStream.read1(BufferedInputStream.java:290)
	at java.base@11.0.18/java.io.BufferedInputStream.read(BufferedInputStream.java:351)
	at java.base@11.0.18/sun.net.www.MeteredStream.read(MeteredStream.java:134)
	at java.base@11.0.18/java.io.FilterInputStream.read(FilterInputStream.java:133)
	at java.base@11.0.18/sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3525)
	at java.base@11.0.18/java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
	at java.base@11.0.18/java.io.BufferedInputStream.read1(BufferedInputStream.java:292)
	at java.base@11.0.18/java.io.BufferedInputStream.read(BufferedInputStream.java:351)
	at java.base@11.0.18/java.io.FilterInputStream.read(FilterInputStream.java:133)
	at java.base@11.0.18/java.io.PushbackInputStream.read(PushbackInputStream.java:183)
	at java.base@11.0.18/java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:243)
	at java.base@11.0.18/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:159)
	at java.base@11.0.18/java.util.zip.ZipInputStream.read(ZipInputStream.java:197)
	at java.base@11.0.18/java.io.FilterInputStream.read(FilterInputStream.java:133)
	at java.base@11.0.18/java.io.PushbackInputStream.read(PushbackInputStream.java:183)
	at java.base@11.0.18/java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:243)
	at java.base@11.0.18/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:159)
	at java.base@11.0.18/java.util.zip.ZipInputStream.read(ZipInputStream.java:197)
	at java.base@11.0.18/java.util.jar.JarInputStream.read(JarInputStream.java:207)
	at java.base@11.0.18/java.io.FilterInputStream.read(FilterInputStream.java:107)
	at app//com.hazelcast.internal.nio.IOUtil.drainTo(IOUtil.java:761)
	at app//com.hazelcast.jet.impl.JobRepository.readStreamAndPutCompressedToMap(JobRepository.java:336)
	at app//com.hazelcast.jet.impl.JobRepository.loadJarFromInputStream(JobRepository.java:322)
	at app//com.hazelcast.jet.impl.JobRepository.loadJarsInZip(JobRepository.java:305)
	at app//com.hazelcast.jet.impl.JobRepository.uploadJobResources(JobRepository.java:254)
	at app//com.hazelcast.jet.impl.AbstractJetInstance.uploadResources(AbstractJetInstance.java:381)
	at app//com.hazelcast.jet.impl.AbstractJetInstance.newJobInt(AbstractJetInstance.java:161)
	at app//com.hazelcast.jet.impl.AbstractJetInstance.newJobInt(AbstractJetInstance.java:146)
	at app//com.hazelcast.jet.impl.AbstractJetInstance.newJob(AbstractJetInstance.java:132)
	at app//com.hazelcast.jet.kafka.connect.KafkaConnectJdbcIntegrationTest.testDynamicReconfiguration(KafkaConnectJdbcIntegrationTest.java:277)
	at java.base@11.0.18/java.lang.reflect.Method.invoke(Method.java:566)
	at app//com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at app//com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base@11.0.18/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base@11.0.18/java.lang.Thread.run(Thread.java:834)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-nightly-force-offload/77/

**Comment by orcunc** [comment]
The test is experiencing a timeout issue during the jar upload to the cluster. 

My hypothesis is that the extended duration is primarily due to the execution time of SQL insert statements, leaving insufficient time for the jar upload to complete. The previously individual JDBC inserts have been optimized and converted to batch inserts through this pull request: 

https://github.com/hazelcast/hazelcast-mono/pull/571. 

Consequently, I am closing this issue for now. If the problem resurfaces, we can investigate whether there are additional contributing factors.
