### ISSUE TITLE
com.hazelcast.jet.kafka.connect.KafkaConnectJdbcIntegrationTest.testScaling_with_new_member

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hazelcast#26137]
_master_ (commit a404e908dc6af306bc6061f0a3b11491245453ba)
Failed on oracle-11 (little-endian): https://jenkins.hazelcast.com/job/Hazelcast-master-nightly-little-endian/55/testReport/junit/com.hazelcast.jet.kafka.connect/KafkaConnectJdbcIntegrationTest/testScaling_with_new_member/

<details><summary>Stacktrace:</summary>

```
java.lang.RuntimeException: 10 attempts to cancel the job failed, shut down the cluster
	at com.hazelcast.jet.core.JetTestSupport.ditchJob0(JetTestSupport.java:548)
	at com.hazelcast.jet.core.JetTestSupport.ditchJob(JetTestSupport.java:469)
	at com.hazelcast.jet.core.JetTestSupport.shutdownJobsAndGetLeakedClassLoaders(JetTestSupport.java:150)
	at com.hazelcast.jet.core.JetTestSupport.shutdownFactory(JetTestSupport.java:120)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:381)
	at com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37)
	at com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:104)
	at com.hazelcast.test.metrics.MetricsRule$1.evaluate(MetricsRule.java:63)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:53)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:32)
	at com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:41)
	at com.hazelcast.test.OverridePropertyRule$1.evaluate(OverridePropertyRule.java:66)
	at com.hazelcast.test.OverridePropertyRule$1.evaluate(OverridePropertyRule.java:66)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-nightly-little-endian/55/

**Comment by sumnerib** [comment]
Failed again on _master_ with OpenJDK17: https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK17-nightly-Esxi7/61/testReport/junit/com.hazelcast.jet.kafka.connect/KafkaConnectJdbcIntegrationTest/testScaling_with_new_member/

**Comment by sumnerib** [comment]
Failed again on _master_ with oracle-17: https://jenkins.hazelcast.com/job/Hazelcast-master-sonar/336/testReport/junit/com.hazelcast.jet.kafka.connect/KafkaConnectJdbcIntegrationTest/testScaling_with_new_member/

**Comment by Patras3** [comment]
Failed again on _master_ with openjdk-sts (openjdk-20): https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK-sts-nightly/59/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectJdbcIntegrationTest/testScaling_with_new_member/

**Comment by olukas** [comment]
Failed again on _master_ with openjdk-17: https://jenkins.hazelcast.com/job/Hazelcast-master-ZuluJDK17-nightly/96/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectJdbcIntegrationTest/testScaling_with_new_member/

**Comment by olukas** [comment]
Failed again on _master_ with oracle-17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/347/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectJdbcIntegrationTest/testScaling_with_new_member/

**Comment by olukas** [comment]
Failed again on _master_ with oracle-11 (little-endian): https://jenkins.hazelcast.com/job/Hazelcast-master-nightly-little-endian/59/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectJdbcIntegrationTest/testScaling_with_new_member/

**Comment by sumnerib** [comment]
Failed again on _master_ with oracle-11: https://jenkins.hazelcast.com/job/Hazelcast-master-OracleJDK11-nightly/982/testReport/junit/com.hazelcast.jet.kafka.connect/KafkaConnectJdbcIntegrationTest/testScaling_with_new_member/

**Comment by Patras3** [comment]
Failed again on _master_ with oracle-17: https://jenkins.hazelcast.com/job/Hazelcast-master-sonar/381/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectJdbcIntegrationTest/testScaling_with_new_member/

**Comment by orcunc** [comment]
Closed by https://github.com/hazelcast/hazelcast-mono/pull/571
