### ISSUE TITLE
com.hazelcast.jet.core.ProcessorsTest.aggregateByKey

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hazelcast#26142]
_master_ (commit febd03249036dd9fa35fa2abb3980b41d6291f42)
Failed on MacOS: https://jenkins.hazelcast.com/job/Hazelcast-master-MacOS-ZuluJDK11/301/testReport/junit/com.hazelcast.jet.core/ProcessorsTest/aggregateByKey/

<details><summary>Stacktrace:</summary>

```
com.hazelcast.spi.exception.DistributedObjectDestroyedException: Proxy [hz:impl:mapService:__jet.exportedSnapshotsCache] was destroyed while being created. This may result in incomplete cleanup of resources.
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyRegistry.destroyProxy(ProxyRegistry.java:320)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyServiceImpl.destroyLocalDistributedObject(ProxyServiceImpl.java:189)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyServiceImpl.destroyDistributedObject(ProxyServiceImpl.java:177)
	at com.hazelcast.spi.impl.AbstractDistributedObject.destroy(AbstractDistributedObject.java:76)
	at com.hazelcast.jet.SimpleTestInClusterSupport.lambda$supportAfter$6(SimpleTestInClusterSupport.java:210)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at com.hazelcast.jet.SimpleTestInClusterSupport.supportAfter(SimpleTestInClusterSupport.java:210)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:381)
	at com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37)
	at com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:104)
	at com.hazelcast.test.metrics.MetricsRule$1.evaluate(MetricsRule.java:63)
	at com.hazelcast.test.HazelcastParallelClassRunner.access$101(HazelcastParallelClassRunner.java:52)
	at com.hazelcast.test.HazelcastParallelClassRunner$TestRunner.run(HazelcastParallelClassRunner.java:165)
	at java.base/java.lang.Thread.run(Thread.java:829)

```
</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: filteringWithMapUsingServiceAsync in 0.005 seconds.
Hiccups measured while running test 'aggregateByKey(com.hazelcast.jet.core.ProcessorsTest):'
17:01:50, accumulated pauses: 493 ms, max pause: 5 ms, pauses over 1000 ms: 0

17:01:53.611051 Input-0: [a]
17:01:53.611070 Saving & restoring snapshot

No metrics recorded during the test

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-MacOS-ZuluJDK11/301/

**Comment by k-jamroz** [comment]
Looks the same like all other issues fixed by #26092
