### ISSUE TITLE
com.hazelcast.jet.sql.impl.connector.jdbc.oracle.OracleAllTypesSelectJdbcSqlConnectorTest.selectRowWithAllTypes

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hazelcast#26175]
_master_ (commit 868b5f544bb05c5a569db4cfeeaa6ab045dd73f6)
Failed on openjdk-17: https://jenkins.hazelcast.com/job/Hazelcast-master-ZuluJDK17-nightly/95/testReport/junit/com.hazelcast.jet.sql.impl.connector.jdbc.oracle/OracleAllTypesSelectJdbcSqlConnectorTest/selectRowWithAllTypes/

<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: 

Expecting actual:
  []
to contain exactly in any order:
  [Row{[2022-12-30(class=java.time.LocalDate)]}]
but could not find the following elements:
  [Row{[2022-12-30(class=java.time.LocalDate)]}]

	at com.hazelcast.jet.sql.SqlTestSupport.assertRowsAnyOrder(SqlTestSupport.java:407)
	at com.hazelcast.jet.sql.SqlTestSupport.assertRowsAnyOrder(SqlTestSupport.java:384)
	at com.hazelcast.jet.sql.SqlTestSupport.assertRowsAnyOrder(SqlTestSupport.java:195)
	at com.hazelcast.jet.sql.impl.connector.jdbc.AllTypesSelectJdbcSqlConnectorTest.selectRowWithAllTypes(AllTypesSelectJdbcSqlConnectorTest.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)

```
</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: resolveMappingType[type:DATE, mappingType:DATE, value:'2022-12-30', expected:2022-12-30] in 0.412 seconds.
Started Running Test: selectRowWithAllTypes[type:DATE, mappingType:DATE, value:'2022-12-30', expected:2022-12-30]
07:13:01,400 DEBUG |selectRowWithAllTypes[type:DATE, mappingType:DATE, value:'2022-12-30', expected:2022-12-30]| - [CalciteSqlOptimizer] selectRowWithAllTypes - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Before logical opt:
LogicalTableScan(table=[[hazelcast, public, mapping_o_09451872_dedc_40e0_a496_5549b035b188[projects=[$0]]]])

07:13:01,400 DEBUG |selectRowWithAllTypes[type:DATE, mappingType:DATE, value:'2022-12-30', expected:2022-12-30]| - [CalciteSqlOptimizer] selectRowWithAllTypes - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] After logical opt:
FullScanLogicalRel(table=[[hazelcast, public, mapping_o_09451872_dedc_40e0_a496_5549b035b188[projects=[$0]]]])

07:13:01,401 DEBUG |selectRowWithAllTypes[type:DATE, mappingType:DATE, value:'2022-12-30', expected:2022-12-30]| - [CalciteSqlOptimizer] selectRowWithAllTypes - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] After physical opt:
FullScanPhysicalRel(table=[[hazelcast, public, mapping_o_09451872_dedc_40e0_a496_5549b035b188[projects=[$0]]]], discriminator=[0])

07:13:01,403 DEBUG |selectRowWithAllTypes[type:DATE, mappingType:DATE, value:'2022-12-30', expected:2022-12-30]| - [LightMasterContext] selectRowWithAllTypes - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Start executing light job 0ae6-5048-0e96-0001, execution graph in DOT format:
digraph DAG {
	"Select([table_o_a1875432_c2e7_4c77_80a2_595bf1e6cd13])" [localParallelism=1];
	"ClientSink" [localParallelism=1];
	"Select([table_o_a1875432_c2e7_4c77_80a2_595bf1e6cd13])" -> "ClientSink" [label="distributed to [127.0.0.1]:5701-partitioned", queueSize=16];
}
HINT: You can use graphviz or http://viz-js.com to visualize the printed graph.
07:13:01,403 DEBUG |selectRowWithAllTypes[type:DATE, mappingType:DATE, value:'2022-12-30', expected:2022-12-30]| - [LightMasterContext] selectRowWithAllTypes - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Job config for 0ae6-5048-0e96-0001: JobConfig {name=null, processingGuarantee=NONE, snapshotIntervalMillis=10000, autoScaling=true, suspendOnFailure=false, splitBrainProtectionEnabled=false, enableMetrics=true, storeMetricsAfterJobCompletion=false, resourceConfigs={}, serializerConfigs={}, arguments={__sql.arguments=[], __sql.queryUnbounded=false, __sql.queryText=SELECT * FROM mapping_o_09451872_dedc_40e0_a496_5549b035b188}, classLoaderFactory=null, initialSnapshotName=null, maxProcessorAccumulatedRecords=-1, timeoutMillis=0}
07:13:01,403 DEBUG |selectRowWithAllTypes[type:DATE, mappingType:DATE, value:'2022-12-30', expected:2022-12-30]| - [LightMasterContext] selectRowWithAllTypes - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Building execution plan for 0ae6-5048-0e96-0001
07:13:01,404 DEBUG || - [LightMasterContext] hz.OracleAllTypesSelectJdbcSqlConnectorTest_unruffled_roentgen.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Built execution plans for 0ae6-5048-0e96-0001
07:13:01,404 DEBUG || - [InitExecutionOperation] hz.OracleAllTypesSelectJdbcSqlConnectorTest_unruffled_roentgen.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Initializing execution plan for job 0ae6-5048-0e96-0001, execution 0ae6-5048-0e96-0001 from [127.0.0.1]:5701
07:13:01,404 DEBUG || - [InitExecutionOperation] hz.OracleAllTypesSelectJdbcSqlConnectorTest_jovial_roentgen.generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] Initializing execution plan for job 0ae6-5048-0e96-0001, execution 0ae6-5048-0e96-0001 from [127.0.0.1]:5701
07:13:01,405 DEBUG || - [JobExecutionService] hz.OracleAllTypesSelectJdbcSqlConnectorTest_jovial_roentgen.cached.thread-9 - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] Execution plan for light job ID=0ae6-5048-0e96-0001, jobName='0ae6-5048-0e96-0001', executionId=0ae6-5048-0e96-0001 initialized, will start the execution
07:13:01,405 DEBUG || - [JobExecutionService] hz.OracleAllTypesSelectJdbcSqlConnectorTest_unruffled_roentgen.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Execution plan for light job ID=0ae6-5048-0e96-0001, jobName='0ae6-5048-0e96-0001', executionId=0ae6-5048-0e96-0001 initialized, will start the execution
07:13:01,415 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-9 - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] Completed execution of job '0ae6-5048-0e96-0001', execution 0ae6-5048-0e96-0001
07:13:01,415 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-9 - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] Execution of job '0ae6-5048-0e96-0001', execution 0ae6-5048-0e96-0001 completed
07:13:01,416 DEBUG || - [JobExecutionService] hz.OracleAllTypesSelectJdbcSqlConnectorTest_unruffled_roentgen.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Completed execution of job '0ae6-5048-0e96-0001', execution 0ae6-5048-0e96-0001
07:13:01,416 DEBUG || - [JobExecutionService] hz.OracleAllTypesSelectJdbcSqlConnectorTest_unruffled_roentgen.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Execution of job '0ae6-5048-0e96-0001', execution 0ae6-5048-0e96-0001 completed
07:13:01,419 DEBUG |selectRowWithAllTypes[type:DATE, mappingType:DATE, value:'2022-12-30', expected:2022-12-30]| - [CalciteSqlOptimizer] selectRowWithAllTypes - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Before logical opt:
LogicalCalc(expr#0=[{inputs}], expr#1=[?0], expr#2=[=($t0, $t1)], table_column=[$t0], $condition=[$t2])
  LogicalTableScan(table=[[hazelcast, public, mapping_o_09451872_dedc_40e0_a496_5549b035b188[projects=[$0]]]])

07:13:01,419 DEBUG |selectRowWithAllTypes[type:DATE, mappingType:DATE, value:'2022-12-30', expected:2022-12-30]| - [CalciteSqlOptimizer] selectRowWithAllTypes - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] After logical opt:
FullScanLogicalRel(table=[[hazelcast, public, mapping_o_09451872_dedc_40e0_a496_5549b035b188[projects=[$0], filter==($0, ?0)]]])

07:13:01,420 DEBUG |selectRowWithAllTypes[type:DATE, mappingType:DATE, value:'2022-12-30', expected:2022-12-30]| - [CalciteSqlOptimizer] selectRowWithAllTypes - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] After physical opt:
FullScanPhysicalRel(table=[[hazelcast, public, mapping_o_09451872_dedc_40e0_a496_5549b035b188[projects=[$0], filter==($0, ?0)]]], discriminator=[0])

07:13:01,422 DEBUG |selectRowWithAllTypes[type:DATE, mappingType:DATE, value:'2022-12-30', expected:2022-12-30]| - [LightMasterContext] selectRowWithAllTypes - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Start executing light job 0ae6-5048-0e97-0001, execution graph in DOT format:
digraph DAG {
	"Select([table_o_a1875432_c2e7_4c77_80a2_595bf1e6cd13])" [localParallelism=1];
	"ClientSink" [localParallelism=1];
	"Select([table_o_a1875432_c2e7_4c77_80a2_595bf1e6cd13])" -> "ClientSink" [label="distributed to [127.0.0.1]:5701-partitioned", queueSize=16];
}
HINT: You can use graphviz or http://viz-js.com to visualize the printed graph.
07:13:01,422 DEBUG |selectRowWithAllTypes[type:DATE, mappingType:DATE, value:'2022-12-30', expected:2022-12-30]| - [LightMasterContext] selectRowWithAllTypes - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Job config for 0ae6-5048-0e97-0001: JobConfig {name=null, processingGuarantee=NONE, snapshotIntervalMillis=10000, autoScaling=true, suspendOnFailure=false, splitBrainProtectionEnabled=false, enableMetrics=true, storeMetricsAfterJobCompletion=false, resourceConfigs={}, serializerConfigs={}, arguments={__sql.arguments=[2022-12-30], __sql.queryUnbounded=false, __sql.queryText=SELECT * FROM mapping_o_09451872_dedc_40e0_a496_5549b035b188 WHERE table_column = ?}, classLoaderFactory=null, initialSnapshotName=null, maxProcessorAccumulatedRecords=-1, timeoutMillis=0}
07:13:01,422 DEBUG |selectRowWithAllTypes[type:DATE, mappingType:DATE, value:'2022-12-30', expected:2022-12-30]| - [LightMasterContext] selectRowWithAllTypes - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Building execution plan for 0ae6-5048-0e97-0001
07:13:01,422 DEBUG || - [LightMasterContext] hz.OracleAllTypesSelectJdbcSqlConnectorTest_unruffled_roentgen.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Built execution plans for 0ae6-5048-0e97-0001
07:13:01,423 DEBUG || - [InitExecutionOperation] hz.OracleAllTypesSelectJdbcSqlConnectorTest_jovial_roentgen.generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] Initializing execution plan for job 0ae6-5048-0e97-0001, execution 0ae6-5048-0e97-0001 from [127.0.0.1]:5701
07:13:01,423 DEBUG || - [InitExecutionOperation] hz.OracleAllTypesSelectJdbcSqlConnectorTest_unruffled_roentgen.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Initializing execution plan for job 0ae6-5048-0e97-0001, execution 0ae6-5048-0e97-0001 from [127.0.0.1]:5701
07:13:01,423 DEBUG || - [JobExecutionService] hz.OracleAllTypesSelectJdbcSqlConnectorTest_jovial_roentgen.cached.thread-9 - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] Execution plan for light job ID=0ae6-5048-0e97-0001, jobName='0ae6-5048-0e97-0001', executionId=0ae6-5048-0e97-0001 initialized, will start the execution
07:13:01,424 DEBUG || - [JobExecutionService] hz.OracleAllTypesSelectJdbcSqlConnectorTest_unruffled_roentgen.cached.thread-6 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Execution plan for light job ID=0ae6-5048-0e97-0001, jobName='0ae6-5048-0e97-0001', executionId=0ae6-5048-0e97-0001 initialized, will start the execution
07:13:01,424 DEBUG || - [JobExecutionService] hz.OracleAllTypesSelectJdbcSqlConnectorTest_jovial_roentgen.cached.thread-3 - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] Completed execution of job '0ae6-5048-0e97-0001', execution 0ae6-5048-0e97-0001
07:13:01,424 DEBUG || - [JobExecutionService] hz.OracleAllTypesSelectJdbcSqlConnectorTest_jovial_roentgen.cached.thread-3 - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] Execution of job '0ae6-5048-0e97-0001', execution 0ae6-5048-0e97-0001 completed
07:13:01,432 DEBUG || - [JobExecutionService] hz.OracleAllTypesSelectJdbcSqlConnectorTest_unruffled_roentgen.cached.thread-6 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Completed execution of job '0ae6-5048-0e97-0001', execution 0ae6-5048-0e97-0001
07:13:01,432 DEBUG || - [JobExecutionService] hz.OracleAllTypesSelectJdbcSqlConnectorTest_unruffled_roentgen.cached.thread-6 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Execution of job '0ae6-5048-0e97-0001', execution 0ae6-5048-0e97-0001 completed
07:13:02,244  INFO |selectRowWithAllTypes[type:DATE, mappingType:DATE, value:'2022-12-30', expected:2022-12-30]| - [SqlTestSupport] Time-limited test - Removing 2 cached plans in SqlTestSupport.@After
07:13:02,244  INFO |selectRowWithAllTypes[type:DATE, mappingType:DATE, value:'2022-12-30', expected:2022-12-30]| - [SqlTestSupport] Time-limited test - Removing 0 cached plans in SqlTestSupport.@After
07:13:02,245  INFO |selectRowWithAllTypes[type:DATE, mappingType:DATE, value:'2022-12-30', expected:2022-12-30]| - [SimpleTestInClusterSupport] Time-limited test - Ditching 0 jobs in SimpleTestInClusterSupport.@After: []
07:13:02,245  INFO |selectRowWithAllTypes[type:DATE, mappingType:DATE, value:'2022-12-30', expected:2022-12-30]| - [SimpleTestInClusterSupport] Time-limited test - Destroying 3 distributed objects in SimpleTestInClusterSupport.@After: [hz:impl:mapService/__jet.results, hz:impl:mapService/__jet.records, hz:impl:mapService/__sql.catalog]
07:13:02,247 ERROR || - [EventServiceImpl] hz.OracleAllTypesSelectJdbcSqlConnectorTest_unruffled_roentgen.event-129 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] hz.OracleAllTypesSelectJdbcSqlConnectorTest_unruffled_roentgen.event-129 caught an exception while processing:com.hazelcast.spi.impl.eventservice.impl.LocalEventDispatcher@2cedef01
java.lang.UnsupportedOperationException: SQL catalog must never be cleared - MapEvent{entryEventType=CLEAR_ALL, member=Member [127.0.0.1]:5701 - 77422011-016c-49b5-b874-af081ff92626 this, name='__sql.catalog', numberOfEntriesAffected=1}
	at com.hazelcast.jet.sql.impl.schema.AbstractSchemaStorage$EntryListenerAdapter.mapCleared(AbstractSchemaStorage.java:74) ~[classes/:?]
	at com.hazelcast.map.impl.MapListenerAdaptors.lambda$static$12(MapListenerAdaptors.java:132) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.map.impl.InternalMapListenerAdapter.onEvent(InternalMapListenerAdapter.java:56) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.map.impl.InternalMapListenerAdapter.onEvent(InternalMapListenerAdapter.java:35) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.map.impl.event.MapEventPublishingService.callListener(MapEventPublishingService.java:172) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.map.impl.event.MapEventPublishingService.dispatchMapEventData(MapEventPublishingService.java:126) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.map.impl.event.MapEventPublishingService.dispatchEvent(MapEventPublishingService.java:87) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.map.impl.event.MapEventPublishingService.dispatchEvent(MapEventPublishingService.java:47) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.map.impl.MapService.dispatchEvent(MapService.java:134) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.map.impl.MapService.dispatchEvent(MapService.java:101) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.spi.impl.eventservice.impl.LocalEventDispatcher.run(LocalEventDispatcher.java:64) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.internal.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:245) [hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.internal.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:228) [hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
07:13:02,247  WARN || - [EventService] hz.OracleAllTypesSelectJdbcSqlConnectorTest_jovial_roentgen.event-130 - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] Error while logging processing event
java.lang.UnsupportedOperationException: SQL catalog must never be cleared - MapEvent{entryEventType=CLEAR_ALL, member=Member [127.0.0.1]:5701 - 77422011-016c-49b5-b874-af081ff92626, name='__sql.catalog', numberOfEntriesAffected=1}
	at com.hazelcast.jet.sql.impl.schema.AbstractSchemaStorage$EntryListenerAdapter.mapCleared(AbstractSchemaStorage.java:74) ~[classes/:?]
	at com.hazelcast.map.impl.MapListenerAdaptors.lambda$static$12(MapListenerAdaptors.java:132) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.map.impl.InternalMapListenerAdapter.onEvent(InternalMapListenerAdapter.java:56) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.map.impl.InternalMapListenerAdapter.onEvent(InternalMapListenerAdapter.java:35) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.map.impl.event.MapEventPublishingService.callListener(MapEventPublishingService.java:172) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.map.impl.event.MapEventPublishingService.dispatchMapEventData(MapEventPublishingService.java:126) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.map.impl.event.MapEventPublishingService.dispatchEvent(MapEventPublishingService.java:87) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.map.impl.event.MapEventPublishingService.dispatchEvent(MapEventPublishingService.java:47) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.map.impl.MapService.dispatchEvent(MapService.java:134) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.map.impl.MapService.dispatchEvent(MapService.java:101) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.spi.impl.eventservice.impl.EventProcessor.process(EventProcessor.java:63) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.spi.impl.eventservice.impl.RemoteEventProcessor.run(RemoteEventProcessor.java:48) [hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.internal.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:245) [hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.internal.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:228) [hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
07:13:02,447  INFO |selectRowWithAllTypes[type:DATE, mappingType:DATE, value:'2022-12-30', expected:2022-12-30]| - [HazelcastTestSupport] Time-limited test - Shutting down node factory as @After action
BuildInfo right after selectRowWithAllTypes[type:DATE, mappingType:DATE, value:'2022-12-30', expected:2022-12-30](com.hazelcast.jet.sql.impl.connector.jdbc.oracle.OracleAllTypesSelectJdbcSqlConnectorTest): BuildInfo{version='5.4.0-SNAPSHOT', build='20231208', buildNumber=20231208, revision=868b5f5, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'selectRowWithAllTypes[type:DATE, mappingType:DATE, value:'2022-12-30', expected:2022-12-30](com.hazelcast.jet.sql.impl.connector.jdbc.oracle.OracleAllTypesSelectJdbcSqlConnectorTest):'
07:13:00, accumulated pauses: 810 ms, max pause: 793 ms, pauses over 1000 ms: 0


No metrics recorded during the test

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-ZuluJDK17-nightly/95/

**Comment by Patras3** [comment]
Failed again on _master_ with zing-17: https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK17-nightly/55/testReport/com.hazelcast.jet.sql.impl.connector.jdbc.oracle/OracleAllTypesSelectJdbcSqlConnectorTest/selectRowWithAllTypes/

**Comment by orcunc** [comment]
Fixed by https://github.com/hazelcast/hazelcast-mono/pull/404
