### ISSUE TITLE
com.hazelcast.jet.sql.impl.connector.jdbc.oracle.OracleAllTypesInsertJdbcSqlConnectorTest.insertRowWithAllTypes

### ISSUE THREAD

**Issue by Patras3** [hazelcast/hazelcast#26177]
_master_ (commit 015461c8dc513a0d8c4fd795204c0a1a28d261f5)

Failed on zing-17: https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK17-nightly/55/testReport/com.hazelcast.jet.sql.impl.connector.jdbc.oracle/OracleAllTypesInsertJdbcSqlConnectorTest/insertRowWithAllTypes/
<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: 

Expecting actual:
  [Row{[0(class=java.lang.Integer), 2022-12-30(class=java.sql.Date)]},
    Row{[1(class=java.lang.Integer), 2022-12-30(class=java.sql.Date)]}]
to contain exactly in any order:
  [Row{[0(class=java.lang.Integer), 2022-12-30(class=java.sql.Date)]},
    Row{[1(class=java.lang.Integer), 2022-12-30(class=java.sql.Date)]}]
elements not found:
  [Row{[0(class=java.lang.Integer), 2022-12-30(class=java.sql.Date)]},
    Row{[1(class=java.lang.Integer), 2022-12-30(class=java.sql.Date)]}]
and elements not expected:
  [Row{[0(class=java.lang.Integer), 2022-12-30(class=java.sql.Date)]},
    Row{[1(class=java.lang.Integer), 2022-12-30(class=java.sql.Date)]}]

	at com.hazelcast.jet.sql.impl.connector.jdbc.JdbcSqlTestSupport.assertJdbcRowsAnyOrder(JdbcSqlTestSupport.java:251)
	at com.hazelcast.jet.sql.impl.connector.jdbc.AllTypesInsertJdbcSqlConnectorTest.insertRowWithAllTypes(AllTypesInsertJdbcSqlConnectorTest.java:110)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:891)

```
</details>

<details><summary>Standard output:</summary>

```
22:06:23,382 DEBUG |insertRowWithAllTypes[type:DATE, mappingType:DATE, sqlValue:'2022-12-30', javaValue:2022-12-30, jdbcValue:12/30/22, 12:00 AM]| - [CalciteSqlOptimizer] insertRowWithAllTypes - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Before logical opt:
LogicalTableInsert(table=[[hazelcast, public, mapping_o_603a69db_90fc_45d7_b1a3_e6bfebc321ea[projects=[$0, $1]]]], operation=[INSERT], flattened=[false])
  LogicalValues(tuples=[[{ 0, 2022-12-30 }]])

22:06:23,383 DEBUG |insertRowWithAllTypes[type:DATE, mappingType:DATE, sqlValue:'2022-12-30', javaValue:2022-12-30, jdbcValue:12/30/22, 12:00 AM]| - [CalciteSqlOptimizer] insertRowWithAllTypes - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] After logical opt:
InsertLogicalRel(table=[[hazelcast, public, mapping_o_603a69db_90fc_45d7_b1a3_e6bfebc321ea[projects=[$0, $1]]]], operation=[INSERT], flattened=[false])
  ValuesLogicalRel(values=[{expressions=[[ConstantExpression{type=QueryDataType {family=INTEGER}, value=0}, ConstantExpression{type=QueryDataType {family=DATE}, value=2022-12-30}]]}])

22:06:23,384 DEBUG |insertRowWithAllTypes[type:DATE, mappingType:DATE, sqlValue:'2022-12-30', javaValue:2022-12-30, jdbcValue:12/30/22, 12:00 AM]| - [CalciteSqlOptimizer] insertRowWithAllTypes - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] After physical opt:
InsertPhysicalRel(table=[[hazelcast, public, mapping_o_603a69db_90fc_45d7_b1a3_e6bfebc321ea[projects=[$0, $1]]]], operation=[INSERT], flattened=[false])
  ValuesPhysicalRel(values=[{expressions=[[ConstantExpression{type=QueryDataType {family=INTEGER}, value=0}, ConstantExpression{type=QueryDataType {family=DATE}, value=2022-12-30}]]}])

22:06:23,385 DEBUG |insertRowWithAllTypes[type:DATE, mappingType:DATE, sqlValue:'2022-12-30', javaValue:2022-12-30, jdbcValue:12/30/22, 12:00 AM]| - [LightMasterContext] insertRowWithAllTypes - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Start executing light job 0ae7-1cc4-674c-0001, execution graph in DOT format:
digraph DAG {
	"Values" [localParallelism=1];
	"Insert([table_o_cd12e465_9d9f_4ebf_8557_6567110f0ee1])" [localParallelism=1];
	"Values" -> "Insert([table_o_cd12e465_9d9f_4ebf_8557_6567110f0ee1])" [queueSize=16];
}
HINT: You can use graphviz or http://viz-js.com to visualize the printed graph.
22:06:23,385 DEBUG |insertRowWithAllTypes[type:DATE, mappingType:DATE, sqlValue:'2022-12-30', javaValue:2022-12-30, jdbcValue:12/30/22, 12:00 AM]| - [LightMasterContext] insertRowWithAllTypes - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Job config for 0ae7-1cc4-674c-0001: JobConfig {name=null, processingGuarantee=NONE, snapshotIntervalMillis=10000, autoScaling=true, suspendOnFailure=false, splitBrainProtectionEnabled=false, enableMetrics=true, storeMetricsAfterJobCompletion=false, resourceConfigs={}, serializerConfigs={}, arguments={__sql.arguments=[], __sql.queryUnbounded=false, __sql.queryText=INSERT INTO mapping_o_603a69db_90fc_45d7_b1a3_e6bfebc321ea VALUES(0, '2022-12-30')}, classLoaderFactory=null, initialSnapshotName=null, maxProcessorAccumulatedRecords=-1, timeoutMillis=0}
22:06:23,385 DEBUG |insertRowWithAllTypes[type:DATE, mappingType:DATE, sqlValue:'2022-12-30', javaValue:2022-12-30, jdbcValue:12/30/22, 12:00 AM]| - [LightMasterContext] insertRowWithAllTypes - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Building execution plan for 0ae7-1cc4-674c-0001
22:06:23,386 DEBUG || - [LightMasterContext] hz.OracleAllTypesInsertJdbcSqlConnectorTest_optimistic_fermat.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Built execution plans for 0ae7-1cc4-674c-0001
22:06:23,386 DEBUG || - [InitExecutionOperation] hz.OracleAllTypesInsertJdbcSqlConnectorTest_optimistic_fermat.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Initializing execution plan for job 0ae7-1cc4-674c-0001, execution 0ae7-1cc4-674c-0001 from [127.0.0.1]:5701
22:06:23,386 DEBUG || - [JobExecutionService] hz.OracleAllTypesInsertJdbcSqlConnectorTest_optimistic_fermat.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Execution plan for light job ID=0ae7-1cc4-674c-0001, jobName='0ae7-1cc4-674c-0001', executionId=0ae7-1cc4-674c-0001 initialized, will start the execution
22:06:23,386 DEBUG || - [InitExecutionOperation] hz.OracleAllTypesInsertJdbcSqlConnectorTest_musing_fermat.generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] Initializing execution plan for job 0ae7-1cc4-674c-0001, execution 0ae7-1cc4-674c-0001 from [127.0.0.1]:5701
22:06:23,387 DEBUG || - [WriteJdbcP] hz.OracleAllTypesInsertJdbcSqlConnectorTest_optimistic_fermat.jet.blocking.thread-1 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] [0ae7-1cc4-674c-0001/Insert([table_o_cd12e465_9d9f_4ebf_8557_6567110f0ee1])#0] Actual pool size used: 1
22:06:23,387 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-7 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Completed execution of job '0ae7-1cc4-674c-0001', execution 0ae7-1cc4-674c-0001
22:06:23,387 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-7 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Execution of job '0ae7-1cc4-674c-0001', execution 0ae7-1cc4-674c-0001 completed
22:06:23,387 DEBUG || - [JobExecutionService] hz.OracleAllTypesInsertJdbcSqlConnectorTest_musing_fermat.cached.thread-7 - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] Execution plan for light job ID=0ae7-1cc4-674c-0001, jobName='0ae7-1cc4-674c-0001', executionId=0ae7-1cc4-674c-0001 initialized, will start the execution
22:06:23,388 DEBUG || - [WriteJdbcP] hz.OracleAllTypesInsertJdbcSqlConnectorTest_musing_fermat.jet.blocking.thread-0 - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] [0ae7-1cc4-674c-0001/Insert([table_o_cd12e465_9d9f_4ebf_8557_6567110f0ee1])#1] Actual pool size used: 1
22:06:23,395 DEBUG || - [WriteJdbcP] hz.OracleAllTypesInsertJdbcSqlConnectorTest_musing_fermat.jet.blocking.thread-0 - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] [0ae7-1cc4-674c-0001/Insert([table_o_cd12e465_9d9f_4ebf_8557_6567110f0ee1])#1] release null
22:06:23,395 DEBUG || - [JobExecutionService] hz.OracleAllTypesInsertJdbcSqlConnectorTest_musing_fermat.cached.thread-7 - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] Completed execution of job '0ae7-1cc4-674c-0001', execution 0ae7-1cc4-674c-0001
22:06:23,396 DEBUG || - [JobExecutionService] hz.OracleAllTypesInsertJdbcSqlConnectorTest_musing_fermat.cached.thread-7 - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] Execution of job '0ae7-1cc4-674c-0001', execution 0ae7-1cc4-674c-0001 completed
22:06:23,398 DEBUG |insertRowWithAllTypes[type:DATE, mappingType:DATE, sqlValue:'2022-12-30', javaValue:2022-12-30, jdbcValue:12/30/22, 12:00 AM]| - [CalciteSqlOptimizer] insertRowWithAllTypes - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Before logical opt:
LogicalTableInsert(table=[[hazelcast, public, mapping_o_603a69db_90fc_45d7_b1a3_e6bfebc321ea[projects=[$0, $1]]]], operation=[INSERT], flattened=[false])
  LogicalCalc(expr#0=[{inputs}], expr#1=[1], expr#2=[?0], id=[$t1], table_column=[$t2])
    LogicalValues(tuples=[[{ 0 }]])

22:06:23,399 DEBUG |insertRowWithAllTypes[type:DATE, mappingType:DATE, sqlValue:'2022-12-30', javaValue:2022-12-30, jdbcValue:12/30/22, 12:00 AM]| - [CalciteSqlOptimizer] insertRowWithAllTypes - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] After logical opt:
InsertLogicalRel(table=[[hazelcast, public, mapping_o_603a69db_90fc_45d7_b1a3_e6bfebc321ea[projects=[$0, $1]]]], operation=[INSERT], flattened=[false])
  ValuesLogicalRel(values=[{projection=[ConstantExpression{type=QueryDataType {family=INTEGER}, value=1}, ParameterExpression{index=0}], values=[{expressions=[[ConstantExpression{type=QueryDataType {family=INTEGER}, value=0}]]}]}])

22:06:23,399 DEBUG |insertRowWithAllTypes[type:DATE, mappingType:DATE, sqlValue:'2022-12-30', javaValue:2022-12-30, jdbcValue:12/30/22, 12:00 AM]| - [CalciteSqlOptimizer] insertRowWithAllTypes - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] After physical opt:
InsertPhysicalRel(table=[[hazelcast, public, mapping_o_603a69db_90fc_45d7_b1a3_e6bfebc321ea[projects=[$0, $1]]]], operation=[INSERT], flattened=[false])
  ValuesPhysicalRel(values=[{projection=[ConstantExpression{type=QueryDataType {family=INTEGER}, value=1}, ParameterExpression{index=0}], values=[{expressions=[[ConstantExpression{type=QueryDataType {family=INTEGER}, value=0}]]}]}])

22:06:23,400 DEBUG |insertRowWithAllTypes[type:DATE, mappingType:DATE, sqlValue:'2022-12-30', javaValue:2022-12-30, jdbcValue:12/30/22, 12:00 AM]| - [LightMasterContext] insertRowWithAllTypes - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Start executing light job 0ae7-1cc4-674d-0001, execution graph in DOT format:
digraph DAG {
	"Values" [localParallelism=1];
	"Insert([table_o_cd12e465_9d9f_4ebf_8557_6567110f0ee1])" [localParallelism=1];
	"Values" -> "Insert([table_o_cd12e465_9d9f_4ebf_8557_6567110f0ee1])" [queueSize=16];
}
HINT: You can use graphviz or http://viz-js.com to visualize the printed graph.
22:06:23,400 DEBUG |insertRowWithAllTypes[type:DATE, mappingType:DATE, sqlValue:'2022-12-30', javaValue:2022-12-30, jdbcValue:12/30/22, 12:00 AM]| - [LightMasterContext] insertRowWithAllTypes - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Job config for 0ae7-1cc4-674d-0001: JobConfig {name=null, processingGuarantee=NONE, snapshotIntervalMillis=10000, autoScaling=true, suspendOnFailure=false, splitBrainProtectionEnabled=false, enableMetrics=true, storeMetricsAfterJobCompletion=false, resourceConfigs={}, serializerConfigs={}, arguments={__sql.arguments=[2022-12-30], __sql.queryUnbounded=false, __sql.queryText=INSERT INTO mapping_o_603a69db_90fc_45d7_b1a3_e6bfebc321ea VALUES(1, ?)}, classLoaderFactory=null, initialSnapshotName=null, maxProcessorAccumulatedRecords=-1, timeoutMillis=0}
22:06:23,400 DEBUG |insertRowWithAllTypes[type:DATE, mappingType:DATE, sqlValue:'2022-12-30', javaValue:2022-12-30, jdbcValue:12/30/22, 12:00 AM]| - [LightMasterContext] insertRowWithAllTypes - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Building execution plan for 0ae7-1cc4-674d-0001
22:06:23,400 DEBUG || - [LightMasterContext] hz.OracleAllTypesInsertJdbcSqlConnectorTest_optimistic_fermat.cached.thread-9 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Built execution plans for 0ae7-1cc4-674d-0001
22:06:23,401 DEBUG || - [InitExecutionOperation] hz.OracleAllTypesInsertJdbcSqlConnectorTest_optimistic_fermat.cached.thread-9 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Initializing execution plan for job 0ae7-1cc4-674d-0001, execution 0ae7-1cc4-674d-0001 from [127.0.0.1]:5701
22:06:23,401 DEBUG || - [JobExecutionService] hz.OracleAllTypesInsertJdbcSqlConnectorTest_optimistic_fermat.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Execution plan for light job ID=0ae7-1cc4-674d-0001, jobName='0ae7-1cc4-674d-0001', executionId=0ae7-1cc4-674d-0001 initialized, will start the execution
22:06:23,401 DEBUG || - [InitExecutionOperation] hz.OracleAllTypesInsertJdbcSqlConnectorTest_musing_fermat.generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] Initializing execution plan for job 0ae7-1cc4-674d-0001, execution 0ae7-1cc4-674d-0001 from [127.0.0.1]:5701
22:06:23,401 DEBUG || - [WriteJdbcP] hz.OracleAllTypesInsertJdbcSqlConnectorTest_optimistic_fermat.jet.blocking.thread-1 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] [0ae7-1cc4-674d-0001/Insert([table_o_cd12e465_9d9f_4ebf_8557_6567110f0ee1])#0] Actual pool size used: 1
22:06:23,402 DEBUG || - [JobExecutionService] hz.OracleAllTypesInsertJdbcSqlConnectorTest_optimistic_fermat.cached.thread-6 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Completed execution of job '0ae7-1cc4-674d-0001', execution 0ae7-1cc4-674d-0001
22:06:23,402 DEBUG || - [JobExecutionService] hz.OracleAllTypesInsertJdbcSqlConnectorTest_optimistic_fermat.cached.thread-6 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Execution of job '0ae7-1cc4-674d-0001', execution 0ae7-1cc4-674d-0001 completed
22:06:23,402 DEBUG || - [JobExecutionService] hz.OracleAllTypesInsertJdbcSqlConnectorTest_musing_fermat.cached.thread-7 - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] Execution plan for light job ID=0ae7-1cc4-674d-0001, jobName='0ae7-1cc4-674d-0001', executionId=0ae7-1cc4-674d-0001 initialized, will start the execution
22:06:23,402 DEBUG || - [WriteJdbcP] hz.OracleAllTypesInsertJdbcSqlConnectorTest_musing_fermat.jet.blocking.thread-1 - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] [0ae7-1cc4-674d-0001/Insert([table_o_cd12e465_9d9f_4ebf_8557_6567110f0ee1])#1] Actual pool size used: 1
22:06:23,404 DEBUG || - [WriteJdbcP] hz.OracleAllTypesInsertJdbcSqlConnectorTest_musing_fermat.jet.blocking.thread-1 - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] [0ae7-1cc4-674d-0001/Insert([table_o_cd12e465_9d9f_4ebf_8557_6567110f0ee1])#1] release null
22:06:23,404 DEBUG || - [JobExecutionService] hz.OracleAllTypesInsertJdbcSqlConnectorTest_musing_fermat.cached.thread-7 - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] Completed execution of job '0ae7-1cc4-674d-0001', execution 0ae7-1cc4-674d-0001
22:06:23,404 DEBUG || - [JobExecutionService] hz.OracleAllTypesInsertJdbcSqlConnectorTest_musing_fermat.cached.thread-7 - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] Execution of job '0ae7-1cc4-674d-0001', execution 0ae7-1cc4-674d-0001 completed
22:06:23,497  INFO |insertRowWithAllTypes[type:DATE, mappingType:DATE, sqlValue:'2022-12-30', javaValue:2022-12-30, jdbcValue:12/30/22, 12:00 AM]| - [SqlTestSupport] Time-limited test - Removing 2 cached plans in SqlTestSupport.@After
22:06:23,497  INFO |insertRowWithAllTypes[type:DATE, mappingType:DATE, sqlValue:'2022-12-30', javaValue:2022-12-30, jdbcValue:12/30/22, 12:00 AM]| - [SqlTestSupport] Time-limited test - Removing 0 cached plans in SqlTestSupport.@After
22:06:23,497  INFO |insertRowWithAllTypes[type:DATE, mappingType:DATE, sqlValue:'2022-12-30', javaValue:2022-12-30, jdbcValue:12/30/22, 12:00 AM]| - [SimpleTestInClusterSupport] Time-limited test - Ditching 0 jobs in SimpleTestInClusterSupport.@After: []
22:06:23,497  INFO |insertRowWithAllTypes[type:DATE, mappingType:DATE, sqlValue:'2022-12-30', javaValue:2022-12-30, jdbcValue:12/30/22, 12:00 AM]| - [SimpleTestInClusterSupport] Time-limited test - Destroying 1 distributed objects in SimpleTestInClusterSupport.@After: [hz:impl:mapService/__sql.catalog]
22:06:23,499  INFO |insertRowWithAllTypes[type:DATE, mappingType:DATE, sqlValue:'2022-12-30', javaValue:2022-12-30, jdbcValue:12/30/22, 12:00 AM]| - [HazelcastTestSupport] Time-limited test - Shutting down node factory as @After action
BuildInfo right after insertRowWithAllTypes[type:DATE, mappingType:DATE, sqlValue:'2022-12-30', javaValue:2022-12-30, jdbcValue:12/30/22, 12:00 AM](com.hazelcast.jet.sql.impl.connector.jdbc.oracle.OracleAllTypesInsertJdbcSqlConnectorTest): BuildInfo{version='5.4.0-SNAPSHOT', build='20231208', buildNumber=20231208, revision=015461c, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'insertRowWithAllTypes[type:DATE, mappingType:DATE, sqlValue:'2022-12-30', javaValue:2022-12-30, jdbcValue:12/30/22, 12:00 AM](com.hazelcast.jet.sql.impl.connector.jdbc.oracle.OracleAllTypesInsertJdbcSqlConnectorTest):'
22:06:20, accumulated pauses: 3467 ms, max pause: 10 ms, pauses over 1000 ms: 0

22:06:23,499  WARN || - [EventService] hz.OracleAllTypesInsertJdbcSqlConnectorTest_musing_fermat.event-99 - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] Error while logging processing event
java.lang.UnsupportedOperationException: SQL catalog must never be cleared - MapEvent{entryEventType=CLEAR_ALL, member=Member [127.0.0.1]:5701 - a6c0d8e0-1ea1-499b-9e7d-8b818fc22bd4, name='__sql.catalog', numberOfEntriesAffected=1}
	at com.hazelcast.jet.sql.impl.schema.AbstractSchemaStorage$EntryListenerAdapter.mapCleared(AbstractSchemaStorage.java:74) ~[classes/:?]
	at com.hazelcast.map.impl.MapListenerAdaptors.lambda$static$12(MapListenerAdaptors.java:132) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.map.impl.InternalMapListenerAdapter.onEvent(InternalMapListenerAdapter.java:56) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.map.impl.InternalMapListenerAdapter.onEvent(InternalMapListenerAdapter.java:35) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.map.impl.event.MapEventPublishingService.callListener(MapEventPublishingService.java:172) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.map.impl.event.MapEventPublishingService.dispatchMapEventData(MapEventPublishingService.java:126) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.map.impl.event.MapEventPublishingService.dispatchEvent(MapEventPublishingService.java:87) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.map.impl.event.MapEventPublishingService.dispatchEvent(MapEventPublishingService.java:47) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.map.impl.MapService.dispatchEvent(MapService.java:134) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.map.impl.MapService.dispatchEvent(MapService.java:101) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.spi.impl.eventservice.impl.EventProcessor.process(EventProcessor.java:63) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.spi.impl.eventservice.impl.RemoteEventProcessor.run(RemoteEventProcessor.java:48) [hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.internal.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:245) [hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.internal.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:228) [hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]

No metrics recorded during the test
22:06:23,499 ERROR || - [EventServiceImpl] hz.OracleAllTypesInsertJdbcSqlConnectorTest_optimistic_fermat.event-98 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] hz.OracleAllTypesInsertJdbcSqlConnectorTest_optimistic_fermat.event-98 caught an exception while processing:com.hazelcast.spi.impl.eventservice.impl.LocalEventDispatcher@1e8cf7ef
java.lang.UnsupportedOperationException: SQL catalog must never be cleared - MapEvent{entryEventType=CLEAR_ALL, member=Member [127.0.0.1]:5701 - a6c0d8e0-1ea1-499b-9e7d-8b818fc22bd4 this, name='__sql.catalog', numberOfEntriesAffected=1}
	at com.hazelcast.jet.sql.impl.schema.AbstractSchemaStorage$EntryListenerAdapter.mapCleared(AbstractSchemaStorage.java:74) ~[classes/:?]
	at com.hazelcast.map.impl.MapListenerAdaptors.lambda$static$12(MapListenerAdaptors.java:132) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.map.impl.InternalMapListenerAdapter.onEvent(InternalMapListenerAdapter.java:56) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.map.impl.InternalMapListenerAdapter.onEvent(InternalMapListenerAdapter.java:35) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.map.impl.event.MapEventPublishingService.callListener(MapEventPublishingService.java:172) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.map.impl.event.MapEventPublishingService.dispatchMapEventData(MapEventPublishingService.java:126) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.map.impl.event.MapEventPublishingService.dispatchEvent(MapEventPublishingService.java:87) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.map.impl.event.MapEventPublishingService.dispatchEvent(MapEventPublishingService.java:47) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.map.impl.MapService.dispatchEvent(MapService.java:134) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.map.impl.MapService.dispatchEvent(MapService.java:101) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.spi.impl.eventservice.impl.LocalEventDispatcher.run(LocalEventDispatcher.java:64) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.internal.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:245) [hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.internal.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:228) [hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-ZingJDK17-nightly/55/

**Comment by Patras3** [comment]
Failed again on _master_ with oracle-11 (little-endian): https://jenkins.hazelcast.com/job/Hazelcast-master-nightly-little-endian/56/testReport/com.hazelcast.jet.sql.impl.connector.jdbc.oracle/OracleAllTypesInsertJdbcSqlConnectorTest/insertRowWithAllTypes_4/

**Comment by olukas** [comment]
Failed again on _master_ with openjdk-17: https://jenkins.hazelcast.com/job/Hazelcast-master-ZuluJDK17-nightly/96/testReport/com.hazelcast.jet.sql.impl.connector.jdbc.oracle/OracleAllTypesInsertJdbcSqlConnectorTest/insertRowWithAllTypes/

**Comment by olukas** [comment]
Failed again on _master_ with oracle-11 (force-offload): https://jenkins.hazelcast.com/job/Hazelcast-master-nightly-force-offload/79/testReport/com.hazelcast.jet.sql.impl.connector.jdbc.oracle/OracleAllTypesInsertJdbcSqlConnectorTest/insertRowWithAllTypes_2/

**Comment by olukas** [comment]
Failed again on _master_ with oracle-11 (force-offload): https://jenkins.hazelcast.com/job/Hazelcast-master-nightly-force-offload/80/testReport/com.hazelcast.jet.sql.impl.connector.jdbc.oracle/OracleAllTypesInsertJdbcSqlConnectorTest/insertRowWithAllTypes/

**Comment by olukas** [comment]
Seems to fail constantly.

**Comment by orcunc** [comment]
Fixed by https://github.com/hazelcast/hazelcast-mono/pull/404
