### ISSUE TITLE
com.hazelcast.mapstore.oracle.*

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hazelcast#26173]
_master_ (commit 868b5f544bb05c5a569db4cfeeaa6ab045dd73f6)
Failed on OpenJDK11: https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK11-arm64-nightly/43/testReport/junit/com.hazelcast.mapstore.oracle/

<details><summary>Stacktrace:</summary>

```
org.testcontainers.containers.ContainerLaunchException: Container startup failed for image gvenzl/oracle-xe:21-slim-faststart
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:362)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:333)
	at com.hazelcast.test.jdbc.OracleDatabaseProvider.createDatabase(OracleDatabaseProvider.java:34)
	at com.hazelcast.jet.sql.impl.connector.jdbc.JdbcSqlTestSupport.initialize(JdbcSqlTestSupport.java:74)
	at com.hazelcast.jet.sql.impl.connector.jdbc.JdbcSqlTestSupport.initialize(JdbcSqlTestSupport.java:69)
	at com.hazelcast.mapstore.oracle.OracleGenericMapStoreBasicIT.beforeClass(OracleGenericMapStoreBasicIT.java:32)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:41)
	at com.hazelcast.test.OverridePropertyRule$1.evaluate(OverridePropertyRule.java:66)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:347)
	... 10 more
Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:566)
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:357)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
	... 11 more
Caused by: org.testcontainers.shaded.org.awaitility.core.ConditionTimeoutException: Lambda expression in org.testcontainers.containers.GenericContainer: expected the predicate to return <true> but it returned <false> for input of <InspectContainerResponse(args=[], config=ContainerConfig(attachStderr=false, attachStdin=false, attachStdout=false, cmd=null, domainName=, entrypoint=[container-entrypoint.sh], env=[ORACLE_PASSWORD=test, APP_USER=test, APP_USER_PASSWORD=test, PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/oracle/product/21c/dbhomeXE/bin:/opt/oracle, ORACLE_BASE=/opt/oracle, ORACLE_BASE_CONFIG=/opt/oracle, ORACLE_BASE_HOME=/opt/oracle/homes/OraDBHome21cXE, ORACLE_HOME=/opt/oracle/product/21c/dbhomeXE, ORACLE_SID=XE, NLS_LANG=.AL32UTF8], exposedPorts=[1521/tcp, 8080/tcp], hostName=163b04f243e9, image=gvenzl/oracle-xe:21-slim-faststart, labels={io.buildah.version=1.29.1, org.opencontainers.image.source=https://github.com/gvenzl/oci-oracle-xe, org.testcontainers=true, org.testcontainers.lang=java, org.testcontainers.sessionId=f690d156-e62c-4e15-a2e1-2fb0221ddf97, org.testcontainers.version=1.19.3}, macAddress=null, networkDisabled=null, onBuild=null, stdinOpen=false, portSpecs=null, stdInOnce=false, tty=false, user=oracle, volumes=null, workingDir=/opt/oracle, healthCheck=null), created=2023-12-07T02:35:09.338207245Z, driver=overlay2, execDriver=null, hostConfig=HostConfig(binds=[], blkioWeight=0, blkioWeightDevice=null, blkioDeviceReadBps=null, blkioDeviceWriteBps=null, blkioDeviceReadIOps=null, blkioDeviceWriteIOps=null, memorySwappiness=null, nanoCPUs=0, capAdd=null, capDrop=null, containerIDFile=, cpuPeriod=0, cpuRealtimePeriod=0, cpuRealtimeRuntime=0, cpuShares=0, cpuQuota=0, cpusetCpus=, cpusetMems=, devices=null, deviceCgroupRules=null, deviceRequests=null, diskQuota=null, dns=null, dnsOptions=null, dnsSearch=null, extraHosts=[], groupAdd=null, ipcMode=shareable, cgroup=, links=[], logConfig=LogConfig(type=json-file, config={}), lxcConf=null, memory=0, memorySwap=0, memoryReservation=0, kernelMemory=0, networkMode=default, oomKillDisable=false, init=null, autoRemove=false, oomScoreAdj=0, portBindings={1521/tcp=[Lcom.github.dockerjava.api.model.Ports$Binding;@60e44454, 8080/tcp=[Lcom.github.dockerjava.api.model.Ports$Binding;@1377f2b2}, privileged=false, publishAllPorts=false, readonlyRootfs=false, restartPolicy=no, ulimits=[Ulimit(name=nofile, soft=32768, hard=65536)], cpuCount=0, cpuPercent=0, ioMaximumIOps=0, ioMaximumBandwidth=0, volumesFrom=[], mounts=null, pidMode=, isolation=null, securityOpts=null, storageOpt=null, cgroupParent=, volumeDriver=, shmSize=67108864, pidsLimit=null, runtime=runc, tmpFs=null, utSMode=, usernsMode=, sysctls=null, consoleSize=[0, 0], cgroupnsMode=host), hostnamePath=/var/lib/docker/containers/163b04f243e9fcc4aedaaccacaa9a822a1c546f0cbd4c41cffc46fcce4d9e995/hostname, hostsPath=/var/lib/docker/containers/163b04f243e9fcc4aedaaccacaa9a822a1c546f0cbd4c41cffc46fcce4d9e995/hosts, logPath=/var/lib/docker/containers/163b04f243e9fcc4aedaaccacaa9a822a1c546f0cbd4c41cffc46fcce4d9e995/163b04f243e9fcc4aedaaccacaa9a822a1c546f0cbd4c41cffc46fcce4d9e995-json.log, id=163b04f243e9fcc4aedaaccacaa9a822a1c546f0cbd4c41cffc46fcce4d9e995, sizeRootFs=null, sizeRw=null, imageId=sha256:395e7780aaba5f8c33082bf533a17a4bffdb7bcdd58034702a1634fcbd3d1137, mountLabel=, name=/hungry_pare, restartCount=0, networkSettings=NetworkSettings(bridge=, sandboxId=d3b9c751069d5f0f972c9cf627a743c19072c86d9e85877b4182197099bdbbf5, hairpinMode=false, linkLocalIPv6Address=, linkLocalIPv6PrefixLen=0, ports={}, sandboxKey=/var/run/docker/netns/d3b9c751069d, secondaryIPAddresses=null, secondaryIPv6Addresses=null, endpointID=, gateway=, portMapping=null, globalIPv6Address=, globalIPv6PrefixLen=0, ipAddress=, ipPrefixLen=0, ipV6Gateway=, macAddress=, networks={bridge=ContainerNetwork(ipamConfig=null, links=[], aliases=null, networkID=390b93bb1d6531a1fc966ed46fbc6551dd45cf2b6ad2d74409477f591cf74c33, endpointId=, gateway=, ipAddress=, ipPrefixLen=0, ipV6Gateway=, globalIPv6Address=, globalIPv6PrefixLen=0, macAddress=)}), path=container-entrypoint.sh, processLabel=, resolvConfPath=/var/lib/docker/containers/163b04f243e9fcc4aedaaccacaa9a822a1c546f0cbd4c41cffc46fcce4d9e995/resolv.conf, execIds=null, state=InspectContainerResponse.ContainerState(status=exited, running=false, paused=false, restarting=false, oomKilled=false, dead=false, pid=0, exitCode=1, error=, startedAt=2023-12-07T02:35:09.856673278Z, finishedAt=2023-12-07T02:35:09.855850384Z, health=null), volumes=null, volumesRW=null, node=null, mounts=[], graphDriver=GraphDriver(name=overlay2, data=GraphData(rootDir=null, deviceId=null, deviceName=null, deviceSize=null, dir=null)), platform=linux)> within 5 seconds.
	at org.testcontainers.shaded.org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)
	at org.testcontainers.shaded.org.awaitility.core.AbstractHamcrestCondition.await(AbstractHamcrestCondition.java:86)
	at org.testcontainers.shaded.org.awaitility.core.ConditionFactory.until(ConditionFactory.java:985)
	at org.testcontainers.shaded.org.awaitility.core.ConditionFactory.until(ConditionFactory.java:691)
	at org.testcontainers.shaded.org.awaitility.core.ConditionFactory.until(ConditionFactory.java:708)
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:469)
	... 13 more

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-OpenJDK11-arm64-nightly/43/

**Comment by Patras3** [comment]
Failed again on _master_ with OpenJDK11: https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK11-arm64-nightly/44/testReport/com.hazelcast.mapstore.oracle/OracleGenericMapStoreBasicIT/___/

**Comment by orcunc** [comment]
Fixed by : https://github.com/hazelcast/hazelcast-mono/pull/740
