### ISSUE TITLE
com.hazelcast.internal.tpcengine.nio.TlsNioAsyncSocket_RpcTest JVM crash

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hazelcast#26172]
_master_ (commit 7789979d228cd19073c0f64109dba34032b1f38f)

Failed on OpenJDK-11-arm64: https://jenkins.hazelcast.com/job/Hazelcast-EE-master-OpenJDK11-arm64/79/

<details><summary>Stacktrace:</summary>

```
17:00:27 [ERROR] Error occurred in starting fork, check output in log
17:00:27 [ERROR] Process Exit Code: 137
17:00:27 [ERROR] Crashed tests:
17:00:27 [ERROR] com.hazelcast.internal.tpcengine.nio.TlsNioAsyncSocket_RpcTest
17:00:27 [ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
17:00:27 [ERROR] Command was /bin/sh -c cd '/home/ec2-user/workspace/Hazelcast-EE-master-OpenJDK11-arm64/hazelcast-enterprise' && '/usr/lib/jvm/java-11-openjdk-11.0.19.0.7-1.amzn2.0.1.aarch64/bin/java' '-Xmx8G' '-Xms8G' '-verbose:gc' '-Xlog:gc:maven_gc.log' '-XX:+HeapDumpOnOutOfMemoryError' '-XX:HeapDumpPath=/home/ec2-user/workspace/Hazelcast-EE-master-OpenJDK11-arm64/test.hprof' '--add-exports' 'java.base/jdk.internal.ref=ALL-UNNAMED' '--add-opens' 'java.base/java.nio=ALL-UNNAMED' '--add-opens' 'java.base/sun.nio.ch=ALL-UNNAMED' '--add-opens' 'java.base/java.lang=ALL-UNNAMED' '--add-opens' 'jdk.management/com.sun.management.internal=ALL-UNNAMED' '--add-opens' 'java.management/sun.management=ALL-UNNAMED' '--add-exports' 'jdk.management/com.ibm.lang.management.internal=ALL-UNNAMED' '--illegal-access=warn' '-ea' '-Dhazelcast.hidensity.check.freememory=false' '-Dhazelcast.phone.home.enabled=false' '-Dhazelcast.test.use.network=false' '-Dhazelcast.tomcat.shutdown_hazelcast_instance=false' '-Dlog4j.skipJansi=true' '-jar' '/home/ec2-user/workspace/Hazelcast-EE-master-OpenJDK11-arm64/hazelcast-enterprise/target/surefire/surefirebooter-20231206214800333_983.jar' '/home/ec2-user/workspace/Hazelcast-EE-master-OpenJDK11-arm64/hazelcast-enterprise/target/surefire' '2023-12-06T21-43-56_673-jvmRun1' 'surefire-20231206214800333_981tmp' 'surefire_2-20231206214800333_982tmp'
17:00:27 [ERROR] Error occurred in starting fork, check output in log
17:00:27 [ERROR] Process Exit Code: 137
17:00:27 [ERROR] Crashed tests:
17:00:27 [ERROR] com.hazelcast.internal.tpcengine.nio.TlsNioAsyncSocket_RpcTest
17:00:27 [ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:643)
17:00:27 [ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:285)
17:00:27 [ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:250)
17:00:27 [ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1240)
17:00:27 [ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1089)
17:00:27 [ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:905)
17:00:27 [ERROR] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
17:00:27 [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
17:00:27 [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
17:00:27 [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
17:00:27 [ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
17:00:27 [ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
17:00:27 [ERROR] 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
17:00:27 [ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
17:00:27 [ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
17:00:27 [ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
17:00:27 [ERROR] 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
17:00:27 [ERROR] 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
17:00:27 [ERROR] 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
17:00:27 [ERROR] 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
17:00:28 [ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
17:00:28 [ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
17:00:28 [ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
17:00:28 [ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
17:00:28 [ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
17:00:28 [ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
17:00:28 [ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
17:00:28 [ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
17:00:28 [ERROR] -> [Help 1]
17:00:28 [ERROR] 
```

</details>

Stdout: https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-EE-master-OpenJDK11-arm64/79/

**Comment by olukas** [comment]
Closing the test failure - it doesn't seem to be related to `master` or the latest maintenance stream `5.5.z` and it hasn't fail in the last 3 months. Feel free to reopen test failure if it occurs on `master` or on the latest maintenance stream.
