### ISSUE TITLE
com.hazelcast.client.starter.HazelcastClientStarterTest.testClientLifecycle

### ISSUE THREAD

**Issue by Patras3** [hazelcast/hazelcast#26179]
_5.3.z_ (commit ea353f696331004fcbc5aad701ec2d6d6069d98d)

Failed on oracle-8: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-OracleJDK8-nightly/118/testReport/junit/com.hazelcast.client.starter/HazelcastClientStarterTest/testClientLifecycle/
<details><summary>Stacktrace:</summary>

```
java.lang.IllegalStateException: Maven dependency:get timed out
	at com.hazelcast.internal.util.Preconditions.checkState(Preconditions.java:369)
	at com.hazelcast.test.starter.HazelcastVersionLocator.downloadArtifact(HazelcastVersionLocator.java:94)
	at com.hazelcast.test.starter.HazelcastVersionLocator.locateArtifact(HazelcastVersionLocator.java:82)
	at com.hazelcast.test.starter.HazelcastVersionLocator.locateVersion(HazelcastVersionLocator.java:67)
	at com.hazelcast.test.starter.HazelcastStarter$HazelcastVersionClassloaderFuture.get(HazelcastStarter.java:363)
	at com.hazelcast.test.starter.HazelcastStarter.getTargetVersionClassloader(HazelcastStarter.java:262)
	at com.hazelcast.client.starter.HazelcastClientStarter.newHazelcastClient(HazelcastClientStarter.java:54)
	at com.hazelcast.client.starter.HazelcastClientStarter.newHazelcastClient(HazelcastClientStarter.java:48)
	at com.hazelcast.client.starter.HazelcastClientStarter.newHazelcastClient(HazelcastClientStarter.java:43)
	at com.hazelcast.client.starter.HazelcastClientStarterTest.testClientLifecycle(HazelcastClientStarterTest.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:750)

```
</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: testClientMap in 2.087 seconds.
Started Running Test: testClientLifecycle
class com.hazelcast.instance.impl.HazelcastInstanceFactory loaded by HazelcastAPIDelegatingClassloader{urls = "[file:/home/jenkins/.m2/repository/com/hazelcast/hazelcast/4.0.3/hazelcast-4.0.3.jar, file:/home/jenkins/.m2/repository/com/hazelcast/hazelcast/4.0.3/hazelcast-4.0.3-tests.jar]"}
17:54:09,512  INFO |testClientLifecycle| - [MetricsConfigHelper] testClientLifecycle - [LOCAL] [dev] [4.0.3] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
17:54:09,512  INFO |testClientLifecycle| - [AddressPicker] testClientLifecycle - [LOCAL] [dev] [4.0.3] Picked [127.0.0.1]:5701, using socket ServerSocket[addr=/0.0.0.0,localport=5701], bind any local is true
17:54:09,512  INFO |testClientLifecycle| - [system] testClientLifecycle - [127.0.0.1]:5701 [dev] [4.0.3] Hazelcast 4.0.3 (20200921 - 59ae831) starting at [127.0.0.1]:5701
17:54:09,512  INFO |testClientLifecycle| - [system] testClientLifecycle - [127.0.0.1]:5701 [dev] [4.0.3] Copyright (c) 2008-2020, Hazelcast, Inc. All Rights Reserved.
17:54:09,513  INFO |testClientLifecycle| - [MetricsConfigHelper] testClientLifecycle - [127.0.0.1]:5701 [dev] [4.0.3] Collecting debug metrics and sending to diagnostics is enabled
17:54:09,513  INFO |testClientLifecycle| - [BackpressureRegulator] testClientLifecycle - [127.0.0.1]:5701 [dev] [4.0.3] Backpressure is disabled
17:54:09,516  WARN |testClientLifecycle| - [Node] testClientLifecycle - [127.0.0.1]:5701 [dev] [4.0.3] Hazelcast is bound to 127.0.0.1 and loop-back mode is disabled in the configuration. This could cause multicast auto-discovery issues and render it unable to work. Check your network connectivity, try to enable the loopback mode and/or force -Djava.net.preferIPv4Stack=true on your JVM.
17:54:09,516  INFO |testClientLifecycle| - [Node] testClientLifecycle - [127.0.0.1]:5701 [dev] [4.0.3] Creating MulticastJoiner
17:54:09,516  WARN |testClientLifecycle| - [CPSubsystem] testClientLifecycle - [127.0.0.1]:5701 [dev] [4.0.3] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
17:54:09,519  INFO |testClientLifecycle| - [OperationExecutorImpl] testClientLifecycle - [127.0.0.1]:5701 [dev] [4.0.3] Starting 8 partition threads and 5 generic threads (1 dedicated for priority tasks)
17:54:09,520  INFO |testClientLifecycle| - [Diagnostics] testClientLifecycle - [127.0.0.1]:5701 [dev] [4.0.3] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
17:54:09,520  INFO |testClientLifecycle| - [LifecycleService] testClientLifecycle - [127.0.0.1]:5701 [dev] [4.0.3] [127.0.0.1]:5701 is STARTING
17:54:11,209  INFO |testClientLifecycle| - [ClusterService] testClientLifecycle - [127.0.0.1]:5701 [dev] [4.0.3] 

Members {size:1, ver:1} [
	Member [127.0.0.1]:5701 - db0e7abc-c194-47a7-b4de-d9fa6ec8d870 this
]

17:54:11,210  INFO |testClientLifecycle| - [LifecycleService] testClientLifecycle - [127.0.0.1]:5701 [dev] [4.0.3] [127.0.0.1]:5701 is STARTED
Starting client 4.0.1
class com.hazelcast.client.HazelcastClient loaded by HazelcastAPIDelegatingClassloader{urls = "[file:/home/jenkins/.m2/repository/com/hazelcast/hazelcast/4.0.1/hazelcast-4.0.1.jar, file:/home/jenkins/.m2/repository/com/hazelcast/hazelcast/4.0.1/hazelcast-4.0.1-tests.jar]"}
17:54:18,977  INFO |testClientLifecycle| - [ClientInvocationService] testClientLifecycle - hz.client_1 [dev] [4.0.1] Running with 2 response threads, dynamic=true
17:54:19,034  INFO |testClientLifecycle| - [LifecycleService] testClientLifecycle - hz.client_1 [dev] [4.0.1] HazelcastClient 4.0.1 (20200409 - e086b9c) is STARTING
17:54:19,034  INFO |testClientLifecycle| - [LifecycleService] testClientLifecycle - hz.client_1 [dev] [4.0.1] HazelcastClient 4.0.1 (20200409 - e086b9c) is STARTED
17:54:19,053  INFO |testClientLifecycle| - [ClientConnectionManager] testClientLifecycle - hz.client_1 [dev] [4.0.1] Trying to connect to cluster: dev
17:54:19,055  INFO |testClientLifecycle| - [ClientConnectionManager] testClientLifecycle - hz.client_1 [dev] [4.0.1] Trying to connect to [127.0.0.1]:5701
17:54:19,078 DEBUG |testClientLifecycle| - [AuthenticationMessageTask] hz.86e4159b-877b-48b0-9dfc-1e8ae166f3a7.generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [4.0.3] Processing authentication with clientUuid bca22a3f-8924-4559-8e17-8506bdaff680
17:54:19,078  INFO |testClientLifecycle| - [AuthenticationMessageTask] hz.86e4159b-877b-48b0-9dfc-1e8ae166f3a7.generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [4.0.3] Received auth from Connection[id=1, /127.0.0.1:5701->/127.0.0.1:36519, qualifier=null, endpoint=[127.0.0.1]:36519, alive=true, connectionType=JVM], successfully authenticated, clientUuid: bca22a3f-8924-4559-8e17-8506bdaff680, client version: 4.0.1
17:54:19,081  INFO |testClientLifecycle| - [LifecycleService] testClientLifecycle - hz.client_1 [dev] [4.0.1] HazelcastClient 4.0.1 (20200409 - e086b9c) is CLIENT_CONNECTED
17:54:19,081  INFO |testClientLifecycle| - [ClientConnectionManager] testClientLifecycle - hz.client_1 [dev] [4.0.1] Authenticated with server [127.0.0.1]:5701:db0e7abc-c194-47a7-b4de-d9fa6ec8d870, server version: 4.0.3, local address: /127.0.0.1:36519
17:54:19,082 TRACE |testClientLifecycle| - [ClientListenerService] testClientLifecycle - hz.client_1 [dev] [4.0.1] Register attempt of ClusterViewListenerHandler to ClientConnection{alive=true, connectionId=1, channel=NioChannel{/127.0.0.1:36519->/127.0.0.1:5701}, remoteEndpoint=[127.0.0.1]:5701, lastReadTime=2023-12-11 17:54:19.078, lastWriteTime=2023-12-11 17:54:19.077, closedTime=never, connected server version=4.0.3}
17:54:19,083  INFO |testClientLifecycle| - [Diagnostics] testClientLifecycle - hz.client_1 [dev] [4.0.1] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
17:54:19,085 TRACE || - [ClientListenerService] ForkJoinPool.commonPool-worker-7 - hz.client_1 [dev] [4.0.1] Registered ClusterViewListenerHandler to ClientConnection{alive=true, connectionId=1, channel=NioChannel{/127.0.0.1:36519->/127.0.0.1:5701}, remoteEndpoint=[127.0.0.1]:5701, lastReadTime=2023-12-11 17:54:19.084, lastWriteTime=2023-12-11 17:54:19.082, closedTime=never, connected server version=4.0.3}
17:54:19,089  INFO |testClientLifecycle| - [ClientClusterService] hz.client_1.event-1 - hz.client_1 [dev] [4.0.1] 

Members [1] {
	Member [127.0.0.1]:5701 - db0e7abc-c194-47a7-b4de-d9fa6ec8d870
}

17:54:19,113 TRACE |testClientLifecycle| - [ClientListenerService] hz.client_1.eventRegistration- - hz.client_1 [dev] [4.0.1] Register attempt of ClientListenerRegistration{codec=com.hazelcast.client.impl.spi.impl.ClientInvocationServiceImpl$1@3fd4c19a, handler=com.hazelcast.client.impl.spi.impl.ClientInvocationServiceImpl$BackupEventHandler@7ad64804} to ClientConnection{alive=true, connectionId=1, channel=NioChannel{/127.0.0.1:36519->/127.0.0.1:5701}, remoteEndpoint=[127.0.0.1]:5701, lastReadTime=2023-12-11 17:54:19.084, lastWriteTime=2023-12-11 17:54:19.082, closedTime=never, connected server version=4.0.3}
17:54:19,114 TRACE |testClientLifecycle| - [ClientListenerService] hz.client_1.eventRegistration- - hz.client_1 [dev] [4.0.1] Registered ClientListenerRegistration{codec=com.hazelcast.client.impl.spi.impl.ClientInvocationServiceImpl$1@3fd4c19a, handler=com.hazelcast.client.impl.spi.impl.ClientInvocationServiceImpl$BackupEventHandler@7ad64804} to ClientConnection{alive=true, connectionId=1, channel=NioChannel{/127.0.0.1:36519->/127.0.0.1:5701}, remoteEndpoint=[127.0.0.1]:5701, lastReadTime=2023-12-11 17:54:19.114, lastWriteTime=2023-12-11 17:54:19.113, closedTime=never, connected server version=4.0.3}
17:54:19,123  INFO |testClientLifecycle| - [ClientStatisticsService] testClientLifecycle - Client statistics is enabled with period 5 seconds.
Stopping client 4.0.1
17:54:19,125  INFO |testClientLifecycle| - [LifecycleService] testClientLifecycle - hz.client_1 [dev] [4.0.1] HazelcastClient 4.0.1 (20200409 - e086b9c) is SHUTTING_DOWN
17:54:19,127  INFO |testClientLifecycle| - [TcpIpConnection] hz.86e4159b-877b-48b0-9dfc-1e8ae166f3a7.IO.thread-in-0 - [127.0.0.1]:5701 [dev] [4.0.3] Connection[id=1, /127.0.0.1:5701->/127.0.0.1:36519, qualifier=null, endpoint=[127.0.0.1]:36519, alive=false, connectionType=JVM] closed. Reason: Connection closed by the other side
17:54:19,127  INFO |testClientLifecycle| - [ClientConnectionManager] testClientLifecycle - hz.client_1 [dev] [4.0.1] Removed connection to endpoint: [127.0.0.1]:5701:db0e7abc-c194-47a7-b4de-d9fa6ec8d870, connection: ClientConnection{alive=false, connectionId=1, channel=NioChannel{/127.0.0.1:36519->/127.0.0.1:5701}, remoteEndpoint=[127.0.0.1]:5701, lastReadTime=2023-12-11 17:54:19.114, lastWriteTime=2023-12-11 17:54:19.113, closedTime=2023-12-11 17:54:19.126, connected server version=4.0.3}
17:54:19,127  INFO |testClientLifecycle| - [LifecycleService] testClientLifecycle - hz.client_1 [dev] [4.0.1] HazelcastClient 4.0.1 (20200409 - e086b9c) is CLIENT_DISCONNECTED
17:54:19,127  INFO |testClientLifecycle| - [ClientEndpointManager] hz.86e4159b-877b-48b0-9dfc-1e8ae166f3a7.event-40 - [127.0.0.1]:5701 [dev] [4.0.3] Destroying ClientEndpoint{connection=Connection[id=1, /127.0.0.1:5701->/127.0.0.1:36519, qualifier=null, endpoint=[127.0.0.1]:36519, alive=false, connectionType=JVM], clientUuid='bca22a3f-8924-4559-8e17-8506bdaff680, authenticated=true, clientVersion=4.0.1, creationTime=1702317259077, latest clientAttributes=null}
17:54:19,136  INFO |testClientLifecycle| - [LifecycleService] testClientLifecycle - hz.client_1 [dev] [4.0.1] HazelcastClient 4.0.1 (20200409 - e086b9c) is SHUTDOWN
Starting client 4.0.2
17:56:20,932  INFO |testClientLifecycle| - [LifecycleService] main - [127.0.0.1]:5701 [dev] [4.0.3] [127.0.0.1]:5701 is SHUTTING_DOWN
17:56:20,932  INFO |testClientLifecycle| - [Node] main - [127.0.0.1]:5701 [dev] [4.0.3] Shutting down multicast service...
17:56:20,933  INFO |testClientLifecycle| - [Node] main - [127.0.0.1]:5701 [dev] [4.0.3] Shutting down connection manager...
17:56:20,934  INFO |testClientLifecycle| - [Node] main - [127.0.0.1]:5701 [dev] [4.0.3] Shutting down node engine...
17:56:20,941  INFO |testClientLifecycle| - [NodeExtension] main - [127.0.0.1]:5701 [dev] [4.0.3] Destroying node NodeExtension.
17:56:20,941  INFO |testClientLifecycle| - [Node] main - [127.0.0.1]:5701 [dev] [4.0.3] Hazelcast Shutdown is completed in 9 ms.
17:56:20,941  INFO |testClientLifecycle| - [LifecycleService] main - [127.0.0.1]:5701 [dev] [4.0.3] [127.0.0.1]:5701 is SHUTDOWN

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-5.maintenance-OracleJDK8-nightly/118/

**Comment by JackPGreen** [comment]
Duplicates #25919
