### ISSUE TITLE
com.hazelcast.internal.cluster.impl.DemoteDataMemberTest.demotion_shouldSucceed_whenMasterLeaves_duringDemotion

### ISSUE THREAD

**Issue by Patras3** [hazelcast/hazelcast#26180]
_master_ (commit 124f6df93876781d63ee66bfb565315e099cf8d5)

Failed on Windows - OracleJDK11: https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-OracleJDK11/477/testReport/junit/com.hazelcast.internal.cluster.impl/DemoteDataMemberTest/demotion_shouldSucceed_whenMasterLeaves_duringDemotion/
<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: 
Replica 0 of partition Partition {ID: 0, Version: 10} [
	0:[127.0.0.1]:5703 - 11858e61-f2a0-447f-b8a1-50876d175e0f
	1:[127.0.0.1]:5702 - 1052cedf-35a6-44b7-9926-3d79d8bdb006
] must not have the given address. Actual: [127.0.0.1]:5703
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failEquals(Assert.java:187)
	at org.junit.Assert.assertNotEquals(Assert.java:163)
	at com.hazelcast.internal.cluster.impl.DemoteDataMemberTest.assertNoPartitionsAssigned(DemoteDataMemberTest.java:480)
	at com.hazelcast.internal.cluster.impl.DemoteDataMemberTest.demotion_shouldSucceed_whenMasterLeaves_duringDemotion(DemoteDataMemberTest.java:343)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-Windows-OracleJDK11/477/

**Comment by olukas** [comment]
Closing the test failure - it doesn't seem to be related to `master` or the latest maintenance stream `5.5.z` and it hasn't fail in the last 3 months. Feel free to reopen test failure if it occurs on `master` or on the latest maintenance stream.

**Comment by AleksPeychev** [comment]
Reopening as issue occurred again on: _master_ (commit a2f4a93401d6c7a0fca7c2526bf235e0782baa6f)
with MicrosoftJDK17 (Windows): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Windows-MicrosoftJDK17/141/testReport/com.hazelcast.internal.cluster.impl/DemoteDataMemberTest/demotion_shouldSucceed_whenMasterLeaves_duringDemotion/
<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: 
Replica 0 of partition Partition {ID: 9, Version: 8} [
	0:[127.0.0.1]:5703 - 88105abe-ea64-4580-91af-1263e154378b
	1:[127.0.0.1]:5702 - ad771be6-c879-4677-bc25-87c5b88e2fb7
] must not have the given address. Actual: [127.0.0.1]:5703
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failEquals(Assert.java:187)
	at org.junit.Assert.assertNotEquals(Assert.java:163)
	at com.hazelcast.internal.cluster.impl.DemoteDataMemberTest.assertNoPartitionsAssigned(DemoteDataMemberTest.java:480)
	at com.hazelcast.internal.cluster.impl.DemoteDataMemberTest.demotion_shouldSucceed_whenMasterLeaves_duringDemotion(DemoteDataMemberTest.java:343)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)

```
</details>



Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-Windows-MicrosoftJDK17/141/
