### ISSUE TITLE
com.hazelcast.jet.sql.impl.connector.jdbc.mysql.MySqlDownTest.showDataConnectionsShouldReturnQuickly [HZ-4135]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#26189]
_master_ (commit 16069feefba3dc70102fc314e3f5c97d570d94b5)

Failed on oracle-11 (mysql-8.0): https://jenkins.hazelcast.com/job/Hazelcast-master-mysql-8.0/38/testReport/com.hazelcast.jet.sql.impl.connector.jdbc.mysql/MySqlDownTest/showDataConnectionsShouldReturnQuickly/
<details><summary>Stacktrace:</summary>

```
org.opentest4j.AssertionFailedError: 

Expecting actual:
  [Row{[mysql(class=java.lang.String), jdbc(class=java.lang.String), ["Table"](class=com.hazelcast.core.HazelcastJsonValue)]},
    Row{[testDatabaseRef(class=java.lang.String), Jdbc(class=java.lang.String), ["Table"](class=com.hazelcast.core.HazelcastJsonValue)]}]
to contain exactly (and in same order):
  [Row{[mysql(class=java.lang.String), jdbc(class=java.lang.String), ["Table"](class=com.hazelcast.core.HazelcastJsonValue)]},
    Row{[testDatabaseRef(class=java.lang.String), jdbc(class=java.lang.String), ["Table"](class=com.hazelcast.core.HazelcastJsonValue)]}]
but some elements were not found:
  [Row{[testDatabaseRef(class=java.lang.String), jdbc(class=java.lang.String), ["Table"](class=com.hazelcast.core.HazelcastJsonValue)]}]
and others were not expected:
  [Row{[testDatabaseRef(class=java.lang.String), Jdbc(class=java.lang.String), ["Table"](class=com.hazelcast.core.HazelcastJsonValue)]}]

	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at com.hazelcast.jet.sql.impl.connector.jdbc.mysql.MySqlDownTest.showDataConnectionsShouldReturnQuickly(MySqlDownTest.java:94)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)

```
</details>

<details><summary>Standard output:</summary>

```
21:18:21,920  INFO || - [MetricsConfigHelper] Time-limited test - [LOCAL] [dev] [5.4.0-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
21:18:21,922  INFO || - [logo] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
21:18:21,922  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Copyright (c) 2008-2023, Hazelcast, Inc. All Rights Reserved.
21:18:21,922  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Hazelcast Platform 5.4.0-SNAPSHOT (20231216 - 16069fe) starting at [127.0.0.1]:5701
21:18:21,922  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Cluster name: dev
21:18:21,922  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed. For more information, see the documentation for Integrity Checker.
21:18:21,922  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Jet is enabled
21:18:21,969  INFO || - [MetricsConfigHelper] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
21:18:21,970  INFO || - [TpcServerBootstrap] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] TPC: disabled
21:18:21,979  WARN || - [CPSubsystem] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
21:18:21,986  INFO || - [JetServiceBackend] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Setting number of cooperative threads and default parallelism to 2
21:18:21,988  INFO || - [Diagnostics] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
21:18:21,989  INFO || - [LifecycleService] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] [127.0.0.1]:5701 is STARTING
21:18:21,989  INFO || - [ClusterService] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] 

Members {size:1, ver:1} [
	Member [127.0.0.1]:5701 - a656af38-8569-40e8-a84b-25335f5c3c85 this
]

21:18:21,989  INFO || - [JobCoordinationService] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Jet started scanning for jobs
21:18:21,989 DEBUG || - [JobCoordinationService] hz.MySqlDownTest_focused_tereshkova.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
21:18:21,989  INFO || - [LifecycleService] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] [127.0.0.1]:5701 is STARTED
21:18:21,991  INFO || - [MetricsConfigHelper] Time-limited test - [LOCAL] [dev] [5.4.0-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
21:18:21,992  INFO || - [logo] Time-limited test - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
21:18:21,992  INFO || - [system] Time-limited test - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] Copyright (c) 2008-2023, Hazelcast, Inc. All Rights Reserved.
21:18:21,992  INFO || - [system] Time-limited test - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] Hazelcast Platform 5.4.0-SNAPSHOT (20231216 - 16069fe) starting at [127.0.0.1]:5702
21:18:21,992  INFO || - [system] Time-limited test - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] Cluster name: dev
21:18:21,992  INFO || - [system] Time-limited test - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed. For more information, see the documentation for Integrity Checker.
21:18:21,992  INFO || - [system] Time-limited test - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] Jet is enabled
21:18:21,997  INFO || - [MetricsConfigHelper] Time-limited test - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
21:18:21,997  INFO || - [TpcServerBootstrap] Time-limited test - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] TPC: disabled
21:18:22,004  WARN || - [CPSubsystem] Time-limited test - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
21:18:22,009  INFO || - [JetServiceBackend] Time-limited test - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] Setting number of cooperative threads and default parallelism to 2
21:18:22,012  INFO || - [Diagnostics] Time-limited test - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
21:18:22,012  INFO || - [LifecycleService] Time-limited test - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] [127.0.0.1]:5702 is STARTING
21:18:22,013  INFO || - [MockServer] Time-limited test - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] Created connection to endpoint: [127.0.0.1]:5701-a656af38-8569-40e8-a84b-25335f5c3c85, connection: MockConnection{localEndpoint=[address=[127.0.0.1]:5702, uuid=e9654a23-31d7-4c5e-b0c9-e4c2476764b1], remoteEndpoint=[address=[127.0.0.1]:5701, uuid=a656af38-8569-40e8-a84b-25335f5c3c85], alive=true}
21:18:22,016  INFO || - [MockServer] hz.MySqlDownTest_focused_tereshkova.priority-generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Created connection to endpoint: [127.0.0.1]:5702-e9654a23-31d7-4c5e-b0c9-e4c2476764b1, connection: MockConnection{localEndpoint=[address=[127.0.0.1]:5701, uuid=a656af38-8569-40e8-a84b-25335f5c3c85], remoteEndpoint=[address=[127.0.0.1]:5702, uuid=e9654a23-31d7-4c5e-b0c9-e4c2476764b1], alive=true}
21:18:22,017  INFO || - [ClusterService] hz.MySqlDownTest_focused_tereshkova.priority-generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] 

Members {size:2, ver:2} [
	Member [127.0.0.1]:5701 - a656af38-8569-40e8-a84b-25335f5c3c85 this
	Member [127.0.0.1]:5702 - e9654a23-31d7-4c5e-b0c9-e4c2476764b1
]

21:18:22,089 DEBUG || - [JobCoordinationService] hz.MySqlDownTest_focused_tereshkova.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
21:18:22,115  INFO || - [ClusterService] hz.MySqlDownTest_distracted_tereshkova.generic-operation.thread-1 - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] 

Members {size:2, ver:2} [
	Member [127.0.0.1]:5701 - a656af38-8569-40e8-a84b-25335f5c3c85
	Member [127.0.0.1]:5702 - e9654a23-31d7-4c5e-b0c9-e4c2476764b1 this
]

21:18:22,116  INFO || - [JobCoordinationService] Time-limited test - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] Jet started scanning for jobs
21:18:22,117  INFO || - [LifecycleService] Time-limited test - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] [127.0.0.1]:5702 is STARTED
Started Running Test: showDataConnectionsShouldReturnQuickly
21:18:22,189 DEBUG || - [JobCoordinationService] hz.MySqlDownTest_focused_tereshkova.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
21:18:22,289 DEBUG || - [JobCoordinationService] hz.MySqlDownTest_focused_tereshkova.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
21:18:22,390 DEBUG || - [JobCoordinationService] hz.MySqlDownTest_focused_tereshkova.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
21:18:22,490 DEBUG || - [JobCoordinationService] hz.MySqlDownTest_focused_tereshkova.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
21:18:22,591 DEBUG || - [JobCoordinationService] hz.MySqlDownTest_focused_tereshkova.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
21:18:22,691 DEBUG || - [JobCoordinationService] hz.MySqlDownTest_focused_tereshkova.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
21:18:22,791 DEBUG || - [JobCoordinationService] hz.MySqlDownTest_focused_tereshkova.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
21:18:22,891 DEBUG || - [JobCoordinationService] hz.MySqlDownTest_focused_tereshkova.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
21:18:22,992 DEBUG || - [JobCoordinationService] hz.MySqlDownTest_focused_tereshkova.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
21:18:23,091 DEBUG || - [JobCoordinationService] hz.MySqlDownTest_focused_tereshkova.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
21:18:23,191 DEBUG || - [JobCoordinationService] hz.MySqlDownTest_focused_tereshkova.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
21:18:23,292 DEBUG || - [JobCoordinationService] hz.MySqlDownTest_focused_tereshkova.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
21:18:23,392 DEBUG || - [JobCoordinationService] hz.MySqlDownTest_focused_tereshkova.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
21:18:23,492 DEBUG || - [JobCoordinationService] hz.MySqlDownTest_focused_tereshkova.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
21:18:23,592 DEBUG || - [JobCoordinationService] hz.MySqlDownTest_focused_tereshkova.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
21:18:23,692 DEBUG || - [JobCoordinationService] hz.MySqlDownTest_focused_tereshkova.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
21:18:23,793 DEBUG || - [JobCoordinationService] hz.MySqlDownTest_focused_tereshkova.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
21:18:23,892 DEBUG || - [JobCoordinationService] hz.MySqlDownTest_focused_tereshkova.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
21:18:23,980  INFO |showDataConnectionsShouldReturnQuickly| - [PartitionStateManager] showDataConnectionsShouldReturnQuickly - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Initializing cluster partition table arrangement...
21:18:23,995 DEBUG || - [JobRepository] hz.MySqlDownTest_focused_tereshkova.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
21:18:26,341  INFO |showDataConnectionsShouldReturnQuickly| - [SqlTestSupport] Time-limited test - Removing 0 cached plans in SqlTestSupport.@After
21:18:26,341  INFO |showDataConnectionsShouldReturnQuickly| - [SqlTestSupport] Time-limited test - Removing 0 cached plans in SqlTestSupport.@After
21:18:26,343  INFO |showDataConnectionsShouldReturnQuickly| - [SimpleTestInClusterSupport] Time-limited test - Ditching 0 jobs in SimpleTestInClusterSupport.@After: []
21:18:26,343  INFO |showDataConnectionsShouldReturnQuickly| - [SimpleTestInClusterSupport] Time-limited test - Destroying 1 distributed objects in SimpleTestInClusterSupport.@After: [hz:impl:mapService/__sql.catalog]
21:18:26,348  INFO |showDataConnectionsShouldReturnQuickly| - [HazelcastTestSupport] Time-limited test - Shutting down node factory as @After action
21:18:26,348  WARN || - [EventService] hz.MySqlDownTest_distracted_tereshkova.event-8 - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] Error while logging processing event
java.lang.UnsupportedOperationException: SQL catalog must never be cleared - MapEvent{entryEventType=CLEAR_ALL, member=Member [127.0.0.1]:5701 - a656af38-8569-40e8-a84b-25335f5c3c85, name='__sql.catalog', numberOfEntriesAffected=2}
	at com.hazelcast.jet.sql.impl.schema.AbstractSchemaStorage$EntryListenerAdapter.mapCleared(AbstractSchemaStorage.java:74) ~[classes/:?]
	at com.hazelcast.map.impl.MapListenerAdaptors.lambda$static$12(MapListenerAdaptors.java:132) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.map.impl.InternalMapListenerAdapter.onEvent(InternalMapListenerAdapter.java:56) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.map.impl.InternalMapListenerAdapter.onEvent(InternalMapListenerAdapter.java:35) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.map.impl.event.MapEventPublishingService.callListener(MapEventPublishingService.java:172) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.map.impl.event.MapEventPublishingService.dispatchMapEventData(MapEventPublishingService.java:126) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.map.impl.event.MapEventPublishingService.dispatchEvent(MapEventPublishingService.java:87) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.map.impl.event.MapEventPublishingService.dispatchEvent(MapEventPublishingService.java:47) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.map.impl.MapService.dispatchEvent(MapService.java:134) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.map.impl.MapService.dispatchEvent(MapService.java:101) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.spi.impl.eventservice.impl.EventProcessor.process(EventProcessor.java:63) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.spi.impl.eventservice.impl.RemoteEventProcessor.run(RemoteEventProcessor.java:48) [hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.internal.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:245) [hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.internal.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:228) [hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
21:18:26,348 ERROR || - [EventServiceImpl] hz.MySqlDownTest_focused_tereshkova.event-7 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] hz.MySqlDownTest_focused_tereshkova.event-7 caught an exception while processing:com.hazelcast.spi.impl.eventservice.impl.LocalEventDispatcher@204e72f1
java.lang.UnsupportedOperationException: SQL catalog must never be cleared - MapEvent{entryEventType=CLEAR_ALL, member=Member [127.0.0.1]:5701 - a656af38-8569-40e8-a84b-25335f5c3c85 this, name='__sql.catalog', numberOfEntriesAffected=2}
	at com.hazelcast.jet.sql.impl.schema.AbstractSchemaStorage$EntryListenerAdapter.mapCleared(AbstractSchemaStorage.java:74) ~[classes/:?]
	at com.hazelcast.map.impl.MapListenerAdaptors.lambda$static$12(MapListenerAdaptors.java:132) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.map.impl.InternalMapListenerAdapter.onEvent(InternalMapListenerAdapter.java:56) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.map.impl.InternalMapListenerAdapter.onEvent(InternalMapListenerAdapter.java:35) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.map.impl.event.MapEventPublishingService.callListener(MapEventPublishingService.java:172) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.map.impl.event.MapEventPublishingService.dispatchMapEventData(MapEventPublishingService.java:126) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.map.impl.event.MapEventPublishingService.dispatchEvent(MapEventPublishingService.java:87) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.map.impl.event.MapEventPublishingService.dispatchEvent(MapEventPublishingService.java:47) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.map.impl.MapService.dispatchEvent(MapService.java:134) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.map.impl.MapService.dispatchEvent(MapService.java:101) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.spi.impl.eventservice.impl.LocalEventDispatcher.run(LocalEventDispatcher.java:64) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.internal.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:245) [hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.internal.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:228) [hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
BuildInfo right after showDataConnectionsShouldReturnQuickly(com.hazelcast.jet.sql.impl.connector.jdbc.mysql.MySqlDownTest): BuildInfo{version='5.4.0-SNAPSHOT', build='20231216', buildNumber=20231216, revision=16069fe, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'showDataConnectionsShouldReturnQuickly(com.hazelcast.jet.sql.impl.connector.jdbc.mysql.MySqlDownTest):'
21:18:20, accumulated pauses: 42 ms, max pause: 0 ms, pauses over 1000 ms: 0
21:18:25, accumulated pauses: 173 ms, max pause: 162 ms, pauses over 1000 ms: 0


No metrics recorded during the test

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-mysql-8.0/38/

**Comment by olukas** [comment]
Failed again on _master_ with oracle-11 (mysql-8.2): https://jenkins.hazelcast.com/job/Hazelcast-master-mysql-8.2/12/testReport/com.hazelcast.jet.sql.impl.connector.jdbc.mysql/MySqlDownTest/showDataConnectionsShouldReturnQuickly/

**Comment by olukas** [comment]
Failed again on _master_ with:
- oracle-11 (mysql-5.7): https://jenkins.hazelcast.com/job/Hazelcast-master-mysql-5.7/39/testReport/com.hazelcast.jet.sql.impl.connector.jdbc.mysql/MySqlDownTest/showDataConnectionsShouldReturnQuickly/
- oracle-11 (mysql-8.0): 
  - https://jenkins.hazelcast.com/job/Hazelcast-master-mysql-8.0/39/testReport/com.hazelcast.jet.sql.impl.connector.jdbc.mysql/MySqlDownTest/showDataConnectionsShouldReturnQuickly/
  - https://jenkins.hazelcast.com/job/Hazelcast-master-mysql-8.0/40/testReport/com.hazelcast.jet.sql.impl.connector.jdbc.mysql/MySqlDownTest/showDataConnectionsShouldReturnQuickly/
- oracle-11 (mysql-8.2): 
  - https://jenkins.hazelcast.com/job/Hazelcast-master-mysql-8.2/13/testReport/com.hazelcast.jet.sql.impl.connector.jdbc.mysql/MySqlDownTest/showDataConnectionsShouldReturnQuickly/
  - https://jenkins.hazelcast.com/job/Hazelcast-master-mysql-8.2/14/testReport/com.hazelcast.jet.sql.impl.connector.jdbc.mysql/MySqlDownTest/showDataConnectionsShouldReturnQuickly/

**Comment by olukas** [comment]
Seems to fail constantly.

**Comment by olukas** [comment]
Seems to be fixed. Feel free to reopen if it will fail again (and remote `constant-test-failure` label unless it fails constantly).
