### ISSUE TITLE
com.hazelcast.jet.kafka.connect.KafkaConnectIT.(?)

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#26186]
_master_ (commit 4c9cd6ae7386dbde10450d5fd6bc14b71c59e37a)

Failed on corretto-17: https://jenkins.hazelcast.com/job/Hazelcast-master-CorrettoJDK17/119/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectIT/___/
<details><summary>Stacktrace:</summary>

```
org.junit.runners.model.TestTimedOutException: test timed out after 900 seconds
	at java.base@17.0.5/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@17.0.5/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341)
	at app//com.hazelcast.spi.impl.AbstractInvocationFuture.manageParking(AbstractInvocationFuture.java:694)
	at app//com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:616)
	at app//com.hazelcast.jet.impl.JetInstanceImpl.getJobsInt(JetInstanceImpl.java:105)
	at app//com.hazelcast.jet.impl.AbstractJetInstance.getJobs(AbstractJetInstance.java:245)
	at app//com.hazelcast.jet.core.JetTestSupport.shutdownJobsAndGetLeakedClassLoaders(JetTestSupport.java:148)
	at app//com.hazelcast.jet.core.JetTestSupport.shutdownFactory(JetTestSupport.java:120)
	at java.base@17.0.5/java.lang.reflect.Method.invoke(Method.java:568)
	at app//com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:381)
	at app//com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37)
	at app//com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:104)
	at app//com.hazelcast.test.metrics.MetricsRule$1.evaluate(MetricsRule.java:63)
	at app//com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:53)
	at app//com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:32)
	at app//com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:41)
	at app//com.hazelcast.test.OverridePropertyRule$1.evaluate(OverridePropertyRule.java:69)
	at app//com.hazelcast.test.OverridePropertyRule$1.evaluate(OverridePropertyRule.java:69)
	at java.base@17.0.5/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base@17.0.5/java.lang.Thread.run(Thread.java:833)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-CorrettoJDK17/119/

**Comment by olukas** [comment]
Failed again on _master_ with oracle-11 (force-offload): https://jenkins.hazelcast.com/job/Hazelcast-master-force-offload/79/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectIT/___/

**Comment by Patras3** [comment]
Failed again on _master_ with corretto-21: https://jenkins.hazelcast.com/job/Hazelcast-master-CorrettoJDK21/1/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectIT/___/

**Comment by olukas** [comment]
Failed again on _master_ with RedHatJDK17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-RedHatJDK17/104/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectIT/___/

**Comment by olukas** [comment]
Failed again on _master_ with OpenJDK17: https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK17-Esxi7/80/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectIT/___/

**Comment by Patras3** [comment]
This comment was automatically generated to summarize test results for the last 30 days.

```

For branch: master
Builds between : 2024-07-13 04:15 - 2024-07-18 06:02
Jobs: 16, Runs: 18, Passed: 0, Failed: 18, Skipped: 0, Fail Ratio: 100.00%
Run on:
+----------------------------------------------------+
| JDK          | PASSED | FAILED | SKIPPED |  RATIO  |
+----------------------------------------------------+
| unknown      |   0    |   8    |    0    | 100.00% |
| zing-17      |   0    |   1    |    0    | 100.00% |
| openj9-17    |   0    |   1    |    0    | 100.00% |
| microsoft-17 |   0    |   1    |    0    | 100.00% |
| openj9-21    |   0    |   1    |    0    | 100.00% |
| oracle-17    |   0    |   3    |    0    | 100.00% |
| redhat-17    |   0    |   1    |    0    | 100.00% |
| zing-21      |   0    |   1    |    0    | 100.00% |
| openjdk-17   |   0    |   1    |    0    | 100.00% |
+----------------------------------------------------+

Builds Timeline:
2024-07-18 06:02 - FAILED (openj9-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-Openj9-17/128/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectIT/(?)/
2024-07-18 00:01 - FAILED (oracle-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-OracleJDK17/143/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectIT/(?)/
2024-07-17 22:44 - FAILED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK17-arm64/29/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectIT/(?)/
2024-07-17 22:33 - FAILED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-CorrettoJDK17-arm64/25/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectIT/(?)/
2024-07-17 03:00 - FAILED (microsoft-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-MicrosoftJDK17/124/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectIT/(?)/
2024-07-16 19:33 - FAILED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-MacOS-OpenJDK17/53/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectIT/(?)/
2024-07-16 18:12 - FAILED (zing-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK21/27/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectIT/(?)/
2024-07-16 04:15 - FAILED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-MacOS-ZuluJDK21/61/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectIT/(?)/
2024-07-16 00:13 - FAILED (redhat-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-RedHatJDK17/126/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectIT/(?)/
2024-07-15 21:09 - FAILED (openjdk-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-ZuluJDK17/146/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectIT/(?)/
2024-07-15 05:13 - FAILED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK17-Esxi7/98/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectIT/(?)/
2024-07-14 21:13 - FAILED (oracle-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-force-offload/107/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectIT/(?)/
2024-07-14 09:01 - FAILED (zing-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK17/63/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectIT/(?)/
2024-07-13 20:07 - FAILED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK17/124/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectIT/(?)/
2024-07-13 19:33 - FAILED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-MacOS-OpenJDK17/52/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectIT/(?)/
2024-07-13 09:14 - FAILED (openj9-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-Openj9-21/26/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectIT/(?)/
2024-07-13 09:12 - FAILED (oracle-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-little-endian/314/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectIT/(?)/
2024-07-13 04:15 - FAILED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-MacOS-ZuluJDK21/60/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectIT/(?)/

----------------------------------------
```

**Comment by olukas** [comment]
Closing the test failure - it hasn't failed in the last 3 months.
