### ISSUE TITLE
com.hazelcast.jet.sql.impl.connector.jdbc.postgres.PostgresMappingJdbcSqlConnectorTest and com.hazelcast.jet.sql.impl.connector.jdbc.mysql.MySQLMappingJdbcSqlConnectorTest.createMappingFails_tableExistInAnotherDatabase_externalNameOnlyTableName [HZ-4134]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#26188]
_master_ (commit f7656f402b9e7a829607c9b6b08aaec9ac30206b)

Failed on oracle-11 (postgres-11): https://jenkins.hazelcast.com/job/Hazelcast-master-postgres-11/34/testReport/com.hazelcast.jet.sql.impl.connector.jdbc.postgres/PostgresMappingJdbcSqlConnectorTest/

Following tests failed:
- `com.hazelcast.jet.sql.impl.connector.jdbc.postgres.PostgresMappingJdbcSqlConnectorTest.createMappingFails_tableExistInAnotherDatabase_externalNameFullName`
- `com.hazelcast.jet.sql.impl.connector.jdbc.postgres.PostgresMappingJdbcSqlConnectorTest.createMappingFails_tableExistInAnotherDatabase_externalNameOnlyTableName`

<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: 

Expecting code to raise a throwable.
	at com.hazelcast.jet.sql.impl.connector.jdbc.MappingJdbcSqlConnectorTest.createMappingFails_tableExistInAnotherDatabase_externalNameFullName(MappingJdbcSqlConnectorTest.java:568)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)

```
</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: createMappingWithExternalTableNameTooManyComponents in 0.019 seconds.
Started Running Test: createMappingFails_tableExistInAnotherDatabase_externalNameFullName
01:17:27,739  INFO |createMappingFails_tableExistInAnotherDatabase_externalNameFullName| - [SqlTestSupport] Time-limited test - Removing 0 cached plans in SqlTestSupport.@After
01:17:27,739  INFO |createMappingFails_tableExistInAnotherDatabase_externalNameFullName| - [SqlTestSupport] Time-limited test - Removing 0 cached plans in SqlTestSupport.@After
01:17:27,742  INFO |createMappingFails_tableExistInAnotherDatabase_externalNameFullName| - [SimpleTestInClusterSupport] Time-limited test - Ditching 0 jobs in SimpleTestInClusterSupport.@After: []
01:17:27,742  INFO |createMappingFails_tableExistInAnotherDatabase_externalNameFullName| - [SimpleTestInClusterSupport] Time-limited test - Destroying 3 distributed objects in SimpleTestInClusterSupport.@After: [hz:impl:mapService/__jet.results, hz:impl:mapService/__jet.records, hz:impl:mapService/__sql.catalog]
01:17:27,748  INFO |createMappingFails_tableExistInAnotherDatabase_externalNameFullName| - [HazelcastTestSupport] Time-limited test - Shutting down node factory as @After action
01:17:27,748  WARN || - [EventService] hz.PostgresMappingJdbcSqlConnectorTest_vigilant_jemison.event-2 - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] Error while logging processing event
java.lang.UnsupportedOperationException: SQL catalog must never be cleared - MapEvent{entryEventType=CLEAR_ALL, member=Member [127.0.0.1]:5701 - ae3b4568-f4e9-4ea4-a7ec-09d038823e29, name='__sql.catalog', numberOfEntriesAffected=1}
	at com.hazelcast.jet.sql.impl.schema.AbstractSchemaStorage$EntryListenerAdapter.mapCleared(AbstractSchemaStorage.java:74) ~[classes/:?]
	at com.hazelcast.map.impl.MapListenerAdaptors.lambda$static$12(MapListenerAdaptors.java:132) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.map.impl.InternalMapListenerAdapter.onEvent(InternalMapListenerAdapter.java:56) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.map.impl.InternalMapListenerAdapter.onEvent(InternalMapListenerAdapter.java:35) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.map.impl.event.MapEventPublishingService.callListener(MapEventPublishingService.java:181) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.map.impl.event.MapEventPublishingService.dispatchMapEventData(MapEventPublishingService.java:135) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.map.impl.event.MapEventPublishingService.dispatchEvent(MapEventPublishingService.java:78) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.map.impl.event.MapEventPublishingService.dispatchEvent(MapEventPublishingService.java:49) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.map.impl.MapService.dispatchEvent(MapService.java:136) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.map.impl.MapService.dispatchEvent(MapService.java:103) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.spi.impl.eventservice.impl.EventProcessor.process(EventProcessor.java:63) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.spi.impl.eventservice.impl.RemoteEventProcessor.run(RemoteEventProcessor.java:48) [hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.internal.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:245) [hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.internal.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:228) [hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
01:17:27,748 ERROR || - [EventServiceImpl] hz.PostgresMappingJdbcSqlConnectorTest_competent_jemison.event-1 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] hz.PostgresMappingJdbcSqlConnectorTest_competent_jemison.event-1 caught an exception while processing:com.hazelcast.spi.impl.eventservice.impl.LocalEventDispatcher@53ff22d5
java.lang.UnsupportedOperationException: SQL catalog must never be cleared - MapEvent{entryEventType=CLEAR_ALL, member=Member [127.0.0.1]:5701 - ae3b4568-f4e9-4ea4-a7ec-09d038823e29 this, name='__sql.catalog', numberOfEntriesAffected=1}
	at com.hazelcast.jet.sql.impl.schema.AbstractSchemaStorage$EntryListenerAdapter.mapCleared(AbstractSchemaStorage.java:74) ~[classes/:?]
	at com.hazelcast.map.impl.MapListenerAdaptors.lambda$static$12(MapListenerAdaptors.java:132) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.map.impl.InternalMapListenerAdapter.onEvent(InternalMapListenerAdapter.java:56) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.map.impl.InternalMapListenerAdapter.onEvent(InternalMapListenerAdapter.java:35) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.map.impl.event.MapEventPublishingService.callListener(MapEventPublishingService.java:181) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.map.impl.event.MapEventPublishingService.dispatchMapEventData(MapEventPublishingService.java:135) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.map.impl.event.MapEventPublishingService.dispatchEvent(MapEventPublishingService.java:78) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.map.impl.event.MapEventPublishingService.dispatchEvent(MapEventPublishingService.java:49) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.map.impl.MapService.dispatchEvent(MapService.java:136) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.map.impl.MapService.dispatchEvent(MapService.java:103) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.spi.impl.eventservice.impl.LocalEventDispatcher.run(LocalEventDispatcher.java:64) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.internal.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:245) [hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.internal.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:228) [hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
BuildInfo right after createMappingFails_tableExistInAnotherDatabase_externalNameFullName(com.hazelcast.jet.sql.impl.connector.jdbc.postgres.PostgresMappingJdbcSqlConnectorTest): BuildInfo{version='5.4.0-SNAPSHOT', build='20231218', buildNumber=20231218, revision=f7656f4, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'createMappingFails_tableExistInAnotherDatabase_externalNameFullName(com.hazelcast.jet.sql.impl.connector.jdbc.postgres.PostgresMappingJdbcSqlConnectorTest):'
01:17:25, accumulated pauses: 123 ms, max pause: 31 ms, pauses over 1000 ms: 0


No metrics recorded during the test

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-postgres-11/34/

**Comment by olukas** [comment]
Failed again on _master_ with oracle-11 (postgres-13): https://jenkins.hazelcast.com/job/Hazelcast-master-postgres-13/34/testReport/com.hazelcast.jet.sql.impl.connector.jdbc.postgres/PostgresMappingJdbcSqlConnectorTest/

**Comment by olukas** [comment]
Test `com.hazelcast.jet.sql.impl.connector.jdbc.mysql.MySQLMappingJdbcSqlConnectorTest.createMappingFails_tableExistInAnotherDatabase_externalNameOnlyTableName` failed again on _master_ with oracle-11 (mysql-8.0) with the same exception: https://jenkins.hazelcast.com/job/Hazelcast-master-mysql-8.0/38/testReport/com.hazelcast.jet.sql.impl.connector.jdbc.mysql/MySQLMappingJdbcSqlConnectorTest/createMappingFails_tableExistInAnotherDatabase_externalNameOnlyTableName/

**Comment by olukas** [comment]
Test `com.hazelcast.jet.sql.impl.connector.jdbc.mysql.MySQLMappingJdbcSqlConnectorTest.createMappingFails_tableExistInAnotherDatabase_externalNameOnlyTableName` failed again on _master_ with:
- oracle-11 (mysql-5.7): https://jenkins.hazelcast.com/job/Hazelcast-master-mysql-5.7/39/testReport/com.hazelcast.jet.sql.impl.connector.jdbc.mysql/MySQLMappingJdbcSqlConnectorTest/createMappingFails_tableExistInAnotherDatabase_externalNameOnlyTableName/
- oracle-11 (mysql-8.0): 
  - https://jenkins.hazelcast.com/job/Hazelcast-master-mysql-8.0/39/testReport/com.hazelcast.jet.sql.impl.connector.jdbc.mysql/MySQLMappingJdbcSqlConnectorTest/createMappingFails_tableExistInAnotherDatabase_externalNameOnlyTableName/
  - https://jenkins.hazelcast.com/job/Hazelcast-master-mysql-8.0/40/testReport/com.hazelcast.jet.sql.impl.connector.jdbc.mysql/MySQLMappingJdbcSqlConnectorTest/createMappingFails_tableExistInAnotherDatabase_externalNameOnlyTableName/
- oracle-11 (mysql-8.2):
  - https://jenkins.hazelcast.com/job/Hazelcast-master-mysql-8.2/13/testReport/com.hazelcast.jet.sql.impl.connector.jdbc.mysql/MySQLMappingJdbcSqlConnectorTest/createMappingFails_tableExistInAnotherDatabase_externalNameOnlyTableName/
  - https://jenkins.hazelcast.com/job/Hazelcast-master-mysql-8.2/14/testReport/com.hazelcast.jet.sql.impl.connector.jdbc.mysql/MySQLMappingJdbcSqlConnectorTest/createMappingFails_tableExistInAnotherDatabase_externalNameOnlyTableName/

**Comment by olukas** [comment]
Test `com.hazelcast.jet.sql.impl.connector.jdbc.postgres.PostgresMappingJdbcSqlConnectorTest` failed again on _master_ with oracle-11 (force-offload): https://jenkins.hazelcast.com/job/Hazelcast-master-nightly-force-offload/80/testReport/com.hazelcast.jet.sql.impl.connector.jdbc.postgres/PostgresMappingJdbcSqlConnectorTest/

**Comment by olukas** [comment]
Seems to fail contantly.

**Comment by Patras3** [comment]
Recent test failure for reference:
Failed again on _master_ with oracle-17: https://jenkins.hazelcast.com/job/Hazelcast-master-postgres-13/40/testReport/com.hazelcast.jet.sql.impl.connector.jdbc.postgres/PostgresMappingJdbcSqlConnectorTest/createMappingFails_tableExistInAnotherDatabase_externalNameFullName/

**Comment by orcunc** [comment]
Closed by https://github.com/hazelcast/hazelcast-mono/pull/588
