### ISSUE TITLE
com.hazelcast.jet.sql_nightly.SqlSTSInnerNonEquiJoinFaultToleranceStressTest.stressTest[processingGuarantee:exactlyOnce, restartGraceful:true]

### ISSUE THREAD

**Issue by Patras3** [hazelcast/hazelcast#26182]
_5.3.z_ (commit ea353f696331004fcbc5aad701ec2d6d6069d98d)

Failed on ibm-8: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-IbmJDK8-nightly/114/testReport/junit/com.hazelcast.jet.sql_nightly/SqlSTSInnerNonEquiJoinFaultToleranceStressTest/stressTest_processingGuarantee_exactlyOnce__restartGraceful_true_/
<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: 
[Missing element: value-9903] 
Expecting actual not to be null
	at com.hazelcast.jet.sql_nightly.SqlSTSInnerEquiJoinFaultToleranceStressTest.stressTest(SqlSTSInnerEquiJoinFaultToleranceStressTest.java:241)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.lang.Thread.run(Thread.java:825)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-5.maintenance-IbmJDK8-nightly/114/

**Comment by Patras3** [comment]
Failed again on _master_ with oracle-11: https://jenkins.hazelcast.com/job/Hazelcast-master-OracleJDK11-nightly/978/testReport/com.hazelcast.jet.sql_nightly/SqlSTSInnerNonEquiJoinFaultToleranceStressTest/stressTest/

**Comment by Patras3** [comment]
Failed again on _5.3.z_ with ibm-8: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-IbmJDK8-nightly/119/testReport/junit/com.hazelcast.jet.sql_nightly/SqlSTSInnerNonEquiJoinFaultToleranceStressTest/stressTest_processingGuarantee_exactlyOnce__restartGraceful_true_/ but with timeout.

**Comment by Patras3** [comment]
Failed again on _5.3.z_ with ibm-8: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-IbmJDK8-nightly/121/testReport/com.hazelcast.jet.sql_nightly/SqlSTSInnerNonEquiJoinFaultToleranceStressTest/

**Comment by olukas** [comment]
Failed again on _5.3.z_ with IbmJDK8-nightly: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-IbmJDK8-nightly/123/testReport/com.hazelcast.jet.sql_nightly/SqlSTSInnerNonEquiJoinFaultToleranceStressTest/stressTest_processingGuarantee_exactlyOnce__restartGraceful_true_/

**Comment by Patras3** [comment]
Failed again on _5.3.z_ with oracle-8: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-OracleJDK8-nightly/130/testReport/junit/com.hazelcast.jet.sql_nightly/SqlSTSInnerNonEquiJoinFaultToleranceStressTest/stressTest_processingGuarantee_exactlyOnce__restartGraceful_true_/

**Comment by olukas** [comment]
Failed again on _5.3.z_ with OracleJDK8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-OracleJDK8-nightly/135/testReport/com.hazelcast.jet.sql_nightly/SqlSTSInnerNonEquiJoinFaultToleranceStressTest/stressTest_processingGuarantee_exactlyOnce__restartGraceful_true_/

**Comment by Patras3** [comment]
Failed again on _5.3.z_ with ibm-8: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-IbmJDK8-nightly/133/testReport/junit/com.hazelcast.jet.sql_nightly/SqlSTSInnerNonEquiJoinFaultToleranceStressTest/stressTest_processingGuarantee_exactlyOnce__restartGraceful_true_/

**Comment by sumnerib** [comment]
Failed again on _5.4.z_ with openj9-21: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-Openj9-21-nightly/7/testReport/com.hazelcast.jet.sql_nightly/SqlSTSInnerNonEquiJoinFaultToleranceStressTest/stressTest_processingGuarantee_exactlyOnce__restartGraceful_true_/

**Comment by Patras3** [comment]
This comment was automatically generated to summarize test results for the last 30 days.

```

For branch: master
Builds between : 2024-07-03 03:15 - 2024-07-31 03:15
Jobs: 9, Runs: 22, Passed: 22, Failed: 0, Skipped: 0, Fail Ratio: 0.00%
Run on:
+--------------------------------------------------+
| JDK        | PASSED | FAILED | SKIPPED |  RATIO  |
+--------------------------------------------------+
| oracle-17  |   3    |   0    |    0    |   0.00% |
| unknown    |   5    |   0    |    0    |   0.00% |
| zing-21    |   3    |   0    |    0    |   0.00% |
| openj9-21  |   3    |   0    |    0    |   0.00% |
| oracle-21  |   2    |   0    |    0    |   0.00% |
| zing-17    |   2    |   0    |    0    |   0.00% |
| openjdk-17 |   4    |   0    |    0    |   0.00% |
+--------------------------------------------------+
Note: Passing since 2024-07-05 03:14

Builds Timeline:
2024-07-31 03:15 - PASSED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK17-nightly-Esxi7/99/testReport/com.hazelcast.jet.sql_nightly/SqlSTSInnerNonEquiJoinFaultToleranceStressTest/stressTest[processingGuarantee:exactlyOnce, restartGraceful:true]/
2024-07-31 03:08 - PASSED (oracle-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-OracleJDK21-nightly/28/testReport/com.hazelcast.jet.sql_nightly/SqlSTSInnerNonEquiJoinFaultToleranceStressTest/stressTest[processingGuarantee:exactlyOnce, restartGraceful:true]/
2024-07-29 03:12 - PASSED (openj9-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-Openj9-21-nightly/29/testReport/com.hazelcast.jet.sql_nightly/SqlSTSInnerNonEquiJoinFaultToleranceStressTest/stressTest[processingGuarantee:exactlyOnce, restartGraceful:true]/
2024-07-28 18:11 - PASSED (zing-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK21-nightly/32/testReport/com.hazelcast.jet.sql_nightly/SqlSTSInnerNonEquiJoinFaultToleranceStressTest/stressTest[processingGuarantee:exactlyOnce, restartGraceful:true]/
2024-07-28 12:12 - PASSED (oracle-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-nightly-force-offload/111/testReport/com.hazelcast.jet.sql_nightly/SqlSTSInnerNonEquiJoinFaultToleranceStressTest/stressTest[processingGuarantee:exactlyOnce, restartGraceful:true]/
2024-07-27 00:07 - PASSED (oracle-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-nightly-little-endian/89/testReport/com.hazelcast.jet.sql_nightly/SqlSTSInnerNonEquiJoinFaultToleranceStressTest/stressTest[processingGuarantee:exactlyOnce, restartGraceful:true]/
2024-07-26 18:06 - PASSED (zing-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK17-nightly/91/testReport/com.hazelcast.jet.sql_nightly/SqlSTSInnerNonEquiJoinFaultToleranceStressTest/stressTest[processingGuarantee:exactlyOnce, restartGraceful:true]/
2024-07-26 03:14 - PASSED (openjdk-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-ZuluJDK17-nightly/128/testReport/com.hazelcast.jet.sql_nightly/SqlSTSInnerNonEquiJoinFaultToleranceStressTest/stressTest[processingGuarantee:exactlyOnce, restartGraceful:true]/
2024-07-24 21:52 - PASSED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-CorrettoJDK17-arm64-nightly/26/testReport/com.hazelcast.jet.sql_nightly/SqlSTSInnerNonEquiJoinFaultToleranceStressTest/stressTest[processingGuarantee:exactlyOnce, restartGraceful:true]/
2024-07-24 03:15 - PASSED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK17-nightly-Esxi7/98/testReport/com.hazelcast.jet.sql_nightly/SqlSTSInnerNonEquiJoinFaultToleranceStressTest/stressTest[processingGuarantee:exactlyOnce, restartGraceful:true]/
2024-07-24 03:08 - PASSED (oracle-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-OracleJDK21-nightly/27/testReport/com.hazelcast.jet.sql_nightly/SqlSTSInnerNonEquiJoinFaultToleranceStressTest/stressTest[processingGuarantee:exactlyOnce, restartGraceful:true]/
2024-07-22 03:12 - PASSED (openj9-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-Openj9-21-nightly/28/testReport/com.hazelcast.jet.sql_nightly/SqlSTSInnerNonEquiJoinFaultToleranceStressTest/stressTest[processingGuarantee:exactlyOnce, restartGraceful:true]/
2024-07-21 18:11 - PASSED (zing-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK21-nightly/31/testReport/com.hazelcast.jet.sql_nightly/SqlSTSInnerNonEquiJoinFaultToleranceStressTest/stressTest[processingGuarantee:exactlyOnce, restartGraceful:true]/
2024-07-20 00:07 - PASSED (oracle-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-nightly-little-endian/88/testReport/com.hazelcast.jet.sql_nightly/SqlSTSInnerNonEquiJoinFaultToleranceStressTest/stressTest[processingGuarantee:exactlyOnce, restartGraceful:true]/
2024-07-19 18:06 - PASSED (zing-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK17-nightly/90/testReport/com.hazelcast.jet.sql_nightly/SqlSTSInnerNonEquiJoinFaultToleranceStressTest/stressTest[processingGuarantee:exactlyOnce, restartGraceful:true]/
2024-07-19 03:14 - PASSED (openjdk-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-ZuluJDK17-nightly/127/testReport/com.hazelcast.jet.sql_nightly/SqlSTSInnerNonEquiJoinFaultToleranceStressTest/stressTest[processingGuarantee:exactlyOnce, restartGraceful:true]/
2024-07-12 03:14 - PASSED (openjdk-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-ZuluJDK17-nightly/126/testReport/com.hazelcast.jet.sql_nightly/SqlSTSInnerNonEquiJoinFaultToleranceStressTest/stressTest[processingGuarantee:exactlyOnce, restartGraceful:true]/
2024-07-10 09:10 - PASSED (zing-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK21-nightly/29/testReport/com.hazelcast.jet.sql_nightly/SqlSTSInnerNonEquiJoinFaultToleranceStressTest/stressTest[processingGuarantee:exactlyOnce, restartGraceful:true]/
2024-07-10 03:15 - PASSED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK17-nightly-Esxi7/96/testReport/com.hazelcast.jet.sql_nightly/SqlSTSInnerNonEquiJoinFaultToleranceStressTest/stressTest[processingGuarantee:exactlyOnce, restartGraceful:true]/
2024-07-08 03:12 - PASSED (openj9-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-Openj9-21-nightly/26/testReport/com.hazelcast.jet.sql_nightly/SqlSTSInnerNonEquiJoinFaultToleranceStressTest/stressTest[processingGuarantee:exactlyOnce, restartGraceful:true]/
2024-07-05 03:14 - FIXED (openjdk-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-ZuluJDK17-nightly/125/testReport/com.hazelcast.jet.sql_nightly/SqlSTSInnerNonEquiJoinFaultToleranceStressTest/stressTest[processingGuarantee:exactlyOnce, restartGraceful:true]/
2024-07-03 03:15 - PASSED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK17-nightly-Esxi7/95/testReport/com.hazelcast.jet.sql_nightly/SqlSTSInnerNonEquiJoinFaultToleranceStressTest/stressTest[processingGuarantee:exactlyOnce, restartGraceful:true]/

----------------------------------------

For branch: 5.5.z
Builds between : 2024-07-31 18:08 - 2024-07-31 18:08
Jobs: 1, Runs: 1, Passed: 1, Failed: 0, Skipped: 0, Fail Ratio: 0.00%
Run on:
+--------------------------------------------------+
| JDK        | PASSED | FAILED | SKIPPED |  RATIO  |
+--------------------------------------------------+
| openjdk-17 |   1    |   0    |    0    |   0.00% |
+--------------------------------------------------+

Builds Timeline:
2024-07-31 18:08 - PASSED (openjdk-17):
    https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-ZuluJDK17-nightly/128/testReport/com.hazelcast.jet.sql_nightly/SqlSTSInnerNonEquiJoinFaultToleranceStressTest/stressTest[processingGuarantee:exactlyOnce, restartGraceful:true]/

----------------------------------------

For branch: 5.4.z
Builds between : 2024-07-03 18:08 - 2024-07-29 18:02
Jobs: 3, Runs: 12, Passed: 11, Failed: 1, Skipped: 0, Fail Ratio: 8.33%
Run on:
+--------------------------------------------------+
| JDK        | PASSED | FAILED | SKIPPED |  RATIO  |
+--------------------------------------------------+
| oracle-21  |   3    |   1    |    0    |  25.00% |
| openjdk-17 |   4    |   0    |    0    |   0.00% |
| openj9-21  |   4    |   0    |    0    |   0.00% |
+--------------------------------------------------+
Note: Passing since 2024-07-22 18:02

Builds Timeline:
2024-07-29 18:02 - PASSED (oracle-21):
    https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-OracleJDK21-nightly/14/testReport/com.hazelcast.jet.sql_nightly/SqlSTSInnerNonEquiJoinFaultToleranceStressTest/stressTest[processingGuarantee:exactlyOnce, restartGraceful:true]/
2024-07-27 18:06 - PASSED (openj9-21):
    https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-Openj9-21-nightly/13/testReport/com.hazelcast.jet.sql_nightly/SqlSTSInnerNonEquiJoinFaultToleranceStressTest/stressTest[processingGuarantee:exactlyOnce, restartGraceful:true]/
2024-07-24 18:08 - PASSED (openjdk-17):
    https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-ZuluJDK17-nightly/127/testReport/com.hazelcast.jet.sql_nightly/SqlSTSInnerNonEquiJoinFaultToleranceStressTest/stressTest[processingGuarantee:exactlyOnce, restartGraceful:true]/
2024-07-22 18:02 - FIXED (oracle-21):
    https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-OracleJDK21-nightly/13/testReport/com.hazelcast.jet.sql_nightly/SqlSTSInnerNonEquiJoinFaultToleranceStressTest/stressTest[processingGuarantee:exactlyOnce, restartGraceful:true]/
2024-07-20 18:06 - PASSED (openj9-21):
    https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-Openj9-21-nightly/12/testReport/com.hazelcast.jet.sql_nightly/SqlSTSInnerNonEquiJoinFaultToleranceStressTest/stressTest[processingGuarantee:exactlyOnce, restartGraceful:true]/
2024-07-17 18:08 - PASSED (openjdk-17):
    https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-ZuluJDK17-nightly/126/testReport/com.hazelcast.jet.sql_nightly/SqlSTSInnerNonEquiJoinFaultToleranceStressTest/stressTest[processingGuarantee:exactlyOnce, restartGraceful:true]/
2024-07-15 18:02 - REGRESSION (oracle-21):
    https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-OracleJDK21-nightly/12/testReport/com.hazelcast.jet.sql_nightly/SqlSTSInnerNonEquiJoinFaultToleranceStressTest/stressTest[processingGuarantee:exactlyOnce, restartGraceful:true]/
2024-07-13 18:06 - PASSED (openj9-21):
    https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-Openj9-21-nightly/11/testReport/com.hazelcast.jet.sql_nightly/SqlSTSInnerNonEquiJoinFaultToleranceStressTest/stressTest[processingGuarantee:exactlyOnce, restartGraceful:true]/
2024-07-10 18:08 - PASSED (openjdk-17):
    https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-ZuluJDK17-nightly/125/testReport/com.hazelcast.jet.sql_nightly/SqlSTSInnerNonEquiJoinFaultToleranceStressTest/stressTest[processingGuarantee:exactlyOnce, restartGraceful:true]/
2024-07-08 18:02 - PASSED (oracle-21):
    https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-OracleJDK21-nightly/11/testReport/com.hazelcast.jet.sql_nightly/SqlSTSInnerNonEquiJoinFaultToleranceStressTest/stressTest[processingGuarantee:exactlyOnce, restartGraceful:true]/
2024-07-06 18:06 - PASSED (openj9-21):
    https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-Openj9-21-nightly/10/testReport/com.hazelcast.jet.sql_nightly/SqlSTSInnerNonEquiJoinFaultToleranceStressTest/stressTest[processingGuarantee:exactlyOnce, restartGraceful:true]/
2024-07-03 18:08 - PASSED (openjdk-17):
    https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-ZuluJDK17-nightly/124/testReport/com.hazelcast.jet.sql_nightly/SqlSTSInnerNonEquiJoinFaultToleranceStressTest/stressTest[processingGuarantee:exactlyOnce, restartGraceful:true]/

----------------------------------------

For branch: 5.3.z
Builds between : 2024-07-08 03:11 - 2024-07-29 03:11
Jobs: 1, Runs: 5, Passed: 3, Failed: 2, Skipped: 0, Fail Ratio: 40.00%
Run on:
+------------------------------------------------+
| JDK      | PASSED | FAILED | SKIPPED |  RATIO  |
+------------------------------------------------+
| oracle-8 |   3    |   2    |    0    |  40.00% |
+------------------------------------------------+
Note: Failing since 2024-07-22 03:11

Builds Timeline:
2024-07-29 03:11 - REGRESSION (oracle-8):
    https://jenkins.hazelcast.com/job/Hazelcast-5.3.z-OracleJDK8-nightly/13/testReport/com.hazelcast.jet.sql_nightly/SqlSTSInnerNonEquiJoinFaultToleranceStressTest/stressTest[processingGuarantee:exactlyOnce, restartGraceful:true]/
2024-07-29 03:11 - REGRESSION (oracle-8):
    https://jenkins.hazelcast.com/job/Hazelcast-5.3.z-OracleJDK8-nightly/13/testReport/com.hazelcast.jet.sql_nightly/SqlSTSInnerNonEquiJoinFaultToleranceStressTest/stressTest[processingGuarantee:exactlyOnce, restartGraceful:true]/
2024-07-22 03:11 - PASSED (oracle-8):
    https://jenkins.hazelcast.com/job/Hazelcast-5.3.z-OracleJDK8-nightly/12/testReport/com.hazelcast.jet.sql_nightly/SqlSTSInnerNonEquiJoinFaultToleranceStressTest/stressTest[processingGuarantee:exactlyOnce, restartGraceful:true]/
2024-07-15 03:11 - PASSED (oracle-8):
    https://jenkins.hazelcast.com/job/Hazelcast-5.3.z-OracleJDK8-nightly/11/testReport/com.hazelcast.jet.sql_nightly/SqlSTSInnerNonEquiJoinFaultToleranceStressTest/stressTest[processingGuarantee:exactlyOnce, restartGraceful:true]/
2024-07-08 03:11 - FIXED (oracle-8):
    https://jenkins.hazelcast.com/job/Hazelcast-5.3.z-OracleJDK8-nightly/10/testReport/com.hazelcast.jet.sql_nightly/SqlSTSInnerNonEquiJoinFaultToleranceStressTest/stressTest[processingGuarantee:exactlyOnce, restartGraceful:true]/

----------------------------------------
```

**Comment by olukas** [comment]
Closing the test failure - it doesn't seem to be related to `master` or the latest maintenance stream `5.5.z`. Feel free to reopen test failure if it occurs on `master` or on the latest maintenance stream.
