### ISSUE TITLE
com.hazelcast.map.EvictionTest.testEvictionLRU_statisticsDisabled

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#26198]
_5.3.z_ (commit d1ee0372a10dc5f2ebf18f71d9eeaf8bf15e1613)

Failed on openj9-17: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-Openj9-17/96/testReport/com.hazelcast.map/EvictionTest/

Failed in variants:
- `com.hazelcast.map.EvictionTest.testEvictionLRU_statisticsDisabled[statisticsEnabled:true, perEntryStatsEnabled:true]`
- `com.hazelcast.map.EvictionTest.testEvictionLRU_statisticsDisabled[statisticsEnabled:false, perEntryStatsEnabled:true]`
- `com.hazelcast.map.EvictionTest.testEvictionLRU_statisticsDisabled[statisticsEnabled:true, perEntryStatsEnabled:false]`
- `com.hazelcast.map.EvictionTest.testEvictionLRU_statisticsDisabled[statisticsEnabled:false, perEntryStatsEnabled:false]`

<details><summary>Stacktrace:</summary>

```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.base/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.manageParking(AbstractInvocationFuture.java:694)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:616)
	at com.hazelcast.map.impl.proxy.MapProxySupport.invokeOperation(MapProxySupport.java:517)
	at com.hazelcast.map.impl.proxy.MapProxySupport.putInternal(MapProxySupport.java:445)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.put(MapProxyImpl.java:138)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.put(MapProxyImpl.java:128)
	at com.hazelcast.map.EvictionTest.testEvictionLRU_statisticsDisabled(EvictionTest.java:581)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:858)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-5.maintenance-Openj9-17/96/

**Comment by olukas** [comment]
Closing the test failure - it doesn't seem to be related to `master` or the latest maintenance stream `5.5.z` and it hasn't fail in the last 3 months. Feel free to reopen test failure if it occurs on `master` or on the latest maintenance stream.
