### ISSUE TITLE
com.hazelcast.jet.sql.impl.connector.map.index.SqlIndexTest.(?)

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#26190]
_master_ (commit 16069feefba3dc70102fc314e3f5c97d570d94b5)

Failed on Windows - MicrosoftJDK17: https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK17/94/testReport/com.hazelcast.jet.sql.impl.connector.map.index/SqlIndexTest/___/

**It also breaks some tests which runs after this test.** 

<details><summary>Stacktrace:</summary>

```
org.junit.runners.model.TestTimedOutException: test timed out after 900 seconds
	at java.base@17.0.7/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@17.0.7/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252)
	at java.base@17.0.7/java.util.concurrent.FutureTask.awaitDone(FutureTask.java:444)
	at java.base@17.0.7/java.util.concurrent.FutureTask.get(FutureTask.java:203)
	at app//com.hazelcast.test.FailOnTimeoutStatement.getResult(FailOnTimeoutStatement.java:80)
	at app//com.hazelcast.test.FailOnTimeoutStatement.evaluate(FailOnTimeoutStatement.java:58)
	at app//com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:365)
	at app//org.assertj.core.api.SoftAssertionsStatement$1.evaluate(SoftAssertionsStatement.java:41)
	at app//com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37)
	at app//com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:104)
	at app//com.hazelcast.test.metrics.MetricsRule$1.evaluate(MetricsRule.java:63)
	at app//com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:53)
	at app//com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:32)
	at app//com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:41)
	at app//com.hazelcast.test.OverridePropertyRule$1.evaluate(OverridePropertyRule.java:69)
	at java.base@17.0.7/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base@17.0.7/java.lang.Thread.run(Thread.java:833)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-Windows-MicrosoftJDK17/94/

**Comment by olukas** [comment]
Failed again on _master_ with:
- Windows - MicrosoftJDK17: https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK17/96/testReport/com.hazelcast.jet.sql.impl.connector.map.index/SqlIndexTest/___/
- Windows - OracleJDK11: https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-OracleJDK11/480/testReport/com.hazelcast.jet.sql.impl.connector.map.index/SqlIndexTest/___/

**Comment by k-jamroz** [comment]
Hopefully will improve after https://github.com/hazelcast/hazelcast-mono/pull/798
