### ISSUE TITLE
com.hazelcast.jet.sql_nightly.SqlSTSInnerNonEquiJoinFaultToleranceStressTest.stressTest

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#26197]
_5.3.z_ (commit d1ee0372a10dc5f2ebf18f71d9eeaf8bf15e1613)

Failed on ibm-8: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-IbmJDK8-nightly/117/testReport/com.hazelcast.jet.sql_nightly/SqlSTSInnerNonEquiJoinFaultToleranceStressTest/stressTest_processingGuarantee_atLeastOnce__restartGraceful_true_/

Failed in variant `[processingGuarantee:atLeastOnce, restartGraceful:true]`.

<details><summary>Stacktrace:</summary>

```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:349)
	at com.hazelcast.internal.util.concurrent.BackoffIdleStrategy.idle(BackoffIdleStrategy.java:84)
	at com.hazelcast.jet.sql.impl.QueryResultProducerImpl$InternalIterator.hasNextWait(QueryResultProducerImpl.java:164)
	at com.hazelcast.jet.sql.impl.QueryResultProducerImpl$InternalIterator.hasNext(QueryResultProducerImpl.java:140)
	at com.hazelcast.jet.sql.impl.SqlResultImpl$RowToSqlRowIterator.hasNext(SqlResultImpl.java:127)
	at com.hazelcast.jet.sql_nightly.SqlSTSInnerEquiJoinFaultToleranceStressTest.stressTest(SqlSTSInnerEquiJoinFaultToleranceStressTest.java:209)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.lang.Thread.run(Thread.java:825)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-5.maintenance-IbmJDK8-nightly/117/

**Comment by olukas** [comment]
Failed again on _5.3.z_ with oracle-8: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-OracleJDK8-nightly/120/testReport/com.hazelcast.jet.sql_nightly/SqlSTSInnerNonEquiJoinFaultToleranceStressTest/stressTest_processingGuarantee_atLeastOnce__restartGraceful_true_/

**Comment by olukas** [comment]
Failed again on _5.3.z_ with OracleJDK8: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-OracleJDK8-nightly/126/testReport/com.hazelcast.jet.sql_nightly/SqlSTSInnerNonEquiJoinFaultToleranceStressTest/stressTest_processingGuarantee_atLeastOnce__restartGraceful_true_/

**Comment by sumnerib** [comment]
Failed again on _5.3.z_ with oracle-8: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-OracleJDK8-nightly/128/testReport/junit/com.hazelcast.jet.sql_nightly/SqlSTSInnerNonEquiJoinFaultToleranceStressTest/stressTest_processingGuarantee_atLeastOnce__restartGraceful_true_/

**Comment by AleksPeychev** [comment]
Failed again on _master_ with oracle-21: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-OracleJDK21-nightly/6/testReport/junit/com.hazelcast.jet.sql_nightly/SqlSTSInnerEquiJoinFaultToleranceStressTest/stressTest_processingGuarantee_atLeastOnce__restartGraceful_true_/

**Comment by sumnerib** [comment]
Failed again on _5.3.z_ with openjdk-17: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-ZuluJDK17-nightly/112/testReport/junit/com.hazelcast.jet.sql_nightly/SqlSTSInnerEquiJoinFaultToleranceStressTest/

Different stacktrace:

```
java.lang.NullPointerException: Cannot invoke "java.lang.Thread.join()" because "this.kafkaFeedThread" is null
	at com.hazelcast.jet.sql_nightly.SqlSTSInnerEquiJoinFaultToleranceStressTest.after(SqlSTSInnerEquiJoinFaultToleranceStressTest.java:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:381)
	at com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37)
	at com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:104)
	at com.hazelcast.test.metrics.MetricsRule$1.evaluate(MetricsRule.java:63)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:50)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:29)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:41)
	at com.hazelcast.test.OverridePropertyRule$1.evaluate(OverridePropertyRule.java:66)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by Patras3** [comment]
Failed again on _5.3.z_ with oracle-8: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-OracleJDK8-nightly/137/testReport/junit/com.hazelcast.jet.sql_nightly/SqlSTSInnerNonEquiJoinFaultToleranceStressTest/stressTest_processingGuarantee_atLeastOnce__restartGraceful_true_/

**Comment by olukas** [comment]
Closing the test failure - it doesn't seem to be related to `master` or the latest maintenance stream `5.5.z` and it hasn't fail in the last 3 months. Feel free to reopen test failure if it occurs on `master` or on the latest maintenance stream.
