### ISSUE TITLE
com.hazelcast.jet.kafka.connect.KafkaConnectIntegrationTest.windowing_withNativeTimestamps_should_fail_when_records_without_native_timestamps

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#26205]
_5.3.z_ (commit d1ee0372a10dc5f2ebf18f71d9eeaf8bf15e1613)

Failed on oracle-17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-sonar/315/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectIntegrationTest/windowing_withNativeTimestamps_should_fail_when_records_without_native_timestamps/
<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: 

Expecting actual throwable to be an instance of:
  java.util.concurrent.CompletionException
but was:
  com.hazelcast.jet.JetException: Job resource upload failed
	at com.hazelcast.jet.impl.JobRepository.uploadJobResources(JobRepository.java:261)
	at com.hazelcast.jet.impl.AbstractJetInstance.uploadResources(AbstractJetInstance.java:344)
	at com.hazelcast.jet.impl.AbstractJetInstance.newJobInt(AbstractJetInstance.java:142)
	...(19 remaining lines not displayed - this can be changed with Assertions.setMaxStackTraceElementsDisplayed)
	at com.hazelcast.jet.kafka.connect.KafkaConnectIntegrationTest.windowing_withNativeTimestamps_should_fail_when_records_without_native_timestamps(KafkaConnectIntegrationTest.java:166)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-5.maintenance-sonar/315/

**Comment by Patras3** [comment]
This comment was automatically generated to summarize test results for the last 30 days.

```

For branch: 5.3.z
Builds between : 2024-07-05 21:09 - 2024-07-26 21:09
Jobs: 1, Runs: 4, Passed: 4, Failed: 0, Skipped: 0, Fail Ratio: 0.00%
Run on:
+------------------------------------------------+
| JDK      | PASSED | FAILED | SKIPPED |  RATIO  |
+------------------------------------------------+
| oracle-8 |   4    |   0    |    0    |   0.00% |
+------------------------------------------------+

Builds Timeline:
2024-07-26 21:09 - PASSED (oracle-8):
    https://jenkins.hazelcast.com/job/Hazelcast-5.3.z-OracleJDK8/13/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectIntegrationTest/windowing_withNativeTimestamps_should_fail_when_records_without_native_timestamps/
2024-07-19 21:09 - PASSED (oracle-8):
    https://jenkins.hazelcast.com/job/Hazelcast-5.3.z-OracleJDK8/12/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectIntegrationTest/windowing_withNativeTimestamps_should_fail_when_records_without_native_timestamps/
2024-07-12 21:09 - PASSED (oracle-8):
    https://jenkins.hazelcast.com/job/Hazelcast-5.3.z-OracleJDK8/11/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectIntegrationTest/windowing_withNativeTimestamps_should_fail_when_records_without_native_timestamps/
2024-07-05 21:09 - PASSED (oracle-8):
    https://jenkins.hazelcast.com/job/Hazelcast-5.3.z-OracleJDK8/10/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectIntegrationTest/windowing_withNativeTimestamps_should_fail_when_records_without_native_timestamps/

----------------------------------------
```

**Comment by olukas** [comment]
Closing the test failure - it doesn't seem to be related to `master` or the latest maintenance stream `5.5.z` and it hasn't fail in the last 3 months. Feel free to reopen test failure if it occurs on `master` or on the latest maintenance stream.
