### ISSUE TITLE
com.hazelcast.cp.internal.session.SessionManagerServiceTest

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#26200]
_master_ (commit d42b2e0ccd5388e4964d007650a0dd5c3131476c)

Failed on openj9-11: https://jenkins.hazelcast.com/job/Hazelcast-master-Openj9-11/163/testReport/com.hazelcast.cp.internal.session/SessionManagerServiceTest/

Following tests failed:
- `com.hazelcast.cp.internal.session.SessionManagerServiceTest.acquireSession_returnsTheExistingSession_whenSessionInUse`
- `com.hazelcast.cp.internal.session.SessionManagerServiceTest.sessionHeartbeatsAreSent_whenSessionInUse`
- `com.hazelcast.cp.internal.session.SessionManagerServiceTest.sessionHeartbeatsAreNotSent_whenSessionReleased`

<details><summary>Stacktrace for sessionHeartbeatsAreSent_whenSessionInUse and sessionHeartbeatsAreNotSent_whenSessionReleased:</summary>

```
Wanted but not invoked:
proxySessionManagerService.heartbeat(
    CPGroupId{name='group', seed=0, groupId=21},
    1L
);
-> at com.hazelcast.cp.internal.session.ProxySessionManagerService.heartbeat(ProxySessionManagerService.java:79)

However, there were exactly 4 interactions with this mock:
proxySessionManagerService.acquireSession(
    CPGroupId{name='group', seed=0, groupId=21}
);
-> at com.hazelcast.cp.internal.session.AbstractProxySessionManagerTest.sessionHeartbeatsAreSent_whenSessionInUse(AbstractProxySessionManagerTest.java:141)

proxySessionManagerService.requestNewSession(
    CPGroupId{name='group', seed=0, groupId=21}
);
-> at com.hazelcast.cp.internal.session.AbstractProxySessionManager.createNewSession(AbstractProxySessionManager.java:215)

proxySessionManagerService.scheduleWithRepetition(
    com.hazelcast.cp.internal.session.AbstractProxySessionManager$HeartbeatTask@c7dccc5,
    1000L,
    MILLISECONDS
);
-> at com.hazelcast.cp.internal.session.AbstractProxySessionManager.scheduleHeartbeatTask(AbstractProxySessionManager.java:235)

proxySessionManagerService.invalidateSession(
    CPGroupId{name='group', seed=0, groupId=21},
    1L
);
-> at com.hazelcast.cp.internal.session.AbstractProxySessionManager$HeartbeatTask.lambda$run$0(AbstractProxySessionManager.java:322)


	at com.hazelcast.cp.internal.session.ProxySessionManagerService.heartbeat(ProxySessionManagerService.java:79)
	at com.hazelcast.cp.internal.session.AbstractProxySessionManagerTest.lambda$sessionHeartbeatsAreSent_whenSessionInUse$3(AbstractProxySessionManagerTest.java:147)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1186)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1291)
	at com.hazelcast.cp.internal.session.AbstractProxySessionManagerTest.sessionHeartbeatsAreSent_whenSessionInUse(AbstractProxySessionManagerTest.java:147)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:840)

```
</details>

<details><summary>Stacktrace for acquireSession_returnsTheExistingSession_whenSessionInUse:</summary>

```
java.lang.AssertionError: expected:<1> but was:<2>
	at com.hazelcast.cp.internal.session.AbstractProxySessionManagerTest.lambda$acquireSession_returnsTheExistingSession_whenSessionInUse$7(AbstractProxySessionManagerTest.java:176)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueAllTheTime(HazelcastTestSupport.java:1164)
	at com.hazelcast.cp.internal.session.AbstractProxySessionManagerTest.acquireSession_returnsTheExistingSession_whenSessionInUse(AbstractProxySessionManagerTest.java:176)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:840)
```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-Openj9-11/163/

**Comment by olukas** [comment]
Closing the test failure - it doesn't seem to be related to `master` or the latest maintenance stream `5.5.z` and it hasn't fail in the last 3 months. Feel free to reopen test failure if it occurs on `master` or on the latest maintenance stream.
