### ISSUE TITLE
com.hazelcast.jet.kafka.connect.KafkaConnectSQSIntegrationTest.testReadFromSQSConnector [HZ-4177]

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hazelcast#26211]
_master_ (commit ac5fb8ec9f5a95614154c5aa3c55672ab458f633)
Failed on OpenJDK17: https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK17-nightly-Esxi7/66/testReport/junit/com.hazelcast.jet.kafka.connect/KafkaConnectSQSIntegrationTest/testReadFromSQSConnector/

<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: Job was expected to complete with AssertionCompletedException, but completed with: com.hazelcast.jet.JetException: Exception in ProcessorTasklet{0b10-c641-b980-0001/assertCollectedEventually#0}: java.lang.AssertionError: java.lang.AssertionError: expected:<1000> but was:<466>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at com.hazelcast.jet.kafka.connect.KafkaConnectSQSIntegrationTest.testReadFromSQSConnector(KafkaConnectSQSIntegrationTest.java:129)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:840)

```

</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-OpenJDK17-nightly-Esxi7/66/

**Comment by sumnerib** [comment]
Failed again on _master_ with oracle-11: https://jenkins.hazelcast.com/job/Hazelcast-master-OracleJDK11-nightly/982/testReport/junit/com.hazelcast.jet.kafka.connect/KafkaConnectSQSIntegrationTest/testReadFromSQSConnector/

**Comment by Patras3** [comment]
Failed again on _master_ with oracle-17: https://jenkins.hazelcast.com/job/Hazelcast-master-sonar/372/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectSQSIntegrationTest/testReadFromSQSConnector/

**Comment by orcunc** [comment]
Closed by https://github.com/hazelcast/hazelcast-mono/pull/407
