### ISSUE TITLE
com.hazelcast.client.config failures on Windows [HZ-4255]

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hazelcast#26214]
_master_ (commit 824a51e3eea5d9750964b74196e5b92a4a47b7dc)
Failed on Windows - MicrosoftJDK11: https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK11/100/testReport/junit/com.hazelcast.client.config/

[com.hazelcast.client.config.XmlClientConfigImportVariableReplacementTest.testImportResourceWithNestedImportsAndProperties](https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK11/lastSuccessfulBuild/testReport/junit/com.hazelcast.client.config/XmlClientConfigImportVariableReplacementTest/testImportResourceWithNestedImportsAndProperties/)
[com.hazelcast.client.config.XmlClientConfigImportVariableReplacementTest.testImportResourceWithNestedImports](https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK11/lastSuccessfulBuild/testReport/junit/com.hazelcast.client.config/XmlClientConfigImportVariableReplacementTest/testImportResourceWithNestedImports/)
[com.hazelcast.config.XmlConfigImportVariableReplacementTest.testImportWithVariableReplacementAsSubstring](https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK11/lastSuccessfulBuild/testReport/junit/com.hazelcast.config/XmlConfigImportVariableReplacementTest/testImportWithVariableReplacementAsSubstring/)
[com.hazelcast.config.XmlConfigImportVariableReplacementTest.testMapConfigFromMainAndImportedFile](https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK11/lastSuccessfulBuild/testReport/junit/com.hazelcast.config/XmlConfigImportVariableReplacementTest/testMapConfigFromMainAndImportedFile/)
[com.hazelcast.config.XmlConfigImportVariableReplacementTest.testImportResourceWithNestedImports](https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK11/lastSuccessfulBuild/testReport/junit/com.hazelcast.config/XmlConfigImportVariableReplacementTest/testImportResourceWithNestedImports/)
[com.hazelcast.config.XmlConfigImportVariableReplacementTest.testImportOverlappingMapConfigFromFile](https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK11/lastSuccessfulBuild/testReport/junit/com.hazelcast.config/XmlConfigImportVariableReplacementTest/testImportOverlappingMapConfigFromFile/)
[com.hazelcast.config.XmlConfigImportVariableReplacementTest.testImportResourceWithNestedImportsAndProperties](https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK11/lastSuccessfulBuild/testReport/junit/com.hazelcast.config/XmlConfigImportVariableReplacementTest/testImportResourceWithNestedImportsAndProperties/)
[com.hazelcast.config.XmlConfigImportVariableReplacementTest.testReplaceVariablesWithUrlConfig](https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK11/lastSuccessfulBuild/testReport/junit/com.hazelcast.config/XmlConfigImportVariableReplacementTest/testReplaceVariablesWithUrlConfig/)
[com.hazelcast.config.YamlConfigImportVariableReplacementTest.testReplaceVariablesWithUrlConfig](https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK11/lastSuccessfulBuild/testReport/junit/com.hazelcast.config/YamlConfigImportVariableReplacementTest/testReplaceVariablesWithUrlConfig/)

<details><summary>Stacktrace:</summary>

```
com.hazelcast.config.InvalidConfigurationException: Failed to load resource: file:///C:\Jenkins\workspace\Hazelcast-master-Windows-MicrosoftJDK11\hazelcast\config-replacer.xml
	at com.hazelcast.config.AbstractXmlConfigBuilder.replaceImports(AbstractXmlConfigBuilder.java:147)
	at com.hazelcast.config.AbstractXmlConfigBuilder.replaceImports(AbstractXmlConfigBuilder.java:155)
	at com.hazelcast.config.AbstractXmlConfigBuilder.process(AbstractXmlConfigBuilder.java:99)
	at com.hazelcast.client.config.XmlClientConfigBuilder.parseAndBuildConfig(XmlClientConfigBuilder.java:171)
	at com.hazelcast.client.config.XmlClientConfigBuilder.build(XmlClientConfigBuilder.java:154)
	at com.hazelcast.client.config.XmlClientConfigBuilder.build(XmlClientConfigBuilder.java:147)
	at com.hazelcast.client.config.XmlClientConfigBuilder.build(XmlClientConfigBuilder.java:142)
	at com.hazelcast.client.config.XmlClientConfigBuilderTest.buildConfig(XmlClientConfigBuilderTest.java:873)
	at com.hazelcast.client.config.XmlClientConfigImportVariableReplacementTest.testImportResourceWithNestedImportsAndProperties(XmlClientConfigImportVariableReplacementTest.java:161)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:829)

```
</details>

<details><summary>Standard output:</summary>

```
Started Running Test: testImportResourceWithNestedImportsAndProperties
18:27:47,516  INFO |testImportResourceWithNestedImportsAndProperties| - [HazelcastTestSupport] main - Shutting down node factory as @After action
BuildInfo right after testImportResourceWithNestedImportsAndProperties(com.hazelcast.client.config.XmlClientConfigImportVariableReplacementTest): BuildInfo{version='5.4.0-SNAPSHOT', build='20240111', buildNumber=20240111, revision=824a51e, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'testImportResourceWithNestedImportsAndProperties(com.hazelcast.client.config.XmlClientConfigImportVariableReplacementTest):'
18:27:45, accumulated pauses: 2503 ms, max pause: 602 ms, pauses over 1000 ms: 0


No metrics recorded during the test

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-Windows-MicrosoftJDK11/100/

**Comment by JackPGreen** [comment]
This was broken on Windows (only) in https://github.com/hazelcast/hazelcast-mono/pull/344

**Comment by Patras3** [comment]
Failed again on _master_ with Windows - MicrosoftJDK17: https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK17/98/testReport/com.hazelcast.client.config/XmlClientConfigImportVariableReplacementTest/

**Comment by Patras3** [comment]
It's a constant test failure for Windows.

**Comment by Patras3** [comment]
Reopening as issue occurred again on: _master_ (commit d86e97b937ff7b4085719c062ef296b89d9304d0)
with Windows - MicrosoftJDK17: 
with error:  `Illegal character in path at index 10`
https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK17/99/testReport/com.hazelcast.config/YamlConfigImportVariableReplacementTest/testReplaceVariablesWithUrlConfig/
<details><summary>Stacktrace:</summary>

```
java.lang.IllegalArgumentException: Illegal character in path at index 10: file:///C:\Jenkins\workspace\Hazelcast-master-Windows-MicrosoftJDK17\hazelcast\foo.bar
	at java.base/java.net.URI.create(URI.java:906)
	at com.hazelcast.config.UrlYamlConfig.<init>(UrlYamlConfig.java:65)
	at com.hazelcast.config.YamlConfigImportVariableReplacementTest.testReplaceVariablesWithUrlConfig(YamlConfigImportVariableReplacementTest.java:642)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.net.URISyntaxException: Illegal character in path at index 10: file:///C:\Jenkins\workspace\Hazelcast-master-Windows-MicrosoftJDK17\hazelcast\foo.bar
	at java.base/java.net.URI$Parser.fail(URI.java:2976)
	at java.base/java.net.URI$Parser.checkChars(URI.java:3147)
	at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3229)
	at java.base/java.net.URI$Parser.parse(URI.java:3177)
	at java.base/java.net.URI.<init>(URI.java:623)
	at java.base/java.net.URI.create(URI.java:904)
	... 7 more

```
</details>

https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK17/99/testReport/com.hazelcast.config/XmlConfigImportVariableReplacementTest/testReplaceVariablesWithUrlConfig/
<details><summary>Stacktrace:</summary>

```
java.lang.IllegalArgumentException: Illegal character in path at index 10: file:///C:\Jenkins\workspace\Hazelcast-master-Windows-MicrosoftJDK17\hazelcast\config-properties.xml
	at java.base/java.net.URI.create(URI.java:906)
	at com.hazelcast.config.UrlXmlConfig.<init>(UrlXmlConfig.java:65)
	at com.hazelcast.config.XmlConfigImportVariableReplacementTest.testReplaceVariablesWithUrlConfig(XmlConfigImportVariableReplacementTest.java:638)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.net.URISyntaxException: Illegal character in path at index 10: file:///C:\Jenkins\workspace\Hazelcast-master-Windows-MicrosoftJDK17\hazelcast\config-properties.xml
	at java.base/java.net.URI$Parser.fail(URI.java:2976)
	at java.base/java.net.URI$Parser.checkChars(URI.java:3147)
	at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3229)
	at java.base/java.net.URI$Parser.parse(URI.java:3177)
	at java.base/java.net.URI.<init>(URI.java:623)
	at java.base/java.net.URI.create(URI.java:904)
	... 7 more

```
</details>
There are also some new test failures with this error: `other is different type of Path` :

* https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK17/99/testReport/com.hazelcast.config/XmlYamlConfigBuilderEqualsTest/testFullExampleWithAdvancedNetwork/
* https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK17/99/testReport/com.hazelcast.config/XmlYamlConfigBuilderEqualsTest/testFullExample/

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-Windows-MicrosoftJDK17/99/

**Comment by Patras3** [comment]
Failed again on _master_ with Windows - OracleJDK11: https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-OracleJDK11/483/testReport/com.hazelcast.config/

**Comment by JackPGreen** [comment]
> Reopening as issue occurred again on: _master_ (commit [d86e97b](https://github.com/hazelcast/hazelcast/commit/d86e97b937ff7b4085719c062ef296b89d9304d0)) with Windows - MicrosoftJDK17: with error: `Illegal character in path at index 10` https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK17/99/testReport/com.hazelcast.config/YamlConfigImportVariableReplacementTest/testReplaceVariablesWithUrlConfig/
> 
> Stacktrace:
> https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK17/99/testReport/com.hazelcast.config/XmlConfigImportVariableReplacementTest/testReplaceVariablesWithUrlConfig/

https://github.com/hazelcast/hazelcast-mono/pull/514

> 
> Stacktrace:
> There are also some new test failures with this error: `other is different type of Path` :
> * https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK17/99/testReport/com.hazelcast.config/XmlYamlConfigBuilderEqualsTest/testFullExampleWithAdvancedNetwork/
> * https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK17/99/testReport/com.hazelcast.config/XmlYamlConfigBuilderEqualsTest/testFullExample/
> 
> Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-Windows-MicrosoftJDK17/99/

Looks to be an issue with relative path resolution in `com.hazelcast.config.XmlYamlConfigBuilderEqualsTest.replaceUCNReferencesWithTemporaryFile(String)`, I've not got a fix yet.

**Comment by Patras3** [comment]
Failed again on _master_ with Windows - MicrosoftJDK17: https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK17/100/testReport/com.hazelcast.config/XmlYamlConfigBuilderEqualsTest/

**Comment by JackPGreen** [comment]
@Patras3 @sumnerib would it help to rename this issue to make it clear it's Windows-only? I can't unfortunately.

**Comment by Patras3** [comment]
@JackPGreen  I also cannot. 
Maybe worth to introduce extra label which will show Windows/MacOS related issues and it will be added automagically if someone from QE team will create a issue by script. Something like: `Env: Windows` `Env: MacOS` wdyt @olukas ?

**Comment by olukas** [comment]
@Patras3 It would not be too easy to do it in the script for creating issues - we can have constant test failure but first time when we will see it could be on Windows - then the script will report it as `Env: Windows` even if it occurs on non-Windows platform. We can add it manually but it means to go through all TF which we have (we can do that but it will cost us some time).

**Comment by olukas** [comment]
Tests `com.hazelcast.config.XmlYamlConfigBuilderEqualsTest.testFullExample` and `com.hazelcast.config.XmlYamlConfigBuilderEqualsTest.testFullExampleWithAdvancedNetwork` failed again on _master_ with Windows - MicrosoftJDK17 with message `'other' is different type of Path`: https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK17/101/testReport/com.hazelcast.config/XmlYamlConfigBuilderEqualsTest/
