### ISSUE TITLE
Could not find an available, non-overlapping IPv4 address in com.hazelcast.jet.sql.impl.connector.jdbc.mysql.*

### ISSUE THREAD

**Issue by Patras3** [hazelcast/hazelcast#26215]
_master_ (commit d23fa2f57bbe0a1c0599dd7fa43af4593bb7d283)

Failed on oracle-11:
* https://jenkins.hazelcast.com/job/Hazelcast-master-mysql-8.2/16/testReport/com.hazelcast.jet.sql.impl.connector.jdbc.mysql/MySQLInsertJdbcSqlConnectorTest/___/

* https://jenkins.hazelcast.com/job/Hazelcast-master-mysql-8.2/16/testReport/com.hazelcast.jet.sql.impl.connector.jdbc.mysql/MySQLAllTypesInsertJdbcSqlConnectorTest/___/

* https://jenkins.hazelcast.com/job/Hazelcast-master-mysql-8.2/16/testReport/com.hazelcast.jet.sql.impl.connector.jdbc.mysql/MySQLSchemaJdbcSqlConnectorTest/___/

<details><summary>Stacktrace:</summary>

```
org.testcontainers.containers.ContainerLaunchException: Container startup failed for image mysql:8.2.0
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:362)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:333)
	at com.hazelcast.test.jdbc.JdbcDatabaseProvider.createDatabase(JdbcDatabaseProvider.java:39)
	at com.hazelcast.jet.sql.impl.connector.jdbc.JdbcSqlTestSupport.initialize(JdbcSqlTestSupport.java:76)
	at com.hazelcast.jet.sql.impl.connector.jdbc.JdbcSqlTestSupport.initialize(JdbcSqlTestSupport.java:70)
	at com.hazelcast.jet.sql.impl.connector.jdbc.mysql.MySQLSchemaJdbcSqlConnectorTest.beforeClass(MySQLSchemaJdbcSqlConnectorTest.java:33)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:41)
	at com.hazelcast.test.OverridePropertyRule$1.evaluate(OverridePropertyRule.java:69)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:347)
	... 10 more
Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:566)
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:357)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
	... 11 more
Caused by: com.github.dockerjava.api.exception.NotFoundException: Status 404: {"message":"could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:241)
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.post(DefaultInvocationBuilder.java:124)
	at org.testcontainers.shaded.com.github.dockerjava.core.exec.CreateNetworkCmdExec.execute(CreateNetworkCmdExec.java:27)
	at org.testcontainers.shaded.com.github.dockerjava.core.exec.CreateNetworkCmdExec.execute(CreateNetworkCmdExec.java:12)
	at org.testcontainers.shaded.com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21)
	at org.testcontainers.shaded.com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:33)
	at org.testcontainers.containers.Network$NetworkImpl.create(Network.java:100)
	at org.testcontainers.containers.Network$NetworkImpl.getId(Network.java:64)
	at org.testcontainers.containers.ContainerDef.applyTo(ContainerDef.java:106)
	at org.testcontainers.containers.GenericContainer.applyConfiguration(GenericContainer.java:786)
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:392)
	... 13 more

```
</details>

**Comment by Patras3** [comment]
Failed again on _master_ with oracle-11: https://jenkins.hazelcast.com/job/Hazelcast-master-mysql-8.0/42/testReport/com.hazelcast.jet.sql.impl.connector.jdbc.mysql/
