### ISSUE TITLE
com.hazelcast.jet.kafka.imp.WriteKafkaPTest tests are failing with "Number of partitions is below 1."

### ISSUE THREAD

**Issue by Patras3** [hazelcast/hazelcast#26217]
_master_ (commit d23fa2f57bbe0a1c0599dd7fa43af4593bb7d283)

Failed on oracle-11: https://jenkins.hazelcast.com/job/Hazelcast-master-Redpanda-23.3.z/2/testReport/com.hazelcast.jet.kafka.impl/WriteKafkaPTest/stressTest_graceful_exOnce/
<details><summary>Stacktrace:</summary>

```
java.lang.RuntimeException: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.InvalidPartitionsException: Number of partitions is below 1.
	at com.hazelcast.jet.kafka.impl.KafkaTestSupport.createTopic(KafkaTestSupport.java:134)
	at com.hazelcast.jet.kafka.impl.WriteKafkaPTest.before(WriteKafkaPTest.java:96)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:365)
	at com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37)
	at com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:104)
	at com.hazelcast.test.metrics.MetricsRule$1.evaluate(MetricsRule.java:63)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:53)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:32)
	at com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:41)
	at com.hazelcast.test.OverridePropertyRule$1.evaluate(OverridePropertyRule.java:69)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.InvalidPartitionsException: Number of partitions is below 1.
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
	at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:165)
	at com.hazelcast.jet.kafka.impl.KafkaTestSupport.createTopic(KafkaTestSupport.java:132)
	... 12 more
Caused by: org.apache.kafka.common.errors.InvalidPartitionsException: Number of partitions is below 1.

```
</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: when_processingGuaranteeOn_then_lingeringRecordsSentOnSnapshot_atLeastOnce in 0.148 seconds.
Started Running Test: stressTest_graceful_exOnce
21:21:35,354  INFO |stressTest_graceful_exOnce| - [SimpleTestInClusterSupport] Time-limited test - Ditching 0 jobs in SimpleTestInClusterSupport.@After: []
21:21:35,354  INFO |stressTest_graceful_exOnce| - [SimpleTestInClusterSupport] Time-limited test - Destroying 3 distributed objects in SimpleTestInClusterSupport.@After: [hz:impl:mapService/__jet.executionRecords, hz:impl:mapService/__jet.results, hz:impl:mapService/__jet.records]
21:21:35,355  INFO |stressTest_graceful_exOnce| - [HazelcastTestSupport] Time-limited test - Shutting down node factory as @After action
BuildInfo right after stressTest_graceful_exOnce(com.hazelcast.jet.kafka.impl.WriteKafkaPTest): BuildInfo{version='5.4.0-SNAPSHOT', build='20240112', buildNumber=20240112, revision=d23fa2f, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'stressTest_graceful_exOnce(com.hazelcast.jet.kafka.impl.WriteKafkaPTest):'
21:21:35, accumulated pauses: 232 ms, max pause: 120 ms, pauses over 1000 ms: 0


No metrics recorded during the test

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-Redpanda-23.3.z/2/

Failing with the same issue (`Number of partitions is below 1.`) for:
* [when_processingGuaranteeOn_then_lingeringRecordsSentOnSnapshot_atLeastOnce](https://jenkins.hazelcast.com/job/Hazelcast-master-Redpanda-23.3.z/2/testReport/com.hazelcast.jet.kafka.impl/WriteKafkaPTest/when_processingGuaranteeOn_then_lingeringRecordsSentOnSnapshot_atLeastOnce)
* [when_transactionRolledBackHeuristically_then_sinkIgnoresIt](https://jenkins.hazelcast.com/job/Hazelcast-master-Redpanda-23.3.z/2/testReport/com.hazelcast.jet.kafka.impl/WriteKafkaPTest/when_transactionRolledBackHeuristically_then_sinkIgnoresIt)

**Comment by olukas** [comment]
Failed again on _master_ with Redpanda: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Redpanda-23.3.z/6/testReport/

**Comment by AleksPeychev** [comment]
Failed again on _master_ with oracle-17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Redpanda-23.3.z/8/testReport/com.hazelcast.jet.kafka.impl/WriteKafkaPTest

**Comment by sumnerib** [comment]
Failed again on _master_ with oracle-17: https://jenkins.hazelcast.com/job/Hazelcast-master-Redpanda-23.3.z/15/testReport/

**Comment by Patras3** [comment]
Rescent TF (still fails constantly):
Failed again on _master_ with oracle-17: https://jenkins.hazelcast.com/job/Hazelcast-master-Redpanda-23.3.z/20/testReport/com.hazelcast.jet.kafka.impl/WriteKafkaPTest/

**Comment by Patras3** [comment]
Failed again on _master_ with oracle-17: https://jenkins.hazelcast.com/job/Hazelcast-master-Redpanda-24.1.z/3/testReport/com.hazelcast.jet.kafka.impl/WriteKafkaPTest/ and error log is now different:
`Caused by: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.InvalidPartitionsException: Can not increase partition count due to memory limit`

**Comment by Patras3** [comment]
Failed again on _master_ with oracle-17: https://jenkins.hazelcast.com/job/Hazelcast-master-Redpanda-23.3.z/31/testReport/com.hazelcast.jet.sql.impl.connector.kafka/SqlAvroTest/

**Comment by olukas** [comment]
Closing as a subset of https://github.com/hazelcast/hazelcast/issues/26307
