### ISSUE TITLE
Some test are failing in com.hazelcast.jet.sql.impl.connector.jdbc.mysql and com.hazelcast.jet.sql.impl.connector.jdbc.mssql with Unsupported column type: CHAR exception [HZ-4212]

### ISSUE THREAD

**Issue by Patras3** [hazelcast/hazelcast#26219]
_master_ (commit d23fa2f57bbe0a1c0599dd7fa43af4593bb7d283)

Failed on zing-11: https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK11-nightly/67/testReport/com.hazelcast.jet.sql.impl.connector.jdbc.mysql/MySQLAllTypesInsertJdbcSqlConnectorTest/insertRowWithAllTypes/
<details><summary>Stacktrace:</summary>

```
com.hazelcast.sql.HazelcastSqlException: Unsupported column type: CHAR
	at com.hazelcast.sql.impl.CoreQueryUtils.toPublicException(CoreQueryUtils.java:62)
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:238)
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:187)
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:181)
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:175)
	at com.hazelcast.sql.SqlService.execute(SqlService.java:89)
	at com.hazelcast.jet.sql.impl.connector.jdbc.JdbcSqlTestSupport.execute(JdbcSqlTestSupport.java:236)
	at com.hazelcast.jet.sql.impl.connector.jdbc.AllTypesInsertJdbcSqlConnectorTest.insertRowWithAllTypes(AllTypesInsertJdbcSqlConnectorTest.java:99)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:887)
Caused by: java.lang.IllegalArgumentException: Unsupported column type: CHAR
	at com.hazelcast.jet.sql.impl.connector.jdbc.DefaultTypeResolver.resolveType(DefaultTypeResolver.java:99)
	at com.hazelcast.jet.sql.impl.connector.jdbc.JdbcSqlConnector.validateType(JdbcSqlConnector.java:263)
	at com.hazelcast.jet.sql.impl.connector.jdbc.JdbcSqlConnector.resolveAndValidateFields(JdbcSqlConnector.java:137)
	at com.hazelcast.jet.sql.impl.schema.TableResolverImpl.resolveMapping(TableResolverImpl.java:177)
	at com.hazelcast.jet.sql.impl.schema.TableResolverImpl.createMapping(TableResolverImpl.java:134)
	at com.hazelcast.jet.sql.impl.PlanExecutor.execute(PlanExecutor.java:178)
	at com.hazelcast.jet.sql.impl.SqlPlanImpl$CreateMappingPlan.execute(SqlPlanImpl.java:156)
	at com.hazelcast.sql.impl.SqlServiceImpl.query0(SqlServiceImpl.java:283)
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:221)
	... 11 more

```
</details>

<details><summary>Standard output:</summary>

```
22:09:02,686  INFO |insertRowWithAllTypes[type:CHAR(3), mappingType:VARCHAR, sqlValue:'try', javaValue:try, jdbcValue:try]| - [SqlTestSupport] Time-limited test - Removing 0 cached plans in SqlTestSupport.@After
22:09:02,686  INFO |insertRowWithAllTypes[type:CHAR(3), mappingType:VARCHAR, sqlValue:'try', javaValue:try, jdbcValue:try]| - [SqlTestSupport] Time-limited test - Removing 0 cached plans in SqlTestSupport.@After
22:09:02,686  INFO |insertRowWithAllTypes[type:CHAR(3), mappingType:VARCHAR, sqlValue:'try', javaValue:try, jdbcValue:try]| - [SimpleTestInClusterSupport] Time-limited test - Ditching 0 jobs in SimpleTestInClusterSupport.@After: []
22:09:02,686  INFO |insertRowWithAllTypes[type:CHAR(3), mappingType:VARCHAR, sqlValue:'try', javaValue:try, jdbcValue:try]| - [SimpleTestInClusterSupport] Time-limited test - Destroying 1 distributed objects in SimpleTestInClusterSupport.@After: [hz:impl:mapService/__sql.catalog]
22:09:02,687  INFO |insertRowWithAllTypes[type:CHAR(3), mappingType:VARCHAR, sqlValue:'try', javaValue:try, jdbcValue:try]| - [HazelcastTestSupport] Time-limited test - Shutting down node factory as @After action
BuildInfo right after insertRowWithAllTypes[type:CHAR(3), mappingType:VARCHAR, sqlValue:'try', javaValue:try, jdbcValue:try](com.hazelcast.jet.sql.impl.connector.jdbc.mysql.MySQLAllTypesInsertJdbcSqlConnectorTest): BuildInfo{version='5.4.0-SNAPSHOT', build='20240114', buildNumber=20240114, revision=d23fa2f, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'insertRowWithAllTypes[type:CHAR(3), mappingType:VARCHAR, sqlValue:'try', javaValue:try, jdbcValue:try](com.hazelcast.jet.sql.impl.connector.jdbc.mysql.MySQLAllTypesInsertJdbcSqlConnectorTest):'
22:09:00, accumulated pauses: 2665 ms, max pause: 13 ms, pauses over 1000 ms: 0


No metrics recorded during the test

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-ZingJDK11-nightly/67/

The same exception for:
https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK11-nightly/67/testReport/com.hazelcast.jet.sql.impl.connector.jdbc.mysql/MySQLAllTypesInsertJdbcSqlConnectorTest/insertRowWithAllTypes/
https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK11-nightly/67/testReport/com.hazelcast.jet.sql.impl.connector.jdbc.mysql/MySQLAllTypesSelectJdbcSqlConnectorTest/resolveMappingType/

**Comment by Patras3** [comment]
Failed again on _master_ with ibm-11: https://jenkins.hazelcast.com/job/Hazelcast-master-Openj9-11-nightly/139/testReport/

**Comment by Patras3** [comment]
Looks like it's a constant test failure.

**Comment by Patras3** [comment]
Failed again on _5.3.z_ with ibm-8: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-IbmJDK8-nightly/120/testReport/com.hazelcast.jet.sql.impl.connector.jdbc.mysql/MySQLAllTypesSelectJdbcSqlConnectorTest/selectRowWithAllTypes_type_CHAR_3___mappingType_VARCHAR__value__try___expected_try_/
