### ISSUE TITLE
com.hazelcast.topic.impl.reliable.LossToleranceTest [HZ-4346]

### ISSUE THREAD

**Issue by Patras3** [hazelcast/hazelcast#26228]
_master_ (commit d86e97b937ff7b4085719c062ef296b89d9304d0)

Failed on microsoft-11: https://jenkins.hazelcast.com/job/Hazelcast-master-MicrosoftJDK11/100/testReport/com.hazelcast.topic.impl.reliable/LossToleranceTest/
All tests are failing with the same issue:
<details><summary>Stacktrace:</summary>

```
java.lang.NullPointerException
	at com.hazelcast.topic.impl.reliable.LossToleranceTest.setup(LossToleranceTest.java:70)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:365)
	at com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37)
	at com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:104)
	at com.hazelcast.test.metrics.MetricsRule$1.evaluate(MetricsRule.java:63)
	at com.hazelcast.test.HazelcastParallelClassRunner.access$101(HazelcastParallelClassRunner.java:52)
	at com.hazelcast.test.HazelcastParallelClassRunner$TestRunner.run(HazelcastParallelClassRunner.java:165)
	at java.base/java.lang.Thread.run(Thread.java:829)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-MicrosoftJDK11/100/

**Comment by AyberkSorgun** [comment]
Fixed by https://github.com/hazelcast/hazelcast-mono/pull/716
