### ISSUE TITLE
com.hazelcast.jet.kafka.connect.KafkaConnectRedisIT.testReadFromRedisConnector

### ISSUE THREAD

**Issue by Patras3** [hazelcast/hazelcast#26232]
_master_ (commit 038f26db1bea01538eda6fe434788bd99de39934)

Failed on oracle-17 (sonar build): https://jenkins.hazelcast.com/job/Hazelcast-master-sonar/386/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectRedisIT/testReadFromRedisConnector/
<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: jobId=0b29-2812-fd00-0001 expected:<RUNNING> but was:<FAILED>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:120)
	at com.hazelcast.jet.core.JetTestSupport.lambda$assertJobStatusEventually$2(JetTestSupport.java:338)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1188)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1207)
	at com.hazelcast.jet.core.JetTestSupport.assertJobStatusEventually(JetTestSupport.java:337)
	at com.hazelcast.jet.core.JetTestSupport.assertJobStatusEventually(JetTestSupport.java:253)
	at com.hazelcast.jet.kafka.connect.KafkaConnectRedisIT.testReadFromRedisConnector(KafkaConnectRedisIT.java:107)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-sonar/386/

**Comment by Patras3** [comment]
Failed again on _master_ with oracle-17 (little-endian): https://jenkins.hazelcast.com/job/Hazelcast-master-nightly-little-endian/63/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectRedisIT/testReadFromRedisConnector/
