### ISSUE TITLE
com.hazelcast.aws.AwsEcsApiTest

### ISSUE THREAD

**Issue by Patras3** [hazelcast/hazelcast#26231]
_master_ (commit 038f26db1bea01538eda6fe434788bd99de39934)

Failed on OpenJDK17: https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK17-arm64/3/testReport/junit/com.hazelcast.aws/AwsEcsApiTest/listTasks/
<details><summary>Stacktrace:</summary>

```
com.hazelcast.spi.exception.RestClientException: 
Failure executing: POST at: http://localhost:41765. Message: 
                                               Request was not matched
                                               =======================

-----------------------------------------------------------------------------------------------------------------------
| Closest stub                                             | Request                                                  |
-----------------------------------------------------------------------------------------------------------------------
                                                           |
POST                                                       | POST
/                                                          | /
                                                           |
X-Amz-Date: 20200403T102518Z                               | X-Amz-Date: 20200403T102518Z
Authorization: authorization-header                        | Authorization: authorization-header
X-Amz-Target:                                              | X-Amz-Target:
AmazonEC2ContainerServiceV20141113.DescribeTasks           | AmazonEC2ContainerServiceV20141113.DescribeTasks
Content-Type: application/x-amz-json-1.1                   | Content-Type: application/x-amz-json-1.1
Accept-Encoding: identity                                  | Accept-Encoding: identity
X-Amz-Security-Token:                                      | X-Amz-Security-Token:
IQoJb3JpZ2luX2VjEFIaDGV1LWNlbnRyYWwtMSJGM==                | IQoJb3JpZ2luX2VjEFIaDGV1LWNlbnRyYWwtMSJGM==
                                                           |
[equalToJson]                                              | {                                                   <<<<< Body does not match
{                                                          |   "tasks" : [
  "tasks" : [                                              | "arn:aws:ecs:us-east-1:012345678910:task/0b69d5c0-d655-46
"arn:aws:ecs:us-east-1:012345678910:task/51a01bdf-d00e-48  | 95-98cd-5d2d526d9d5a",
7e-ab14-7645330b6207",                                     | "arn:aws:ecs:us-east-1:012345678910:task/51a01bdf-d00e-48
"arn:aws:ecs:us-east-1:012345678910:task/0b69d5c0-d655-46  | 7e-ab14-7645330b6207" ],
95-98cd-5d2d526d9d5a" ],                                   |   "include" : [ "TAGS" ],
  "include" : [ "TAGS" ],                                  | "cluster" :
"cluster" :                                                | "arn:aws:ecs:eu-central-1:665466731577:cluster/rafal-test
"arn:aws:ecs:eu-central-1:665466731577:cluster/rafal-test  | -cluster"
-cluster"                                                  | }
}                                                          |
                                                           |
-----------------------------------------------------------------------------------------------------------------------
. HTTP Error Code: 404
	at com.hazelcast.spi.utils.RestClient.checkResponseCode(RestClient.java:257)
	at com.hazelcast.spi.utils.RestClient.call(RestClient.java:193)
	at com.hazelcast.spi.utils.RestClient.lambda$callWithRetries$1(RestClient.java:187)
	at com.hazelcast.spi.utils.RetryUtils.retry(RetryUtils.java:65)
	at com.hazelcast.spi.utils.RetryUtils.retry(RetryUtils.java:51)
	at com.hazelcast.spi.utils.RestClient.callWithRetries(RestClient.java:187)
	at com.hazelcast.spi.utils.RestClient.post(RestClient.java:159)
	at com.hazelcast.aws.AwsEcsApi.callAwsService(AwsEcsApi.java:172)
	at com.hazelcast.aws.AwsEcsApi.describeTasks(AwsEcsApi.java:108)
	at com.hazelcast.aws.AwsEcsApi.listTaskPrivateAddresses(AwsEcsApi.java:68)
	at com.hazelcast.aws.AwsEcsApiTest.listTasks(AwsEcsApiTest.java:94)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.mockito.internal.runners.DefaultInternalRunner$1$1.evaluate(DefaultInternalRunner.java:55)
	at com.github.tomakehurst.wiremock.junit.WireMockRule$1.evaluate(WireMockRule.java:67)
	at org.mockito.internal.runners.DefaultInternalRunner$1.run(DefaultInternalRunner.java:100)
	at org.mockito.internal.runners.DefaultInternalRunner.run(DefaultInternalRunner.java:107)
	at org.mockito.internal.runners.StrictRunner.run(StrictRunner.java:42)
	at org.mockito.junit.MockitoJUnitRunner.run(MockitoJUnitRunner.java:163)

```
</details>

Similat issue for all below tests:
[listTasks](https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK17-arm64/3/testReport/junit/com.hazelcast.aws/AwsEcsApiTest/listTasks)	0.11 sec	Failed
[listTasksFiltered](https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK17-arm64/3/testReport/junit/com.hazelcast.aws/AwsEcsApiTest/listTasksFiltered)	43 ms	Failed
[listTasksFilteredByTags](https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK17-arm64/3/testReport/junit/com.hazelcast.aws/AwsEcsApiTest/listTasksFilteredByTags)	34 ms	Failed

I think it's because of tasks which sometimes can be not in the same order.

**Comment by Patras3** [comment]
FYI : @orcunc it looks like regression after https://github.com/hazelcast/hazelcast-mono/pull/511

**Comment by Patras3** [comment]
Failed again on _master_ with OpenJDK17: https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK17-Esxi7/74/testReport/junit/com.hazelcast.aws/AwsEcsApiTest/

**Comment by Patras3** [comment]
Fixed by:
https://github.com/hazelcast/hazelcast-mono/pull/557
