### ISSUE TITLE
com.hazelcast.jet.kafka.connect.KafkaConnectJdbcIT.testScaling_with_new_member [HZ-4271]

### ISSUE THREAD

**Issue by Patras3** [hazelcast/hazelcast#26235]
_master_ (commit 8a50ce7289a6f1a12a548d0657a363ee15c54502)

Failed on oracle-17 (little-endian): https://jenkins.hazelcast.com/job/Hazelcast-master-nightly-little-endian/63/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectJdbcIT/testScaling_with_new_member/
<details><summary>Stacktrace:</summary>

```
java.lang.RuntimeException: 10 attempts to cancel the job failed, shut down the cluster
	at com.hazelcast.jet.core.JetTestSupport.ditchJob0(JetTestSupport.java:548)
	at com.hazelcast.jet.core.JetTestSupport.ditchJob(JetTestSupport.java:469)
	at com.hazelcast.jet.core.JetTestSupport.shutdownJobsAndGetLeakedClassLoaders(JetTestSupport.java:150)
	at com.hazelcast.jet.core.JetTestSupport.shutdownFactory(JetTestSupport.java:120)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:381)
	at com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37)
	at com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:104)
	at com.hazelcast.test.metrics.MetricsRule$1.evaluate(MetricsRule.java:63)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:53)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:32)
	at com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:41)
	at com.hazelcast.test.OverridePropertyRule$1.evaluate(OverridePropertyRule.java:69)
	at org.testcontainers.containers.FailureDetectingExternalResource$1.evaluate(FailureDetectingExternalResource.java:29)
	at com.hazelcast.test.OverridePropertyRule$1.evaluate(OverridePropertyRule.java:69)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-nightly-little-endian/63/

**Comment by Patras3** [comment]
Failed again on _master_ with zing-21: https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK21-nightly/2/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectJdbcIT/testScaling_with_new_member/
