### ISSUE TITLE
com.hazelcast.client.replicatedmap.ClientReplicatedMapTest.testPutAllWithMetadataAsync

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#26251]
_5.3.z_ (commit bbdddd7a31e13215071ec5538ccda19f0c63b426)

Failed on ZuluJDK8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-ZuluJDK8/123/testReport/com.hazelcast.client.replicatedmap/ClientReplicatedMapTest/testPutAllWithMetadataAsync_format_BINARY_/

Fails with `[format:BINARY]` and `[format:OBJECT]`.

<details><summary>Stacktrace:</summary>

```
java.lang.NullPointerException
	at com.hazelcast.client.replicatedmap.ClientReplicatedMapTest.getVersionMaps(ClientReplicatedMapTest.java:553)
	at com.hazelcast.client.replicatedmap.ClientReplicatedMapTest.testPutAllWithMetadataAsync(ClientReplicatedMapTest.java:488)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:750)

```
</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: testNonEmptyMapIsNotEmpty[format:BINARY] in 1.210 seconds.
Started Running Test: testPutReturnValueDeserialization[format:BINARY]
Started Running Test: testKeySet[format:BINARY]
Started Running Test: testNearCacheInvalidation[format:BINARY]
Started Running Test: testPutNullReturnValueDeserialization[format:BINARY]
08:49:57,474  INFO |testPutAllWithMetadataAsync[format:BINARY]| - [NodeExtension] Thread-20822 - [127.0.0.1]:5702 [dev] [5.3.7-SNAPSHOT] Destroying node NodeExtension.
08:49:57,475  INFO |testPutAllWithMetadataAsync[format:BINARY]| - [Node] Thread-20822 - [127.0.0.1]:5702 [dev] [5.3.7-SNAPSHOT] Hazelcast Shutdown is completed in 53 ms.
08:49:57,475  INFO |testPutAllWithMetadataAsync[format:BINARY]| - [LifecycleService] Thread-20822 - [127.0.0.1]:5702 [dev] [5.3.7-SNAPSHOT] [127.0.0.1]:5702 is SHUTDOWN
08:49:57,479  INFO |testPutAllWithMetadataAsync[format:BINARY]| - [LifecycleService] Thread-20822 - [127.0.0.1]:5701 [dev] [5.3.7-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
08:49:57,483  WARN |testPutAllWithMetadataAsync[format:BINARY]| - [Node] Thread-20822 - [127.0.0.1]:5701 [dev] [5.3.7-SNAPSHOT] Terminating forcefully...
08:49:57,483  INFO |testPutAllWithMetadataAsync[format:BINARY]| - [Node] Thread-20822 - [127.0.0.1]:5701 [dev] [5.3.7-SNAPSHOT] Shutting down connection manager...
08:49:57,483  INFO |testPutAllWithMetadataAsync[format:BINARY]| - [Node] Thread-20822 - [127.0.0.1]:5701 [dev] [5.3.7-SNAPSHOT] Shutting down node engine...
08:49:57,486  INFO |testRemove[format:BINARY]| - [ClientInvocationService] testRemove - hz.client_714 [dev] [5.3.7-SNAPSHOT] Running with 2 response threads, dynamic=true
08:49:57,496  INFO |testNearCacheInvalidation[format:BINARY]| - [MetricsConfigHelper] testNearCacheInvalidation - [LOCAL] [dev] [5.3.7-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
08:49:57,496  INFO |testPutNullReturnValueDeserialization[format:BINARY]| - [MetricsConfigHelper] testPutNullReturnValueDeserialization - [LOCAL] [dev] [5.3.7-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
08:49:57,498  INFO |testPutAllWithMetadataAsync[format:BINARY]| - [NodeExtension] Thread-20822 - [127.0.0.1]:5701 [dev] [5.3.7-SNAPSHOT] Destroying node NodeExtension.
08:49:57,498  INFO |testPutAllWithMetadataAsync[format:BINARY]| - [Node] Thread-20822 - [127.0.0.1]:5701 [dev] [5.3.7-SNAPSHOT] Hazelcast Shutdown is completed in 15 ms.
08:49:57,498  INFO |testPutAllWithMetadataAsync[format:BINARY]| - [LifecycleService] Thread-20822 - [127.0.0.1]:5701 [dev] [5.3.7-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
BuildInfo right after testPutAllWithMetadataAsync[format:BINARY](com.hazelcast.client.replicatedmap.ClientReplicatedMapTest): BuildInfo{version='5.3.7-SNAPSHOT', build='20240211', buildNumber=20240211, revision=, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'testPutAllWithMetadataAsync[format:BINARY](com.hazelcast.client.replicatedmap.ClientReplicatedMapTest):'
08:49:55, accumulated pauses: 1015 ms, max pause: 999 ms, pauses over 1000 ms: 0

08:49:57,498  INFO |testPutReturnValueDeserialization[format:BINARY]| - [MetricsConfigHelper] testPutReturnValueDeserialization - [LOCAL] [dev] [5.3.7-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
08:49:57,498  INFO |testRemove[format:BINARY]| - [LifecycleService] testRemove - hz.client_714 [dev] [5.3.7-SNAPSHOT] HazelcastClient 5.3.7-SNAPSHOT (20240211) is STARTING
08:49:57,499  INFO |testRemove[format:BINARY]| - [LifecycleService] testRemove - hz.client_714 [dev] [5.3.7-SNAPSHOT] HazelcastClient 5.3.7-SNAPSHOT (20240211) is STARTED
08:49:57,499  INFO |testNearCacheInvalidation[format:BINARY]| - [logo] testNearCacheInvalidation - [127.0.0.1]:5701 [dev] [5.3.7-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
08:49:57,499  INFO |testNearCacheInvalidation[format:BINARY]| - [system] testNearCacheInvalidation - [127.0.0.1]:5701 [dev] [5.3.7-SNAPSHOT] Copyright (c) 2008-2023, Hazelcast, Inc. All Rights Reserved.
08:49:57,499  INFO |testNearCacheInvalidation[format:BINARY]| - [system] testNearCacheInvalidation - [127.0.0.1]:5701 [dev] [5.3.7-SNAPSHOT] Hazelcast Platform 5.3.7-SNAPSHOT (20240211) starting at [127.0.0.1]:5701
08:49:57,499  INFO |testPutNullReturnValueDeserialization[format:BINARY]| - [logo] testPutNullReturnValueDeserialization - [127.0.0.1]:5701 [dev] [5.3.7-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
08:49:57,499  INFO |testNearCacheInvalidation[format:BINARY]| - [system] testNearCacheInvalidation - [127.0.0.1]:5701 [dev] [5.3.7-SNAPSHOT] Cluster name: dev
08:49:57,499  INFO |testPutNullReturnValueDeserialization[format:BINARY]| - [system] testPutNullReturnValueDeserialization - [127.0.0.1]:5701 [dev] [5.3.7-SNAPSHOT] Copyright (c) 2008-2023, Hazelcast, Inc. All Rights Reserved.
08:49:57,499  INFO |testNearCacheInvalidation[format:BINARY]| - [system] testNearCacheInvalidation - [127.0.0.1]:5701 [dev] [5.3.7-SNAPSHOT] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed. For more information, see the documentation for Integrity Checker.
08:49:57,499  INFO |testPutNullReturnValueDeserialization[format:BINARY]| - [system] testPutNullReturnValueDeserialization - [127.0.0.1]:5701 [dev] [5.3.7-SNAPSHOT] Hazelcast Platform 5.3.7-SNAPSHOT (20240211) starting at [127.0.0.1]:5701
08:49:57,499  INFO |testNearCacheInvalidation[format:BINARY]| - [system] testNearCacheInvalidation - [127.0.0.1]:5701 [dev] [5.3.7-SNAPSHOT] The Jet engine is disabled.
To enable the Jet engine on the members, do one of the following:
  - Change member config using Java API: config.getJetConfig().setEnabled(true)
  - Change XML/YAML configuration property: Set hazelcast.jet.enabled to true
  - Add system property: -Dhz.jet.enabled=true (for Hazelcast embedded, works only when loading config via Config.load)
  - Add environment variable: HZ_JET_ENABLED=true (recommended when running container image. For Hazelcast embedded, works only when loading config via Config.load)
08:49:57,499  INFO |testPutNullReturnValueDeserialization[format:BINARY]| - [system] testPutNullReturnValueDeserialization - [127.0.0.1]:5701 [dev] [5.3.7-SNAPSHOT] Cluster name: dev
08:49:57,499  INFO |testPutNullReturnValueDeserialization[format:BINARY]| - [system] testPutNullReturnValueDeserialization - [127.0.0.1]:5701 [dev] [5.3.7-SNAPSHOT] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed. For more information, see the documentation for Integrity Checker.
08:49:57,499  INFO |testPutNullReturnValueDeserialization[format:BINARY]| - [system] testPutNullReturnValueDeserialization - [127.0.0.1]:5701 [dev] [5.3.7-SNAPSHOT] The Jet engine is disabled.
To enable the Jet engine on the members, do one of the following:
  - Change member config using Java API: config.getJetConfig().setEnabled(true)
  - Change XML/YAML configuration property: Set hazelcast.jet.enabled to true
  - Add system property: -Dhz.jet.enabled=true (for Hazelcast embedded, works only when loading config via Config.load)
  - Add environment variable: HZ_JET_ENABLED=true (recommended when running container image. For Hazelcast embedded, works only when loading config via Config.load)

No metrics recorded during the test
08:49:57,499  INFO |testKeySet[format:BINARY]| - [MetricsConfigHelper] testKeySet - [LOCAL] [dev] [5.3.7-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
08:49:57,500  INFO |testPutReturnValueDeserialization[format:BINARY]| - [logo] testPutReturnValueDeserialization - [127.0.0.1]:5701 [dev] [5.3.7-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
08:49:57,500  INFO |testPutReturnValueDeserialization[format:BINARY]| - [system] testPutReturnValueDeserialization - [127.0.0.1]:5701 [dev] [5.3.7-SNAPSHOT] Copyright (c) 2008-2023, Hazelcast, Inc. All Rights Reserved.
08:49:57,500  INFO |testPutReturnValueDeserialization[format:BINARY]| - [system] testPutReturnValueDeserialization - [127.0.0.1]:5701 [dev] [5.3.7-SNAPSHOT] Hazelcast Platform 5.3.7-SNAPSHOT (20240211) starting at [127.0.0.1]:5701
08:49:57,500  INFO |testPutReturnValueDeserialization[format:BINARY]| - [system] testPutReturnValueDeserialization - [127.0.0.1]:5701 [dev] [5.3.7-SNAPSHOT] Cluster name: dev
08:49:57,500  INFO |testPutReturnValueDeserialization[format:BINARY]| - [system] testPutReturnValueDeserialization - [127.0.0.1]:5701 [dev] [5.3.7-SNAPSHOT] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed. For more information, see the documentation for Integrity Checker.
08:49:57,500  INFO |testPutReturnValueDeserialization[format:BINARY]| - [system] testPutReturnValueDeserialization - [127.0.0.1]:5701 [dev] [5.3.7-SNAPSHOT] The Jet engine is disabled.
To enable the Jet engine on the members, do one of the following:
  - Change member config using Java API: config.getJetConfig().setEnabled(true)
  - Change XML/YAML configuration property: Set hazelcast.jet.enabled to true
  - Add system property: -Dhz.jet.enabled=true (for Hazelcast embedded, works only when loading config via Config.load)
  - Add environment variable: HZ_JET_ENABLED=true (recommended when running container image. For Hazelcast embedded, works only when loading config via Config.load)
08:49:57,500  INFO |testRemove[format:BINARY]| - [ClientConnectionManager] testRemove - hz.client_714 [dev] [5.3.7-SNAPSHOT] Trying to connect to cluster: dev
08:49:57,500  INFO |testRemove[format:BINARY]| - [ClientConnectionManager] testRemove - hz.client_714 [dev] [5.3.7-SNAPSHOT] Trying to connect to [127.0.0.1]:5701
08:49:57,500  INFO |testRemove[format:BINARY]| - [HazelcastClient] testRemove - Created connection to endpoint: [127.0.0.1]:5701, connection: MockedClientConnection{localAddress=[127.0.0.1]:40001, super=ClientConnection{alive=true, connectionId=1, channel=null, remoteAddress=null, lastReadTime=never, lastWriteTime=never, closedTime=never}}
08:49:57,500  INFO |testKeySet[format:BINARY]| - [logo] testKeySet - [127.0.0.1]:5701 [dev] [5.3.7-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
08:49:57,500  INFO |testKeySet[format:BINARY]| - [system] testKeySet - [127.0.0.1]:5701 [dev] [5.3.7-SNAPSHOT] Copyright (c) 2008-2023, Hazelcast, Inc. All Rights Reserved.
08:49:57,500  INFO |testKeySet[format:BINARY]| - [system] testKeySet - [127.0.0.1]:5701 [dev] [5.3.7-SNAPSHOT] Hazelcast Platform 5.3.7-SNAPSHOT (20240211) starting at [127.0.0.1]:5701
08:49:57,500  INFO |testKeySet[format:BINARY]| - [system] testKeySet - [127.0.0.1]:5701 [dev] [5.3.7-SNAPSHOT] Cluster name: dev
08:49:57,500  INFO |testKeySet[format:BINARY]| - [system] testKeySet - [127.0.0.1]:5701 [dev] [5.3.7-SNAPSHOT] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed. For more information, see the documentation for Integrity Checker.
08:49:57,500  INFO |testKeySet[format:BINARY]| - [system] testKeySet - [127.0.0.1]:5701 [dev] [5.3.7-SNAPSHOT] The Jet engine is disabled.
To enable the Jet engine on the members, do one of the following:
  - Change member config using Java API: config.getJetConfig().setEnabled(true)
  - Change XML/YAML configuration property: Set hazelcast.jet.enabled to true
  - Add system property: -Dhz.jet.enabled=true (for Hazelcast embedded, works only when loading config via Config.load)
  - Add environment variable: HZ_JET_ENABLED=true (recommended when running container image. For Hazelcast embedded, works only when loading config via Config.load)
08:49:57,503 DEBUG |testRemove[format:BINARY]| - [AuthenticationMessageTask] hz.ClientReplicatedMapTest_dazzling_poincare.priority-generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [5.3.7-SNAPSHOT] Processing authentication with clientUuid 6e9b6274-4883-43a0-bac8-b1d9378ef792 and clientName hz.client_714
08:49:57,503  INFO |testRemove[format:BINARY]| - [AuthenticationMessageTask] hz.ClientReplicatedMapTest_dazzling_poincare.priority-generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [5.3.7-SNAPSHOT] Received auth from MockedNodeConnection{ remoteAddress = [127.0.0.1]:40001, localAddress = [127.0.0.1]:5701, connectionId = 1}, successfully authenticated, clientUuid: 6e9b6274-4883-43a0-bac8-b1d9378ef792, client name: hz.client_714, client version: 5.3.7-SNAPSHOT
08:49:57,504  INFO |testRemove[format:BINARY]| - [LifecycleService] testRemove - hz.client_714 [dev] [5.3.7-SNAPSHOT] HazelcastClient 5.3.7-SNAPSHOT (20240211) is CLIENT_CONNECTED
08:49:57,504  INFO |testRemove[format:BINARY]| - [ClientConnectionManager] testRemove - hz.client_714 [dev] [5.3.7-SNAPSHOT] Authenticated with server [127.0.0.1]:5701:f84aa9d1-4425-4cc5-90af-634051e59fec, server version: 5.3.7-SNAPSHOT, local address: /127.0.0.1:40001
08:49:57,504  INFO |testRemove[format:BINARY]| - [Diagnostics] testRemove - hz.client_714 [dev] [5.3.7-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
08:49:57,504 TRACE |testRemove[format:BINARY]| - [ClientListenerService] hz.client_714.internal-1 - hz.client_714 [dev] [5.3.7-SNAPSHOT] Register attempt of ClusterViewListenerHandler to MockedClientConnection{localAddress=[127.0.0.1]:40001, super=ClientConnection{alive=true, connectionId=1, channel=null, remoteAddress=[127.0.0.1]:5701, lastReadTime=2024-02-11 08:49:57.504, lastWriteTime=2024-02-11 08:49:57.500, closedTime=never}}
08:49:57,505  INFO |entryViews_emptyPartition[format:BINARY]| - [LifecycleService] Thread-20824 - hz.client_711 [dev] [5.3.7-SNAPSHOT] HazelcastClient 5.3.7-SNAPSHOT (20240211) is SHUTTING_DOWN
08:49:57,505 TRACE |testRemove[format:BINARY]| - [ClientListenerService] ForkJoinPool.commonPool-worker-9 - hz.client_714 [dev] [5.3.7-SNAPSHOT] Registered ClusterViewListenerHandler to MockedClientConnection{localAddress=[127.0.0.1]:40001, super=ClientConnection{alive=true, connectionId=1, channel=null, remoteAddress=[127.0.0.1]:5701, lastReadTime=2024-02-11 08:49:57.505, lastWriteTime=2024-02-11 08:49:57.504, closedTime=never}}
08:49:57,505  INFO |entryViews_emptyPartition[format:BINARY]| - [ClientConnectionManager] Thread-20824 - hz.client_711 [dev] [5.3.7-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5701:bc4bad8c-f35e-4ac2-9b92-e2bad7d5ede3, connection: MockedClientConnection{localAddress=[127.0.0.1]:40002, super=ClientConnection{alive=false, connectionId=2, channel=null, remoteAddress=[127.0.0.1]:5701, lastReadTime=2024-02-11 08:49:57.504, lastWriteTime=2024-02-11 08:49:57.503, closedTime=2024-02-11 08:49:57.505}}
08:49:57,505  WARN |entryViews_emptyPartition[format:BINARY]| - [TestClientRegistry$MockedServerConnection] pool-2011-thread-1 - Server connection closed: null
08:49:57,505  INFO |entryViews_emptyPartition[format:BINARY]| - [ClientConnectionManager] Thread-20824 - hz.client_711 [dev] [5.3.7-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5702:93d48378-1910-45c1-80de-3d9f0db15b8a, connection: MockedClientConnection{localAddress=[127.0.0.1]:40001, super=ClientConnection{alive=false, connectionId=1, channel=null, remoteAddress=[127.0.0.1]:5702, lastReadTime=2024-02-11 08:49:57.505, lastWriteTime=2024-02-11 08:49:57.504, closedTime=2024-02-11 08:49:57.505}}
08:49:57,505  INFO |entryViews_emptyPartition[format:BINARY]| - [MockServer] pool-2011-thread-1 - [127.0.0.1]:5701 [dev] [5.3.7-SNAPSHOT] Removed connection to endpoint: [address=[127.0.0.1]:40002, uuid=5324805c-adb3-4274-85a4-af54ea51a418], connection: MockedNodeConnection{ remoteAddress = [127.0.0.1]:40002, localAddress = [127.0.0.1]:5701, connectionId = 2}
08:49:57,505  INFO |entryViews_emptyPartition[format:BINARY]| - [LifecycleService] Thread-20824 - hz.client_711 [dev] [5.3.7-SNAPSHOT] HazelcastClient 5.3.7-SNAPSHOT (20240211) is CLIENT_DISCONNECTED
08:49:57,506  INFO |testRemove[format:BINARY]| - [ClientClusterService] hz.client_714.event-48856 - hz.client_714 [dev] [5.3.7-SNAPSHOT] 

Members [1] {
	Member [127.0.0.1]:5701 - f84aa9d1-4425-4cc5-90af-634051e59fec
}

08:49:57,506  WARN |entryViews_emptyPartition[format:BINARY]| - [TwoWayBlockableExecutor] pool-2011-thread-1 - Dropping incoming runnable since other end closed. Server Closed EOF. MockedClientConnection{localAddress=[127.0.0.1]:40002, super=ClientConnection{alive=false, connectionId=2, channel=null, remoteAddress=[127.0.0.1]:5701, lastReadTime=2024-02-11 08:49:57.504, lastWriteTime=2024-02-11 08:49:57.503, closedTime=2024-02-11 08:49:57.505}}
08:49:57,506  WARN |entryViews_emptyPartition[format:BINARY]| - [TestClientRegistry$MockedServerConnection] pool-2007-thread-1 - Server connection closed: null
08:49:57,506  INFO |entryViews_emptyPartition[format:BINARY]| - [ClientEndpointManager] hz.ClientReplicatedMapTest_romantic_poincare.event-48743 - [127.0.0.1]:5701 [dev] [5.3.7-SNAPSHOT] Destroying ClientEndpoint{connection=MockedNodeConnection{ remoteAddress = [127.0.0.1]:40002, localAddress = [127.0.0.1]:5701, connectionId = 2}, clientUuid=5324805c-adb3-4274-85a4-af54ea51a418, clientName=hz.client_711, authenticated=true, clientVersion=5.3.7-SNAPSHOT, creationTime=1707641397393, latest clientAttributes=lastStatisticsCollectionTime=1707641397408,enterprise=false,clientType=JVM,clientVersion=5.3.7-SNAPSHOT,clusterConnectionTimestamp=1707641397381,clientAddress=127.0.0.1,clientName=hz.client_711,credentials.principal=null,os.committedVirtualMemorySize=32762081280,os.freePhysicalMemorySize=651261718528,os.freeSwapSpaceSize=10736623616,os.maxFileDescriptorCount=1048576,os.openFileDescriptorCount=710,os.processCpuTime=4748890000000,os.systemLoadAverage=8.05,os.totalPhysicalMemorySize=808603877376,os.totalSwapSpaceSize=10737410048,runtime.availableProcessors=8,runtime.freeMemory=5175064720,runtime.maxMemory=8410103808,runtime.totalMemory=8410103808,runtime.uptime=5425238,runtime.usedMemory=3235039088, labels=[]}
08:49:57,506  INFO |entryViews_emptyPartition[format:BINARY]| - [MockServer] pool-2007-thread-1 - [127.0.0.1]:5702 [dev] [5.3.7-SNAPSHOT] Removed connection to endpoint: [address=[127.0.0.1]:40001, uuid=5324805c-adb3-4274-85a4-af54ea51a418], connection: MockedNodeConnection{ remoteAddress = [127.0.0.1]:40001, localAddress = [127.0.0.1]:5702, connectionId = 1}
08:49:57,506  WARN |entryViews_emptyPartition[format:BINARY]| - [TwoWayBlockableExecutor] pool-2007-thread-1 - Dropping incoming runnable since other end closed. Server Closed EOF. MockedClientConnection{localAddress=[127.0.0.1]:40001, super=ClientConnection{alive=false, connectionId=1, channel=null, remoteAddress=[127.0.0.1]:5702, lastReadTime=2024-02-11 08:49:57.505, lastWriteTime=2024-02-11 08:49:57.504, closedTime=2024-02-11 08:49:57.505}}
08:49:57,506  INFO |testPutReturnValueDeserialization[format:BINARY]| - [MetricsConfigHelper] testPutReturnValueDeserialization - [127.0.0.1]:5701 [dev] [5.3.7-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
08:49:57,506  INFO |entryViews_emptyPartition[format:BINARY]| - [ClientEndpointManager] hz.ClientReplicatedMapTest_gracious_poincare.event-48778 - [127.0.0.1]:5702 [dev] [5.3.7-SNAPSHOT] Destroying ClientEndpoint{connection=MockedNodeConnection{ remoteAddress = [127.0.0.1]:40001, localAddress = [127.0.0.1]:5702, connectionId = 1}, clientUuid=5324805c-adb3-4274-85a4-af54ea51a418, clientName=hz.client_711, authenticated=true, clientVersion=5.3.7-SNAPSHOT, creationTime=1707641396320, latest clientAttributes=null, labels=[]}
08:49:57,507  INFO |testPutReturnValueDeserialization[format:BINARY]| - [TpcServerBootstrap] testPutReturnValueDeserialization - [127.0.0.1]:5701 [dev] [5.3.7-SNAPSHOT] TPC: disabled
08:49:57,507  INFO |entryViews_emptyPartition[format:BINARY]| - [LifecycleService] Thread-20824 - hz.client_711 [dev] [5.3.7-SNAPSHOT] HazelcastClient 5.3.7-SNAPSHOT (20240211) is SHUTDOWN
08:49:57,507  INFO |testNearCacheInvalidation[format:BINARY]| - [MetricsConfigHelper] testNearCacheInvalidation - [127.0.0.1]:5701 [dev] [5.3.7-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
08:49:57,508  INFO |testKeySet[format:BINARY]| - [MetricsConfigHelper] testKeySet - [127.0.0.1]:5701 [dev] [5.3.7-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
08:49:57,509  INFO |testPutNullReturnValueDeserialization[format:BINARY]| - [MetricsConfigHelper] testPutNullReturnValueDeserialization - [127.0.0.1]:5701 [dev] [5.3.7-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-5.maintenance-ZuluJDK8/123/

**Comment by olukas** [comment]
Failed again on _5.3.z_ with oracle-8 (little-endian): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-little-endian/290/testReport/com.hazelcast.client.replicatedmap/ClientReplicatedMapTest/testPutAllWithMetadataAsync_format_OBJECT_/

**Comment by srknzl** [comment]
closed in https://github.com/hazelcast/hazelcast-mono/commit/d160431eb4c8b7e22ede5f266274caed2b82bab3
