### ISSUE TITLE
com.hazelcast.partition.strategy.AttributePartitioningStrategyIntegrationTest

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#26256]
_master_ (commit 10a49707caee9535cb8e2db6641319c7cf853681)

Failed on Openj9-17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Openj9-17/107/testReport/com.hazelcast.partition.strategy/AttributePartitioningStrategyIntegrationTest/

Following tests failed:
- `com.hazelcast.partition.strategy.AttributePartitioningStrategyIntegrationTest.testCompactObject`
- `com.hazelcast.partition.strategy.AttributePartitioningStrategyIntegrationTest.testJavaObject`

<details><summary>Stacktrace for testCompactObject:</summary>

```
java.lang.AssertionError: expected:<100> but was:<200>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at com.hazelcast.partition.strategy.AttributePartitioningStrategyIntegrationTest.testCompactObject(AttributePartitioningStrategyIntegrationTest.java:121)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:858)
```

</details>

<details><summary>Stacktrace for testJavaObject:</summary>

```
java.lang.NullPointerException: Cannot invoke "java.lang.Object.toString()" because "value" is null
	at java.base/java.lang.StringConcatHelper.stringOf(StringConcatHelper.java:453)
	at com.hazelcast.jet.SimpleTestInClusterSupport.lambda$supportAfter$6(SimpleTestInClusterSupport.java:173)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1242)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:522)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:512)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:239)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at com.hazelcast.jet.SimpleTestInClusterSupport.supportAfter(SimpleTestInClusterSupport.java:174)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:381)
	at com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37)
	at com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:104)
	at com.hazelcast.test.metrics.MetricsRule$1.evaluate(MetricsRule.java:63)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:53)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:32)
	at com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:41)
	at com.hazelcast.test.OverridePropertyRule$1.evaluate(OverridePropertyRule.java:69)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:858)
```

</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-Openj9-17/107/

**Comment by AleksPeychev** [comment]
Failed again on _master_ with openj9-17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Openj9-17/122/testReport/junit/com.hazelcast.partition.strategy/AttributePartitioningStrategyIntegrationTest/
Following tests failed:
`com.hazelcast.partition.strategy.AttributePartitioningStrategyIntegrationTest.testCompactObject`
`com.hazelcast.partition.strategy.AttributePartitioningStrategyIntegrationTest.testDynamicPartitioningAttributesConfiguration`
`com.hazelcast.partition.strategy.AttributePartitioningStrategyIntegrationTest.testJavaObject`
`com.hazelcast.partition.strategy.AttributePartitioningStrategyIntegrationTest.testIDSObject`
`com.hazelcast.partition.strategy.AttributePartitioningStrategyIntegrationTest.testPortableObject`
`com.hazelcast.partition.strategy.AttributePartitioningStrategyIntegrationTest.testJsonObject`

**Comment by JackPGreen** [comment]
I _think_ this is the same issue reported [here](https://github.com/hazelcast/hazelcast/issues/26327#issuecomment-2104426731).

_Hopefully_ fixed as part of https://github.com/hazelcast/DevOps/pull/285
