### ISSUE TITLE
com.hazelcast.jet.impl.util.ReflectionUtilsTest.testGetStackTrace

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hazelcast#26259]
_master_ (commit 510829c224555cfed73cb9e7d56d684ecfe22a62)

Failed on Windows - MicrosoftJDK17: https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK17/103/testReport/junit/com.hazelcast.jet.impl.util/ReflectionUtilsTest/testGetStackTrace/
<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: 

Expecting actual:
  "com.hazelcast.jet.impl.util.ReflectionUtilsTest.testGetStackTrace(ReflectionUtilsTest.java:209)
	java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.base/java.lang.reflect.Method.invoke(Method.java:568)
	org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	java.base/java.lang.Thread.run(Thread.java:833)"
to start with:
  "	java.base/java.lang.Thread.run"

	at com.hazelcast.jet.impl.util.ReflectionUtilsTest.testGetStackTrace(ReflectionUtilsTest.java:217)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)

```
</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: when_findPropertySetter_nonExistent_then_returnsNull in 0.662 seconds.

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-Windows-MicrosoftJDK17/103/

**Comment by JackPGreen** [comment]
New, introduced in https://github.com/hazelcast/hazelcast-mono/pull/758
