### ISSUE TITLE
com.hazelcast.client.tpc.TpcChannelConnectorTest [HZ-4567]

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hazelcast#26262]
_master_ (commit e3fc5f5caca4b27388dd91cf582146ceb0349e0e)

Failed on zing-21: https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK21/4/testReport/junit/com.hazelcast.client.tpc/TpcChannelConnectorTest/

<details><summary>Stacktrace:</summary>

```
Wanted but not invoked:
channel.write(<any>);
-> at com.hazelcast.client.tpc.TpcChannelConnectorTest.testConnector_whenAuthenticationMessageCannotBeSent(TpcChannelConnectorTest.java:234)
Actually, there were zero interactions with this mock.

	at com.hazelcast.client.tpc.TpcChannelConnectorTest.testConnector_whenAuthenticationMessageCannotBeSent(TpcChannelConnectorTest.java:234)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.lang.Thread.run(Thread.java:1584)

```
</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: testConnector_whenChannelCreationFails in 1.815 seconds.
Started Running Test: testConnector_whenChannelCreationsFails_afterSomeChannelsAreEstablished
Started Running Test: testConnector_translate

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-ZingJDK21/4/

**Comment by Patras3** [comment]
Failed again on _master_ with zing-21: https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK21/7/testReport/junit/com.hazelcast.client.tpc/TpcChannelConnectorTest/
