### ISSUE TITLE
com.hazelcast.jet.sql.impl.connector.keyvalue.KvMetadataResolversTest [HZ-4464]

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hazelcast#26261]
_master_ (commit e3fc5f5caca4b27388dd91cf582146ceb0349e0e)

Failed on zing-21: https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK21/4/testReport/junit/com.hazelcast.jet.sql.impl.connector.keyvalue/KvMetadataResolversTest/

<details><summary>Stacktrace:</summary>

```
java.lang.NullPointerException: Cannot invoke "com.hazelcast.jet.sql.impl.CalciteSqlOptimizer.relationsStorage()" because the return value of "com.hazelcast.sql.impl.SqlServiceImpl.getOptimizer()" is null
	at com.hazelcast.jet.sql.impl.connector.keyvalue.KvMetadataResolvers.resolveAndValidateFields(KvMetadataResolvers.java:94)
	at com.hazelcast.jet.sql.impl.connector.keyvalue.KvMetadataResolversTest.when_valueFieldsEmpty_then_doesNotFail(KvMetadataResolversTest.java:203)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at junitparams.JUnitParamsRunner.runChild(JUnitParamsRunner.java:449)
	at junitparams.JUnitParamsRunner.runChild(JUnitParamsRunner.java:393)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-ZingJDK21/4/

**Comment by k-jamroz** [comment]
This is probably related to Mockito issues. This test mocks some classes. @shultseva WDYT?

**Comment by shultseva** [comment]
yes, this is one more Mockito problem
