### ISSUE TITLE
com.hazelcast.jet.kafka.connect.impl.ReadKafkaConnectPTest.should_produce_watermarks(int)[2] 1

### ISSUE THREAD

**Issue by AleksPeychev** [hazelcast/hazelcast#26268]
_master_ (commit c166a99f95531e8d5a1b9b31d1f82f21c96f32c1)
Failed on oracle-21: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-OracleJDK21/5/testReport/junit/com.hazelcast.jet.kafka.connect.impl/ReadKafkaConnectPTest/should_produce_watermarks_int__2__1/
<details><summary>Stacktrace:</summary>

```
org.opentest4j.AssertionFailedError: expected: <true> but was: <false>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertTrue.failNotTrue(AssertTrue.java:63)
	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:36)
	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:31)
	at org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:183)
	at com.hazelcast.jet.kafka.connect.impl.ReadKafkaConnectPTest.lambda$should_produce_watermarks$2(ReadKafkaConnectPTest.java:133)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1200)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1305)
	at com.hazelcast.jet.kafka.connect.impl.ReadKafkaConnectPTest.should_produce_watermarks(ReadKafkaConnectPTest.java:133)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)

```
</details>

<details><summary>Standard output:</summary>

```
00:57:38,821  INFO || - [MetricsConfigHelper] main - [LOCAL] [dev] [5.4.0-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
00:57:38,822  INFO || - [logo] main - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] 
	o    o     o     o---o   o--o o      o---o     o     o----o o--o--o
	|    |    / \       /         |     /         / \    |         |   
	o----o       o     o   o----o |    o             o   o----o    |   
	|    |  *     \   /           |     \       *     \       |    |   
	o    o *       o o---o   o--o o----o o---o *       o o----o    o   
00:57:38,822  INFO || - [system] main - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Copyright (c) 2008-2024, Hazelcast, Inc. All Rights Reserved.
00:57:38,822  INFO || - [system] main - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Hazelcast Platform 5.4.0-SNAPSHOT (20240224) starting at [127.0.0.1]:5701
00:57:38,822  INFO || - [system] main - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Cluster name: dev
00:57:38,822  INFO || - [system] main - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed. For more information, see the documentation for Integrity Checker.
00:57:38,822  INFO || - [system] main - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Jet is enabled
00:57:38,826  INFO || - [MetricsConfigHelper] main - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
00:57:38,838  WARN || - [CPSubsystem] main - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
00:57:38,851  INFO || - [JetServiceBackend] main - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Setting number of cooperative threads and default parallelism to 2
00:57:38,860  INFO || - [Diagnostics] main - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
00:57:38,861  INFO || - [LifecycleService] main - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] [127.0.0.1]:5701 is STARTING
00:57:38,862  INFO || - [ClusterService] main - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] 

Members {size:1, ver:1} [
	Member [127.0.0.1]:5701 - b87a4f7a-c950-47da-8045-e2f0c8a37244 this
]

00:57:38,862  INFO || - [JobCoordinationService] main - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Jet started scanning for jobs
00:57:38,862 DEBUG || - [JobCoordinationService] hz.unruffled_gould.cached.thread-1 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
00:57:38,863  INFO || - [LifecycleService] main - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] [127.0.0.1]:5701 is STARTED
00:57:38,866  INFO || - [PartitionStateManager] main - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Initializing cluster partition table arrangement...
00:57:38,868 DEBUG || - [SourceConnectorWrapper] main - Initializing connector 'some-name' of class 'com.hazelcast.jet.kafka.connect.impl.DummySourceConnector'
00:57:38,868 DEBUG || - [SourceConnectorWrapper] main - Starting connector 'some-name'. Below are the propertiesFromUser
00:57:38,868 DEBUG || - [SourceConnectorWrapper] main - Creating task runner 'some-name'
00:57:38,868  INFO || - [SourceConnectorWrapper] main - Updating tasks configuration
00:57:38,868 DEBUG || - [SourceConnectorWrapper] main - sourceConnector index 0 taskConfig={connector.class=com.hazelcast.jet.kafka.connect.impl.DummySourceConnector, name=some-name, task.id=0, dummy.source.connector.items.size=5, tasks.max=2}
00:57:38,868 DEBUG || - [SourceConnectorWrapper] main - sourceConnector index 1 taskConfig={connector.class=com.hazelcast.jet.kafka.connect.impl.DummySourceConnector, name=some-name, task.id=1, dummy.source.connector.items.size=5, tasks.max=2}
00:57:38,868  INFO || - [SourceConnectorWrapper] main - Publishing TaskConfigTopic
00:57:38,869  INFO || - [SourceConnectorWrapper] main - 2 task configs were sent
00:57:38,872 DEBUG || - [SourceConnectorWrapper] main - Initializing connector 'some-name' of class 'com.hazelcast.jet.kafka.connect.impl.DummySourceConnector'
00:57:38,873 DEBUG || - [SourceConnectorWrapper] main - Starting connector 'some-name'. Below are the propertiesFromUser
00:57:38,873  INFO || - [SourceConnectorWrapper] hz.unruffled_gould.async.thread-1 - Received TaskConfigTopic message
00:57:38,873 DEBUG || - [SourceConnectorWrapper] main - Creating task runner 'some-name'
00:57:38,875  INFO || - [SourceConnectorWrapper] hz.unruffled_gould.async.thread-2 - Received TaskConfigTopic message
00:57:38,875  INFO || - [SourceConnectorWrapper] hz.unruffled_gould.async.thread-2 - Updating taskRunner with processorOrder = 1 with taskConfig={connector.class=com.hazelcast.jet.kafka.connect.impl.DummySourceConnector, tasks.max=2, name=some-name, task.id=1, dummy.source.connector.items.size=5}
00:57:38,875  INFO || - [SourceConnectorWrapper] hz.unruffled_gould.async.thread-1 - Updating taskRunner with processorOrder = 0 with taskConfig={connector.class=com.hazelcast.jet.kafka.connect.impl.DummySourceConnector, tasks.max=2, name=some-name, task.id=0, dummy.source.connector.items.size=5}
00:57:38,875  INFO || - [TaskRunner some-name-task-0] hz.unruffled_gould.async.thread-1 - Updating task 'some-name-task-0' configuration
00:57:38,875 DEBUG || - [SourceConnectorWrapper] main - requestTaskReconfiguration is skipped because Source Connector is not master
00:57:38,876  INFO || - [testVertex#0] main - Entering ReadKafkaConnectP init processorOrder=0 localProcessorIndex= 0, globalProcessorIndex=0, snapshotsEnabled=false
00:57:38,963 DEBUG || - [JobRepository] hz.unruffled_gould.cached.thread-1 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
00:57:43,964 DEBUG || - [JobRepository] hz.unruffled_gould.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
00:57:48,964 DEBUG || - [JobRepository] hz.unruffled_gould.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
00:57:53,964 DEBUG || - [JobRepository] hz.unruffled_gould.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
00:57:58,964 DEBUG || - [JobRepository] hz.unruffled_gould.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
00:58:03,964 DEBUG || - [JobRepository] hz.unruffled_gould.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
00:58:08,965 DEBUG || - [JobRepository] hz.unruffled_gould.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
00:58:13,965 DEBUG || - [JobRepository] hz.unruffled_gould.cached.thread-9 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
00:58:18,964 DEBUG || - [JobRepository] hz.unruffled_gould.cached.thread-10 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
00:58:23,964 DEBUG || - [JobRepository] hz.unruffled_gould.cached.thread-9 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
00:58:28,964 DEBUG || - [JobRepository] hz.unruffled_gould.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
00:58:33,965 DEBUG || - [JobRepository] hz.unruffled_gould.cached.thread-1 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
00:58:38,965 DEBUG || - [JobRepository] hz.unruffled_gould.cached.thread-13 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
00:58:43,965 DEBUG || - [JobRepository] hz.unruffled_gould.cached.thread-13 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
00:58:48,966 DEBUG || - [JobRepository] hz.unruffled_gould.cached.thread-10 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
00:58:53,966 DEBUG || - [JobRepository] hz.unruffled_gould.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
00:58:58,966 DEBUG || - [JobRepository] hz.unruffled_gould.cached.thread-11 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
00:59:03,967 DEBUG || - [JobRepository] hz.unruffled_gould.cached.thread-13 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
00:59:08,973 DEBUG || - [JobRepository] hz.unruffled_gould.cached.thread-12 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
00:59:13,974 DEBUG || - [JobRepository] hz.unruffled_gould.cached.thread-14 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
00:59:18,973 DEBUG || - [JobRepository] hz.unruffled_gould.cached.thread-12 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
00:59:23,974 DEBUG || - [JobRepository] hz.unruffled_gould.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
00:59:28,974 DEBUG || - [JobRepository] hz.unruffled_gould.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
00:59:33,974 DEBUG || - [JobRepository] hz.unruffled_gould.cached.thread-14 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
00:59:38,975 DEBUG || - [JobRepository] hz.unruffled_gould.cached.thread-16 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
00:59:39,058 DEBUG || - [SourceConnectorWrapper] main - Stopping connector 'some-name'
00:59:39,060 DEBUG || - [SourceConnectorWrapper] main - Connector 'some-name' stopped
00:59:39,060  INFO || - [testVertex#0] main - Closed ReadKafkaConnectP
00:59:39,061  INFO || - [LifecycleService] main - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
00:59:39,062 DEBUG || - [JobCoordinationService] main - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Added a shutting-down member: b87a4f7a-c950-47da-8045-e2f0c8a37244
00:59:39,062 DEBUG || - [JetServiceBackend] ForkJoinPool.commonPool-worker-3 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] All non-master members were informed about the shutdown of member b87a4f7a-c950-47da-8045-e2f0c8a37244
00:59:39,076  INFO || - [MigrationManager] hz.unruffled_gould.cached.thread-15 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Shutdown request of Member [127.0.0.1]:5701 - b87a4f7a-c950-47da-8045-e2f0c8a37244 this is handled
00:59:39,079  INFO || - [Node] main - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Shutting down connection manager...
00:59:39,080  INFO || - [Node] main - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Shutting down node engine...
00:59:39,089  INFO || - [NodeExtension] main - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Destroying node NodeExtension.
00:59:39,089  INFO || - [Node] main - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Hazelcast Shutdown is completed in 28 ms.
00:59:39,089  INFO || - [LifecycleService] main - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-OracleJDK21/5/

**Comment by olukas** [comment]
Closing the test failure - it hasn't failed in the last 3 months.
