### ISSUE TITLE
com.hazelcast.jet.sql.impl.expression.math.MinusOperatorIntegrationTest and PlusOperatorIntegrationTest

### ISSUE THREAD

**Issue by AleksPeychev** [hazelcast/hazelcast#26273]
_5.3.z_ (commit c2482d74b8c9118d16cd9f1d844fa68deaf05853)
Failed on oracle-11: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-OracleJDK11/127/testReport/junit/com.hazelcast.jet.sql.impl.expression.math/MinusOperatorIntegrationTest/
and 
https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-OracleJDK11/127/testReport/junit/com.hazelcast.jet.sql.impl.expression.math/PlusOperatorIntegrationTest/
<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: expected:<2023-01-28T00:00> but was:<2023-01-29T00:00>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:120)
	at org.junit.Assert.assertEquals(Assert.java:146)
	at com.hazelcast.jet.sql.impl.expression.ExpressionTestSupport.checkValue0(ExpressionTestSupport.java:154)
	at com.hazelcast.jet.sql.impl.expression.ExpressionTestSupport.putAndCheckValue(ExpressionTestSupport.java:124)
	at com.hazelcast.jet.sql.impl.expression.math.MinusOperatorIntegrationTest.testDate(MinusOperatorIntegrationTest.java:424)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-5.maintenance-OracleJDK11/127/

**Comment by AleksPeychev** [comment]
Failed again on _master_ with oracle-17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-OracleJDK17/123/testReport/junit/com.hazelcast.jet.sql.impl.expression.math/MinusOperatorIntegrationTest/testDate/

**Comment by JackPGreen** [comment]
Fixed in https://github.com/hazelcast/hazelcast-mono/pull/962

Not backported to `5.3.z` etc as issue only happens on leap-year and `5.3.z` unlikely to be supported by the next one.
