### ISSUE TITLE
com.hazelcast.jet.kafka.connect.KafkaConnectIT.test_scaling

### ISSUE THREAD

**Issue by Patras3** [hazelcast/hazelcast#26276]
_master_ (commit 5764f01c5e4d7d2b1dc728eb3e1bbdd716a9c8f7)

Failed on oracle-17 (force-offload): https://jenkins.hazelcast.com/job/Hazelcast-master-force-offload/88/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectIT/test_scaling/
<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: 

Expecting actual:
  0L
to be greater than:
  1000L

	at com.hazelcast.jet.kafka.connect.KafkaConnectIT.lambda$test_scaling$4(KafkaConnectIT.java:292)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1200)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1305)
	at com.hazelcast.jet.kafka.connect.KafkaConnectIT.test_scaling(KafkaConnectIT.java:291)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:842)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-force-offload/88/

**Comment by olukas** [comment]
Failed again on _master_ with Windows - MicrosoftJDK17: https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK17/106/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectIT/test_scaling/

**Comment by orcunc** [comment]
I am closing this issue for now after the PR is merged. Let's see if it repeats again
