### ISSUE TITLE
com.hazelcast.spring , cache , context, hibernate , hotrestart , jet, replicatedmap , security, springaware , transaction

### ISSUE THREAD

**Issue by AleksPeychev** [hazelcast/hazelcast#26278]
_master_ (commit 82589ae82e8358b6e625411b9e5b9641f8526cee)
Failed on oracle-17: 

- https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-spring4/36/testReport/junit/com.hazelcast.spring/
- https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-spring4/36/testReport/junit/com.hazelcast.cache/
- https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-spring4/36/testReport/junit/com.hazelcast.spring.context/
- https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-spring4/36/testReport/junit/com.hazelcast.spring.hibernate/
- https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-spring4/36/testReport/junit/com.hazelcast.spring/
- https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-spring4/36/testReport/junit/com.hazelcast.spring.jet/
- https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-spring4/36/testReport/junit/com.hazelcast.spring.replicatedmap/
- https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-spring4/36/testReport/junit/com.hazelcast.spring.security/
- https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-spring4/36/testReport/junit/com.hazelcast.spring.springaware/
- https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-spring4/36/testReport/junit/com.hazelcast.spring.transaction/

<details><summary>Stacktrace:</summary>

```
java.lang.NullPointerException: Cannot invoke "com.hazelcast.client.impl.clientside.HazelcastClientProxy.getClientConfig()" because "this.hazelcastReliableTopic" is null
	at com.hazelcast.spring.TestClientApplicationContext.testReliableTopicConfig(TestClientApplicationContext.java:548)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:842)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-spring4/36/

**Comment by AleksPeychev** [comment]
Spring 4 is not supported any more. Jenkins job for Spring 5 is introduced.
