### ISSUE TITLE
com.hazelcast.jet.sql_nightly.SqlSTSInnerEquiJoinFaultToleranceStressTest.stressTest

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#26287]
_master_ (commit 2eba02750c3462f6b41bc5a9c145cc52e05259de)

Failed on OracleJDK21: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-OracleJDK21-nightly/8/testReport/com.hazelcast.jet.sql_nightly/SqlSTSInnerEquiJoinFaultToleranceStressTest/stressTest_processingGuarantee_atLeastOnce__restartGraceful_true_/

Failed in variant `com.hazelcast.jet.sql_nightly.SqlSTSInnerEquiJoinFaultToleranceStressTest.stressTest[processingGuarantee:atLeastOnce, restartGraceful:true]`

<details><summary>Stacktrace:</summary>

```
java.lang.RuntimeException: java.lang.AssertionError: No more snapshots produced in 30 seconds
	at com.hazelcast.jet.sql_nightly.SqlSTSInnerEquiJoinFaultToleranceStressTest.after(SqlSTSInnerEquiJoinFaultToleranceStressTest.java:194)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:381)
	at com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37)
	at com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:104)
	at com.hazelcast.test.metrics.MetricsRule$1.evaluate(MetricsRule.java:63)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:53)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:32)
	at com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:41)
	at com.hazelcast.test.OverridePropertyRule$1.evaluate(OverridePropertyRule.java:68)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.AssertionError: No more snapshots produced in 30 seconds
	at com.hazelcast.jet.core.JetTestSupport.lambda$waitForNextSnapshot$6(JetTestSupport.java:438)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1200)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1219)
	at com.hazelcast.jet.core.JetTestSupport.waitForNextSnapshot(JetTestSupport.java:434)
	at com.hazelcast.jet.sql_nightly.SqlSTSInnerEquiJoinFaultToleranceStressTest$JobRestarter.run(SqlSTSInnerEquiJoinFaultToleranceStressTest.java:279)
```

</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-OracleJDK21-nightly/8/Hazelcast-master-OracleJDK21-nightly-8.zip

**Comment by Fly-Style** [comment]
3+ months without failures = closing.
