### ISSUE TITLE
com.hazelcast.internal.partition.MigrationInvocationsSafetyTest

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#26286]
_master_ (commit 2eba02750c3462f6b41bc5a9c145cc52e05259de)

Failed on oracle-17 (sonar build): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/420/testReport/com.hazelcast.internal.partition/MigrationInvocationsSafetyTest/

Following tests failed:
- `com.hazelcast.internal.partition.MigrationInvocationsSafetyTest.promotionCommit_shouldBeRetried_whenTargetNotResponds`
- `com.hazelcast.internal.partition.MigrationInvocationsSafetyTest.migrationCommit_shouldBeRetried_whenTargetNotResponds`
- `com.hazelcast.internal.partition.MigrationInvocationsSafetyTest.promotionCommit_shouldRollback_whenTargetCrashes`

<details><summary>Stacktrace:</summary>

```
java.lang.NoSuchFieldException: memberHeartbeatTimeoutMillis
	at java.base/java.lang.Class.getDeclaredField(Class.java:2610)
	at com.hazelcast.internal.partition.MigrationInvocationsSafetyTest.setMigrationCommitTimeoutMillis(MigrationInvocationsSafetyTest.java:419)
	at com.hazelcast.internal.partition.MigrationInvocationsSafetyTest.promotionCommit_shouldBeRetried_whenTargetNotResponds(MigrationInvocationsSafetyTest.java:340)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:842)
```

</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-sonar/420/

**Comment by k-jamroz** [comment]
Caused by mockito-related refactor + use of reflection in the test
