### ISSUE TITLE
com.hazelcast.jet.sql.impl.connector.kafka.SqlAvroSchemaEvolutionTest [HZG-44]

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hazelcast#26296]
_master_ (commit 6832418a4a2b14fb4b8982df28047f9f459214e4)

Failed on oracle-17: https://jenkins.hazelcast.com/job/Hazelcast-master-Kafka-confluent-platform-7.6.z/3/testReport/junit/com.hazelcast.jet.sql.impl.connector.kafka/SqlAvroSchemaEvolutionTest/

<details><summary>Stacktrace:</summary>

```
java.lang.NoClassDefFoundError: Could not initialize class io.confluent.kafka.schemaregistry.storage.encoder.MetadataEncoderService
	at io.confluent.kafka.schemaregistry.storage.KafkaSchemaRegistry.<init>(KafkaSchemaRegistry.java:224)
	at io.confluent.kafka.schemaregistry.rest.SchemaRegistryRestApplication.initSchemaRegistry(SchemaRegistryRestApplication.java:73)
	at io.confluent.kafka.schemaregistry.rest.SchemaRegistryRestApplication.configureBaseApplication(SchemaRegistryRestApplication.java:103)
	at io.confluent.rest.Application.configureHandler(Application.java:324)
	at io.confluent.rest.ApplicationServer.doStart(ApplicationServer.java:212)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at com.hazelcast.jet.kafka.impl.KafkaTestSupport.createSchemaRegistry(KafkaTestSupport.java:254)
	at com.hazelcast.jet.sql.impl.connector.kafka.KafkaSqlTestSupport.createSchemaRegistry(KafkaSqlTestSupport.java:77)
	at com.hazelcast.jet.sql.impl.connector.kafka.SqlAvroSchemaEvolutionTest.initialize(SqlAvroSchemaEvolutionTest.java:88)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:41)
	at com.hazelcast.test.OverridePropertyRule$1.evaluate(OverridePropertyRule.java:68)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:842)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoClassDefFoundError: com/google/protobuf/GeneratedMessageV3 [in thread "Time-limited test"]
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at com.google.crypto.tink.aead.AeadConfig.<clinit>(AeadConfig.java:59)
	at io.confluent.kafka.schemaregistry.storage.encoder.MetadataEncoderService.<clinit>(MetadataEncoderService.java:81)
	at io.confluent.kafka.schemaregistry.storage.KafkaSchemaRegistry.<init>(KafkaSchemaRegistry.java:224)
	at io.confluent.kafka.schemaregistry.rest.SchemaRegistryRestApplication.initSchemaRegistry(SchemaRegistryRestApplication.java:73)
	at io.confluent.kafka.schemaregistry.rest.SchemaRegistryRestApplication.configureBaseApplication(SchemaRegistryRestApplication.java:103)
	at io.confluent.rest.Application.configureHandler(Application.java:324)
	at io.confluent.rest.ApplicationServer.doStart(ApplicationServer.java:212)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at com.hazelcast.jet.kafka.impl.KafkaTestSupport.createSchemaRegistry(KafkaTestSupport.java:254)
	at com.hazelcast.jet.sql.impl.connector.kafka.KafkaSqlTestSupport.createSchemaRegistry(KafkaSqlTestSupport.java:77)
	at com.hazelcast.jet.sql.impl.connector.kafka.SqlAvroTest.setup(SqlAvroTest.java:137)
	... 5 more

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-Kafka-confluent-platform-7.6.z/3/

**Comment by AleksPeychev** [comment]
Crashed test on _master_ with oracle-21

<details><summary>Stacktrace:</summary>

```
10:32:30 [INFO] Running com.hazelcast.jet.sql.impl.connector.kafka.SqlAvroTest
10:32:30 [INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 s -- in com.hazelcast.jet.sql.impl.connector.kafka.SqlAvroTest
10:32:30 [INFO] Running com.hazelcast.jet.sql.impl.connector.kafka.SqlAvroSchemaEvolutionTest
..........
10:32:41 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.3.0:test (default-test) on project hazelcast-sql: 
10:32:41 [ERROR] 
10:32:41 [ERROR] Please refer to /home/jenkins/jenkins_slave/workspace/Hazelcast-master-OracleJDK21-nightly/hazelcast/hazelcast-sql/target/surefire-reports for the individual test results.
10:32:41 [ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
10:32:41 
[ERROR] The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
10:32:41 [ERROR] Command was /bin/sh -c cd '/home/jenkins/jenkins_slave/workspace/Hazelcast-master-OracleJDK21-nightly/hazelcast/hazelcast-sql' && '/usr/share/jdks/oracle-21/bin/java' '-Xms8g' '-Xmx8g' '--add-exports' 'java.base/jdk.internal.ref=ALL-UNNAMED' '--add-opens' 'jdk.management/com.sun.management.internal=ALL-UNNAMED' '--add-opens' 'java.base/sun.nio.ch=ALL-UNNAMED' '--add-opens' 'java.base/java.lang=ALL-UNNAMED' '--add-opens' 'java.management/sun.management=ALL-UNNAMED' '-Dhazelcast.phone.home.enabled=false' '-Dhazelcast.test.use.network=false' '-Dlog4j.skipJansi=true' '-jar' '/home/jenkins/jenkins_slave/workspace/Hazelcast-master-OracleJDK21-nightly/hazelcast/hazelcast-sql/target/surefire/surefirebooter-20240703071228703_11272.jar' '/home/jenkins/jenkins_slave/workspace/Hazelcast-master-OracleJDK21-nightly/hazelcast/hazelcast-sql/target/surefire' '2024-07-03T01-30-56_287-jvmRun3' 'surefire-20240703071228703_11270tmp' 'surefire_18-20240703071228703_11271tmp'
10:32:41 [ERROR] Error occurred in starting fork, check output in log
10:32:41 [ERROR] Process Exit Code: 1
10:32:41 [ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
10:32:41 [ERROR] Command was /bin/sh -c cd '/home/jenkins/jenkins_slave/workspace/Hazelcast-master-OracleJDK21-nightly/hazelcast/hazelcast-sql' && '/usr/share/jdks/oracle-21/bin/java' '-Xms8g' '-Xmx8g' '--add-exports' 'java.base/jdk.internal.ref=ALL-UNNAMED' '--add-opens' 'jdk.management/com.sun.management.internal=ALL-UNNAMED' '--add-opens' 'java.base/sun.nio.ch=ALL-UNNAMED' '--add-opens' 'java.base/java.lang=ALL-UNNAMED' '--add-opens' 'java.management/sun.management=ALL-UNNAMED' '-Dhazelcast.phone.home.enabled=false' '-Dhazelcast.test.use.network=false' '-Dlog4j.skipJansi=true' '-jar' '/home/jenkins/jenkins_slave/workspace/Hazelcast-master-OracleJDK21-nightly/hazelcast/hazelcast-sql/target/surefire/surefirebooter-20240703071228703_11272.jar' '/home/jenkins/jenkins_slave/workspace/Hazelcast-master-OracleJDK21-nightly/hazelcast/hazelcast-sql/target/surefire' '2024-07-03T01-30-56_287-jvmRun3' 'surefire-20240703071228703_11270tmp' 'surefire_18-20240703071228703_11271tmp'
10:32:41 [ERROR] Error occurred in starting fork, check output in log
10:32:41 [ERROR] Process Exit Code: 1
```
</details>


Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-OracleJDK21-nightly/24/

**Comment by sumnerib** [comment]
Failed again on _master_ with openj9-21: https://jenkins.hazelcast.com/job/Hazelcast-master-Openj9-21-nightly/28/testReport/junit/com.hazelcast.jet.sql.impl.connector.kafka/SqlAvroSchemaEvolutionTest/

Different stacktrace:
```
java.lang.AssertionError: expected:<2> but was:<3>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at com.hazelcast.jet.sql.impl.connector.kafka.SqlAvroSchemaEvolutionTest.insertAndAssertRecords(SqlAvroSchemaEvolutionTest.java:245)
	at com.hazelcast.jet.sql.impl.connector.kafka.SqlAvroSchemaEvolutionTest.test_autoRegisterSchema(SqlAvroSchemaEvolutionTest.java:139)
	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.lang.Thread.run(Thread.java:1595)
```

**Comment by sumnerib** [comment]
Failed again on _master_ with oracle-17 (redpanda): https://jenkins.hazelcast.com/job/Hazelcast-master-Redpanda-23.2.z/47/testReport/junit/com.hazelcast.jet.sql.impl.connector.kafka/SqlAvroSchemaEvolutionTest/

**Comment by sumnerib** [comment]
Failed again on _master_ with openjdk-17: https://jenkins.hazelcast.com/job/Hazelcast-master-ZuluJDK17-nightly/128/testReport/junit/com.hazelcast.jet.sql.impl.connector.kafka/SqlAvroSchemaEvolutionTest/

**Comment by Patras3** [comment]
Failed again on _master_ with openj9-21: https://jenkins.hazelcast.com/job/Hazelcast-master-Openj9-21-nightly/29/testReport/com.hazelcast.jet.sql.impl.connector.kafka/SqlAvroSchemaEvolutionTest/

**Comment by nishaatr** [comment]
Changed Milestone to 6.0.0 to ensure 5.5.0 does not report any Open [issues ](https://github.com/issues?page=1&q=is%3Aopen+milestone%3A5.5.0+repo%3Ahazelcast%2Fhazelcast+repo%3Ahazelcast%2Fhazelcast-enterprise+repo%3Ahazelcast%2Fhazelcast-mono+sort%3Acreated-desc)
Please correct as necessary

**Comment by Patras3** [comment]
Failed again on _master_ with oracle-17 (little-endian): https://jenkins.hazelcast.com/job/Hazelcast-master-nightly-little-endian/89/testReport/com.hazelcast.jet.sql.impl.connector.kafka/SqlAvroSchemaEvolutionTest/
