### ISSUE TITLE
Multiple test failures com.hazelcast.jet.cdc.DebeziumCdcIntegrationTest.postgres , com.hazelcast.jet.cdc.DebeziumCdcIntegrationTest.schemaChangesArePassed [HZ-4651]

### ISSUE THREAD

**Issue by AleksPeychev** [hazelcast/hazelcast#26299]
Two test failures DebeziumCdcIntegrationTest.postgres and DebeziumCdcIntegrationTest.schemaChangesArePassed : 

_master_ (commit c77abb53c903c97b03625457d78cd3cca9f4945d)
Failed on openj9-21: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Openj9-21-nightly/11/testReport/junit/com.hazelcast.jet.cdc/DebeziumCdcIntegrationTest/postgres/
<details><summary>Stacktrace:</summary>

```
org.junit.ComparisonFailure: 
expected:<...=annek@noanswer.org}[
UPDATE:Customer {id=1004, firstName=Anne Marie, lastName=Kretchmar, email=annek@noanswer.org}
INSERT:Customer {id=1005, firstName=Jason, lastName=Bourne, email=jason@bourne.org}
DELETE:Customer {id=1005, firstName=Jason, lastName=Bourne, email=jason@bourne.org}]> but was:<...=annek@noanswer.org}[]>
	at org.junit.Assert.assertEquals(Assert.java:117)
	at org.junit.Assert.assertEquals(Assert.java:146)
	at com.hazelcast.test.HazelcastTestSupport.lambda$assertEqualsEventually$9(HazelcastTestSupport.java:1021)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1200)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1305)
	at com.hazelcast.test.HazelcastTestSupport.assertEqualsEventually(HazelcastTestSupport.java:1021)
	at com.hazelcast.jet.cdc.DebeziumCdcIntegrationTest.postgres(DebeziumCdcIntegrationTest.java:307)
	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.lang.Thread.run(Thread.java:1595)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-Openj9-21-nightly/11/

------------------------------------------------------------------------------------

Failed on openj9-21: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Openj9-21-nightly/11/testReport/junit/com.hazelcast.jet.cdc/DebeziumCdcIntegrationTest/schemaChangesArePassed/
<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: 

Expecting any elements of:
  [key:{{"databaseName":""}}, value:{{"source":{"version":"1.9.8.Final","connector":"mysql","name":"dbserver1","ts_ms":1711349623398,"snapshot":"true","db":"","sequence":null,"table":null,"server_id":0,"gtid":null,"file":"mysql-bin.000003","pos":157,"row":0,"thread":null,"query":null},"databaseName":"","schemaName":null,"ddl":"SET character_set_server=utf8mb4, collation_server=utf8mb4_0900_ai_ci","tableChanges":[]}},
    key:{{"databaseName":"inventory"}}, value:{{"source":{"version":"1.9.8.Final","connector":"mysql","name":"dbserver1","ts_ms":1711349623406,"snapshot":"true","db":"inventory","sequence":null,"table":"addresses","server_id":0,"gtid":null,"file":"mysql-bin.000003","pos":157,"row":0,"thread":null,"query":null},"databaseName":"inventory","schemaName":null,"ddl":"DROP TABLE IF EXISTS `inventory`.`addresses`","tableChanges":[]}},
    key:{{"databaseName":"inventory"}}, value:{{"source":{"version":"1.9.8.Final","connector":"mysql","name":"dbserver1","ts_ms":1711349623407,"snapshot":"true","db":"inventory","sequence":null,"table":"customers","server_id":0,"gtid":null,"file":"mysql-bin.000003","pos":157,"row":0,"thread":null,"query":null},"databaseName":"inventory","schemaName":null,"ddl":"DROP TABLE IF EXISTS `inventory`.`customers`","tableChanges":[]}},
    key:{{"databaseName":"inventory"}}, value:{{"source":{"version":"1.9.8.Final","connector":"mysql","name":"dbserver1","ts_ms":1711349623408,"snapshot":"true","db":"inventory","sequence":null,"table":"geom","server_id":0,"gtid":null,"file":"mysql-bin.000003","pos":157,"row":0,"thread":null,"query":null},"databaseName":"inventory","schemaName":null,"ddl":"DROP TABLE IF EXISTS `inventory`.`geom`","tableChanges":[]}},
    key:{{"databaseName":"inventory"}}, value:{{"source":{"version":"1.9.8.Final","connector":"mysql","name":"dbserver1","ts_ms":1711349623408,"snapshot":"true","db":"inventory","sequence":null,"table":"orders","server_id":0,"gtid":null,"file":"mysql-bin.000003","pos":157,"row":0,"thread":null,"query":null},"databaseName":"inventory","schemaName":null,"ddl":"DROP TABLE IF EXISTS `inventory`.`orders`","tableChanges":[]}},
    key:{{"databaseName":"inventory"}}, value:{{"source":{"version":"1.9.8.Final","connector":"mysql","name":"dbserver1","ts_ms":1711349623409,"snapshot":"true","db":"inventory","sequence":null,"table":"products","server_id":0,"gtid":null,"file":"mysql-bin.000003","pos":157,"row":0,"thread":null,"query":null},"databaseName":"inventory","schemaName":null,"ddl":"DROP TABLE IF EXISTS `inventory`.`products`","tableChanges":[]}},
    key:{{"databaseName":"inventory"}}, value:{{"source":{"version":"1.9.8.Final","connector":"mysql","name":"dbserver1","ts_ms":1711349623409,"snapshot":"true","db":"inventory","sequence":null,"table":"products_on_hand","server_id":0,"gtid":null,"file":"mysql-bin.000003","pos":157,"row":0,"thread":null,"query":null},"databaseName":"inventory","schemaName":null,"ddl":"DROP TABLE IF EXISTS `inventory`.`products_on_hand`","tableChanges":[]}},
    key:{{"databaseName":"inventory"}}, value:{{"source":{"version":"1.9.8.Final","connector":"mysql","name":"dbserver1","ts_ms":1711349623412,"snapshot":"true","db":"inventory","sequence":null,"table":null,"server_id":0,"gtid":null,"file":"mysql-bin.000003","pos":157,"row":0,"thread":null,"query":null},"databaseName":"inventory","schemaName":null,"ddl":"DROP DATABASE IF EXISTS `inventory`","tableChanges":[]}},
    key:{{"databaseName":"inventory"}}, value:{{"source":{"version":"1.9.8.Final","connector":"mysql","name":"dbserver1","ts_ms":1711349623412,"snapshot":"true","db":"inventory","sequence":null,"table":null,"server_id":0,"gtid":null,"file":"mysql-bin.000003","pos":157,"row":0,"thread":null,"query":null},"databaseName":"inventory","schemaName":null,"ddl":"CREATE DATABASE `inventory` CHARSET utf8mb4 COLLATE utf8mb4_0900_ai_ci","tableChanges":[]}},
    key:{{"databaseName":"inventory"}}, value:{{"source":{"version":"1.9.8.Final","connector":"mysql","name":"dbserver1","ts_ms":1711349623413,"snapshot":"true","db":"inventory","sequence":null,"table":null,"server_id":0,"gtid":null,"file":"mysql-bin.000003","pos":157,"row":0,"thread":null,"query":null},"databaseName":"inventory","schemaName":null,"ddl":"USE `inventory`","tableChanges":[]}},
    key:{{"databaseName":"inventory"}}, value:{{"source":{"version":"1.9.8.Final","connector":"mysql","name":"dbserver1","ts_ms":1711349623429,"snapshot":"true","db":"inventory","sequence":null,"table":"addresses","server_id":0,"gtid":null,"file":"mysql-bin.000003","pos":157,"row":0,"thread":null,"query":null},"databaseName":"inventory","schemaName":null,"ddl":"CREATE TABLE `addresses` (
  `id` int NOT NULL AUTO_INCREMENT,
  `customer_id` int NOT NULL,
  `street` varchar(255) NOT NULL,
  `city` varchar(255) NOT NULL,
  `state` varchar(255) NOT NULL,
  `zip` varchar(255) NOT NULL,
  `type` enum('SHIPPING','BILLING','LIVING') NOT NULL,
  PRIMARY KEY (`id`),
  KEY `address_customer` (`customer_id`),
  CONSTRAINT `addresses_ibfk_1` FOREIGN KEY (`customer_id`) REFERENCES `customers` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=17 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci","tableChanges":[]}},
    key:{{"databaseName":"inventory"}}, value:{{"source":{"version":"1.9.8.Final","connector":"mysql","name":"dbserver1","ts_ms":1711349623445,"snapshot":"true","db":"inventory","sequence":null,"table":"customers","server_id":0,"gtid":null,"file":"mysql-bin.000003","pos":157,"row":0,"thread":null,"query":null},"databaseName":"inventory","schemaName":null,"ddl":"CREATE TABLE `customers` (
  `id` int NOT NULL AUTO_INCREMENT,
  `first_name` varchar(255) NOT NULL,
  `last_name` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `email` (`email`)
) ENGINE=InnoDB AUTO_INCREMENT=1005 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci","tableChanges":[{"type":"CREATE","id":"\"inventory\".\"customers\"","table":{"defaultCharsetName":"utf8mb4","primaryKeyColumnNames":["id"],"columns":[{"name":"id","jdbcType":4,"nativeType":null,"typeName":"INT","typeExpression":"INT","charsetName":null,"length":null,"scale":null,"position":1,"optional":false,"autoIncremented":true,"generated":true,"comment":null},{"name":"first_name","jdbcType":12,"nativeType":null,"typeName":"VARCHAR","typeExpression":"VARCHAR","charsetName":"utf8mb4","length":255,"scale":null,"position":2,"optional":false,"autoIncremented":false,"generated":false,"comment":null},{"name":"last_name","jdbcType":12,"nativeType":null,"typeName":"VARCHAR","typeExpression":"VARCHAR","charsetName":"utf8mb4","length":255,"scale":null,"position":3,"optional":false,"autoIncremented":false,"generated":false,"comment":null},{"name":"email","jdbcType":12,"nativeType":null,"typeName":"VARCHAR","typeExpression":"VARCHAR","charsetName":"utf8mb4","length":255,"scale":null,"position":4,"optional":false,"autoIncremented":false,"generated":false,"comment":null}],"comment":null}}]}},
    key:{{"databaseName":"inventory"}}, value:{{"source":{"version":"1.9.8.Final","connector":"mysql","name":"dbserver1","ts_ms":1711349623453,"snapshot":"true","db":"inventory","sequence":null,"table":"geom","server_id":0,"gtid":null,"file":"mysql-bin.000003","pos":157,"row":0,"thread":null,"query":null},"databaseName":"inventory","schemaName":null,"ddl":"CREATE TABLE `geom` (
  `id` int NOT NULL AUTO_INCREMENT,
  `g` geometry NOT NULL,
  `h` geometry DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci","tableChanges":[]}},
    key:{{"databaseName":"inventory"}}, value:{{"source":{"version":"1.9.8.Final","connector":"mysql","name":"dbserver1","ts_ms":1711349623457,"snapshot":"true","db":"inventory","sequence":null,"table":"orders","server_id":0,"gtid":null,"file":"mysql-bin.000003","pos":157,"row":0,"thread":null,"query":null},"databaseName":"inventory","schemaName":null,"ddl":"CREATE TABLE `orders` (
  `order_number` int NOT NULL AUTO_INCREMENT,
  `order_date` date NOT NULL,
  `purchaser` int NOT NULL,
  `quantity` int NOT NULL,
  `product_id` int NOT NULL,
  PRIMARY KEY (`order_number`),
  KEY `order_customer` (`purchaser`),
  KEY `ordered_product` (`product_id`),
  CONSTRAINT `orders_ibfk_1` FOREIGN KEY (`purchaser`) REFERENCES `customers` (`id`),
  CONSTRAINT `orders_ibfk_2` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=10005 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci","tableChanges":[]}},
    key:{{"databaseName":"inventory"}}, value:{{"source":{"version":"1.9.8.Final","connector":"mysql","name":"dbserver1","ts_ms":1711349623472,"snapshot":"true","db":"inventory","sequence":null,"table":"products","server_id":0,"gtid":null,"file":"mysql-bin.000003","pos":157,"row":0,"thread":null,"query":null},"databaseName":"inventory","schemaName":null,"ddl":"CREATE TABLE `products` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `description` varchar(512) DEFAULT NULL,
  `weight` float DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=110 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci","tableChanges":[]}},
    key:{{"databaseName":"inventory"}}, value:{{"source":{"version":"1.9.8.Final","connector":"mysql","name":"dbserver1","ts_ms":1711349623477,"snapshot":"true","db":"inventory","sequence":null,"table":"products_on_hand","server_id":0,"gtid":null,"file":"mysql-bin.000003","pos":157,"row":0,"thread":null,"query":null},"databaseName":"inventory","schemaName":null,"ddl":"CREATE TABLE `products_on_hand` (
  `product_id` int NOT NULL,
  `quantity` int NOT NULL,
  PRIMARY KEY (`product_id`),
  CONSTRAINT `products_on_hand_ibfk_1` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci","tableChanges":[]}},
    key:{{"id":1001}}, value:{{"id":1001,"first_name":"Sally","last_name":"Thomas","email":"sally.thomas@acme.com"}},
    key:{{"id":1002}}, value:{{"id":1002,"first_name":"George","last_name":"Bailey","email":"gbailey@foobar.com"}},
    key:{{"id":1003}}, value:{{"id":1003,"first_name":"Edward","last_name":"Walker","email":"ed@walker.com"}},
    key:{{"id":1004}}, value:{{"id":1004,"first_name":"Anne","last_name":"Kretchmar","email":"annek@noanswer.org"}},
    key:{{"databaseName":"inventory"}}, value:{{"source":{"version":"1.9.8.Final","connector":"mysql","name":"dbserver1","ts_ms":1711349623523,"snapshot":"false","db":"inventory","sequence":null,"table":"tableForSchemaChangesArePassed","server_id":223344,"gtid":null,"file":"mysql-bin.000003","pos":234,"row":0,"thread":null,"query":null},"databaseName":"inventory","schemaName":null,"ddl":"CREATE TABLE `inventory`.`tableForSchemaChangesArePassed` (id INT)","tableChanges":[]}}]
to match given predicate but none did.
	at com.hazelcast.jet.cdc.DebeziumCdcIntegrationTest.lambda$schemaChangesArePassed$10(DebeziumCdcIntegrationTest.java:537)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1200)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1305)
	at com.hazelcast.jet.cdc.DebeziumCdcIntegrationTest.schemaChangesArePassed(DebeziumCdcIntegrationTest.java:533)
	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.lang.Thread.run(Thread.java:1595)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-Openj9-21-nightly/11/

**Comment by AleksPeychev** [comment]
Failed again on _master_ with zing-21: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZingJDK21-nightly/12/testReport/junit/com.hazelcast.jet.cdc/DebeziumCdcIntegrationTest/postgres/

**Comment by AleksPeychev** [comment]
Failed again on _master_ with oracle-17 (force-offload): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-nightly-force-offload/93/testReport/junit/com.hazelcast.jet.cdc/DebeziumCdcIntegrationTest/postgres/

**Comment by AleksPeychev** [comment]
Failed again on _master_ with openj9-21: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Openj9-21-nightly/12/consoleFull#16541235993ee7a23a-abdd-4ede-acea-25daf22ff7f1

**Comment by AleksPeychev** [comment]
Failed again on _master_ with OpenJDK17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-OpenJDK17-nightly-Esxi7/81/testReport/junit/com.hazelcast.jet.cdc/DebeziumCdcIntegrationTest/schemaChangesArePassed/

**Comment by arodionov** [comment]
Failed again on master on PR build: https://jenkins.hazelcast.com/job/Hazelcast-mono-OS-pr-nightly-tests/47/testReport/com.hazelcast.jet.cdc/DebeziumCdcIntegrationTest/schemaChangesArePassed/

**Comment by sumnerib** [comment]
Failed again on _master_ with oracle-17 (force-offload): https://jenkins.hazelcast.com/job/Hazelcast-master-nightly-force-offload/96/testReport/junit/com.hazelcast.jet.cdc/DebeziumCdcIntegrationTest/schemaChangesArePassed/

**Comment by Patras3** [comment]
Failed again on _master_ with oracle-17 (little-endian): https://jenkins.hazelcast.com/job/Hazelcast-master-nightly-little-endian/75/testReport/com.hazelcast.jet.cdc/DebeziumCdcIntegrationTest/schemaChangesArePassed/

**Comment by Patras3** [comment]
Failed again on _master_ with oracle-17 (force-offload): https://jenkins.hazelcast.com/job/Hazelcast-master-nightly-force-offload/97/testReport/com.hazelcast.jet.cdc/DebeziumCdcIntegrationTest/schemaChangesArePassed/

**Comment by olukas** [comment]
Failed again on _master_ with oracle-17 (force-offload): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-nightly-force-offload/98/testReport/com.hazelcast.jet.cdc/DebeziumCdcIntegrationTest/schemaChangesArePassed/

**Comment by olukas** [comment]
Failed again on _master_ with oracle-17 (force-offload): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-nightly-force-offload/99/testReport/com.hazelcast.jet.cdc/DebeziumCdcIntegrationTest/schemaChangesArePassed/

**Comment by AleksPeychev** [comment]
Failed again on _master_ with openj9-21: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Openj9-21-nightly/17/testReport/junit/com.hazelcast.jet.cdc/DebeziumCdcIntegrationTest/schemaChangesArePassed/

**Comment by sumnerib** [comment]
Failed again on _master_ with openj9-21: https://jenkins.hazelcast.com/job/Hazelcast-master-Openj9-21-nightly/18/testReport/com.hazelcast.jet.cdc/DebeziumCdcIntegrationTest/schemaChangesArePassed/

**Comment by sumnerib** [comment]
Fails constantly on `openjdk-17 (zulu)`

**Comment by olukas** [comment]
Failed again on _master_ with oracle-17 (force-offload): https://jenkins.hazelcast.com/job/Hazelcast-master-nightly-force-offload/102/testReport/com.hazelcast.jet.cdc/DebeziumCdcIntegrationTest/schemaChangesArePassed/

**Comment by sumnerib** [comment]
Failed again on _master_ with openj9-21: https://jenkins.hazelcast.com/job/Hazelcast-master-Openj9-21-nightly/23/testReport/com.hazelcast.jet.cdc/DebeziumCdcIntegrationTest/schemaChangesArePassed/

**Comment by Patras3** [comment]
Failed again on _master_ with zing-17: https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK17-nightly/86/testReport/com.hazelcast.jet.cdc/DebeziumCdcIntegrationTest/schemaChangesArePassed/

**Comment by olukas** [comment]
Failed again on _master_ with openj9-21: https://jenkins.hazelcast.com/job/Hazelcast-master-Openj9-21-nightly/26/testReport/com.hazelcast.jet.cdc/DebeziumCdcIntegrationTest/schemaChangesArePassed/

**Comment by olukas** [comment]
It seems to fail constantly on a lot of various platforms. Maybe @TomaszGaweda this is something what you should have on your radar since you did some Debezium related changes recently.

**Comment by TomaszGaweda** [comment]
Thanks @olukas for tagging me - I will take a look. I've refactored those tests a lot in new enterprise connector, will backport those changes to OS connector, should give more stable results.

**Comment by sumnerib** [comment]
Failed again on _5.4.z_ with openj9-21: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-Openj9-21-nightly/12/testReport/junit/com.hazelcast.jet.cdc/DebeziumCdcIntegrationTest/schemaChangesArePassed/

**Comment by olukas** [comment]
Closing the test failure - it doesn't seem to be related to `master` or the latest maintenance stream `5.5.z`. Feel free to reopen test failure if it occurs on `master` or on the latest maintenance stream.

**Comment by AleksPeychev** [comment]
Failed again on _5.5.z_ with openjdk-17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-ZuluJDK17-nightly/138/testReport/junit/com.hazelcast.jet.cdc/DebeziumCdcIntegrationTest/schemaChangesArePassed/

**Comment by AleksPeychev** [comment]
Failed again on _5.4.z_ with oracle-21: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.4.z-OracleJDK17-nightly/14/testReport/com.hazelcast.jet.cdc/DebeziumCdcIntegrationTest/schemaChangesArePassed/
