### ISSUE TITLE
com.hazelcast.map.merge.TSMapMetadataPreservationForBigRecordsOnSplitBrainTest [HZ-4621]

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hazelcast#26295]
_master_ (commit  f2d75b07f40e5751c14f3281479daac69d41a194)

Failed on Corretto-JDK17-arm64: https://jenkins.hazelcast.com/job/Hazelcast-EE-master-CorrettoJDK17-arm64/11/consoleFull

<details><summary>Stacktrace:</summary>

```
18:36:17 [ERROR] Error occurred in starting fork, check output in log
18:36:17 [ERROR] Process Exit Code: 137
18:36:17 [ERROR] Crashed tests:
18:36:17 [ERROR] com.hazelcast.map.merge.TSMapMetadataPreservationForBigRecordsOnSplitBrainTest
18:36:17 [ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
```

</details>

Stdout logs: https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-EE-master-CorrettoJDK17-arm64/11/

**Comment by AleksPeychev** [comment]
Another crashed test com.hazelcast.internal.dynamicconfig.DynamicDeviceConfigUpdateTest 

<details><summary>Standard output:</summary>

```
01:36:17 [ERROR] Crashed tests:
01:36:17 [ERROR] com.hazelcast.map.merge.TSMapMetadataPreservationForBigRecordsOnSplitBrainTest
01:36:17 [ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
01:36:17 [ERROR] Command was /bin/sh -c cd '/home/ec2-user/workspace/Hazelcast-EE-master-CorrettoJDK17-arm64/hazelcast-enterprise' && '/home/ec2-user/.sdkman/candidates/java/17.0.10-amzn/bin/java' '-Xms7g' '-Xmx8g' '--add-exports' 'java.base/jdk.internal.ref=ALL-UNNAMED' '--add-opens' 'java.base/java.nio=ALL-UNNAMED' '--add-opens' 'java.base/sun.nio.ch=ALL-UNNAMED' '--add-opens' 'java.base/java.lang=ALL-UNNAMED' '--add-opens' 'java.base/java.util=ALL-UNNAMED' '--add-opens' 'java.base/java.util.concurrent=ALL-UNNAMED' '--add-opens' 'jdk.management/com.sun.management.internal=ALL-UNNAMED' '--add-opens' 'java.management/sun.management=ALL-UNNAMED' '--add-exports' 'jdk.management/com.ibm.lang.management.internal=ALL-UNNAMED' '-ea' '-Dhazelcast.hidensity.check.freememory=false' '-Dhazelcast.phone.home.enabled=false' '-Dhazelcast.test.use.network=false' '-Dhazelcast.tomcat.shutdown_hazelcast_instance=false' '-Dlog4j.skipJansi=true' '-jar' '/home/ec2-user/workspace/Hazelcast-EE-master-CorrettoJDK17-arm64/hazelcast-enterprise/target/surefire/surefirebooter-20240320214334370_1060.jar' '/home/ec2-user/workspace/Hazelcast-EE-master-CorrettoJDK17-arm64/hazelcast-enterprise/target/surefire' '2024-03-20T21-40-07_156-jvmRun1' 'surefire-20240320214334370_1058tmp' 'surefire_3-20240320214334370_1059tmp'
01:36:17 [ERROR] Error occurred in starting fork, check output in log
01:36:17 [ERROR] Process Exit Code: 137
01:36:17 [ERROR] Crashed tests:
01:36:17 [ERROR] com.hazelcast.map.merge.TSMapMetadataPreservationForBigRecordsOnSplitBrainTest
01:36:17 [ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:643)
01:36:17 [ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:285)
01:36:17 [ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:250)
01:36:17 [ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1241)
01:36:17 [ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1090)
01:36:17 [ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:910)
01:36:17 [ERROR] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
01:36:17 [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
01:36:17 [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
01:36:17 [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
01:36:17 [ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
01:36:17 [ERROR] 	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:190)
01:36:17 [ERROR] 	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:186)
01:36:17 [ERROR] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
01:36:17 [ERROR] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
01:36:17 [ERROR] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
01:36:17 [ERROR] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
01:36:17 [ERROR] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
01:36:17 [ERROR] 	at java.base/java.lang.Thread.run(Thread.java:840)
```

</details>


Failed again on Corretto-JDK17-arm64: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-EE-master-CorrettoJDK17-arm64/12/consoleFull

Stacktrace:
Stdout logs: https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-EE-master-CorrettoJDK17-arm64/12/

**Comment by nishaatr** [comment]
Changed Milestone to 6.0.0 to ensure 5.5.0 does not report any Open [issues ](https://github.com/issues?page=1&q=is%3Aopen+milestone%3A5.5.0+repo%3Ahazelcast%2Fhazelcast+repo%3Ahazelcast%2Fhazelcast-enterprise+repo%3Ahazelcast%2Fhazelcast-mono+sort%3Acreated-desc)
Please correct as necessary

**Comment by olukas** [comment]
Closing the test failure - it hasn't failed in the last 3 months.
