### ISSUE TITLE
Multiple test failures com.hazelcast.jet.sql.impl.connector.kafka.SqlAvroSchemaEvolutionTest.(?) and kafka/SqlAvroTest/___/

### ISSUE THREAD

**Issue by AleksPeychev** [hazelcast/hazelcast#26300]
_master_ (commit ffd95a9ebc1d019dd161e282b9f357f7cb346177)
Failed on oracle-17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Kafka-confluent-platform-7.1.z/102/testReport/junit/com.hazelcast.jet.sql.impl.connector.kafka/SqlAvroSchemaEvolutionTest/___/
<details><summary>Stacktrace:</summary>

```
java.lang.NoClassDefFoundError: Could not initialize class io.confluent.kafka.schemaregistry.storage.encoder.MetadataEncoderService
	at io.confluent.kafka.schemaregistry.storage.KafkaSchemaRegistry.<init>(KafkaSchemaRegistry.java:224)
	at io.confluent.kafka.schemaregistry.rest.SchemaRegistryRestApplication.initSchemaRegistry(SchemaRegistryRestApplication.java:73)
	at io.confluent.kafka.schemaregistry.rest.SchemaRegistryRestApplication.configureBaseApplication(SchemaRegistryRestApplication.java:103)
	at io.confluent.rest.Application.configureHandler(Application.java:324)
	at io.confluent.rest.ApplicationServer.doStart(ApplicationServer.java:212)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at com.hazelcast.jet.kafka.impl.KafkaTestSupport.createSchemaRegistry(KafkaTestSupport.java:254)
	at com.hazelcast.jet.sql.impl.connector.kafka.KafkaSqlTestSupport.createSchemaRegistry(KafkaSqlTestSupport.java:77)
	at com.hazelcast.jet.sql.impl.connector.kafka.SqlAvroSchemaEvolutionTest.initialize(SqlAvroSchemaEvolutionTest.java:88)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:41)
	at com.hazelcast.test.OverridePropertyRule$1.evaluate(OverridePropertyRule.java:68)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:842)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoClassDefFoundError: com/google/protobuf/GeneratedMessageV3 [in thread "Time-limited test"]
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at com.google.crypto.tink.aead.AeadConfig.<clinit>(AeadConfig.java:59)
	at io.confluent.kafka.schemaregistry.storage.encoder.MetadataEncoderService.<clinit>(MetadataEncoderService.java:81)
	at io.confluent.kafka.schemaregistry.storage.KafkaSchemaRegistry.<init>(KafkaSchemaRegistry.java:224)
	at io.confluent.kafka.schemaregistry.rest.SchemaRegistryRestApplication.initSchemaRegistry(SchemaRegistryRestApplication.java:73)
	at io.confluent.kafka.schemaregistry.rest.SchemaRegistryRestApplication.configureBaseApplication(SchemaRegistryRestApplication.java:103)
	at io.confluent.rest.Application.configureHandler(Application.java:324)
	at io.confluent.rest.ApplicationServer.doStart(ApplicationServer.java:212)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at com.hazelcast.jet.kafka.impl.KafkaTestSupport.createSchemaRegistry(KafkaTestSupport.java:254)
	at com.hazelcast.jet.sql.impl.connector.kafka.KafkaSqlTestSupport.createSchemaRegistry(KafkaSqlTestSupport.java:77)
	at com.hazelcast.jet.sql.impl.connector.kafka.SqlAvroTest.setup(SqlAvroTest.java:137)
	... 5 more

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-Kafka-confluent-platform-7.1.z/102/

-------------------------------------------------------

_master_ (commit ffd95a9ebc1d019dd161e282b9f357f7cb346177)
Failed on oracle-17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Kafka-confluent-platform-7.1.z/102/testReport/junit/com.hazelcast.jet.sql.impl.connector.kafka/SqlAvroTest/___/
<details><summary>Stacktrace:</summary>

```
java.lang.NoClassDefFoundError: com/google/protobuf/GeneratedMessageV3
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at com.google.crypto.tink.aead.AeadConfig.<clinit>(AeadConfig.java:59)
	at io.confluent.kafka.schemaregistry.storage.encoder.MetadataEncoderService.<clinit>(MetadataEncoderService.java:81)
	at io.confluent.kafka.schemaregistry.storage.KafkaSchemaRegistry.<init>(KafkaSchemaRegistry.java:224)
	at io.confluent.kafka.schemaregistry.rest.SchemaRegistryRestApplication.initSchemaRegistry(SchemaRegistryRestApplication.java:73)
	at io.confluent.kafka.schemaregistry.rest.SchemaRegistryRestApplication.configureBaseApplication(SchemaRegistryRestApplication.java:103)
	at io.confluent.rest.Application.configureHandler(Application.java:324)
	at io.confluent.rest.ApplicationServer.doStart(ApplicationServer.java:212)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at com.hazelcast.jet.kafka.impl.KafkaTestSupport.createSchemaRegistry(KafkaTestSupport.java:254)
	at com.hazelcast.jet.sql.impl.connector.kafka.KafkaSqlTestSupport.createSchemaRegistry(KafkaSqlTestSupport.java:77)
	at com.hazelcast.jet.sql.impl.connector.kafka.SqlAvroTest.setup(SqlAvroTest.java:137)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:41)
	at com.hazelcast.test.OverridePropertyRule$1.evaluate(OverridePropertyRule.java:68)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:842)
Caused by: java.lang.ClassNotFoundException: com.google.protobuf.GeneratedMessageV3
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 25 more

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-Kafka-confluent-platform-7.1.z/102/

**Comment by JackPGreen** [comment]
`protobuf-bom` was upgraded in https://github.com/hazelcast/hazelcast-mono/pull/1102, which has [breaking changes](https://github.com/protocolbuffers/protobuf/releases/tag/v26.0).

[Confluent requires v3](https://github.com/confluentinc/common/blob/90953a277442931b0df42c129f33df470355c71c/pom.xml#L88), which causes compilation errors - the only solution would be to downgrade `protobuf-bom`.
