### ISSUE TITLE
VM crash or System.exit called on modulepath-tests [HZ-4652]

### ISSUE THREAD

**Issue by AleksPeychev** [hazelcast/hazelcast#26304]
_master_ (commit 009146c751e0ae6e848bd171a9b8688d6db77c5d)
Failed on : 
 - oracle-17 (little-endian): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-nightly-little-endian/73/consoleFull
 -  _master_ with openjdk-17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZuluJDK17-nightly/112/consoleFull
And in Enterprise on Hazelcast Enterprise(Core) :
 - https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-EE-master-CorrettoJDK17-arm64/13/consoleFull
<details><summary>Stacktrace:</summary>

```
08:11:09 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.2.5:test (default-test) on project modulepath-tests: 
08:11:09 [ERROR] 
08:11:09 [ERROR] Please refer to /home/jenkins/jenkins_slave/workspace/Hazelcast-master-nightly-little-endian/hazelcast/modulepath-tests/target/surefire-reports for the individual test results.
08:11:09 [ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
08:11:09 [ERROR] The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
08:11:09 [ERROR] Command was /bin/sh -c cd '/home/jenkins/jenkins_slave/workspace/Hazelcast-master-nightly-little-endian/hazelcast/modulepath-tests' && '/usr/share/jdks/oracle-17/bin/java' '-Xms8g' '-Xmx8g' '--add-exports' 'java.base/jdk.internal.ref=ALL-UNNAMED' '--add-opens' 'jdk.management/com.sun.management.internal=ALL-UNNAMED' '--add-opens' 'java.base/sun.nio.ch=ALL-UNNAMED' '--add-opens' 'java.base/java.lang=ALL-UNNAMED' '--add-opens' 'java.management/sun.management=ALL-UNNAMED' '-Dhazelcast.phone.home.enabled=false' '-Dhazelcast.logging.type=none' '-Dhazelcast.test.use.network=false' '-Dlog4j.skipJansi=true' '@/home/jenkins/jenkins_slave/workspace/Hazelcast-master-nightly-little-endian/hazelcast/modulepath-tests/target/surefire/surefireargs-20240406051109443_15800' '/home/jenkins/jenkins_slave/workspace/Hazelcast-master-nightly-little-endian/hazelcast/modulepath-tests/target/surefire' '2024-04-05T22-08-50_810-jvmRun1' 'surefire-20240406051109443_15798tmp' 'surefire_11-20240406051109443_15799tmp'
08:11:09 [ERROR] Error occurred in starting fork, check output in log
08:11:09 [ERROR] Process Exit Code: 1
08:11:09 [ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
08:11:09 [ERROR] Command was /bin/sh -c cd '/home/jenkins/jenkins_slave/workspace/Hazelcast-master-nightly-little-endian/hazelcast/modulepath-tests' && '/usr/share/jdks/oracle-17/bin/java' '-Xms8g' '-Xmx8g' '--add-exports' 'java.base/jdk.internal.ref=ALL-UNNAMED' '--add-opens' 'jdk.management/com.sun.management.internal=ALL-UNNAMED' '--add-opens' 'java.base/sun.nio.ch=ALL-UNNAMED' '--add-opens' 'java.base/java.lang=ALL-UNNAMED' '--add-opens' 'java.management/sun.management=ALL-UNNAMED' '-Dhazelcast.phone.home.enabled=false' '-Dhazelcast.logging.type=none' '-Dhazelcast.test.use.network=false' '-Dlog4j.skipJansi=true' '@/home/jenkins/jenkins_slave/workspace/Hazelcast-master-nightly-little-endian/hazelcast/modulepath-tests/target/surefire/surefireargs-20240406051109443_15800' '/home/jenkins/jenkins_slave/workspace/Hazelcast-master-nightly-little-endian/hazelcast/modulepath-tests/target/surefire' '2024-04-05T22-08-50_810-jvmRun1' 'surefire-20240406051109443_15798tmp' 'surefire_11-20240406051109443_15799tmp'
08:11:09 [ERROR] Error occurred in starting fork, check output in log
08:11:09 [ERROR] Process Exit Code: 1
08:11:09 [ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:643)
08:11:09 [ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:285)
08:11:09 [ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:250)
08:11:09 [ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1241)
08:11:09 [ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1090)
08:11:09 [ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:910)
08:11:09 [ERROR] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:126)
08:11:09 [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:342)
08:11:09 [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:330)
08:11:09 [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
08:11:09 [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:175)
08:11:09 [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.access$000(MojoExecutor.java:76)
08:11:09 [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor$1.run(MojoExecutor.java:163)
08:11:09 [ERROR] 	at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute(DefaultMojosExecutionStrategy.java:39)
08:11:09 [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:160)
08:11:09 [ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:105)
08:11:09 [ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:73)
08:11:09 [ERROR] 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:53)
08:11:09 [ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:118)
08:11:09 [ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:261)
08:11:09 [ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:173)
08:11:09 [ERROR] 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:101)
08:11:09 [ERROR] 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:910)
08:11:09 [ERROR] 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:283)
08:11:09 [ERROR] 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:206)
08:11:09 [ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
08:11:09 [ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
08:11:09 [ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
08:11:09 [ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
08:11:09 [ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:283)
08:11:09 [ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:226)
08:11:09 [ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:407)
08:11:09 [ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:348)
08:11:09 [ERROR] -> [Help 1]
08:11:09 [ERROR] 
08:11:09 [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
08:11:09 [ERROR] Re-run Maven using the -X switch to enable full debug logging.
08:11:09 [ERROR] 
08:11:09 [ERROR] For more information about the errors and possible solutions, please read the following articles:
08:11:09 [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
08:11:09 [ERROR] 
08:11:09 [ERROR] After correcting the problems, you can resume the build with the command
08:11:09 [ERROR]   mvn <args> -rf :modulepath-tests
```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-nightly-little-endian/73/

**Comment by olukas** [comment]
Crashed again on:
- OracleJDK 17 (force-offload): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-nightly-force-offload/95/console
- ZingJDK21: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZingJDK21-nightly/14/console
- OracleJDK 17 (sonar): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-mono-OS-master-sonar/119/console
- Openj9-21: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Openj9-21-nightly/13/console

<details><summary>Console output:</summary>

```
19:20:44 [INFO]  T E S T S
19:20:44 [INFO] -------------------------------------------------------
19:20:45 [ERROR] Error occurred during initialization of boot layer
19:20:45 [ERROR] java.lang.module.FindException: Unable to derive module descriptor for /home/jenkins/jenkins_slave/workspace/Hazelcast-master-nightly-force-offload/hazelcast/hazelcast/target/hazelcast-5.5.0-SNAPSHOT.jar
19:20:45 [INFO] 
19:20:45 [INFO] Results:
19:20:45 [INFO] 
19:20:45 [INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
19:20:45 [INFO] 
19:20:45 [WARNING] Corrupted channel by directly writing to native stream in forked JVM 1. See FAQ web page and the dump file 
```
</details>

**Comment by JackPGreen** [comment]
@AleksPeychev you've put this on the `5.4` backlog, but I think this is only in `master` (post `5.4` branch creation). Just wanted to check the fix wouldn't need backporting.

**Comment by olukas** [comment]
@JackPGreen backport is not needed since CP -> EE is not part of 5.4.z branch.
