### ISSUE TITLE
com.hazelcast.query.impl.JsonIndexIntegrationTest crashed JVM [HZ-4675]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#26309]
_master_ (commit c80a5d09f3dd556d1fa24dead95d17f5322eb36f)

Failed on OracleJDK17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-OracleJDK17/129/console

<details><summary>Console output:</summary>

```
02:08:33 [INFO] Running com.hazelcast.query.impl.JsonIndexIntegrationTest
02:08:33 [DEBUG] Closing the fork 1 after not saying Good Bye.
...
02:08:34 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.2.5:test (default-test) on project hazelcast: 
02:08:34 [ERROR] 
02:08:34 [ERROR] Please refer to /home/jenkins/jenkins_slave/workspace/Hazelcast-master-OracleJDK17/hazelcast/hazelcast/target/surefire-reports for the individual test results.
02:08:34 [ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
02:08:34 [ERROR] The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
02:08:34 [ERROR] Command was /bin/sh -c cd '/home/jenkins/jenkins_slave/workspace/Hazelcast-master-OracleJDK17/hazelcast/hazelcast' && '/usr/share/jdks/oracle-17/bin/java' '-Xms8g' '-Xmx8g' '--add-exports' 'java.base/jdk.internal.ref=ALL-UNNAMED' '--add-opens' 'jdk.management/com.sun.management.internal=ALL-UNNAMED' '--add-opens' 'java.base/sun.nio.ch=ALL-UNNAMED' '--add-opens' 'java.base/java.lang=ALL-UNNAMED' '--add-opens' 'java.management/sun.management=ALL-UNNAMED' '-Dhazelcast.phone.home.enabled=false' '-Dhazelcast.test.use.network=false' '-Dlog4j.skipJansi=true' '-jar' '/home/jenkins/jenkins_slave/workspace/Hazelcast-master-OracleJDK17/hazelcast/hazelcast/target/surefire/surefirebooter-20240410220643743_254.jar' '/home/jenkins/jenkins_slave/workspace/Hazelcast-master-OracleJDK17/hazelcast/hazelcast/target/surefire' '2024-04-10T22-02-45_814-jvmRun1' 'surefire-20240410220643743_252tmp' 'surefire_2-20240410220643743_253tmp'
02:08:34 [ERROR] Process Exit Code: 0
02:08:34 [ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
02:08:34 [ERROR] Command was /bin/sh -c cd '/home/jenkins/jenkins_slave/workspace/Hazelcast-master-OracleJDK17/hazelcast/hazelcast' && '/usr/share/jdks/oracle-17/bin/java' '-Xms8g' '-Xmx8g' '--add-exports' 'java.base/jdk.internal.ref=ALL-UNNAMED' '--add-opens' 'jdk.management/com.sun.management.internal=ALL-UNNAMED' '--add-opens' 'java.base/sun.nio.ch=ALL-UNNAMED' '--add-opens' 'java.base/java.lang=ALL-UNNAMED' '--add-opens' 'java.management/sun.management=ALL-UNNAMED' '-Dhazelcast.phone.home.enabled=false' '-Dhazelcast.test.use.network=false' '-Dlog4j.skipJansi=true' '-jar' '/home/jenkins/jenkins_slave/workspace/Hazelcast-master-OracleJDK17/hazelcast/hazelcast/target/surefire/surefirebooter-20240410220643743_254.jar' '/home/jenkins/jenkins_slave/workspace/Hazelcast-master-OracleJDK17/hazelcast/hazelcast/target/surefire' '2024-04-10T22-02-45_814-jvmRun1' 'surefire-20240410220643743_252tmp' 'surefire_2-20240410220643743_253tmp'
02:08:34 [ERROR] Process Exit Code: 0
02:08:34 [ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:643)
02:08:34 [ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:285)
02:08:34 [ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:250)
02:08:34 [ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1241)
02:08:34 [ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1090)
02:08:34 [ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:910)
02:08:34 [ERROR] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:126)
02:08:34 [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:328)
02:08:34 [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:316)
02:08:34 [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
02:08:34 [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:174)
02:08:34 [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.access$000(MojoExecutor.java:75)
02:08:34 [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor$1.run(MojoExecutor.java:162)
02:08:34 [ERROR] 	at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute(DefaultMojosExecutionStrategy.java:39)
02:08:34 [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:159)
02:08:34 [ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:105)
02:08:34 [ERROR] 	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:193)
02:08:34 [ERROR] 	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:180)
02:08:34 [ERROR] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
02:08:34 [ERROR] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
02:08:34 [ERROR] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
02:08:34 [ERROR] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
02:08:34 [ERROR] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
02:08:34 [ERROR] 	at java.base/java.lang.Thread.run(Thread.java:842)
02:08:34 [ERROR] -> [Help 1]
02:08:34 org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.2.5:test (default-test) on project hazelcast: 
02:08:34 
02:08:34 Please refer to /home/jenkins/jenkins_slave/workspace/Hazelcast-master-OracleJDK17/hazelcast/hazelcast/target/surefire-reports for the individual test results.
02:08:34 Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
02:08:34 The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
02:08:34 Command was /bin/sh -c cd '/home/jenkins/jenkins_slave/workspace/Hazelcast-master-OracleJDK17/hazelcast/hazelcast' && '/usr/share/jdks/oracle-17/bin/java' '-Xms8g' '-Xmx8g' '--add-exports' 'java.base/jdk.internal.ref=ALL-UNNAMED' '--add-opens' 'jdk.management/com.sun.management.internal=ALL-UNNAMED' '--add-opens' 'java.base/sun.nio.ch=ALL-UNNAMED' '--add-opens' 'java.base/java.lang=ALL-UNNAMED' '--add-opens' 'java.management/sun.management=ALL-UNNAMED' '-Dhazelcast.phone.home.enabled=false' '-Dhazelcast.test.use.network=false' '-Dlog4j.skipJansi=true' '-jar' '/home/jenkins/jenkins_slave/workspace/Hazelcast-master-OracleJDK17/hazelcast/hazelcast/target/surefire/surefirebooter-20240410220643743_254.jar' '/home/jenkins/jenkins_slave/workspace/Hazelcast-master-OracleJDK17/hazelcast/hazelcast/target/surefire' '2024-04-10T22-02-45_814-jvmRun1' 'surefire-20240410220643743_252tmp' 'surefire_2-20240410220643743_253tmp'
02:08:34 Process Exit Code: 0
02:08:34 org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
02:08:34 Command was /bin/sh -c cd '/home/jenkins/jenkins_slave/workspace/Hazelcast-master-OracleJDK17/hazelcast/hazelcast' && '/usr/share/jdks/oracle-17/bin/java' '-Xms8g' '-Xmx8g' '--add-exports' 'java.base/jdk.internal.ref=ALL-UNNAMED' '--add-opens' 'jdk.management/com.sun.management.internal=ALL-UNNAMED' '--add-opens' 'java.base/sun.nio.ch=ALL-UNNAMED' '--add-opens' 'java.base/java.lang=ALL-UNNAMED' '--add-opens' 'java.management/sun.management=ALL-UNNAMED' '-Dhazelcast.phone.home.enabled=false' '-Dhazelcast.test.use.network=false' '-Dlog4j.skipJansi=true' '-jar' '/home/jenkins/jenkins_slave/workspace/Hazelcast-master-OracleJDK17/hazelcast/hazelcast/target/surefire/surefirebooter-20240410220643743_254.jar' '/home/jenkins/jenkins_slave/workspace/Hazelcast-master-OracleJDK17/hazelcast/hazelcast/target/surefire' '2024-04-10T22-02-45_814-jvmRun1' 'surefire-20240410220643743_252tmp' 'surefire_2-20240410220643743_253tmp'
02:08:34 Process Exit Code: 0
02:08:34 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:643)
02:08:34 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:285)
02:08:34 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:250)
02:08:34 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1241)
02:08:34 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1090)
02:08:34 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:910)
02:08:34 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:126)
02:08:34 	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:328)
02:08:34 	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:316)
02:08:34 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
02:08:34 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:174)
02:08:34 	at org.apache.maven.lifecycle.internal.MojoExecutor.access$000(MojoExecutor.java:75)
02:08:34 	at org.apache.maven.lifecycle.internal.MojoExecutor$1.run(MojoExecutor.java:162)
02:08:34 	at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute(DefaultMojosExecutionStrategy.java:39)
02:08:34 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:159)
02:08:34 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:105)
02:08:34 	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:193)
02:08:34 	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:180)
02:08:34 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
02:08:34 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
02:08:34 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
02:08:34 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
02:08:34 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
02:08:34 	at java.base/java.lang.Thread.run(Thread.java:842)
02:08:34 
02:08:34     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:333)
02:08:34     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:316)
02:08:34     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:212)
02:08:34     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:174)
02:08:34     at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:75)
02:08:34     at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:162)
02:08:34     at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
02:08:34     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:159)
02:08:34     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
02:08:34     at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:193)
02:08:34     at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:180)
02:08:34     at java.util.concurrent.FutureTask.run (FutureTask.java:264)
02:08:34     at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:539)
02:08:34     at java.util.concurrent.FutureTask.run (FutureTask.java:264)
02:08:34     at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1136)
02:08:34     at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:635)
02:08:34     at java.lang.Thread.run (Thread.java:842)
02:08:34 Caused by: org.apache.maven.plugin.MojoExecutionException: 
02:08:34 
02:08:34 Please refer to /home/jenkins/jenkins_slave/workspace/Hazelcast-master-OracleJDK17/hazelcast/hazelcast/target/surefire-reports for the individual test results.
02:08:34 Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
02:08:34 The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
02:08:34 Command was /bin/sh -c cd '/home/jenkins/jenkins_slave/workspace/Hazelcast-master-OracleJDK17/hazelcast/hazelcast' && '/usr/share/jdks/oracle-17/bin/java' '-Xms8g' '-Xmx8g' '--add-exports' 'java.base/jdk.internal.ref=ALL-UNNAMED' '--add-opens' 'jdk.management/com.sun.management.internal=ALL-UNNAMED' '--add-opens' 'java.base/sun.nio.ch=ALL-UNNAMED' '--add-opens' 'java.base/java.lang=ALL-UNNAMED' '--add-opens' 'java.management/sun.management=ALL-UNNAMED' '-Dhazelcast.phone.home.enabled=false' '-Dhazelcast.test.use.network=false' '-Dlog4j.skipJansi=true' '-jar' '/home/jenkins/jenkins_slave/workspace/Hazelcast-master-OracleJDK17/hazelcast/hazelcast/target/surefire/surefirebooter-20240410220643743_254.jar' '/home/jenkins/jenkins_slave/workspace/Hazelcast-master-OracleJDK17/hazelcast/hazelcast/target/surefire' '2024-04-10T22-02-45_814-jvmRun1' 'surefire-20240410220643743_252tmp' 'surefire_2-20240410220643743_253tmp'
02:08:34 Process Exit Code: 0
02:08:34 org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
02:08:34 Command was /bin/sh -c cd '/home/jenkins/jenkins_slave/workspace/Hazelcast-master-OracleJDK17/hazelcast/hazelcast' && '/usr/share/jdks/oracle-17/bin/java' '-Xms8g' '-Xmx8g' '--add-exports' 'java.base/jdk.internal.ref=ALL-UNNAMED' '--add-opens' 'jdk.management/com.sun.management.internal=ALL-UNNAMED' '--add-opens' 'java.base/sun.nio.ch=ALL-UNNAMED' '--add-opens' 'java.base/java.lang=ALL-UNNAMED' '--add-opens' 'java.management/sun.management=ALL-UNNAMED' '-Dhazelcast.phone.home.enabled=false' '-Dhazelcast.test.use.network=false' '-Dlog4j.skipJansi=true' '-jar' '/home/jenkins/jenkins_slave/workspace/Hazelcast-master-OracleJDK17/hazelcast/hazelcast/target/surefire/surefirebooter-20240410220643743_254.jar' '/home/jenkins/jenkins_slave/workspace/Hazelcast-master-OracleJDK17/hazelcast/hazelcast/target/surefire' '2024-04-10T22-02-45_814-jvmRun1' 'surefire-20240410220643743_252tmp' 'surefire_2-20240410220643743_253tmp'
02:08:34 Process Exit Code: 0
02:08:34 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:643)
02:08:34 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:285)
02:08:34 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:250)
02:08:34 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1241)
02:08:34 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1090)
02:08:34 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:910)
02:08:34 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:126)
02:08:34 	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:328)
02:08:34 	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:316)
02:08:34 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
02:08:34 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:174)
02:08:34 	at org.apache.maven.lifecycle.internal.MojoExecutor.access$000(MojoExecutor.java:75)
02:08:34 	at org.apache.maven.lifecycle.internal.MojoExecutor$1.run(MojoExecutor.java:162)
02:08:34 	at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute(DefaultMojosExecutionStrategy.java:39)
02:08:34 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:159)
02:08:34 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:105)
02:08:34 	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:193)
02:08:34 	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:180)
02:08:34 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
02:08:34 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
02:08:34 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
02:08:34 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
02:08:34 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
02:08:34 	at java.base/java.lang.Thread.run(Thread.java:842)
02:08:34 
02:08:34     at org.apache.maven.plugin.surefire.SurefireHelper.reportExecution (SurefireHelper.java:154)
02:08:34     at org.apache.maven.plugin.surefire.SurefirePlugin.handleSummary (SurefirePlugin.java:542)
02:08:34     at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked (AbstractSurefireMojo.java:1102)
02:08:34     at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute (AbstractSurefireMojo.java:910)
02:08:34     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:126)
02:08:34     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:328)
02:08:34     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:316)
02:08:34     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:212)
02:08:34     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:174)
02:08:34     at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:75)
02:08:34     at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:162)
02:08:34     at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
02:08:34     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:159)
02:08:34     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
02:08:34     at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:193)
02:08:34     at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:180)
02:08:34     at java.util.concurrent.FutureTask.run (FutureTask.java:264)
02:08:34     at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:539)
02:08:34     at java.util.concurrent.FutureTask.run (FutureTask.java:264)
02:08:34     at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1136)
02:08:34     at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:635)
02:08:34     at java.lang.Thread.run (Thread.java:842)
02:08:34 Caused by: org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
02:08:34 Command was /bin/sh -c cd '/home/jenkins/jenkins_slave/workspace/Hazelcast-master-OracleJDK17/hazelcast/hazelcast' && '/usr/share/jdks/oracle-17/bin/java' '-Xms8g' '-Xmx8g' '--add-exports' 'java.base/jdk.internal.ref=ALL-UNNAMED' '--add-opens' 'jdk.management/com.sun.management.internal=ALL-UNNAMED' '--add-opens' 'java.base/sun.nio.ch=ALL-UNNAMED' '--add-opens' 'java.base/java.lang=ALL-UNNAMED' '--add-opens' 'java.management/sun.management=ALL-UNNAMED' '-Dhazelcast.phone.home.enabled=false' '-Dhazelcast.test.use.network=false' '-Dlog4j.skipJansi=true' '-jar' '/home/jenkins/jenkins_slave/workspace/Hazelcast-master-OracleJDK17/hazelcast/hazelcast/target/surefire/surefirebooter-20240410220643743_254.jar' '/home/jenkins/jenkins_slave/workspace/Hazelcast-master-OracleJDK17/hazelcast/hazelcast/target/surefire' '2024-04-10T22-02-45_814-jvmRun1' 'surefire-20240410220643743_252tmp' 'surefire_2-20240410220643743_253tmp'
02:08:34 Process Exit Code: 0
02:08:34     at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork (ForkStarter.java:643)
02:08:34     at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run (ForkStarter.java:285)
02:08:34     at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run (ForkStarter.java:250)
02:08:34     at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider (AbstractSurefireMojo.java:1241)
02:08:34     at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked (AbstractSurefireMojo.java:1090)
02:08:34     at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute (AbstractSurefireMojo.java:910)
02:08:34     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:126)
02:08:34     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:328)
02:08:34     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:316)
02:08:34     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:212)
02:08:34     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:174)
02:08:34     at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:75)
02:08:34     at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:162)
02:08:34     at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
02:08:34     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:159)
02:08:34     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
02:08:34     at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:193)
02:08:34     at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:180)
02:08:34     at java.util.concurrent.FutureTask.run (FutureTask.java:264)
02:08:34     at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:539)
02:08:34     at java.util.concurrent.FutureTask.run (FutureTask.java:264)
02:08:34     at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1136)
02:08:34     at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:635)
02:08:34     at java.lang.Thread.run (Thread.java:842)
```

</details>

**Comment by olukas** [comment]
Closing the test failure - it hasn't failed in the last 3 months.

**Comment by AleksPeychev** [comment]
Reopening as issue occurred again on: _master_ (commit 5228ecc9f8ca3504f40227be2cf04d097ec94aa8)
with oracle-17 (little-endian): https://jenkins.hazelcast.com/job/Hazelcast-master-little-endian/331/consoleFull

**Comment by k-jamroz** [comment]
@AleksPeychev I suspect it might be the same crash as https://github.com/hazelcast/hazelcast-mono/issues/4279#issuecomment-2862342136 but I cannot see crash dump in the artifacts.

**Comment by k-jamroz** [comment]
The above warning seems to be benign caused by the test structure: sync operation is still executing when the member is being shut down and the permits are reset in `PartitionReplicaManager.reset` during shutdown, apparently before the operation finishes.
