### ISSUE TITLE
com.hazelcast.jet.sql.impl.connector.kafka.SqlAvroTest failed on Redpanda [HZG-57] [HZG-464]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#26307]
_master_ (commit f180f27199962fadab65a8a332a276d1215eb9f0)

Failed on Redpanda 23.3.z:
- https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Redpanda-23.3.z/14/testReport/com.hazelcast.jet.sql.impl.connector.kafka/SqlAvroTest/
- https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Redpanda-23.3.z/14/testReport/com.hazelcast.jet.kafka.impl/WriteKafkaPTest/

Following tests failed:
- `com.hazelcast.jet.kafka.impl.WriteKafkaPTest.when_recordLingerEnabled_then_sentOnCompletion`
- `com.hazelcast.jet.kafka.impl.WriteKafkaPTest.test_resumeTransaction`
- `com.hazelcast.jet.sql.impl.connector.kafka.SqlAvroTest.test_topLevelFieldExtraction[useSchemaRegistry=[false]]`
- `com.hazelcast.jet.sql.impl.connector.kafka.SqlAvroTest.test_nonInclusiveUnion[useSchemaRegistry=[false]]`
- `com.hazelcast.jet.sql.impl.connector.kafka.SqlAvroTest.test_keyAndValueSchemaAvailableInInformationSchema[useSchemaRegistry=[false]]`
- `com.hazelcast.jet.kafka.impl.WriteKafkaPTest.testWriteToTopic`
- `com.hazelcast.jet.sql.impl.connector.kafka.SqlAvroTest.test_nestedField[useSchemaRegistry=[true]]`
- `com.hazelcast.jet.sql.impl.connector.kafka.SqlAvroTest.test_explicitKeyAndValueSerializers[useSchemaRegistry=[true]]`
- `com.hazelcast.jet.sql.impl.connector.kafka.SqlAvroTest.test_allTypes[useSchemaRegistry=[true]]`
- `com.hazelcast.jet.sql.impl.connector.kafka.SqlAvroTest.test_fieldsMapping[useSchemaRegistry=[true]]`
- `com.hazelcast.jet.sql.impl.connector.kafka.SqlAvroTest.test_mappingAndTypeHasMissingOptionalField[useSchemaRegistry=[false]]`
- `com.hazelcast.jet.sql.impl.connector.kafka.SqlAvroTest.test_nulls[useSchemaRegistry=[false]]`
- `com.hazelcast.jet.sql.impl.connector.kafka.SqlAvroTest.test_nulls[useSchemaRegistry=[true]]`
- `com.hazelcast.jet.sql.impl.connector.kafka.SqlAvroTest.test_topLevelFieldExtraction[useSchemaRegistry=[true]]`
- `com.hazelcast.jet.sql.impl.connector.kafka.SqlAvroTest.test_schemaIdForTwoQueriesIsEqual[useSchemaRegistry=[true]]`
- `com.hazelcast.jet.sql.impl.connector.kafka.SqlAvroTest.test_schemaEvolution[useSchemaRegistry=[false]]`
- `com.hazelcast.jet.sql.impl.connector.kafka.SqlAvroTest.test_schemaEvolution[useSchemaRegistry=[true]]`

<details><summary>Stacktrace:</summary>

```
java.lang.RuntimeException: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.InvalidPartitionsException: Number of partitions is below 1.
	at com.hazelcast.jet.kafka.impl.KafkaTestSupport.createTopic(KafkaTestSupport.java:134)
	at com.hazelcast.jet.sql.impl.connector.kafka.KafkaSqlTestSupport.createRandomTopic(KafkaSqlTestSupport.java:90)
	at com.hazelcast.jet.sql.impl.connector.kafka.SqlAvroTest.createRandomTopic(SqlAvroTest.java:877)
	at com.hazelcast.jet.sql.impl.connector.kafka.SqlAvroTest.test_nestedField(SqlAvroTest.java:167)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:842)
Caused by: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.InvalidPartitionsException: Number of partitions is below 1.
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
	at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:165)
	at com.hazelcast.jet.kafka.impl.KafkaTestSupport.createTopic(KafkaTestSupport.java:132)
	... 8 more
Caused by: org.apache.kafka.common.errors.InvalidPartitionsException: Number of partitions is below 1.

```
</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: test_unionWithString[useSchemaRegistry=[true]] in 0.002 seconds.
Started Running Test: test_nestedField[useSchemaRegistry=[true]]
21:32:49,177  INFO || - [DockerizedRedPandaTestSupport] docker-java-stream-785697843 - STDERR: INFO  2024-04-05 21:32:49,176 [shard 0:main] cluster - topics_frontend.cc:137 - Create topics {{configuration: { topic: {kafka/t_50082ddf_264a_4daa_b5da_b78363e62527}, partition_count: 4, replication_factor: 1, properties: {compression: {nullopt}, cleanup_policy_bitflags: {delete}, compaction_strategy: {nullopt}, retention_bytes: {}, retention_duration_ms: {}, segment_size: {nullopt}, timestamp_type: {nullopt}, recovery_enabled: {nullopt}, shadow_indexing: {disabled}, read_replica: {nullopt}, read_replica_bucket: {nullopt} remote_topic_properties: {nullopt}, batch_max_bytes: {nullopt}, retention_local_target_bytes: {}, retention_local_target_ms: {}, remote_delete: true, segment_ms: {}, record_key_schema_id_validation: {nullopt}, record_key_schema_id_validation_compat: {nullopt}, record_key_subject_name_strategy:  {nullopt}, record_key_subject_name_strategy_compat: {nullopt}, record_value_schema_id_validation: {nullopt},  record_value_schema_id_validation_compat: {nullopt}, record_value_subject_name_strategy: {nullopt}, record_value_subject_name_strategy_compat: {nullopt}, initial_retention_local_target_bytes: {}, initial_retention_local_target_ms: {}}}, custom_assignments: {}}}
21:32:49,177  INFO || - [DockerizedRedPandaTestSupport] docker-java-stream-785697843 - STDERR: WARN  2024-04-05 21:32:49,176 [shard 0:main] cluster - partition_allocator.cc:234 - Refusing to create 4 new partitions as total partition count 258 would exceed memory limit 256
21:32:49,436  INFO |test_nestedField[useSchemaRegistry=[true]]| - [SqlTestSupport] Time-limited test - Removing 0 cached plans in SqlTestSupport.@After
21:32:49,436  INFO |test_nestedField[useSchemaRegistry=[true]]| - [SimpleTestInClusterSupport] Time-limited test - Ditching 0 jobs in SimpleTestInClusterSupport.@After: []
21:32:49,436  INFO |test_nestedField[useSchemaRegistry=[true]]| - [SimpleTestInClusterSupport] Time-limited test - Destroying 3 distributed objects in SimpleTestInClusterSupport.@After: [hz:impl:mapService/__jet.results, hz:impl:mapService/__jet.records, hz:impl:mapService/__sql.catalog]
21:32:49,437  INFO |test_nestedField[useSchemaRegistry=[true]]| - [HazelcastTestSupport] Time-limited test - Shutting down node factory as @After action
BuildInfo right after test_nestedField[useSchemaRegistry=[true]](com.hazelcast.jet.sql.impl.connector.kafka.SqlAvroTest): BuildInfo{version='5.5.0-SNAPSHOT', build='20240405', buildNumber=20240405, revision=, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'test_nestedField[useSchemaRegistry=[true]](com.hazelcast.jet.sql.impl.connector.kafka.SqlAvroTest):'
21:32:45, accumulated pauses: 3683 ms, max pause: 418 ms, pauses over 1000 ms: 0


No metrics recorded during the test

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-Redpanda-23.3.z/14/

**Comment by olukas** [comment]
Failed again on _master_ with oracle-17:
- https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Redpanda-23.3.z/17/testReport/com.hazelcast.jet.kafka.impl/WriteKafkaPTest/
- https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Redpanda-23.3.z/17/testReport/com.hazelcast.jet.sql.impl.connector.kafka/SqlAvroTest/

**Comment by AleksPeychev** [comment]
Failed again on _master_ with oracle-17: 
 - https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Redpanda-24.1.z/1/testReport/junit/com.hazelcast.jet.kafka.impl/WriteKafkaPTest/
 - https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Redpanda-24.1.z/1/testReport/junit/com.hazelcast.jet.sql.impl.connector.kafka/SqlAvroTest/

**Comment by sumnerib** [comment]
Failed again on _master_ with oracle-17: https://jenkins.hazelcast.com/job/Hazelcast-master-Redpanda-24.1.z/2/testReport/

**Comment by olukas** [comment]
Failed again on _master_ with oracle-17: https://jenkins.hazelcast.com/job/Hazelcast-master-Redpanda-23.3.z/21/testReport/

**Comment by AleksPeychev** [comment]
Failed again on _master_ with oracle-17: 
 - https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Redpanda-23.3.z/23/testReport/junit/com.hazelcast.jet.sql.impl.connector.kafka/SqlAvroTest/
 - Failed again on _master_ with oracle-17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Redpanda-23.3.z/23/testReport/junit/com.hazelcast.jet.kafka.impl/WriteKafkaPTest/

**Comment by sumnerib** [comment]
Failed again on _master_ with oracle-17: https://jenkins.hazelcast.com/job/Hazelcast-master-Redpanda-23.3.z/24/testReport/

**Comment by sumnerib** [comment]
Failed again on _master_ with oracle-17: https://jenkins.hazelcast.com/job/Hazelcast-master-Redpanda-23.3.z/29/testReport/junit/com.hazelcast.jet.sql.impl.connector.kafka/SqlAvroTest/

**Comment by AleksPeychev** [comment]
Reopening as issue occurred again on: _master_ (commit a1a12b90436947940512f088a493bf37f22f59a7)
with oracle-17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Kafka-confluent-platform-7.4.z/84/testReport/junit/com.hazelcast.jet.sql.impl.connector.kafka/SqlAvroTest/test_schemaEvolution_useSchemaRegistry__false__/
<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: 

Expecting throwable message:
  "com.hazelcast.sql.HazelcastSqlException: The Jet SQL job failed: Execution on a member failed: com.hazelcast.jet.JetException: Exception in ProcessorTasklet{0cb9-0637-248d-0001/Kafka[public.t_9f88549b_dc37_4e9e_bb4b_e395e694be40]#0}: org.apache.kafka.common.errors.RecordDeserializationException: Error deserializing VALUE for partition t_9f88549b_dc37_4e9e_bb4b_e395e694be40-0 at offset 0. If needed, please seek past the record to continue consumption."
to contain:
  "Error deserializing key/value"
but did not.

Throwable that failed the check:

java.util.concurrent.ExecutionException: com.hazelcast.sql.HazelcastSqlException: The Jet SQL job failed: Execution on a member failed: com.hazelcast.jet.JetException: Exception in ProcessorTasklet{0cb9-0637-248d-0001/Kafka[public.t_9f88549b_dc37_4e9e_bb4b_e395e694be40]#0}: org.apache.kafka.common.errors.RecordDeserializationException: Error deserializing VALUE for partition t_9f88549b_dc37_4e9e_bb4b_e395e694be40-0 at offset 0. If needed, please seek past the record to continue consumption.
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096)
	at com.hazelcast.jet.sql.SqlTestSupport.assertRowsEventuallyInAnyOrder(SqlTestSupport.java:266)
	at com.hazelcast.jet.sql.SqlTestSupport.assertRowsEventuallyInAnyOrder(SqlTestSupport.java:204)
	at com.hazelcast.jet.sql.SqlTestSupport.assertRowsEventuallyInAnyOrder(SqlTestSupport.java:181)
	at com.hazelcast.jet.sql.SqlTestSupport.assertRowsEventuallyInAnyOrder(SqlTestSupport.java:165)
	at com.hazelcast.jet.sql.impl.connector.kafka.SqlAvroTest.lambda$test_schemaEvolution$14(SqlAvroTest.java:691)
	at org.assertj.core.api.ThrowableAssert.catchThrowable(ThrowableAssert.java:63)
	at org.assertj.core.api.AssertionsForClassTypes.catchThrowable(AssertionsForClassTypes.java:904)
	at org.assertj.core.api.Assertions.catchThrowable(Assertions.java:1470)
	at org.assertj.core.api.Assertions.assertThatThrownBy(Assertions.java:1313)
	at com.hazelcast.jet.sql.impl.connector.kafka.SqlAvroTest.test_schemaEvolution(SqlAvroTest.java:701)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:842)
Caused by: com.hazelcast.sql.HazelcastSqlException: The Jet SQL job failed: Execution on a member failed: com.hazelcast.jet.JetException: Exception in ProcessorTasklet{0cb9-0637-248d-0001/Kafka[public.t_9f88549b_dc37_4e9e_bb4b_e395e694be40]#0}: org.apache.kafka.common.errors.RecordDeserializationException: Error deserializing VALUE for partition t_9f88549b_dc37_4e9e_bb4b_e395e694be40-0 at offset 0. If needed, please seek past the record to continue consumption.
	at com.hazelcast.sql.impl.CoreQueryUtils.toPublicException(CoreQueryUtils.java:49)
	at com.hazelcast.jet.sql.impl.SqlResultImpl$RowToSqlRowIterator.hasNext(SqlResultImpl.java:130)
	at com.hazelcast.jet.sql.SqlTestSupport.lambda$assertRowsEventuallyInAnyOrder$1(SqlTestSupport.java:249)
	... 1 more
Caused by: com.hazelcast.sql.impl.QueryException: The Jet SQL job failed: Execution on a member failed: com.hazelcast.jet.JetException: Exception in ProcessorTasklet{0cb9-0637-248d-0001/Kafka[public.t_9f88549b_dc37_4e9e_bb4b_e395e694be40]#0}: org.apache.kafka.common.errors.RecordDeserializationException: Error deserializing VALUE for partition t_9f88549b_dc37_4e9e_bb4b_e395e694be40-0 at offset 0. If needed, please seek past the record to continue consumption.
	at com.hazelcast.sql.impl.QueryException.error(QueryException.java:69)
	at com.hazelcast.jet.sql.impl.PlanExecutor.lambda$execute$5(PlanExecutor.java:557)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
	at com.hazelcast.jet.impl.util.NonCompletableFuture.internalCompleteExceptionally(NonCompletableFuture.java:72)
	at com.hazelcast.jet.impl.AbstractJobProxy$CallbackBase.accept(AbstractJobProxy.java:498)
	at com.hazelcast.jet.impl.AbstractJobProxy$CallbackBase.accept(AbstractJobProxy.java:481)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$WhenCompleteNode.lambda$execute$0(AbstractInvocationFuture.java:1562)
	at com.hazelcast.test.TestLoggingUtils$CustomTestNameAwareForkJoinPool$TestNameAwareRunnable.run(TestLoggingUtils.java:104)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: com.hazelcast.jet.JetException: Execution on a member failed: com.hazelcast.jet.JetException: Exception in ProcessorTasklet{0cb9-0637-248d-0001/Kafka[public.t_9f88549b_dc37_4e9e_bb4b_e395e694be40]#0}: org.apache.kafka.common.errors.RecordDeserializationException: Error deserializing VALUE for partition t_9f88549b_dc37_4e9e_bb4b_e395e694be40-0 at offset 0. If needed, please seek past the record to continue consumption.
	at com.hazelcast.jet.impl.LightMasterContext.findError(LightMasterContext.java:360)
	at com.hazelcast.jet.impl.LightMasterContext.lambda$createContext$3(LightMasterContext.java:184)
	at com.hazelcast.jet.impl.LightMasterContext.lambda$invokeOnParticipant$9(LightMasterContext.java:328)
	... 8 more
Caused by: com.hazelcast.jet.JetException: Exception in ProcessorTasklet{0cb9-0637-248d-0001/Kafka[public.t_9f88549b_dc37_4e9e_bb4b_e395e694be40]#0}: org.apache.kafka.common.errors.RecordDeserializationException: Error deserializing VALUE for partition t_9f88549b_dc37_4e9e_bb4b_e395e694be40-0 at offset 0. If needed, please seek past the record to continue consumption.
	at com.hazelcast.jet.impl.execution.TaskletExecutionService.handleTaskletExecutionError(TaskletExecutionService.java:289)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$BlockingWorker.run(TaskletExecutionService.java:328)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:842)
Caused by: com.hazelcast.jet.impl.execution.TaskletExecutionException: Exception in ProcessorTasklet{0cb9-0637-248d-0001/Kafka[public.t_9f88549b_dc37_4e9e_bb4b_e395e694be40]#0}: org.apache.kafka.common.errors.RecordDeserializationException: Error deserializing VALUE for partition t_9f88549b_dc37_4e9e_bb4b_e395e694be40-0 at offset 0. If needed, please seek past the record to continue consumption.
	at com.hazelcast.jet.impl.execution.TaskletExecutionService.handleTaskletExecutionError(TaskletExecutionService.java:288)
	... 6 more
Caused by: org.apache.kafka.common.errors.RecordDeserializationException: Error deserializing VALUE for partition t_9f88549b_dc37_4e9e_bb4b_e395e694be40-0 at offset 0. If needed, please seek past the record to continue consumption.
	at org.apache.kafka.clients.consumer.internals.CompletedFetch.newRecordDeserializationException(CompletedFetch.java:346)
	at org.apache.kafka.clients.consumer.internals.CompletedFetch.parseRecord(CompletedFetch.java:330)
	at org.apache.kafka.clients.consumer.internals.CompletedFetch.fetchRecords(CompletedFetch.java:284)
	at org.apache.kafka.clients.consumer.internals.FetchCollector.fetchRecords(FetchCollector.java:168)
	at org.apache.kafka.clients.consumer.internals.FetchCollector.collectFetch(FetchCollector.java:134)
	at org.apache.kafka.clients.consumer.internals.Fetcher.collectFetch(Fetcher.java:145)
	at org.apache.kafka.clients.consumer.internals.LegacyKafkaConsumer.pollForFetches(LegacyKafkaConsumer.java:694)
	at org.apache.kafka.clients.consumer.internals.LegacyKafkaConsumer.poll(LegacyKafkaConsumer.java:618)
	at org.apache.kafka.clients.consumer.internals.LegacyKafkaConsumer.poll(LegacyKafkaConsumer.java:591)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:874)
	at com.hazelcast.jet.kafka.impl.StreamKafkaP.complete(StreamKafkaP.java:243)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.complete(ProcessorTasklet.java:539)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:419)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:291)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$BlockingWorker.run(TaskletExecutionService.java:318)
	... 5 more
Caused by: org.apache.kafka.common.errors.SerializationException: Error deserializing Avro message
	at com.hazelcast.jet.kafka.HazelcastKafkaAvroDeserializer.deserialize(HazelcastKafkaAvroDeserializer.java:54)
	at com.hazelcast.jet.kafka.HazelcastKafkaAvroDeserializer.deserialize(HazelcastKafkaAvroDeserializer.java:38)
	at org.apache.kafka.common.serialization.Deserializer.deserialize(Deserializer.java:62)
	at org.apache.kafka.common.serialization.Deserializer.deserialize(Deserializer.java:73)
	at org.apache.kafka.clients.consumer.internals.CompletedFetch.parseRecord(CompletedFetch.java:327)
	... 18 more
Caused by: com.hazelcast.jet.JetException: java.io.EOFException
	at com.hazelcast.jet.impl.util.ExceptionUtil.peeledAndUnchecked(ExceptionUtil.java:138)
	at com.hazelcast.jet.impl.util.ExceptionUtil.rethrow(ExceptionUtil.java:144)
	at com.hazelcast.jet.avro.impl.AvroSerializerHooks.deserialize(AvroSerializerHooks.java:76)
	at com.hazelcast.jet.kafka.HazelcastKafkaAvroDeserializer.deserialize(HazelcastKafkaAvroDeserializer.java:52)
	... 22 more
Caused by: java.io.EOFException
	at org.apache.avro.io.BinaryDecoder.ensureBounds(BinaryDecoder.java:514)
	at org.apache.avro.io.BinaryDecoder.readInt(BinaryDecoder.java:155)
	at org.apache.avro.io.BinaryDecoder.readIndex(BinaryDecoder.java:465)
	at org.apache.avro.io.ResolvingDecoder.readIndex(ResolvingDecoder.java:282)
	at org.apache.avro.generic.GenericDatumReader.readWithoutConversion(GenericDatumReader.java:188)
	at org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:161)
	at org.apache.avro.generic.GenericDatumReader.readField(GenericDatumReader.java:260)
	at org.apache.avro.generic.GenericDatumReader.readRecord(GenericDatumReader.java:248)
	at org.apache.avro.generic.GenericDatumReader.readWithoutConversion(GenericDatumReader.java:180)
	at org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:161)
	at org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:154)
	at com.hazelcast.jet.avro.impl.AvroSerializerHooks.deserialize(AvroSerializerHooks.java:74)
	... 23 more

	at com.hazelcast.jet.sql.impl.connector.kafka.SqlAvroTest.test_schemaEvolution(SqlAvroTest.java:702)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:842)

```
</details>



Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-Kafka-confluent-platform-7.4.z/84/

**Comment by AleksPeychev** [comment]
Failed again on _master_ with oracle-17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Kafka-confluent-platform-7.1.z/139/testReport/junit/com.hazelcast.jet.sql.impl.connector.kafka/SqlAvroTest/test_schemaEvolution_useSchemaRegistry__false__/

**Comment by AleksPeychev** [comment]
Failed again on _master_ with oracle-17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Kafka-confluent-platform-7.5.z/70/testReport/com.hazelcast.jet.sql.impl.connector.kafka/SqlAvroTest/test_schemaEvolution_useSchemaRegistry__false__/

**Comment by AleksPeychev** [comment]
Failed again on _master_ with oracle-17: https://jenkins.hazelcast.com/job/Hazelcast-master-Kafka-confluent-platform-7.1.z/164/testReport/com.hazelcast.jet.sql.impl.connector.kafka/SqlAvroTest/test_schemaEvolution_useSchemaRegistry__false__/

**Comment by AleksPeychev** [comment]
Failed again on all **Kafka/Confluent Platform Versions** _master_ with oracle-17: 
 - https://jenkins.hazelcast.com/view/Kafka/job/Hazelcast-master-Kafka-confluent-platform-7.3.z/136/testReport/com.hazelcast.jet.sql.impl.connector.kafka/SqlAvroTest/test_schemaEvolution_useSchemaRegistry__false__/
 - https://jenkins.hazelcast.com/view/Kafka/job/Hazelcast-master-Kafka-confluent-platform-7.4.z/109/testReport/com.hazelcast.jet.sql.impl.connector.kafka/SqlAvroTest/test_schemaEvolution_useSchemaRegistry__false__/
 - https://jenkins.hazelcast.com/view/Kafka/job/Hazelcast-master-Kafka-confluent-platform-7.5.z/94/testReport/com.hazelcast.jet.sql.impl.connector.kafka/SqlAvroTest/test_schemaEvolution_useSchemaRegistry__false__/
 - https://jenkins.hazelcast.com/view/Kafka/job/Hazelcast-master-Kafka-confluent-platform-7.6.z/66/testReport/com.hazelcast.jet.sql.impl.connector.kafka/SqlAvroTest/test_schemaEvolution_useSchemaRegistry__false__/
 - https://jenkins.hazelcast.com/view/Kafka/job/Hazelcast-master-Kafka-confluent-platform-7.7.z/39/testReport/com.hazelcast.jet.sql.impl.connector.kafka/SqlAvroTest/test_schemaEvolution_useSchemaRegistry__false__/
 - https://jenkins.hazelcast.com/view/Kafka/job/Hazelcast-master-Kafka-confluent-platform-7.8.z/164/testReport/com.hazelcast.jet.sql.impl.connector.kafka/SqlAvroTest/test_schemaEvolution_useSchemaRegistry__false__/

**Comment by AleksPeychev** [comment]
Failed again on all **Redpanda Versions** _master_ with oracle-17: 
-  https://jenkins.hazelcast.com/view/Redpanda/job/Hazelcast-master-Redpanda-23.3.z/74/testReport/com.hazelcast.jet.sql.impl.connector.kafka/SqlAvroTest/test_schemaEvolution_useSchemaRegistry__false__/
- https://jenkins.hazelcast.com/view/Redpanda/job/Hazelcast-master-Redpanda-24.1.z/57/testReport/com.hazelcast.jet.sql.impl.connector.kafka/SqlAvroTest/test_schemaEvolution_useSchemaRegistry__false__/
- https://jenkins.hazelcast.com/view/Redpanda/job/Hazelcast-master-Redpanda-24.2.z/39/testReport/com.hazelcast.jet.sql.impl.connector.kafka/SqlAvroTest/test_schemaEvolution_useSchemaRegistry__false__/
- https://jenkins.hazelcast.com/view/Redpanda/job/Hazelcast-master-Redpanda-24.3.z/52/testReport/com.hazelcast.jet.kafka.impl/StreamKafkaPTest/when_partitionAddedWhilePartitionsInitialOffsetsProvided_then_consumedFromBeginning/
