### ISSUE TITLE
hazelcast fails to start with java.lang.ClassCastException: class java.lang.Boolean cannot be cast to class java.lang.String 

### ISSUE THREAD

**Issue by kgignatyev** [hazelcast/hazelcast#26310]
**Describe the bug**
Hazelcast instance cannot be created, throws exception

Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.hazelcast.core.HazelcastInstance]: Factory method 'hazelcastInstance' threw exception with message: class java.lang.Boolean cannot be cast to class java.lang.String (java.lang.Boolean and java.lang.String are in module java.base of loader 'bootstrap')
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:177) ~[spring-beans-6.1.5.jar:6.1.5]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:644) ~[spring-beans-6.1.5.jar:6.1.5]
	... 79 common frames omitted
Caused by: java.lang.ClassCastException: class java.lang.Boolean cannot be cast to class java.lang.String (java.lang.Boolean and java.lang.String are in module java.base of loader 'bootstrap')
	at com.hazelcast.internal.config.override.SystemPropertiesConfigParser.lambda$parse$0(SystemPropertiesConfigParser.java:49) ~[hazelcast-5.3.7.jar:5.3.7]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[na:na]
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133) ~[na:na]

This is cause by polyglot.engine.WarnInterpreterOnly property value, which is boolean but
hazelcast-5.3.6-sources.jar!/com/hazelcast/internal/config/override/SystemPropertiesConfigParser.java:49 
code expects all values to be String-s

<img width="1786" alt="image" src="https://github.com/hazelcast/hazelcast/assets/868783/69ee4478-c169-45f0-8ffb-19c0fad3c602">

**Expected behavior**

Hazelcast instance starts even when system properties have non string properties

**To Reproduce**

<img width="1928" alt="image" src="https://github.com/hazelcast/hazelcast/assets/868783/8c2574d8-1d99-4a3c-858e-92238856bbbd">

**Additional context**

java -version
openjdk version "21.0.2" 2024-01-16 LTS
OpenJDK Runtime Environment Zulu21.32+17-CA (build 21.0.2+13-LTS)
OpenJDK 64-Bit Server VM Zulu21.32+17-CA (build 21.0.2+13-LTS, mixed mode, sharing)

uname -a
Darwin Konstantins-M1-MBP.local 23.4.0 Darwin Kernel Version 23.4.0: Fri Mar 15 00:10:42 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6000 arm64

**Comment by kgignatyev** [comment]
The culprit is Flyway library, however it does not do anything illegal. I think that Hazelcast code should be more resilient
<img width="1957" alt="image" src="https://github.com/hazelcast/hazelcast/assets/868783/8775eb39-0f41-461a-b3f9-e62f0f0f8a5d">

**Comment by JackPGreen** [comment]
Thanks for the report, @kgignatyev
