### ISSUE TITLE
classloading.JavaXCacheDependencyClientTest.createHazelcastInstance_getCache [HZ-4698]

### ISSUE THREAD

**Issue by Patras3** [hazelcast/hazelcast#26318]
_master_ (commit 9e30d555e2d7c1250a3b42cd22090aa46daf6448)

Failed on oracle-17 (little-endian): https://jenkins.hazelcast.com/job/Hazelcast-master-nightly-little-endian/75/testReport/classloading/JavaXCacheDependencyClientTest/createHazelcastInstance_getCache/
<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: Application created a ThreadLocal on thread [hz.hz.client_3.IO.thread-in-0] of type [com.hazelcast.internal.networking.nio.NioThread] with key of type [com.hazelcast.client.impl.spi.impl.ClientResponseHandlerSupplier$1] (value [com.hazelcast.client.impl.spi.impl.ClientResponseHandlerSupplier$1@5d8590dc]) and a value of type [com.hazelcast.internal.util.MutableInteger] (value [com.hazelcast.internal.util.MutableInteger@502b5d29) but failed to remove it when the application was stopped. - consider that this failure may be due to NioNetworking#shutdown not waiting for NioThread instances to join.
	at classloading.ThreadLocalLeakTestUtils.checkThreadLocalMapForLeaks(ThreadLocalLeakTestUtils.java:176)
	at classloading.ThreadLocalLeakTestUtils.checkThreadLocalsForLeaks(ThreadLocalLeakTestUtils.java:71)
	at classloading.AbstractJavaXCacheDependencyTest.createHazelcastInstance_getCache(AbstractJavaXCacheDependencyTest.java:74)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:842)

```
</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: createHazelcastInstance in 0.027 seconds.
Started Running Test: createHazelcastInstance_getCache
22:12:48,209  INFO |createHazelcastInstance_getCache| - [ClientInvocationService] createHazelcastInstance_getCache - hz.client_3 [dev] [5.5.0-SNAPSHOT] Running with 2 response threads, dynamic=true
22:12:48,211  INFO |createHazelcastInstance_getCache| - [LifecycleService] createHazelcastInstance_getCache - hz.client_3 [dev] [5.5.0-SNAPSHOT] HazelcastClient 5.5.0-SNAPSHOT (20240419) is STARTING
22:12:48,211  INFO |createHazelcastInstance_getCache| - [LifecycleService] createHazelcastInstance_getCache - hz.client_3 [dev] [5.5.0-SNAPSHOT] HazelcastClient 5.5.0-SNAPSHOT (20240419) is STARTED
22:12:48,215  INFO |createHazelcastInstance_getCache| - [ClientConnectionManager] createHazelcastInstance_getCache - hz.client_3 [dev] [5.5.0-SNAPSHOT] Trying to connect to cluster: dev
22:12:48,215  INFO |createHazelcastInstance_getCache| - [ClientConnectionManager] createHazelcastInstance_getCache - hz.client_3 [dev] [5.5.0-SNAPSHOT] Trying to connect to [127.0.0.1]:5701
22:12:48,217 DEBUG || - [AuthenticationMessageTask] hz.festive_chaum.priority-generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [5.5.0-SNAPSHOT] Processing authentication with clientUuid 81c5603c-589a-4483-b7e9-44efe995f89e and clientName hz.client_3
22:12:48,217  INFO || - [AuthenticationMessageTask] hz.festive_chaum.priority-generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [5.5.0-SNAPSHOT] Received auth from Connection[id=3, /127.0.0.1:5701->/127.0.0.1:42513, qualifier=null, endpoint=[127.0.0.1]:42513, remoteUuid=81c5603c-589a-4483-b7e9-44efe995f89e, alive=true, connectionType=JVM, planeIndex=-1], successfully authenticated, clientUuid: 81c5603c-589a-4483-b7e9-44efe995f89e, client name: hz.client_3, client version: 5.5.0-SNAPSHOT
22:12:48,218  INFO |createHazelcastInstance_getCache| - [ClientClusterService] createHazelcastInstance_getCache - hz.client_3 [dev] [5.5.0-SNAPSHOT] 

Members [1] {
	Member [127.0.0.1]:5701 - 96da4f39-e969-421c-ae91-32bc66335428
}

22:12:48,218  INFO |createHazelcastInstance_getCache| - [LifecycleService] createHazelcastInstance_getCache - hz.client_3 [dev] [5.5.0-SNAPSHOT] HazelcastClient 5.5.0-SNAPSHOT (20240419) is CLIENT_CONNECTED
22:12:48,219  INFO |createHazelcastInstance_getCache| - [ClientConnectionManager] createHazelcastInstance_getCache - hz.client_3 [dev] [5.5.0-SNAPSHOT] Authenticated with server [127.0.0.1]:5701:96da4f39-e969-421c-ae91-32bc66335428, server version: 5.5.0-SNAPSHOT, local address: /127.0.0.1:42513
22:12:48,219  INFO |createHazelcastInstance_getCache| - [Diagnostics] createHazelcastInstance_getCache - hz.client_3 [dev] [5.5.0-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
22:12:48,219 TRACE |createHazelcastInstance_getCache| - [ClientListenerService] hz.client_3.internal-1 - hz.client_3 [dev] [5.5.0-SNAPSHOT] Register attempt of ClusterViewListenerHandler to ClientConnection{alive=true, connectionId=1, channel=NioChannel{/127.0.0.1:42513->/127.0.0.1:5701}, remoteAddress=[127.0.0.1]:5701, lastReadTime=2024-04-19 22:12:48.217, lastWriteTime=2024-04-19 22:12:48.216, closedTime=never}
22:12:48,221 TRACE |createHazelcastInstance_getCache| - [ClientListenerService] hz.client_3.eventRegistration- - hz.client_3 [dev] [5.5.0-SNAPSHOT] Register attempt of ClientListenerRegistration{codec=com.hazelcast.client.impl.spi.impl.ClientInvocationServiceImpl$1@427ed905, handler=com.hazelcast.client.impl.spi.impl.ClientInvocationServiceImpl$BackupEventHandler@4f96f626} to ClientConnection{alive=true, connectionId=1, channel=NioChannel{/127.0.0.1:42513->/127.0.0.1:5701}, remoteAddress=[127.0.0.1]:5701, lastReadTime=2024-04-19 22:12:48.217, lastWriteTime=2024-04-19 22:12:48.220, closedTime=never}
22:12:48,222 TRACE || - [ClientListenerService] ForkJoinPool.commonPool-worker-1 - hz.client_3 [dev] [5.5.0-SNAPSHOT] Registered ClusterViewListenerHandler to ClientConnection{alive=true, connectionId=1, channel=NioChannel{/127.0.0.1:42513->/127.0.0.1:5701}, remoteAddress=[127.0.0.1]:5701, lastReadTime=2024-04-19 22:12:48.221, lastWriteTime=2024-04-19 22:12:48.221, closedTime=never}
22:12:48,222 TRACE |createHazelcastInstance_getCache| - [ClientListenerService] hz.client_3.eventRegistration- - hz.client_3 [dev] [5.5.0-SNAPSHOT] Registered ClientListenerRegistration{codec=com.hazelcast.client.impl.spi.impl.ClientInvocationServiceImpl$1@427ed905, handler=com.hazelcast.client.impl.spi.impl.ClientInvocationServiceImpl$BackupEventHandler@4f96f626} to ClientConnection{alive=true, connectionId=1, channel=NioChannel{/127.0.0.1:42513->/127.0.0.1:5701}, remoteAddress=[127.0.0.1]:5701, lastReadTime=2024-04-19 22:12:48.222, lastWriteTime=2024-04-19 22:12:48.221, closedTime=never}
22:12:48,223  INFO |createHazelcastInstance_getCache| - [ClientStatisticsService] createHazelcastInstance_getCache - Client statistics is enabled with period 5 seconds.
22:12:48,224  INFO |createHazelcastInstance_getCache| - [LifecycleService] createHazelcastInstance_getCache - hz.client_3 [dev] [5.5.0-SNAPSHOT] HazelcastClient 5.5.0-SNAPSHOT (20240419) is SHUTTING_DOWN
22:12:48,225  INFO || - [TcpServerConnection] hz.festive_chaum.IO.thread-in-2 - [127.0.0.1]:5701 [dev] [5.5.0-SNAPSHOT] Connection[id=3, /127.0.0.1:5701->/127.0.0.1:42513, qualifier=null, endpoint=[127.0.0.1]:42513, remoteUuid=81c5603c-589a-4483-b7e9-44efe995f89e, alive=false, connectionType=JVM, planeIndex=-1] closed. Reason: Connection closed by the other side
22:12:48,225  INFO |createHazelcastInstance_getCache| - [ClientConnectionManager] createHazelcastInstance_getCache - hz.client_3 [dev] [5.5.0-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5701:96da4f39-e969-421c-ae91-32bc66335428, connection: ClientConnection{alive=false, connectionId=1, channel=NioChannel{/127.0.0.1:42513->/127.0.0.1:5701}, remoteAddress=[127.0.0.1]:5701, lastReadTime=2024-04-19 22:12:48.222, lastWriteTime=2024-04-19 22:12:48.221, closedTime=2024-04-19 22:12:48.224}
22:12:48,225  INFO |createHazelcastInstance_getCache| - [LifecycleService] createHazelcastInstance_getCache - hz.client_3 [dev] [5.5.0-SNAPSHOT] HazelcastClient 5.5.0-SNAPSHOT (20240419) is CLIENT_DISCONNECTED
22:12:48,225  INFO || - [ClientEndpointManager] hz.festive_chaum.event-4 - [127.0.0.1]:5701 [dev] [5.5.0-SNAPSHOT] Destroying ClientEndpoint{connection=Connection[id=3, /127.0.0.1:5701->/127.0.0.1:42513, qualifier=null, endpoint=[127.0.0.1]:42513, remoteUuid=81c5603c-589a-4483-b7e9-44efe995f89e, alive=false, connectionType=JVM, planeIndex=-1], clientUuid=81c5603c-589a-4483-b7e9-44efe995f89e, clientName=hz.client_3, authenticated=true, clientVersion=5.5.0-SNAPSHOT, creationTime=1713564768216, latest clientAttributes=null, labels=[]}
22:12:48,234  INFO |createHazelcastInstance_getCache| - [LifecycleService] createHazelcastInstance_getCache - hz.client_3 [dev] [5.5.0-SNAPSHOT] HazelcastClient 5.5.0-SNAPSHOT (20240419) is SHUTDOWN

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-nightly-little-endian/75/

**Comment by nishaatr** [comment]
Changed Milestone to 6.0.0 to ensure 5.5.0 does not report any Open [issues ](https://github.com/issues?page=1&q=is%3Aopen+milestone%3A5.5.0+repo%3Ahazelcast%2Fhazelcast+repo%3Ahazelcast%2Fhazelcast-enterprise+repo%3Ahazelcast%2Fhazelcast-mono+sort%3Acreated-desc)
Please correct as necessary

**Comment by olukas** [comment]
Closing the test failure - it hasn't fail in the last 3 months.

**Comment by AleksPeychev** [comment]
Reopening as issue occurred again on: _master_ (commit 6197a04accf8e17329650645741b48639105a128)
with zing-17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZingJDK17-nightly/108/testReport/junit/classloading/JavaXCacheDependencyClientTest/createHazelcastInstance_getCache/
<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: Application created a ThreadLocal on thread [hz.hz.client_3.IO.thread-in-0] of type [com.hazelcast.internal.networking.nio.NioThread] with key of type [java.lang.ThreadLocal.SuppliedThreadLocal] (value [java.lang.ThreadLocal$SuppliedThreadLocal@5fe59c49]) and a value of type [com.hazelcast.internal.util.MutableInteger] (value [com.hazelcast.internal.util.MutableInteger@5d3e4cc6) but failed to remove it when the application was stopped.
	at classloading.ThreadLocalLeakTestUtils.checkThreadLocalMapForLeaks(ThreadLocalLeakTestUtils.java:176)
	at classloading.ThreadLocalLeakTestUtils.checkThreadLocalsForLeaks(ThreadLocalLeakTestUtils.java:71)
	at classloading.AbstractJavaXCacheDependencyTest.createHazelcastInstance_getCache(AbstractJavaXCacheDependencyTest.java:70)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:898)

```
</details>


<details><summary>Standard output:</summary>

```
Finished Running Test: createHazelcastInstance in 0.093 seconds.
Started Running Test: createHazelcastInstance_getCache
21:26:11,455  INFO |createHazelcastInstance_getCache| - [ClientInvocationService] createHazelcastInstance_getCache - hz.client_3 [dev] [6.0.0-SNAPSHOT] Running with 2 response threads, dynamic=true
21:26:11,456  INFO |createHazelcastInstance_getCache| - [LifecycleService] createHazelcastInstance_getCache - hz.client_3 [dev] [6.0.0-SNAPSHOT] HazelcastClient 6.0.0-SNAPSHOT (20241115) is STARTING
21:26:11,456  INFO |createHazelcastInstance_getCache| - [LifecycleService] createHazelcastInstance_getCache - hz.client_3 [dev] [6.0.0-SNAPSHOT] HazelcastClient 6.0.0-SNAPSHOT (20241115) is STARTED
21:26:11,458  INFO |createHazelcastInstance_getCache| - [ClientConnectionManager] createHazelcastInstance_getCache - hz.client_3 [dev] [6.0.0-SNAPSHOT] Trying to connect to cluster: dev
21:26:11,458  INFO |createHazelcastInstance_getCache| - [ClientConnectionManager] createHazelcastInstance_getCache - hz.client_3 [dev] [6.0.0-SNAPSHOT] Trying to connect to [127.0.0.1]:5701
21:26:11,459 DEBUG || - [AuthenticationMessageTask] hz.HazelcastXAStressTest_flamboyant_jemison.priority-generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [6.0.0-SNAPSHOT] Processing authentication with clientUuid 95d5be80-eaac-40bc-8a5c-3ba813392888 and clientName hz.client_3
21:26:11,459  INFO || - [AuthenticationMessageTask] hz.HazelcastXAStressTest_flamboyant_jemison.priority-generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [6.0.0-SNAPSHOT] Received auth from Connection[id=3, /127.0.0.1:5701->/127.0.0.1:57293, qualifier=null, endpoint=[127.0.0.1]:57293, remoteUuid=95d5be80-eaac-40bc-8a5c-3ba813392888, alive=true, connectionType=JVM, planeIndex=-1], successfully authenticated, clientUuid: 95d5be80-eaac-40bc-8a5c-3ba813392888, client name: hz.client_3, client version: 6.0.0-SNAPSHOT
21:26:11,460  INFO |createHazelcastInstance_getCache| - [ClientClusterService] createHazelcastInstance_getCache - hz.client_3 [dev] [6.0.0-SNAPSHOT] Members [1] {
	Member [127.0.0.1]:5701 - 402c03e5-2f86-4b22-99a3-678872306e3f
}

21:26:11,460  INFO |createHazelcastInstance_getCache| - [LifecycleService] createHazelcastInstance_getCache - hz.client_3 [dev] [6.0.0-SNAPSHOT] HazelcastClient 6.0.0-SNAPSHOT (20241115) is CLIENT_CONNECTED
21:26:11,460  INFO |createHazelcastInstance_getCache| - [ClientConnectionManager] createHazelcastInstance_getCache - hz.client_3 [dev] [6.0.0-SNAPSHOT] Authenticated with server [127.0.0.1]:5701:402c03e5-2f86-4b22-99a3-678872306e3f, server version: 6.0.0-SNAPSHOT, local address: /127.0.0.1:57293
21:26:11,460  INFO |createHazelcastInstance_getCache| - [Diagnostics] createHazelcastInstance_getCache - hz.client_3 [dev] [6.0.0-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
21:26:11,461 DEBUG |createHazelcastInstance_getCache| - [ClientListenerService] hz.client_3.event-15 - hz.client_3 [dev] [6.0.0-SNAPSHOT] No eventHandler for callId: 0, event: ClientMessage{connection=ClientConnection{alive=true, connectionId=1, channel=NioChannel{/127.0.0.1:57293->/127.0.0.1:5701}, remoteAddress=[127.0.0.1]:5701, remoteUuid=402c03e5-2f86-4b22-99a3-678872306e3f, clusterUuid=8fb57305-1cbe-4c0d-b6e2-cac6e86b623e, lastReadTime=2024-11-15 21:26:11.461, lastWriteTime=2024-11-15 21:26:11.460, closedTime=never}, length=38, operation=null, isRetryable=false, correlationId=0, messageType=304, isEvent=true, isfragmented=false}
21:26:11,462  INFO |createHazelcastInstance_getCache| - [ClientStatisticsService] createHazelcastInstance_getCache - Client statistics is enabled with period 5 seconds.
21:26:11,469  INFO |createHazelcastInstance_getCache| - [LifecycleService] createHazelcastInstance_getCache - hz.client_3 [dev] [6.0.0-SNAPSHOT] HazelcastClient 6.0.0-SNAPSHOT (20241115) is SHUTTING_DOWN
21:26:11,469  INFO || - [TcpServerConnection] hz.HazelcastXAStressTest_flamboyant_jemison.IO.thread-in-2 - [127.0.0.1]:5701 [dev] [6.0.0-SNAPSHOT] Connection[id=3, /127.0.0.1:5701->/127.0.0.1:57293, qualifier=null, endpoint=[127.0.0.1]:57293, remoteUuid=95d5be80-eaac-40bc-8a5c-3ba813392888, alive=false, connectionType=JVM, planeIndex=-1] closed. Reason: Connection closed by the other side
21:26:11,469  INFO || - [ClientEndpointManager] hz.HazelcastXAStressTest_flamboyant_jemison.event-27826 - [127.0.0.1]:5701 [dev] [6.0.0-SNAPSHOT] Destroying ClientEndpoint{connection=Connection[id=3, /127.0.0.1:5701->/127.0.0.1:57293, qualifier=null, endpoint=[127.0.0.1]:57293, remoteUuid=95d5be80-eaac-40bc-8a5c-3ba813392888, alive=false, connectionType=JVM, planeIndex=-1], clientUuid=95d5be80-eaac-40bc-8a5c-3ba813392888, clientName=hz.client_3, authenticated=true, clientVersion=6.0.0-SNAPSHOT, creationTime=1731705971459, latest clientAttributes=null, labels=[]}
21:26:11,469  INFO |createHazelcastInstance_getCache| - [ClientConnectionManager] createHazelcastInstance_getCache - hz.client_3 [dev] [6.0.0-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5701:402c03e5-2f86-4b22-99a3-678872306e3f, connection: ClientConnection{alive=false, connectionId=1, channel=NioChannel{/127.0.0.1:57293->/127.0.0.1:5701}, remoteAddress=[127.0.0.1]:5701, remoteUuid=402c03e5-2f86-4b22-99a3-678872306e3f, clusterUuid=8fb57305-1cbe-4c0d-b6e2-cac6e86b623e, lastReadTime=2024-11-15 21:26:11.462, lastWriteTime=2024-11-15 21:26:11.461, closedTime=2024-11-15 21:26:11.469}
21:26:11,469  INFO |createHazelcastInstance_getCache| - [LifecycleService] createHazelcastInstance_getCache - hz.client_3 [dev] [6.0.0-SNAPSHOT] HazelcastClient 6.0.0-SNAPSHOT (20241115) is CLIENT_DISCONNECTED
21:26:11,471  INFO |createHazelcastInstance_getCache| - [LifecycleService] createHazelcastInstance_getCache - hz.client_3 [dev] [6.0.0-SNAPSHOT] HazelcastClient 6.0.0-SNAPSHOT (20241115) is SHUTDOWN

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-ZingJDK17-nightly/108/
