### ISSUE TITLE
Hazelcast Compatibility issue

### ISSUE THREAD

**Issue by RitikaLaddha** [hazelcast/hazelcast#26339]
hazelcast.version: 4.4.6
quarkus.platform.version: 3.6.6
vertx.version: 4.4.5

Are these three versions compatible with each other?

[Link to community question with detailed logs](https://hazelcastcommunity.slack.com/archives/C015Q2TUBKL/p1716386923803379)

**Comment by RitikaLaddha** [comment]
> hazelcast.version: 4.4.6 quarkus.platform.version: 3.6.6 vertx.version: 4.4.5
> 
> Are these three versions compatible with each other?
> 
> [Link to community question with detailed logs](https://hazelcastcommunity.slack.com/archives/C015Q2TUBKL/p1716386923803379)

I am getting different types of error

Error 1:

> 13:43:38 SEVERE traceId=, parentId=, spanId=, sampled= [[co.ha.in.cl.im](http://co.ha.in.cl.im/).op.SplitBrainMergeValidationOp] (hz.CDS-Hazelcast_Instance.priority-generic-operation.thread-0) [10.18.81.153]:5701 [dev] [4.2.8] Target is this node! -> [10.18.81.153]:5701: java.lang.IllegalArgumentException: Target is this node! -> [10.18.81.153]:5701
        at com.hazelcast.spi.impl.operationservice.impl.OutboundResponseHandler.checkTarget(OutboundResponseHandler.java:226)
        at com.hazelcast.spi.impl.operationservice.impl.OutboundResponseHandler.sendNormalResponse(OutboundResponseHandler.java:125)
        at com.hazelcast.spi.impl.operationservice.impl.OutboundResponseHandler.sendResponse(OutboundResponseHandler.java:88)
        at com.hazelcast.spi.impl.operationservice.Operation.sendResponse(Operation.java:475)
        at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:282)
        at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:248)
        at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:469)
        at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:197)
        at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:137)
        at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123)
        at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)

        
        
        
Error 2:

> 13:47:58 INFO  traceId=, parentId=, spanId=, sampled= [[co.ha.in.pa](http://co.ha.in.pa/).op.MigrationRequestOperation] (Thread-65) [10.18.81.16]:5702 [dev] [4.2.8] Failure while executing MigrationInfo{uuid=b531ffea-1363-4b39-8ec6-9d8330166237, partitionId=4, source=[10.18.81.16]:5702 - 126b3847-5365-4416-8ed7-311b6974b27d, sourceCurrentReplicaIndex=0, sourceNewReplicaIndex=3, destination=[10.18.81.8]:5701 - 163be77f-369a-48c0-af56-a4ecc5ea9b86, destinationCurrentReplicaIndex=-1, destinationNewReplicaIndex=0, master=[10.18.81.153]:5701, initialPartitionVersion=381, partitionVersionIncrement=2, status=ACTIVE}: com.hazelcast.core.MemberLeftException: Member [10.18.81.8]:5701 - 163be77f-369a-48c0-af56-a4ecc5ea9b86 has left cluster!
        at com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor$OnMemberLeftTask.onTargetLoss(InvocationMonitor.java:427)
        at com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor$OnMemberLeftTask.run0(InvocationMonitor.java:394)
        at com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor$MonitorTask.run(InvocationMonitor.java:254)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:840)
        

        
        
        
        
        
Error 3:

> INFO exec -a "java" java -Djava.util.logging.manager=org.jboss.logmanager.LogManager -Dvertx.hazelcast.config=/etc/config/hazelcast/cluster.xml -Dquarkus.log.category=INFO -Xms400m -Xmx425m -cp "." -jar /deployments/app.jar 
INFO running in /deployments
Picked up JAVA_TOOL_OPTIONS: -Djava.net.preferIPv4Stack=true
May 22, 2024 8:38:16 AM com.rockwell.idp.administration.AdminServiceLauncher
INFO: Administration Service Application
May 22, 2024 8:38:17 AM io.quarkus.config
WARN: Unrecognized configuration key "quarkus.oidc.keycloak.devservices.enabled" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
May 22, 2024 8:38:17 AM io.quarkus.config
WARN: Unrecognized configuration key "quarkus.log.category" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
May 22, 2024 8:38:18 AM org.hibernate.validator.internal.util.Version
INFO: HV000001: Hibernate Validator 1.3.0-28-SNAPSHOT
May 22, 2024 8:38:20 AM com.hazelcast.config.AbstractXmlConfigHelper
WARNING: Name of the hazelcast schema location[http://www.hazelcast.com/schema/config/hazelcast-config-5.1.xsd] is incorrect, using default
May 22, 2024 8:38:21 AM com.hazelcast.instance.impl.HazelcastInstanceFactory
WARNING: Hazelcast is starting in a Java modular environment (Java 9 and newer) but without proper access to required Java packages. Use additional Java arguments to provide Hazelcast access to Java internal API. The internal API access is used to get the best performance results. Arguments to be used:
 --add-modules java.se --add-exports java.base/jdk.internal.ref=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.management/sun.management=ALL-UNNAMED --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED
May 22, 2024 8:38:21 AM com.hazelcast.system
INFO: [10.18.81.157]:5701 [dev] [4.2.8] Hazelcast 4.2.8 (20230529 - 90df6cd) starting at [10.18.81.157]:5701
May 22, 2024 8:38:22 AM com.hazelcast.spi.discovery.integration.DiscoveryService
INFO: [10.18.81.157]:5701 [dev] [4.2.8] Kubernetes Discovery properties: { service-dns: hazelcast-service.idp.svc.cluster.local, service-dns-timeout: 5, service-name: null, service-port: 0, service-label: null, service-label-value: true, namespace: null, pod-label: null, pod-label-value: null, resolve-not-ready-addresses: true, use-node-name-as-external-address: false, kubernetes-api-retries: 3, kubernetes-master: https://192.168.0.1:443}
May 22, 2024 8:38:22 AM com.hazelcast.spi.discovery.integration.DiscoveryService
INFO: [10.18.81.157]:5701 [dev] [4.2.8] Kubernetes Discovery activated with mode: DNS_LOOKUP
May 22, 2024 8:38:22 AM com.hazelcast.instance.impl.Node
INFO: [10.18.81.157]:5701 [dev] [4.2.8] Using Discovery SPI
May 22, 2024 8:38:22 AM com.hazelcast.cp.CPSubsystem
WARNING: [10.18.81.157]:5701 [dev] [4.2.8] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
May 22, 2024 8:38:23 AM com.hazelcast.internal.diagnostics.Diagnostics
INFO: [10.18.81.157]:5701 [dev] [4.2.8] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
May 22, 2024 8:38:23 AM com.hazelcast.core.LifecycleService
INFO: [10.18.81.157]:5701 [dev] [4.2.8] [10.18.81.157]:5701 is STARTING
May 22, 2024 8:38:23 AM com.hazelcast.internal.cluster.impl.DiscoveryJoiner
INFO: [10.18.81.157]:5701 [dev] [4.2.8] [192.168.54.25]:5701 is added to the blacklist.
May 22, 2024 8:38:23 AM com.hazelcast.internal.cluster.impl.DiscoveryJoiner
INFO: [10.18.81.157]:5701 [dev] [4.2.8] [192.168.54.25]:5701 is removed from the blacklist.
May 22, 2024 8:38:23 AM com.hazelcast.internal.server.tcp.TcpServerConnection
INFO: [10.18.81.157]:5701 [dev] [4.2.8] Initialized new cluster connection between /10.18.81.157:5701 and /10.18.81.139:47102
May 22, 2024 8:38:23 AM com.hazelcast.internal.server.tcp.TcpServerConnection
INFO: [10.18.81.157]:5701 [dev] [4.2.8] Initialized new cluster connection between /0.0.0.0:49729 and /192.168.54.25:5701
May 22, 2024 8:39:37 AM com.hazelcast.internal.server.tcp.TcpServerConnection
INFO: [10.18.81.157]:5701 [dev] [4.2.8] Initialized new cluster connection between /10.18.81.157:5701 and /10.18.81.206:37569
May 22, 2024 8:39:47 AM com.hazelcast.internal.server.tcp.TcpServerConnection
INFO: [10.18.81.157]:5701 [dev] [4.2.8] Initialized new cluster connection between /10.18.81.157:5701 and /10.18.81.206:33339
May 22, 2024 8:43:23 AM com.hazelcast.instance.impl.Node
SEVERE: [10.18.81.157]:5701 [dev] [4.2.8] Could not join cluster. Shutting down now!
May 22, 2024 8:43:23 AM com.hazelcast.core.LifecycleService
INFO: [10.18.81.157]:5701 [dev] [4.2.8] [10.18.81.157]:5701 is SHUTTING_DOWN
May 22, 2024 8:43:23 AM com.hazelcast.instance.impl.Node
WARNING: [10.18.81.157]:5701 [dev] [4.2.8] Terminating forcefully...
May 22, 2024 8:43:23 AM com.hazelcast.instance.impl.Node
INFO: [10.18.81.157]:5701 [dev] [4.2.8] Shutting down connection manager...
May 22, 2024 8:43:23 AM com.hazelcast.internal.server.tcp.TcpServerConnection
INFO: [10.18.81.157]:5701 [dev] [4.2.8] Connection[id=3, /10.18.81.157:5701->/10.18.81.206:37569, qualifier=null, endpoint=[10.18.81.206]:5701, alive=false, connectionType=MEMBER, planeIndex=0] closed. Reason: TcpServer is stopping
May 22, 2024 8:43:23 AM com.hazelcast.internal.server.tcp.TcpServerConnection
INFO: [10.18.81.157]:5701 [dev] [4.2.8] Connection[id=1, /0.0.0.0:49729->/192.168.54.25:5701, qualifier=null, endpoint=[192.168.54.25]:5701, alive=false, connectionType=MEMBER, planeIndex=0] closed. Reason: TcpServer is stopping
May 22, 2024 8:43:23 AM com.hazelcast.internal.server.tcp.TcpServerConnection
INFO: [10.18.81.157]:5701 [dev] [4.2.8] Connection[id=4, /10.18.81.157:5701->/10.18.81.206:33339, qualifier=null, endpoint=[10.18.81.206]:5702, alive=false, connectionType=MEMBER, planeIndex=0] closed. Reason: TcpServer is stopping
May 22, 2024 8:43:23 AM com.hazelcast.internal.server.tcp.TcpServerConnection
INFO: [10.18.81.157]:5701 [dev] [4.2.8] Connection[id=2, /10.18.81.157:5701->/10.18.81.139:47102, qualifier=null, endpoint=[10.18.81.157]:5701, alive=false, connectionType=MEMBER, planeIndex=0] closed. Reason: Connection closed by the other side
May 22, 2024 8:43:23 AM com.hazelcast.instance.impl.Node
INFO: [10.18.81.157]:5701 [dev] [4.2.8] Shutting down node engine...
May 22, 2024 8:43:23 AM com.hazelcast.instance.impl.NodeExtension
INFO: [10.18.81.157]:5701 [dev] [4.2.8] Destroying node NodeExtension.
May 22, 2024 8:43:23 AM com.hazelcast.instance.impl.Node
INFO: [10.18.81.157]:5701 [dev] [4.2.8] Hazelcast Shutdown is completed in 8 ms.
May 22, 2024 8:43:23 AM com.hazelcast.core.LifecycleService
INFO: [10.18.81.157]:5701 [dev] [4.2.8] [10.18.81.157]:5701 is SHUTDOWN
May 22, 2024 8:43:23 AM com.hazelcast.internal.util.phonehome.PhoneHome
WARNING: [10.18.81.157]:5701 [dev] [4.2.8] Could not schedule phone home task! Most probably Hazelcast failed to start.
May 22, 2024 8:43:23 AM com.hazelcast.instance.impl.Node
INFO: [10.18.81.157]:5701 [dev] [4.2.8] Node is already shutting down... Waiting for shutdown process to complete...
May 22, 2024 8:43:23 AM io.vertx.core.impl.VertxImpl
ERROR: Failed to initialize clustered Vert.x
java.lang.IllegalStateException: Node failed to start!
	at com.hazelcast.instance.impl.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:125)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:211)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:190)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:128)
	at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:57)
	at io.vertx.spi.cluster.hazelcast.HazelcastClusterManager.lambda$join$1(HazelcastClusterManager.java:135)
	at io.vertx.core.impl.ContextBase.lambda$executeBlocking$1(ContextBase.java:180)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:277)
	at io.vertx.core.impl.ContextBase.lambda$internalExecuteBlocking$2(ContextBase.java:199)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:587)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)

May 22, 2024 8:43:23 AM io.vertx.core.impl.VertxImpl
ERROR: Failed to leave cluster
java.lang.NullPointerException: Cannot invoke "io.vertx.spi.cluster.hazelcast.impl.SubsMapHelper.close()" because "this.subsMapHelper" is null
	at io.vertx.spi.cluster.hazelcast.HazelcastClusterManager.lambda$leave$5(HazelcastClusterManager.java:255)
	at io.vertx.core.impl.ContextBase.lambda$executeBlocking$1(ContextBase.java:180)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:277)
	at io.vertx.core.impl.ContextBase.lambda$internalExecuteBlocking$2(ContextBase.java:199)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)

May 22, 2024 8:43:23 AM io.quarkus.runtime.ApplicationLifecycleManager run
ERROR: Failed to start application (with profile [prod])
java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
	at com.rockwell.idp.administration.AdminServiceLauncher.main(AdminServiceLauncher.java:21)
Caused by: java.util.concurrent.CompletionException: java.lang.IllegalStateException: Node failed to start!
	at java.base/java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:413)
	at java.base/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2118)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder.initialize(VertxCoreRecorder.java:240)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$VertxSupplier.get(VertxCoreRecorder.java:619)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$VertxSupplier.get(VertxCoreRecorder.java:598)
	at io.quarkus.opentelemetry.runtime.OpenTelemetryRecorder.storeVertxOnContextStorage(OpenTelemetryRecorder.java:45)
	at io.quarkus.deployment.steps.OpenTelemetryProcessor$createOpenTelemetry193862828.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.OpenTelemetryProcessor$createOpenTelemetry193862828.deploy(Unknown Source)
	... 7 more
Caused by: java.lang.IllegalStateException: Node failed to start!
	at com.hazelcast.instance.impl.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:125)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:211)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:190)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:128)
	at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:57)
	at io.vertx.spi.cluster.hazelcast.HazelcastClusterManager.lambda$join$1(HazelcastClusterManager.java:135)
	at io.vertx.core.impl.ContextBase.lambda$executeBlocking$1(ContextBase.java:180)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:277)
	at io.vertx.core.impl.ContextBase.lambda$internalExecuteBlocking$2(ContextBase.java:199)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:587)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)




Error 4:

> 12:25:10 INFO  traceId=, parentId=, spanId=, sampled= [co.ha.in.se.InternalSerializationService] (executor-thread-7) Performance Hint: Serialization service will use java.io.Serializable for: java.lang.String. Please consider using a faster serialization option such as DataSerializable.
12:25:10 WARN  traceId=, parentId=, spanId=, sampled= [io.ve.co.ev.im.cl.ConnectionHolder] (vert.x-eventloop-thread-1) Connecting to server b9fefb2b-3eb5-47be-9aa3-ef842e4e0dd4 failed: com.hazelcast.core.HazelcastInstanceNotActiveException: State: SHUT_DOWN Operation: class com.hazelcast.map.impl.operation.GetOperation
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.engineActive(Invocation.java:512)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:550)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:540)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:240)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:59)
	at com.hazelcast.map.impl.proxy.MapProxySupport.invokeOperation(MapProxySupport.java:478)
	at com.hazelcast.map.impl.proxy.MapProxySupport.getInternal(MapProxySupport.java:372)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.get(MapProxyImpl.java:123)
	at io.vertx.spi.cluster.hazelcast.HazelcastClusterManager.lambda$getNodeInfo$3(HazelcastClusterManager.java:198)
	at io.vertx.core.impl.ContextBase.lambda$executeBlocking$1(ContextBase.java:180)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:277)
	at io.vertx.core.impl.ContextBase.lambda$internalExecuteBlocking$2(ContextBase.java:199)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1512)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)
	at ------ submitted from ------.()
	at com.hazelcast.internal.util.ExceptionUtil.cloneExceptionWithFixedAsyncStackTrace(ExceptionUtil.java:289)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.returnOrThrowWithGetConventions(InvocationFuture.java:112)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:100)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:609)
	at com.hazelcast.map.impl.proxy.MapProxySupport.invokeOperation(MapProxySupport.java:479)
	at com.hazelcast.map.impl.proxy.MapProxySupport.getInternal(MapProxySupport.java:372)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.get(MapProxyImpl.java:123)
	at io.vertx.spi.cluster.hazelcast.HazelcastClusterManager.lambda$getNodeInfo$3(HazelcastClusterManager.java:198)
	at io.vertx.core.impl.ContextBase.lambda$executeBlocking$1(ContextBase.java:180)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:277)
	at io.vertx.core.impl.ContextBase.lambda$internalExecuteBlocking$2(ContextBase.java:199)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1512)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)
12:26:36 INFO  traceId=, parentId=, spanId=, sampled= [co.ro.id.ad.co.EventBusConsumer] (executor-thread-7) Message Received: {"body":null,"headers":{"action":"GET_RESOURCE","requestId":"cd5bf2e7-1b33-4c6e-839a-12818f46c25b","resourceId":null,"resourceName":"system"}}
12:26:36 INFO  traceId=, parentId=, spanId=, sampled= [[co.ro.id.ad](http://co.ro.id.ad/).ha.HealthHandler] (executor-thread-7) Received: null, {"action":"GET_RESOURCE","requestId":"cd5bf2e7-1b33-4c6e-839a-12818f46c25b","resourceId":null,"resourceName":"system"}
12:26:36 INFO  traceId=, parentId=, spanId=, sampled= [[co.ro.id.ad](http://co.ro.id.ad/).ha.HealthHandler] (executor-thread-7) Request Received with requestBody: null | action: GET_RESOURCE | resourceName: system | resourceId: null | requestId: cd5bf2e7-1b33-4c6e-839a-12818f46c25b
12:26:36 INFO  traceId=, parentId=, spanId=, sampled= [[co.ro.id.ad.se](http://co.ro.id.ad.se/).k8.K8sDeploymentOperations] (executor-thread-7) Fetching System Health Information
12:26:36 INFO  traceId=, parentId=, spanId=, sampled= [[co.ro.id.ad.se](http://co.ro.id.ad.se/).k8.K8sDeploymentOperations] (executor-thread-7) Fetching System Health Informationio.fabric8.kubernetes.client.impl.KubernetesClientImpl@597da8db
12:26:36 INFO  traceId=, parentId=, spanId=, sampled= [co.ro.id.ad.se.he.im.HealthServiceImpl] (executor-thread-7) Responding with the current configuration: {"owner":"CDS","instance_id":"383a98fb-3a3b-43e7-ae00-cd9797d33503","description":"Converged Data Services Dev Environment","env":"dev","version":"1.1.0","uuid":"3e79b02a-8881-4d0d-9e68-9a9478e8655b","email":"[swcidpeng@rockwellautomation.onmicrosoft.com](mailto:swcidpeng@rockwellautomation.onmicrosoft.com)"}
12:26:36 WARN  traceId=, parentId=, spanId=, sampled= [io.ve.co.ev.im.cl.ConnectionHolder] (vert.x-eventloop-thread-1) Connecting to server 6ef178b6-61c9-4c69-b366-e43a912c2745 failed: com.hazelcast.core.HazelcastInstanceNotActiveException: State: SHUT_DOWN Operation: class com.hazelcast.map.impl.operation.GetOperation
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.engineActive(Invocation.java:512)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:550)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:540)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:240)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:59)
	at com.hazelcast.map.impl.proxy.MapProxySupport.invokeOperation(MapProxySupport.java:478)
	at com.hazelcast.map.impl.proxy.MapProxySupport.getInternal(MapProxySupport.java:372)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.get(MapProxyImpl.java:123)
	at io.vertx.spi.cluster.hazelcast.HazelcastClusterManager.lambda$getNodeInfo$3(HazelcastClusterManager.java:198)
	at io.vertx.core.impl.ContextBase.lambda$executeBlocking$1(ContextBase.java:180)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:277)
	at io.vertx.core.impl.ContextBase.lambda$internalExecuteBlocking$2(ContextBase.java:199)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1512)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)
	at ------ submitted from ------.()
	at com.hazelcast.internal.util.ExceptionUtil.cloneExceptionWithFixedAsyncStackTrace(ExceptionUtil.java:289)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.returnOrThrowWithGetConventions(InvocationFuture.java:112)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:100)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:609)
	at com.hazelcast.map.impl.proxy.MapProxySupport.invokeOperation(MapProxySupport.java:479)
	at com.hazelcast.map.impl.proxy.MapProxySupport.getInternal(MapProxySupport.java:372)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.get(MapProxyImpl.java:123)
	at io.vertx.spi.cluster.hazelcast.HazelcastClusterManager.lambda$getNodeInfo$3(HazelcastClusterManager.java:198)
	at io.vertx.core.impl.ContextBase.lambda$executeBlocking$1(ContextBase.java:180)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:277)
	at io.vertx.core.impl.ContextBase.lambda$internalExecuteBlocking$2(ContextBase.java:199)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1512)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)
