### ISSUE TITLE
com.hazelcast.test.HazelcastTestSupportTest [HZG-15]

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hazelcast#26335]
_master_ (commit 4e2c5389247b64991932023ffaa91e6ec0f5bf24)

Failed on MacOS - ZuluJDK21: https://jenkins.hazelcast.com/job/Hazelcast-master-MacOS-ZuluJDK21/41/testReport/junit/com.hazelcast.test/HazelcastTestSupportTest/

<details><summary>Stacktrace:</summary>

```
java.lang.InternalError: java.lang.IllegalAccessException: static final field has no write access: com.hazelcast.test.HazelcastTestSupportTest$TestClass.publicStaticFinalField/java.lang.Object/putStatic, from class java.lang.Object (module java.base)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newFieldAccessor(MethodHandleAccessorFactory.java:167)
	at java.base/jdk.internal.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:145)
	at java.base/java.lang.reflect.Field.acquireOverrideFieldAccessor(Field.java:1200)
	at java.base/java.lang.reflect.Field.getOverrideFieldAccessor(Field.java:1169)
	at java.base/java.lang.reflect.Field.set(Field.java:836)
	at com.hazelcast.test.HazelcastTestSupport.setFieldValue(HazelcastTestSupport.java:1516)
	at com.hazelcast.test.HazelcastTestSupport.setFieldValue(HazelcastTestSupport.java:1496)
	at com.hazelcast.test.HazelcastTestSupportTest.test_setPublicStaticFinalField(HazelcastTestSupportTest.java:34)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.IllegalAccessException: static final field has no write access: com.hazelcast.test.HazelcastTestSupportTest$TestClass.publicStaticFinalField/java.lang.Object/putStatic, from class java.lang.Object (module java.base)
	at java.base/java.lang.invoke.MemberName.makeAccessException(MemberName.java:894)
	at java.base/java.lang.invoke.MethodHandles$Lookup.unreflectField(MethodHandles.java:3597)
	at java.base/java.lang.invoke.MethodHandles$Lookup.unreflectSetter(MethodHandles.java:3588)
	at java.base/java.lang.invoke.MethodHandleImpl$1.unreflectField(MethodHandleImpl.java:1632)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newFieldAccessor(MethodHandleAccessorFactory.java:145)
	... 12 more

```
</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: test_setPrivateStaticField in 0.001 seconds.
Started Running Test: test_setPublicStaticFinalField
02:30:30,218  INFO |test_setPublicStaticFinalField| - [HazelcastTestSupport] main - Shutting down node factory as @After action
BuildInfo right after test_setPublicStaticFinalField(com.hazelcast.test.HazelcastTestSupportTest): BuildInfo{version='5.5.0-SNAPSHOT', build='20240516', buildNumber=20240516, revision=, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'test_setPublicStaticFinalField(com.hazelcast.test.HazelcastTestSupportTest):'
02:30:30, accumulated pauses: 88 ms, max pause: 69 ms, pauses over 1000 ms: 0


No metrics recorded during the test

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-MacOS-ZuluJDK21/41/

**Comment by sumnerib** [comment]
Failed again on _master_ with redhat-21: https://jenkins.hazelcast.com/job/Hazelcast-master-RedHatJDK21/18/testReport/junit/com.hazelcast.test/HazelcastTestSupportTest/

**Comment by Patras3** [comment]
Failed again on _master_ with Windows - OracleJDK21: https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-OracleJDK21/4/testReport/com.hazelcast.test/HazelcastTestSupportTest/

**Comment by Patras3** [comment]
Looks like here 2 tests are also affected due to above:
Failed again on _master_ with Windows - OracleJDK21: https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-OracleJDK21/4/testReport/com.hazelcast.internal.util.phonehome/PhoneHomeIntegrationTest/

**Comment by Patras3** [comment]
Failed again on _master_ with MacOS - ZuluJDK21: https://jenkins.hazelcast.com/job/Hazelcast-master-MacOS-ZuluJDK21/42/testReport/com.hazelcast.test/HazelcastTestSupportTest/

**Comment by JackPGreen** [comment]
@burakgok could this have been introduced inn https://github.com/hazelcast/hazelcast-mono/pull/1303?
