### ISSUE TITLE
com.hazelcast.config.IndexConfigTest.testIndexEquality [HZ-4755]

### ISSUE THREAD

**Issue by Patras3** [hazelcast/hazelcast#26337]
_5.4.z_ (commit e6223c755fee943f2057e7100caf2794088aab87)

Failed on openj9-21: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-Openj9-21/3/testReport/junit/com.hazelcast.config/IndexConfigTest/testIndexEquality/
<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: expected:<false> but was:<true>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:120)
	at org.junit.Assert.assertEquals(Assert.java:146)
	at com.hazelcast.config.IndexConfigTest.checkIndexQuality(IndexConfigTest.java:74)
	at com.hazelcast.config.IndexConfigTest.testIndexEquality(IndexConfigTest.java:58)
	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.lang.Thread.run(Thread.java:1595)

```
</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: testIndexDefaults in 0.042 seconds.

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-5.maintenance-Openj9-21/3/

**Comment by Fly-Style** [comment]
Took a look on the test. Clearly, false positive, Universe fluctuation. Impossible (read with french accent).
