### ISSUE TITLE
com.hazelcast.client.SubsetClientRoutingPartitionGroupTest.terminated_members_are_removed_from_memberGroupView

### ISSUE THREAD

**Issue by Patras3** [hazelcast/hazelcast#26338]
_master_ (commit 61a34c0b5b2db066173933eaefa37af84a64cd84)

Failed on MacOS - ZuluJDK21: https://jenkins.hazelcast.com/job/Hazelcast-master-MacOS-ZuluJDK21/42/testReport/com.hazelcast.client/SubsetClientRoutingPartitionGroupTest/terminated_members_are_removed_from_memberGroupView/
<details><summary>Stacktrace:</summary>

```
com.hazelcast.client.HazelcastClientNotActiveException: Client is shutting down
	at com.hazelcast.client.impl.spi.impl.ClientInvocation.notifyExceptionWithOwnedPermission(ClientInvocation.java:323)
	at com.hazelcast.client.impl.spi.impl.ClientInvocation.invokeOnSelection(ClientInvocation.java:212)
	at com.hazelcast.client.impl.spi.impl.ClientInvocation.invoke(ClientInvocation.java:156)
	at com.hazelcast.client.impl.spi.ClientProxy.invokeOnPartition(ClientProxy.java:188)
	at com.hazelcast.client.impl.spi.ClientProxy.invoke(ClientProxy.java:183)
	at com.hazelcast.client.impl.proxy.ClientMapProxy.getInternal(ClientMapProxy.java:266)
	at com.hazelcast.client.impl.proxy.ClientMapProxy.get(ClientMapProxy.java:260)
	at com.hazelcast.client.SubsetClientRoutingPartitionGroupTest.terminated_members_are_removed_from_memberGroupView(SubsetClientRoutingPartitionGroupTest.java:189)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.lang.Thread.run(Thread.java:1583)
	at ------ submitted from ------.()
	at com.hazelcast.internal.util.ExceptionUtil.cloneExceptionWithFixedAsyncStackTrace(ExceptionUtil.java:348)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.returnOrThrowWithGetConventions(InvocationFuture.java:112)
	at com.hazelcast.client.impl.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:95)
	at com.hazelcast.client.impl.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:40)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:610)
	at com.hazelcast.client.impl.spi.ClientProxy.invokeOnPartition(ClientProxy.java:189)
	at com.hazelcast.client.impl.spi.ClientProxy.invoke(ClientProxy.java:183)
	at com.hazelcast.client.impl.proxy.ClientMapProxy.getInternal(ClientMapProxy.java:266)
	at com.hazelcast.client.impl.proxy.ClientMapProxy.get(ClientMapProxy.java:260)
	at com.hazelcast.client.SubsetClientRoutingPartitionGroupTest.terminated_members_are_removed_from_memberGroupView(SubsetClientRoutingPartitionGroupTest.java:189)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.io.IOException: No connection found to cluster.
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.checkInvocationAllowed(TcpClientConnectionManager.java:643)
	at com.hazelcast.client.impl.spi.impl.ClientInvocationServiceImpl.checkInvocationAllowed(ClientInvocationServiceImpl.java:336)
	at com.hazelcast.client.impl.spi.impl.ClientInvocation.invokeOnSelection(ClientInvocation.java:180)
	at com.hazelcast.client.impl.spi.impl.ClientInvocation.invoke(ClientInvocation.java:156)
	at com.hazelcast.client.impl.spi.ClientProxy.invokeOnPartition(ClientProxy.java:188)
	... 9 more

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-MacOS-ZuluJDK21/42/

**Comment by nishaatr** [comment]
Changed Milestone to 6.0.0 to ensure 5.5.0 does not report any Open [issues ](https://github.com/issues?page=1&q=is%3Aopen+milestone%3A5.5.0+repo%3Ahazelcast%2Fhazelcast+repo%3Ahazelcast%2Fhazelcast-enterprise+repo%3Ahazelcast%2Fhazelcast-mono+sort%3Acreated-desc)
Please correct as necessary

**Comment by Patras3** [comment]
This comment was automatically generated to summarize test results for the last 30 days.

```

For branch: master
Builds between : 2024-07-02 03:07 - 2024-07-08 06:13
Jobs: 24, Runs: 27, Passed: 27, Failed: 0, Skipped: 0, Fail Ratio: 0.00%
Run on:
+----------------------------------------------------+
| JDK          | PASSED | FAILED | SKIPPED |  RATIO  |
+----------------------------------------------------+
| corretto-21  |   1    |   0    |    0    |   0.00% |
| oracle-17    |   5    |   0    |    0    |   0.00% |
| microsoft-21 |   1    |   0    |    0    |   0.00% |
| oracle-21    |   1    |   0    |    0    |   0.00% |
| zing-17      |   1    |   0    |    0    |   0.00% |
| zing-21      |   1    |   0    |    0    |   0.00% |
| microsoft-17 |   2    |   0    |    0    |   0.00% |
| openj9-17    |   1    |   0    |    0    |   0.00% |
| unknown      |   8    |   0    |    0    |   0.00% |
| openjdk-17   |   1    |   0    |    0    |   0.00% |
| redhat-21    |   1    |   0    |    0    |   0.00% |
| corretto-17  |   1    |   0    |    0    |   0.00% |
| redhat-17    |   1    |   0    |    0    |   0.00% |
| openjdk-21   |   1    |   0    |    0    |   0.00% |
| openj9-21    |   1    |   0    |    0    |   0.00% |
+----------------------------------------------------+

Builds Timeline:
2024-07-08 06:13 - PASSED (openjdk-21):
    https://jenkins.hazelcast.com/job/Hazelcast-EE-master-ZuluJDK21/25/testReport/com.hazelcast.client/SubsetClientRoutingPartitionGroupTest/terminated_members_are_removed_from_memberGroupView/
2024-07-08 02:32 - PASSED (oracle-17):
    https://jenkins.hazelcast.com/job/Hazelcast-EE-master-sonar/558/testReport/com.hazelcast.client/SubsetClientRoutingPartitionGroupTest/terminated_members_are_removed_from_memberGroupView/
2024-07-08 02:27 - PASSED (oracle-17):
    https://jenkins.hazelcast.com/job/Hazelcast-mono-EE-master-sonar/232/testReport/com.hazelcast.client/SubsetClientRoutingPartitionGroupTest/terminated_members_are_removed_from_memberGroupView/
2024-07-08 00:06 - PASSED (redhat-17):
    https://jenkins.hazelcast.com/job/Hazelcast-EE-master-RedHatJDK17/127/testReport/com.hazelcast.client/SubsetClientRoutingPartitionGroupTest/terminated_members_are_removed_from_memberGroupView/
2024-07-07 21:06 - PASSED (openjdk-17):
    https://jenkins.hazelcast.com/job/Hazelcast-EE-master-ZuluJDK17/140/testReport/com.hazelcast.client/SubsetClientRoutingPartitionGroupTest/terminated_members_are_removed_from_memberGroupView/
2024-07-07 20:12 - PASSED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-EE-master-Windows-MicrosoftJDK21/25/testReport/com.hazelcast.client/SubsetClientRoutingPartitionGroupTest/terminated_members_are_removed_from_memberGroupView/
2024-07-07 09:10 - PASSED (corretto-21):
    https://jenkins.hazelcast.com/job/Hazelcast-EE-master-CorrettoJDK21/25/testReport/com.hazelcast.client/SubsetClientRoutingPartitionGroupTest/terminated_members_are_removed_from_memberGroupView/
2024-07-07 09:05 - PASSED (oracle-17):
    https://jenkins.hazelcast.com/job/Hazelcast-EE-master-little-endian/314/testReport/com.hazelcast.client/SubsetClientRoutingPartitionGroupTest/terminated_members_are_removed_from_memberGroupView/
2024-07-07 03:05 - PASSED (openj9-17):
    https://jenkins.hazelcast.com/job/Hazelcast-EE-master-Openj9-17/126/testReport/com.hazelcast.client/SubsetClientRoutingPartitionGroupTest/terminated_members_are_removed_from_memberGroupView/
2024-07-06 21:08 - PASSED (oracle-17):
    https://jenkins.hazelcast.com/job/Hazelcast-EE-master-force-offload/106/testReport/com.hazelcast.client/SubsetClientRoutingPartitionGroupTest/terminated_members_are_removed_from_memberGroupView/
2024-07-06 12:13 - PASSED (corretto-17):
    https://jenkins.hazelcast.com/job/Hazelcast-EE-master-CorrettoJDK17/143/testReport/com.hazelcast.client/SubsetClientRoutingPartitionGroupTest/terminated_members_are_removed_from_memberGroupView/
2024-07-05 21:43 - PASSED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-EE-master-MacOS-OpenJDK17/47/testReport/com.hazelcast.client/SubsetClientRoutingPartitionGroupTest/terminated_members_are_removed_from_memberGroupView/
2024-07-05 21:09 - PASSED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-EE-master-OpenJDK17-Esxi7/93/testReport/com.hazelcast.client/SubsetClientRoutingPartitionGroupTest/terminated_members_are_removed_from_memberGroupView/
2024-07-05 18:01 - PASSED (zing-21):
    https://jenkins.hazelcast.com/job/Hazelcast-EE-master-ZingJDK21/28/testReport/com.hazelcast.client/SubsetClientRoutingPartitionGroupTest/terminated_members_are_removed_from_memberGroupView/
2024-07-05 17:03 - PASSED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-EE-master-MacOS-ZuluJDK21/49/testReport/com.hazelcast.client/SubsetClientRoutingPartitionGroupTest/terminated_members_are_removed_from_memberGroupView/
2024-07-05 00:12 - PASSED (oracle-17):
    https://jenkins.hazelcast.com/job/Hazelcast-EE-master-OracleJDK17/143/testReport/com.hazelcast.client/SubsetClientRoutingPartitionGroupTest/terminated_members_are_removed_from_memberGroupView/
2024-07-04 21:00 - PASSED (openj9-21):
    https://jenkins.hazelcast.com/job/Hazelcast-EE-master-Openj9-21/24/testReport/com.hazelcast.client/SubsetClientRoutingPartitionGroupTest/terminated_members_are_removed_from_memberGroupView/
2024-07-04 14:17 - PASSED (microsoft-17):
    https://jenkins.hazelcast.com/job/Hazelcast-EE-master-MicrosoftJDK17/125/testReport/com.hazelcast.client/SubsetClientRoutingPartitionGroupTest/terminated_members_are_removed_from_memberGroupView/
2024-07-04 03:03 - PASSED (microsoft-17):
    https://jenkins.hazelcast.com/job/Hazelcast-EE-master-MicrosoftJDK17/124/testReport/com.hazelcast.client/SubsetClientRoutingPartitionGroupTest/terminated_members_are_removed_from_memberGroupView/
2024-07-03 23:20 - PASSED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-EE-master-CorrettoJDK17-arm64/26/testReport/com.hazelcast.client/SubsetClientRoutingPartitionGroupTest/terminated_members_are_removed_from_memberGroupView/
2024-07-03 21:00 - PASSED (zing-17):
    https://jenkins.hazelcast.com/job/Hazelcast-EE-master-ZingJDK17/94/testReport/com.hazelcast.client/SubsetClientRoutingPartitionGroupTest/terminated_members_are_removed_from_memberGroupView/
2024-07-03 06:14 - PASSED (redhat-21):
    https://jenkins.hazelcast.com/job/Hazelcast-EE-master-RedHatJDK21/24/testReport/com.hazelcast.client/SubsetClientRoutingPartitionGroupTest/terminated_members_are_removed_from_memberGroupView/
2024-07-02 21:43 - PASSED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-EE-master-MacOS-OpenJDK17/46/testReport/com.hazelcast.client/SubsetClientRoutingPartitionGroupTest/terminated_members_are_removed_from_memberGroupView/
2024-07-02 21:05 - PASSED (oracle-21):
    https://jenkins.hazelcast.com/job/Hazelcast-EE-master-OracleJDK21/22/testReport/com.hazelcast.client/SubsetClientRoutingPartitionGroupTest/terminated_members_are_removed_from_memberGroupView/
2024-07-02 20:14 - PASSED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-EE-master-Windows-MicrosoftJDK17/132/testReport/com.hazelcast.client/SubsetClientRoutingPartitionGroupTest/terminated_members_are_removed_from_memberGroupView/
2024-07-02 17:03 - PASSED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-EE-master-MacOS-ZuluJDK21/48/testReport/com.hazelcast.client/SubsetClientRoutingPartitionGroupTest/terminated_members_are_removed_from_memberGroupView/
2024-07-02 03:07 - PASSED (microsoft-21):
    https://jenkins.hazelcast.com/job/Hazelcast-EE-master-MicrosoftJDK21/25/testReport/com.hazelcast.client/SubsetClientRoutingPartitionGroupTest/terminated_members_are_removed_from_memberGroupView/

----------------------------------------
```
