### ISSUE TITLE
com.hazelcast.jet.impl.deployment.JetClassLoaderTest.when_processorCalled_then_contextClassLoaderSet

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hazelcast#26332]
_5.4.z_ (commit 9191ef1b22e4a03e667c873f23f46e403db490d7)

Failed on openj9-21: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-Openj9-21/2/testReport/com.hazelcast.jet.impl.deployment/JetClassLoaderTest/when_processorCalled_then_contextClassLoaderSet/
<details><summary>Stacktrace:</summary>

```
java.lang.NullPointerException
	at java.base/java.lang.StringConcatHelper.simpleConcat(StringConcatHelper.java)
	at com.hazelcast.jet.core.JetTestSupport.lambda$assertJobStatusEventually$2(JetTestSupport.java:338)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1200)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1219)
	at com.hazelcast.jet.core.JetTestSupport.assertJobStatusEventually(JetTestSupport.java:337)
	at com.hazelcast.jet.core.JetTestSupport.assertJobStatusEventually(JetTestSupport.java:253)
	at com.hazelcast.jet.impl.deployment.JetClassLoaderTest.when_processorCalled_then_contextClassLoaderSet(JetClassLoaderTest.java:108)
	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.lang.Thread.run(Thread.java:1595)

```
</details>

<details><summary>Standard output:</summary>

```
Started Running Test: when_processorCalled_then_contextClassLoaderSet
01:22:47,347  INFO |when_processorCalled_then_contextClassLoaderSet| - [MetricsConfigHelper] when_processorCalled_then_contextClassLoaderSet - [LOCAL] [dev] [5.4.1-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
01:22:47,348  INFO |when_processorCalled_then_contextClassLoaderSet| - [logo] when_processorCalled_then_contextClassLoaderSet - [127.0.0.1]:5701 [dev] [5.4.1-SNAPSHOT] 
	o    o     o     o---o   o--o o      o---o     o     o----o o--o--o
	|    |    / \       /         |     /         / \    |         |   
	o----o       o     o   o----o |    o             o   o----o    |   
	|    |  *     \   /           |     \       *     \       |    |   
	o    o *       o o---o   o--o o----o o---o *       o o----o    o   
01:22:47,348  INFO |when_processorCalled_then_contextClassLoaderSet| - [system] when_processorCalled_then_contextClassLoaderSet - [127.0.0.1]:5701 [dev] [5.4.1-SNAPSHOT] Copyright (c) 2008-2024, Hazelcast, Inc. All Rights Reserved.
01:22:47,348  INFO |when_processorCalled_then_contextClassLoaderSet| - [system] when_processorCalled_then_contextClassLoaderSet - [127.0.0.1]:5701 [dev] [5.4.1-SNAPSHOT] Hazelcast Platform 5.4.1-SNAPSHOT (20240513) starting at [127.0.0.1]:5701
01:22:47,348  INFO |when_processorCalled_then_contextClassLoaderSet| - [system] when_processorCalled_then_contextClassLoaderSet - [127.0.0.1]:5701 [dev] [5.4.1-SNAPSHOT] Cluster name: dev
01:22:47,348  INFO |when_processorCalled_then_contextClassLoaderSet| - [system] when_processorCalled_then_contextClassLoaderSet - [127.0.0.1]:5701 [dev] [5.4.1-SNAPSHOT] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed. For more information, see the documentation for Integrity Checker.
01:22:47,348  INFO |when_processorCalled_then_contextClassLoaderSet| - [system] when_processorCalled_then_contextClassLoaderSet - [127.0.0.1]:5701 [dev] [5.4.1-SNAPSHOT] Jet is enabled
01:22:47,349  INFO |when_processorCalled_then_contextClassLoaderSet| - [MetricsConfigHelper] when_processorCalled_then_contextClassLoaderSet - [127.0.0.1]:5701 [dev] [5.4.1-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
01:22:47,353  WARN |when_processorCalled_then_contextClassLoaderSet| - [CPSubsystem] when_processorCalled_then_contextClassLoaderSet - [127.0.0.1]:5701 [dev] [5.4.1-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
01:22:47,357  INFO |when_processorCalled_then_contextClassLoaderSet| - [JetServiceBackend] when_processorCalled_then_contextClassLoaderSet - [127.0.0.1]:5701 [dev] [5.4.1-SNAPSHOT] Setting number of cooperative threads and default parallelism to 2
01:22:47,358  INFO |when_processorCalled_then_contextClassLoaderSet| - [Diagnostics] when_processorCalled_then_contextClassLoaderSet - [127.0.0.1]:5701 [dev] [5.4.1-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
01:22:47,358  INFO |when_processorCalled_then_contextClassLoaderSet| - [LifecycleService] when_processorCalled_then_contextClassLoaderSet - [127.0.0.1]:5701 [dev] [5.4.1-SNAPSHOT] [127.0.0.1]:5701 is STARTING
01:22:47,358  INFO |when_processorCalled_then_contextClassLoaderSet| - [ClusterService] when_processorCalled_then_contextClassLoaderSet - [127.0.0.1]:5701 [dev] [5.4.1-SNAPSHOT] 

Members {size:1, ver:1} [
	Member [127.0.0.1]:5701 - 741f7e12-f4c4-461c-ad6e-45e8418eae81 this
]

01:22:47,358  INFO |when_processorCalled_then_contextClassLoaderSet| - [JobCoordinationService] when_processorCalled_then_contextClassLoaderSet - [127.0.0.1]:5701 [dev] [5.4.1-SNAPSHOT] Jet started scanning for jobs
01:22:47,358 DEBUG |when_processorCalled_then_contextClassLoaderSet| - [JobCoordinationService] hz.JetClassLoaderTest_recursing_goldstine.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.4.1-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
01:22:47,358  INFO |when_processorCalled_then_contextClassLoaderSet| - [LifecycleService] when_processorCalled_then_contextClassLoaderSet - [127.0.0.1]:5701 [dev] [5.4.1-SNAPSHOT] [127.0.0.1]:5701 is STARTED
01:22:47,360  INFO |when_processorCalled_then_contextClassLoaderSet| - [PartitionStateManager] hz.JetClassLoaderTest_recursing_goldstine.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.4.1-SNAPSHOT] Initializing cluster partition table arrangement...
01:22:47,360 DEBUG |when_processorCalled_then_contextClassLoaderSet| - [JobClassLoaderService] hz.JetClassLoaderTest_recursing_goldstine.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.4.1-SNAPSHOT] Creating job classLoader for job 0bb0-21be-ef80-0001
01:22:47,361 DEBUG |when_processorCalled_then_contextClassLoaderSet| - [JobClassLoaderService] hz.JetClassLoaderTest_recursing_goldstine.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.4.1-SNAPSHOT] Create processor classloader map for job 0bb0-21be-ef80-0001
01:22:47,362  INFO |when_processorCalled_then_contextClassLoaderSet| - [JobCoordinationService] hz.JetClassLoaderTest_recursing_goldstine.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.4.1-SNAPSHOT] Starting job 0bb0-21be-ef80-0001 based on submit request
01:22:47,368  INFO |when_processorCalled_then_contextClassLoaderSet| - [MasterJobContext] hz.JetClassLoaderTest_recursing_goldstine.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.4.1-SNAPSHOT] Didn't find any snapshot to restore for job '0bb0-21be-ef80-0001', execution 0bb0-21be-ef81-0001
01:22:47,368  INFO |when_processorCalled_then_contextClassLoaderSet| - [MasterJobContext] hz.JetClassLoaderTest_recursing_goldstine.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.4.1-SNAPSHOT] Start executing job '0bb0-21be-ef80-0001', execution 0bb0-21be-ef81-0001, execution graph in DOT format:
digraph DAG {
	"v1" [localParallelism=1];
	"v2" [localParallelism=1];
	"v1" -> "v2" [queueSize=1024];
}
HINT: You can use graphviz or http://viz-js.com to visualize the printed graph.
01:22:47,368 DEBUG |when_processorCalled_then_contextClassLoaderSet| - [MasterJobContext] hz.JetClassLoaderTest_recursing_goldstine.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.4.1-SNAPSHOT] Building execution plan for job '0bb0-21be-ef80-0001', execution 0bb0-21be-ef81-0001
01:22:47,368 DEBUG |when_processorCalled_then_contextClassLoaderSet| - [MasterJobContext] hz.JetClassLoaderTest_recursing_goldstine.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.4.1-SNAPSHOT] Built execution plans for job '0bb0-21be-ef80-0001', execution 0bb0-21be-ef81-0001
01:22:47,370 DEBUG |when_processorCalled_then_contextClassLoaderSet| - [InitExecutionOperation] hz.JetClassLoaderTest_recursing_goldstine.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.4.1-SNAPSHOT] Initializing execution plan for job 0bb0-21be-ef80-0001, execution 0bb0-21be-ef81-0001 from [127.0.0.1]:5701
01:22:47,371  INFO |when_processorCalled_then_contextClassLoaderSet| - [JobExecutionService] hz.JetClassLoaderTest_recursing_goldstine.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.4.1-SNAPSHOT] Execution plan for jobId=0bb0-21be-ef80-0001, jobName='0bb0-21be-ef80-0001', executionId=0bb0-21be-ef81-0001 initialized
01:22:47,372 DEBUG |when_processorCalled_then_contextClassLoaderSet| - [MasterJobContext] hz.JetClassLoaderTest_recursing_goldstine.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.4.1-SNAPSHOT] Init of job '0bb0-21be-ef80-0001', execution 0bb0-21be-ef81-0001 was successful
01:22:47,372 DEBUG |when_processorCalled_then_contextClassLoaderSet| - [MasterJobContext] hz.JetClassLoaderTest_recursing_goldstine.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.4.1-SNAPSHOT] Executing job '0bb0-21be-ef80-0001', execution 0bb0-21be-ef81-0001
01:22:47,372  INFO |when_processorCalled_then_contextClassLoaderSet| - [JobExecutionService] hz.JetClassLoaderTest_recursing_goldstine.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.4.1-SNAPSHOT] Start execution of job '0bb0-21be-ef80-0001', execution 0bb0-21be-ef81-0001 from coordinator [127.0.0.1]:5701
01:22:47,374 DEBUG |when_processorCalled_then_contextClassLoaderSet| - [JobCoordinationService] hz.JetClassLoaderTest_recursing_goldstine.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.4.1-SNAPSHOT] job '0bb0-21be-ef80-0001', execution 0bb0-21be-ef81-0001 snapshot is scheduled in 1ms
01:22:47,376 DEBUG |when_processorCalled_then_contextClassLoaderSet| - [AbstractJobProxy] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.1-SNAPSHOT] Sending CANCEL_FORCEFUL request for job 0bb0-21be-ef80-0001 (name ??)
01:22:47,377 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-7 - [127.0.0.1]:5701 [dev] [5.4.1-SNAPSHOT] Completed execution of job '0bb0-21be-ef80-0001', execution 0bb0-21be-ef81-0001
01:22:47,377 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-7 - [127.0.0.1]:5701 [dev] [5.4.1-SNAPSHOT] Execution of job '0bb0-21be-ef80-0001', execution 0bb0-21be-ef81-0001 completed with failure
java.util.concurrent.CompletionException: com.hazelcast.jet.impl.exception.JobTerminateRequestedException: CANCEL_FORCEFUL
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:874) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194) ~[?:?]
	at com.hazelcast.jet.impl.util.NonCompletableFuture.internalCompleteExceptionally(NonCompletableFuture.java:72) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$ExecutionTracker.taskletDone(TaskletExecutionService.java:502) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.dismissTasklet(TaskletExecutionService.java:433) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:419) ~[classes/:?]
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891) ~[?:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.run(TaskletExecutionService.java:373) ~[classes/:?]
	at java.base/java.lang.Thread.run(Thread.java:1595) ~[?:?]
Caused by: com.hazelcast.jet.impl.exception.JobTerminateRequestedException: CANCEL_FORCEFUL
	at com.hazelcast.jet.impl.execution.ExecutionContext.terminateExecution(ExecutionContext.java:318) ~[classes/:?]
	at com.hazelcast.jet.impl.JobExecutionService.terminateExecution0(JobExecutionService.java:726) ~[classes/:?]
	at com.hazelcast.jet.impl.JobExecutionService.terminateExecution(JobExecutionService.java:722) ~[classes/:?]
	at com.hazelcast.jet.impl.operation.TerminateExecutionOperation.doRun(TerminateExecutionOperation.java:59) ~[classes/:?]
	at com.hazelcast.jet.impl.operation.AsyncOperation.run(AsyncOperation.java:55) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:193) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:294) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:265) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:216) ~[classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:459) ~[classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:519) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:618) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:597) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:558) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:241) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:71) ~[classes/:?]
	at com.hazelcast.jet.impl.MasterContext.invokeOnParticipant(MasterContext.java:428) ~[classes/:?]
	at com.hazelcast.jet.impl.MasterContext.invokeOnParticipants(MasterContext.java:411) ~[classes/:?]
	at com.hazelcast.jet.impl.MasterContext.invokeOnParticipants(MasterContext.java:382) ~[classes/:?]
	at com.hazelcast.jet.impl.MasterJobContext.lambda$cancelExecutionInvocations$24(MasterJobContext.java:760) ~[classes/:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1595) ~[?:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76) ~[classes/:?]
	at com.hazelcast.internal.util.executor.PoolExecutorThreadFactory$ManagedThread.executeRun(PoolExecutorThreadFactory.java:74) ~[classes/:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:111) ~[classes/:?]
01:22:47,378 DEBUG || - [MasterJobContext] ForkJoinPool.commonPool-worker-7 - [127.0.0.1]:5701 [dev] [5.4.1-SNAPSHOT] job '0bb0-21be-ef80-0001', execution 0bb0-21be-ef81-0001 received response to StartExecutionOperation from [127.0.0.1]:5701: com.hazelcast.jet.impl.exception.JobTerminateRequestedException: CANCEL_FORCEFUL
01:22:47,378 DEBUG || - [MasterJobContext] ForkJoinPool.commonPool-worker-7 - [127.0.0.1]:5701 [dev] [5.4.1-SNAPSHOT] job '0bb0-21be-ef80-0001', execution 0bb0-21be-ef81-0001 to be cancelled after Execution
01:22:47,378 DEBUG |when_processorCalled_then_contextClassLoaderSet| - [JobClassLoaderService] hz.JetClassLoaderTest_recursing_goldstine.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.4.1-SNAPSHOT] Finish JobClassLoaders phaseCount = 0, removing classloaders for jobId=0bb0-21be-ef80-0001
01:22:47,378  INFO |when_processorCalled_then_contextClassLoaderSet| - [MasterJobContext] hz.JetClassLoaderTest_recursing_goldstine.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.4.1-SNAPSHOT] Execution of job '0bb0-21be-ef80-0001', execution 0bb0-21be-ef81-0001 got terminated, reason=com.hazelcast.jet.impl.exception.CancellationByUserException
	Start time: 2024-05-13T01:22:47.362
	Duration: 00:00:00.016
	To see additional job metrics enable JobConfig.storeMetricsAfterJobCompletion
01:22:47,378 DEBUG |when_processorCalled_then_contextClassLoaderSet| - [MasterSnapshotContext] hz.JetClassLoaderTest_recursing_goldstine.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.4.1-SNAPSHOT] Starting snapshot 0 for job '0bb0-21be-ef80-0001', execution 0bb0-21be-ef81-0001, flags: terminal=no,export=no, writing to: null
01:22:47,379 DEBUG |when_processorCalled_then_contextClassLoaderSet| - [JobCoordinationService] hz.JetClassLoaderTest_recursing_goldstine.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.4.1-SNAPSHOT] job '0bb0-21be-ef80-0001', execution 0bb0-21be-ef81-0001 is completed
01:22:47,380  INFO |when_processorCalled_then_contextClassLoaderSet| - [JetTestSupport] Time-limited test - Terminating instanceFactory in JetTestSupport.@After
01:22:47,381  INFO |when_processorCalled_then_contextClassLoaderSet| - [LifecycleService] Thread-3885 - [127.0.0.1]:5701 [dev] [5.4.1-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
01:22:47,381  WARN |when_processorCalled_then_contextClassLoaderSet| - [Node] Thread-3885 - [127.0.0.1]:5701 [dev] [5.4.1-SNAPSHOT] Terminating forcefully...
01:22:47,381  INFO |when_processorCalled_then_contextClassLoaderSet| - [Node] Thread-3885 - [127.0.0.1]:5701 [dev] [5.4.1-SNAPSHOT] Shutting down connection manager...
01:22:47,381  INFO |when_processorCalled_then_contextClassLoaderSet| - [Node] Thread-3885 - [127.0.0.1]:5701 [dev] [5.4.1-SNAPSHOT] Shutting down node engine...
01:22:47,384  WARN |when_processorCalled_then_contextClassLoaderSet| - [JobCoordinationService] hz.JetClassLoaderTest_recursing_goldstine.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.4.1-SNAPSHOT] null
com.hazelcast.core.HazelcastInstanceNotActiveException: HazelcastInstance[[127.0.0.1]:5701] is not active!
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyRegistry.getService(ProxyRegistry.java:92) ~[classes/:?]
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyRegistry.<init>(ProxyRegistry.java:74) ~[classes/:?]
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyServiceImpl.lambda$new$0(ProxyServiceImpl.java:84) ~[classes/:?]
	at com.hazelcast.internal.util.ConcurrencyUtil.getOrPutIfAbsent(ConcurrencyUtil.java:176) ~[classes/:?]
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyServiceImpl.getOrCreateRegistry(ProxyServiceImpl.java:144) ~[classes/:?]
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyServiceImpl.getDistributedObject(ProxyServiceImpl.java:152) ~[classes/:?]
	at com.hazelcast.instance.impl.HazelcastInstanceImpl.getDistributedObject(HazelcastInstanceImpl.java:365) ~[classes/:?]
	at com.hazelcast.instance.impl.HazelcastInstanceImpl.getMap(HazelcastInstanceImpl.java:184) ~[classes/:?]
	at com.hazelcast.jet.impl.MasterSnapshotContext.lambda$onSnapshotPhase1CompleteWithStartResponses$7(MasterSnapshotContext.java:331) ~[classes/:?]
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$60(JobCoordinationService.java:1481) ~[classes/:?]
	at com.hazelcast.jet.impl.JobCoordinationService.submitToCoordinatorThread(JobCoordinationService.java:1490) ~[classes/:?]
	at com.hazelcast.jet.impl.JobCoordinationService.submitToCoordinatorThread(JobCoordinationService.java:1480) ~[classes/:?]
	at com.hazelcast.jet.impl.MasterSnapshotContext.onSnapshotPhase1CompleteWithStartResponses(MasterSnapshotContext.java:296) ~[classes/:?]
	at com.hazelcast.jet.impl.MasterSnapshotContext.lambda$onSnapshotPhase1Complete$3(MasterSnapshotContext.java:283) ~[classes/:?]
	at com.hazelcast.internal.util.ExceptionUtil.lambda$withTryCatch$1(ExceptionUtil.java:199) ~[classes/:?]
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:887) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2357) ~[?:?]
	at com.hazelcast.jet.impl.MasterSnapshotContext.lambda$onSnapshotPhase1Complete$4(MasterSnapshotContext.java:282) ~[classes/:?]
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$60(JobCoordinationService.java:1481) ~[classes/:?]
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$61(JobCoordinationService.java:1502) ~[classes/:?]
	at com.hazelcast.internal.util.executor.CompletableFutureTask.run(CompletableFutureTask.java:64) [classes/:?]
	at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:220) [classes/:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) [?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) [?:?]
	at java.base/java.lang.Thread.run(Thread.java:1595) [?:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76) [classes/:?]
	at com.hazelcast.internal.util.executor.PoolExecutorThreadFactory$ManagedThread.executeRun(PoolExecutorThreadFactory.java:74) [classes/:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:111) [classes/:?]
01:22:47,386  INFO |when_processorCalled_then_contextClassLoaderSet| - [NodeExtension] Thread-3885 - [127.0.0.1]:5701 [dev] [5.4.1-SNAPSHOT] Destroying node NodeExtension.
01:22:47,386  INFO |when_processorCalled_then_contextClassLoaderSet| - [Node] Thread-3885 - [127.0.0.1]:5701 [dev] [5.4.1-SNAPSHOT] Hazelcast Shutdown is completed in 5 ms.
01:22:47,386  INFO |when_processorCalled_then_contextClassLoaderSet| - [LifecycleService] Thread-3885 - [127.0.0.1]:5701 [dev] [5.4.1-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
01:22:47,386  INFO |when_processorCalled_then_contextClassLoaderSet| - [HazelcastTestSupport] Time-limited test - Shutting down node factory as @After action
BuildInfo right after when_processorCalled_then_contextClassLoaderSet(com.hazelcast.jet.impl.deployment.JetClassLoaderTest): BuildInfo{version='5.4.1-SNAPSHOT', build='20240513', buildNumber=20240513, revision=, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'when_processorCalled_then_contextClassLoaderSet(com.hazelcast.jet.impl.deployment.JetClassLoaderTest):'
01:22:45, accumulated pauses: 18 ms, max pause: 2 ms, pauses over 1000 ms: 0


No metrics recorded during the test

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-5.maintenance-Openj9-21/2/

**Comment by Fly-Style** [comment]
Fixed by https://github.com/hazelcast/hazelcast-mono/pull/2522
