### ISSUE TITLE
com.hazelcast.client.listeners.QueueItemListenerOnReconnectTest.testListenersTerminateCluster_when_multipleServer

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#26348]
_master_ (commit 7e05f917b904fb4daa34319ca0c4d382cda5b323)

Failed on openjdk-17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZuluJDK17/139/testReport/com.hazelcast.client.listeners/QueueItemListenerOnReconnectTest/testListenersTerminateCluster_when_multipleServer_2__routingMode_SUBSET_/

Failed in variant `[2: routingMode=SUBSET]`.

<details><summary>Stacktrace:</summary>

```
com.hazelcast.client.HazelcastClientNotActiveException: Client is not active.
	at com.hazelcast.client.impl.clientside.HazelcastClientProxy.getClient(HazelcastClientProxy.java:304)
	at com.hazelcast.client.impl.clientside.HazelcastClientProxy.getCluster(HazelcastClientProxy.java:150)
	at com.hazelcast.test.HazelcastTestSupport.getClusterSize(HazelcastTestSupport.java:1053)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSize(HazelcastTestSupport.java:1044)
	at com.hazelcast.test.HazelcastTestSupport.lambda$assertClusterSizeEventually$11(HazelcastTestSupport.java:1080)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1214)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1233)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:1080)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:1058)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest.testListenersTerminateCluster(AbstractListenersOnReconnectTest.java:289)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest.testListenersTerminateCluster_when_multipleServer(AbstractListenersOnReconnectTest.java:251)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:840)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-ZuluJDK17/139/

**Comment by olukas** [comment]
Failed again on _master_ with Windows - OracleJDK21: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Windows-OracleJDK21/5/testReport/com.hazelcast.client/TcpClientConnectionTest/testAddingConnectionListenerTwice_shouldCauseEventDeliveredTwice_2__routingMode_SUBSET_/

**Comment by nishaatr** [comment]
Changed Milestone to 6.0.0 to ensure 5.5.0 does not report any Open [issues ](https://github.com/issues?page=1&q=is%3Aopen+milestone%3A5.5.0+repo%3Ahazelcast%2Fhazelcast+repo%3Ahazelcast%2Fhazelcast-enterprise+repo%3Ahazelcast%2Fhazelcast-mono+sort%3Acreated-desc)
Please correct as necessary
