### ISSUE TITLE
com.hazelcast.mapstore.mariadb.MariaDBGenericMapStoreIT.testRemoveWhenNotExists

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#26345]
_master_ (commit cf4fdf16f962371a4a5b03a89e5995295c6c98d8)

Failed on ZingJDK21: https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK21-nightly/21/consoleFull _(junit test results were not stored due to OOM thrown from JUnit test result report plugin)_

<details><summary>Stacktrace:</summary>

```
[ERROR] com.hazelcast.mapstore.mariadb.MariaDBGenericMapStoreIT.testRemoveWhenNotExists -- Time elapsed: 0.178 s <<< ERROR!
com.hazelcast.core.HazelcastException: MapStore init failed for map: maria_testremovewhennotexists
	at com.hazelcast.mapstore.GenericMapLoader.awaitSuccessfulInit(GenericMapLoader.java:398)
	at com.hazelcast.mapstore.GenericMapLoader.loadAllKeys(GenericMapLoader.java:378)
	at com.hazelcast.map.impl.MapStoreWrapper.lambda$loadAllKeys$6(MapStoreWrapper.java:168)
	at com.hazelcast.internal.namespace.NamespaceUtil.callWithClassLoader(NamespaceUtil.java:200)
	at com.hazelcast.internal.namespace.NamespaceUtil.callWithOwnClassLoader(NamespaceUtil.java:152)
	at com.hazelcast.map.impl.MapStoreWrapper.loadAllKeys(MapStoreWrapper.java:168)
	at com.hazelcast.map.impl.mapstore.BasicMapStoreContext.loadAllKeys(BasicMapStoreContext.java:174)
	at com.hazelcast.map.impl.MapKeyLoader.sendKeysInBatches(MapKeyLoader.java:441)
	at com.hazelcast.map.impl.MapKeyLoader.lambda$sendKeys$0(MapKeyLoader.java:265)
	at com.hazelcast.internal.util.executor.CompletableFutureTask.run(CompletableFutureTask.java:64)
	at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:220)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.lang.Thread.run(Thread.java:1584)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.internal.util.executor.PoolExecutorThreadFactory$ManagedThread.executeRun(PoolExecutorThreadFactory.java:74)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:111)
	at ------ submitted from ------.()
	at com.hazelcast.internal.util.ExceptionUtil.cloneExceptionWithFixedAsyncStackTrace(ExceptionUtil.java:348)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.returnOrThrowWithGetConventions(InvocationFuture.java:112)
	at com.hazelcast.client.impl.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:95)
	at com.hazelcast.client.impl.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:40)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:618)
	at com.hazelcast.client.impl.spi.ClientProxy.invokeOnPartition(ClientProxy.java:189)
	at com.hazelcast.client.impl.spi.ClientProxy.invoke(ClientProxy.java:183)
	at com.hazelcast.client.impl.proxy.ClientMapProxy.removeInternal(ClientMapProxy.java:300)
	at com.hazelcast.client.impl.proxy.ClientMapProxy.remove(ClientMapProxy.java:294)
	at com.hazelcast.mapstore.GenericMapStoreIT.testRemoveWhenNotExists(GenericMapStoreIT.java:290)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.lang.Thread.run(Thread.java:1584)
Caused by: com.hazelcast.sql.HazelcastSqlException: Resurrected a dead object
	at com.hazelcast.sql.impl.CoreQueryUtils.toPublicException(CoreQueryUtils.java:61)
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:242)
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:191)
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:185)
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:179)
	at com.hazelcast.sql.SqlService.execute(SqlService.java:89)
	at com.hazelcast.mapstore.MappingHelper.createMapping(MappingHelper.java:49)
	at com.hazelcast.mapstore.GenericMapLoader.createOrReadMapping(GenericMapLoader.java:223)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at com.hazelcast.internal.util.executor.CompletableFutureTask.run(CompletableFutureTask.java:64)
	at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:220)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.lang.Thread.run(Thread.java:1584)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.internal.util.executor.PoolExecutorThreadFactory$ManagedThread.executeRun(PoolExecutorThreadFactory.java:74)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:111)
Caused by: java.lang.IllegalStateException: Resurrected a dead object
	at com.hazelcast.dataconnection.impl.ReferenceCounter.lambda$retain$0(ReferenceCounter.java:54)
	at java.util.concurrent.atomic.AtomicInteger.updateAndGet(AtomicInteger.java:281)
	at com.hazelcast.dataconnection.impl.ReferenceCounter.retain(ReferenceCounter.java:52)
	at com.hazelcast.dataconnection.DataConnectionBase.retain(DataConnectionBase.java:48)
	at com.hazelcast.dataconnection.impl.DataConnectionServiceImpl.lambda$getAndRetainDataConnection$3(DataConnectionServiceImpl.java:211)
	at java.util.concurrent.ConcurrentHashMap.computeIfPresent(ConcurrentHashMap.java:1828)
	at com.hazelcast.dataconnection.impl.DataConnectionServiceImpl.getAndRetainDataConnection(DataConnectionServiceImpl.java:207)
	at com.hazelcast.jet.sql.impl.connector.jdbc.JdbcSqlConnector.resolveAndValidateFields(JdbcSqlConnector.java:104)
	at com.hazelcast.jet.sql.impl.schema.TableResolverImpl.resolveMapping(TableResolverImpl.java:177)
	at com.hazelcast.jet.sql.impl.schema.TableResolverImpl.createMapping(TableResolverImpl.java:134)
	at com.hazelcast.jet.sql.impl.PlanExecutor.execute(PlanExecutor.java:177)
	at com.hazelcast.jet.sql.impl.SqlPlanImpl$CreateMappingPlan.execute(SqlPlanImpl.java:156)
	at com.hazelcast.sql.impl.SqlServiceImpl.query0(SqlServiceImpl.java:287)
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:225)
	... 15 more
```

</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-ZingJDK21-nightly/21/Hazelcast-master-ZingJDK21-nightly-21.zip

**Comment by nishaatr** [comment]
Changed Milestone to 6.0.0 to ensure 5.5.0 does not report any Open [issues ](https://github.com/issues?page=1&q=is%3Aopen+milestone%3A5.5.0+repo%3Ahazelcast%2Fhazelcast+repo%3Ahazelcast%2Fhazelcast-enterprise+repo%3Ahazelcast%2Fhazelcast-mono+sort%3Acreated-desc)
Please correct as necessary

**Comment by Patras3** [comment]
This comment was automatically generated to summarize test results for the last 30 days.

```

For branch: master
Builds between : 2024-07-12 03:14 - 2024-07-31 03:15
Jobs: 9, Runs: 17, Passed: 17, Failed: 0, Skipped: 0, Fail Ratio: 0.00%
Run on:
+--------------------------------------------------+
| JDK        | PASSED | FAILED | SKIPPED |  RATIO  |
+--------------------------------------------------+
| oracle-17  |   3    |   0    |    0    |   0.00% |
| unknown    |   3    |   0    |    0    |   0.00% |
| zing-21    |   2    |   0    |    0    |   0.00% |
| openj9-21  |   2    |   0    |    0    |   0.00% |
| oracle-21  |   2    |   0    |    0    |   0.00% |
| zing-17    |   2    |   0    |    0    |   0.00% |
| openjdk-17 |   3    |   0    |    0    |   0.00% |
+--------------------------------------------------+

Builds Timeline:
2024-07-31 03:15 - PASSED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK17-nightly-Esxi7/99/testReport/com.hazelcast.mapstore.mariadb/MariaDBGenericMapStoreIT/testRemoveWhenNotExists/
2024-07-31 03:08 - PASSED (oracle-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-OracleJDK21-nightly/28/testReport/com.hazelcast.mapstore.mariadb/MariaDBGenericMapStoreIT/testRemoveWhenNotExists/
2024-07-29 03:12 - PASSED (openj9-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-Openj9-21-nightly/29/testReport/com.hazelcast.mapstore.mariadb/MariaDBGenericMapStoreIT/testRemoveWhenNotExists/
2024-07-28 18:11 - PASSED (zing-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK21-nightly/32/testReport/com.hazelcast.mapstore.mariadb/MariaDBGenericMapStoreIT/testRemoveWhenNotExists/
2024-07-28 12:12 - PASSED (oracle-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-nightly-force-offload/111/testReport/com.hazelcast.mapstore.mariadb/MariaDBGenericMapStoreIT/testRemoveWhenNotExists/
2024-07-27 00:07 - PASSED (oracle-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-nightly-little-endian/89/testReport/com.hazelcast.mapstore.mariadb/MariaDBGenericMapStoreIT/testRemoveWhenNotExists/
2024-07-26 18:06 - PASSED (zing-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK17-nightly/91/testReport/com.hazelcast.mapstore.mariadb/MariaDBGenericMapStoreIT/testRemoveWhenNotExists/
2024-07-26 03:14 - PASSED (openjdk-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-ZuluJDK17-nightly/128/testReport/com.hazelcast.mapstore.mariadb/MariaDBGenericMapStoreIT/testRemoveWhenNotExists/
2024-07-24 21:52 - PASSED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-CorrettoJDK17-arm64-nightly/26/testReport/com.hazelcast.mapstore.mariadb/MariaDBGenericMapStoreIT/testRemoveWhenNotExists/
2024-07-24 03:15 - PASSED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK17-nightly-Esxi7/98/testReport/com.hazelcast.mapstore.mariadb/MariaDBGenericMapStoreIT/testRemoveWhenNotExists/
2024-07-24 03:08 - PASSED (oracle-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-OracleJDK21-nightly/27/testReport/com.hazelcast.mapstore.mariadb/MariaDBGenericMapStoreIT/testRemoveWhenNotExists/
2024-07-22 03:12 - PASSED (openj9-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-Openj9-21-nightly/28/testReport/com.hazelcast.mapstore.mariadb/MariaDBGenericMapStoreIT/testRemoveWhenNotExists/
2024-07-21 18:11 - PASSED (zing-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK21-nightly/31/testReport/com.hazelcast.mapstore.mariadb/MariaDBGenericMapStoreIT/testRemoveWhenNotExists/
2024-07-20 00:07 - PASSED (oracle-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-nightly-little-endian/88/testReport/com.hazelcast.mapstore.mariadb/MariaDBGenericMapStoreIT/testRemoveWhenNotExists/
2024-07-19 18:06 - PASSED (zing-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK17-nightly/90/testReport/com.hazelcast.mapstore.mariadb/MariaDBGenericMapStoreIT/testRemoveWhenNotExists/
2024-07-19 03:14 - PASSED (openjdk-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-ZuluJDK17-nightly/127/testReport/com.hazelcast.mapstore.mariadb/MariaDBGenericMapStoreIT/testRemoveWhenNotExists/
2024-07-12 03:14 - PASSED (openjdk-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-ZuluJDK17-nightly/126/testReport/com.hazelcast.mapstore.mariadb/MariaDBGenericMapStoreIT/testRemoveWhenNotExists/

----------------------------------------

For branch: 5.5.z
Builds between : 2024-07-31 18:08 - 2024-07-31 18:08
Jobs: 1, Runs: 1, Passed: 1, Failed: 0, Skipped: 0, Fail Ratio: 0.00%
Run on:
+--------------------------------------------------+
| JDK        | PASSED | FAILED | SKIPPED |  RATIO  |
+--------------------------------------------------+
| openjdk-17 |   1    |   0    |    0    |   0.00% |
+--------------------------------------------------+

Builds Timeline:
2024-07-31 18:08 - PASSED (openjdk-17):
    https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-ZuluJDK17-nightly/128/testReport/com.hazelcast.mapstore.mariadb/MariaDBGenericMapStoreIT/testRemoveWhenNotExists/

----------------------------------------

For branch: 5.4.z
Builds between : 2024-07-03 18:08 - 2024-07-29 18:02
Jobs: 3, Runs: 12, Passed: 12, Failed: 0, Skipped: 0, Fail Ratio: 0.00%
Run on:
+--------------------------------------------------+
| JDK        | PASSED | FAILED | SKIPPED |  RATIO  |
+--------------------------------------------------+
| openjdk-17 |   4    |   0    |    0    |   0.00% |
| oracle-21  |   4    |   0    |    0    |   0.00% |
| openj9-21  |   4    |   0    |    0    |   0.00% |
+--------------------------------------------------+

Builds Timeline:
2024-07-29 18:02 - PASSED (oracle-21):
    https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-OracleJDK21-nightly/14/testReport/com.hazelcast.mapstore.mariadb/MariaDBGenericMapStoreIT/testRemoveWhenNotExists/
2024-07-27 18:06 - PASSED (openj9-21):
    https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-Openj9-21-nightly/13/testReport/com.hazelcast.mapstore.mariadb/MariaDBGenericMapStoreIT/testRemoveWhenNotExists/
2024-07-24 18:08 - PASSED (openjdk-17):
    https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-ZuluJDK17-nightly/127/testReport/com.hazelcast.mapstore.mariadb/MariaDBGenericMapStoreIT/testRemoveWhenNotExists/
2024-07-22 18:02 - PASSED (oracle-21):
    https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-OracleJDK21-nightly/13/testReport/com.hazelcast.mapstore.mariadb/MariaDBGenericMapStoreIT/testRemoveWhenNotExists/
2024-07-20 18:06 - PASSED (openj9-21):
    https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-Openj9-21-nightly/12/testReport/com.hazelcast.mapstore.mariadb/MariaDBGenericMapStoreIT/testRemoveWhenNotExists/
2024-07-17 18:08 - PASSED (openjdk-17):
    https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-ZuluJDK17-nightly/126/testReport/com.hazelcast.mapstore.mariadb/MariaDBGenericMapStoreIT/testRemoveWhenNotExists/
2024-07-15 18:02 - PASSED (oracle-21):
    https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-OracleJDK21-nightly/12/testReport/com.hazelcast.mapstore.mariadb/MariaDBGenericMapStoreIT/testRemoveWhenNotExists/
2024-07-13 18:06 - PASSED (openj9-21):
    https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-Openj9-21-nightly/11/testReport/com.hazelcast.mapstore.mariadb/MariaDBGenericMapStoreIT/testRemoveWhenNotExists/
2024-07-10 18:08 - PASSED (openjdk-17):
    https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-ZuluJDK17-nightly/125/testReport/com.hazelcast.mapstore.mariadb/MariaDBGenericMapStoreIT/testRemoveWhenNotExists/
2024-07-08 18:02 - PASSED (oracle-21):
    https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-OracleJDK21-nightly/11/testReport/com.hazelcast.mapstore.mariadb/MariaDBGenericMapStoreIT/testRemoveWhenNotExists/
2024-07-06 18:06 - PASSED (openj9-21):
    https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-Openj9-21-nightly/10/testReport/com.hazelcast.mapstore.mariadb/MariaDBGenericMapStoreIT/testRemoveWhenNotExists/
2024-07-03 18:08 - PASSED (openjdk-17):
    https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-ZuluJDK17-nightly/124/testReport/com.hazelcast.mapstore.mariadb/MariaDBGenericMapStoreIT/testRemoveWhenNotExists/

----------------------------------------
```
