### ISSUE TITLE
com.hazelcast.jet.sql_slow.SqlSlowIndexResolutionTest and com.hazelcast.jet.sql.impl.SqlImposeOrderFunctionTest

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#26347]
_5.4.z_ (commit d4d0430639d44fadbfb65c3edd78a982bbc737b5)

Failed on openj9-21: 
- https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-Openj9-21-nightly/4/testReport/com.hazelcast.jet.sql_slow/SqlSlowIndexResolutionTest/
- https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-Openj9-21-nightly/4/testReport/com.hazelcast.jet.sql.impl/SqlImposeOrderFunctionTest/
<details><summary>Stacktrace:</summary>

```
java.lang.NullPointerException: Cannot invoke "java.lang.Object.toString()" because "value" is null
	at java.base/java.lang.StringConcatHelper.stringOf(StringConcatHelper.java:467)
	at com.hazelcast.jet.SimpleTestInClusterSupport.lambda$supportAfter$6(SimpleTestInClusterSupport.java:173)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1249)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:522)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:512)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:239)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at com.hazelcast.jet.SimpleTestInClusterSupport.supportAfter(SimpleTestInClusterSupport.java:174)
	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
	at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:381)
	at com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37)
	at com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:104)
	at com.hazelcast.test.metrics.MetricsRule$1.evaluate(MetricsRule.java:63)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:53)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:32)
	at com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:41)
	at com.hazelcast.test.OverridePropertyRule$1.evaluate(OverridePropertyRule.java:68)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.lang.Thread.run(Thread.java:1595)

```
</details>

<details><summary>Standard output:</summary>

```
22:16:49,374  INFO || - [MetricsConfigHelper] Time-limited test - [LOCAL] [dev] [5.4.1-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
22:16:49,375  INFO || - [logo] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.1-SNAPSHOT] 
	o    o     o     o---o   o--o o      o---o     o     o----o o--o--o
	|    |    / \       /         |     /         / \    |         |   
	o----o       o     o   o----o |    o             o   o----o    |   
	|    |  *     \   /           |     \       *     \       |    |   
	o    o *       o o---o   o--o o----o o---o *       o o----o    o   
22:16:49,375  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.1-SNAPSHOT] Copyright (c) 2008-2024, Hazelcast, Inc. All Rights Reserved.
22:16:49,375  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.1-SNAPSHOT] Hazelcast Platform 5.4.1-SNAPSHOT (20240525) starting at [127.0.0.1]:5701
22:16:49,375  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.1-SNAPSHOT] Cluster name: dev
22:16:49,375  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.1-SNAPSHOT] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed. For more information, see the documentation for Integrity Checker.
22:16:49,375  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.1-SNAPSHOT] Jet is enabled
22:16:49,379  INFO || - [MetricsConfigHelper] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.1-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
22:16:49,386  WARN || - [CPSubsystem] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.1-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
22:16:49,390  INFO || - [JetServiceBackend] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.1-SNAPSHOT] Setting number of cooperative threads and default parallelism to 2
22:16:49,391  INFO || - [Diagnostics] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.1-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
22:16:49,391  INFO || - [LifecycleService] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.1-SNAPSHOT] [127.0.0.1]:5701 is STARTING
22:16:49,391  INFO || - [ClusterService] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.1-SNAPSHOT] 

Members {size:1, ver:1} [
	Member [127.0.0.1]:5701 - 5664ff5e-b304-4f99-9578-c47e41218dd6 this
]

22:16:49,391  INFO || - [JobCoordinationService] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.1-SNAPSHOT] Jet started scanning for jobs
22:16:49,391  INFO || - [LifecycleService] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.1-SNAPSHOT] [127.0.0.1]:5701 is STARTED
22:16:49,392  INFO || - [MetricsConfigHelper] Time-limited test - [LOCAL] [dev] [5.4.1-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
22:16:49,393  INFO || - [logo] Time-limited test - [127.0.0.1]:5702 [dev] [5.4.1-SNAPSHOT] 
	o    o     o     o---o   o--o o      o---o     o     o----o o--o--o
	|    |    / \       /         |     /         / \    |         |   
	o----o       o     o   o----o |    o             o   o----o    |   
	|    |  *     \   /           |     \       *     \       |    |   
	o    o *       o o---o   o--o o----o o---o *       o o----o    o   
22:16:49,393  INFO || - [system] Time-limited test - [127.0.0.1]:5702 [dev] [5.4.1-SNAPSHOT] Copyright (c) 2008-2024, Hazelcast, Inc. All Rights Reserved.
22:16:49,393  INFO || - [system] Time-limited test - [127.0.0.1]:5702 [dev] [5.4.1-SNAPSHOT] Hazelcast Platform 5.4.1-SNAPSHOT (20240525) starting at [127.0.0.1]:5702
22:16:49,393  INFO || - [system] Time-limited test - [127.0.0.1]:5702 [dev] [5.4.1-SNAPSHOT] Cluster name: dev
22:16:49,393  INFO || - [system] Time-limited test - [127.0.0.1]:5702 [dev] [5.4.1-SNAPSHOT] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed. For more information, see the documentation for Integrity Checker.
22:16:49,393  INFO || - [system] Time-limited test - [127.0.0.1]:5702 [dev] [5.4.1-SNAPSHOT] Jet is enabled
22:16:49,396  INFO || - [MetricsConfigHelper] Time-limited test - [127.0.0.1]:5702 [dev] [5.4.1-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
22:16:49,398 DEBUG || - [JobCoordinationService] hz.SqlSlowIndexResolutionTest_cranky_driscoll.cached.thread-6 - [127.0.0.1]:5701 [dev] [5.4.1-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
22:16:49,400  WARN || - [CPSubsystem] Time-limited test - [127.0.0.1]:5702 [dev] [5.4.1-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
22:16:49,405  INFO || - [JetServiceBackend] Time-limited test - [127.0.0.1]:5702 [dev] [5.4.1-SNAPSHOT] Setting number of cooperative threads and default parallelism to 2
22:16:49,406  INFO || - [Diagnostics] Time-limited test - [127.0.0.1]:5702 [dev] [5.4.1-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
22:16:49,406  INFO || - [LifecycleService] Time-limited test - [127.0.0.1]:5702 [dev] [5.4.1-SNAPSHOT] [127.0.0.1]:5702 is STARTING
22:16:49,406  INFO || - [MockServer] Time-limited test - [127.0.0.1]:5702 [dev] [5.4.1-SNAPSHOT] Created connection to endpoint: [127.0.0.1]:5701-5664ff5e-b304-4f99-9578-c47e41218dd6, connection: MockConnection{localEndpoint=[address=[127.0.0.1]:5702, uuid=fb9e92ac-1d79-48fb-bfa7-b9a086c21dbf], remoteEndpoint=[address=[127.0.0.1]:5701, uuid=5664ff5e-b304-4f99-9578-c47e41218dd6], alive=true}
22:16:49,407  INFO || - [MockServer] hz.SqlSlowIndexResolutionTest_cranky_driscoll.priority-generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [5.4.1-SNAPSHOT] Created connection to endpoint: [127.0.0.1]:5702-fb9e92ac-1d79-48fb-bfa7-b9a086c21dbf, connection: MockConnection{localEndpoint=[address=[127.0.0.1]:5701, uuid=5664ff5e-b304-4f99-9578-c47e41218dd6], remoteEndpoint=[address=[127.0.0.1]:5702, uuid=fb9e92ac-1d79-48fb-bfa7-b9a086c21dbf], alive=true}
22:16:49,407  INFO || - [ClusterService] hz.SqlSlowIndexResolutionTest_cranky_driscoll.priority-generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [5.4.1-SNAPSHOT] 

Members {size:2, ver:2} [
	Member [127.0.0.1]:5701 - 5664ff5e-b304-4f99-9578-c47e41218dd6 this
	Member [127.0.0.1]:5702 - fb9e92ac-1d79-48fb-bfa7-b9a086c21dbf
]

22:16:49,499 DEBUG || - [JobCoordinationService] hz.SqlSlowIndexResolutionTest_cranky_driscoll.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.4.1-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
22:16:49,508  INFO || - [ClusterService] hz.SqlSlowIndexResolutionTest_agitated_driscoll.generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.4.1-SNAPSHOT] 

Members {size:2, ver:2} [
	Member [127.0.0.1]:5701 - 5664ff5e-b304-4f99-9578-c47e41218dd6
	Member [127.0.0.1]:5702 - fb9e92ac-1d79-48fb-bfa7-b9a086c21dbf this
]

22:16:49,509  INFO || - [JobCoordinationService] Time-limited test - [127.0.0.1]:5702 [dev] [5.4.1-SNAPSHOT] Jet started scanning for jobs
22:16:49,510  INFO || - [LifecycleService] Time-limited test - [127.0.0.1]:5702 [dev] [5.4.1-SNAPSHOT] [127.0.0.1]:5702 is STARTED
22:16:49,511  INFO || - [MetricsConfigHelper] Time-limited test - [LOCAL] [dev] [5.4.1-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
22:16:49,512  INFO || - [logo] Time-limited test - [127.0.0.1]:5703 [dev] [5.4.1-SNAPSHOT] 
	o    o     o     o---o   o--o o      o---o     o     o----o o--o--o
	|    |    / \       /         |     /         / \    |         |   
	o----o       o     o   o----o |    o             o   o----o    |   
	|    |  *     \   /           |     \       *     \       |    |   
	o    o *       o o---o   o--o o----o o---o *       o o----o    o   
22:16:49,512  INFO || - [system] Time-limited test - [127.0.0.1]:5703 [dev] [5.4.1-SNAPSHOT] Copyright (c) 2008-2024, Hazelcast, Inc. All Rights Reserved.
22:16:49,512  INFO || - [system] Time-limited test - [127.0.0.1]:5703 [dev] [5.4.1-SNAPSHOT] Hazelcast Platform 5.4.1-SNAPSHOT (20240525) starting at [127.0.0.1]:5703
22:16:49,512  INFO || - [system] Time-limited test - [127.0.0.1]:5703 [dev] [5.4.1-SNAPSHOT] Cluster name: dev
22:16:49,512  INFO || - [system] Time-limited test - [127.0.0.1]:5703 [dev] [5.4.1-SNAPSHOT] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed. For more information, see the documentation for Integrity Checker.
22:16:49,512  INFO || - [system] Time-limited test - [127.0.0.1]:5703 [dev] [5.4.1-SNAPSHOT] Jet is enabled
22:16:49,516  INFO || - [MetricsConfigHelper] Time-limited test - [127.0.0.1]:5703 [dev] [5.4.1-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
22:16:49,531  WARN || - [CPSubsystem] Time-limited test - [127.0.0.1]:5703 [dev] [5.4.1-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
22:16:49,538  INFO || - [JetServiceBackend] Time-limited test - [127.0.0.1]:5703 [dev] [5.4.1-SNAPSHOT] Setting number of cooperative threads and default parallelism to 2
22:16:49,540  INFO || - [Diagnostics] Time-limited test - [127.0.0.1]:5703 [dev] [5.4.1-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
22:16:49,540  INFO || - [LifecycleService] Time-limited test - [127.0.0.1]:5703 [dev] [5.4.1-SNAPSHOT] [127.0.0.1]:5703 is STARTING
22:16:49,543  INFO || - [MockServer] Time-limited test - [127.0.0.1]:5703 [dev] [5.4.1-SNAPSHOT] Created connection to endpoint: [127.0.0.1]:5701-5664ff5e-b304-4f99-9578-c47e41218dd6, connection: MockConnection{localEndpoint=[address=[127.0.0.1]:5703, uuid=62194650-e102-46d5-9588-03c5fd2f0553], remoteEndpoint=[address=[127.0.0.1]:5701, uuid=5664ff5e-b304-4f99-9578-c47e41218dd6], alive=true}
22:16:49,544  INFO || - [MockServer] hz.SqlSlowIndexResolutionTest_cranky_driscoll.generic-operation.thread-1 - [127.0.0.1]:5701 [dev] [5.4.1-SNAPSHOT] Created connection to endpoint: [127.0.0.1]:5703-62194650-e102-46d5-9588-03c5fd2f0553, connection: MockConnection{localEndpoint=[address=[127.0.0.1]:5701, uuid=5664ff5e-b304-4f99-9578-c47e41218dd6], remoteEndpoint=[address=[127.0.0.1]:5703, uuid=62194650-e102-46d5-9588-03c5fd2f0553], alive=true}
22:16:49,545  INFO || - [ClusterService] hz.SqlSlowIndexResolutionTest_cranky_driscoll.generic-operation.thread-1 - [127.0.0.1]:5701 [dev] [5.4.1-SNAPSHOT] 

Members {size:3, ver:3} [
	Member [127.0.0.1]:5701 - 5664ff5e-b304-4f99-9578-c47e41218dd6 this
	Member [127.0.0.1]:5702 - fb9e92ac-1d79-48fb-bfa7-b9a086c21dbf
	Member [127.0.0.1]:5703 - 62194650-e102-46d5-9588-03c5fd2f0553
]

22:16:49,546  INFO || - [MockServer] hz.SqlSlowIndexResolutionTest_agitated_driscoll.priority-generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.4.1-SNAPSHOT] Created connection to endpoint: [127.0.0.1]:5703-62194650-e102-46d5-9588-03c5fd2f0553, connection: MockConnection{localEndpoint=[address=[127.0.0.1]:5702, uuid=fb9e92ac-1d79-48fb-bfa7-b9a086c21dbf], remoteEndpoint=[address=[127.0.0.1]:5703, uuid=62194650-e102-46d5-9588-03c5fd2f0553], alive=true}
22:16:49,546  INFO || - [ClusterService] hz.SqlSlowIndexResolutionTest_agitated_driscoll.priority-generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.4.1-SNAPSHOT] 

Members {size:3, ver:3} [
	Member [127.0.0.1]:5701 - 5664ff5e-b304-4f99-9578-c47e41218dd6
	Member [127.0.0.1]:5702 - fb9e92ac-1d79-48fb-bfa7-b9a086c21dbf this
	Member [127.0.0.1]:5703 - 62194650-e102-46d5-9588-03c5fd2f0553
]

22:16:49,599 DEBUG || - [JobCoordinationService] hz.SqlSlowIndexResolutionTest_cranky_driscoll.cached.thread-1 - [127.0.0.1]:5701 [dev] [5.4.1-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
22:16:49,657  INFO || - [ClusterService] hz.SqlSlowIndexResolutionTest_stoic_driscoll.generic-operation.thread-1 - [127.0.0.1]:5703 [dev] [5.4.1-SNAPSHOT] 

Members {size:3, ver:3} [
	Member [127.0.0.1]:5701 - 5664ff5e-b304-4f99-9578-c47e41218dd6
	Member [127.0.0.1]:5702 - fb9e92ac-1d79-48fb-bfa7-b9a086c21dbf
	Member [127.0.0.1]:5703 - 62194650-e102-46d5-9588-03c5fd2f0553 this
]

22:16:49,658  INFO || - [MockServer] Time-limited test - [127.0.0.1]:5703 [dev] [5.4.1-SNAPSHOT] Created connection to endpoint: [127.0.0.1]:5702-fb9e92ac-1d79-48fb-bfa7-b9a086c21dbf, connection: MockConnection{localEndpoint=[address=[127.0.0.1]:5703, uuid=62194650-e102-46d5-9588-03c5fd2f0553], remoteEndpoint=[address=[127.0.0.1]:5702, uuid=fb9e92ac-1d79-48fb-bfa7-b9a086c21dbf], alive=true}
22:16:49,658  INFO || - [JobCoordinationService] Time-limited test - [127.0.0.1]:5703 [dev] [5.4.1-SNAPSHOT] Jet started scanning for jobs
22:16:49,659  INFO || - [LifecycleService] Time-limited test - [127.0.0.1]:5703 [dev] [5.4.1-SNAPSHOT] [127.0.0.1]:5703 is STARTED
Started Running Test: testIndexResolution[indexType:SORTED, composite:true, type1:Boolean, type2:Boolean]
22:16:49,668  INFO |testIndexResolution[indexType:SORTED, composite:true, type1:Boolean, type2:Boolean]| - [PartitionStateManager] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.1-SNAPSHOT] Initializing cluster partition table arrangement...
22:16:49,714 DEBUG || - [JobRepository] hz.SqlSlowIndexResolutionTest_cranky_driscoll.cached.thread-1 - [127.0.0.1]:5701 [dev] [5.4.1-SNAPSHOT] Skipping job cleanup because job records IMap does not exist
22:16:49,921  INFO |testIndexResolution[indexType:SORTED, composite:true, type1:Boolean, type2:Boolean]| - [SqlTestSupport] Time-limited test - Removing 0 cached plans in SqlTestSupport.@After
22:16:49,922  INFO |testIndexResolution[indexType:SORTED, composite:true, type1:Boolean, type2:Boolean]| - [SqlTestSupport] Time-limited test - Removing 0 cached plans in SqlTestSupport.@After
22:16:49,922  INFO |testIndexResolution[indexType:SORTED, composite:true, type1:Boolean, type2:Boolean]| - [SqlTestSupport] Time-limited test - Removing 0 cached plans in SqlTestSupport.@After
22:16:49,923  INFO |testIndexResolution[indexType:SORTED, composite:true, type1:Boolean, type2:Boolean]| - [SimpleTestInClusterSupport] Time-limited test - Ditching 0 jobs in SimpleTestInClusterSupport.@After: []
22:16:49,923  INFO |testIndexResolution[indexType:SORTED, composite:true, type1:Boolean, type2:Boolean]| - [HazelcastTestSupport] Time-limited test - Shutting down node factory as @After action
BuildInfo right after testIndexResolution[indexType:SORTED, composite:true, type1:Boolean, type2:Boolean](com.hazelcast.jet.sql_slow.SqlSlowIndexResolutionTest): BuildInfo{version='5.4.1-SNAPSHOT', build='20240525', buildNumber=20240525, revision=, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'testIndexResolution[indexType:SORTED, composite:true, type1:Boolean, type2:Boolean](com.hazelcast.jet.sql_slow.SqlSlowIndexResolutionTest):'
22:16:45, accumulated pauses: 620 ms, max pause: 247 ms, pauses over 1000 ms: 0


No metrics recorded during the test

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-5.maintenance-Openj9-21-nightly/4/

**Comment by Patras3** [comment]
Failed again on _5.4.z_ with openj9-21: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-Openj9-21-nightly/8/testReport/com.hazelcast.jet.sql.impl/SqlImposeOrderFunctionTest/
