### ISSUE TITLE
Caused by: java.lang.ClassCastException: class com.TestClass cannot be cast to class com.TestClass  (com.TestClass  is in unnamed module of loader 'app'; comTestClass  is in unnamed module of loader org.springframework.boot.devtools.restart.classloader.RestartClassLoader

### ISSUE THREAD

**Issue by MCMicS** [hazelcast/hazelcast#26361]
**Describe the bug**
I upgraded from Spring Boot 2 to Spring Boot 3 with new Hazelcast version and now I got a ClassCastException Error for use a `MapProxyImpl` if retreive the object again.
I know it's because the two classpath from Spring app and the devtools.
Maybe it's an configuration issue on my side

**Expected behavior**

**To Reproduce**

1. use Hazlecast Map
2. serialize object into map
3. later in other thread deserialze it and read from `IMap` and you will have an ClassCastException

**Additional context**
- Only happens if `spring-boot-devtools` is also in classpath
- https://docs.spring.io/spring-boot/reference/using/devtools.html#using.devtools.restart.limitations says a Known Limitation and that libraries should handle it.

**Additional context**
- Remove ``spring-boot-devtools` module

Hope you can give any hints to configure or solve this.

**Comment by kashev** [comment]
I think a very similar issue is happening to me in a Maven project with multiple modules. In a shared library `common-lib`, an object is put into a distributed data structure. In my actual spring app using Hazelcast (`my-app`), when I take the object out, `instance of` fails. I stepped through using a debugger and noticed that the classloader was different in `my-app` - it was `RestartClassLoader`, not `AppClassloader`.

Has anyone figured out a way to configure `spring-boot-devtools` so they don't have to remove it completely? In my testing, setting `spring.devtools.restart.enabled=false` in my `application.properties` doesn't actually seem to fix the issue (only fully removing it).

**Comment by ArnauAregall** [comment]
Still reproducible with SB 3.4.2 and Hazelcast 5.5.0, using JDK 21.

```
org.springframework.boot:spring-boot:3.4.2
org.springframework.boot:spring-boot-autoconfigure:3.4.2
org.springframework.boot:spring-boot-devtools:3.4.2

com.hazelcast:hazelcast:5.5.0
com.hazelcast:hazelcast-spring:5.5.0
```

**Comment by OmarHawk** [comment]
I do wonder if this is something Hazelcast or Spring Boot Devtools need to solve. Because in older Spring Boot versions this had worked, I'd assume it a regression from there...

**Comment by ArnauAregall** [comment]
As when running locally with devtools enabled  having a distributed cache is not likely needed (at least for us), we finally decided to provide an in-memory `CacheManager` when running the app with `develop` profile and a `HazelcastCacheManager` for our default profile.

**Comment by singhnitinkr** [comment]
We are trying to upgrade from HA (IMDG) 4.2.5 to HA 5.5.x ; and have been having similar classloader issue. The exact stack trace is however different. Until Hazelcast-5.3.5 current setup works flawlessly with just jar upgrade; but as soon as we try Hazelcast-4.0, we start getting different flavors of class not found.

Hazelcast Jar Version: 4.0 or above
Java: Microsoft OpenJDK 17/21 [fails with both]
Java app server: Tomcat 9 [tried with both <[Loader delegate](https://tomcat.apache.org/tomcat-9.0-doc/class-loader-howto.html)="true"/> or false;]

[HA stack-trace.txt](https://github.com/user-attachments/files/19783269/HA.stack-trace.txt)

```
Exception: 00:31:09.087 [hz.MASTER.partition-operation.thread-5] ERROR com.hazelcast.map.impl.operation.SetOperation - [localhost]:5702 [MASTER] [5.5.5] java.lang.ClassNotFoundException: com.xx.core.data.user.xx
com.hazelcast.nio.serialization.HazelcastSerializationException: java.lang.ClassNotFoundException: com.xx.core.data.user.xx
        at com.hazelcast.internal.serialization.impl.defaultserializers.JavaDefaultSerializers$JavaSerializer.read(JavaDefaultSerializers.java:99) ~[hazelcast-5.5.5.jar:5.5.5]
        at com.hazelcast.internal.serialization.impl.defaultserializers.JavaDefaultSerializers$JavaSerializer.read(JavaDefaultSerializers.java:88) ~[hazelcast-5.5.5.jar:5.5.5]
        at 
......
Caused by: java.lang.ClassNotFoundException: com.xx.core.data.user.xx
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445) ~[?:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593) ~[?:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
```

For more reference, we usually bundle wars, but there are some common utils and sub-module which we package as jars (our own classes) and add in tomcat-lib, directly serializing classes from within wars work fine, but not from tomcat/webapps/{war}/WEB-INF/lib or tomcat/lib

Maybe HA 4.x with minimum Java version as 17, were able to do away with some legacy code or classloading optimizations that needs identification and additional changes to support.

I will try to test more and localize to simple repro setup if possible
