### ISSUE TITLE
Kubernetes Hazelcast Issue with version 5 onwards. It works fine with 4.2.8 version.

### ISSUE THREAD

**Issue by dwvd** [hazelcast/hazelcast#26364]
I have an issue with Hazelcast version 5.4.0 and my pods are not connection to each other and I am getting exception. 
I have generated my files from here 
https://github.com/hazelcast/charts/tree/master/stable/hazelcast

and only change which I did is to change the ClusterRole to Role and ClusterRoleBinding to RoleBinding.

In my Kubernetes environment, I have Istio configured. Exactly same config works fine if I change the docker Image from 5.4.0 to 4.2.8 but gives following exception with 5.4.0

LOGGING_LEVEL is set to ALL

```
024-06-24 18:14:34,068 [[35mDEBUG[m] [[36mhz.admiring_jemison.InvocationMonitorThread[m] [[34mc.h.s.i.o.i.InvocationMonitor[m]: [10.42.152.81]:5701 [dev] [5.4.0] Invocations:1 timeouts:0 backup-timeouts:0 member-left: 0
2024-06-24 18:14:35,068 [[30mTRACE[m] [[36mhz.admiring_jemison.InvocationMonitorThread[m] [[34mc.h.s.i.o.i.InvocationMonitor[m]: [10.42.152.81]:5701 [dev] [5.4.0] Scanning all invocations
2024-06-24 18:14:35,068 [[35mDEBUG[m] [[36mhz.admiring_jemison.InvocationMonitorThread[m] [[34mc.h.s.i.o.i.InvocationMonitor[m]: [10.42.152.81]:5701 [dev] [5.4.0] Invocations:1 timeouts:0 backup-timeouts:0 member-left: 0
2024-06-24 18:14:36,067 [[30mTRACE[m] [[36mhz.admiring_jemison.InvocationMonitorThread[m] [[34mc.h.s.i.o.i.InvocationMonitor[m]: [10.42.152.81]:5701 [dev] [5.4.0] Scanning all invocations
2024-06-24 18:14:36,068 [[35mDEBUG[m] [[36mhz.admiring_jemison.InvocationMonitorThread[m] [[34mc.h.s.i.o.i.InvocationMonitor[m]: [10.42.152.81]:5701 [dev] [5.4.0] Invocations:1 timeouts:0 backup-timeouts:0 member-left: 0
2024-06-24 18:14:36,070 [[30mTRACE[m] [[36mhz.admiring_jemison.InvocationMonitorThread[m] [[34mc.h.s.i.o.i.InvocationMonitor[m]: [10.42.152.81]:5701 [dev] [5.4.0] Broadcasting operation control packets to: 1 members
2024-06-24 18:14:36,632 [[35mDEBUG[m] [[36mmain[m] [[34mc.h.i.c.i.DiscoveryJoiner[m]: [10.42.152.81]:5701 [dev] [5.4.0] java.util.concurrent.TimeoutException: JoinMastershipClaimOp failed to complete within 9999914394 NANOSECONDS. Invocation{op=com.hazelcast.internal.cluster.impl.operations.JoinMastershipClaimOp{serviceName='hz:core:clusterService', identityHash=978609035, partitionId=-1, replicaIndex=0, callId=1, invocationTime=1719252866614 (2024-06-24 18:14:26.614), waitTimeout=-1, callTimeout=60000, tenantControl=com.hazelcast.spi.impl.tenantcontrol.NoopTenantControl@0}, tryCount=1, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=60000, firstInvocationTimeMs=1719252866612, firstInvocationTime='2024-06-24 18:14:26.612', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 00:00:00.000', targetAddress=[10.42.3.164]:5701, targetMember=null, memberListVersion=1, pendingResponse={VOID}, backupsAcksExpected=-1, backupsAcksReceived=0, connection=null}
com.hazelcast.core.HazelcastException: java.util.concurrent.TimeoutException: JoinMastershipClaimOp failed to complete within 9999914394 NANOSECONDS. Invocation{op=com.hazelcast.internal.cluster.impl.operations.JoinMastershipClaimOp{serviceName='hz:core:clusterService', identityHash=978609035, partitionId=-1, replicaIndex=0, callId=1, invocationTime=1719252866614 (2024-06-24 18:14:26.614), waitTimeout=-1, callTimeout=60000, tenantControl=com.hazelcast.spi.impl.tenantcontrol.NoopTenantControl@0}, tryCount=1, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=60000, firstInvocationTimeMs=1719252866612, firstInvocationTime='2024-06-24 18:14:26.612', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 00:00:00.000', targetAddress=[10.42.3.164]:5701, targetMember=null, memberListVersion=1, pendingResponse={VOID}, backupsAcksExpected=-1, backupsAcksReceived=0, connection=null}
	at com.hazelcast.internal.util.ExceptionUtil.lambda$static$0(ExceptionUtil.java:48) ~[hazelcast-5.4.0.jar:5.4.0]
	at com.hazelcast.internal.util.ExceptionUtil.peel(ExceptionUtil.java:126) ~[hazelcast-5.4.0.jar:5.4.0]
	at com.hazelcast.internal.util.ExceptionUtil.peel(ExceptionUtil.java:69) ~[hazelcast-5.4.0.jar:5.4.0]
	at com.hazelcast.internal.util.ExceptionUtil.rethrow(ExceptionUtil.java:131) ~[hazelcast-5.4.0.jar:5.4.0]
	at com.hazelcast.internal.util.FutureUtil$1.handleException(FutureUtil.java:54) ~[hazelcast-5.4.0.jar:5.4.0]
	at com.hazelcast.internal.util.FutureUtil.returnWithDeadline(FutureUtil.java:276) ~[hazelcast-5.4.0.jar:5.4.0]
	at com.hazelcast.internal.util.FutureUtil.returnWithDeadline(FutureUtil.java:241) ~[hazelcast-5.4.0.jar:5.4.0]
	at com.hazelcast.internal.cluster.impl.TcpIpJoiner.claimMastership(TcpIpJoiner.java:236) ~[hazelcast-5.4.0.jar:5.4.0]
	at com.hazelcast.internal.cluster.impl.TcpIpJoiner.tryClaimMastership(TcpIpJoiner.java:186) ~[hazelcast-5.4.0.jar:5.4.0]
	at com.hazelcast.internal.cluster.impl.TcpIpJoiner.joinViaPossibleMembers(TcpIpJoiner.java:172) ~[hazelcast-5.4.0.jar:5.4.0]
	at com.hazelcast.internal.cluster.impl.TcpIpJoiner.doJoin(TcpIpJoiner.java:113) ~[hazelcast-5.4.0.jar:5.4.0]
	at com.hazelcast.internal.cluster.impl.AbstractJoiner.join(AbstractJoiner.java:139) ~[hazelcast-5.4.0.jar:5.4.0]
	at com.hazelcast.instance.impl.Node.join(Node.java:946) ~[hazelcast-5.4.0.jar:5.4.0]
	at com.hazelcast.instance.impl.Node.start(Node.java:542) ~[hazelcast-5.4.0.jar:5.4.0]
	at com.hazelcast.instance.impl.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:124) ~[hazelcast-5.4.0.jar:5.4.0]
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:218) ~[hazelcast-5.4.0.jar:5.4.0]
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:197) ~[hazelcast-5.4.0.jar:5.4.0]
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:135) ~[hazelcast-5.4.0.jar:5.4.0]
	at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:95) ~[hazelcast-5.4.0.jar:5.4.0]
	at com.hazelcast.core.server.HazelcastMemberStarter.main(HazelcastMemberStarter.java:45) ~[hazelcast-5.4.0.jar:5.4.0]
	at com.hazelcast.commandline.HazelcastServerCommandLine.lambda$new$2f647568$1(HazelcastServerCommandLine.java:44) ~[hazelcast-distribution-5.4.0.jar:?]
	at com.hazelcast.jet.function.RunnableEx.run(RunnableEx.java:31) [hazelcast-5.4.0.jar:5.4.0]
	at com.hazelcast.commandline.HazelcastServerCommandLine.start(HazelcastServerCommandLine.java:101) [hazelcast-distribution-5.4.0.jar:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at picocli.CommandLine.executeUserObject(CommandLine.java:2066) [picocli-4.7.5.jar:4.7.5]
	at picocli.CommandLine.access$1500(CommandLine.java:148) [picocli-4.7.5.jar:4.7.5]
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461) [picocli-4.7.5.jar:4.7.5]
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453) [picocli-4.7.5.jar:4.7.5]
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415) [picocli-4.7.5.jar:4.7.5]
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273) [picocli-4.7.5.jar:4.7.5]
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417) [picocli-4.7.5.jar:4.7.5]
	at picocli.CommandLine.execute(CommandLine.java:2170) [picocli-4.7.5.jar:4.7.5]
	at com.hazelcast.commandline.HazelcastServerCommandLine.runCommandLine(HazelcastServerCommandLine.java:63) [hazelcast-distribution-5.4.0.jar:?]
	at com.hazelcast.commandline.HazelcastServerCommandLine.main(HazelcastServerCommandLine.java:52) [hazelcast-distribution-5.4.0.jar:?]
Caused by: java.util.concurrent.TimeoutException: JoinMastershipClaimOp failed to complete within 9999914394 NANOSECONDS. Invocation{op=com.hazelcast.internal.cluster.impl.operations.JoinMastershipClaimOp{serviceName='hz:core:clusterService', identityHash=978609035, partitionId=-1, replicaIndex=0, callId=1, invocationTime=1719252866614 (2024-06-24 18:14:26.614), waitTimeout=-1, callTimeout=60000, tenantControl=com.hazelcast.spi.impl.tenantcontrol.NoopTenantControl@0}, tryCount=1, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=60000, firstInvocationTimeMs=1719252866612, firstInvocationTime='2024-06-24 18:14:26.612', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 00:00:00.000', targetAddress=[10.42.3.164]:5701, targetMember=null, memberListVersion=1, pendingResponse={VOID}, backupsAcksExpected=-1, backupsAcksReceived=0, connection=null}
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.newTimeoutException(InvocationFuture.java:85) ~[hazelcast-5.4.0.jar:5.4.0]
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:657) ~[hazelcast-5.4.0.jar:5.4.0]
	at com.hazelcast.internal.util.FutureUtil.executeWithDeadline(FutureUtil.java:390) ~[hazelcast-5.4.0.jar:5.4.0]
	at com.hazelcast.internal.util.FutureUtil.returnWithDeadline(FutureUtil.java:271) ~[hazelcast-5.4.0.jar:5.4.0]
	... 29 more
2024-06-24 18:14:36,634 [[35mDEBUG[m] [[36mmain[m] [[34mc.h.i.c.i.DiscoveryJoiner[m]: [10.42.152.81]:5701 [dev] [5.4.0] My claim to be master is rejected! Voting endpoints: [[10.42.3.164]:5701]
2024-06-24 18:14:36,634 [[35mDEBUG[m] [[36mmain[m] [[34mc.h.i.c.ClusterService[m]: [10.42.152.81]:5701 [dev] [5.4.0] Setting master address to null
2024-06-24 18:14:36,634 [[35mDEBUG[m] [[36mmain[m] [[34mc.h.i.c.i.DiscoveryJoiner[m]: [10.42.152.81]:5701 [dev] [5.4.0] NOT sending master question to blacklisted endpoints: {}
2024-06-24 18:14:36,634 [[35mDEBUG[m] [[36mmain[m] [[34mc.h.i.c.i.DiscoveryJoiner[m]: [10.42.152.81]:5701 [dev] [5.4.0] Sending master question to [10.42.3.164]:5701


```

Please help me how to triage this issue.

**Comment by semihbkgr** [comment]
Hi @dwvd 

There have been some changes in the protocol used for member-to-member communication between Hazelcast versions 4.x and 5.x.

Hazelcast 5.x uses a server-first protocol, which makes automatic protocol selection in Istio impossible.

> Server First protocols, such as MySQL, are incompatible with automatic protocol selection. See [Server first protocols](https://istio.io/latest/docs/ops/deployment/application-requirements/#server-first-protocols) for more information.

To address this issue, you need to specify the protocol in the Istio context. You can use a headless service to provide the protocol to Istio

---

Create a headless service that selects all the Hazelcast member pods. Specify the Hazelcast port and protocol in this headless service:

```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: hazelcast
    meta.helm.sh/release-namespace: default
  labels:
    app.kubernetes.io/instance: hazelcast
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: hazelcast
    helm.sh/chart: hazelcast-5.9.1
  name: hazelcast
  namespace: default
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - appProtocol: tcp
    name: hazelcast
    port: 5701
    targetPort: hazelcast
  selector:
    app.kubernetes.io/instance: hazelcast
    app.kubernetes.io/name: hazelcast
    role: hazelcast
```

Then, you can safely use this headless service in the Kubernetes discovery plugin configuration:

```yaml
hazelcast:
  network:
    join:
      kubernetes:
        enabled: true
        namespace: default
        service-name: hazelcast
```

Hazelcast and Istio should work together with this setup.

```
NAME                    READY   STATUS    RESTARTS   AGE
hazelcast-0             2/2     Running   0          1m
hazelcast-1             2/2     Running   0          1m
hazelcast-2             2/2     Running   0          1m
```

```
2024-06-25 14:48:59,732 [ INFO] [hz.romantic_wilbur.priority-generic-operation.thread-0] [c.h.i.c.ClusterService]: [10.56.1.11]:5701 [dev] [5.4.0]

Members {size:3, ver:3} [
	Member [10.56.1.11]:5701 - 64cbee2d-a611-425f-b062-aec732808836 this
	Member [10.56.0.9]:5701 - 0588f44d-5e17-4019-9aa9-249fc786e2e0
	Member [10.56.2.14]:5701 - 1181064c-ea2e-427a-b2c7-8d7aa611218a
]

```

The Hazelcast Platform Operator and Helm charts automate and manage these steps with advanced capabilities.

**Comment by dwvd** [comment]
Thanks for response. Here are all the list of files which I am uploading to kubernetes and it works fine with 4.2.8 version but get into following exception and keeps restarting the pod1 as it tries to connect to pod0.


<img width="1772" alt="Screenshot 2024-06-25 at 12 20 39 PM" src="https://github.com/hazelcast/hazelcast/assets/8029422/d9ef966f-c449-416c-a7fc-b0048c6d8ac7">


You may need to change docker registry and name space into it.
When I am changing the image from 4.2.8 it all works but not with 5.4.0

config map

```
apiVersion: v1
data:
  hazelcast.yaml: |-
    hazelcast:
      cluster-name: it
      cache:
        "*":
          key-type:
            class-name: java.lang.Object
          value-type:
            class-name: java.lang.Object
          statistics-enabled: false
          management-enabled: false
          expiry-policy-factory:
            timed-expiry-policy-factory:
              expiry-policy-type: MODIFIED
              duration-amount: 24
              time-unit: HOURS
          backup-count: 1
          async-backup-count: 1
          eviction:
            size: 1000000
            max-size-policy: ENTRY_COUNT
            eviction-policy: LFU
      jet:
        enabled: true
      network:
        join:
          kubernetes:
            enabled: true
            service-name: hazelcast-cluster
        rest-api:
          enabled: true
kind: ConfigMap
metadata:
  annotations:
    usb-buildPipeline: somenotation
  labels:
    app: hazelcast
  name: hazelcast-configuration



```

HPA

```
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hazelcast-cluster-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: hazelcast-cluster
  minReplicas: 3
  maxReplicas: 8
  targetCPUUtilizationPercentage: 80


```


```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hazelcast-role
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  - pods
  - nodes
  - services
  verbs:
  - get
  - list


```

```
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hazelcast-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: hazelcast-role
subjects:
- kind: ServiceAccount
  name: hazelcast-service-account
  namespace: default
- kind: ServiceAccount
  name: someservice
  namespace: default
```

```
apiVersion: v1
kind: Service
metadata:
  name: hazelcast-cluster
spec:
  type: ClusterIP
  clusterIP: None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  selector:
    app: hazelcast-cluster
  ports:
    - appProtocol: tcp
      name: hazelcast
      port: 5701
      targetPort: hazelcast

```

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hazelcast-service-account
```

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hazelcast-cluster
spec:
  serviceName: hazelcast-cluster
  replicas: 3
  selector:
    matchLabels:
      app: hazelcast-cluster
  template:
    metadata:
      labels:
        app: hazelcast-cluster
    spec:
      terminationGracePeriodSeconds: 600
      hostNetwork: false
      hostPID: false
      hostIPC: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
      containers:
      - name: hazelcast-cluster
        image: "artifactory.registry:5000/hazelcast/hazelcast:4.2.8"
        ###DOCKER_IMAGE#|
        imagePullPolicy: "IfNotPresent"
        resources:
            limits:
              cpu: 10000m
              memory: 12000Mi
            requests:
              cpu: 8000m
              memory: 2048Mi
        ports:
        - name: hazelcast
          containerPort: 5701
        livenessProbe:
          httpGet:
            path: /hazelcast/health/node-state
            port: 5701
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 10
          successThreshold: 1
          failureThreshold: 10
        readinessProbe:
          httpGet:
            path: /hazelcast/health/ready
            port: 5701
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 10
          successThreshold: 1
          failureThreshold: 10
        volumeMounts:
        - name: hazelcast-storage
          mountPath: /data/hazelcast
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: JAVA_OPTS
          value: "-Dhazelcast.config=/data/hazelcast/hazelcast.yaml -Dhz.jet.enabled=true -Dhazelcast.health.monitoring.level=NOISY -Dhazelcast.health.monitoring.delay.seconds=60 -Dhazelcast.shutdownhook.policy=GRACEFUL -Dhazelcast.shutdownhook.enabled=true -Dhazelcast.graceful.shutdown.max.wait=600   "
        securityContext:
          runAsNonRoot: true
          runAsUser: 65534
          runAsGroup: 65534
          privileged: false
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      serviceAccountName: hazelcast-service-account
      automountServiceAccountToken: true
      volumes:
      - name: hazelcast-storage
        configMap:
          name: hazelcast-configuration
```

**Comment by semihbkgr** [comment]
Thank you for the detailed answer and for sharing the resource files.

I tested your setup with Hazelcast 5.4.0 in Istio 1.21, and it is working in my cluster.

The error message indicates that pod-1 cannot communicate with pod-0, which occurs when the protocol is not specified properly. However, it seems that you did specify the protocol (TCP) in the headless service. Hazelcast version 4.2.8 works because it doesn't require you to specify the protocol manually; Istio can automatically detect it. This is not the case for Hazelcast version 5.

Do you have any specific configurations that might affect protocol selection or communication in your Istio setup?

**Comment by dwvd** [comment]
Thanks @semihbkgr . I am onto Istio version 1.19.
Attach are the logs from my istio-proxy for the pod1 which is trying to connect to pod0
[hazelcast-cluster-1_istio-proxy (1).log](https://github.com/user-attachments/files/16018396/hazelcast-cluster-1_istio-proxy.1.log)

How to triage pod for root cause in this case for socket connection timeout issue?

**Comment by semihbkgr** [comment]
I recall that some patch versions of Istio 1.19 and 1.18 were incompatible with Hazelcast due to a headless service issue when `podManagementPolicy` is set to `Parallel`.

Based on your configuration, it appears you are not using the `Parallel` `podManagementPolicy`. However, could you confirm that you are indeed using `podManagementPolicy` as `OrderedReady`?

**Comment by dwvd** [comment]
@semihbkgr  Yes you are right. We have a podManagementPolicy as OrderedReady. 
Any fix for this or only option is upgrade to istio 1.20?

**Comment by semihbkgr** [comment]
I don't think upgrading Istio to version 1.20 will resolve this issue. Could you please share the specific Istio version including the patch number? I'll check to see if there are any compatibility issues.

**Comment by dwvd** [comment]
Following is our version
1.19.3-41218ffa66c12acf77ad08b3ef07d296218d0929-Clean

**Comment by semihbkgr** [comment]
I tested it, and it is working in my cluster with the same setup.

The only way to get the same error logs as you is if the appProtocol(`tcp`) value in the headless service is deleted.

Could you share the endpoints of the Hazelcast service?

```shell
kubectl get ep hazelcast-cluster -oyaml
```

```yaml
apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2024-06-28T19:34:21Z"
  creationTimestamp: "2024-06-28T18:33:13Z"
  labels:
    service.kubernetes.io/headless: ""
  name: hazelcast-cluster
  namespace: test
  resourceVersion: "143478"
  uid: 94f964a8-8a5d-4da9-8116-f9769276364e
subsets:
- addresses:
  - hostname: hazelcast-cluster-0
    ip: 10.128.0.19
    nodeName: gke-cluster-semih-default-pool-0ee36f66-vjpx
    targetRef:
      kind: Pod
      name: hazelcast-cluster-0
      namespace: test
      uid: e3242540-2504-4cdd-ab8f-c91749dad29e
  - hostname: hazelcast-cluster-1
    ip: 10.128.1.15
    nodeName: gke-cluster-semih-default-pool-0ee36f66-shz7
    targetRef:
      kind: Pod
      name: hazelcast-cluster-1
      namespace: test
      uid: d935c7e5-dbf3-4bb9-a629-a051d99041ec
  notReadyAddresses:
  - hostname: hazelcast-cluster-2
    ip: 10.128.2.17
    nodeName: gke-cluster-semih-default-pool-0ee36f66-17mx
    targetRef:
      kind: Pod
      name: hazelcast-cluster-2
      namespace: test
      uid: 96df2115-ebbc-4106-9c7a-294ba32a6a87
  ports:
  - appProtocol: tcp
    name: hazelcast
    port: 5701
    protocol: TCP

```

**Comment by dwvd** [comment]
Here is my output-

```
> kubectl get ep hazelcast-cluster -oyaml -n apl-osl-data-apis-dev1
apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: "2024-06-25T17:24:05Z"
  labels:
    service.kubernetes.io/headless: ""
  name: hazelcast-cluster
  namespace: apl-osl-data-apis-dev1
  resourceVersion: "5914154545"
  uid: 4d8a39ba-8fff-4c85-af55-03f213ea6af6
subsets:
- addresses:
  - hostname: hazelcast-cluster-0
    ip: 10.42.115.168
    nodeName: gen-obc-k8-test1-worker-userpool2-tf3
    targetRef:
      kind: Pod
      name: hazelcast-cluster-0
      namespace: apl-osl-data-apis-dev1
      uid: c7158957-af2b-4b4d-a261-2c06b40c6a83
  - hostname: hazelcast-cluster-1
    ip: 10.42.98.82
    nodeName: gen-obc-k8-test1-worker-userpool2-tf1
    targetRef:
      kind: Pod
      name: hazelcast-cluster-1
      namespace: apl-osl-data-apis-dev1
      uid: f4989af6-e717-4547-9a7f-07a113c8df2b
  ports:
  - appProtocol: tcp
    name: hazelcast
    port: 5701
    protocol: TCP


```

**Comment by dwvd** [comment]
here is my output-

```
> kubectl get ep hazelcast-cluster -oyaml -n apl-osl-data-apis-dev1
apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2024-06-28T20:48:21Z"
  creationTimestamp: "2024-06-25T17:24:05Z"
  labels:
    service.kubernetes.io/headless: ""
  name: hazelcast-cluster
  namespace: apl-osl-data-apis-dev1
  resourceVersion: "5922104237"
  uid: 4d8a39ba-8fff-4c85-af55-03f213ea6af6
subsets:
- addresses:
  - hostname: hazelcast-cluster-0
    ip: 10.42.130.96
    nodeName: gen-obc-k8-test1-worker-userpool2-tf14
    targetRef:
      kind: Pod
      name: hazelcast-cluster-0
      namespace: apl-osl-data-apis-dev1
      uid: 232f5ff2-f9e6-4656-a34e-63e8a8b2313c
  notReadyAddresses:
  - hostname: hazelcast-cluster-1
    ip: 10.42.154.56
    nodeName: gen-obc-k8-test1-worker-userpool4-tf11
    targetRef:
      kind: Pod
      name: hazelcast-cluster-1
      namespace: apl-osl-data-apis-dev1
      uid: f2928b2c-1bd0-4451-bf78-25b0efb70381
  ports:
  - appProtocol: tcp
    name: hazelcast
    port: 5701
    protocol: TCP


```

**Comment by dwvd** [comment]
@semihbkgr - Any other thing which I could try to figure out exact issue?

**Comment by semihbkgr** [comment]
Can you try setting `publishNotReadyAddresses` to `true` in the headless service?

**Comment by dwvd** [comment]
It still keep trying to connect.

<img width="1915" alt="Screenshot 2024-07-02 at 7 45 48 AM" src="https://github.com/hazelcast/hazelcast/assets/8029422/f34bfacb-066c-407c-aba5-4b6662d38238">

**Comment by dwvd** [comment]
Any other option which I can try? @semihbkgr

**Comment by marquesj2-ppb** [comment]
Did you manage to get this working?

**Comment by dwvd** [comment]
No, it never worked for me.

**Comment by atilsensalduz** [comment]
Hey @dwvd , I’d like to investigate this issue further. We encountered a similar problem when the user applied the `traffic.sidecar.istio.io/excludeOutboundPorts: "5701" `annotation without also setting `traffic.sidecar.istio.io/excludeInboundPorts`.

This caused an asymmetric traffic path where outbound traffic bypassed Envoy (as intended), but inbound traffic was still intercepted by Envoy.

Could you please check if there is any annotation that excludes only unidirectional traffic from Envoy interception?

**Comment by dwvd** [comment]
@atilsensalduz I don't have any traffic.sidecar.istio.io/excludeOutboundPorts and traffic.sidecar.istio.io/excludeInboundPorts annotations in my configuration.

**Comment by atilsensalduz** [comment]
Thanks for confirming @dwvd . Just to make sure I understand correctly, your namespace where Hazelcast is installed has the `istio-injection=enabled` label, and there aren’t any additional Istio-specific configurations applied, right?

**Comment by dwvd** [comment]
yes you are right. no additional configurations.

**Comment by atilsensalduz** [comment]
I couldn't reproduce the issue with the configuration you provided. If you don’t mind, could you check the traffic using tcpdump with the following commands?

```
k debug -it hazelcast-cluster-1 --image=dockersec/tcpdump --target hazelcast-cluster -- sh  
tcpdump -i any port 5701 -vv  
```

**Comment by rcbandit111** [comment]
Do you have some solution for the issue?

**Comment by dwvd** [comment]
no

**Comment by dwvd** [comment]
> I had same issue with istio 1.17, after adding annotation 
> `  traffic.sidecar.istio.io/excludeInboundPorts: "5701"` and 
>   `  traffic.sidecar.istio.io/excludeOutboundPorts: "5701"`
> hazelcast works fine now
> 

Yes it worked with this suggestion.
