### ISSUE TITLE
com.hazelcast.jet.sql.impl.aggregate.SqlAggregateTest - NullPointerException [HZ-4803]

### ISSUE THREAD

**Issue by Patras3** [hazelcast/hazelcast#26367]
_master_ (commit e0fdcd3abe42b8961c2ea0a1e3811cb42f538d26)

Failed on openj9-21: https://jenkins.hazelcast.com/job/Hazelcast-master-Openj9-21-nightly/24/testReport/com.hazelcast.jet.sql.impl.aggregate/SqlAggregateTest

All tests failed with the NPEs
<details><summary>Stacktrace:</summary>

```
java.lang.NullPointerException
	at java.base/java.lang.StringConcatHelper.stringOf(StringConcatHelper.java)
	at com.hazelcast.jet.SimpleTestInClusterSupport.lambda$supportAfter$6(SimpleTestInClusterSupport.java:174)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1249)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:522)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:512)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:239)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at com.hazelcast.jet.SimpleTestInClusterSupport.supportAfter(SimpleTestInClusterSupport.java:175)
	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
	at com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37)
	at com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:103)
	at com.hazelcast.test.metrics.MetricsRule$1.evaluate(MetricsRule.java:64)
	at junitparams.internal.ParameterisedTestMethodRunner.runMethodInvoker(ParameterisedTestMethodRunner.java:47)
	at junitparams.internal.ParameterisedTestMethodRunner.runTestMethod(ParameterisedTestMethodRunner.java:40)
	at junitparams.internal.ParameterisedTestClassRunner.runParameterisedTest(ParameterisedTestClassRunner.java:146)
	at junitparams.JUnitParamsRunner.runChild(JUnitParamsRunner.java:446)
	at junitparams.JUnitParamsRunner.runChild(JUnitParamsRunner.java:393)
	at com.hazelcast.test.OverridePropertyRule$1.evaluate(OverridePropertyRule.java:68)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.lang.Thread.run(Thread.java:1595)

```
</details>

<details><summary>Standard output:</summary>

```
CREATE MAPPING o_bdc828aa_3118_4ac9_9866_9bb08c8b5138 TYPE TestBatch OPTIONS ('names'='name,distance', 'types'='VARCHAR,INTEGER', 'values'='A,1
B,2
A,3
B,4', 'streaming'='false')
08:09:47,093 DEBUG || - [CalciteSqlOptimizerImpl] Time-limited test - [127.0.0.1]:5701 [dev] [5.5.0-SNAPSHOT] Before logical opt:
LogicalSort(sort0=[$1], dir0=[DESC])
  LogicalAggregate(group=[{0}], avg_distance=[AVG($1)])
    LogicalTableScan(table=[[hazelcast, public, o_bdc828aa_3118_4ac9_9866_9bb08c8b5138[projects=[$0, $1]]]])

08:09:47,098 DEBUG || - [CalciteSqlOptimizerImpl] Time-limited test - [127.0.0.1]:5701 [dev] [5.5.0-SNAPSHOT] After logical opt:
SortLogicalRel(sort0=[$1], dir0=[DESC])
  AggregateLogicalRel(group=[{0}], avg_distance=[AVG($1)])
    FullScanLogicalRel(table=[[hazelcast, public, o_bdc828aa_3118_4ac9_9866_9bb08c8b5138[projects=[$0, $1]]]])

08:09:47,111 DEBUG || - [CalciteSqlOptimizerImpl] Time-limited test - [127.0.0.1]:5701 [dev] [5.5.0-SNAPSHOT] After physical opt:
SortPhysicalRel(sort0=[$1], dir0=[DESC])
  AggregateCombineByKeyPhysicalRel(group=[{0}], avg_distance=[AVG($1)])
    AggregateAccumulateByKeyPhysicalRel(group=[{0}])
      FullScanPhysicalRel(table=[[hazelcast, public, o_bdc828aa_3118_4ac9_9866_9bb08c8b5138[projects=[$0, $1]]]], discriminator=[0])

08:09:47,127 DEBUG || - [LightMasterContext] Time-limited test - [127.0.0.1]:5701 [dev] [5.5.0-SNAPSHOT] Start executing light job 0be6-91ab-d1c2-0001, execution graph in DOT format:
digraph DAG {
	"TestBatch[public.o_bdc828aa_3118_4ac9_9866_9bb08c8b5138]" [localParallelism=1];
	"AccumulateByKey" [localParallelism=2];
	"CombineByKey" [localParallelism=2];
	"Sort" [localParallelism=2];
	"SortCombine" [localParallelism=1];
	"ClientSink" [localParallelism=1];
	"TestBatch[public.o_bdc828aa_3118_4ac9_9866_9bb08c8b5138]" -> "AccumulateByKey" [label="isolated", queueSize=1024];
	"AccumulateByKey" -> "CombineByKey" [label="distributed-partitioned", queueSize=1024];
	"CombineByKey" -> "Sort" [label="isolated", queueSize=1024];
	"Sort" -> "SortCombine" [label="distributed to [127.0.0.1]:5701-partitioned-ordered", queueSize=1024];
	"SortCombine" -> "ClientSink" [label="distributed to [127.0.0.1]:5701-partitioned", queueSize=1024];
}
HINT: You can use graphviz or http://viz-js.com to visualize the printed graph.
08:09:47,127 DEBUG || - [LightMasterContext] Time-limited test - [127.0.0.1]:5701 [dev] [5.5.0-SNAPSHOT] Job config for 0be6-91ab-d1c2-0001: JobConfig {name=null, processingGuarantee=NONE, snapshotIntervalMillis=10000, autoScaling=true, suspendOnFailure=false, splitBrainProtectionEnabled=false, enableMetrics=true, storeMetricsAfterJobCompletion=false, resourceConfigs={}, serializerConfigs={}, arguments={__sql.arguments=[], __sql.queryUnbounded=false, __sql.queryText=SELECT name, AVG(distance) avg_distance FROM o_bdc828aa_3118_4ac9_9866_9bb08c8b5138 GROUP BY name ORDER BY avg_distance DESC}, classLoaderFactory=null, initialSnapshotName=null, maxProcessorAccumulatedRecords=-1, timeoutMillis=0}
08:09:47,127 DEBUG || - [LightMasterContext] Time-limited test - [127.0.0.1]:5701 [dev] [5.5.0-SNAPSHOT] Building execution plan for 0be6-91ab-d1c2-0001
08:09:47,129 DEBUG || - [LightMasterContext] hz.SqlAggregateTest_inspiring_wozniak.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.5.0-SNAPSHOT] Built execution plans for 0be6-91ab-d1c2-0001
08:09:47,129 DEBUG || - [InitExecutionOperation] hz.SqlAggregateTest_inspiring_wozniak.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.5.0-SNAPSHOT] Initializing execution plan for job sun.nio.cs.UTF_8$Encoder@f252249e, execution 0be6-91ab-d1c2-0001 from [127.0.0.1]:5701
08:09:47,137 DEBUG || - [JobExecutionService] hz.SqlAggregateTest_inspiring_wozniak.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.5.0-SNAPSHOT] Execution plan for light job ID=0be6-91ab-d1c2-0001, jobName='0be6-91ab-d1c2-0001', executionId=0be6-91ab-d1c2-0001 initialized, will start the execution
08:09:47,154 DEBUG || - [InitExecutionOperation] hz.SqlAggregateTest_pedantic_wozniak.generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.5.0-SNAPSHOT] Initializing execution plan for job com.hazelcast.jet.impl.execution.init.ExecutionPlan@a55a6f28, execution 0be6-91ab-d1c2-0001 from [127.0.0.1]:5701
08:09:47,158 DEBUG || - [JobExecutionService] hz.SqlAggregateTest_pedantic_wozniak.generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.5.0-SNAPSHOT] Execution plan for light job ID=0be6-91ab-d1c2-0001, jobName='0be6-91ab-d1c2-0001', executionId=0be6-91ab-d1c2-0001 initialized, will start the execution
08:09:47,167 DEBUG || - [JobExecutionService] hz.SqlAggregateTest_pedantic_wozniak.cached.thread-4 - [127.0.0.1]:5702 [dev] [5.5.0-SNAPSHOT] Completed execution of job 'null', execution 0be6-91ab-d1c2-0001
08:09:47,167 DEBUG || - [JobExecutionService] hz.SqlAggregateTest_pedantic_wozniak.cached.thread-4 - [127.0.0.1]:5702 [dev] [5.5.0-SNAPSHOT] Execution of job 'null', execution 0be6-91ab-d1c2-0001 completed
08:09:47,170 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-7 - [127.0.0.1]:5701 [dev] [5.5.0-SNAPSHOT] Completed execution of job 'null', execution 0be6-91ab-d1c2-0001
08:09:47,170 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-7 - [127.0.0.1]:5701 [dev] [5.5.0-SNAPSHOT] Execution of job 'null', execution 0be6-91ab-d1c2-0001 completed
08:09:47,170  INFO || - [SqlTestSupport] Time-limited test - Removing 1 cached plans in SqlTestSupport.@After
08:09:47,170  INFO || - [SqlTestSupport] Time-limited test - Removing 0 cached plans in SqlTestSupport.@After
08:09:47,171  INFO || - [SimpleTestInClusterSupport] Time-limited test - Ditching 0 jobs in SimpleTestInClusterSupport.@After: []
08:09:47,171  INFO || - [HazelcastTestSupport] Time-limited test - Shutting down node factory as @After action
BuildInfo right after test_orderByAvg(INTEGER, DECIMAL) [2](com.hazelcast.jet.sql.impl.aggregate.SqlAggregateTest): BuildInfo{version='5.5.0-SNAPSHOT', build='20240624', buildNumber=20240624, revision=, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'test_orderByAvg(INTEGER, DECIMAL) [2](com.hazelcast.jet.sql.impl.aggregate.SqlAggregateTest):'
08:09:45, accumulated pauses: 495 ms, max pause: 263 ms, pauses over 1000 ms: 0


No metrics recorded during the test

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-Openj9-21-nightly/24/

**Comment by Patras3** [comment]
Failed again on _5.4.z_ with openj9-21: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-Openj9-21-nightly/8/testReport/com.hazelcast.jet.sql.impl.aggregate/SqlAggregateTest/
