### ISSUE TITLE
com.hazelcast.query.impl.predicates.CompositeIndexVisitorTest, com.hazelcast.query.impl.predicates.EvaluateVisitorTest and RangeVisitorTest and com.hazelcast.query.impl.predicates.RangeVisitorTest[HZ-4820]

### ISSUE THREAD

**Issue by AleksPeychev** [hazelcast/hazelcast#26375]
_master_ (commit 99b6aac3d3ee0aea38c27fabe44927f64ec2a023)

Failed on zing-21: 
 - https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK21/25/testReport/junit/com.hazelcast.query.impl.predicates/CompositeIndexVisitorTest/testUnoptimizablePredicates/
 
 - https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK21/25/testReport/junit/com.hazelcast.query.impl.predicates/CompositeIndexVisitorTest/testOptimizablePredicates/
 
<details><summary>Stacktrace:</summary>

```
java.lang.NullPointerException: Cannot read the array length because "compositeIndexes" is null
	at com.hazelcast.query.impl.predicates.CompositeIndexVisitor.visit(CompositeIndexVisitor.java:51)
	at com.hazelcast.query.impl.predicates.VisitorTestSupport.check(VisitorTestSupport.java:79)
	at com.hazelcast.query.impl.predicates.CompositeIndexVisitorTest.testOptimizablePredicates(CompositeIndexVisitorTest.java:108)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.lang.Thread.run(Thread.java:1584)

```
</details>

<details><summary>Standard output:</summary>

```
Started Running Test: testOptimizablePredicates
Started Running Test: testUnoptimizablePredicates

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-ZingJDK21/25/

--------------------------------------------------------------------------------------------------

_master_ (commit 99b6aac3d3ee0aea38c27fabe44927f64ec2a023)

Failed on zing-21: 
 - https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK21/25/testReport/junit/com.hazelcast.query.impl.predicates/EvaluateVisitorTest/testOptimizablePredicates/
 - https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK21/25/testReport/junit/com.hazelcast.query.impl.predicates/EvaluateVisitorTest/testUnoptimizablePredicates/
<details><summary>Stacktrace:</summary>

```
java.lang.NullPointerException: Cannot invoke "com.hazelcast.query.impl.AttributeIndexRegistry.match(String, com.hazelcast.query.impl.QueryContext$IndexMatchHint)" because "this.evaluateOnlyAttributeIndexRegistry" is null
	at com.hazelcast.query.impl.IndexRegistry.matchIndex(IndexRegistry.java:539)
	at com.hazelcast.query.impl.predicates.EvaluateVisitor.visit(EvaluateVisitor.java:216)
	at com.hazelcast.query.impl.predicates.EqualPredicate.accept(EqualPredicate.java:62)
	at com.hazelcast.query.impl.predicates.EvaluateVisitorTest.optimize(EvaluateVisitorTest.java:375)
	at com.hazelcast.query.impl.predicates.EvaluateVisitorTest.assertNoOptimization(EvaluateVisitorTest.java:198)
	at com.hazelcast.query.impl.predicates.EvaluateVisitorTest.testUnoptimizablePredicates(EvaluateVisitorTest.java:139)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.lang.Thread.run(Thread.java:1584)

```
</details>

<details><summary>Standard output:</summary>

```
Started Running Test: testOptimizablePredicates
Started Running Test: testUnoptimizablePredicates

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-ZingJDK21/25/

------------------------------------------------------------------------------------------------

_master_ (commit 99b6aac3d3ee0aea38c27fabe44927f64ec2a023)

Failed on zing-21: https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK21/25/testReport/junit/com.hazelcast.query.impl.predicates/RangeVisitorTest/
<details><summary>Stacktrace:</summary>

```
java.lang.NullPointerException: Cannot invoke "com.hazelcast.query.impl.ConverterCache.get(String)" because "this.converterCache" is null
	at com.hazelcast.query.impl.IndexRegistry.getConverter(IndexRegistry.java:567)
	at com.hazelcast.query.impl.predicates.RangeVisitor.visit(RangeVisitor.java:64)
	at com.hazelcast.query.impl.predicates.RangeVisitorTest.testBetweenPredicateOptimization(RangeVisitorTest.java:144)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.lang.Thread.run(Thread.java:1584)

```
</details>

<details><summary>Standard output:</summary>

```
Started Running Test: testBetweenPredicateOptimization
Started Running Test: testUnsatisfiablePredicates
Started Running Test: testUnoptimizablePredicates
Started Running Test: testOptimizablePredicates
Started Running Test: testNullsHandling
Started Running Test: testDuplicatesHandling

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-ZingJDK21/25/

**Comment by AleksPeychev** [comment]
Failed again on _master_ with zing-17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZingJDK17/75/testReport/junit/com.hazelcast.query.impl.predicates/EvaluateVisitorTest/testOptimizablePredicates/

**Comment by AleksPeychev** [comment]
Failed again on _master_ with zing-17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZingJDK17/75/testReport/junit/com.hazelcast.query.impl.predicates/EvaluateVisitorTest/testOptimizablePredicates/

**Comment by AleksPeychev** [comment]
Failed again on _master_ with zing-17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZingJDK17/76/testReport/junit/com.hazelcast.query.impl.predicates/EvaluateVisitorTest/testOptimizablePredicates/

**Comment by AleksPeychev** [comment]
Same reason as [this](https://github.com/hazelcast/hazelcast/issues/23517). Anomalous failures caused by Mockito on Zing JDK 17 and 21.
