### ISSUE TITLE
com.hazelcast.jet.JobStatusListenerTest [HZ-4821]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#26377]
_master_ (commit 978f3415aa7bb92b35f8b7a8b9bce528eb150c6d)

Failed on openj9-21: https://jenkins.hazelcast.com/job/Hazelcast-master-Openj9-21-nightly/26/testReport/com.hazelcast.jet/JobStatusListenerTest/

Following tests failed:
- `com.hazelcast.jet.JobStatusListenerTest.testListener_jobFails[onClient]`
- `com.hazelcast.jet.JobStatusListenerTest.testListener_waitForCompletion[onClient]`
- `com.hazelcast.jet.JobStatusListenerTest.testListener_suspend_resume_restart_cancelJob[onClient]`
- `com.hazelcast.jet.JobStatusListenerTest.testListener_suspendOnFailure[onClient]`
- `com.hazelcast.jet.JobStatusListenerTest.testListenerDeregistration[onClient]`
- `com.hazelcast.jet.JobStatusListenerTest.testListener_restartOnException[onClient]`

<details><summary>Stacktrace for testListener_waitForCompletion[onClient], testListener_jobFails[onClient], testListenerDeregistration[onClient]:</summary>

```
java.lang.AssertionError: expected:<[Jet: NOT_RUNNING -> STARTING, Jet: STARTING -> RUNNING, Jet: RUNNING -> COMPLETED]> but was:<[Jet: STARTING -> RUNNING, Jet: STARTING -> RUNNING, Jet: RUNNING -> COMPLETED]>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:120)
	at org.junit.Assert.assertEquals(Assert.java:146)
	at com.hazelcast.jet.JobStatusListenerTest.lambda$assertTailEqualsEventually$9(JobStatusListenerTest.java:309)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1216)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1321)
	at com.hazelcast.jet.JobStatusListenerTest.assertTailEqualsEventually(JobStatusListenerTest.java:305)
	at com.hazelcast.jet.JobStatusListenerTest$TestCase.run(JobStatusListenerTest.java:421)
	at com.hazelcast.jet.JobStatusListenerTest$TestCase.runJob(JobStatusListenerTest.java:399)
	at com.hazelcast.jet.JobStatusListenerTest.testListener_waitForCompletion(JobStatusListenerTest.java:115)
	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.lang.Thread.run(Thread.java:1595)

```
</details>

<details><summary>Stacktrace for testListener_restartOnException[onClient], testListener_suspend_resume_restart_cancelJob[onClient], testListener_suspendOnFailure[onClient]:</summary>

```
java.lang.AssertionError: Expected 'length' to be between 5 and 6, but was 9
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at com.hazelcast.test.HazelcastTestSupport.assertBetween(HazelcastTestSupport.java:1389)
	at com.hazelcast.jet.JobStatusListenerTest.lambda$assertTailEqualsEventually$9(JobStatusListenerTest.java:307)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1216)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1321)
	at com.hazelcast.jet.JobStatusListenerTest.assertTailEqualsEventually(JobStatusListenerTest.java:305)
	at com.hazelcast.jet.JobStatusListenerTest.lambda$testListener_restartOnException$c8cc76b3$1(JobStatusListenerTest.java:175)
	at com.hazelcast.function.BiConsumerEx.accept(BiConsumerEx.java:47)
	at com.hazelcast.jet.JobStatusListenerTest$TestCase.run(JobStatusListenerTest.java:419)
	at com.hazelcast.jet.JobStatusListenerTest$TestCase.runJob(JobStatusListenerTest.java:399)
	at com.hazelcast.jet.JobStatusListenerTest.testListener_restartOnException(JobStatusListenerTest.java:182)
	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.lang.Thread.run(Thread.java:1595)
```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-Openj9-21-nightly/26/

**Comment by olukas** [comment]
Seems to fail constantly.

**Comment by olukas** [comment]
Closing as duplicate of https://github.com/hazelcast/hazelcast/issues/26366
