### ISSUE TITLE
com.hazelcast.topic.impl.reliable.ReliableTopicBasicDistributedTest [HZ-4833]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#26378]
_master_ (commit 978f3415aa7bb92b35f8b7a8b9bce528eb150c6d)

Failed on openj9-21: https://jenkins.hazelcast.com/job/Hazelcast-master-Openj9-21/25/testReport/com.hazelcast.topic.impl.reliable/ReliableTopicBasicDistributedTest/

Following tests failed:
- `com.hazelcast.topic.impl.reliable.ReliableTopicBasicDistributedTest.publishSingle`
- `com.hazelcast.topic.impl.reliable.ReliableTopicBasicDistributedTest.addMessageListener`
- `com.hazelcast.topic.impl.reliable.ReliableTopicBasicDistributedTest.removeMessageListener_whenNonExisting`
- `com.hazelcast.topic.impl.reliable.ReliableTopicBasicDistributedTest.testDestroyTopicRemovesStatistics`
- `com.hazelcast.topic.impl.reliable.ReliableTopicBasicDistributedTest.removeMessageListener_whenExisting`
- `com.hazelcast.topic.impl.reliable.ReliableTopicBasicDistributedTest.statistics`
- `com.hazelcast.topic.impl.reliable.ReliableTopicBasicDistributedTest.testMessageFieldSetCorrectly`
- `com.hazelcast.topic.impl.reliable.ReliableTopicBasicDistributedTest.addRemoveMessageListeners`

<details><summary>Stacktrace:</summary>

```
java.lang.NullPointerException: Cannot invoke "java.lang.Object.toString()" because "value" is null
	at java.base/java.lang.StringConcatHelper.stringOf(StringConcatHelper.java:467)
	at java.base/java.lang.StringConcatHelper.simpleConcat(StringConcatHelper.java:421)
	at com.hazelcast.test.HazelcastTestSupport.randomNameOwnedBy(HazelcastTestSupport.java:536)
	at com.hazelcast.topic.impl.reliable.ReliableTopicAbstractTest.setup(ReliableTopicAbstractTest.java:72)
	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
	at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:366)
	at com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37)
	at com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:103)
	at com.hazelcast.test.metrics.MetricsRule$1.evaluate(MetricsRule.java:64)
	at com.hazelcast.test.HazelcastParallelClassRunner.access$101(HazelcastParallelClassRunner.java:52)
	at com.hazelcast.test.HazelcastParallelClassRunner$TestRunner.run(HazelcastParallelClassRunner.java:168)
	at java.base/java.lang.Thread.run(Thread.java:1595)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-Openj9-21/25/

**Comment by sumnerib** [comment]
Failed again on _5.4.z_ with openj9-21: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-Openj9-21/12/testReport/junit/com.hazelcast.topic.impl.reliable/ReliableTopicBasicDistributedTest/

**Comment by nishaatr** [comment]
Changed Millstone to 5.5.z to ensure 5.5.0 does not report any Open [issues ](https://github.com/issues?page=1&q=is%3Aopen+milestone%3A5.5.0+repo%3Ahazelcast%2Fhazelcast+repo%3Ahazelcast%2Fhazelcast-enterprise+repo%3Ahazelcast%2Fhazelcast-mono+sort%3Acreated-desc)
Please correct as necessary

**Comment by olukas** [comment]
Failed again on _5.5.z_ with openj9-21: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-Openj9-21/14/testReport/com.hazelcast.topic.impl.reliable/ReliableTopicBasicDistributedTest/

**Comment by olukas** [comment]
Failed again on _5.5.z_ with openj9-21: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-Openj9-21/18/testReport/com.hazelcast.topic.impl.reliable/ReliableTopicBasicDistributedTest/
