### ISSUE TITLE
com.hazelcast.jet.sql.impl.connector.kafka.SqlJsonTest

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hazelcast#26383]
_5.4.z_ (commit 707eef12cbc8bf83842d51471db47796b83cbce6)

Failed on oracle-17: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-sonar/473/testReport/junit/com.hazelcast.jet.sql.impl.connector.kafka/SqlJsonTest/___/
<details><summary>Stacktrace:</summary>

```
org.testcontainers.containers.ContainerLaunchException: Container startup failed for image confluentinc/cp-kafka:7.4.0
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:359)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:330)
	at com.hazelcast.jet.kafka.impl.DockerizedKafkaTestSupport.createKafkaCluster0(DockerizedKafkaTestSupport.java:40)
	at com.hazelcast.jet.kafka.impl.KafkaTestSupport.createKafkaCluster(KafkaTestSupport.java:102)
	at com.hazelcast.jet.sql.impl.connector.kafka.KafkaSqlTestSupport.createKafkaCluster(KafkaSqlTestSupport.java:65)
	at com.hazelcast.jet.sql.impl.connector.kafka.KafkaSqlTestSupport.setup(KafkaSqlTestSupport.java:54)
	at com.hazelcast.jet.sql.impl.connector.kafka.KafkaSqlTestSupport.setup(KafkaSqlTestSupport.java:49)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:41)
	at com.hazelcast.test.OverridePropertyRule$1.evaluate(OverridePropertyRule.java:68)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:842)
Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:344)
	... 11 more
Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:563)
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:354)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
	... 12 more
Caused by: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for log output matching '.*\[KafkaServer id=\d+\] started.*'
	at org.testcontainers.containers.wait.strategy.LogMessageWaitStrategy.waitUntilReady(LogMessageWaitStrategy.java:47)
	at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:52)
	at org.testcontainers.containers.GenericContainer.waitUntilContainerStarted(GenericContainer.java:909)
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:500)
	... 14 more

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-5.maintenance-sonar/473/

**Comment by olukas** [comment]
Closing the test failure - it doesn't seem to be related to `master` or the latest maintenance stream `5.5.z`. Feel free to reopen test failure if it occurs on `master` or on the latest maintenance stream.
