### ISSUE TITLE
com.hazelcast.map.merge.MapSplitBrainStressTest.testSplitBrain [HZ-4836]

### ISSUE THREAD

**Issue by Patras3** [hazelcast/hazelcast#26385]
_5.4.z_ (commit f6624178d1b1f75a284b78a8b5cb432350cb0435)

Failed on openj9-21: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-Openj9-21-nightly/13/testReport/com.hazelcast.map.merge/MapSplitBrainStressTest/testSplitBrain/
<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: expected 100 entries in map 55/100 (iteration 7) expected:<100> but was:<93>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at com.hazelcast.map.merge.MapSplitBrainStressTest.lambda$onAfterSplitBrainHealed$0(MapSplitBrainStressTest.java:150)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1200)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1305)
	at com.hazelcast.map.merge.MapSplitBrainStressTest.onAfterSplitBrainHealed(MapSplitBrainStressTest.java:150)
	at com.hazelcast.test.SplitBrainTestSupport.doIteration(SplitBrainTestSupport.java:207)
	at com.hazelcast.test.SplitBrainTestSupport.testSplitBrain(SplitBrainTestSupport.java:195)
	at com.hazelcast.map.merge.MapSplitBrainStressTest.testSplitBrain(MapSplitBrainStressTest.java:102)
	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.lang.Thread.run(Thread.java:1595)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-5.maintenance-Openj9-21-nightly/13/

**Comment by Patras3** [comment]
This comment was automatically generated to summarize test results for the last 30 days.

```

For branch: master
Builds between : 2024-07-03 03:15 - 2024-07-31 03:15
Jobs: 9, Runs: 31, Passed: 28, Failed: 3, Skipped: 0, Fail Ratio: 9.68%
Run on:
+--------------------------------------------------+
| JDK        | PASSED | FAILED | SKIPPED |  RATIO  |
+--------------------------------------------------+
| zing-21    |   3    |   1    |    0    |  25.00% |
| oracle-17  |   4    |   1    |    0    |  20.00% |
| unknown    |   7    |   1    |    0    |  12.50% |
| openj9-21  |   3    |   0    |    0    |   0.00% |
| oracle-21  |   4    |   0    |    0    |   0.00% |
| zing-17    |   3    |   0    |    0    |   0.00% |
| openjdk-17 |   4    |   0    |    0    |   0.00% |
+--------------------------------------------------+
Note: Passing since 2024-07-24 03:15

Builds Timeline:
2024-07-31 03:15 - PASSED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK17-nightly-Esxi7/99/testReport/com.hazelcast.map.merge/MapSplitBrainStressTest/testSplitBrain/
2024-07-31 03:08 - PASSED (oracle-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-OracleJDK21-nightly/28/testReport/com.hazelcast.map.merge/MapSplitBrainStressTest/testSplitBrain/
2024-07-29 03:12 - PASSED (openj9-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-Openj9-21-nightly/29/testReport/com.hazelcast.map.merge/MapSplitBrainStressTest/testSplitBrain/
2024-07-28 18:11 - PASSED (zing-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK21-nightly/32/testReport/com.hazelcast.map.merge/MapSplitBrainStressTest/testSplitBrain/
2024-07-28 12:12 - PASSED (oracle-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-nightly-force-offload/111/testReport/com.hazelcast.map.merge/MapSplitBrainStressTest/testSplitBrain/
2024-07-27 00:07 - PASSED (oracle-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-nightly-little-endian/89/testReport/com.hazelcast.map.merge/MapSplitBrainStressTest/testSplitBrain/
2024-07-26 18:06 - PASSED (zing-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK17-nightly/91/testReport/com.hazelcast.map.merge/MapSplitBrainStressTest/testSplitBrain/
2024-07-26 03:14 - PASSED (openjdk-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-ZuluJDK17-nightly/128/testReport/com.hazelcast.map.merge/MapSplitBrainStressTest/testSplitBrain/
2024-07-24 21:52 - PASSED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-CorrettoJDK17-arm64-nightly/26/testReport/com.hazelcast.map.merge/MapSplitBrainStressTest/testSplitBrain/
2024-07-24 03:15 - FIXED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK17-nightly-Esxi7/98/testReport/com.hazelcast.map.merge/MapSplitBrainStressTest/testSplitBrain/
2024-07-24 03:08 - PASSED (oracle-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-OracleJDK21-nightly/27/testReport/com.hazelcast.map.merge/MapSplitBrainStressTest/testSplitBrain/
2024-07-22 03:12 - PASSED (openj9-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-Openj9-21-nightly/28/testReport/com.hazelcast.map.merge/MapSplitBrainStressTest/testSplitBrain/
2024-07-21 18:11 - FIXED (zing-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK21-nightly/31/testReport/com.hazelcast.map.merge/MapSplitBrainStressTest/testSplitBrain/
2024-07-20 00:07 - FIXED (oracle-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-nightly-little-endian/88/testReport/com.hazelcast.map.merge/MapSplitBrainStressTest/testSplitBrain/
2024-07-19 18:06 - PASSED (zing-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK17-nightly/90/testReport/com.hazelcast.map.merge/MapSplitBrainStressTest/testSplitBrain/
2024-07-19 03:14 - PASSED (openjdk-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-ZuluJDK17-nightly/127/testReport/com.hazelcast.map.merge/MapSplitBrainStressTest/testSplitBrain/
2024-07-17 03:15 - REGRESSION (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK17-nightly-Esxi7/97/testReport/com.hazelcast.map.merge/MapSplitBrainStressTest/testSplitBrain/
2024-07-14 18:11 - REGRESSION (zing-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK21-nightly/30/testReport/com.hazelcast.map.merge/MapSplitBrainStressTest/testSplitBrain/
2024-07-13 00:07 - REGRESSION (oracle-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-nightly-little-endian/87/testReport/com.hazelcast.map.merge/MapSplitBrainStressTest/testSplitBrain/
2024-07-12 03:14 - PASSED (openjdk-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-ZuluJDK17-nightly/126/testReport/com.hazelcast.map.merge/MapSplitBrainStressTest/testSplitBrain/
2024-07-10 21:52 - PASSED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-CorrettoJDK17-arm64-nightly/24/testReport/com.hazelcast.map.merge/MapSplitBrainStressTest/testSplitBrain/
2024-07-10 09:10 - PASSED (zing-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK21-nightly/29/testReport/com.hazelcast.map.merge/MapSplitBrainStressTest/testSplitBrain/
2024-07-10 03:15 - PASSED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK17-nightly-Esxi7/96/testReport/com.hazelcast.map.merge/MapSplitBrainStressTest/testSplitBrain/
2024-07-10 03:08 - PASSED (oracle-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-OracleJDK21-nightly/25/testReport/com.hazelcast.map.merge/MapSplitBrainStressTest/testSplitBrain/
2024-07-08 03:12 - PASSED (openj9-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-Openj9-21-nightly/26/testReport/com.hazelcast.map.merge/MapSplitBrainStressTest/testSplitBrain/
2024-07-06 00:07 - PASSED (oracle-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-nightly-little-endian/86/testReport/com.hazelcast.map.merge/MapSplitBrainStressTest/testSplitBrain/
2024-07-05 18:06 - PASSED (zing-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK17-nightly/88/testReport/com.hazelcast.map.merge/MapSplitBrainStressTest/testSplitBrain/
2024-07-05 03:14 - PASSED (openjdk-17):
    https://jenkins.hazelcast.com/job/Hazelcast-master-ZuluJDK17-nightly/125/testReport/com.hazelcast.map.merge/MapSplitBrainStressTest/testSplitBrain/
2024-07-03 21:52 - PASSED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-CorrettoJDK17-arm64-nightly/23/testReport/com.hazelcast.map.merge/MapSplitBrainStressTest/testSplitBrain/
2024-07-03 03:28 - PASSED (oracle-21):
    https://jenkins.hazelcast.com/job/Hazelcast-master-OracleJDK21-nightly/24/testReport/com.hazelcast.map.merge/MapSplitBrainStressTest/testSplitBrain/
2024-07-03 03:15 - PASSED (unknown):
    https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK17-nightly-Esxi7/95/testReport/com.hazelcast.map.merge/MapSplitBrainStressTest/testSplitBrain/

----------------------------------------

For branch: 5.5.z
Builds between : 2024-07-31 18:08 - 2024-07-31 18:08
Jobs: 1, Runs: 1, Passed: 1, Failed: 0, Skipped: 0, Fail Ratio: 0.00%
Run on:
+--------------------------------------------------+
| JDK        | PASSED | FAILED | SKIPPED |  RATIO  |
+--------------------------------------------------+
| openjdk-17 |   1    |   0    |    0    |   0.00% |
+--------------------------------------------------+

Builds Timeline:
2024-07-31 18:08 - PASSED (openjdk-17):
    https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-ZuluJDK17-nightly/128/testReport/com.hazelcast.map.merge/MapSplitBrainStressTest/testSplitBrain/

----------------------------------------

For branch: 5.4.z
Builds between : 2024-07-03 18:08 - 2024-07-29 18:02
Jobs: 3, Runs: 12, Passed: 11, Failed: 1, Skipped: 0, Fail Ratio: 8.33%
Run on:
+--------------------------------------------------+
| JDK        | PASSED | FAILED | SKIPPED |  RATIO  |
+--------------------------------------------------+
| openj9-21  |   3    |   1    |    0    |  25.00% |
| openjdk-17 |   4    |   0    |    0    |   0.00% |
| oracle-21  |   4    |   0    |    0    |   0.00% |
+--------------------------------------------------+
Note: Passing since 2024-07-27 18:06

Builds Timeline:
2024-07-29 18:02 - PASSED (oracle-21):
    https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-OracleJDK21-nightly/14/testReport/com.hazelcast.map.merge/MapSplitBrainStressTest/testSplitBrain/
2024-07-27 18:06 - REGRESSION (openj9-21):
    https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-Openj9-21-nightly/13/testReport/com.hazelcast.map.merge/MapSplitBrainStressTest/testSplitBrain/
2024-07-24 18:08 - PASSED (openjdk-17):
    https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-ZuluJDK17-nightly/127/testReport/com.hazelcast.map.merge/MapSplitBrainStressTest/testSplitBrain/
2024-07-22 18:02 - PASSED (oracle-21):
    https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-OracleJDK21-nightly/13/testReport/com.hazelcast.map.merge/MapSplitBrainStressTest/testSplitBrain/
2024-07-20 18:06 - PASSED (openj9-21):
    https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-Openj9-21-nightly/12/testReport/com.hazelcast.map.merge/MapSplitBrainStressTest/testSplitBrain/
2024-07-17 18:08 - PASSED (openjdk-17):
    https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-ZuluJDK17-nightly/126/testReport/com.hazelcast.map.merge/MapSplitBrainStressTest/testSplitBrain/
2024-07-15 18:02 - PASSED (oracle-21):
    https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-OracleJDK21-nightly/12/testReport/com.hazelcast.map.merge/MapSplitBrainStressTest/testSplitBrain/
2024-07-13 18:06 - PASSED (openj9-21):
    https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-Openj9-21-nightly/11/testReport/com.hazelcast.map.merge/MapSplitBrainStressTest/testSplitBrain/
2024-07-10 18:08 - PASSED (openjdk-17):
    https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-ZuluJDK17-nightly/125/testReport/com.hazelcast.map.merge/MapSplitBrainStressTest/testSplitBrain/
2024-07-08 18:02 - PASSED (oracle-21):
    https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-OracleJDK21-nightly/11/testReport/com.hazelcast.map.merge/MapSplitBrainStressTest/testSplitBrain/
2024-07-06 18:06 - PASSED (openj9-21):
    https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-Openj9-21-nightly/10/testReport/com.hazelcast.map.merge/MapSplitBrainStressTest/testSplitBrain/
2024-07-03 18:08 - PASSED (openjdk-17):
    https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-ZuluJDK17-nightly/124/testReport/com.hazelcast.map.merge/MapSplitBrainStressTest/testSplitBrain/

----------------------------------------

For branch: 5.2.z
Builds between : 2024-07-06 03:10 - 2024-07-27 03:10
Jobs: 1, Runs: 4, Passed: 4, Failed: 0, Skipped: 0, Fail Ratio: 0.00%
Run on:
+------------------------------------------------+
| JDK      | PASSED | FAILED | SKIPPED |  RATIO  |
+------------------------------------------------+
| oracle-8 |   4    |   0    |    0    |   0.00% |
+------------------------------------------------+

Builds Timeline:
2024-07-27 03:10 - PASSED (oracle-8):
    https://jenkins.hazelcast.com/job/Hazelcast-5.2.z-OracleJDK8-nightly/63/testReport/com.hazelcast.map.merge/MapSplitBrainStressTest/testSplitBrain/
2024-07-20 03:10 - PASSED (oracle-8):
    https://jenkins.hazelcast.com/job/Hazelcast-5.2.z-OracleJDK8-nightly/62/testReport/com.hazelcast.map.merge/MapSplitBrainStressTest/testSplitBrain/
2024-07-13 03:10 - PASSED (oracle-8):
    https://jenkins.hazelcast.com/job/Hazelcast-5.2.z-OracleJDK8-nightly/61/testReport/com.hazelcast.map.merge/MapSplitBrainStressTest/testSplitBrain/
2024-07-06 03:10 - PASSED (oracle-8):
    https://jenkins.hazelcast.com/job/Hazelcast-5.2.z-OracleJDK8-nightly/60/testReport/com.hazelcast.map.merge/MapSplitBrainStressTest/testSplitBrain/

----------------------------------------

For branch: 4.2.z
Builds between : 2024-07-07 12:14 - 2024-07-28 12:14
Jobs: 1, Runs: 4, Passed: 4, Failed: 0, Skipped: 0, Fail Ratio: 0.00%
Run on:
+------------------------------------------------+
| JDK      | PASSED | FAILED | SKIPPED |  RATIO  |
+------------------------------------------------+
| oracle-8 |   4    |   0    |    0    |   0.00% |
+------------------------------------------------+

Builds Timeline:
2024-07-28 12:14 - PASSED (oracle-8):
    https://jenkins.hazelcast.com/job/Hazelcast-4.maintenance-OracleJDK8-nightly/1040/testReport/com.hazelcast.map.merge/MapSplitBrainStressTest/testSplitBrain/
2024-07-21 12:14 - PASSED (oracle-8):
    https://jenkins.hazelcast.com/job/Hazelcast-4.maintenance-OracleJDK8-nightly/1039/testReport/com.hazelcast.map.merge/MapSplitBrainStressTest/testSplitBrain/
2024-07-14 12:14 - PASSED (oracle-8):
    https://jenkins.hazelcast.com/job/Hazelcast-4.maintenance-OracleJDK8-nightly/1038/testReport/com.hazelcast.map.merge/MapSplitBrainStressTest/testSplitBrain/
2024-07-07 12:14 - PASSED (oracle-8):
    https://jenkins.hazelcast.com/job/Hazelcast-4.maintenance-OracleJDK8-nightly/1037/testReport/com.hazelcast.map.merge/MapSplitBrainStressTest/testSplitBrain/

----------------------------------------

For branch: 5.3.z
Builds between : 2024-07-08 03:11 - 2024-07-29 03:11
Jobs: 1, Runs: 4, Passed: 4, Failed: 0, Skipped: 0, Fail Ratio: 0.00%
Run on:
+------------------------------------------------+
| JDK      | PASSED | FAILED | SKIPPED |  RATIO  |
+------------------------------------------------+
| oracle-8 |   4    |   0    |    0    |   0.00% |
+------------------------------------------------+

Builds Timeline:
2024-07-29 03:11 - PASSED (oracle-8):
    https://jenkins.hazelcast.com/job/Hazelcast-5.3.z-OracleJDK8-nightly/13/testReport/com.hazelcast.map.merge/MapSplitBrainStressTest/testSplitBrain/
2024-07-22 03:11 - PASSED (oracle-8):
    https://jenkins.hazelcast.com/job/Hazelcast-5.3.z-OracleJDK8-nightly/12/testReport/com.hazelcast.map.merge/MapSplitBrainStressTest/testSplitBrain/
2024-07-15 03:11 - PASSED (oracle-8):
    https://jenkins.hazelcast.com/job/Hazelcast-5.3.z-OracleJDK8-nightly/11/testReport/com.hazelcast.map.merge/MapSplitBrainStressTest/testSplitBrain/
2024-07-08 03:11 - PASSED (oracle-8):
    https://jenkins.hazelcast.com/job/Hazelcast-5.3.z-OracleJDK8-nightly/10/testReport/com.hazelcast.map.merge/MapSplitBrainStressTest/testSplitBrain/

----------------------------------------
```

**Comment by olukas** [comment]
Closing the test failure - it doesn't seem to be related to `master` or the latest maintenance stream `5.5.z`. Feel free to reopen test failure if it occurs on `master` or on the latest maintenance stream.
