### ISSUE TITLE
com.hazelcast.config.XmlConfigSchemaLocationTest.testSchemaLocationsExist [HZ-4838]

### ISSUE THREAD

**Issue by Patras3** [hazelcast/hazelcast#26389]
_5.5.z_ (commit 05a536adab0fc9939805b2326e4d04be6626a36d)

Failed on oracle-17: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-sonar/481/testReport/com.hazelcast.config/XmlConfigSchemaLocationTest/testSchemaLocationsExist/
<details><summary>Stacktrace:</summary>

```
java.lang.IllegalStateException: Error while validating schema location 'https://maven.apache.org/xsd/maven-4.0.0.xsd' from 'com/hazelcast/client/console/testjob-with-hz-bootstrap/pom.xml'
	at com.hazelcast.config.XmlConfigSchemaLocationTest.validateSchemaLocationUrl(XmlConfigSchemaLocationTest.java:117)
	at com.hazelcast.config.XmlConfigSchemaLocationTest.testSchemaLocationsExist(XmlConfigSchemaLocationTest.java:98)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:842)
Caused by: java.net.ConnectException
	at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:573)
	at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:123)
	at com.hazelcast.config.XmlConfigSchemaLocationTest.getResponseCode(XmlConfigSchemaLocationTest.java:164)
	at com.hazelcast.config.XmlConfigSchemaLocationTest.validateSchemaLocationUrl(XmlConfigSchemaLocationTest.java:115)
	... 6 more
Caused by: java.net.ConnectException
	at java.net.http/jdk.internal.net.http.common.Utils.toConnectException(Utils.java:1055)
	at java.net.http/jdk.internal.net.http.PlainHttpConnection.connectAsync(PlainHttpConnection.java:198)
	at java.net.http/jdk.internal.net.http.PlainHttpConnection.checkRetryConnect(PlainHttpConnection.java:230)
	at java.net.http/jdk.internal.net.http.PlainHttpConnection.lambda$connectAsync$1(PlainHttpConnection.java:206)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	... 1 more
Caused by: java.nio.channels.ClosedChannelException
	at java.base/sun.nio.ch.SocketChannelImpl.ensureOpen(SocketChannelImpl.java:195)
	at java.base/sun.nio.ch.SocketChannelImpl.beginConnect(SocketChannelImpl.java:760)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:848)
	at java.net.http/jdk.internal.net.http.PlainHttpConnection.lambda$connectAsync$0(PlainHttpConnection.java:183)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at java.net.http/jdk.internal.net.http.PlainHttpConnection.connectAsync(PlainHttpConnection.java:185)
	... 9 more

```
</details>

<details><summary>Standard output:</summary>

```
Started Running Test: testSchemaLocationsExist
asym-ssl.xml
log4j2-debug-queue.xml
hazelcast-client-failover-sample.xml
META-INF/platform-knopflerfish/definition-3.4.0.xml
META-INF/platform-equinox/definition-3.4.0.xml
OSGI-INF/io.fabric8.kubernetes.client.osgi.ManagedKubernetesClient.xml
META-INF/platform-equinox/definition-3.8.2.xml
META-INF/platform-felix/definition-4.0.2.xml
auth_X509.xml
hazelcast-default-assembly.xml
META-INF/platform-knopflerfish/definition-2.2.0.xml
azure/test-azure-config.xml
wiremock/org/eclipse/jetty/webapp/webdefault.xml
META-INF/platform-felix/definition-1.0.1.xml
META-INF/platform-felix/definition-4.0.1.xml
META-INF/platform-equinox/definition-3.9.1.xml
fork.xml
azure/test-azure-config-invalid.xml
META-INF/platform-equinox/definition-3.8.1.xml
META-INF/beans.xml
gcp/test-gcp-config-invalid.xml
tunnel.xml
jg-magic-map.xml
log4j2.xml
META-INF/platform-concierge/definition-1.0.0.xml
META-INF/platform-felix/definition-1.0.0.xml
META-INF/platform-felix/definition-2.0.5.xml
META-INF/platform-knopflerfish/definition-2.0.5.xml
hazelcast-client-dummy-multicast-discovery-test.xml
META-INF/platform-felix/definition-1.6.0.xml
META-INF/platform-equinox/definition-3.8.0.xml
META-INF/platform-knopflerfish/definition-2.3.0.xml
tcp-low-latency.xml
auth_regex.xml
hazelcast-querycache-xml-config-wildcard-test.xml
hazelcast-docker-assembly.xml
META-INF/platform-felix/definition-1.6.1.xml
META-INF/platform-felix/definition-4.0.3.xml
hazelcast-multicast-plugin.xml
hazelcast-client-failover-full-example.xml
META-INF/platform-felix/definition-4.2.0.xml
auth_krb5.xml
hazelcast-client-test.xml
com/hazelcast/client/console/hazelcast-client-test.xml
test-hazelcast-jcache-with-split-brain-protection.xml
hazelcast-client-c2.xml
META-INF/platform-felix/definition-3.0.8.xml
META-INF/platform-felix/definition-4.4.1.xml
fast.xml
log4j2-trace-dynamic-map-config-update.xml
test-hazelcast-jcache2.xml
log4j2-trace-default-address-picker.xml
test-hazelcast-discovery-spi-metadata.xml
META-INF/platform-knopflerfish/definition-2.3.2.xml
META-INF/platform-knopflerfish/definition-2.0.3.xml
META-INF/platform-felix/definition-2.0.3.xml
hazelcast-client-failover-sample-with-variable.xml
com/hazelcast/config/jet/jet-config-and-instance-config.xml
udp.xml
test-hazelcast-invalid-cache.xml
META-INF/platform-felix/definition-4.2.1.xml
META-INF/platform-knopflerfish/definition-2.1.1.xml
META-INF/platform-felix/definition-2.0.4.xml
META-INF/platform-knopflerfish/definition-2.0.4.xml
hazelcast-client-querycache-xml-config-wildcard-test.xml
hazelcast-client-c1.xml
META-INF/platform-felix/definition-3.0.7.xml
org/codehaus/groovy/tools/groovydoc/gstringTemplates/classLevel/classDocStructuredData.xml
META-INF/platform-knopflerfish/definition-2.1.0.xml
test-hazelcast-jcache-partition-lost-listener.xml
hazelcast-full-example.xml
META-INF/platform-knopflerfish/definition-2.3.1.xml
groovy/grape/defaultGrapeConfig.xml
log4j2-debug-index-stats.xml
hazelcast-security-hardened.xml
log4j2-debug.xml
aQute/bnd/help/syntax.xml
META-INF/platform-knopflerfish/definition-2.0.1.xml
META-INF/platform-felix/definition-2.0.1.xml
test-hazelcast-real-jcache.xml
sym-encrypt.xml
gcp/test-gcp-config.xml
test-hazelcast-jcache.xml
test-hazelcast-client-jcache.xml
hazelcast-client-discovery-spi-test.xml
META-INF/platform-felix/definition-4.0.0.xml
test-hazelcast-variable.xml
log4j2-debug-cp.xml
META-INF/plexus/components.xml
META-INF/platform-felix/definition-3.0.9.xml
META-INF/platform-knopflerfish/definition-2.3.3.xml
test-hazelcast-client-simple.xml
org/apache/maven/model/pom-4.0.0.xml
tcp-minimal.xml
META-INF/platform-felix/definition-2.0.2.xml
META-INF/platform-knopflerfish/definition-2.0.2.xml
log4j2-trace-graceful-shutdown-correctness.xml
META-INF/platform-felix/definition-4.4.0.xml
logback.xml
settings.xml
org/codehaus/groovy/tools/groovydoc/gstringTemplates/topLevel/rootDocStructuredData.xml
asym-encrypt.xml
META-INF/platform-equinox/definition-3.6.1.xml
log4j2-trace-map-split-brain-stress.xml
test-hazelcast-client-variable.xml
com/hazelcast/config/jet/just-instance-config.xml
META-INF/maven/com.github.stefanbirkner/system-lambda/pom.xml
META-INF/maven/io.netty/netty-codec/pom.xml
META-INF/maven/io.netty/netty-transport-native-kqueue/pom.xml
META-INF/maven/io.github.classgraph/classgraph/pom.xml
META-INF/maven/org.sonatype.aether/aether-util/pom.xml
META-INF/maven/org.ops4j.pax.exam/pax-exam/pom.xml
META-INF/maven/org.apache.activemq/artemis-jakarta-client/pom.xml
META-INF/maven/io.fabric8/mockwebserver/pom.xml
META-INF/maven/org.apache.maven/maven-aether-provider/pom.xml
META-INF/maven/org.jline/jline-reader/pom.xml
META-INF/maven/org.ops4j.pax.exam/pax-exam-container-rbc-client/pom.xml
META-INF/maven/org.apache.maven.resolver/maven-resolver-impl/pom.xml
META-INF/maven/org.ops4j.pax.scanner/pax-scanner-obr/pom.xml
META-INF/maven/jakarta.jms/jakarta.jms-api/pom.xml
META-INF/maven/commons-codec/commons-codec/pom.xml
META-INF/maven/com.zaxxer/HikariCP/pom.xml
META-INF/maven/io.netty/netty-codec-http/pom.xml
META-INF/maven/io.netty/netty-common/pom.xml
META-INF/maven/net.bytebuddy/byte-buddy-agent/pom.xml
META-INF/maven/org.apache.karaf/org.apache.karaf.util/pom.xml
META-INF/maven/org.ops4j.pax.runner/pax-runner-platform-felix/pom.xml
META-INF/maven/org.fusesource.jansi/jansi-native/pom.xml
META-INF/maven/org.ops4j.pax.exam/pax-exam-container-paxrunner/pom.xml
META-INF/maven/org.assertj/assertj-core/pom.xml
META-INF/maven/javax.transaction/javax.transaction-api/pom.xml
META-INF/maven/org.apache.commons/commons-text/pom.xml
META-INF/maven/io.netty/netty-handler-proxy/pom.xml
META-INF/maven/org.ops4j.pax.scanner/pax-scanner-common/pom.xml
META-INF/maven/org.ops4j.pax.exam/pax-exam-junit4/pom.xml
META-INF/maven/org.ops4j.pax.url/pax-url-assembly/pom.xml
META-INF/maven/org.ops4j.base/ops4j-base-io/pom.xml
META-INF/maven/io.fabric8/kubernetes-model-core/pom.xml
META-INF/maven/javax.cache/cache-api/pom.xml
META-INF/maven/com.fasterxml.jackson.core/jackson-databind/pom.xml
com/hazelcast/client/console/testjob-with-hz-bootstrap/pom.xml
01:21:14,298  INFO |testSchemaLocationsExist| - [HazelcastTestSupport] main - Shutting down node factory as @After action
BuildInfo right after testSchemaLocationsExist(com.hazelcast.config.XmlConfigSchemaLocationTest): BuildInfo{version='5.5.1-SNAPSHOT', build='20240801', buildNumber=20240801, revision=, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'testSchemaLocationsExist(com.hazelcast.config.XmlConfigSchemaLocationTest):'
01:16:45, accumulated pauses: 72 ms, max pause: 17 ms, pauses over 1000 ms: 0
01:16:50, accumulated pauses: 52 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:16:55, accumulated pauses: 63 ms, max pause: 3 ms, pauses over 1000 ms: 0
01:17:00, accumulated pauses: 58 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:17:05, accumulated pauses: 59 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:17:10, accumulated pauses: 60 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:17:15, accumulated pauses: 61 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:17:20, accumulated pauses: 61 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:17:25, accumulated pauses: 62 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:17:30, accumulated pauses: 60 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:17:35, accumulated pauses: 59 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:17:40, accumulated pauses: 58 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:17:45, accumulated pauses: 58 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:17:50, accumulated pauses: 58 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:17:55, accumulated pauses: 58 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:18:00, accumulated pauses: 56 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:18:05, accumulated pauses: 57 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:18:10, accumulated pauses: 56 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:18:15, accumulated pauses: 59 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:18:20, accumulated pauses: 58 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:18:25, accumulated pauses: 58 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:18:30, accumulated pauses: 59 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:18:35, accumulated pauses: 59 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:18:40, accumulated pauses: 59 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:18:45, accumulated pauses: 60 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:18:50, accumulated pauses: 57 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:18:55, accumulated pauses: 58 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:19:00, accumulated pauses: 49 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:19:05, accumulated pauses: 48 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:19:10, accumulated pauses: 56 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:19:15, accumulated pauses: 57 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:19:20, accumulated pauses: 57 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:19:25, accumulated pauses: 59 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:19:30, accumulated pauses: 60 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:19:35, accumulated pauses: 56 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:19:40, accumulated pauses: 58 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:19:45, accumulated pauses: 49 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:19:50, accumulated pauses: 46 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:19:55, accumulated pauses: 49 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:20:00, accumulated pauses: 57 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:20:05, accumulated pauses: 54 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:20:10, accumulated pauses: 51 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:20:15, accumulated pauses: 49 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:20:20, accumulated pauses: 52 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:20:25, accumulated pauses: 50 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:20:30, accumulated pauses: 56 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:20:35, accumulated pauses: 56 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:20:40, accumulated pauses: 60 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:20:45, accumulated pauses: 60 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:20:50, accumulated pauses: 61 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:20:55, accumulated pauses: 59 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:21:00, accumulated pauses: 53 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:21:05, accumulated pauses: 61 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:21:10, accumulated pauses: 2536 ms, max pause: 2516 ms, pauses over 1000 ms: 1


No metrics recorded during the test

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-5.maintenance-sonar/481/

**Comment by nishaatr** [comment]
Update milestone to 6.0.0 as PR was for master
