### ISSUE TITLE
com.hazelcast.jet.kafka.impl.WriteKafkaPTest.testWriteToTopicWithDataConnection

### ISSUE THREAD

**Issue by Patras3** [hazelcast/hazelcast#26391]
_5.5.z_ (commit b12eb425b14f697310c5d0e12efcb04d427f1507)

Failed on microsoft-21: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-MicrosoftJDK21/13/testReport/junit/com.hazelcast.jet.kafka.impl/WriteKafkaPTest/testWriteToTopicWithDataConnection/
<details><summary>Stacktrace:</summary>

```
java.lang.RuntimeException: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TopicExistsException: Topic '41fe209d-e2c5-4e31-90e2-08ae394664ad' already exists.
	at com.hazelcast.jet.kafka.impl.KafkaTestSupport.createTopic(KafkaTestSupport.java:134)
	at com.hazelcast.jet.kafka.impl.WriteKafkaPTest.before(WriteKafkaPTest.java:96)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:366)
	at com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37)
	at com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:103)
	at com.hazelcast.test.metrics.MetricsRule$1.evaluate(MetricsRule.java:64)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:53)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:32)
	at com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:41)
	at com.hazelcast.test.OverridePropertyRule$1.evaluate(OverridePropertyRule.java:68)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TopicExistsException: Topic '41fe209d-e2c5-4e31-90e2-08ae394664ad' already exists.
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
	at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:165)
	at com.hazelcast.jet.kafka.impl.KafkaTestSupport.createTopic(KafkaTestSupport.java:132)
	... 12 more
Caused by: org.apache.kafka.common.errors.TopicExistsException: Topic '41fe209d-e2c5-4e31-90e2-08ae394664ad' already exists.

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-5.maintenance-MicrosoftJDK21/13/

**Comment by nishaatr** [comment]
Hi @Patras3 
Can we move this to Mono please?
Prefer we don't create issues here unless there is a very good reason
I have a release post task to cleanup Milestone so makes it little difficult for me
Also, I thought we have moved to JIRA and don't create issues in GH.

**Comment by Patras3** [comment]
> Hi @Patras3 Can we move this to Mono please? Prefer we don't create issues here unless there is a very good reason I have a release post task to cleanup Milestone so makes it little difficult for me Also, I thought we have moved to JIRA and don't create issues in GH.

https://github.com/hazelcast/hazelcast/issues/26415#issuecomment-2360275734
