### ISSUE TITLE
com.hazelcast.cluster.JoinStressTest.testTcpJoin_whenInitialMembersTerminated_duringStartup [HZG-453]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#26397]
_5.5.z_ (commit 49c3b7919dbf0d3258938555f7d2e99d91eb0e79)

Failed on oracle-21: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-OracleJDK21-nightly/15/testReport/com.hazelcast.cluster/JoinStressTest/testTcpJoin_whenInitialMembersTerminated_duringStartup/
<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: Cluster size is not correct. Expected: 2, actual: 1, instance index: 0
	at org.junit.Assert.fail(Assert.java:89)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSize(HazelcastTestSupport.java:1048)
	at com.hazelcast.test.HazelcastTestSupport.lambda$assertClusterSizeEventually$11(HazelcastTestSupport.java:1082)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1216)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1235)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:1082)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:1060)
	at com.hazelcast.cluster.JoinStressTest.testJoin_whenInitialMembersTerminated_duringStartup(JoinStressTest.java:334)
	at com.hazelcast.cluster.JoinStressTest.testTcpJoin_whenInitialMembersTerminated_duringStartup(JoinStressTest.java:294)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.lang.Thread.run(Thread.java:1583)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-5.maintenance-OracleJDK21-nightly/15/

**Comment by AleksPeychev** [comment]
Failed again on _5.4.z_ with oracle-21: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.4.z-OracleJDK17-nightly/44/testReport/com.hazelcast.cluster/JoinStressTest/testTcpJoin_whenInitialMembersTerminated_duringStartup/

**Comment by ethurma** [comment]
Closing as test appears to be passing and stable.
