### ISSUE TITLE
com.hazelcast.test.starter.test.HazelcastVersionLocatorTest.(?) [HZ-4840]

### ISSUE THREAD

**Issue by Patras3** [hazelcast/hazelcast#26390]
_master_ (commit fadb19c04d1334c1182c3ff4dc91435ed3cb3843)

Failed on openjdk-17: https://jenkins.hazelcast.com/job/Hazelcast-master-ZuluJDK17-nightly/129/testReport/com.hazelcast.test.starter.test/HazelcastVersionLocatorTest/___/
<details><summary>Stacktrace:</summary>

```
java.lang.IllegalStateException: Maven dependency:get failed with code 1
	at com.hazelcast.internal.util.Preconditions.checkState(Preconditions.java:353)
	at com.hazelcast.test.starter.MavenInterface.downloadArtifact(MavenInterface.java:121)
	at com.hazelcast.test.starter.MavenInterface.locateArtifact(MavenInterface.java:100)
	at com.hazelcast.test.starter.HazelcastVersionLocator.lambda$locateVersion$0(HazelcastVersionLocator.java:65)
	at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:180)
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.base/java.util.stream.SpinedBuffer$1Splitr.forEachRemaining(SpinedBuffer.java:364)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at com.hazelcast.test.starter.HazelcastVersionLocator.locateVersion(HazelcastVersionLocator.java:64)
	at com.hazelcast.test.starter.test.HazelcastVersionLocatorTest.setUp(HazelcastVersionLocatorTest.java:55)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)

```
</details>

**Comment by AleksPeychev** [comment]
Failed again on _master_ with zing-21: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZingJDK21-nightly/55/testReport/junit/com.hazelcast.test.starter.test/HazelcastVersionLocatorTest/

**Comment by AleksPeychev** [comment]
Failed again on _master_ with oracle-17 (force-offload): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-nightly-force-offload/134/testReport/junit/com.hazelcast.test.starter.test/HazelcastVersionLocatorTest/
