### ISSUE TITLE
Continuous Hazelcast connection errors during k8s restart when using IQueue.take()

### ISSUE THREAD

**Issue by nbatchelder** [hazelcast/hazelcast#26401]
Hi there,

I'm running Hazelcast in a Spring Boot application, and I'm running into connection issues during rolling restarts of the application. When I run the app with the Istio sidecar enabled, I see a log like this every 15s:

```
2024-08-08 22:38:59 - [10.1.14.167]:5701 [hc-minimal] [5.3.5] Connection[id=68, /10.1.14.167:40679->/10.1.14.178:5701, qualifier=null, endpoint=[10.1.14.178]:5701, remoteUuid=null, alive=false, connectionType=NONE, planeIndex=-1] closed. Reason: Exception in Connection[id=68, /10.1.14.167:40679->/10.1.14.178:5701, qualifier=null, endpoint=[10.1.14.178]:5701, remoteUuid=null, alive=true, connectionType=NONE, planeIndex=-1], thread=hz.hc-minimal.IO.thread-in-3
], thread=hz.hc-minimal.IO.thread-in-3
java.net.SocketException: Connection reset
        at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:401)
        at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:434)
        at com.hazelcast.internal.networking.nio.NioInboundPipeline.process(NioInboundPipeline.java:115)
        at com.hazelcast.internal.networking.nio.NioThread.processSelectionKey(NioThread.java:383)
        at com.hazelcast.internal.networking.nio.NioThread.processSelectionKeys(NioThread.java:368)
        at com.hazelcast.internal.networking.nio.NioThread.selectLoop(NioThread.java:294)
        at com.hazelcast.internal.networking.nio.NioThread.executeRun(NioThread.java:249)
        at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:111)
```

However, even without Istio enabled, I am able to see repeated Hazelcast trace logs like the ones below, which indicate that the issue is not due to Istio.
```
2024-08-07 21:10:19 - [10.1.155.20]:5701 [hc-minimal] [5.3.5] Connection to: [10.1.155.51]:5701 streamId:0 is not yet in progress
2024-08-07 21:10:20 - [10.1.155.20]:5701 [hc-minimal] [5.3.5] Connection to: [10.1.155.51]:5701 streamId:0 is already in progress
2024-08-07 21:10:20 - [10.1.155.20]:5701 [hc-minimal] [5.3.5] Connection to: [10.1.155.51]:5701 streamId:0 is already in progress
2024-08-07 21:10:20 - [10.1.155.20]:5701 [hc-minimal] [5.3.5] Connection to: [10.1.155.51]:5701 streamId:0 is already in progress
```

During the initial deployment, the app is fine. However, when I do a rolling restart (`kubectl rollout restart deployment ...`), the hazelcast instance in the new pod connects to the hazelcast instance in the original pod, and when the original pod is taken down, the new instance continuously tries, and fails, to connect to the old one. 

**Note:** In my application, I'm calling `take()` on an `IQueue`. The problem disappears when I switch this `take()` call to a `poll()`. 

**Expected behavior**

[This issue](https://github.com/hazelcast/hazelcast-kubernetes/issues/296) seems very relevant, and based on that discussion, we'd expect to see a series of connection errors during the termination of the original pod. However, in our case, these connection errors persist forever, once every 15s.

**To Reproduce**

I've created a minimal example with reproduce this behavior [here](https://github.com/nbatchelder/hc-minimal). Please let me know if you have any questions on running, and thanks in advance for your help!

**Additional context**
Environment:
```
microk8s v1.27.16
istio 1.20.4
hazelcast 5.3.5
```

**Comment by marquesj2-ppb** [comment]
Did you manage to fix this ?

**Comment by nbatchelder** [comment]
@marquesj2-ppb No I haven't - are you seeing something similar?
