### ISSUE TITLE
com.hazelcast.internal.dynamicconfig.DynamicConfigTest.testMapConfig_withEntryListenerClassName

### ISSUE THREAD

**Issue by Patras3** [hazelcast/hazelcast#26415]
_5.5.z_ (commit 7e84ca5400cfca02b1216e2258d07f3b632416de)

Failed on Windows - MicrosoftJDK17: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-Windows-MicrosoftJDK17/17/testReport/com.hazelcast.internal.dynamicconfig/DynamicConfigTest/testMapConfig_withEntryListenerClassName/
<details><summary>Stacktrace:</summary>

```
org.opentest4j.AssertionFailedError: 

expected: MapConfig{name='29fd9cf8-0f87-4c42-90fc-601a371b13f6', inMemoryFormat='BINARY', metadataPolicy=CREATE_ON_UPDATE, backupCount=1, asyncBackupCount=0, timeToLiveSeconds=0, maxIdleSeconds=0, readBackupData=false, evictionConfig=EvictionConfig{size=2147483647, maxSizePolicy=PER_NODE, evictionPolicy=NONE, comparatorClassName=null, comparator=null}, merkleTree=MerkleTreeConfig{enabled=null, depth=10}, eventJournal=EventJournalConfig{enabled=false, capacity=10000, timeToLiveSeconds=0}, hotRestart=HotRestartConfig{enabled=false, fsync=false}, dataPersistenceConfig=DataPersistenceConfig{enabled=false, fsync=false}, nearCacheConfig=null, mapStoreConfig=MapStoreConfig{enabled=false, className='null', factoryClassName='null', writeDelaySeconds=0, writeBatchSize=1, implementation=null, factoryImplementation=null, properties={}, initialLoadMode=LAZY, writeCoalescing=true, offload=true}, mergePolicyConfig=MergePolicyConfig{policy='com.hazelcast.spi.merge.PutIfAbsentMergePolicy', batchSize=100}, wanReplicationRef=null, entryListenerConfigs=[EntryListenerConfig{local=false, includeValue=true}], indexConfigs=null, attributeConfigs=null, splitBrainProtectionName=null, queryCacheConfigs=null, cacheDeserializedValues=INDEX_ONLY, statisticsEnabled=true, entryStatsEnabled=false, tieredStoreConfig=TieredStoreConfig{enabled=false, memoryTierConfig=MemoryTierConfig{capacity=256 MEGABYTES}, diskTierConfig=DiskTierConfig{enabled=false, deviceName='default-tiered-store-device'}}, partitioningAttributeConfigs=null, userCodeNamespace=null}
 but was: MapConfig{name='29fd9cf8-0f87-4c42-90fc-601a371b13f6', inMemoryFormat='BINARY', metadataPolicy=CREATE_ON_UPDATE, backupCount=1, asyncBackupCount=0, timeToLiveSeconds=0, maxIdleSeconds=0, readBackupData=false, evictionConfig=EvictionConfig{size=2147483647, maxSizePolicy=PER_NODE, evictionPolicy=NONE, comparatorClassName=null, comparator=null}, merkleTree=MerkleTreeConfig{enabled=null, depth=10}, eventJournal=EventJournalConfig{enabled=false, capacity=10000, timeToLiveSeconds=0}, hotRestart=HotRestartConfig{enabled=false, fsync=false}, dataPersistenceConfig=DataPersistenceConfig{enabled=false, fsync=false}, nearCacheConfig=null, mapStoreConfig=MapStoreConfig{enabled=false, className='null', factoryClassName='null', writeDelaySeconds=0, writeBatchSize=1, implementation=null, factoryImplementation=null, properties={}, initialLoadMode=LAZY, writeCoalescing=true, offload=true}, mergePolicyConfig=MergePolicyConfig{policy='com.hazelcast.spi.merge.PutIfAbsentMergePolicy', batchSize=100}, wanReplicationRef=null, entryListenerConfigs=[], indexConfigs=[], attributeConfigs=[], splitBrainProtectionName=null, queryCacheConfigs=[], cacheDeserializedValues=INDEX_ONLY, statisticsEnabled=true, entryStatsEnabled=false, tieredStoreConfig=TieredStoreConfig{enabled=false, memoryTierConfig=MemoryTierConfig{capacity=256 MEGABYTES}, diskTierConfig=DiskTierConfig{enabled=false, deviceName='default-tiered-store-device'}}, partitioningAttributeConfigs=[], userCodeNamespace=null}
	at com.hazelcast.internal.dynamicconfig.DynamicConfigTest.assertConfigurationsEqualOnAllMembers(DynamicConfigTest.java:804)
	at com.hazelcast.internal.dynamicconfig.DynamicConfigTest.assertConfigurationsEqualOnAllMembers(DynamicConfigTest.java:778)
	at com.hazelcast.internal.dynamicconfig.DynamicConfigTest.testMapConfig_withEntryListenerClassName(DynamicConfigTest.java:413)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-5.maintenance-Windows-MicrosoftJDK17/17/

Similar issue was for another test here:
https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-Windows-MicrosoftJDK17/17/testReport/com.hazelcast.internal.dynamicconfig/DynamicConfigTest/testMapConfig_withEntryListenerClassName/

**Comment by nishaatr** [comment]
Hi @Patras3 
Can we move this to Mono?
Prefer we don't create issues here unless there is a very good reason
I have a release post task to cleanup Milestone so makes it little difficult for me
Also, I thought we have moved to JIRA and don't create issues in GH. Also, this has JIRA so any need for GH issue?

**Comment by Patras3** [comment]
> Hi @Patras3 Can we move this to Mono? Prefer we don't create issues here unless there is a very good reason I have a release post task to cleanup Milestone so makes it little difficult for me Also, I thought we have moved to JIRA and don't create issues in GH. Also, this has JIRA so any need for GH issue?

@nishaatr The process of reporting test failures uses OS repository for reporting TF, which appears on the OS version and Mono repo to report EE Test Failures. Nothing was changed in this topic. The whole process is based on reporting in GH, and Jira task is just an addition for developers. The ADR which can change this is being created.

Moreover, what do you mean by "cleanup Milestone"? Test failures are using `x.y.z` / `Backlog` milestone which says on which latest version issue happened, for example, in this case it's `5.5.z` and not `master`.
QEs are responsible for changing Milestone if the latest app version for the issue was changed.

**Comment by Patras3** [comment]
> Moreover, what do you mean by "cleanup Milestone"? Test failures are using `x.y.z` / `Backlog` milestone which says on which latest version issue happened, for example, in this case it's `5.5.z` and not `master`. QEs are responsible for changing Milestone if the latest app version for the issue was changed.

@nishaatr  I just spoke with @olukas and looks like I missed info that TF should be reported now with a `Backlog` milestone, so please ignore above and I will adjust scripts to use `Backlog` now.

**Comment by nishaatr** [comment]
> > Moreover, what do you mean by "cleanup Milestone"? Test failures are using `x.y.z` / `Backlog` milestone which says on which latest version issue happened, for example, in this case it's `5.5.z` and not `master`. QEs are responsible for changing Milestone if the latest app version for the issue was changed.
> 
> @nishaatr I just spoke with @olukas and looks like I missed info that TF should be reported now with a `Backlog` milestone, so please ignore above and I will adjust scripts to use `Backlog` now.

Thanks @Patras3.
