### ISSUE TITLE
com.hazelcast.query.impl.IndexDeserializationTest crashed

### ISSUE THREAD

**Issue by Patras3** [hazelcast/hazelcast#26417]
Crashed on master: https://jenkins.hazelcast.com/job/Hazelcast-master-force-offload/113/console
```
21:13:55  > git checkout -f da3a4cbdb3962dc02b5213e1096d3384929bf510 # timeout=10
21:13:59 Commit message: "Rework new PR Builder DevInfra guard case (#3048)"
```

```
23:25:55 [ERROR] Command was /bin/sh -c cd '/home/jenkins/jenkins_slave/workspace/Hazelcast-master-force-offload/hazelcast/hazelcast' && '/usr/share/jdks/oracle-17/bin/java' '-Xms8g' '-Xmx8g' '--add-exports' 'java.base/jdk.internal.ref=ALL-UNNAMED' '--add-opens' 'jdk.management/com.sun.management.internal=ALL-UNNAMED' '--add-opens' 'java.base/sun.nio.ch=ALL-UNNAMED' '--add-opens' 'java.base/java.lang=ALL-UNNAMED' '--add-opens' 'java.management/sun.management=ALL-UNNAMED' '-Dhazelcast.phone.home.enabled=false' '-Dhazelcast.test.use.network=false' '-Dlog4j.skipJansi=true' '-Dhazelcast.internal.map.force.offload.all.map.operations=true' '-jar' '/home/jenkins/jenkins_slave/workspace/Hazelcast-master-force-offload/hazelcast/hazelcast/target/surefire/surefirebooter-20240825191919312_250.jar' '/home/jenkins/jenkins_slave/workspace/Hazelcast-master-force-offload/hazelcast/hazelcast/target/surefire' '2024-08-25T19-14-36_359-jvmRun1' 'surefire-20240825191919312_248tmp' 'surefire_2-20240825191919312_249tmp'
23:25:55 [ERROR] Process Exit Code: 0
23:25:55 [ERROR] Crashed tests:
23:25:55 [ERROR] com.hazelcast.query.impl.IndexDeserializationTest
23:25:55 [ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
23:25:55 [ERROR] Command was /bin/sh -c cd '/home/jenkins/jenkins_slave/workspace/Hazelcast-master-force-offload/hazelcast/hazelcast' && '/usr/share/jdks/oracle-17/bin/java' '-Xms8g' '-Xmx8g' '--add-exports' 'java.base/jdk.internal.ref=ALL-UNNAMED' '--add-opens' 'jdk.management/com.sun.management.internal=ALL-UNNAMED' '--add-opens' 'java.base/sun.nio.ch=ALL-UNNAMED' '--add-opens' 'java.base/java.lang=ALL-UNNAMED' '--add-opens' 'java.management/sun.management=ALL-UNNAMED' '-Dhazelcast.phone.home.enabled=false' '-Dhazelcast.test.use.network=false' '-Dlog4j.skipJansi=true' '-Dhazelcast.internal.map.force.offload.all.map.operations=true' '-jar' '/home/jenkins/jenkins_slave/workspace/Hazelcast-master-force-offload/hazelcast/hazelcast/target/surefire/surefirebooter-20240825191919312_250.jar' '/home/jenkins/jenkins_slave/workspace/Hazelcast-master-force-offload/hazelcast/hazelcast/target/surefire' '2024-08-25T19-14-36_359-jvmRun1' 'surefire-20240825191919312_248tmp' 'surefire_2-20240825191919312_249tmp'
23:25:55 [ERROR] Process Exit Code: 0
23:25:55 [ERROR] Crashed tests:
23:25:55 [ERROR] com.hazelcast.query.impl.IndexDeserializationTest
23:25:55 [ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:643)
23:25:55 [ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:285)
23:25:55 [ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:250)
23:25:55 [ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1338)
23:25:55 [ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1138)
23:25:55 [ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:972)
23:25:55 [ERROR] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:126)
23:25:55 [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:328)
23:25:55 [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:316)
23:25:55 [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
23:25:55 [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:174)
23:25:55 [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.access$000(MojoExecutor.java:75)
23:25:55 [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor$1.run(MojoExecutor.java:162)
23:25:55 [ERROR] 	at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute(DefaultMojosExecutionStrategy.java:39)
23:25:55 [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:159)
23:25:55 [ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:105)
23:25:55 [ERROR] 	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:193)
23:25:55 [ERROR] 	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:180)
23:25:55 [ERROR] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
23:25:55 [ERROR] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
23:25:55 [ERROR] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
23:25:55 [ERROR] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
23:25:55 [ERROR] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
23:25:55 [ERROR] 	at java.base/java.lang.Thread.run(Thread.java:842)
```

**Comment by olukas** [comment]
Crashed again on _5.5.z_ branch with ZuluJDK17: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-ZuluJDK17/131/consoleFull
