### ISSUE TITLE
com.hazelcast.jet.cdc.mysql.MySqlCdcNetworkIntegrationTest.when_databaseShutdownDuringBinlogReading[reconnect w/ state reset]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#26421]
_master_ (commit 1bf97e0dee8ed1ae66e5d165c4c485b73b508818)

Failed on zing-17: https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK17-nightly/97/testReport/com.hazelcast.jet.cdc.mysql/MySqlCdcNetworkIntegrationTest/

Following tests failed:
- `com.hazelcast.jet.cdc.mysql.MySqlCdcNetworkIntegrationTest.when_databaseShutdownDuringBinlogReading[reconnect w/ state reset]`
- `com.hazelcast.jet.cdc.mysql.MySqlCdcNetworkIntegrationTest.when_noDatabaseToConnectTo[reconnect]`

<details><summary>Stacktrace:</summary>

```
org.testcontainers.containers.ContainerLaunchException: Container startup failed for image debezium/example-mysql:2.3.0.Final
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:359)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:330)
	at com.hazelcast.jet.cdc.mysql.MySqlCdcNetworkIntegrationTest.initMySql(MySqlCdcNetworkIntegrationTest.java:352)
	at com.hazelcast.jet.cdc.mysql.MySqlCdcNetworkIntegrationTest.when_databaseShutdownDuringBinlogReading(MySqlCdcNetworkIntegrationTest.java:287)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:898)
Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:344)
	... 8 more
Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:563)
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:354)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
	... 9 more
Caused by: com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"driver failed programming external connectivity on endpoint MySqlCdcNetworkIntegrationTest.when_databaseShutdownDuringBinlogReading_reconnect_w__state_reset____6907d4cd-7136-49c2-b03a-5dac95e81af2 (5b984c40aafb97dfe3bda3dd97972f8f65bd93a53cbb4729c13809f9279fe2f2): Bind for :::33647 failed: port is already allocated"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247)
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.post(DefaultInvocationBuilder.java:102)
	at org.testcontainers.shaded.com.github.dockerjava.core.exec.StartContainerCmdExec.execute(StartContainerCmdExec.java:31)
	at org.testcontainers.shaded.com.github.dockerjava.core.exec.StartContainerCmdExec.execute(StartContainerCmdExec.java:13)
	at org.testcontainers.shaded.com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21)
	at org.testcontainers.shaded.com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:33)
	at org.testcontainers.shaded.com.github.dockerjava.core.command.StartContainerCmdImpl.exec(StartContainerCmdImpl.java:42)
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:452)
	... 11 more

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-ZingJDK17-nightly/97/

**Comment by olukas** [comment]
Failed again on _5.5.z_ with openj9-21: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-Openj9-21-nightly/18/testReport/com.hazelcast.jet.cdc.mysql/MySqlCdcNetworkIntegrationTest/when_databaseShutdownDuringSnapshotting_reconnect_/
