### ISSUE TITLE
com.hazelcast.jet.sql.impl.connector.kafka.SqlAvroSchemaEvolutionTest

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#26432]
_5.5.z_ (commit 4af18c0d4df1e230f04756845cbf6d96225e092e)

Failed on openjdk-17: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-ZuluJDK17-nightly/135/testReport/com.hazelcast.jet.sql.impl.connector.kafka/SqlAvroSchemaEvolutionTest/

Following tests failed:
- `com.hazelcast.jet.sql.impl.connector.kafka.SqlAvroSchemaEvolutionTest.test_useLatestSchema[TopicNameStrategy, updateMapping=[true]]`
- `com.hazelcast.jet.sql.impl.connector.kafka.SqlAvroSchemaEvolutionTest.test_useLatestSchema[TopicRecordNameStrategy, updateMapping=[false]]`
- `com.hazelcast.jet.sql.impl.connector.kafka.SqlAvroSchemaEvolutionTest.test_useLatestSchema[TopicRecordNameStrategy, updateMapping=[true]]`
- `com.hazelcast.jet.sql.impl.connector.kafka.SqlAvroSchemaEvolutionTest.test_useLatestSchema[RecordNameStrategy, updateMapping=[false]]`
- `com.hazelcast.jet.sql.impl.connector.kafka.SqlAvroSchemaEvolutionTest.test_useLatestSchema[RecordNameStrategy, updateMapping=[true]]`
- `com.hazelcast.jet.sql.impl.connector.kafka.SqlAvroSchemaEvolutionTest.test_autoRegisterSchema[TopicNameStrategy, updateMapping=[false]]`
- `com.hazelcast.jet.sql.impl.connector.kafka.SqlAvroSchemaEvolutionTest.test_autoRegisterSchema[TopicNameStrategy, updateMapping=[true]]`
- `com.hazelcast.jet.sql.impl.connector.kafka.SqlAvroSchemaEvolutionTest.test_autoRegisterSchema[TopicRecordNameStrategy, updateMapping=[false]]`
- `com.hazelcast.jet.sql.impl.connector.kafka.SqlAvroSchemaEvolutionTest.test_autoRegisterSchema[TopicRecordNameStrategy, updateMapping=[true]]`
- `com.hazelcast.jet.sql.impl.connector.kafka.SqlAvroSchemaEvolutionTest.test_autoRegisterSchema[RecordNameStrategy, updateMapping=[false]]`
- `com.hazelcast.jet.sql.impl.connector.kafka.SqlAvroSchemaEvolutionTest.test_autoRegisterSchema[RecordNameStrategy, updateMapping=[true]]`
- `com.hazelcast.jet.sql.impl.connector.kafka.SqlAvroSchemaEvolutionTest.test_useSpecificSchema[TopicNameStrategy, updateMapping=[false]]`
- `com.hazelcast.jet.sql.impl.connector.kafka.SqlAvroSchemaEvolutionTest.test_useSpecificSchema[TopicNameStrategy, updateMapping=[true]]`
- `com.hazelcast.jet.sql.impl.connector.kafka.SqlAvroSchemaEvolutionTest.test_useSpecificSchema[TopicRecordNameStrategy, updateMapping=[false]]`
- `com.hazelcast.jet.sql.impl.connector.kafka.SqlAvroSchemaEvolutionTest.test_useSpecificSchema[TopicRecordNameStrategy, updateMapping=[true]]`
- `com.hazelcast.jet.sql.impl.connector.kafka.SqlAvroSchemaEvolutionTest.test_useSpecificSchema[RecordNameStrategy, updateMapping=[false]]`
- `com.hazelcast.jet.sql.impl.connector.kafka.SqlAvroSchemaEvolutionTest.test_useSpecificSchema[RecordNameStrategy, updateMapping=[true]]`

<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: expected:<2> but was:<4>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at com.hazelcast.jet.sql.impl.connector.kafka.SqlAvroSchemaEvolutionTest.insertAndAssertRecords(SqlAvroSchemaEvolutionTest.java:245)
	at com.hazelcast.jet.sql.impl.connector.kafka.SqlAvroSchemaEvolutionTest.test_useLatestSchema(SqlAvroSchemaEvolutionTest.java:174)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:840)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-5.maintenance-ZuluJDK17-nightly/135/

**Comment by olukas** [comment]
Failed again on _5.5.z_ with:
- openj9-21: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-Openj9-21-nightly/22/testReport/com.hazelcast.jet.sql.impl.connector.kafka/SqlAvroSchemaEvolutionTest/
- openjdk-17: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-ZuluJDK17-nightly/136/testReport/com.hazelcast.jet.sql.impl.connector.kafka/SqlAvroSchemaEvolutionTest/
- oracle-21: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-OracleJDK21-nightly/22/testReport/com.hazelcast.jet.sql.impl.connector.kafka/SqlAvroSchemaEvolutionTest/

**Comment by AleksPeychev** [comment]
Failed again on _5.5.z_ with oracle-21: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-OracleJDK21-nightly/23/testReport/junit/com.hazelcast.jet.sql.impl.connector.kafka/SqlAvroSchemaEvolutionTest/

**Comment by AleksPeychev** [comment]
Failed again on _5.5.z_ with openjdk-17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-ZuluJDK17-nightly/138/testReport/junit/com.hazelcast.jet.sql.impl.connector.kafka/SqlAvroSchemaEvolutionTest/test_useLatestSchema_TopicRecordNameStrategy__updateMapping__true__/

**Comment by AleksPeychev** [comment]
Failed again on _5.5.z_ with openj9-21: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-Openj9-21-nightly/24/testReport/junit/com.hazelcast.jet.sql.impl.connector.kafka/SqlAvroSchemaEvolutionTest/test_autoRegisterSchema_TopicNameStrategy__updateMapping__false__/

**Comment by sumnerib** [comment]
Failed again on _5.5.z_ with openjdk-17: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-ZuluJDK17-nightly/139/testReport/com.hazelcast.jet.sql.impl.connector.kafka/SqlAvroSchemaEvolutionTest/

**Comment by sumnerib** [comment]
Failed again on _5.5.z_ with openj9-21: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-Openj9-21-nightly/25/testReport/com.hazelcast.jet.sql.impl.connector.kafka/SqlAvroSchemaEvolutionTest/

**Comment by sumnerib** [comment]
Fails constantly on `openj9-21`

**Comment by sumnerib** [comment]
Failed again on _5.5.z_ with oracle-21: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-OracleJDK21-nightly/26/testReport/com.hazelcast.jet.sql.impl.connector.kafka/SqlAvroSchemaEvolutionTest/

**Comment by AleksPeychev** [comment]
Failed again on _5.5.3_ with oracle --version-by-pom: https://jenkins.hazelcast.com/view/Release/job/Hazelcast-5.releaseBranch-nightly-FIPS/2/testReport/junit/com.hazelcast.jet.sql.impl.connector.kafka/SqlAvroSchemaEvolutionTest/

**Comment by AleksPeychev** [comment]
Failed again on _5.5.4_ with oracle --version-by-pom: https://jenkins.hazelcast.com/view/Release/job/Hazelcast-5.releaseBranch-nightly/20/testReport/junit/com.hazelcast.jet.sql.impl.connector.kafka/SqlAvroSchemaEvolutionTest/

**Comment by alaktionov** [comment]
Failed again on 5.5.5 with oracle --version-by-pom: https://jenkins.hazelcast.com/view/Release/job/Hazelcast-5.releaseBranch-nightly/21/testReport/junit/com.hazelcast.jet.sql.impl.connector.kafka/SqlAvroSchemaEvolutionTest/

**Comment by AleksPeychev** [comment]
Failed again on _5.5.z_ with : 
 - openjdk-17: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-ZuluJDK17-nightly/170/testReport/com.hazelcast.jet.sql.impl.connector.kafka/SqlAvroSchemaEvolutionTest/
 - oracle-21: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-OracleJDK21-nightly/56/testReport/com.hazelcast.jet.sql.impl.connector.kafka/SqlAvroSchemaEvolutionTest/
 - openj9-21: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-Openj9-21-nightly/54/testReport/com.hazelcast.jet.sql.impl.connector.kafka/SqlAvroSchemaEvolutionTest/
 - openjdk-17: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-ZuluJDK17-nightly/169/testReport/com.hazelcast.jet.sql.impl.connector.kafka/SqlAvroSchemaEvolutionTest/
 - oracle-21: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-OracleJDK21-nightly/55/testReport/com.hazelcast.jet.sql.impl.connector.kafka/SqlAvroSchemaEvolutionTest/
 - openj9-21: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-Openj9-21-nightly/53/testReport/com.hazelcast.jet.sql.impl.connector.kafka/SqlAvroSchemaEvolutionTest/

**Comment by AleksPeychev** [comment]
Failed again on _5.5.6_ with oracle --version-by-pom: https://jenkins.hazelcast.com/view/Release/job/Hazelcast-5.releaseBranch-nightly/23/testReport/junit/com.hazelcast.jet.sql.impl.connector.kafka/SqlAvroSchemaEvolutionTest/

**Comment by k-jamroz** [comment]
There was a similar test failure, already fixed on master: https://github.com/hazelcast/hazelcast/issues/26296

**Comment by k-jamroz** [comment]
In particular this comment reports similar stack trace: https://github.com/hazelcast/hazelcast/issues/26296#issuecomment-2243026704

**Comment by AleksPeychev** [comment]
On master `test_useSpecificSchema` and all its variants are skipped on all JDKs with message
`(key|value).schema.id configs are not supported currently. Key/value-specific serializer configs will be implemented by HZG-53.
`
https://jenkins.hazelcast.com/job/Hazelcast-master-CorrettoJDK17-arm64-nightly/68/testReport/com.hazelcast.jet.sql.impl.connector.kafka/SqlAvroSchemaEvolutionTest/

**Comment by AleksPeychev** [comment]
Validated on [ZuluJDK17](https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-ZuluJDK17-nightly/171/testReport/com.hazelcast.jet.sql.impl.connector.kafka/SqlAvroSchemaEvolutionTest/) that all variants of SqlAvroSchemaEvolutionTest.test_autoRegisterSchema and test_useLatestSchema are fixed and that SqlAvroSchemaEvolutionTest.test_useSpecificSchema is disabled the reason why is [here](https://github.com/hazelcast/hazelcast-mono/pull/2764).
