### ISSUE TITLE
com.hazelcast.map.impl.recordstore.expiry.ExpirySystemTest.testAddWhenTTLIsUnsetDoesNotStoreForExpiration

### ISSUE THREAD

**Issue by AleksPeychev** [hazelcast/hazelcast#26438]
_master_ (commit 68a09bd22672e0a4c519abbb22ff921cefa14717)

Failed on zing-17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZingJDK17/75/testReport/junit/com.hazelcast.map.impl.recordstore.expiry/ExpirySystemTest/testAddWhenTTLIsUnsetDoesNotStoreForExpiration/
<details><summary>Stacktrace:</summary>

```
java.lang.NumberFormatException: Cannot parse null string
	at java.base/java.lang.Long.parseLong(Long.java:674)
	at java.base/java.lang.Long.parseLong(Long.java:836)
	at com.hazelcast.spi.properties.HazelcastProperties.getLong(HazelcastProperties.java:209)
	at com.hazelcast.spi.properties.HazelcastProperties.getMillis(HazelcastProperties.java:255)
	at com.hazelcast.map.impl.recordstore.expiry.ExpirySystemImpl.<init>(ExpirySystemImpl.java:93)
	at com.hazelcast.map.impl.recordstore.expiry.ExpirySystemTest.setUp(ExpirySystemTest.java:87)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.mockito.internal.runners.DefaultInternalRunner$1$1.evaluate(DefaultInternalRunner.java:55)
	at org.mockito.internal.runners.DefaultInternalRunner$1.run(DefaultInternalRunner.java:100)
	at org.mockito.internal.runners.DefaultInternalRunner.run(DefaultInternalRunner.java:107)
	at org.mockito.internal.runners.StrictRunner.run(StrictRunner.java:42)
	at org.mockito.junit.MockitoJUnitRunner.run(MockitoJUnitRunner.java:163)

```
</details>

**Comment by sumnerib** [comment]
Failed again on _master_ with zing-21: https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK21/41/testReport/com.hazelcast.map.impl.recordstore.expiry/ExpirySystemTest/
