### ISSUE TITLE
com.hazelcast.multimap.MultiMapTest

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#26431]
_master_ (commit 4bae3019c201de10da4126731b35a1afa9612991)

Failed on OpenJDK17: https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK17-Esxi7/107/testReport/com.hazelcast.multimap/MultiMapTest/

Following tests failed:
- `com.hazelcast.multimap.MultiMapTest.testPutGetRemoveWhileCollectionTypeList`
- `com.hazelcast.multimap.MultiMapTest.testPutGetRemoveWhileCollectionTypeSet`
- `com.hazelcast.multimap.MultiMapTest.testCollectionInterfaceMethods`

<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: expected:<4> but was:<3>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at com.hazelcast.multimap.MultiMapTest.testPutGetRemoveWhileCollectionTypeList(MultiMapTest.java:661)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:840)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-OpenJDK17-Esxi7/107/

**Comment by sumnerib** [comment]
Failed again on _master_ with OpenJDK17 (Esxi7): https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK17-Esxi7/113/testReport/com.hazelcast.multimap/MultiMapTest/

**Comment by AleksPeychev** [comment]
Failed again on _master_ with OpenJDK17 (Esxi7): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-OpenJDK17-Esxi7/120/testReport/junit/com.hazelcast.multimap/MultiMapTest/testPutGetRemoveWhileCollectionTypeSet/
