### ISSUE TITLE
com.hazelcast.internal.util.phonehome.PhoneHomeIntegrationTest.testForViridian and testDownloadIdOverriddenWithEnvVar

### ISSUE THREAD

**Issue by AleksPeychev** [hazelcast/hazelcast#26439]
_master_ (commit 68a09bd22672e0a4c519abbb22ff921cefa14717)

Failed on zing-17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZingJDK17/75/testReport/junit/com.hazelcast.internal.util.phonehome/PhoneHomeIntegrationTest/testForViridian/
<details><summary>Stacktrace:</summary>

```
com.github.tomakehurst.wiremock.client.VerificationException: 
No requests exactly matched. Most similar request was:  expected:<
POST
/ping

[contains]
vrd=SERVERLESS> but was:<
POST
/ping


jet=true&jetrsup=false&jetjobss=0&cld=A&dck=K&mmct=0&mmcta=0&tpct=0&tpcta=0&figct=0&figcta=0&sect=0&secta=0&quct=0&qucta=0&lict=0&licta=0&cact=0&cacta=0&rpct=0&rpcta=0&pncct=0&pnccta=0&rbct=0&rbcta=0&cect=0&cecta=0&mpct=0&mpcta=0&allmembersclients=0&singlememberclients=0&multimemberclients=0&m=7a769e20-496d-492e-a08f-5108bfb18e66&c=d33b2406-742a-468c-9f7c-14d00a06ecba&crsz=A&ecrsz=1&cuptm=352&nuptm=2177624&jvmn=Zing+64-Bit+Tiered+VM&parct=271&p=source&jvmv=17.0.10.0.101&version=6.0.0-SNAPSHOT&classpath=hazelcast-tpc-engine-6.0.0-SNAPSHOT.jar%2Cjctools-core-4.0.5.jar%2Cslf4j-api-2.0.16.jar%2Cjackson-core-2.17.2.jar%2Cjackson-jr-objects-2.17.2.jar%2Cjackson-jr-annotation-support-2.17.2.jar%2Cjackson-annotations-2.17.2.jar%2Csnakeyaml-engine-2.8.jar%2Cobjenesis-3.4.jar%2Cclassgraph-4.8.177.jar%2Ceverit-json-schema-1.14.4.jar%2Cjson-20231013.jar%2Cpicocli-4.7.6.jar%2Cjline-terminal-3.27.0.jar%2Cjline-native-3.27.0.jar%2Cjline-reader-3.27.0.jar%2Csystem-lambda-1.2.1.jar%2Cjakarta.jms-api-3.1.0.jar%2Ccache-tests-1.1.1-tests.jar%2Chamcrest-core-3.0.jar%2Chamcrest-3.0.jar%2Ccache-tests-1.1.1.jar%2Creload4j-1.2.25.jar%2Clog4j-api-2.24.1.jar%2Clog4j-core-2.24.1.jar%2Cspymemcached-2.12.3.jar%2Ctransactions-jdbc-3.9.3.jar%2Ctransactions-jta-3.9.3.jar%2Ctransactions-3.9.3.jar%2Ctransactions-api-3.9.3.jar%2Catomikos-util-3.9.3.jar%2Cjavax.transaction-api-1.3.jar%2Corg.osgi.core-4.2.0.jar%2Cgroovy-all-2.4.21.jar%2Cpax-exam-junit4-2.6.0.jar%2Cpax-exam-spi-2.6.0.jar%2Casm-3.0.jar%2Cguava-33.3.0-jre.jar%2Cfailureaccess-1.0.2.jar%2Clistenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar%2Cerror_prone_annotations-2.33.0.jar%2Cj2objc-annotations-3.0.0.jar%2Ctinybundles-1.0.0.jar%2Cbndlib-1.43.0.jar%2Cops4j-base-lang-1.4.0.jar%2Cpax-exam-container-paxrunner-2.6.0.jar%2Cpax-exam-2.6.0.jar%2Cops4j-base-store-1.4.0.jar%2Cops4j-base-util-property-1.4.0.jar%2Cpax-exam-container-remote-2.6.0.jar%2Cpax-swissbox-core-1.5.1.jar%2Cpax-swissbox-lifecycle-1.5.1.jar%2Cpax-exam-container-rbc-client-2.6.0.jar%2Cpax-exam-container-rbc-2.6.0.jar%2Cops4j-base-io-1.4.0.jar%2Cops4j-base-net-1.4.0.jar%2Cops4j-base-monitors-1.4.0.jar%2Ccommons-logging-api-1.1.jar%2Cpax-exam-link-mvn-2.6.0.jar%2Cpax-runner-no-jcl-1.8.6.jar%2Cjavax.inject-1.jar%2CHdrHistogram-2.2.2.jar%2Cartemis-core-client-2.37.0.jar%2Cjgroups-5.3.10.Final.jar%2Cnetty-transport-native-epoll-4.1.114.Final-linux-x86_64.jar%2Cnetty-transport-native-unix-common-4.1.114.Final.jar%2Cnetty-transport-classes-epoll-4.1.114.Final.jar%2Cnetty-transport-native-kqueue-4.1.114.Final-osx-x86_64.jar%2Cnetty-transport-classes-kqueue-4.1.114.Final.jar%2Cnetty-codec-http-4.1.114.Final.jar%2Cnetty-buffer-4.1.114.Final.jar%2Cnetty-transport-4.1.114.Final.jar%2Cnetty-handler-4.1.114.Final.jar%2Cnetty-handler-proxy-4.1.114.Final.jar%2Cnetty-codec-4.1.114.Final.jar%2Cnetty-codec-socks-4.1.114.Final.jar%2Cnetty-common-4.1.114.Final.jar%2Cnetty-resolver-4.1.114.Final.jar%2Cpem-keystore-2.4.0.jar%2Cbcprov-jdk18on-1.78.jar%2Cbcpkix-jdk18on-1.78.jar%2Cbcutil-jdk18on-1.78.jar%2Cartemis-jakarta-client-2.37.0.jar%2Cartemis-selector-2.37.0.jar%2Cartemis-server-2.37.0.jar%2Ccaffeine-3.1.8.jar%2Cartemis-jdbc-store-2.37.0.jar%2Ccommons-dbcp2-2.12.0.jar%2Ccommons-pool2-2.12.0.jar%2Cartemis-lockmanager-api-2.37.0.jar%2Ccommons-beanutils-1.9.4.jar%2Ccommons-logging-1.3.4.jar%2Ccommons-lang3-3.17.0.jar%2Ccommons-configuration2-2.11.0.jar%2Ccommons-text-1.12.0.jar%2Ccommons-collections-3.2.2.jar%2Cmicrometer-core-1.13.3.jar%2Cmicrometer-commons-1.13.3.jar%2Cmicrometer-observation-1.13.3.jar%2Cartemis-journal-2.37.0.jar%2Cactivemq-artemis-native-2.0.0.jar%2Cartemis-commons-2.37.0.jar%2Cartemis-jakarta-service-extensions-2.37.0.jar%2Cjakarta.transaction-api-2.0.1.jar%2Cartemis-junit-2.37.0.jar%2Cartemis-junit-commons-2.37.0.jar%2Cartemis-jms-server-2.37.0.jar%2Cartemis-service-extensions-2.37.0.jar%2Crabbitmq-1.20.2.jar%2Ctestcontainers-1.20.2.jar%2Ccommons-compress-1.27.1.jar%2Cduct-tape-1.0.8.jar%2Cdocker-java-api-3.4.0.jar%2Cdocker-java-transport-zerodep-3.4.0.jar%2Cdocker-java-transport-3.4.0.jar%2Cjna-5.15.0.jar%2Crabbitmq-jms-3.3.0.jar%2Camqp-client-5.22.0.jar%2Ch2-2.3.232.jar%2Cpostgresql-1.20.2.jar%2Cjdbc-1.20.2.jar%2Cdatabase-commons-1.20.2.jar%2Cmysql-1.20.2.jar%2Cmssqlserver-1.20.2.jar%2Cmariadb-1.20.2.jar%2Cpostgresql-42.7.4.jar%2Cchecker-qual-3.48.0.jar%2Cmysql-connector-j-9.0.0.jar%2Cprotobuf-java-3.25.3.jar%2Cmssql-jdbc-12.8.1.jre11.jar%2Coracle-xe-1.20.2.jar%2Coracle-free-1.20.2.jar%2Cojdbc11-23.5.0.24.07.jar%2Ckotlin-stdlib-2.0.20.jar%2Cannotations-13.0.jar%2Cwiremock-standalone-3.9.1.jar%2Chazelcast-archunit-rules-6.0.0-SNAPSHOT.jar%2Carchunit-1.3.0.jar%2CHikariCP-6.0.0.jar%2Ckubernetes-server-mock-6.13.4.jar%2Cmockwebserver-6.13.4.jar%2Cmockwebserver-3.12.12.jar%2Cokhttp-3.12.12.jar%2Cokio-1.15.0.jar%2Cjackson-databind-2.17.2.jar%2Czjsonpatch-0.3.0.jar%2Cservicecatalog-client-6.13.4.jar%2Cservicecatalog-model-6.13.4.jar%2Ckubernetes-model-core-6.13.4.jar%2Ckubernetes-model-common-6.13.4.jar%2Ckubernetes-client-6.13.4.jar%2Ckubernetes-httpclient-okhttp-6.13.4.jar%2Clogging-interceptor-3.12.12.jar%2Ckubernetes-client-api-6.13.4.jar%2Ckubernetes-model-gatewayapi-6.13.4.jar%2Ckubernetes-model-resource-6.13.4.jar%2Ckubernetes-model-rbac-6.13.4.jar%2Ckubernetes-model-admissionregistration-6.13.4.jar%2Ckubernetes-model-apps-6.13.4.jar%2Ckubernetes-model-autoscaling-6.13.4.jar%2Ckubernetes-model-apiextensions-6.13.4.jar%2Ckubernetes-model-batch-6.13.4.jar%2Ckubernetes-model-certificates-6.13.4.jar%2Ckubernetes-model-coordination-6.13.4.jar%2Ckubernetes-model-discovery-6.13.4.jar%2Ckubernetes-model-events-6.13.4.jar%2Ckubernetes-model-extensions-6.13.4.jar%2Ckubernetes-model-flowcontrol-6.13.4.jar%2Ckubernetes-model-networking-6.13.4.jar%2Ckubernetes-model-metrics-6.13.4.jar%2Ckubernetes-model-policy-6.13.4.jar%2Ckubernetes-model-scheduling-6.13.4.jar%2Ckubernetes-model-storageclass-6.13.4.jar%2Ckubernetes-model-node-6.13.4.jar%2Cjackson-dataformat-yaml-2.17.2.jar%2Csnakeyaml-2.3.jar%2Cjackson-datatype-jsr310-2.17.2.jar%2Cmaven-resolver-provider-3.9.9.jar%2Cmaven-model-3.9.9.jar%2Cmaven-model-builder-3.9.9.jar%2Cplexus-interpolation-1.27.jar%2Cmaven-artifact-3.9.9.jar%2Cmaven-builder-support-3.9.9.jar%2Corg.eclipse.sisu.inject-0.9.0.M3.jar%2Cmaven-repository-metadata-3.9.9.jar%2Cmaven-resolver-api-1.9.22.jar%2Cmaven-resolver-spi-1.9.22.jar%2Cmaven-resolver-util-1.9.22.jar%2Cmaven-resolver-impl-1.9.22.jar%2Cmaven-resolver-named-locks-1.9.22.jar%2Cplexus-utils-3.5.1.jar%2Ccommons-io-2.17.0.jar%2Ccommons-codec-1.17.1.jar%2Ccache-api-1.1.1.jar%2Cjunit-jupiter-engine-5.11.1.jar%2Cjunit-platform-engine-1.11.1.jar%2Copentest4j-1.3.0.jar%2Cjunit-platform-commons-1.11.1.jar%2Cjunit-jupiter-api-5.11.1.jar%2Capiguardian-api-1.1.2.jar%2Cjunit-vintage-engine-5.11.1.jar%2Cjunit-4.13.2.jar%2Cjunit-jupiter-params-5.11.1.jar%2Cjunit-pioneer-2.2.0.jar%2Cjunit-platform-launcher-1.11.1.jar%2Cassertj-core-3.26.3.jar%2Csystem-stubs-jupiter-2.1.7.jar%2Csystem-stubs-core-2.1.7.jar%2Csystem-stubs-junit4-2.1.7.jar%2Cmockito-core-5.14.1.jar%2Cmockito-junit-jupiter-5.14.1.jar%2Creflections-0.10.2.jar%2Cjavassist-3.30.2-GA.jar%2Cjsr305-3.0.2.jar%2Cspotbugs-annotations-4.8.6.jar%2Cbyte-buddy-1.15.3.jar%2Cbyte-buddy-agent-1.15.3.jar%2Cequalsverifier-3.17.1.jar%2Ctomcat-embed-core-10.1.20.jar%2Ctomcat-annotations-api-10.1.20.jar&cjv=0&cjvco=0&cjvcc=0&cjvtcd=0&cjvcv=&cdn=0&cdnco=0&cdncc=0&cdntcd=0&cdncv=&ccpp=0&ccppco=0&ccppcc=0&ccpptcd=0&ccppcv=&cnjs=0&cnjsco=0&cnjscc=0&cnjstcd=0&cnjscv=&cgo=0&cgoco=0&cgocc=0&cgotcd=0&cgocv=&ccl=0&cclco=0&cclcc=0&ccltcd=0&cclcv=&cpy=0&cpyco=0&cpycc=0&cpytcd=0&cpycv=&cssz=A&cawact=0&osn=Linux&osa=amd64&osv=5.15.0-112-generic&mpbrct=0&mpmsct=0&mpaoqcct=0&mpaoict=0&mphect=0&mpwact=0&mpaocct=0&mpevct=0&mpnmct=0&mpptlams=-1&mpptla=-1&mpgtlams=-1&mpgtla=-1&mpvaluesct=0&mpentriesct=0&mpqslh=0&ucnenabled=false&restenabled=0&restmappostsucc=0&restmappostfail=0&restmapdeletesucc=0&restmapdeletefail=0&restmapgetsucc=0&restmapgetfail=0&restmaprequestct=0&restmapct=0&restqueuepostsucc=0&restqueuepostfail=0&restqueuegetsucc=0&restqueuegetfail=0&restqueuedeletesucc=0&restqueuedeletefail=0&restqueuect=0&restqueuerequestct=0&restconfigupdatesucc=0&restconfigupdatefail=0&restconfigreloadsucc=0&restconfigreloadfail=0&restrequestct=0&restuniqrequestct=0&vcpuct=8&dcpe=false&hdme=false&muhs=1589641216&mfhs=7000293376&tse=false&dmc=0&sqlqs=0&sqlqse=0>
	at com.github.tomakehurst.wiremock.client.VerificationException.forUnmatchedRequestPattern(VerificationException.java:35)
	at com.github.tomakehurst.wiremock.client.WireMock.verificationExceptionForNearMisses(WireMock.java:784)
	at com.github.tomakehurst.wiremock.client.WireMock.verifyThat(WireMock.java:774)
	at com.github.tomakehurst.wiremock.client.WireMock.verifyThat(WireMock.java:754)
	at com.github.tomakehurst.wiremock.client.WireMock.verify(WireMock.java:795)
	at com.hazelcast.internal.util.phonehome.PhoneHomeIntegrationTest.testForViridian(PhoneHomeIntegrationTest.java:327)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:898)

```
</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: testMapMetrics in 0.344 seconds.
Started Running Test: testForViridian
07:46:24,840  INFO |testForViridian| - [MetricsConfigHelper] main - [LOCAL] [dev] [6.0.0-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
07:46:24,841  INFO |testForViridian| - [logo] main - [127.0.0.1]:5701 [dev] [6.0.0-SNAPSHOT] 
    o    o     o     o---o   o--o o      o---o     o     o----o o--o--o
    |    |    / \       /         |     /         / \    |         |
    o----o       o     o   o----o |    o             o   o----o    |
    |    |  *     \   /           |     \       *     \       |    |
    o    o *       o o---o   o--o o----o o---o *       o o----o    o

07:46:24,841  INFO |testForViridian| - [system] main - [127.0.0.1]:5701 [dev] [6.0.0-SNAPSHOT] Copyright (c) 2008-2024, Hazelcast, Inc. All Rights Reserved.
07:46:24,841  INFO |testForViridian| - [system] main - [127.0.0.1]:5701 [dev] [6.0.0-SNAPSHOT] Hazelcast Platform 6.0.0-SNAPSHOT (20241006) starting at [127.0.0.1]:5701
07:46:24,841  INFO |testForViridian| - [system] main - [127.0.0.1]:5701 [dev] [6.0.0-SNAPSHOT] Cluster name: dev
07:46:24,841  INFO |testForViridian| - [system] main - [127.0.0.1]:5701 [dev] [6.0.0-SNAPSHOT] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed. For more information, see the documentation for Integrity Checker.
07:46:24,841  INFO |testForViridian| - [system] main - [127.0.0.1]:5701 [dev] [6.0.0-SNAPSHOT] Jet is enabled
07:46:24,843  INFO |testForViridian| - [MetricsConfigHelper] main - [127.0.0.1]:5701 [dev] [6.0.0-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
07:46:24,851  INFO |testForViridian| - [JetServiceBackend] main - [127.0.0.1]:5701 [dev] [6.0.0-SNAPSHOT] Setting number of cooperative threads and default parallelism to 8
07:46:24,852  INFO |testForViridian| - [Diagnostics] main - [127.0.0.1]:5701 [dev] [6.0.0-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
07:46:24,852  INFO |testForViridian| - [LifecycleService] main - [127.0.0.1]:5701 [dev] [6.0.0-SNAPSHOT] [127.0.0.1]:5701 is STARTING
07:46:24,852  INFO |testForViridian| - [ClusterService] main - [127.0.0.1]:5701 [dev] [6.0.0-SNAPSHOT] 

Members {size:1, ver:1} [
	Member [127.0.0.1]:5701 - 7a769e20-496d-492e-a08f-5108bfb18e66 this
]

07:46:24,852  INFO |testForViridian| - [JobCoordinationService] main - [127.0.0.1]:5701 [dev] [6.0.0-SNAPSHOT] Jet started scanning for jobs
07:46:24,852  INFO |testForViridian| - [LifecycleService] main - [127.0.0.1]:5701 [dev] [6.0.0-SNAPSHOT] [127.0.0.1]:5701 is STARTED
07:46:24,864 DEBUG |testForViridian| - [JobCoordinationService] hz.PhoneHomeIntegrationTest_objective_buck.cached.thread-6 - [127.0.0.1]:5701 [dev] [6.0.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
07:46:24,866  INFO |testForViridian| - [HealthMonitor] hz.PhoneHomeIntegrationTest_objective_buck.HealthMonitor - [127.0.0.1]:5701 [dev] [6.0.0-SNAPSHOT] The HealthMonitor has detected a high load on the system. For more detailed information,
enable Diagnostics by adding the property -Dhazelcast.diagnostics.enabled=true
07:46:24,867  INFO |testForViridian| - [HealthMonitor] hz.PhoneHomeIntegrationTest_objective_buck.HealthMonitor - [127.0.0.1]:5701 [dev] [6.0.0-SNAPSHOT] processors=8, physical.memory.total=754.5G, physical.memory.free=547.8G, swap.space.total=8.0G, swap.space.free=8.0G, heap.memory.used=7.2G, heap.memory.free=796.0M, heap.memory.total=8.0G, heap.memory.max=8.0G, heap.memory.used/total=90.28%, heap.memory.used/max=90.28%, minor.gc.count=0, minor.gc.time=0ms, major.gc.count=0, major.gc.time=0ms, unknown.gc.count=1403, unknown.gc.time=64472ms, load.process=54.06%, load.system=65.07%, load.systemAverage=3.38, thread.count=291, thread.peakCount=1454, cluster.timeDiff=0, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=0, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=0, clientEndpoint.count=0, connection.active.count=0, client.connection.count=0, connection.count=0
07:46:24,964 DEBUG |testForViridian| - [JobCoordinationService] hz.PhoneHomeIntegrationTest_objective_buck.cached.thread-1 - [127.0.0.1]:5701 [dev] [6.0.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
07:46:25,064 DEBUG |testForViridian| - [JobCoordinationService] hz.PhoneHomeIntegrationTest_objective_buck.cached.thread-1 - [127.0.0.1]:5701 [dev] [6.0.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
07:46:25,192 DEBUG |testForViridian| - [JobCoordinationService] hz.PhoneHomeIntegrationTest_objective_buck.cached.thread-1 - [127.0.0.1]:5701 [dev] [6.0.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
07:46:25,292 DEBUG |testForViridian| - [JobCoordinationService] hz.PhoneHomeIntegrationTest_objective_buck.cached.thread-6 - [127.0.0.1]:5701 [dev] [6.0.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
07:46:25,366  INFO |testForViridian| - [HazelcastTestSupport] main - Shutting down node factory as @After action
07:46:25,366  INFO |testForViridian| - [LifecycleService] main - [127.0.0.1]:5701 [dev] [6.0.0-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
07:46:25,367  WARN |testForViridian| - [Node] main - [127.0.0.1]:5701 [dev] [6.0.0-SNAPSHOT] Terminating forcefully...
07:46:25,367  INFO |testForViridian| - [Node] main - [127.0.0.1]:5701 [dev] [6.0.0-SNAPSHOT] Shutting down connection manager...
07:46:25,367  INFO |testForViridian| - [Node] main - [127.0.0.1]:5701 [dev] [6.0.0-SNAPSHOT] Shutting down node engine...
07:46:25,371  INFO |testForViridian| - [NodeExtension] main - [127.0.0.1]:5701 [dev] [6.0.0-SNAPSHOT] Destroying node NodeExtension.
07:46:25,371  INFO |testForViridian| - [Node] main - [127.0.0.1]:5701 [dev] [6.0.0-SNAPSHOT] Hazelcast Shutdown is completed in 5 ms.
07:46:25,371  INFO |testForViridian| - [LifecycleService] main - [127.0.0.1]:5701 [dev] [6.0.0-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
BuildInfo right after testForViridian(com.hazelcast.internal.util.phonehome.PhoneHomeIntegrationTest): BuildInfo{version='6.0.0-SNAPSHOT', build='20241006', buildNumber=20241006, revision=, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'testForViridian(com.hazelcast.internal.util.phonehome.PhoneHomeIntegrationTest):'
07:46:20, accumulated pauses: 365 ms, max pause: 231 ms, pauses over 1000 ms: 0
07:46:25, accumulated pauses: 102 ms, max pause: 100 ms, pauses over 1000 ms: 0


No metrics recorded during the test

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-ZingJDK17/75/

**Comment by AleksPeychev** [comment]
Failed again on _master_ with zing-17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZingJDK17/76/testReport/junit/com.hazelcast.internal.util.phonehome/PhoneHomeIntegrationTest/

**Comment by AleksPeychev** [comment]
Failed again on _master_ with zing-17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZingJDK17/81/testReport/junit/com.hazelcast.internal.util.phonehome/PhoneHomeIntegrationTest/testDownloadIdOverriddenWithEnvVar/

**Comment by AleksPeychev** [comment]
Failed again on _master_ with zing-17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZingJDK17/86/testReport/junit/com.hazelcast.internal.util.phonehome/PhoneHomeIntegrationTest/
