### ISSUE TITLE
com.hazelcast.internal.partition.GracefulShutdownCorrectnessTest

### ISSUE THREAD

**Issue by AleksPeychev** [hazelcast/hazelcast#26444]
_5.5.z_ (commit 8ff9b537838fe2a66629d3a1f3cb95f4dba1b56b)

Failed on redhat-17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-RedHatJDK17/137/testReport/junit/com.hazelcast.internal.partition/GracefulShutdownCorrectnessTest/___/
<details><summary>Stacktrace:</summary>

```
java.lang.IllegalStateException: Instances haven't been shut down: [HazelcastInstance{name='GracefulShutdownCorrectnessTest_eager_aryabhata', node=[127.0.0.1]:5704}]
	at com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:49)
	at com.hazelcast.test.ChangeLoggingRule$1.evaluate(ChangeLoggingRule.java:44)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-5.maintenance-RedHatJDK17/137/
 
----------------------------------------------------------------------------

_5.5.z_ (commit 8ff9b537838fe2a66629d3a1f3cb95f4dba1b56b)

Failed on redhat-17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-RedHatJDK17/137/testReport/junit/com.hazelcast.internal.partition/GracefulShutdownCorrectnessTest/testPartitionData_whenNodesStartedShutdown_whileOperationsOngoing_backups_0_nodes_2_shutdown_1_/
<details><summary>Stacktrace:</summary>

```
java.util.concurrent.CompletionException: com.hazelcast.core.OperationTimeoutException: TestPutOperation got rejected before execution due to not starting within the operation-call-timeout of: 60000 ms. Current time: 2024-10-08 23:18:07.583. Start time: 2024-10-08 23:17:01.210. Total elapsed time: 66373 ms. Invocation{op=com.hazelcast.internal.partition.service.TestPutOperation{serviceName='TestMigrationAwareService', identityHash=273023610, partitionId=58, replicaIndex=0, callId=-27236, invocationTime=1728429421210 (2024-10-08 23:17:01.210), waitTimeout=-1, callTimeout=60000, tenantControl=com.hazelcast.spi.impl.tenantcontrol.NoopTenantControl@0}, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=60000, firstInvocationTimeMs=1728429421210, firstInvocationTime='2024-10-08 23:17:01.210', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 00:00:00.000', targetAddress=[127.0.0.1]:5701, targetMember=Member [127.0.0.1]:5701 - 625455e6-716f-40ba-b785-38295915dc48 this, memberListVersion=3, pendingResponse={VOID}, backupsAcksExpected=-1, backupsAcksReceived=0, connection=null}
	at com.hazelcast.spi.impl.AbstractInvocationFuture.returnOrThrowWithJoinConventions(AbstractInvocationFuture.java:820)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.resolveAndThrowWithJoinConvention(AbstractInvocationFuture.java:841)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.join(AbstractInvocationFuture.java:554)
	at com.hazelcast.internal.partition.AbstractGracefulShutdownCorrectnessTest.testPartitionData_whenNodesStartedShutdown_whileOperationsOngoing(AbstractGracefulShutdownCorrectnessTest.java:148)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: com.hazelcast.core.OperationTimeoutException: TestPutOperation got rejected before execution due to not starting within the operation-call-timeout of: 60000 ms. Current time: 2024-10-08 23:18:07.583. Start time: 2024-10-08 23:17:01.210. Total elapsed time: 66373 ms. Invocation{op=com.hazelcast.internal.partition.service.TestPutOperation{serviceName='TestMigrationAwareService', identityHash=273023610, partitionId=58, replicaIndex=0, callId=-27236, invocationTime=1728429421210 (2024-10-08 23:17:01.210), waitTimeout=-1, callTimeout=60000, tenantControl=com.hazelcast.spi.impl.tenantcontrol.NoopTenantControl@0}, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=60000, firstInvocationTimeMs=1728429421210, firstInvocationTime='2024-10-08 23:17:01.210', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 00:00:00.000', targetAddress=[127.0.0.1]:5701, targetMember=Member [127.0.0.1]:5701 - 625455e6-716f-40ba-b785-38295915dc48 this, memberListVersion=3, pendingResponse={VOID}, backupsAcksExpected=-1, backupsAcksReceived=0, connection=null}
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.newOperationTimeoutException(InvocationFuture.java:203)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.toExceptionalResult(InvocationFuture.java:165)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:131)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.resolveAndThrowWithJoinConvention(AbstractInvocationFuture.java:840)
	... 7 more

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-5.maintenance-RedHatJDK17/137/

**Comment by AleksPeychev** [comment]
Failed again on _master_ with CorrettoJDK17 (arm64): https://jenkins.hazelcast.com/job/Hazelcast-master-CorrettoJDK17-arm64/47/testReport/com.hazelcast.internal.partition/GracefulShutdownCorrectnessTest/testPartitionData_whenNodesStartedShutdown_backups_0_nodes_2_shutdown_1_/

**Comment by Patras3** [comment]
Failed again on _master_ with OpenJDK17 (arm64): https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK17-arm64/82/testReport/com.hazelcast.internal.partition/GracefulShutdownCorrectnessTest/testPartitionData_whenNodesStartedShutdown_withRestart_backups_0_nodes_2_shutdown_1_/
Fails often in arm64

```
Jobs: 1, Runs: 12, Passed: 5, Failed: 7, Skipped: 0, Other: 0, Fail Ratio: 58.33%</p>
JDK | FAILED | PASSED | FIXED | REGRESSION | Total
-- | -- | -- | -- | -- | --
OpenJDK17 (arm64) | 4 | 3 | 2 | 3 | 12

</div>Branch: master
[Collapse/Expand]
Builds: 2025-05-07 22:44:32 — 2025-07-23 22:39:00
Jobs: 1, Runs: 12, Passed: 5, Failed: 7, Skipped: 0, Other: 0, Fail Ratio: 58.33%

JDK	FAILED	PASSED	FIXED	REGRESSION	Total
OpenJDK17 (arm64)	4	3	2	3	12
Timeline:
Date	Status	Job
2025-07-23 22:39:00	FAILED	[Hazelcast-master-OpenJDK17-arm64 #82](https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK17-arm64/82/testReport/com.hazelcast.internal.partition/GracefulShutdownCorrectnessTest)
2025-07-16 22:44:29	FAILED	[Hazelcast-master-OpenJDK17-arm64 #81](https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK17-arm64/81/testReport/com.hazelcast.internal.partition/GracefulShutdownCorrectnessTest)
2025-07-09 22:44:33	REGRESSION	[Hazelcast-master-OpenJDK17-arm64 #80](https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK17-arm64/80/testReport/com.hazelcast.internal.partition/GracefulShutdownCorrectnessTest)
2025-07-02 22:39:00	FIXED	[Hazelcast-master-OpenJDK17-arm64 #79](https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK17-arm64/79/testReport/com.hazelcast.internal.partition/GracefulShutdownCorrectnessTest)
2025-06-25 22:44:37	FAILED	[Hazelcast-master-OpenJDK17-arm64 #78](https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK17-arm64/78/testReport/com.hazelcast.internal.partition/GracefulShutdownCorrectnessTest)
2025-06-18 22:44:23	REGRESSION	[Hazelcast-master-OpenJDK17-arm64 #77](https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK17-arm64/77/testReport/com.hazelcast.internal.partition/GracefulShutdownCorrectnessTest)
2025-06-11 22:39:00	PASSED	[Hazelcast-master-OpenJDK17-arm64 #76](https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK17-arm64/76/testReport/com.hazelcast.internal.partition/GracefulShutdownCorrectnessTest)
2025-06-04 22:44:28	PASSED	[Hazelcast-master-OpenJDK17-arm64 #75](https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK17-arm64/75/testReport/com.hazelcast.internal.partition/GracefulShutdownCorrectnessTest)
2025-05-28 22:44:21	PASSED	[Hazelcast-master-OpenJDK17-arm64 #74](https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK17-arm64/74/testReport/com.hazelcast.internal.partition/GracefulShutdownCorrectnessTest)
2025-05-21 22:44:36	FIXED	[Hazelcast-master-OpenJDK17-arm64 #73](https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK17-arm64/73/testReport/com.hazelcast.internal.partition/GracefulShutdownCorrectnessTest)
2025-05-14 22:39:00	FAILED	[Hazelcast-master-OpenJDK17-arm64 #72](https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK17-arm64/72/testReport/com.hazelcast.internal.partition/GracefulShutdownCorrectnessTest)
2025-05-07 22:44:32	REGRESSION	[Hazelcast-master-OpenJDK17-arm64 #71](https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK17-arm64/71/testReport/com.hazelcast.internal.partition/GracefulShutdownCorrectnessTest)
```
