### ISSUE TITLE
Multiple 'Could not find a valid Docker environment' failures on MacOS [HZG-237]

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hazelcast#26447]
_master_ (commit 4222c9bcb40f8bd56671d5bfda855408c5a3ac10)
Failed on openjdk-17 (MacOS): https://jenkins.hazelcast.com/job/Hazelcast-master-MacOS-OpenJDK17/84/testReport

com.hazelcast.jet.elastic.ElasticClientsTest.given_clientAsString_whenReadFromElasticSource_thenFinishSuccessfully
[com.hazelcast.jet.kafka.impl.StreamKafkaPTest.(?)](https://jenkins.hazelcast.com/job/Hazelcast-master-MacOS-OpenJDK17/84/testReport/junit/com.hazelcast.jet.kafka.impl/StreamKafkaPTest/___/)
[com.hazelcast.jet.kafka.impl.WriteKafkaPTest.(?)](https://jenkins.hazelcast.com/job/Hazelcast-master-MacOS-OpenJDK17/84/testReport/junit/com.hazelcast.jet.kafka.impl/WriteKafkaPTest/___/)
[com.hazelcast.mapstore.mongodb.MongoGenericMapStoreBasicIT.(?)](https://jenkins.hazelcast.com/job/Hazelcast-master-MacOS-OpenJDK17/84/testReport/junit/com.hazelcast.mapstore.mongodb/MongoGenericMapStoreBasicIT/___/)
[com.hazelcast.jet.sql.impl.connector.mongodb.AllTypesInsertMongoSqlConnectorIT.(?)](https://jenkins.hazelcast.com/job/Hazelcast-master-MacOS-OpenJDK17/84/testReport/junit/com.hazelcast.jet.sql.impl.connector.mongodb/AllTypesInsertMongoSqlConnectorIT/___/)
[com.hazelcast.jet.sql.impl.connector.mongodb.AllTypesSelectInsertedMongoSqlConnectorIT.(?)](https://jenkins.hazelcast.com/job/Hazelcast-master-MacOS-OpenJDK17/84/testReport/junit/com.hazelcast.jet.sql.impl.connector.mongodb/AllTypesSelectInsertedMongoSqlConnectorIT/___/)
[com.hazelcast.jet.sql.impl.connector.mongodb.AllTypesSelectMongoSqlConnectorIT.(?)](https://jenkins.hazelcast.com/job/Hazelcast-master-MacOS-OpenJDK17/84/testReport/junit/com.hazelcast.jet.sql.impl.connector.mongodb/AllTypesSelectMongoSqlConnectorIT/___/)
[com.hazelcast.jet.sql.impl.connector.mongodb.MongoBatchSqlConnectorDeleteIT.(?)](https://jenkins.hazelcast.com/job/Hazelcast-master-MacOS-OpenJDK17/84/testReport/junit/com.hazelcast.jet.sql.impl.connector.mongodb/MongoBatchSqlConnectorDeleteIT/___/)
[com.hazelcast.jet.sql.impl.connector.mongodb.MongoBatchSqlConnectorUpdateIT.(?)](https://jenkins.hazelcast.com/job/Hazelcast-master-MacOS-OpenJDK17/84/testReport/junit/com.hazelcast.jet.sql.impl.connector.mongodb/MongoBatchSqlConnectorUpdateIT/___/)
[com.hazelcast.jet.sql.impl.connector.mongodb.MongoCreateDataConnectionSqlIT.(?)](https://jenkins.hazelcast.com/job/Hazelcast-master-MacOS-OpenJDK17/84/testReport/junit/com.hazelcast.jet.sql.impl.connector.mongodb/MongoCreateDataConnectionSqlIT/___/)
[com.hazelcast.jet.sql.impl.connector.mongodb.MongoSqlConnectorIT.(?)](https://jenkins.hazelcast.com/job/Hazelcast-master-MacOS-OpenJDK17/84/testReport/junit/com.hazelcast.jet.sql.impl.connector.mongodb/MongoSqlConnectorIT/___/)
[com.hazelcast.jet.sql.impl.connector.mongodb.MongoStreamSqlConnectorIT.(?)](https://jenkins.hazelcast.com/job/Hazelcast-master-MacOS-OpenJDK17/84/testReport/junit/com.hazelcast.jet.sql.impl.connector.mongodb/MongoStreamSqlConnectorIT/___/)
[com.hazelcast.jet.sql.impl.connector.mongodb.SqlMappingIT.(?)](https://jenkins.hazelcast.com/job/Hazelcast-master-MacOS-OpenJDK17/84/testReport/junit/com.hazelcast.jet.sql.impl.connector.mongodb/SqlMappingIT/___/)
[com.hazelcast.jet.mongodb.MongoSourceResourceExistenceTest.(?)](https://jenkins.hazelcast.com/job/Hazelcast-master-MacOS-OpenJDK17/84/testReport/junit/com.hazelcast.jet.mongodb/MongoSourceResourceExistenceTest/___/)
[com.hazelcast.jet.mongodb.MongoSourceVariousIdTypesTest.(?)](https://jenkins.hazelcast.com/job/Hazelcast-master-MacOS-OpenJDK17/84/testReport/junit/com.hazelcast.jet.mongodb/MongoSourceVariousIdTypesTest/___/)
[com.hazelcast.jet.mongodb.MongoSourcesWindowedTest.(?)](https://jenkins.hazelcast.com/job/Hazelcast-master-MacOS-OpenJDK17/84/testReport/junit/com.hazelcast.jet.mongodb/MongoSourcesWindowedTest/___/)
[com.hazelcast.jet.mongodb.dataconnection.MongoDataConnectionAuthTest.(?)](https://jenkins.hazelcast.com/job/Hazelcast-master-MacOS-OpenJDK17/84/testReport/junit/com.hazelcast.jet.mongodb.dataconnection/MongoDataConnectionAuthTest/___/)
[com.hazelcast.jet.mongodb.dataconnection.MongoDataConnectionMutualSslTest.should_connect_with_ssl](https://jenkins.hazelcast.com/job/Hazelcast-master-MacOS-OpenJDK17/84/testReport/junit/com.hazelcast.jet.mongodb.dataconnection/MongoDataConnectionMutualSslTest/should_connect_with_ssl/)
[com.hazelcast.jet.mongodb.dataconnection.MongoDataConnectionSslTest.should_connect_with_ssl](https://jenkins.hazelcast.com/job/Hazelcast-master-MacOS-OpenJDK17/84/testReport/junit/com.hazelcast.jet.mongodb.dataconnection/MongoDataConnectionSslTest/should_connect_with_ssl/)
[com.hazelcast.jet.mongodb.dataconnection.MongoDataConnectionTest.(?)](https://jenkins.hazelcast.com/job/Hazelcast-master-MacOS-OpenJDK17/84/testReport/junit/com.hazelcast.jet.mongodb.dataconnection/MongoDataConnectionTest/___/)
[com.hazelcast.jet.sql.impl.connector.mongodb.FieldResolverTest.(?)](https://jenkins.hazelcast.com/job/Hazelcast-master-MacOS-OpenJDK17/84/testReport/junit/com.hazelcast.jet.sql.impl.connector.mongodb/FieldResolverTest/___/)
[com.hazelcast.jet.s3.S3MockTest.(?)](https://jenkins.hazelcast.com/job/Hazelcast-master-MacOS-OpenJDK17/84/testReport/junit/com.hazelcast.jet.s3/S3MockTest/___/)
[com.hazelcast.jet.sql.impl.aggregate.SqlAggregationWithDmlTest.(?)](https://jenkins.hazelcast.com/job/Hazelcast-master-MacOS-OpenJDK17/84/testReport/junit/com.hazelcast.jet.sql.impl.aggregate/SqlAggregationWithDmlTest/___/)
[com.hazelcast.jet.sql.impl.connector.kafka.SqlPrimitiveTest.(?)](https://jenkins.hazelcast.com/job/Hazelcast-master-MacOS-OpenJDK17/84/testReport/junit/com.hazelcast.jet.sql.impl.connector.kafka/SqlPrimitiveTest/___/)
[com.hazelcast.dataconnection.impl.ListResourcesTest.shouldListResourcesDefaultAndNonDefaultSchema[provider == com.hazelcast.test.jdbc.PostgresDatabaseProvider@57d9db79]](https://jenkins.hazelcast.com/job/Hazelcast-master-MacOS-OpenJDK17/84/testReport/junit/com.hazelcast.dataconnection.impl/ListResourcesTest/shouldListResourcesDefaultAndNonDefaultSchema_provider____com_hazelcast_test_jdbc_PostgresDatabaseProvider_57d9db79_/)
[com.hazelcast.dataconnection.impl.ListResourcesTest.shouldListResourcesDefaultAndNonDefaultSchema[provider == com.hazelcast.test.jdbc.MySQLDatabaseProvider@2ca50b7a]](https://jenkins.hazelcast.com/job/Hazelcast-master-MacOS-OpenJDK17/84/testReport/junit/com.hazelcast.dataconnection.impl/ListResourcesTest/shouldListResourcesDefaultAndNonDefaultSchema_provider____com_hazelcast_test_jdbc_MySQLDatabaseProvider_2ca50b7a_/)
[com.hazelcast.dataconnection.impl.ListResourcesTest.shouldListResourcesDefaultAndNonDefaultSchema[provider == com.hazelcast.test.jdbc.MSSQLDatabaseProvider@154398a5]](https://jenkins.hazelcast.com/job/Hazelcast-master-MacOS-OpenJDK17/84/testReport/junit/com.hazelcast.dataconnection.impl/ListResourcesTest/shouldListResourcesDefaultAndNonDefaultSchema_provider____com_hazelcast_test_jdbc_MSSQLDatabaseProvider_154398a5_/)
[com.hazelcast.jet.impl.connector.MySQLReadJdbcPPropertiesTest.(?)](https://jenkins.hazelcast.com/job/Hazelcast-master-MacOS-OpenJDK17/84/testReport/junit/com.hazelcast.jet.impl.connector/MySQLReadJdbcPPropertiesTest/___/)
[com.hazelcast.jet.impl.connector.PostgreReadJdbcPPropertiesTest.(?)](https://jenkins.hazelcast.com/job/Hazelcast-master-MacOS-OpenJDK17/84/testReport/junit/com.hazelcast.jet.impl.connector/PostgreReadJdbcPPropertiesTest/___/)
[com.hazelcast.jet.impl.connector.mssql.MSSQLReadJdbcPTest.(?)](https://jenkins.hazelcast.com/job/Hazelcast-master-MacOS-OpenJDK17/84/testReport/junit/com.hazelcast.jet.impl.connector.mssql/MSSQLReadJdbcPTest/___/)
[com.hazelcast.jet.impl.connector.mssql.MSSQLWriteJdbcPTest.(?)](https://jenkins.hazelcast.com/job/Hazelcast-master-MacOS-OpenJDK17/84/testReport/junit/com.hazelcast.jet.impl.connector.mssql/MSSQLWriteJdbcPTest/___/)
[com.hazelcast.jet.impl.connector.mysql.MySQLReadJdbcPTest.(?)](https://jenkins.hazelcast.com/job/Hazelcast-master-MacOS-OpenJDK17/84/testReport/junit/com.hazelcast.jet.impl.connector.mysql/MySQLReadJdbcPTest/___/)
[com.hazelcast.jet.impl.connector.mysql.MySQLWriteJdbcPTest.(?)](https://jenkins.hazelcast.com/job/Hazelcast-master-MacOS-OpenJDK17/84/testReport/junit/com.hazelcast.jet.impl.connector.mysql/MySQLWriteJdbcPTest/___/)
[com.hazelcast.jet.impl.connector.postgres.PostgresReadJdbcPTest.(?)](https://jenkins.hazelcast.com/job/Hazelcast-master-MacOS-OpenJDK17/84/testReport/junit/com.hazelcast.jet.impl.connector.postgres/PostgresReadJdbcPTest/___/)
[com.hazelcast.jet.impl.connector.postgres.PostgresWriteJdbcPTest.(?)](https://jenkins.hazelcast.com/job/Hazelcast-master-MacOS-OpenJDK17/84/testReport/junit/com.hazelcast.jet.impl.connector.postgres/PostgresWriteJdbcPTest/___/)
[com.hazelcast.jet.sql.impl.connector.jdbc.oracle.OracleTableAndColumnNameTest.(?)](https://jenkins.hazelcast.com/job/Hazelcast-master-MacOS-OpenJDK17/84/testReport/junit/com.hazelcast.jet.sql.impl.connector.jdbc.oracle/OracleTableAndColumnNameTest/___/)

<details><summary>Stacktrace:</summary>

```
java.lang.IllegalStateException: Could not find a valid Docker environment. Please see logs and check configuration
	at org.testcontainers.dockerclient.DockerClientProviderStrategy.lambda$getFirstValidStrategy$7(DockerClientProviderStrategy.java:277)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at org.testcontainers.dockerclient.DockerClientProviderStrategy.getFirstValidStrategy(DockerClientProviderStrategy.java:268)
	at org.testcontainers.DockerClientFactory.getOrInitializeStrategy(DockerClientFactory.java:154)
	at org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:196)
	at org.testcontainers.DockerClientFactory$1.getDockerClient(DockerClientFactory.java:108)
	at com.github.dockerjava.api.DockerClientDelegate.authConfig(DockerClientDelegate.java:109)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:329)
	at com.hazelcast.jet.elastic.ElasticSupport.lambda$static$0(ElasticSupport.java:48)
	at com.hazelcast.jet.impl.util.MemoizingSupplier.get(MemoizingSupplier.java:39)
	at com.hazelcast.jet.elastic.ElasticSupport.elasticClientSupplier(ElasticSupport.java:72)
	at com.hazelcast.jet.elastic.BaseElasticTest.elasticClientSupplier(BaseElasticTest.java:118)
	at com.hazelcast.jet.elastic.BaseElasticTest.setUpBase(BaseElasticTest.java:91)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:365)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:53)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:32)
	at com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:41)

```
</details>

<details><summary>Standard output:</summary>

```
Started Running Test: given_clientAsString_whenReadFromElasticSource_thenFinishSuccessfully
19:23:51,724 DEBUG |given_clientAsString_whenReadFromElasticSource_thenFinishSuccessfully| - [TestcontainersConfiguration] main - Testcontainers configuration overrides will be loaded from file:/Users/ec2-user/.testcontainers.properties
19:23:51,728  INFO |given_clientAsString_whenReadFromElasticSource_thenFinishSuccessfully| - [PullPolicy] main - Image pull policy will be performed by: DefaultPullPolicy()
19:23:51,732  INFO |given_clientAsString_whenReadFromElasticSource_thenFinishSuccessfully| - [ImageNameSubstitutor] main - Image name substitution will be performed by: DefaultImageNameSubstitutor (composite of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitutor')
19:23:51,743  INFO |given_clientAsString_whenReadFromElasticSource_thenFinishSuccessfully| - [DockerClientFactory] main - Testcontainers version: 1.20.2
19:23:52,119  INFO |given_clientAsString_whenReadFromElasticSource_thenFinishSuccessfully| - [DockerClientProviderStrategy] main - Loaded org.testcontainers.dockerclient.UnixSocketClientProviderStrategy from ~/.testcontainers.properties, will try it first
19:23:52,127 DEBUG |given_clientAsString_whenReadFromElasticSource_thenFinishSuccessfully| - [DockerClientProviderStrategy] main - Trying out strategy: UnixSocketClientProviderStrategy
19:23:52,132 DEBUG |given_clientAsString_whenReadFromElasticSource_thenFinishSuccessfully| - [DockerClientProviderStrategy] main - UnixSocketClientProviderStrategy: failed with exception InvalidConfigurationException (Could not find unix domain socket). Root cause NoSuchFileException (/var/run/docker.sock)
19:23:52,133 DEBUG |given_clientAsString_whenReadFromElasticSource_thenFinishSuccessfully| - [DockerClientProviderStrategy] main - Trying out strategy: DockerDesktopClientProviderStrategy
19:23:52,134 DEBUG |given_clientAsString_whenReadFromElasticSource_thenFinishSuccessfully| - [DockerDesktopClientProviderStrategy] main - '/Users/ec2-user/.docker/desktop' does not exist.
19:23:52,135 DEBUG |given_clientAsString_whenReadFromElasticSource_thenFinishSuccessfully| - [DockerDesktopClientProviderStrategy] main - '/Users/ec2-user/.docker/run/docker.sock' does not exist.
19:23:52,135 DEBUG |given_clientAsString_whenReadFromElasticSource_thenFinishSuccessfully| - [DockerClientProviderStrategy] main - DockerDesktopClientProviderStrategy: failed with exception NullPointerException (Cannot invoke "java.nio.file.Path.toString()" because the return value of "org.testcontainers.dockerclient.DockerDesktopClientProviderStrategy.getSocketPath()" is null)
19:23:52,138  INFO |given_clientAsString_whenReadFromElasticSource_thenFinishSuccessfully| - [DockerMachineClientProviderStrategy] main - docker-machine executable was not found on PATH ([/usr/local/bin, /usr/bin, /bin, /usr/sbin, /sbin, /usr/local/opt/openjdk@17])
19:23:52,138 ERROR |given_clientAsString_whenReadFromElasticSource_thenFinishSuccessfully| - [DockerClientProviderStrategy] main - Could not find a valid Docker environment. Please check configuration. Attempted configurations were:
	UnixSocketClientProviderStrategy: failed with exception InvalidConfigurationException (Could not find unix domain socket). Root cause NoSuchFileException (/var/run/docker.sock)
	DockerDesktopClientProviderStrategy: failed with exception NullPointerException (Cannot invoke "java.nio.file.Path.toString()" because the return value of "org.testcontainers.dockerclient.DockerDesktopClientProviderStrategy.getSocketPath()" is null)As no valid configuration was found, execution cannot continue.
See https://java.testcontainers.org/on_failure.html for more details.

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-MacOS-OpenJDK17/84/

**Comment by sumnerib** [comment]
Failed again on _master_ with ZuluJDK21 (MacOS): https://jenkins.hazelcast.com/job/Hazelcast-master-MacOS-ZuluJDK21/92/testReport/

**Comment by sumnerib** [comment]
Fails constantly on `ZuluJDK21 (MacOS)`

**Comment by AleksPeychev** [comment]
Fails constantly on `openjdk-17 (MacOS)`

**Comment by JamesHazelcast** [comment]
I checked the associated Jenkins jobs [(1)](https://jenkins.hazelcast.com/job/Hazelcast-master-MacOS-ZuluJDK21/) and [(2)](https://jenkins.hazelcast.com/job/Hazelcast-master-MacOS-OpenJDK17/), and I see all recent jobs either pass without failures, or have a few unrelated flaky failures. This means the test failure is no longer valid / got fixed somewhere else already, so this issue can be closed.
