### ISSUE TITLE
com.hazelcast.internal.cluster.impl.ClusterStateManagerTest [HZG-247]

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hazelcast#26446]
_master_ (commit e3fa9bc4b8616ddcc3bfe766759874ebbdad4acf)
Failed on zing-21: https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK21/41/testReport/com.hazelcast.internal.cluster.impl/ClusterStateManagerTest/

<details><summary>Stacktrace:</summary>

```
java.lang.NullPointerException: Cannot invoke "com.hazelcast.logging.impl.LoggingServiceImpl.getLogger(java.lang.Class)" because "this.loggingService" is null
	at com.hazelcast.instance.impl.Node.getLogger(Node.java:769)
	at com.hazelcast.internal.cluster.impl.ClusterStateManager.<init>(ClusterStateManager.java:87)
	at com.hazelcast.internal.cluster.impl.ClusterStateManagerTest.setup(ClusterStateManagerTest.java:101)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:365)
	at com.hazelcast.test.HazelcastParallelClassRunner.access$101(HazelcastParallelClassRunner.java:52)
	at com.hazelcast.test.HazelcastParallelClassRunner$TestRunner.run(HazelcastParallelClassRunner.java:168)
	at java.base/java.lang.Thread.run(Thread.java:1584)

```
</details>

<details><summary>Standard output:</summary>

```
Started Running Test: test_lockClusterState_forActiveState_whenHasOnGoingMigration
Started Running Test: test_lockClusterState_forFrozenState_whenHasOnGoingMigration
Started Running Test: test_defaultState
Started Running Test: test_lockClusterState_nonPositiveLeaseTime
Started Running Test: test_lockClusterState_fail_withDifferentPartitionStateStamps
Started Running Test: test_changeLocalClusterState_success
Started Running Test: test_changeLocalClusterState_nullTransactionId
Started Running Test: test_unlockClusterState_fail_whenNotLocked

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-ZingJDK21/41/

**Comment by JackPGreen** [comment]
`loggingService` is a `final` field initialized in the constructor, unsure how could ever be `null`:
https://github.com/hazelcast/hazelcast/blob/a227d94f58ea8d2aca86b6a4a35aad0c09af5fcb/hazelcast/src/main/java/com/hazelcast/instance/impl/Node.java#L171
https://github.com/hazelcast/hazelcast/blob/a227d94f58ea8d2aca86b6a4a35aad0c09af5fcb/hazelcast/src/main/java/com/hazelcast/instance/impl/Node.java#L229-L230

Suspect JDK issue.

**Comment by JackPGreen** [comment]
Closing to see if re-occurs.

**Comment by AleksPeychev** [comment]
Reopening as issue occurred again on: _master_ (commit c2b29936260b2e522a2f63774b425f39ad7df517)
with zing-21: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZingJDK21/43/testReport/junit/com.hazelcast.internal.cluster.impl/ClusterStateManagerTest/test_unlockClusterState_fail_whenLockedByElse/
<details><summary>Stacktrace:</summary>

```
java.lang.NullPointerException: Cannot invoke "com.hazelcast.logging.impl.LoggingServiceImpl.getLogger(java.lang.Class)" because "this.loggingService" is null
	at com.hazelcast.instance.impl.Node.getLogger(Node.java:769)
	at com.hazelcast.internal.cluster.impl.ClusterStateManager.<init>(ClusterStateManager.java:87)
	at com.hazelcast.internal.cluster.impl.ClusterStateManagerTest.setup(ClusterStateManagerTest.java:101)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:365)
	at com.hazelcast.test.HazelcastParallelClassRunner.access$101(HazelcastParallelClassRunner.java:52)
	at com.hazelcast.test.HazelcastParallelClassRunner$TestRunner.run(HazelcastParallelClassRunner.java:168)
	at java.base/java.lang.Thread.run(Thread.java:1584)

```
</details>


<details><summary>Standard output:</summary>

```
Finished Running Test: test_lockClusterState_nullInitiator in 0.415 seconds.

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-ZingJDK21/43/

**Comment by sumnerib** [comment]
Failed again on _master_ with zing-21: https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK21/44/testReport/com.hazelcast.internal.cluster.impl/ClusterStateManagerTest/

**Comment by sumnerib** [comment]
Fails constantly on `zing-21`.

**Comment by AleksPeychev** [comment]
Failed again on _master_ with zing-21: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZingJDK21/61/testReport/com.hazelcast.internal.cluster.impl/ClusterStateManagerTest/

**Comment by AleksPeychev** [comment]
Anomalous failures caused by Mockito on Zing JDK 17 and 21 tracked https://github.com/hazelcast/hazelcast/issues/23517.
