### ISSUE TITLE
NPE when Preconditions.checkNotNull: Target cannot be null!

### ISSUE THREAD

**Issue by hdalimbkar** [hazelcast/hazelcast#26457]
java.lang.NullPointerException: Target cannot be null!
	at com.hazelcast.util.Preconditions.checkNotNull(Preconditions.java:59) ~[hazelcast-3.6.7.jar:3.6.7]
	at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.createInvocationBuilder(OperationServiceImpl.java:256) ~[hazelcast-3.6.7.jar:3.6.7]
	at com.hazelcast.client.impl.protocol.task.CreateProxyMessageTask.getInvocationBuilder(CreateProxyMessageTask.java:42) ~[hazelcast-3.6.7.jar:3.6.7]
	at com.hazelcast.client.impl.protocol.task.AbstractInvocationMessageTask.processMessage(AbstractInvocationMessageTask.java:39) ~[hazelcast-3.6.7.jar:3.6.7]
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:128) ~[hazelcast-3.6.7.jar:3.6.7]
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:108) ~[hazelcast-3.6.7.jar:3.6.7]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:na]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:na]
	at java.lang.Thread.run(Thread.java:750) ~[na:na]
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76) ~[hazelcast-3.6.7.jar:3.6.7]
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92) ~[hazelcast-3.6.7.jar:3.6.7]

**Comment by ataltinok** [comment]
Could you provide a bit more context on this issue? 
- What caused this NPE? 
- Was it working before? 
- Are there cases that don't throw an NPE?
