### ISSUE TITLE
com.hazelcast.topic.TopicTest

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hazelcast#26456]
_master_ (commit 3e8fa8115c4ce217b788bf3a936173116fba3da7)
Failed on zing-21: https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK21/44/testReport/com.hazelcast.topic/TopicTest/testTopicCluster/

<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: CountDownLatch failed to complete within 120 seconds, count left: 1
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:1147)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:1132)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:1120)
	at com.hazelcast.topic.TopicTest.testTopicCluster(TopicTest.java:586)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.lang.Thread.run(Thread.java:1584)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-ZingJDK21/44/

**Comment by AleksPeychev** [comment]
Failed again on _master_ with redhat-17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-RedHatJDK17/144/testReport/junit/com.hazelcast.topic/TopicTest/
