### ISSUE TITLE
com.hazelcast.client.impl.clientside.ClientDynamicConfigSmokeTest.map_testConflictingStaticConfig

### ISSUE THREAD

**Issue by AleksPeychev** [hazelcast/hazelcast#26459]
_master_ (commit 5228ecc9f8ca3504f40227be2cf04d097ec94aa8)

Failed on openj9-21: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Openj9-21/43/testReport/com.hazelcast.client.impl.clientside/ClientDynamicConfigSmokeTest/map_testConflictingStaticConfig/
<details><summary>Stacktrace:</summary>

```
junit.framework.AssertionFailedError: 
Unexpected java.lang.NullPointerException exception type thrown with message:
Cannot invoke "java.lang.invoke.MethodHandle.invoke(java.lang.String)"
	at com.hazelcast.test.HazelcastTestSupport.assertThrows(HazelcastTestSupport.java:1446)
	at com.hazelcast.internal.dynamicconfig.DynamicConfigSmokeTest.map_testConflictingStaticConfig(DynamicConfigSmokeTest.java:247)
	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.lang.Thread.run(Thread.java:1595)

```
</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: map_testNonConflictingStaticConfig in 0.096 seconds.
08:34:16,054  INFO |map_testConflictingStaticConfig| - [LifecycleService] Thread-53482 - hz.client_3998 [dev] [6.0.0-SNAPSHOT] HazelcastClient 6.0.0-SNAPSHOT (20241109) is SHUTTING_DOWN
08:34:16,054  WARN |map_testConflictingStaticConfig| - [TestClientRegistry$MockedServerConnection] pool-11170-thread-1 - Server connection closed: null
08:34:16,054  INFO |map_testConflictingStaticConfig| - [MockServer] pool-11170-thread-1 - [127.0.0.1]:5701 [dev] [6.0.0-SNAPSHOT] Removed connection to endpoint: [address=[127.0.0.1]:40001, uuid=457e19da-c436-4d6b-9663-a97c9100722c], connection: MockedNodeConnection{ remoteAddress = [127.0.0.1]:40001, localAddress = [127.0.0.1]:5701, connectionId = 1}
08:34:16,054  INFO |map_testConflictingStaticConfig| - [ClientConnectionManager] Thread-53482 - hz.client_3998 [dev] [6.0.0-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5701:24881f83-392c-4d8c-ac34-e3e2bb811b96, connection: MockedClientConnection{localAddress=[127.0.0.1]:40001, super=ClientConnection{alive=false, connectionId=1, channel=null, remoteAddress=[127.0.0.1]:5701, remoteUuid=24881f83-392c-4d8c-ac34-e3e2bb811b96, clusterUuid=659f906b-4074-4cc2-adf8-4046c2758926, lastReadTime=2024-11-09 08:34:16.004, lastWriteTime=2024-11-09 08:34:15.993, closedTime=2024-11-09 08:34:16.054}}
08:34:16,055  INFO |map_testConflictingStaticConfig| - [LifecycleService] Thread-53482 - hz.client_3998 [dev] [6.0.0-SNAPSHOT] HazelcastClient 6.0.0-SNAPSHOT (20241109) is CLIENT_DISCONNECTED
08:34:16,055  WARN |map_testConflictingStaticConfig| - [TwoWayBlockableExecutor] pool-11170-thread-1 - Dropping incoming runnable since other end closed. Server Closed EOF. MockedClientConnection{localAddress=[127.0.0.1]:40001, super=ClientConnection{alive=false, connectionId=1, channel=null, remoteAddress=[127.0.0.1]:5701, remoteUuid=24881f83-392c-4d8c-ac34-e3e2bb811b96, clusterUuid=659f906b-4074-4cc2-adf8-4046c2758926, lastReadTime=2024-11-09 08:34:16.004, lastWriteTime=2024-11-09 08:34:15.993, closedTime=2024-11-09 08:34:16.054}}
08:34:16,055  INFO |map_testConflictingStaticConfig| - [ClientEndpointManager] hz.ClientDynamicConfigSmokeTest_nifty_williams.event-54598 - [127.0.0.1]:5701 [dev] [6.0.0-SNAPSHOT] Destroying ClientEndpoint{connection=MockedNodeConnection{ remoteAddress = [127.0.0.1]:40001, localAddress = [127.0.0.1]:5701, connectionId = 1}, clientUuid=457e19da-c436-4d6b-9663-a97c9100722c, clientName=hz.client_3998, authenticated=true, clientVersion=6.0.0-SNAPSHOT, creationTime=1731141255986, latest clientAttributes=lastStatisticsCollectionTime=1731141255991,enterprise=false,clientType=JVM,clientVersion=6.0.0-SNAPSHOT,clusterConnectionTimestamp=1731141255985,clientAddress=127.0.0.1,clientName=hz.client_3998,credentials.principal=null,os.committedVirtualMemorySize=31165681664,os.freePhysicalMemorySize=620220252160,os.freeSwapSpaceSize=8573939712,os.maxFileDescriptorCount=1048576,os.openFileDescriptorCount=243,os.processCpuTime=4670379677000,os.systemLoadAverage=4.97216796875,os.totalPhysicalMemorySize=811471450112,os.totalSwapSpaceSize=8589930496,runtime.availableProcessors=8,runtime.freeMemory=7195702176,runtime.maxMemory=8589934592,runtime.totalMemory=8589934592,runtime.uptime=4354079,runtime.usedMemory=1394232416, labels=[]}
08:34:16,055  INFO |map_testConflictingStaticConfig| - [LifecycleService] Thread-53482 - hz.client_3998 [dev] [6.0.0-SNAPSHOT] HazelcastClient 6.0.0-SNAPSHOT (20241109) is SHUTDOWN
08:34:16,056  INFO |map_testConflictingStaticConfig| - [LifecycleService] Thread-53482 - [127.0.0.1]:5701 [dev] [6.0.0-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
08:34:16,056  WARN |map_testConflictingStaticConfig| - [Node] Thread-53482 - [127.0.0.1]:5701 [dev] [6.0.0-SNAPSHOT] Terminating forcefully...
08:34:16,056  INFO |map_testConflictingStaticConfig| - [Node] Thread-53482 - [127.0.0.1]:5701 [dev] [6.0.0-SNAPSHOT] Shutting down connection manager...
08:34:16,056  INFO |map_testConflictingStaticConfig| - [Node] Thread-53482 - [127.0.0.1]:5701 [dev] [6.0.0-SNAPSHOT] Shutting down node engine...
Started Running Test: map_initialSubmitTest_withWildcards
08:34:16,058 DEBUG |multimap_initialSubmitTest| - [JobCoordinationService] hz.ClientDynamicConfigSmokeTest_condescending_williams.cached.thread-2 - [127.0.0.1]:5701 [dev] [6.0.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
08:34:16,059  INFO |map_initialSubmitTest_withWildcards| - [MetricsConfigHelper] map_initialSubmitTest_withWildcards - [LOCAL] [dev] [6.0.0-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
08:34:16,059  INFO |map_initialSubmitTest_withWildcards| - [logo] map_initialSubmitTest_withWildcards - [127.0.0.1]:5701 [dev] [6.0.0-SNAPSHOT] 
    o    o     o     o---o   o--o o      o---o     o     o----o o--o--o
    |    |    / \       /         |     /         / \    |         |
    o----o       o     o   o----o |    o             o   o----o    |
    |    |  *     \   /           |     \       *     \       |    |
    o    o *       o o---o   o--o o----o o---o *       o o----o    o

08:34:16,059  INFO |map_initialSubmitTest_withWildcards| - [system] map_initialSubmitTest_withWildcards - [127.0.0.1]:5701 [dev] [6.0.0-SNAPSHOT] Copyright (c) 2008-2024, Hazelcast, Inc. All Rights Reserved.
08:34:16,059  INFO |map_initialSubmitTest_withWildcards| - [system] map_initialSubmitTest_withWildcards - [127.0.0.1]:5701 [dev] [6.0.0-SNAPSHOT] Hazelcast Platform 6.0.0-SNAPSHOT (20241109) starting at [127.0.0.1]:5701
08:34:16,059  INFO |map_initialSubmitTest_withWildcards| - [system] map_initialSubmitTest_withWildcards - [127.0.0.1]:5701 [dev] [6.0.0-SNAPSHOT] Cluster name: dev
08:34:16,059  INFO |map_initialSubmitTest_withWildcards| - [system] map_initialSubmitTest_withWildcards - [127.0.0.1]:5701 [dev] [6.0.0-SNAPSHOT] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed. For more information, see the documentation for Integrity Checker.
08:34:16,059  INFO |map_initialSubmitTest_withWildcards| - [system] map_initialSubmitTest_withWildcards - [127.0.0.1]:5701 [dev] [6.0.0-SNAPSHOT] Jet is enabled
08:34:16,060 DEBUG |cacheConfig_whenListenerIsRegistered| - [JobCoordinationService] hz.ClientDynamicConfigSmokeTest_vigilant_williams.cached.thread-5 - [127.0.0.1]:5701 [dev] [6.0.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
08:34:16,061  INFO |map_initialSubmitTest_withWildcards| - [MetricsConfigHelper] map_initialSubmitTest_withWildcards - [127.0.0.1]:5701 [dev] [6.0.0-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
08:34:16,061  INFO |map_testConflictingStaticConfig| - [NodeExtension] Thread-53482 - [127.0.0.1]:5701 [dev] [6.0.0-SNAPSHOT] Destroying node NodeExtension.
08:34:16,061  INFO |map_testConflictingStaticConfig| - [Node] Thread-53482 - [127.0.0.1]:5701 [dev] [6.0.0-SNAPSHOT] Hazelcast Shutdown is completed in 5 ms.
08:34:16,062  INFO |map_testConflictingStaticConfig| - [LifecycleService] Thread-53482 - [127.0.0.1]:5701 [dev] [6.0.0-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
08:34:16,062  INFO |map_testConflictingStaticConfig| - [HazelcastTestSupport] Thread-53482 - Shutting down node factory as @After action
BuildInfo right after map_testConflictingStaticConfig(com.hazelcast.client.impl.clientside.ClientDynamicConfigSmokeTest): BuildInfo{version='6.0.0-SNAPSHOT', build='20241109', buildNumber=20241109, revision=, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'map_testConflictingStaticConfig(com.hazelcast.client.impl.clientside.ClientDynamicConfigSmokeTest):'
08:34:15, accumulated pauses: 28 ms, max pause: 21 ms, pauses over 1000 ms: 0

08:34:16,066  INFO |map_initialSubmitTest_withWildcards| - [JetServiceBackend] map_initialSubmitTest_withWildcards - [127.0.0.1]:5701 [dev] [6.0.0-SNAPSHOT] Setting number of cooperative threads and default parallelism to 2
08:34:16,066 DEBUG |map_initialSubmitTest| - [JobCoordinationService] hz.ClientDynamicConfigSmokeTest_peaceful_williams.cached.thread-4 - [127.0.0.1]:5701 [dev] [6.0.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.

No metrics recorded during the test
08:34:16,067  INFO |map_initialSubmitTest_withWildcards| - [Diagnostics] map_initialSubmitTest_withWildcards - [127.0.0.1]:5701 [dev] [6.0.0-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
08:34:16,067  INFO |map_initialSubmitTest_withWildcards| - [LifecycleService] map_initialSubmitTest_withWildcards - [127.0.0.1]:5701 [dev] [6.0.0-SNAPSHOT] [127.0.0.1]:5701 is STARTING
08:34:16,067  INFO |map_initialSubmitTest_withWildcards| - [ClusterService] map_initialSubmitTest_withWildcards - [127.0.0.1]:5701 [dev] [6.0.0-SNAPSHOT] 

Members {size:1, ver:1} [
	Member [127.0.0.1]:5701 - bcffea2b-bce6-41ab-af22-92858fcb2934 this
]

08:34:16,067  INFO |map_initialSubmitTest_withWildcards| - [JobCoordinationService] map_initialSubmitTest_withWildcards - [127.0.0.1]:5701 [dev] [6.0.0-SNAPSHOT] Jet started scanning for jobs
08:34:16,067  INFO |map_initialSubmitTest_withWildcards| - [LifecycleService] map_initialSubmitTest_withWildcards - [127.0.0.1]:5701 [dev] [6.0.0-SNAPSHOT] [127.0.0.1]:5701 is STARTED
08:34:16,068 DEBUG |map_initialSubmitTest_withWildcards| - [JobCoordinationService] hz.ClientDynamicConfigSmokeTest_sweet_williams.cached.thread-7 - [127.0.0.1]:5701 [dev] [6.0.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
08:34:16,068  INFO |map_initialSubmitTest_withWildcards| - [MetricsConfigHelper] map_initialSubmitTest_withWildcards - [LOCAL] [dev] [6.0.0-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
08:34:16,068  INFO |map_initialSubmitTest_withWildcards| - [logo] map_initialSubmitTest_withWildcards - [127.0.0.1]:5702 [dev] [6.0.0-SNAPSHOT] 
    o    o     o     o---o   o--o o      o---o     o     o----o o--o--o
    |    |    / \       /         |     /         / \    |         |
    o----o       o     o   o----o |    o             o   o----o    |
    |    |  *     \   /           |     \       *     \       |    |
    o    o *       o o---o   o--o o----o o---o *       o o----o    o

08:34:16,068  INFO |map_initialSubmitTest_withWildcards| - [system] map_initialSubmitTest_withWildcards - [127.0.0.1]:5702 [dev] [6.0.0-SNAPSHOT] Copyright (c) 2008-2024, Hazelcast, Inc. All Rights Reserved.
08:34:16,068  INFO |map_initialSubmitTest_withWildcards| - [system] map_initialSubmitTest_withWildcards - [127.0.0.1]:5702 [dev] [6.0.0-SNAPSHOT] Hazelcast Platform 6.0.0-SNAPSHOT (20241109) starting at [127.0.0.1]:5702
08:34:16,068  INFO |map_initialSubmitTest_withWildcards| - [system] map_initialSubmitTest_withWildcards - [127.0.0.1]:5702 [dev] [6.0.0-SNAPSHOT] Cluster name: dev
08:34:16,068  INFO |map_initialSubmitTest_withWildcards| - [system] map_initialSubmitTest_withWildcards - [127.0.0.1]:5702 [dev] [6.0.0-SNAPSHOT] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed. For more information, see the documentation for Integrity Checker.
08:34:16,068  INFO |map_initialSubmitTest_withWildcards| - [system] map_initialSubmitTest_withWildcards - [127.0.0.1]:5702 [dev] [6.0.0-SNAPSHOT] Jet is enabled
08:34:16,069  INFO |map_initialSubmitTest_withWildcards| - [MetricsConfigHelper] map_initialSubmitTest_withWildcards - [127.0.0.1]:5702 [dev] [6.0.0-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
08:34:16,073  INFO |multimap_initialSubmitTest| - [ClusterService] hz.ClientDynamicConfigSmokeTest_confident_williams.priority-generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [6.0.0-SNAPSHOT] 

Members {size:2, ver:2} [
	Member [127.0.0.1]:5701 - 97a97cda-6945-4816-9756-d1cd0e6d12db
	Member [127.0.0.1]:5702 - a09ed2eb-db04-4a00-ac1c-67cdfadf954a this
]

08:34:16,073  INFO |multimap_initialSubmitTest| - [JobCoordinationService] multimap_initialSubmitTest - [127.0.0.1]:5702 [dev] [6.0.0-SNAPSHOT] Jet started scanning for jobs
08:34:16,073  INFO |multimap_initialSubmitTest| - [LifecycleService] multimap_initialSubmitTest - [127.0.0.1]:5702 [dev] [6.0.0-SNAPSHOT] [127.0.0.1]:5702 is STARTED
08:34:16,074  INFO |multimap_initialSubmitTest| - [MetricsConfigHelper] multimap_initialSubmitTest - [LOCAL] [dev] [6.0.0-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
08:34:16,074  INFO |multimap_initialSubmitTest| - [logo] multimap_initialSubmitTest - [127.0.0.1]:5703 [dev] [6.0.0-SNAPSHOT] 
    o    o     o     o---o   o--o o      o---o     o     o----o o--o--o
    |    |    / \       /         |     /         / \    |         |
    o----o       o     o   o----o |    o             o   o----o    |
    |    |  *     \   /           |     \       *     \       |    |
    o    o *       o o---o   o--o o----o o---o *       o o----o    o

08:34:16,074  INFO |multimap_initialSubmitTest| - [system] multimap_initialSubmitTest - [127.0.0.1]:5703 [dev] [6.0.0-SNAPSHOT] Copyright (c) 2008-2024, Hazelcast, Inc. All Rights Reserved.
08:34:16,074  INFO |multimap_initialSubmitTest| - [system] multimap_initialSubmitTest - [127.0.0.1]:5703 [dev] [6.0.0-SNAPSHOT] Hazelcast Platform 6.0.0-SNAPSHOT (20241109) starting at [127.0.0.1]:5703
08:34:16,074  INFO |multimap_initialSubmitTest| - [system] multimap_initialSubmitTest - [127.0.0.1]:5703 [dev] [6.0.0-SNAPSHOT] Cluster name: dev
08:34:16,074  INFO |multimap_initialSubmitTest| - [system] multimap_initialSubmitTest - [127.0.0.1]:5703 [dev] [6.0.0-SNAPSHOT] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed. For more information, see the documentation for Integrity Checker.
08:34:16,074  INFO |multimap_initialSubmitTest| - [system] multimap_initialSubmitTest - [127.0.0.1]:5703 [dev] [6.0.0-SNAPSHOT] Jet is enabled
08:34:16,074  INFO |multimap_withNewMemberJoiningLater| - [MetricsConfigHelper] multimap_withNewMemberJoiningLater - [LOCAL] [dev] [6.0.0-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
08:34:16,074  INFO |multimap_withNewMemberJoiningLater| - [logo] multimap_withNewMemberJoiningLater - [127.0.0.1]:5702 [dev] [6.0.0-SNAPSHOT] 
    o    o     o     o---o   o--o o      o---o     o     o----o o--o--o
    |    |    / \       /         |     /         / \    |         |
    o----o       o     o   o----o |    o             o   o----o    |
    |    |  *     \   /           |     \       *     \       |    |
    o    o *       o o---o   o--o o----o o---o *       o o----o    o

08:34:16,074  INFO |multimap_withNewMemberJoiningLater| - [system] multimap_withNewMemberJoiningLater - [127.0.0.1]:5702 [dev] [6.0.0-SNAPSHOT] Copyright (c) 2008-2024, Hazelcast, Inc. All Rights Reserved.
08:34:16,074  INFO |multimap_withNewMemberJoiningLater| - [system] multimap_withNewMemberJoiningLater - [127.0.0.1]:5702 [dev] [6.0.0-SNAPSHOT] Hazelcast Platform 6.0.0-SNAPSHOT (20241109) starting at [127.0.0.1]:5702
08:34:16,074  INFO |multimap_withNewMemberJoiningLater| - [system] multimap_withNewMemberJoiningLater - [127.0.0.1]:5702 [dev] [6.0.0-SNAPSHOT] Cluster name: dev
08:34:16,074  INFO |multimap_withNewMemberJoiningLater| - [system] multimap_withNewMemberJoiningLater - [127.0.0.1]:5702 [dev] [6.0.0-SNAPSHOT] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed. For more information, see the documentation for Integrity Checker.
08:34:16,074  INFO |multimap_withNewMemberJoiningLater| - [system] multimap_withNewMemberJoiningLater - [127.0.0.1]:5702 [dev] [6.0.0-SNAPSHOT] Jet is enabled
08:34:16,075  INFO |map_initialSubmitTest_withWildcards| - [JetServiceBackend] map_initialSubmitTest_withWildcards - [127.0.0.1]:5702 [dev] [6.0.0-SNAPSHOT] Setting number of cooperative threads and default parallelism to 2
08:34:16,075  INFO |map_initialSubmitTest| - [ClusterService] hz.ClientDynamicConfigSmokeTest_romantic_williams.priority-generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [6.0.0-SNAPSHOT] 

Members {size:2, ver:2} [
	Member [127.0.0.1]:5701 - f528c6b6-5f23-4567-907f-392b5c18a358
	Member [127.0.0.1]:5702 - 73da9d25-8e63-4e0c-a33d-3b150cf16578 this
]

08:34:16,075  INFO |map_initialSubmitTest| - [JobCoordinationService] map_initialSubmitTest - [127.0.0.1]:5702 [dev] [6.0.0-SNAPSHOT] Jet started scanning for jobs
08:34:16,076  INFO |map_initialSubmitTest| - [LifecycleService] map_initialSubmitTest - [127.0.0.1]:5702 [dev] [6.0.0-SNAPSHOT] [127.0.0.1]:5702 is STARTED
08:34:16,076  INFO |multimap_initialSubmitTest| - [MetricsConfigHelper] multimap_initialSubmitTest - [127.0.0.1]:5703 [dev] [6.0.0-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
08:34:16,076  INFO |map_initialSubmitTest| - [MetricsConfigHelper] map_initialSubmitTest - [LOCAL] [dev] [6.0.0-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
08:34:16,076  INFO |map_initialSubmitTest| - [logo] map_initialSubmitTest - [127.0.0.1]:5703 [dev] [6.0.0-SNAPSHOT] 
    o    o     o     o---o   o--o o      o---o     o     o----o o--o--o
    |    |    / \       /         |     /         / \    |         |
    o----o       o     o   o----o |    o             o   o----o    |
    |    |  *     \   /           |     \       *     \       |    |
    o    o *       o o---o   o--o o----o o---o *       o o----o    o

08:34:16,076  INFO |map_initialSubmitTest| - [system] map_initialSubmitTest - [127.0.0.1]:5703 [dev] [6.0.0-SNAPSHOT] Copyright (c) 2008-2024, Hazelcast, Inc. All Rights Reserved.
08:34:16,076  INFO |map_initialSubmitTest| - [system] map_initialSubmitTest - [127.0.0.1]:5703 [dev] [6.0.0-SNAPSHOT] Hazelcast Platform 6.0.0-SNAPSHOT (20241109) starting at [127.0.0.1]:5703
08:34:16,076  INFO |map_initialSubmitTest| - [system] map_initialSubmitTest - [127.0.0.1]:5703 [dev] [6.0.0-SNAPSHOT] Cluster name: dev
08:34:16,076  INFO |map_initialSubmitTest| - [system] map_initialSubmitTest - [127.0.0.1]:5703 [dev] [6.0.0-SNAPSHOT] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed. For more information, see the documentation for Integrity Checker.
08:34:16,076  INFO |map_initialSubmitTest| - [system] map_initialSubmitTest - [127.0.0.1]:5703 [dev] [6.0.0-SNAPSHOT] Jet is enabled
08:34:16,076  INFO |map_initialSubmitTest_withWildcards| - [Diagnostics] map_initialSubmitTest_withWildcards - [127.0.0.1]:5702 [dev] [6.0.0-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
08:34:16,077  INFO |multimap_withNewMemberJoiningLater| - [MetricsConfigHelper] multimap_withNewMemberJoiningLater - [127.0.0.1]:5702 [dev] [6.0.0-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
08:34:16,077  INFO |map_initialSubmitTest_withWildcards| - [LifecycleService] map_initialSubmitTest_withWildcards - [127.0.0.1]:5702 [dev] [6.0.0-SNAPSHOT] [127.0.0.1]:5702 is STARTING
08:34:16,077  INFO |map_initialSubmitTest_withWildcards| - [MockServer] map_initialSubmitTest_withWildcards - [127.0.0.1]:5702 [dev] [6.0.0-SNAPSHOT] Created connection to endpoint: [127.0.0.1]:5701-bcffea2b-bce6-41ab-af22-92858fcb2934, connection: MockConnection{localEndpoint=[address=[127.0.0.1]:5702, uuid=b48b97ed-1eca-46b9-83ee-3e547a2ea5cd], remoteEndpoint=[address=[127.0.0.1]:5701, uuid=bcffea2b-bce6-41ab-af22-92858fcb2934], alive=true}
08:34:16,077  INFO |map_initialSubmitTest_withWildcards| - [MockServer] hz.ClientDynamicConfigSmokeTest_sweet_williams.priority-generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [6.0.0-SNAPSHOT] Created connection to endpoint: [127.0.0.1]:5702-b48b97ed-1eca-46b9-83ee-3e547a2ea5cd, connection: MockConnection{localEndpoint=[address=[127.0.0.1]:5701, uuid=bcffea2b-bce6-41ab-af22-92858fcb2934], remoteEndpoint=[address=[127.0.0.1]:5702, uuid=b48b97ed-1eca-46b9-83ee-3e547a2ea5cd], alive=true}
08:34:16,078  INFO |map_initialSubmitTest_withWildcards| - [ClusterService] hz.ClientDynamicConfigSmokeTest_sweet_williams.priority-generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [6.0.0-SNAPSHOT] 

Members {size:2, ver:2} [
	Member [127.0.0.1]:5701 - bcffea2b-bce6-41ab-af22-92858fcb2934 this
	Member [127.0.0.1]:5702 - b48b97ed-1eca-46b9-83ee-3e547a2ea5cd
]

08:34:16,078  INFO |map_initialSubmitTest| - [MetricsConfigHelper] map_initialSubmitTest - [127.0.0.1]:5703 [dev] [6.0.0-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
08:34:16,079  INFO |mapConfig_withLiteMemberJoiningLater_isImmediatelyAvailable| - [MetricsConfigHelper] mapConfig_withLiteMemberJoiningLater_isImmediatelyAvailable - [LOCAL] [dev] [6.0.0-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
08:34:16,079  INFO |mapConfig_withLiteMemberJoiningLater_isImmediatelyAvailable| - [logo] mapConfig_withLiteMemberJoiningLater_isImmediatelyAvailable - [127.0.0.1]:5702 [dev] [6.0.0-SNAPSHOT] 
    o    o     o     o---o   o--o o      o---o     o     o----o o--o--o
    |    |    / \       /         |     /         / \    |         |
    o----o       o     o   o----o |    o             o   o----o    |
    |    |  *     \   /           |     \       *     \       |    |
    o    o *       o o---o   o--o o----o o---o *       o o----o    o

08:34:16,079  INFO |mapConfig_withLiteMemberJoiningLater_isImmediatelyAvailable| - [system] mapConfig_withLiteMemberJoiningLater_isImmediatelyAvailable - [127.0.0.1]:5702 [dev] [6.0.0-SNAPSHOT] Copyright (c) 2008-2024, Hazelcast, Inc. All Rights Reserved.
08:34:16,079  INFO |mapConfig_withLiteMemberJoiningLater_isImmediatelyAvailable| - [system] mapConfig_withLiteMemberJoiningLater_isImmediatelyAvailable - [127.0.0.1]:5702 [dev] [6.0.0-SNAPSHOT] Hazelcast Platform 6.0.0-SNAPSHOT (20241109) starting at [127.0.0.1]:5702
08:34:16,079  INFO |mapConfig_withLiteMemberJoiningLater_isImmediatelyAvailable| - [system] mapConfig_withLiteMemberJoiningLater_isImmediatelyAvailable - [127.0.0.1]:5702 [dev] [6.0.0-SNAPSHOT] Cluster name: dev
08:34:16,079  INFO |mapConfig_withLiteMemberJoiningLater_isImmediatelyAvailable| - [system] mapConfig_withLiteMemberJoiningLater_isImmediatelyAvailable - [127.0.0.1]:5702 [dev] [6.0.0-SNAPSHOT] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed. For more information, see the documentation for Integrity Checker.
08:34:16,079  INFO |mapConfig_withLiteMemberJoiningLater_isImmediatelyAvailable| - [system] mapConfig_withLiteMemberJoiningLater_isImmediatelyAvailable - [127.0.0.1]:5702 [dev] [6.0.0-SNAPSHOT] Jet is enabled
08:34:16,081  INFO |mapConfig_withLiteMemberJoiningLater_isImmediatelyAvailable| - [MetricsConfigHelper] mapConfig_withLiteMemberJoiningLater_isImmediatelyAvailable - [127.0.0.1]:5702 [dev] [6.0.0-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
08:34:16,085  INFO |map_initialSubmitTest| - [JetServiceBackend] map_initialSubmitTest - [127.0.0.1]:5703 [dev] [6.0.0-SNAPSHOT] Setting number of cooperative threads and default parallelism to 2
08:34:16,085 DEBUG |map_testNonConflictingDynamicConfigWithTheSameName| - [JobCoordinationService] hz.ClientDynamicConfigSmokeTest_reverent_williams.cached.thread-3 - [127.0.0.1]:5701 [dev] [6.0.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
08:34:16,085  INFO |multimap_initialSubmitTest| - [JetServiceBackend] multimap_initialSubmitTest - [127.0.0.1]:5703 [dev] [6.0.0-SNAPSHOT] Setting number of cooperative threads and default parallelism to 2
08:34:16,086  INFO |cacheConfig_whenListenerIsRegistered| - [ClusterService] hz.ClientDynamicConfigSmokeTest_blissful_williams.priority-generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [6.0.0-SNAPSHOT] 

Members {size:2, ver:2} [
	Member [127.0.0.1]:5701 - b5e04c9c-453f-470f-841e-e49dbd4e8b6f
	Member [127.0.0.1]:5702 - 6543d63a-8154-4408-a03e-aa093e5ece1b this
]

08:34:16,086  INFO |cacheConfig_whenListenerIsRegistered| - [JobCoordinationService] cacheConfig_whenListenerIsRegistered - [127.0.0.1]:5702 [dev] [6.0.0-SNAPSHOT] Jet started scanning for jobs
08:34:16,087  INFO |cacheConfig_whenListenerIsRegistered| - [LifecycleService] cacheConfig_whenListenerIsRegistered - [127.0.0.1]:5702 [dev] [6.0.0-SNAPSHOT] [127.0.0.1]:5702 is STARTED
08:34:16,087  INFO |cacheConfig_whenListenerIsRegistered| - [AbstractConfigLocator] cacheConfig_whenListenerIsRegistered - Loading 'hazelcast-client-default.xml' from the classpath.

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-Openj9-21/43/

**Comment by JackPGreen** [comment]
This failure makes no sense - `String.format` is `null` safe, and `expectedType` can't be `null`, so how can a `NullPointerException` be thrown on line 1,446? Suspect JDK issue.

https://github.com/hazelcast/hazelcast/blob/f2051a13449d429956167d11489e7dc04dec3560/hazelcast/src/test/java/com/hazelcast/test/HazelcastTestSupport.java#L1438-L1450
