### ISSUE TITLE
Upgrading  vertx-hazelcast to 4.5.11 causes thread block upon identifying hazelcast instance uuid

### ISSUE THREAD

**Issue by saranyadevitrimble** [hazelcast/hazelcast#26460]
**Describe the bug**
     After upgrading from Vert.x 4.2.8 to Vert.x 4.5.11, which uses Hazelcast 5.3.5, we have observed a significant increase in idle CPU utilization (from around 10% to 60%) and frequent Thread blocked exceptions in our application. The specific error is triggered during Hazelcast MapProxyImpl.entrySet() queries, resulting in the following stack trace:
     `2024-11-15 11:52:44,139 354652 [vertx-blocked-thread-checker] WARN  i.v.core.impl.BlockedThreadChecker - Thread Thread[vert.x-eventloop-thread-2,5,main] has been blocked for 10139 ms, time limit is 2000 ms 
io.vertx.core.VertxException: Thread blocked
	at java.base/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.manageParking(AbstractInvocationFuture.java:694)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:616)
	at com.hazelcast.map.impl.query.QueryEngineImpl.addResultsOfPredicate(QueryEngineImpl.java:215)
	at com.hazelcast.map.impl.query.QueryEngineImpl.doRunOnQueryThreads(QueryEngineImpl.java:166)
	at com.hazelcast.map.impl.query.QueryEngineImpl.runOnGivenPartitions(QueryEngineImpl.java:142)
	at com.hazelcast.map.impl.query.QueryEngineImpl.execute(QueryEngineImpl.java:109)
	at com.hazelcast.map.impl.proxy.MapProxySupport.executeQueryInternal(MapProxySupport.java:1441)
	at com.hazelcast.map.impl.proxy.MapProxySupport.executeQueryInternal(MapProxySupport.java:1405)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.executePredicate(MapProxyImpl.java:801)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.entrySet(MapProxyImpl.java:750)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.entrySet(MapProxyImpl.java:744)
	at com.trimble.tcp.events.retriever.service.hzc.HazelcastService.getWorkerInstanceUuid(HazelcastService.java:58)
	at com.trimble.tcp.events.retriever.service.TaskManagerService.addNewTaskDetails(TaskManagerService.java:88)
	at com.trimble.tcp.events.retriever.service.TaskManagerService.doManageTask(TaskManagerService.java:70)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:1087)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:1063)
	at io.vertx.core.impl.ContextImpl.emit(ContextImpl.java:342)
	at io.vertx.core.impl.ContextImpl.emit(ContextImpl.java:335)
	at io.vertx.core.impl.ContextInternal.emit(ContextInternal.java:200)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.run(VertxImpl.java:1081)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:162)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)`

**Expected behavior**
      Minimal idle CPU utilization increase after upgrading.
      No thread-blocking issues during Hazelcast map operations.

**To Reproduce**

1. Upgrade a Vert.x application from version 4.2.8 to 4.5.11.
2. Use Hazelcast for distributed data operations.
3. Execute a query using MapProxyImpl.entrySet() or similar calls.
4. Observe increased CPU usage and thread-blocking behavior.

**Additional context**
Previous configuration: Vert.x 4.2.8 (with an older Hazelcast version).
Current configuration: Vert.x 4.5.11 (Hazelcast 5.3.5).
Using Vert.x dependencies: vertx-web-client, vertx-core, vertx-web, vertx-hazelcast, vertx-micrometer-metrics, vertx-mysql-client.

Please provide any guidance on potential changes in Hazelcast or Vert.x configurations that could mitigate these issues, or whether this indicates a possible regression or compatibility issue.

**Comment by guss77** [comment]
I also have numerous "thread blocked" with Hazelcast on Vert.x 4.5.11, and I also tried upgrading Hazelcast from 5.3.5 to 5.3.6 and now to 5.5.0 - without a change in behavior. For me the thread blocking is most apparent during node startup.
