### ISSUE TITLE
No DataSerializerFactory registered for namespace: 0

### ISSUE THREAD

**Issue by n0th1n6** [hazelcast/hazelcast#2794]
Hi,

Like in this issue https://github.com/hazelcast/hazelcast/issues/2026 I am also getting the same error when starting the second node while using hazelcast 3.2.3. I have also tried 

<pre>config.setClassLoader(getClass().getClassLoader());</pre>

<pre>
2014-06-23 18:37:03,145 | ERROR | eration.thread-5 | OperationService                   54 | 258 - com.hazelcast - 3.2.0 | [10.202.176.25]:5701 [sef-smfe] [3.2] No DataSerializerFactory registered for namespace: 0
com.hazelcast.nio.serialization.HazelcastSerializationException: No DataSerializerFactory registered for namespace: 0
        at com.hazelcast.nio.serialization.DataSerializer.read(DataSerializer.java:93)[258:com.hazelcast:3.2.0]
        at com.hazelcast.nio.serialization.DataSerializer.read(DataSerializer.java:36)[258:com.hazelcast:3.2.0]
        at com.hazelcast.nio.serialization.StreamSerializerAdapter.read(StreamSerializerAdapter.java:59)[258:com.hazelcast:3.2.0]
        at com.hazelcast.nio.serialization.SerializationServiceImpl.toObject(SerializationServiceImpl.java:221)[258:com.hazelcast:3.2.0]
        at com.hazelcast.spi.impl.NodeEngineImpl.toObject(NodeEngineImpl.java:156)[258:com.hazelcast:3.2.0]
        at com.hazelcast.spi.impl.BasicOperationService.processPacket(BasicOperationService.java:295)[258:com.hazelcast:3.2.0]
        at com.hazelcast.spi.impl.BasicOperationService.access$400(BasicOperationService.java:102)[258:com.hazelcast:3.2.0]
        at com.hazelcast.spi.impl.BasicOperationService$BasicOperationProcessorImpl.process(BasicOperationService.java:756)[258:com.hazelcast:3.2.0]
        at com.hazelcast.spi.impl.BasicOperationScheduler$ProcessTask.run(BasicOperationScheduler.java:182)[258:com.hazelcast:3.2.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_05]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_05]
        at java.lang.Thread.run(Thread.java:745)[:1.8.0_05]
        at com.hazelcast.util.executor.PoolExecutorThreadFactory$ManagedThread.run(PoolExecutorThreadFactory.java:59)[258:com.hazelcast:3.2.0]
</pre>

Here's part of the config

<pre>
   <group>
      <name>s01</name>
      <password>s01</password>
   </group>
   <network>
      <port auto-increment="false">5701</port>
      <interfaces enabled="true">
         <interface>xx.xxx.xxx.*</interface>
      </interfaces>
      <join>
         <tcp-ip enabled="true">
            <member>xx.xxx.xxx.1</member>
            <member>xx.xxx.xxx.2</member>
         </tcp-ip>
         <multicast enabled="false">
            <multicast-group>224.2.2.3</multicast-group>
            <multicast-port>54327</multicast-port>
         </multicast>
      </join>
   </network>
</pre>

**Comment by squinn** [comment]
For those that may be running into this problem in an OSGi environment, you may be getting bit by a nuance of the com.hazelcast.util.ServiceLoader.findHighestReachableClassLoader() method sometimes picking the wrong class loader during Hazelcast initialization (as it won't always pick the class loader you set on the config).  The following shows a way to work around that problem by taking advantage of Java's context class loader:

    private HazelcastInstance createHazelcastInstance() {  
        
        // Use the following if you're only using the Hazelcast data serializers   
        final ClassLoader classLoader = Hazelcast.class.getClassLoader();

        // Use the following if you have custom data serializers that you need
        // final ClassLoader classLoader = this.getClass().getClassLoader();
        
        final com.hazelcast.config.Config config = new com.hazelcast.config.Config();
        config.setClassLoader(classLoader);
        final ClassLoader previousContextClassLoader = Thread.currentThread().getContextClassLoader();
        try {
            Thread.currentThread().setContextClassLoader(classLoader);
            return Hazelcast.newHazelcastInstance(config);
        } finally {
            if(previousContextClassLoader != null) {
                Thread.currentThread().setContextClassLoader(previousContextClassLoader);
            }
        }
    }
