### ISSUE TITLE
Hazelcast Threads Hung

### ISSUE THREAD

**Issue by preetpuri** [hazelcast/hazelcast#2806]
Seeing lot of threads in Time_Waiting state which is causing the application to slow down.
Any thoughts?

Version -> 2.4 

**********************************************************************************************************************
From hazelcast thread dumps

"hz._hzInstance_1_test.cached.thread-1709" prio=10 tid=0x00007fee44444000 nid=0x66bc waiting on condition [0x00007fec0cf8e000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000512482178> (a java.util.concurrent.SynchronousQueue$TransferStack)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:198)
	at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:424)
	at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:323)
	at java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:874)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:945)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:907)
	at java.lang.Thread.run(Thread.java:662)
	at com.hazelcast.impl.ExecutorThreadFactory$1.run(ExecutorThreadFactory.java:38)
***********************************************************************************************************************
Hazlecast Logs - within 5 min Hazlecsae logs are filled with below warning

WARNING: 1001 ThreadContext is created!! You might have too many threads. Is that normal?

***********************************************************************************************************************
App thread dumps
 
"http--0.0.0.0-8080-1028" daemon prio=10 tid=0x00007feb6c6b4000 nid=0x1eb7 waiting on condition [0x00007fea71656000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000546f83280> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:198)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2116)
	at com.hazelcast.util.ResponseQueueFactory$LockBasedResponseQueue.poll(ResponseQueueFactory.java:63)
	at com.hazelcast.client.Call.getResponse(Call.java:82)
	at com.hazelcast.client.ProxyHelper.doCall(ProxyHelper.java:67)
	at com.hazelcast.client.ProxyHelper.callAndGetResult(ProxyHelper.java:59)
	at com.hazelcast.client.ProxyHelper.doOp(ProxyHelper.java:145)
	at com.hazelcast.client.ProxyHelper.doOp(ProxyHelper.java:140)
	at com.hazelcast.client.MapClientProxy.remove(MapClientProxy.java:329)

**Comment by enesakar** [comment]
Closing the issue. Can you check if issue exists in 3.x versions?
