### ISSUE TITLE
Transactional Queues broken

### ISSUE THREAD

**Issue by kwitten** [hazelcast/hazelcast#2838]
Seems like the transactional queues are not compatible with the backup service. I get transaction exceptions when starting a new instance. 

2014-06-26_20:01:49.89440 Jun 26, 2014 3:01:49 PM com.hazelcast.transaction.impl.ReplicateTxOperation
2014-06-26_20:01:49.89495 SEVERE: [172.16.2.82]:5701 [scan-group] [3.2.3] Could not find begin tx log!
2014-06-26_20:01:49.89496 com.hazelcast.transaction.TransactionException: Could not find begin tx log!
2014-06-26_20:01:49.89496 	at com.hazelcast.transaction.impl.TransactionManagerServiceImpl.prepareTxBackupLog(TransactionManagerServiceImpl.java:250)
2014-06-26_20:01:49.89497 	at com.hazelcast.transaction.impl.ReplicateTxOperation.run(ReplicateTxOperation.java:59)
2014-06-26_20:01:49.89497 	at com.hazelcast.spi.impl.BasicOperationService.processOperation(BasicOperationService.java:363)
2014-06-26_20:01:49.89497 	at com.hazelcast.spi.impl.BasicOperationService.processPacket(BasicOperationService.java:309)
2014-06-26_20:01:49.89497 	at com.hazelcast.spi.impl.BasicOperationService.access$400(BasicOperationService.java:102)
2014-06-26_20:01:49.89498 	at com.hazelcast.spi.impl.BasicOperationService$BasicOperationProcessorImpl.process(BasicOperationService.java:756)
2014-06-26_20:01:49.89498 	at com.hazelcast.spi.impl.BasicOperationScheduler$ProcessTask.run(BasicOperationScheduler.java:186)
2014-06-26_20:01:49.89498 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
2014-06-26_20:01:49.89499 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
2014-06-26_20:01:49.89499 	at java.lang.Thread.run(Thread.java:744)

And

2014-06-26_20:02:18.79105 SEVERE: [172.16.2.82]:5701 [scan-group] [3.2.3] Backup reserve failed: 0
2014-06-26_20:02:18.79106 com.hazelcast.transaction.TransactionException: Backup reserve failed: 0
2014-06-26_20:02:18.79106 	at com.hazelcast.queue.QueueContainer.txnPollBackupReserve(QueueContainer.java:133)
2014-06-26_20:02:18.79106 	at com.hazelcast.queue.tx.TxnPrepareBackupOperation.run(TxnPrepareBackupOperation.java:48)
2014-06-26_20:02:18.79106 	at com.hazelcast.spi.impl.BasicOperationService.processOperation(BasicOperationService.java:363)
2014-06-26_20:02:18.79107 	at com.hazelcast.spi.impl.BasicOperationService.runOperation(BasicOperationService.java:228)
2014-06-26_20:02:18.79107 	at com.hazelcast.spi.impl.Backup.run(Backup.java:98)
2014-06-26_20:02:18.79107 	at com.hazelcast.spi.impl.BasicOperationService.processOperation(BasicOperationService.java:363)
2014-06-26_20:02:18.79107 	at com.hazelcast.spi.impl.BasicOperationService.processPacket(BasicOperationService.java:309)
2014-06-26_20:02:18.79108 	at com.hazelcast.spi.impl.BasicOperationService.access$400(BasicOperationService.java:102)
2014-06-26_20:02:18.79108 	at com.hazelcast.spi.impl.BasicOperationService$BasicOperationProcessorImpl.process(BasicOperationService.java:756)
2014-06-26_20:02:18.79110 	at com.hazelcast.spi.impl.BasicOperationScheduler$PartitionThread.process(BasicOperationScheduler.java:276)
2014-06-26_20:02:18.79111 	at com.hazelcast.spi.impl.BasicOperationScheduler$PartitionThread.doRun(BasicOperationScheduler.java:270)
2014-06-26_20:02:18.79111 	at com.hazelcast.spi.impl.BasicOperationScheduler$PartitionThread.run(BasicOperationScheduler.java:245)
20

**Comment by kwitten** [comment]
As @bentmann points out this is not a duplicate of #2805, we are still experiencing this issue with version 3.3.1. 

Please reopen this issue.

**Comment by gurbuzali** [comment]
I'm reopening the issue then
Can you please provide a test-code to reproduce the issue ?
Have you tried latest version to see if the issue disappears ?

**Comment by kwitten** [comment]
I don't have test code that can reproduce this issue. It seems to happen sporadically on our cluster.

Here is the stack trace for version 3.1.1

com.hazelcast.transaction.TransactionException: Could not find begin tx log!
        at com.hazelcast.transaction.impl.TransactionManagerServiceImpl.prepareTxBackupLog(TransactionManagerServiceImpl.java:299) ~[hazelcast-3.3.1.jar:3.3.1]
        at com.hazelcast.transaction.impl.ReplicateTxOperation.run(ReplicateTxOperation.java:57) ~[hazelcast-3.3.1.jar:3.3.1]
        at com.hazelcast.spi.impl.BasicOperationService$OperationHandler.handle(BasicOperationService.java:699) [hazelcast-3.3.1.jar:3.3.1]
        at com.hazelcast.spi.impl.BasicOperationService$OperationHandler.access$400(BasicOperationService.java:675) [hazelcast-3.3.1.jar:3.3.1]
        at com.hazelcast.spi.impl.BasicOperationService$OperationPacketHandler.handle(BasicOperationService.java:649) [hazelcast-3.3.1.jar:3.3.1]
        at com.hazelcast.spi.impl.BasicOperationService$OperationPacketHandler.handle(BasicOperationService.java:604) [hazelcast-3.3.1.jar:3.3.1]
        at com.hazelcast.spi.impl.BasicOperationService$OperationPacketHandler.access$1400(BasicOperationService.java:591) [hazelcast-3.3.1.jar:3.3.1]
        at com.hazelcast.spi.impl.BasicOperationService$BasicDispatcherImpl.dispatch(BasicOperationService.java:543) [hazelcast-3.3.1.jar:3.3.1]
        at com.hazelcast.spi.impl.BasicOperationScheduler$OperationThread.process(BasicOperationScheduler.java:439) [hazelcast-3.3.1.jar:3.3.1]
        at com.hazelcast.spi.impl.BasicOperationScheduler$OperationThread.doRun(BasicOperationScheduler.java:433) [hazelcast-3.3.1.jar:3.3.1]
        at com.hazelcast.spi.impl.BasicOperationScheduler$OperationThread.run(BasicOperationScheduler.java:408) [hazelcast-3.3.1.jar:3.3.1]

**Comment by gurbuzali** [comment]
Have you tried latest version to see if the issue disappears ?

**Comment by bwzhang2011** [comment]
@kwitten, have you tried hz3.3.5, such version is stable than 3.3.1

**Comment by kwitten** [comment]
Upgraded to 3.4.1 and still see this .

**Comment by bwzhang2011** [comment]
@gurbuzali, any update with such issue ?

**Comment by bwzhang2011** [comment]
@kwitten, did you test it with 3.5 EA2 snapshot

**Comment by bwzhang2011** [comment]
@kwitten, any update with such issue in hz3.5.1 or hz3.6 snapshot ?

**Comment by kwitten** [comment]
@bwzhang2011 We are still running 3.4.2 so I'm not sure if the newer versions fix this or not. If we upgrade in the near future I'll let you  know.

**Comment by bwzhang2011** [comment]
@kwitten thanks for feed back. there's no doubt that hz3.5+ bettern than 3.4.x but transaction improvement for distribute data structure still not found in the latest manual but it's recommended to update to such version.

**Comment by bwzhang2011** [comment]
@kwitten, any update with such issue ?
