### ISSUE TITLE
3.3-RC2: IMap#keySet triggers value deserialization

### ISSUE THREAD

**Issue by kennymacleod** [hazelcast/hazelcast#3008]
Starting in 3.3-RC2, we've noticed that calling `IMap#keySet()` triggers deserialization of the values in the map. This did not occur with RC1 (or EA1, EA2 or 3.2.x).

Here's a short program to demonstrate. Note that when we call `IMap#keySet` or `IMap#localKeySet`, we see `TestValue#readResolve` being invoked, indicating deserialization has taken place.

This is obviously a very serious performance problem.

```
public class HazelcastGetKeysTester
{
    public static void main(String[] args) throws Exception
    {
        final Config config = new XmlConfigBuilder().build();
        config.getNetworkConfig().getJoin().getMulticastConfig().setEnabled(false);
        HazelcastInstance hazelcastInstance = Hazelcast.newHazelcastInstance(config);

        final IMap<String, TestValue> map = hazelcastInstance.getMap("mymap");

        System.out.println("Adding value to IMap");
        map.set("key1", new TestValue("value1"));

        System.out.println("Getting value from IMap");
        map.get("key1");

        System.out.println("Getting keys from IMap");
        map.keySet();

        System.out.println("Getting local keys from IMap");
        map.localKeySet();

        Hazelcast.shutdownAll();
    }

    public static class TestValue implements Serializable
    {
        private final String value;

        public TestValue(final String value)
        {
            this.value = value;
        }

        private Object readResolve()
        {
            System.out.println("Deserializing " + value);
            return this;
        }
    }
}
```

**Comment by andrey-yemelyanov** [comment]
Hi,

I am seeing this problem in Hazelcast 4.1.1. When calling map.keySet(), values will be deserialized. Is it a feature now? Please advise how I can retrieve just the keys in a certain map.

**Comment by ahmetmircik** [comment]
Hi @andrey-yemelyanov, 

Normally, deserialization shouldn't happen. Could you please share a reproducer?

**Comment by andrey-yemelyanov** [comment]
Hi,

This is basically the code we are running on an IMap instance.

for (String key : map.keySet()) {
            if (sb.charAt(sb.length() - 1) != '[') {
                sb.append(", ");
            }
            sb.append("\"" + key + "\"");
            sb.append("\"," + map.getEntryView(key).getExpirationTime() + "\"");
        }

But getting a serialization exception:

Exception thrown by application class 'com.hazelcast.internal.serialization.impl.defaultserializers.JavaDefaultSerializers$JavaSerializer.read:87'
com.hazelcast.nio.serialization.HazelcastSerializationException: java.lang.ClassNotFoundException: com.vcc.vida.cache.CacheWrapper
	at com.hazelcast.internal.serialization.impl.defaultserializers.JavaDefaultSerializers$JavaSerializer.read(JavaDefaultSerializers.java:87)
	at com.hazelcast.internal.serialization.impl.defaultserializers.JavaDefaultSerializers$JavaSerializer.read(JavaDefaultSerializers.java:76)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:44)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:205)
	at com.hazelcast.map.impl.record.Records.tryStoreIntoCache(Records.java:164)
	at com.hazelcast.map.impl.record.Records.getValueOrCachedValue(Records.java:131)
	at com.hazelcast.map.impl.query.PartitionScanRunner$1.accept(PartitionScanRunner.java:99)
	at com.hazelcast.map.impl.query.PartitionScanRunner$1.accept(PartitionScanRunner.java:94)
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.forEach(DefaultRecordStore.java:234)
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.forEach(DefaultRecordStore.java:218)
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.forEachAfterLoad(DefaultRecordStore.java:247)
	at com.hazelcast.map.impl.query.PartitionScanRunner.run(PartitionScanRunner.java:94)
	at com.hazelcast.map.impl.query.CallerRunsPartitionScanExecutor.execute(CallerRunsPartitionScanExecutor.java:43)
	at com.hazelcast.map.impl.query.QueryRunner.runPartitionIndexOrPartitionScanQueryOnGivenOwnedPartition(QueryRunner.java:219)
	at com.hazelcast.map.impl.query.QueryPartitionOperation.runInternal(QueryPartitionOperation.java:46)
	at com.hazelcast.map.impl.operation.MapOperation.run(MapOperation.java:112)
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:184)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:256)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:237)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:213)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:160)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:138)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
	at ------ submitted from ------.()
	at com.hazelcast.internal.util.ExceptionUtil.cloneExceptionWithFixedAsyncStackTrace(ExceptionUtil.java:265)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.returnOrThrowWithGetConventions(InvocationFuture.java:112)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:100)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:606)
	at com.hazelcast.client.impl.protocol.task.map.AbstractMapQueryMessageTask.collectResultsFromMissingPartitions(AbstractMapQueryMessageTask.java:247)
	at com.hazelcast.client.impl.protocol.task.map.AbstractMapQueryMessageTask.invokeOnMissingPartitions(AbstractMapQueryMessageTask.java:136)
	at com.hazelcast.client.impl.protocol.task.map.AbstractMapQueryMessageTask.call(AbstractMapQueryMessageTask.java:100)
	at com.hazelcast.client.impl.protocol.task.AbstractCallableMessageTask.processMessage(AbstractCallableMessageTask.java:35)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:153)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:116)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:834)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
	at ------ submitted from ------.()
	at com.hazelcast.internal.util.ExceptionUtil.cloneExceptionWithFixedAsyncStackTrace(ExceptionUtil.java:265)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.returnOrThrowWithGetConventions(InvocationFuture.java:112)
	at com.hazelcast.client.impl.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:95)
	at com.hazelcast.client.impl.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:40)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:614)
	at com.hazelcast.client.impl.spi.ClientProxy.invoke(ClientProxy.java:215)
	at com.hazelcast.client.impl.proxy.ClientMapProxy.keySet(ClientMapProxy.java:1105)
	at com.vcc.vida.restws.resources.operations.CacheOperationsResource.getCacheObjectContent(CacheOperationsResource.java:81)
	at com.vcc.vida.restws.resources.operations.CacheOperationsResource$Proxy$_$$_WeldClientProxy.getCacheObjectContent(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor1417.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at com.ibm.ws.jaxrs20.server.LibertyJaxRsServerFactoryBean.performInvocation(LibertyJaxRsServerFactoryBean.java:652)
	at [internal classes]
	at com.vcc.vida.operations.filter.OperationsAuthorizationFilter.doFilter(OperationsAuthorizationFilter.java:76)
	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)
	at [internal classes]
Caused by: java.lang.ClassNotFoundException: com.vcc.vida.cache.CacheWrapper
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at com.hazelcast.internal.nio.ClassLoaderUtil.tryLoadClass(ClassLoaderUtil.java:289)
	at com.hazelcast.internal.nio.ClassLoaderUtil.loadClass(ClassLoaderUtil.java:249)
	at com.hazelcast.internal.nio.IOUtil$ClassLoaderAwareObjectInputStream.resolveClass(IOUtil.java:783)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1995)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1862)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2169)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1679)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:493)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:451)
	at com.hazelcast.internal.serialization.impl.defaultserializers.JavaDefaultSerializers$JavaSerializer.read(JavaDefaultSerializers.java:83)
	at com.hazelcast.internal.serialization.impl.defaultserializers.JavaDefaultSerializers$JavaSerializer.read(JavaDefaultSerializers.java:76)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:44)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:205)
	at com.hazelcast.map.impl.record.Records.tryStoreIntoCache(Records.java:164)
	at com.hazelcast.map.impl.record.Records.getValueOrCachedValue(Records.java:131)
	at com.hazelcast.map.impl.query.PartitionScanRunner$1.accept(PartitionScanRunner.java:99)
	at com.hazelcast.map.impl.query.PartitionScanRunner$1.accept(PartitionScanRunner.java:94)
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.forEach(DefaultRecordStore.java:234)
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.forEach(DefaultRecordStore.java:218)
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.forEachAfterLoad(DefaultRecordStore.java:247)
	at com.hazelcast.map.impl.query.PartitionScanRunner.run(PartitionScanRunner.java:94)
	at com.hazelcast.map.impl.query.CallerRunsPartitionScanExecutor.execute(CallerRunsPartitionScanExecutor.java:43)
	at com.hazelcast.map.impl.query.QueryRunner.runPartitionIndexOrPartitionScanQueryOnGivenOwnedPartition(QueryRunner.java:219)
	at com.hazelcast.map.impl.query.QueryPartitionOperation.runInternal(QueryPartitionOperation.java:46)
	at com.hazelcast.map.impl.operation.MapOperation.run(MapOperation.java:112)
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:184)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:256)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:237)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:213)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:160)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:138)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
