### ISSUE TITLE
[TEST-FAILURE] BackupTest.testBackupRemoveWhenOwnerNodeDead

### ISSUE THREAD

**Issue by serkan-ozal** [hazelcast/hazelcast#3064]
~~~~~
java.lang.AssertionError: Remove failed! 
Expected :0
Actual   :1
 	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:555)
	at com.hazelcast.map.BackupTest.testBackupRemoveWhenOwnerNodeDead(BackupTest.java:556)
~~~~~

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-sonar/com.hazelcast$hazelcast/551/testReport/junit/com.hazelcast.map/BackupTest/testBackupRemoveWhenOwnerNodeDead/

**Comment by mesutcelik** [comment]
no failure recently.
