### ISSUE TITLE
[lock] [transaction] [queue] TxnQueueWithLockTest - Current thread is not owner of the lock,  AsynchronousCloseException,  Error during rollback!

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#3083]
Stabilizer test: com.hazelcast.stabilizer.tests.queue.TxnQueueWithLockTest

With softKill member node during run

 expected number of items in Q:  <1661> but was:<1882>
TxnQ: TxnCounter{committed=1662, rolled=1} from   5 (threads)
should have been 6, so 1 of the "worker" threads,  died during the test.  accounting for the large difference in the Q size assertion. 

```
WARN  2014-07-25 09:28:19,159 [hz.client_0_workers.cluster-listener] com.hazelcast.client.spi.impl.ClusterListenerThread: Error while listening cluster events! -> ClientConnection{live=false, writeHandler=com.hazelcast.client.connection.nio.ClientWriteHandler@488a5770, readHandler=com.hazelcast.client.connection.nio.ClientReadHandler@72729f44, connectionId=1, socketChannel=DefaultSocketChannelWrapper{socketChannel=java.nio.channels.SocketChannel[closed]}, remoteEndpoint=Address[10.231.41.49]:5701}

java.nio.channels.AsynchronousCloseException
    at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:205)
    at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:412)
    at com.hazelcast.nio.tcp.DefaultSocketChannelWrapper.read(DefaultSocketChannelWrapper.java:59)
    at com.hazelcast.client.connection.nio.ClientConnection.read(ClientConnection.java:195)
    at com.hazelcast.client.spi.impl.ClusterListenerThread.listenMembershipEvents(ClusterListenerThread.java:175)
    at com.hazelcast.client.spi.impl.ClusterListenerThread.run(ClusterListenerThread.java:89)






java.lang.IllegalMonitorStateException: Current thread is not owner of the lock! -> Owner: 139aa449-914f-4439-ac43-ff6fac2868c3, thread-id: 27
    at com.hazelcast.concurrent.lock.operations.UnlockOperation.ensureUnlocked(UnlockOperation.java:71)
    at com.hazelcast.concurrent.lock.operations.UnlockOperation.unlock(UnlockOperation.java:65)
    at com.hazelcast.concurrent.lock.operations.UnlockOperation.run(UnlockOperation.java:57)
    at com.hazelcast.spi.impl.BasicOperationService$OperationHandler.handle(BasicOperationService.java:673)
    at com.hazelcast.spi.impl.BasicOperationService$OperationHandler.access$400(BasicOperationService.java:649)
    at com.hazelcast.spi.impl.BasicOperationService$BasicDispatcherImpl.dispatch(BasicOperationService.java:527)
    at com.hazelcast.spi.impl.BasicOperationScheduler$OperationThread.process(BasicOperationScheduler.java:439)
    at com.hazelcast.spi.impl.BasicOperationScheduler$OperationThread.doRun(BasicOperationScheduler.java:433)
    at com.hazelcast.spi.impl.BasicOperationScheduler$OperationThread.run(BasicOperationScheduler.java:408)
    at ------ End remote and begin local stack-trace ------.(Unknown Source)
    at com.hazelcast.client.spi.impl.ClientCallFuture.resolveResponse(ClientCallFuture.java:194)
    at com.hazelcast.client.spi.impl.ClientCallFuture.get(ClientCallFuture.java:136)
    at com.hazelcast.client.spi.impl.ClientCallFuture.get(ClientCallFuture.java:113)
    at com.hazelcast.client.spi.ClientProxy.invoke(ClientProxy.java:112)
    at com.hazelcast.client.proxy.ClientLockProxy.invoke(ClientLockProxy.java:130)
    at com.hazelcast.client.proxy.ClientLockProxy.unlock(ClientLockProxy.java:111)
    at com.hazelcast.stabilizer.tests.queue.TxnQueueWithLockTest$Worker.run(TxnQueueWithLockTest.java:93)
    at java.lang.Thread.run(Thread.java:745)
    at com.hazelcast.stabilizer.tests.utils.ThreadSpawner$DefaultThread.run(ThreadSpawner.java:88)




[10.231.41.49]:5701 [workers] [3.3-RC3-SNAPSHOT] Error during rollback!
java.util.concurrent.ExecutionException: com.hazelcast.core.HazelcastInstanceNotActiveException: Hazelcast instance is not active!
    at com.hazelcast.spi.impl.BasicInvocationFuture.resolveApplicationResponseOrThrowException(BasicInvocationFuture.java:305)
    at com.hazelcast.spi.impl.BasicInvocationFuture.get(BasicInvocationFuture.java:181)
    at com.hazelcast.transaction.impl.TransactionImpl.rollback(TransactionImpl.java:324)
    at com.hazelcast.transaction.impl.TransactionContextImpl.rollbackTransaction(TransactionContextImpl.java:91)
    at com.hazelcast.client.ClientEndpoint.destroy(ClientEndpoint.java:227)
    at com.hazelcast.client.ClientEngineImpl.shutdown(ClientEngineImpl.java:283)
    at com.hazelcast.spi.impl.ServiceManager.shutdownService(ServiceManager.java:224)
    at com.hazelcast.spi.impl.ServiceManager.shutdown(ServiceManager.java:215)
    at com.hazelcast.spi.impl.NodeEngineImpl.shutdown(NodeEngineImpl.java:388)
    at com.hazelcast.instance.Node.shutdown(Node.java:420)
    at com.hazelcast.instance.Node$NodeShutdownHookThread.run(Node.java:511)
Caused by: com.hazelcast.core.HazelcastInstanceNotActiveException: Hazelcast instance is not active!
    at com.hazelcast.spi.impl.BasicInvocation.engineActive(BasicInvocation.java:304)
    at com.hazelcast.spi.impl.BasicInvocation.doInvoke(BasicInvocation.java:257)
    at com.hazelcast.spi.impl.BasicInvocation.invoke(BasicInvocation.java:232)
    at com.hazelcast.spi.impl.BasicOperationService.invokeOnPartition(BasicOperationService.java:237)
    at com.hazelcast.queue.tx.QueueTransactionLog.invoke(QueueTransactionLog.java:67)
    at com.hazelcast.queue.tx.QueueTransactionLog.rollback(QueueTransactionLog.java:85)
    at com.hazelcast.transaction.impl.TransactionImpl.rollback(TransactionImpl.java:320)
    ... 8 more

```

**Comment by Danny-Hazelcast** [comment]
old issue, no longer relevant.
