### ISSUE TITLE
ClientMapIssueTest.testListenerRegistrations

### ISSUE THREAD

**Issue by mesutcelik** [hazelcast/hazelcast#3118]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance/com.hazelcast$hazelcast-client/387/testReport/junit/com.hazelcast.client.map/ClientMapIssueTest/testListenerRegistrations/

```
java.lang.AssertionError: there should be only one registrations expected:<1> but was:<0>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at com.hazelcast.client.map.ClientMapIssueTest.testListenerRegistrations(ClientMapIssueTest.java:92)
```

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: there should be only one registration expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.client.map.ClientMapIssueTest$1.run(ClientMapIssueTest.java:88)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:835)
	at com.hazelcast.client.map.ClientMapIssueTest.testListenerRegistrations(ClientMapIssueTest.java:82)
```

https://hazelcast-l337.ci.cloudbees.com/view/Quality-Outreach/job/Hazelcast-3.x-OpenJDK8-Quality-Outreach/com.hazelcast$hazelcast-client/254/testReport/junit/com.hazelcast.client.map/ClientMapIssueTest/testListenerRegistrations/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: there should be only one registration expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.client.map.ClientMapIssueTest$1.run(ClientMapIssueTest.java:90)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:851)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:865)
	at com.hazelcast.client.map.ClientMapIssueTest.testListenerRegistrations(ClientMapIssueTest.java:84)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.maintenance-OracleJDK1.6/com.hazelcast$hazelcast-client/374/testReport/junit/com.hazelcast.client.map/ClientMapIssueTest/testListenerRegistrations/

**Comment by ahmetmircik** [comment]
no recent failure exists.

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: there should be only one registration expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.client.map.ClientMapIssueTest$1.run(ClientMapIssueTest.java:91)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:905)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:919)
	at com.hazelcast.client.map.ClientMapIssueTest.testListenerRegistrations(ClientMapIssueTest.java:85)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-ZuluJDK6/com.hazelcast$hazelcast-client/141/testReport/junit/com.hazelcast.client.map/ClientMapIssueTest/testListenerRegistrations/

**Comment by sancar** [comment]
Fixed by https://github.com/hazelcast/hazelcast/pull/9588
