### ISSUE TITLE
ClientMapTest.testMapStatistics

### ISSUE THREAD

**Issue by mesutcelik** [hazelcast/hazelcast#3138]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OracleJDK1.6/com.hazelcast$hazelcast-client/242/testReport/junit/com.hazelcast.client.map/ClientMapTest/testMapStatistics/

```
java.lang.AssertionError: get count expected:<1000> but was:<999>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at com.hazelcast.client.map.ClientMapTest.testMapStatistics(ClientMapTest.java:860)
```

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: get latency
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.client.map.ClientMapTest.testMapStatistics(ClientMapTest.java:820)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.8/com.hazelcast$hazelcast-client/578/testReport/junit/com.hazelcast.client.map/ClientMapTest/testMapStatistics/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: get latency
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.client.map.ClientMapTest.testMapStatistics(ClientMapTest.java:820)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-ZuluJDK7/com.hazelcast$hazelcast-client/581/testReport/junit/com.hazelcast.client.map/ClientMapTest/testMapStatistics/

**Comment by sancar** [comment]
Same failing scenario as https://github.com/hazelcast/hazelcast/issues/10025.
Merging to https://github.com/hazelcast/hazelcast/issues/10025.
