### ISSUE TITLE
InterruptedException in PartitionIteratingOperation then instance becomes inactive

### ISSUE THREAD

**Issue by agherardi** [hazelcast/hazelcast#3217]
Hi,
After running my application for a few days on a 2-server cluster, I see the following error in the log:

```
ERROR [2014-08-09 12:14:20,690] com.hazelcast.spi.impl.PartitionIteratingOperation: [192.168.240.24]:5701 [vmscore_1] [3.2] null^M
! java.lang.InterruptedException: null^M
! at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(Unknown Source) ~[na:1.7.0_51]^M
! at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source) ~[na:1.7.0_51]^M
! at com.hazelcast.util.ResponseQueueFactory$LockBasedResponseQueue.take(ResponseQueueFactory.java:47) ~[vmscore-1.0.0-SNAPSHOT-fat.jar:1.0.0-SNAPSHOT]^M
! at com.hazelcast.spi.impl.PartitionIteratingOperation$ResponseQueue.get(PartitionIteratingOperation.java:104) ~[vmscore-1.0.0-SNAPSHOT-fat.jar:1.0.0-SNAPSHOT]^M
! at com.hazelcast.spi.impl.PartitionIteratingOperation.run(PartitionIteratingOperation.java:66) ~[vmscore-1.0.0-SNAPSHOT-fat.jar:1.0.0-SNAPSHOT]^M
! at com.hazelcast.spi.impl.BasicOperationService.processOperation(BasicOperationService.java:363) [vmscore-1.0.0-SNAPSHOT-fat.jar:1.0.0-SNAPSHOT]^M
! at com.hazelcast.spi.impl.BasicOperationService.processPacket(BasicOperationService.java:309) [vmscore-1.0.0-SNAPSHOT-fat.jar:1.0.0-SNAPSHOT]^M
! at com.hazelcast.spi.impl.BasicOperationService.access$400(BasicOperationService.java:102) [vmscore-1.0.0-SNAPSHOT-fat.jar:1.0.0-SNAPSHOT]^M
! at com.hazelcast.spi.impl.BasicOperationService$BasicOperationProcessorImpl.process(BasicOperationService.java:756) [vmscore-1.0.0-SNAPSHOT-fat.jar:1.0.0-SNAPSHOT]^M
! at com.hazelcast.spi.impl.BasicOperationScheduler$ProcessTask.run(BasicOperationScheduler.java:186) [vmscore-1.0.0-SNAPSHOT-fat.jar:1.0.0-SNAPSHOT]^M
! at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.7.0_51]^M
! at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.7.0_51]^M
! at java.lang.Thread.run(Unknown Source) [na:1.7.0_51]^M
! at com.hazelcast.util.executor.PoolExecutorThreadFactory$ManagedThread.run(PoolExecutorThreadFactory.java:59) [vmscore-1.0.0-SNAPSHOT-fat.jar:1.0.0-SNAPSHOT]^M
WARN  [2014-08-09 12:14:21,111] com.hazelcast.spi.impl.BasicInvocation: [192.168.240.24]:5701 [vmscore_1] [3.2] No response for 120011 ms. InvocationFuture{invocation=BasicInvocation{ serviceName='hz:impl:queueService', op=com.hazelcast.queue.PollOperation@3f180ce4, partitionId=134, replicaIndex=0, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeout=60000, target=Address[192.168.240.24]:5701}, done=false}

Shortly after, Hazelcast stops working. The logs says that the instance is no longer active:

WARN  [2014-08-09 12:14:21,111] com.hazelcast.spi.impl.BasicInvocation: [192.168.240.24]:5701 [vmscore_1] [3.2] While asking 'is-executing': InvocationFuture{invocation=BasicInvocation{ serviceName='hz:impl:lockService', op=com.hazelcast.concurrent.lock.operations.LockOperation@7ccb168f, partitionId=134, replicaIndex=0, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeout=60000, target=Address[192.168.240.24]:5701}, done=false}^M
! java.util.concurrent.ExecutionException: com.hazelcast.core.HazelcastInstanceNotActiveException: Hazelcast instance is not active!^M
! at com.hazelcast.spi.impl.BasicInvocation$InvocationFuture.resolveResponseOrThrowException(BasicInvocation.java:792) [vmscore-1.0.0-SNAPSHOT-fat.jar:1.0.0-SNAPSHOT]^M
! at com.hazelcast.spi.impl.BasicInvocation$InvocationFuture.get(BasicInvocation.java:696) [vmscore-1.0.0-SNAPSHOT-fat.jar:1.0.0-SNAPSHOT]^M
! at com.hazelcast.spi.impl.BasicInvocation$InvocationFuture.isOperationExecuting(BasicInvocation.java:875) [vmscore-1.0.0-SNAPSHOT-fat.jar:1.0.0-SNAPSHOT]^M
! at com.hazelcast.spi.impl.BasicInvocation$InvocationFuture.waitForResponse(BasicInvocation.java:753) [vmscore-1.0.0-SNAPSHOT-fat.jar:1.0.0-SNAPSHOT]^M
! at com.hazelcast.spi.impl.BasicInvocation$InvocationFuture.get(BasicInvocation.java:695) [vmscore-1.0.0-SNAPSHOT-fat.jar:1.0.0-SNAPSHOT]^M
! at com.hazelcast.spi.impl.BasicInvocation$InvocationFuture.get(BasicInvocation.java:674) [vmscore-1.0.0-SNAPSHOT-fat.jar:1.0.0-SNAPSHOT]^M
! at com.hazelcast.spi.impl.BasicInvocation$InvocationFuture.getSafely(BasicInvocation.java:687) [vmscore-1.0.0-SNAPSHOT-fat.jar:1.0.0-SNAPSHOT]^M
! at com.hazelcast.concurrent.lock.LockProxySupport.lock(LockProxySupport.java:80) [vmscore-1.0.0-SNAPSHOT-fat.jar:1.0.0-SNAPSHOT]^M
! at com.hazelcast.concurrent.lock.LockProxySupport.lock(LockProxySupport.java:74) [vmscore-1.0.0-SNAPSHOT-fat.jar:1.0.0-SNAPSHOT]^M
! at com.hazelcast.map.proxy.MapProxyImpl.lock(MapProxyImpl.java:233) [vmscore-1.0.0-SNAPSHOT-fat.jar:1.0.0-SNAPSHOT]^M
```

Any suggestions?

Thanks in advance.

**Comment by mnkanojia** [comment]
Hi agherardi,
Did you find out what your issue was? I am facing the same issue.

**Comment by pveentjer** [comment]
Which HZ version are you using.

**Comment by mdogan** [comment]
`PartitionIteratingOperation ` is non-blocking since 3.8. https://github.com/hazelcast/hazelcast/pull/8893
