### ISSUE TITLE
[TEST-FAILURE] EntryProcessorStressTest.dropedEntryProcessorTest_withKeyOwningNodeTermination

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#3329]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-problematicTest/com.hazelcast$hazelcast/225/testReport/com.hazelcast.map/EntryProcessorStressTest/dropedEntryProcessorTest_withKeyOwningNodeTermination/
```
java.lang.AssertionError: failed to execute all entry processor tasks at iteration
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.map.EntryProcessorStressTest$1.run(EntryProcessorStressTest.java:87)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:236)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:252)
	at com.hazelcast.map.EntryProcessorStressTest.dropedEntryProcessorTest_withKeyOwningNodeTermination(EntryProcessorStressTest.java:82)
```

**Comment by enesakar** [comment]
closing test failures whose test has not failed in last month
