### ISSUE TITLE
ClientLockWithTerminationTest.testLockOnClient_withNodeCrash

### ISSUE THREAD

**Issue by mdogan** [hazelcast/hazelcast#3422]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-pr-builder/com.hazelcast$hazelcast-client/10092/testReport/junit/com.hazelcast.client.lock/ClientLockWithTerminationTest/testLockOnClient_withNodeCrash/

```
Error Message

Lock was obtained by 2 different clients 
Stacktrace

java.lang.AssertionError: Lock was obtained by 2 different clients 
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.assertTrue(Assert.java:41)
    at org.junit.Assert.assertFalse(Assert.java:64)
    at com.hazelcast.client.lock.ClientLockWithTerminationTest.testLockOnClient_withNodeCrash(ClientLockWithTerminationTest.java:87)
```

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance/com.hazelcast$hazelcast-client/752/testReport/junit/com.hazelcast.client.lock/ClientLockWithTerminationTest/testLockOnClient_withNodeCrash/

**Comment by sancar** [comment]
Not able to reproduce at the moment. 

Here a critical finding for future assignee. 
There is a class cast exception in the logs. This log is from ClusterListenerThread and related to response packages from blocking owner connection . This log is indication of something is not right but I could not find(or reproduce) the exact scenario. 

Note that this issue is not applicable to master(3.5), since we do not have an separate blocking connection anymore in the 3.5-SNAPSHOT.  

23:18:15,639  WARN [ClusterListenerThread] hz.client_106_dev.cluster-listener - Error while listening cluster events! -> ClientConnection{live=true, writeHandler=com.hazelcast.client.connection.nio.ClientWriteHandler@5388ecec, readHandler=com.hazelcast.client.connection.nio.ClientReadHandler@427aa4cc, connectionId=4, socketChannel=DefaultSocketChannelWrapper{socketChannel=java.nio.channels.SocketChannel[connected local=/127.0.0.1:51069 remote=/127.0.0.1:5701]}, remoteEndpoint=Address[127.0.0.1]:5701}, Error: java.lang.ClassCastException: com.hazelcast.cluster.client.ClientMembershipEvent cannot be cast to com.hazelcast.spi.impl.SerializableCollection

log is from following cloudbees build( same with the one mesut shared )
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance/com.hazelcast$hazelcast-client/752/testReport/junit/com.hazelcast.client.lock/ClientLockWithTerminationTest/testLockOnClient_withNodeCrash/

**Comment by mesutcelik** [comment]
no recent failure.

**Comment by Donnerbart** [comment]
Occurred again in a PR builder run, but with a different exception:
```
com.hazelcast.core.OperationTimeoutException: ClientInvocation{clientMessageType=5, callIdSequence=com.hazelcast.client.spi.impl.CallIdSequence$CallIdSequenceFailFast@6a67d193, target=connection MockedClientConnection{, localAddress=[127.0.0.1]:40025, super=ClientConnection{alive=true, connectionId=2, socketChannel=null, remoteEndpoint=[127.0.0.1]:5021, lastReadTime=2017-04-20 11:42:13.955, lastWriteTime=2017-04-20 11:42:13.953, closedTime=never, lastHeartbeatRequested=never, lastHeartbeatReceived=never, connected server version=3.9-SNAPSHOT}}, sendConnection=MockedClientConnection{, localAddress=[127.0.0.1]:40025, super=ClientConnection{alive=true, connectionId=2, socketChannel=null, remoteEndpoint=[127.0.0.1]:5021, lastReadTime=2017-04-20 11:42:13.955, lastWriteTime=2017-04-20 11:42:13.953, closedTime=never, lastHeartbeatRequested=never, lastHeartbeatReceived=never, connected server version=3.9-SNAPSHOT}}} timed out by 702 ms
	at com.hazelcast.client.spi.impl.ClientInvocation.notifyException(ClientInvocation.java:198)
	at com.hazelcast.client.spi.impl.ClientInvocationServiceSupport$ResponseThread.handleClientMessage(ClientInvocationServiceSupport.java:332)
	at com.hazelcast.client.spi.impl.ClientInvocationServiceSupport$ResponseThread.process(ClientInvocationServiceSupport.java:314)
	at com.hazelcast.client.spi.impl.ClientInvocationServiceSupport$ResponseThread.doRun(ClientInvocationServiceSupport.java:307)
	at com.hazelcast.client.spi.impl.ClientInvocationServiceSupport$ResponseThread.run(ClientInvocationServiceSupport.java:291)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:93)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:33)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:155)
	at com.hazelcast.client.spi.ProxyManager.initialize(ProxyManager.java:354)
	at com.hazelcast.client.spi.ProxyManager.initializeWithRetry(ProxyManager.java:312)
	at com.hazelcast.client.spi.ProxyManager.getOrCreateProxy(ProxyManager.java:293)
	at com.hazelcast.client.impl.HazelcastClientInstanceImpl.getDistributedObject(HazelcastClientInstanceImpl.java:660)
	at com.hazelcast.client.impl.HazelcastClientInstanceImpl.getLock(HazelcastClientInstanceImpl.java:496)
	at com.hazelcast.client.impl.HazelcastClientProxy.getLock(HazelcastClientProxy.java:138)
	at com.hazelcast.client.lock.ClientLockWithTerminationTest.testLockOnClient_withNodeCrash(ClientLockWithTerminationTest.java:85)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/8424/testReport/junit/com.hazelcast.client.lock/ClientLockWithTerminationTest/testLockOnClient_withNodeCrash/

**Comment by mmedenjak** [comment]
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.8/567/

**Comment by mmedenjak** [comment]
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK8/com.hazelcast$hazelcast-client/1154/

**Comment by vbekiaris** [comment]
PR builder failure: https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/8489/testReport/junit/com.hazelcast.client.lock/ClientLockWithTerminationTest/testLockOnClient_withNodeCrash/
```
com.hazelcast.core.OperationTimeoutException: ClientInvocation{clientMessageType=5, callIdSequence=com.hazelcast.client.spi.impl.CallIdSequence$CallIdSequenceFailFast@1e3bd51, target=connection MockedClientConnection{, localAddress=[127.0.0.1]:40012, super=ClientConnection{alive=true, connectionId=2, socketChannel=null, remoteEndpoint=[127.0.0.1]:5005, lastReadTime=2017-04-24 11:38:59.577, lastWriteTime=2017-04-24 11:38:59.575, closedTime=never, lastHeartbeatRequested=never, lastHeartbeatReceived=never, connected server version=3.9-SNAPSHOT}}, sendConnection=MockedClientConnection{, localAddress=[127.0.0.1]:40012, super=ClientConnection{alive=true, connectionId=2, socketChannel=null, remoteEndpoint=[127.0.0.1]:5005, lastReadTime=2017-04-24 11:38:59.577, lastWriteTime=2017-04-24 11:38:59.575, closedTime=never, lastHeartbeatRequested=never, lastHeartbeatReceived=never, connected server version=3.9-SNAPSHOT}}} timed out by 404 ms
	at com.hazelcast.client.spi.impl.ClientInvocation.notifyException(ClientInvocation.java:198)
	at com.hazelcast.client.spi.impl.ClientInvocationServiceSupport$ResponseThread.handleClientMessage(ClientInvocationServiceSupport.java:332)
	at com.hazelcast.client.spi.impl.ClientInvocationServiceSupport$ResponseThread.process(ClientInvocationServiceSupport.java:314)
	at com.hazelcast.client.spi.impl.ClientInvocationServiceSupport$ResponseThread.doRun(ClientInvocationServiceSupport.java:307)
	at com.hazelcast.client.spi.impl.ClientInvocationServiceSupport$ResponseThread.run(ClientInvocationServiceSupport.java:291)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:93)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:33)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:155)
	at com.hazelcast.client.spi.ProxyManager.initialize(ProxyManager.java:354)
	at com.hazelcast.client.spi.ProxyManager.initializeWithRetry(ProxyManager.java:312)
	at com.hazelcast.client.spi.ProxyManager.getOrCreateProxy(ProxyManager.java:293)
	at com.hazelcast.client.impl.HazelcastClientInstanceImpl.getDistributedObject(HazelcastClientInstanceImpl.java:660)
	at com.hazelcast.client.impl.HazelcastClientInstanceImpl.getLock(HazelcastClientInstanceImpl.java:496)
	at com.hazelcast.client.impl.HazelcastClientProxy.getLock(HazelcastClientProxy.java:138)
	at com.hazelcast.client.lock.ClientLockWithTerminationTest.testLockOnClient_withNodeCrash(ClientLockWithTerminationTest.java:85)
```

**Comment by Donnerbart** [comment]
New failure in a PR builder:
```
com.hazelcast.core.OperationTimeoutException: ClientInvocation{clientMessageType=5, callIdSequence=com.hazelcast.client.spi.impl.CallIdSequence$CallIdSequenceFailFast@615c1ae3, target=connection MockedClientConnection{, localAddress=[127.0.0.1]:40015, super=ClientConnection{alive=true, connectionId=2, socketChannel=null, remoteEndpoint=[127.0.0.1]:5012, lastReadTime=2017-04-26 17:48:25.196, lastWriteTime=2017-04-26 17:48:25.194, closedTime=never, lastHeartbeatRequested=never, lastHeartbeatReceived=never, connected server version=3.9-SNAPSHOT}}, sendConnection=MockedClientConnection{, localAddress=[127.0.0.1]:40015, super=ClientConnection{alive=true, connectionId=2, socketChannel=null, remoteEndpoint=[127.0.0.1]:5012, lastReadTime=2017-04-26 17:48:25.196, lastWriteTime=2017-04-26 17:48:25.194, closedTime=never, lastHeartbeatRequested=never, lastHeartbeatReceived=never, connected server version=3.9-SNAPSHOT}}} timed out by 685 ms
	at com.hazelcast.client.spi.impl.ClientInvocation.notifyException(ClientInvocation.java:198)
	at com.hazelcast.client.spi.impl.ClientInvocationServiceSupport$ResponseThread.handleClientMessage(ClientInvocationServiceSupport.java:332)
	at com.hazelcast.client.spi.impl.ClientInvocationServiceSupport$ResponseThread.process(ClientInvocationServiceSupport.java:314)
	at com.hazelcast.client.spi.impl.ClientInvocationServiceSupport$ResponseThread.doRun(ClientInvocationServiceSupport.java:307)
	at com.hazelcast.client.spi.impl.ClientInvocationServiceSupport$ResponseThread.run(ClientInvocationServiceSupport.java:291)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:93)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:33)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:155)
	at com.hazelcast.client.spi.ProxyManager.initialize(ProxyManager.java:354)
	at com.hazelcast.client.spi.ProxyManager.initializeWithRetry(ProxyManager.java:312)
	at com.hazelcast.client.spi.ProxyManager.getOrCreateProxy(ProxyManager.java:293)
	at com.hazelcast.client.impl.HazelcastClientInstanceImpl.getDistributedObject(HazelcastClientInstanceImpl.java:660)
	at com.hazelcast.client.impl.HazelcastClientInstanceImpl.getLock(HazelcastClientInstanceImpl.java:496)
	at com.hazelcast.client.impl.HazelcastClientProxy.getLock(HazelcastClientProxy.java:138)
	at com.hazelcast.client.lock.ClientLockWithTerminationTest.testLockOnClient_withNodeCrash(ClientLockWithTerminationTest.java:85)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/8547/testReport/junit/com.hazelcast.client.lock/ClientLockWithTerminationTest/testLockOnClient_withNodeCrash/

**Comment by hasancelik** [comment]
```
com.hazelcast.client.HazelcastClientNotActiveException: Owner connection is not available!
	at com.hazelcast.client.spi.impl.ClientInvocation.notifyException(ClientInvocation.java:193)
	at com.hazelcast.client.spi.impl.ClientInvocation.invokeOnSelection(ClientInvocation.java:160)
	at com.hazelcast.client.spi.impl.ClientInvocation.retry(ClientInvocation.java:178)
	at com.hazelcast.client.spi.impl.ClientInvocation.run(ClientInvocation.java:166)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$101(ScheduledThreadPoolExecutor.java:165)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:266)
	at com.hazelcast.util.executor.LoggingScheduledExecutor$LoggingDelegatingFuture.run(LoggingScheduledExecutor.java:160)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:704)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:96)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:33)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:155)
	at com.hazelcast.client.spi.ProxyManager.initialize(ProxyManager.java:372)
	at com.hazelcast.client.spi.ProxyManager.initializeWithRetry(ProxyManager.java:331)
	at com.hazelcast.client.spi.ProxyManager.getOrCreateProxy(ProxyManager.java:304)
	at com.hazelcast.client.impl.HazelcastClientInstanceImpl.getDistributedObject(HazelcastClientInstanceImpl.java:690)
	at com.hazelcast.client.impl.HazelcastClientInstanceImpl.getLock(HazelcastClientInstanceImpl.java:526)
	at com.hazelcast.client.impl.HazelcastClientProxy.getLock(HazelcastClientProxy.java:138)
	at com.hazelcast.client.lock.ClientLockWithTerminationTest.testLockOnClient_withNodeCrash(ClientLockWithTerminationTest.java:85)
Caused by: java.io.IOException: Owner connection is not available!
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.getConnection(ClientConnectionManagerImpl.java:355)
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.getOrTriggerConnect(ClientConnectionManagerImpl.java:342)
	at com.hazelcast.client.spi.impl.SmartClientInvocationService.getOrTriggerConnect(SmartClientInvocationService.java:70)
	at com.hazelcast.client.spi.impl.SmartClientInvocationService.invokeOnTarget(SmartClientInvocationService.java:65)
	at com.hazelcast.client.spi.impl.ClientInvocation.invokeOnSelection(ClientInvocation.java:152)
	at com.hazelcast.client.spi.impl.ClientInvocation.retry(ClientInvocation.java:178)
	at com.hazelcast.client.spi.impl.ClientInvocation.run(ClientInvocation.java:166)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$101(ScheduledThreadPoolExecutor.java:165)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:266)
	at com.hazelcast.util.executor.LoggingScheduledExecutor$LoggingDelegatingFuture.run(LoggingScheduledExecutor.java:160)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:704)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-ZuluJDK6-freestyle/96/testReport/junit/com.hazelcast.client.lock/ClientLockWithTerminationTest/testLockOnClient_withNodeCrash/

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-freestyle/302/testReport/junit/com.hazelcast.client.lock/ClientLockWithTerminationTest/testLockOnClient_withNodeCrash/
