### ISSUE TITLE
[TEST-FAILURE] BasicMapTest.testMapLoaderLoadUpdatingIndex

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#3426]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance/com.hazelcast$hazelcast/434/testReport/junit/com.hazelcast.map/BasicMapTest/testMapLoaderLoadUpdatingIndex/
```
java.lang.AssertionError: expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:555)
	at org.junit.Assert.assertEquals(Assert.java:542)
	at com.hazelcast.map.BasicMapTest.testMapLoaderLoadUpdatingIndex(BasicMapTest.java:1173)
```

**Comment by ahmetmircik** [comment]
Seems still failing https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-pr-builder/com.hazelcast$hazelcast/12034/testReport/junit/com.hazelcast.map.mapstore/MapLoaderTest/testMapLoaderLoadUpdatingIndex/

**Comment by ahmetmircik** [comment]
did not fail recently, will handle it if we encounter a new failure.
