### ISSUE TITLE
waitForResponse never returns in 3.3-RC3

### ISSUE THREAD

**Issue by juan-palacios** [hazelcast/hazelcast#3466]
When starting our application a map query never returns (waited for about 14hs):

```
at com.hazelcast.spi.impl.BasicInvocationFuture.waitForResponse(BasicInvocationFuture.java:205)
        - locked <0x00000000d6d3ef20> (a com.hazelcast.spi.impl.BasicInvocationFuture)
        at com.hazelcast.spi.impl.BasicInvocationFuture.get(BasicInvocationFuture.java:180)
        at com.hazelcast.spi.impl.BasicInvocationFuture.get(BasicInvocationFuture.java:160)
        at com.hazelcast.map.proxy.MapProxySupport.invokeOperation(MapProxySupport.java:402)
        at com.hazelcast.map.proxy.MapProxySupport.getInternal(MapProxySupport.java:218)
        at com.hazelcast.map.proxy.MapProxyImpl.get(MapProxyImpl.java:84)
...
        at org.springframework.web.servlet.FrameworkServlet.initWebApplicationContext(FrameworkServlet.java:543)
        at com.myapp.spring.web.servlet.MyDispatcherServlet.initWebApplicationContext(MyDispatcherServlet.java:125)
        at org.springframework.web.servlet.FrameworkServlet.initServletBean(FrameworkServlet.java:484)
        at org.springframework.web.servlet.HttpServletBean.init(HttpServletBean.java:136)
        at javax.servlet.GenericServlet.init(GenericServlet.java:158)
        at com.myapp.spring.lifecycle.LifecycleDispatcherServlet$1.run(LifecycleDispatcherServlet.java:89)
        at java.lang.Thread.run(Thread.java:745)
```

Because the thread is trying to initialise the Spring context, the node locks and is unable to complete any other tasks, including re-partitioning:

```
"hz.hazelcast.partition-operation.thread-14" daemon prio=10 tid=0x00007f799c8a0000 nid=0x9b9a waiting for monitor entry [0x00007f79f99d3000]
   java.lang.Thread.State: BLOCKED (on object monitor)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:186)
        - waiting to lock <0x00000000d276b888> (a java.util.concurrent.ConcurrentHashMap)
        at org.springframework.beans.factory.support.AbstractBeanFactory.isTypeMatch(AbstractBeanFactory.java:486)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doGetBeanNamesForType(DefaultListableBeanFactory.java:387)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:362)
        at org.springframework.beans.factory.BeanFactoryUtils.beanNamesForTypeIncludingAncestors(BeanFactoryUtils.java:187)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1002)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:960)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:858)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredMethodElement.inject(AutowiredAnnotationBeanPostProcessor.java:553)
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:87)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:289)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1185)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireBean(AbstractAutowireCapableBeanFactory.java:301)
        at com.hazelcast.spring.context.SpringManagedContext.initializeIfSpringAwareIsPresent(SpringManagedContext.java:61)
        at com.hazelcast.spring.context.SpringManagedContext.initialize(SpringManagedContext.java:46)
        at com.hazelcast.instance.HazelcastManagedContext.initialize(HazelcastManagedContext.java:47)
        at com.hazelcast.nio.serialization.SerializationServiceImpl.toObject(SerializationServiceImpl.java:264)
        at com.hazelcast.queue.QueueStoreWrapper.store(QueueStoreWrapper.java:146)
        at com.hazelcast.queue.QueueContainer.offer(QueueContainer.java:268)
        at com.hazelcast.queue.OfferOperation.run(OfferOperation.java:52)
        at com.hazelcast.spi.impl.BasicOperationService$OperationHandler.handle(BasicOperationService.java:673)
        at com.hazelcast.spi.impl.BasicOperationService$OperationHandler.access$400(BasicOperationService.java:649)
        at com.hazelcast.spi.impl.BasicOperationService$OperationPacketHandler.handle(BasicOperationService.java:623)
        at com.hazelcast.spi.impl.BasicOperationService$OperationPacketHandler.handle(BasicOperationService.java:591)
        at com.hazelcast.spi.impl.BasicOperationService$OperationPacketHandler.access$1400(BasicOperationService.java:578)
        at com.hazelcast.spi.impl.BasicOperationService$BasicDispatcherImpl.dispatch(BasicOperationService.java:533)
        at com.hazelcast.spi.impl.BasicOperationScheduler$OperationThread.process(BasicOperationScheduler.java:439)
        at com.hazelcast.spi.impl.BasicOperationScheduler$OperationThread.doRun(BasicOperationScheduler.java:433)
        at com.hazelcast.spi.impl.BasicOperationScheduler$OperationThread.run(BasicOperationScheduler.java:408)
```

We were able to mitigate this issue by overriding the logic in `InternalPartitionServiceImpl` and delaying the re-partitioning task. But unfortunately this doesn't explain, why the `MapProxyImpl.get` call never completes or times out.

**Comment by pveentjer** [comment]
Closing this ticket since it is 3 years also and the whole design of invocation futures has been completely changed.
