### ISSUE TITLE
[TEST-FAILURE] MemberListTest.testOutOfSyncMemberListTwoMasters

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#3495]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/299/testReport/junit/com.hazelcast.cluster/MemberListTest/testOutOfSyncMemberListTwoMasters/

```
com.hazelcast.core.HazelcastException: Port [35703] is already in use and auto-increment is disabled. Hazelcast cannot start.
    at com.hazelcast.instance.DefaultAddressPicker.pickAddress(DefaultAddressPicker.java:112)
    at com.hazelcast.instance.Node.<init>(Node.java:146)
    at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:120)
    at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:153)
    at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:136)
    at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:112)
    at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:58)
    at com.hazelcast.cluster.MemberListTest.testOutOfSyncMemberListTwoMasters(MemberListTest.java:172)
```

maybe this test failed due to other builds || tests that ran at the same time.

**Comment by Donnerbart** [comment]
Failed during a local run for code coverage:
```
java.lang.AssertionError: 
Expected :Member [127.0.0.1]:35701 this
Actual   :Member [127.0.0.1]:35702 this
 <Click to see difference>


	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.cluster.MemberListTest.testOutOfSyncMemberListTwoMasters(MemberListTest.java:174)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:88)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:82)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
```
https://gist.githubusercontent.com/Donnerbart/aa358b1f799889cc01ed/raw/eb2fbc5f29a7ed10d7b9d737abd5cee5a2bfb45e/MemberListTest_failure.log
