### ISSUE TITLE
[TEST-FAILURE] AtomicLongTest.testAtomicLongSpawnNodeInParallel

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#3507]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x/com.hazelcast$hazelcast/1683/testReport/junit/com.hazelcast.concurrent.atomiclong/AtomicLongTest/testAtomicLongSpawnNodeInParallel/

```
java.lang.AssertionError: CountDownLatch failed to complete within 120 seconds , count left: 1
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.assertTrue(Assert.java:41)
    at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:179)
    at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:172)
    at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:164)
    at com.hazelcast.concurrent.atomiclong.AtomicLongTest.testAtomicLongSpawnNodeInParallel(AtomicLongTest.java:197)
```

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/3503/
```
java.lang.AssertionError: expected:<104> but was:<103>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.concurrent.atomiclong.AtomicLongAdvancedTest.testAtomicLongSpawnNodeInParallel(AtomicLongAdvancedTest.java:105)
```

**Comment by jerrinot** [comment]
The failure https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/3503/ does not seem to be specific to AtomicLong. It seems to be related to a join process. See:

```
java.lang.IllegalStateException: Node failed to start!
	at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:133)
	at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:160)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:143)
	at com.hazelcast.test.TestHazelcastInstanceFactory.newHazelcastInstance(TestHazelcastInstanceFactory.java:112)
	at com.hazelcast.test.TestHazelcastInstanceFactory.newHazelcastInstance(TestHazelcastInstanceFactory.java:99)
	at com.hazelcast.concurrent.atomiclong.AtomicLongAdvancedTest$2.run(AtomicLongAdvancedTest.java:87)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
```

**Comment by jerrinot** [comment]
Thanks to @mdogan for pointing me to this issue: #8085
The fix was not backported into maintenance branch hence I guess it's the same problem.
