### ISSUE TITLE
[TEST-FAILURE] ClientMapReduceTest failures

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#3525]
ClientMapReduceTest.testInProcessCancellation
ClientMapReduceTest.testExceptionDistribution
```
java.lang.Exception: test timed out after 60000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:226)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1033)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1326)
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:282)
	at com.hazelcast.client.proxy.ClientMapReduceProxy$ClientCompletableFuture.get(ClientMapReduceProxy.java:208)
	at com.hazelcast.spi.impl.AbstractCompletableFuture.get(AbstractCompletableFuture.java:87)
	at com.hazelcast.client.mapreduce.ClientMapReduceTest.testInProcessCancellation(ClientMapReduceTest.java:122)
```

```
java.lang.Exception: test timed out after 60000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:226)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1033)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1326)
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:282)
	at com.hazelcast.client.proxy.ClientMapReduceProxy$ClientCompletableFuture.get(ClientMapReduceProxy.java:208)
	at com.hazelcast.spi.impl.AbstractCompletableFuture.get(AbstractCompletableFuture.java:87)
	at com.hazelcast.client.mapreduce.ClientMapReduceTest.testExceptionDistribution(ClientMapReduceTest.java:87)
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/301/testReport/

**Comment by mesutcelik** [comment]
I am reopening this failure. Only following test failed this time.

```
ClientMapReduceTest.testInProcessCancellation
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/486/com.hazelcast$hazelcast-client/testReport/com.hazelcast.client.mapreduce/ClientMapReduceTest/testInProcessCancellation/

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast-client/494/testReport/junit/com.hazelcast.client.mapreduce/ClientMapReduceTest/testInProcessCancellation/

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/495/com.hazelcast$hazelcast-client/testReport/com.hazelcast.client.mapreduce/ClientMapReduceTest/testInProcessCancellation/

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-sonar/com.hazelcast$hazelcast-client/559/testReport/junit/com.hazelcast.client.mapreduce/ClientMapReduceTest/testInProcessCancellation/
