### ISSUE TITLE
HazelcastInstanceNotActiveException induce total hazelcast cluster not working 

### ISSUE THREAD

**Issue by bwzhang2011** [hazelcast/hazelcast#3695]
I got massive error Exception due to the HazelcastInstanceNotActiveException thrown with access to the Queue component like:

final  IQueue<Object> itemQueue = hzInstance.getQueue("queueName");

new Thread(new Runnable() {
    public void run() {
         while(true) {
            try {
                 Object queueItem = itemQueue.poll(1000L,TimeUnit.MILLISECONDS);

                 if(queueItem != null) {
                        //TODO
                 }
            }catch(Exception ex) {
              // here catch the HazelcastInstanceNotActiveException  
            }
     }
    }
}).start();

The reason due to such is the connection lost the hzInstance just like the logs traced for analysis:

2014-09-26 12:49:55,961  INFO (com.hazelcast.nio.tcp.TcpIpConnection:380) - [172.168.101.36]:5886 [verifyGroup] [3.3] Connection [Address[172.168.101.36]:28150] lost. Reason: Socket explicitly closed
2014-09-26 12:49:55,961  WARN (com.hazelcast.nio.tcp.ReadHandler:33) - [172.168.101.36]:5886 [verifyGroup] [3.3] hz.Hazelcast for verify(monitor).IO.thread-in-1 Closing socket to endpoint Address[172.168.101.36]:28164, Cause:java.io.EOFException: Remote socket closed!
2014-09-26 12:49:55,962  INFO (com.hazelcast.nio.tcp.TcpIpConnection:380) - [172.168.101.36]:5886 [verifyGroup] [3.3] Connection [Address[172.168.101.36]:28149] lost. Reason: Socket explicitly closed
2014-09-26 12:49:55,962  INFO (com.hazelcast.nio.tcp.TcpIpConnection:380) - [172.168.101.36]:5886 [verifyGroup] [3.3] Connection [Address[172.168.101.36]:28166] lost. Reason: Socket explicitly closed
2014-09-26 12:49:55,963  INFO (com.hazelcast.nio.tcp.TcpIpConnection:380) - [172.168.101.36]:5886 [verifyGroup] [3.3] Connection [Address[172.168.101.36]:28155] lost. Reason: Socket explicitly closed
2014-09-26 12:49:55,963  INFO (com.hazelcast.nio.tcp.TcpIpConnection:380) - [172.168.101.36]:5886 [verifyGroup] [3.3] Connection [Address[172.168.101.36]:28163] lost. Reason: Socket explicitly closed
2014-09-26 12:49:55,963  INFO (com.hazelcast.nio.tcp.TcpIpConnection:380) - [172.168.101.36]:5886 [verifyGroup] [3.3] Connection [Address[172.168.101.36]:28171] lost. Reason: Socket explicitly closed
2014-09-26 12:49:55,963  INFO (com.hazelcast.nio.tcp.TcpIpConnection:380) - [172.168.101.36]:5886 [verifyGroup] [3.3] Connection [Address[172.168.101.36]:28162] lost. Reason: Socket explicitly closed

After such down it will lead to shutdown the mancenter(I  just make some configuration to start the monitor WAR to be integrated with the deployment) service as follows:

2014-09-26 12:49:55,965  INFO (com.hazelcast.management.ManagementCenterService:405) - [172.168.101.36]:5886 [verifyGroup] [3.3] Shutting down Hazelcast Management Center Service

And once such shutdown invoking, the thread always run with while(true)) to use queue to load the data for response,but now the instance seems to shutdown so that the exception thrown. 

but I have several questions about that:
1. Why the hzInstance could be shutdown, as it was the client role to be apart from the connection with our machine(only on behalf of the client side to disconnected with the HzInstance ) 

2. Why it would invoke the shutdown operation to the mancenter.do those could be configured or
the reason for hz inteself to shutdown the instance itself(e.g when and how )

3. How could I find some solution to solve the HazelcastInstanceNotActiveException  problem as
the hzInstance is invoked in the server side(no reason itself to make it not active)

as the above conclusion, hope the hz team could point out my mistake or help me solve such problem to make sure of its stability.

**Comment by bwzhang2011** [comment]
@mdogan, such issue still not resolved and reproduced in our production environment. I hope hz team could pay more attention to that and find the final solution for that. if such thrown, how could we solve such problem. @talip, as you're the CTO of hz, the hazelcastNotActiveException is very serious that would induce the whole cluster not working, so please assign more people to find the final solution and it should has the highest priority.

**Comment by bwzhang2011** [comment]
by the way, the hazelcast version in our production environment is 3.3.5

**Comment by oallouch** [comment]
Have you tried the back pressure thingy ?

**Comment by bwzhang2011** [comment]
@oallouch, thanks for review but I don't know much about back-pressure and it's such feature in hz3.4. 
From our logging record, one of the reasons induced such exception is the network issue but I didn't know why such thrown out as hzInstance was created in my cluster env while other use the client api to establish the connection between the application and cluster.

**Comment by bwzhang2011** [comment]
@oallouch, would you mind leaving me more message about this ? from my production, such exception thrown just under the network switched. our network monitored by some firewall configuration and once it was started, it would impact the packets between each node (just like the application with the cluster resort to the hzclient instance). I think I should upgrade to the latest one if hz3.4.1 released next month and begin to close the issue.

**Comment by oallouch** [comment]
I've actually never tried it, but I think it might help. I suspect we have some issues with the inter-server communication.

**Comment by bwzhang2011** [comment]
@oallouch thanks for review. as the mancenter doesn't provide any monitor for the inter-server communication. so I have to just rely on the log. from my experience, it only occurred in IQueue component for long polling state for my demon thread poll the data each interval. I think hz has resolved such issue but need to investigate that for hz client has been heavily refactored in hz3.5 so we don't quite know about the changes.

**Comment by bwzhang2011** [comment]
@mdogan, I still got the hazelcast notActiveException  from my prod env. as the hazelcast version is 3.3.5 and I don't know why it would induce such error just like

com.hazelcast.core.HazelcastInstanceNotActiveException: Hazelcast instance is not active!
	at com.hazelcast.spi.AbstractDistributedObject.throwNotActiveException(AbstractDistributedObject.java:81) ~[hazelcast-all-3.3.5.jar:na]
	at com.hazelcast.spi.AbstractDistributedObject.lifecycleCheck(AbstractDistributedObject.java:76) ~[hazelcast-all-3.3.5.jar:na]
	at com.hazelcast.spi.AbstractDistributedObject.getNodeEngine(AbstractDistributedObject.java:70) ~[hazelcast-all-3.3.5.jar:na]
	at com.hazelcast.map.proxy.MapProxySupport.clearInternal(MapProxySupport.java:819) ~[hazelcast-all-3.3.5.jar:na]
	at com.hazelcast.map.proxy.MapProxyImpl.clearInternal(MapProxyImpl.java:72) ~[hazelcast-all-3.3.5.jar:na]
	at com.hazelcast.map.proxy.MapProxyImpl.clear(MapProxyImpl.java:540) ~[hazelcast-all-3.3.5.jar:na]
	at com.hazelcast.spring.cache.HazelcastCache.clear(HazelcastCache.java:92) ~[hazelcast-all-3.3.5.jar:na]

**Comment by bwzhang2011** [comment]
@pveentjer , would you mind sparing your time and have a look at ? I would be crazy since it's a so long time issue since last year and I don't know why and how to solve the problem and my solution is to upgrade the hazelcast version and restart my shell script. so please help us for when it occured , the whole cluster is down and I could not bear it that our team would deem it to be not strong.

**Comment by bwzhang2011** [comment]
@pveentjer, @mdogan or someone else take interested in such issue. I think it should be closed as it seldom occurred as ever before maybe the latest one like hz3.5+ would solve that and I will keep up with such until it completely disappeared and of source it would reopen once it was reproduced.
