### ISSUE TITLE
On startup, Illegal character in opaque part at index 22: wsjar:file:/C:/Program Files/.....

### ISSUE THREAD

**Issue by hicyo** [hazelcast/hazelcast#3752]
I have just upgraded to the new version 3.3 and I have an error on startup not ocurred previously when I was using 3.1.x versions. I am using IBM Websphere Server 7 on Windows 7 64 bits.
According to what we can see in the log attached below, some files located in hazelcast jar in "META-INF/services" directory cannot be loaded correctly because of a whitespace that exists in this directory name "C:/Program Files".
The files affected are:
- com.hazelcast.PortableHook
- com.hazelcast.DataSerializerHook
- com.hazelcast.SerializerHook
-  com.hazelcast.NodeInitializer
the same error ocurrs for each of these files.
 
```
ServiceLoader E com.hazelcast.util.ServiceLoader  Illegal character in opaque part at index 22: wsjar:file:/C:/Program Files/IBM/WebSphere/AppServer/profiles/AppSrv01/installedApps/W7-ESMAD0191Cell01/my aplication.ear/APP-INF/lib/hazelcast-3.3.1.jar!/META-INF/services/com.hazelcast.PortableHook
                                 java.net.URISyntaxException: Illegal character in opaque part at index 22: wsjar:file:/C:/Program Files/IBM/WebSphere/AppServer/profiles/AppSrv01/installedApps/W7-ESMAD0191Cell01/my aplication.ear/APP-INF/lib/hazelcast-3.3.1.jar!/META-INF/services/com.hazelcast.PortableHook
	at java.net.URI$Parser.fail(URI.java:2821)
	at java.net.URI$Parser.checkChars(URI.java:2994)
	at java.net.URI$Parser.parse(URI.java:3031)
	at java.net.URI.<init>(URI.java:588)
	at java.net.URL.toURI(URL.java:930)
	at com.hazelcast.util.ServiceLoader.collectFactoryUrls(ServiceLoader.java:118)
	at com.hazelcast.util.ServiceLoader.iterator(ServiceLoader.java:69)
	at com.hazelcast.nio.serialization.PortableHookLoader.load(PortableHookLoader.java:46)
	at com.hazelcast.nio.serialization.PortableHookLoader.<init>(PortableHookLoader.java:41)
	at com.hazelcast.nio.serialization.SerializationServiceImpl.<init>(SerializationServiceImpl.java:119)
	at com.hazelcast.nio.serialization.SerializationServiceBuilder.build(SerializationServiceBuilder.java:175)
	at com.hazelcast.instance.Node.createSerializationService(Node.java:193)
	at com.hazelcast.instance.Node.<init>(Node.java:140)
	at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:120)
	at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:153)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:136)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:112)
	at testutil.spring.javaconfig.CoreCacheHazelcastInstanceConf.hazelcast(CoreCacheHazelcastInstanceConf.java:161)
	at testutil.spring.javaconfig.CoreCacheHazelcastInstanceConf$$EnhancerBySpringCGLIB$$c8f3c7df.CGLIB$hazelcast$0(<generated>)
	at testutil.spring.javaconfig.CoreCacheHazelcastInstanceConf$$EnhancerBySpringCGLIB$$c8f3c7df$$FastClassBySpringCGLIB$$bc8db817.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:312)
	at testutil.spring.javaconfig.CoreCacheHazelcastInstanceConf$$EnhancerBySpringCGLIB$$c8f3c7df.hazelcast(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:60)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:37)
	at java.lang.reflect.Method.invoke(Method.java:611)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:166)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:586)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1094)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:989)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:504)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:475)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:304)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:300)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:195)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1017)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:960)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:858)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:480)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:87)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:289)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1185)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:537)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:475)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:304)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:300)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:195)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:703)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:760)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:482)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:403)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:106)
	at org.osbl.client.web.spring.ContextLoaderListenerNM.contextInitialized(ContextLoaderListenerNM.java:66)
	at com.ibm.ws.webcontainer.webapp.WebApp.notifyServletContextCreated(WebApp.java:1718)
	at com.ibm.ws.webcontainer.webapp.WebApp.commonInitializationFinish(WebApp.java:385)
	at com.ibm.ws.webcontainer.webapp.WebAppImpl.initialize(WebAppImpl.java:299)
	at com.ibm.ws.webcontainer.webapp.WebGroupImpl.addWebApplication(WebGroupImpl.java:100)
	at com.ibm.ws.webcontainer.VirtualHostImpl.addWebApplication(VirtualHostImpl.java:166)
	at com.ibm.ws.webcontainer.WSWebContainer.addWebApp(WSWebContainer.java:732)
	at com.ibm.ws.webcontainer.WSWebContainer.addWebApplication(WSWebContainer.java:617)
	at com.ibm.ws.webcontainer.component.WebContainerImpl.install(WebContainerImpl.java:376)
	at com.ibm.ws.webcontainer.component.WebContainerImpl.start(WebContainerImpl.java:668)
	at com.ibm.ws.runtime.component.ApplicationMgrImpl.start(ApplicationMgrImpl.java:1127)
	at com.ibm.ws.runtime.component.DeployedApplicationImpl.fireDeployedObjectStart(DeployedApplicationImpl.java:1319)
	at com.ibm.ws.runtime.component.DeployedModuleImpl.start(DeployedModuleImpl.java:611)
	at com.ibm.ws.runtime.component.DeployedApplicationImpl.start(DeployedApplicationImpl.java:944)
	at com.ibm.ws.runtime.component.ApplicationMgrImpl.startApplication(ApplicationMgrImpl.java:740)
	at com.ibm.ws.runtime.component.ApplicationMgrImpl.start(ApplicationMgrImpl.java:2051)
	at com.ibm.ws.runtime.component.CompositionUnitMgrImpl.start(CompositionUnitMgrImpl.java:385)
	at com.ibm.ws.runtime.component.CompositionUnitImpl.start(CompositionUnitImpl.java:123)
	at com.ibm.ws.runtime.component.CompositionUnitMgrImpl.start(CompositionUnitMgrImpl.java:328)
	at com.ibm.ws.runtime.component.CompositionUnitMgrImpl.access$300(CompositionUnitMgrImpl.java:113)
	at com.ibm.ws.runtime.component.CompositionUnitMgrImpl$CUInitializer.run(CompositionUnitMgrImpl.java:895)
	at com.ibm.wsspi.runtime.component.WsComponentImpl$_AsynchInitializer.run(WsComponentImpl.java:496)
	at com.ibm.ws.util.ThreadPool$Worker.run(ThreadPool.java:1646)

00000018 ServiceLoader W com.hazelcast.util.ServiceLoader  Service loader could not load 'META-INF/services/com.hazelcast.PortableHook' It may be empty or does not exist.
```

To resolve this issue, I think it is only a question to handle directory names before getting these resources. 
Thanks.

**Comment by hicyo** [comment]
Now, I still having the same issue using 3.4 version on Solaris 10 and Websphere application server 7.

**Comment by rn55** [comment]
Hi Guys,
I'm easily reproducing issue:
My environment: CentOS 6.5, java 1.8 25, hazelcast 3.3.2

Errors:

`SEVERE: Illegal character in opaque part at index 38: jar:file:/home/mtalaga/ProgramData/amp server 5.7.10build44/lib/common/com.hazelcast.hazelcast-all-3.3.2.jar!/META-INF/services/com.hazelcast.PortableHook
java.net.URISyntaxException: Illegal character in opaque part at index 38: jar:file:/home/mtalaga/ProgramData/qwa server 5.7.10build44/lib/common/com.hazelcast.hazelcast-all-3.3.2.jar!/META-INF/services/com.hazelcast.PortableHook
at java.net.URI$Parser.fail(URI.java:2848)
at java.net.URI$Parser.checkChars(URI.java:3021)`

`SEVERE: Illegal character in opaque part at index 38: jar:file:/home/mtalaga/ProgramData/amp server 5.7.10build44/lib/common/com.hazelcast.hazelcast-all-3.3.2.jar!/META-INF/services/com.hazelcast.DataSerializerHook
java.net.URISyntaxException: Illegal character in opaque part at index 38: jar:file:/home/mtalaga/ProgramData/qwa server 5.7.10build44/lib/common/com.hazelcast.hazelcast-all-3.3.2.jar!/META-INF/services/com.hazelcast.DataSerializerHook
at java.net.URI$Parser.fail(URI.java:2848)
at java.net.URI$Parser.checkChars(URI.java:3021)`

Any updates on this?

**Comment by yacota** [comment]
Hi,
I can reproduce the problem randomly 
Environment : CentOS 6.4,  1.8.0_11, hazelcast 3.4.1
{code}
java.net.URISyntaxException: Illegal character in opaque part at index 64: jar:war:file:/data/agile/agile.pubfrontal/webapps/pubfrontal.war^/WEB-INF/lib/hazelcast-3.4.1.jar!/META-INF/services/com.hazelcast.instance.NodeExtension
        at java.net.URI$Parser.fail(URI.java:2848)
        at java.net.URI$Parser.checkChars(URI.java:3021)
        at java.net.URI$Parser.parse(URI.java:3058)
        at java.net.URI.<init>(URI.java:588)
        at java.net.URL.toURI(URL.java:939)
        at com.hazelcast.util.ServiceLoader.collectFactoryUrls(ServiceLoader.java:122)
        at com.hazelcast.util.ServiceLoader.iterator(ServiceLoader.java:73)
        at com.hazelcast.instance.NodeExtensionFactory.create(NodeExtensionFactory.java:33)
        at com.hazelcast.instance.Node.<init>(Node.java:155)
        at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:117)
      at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:153)
        at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:136)
        at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:112)
        at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:87)
        at com.ctv.publisher.configuration.HazelcastCacheConfiguration.hazelcastInstance(HazelcastCacheConfiguration.java:29)
        at com.ctv.publisher.configuration.HazelcastCacheConfiguration$$EnhancerBySpringCGLIB$$27329f0a.CGLIB$hazelcastInstance$0(<generated>)
        at com.ctv.publisher.configuration.HazelcastCacheConfiguration$$EnhancerBySpringCGLIB$$27329f0a$$FastClassBySpringCGLIB$$2e2d940.invoke(<generated>)
{code}

**Comment by rn55** [comment]
Hi,
Is there a chance to fix problem soon? I wouldn't like to ask customer to not use whitespaces in path...
I reproduced problem on CentOS and MacOS. 
I tried to patch ServiceLoader.java:
`URI uri = new URI(url.toString().replace(" ", "%20"));`
and it seems to work fine but I would like to avoid using patches

**Comment by serkan-ozal** [comment]
The better solution should be like `URI uri = new URI(URLEncoder.encode(url.toString(), "UTF-8"));` instead of `URI uri = new URI(url.toString().replace(" ", "%20"));`

**Comment by Vampire** [comment]
@serkan-ozal the `URLEncoder` is for HTML encoding. This is highly non-working here. It would change the space to a plus sign and also change the slashes, exclamation mark, colons and so on to `%XX` entities which will render the URL unusable except for safe transmission inside an HTTP URL. To use it in the meant context as `URL` again, you would have use the `URLDecoder.decode()` method later on and then you also have the space back.

The change pull request #4740 was exactly the right solution that was also applied to JSF which had the same problem here: https://java.net/jira/browse/JAVASERVERFACES-2628, except they used `toExternalForm()` on `URL` instead of `toString()`, but internally `URL.toString()` just calls `URL.toExternalForm()` anyway, so it does not make any difference.

I'd opt to merge the pull request #4740.

**Comment by jerrinot** [comment]
@Vampire: thanks for your analysis and especially for the link to JSF!

**Comment by Vampire** [comment]
You're welcome :-)

**Comment by Vampire** [comment]
I applied the fix and also added a test case that was failing and is not anymore.
I created two pull requests, on for 3.3.6 (#7311) and one for master (#7310).

**Comment by Vampire** [comment]
Will this be fixed in 3.6.2 as the milestone suggests? My merge request was only merged into master.

**Comment by jerrinot** [comment]
@Vampire: good catch. apparently we didn't merge it into the maintenance branch. 
@mesutcelik: I think we should merge the backport and have it in 3.6.3, wdyt?

**Comment by Vampire** [comment]
Ah, ok 3.6.3 then of course. Didn't see that it is released already as `git fetch --all` does not fetch tags :-(

**Comment by jerrinot** [comment]
`get fetch --all --tags` should help

**Comment by Vampire** [comment]
Yep, but afair this fetches only the tags, but not the branches, or do I remember wrongly?

**Comment by jerrinot** [comment]
I think branches are always fetched. `tags` are fetched only(?) when you explicitly ask for it.

**Comment by Donnerbart** [comment]
`git help fetch`
> `-t, --tags`
> Fetch all tags from the remote (i.e., `fetch remote tags refs/tags/*` into local tags with the same name), **in addition to whatever else would otherwise be fetched.**

`git fetch --all --tags` should work fine to fetch all branches and tags.

**Comment by Vampire** [comment]
Ah, great thanks. I probably got it confused with push where `--all` and `--tags` cannot be combined.

**Comment by vbekiaris** [comment]
Backported & merged into `maintenance-3.x` branch with #8016 . Thanks @Vampire for the awesome contribution!

**Comment by jeanse7en** [comment]
Actually, it's big problem where you put your server. 
I already faced this problem before, I used Geronimo with the space in my direction D:\Common DevTool\Geronimo.
Have 2 ways to resolve
1.  change to D:\Tool\Geronimo, it ran well.
Your directory is not correct, C:/Program Files, You should move your server to another place without space in name. 
2. Upgrade the jsf version.
Hope that my answer can help you

**Comment by Vampire** [comment]
@jeanse7en this is a two years old issue that was fixed two years ago. What do you want to say with your comment? That the error is back? Then you should probably open a new issues.

**Comment by ravichappa22** [comment]
This is really a big issue as we see most of the windows OS based application servers deployed under folder "Program Files" which has space and they are not converted to replace with %20, but Mac or Linux based working fine, anyone fix this issue or found a work around please suggest, I am at the same problem @mmedenjak @Vampire @pveentjer @idf3d. Error is back with hazelcast 4.2.1

**Comment by mmedenjak** [comment]
Probably reintroduced with https://github.com/hazelcast/hazelcast/pull/16851. @ravichappa22 please open an issue with the stack trace or, better yet, submit a PR with the fix.
