### ISSUE TITLE
ClassNotFoundException during merge operation

### ISSUE THREAD

**Issue by IlaiG** [hazelcast/hazelcast#3755]
We're running in a 2 node client-server configuration running 3.2.5

After one of the nodes got disconnected and reconnected, during the merge operation we are getting thousands of the following severe exceptions:

```
» 17:00:50.703 SEVERE: [SERVER1]:5701 [dev] [3.2.5] java.lang.ClassNotFoundException: com.our.class.name
» 17:00:50.703 com.hazelcast.nio.serialization.HazelcastSerializationException: java.lang.ClassNotFoundException: com.datorama.core.model.admin.UiJob
» 17:00:50.703 at com.hazelcast.nio.serialization.DefaultSerializers$ObjectSerializer.read(DefaultSerializers.java:190)
» 17:00:50.703 at com.hazelcast.nio.serialization.StreamSerializerAdapter.read(StreamSerializerAdapter.java:59)
» 17:00:50.703 at com.hazelcast.nio.serialization.SerializationServiceImpl.toObject(SerializationServiceImpl.java:221)
» 17:00:50.703 at com.hazelcast.spi.impl.NodeEngineImpl.toObject(NodeEngineImpl.java:156)
» 17:00:50.703 at com.hazelcast.map.MapService.toObject(MapService.java:867)
» 17:00:50.703 at com.hazelcast.map.operation.MergeOperation.run(MergeOperation.java:49)
» 17:00:50.703 at com.hazelcast.spi.impl.BasicOperationService.processOperation(BasicOperationService.java:363)
» 17:00:50.703 at com.hazelcast.spi.impl.BasicOperationService.access$300(BasicOperationService.java:102)
» 17:00:50.703 at com.hazelcast.spi.impl.BasicOperationService$BasicOperationProcessorImpl.process(BasicOperationService.java:764)
» 17:00:50.703 at com.hazelcast.spi.impl.BasicOperationScheduler$PartitionThread.process(BasicOperationScheduler.java:288)
» 17:00:50.703 at com.hazelcast.spi.impl.BasicOperationScheduler$PartitionThread.doRun(BasicOperationScheduler.java:282)
» 17:00:50.703 at com.hazelcast.spi.impl.BasicOperationScheduler$PartitionThread.run(BasicOperationScheduler.java:257)
» 17:00:50.703 Caused by: java.lang.ClassNotFoundException: com.our.class.name
» 17:00:50.703 at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
» 17:00:50.703 at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
» 17:00:50.703 at java.security.AccessController.doPrivileged(Native Method)
» 17:00:50.703 at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
» 17:00:50.703 at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
» 17:00:50.703 at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
» 17:00:50.703 at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
» 17:00:50.703 at com.hazelcast.nio.ClassLoaderUtil.tryLoadClass(ClassLoaderUtil.java:123)
» 17:00:50.703 at com.hazelcast.nio.ClassLoaderUtil.loadClass(ClassLoaderUtil.java:112)
» 17:00:50.703 at com.hazelcast.nio.IOUtil$1.resolveClass(IOUtil.java:89)
» 17:00:50.703 at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1612)
» 17:00:50.703 at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1517)
» 17:00:50.703 at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1771)
» 17:00:50.703 at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
» 17:00:50.703 at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)
» 17:00:50.703 at com.hazelcast.nio.serialization.DefaultSerializers$ObjectSerializer.read(DefaultSerializers.java:185)
» 17:00:50.703 ... 11 more
» 17:00:50.703 Sep 30, 2014 2:00:57 PM com.hazelcast.map.operation.MergeOperation
```

We're not sure why the merge operation would need to serialize/deserialize our objects.

**Comment by innokenty-shuvalov** [comment]
Hi, I'm running version 3.4.1 and I've got exactly the same issue. Can you please take a look?

```java
2015-05-22 10:31:56,235 FATAL MergeOperation - [aerostat-h-1.haze.yandex.net]:5803 [aerostat-production-new] [3.4.1] java.lang.ClassNotFoundException: org.apache.activemq.command.ActiveMQQueue
com.hazelcast.nio.serialization.HazelcastSerializationException: java.lang.ClassNotFoundException: org.apache.activemq.command.ActiveMQQueue
        at com.hazelcast.nio.serialization.DefaultSerializers$ObjectSerializer.read(DefaultSerializers.java:201)
        at com.hazelcast.nio.serialization.StreamSerializerAdapter.toObject(StreamSerializerAdapter.java:65)
        at com.hazelcast.nio.serialization.SerializationServiceImpl.toObject(SerializationServiceImpl.java:260)
        at com.hazelcast.map.impl.LazyEntryView.getValue(LazyEntryView.java:57)
        at com.hazelcast.map.merge.HigherHitsMapMergePolicy.merge(HigherHitsMapMergePolicy.java:38)
        at com.hazelcast.map.impl.DefaultRecordStore.merge(DefaultRecordStore.java:791)
        at com.hazelcast.map.impl.operation.MergeOperation.run(MergeOperation.java:47)
        at com.hazelcast.spi.impl.BasicOperationService$OperationHandler.handle(BasicOperationService.java:733)
        at com.hazelcast.spi.impl.BasicOperationService$OperationHandler.access$500(BasicOperationService.java:709)
        at com.hazelcast.spi.impl.BasicOperationService$BasicDispatcherImpl.dispatch(BasicOperationService.java:560)
        at com.hazelcast.spi.impl.BasicOperationScheduler$OperationThread.process(BasicOperationScheduler.java:466)
        at com.hazelcast.spi.impl.BasicOperationScheduler$OperationThread.doRun(BasicOperationScheduler.java:458)
        at com.hazelcast.spi.impl.BasicOperationScheduler$OperationThread.run(BasicOperationScheduler.java:432)
Caused by: java.lang.ClassNotFoundException: org.apache.activemq.command.ActiveMQQueue
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at com.hazelcast.nio.ClassLoaderUtil.tryLoadClass(ClassLoaderUtil.java:124)
        at com.hazelcast.nio.ClassLoaderUtil.loadClass(ClassLoaderUtil.java:113)
        at com.hazelcast.nio.IOUtil$1.resolveClass(IOUtil.java:113)
        at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1612)
        at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1517)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1771)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)
        at java.util.HashMap.readObject(HashMap.java:1180)
        at sun.reflect.GeneratedMethodAccessor33.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1017)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1893)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1990)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1915)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)
        at com.hazelcast.nio.serialization.DefaultSerializers$ObjectSerializer.read(DefaultSerializers.java:196)
        ... 12 more
```
