### ISSUE TITLE
Improper behavior on client authentication failure

### ISSUE THREAD

**Issue by pveentjer** [hazelcast/hazelcast#3769]
There is a problem with client authentication. Instead of getting an AuthenticationException, a IllegalStateException is thrown. I see that the AuthenticationRequest does throw an exception; but somehow it leads to the connection getting closed and the client not being able to read out the exception.

```
@Test(expected = AuthenticationException.class)
    public void authenticationError() throws Throwable {
        final HazelcastInstance hzlCluster = Hazelcast.newHazelcastInstance();

        final ClientConfig clientConfig = new ClientConfig();
        clientConfig.setGroupConfig(new GroupConfig("unknown-group", "invalid-pwd"));

        final List<String> addresse = new ArrayList<String>();
        addresse.add("localhost:" + hzlCluster.getConfig().getNetworkConfig().getPort());
        clientConfig.setAddresses(addresse);

        try {
            HazelcastClient.newHazelcastClient(clientConfig);
        } catch (final RuntimeException e) {
            if (e.getCause() != null && e.getCause() instanceof AuthenticationException) {
                throw e.getCause();
            } else {
                throw e;
            }
        }
    }

The same JUnit test launched with a version 3.2, 3.3 or 3.4-SNAPSHOT throws an error due to the initial partitions, not the invalid credentials:
java.lang.Exception: Unexpected exception, expected<com.hazelcast.client.AuthenticationException> but was<java.lang.IllegalStateException>
    at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:28)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: java.lang.IllegalStateException: Cannot get initial partitions!
    at com.hazelcast.client.spi.impl.ClientPartitionServiceImpl.getInitialPartitions(ClientPartitionServiceImpl.java:105)
    at com.hazelcast.client.spi.impl.ClientPartitionServiceImpl.start(ClientPartitionServiceImpl.java:63)
    at com.hazelcast.client.HazelcastClient.start(HazelcastClient.java:260)
    at com.hazelcast.client.HazelcastClient.newHazelcastClient(HazelcastClient.java:222)
    at org.ow2.petals.microkernel.registry.overlay.testAuthenticationError.authenticationError(testAuthenticationError.java:46)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)
```

**Comment by cdeneux** [comment]
Hi sancar, pveentjer,
Any news on this subject ? How can I check only invalid credentials on the HZL client side ?
Regards

**Comment by sancar** [comment]
Hi, I am not sure how we can expose this information with current design because of the reasons that I described earlier in my comment. And currently there is no way to learn if credentials are valid or not. 

One thing that comes to my mind is to throw a special exception that has a method like 
Map<Address, Exception > getFailures();
when client can not connect to any address in the list. Than you may check exception of a specific address, if it is Invalid Credentials or a network problem(IOException).

But again we are not working on this particular issue right now. 

You either need to change your design(You may need to rely on hazelcast client retry mechanism only)
,or modify the hazelcast with an exception like I mentioned.
