### ISSUE TITLE
[TEST-FIX] ProducerConsumerConditionStressTest.test

### ISSUE THREAD

**Issue by mesutcelik** [hazelcast/hazelcast#3789]
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-problematicTest/com.hazelcast$hazelcast/272/testReport/junit/com.hazelcast.concurrent.lock/ProducerConsumerConditionStressTest/test/

```
java.lang.AssertionError: Timeout waiting for thread ProducerThread-1 to terminate
	at org.junit.Assert.fail(Assert.java:88)
	at com.hazelcast.test.HazelcastTestSupport.assertJoinable(HazelcastTestSupport.java:153)
	at com.hazelcast.concurrent.lock.ProducerConsumerConditionStressTest.test(ProducerConsumerConditionStressTest.java:49)
```

**Comment by jerrinot** [comment]
fixed by #8269
