### ISSUE TITLE
MapProxyImpl.aggregate hangs sometimes

### ISSUE THREAD

**Issue by antoinebaudoux** [hazelcast/hazelcast#3824]
Hello, 

I'm using the new IMap.aggregate method to compute statistics. I need to perform a count of map entries, grouped by a given property. The property value is extracted using a generic "propertyExtractor".

Since this feature is not supported natively, I first get the disctinct property values:

``` java
List<String> values = Lists.newArrayList(liveStatsMap.aggregate(Supplier.fromPredicate((entry) -> channel.equals(entry.getValue().getChannel()),Supplier.all(propertyExtractor)),
                    Aggregations.distinctValues()));
```

Then I launch one thread per value to perform the counts:

``` java
List<Callable<Long>> callables = Lists.newArrayList();
for (String value : values) {
    callables.add(() -> liveStatsMap.aggregate(Supplier.fromPredicate((entry) -> channel.equals(entry.getValue().getChannel()) && value.equals(propertyExtractor.extract(entry.getValue()))),
                        Aggregations.count()));
}
List<Future<Long>> futures = statsComputeThreads.invokeAll(callables);
```

It works most of the time, but sometimes one of the "aggregate" calls in the "for" loop hangs and never returns.

Here is the stack trace:

```
at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1037)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1328)
    at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:277)
    at com.hazelcast.mapreduce.impl.task.TrackableJobFuture.get(TrackableJobFuture.java:123)
    at com.hazelcast.spi.impl.AbstractCompletableFuture.get(AbstractCompletableFuture.java:87)
    at com.hazelcast.map.proxy.MapProxyImpl.aggregate(MapProxyImpl.java:682)
    at com.hazelcast.map.proxy.MapProxyImpl.aggregate(MapProxyImpl.java:656)
```

Another trace is:

"hz.ecstreaming.wait-notify" #134 prio=5 os_prio=0 tid=0x00007fc6d48d2800 nid=0x72d5 waiting on     condition [0x00007fc5210cf000]
   java.lang.Thread.State: TIMED_WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000000802361b8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
        at java.util.concurrent.DelayQueue.poll(DelayQueue.java:259)
        at com.hazelcast.spi.impl.WaitNotifyServiceImpl$ExpirationTask.doRun(WaitNotifyServiceImpl.java:430)
        at com.hazelcast.spi.impl.WaitNotifyServiceImpl$ExpirationTask.run(WaitNotifyServiceImpl.java:415)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
        at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
        at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)
Can you confirm that this should never happen and that is is a bug?

Thanks,

Antoine

**Comment by markathomas** [comment]
I am seeing errors that appear related to this issue in Hazelcast 3.4.1.  I have copied the aggregate code from the IMap implementation so that I can return a Future instead of requiring an immediate result.  On server start, all my DAO classes perform an max aggregation on each map associated with a persistent entity in order to find the max id for objects of that type.  This value is used as the seed value for initializing an IdGenerator.  All DAOs except for one work perfectly.  The one with issues deals with two separate derivations of a common interface with one representing 'local' objects and the other 'remote'.  For this DAO I perform two async aggregations at the same time but on two separate IMaps.  Pretty much every time this code is executed the operations encounter a serialization exception and then throw a time out exception on the calling node.  Here is the stack trace. Any help on this matter would be greatly appreciated.
```
2015-03-03 10:59:31,452 [CallStateManager-executor-thread-1] ERROR: failed to compute max display id due to an exception
java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.hazelcast.nio.serialization.HazelcastSerializationException: java.io.EOFException
	at com.hazelcast.mapreduce.impl.task.TrackableJobFuture.setResult(TrackableJobFuture.java:77)
	at com.hazelcast.mapreduce.impl.task.JobSupervisor.notifyRemoteException(JobSupervisor.java:153)
	at com.hazelcast.mapreduce.impl.operation.NotifyRemoteExceptionOperation.run(NotifyRemoteExceptionOperation.java:54)
	at com.hazelcast.spi.impl.BasicOperationService$OperationHandler.handle(BasicOperationService.java:733)
	at com.hazelcast.spi.impl.BasicOperationService$OperationHandler.access$500(BasicOperationService.java:709)
	at com.hazelcast.spi.impl.BasicOperationService$OperationPacketHandler.handle(BasicOperationService.java:683)
	at com.hazelcast.spi.impl.BasicOperationService$OperationPacketHandler.handle(BasicOperationService.java:627)
	at com.hazelcast.spi.impl.BasicOperationService$OperationPacketHandler.access$1500(BasicOperationService.java:614)
	at com.hazelcast.spi.impl.BasicOperationService$BasicDispatcherImpl.dispatch(BasicOperationService.java:566)
	at com.hazelcast.spi.impl.BasicOperationScheduler$OperationThread.process(BasicOperationScheduler.java:466)
	at com.hazelcast.spi.impl.BasicOperationScheduler$OperationThread.doRun(BasicOperationScheduler.java:458)
	at com.hazelcast.spi.impl.BasicOperationScheduler$OperationThread.run(BasicOperationScheduler.java:432)
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.hazelcast.nio.serialization.HazelcastSerializationException: java.io.EOFException
	at com.hazelcast.mapreduce.impl.MapReduceUtil.requestAssignment(MapReduceUtil.java:221)
	at com.hazelcast.mapreduce.impl.MapReduceUtil.mapResultToMember(MapReduceUtil.java:183)
	at com.hazelcast.mapreduce.impl.task.MapCombineTask.sendLastChunkToAssignedReducers(MapCombineTask.java:194)
	at com.hazelcast.mapreduce.impl.task.MapCombineTask.finalizeMapping(MapCombineTask.java:169)
	at com.hazelcast.mapreduce.impl.task.MapCombineTask.processPartitionMapping(MapCombineTask.java:246)
	at com.hazelcast.mapreduce.impl.task.MapCombineTask.access$700(MapCombineTask.java:64)
	at com.hazelcast.mapreduce.impl.task.MapCombineTask$PartitionProcessor.processPartitions(MapCombineTask.java:296)
	at com.hazelcast.mapreduce.impl.task.MapCombineTask$PartitionProcessor.run(MapCombineTask.java:273)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at com.hazelcast.util.executor.CompletableFutureTask.run(CompletableFutureTask.java:57)
	at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:209)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)
	at ------ End remote and begin local stack-trace ------.(Unknown Source)
	at ------ Operation failed on node: Address[10.1.3.10]:5701 ------.notifyRemoteException(JobSupervisor.java:151)
	at com.hazelcast.mapreduce.impl.task.JobSupervisor.notifyRemoteException(JobSupervisor.java:151)
	... 10 more
Caused by: java.util.concurrent.ExecutionException: com.hazelcast.nio.serialization.HazelcastSerializationException: java.io.EOFException
	at com.hazelcast.spi.impl.BasicInvocationFuture.resolveApplicationResponseOrThrowException(BasicInvocationFuture.java:343)
	at com.hazelcast.spi.impl.BasicInvocationFuture.get(BasicInvocationFuture.java:194)
	at com.hazelcast.spi.impl.BasicInvocationFuture.get(BasicInvocationFuture.java:173)
	at com.hazelcast.mapreduce.impl.MapReduceService.processRequest(MapReduceService.java:223)
	at com.hazelcast.mapreduce.impl.MapReduceUtil.requestAssignment(MapReduceUtil.java:207)
	at com.hazelcast.mapreduce.impl.MapReduceUtil.mapResultToMember(MapReduceUtil.java:183)
	at com.hazelcast.mapreduce.impl.task.MapCombineTask.sendLastChunkToAssignedReducers(MapCombineTask.java:194)
	at com.hazelcast.mapreduce.impl.task.MapCombineTask.finalizeMapping(MapCombineTask.java:169)
	at com.hazelcast.mapreduce.impl.task.MapCombineTask.processPartitionMapping(MapCombineTask.java:246)
	at com.hazelcast.mapreduce.impl.task.MapCombineTask.access$700(MapCombineTask.java:64)
	at com.hazelcast.mapreduce.impl.task.MapCombineTask$PartitionProcessor.processPartitions(MapCombineTask.java:296)
	at com.hazelcast.mapreduce.impl.task.MapCombineTask$PartitionProcessor.run(MapCombineTask.java:273)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at com.hazelcast.util.executor.CompletableFutureTask.run(CompletableFutureTask.java:57)
	at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:209)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)
Caused by: com.hazelcast.nio.serialization.HazelcastSerializationException: java.io.EOFException
	at com.hazelcast.nio.serialization.SerializationServiceImpl.handleException(SerializationServiceImpl.java:419)
	at com.hazelcast.nio.serialization.SerializationServiceImpl.readObject(SerializationServiceImpl.java:315)
	at com.hazelcast.nio.serialization.ByteArrayObjectDataInput.readObject(ByteArrayObjectDataInput.java:439)
	at com.hazelcast.mapreduce.impl.operation.KeysAssignmentOperation.readInternal(KeysAssignmentOperation.java:119)
	at com.hazelcast.spi.Operation.readData(Operation.java:299)
	at com.hazelcast.nio.serialization.DataSerializer.read(DataSerializer.java:111)
	at com.hazelcast.nio.serialization.DataSerializer.read(DataSerializer.java:39)
	at com.hazelcast.nio.serialization.StreamSerializerAdapter.toObject(StreamSerializerAdapter.java:65)
	at com.hazelcast.nio.serialization.SerializationServiceImpl.toObject(SerializationServiceImpl.java:260)
	at com.hazelcast.spi.impl.NodeEngineImpl.toObject(NodeEngineImpl.java:186)
	at com.hazelcast.spi.impl.BasicOperationService$OperationPacketHandler.loadOperation(BasicOperationService.java:638)
	at com.hazelcast.spi.impl.BasicOperationService$OperationPacketHandler.handle(BasicOperationService.java:621)
	at com.hazelcast.spi.impl.BasicOperationService$OperationPacketHandler.access$1500(BasicOperationService.java:614)
	at com.hazelcast.spi.impl.BasicOperationService$BasicDispatcherImpl.dispatch(BasicOperationService.java:566)
	at com.hazelcast.spi.impl.BasicOperationScheduler$OperationThread.process(BasicOperationScheduler.java:466)
	at com.hazelcast.spi.impl.BasicOperationScheduler$OperationThread.doRun(BasicOperationScheduler.java:458)
	at com.hazelcast.spi.impl.BasicOperationScheduler$OperationThread.run(BasicOperationScheduler.java:432)
	at ------ End remote and begin local stack-trace ------.(Unknown Source)
	at com.hazelcast.spi.impl.BasicInvocationFuture.resolveApplicationResponse(BasicInvocationFuture.java:387)
	at com.hazelcast.spi.impl.BasicInvocationFuture.resolveApplicationResponseOrThrowException(BasicInvocationFuture.java:320)
	... 20 more
Caused by: java.io.EOFException
	at com.hazelcast.nio.serialization.ByteArrayObjectDataInput.readBoolean(ByteArrayObjectDataInput.java:104)
	at com.hazelcast.nio.serialization.SerializationServiceImpl.readObject(SerializationServiceImpl.java:297)
	at com.hazelcast.nio.serialization.ByteArrayObjectDataInput.readObject(ByteArrayObjectDataInput.java:439)
	at com.hazelcast.mapreduce.impl.operation.KeysAssignmentOperation.readInternal(KeysAssignmentOperation.java:119)
	at com.hazelcast.spi.Operation.readData(Operation.java:299)
	at com.hazelcast.nio.serialization.DataSerializer.read(DataSerializer.java:111)
	at com.hazelcast.nio.serialization.DataSerializer.read(DataSerializer.java:39)
	at com.hazelcast.nio.serialization.StreamSerializerAdapter.toObject(StreamSerializerAdapter.java:65)
	at com.hazelcast.nio.serialization.SerializationServiceImpl.toObject(SerializationServiceImpl.java:260)
	at com.hazelcast.spi.impl.NodeEngineImpl.toObject(NodeEngineImpl.java:186)
	at com.hazelcast.spi.impl.BasicOperationService$OperationPacketHandler.loadOperation(BasicOperationService.java:638)
	at com.hazelcast.spi.impl.BasicOperationService$OperationPacketHandler.handle(BasicOperationService.java:621)
	at com.hazelcast.spi.impl.BasicOperationService$OperationPacketHandler.access$1500(BasicOperationService.java:614)
	at com.hazelcast.spi.impl.BasicOperationService$BasicDispatcherImpl.dispatch(BasicOperationService.java:566)
	at com.hazelcast.spi.impl.BasicOperationScheduler$OperationThread.process(BasicOperationScheduler.java:466)
	at com.hazelcast.spi.impl.BasicOperationScheduler$OperationThread.doRun(BasicOperationScheduler.java:458)
	at com.hazelcast.spi.impl.BasicOperationScheduler$OperationThread.run(BasicOperationScheduler.java:432)
```

**Comment by noctarius** [comment]
Why do you think this is related to this previous issue? Your stacktrace talks about an EOF exception which means there is something wrong in the network or serialization. Are you sure your serialization code is symmetric? This heavily sounds like you have too less data written to the stream (on serialization) and therefore your deserialization doesn't work. As you see on the stacktrace it fails on reading a boolean.

**Comment by markathomas** [comment]
this only happens for aggregation and a timeout is thrown which is why i
thought they might be related.  the serialization error stems from a
Hazelcast class and not my own so I have no idea how to fix it

Regards,

Mark Thomas
spatialguru.net@gmail.com
205.529.9013

"Commit to the Lord whatever you do,
    and your plans will succeed." - Proverbs 16:3

**Comment by noctarius** [comment]
I guess the timeout happens because the operation fails internally, is killed and eventually you get the timeout exception. Can you show the failing DAO code?

**Comment by markathomas** [comment]
```
@Override
    protected Future<Collection<Long>> getInitialSequenceValueFuture() {
        this.logger.debug("Looking up initial sequence value for RealtimeLocalParticipant");
        Supplier<Serializable, RealtimeLocalParticipant, Long> localSupplier =
          Supplier.all(new DisplayIdPropertyExtractor<RealtimeLocalParticipant>());
        Aggregation<Serializable, Long, Long> localAggregation = Aggregations.longMax();
        Cache<Serializable, RealtimeLocalParticipant> cache =
          this.hazelcast.getNonTransactionalCache(RealtimeLocalParticipant.class);
        Future<Long> localMax = cache.aggregateAsync(localSupplier, localAggregation);

        this.logger.debug("Looking up initial sequence value for RealtimeRemoteParticipant");
        Supplier<Serializable, RealtimeRemoteParticipant, Long> remoteSupplier =
          Supplier.all(new DisplayIdPropertyExtractor<RealtimeRemoteParticipant>());
        Aggregation<Serializable, Long, Long> remoteAggregation = Aggregations.longMax();
        Cache<Serializable, RealtimeRemoteParticipant> remoteCache =
          this.hazelcast.getNonTransactionalCache(RealtimeRemoteParticipant.class);
        Future<Long> remoteMax = remoteCache.aggregateAsync(remoteSupplier, remoteAggregation);

        return new CombinedFuture<>(Arrays.asList(localMax, remoteMax));
    }
```

**Comment by markathomas** [comment]
And here's the property extractor:
```java
public class DisplayIdPropertyExtractor<T extends GridObject> implements PropertyExtractor<T, Long>  {

    private static final long serialVersionUID = 4491963115539411190L;

    public Long extract(T value) {
        return value.getDisplayId();
    }
}
```

**Comment by noctarius** [comment]
So what happens is, it fails to assign a key since one of the keys cannot be read. What is the key class and what does it look like?

**Comment by markathomas** [comment]
The key class is a Serializable version of PartitionAwareKey defined as
AffinityKey<UUID, AffinityKey<UUID, UUID>> where the key is the object's
UUID and the partition key is an affinity key with the UUID of a PhoneCall
object as the key and the UUID of the node the call was created on as it's
partition key

Regards,

Mark Thomas
spatialguru.net@gmail.com
205.529.9013

"Commit to the Lord whatever you do,
    and your plans will succeed." - Proverbs 16:3

**Comment by noctarius** [comment]
Are you sure the same version of the class is deployed everywhere? Is it just Serializable or have you used Externalizable or (Identified)DataSerializable? What version exactly do you use?

**Comment by markathomas** [comment]
Yes, it is deployed everywhere.  It uses Kryo for serialization.  Again,
this only happens on aggregation where two aggregations are started
concurrently.  If the serialization was wrong I'd be getting errors on
every put to the IMap. We are using version Hazelcast version 3.4.1.

Regards,

Mark Thomas
spatialguru.net@gmail.com
205.529.9013

"Commit to the Lord whatever you do,
    and your plans will succeed." - Proverbs 16:3

**Comment by noctarius** [comment]
Well if there is a problem in the system it needs to be triggered by something that is special about these classes since I guess the aggregation is almost the same all the time, isn't it?

**Comment by noctarius** [comment]
"If the serialization was wrong I'd be getting errors on
every put to the IMap."
PS: This is not correct since deserialization fails and we don't do deserialization on a put.

**Comment by markathomas** [comment]
yes, you are correct.  the aggregation is always the same.

Regards,

Mark Thomas
spatialguru.net@gmail.com
205.529.9013

"Commit to the Lord whatever you do,
    and your plans will succeed." - Proverbs 16:3

**Comment by markathomas** [comment]
You're right. I meant on queries. I have no problem querying the maps these
objects are in.  If I did I'd definitely know it as my app would cease to
function.

Regards,

Mark Thomas
spatialguru.net@gmail.com
205.529.9013

"Commit to the Lord whatever you do,
    and your plans will succeed." - Proverbs 16:3

**Comment by noctarius** [comment]
Mh that's true but currently there is no chance to even guess what it is. Since the deserialization fails and it fails on a key, the only logical reason is a broken key serialization. There might be others but with the given information this is the most obvious one, sorry :)

**Comment by markathomas** [comment]
sure, thanks for the ideas. i'll try and debug it over JVMTI

Regards,

Mark Thomas
spatialguru.net@gmail.com
205.529.9013

"Commit to the Lord whatever you do,
    and your plans will succeed." - Proverbs 16:3

**Comment by noctarius** [comment]
Perfect, please let me know - eager to know what the reason is! :)
