### ISSUE TITLE
JoinStressTest.testTCPIPJoinWithManyNodes

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#3888]
com.hazelcast.cluster.JoinStressTest.testTCPIPJoinWithManyNodes

```
java.lang.AssertionError: expected:<20> but was:<18>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at com.hazelcast.cluster.JoinStressTest.testJoinWithManyNodes(JoinStressTest.java:108)
    at com.hazelcast.cluster.JoinStressTest.testTCPIPJoinWithManyNodes(JoinStressTest.java:68)
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/345/testReport/junit/com.hazelcast.cluster/JoinStressTest/testTCPIPJoinWithManyNodes/

**Comment by hasancelik** [comment]
new failure with different error:
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertNotNull(Assert.java:712)
	at org.junit.Assert.assertNotNull(Assert.java:722)
	at com.hazelcast.cluster.JoinStressTest.testJoinWithManyNodes(JoinStressTest.java:149)
	at com.hazelcast.cluster.JoinStressTest.testTCPIPJoinWithManyNodes(JoinStressTest.java:78)

```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/651/testReport/junit/com.hazelcast.cluster/JoinStressTest/testTCPIPJoinWithManyNodes/

**Comment by eminn** [comment]
No build log available and the tests are passing for a long time.

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: Cluster size is not correct. Expected: 20 Actual: 8
	at org.junit.Assert.fail(Assert.java:88)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSize(HazelcastTestSupport.java:915)
	at com.hazelcast.test.HazelcastTestSupport$13.run(HazelcastTestSupport.java:937)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1086)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:933)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:927)
	at com.hazelcast.cluster.JoinStressTest.testJoinWithManyNodes(JoinStressTest.java:136)
	at com.hazelcast.cluster.JoinStressTest.testTCPIPJoinWithManyNodes(JoinStressTest.java:72)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/1461/testReport/junit/com.hazelcast.cluster/JoinStressTest/testTCPIPJoinWithManyNodes/

**Comment by hasancelik** [comment]
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.lang.Thread.sleep(Native Method)
	at java.lang.Thread.sleep(Thread.java:340)
	at java.util.concurrent.TimeUnit.sleep(TimeUnit.java:360)
	at com.hazelcast.test.HazelcastTestSupport.sleepMillis(HazelcastTestSupport.java:308)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1113)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:952)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:946)
	at com.hazelcast.cluster.JoinStressTest.testJoinWithManyNodes(JoinStressTest.java:138)
	at com.hazelcast.cluster.JoinStressTest.testTCPIPJoinWithManyNodes(JoinStressTest.java:74)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/1477/testReport/junit/com.hazelcast.cluster/JoinStressTest/testTCPIPJoinWithManyNodes/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: Cluster size is not correct. Expected: 20, actual: 18, instance index: 0
	at org.junit.Assert.fail(Assert.java:88)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSize(HazelcastTestSupport.java:957)
	at com.hazelcast.test.HazelcastTestSupport$13.run(HazelcastTestSupport.java:978)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1149)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:975)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:969)
	at com.hazelcast.cluster.JoinStressTest.testJoinWithManyNodes(JoinStressTest.java:140)
	at com.hazelcast.cluster.JoinStressTest.testTCPIPJoinWithManyNodes(JoinStressTest.java:76)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/1576/testReport/junit/com.hazelcast.cluster/JoinStressTest/testTCPIPJoinWithManyNodes/

**Comment by blazember** [comment]
Last failure:
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly-lab/6/testReport/junit/com.hazelcast.cluster/JoinStressTest/testTCPIPJoinWithManyNodes/

History: https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly-lab/6/testReport/junit/com.hazelcast.cluster/JoinStressTest/testTCPIPJoinWithManyNodes/history/

**Comment by blazember** [comment]
In the last failing build, there were a couple notable pauses that sum up to 12s, which itself is around the max execution time for this test:
```
23:54:55, accumulated pauses: 6415 ms, max pause: 6408 ms, pauses over 1000 ms: 1
23:55:10, accumulated pauses: 2558 ms, max pause: 2527 ms, pauses over 1000 ms: 1
23:57:30, accumulated pauses: 2456 ms, max pause: 2431 ms, pauses over 1000 ms: 1
23:58:15, accumulated pauses: 718 ms, max pause: 504 ms, pauses over 1000 ms: 0
```

**Comment by mmedenjak** [comment]
@blazember can we now close this issue until it fails again?

**Comment by blazember** [comment]
@mmedenjak yes, closed it. Let's see the improved logs if it fails again.
