### ISSUE TITLE
[TEST-FAILURE] MapReduceStressTest.test

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#3889]
com.hazelcast.mapreduce.MapReduceStressTest.test

```
java.lang.Exception: test timed out after 60000 milliseconds
	at java.lang.Thread.sleep(Native Method)
	at com.hazelcast.test.HazelcastTestSupport.sleepMillis(HazelcastTestSupport.java:215)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:248)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:137)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:133)
	at com.hazelcast.mapreduce.MapReduceStressTest.test(MapReduceStressTest.java:63)
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/344/testReport/junit/com.hazelcast.mapreduce/MapReduceStressTest/test/

**Comment by bilalyasar** [comment]
new failure:
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/434/testReport/junit/com.hazelcast.mapreduce/MapReduceStressTest/test/
