### ISSUE TITLE
Creating a simple GlassFish service to use Hazelcast fails

### ISSUE THREAD

**Issue by smillidge** [hazelcast/hazelcast#3922]
Creating a simple GlassFish kernel service;

@Service(name="hazelcast")
@RunLevel(StartupRunLevel.VAL)
public class HazelcastBootstrap {
    
    private HazelcastInstance theInstance;

    @PostConstruct
    public void postConstruct() {
        theInstance = Hazelcast.newHazelcastInstance();
    }
    
}

Fails with exception;
java.lang.IllegalArgumentException: PortableFactory[-20] is already registered! com.hazelcast.nio.serialization.ArrayPortableFactory@2dc65993 -> com.hazelcast.nio.serialization.ArrayPortableFactory@691a29cb
	at com.hazelcast.nio.serialization.PortableHookLoader.register(PortableHookLoader.java:84)
	at com.hazelcast.nio.serialization.PortableHookLoader.load(PortableHookLoader.java:51)
	at com.hazelcast.nio.serialization.PortableHookLoader.<init>(PortableHookLoader.java:41)
	at com.hazelcast.nio.serialization.SerializationServiceImpl.<init>(SerializationServiceImpl.java:85)
	at com.hazelcast.nio.serialization.SerializationServiceBuilder.build(SerializationServiceBuilder.java:174)
	at com.hazelcast.instance.Node.<init>(Node.java:158)
	at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:95)
	at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:147)
	at com.hazelcast.instance.HazelcastInstanceFactory.getOrCreateHazelcastInstance(HazelcastInstanceFactory.java:94)
	at com.hazelcast.core.Hazelcast.getOrCreateHazelcastInstance(Hazelcast.java:116)
	at fish.payara.nucleus.hazelcast.HazelcastBootstrap.postConstruct(HazelcastBootstrap.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.glassfish.hk2.utilities.reflection.ReflectionHelper.invoke(ReflectionHelper.java:1019)
	at org.jvnet.hk2.internal.ClazzCreator.postConstructMe(ClazzCreator.java:335)
	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:377)
	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:471)
	at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:227)
	at org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:84)
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2270)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:105)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:87)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1223)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1154)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$UpOneLevel.run(CurrentTaskFuture.java:754)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

I have debugged this and there are two classloaders referenced during the load of the hooks. However when these are setup in ServiceLoader.java in the code snippet below the URL contained in the URL definition is identical for both and the URL in both points to the same core Hazelcast OSGI bundle. Therefore there is only one set of classes in the installation but Hazelcast has detected two ClassLoaders to load from and therefore loads the definitions twice.

        for (ClassLoader selectedClassLoader : classLoaders) {
            factoryUrls.addAll(collectFactoryUrls(factoryId, selectedClassLoader));
        }
        final Set<ServiceDefinition> serviceDefinitions = new HashSet<ServiceDefinition>();
        for (URLDefinition urlDefinition : factoryUrls) {
            serviceDefinitions.addAll(parse(urlDefinition));
        }

Therefore is it possible to modify ServiceLoader to only add service definitions from unique URLs?

**Comment by mesutcelik** [comment]
@jerrinot , @serkan-ozal ,

I think we need to create a new enhancement issue with the explanation of what the proper fix looks like... and close this one... This issue has lots of comments in it...

Can one of you do that?

**Comment by mesutcelik** [comment]
I am closing this one. Better solution will be provided in future releases.

**Comment by ejain** [comment]
Looks like the "better solution" is still pending, see #2395...
