### ISSUE TITLE
java.lang.IllegalMonitorStateException: Current thread is not owner of the lock! with Hazelcast 3.3

### ISSUE THREAD

**Issue by akonapur** [hazelcast/hazelcast#3942]
Hi ,
We are using hazelcast v3.3 on standalone jboss 7.2.
The application works fine and then all of a sudden we start seeing the following exception.
The owner of the lock is shown as *dc639862-6273-4b41-a337-2c818bf310b3*, however we couldn't find reference to this ID even in thread dumps. The thread which get into this exception is the same *thread with id: 1009*, still it complains as not owner of lock.
Exception:
2014-10-27 21:29:23,977 10.4.204.41 (trafficScheduleImportJobsManager-244) ERROR ***[com.omn.common.msg.MessageFactory] {MsfMessaging} Error occurred while Releasing Lock on: queue/ScheduleImportJobs Owner:trafficScheduleImportJobsManager-244
java.lang.IllegalMonitorStateException: Current thread is not owner of the lock! -> Owner: dc639862-6273-4b41-a337-2c818bf310b3, *thread-id: 1009*
at com.hazelcast.concurrent.lock.operations.UnlockOperation.ensureUnlocked(UnlockOperation.java:71)
at com.hazelcast.concurrent.lock.operations.UnlockOperation.unlock(UnlockOperation.java:65)
at com.hazelcast.concurrent.lock.operations.UnlockOperation.run(UnlockOperation.java:57)
at com.hazelcast.spi.impl.BasicOperationService$OperationHandler.handle(BasicOperationService.java:699)
at com.hazelcast.spi.impl.BasicOperationService$OperationHandler.access$400(BasicOperationService.java:675)
at com.hazelcast.spi.impl.BasicOperationService$BasicDispatcherImpl.dispatch(BasicOperationService.java:537)
at com.hazelcast.spi.impl.BasicOperationScheduler$OperationThread.process(BasicOperationScheduler.java:439)
at com.hazelcast.spi.impl.BasicOperationScheduler$OperationThread.doRun(BasicOperationScheduler.java:433)
at com.hazelcast.spi.impl.BasicOperationScheduler$OperationThread.run(BasicOperationScheduler.java:408)

**Comment by gurbuzali** [comment]
closing this one now, feel free to re-open if your are still experiencing the issue
