### ISSUE TITLE
[TEST-FAILURE] BasicCacheTest.testCompletionTest

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#3968]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OracleJDK8/com.hazelcast$hazelcast/239/testReport/junit/com.hazelcast.cache/BasicCacheTest/testCompletionTest/
```
junit.framework.AssertionFailedError: expected:<2> but was:<1>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at junit.framework.Assert.assertEquals(Assert.java:241)
	at com.hazelcast.cache.BasicCacheTest.testCompletionTest(BasicCacheTest.java:203)
```

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-OracleJDK8/com.hazelcast$hazelcast/171/testReport/junit/com.hazelcast.cache/BasicCacheTest/testCompletionTest/
