### ISSUE TITLE
NullPointerException in com.hazelcast.spi.impl.EventServiceImpl

### ISSUE THREAD

**Issue by vkkotha** [hazelcast/hazelcast#4017]
Getting a NPE in a distributed hazelcast when using hibernate secondary cache.
Seems like Topic dispatcher is sending null as newVersion causing this exception.
Happens when a Versioned Class & a Collection are Cached. Due to this the items from cache are not removed on update.

```
[2014-11-06 02:45:04,257] [FATAL] [com.hazelcast.spi.impl.EventServiceImpl] [hz.hazelcast.event-4] [127.0.0.1]:5702 [dev] [3.3.2] hz.hazelcast.event-4 caught an exception while processing task:EventPacketProcessor{eventPacket=null}
java.lang.NullPointerException
    at org.hibernate.internal.util.compare.ComparableComparator.compare(ComparableComparator.java:41)
    at org.hibernate.internal.util.compare.ComparableComparator.compare(ComparableComparator.java:36)
    at com.hazelcast.hibernate.local.LocalRegionCache$3.onMessage(LocalRegionCache.java:158)
    at com.hazelcast.topic.impl.TopicService.dispatchEvent(TopicService.java:135)
    at com.hazelcast.spi.impl.EventServiceImpl$EventPacketProcessor.process(EventServiceImpl.java:537)
    at com.hazelcast.spi.impl.EventServiceImpl$RemoteEventPacketProcessor.run(EventServiceImpl.java:617)
    at com.hazelcast.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:189)
    at com.hazelcast.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:173)
```

**Comment by Zubastick** [comment]
We have the same problem.

This occurs on a distributed environment with HazelcastLocalCacheRegionFactory when collection that contains Hibernate @Version column in an entity is loaded.

Please reopen the issue. We are using Hazelcast 3.5.1

**Comment by Zubastick** [comment]
Stackstrace:

java.lang.NullPointerException 
	at org.hibernate.internal.util.compare.ComparableComparator.compare(ComparableComparator.java:41) 
	at org.hibernate.internal.util.compare.ComparableComparator.compare(ComparableComparator.java:36) 
	at com.hazelcast.hibernate.local.LocalRegionCache$3.onMessage(LocalRegionCache.java:158) 
	at com.hazelcast.topic.impl.TopicService.dispatchEvent(TopicService.java:138) 
	at com.hazelcast.spi.impl.eventservice.impl.EventPacketProcessor.process(EventPacketProcessor.java:53) 
	at com.hazelcast.spi.impl.eventservice.impl.RemoteEventPacketProcessor.run(RemoteEventPacketProcessor.java:38) 
	at com.hazelcast.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:190) 
	at com.hazelcast.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:174)

**Comment by emrahkocaman** [comment]
@Zubastick I've tried with this sample project, no luck so far. https://github.com/emrahkocaman/Hazelcast_SecondLevelCache

Can you please try reproducing the issue using the sample project or better try creating a unit test?
