### ISSUE TITLE
Hz 3.2.6,  on Member node Fail:  time window where Map size is wrong and values are Null

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#4048]
Hz version: 3.2.6
stabilizer Test:  com.hazelcast.stabilizer.tests.map.MapIntegrity

using chaosmonkey softKill: at 1 min into run, then 1 more min of running.
using system properties of:
-Dhazelcast.initial.min.cluster.size=271
-Dhazelcast.initial.min.cluster.size=2711

```
MapInit@class=com.hazelcast.stabilizer.tests.map.MapIntegrity
MapInit@mapName=ObjectMap
```

this test with a member node termination situation reveals that there is a window,  after a node has been killed,  where map size can report the wrong size and keys from the map return a null value.
however after a short time the map returns to its original size, and all keys return the correct value.

When running this test with member node termination of 3.4-RC1-SNAPSHOT.  the has not failed.
so after member termination,  the map allway s  returns the correct size.

show that 12 calls to map Size returned the wrong value (to small). 
```
Failure[
   message='Worked ran into an unhandled exception'
   type='Worker exception'
   agentAddress=10.237.144.225
   time=Mon Nov 10 12:45:08 UTC 2014
   workerAddress=10.237.144.225:5701
   workerId=worker-10.237.144.225-1-server
   test=TestCase{
          id=MapInit
        , class=com.hazelcast.stabilizer.tests.map.MapIntegrity
        , mapName=ObjectMap
    }
   cause=junit.framework.AssertionFailedError: com.hazelcast.stabilizer.tests.map.MapIntegrity: Counter{getNull=0, mapSizeError=12} expected:<12> but was:<0>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:159)
	at com.hazelcast.stabilizer.tests.map.MapIntegrity.verify(MapIntegrity.java:147)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.hazelcast.stabilizer.worker.TestContainer.invoke(TestContainer.java:177)
	at com.hazelcast.stabilizer.worker.TestContainer.localVerify(TestContainer.java:152)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.hazelcast.stabilizer.worker.MemberWorker$TestCommandRequestProcessingThread$2.doRun(MemberWorker.java:444)
	at com.hazelcast.stabilizer.worker.MemberWorker$CommandThread.run(MemberWorker.java:535)

]
```

**Comment by gurbuzali** [comment]
closing since related ticket already closed
