### ISSUE TITLE
[TEST-FAILURE] ClientExecutorServiceTest.testGetFutureAfterCancel

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#4142]
```
java.lang.AssertionError: Expected exception: java.util.concurrent.CancellationException
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:32)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at com.hazelcast.test.HazelcastParallelClassRunner.access$201(HazelcastParallelClassRunner.java:26)
	at com.hazelcast.test.HazelcastParallelClassRunner$TestRunner.run(HazelcastParallelClassRunner.java:91)
	at java.lang.Thread.run(Thread.java:662)
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-OpenJDK6/com.hazelcast$hazelcast-client/61/testReport/junit/com.hazelcast.client.executor/ClientExecutorServiceTest/testGetFutureAfterCancel/

**Comment by ahmetmircik** [comment]
failed again see: https://github.com/hazelcast/hazelcast/pull/4486#issuecomment-71850475

**Comment by sancar** [comment]
I am closing this one because 
1) This test is not failing for more than 30 builds. And last fail logs are deleted. 
2) Test is not failing in my local. 
If someone has logs related to this, please reopen the issue.

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: Expected exception: java.util.concurrent.CancellationException
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:32)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:134)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at com.hazelcast.test.HazelcastParallelClassRunner.access$201(HazelcastParallelClassRunner.java:29)
	at com.hazelcast.test.HazelcastParallelClassRunner$TestRunner.run(HazelcastParallelClassRunner.java:89)
	at java.lang.Thread.run(Thread.java:780)
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast$hazelcast-client/629/testReport/junit/com.hazelcast.client.executor/ClientExecutorServiceTest/testGetFutureAfterCancel/
