### ISSUE TITLE
queue.take() doesnt get interrupted on shutdown

### ISSUE THREAD

**Issue by StanAccy** [hazelcast/hazelcast#4143]
When we shutdown Hazelcast with threads listening on a queue, we assumed we would receive interruptions on the waiting threads (its the only exception mentioned in the queue.take() javadoc) - instead we dont, we get HazelcastInstanceNotActiveException thrown.

Please could you clarify in the Javadocs what should occur in this situation (HZ 3.3.2).  We're fine catching the additional exception as long as its declared in the API.

```java
		Config cfg = new Config();

		NetworkConfig networkConfig = new NetworkConfig();
		networkConfig.setPort( 10500 );
		cfg.setNetworkConfig( networkConfig );

		GroupConfig groupConfig = new GroupConfig();
		groupConfig.setName( "test" );
		groupConfig.setPassword( "test" );
		cfg.setGroupConfig( groupConfig );

		HazelcastInstance node = Hazelcast.newHazelcastInstance( cfg );

		Thread t = new Thread( () -> {
			IQueue<Object> testQ = node.getQueue( "test" );

			boolean exit = false;
			while( !exit )
			{
				try
				{
					Object obj = testQ.take();
				}
				catch( InterruptedException e )
				{
					System.err.println( "InterruptedException, exiting..." );
					e.printStackTrace();
					exit = true;
				}
				catch( Exception e )
				{
					System.err.println( "Exception Caught: " + e.getClass().getName() + " : " + e.getMessage() );
					e.printStackTrace();
					exit = true;
				}
			}
		} );
		t.start();

		Thread.sleep( 2000 );
		node.shutdown();
```

**Comment by Serdaro** [comment]
@gurbuzali, do you need any help on this, documentation-wise?

**Comment by ashutosh0205** [comment]
I have also found that not just for shutdown() but when I am actually interrupting thread using thread. interrupt(), I expect it to throw right exception i. e. InterruptedException() and this is the exception which is mentioned in throws clause of take() method but what I am getting is hazelcastException() which has InterruptedException() wrapped inside it.

**Comment by baptistemesta** [comment]
Hi,
Just to add that there is the same issue on Thread.interrupt(). but it's working fine if you use HazelcastClient instead of Halzelcast (see commented code below)
```java
    @Test
    public void testInterrupt() throws InterruptedException {
        HazelcastInstance instance = Hazelcast.newHazelcastInstance();
        HazelcastInstance client = HazelcastClient.newHazelcastClient();
        //KO
        final IQueue<String> hzQueue = instance.getQueue("HZQueue");
        //OK
        //final IQueue<String> hzQueue = client.getQueue("HZQueue");
        //OK
        //final ArrayBlockingQueue<String> hzQueue = new ArrayBlockingQueue<String>(10);
        Thread threadToBeInterrupted = new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    while(true){
                        hzQueue.take();
                    }
                } catch (InterruptedException e) {
                    //ok, will end
                }
            }
        }, "threadToBeInterrupted");
        threadToBeInterrupted.start();
        threadToBeInterrupted.interrupt();
        long before = System.currentTimeMillis();
        threadToBeInterrupted.join(10000);
        assertThat(System.currentTimeMillis() - before).isLessThan(9000).as("should not time out when joining thread after interrupt");
    }
```

**Comment by vertex-github** [comment]
JM2C - throwing anything other than the standard JDK InterruptedException is falling afoul of what most programmers expect should be thrown. If Hazelcast intends to be a drop-in replacement for the standard collections + other stuff, then the expectation is surely that InterruptedException should be thrown in these scenarios.

**Comment by mdogan** [comment]
Common exception types, those can be thrown by any Hazelcast API, are now documented by commit: c300effeaf513afcedb9cc223a64df6932ffbd03 

Also by the commit 68179ecf4a5f8a14aa901490f90711677508862d, `IQueue.take()/poll()/put()/offer()` will not wrap `InterruptedException` inside `HazelcastException`.

**Comment by StanAccy** [comment]
@mdogan Just running a test with 3.4.2.  When Hazelcast is running and I have a thread waiting on a queue.take(), any interruptions to that thread (or an ExecutorService.shutdown() ) dont seem to propagate to the iQueue.take() method.  The thread(s) are blocked inside BasicInvocationFuture.pollResponse().  However, if I take that methods code, and run it outside of Hazelcast and interrupt the thread, everything works as expected.  Im curious to know why the IQueue.take() isnt being interupted.

**Comment by StanAccy** [comment]
BasicInvocationFuture, line 231 catches the InterruptedException and does nothing with it except setting an internal flag.  The interrupted thread loops back around and waits again, thus losing the interrupt. Now the thread waits until Hazelcast shutsdown and then receives a HazelcastInstanceNotActiveException.

Could the initial InterruptedException not be allowed to simply propagate out?

**Comment by StanAccy** [comment]
Also just tried with the 3.4.3 source, we still dont get InterruptedException on a queue.take() operation (test code as above):

```java
16:47:42,045  INFO [HZScratch] Thread-1 - Waiting on IQueue
Jun 11, 2015 4:47:42 PM com.hazelcast.partition.InternalPartitionService
INFO: [10.37.129.2]:10500 [dev] [3.4.3] Initializing cluster partition table first arrangement...
16:47:44,039  INFO [HZScratch] main - Interrupting thread... : Thread-1
16:47:44,039  INFO [HZScratch] main - Waiting on thread...
16:47:46,039  INFO [HZScratch] main - Done.
Jun 11, 2015 4:47:51 PM com.hazelcast.core.LifecycleService
INFO: [10.37.129.2]:10500 [dev] [3.4.3] Address[10.37.129.2]:10500 is SHUTTING_DOWN
Jun 11, 2015 4:47:51 PM com.hazelcast.instance.Node
16:47:51,039  INFO [HZScratch] main - Thread has exited? : false
INFO: [10.37.129.2]:10500 [dev] [3.4.3] Shutting down multicast service...
Jun 11, 2015 4:47:51 PM com.hazelcast.instance.Node
INFO: [10.37.129.2]:10500 [dev] [3.4.3] Shutting down connection manager...
Jun 11, 2015 4:47:51 PM com.hazelcast.instance.Node
INFO: [10.37.129.2]:10500 [dev] [3.4.3] Shutting down node engine...
16:47:51,047 ERROR [HZScratch] Thread-1 - Exception while waiting
com.hazelcast.core.HazelcastInstanceNotActiveException: Hazelcast instance is not active!
	at com.hazelcast.spi.impl.WaitNotifyServiceImpl.shutdown(WaitNotifyServiceImpl.java:235)
	at com.hazelcast.spi.impl.NodeEngineImpl.shutdown(NodeEngineImpl.java:392)
	at com.hazelcast.instance.Node.shutdown(Node.java:407)
	at com.hazelcast.instance.LifecycleServiceImpl.shutdown(LifecycleServiceImpl.java:91)
	at com.hazelcast.instance.HazelcastInstanceProxy.shutdown(HazelcastInstanceProxy.java:238)
	at com.hazelcast.HZScratch.testHZ(HZScratch.java:89)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
16:47:51,051  INFO [HZScratch] Thread-1 - Thread exiting.
```

**Comment by pveentjer** [comment]
The interrupt handling has been improved some time ago. I have run your test

```
Jun 08, 2016 8:03:33 AM com.hazelcast.Main
INFO: Interrupting thread...
Jun 08, 2016 8:03:33 AM com.hazelcast.Main
INFO: Waiting on thread...
Jun 08, 2016 8:04:32 AM com.hazelcast.Main
INFO: Thread interrupted.
Jun 08, 2016 8:04:32 AM com.hazelcast.Main
INFO: Thread exiting.
Jun 08, 2016 8:04:32 AM com.hazelcast.Main
INFO: Done.
Jun 08, 2016 8:04:38 AM com.hazelcast.Main
INFO: Thread has exited? : true<-------------
```
