### ISSUE TITLE
AtomicLongStableReadStressTest.testChangingCluster

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#4179]
```
java.lang.AssertionError: com.hazelcast.client.stress.AtomicLongStableReadStressTest$StressThread1 encountered an error expected null, but was:<com.hazelcast.core.HazelcastInstanceNotActiveException: Hazelcast instance is not ready yet!>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotNull(Assert.java:664)
	at org.junit.Assert.assertNull(Assert.java:646)
	at com.hazelcast.client.stress.StressTestSupport$TestThread.assertNoError(StressTestSupport.java:171)
	at com.hazelcast.client.stress.StressTestSupport.assertNoErrors(StressTestSupport.java:122)
	at com.hazelcast.client.stress.StressTestSupport.joinAll(StressTestSupport.java:143)
	at com.hazelcast.client.stress.AtomicLongStableReadStressTest.test(AtomicLongStableReadStressTest.java:71)
	at com.hazelcast.client.stress.AtomicLongStableReadStressTest.testChangingCluster(AtomicLongStableReadStressTest.java:59)
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-nightly/309/com.hazelcast$hazelcast-client/testReport/com.hazelcast.client.stress/AtomicLongStableReadStressTest/testChangingCluster/

**Comment by hasancelik** [comment]
testChangingCluster
```
java.lang.AssertionError: com.hazelcast.client.stress.AtomicLongStableReadStressTest$StressThread1 encountered an error expected null, but was:<com.hazelcast.core.HazelcastInstanceNotActiveException: State: PASSIVE Operation: class com.hazelcast.concurrent.atomiclong.operations.GetOperation>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotNull(Assert.java:755)
	at org.junit.Assert.assertNull(Assert.java:737)
	at com.hazelcast.client.stress.StressTestSupport$TestThread.assertNoError(StressTestSupport.java:171)
	at com.hazelcast.client.stress.StressTestSupport.assertNoErrors(StressTestSupport.java:122)
	at com.hazelcast.client.stress.StressTestSupport.joinAll(StressTestSupport.java:143)
	at com.hazelcast.client.stress.AtomicLongStableReadStressTest.test(AtomicLongStableReadStressTest.java:72)
	at com.hazelcast.client.stress.AtomicLongStableReadStressTest.testChangingCluster(AtomicLongStableReadStressTest.java:60)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast-client/994/testReport/junit/com.hazelcast.client.stress/AtomicLongStableReadStressTest/testChangingCluster/

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-nightly/994/#showFailuresLink
