### ISSUE TITLE
Hibernate + hazelcast deadlock

### ISSUE THREAD

**Issue by poi212003** [hazelcast/hazelcast#429]
We're using spring + hazelcast 2.1.2 + hibernate 3 (the cluster consists of 2 tomcat instances each is a hazelcast node) and after some time a lot of AJP threads gets stuck (which eventually eats the DB connections), see thread dump: 

When the issue happens - all requests are stuck, if I close one of the tomcats - the connections are released and  the tomcat starts responding again.

Not sure how to reproduce - looks like it happens randomly.

Can someone tell me if it's fixed in the new version?

P.S - looks like the same issue as here: https://code.google.com/p/hazelcast/issues/detail?id=692

```
"ajp-apr-8009-exec-1101" id=42564 idx=0x1f10 tid=34120 prio=5 alive, parked, native_blocked, daemon
    at jrockit/vm/Locks.park0(J)V(Native Method)
    at jrockit/vm/Locks.park(Locks.java:2230)[optimized]
    at jrockit/proxy/sun/misc/Unsafe.park(Unsafe.java:616)[inlined]
    at java/util/concurrent/locks/LockSupport.parkNanos(LockSupport.java:196)[inlined]
    at java/util/concurrent/locks/AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2116)[optimized]
    at com/hazelcast/util/ResponseQueueFactory$LockBasedResponseQueue.poll(ResponseQueueFactory.java:63)[optimized]
    at com/hazelcast/impl/BaseManager$ResponseQueueCall.waitAndGetResult(BaseManager.java:545)[inlined]
    at com/hazelcast/impl/BaseManager$ResponseQueueCall.getRedoAwareResult(BaseManager.java:574)[optimized]
    at com/hazelcast/impl/BaseManager$ResponseQueueCall.getResult(BaseManager.java:569)[inlined]
    at com/hazelcast/impl/BaseManager$RequestBasedCall.getResultAsObject(BaseManager.java:416)[inlined]
    at com/hazelcast/impl/BaseManager$ResponseQueueCall.getResultAsObject(BaseManager.java:505)[inlined]
    at com/hazelcast/impl/BaseManager$RequestBasedCall.getResultAsObject(BaseManager.java:412)[inlined]
    at com/hazelcast/impl/BaseManager$ResponseQueueCall.getResultAsObject(BaseManager.java:505)[inlined]
    at com/hazelcast/impl/ConcurrentMapManager$MLock.lock(ConcurrentMapManager.java:489)[inlined]
    at com/hazelcast/impl/ConcurrentMapManager$MLock.lock(ConcurrentMapManager.java:472)[optimized]
    at com/hazelcast/impl/ConcurrentMapManager.lock(ConcurrentMapManager.java:403)
    at com/hazelcast/impl/MProxyImpl$MProxyReal.tryLock(MProxyImpl.java:698)
    at sun/reflect/GeneratedMethodAccessor1739.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;(Unknown Source)
    at sun/reflect/DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)[optimized]
    at java/lang/reflect/Method.invoke(Method.java:597)[inlined]
    at com/hazelcast/impl/MProxyImpl$DynamicInvoker.invoke(MProxyImpl.java:66)[optimized]
    at $Proxy16.tryLock(Ljava/lang/Object;JLjava/util/concurrent/TimeUnit;)Z(Unknown Source)
    at com/hazelcast/impl/MProxyImpl.tryLock(MProxyImpl.java:397)
    at com/hazelcast/hibernate/access/ReadWriteAccessDelegate.lockItem(ReadWriteAccessDelegate.java:107)
    at com/hazelcast/hibernate/entity/AbstractEntityRegionAccessStrategy.lockItem(AbstractEntityRegionAccessStrategy.java:66)
    at org/hibernate/action/EntityUpdateAction.execute(EntityUpdateAction.java:107)
    at org/hibernate/engine/ActionQueue.execute(ActionQueue.java:268)
    at org/hibernate/engine/ActionQueue.executeActions(ActionQueue.java:260)
    at org/hibernate/engine/ActionQueue.executeActions(ActionQueue.java:180)
    at org/hibernate/event/def/AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:321)[inlined]
    at org/hibernate/event/def/DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:51)[optimized]
    at org/hibernate/impl/SessionImpl.flush(SessionImpl.java:1206)[inlined]
    at org/hibernate/impl/SessionImpl.managedFlush(SessionImpl.java:375)[optimized]
    at org/hibernate/transaction/JDBCTransaction.commit(JDBCTransaction.java:137)[optimized]
    at org/springframework/orm/hibernate3/HibernateTransactionManager.doCommit(HibernateTransactionManager.java:606)[optimized]
    at org/springframework/transaction/support/AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:709)[optimized]
    at org/springframework/transaction/support/AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:678)[optimized]
    at org/springframework/transaction/interceptor/TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:321)[inlined]
    at org/springframework/transaction/interceptor/TransactionInterceptor.invoke(TransactionInterceptor.java:116)[optimized]
    at org/springframework/aop/framework/ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:171)[optimized]
    at org/springframework/aop/framework/JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)[optimized]
    at $Proxy28.saveSessionId(Ljava/lang/String;Lcom/fx/objects/UserObject;)V(Unknown Source)
    at com/fx/web/api/ApiController.logout(ApiController.java:213)
    at sun/reflect/GeneratedMethodAccessor2481.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;(Unknown Source)
    at sun/reflect/DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)[optimized]
    at java/lang/reflect/Method.invoke(Method.java:597)[optimized]
    at org/springframework/web/bind/annotation/support/HandlerMethodInvoker.doInvokeMethod(HandlerMethodInvoker.java:413)[inlined]
    at org/springframework/web/bind/annotation/support/HandlerMethodInvoker.invokeHandlerMethod(HandlerMethodInvoker.java:134)[inlined]
    at org/springframework/web/servlet/mvc/annotation/AnnotationMethodHandlerAdapter.invokeHandlerMethod(AnnotationMethodHandlerAdapter.java:310)[inlined]
    at org/springframework/web/servlet/mvc/annotation/AnnotationMethodHandlerAdapter.handle(AnnotationMethodHandlerAdapter.java:297)[optimized]
    at org/springframework/web/servlet/DispatcherServlet.doDispatch(DispatcherServlet.java:875)[optimized]
    at org/springframework/web/servlet/DispatcherServlet.doService(DispatcherServlet.java:809)[inlined]
    at org/springframework/web/servlet/FrameworkServlet.processRequest(FrameworkServlet.java:571)[inlined]
    at org/springframework/web/servlet/FrameworkServlet.doGet(FrameworkServlet.java:501)[optimized]
    at javax/servlet/http/HttpServlet.service(HttpServlet.java:621)[optimized]
    at javax/servlet/http/HttpServlet.service(HttpServlet.java:728)[optimized]
    at org/apache/catalina/core/ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)[inlined]
    at org/apache/catalina/core/ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)[optimized]
    at org/tuckey/web/filters/urlrewrite/UrlRewriteFilter.doFilter(UrlRewriteFilter.java:350)[optimized]
    at org/apache/catalina/core/ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)[inlined]
    at org/apache/catalina/core/ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)[optimized]
    at org/springframework/orm/hibernate3/support/OpenSessionInViewFilter.doFilterInternal(OpenSessionInViewFilter.java:198)[optimized]
    at org/springframework/web/filter/OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)[optimized]
    at org/apache/catalina/core/ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)[inlined]
    at org/apache/catalina/core/ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)[optimized]
    at com/fx/filters/HttpFilter.doFilter(HttpFilter.java:34)[optimized]
    at org/apache/catalina/core/ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)[inlined]
    at org/apache/catalina/core/ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)[optimized]
    at com/fx/filters/MessageFilter.doFilter(MessageFilter.java:28)[optimized]
    at org/apache/catalina/core/ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)[inlined]
    at org/apache/catalina/core/ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)[optimized]
    at org/springframework/web/filter/CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:96)[optimized]
    at org/springframework/web/filter/OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)[optimized]
    at org/apache/catalina/core/ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)[inlined]
    at org/apache/catalina/core/ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)[optimized]
    at org/apache/catalina/core/StandardWrapperValve.invoke(StandardWrapperValve.java:222)[optimized]
    at org/apache/catalina/core/StandardContextValve.invoke(StandardContextValve.java:123)[optimized]
    at org/apache/catalina/authenticator/AuthenticatorBase.invoke(AuthenticatorBase.java:472)[optimized]
    at org/apache/catalina/core/StandardHostValve.invoke(StandardHostValve.java:171)[optimized]
    at org/apache/catalina/valves/ErrorReportValve.invoke(ErrorReportValve.java:99)[optimized]
    at org/apache/catalina/core/StandardEngineValve.invoke(StandardEngineValve.java:118)[optimized]
    at org/apache/catalina/connector/CoyoteAdapter.service(CoyoteAdapter.java:407)[optimized]
    at org/apache/coyote/ajp/AjpAprProcessor.process(AjpAprProcessor.java:197)[optimized]
    at org/apache/coyote/AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)[optimized]
    at org/apache/tomcat/util/net/AprEndpoint$SocketProcessor.run(AprEndpoint.java:1822)[optimized]
    ^-- Holding lock: org/apache/tomcat/util/net/SocketWrapper@0x000000019AE240D0[biased lock]
    at java/util/concurrent/ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)[inlined]
    at java/util/concurrent/ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)[optimized]
    at java/lang/Thread.run(Thread.java:662)[optimized]
    at jrockit/vm/RNI.c2java(JJJJJ)V(Native Method)
    -- end of trace

```

**Comment by enesakar** [comment]
Closing the issue. Can you check if issue exists in 3.x versions?
