### ISSUE TITLE
ClientSplitBrainTest.testClientListeners_InSplitBrain

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#4290]
```
java.lang.AssertionError: id 0 expected:<3> but was:<0>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at com.hazelcast.client.ClientSplitBrainTest$1.run(ClientSplitBrainTest.java:93)
    at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:239)
    at com.hazelcast.client.ClientSplitBrainTest.checkEventsEventually(ClientSplitBrainTest.java:90)
    at com.hazelcast.client.ClientSplitBrainTest.testClientListeners_InSplitBrain(ClientSplitBrainTest.java:84)
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-OpenJDK6/com.hazelcast$hazelcast-client/83/testReport/junit/com.hazelcast.client/ClientSplitBrainTest/testClientListeners_InSplitBrain/

**Comment by bilalyasar** [comment]
again failed: https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast-client/465/testReport/junit/com.hazelcast.client/ClientSplitBrainTest/testClientListeners_InSplitBrain/

**Comment by bilalyasar** [comment]
failed,  same exception
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/470/com.hazelcast$hazelcast-client/testReport/com.hazelcast.client/ClientSplitBrainTest/testClientListeners_InSplitBrain/

**Comment by bilalyasar** [comment]
```
Running com.hazelcast.client.ClientSplitBrainTest
Build timed out (after 360 minutes). Marking the build as aborted.
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/472/console

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: listener id 2
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.client.ClientSplitBrainTest$1.run(ClientSplitBrainTest.java:101)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:753)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:767)
	at com.hazelcast.client.ClientSplitBrainTest.checkEventsEventually(ClientSplitBrainTest.java:98)
	at com.hazelcast.client.ClientSplitBrainTest.testClientListeners_InSplitBrain(ClientSplitBrainTest.java:85)

```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast-client/653/testReport/junit/com.hazelcast.client/ClientSplitBrainTest/testClientListeners_InSplitBrain/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast-client/677/testReport/junit/com.hazelcast.client/ClientSplitBrainTest/testClientListeners_InSplitBrain/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast-client-new/679/testReport/junit/com.hazelcast.client/ClientSplitBrainTest/testClientListeners_InSplitBrain/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: listener id 0
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.client.ClientSplitBrainTest$1.run(ClientSplitBrainTest.java:102)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:737)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:751)
	at com.hazelcast.client.ClientSplitBrainTest.checkEventsEventually(ClientSplitBrainTest.java:99)
	at com.hazelcast.client.ClientSplitBrainTest.testClientListeners_InSplitBrain(ClientSplitBrainTest.java:85)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-nightly/com.hazelcast$hazelcast-client-new/685/testReport/junit/com.hazelcast.client/ClientSplitBrainTest/testClientListeners_InSplitBrain/

**Comment by sancar** [comment]
Fixed via #7162

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: listener id 2
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.client.ClientSplitBrainTest$1.run(ClientSplitBrainTest.java:102)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:857)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:871)
	at com.hazelcast.client.ClientSplitBrainTest.checkEventsEventually(ClientSplitBrainTest.java:99)
	at com.hazelcast.client.ClientSplitBrainTest.testClientListeners_InSplitBrain(ClientSplitBrainTest.java:85)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast-client/946/testReport/junit/com.hazelcast.client/ClientSplitBrainTest/testClientListeners_InSplitBrain/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: listener id 2
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.client.ClientSplitBrainTest$1.run(ClientSplitBrainTest.java:102)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:924)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:941)
	at com.hazelcast.client.ClientSplitBrainTest.checkEventsEventually(ClientSplitBrainTest.java:99)
	at com.hazelcast.client.ClientSplitBrainTest.testClientListeners_InSplitBrain(ClientSplitBrainTest.java:85)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast-client/1199/testReport/junit/com.hazelcast.client/ClientSplitBrainTest/testClientListeners_InSplitBrain/

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast-client/1203/testReport/junit/com.hazelcast.client/ClientSplitBrainTest/testClientListeners_InSplitBrain/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: listener id 2
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.client.ClientSplitBrainTest$1.run(ClientSplitBrainTest.java:102)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:967)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:984)
	at com.hazelcast.client.ClientSplitBrainTest.checkEventsEventually(ClientSplitBrainTest.java:99)
	at com.hazelcast.client.ClientSplitBrainTest.testClientListeners_InSplitBrain(ClientSplitBrainTest.java:85)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast-client/1209/testReport/junit/com.hazelcast.client/ClientSplitBrainTest/testClientListeners_InSplitBrain/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: listener id 2
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.client.ClientSplitBrainTest$1.run(ClientSplitBrainTest.java:102)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:967)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:984)
	at com.hazelcast.client.ClientSplitBrainTest.checkEventsEventually(ClientSplitBrainTest.java:99)
	at com.hazelcast.client.ClientSplitBrainTest.testClientListeners_InSplitBrain(ClientSplitBrainTest.java:85)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/1216/com.hazelcast$hazelcast-client/testReport/com.hazelcast.client/ClientSplitBrainTest/testClientListeners_InSplitBrain/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.client.ClientSplitBrainTest.testClientListeners_InSplitBrain(ClientSplitBrainTest.java:93)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast-client/1313/testReport/junit/com.hazelcast.client/ClientSplitBrainTest/testClientListeners_InSplitBrain/

**Comment by hasancelik** [comment]
```
com.hazelcast.core.HazelcastInstanceNotActiveException: Hazelcast instance is not active!
	at com.hazelcast.instance.HazelcastInstanceProxy.getOriginal(HazelcastInstanceProxy.java:303)
	at com.hazelcast.instance.HazelcastInstanceProxy.getCluster(HazelcastInstanceProxy.java:211)
	at com.hazelcast.test.HazelcastTestSupport.getClusterSize(HazelcastTestSupport.java:940)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSize(HazelcastTestSupport.java:932)
	at com.hazelcast.client.ClientSplitBrainTest.testClientListeners_InSplitBrain(ClientSplitBrainTest.java:98)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast-client/1510/testReport/junit/com.hazelcast.client/ClientSplitBrainTest/testClientListeners_InSplitBrain/

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast-client/1513/testReport/junit/com.hazelcast.client/ClientSplitBrainTest/testClientListeners_InSplitBrain/

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast-client/1514/testReport/junit/com.hazelcast.client/ClientSplitBrainTest/testClientListeners_InSplitBrain/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: CountDownLatch failed to complete within 120 seconds, count left: 1
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:1016)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:1009)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:1001)
	at com.hazelcast.client.ClientSplitBrainTest.testClientListeners_InSplitBrain(ClientSplitBrainTest.java:97)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast-client/1545/testReport/junit/com.hazelcast.client/ClientSplitBrainTest/testClientListeners_InSplitBrain/

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/1546/com.hazelcast$hazelcast-client/testReport/com.hazelcast.client/ClientSplitBrainTest/testClientListeners_InSplitBrain/

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/1547/com.hazelcast$hazelcast-client/testReport/com.hazelcast.client/ClientSplitBrainTest/testClientListeners_InSplitBrain/

**Comment by sancar** [comment]
fixed by https://github.com/hazelcast/hazelcast/pull/11883 and https://github.com/hazelcast/hazelcast/pull/11852
