### ISSUE TITLE
[TEST-FAILURE] ListTest.testMigrationSerializationNotFails_whenTransactionsAreUsed

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#4302]
```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:638)
	at java.util.ArrayList.get(ArrayList.java:414)
	at com.hazelcast.collection.list.ListContainer.get(ListContainer.java:63)
	at com.hazelcast.collection.list.ListGetOperation.run(ListGetOperation.java:44)
	at com.hazelcast.spi.impl.BasicOperationService$OperationHandler.handle(BasicOperationService.java:698)
	at com.hazelcast.spi.impl.BasicOperationService$OperationHandler.access$400(BasicOperationService.java:674)
	at com.hazelcast.spi.impl.BasicOperationService$BasicDispatcherImpl.dispatch(BasicOperationService.java:536)
	at com.hazelcast.spi.impl.BasicOperationScheduler$OperationThread.process(BasicOperationScheduler.java:439)
	at com.hazelcast.spi.impl.BasicOperationScheduler$OperationThread.doRun(BasicOperationScheduler.java:433)
	at com.hazelcast.spi.impl.BasicOperationScheduler$OperationThread.run(BasicOperationScheduler.java:408)
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-OracleJDK8/com.hazelcast$hazelcast/84/testReport/junit/com.hazelcast.collection/ListTest/testMigrationSerializationNotFails_whenTransactionsAreUsed/

**Comment by gurbuzali** [comment]
please see https://github.com/hazelcast/hazelcast/pull/4313#issuecomment-71830247
