### ISSUE TITLE
NullPointerException during map.put() and map.destroy() are called concurrently

### ISSUE THREAD

**Issue by mdogan** [hazelcast/hazelcast#4331]
When map.destroy() is called, it clears map data out of partition threads and it makes partition data inconsistent for operations running concurrently in partition threads.

```
java.lang.NullPointerException
        at com.hazelcast.map.impl.record.Records.buildRecordInfo(Records.java:22)
        at com.hazelcast.map.impl.operation.BasePutOperation.getBackupOperation(BasePutOperation.java:89)
        at com.hazelcast.spi.impl.BasicOperationService$OperationBackupHandler.initBackupOperation(BasicOperationService.java:973)
        at com.hazelcast.spi.impl.BasicOperationService$OperationBackupHandler.newBackup(BasicOperationService.java:961)
        at com.hazelcast.spi.impl.BasicOperationService$OperationBackupHandler.makeBackups(BasicOperationService.java:948)
        at com.hazelcast.spi.impl.BasicOperationService$OperationBackupHandler.backup(BasicOperationService.java:915)
        at com.hazelcast.spi.impl.BasicOperationService$OperationHandler.handleResponse(BasicOperationService.java:769)
        at com.hazelcast.spi.impl.BasicOperationService$OperationHandler.handle(BasicOperationService.java:734)
        at com.hazelcast.spi.impl.BasicOperationService$OperationHandler.access$500(BasicOperationService.java:709)
        at com.hazelcast.spi.impl.BasicOperationService.runOperationOnCallingThread(BasicOperationService.java:253)
        at com.hazelcast.spi.impl.BasicInvocation.doInvokeLocal(BasicInvocation.java:280)
        at com.hazelcast.spi.impl.BasicInvocation.doInvoke(BasicInvocation.java:262)
        at com.hazelcast.spi.impl.BasicInvocation.invoke(BasicInvocation.java:229)
        at com.hazelcast.spi.impl.BasicInvocationBuilder.invoke(BasicInvocationBuilder.java:45)
        at com.hazelcast.client.impl.client.PartitionClientRequest.process(PartitionClientRequest.java:60)
        at com.hazelcast.client.impl.ClientEngineImpl$ClientPacketProcessor.processRequest(ClientEngineImpl.java:434)
        at com.hazelcast.client.impl.ClientEngineImpl$ClientPacketProcessor.run(ClientEngineImpl.java:353)
        at com.hazelcast.spi.impl.BasicOperationService$BasicDispatcherImpl.dispatch(BasicOperationService.java:569)
```

**Comment by toktarev** [comment]
https://github.com/hazelcast/hazelcast/pull/5449/commits
