### ISSUE TITLE
Client shuts down when IP changes upon reconnects

### ISSUE THREAD

**Issue by mzapletal** [hazelcast/hazelcast#4349]
We have been experiencing that HZ clients shutdown in case of an IP change of one or more of the configured node (DNS) addresses. 

Steps that led to the problem:

1. Cluster with two nodes
2. Clients are configured to access cluster nodes via FQDN
3. Shutdown of both cluster nodes
4. (clients try to reconnect)
5. Cluster nodes come up again
6. During startup, cluster nodes get new (private) IP addresses, which are registered at the DNS service
7. It seems that there is a small time window where the FQDN has no IP assigned/configured at the DNS service, because accessing ``InetAddress address = inetSocketAddress.getAddress();`` https://github.com/hazelcast/hazelcast/blob/3.3.4/hazelcast/src/main/java/com/hazelcast/nio/Address.java#L198 evaluates to null. Since this exception is nowhere handled, ``ClusterListenerThread.run`` shuts down the client https://github.com/hazelcast/hazelcast/blob/3.3.4/hazelcast-client/src/main/java/com/hazelcast/client/spi/impl/ClusterListenerThread.java#L83-L94. 

We are experiencing this issue with 3.3.1, but as far as I can see the code in the master (i.e., 3.4) is the same. 

I would suggest to handle the exception directly here https://github.com/hazelcast/hazelcast/blob/3.4/hazelcast-client/src/main/java/com/hazelcast/client/spi/impl/ClusterListenerThread.java#L258-L260, but this may also have an impact on initial connection attempts (where it may be desired to quit immediately).

*full stacktrace*
``` java
java.lang.IllegalArgumentException: Can't resolve address: hz0.example.com:5701
	at com.hazelcast.nio.Address.resolve(Address.java:200) ~[hazelcast-3.3.1.jar:3.3.1]
	at com.hazelcast.nio.Address.<init>(Address.java:69) ~[hazelcast-3.3.1.jar:3.3.1]
	at com.hazelcast.client.spi.impl.ClusterListenerThread.connectToOne(ClusterListenerThread.java:246) ~[hazelcast-client-3.3.1.jar:3.3.1]
	at com.hazelcast.client.spi.impl.ClusterListenerThread.run(ClusterListenerThread.java:79) ~[hazelcast-client-3.3.1.jar:3.3.1]
java.lang.IllegalArgumentException: Can't resolve address: hz0.example.com:5701
	at com.hazelcast.nio.Address.resolve(Address.java:200)
	at com.hazelcast.nio.Address.<init>(Address.java:69)
	at com.hazelcast.client.spi.impl.ClusterListenerThread.connectToOne(ClusterListenerThread.java:246)
	at com.hazelcast.client.spi.impl.ClusterListenerThread.run(ClusterListenerThread.java:79)
```

**Comment by mdogan** [comment]
Problem is, when address can't be resolved client terminates immediately. As @mzapletal reported, `java.lang.IllegalArgumentException: Can't resolve address: ...` is not handled correctly.

```java
ClientConfig config = new ClientConfig();
config.getNetworkConfig().addAddress("issue4349-test.hazelcast.com");
HazelcastInstance client = HazelcastClient.newHazelcastClient(config);
```

```
10:16:53,067  INFO [LifecycleService] - HazelcastClient[hz.client_0_dev][3.5-SNAPSHOT] is STARTING
10:16:53,390  INFO [LifecycleService] - HazelcastClient[hz.client_0_dev][3.5-SNAPSHOT] is STARTED
10:16:53,573 FATAL [ClusterListenerThread] - Error while connecting to cluster!
java.lang.IllegalArgumentException: Can't resolve address: issue4349-test.hazelcast.com:5701
	at com.hazelcast.nio.Address.resolve(Address.java:200)
	at com.hazelcast.nio.Address.<init>(Address.java:69)
	at com.hazelcast.client.spi.impl.ClusterListenerThread.connectToOne(ClusterListenerThread.java:258)
	at com.hazelcast.client.spi.impl.ClusterListenerThread.run(ClusterListenerThread.java:86)
10:16:53,574  INFO [LifecycleService] - HazelcastClient[hz.client_0_dev][3.5-SNAPSHOT] is SHUTTING_DOWN
10:16:53,575  INFO [LifecycleService] - HazelcastClient[hz.client_0_dev][3.5-SNAPSHOT] is SHUTDOWN
Exception in thread "main" java.lang.IllegalArgumentException: Can't resolve address: issue4349-test.hazelcast.com:5701
	at com.hazelcast.nio.Address.resolve(Address.java:200)
	at com.hazelcast.nio.Address.<init>(Address.java:69)
	at com.hazelcast.client.spi.impl.ClusterListenerThread.connectToOne(ClusterListenerThread.java:258)
	at com.hazelcast.client.spi.impl.ClusterListenerThread.run(ClusterListenerThread.java:86)
```

**Comment by bwzhang2011** [comment]
@sancar, as hz3.3.4+ improvement the client connection,  our production of hazelcatNotActiveException decreased more. but once some configuration changed or network switched, it also induced such exception thrown and impact the cluster of hazelcast. so I hope hz team could pay more attention to the stability of hazelcast just like the hz client component, at lease keep the pace for reconnecting but not for hazelcast not activeException which I could not resolve.

**Comment by bwzhang2011** [comment]
now I updated to hz3.3.5 but it still suffered the connecton lost and hazelcastNotActiveException. @mdogan, would you mind paying more attention to that, as I proposed and suggested, if such exception thrown, the whole cluster was impacted by that.
