### ISSUE TITLE
RepartitioningStressTest intermittent failures

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#4356]
```
java.lang.AssertionError: GetThread-0 failed with an exception:expected:<3661> but was:<null>
    at org.junit.Assert.fail(Assert.java:88)
    at com.hazelcast.spi.RepartitioningStressTest$TestThread.assertDiedPeacefully(RepartitioningStressTest.java:200)
    at com.hazelcast.spi.RepartitioningStressTest.callWithoutBackups(RepartitioningStressTest.java:170)
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-nightly/com.hazelcast$hazelcast/334/testReport/junit/com.hazelcast.spi/RepartitioningStressTest/callWithoutBackups/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/434/testReport/junit/com.hazelcast.spi/RepartitioningStressTest/callWithoutBackups/

**Comment by jerrinot** [comment]
The last failure is from January. 
Moreover the test is `@Ignored` in a master branch.
