### ISSUE TITLE
[TEST-FAILURE] testLock_WhenDummyClientAndOwnerNodeDiesTogether

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#4368]
```
java.lang.IllegalStateException: Node failed to start!
	at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:125)
	at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:153)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:136)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:112)
	at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:87)
	at com.hazelcast.client.ClientRegressionTest.testLock_WhenClientAndOwnerNodeDiesTogether(ClientRegressionTest.java:610)
	at com.hazelcast.client.ClientRegressionTest.testLock_WhenDummyClientAndOwnerNodeDiesTogether(ClientRegressionTest.java:593)
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x/com.hazelcast$hazelcast-client/2459/testReport/junit/com.hazelcast.client/ClientRegressionTest/testLock_WhenDummyClientAndOwnerNodeDiesTogether/

**Comment by sancar** [comment]
fixed via #4534
