### ISSUE TITLE
HazelcastSerializationException when adding non-core Java classes to session with session replication enabled

### ISSUE THREAD

**Issue by ben-loy** [hazelcast/hazelcast#4385]
Description:
I'm using Hazelcast 3.4 for session replication with a application server in client mode connecting to a single server instance on localhost.  My web application added an object to the session object that isn't in the standard Java library and the client is receiving a HazelcastSerializationException from the server trying to deserialize it.  Adding the jars with the missing classes to the server does fix the issue though I was told that the server shouldn't be trying to deserialize client objects.

My configuration for the WebFilter is nonstandard because I'm using Spring to define the hazelcast cluster instead of using hazelcast.xml:

    <hz:client id="hazelcastSessionClient">
        <hz:group name="${hazelcast.group.name}" password="${hazelcast.group.password}"/>
        <hz:network>
            <hz:member>${hazelcast.member}</hz:member>
        </hz:network>
    </hz:client>

web.xml snippet:

    <filter>
        <filter-name>hazelcast-filter</filter-name>
        <filter-class>com.bloy.HazelcastSpringWebFilter</filter-class>
        <init-param>
            <param-name>map-name</param-name>
            <param-value>sessions</param-value>
        </init-param>
        <init-param>
            <param-name>use-client</param-name>
            <param-value>true</param-value>
        </init-param>
        <init-param>
            
            <param-name>config-location</param-name>
            <param-value>hazelcastSessionClient</param-value>
        </init-param>
        <init-param>
            <param-name>sticky-session</param-name>
            <param-value>false</param-value>
        </init-param>
        <init-param>
            <param-name>cookie-secure</param-name>
            <param-value>true</param-value>
        </init-param>
        <init-param>
            <param-name>cookie-http-only</param-name>
            <param-value>true</param-value>
        </init-param>
        <init-param>
            <param-name>debug</param-name>
            <param-value>true</param-value>
        </init-param>
    </filter>

Application server:
Hazelcast 3.4 (core, hibernate3, spring, wm, client)
Tomcat 7.0.57
Spring 3.2.6

Hazelcast server:
Hazelcast 3.4 (all)

Environment:
Java 1.7.0_71
Mac OS X 10.10.1

Exception as seen by the client:

...
Caused by: com.hazelcast.nio.serialization.HazelcastSerializationException: java.lang.ClassNotFoundException: org.springframework.security.web.csrf.DefaultCsrfToken
	at com.hazelcast.nio.serialization.DefaultSerializers$ObjectSerializer.read(DefaultSerializers.java:201)
	at com.hazelcast.nio.serialization.StreamSerializerAdapter.toObject(StreamSerializerAdapter.java:65)
	at com.hazelcast.nio.serialization.SerializationServiceImpl.toObject(SerializationServiceImpl.java:260)
	at com.hazelcast.spi.impl.NodeEngineImpl.toObject(NodeEngineImpl.java:186)
	at com.hazelcast.map.impl.AbstractMapServiceContextSupport.toObject(AbstractMapServiceContextSupport.java:42)
	at com.hazelcast.map.impl.DefaultMapServiceContext.toObject(DefaultMapServiceContext.java:28)
	at com.hazelcast.map.impl.operation.AbstractMultipleEntryOperation.toObject(AbstractMultipleEntryOperation.java:200)
	at com.hazelcast.map.impl.operation.PartitionWideEntryOperation.run(PartitionWideEntryOperation.java:67)
	at com.hazelcast.spi.impl.BasicOperationService$OperationHandler.handle(BasicOperationService.java:733)
	at com.hazelcast.spi.impl.BasicOperationService$OperationHandler.access$500(BasicOperationService.java:709)
	at com.hazelcast.spi.impl.BasicOperationService$BasicDispatcherImpl.dispatch(BasicOperationService.java:560)
	at com.hazelcast.spi.impl.BasicOperationScheduler$OperationThread.process(BasicOperationScheduler.java:466)
	at com.hazelcast.spi.impl.BasicOperationScheduler$OperationThread.doRun(BasicOperationScheduler.java:458)
	at com.hazelcast.spi.impl.BasicOperationScheduler$OperationThread.run(BasicOperationScheduler.java:432)
	at ------ End remote and begin local stack-trace ------.(Unknown Source)
	at com.hazelcast.client.spi.impl.ClientCallFuture.resolveResponse(ClientCallFuture.java:201)
	at com.hazelcast.client.spi.impl.ClientCallFuture.get(ClientCallFuture.java:142)
	at com.hazelcast.client.spi.impl.ClientCallFuture.get(ClientCallFuture.java:118)
	at com.hazelcast.client.spi.ClientProxy.invoke(ClientProxy.java:151)
	at com.hazelcast.client.proxy.ClientMapProxy.executeOnEntries(ClientMapProxy.java:890)
	at com.hazelcast.web.WebFilter.destroySession(WebFilter.java:388)
	at com.hazelcast.web.WebFilter$RequestWrapper.getSession(WebFilter.java:595)
	at com.hazelcast.web.WebFilter$RequestWrapper.getSession(WebFilter.java:588)
	at org.apache.jasper.runtime.PageContextImpl._initialize(PageContextImpl.java:147)
	at org.apache.jasper.runtime.PageContextImpl.initialize(PageContextImpl.java:126)
	at org.apache.jasper.runtime.JspFactoryImpl.internalGetPageContext(JspFactoryImpl.java:112)
	at org.apache.jasper.runtime.JspFactoryImpl.getPageContext(JspFactoryImpl.java:65)
	... 110 more
Caused by: java.lang.ClassNotFoundException: org.springframework.security.web.csrf.DefaultCsrfToken
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at com.hazelcast.nio.ClassLoaderUtil.tryLoadClass(ClassLoaderUtil.java:124)
	at com.hazelcast.nio.ClassLoaderUtil.loadClass(ClassLoaderUtil.java:113)
	at com.hazelcast.nio.IOUtil$1.resolveClass(IOUtil.java:113)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1612)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1517)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1771)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)
	at com.hazelcast.nio.serialization.DefaultSerializers$ObjectSerializer.read(DefaultSerializers.java:196)
	at com.hazelcast.nio.serialization.StreamSerializerAdapter.toObject(StreamSerializerAdapter.java:65)
	at com.hazelcast.nio.serialization.SerializationServiceImpl.toObject(SerializationServiceImpl.java:260)
	at com.hazelcast.spi.impl.NodeEngineImpl.toObject(NodeEngineImpl.java:186)
	at com.hazelcast.map.impl.AbstractMapServiceContextSupport.toObject(AbstractMapServiceContextSupport.java:42)
	at com.hazelcast.map.impl.DefaultMapServiceContext.toObject(DefaultMapServiceContext.java:28)
	at com.hazelcast.map.impl.operation.AbstractMultipleEntryOperation.toObject(AbstractMultipleEntryOperation.java:200)
	at com.hazelcast.map.impl.operation.PartitionWideEntryOperation.run(PartitionWideEntryOperation.java:67)
	at com.hazelcast.spi.impl.BasicOperationService$OperationHandler.handle(BasicOperationService.java:733)
	at com.hazelcast.spi.impl.BasicOperationService$OperationHandler.access$500(BasicOperationService.java:709)
	at com.hazelcast.spi.impl.BasicOperationService$BasicDispatcherImpl.dispatch(BasicOperationService.java:560)
	at com.hazelcast.spi.impl.BasicOperationScheduler$OperationThread.process(BasicOperationScheduler.java:466)
	at com.hazelcast.spi.impl.BasicOperationScheduler$OperationThread.doRun(BasicOperationScheduler.java:458)
	at com.hazelcast.spi.impl.BasicOperationScheduler$OperationThread.run(BasicOperationScheduler.java:432)

**Comment by mesutcelik** [comment]
@Azaere , 

Thanks for reporting. Session invalidation is done via Hazelcast Entry Processors and Entry Processors require all classes available on the classpath. That is a problem with Client/Server architecture on our Session Replication Module.

Your only option for now to include those classes on the Hazelcast Cluster classpath.

**Comment by bilalyasar** [comment]
with hazelcast-3.5 , this issue has been solved via https://github.com/hazelcast/hazelcast/pull/5374
