### ISSUE TITLE
[TEST-FAILURE] DistributedMapperMapReduceTest.testAsyncMapperReducerCollator

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#4390]
```
java.lang.Exception: test timed out after 30000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:156)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:811)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:969)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1281)
	at java.util.concurrent.Semaphore.acquire(Semaphore.java:286)
	at com.hazelcast.mapreduce.DistributedMapperMapReduceTest.testAsyncMapperReducerCollator(DistributedMapperMapReduceTest.java:244)
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-OpenJDK6/com.hazelcast$hazelcast/109/testReport/junit/com.hazelcast.mapreduce/DistributedMapperMapReduceTest/testAsyncMapperReducerCollator/

**Comment by mesutcelik** [comment]
no failure seen lately.

**Comment by hasancelik** [comment]
```
org.junit.runners.model.TestTimedOutException: test timed out after 30000 milliseconds
	at java.lang.Thread.sleep(Native Method)
	at com.hazelcast.test.mocknetwork.MockJoiner.doJoin(MockJoiner.java:75)
	at com.hazelcast.internal.cluster.impl.AbstractJoiner.join(AbstractJoiner.java:118)
	at com.hazelcast.instance.Node.join(Node.java:607)
	at com.hazelcast.instance.Node.start(Node.java:357)
	at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:133)
	at com.hazelcast.instance.DefaultHazelcastInstanceFactory.newHazelcastInstance(DefaultHazelcastInstanceFactory.java:38)
	at com.hazelcast.instance.HazelcastInstanceManager.constructHazelcastInstance(HazelcastInstanceManager.java:227)
	at com.hazelcast.instance.HazelcastInstanceManager.newHazelcastInstance(HazelcastInstanceManager.java:185)
	at com.hazelcast.test.TestHazelcastInstanceFactory.newHazelcastInstance(TestHazelcastInstanceFactory.java:116)
	at com.hazelcast.test.TestHazelcastInstanceFactory.newHazelcastInstance(TestHazelcastInstanceFactory.java:103)
	at com.hazelcast.mapreduce.DistributedMapperMapReduceTest.testMapperReducerCollator(DistributedMapperMapReduceTest.java:120)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/new-lab-fast-pr/2917/testReport/junit/com.hazelcast.mapreduce/DistributedMapperMapReduceTest/testMapperReducerCollator/

**Comment by hasancelik** [comment]
supressed by 470c0d7dd911b056f9d24beb8abce87085c6030c
