### ISSUE TITLE
Filter Based Web Session Replication :com.hazelcast.nio.serialization.HazelcastSerializationException: No DataSerializerFactory registered for namespace: -1000

### ISSUE THREAD

**Issue by zhangyibao** [hazelcast/hazelcast#4397]
Hazelcast 3.4
```
com.hazelcast.nio.serialization.HazelcastSerializationException: No DataSerializerFactory registered for namespace: -1000
	at com.hazelcast.nio.serialization.DataSerializer.read(DataSerializer.java:98)
	at com.hazelcast.nio.serialization.DataSerializer.read(DataSerializer.java:39)
	at com.hazelcast.nio.serialization.StreamSerializerAdapter.read(StreamSerializerAdapter.java:44)
	at com.hazelcast.nio.serialization.SerializationServiceImpl.readObject(SerializationServiceImpl.java:309)
	at com.hazelcast.nio.serialization.ByteArrayObjectDataInput.readObject(ByteArrayObjectDataInput.java:439)
	at com.hazelcast.map.impl.client.MapExecuteOnKeyRequest.read(MapExecuteOnKeyRequest.java:93)
	at com.hazelcast.client.impl.client.ClientRequest.readPortable(ClientRequest.java:116)
	at com.hazelcast.nio.serialization.PortableSerializer.read(PortableSerializer.java:88)
	at com.hazelcast.nio.serialization.PortableSerializer.read(PortableSerializer.java:30)
	at com.hazelcast.nio.serialization.StreamSerializerAdapter.toObject(StreamSerializerAdapter.java:65)
	at com.hazelcast.nio.serialization.SerializationServiceImpl.toObject(SerializationServiceImpl.java:260)
	at com.hazelcast.client.impl.ClientEngineImpl$ClientPacketProcessor.loadRequest(ClientEngineImpl.java:364)
	at com.hazelcast.client.impl.ClientEngineImpl$ClientPacketProcessor.run(ClientEngineImpl.java:340)
	at com.hazelcast.spi.impl.BasicOperationService$BasicDispatcherImpl.dispatch(BasicOperationService.java:569)
	at com.hazelcast.spi.impl.BasicOperationScheduler$OperationThread.process(BasicOperationScheduler.java:466)
	at com.hazelcast.spi.impl.BasicOperationScheduler$OperationThread.doRun(BasicOperationScheduler.java:458)
	at com.hazelcast.spi.impl.BasicOperationScheduler$OperationThread.run(BasicOperationScheduler.java:432)
	at ------ End remote and begin local stack-trace ------.(Unknown Source)
	at com.hazelcast.client.spi.impl.ClientCallFuture.resolveResponse(ClientCallFuture.java:201)
	at com.hazelcast.client.spi.impl.ClientCallFuture.get(ClientCallFuture.java:142)
	at com.hazelcast.client.spi.impl.ClientCallFuture.get(ClientCallFuture.java:118)
	at com.hazelcast.client.spi.ClientProxy.invoke(ClientProxy.java:127)
	at com.hazelcast.client.proxy.ClientMapProxy.executeOnKey(ClientMapProxy.java:857)
	at com.hazelcast.web.WebFilter.createNewSession(WebFilter.java:312)
	at com.hazelcast.web.WebFilter$RequestWrapper.getSession(WebFilter.java:614)
	at com.hazelcast.web.WebFilter$RequestWrapper.getSession(WebFilter.java:588)
	at org.apache.jasper.runtime.PageContextImpl._initialize(PageContextImpl.java:147)
	at org.apache.jasper.runtime.PageContextImpl.initialize(PageContextImpl.java:126)
	at org.apache.jasper.runtime.JspFactoryImpl.internalGetPageContext(JspFactoryImpl.java:112)
	at org.apache.jasper.runtime.JspFactoryImpl.getPageContext(JspFactoryImpl.java:65)
	at org.apache.jsp.WEB_002dINF.views.cepMain_jsp._jspService(cepMain_jsp.java:64)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:432)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:390)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:334)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.hazelcast.web.WebFilter.doFilter(WebFilter.java:463)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.logging.log4j.core.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:59)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:748)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:486)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:411)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:338)
	at com.hazelcast.web.WebFilter$RequestWrapper$1.forward(WebFilter.java:551)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at net.bull.javamelody.JspWrapper.invoke(JspWrapper.java:150)
	at net.bull.javamelody.JdbcWrapper$DelegatingInvocationHandler.invoke(JdbcWrapper.java:281)
	at com.sun.proxy.$Proxy24.forward(Unknown Source)
	at com.jfinal.render.JspRender.render(JspRender.java:56)
	at com.jfinal.core.ActionHandler.handle(ActionHandler.java:92)
	at com.jfinal.ext.handler.UrlSkipHandler.handle(UrlSkipHandler.java:45)
	at com.jfinal.ext.handler.UrlSkipHandler.handle(UrlSkipHandler.java:45)
	at com.jfinal.core.JFinalFilter.doFilter(JFinalFilter.java:72)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:202)
	at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:180)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.hazelcast.web.WebFilter.doFilter(WebFilter.java:463)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.logging.log4j.core.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:66)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1040)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:313)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
```
Please help me ,thks.

**Comment by noctarius** [comment]
Your serverside does not have the session replication jar in classpath, does it?

**Comment by zhangyibao** [comment]
These jars have been inclueded:
hazelcast-3.4.jar
hazelcast-client-3.4.jar
hazelcast-wm-3.4.jar

I looks this file: hazelcast-documentation-3.4.pdf

**Comment by zhangyibao** [comment]
<?xml version="1.0" encoding="UTF-8"?>


<hazelcast-client xsi:schemaLocation="http://www.hazelcast.com/schema/client-config hazelcast-client-config-3.3.xsd"
                  xmlns="http://www.hazelcast.com/schema/client-config"
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <group>
        <name>dev</name>
        <password>dev-pass</password>
    </group>
    <properties>
        <property name="hazelcast.client.connection.timeout">10000</property>
        <property name="hazelcast.client.retry.count">6</property>
    </properties>

    <network>
        <cluster-members>
            <address>10.1.252.167</address>
        </cluster-members>
        <smart-routing>true</smart-routing>
        <redo-operation>true</redo-operation>
        <connection-timeout>10000</connection-timeout>
        <connection-attempt-period>1000</connection-attempt-period>
         <connection-attempt-limit>10</connection-attempt-limit>
    </network>

    <executor-pool-size>100</executor-pool-size>

   

   

    <load-balancer type="round-robin"/>

    <near-cache name="asd">
        <max-size>2000000</max-size>
        <time-to-live-seconds>90</time-to-live-seconds>
        <max-idle-seconds>100</max-idle-seconds>
        <eviction-policy>LFU</eviction-policy>
        <invalidate-on-change>true</invalidate-on-change>
        <in-memory-format>OBJECT</in-memory-format>
    </near-cache>
    
</hazelcast-client>

**Comment by zhangyibao** [comment]
![image](https://cloud.githubusercontent.com/assets/10447211/5690927/88ec1632-98e6-11e4-9f35-5cccec2d39ca.png)

**Comment by bilalyasar** [comment]
@zhangyibao , i tried to reproduce your case but couldn't succeed. Can you give more detail for your case like your server-client side configurations or a sample project, scenario?

**Comment by zhangyibao** [comment]
@bilalyasar  ,I have not succeeded.

**Comment by mesutcelik** [comment]
closing because of inactivity. Can you please try with latest 3.6-EA and reopen this if you think the problem is still there.
