### ISSUE TITLE
[TEST-FAILURE] MapStoreTest.testMapInitialLoad

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#4401]
```
ava.lang.Exception: test timed out after 120000 milliseconds
	at java.lang.Object.wait(Native Method)
	at com.hazelcast.spi.impl.BasicInvocationFuture.pollResponse(BasicInvocationFuture.java:265)
	at com.hazelcast.spi.impl.BasicInvocationFuture.waitForResponse(BasicInvocationFuture.java:216)
	at com.hazelcast.spi.impl.BasicInvocationFuture.get(BasicInvocationFuture.java:193)
	at com.hazelcast.spi.impl.BasicInvocationFuture.get(BasicInvocationFuture.java:173)
	at com.hazelcast.spi.impl.BasicOperationService$InvokeOnPartitions.retryFailedPartitions(BasicOperationService.java:529)
	at com.hazelcast.spi.impl.BasicOperationService$InvokeOnPartitions.invoke(BasicOperationService.java:467)
	at com.hazelcast.spi.impl.BasicOperationService$InvokeOnPartitions.access$500(BasicOperationService.java:437)
	at com.hazelcast.spi.impl.BasicOperationService.invokeOnAllPartitions(BasicOperationService.java:311)
	at com.hazelcast.map.impl.proxy.MapProxySupport.size(MapProxySupport.java:633)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.size(MapProxyImpl.java:71)
	at com.hazelcast.map.mapstore.MapStoreTest.testMapInitialLoad(MapStoreTest.java:298)
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OracleJDK8/com.hazelcast$hazelcast/310/testReport/junit/com.hazelcast.map.mapstore/MapStoreTest/testMapInitialLoad/

**Comment by ahmetmircik** [comment]
Looks like needs some more time to complete https://github.com/hazelcast/hazelcast/commit/898bb117f200cc48a15bfc0d8b27418ebe2df752

**Comment by bilalyasar** [comment]
again failed:
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OracleJDK8/com.hazelcast$hazelcast/316/testReport/junit/com.hazelcast.map.mapstore/MapStoreTest/testMapInitialLoad/

**Comment by gurbuzali** [comment]
another failure 
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-pr-builder/com.hazelcast$hazelcast/11578/testReport/junit/com.hazelcast.map.mapstore/MapStoreTest/testMapInitialLoad/

**Comment by mesutcelik** [comment]
@ahmetmircik ,

Do you have any update on that one?

**Comment by ahmetmircik** [comment]
seems not failing any more, closing now.
