### ISSUE TITLE
ClassCastException when create HazelCastInstance in OSGI environment

### ISSUE THREAD

**Issue by buondoi** [hazelcast/hazelcast#4416]
Caused by: com.hazelcast.core.HazelcastException: java.lang.ClassCastException: Cannot cast com.hazelcast.instance.DefaultNodeExtension to com.hazelcast.instance.NodeExtension
	at com.hazelcast.util.ServiceLoader$1.next(ServiceLoader.java:99)
	at com.hazelcast.instance.NodeExtensionFactory.create(NodeExtensionFactory.java:35)
	at com.hazelcast.instance.Node.<init>(Node.java:154)
	at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:117)

**Comment by hasancelik** [comment]
Thanks for reporting your issue. Please share with us the following information, to help us resolve your issue quickly and efficiently.

1)Hazelcast version that you use (e.g. 3.4, also specify whether it is a minor release or the latest snapshot).
2)Cluster size, i.e. the number of Hazelcast cluster members.
3)Number of the clients.
4)Version of Java. It is also helpful to mention the JVM parameters.
5)Operating system. If it is Linux, kernel version is helpful.
6)Logs and stack traces, if available.
7)Detailed description of the steps to reproduce your issue.
8)Unit test with the hazelcast.xml file. If you could include a unit test which reproduces your issue, we would be grateful.
9)If available, integration module versions (e.g. Tomcat, Jetty, Spring, Hibernate). Also, include their detailed configuration information such as web.xml, Hibernate configuration and context.xml for Spring.

**Comment by buondoi** [comment]
Hi,

1/ We're using version 3.4 final release. 
2/ We're evaluating phase so just on 1 local machine. 
3/ Java 1.8.0_20
4/ OS: Window
5/ The log as in this issue, we just create new HazelcastInstance from another osgi bundle. I think thi my be an issue?
6/ We don't integrate with any other modules

**Comment by buondoi** [comment]
Hi, 

I just tried to turn on "hazelcast.osgi.start" and also got this error.

This is stacktrace

com.hazelcast.core.HazelcastException: java.lang.ClassCastException: Cannot cast com.hazelcast.instance.DefaultNodeExtension to com.hazelcast.instance.NodeExtension
	at com.hazelcast.util.ServiceLoader$1.next(ServiceLoader.java:99)
	at com.hazelcast.instance.NodeExtensionFactory.create(NodeExtensionFactory.java:35)
	at com.hazelcast.instance.Node.<init>(Node.java:154)
	at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:117)
	at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:153)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:136)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:112)
	at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:87)
	at com.hazelcast.osgi.Activator.start(Activator.java:49)

**Comment by pveentjer** [comment]
Can you create a unit test that reproduces the issue? OSGI is nasty complex stuff and it is a lot easier if you can provide us with a unit test that reproduces the problem.

**Comment by serkan-ozal** [comment]
Hi @buondoi 

Does this issue occurred when you run Hazelcast as standalone OSGI bundle with `hazelcast.osgi.start`?

I have tried to run the Hazelcast jar as OSGI bundle on Eclipse Equinox and it is installed, resolved and started without any problem. As far as I understand, the problem seems that not Hazelcast related.

**Comment by serkan-ozal** [comment]
I think it is not Hazelcast issue. I have tested both current master branch and 3.4 versions, both of them works. The issue is possibly related with your use case and environment.

**Comment by noctarius** [comment]
Do you maybe have the hazelcast jar as its own bundle and inside your deployed bundle?

**Comment by afaslan** [comment]
I had the same problem and I solved my envirement problem! 

My issue was:
===========
I was trying to run hazelcast under my web application running under tomcat. 
I realized that hazelcast-3.4.2.jar is in WEB-INF/lib and the same jar is also in tomcat/lib
**I deleted hazelcast-3.4.2.jar under tomcat/lib and the problem is solved! :)**

My Envirement:
================
hazelcast version=3.4.2

Windows SErver 2012 R2

Tomcat 7.0.42

java version "1.7.0_79"
Java(TM) SE Runtime Environment (build 1.7.0_79-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.79-b02, mixed mode)
