### ISSUE TITLE
[TEST-FAILURE] MembershipListenerTest.whenMemberAdded_thenMemberAddedEvent

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#4418]
```
java.lang.AssertionError: expected:<1> but was:<2>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:555)
	at org.junit.Assert.assertEquals(Assert.java:542)
	at com.hazelcast.client.MembershipListenerTest$1.run(MembershipListenerTest.java:65)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:251)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:267)
	at com.hazelcast.client.MembershipListenerTest.whenMemberAdded_thenMemberAddedEvent(MembershipListenerTest.java:62)
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-IbmJDK1.6/com.hazelcast$hazelcast-client/114/testReport/junit/com.hazelcast.client/MembershipListenerTest/whenMemberAdded_thenMemberAddedEvent/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.6/com.hazelcast$hazelcast-client/442/testReport/junit/com.hazelcast.client/MembershipListenerTest/whenMemberAdded_thenMemberAddedEvent/

**Comment by sancar** [comment]
Same failure here:
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.7/450/console
