### ISSUE TITLE
[TEST-FAILURE] ClientRegressionTest.testLock_WhenSmartClientAndOwnerNodeDiesTogether

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#4434]
```
java.lang.IllegalStateException: Node failed to start!
	at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:125)
	at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:153)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:136)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:112)
	at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:87)
	at com.hazelcast.client.ClientRegressionTest.testLock_WhenClientAndOwnerNodeDiesTogether(ClientRegressionTest.java:610)
	at com.hazelcast.client.ClientRegressionTest.testLock_WhenSmartClientAndOwnerNodeDiesTogether(ClientRegressionTest.java:598)
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.6/com.hazelcast$hazelcast-client/426/testReport/junit/com.hazelcast.client/ClientRegressionTest/testLock_WhenSmartClientAndOwnerNodeDiesTogether/

**Comment by sancar** [comment]
fixed via #4534
