### ISSUE TITLE
NullPointerException  thrown from  TextCommandServiceImpl, then rest request failed to get respone

### ISSUE THREAD

**Issue by jinhaotian** [hazelcast/hazelcast#4476]
Hazelcast Version:3.3.2
JDK:build 1.7.0_51-b13
OS:CentOS release 6.4 kernel/ 2.6.32-358.el6.x86_64

In our production system(running in vmware vm). we some time got deal unreponsive node(rest request). NullPointerException found in the log

Exception in thread "hz._hzInstance_1_prod.ascii.service.response" java.lang.NullPointerException
	at com.hazelcast.ascii.TextCommandServiceImpl$ResponseThreadRunnable.run(TextCommandServiceImpl.java:374)
	at java.lang.Thread.run(Thread.java:744)

this usually happened when there is a high IO on vm host.

I am trying to reproduce it on our test environment. no luck yet

**Comment by jinhaotian** [comment]
We I did the following load testing and reproduced the exception
1. send huge new connections(rest get) every seconds and disconnection them immediately.
2. make the disk io slow (blocking  all logging request for serveral seconds)

Then hz._hzInstance_1_load.ascii.service.response thread will quit because the above exception. the rest processor would stop working. 

also  some time the IO.thread-Acceptor will quit too. because the following error.

Exception in thread "hz._hzInstance_1_load.IO.thread-Acceptor" java.util.concurrent.RejectedExecutionException: Executor[hz:io] is overloaded!
        at com.hazelcast.util.executor.CachedExecutorServiceDelegate.execute(CachedExecutorServiceDelegate.java:104)
        at com.hazelcast.spi.impl.ExecutionServiceImpl.execute(ExecutionServiceImpl.java:205)
        at com.hazelcast.nio.NodeIOService.executeAsync(NodeIOService.java:221)
        at com.hazelcast.nio.tcp.SocketAcceptor.acceptSocket(SocketAcceptor.java:130)
        at com.hazelcast.nio.tcp.SocketAcceptor.run(SocketAcceptor.java:70)
        at java.lang.Thread.run(Thread.java:744)

**Comment by jinhaotian** [comment]
part of cause of the above issue is because we have some bad config/programming.(logging, extensive client reconnect, queue size is too small).

we gonna fix our config first.

**Comment by hasancelik** [comment]
Hi @jinhaotian ,

Thanks for reporting your issue. What is the last status of this issue? Do you still get this exception after change configuration?

**Comment by jinhaotian** [comment]
We have changed our config about 10 weeks now. 
this issue do not happen again. 

Thanks
