### ISSUE TITLE
Starting an embedded Tomcat instance with hazelcast-filter com.hazelcast.web.WebFilter

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#4483]
Error
```
com.hazelcast.core.HazelcastException: java.lang.ClassCastException: Cannot cast com.hazelcast.instance.DefaultNodeExtension to com.hazelcast.instance.NodeExtension
```

Full Log
```
Jan 26, 2015 1:58:03 PM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-bio-6555"]
Jan 26, 2015 1:58:03 PM org.apache.catalina.core.StandardService startInternal
INFO: Starting service Tomcat
Jan 26, 2015 1:58:03 PM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet Engine: Apache Tomcat/7.0.54
Jan 26, 2015 1:58:04 PM org.apache.catalina.startup.ContextConfig getDefaultWebXmlFragment
INFO: No global web.xml found
Jan 26, 2015 1:58:22 PM org.apache.catalina.core.StandardContext filterStart
SEVERE: Exception starting filter hazelcast-filter
com.hazelcast.core.HazelcastException: java.lang.ClassCastException: Cannot cast com.hazelcast.instance.DefaultNodeExtension to com.hazelcast.instance.NodeExtension
	at com.hazelcast.util.ServiceLoader$1.next(ServiceLoader.java:99)
	at com.hazelcast.instance.NodeExtensionFactory.create(NodeExtensionFactory.java:35)
	at com.hazelcast.instance.Node.<init>(Node.java:155)
	at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:117)
	at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:153)
	at com.hazelcast.instance.HazelcastInstanceFactory.getOrCreateHazelcastInstance(HazelcastInstanceFactory.java:99)
	at com.hazelcast.core.Hazelcast.getOrCreateHazelcastInstance(Hazelcast.java:116)
	at com.hazelcast.web.HazelcastInstanceLoader.createHazelcastInstance(HazelcastInstanceLoader.java:93)
	at com.hazelcast.web.HazelcastInstanceLoader.createInstance(HazelcastInstanceLoader.java:84)
	at com.hazelcast.web.WebFilter.getInstance(WebFilter.java:484)
	at com.hazelcast.web.WebFilter.initInstance(WebFilter.java:276)
	at com.hazelcast.web.WebFilter.init(WebFilter.java:173)
	at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:279)
	at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:260)
	at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:105)
	at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4809)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5485)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassCastException: Cannot cast com.hazelcast.instance.DefaultNodeExtension to com.hazelcast.instance.NodeExtension
	at java.lang.Class.cast(Class.java:3094)
	at com.hazelcast.util.ServiceLoader$1.next(ServiceLoader.java:97)
	... 23 more

Jan 26, 2015 1:58:22 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: Error filterStart
Jan 26, 2015 1:58:22 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: Context [/] startup failed due to previous errors
Jan 26, 2015 1:58:22 PM org.apache.catalina.loader.WebappClassLoader checkThreadLocalMapForLeaks
SEVERE: The web application [/] created a ThreadLocal with key of type [com.hazelcast.util.UuidUtil$1] (value [com.hazelcast.util.UuidUtil$1@fb7b093]) and a value of type [java.util.Random] (value [java.util.Random@64a98af4]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
Jan 26, 2015 1:58:22 PM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-bio-6555"]
```

**Comment by gurbuzali** [comment]
@Danny-Hazelcast did you tried this out of stabilizer ? 
can it be that the issue is related with stabilizer + tomcat-embedded ?

**Comment by Danny-Hazelcast** [comment]
so i removed the hazelcast jars from webapp/WEB-INF/lib
so then tomcat then used the hazelcast jars in the parent class loader,
and all was good

**Comment by serkan-ozal** [comment]
@Danny-Hazelcast good. so now where does Tomcat take Hazelcast jars from ?

**Comment by Danny-Hazelcast** [comment]
from the parent class loader,  which in this case happens to be "stabilizer",  It has the hz jars in its class path,  It is not creating hz instances directly is i disables this,  but It is still making use of hz logging,  and perhaps other static class,  which might cause the nodeContext to be loaded ?
