### ISSUE TITLE
[TEST-FAILURE] ClientInvocationTest.executionCallback_TooLongThrowableStackTrace

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#4494]
```
java.lang.AssertionError: Callback should be notified on time!
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.client.spi.impl.ClientInvocationTest.executionCallback_TooLongThrowableStackTrace(ClientInvocationTest.java:85)
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.6/com.hazelcast$hazelcast-client/435/testReport/junit/com.hazelcast.client.spi.impl/ClientInvocationTest/executionCallback_TooLongThrowableStackTrace/

**Comment by sancar** [comment]
Closed via #4551
