### ISSUE TITLE
[TEST-FAILURE] ClientMapReduceTest.testMapperReducerCollator

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#4496]
```
java.lang.IllegalStateException: Node failed to start!
	at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:125)
	at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:153)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:136)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:112)
	at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:58)
	at com.hazelcast.client.mapreduce.ClientMapReduceTest.testMapperReducerCollator(ClientMapReduceTest.java:287)
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast-client/449/testReport/junit/com.hazelcast.client.mapreduce/ClientMapReduceTest/testMapperReducerCollator/

**Comment by sancar** [comment]
It seems that this test failed because StressTestSupport threads is not closed because of another failure in AtomicLongStableReadStressTest. 
There is already opened issue for that. Closing this one. 

Related to  #4179
