### ISSUE TITLE
[TEST-FAILURE] ExecutorServiceTest.testManagedPostregisteredExecutionCallbackCompletableFuture

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#4507]
```
java.lang.AssertionError: CountDownLatch failed to complete within 120 seconds , count left: 1
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:194)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:187)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:179)
	at com.hazelcast.executor.ExecutorServiceTest.testManagedPostregisteredExecutionCallbackCompletableFuture(ExecutorServiceTest.java:1239)
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-OracleJDK1.7/com.hazelcast$hazelcast/10/testReport/junit/com.hazelcast.executor/ExecutorServiceTest/testManagedPostregisteredExecutionCallbackCompletableFuture/

**Comment by mesutcelik** [comment]
@gurbuzali 

I checked that one on the history of maintenance builds. no failure lately...

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance/com.hazelcast$hazelcast/727/testReport/com.hazelcast.executor/ExecutorServiceTest/testManagedPostregisteredExecutionCallbackCompletableFuture/history/
