### ISSUE TITLE
[TEST-FAILURE] MemoryLeakTest.testShutdownAllMemoryLeak

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#4508]
```
java.lang.AssertionError: UsedMemory now: 7 but expected max: 7
	at org.junit.Assert.fail(Assert.java:88)
	at com.hazelcast.cluster.MemoryLeakTest.waitForGC(MemoryLeakTest.java:72)
	at com.hazelcast.cluster.MemoryLeakTest.testShutdownAllMemoryLeak(MemoryLeakTest.java:53)
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/453/testReport/junit/com.hazelcast.cluster/MemoryLeakTest/testShutdownAllMemoryLeak/

**Comment by mesutcelik** [comment]
has anyone fixed that one? Last failure is 3 weeks old... @gurbuzali @eminn ?

**Comment by eminn** [comment]
test removed via aaebde6f1871b1a6857928e6a610e45a3fc3c9f1
