### ISSUE TITLE
Please do not shut down when incompatible joiner detected

### ISSUE THREAD

**Issue by romanr** [hazelcast/hazelcast#4514]
If node finds a node on network with incompatible joiner, it shuts down! This is way too drastic measure. 

```
[FATAL] [3.4] Node could not join cluster. A Configuration mismatch was detected: Incompatible joiners! expected: tcp-ip, foundaws Node is going to shutdown now!
[FATAL] [3.4] Node could not join cluster. A Configuration mismatch was detected: Incompatible joiners! expected: tcp-ip, foundaws Node is going to shutdown now!
[WARN] [3.4] Terminating forcefully...
[INFO] [3.4] Shutting down connection manager...
[INFO] [3.4] Connection [Address[x.x.x.5]:5701] lost. Reason: Socket explicitly closed
[INFO] [3.4] Shutting down node engine...
```

This can't be right. External factor such as something existing on a network should not affect application so that it shuts down.

And it is a potential security issue: since anyone can possibly shut down your application by starting another Hazelcast instance on same network with incompatible joiner!

**Comment by romanr** [comment]
Also it makes High Availability scenarios impossible. If you want to switch your cluster from one Joiner method to another, you can't! If you will try to switch to other joiner type one-by-one, they will all fail and shutdown because instances with other joiner configuration exist on the network. 
You will have to shut down ALL instances that you have. And then start them. Thus you will be making an interruption in service.

**Comment by gurbuzali** [comment]
Hi,
When Hazelcast detects a configuration mismatch, it sends an operation to that node to shutdown itself.
So basically below statement is not true, the newly started instance will get shutdown not the current cluster, when there is a configuration mismatch.
"since anyone can possibly shut down your application by starting another Hazelcast instance on same network with incompatible joiner!" 

Here I've tried to reproduce the issue that you've described with multicast and tcp-ip config.
But Hazelcast apparently does not consider this as a 'configuration mismatch' since both nodes start individually

```
        // Default Multi-cast
        HazelcastInstance instance1 = Hazelcast.newHazelcastInstance();

        Config config = new Config();
        JoinConfig join = config.getNetworkConfig().getJoin();
        join.getMulticastConfig().setEnabled(false);
        join.getTcpIpConfig().setEnabled(true);

        // Tcp-Ip enabled
        HazelcastInstance instance2 = Hazelcast.newHazelcastInstance(config);

        Set<HazelcastInstance> instances = Hazelcast.getAllHazelcastInstances();

        for (HazelcastInstance instance : instances) {
            System.err.println(instance.getName() + " - " + instance.getLifecycleService().isRunning());
        }
```

**Comment by gurbuzali** [comment]
did you able to reproduce the issue?

**Comment by gurbuzali** [comment]
closing, not reproducible

**Comment by manish-panwar** [comment]
I was able to reproduce this issue.

**Comment by manish-panwar** [comment]
But it shutdown the node itself, not the whole cluster.

**Comment by romanr** [comment]
Yes, thats' what I meant in my report.

**Comment by acvcu** [comment]
I was able to get around this issue by using a firewall (iptables) to block connections between nodes. This allows you to reconfigure one node and restart it with Hazelcast thinking the other node is down. Then you can reconfigure the second node and restart it. Once all is working then open up the firewall and restart both nodes again. This will somewhat allow for HA during a reconfiguration (although the hazelcast in-memory cached data will be cleared doing it this way).

**Comment by ramtech123** [comment]
If anyone is interested in this issue, please refer #13162. 
The workaround is to have a group name for the cluster, and append some info about what type of cluster it is, say `MyAppsGroup-tcp`, `MyAppsGroup-multicast` etc. This will ensure that latest node will start as a standalone node or join a live cluster with matching joiner.

**Comment by JuKu** [comment]
@romanr @gurbuzali  @ramtech123 I have also the same problem with hazelcast 3.11 .
#13162 

I get this exception:
```
java.lang.IllegalStateException: Node failed to start!
	at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:133)
	at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:202)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:181)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:131)
	at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:57)
	at com.jukusoft.mmo.gs.frontend.ServerMain.createHazelcastInstance(ServerMain.java:338)
	at com.jukusoft.mmo.gs.frontend.ServerMain.start(ServerMain.java:127)
	at com.jukusoft.mmo.gs.frontend.ServerMain.main(ServerMain.java:53)
```

This is the way i create the (standalone) hazelcast instance on the first server:
```java
protected static HazelcastInstance createHazelcastInstance () {
            //create an new hazelcast instance
            com.hazelcast.config.Config config = new com.hazelcast.config.Config();

            //disable hazelcast logging
            config.setProperty("hazelcast.logging.type", "none");

            CacheSimpleConfig cacheConfig = new CacheSimpleConfig();
            config.getCacheConfigs().put("session-cache", cacheConfig);

            JoinConfig joinConfig = config.getNetworkConfig().getJoin();

            if (Config.getBool(HAZELCAST_TAG, "joinConfig")) {//it's true
                //disable other join configs
                joinConfig.getMulticastConfig().setEnabled(false);

                Log.i(HAZELCAST_TAG, "join config enabled.");
                TcpIpConfig ipConfig = joinConfig.getTcpIpConfig();

                String members = Config.get(HAZELCAST_TAG, "members");
                String[] memberArray = members.split(",");//list with other nodes in cluster (they aren't up all!)
                Log.i(HAZELCAST_TAG, "tcp/ip cluster members: " + members);

                for (String member : memberArray) {
                    ipConfig.addMember(member);
                }

                ipConfig.setEnabled(true);
            }

            //https://docs.hazelcast.org/docs/management-center/3.9.4/manual/html/Deploying_and_Starting.html
            if (Config.getBool(HAZELCAST_MANCENTER_TAG, "enabled")) {//it's true
                //configure connection to hazelcast management center
                config.getManagementCenterConfig().setEnabled(true);
                config.getManagementCenterConfig().setUrl(Config.get(HAZELCAST_MANCENTER_TAG, "url"));
            }

            return Hazelcast.newHazelcastInstance(config);
    }
```

And this is the way i create the other instance (other server):
```java
public static HazelcastInstance createHazelcastInstance () {
            //create an new hazelcast instance
            com.hazelcast.config.Config config = new com.hazelcast.config.Config();

            //disable hazelcast logging
            config.setProperty("hazelcast.logging.type", "none");

            CacheSimpleConfig cacheConfig = new CacheSimpleConfig();
            config.getCacheConfigs().put("session-cache", cacheConfig);

            //https://docs.hazelcast.org/docs/management-center/3.9.4/manual/html/Deploying_and_Starting.html
            if (Config.getBool(HAZELCAST_MANCENTER_TAG, "enabled")) {//it's true
                //configure connection to hazelcast management center
                config.getManagementCenterConfig().setEnabled(true);
                config.getManagementCenterConfig().setUrl(Config.get(HAZELCAST_MANCENTER_TAG, "url"));
            }

            return Hazelcast.newHazelcastInstance(config);
    }
```

**Comment by JuKu** [comment]
Full log (i have activate the hazelcast logging):
```
Jan 25, 2019 12:31:12 AM com.hazelcast.instance.AddressPicker
INFORMATION: [LOCAL] [dev] [3.11] Interfaces is disabled, trying to pick one address from TCP-IP config addresses: [192.168.0.100, 192.168.0.102]
Jan 25, 2019 12:31:12 AM com.hazelcast.instance.AddressPicker
INFORMATION: [LOCAL] [dev] [3.11] Prefer IPv4 stack is true, prefer IPv6 addresses is false
Jan 25, 2019 12:31:13 AM com.hazelcast.instance.AddressPicker
INFORMATION: [LOCAL] [dev] [3.11] Picked [192.168.0.100]:5701, using socket ServerSocket[addr=/0:0:0:0:0:0:0:0,localport=5701], bind any local is true
Jan 25, 2019 12:31:13 AM com.hazelcast.system
INFORMATION: [192.168.0.100]:5701 [dev] [3.11] Hazelcast 3.11 (20181023 - 1500bbb) starting at [192.168.0.100]:5701
Jan 25, 2019 12:31:13 AM com.hazelcast.system
INFORMATION: [192.168.0.100]:5701 [dev] [3.11] Copyright (c) 2008-2018, Hazelcast, Inc. All Rights Reserved.
Jan 25, 2019 12:31:13 AM com.hazelcast.instance.Node
INFORMATION: [192.168.0.100]:5701 [dev] [3.11] A non-empty group password is configured for the Hazelcast member. Starting with Hazelcast version 3.8.2, members with the same group name, but with different group passwords (that do not use authentication) form a cluster. The group password configuration will be removed completely in a future release.
Jan 25, 2019 12:31:13 AM com.hazelcast.spi.impl.operationservice.impl.BackpressureRegulator
INFORMATION: [192.168.0.100]:5701 [dev] [3.11] Backpressure is disabled
Jan 25, 2019 12:31:13 AM com.hazelcast.instance.Node
INFORMATION: [192.168.0.100]:5701 [dev] [3.11] Creating TcpIpJoiner
Jan 25, 2019 12:31:14 AM com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl
INFORMATION: [192.168.0.100]:5701 [dev] [3.11] Starting 8 partition threads and 5 generic threads (1 dedicated for priority tasks)
Jan 25, 2019 12:31:14 AM com.hazelcast.internal.diagnostics.Diagnostics
INFORMATION: [192.168.0.100]:5701 [dev] [3.11] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
Jan 25, 2019 12:31:14 AM com.hazelcast.core.LifecycleService
INFORMATION: [192.168.0.100]:5701 [dev] [3.11] [192.168.0.100]:5701 is STARTING
Jan 25, 2019 12:31:14 AM com.hazelcast.nio.tcp.TcpIpConnector
INFORMATION: [192.168.0.100]:5701 [dev] [3.11] Connecting to /192.168.0.102:5701, timeout: 0, bind-any: true
Jan 25, 2019 12:31:14 AM com.hazelcast.nio.tcp.TcpIpConnector
INFORMATION: [192.168.0.100]:5701 [dev] [3.11] Connecting to /192.168.0.102:5703, timeout: 0, bind-any: true
Jan 25, 2019 12:31:14 AM com.hazelcast.nio.tcp.TcpIpConnector
INFORMATION: [192.168.0.100]:5701 [dev] [3.11] Connecting to /192.168.0.100:5702, timeout: 0, bind-any: true
Jan 25, 2019 12:31:14 AM com.hazelcast.nio.tcp.TcpIpConnector
INFORMATION: [192.168.0.100]:5701 [dev] [3.11] Connecting to /192.168.0.102:5702, timeout: 0, bind-any: true
Jan 25, 2019 12:31:14 AM com.hazelcast.nio.tcp.TcpIpConnector
INFORMATION: [192.168.0.100]:5701 [dev] [3.11] Connecting to /192.168.0.100:5703, timeout: 0, bind-any: true
Jan 25, 2019 12:31:14 AM com.hazelcast.nio.tcp.TcpIpConnection
INFORMATION: [192.168.0.100]:5701 [dev] [3.11] Initialized new cluster connection between /192.168.0.100:6291 and /192.168.0.102:5701
Jan 25, 2019 12:31:15 AM com.hazelcast.cluster
SCHWERWIEGEND: [192.168.0.100]:5701 [dev] [3.11] Node could not join cluster. A Configuration mismatch was detected: Incompatible joiners! expected: multicast, found: tcp-ip Node is going to shutdown now!
Jan 25, 2019 12:31:15 AM com.hazelcast.cluster
SCHWERWIEGEND: [192.168.0.100]:5701 [dev] [3.11] Node could not join cluster. A Configuration mismatch was detected: Incompatible joiners! expected: multicast, found: tcp-ip Node is going to shutdown now!
Jan 25, 2019 12:31:15 AM com.hazelcast.instance.Node
INFORMATION: [192.168.0.100]:5701 [dev] [3.11] Node is already shutting down... Waiting for shutdown process to complete...
Jan 25, 2019 12:31:15 AM com.hazelcast.instance.Node
WARNUNG: [192.168.0.100]:5701 [dev] [3.11] Terminating forcefully...
Jan 25, 2019 12:31:15 AM com.hazelcast.instance.Node
INFORMATION: [192.168.0.100]:5701 [dev] [3.11] Shutting down connection manager...
Jan 25, 2019 12:31:15 AM com.hazelcast.nio.tcp.TcpIpConnector
INFORMATION: [192.168.0.100]:5701 [dev] [3.11] Could not connect to: /192.168.0.102:5702. Reason: SocketException[Connection refused: connect to address /192.168.0.102:5702]
Jan 25, 2019 12:31:15 AM com.hazelcast.cluster.impl.TcpIpJoiner
INFORMATION: [192.168.0.100]:5701 [dev] [3.11] [192.168.0.102]:5702 is added to the blacklist.
Jan 25, 2019 12:31:15 AM com.hazelcast.nio.tcp.TcpIpConnector
INFORMATION: [192.168.0.100]:5701 [dev] [3.11] Could not connect to: /192.168.0.100:5702. Reason: SocketException[Connection refused: connect to address /192.168.0.100:5702]
Jan 25, 2019 12:31:15 AM com.hazelcast.nio.tcp.TcpIpConnector
INFORMATION: [192.168.0.100]:5701 [dev] [3.11] Could not connect to: /192.168.0.100:5703. Reason: SocketException[Connection refused: connect to address /192.168.0.100:5703]
Jan 25, 2019 12:31:15 AM com.hazelcast.cluster.impl.TcpIpJoiner
INFORMATION: [192.168.0.100]:5701 [dev] [3.11] [192.168.0.100]:5702 is added to the blacklist.
Jan 25, 2019 12:31:15 AM com.hazelcast.cluster.impl.TcpIpJoiner
INFORMATION: [192.168.0.100]:5701 [dev] [3.11] [192.168.0.100]:5703 is added to the blacklist.
Jan 25, 2019 12:31:15 AM com.hazelcast.nio.tcp.TcpIpConnector
INFORMATION: [192.168.0.100]:5701 [dev] [3.11] Could not connect to: /192.168.0.102:5703. Reason: SocketException[Connection refused: connect to address /192.168.0.102:5703]
Jan 25, 2019 12:31:15 AM com.hazelcast.cluster.impl.TcpIpJoiner
INFORMATION: [192.168.0.100]:5701 [dev] [3.11] [192.168.0.102]:5703 is added to the blacklist.
Jan 25, 2019 12:31:15 AM com.hazelcast.nio.tcp.TcpIpConnection
INFORMATION: [192.168.0.100]:5701 [dev] [3.11] Connection[id=1, /192.168.0.100:6291->/192.168.0.102:5701, endpoint=[192.168.0.102]:5701, alive=false, type=MEMBER] closed. Reason: TcpIpConnectionManager is stopping
Jan 25, 2019 12:31:15 AM com.hazelcast.instance.Node
INFORMATION: [192.168.0.100]:5701 [dev] [3.11] Shutting down node engine...
Jan 25, 2019 12:31:15 AM com.hazelcast.instance.Node
WARNUNG: [192.168.0.100]:5701 [dev] [3.11] Interrupted while waiting for shutdown!
Jan 25, 2019 12:31:15 AM com.hazelcast.instance.NodeExtension
INFORMATION: [192.168.0.100]:5701 [dev] [3.11] Destroying node NodeExtension.
Jan 25, 2019 12:31:15 AM com.hazelcast.instance.Node
INFORMATION: [192.168.0.100]:5701 [dev] [3.11] Hazelcast Shutdown is completed in 412 ms.
Jan 25, 2019 12:31:20 AM com.hazelcast.instance.Node
WARNUNG: [192.168.0.100]:5701 [dev] [3.11] ManagementCenterService could not be constructed!
com.hazelcast.spi.exception.RetryableHazelcastException: HazelcastInstance[[192.168.0.100]:5701] is not active!
	at com.hazelcast.spi.impl.NodeEngineImpl.getService(NodeEngineImpl.java:369)
	at com.hazelcast.spi.impl.eventservice.impl.EventServiceImpl.getSegment(EventServiceImpl.java:540)
	at com.hazelcast.spi.impl.eventservice.impl.EventServiceImpl.registerListenerInternal(EventServiceImpl.java:282)
	at com.hazelcast.spi.impl.eventservice.impl.EventServiceImpl.registerLocalListener(EventServiceImpl.java:242)
	at com.hazelcast.internal.cluster.impl.ClusterServiceImpl.addMembershipListener(ClusterServiceImpl.java:788)
	at com.hazelcast.internal.management.ManagementCenterService.<init>(ManagementCenterService.java:141)
	at com.hazelcast.instance.Node.start(Node.java:419)
	at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:131)
	at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:202)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:181)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:131)
	at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:57)
	at com.jukusoft.mmo.gs.frontend.ServerMain.createHazelcastInstance(ServerMain.java:338)
	at com.jukusoft.mmo.gs.frontend.ServerMain.start(ServerMain.java:127)
	at com.jukusoft.mmo.gs.frontend.ServerMain.main(ServerMain.java:53)

Jan 25, 2019 12:31:20 AM com.hazelcast.util.PhoneHome
WARNUNG: [192.168.0.100]:5701 [dev] [3.11] Could not schedule phone home task! Most probably Hazelcast failed to start.
Jan 25, 2019 12:31:20 AM com.hazelcast.instance.Node
INFORMATION: [192.168.0.100]:5701 [dev] [3.11] Node is already shutting down... Waiting for shutdown process to complete...
java.lang.IllegalStateException: Node failed to start!
	at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:133)
	at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:202)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:181)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:131)
	at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:57)
	at com.jukusoft.mmo.gs.frontend.ServerMain.createHazelcastInstance(ServerMain.java:338)
	at com.jukusoft.mmo.gs.frontend.ServerMain.start(ServerMain.java:127)
	at com.jukusoft.mmo.gs.frontend.ServerMain.main(ServerMain.java:53)
```
