### ISSUE TITLE
ExecutorServiceTest.testInvokeAllTimeoutCancelled

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#4528]
```
java.util.concurrent.CancellationException: null
    at com.hazelcast.executor.impl.CancellableDelegatingFuture.cancel(CancellableDelegatingFuture.java:78)
    at com.hazelcast.executor.impl.ExecutorServiceProxy.cancelAll(ExecutorServiceProxy.java:521)
    at com.hazelcast.executor.impl.ExecutorServiceProxy.invokeAll(ExecutorServiceProxy.java:479)
    at com.hazelcast.executor.ExecutorServiceTest.testInvokeAllTimeoutCancelled(ExecutorServiceTest.java:681)
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast$hazelcast/452/testReport/junit/com.hazelcast.executor/ExecutorServiceTest/testInvokeAllTimeoutCancelled/

**Comment by sancar** [comment]
Another failure here
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-pr-builder/com.hazelcast$hazelcast/11735/testReport/junit/com.hazelcast.executor/ExecutorServiceTest/testInvokeAllTimeoutCancelled/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x/com.hazelcast$hazelcast/2721/testReport/junit/com.hazelcast.executor/ExecutorServiceTest/testInvokeAllTimeoutCancelled/
```
java.util.concurrent.CancellationException: null
	at com.hazelcast.executor.impl.CancellableDelegatingFuture.cancel(CancellableDelegatingFuture.java:78)
	at com.hazelcast.executor.impl.ExecutorServiceProxy.cancelAll(ExecutorServiceProxy.java:521)
	at com.hazelcast.executor.impl.ExecutorServiceProxy.invokeAll(ExecutorServiceProxy.java:479)
	at com.hazelcast.executor.ExecutorServiceTest.testInvokeAllTimeoutCancelled(ExecutorServiceTest.java:682)
```

**Comment by hasancelik** [comment]
```
java.util.concurrent.CancellationException: null
	at com.hazelcast.executor.impl.DistributedExecutorService.cancel(DistributedExecutorService.java:125)
	at com.hazelcast.executor.impl.operations.CancellationOperation.run(CancellationOperation.java:52)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:181)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:122)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:102)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:111)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrow(InvocationFuture.java:74)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:174)
	at com.hazelcast.util.executor.DelegatingFuture.get(DelegatingFuture.java:73)
	at com.hazelcast.util.executor.DelegatingFuture.get(DelegatingFuture.java:58)
	at com.hazelcast.executor.ExecutorServiceTest.testInvokeAllTimeoutCancelled(ExecutorServiceTest.java:799)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-OracleJDK1.7/com.hazelcast$hazelcast/563/testReport/junit/com.hazelcast.executor/ExecutorServiceTest/testInvokeAllTimeoutCancelled/

**Comment by mdogan** [comment]
No failures since Aug.

**Comment by Donnerbart** [comment]
**com.hazelcast.executor.ExecutorServiceTest.testInvokeAllTimeoutCancelled**
```java
java.util.concurrent.CancellationException: null
	at com.hazelcast.executor.impl.DistributedExecutorService.cancel(DistributedExecutorService.java:125)
	at com.hazelcast.executor.impl.operations.CancellationOperation.run(CancellationOperation.java:50)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:194)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:120)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:100)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:127)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:79)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:147)
	at com.hazelcast.util.executor.DelegatingFuture.get(DelegatingFuture.java:83)
	at com.hazelcast.executor.ExecutorServiceTest.testInvokeAllTimeoutCancelled(ExecutorServiceTest.java:793)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/11794/testReport/junit/com.hazelcast.executor/ExecutorServiceTest/testInvokeAllTimeoutCancelled/
