### ISSUE TITLE
AbstractEntryProcessor does not implement default required Serialization methods

### ISSUE THREAD

**Issue by fridgebuzz** [hazelcast/hazelcast#4539]
Following all the examples for how to use AbstractEntryProcessor will result in an exception whenever more than one node is involved:
```
com.hazelcast.nio.serialization.HazelcastSerializationException: java.io.NotSerializableException: ca.thoughtwire.hazelcasttest.ExecuteOnEntriesTest
	at com.hazelcast.nio.serialization.SerializationServiceImpl.handleException(SerializationServiceImpl.java:298)
	at com.hazelcast.nio.serialization.SerializationServiceImpl.writeObject(SerializationServiceImpl.java:254)
	at com.hazelcast.nio.serialization.ByteArrayObjectDataOutput.writeObject(ByteArrayObjectDataOutput.java:262)
	at com.hazelcast.map.operation.PartitionWideEntryOperationFactory.writeData(PartitionWideEntryOperationFactory.java:48)
	at com.hazelcast.nio.serialization.DataSerializer.write(DataSerializer.java:129)
	at com.hazelcast.nio.serialization.DataSerializer.write(DataSerializer.java:36)
	at com.hazelcast.nio.serialization.StreamSerializerAdapter.write(StreamSerializerAdapter.java:36)
	at com.hazelcast.nio.serialization.SerializationServiceImpl.writeObject(SerializationServiceImpl.java:252)
	at com.hazelcast.nio.serialization.ByteArrayObjectDataOutput.writeObject(ByteArrayObjectDataOutput.java:262)
	at com.hazelcast.spi.impl.PartitionIteratingOperation.writeInternal(PartitionIteratingOperation.java:170)
	at com.hazelcast.spi.Operation.writeData(Operation.java:284)
	at com.hazelcast.nio.serialization.DataSerializer.write(DataSerializer.java:129)
	at com.hazelcast.nio.serialization.DataSerializer.write(DataSerializer.java:36)
	at com.hazelcast.nio.serialization.StreamSerializerAdapter.write(StreamSerializerAdapter.java:48)
	at com.hazelcast.nio.serialization.SerializationServiceImpl.toData(SerializationServiceImpl.java:176)
	at com.hazelcast.nio.serialization.SerializationServiceImpl.toData(SerializationServiceImpl.java:157)
	at com.hazelcast.spi.impl.NodeEngineImpl.toData(NodeEngineImpl.java:151)
	at com.hazelcast.spi.impl.BasicOperationService.send(BasicOperationService.java:650)
	at com.hazelcast.spi.impl.BasicOperationService.send(BasicOperationService.java:627)
	at com.hazelcast.spi.impl.BasicInvocation.doInvoke(BasicInvocation.java:355)
	at com.hazelcast.spi.impl.BasicInvocation.invoke(BasicInvocation.java:190)
	at com.hazelcast.spi.impl.BasicInvocationBuilder.invoke(BasicInvocationBuilder.java:48)
	at com.hazelcast.spi.impl.BasicOperationService.invokeOnPartitions(BasicOperationService.java:577)
	at com.hazelcast.spi.impl.BasicOperationService.invokeOnAllPartitions(BasicOperationService.java:549)
	at com.hazelcast.map.proxy.MapProxySupport.executeOnEntries(MapProxySupport.java:820)
	at com.hazelcast.map.proxy.MapProxyImpl.executeOnEntries(MapProxyImpl.java:39)
	at ca.thoughtwire.hazelcasttest.ExecuteOnEntriesTest.executeOnEntries(ExecuteOnEntriesTest.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:74)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:211)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
Caused by: java.io.NotSerializableException: ca.thoughtwire.grid.entry.ExecuteOnEntriesTest
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1183)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1547)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1508)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1431)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1177)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:347)
	at com.hazelcast.nio.serialization.DefaultSerializers$ObjectSerializer.write(DefaultSerializers.java:204)
	at com.hazelcast.nio.serialization.StreamSerializerAdapter.write(StreamSerializerAdapter.java:36)
	at com.hazelcast.nio.serialization.SerializationServiceImpl.writeObject(SerializationServiceImpl.java:252)
	... 52 more
```
To prevent it one must implement no-op methods:

```java
private void readObject( ObjectInputStream in) throws ClassNotFoundException, IOException {}
private void writeObject( ObjectOutputStream out) throws IOException {}
```
It would be more convenient if AbstractEntryProcessor implemented those no-op methods and extenders can override them if necessary.

Here's a test that proves the problem:

hazelcast1.xml
```xml
<?xml version="1.0" encoding="UTF-8"?>
<hazelcast xsi:schemaLocation="http://www.hazelcast.com/schema/config http://www.hazelcast.com/schema/config/hazelcast-config-3.2.xsd"
           xmlns="http://www.hazelcast.com/schema/config"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <group>
        <name>test</name>
        <password>password</password>
    </group>

    <network>
        <port auto-increment="true">6200</port>
        <join>
        	<multicast enabled="false"/>
	        <tcp-ip enabled="true">
	        	<member>localhost:6200</member>
	        	<member>localhost:6203</member>
            </tcp-ip>
         </join>
    </network>

    <map name="testMap">
        <backup-count>1</backup-count>
        <merge-policy>com.hazelcast.map.merge.PassThroughMergePolicy</merge-policy>
    </map>
</hazelcast>
```
hazelcast2.xml
```xml
<?xml version="1.0" encoding="UTF-8"?>
<hazelcast xsi:schemaLocation="http://www.hazelcast.com/schema/config http://www.hazelcast.com/schema/config/hazelcast-config-3.2.xsd"
           xmlns="http://www.hazelcast.com/schema/config"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <group>
        <name>test</name>
        <password>password</password>
    </group>

    <network>
        <port auto-increment="true">6203</port>
        <join>
        	<multicast enabled="false"/>
	        <tcp-ip enabled="true">
	        	<member>localhost:6200</member>
	        	<member>localhost:6203</member>
            </tcp-ip>
         </join>
    </network>

    <map name="testMap">
        <backup-count>1</backup-count>
        <merge-policy>com.hazelcast.map.merge.PassThroughMergePolicy</merge-policy>
    </map>
</hazelcast>
```
Test class:
```java
package ca.thoughtwire.hazelcasttest;

import com.hazelcast.config.ClasspathXmlConfig;
import com.hazelcast.config.Config;
import com.hazelcast.core.Hazelcast;
import com.hazelcast.core.HazelcastInstance;
import com.hazelcast.core.IMap;
import com.hazelcast.map.AbstractEntryProcessor;
import com.hazelcast.nio.ObjectDataInput;
import com.hazelcast.nio.ObjectDataOutput;
import com.hazelcast.nio.serialization.DataSerializable;
import org.junit.BeforeClass;
import org.junit.Test;

import java.io.IOException;
import java.util.Map;
import java.util.Random;

/**
 * @author vanessa.williams
 */
public class ExecuteOnEntriesTest {

    @BeforeClass
    public static void init()
    {
        Config standardConfig1, standardConfig2;
        standardConfig1 = new ClasspathXmlConfig("hazelcast1.xml");
        grid1 = Hazelcast.newHazelcastInstance(standardConfig1);

        standardConfig2 = new ClasspathXmlConfig("hazelcast2.xml");
        grid2 = Hazelcast.newHazelcastInstance(standardConfig2);

        testMap = grid1.getMap("testMap");
        Random random = new Random(System.currentTimeMillis());
        for (int i=0; i<2000; i++)
        {
            testMap.put(i, new GridEntry(random.nextInt(), random.nextInt(), random.nextInt()));
        }
    }

    @Test
    public void executeOnEntries()
    {
        testMap.executeOnEntries(new DeleteEntryProcessor<Integer, Integer>());
    }

    public class DeleteEntryProcessor<K, V> extends AbstractEntryProcessor<K, V> {

        @Override
        public Object process(Map.Entry<K, V> entry)
        {
            entry.setValue(null);
            return null;
        }
    }

    public static class GridEntry implements DataSerializable
    {
        private Integer arg1;
        private Integer arg2;
        private Integer arg3;

        public GridEntry() {}

        public GridEntry(Integer arg1, Integer arg2, Integer arg3)
        {
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
        }

        public Integer getArg1() { return arg1; }

        public void setArg1(Integer arg1) { this.arg1 = arg1; }

        public Integer getArg2() { return arg2; }

        public void setArg2(Integer arg2) { this.arg2 = arg2; }

        public Integer getArg3() { return arg3; }

        public void setArg3(Integer arg3) { this.arg3 = arg3; }

        public void writeData(ObjectDataOutput out) throws IOException {
            out.writeInt(arg1);
            out.writeInt(arg2);
            out.writeInt(arg3);
        }

        public void readData(ObjectDataInput in) throws IOException {
            arg1 = in.readInt();
            arg2 = in.readInt();
            arg3 = in.readInt();
        }
    }

    private static HazelcastInstance grid1, grid2;
    private static IMap<Integer, GridEntry> testMap;
}
```
It would be an improvement, because it took us some time to figure out what was causing the problem.

**Comment by gurbuzali** [comment]
As seen from the stack-trace the problem is not with the AbstractEntryProcessor but the test class itself
```
com.hazelcast.nio.serialization.HazelcastSerializationException: java.io.NotSerializableException: ca.thoughtwire.hazelcasttest.ExecuteOnEntriesTest
```
Since `DeleteEntryProcessor` is an inner class, test class should be `Serializable` too.
Or you can use static inner classes.

Please see
http://stackoverflow.com/questions/7144912/why-is-a-serializable-inner-class-not-serializable
