### ISSUE TITLE
[TEST-FAILURE] ClientQueueDisruptionTest.clientsConsume_withNodeShutdown

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#4549]
```
com.hazelcast.spi.exception.TargetDisconnectedException: null
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.get(ClientInvocationFuture.java:110)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.get(ClientInvocationFuture.java:91)
	at com.hazelcast.client.spi.ClientProxy.invokeInterruptibly(ClientProxy.java:141)
	at com.hazelcast.client.proxy.ClientQueueProxy.invokeInterruptibly(ClientQueueProxy.java:293)
	at com.hazelcast.client.proxy.ClientQueueProxy.poll(ClientQueueProxy.java:144)
	at com.hazelcast.client.proxy.ClientQueueProxy.poll(ClientQueueProxy.java:193)
	at com.hazelcast.client.queue.ClientQueueDisruptionTest.clientsConsume_withNodeShutdown(ClientQueueDisruptionTest.java:66)
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast-client/460/testReport/junit/com.hazelcast.client.queue/ClientQueueDisruptionTest/clientsConsume_withNodeShutdown/

**Comment by bilalyasar** [comment]
again failed: https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast-client/465/testReport/junit/com.hazelcast.client.queue/ClientQueueDisruptionTest/clientsConsume_withNodeShutdown/

**Comment by sancar** [comment]
new stack strace
```
expected:<5030> but was:<5031>

junit.framework.AssertionFailedError: expected:<5030> but was:<5031>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:86)
	at junit.framework.TestCase.assertEquals(TestCase.java:253)
	at com.hazelcast.client.queue.ClientQueueDisruptionTest.clientsConsume_withNodeShutdown(ClientQueueDisruptionTest.java:68)
```

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/480/com.hazelcast$hazelcast-client/testReport/com.hazelcast.client.queue/ClientQueueDisruptionTest/clientsConsume_withNodeShutdown/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast-client-new/585/testReport/junit/com.hazelcast.client.queue/ClientQueueDisruptionTest/clientsConsume_withNodeShutdown/

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/589/com.hazelcast$hazelcast-client-new/testReport/com.hazelcast.client.queue/ClientQueueDisruptionTest/clientsConsume_withNodeShutdown/

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/593/com.hazelcast$hazelcast-client-new/testReport/com.hazelcast.client.queue/ClientQueueDisruptionTest/clientsConsume_withNodeShutdown/

**Comment by hasancelik** [comment]
```
com.hazelcast.core.OperationTimeoutException: No response for 120000 ms. Aborting invocation! Invocation{serviceName='hz:impl:queueService', op=com.hazelcast.collection.impl.queue.operations.OfferOperation{serviceName='hz:impl:queueService', partitionId=257, replicaIndex=0, callId=2713, invocationTime=1449715731281 (Thu Dec 10 04:48:51 EET 2015), waitTimeout=0, callTimeout=60000}, partitionId=257, replicaIndex=0, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeout=60000, target=Address[127.0.0.1]:5703, backupsExpected=0, backupsCompleted=0, connection=Connection [/127.0.0.1:5701 -> /127.0.0.1:35594], endpoint=Address[127.0.0.1]:5703, alive=true, type=MEMBER} No response has been received!  backups-expected:0 backups-completed: 0
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.newOperationTimeoutException(Invocation.java:535)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.waitForResponse(InvocationFuture.java:275)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.get(InvocationFuture.java:222)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.get(InvocationFuture.java:202)
	at com.hazelcast.collection.impl.queue.QueueProxySupport.invokeAndGet(QueueProxySupport.java:177)
	at com.hazelcast.collection.impl.queue.QueueProxySupport.offerInternal(QueueProxySupport.java:94)
	at com.hazelcast.collection.impl.queue.QueueProxyImpl.offer(QueueProxyImpl.java:77)
	at com.hazelcast.collection.impl.queue.QueueProxyImpl.offer(QueueProxyImpl.java:62)
	at com.hazelcast.client.queue.ClientQueueDisruptionTest$1.run(ClientQueueDisruptionTest.java:73)
	at com.hazelcast.test.HazelcastTestSupport.assertExactlyOneSuccessfulRun(HazelcastTestSupport.java:901)
	at com.hazelcast.test.HazelcastTestSupport.assertExactlyOneSuccessfulRun(HazelcastTestSupport.java:893)
	at com.hazelcast.client.queue.ClientQueueDisruptionTest.clientsConsume_withNodeShutdown(ClientQueueDisruptionTest.java:70)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast-client/796/testReport/junit/com.hazelcast.client.queue/ClientQueueDisruptionTest/clientsConsume_withNodeShutdown/

**Comment by hasancelik** [comment]
```
com.hazelcast.core.OperationTimeoutException: No response for 120000 ms. Aborting invocation! Invocation{serviceName='hz:impl:queueService', op=com.hazelcast.collection.impl.queue.operations.OfferOperation{serviceName='hz:impl:queueService', partitionId=257, replicaIndex=0, callId=5853, invocationTime=1450149886298 (Tue Dec 15 05:24:46 EET 2015), waitTimeout=0, callTimeout=60000}, partitionId=257, replicaIndex=0, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeout=60000, target=Address[127.0.0.1]:5703, backupsExpected=0, backupsCompleted=0, connection=Connection [/127.0.0.1:54388 -> /127.0.0.1:5703], endpoint=Address[127.0.0.1]:5703, alive=true, type=MEMBER} No response has been received!  backups-expected:0 backups-completed: 0
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.newOperationTimeoutException(Invocation.java:535)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.waitForResponse(InvocationFuture.java:275)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.get(InvocationFuture.java:222)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.get(InvocationFuture.java:202)
	at com.hazelcast.collection.impl.queue.QueueProxySupport.invokeAndGet(QueueProxySupport.java:177)
	at com.hazelcast.collection.impl.queue.QueueProxySupport.offerInternal(QueueProxySupport.java:94)
	at com.hazelcast.collection.impl.queue.QueueProxyImpl.offer(QueueProxyImpl.java:77)
	at com.hazelcast.collection.impl.queue.QueueProxyImpl.offer(QueueProxyImpl.java:62)
	at com.hazelcast.client.queue.ClientQueueDisruptionTest$1.run(ClientQueueDisruptionTest.java:73)
	at com.hazelcast.test.HazelcastTestSupport.assertExactlyOneSuccessfulRun(HazelcastTestSupport.java:901)
	at com.hazelcast.test.HazelcastTestSupport.assertExactlyOneSuccessfulRun(HazelcastTestSupport.java:893)
	at com.hazelcast.client.queue.ClientQueueDisruptionTest.clientsConsume_withNodeShutdown(ClientQueueDisruptionTest.java:70)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast-client/801/testReport/junit/com.hazelcast.client.queue/ClientQueueDisruptionTest/clientsConsume_withNodeShutdown/
