### ISSUE TITLE
hazelcast-aws exceptions after signature changing

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#4571]
```
WARNING: [172.30.4.33]:5701 [dev] [3.5-SNAPSHOT] URI can't be null.
java.lang.IllegalArgumentException: URI can't be null.
	at sun.net.spi.DefaultProxySelector.select(DefaultProxySelector.java:141)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:926)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
```
this exception is thrower and aws has a problem currently.
after this merge https://github.com/hazelcast/hazelcast/pull/4103 , we have to change request headers..

**Comment by bilalyasar** [comment]
closed via #4572
