### ISSUE TITLE
Unnecessary de-serialization at server-side when using Cache.get()

### ISSUE THREAD

**Issue by alparslanavci** [hazelcast/hazelcast#4632]
It seems objects are unnecessarily de-serialized on server-side when Cache.get() is called.

```java
    @org.junit.Test
    public void testCacheGet_withCustomSerialization() {
        Hazelcast.newHazelcastInstance();

        ClientConfig config = new ClientConfig();
        SerializerConfig serializerConfig = new SerializerConfig()
                .setImplementation(new FooXmlSerializer())
                .setTypeClass(Foo.class);
        config.getSerializationConfig().addSerializerConfig(serializerConfig);
        HazelcastInstance hazelcastClient = HazelcastClient.newHazelcastClient(config);

        CachingProvider provider = HazelcastClientCachingProvider.createCachingProvider(hazelcastClient);
        CacheManager cacheManager = provider.getCacheManager();

        String cacheName = "test";
        Cache<Object, Foo> cache = cacheManager.createCache(cacheName, new CacheConfig());
        String key = "foo";
        Foo valueBefore = new Foo();
        cache.put(key, valueBefore);
        Foo valueAfter = cache.get(key);
        assertEquals(valueBefore, valueAfter);
    }

    private class Foo {
        private String foo;

        public String getFoo() {
            return foo;
        }

        public void setFoo(String foo) {
            this.foo = foo;
        }

        @Override
        public boolean equals(Object o) {
            if (this == o) return true;
            if (o == null || getClass() != o.getClass()) return false;

            Foo foo1 = (Foo) o;

            if (foo != null ? !foo.equals(foo1.foo) : foo1.foo != null) return false;

            return true;
        }

        @Override
        public int hashCode() {
            return foo != null ? foo.hashCode() : 0;
        }
    }

    public class FooXmlSerializer implements StreamSerializer<Foo> {

        @Override
        public int getTypeId() {
            return 10;
        }

        @Override
        public void write(ObjectDataOutput out, Foo object) throws IOException {
            out.writeUTF(object.getFoo());
        }

        @Override
        public Foo read(ObjectDataInput in) throws IOException {
            Foo foo = new Foo();
            foo.setFoo(in.readUTF());
            return foo;
        }

        @Override
        public void destroy() {
        }
    }
```

**Comment by pveentjer** [comment]
it isn't completely unwanted because in your case, the Foo instance, is potentially shared between multiple threads. That is why a defensive copy is made to prevent unexpected sharing of instances.

But.. one of the optimizations on my radar is the ability to say that an instance is immutable (e.g. annotation, well known types like String or using configuration). Once the system sees that a immutable instance is returned, it can just return that instance instead of making a defensive copy.

https://github.com/hazelcast/hazelcast/issues/1194

**Comment by pveentjer** [comment]
Perhaps I'm miss understanding you and you are saying that on the serverside unwanted deserialization is done... my badd...

**Comment by sancar** [comment]
We already discussed this with @alparslanavci . Clients should be able to send and receive data with custom serialization(or a portable that servers did not know). Think of nodes as central servers that lots of different applications(clients) are connected to. Servers should never try to deserialize the data that client sent, because servers will not have these classes.  

This is working for most of our data structures. We ( it was @eminn  if I dont remember wrong ) saw similar problem with replicated map, and recently @alparslanavci come accross same problem with our cache solution. 

Thinks like query entryprocessor is exception. User will not be able to use these in this kind of scenario. 

And this test will fail with something like "There is no suitable deserializer for id ..." because serializer is only registered in client side.

**Comment by alparslanavci** [comment]
Thanks for the detailed explanation @sancar. I've forgotten to add the exception that is get from the failed test.

```
Feb 18, 2015 9:45:43 AM com.hazelcast.cache.impl.operation.CacheGetOperation
SEVERE: [192.168.194.1]:5701 [dev] [3.5-SNAPSHOT] There is no suitable de-serializer for type 10
com.hazelcast.nio.serialization.HazelcastSerializationException: There is no suitable de-serializer for type 10
	at com.hazelcast.nio.serialization.SerializationServiceImpl.toObject(SerializationServiceImpl.java:257)
	at com.hazelcast.cache.impl.CacheRecordStore.dataToValue(CacheRecordStore.java:112)
	at com.hazelcast.cache.impl.CacheRecordStore.recordToValue(CacheRecordStore.java:124)
	at com.hazelcast.cache.impl.AbstractCacheRecordStore.get(AbstractCacheRecordStore.java:766)
	at com.hazelcast.cache.impl.operation.CacheGetOperation.run(CacheGetOperation.java:50)
	at com.hazelcast.spi.impl.BasicOperationService$OperationHandler.process(BasicOperationService.java:613)
	at com.hazelcast.spi.impl.BasicOperationService.runOperationOnCallingThread(BasicOperationService.java:255)
	at com.hazelcast.spi.impl.BasicInvocation.doInvokeLocal(BasicInvocation.java:276)
	at com.hazelcast.spi.impl.BasicInvocation.doInvoke(BasicInvocation.java:258)
	at com.hazelcast.spi.impl.BasicInvocation.invoke(BasicInvocation.java:225)
	at com.hazelcast.spi.impl.BasicInvocationBuilder.invoke(BasicInvocationBuilder.java:45)
	at com.hazelcast.client.impl.client.PartitionClientRequest.process(PartitionClientRequest.java:60)
	at com.hazelcast.client.impl.ClientEngineImpl$ClientPacketProcessor.processRequest(ClientEngineImpl.java:430)
	at com.hazelcast.client.impl.ClientEngineImpl$ClientPacketProcessor.run(ClientEngineImpl.java:349)
	at com.hazelcast.spi.impl.ClassicOperationScheduler$OperationThread.process(ClassicOperationScheduler.java:516)
	at com.hazelcast.spi.impl.ClassicOperationScheduler$OperationThread.doRun(ClassicOperationScheduler.java:494)
	at com.hazelcast.spi.impl.ClassicOperationScheduler$OperationThread.run(ClassicOperationScheduler.java:468)
```

**Comment by smillidge** [comment]
#4775 is related to this with the same stack trace so doesn't have to be client-server just classloader related.
