### ISSUE TITLE
HZ 3.3.5 SINGLE NODE - com.hazelcast.core.OperationTimeoutException: No response for 20000 ms. Aborting invocation

### ISSUE THREAD

**Issue by patriziomunzi** [hazelcast/hazelcast#4649]
I'm trying to move to HZ 3.3.5 but my first load test with a dummy test case failed on tons of: 

```
2015-02-19 16:00:33.834 ERROR [Test:100] com.hazelcast.core.OperationTimeoutException: No response for 20000 ms. Aborting invocation! BasicInvocationFuture{invocation=BasicInvocation{ serviceName='hz:impl:lockService', op=com.hazelcast.concurrent.lock.operations.LockOperation@6e7dcae3, partitionId=145, replicaIndex=0, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeout=10000, target=Address[172.18.1.11]:5701}, response=null, done=false} No response has been send  backups-expected:0 backups-completed: 0
com.hazelcast.core.OperationTimeoutException: No response for 20000 ms. Aborting invocation! BasicInvocationFuture{invocation=BasicInvocation{ serviceName='hz:impl:lockService', op=com.hazelcast.concurrent.lock.operations.LockOperation@6e7dcae3, partitionId=145, replicaIndex=0, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeout=10000, target=Address[172.18.1.11]:5701}, response=null, done=false} No response has been send  backups-expected:0 backups-completed: 0
        at com.hazelcast.spi.impl.BasicInvocationFuture.newOperationTimeoutException(BasicInvocationFuture.java:288)
        at com.hazelcast.spi.impl.BasicInvocationFuture.waitForResponse(BasicInvocationFuture.java:241)
        at com.hazelcast.spi.impl.BasicInvocationFuture.get(BasicInvocationFuture.java:190)
        at com.hazelcast.spi.impl.BasicInvocationFuture.get(BasicInvocationFuture.java:170)
        at com.hazelcast.concurrent.lock.LockProxySupport.tryLock(LockProxySupport.java:113)
        at com.hazelcast.map.proxy.MapProxyImpl.tryLock(MapProxyImpl.java:372)
        at com.hypertv.hazelcast.cache.HazelcastCacheWrapper.tryLock(HazelcastCacheWrapper.java:190)
        at com.hypertv.datagrid.test.cache.util.ValueObjectCacheUtil.tryLock(ValueObjectCacheUtil.java:117)
[...]
```

My code snippet is:

```
            ValueObjectKey vok = new ValueObjectKey(id, name);
            ValueObject valueObject = null;

            try
            {
                if (ValueObjectCacheUtil.tryLock(vok, 10000L, TimeUnit.MILLISECONDS))
                {
                    if ((valueObject = ValueObjectCacheUtil.getById(vok)) != null) 
                    {
                        _log.debug("OBJECT FOUND [Id: " + valueObject.getPrimaryKey() + ", Object: " + valueObject.toString() + "] increase score value");

                        valueObject.setValue(value);
                        valueObject.setScore(valueObject.getScore() + 1);
                    }
                    else 
                    {
                        _log.debug("OBJECT NOT FOUND, create it");

                        valueObject = new ValueObject(vok, value, "uuid", 0, 0, 1, 1, 0);
                    }

                    ValueObjectCacheUtil.put(valueObject);

                    _log.debug("PUT IN CACHE : [Id: " + valueObject.getPrimaryKey() + ", Object: " + valueObject.toString() + "]");
                }
            }
            catch (Exception e)
            {
                _log.error(e.toString());
                e.printStackTrace();
            }
            finally
            {
                if (ValueObjectCacheUtil.isLocked(vok))
                {
                    ValueObjectCacheUtil.unlock(vok);
                }
            }
```

Am I doing something wrong??

**Comment by pveentjer** [comment]
You are making use of locks, since it I see it in the error. But from your code it is unclear to see how you are using those locks. But the exception doesn't sound that nice to me. Can you post the content of ValueObjectCacheUtil

**Comment by patriziomunzi** [comment]
Unfortunately I'm using the lock in a very straightforward  way.
Taking out all the wrappers and IFs I simply do:
````
	private HazelcastInstance instance;
	private String cacheName;
	[...]
	public static boolean tryLock(ValueObjectKey key, long time, TimeUnit timeunit)
	throws InterruptedException {
		return instance.getMap(cacheName).tryLock(key, time, timeunit);
	}
```
Unit tests pass, the problem arises only when load testing.

**Comment by patriziomunzi** [comment]
Any feedback on this?

**Comment by iody** [comment]
im also having the same issue. any idea?

**Comment by iody** [comment]
found the fix. just increase teh timeout of your try lock

**Comment by mdogan** [comment]
There were significant changes and many fixes in invocation timeout mechanism and lock implementation in recent releases. Please try latest version and feel free to open a new issue if problem still exists.
