### ISSUE TITLE
NullPointerException on CachePutBackupOperation

### ISSUE THREAD

**Issue by eeimarn** [hazelcast/hazelcast#4660]
I am currently evaluating hazelcast and its jcache api, i am trying to get a feature that was previously working with infinispan working with hazelcast, i have used hazelcast a couple of years ago and was very happy with the results, but with this problem i am drawing a blank so any any advice would be very much appreciated. 

I am currently just testing 2 hazelcast instances running within a  .war file on 2 seperate jboss instances that are running locally on my machine and i am seeing the following strange stack trace under very light load 3 requests per second:

I have also turned off cache backup operations by setting the <backup-count> in hazelcast.xml to 0 but this exception still is thrown (strange).

```
14:02:05,450 SEVERE [com.hazelcast.cache.impl.operation.CachePutBackupOperation] (hz.JCacheSharedInstance.partition-operation.thread-6) [127.0.0.1]:7702 [exposure] [3.4.1] null: java.lang.NullPointerException
	at com.hazelcast.util.ConcurrentReferenceHashMap.put(ConcurrentReferenceHashMap.java:1278) [hazelcast-3.4.1.jar:3.4.1]
	at com.hazelcast.cache.impl.AbstractCacheRecordStore.putRecord(AbstractCacheRecordStore.java:730) [hazelcast-3.4.1.jar:3.4.1]
	at com.hazelcast.cache.impl.operation.CachePutBackupOperation.run(CachePutBackupOperation.java:57) [hazelcast-3.4.1.jar:3.4.1]
	at com.hazelcast.spi.impl.Backup.run(Backup.java:92) [hazelcast-3.4.1.jar:3.4.1]
	at com.hazelcast.spi.impl.BasicOperationService$OperationHandler.handle(BasicOperationService.java:733) [hazelcast-3.4.1.jar:3.4.1]
	at com.hazelcast.spi.impl.BasicOperationService$OperationHandler.access$500(BasicOperationService.java:709) [hazelcast-3.4.1.jar:3.4.1]
	at com.hazelcast.spi.impl.BasicOperationService$OperationPacketHandler.handle(BasicOperationService.java:683) [hazelcast-3.4.1.jar:3.4.1]
	at com.hazelcast.spi.impl.BasicOperationService$OperationPacketHandler.handle(BasicOperationService.java:627) [hazelcast-3.4.1.jar:3.4.1]
	at com.hazelcast.spi.impl.BasicOperationService$OperationPacketHandler.access$1500(BasicOperationService.java:614) [hazelcast-3.4.1.jar:3.4.1]
	at com.hazelcast.spi.impl.BasicOperationService$BasicDispatcherImpl.dispatch(BasicOperationService.java:566) [hazelcast-3.4.1.jar:3.4.1]
	at com.hazelcast.spi.impl.BasicOperationScheduler$OperationThread.process(BasicOperationScheduler.java:466) [hazelcast-3.4.1.jar:3.4.1]
	at com.hazelcast.spi.impl.BasicOperationScheduler$OperationThread.doRun(BasicOperationScheduler.java:458) [hazelcast-3.4.1.jar:3.4.1]
	at com.hazelcast.spi.impl.BasicOperationScheduler$OperationThread.run(BasicOperationScheduler.java:432) [hazelcast-3.4.1.jar:3.4.1]
```

Having looked at the online source code for the ConcurrentReferenceHashMap I can see that the nullpointer is caused by a value being null, . 

```
/**
     * Maps the specified key to the specified value in this table.
     * Neither the key nor the value can be null.
     * <p/>
     * <p> The value can be retrieved by calling the <tt>get</tt> method
     * with a key that is equal to the original key.
     *
     * @param key   key with which the specified value is to be associated
     * @param value value to be associated with the specified key
     * @return the previous value associated with <tt>key</tt>, or
     * <tt>null</tt> if there was no mapping for <tt>key</tt>
     * @throws NullPointerException if the specified key or value is null
     */
    public V put(K key, V value) {
        if (value == null)
            throw new NullPointerException();
        int hash = hashOf(key);
        return segmentFor(hash).put(key, hash, value, false);
    }
```

This problem does not occur very often maybe once in ever 20 requests and as far as i can see this problem occurs with various different put operations, so (although i probably will be wrong) I think that it may be a problem with the new hazelcast version.

**Comment by jerrinot** [comment]
this is a follow-up of https://groups.google.com/forum/#!topic/hazelcast/dv1i1_xZad0

**Comment by serkan-ozal** [comment]
fixed via https://github.com/hazelcast/hazelcast/commit/99f31ad15ab271a744bd4323cd2d1979c85e5e6e

**Comment by charlesmarvin** [comment]
This issue seems to happen for CachePutAllBackupOperation as well when running multiple nodes.
<pre>
ERROR [2015-06-27 13:17:25,908] com.hazelcast.cache.impl.operation.CachePutAllBackupOperation: [**.***.*.**]:5702 [dev] [3.5-EA] null
! java.lang.NullPointerException: null
! at com.hazelcast.util.ConcurrentReferenceHashMap.put(ConcurrentReferenceHashMap.java:1278) ~[hazelcast-3.5-EA.jar:3.5-EA]
! at com.hazelcast.cache.impl.AbstractCacheRecordStore.doPutRecord(AbstractCacheRecordStore.java:816) ~[hazelcast-3.5-EA.jar:3.5-EA]
! at com.hazelcast.cache.impl.AbstractCacheRecordStore.doPutRecord(AbstractCacheRecordStore.java:812) ~[hazelcast-3.5-EA.jar:3.5-EA]
! at com.hazelcast.cache.impl.AbstractCacheRecordStore.putRecord(AbstractCacheRecordStore.java:808) ~[hazelcast-3.5-EA.jar:3.5-EA]
! at com.hazelcast.cache.impl.operation.CachePutAllBackupOperation.run(CachePutAllBackupOperation.java:66) ~[hazelcast-3.5-EA.jar:3.5-EA]
! at com.hazelcast.spi.impl.operationservice.impl.operations.Backup.run(Backup.java:101) ~[hazelcast-3.5-EA.jar:3.5-EA]
! at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:137) [hazelcast-3.5-EA.jar:3.5-EA]
! at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:309) [hazelcast-3.5-EA.jar:3.5-EA]
! at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.processPacket(OperationThread.java:142) [hazelcast-3.5-EA.jar:3.5-EA]
! at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.process(OperationThread.java:115) [hazelcast-3.5-EA.jar:3.5-EA]
! at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.doRun(OperationThread.java:101) [hazelcast-3.5-EA.jar:3.5-EA]
! at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.run(OperationThread.java:76) [hazelcast-3.5-EA.jar:3.5-EA]
</pre>

**Comment by serkan-ozal** [comment]
Hi @charlesmarvin,

Thanks for reporting the issue. Since it's cause is different, I have created another issue https://github.com/hazelcast/hazelcast/issues/5618 and you can read the comment of the issue for the reason of exception.

Regards.
