### ISSUE TITLE
Strange mapName for MapStoreFactory.newMapStore()

### ISSUE THREAD

**Issue by bitec** [hazelcast/hazelcast#4667]
Hi.
I used the asterix configuraiton for maps and mapStore configuration using custom MapStoreFactory:
```xml
<hz:map name="query.archive.*"
                    eviction-percentage="25"
                    eviction-policy="LRU"
                    max-size="${judgements.hz.archive.max.size}"
                    max-size-policy="PER_NODE"
                    max-idle-seconds="${judgements.hz.archive.max.idle}"
                    in-memory-format="OBJECT"
                    read-backup-data="true"
                    backup-count="0">
                <hz:map-store enabled="true" factory-implementation="mapStoreProvider"
                              write-delay-seconds="0"/>
            </hz:map>
```
This worked ok for half a year.
Then I tried the more specific configuration for some maps and changed maps configuration to the following:

```xml
<hz:map name="query.archive.RU.WEB"
                   ...>
                <hz:map-store enabled="true" factory-implementation="mapStoreProvider"
                              write-delay-seconds="0"/>
            </hz:map>
            <hz:map name="query.archive.TR.WEB"
                    ...>
                <hz:map-store enabled="true" factory-implementation="mapStoreProvider"
                              write-delay-seconds="0"/>
            </hz:map>
            <hz:map name="query.archive.*.WEB"
                    ....>
                <hz:map-store enabled="true" factory-implementation="mapStoreProvider"
                              write-delay-seconds="0"/>
            </hz:map>

          <hz:map name="query.archive.*"
                    ....>
                <hz:map-store enabled="true" factory-implementation="mapStoreProvider"
                              write-delay-seconds="0"/>
            </hz:map>
```
And now I face the sporadic strange mapName parameter in my MapStoreFactory with asterix: **"query.archive.*"**

Code for MapStoreFactory is not interesting, it tries to create dynamic map store by the name. Name is usually **query.archive.[1].[2]** and 1, 2 are used to create map store. It works but twice the last weeks my mapStoreFactory failed as got the strange map name: "query.archive.*". Usually these sporadic problems are the sign of  concurrency race.

So, independent of my code and the way configuration with asterixes parsed - how can this be that Map StoreFactory gets the sample with asterixes instead of specific map name?

Btw, I use Hz 3.3.2

**Comment by ahmetmircik** [comment]
Hi,
Thanks for the report. 
Is it possible for you to test/verify it with `version 3.4.1` also?

**Comment by bitec** [comment]
Well, will do this in testing environment, if everything is ok, will move to prod

**Comment by bitec** [comment]
this is the same for 3.4.1

**Comment by bitec** [comment]
Any plans on this?

Seems "overloading" of maps now is not supported that is disappointing

**Comment by gurbuzali** [comment]
Hi,
Can you please give some detailed information about what you mean by 'overloading' ?
For the strange mapName issue, regardless of the configuration mapName should always be the name which you've passed to `HazelcastInstance.getMap(mapName)`

I've created a small test code which shows the stack-trace to prove that the string you've passed to `getMap` method travels to `newMapStore` method.

Can you please check and log the stack-trace in you factory class like below :
```
    if (mapName.contains("*")) {
            new Throwable("newMapStore").printStackTrace()
    }
```

**Comment by bitec** [comment]
```
java.lang.Throwable: newMapStore
        at ru.yandex.search.judgement.application.StorageProvider$MapStoreProvider.newMapStore(StorageProvider.java:122)
        at com.hazelcast.map.MapContainer.createMapStoreWrapper(MapContainer.java:149)
        at com.hazelcast.map.MapContainer.initMapStoreOperations(MapContainer.java:113)
        at com.hazelcast.map.MapContainer.<init>(MapContainer.java:84)
        at com.hazelcast.map.DefaultMapServiceContext$1.createNew(DefaultMapServiceContext.java:28)
        at com.hazelcast.map.DefaultMapServiceContext$1.createNew(DefaultMapServiceContext.java:26)
        at com.hazelcast.util.ConcurrencyUtil.getOrPutSynchronized(ConcurrencyUtil.java:40)
        at com.hazelcast.map.DefaultMapServiceContext.getMapContainer(DefaultMapServiceContext.java:64)
        at com.hazelcast.map.AbstractMapServiceContextSupport.interceptAfterRemove(AbstractMapServiceContextSupport.java:165)
        at com.hazelcast.map.DefaultMapServiceContext.interceptAfterRemove(DefaultMapServiceContext.java:21)
        at com.hazelcast.map.eviction.EvictionHelper.interceptAndInvalidate(EvictionHelper.java:154)
        at com.hazelcast.map.eviction.EvictionHelper.removeEvictableRecords(EvictionHelper.java:103)
        at com.hazelcast.map.AbstractEvictableRecordStore.removeEvictableRecords(AbstractEvictableRecordStore.java:209)
        at com.hazelcast.map.AbstractEvictableRecordStore.cleanUp(AbstractEvictableRecordStore.java:193)
        at com.hazelcast.map.AbstractEvictableRecordStore.evictEntries(AbstractEvictableRecordStore.java:162)
        at com.hazelcast.map.DefaultRecordStore.put(DefaultRecordStore.java:697)
        at com.hazelcast.map.operation.EntryOperation.put(EntryOperation.java:227)
        at com.hazelcast.map.operation.EntryOperation.entryAddedOrUpdated(EntryOperation.java:200)
        at com.hazelcast.map.operation.EntryOperation.run(EntryOperation.java:93)
        at com.hazelcast.spi.impl.BasicOperationService$OperationHandler.handle(BasicOperationService.java:699)
        at com.hazelcast.spi.impl.BasicOperationService$OperationHandler.access$400(BasicOperationService.java:675)
        at com.hazelcast.spi.impl.BasicOperationService$BasicDispatcherImpl.dispatch(BasicOperationService.java:537)
        at com.hazelcast.spi.impl.BasicOperationScheduler$OperationThread.process(BasicOperationScheduler.java:439)
        at com.hazelcast.spi.impl.BasicOperationScheduler$OperationThread.doRun(BasicOperationScheduler.java:433)
        at com.hazelcast.spi.impl.BasicOperationScheduler$OperationThread.run(BasicOperationScheduler.java:408)
```

**Comment by gurbuzali** [comment]
thank you for the report I've found the bug
