### ISSUE TITLE
QuerySlowTest.testRangeIndexSQLPerformance

### ISSUE THREAD

**Issue by mesutcelik** [hazelcast/hazelcast#4690]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/481/testReport/junit/com.hazelcast.map.query/QuerySlowTest/testRangeIndexSQLPerformance/

**Comment by mesutcelik** [comment]
no recent failure. closing.

**Comment by Donnerbart** [comment]
```
org.junit.runners.model.TestTimedOutException: test timed out after 60000 milliseconds
	at java.lang.Object.wait(Native Method)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.pollResponse(InvocationFuture.java:300)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.waitForResponse(InvocationFuture.java:245)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.get(InvocationFuture.java:222)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.get(InvocationFuture.java:202)
	at com.hazelcast.map.impl.proxy.MapProxySupport.invokeOperation(MapProxySupport.java:301)
	at com.hazelcast.map.impl.proxy.MapProxySupport.putInternal(MapProxySupport.java:271)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.put(MapProxyImpl.java:106)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.put(MapProxyImpl.java:96)
	at com.hazelcast.map.impl.query.QuerySlowTest.testRangeIndexSQLPerformance(QuerySlowTest.java:159)
```
https://hazelcast-l337.ci.cloudbees.com/view/Sonar/job/Hazelcast-3.x-sonar/lastSuccessfulBuild/com.hazelcast$hazelcast/testReport/com.hazelcast.map.impl.query/QuerySlowTest/testRangeIndexSQLPerformance/

The whole build took about an hour longer than usual. We also had a ton of PR builders running during the execution. Maybe we just overcommited CloudBees (again).

**Comment by gurbuzali** [comment]
link to the build misleading `lastSuccessfulBuild`, here is the correct one:
https://hazelcast-l337.ci.cloudbees.com/view/Sonar/job/Hazelcast-3.x-sonar/857/
It takes 7-8 seconds on my computer, if I busy up the cpus with spinning it takes 15 seconds.
The timeout is 60 seconds. I don't think it is failing because 60 seconds is not enough, I've increased it nevertheless just to be sure.  https://github.com/hazelcast/hazelcast/commit/c2d7536d1f61a04c526ea6d2cb4125cf10de7d6b

**Comment by hasancelik** [comment]
**maintenance**
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.map.impl.query.QuerySlowTest.testRangeIndexSQLPerformance(QuerySlowTest.java:157)
```
https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.maintenance-nightly/com.hazelcast$hazelcast/893/testReport/junit/com.hazelcast.map.impl.query/QuerySlowTest/testRangeIndexSQLPerformance/

**Comment by mdogan** [comment]
This test is renamed & refactored on master and I don't think we'll fix this in maintenance. Even we can remove it completely, since it's trying to measure performance of indexed queries against non-indexed, not a thing expected from a unit test.
