### ISSUE TITLE
Error while fetching cluster partition table!

### ISSUE THREAD

**Issue by cherednichenko** [hazelcast/hazelcast#4733]
Issue when I run StringICacheTest test on Hazelcast version 3.4. I have seen ONLY once because on the second run it wasn't happened.

Note: There wasn't any files created with Stabilizer with FAILURE words and that issue happened actually when socket was closed:

 ```
WARN  2015-03-04 08:29:37,467 [hz.client_0_workers.cluster-listener] com.hazelcast.client.connection.nio.ClientConnection: Connection [null] lost. Reason: Socket explicitly closed
INFO  2015-03-04 08:29:37,467 [hz.client_0_workers.cluster-listener] com.hazelcast.core.LifecycleService: HazelcastClient[hz.client_0_workers][3.4] is CLIENT_DISCONNECTED
WARN  2015-03-04 08:29:37,470 [InSelector] com.hazelcast.client.connection.nio.ClientConnection: Connection [/10.167.201.209:5701] lost. Reason: java.io.EOFException[Remote socket closed!]
WARN  2015-03-04 08:29:37,470 [InSelector] com.hazelcast.client.connection.nio.ClientReadHandler: InSelector Closing socket to endpoint Address[10.167.201.209]:5701, Cause:java.io.EOFException: Remote socket closed!
 ``` 
=========================================

```   
FATAL 2015-03-04 08:29:40,067 [hz.client_0_workers.cached-1] com.hazelcast.client.spi.ClientPartitionService: Error while fetching cluster partition table!
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:735)
	at sun.nio.ch.SocketAdaptor.connect(SocketAdaptor.java:117)
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl$ConnectionProcessor.call(ClientConnectionManagerImpl.java:383)
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl$ConnectionProcessor.call(ClientConnectionManagerImpl.java:350)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at com.hazelcast.util.executor.CompletableFutureTask.run(CompletableFutureTask.java:57)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)
INFO  2015-03-04 08:29:40,072 [Thread-0] com.hazelcast.stabilizer.worker.MemberWorker: Stopping threads...
   ```

**Comment by sancar** [comment]
Closing this one, because we dont have much information to investigate the issue further.
