### ISSUE TITLE
regrestion,  can't use *  in xml Jcache config names.  3.5-snapshot

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#4753]
we should add a junit test for this,  

```
Failure[
   message='Worked ran into an unhandled exception'
   type='Worker exception'
   agentAddress=10.0.0.134
   time=Fri Mar 06 09:50:30 UTC 2015
   workerAddress=10.0.0.134:5701
   workerId=worker-10.0.0.134-1-server
   test=TestCase{
          id=loadCache
        , class=com.LoadCache
        , cacheBaseName=j
    }
   cause=java.lang.IllegalArgumentException: CacheConfig is null! /hz/j0
	at com.hazelcast.cache.EnterpriseCacheService.createNewRecordStore(EnterpriseCacheService.java:82)
	at com.hazelcast.cache.impl.CachePartitionSegment$1.createNew(CachePartitionSegment.java:56)
	at com.hazelcast.cache.impl.CachePartitionSegment$1.createNew(CachePartitionSegment.java:53)
	at com.hazelcast.util.ConcurrencyUtil.getOrPutSynchronized(ConcurrencyUtil.java:40)
	at com.hazelcast.cache.impl.CachePartitionSegment.getOrCreateCache(CachePartitionSegment.java:76)
	at com.hazelcast.cache.impl.AbstractCacheService.getOrCreateCache(AbstractCacheService.java:103)
	at com.hazelcast.cache.hidensity.operation.AbstractHiDensityCacheOperation.beforeRun(AbstractHiDensityCacheOperation.java:76)
	at com.hazelcast.spi.impl.BasicOperationService$BasicOperationRunner.run(BasicOperationService.java:732)
	at com.hazelcast.spi.impl.BasicOperationService$BasicOperationRunner.run(BasicOperationService.java:896)
	at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.processPacket(OperationThread.java:126)
	at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.process(OperationThread.java:99)
	at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.doRun(OperationThread.java:85)
	at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.run(OperationThread.java:60)
	at ------ End remote and begin local stack-trace ------.(Unknown Source)
	at com.hazelcast.spi.impl.BasicInvocationFuture.resolveApplicationResponse(BasicInvocationFuture.java:391)
	at com.hazelcast.spi.impl.BasicInvocationFuture.resolveApplicationResponseOrThrowException(BasicInvocationFuture.java:324)
	at com.hazelcast.spi.impl.BasicInvocationFuture.get(BasicInvocationFuture.java:198)
	at com.hazelcast.spi.impl.BasicInvocationFuture.get(BasicInvocationFuture.java:177)
	at com.hazelcast.cache.impl.AbstractCacheProxy.put(AbstractCacheProxy.java:201)
	at com.hazelcast.cache.impl.CacheProxy.put(CacheProxy.java:70)
	at com.hazelcast.cache.impl.CacheProxy.put(CacheProxy.java:132)
	at com.LoadCache$Worker.updateDynamicCaches(LoadCache.java:113)
	at com.LoadCache$Worker.run(LoadCache.java:104)
	at java.lang.Thread.run(Thread.java:745)
	at com.hazelcast.stabilizer.test.utils.ThreadSpawner$DefaultThread.run(ThreadSpawner.java:89)

]
```

**Comment by Danny-Hazelcast** [comment]
@serkan-ozal,  hi  can you take a look
