### ISSUE TITLE
While executing unit tests, SlowOperationDetectorThread and CleanupThread may not be terminated before next test started

### ISSUE THREAD

**Issue by serkan-ozal** [hazelcast/hazelcast#4757]
In the ```shutdown``` methods, these threads are not waited to finish their works and so they may continue to running on next test(s)

As seen from the logs below, these threads (from previous tests) may work at next tests

````
"hz._hzInstance_29_dev.migration" 
	java.lang.Thread.State: TIMED_WAITING on lock=java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@bd5d765
		at sun.misc.Unsafe.park(Native Method)
		at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:196)
		at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2025)
		at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:424)
		at com.hazelcast.partition.impl.InternalPartitionServiceImpl$MigrationThread.doRun(InternalPartitionServiceImpl.java:1778)
		at com.hazelcast.partition.impl.InternalPartitionServiceImpl$MigrationThread.run(InternalPartitionServiceImpl.java:1760)

...

"hz._hzInstance_28_dev.CleanupThread" 
	java.lang.Thread.State: TIMED_WAITING
		at java.lang.Thread.sleep(Native Method)
		at com.hazelcast.spi.impl.BasicOperationService$CleanupThread.sleep(BasicOperationService.java:1114)
		at com.hazelcast.spi.impl.BasicOperationService$CleanupThread.run(BasicOperationService.java:1103)

"hz._hzInstance_28_dev.SlowOperationDetectorThread" 
	java.lang.Thread.State: TIMED_WAITING
		at java.lang.Thread.sleep(Native Method)
		at java.lang.Thread.sleep(Thread.java:302)
		at java.util.concurrent.TimeUnit.sleep(TimeUnit.java:328)
		at com.hazelcast.spi.impl.SlowOperationDetector$SlowOperationDetectorThread.sleepInterval(SlowOperationDetector.java:218)
		at com.hazelcast.spi.impl.SlowOperationDetector$SlowOperationDetectorThread.run(SlowOperationDetector.java:122)
```

There must not be any thread like ```hz._hzInstance_28***```.

**Comment by pveentjer** [comment]
@serkan-ozal if you want I can fix this.

**Comment by serkan-ozal** [comment]
@pveentjer ok, can you fix both of them. I was fixing them with ```thread.join(...)```
