### ISSUE TITLE
"Unable to connect to any address in the config!" and "Error while connecting to cluster!"

### ISSUE THREAD

**Issue by cherednichenko** [hazelcast/hazelcast#4774]
I run the following test in two consoles at the same time on Hazelcast version 3.4 (like in parallel). Two workers were created in agents.txt 

```
INFO  14:26:02 --------------------------------------------------------------
INFO  14:26:02 Connect to agent 54.83.184.178 OK
INFO  14:26:02 Connect to agent 54.160.69.25 OK
INFO  14:26:02 --------------------------------------------------------------
INFO  14:26:02 All agents are reachable!
INFO  14:26:02 --------------------------------------------------------------
INFO  14:26:03 Performance monitor enabled: false
INFO  14:26:03 Total number of agents: 2
INFO  14:26:03 Total number of Hazelcast member workers: 1
INFO  14:26:03 Total number of Hazelcast client workers: 2
INFO  14:26:03     Agent 54.83.184.178 members: 1 clients: 1
INFO  14:26:03     Agent 54.160.69.25 members: 0 clients: 1
```

go.sh looks:

```
[sergei@ip-10-72-134-107 test1]$ cat go.sh 
#!/bin/sh

boxCount=1
members=1
clients=2
duration=1m

provisioner --scale ${boxCount}

coordinator --memberWorkerCount ${members} \
	        --clientWorkerCount ${clients} \
	        --duration ${duration} \
	        --parallel \
	        test1.properties

provisioner --download

provisioner --terminate
```

Test:
```
test1@class=com.hazelcast.stabilizer.tests.map.StringStringMapTest
test1@keyCount=1000
```

Output from 1 console:
```
INFO  2015-03-09 10:26:07,920 [main] com.hazelcast.core.LifecycleService: HazelcastClient[hz.client_0_workers][3.4] is STARTED
WARN  2015-03-09 10:26:08,134 [hz.client_0_workers.cluster-listener] com.hazelcast.client.spi.impl.ClusterListenerThread: Unable to get alive cluster connection, try in 2799 ms later, attempt 1 of 2.
WARN  2015-03-09 10:26:10,935 [hz.client_0_workers.cluster-listener] com.hazelcast.client.spi.impl.ClusterListenerThread: Unable to get alive cluster connection, try in 2999 ms later, attempt 2 of 2.
FATAL 2015-03-09 10:26:13,936 [hz.client_0_workers.cluster-listener] com.hazelcast.client.spi.impl.ClusterListenerThread: Error while connecting to cluster!
java.lang.IllegalStateException: Unable to connect to any address in the config! The following addresses were tried:[Address[10.144.227.239]:5701, Address[10.238.169.212]:5701]
	at com.hazelcast.client.spi.impl.ClusterListenerThread.connectToOne(ClusterListenerThread.java:288)
	at com.hazelcast.client.spi.impl.ClusterListenerThread.run(ClusterListenerThread.java:86)
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:735)
	at sun.nio.ch.SocketAdaptor.connect(SocketAdaptor.java:117)
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl$ConnectionProcessor.call(ClientConnectionManagerImpl.java:383)
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl$ConnectionProcessor.call(ClientConnectionManagerImpl.java:350)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at com.hazelcast.util.executor.CompletableFutureTask.run(CompletableFutureTask.java:57)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)
INFO  2015-03-09 10:26:13,939 [hz.client_0_workers.cluster-listener] com.hazelcast.core.LifecycleService: HazelcastClient[hz.client_0_workers][3.4] is SHUTTING_DOWN
INFO  2015-03-09 10:26:13,942 [hz.client_0_workers.cluster-listener] com.hazelcast.core.LifecycleService: HazelcastClient[hz.client_0_workers][3.4] is SHUTDOWN
WARN  2015-03-09 10:26:13,942 [main] com.hazelcast.stabilizer.utils.ExceptionReporter: Exception #1 detected
java.lang.IllegalStateException: Unable to connect to any address in the config! The following addresses were tried:[Address[10.144.227.239]:5701, Address[10.238.169.212]:5701]
	at com.hazelcast.client.spi.impl.ClusterListenerThread.connectToOne(ClusterListenerThread.java:288)
	at com.hazelcast.client.spi.impl.ClusterListenerThread.run(ClusterListenerThread.java:86)
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:735)
	at sun.nio.ch.SocketAdaptor.connect(SocketAdaptor.java:117)
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl$ConnectionProcessor.call(ClientConnectionManagerImpl.java:383)
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl$ConnectionProcessor.call(ClientConnectionManagerImpl.java:350)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at com.hazelcast.util.executor.CompletableFutureTask.run(CompletableFutureTask.java:57)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)
INFO  2015-03-09 10:26:03,542 [main] com.hazelcast.stabilizer.worker.MemberWorker: Starting Stabilizer Worker

......

FATAL 2015-03-09 10:26:13,919 [hz.client_0_workers.cluster-listener] com.hazelcast.client.spi.impl.ClusterListenerThread: Error while connecting to cluster!
java.lang.IllegalStateException: Unable to connect to any address in the config! The following addresses were tried:[Address[10.144.227.239]:5701, Address[10.238.169.212]:5701]
	at com.hazelcast.client.spi.impl.ClusterListenerThread.connectToOne(ClusterListenerThread.java:288)
	at com.hazelcast.client.spi.impl.ClusterListenerThread.run(ClusterListenerThread.java:86)
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:735)
	at sun.nio.ch.SocketAdaptor.connect(SocketAdaptor.java:117)
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl$ConnectionProcessor.call(ClientConnectionManagerImpl.java:383)
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl$ConnectionProcessor.call(ClientConnectionManagerImpl.java:350)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at com.hazelcast.util.executor.CompletableFutureTask.run(CompletableFutureTask.java:57)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)
INFO  2015-03-09 10:26:13,922 [hz.client_0_workers.cluster-listener] com.hazelcast.core.LifecycleService: HazelcastClient[hz.client_0_workers][3.4] is SHUTTING_DOWN
INFO  2015-03-09 10:26:13,924 [hz.client_0_workers.cluster-listener] com.hazelcast.core.LifecycleService: HazelcastClient[hz.client_0_workers][3.4] is SHUTDOWN
WARN  2015-03-09 10:26:13,925 [main] com.hazelcast.stabilizer.utils.ExceptionReporter: Exception #1 detected
java.lang.IllegalStateException: Unable to connect to any address in the config! The following addresses were tried:[Address[10.144.227.239]:5701, Address[10.238.169.212]:5701]
	at com.hazelcast.client.spi.impl.ClusterListenerThread.connectToOne(ClusterListenerThread.java:288)
	at com.hazelcast.client.spi.impl.ClusterListenerThread.run(ClusterListenerThread.java:86)
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:735)
	at sun.nio.ch.SocketAdaptor.connect(SocketAdaptor.java:117)
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl$ConnectionProcessor.call(ClientConnectionManagerImpl.java:383)
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl$ConnectionProcessor.call(ClientConnectionManagerImpl.java:350)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at com.hazelcast.util.executor.CompletableFutureTask.run(CompletableFutureTask.java:57)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)
```

Output from 2 console:

```
INFO  2015-03-09 10:26:03,460 [main] com.hazelcast.core.LifecycleService: [10.238.169.212]:5701 [workers] [3.4] Address[10.238.169.212]:5701 is STARTING
INFO  2015-03-09 10:26:03,616 [hz._hzInstance_1_workers.cached.thread-2] com.hazelcast.nio.tcp.SocketConnector: [10.238.169.212]:5701 [workers] [3.4] Connecting to /10.144.227.239:5701, timeout: 0, bind-any: true
INFO  2015-03-09 10:26:03,812 [hz._hzInstance_1_workers.cached.thread-2] com.hazelcast.nio.tcp.SocketConnector: [10.238.169.212]:5701 [workers] [3.4] Could not connect to: /10.144.227.239:5701. Reason: SocketException[Connection refused to address /10.144.227.239:5701]
INFO  2015-03-09 10:26:03,813 [hz._hzInstance_1_workers.cached.thread-2] com.hazelcast.cluster.impl.TcpIpJoiner: [10.238.169.212]:5701 [workers] [3.4] Address[10.144.227.239]:5701 is added to the blacklist.
INFO  2015-03-09 10:26:04,416 [hz._hzInstance_1_workers.IO.thread-Acceptor] com.hazelcast.nio.tcp.SocketAcceptor: [10.238.169.212]:5701 [workers] [3.4] Accepting socket connection from /10.238.169.212:59615
```

![run_two_sets_same_test_using_different_workers](https://cloud.githubusercontent.com/assets/7486878/6557418/73fdb018-c67d-11e4-9bc1-e4e85d4d18cf.png)
![run_two_sets_same_test_using_different_workers1](https://cloud.githubusercontent.com/assets/7486878/6557419/7421f1d0-c67d-11e4-8091-60a4967ffc09.png)

**Comment by pveentjer** [comment]
You are trying to connect to the same agents from 2 different consoles? This is not a supported use-case for Stabilizer.

**Comment by cherednichenko** [comment]
Perhaps, but it's real case I believe. As far as I saw agents were created and agents.txt was updated successfully. It's all about parallelisation and multi-theards, isn't it?

**Comment by pveentjer** [comment]
You should not test it this way because Stabilizer is not designed for this usecase. What actually happens is that the JVM's are killed using kill-9.
