### ISSUE TITLE
[TEST-FAILURE]  InvocationNetworkSplitTest.testWaitingInvocations_whenNodeSplitFromCluster

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#4779]
```
java.lang.AssertionError: expected:<3> but was:<2>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:555)
	at org.junit.Assert.assertEquals(Assert.java:542)
	at com.hazelcast.spi.impl.InvocationNetworkSplitTest.testWaitingInvocations_whenNodeSplitFromCluster(InvocationNetworkSplitTest.java:103)
	at com.hazelcast.spi.impl.InvocationNetworkSplitTest.testWaitingInvocations_whenNodeSplitFromCluster(InvocationNetworkSplitTest.java:57)
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-OracleJDK1.6/com.hazelcast$hazelcast/170/testReport/junit/com.hazelcast.spi.impl/InvocationNetworkSplitTest/testWaitingInvocations_whenNodeSplitFromCluster/

**Comment by bilalyasar** [comment]
also scenaria 1 fails: https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK6/com.hazelcast$hazelcast/467/testReport/junit/com.hazelcast.spi.impl/InvocationNetworkSplitTest/testWaitingInvocations_whenNodePartiallySplitFromCluster_scenario1/

**Comment by bilalyasar** [comment]
duplicate of #4734 , closing.
