### ISSUE TITLE
[TEST-FAILURE] SlowOperationDetector_purgeTest.testPurging_SlowOperationLog

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#4780]
```
java.lang.AssertionError: Expected 0 slow operation logs, but was 1 expected:<0> but was:<1>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at com.hazelcast.test.HazelcastTestSupport.assertEqualsStringFormat(HazelcastTestSupport.java:647)
	at com.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationDetectorAbstractTest.assertNumberOfSlowOperationLogs(SlowOperationDetectorAbstractTest.java:130)
	at com.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationDetector_purgeTest.testPurging_SlowOperationLog(SlowOperationDetector_purgeTest.java:90)
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/492/testReport/junit/com.hazelcast.spi.impl.operationexecutor.slowoperationdetector/SlowOperationDetector_purgeTest/testPurging_SlowOperationLog/

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-sonar/com.hazelcast$hazelcast/551/testReport/junit/com.hazelcast.spi.impl.operationexecutor.slowoperationdetector/SlowOperationDetector_purgeTest/testPurging_SlowOperationLog/

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/495/com.hazelcast$hazelcast/testReport/com.hazelcast.spi.impl.operationexecutor.slowoperationdetector/SlowOperationDetector_purgeTest/testPurging_SlowOperationLog/

**Comment by Donnerbart** [comment]
This should be an error in the test, not the purging. I just increased the sleep time by a second. If the test still fails I'll have a closer look at the code.

**Comment by mesutcelik** [comment]
@Donnerbart ,

Can you please close this issue with commit id? That is beneficial for the history of test failure.

**Comment by Donnerbart** [comment]
Should be fixed via https://github.com/hazelcast/hazelcast/commit/3e23c778f73c3739a2e304aff8397cbf74be5a17
