### ISSUE TITLE
[TEST-FAILURE] ClientTxnMultiMapTest failures

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#4781]
com.hazelcast.client.txn.ClientTxnMultiMapTest.testRemove_whenBackedWithList
com.hazelcast.client.txn.ClientTxnMultiMapTest.testGet_whenBackedWithList
```
com.hazelcast.core.HazelcastException: Could not obtain Connection!!!
	at com.hazelcast.client.txn.ClientTransactionManager.getRandomAddress(ClientTransactionManager.java:216)
	at com.hazelcast.client.txn.ClientTransactionManager.connect(ClientTransactionManager.java:140)
	at com.hazelcast.client.txn.TransactionContextProxy.<init>(TransactionContextProxy.java:63)
	at com.hazelcast.client.txn.ClientTransactionManager.newTransactionContext(ClientTransactionManager.java:87)
	at com.hazelcast.client.txn.ClientTransactionManager.newTransactionContext(ClientTransactionManager.java:83)
	at com.hazelcast.client.impl.HazelcastClientInstanceImpl.newTransactionContext(HazelcastClientInstanceImpl.java:343)
	at com.hazelcast.client.impl.HazelcastClientProxy.newTransactionContext(HazelcastClientProxy.java:158)
	at com.hazelcast.client.txn.ClientTxnMultiMapTest.testRemove_whenBackedWithList(ClientTxnMultiMapTest.java:241)
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK8/492/testReport/

**Comment by sancar** [comment]
Possibly fixed via https://github.com/hazelcast/hazelcast/pull/4769 because of the change in initial member list behaviour
