### ISSUE TITLE
'Error while fetching cluster partition table!' and 'Connection refused' occur when 'workers' were killed during running the test

### ISSUE THREAD

**Issue by cherednichenko** [hazelcast/hazelcast#4783]
I run 'com.hazelcast.stabilizer.tests.map.StringStringMapTest' test and it some moment I killed all workers on stabilizer machine, then exceptions occur on client side.

```
Failure[
   message='Worked ran into an unhandled exception'
   type='Worker exception'
   agentAddress=10.169.69.31
   time=Tue Mar 10 15:27:22 UTC 2015
   workerAddress=client:10.169.69.31
   workerId=worker-10.169.69.31-5-client
   test=TestCase{
          id=test1
        , class=com.hazelcast.stabilizer.tests.map.StringStringMapTest
        , keyCount=1000
    }
   cause=com.hazelcast.core.HazelcastException: java.net.ConnectException: Connection refused
    at com.hazelcast.util.ExceptionUtil.rethrow(ExceptionUtil.java:52)
    at com.hazelcast.util.ExceptionUtil.rethrow(ExceptionUtil.java:47)
    at com.hazelcast.client.spi.ClientProxy.invoke(ClientProxy.java:130)
    at com.hazelcast.client.proxy.ClientMapProxy.get(ClientMapProxy.java:191)
    at com.hazelcast.stabilizer.tests.map.StringStringMapTest$WorkerTask.timeStep(StringStringMap
Test.java:129)
    at com.hazelcast.stabilizer.tests.map.StringStringMapTest$WorkerTask.timeStep(StringStringMap
Test.java:106)
    at com.hazelcast.stabilizer.worker.tasks.AbstractWorkerTask.run(AbstractWorkerTask.java:57)
    at java.lang.Thread.run(Thread.java:744)
    at com.hazelcast.stabilizer.test.utils.ThreadSpawner$DefaultThread.run(ThreadSpawner.java:89)
Caused by: java.net.ConnectException: Connection refused
    at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
    at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:735)
    at sun.nio.ch.SocketAdaptor.connect(SocketAdaptor.java:117)
    at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl$ConnectionProcessor.call(C
lientConnectionManagerImpl.java:383)
    at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl$ConnectionProcessor.call(C
lientConnectionManagerImpl.java:350)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at com.hazelcast.util.executor.CompletableFutureTask.run(CompletableFutureTask.java:57)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:744)
    at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:
76)
    at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)
    at ------ End remote and begin local stack-trace ------.(Unknown Source)
    at com.hazelcast.client.spi.impl.ClientCallFuture.resolveResponse(ClientCallFuture.java:201)
    at com.hazelcast.client.spi.impl.ClientCallFuture.get(ClientCallFuture.java:142)
    at com.hazelcast.client.spi.impl.ClientCallFuture.get(ClientCallFuture.java:118)
    at com.hazelcast.client.spi.ClientProxy.invoke(ClientProxy.java:127)
    ... 6 more

]
```

It's from the log of one of workers:

```
WARN  2015-03-10 11:27:20,931 [hz.client_0_workers.cluster-listener] com.hazelcast.client.connection.nio.ClientConnection: Connection [null] lost. Reason: Socket explicitly closed
INFO  2015-03-10 11:27:20,931 [hz.client_0_workers.cluster-listener] com.hazelcast.core.LifecycleService: HazelcastClient[hz.client_0_workers][3.4] is CLIENT_DISCONNECTED
WARN  2015-03-10 11:27:20,931 [InSelector] com.hazelcast.client.connection.nio.ClientReadHandler: InSelector Closing socket to endpoint Address[10.169.69.31]:5701, Cause:java.io.IOException: Connection reset by peer
WARN  2015-03-10 11:27:21,197 [Thread-1] com.hazelcast.stabilizer.utils.ExceptionReporter: Exception #1 detected
com.hazelcast.core.HazelcastException: java.net.ConnectException: Connection refused
    at com.hazelcast.util.ExceptionUtil.rethrow(ExceptionUtil.java:52)
    at com.hazelcast.util.ExceptionUtil.rethrow(ExceptionUtil.java:47)
    at com.hazelcast.client.spi.ClientProxy.invoke(ClientProxy.java:130)
    at com.hazelcast.client.proxy.ClientMapProxy.get(ClientMapProxy.java:191)
    at com.hazelcast.stabilizer.tests.map.StringStringMapTest$WorkerTask.timeStep(StringStringMapTest.java:129)
    at com.hazelcast.stabilizer.tests.map.StringStringMapTest$WorkerTask.timeStep(StringStringMapTest.java:106)
    at com.hazelcast.stabilizer.worker.tasks.AbstractWorkerTask.run(AbstractWorkerTask.java:57)
    at java.lang.Thread.run(Thread.java:744)
    at com.hazelcast.stabilizer.test.utils.ThreadSpawner$DefaultThread.run(ThreadSpawner.java:89)
Caused by: java.net.ConnectException: Connection refused
    at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
    at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:735)
    at sun.nio.ch.SocketAdaptor.connect(SocketAdaptor.java:117)
    at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl$ConnectionProcessor.call(ClientConnectionManagerImpl.java:383)
    at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl$ConnectionProcessor.call(ClientConnectionManagerImpl.java:350)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at com.hazelcast.util.executor.CompletableFutureTask.run(CompletableFutureTask.java:57)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:744)
    at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
    at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)
    at ------ End remote and begin local stack-trace ------.(Unknown Source)
    at com.hazelcast.client.spi.impl.ClientCallFuture.resolveResponse(ClientCallFuture.java:201)
    at com.hazelcast.client.spi.impl.ClientCallFuture.get(ClientCallFuture.java:142)
    at com.hazelcast.client.spi.impl.ClientCallFuture.get(ClientCallFuture.java:118)
    at com.hazelcast.client.spi.ClientProxy.invoke(ClientProxy.java:127)
    ... 6 more
```

and the last in log:
```
INFO  2015-03-10 11:27:21,269 [Thread-3] com.hazelcast.stabilizer.worker.WorkerCommandRequestProcessor: --------------------------- Completed test1.run() ---------------------------
INFO  2015-03-10 11:27:21,269 [Thread-3] com.hazelcast.stabilizer.worker.WorkerCommandRequestProcessor: --------------------------- Stopping performance monitoring ---------------------------
WARN  2015-03-10 11:27:21,932 [hz.client_0_workers.cluster-listener] com.hazelcast.client.spi.impl.ClusterListenerThread: Unable to get alive cluster connection, try in 2999 ms later, attempt 1 of 2.
WARN  2015-03-10 11:27:24,934 [hz.client_0_workers.cluster-listener] com.hazelcast.client.spi.impl.ClusterListenerThread: Unable to get alive cluster connection, try in 2998 ms later, attempt 2 of 2.
[sergei@ip-10-72-134-107 worker-10.169.69.31-5-client]$ 
```

and from the log of the second worked:
```
INFO  2015-03-10 11:27:21,265 [Thread-4] com.hazelcast.stabilizer.worker.WorkerCommandRequestProcessor: --------------------------- Stopping performance monitoring ---------------------------
WARN  2015-03-10 11:27:21,934 [hz.client_0_workers.cluster-listener] com.hazelcast.client.spi.impl.ClusterListenerThread: Unable to get alive cluster connection, try in 2998 ms later, attempt 1 of 2.
WARN  2015-03-10 11:27:24,933 [hz.client_0_workers.cluster-listener] com.hazelcast.client.spi.impl.ClusterListenerThread: Unable to get alive cluster connection, try in 2999 ms later, attempt 2 of 2.
FATAL 2015-03-10 11:27:25,874 [hz.client_0_workers.cached-1] com.hazelcast.client.spi.ClientPartitionService: Error while fetching cluster partition table!
java.net.ConnectException: Connection refused
    at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
    at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:735)
    at sun.nio.ch.SocketAdaptor.connect(SocketAdaptor.java:117)
    at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl$ConnectionProcessor.call(ClientConnectionManagerImpl.java:383)
    at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl$ConnectionProcessor.call(ClientConnectionManagerImpl.java:350)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at com.hazelcast.util.executor.CompletableFutureTask.run(CompletableFutureTask.java:57)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:744)
    at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
    at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)
[sergei@ip-10-72-134-107 worker-10.169.69.31-6-client]$ 
```

![workers_interruption_and_worker_exceptiosn](https://cloud.githubusercontent.com/assets/7486878/6584996/b8f30c40-c777-11e4-88be-f7d0c78429ca.png)

p.s. when I killed two processes for workers instead of three, the following errors occurs:
![workers_interruption](https://cloud.githubusercontent.com/assets/7486878/6585011/dd132ca4-c777-11e4-81a4-2de8b63e41c4.png)
![workers_interruption1](https://cloud.githubusercontent.com/assets/7486878/6585012/dd484ae2-c777-11e4-9374-72e0671c51b5.png)

**Comment by gurbuzali** [comment]
This is the expected behavior, if all nodes are down clients will throw `ConnectionRefusedException`
