### ISSUE TITLE
[TEST-FAILURE] standalone.ClientMapStandaloneTest failures

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#4784]
com.hazelcast.client.standalone.ClientMapStandaloneTest.testPortable_withEntryListenerWithPredicate
com.hazelcast.client.standalone.ClientMapStandaloneTest.testGet
com.hazelcast.client.standalone.ClientMapStandaloneTest.testPut
com.hazelcast.client.standalone.ClientMapStandaloneTest.testClear
com.hazelcast.client.standalone.ClientMapStandaloneTest.testRemove

```
com.hazelcast.core.HazelcastException: java.io.IOException: Not address found to invoke 
	at com.hazelcast.client.spi.impl.ClientSmartInvocationServiceImpl.invokeOnRandomTarget(ClientSmartInvocationServiceImpl.java:57)
	at com.hazelcast.client.spi.impl.ClientInvocation.invokeOnSelection(ClientInvocation.java:148)
	at com.hazelcast.client.spi.impl.ClientInvocation.invoke(ClientInvocation.java:132)
	at com.hazelcast.client.spi.impl.ClientInvocation.run(ClientInvocation.java:155)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1121)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:614)
	at java.lang.Thread.run(Thread.java:780)
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.7/486/

**Comment by sancar** [comment]
Possibly fixed via https://github.com/hazelcast/hazelcast/pull/4769 because of the change in initial member list behaviour
