### ISSUE TITLE
[TEST-FAILURE] ClientExecutionPoolSizeLowTest.testOwnerNodeTerminateWithAsyncOperations

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#4787]
```
java.lang.AssertionError: the size of the map is not correct expected:<1000> but was:<677>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:555)
	at com.hazelcast.test.HazelcastTestSupport$3.run(HazelcastTestSupport.java:139)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:256)
	at com.hazelcast.test.HazelcastTestSupport.assertSizeEventually(HazelcastTestSupport.java:136)
	at com.hazelcast.test.HazelcastTestSupport.assertSizeEventually(HazelcastTestSupport.java:132)
	at com.hazelcast.client.io.ClientExecutionPoolSizeLowTest.testOwnerNodeTerminateWithAsyncOperations(ClientExecutionPoolSizeLowTest.java:97)
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-nightly/com.hazelcast$hazelcast-client/413/testReport/junit/com.hazelcast.client.io/ClientExecutionPoolSizeLowTest/testOwnerNodeTerminateWithAsyncOperations/

**Comment by mesutcelik** [comment]
**This is maintenance-3.x branch**

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-OracleJDK8/173/com.hazelcast$hazelcast/testReport/com.hazelcast.map/LocalMapStatsTest/testLastAccessTime_updatedConcurrently/

**Comment by mesutcelik** [comment]
**This has made night build timeout**
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/498/artifact/hazelcast-client/target/surefire-reports/com.hazelcast.client.io.ClientExecutionPoolSizeLowTest-output.txt

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-nightly/421/com.hazelcast$hazelcast-client/testReport/com.hazelcast.client.io/ClientExecutionPoolSizeLowTest/testOwnerNodeTerminateWithAsyncOperations/

**Comment by sancar** [comment]
Closed via https://github.com/hazelcast/hazelcast/commit/02c24e596d1f598d1b9bdda6e9eb9ed1c132a1c8 .

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast-client/535/testReport/junit/com.hazelcast.client.io/ClientExecutionPoolSizeLowTest/testOwnerNodeTerminateWithAsyncOperations/

@sancar , 
that failed again..

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-sonar/com.hazelcast$hazelcast-client/594/testReport/junit/com.hazelcast.client.io/ClientExecutionPoolSizeLowTest/testOwnerNodeTerminateWithAsyncOperations/

**Comment by sancar** [comment]
Closing this one since it did not failed over 1 month.
