### ISSUE TITLE
[TEST-FAILURE] JCacheListenerTest.testReplaceIfSameWithSyncListener_whenEntryNotExists

### ISSUE THREAD

**Issue by mesutcelik** [hazelcast/hazelcast#4830]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.6/485/com.hazelcast$hazelcast/testReport/com.hazelcast.cache/JCacheListenerTest/testReplaceIfSameWithSyncListener_whenEntryNotExists/

**Comment by serkan-ozal** [comment]
Not sure but may be related this.

From one of the previous map-reduce tests, seems that there are unclosed threads.

````
"cached2" 
	java.lang.Thread.State: TIMED_WAITING on lock=com.hazelcast.spi.impl.BasicInvocationFuture@5e7d5e7d
		at java.lang.Object.wait(Native Method)
		at java.lang.Object.wait(Object.java:196)
		at com.hazelcast.spi.impl.BasicInvocationFuture.pollResponse(BasicInvocationFuture.java:269)
		at com.hazelcast.spi.impl.BasicInvocationFuture.waitForResponse(BasicInvocationFuture.java:220)
		at com.hazelcast.spi.impl.BasicInvocationFuture.get(BasicInvocationFuture.java:197)
		at com.hazelcast.spi.impl.BasicInvocationFuture.get(BasicInvocationFuture.java:177)
		at com.hazelcast.mapreduce.impl.MapReduceService.processRequest(MapReduceService.java:223)
		at com.hazelcast.mapreduce.impl.task.KeyValueSourceFacade.notifyProcessStats(KeyValueSourceFacade.java:112)
		at com.hazelcast.mapreduce.impl.task.KeyValueSourceFacade.close(KeyValueSourceFacade.java:101)
		at com.hazelcast.mapreduce.impl.task.MapCombineTask.processPartitionMapping(MapCombineTask.java:245)
		at com.hazelcast.mapreduce.impl.task.MapCombineTask.access$700(MapCombineTask.java:64)
		at com.hazelcast.mapreduce.impl.task.MapCombineTask$PartitionProcessor.processPartitions(MapCombineTask.java:296)
		at com.hazelcast.mapreduce.impl.task.MapCombineTask$PartitionProcessor.run(MapCombineTask.java:273)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:452)
		at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:314)
		at java.util.concurrent.FutureTask.run(FutureTask.java:149)
		at com.hazelcast.util.executor.CompletableFutureTask.run(CompletableFutureTask.java:57)
		at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:209)
		at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:897)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:919)
		at java.lang.Thread.run(Thread.java:738)
		at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
		at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)

"scheduled" 
	java.lang.Thread.State: TIMED_WAITING on lock=java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@30283028
		at sun.misc.Unsafe.park(Native Method)
		at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:222)
		at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2036)
		at java.util.concurrent.DelayQueue.take(DelayQueue.java:175)
		at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:620)
		at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:613)
		at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:958)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
		at java.lang.Thread.run(Thread.java:738)
		at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
		at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)

"hz._hzInstance_817_dev.partition-operation.thread-0" 
	java.lang.Thread.State: WAITING on lock=java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@52475247
		at sun.misc.Unsafe.park(Native Method)
		at java.util.concurrent.locks.LockSupport.park(LockSupport.java:182)
		at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1998)
		at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
		at com.hazelcast.spi.impl.operationexecutor.classic.DefaultScheduleQueue.take(DefaultScheduleQueue.java:79)
		at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.doRun(OperationThread.java:73)
		at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.run(OperationThread.java:60)

"hz._hzInstance_817_dev.partition-operation.thread-1" 
	java.lang.Thread.State: WAITING on lock=java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@53d053d0
		at sun.misc.Unsafe.park(Native Method)
		at java.util.concurrent.locks.LockSupport.park(LockSupport.java:182)
		at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1998)
		at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
		at com.hazelcast.spi.impl.operationexecutor.classic.DefaultScheduleQueue.take(DefaultScheduleQueue.java:79)
		at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.doRun(OperationThread.java:73)
		at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.run(OperationThread.java:60)

"hz._hzInstance_817_dev.generic-operation.thread-0" 
	java.lang.Thread.State: WAITING on lock=java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@480b480b
		at sun.misc.Unsafe.park(Native Method)
		at java.util.concurrent.locks.LockSupport.park(LockSupport.java:182)
		at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1998)
		at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
		at com.hazelcast.spi.impl.operationexecutor.classic.DefaultScheduleQueue.take(DefaultScheduleQueue.java:79)
		at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.doRun(OperationThread.java:73)
		at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.run(OperationThread.java:60)

"hz._hzInstance_817_dev.generic-operation.thread-1" 
	java.lang.Thread.State: WAITING on lock=java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@480b480b
		at sun.misc.Unsafe.park(Native Method)
		at java.util.concurrent.locks.LockSupport.park(LockSupport.java:182)
		at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1998)
		at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
		at com.hazelcast.spi.impl.operationexecutor.classic.DefaultScheduleQueue.take(DefaultScheduleQueue.java:79)
		at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.doRun(OperationThread.java:73)
		at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.run(OperationThread.java:60)

"hz._hzInstance_817_dev.response" 
	java.lang.Thread.State: WAITING on lock=java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@58635863
		at sun.misc.Unsafe.park(Native Method)
		at java.util.concurrent.locks.LockSupport.park(LockSupport.java:182)
		at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1998)
		at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
		at com.hazelcast.spi.impl.operationexecutor.classic.ResponseThread.doRun(ResponseThread.java:57)
		at com.hazelcast.spi.impl.operationexecutor.classic.ResponseThread.run(ResponseThread.java:46)

"hz._hzInstance_817_dev.SlowOperationDetectorThread" 
	java.lang.Thread.State: TIMED_WAITING
		at java.lang.Thread.sleep(Native Method)
		at java.util.concurrent.TimeUnit.sleep(TimeUnit.java:339)
		at com.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationDetector$DetectorThread.sleepInterval(SlowOperationDetector.java:242)
		at com.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationDetector$DetectorThread.run(SlowOperationDetector.java:145)

"hz._hzInstance_817_dev.CleanupThread" 
	java.lang.Thread.State: TIMED_WAITING
		at java.lang.Thread.sleep(Native Method)
		at java.lang.Thread.sleep(Thread.java:853)
		at com.hazelcast.spi.impl.BasicOperationService$CleanupThread.sleep(BasicOperationService.java:1126)
		at com.hazelcast.spi.impl.BasicOperationService$CleanupThread.run(BasicOperationService.java:1115)

"hz._hzInstance_817_dev.event-4081" 
	java.lang.Thread.State: WAITING on lock=java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@733d733d
		at sun.misc.Unsafe.park(Native Method)
		at java.util.concurrent.locks.LockSupport.park(LockSupport.java:182)
		at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1998)
		at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
		at com.hazelcast.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:173)

"hz._hzInstance_817_dev.event-4082" 
	java.lang.Thread.State: WAITING on lock=java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@746a746a
		at sun.misc.Unsafe.park(Native Method)
		at java.util.concurrent.locks.LockSupport.park(LockSupport.java:182)
		at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1998)
		at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
		at com.hazelcast.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:173)

"hz._hzInstance_817_dev.event-4083" 
	java.lang.Thread.State: WAITING on lock=java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@75977597
		at sun.misc.Unsafe.park(Native Method)
		at java.util.concurrent.locks.LockSupport.park(LockSupport.java:182)
		at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1998)
		at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
		at com.hazelcast.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:173)

"hz._hzInstance_817_dev.event-4084" 
	java.lang.Thread.State: WAITING on lock=java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@76c476c4
		at sun.misc.Unsafe.park(Native Method)
		at java.util.concurrent.locks.LockSupport.park(LockSupport.java:182)
		at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1998)
		at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
		at com.hazelcast.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:173)

"hz._hzInstance_817_dev.event-4085" 
	java.lang.Thread.State: WAITING on lock=java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@78087808
		at sun.misc.Unsafe.park(Native Method)
		at java.util.concurrent.locks.LockSupport.park(LockSupport.java:182)
		at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1998)
		at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
		at com.hazelcast.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:173)

"hz._hzInstance_817_dev.wait-notify" 
	java.lang.Thread.State: TIMED_WAITING on lock=java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@7b5f7b5f
		at sun.misc.Unsafe.park(Native Method)
		at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:222)
		at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2036)
		at java.util.concurrent.DelayQueue.poll(DelayQueue.java:212)
		at com.hazelcast.spi.impl.waitnotifyservice.impl.WaitNotifyServiceImpl$ExpirationTask.doRun(WaitNotifyServiceImpl.java:295)
		at com.hazelcast.spi.impl.waitnotifyservice.impl.WaitNotifyServiceImpl$ExpirationTask.run(WaitNotifyServiceImpl.java:280)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:452)
		at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:314)
		at java.util.concurrent.FutureTask.run(FutureTask.java:149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:897)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:919)
		at java.lang.Thread.run(Thread.java:738)
		at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
```

**Comment by serkan-ozal** [comment]
closed via https://github.com/hazelcast/hazelcast/commit/f2c330791c49e123a5bf3e916979ec43ef182cab

**Comment by serkan-ozal** [comment]
I am closing now and we can open if it fails again
