### ISSUE TITLE
On Dynamic Cluster, New Member Doesn't Know Cache Configs At Join

### ISSUE THREAD

**Issue by serkan-ozal** [hazelcast/hazelcast#4841]
On Dynamic Cluster, new member can take and execute a cache operation before it gets cache config via cache replication operation. In this case, there will be error about unknown cache/cache config. After a cache replication event is received, these configs will be taken but at this time it does'n execute some cache operations (such as cache put backup) due to unknown cache config. And this may cause data lost.

**Comment by Danny-Hazelcast** [comment]
FATAL 2015-03-19 15:27:51,968 [hz._hzInstance_1_workers.partition-operation.thread-0] com.hazelcast.cache.hidensity.operation.CachePutBackupOperation: [10.0.0.181]:5701 [workers]
 [3.5-SNAPSHOT] CacheConfig is null! /hz/j7
java.lang.IllegalArgumentException: CacheConfig is null! /hz/j7
    at com.hazelcast.cache.EnterpriseCacheService.createNewRecordStore(EnterpriseCacheService.java:82)
    at com.hazelcast.cache.impl.CachePartitionSegment$1.createNew(CachePartitionSegment.java:56)
    at com.hazelcast.cache.impl.CachePartitionSegment$1.createNew(CachePartitionSegment.java:53)
    at com.hazelcast.util.ConcurrencyUtil.getOrPutSynchronized(ConcurrencyUtil.java:40)
    at com.hazelcast.cache.impl.CachePartitionSegment.getOrCreateCache(CachePartitionSegment.java:76)
    at com.hazelcast.cache.impl.AbstractCacheService.getOrCreateCache(AbstractCacheService.java:108)
    at com.hazelcast.cache.hidensity.operation.AbstractHiDensityCacheOperation.beforeRun(AbstractHiDensityCacheOperation.java:76)
    at com.hazelcast.spi.impl.operationservice.impl.operations.Backup.run(Backup.java:100)
    at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:100)
    at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:258)
    at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.processPacket(OperationThread.java:126)
    at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.process(OperationThread.java:99)
    at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.doRun(OperationThread.java:85)
    at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.run(OperationThread.java:60)

**Comment by Danny-Hazelcast** [comment]
I have re encountered this issue,  and have a test for reproduction it  located at  
```
/disk1/danny/jcache-CacheNotExistsException      (for my memory)
```

cluster time line,   3 box, 1 dedicated member, 4 clients
1 min run, 
start 1 box 1 dedicated member

test.properties
```
jcache@class=com.hazelcast.enterprise.tests.jcache.JcacheTest
jcache@dynamicValueSizes=true
jcache@cacheBaseNamesStr=nat-nat,nat-bin,nat-obj,bin-nat,bin-bin,bin-obj,obj-nat,obj-bin,obj-obj
jcache@cachesPerName=2
jcache@threadCount=32
jcache@valueByteArraySize=4000

cacheMaxSz@class=com.hazelcast.simulator.tests.icache.EvictionICacheTest
cacheMaxSz@basename=maxCacheSmall
```

the exception 
```
cat group1/failures-2015-05-13__13_52_02.txt
Failure[
   message='Worked ran into an unhandled exception'
   type='Worker exception'
   agentAddress=10.81.168.4
   time=Wed May 13 13:53:44 UTC 2015
   workerAddress=client:10.81.168.4
   workerId=worker-10.81.168.4-1-client
   test=TestCase{
          id=cacheMaxSz
        , class=com.hazelcast.simulator.tests.icache.EvictionICacheTest
        , basename=maxCacheSmall
    }
   cause=com.hazelcast.cache.CacheNotExistsException: Cache config for cache /hz/maxCacheSmall has not been created yet !
	at com.hazelcast.cache.impl.client.AbstractCacheAllPartitionsRequest.getOperationProvider(AbstractCacheAllPartitionsRequest.java:48)
	at com.hazelcast.cache.impl.client.CacheSizeRequest.createOperationFactory(CacheSizeRequest.java:61)
	at com.hazelcast.client.impl.client.AllPartitionsClientRequest.process(AllPartitionsClientRequest.java:33)
	at com.hazelcast.client.impl.ClientEngineImpl$ClientPacketProcessor.processRequest(ClientEngineImpl.java:463)
	at com.hazelcast.client.impl.ClientEngineImpl$ClientPacketProcessor.run(ClientEngineImpl.java:379)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)
	at ------ End remote and begin local stack-trace ------.(Unknown Source)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveResponse(ClientInvocationFuture.java:147)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.get(ClientInvocationFuture.java:114)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.get(ClientInvocationFuture.java:89)
	at com.hazelcast.client.cache.impl.AbstractClientCacheProxyBase.invoke(AbstractClientCacheProxyBase.java:168)
	at com.hazelcast.client.cache.impl.AbstractClientCacheProxy.size(AbstractClientCacheProxy.java:311)
	at com.hazelcast.client.cache.impl.ClientCacheProxy.size(ClientCacheProxy.java:72)
	at com.hazelcast.simulator.tests.icache.EvictionICacheTest$WorkerThread.run(EvictionICacheTest.java:158)
	at java.lang.Thread.run(Thread.java:745)
	at com.hazelcast.simulator.utils.ThreadSpawner$DefaultThread.run(ThreadSpawner.java:106)

]
```

**Comment by serkan-ozal** [comment]
@Danny-Hazelcast I will fix this issue with with post join operation. 

This test doesn't compeletely fail on Enterprise JCache, because in your test you expect `IllegalArgumentException`. Then this temporary state is handled via `CacheReplicationOperation` since `CacheReplicationOperation` also carries cache configurations. So new node gets cache configuration and test can continue without problem.

However, this test fails on Open-Source JCache, because  in your test you expect `IllegalArgumentException` but Open-Source `CacheService` throws `CacheNotExistsException` (not a `IllegalArgumentException` but `IllegalStateException`).

Anyway, it is obvious that there is a problematic time window between node join and getting `CacheReplicationOperation` and will fix it before 3.5 release by sending cache configurations at node join to cluster via post join operation.

**Comment by Danny-Hazelcast** [comment]
its probably one of them auto closes,  but I would like to keep it open,  as i have a simulator test to reproduce this one.

**Comment by Danny-Hazelcast** [comment]
tested fixed
