### ISSUE TITLE
Native OOM Exceptions during fixing Native OOM problems

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#4842]
cause=java.lang.AssertionError: Double free(): 139974041452336
    at com.hazelcast.memory.AbstractPoolingMemoryManager.free(AbstractPoolingMemoryManager.java:143)
    at com.hazelcast.memory.PoolingMemoryManager.free(PoolingMemoryManager.java:92)
    at com.hazelcast.nio.serialization.EnterpriseSerializationServiceImpl.disposeData(EnterpriseSerializationServiceImpl.java:258)
    at com.hazelcast.cache.hidensity.impl.nativememory.HiDensityNativeMemoryCacheRecordProcessor.disposeData(HiDensityNativeMemoryCacheRecordProcessor.java:132)
    at com.hazelcast.elastic.map.BinaryElasticHashMap.clear(BinaryElasticHashMap.java:771)
    at com.hazelcast.cache.hidensity.impl.nativememory.HiDensityNativeMemoryCacheRecordMap.clear(HiDensityNativeMemoryCacheRecordMap.java:104)
    at com.hazelcast.cache.hidensity.impl.nativememory.HiDensityNativeMemoryCacheRecordMap.forceEvict(HiDensityNativeMemoryCacheRecordMap.java:154)
    at com.hazelcast.cache.hidensity.impl.nativememory.HiDensityNativeMemoryCacheRecordStore.forceEvict(HiDensityNativeMemoryCacheRecordStore.java:804)
    at com.hazelcast.cache.EnterpriseCacheService.forceEvict(EnterpriseCacheService.java:200)
    at com.hazelcast.cache.hidensity.operation.AbstractHiDensityCacheOperation.forceEvict(AbstractHiDensityCacheOperation.java:94)
    at com.hazelcast.cache.hidensity.operation.AbstractHiDensityCacheOperation.forceEvictAndRunInternal(AbstractHiDensityCacheOperation.java:109)
    at com.hazelcast.cache.hidensity.operation.AbstractHiDensityCacheOperation.run(AbstractHiDensityCacheOperation.java:102)
    at com.hazelcast.spi.impl.BasicOperationService$BasicOperationRunner.run(BasicOperationService.java:747)
    at com.hazelcast.spi.impl.BasicOperationService$BasicOperationRunner.run(BasicOperationService.java:905)
    at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.processPacket(OperationThread.java:126)
    at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.process(OperationThread.java:99)
    at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.doRun(OperationThread.java:85)
    at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.run(OperationThread.java:60)
    at ------ End remote and begin local stack-trace ------.(Unknown Source)
    at com.hazelcast.spi.impl.BasicInvocationFuture.resolveApplicationResponse(BasicInvocationFuture.java:391)
    at com.hazelcast.spi.impl.BasicInvocationFuture.resolveApplicationResponseOrThrowException(BasicInvocationFuture.java:324)
    at com.hazelcast.spi.impl.BasicInvocationFuture.get(BasicInvocationFuture.java:198)
    at com.hazelcast.spi.impl.BasicInvocationFuture.get(BasicInvocationFuture.java:177)
    at com.hazelcast.cache.impl.AbstractCacheProxy.put(AbstractCacheProxy.java:201)
    at com.hazelcast.cache.impl.CacheProxy.put(CacheProxy.java:70)
    at com.hazelcast.cache.impl.CacheProxy.put(CacheProxy.java:132)
    at com.LoadCache$Worker.updateDynamicCaches(LoadCache.java:148)
    at com.LoadCache$Worker.run(LoadCache.java:139)
    at java.lang.Thread.run(Thread.java:745)
    at com.hazelcast.stabilizer.test.utils.ThreadSpawner$DefaultThread.run(ThreadSpawner.java:89) 

com.hazelcast.nio.serialization.HazelcastSerializationException: There is no suitable de-serializer for type 1617920
    at com.hazelcast.nio.serialization.SerializationServiceImpl.toObject(SerializationServiceImpl.java:257)
    at com.hazelcast.cache.hidensity.impl.nativememory.HiDensityNativeMemoryCacheRecordAccessor.readValue(HiDensityNativeMemoryCacheRecordAccessor.java:99)
    at com.hazelcast.cache.hidensity.impl.nativememory.HiDensityNativeMemoryCacheRecordProcessor.readValue(HiDensityNativeMemoryCacheRecordProcessor.java:74)
    at com.hazelcast.cache.hidensity.impl.nativememory.HiDensityNativeMemoryCacheRecordStore.recordToValue(HiDensityNativeMemoryCacheRecordStore.java:204)
    at com.hazelcast.cache.hidensity.impl.nativememory.HiDensityNativeMemoryCacheRecordStore.recordToValue(HiDensityNativeMemoryCacheRecordStore.java:34)
    at com.hazelcast.cache.impl.AbstractCacheRecordStore.get(AbstractCacheRecordStore.java:783)
    at com.hazelcast.cache.impl.operation.CacheGetOperation.run(CacheGetOperation.java:50)
    at com.hazelcast.spi.impl.BasicOperationService$BasicOperationRunner.run(BasicOperationService.java:747)
    at com.hazelcast.spi.impl.BasicOperationService$BasicOperationRunner.run(BasicOperationService.java:905)
    at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.processPacket(OperationThread.java:126)
    at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.process(OperationThread.java:99)
    at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.doRun(OperationThread.java:85)
    at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.run(OperationThread.java:60)
    at ------ End remote and begin local stack-trace ------.(Unknown Source)
    at com.hazelcast.spi.impl.BasicInvocationFuture.resolveApplicationResponse(BasicInvocationFuture.java:391)
    at com.hazelcast.spi.impl.BasicInvocationFuture.resolveApplicationResponseOrThrowException(BasicInvocationFuture.java:324)
    at com.hazelcast.spi.impl.BasicInvocationFuture.get(BasicInvocationFuture.java:198)
    at com.hazelcast.spi.impl.BasicInvocationFuture.get(BasicInvocationFuture.java:177)
    at com.hazelcast.cache.impl.AbstractCacheProxy.get(AbstractCacheProxy.java:158)
    at com.hazelcast.cache.impl.CacheProxy.get(CacheProxy.java:70)
    at com.hazelcast.cache.impl.CacheProxy.get(CacheProxy.java:86)
    at com.LoadCache$Worker.updateDynamicCaches(LoadCache.java:151)
    at com.LoadCache$Worker.run(LoadCache.java:139)
    at java.lang.Thread.run(Thread.java:745)
    at com.hazelcast.stabilizer.test.utils.ThreadSpawner$DefaultThread.run(ThreadSpawner.java:89)

**Comment by Danny-Hazelcast** [comment]
Fixed
