### ISSUE TITLE
NullPointerException and IllegalStateException occur when running 'com.hazelcast.simulator.tests.icache.EvictionICacheTest'

### ISSUE THREAD

**Issue by cherednichenko** [hazelcast/hazelcast#4849]
Version 3.4.
Test: com.hazelcast.simulator.tests.icache.EvictionICacheTest

Logs:
```
INFO  14:22:24 --------------------------------------------------------------
Running Test : test2
TestCase{
      id=test2
    , class=com.hazelcast.simulator.tests.icache.EvictionICacheTest
}
--------------------------------------------------------------
INFO  14:22:24 test2 Starting Test initialization
INFO  14:22:25 test2 Completed Test initialization
INFO  14:22:25 test2 Starting Test setup
WARN  14:22:27 Failure #1  client:10.231.179.195 Worker exception[java.lang.NullPointerException]
WARN  14:22:27 Failure #2  10.231.179.195:5701 Worker exception[java.lang.NullPointerException]
WARN  14:22:27 Failure #3  client:10.231.179.195 Worker exception[java.lang.NullPointerException]
INFO  14:22:27 test2 Completed Test setup
INFO  14:22:27 test2 Starting Test local warmup
INFO  14:22:29 test2 Completed Test local warmup
INFO  14:22:29 test2 Starting Test global warmup
INFO  14:22:31 test2 Completed Test global warmup
INFO  14:22:31 test2 Starting Test start
INFO  14:22:32 test2 Completed Test start
INFO  14:22:32 test2 Test will run for 00d 00h 01m 00s
INFO  14:22:32 test2 Critical Failure detected, aborting execution of test
INFO  14:22:32 test2 Test finished running
INFO  14:22:32 test2 Starting Test stop
WARN  14:22:33 Failure #4  client:10.231.179.195 Worker exception[java.lang.IllegalStateException: Sum of operation probabilities should be exactly 1.0, but is 0.000000]
WARN  14:22:33 Failure #5  client:10.231.179.195 Worker exception[java.lang.IllegalStateException: Sum of operation probabilities should be exactly 1.0, but is 0.000000]
INFO  14:22:34 test2 Completed Test stop
```

from failure file:
```
Failure[
   message='Worked ran into an unhandled exception'
   type='Worker exception'
   agentAddress=10.231.179.195
   time=Fri Mar 20 14:22:26 UTC 2015
   workerAddress=client:10.231.179.195
   workerId=worker-10.231.179.195-15-client
   test=TestCase{
          id=test2
        , class=com.hazelcast.simulator.tests.icache.EvictionICacheTest
    }
   cause=java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.hash(ConcurrentHashMap.java:333)
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:988)
	at com.hazelcast.config.Config.lookupByPattern(Config.java:884)
	at com.hazelcast.config.Config.findCacheConfig(Config.java:251)
	at com.hazelcast.cache.impl.AbstractCacheService.findCacheConfig(AbstractCacheService.java:235)
	at com.hazelcast.cache.impl.operation.CacheGetConfigOperation.run(CacheGetConfigOperation.java:55)
	at com.hazelcast.spi.impl.BasicOperationService$OperationHandler.handle(BasicOperationService.java:733)
	at com.hazelcast.spi.impl.BasicOperationService$OperationHandler.access$500(BasicOperationService.java:709)
	at com.hazelcast.spi.impl.BasicOperationService.runOperationOnCallingThread(BasicOperationService.java:253)
	at com.hazelcast.spi.impl.BasicInvocation.doInvokeLocal(BasicInvocation.java:280)
	at com.hazelcast.spi.impl.BasicInvocation.doInvoke(BasicInvocation.java:262)
	at com.hazelcast.spi.impl.BasicInvocation.invoke(BasicInvocation.java:229)
	at com.hazelcast.spi.impl.BasicInvocationBuilder.invoke(BasicInvocationBuilder.java:45)
	at com.hazelcast.client.impl.client.PartitionClientRequest.process(PartitionClientRequest.java:60)
	at com.hazelcast.client.impl.ClientEngineImpl$ClientPacketProcessor.processRequest(ClientEngineImpl.java:434)
	at com.hazelcast.client.impl.ClientEngineImpl$ClientPacketProcessor.run(ClientEngineImpl.java:353)
	at com.hazelcast.spi.impl.BasicOperationService$BasicDispatcherImpl.dispatch(BasicOperationService.java:569)
	at com.hazelcast.spi.impl.BasicOperationScheduler$OperationThread.process(BasicOperationScheduler.java:466)
	at com.hazelcast.spi.impl.BasicOperationScheduler$OperationThread.doRun(BasicOperationScheduler.java:458)
	at com.hazelcast.spi.impl.BasicOperationScheduler$OperationThread.run(BasicOperationScheduler.java:432)
	at ------ End remote and begin local stack-trace ------.(Unknown Source)
	at com.hazelcast.client.spi.impl.ClientCallFuture.resolveResponse(ClientCallFuture.java:201)
	at com.hazelcast.client.spi.impl.ClientCallFuture.get(ClientCallFuture.java:142)
	at com.hazelcast.client.spi.impl.ClientCallFuture.get(ClientCallFuture.java:118)
	at com.hazelcast.client.cache.impl.HazelcastClientCacheManager.getCacheConfigFromPartition(HazelcastClientCacheManager.java:135)
	at com.hazelcast.cache.impl.AbstractHazelcastCacheManager.getCacheUnchecked(AbstractHazelcastCacheManager.java:196)
	at com.hazelcast.cache.impl.AbstractHazelcastCacheManager.getCache(AbstractHazelcastCacheManager.java:175)
	at com.hazelcast.cache.impl.AbstractHazelcastCacheManager.getCache(AbstractHazelcastCacheManager.java:44)
	at com.hazelcast.simulator.tests.icache.EvictionICacheTest.setup(EvictionICacheTest.java:98)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.hazelcast.simulator.utils.ReflectionUtils.invokeMethod(ReflectionUtils.java:29)
	at com.hazelcast.simulator.worker.TestContainer.setup(TestContainer.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.hazelcast.simulator.worker.WorkerCommandRequestProcessor$WorkerCommandRequestProcessorThread$2.doRun(WorkerCommandRequestProcessor.java:260)
	at com.hazelcast.simulator.worker.WorkerCommandRequestProcessor$CommandThread.run(WorkerCommandRequestProcessor.java:326)

]
```

from worker logs:
```
--------------------------- Initializing test test2 ---------------------------
TestCase{
      id=test2
    , class=com.hazelcast.simulator.tests.icache.EvictionICacheTest
}
INFO  2015-03-20 10:22:25,954 [Thread-1] com.hazelcast.simulator.worker.WorkerCommandRequestProcessor: --------------------------- Starting test2.setup() ---------------------------
FATAL 2015-03-20 10:22:26,019 [Thread-1] com.hazelcast.simulator.worker.WorkerCommandRequestProcessor: --------------------------- Failed test2.setup() ---------------------------
WARN  2015-03-20 10:22:26,020 [Thread-1] com.hazelcast.simulator.utils.ExceptionReporter: Exception #1 detected
java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.hash(ConcurrentHashMap.java:333)
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:988)
	at com.hazelcast.config.Config.lookupByPattern(Config.java:884)
	at com.hazelcast.config.Config.findCacheConfig(Config.java:251)
	at com.hazelcast.cache.impl.AbstractCacheService.findCacheConfig(AbstractCacheService.java:235)
	at com.hazelcast.cache.impl.operation.CacheGetConfigOperation.run(CacheGetConfigOperation.java:55)
	at com.hazelcast.spi.impl.BasicOperationService$OperationHandler.handle(BasicOperationService.java:733)
	at com.hazelcast.spi.impl.BasicOperationService$OperationHandler.access$500(BasicOperationService.java:709)
	at com.hazelcast.spi.impl.BasicOperationService.runOperationOnCallingThread(BasicOperationService.java:253)
	at com.hazelcast.spi.impl.BasicInvocation.doInvokeLocal(BasicInvocation.java:280)
	at com.hazelcast.spi.impl.BasicInvocation.doInvoke(BasicInvocation.java:262)
	at com.hazelcast.spi.impl.BasicInvocation.invoke(BasicInvocation.java:229)
	at com.hazelcast.spi.impl.BasicInvocationBuilder.invoke(BasicInvocationBuilder.java:45)
	at com.hazelcast.client.impl.client.PartitionClientRequest.process(PartitionClientRequest.java:60)
	at com.hazelcast.client.impl.ClientEngineImpl$ClientPacketProcessor.processRequest(ClientEngineImpl.java:434)
	at com.hazelcast.client.impl.ClientEngineImpl$ClientPacketProcessor.run(ClientEngineImpl.java:353)
	at com.hazelcast.spi.impl.BasicOperationService$BasicDispatcherImpl.dispatch(BasicOperationService.java:569)
	at com.hazelcast.spi.impl.BasicOperationScheduler$OperationThread.process(BasicOperationScheduler.java:466)
	at com.hazelcast.spi.impl.BasicOperationScheduler$OperationThread.doRun(BasicOperationScheduler.java:458)
	at com.hazelcast.spi.impl.BasicOperationScheduler$OperationThread.run(BasicOperationScheduler.java:432)
	at ------ End remote and begin local stack-trace ------.(Unknown Source)
	at com.hazelcast.client.spi.impl.ClientCallFuture.resolveResponse(ClientCallFuture.java:201)
	at com.hazelcast.client.spi.impl.ClientCallFuture.get(ClientCallFuture.java:142)
	at com.hazelcast.client.spi.impl.ClientCallFuture.get(ClientCallFuture.java:118)
	at com.hazelcast.client.cache.impl.HazelcastClientCacheManager.getCacheConfigFromPartition(HazelcastClientCacheManager.java:135)
	at com.hazelcast.cache.impl.AbstractHazelcastCacheManager.getCacheUnchecked(AbstractHazelcastCacheManager.java:196)
	at com.hazelcast.cache.impl.AbstractHazelcastCacheManager.getCache(AbstractHazelcastCacheManager.java:175)
	at com.hazelcast.cache.impl.AbstractHazelcastCacheManager.getCache(AbstractHazelcastCacheManager.java:44)
	at com.hazelcast.simulator.tests.icache.EvictionICacheTest.setup(EvictionICacheTest.java:98)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.hazelcast.simulator.utils.ReflectionUtils.invokeMethod(ReflectionUtils.java:29)
	at com.hazelcast.simulator.worker.TestContainer.setup(TestContainer.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.hazelcast.simulator.worker.WorkerCommandRequestProcessor$WorkerCommandRequestProcessorThread$2.doRun(WorkerCommandRequestProcessor.java:260)
	at com.hazelcast.simulator.worker.WorkerCommandRequestProcessor$CommandThread.run(WorkerCommandRequestProcessor.java:326)
INFO  2015-03-20 10:22:27,962 [Thread-2] com.hazelcast.simulator.worker.WorkerCommandRequestProcessor: --------------------------- Starting test2.localWarmup() ---------------------------
INFO  2015-03-20 10:22:27,962 [Thread-2] com.hazelcast.simulator.worker.WorkerCommandRequestProcessor: --------------------------- Finished test2.localWarmup() ---------------------------
INFO  2015-03-20 10:22:32,012 [WorkerCommandRequestProcessorThread] com.hazelcast.simulator.worker.WorkerCommandRequestProcessor: --------------------------- Starting performance monitoring ---------------------------
INFO  2015-03-20 10:22:32,012 [Thread-3] com.hazelcast.simulator.worker.WorkerCommandRequestProcessor: --------------------------- Starting test2.run() ---------------------------
WARN  2015-03-20 10:22:32,015 [Thread-3] com.hazelcast.simulator.utils.ExceptionReporter: Exception #2 detected
java.lang.IllegalStateException: Sum of operation probabilities should be exactly 1.0, but is 0.000000
	at com.hazelcast.simulator.worker.selector.OperationSelectorBuilder.probabilityMismatch(OperationSelectorBuilder.java:95)
	at com.hazelcast.simulator.worker.selector.OperationSelectorBuilder.build(OperationSelectorBuilder.java:82)
	at com.hazelcast.simulator.tests.icache.EvictionICacheTest$WorkerThread.<init>(EvictionICacheTest.java:129)
	at com.hazelcast.simulator.tests.icache.EvictionICacheTest$WorkerThread.<init>(EvictionICacheTest.java:128)
	at com.hazelcast.simulator.tests.icache.EvictionICacheTest.run(EvictionICacheTest.java:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.hazelcast.simulator.utils.ReflectionUtils.invokeMethod(ReflectionUtils.java:29)
	at com.hazelcast.simulator.worker.TestContainer.run(TestContainer.java:151)
	at com.hazelcast.simulator.worker.WorkerCommandRequestProcessor$WorkerCommandRequestProcessorThread$1.doRun(WorkerCommandRequestProcessor.java:198)
	at com.hazelcast.simulator.worker.WorkerCommandRequestProcessor$CommandThread.run(WorkerCommandRequestProcessor.java:326)
```

**Comment by pveentjer** [comment]
This is not a bug in HZ. You have a bug in your configuration, which causes a problem in the stabilizer. You have not configured the propabilities correctly.

**Comment by cherednichenko** [comment]
Ok. I'll try BUT I just picked up default test and configuration and didn't change anything actually :)

But you're right - it needs to be re-tested.

**Comment by pveentjer** [comment]
Probably the default configuration of that test is broken because of a lot of changes in the test framework recently.

**Comment by cherednichenko** [comment]
Yeap, make sense.

Seems we need to re-run all tests and check results.

**Comment by cherednichenko** [comment]
As we found with Peter, there are a couple bugs:
1 - we don't provide a good name for the cache (base name) that is the error in our test.
I actually tried to fix it by adding the following properties to the test BUT the result was the same (but for Peter it worked somehow seems):
```
test2@class=com.hazelcast.simulator.tests.icache.EvictionICacheTest
test2@basename=foobar
```
2 - they should provide an argument check because they continue with creating the cache while a null argument is passed in (I'm going actually to create unit tests for last one.)

**Comment by serkan-ozal** [comment]
Hi @cherednichenko ,

I can't understand the problem in this issue. What should I do for this issue?

**Comment by cherednichenko** [comment]
@serkan-ozal just run that Simulator test - that's it. :)

**Comment by serkan-ozal** [comment]
I think the problem is about somehow `basename` property is not binded (maybe because of simulator test configuration issue) to test case. Especially this error `java.lang.IllegalStateException: Sum of operation probabilities should be exactly 1.0, but is 0.000000` supports my thoughts about this issue. So at the moment, I don't think the issue is about our JCache implementation.

**Comment by Danny-Hazelcast** [comment]
This issue I caused by,  not defining a basename  in the test.properties file when running this test.
in the source code of the  EvictionICacheTest   we can see  basename is null by default.  which means this test must define a basename in the test.properties file.

over the past few days,  while looking into a different issue  i have run these  EvictionICacheTest ' s

icacheMaxSmall@class=com.hazelcast.simulator.tests.icache.EvictionICacheTest
icacheMaxSmall@basename=maxCachSmall1

icacheMaxMediume@class=com.hazelcast.simulator.tests.icache.EvictionICacheTest
icacheMaxMediume@basename=maxCachMediume1

icacheMaxLarge@class=com.hazelcast.simulator.tests.icache.EvictionICacheTest
icacheMaxLarge@basename=maxCachLarge1 


these have run hundreds of times all passing

**Comment by Danny-Hazelcast** [comment]
also you can check the default hazelcast xml file for simulator, you will find   cache's with the names 

maxCachSmall1
maxCachMediume1
maxCachLarge1

defined with specific properties,  running this test on a map which dose not have a max size police defined, is not very meaning ful
