### ISSUE TITLE
NPE Slow operation detector

### ISSUE THREAD

**Issue by pveentjer** [hazelcast/hazelcast#4855]
I think it is caused by a data race. 

* So the OperationRunner.currentTask is seen as slow.
* The operation completes, so current task is null
* The SlowOperationLog is created by accessing the OperationRunner.currentTask. 
which leads to the NPE. 

So make sure you take a 'snapshot' of reality that is valid instead of dealing with something that moves underneath your feet. In most cases storing the operation in a local variable (and passing it around) is the best approach to deal with this.

Could also be that something else is happening :)

```
Exception in thread "hz._hzInstance_39_dev.SlowOperationDetectorThread" java.lang.NullPointerException
	at com.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationLog.<init>(SlowOperationLog.java:59)
	at com.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationDetector$DetectorThread.getOrCreateSlowOperationLog(SlowOperationDetector.java:206)
	at com.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationDetector$DetectorThread.scanOperationRunner(SlowOperationDetector.java:184)
	at com.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationDetector$DetectorThread.scan(SlowOperationDetector.java:157)
	at com.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationDetector$DetectorThread.run(SlowOperationDetector.java:138)
```

**Comment by Donnerbart** [comment]
Could someone please merge #4827 before I fix this issue?
