### ISSUE TITLE
Out of memory on management center version 3.4.1

### ISSUE THREAD

**Issue by Belkacem** [hazelcast/hazelcast#4863]
Hi,
I'm getting an out of memory on management center, here's the stack trace.
Cheers
Belkacem

Hazelcast Management Center successfully started
2015-03-19 11:45:49.390:INFO:oejs.AbstractConnector:Started SelectChannelConnector@0.0.0.0:8090
Exception in thread "qtp23637981-236" Exception in thread "qtp23637981-105" Exception in thread "qtp23637981-195" java.lang.OutOfMemoryError: Java heap space
	at org.eclipse.jetty.util.log.StdErrLog.warn(StdErrLog.java:292)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:698)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Unknown Source)
java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
2015-03-21 23:00:24.361:WARN:oejs.ServletHandler:Error for /root/collector.do
java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOfRange(Unknown Source)
	at java.lang.String.<init>(Unknown Source)
	at com.hazelcast.com.eclipsesource.json.JsonParser.endCapture(JsonParser.java:354)
	at com.hazelcast.com.eclipsesource.json.JsonParser.readNumber(JsonParser.java:257)
	at com.hazelcast.com.eclipsesource.json.JsonParser.readValue(JsonParser.java:95)
	at com.hazelcast.com.eclipsesource.json.JsonParser.readArray(JsonParser.java:110)
	at com.hazelcast.com.eclipsesource.json.JsonParser.readValue(JsonParser.java:81)
	at com.hazelcast.com.eclipsesource.json.JsonParser.readObject(JsonParser.java:134)
	at com.hazelcast.com.eclipsesource.json.JsonParser.readValue(JsonParser.java:83)
	at com.hazelcast.com.eclipsesource.json.JsonParser.readObject(JsonParser.java:134)
	at com.hazelcast.com.eclipsesource.json.JsonParser.readValue(JsonParser.java:83)
	at com.hazelcast.com.eclipsesource.json.JsonParser.readObject(JsonParser.java:134)
	at com.hazelcast.com.eclipsesource.json.JsonParser.readValue(JsonParser.java:83)
	at com.hazelcast.com.eclipsesource.json.JsonParser.readObject(JsonParser.java:134)
	at com.hazelcast.com.eclipsesource.json.JsonParser.readValue(JsonParser.java:83)
	at com.hazelcast.com.eclipsesource.json.JsonParser.parse(JsonParser.java:62)
	at com.hazelcast.com.eclipsesource.json.JsonValue.readFrom(JsonValue.java:105)
	at com.hazelcast.com.eclipsesource.json.JsonObject.readFrom(JsonObject.java:138)
	at com.hazelcast.webmonitor.servlet.CollectorServlet.handleRequest(CollectorServlet.java:37)
	at org.springframework.web.context.support.HttpRequestHandlerServlet.service(HttpRequestHandlerServlet.java:68)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:686)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1494)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:186)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:160)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:343)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:260)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1474)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:499)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
2015-03-21 23:00:24.361:WARN:oejs.AbstractConnector:
java.lang.IllegalArgumentException: port out of range:695486520
	at java.net.InetSocketAddress.checkPort(Unknown Source)
	at java.net.InetSocketAddress.<init>(Unknown Source)
	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
	at sun.nio.ch.ServerSocketChannelImpl.accept(Unknown Source)
	at org.eclipse.jetty.server.nio.SelectChannelConnector.accept(SelectChannelConnector.java:109)
	at org.eclipse.jetty.server.AbstractConnector$Acceptor.run(AbstractConnector.java:938)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Unknown Source)
Exception in thread "qtp23637981-12" 2015-03-21 23:00:36.540:WARN:oejs.ServletHandler:Error for /root/collector.do
java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
Exception in thread "qtp23637981-13"

**Comment by emrahkocaman** [comment]
Hi @Belkacem, 
This behaviour is not reproducible on our side.
Could you please provide a heap dump? (You may start your jvm with `-XX:+HeapDumpOnOutOfMemoryError` parameter)
Also, you may need to increase your heap size depending on your cluster size and data structure count.

**Comment by emrahkocaman** [comment]
Closing this issue, please feel free to reopen it when you've additional info.
