### ISSUE TITLE
CachingProvider does not honor custom URI

### ISSUE THREAD

**Issue by snicoll** [hazelcast/hazelcast#4943]
The JSR-107 spec states in section 10.1.1 that

> For example an implementation may permit a URI to be used as the location of a configuration file,
say for pre-configured caches.
cachingProvider.getCacheManager(“/sample/ConfigurationFile.xml”);

It seems that Hazelcast ignores a custom URI and actually even fail if you try to call it with one. Debugging on 3.4.1 it ends up in  `HazelcastServerCachingProvider#instanceFromProperties` that looks for the `hazelcast.config.location` or `hazelcast.instance.name` property and if none is set just returns `null` as a provider. 

This latter fails with a null check:

```
Caused by: javax.cache.CacheException: Error opening URI [file:/Users/snicoll/workspace/pivotal/spring-boot/spring-boot-autoconfigure/target/test-classes/org/springframework/boot/autoconfigure/cache/hazelcast-specific.xml]
	at com.hazelcast.cache.impl.AbstractHazelcastCachingProvider.getCacheManager(AbstractHazelcastCachingProvider.java:89)
	at com.hazelcast.cache.impl.AbstractHazelcastCachingProvider.getCacheManager(AbstractHazelcastCachingProvider.java:113)
	at com.hazelcast.cache.HazelcastCachingProvider.getCacheManager(HazelcastCachingProvider.java:153)
	at org.springframework.boot.autoconfigure.cache.JCacheCacheConfiguration.createCacheManager(JCacheCacheConfiguration.java:87)
	at org.springframework.boot.autoconfigure.cache.JCacheCacheConfiguration.cacheManager(JCacheCacheConfiguration.java:71)
	at org.springframework.boot.autoconfigure.cache.JCacheCacheConfiguration$$EnhancerBySpringCGLIB$$9bd583bb.CGLIB$cacheManager$0(<generated>)
	at org.springframework.boot.autoconfigure.cache.JCacheCacheConfiguration$$EnhancerBySpringCGLIB$$9bd583bb$$FastClassBySpringCGLIB$$1a319b0a.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:309)
	at org.springframework.boot.autoconfigure.cache.JCacheCacheConfiguration$$EnhancerBySpringCGLIB$$9bd583bb.cacheManager(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
	... 90 more
Caused by: java.lang.NullPointerException: hazelcastInstance cannot be null
	at com.hazelcast.util.ValidationUtil.checkNotNull(ValidationUtil.java:31)
	at com.hazelcast.cache.impl.AbstractHazelcastCacheManager.<init>(AbstractHazelcastCacheManager.java:68)
	at com.hazelcast.cache.impl.HazelcastServerCacheManager.<init>(HazelcastServerCacheManager.java:58)
	at com.hazelcast.cache.impl.HazelcastServerCachingProvider.createHazelcastCacheManager(HazelcastServerCachingProvider.java:78)
	at com.hazelcast.cache.impl.HazelcastServerCachingProvider.createHazelcastCacheManager(HazelcastServerCachingProvider.java:42)
	at com.hazelcast.cache.impl.AbstractHazelcastCachingProvider.getCacheManager(AbstractHazelcastCachingProvider.java:86)
	... 104 more
```

Looking at the code the `URI` is completely ignored. Is it wrong to assume that the `URI` parameter is used to specify a custom configuration file?

If so, what is the meaning of the `CacheManager`'s URI in the hazelcast implementation?

Thanks

**Comment by noctarius** [comment]
Hey @snicoll,

Is it possible that you can offer a small unittest to be fixed from our side?

Thanks
Chris

**Comment by snicoll** [comment]
https://github.com/snicoll/hazelcast-4943

**Comment by serkan-ozal** [comment]
Hi @snicoll, sorry for late response.

Thanks for your test and reference to JCache spec document.

@noctarius is right. We use URI like a name or id since JCache spec doesn't enforce URI to be used for configuration file path as you stated. 

Here are some definitions about URI and cache manager relationship from spec:

> CacheManager instances, uniquely identified by implementation specific URIs ...

and 

> CacheManagers are logically identified by the URI ...

So as @noctarius suggested this http://docs.hazelcast.org/docs/3.4/manual/html/jcache-icache.html#configuration-scope is our way to specify configuration file

Regards.

**Comment by snicoll** [comment]
okay so your answer is that you won't support URI has a mean to configure the underlying hazelcast instance? Too bad that the spec is confusing in that area, a standard way of passing a reference to a configuration file isn't a crazy idea IMO.

Can you please fix the code to provider a better exception? (like a hint to the property to set?). Thanks!

**Comment by noctarius** [comment]
What do you mean? The property is a constant inside HazelcastCachingProvider, you don't need to know the property.

**Comment by snicoll** [comment]
I mean that:

```
Caused by: java.lang.NullPointerException: hazelcastInstance cannot be null
```

**Comment by noctarius** [comment]
Ah yeah, I think this is more like a bug not specific about the uri you gave

**Comment by snicoll** [comment]
Again. The spec states I _might_ set an URI. I do that and I get a `NullPointerException`. That's the only point I am making here. Thanks for the support!

**Comment by serkan-ozal** [comment]
@snicoll you are right. we should provide better (more informative) exception in this case

**Comment by serkan-ozal** [comment]
Hi @snicoll,

As a result, as far as I understand, more informative error message is sufficient for this issue like this:

```
Not available Hazelcast instance. Please specify your Hazelcast configuration file path via "HazelcastCachingProvider.HAZELCAST_CONFIG_LOCATION" property or 
specify Hazelcast instance name via "HazelcastCachingProvider.HAZELCAST_INSTANCE_NAME" property in "properties" parameter.
```

What do you think?

**Comment by snicoll** [comment]
Sounds good. Thanks!

**Comment by serkan-ozal** [comment]
closed via https://github.com/hazelcast/hazelcast/commit/6d7d1640a68ef9d1433234d2a0ad8443ec25aa7d
