### ISSUE TITLE
[TEST-FAILURE] SemaphoreSplitBrainTest.testSemaphoreSplitBrain

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#4954]
```
java.lang.IllegalStateException: Node failed to start!
	at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:122)
	at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:153)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:136)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:112)
	at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:58)
	at com.hazelcast.concurrent.semaphore.SemaphoreSplitBrainTest.testSemaphoreSplitBrain(SemaphoreSplitBrainTest.java:48)
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OracleJDK8/com.hazelcast$hazelcast/387/testReport/junit/com.hazelcast.concurrent.semaphore/SemaphoreSplitBrainTest/testSemaphoreSplitBrain/

**Comment by Donnerbart** [comment]
```
junit.framework.AssertionFailedError: expected:<1> but was:<0>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at junit.framework.Assert.assertEquals(Assert.java:241)
	at junit.framework.TestCase.assertEquals(TestCase.java:409)
	at com.hazelcast.concurrent.semaphore.SemaphoreSplitBrainTest.testSemaphoreSplitBrain(SemaphoreSplitBrainTest.java:93)
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-pr-builder/com.hazelcast$hazelcast/12541/testReport/junit/com.hazelcast.concurrent.semaphore/SemaphoreSplitBrainTest/testSemaphoreSplitBrain/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK8-Quality-Outreach/com.hazelcast$hazelcast/37/testReport/junit/com.hazelcast.concurrent.semaphore/SemaphoreSplitBrainTest/testSemaphoreSplitBrain/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OracleJDK8/com.hazelcast$hazelcast/411/testReport/junit/com.hazelcast.concurrent.semaphore/SemaphoreSplitBrainTest/testSemaphoreSplitBrain/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OracleJDK8/413/com.hazelcast$hazelcast/testReport/com.hazelcast.concurrent.semaphore/SemaphoreSplitBrainTest/testSemaphoreSplitBrain/

**Comment by eminn** [comment]
I am closing this issue since this is related to a network isolation problem which is fixed by CloudBees.
