### ISSUE TITLE
NoClassDefFoundError  com/hazelcast/executor/impl/client/RefreshableRequest

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#4968]
Hz version 3.5-SANPSHOT

I ran into this issue while terminating a cluster which happened to have,  a group of clients still connected to it.

java.lang.NoClassDefFoundError: com/hazelcast/executor/impl/client/RefreshableRequest
	at com.hazelcast.client.spi.impl.ClientInvocation.handleRetry(ClientInvocation.java:210)
	at com.hazelcast.client.spi.impl.ClientInvocation.notifyException(ClientInvocation.java:191)
	at com.hazelcast.client.spi.impl.ClientInvocation.notify(ClientInvocation.java:180)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.get(ClientInvocationFuture.java:108)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.get(ClientInvocationFuture.java:89)
	at com.hazelcast.client.spi.ClientProxy.invoke(ClientProxy.java:151)
	at com.hazelcast.client.proxy.ClientMapProxy.getAll(ClientMapProxy.java:664)
	at com.hazelcast.simulator.tests.wang.Wang2$Worker.getAllPhase(Wang2.java:190)
	at com.hazelcast.simulator.tests.wang.Wang2$Worker.run(Wang2.java:136)
	at java.lang.Thread.run(Thread.java:745)
	at com.hazelcast.simulator.test.utils.ThreadSpawner$DefaultThread.run(ThreadSpawner.java:89)

**Comment by sancar** [comment]
@Danny-Hazelcast 
We just removed that interface from 3.5-SNAPSHOT . It is probably related to maven loading old classes. A clean build probably will fix the issue.

**Comment by Danny-Hazelcast** [comment]
@sancar 

both client and server are using this version of 3.5-SNAPSHOT    f7b217e

INFO  2015-04-01 12:55:03,164 [main] com.hazelcast.system: [10.0.0.221]:5703 [workers] [3.5-SNAPSHOT] Hazelcast 3.5-SNAPSHOT (20150330 - f7b217e) starting at Address[10.0.0.221]:5703

Using artifact: /home/danny/.m2/repository/com/hazelcast/hazelcast-client/3.5-SNAPSHOT/hazelcast-client-3.5-SNAPSHOT.jar

**Comment by sancar** [comment]
I dont know how but it seems client.jar is in a state that it knows about Refreshable Request( behind the core hazelcast ).  But since it is removed in the core it can not be loaded. Does not "mvn clean" solve your problem?

**Comment by Danny-Hazelcast** [comment]
INFO  2015-04-01 13:39:52,323 [main] com.hazelcast.system: [10.0.0.221]:5704 [workers] [3.5-SNAPSHOT] Hazelcast 3.5-SNAPSHOT (20150401 - b301f7b) starting at Address[10.0.0.221]:5704

current head master works


and results in the normal 

```com.hazelcast.client.HazelcastClientNotActiveException: Connection refused
    at com.hazelcast.client.spi.impl.ClientInvocation.notify(ClientInvocation.java:176)
    at com.hazelcast.client.spi.impl.ClientInvocation.invoke(ClientInvocation.java:133)
    at com.hazelcast.client.spi.impl.ClientInvocation.run(ClientInvocation.java:154)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
    at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
    at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)
    at ------ End remote and begin local stack-trace ------.(Unknown Source)
    at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveResponse(ClientInvocationFuture.java:147)
    at com.hazelcast.client.spi.impl.ClientInvocationFuture.get(ClientInvocationFuture.java:114)
    at com.hazelcast.client.spi.impl.ClientInvocationFuture.get(ClientInvocationFuture.java:89)
    at com.hazelcast.client.spi.ClientProxy.invoke(ClientProxy.java:151)
    at com.hazelcast.client.proxy.ClientMapProxy.size(ClientMapProxy.java:1042)
    at com.hazelcast.simulator.tests.wang.Wang$Worker.mapSizePhase(Wang.java:214)
    at com.hazelcast.simulator.tests.wang.Wang$Worker.run(Wang.java:143)
    at java.lang.Thread.run(Thread.java:745)
    at com.hazelcast.simulator.test.utils.ThreadSpawner$DefaultThread.run(ThreadSpawner.java:89)```
