### ISSUE TITLE
[TEST-FAILURE] QueueSplitBrainTest.testQueueSplitBrain

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#4976]
```
java.lang.AssertionError: the size of the cluster is not correct expected:<3> but was:<2>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.test.HazelcastTestSupport$10.run(HazelcastTestSupport.java:544)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:617)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:540)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:536)
	at com.hazelcast.collection.impl.queue.QueueSplitBrainTest.testQueueSplitBrain(QueueSplitBrainTest.java:82)
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OracleJDK1.6/com.hazelcast$hazelcast/497/testReport/junit/com.hazelcast.collection.impl.queue/QueueSplitBrainTest/testQueueSplitBrain/

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x/com.hazelcast$hazelcast/2953/testReport/junit/com.hazelcast.collection.impl.queue/QueueSplitBrainTest/testQueueSplitBrain/

**Comment by muratayan** [comment]
I am working on this

**Comment by eminn** [comment]
I am closing this issue since this is related to a network isolation problem which is fixed by CloudBees.
