### ISSUE TITLE
[TEST-FAILURE] listNearCaches(com.hazelcast.cache.nearcache.NearCacheManagerTest)

### ISSUE THREAD

**Issue by serkan-ozal** [hazelcast/hazelcast#4989]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK8/519/

```
listNearCaches(com.hazelcast.cache.nearcache.NearCacheManagerTest)  Time elapsed: 0.046 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<TestNearCache-[1]> but was:<TestNearCache-[2]>
at org.junit.Assert.assertEquals(Assert.java:115)
at org.junit.Assert.assertEquals(Assert.java:144)
at com.hazelcast.cache.nearcache.NearCacheManagerTestSupport.doListNearCaches(NearCacheManagerTestSupport.java:60)
at com.hazelcast.cache.nearcache.NearCacheManagerTest.listNearCaches(NearCacheManagerTest.java:28)
```

**Comment by serkan-ozal** [comment]
fixed via https://github.com/hazelcast/hazelcast/commit/8321d80f566d0851b122ddbf0fc801a1cf4cc0ab
