### ISSUE TITLE
[TEST-FAILURE] ClientTxnTest.testTxnRollbackOnServerCrash

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#4995]
```
com.hazelcast.core.HazelcastException: java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:706)
	at sun.nio.ch.SocketAdaptor.connect(SocketAdaptor.java:127)
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.createSocketConnection(ClientConnectionManagerImpl.java:241)
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.getOrConnect(ClientConnectionManagerImpl.java:196)
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.getOrConnect(ClientConnectionManagerImpl.java:65)
	at com.hazelcast.client.spi.impl.ClientSmartInvocationServiceImpl.invokeOnPartitionOwner(ClientSmartInvocationServiceImpl.java:48)
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast$hazelcast-client/512/testReport/junit/com.hazelcast.client.txn/ClientTxnTest/testTxnRollbackOnServerCrash/

**Comment by sancar** [comment]
fixed via #5259
