### ISSUE TITLE
[TEST-FAILURE]  'dependencies.dependency.version' for org.jboss.arquillian.protocol:arquillian-protocol-servlet:jar is missing

### ISSUE THREAD

**Issue by mesutcelik** [hazelcast/hazelcast#5029]
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/523/
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/522/

```
00:54:40 java.io.IOException: remote file operation failed: /scratch/jenkins/workspace/Hazelcast-3.x-nightly at hudson.remoting.Channel@41483db2:52df410d: hudson.remoting.ProxyException: hudson.maven.MavenModuleSetBuild$MavenExecutionException: org.apache.maven.project.ProjectBuildingException: Some problems were encountered while processing the POMs:
00:54:40 [ERROR] Non-resolvable import POM: Could not find artifact org.jboss.arquillian:arquillian-bom:pom:1.0.3.Final in central (http://repo.cloudbees.com/content/repositories/central) @ line 83, column 25
00:54:40 [ERROR] 'dependencies.dependency.version' for org.jboss.arquillian.junit:arquillian-junit-container:jar is missing. @ line 108, column 21
00:54:40 [ERROR] 'dependencies.dependency.version' for org.jboss.arquillian.protocol:arquillian-protocol-servlet:jar is missing. @ line 172, column 21
00:54:40 
00:54:40 	at hudson.FilePath.act(FilePath.java:976)
00:54:40 	at hudson.FilePath.act(FilePath.java:958)
00:54:40 	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.parsePoms(MavenModuleSetBuild.java:953)
00:54:40 	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.doRun(MavenModuleSetBuild.java:681)
00:54:40 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:543)
00:54:40 	at hudson.model.Run.execute(Run.java:1745)
00:54:40 	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:529)
00:54:40 	at hudson.model.ResourceController.execute(ResourceController.java:89)
00:54:40 	at hudson.model.Executor.run(Executor.java:240)
00:54:40 Caused by: hudson.remoting.ProxyException: hudson.maven.MavenModuleSetBuild$MavenExecutionException: org.apache.maven.project.ProjectBuildingException: Some problems were encountered while processing the POMs:
00:54:40 [ERROR] Non-resolvable import POM: Could not find artifact org.jboss.arquillian:arquillian-bom:pom:1.0.3.Final in central (http://repo.cloudbees.com/content/repositories/central) @ line 83, column 25
00:54:40 [ERROR] 'dependencies.dependency.version' for org.jboss.arquillian.junit:arquillian-junit-container:jar is missing. @ line 108, column 21
00:54:40 [ERROR] 'dependencies.dependency.version' for org.jboss.arquillian.protocol:arquillian-protocol-servlet:jar is missing. @ line 172, column 21
00:54:40 
00:54:40 	at hudson.maven.MavenModuleSetBuild$PomParser.invoke(MavenModuleSetBuild.java:1357)
00:54:40 	at hudson.maven.MavenModuleSetBuild$PomParser.invoke(MavenModuleSetBuild.java:1091)
00:54:40 	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:2589)
00:54:40 	at hudson.remoting.UserRequest.perform(UserRequest.java:121)
00:54:40 	at hudson.remoting.UserRequest.perform(UserRequest.java:49)
00:54:40 	at hudson.remoting.Request$2.run(Request.java:324)
00:54:40 	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
00:54:40 	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
00:54:40 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
00:54:40 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
00:54:40 	at java.lang.Thread.run(Thread.java:745)
00:54:40 	at ......remote call to 52df410d(Native Method)
00:54:40 	at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1356)
00:54:40 	at hudson.remoting.UserResponse.retrieve(UserRequest.java:221)
00:54:40 	at hudson.remoting.Channel.call(Channel.java:752)
00:54:40 	at hudson.FilePath.act(FilePath.java:969)
00:54:40 	... 8 more
00:54:40 Caused by: hudson.remoting.ProxyException: org.apache.maven.project.ProjectBuildingException: Some problems were encountered while processing the POMs:
00:54:40 [ERROR] Non-resolvable import POM: Could not find artifact org.jboss.arquillian:arquillian-bom:pom:1.0.3.Final in central (http://repo.cloudbees.com/content/repositories/central) @ line 83, column 25
00:54:40 [ERROR] 'dependencies.dependency.version' for org.jboss.arquillian.junit:arquillian-junit-container:jar is missing. @ line 108, column 21
00:54:40 [ERROR] 'dependencies.dependency.version' for org.jboss.arquillian.protocol:arquillian-protocol-servlet:jar is missing. @ line 172, column 21
00:54:40 
00:54:40 	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:364)
00:54:40 	at hudson.maven.MavenEmbedder.buildProjects(MavenEmbedder.java:361)
00:54:40 	at hudson.maven.MavenEmbedder.readProjects(MavenEmbedder.java:331)
00:54:40 	at hudson.maven.MavenModuleSetBuild$PomParser.invoke(MavenModuleSetBuild.java:1294)
00:54:40 	at hudson.maven.MavenModuleSetBuild$PomParser.invoke(MavenModuleSetBuild.java:1091)
00:54:40 	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:2589)
00:54:40 	at hudson.remoting.UserRequest.perform(UserRequest.java:121)
00:54:40 	at hudson.remoting.UserRequest.perform(UserRequest.java:49)
00:54:40 	at hudson.remoting.Request$2.run(Request.java:324)
00:54:40 	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
00:54:40 	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
00:54:40 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
00:54:40 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
00:54:40 	at java.lang.Thread.run(Thread.java:745)
00:54:40 Archiving artifacts
```

**Comment by mesutcelik** [comment]
no recent failure. I will revisit this issue based on the feedback by Cloudbees...
