### ISSUE TITLE
[TEST-FAILURE] MapLoaderTest.testMapLoaderLoadUpdatingIndex

### ISSUE THREAD

**Issue by mesutcelik** [hazelcast/hazelcast#5035]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK6/499/com.hazelcast$hazelcast/testReport/com.hazelcast.map.mapstore/MapLoaderTest/testMapLoaderLoadUpdatingIndex/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-OracleJDK1.6/com.hazelcast$hazelcast/247/testReport/junit/com.hazelcast.map.mapstore/MapLoaderTest/testMapLoaderLoadUpdatingIndex/

**Comment by jerrinot** [comment]
The issue has the same root cause as #5393

**Comment by jerrinot** [comment]
There is another possible root cause - there is a fixed 3s timeout in `map.destroy()` 
I can reproduce it in 100% of cases using 8dad05f3dd4d8e539d606809acdda15c2e874007

**Comment by gurbuzali** [comment]
closed via https://github.com/hazelcast/hazelcast/pull/5433

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: call-count of loadAllKeys method is problematic expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.map.mapstore.MapLoaderTest$4.run(MapLoaderTest.java:214)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:828)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:842)
	at com.hazelcast.map.mapstore.MapLoaderTest.assertLoadAllKeysCount(MapLoaderTest.java:211)
	at com.hazelcast.map.mapstore.MapLoaderTest.testMapLoaderLoadUpdatingIndex(MapLoaderTest.java:124)
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OracleJDK1.6/com.hazelcast$hazelcast/698/testReport/junit/com.hazelcast.map.mapstore/MapLoaderTest/testMapLoaderLoadUpdatingIndex/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-OracleJDK1.7/com.hazelcast$hazelcast/180/testReport/junit/com.hazelcast.map.mapstore/MapLoaderTest/testMapLoaderLoadUpdatingIndex/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x/com.hazelcast$hazelcast/3949/testReport/junit/com.hazelcast.map.mapstore/MapLoaderTest/testMapLoaderLoadUpdatingIndex/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OracleJDK1.7/com.hazelcast$hazelcast/280/testReport/junit/com.hazelcast.map.mapstore/MapLoaderTest/testMapLoaderLoadUpdatingIndex/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-OracleJDK1.7/com.hazelcast$hazelcast/289/testReport/junit/com.hazelcast.map.mapstore/MapLoaderTest/testMapLoaderLoadUpdatingIndex/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: call-count of loadAllKeys method is problematic expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.map.mapstore.MapLoaderTest$4.run(MapLoaderTest.java:214)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:825)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:839)
	at com.hazelcast.map.mapstore.MapLoaderTest.assertLoadAllKeysCount(MapLoaderTest.java:211)
	at com.hazelcast.map.mapstore.MapLoaderTest.testMapLoaderLoadUpdatingIndex(MapLoaderTest.java:124)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK1.6/com.hazelcast$hazelcast/719/testReport/junit/com.hazelcast.map.mapstore/MapLoaderTest/testMapLoaderLoadUpdatingIndex/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.6/com.hazelcast$hazelcast/748/testReport/junit/com.hazelcast.map.mapstore/MapLoaderTest/testMapLoaderLoadUpdatingIndex/

**Comment by Donnerbart** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-pr-builder/com.hazelcast$hazelcast/16855/testReport/junit/com.hazelcast.map.mapstore/MapLoaderTest/testMapLoaderLoadUpdatingIndex/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK1.6/com.hazelcast$hazelcast/728/testReport/junit/com.hazelcast.map.mapstore/MapLoaderTest/testMapLoaderLoadUpdatingIndex/

**Comment by hasancelik** [comment]
**maintenance**
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-OracleJDK8/com.hazelcast$hazelcast/310/testReport/junit/com.hazelcast.map.mapstore/MapLoaderTest/testMapLoaderLoadUpdatingIndex/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK1.6/com.hazelcast$hazelcast/733/testReport/junit/com.hazelcast.map.mapstore/MapLoaderTest/testMapLoaderLoadUpdatingIndex/

**Comment by jerrinot** [comment]
It's a race between query operations and join (finalization?). 
It's not particularly easy to reproduce it; I can increase likely-hood of the issue by:
1. decreasing generic partition thread count to 1
2. removing the sleep at https://github.com/jerrinot/hazelcast/blob/3a6371a4201d82e46592b4d56816f5d6487d05d7/hazelcast/src/test/java/com/hazelcast/map/impl/query/QueryIndexMigrationTest.java#L251 <--- this will increase chance of the clash. 

Theory: 
Query operations are occupying generic thread(s) -> Cluster Join can't be finalized. However because join is not finalized then `QueryPartitionOperation` can't be executed(?). The joins eventually times out and cluster is unblocked: https://github.com/jerrinot/hazelcast/blob/a1851f7a8598745035f9b64eec43d93d4de5bd32/hazelcast/src/main/java/com/hazelcast/cluster/impl/ClusterJoinManager.java#L514 However the test timeout is just 1 minute -> test failure. 

The test has timeout set to 1 minutes. I believe increasing its timeout is a sufficient workaround for now. Real solution could be introduciton of a dedicated threadpool for cluster management  operations?

**Comment by sancar** [comment]
Also failed in maintenance branch. 
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-pr-builder/17145/console
```
Failed tests: 
18:36:19   MapLoaderTest.testMapLoaderLoadUpdatingIndex:123->assertLoadAllKeysCount:210->HazelcastTestSupport.assertTrueEventually:751->HazelcastTestSupport.assertTrueEventually:737 call-count of loadAllKeys method is problematic expected:<1> but was:<0>
```

I ignored the test in maintenance branch also.

**Comment by tombujok** [comment]
OK. I'm working on it. It looks like a dead-lock...

**Comment by hasancelik** [comment]
ignored by #6822

**Comment by jerrinot** [comment]
this seems to be quite easy to reproduce with some `@Repeat` and 
```java
config.setProperty(GroupProperty.GENERIC_OPERATION_THREAD_COUNT, "1");
config.setProperty(GroupProperty.PARTITION_OPERATION_THREAD_COUNT, "1");
```

**Comment by jerrinot** [comment]
**Analysis**
The [test](https://github.com/jerrinot/hazelcast/blob/ecb3ed2f9443a5f9066667af773952df5473a246/hazelcast/src/test/java/com/hazelcast/map/mapstore/MapLoaderTest.java#L103) has 2 parts separated by [`map.destroy()`](https://github.com/jerrinot/hazelcast/blob/ecb3ed2f9443a5f9066667af773952df5473a246/hazelcast/src/test/java/com/hazelcast/map/mapstore/MapLoaderTest.java#L122)

In the 1st part the MapLoader [`loadAllKeys()`](https://github.com/jerrinot/hazelcast/blob/ecb3ed2f9443a5f9066667af773952df5473a246/hazelcast/src/test/java/com/hazelcast/map/mapstore/MapLoaderTest.java#L295) returns empty set as `preloadValues` flag is false -> The [`loadAllKeysCallCount`](https://github.com/jerrinot/hazelcast/blob/ecb3ed2f9443a5f9066667af773952df5473a246/hazelcast/src/test/java/com/hazelcast/map/mapstore/MapLoaderTest.java#L297) is not incremented. So far so good.

In the 2nd part the test destroys the map, [switches](https://github.com/jerrinot/hazelcast/blob/ecb3ed2f9443a5f9066667af773952df5473a246/hazelcast/src/test/java/com/hazelcast/map/mapstore/MapLoaderTest.java#L123) the `preloadValues` flag to `true`, [re-creates](https://github.com/jerrinot/hazelcast/blob/ecb3ed2f9443a5f9066667af773952df5473a246/hazelcast/src/test/java/com/hazelcast/map/mapstore/MapLoaderTest.java#L126) the map and [expects](https://github.com/jerrinot/hazelcast/blob/ecb3ed2f9443a5f9066667af773952df5473a246/hazelcast/src/test/java/com/hazelcast/map/mapstore/MapLoaderTest.java#L128) the `loadAllKeysCallCount` to be `1`. 

The issue is that the 1st part of the test creates bunch of `PartitionCheckIfLoadedOperation`. If the map is destroyed while some of the `PartitionCheckIfLoadedOperation` are still in-flight then they will [re-create](https://github.com/jerrinot/hazelcast/blob/505a913c89f29d0420aac2d356d24331de6cc701/hazelcast/src/main/java/com/hazelcast/map/impl/operation/PartitionCheckIfLoadedOperation.java#L55-L55) the RecordStore before the test thread switches the `preloadValues` flag to true. -> The keys will not be loaded from the MapStore and the [assertion](https://github.com/jerrinot/hazelcast/blob/ecb3ed2f9443a5f9066667af773952df5473a246/hazelcast/src/test/java/com/hazelcast/map/mapstore/MapLoaderTest.java#L128) will not be true. 

The seems to be a similar problem with `LoadStatusOperation` as it created the RecordStore if it does not exist.

Possible solution is the use `getExistingRecordStore()` instead of `geRecordStore()` which has the `getOrCreate()` semantic.

**Comment by gurbuzali** [comment]
+1 to `getExistingRecordStore`

**Comment by jerrinot** [comment]
it's not that easy. as it's used to trigger loading in some cases.

**Comment by jerrinot** [comment]
I'm moving this one to 3.7 as discussed
