### ISSUE TITLE
[TEST-FAILURE] Client AvgAggregationTest Timeout

### ISSUE THREAD

**Issue by mesutcelik** [hazelcast/hazelcast#5074]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.7/525/artifact/hazelcast-client/target/surefire-reports/com.hazelcast.client.mapreduce.aggregation.AvgAggregationTest-output.txt

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x/3029/console

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK8/534/console

**Comment by sancar** [comment]
Closing this one since it did not failed over 1 month.

**Comment by bilalyasar** [comment]
new timeout:
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK8-Quality-Outreach/90/console
```
01:56:10 Running com.hazelcast.client.mapreduce.aggregation.AvgAggregationTest
03:38:31 Build timed out (after 150 minutes). Marking the build as failed.
```

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK6/568/console

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK6/621/consoleFull

**Comment by hasancelik** [comment]
Related failure:
https://github.com/hazelcast/hazelcast/issues/5916

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.maintenance/949/console

**Comment by hasancelik** [comment]
```
org.junit.runners.model.TestTimedOutException: test timed out after 60000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:226)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1033)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1326)
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:282)
	at com.hazelcast.client.proxy.ClientMapReduceProxy$ClientCompletableFuture.get(ClientMapReduceProxy.java:207)
	at com.hazelcast.spi.impl.AbstractCompletableFuture.get(AbstractCompletableFuture.java:106)
	at com.hazelcast.client.proxy.ClientMapProxy.aggregate(ClientMapProxy.java:992)
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OracleJDK8/com.hazelcast$hazelcast-client/531/testReport/junit/com.hazelcast.client.mapreduce.aggregation/AvgAggregationTest/testBigDecimalAvgWithExtractor/

**Comment by jerrinot** [comment]
could we enable verbose GC log for tests?

**Comment by sancar** [comment]
Merging to https://github.com/hazelcast/hazelcast/issues/5916
