### ISSUE TITLE
SmallClusterTest Failures

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#5103]
com.hazelcast.executor.SmallClusterTest.submitToKeyOwner_callable
com.hazelcast.executor.SmallClusterTest.submitToMember_callable

```
org.junit.runners.model.TestTimedOutException: test timed out after 30000 milliseconds
    at java.lang.Object.wait(Native Method)
    at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.pollResponse(InvocationFuture.java:299)
    at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.waitForResponse(InvocationFuture.java:247)
    at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.get(InvocationFuture.java:224)
    at com.hazelcast.util.executor.DelegatingFuture.get(DelegatingFuture.java:70)
    at com.hazelcast.executor.SmallClusterTest.submitToKeyOwner_callable(SmallClusterTest.java:209)
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK9-Quality-Outreach/39/

**Comment by mdogan** [comment]
Closing.. not reproducible and not failing more than a month.

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.6/com.hazelcast$hazelcast/593/testReport/junit/com.hazelcast.executor/SmallClusterTest/submitToMember_callable/

**Comment by Donnerbart** [comment]
Increased test timeout of failing tests via https://github.com/hazelcast/hazelcast/commit/95feba9bcbbe81a7d7917f90dc6d691f304fb49a

**Comment by hasancelik** [comment]
com.hazelcast.executor.SmallClusterTest.submitToAllMembers_statefulCallable
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at org.apache.log4j.Category.callAppenders(Category.java:201)
	at org.apache.log4j.Category.forcedLog(Category.java:388)
	at org.apache.log4j.Category.log(Category.java:835)
	at com.hazelcast.logging.Log4jFactory$Log4jLogger.log(Log4jFactory.java:45)
	at com.hazelcast.logging.AbstractLogger.finest(AbstractLogger.java:30)
	at com.hazelcast.config.Config.lookupByPattern(Config.java:1299)
	at com.hazelcast.config.Config.findExecutorConfig(Config.java:762)
	at com.hazelcast.spi.impl.executionservice.impl.ExecutionServiceImpl$1.createNew(ExecutionServiceImpl.java:91)
	at com.hazelcast.spi.impl.executionservice.impl.ExecutionServiceImpl$1.createNew(ExecutionServiceImpl.java:88)
	at com.hazelcast.util.ConcurrencyUtil.getOrPutIfAbsent(ConcurrencyUtil.java:94)
	at com.hazelcast.spi.impl.executionservice.impl.ExecutionServiceImpl.getExecutor(ExecutionServiceImpl.java:215)
	at com.hazelcast.spi.impl.executionservice.impl.ExecutionServiceImpl.execute(ExecutionServiceImpl.java:241)
	at com.hazelcast.executor.impl.DistributedExecutorService.execute(DistributedExecutorService.java:109)
	at com.hazelcast.executor.impl.operations.AbstractCallableTaskOperation.run(AbstractCallableTaskOperation.java:98)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:186)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:373)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:400)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:532)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:517)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:488)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:202)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:59)
	at com.hazelcast.executor.impl.ExecutorServiceProxy.submitToMember(ExecutorServiceProxy.java:393)
	at com.hazelcast.executor.impl.ExecutorServiceProxy.submitToMembers(ExecutorServiceProxy.java:408)
	at com.hazelcast.executor.impl.ExecutorServiceProxy.submitToAllMembers(ExecutorServiceProxy.java:415)
	at com.hazelcast.executor.SmallClusterTest.submitToAllMembers_statefulCallable(SmallClusterTest.java:283)
```
com.hazelcast.executor.SmallClusterTest.submitToMember_callable
```
org.junit.runners.model.TestTimedOutException: test timed out after 60000 milliseconds
	at org.apache.log4j.Category.callAppenders(Category.java:201)
	at org.apache.log4j.Category.forcedLog(Category.java:388)
	at org.apache.log4j.Category.log(Category.java:835)
	at com.hazelcast.logging.Log4jFactory$Log4jLogger.log(Log4jFactory.java:45)
	at com.hazelcast.logging.AbstractLogger.finest(AbstractLogger.java:30)
	at com.hazelcast.config.Config.lookupByPattern(Config.java:1299)
	at com.hazelcast.config.Config.findExecutorConfig(Config.java:762)
	at com.hazelcast.spi.impl.executionservice.impl.ExecutionServiceImpl$1.createNew(ExecutionServiceImpl.java:91)
	at com.hazelcast.spi.impl.executionservice.impl.ExecutionServiceImpl$1.createNew(ExecutionServiceImpl.java:88)
	at com.hazelcast.util.ConcurrencyUtil.getOrPutIfAbsent(ConcurrencyUtil.java:94)
	at com.hazelcast.spi.impl.executionservice.impl.ExecutionServiceImpl.getExecutor(ExecutionServiceImpl.java:215)
	at com.hazelcast.spi.impl.executionservice.impl.ExecutionServiceImpl.execute(ExecutionServiceImpl.java:241)
	at com.hazelcast.executor.impl.DistributedExecutorService.execute(DistributedExecutorService.java:109)
	at com.hazelcast.executor.impl.operations.AbstractCallableTaskOperation.run(AbstractCallableTaskOperation.java:98)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:186)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:373)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:400)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:532)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:517)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:488)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:202)
	at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.invokeOnTarget(OperationServiceImpl.java:316)
	at com.hazelcast.executor.impl.ExecutorServiceProxy.submitToMember(ExecutorServiceProxy.java:300)
	at com.hazelcast.executor.SmallClusterTest.submitToMember_callable(SmallClusterTest.java:212)
```
com.hazelcast.executor.SmallClusterTest.submitToSeveralNodes_callable
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:315)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:153)
	at com.hazelcast.util.executor.DelegatingFuture.get(DelegatingFuture.java:83)
	at com.hazelcast.executor.SmallClusterTest.submitToSeveralNodes_callable(SmallClusterTest.java:167)

```
com.hazelcast.executor.SmallClusterTest.submitToAllMembers_runnable
```
java.lang.AssertionError: expected:<9> but was:<5>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.executor.SmallClusterTest.submitToAllMembers_runnable(SmallClusterTest.java:158)

```
com.hazelcast.executor.SmallClusterTest.executionCallback_notified
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:315)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:153)
	at com.hazelcast.util.executor.DelegatingFuture.get(DelegatingFuture.java:83)
	at com.hazelcast.executor.SmallClusterTest.executionCallback_notified(SmallClusterTest.java:72)
```
com.hazelcast.executor.SmallClusterTest.submitToAllMembers_callable
```
java.lang.AssertionError: expected:<9> but was:<5>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.executor.SmallClusterTest.submitToAllMembers_callable(SmallClusterTest.java:270)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.8/445/

**Comment by mdogan** [comment]
Last failure https://github.com/hazelcast/hazelcast/issues/5103#issuecomment-269179725 looks unusual. It's most probably affected by a slow environment.
