### ISSUE TITLE
ExecutorServiceTest.testInvokeAllTimeoutSuccess

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#5128]
```
java.lang.AssertionError: expected:<231> but was:<1000>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:555)
	at org.junit.Assert.assertEquals(Assert.java:542)
	at com.hazelcast.executor.ExecutorServiceTest.testInvokeAllTimeoutSuccess(ExecutorServiceTest.java:740)
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-IbmJDK1.7/com.hazelcast$hazelcast/215/testReport/junit/com.hazelcast.executor/ExecutorServiceTest/testInvokeAllTimeoutSuccess/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-IbmJDK1.7/com.hazelcast$hazelcast/241/testReport/junit/com.hazelcast.executor/ExecutorServiceTest/testInvokeAllTimeoutSuccess/

**Comment by Donnerbart** [comment]
```
Regression

com.hazelcast.executor.ExecutorServiceTest.testInvokeAllTimeoutSuccess

Failing for the past 1 build (Since Unstable#568 )
Took 0.16 sec.
Error Message

expected:<null> but was:<Task completed>
Stacktrace

java.lang.AssertionError: expected:<null> but was:<Task completed>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.executor.ExecutorServiceTest.testInvokeAllTimeoutSuccess(ExecutorServiceTest.java:836)
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OracleJDK8/com.hazelcast$hazelcast/568/testReport/junit/com.hazelcast.executor/ExecutorServiceTest/testInvokeAllTimeoutSuccess/

**Comment by hasancelik** [comment]
```
java.util.concurrent.CancellationException: null
	at com.hazelcast.executor.impl.DistributedExecutorService.cancel(DistributedExecutorService.java:114)
	at com.hazelcast.executor.impl.operations.CancellationOperation.run(CancellationOperation.java:52)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:172)
	at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.processOperation(OperationThread.java:198)
	at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.process(OperationThread.java:132)
	at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.doRun(OperationThread.java:124)
	at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.run(OperationThread.java:99)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK1.6/com.hazelcast$hazelcast/761/testReport/junit/com.hazelcast.executor/ExecutorServiceTest/testInvokeAllTimeoutSuccess/

**Comment by gurbuzali** [comment]
I've just increased the wait time to 15 seconds, let's see if it fails again
https://github.com/hazelcast/hazelcast/commit/843126a07f1ea0b6269255ffc68be099b8f567ce  

As a note:
Console shows that the test completed in less than 1 second
```
06:58:11 Running com.hazelcast.executor.ExecutorServiceTest
06:58:11 Tests run: 40, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.045 sec <<< FAILURE! - in 
```
This is very suspicious, it takes 10 seconds in my machine. it also shows `SpecificSetupTest` lasts less than 1 second too
```
06:58:11 Running com.hazelcast.executor.SpecificSetupTest
06:58:11 Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec - in com.hazelcast.executor.SpecificSetupTest
```
But it has a test which sleeps for 3 seconds in it. I believe there is a time-jump or something like that. this is from the same test log
```
06:56:36 Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.153 sec - in com.hazelcast.internal.metrics.metricsets.GarbageCollectionMetricSetTest
06:56:36 Running com.hazelcast.internal.metrics.metricsets.OperatingSystemMetricSetTest
06:58:09 Tests run: 6, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 1.384 sec - in com.hazelcast.internal.metrics.metricsets.OperatingSystemMetricSetTest
06:58:09 Running com.hazelcast.internal.metrics.metricsets.RuntimeMetricSetTest
06:58:09 Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in com.hazelcast.internal.metrics.metricsets.RuntimeMetricSetTest
```
As you can see logging time jumps from `06:56:36` to `06:58:09` but time elapsed for the tests shows very small amounts.
