### ISSUE TITLE
ClientMapProxy.entrySet() seems to have O(n²) complexity (all clients)

### ISSUE THREAD

**Issue by Donnerbart** [hazelcast/hazelcast#5130]
While writing tests for my unbounded return values feature I had massive problems with executing a simple `IMap.entrySet()` on the client side with about 150k entries in the map.

So I changed my failing test until I came up with the following code to measure the duration of several `IMap` methods on client side with a different number of server nodes as well as local and remote setup: https://gist.github.com/Donnerbart/ad25717a52b4521da221

These are the results:
![test1a](https://cloud.githubusercontent.com/assets/4196298/7253598/3020bc68-e83e-11e4-86e9-48118b7120b7.png)
![test1b](https://cloud.githubusercontent.com/assets/4196298/7253601/335fd350-e83e-11e4-83da-f2ddd6764081.png)
![test2a](https://cloud.githubusercontent.com/assets/4196298/7253605/364d5e7a-e83e-11e4-87ff-355ca969599c.png)
![test2b](https://cloud.githubusercontent.com/assets/4196298/7253611/3a361cd4-e83e-11e4-85d1-48c5955fa7c7.png)
![test3a](https://cloud.githubusercontent.com/assets/4196298/7253612/3a4e194c-e83e-11e4-940a-bf6f53e40200.png)
![test3b](https://cloud.githubusercontent.com/assets/4196298/7253621/41d48e30-e83e-11e4-9bdb-ffe71e8fb401.png)
![test4a](https://cloud.githubusercontent.com/assets/4196298/7253620/41d42ce2-e83e-11e4-99ed-d519f3a34193.png)
![test4b](https://cloud.githubusercontent.com/assets/4196298/7253623/41d58ab0-e83e-11e4-981a-4b58eadf85f7.png)
![test5a](https://cloud.githubusercontent.com/assets/4196298/7253624/41d573c2-e83e-11e4-9e96-896624dbb65e.png)
![test5b](https://cloud.githubusercontent.com/assets/4196298/7253622/41d52a98-e83e-11e4-982b-28210d0080a9.png)
![test6a](https://cloud.githubusercontent.com/assets/4196298/7253625/41d78720-e83e-11e4-9376-87b1fb22378e.png)
![test6b](https://cloud.githubusercontent.com/assets/4196298/7253626/41ef5a26-e83e-11e4-9bcf-eb1a9743477a.png)

The local setup were client and server nodes on the same machine. The remote setup were client on one and all server nodes on another machine.

**Comment by pveentjer** [comment]
Need to look at it, but good work. If you were not working yet for HZ I would certainly hire you :)

**Comment by Donnerbart** [comment]
With the new client it is even worse. I used the same test code (see gist link in the description) and the test crashes with a `TargetDisconnectedException` at just 2000 entries!
```
########################################################
IMap<Integer, Integer>
########################################################
Filling map from 0 to 100
IMap test with mapSize 100
--------------------------------------------------------
IMap.values() took 9 ms
IMap.values(predicate) took 10 ms
IMap.keySet() took 9 ms
IMap.keySet(predicate) took 4 ms
IMap.entrySet() took 11 ms
IMap.entrySet(predicate) took 10 ms
########################################################
Filling map from 100 to 500
IMap test with mapSize 500
--------------------------------------------------------
IMap.values() took 8 ms
IMap.values(predicate) took 7 ms
IMap.keySet() took 9 ms
IMap.keySet(predicate) took 6 ms
IMap.entrySet() took 9 ms
IMap.entrySet(predicate) took 8 ms
########################################################
Filling map from 500 to 750
IMap test with mapSize 750
--------------------------------------------------------
IMap.values() took 8 ms
IMap.values(predicate) took 7 ms
IMap.keySet() took 7 ms
IMap.keySet(predicate) took 8 ms
IMap.entrySet() took 11 ms
IMap.entrySet(predicate) took 12 ms
########################################################
Filling map from 750 to 1000
IMap test with mapSize 1000
--------------------------------------------------------
IMap.values() took 6 ms
IMap.values(predicate) took 5 ms
IMap.keySet() took 5 ms
IMap.keySet(predicate) took 5 ms
IMap.entrySet() took 7 ms
IMap.entrySet(predicate) took 6 ms
########################################################
Filling map from 1000 to 2000
IMap test with mapSize 2000
--------------------------------------------------------
IMap.values() took 5 ms
IMap.values(predicate) took 4 ms
IMap.keySet() took 6 ms
IMap.keySet(predicate) took 4 ms
May 4, 2015 6:47:37 PM com.hazelcast.client.connection.nio.ClientConnection
WARNING: Connection [/127.0.0.1:5701] lost. Reason: Socket explicitly closed
May 4, 2015 6:47:37 PM com.hazelcast.nio.tcp.TcpIpConnection
INFO: [172.16.16.200]:5701 [dev] [3.5-SNAPSHOT] Connection [Address[127.0.0.1]:53216] lost. Reason: java.io.IOException[Connection reset by peer]
May 4, 2015 6:47:37 PM com.hazelcast.core.LifecycleService
INFO: HazelcastClient[hz.client_0_dev][3.5-SNAPSHOT] is CLIENT_DISCONNECTED
May 4, 2015 6:47:37 PM com.hazelcast.nio.tcp.ReadHandler
WARNING: [172.16.16.200]:5701 [dev] [3.5-SNAPSHOT] hz._hzInstance_1_dev.IO.thread-in-0 Closing socket to endpoint Address[127.0.0.1]:53216, Cause:java.io.IOException: Connection reset by peer
May 4, 2015 6:47:37 PM com.hazelcast.nio.tcp.SocketAcceptor
INFO: [172.16.16.200]:5701 [dev] [3.5-SNAPSHOT] Accepting socket connection from /172.16.16.200:53848
May 4, 2015 6:47:37 PM com.hazelcast.client.ClientEndpointManager
INFO: [172.16.16.200]:5701 [dev] [3.5-SNAPSHOT] Destroying ClientEndpoint{conn=Connection [/127.0.0.1:5701 -> /127.0.0.1:53216], endpoint=Address[127.0.0.1]:53216, live=false, type=JAVA_CLIENT, principal='ClientPrincipal{uuid='6aa493f8-7572-448a-ad4d-899bb0fd4d44', ownerUuid='0d556e2f-9b0b-40ea-993c-47ba7f76b64e'}', firstConnection=true, authenticated=true}
May 4, 2015 6:47:37 PM com.hazelcast.client.impl.protocol.task.AuthenticationMessageTask
INFO: [172.16.16.200]:5701 [dev] [3.5-SNAPSHOT] Received auth from Connection [/172.16.16.200:5701 -> /172.16.16.200:53848], endpoint=null, live=true, type=JAVA_CLIENT, successfully authenticated
May 4, 2015 6:47:37 PM com.hazelcast.nio.tcp.TcpIpConnectionManager
INFO: [172.16.16.200]:5701 [dev] [3.5-SNAPSHOT] Established socket connection between /172.16.16.200:5701
May 4, 2015 6:47:37 PM com.hazelcast.client.spi.ClientPartitionService
SEVERE: Error while fetching cluster partition table!
java.util.concurrent.ExecutionException: com.hazelcast.spi.exception.TargetDisconnectedException
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveResponse(ClientInvocationFuture.java:169)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.get(ClientInvocationFuture.java:118)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.get(ClientInvocationFuture.java:93)
	at com.hazelcast.client.spi.impl.ClientPartitionServiceImpl.getPartitionsFrom(ClientPartitionServiceImpl.java:101)
	at com.hazelcast.client.spi.impl.ClientPartitionServiceImpl.getPartitions(ClientPartitionServiceImpl.java:90)
	at com.hazelcast.client.spi.impl.ClientPartitionServiceImpl.access$400(ClientPartitionServiceImpl.java:44)
	at com.hazelcast.client.spi.impl.ClientPartitionServiceImpl$RefreshTask.run(ClientPartitionServiceImpl.java:211)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:701)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)
Caused by: com.hazelcast.spi.exception.TargetDisconnectedException
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.get(ClientInvocationFuture.java:112)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.get(ClientInvocationFuture.java:93)
	at com.hazelcast.client.spi.impl.ClientPartitionServiceImpl.getPartitionsFrom(ClientPartitionServiceImpl.java:101)
	at com.hazelcast.client.spi.impl.ClientPartitionServiceImpl.getPartitions(ClientPartitionServiceImpl.java:90)
	at com.hazelcast.client.spi.impl.ClientPartitionServiceImpl.access$400(ClientPartitionServiceImpl.java:44)
	at com.hazelcast.client.spi.impl.ClientPartitionServiceImpl$RefreshTask.run(ClientPartitionServiceImpl.java:211)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:701)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)
	at ------ End remote and begin local stack-trace ------.(Unknown Source)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveResponse(ClientInvocationFuture.java:156)
	... 11 more

com.hazelcast.spi.exception.TargetDisconnectedException
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.get(ClientInvocationFuture.java:112)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.get(ClientInvocationFuture.java:93)
	at com.hazelcast.client.spi.ClientProxy.invoke(ClientProxy.java:147)
	at com.hazelcast.client.proxy.ClientMapProxy.entrySet(ClientMapProxy.java:828)
	at com.hazelcast.client.map.ClientMapPerformanceTest.callMethodsOnMap(ClientMapPerformanceTest.java:176)
	at com.hazelcast.client.map.ClientMapPerformanceTest.runTest(ClientMapPerformanceTest.java:93)
	at com.hazelcast.client.map.ClientMapPerformanceTest.testLocal_singleNode(ClientMapPerformanceTest.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
	at ------ End remote and begin local stack-trace ------.(Unknown Source)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveResponse(ClientInvocationFuture.java:156)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.get(ClientInvocationFuture.java:118)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.get(ClientInvocationFuture.java:93)
	at com.hazelcast.client.spi.ClientProxy.invoke(ClientProxy.java:147)
	at com.hazelcast.client.proxy.ClientMapProxy.entrySet(ClientMapProxy.java:828)
	at com.hazelcast.client.map.ClientMapPerformanceTest.callMethodsOnMap(ClientMapPerformanceTest.java:176)
	at com.hazelcast.client.map.ClientMapPerformanceTest.runTest(ClientMapPerformanceTest.java:93)
	at com.hazelcast.client.map.ClientMapPerformanceTest.testLocal_singleNode(ClientMapPerformanceTest.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)

May 4, 2015 6:47:37 PM com.hazelcast.core.LifecycleService
INFO: [172.16.16.200]:5701 [dev] [3.5-SNAPSHOT] Address[172.16.16.200]:5701 is SHUTTING_DOWN

Process finished with exit code 255
```

This easily explains the problems I have with the unbounded return values tests:
https://github.com/hazelcast/hazelcast/issues/5172
https://github.com/hazelcast/hazelcast/pull/5231

**Comment by Donnerbart** [comment]
I just removed the `entrySet()` calls to see how the performance of the `values() and keySet()` methods are. And the test get's stuck without any exception shortly over 2500 map entries:
```
########################################################
IMap<Integer, Integer>
########################################################
Filling map from 0 to 2400
IMap test with mapSize 2400
--------------------------------------------------------
IMap.values() took 18 ms
IMap.values(predicate) took 23 ms
IMap.keySet() took 14 ms
IMap.keySet(predicate) took 19 ms
########################################################
Filling map from 2400 to 2410
IMap test with mapSize 2410
--------------------------------------------------------
IMap.values() took 10 ms
IMap.values(predicate) took 10 ms
IMap.keySet() took 6 ms
IMap.keySet(predicate) took 8 ms
########################################################
Filling map from 2410 to 2420
IMap test with mapSize 2420
--------------------------------------------------------
IMap.values() took 6 ms
IMap.values(predicate) took 5 ms
IMap.keySet() took 5 ms
IMap.keySet(predicate) took 3 ms
########################################################
Filling map from 2420 to 2430
IMap test with mapSize 2430
--------------------------------------------------------
IMap.values() took 6 ms
IMap.values(predicate) took 2 ms
IMap.keySet() took 8 ms
IMap.keySet(predicate) took 3 ms
########################################################
Filling map from 2430 to 2440
IMap test with mapSize 2440
--------------------------------------------------------
IMap.values() took 6 ms
IMap.values(predicate) took 2 ms
IMap.keySet() took 5 ms
IMap.keySet(predicate) took 2 ms
########################################################
Filling map from 2440 to 2450
IMap test with mapSize 2450
--------------------------------------------------------
IMap.values() took 6 ms
IMap.values(predicate) took 3 ms
IMap.keySet() took 4 ms
IMap.keySet(predicate) took 5 ms
########################################################
Filling map from 2450 to 2460
IMap test with mapSize 2460
--------------------------------------------------------
IMap.values() took 4 ms
IMap.values(predicate) took 4 ms
IMap.keySet() took 5 ms
IMap.keySet(predicate) took 2 ms
########################################################
Filling map from 2460 to 2470
IMap test with mapSize 2470
--------------------------------------------------------
IMap.values() took 9 ms
IMap.values(predicate) took 2 ms
IMap.keySet() took 4 ms
IMap.keySet(predicate) took 2 ms
########################################################
Filling map from 2470 to 2480
IMap test with mapSize 2480
--------------------------------------------------------
IMap.values() took 2 ms
IMap.values(predicate) took 1 ms
IMap.keySet() took 2 ms
IMap.keySet(predicate) took 1 ms
########################################################
Filling map from 2480 to 2490
IMap test with mapSize 2490
--------------------------------------------------------
IMap.values() took 4 ms
IMap.values(predicate) took 2 ms
IMap.keySet() took 3 ms
IMap.keySet(predicate) took 1 ms
########################################################
Filling map from 2490 to 2500
IMap test with mapSize 2500
--------------------------------------------------------
IMap.values() took 3 ms
IMap.values(predicate) took 1 ms
IMap.keySet() took 4 ms
IMap.keySet(predicate) took 1 ms
########################################################
Filling map from 2500 to 2510
IMap test with mapSize 2510
--------------------------------------------------------
IMap.values() took 3 ms
IMap.values(predicate) took 1 ms
IMap.keySet() took 4 ms
IMap.keySet(predicate) took 3 ms
########################################################
Filling map from 2510 to 2520
IMap test with mapSize 2520
--------------------------------------------------------
```
There seems to be a major issue in those methods. This easily explains the problems I have with the unbounded return values tests (#5172 and #5231).

Just to be sure that I didn't mess up anything with my own test code, I just ran the `ClientMapBasicTest.testValues()` with an increased `int max = 23`. This test also fails with about 1200 map entries.

**Comment by Donnerbart** [comment]
Summary:

**Old client:** The `IMap.entySet()` method seems to have a O(n²) complexity. Also `IMap.entrySet(predicate)` has a non-ideal runtime with higher n. Beside that the performance of the query methods (`IMap.values(predicate)`, `IMap.keySet(predicate)`) and non-query methods (`IMap.values()`, `IMap.keySet()`) seem to be okay.

**New client:** All methods crash between 2000 and 2500 entries with a `TargetDisconnectedException`.

**Comment by Donnerbart** [comment]
`ClientMapBasicTest.testValues_withPredicate()` works fine even with 1,00,0000 entries in the map. So I assume the problem is not the map size (or iterating over a huge map), but the size of the response.

This would explain why a `IMap.values()` or `IMap.values(TruePredicate.INSTANCE)` fails, but the `IMap.values(new SQLPreciate(...))` with a single return value works.

**Comment by bwzhang2011** [comment]
@Donnerbart, did you communicate with @sancar  about this ? as the new client is about to released together with hz3.5 E.A

**Comment by pveentjer** [comment]
We'll include the old client.

**Comment by bwzhang2011** [comment]
@pveentjer, thanks for review. hope such could be resolved.

**Comment by Donnerbart** [comment]
Good news: The `TargetDisconnectedException` in the new client has gone. Kudos to the client team to fix this!

Bad news: The scalability of `entrySet()` seems to be the same for the new client.
```
########################################################
Filling map from 90000 to 100000
IMap test with mapSize 100000
--------------------------------------------------------
IMap.values() took 22 ms
IMap.values(predicate) took 52 ms
IMap.keySet() took 37 ms
IMap.keySet(predicate) took 61 ms
IMap.entrySet() took 52966 ms
IMap.entrySet(predicate) took 54352 ms
########################################################
```
When I have time I can try to get the graphs for all the different setups. But even from this snippet the trend should be visible. Also the `values()` and `keySet()` seem to perform very good in comparison to the old client.

**Comment by bwzhang2011** [comment]
@Donnerbart,  how could you make that picture to get the performance test cases ? would you mind sharing your experiences or skill for that, if we want to dig into some analysis for the API

**Comment by Donnerbart** [comment]
Since I didn't need to automate this I used LibreOffice. You can also use OpenOffice or Excel. I just copy & pasted the output of the test into the program.

If I would need to do this on a regular basis I would use at least a CSV format and maybe HdrHistogram. Or I would write a Simulator test for this and use Visualizer to compare the results of different runs: http://blog.hazelcast.com/2015/05/21/hazelcast-simulator-0-5-released/

**Comment by bwzhang2011** [comment]
@Donnerbart, thanks for your share. Maybe most of us should spare more time for hz-simulator for clustering testing and I will spare more time for hdrhistogram learning.

**Comment by bwzhang2011** [comment]
by the way, how does the solution of the new client towards the entry set complexity going on ? any response from the client team to be be confirmed ?

**Comment by sancar** [comment]
Moving this to 3.6 since Performance related protocol improvements are planned to 3.6

**Comment by bwzhang2011** [comment]
@sancar, any update with such issue ?

**Comment by Donnerbart** [comment]
Issue has been fixed with several PRs by migrating member, old and new client to use predicates for all methods. This was finally possible due to #6288 which reduced the traffic of the predicate methods so there is no performance impact by switching to them.

This specific test was not repeated, but the original nightly tests are now enabled which check for the query result limit. They skipped the entrySet() methods before, since they didn't finish in a reasonable time. Also the scope of the predicate usage and query result limit is checked by those nightly tests.
