### ISSUE TITLE
Value passed into ICompletableFuture.onResponse is not deserialized

### ISSUE THREAD

**Issue by youngm** [hazelcast/hazelcast#5158]
Hazelcast Version: 3.4.2
If this is a feature of ICompletableFuture then perhaps the type should be changed to *Data* instead of generic?
The example below throws this exception:
```
java.lang.ClassCastException: com.hazelcast.nio.serialization.DefaultData cannot be cast to java.lang.String
	at TestCompletableFuture$1.onResponse(TestCompletableFuture.java:1)
	at com.hazelcast.spi.impl.BasicInvocationFuture$1.run(BasicInvocationFuture.java:96)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)
```

```
		HazelcastInstance instance = Hazelcast.newHazelcastInstance();
		IMap<String, String> map = instance.getMap("map");
		map.set("key", "Some Value");
		ICompletableFuture<String> f = (ICompletableFuture<String>) map.getAsync("key");
		f.andThen(new ExecutionCallback<String>() {
			public void onResponse(String response) {
				System.out.println(response);
			}

			public void onFailure(Throwable t) {

			}
		});
		Hazelcast.shutdownAll();
```

**Comment by pveentjer** [comment]
Let me have a look

**Comment by pveentjer** [comment]
I'm going to move this issue to the 3.6 release. Although the behavior is not correct, the API is not intended to be used this way. I just verified with the ICache, and it works fine.

```
public class Main {

    public static void main(String[] args){
         HazelcastServerCachingProvider cachingProvider = createCachingProvider(new Config());
        CacheConfig config = new CacheConfig();
        config.setName("xmlCache").setTypes(String.class, String.class);
        ICache<String, String> cache = (ICache)cachingProvider.getCacheManager().createCache("xmlCache", config);
        cache.put("key", "Some Value");
        ICompletableFuture<String> f = cache.getAsync("key");
        f.andThen(new ExecutionCallback<String>() {
            public void onResponse(String response) {
                System.out.println(response);
            }

            public void onFailure(Throwable t) {

            }
        });
        Hazelcast.shutdownAll();
    }

    private static HazelcastServerCachingProvider createCachingProvider(Config hzConfig){
        HazelcastInstance hazelcastInstance = Hazelcast.newHazelcastInstance(hzConfig);
        HazelcastServerCachingProvider cachingProvider =
                HazelcastServerCachingProvider.createCachingProvider(hazelcastInstance);
        return cachingProvider;
    }
}
```

**Comment by mdogan** [comment]
I already fixed this, see: https://github.com/hazelcast/hazelcast/issues/5382

**Comment by jerrinot** [comment]
assigning to @mdogan as he has already sent a PR with a fix. #5382
