### ISSUE TITLE
[TEST-FAILURE] ClusterMembershipIntegrationTest failures

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#5164]
com.hazelcast.webmonitor.ClusterMembershipIntegrationTest.testMemberLeavingCluster
com.hazelcast.webmonitor.ClusterMembershipIntegrationTest.testMemberJoiningCluster

```
ava.lang.IllegalStateException: Node failed to start!
	at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:122)
	at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:153)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:136)
	at com.hazelcast.test.TestHazelcastInstanceFactory.newHazelcastInstance(TestHazelcastInstanceFactory.java:80)
	at com.hazelcast.webmonitor.ClusterMembershipIntegrationTest.testMemberLeavingCluster(ClusterMembershipIntegrationTest.java:125)
```
https://hazelcast-l337.ci.cloudbees.com/job/ManagementCenter-3.x/2306/

also from logs:
```
java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
	at com.hazelcast.test.TestNodeRegistry$MockConnection.readFromPacket(TestNodeRegistry.java:369)
	at com.hazelcast.test.TestNodeRegistry$MockConnection.write(TestNodeRegistry.java:351)
```
i saw such a NoSuchMethodError in other builds time to time. Maybe this failure doesn't related to hz.

**Comment by bilalyasar** [comment]
moved to https://github.com/hazelcast/management-center/issues/170
