### ISSUE TITLE
[TEST-FAILURE] SlowOperationDetector_EntryProcessorTest failures

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#5169]
com.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationDetector_EntryProcessorTest.testSlowEntryProcessor
com.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationDetector_EntryProcessorTest.testMultipleSlowEntryProcessorClasses

```
java.lang.AssertionError: Expected 4 total invocations, but was 3 expected:<4> but was:<3>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at com.hazelcast.test.HazelcastTestSupport.assertEqualsStringFormat(HazelcastTestSupport.java:672)
	at 
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-sonar/com.hazelcast$hazelcast/600/testReport/junit/com.hazelcast.spi.impl.operationexecutor.slowoperationdetector/SlowOperationDetector_EntryProcessorTest/testSlowEntryProcessor/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-sonar/601/com.hazelcast$hazelcast/testReport/com.hazelcast.spi.impl.operationexecutor.slowoperationdetector/SlowOperationDetector_EntryProcessorTest/testMultipleSlowEntryProcessorClasses/
