### ISSUE TITLE
[TEST-FAILURE] SlowOperationDetectorBasicTest.testSlowRecursiveOperation

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#5173]
```
java.lang.AssertionError: Expected 50 total invocations, but was 43 expected:<50> but was:<43>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at com.hazelcast.test.HazelcastTestSupport.assertEqualsStringFormat(HazelcastTestSupport.java:672)
	at com.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationDetectorAbstractTest.assertTotalInvocations(SlowOperationDetectorAbstractTest.java:117)
	at com.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationDetectorBasicTest.testSlowRecursiveOperation(SlowOperationDetectorBasicTest.java:203)
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK7-Quality-Outreach/com.hazelcast$hazelcast/41/testReport/junit/com.hazelcast.spi.impl.operationexecutor.slowoperationdetector/SlowOperationDetectorBasicTest/testSlowRecursiveOperation/

**Comment by Donnerbart** [comment]
Should be fixed via https://github.com/hazelcast/hazelcast/pull/5197

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: Expected 40 total invocations, but was 13. Log: {"operation":"com.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationDetectorBasicTest$SlowRecursiveOperation","stackTrace":"java.lang.Thread.sleep(Native Method)\n\tjava.lang.Thread.sleep(Thread.java:340)\n\tjava.util.concurrent.TimeUnit.sleep(TimeUnit.java:386)\n\tcom.hazelcast.test.HazelcastTestSupport.sleepSeconds(HazelcastTestSupport.java:288)\n\tcom.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationDetectorBasicTest$SlowRecursiveOperation.recursiveCall(SlowOperationDetectorBasicTest.java:309)\n\tcom.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationDetectorBasicTest$SlowRecursiveOperation.recursiveCall(SlowOperationDetectorBasicTest.java:313)\n\tcom.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationDetectorBasicTest$SlowRecursiveOperation.recursiveCall(SlowOperationDetectorBasicTest.java:313)\n\tcom.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationDetectorBasicTest$SlowRecursiveOperation.recursiveCall(SlowOperationDetectorBasicTest.java:313)\n\tcom.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationDetectorBasicTest$SlowRecursiveOperation.recursiveCall(SlowOperationDetectorBasicTest.java:313)\n\tcom.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationDetectorBasicTest$SlowRecursiveOperation.recursiveCall(SlowOperationDetectorBasicTest.java:313)\n\tcom.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationDetectorBasicTest$SlowRecursiveOperation.recursiveCall(SlowOperationDetectorBasicTest.java:313)\n\tcom.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationDetectorBasicTest$SlowRecursiveOperation.recursiveCall(SlowOperationDetectorBasicTest.java:313)\n\tcom.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationDetectorBasicTest$SlowRecursiveOperation.recursiveCall(SlowOperationDetectorBasicTest.java:313)\n\tcom.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationDetectorBasicTest$SlowRecursiveOperation.recursiveCall(SlowOperationDetectorBasicTest.java:313)\n\tcom.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationDetectorBasicTest$SlowRecursiveOperation.recursiveCall(SlowOperationDetectorBasicTest.java:313)\n\tcom.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationDetectorBasicTest$SlowRecursiveOperation.recursiveCall(SlowOperationDetectorBasicTest.java:313)\n\tcom.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationDetectorBasicTest$SlowRecursiveOperation.recursiveCall(SlowOperationDetectorBasicTest.java:313)\n\tcom.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationDetectorBasicTest$SlowRecursiveOperation.recursiveCall(SlowOperationDetectorBasicTest.java:313)\n\tcom.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationDetectorBasicTest$SlowRecursiveOperation.recursiveCall(SlowOperationDetectorBasicTest.java:313)\n\tcom.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationDetectorBasicTest$SlowRecursiveOperation.recursiveCall(SlowOperationDetectorBasicTest.java:313)\n\tcom.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationDetectorBasicTest$SlowRecursiveOperation.run(SlowOperationDetectorBasicTest.java:304)\n\tcom.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:183)\n\tcom.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:122)\n\tcom.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:102)","totalInvocations":13,"invocations":[{"id":1131959801,"details":"com.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationDetectorBasicTest$SlowRecursiveOperation{serviceName='null', identityHash=1131959801, partitionId=18, replicaIndex=0, callId=0, invocationTime=-1 (1970-01-01 01:59:59.999), waitTimeout=-1, callTimeout=9223372036854775807}","startedAt":1465933985962,"durationMs":3733},{"id":24405948,"details":"com.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationDetectorBasicTest$SlowRecursiveOperation{serviceName='null', identityHash=24405948, partitionId=27, replicaIndex=0, callId=0, invocationTime=-1 (1970-01-01 01:59:59.999), waitTimeout=-1, callTimeout=9223372036854775807}","startedAt":1465933985962,"durationMs":3733},{"id":389020642,"details":"com.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationDetectorBasicTest$SlowRecursiveOperation{serviceName='null', identityHash=389020642, partitionId=36, replicaIndex=0, callId=0, invocationTime=-1 (1970-01-01 01:59:59.999), waitTimeout=-1, callTimeout=9223372036854775807}","startedAt":1465933983899,"durationMs":5795},{"id":1985597259,"details":"com.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationDetectorBasicTest$SlowRecursiveOperation{serviceName='null', identityHash=1985597259, partitionId=9, replicaIndex=0, callId=0, invocationTime=-1 (1970-01-01 01:59:59.999), waitTimeout=-1, callTimeout=9223372036854775807}","startedAt":1465933985962,"durationMs":3733},{"id":515683530,"details":"com.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationDetectorBasicTest$SlowRecursiveOperation{serviceName='null', identityHash=515683530, partitionId=1, replicaIndex=0, callId=0, invocationTime=-1 (1970-01-01 01:59:59.999), waitTimeout=-1, callTimeout=9223372036854775807}","startedAt":1465933982894,"durationMs":3067},{"id":276515181,"details":"com.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationDetectorBasicTest$SlowRecursiveOperation{serviceName='null', identityHash=276515181, partitionId=10, replicaIndex=0, callId=0, invocationTime=-1 (1970-01-01 01:59:59.999), waitTimeout=-1, callTimeout=9223372036854775807}","startedAt":1465933982894,"durationMs":1004},{"id":1741639577,"details":"com.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationDetectorBasicTest$SlowRecursiveOperation{serviceName='null', identityHash=1741639577, partitionId=63, replicaIndex=0, callId=0, invocationTime=-1 (1970-01-01 01:59:59.999), waitTimeout=-1, callTimeout=9223372036854775807}","startedAt":1465933983899,"durationMs":5795},{"id":48760030,"details":"com.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationDetectorBasicTest$SlowRecursiveOperation{serviceName='null', identityHash=48760030, partitionId=81, replicaIndex=0, callId=0, invocationTime=-1 (1970-01-01 01:59:59.999), waitTimeout=-1, callTimeout=9223372036854775807}","startedAt":1465933983899,"durationMs":5795},{"id":1389100850,"details":"com.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationDetectorBasicTest$SlowRecursiveOperation{serviceName='null', identityHash=1389100850, partitionId=45, replicaIndex=0, callId=0, invocationTime=-1 (1970-01-01 01:59:59.999), waitTimeout=-1, callTimeout=9223372036854775807}","startedAt":1465933983899,"durationMs":5795},{"id":1448600620,"details":"com.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationDetectorBasicTest$SlowRecursiveOperation{serviceName='null', identityHash=1448600620, partitionId=54, replicaIndex=0, callId=0, invocationTime=-1 (1970-01-01 01:59:59.999), waitTimeout=-1, callTimeout=9223372036854775807}","startedAt":1465933983899,"durationMs":5795},{"id":1811408427,"details":"com.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationDetectorBasicTest$SlowRecursiveOperation{serviceName='null', identityHash=1811408427, partitionId=0, replicaIndex=0, callId=0, invocationTime=-1 (1970-01-01 01:59:59.999), waitTimeout=-1, callTimeout=9223372036854775807}","startedAt":1465933985962,"durationMs":3733},{"id":340058042,"details":"com.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationDetectorBasicTest$SlowRecursiveOperation{serviceName='null', identityHash=340058042, partitionId=19, replicaIndex=0, callId=0, invocationTime=-1 (1970-01-01 01:59:59.999), waitTimeout=-1, callTimeout=9223372036854775807}","startedAt":1465933982894,"durationMs":1004},{"id":257382505,"details":"com.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationDetectorBasicTest$SlowRecursiveOperation{serviceName='null', identityHash=257382505, partitionId=72, replicaIndex=0, callId=0, invocationTime=-1 (1970-01-01 01:59:59.999), waitTimeout=-1, callTimeout=9223372036854775807}","startedAt":1465933983899,"durationMs":5795}]} expected:<40> but was:<13>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at com.hazelcast.test.HazelcastTestSupport.assertEqualsStringFormat(HazelcastTestSupport.java:923)
	at com.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationDetectorAbstractTest.assertTotalInvocations(SlowOperationDetectorAbstractTest.java:131)
	at com.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationDetectorBasicTest.testSlowRecursiveOperation(SlowOperationDetectorBasicTest.java:198)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-sonar/com.hazelcast$hazelcast/1093/testReport/junit/com.hazelcast.spi.impl.operationexecutor.slowoperationdetector/SlowOperationDetectorBasicTest/testSlowRecursiveOperation/
