### ISSUE TITLE
CustomPropertiesTest.testNativeClient

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#5190]
```
org.hibernate.InvalidMappingException: Could not parse mapping document from resource com/hazelcast/hibernate/entity/DummyProperty.hbm.xml
	at org.dom4j.io.SAXReader.read(SAXReader.java:484)
	at org.hibernate.cfg.Configuration.addInputStream(Configuration.java:601)
	at org.hibernate.cfg.Configuration.addResource(Configuration.java:668)
	at org.hibernate.cfg.Configuration.parseMappingElement(Configuration.java:1679)
	at org.hibernate.cfg.Configuration.parseSessionFactory(Configuration.java:1647)
	at org.hibernate.cfg.Configuration.doConfigure(Configuration.java:1626)
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-nightly/com.hazelcast$hazelcast-hibernate3/461/testReport/junit/com.hazelcast.hibernate/CustomPropertiesTest/testNativeClient/

**Comment by kobalski** [comment]
Should be fixed via commit https://github.com/hazelcast/hazelcast/commit/a012962241c7fdfc6f6004c148ba3b26a6e0d5e2
Closing for now.

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: expected:<1> but was:<2>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.hibernate.CustomPropertiesTest.testNativeClient(CustomPropertiesTest.java:82)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-nightly/com.hazelcast$hazelcast-hibernate3/911/testReport/junit/com.hazelcast.hibernate/CustomPropertiesTest/testNativeClient/
