### ISSUE TITLE
[TEST-FAILURE] MapStoreTest.testOneMemberFlush

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#5191]
```
org.junit.runners.model.TestTimedOutException: test timed out after 120000 milliseconds
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:196)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.pollResponse(InvocationFuture.java:299)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.waitForResponse(InvocationFuture.java:247)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.get(InvocationFuture.java:224)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.get(InvocationFuture.java:204)
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.6/com.hazelcast$hazelcast/530/testReport/junit/com.hazelcast.map.mapstore/MapStoreTest/testOneMemberFlush/

**Comment by eminn** [comment]
Closing the test failure since it is not failing recently.
