### ISSUE TITLE
New Client GetAsync Fails with a NegativeArraySizeException

### ISSUE THREAD

**Issue by gurbuzali** [hazelcast/hazelcast#5229]
```
        Hazelcast.newHazelcastInstance();
        IMap map = client.getMap("map");

        int size = 100;
        for (int i = 0; i < size; i++) {
            map.put(i, i);
        }
        for (int i = 0; i < size; i++) {
            Future f = map.getAsync(i);
            f.get();
        }
```

**Comment by gurbuzali** [comment]
```
java.lang.NegativeArraySizeException
	at com.hazelcast.client.impl.protocol.util.ParameterFlyweight.getByteArray(ParameterFlyweight.java:190)
	at com.hazelcast.client.impl.protocol.util.ParameterFlyweight.getData(ParameterFlyweight.java:197)
	at com.hazelcast.client.impl.protocol.parameters.GenericResultParameters.<init>(GenericResultParameters.java:38)
	at com.hazelcast.client.impl.protocol.parameters.GenericResultParameters.decode(GenericResultParameters.java:43)
	at com.hazelcast.util.executor.DelegatingFuture.getResult(DelegatingFuture.java:108)
	at com.hazelcast.util.executor.DelegatingFuture.get(DelegatingFuture.java:72)
	at com.hazelcast.util.executor.DelegatingFuture.get(DelegatingFuture.java:57)
	at com.hazelcast.client.map.ClientMapNearCacheTest.test(ClientMapNearCacheTest.java:253)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at com.hazelcast.test.HazelcastParallelClassRunner.access$201(HazelcastParallelClassRunner.java:29)
	at com.hazelcast.test.HazelcastParallelClassRunner$TestRunner.run(HazelcastParallelClassRunner.java:89)
	at java.lang.Thread.run(Thread.java:695)
```

**Comment by gurbuzali** [comment]
I've ignored the `ClientMapNearCacheTest.testGetAsyncPupulatesNearCache` https://github.com/hazelcast/hazelcast/commit/467824b
should be re-opened after fixing this issue
