### ISSUE TITLE
Unbounded return values tests run forever with new client

### ISSUE THREAD

**Issue by Donnerbart** [hazelcast/hazelcast#5230]
There are some exceptions when I run one of the new tests for the "unbounded return values" feature with the new client.

The first exceptions are some `ConnectException`:
```
12:43:00,208 DEBUG [ClusterListenerSupport] main - Exception during initial connection to localhost/127.0.0.1:5702
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at sun.nio.ch.SocketAdaptor.connect(SocketAdaptor.java:111)
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.createSocketConnection(ClientConnectionManagerImpl.java:244)
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.getOrConnect(ClientConnectionManagerImpl.java:198)
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.getOrConnect(ClientConnectionManagerImpl.java:67)
	at com.hazelcast.client.spi.impl.ClusterListenerSupport.connect(ClusterListenerSupport.java:228)
	at com.hazelcast.client.spi.impl.ClusterListenerSupport.connectToOne(ClusterListenerSupport.java:196)
	at com.hazelcast.client.spi.impl.ClusterListenerSupport.connectToCluster(ClusterListenerSupport.java:149)
	at com.hazelcast.client.spi.impl.ClientClusterServiceImpl.start(ClientClusterServiceImpl.java:181)
	at com.hazelcast.client.impl.HazelcastClientInstanceImpl.start(HazelcastClientInstanceImpl.java:230)
	at com.hazelcast.client.HazelcastClient.newHazelcastClient(HazelcastClient.java:81)
	at com.hazelcast.client.HazelcastClient.newHazelcastClient(HazelcastClient.java:68)
	at com.hazelcast.client.map.ClientMapUnboundReturnValuesTestSupport.internalSetUpClient(ClientMapUnboundReturnValuesTestSupport.java:140)
	at com.hazelcast.client.map.ClientMapUnboundReturnValuesTestSupport.runClientMapTestTxnWithException(ClientMapUnboundReturnValuesTestSupport.java:107)
	at com.hazelcast.client.map.ClientMapUnboundReturnValues_TxnTest.testClientTxnMap_withException_PreCheck(ClientMapUnboundReturnValues_TxnTest.java:20)
(...)
```

There is a debug stack trace before that, but maybe this is unrelated:
```
12:42:57,772 DEBUG [UTFEncoderDecoder] main - Old String constructor doesn't seem available
java.lang.NoSuchMethodException: java.lang.String.<init>(int, int, [C)
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.getDeclaredConstructor(Class.java:2178)
	at com.hazelcast.nio.UTFEncoderDecoder.useOldStringConstructor(UTFEncoderDecoder.java:691)
	at com.hazelcast.nio.UTFEncoderDecoder.buildFastStringCreator(UTFEncoderDecoder.java:737)
	at com.hazelcast.nio.UTFEncoderDecoder.createStringCreator(UTFEncoderDecoder.java:712)
	at com.hazelcast.nio.UTFEncoderDecoder.createStringCreator(UTFEncoderDecoder.java:708)
	at com.hazelcast.nio.UTFEncoderDecoder.buildUTFUtil(UTFEncoderDecoder.java:702)
	at com.hazelcast.nio.UTFEncoderDecoder.<clinit>(UTFEncoderDecoder.java:48)
	at com.hazelcast.nio.serialization.ByteArrayObjectDataOutput.writeUTF(ByteArrayObjectDataOutput.java:230)
	at com.hazelcast.nio.serialization.DataSerializer.write(DataSerializer.java:138)
	at com.hazelcast.nio.serialization.DataSerializer.write(DataSerializer.java:39)
	at com.hazelcast.nio.serialization.StreamSerializerAdapter.write(StreamSerializerAdapter.java:37)
	at com.hazelcast.nio.serialization.SerializationServiceImpl.writeObject(SerializationServiceImpl.java:300)
	at com.hazelcast.nio.serialization.ByteArrayObjectDataOutput.writeObject(ByteArrayObjectDataOutput.java:315)
	at com.hazelcast.cluster.impl.MulticastService.send(MulticastService.java:182)
	at com.hazelcast.cluster.impl.MulticastJoiner.findMasterWithMulticast(MulticastJoiner.java:150)
	at com.hazelcast.cluster.impl.MulticastJoiner.doJoin(MulticastJoiner.java:56)
	at com.hazelcast.cluster.impl.AbstractJoiner.join(AbstractJoiner.java:93)
	at com.hazelcast.instance.Node.join(Node.java:534)
	at com.hazelcast.instance.Node.start(Node.java:343)
	at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:121)
	at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:152)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:135)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:111)
	at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:58)
	at com.hazelcast.client.map.ClientMapUnboundReturnValuesTestSupport.getMapWithNodeCount(ClientMapUnboundReturnValuesTestSupport.java:169)
	at com.hazelcast.client.map.ClientMapUnboundReturnValuesTestSupport.internalSetUpClient(ClientMapUnboundReturnValuesTestSupport.java:138)
	at com.hazelcast.client.map.ClientMapUnboundReturnValuesTestSupport.runClientMapTestTxnWithException(ClientMapUnboundReturnValuesTestSupport.java:107)
	at com.hazelcast.client.map.ClientMapUnboundReturnValues_TxnTest.testClientTxnMap_withException_PreCheck(ClientMapUnboundReturnValues_TxnTest.java:20)
(...)
```

This is how I run the test:
```
mvn clean install -DskipTests
mvn test -Pnightly-build -DfailIfNoTests=false -Dhazelcast.logging.type=log4j -Dlog4j.configuration=https://gist.githubusercontent.com/Donnerbart/7c883affe206b312181b/raw/d848fe8fe9416e1fb81283e6d3076f295cf9b7ab/log4j.conf -Dtest=ClientMapUnboundReturnValues_TxnTest
```

Same happens with the `ClientMapUnboundReturnValues_BasicTest`.

**Comment by Donnerbart** [comment]
This exception is followed by some `ConnectException`, but I think those are caused by the exception above.

```
12:43:00,208 DEBUG [ClusterListenerSupport] main - Exception during initial connection to localhost/127.0.0.1:5702
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at sun.nio.ch.SocketAdaptor.connect(SocketAdaptor.java:111)
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.createSocketConnection(ClientConnectionManagerImpl.java:244)
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.getOrConnect(ClientConnectionManagerImpl.java:198)
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.getOrConnect(ClientConnectionManagerImpl.java:67)
	at com.hazelcast.client.spi.impl.ClusterListenerSupport.connect(ClusterListenerSupport.java:228)
	at com.hazelcast.client.spi.impl.ClusterListenerSupport.connectToOne(ClusterListenerSupport.java:196)
	at com.hazelcast.client.spi.impl.ClusterListenerSupport.connectToCluster(ClusterListenerSupport.java:149)
	at com.hazelcast.client.spi.impl.ClientClusterServiceImpl.start(ClientClusterServiceImpl.java:181)
	at com.hazelcast.client.impl.HazelcastClientInstanceImpl.start(HazelcastClientInstanceImpl.java:230)
	at com.hazelcast.client.HazelcastClient.newHazelcastClient(HazelcastClient.java:81)
	at com.hazelcast.client.HazelcastClient.newHazelcastClient(HazelcastClient.java:68)
	at com.hazelcast.client.map.ClientMapUnboundReturnValuesTestSupport.internalSetUpClient(ClientMapUnboundReturnValuesTestSupport.java:140)
	at com.hazelcast.client.map.ClientMapUnboundReturnValuesTestSupport.runClientMapTestTxnWithException(ClientMapUnboundReturnValuesTestSupport.java:107)
	at com.hazelcast.client.map.ClientMapUnboundReturnValues_TxnTest.testClientTxnMap_withException_PreCheck(ClientMapUnboundReturnValues_TxnTest.java:20)
(...)
```

**Comment by Donnerbart** [comment]
Here is the full log: [com.hazelcast.client.map.ClientMapUnboundReturnValues_TxnTest-output.txt](https://files.zenhub.io/554755f8d40187b7722f8f54)

**Comment by jerrinot** [comment]
please note it's a DEBUG message. I'm not 100% sure but I believe it's not a problem at all. StringCreator is just looking for the fastest way to construct Strings - available options depends on the exact JVM version. 

```
12:42:57,772 DEBUG [UTFEncoderDecoder] main - Old String constructor doesn't seem available
java.lang.NoSuchMethodException: java.lang.String.<init>(int, int, [C)
    at java.lang.Class.getConstructor0(Class.java:3082)
    at java.lang.Class.getDeclaredConstructor(Class.java:2178)
    at com.hazelcast.nio.UTFEncoderDecoder.useOldStringConstructor(UTFEncoderDecoder.java:691)
    at com.hazelcast.nio.UTFEncoderDecoder.buildFastStringCreator(UTFEncoderDecoder.java:737)
    at com.hazelcast.nio.UTFEncoderDecoder.createStringCreator(UTFEncoderDecoder.java:712)
```

**Comment by Donnerbart** [comment]
Hmm, that's a good point. Nevertheless the test doesn't finish but seems to run forever. The full log is already attached. Maybe we need another place to catch the exception properly, I'm trying to understand that part of the new requests right now.

**Comment by Donnerbart** [comment]
I just see that mostly all of the `QueryResultLimitExceeded` exceptions are thrown by the `QueryPartitionOperation`:
```
12:43:06,587 FATAL [QueryPartitionOperation] hz._hzInstance_1_dev.partition-operation.thread-4 - [127.0.0.1]:5701 [dev] [3.5-SNAPSHOT] This exception has been thrown to prevent an OOME on this Hazelcast instance. An OOME might occur when a query collects large data sets from the whole cluster, e.g. by calling IMap.values(), IMap.keySet() or IMap.entrySet(). See GroupProperties.PROP_QUERY_RESULT_SIZE_LIMIT for further details.
```

So maybe the test runs forever since we don't catch the exception of a `QueryOperation` before that and execute the whole operation again for all partitions. This may result in a very long runtime and eventually the timeout.

**Comment by jerrinot** [comment]
```
So maybe the test runs forever since we don't catch the exception of a QueryOperation before that and execute the whole operation again for all partitions. 
```

Can you elaborate it?

**Comment by Donnerbart** [comment]
I think the catch is at least missing in `AbstractMapQueryMessageTask.call()`.

```java
    @Override
    protected final ClientMessage call() throws Exception {
        Collection<QueryResultEntry> result = new LinkedList<QueryResultEntry>();

        Collection<MemberImpl> members = nodeEngine.getClusterService().getMemberList();
        List<Future> futures = new ArrayList<Future>();
        Predicate predicate = getPredicate();
        createInvocations(members, futures, predicate);

        int partitionCount = nodeEngine.getPartitionService().getPartitionCount();
        Set<Integer> finishedPartitions = new HashSet<Integer>(partitionCount);
        try {
            collectResults(result, futures, finishedPartitions);
        } catch (QueryResultSizeExceededException e) {
            throw ExceptionUtil.rethrow(e);
        }

        if (hasMissingPartitions(finishedPartitions, partitionCount)) {
            List<Integer> missingList = findMissingPartitions(finishedPartitions, partitionCount);
            List<Future> missingFutures = new ArrayList<Future>(missingList.size());
            createInvocationsForMissingPartitions(missingList, missingFutures, predicate);
            collectResultsFromMissingPartitions(result, missingFutures);
        }
        return reduce(result);
    }
```
I'm trying to figure out if there are any other missing code parts at the moment. Tests are still failing.

I'm getting another exception type on the basic tests:
```
java.lang.NoSuchMethodException: com.hazelcast.map.QueryResultSizeExceededException.<init>(java.lang.String)
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.getDeclaredConstructor(Class.java:2178)
	at com.hazelcast.client.spi.impl.ClientInvocationServiceSupport$ResponseThread.handleClientMessage(ClientInvocationServiceSupport.java:373)
	at com.hazelcast.client.spi.impl.ClientInvocationServiceSupport$ResponseThread.process(ClientInvocationServiceSupport.java:349)
	at com.hazelcast.client.spi.impl.ClientInvocationServiceSupport$ResponseThread.doRun(ClientInvocationServiceSupport.java:342)
	at com.hazelcast.client.spi.impl.ClientInvocationServiceSupport$ResponseThread.run(ClientInvocationServiceSupport.java:319)
```

**Comment by Donnerbart** [comment]
`NoSuchMethodException` exception has been fixed locally, by adding the missing constructor to the `QueryResultSizeExceededException`.

I still have the feeling (since I didn't find the matching code yet) that the exception is not thrown to the test, but the operation is executed again or something like that.
