### ISSUE TITLE
BasicMapTest.testMapEvictAndListener

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#5236]
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.map.BasicMapTest.testMapEvictAndListener(BasicMapTest.java:214)
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-IbmJDK1.7/com.hazelcast$hazelcast/228/testReport/junit/com.hazelcast.map/BasicMapTest/testMapEvictAndListener/

**Comment by ahmetmircik** [comment]
closed via https://github.com/hazelcast/hazelcast/commit/6223e2d66f1f0e11026d1e889e82229c85198f93

**Comment by hasancelik** [comment]
```
org.junit.ComparisonFailure: expected:</home/data/file[2].dat> but was:</home/data/file[1].dat>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.map.BasicMapTest.testMapEvictAndListener(BasicMapTest.java:221)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-sonar/com.hazelcast$hazelcast/1142/testReport/junit/com.hazelcast.map/BasicMapTest/testMapEvictAndListener/

**Comment by ahmetmircik** [comment]
should be fixed by https://github.com/hazelcast/hazelcast/commit/c0dd2786291d0a88f54879097d5b3415b107fd40
