### ISSUE TITLE
MapLoaderFailoverTest.testLoadsAll_whenInitialLoaderNodeRemovedWhileLoading

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#5257]
```
org.junit.runners.model.TestTimedOutException: test timed out after 60000 milliseconds
    at java.lang.Object.wait(Native Method)
    at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.pollResponse(InvocationFuture.java:299)
    at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.waitForResponse(InvocationFuture.java:247)
    at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.get(InvocationFuture.java:224)
    at com.hazelcast.util.executor.DelegatingFuture.get(DelegatingFuture.java:72)
    at com.hazelcast.util.executor.DelegatingFuture.get(DelegatingFuture.java:57)
    at com.hazelcast.map.mapstore.MapLoaderFailoverTest.testLoadsAll_whenInitialLoaderNodeRemovedWhileLoading(MapLoaderFailoverTest.java:139)
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OracleJDK1.6/com.hazelcast$hazelcast/531/testReport/junit/com.hazelcast.map.mapstore/MapLoaderFailoverTest/testLoadsAll_whenInitialLoaderNodeRemovedWhileLoading/

**Comment by bilalyasar** [comment]
it is map loader failover test, updated title.

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-sonar/com.hazelcast$hazelcast/622/testReport/junit/com.hazelcast.map.mapstore/MapLoaderFailoverTest/testLoadsAll_whenInitialLoaderNodeRemovedAfterLoading/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK8/com.hazelcast$hazelcast/561/testReport/junit/com.hazelcast.map.mapstore/MapLoaderFailoverTest/testLoadsAll_whenInitialLoaderNodeRemovedAfterLoading/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK8-Quality-Outreach/com.hazelcast$hazelcast/59/testReport/junit/com.hazelcast.map.mapstore/MapLoaderFailoverTest/testLoadsAll_whenInitialLoaderNodeRemovedAfterLoading/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x/com.hazelcast$hazelcast/3180/testReport/junit/com.hazelcast.map.mapstore/MapLoaderFailoverTest/testLoadsAll_whenInitialLoaderNodeRemovedWhileLoading/

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK9-Quality-Outreach/70/com.hazelcast$hazelcast/testReport/com.hazelcast.map.mapstore/MapLoaderFailoverTest/testLoadsAll_whenInitialLoaderNodeRemovedWhileLoading/

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK8-Quality-Outreach/66/com.hazelcast$hazelcast/testReport/com.hazelcast.map.mapstore/MapLoaderFailoverTest/testLoadsAll_whenInitialLoaderNodeRemovedWhileLoading/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x/com.hazelcast$hazelcast/3209/testReport/junit/com.hazelcast.map.mapstore/MapLoaderFailoverTest/testLoadsAll_whenInitialLoaderNodeRemovedWhileLoading/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK7-Quality-Outreach/com.hazelcast$hazelcast/71/testReport/junit/com.hazelcast.map.mapstore/MapLoaderFailoverTest/testLoadsAll_whenInitialLoaderNodeRemovedWhileLoading/

**Comment by mesutcelik** [comment]
fixed by https://github.com/hazelcast/hazelcast/pull/5336

**Comment by mesutcelik** [comment]
@ajermakovics ,

You can use special keywords to close issues when related PR is merged. 
https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-OracleJDK1.7/com.hazelcast$hazelcast/141/testReport/junit/com.hazelcast.map.mapstore/MapLoaderFailoverTest/testLoadsAll_whenInitialLoaderNodeRemovedWhileLoading/

**Comment by Donnerbart** [comment]
I'm closing this once since it didn't occur since 4 month and the last failure was maybe racy with merge of the fix.

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: expected:<1> but was:<null>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.map.impl.mapstore.MapLoaderFailoverTest.testLoadsAll_whenInitialLoaderNodeRemovedWhileLoading(MapLoaderFailoverTest.java:139)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK8/com.hazelcast$hazelcast/1201/testReport/junit/com.hazelcast.map.impl.mapstore/MapLoaderFailoverTest/testLoadsAll_whenInitialLoaderNodeRemovedWhileLoading/

**Comment by Donnerbart** [comment]
**com.hazelcast.map.impl.mapstore.MapLoaderFailoverTest.testDoesntLoadAgain_whenLoaderNodeGoesDown**
```java
org.junit.runners.model.TestTimedOutException: test timed out after 60000 milliseconds
	at java.lang.Thread.sleep(Native Method)
	at java.lang.Thread.sleep(Thread.java:340)
	at java.util.concurrent.TimeUnit.sleep(TimeUnit.java:360)
	at com.hazelcast.test.HazelcastTestSupport.sleepMillis(HazelcastTestSupport.java:332)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1157)
	at com.hazelcast.test.HazelcastTestSupport.waitAllForSafeState(HazelcastTestSupport.java:665)
	at com.hazelcast.test.HazelcastTestSupport.waitAllForSafeState(HazelcastTestSupport.java:661)
	at com.hazelcast.map.impl.mapstore.MapLoaderFailoverTest.testDoesntLoadAgain_whenLoaderNodeGoesDown(MapLoaderFailoverTest.java:73)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/11601/testReport/junit/com.hazelcast.map.impl.mapstore/MapLoaderFailoverTest/testDoesntLoadAgain_whenLoaderNodeGoesDown/

**com.hazelcast.map.impl.mapstore.MapLoaderFailoverTest.testLoadsAll_whenInitialLoaderNodeRemovedAfterLoading**
```java
org.junit.runners.model.TestTimedOutException: test timed out after 60000 milliseconds
	at java.lang.Thread.sleep(Native Method)
	at java.lang.Thread.sleep(Thread.java:340)
	at java.util.concurrent.TimeUnit.sleep(TimeUnit.java:360)
	at com.hazelcast.map.impl.proxy.MapProxySupport.waitAllTrue(MapProxySupport.java:664)
	at com.hazelcast.map.impl.proxy.MapProxySupport.waitUntilLoaded(MapProxySupport.java:642)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.waitUntilLoaded(MapProxyImpl.java:111)
	at com.hazelcast.map.impl.proxy.MapProxySupport.loadAllInternal(MapProxySupport.java:521)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.loadAll(MapProxyImpl.java:585)
	at com.hazelcast.map.impl.mapstore.MapLoaderFailoverTest.testLoadsAll_whenInitialLoaderNodeRemovedAfterLoading(MapLoaderFailoverTest.java:112)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/11601/testReport/junit/com.hazelcast.map.impl.mapstore/MapLoaderFailoverTest/testLoadsAll_whenInitialLoaderNodeRemovedAfterLoading/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: expected:<1> but was:<null>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.map.impl.mapstore.MapLoaderFailoverTest.testLoadsAll_whenInitialLoaderNodeRemovedWhileLoading(MapLoaderFailoverTest.java:139)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.7-freestyle/74/testReport/junit/com.hazelcast.map.impl.mapstore/MapLoaderFailoverTest/testLoadsAll_whenInitialLoaderNodeRemovedWhileLoading/

**Comment by blazember** [comment]
The last failure recorded on Dec 25, 2017, by Hasan is the result of the following events in the following sequence:

1) asyncGetting a particular key on node X
2) Loading entries from store is triggered by 1)
3) GetOperation retries a couple of times on node X, waits for loading to complete
4) Node X gets terminated
5) GetOperation continues on node Y
6) GetOperation completes on node Y and returns null
7) The requested key gets loaded on node Y

There is a race condition between the migrated GetOperation and the restarted loading process after the loader node has terminated. That means the test's expectation is not in sync with the current implementation (loading asynchronously on the nodes) and may fail occasionally.

The failure is more likely to happen with choosing another key to load, like 4999, which produced a likely enough possibility locally to debug it.

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: expected:<1> but was:<null>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.map.impl.mapstore.MapLoaderFailoverTest.testLoadsAll_whenInitialLoaderNodeRemovedWhileLoading(MapLoaderFailoverTest.java:139)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-OracleJDK1.7-freestyle/44/testReport/junit/com.hazelcast.map.impl.mapstore/MapLoaderFailoverTest/testLoadsAll_whenInitialLoaderNodeRemovedWhileLoading/

**Comment by blazember** [comment]
Closing as explained in details by #12384.

**Comment by kwart** [comment]
Reopening. The test is still unstable.
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-pr-builder/17135/testReport/junit/com.hazelcast.map.impl.mapstore/MapLoaderFailoverTest/testLoadsAll_whenInitialLoaderNodeRemovedWhileLoading/

 If we know the fix is not ready yet, we should add an `@Ignore` to the test.

**Comment by mmedenjak** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-pr-builder/17453/testReport/junit/com.hazelcast.map.impl.mapstore/MapLoaderFailoverTest/testLoadsAll_whenInitialLoaderNodeRemovedWhileLoading/

```
java.lang.AssertionError: expected:<1> but was:<null>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.map.impl.mapstore.MapLoaderFailoverTest.testLoadsAll_whenInitialLoaderNodeRemovedWhileLoading(MapLoaderFailoverTest.java:139)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by mmedenjak** [comment]
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/5604

```
java.lang.AssertionError: expected:<1> but was:<null>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.map.impl.mapstore.MapLoaderFailoverTest.testLoadsAll_whenInitialLoaderNodeRemovedWhileLoading(MapLoaderFailoverTest.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```
