### ISSUE TITLE
[TEST-FAILURE] SplitBrainHandlerTest failures

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#5276]
com.hazelcast.cluster.SplitBrainHandlerTest.testClusterMerge_when_split_not_detected_by_slave_and_restart_during_merge
com.hazelcast.cluster.SplitBrainHandlerTest.testClusterMerge_when_split_not_detected_by_slave
```
java.lang.AssertionError: expected:<Address[127.0.0.1]:5703> but was:<Address[127.0.0.1]:5702>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.cluster.SplitBrainHandlerTest.testClusterMerge_when_split_not_detected_by_slave_and_restart_during_merge(SplitBrainHandlerTest.java:710)
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-nightly/474/#showFailuresLink

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-nightly/473/
