### ISSUE TITLE
[TEST-FAILURE] ClientReconnectTest.testClientReconnectOnClusterDown

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#5286]
```
java.util.concurrent.RejectedExecutionException: Internal executor rejected task: java.util.concurrent.FutureTask@5ac791f4, because client is shutting down...
	at com.hazelcast.client.spi.impl.ClientExecutionServiceImpl$1.rejectedExecution(ClientExecutionServiceImpl.java:59)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:767)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:658)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:78)
	at com.hazelcast.client.spi.impl.ClientExecutionServiceImpl.submitInternal(ClientExecutionServiceImpl.java:80)
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.getOrConnect(ClientConnectionManagerImpl.java:333)
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.tryToConnect(ClientConnectionManagerImpl.java:274)
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-OpenJDK6/com.hazelcast$hazelcast-client/234/testReport/junit/com.hazelcast.client/ClientReconnectTest/testClientReconnectOnClusterDown/

**Comment by sancar** [comment]
fixed by https://github.com/hazelcast/hazelcast/commit/c32eaabcab0803cc0b610aaaa244c432f066c496

**Comment by bilalyasar** [comment]
very related failure, so i will not open new issue, i am reopening this one:
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-OpenJDK7/com.hazelcast$hazelcast-client/246/testReport/junit/com.hazelcast.client/ClientReconnectTest/testClientReconnectOnClusterDownWithEntryListeners/
