### ISSUE TITLE
TestCacheManager.testCacheNames

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#5297]
```
java.lang.AssertionError: CountDownLatch failed to complete within 120 seconds , count left: 1
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.assertTrue(Assert.java:41)
    at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:645)
    at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:638)
    at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:630)
    at com.hazelcast.spring.cache.TestCacheManager.testCacheNames(TestCacheManager.java:121)
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK8/com.hazelcast$hazelcast-spring/558/testReport/junit/com.hazelcast.spring.cache/TestCacheManager/testCacheNames/

**Comment by bilalyasar** [comment]
another failure in the same class probably related:
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK8/com.hazelcast$hazelcast-spring/558/testReport/junit/com.hazelcast.spring.cache/TestCacheManager/test/

**Comment by mesutcelik** [comment]
seems fixed already. related to cloudbees multicast problem.

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: CountDownLatch failed to complete within 120 seconds , count left: 1
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:764)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:757)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:749)
	at com.hazelcast.spring.cache.TestCacheManager.testCacheNames(TestCacheManager.java:126)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-ZuluJDK6/com.hazelcast$hazelcast-spring/160/testReport/junit/com.hazelcast.spring.cache/TestCacheManager/testCacheNames/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: CountDownLatch failed to complete within 120 seconds , count left: 1
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:764)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:757)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:749)
	at com.hazelcast.spring.cache.TestCacheManager.testCacheNames(TestCacheManager.java:126)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK1.8/com.hazelcast$hazelcast-spring/225/testReport/junit/com.hazelcast.spring.cache/TestCacheManager/testCacheNames/

**Comment by emrahkocaman** [comment]
Resolved by #8245

**Comment by sancar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/7298/
@emrahkocaman Test failed in my pr

**Comment by Donnerbart** [comment]
Another failure in a PR build run:
```
java.lang.AssertionError: CountDownLatch failed to complete within 120 seconds, count left: 1
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:899)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:892)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:884)
	at com.hazelcast.spring.cache.TestCacheManager.testCacheNames(TestCacheManager.java:121)
```
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/new-lab-fast-pr/8393/testReport/junit/com.hazelcast.spring.cache/TestCacheManager/testCacheNames/

**Comment by jerrinot** [comment]
last failure from April. closing.

**Comment by mdogan** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/11879/testReport/junit/com.hazelcast.spring.cache/TestCacheManager/testCacheNames/

```
java.lang.AssertionError: CountDownLatch failed to complete within 120 seconds, count left: 1
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:1016)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:1009)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:1001)
	at com.hazelcast.spring.cache.TestCacheManager.testCacheNames(TestCacheManager.java:121)
```

**Comment by Donnerbart** [comment]
**com.hazelcast.spring.cache.TestCacheManager.testCacheNames**
```java
java.lang.AssertionError: CountDownLatch failed to complete within 120 seconds, count left: 1
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:1032)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:1025)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:1017)
	at com.hazelcast.spring.cache.TestCacheManager.testCacheNames(TestCacheManager.java:121)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/12276/testReport/junit/com.hazelcast.spring.cache/TestCacheManager/testCacheNames/

**Comment by sancar** [comment]
com.hazelcast.spring.cache.TestCacheManager.testCacheNames

https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/12317/testReport/junit/com.hazelcast.spring.cache/TestCacheManager/testCacheNames/

Error Message

CountDownLatch failed to complete within 120 seconds, count left: 1

```
java.lang.AssertionError: CountDownLatch failed to complete within 120 seconds, count left: 1
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:1016)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:1009)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:1001)
	at com.hazelcast.spring.cache.TestCacheManager.testCacheNames(TestCacheManager.java:121)
```

**Comment by sancar** [comment]
One more failure 
```
Error Message
CountDownLatch failed to complete within 120 seconds, count left: 1
Stacktrace
java.lang.AssertionError: CountDownLatch failed to complete within 120 seconds, count left: 1
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:1012)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:1005)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:997)
	at com.hazelcast.spring.cache.TestCacheManager.testCacheNames(TestCacheManager.java:121)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/12357/testReport/junit/com.hazelcast.spring.cache/TestCacheManager/testCacheNames/
