### ISSUE TITLE
[TEST-FAILURE] MapLoaderMultiNodeTest.testDoesNotLoadAgain_whenLoadedLazyAndNodeAdded

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#5318]
```
java.lang.AssertionError: expected:<1> but was:<2>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.map.mapstore.MapLoaderMultiNodeTest.testDoesNotLoadAgain_whenLoadedLazyAndNodeAdded(MapLoaderMultiNodeTest.java:113)
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OracleJDK8/com.hazelcast$hazelcast/432/testReport/junit/com.hazelcast.map.mapstore/MapLoaderMultiNodeTest/testDoesNotLoadAgain_whenLoadedLazyAndNodeAdded/

**Comment by ajermakovics** [comment]
No failing for me during 100 repeated runs with high cpu load. Both on current master and on master at the day of the failure.
