### ISSUE TITLE
[TEST-FAILURE] map.ClientMapEvictAllTest timeout

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#5362]
```
01:55:31 Running com.hazelcast.client.map.ClientMapEvictAllTest
03:57:48 ERROR: Couldn't find path for tool 'Oracle JDK 8 (latest)' 
03:57:48 Build timed out (after 200 minutes). Marking the build as failed.
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-sonar/628/console

**Comment by eminn** [comment]
```
03:57:49 Looks like the node went offline during the build. Check the slave log for the details.
details
[05/22/15 03:53:41] [SSH] Opening SSH connection to prd-lxc-lrg-013f80e0.mansions.cloudbees.com:10102.
No route to host
ERROR: Unexpected error in launching a slave. This is probably a bug in Jenkins.
java.lang.IllegalStateException: Connection is not established!
	at com.trilead.ssh2.Connection.getRemainingAuthMethods(Connection.java:1030)
	at com.cloudbees.jenkins.plugins.sshcredentials.impl.TrileadSSHPublicKeyAuthenticator.getRemainingAuthMethods(TrileadSSHPublicKeyAuthenticator.java:88)
	at com.cloudbees.jenkins.plugins.sshcredentials.impl.TrileadSSHPublicKeyAuthenticator.canAuthenticate(TrileadSSHPublicKeyAuthenticator.java:80)
	at com.cloudbees.jenkins.plugins.sshcredentials.SSHAuthenticator.newInstance(SSHAuthenticator.java:207)
	at com.cloudbees.jenkins.plugins.sshcredentials.SSHAuthenticator.newInstance(SSHAuthenticator.java:169)
	at hudson.plugins.sshslaves.SSHLauncher.openConnection(SSHLauncher.java:1230)
	at hudson.plugins.sshslaves.SSHLauncher$2.call(SSHLauncher.java:696)
	at hudson.plugins.sshslaves.SSHLauncher$2.call(SSHLauncher.java:691)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

03:57:49 FATAL: channel is already closed
```
I don't think this build failure directly related to hazelcast.

**Comment by mesutcelik** [comment]
:+1: 

I think @bilalyasar has already raised a ticket about this problem to Cloudbees.

**Comment by eminn** [comment]
I am closing this issue then.
