### ISSUE TITLE
[TEST-FAILURE] JCacheListenerTest.testSyncListener

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#5363]
```
java.lang.AssertionError: CountDownLatch failed to complete within 120 seconds , count left: 1
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:198)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:191)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:183)
	at com.hazelcast.cache.JCacheListenerTest.testSyncListener(JCacheListenerTest.java:93)
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-OracleJDK1.7/com.hazelcast$hazelcast/125/testReport/junit/com.hazelcast.cache/JCacheListenerTest/testSyncListener/

**Comment by serkan-ozal** [comment]
Should be fixed via https://github.com/hazelcast/hazelcast/commit/5a84641d6ca0ba61f6bc3db3f4d51994ee307736
