### ISSUE TITLE
BasicMapTest.testMapTryPut

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#5364]
```
java.lang.AssertionError: expected:<0> but was:<2>
    at org.junit.Assert.fail(Assert.java:88)
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-OracleJDK1.6/com.hazelcast$hazelcast/246/testReport/junit/com.hazelcast.map/BasicMapTest/testMapTryPut/

**Comment by ahmetmircik** [comment]
closed via https://github.com/hazelcast/hazelcast/commit/cba5069687cbeacd197393dba096a6d7bb30a0be

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: CountDownLatch failed to complete within 120 seconds , count left: 1
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:812)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:805)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:797)
	at com.hazelcast.map.BasicMapTest.testMapTryPut(BasicMapTest.java:738)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.8/com.hazelcast$hazelcast/402/testReport/junit/com.hazelcast.map/BasicMapTest/testMapTryPut/

**Comment by vbekiaris** [comment]
Failed build log seems to indicate that the [`tryPut` invocation](https://github.com/hazelcast/hazelcast/blob/c0dd2786291d0a88f54879097d5b3415b107fd40/hazelcast/src/test/java/com/hazelcast/map/BasicMapTest.java#L718) waited for 5 seconds before being timed out, so for some unknown reason the main test thread did not manage to unlock the key in this period of time (perhaps due to load in the build environment?).
