### ISSUE TITLE
MigrationAwareServiceTest Failures

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#5393]
```
java.lang.AssertionError: expected:<542> but was:<506>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK8-Quality-Outreach/com.hazelcast$hazelcast/72/testReport/junit/com.hazelcast.spi/MigrationAwareServiceTest/testPartitionDataSize_whenNodesStartedParallel_withSingleBackup/

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.6/com.hazelcast$hazelcast/549/testReport/junit/com.hazelcast.spi/MigrationAwareServiceTest/testPartitionDataSize_whenNodesStartedParallel_withSingleBackup/

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.7/572/

**Comment by mesutcelik** [comment]
This time different method.

```
MigrationAwareServiceTest.testPartitionDataSize_whenBackupNodesTerminated_withThreeBackups
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x/com.hazelcast$hazelcast/3280/testReport/junit/com.hazelcast.spi/MigrationAwareServiceTest/testPartitionDataSize_whenBackupNodesTerminated_withThreeBackups/

**Comment by eminn** [comment]
That build is started before the fix is merged into the master.

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.6/574/com.hazelcast$hazelcast/testReport/com.hazelcast.spi/MigrationAwareServiceTest/testPartitionDataSize_whenBackupNodesTerminated_withThreeBackups/

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.6/590/testReport/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.6/com.hazelcast$hazelcast/593/testReport/junit/com.hazelcast.spi/MigrationAwareServiceTest/testPartitionDataSize_whenBackupNodesTerminated_withThreeBackups/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-IbmJDK1.6/com.hazelcast$hazelcast/266/testReport/junit/com.hazelcast.spi/MigrationAwareServiceTest/testPartitionDataSize_whenBackupNodesTerminated_withThreeBackups/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast$hazelcast/650/testReport/junit/com.hazelcast.spi/MigrationAwareServiceTest/testPartitionDataSize_whenBackupNodesTerminated_withThreeBackups/

**Comment by eminn** [comment]
No build logs available/not failing recently.

**Comment by hasancelik** [comment]
**testPartitionDataSize_whenBackupNodesTerminated_withThreeBackups**
```
java.lang.AssertionError: expected:<1084> but was:<1051>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.spi.MigrationAwareServiceTest$3.run(MigrationAwareServiceTest.java:222)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:835)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:849)
	at com.hazelcast.spi.MigrationAwareServiceTest.assertSize(MigrationAwareServiceTest.java:211)
	at com.hazelcast.spi.MigrationAwareServiceTest.testPartitionDataSize_whenBackupNodesTerminated(MigrationAwareServiceTest.java:147)
	at com.hazelcast.spi.MigrationAwareServiceTest.testPartitionDataSize_whenBackupNodesTerminated_withThreeBackups(MigrationAwareServiceTest.java:135)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK1.6/com.hazelcast$hazelcast/761/testReport/junit/com.hazelcast.spi/MigrationAwareServiceTest/testPartitionDataSize_whenBackupNodesTerminated_withThreeBackups/

**Comment by mesutcelik** [comment]
**withThreeBackups**
```
java.lang.AssertionError: expected:<1084> but was:<1033>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.spi.MigrationAwareServiceTest$3.run(MigrationAwareServiceTest.java:222)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:835)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:849)
	at com.hazelcast.spi.MigrationAwareServiceTest.assertSize(MigrationAwareServiceTest.java:211)
	at com.hazelcast.spi.MigrationAwareServiceTest.testPartitionDataSize_whenBackupNodesTerminated(MigrationAwareServiceTest.java:147)
	at com.hazelcast.spi.MigrationAwareServiceTest.testPartitionDataSize_whenBackupNodesTerminated_withThreeBackups(MigrationAwareServiceTest.java:135)
```

**withTwoBackups**
```
java.lang.AssertionError: expected:<813> but was:<799>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.spi.MigrationAwareServiceTest$3.run(MigrationAwareServiceTest.java:222)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:835)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:849)
	at com.hazelcast.spi.MigrationAwareServiceTest.assertSize(MigrationAwareServiceTest.java:211)
	at com.hazelcast.spi.MigrationAwareServiceTest.testPartitionDataSize_whenBackupNodesTerminated(MigrationAwareServiceTest.java:147)
	at com.hazelcast.spi.MigrationAwareServiceTest.testPartitionDataSize_whenBackupNodesTerminated_withTwoBackups(MigrationAwareServiceTest.java:130)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK1.7/333/

**Comment by sancar** [comment]
I have reproduced the issue in my local. Here are the logs for anyone interested
https://gist.github.com/sancar/673b004a46fa7c96efca

**Comment by mdogan** [comment]
not an existing test anymore.
