### ISSUE TITLE
[TEST-FAILURE] XATestWithJCA.testPut

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#5404]
```
java.lang.NoClassDefFoundError: org/junit/runners/model/MultipleFailureException
	at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:150)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
	at com.hazelcast.test.HazelcastParallelClassRunner.access$201(HazelcastParallelClassRunner.java:29)
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x/com.hazelcast$hazelcast-jca/3242/testReport/junit/com.hazelcast.jca/XATestWithJCA/testPut/

**Comment by serkan-ozal** [comment]
The problem was about thread dump on test failure. At the moment, thread dump is disabled by https://github.com/hazelcast/hazelcast/commit/9833c5416fb8affdc05e5696f02a96205836f336. So I am closing this one and will look at the problem for the thread dump side.
