### ISSUE TITLE
[TEST-FAILURE] LockBasicDistributedTest.testTryLock

### ISSUE THREAD

**Issue by mesutcelik** [hazelcast/hazelcast#5416]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK6/549/com.hazelcast$hazelcast/testReport/com.hazelcast.concurrent.lock/LockBasicDistributedTest/testTryLock/

**Comment by pveentjer** [comment]
@eminn are you working on this ticket or can I take it over?

**Comment by pveentjer** [comment]
I don't think this issue is related to locking; but to a member failing to join the cluster. If a member sends a JoinRequestOperation to another member, the other member is allowed to drop this message if a join is already happening. This is one of the messages I see in the log. 

Something else I see in the log is that the JoinRequestOperation can be very slow to get executed since I see it in the SlowOperationDetector.

```
02:33:59,424  WARN [SlowOperationDetector] hz._hzInstance_2131_dev.SlowOperationDetectorThread - [127.0.0.1]:7273 [dev] [3.5-EA2-SNAPSHOT] Slow operation detected: com.hazelcast.cluster.impl.operations.JoinRequestOperation
```

This can be caused of the ClusterService.lock already is acquired and the JoinRequestOperation tries to acquire it.

**Comment by pveentjer** [comment]
I'm going to move this one to 3.6.

The failure is not related to locking but a failure related to the ClusterService. And it seems to be either a data race or some logical error. 

The ClusterService doesn't have any tests, so we can't make any changes to it. Else we are increasing risk for the sake of dealing with a spurious failing test.

**Comment by eminn** [comment]
```

02:34:57,614 FATAL [Node] testTryLock - [127.0.0.1]:7284 [dev] [3.5-EA2-SNAPSHOT] Error while joining the cluster!
java.lang.AssertionError: Node[Address[127.0.0.1]:7284] should have been joined to Address[127.0.0.1]:7283
	at com.hazelcast.test.TestNodeRegistry$MockJoiner.doJoin(TestNodeRegistry.java:194)
	at com.hazelcast.cluster.impl.AbstractJoiner.join(AbstractJoiner.java:93)
	at com.hazelcast.instance.Node.join(Node.java:534)
	at com.hazelcast.instance.Node.start(Node.java:343)
	at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:126)
	at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:152)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:135)
	at com.hazelcast.test.TestHazelcastInstanceFactory.newHazelcastInstance(TestHazelcastInstanceFactory.java:80)
	at com.hazelcast.test.TestHazelcastInstanceFactory.newInstances(TestHazelcastInstanceFactory.java:96)
	at com.hazelcast.test.TestHazelcastInstanceFactory.newInstances(TestHazelcastInstanceFactory.java:102)
	at com.hazelcast.test.TestHazelcastInstanceFactory.newInstances(TestHazelcastInstanceFactory.java:90)
	at com.hazelcast.concurrent.lock.LockBasicDistributedTest.newInstances(LockBasicDistributedTest.java:14)
	at com.hazelcast.concurrent.lock.LockBasicTest.setup(LockBasicTest.java:51)
	at sun.reflect.GeneratedMethodAccessor94.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at com.hazelcast.test.HazelcastParallelClassRunner.access$201(HazelcastParallelClassRunner.java:29)
	at com.hazelcast.test.HazelcastParallelClassRunner$TestRunner.run(HazelcastParallelClassRunner.java:89)
	at java.lang.Thread.run(Thread.java:662)
```

I believe issue is related with mock joiner since there is hardcoded 1000 times join retry in the mock joiner with 50 ms interval which sums up 50 seconds and the join in this particular test is slow. We can increase this retry count and see if this is going to fail again.
