### ISSUE TITLE
MapLoaderTest.testMapCanBeLoaded_whenLoadAllKeysThrowsExceptionFirstTime

### ISSUE THREAD

**Issue by mesutcelik** [hazelcast/hazelcast#5453]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK7/558/artifact/hazelcast/target/surefire-reports/com.hazelcast.map.mapstore.MapLoaderTest-output.txt

It is weird that it tries to connect Man Center

```
http://127.0.0.1:8090/mancenter
04:24:25,085 DEBUG [ManagementCenterService] hz._hzInstance_2628_dev.MC.State.Sender - [127.0.0.1]:7675 [dev] [3.5-EA2-SNAPSHOT] Opening collector connection:http://127.0.0.1:8090/mancenter/collector.do
04:24:25,085 DEBUG [ManagementCenterService] hz._hzInstance_2628_dev.MC.Task.Poller - [127.0.0.1]:7675 [dev] [3.5-EA2-SNAPSHOT] Opening getTask connection:http://127.0.0.1:8090/mancenter/getTask.do?member=127.0.0.1:7675&cluster=dev
04:24:25,086 DEBUG [ManagementCenterService] hz._hzInstance_2628_dev.MC.Task.Poller - [127.0.0.1]:7675 [dev] [3.5-EA2-SNAPSHOT] Failed to connect to management center
java.net.ConnectException: Connection refused
    at java.net.PlainSocketImpl.socketConnect(Native Method)
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
    at java.net.Socket.connect(Socket.java:579)
    at java.net.Socket.connect(Socket.java:528)
    at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
    at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
    at sun.net.www.http.HttpClient.New(HttpClient.java:308)
    at sun.net.www.http.HttpClient.New(HttpClient.java:326)
    at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:996)
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:932)
    at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:850)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1300)
    at com.hazelcast.internal.management.ManagementCenterService$TaskPollThread.openTaskInputStream(ManagementCenterService.java:495)
    at com.hazelcast.internal.management.ManagementCenterService$TaskPollThread.processTask(ManagementCenterService.java:435)
    at com.hazelcast.internal.management.ManagementCenterService$TaskPollThread.run(ManagementCenterService.java:416)
```

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK8-Quality-Outreach/com.hazelcast$hazelcast/82/testReport/junit/com.hazelcast.map.mapstore/MapLoaderTest/testMapCanBeLoaded_whenLoadAllKeysThrowsExceptionFirstTime/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.map.mapstore.MapLoaderTest.testMapCanBeLoaded_whenLoadAllKeysThrowsExceptionFirstTime(MapLoaderTest.java:171)
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x/com.hazelcast$hazelcast/3938/testReport/junit/com.hazelcast.map.mapstore/MapLoaderTest/testMapCanBeLoaded_whenLoadAllKeysThrowsExceptionFirstTime/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.6/com.hazelcast$hazelcast/720/testReport/junit/com.hazelcast.map.mapstore/MapLoaderTest/testMapCanBeLoaded_whenLoadAllKeysThrowsExceptionFirstTime/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-ZuluJDK6/com.hazelcast$hazelcast/10/testReport/junit/com.hazelcast.map.mapstore/MapLoaderTest/testMapCanBeLoaded_whenLoadAllKeysThrowsExceptionFirstTime/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x/com.hazelcast$hazelcast/4002/testReport/junit/com.hazelcast.map.mapstore/MapLoaderTest/testMapCanBeLoaded_whenLoadAllKeysThrowsExceptionFirstTime/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/lab-fast-pr/62/testReport/junit/com.hazelcast.map.mapstore/MapLoaderTest/testMapCanBeLoaded_whenLoadAllKeysThrowsExceptionFirstTime/

**Comment by Donnerbart** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-pr-builder/com.hazelcast$hazelcast/16855/testReport/junit/com.hazelcast.map.mapstore/MapLoaderTest/testMapCanBeLoaded_whenLoadAllKeysThrowsExceptionFirstTime/

**Comment by gurbuzali** [comment]
last 2 failure links are not reachable

**Comment by gurbuzali** [comment]
possible fix https://github.com/hazelcast/hazelcast/commit/10646709e0e7306fb2d837294387fbd489fddb39

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.map.mapstore.MapLoaderTest.testMapCanBeLoaded_whenLoadAllKeysThrowsExceptionFirstTime(MapLoaderTest.java:175)
```
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.6/com.hazelcast$hazelcast/761/testReport/junit/com.hazelcast.map.mapstore/MapLoaderTest/testMapCanBeLoaded_whenLoadAllKeysThrowsExceptionFirstTime/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.map.mapstore.MapLoaderTest.testMapCanBeLoaded_whenLoadAllKeysThrowsExceptionFirstTime(MapLoaderTest.java:175)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.6/768/com.hazelcast$hazelcast/testReport/com.hazelcast.topic/TopicTest/testTopicCluster/

**Comment by tombujok** [comment]
Failed today on my local Ubuntu JDK1.6 installation in an overnight run on the 18808th execution.
```
---> Repeating test xceptionFirstTime], run count [18808]
THREAD DUMP FOR TEST FAILURE: "expected:<1> but was:<0>" at "testMapCanBeLoaded_whenLoadAllKeysThrowsExceptionFirstTime"


java.lang.AssertionError: 
Expected :1
Actual   :0
 <Click to see difference>


	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.map.impl.mapstore.MapLoaderTest.testMapCanBeLoaded_whenLoadAllKeysThrowsExceptionFirstTime(MapLoaderTest.java:171)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:37)
	at java.lang.reflect.Method.invoke(Method.java:611)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:314)
	at java.util.concurrent.FutureTask.run(FutureTask.java:149)
	at java.lang.Thread.run(Thread.java:767)

Finished Running Test: testMapCanBeLoaded_whenLoadAllKeysThrowsExceptionFirstTime in 36630.301 seconds.

Process finished with exit code 255
```

**Comment by tombujok** [comment]
I managed to reproduce it with the following config too:
```
        config.setProperty(GroupProperty.GENERIC_OPERATION_THREAD_COUNT, "1");
        config.setProperty(GroupProperty.PARTITION_COUNT, "2");
        config.setProperty(GroupProperty.PARTITION_OPERATION_THREAD_COUNT, "1");
```

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.map.mapstore.MapLoaderTest.testMapCanBeLoaded_whenLoadAllKeysThrowsExceptionFirstTime(MapLoaderTest.java:173)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-IbmJDK1.6/com.hazelcast$hazelcast/326/testReport/junit/com.hazelcast.map.mapstore/MapLoaderTest/testMapCanBeLoaded_whenLoadAllKeysThrowsExceptionFirstTime/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.map.mapstore.MapLoaderTest.testMapCanBeLoaded_whenLoadAllKeysThrowsExceptionFirstTime(MapLoaderTest.java:173)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.maintenance-IbmJDK1.6/com.hazelcast$hazelcast/326/testReport/junit/com.hazelcast.map.mapstore/MapLoaderTest/testMapCanBeLoaded_whenLoadAllKeysThrowsExceptionFirstTime/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.map.impl.mapstore.MapLoaderTest.testMapCanBeLoaded_whenLoadAllKeysThrowsExceptionFirstTime(MapLoaderTest.java:221)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast$hazelcast/796/testReport/junit/com.hazelcast.map.impl.mapstore/MapLoaderTest/testMapCanBeLoaded_whenLoadAllKeysThrowsExceptionFirstTime/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.8/com.hazelcast$hazelcast/115/testReport/junit/com.hazelcast.map.impl.mapstore/MapLoaderTest/testMapCanBeLoaded_whenLoadAllKeysThrowsExceptionFirstTime/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast$hazelcast/812/testReport/junit/com.hazelcast.map.impl.mapstore/MapLoaderTest/testMapCanBeLoaded_whenLoadAllKeysThrowsExceptionFirstTime/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.map.impl.mapstore.MapLoaderTest.testMapCanBeLoaded_whenLoadAllKeysThrowsExceptionFirstTime(MapLoaderTest.java:221)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK1.8/com.hazelcast$hazelcast/132/testReport/junit/com.hazelcast.map.impl.mapstore/MapLoaderTest/testMapCanBeLoaded_whenLoadAllKeysThrowsExceptionFirstTime/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.map.impl.mapstore.MapLoaderTest.testMapCanBeLoaded_whenLoadAllKeysThrowsExceptionFirstTime(MapLoaderTest.java:221)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.maintenance-IbmJDK1.7/com.hazelcast$hazelcast/358/testReport/junit/com.hazelcast.map.impl.mapstore/MapLoaderTest/testMapCanBeLoaded_whenLoadAllKeysThrowsExceptionFirstTime/

**Comment by mdogan** [comment]
Another failure: https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/2405/testReport/junit/com.hazelcast.map.impl.mapstore/MapLoaderTest/testMapCanBeLoaded_whenLoadAllKeysThrowsExceptionFirstTime/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.map.impl.mapstore.MapLoaderTest.testMapCanBeLoaded_whenLoadAllKeysThrowsExceptionFirstTime(MapLoaderTest.java:221)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-sonar/com.hazelcast$hazelcast/1035/testReport/junit/com.hazelcast.map.impl.mapstore/MapLoaderTest/testMapCanBeLoaded_whenLoadAllKeysThrowsExceptionFirstTime/

**Comment by Donnerbart** [comment]
**Error Message**
expected:<1> but was:<0>

**Stacktrace**
```
java.lang.AssertionError: expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.map.impl.mapstore.MapLoaderTest.testMapCanBeLoaded_whenLoadAllKeysThrowsExceptionFirstTime(MapLoaderTest.java:221)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/2901/testReport/junit/com.hazelcast.map.impl.mapstore/MapLoaderTest/testMapCanBeLoaded_whenLoadAllKeysThrowsExceptionFirstTime/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.map.impl.mapstore.MapLoaderTest.testMapCanBeLoaded_whenLoadAllKeysThrowsExceptionFirstTime(MapLoaderTest.java:221)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast$hazelcast/898/testReport/junit/com.hazelcast.map.impl.mapstore/MapLoaderTest/testMapCanBeLoaded_whenLoadAllKeysThrowsExceptionFirstTime/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.map.impl.mapstore.MapLoaderTest.testMapCanBeLoaded_whenLoadAllKeysThrowsExceptionFirstTime(MapLoaderTest.java:221)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x/com.hazelcast$hazelcast/5051/testReport/junit/com.hazelcast.map.impl.mapstore/MapLoaderTest/testMapCanBeLoaded_whenLoadAllKeysThrowsExceptionFirstTime/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.map.impl.mapstore.MapLoaderTest.testMapCanBeLoaded_whenLoadAllKeysThrowsExceptionFirstTime(MapLoaderTest.java:221)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-ZuluJDK8/com.hazelcast$hazelcast/206/testReport/junit/com.hazelcast.map.impl.mapstore/MapLoaderTest/testMapCanBeLoaded_whenLoadAllKeysThrowsExceptionFirstTime/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.map.impl.mapstore.MapLoaderTest.testMapCanBeLoaded_whenLoadAllKeysThrowsExceptionFirstTime(MapLoaderTest.java:221)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-OracleJDK1.7/lastBuild/com.hazelcast$hazelcast/testReport/com.hazelcast.map.impl.mapstore/MapLoaderTest/testMapCanBeLoaded_whenLoadAllKeysThrowsExceptionFirstTime/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.map.impl.mapstore.MapLoaderTest.testMapCanBeLoaded_whenLoadAllKeysThrowsExceptionFirstTime(MapLoaderTest.java:221)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-ZuluJDK6/com.hazelcast$hazelcast/222/testReport/junit/com.hazelcast.map.impl.mapstore/MapLoaderTest/testMapCanBeLoaded_whenLoadAllKeysThrowsExceptionFirstTime/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/new-lab-fast-pr/3519/testReport/junit/com.hazelcast.map.impl.mapstore/MapLoaderTest/testMapCanBeLoaded_whenLoadAllKeysThrowsExceptionFirstTime/

**Comment by Holmistr** [comment]
*master* (commit 2d4acbc2f714b9fa2dceb6f5e76a909b2a2ebb7a)

Failed again on Zulu JDK9: https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-ZuluJDK9/5/testReport/com.hazelcast.map.impl.mapstore/MapLoaderTest/testMapCanBeLoaded_whenLoadAllKeysThrowsExceptionFirstTime/

Stacktrace:
```
java.lang.IllegalStateException: Intentional exception
	at com.hazelcast.map.impl.mapstore.MapLoaderTest$FailingMapLoader.loadAllKeys(MapLoaderTest.java:925)
	at com.hazelcast.map.impl.mapstore.MapLoaderTest$FailingMapLoader.loadAllKeys(MapLoaderTest.java:918)
	at com.hazelcast.map.impl.MapStoreWrapper.loadAllKeys(MapStoreWrapper.java:152)
	at com.hazelcast.map.impl.mapstore.BasicMapStoreContext.loadAllKeys(BasicMapStoreContext.java:180)
	at com.hazelcast.map.impl.MapKeyLoader.sendKeysInBatches(MapKeyLoader.java:433)
	at com.hazelcast.map.impl.MapKeyLoader.access$200(MapKeyLoader.java:73)
	at com.hazelcast.map.impl.MapKeyLoader$1.call(MapKeyLoader.java:245)
	at com.hazelcast.map.impl.MapKeyLoader$1.call(MapKeyLoader.java:242)
	at com.hazelcast.util.executor.CompletableFutureTask.run(CompletableFutureTask.java:67)
	at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:227)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.base/java.lang.Thread.run(Thread.java:844)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:127)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:79)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:154)
	at com.hazelcast.spi.impl.operationservice.impl.InvokeOnPartitions.retryFailedPartitions(InvokeOnPartitions.java:144)
	at com.hazelcast.spi.impl.operationservice.impl.InvokeOnPartitions.invoke(InvokeOnPartitions.java:74)
	at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.invokeOnAllPartitions(OperationServiceImpl.java:386)
	at com.hazelcast.map.impl.proxy.MapProxySupport.size(MapProxySupport.java:713)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.size(MapProxyImpl.java:107)
	at com.hazelcast.map.impl.mapstore.MapLoaderTest.testMapCanBeLoaded_whenLoadAllKeysThrowsExceptionFirstTime(MapLoaderTest.java:631)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

Standard output:
```
09:47:34,760 ERROR |testMapCanBeLoaded_whenLoadAllKeysThrowsExceptionFirstTime| - [DefaultRecordStore] hz._hzInstance_5903_dev.partition-operation.thread-42 - [127.0.0.1]:5702 [dev] [3.11-SNAPSHOT] Exception while loading map com.hazelcast.map.impl.mapstore.MapLoaderTest
java.lang.IllegalStateException: Intentional exception
	at com.hazelcast.map.impl.mapstore.MapLoaderTest$FailingMapLoader.loadAllKeys(MapLoaderTest.java:925) ~[test-classes/:?]
	at com.hazelcast.map.impl.mapstore.MapLoaderTest$FailingMapLoader.loadAllKeys(MapLoaderTest.java:918) ~[test-classes/:?]
	at com.hazelcast.map.impl.MapStoreWrapper.loadAllKeys(MapStoreWrapper.java:152) ~[classes/:?]
	at com.hazelcast.map.impl.mapstore.BasicMapStoreContext.loadAllKeys(BasicMapStoreContext.java:180) ~[classes/:?]
	at com.hazelcast.map.impl.MapKeyLoader.sendKeysInBatches(MapKeyLoader.java:433) ~[classes/:?]
	at com.hazelcast.map.impl.MapKeyLoader.access$200(MapKeyLoader.java:73) ~[classes/:?]
	at com.hazelcast.map.impl.MapKeyLoader$1.call(MapKeyLoader.java:245) ~[classes/:?]
	at com.hazelcast.map.impl.MapKeyLoader$1.call(MapKeyLoader.java:242) ~[classes/:?]
	at com.hazelcast.util.executor.CompletableFutureTask.run(CompletableFutureTask.java:67) ~[classes/:?]
	at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:227) ~[classes/:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:844) ~[?:?]
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64) ~[classes/:?]
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80) ~[classes/:?]
09:47:34,761 ERROR |testMapCanBeLoaded_whenLoadAllKeysThrowsExceptionFirstTime| - [GetOperation] hz._hzInstance_5903_dev.partition-operation.thread-42 - [127.0.0.1]:5702 [dev] [3.11-SNAPSHOT] Intentional exception
java.lang.IllegalStateException: Intentional exception
	at com.hazelcast.map.impl.mapstore.MapLoaderTest$FailingMapLoader.loadAllKeys(MapLoaderTest.java:925) ~[test-classes/:?]
	at com.hazelcast.map.impl.mapstore.MapLoaderTest$FailingMapLoader.loadAllKeys(MapLoaderTest.java:918) ~[test-classes/:?]
	at com.hazelcast.map.impl.MapStoreWrapper.loadAllKeys(MapStoreWrapper.java:152) ~[classes/:?]
	at com.hazelcast.map.impl.mapstore.BasicMapStoreContext.loadAllKeys(BasicMapStoreContext.java:180) ~[classes/:?]
	at com.hazelcast.map.impl.MapKeyLoader.sendKeysInBatches(MapKeyLoader.java:433) ~[classes/:?]
	at com.hazelcast.map.impl.MapKeyLoader.access$200(MapKeyLoader.java:73) ~[classes/:?]
	at com.hazelcast.map.impl.MapKeyLoader$1.call(MapKeyLoader.java:245) ~[classes/:?]
	at com.hazelcast.map.impl.MapKeyLoader$1.call(MapKeyLoader.java:242) ~[classes/:?]
	at com.hazelcast.util.executor.CompletableFutureTask.run(CompletableFutureTask.java:67) ~[classes/:?]
	at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:227) ~[classes/:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:844) ~[?:?]
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64) ~[classes/:?]
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80) ~[classes/:?]
```

Standard output:
```
Hiccups measured while running test 'testMapCanBeLoaded_whenLoadAllKeysThrowsExceptionFirstTime(com.hazelcast.map.impl.mapstore.MapLoaderTest):'
09:47:30, accumulated pauses: 244 ms, max pause: 214 ms, pauses over 1000 ms: 0
09:47:35, accumulated pauses: 0 ms, max pause: 0 ms, pauses over 1000 ms: 0
```
