### ISSUE TITLE
[TEST-FAILURE] RingbufferContainerSerializationTest.whenObjectInMemoryFormat_andTTLEnabled

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#5463]
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.ringbuffer.impl.RingbufferContainerSerializationTest.testSerialization(RingbufferContainerSerializationTest.java:133)
	at com.hazelcast.ringbuffer.impl.RingbufferContainerSerializationTest.test(RingbufferContainerSerializationTest.java:92)
	at com.hazelcast.ringbuffer.impl.RingbufferContainerSerializationTest.whenObjectInMemoryFormat_andTTLEnabled(RingbufferContainerSerializationTest.java:61)
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x/com.hazelcast$hazelcast/3292/testReport/junit/com.hazelcast.ringbuffer.impl/RingbufferContainerSerializationTest/whenObjectInMemoryFormat_andTTLEnabled/

**Comment by pveentjer** [comment]
The probably cause is that the time window in the test was too small and if a big delay is happening, the test fails for false reasons. I have double the time window from 1 second to 2 seconds to reduce the chance this happens again.
