### ISSUE TITLE
[ringbuffer] RingbufferAddAllReadManyStressTest.whenShortTTLAndBigBuffer

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#5498]
```
No error should have been thrown, but ConsumeThread-1 completed error expected null, but was:
<java.util.concurrent.ExecutionException: com.hazelcast.ringbuffer.StaleSequenceException: 
sequence:1123660 is too small. The current headSequence is:1123668>
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-nightly/509/com.hazelcast$hazelcast/testReport/com.hazelcast.ringbuffer.impl/RingbufferAddAllReadManyStressTest/whenShortTTLAndBigBuffer/

**Comment by pveentjer** [comment]
The consumer must have run behind and then you get into this behavior. Perhaps a gc or something. I'll increase the TTL or the size of the buffer.

**Comment by pveentjer** [comment]
Ok. I have increased the TTL; this should prevent running into spurious failures due to a slow environment.

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: No error should have been thrown, but ConsumeThread-2 completed error expected null, but was:<java.util.concurrent.ExecutionException: com.hazelcast.ringbuffer.StaleSequenceException: sequence:76334 is too small. The current headSequence is:76357>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotNull(Assert.java:755)
	at org.junit.Assert.assertNull(Assert.java:737)
	at com.hazelcast.test.TestThread.assertSucceedsEventually(TestThread.java:60)
	at com.hazelcast.ringbuffer.impl.RingbufferAddAllReadManyStressTest.test(RingbufferAddAllReadManyStressTest.java:87)
	at com.hazelcast.ringbuffer.impl.RingbufferAddAllReadManyStressTest.whenShortTTLAndBigBuffer(RingbufferAddAllReadManyStressTest.java:62)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-nightly/com.hazelcast$hazelcast/691/testReport/junit/com.hazelcast.ringbuffer.impl/RingbufferAddAllReadManyStressTest/whenShortTTLAndBigBuffer/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: No error should have been thrown, but ConsumeThread-2 completed error expected null, but was:<java.util.concurrent.ExecutionException: com.hazelcast.ringbuffer.StaleSequenceException: sequence:82927 is too small. The current headSequence is:82989>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotNull(Assert.java:755)
	at org.junit.Assert.assertNull(Assert.java:737)
	at com.hazelcast.test.TestThread.assertSucceedsEventually(TestThread.java:60)
	at com.hazelcast.ringbuffer.impl.RingbufferAddAllReadManyStressTest.test(RingbufferAddAllReadManyStressTest.java:87)
	at com.hazelcast.ringbuffer.impl.RingbufferAddAllReadManyStressTest.whenShortTTLAndBigBuffer(RingbufferAddAllReadManyStressTest.java:62)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-nightly/com.hazelcast$hazelcast/696/testReport/junit/com.hazelcast.ringbuffer.impl/RingbufferAddAllReadManyStressTest/whenShortTTLAndBigBuffer/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: No error should have been thrown, but ConsumeThread-1 completed error expected null, but was:<java.util.concurrent.ExecutionException: com.hazelcast.ringbuffer.StaleSequenceException: sequence:82361 is too small. The current headSequence is:82386>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotNull(Assert.java:755)
	at org.junit.Assert.assertNull(Assert.java:737)
	at com.hazelcast.test.TestThread.assertSucceedsEventually(TestThread.java:60)
	at com.hazelcast.ringbuffer.impl.RingbufferAddAllReadManyStressTest.test(RingbufferAddAllReadManyStressTest.java:86)
	at com.hazelcast.ringbuffer.impl.RingbufferAddAllReadManyStressTest.whenShortTTLAndBigBuffer(RingbufferAddAllReadManyStressTest.java:62)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-nightly/com.hazelcast$hazelcast/704/testReport/junit/com.hazelcast.ringbuffer.impl/RingbufferAddAllReadManyStressTest/whenShortTTLAndBigBuffer/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-nightly/705/com.hazelcast$hazelcast/testReport/com.hazelcast.ringbuffer.impl/RingbufferAddAllReadManyStressTest/whenShortTTLAndBigBuffer/

**Comment by mesutcelik** [comment]
fixed by https://github.com/hazelcast/hazelcast/issues/7187

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: No error should have been thrown, but ConsumeThread-2 completed error expected null, but was:<java.util.concurrent.ExecutionException: com.hazelcast.ringbuffer.StaleSequenceException: sequence:43046 is too small. The current headSequence is:43095 tailSequence is:43094>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotNull(Assert.java:755)
	at org.junit.Assert.assertNull(Assert.java:737)
	at com.hazelcast.test.TestThread.assertSucceedsEventually(TestThread.java:62)
	at com.hazelcast.ringbuffer.impl.RingbufferAddAllReadManyStressTest.test(RingbufferAddAllReadManyStressTest.java:105)
	at com.hazelcast.ringbuffer.impl.RingbufferAddAllReadManyStressTest.whenShortTTLAndBigBuffer(RingbufferAddAllReadManyStressTest.java:79)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/1055/testReport/junit/com.hazelcast.ringbuffer.impl/RingbufferAddAllReadManyStressTest/whenShortTTLAndBigBuffer/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: No error should have been thrown, but ConsumeThread-1 completed error expected null, but was:<java.util.concurrent.ExecutionException: com.hazelcast.ringbuffer.StaleSequenceException: sequence:10 is too small. The current headSequence is:97 tailSequence is:96>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotNull(Assert.java:755)
	at org.junit.Assert.assertNull(Assert.java:737)
	at com.hazelcast.test.TestThread.assertSucceedsEventually(TestThread.java:62)
	at com.hazelcast.ringbuffer.impl.RingbufferAddAllReadManyStressTest.test(RingbufferAddAllReadManyStressTest.java:104)
	at com.hazelcast.ringbuffer.impl.RingbufferAddAllReadManyStressTest.whenShortTTLAndBigBuffer(RingbufferAddAllReadManyStressTest.java:79)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/1082/testReport/junit/com.hazelcast.ringbuffer.impl/RingbufferAddAllReadManyStressTest/whenShortTTLAndBigBuffer/

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/1084/testReport/junit/com.hazelcast.ringbuffer.impl/RingbufferAddAllReadManyStressTest/whenShortTTLAndBigBuffer/

**Comment by jerrinot** [comment]
fixed by #9505

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: No error should have been thrown, but ConsumeThread-1 completed error expected null, but was:<java.util.concurrent.ExecutionException: com.hazelcast.ringbuffer.StaleSequenceException: sequence:5405 is too small and data store is disabled. The current headSequence is:5408 tailSequence is:5407>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotNull(Assert.java:755)
	at org.junit.Assert.assertNull(Assert.java:737)
	at com.hazelcast.test.TestThread.assertSucceedsEventually(TestThread.java:62)
	at com.hazelcast.ringbuffer.impl.RingbufferAddAllReadManyStressTest.test(RingbufferAddAllReadManyStressTest.java:104)
	at com.hazelcast.ringbuffer.impl.RingbufferAddAllReadManyStressTest.whenShortTTLAndBigBuffer(RingbufferAddAllReadManyStressTest.java:79)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/1212/testReport/junit/com.hazelcast.ringbuffer.impl/RingbufferAddAllReadManyStressTest/whenShortTTLAndBigBuffer/

**Comment by hasancelik** [comment]
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.util.Arrays.copyOf(Arrays.java:2367)
	at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:130)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:114)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:415)
	at java.lang.StringBuilder.append(StringBuilder.java:132)
	at java.lang.StringBuilder.append(StringBuilder.java:128)
	at java.lang.AssertionError.<init>(AssertionError.java:74)
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at com.hazelcast.test.TestThread$1.run(TestThread.java:68)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:967)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:984)
	at com.hazelcast.test.TestThread.assertTerminates(TestThread.java:65)
	at com.hazelcast.test.TestThread.assertSucceedsEventually(TestThread.java:77)
	at com.hazelcast.ringbuffer.impl.RingbufferAddAllReadManyStressTest.test(RingbufferAddAllReadManyStressTest.java:119)
	at com.hazelcast.ringbuffer.impl.RingbufferAddAllReadManyStressTest.whenShortTTLAndBigBuffer(RingbufferAddAllReadManyStressTest.java:95)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/1274/testReport/junit/com.hazelcast.ringbuffer.impl/RingbufferAddAllReadManyStressTest/whenShortTTLAndBigBuffer/

**Comment by Donnerbart** [comment]
These tests are also failing in the Hazelcast 4 nightly builds:
**RingbufferAddAllReadManyStressTest.whenNoTTL**
```java
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.lang.Thread.sleep(Native Method)
	at java.lang.Thread.sleep(Thread.java:340)
	at java.util.concurrent.TimeUnit.sleep(TimeUnit.java:386)
	at com.hazelcast.test.HazelcastTestSupport.sleepSeconds(HazelcastTestSupport.java:296)
	at com.hazelcast.test.HazelcastTestSupport.sleepAndStop(HazelcastTestSupport.java:318)
	at com.hazelcast.ringbuffer.impl.RingbufferAddAllReadManyStressTest.test(RingbufferAddAllReadManyStressTest.java:116)
	at com.hazelcast.ringbuffer.impl.RingbufferAddAllReadManyStressTest.whenNoTTL(RingbufferAddAllReadManyStressTest.java:70)
```

**RingbufferAddAllReadManyStressTest.whenShortTTLAndBigBuffer**
```java
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.lang.Thread.sleep(Native Method)
	at java.lang.Thread.sleep(Thread.java:340)
	at java.util.concurrent.TimeUnit.sleep(TimeUnit.java:386)
	at com.hazelcast.test.HazelcastTestSupport.sleepSeconds(HazelcastTestSupport.java:296)
	at com.hazelcast.test.HazelcastTestSupport.sleepAndStop(HazelcastTestSupport.java:318)
	at com.hazelcast.ringbuffer.impl.RingbufferAddAllReadManyStressTest.test(RingbufferAddAllReadManyStressTest.java:116)
	at com.hazelcast.ringbuffer.impl.RingbufferAddAllReadManyStressTest.whenShortTTLAndBigBuffer(RingbufferAddAllReadManyStressTest.java:95)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%204/job/Hazelcast-4.x-nightly/93/testReport/

**Comment by mmedenjak** [comment]
The hazelcast-4.x tests were running for over 5 minutes and were preempted but showed no signs of errors. The logs for the Hazelcast-3.x-nightly/1274 are in the amazon glacier and it would cost us to get to them. Probably it is also a result of a slow environment. Will try and check if there is a way of optimising the test to run faster.

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: No error should have been thrown, but ProduceThread completed error expected null, but was:<java.lang.OutOfMemoryError: Java heap space>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotNull(Assert.java:755)
	at org.junit.Assert.assertNull(Assert.java:737)
	at com.hazelcast.test.TestThread.assertSucceedsEventually(TestThread.java:78)
	at com.hazelcast.ringbuffer.impl.RingbufferAddAllReadManyStressTest.test(RingbufferAddAllReadManyStressTest.java:120)
	at com.hazelcast.ringbuffer.impl.RingbufferAddAllReadManyStressTest.whenShortTTLAndBigBuffer(RingbufferAddAllReadManyStressTest.java:96)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/1470/testReport/junit/com.hazelcast.ringbuffer.impl/RingbufferAddAllReadManyStressTest/whenShortTTLAndBigBuffer/

**Comment by mmedenjak** [comment]
Ran with nightly builder 5160 times without failure. I will increasing the test duration

**Comment by hasancelik** [comment]
*maintenance*
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.lang.Thread.sleep(Native Method)
	at java.lang.Thread.sleep(Thread.java:340)
	at java.util.concurrent.TimeUnit.sleep(TimeUnit.java:386)
	at com.hazelcast.test.HazelcastTestSupport.sleepSeconds(HazelcastTestSupport.java:316)
	at com.hazelcast.test.HazelcastTestSupport.sleepAndStop(HazelcastTestSupport.java:338)
	at com.hazelcast.ringbuffer.impl.RingbufferAddAllReadManyStressTest.test(RingbufferAddAllReadManyStressTest.java:117)
	at com.hazelcast.ringbuffer.impl.RingbufferAddAllReadManyStressTest.whenShortTTLAndBigBuffer(RingbufferAddAllReadManyStressTest.java:96)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-nightly/com.hazelcast$hazelcast/1389/testReport/junit/com.hazelcast.ringbuffer.impl/RingbufferAddAllReadManyStressTest/whenShortTTLAndBigBuffer/

**Comment by hasancelik** [comment]
**RingbufferAddAllReadManyStressTest.whenNoTTL**
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.lang.Thread.sleep(Native Method)
	at java.lang.Thread.sleep(Thread.java:340)
	at java.util.concurrent.TimeUnit.sleep(TimeUnit.java:386)
	at com.hazelcast.test.HazelcastTestSupport.sleepSeconds(HazelcastTestSupport.java:324)
	at com.hazelcast.test.HazelcastTestSupport.sleepAndStop(HazelcastTestSupport.java:346)
	at com.hazelcast.ringbuffer.impl.RingbufferAddAllReadManyStressTest.test(RingbufferAddAllReadManyStressTest.java:117)
	at com.hazelcast.ringbuffer.impl.RingbufferAddAllReadManyStressTest.whenNoTTL(RingbufferAddAllReadManyStressTest.java:71)
```

**RingbufferAddAllReadManyStressTest.whenShortTTLAndBigBuffer**
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.lang.Thread.sleep(Native Method)
	at java.lang.Thread.sleep(Thread.java:340)
	at java.util.concurrent.TimeUnit.sleep(TimeUnit.java:386)
	at com.hazelcast.test.HazelcastTestSupport.sleepSeconds(HazelcastTestSupport.java:324)
	at com.hazelcast.test.HazelcastTestSupport.sleepAndStop(HazelcastTestSupport.java:346)
	at com.hazelcast.ringbuffer.impl.RingbufferAddAllReadManyStressTest.test(RingbufferAddAllReadManyStressTest.java:117)
	at com.hazelcast.ringbuffer.impl.RingbufferAddAllReadManyStressTest.whenShortTTLAndBigBuffer(RingbufferAddAllReadManyStressTest.java:96)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/1526/

**Comment by hasancelik** [comment]
*master*
**RingbufferAddAllReadManyStressTest.whenNoTTL**
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.lang.Thread.sleep(Native Method)
	at java.lang.Thread.sleep(Thread.java:340)
	at java.util.concurrent.TimeUnit.sleep(TimeUnit.java:386)
	at com.hazelcast.test.HazelcastTestSupport.sleepSeconds(HazelcastTestSupport.java:324)
	at com.hazelcast.test.HazelcastTestSupport.sleepAndStop(HazelcastTestSupport.java:346)
	at com.hazelcast.ringbuffer.impl.RingbufferAddAllReadManyStressTest.test(RingbufferAddAllReadManyStressTest.java:117)
	at com.hazelcast.ringbuffer.impl.RingbufferAddAllReadManyStressTest.whenNoTTL(RingbufferAddAllReadManyStressTest.java:71)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/1535/testReport/junit/com.hazelcast.ringbuffer.impl/RingbufferAddAllReadManyStressTest/whenNoTTL/

**RingbufferAddAllReadManyStressTest.whenShortTTLAndBigBuffer**
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.lang.Thread.sleep(Native Method)
	at java.lang.Thread.sleep(Thread.java:340)
	at java.util.concurrent.TimeUnit.sleep(TimeUnit.java:386)
	at com.hazelcast.test.HazelcastTestSupport.sleepSeconds(HazelcastTestSupport.java:324)
	at com.hazelcast.test.HazelcastTestSupport.sleepAndStop(HazelcastTestSupport.java:346)
	at com.hazelcast.ringbuffer.impl.RingbufferAddAllReadManyStressTest.test(RingbufferAddAllReadManyStressTest.java:117)
	at com.hazelcast.ringbuffer.impl.RingbufferAddAllReadManyStressTest.whenShortTTLAndBigBuffer(RingbufferAddAllReadManyStressTest.java:96)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/1535/testReport/junit/com.hazelcast.ringbuffer.impl/RingbufferAddAllReadManyStressTest/whenShortTTLAndBigBuffer/

**Comment by hasancelik** [comment]
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.lang.Thread.sleep(Native Method)
	at java.lang.Thread.sleep(Thread.java:340)
	at java.util.concurrent.TimeUnit.sleep(TimeUnit.java:386)
	at com.hazelcast.test.HazelcastTestSupport.sleepSeconds(HazelcastTestSupport.java:324)
	at com.hazelcast.test.HazelcastTestSupport.sleepAndStop(HazelcastTestSupport.java:346)
	at com.hazelcast.ringbuffer.impl.RingbufferAddAllReadManyStressTest.test(RingbufferAddAllReadManyStressTest.java:117)
	at com.hazelcast.ringbuffer.impl.RingbufferAddAllReadManyStressTest.whenNoTTL(RingbufferAddAllReadManyStressTest.java:71)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/1536/com.hazelcast$hazelcast/testReport/com.hazelcast.ringbuffer.impl/RingbufferAddAllReadManyStressTest/whenNoTTL/

**Comment by hasancelik** [comment]
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.lang.Thread.sleep(Native Method)
	at java.lang.Thread.sleep(Thread.java:340)
	at java.util.concurrent.TimeUnit.sleep(TimeUnit.java:386)
	at com.hazelcast.test.HazelcastTestSupport.sleepSeconds(HazelcastTestSupport.java:324)
	at com.hazelcast.test.HazelcastTestSupport.sleepAndStop(HazelcastTestSupport.java:346)
	at com.hazelcast.ringbuffer.impl.RingbufferAddAllReadManyStressTest.test(RingbufferAddAllReadManyStressTest.java:117)
	at com.hazelcast.ringbuffer.impl.RingbufferAddAllReadManyStressTest.whenNoTTL(RingbufferAddAllReadManyStressTest.java:71)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/1544/testReport/junit/com.hazelcast.ringbuffer.impl/RingbufferAddAllReadManyStressTest/whenNoTTL/

**Comment by hasancelik** [comment]
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.lang.Thread.sleep(Native Method)
	at java.lang.Thread.sleep(Thread.java:340)
	at java.util.concurrent.TimeUnit.sleep(TimeUnit.java:386)
	at com.hazelcast.test.HazelcastTestSupport.sleepSeconds(HazelcastTestSupport.java:324)
	at com.hazelcast.test.HazelcastTestSupport.sleepAndStop(HazelcastTestSupport.java:346)
	at com.hazelcast.ringbuffer.impl.RingbufferAddAllReadManyStressTest.test(RingbufferAddAllReadManyStressTest.java:117)
	at com.hazelcast.ringbuffer.impl.RingbufferAddAllReadManyStressTest.whenNoTTL(RingbufferAddAllReadManyStressTest.java:71)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/1561/testReport/junit/com.hazelcast.ringbuffer.impl/RingbufferAddAllReadManyStressTest/whenNoTTL/

**Comment by hasancelik** [comment]
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.lang.Thread.sleep(Native Method)
	at java.lang.Thread.sleep(Thread.java:340)
	at java.util.concurrent.TimeUnit.sleep(TimeUnit.java:386)
	at com.hazelcast.test.HazelcastTestSupport.sleepSeconds(HazelcastTestSupport.java:340)
	at com.hazelcast.test.HazelcastTestSupport.sleepAndStop(HazelcastTestSupport.java:362)
	at com.hazelcast.ringbuffer.impl.RingbufferAddAllReadManyStressTest.test(RingbufferAddAllReadManyStressTest.java:117)
	at com.hazelcast.ringbuffer.impl.RingbufferAddAllReadManyStressTest.whenNoTTL(RingbufferAddAllReadManyStressTest.java:71)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/1568/testReport/junit/com.hazelcast.ringbuffer.impl/RingbufferAddAllReadManyStressTest/whenNoTTL/

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/1570/testReport/junit/com.hazelcast.ringbuffer.impl/RingbufferAddAllReadManyStressTest/whenNoTTL/

**Comment by hasancelik** [comment]
*master*
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.util.regex.Pattern$Curly.match0(Pattern.java:4250)
	at java.util.regex.Pattern$Curly.match(Pattern.java:4234)
	at java.util.regex.Pattern$GroupHead.match(Pattern.java:4658)
	at java.util.regex.Pattern$Branch.match(Pattern.java:4604)
	at java.util.regex.Pattern$Branch.match(Pattern.java:4602)
	at java.util.regex.Pattern$BmpCharProperty.match(Pattern.java:3798)
	at java.util.regex.Pattern$Start.match(Pattern.java:3461)
	at java.util.regex.Matcher.search(Matcher.java:1248)
	at java.util.regex.Matcher.find(Matcher.java:664)
	at java.util.Formatter.parse(Formatter.java:2549)
	at java.util.Formatter.format(Formatter.java:2501)
	at java.util.Formatter.format(Formatter.java:2455)
	at java.lang.String.format(String.java:2940)
	at com.hazelcast.test.TestThread$1.run(TestThread.java:68)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1149)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1166)
	at com.hazelcast.test.TestThread.assertTerminates(TestThread.java:65)
	at com.hazelcast.test.TestThread.assertSucceedsEventually(TestThread.java:77)
	at com.hazelcast.ringbuffer.impl.RingbufferAddAllReadManyStressTest.test(RingbufferAddAllReadManyStressTest.java:120)
	at com.hazelcast.ringbuffer.impl.RingbufferAddAllReadManyStressTest.whenNoTTL(RingbufferAddAllReadManyStressTest.java:71)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/1576/testReport/junit/com.hazelcast.ringbuffer.impl/RingbufferAddAllReadManyStressTest/whenNoTTL/

**Comment by hasancelik** [comment]
*maintenance*
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.lang.Thread.sleep(Native Method)
	at java.lang.Thread.sleep(Thread.java:340)
	at java.util.concurrent.TimeUnit.sleep(TimeUnit.java:386)
	at com.hazelcast.test.HazelcastTestSupport.sleepSeconds(HazelcastTestSupport.java:316)
	at com.hazelcast.test.HazelcastTestSupport.sleepAndStop(HazelcastTestSupport.java:338)
	at com.hazelcast.ringbuffer.impl.RingbufferAddAllReadManyStressTest.test(RingbufferAddAllReadManyStressTest.java:117)
	at com.hazelcast.ringbuffer.impl.RingbufferAddAllReadManyStressTest.whenNoTTL(RingbufferAddAllReadManyStressTest.java:71)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-nightly/com.hazelcast$hazelcast/1457/testReport/junit/com.hazelcast.ringbuffer.impl/RingbufferAddAllReadManyStressTest/whenNoTTL/

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-nightly/com.hazelcast$hazelcast/1458/testReport/junit/com.hazelcast.ringbuffer.impl/RingbufferAddAllReadManyStressTest/whenNoTTL/
