### ISSUE TITLE
ClientMapStoreTest.mapSize_After_MapStore_OperationQueue_OverFlow_Test

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#5499]
```
junit.framework.AssertionFailedError: expected:<50000> but was:<50001>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at junit.framework.Assert.assertEquals(Assert.java:241)
	at com.hazelcast.client.map.ClientMapStoreTest.mapSize_After_MapStore_OperationQueue_OverFlow_Test(ClientMapStoreTest.java:142)
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-nightly/com.hazelcast$hazelcast-client/508/testReport/junit/com.hazelcast.client.map/ClientMapStoreTest/mapSize_After_MapStore_OperationQueue_OverFlow_Test/

**Comment by sancar** [comment]
Closing this one since it did not failed last 2 months

**Comment by hasancelik** [comment]
**sonar**
```
java.lang.AssertionError: expected:<50000> but was:<50001>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.client.map.ClientMapStoreTest.mapSize_After_MapStore_OperationQueue_OverFlow_Test(ClientMapStoreTest.java:142)
```

https://hazelcast-l337.ci.cloudbees.com/view/Sonar/job/Hazelcast-3.x-sonar/com.hazelcast$hazelcast-client-legacy/898/testReport/junit/com.hazelcast.client.map/ClientMapStoreTest/mapSize_After_MapStore_OperationQueue_OverFlow_Test/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast-client-legacy/816/testReport/junit/com.hazelcast.client.map/ClientMapStoreTest/mapSize_After_MapStore_OperationQueue_OverFlow_Test/

**Comment by sancar** [comment]
This test can fail if putAsync's take slightly longer time. I have added `Thread.sleep(0, 1);`  inside for loop and test is failing every time with this change. 

As far as I understand, If 50,001  put async's can not be finished in 4 seconds because of environment load, test will fail. 

I could increase the delay seconds but how much ?
I could not find an appropriate way to test this. @ahmetmircik Do you have a suggestion ? or Should I delete the test ?

**Comment by ahmetmircik** [comment]
@sancar since this test is trying to assert that we can not put into imap more than write-behind-queue limit, we can increase the write-behind-delay-seconds to a bigger number like 300 seconds.

**Comment by sancar** [comment]
@ahmetmircik 
 If I increase the 300 seconds, don't I have to increase the thread.sleep with that ? I think we don't want such a long test, do we ?

**Comment by hasancelik** [comment]
```
java.util.concurrent.ExecutionException: com.hazelcast.map.ReachedMaxSizeException: Reached node-wide max capacity for write-behind-stores. Max allowed capacity = [50000], current capacity = [50000], required capacity = [1]
    at com.hazelcast.map.impl.mapstore.writebehind.BoundedWriteBehindQueue.throwException(BoundedWriteBehindQueue.java:215)
    at com.hazelcast.map.impl.mapstore.writebehind.BoundedWriteBehindQueue.addCapacity(BoundedWriteBehindQueue.java:194)
    at com.hazelcast.map.impl.mapstore.writebehind.BoundedWriteBehindQueue.addLast(BoundedWriteBehindQueue.java:77)
    at com.hazelcast.map.impl.mapstore.writebehind.SynchronizedWriteBehindQueue.addLast(SynchronizedWriteBehindQueue.java:55)
    at com.hazelcast.map.impl.mapstore.writebehind.WriteBehindStore.add(WriteBehindStore.java:138)
    at com.hazelcast.map.impl.mapstore.writebehind.WriteBehindStore.add(WriteBehindStore.java:132)
    at com.hazelcast.map.impl.mapstore.writebehind.WriteBehindStore.add(WriteBehindStore.java:43)
    at com.hazelcast.map.impl.recordstore.DefaultRecordStore.putInternal(DefaultRecordStore.java:681)
    at com.hazelcast.map.impl.recordstore.DefaultRecordStore.put(DefaultRecordStore.java:669)
    at com.hazelcast.map.impl.operation.PutOperation.run(PutOperation.java:34)
    at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:172)
    at com.hazelcast.spi.impl.operationexecutor.classic.ClassicOperationExecutor.runOnCallingThread(ClassicOperationExecutor.java:392)
    at com.hazelcast.spi.impl.operationexecutor.classic.ClassicOperationExecutor.runOnCallingThreadIfPossible(ClassicOperationExecutor.java:345)
    at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:259)
    at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:243)
    at com.hazelcast.spi.impl.operationservice.impl.Invocation.invokeInternal(Invocation.java:210)
    at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:180)
    at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:46)
    at com.hazelcast.client.impl.protocol.task.AbstractPartitionMessageTask.processMessage(AbstractPartitionMessageTask.java:65)
    at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:121)
    at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:100)
    at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:127)
    at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.processPartitionSpecificRunnable(OperationThread.java:159)
    at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.process(OperationThread.java:142)
    at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.doRun(OperationThread.java:124)
    at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.run(OperationThread.java:99)
    at ------ End remote and begin local stack-trace ------.(Unknown Source)
    at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveResponse(ClientInvocationFuture.java:133)
    at com.hazelcast.client.spi.impl.ClientInvocationFuture.get(ClientInvocationFuture.java:100)
    at com.hazelcast.client.util.ClientDelegatingFuture.get(ClientDelegatingFuture.java:118)
    at com.hazelcast.client.util.ClientDelegatingFuture.get(ClientDelegatingFuture.java:105)
    at com.hazelcast.client.map.ClientMapStoreTest.mapSize_After_MapStore_OperationQueue_OverFlow_Test(ClientMapStoreTest.java:148)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast%24hazelcast-client/821/testReport/junit/com.hazelcast.client.map/ClientMapStoreTest/mapSize_After_MapStore_OperationQueue_OverFlow_Test/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.client.map.ClientMapStoreTest.mapSize_After_MapStore_OperationQueue_OverFlow_Test(ClientMapStoreTest.java:153)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast-client/826/testReport/junit/com.hazelcast.client.map/ClientMapStoreTest/mapSize_After_MapStore_OperationQueue_OverFlow_Test/

**Comment by hasancelik** [comment]
**maintenance**
```
java.lang.AssertionError: java.util.concurrent.ExecutionException: com.hazelcast.map.ReachedMaxSizeException: Reached node-wide max capacity for write-behind-stores. Max allowed capacity = [50000], current capacity = [50000], required capacity = [1] is not an instanceof com.hazelcast.map.ReachedMaxSizeException
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport.assertInstanceOf(HazelcastTestSupport.java:572)
	at com.hazelcast.client.map.ClientMapStoreTest.mapSize_After_MapStore_OperationQueue_OverFlow_Test(ClientMapStoreTest.java:152)
```
https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.maintenance-nightly/com.hazelcast$hazelcast-client/726/testReport/junit/com.hazelcast.client.map/ClientMapStoreTest/mapSize_After_MapStore_OperationQueue_OverFlow_Test/


**master**
```
java.lang.AssertionError: java.util.concurrent.ExecutionException: com.hazelcast.map.ReachedMaxSizeException: Reached node-wide max capacity for write-behind-stores. Max allowed capacity = [50000], current capacity = [50000], required capacity = [1] is not an instanceof com.hazelcast.map.ReachedMaxSizeException
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport.assertInstanceOf(HazelcastTestSupport.java:617)
	at com.hazelcast.client.map.ClientMapStoreTest.mapSize_After_MapStore_OperationQueue_OverFlow_Test(ClientMapStoreTest.java:153)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast-client/829/testReport/junit/com.hazelcast.client.map/ClientMapStoreTest/mapSize_After_MapStore_OperationQueue_OverFlow_Test/

**Comment by sancar** [comment]
@hasancelik I have updated the tests wrong. These two last failures are because of that. I will update the tests again asap.

**Comment by sancar** [comment]
Not failing at the moment. I have changed the test so that next time it fails we will know which exception we get instead of expected one. Closing to wait a new failure.

**Comment by hasancelik** [comment]
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrow(ClientInvocationFuture.java:74)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrow(ClientInvocationFuture.java:30)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:174)
	at com.hazelcast.client.util.ClientDelegatingFuture.get(ClientDelegatingFuture.java:121)
	at com.hazelcast.client.util.ClientDelegatingFuture.get(ClientDelegatingFuture.java:108)
	at com.hazelcast.client.map.ClientMapStoreTest.mapSize_After_MapStore_OperationQueue_OverFlow_Test(ClientMapStoreTest.java:149)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-sonar/com.hazelcast$hazelcast-client/1041/testReport/junit/com.hazelcast.client.map/ClientMapStoreTest/mapSize_After_MapStore_OperationQueue_OverFlow_Test/

**Comment by hasancelik** [comment]
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.lang.Throwable.getStackTraceElement(Native Method)
	at java.lang.Throwable.getOurStackTrace(Throwable.java:827)
	at java.lang.Throwable.getStackTrace(Throwable.java:816)
	at java.lang.Thread.getStackTrace(Thread.java:1552)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrow(ClientInvocationFuture.java:74)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrow(ClientInvocationFuture.java:30)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:186)
	at com.hazelcast.client.util.ClientDelegatingFuture.get(ClientDelegatingFuture.java:121)
	at com.hazelcast.client.util.ClientDelegatingFuture.get(ClientDelegatingFuture.java:108)
	at com.hazelcast.client.map.ClientMapStoreTest.mapSize_After_MapStore_OperationQueue_OverFlow_Test(ClientMapStoreTest.java:149)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-sonar/com.hazelcast$hazelcast-client/1043/testReport/junit/com.hazelcast.client.map/ClientMapStoreTest/mapSize_After_MapStore_OperationQueue_OverFlow_Test/

**Comment by hasancelik** [comment]
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.lang.Throwable.fillInStackTrace(Native Method)
	at java.lang.Throwable.fillInStackTrace(Throwable.java:783)
	at java.lang.Throwable.<init>(Throwable.java:250)
	at java.lang.Exception.<init>(Exception.java:54)
	at java.lang.Thread.getStackTrace(Thread.java:1552)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrow(ClientInvocationFuture.java:74)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrow(ClientInvocationFuture.java:30)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:174)
	at com.hazelcast.client.util.ClientDelegatingFuture.get(ClientDelegatingFuture.java:121)
	at com.hazelcast.client.util.ClientDelegatingFuture.get(ClientDelegatingFuture.java:108)
	at com.hazelcast.client.map.ClientMapStoreTest.mapSize_After_MapStore_OperationQueue_OverFlow_Test(ClientMapStoreTest.java:149)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-sonar/com.hazelcast$hazelcast-client/1046/testReport/junit/com.hazelcast.client.map/ClientMapStoreTest/mapSize_After_MapStore_OperationQueue_OverFlow_Test/

**Comment by Donnerbart** [comment]
I ran the tests locally to retrieve code coverage data and it failed with this exception:
```
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at com.hazelcast.client.impl.protocol.codec.StackTraceElementCodec.decode(StackTraceElementCodec.java:37)
	at com.hazelcast.client.impl.protocol.codec.ErrorCodec.<init>(ErrorCodec.java:54)
	at com.hazelcast.client.impl.protocol.codec.ErrorCodec.decode(ErrorCodec.java:66)
	at com.hazelcast.client.impl.protocol.ClientExceptionFactory.createException(ClientExceptionFactory.java:584)
	at com.hazelcast.client.spi.impl.ClientInvocationServiceSupport$ResponseThread.handleClientMessage(ClientInvocationServiceSupport.java:326)
	at com.hazelcast.client.spi.impl.ClientInvocationServiceSupport$ResponseThread.process(ClientInvocationServiceSupport.java:308)
	at com.hazelcast.client.spi.impl.ClientInvocationServiceSupport$ResponseThread.doRun(ClientInvocationServiceSupport.java:301)
	at com.hazelcast.client.spi.impl.ClientInvocationServiceSupport$ResponseThread.run(ClientInvocationServiceSupport.java:278)

THREAD DUMP FOR TEST FAILURE: "com.hazelcast.spi.exception.TargetDisconnectedException: Disconnecting from member [127.0.0.1]:6079 due to heartbeat problems. Current time: 2016-05-10 14:00:33.355. Last heartbeat: never is not an instanceof com.hazelcast.map.ReachedMaxSizeException" at "mapSize_After_MapStore_OperationQueue_OverFlow_Test"

(...)

java.lang.AssertionError: com.hazelcast.spi.exception.TargetDisconnectedException: Disconnecting from member [127.0.0.1]:6079 due to heartbeat problems. Current time: 2016-05-10 14:00:33.355. Last heartbeat: never is not an instanceof com.hazelcast.map.ReachedMaxSizeException

	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport.assertInstanceOf(HazelcastTestSupport.java:624)
	at com.hazelcast.client.map.ClientMapStoreTest.mapSize_After_MapStore_OperationQueue_OverFlow_Test(ClientMapStoreTest.java:152)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:88)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:82)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by hasancelik** [comment]
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrow(ClientInvocationFuture.java:74)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrow(ClientInvocationFuture.java:30)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:174)
	at com.hazelcast.client.util.ClientDelegatingFuture.get(ClientDelegatingFuture.java:121)
	at com.hazelcast.client.util.ClientDelegatingFuture.get(ClientDelegatingFuture.java:108)
	at com.hazelcast.client.map.ClientMapStoreTest.mapSize_After_MapStore_OperationQueue_OverFlow_Test(ClientMapStoreTest.java:149)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-sonar/com.hazelcast$hazelcast-client/1049/testReport/junit/com.hazelcast.client.map/ClientMapStoreTest/mapSize_After_MapStore_OperationQueue_OverFlow_Test/

**Comment by hasancelik** [comment]
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:338)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:182)
	at com.hazelcast.client.util.ClientDelegatingFuture.get(ClientDelegatingFuture.java:121)
	at com.hazelcast.client.util.ClientDelegatingFuture.get(ClientDelegatingFuture.java:108)
	at com.hazelcast.client.map.ClientMapStoreTest.mapSize_After_MapStore_OperationQueue_OverFlow_Test(ClientMapStoreTest.java:149)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-sonar/com.hazelcast$hazelcast-client/1054/testReport/junit/com.hazelcast.client.map/ClientMapStoreTest/mapSize_After_MapStore_OperationQueue_OverFlow_Test/

**Comment by hasancelik** [comment]
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.lang.Throwable.fillInStackTrace(Native Method)
	at java.lang.Throwable.fillInStackTrace(Throwable.java:783)
	at java.lang.Throwable.<init>(Throwable.java:250)
	at java.lang.Exception.<init>(Exception.java:54)
	at java.lang.Thread.getStackTrace(Thread.java:1552)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrow(ClientInvocationFuture.java:74)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrow(ClientInvocationFuture.java:30)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:174)
	at com.hazelcast.client.util.ClientDelegatingFuture.get(ClientDelegatingFuture.java:121)
	at com.hazelcast.client.util.ClientDelegatingFuture.get(ClientDelegatingFuture.java:108)
	at com.hazelcast.client.map.ClientMapStoreTest.mapSize_After_MapStore_OperationQueue_OverFlow_Test(ClientMapStoreTest.java:149)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-sonar/1055/com.hazelcast$hazelcast-client/testReport/com.hazelcast.client.map/ClientMapStoreTest/mapSize_After_MapStore_OperationQueue_OverFlow_Test/

**Comment by hasancelik** [comment]
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.lang.Throwable.getStackTraceElement(Native Method)
	at java.lang.Throwable.getOurStackTrace(Throwable.java:827)
	at java.lang.Throwable.getStackTrace(Throwable.java:816)
	at java.lang.Thread.getStackTrace(Thread.java:1552)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrow(ClientInvocationFuture.java:74)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrow(ClientInvocationFuture.java:30)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:174)
	at com.hazelcast.client.util.ClientDelegatingFuture.get(ClientDelegatingFuture.java:121)
	at com.hazelcast.client.util.ClientDelegatingFuture.get(ClientDelegatingFuture.java:108)
	at com.hazelcast.client.map.ClientMapStoreTest.mapSize_After_MapStore_OperationQueue_OverFlow_Test(ClientMapStoreTest.java:149)
```

https://hazelcast-l337.ci.cloudbees.com/view/Sonar/job/Hazelcast-3.x-sonar/com.hazelcast$hazelcast-client/1062/testReport/junit/com.hazelcast.client.map/ClientMapStoreTest/mapSize_After_MapStore_OperationQueue_OverFlow_Test/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: expected null, but was:<Invocation{op=com.hazelcast.spi.impl.operationservice.impl.DummyBackupAwareOperation{serviceName='null', identityHash=582573722, partitionId=1, replicaIndex=0, callId=0, invocationTime=-1 (1970-01-01 01:59:59.999), waitTimeout=-1, callTimeout=9223372036854775807}, tryCount=0, tryPauseMillis=0, invokeCount=0, callTimeoutMillis=20000, firstInvocationTimeMs=1464920582458, firstInvocationTime='2016-06-03 05:23:02.458', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 02:00:00.000', target=[127.0.0.1]:15011, pendingResponse={foo}, backupsAcksExpected=1, backupsAcksReceived=0, connection=null}>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotNull(Assert.java:755)
	at org.junit.Assert.assertNull(Assert.java:737)
	at org.junit.Assert.assertNull(Assert.java:747)
	at com.hazelcast.spi.impl.operationservice.impl.ResponseHandler_NotifyTest.normalResponse_whenBackupMissing_thenEventuallySuccess(ResponseHandler_NotifyTest.java:117)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-sonar/com.hazelcast$hazelcast-client/1079/testReport/junit/com.hazelcast.client.map/ClientMapStoreTest/mapSize_After_MapStore_OperationQueue_OverFlow_Test/

**Comment by hasancelik** [comment]
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:338)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:182)
	at com.hazelcast.client.util.ClientDelegatingFuture.get(ClientDelegatingFuture.java:121)
	at com.hazelcast.client.util.ClientDelegatingFuture.get(ClientDelegatingFuture.java:108)
	at com.hazelcast.client.map.ClientMapStoreTest.mapSize_After_MapStore_OperationQueue_OverFlow_Test(ClientMapStoreTest.java:149)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-sonar/1082/com.hazelcast$hazelcast-client/testReport/com.hazelcast.client.map/ClientMapStoreTest/mapSize_After_MapStore_OperationQueue_OverFlow_Test/

**Comment by hasancelik** [comment]
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.lang.Throwable.getStackTraceElement(Native Method)
	at java.lang.Throwable.getOurStackTrace(Throwable.java:827)
	at java.lang.Throwable.getStackTrace(Throwable.java:816)
	at java.lang.Thread.getStackTrace(Thread.java:1552)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrow(ClientInvocationFuture.java:74)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrow(ClientInvocationFuture.java:30)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:174)
	at com.hazelcast.client.util.ClientDelegatingFuture.get(ClientDelegatingFuture.java:121)
	at com.hazelcast.client.util.ClientDelegatingFuture.get(ClientDelegatingFuture.java:108)
	at com.hazelcast.client.map.ClientMapStoreTest.mapSize_After_MapStore_OperationQueue_OverFlow_Test(ClientMapStoreTest.java:149)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-sonar/com.hazelcast$hazelcast-client/1085/testReport/junit/com.hazelcast.client.map/ClientMapStoreTest/mapSize_After_MapStore_OperationQueue_OverFlow_Test/

**Comment by hasancelik** [comment]
supressed by https://github.com/hazelcast/hazelcast/commit/63c8c38c0cf804506318d414d22145b32b91142f
