### ISSUE TITLE
IExecService.submitToMember(Runnable task, Member member) throws NPE

### ISSUE THREAD

**Issue by dsukhoroslov** [hazelcast/hazelcast#5548]
I have a case when I want to run a task on local member asynchronously, and I don't need a result. So, I implemented a Runnable + IdentifiedDataSerializable (don't see why it is necessary to serialize/deserialize a task when it is invoked on the local member only, BTW). I start my task as:
	execService.submitToMember(new MyTask(<params>),					
							hzInstance.getCluster().getLocalMember(), null);

the task invoked properly and run with no issues. But then I see the following HZ exception in my logs:

<code>
2015-06-21 13:11:35.295 [hz.default.async.thread-3] ERROR com.hazelcast.spi.impl.operationservice.impl.Invocation - [localhost]:10500 [default] [3.5] Failed asynchronous execution of execution callback: com.hazelcast.spi.impl.operationservice.impl.InvocationFuture$ExecutorCallbackAdapter@6abd7d51for call Invocation{ serviceName='hz:impl:executorService', op=com.hazelcast.executor.impl.operations.MemberCallableTaskOperation{serviceName='null', partitionId=-1, callId=0, invocationTime=1434881495295, waitTimeout=-1, callTimeout=60000}, partitionId=-1, replicaIndex=0, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeout=60000, target=Address[localhost]:10500, backupsExpected=0, backupsCompleted=0}
java.lang.NullPointerException: null
	at com.hazelcast.executor.impl.ExecutionCallbackAdapter.notify(ExecutionCallbackAdapter.java:36) ~[hazelcast-all-3.5.jar:3.5]
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture$ExecutorCallbackAdapter.onResponse(InvocationFuture.java:438) ~[hazelcast-all-3.5.jar:3.5]
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture$1.run(InvocationFuture.java:135) ~[hazelcast-all-3.5.jar:3.5]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_75]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_75]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_75]
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76) [hazelcast-all-3.5.jar:3.5]
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92) [hazelcast-all-3.5.jar:3.5]
</code>

It is thown outside of my code, I don't know why. Any ideas why this happens? Please, have a look!

Thanks, Denis.

**Comment by gurbuzali** [comment]
you are passing `ExecutionCallback` as null to the method call, that's why you are getting exception
```
/**
     * Submits a task to the specified member. Caller will be notified for the result of the task by
     * {@link ExecutionCallback#onResponse(Object)} or {@link ExecutionCallback#onFailure(Throwable)}.
     *
     * @param task the task submitted to the specified member
     * @param callback callback
     */
    <T> void submitToMember(Callable<T> task, Member member, ExecutionCallback<T> callback);
```

you can use below method instead if you don't want to use `ExecutionCallback`

```
/**
     * Submits a task to the specified member and returns a Future
     * representing that task.
     *
     * @param task the task submitted to the specified member
     * @param member the specified member
     * @return a Future representing pending completion of the task
     */
    <T> Future<T> submitToMember(Callable<T> task, Member member);
```
