### ISSUE TITLE
[TEST-FAILURE] ClientNearCacheTest.putToCacheAndThenGetFromClientNearCacheWithObjectInMemoryFormat

### ISSUE THREAD

**Issue by mesutcelik** [hazelcast/hazelcast#5576]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.7/594/com.hazelcast$hazelcast-client/testReport/com.hazelcast.client.cache.nearcache/ClientNearCacheTest/putToCacheAndThenGetFromClientNearCacheWithObjectInMemoryFormat/

**Comment by sancar** [comment]
Closing this one since did not failed last 2 months

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: expected:<Value-99> but was:<null>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.client.cache.nearcache.ClientNearCacheTestSupport.putToCacheAndThenGetFromClientNearCache(ClientNearCacheTestSupport.java:180)
	at com.hazelcast.client.cache.nearcache.ClientNearCacheTest.putToCacheAndThenGetFromClientNearCacheWithObjectInMemoryFormat(ClientNearCacheTest.java:47)
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK9-Quality-Outreach/com.hazelcast$hazelcast-client-new/228/testReport/junit/com.hazelcast.client.cache.nearcache/ClientNearCacheTest/putToCacheAndThenGetFromClientNearCacheWithObjectInMemoryFormat/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK7/com.hazelcast$hazelcast-client/694/testReport/junit/com.hazelcast.client.cache.nearcache/ClientNearCacheTest/putToCacheAndThenGetFromClientNearCacheWithObjectInMemoryFormat/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OracleJDK1.6/com.hazelcast$hazelcast-client-new/698/testReport/junit/com.hazelcast.client.cache.nearcache/ClientNearCacheTest/putToCacheAndThenGetFromClientNearCacheWithBinaryInMemoryFormat/

**Comment by mdogan** [comment]
A similar failure:

```
com.hazelcast.client.cache.nearcache.ClientNearCacheTest
15:17:00 putToCacheAndThenGetFromClientNearCacheWithBinaryInMemoryFormat(com.hazelcast.client.cache.nearcache.ClientNearCacheTest)  Time elapsed: 0.938 sec  <<< FAILURE!
15:17:00 java.lang.AssertionError: expected:<Value-0> but was:<null>
15:17:00 	at org.junit.Assert.fail(Assert.java:88)
15:17:00 	at org.junit.Assert.failNotEquals(Assert.java:834)
15:17:00 	at org.junit.Assert.assertEquals(Assert.java:118)
15:17:00 	at org.junit.Assert.assertEquals(Assert.java:144)
15:17:00 	at com.hazelcast.client.cache.nearcache.ClientNearCacheTestSupport.putToCacheAndThenGetFromClientNearCache(ClientNearCacheTestSupport.java:180)
15:17:00 	at com.hazelcast.client.cache.nearcache.ClientNearCacheTest.putToCacheAndThenGetFromClientNearCacheWithBinaryInMemoryFormat(ClientNearCacheTest.java:42)
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-pr-builder/com.hazelcast$hazelcast-client/16410/testReport/junit/com.hazelcast.client.cache.nearcache/ClientNearCacheTest/putToCacheAndThenGetFromClientNearCacheWithBinaryInMemoryFormat/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: expected:<Value-0> but was:<null>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.client.cache.nearcache.ClientNearCacheTestSupport$2.run(ClientNearCacheTestSupport.java:187)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:825)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:839)
	at com.hazelcast.client.cache.nearcache.ClientNearCacheTestSupport.putToCacheAndThenGetFromClientNearCache(ClientNearCacheTestSupport.java:184)
	at com.hazelcast.client.cache.nearcache.ClientNearCacheTest.putToCacheAndThenGetFromClientNearCacheWithBinaryInMemoryFormat(ClientNearCacheTest.java:42)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-OracleJDK1.7/com.hazelcast$hazelcast-client-legacy/293/testReport/junit/com.hazelcast.client.cache.nearcache/ClientNearCacheTest/putToCacheAndThenGetFromClientNearCacheWithBinaryInMemoryFormat/

**Comment by serkan-ozal** [comment]
should be fixed via https://github.com/hazelcast/hazelcast/pull/6749
