### ISSUE TITLE
3.5 performance improvement: submitToKeyOwner deserializes request twice.

### ISSUE THREAD

**Issue by oobles** [hazelcast/hazelcast#5578]
While doing some investigation into an issue we have with IExecutor.submitToKeyOwner I notice that the request is deserialized twice for a single call (we are using custom serialization which could be the cause).  These a two stack traces showing the call stacks where deserialization occurs of the request twice.  This has the effect of not allowing ObjectPool patterns for the object we deserialize because the first object is discarded and can't be returned to the ObjectPool.  The second is that it performs work that is thrown away.  In instances where the object is large or deep, this could improve performance considerably.

Here's the two stack traces where the object is read from the same call.

First time object is deserialized:
	at com.hazelcast.nio.serialization.StreamSerializerAdapter.read(StreamSerializerAdapter.java:41)
	at com.hazelcast.nio.serialization.SerializationServiceImpl.readObject(SerializationServiceImpl.java:325)
	at com.hazelcast.nio.serialization.ByteArrayObjectDataInput.readObject(ByteArrayObjectDataInput.java:489)
	at com.hazelcast.executor.impl.client.PartitionTargetCallableRequest.read(PartitionTargetCallableRequest.java:120)
	at com.hazelcast.client.impl.client.ClientRequest.readPortable(ClientRequest.java:97)
	at com.hazelcast.nio.serialization.PortableSerializer.read(PortableSerializer.java:84)
	at com.hazelcast.nio.serialization.PortableSerializer.read(PortableSerializer.java:73)
	at com.hazelcast.nio.serialization.PortableSerializer.read(PortableSerializer.java:29)
	at com.hazelcast.nio.serialization.StreamSerializerAdapter.read(StreamSerializerAdapter.java:41)
	at com.hazelcast.nio.serialization.SerializationServiceImpl.toObject(SerializationServiceImpl.java:276)
	at com.hazelcast.client.impl.ClientEngineImpl$ClientPacketProcessor.loadRequest(ClientEngineImpl.java:391)
	at com.hazelcast.client.impl.ClientEngineImpl$ClientPacketProcessor.run(ClientEngineImpl.java:366)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:100)
	at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.processPartitionSpecificRunnable(OperationThread.java:130)
	at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.process(OperationThread.java:120)
	at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.doRun(OperationThread.java:101)
	at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.run(OperationThread.java:76)

Second time request deserialized:
com.hazelcast.nio.serialization.StreamSerializerAdapter.read(StreamSerializerAdapter.java:41)
	at com.hazelcast.nio.serialization.SerializationServiceImpl.toObject(SerializationServiceImpl.java:276)
	at com.hazelcast.spi.impl.NodeEngineImpl.toObject(NodeEngineImpl.java:200)
	at com.hazelcast.executor.impl.operations.BaseCallableTaskOperation.getCallable(BaseCallableTaskOperation.java:81)
	at com.hazelcast.executor.impl.operations.BaseCallableTaskOperation.beforeRun(BaseCallableTaskOperation.java:63)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:131)
	at com.hazelcast.spi.impl.operationexecutor.classic.ClassicOperationExecutor.runOnCallingThread(ClassicOperationExecutor.java:380)
	at com.hazelcast.spi.impl.operationexecutor.classic.ClassicOperationExecutor.runOnCallingThreadIfPossible(ClassicOperationExecutor.java:342)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:247)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:231)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invokeInternal(Invocation.java:198)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:168)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:51)
	at com.hazelcast.client.impl.client.TargetClientRequest.process(TargetClientRequest.java:36)
	at com.hazelcast.client.impl.ClientEngineImpl$ClientPacketProcessor.processRequest(ClientEngineImpl.java:463)
	at com.hazelcast.client.impl.ClientEngineImpl$ClientPacketProcessor.run(ClientEngineImpl.java:379)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:100)
	at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.processPartitionSpecificRunnable(OperationThread.java:130)
	at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.process(OperationThread.java:120)
	at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.doRun(OperationThread.java:101)
	at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.run(OperationThread.java:76)

**Comment by gurbuzali** [comment]
Hi @oobles,
Thank you for reporting, this is a known issue. the double de-serialization occurs because of client usage, it is not related with customer serializer as you've suspected.

**Comment by oobles** [comment]
Thanks, is this a 3.5 specific issue?  Is this also in 3.4.x?

**Comment by gurbuzali** [comment]
unfortunately yes, it is also in 3.4.x

**Comment by bwzhang2011** [comment]
@gurbuzali, any update with such issue ?

**Comment by jerrinot** [comment]
fixed by #5583
