### ISSUE TITLE
Declaratively disable multicast for hazelcast client

### ISSUE THREAD

**Issue by ssozonoff** [hazelcast/hazelcast#5604]
I am able to add AWS discovery to the XML configuration file for a hazelcast client but then get an error that multicast needs to be disabled. Can't find a way to do this?

**Comment by bilalyasar** [comment]
@ssozonoff , can you post xml file? [ with removing your access and secret key :) ]

**Comment by ssozonoff** [comment]
```xml
<?xml version="1.0" encoding="UTF-8"?>
<hazelcast-client xsi:schemaLocation="http://www.hazelcast.com/schema/client-config hazelcast-client-config-3.5.xsd"
                  xmlns="http://www.hazelcast.com/schema/client-config"
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <group>
        <name>xxxx</name>
        <password>yyyyy</password>
    </group>
    <properties>
        <property name="hazelcast.client.connection.timeout">10000</property>
        <property name="hazelcast.client.retry.count">6</property>
        <property name="hazelcast.prefer.ipv4.stack">true</property>
    </properties>
    <network>
        <smart-routing>true</smart-routing>
        <redo-operation>true</redo-operation>
        <connection-timeout>30000</connection-timeout>

        <aws enabled="true">
            <access-key>111111111111111</access-key>
            <secret-key>2222222222222222</secret-key>
            <region>us-east-1</region>                              <!-- optional, default is us-east-1 -->
            <host-header>ec2.amazonaws.com</host-header>              <!-- optional, default is ec2.amazonaws.com.
                                                If set, region shouldn't be set as it will override this property -->
            <security-group-name>sg_hazelcast</security-group-name> <!-- optional -->
            <tag-key>environment</tag-key>                                  <!-- optional -->
            <tag-value>trial</tag-value>                          <!-- optional -->
        </aws>
    </network>
</hazelcast-client>
```

**Comment by noctarius** [comment]
Just deactivate it the way you enabled aws:
```xml
<network>
  <join>
    <multicast enabled="false" />
    <!-- aws config -->
  </join>
</network>
```

**Comment by ssozonoff** [comment]
Thats what one would expect :-)

Have a look at hazelcast-client-config-3.5.xsd

**Comment by bilalyasar** [comment]
@ssozonoff , can you post your full error log?

**Comment by ssozonoff** [comment]
Caused by: com.hazelcast.config.InvalidConfigurationException: Multicast and AWS join can't be enabled at the same time
	at com.hazelcast.config.JoinConfig.verify(JoinConfig.java:95)
	at com.hazelcast.instance.Node.createJoiner(Node.java:552)
	at com.hazelcast.instance.DefaultNodeContext.createJoiner(DefaultNodeContext.java:35)
	at com.hazelcast.instance.Node.<init>(Node.java:171)
	at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:120)
	at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:152)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:135)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:166)
	... 53 more

**Comment by noctarius** [comment]
@ssozonoff What would that have to do with ClientConfig? It is a server-side error!

**Comment by ssozonoff** [comment]
You are of course right!!! Thats what happens when I cant share the same Hazelcast instance with my L2 Cache layer. Sorry for the confusion guys!

**Comment by noctarius** [comment]
Have you added my code snippet?

**Comment by ssozonoff** [comment]
Well I dont know why I thought this was happening client side. I basically have a server and client setup in the same App, one runnung under Spring and the other is an L2 Cache in the ORM. I got things a little muddled up but clearly disabling multicast works! Thanks
