### ISSUE TITLE
Please provide hibernate5 support

### ISSUE THREAD

**Issue by ptahchiev** [hazelcast/hazelcast#5633]
Following this comment:

https://github.com/hazelcast/hazelcast-hibernate4/issues/2#issuecomment-117240433

I would like to ask you to provide hibernate5 support. If I use hibernate5 I get the following exception:
````
Caused by: java.lang.AbstractMethodError: com.hazelcast.hibernate.HazelcastLocalCacheRegionFactory.start(Lorg/hibernate/boot/spi/SessionFactoryOptions;Ljava/util/Properties;)V
    at org.hibernate.internal.CacheImpl.<init>(CacheImpl.java:48)
    at org.hibernate.engine.spi.CacheInitiator.initiateService(CacheInitiator.java:28)
    at org.hibernate.engine.spi.CacheInitiator.initiateService(CacheInitiator.java:20)
    at org.hibernate.service.internal.SessionFactoryServiceRegistryImpl.initiateService(SessionFactoryServiceRegistryImpl.java:46)
    at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:234)
    at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:208)
    at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:189)
    at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:237)
    at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:445)
    at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:779)
    at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:60)
    at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:343)
    at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:318)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1633)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1570)
    ... 94 more

````

**Comment by bwzhang2011** [comment]
@kobalski, any update with such issue ?

**Comment by ptahchiev** [comment]
hibernate5 is already out

**Comment by bitvector2** [comment]
Any news on this issue?

**Comment by winweb** [comment]
any update with this issue ?

**Comment by mesutcelik** [comment]
Hi @bitvector2 , @winweb , @bwzhang2011 ,

Unfortunately, Hibernate 5 Support is not in our 3.6 roadmap. However, any kind of contribution is very much appreciated. 

We have created a framework for external contributions called [Hazelcast Enhanecement Proposals](https://hazelcast.atlassian.net/wiki/display/COM/Hazelcast+Enhancement+Proposals). please feel free to contact us (cc: @noctarius ) if you are interested to contribute to Hibernate 5 Support for Hazelcast.

We are looking forward to hear from you.

**Comment by winweb** [comment]
@mesutcelik Thanks, for your update.

**Comment by bturner** [comment]
@mesutcelik @noctarius 

If Hazelcast is interested in contributions for this, I'm happy to add it (I already have it working locally, but I need to do some more exhaustive testing before I open a pull request). I contributed support for 4.2 and 4.3 in #2621 and I was involved with changes to how caching worked in #4110, so I know a bit about the Hibernate bits of the system.

Once I've got my testing done, should I open a pull request? (Note: I understand it likely won't get included in 3.6.)

**Comment by noctarius** [comment]
Hey @bturner, we're always happy about contribution :) As you figured out it won't be in 3.6 anymore but it is possible to add it to a later patchlevel and 3.7.

I would say this is not big enough for a HEP, is it? Apart from that, as you mentioned, it is almost done. I suggest just open a PR as you said.

**Comment by gionn** [comment]
@bturner if you open a PR I will test it too

**Comment by ptahchiev** [comment]
@btuner any updates here? :)

**Comment by bturner** [comment]
@gionn @ptahchiev Sorry for the delay. I made my changes against a Hazelcast 3.5 branch, so I'm in the process of updating them for 3.6. Hopefully I'll have that done tomorrow.

**Comment by bturner** [comment]
I've opened #7021 with my Hibernate 5 changes.

**Comment by LoneRifle** [comment]
This issue has been resolved by the above PR and can be considered closed.

**Comment by hho** [comment]
Would be great if 5.x could be added to the [Hazelcast manual](http://docs.hazelcast.org/docs/3.7-EA/manual/html-single/index.html#supported-hibernate-versions) as well.

**Comment by mesutcelik** [comment]
Thanks for raising this @hho
I believe @Serdaro can can fix this.

**Comment by Serdaro** [comment]
@hho , @mesutcelik , It was already included in the README of https://github.com/hazelcast/hazelcast-hibernate. Please note that Hibernate integration is now a plugin (see https://hazelcast.org/plugins/?type=integration) and the documentation is under its own GitHub repo at  https://github.com/hazelcast/hazelcast-hibernate.
