### ISSUE TITLE
com.hazelcast.cluster.impl.TcpIpJoinerOverAWS Server returned HTTP response code: 401 for URL: https://ec2.amazonaws.com/?Action=DescribeInstances

### ISSUE THREAD

**Issue by jensenmo** [hazelcast/hazelcast#5653]
Hi there,

Somewhat related to https://github.com/hazelcast/hazelcast/issues/5220 (embedded hazelcast in vert.x). Hazelcast cluster unable to form between nodes (and vert.x shuts down) in AWS due to the error (see stack trace at bottom). Hazelcast release 3.5 with vert.x 2.1.6.

This happens in region eu-west-1.

@purplefox FYI

The *exact* same set-up - with vert.x 2.1.5 / hazelcast 3.2.3 - works perfectly fine.

Using the same AWS key/secret as those configured in the hazelcast cluster.xml configuration also works 100% OK with AWS CLI "aws ec2 describe-instances" on the same node that the issue occurs on.

I had a look at http://docs.hazelcast.org/docs/latest-dev/manual/html-single/hazelcast-documentation.html and I am wondering if this is related somehow to the bug or fix for the following issue?

- The class TcpIpJoinerOverAWS fails at the recently launched AWS eu-central-1 region. The reason for the fail is that the region requires v4 signatures [#3963]

Stack trace (obfuscated signature + key)
```
2015-07-03 09:44:17.222000 INFO com.hazelcast.core.LifecycleService [10.0.3.116]:5701 [tos-test] [3.5] Address[10.0.3.116]:5701 is STARTING
2015-07-03 09:44:18.400000 WARNING com.hazelcast.cluster.impl.TcpIpJoinerOverAWS [10.0.3.116]:5701 [tos-test] [3.5] Server returned HTTP response code: 401 for URL: https://ec2.amazonaws.com/?Action=DescribeInstances&Version=2014-06-15&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=XXXXXXXXXXXXXXXX%2F20150703%2Feu-west-1%2Fec2%2Faws4_request&X-Amz-Date=20150703T094417Z&X-Amz-Expires=30&X-Amz-Signature=YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY&X-Amz-SignedHeaders=host
java.io.IOException: Server returned HTTP response code: 401 for URL: https://ec2.amazonaws.com/?Action=DescribeInstances&Version=2014-06-15&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=XXXXXXXXXXXXXXXX%2F20150703%2Feu-west-1%2Fec2%2Faws4_request&X-Amz-Date=20150703T094417Z&X-Amz-Expires=30&X-Amz-Signature=YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY&X-Amz-SignedHeaders=host
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1627)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
        at com.hazelcast.aws.impl.DescribeInstances.callService(DescribeInstances.java:81)
        at com.hazelcast.aws.impl.DescribeInstances.execute(DescribeInstances.java:70)
        at com.hazelcast.aws.AWSClient.getPrivateIpAddresses(AWSClient.java:45)
        at com.hazelcast.cluster.impl.TcpIpJoinerOverAWS.getMembers(TcpIpJoinerOverAWS.java:46)
        at com.hazelcast.cluster.impl.TcpIpJoiner.getPossibleAddresses(TcpIpJoiner.java:396)
        at com.hazelcast.cluster.impl.TcpIpJoiner.joinViaPossibleMembers(TcpIpJoiner.java:126)
        at com.hazelcast.cluster.impl.TcpIpJoiner.doJoin(TcpIpJoiner.java:86)
        at com.hazelcast.cluster.impl.AbstractJoiner.join(AbstractJoiner.java:93)
        at com.hazelcast.instance.Node.join(Node.java:534)
        at com.hazelcast.instance.Node.start(Node.java:343)
        at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:126)
        at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:152)
        at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:135)
        at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:111)
        at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:58)
        at org.vertx.java.spi.cluster.impl.hazelcast.HazelcastClusterManager.join(HazelcastClusterManager.java:78)
        at org.vertx.java.core.impl.DefaultVertx.<init>(DefaultVertx.java:117)
        at org.vertx.java.platform.impl.DefaultPlatformManager.createVertxSynchronously(DefaultPlatformManager.java:139)
        at org.vertx.java.platform.impl.DefaultPlatformManager.<init>(DefaultPlatformManager.java:119)
        at org.vertx.java.platform.impl.DefaultPlatformManager.<init>(DefaultPlatformManager.java:111)
        at org.vertx.java.platform.impl.DefaultPlatformManagerFactory.createPlatformManager(DefaultPlatformManagerFactory.java:33)
        at org.vertx.java.platform.impl.cli.Starter.createPM(Starter.java:211)
        at org.vertx.java.platform.impl.cli.Starter.startPM(Starter.java:255)
        at org.vertx.java.platform.impl.cli.Starter.runVerticle(Starter.java:275)
        at org.vertx.java.platform.impl.cli.Starter.<init>(Starter.java:91)
        at org.vertx.java.platform.impl.cli.Starter.main(Starter.java:55)
```
Thanks in advance for your assistance.

**Comment by igmar** [comment]
I'll have a look, this is mostly my work.

**Comment by jensenmo** [comment]
Btw here's the logs immediately preceding the error logged - in case it's of any help:

2015-07-03 09:44:15.383000 INFO org.vertx.java.platform.impl.cli.Starter Starting clustering...
2015-07-03 09:44:15.442000 INFO org.vertx.java.platform.impl.cli.Starter No cluster-host specified so using address 10.0.3.116
2015-07-03 09:44:16.132000 WARNING com.hazelcast.config.AbstractXmlConfigHelper Name of the hazelcast schema location incorrect using default
2015-07-03 09:44:16.537000 INFO com.hazelcast.instance.DefaultAddressPicker [LOCAL] [tos-test] [3.5] Interfaces is enabled, trying to pick one address matching to one of: [10.0.3.116]
2015-07-03 09:44:16.540000 INFO com.hazelcast.instance.DefaultAddressPicker [LOCAL] [tos-test] [3.5] Prefer IPv4 stack is true.
2015-07-03 09:44:16.546000 INFO com.hazelcast.instance.DefaultAddressPicker [LOCAL] [tos-test] [3.5] Picked Address[10.0.3.116]:5701, using socket ServerSocket[addr=/0:0:0:0:0:0:0:0,localport=5701], bind any local is true
2015-07-03 09:44:16.848000 INFO com.hazelcast.spi.OperationService [10.0.3.116]:5701 [tos-test] [3.5] Backpressure is disabled
2015-07-03 09:44:16.858000 INFO com.hazelcast.spi.impl.operationexecutor.classic.ClassicOperationExecutor [10.0.3.116]:5701 [tos-test] [3.5] Starting with 2 generic operation threads and 2 partition operation threads.
2015-07-03 09:44:17.206000 INFO com.hazelcast.system [10.0.3.116]:5701 [tos-test] [3.5] Hazelcast 3.5 (20150617 - 4270dc6) starting at Address[10.0.3.116]:5701
2015-07-03 09:44:17.207000 INFO com.hazelcast.system [10.0.3.116]:5701 [tos-test] [3.5] Copyright (c) 2008-2015, Hazelcast, Inc. All Rights Reserved.
2015-07-03 09:44:17.208000 INFO com.hazelcast.instance.Node [10.0.3.116]:5701 [tos-test] [3.5] Creating AWSJoiner
2015-07-03 09:44:17.222000 INFO com.hazelcast.core.LifecycleService [10.0.3.116]:5701 [tos-test] [3.5] Address[10.0.3.116]:5701 is STARTING

**Comment by mikecroft** [comment]
I had the same thing happen in `eu-west-1` with Hazelcast 3.5, downgrading to 3.4.2 got around the 401 although I could never get the cluster to form with instances in EC2 classic. I didn't try with other regions, but I can if needed.

**Comment by tcanabarro** [comment]
We are seeing the same errors on `us-west-2`:

* vert.x-2.1.6 with Hazelcast 3.5: `HTTP 401 on TcpIpJoinerOverAWS`
* vert.x-2.1.5 with Hazelcast 3.2.5: `OK`

```
INFO  o.v.j.p.i.c.Starter - Starting clustering...
INFO  o.v.j.p.i.c.Starter - No cluster-host specified so using address 10.0.0.62
INFO  o.v.j.p.i.c.Starter - Starting clustering...
INFO  o.v.j.p.i.c.Starter - No cluster-host specified so using address 10.0.0.62
ERROR c.h.c.i.TcpIpJoinerOverAWS - [10.0.0.62]:5701 [dev] [3.5] java.io.IOException: Server returned HTTP response code: 401 for URL: https://ec2.amazonaws.com/?Action=DescribeInstances&Version=2014-06-15&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=XXXXXXXXXXXXXXXXXXXX%2F20150722%2Fus-west-2%2Fec2%2Faws4_request&X-Amz-Date=20150722T205041Z&X-Amz-Expires=30&X-Amz-Signature=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&X-Amz-SignedHeaders=host
com.hazelcast.core.HazelcastException: java.io.IOException: Server returned HTTP response code: 401 for URL: https://ec2.amazonaws.com/?Action=DescribeInstances&Version=2014-06-15&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=XXXXXXXXXXXXXXXXXXXX%2F20150722%2Fus-west-2%2Fec2%2Faws4_request&X-Amz-Date=20150722T205041Z&X-Amz-Expires=30&X-Amz-Signature=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&X-Amz-SignedHeaders=host
  at com.hazelcast.util.ExceptionUtil.rethrow(ExceptionUtil.java:67)
  at com.hazelcast.cluster.impl.TcpIpJoinerOverAWS.getMembers(TcpIpJoinerOverAWS.java:61)
  at com.hazelcast.cluster.impl.TcpIpJoiner.getPossibleAddresses(TcpIpJoiner.java:396)
  at com.hazelcast.cluster.impl.TcpIpJoiner.joinViaPossibleMembers(TcpIpJoiner.java:126)
  at com.hazelcast.cluster.impl.TcpIpJoiner.doJoin(TcpIpJoiner.java:86)
  at com.hazelcast.cluster.impl.AbstractJoiner.join(AbstractJoiner.java:93)
  at com.hazelcast.instance.Node.join(Node.java:534)
  at com.hazelcast.instance.Node.start(Node.java:343)
  at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:126)
  at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:152)
  at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:135)
  at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:111)
  at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:58)
  at org.vertx.java.spi.cluster.impl.hazelcast.HazelcastClusterManager.join(HazelcastClusterManager.java:78)
  at org.vertx.java.core.impl.DefaultVertx.<init>(DefaultVertx.java:117)
  at org.vertx.java.platform.impl.DefaultPlatformManager.createVertxSynchronously(DefaultPlatformManager.java:139)
  at org.vertx.java.platform.impl.DefaultPlatformManager.<init>(DefaultPlatformManager.java:119)
  at org.vertx.java.platform.impl.DefaultPlatformManager.<init>(DefaultPlatformManager.java:111)
  at org.vertx.java.platform.impl.DefaultPlatformManagerFactory.createPlatformManager(DefaultPlatformManagerFactory.java:33)
  at org.vertx.java.platform.impl.cli.Starter.createPM(Starter.java:211)
  at org.vertx.java.platform.impl.cli.Starter.startPM(Starter.java:255)
  at org.vertx.java.platform.impl.cli.Starter.runVerticle(Starter.java:275)
  at org.vertx.java.platform.impl.cli.Starter.<init>(Starter.java:91)
  at org.vertx.java.platform.impl.cli.Starter.main(Starter.java:55)
```

**Comment by pveentjer** [comment]
Can you file a report at the Hazelcast github?
https://github.com/hazelcast/hazelcast/issues
Perhaps there is an issue with aws joiner.

PS: The aws joiner is nothing more than a mechanism to configure the tcp/ip joiner with well known addresses. You could also use something like jclouds to access the information you need and programmatically configure the tcp/ip joiner.

**Comment by pveentjer** [comment]
I can confirm there is an issue with the AWS joiner. For us-east-1 it works fine, but if I pick a different region I get the above exceptions.

**Comment by igmar** [comment]
Checking right now.

**Comment by igmar** [comment]
The backport if the patch does NOT fix this issue. We actually have 2 issues :

1) The request was wrong. I fixed that part, and verified on 3 different regions it gives a correct result
2) The SAX parser blows up

I'm on the dark on #2 : No idea how and why. Can anyone help me with  this ?

**Comment by bilalyasar** [comment]
Hi @igmar, let me check

**Comment by igmar** [comment]
Never mind, I'm an idiot. I tested on a region that only had stopped instances.

**Comment by igmar** [comment]
Pull send, needs a proper rebase first.

Code used for testing : 

public class EC2LiveTest {
    private final static String TEST_REGION = "eu-west-1";
    private final static String TEST_ACCESS_KEY = "AKIA.......";
    private final static String TEST_SECRET_KEY = "mysecretkey";

    @Test
    public void testDescribe() {
        AwsConfig awsConfig = new AwsConfig();
        awsConfig.setRegion(TEST_REGION);
        awsConfig.setAccessKey(TEST_ACCESS_KEY);
        awsConfig.setSecretKey(TEST_SECRET_KEY);

        DescribeInstances di = new DescribeInstances(awsConfig);
        try {
            Map<String, String> res = di.execute();
            System.out.println(res);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}

**Comment by jensenmo** [comment]
Hi, I'm wondering if there's an approximate date for release of a hazelcast (3.5.x) version that fixes this issue? Thanks.

**Comment by jerrinot** [comment]
@jensenmo: Hazelcast 3.5.2 was released yesterday and it contains the the fix - https://github.com/hazelcast/hazelcast/pull/5778

**Comment by jensenmo** [comment]
That's great news - I'll get it tested with vert.x 2.1.6 (assuming there's no breaking hazelcast changes between 3.5 -> 3.5.2) in AWS. Thanks!

**Comment by gurbuzali** [comment]
there shouldn't be

**Comment by jensenmo** [comment]
@purplefox FYI
Hi I managed to get vert.x 2.1.6 up and running in our AWS test cluster of 3 nodes (with 3 x 3 service instance running over vert.x) with Hazelcast 3.5.2 and all is looking good so far. Thanks a lot for your assistance.
