### ISSUE TITLE
[TEST-FAILURE] JCacheListenerTest.testRemoveIfSameWithSyncListener_whenValueIsNotSame

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#5664]
```
org.junit.runners.model.TestTimedOutException: test timed out after 30000 milliseconds
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:196)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.pollResponse(InvocationFuture.java:291)
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast$hazelcast/608/testReport/junit/com.hazelcast.cache/JCacheListenerTest/testRemoveIfSameWithSyncListener_whenValueIsNotSame/

**Comment by serkan-ozal** [comment]
Closing this one since did not failed last 1.5 month
