### ISSUE TITLE
[TEST-FAILURE] MapReduceTest.testExceptionDistribution

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#5702]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-IbmJDK1.6/com.hazelcast$hazelcast/266/testReport/junit/com.hazelcast.mapreduce/MapReduceTest/testExceptionDistribution/

```
org.junit.runners.model.TestTimedOutException: test timed out after 30000 milliseconds
	at org.apache.log4j.PatternLayout.format(PatternLayout.java:503)
	at org.apache.log4j.WriterAppender.subAppend(WriterAppender.java:301)
	at org.apache.log4j.WriterAppender.append(WriterAppender.java:159)
	at org.apache.log4j.AppenderSkeleton.doAppend(AppenderSkeleton.java:230)
	at org.apache.log4j.helpers.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:65)
	at org.apache.log4j.Category.callAppenders(Category.java:203)
	at org.apache.log4j.Category.forcedLog(Category.java:388)
	at org.apache.log4j.Category.debug(Category.java:276)
	at com.hazelcast.logging.Log4jFactory$Log4jLogger.log(Log4jFactory.java:88)
	at com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:224)
	at com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:211)
	at com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.finest(LoggingServiceImpl.java:156)
	at com.hazelcast.spi.impl.ServiceManager.shutdownService(ServiceManager.java:253)
	at com.hazelcast.spi.impl.ServiceManager.shutdown(ServiceManager.java:246)
	at com.hazelcast.spi.impl.NodeEngineImpl.shutdown(NodeEngineImpl.java:322)
	at com.hazelcast.instance.Node.shutdown(Node.java:409)
	at com.hazelcast.instance.LifecycleServiceImpl.shutdown(LifecycleServiceImpl.java:91)
	at com.hazelcast.instance.HazelcastInstanceProxy.shutdown(HazelcastInstanceProxy.java:261)
	at com.hazelcast.mapreduce.MapReduceTest.tripshutdown(MapReduceTest.java:54)
	at com.hazelcast.mapreduce.MapReduceTest.testExceptionDistribution(MapReduceTest.java:251)
```

**Comment by Donnerbart** [comment]
Increased test timeout of exception throwing tests to same as normal tests via https://github.com/hazelcast/hazelcast/commit/161b8b008ddfbfe42b66db59b04eb76d098bebc1
