### ISSUE TITLE
MapEventPublisherImpl eats up exception

### ISSUE THREAD

**Issue by pveentjer** [hazelcast/hazelcast#5734]
The following program shows the issue:

```
package com.hazelcast;

import com.hazelcast.config.Config;
import com.hazelcast.config.InMemoryFormat;
import com.hazelcast.config.MapConfig;
import com.hazelcast.config.NearCacheConfig;
import com.hazelcast.core.EntryEvent;
import com.hazelcast.core.Hazelcast;
import com.hazelcast.core.HazelcastInstance;
import com.hazelcast.core.IMap;
import com.hazelcast.map.listener.EntryAddedListener;
import com.hazelcast.query.Predicate;
import com.hazelcast.spi.AbstractOperation;
import com.hazelcast.spi.Operation;
import com.hazelcast.spi.impl.operationexecutor.OperationExecutor;
import com.hazelcast.test.HazelcastTestSupport;
import org.apache.log4j.Level;
import org.junit.Test;

import java.util.HashMap;
import java.util.Map;

import static org.junit.Assert.assertTrue;

public class PartitionDeadlockTest extends HazelcastTestSupport {

    private IMap<Integer, String> idxCache;
    private boolean applied = false;
    private HazelcastInstance hz;

    @Test
    public void testPartitionOperation() throws Exception {
        setLoggingLog4j();
        setLogLevel(Level.DEBUG);

        Config config = new Config();
        config.setProperty("hazelcast.logging.type", "slf4j");

        hz = Hazelcast.newHazelcastInstance(config);

        IMap<String, String> dataCache = hz.getMap("data-cache");
        MyEntryListener l = new MyEntryListener();
        MyPredicate predicate = new MyPredicate();
        String uuid = dataCache.addEntryListener(l, predicate, false);

        idxCache = hz.getMap("idx-cache");
        idxCache.put(5, "value5");

        HashMap<String, String> data = new HashMap<String, String>();
        for (int i = 0; i < 10; i++) {
            data.put(String.valueOf(i), "value" + i);
        }
        dataCache.putAll(data);

        Thread.sleep(1000); //000);
        hz.shutdown();
        assertTrue(applied);
    }

    private class MyPredicate implements Predicate<String, String> {

        @Override
        public boolean apply(Map.Entry<String, String> mapEntry) {
            try {
                System.out.println(Thread.currentThread().getName() + " started");
                int key = Integer.parseInt(mapEntry.getKey());
                final int partitionId = getPartitionService(hz).getPartitionId(key);
                System.out.println("partitionid of key:" + partitionId);
                OperationExecutor executor = getOperationService(hz).getOperationExecutor();

                Operation op = new AbstractOperation() {
                    {
                        setPartitionId(partitionId);
                    }

                    @Override
                    public void run() throws Exception {

                    }
                };

                System.out.println("isInvocationAllowedFromCurrentThread:" + executor.isInvocationAllowedFromCurrentThread(op, false));


                boolean result = idxCache.containsKey(key);
                System.out.println(Thread.currentThread() + " completes");
                return result;
            }catch (RuntimeException t){
                t.printStackTrace();
                throw t;
            }
        }
    }

    private class MyEntryListener implements EntryAddedListener<String, String> {

        @Override
        public void entryAdded(EntryEvent<String, String> event) {
            applied = true;
        }
    }
}
```

If I would remove the try/catch in the MyPredicate, the IllegalThreadStateException is thrown away

**Comment by ahmetmircik** [comment]
@pveentjer it seems `MapEventPublisherImpl` does not eat exceptions, it is [OperationRunnerImpl](https://github.com/hazelcast/hazelcast/blob/b1904b836e530cce07fa0d0c4800328537788dab/hazelcast/src/main/java/com/hazelcast/spi/impl/operationservice/impl/OperationRunnerImpl.java#L243) and it only logs that kind of exceptions in `afterRun` phase.

**Comment by mdogan** [comment]
I didn't understand what is expected here. Since most of the events are fired on `operation.afterRun()` phase, we can't return failure to the user. It seems in `putAll` case, event is fired in `run()` method exceptionally. 

In above test, exception is thrown to the caller as far as I see. And I don't understand, purpose of that `try/catch` block, it's doing nothing except printing exception stack-trace.

**Comment by tombujok** [comment]
@pveentjer I've removed the try/catch statements and run the test - I clearly see the exception in the log. What is the behavior that you are missing?

Here's the output:

```
/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/bin/java -Xms128m -Xmx1G -Dhazelcast.phone.home.enabled=false -Dhazelcast.mancenter.enabled=false -Dhazelcast.test.use.network=false -Didea.launcher.port=7533 "-Didea.launcher.bin.path=/Applications/IntelliJ IDEA 15 CE.app/Contents/bin" -Didea.junit.sm_runner -Dfile.encoding=UTF-8 -classpath "/Applications/IntelliJ IDEA 15 CE.app/Contents/lib/idea_rt.jar:/Applications/IntelliJ IDEA 15 CE.app/Contents/plugins/junit/lib/junit-rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/lib/ant-javafx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/lib/dt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/lib/javafx-mx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/lib/jconsole.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/lib/packager.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/lib/sa-jdi.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/lib/tools.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/deploy.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/javaws.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/jfxswt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/management-agent.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/plugin.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/cldrdata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/jaccess.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/jfxrt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/nashorn.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/repos/hazelcast/hazelcast/target/test-classes:/repos/hazelcast/hazelcast/target/classes:/Users/tom/.m2/repository/org/hamcrest/hamcrest-library/1.3/hamcrest-library-1.3.jar:/Users/tom/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar:/Users/tom/.m2/repository/javax/cache/cache-tests/1.0.0/cache-tests-1.0.0-tests.jar:/Users/tom/.m2/repository/javax/cache/test-domain/1.0.0/test-domain-1.0.0.jar:/Users/tom/.m2/repository/javax/cache/cache-tests/1.0.0/cache-tests-1.0.0.jar:/Users/tom/.m2/repository/log4j/log4j/1.2.12/log4j-1.2.12.jar:/Users/tom/.m2/repository/org/apache/logging/log4j/log4j-api/2.0.1/log4j-api-2.0.1.jar:/Users/tom/.m2/repository/org/apache/logging/log4j/log4j-core/2.0.1/log4j-core-2.0.1.jar:/Users/tom/.m2/repository/org/slf4j/slf4j-api/1.6.0/slf4j-api-1.6.0.jar:/Users/tom/.m2/repository/net/spy/spymemcached/2.10.2/spymemcached-2.10.2.jar:/Users/tom/.m2/repository/com/atomikos/transactions-jdbc/3.9.3/transactions-jdbc-3.9.3.jar:/Users/tom/.m2/repository/com/atomikos/transactions-jta/3.9.3/transactions-jta-3.9.3.jar:/Users/tom/.m2/repository/com/atomikos/transactions/3.9.3/transactions-3.9.3.jar:/Users/tom/.m2/repository/com/atomikos/transactions-api/3.9.3/transactions-api-3.9.3.jar:/Users/tom/.m2/repository/com/atomikos/atomikos-util/3.9.3/atomikos-util-3.9.3.jar:/Users/tom/.m2/repository/org/apache/geronimo/specs/geronimo-jta_1.1_spec/1.1.1/geronimo-jta_1.1_spec-1.1.1.jar:/Users/tom/.m2/repository/com/eclipsesource/minimal-json/minimal-json/0.9.2/minimal-json-0.9.2.jar:/repos/hazelcast/hazelcast-code-generator/target/classes:/Users/tom/.m2/repository/org/freemarker/freemarker/2.3.23/freemarker-2.3.23.jar:/Users/tom/.m2/repository/javax/servlet/jsp/javax.servlet.jsp-api/2.2.1/javax.servlet.jsp-api-2.2.1.jar:/Users/tom/.m2/repository/javax/servlet/javax.servlet-api/3.0.1/javax.servlet-api-3.0.1.jar:/Users/tom/.m2/repository/org/eclipse/jetty/jetty-server/8.1.16.v20140903/jetty-server-8.1.16.v20140903.jar:/Users/tom/.m2/repository/org/eclipse/jetty/orbit/javax.servlet/3.0.0.v201112011016/javax.servlet-3.0.0.v201112011016.jar:/Users/tom/.m2/repository/org/eclipse/jetty/jetty-continuation/8.1.16.v20140903/jetty-continuation-8.1.16.v20140903.jar:/Users/tom/.m2/repository/org/eclipse/jetty/jetty-http/8.1.16.v20140903/jetty-http-8.1.16.v20140903.jar:/Users/tom/.m2/repository/org/eclipse/jetty/jetty-io/8.1.16.v20140903/jetty-io-8.1.16.v20140903.jar:/Users/tom/.m2/repository/org/eclipse/jetty/jetty-webapp/8.1.16.v20140903/jetty-webapp-8.1.16.v20140903.jar:/Users/tom/.m2/repository/org/eclipse/jetty/jetty-xml/8.1.16.v20140903/jetty-xml-8.1.16.v20140903.jar:/Users/tom/.m2/repository/org/eclipse/jetty/jetty-util/8.1.16.v20140903/jetty-util-8.1.16.v20140903.jar:/Users/tom/.m2/repository/org/eclipse/jetty/jetty-servlet/8.1.16.v20140903/jetty-servlet-8.1.16.v20140903.jar:/Users/tom/.m2/repository/org/eclipse/jetty/jetty-security/8.1.16.v20140903/jetty-security-8.1.16.v20140903.jar:/Users/tom/.m2/repository/org/apache/httpcomponents/httpclient/4.3.1/httpclient-4.3.1.jar:/Users/tom/.m2/repository/org/apache/httpcomponents/httpcore/4.3/httpcore-4.3.jar:/Users/tom/.m2/repository/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar:/Users/tom/.m2/repository/commons-codec/commons-codec/1.6/commons-codec-1.6.jar:/Users/tom/.m2/repository/org/osgi/org.osgi.core/4.2.0/org.osgi.core-4.2.0.jar:/Users/tom/.m2/repository/org/codehaus/groovy/groovy-all/2.1.8/groovy-all-2.1.8.jar:/Users/tom/.m2/repository/org/jruby/jruby-complete/1.7.22/jruby-complete-1.7.22.jar:/Users/tom/.m2/repository/org/ops4j/pax/exam/pax-exam-junit4/2.6.0/pax-exam-junit4-2.6.0.jar:/Users/tom/.m2/repository/org/ops4j/pax/exam/pax-exam-spi/2.6.0/pax-exam-spi-2.6.0.jar:/Users/tom/.m2/repository/asm/asm/3.0/asm-3.0.jar:/Users/tom/.m2/repository/com/google/guava/guava/12.0/guava-12.0.jar:/Users/tom/.m2/repository/com/google/code/findbugs/jsr305/1.3.9/jsr305-1.3.9.jar:/Users/tom/.m2/repository/org/ops4j/pax/tinybundles/tinybundles/1.0.0/tinybundles-1.0.0.jar:/Users/tom/.m2/repository/biz/aQute/bndlib/1.43.0/bndlib-1.43.0.jar:/Users/tom/.m2/repository/org/ops4j/base/ops4j-base-lang/1.4.0/ops4j-base-lang-1.4.0.jar:/Users/tom/.m2/repository/org/ops4j/pax/exam/pax-exam-container-paxrunner/2.6.0/pax-exam-container-paxrunner-2.6.0.jar:/Users/tom/.m2/repository/org/ops4j/pax/exam/pax-exam/2.6.0/pax-exam-2.6.0.jar:/Users/tom/.m2/repository/org/ops4j/base/ops4j-base-store/1.4.0/ops4j-base-store-1.4.0.jar:/Users/tom/.m2/repository/org/ops4j/base/ops4j-base-util-property/1.4.0/ops4j-base-util-property-1.4.0.jar:/Users/tom/.m2/repository/org/ops4j/pax/exam/pax-exam-container-remote/2.6.0/pax-exam-container-remote-2.6.0.jar:/Users/tom/.m2/repository/org/ops4j/pax/swissbox/pax-swissbox-core/1.5.1/pax-swissbox-core-1.5.1.jar:/Users/tom/.m2/repository/org/ops4j/pax/swissbox/pax-swissbox-lifecycle/1.5.1/pax-swissbox-lifecycle-1.5.1.jar:/Users/tom/.m2/repository/org/ops4j/pax/exam/pax-exam-container-rbc-client/2.6.0/pax-exam-container-rbc-client-2.6.0.jar:/Users/tom/.m2/repository/org/ops4j/pax/exam/pax-exam-container-rbc/2.6.0/pax-exam-container-rbc-2.6.0.jar:/Users/tom/.m2/repository/org/ops4j/base/ops4j-base-io/1.4.0/ops4j-base-io-1.4.0.jar:/Users/tom/.m2/repository/org/ops4j/base/ops4j-base-net/1.4.0/ops4j-base-net-1.4.0.jar:/Users/tom/.m2/repository/org/ops4j/base/ops4j-base-monitors/1.4.0/ops4j-base-monitors-1.4.0.jar:/Users/tom/.m2/repository/commons-logging/commons-logging-api/1.1/commons-logging-api-1.1.jar:/Users/tom/.m2/repository/org/ops4j/pax/exam/pax-exam-link-mvn/2.6.0/pax-exam-link-mvn-2.6.0.jar:/Users/tom/.m2/repository/org/ops4j/pax/runner/pax-runner-no-jcl/1.8.6/pax-runner-no-jcl-1.8.6.jar:/Users/tom/.m2/repository/javax/inject/javax.inject/1/javax.inject-1.jar:/Users/tom/.m2/repository/javax/cache/cache-api/1.0.0/cache-api-1.0.0.jar:/Users/tom/.m2/repository/junit/junit/4.12/junit-4.12.jar:/Users/tom/.m2/repository/org/mockito/mockito-all/1.10.19/mockito-all-1.10.19.jar:/Users/tom/.m2/repository/org/powermock/powermock-module-junit4/1.6.3/powermock-module-junit4-1.6.3.jar:/Users/tom/.m2/repository/org/powermock/powermock-module-junit4-common/1.6.3/powermock-module-junit4-common-1.6.3.jar:/Users/tom/.m2/repository/org/powermock/powermock-core/1.6.3/powermock-core-1.6.3.jar:/Users/tom/.m2/repository/org/javassist/javassist/3.20.0-GA/javassist-3.20.0-GA.jar:/Users/tom/.m2/repository/org/powermock/powermock-reflect/1.6.3/powermock-reflect-1.6.3.jar:/Users/tom/.m2/repository/org/objenesis/objenesis/2.1/objenesis-2.1.jar:/Users/tom/.m2/repository/org/powermock/powermock-api-mockito/1.6.3/powermock-api-mockito-1.6.3.jar:/Users/tom/.m2/repository/org/powermock/powermock-api-support/1.6.3/powermock-api-support-1.6.3.jar:/Users/tom/.m2/repository/com/google/code/findbugs/annotations/3.0.0/annotations-3.0.0.jar" com.intellij.rt.execution.application.AppMain com.intellij.rt.execution.junit.JUnitStarter -ideVersion5 com.hazelcast.PartitionDeadlockTest,testPartitionOperation
ASSERT_TRUE_EVENTUALLY_TIMEOUT = 120SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
hz._hzInstance_1_dev.partition-operation.thread-1 started
hz._hzInstance_1_dev.partition-operation.thread-0 started
hz._hzInstance_1_dev.partition-operation.thread-3 started
hz._hzInstance_1_dev.partition-operation.thread-5 started
hz._hzInstance_1_dev.partition-operation.thread-6 started
partitionid of key:179
partitionid of key:42
partitionid of key:134
partitionid of key:164
isInvocationAllowedFromCurrentThread:false
partitionid of key:227
isInvocationAllowedFromCurrentThread:false
isInvocationAllowedFromCurrentThread:false
isInvocationAllowedFromCurrentThread:false
isInvocationAllowedFromCurrentThread:false
hz._hzInstance_1_dev.partition-operation.thread-0 started
partitionid of key:27
isInvocationAllowedFromCurrentThread:false
hz._hzInstance_1_dev.partition-operation.thread-1 started
partitionid of key:31
isInvocationAllowedFromCurrentThread:false
hz._hzInstance_1_dev.partition-operation.thread-1 started
partitionid of key:169
isInvocationAllowedFromCurrentThread:false
hz._hzInstance_1_dev.partition-operation.thread-1 started
partitionid of key:5
isInvocationAllowedFromCurrentThread:false
hz._hzInstance_1_dev.partition-operation.thread-3 started
partitionid of key:11
isInvocationAllowedFromCurrentThread:false

java.lang.IllegalThreadStateException: Thread[hz._hzInstance_1_dev.partition-operation.thread-0,5,_hzInstance_1_dev] cannot make remote call: com.hazelcast.map.impl.operation.ContainsKeyOperation{serviceName='hz:impl:mapService', partitionId=179, replicaIndex=0, callId=0, invocationTime=-1 (Thu Jan 01 00:59:59 CET 1970), waitTimeout=-1, callTimeout=60000, name=idx-cache, name=idx-cache}

	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invokeInternal(Invocation.java:208)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:180)
	at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.invokeOnPartition(OperationServiceImpl.java:317)
	at com.hazelcast.map.impl.proxy.MapProxySupport.containsKeyInternal(MapProxySupport.java:491)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.containsKey(MapProxyImpl.java:215)
	at com.hazelcast.PartitionDeadlockTest$MyPredicate.apply(PartitionDeadlockTest.java:86)
	at com.hazelcast.map.impl.query.QueryEventFilter.eval(QueryEventFilter.java:49)
	at com.hazelcast.map.impl.event.MapEventPublisherImpl.processQueryEventFilter(MapEventPublisherImpl.java:302)
	at com.hazelcast.map.impl.event.MapEventPublisherImpl.doFilter(MapEventPublisherImpl.java:210)
	at com.hazelcast.map.impl.event.MapEventPublisherImpl.publishEvent(MapEventPublisherImpl.java:148)
	at com.hazelcast.map.impl.event.MapEventPublisherImpl.publishEvent(MapEventPublisherImpl.java:130)
	at com.hazelcast.map.impl.operation.PutAllOperation.put(PutAllOperation.java:100)
	at com.hazelcast.map.impl.operation.PutAllOperation.run(PutAllOperation.java:78)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:172)
	at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.processOperation(OperationThread.java:198)
	at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.process(OperationThread.java:132)
	at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.doRun(OperationThread.java:124)
	at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.run(OperationThread.java:99)


Process finished with exit code 255
```

**Comment by tombujok** [comment]
Had a look at it once more.
The exception is not eaten up - as presented above, the exception is thrown and logged without the try/catch block.
Here's the line: 
https://github.com/tombujok/hazelcast/blob/73a871b33d239cd9b3d1224a4a00a999ab28c74b/hazelcast/src/main/java/com/hazelcast/spi/impl/operationservice/impl/Invocation.java#L208-L208.

@pveentjer Plz, let us know, should you be of different opinion.
IMHO, the code behaves properly and is fine for 3.6.
