### ISSUE TITLE
Hazelcast 3.0 RC2 - AWS EC2 Auto-discovery

### ISSUE THREAD

**Issue by CeccoCQ** [hazelcast/hazelcast#577]
Hi,

I'm newbie of Amazon services and Hazelcast.
I read that with latest release (RC2) you have fixed the problems with Amazon auto-discovery .

So, I go into my amazon account in my "Security Credentials" panel, then into "Access Keys" section. I've created a couple of keys and I've changed the hazelcast.xml configuration file with my {access.key} and {secret.key}.

When I started my two nodes, they do not merge into a single cluster, but they form a single cluster for each.

Where am I doing wrong?

**Comment by muthukumarkubendran** [comment]
I'm getting connection time out issue, when trying to start the server. I'm using 3.6.4 version. ’ve provided the aws tags enabled with right AWS access and secret keys, security groups (both inbound and outbound ports open for all traffic), region, host-header…. Not sure if I’m missing anything here, but I keep getting connection time out.

 <aws enabled="true" connection-timeout-seconds="500">
                <access-key>XXXXXX</access-key>
                <secret-key>XXXXXX</secret-key>
                
                <region>us-east-1</region>
                
                <host-header>ec2.amazonaws.com</host-header>
                
                <security-group-name>XXXX</security-group-name>
                <tag-key>type</tag-key>
                <tag-value>hz-nodes</tag-value>
            </aws>


Here is the exception on the console when starting the server. 

WARNING: [10.205.86.97]:5701 [dev] [3.6.4] Connection timed out
java.net.ConnectException: Connection timed out
    at java.net.PlainSocketImpl.socketConnect(Native Method)
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
    at java.net.Socket.connect(Socket.java:589)
    at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
    at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
    at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
    at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
    at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
    at com.hazelcast.aws.impl.DescribeInstances.callService(DescribeInstances.java:158)
    at com.hazelcast.aws.impl.DescribeInstances.execute(DescribeInstances.java:144)
    at com.hazelcast.aws.AWSClient.getPrivateIpAddresses(AWSClient.java:53)
    at com.hazelcast.cluster.impl.TcpIpJoinerOverAWS.getMembers(TcpIpJoinerOverAWS.java:42)
    at com.hazelcast.cluster.impl.TcpIpJoiner.getPossibleAddresses(TcpIpJoiner.java:399)
    at com.hazelcast.cluster.impl.TcpIpJoiner.joinViaPossibleMembers(TcpIpJoiner.java:126)
    at com.hazelcast.cluster.impl.TcpIpJoiner.doJoin(TcpIpJoiner.java:84)
    at com.hazelcast.cluster.impl.AbstractJoiner.join(AbstractJoiner.java:103)
    at com.hazelcast.instance.Node.join(Node.java:581)
    at com.hazelcast.instance.Node.start(Node.java:339)
    at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:131)
    at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:160)
    at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:143)
    at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:111)
    at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:58)
    at com.hazelcast.core.server.StartServer.main(StartServer.java:36)
 
Jul 20, 2016 12:19:35 PM com.hazelcast.cluster.impl.TcpIpJoinerOverAWS
SEVERE: [10.205.86.97]:5701 [dev] [3.6.4] java.net.ConnectException: Connection timed out
com.hazelcast.core.HazelcastException: java.net.ConnectException: Connection timed out
    at com.hazelcast.util.ExceptionUtil.peel(ExceptionUtil.java:73)
    at com.hazelcast.util.ExceptionUtil.peel(ExceptionUtil.java:52)
    at com.hazelcast.util.ExceptionUtil.rethrow(ExceptionUtil.java:83)
    at com.hazelcast.cluster.impl.TcpIpJoinerOverAWS.getMembers(TcpIpJoinerOverAWS.java:57)
    at com.hazelcast.cluster.impl.TcpIpJoiner.getPossibleAddresses(TcpIpJoiner.java:399)
    at com.hazelcast.cluster.impl.TcpIpJoiner.joinViaPossibleMembers(TcpIpJoiner.java:126)
    at com.hazelcast.cluster.impl.TcpIpJoiner.doJoin(TcpIpJoiner.java:84)
    at com.hazelcast.cluster.impl.AbstractJoiner.join(AbstractJoiner.java:103)
    at com.hazelcast.instance.Node.join(Node.java:581)
    at com.hazelcast.instance.Node.start(Node.java:339)
    at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:131)
    at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:160)
    at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:143)
    at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:111)
    at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:58)
    at com.hazelcast.core.server.StartServer.main(StartServer.java:36)
Caused by: java.net.ConnectException: Connection timed out
    at java.net.PlainSocketImpl.socketConnect(Native Method)
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
    at java.net.Socket.connect(Socket.java:589)
    at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
    at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
    at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
    at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
    at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
    at com.hazelcast.aws.impl.DescribeInstances.callService(DescribeInstances.java:158)
    at com.hazelcast.aws.impl.DescribeInstances.execute(DescribeInstances.java:144)
    at com.hazelcast.aws.AWSClient.getPrivateIpAddresses(AWSClient.java:53)
    at com.hazelcast.cluster.impl.TcpIpJoinerOverAWS.getMembers(TcpIpJoinerOverAWS.java:42)
    ... 12 more

**Comment by AlexKryv** [comment]
Thank you so much you saved my day. Hazelcast cluster doesnt work without tags on EC2 instance.
