### ISSUE TITLE
AWSJoiner returns 401

### ISSUE THREAD

**Issue by pveentjer** [hazelcast/hazelcast#5771]
The AWSJoiner doesn't work correctly for most regions. us-east-1 works fine, but the others I have tried fail.

```
import com.hazelcast.core.Hazelcast;

public class Member {
    public static void main(String[] args) {
        Hazelcast.newHazelcastInstance();
    }
}

<hazelcast xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.hazelcast.com/schema/config
                               http://www.hazelcast.com/schema/config/hazelcast-config-3.2.xsd"
           xmlns="http://www.hazelcast.com/schema/config">
    <network>
        <join>
            <aws enabled="true">
                <access-key>xxxx</access-key>
                <secret-key>yyyyy</secret-key>
                <region>eu-west-1</region>
                <security-group-name>peter</security-group-name>
                <tag-key>type</tag-key>
                <tag-value>hz-nodes</tag-value>
            </aws>
        </join>
    </network>
</hazelcast>
```

I get exceptions like this:
```
Jul 23, 2015 7:16:08 AM com.hazelcast.cluster.impl.TcpIpJoinerOverAWS
WARNING: [192.168.122.1]:5701 [dev] [3.6-SNAPSHOT] Server returned HTTP response code: 401 for URL: https://ec2.amazonaws.com/?Action=DescribeInstances&Version=2014-06-15&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=XXXXXXXX%2F20150723%2Feu-west-1%2Fec2%2Faws4_request&X-Amz-Date=20150723T041607Z&X-Amz-Expires=30&X-Amz-Signature=YYYYYYYYYYYYYYY&X-Amz-SignedHeaders=host
java.io.IOException: Server returned HTTP response code: 401 for URL: https://ec2.amazonaws.com/?Action=DescribeInstances&Version=2014-06-15&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=XXXXXXXX%2F20150723%2Feu-west-1%2Fec2%2Faws4_request&X-Amz-Date=20150723T041607Z&X-Amz-Expires=30&X-Amz-Signature=YYYYYYYYYYYYYYYY&X-Amz-SignedHeaders=host
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1626)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at com.hazelcast.aws.impl.DescribeInstances.callService(DescribeInstances.java:81)
	at com.hazelcast.aws.impl.DescribeInstances.execute(DescribeInstances.java:70)
	at com.hazelcast.aws.AWSClient.getPrivateIpAddresses(AWSClient.java:45)
	at com.hazelcast.cluster.impl.TcpIpJoinerOverAWS.getMembers(TcpIpJoinerOverAWS.java:46)
	at com.hazelcast.cluster.impl.TcpIpJoiner.getPossibleAddresses(TcpIpJoiner.java:396)
	at com.hazelcast.cluster.impl.TcpIpJoiner.joinViaPossibleMembers(TcpIpJoiner.java:126)
	at com.hazelcast.cluster.impl.TcpIpJoiner.doJoin(TcpIpJoiner.java:86)
	at com.hazelcast.cluster.impl.AbstractJoiner.join(AbstractJoiner.java:94)
	at com.hazelcast.instance.Node.join(Node.java:534)
	at com.hazelcast.instance.Node.start(Node.java:343)
	at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:132)
	at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:152)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:135)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:111)
	at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:87)
	at Member.main(Member.java:5)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

**Comment by mdogan** [comment]
@pveentjer: there's already an issue for this which is submitted by @jensenmo and referenced by you: #5653. 

Why have you created a new one?

**Comment by pveentjer** [comment]
Didn't drink enough coffee. I thought I was on the vertex repo and not the HZ repo :)

**Comment by mdogan** [comment]
☕
