### ISSUE TITLE
[TEST-FAILURE] map.query.QueryBasicTest failures

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#5800]
com.hazelcast.map.query.QueryBasicTest.testPredicateDateAttributeWithIndex
com.hazelcast.map.query.QueryBasicTest.testPredicateDateAttribute
com.hazelcast.map.query.QueryBasicTest.testPredicateEnumAttributeWithIndex

```
java.lang.RuntimeException: Unable to parse date from value: 'Sat Jan 01 11:43:05 EET 2011' ! Valid format are: 'EEE MMM dd HH:mm:ss zzz yyyy'.
	at com.hazelcast.query.impl.DateHelper.throwRuntimeParseException(DateHelper.java:78)
	at com.hazelcast.query.impl.DateHelper.parseDate(DateHelper.java:41)
	at com.hazelcast.query.impl.TypeConverters$DateConverter.convert(TypeConverters.java:113)
	at com.hazelcast.query.impl.predicates.AbstractPredicate.convert(AbstractPredicate.java:70)
	at com.hazelcast.query.impl.predicates.GreaterLessPredicate.apply(GreaterLessPredicate.java:58)
	at com.hazelcast.query.SqlPredicate.apply(SqlPredicate.java:67)
	at com.hazelcast.map.impl.BasicMapContextQuerySupport.queryOnPartition(BasicMapContextQuerySupport.java:93)
	at com.hazelcast.map.impl.operation.QueryPartitionOperation.run(QueryPartitionOperation.java:51)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:160)
	at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.processOperation(OperationThread.java:180)
	at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.process(OperationThread.java:130)
	at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.doRun(OperationThread.java:122)
	at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.run(OperationThread.java:97)
Caused by: java.text.ParseException: Unparseable date: "Sat Jan 01 11:43:05 EET 2011"
	at java.text.DateFormat.parse(DateFormat.java:366)
         ...
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK9-Quality-Outreach/com.hazelcast$hazelcast/141/testReport/junit/com.hazelcast.map.query/QueryBasicTest/testPredicateDateAttributeWithIndex/

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK9-Quality-Outreach/com.hazelcast$hazelcast/141/testReport/junit/com.hazelcast.map.query/QueryBasicTest/testPredicateDateAttribute/

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK9-Quality-Outreach/com.hazelcast$hazelcast/141/testReport/junit/com.hazelcast.map.query/QueryBasicTest/testPredicateEnumAttributeWithIndex/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK9-Quality-Outreach/142/#showFailuresLink

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK9-Quality-Outreach/170/#showFailuresLink

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK9-Quality-Outreach/174/#showFailuresLink

**Comment by tombujok** [comment]
Have a look at #5980
