### ISSUE TITLE
[TEST-FAILURE] TransactionalMapReadQuorumTest failures

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#5813]
com.hazelcast.quorum.TransactionalMapReadQuorumTest.testTxGetThrowsExceptionWhenQuorumSizeNotMet[Executing: TransactionOptions{timeoutMillis=120000, durability=1, txType=TWO_PHASE}]

com.hazelcast.quorum.TransactionalMapReadQuorumTest.testTxContainsKeyThrowsExceptionWhenQuorumSizeNotMet[Executing: TransactionOptions{timeoutMillis=120000, durability=1, txType=TWO_PHASE}]

com.hazelcast.quorum.TransactionalMapReadQuorumTest.testTxGetThrowsExceptionWhenQuorumSizeNotMet[Executing: TransactionOptions{timeoutMillis=120000, durability=1, txType=LOCAL}]

com.hazelcast.quorum.TransactionalMapReadQuorumTest.testTxContainsKeyThrowsExceptionWhenQuorumSizeNotMet[Executing: TransactionOptions{timeoutMillis=120000, durability=1, txType=LOCAL}]

```
java.lang.AssertionError: Expected exception: com.hazelcast.transaction.TransactionException
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:32)
	at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:134)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at com.hazelcast.test.HazelcastParallelClassRunner.access$201(HazelcastParallelClassRunner.java:29)
	at com.hazelcast.test.HazelcastParallelClassRunner$TestRunner.run(HazelcastParallelClassRunner.java:89)
	at java.lang.Thread.run(Thread.java:738)
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.6/626/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK8-Quality-Outreach/151/
