### ISSUE TITLE
Concurrent Modification Exception : Hazelcast-3.5

### ISSUE THREAD

**Issue by RubavathiSrinivasan** [hazelcast/hazelcast#5854]
We recently upgraded hazelcast version to 3.5 . We are getting the following error and this is inconsistent. We don't update the map values. We just use it as a lookup map. 
```
java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:859)
        at java.util.ArrayList$Itr.next(ArrayList.java:831)
        at com.hazelcast.util.FutureUtil.checkAllDone(FutureUtil.java:344)
        at com.hazelcast.map.impl.DefaultRecordStore.checkIfLoaded(DefaultRecordStore.java:127)
        at com.hazelcast.map.impl.DefaultRecordStore.loadAwareIterator(DefaultRecordStore.java:208)
        at com.hazelcast.map.impl.BasicMapContextQuerySupport.queryOnPartition(BasicMapContextQuerySupport.java:82)
        at com.hazelcast.map.impl.operation.QueryOperation.runSingleThreaded(QueryOperation.java:129)
        at com.hazelcast.map.impl.operation.QueryOperation.fullTableScan(QueryOperation.java:118)
        at com.hazelcast.map.impl.operation.QueryOperation.run(QueryOperation.java:95)
        at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:137)
        at com.hazelcast.spi.impl.operationexecutor.classic.ClassicOperationExecutor.runOnCallingThread(ClassicOperationExecutor.java:380)
        at com.hazelcast.spi.impl.operationexecutor.classic.ClassicOperationExecutor.runOnCallingThreadIfPossible(ClassicOperationExecutor.java:342)
        at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:247)
        at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:231)
        at com.hazelcast.spi.impl.operationservice.impl.Invocation.invokeInternal(Invocation.java:198)
        at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:168)
        at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.invokeOnTarget(OperationServiceImpl.java:277)
        at com.hazelcast.map.impl.BasicMapContextQuerySupport.queryOnMembers(BasicMapContextQuerySupport.java:308)
        at com.hazelcast.map.impl.BasicMapContextQuerySupport.query(BasicMapContextQuerySupport.java:264)
        at com.hazelcast.map.impl.proxy.MapProxySupport.query(MapProxySupport.java:1136)
        at com.hazelcast.map.impl.proxy.MapProxyImpl.values(MapProxyImpl.java:583)
```

**Comment by ajermakovics** [comment]
Hi @RubavathiSrinivasan 

Thanks for reporting! The stacktrace points to where the problem is and we should be able to fix it in the next patch release.

**Comment by bwzhang2011** [comment]
+1
