### ISSUE TITLE
Hazelcast timeout Exception

### ISSUE THREAD

**Issue by RubavathiSrinivasan** [hazelcast/hazelcast#5891]
We are getting the following exception on CentOS

```
com.hazelcast.core.OperationTimeoutException: No response for 120000 ms. Aborting invocation! Invocation{ serviceName='hz:impl:mapService', op=com.hazelcast.map.impl.operation.MapSizeOperation{serviceName='null', partitionId=0, callId=339887, invocationTime=1438957567435, waitTimeout=-1, callTimeout=60000}, partitionId=0, replicaIndex=0, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeout=60000, target=Address[10.0.44.26]:9701, backupsExpected=0, backupsCompleted=0} No response has been received! backups-expected:0 backups-completed: 0
at com.hazelcast.spi.impl.operationservice.impl.Invocation.newOperationTimeoutException(Invocation.java:491)
at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.waitFo
rResponse(InvocationFuture.java:277)
    at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.get(InvocationFuture.java:224)
    at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.get(InvocationFuture.java:204)
    at com.hazelcast.spi.impl.operationservice.impl.InvokeOnPartitions.retryFailedPartitions(InvokeOnPartitions.java:131)
    at com.hazelcast.spi.impl.operationservice.impl.InvokeOnPartitions.invoke(InvokeOnPartitions.java:67)
    at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.invokeOnAllPartitions(OperationServiceImpl.java:326)
    at com.hazelcast.map.impl.proxy.MapProxySupport.size(MapProxySupport.java:692)
    at com.hazelcast.map.impl.proxy.MapProxyImpl.size(MapProxyImpl.java:71)
```

**Comment by jerrinot** [comment]
Hello @RubavathiSrinivasan 

thank you for reporting the issue. Could you please clarify what version of Hazelcast you are using, what exactly is the scenario, whether you are using client-server topology or server-to-server. Obviously a reproducer would be great!

**Comment by RubavathiSrinivasan** [comment]
We are using version 3.5
We hit the server from bot client (5000 threads at a time). It is a client-server topology. 
When there are clients calls the same method which in turn calls the hazelcast map, this exception is thrown.

**Comment by jerrinot** [comment]
@RubavathiSrinivasan: how many members do you have in your cluster? is it 5000 threads from a single client? Is it a smart client? (=default)

**Comment by RubavathiSrinivasan** [comment]
We have 2 members, we are hitting from JMX client(5000 threads).

**Comment by jerrinot** [comment]
@RubavathiSrinivasan: how easy is it reproducible? could you try to run into with the latest 3.6 master?

**Comment by RubavathiSrinivasan** [comment]
We are using maven to build. How can I specify 3.6? Can you give me the group and artifact id for 3.6?

**Comment by jerrinot** [comment]
@RubavathiSrinivasan: Try to use version `<version>3.6-SNAPSHOT</version>` in your pom.xml

**Comment by bwzhang2011** [comment]
@RubavathiSrinivasan, any update with such issue ? hazelcast 3.6 snapshot will make great efforts with its io improvement and else.

**Comment by pveentjer** [comment]
How come you have 5000 threads? In most cases this is a serious smell indicator. 

PS: The Map.size is a very complex operation because it will hit every member in the cluster. What kind of operations are these 5000 threads doing?

**Comment by RubavathiSrinivasan** [comment]
Still we are getting the opertationtimeoutException with the latest hazelcast source. and the following exception is thrown on startup 

com.hazelcast.nio.serialization.HazelcastSerializationException: java.io.EOFException
at com.hazelcast.internal.serialization.impl.SerializationUtil.handleException(SerializationUtil.java:71)
at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:166)
at com.hazelcast.nio.tcp.TcpIpConnectionManager.handle(TcpIpConnectionManager.java:233)
at com.hazelcast.spi.impl.NodeEngineImpl$ConnectionManagerPacketHandler.handle(NodeEngineImpl.java:124)
at com.hazelcast.spi.impl.packetdispatcher.impl.PacketDispatcherImpl.dispatch(PacketDispatcherImpl.java:63)
at com.hazelcast.nio.tcp.MemberReadHandler.handlePacket(MemberReadHandler.java:75)
at com.hazelcast.nio.tcp.MemberReadHandler.onRead(MemberReadHandler.java:58)
at com.hazelcast.nio.tcp.nonblocking.NonBlockingSocketReader.handle(NonBlockingSocketReader.java:178)
at com.hazelcast.nio.tcp.nonblocking.NonBlockingIOThread.handleSelectionKey(NonBlockingIOThread.java:271)
at com.hazelcast.nio.tcp.nonblocking.NonBlockingIOThread.handleSelectionKeys(NonBlockingIOThread.java:256)
at com.hazelcast.nio.tcp.nonblocking.NonBlockingIOThread.runSelectLoop(NonBlockingIOThread.java:206)
at com.hazelcast.nio.tcp.nonblocking.NonBlockingIOThread.run(NonBlockingIOThread.java:163)
Caused by: java.io.EOFException
at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readByte(ByteArrayObjectDataInput.java:145)
at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readUTF(ByteArrayObjectDataInput.java:588)
at com.hazelcast.internal.serialization.impl.DataSerializer.read(DataSerializer.java:118)
at com.hazelcast.internal.serialization.impl.DataSerializer.read(DataSerializer.java:47)
at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:46)
at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:160)

**Comment by mdogan** [comment]
You can enable diagnostics to be able to see internal details of the system during failure. 
```
-Dhazelcast.diagnostics.enabled=true
-Dhazelcast.diagnostics.metric.level=info
-Dhazelcast.diagnostics.invocation.sample.period.seconds=30
-Dhazelcast.diagnostics.pending.invocations.period.seconds=30
-Dhazelcast.diagnostics.slowoperations.period.seconds=30
```

See http://docs.hazelcast.org/docs/3.8.2/manual/html-single/index.html#diagnostics

Please try latest version and feel free to open a new issue if problem still exists.
