### ISSUE TITLE
[TEST-FAILURE] lock.ConditionBasicDistributedTest.testSignalWithSingleWaiter

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#5942]
```
org.junit.runners.model.TestTimedOutException: test timed out after 60000 milliseconds
	at java.lang.Object.wait(Native Method)
	at java.lang.Thread.join(Thread.java:1186)
	at java.lang.Thread.join(Thread.java:1239)
	at com.hazelcast.concurrent.lock.ConditionBasicTest.testSignalWithSingleWaiter(ConditionBasicTest.java:240)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
       ....
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK6/com.hazelcast$hazelcast/626/testReport/junit/com.hazelcast.concurrent.lock/ConditionBasicDistributedTest/testSignalWithSingleWaiter/

**Comment by tombujok** [comment]
Fixed via #6167
