### ISSUE TITLE
[TEST-FAILURE] ClientMapTest.testSubmitToKeyWithCallback

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#5979]
```
java.lang.AssertionError: expected:<2> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.client.map.ClientMapTest.testSubmitToKeyWithCallback(ClientMapTest.java:562)

```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK1.6/com.hazelcast$hazelcast-client/646/testReport/junit/com.hazelcast.client.map/ClientMapTest/testSubmitToKeyWithCallback/

**Comment by jerrinot** [comment]
another failure: https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-pr-builder/14881/

**Comment by jerrinot** [comment]
it's probably related to #5944

**Comment by sancar** [comment]
fixed via https://github.com/hazelcast/hazelcast/commit/0bfdd8a0f61c6bdcf31588f7f86c5afd433bbfd3
