### ISSUE TITLE
[TEST-FAILURE] mapstore.writebehind.WriteBehindWithEntryProcessorTest.updates_on_same_key_when_in_memory_format_is_object

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#6007]
```
 java.lang.AssertionError: expected:<500> but was:<1270>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.map.mapstore.writebehind.WriteBehindWithEntryProcessorTest$3.run(WriteBehindWithEntryProcessorTest.java:163)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:752)
	at com.hazelcast.map.mapstore.writebehind.WriteBehindWithEntryProcessorTest.assertAllSubscriptionsInStore(WriteBehindWithEntryProcessorTest.java:160)
	at com.hazelcast.map.mapstore.writebehind.WriteBehindWithEntryProcessorTest.updates_on_same_key_when_in_memory_format_is_object(WriteBehindWithEntryProcessorTest.java:143)
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OracleJDK1.7/com.hazelcast$hazelcast/209/testReport/junit/com.hazelcast.map.mapstore.writebehind/WriteBehindWithEntryProcessorTest/updates_on_same_key_when_in_memory_format_is_object/

**Comment by ahmetmircik** [comment]
Fixed via https://github.com/hazelcast/hazelcast/commit/d4367ff2b34d93d952c81c4f332dd1500ac42799

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OracleJDK1.7/com.hazelcast$hazelcast/212/testReport/junit/com.hazelcast.map.mapstore.writebehind/WriteBehindWithEntryProcessorTest/updates_on_same_key_when_in_memory_format_is_object/

**Comment by hasancelik** [comment]
**maintenance**

```
java.lang.AssertionError: expected:<500> but was:<4156>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-IbmJDK1.7/com.hazelcast$hazelcast/282/testReport/junit/com.hazelcast.map.mapstore.writebehind/WriteBehindWithEntryProcessorTest/updates_on_same_key_when_in_memory_format_is_object/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK8/com.hazelcast$hazelcast/664/testReport/junit/com.hazelcast.map.mapstore.writebehind/WriteBehindWithEntryProcessorTest/updates_on_same_key_when_in_memory_format_is_object/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OracleJDK1.7/com.hazelcast$hazelcast/216/testReport/junit/com.hazelcast.map.mapstore.writebehind/WriteBehindWithEntryProcessorTest/updates_on_same_key_when_in_memory_format_is_object/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x/com.hazelcast$hazelcast/3665/testReport/junit/com.hazelcast.map.mapstore.writebehind/WriteBehindWithEntryProcessorTest/updates_on_same_key_when_in_memory_format_is_object/

**Comment by ahmetmircik** [comment]
Fixed via https://github.com/hazelcast/hazelcast/commit/df209d49da232f5c8f3c73f69267f06c5ffcfa44

**Comment by jerrinot** [comment]
@ahmetmircik: Could you please explain what was wrong with the test?

**Comment by ahmetmircik** [comment]
@jerrinot It was a leftover of the issue https://github.com/hazelcast/hazelcast/issues/4957. This test should have been refactored according to the fix.
