### ISSUE TITLE
ReplicatedMapTest Failures

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#6016]
**testEvictionObjectDelayDefault**
```
java.lang.AssertionError: CountDownLatch failed to complete within 120 seconds , count left: 1
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:718)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:711)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:703)
	at com.hazelcast.replicatedmap.ReplicatedMapTest.testEviction(ReplicatedMapTest.java:1148)
	at com.hazelcast.replicatedmap.ReplicatedMapTest.testEvictionObjectDelayDefault(ReplicatedMapTest.java:1109)
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast$hazelcast/662/testReport/junit/com.hazelcast.replicatedmap/ReplicatedMapTest/testEvictionObjectDelayDefault/

**Comment by hasancelik** [comment]
testAddListenerBinaryDelayDefault
```
java.util.concurrent.TimeoutException: Deadline reached. Remaining: 100
	at com.hazelcast.test.WatchedOperationExecutor.execute(WatchedOperationExecutor.java:58)
	at com.hazelcast.test.WatchedOperationExecutor.execute(WatchedOperationExecutor.java:37)
	at com.hazelcast.replicatedmap.ReplicatedMapTest.testAddEntryListener(ReplicatedMapTest.java:1090)
	at com.hazelcast.replicatedmap.ReplicatedMapTest.testAddListenerBinaryDelayDefault(ReplicatedMapTest.java:1073)
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.6/com.hazelcast$hazelcast/650/testReport/junit/com.hazelcast.replicatedmap/ReplicatedMapTest/testAddListenerBinaryDelayDefault/

**Comment by hasancelik** [comment]
**testContainsValueObjectDelay**
```
java.util.concurrent.TimeoutException: Deadline reached. Remaining: 25
	at com.hazelcast.test.WatchedOperationExecutor.execute(WatchedOperationExecutor.java:58)
	at com.hazelcast.test.WatchedOperationExecutor.execute(WatchedOperationExecutor.java:37)
	at com.hazelcast.replicatedmap.ReplicatedMapTest.testContainsValue(ReplicatedMapTest.java:827)
	at com.hazelcast.replicatedmap.ReplicatedMapTest.testContainsValueObjectDelay0(ReplicatedMapTest.java:797)
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.6/com.hazelcast$hazelcast/650/testReport/junit/com.hazelcast.replicatedmap/ReplicatedMapTest/testContainsValueObjectDelay0/

**Comment by hasancelik** [comment]
**testEvictionObjectDelayDefault**

```
java.lang.AssertionError: CountDownLatch failed to complete within 120 seconds , count left: 1
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:717)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:710)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:702)
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast$hazelcast/666/testReport/junit/com.hazelcast.replicatedmap/ReplicatedMapTest/testEvictionObjectDelayDefault/

**Comment by hasancelik** [comment]
**testValuesBinaryDefault**

```
java.util.concurrent.TimeoutException: Deadline reached. Remaining: 7
	at com.hazelcast.test.WatchedOperationExecutor.execute(WatchedOperationExecutor.java:58)
	at com.hazelcast.test.WatchedOperationExecutor.execute(WatchedOperationExecutor.java:37)
	at com.hazelcast.client.replicatedmap.ClientReplicatedMapTest.testValues(ClientReplicatedMapTest.java:612)
	at com.hazelcast.client.replicatedmap.ClientReplicatedMapTest.testValuesBinaryDefault(ClientReplicatedMapTest.java:596)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK1.6/com.hazelcast$hazelcast-client-new/667/testReport/junit/com.hazelcast.client.replicatedmap/ClientReplicatedMapTest/testValuesBinaryDefault/

**Comment by hasancelik** [comment]
**testKeySetObjectDelayDefault**

```
java.util.concurrent.TimeoutException: Deadline reached. Remaining: 16
	at com.hazelcast.test.WatchedOperationExecutor.execute(WatchedOperationExecutor.java:58)
	at com.hazelcast.test.WatchedOperationExecutor.execute(WatchedOperationExecutor.java:37)
	at com.hazelcast.client.replicatedmap.ClientReplicatedMapTest.testKeySet(ClientReplicatedMapTest.java:683)
	at com.hazelcast.client.replicatedmap.ClientReplicatedMapTest.testKeySetObjectDelayDefault(ClientReplicatedMapTest.java:653)
```

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.6/680/

**Comment by eminn** [comment]
Fixed by #6176

**Comment by hasancelik** [comment]
**testSizeBinaryDelay0
testKeySetBinaryDelay0
testContainsValueBinaryDelay0
testValuesObjectDelay0
testContainsValueObjectDelay0**

```
java.util.concurrent.TimeoutException: Deadline reached. Remaining: 55
	at com.hazelcast.test.WatchedOperationExecutor.execute(WatchedOperationExecutor.java:60)
	at com.hazelcast.test.WatchedOperationExecutor.execute(WatchedOperationExecutor.java:38)
	at com.hazelcast.client.replicatedmap.ClientReplicatedMapTest.testSize(ClientReplicatedMapTest.java:442)
	at com.hazelcast.client.replicatedmap.ClientReplicatedMapTest.testSizeBinaryDelay0(ClientReplicatedMapTest.java:427)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.maintenance-IbmJDK1.8/70/

**Comment by enesakar** [comment]
not failing for a long time
