### ISSUE TITLE
[discovery] Frequent warning in log, Packet versions are not matching! Expected -> 4, Incoming -> 3

### ISSUE THREAD

**Issue by zeedeveloper** [hazelcast/hazelcast#6040]
Just upgraded to 3.5.2-SNAPShot from 3.4, seeing large no of warning messages 

```
2015-08-21 08:40:13,594 - [warn] c.h.n.t.ReadHandler - [172.24.6.18]:5100 [stage] [3.5.2-SNAPSHOT] hz._hzInstance_1_stage.IO.thread-in-2 Closing socket to endpoint null, Cause:java.lang.IllegalArgumentException: Packet versions are not matching! Expected -> 4, Incoming -> 3
         at com.hazelcast.nio.Packet.readVersion(Packet.java:187) ~[com.hazelcast.hazelcast-3.5.2-SNAPSHOT.jar:3.5.2-SNAPSHOT]
        at com.hazelcast.nio.Packet.readFrom(Packet.java:153) ~[com.hazelcast.hazelcast-3.5.2-SNAPSHOT.jar:3.5.2-SNAPSHOT]
        at com.hazelcast.nio.tcp.DefaultPacketReader.readPacket(DefaultPacketReader.java:44) ~[com.hazelcast.hazelcast-3.5.2-SNAPSHOT.jar:3.5.2-SNAPSHOT]
        at com.hazelcast.nio.tcp.SocketPacketReader.read(SocketPacketReader.java:41) ~[com.hazelcast.hazelcast-3.5.2-SNAPSHOT.jar:3.5.2-SNAPSHOT]
        at com.hazelcast.nio.tcp.ReadHandler.handle(ReadHandler.java:113) ~[com.hazelcast.hazelcast-3.5.2-SNAPSHOT.jar:3.5.2-SNAPSHOT]
        at com.hazelcast.nio.tcp.InSelectorImpl.handleSelectionKey(InSelectorImpl.java:49) [com.hazelcast.hazelcast-3.5.2-SNAPSHOT.jar:3.5.2-SNAPSHOT]
        at com.hazelcast.nio.tcp.AbstractIOSelector.handleSelectionKeys(AbstractIOSelector.java:168) [com.hazelcast.hazelcast-3.5.2-SNAPSHOT.jar:3.5.2-SNAPSHOT]
        at com.hazelcast.nio.tcp.AbstractIOSelector.run(AbstractIOSelector.java:141) [com.hazelcast.hazelcast-3.5.2-SNAPSHOT.jar:3.5.2-SNAPSHOT]
```

**Comment by pveentjer** [comment]
First observation; we should not a stacktrace here. 

Do some member have 3.5 and others have 3.4? Afaik the packet version has been changed in 3.5 from 3 to 4.

**Comment by RobWin** [comment]
Same here.
We have to Hazelcast cluster running. One with 3.5.5 and one with an older version. But the clusters run on different ports and have different cluster names. Still we get the warning messages.

**Comment by jerrinot** [comment]
@RobWin: 
I assume you are using multicast discovery, is this correct? If so then you can isolate them by using a different multicast group or a port. See https://github.com/jerrinot/hazelcast/blob/caf2a852855bebaf94d3523459530c5136cc46e5/hazelcast/src/test/resources/hazelcast-fullconfig.xml#L79-L79

**Comment by RobWin** [comment]
Sry, I forgot to mention it.
We use tcp-ip and have configured an IP-range to configure several cluster members.

The cluster group with v3.5.5 uses port 5702. Then warn messages start to appear, because other nodes, which use a different cluster group name and hazelcast version, try to connect.

```
 {"@timestamp":"2016-03-21T11:19:07.988+01:00","@version":1,"message":"[172.20.19.82]:5702 [auxiliaries-hazelcast] [3.5.4] hz.auxiliaries-distributed-hazelcast.IO.thread-in-1 Closing socket to endpoint Address[172.20.19.82]:5701, Cause:java.io.EOFException: Remote socket closed!","logger_name":"com.hazelcast.nio.tcp.ReadHandler","thread_name":"hz.auxiliaries-distributed-hazelcast.IO.thread-in-1","level":"WARN","level_value":30000,"HOSTNAME":"spica01.aul.t-online.de","tags":null}

{"@timestamp":"2016-03-21T11:19:07.989+01:00","@version":1,"message":"[172.20.19.82]:5702 [spica-auxiliaries-hazelcast] [3.5.4] hz.spica-auxiliaries-distributed-hazelcast.IO.thread-in-2 Closing socket to endpoint Address[172.20.19.84]:5701, Cause:java.io.EOFException: Remote socket closed!","logger_name":"com.hazelcast.nio.tcp.ReadHandler","thread_name":"hz.spica-auxiliaries-distributed-hazelcast.IO.thread-in-2","level":"WARN","level_value":30000,"HOSTNAME":"spica01.aul.t-online.de","tags":null}
```

Then we have a, because port 5701 is already occupied by the old cluster:
```
{"@timestamp":"2016-03-21T11:19:13.007+01:00","@version":1,"message":"[172.20.19.82]:5702 [spica-auxiliaries-hazelcast] [3.5.4] Config seed port is 5701 and cluster size is 1. Some of the ports seem occupied!","logger_name":"com.hazelcast.instance.Node","thread_name":"localhost-startStop-1","level":"WARN","level_value":30000,"HOSTNAME":"spica01.aul.t-online.de","tags":null}
```

Then we receive:

```
{"@timestamp":"2016-03-21T11:24:44.850+01:00","@version":1,"message":"[172.20.19.82]:5702 [spica-auxiliaries-hazelcast] [3.5.4] hz.spica-auxiliaries-distributed-hazelcast.IO.thread-in-0 Closing socket to endpoint null, Cause:java.lang.IllegalArgumentException: Packet versions are not matching! Expected -> 4, Incoming -> 3","logger_name":"com.hazelcast.nio.tcp.ReadHandler","thread_name":"hz.spica-auxiliaries-distributed-hazelcast.IO.thread-in-0","level":"WARN","level_value":30000,"stack_trace":"java.lang.IllegalArgumentException: Packet versions are not matching! Expected -> 4, Incoming -> 3
```


The `com.hazelcast.nio.tcp.ReadHandler` keeps on throwing `Cause:java.io.EOFException: Remote socket closed`

**Comment by RobWin** [comment]
Any advice?

**Comment by jerrinot** [comment]
@RobWin: I am afraid for now the only advice is to suppress it in logging settings or ignore it. 
It does no harm and I believe it does not belong into WARN level.

**Comment by RobWin** [comment]
ok. thx.

**Comment by pveentjer** [comment]
Closing this ticket due to inactivity. Feel free to reopen it.
