### ISSUE TITLE
MapLoaderFailoverTest.testLoadsAll_whenInitialLoaderNodeRemovedAfterLoading

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#6056]
```
java.lang.AssertionError: Cluster size is not correct expected:<2> but was:<3>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:834)
    at org.junit.Assert.assertEquals(Assert.java:645)
    at com.hazelcast.test.HazelcastTestSupport.assertClusterSize(HazelcastTestSupport.java:662)
    at com.hazelcast.map.mapstore.MapLoaderFailoverTest.testLoadsAll_whenInitialLoaderNodeRemovedAfterLoading(MapLoaderFailoverTest.java:112)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK1.6/com.hazelcast$hazelcast/655/testReport/junit/com.hazelcast.map.mapstore/MapLoaderFailoverTest/testLoadsAll_whenInitialLoaderNodeRemovedAfterLoading/

**Comment by Donnerbart** [comment]
https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-OpenJDK8/lastCompletedBuild/com.hazelcast$hazelcast/testReport/com.hazelcast.map.mapstore/MapLoaderFailoverTest/testLoadsAll_whenInitialLoaderNodeRemovedAfterLoading/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.maintenance/com.hazelcast$hazelcast/978/testReport/junit/com.hazelcast.map.mapstore/MapLoaderFailoverTest/testLoadsAll_whenInitialLoaderNodeRemovedAfterLoading/

**Comment by hasancelik** [comment]
```
org.junit.runners.model.TestTimedOutException: test timed out after 60000 milliseconds
	at java.lang.Object.wait(Native Method)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.pollResponse(InvocationFuture.java:300)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.waitForResponse(InvocationFuture.java:245)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.get(InvocationFuture.java:222)
	at com.hazelcast.util.FutureUtil.executeWithDeadline(FutureUtil.java:294)
	at com.hazelcast.util.FutureUtil.waitWithDeadline(FutureUtil.java:278)
	at com.hazelcast.util.FutureUtil.waitWithDeadline(FutureUtil.java:252)
	at com.hazelcast.map.impl.proxy.MapProxySupport.waitUntilLoaded(MapProxySupport.java:508)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.waitUntilLoaded(MapProxyImpl.java:80)
	at com.hazelcast.map.impl.proxy.MapProxySupport.loadAllInternal(MapProxySupport.java:412)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.loadAll(MapProxyImpl.java:543)
	at com.hazelcast.map.impl.mapstore.MapLoaderFailoverTest.testLoadsAll_whenInitialLoaderNodeRemovedAfterLoading(MapLoaderFailoverTest.java:112)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK8/com.hazelcast$hazelcast/688/testReport/junit/com.hazelcast.map.impl.mapstore/MapLoaderFailoverTest/testLoadsAll_whenInitialLoaderNodeRemovedAfterLoading/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: expected:<2> but was:<1>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.map.impl.mapstore.MapLoaderFailoverTest.testLoadsAll_whenInitialLoaderNodeRemovedAfterLoading(MapLoaderFailoverTest.java:113)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-OracleJDK1.6/com.hazelcast$hazelcast/881/testReport/junit/com.hazelcast.map.impl.mapstore/MapLoaderFailoverTest/testLoadsAll_whenInitialLoaderNodeRemovedAfterLoading/

**Comment by tombujok** [comment]
Managed to reproduce with Repeat(1000) on 
```
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)
```

**Comment by hasancelik** [comment]
suppressed by https://github.com/hazelcast/hazelcast/commit/2543fd9c08fdd81f20267190d798bcf56af9da51

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: expected:<2> but was:<3>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.map.impl.mapstore.MapLoaderFailoverTest.testLoadsAll_whenInitialLoaderNodeRemovedAfterLoading(MapLoaderFailoverTest.java:115)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast$hazelcast/1010/testReport/junit/com.hazelcast.map.impl.mapstore/MapLoaderFailoverTest/testLoadsAll_whenInitialLoaderNodeRemovedAfterLoading/

**Comment by mdogan** [comment]
No failure since Aug 23.
