### ISSUE TITLE
MapReduceTest.testKeyedMapperCollator & testKeyPredicateMapperCollator

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#6059]
```
org.junit.runners.model.TestTimedOutException: test timed out after 60000 milliseconds
    at java.lang.Object.wait(Native Method)
    at java.lang.Object.wait(Object.java:196)
    at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.pollResponse(InvocationFuture.java:300)
    at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.waitForResponse(InvocationFuture.java:245)
    at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.get(InvocationFuture.java:222)
    at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.get(InvocationFuture.java:202)
    at com.hazelcast.map.impl.proxy.MapProxySupport.invokeOperation(MapProxySupport.java:436)
    at com.hazelcast.map.impl.proxy.MapProxySupport.putInternal(MapProxySupport.java:397)
    at com.hazelcast.map.impl.proxy.MapProxyImpl.put(MapProxyImpl.java:97)
    at com.hazelcast.map.impl.proxy.MapProxyImpl.put(MapProxyImpl.java:87)
    at com.hazelcast.mapreduce.MapReduceTest.testKeyPredicateMapperCollator(MapReduceTest.java:379)
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast$hazelcast/671/testReport/junit/com.hazelcast.mapreduce/MapReduceTest/testKeyedMapperCollator/

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast$hazelcast/671/testReport/junit/com.hazelcast.mapreduce/MapReduceTest/testKeyPredicateMapperCollator/

**Comment by metanet** [comment]
see comment: https://github.com/hazelcast/hazelcast/issues/7783#issuecomment-233252321

**Comment by mdogan** [comment]
Map reduce is going to be deprecated and eventually removed. Won't be fixed.
