### ISSUE TITLE
PerformanceMonitor exception encountered in Member logs 

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#6098]
I found this loan exception in the member logs during at test run.   other than this exception did not seen any other effects.

```
Current state = FLUSHED, new s
tate = CODING
java.lang.IllegalStateException: Current state = FLUSHED, new state = CODING
    at java.nio.charset.CharsetEncoder.throwIllegalStateException(CharsetEncoder.java:992)
    at java.nio.charset.CharsetEncoder.encode(CharsetEncoder.java:572)
    at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:271)
    at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:125)
    at java.io.OutputStreamWriter.write(OutputStreamWriter.java:207)
    at java.io.BufferedWriter.flushBuffer(BufferedWriter.java:129)
    at java.io.BufferedWriter.flush(BufferedWriter.java:253)
    at com.hazelcast.internal.monitors.PerformanceLogFile$HeadRenderer.render(PerformanceLogFile.java:233)
    at com.hazelcast.internal.monitors.PerformanceLogFile$HeadRenderer.access$100(PerformanceLogFile.java:224)
    at com.hazelcast.internal.monitors.PerformanceLogFile.render(PerformanceLogFile.java:119)
    at com.hazelcast.internal.monitors.PerformanceMonitor$MonitorThread.run(PerformanceMonitor.java:99)
```

**Comment by pveentjer** [comment]
Which Java version/vendor did you use?

**Comment by pveentjer** [comment]
I found the cause of the exception; managed to reproduce it consistently. It is caused by the CharsetEncoder which is put in a static field, but it isn't threadsafe. I now create a new Charsetencoder for every rollover and problem is gone.
