### ISSUE TITLE
[TEST-FAILURE] MigrationAwareServiceTest.testPartitionDataSize_whenBackupNodesTerminated_withSingleBackup

### ISSUE THREAD

**Issue by Donnerbart** [hazelcast/hazelcast#6115]
**Note:** This failure occurred on the Hazelcast-3.x-IbmJDK1.6 build job!

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK1.6/663/
```
Error Message

expected:<542> but was:<517>
Stacktrace

java.lang.AssertionError: expected:<542> but was:<517>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.spi.MigrationAwareServiceTest$3.run(MigrationAwareServiceTest.java:221)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:751)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:765)
	at com.hazelcast.spi.MigrationAwareServiceTest.assertSize(MigrationAwareServiceTest.java:210)
	at com.hazelcast.spi.MigrationAwareServiceTest.testPartitionDataSize_whenBackupNodesTerminated(MigrationAwareServiceTest.java:146)
	at com.hazelcast.spi.MigrationAwareServiceTest.testPartitionDataSize_whenBackupNodesTerminated_withSingleBackup(MigrationAwareServiceTest.java:124)
```

**Comment by eminn** [comment]
No build log available, closing the issue.
