### ISSUE TITLE
[TEST-FAILURE] CacheReadWriteQuorumTest.testPutGetWhenQuorumSizeMet

### ISSUE THREAD

**Issue by Donnerbart** [hazelcast/hazelcast#6120]
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at org.junit.Assert.assertFalse(Assert.java:74)
	at com.hazelcast.quorum.PartitionedCluster$3.run(PartitionedCluster.java:118)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:751)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:765)
	at com.hazelcast.quorum.PartitionedCluster.splitFiveMembersThreeAndTwo(PartitionedCluster.java:113)
	at com.hazelcast.quorum.PartitionedCluster.partitionFiveMembersThreeAndTwo(PartitionedCluster.java:62)
	at com.hazelcast.quorum.cache.CacheReadWriteQuorumTest.initialize(CacheReadWriteQuorumTest.java:93)
```
https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-OpenJDK8/674/com.hazelcast$hazelcast/testReport/com.hazelcast.quorum.cache/CacheReadWriteQuorumTest/com_hazelcast_quorum_cache_CacheReadWriteQuorumTest/

**Comment by mustafaiman** [comment]
closed via https://github.com/hazelcast/hazelcast/pull/6164
