### ISSUE TITLE
LeaseLock simulator test hanging, 3-6.SNAPSHOT

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#6141]
I see all 10 threads of all 4 boxes hanging for ever 

```
grep -r --include *.out LeaseLockTest .
./54.209.174.3/54.209.174.3-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.174.3/54.209.174.3-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.174.3/54.209.174.3-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.174.3/54.209.174.3-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.174.3/54.209.174.3-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.174.3/54.209.174.3-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.174.3/54.209.174.3-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.174.3/54.209.174.3-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.174.3/54.209.174.3-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.174.3/54.209.174.3-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.174.3/54.209.174.3-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest.run(LeaseLockTest.java:48)
./54.209.168.17/54.209.168.17-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.168.17/54.209.168.17-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.168.17/54.209.168.17-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.168.17/54.209.168.17-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.168.17/54.209.168.17-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.168.17/54.209.168.17-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.168.17/54.209.168.17-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.168.17/54.209.168.17-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.168.17/54.209.168.17-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.168.17/54.209.168.17-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.168.17/54.209.168.17-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest.run(LeaseLockTest.java:48)
./54.209.163.81/54.209.163.81-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.163.81/54.209.163.81-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.163.81/54.209.163.81-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.163.81/54.209.163.81-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.163.81/54.209.163.81-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.163.81/54.209.163.81-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.163.81/54.209.163.81-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.163.81/54.209.163.81-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.163.81/54.209.163.81-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.163.81/54.209.163.81-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.163.81/54.209.163.81-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest.run(LeaseLockTest.java:48)
./54.209.172.17/54.209.172.17-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.172.17/54.209.172.17-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.172.17/54.209.172.17-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.172.17/54.209.172.17-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.172.17/54.209.172.17-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.172.17/54.209.172.17-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.172.17/54.209.172.17-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.172.17/54.209.172.17-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.172.17/54.209.172.17-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.172.17/54.209.172.17-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.172.17/54.209.172.17-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest.run(LeaseLockTest.java:48)
```

The line.
```
find ~ -name LeaseLockTest.java | xargs cat -n | grep 64
    64	                    lock.lock(lease, TimeUnit.MILLISECONDS);
```

the essential test code 

```
   24	    public int lockCount = 500;
    25	    public int maxleaseTime = 100;
    26	    public int maxTryTime = 100;
```

```
  56	            while (!testContext.isStopped()) {
    57	                int i = random.nextInt(lockCount);
    58	                ILock lock = targetInstance.getLock(basename+i);
    59
    60	                int lease = 1 + random.nextInt(maxleaseTime);
    61	                int tryTime = 1 + random.nextInt(maxleaseTime);
    62
    63	                if (random.nextBoolean()) {
    64	                    lock.lock(lease, TimeUnit.MILLISECONDS);
    65	                }else {
    66	                    try {
    67	                        lock.tryLock(tryTime, TimeUnit.MILLISECONDS, lease, TimeUnit.MILLISECONDS);
    68	                    } catch (InterruptedException e) {
    69	                        e.printStackTrace();
    70	                    }
    71	                }
    72	            }
```

**Comment by Danny-Hazelcast** [comment]
in code snippet above.  
All locks are obtained with a lease.
All locks should at some time be released.
All locks should become obtainable. 
so 
all call to lock.lock should eventually return.

**Comment by Danny-Hazelcast** [comment]
the test has been hanging for 
```
INFO  13:25:50 lock Waiting 00d 00h 21m 02s for run completion
INFO  13:25:56 lock Waiting 00d 00h 21m 08s for run completion
INFO  13:26:02 lock Waiting 00d 00h 21m 14s for run completion
```

**Comment by Danny-Hazelcast** [comment]
a link to the simulator test code

https://github.com/Danny-Hazelcast/hazelcast-stabilizer/blob/leaseLock/tests/src/main/java/com/hazelcast/simulator/tests/concurrent/lock/LeaseLockTest.java

**Comment by Danny-Hazelcast** [comment]
full logs https://s3.amazonaws.com/dannyc/issues/leaseLock.zip

**Comment by Danny-Hazelcast** [comment]
looking through the logs, i don't see any excetions, or any interesting logs

**Comment by Danny-Hazelcast** [comment]
when increasing the minimum time a lock leas can be held for,  e.g.
```
int lease = 4000 + random.nextInt(maxleaseTime);
int tryTime = 4000 + random.nextInt(maxTryTime);
```

I can still reproduce this issue.

**Comment by Danny-Hazelcast** [comment]
we might have a possible regression with this issue.

our weekly jenkins simulator jobs,  have started to hang again,  
however the nightly jobs seem to run ok,

weekly jobs run on more power full aws boxes and run more clients, producing more load.

leaseLockTest hanging 

```
./jstack/54.175.63.51/54.175.63.51-clientJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.timeStep(LeaseLockTest.java:68)

[jenkins@ip-10-72-134-107 2015_09_21-10_59_13]$ find ~ -name LeaseLockTest.java | xargs cat -n | grep 68
    68	                lock.lock(leaseTime, TimeUnit.MILLISECONDS);
```

**Comment by Danny-Hazelcast** [comment]
@gurbuzali 

stack trace of client's and server's
https://s3.amazonaws.com/dannyc/issues/jstack-issues-6141.zip

**Comment by gurbuzali** [comment]
looking into it

**Comment by jerrinot** [comment]
moving milestone to 3.6 as the try-with-lease-lock feature does not exist in 3.5.x

**Comment by Danny-Hazelcast** [comment]
@gurbuzali   this issue is still occurring.  however it looks like it's only failing in 1 of our simulator jenkins jobs.   

https://hazelcast-l337.ci.cloudbees.com/view/Simulator/job/Hazelcast-Simulator-weekly-enterprise/41/consoleFull

**Comment by Donnerbart** [comment]
The shutdown of the normal nightly enterprise run takes quite some time during shutdown of the Hazelcast instance. We have a ton of this warnings in the log:
```
10.0.0.165]:5701 [workers] [3.6-RC1-SNAPSHOT] Error during rollback!
java.util.concurrent.ExecutionException: com.hazelcast.core.HazelcastInstanceNotActiveException: State: PASSIVE Operation: class com.hazelcast.map.impl.tx.TxnRollbackOperation
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveApplicationResponseOrThrowException(InvocationFuture.java:358)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.get(InvocationFuture.java:223)
	at com.hazelcast.util.FutureUtil.executeWithDeadline(FutureUtil.java:294)
	at com.hazelcast.util.FutureUtil.waitWithDeadline(FutureUtil.java:278)
	at com.hazelcast.util.FutureUtil.waitWithDeadline(FutureUtil.java:252)
	at com.hazelcast.transaction.impl.TransactionImpl.rollback(TransactionImpl.java:307)
	at com.hazelcast.transaction.impl.TransactionContextImpl.rollbackTransaction(TransactionContextImpl.java:80)
	at com.hazelcast.client.impl.ClientEndpointImpl.destroy(ClientEndpointImpl.java:229)
	at com.hazelcast.client.impl.ClientEndpointManagerImpl.removeEndpoint(ClientEndpointManagerImpl.java:115)
	at com.hazelcast.client.impl.ClientEndpointManagerImpl.removeEndpoints(ClientEndpointManagerImpl.java:150)
	at com.hazelcast.client.impl.ClientEngineImpl$DestroyEndpointTask.run(ClientEngineImpl.java:609)
	at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)
Caused by: com.hazelcast.core.HazelcastInstanceNotActiveException: State: PASSIVE Operation: class com.hazelcast.map.impl.tx.TxnRollbackOperation
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.engineActive(Invocation.java:285)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:227)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invokeInternal(Invocation.java:210)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:180)
	at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.invokeOnPartition(OperationServiceImpl.java:310)
	at com.hazelcast.transaction.impl.TransactionLog.invoke(TransactionLog.java:134)
	at com.hazelcast.transaction.impl.TransactionLog.rollback(TransactionLog.java:122)
	at com.hazelcast.transaction.impl.TransactionImpl.rollback(TransactionImpl.java:306)
	... 11 more
```
I don't know if this is related to the lease lock issue, but it looks suspicious.

**Comment by Danny-Hazelcast** [comment]
1 more lease lock hang https://hazelcast-l337.ci.cloudbees.com/view/Simulator/job/Hazelcast-Simulator-nightly/276/console

**Comment by Danny-Hazelcast** [comment]
Got this verification exception from a non hanging run of lease lock test

[java.lang.AssertionError: ILock{name='leaseLock1'} is locked with remainingLeaseTime: 0 ms]

**Comment by Danny-Hazelcast** [comment]
issue still occurring randomly

**Comment by Danny-Hazelcast** [comment]
3.6-RC1 xlarge sim run,  Failed with this issue.

```
INFO  07:56:59 leaseLock            Waiting 00d 08h 02m 00s for run completion (36/125 workers)```
```

I ran the normal simulator test suit,  on a X-Large cluster.  repeatedly for a short duration of 30mins
after 10 successful iterations of this test.

the 11th iteration Hung in the LeasLock test.

**Comment by Danny-Hazelcast** [comment]
another Lease Lock test hang.
https://hazelcast-l337.ci.cloudbees.com/view/Simulator/job/Hazelcast-Simulator-weekly/115/

**Comment by mdogan** [comment]
@Danny-Hazelcast: expecting https://github.com/hazelcast/hazelcast/pull/6904 to fix this problem.

**Comment by Danny-Hazelcast** [comment]
we have to re-open this issue as Leas lock has hung again using 

Hazelcast 3.6-RC2-SNAPSHOT (20151203 - a91b48a)  

```
INFO  16:13:10 leaseLock            Waiting 00d 00h 22m 30s for run completion (79/125 workers)
```

The test hung on the 6th iteration  of a 30min test  using the X-large cluster format  with the normal test.properites of nightly weekly test runs

**Comment by Danny-Hazelcast** [comment]
hang https://hazelcast-l337.ci.cloudbees.com/view/Simulator/job/Hazelcast-Simulator-weekly/116/

**Comment by Danny-Hazelcast** [comment]
hang  https://hazelcast-l337.ci.cloudbees.com/view/Simulator/job/Hazelcast-Simulator-weekly-enterprise/49/console

**Comment by gurbuzali** [comment]
@Danny-Hazelcast this should have been fixed with the latest changes here https://github.com/hazelcast/hazelcast/pull/7117 can you please check

**Comment by Danny-Hazelcast** [comment]
@gurbuzali @mdogan  I am currently tests for this issue,  on master,  

if I reproduce the hang issue,   then  I will reopen this issue

**Comment by Danny-Hazelcast** [comment]
our simulator weekly test run's,  has hanged again 

```
11:13:54 INFO  11:13:54 leaseLock                  Waiting 01d 03h 58m 30s for run completion (10/110 workers)
```

failed jenkins build 
https://hazelcast-l337.ci.cloudbees.com/view/Simulator/job/Hazelcast-Simulator-weekly-enterprise/71/console

logs of run
http://54.87.52.100/~jenkins/workspace/Hazelcast-Simulator-weekly-enterprise/3.7-SNAPSHOT/2016_05_01-01_12_11/

logs backup
https://s3.amazonaws.com/dannyc/issues/leaseLock-regression.zip

**Comment by gurbuzali** [comment]
@Danny-Hazelcast it appears that some clients are having heart-beat problems and throwing `TargetDisconnectedException`. This may not be the original hanging problem related with lease-lock but a general connection issue related with client. I haven't looked at the logs deeply to be able to get a conclusion though. Do we have any other failures, besides this one ?

**Comment by gurbuzali** [comment]
I'm going to close this one. it appears that we do not see any more failures and the one above mentioned failure looks like a generic client issue.

**Comment by Danny-Hazelcast** [comment]
yes also we have not seen the lease lock test hange,  in nightly sim runs for a very long time.
