### ISSUE TITLE
[TEST-FAILURE] map.ClientMapPartitionLostListenerTest.test_mapPartitionLostListener_invoked_fromOtherNode

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#6142]
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at org.junit.Assert.assertFalse(Assert.java:74)
	at com.hazelcast.client.map.ClientMapPartitionLostListenerTest$1.run(ClientMapPartitionLostListenerTest.java:97)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:737)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:751)
	at com.hazelcast.client.map.ClientMapPartitionLostListenerTest.assertMapPartitionLostEventEventually(ClientMapPartitionLostListenerTest.java:91)
	at com.hazelcast.client.map.ClientMapPartitionLostListenerTest.test_mapPartitionLostListener_invoked_fromOtherNode(ClientMapPartitionLostListenerTest.java:124)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.maintenance-IbmJDK1.6/com.hazelcast$hazelcast-client-new/285/testReport/junit/com.hazelcast.client.map/ClientMapPartitionLostListenerTest/test_mapPartitionLostListener_invoked_fromOtherNode/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at org.junit.Assert.assertFalse(Assert.java:74)
	at com.hazelcast.client.map.ClientMapPartitionLostListenerTest$1.run(ClientMapPartitionLostListenerTest.java:102)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:737)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:751)
	at com.hazelcast.client.map.ClientMapPartitionLostListenerTest.assertMapPartitionLostEventEventually(ClientMapPartitionLostListenerTest.java:96)
	at com.hazelcast.client.map.ClientMapPartitionLostListenerTest.test_mapPartitionLostListener_invoked_fromOtherNode(ClientMapPartitionLostListenerTest.java:136)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-IbmJDK1.8/com.hazelcast$hazelcast-client-new/11/testReport/junit/com.hazelcast.client.map/ClientMapPartitionLostListenerTest/test_mapPartitionLostListener_invoked_fromOtherNode/

**Comment by metanet** [comment]
Closed by https://github.com/hazelcast/hazelcast/commit/839b0c339ac2b4958fe9a5129fea311005371643
