### ISSUE TITLE
NullPointerException when adding index

### ISSUE THREAD

**Issue by wimdeblauwe** [hazelcast/hazelcast#6151]
The following unit test shows the NullPointerException:

```
package com.traficon.tmsng.server;

import com.hazelcast.config.Config;
import com.hazelcast.config.MapConfig;
import com.hazelcast.config.MapIndexConfig;
import com.hazelcast.core.Hazelcast;
import com.hazelcast.core.HazelcastInstance;
import com.hazelcast.core.IMap;

import java.io.Serializable;

/**
 * Created by wdb on 07/09/15.
 */
public class HazelcastIndexTest
{
	public static void main( String[] args )
	{
		Config config = new Config();
		MapConfig mapConfig = new MapConfig();
		mapConfig.setName( "test" );
		mapConfig.addMapIndexConfig( new MapIndexConfig( "name", false ) );
		mapConfig.addMapIndexConfig( new MapIndexConfig( "testInterface.foo", false ) );
		config.addMapConfig( mapConfig );
		HazelcastInstance hazelcastInstance = Hazelcast.newHazelcastInstance( config );

		IMap<Object, Object> testMap = hazelcastInstance.getMap( "test" );

		testMap.put( "key", new Person() );
	}

	private static class Person implements Serializable
	{
		private String m_name;
		private TestInterface m_testInterface;

		public String getName()
		{
			return m_name;
		}

		public void setName( String name )
		{
			m_name = name;
		}

		public TestInterface getTestInterface()
		{
			return m_testInterface;
		}

		public void setTestInterface( TestInterface testInterface )
		{
			m_testInterface = testInterface;
		}
	}

	private static interface TestInterface
	{

	}

	private static class TestInterfaceImpl implements TestInterface
	{
		private String m_foo;

		public String getFoo()
		{
			return m_foo;
		}

		public void setFoo( String foo )
		{
			m_foo = foo;
		}
	}
}
```

And this is the resulting exception:

```
Exception in thread "main" com.hazelcast.query.QueryException: java.lang.NullPointerException
	at com.hazelcast.query.impl.getters.ReflectionHelper.createGetter(ReflectionHelper.java:204)
	at com.hazelcast.query.impl.getters.ReflectionHelper.getAttributeType(ReflectionHelper.java:128)
	at com.hazelcast.query.impl.QueryEntry.getAttributeType(QueryEntry.java:174)
	at com.hazelcast.query.impl.IndexImpl.saveEntryIndex(IndexImpl.java:83)
	at com.hazelcast.query.impl.IndexService.saveEntryIndex(IndexService.java:83)
	at com.hazelcast.map.impl.AbstractRecordStore.saveIndex(AbstractRecordStore.java:159)
	at com.hazelcast.map.impl.DefaultRecordStore.put(DefaultRecordStore.java:776)
	at com.hazelcast.map.impl.operation.PutOperation.run(PutOperation.java:34)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:137)
	at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.processOperation(OperationThread.java:154)
	at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.process(OperationThread.java:110)
	at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.doRun(OperationThread.java:101)
	at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.run(OperationThread.java:76)
Caused by: java.lang.NullPointerException
	at com.hazelcast.query.impl.getters.ReflectionHelper.createGetter(ReflectionHelper.java:180)
	... 12 more
```

The problem is that we want to index on a field `foo` that is only available in a subclass of the interface `TestInterface`. This works fine in Coherence.

Is there any workaround we can use for now?

We are using Hazelcast 3.5 on Java 8.

**Comment by serkan-ozal** [comment]
A few notes on this issue:

- Super class of an interface is `null` in Java. So this code template
``` java
while (!Object.class.equals(c)) {
    try {
        ...
    } catch (NoSuchFieldException ignored) {
        c = c.getSuperclass();
    }
}
```
is prune to NPE unless there is interface check. If the class is interface, no need to `getDeclaredField(name);`.

- While iterating over field, instance's type should be used instead of `field.getType()`

**Comment by jerrinot** [comment]
@wimdeblauwe: I'm afraid the best workaround I can see right now is to add the method `String getFoo()` into the `TestInterface` interface.

I'll send a PR to fix the NPE, but in won't help with your case. You will just get a more descriptive error message.

**Comment by jerrinot** [comment]
this is fixed by #6182 and #6185 (backport)

**Comment by wimdeblauwe** [comment]
Shouldn't the PENDING label be removed?

**Comment by jerrinot** [comment]
@wimdeblauwe: You are right, thanks!
