### ISSUE TITLE
[TEST-FAILURE] client.quorum.ClientTransactionalMapQuorumTest

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#6170]
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at org.junit.Assert.assertFalse(Assert.java:74)
	at com.hazelcast.quorum.PartitionedCluster$3.run(PartitionedCluster.java:117)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:761)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:775)
	at com.hazelcast.quorum.PartitionedCluster.splitFiveMembersThreeAndTwo(PartitionedCluster.java:113)
	at com.hazelcast.quorum.PartitionedCluster.partitionFiveMembersThreeAndTwo(PartitionedCluster.java:57)
	at com.hazelcast.client.quorum.ClientTransactionalMapQuorumTest.initialize(ClientTransactionalMapQuorumTest.java:96)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-OpenJDK8/com.hazelcast$hazelcast-client-new/683/testReport/junit/com.hazelcast.client.quorum/ClientTransactionalMapQuorumTest/com_hazelcast_client_quorum_ClientTransactionalMapQuorumTest/

**Comment by mustafaiman** [comment]
closed via https://github.com/hazelcast/hazelcast/pull/6164
