### ISSUE TITLE
[TEST-FAILURE] BasicMapTest.testPutWithTtl

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#6196]
```
java.lang.AssertionError: expected:<value> but was:<null>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.map.BasicMapTest.testPutWithTtl(BasicMapTest.java:1107)
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x/com.hazelcast$hazelcast/3739/testReport/junit/com.hazelcast.map/BasicMapTest/testPutWithTtl/

**Comment by hasancelik** [comment]
**maintenance**

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-OpenJDK7/com.hazelcast$hazelcast/292/testReport/junit/com.hazelcast.map/BasicMapTest/testPutWithTtl/

**Comment by tombujok** [comment]
Managed to reproduce locally with `@Repeat(1000)` 

```
14:04:44,646  INFO [Node] testPutWithTtl - [127.0.0.1]:5488 [dev] [3.6-SNAPSHOT] Hazelcast Shutdown is completed in 1 ms.
14:04:44,646  INFO [LifecycleService] testPutWithTtl - [127.0.0.1]:5488 [dev] [3.6-SNAPSHOT] Address[127.0.0.1]:5488 is SHUTDOWN

java.lang.AssertionError: 
Expected :value
Actual   :null
 <Click to see difference>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.map.BasicMapTest.testPutWithTtl(BasicMapTest.java:1109)
	at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:134)
	at com.hazelcast.test.AbstractHazelcastClassRunner$TestRepeater.evaluate(AbstractHazelcastClassRunner.java:219)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at com.hazelcast.test.HazelcastParallelClassRunner.access$201(HazelcastParallelClassRunner.java:35)
	at com.hazelcast.test.HazelcastParallelClassRunner$TestRunner.run(HazelcastParallelClassRunner.java:119)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by gurbuzali** [comment]
test depends on event-system which has no guarantees to deliver. 
another thing is the comment `ttl should be bigger than 5sec (= sync backup wait timeout)`. it means if backup-response does not come, put will return after waiting for 5 seconds which means only 1 second left for the entry to live. 
I think we should remove the `get` check totally 
and replace `latch` check with an assertEventually

**Comment by tombujok** [comment]
Yes, I agree. I will remove the `assertEquals("value", map.get("key"));` as it doesn't generate any added value in this test.

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: expected:<value> but was:<null>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.map.BasicMapTest.testPutWithTtl(BasicMapTest.java:1106)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-OracleJDK1.6/com.hazelcast$hazelcast/312/testReport/junit/com.hazelcast.map/BasicMapTest/testPutWithTtl/

**Comment by gurbuzali** [comment]
it appears that the maintenance was not fixed
closed via https://github.com/hazelcast/hazelcast/commit/48abc74dd1660373c5137ce52a174e1e72576a6a
