### ISSUE TITLE
[TEST-FAILURE] MigrationAwareServiceTest.testPartitionDataSize_whenBackupNodesTerminated_withTwoBackups

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#6197]
```
java.lang.AssertionError: expected:<813> but was:<798>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.spi.MigrationAwareServiceTest$3.run(MigrationAwareServiceTest.java:220)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:804)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:818)
	at com.hazelcast.spi.MigrationAwareServiceTest.assertSize(MigrationAwareServiceTest.java:209)
	at com.hazelcast.spi.MigrationAwareServiceTest.testPartitionDataSize_whenBackupNodesTerminated(MigrationAwareServiceTest.java:145)
	at com.hazelcast.spi.MigrationAwareServiceTest.testPartitionDataSize_whenBackupNodesTerminated_withTwoBackups(MigrationAwareServiceTest.java:128)
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.6/com.hazelcast$hazelcast/674/testReport/junit/com.hazelcast.spi/MigrationAwareServiceTest/testPartitionDataSize_whenBackupNodesTerminated_withTwoBackups/

**Comment by eminn** [comment]
No build log available, closing the issue.
