### ISSUE TITLE
[TEST-FAILURE] JettyStickySessionsTest Failures

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#6231]
```
java.lang.NullPointerException: null
	at java.lang.Thread.toString(Thread.java:1061)
	at java.lang.String.valueOf(String.java:1657)
	at org.eclipse.jetty.util.log.StdErrLog.format(StdErrLog.java:658)
	at org.eclipse.jetty.util.log.StdErrLog.format(StdErrLog.java:559)
	at org.eclipse.jetty.util.log.StdErrLog.warn(StdErrLog.java:414)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.doStop(QueuedThreadPool.java:176)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.stop(ContainerLifeCycle.java:143)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStop(ContainerLifeCycle.java:162)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStop(AbstractHandler.java:73)
	at org.eclipse.jetty.server.Server.doStop(Server.java:456)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
	at com.hazelcast.session.JettyConfigurator.stop(JettyConfigurator.java:78)
	at com.hazelcast.session.AbstractHazelcastSessionsTest.cleanup(AbstractHazelcastSessionsTest.java:35)
	at sun.reflect.GeneratedMethodAccessor27.invoke(Unknown Source)
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-ee-IbmJDK1.7/com.hazelcast$hazelcast-enterprise-jetty9/420/testReport/junit/com.hazelcast.session.nonsticky/JettyP2PNonStickySessionsTest/testAttributeDistribution/

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-ee-IbmJDK1.7/com.hazelcast$hazelcast-enterprise-jetty9/423/testReport/junit/com.hazelcast.session.sticky/JettyClientServerStickySessionsTest/testAttributeInvalidate/

**Comment by hasancelik** [comment]
11 test failures with different errors:

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-ee-IbmJDK1.7/com.hazelcast$hazelcast-enterprise-jetty9/425/

**By the way, all of test failures occurred on IBM-jdk-7 for now.**
