### ISSUE TITLE
During Polling : com.hazelcast.core.OperationTimeoutException: No response for 20000 ms

### ISSUE THREAD

**Issue by jatingupta12** [hazelcast/hazelcast#6244]
Hazelcast jar version - 3.2.3 , Java version  "1.6.0" (Websphere 7)
Masked the IP address

Exception:

com.hazelcast.core.OperationTimeoutException: No response for 20000 ms. A
borting invocation! InvocationFuture{invocation=BasicInvocation{ serviceName='hz:impl:queueService', op=com.hazelcast.queue.PollOperation@5e565e56, partitionId=197, replicaIndex=0, tryCount=250, tr
yPauseMillis=500, invokeCount=1, callTimeout=10000, target=Address[XX.XX.XX.XXX]:7777}, done=false} No response has been send  backups-expected: 0 backups-completed: 0 reinvocations: 0
com.hazelcast.core.OperationTimeoutException: No response for 20000 ms. Aborting invocation! InvocationFuture{invocation=BasicInvocation{ serviceName='hz:impl:queueService', op=com.hazelcast.queue.
PollOperation@5e565e56, partitionId=197, replicaIndex=0, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeout=10000, target=Address[XX.XX.XX.XXX]:7777}, done=false} No response has been send  backups-expected: 0 backups-completed: 0 reinvocations: 0
        at com.hazelcast.spi.impl.BasicInvocation$InvocationFuture.newOperationTimeoutException(BasicInvocation.java:782)
        at com.hazelcast.spi.impl.BasicInvocation$InvocationFuture.waitForResponse(BasicInvocation.java:760)
        at com.hazelcast.spi.impl.BasicInvocation$InvocationFuture.get(BasicInvocation.java:697)
        at com.hazelcast.spi.impl.BasicInvocation$InvocationFuture.get(BasicInvocation.java:676)
        at com.hazelcast.queue.proxy.QueueProxySupport.pollInternal(QueueProxySupport.java:108)
        at com.hazelcast.queue.proxy.QueueProxyImpl.poll(QueueProxyImpl.java:75)
        at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:191)
        at org.springframework.aop.framework.Cglib2AopProxy$CglibMethodInvocation.invokeJoinpoint(Cglib2AopProxy.java:689)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
        at org.springframework.aop.interceptor.AsyncExecutionInterceptor$1.call(AsyncExecutionInterceptor.java:83)
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:314)
        at java.util.concurrent.FutureTask.run(FutureTask.java:149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
        at java.lang.Thread.run(Thread.java:767)
        at ------ End remote and begin local stack-trace ------.(Unknown Source)
        at java.lang.Thread.getStackTrace(Thread.java:1076)
        at com.hazelcast.spi.impl.BasicInvocation$InvocationFuture.resolveResponse(BasicInvocation.java:862)
        at com.hazelcast.spi.impl.BasicInvocation$InvocationFuture.resolveResponseOrThrowException(BasicInvocation.java:795)
        at com.hazelcast.spi.impl.BasicInvocation$InvocationFuture.get(BasicInvocation.java:698)
        at com.hazelcast.spi.impl.BasicInvocation$InvocationFuture.get(BasicInvocation.java:676)
        at com.hazelcast.queue.proxy.QueueProxySupport.pollInternal(QueueProxySupport.java:108)
        at com.hazelcast.queue.proxy.QueueProxyImpl.poll(QueueProxyImpl.java:75)

------------------------------------------

Below is the hazelcast xml config
-------------------------------------------
<hazelcast
	xsi:schemaLocation="http://www.hazelcast.com/schema/config hazelcast-config-3.1.xsd"
	xmlns="http://www.hazelcast.com/schema/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

	<group>
		<name>asvpool</name>
		<password>acv</password>
	</group>

	<management-center enabled="true">http://localhost:8080/mancenter-3.2.3</management-center>

	<network>
		<port auto-increment="true" port-count="100">7777</port>
		<outbound-ports>
			
			<ports>0</ports>
		</outbound-ports>

		<join>
			<multicast enabled="false" />
			<tcp-ip enabled="true">
				<interface>XX.XX.X.XXX</interface>
				<interface>XX.XX.X.XXX</interface>
                                <interface>XX.XX.X.XXX</interface>
                                <interface>XX.XX.X.XXX</interface>
                                <interface>XX.XX.X.XXX</interface>
				<interface>XX.XX.X.XXX</interface>
                                <interface>XX.XX.X.XXX</interface>
                                <interface>XX.XX.X.XXX</interface>
			</tcp-ip>
		</join>

	</network>

  

	<partition-group enabled="true" group-type="HOST_AWARE">
	</partition-group>

	<merge-policy>hz.ADD_NEW_ENTRY</merge-policy>

	<services enable-defaults="true" />

         <queue name="offerpooleventQ">
             <backup-count>1</backup-count>
              <async-backup-count>0</async-backup-count>
               <empty-queue-ttl>-1</empty-queue-ttl>
               <max-size>10000</max-size>
    </queue>
                   
</hazelcast>

**Comment by jerrinot** [comment]
Hello,

This is a known issue in Hazelcast 3.2.3. See this: https://github.com/hazelcast/hazelcast/pull/3207

I'd recommend you to upgrade to the latest version of Hazelcast - it has significantly better performance, contains tons of bugfixes and has new features as well. 

If you can't upgrade to Hazelcast 3.5.x for any reason then I'd strongly recommend to upgrade to the latest 3.2.x release - it's 3.2.7 at this moment.

**Comment by jerrinot** [comment]
I'm closing this ticket as it's a known issue which which was fixed a long time ago. Feel free to re-open it if you manage to reproduce it even

**Comment by jatingupta12** [comment]
Thanks a lot.

**Comment by jerrinot** [comment]
@jatingupta12: You are very welcome. Happy Hazelcasting! :)

**Comment by bwzhang2011** [comment]
@jerrinot, please  take a look at #4809, it still has the same issue under hz3.5.4.
