### ISSUE TITLE
[TEST-FAILURE] ClientExecutionPoolSizeLowTest.testOwnerNodeTerminateWithAsyncOperations & testOwnerNodeTerminateWithAsyncOperations

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#6253]
```
java.lang.AssertionError: the size of the map is not correct expected:<1000> but was:<999>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.test.HazelcastTestSupport$7.run(HazelcastTestSupport.java:623)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:737)
	at com.hazelcast.test.HazelcastTestSupport.assertSizeEventually(HazelcastTestSupport.java:620)
	at com.hazelcast.test.HazelcastTestSupport.assertSizeEventually(HazelcastTestSupport.java:616)
	at com.hazelcast.client.io.ClientExecutionPoolSizeLowTest.testOwnerNodeTerminateWithAsyncOperations(ClientExecutionPoolSizeLowTest.java:93)
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-nightly/com.hazelcast$hazelcast-client/608/testReport/junit/com.hazelcast.client.io/ClientExecutionPoolSizeLowTest/testOwnerNodeTerminateWithAsyncOperations/

**Comment by hasancelik** [comment]
**testOwnerNodeTerminateWithAsyncOperations**
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-nightly/609/

Also:
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-nightly/610/
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-nightly/611/

**Comment by hasancelik** [comment]
**3.x-nightly**

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast-client/714/testReport/junit/com.hazelcast.client.io/ClientExecutionPoolSizeLowTest/testNodeTerminateWithAsyncOperations/
