### ISSUE TITLE
[TEST-FAILURE] tcp.nonblocking.SelectNow_TcpIpConnection_BasicTest.lastWriteTimeMillis_whenPacketWritten

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#6254]
```
java.lang.AssertionError: nowMs = 1442546093972 lastReadTimeMs:1442546092959
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.nio.tcp.TcpIpConnection_BasicTest.lastWriteTimeMillis_whenPacketWritten(TcpIpConnection_BasicTest.java:108)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:60)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:37)
	at java.lang.reflect.Method.invoke(Method.java:611)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:134)
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.6/com.hazelcast$hazelcast/684/testReport/junit/com.hazelcast.nio.tcp.nonblocking/SelectNow_TcpIpConnection_BasicTest/lastWriteTimeMillis_whenPacketWritten/

**Comment by mdogan** [comment]
very similar to https://github.com/hazelcast/hazelcast/issues/6233

**Comment by Donnerbart** [comment]
It's all the same base class. Will close this as duplicate.
