### ISSUE TITLE
[TEST-FAILURE] AbstractCompletableFutureTest.getWithTimeout_exceptionResultSet_exceptionThrown_noTimeout

### ISSUE THREAD

**Issue by Donnerbart** [hazelcast/hazelcast#6290]
**Regression**
`com.hazelcast.spi.impl.AbstractCompletableFutureTest.getWithTimeout_exceptionResultSet_exceptionThrown_noTimeout`

Failing for the past 1 build (Since Unstable#3781 )
Took 12 ms.

**Error Message**
```
Expected: (an instance of java.lang.RuntimeException and exception with message a string containing "You screwed buddy!")
     but: exception with message a string containing "You screwed buddy!" message was null
Stacktrace was: java.lang.NullPointerException
 at java.lang.management.ThreadInfo.<init>(ThreadInfo.java:168)
 at sun.management.ThreadImpl.dumpThreads0(Native Method)
 at sun.management.ThreadImpl.dumpAllThreads(ThreadImpl.java:446)
 at com.hazelcast.test.AbstractHazelcastClassRunner.generateThreadDump(AbstractHazelcastClassRunner.java:228)
 at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:139)
 at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
 at org.junit.rules.RunRules.evaluate(RunRules.java:20)
 at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
 at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
 at com.hazelcast.test.HazelcastParallelClassRunner.access$301(HazelcastParallelClassRunner.java:47)
 at com.hazelcast.test.HazelcastParallelClassRunner$TestRunner.run(HazelcastParallelClassRunner.java:144)
 at java.lang.Thread.run(Thread.java:745)
```

**Stacktrace**
```
java.lang.AssertionError: 
Expected: (an instance of java.lang.RuntimeException and exception with message a string containing "You screwed buddy!")
     but: exception with message a string containing "You screwed buddy!" message was null
Stacktrace was: java.lang.NullPointerException
	at java.lang.management.ThreadInfo.<init>(ThreadInfo.java:168)
	at sun.management.ThreadImpl.dumpThreads0(Native Method)
	at sun.management.ThreadImpl.dumpAllThreads(ThreadImpl.java:446)
	at com.hazelcast.test.AbstractHazelcastClassRunner.generateThreadDump(AbstractHazelcastClassRunner.java:228)
	at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:139)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at com.hazelcast.test.HazelcastParallelClassRunner.access$301(HazelcastParallelClassRunner.java:47)
	at com.hazelcast.test.HazelcastParallelClassRunner$TestRunner.run(HazelcastParallelClassRunner.java:144)
	at java.lang.Thread.run(Thread.java:745)

	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.junit.rules.ExpectedException.handleException(ExpectedException.java:252)
	at org.junit.rules.ExpectedException.access$000(ExpectedException.java:106)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:241)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at com.hazelcast.test.HazelcastParallelClassRunner.access$301(HazelcastParallelClassRunner.java:47)
	at com.hazelcast.test.HazelcastParallelClassRunner$TestRunner.run(HazelcastParallelClassRunner.java:144)
	at java.lang.Thread.run(Thread.java:745)
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x/com.hazelcast$hazelcast/3781/testReport/junit/com.hazelcast.spi.impl/AbstractCompletableFutureTest/getWithTimeout_exceptionResultSet_exceptionThrown_noTimeout/

**Comment by serkan-ozal** [comment]
Similar to this issue #6291 
See my comments https://github.com/hazelcast/hazelcast/issues/6291#issuecomment-143798098

**Comment by serkan-ozal** [comment]
Closing with same reason mentioned in this comment https://github.com/hazelcast/hazelcast/issues/6291#issuecomment-145875448
