### ISSUE TITLE
getBackupProcessor called 270 times per executeOnEntries invocation

### ISSUE THREAD

**Issue by wimdeblauwe** [hazelcast/hazelcast#6306]
When doing tests with `EntryProcessor` and `EntryBackupProcessor` i noticed that `getBackupProcessor` gets called many times when using `executeOnEntries` method.

Test Program:
```
package test;

import com.hazelcast.config.Config;
import com.hazelcast.core.Hazelcast;
import com.hazelcast.core.HazelcastInstance;
import com.hazelcast.core.ILock;
import com.hazelcast.core.IMap;
import com.hazelcast.map.EntryBackupProcessor;
import com.hazelcast.map.EntryProcessor;

import java.util.Map;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.stream.IntStream;

public class BEPExecuteOnEntriesTest
{
	public static void main( String[] args ) throws InterruptedException
	{
		Config config = new Config();
		config.setProperty("hazelcast.initial.min.cluster.size","2");
		HazelcastInstance hazelcastInstance = Hazelcast.newHazelcastInstance( config );

		// Take a lock so only 1 of the 2 nodes will execute the entry processor
		ILock doItLock = hazelcastInstance.getLock( "doItLock" );
		doItLock.lock();

		IMap<Long, User> testMap;
		try
		{
			testMap = hazelcastInstance.getMap( "testMap" );
			if( !testMap.containsKey( 1L ))
			{

				IntStream.rangeClosed( 1, 10 ).mapToObj( i -> {
					User user = new User();
					user.setId( i );
					user.setName( "Wim" + i );
					return user;
				}  ).forEach( user -> testMap.put( user.getId(), user ) );

				System.out.println( "Calling the entry processor" );
				testMap.executeOnEntries( new MyEntryProcessor() );
			}
		}
		finally
		{
			doItLock.unlock();
		}
	}

	private static class MyEntryProcessor implements EntryProcessor<Long,User>
	{
		private static AtomicInteger counter = new AtomicInteger();

		public MyEntryProcessor()
		{
		}

		@Override
		public Object process( Map.Entry<Long,User> entry )
		{
			System.out.println("Processing entry: " + entry );
			return null;
		}

		@Override
		public EntryBackupProcessor<Long,User> getBackupProcessor()
		{
			System.out.println("Asking backup processor - count = " + counter.incrementAndGet());
			return new EntryBackupProcessor<Long, User>()
			{
				@Override
				public void processBackup( Map.Entry<Long, User> entry )
				{
					System.out.println( "Processing backup entry: " + entry );

				}
			};
		}
	}
}
```

You also need the class User:
```
class User implements Serializable
{
	private long id;
	private String name;
	private DateTime lastLoginTime;

	public long getId()	{
		return id;
	}

	public void setId( long id )	{
		this.id = id;
	}

	public String getName()	{
		return name;
	}

	public void setName( String name )	{
		this.name = name;
	}

	public DateTime getLastLoginTime()	{
		return lastLoginTime;
	}

	public void setLastLoginTime( DateTime lastLoginTime )	{
		this.lastLoginTime = lastLoginTime;
	}

	@Override
	public String toString()	{
		return MoreObjects.toStringHelper( this )
				.add( "id", id )
				.add( "name", name )
				.add( "lastLoginTime", lastLoginTime )
				.toString();
	}
}
```
To test it, just start the program 2 times to get 2 nodes. The output will show something like this:

```
Calling the entry processor
Asking backup processor - count = 1
Asking backup processor - count = 6
Asking backup processor - count = 5
Asking backup processor - count = 2
Asking backup processor - count = 4
Asking backup processor - count = 3
Asking backup processor - count = 7
Asking backup processor - count = 10
Asking backup processor - count = 11
Asking backup processor - count = 13
 
...

Asking backup processor - count = 266
Asking backup processor - count = 267
Asking backup processor - count = 268
Asking backup processor - count = 269
Asking backup processor - count = 270
```

Note that the overloaded method that uses a Predicate thas the same behaviour. The number of entries in the map does not seem to matter.
On the other hand, if you call the entry processor by using `executeOnKey` or `executeOnKeys`, then the backup processor is called 2 times the number of keys you pass in.

Using a debugger, I have noticed that all stacktraces are similar to the following 2:

```
    "hz._hzInstance_1_dev.partition-operation.thread-5@1514" prio=5 tid=0x16 nid=NA waiting for monitor entry
      java.lang.Thread.State: BLOCKED
    	  at java.io.PrintStream.println(PrintStream.java:806)
    	  at test.BEPExecuteOnEntriesTest$MyProcessor.getBackupProcessor(BEPExecuteOnEntriesTest.java:116)
    	  at com.hazelcast.map.impl.operation.PartitionWideEntryOperation.shouldBackup(PartitionWideEntryOperation.java:98)
    	  at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.handleResponse(OperationRunnerImpl.java:184)
    	  at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:138)
    	  at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.processOperation(OperationThread.java:154)
    	  at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.process(OperationThread.java:110)
    	  at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.doRun(OperationThread.java:101)
    	  at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.run(OperationThread.java:76)
```
and
```
    "hz._hzInstance_1_dev.partition-operation.thread-4@1513" prio=5 tid=0x15 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at java.lang.System.arraycopy(System.java:-1)
	  at java.io.BufferedOutputStream.write(BufferedOutputStream.java:128)
	  - locked <0xde3> (a java.io.BufferedOutputStream)
	  at java.io.PrintStream.write(PrintStream.java:480)
	  - locked <0xdd4> (a java.io.PrintStream)
	  at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
	  at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:291)
	  at sun.nio.cs.StreamEncoder.flushBuffer(StreamEncoder.java:104)
	  - locked <0xde4> (a java.io.OutputStreamWriter)
	  at java.io.OutputStreamWriter.flushBuffer(OutputStreamWriter.java:185)
	  at java.io.PrintStream.write(PrintStream.java:527)
	  at java.io.PrintStream.print(PrintStream.java:669)
	  at java.io.PrintStream.println(PrintStream.java:806)
	  at test.BEPExecuteOnEntriesTest$MyEntryProcessor.getBackupProcessor(BEPExecuteOnEntriesTest.java:116)
	  at com.hazelcast.map.impl.operation.PartitionWideEntryWithPredicateOperation.getBackupOperation(PartitionWideEntryWithPredicateOperation.java:46)
	  at com.hazelcast.spi.impl.operationservice.impl.OperationBackupHandler.newBackupOperation(OperationBackupHandler.java:192)
	  at com.hazelcast.spi.impl.operationservice.impl.OperationBackupHandler.newBackup(OperationBackupHandler.java:178)
	  at com.hazelcast.spi.impl.operationservice.impl.OperationBackupHandler.makeBackups(OperationBackupHandler.java:164)
	  at com.hazelcast.spi.impl.operationservice.impl.OperationBackupHandler.backup(OperationBackupHandler.java:74)
	  at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.handleResponse(OperationRunnerImpl.java:185)
	  at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:138)
	  at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.processOperation(OperationThread.java:154)
	  at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.process(OperationThread.java:110)
	  at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.doRun(OperationThread.java:101)
	  at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.run(OperationThread.java:76)
```

It should be avoided that a new object is created, just to know if there is a backup processor or not. This would already half the object creations, especially when Hazelcast creates the backup processor 270 times just for 1 invocation of `executeOnEntries`.

**Comment by pveentjer** [comment]
Which HZ version are you using?

**Comment by wimdeblauwe** [comment]
Hazelcast 3.5.2

**Comment by pveentjer** [comment]
I guess that it is copied to every partition and by default there are 271 partitions. @ahmetmircik is this intended design?

**Comment by gurbuzali** [comment]
This is the expected behavior, `getBackupProcessor` will be called for each partition
