### ISSUE TITLE
MemberListTest.testSwitchingMasters

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#6326]
```
java.lang.AssertionError: expected:<4> but was:<7>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.cluster.MemberListTest.testSwitchingMasters(MemberListTest.java:246)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/723/testReport/junit/com.hazelcast.cluster/MemberListTest/testSwitchingMasters/

**Comment by mdogan** [comment]
I think this failure is not related to test itself. Hazelcast is not able to bind the socket:

```
java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:444)
	at sun.nio.ch.Net.bind(Net.java:436)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:214)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at com.hazelcast.instance.DefaultAddressPicker.getPublicAddressByPortSearch(DefaultAddressPicker.java:122)
	at com.hazelcast.instance.DefaultAddressPicker.pickAddress(DefaultAddressPicker.java:74)
	at com.hazelcast.instance.Node.<init>(Node.java:151)
	at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:125)
	at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:161)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:144)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:112)
	at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:58)
	at com.hazelcast.cluster.MemberListTest.buildInstances(MemberListTest.java:275)
	at com.hazelcast.cluster.MemberListTest.testSwitchingMasters(MemberListTest.java:222)
```

**Comment by hasancelik** [comment]
@mdogan I think you are right but i prefer to wait for another failure, if it does not happen again next couple of days, I will close this issue. Or I can close now?

**Comment by mdogan** [comment]
whenever you wish :)

**Comment by eminn** [comment]
Not failing recently...

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: expected:<5> but was:<7>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.cluster.MemberListTest.testSwitchingMasters(MemberListTest.java:229)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-nightly/com.hazelcast$hazelcast/743/testReport/junit/com.hazelcast.cluster/MemberListTest/testSwitchingMasters/

**Comment by mdogan** [comment]
I think this failure is caused by environment. 
- 3rd node is not able to bind port `55703` and fails to start. 
- Then subsequent nodes cannot join to the initial two nodes and start their own 5 node cluster. 
- Then initial two nodes detect the new cluster and they merge and form a 7 node cluster.

>23:28:52,103 ERROR |testSwitchingMasters| - [DefaultAddressPicker] testSwitchingMasters - [LOCAL] [group] [3.6.1-SNAPSHOT] Port [55703] is already in use and auto-increment is disabled. Hazelcast cannot start.
java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)

Full log is not available, since it's truncated somewhere between:

>23:28:58,147  INFO |testSwitchingMasters| - [DefaultAddressPicker] testSwitch
...[truncated 95467 chars]...
-1 - [127.0.0.1]:55701 [group] [3.6.1-SNAPSHOT] Setting cluster time diff to 0ms.
