### ISSUE TITLE
[TEST-FAILURE] ReplicatedMapLiteMemberTest.testLiteMembersWithZeroReplicationDelay

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#6340]
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.replicatedmap.ReplicatedMapLiteMemberTest$2.run(ReplicatedMapLiteMemberTest.java:100)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:833)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:847)
	at com.hazelcast.replicatedmap.ReplicatedMapLiteMemberTest.testNoReplicationToLiteMember(ReplicatedMapLiteMemberTest.java:96)
	at com.hazelcast.replicatedmap.ReplicatedMapLiteMemberTest.testLiteMembersWithZeroReplicationDelay(ReplicatedMapLiteMemberTest.java:66)
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.6/com.hazelcast$hazelcast/698/testReport/junit/com.hazelcast.replicatedmap/ReplicatedMapLiteMemberTest/testLiteMembersWithZeroReplicationDelay/

**Comment by eminn** [comment]
Fixed by #6176
