### ISSUE TITLE
[TEST-FAILURE] executor.SingleNodeTest.executionCallback_notifiedOnSuccess

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#6370]
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.executor.SingleNodeTest.executionCallback_notifiedOnSuccess(SingleNodeTest.java:108)
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast$hazelcast/723/testReport/junit/com.hazelcast.executor/SingleNodeTest/executionCallback_notifiedOnSuccess/

**Comment by eminn** [comment]
fixed via 6b546fc44c4f4b01e1158505ecdd2a13a9f33f89
