### ISSUE TITLE
[TEST-FAILURE] MapReduceLiteMemberTest.testMapReduceJobSubmissionWithNoDataNode

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#6371]
```
org.junit.runners.model.TestTimedOutException: test timed out after 60000 milliseconds
	at java.lang.Object.wait(Native Method)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.get(ClientInvocationFuture.java:120)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.get(ClientInvocationFuture.java:105)
	at com.hazelcast.client.spi.ProxyManager.initialize(ProxyManager.java:279)
	at com.hazelcast.client.spi.ProxyManager.initializeWithRetry(ProxyManager.java:236)
	at com.hazelcast.client.spi.ProxyManager.getOrCreateProxy(ProxyManager.java:217)
	at com.hazelcast.client.impl.HazelcastClientInstanceImpl.getDistributedObject(HazelcastClientInstanceImpl.java:489)
	at com.hazelcast.client.impl.HazelcastClientInstanceImpl.getJobTracker(HazelcastClientInstanceImpl.java:359)
	at com.hazelcast.client.impl.HazelcastClientProxy.getJobTracker(HazelcastClientProxy.java:128)
	at com.hazelcast.mapreduce.MapReduceLiteMemberTest.testMapReduceJobSubmissionWithNoDataNode(MapReduceLiteMemberTest.java:247)
	at com.hazelcast.client.mapreduce.MapReduceLiteMemberTest.testMapReduceJobSubmissionWithNoDataNode(MapReduceLiteMemberTest.java:117)

```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK8/com.hazelcast$hazelcast-client/709/testReport/junit/com.hazelcast.client.mapreduce/MapReduceLiteMemberTest/testMapReduceJobSubmissionWithNoDataNode/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OracleJDK8/com.hazelcast$hazelcast-client-new/576/testReport/junit/com.hazelcast.client.mapreduce/MapReduceLiteMemberTest/testMapReduceJobSubmissionWithNoDataNode/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OracleJDK8/com.hazelcast$hazelcast-client-new/578/testReport/junit/com.hazelcast.client.mapreduce/MapReduceLiteMemberTest/testMapReduceJobSubmissionWithNoDataNode/

**Comment by Donnerbart** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-pr-builder/com.hazelcast%24hazelcast-client-new/15851/testReport/junit/com.hazelcast.client.mapreduce/MapReduceLiteMemberTest/testMapReduceJobSubmissionWithNoDataNode/

**Comment by metanet** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OracleJDK1.6/com.hazelcast$hazelcast-client-new/687/testReport/junit/com.hazelcast.client.mapreduce/MapReduceLiteMemberTest/testMapReduceJobSubmissionWithNoDataNode/

**Comment by mdogan** [comment]
@metanet:
Is this a similar issue?

```
testMapReduceJobSubmissionWithNoDataNode(com.hazelcast.client.mapreduce.MapReduceLiteMemberTest)  Time elapsed: 154.011 sec  <<< ERROR!
22:40:01 org.junit.runners.model.TestTimedOutException: test timed out after 60000 milliseconds
22:40:01    at java.lang.Thread.sleep(Native Method)
22:40:01    at com.hazelcast.client.spi.ProxyManager.sleepForProxyInitRetry(ProxyManager.java:264)
22:40:01    at com.hazelcast.client.spi.ProxyManager.initializeWithRetry(ProxyManager.java:241)
22:40:01    at com.hazelcast.client.spi.ProxyManager.getOrCreateProxy(ProxyManager.java:212)
22:40:01    at com.hazelcast.client.impl.HazelcastClientInstanceImpl.getDistributedObject(HazelcastClientInstanceImpl.java:492)
22:40:01    at com.hazelcast.client.impl.HazelcastClientInstanceImpl.getJobTracker(HazelcastClientInstanceImpl.java:355)
22:40:01    at com.hazelcast.client.impl.HazelcastClientProxy.getJobTracker(HazelcastClientProxy.java:128)
22:40:01    at com.hazelcast.mapreduce.MapReduceLiteMemberTest.testMapReduceJobSubmissionWithNoDataNode(MapReduceLiteMemberTest.java:247)
22:40:01    at com.hazelcast.client.mapreduce.MapReduceLiteMemberTest.testMapReduceJobSubmissionWithNoDataNode(MapReduceLiteMemberTest.java:99)
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-pr-builder/15972/com.hazelcast$hazelcast-client-new/testReport/com.hazelcast.client.mapreduce/MapReduceLiteMemberTest/testMapReduceJobSubmissionWithNoDataNode/

**Comment by metanet** [comment]
A fix about this test failure was merged yesterday. Apparently, there are some other problems that I couldn't see. I am investigating it.

**Comment by hasancelik** [comment]
```
org.junit.runners.model.TestTimedOutException: test timed out after 60000 milliseconds
	at java.lang.Object.wait(Native Method)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.get(ClientInvocationFuture.java:90)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.get(ClientInvocationFuture.java:75)
	at com.hazelcast.client.spi.ProxyManager.initialize(ProxyManager.java:284)
	at com.hazelcast.client.spi.ProxyManager.initializeWithRetry(ProxyManager.java:231)
	at com.hazelcast.client.spi.ProxyManager.getOrCreateProxy(ProxyManager.java:212)
	at com.hazelcast.client.impl.HazelcastClientInstanceImpl.getDistributedObject(HazelcastClientInstanceImpl.j
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK7/com.hazelcast$hazelcast-client-new/685/testReport/junit/com.hazelcast.client.mapreduce/MapReduceLiteMemberTest/testMapReduceJobSubmissionWithNoDataNode/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OracleJDK1.6/com.hazelcast$hazelcast-client-new/694/testReport/junit/com.hazelcast.client.mapreduce/MapReduceLiteMemberTest/testMapReduceJobSubmissionWithNoDataNode/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x/com.hazelcast$hazelcast-client/3893/testReport/junit/com.hazelcast.client.mapreduce/MapReduceLiteMemberTest/testMapReduceJobSubmissionWithNoDataNode/

**Comment by hasancelik** [comment]
**After the fix**

```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OracleJDK1.6/com.hazelcast$hazelcast-client-new/697/testReport/junit/com.hazelcast.client.mapreduce/MapReduceLiteMemberTest/testMapReduceJobSubmissionWithNoDataNode/
```

**Changes:**
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OracleJDK1.6/com.hazelcast$hazelcast-client-new/697/changes
```

**Comment by hasancelik** [comment]
```
org.junit.runners.model.TestTimedOutException: test timed out after 120000 milliseconds
	at java.lang.Thread.sleep(Native Method)
	at com.hazelcast.client.spi.ProxyManager.sleepForProxyInitRetry(ProxyManager.java:288)
	at com.hazelcast.client.spi.ProxyManager.initializeWithRetry(ProxyManager.java:266)
	at com.hazelcast.client.spi.ProxyManager.getOrCreateProxy(ProxyManager.java:237)
	at com.hazelcast.client.impl.HazelcastClientInstanceImpl.getDistributedObject(HazelcastClientInstanceImpl.java:505)
	at com.hazelcast.client.impl.HazelcastClientInstanceImpl.getJobTracker(HazelcastClientInstanceImpl.java:368)
	at com.hazelcast.client.impl.HazelcastClientProxy.getJobTracker(HazelcastClientProxy.java:128)
	at com.hazelcast.mapreduce.MapReduceLiteMemberTest.testMapReduceJobSubmissionWithNoDataNode(MapReduceLiteMemberTest.java:247)
	at com.hazelcast.client.mapreduce.MapReduceLiteMemberTest.testMapReduceJobSubmissionWithNoDataNode(MapReduceLiteMemberTest.java:100)
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OracleJDK8/com.hazelcast$hazelcast-client/603/testReport/junit/com.hazelcast.client.mapreduce/MapReduceLiteMemberTest/testMapReduceJobSubmissionWithNoDataNode/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-ZuluJDK7/com.hazelcast$hazelcast-client-legacy/7/testReport/junit/com.hazelcast.client.mapreduce/MapReduceLiteMemberTest/testMapReduceJobSubmissionWithNoDataNode/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x/com.hazelcast$hazelcast-client-legacy/4001/testReport/junit/com.hazelcast.client.mapreduce/MapReduceLiteMemberTest/testMapReduceJobSubmissionWithNoDataNode/

**Comment by Donnerbart** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-pr-builder/com.hazelcast$hazelcast-client-legacy/17107/testReport/junit/com.hazelcast.client.mapreduce/MapReduceLiteMemberTest/testMapReduceJobSubmissionWithNoDataNode/

**Comment by sancar** [comment]
fixed by https://github.com/hazelcast/hazelcast/pull/6861

**Comment by hasancelik** [comment]
```
java.util.concurrent.RejectedExecutionException: Task com.hazelcast.client.impl.ClientEngineImpl$ClientPacketProcessor@5000167f rejected from ThreadPoolExecutor{name='hz:client'}
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369)
	at com.hazelcast.client.impl.ClientEngineImpl.handlePacket(ClientEngineImpl.java:177)
	at com.hazelcast.client.test.TestClientRegistry$MockedClientConnection.write(TestClientRegistry.java:175)
	at com.hazelcast.client.spi.impl.ClientInvocationServiceSupport.send(ClientInvocationServiceSupport.java:111)
	at com.hazelcast.client.spi.impl.ClientSmartInvocationServiceImpl.invokeOnConnection(ClientSmartInvocationServiceImpl.java:97)
	at com.hazelcast.client.spi.impl.ClientInvocation.invokeOnSelection(ClientInvocation.java:155)
	at com.hazelcast.client.spi.impl.ClientInvocation.invoke(ClientInvocation.java:145)
	at com.hazelcast.client.spi.ProxyManager.initialize(ProxyManager.java:281)
	at com.hazelcast.client.spi.ProxyManager.initializeWithRetry(ProxyManager.java:239)
	at com.hazelcast.client.spi.ProxyManager.getOrCreateProxy(ProxyManager.java:220)
	at com.hazelcast.client.impl.HazelcastClientInstanceImpl.getDistributedObject(HazelcastClientInstanceImpl.java:505)
	at com.hazelcast.client.impl.HazelcastClientInstanceImpl.getJobTracker(HazelcastClientInstanceImpl.java:375)
	at com.hazelcast.client.impl.HazelcastClientProxy.getJobTracker(HazelcastClientProxy.java:128)
	at com.hazelcast.mapreduce.MapReduceLiteMemberTest.testMapReduceJobSubmissionWithNoDataNode(MapReduceLiteMemberTest.java:248)
	at com.hazelcast.client.mapreduce.MapReduceLiteMemberTest.testMapReduceJobSubmissionWithNoDataNode(MapReduceLiteMemberTest.java:102)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK8/com.hazelcast$hazelcast-client-legacy/641/testReport/junit/com.hazelcast.client.mapreduce/MapReduceLiteMemberTest/testMapReduceJobSubmissionWithNoDataNode/
