### ISSUE TITLE
[TEST-FAILURE] InternalPartitionServiceLiteMemberTest.test_getPartitionOwnerOrWait_onLiteMemberAfterDataMemberShutsDown

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#6372]
```
java.lang.Exception: Unexpected exception, expected<com.hazelcast.partition.NoDataMemberInClusterException> but was<junit.framework.AssertionFailedError>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.assertTrue(Assert.java:22)
	at junit.framework.Assert.assertNull(Assert.java:277)
	at junit.framework.Assert.assertNull(Assert.java:268)
	at com.hazelcast.partition.impl.InternalPartitionServiceLiteMemberTest.test_getPartitionOwnerOrWait_onLiteMemberAfterDataMemberShutsDown(InternalPartitionServiceLiteMemberTest.java:219)

```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK8/com.hazelcast$hazelcast/710/testReport/junit/com.hazelcast.partition.impl/InternalPartitionServiceLiteMemberTest/test_getPartitionOwnerOrWait_onLiteMemberAfterDataMemberShutsDown/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK8-Quality-Outreach/com.hazelcast$hazelcast/199/testReport/junit/com.hazelcast.partition.impl/InternalPartitionServiceLiteMemberTest/test_getPartitionOwnerOrWait_onLiteMemberAfterDataMemberShutsDown/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK8-Quality-Outreach/200/com.hazelcast$hazelcast/testReport/com.hazelcast.partition.impl/InternalPartitionServiceLiteMemberTest/test_getPartitionOwnerOrWait_onLiteMemberAfterDataMemberShutsDown/

**Comment by hasancelik** [comment]
**test_memberGroupSize_afterDataMemberLeavesTheCluster**

```
java.lang.AssertionError: expected:<0> but was:<1>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.partition.impl.InternalPartitionServiceLiteMemberTest.assertMemberGroupsSize(InternalPartitionServiceLiteMemberTest.java:434)
	at com.hazelcast.partition.impl.InternalPartitionServiceLiteMemberTest.test_memberGroupSize_afterDataMemberLeavesTheCluster(InternalPartitionServiceLiteMemberTest.java:411)
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK9-Quality-Outreach/com.hazelcast$hazelcast/227/testReport/junit/com.hazelcast.partition.impl/InternalPartitionServiceLiteMemberTest/test_memberGroupSize_afterDataMemberLeavesTheCluster/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: Expected exception: com.hazelcast.partition.NoDataMemberInClusterException
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:32)
	at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:132)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at com.hazelcast.test.HazelcastParallelClassRunner.access$301(HazelcastParallelClassRunner.java:46)
	at com.hazelcast.test.HazelcastParallelClassRunner$TestRunner.run(HazelcastParallelClassRunner.java:139)
	at java.lang.Thread.run(Thread.java:662)
```


https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OracleJDK1.6/com.hazelcast$hazelcast/700/testReport/junit/com.hazelcast.partition.impl/InternalPartitionServiceLiteMemberTest/test_getPartitionOwnerOrWait_onLiteMemberAfterDataMemberShutsDown/

**Comment by hasancelik** [comment]
**test_liteMemberCanShutdownSafely_withClusterSize2**

```
org.junit.runners.model.TestTimedOutException: test timed out after 30000 milliseconds
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:503)
	at com.hazelcast.instance.HazelcastInstanceFactory$InstanceFuture.get(HazelcastInstanceFactory.java:299)
	at com.hazelcast.instance.HazelcastInstanceFactory.getInstanceImplMap(HazelcastInstanceFactory.java:262)
	at com.hazelcast.instance.NodeShutdownLatch.<init>(NodeShutdownLatch.java:48)
	at com.hazelcast.instance.LifecycleServiceImpl.shutdown(LifecycleServiceImpl.java:90)
	at com.hazelcast.partition.impl.InternalPartitionServiceLiteMemberTest.test_liteMemberCanShutdownSafely_withClusterSize2(InternalPartitionServiceLiteMemberTest.java:240)
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x/com.hazelcast$hazelcast/3926/testReport/junit/com.hazelcast.partition.impl/InternalPartitionServiceLiteMemberTest/test_liteMemberCanShutdownSafely_withClusterSize2/

**Comment by hasancelik** [comment]
**test_liteMemberCanShutdownSafely_whenDataMemberExistsInCluster**
**test_dataMemberCanTerminate_whenOnlyLiteMemberExistsInCluster**
**test_dataMemberCanShutdownSafely_whenOnlyLiteMemberExistsInCluster**
```
org.junit.runners.model.TestTimedOutException: test timed out after 30000 milliseconds
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at com.hazelcast.instance.HazelcastInstanceFactory$InstanceFuture.get(HazelcastInstanceFactory.java:299)
	at com.hazelcast.instance.HazelcastInstanceFactory.getInstanceImplMap(HazelcastInstanceFactory.java:262)
	at com.hazelcast.instance.NodeShutdownLatch.<init>(NodeShutdownLatch.java:48)
	at com.hazelcast.instance.LifecycleServiceImpl.shutdown(LifecycleServiceImpl.java:90)
	at com.hazelcast.partition.impl.InternalPartitionServiceLiteMemberTest.test_liteMemberCanShutdownSafely_whenDataMemberExistsInCluster(InternalPartitionServiceLiteMemberTest.java:270)
```
