### ISSUE TITLE
[TEST-FAILURE] ClientMapNearCacheTest.testNearCacheInvalidation_WithRandom_whenMaxSizeExceeded

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#6373]
```
java.lang.AssertionError: owned entry count 100
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.client.map.ClientMapNearCacheTest$10.run(ClientMapNearCacheTest.java:620)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:737)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:751)
	at com.hazelcast.client.map.ClientMapNearCacheTest.testNearCacheInvalidation_WithRandom_whenMaxSizeExceeded(ClientMapNearCacheTest.java:614)
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-OpenJDK8/com.hazelcast$hazelcast-client-new/298/testReport/junit/com.hazelcast.client.map/ClientMapNearCacheTest/testNearCacheInvalidation_WithRandom_whenMaxSizeExceeded/

**Comment by Donnerbart** [comment]
Should be at least improved via https://github.com/hazelcast/hazelcast/commit/2e6eaab1264598f3bbabe3789cf442ae437ccd7c
