### ISSUE TITLE
[TEST-FAILURE] MapNearCacheInvalidationFromClientTest Failures

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#6407]
```
java.lang.AssertionError: expected:<DefaultData{type=-7, hashCode=768969306, partitionHash=768969306, totalSize=9, dataSize=4, heapCost=29}> but was:<null>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.client.map.MapNearCacheInvalidationFromClientTest.testRemove(MapNearCacheInvalidationFromClientTest.java:208)
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x/lastCompletedBuild/com.hazelcast$hazelcast-client/testReport/com.hazelcast.client.map/MapNearCacheInvalidationFromClientTest/testRemove/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK9-Quality-Outreach/com.hazelcast$hazelcast-client-new/218/testReport/junit/com.hazelcast.client.map/MapNearCacheInvalidationFromClientTest/testRemove/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK9-Quality-Outreach/com.hazelcast$hazelcast-client/219/testReport/junit/com.hazelcast.client.map/MapNearCacheInvalidationFromClientTest/testRemove/

**Comment by hasancelik** [comment]
**MapNearCacheInvalidationFromClientTest.testUpdate**

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK8-Quality-Outreach/com.hazelcast$hazelcast-client/207/testReport/junit/com.hazelcast.client.map/MapNearCacheInvalidationFromClientTest/testUpdate/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK9-Quality-Outreach/220/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK8-Quality-Outreach/211/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK9-Quality-Outreach/com.hazelcast$hazelcast-client-new/226/testReport/junit/com.hazelcast.client.map/MapNearCacheInvalidationFromClientTest/testUpdate/

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK9-Quality-Outreach/com.hazelcast$hazelcast-client/227/testReport/junit/com.hazelcast.client.map/MapNearCacheInvalidationFromClientTest/testUpdate/

**Comment by mdogan** [comment]
Fixed by https://github.com/hazelcast/hazelcast/pull/6524

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: expected:<HeapData{type=-7, hashCode=768969306, partitionHash=768969306, totalSize=12, dataSize=4, heapCost=32}> but was:<null>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.client.map.MapNearCacheInvalidationFromClientTest.testRemove(MapNearCacheInvalidationFromClientTest.java:232)
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK8-Quality-Outreach/com.hazelcast$hazelcast-client-legacy/228/testReport/junit/com.hazelcast.client.map/MapNearCacheInvalidationFromClientTest/testRemove/

**Comment by metanet** [comment]
Closed by https://github.com/hazelcast/hazelcast/commit/89e869b74bc1ca35354cd2da111524cc10f9c141

**Comment by hasancelik** [comment]
**MapNearCacheInvalidationFromClientTest.testEvict**

```
java.lang.AssertionError: lite member near cache size should be less than 99 after evict but was 99
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.client.map.impl.nearcache.MapNearCacheInvalidationFromClientTest$3.run(MapNearCacheInvalidationFromClientTest.java:166)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:825)
	at com.hazelcast.client.map.impl.nearcache.MapNearCacheInvalidationFromClientTest.testEvict(MapNearCacheInvalidationFromClientTest.java:161)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/lab-fast-pr/143/testReport/junit/com.hazelcast.client.map.impl.nearcache/MapNearCacheInvalidationFromClientTest/testEvict/

**Comment by sancar** [comment]
My fix was wrong. Still working on it.
