### ISSUE TITLE
BackpressureRegulatorStressTest FAILURES

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#6426]
```
java.lang.AssertionError: No error should have been thrown, but StressThread-1 completed error expected null, but was:<com.hazelcast.core.HazelcastOverloadException: Failed to get a callId for invocation: Invocation{ serviceName='null', op=com.hazelcast.spi.impl.operationservice.impl.BackpressureRegulatorStressTest$DummyOperation{serviceName='null', partitionId=2, callId=0, invocationTime=1444514742108, waitTimeout=-1, callTimeout=60000}, partitionId=2, replicaIndex=0, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeout=60000, target=Address[127.0.0.1]:5702, backupsExpected=0, backupsCompleted=0, connection=Connection [/127.0.0.1:5701 -> /127.0.0.1:51353], endpoint=Address[127.0.0.1]:5702, alive=true, type=MEMBER}>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotNull(Assert.java:755)
    at org.junit.Assert.assertNull(Assert.java:737)
    at com.hazelcast.test.TestThread.assertSucceedsEventually(TestThread.java:62)
    at com.hazelcast.spi.impl.operationservice.impl.BackpressureRegulatorStressTest.test(BackpressureRegulatorStressTest.java:174)
    at com.hazelcast.spi.impl.operationservice.impl.BackpressureRegulatorStressTest.asyncInvocation(BackpressureRegulatorStressTest.java:74)
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/737/
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/736/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/738/#showFailuresLink

**Comment by hasancelik** [comment]
**BackpressureRegulatorStressTest.asyncInvocation
BackpressureRegulatorStressTest.asyncInvocation_and_asyncBackups
BackpressureRegulatorStressTest.asyncInvocation_and_syncBackups_and_asyncBackups
BackpressureRegulatorStressTest.syncInvocation_and_asyncBackups
BackpressureRegulatorStressTest.asyncInvocation_and_syncBackups**

```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.lang.Thread.sleep(Native Method)
	at java.lang.Thread.sleep(Thread.java:340)
	at java.util.concurrent.TimeUnit.sleep(TimeUnit.java:360)
	at com.hazelcast.test.HazelcastTestSupport.sleepSeconds(HazelcastTestSupport.java:262)
	at com.hazelcast.test.HazelcastTestSupport.sleepAndStop(HazelcastTestSupport.java:284)
	at com.hazelcast.spi.impl.operationservice.impl.BackpressureRegulatorStressTest.test(BackpressureRegulatorStressTest.java:172)
	at com.hazelcast.spi.impl.operationservice.impl.BackpressureRegulatorStressTest.asyncInvocation(BackpressureRegulatorStressTest.java:74)
```

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/804/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/806/#showFailuresLink

**Comment by hasancelik** [comment]
**BackpressureRegulatorStressTest.asyncInvocation_and_asyncBackups**
```
java.lang.AssertionError: No error should have been thrown, but StressThread-1 completed error expected null, but was:<java.lang.OutOfMemoryError: Java heap space>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotNull(Assert.java:755)
	at org.junit.Assert.assertNull(Assert.java:737)
	at com.hazelcast.test.TestThread.assertSucceedsEventually(TestThread.java:62)
	at com.hazelcast.spi.impl.operationservice.impl.BackpressureRegulatorStressTest.test(BackpressureRegulatorStressTest.java:173)
	at com.hazelcast.spi.impl.operationservice.impl.BackpressureRegulatorStressTest.asyncInvocation_and_asyncBackups(BackpressureRegulatorStressTest.java:111)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/1109/testReport/junit/com.hazelcast.spi.impl.operationservice.impl/BackpressureRegulatorStressTest/asyncInvocation_and_asyncBackups/

**Comment by hasancelik** [comment]
**BackpressureRegulatorStressTest.asyncInvocation_and_asyncBackups**
```
java.lang.AssertionError: No error should have been thrown, but StressThread-4 completed error expected null, but was:<java.lang.OutOfMemoryError: GC overhead limit exceeded>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotNull(Assert.java:755)
	at org.junit.Assert.assertNull(Assert.java:737)
	at com.hazelcast.test.TestThread.assertSucceedsEventually(TestThread.java:62)
	at com.hazelcast.spi.impl.operationservice.impl.BackpressureRegulatorStressTest.test(BackpressureRegulatorStressTest.java:173)
	at com.hazelcast.spi.impl.operationservice.impl.BackpressureRegulatorStressTest.asyncInvocation_and_asyncBackups(BackpressureRegulatorStressTest.java:111)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/1128/testReport/junit/com.hazelcast.spi.impl.operationservice.impl/BackpressureRegulatorStressTest/asyncInvocation_and_asyncBackups/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: No error should have been thrown, but StressThread-5 completed error expected null, but was:<java.lang.OutOfMemoryError: GC overhead limit exceeded>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotNull(Assert.java:755)
	at org.junit.Assert.assertNull(Assert.java:737)
	at com.hazelcast.test.TestThread.assertSucceedsEventually(TestThread.java:62)
	at com.hazelcast.spi.impl.operationservice.impl.BackpressureRegulatorStressTest.test(BackpressureRegulatorStressTest.java:173)
	at com.hazelcast.spi.impl.operationservice.impl.BackpressureRegulatorStressTest.asyncInvocation_and_asyncBackups(BackpressureRegulatorStressTest.java:111)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/1167/testReport/junit/com.hazelcast.spi.impl.operationservice.impl/BackpressureRegulatorStressTest/asyncInvocation_and_asyncBackups/

**Comment by hasancelik** [comment]
**BackpressureRegulatorStressTest.asyncInvocation_and_asyncBackups**
```
org.junit.runners.model.TestTimedOutException: test timed out after 600000 milliseconds
	at java.lang.Thread.sleep(Native Method)
	at java.lang.Thread.sleep(Thread.java:340)
	at java.util.concurrent.TimeUnit.sleep(TimeUnit.java:360)
	at com.hazelcast.test.HazelcastTestSupport.sleepSeconds(HazelcastTestSupport.java:305)
	at com.hazelcast.test.HazelcastTestSupport.sleepAndStop(HazelcastTestSupport.java:327)
	at com.hazelcast.spi.impl.operationservice.impl.BackpressureRegulatorStressTest.test(BackpressureRegulatorStressTest.java:171)
	at com.hazelcast.spi.impl.operationservice.impl.BackpressureRegulatorStressTest.asyncInvocation_and_asyncBackups(BackpressureRegulatorStressTest.java:111)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/1166/testReport/junit/com.hazelcast.spi.impl.operationservice.impl/BackpressureRegulatorStressTest/asyncInvocation_and_asyncBackups/

**Comment by jerrinot** [comment]
I can see
```
04:14:30,751  WARN |asyncInvocation_and_asyncBackups| - [InvocationMonitor] hz._hzInstance_1994_dev.InvocationMonitorThread - [127.0.0.1]:6805 [dev] [3.8-SNAPSHOT] MonitorInvocationsTask delayed 47176 ms`
[...]
04:14:32,245  WARN |asyncInvocation_and_asyncBackups| - [SlowOperationDetector] hz._hzInstance_1994_dev.SlowOperationDetectorThread - [127.0.0.1]:6805 [dev] [3.8-SNAPSHOT] Slow operation detected: com.hazelcast.nio.Packet
Hint: You can enable the logging of stacktraces with the following system property: -Dhazelcast.slow.operation.detector.stacktrace.logging.enabled
04:14:15,353  WARN |asyncInvocation_and_asyncBackups| - [InvocationMonitor] hz._hzInstance_1995_dev.InvocationMonitorThread - [127.0.0.1]:6806 [dev] [3.8-SNAPSHOT] MonitorInvocationsTask delayed 27814 ms
04:14:34,795  WARN |asyncInvocation_and_asyncBackups| - [InvocationMonitor] hz._hzInstance_1995_dev.InvocationMonitorThread - [127.0.0.1]:6806 [dev] [3.8-SNAPSHOT] MonitorInvocationsTask delayed 18442 ms
04:14:34,795  WARN |asyncInvocation_and_asyncBackups| - [InvocationMonitor] hz._hzInstance_1995_dev.InvocationMonitorThread - [127.0.0.1]:6806 [dev] [3.8-SNAPSHOT] BroadcastOperationControlTask delayed 33256 ms
04:14:32,244  WARN |asyncInvocation_and_asyncBackups| - [SlowOperationDetector] hz._hzInstance_1995_dev.SlowOperationDetectorThread - [127.0.0.1]:6806 [dev] [3.8-SNAPSHOT] Slow operation detected: com.hazelcast.spi.impl.operationservice.impl.BackpressureRegulatorStressTest$DummyOperation
Hint: You can enable the logging of stacktraces with the following system property: -Dhazelcast.slow.operation.detector.stacktrace.logging.enabled
 at: 8169
 at: 8170
04:14:36,718  INFO |asyncInvocation_and_asyncBackups| - [InvocationMonitor] hz._hzInstance_1994_dev.InvocationMonitorThread - [127.0.0.1]:6805 [dev] [3.8-SNAPSHOT] Invocations:255 timeouts:0 backup-timeouts:34
com.hazelcast.core.OperationTimeoutException: DummyOperation got rejected before execution due to not starting within the operation-call-timeout of: 60000 ms. Current time: 2016-12-11 04:14:38.504. Start time: 2016-12-11 04:13:17.571. Total elapsed time: 80933 ms. Invocation{op=com.hazelcast.spi.impl.operationservice.impl.BackpressureRegulatorStressTest$DummyOperation{serviceName='null', identityHash=2084261030, partitionId=6, replicaIndex=0, callId=-7959, invocationTime=1481422397571 (2016-12-11 04:13:17.571), waitTimeout=-1, callTimeout=60000}, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=60000, firstInvocationTimeMs=1481422397571, firstInvocationTime='2016-12-11 04:13:17.571', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 02:00:00.000', target=[127.0.0.1]:6806, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=MockConnection{localEndpoint=[127.0.0.1]:6805, remoteEndpoint=[127.0.0.1]:6806}}
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.newOperationTimeoutException(InvocationFuture.java:151)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:99)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run(AbstractInvocationFuture.java:243)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)
com.hazelcast.core.OperationTimeoutException: DummyOperation got rejected before execution due to not starting within the operation-call-timeout of: 60000 ms. Current time: 2016-12-11 04:14:38.505. Start time: 2016-12-11
[...]
```

**Comment by jerrinot** [comment]
hm, I can see there are 5,000+ operations. They appears to be backup operations. Payload of each operation is 100kB. `5,000 * 100kB = 500MB` -> this can cause GC pressure when running on Jenkins. 

Now the question is why there is 5000 in-flight backup operations. This is the test setting:
```java
                .setProperty(OPERATION_BACKUP_TIMEOUT_MILLIS.getName(), "60000")
                .setProperty(BACKPRESSURE_ENABLED.getName(), "true")
                .setProperty(BACKPRESSURE_SYNCWINDOW.getName(), "10")
                .setProperty(BACKPRESSURE_MAX_CONCURRENT_INVOCATIONS_PER_PARTITION.getName(), "2")
```

`271 * 2 * 10 = 5420` that's roughly the backup operation count. but it make little sense. as the DummyOperation always use the same partition.

**Comment by jerrinot** [comment]
there is also 542 - 543 invocations. how is that possible? we use just a single partition and we have `BACKPRESSURE_MAX_CONCURRENT_INVOCATIONS_PER_PARTITION` set to 2.
