### ISSUE TITLE
[TEST-FAILURE] CacheBackupTest.entrySuccessfullyRetrievedFromBackupWhenThereIsTwoSyncBackup

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#6436]
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertNotNull(Assert.java:712)
	at org.junit.Assert.assertNotNull(Assert.java:722)
	at com.hazelcast.cache.CacheBackupTest.checkSavedRecordOnBackup(CacheBackupTest.java:83)
	at com.hazelcast.cache.CacheBackupTest.entrySuccessfullyRetrievedFromBackup(CacheBackupTest.java:68)
	at com.hazelcast.cache.CacheBackupTest.entrySuccessfullyRetrievedFromBackupWhenThereIsTwoSyncBackup(CacheBackupTest.java:100)
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x/com.hazelcast$hazelcast/3868/testReport/junit/com.hazelcast.cache/CacheBackupTest/entrySuccessfullyRetrievedFromBackupWhenThereIsTwoSyncBackup/

**Comment by serkan-ozal** [comment]
should be fixed via https://github.com/hazelcast/hazelcast/commit/718e97998162cd4a44c673fc5b467f99787e8b1e
