### ISSUE TITLE
PassThroughCacheMergePolicy  name changed back compatibility issue  

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#6439]
com.hazelcast.cache.merge.PassThroughCacheMergePolicy
changed to
com.hazelcast.cache.impl.merge.policy.PassThroughCacheMergePolicy

causing a backward compatibility issue

```
FATAL 2015-10-13 02:05:28,255 [hz._hzInstance_1_group1.wan-21] com.hazelcast.cache.impl.merge.policy.CacheMergePolicyProvider$1: [10.0.0.84]:5701 [group1] [3.6-SNAPSHOT] com.hazelcast.cache.merge.PassThroughCacheMergePolicy
java.lang.ClassNotFoundException: com.hazelcast.cache.merge.PassThroughCacheMergePolicy
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    at com.hazelcast.nio.ClassLoaderUtil.tryLoadClass(ClassLoaderUtil.java:137)
    at com.hazelcast.nio.ClassLoaderUtil.loadClass(ClassLoaderUtil.java:115)
    at com.hazelcast.nio.ClassLoaderUtil.newInstance(ClassLoaderUtil.java:68)
    at com.hazelcast.cache.impl.merge.policy.CacheMergePolicyProvider$1.createNew(CacheMergePolicyProvider.java:44)
    at com.hazelcast.cache.impl.merge.policy.CacheMergePolicyProvider$1.createNew(CacheMergePolicyProvider.java:40)
    at com.hazelcast.util.ConcurrencyUtil.getOrPutIfAbsent(ConcurrencyUtil.java:51)
    at com.hazelcast.cache.impl.merge.policy.CacheMergePolicyProvider.getMergePolicy(CacheMergePolicyProvider.java:72)
    at com.hazelcast.cache.wan.CacheReplicationSupportingService.handleCacheUpdate(CacheReplicationSupportingService.java:119)
    at com.hazelcast.cache.wan.CacheReplicationSupportingService.onReplicationEvent(CacheReplicationSupportingService.java:74)
    at com.hazelcast.cache.EnterpriseCacheService.onReplicationEvent(EnterpriseCacheService.java:383)
    at com.hazelcast.enterprise.wan.EnterpriseWanReplicationService$WanEventStripedRunnable.run(EnterpriseWanReplicationService.java:158)
    at com.hazelcast.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:187)
    at com.hazelcast.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:171)
```

**Comment by Danny-Hazelcast** [comment]
causes the nightly wan replication test to fail

**Comment by emrahkocaman** [comment]
We'll move them to their original package.
