### ISSUE TITLE
ArrayList sublcass serialization issue

### ISSUE THREAD

**Issue by pveentjer** [hazelcast/hazelcast#6455]
The following example shows the problem:

```
public class Main  {

    public static void main(String[] args){
        HazelcastInstance hz = Hazelcast.newHazelcastInstance();
        IMap<String,Employees> map = hz.getMap("foo");
        map.put("1", new Employees());

        Employees employees = map.get("1");
        System.out.println(employees);
    }

    static class Employees extends ArrayList {

    }
}
```

The following exception is thrown:
```
Exception in thread "main" java.lang.ClassCastException: java.util.ArrayList cannot be cast to com.hazelcast.Main$Employees
	at com.hazelcast.Main.main(Main.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

For more information see:
http://stackoverflow.com/questions/33103491/need-for-custom-serializers-while-using-derivatives-of-arraylist-as-value-in-haz

**Comment by sancar** [comment]
@asimarslan Did we solved this problem with your last changes ? I remember some related parts. 

Note: @pveentjer Serialization is in client team responsibility, I have added CLIENT label to issue.

**Comment by asimarslan** [comment]
This is a more extended problem about class serializer search. I'll add a section in design doc in the latest serializer improvement

**Comment by pveentjer** [comment]
@asimarslan is there an update or should we move this to 3.7 ?
