### ISSUE TITLE
QueryIndexMigrationTest.testIndexCleanupOnMigration

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#6471]
```
org.junit.runners.model.TestTimedOutException: test timed out after 60000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:182)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:822)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:980)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1292)
	at java.util.concurrent.FutureTask$Sync.innerGet(FutureTask.java:229)
	at java.util.concurrent.FutureTask.get(FutureTask.java:94)
	at com.hazelcast.map.impl.query.QueryIndexMigrationTest.testIndexCleanupOnMigration(QueryIndexMigrationTest.java:185)

```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.6/com.hazelcast$hazelcast/712/testReport/junit/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration/

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK6/com.hazelcast$hazelcast/693/testReport/junit/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x/com.hazelcast$hazelcast/3894/testReport/junit/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration/

**Comment by sancar** [comment]
Failed in my pr 
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-pr-builder/16325/console

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x/com.hazelcast$hazelcast/3903/testReport/junit/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration/

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x/com.hazelcast$hazelcast/3905/testReport/junit/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK8/com.hazelcast$hazelcast/726/testReport/junit/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x/com.hazelcast$hazelcast/3907/testReport/junit/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration/

**Comment by ahmetmircik** [comment]
Fix attempt https://github.com/hazelcast/hazelcast/commit/7b508a9f3d81ff10b7805e8094dbb6f0ebba9d51

**Comment by hasancelik** [comment]
```
org.junit.runners.model.TestTimedOutException: test timed out after 60000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:176)
	at java.util.concurrent.FutureTask.awaitDone(FutureTask.java:430)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.hazelcast.map.impl.query.QueryIndexMigrationTest.testIndexCleanupOnMigration(QueryIndexMigrationTest.java:183)
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.8/10/com.hazelcast$hazelcast/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x/com.hazelcast$hazelcast/3968/testReport/junit/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-ZuluJDK8/com.hazelcast$hazelcast/8/testReport/junit/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-ZuluJDK7/com.hazelcast$hazelcast/12/testReport/junit/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK8-Quality-Outreach/com.hazelcast$hazelcast/235/testReport/junit/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration/

**Comment by Donnerbart** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-pr-builder/com.hazelcast$hazelcast/16830/testReport/junit/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration/

**Comment by Donnerbart** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-pr-builder/com.hazelcast$hazelcast/16836/testReport/junit/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-ZuluJDK6/com.hazelcast$hazelcast/22/testReport/junit/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK1.7/com.hazelcast$hazelcast/302/testReport/junit/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/view/Quality-Outreach/job/Hazelcast-3.x-OpenJDK9-Quality-Outreach/com.hazelcast$hazelcast/259/testReport/junit/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK1.6/com.hazelcast$hazelcast/733/testReport/junit/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration/

**Comment by jerrinot** [comment]
It's a race between query operations and join (finalization?). 
It's not particularly easy to reproduce it; I can increase likely-hood of the issue by:
1. decreasing generic partition thread count to 1
2. removing the sleep at https://github.com/jerrinot/hazelcast/blob/3a6371a4201d82e46592b4d56816f5d6487d05d7/hazelcast/src/test/java/com/hazelcast/map/impl/query/QueryIndexMigrationTest.java#L251 <--- this will increase chance of the clash.

Theory: 
Query operations are occupying generic thread(s) -> Cluster Join can't be finalized. However because join is not finalized then QueryPartitionOperation can't be executed(?). The joins eventually times out and cluster is unblocked: https://github.com/jerrinot/hazelcast/blob/a1851f7a8598745035f9b64eec43d93d4de5bd32/hazelcast/src/main/java/com/hazelcast/cluster/impl/ClusterJoinManager.java#L514 However the test timeout is just 1 minute -> test failure.

The test has timeout set to 1 minutes. I believe increasing its timeout is a sufficient workaround for now. Real solution could be introduciton of a dedicated threadpool for cluster management operations?

**Comment by hasancelik** [comment]
ignored by #6822

**Comment by hasancelik** [comment]
```
org.junit.runners.model.TestTimedOutException: test timed out after 60000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:156)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:811)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:969)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1281)
	at java.util.concurrent.FutureTask$Sync.innerGet(FutureTask.java:218)
	at java.util.concurrent.FutureTask.get(FutureTask.java:83)
	at com.hazelcast.map.impl.query.QueryIndexMigrationTest.testIndexCleanupOnMigration(QueryIndexMigrationTest.java:183)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x/com.hazelcast$hazelcast/5421/testReport/junit/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration/

**Comment by hasancelik** [comment]
```
org.junit.runners.model.TestTimedOutException: test timed out after 60000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:198)
	at java.util.concurrent.FutureTask.awaitDone(FutureTask.java:437)
	at java.util.concurrent.FutureTask.get(FutureTask.java:199)
	at com.hazelcast.map.impl.query.QueryIndexMigrationTest.testIndexCleanupOnMigration(QueryIndexMigrationTest.java:183)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast$hazelcast/969/testReport/junit/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration/

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-ZuluJDK8/com.hazelcast$hazelcast/264/testReport/junit/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration/

**Comment by vbekiaris** [comment]
Can we obtain `TEST-com.hazelcast.map.impl.query.QueryIndexMigrationTest.xml` files from the respective `hazelcast/target/surefire-reports` folders to see if there's any further info in there?

**Comment by vbekiaris** [comment]
Another kind of assertion error may be also thrown after several repetitions of the test:
```
testIndexCleanupOnMigration(com.hazelcast.map.impl.query.QueryIndexMigrationTest)  Time elapsed: 4,624.701 sec  <<< ERROR!
java.util.concurrent.ExecutionException: java.lang.AssertionError: expected:<1> but was:<2>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:631)
        at com.hazelcast.map.impl.query.QueryIndexMigrationTest.updateMapAndRunQuery(QueryIndexMigrationTest.java:253)
        at com.hazelcast.map.impl.query.QueryIndexMigrationTest.access$100(QueryIndexMigrationTest.java:64)
```

**Comment by Donnerbart** [comment]
Failed again in the ZuluJDK6 build:
```
org.junit.runners.model.TestTimedOutException: test timed out after 60000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:838)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:998)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
	at java.util.concurrent.FutureTask$Sync.innerGet(FutureTask.java:248)
	at java.util.concurrent.FutureTask.get(FutureTask.java:111)
	at com.hazelcast.map.impl.query.QueryIndexMigrationTest.testIndexCleanupOnMigration(QueryIndexMigrationTest.java:183)
```
https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-ZuluJDK6/lastCompletedBuild/com.hazelcast$hazelcast/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration/

**Comment by ahmetmircik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/3892/

java.lang.AssertionError: expected:<1> but was:<2>
Stacktrace

java.util.concurrent.ExecutionException: java.lang.AssertionError: expected:<1> but was:<2>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:834)
    at org.junit.Assert.assertEquals(Assert.java:645)
    at org.junit.Assert.assertEquals(Assert.java:631)
    at com.hazelcast.map.impl.query.QueryIndexMigrationTest.updateMapAndRunQuery(QueryIndexMigrationTest.java:251)
    at com.hazelcast.map.impl.query.QueryIndexMigrationTest.access$100(QueryIndexMigrationTest.java:63)```

**Comment by vbekiaris** [comment]
`java.lang.AssertionError: expected:<1> but was:<2>` failure mode:

* A member executing `IMap.values(Predicate)` dispatches `QueryOperation`s on all members of the cluster
* Some members execute the query and respond with results for a set of partitions `A`
* Migrations occur
* Other members execute the query and respond with results for a set of partitions `B`
* (other `QueryPartitionOperation`s may be also executed but these are irrelevant for this case)
* Results are aggregated on the original member (https://github.com/hazelcast/hazelcast/blob/d2da655a71ba12db743066c33be55f74412c7dc2/hazelcast/src/main/java/com/hazelcast/map/impl/query/MapQueryEngineImpl.java#L543-L557).
* If set `A` & `B` have a non-empty intersection (due to ownership of partitions having been migrated from members who have already responded before the migration to nodes who respond after the migration), then results for some partitions will be included in the results twice.

I think that this problem started manifesting (more frequently) after #8403 was merged (which fixed a case in which query results were omitted if indexes were being rebuilt during migration at the time of query).

Considering two solutions:
* On the result aggregation side, if the results being added report a partition ID which is not found in the collection of pending partition IDs, this indicates we are about to insert twice results for a partition, so instead discard the whole result set. This is implemented in #8570.
  - Pros: simple, isolated fix. The new code will only get executed when migrations are taking place and not interfere with happy-path execution
  - Cons: when double partition result counting is detected, a whole member's results will be discarded as there is currently no way to know which result came from which partition and selectively discard only these. The missing partitions' results will be retrieved using one `QueryPartitionOperation` per partition which performs a full partition scan.
* On the member querying-side, add an `int[] partitionIds` parameter so that the member that dispatches the `QueryOperation`s asks members for results from specific partition IDs; since the requested partition IDs are determined from the partition state as observed by the dispatcher-member at the beginning of query, there can be no duplicates. Members who perform migrations in-between will report results for the intersection of (owned partition IDs, requested-for partition IDs), so in worst case a few more `QueryPartitionOperation`s will be executed to cater for results missing from specific partition IDs. This is implemented (not fully) in #8569.
  - Pros: still allows using indexes to obtain results from members, does not waste all of a members' results in case of migration
  - Cons: since indexes are not per-partition, we need to iterate over indexed query results and filter per partition ID. Affects code execution in stable cluster, not just during migrations.

**Comment by vbekiaris** [comment]
The `TimeoutException` reported above seems to be legit, the test takes 35 seconds on my laptop without any other load. Given that the tests are executed in a loaded build environment, I would remove the 1 minute timeout

**Comment by vbekiaris** [comment]
Closed via #8570 , thanks @tombujok for the help analyzing this issue.

**Comment by hasancelik** [comment]
```
java.util.concurrent.ExecutionException: java.lang.AssertionError: expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.map.impl.query.QueryIndexMigrationTest.updateMapAndRunQuery(QueryIndexMigrationTest.java:251)
	at com.hazelcast.map.impl.query.QueryIndexMigrationTest.access$100(QueryIndexMigrationTest.java:63)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast$hazelcast/981/testReport/junit/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration/

**Comment by vbekiaris** [comment]
The second failure on Oracle JDK1.6 is a timeout in 1 minute which occurred on July 22nd, before having extended the test timeout to 2 minutes with https://github.com/hazelcast/hazelcast/commit/7eda24207ff408091ba686e959612f514fb610a6:
```
org.junit.runners.model.TestTimedOutException: test timed out after 60000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:156)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:811)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:969)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1281)
	at java.util.concurrent.FutureTask$Sync.innerGet(FutureTask.java:218)
	at java.util.concurrent.FutureTask.get(FutureTask.java:83)
	at com.hazelcast.map.impl.query.QueryIndexMigrationTest.testIndexCleanupOnMigration(QueryIndexMigrationTest.java:183)
```

**Comment by hasancelik** [comment]
```
org.junit.runners.model.TestTimedOutException: test timed out after 120000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:156)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:811)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:969)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1281)
	at java.util.concurrent.FutureTask$Sync.innerGet(FutureTask.java:218)
	at java.util.concurrent.FutureTask.get(FutureTask.java:83)
	at com.hazelcast.map.impl.query.QueryIndexMigrationTest.testIndexCleanupOnMigration(QueryIndexMigrationTest.java:183)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-OracleJDK1.6/com.hazelcast$hazelcast/985/testReport/junit/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: expected:<30> but was:<29>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.map.impl.query.QueryIndexMigrationTest.testQueryWithIndexesWhileMigrating(QueryIndexMigrationTest.java:156)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-ZuluJDK7/com.hazelcast$hazelcast/276/testReport/junit/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testQueryWithIndexesWhileMigrating/
