### ISSUE TITLE
[TEST-FAILURE] BasicClusterStateTest.changeClusterState_toPassive_isAllowed_whileReplicationInProgress

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#6479]
```
com.hazelcast.core.HazelcastException: java.util.concurrent.TimeoutException: Call Invocation{ serviceName='hz:core:clusterService', op=com.hazelcast.cluster.impl.operations.LockClusterStateOperation{serviceName='hz:core:clusterService', partitionId=-1, replicaIndex=0, callId=0, invocationTime=1444961451906 (Fri Oct 16 05:10:51 EEST 2015), waitTimeout=-1, callTimeout=60000}, partitionId=-1, replicaIndex=0, tryCount=250, tryPauseMillis=500, invokeCount=122, callTimeout=60000, target=Address[127.0.0.1]:9153, backupsExpected=0, backupsCompleted=0, connection=MockConnection{localEndpoint=Address[127.0.0.1]:9155, remoteEndpoint=Address[127.0.0.1]:9153}} encountered a timeout
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveApplicationResponse(InvocationFuture.java:367)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveApplicationResponseOrThrowException(InvocationFuture.java:335)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.get(InvocationFuture.java:223)
	at com.hazelcast.util.FutureUtil.executeWithDeadline(FutureUtil.java:294)
	at com.hazelcast.util.FutureUtil.waitWithDeadline(FutureUtil.java:278)
	at com.hazelcast.util.FutureUtil.waitWithDeadline(FutureUtil.java:252)
	at com.hazelcast.cluster.impl.ClusterStateManager.lockClusterState(ClusterStateManager.java:247)
	at com.hazelcast.cluster.impl.ClusterStateManager.changeClusterState(ClusterStateManager.java:221)
	at com.hazelcast.cluster.impl.ClusterStateManager.changeClusterState(ClusterStateManager.java:198)
	at com.hazelcast.cluster.impl.ClusterServiceImpl.changeClusterState(ClusterServiceImpl.java:819)
	at com.hazelcast.cluster.BasicClusterStateTest.changeClusterState_toPassive_isAllowed_whileReplicationInProgress(BasicClusterStateTest.java:265)
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OracleJDK8/com.hazelcast$hazelcast/593/testReport/junit/com.hazelcast.cluster/BasicClusterStateTest/changeClusterState_toPassive_isAllowed_whileReplicationInProgress/

**Comment by Donnerbart** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-pr-builder/com.hazelcast$hazelcast/17121/testReport/junit/com.hazelcast.cluster.impl/BasicClusterStateTest/changeClusterState_toPassive_isAllowed_whileReplicationInProgress/
