### ISSUE TITLE
[TEST-FAILURE] ClientClusterStateTest Timeout 

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#6488]
```
05:37:33 Running com.hazelcast.client.cluster.ClientClusterStateTest
07:14:52 Build timed out (after 180 minutes). Marking the build as aborted.
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OracleJDK8/595/console

```
17:11:38 Running com.hazelcast.client.cluster.ClientClusterStateTest
18:28:22 Build timed out (after 180 minutes). Marking the build as aborted.
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x/3906/console

**Comment by hasancelik** [comment]
```
08:34:36 Running com.hazelcast.client.cluster.ClientClusterStateTest
10:27:51 Build timed out (after 180 minutes). Marking the build as aborted.
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-ZuluJDK7/2/console

**Comment by metanet** [comment]
http://data.whicdn.com/images/127526655/original.jpg 

looking into this

**Comment by metanet** [comment]
there is an interesting exception:

```
java.lang.NullPointerException
	at com.hazelcast.test.TestNodeRegistry$MockConnection.write(TestNodeRegistry.java:480)
	at com.hazelcast.test.TestNodeRegistry$MockConnectionManager.transmit(TestNodeRegistry.java:398)
	at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.send(OperationServiceImpl.java:406)
	at com.hazelcast.client.impl.ClientEngineImpl$ConnectionListenerImpl.callDisconnectionOperation(ClientEngineImpl.java:585)
	at com.hazelcast.client.impl.ClientEngineImpl$ConnectionListenerImpl.connectionRemoved(ClientEngineImpl.java:571)
	at com.hazelcast.test.TestNodeRegistry$MockConnectionManager$3.run(TestNodeRegistry.java:361)
	at com.hazelcast.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:187)
	at com.hazelcast.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:171)
```

**Comment by metanet** [comment]
another NPE

```
java.lang.NullPointerException
	at com.hazelcast.client.impl.protocol.task.AddMembershipListenerMessageTask$MembershipListenerImpl.shouldSendEvent(AddMembershipListenerMessageTask.java:150)
	at com.hazelcast.client.impl.protocol.task.AddMembershipListenerMessageTask$MembershipListenerImpl.memberRemoved(AddMembershipListenerMessageTask.java:118)
	at com.hazelcast.cluster.impl.ClusterServiceImpl.dispatchEvent(ClusterServiceImpl.java:776)
	at com.hazelcast.cluster.impl.ClusterServiceImpl.dispatchEvent(ClusterServiceImpl.java:88)
	at com.hazelcast.spi.impl.eventservice.impl.LocalEventDispatcher.run(LocalEventDispatcher.java:63)
	at com.hazelcast.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:187)
	at com.hazelcast.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:171)
```
