### ISSUE TITLE
[TEST-FAILURE] ReplicatedMapMergePolicyTest.testLatestUpdateMapMergePolicy FAILURES

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#6489]
**testLatestUpdateMapMergePolicy**
**testHigherHitsMapMergePolicy**
```
org.junit.ComparisonFailure: expected:<[LatestUpdatedV]alue> but was:<[v]alue>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.replicatedmap.ReplicatedMapMergePolicyTest.testLatestUpdateMapMergePolicy(ReplicatedMapMergePolicyTest.java:93)
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/744/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/745/#showFailuresLink

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/747/#showFailuresLink
