### ISSUE TITLE
IOBalancerMemoryLeakTest.testMemoryLeak

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#6496]
```
java.net.SocketException: Unexpected end of file from server
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:776)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:633)
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:773)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:633)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1324)
	at com.hazelcast.internal.ascii.HTTPCommunicator.doGet(HTTPCommunicator.java:140)
	at com.hazelcast.internal.ascii.HTTPCommunicator.getClusterInfo(HTTPCommunicator.java:81)
	at com.hazelcast.nio.tcp.nonblocking.iobalancer.IOBalancerMemoryLeakTest.testMemoryLeak(IOBalancerMemoryLeakTest.java:52)
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/745/testReport/junit/com.hazelcast.nio.tcp.nonblocking.iobalancer/IOBalancerMemoryLeakTest/testMemoryLeak/

**Comment by Donnerbart** [comment]
This happened when I executed all tests locally to measure code coverage (which also picks up nightly tests):
```
java.lang.AssertionError: 
Expected :0
Actual   :4
 <Click to see difference>


	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.nio.tcp.nonblocking.iobalancer.IOBalancerMemoryLeakTest$1.run(IOBalancerMemoryLeakTest.java:65)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:835)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:849)
	at com.hazelcast.nio.tcp.nonblocking.iobalancer.IOBalancerMemoryLeakTest.testMemoryLeak(IOBalancerMemoryLeakTest.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:132)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:50)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:29)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at com.hazelcast.test.AbstractHazelcastClassRunner$1.evaluate(AbstractHazelcastClassRunner.java:184)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```

**Comment by eminn** [comment]
Could it happen that somehow another hazelcast instance interfered with this one since I couldn't be able to reproduce it and I don't have any logs.

**Comment by eminn** [comment]
This issue doesn't appear to be fail on our CI, history can be seen  at https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/786/testReport/com.hazelcast.nio.tcp.nonblocking.iobalancer/IOBalancerMemoryLeakTest/history/ . Closing the issue

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: expected:<0> but was:<3>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.nio.tcp.nonblocking.iobalancer.IOBalancerMemoryLeakTest$1.run(IOBalancerMemoryLeakTest.java:65)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:850)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:864)
	at com.hazelcast.nio.tcp.nonblocking.iobalancer.IOBalancerMemoryLeakTest.testMemoryLeak(IOBalancerMemoryLeakTest.java:60)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/836/testReport/junit/com.hazelcast.nio.tcp.nonblocking.iobalancer/IOBalancerMemoryLeakTest/testMemoryLeak/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: expected:<0> but was:<3>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.nio.tcp.nonblocking.iobalancer.IOBalancerMemoryLeakTest$1.run(IOBalancerMemoryLeakTest.java:65)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:851)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:865)
	at com.hazelcast.nio.tcp.nonblocking.iobalancer.IOBalancerMemoryLeakTest.testMemoryLeak(IOBalancerMemoryLeakTest.java:60)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/855/testReport/junit/com.hazelcast.nio.tcp.nonblocking.iobalancer/IOBalancerMemoryLeakTest/testMemoryLeak/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: expected:<0> but was:<2>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.nio.tcp.nonblocking.iobalancer.IOBalancerMemoryLeakTest$1.run(IOBalancerMemoryLeakTest.java:65)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:851)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:865)
	at com.hazelcast.nio.tcp.nonblocking.iobalancer.IOBalancerMemoryLeakTest.testMemoryLeak(IOBalancerMemoryLeakTest.java:60)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/860/testReport/junit/com.hazelcast.nio.tcp.nonblocking.iobalancer/IOBalancerMemoryLeakTest/testMemoryLeak/

**Comment by mahileeb** [comment]
Would this test pick up the leak I've mentioned in my comment?here:https://github.com/hazelcast/hazelcast/issues/6199

LoadTracker.lastEventCounter is leading socket readers/writers

**Comment by eminn** [comment]
It probably won't pickup since the connections on this test are very short living, so even IOBalancer kicks in it won't find any connections to balance.
