### ISSUE TITLE
Map KeyLoader (Transition not allowed from state LOADED to LOADED)

### ISSUE THREAD

**Issue by dbrimley** [hazelcast/hazelcast#6548]
Observed at client site when they starting of a Hazelcast node.  The node is embedded in Tomcat process and there is only 1 process, there are no other cluster members.

```java
2015-10-20 10:59:21,166 ERROR [hz._hzInstance_1_dev.async.thread-3] com.hazelcast.spi.impl.operationservice.impl.Invocation :
[57.200.123.171]:5701 [dev] [3.5] Failed asynchronous execution of execution callback:
com.hazelcast.map.impl.MapKeyLoader$4@5c1d9b36for call Invocation{ serviceName='hz:impl:mapService',
op=com.hazelcast.map.impl.operation.PartitionCheckIfLoadedOperation{serviceName='null', partitionId=71, callId=0, invocationTime=1445331561139, waitTimeout=-1, callTimeout=60000}, partitionId=71, replicaIndex=0,
 tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeout=60000, target=Address[57.200.123.171]:5701, backupsExpected=0, backupsCompleted=0}
java.lang.IllegalStateException: Transition not allowed from state LOADED to LOADED
                at com.hazelcast.util.ValidationUtil.checkState(ValidationUtil.java:179) ~[hazelcast-3.5.jar:3.5]
                at com.hazelcast.util.StateMachine.next(StateMachine.java:60) ~[hazelcast-3.5.jar:3.5]
                at com.hazelcast.util.StateMachine.nextOrStay(StateMachine.java:70) ~[hazelcast-3.5.jar:3.5]
                at com.hazelcast.map.impl.MapKeyLoader$4.onResponse(MapKeyLoader.java:312) ~[hazelcast-3.5.jar:3.5]
                at com.hazelcast.map.impl.MapKeyLoader$4.onResponse(MapKeyLoader.java:308) ~[hazelcast-3.5.jar:3.5]
                at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture$1.run(InvocationFuture.java:135) ~[hazelcast-3.5.jar:3.5]
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_40]
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_40]
                at java.lang.Thread.run(Thread.java:745) [na:1.8.0_40]
                at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76) [hazelcast-3.5.jar:3.5]
                at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92) [hazelcast-3.5.jar:3.5]

```

**Comment by ahmetmircik** [comment]
Hi @dbrimley, that should be fixed in latest 3.5 patch version (which is 3.5.3), please see this issue https://github.com/hazelcast/hazelcast/issues/6305 and fix for it there.

Now closing this issue, if you still encounter the same exception, please reopen this.
