### ISSUE TITLE
[TEST-FAILURE] XmlClientConfigImportVariableReplacementTest FAILURES

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#6557]
```
java.lang.AssertionError: Expected exception: com.hazelcast.config.InvalidConfigurationException
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:32)
	at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:132)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at com.hazelcast.test.HazelcastParallelClassRunner.access$301(HazelcastParallelClassRunner.java:46)
	at com.hazelcast.test.HazelcastParallelClassRunner$TestRunner.run(HazelcastParallelClassRunner.java:139)
	at java.lang.Thread.run(Thread.java:767)
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.6/723/#showFailuresLink
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.8/7/#showFailuresLink

**Comment by bilalyasar** [comment]
closed via https://github.com/hazelcast/hazelcast/pull/6637
