### ISSUE TITLE
[TEST-FAILURE] ClusterShutdownTest FAILURES

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#6563]
**cluster_mustBeShutDown_by_singleMember_when_clusterState_PASSIVE**
```
java.lang.AssertionError: expected:<SHUT_DOWN> but was:<PASSIVE>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.cluster.ClusterShutdownTest.testClusterShutdownWithSingleMember(ClusterShutdownTest.java:59)
	at com.hazelcast.cluster.ClusterShutdownTest.cluster_mustBeShutDown_by_singleMember_when_clusterState_PASSIVE(ClusterShutdownTest.java:36)
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OracleJDK1.6/com.hazelcast$hazelcast/704/testReport/junit/com.hazelcast.cluster/ClusterShutdownTest/cluster_mustBeShutDown_by_singleMember_when_clusterState_PASSIVE/

**related to** #6504

**Comment by hasancelik** [comment]
**cluster_mustBeShutDown_by_singleMember_when_clusterState_FROZEN**

```
java.lang.AssertionError: expected:<SHUT_DOWN> but was:<PASSIVE>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.cluster.ClusterShutdownTest.testClusterShutdownWithSingleMember(ClusterShutdownTest.java:59)
	at com.hazelcast.cluster.ClusterShutdownTest.cluster_mustBeShutDown_by_singleMember_when_clusterState_FROZEN(ClusterShutdownTest.java:31)

```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-ZuluJDK6/com.hazelcast$hazelcast/22/testReport/junit/com.hazelcast.cluster/ClusterShutdownTest/cluster_mustBeShutDown_by_singleMember_when_clusterState_FROZEN/
