### ISSUE TITLE
Errors generated with remote tasks are not being logged by Hazelcast at an appropriate level

### ISSUE THREAD

**Issue by StanAccy** [hazelcast/hazelcast#6599]
HZ 3.5.3.  A task was submitted to key owner via the IExecutionService.  The invoked task encountered a NPE.  This was caught by Hazelcast in DistributedExecutorService.java:206 which in turn invoked the logException(e) method.   The logException method logs that error at FINEST level.  I rarely run logging at the FINEST level, and our expectation was that any exceptions would be logged at WARNING (its not a Hazelcast ERROR, but it's likely an error that the developers and operations staff should be seeing).

Could this code in DistributedExecutorService.java:
```java
        private void logException(Exception e) {
            if (logger.isFinestEnabled()) {
                logger.finest("While executing callable: " + callableToString, e);
            }
        }
```
be altered to log at warning level?

The end result of logging at finest is that the error is never logged (nobody sane runs a cluster with logging at that level) and thus the problem goes unnoticed.

**Comment by pveentjer** [comment]
Queston: did your future get a result? At least on the caller side you should just get an NPE wrapped in an ExecutionException. So on the caller side you would have noticed they exception.

I agree that having logging on finest is not practical in this case. Especially if an execute is done and the task is a fire and forget task.

**Comment by StanAccy** [comment]
No - the future returned null from Future.get() - no exception thrown, so even if they had checked the Future, it wouldnt have shown the error.

**Comment by pveentjer** [comment]
That smells like a bug to me. I'll try to reproduce it and make a fix.

**Comment by StanAccy** [comment]
When I get a moment, I'll upload my test case that I created to reproduce.

N

**Comment by pveentjer** [comment]
I made small example program to reproduce the problem:

```
public class Main {

    public static void main(String[] args) throws ExecutionException, InterruptedException {
        HazelcastInstance hz = Hazelcast.newHazelcastInstance();
        IExecutorService ex = hz.getExecutorService("foo");
        ex.submit(new Task()).get();
    }

    public static class Task implements Runnable, Serializable {
        @Override
        public void run() {
            throw new NullPointerException();
        }
    }
}
```
I have tried with 3.5.1 and 3.6 master.  But in both cases I get the desired result:

```
Exception in thread "main" java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.hazelcast.executor.impl.DistributedExecutorService$CallableProcessor.run(DistributedExecutorService.java:203)
	at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:209)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)
Caused by: java.lang.NullPointerException
	at com.hazelcast.Main$Task.run(Main.java:24)
	at com.hazelcast.executor.impl.RunnableAdapter.call(RunnableAdapter.java:54)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.hazelcast.executor.impl.DistributedExecutorService$CallableProcessor.run(DistributedExecutorService.java:201)
	... 6 more
```

**Comment by StanAccy** [comment]
Thanks Peter - I also see that your test case works as expected (using 3.5.3).  The test case I had used nested tasks (based on the client scenario).  I wasn't checking the inner Future.get(), only the outer one.  So the error is being reported - my apologies for the time waste here.  This has me thinking now (clearly wasnt thinking earlier...)  - now I see why the error logging was set to FINEST - because every invocation is expected to call Future.get(), and then any errors would be clearly visible in the application code.  However, how do we handle fire and forget tasks (which these were).  Raising the log level will likely cause duplicate errors to be logged in most correctly written application code (one by Hazelcast, one by the application code) which I dont think would be appreciated by those users.  Leaving the log level where it is results in incorrectly written code being hard to diagnose in the case of errors. Neither scenario seems good.  A few thoughts which might be overly complex: a. perhaps we could log errors on task submission if the get() isnt invoked within a set time (would require some sort of monitor thread and a flag in the Future) b. Maybe some sort of IES task listener that would report invocations, completions, errors c.) Alter the documentation of submit,submitToKeyOwner etc to state that return values must be checked, and add a submitAndForget() API that will log any errors and doesnt return anything. d.) Just make the docs really explicit that it is the application that is responsible for checking for errors in Future.get() e.) Provide a non-blocking method on Future that could allow the task to be checked for errors.
Another idea - if I submit a Runnable, then Hazelcast logs by default.  If its a Callable, then App code checks and Hazelcast doesnt log.  Runnable tasks are likely fire and forget.  Why would I make it Callable if I wasnt going to check the return value?

**Comment by pveentjer** [comment]
> Raising the log level will likely cause duplicate errors to be logged in most correctly written application code (one by Hazelcast, one by the application code) which I dont think would be appreciated by those users.

It depends. You only get duplicate exceptions when the task is executed on the same node as it was invoked. But perhaps we should state something regarding exception handling and logging; e.g. we don;t log the exception; you need to do it yourself (on the executing side).

>> A few thoughts which might be overly complex

The solutions you have suggested make sense, but imho are fragile and complicated.

What do you think about a configurable exception handler on the IExecutorService. That by default works like it works now, but you can plug in something else.
