### ISSUE TITLE
NoClassDefFoundError org.apache.xml.serializer.TreeWalker

### ISSUE THREAD

**Issue by wmz7year** [hazelcast/hazelcast#6614]
```
java.lang.NoClassDefFoundError: org/apache/xml/serializer/TreeWalker
	at org.apache.xalan.processor.TransformerFactoryImpl.newTransformer(TransformerFactoryImpl.java:823)
	at com.hazelcast.config.AbstractXmlConfigHelper.schemaValidation(AbstractXmlConfigHelper.java:182)
	at com.hazelcast.config.XmlConfigBuilder.parseAndBuildConfig(XmlConfigBuilder.java:211)
	at com.hazelcast.config.XmlConfigBuilder.build(XmlConfigBuilder.java:194)
	at com.hazelcast.config.ClasspathXmlConfig.<init>(ClasspathXmlConfig.java:100)
	at com.hazelcast.config.ClasspathXmlConfig.<init>(ClasspathXmlConfig.java:57)
	at com.hazelcast.config.ClasspathXmlConfig.<init>(ClasspathXmlConfig.java:44)
```

I use hazelcast 3.5.1 and  got this exception,How can I fix it?

**Comment by pveentjer** [comment]
That is a strange error. 

Can you post your full classpath and your jvm version?

**Comment by wmz7year** [comment]
java version "1.7.0_79"
Java(TM) SE Runtime Environment (build 1.7.0_79-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.79-b02, mixed mode)

hazelcast-3.5.1.jar and  hazelcast-cloud-3.5.1.jar

**Comment by bilalyasar** [comment]
@wmz7year , this is known issue for us..  We have completely fixed this issue in `3.6`.. For `3.5`, we advice some workarounds. Can you please set this system property in your jvm , (also you can pass this property to your jvm as an arg line)
```
System.setProperty("javax.xml.transform.TransformerFactory",
                "com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl");
```
many thanks for feedback and we are waiting your new feedbacks..

**Comment by wmz7year** [comment]
@bilalyasar Thanks, it works!

**Comment by smallCabbage** [comment]
@bilalyasar  good, it work!  My error is 
"java.lang.IllegalStateException: You are running with invalid JAXP api or implementation. JAXP api/implementation of version 1.3.1 (included in JDK6) or higher is required. In case you are using ant, make sure ant 1.7.0 or higher is used - older versions of ant contain JAXP api/impl version 1.2 (in xml-apis.jar). If you want to keep using older ant versions, you have to configure it to use higher the JAXP api/impl versions.";
