### ISSUE TITLE
[TEST-FAILURE] VersionCheckTest.testVersionCheckParameters

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#6639]
```
java.lang.AssertionError: Values should be different. Actual: 0
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failEquals(Assert.java:185)
	at org.junit.Assert.assertNotEquals(Assert.java:161)
	at org.junit.Assert.assertNotEquals(Assert.java:175)
	at com.hazelcast.util.VersionCheckTest.testVersionCheckParameters(VersionCheckTest.java:58)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.maintenance-IbmJDK1.6/com.hazelcast$hazelcast/303/testReport/junit/com.hazelcast.util/VersionCheckTest/testVersionCheckParameters/

**Comment by kobalski** [comment]
@hasancelik Closing, this issue since it did not failed again for a long time.
