### ISSUE TITLE
ReplicatedMapLoadingTest.testSyncFillup

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#6672]
```
java.lang.AssertionError: expected:<3000> but was:<2999>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.replicatedmap.ReplicatedMapLoadingTest.testSyncFillup(ReplicatedMapLoadingTest.java:109)
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OracleJDK1.6/com.hazelcast$hazelcast/717/testReport/junit/com.hazelcast.replicatedmap/ReplicatedMapLoadingTest/testSyncFillup/

**Comment by Donnerbart** [comment]
Hopefully fixed via: https://github.com/hazelcast/hazelcast/commit/9bd5d676923e42db4179d83c38de3963046b4457

**Comment by tombujok** [comment]
Just saw it again...

**Comment by Donnerbart** [comment]
Please add the link to the failed build. The error messages should have been improved with the last commit.

**Comment by Donnerbart** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/2769/testReport/junit/com.hazelcast.replicatedmap/ReplicatedMapLoadingTest/testSyncFillUp/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: map1 should contain 3000 elements expected:<3000> but was:<2999>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.replicatedmap.ReplicatedMapLoadingTest.assertMapSize(ReplicatedMapLoadingTest.java:113)
	at com.hazelcast.replicatedmap.ReplicatedMapLoadingTest.access$000(ReplicatedMapLoadingTest.java:37)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK1.6/com.hazelcast$hazelcast/931/testReport/junit/com.hazelcast.replicatedmap/ReplicatedMapLoadingTest/testSyncFillUp/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: map1 should contain 3000 elements expected:<3000> but was:<2999>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.replicatedmap.ReplicatedMapLoadingTest.assertMapSize(ReplicatedMapLoadingTest.java:113)
	at com.hazelcast.replicatedmap.ReplicatedMapLoadingTest.access$000(ReplicatedMapLoadingTest.java:37)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK1.6/com.hazelcast$hazelcast/939/testReport/junit/com.hazelcast.replicatedmap/ReplicatedMapLoadingTest/testSyncFillUp/
