### ISSUE TITLE
Sporadic startup failure on 3.6-EA

### ISSUE THREAD

**Issue by nilskp** [hazelcast/hazelcast#6684]
Have seen this a few times when testing locally (using 3 Hz instances + 1 client in same JVM), on 3.6-EA:

```
Nov 06, 2015 3:16:19 PM com.hazelcast.cluster.impl.operations.FinalizeJoinOperation
SEVERE: [169.254.24.193]:5701 [622fac90-2834-486b-8b7b-aae59343dab8] [3.6-EA] Cannot set initial state after node joined! -> ACTIVE
java.lang.IllegalStateException: Cannot set initial state after node joined! -> ACTIVE
    at com.hazelcast.cluster.impl.ClusterServiceImpl.initialClusterState(ClusterServiceImpl.java:877)
    at com.hazelcast.cluster.impl.operations.FinalizeJoinOperation.run(FinalizeJoinOperation.java:71)
    at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:167)
    at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:386)
    at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.processPacket(OperationThread.java:184)
    at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.process(OperationThread.java:137)
    at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.doRun(OperationThread.java:124)
    at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.run(OperationThread.java:99)
```

**Comment by mdogan** [comment]
Please try latest master. This should have been fixed already by https://github.com/hazelcast/hazelcast/pull/6540

**Comment by enesakar** [comment]
closing. please re-open if you see #6540 did not solve this
