### ISSUE TITLE
ClusterInfoTest.all_nodes_should_have_the_same_cluster_start_time_and_id_after_master_shutdown_and_new_node_join

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#6688]
```
java.lang.AssertionError: the size of the collection is not correct: found-content:[Member [127.0.0.1]:9806, Member [127.0.0.1]:9808 this, Member [127.0.0.1]:9810] expected:<2> but was:<3>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.test.HazelcastTestSupport$6.run(HazelcastTestSupport.java:643)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:825)
	at com.hazelcast.test.HazelcastTestSupport.assertSizeEventually(HazelcastTestSupport.java:640)
	at com.hazelcast.test.HazelcastTestSupport.assertSizeEventually(HazelcastTestSupport.java:636)
	at com.hazelcast.cluster.ClusterInfoTest.all_nodes_should_have_the_same_cluster_start_time_and_id_after_master_shutdown_and_new_node_join(ClusterInfoTest.java:102)
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK8-Quality-Outreach/com.hazelcast$hazelcast/234/testReport/junit/com.hazelcast.cluster/ClusterInfoTest/all_nodes_should_have_the_same_cluster_start_time_and_id_after_master_shutdown_and_new_node_join/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: the size of the collection is not correct: found-content:[Member [127.0.0.1]:8248, Member [127.0.0.1]:8249 this, Member [127.0.0.1]:8250] expected:<2> but was:<3>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.test.HazelcastTestSupport$6.run(HazelcastTestSupport.java:643)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:825)
	at com.hazelcast.test.HazelcastTestSupport.assertSizeEventually(HazelcastTestSupport.java:640)
	at com.hazelcast.test.HazelcastTestSupport.assertSizeEventually(HazelcastTestSupport.java:636)
	at com.hazelcast.cluster.ClusterInfoTest.all_nodes_should_have_the_same_cluster_start_time_and_id_after_master_shutdown_and_new_node_join(ClusterInfoTest.java:102)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-ZuluJDK8/lastCompletedBuild/com.hazelcast$hazelcast/testReport/com.hazelcast.cluster/ClusterInfoTest/all_nodes_should_have_the_same_cluster_start_time_and_id_after_master_shutdown_and_new_node_join/

**Comment by mdogan** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/3661/testReport/junit/com.hazelcast.cluster/ClusterInfoTest/all_nodes_should_have_the_same_cluster_start_time_and_id_after_master_shutdown_and_new_node_join/

```
java.lang.AssertionError: expected:<1466412868183> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.cluster.ClusterInfoTest.all_nodes_should_have_the_same_cluster_start_time_and_id_after_master_shutdown_and_new_node_join(ClusterInfoTest.java:112)
```

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: expected:<1466555081769> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.cluster.ClusterInfoTest.all_nodes_should_have_the_same_cluster_start_time_and_id_after_master_shutdown_and_new_node_join(ClusterInfoTest.java:112)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-ZuluJDK6/com.hazelcast$hazelcast/241/testReport/junit/com.hazelcast.cluster/ClusterInfoTest/all_nodes_should_have_the_same_cluster_start_time_and_id_after_master_shutdown_and_new_node_join/
