### ISSUE TITLE
[TEST-FAILURE] ClientReplicatedMapListenerTest.testEntryAdded

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#6695]
```
java.lang.AssertionError: expected:<1> but was:<2>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.client.replicatedmap.ClientReplicatedMapListenerTest$1.run(ClientReplicatedMapListenerTest.java:59)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:825)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:839)
	at com.hazelcast.client.replicatedmap.ClientReplicatedMapListenerTest.testEntryAdded(ClientReplicatedMapListenerTest.java:56)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.6/com.hazelcast$hazelcast-client/742/testReport/junit/com.hazelcast.client.replicatedmap/ClientReplicatedMapListenerTest/testEntryAdded/

**Comment by sancar** [comment]
fixed by https://github.com/hazelcast/hazelcast/pull/6728
