### ISSUE TITLE
[TEST-FAILURE] ListenerLeakTestSmartRouting Timeout & Failures

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#6764]
```
04:45:28 Running com.hazelcast.client.listeners.leak.ListenerLeakTestSmartRouting
06:23:44 Build timed out (after 180 minutes). Marking the build as aborted.
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.6/751/console
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-pr-builder/16875/console

**Comment by hasancelik** [comment]
**ListenerLeakTestSmartRouting.testDistributedObjectListeners**
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at org.junit.Assert.assertFalse(Assert.java:74)
	at com.hazelcast.client.listeners.leak.ListenerLeakTestSupport.assertNoLeftOverOnNode(ListenerLeakTestSupport.java:68)
	at com.hazelcast.client.listeners.leak.ListenerLeakTestSupport.assertNoLeftOver(ListenerLeakTestSupport.java:49)
	at com.hazelcast.client.listeners.leak.ListenerLeakTestSmartRouting.testDistributedObjectListeners(ListenerLeakTestSmartRouting.java:151)
```

https://hazelcast-l337.ci.cloudbees.com/view/Quality-Outreach/job/Hazelcast-3.x-OpenJDK9-Quality-Outreach/com.hazelcast$hazelcast-client-legacy/258/testReport/junit/com.hazelcast.client.listeners.leak/ListenerLeakTestSmartRouting/testDistributedObjectListeners/

**Comment by cangencer** [comment]
I think this might be fixed by https://github.com/hazelcast/hazelcast/pull/6768. I'm closing this and will re-open if it occurs again.
