### ISSUE TITLE
Error being logged while running TestFullApplicationContext

### ISSUE THREAD

**Issue by jerrinot** [hazelcast/hazelcast#6784]
I'm running `TestFullApplicationContext` test on fcac88e8c27c

and I can see it's logging 
```
WARNING: [127.0.0.1]:5700 [spring-group] [3.6-RC1-SNAPSHOT] Error while initializing proxy: ReplicatedMapProxy -> replicatedMap
java.lang.IllegalArgumentException: EventFilter required!
    at com.hazelcast.spi.impl.eventservice.impl.EventServiceImpl.registerListenerInternal(EventServiceImpl.java:177)
    at com.hazelcast.spi.impl.eventservice.impl.EventServiceImpl.registerLocalListener(EventServiceImpl.java:158)
    at com.hazelcast.replicatedmap.impl.ReplicatedMapEventPublishingService.addEventListener(ReplicatedMapEventPublishingService.java:137)
    at com.hazelcast.replicatedmap.impl.ReplicatedMapService.initializeListeners(ReplicatedMapService.java:353)
    at com.hazelcast.replicatedmap.impl.ReplicatedMapProxy.initialize(ReplicatedMapProxy.java:97)
    at com.hazelcast.spi.impl.proxyservice.impl.ProxyRegistry.doCreateProxy(ProxyRegistry.java:192)
    at com.hazelcast.spi.impl.proxyservice.impl.ProxyRegistry.createProxy(ProxyRegistry.java:182)
    at com.hazelcast.spi.impl.proxyservice.impl.ProxyRegistry.getOrCreateProxy(ProxyRegistry.java:151)
    at com.hazelcast.spi.impl.proxyservice.impl.ProxyServiceImpl.getDistributedObject(ProxyServiceImpl.java:131)
```

**Comment by jerrinot** [comment]
as discussed with @eminn
