### ISSUE TITLE
Passing url to hazelcast.xml and hazelcast-client.xml with -Dhazelcast.config

### ISSUE THREAD

**Issue by gAmUssA** [hazelcast/hazelcast#6795]
Guys, how I can load `hazelcast.xml` from http server using `-Dhazelcast.config`?
like `-Dhazelcast.config=http://resources.dev/hazelcast.xml` gives me

```
Nov 19, 2015 12:17:50 PM com.hazelcast.config.XmlConfigLocator
INFO: Loading configuration http://resources.dev/hazelcast.xml from System property 'hazelcast.config'
Nov 19, 2015 12:17:50 PM com.hazelcast.config.XmlConfigLocator
INFO: Using configuration file at /Users/vikgamov/projects/jcache-jug/http:/resources.dev/hazelcast.xml
Exception in thread "main" com.hazelcast.core.HazelcastException: com.hazelcast.core.HazelcastException: Config file at '/Users/vikgamov/projects/jcache-jug/http:/resources.dev/hazelcast.xml' doesn't exist.
    at com.hazelcast.config.XmlConfigLocator.<init>(XmlConfigLocator.java:68)
    at com.hazelcast.config.XmlConfigBuilder.<init>(XmlConfigBuilder.java:157)
    at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:109)
    at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:87)
    at com.hazelcast.gradle.starter.Starter.main(Starter.java:14)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: com.hazelcast.core.HazelcastException: Config file at '/Users/vikgamov/projects/jcache-jug/http:/resources.dev/hazelcast.xml' doesn't exist.
    at com.hazelcast.config.XmlConfigLocator.loadSystemPropertyFileResource(XmlConfigLocator.java:160)
    at com.hazelcast.config.XmlConfigLocator.loadFromSystemProperty(XmlConfigLocator.java:148)
    at com.hazelcast.config.XmlConfigLocator.<init>(XmlConfigLocator.java:54)
    ... 9 more
```

Please add support for `UrlXmlConfig`.

Thank you

**Comment by pveentjer** [comment]
I don't know if we should abuse subclasses for interpreting the url. This leads to a noisy API. Apart from that, the problem here is with the XmlConfigLocator that only has support for file or classpath based config files. So an additional check needs to be made to interpret http: based urls and a loader should be made for that.

**Comment by pveentjer** [comment]
I have marked this as a backlog item since it isn't a bug. Afaik this is a 30 minute job to get fixed.

**Comment by gAmUssA** [comment]
I potential need for this from our client. I tested this `-D` parameter during a meeting with them and it failed. if it's 30 min to fix, why it's in backlog?

**Comment by pveentjer** [comment]
The question is if it is a bug or working like specified :) 

Anyhow. Where is the fix PR?

**Comment by jerrinot** [comment]
@gAmUssA:

```java
diff --git a/hazelcast/src/main/java/com/hazelcast/config/XmlConfigLocator.java b/hazelcast/src/main/java/com/hazelcast/config/XmlConfigLocator.java
index da7646f..043bf5b 100644
--- a/hazelcast/src/main/java/com/hazelcast/config/XmlConfigLocator.java
+++ b/hazelcast/src/main/java/com/hazelcast/config/XmlConfigLocator.java
@@ -23,6 +23,7 @@ import com.hazelcast.logging.Logger;
 import java.io.File;
 import java.io.FileInputStream;
 import java.io.FileNotFoundException;
+import java.io.IOException;
 import java.io.InputStream;
 import java.net.MalformedURLException;
 import java.net.URL;
@@ -144,12 +145,25 @@ public class XmlConfigLocator {
 
         if (configSystemProperty.startsWith("classpath:")) {
             loadSystemPropertyClassPathResource(configSystemProperty);
+        } else if (configSystemProperty.startsWith("http://") || configSystemProperty.startsWith("https://")) {
+            loadSystemPropertyFromWeb(configSystemProperty);
         } else {
             loadSystemPropertyFileResource(configSystemProperty);
         }
         return true;
     }
 
+    private void loadSystemPropertyFromWeb(String configSystemProperty) {
+        try {
+            configurationUrl = new URL(configSystemProperty);
+            in = configurationUrl.openStream();
+        } catch (MalformedURLException e) {
+            throw new HazelcastException("Invalid Hazelcast configuration URL", e);
+        } catch (IOException e) {
+            throw new HazelcastException("Invalid Hazelcast configuration URL", e);
+        }
+    }
+
     private void loadSystemPropertyFileResource(String configSystemProperty) {
         //it is a file.
         configurationFile = new File(configSystemProperty);
diff --git a/hazelcast/src/test/java/com/hazelcast/core/SillyConfigTest.java b/hazelcast/src/test/java/com/hazelcast/core/SillyConfigTest.java
index 2e24573..8ac818b 100644
--- a/hazelcast/src/test/java/com/hazelcast/core/SillyConfigTest.java
+++ b/hazelcast/src/test/java/com/hazelcast/core/SillyConfigTest.java
@@ -1,4 +1,18 @@
 package com.hazelcast.core;
 
+import org.junit.Test;
+
+import static org.junit.Assert.assertEquals;
+
 public class SillyConfigTest {
+    private static final String URL = "https://gist.githubusercontent.com/jerrinot/325f0fddfe42c848b7cdd75261837b03/raw/9fd8982e58e91f1e9a2dd91348899b6b014c2e50/gistfile1.txt";
+
+    @Test
+    public void testLoadingFromRemoteUrl() {
+        System.setProperty("hazelcast.config", URL);
+        HazelcastInstance instance = Hazelcast.newHazelcastInstance();
+        int cpuCoreFreq = instance.getCluster().getLocalMember().getIntAttribute("CPU_CORE_FREQ");
+        assertEquals(1033, cpuCoreFreq);
+    }
+
 }
```

I don't dare to send a PR with this though :)

**Comment by gAmUssA** [comment]
@jerrinot I can if you want me to

**Comment by jerrinot** [comment]
and I thought the dynamic classloaders are the biggest security hole one could possible imagine :)

**Comment by gAmUssA** [comment]
@jerrinot maybe we should explicitly allow do this with `-Dhazelast.config.allow.load.from.web=true`? 
In this case, there is an indication that user knows what she's doing.

**Comment by jerrinot** [comment]
well, if an attacker is able to change a system property with the URL then the attacker can add a new flag. I don't see much benefit here.

There are other questions:
- what to do when the file is not available? fallback? fail-fast? 
- should we allow HTTPS only? this would (partially) mitigate man-in-the-middle attacks

**Comment by osgill** [comment]
Hi @jerrinot @gAmUssA I am looking for a solution to this as well, loading the `hazelcast.xml` remotely via a url. Are there any options to achieve this without updating the internal XmlConfigLocator ? Or is there a way I can override this class with a custom implementation. Thanks
