### ISSUE TITLE
NPE CachePutBackupOperation: ConcurrentReferenceHashMap.java:1278

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#6800]
during 3.5.4 and 3.6-RC1 simulator runs  in all cluster size,  we find this exception logged in the member logs 

```
FATAL 2015-11-18 20:31:50,542 [hz._hzInstance_1_workers.partition-operation.thread-5] com.hazelcast.cache.impl.operation.CachePutBackupOperation: [10.0.0.230]:5701 [workers] [3.5.4] null
java.lang.NullPointerException
    at com.hazelcast.util.ConcurrentReferenceHashMap.put(ConcurrentReferenceHashMap.java:1278)
    at com.hazelcast.cache.impl.record.CacheRecordHashMap.put(CacheRecordHashMap.java:55)
    at com.hazelcast.cache.impl.record.CacheRecordHashMap.put(CacheRecordHashMap.java:32)
    at com.hazelcast.cache.impl.AbstractCacheRecordStore.doPutRecord(AbstractCacheRecordStore.java:866)
    at com.hazelcast.cache.impl.AbstractCacheRecordStore.doPutRecord(AbstractCacheRecordStore.java:862)
    at com.hazelcast.cache.impl.AbstractCacheRecordStore.putRecord(AbstractCacheRecordStore.java:858)
    at com.hazelcast.cache.impl.operation.CachePutBackupOperation.run(CachePutBackupOperation.java:57)
    at com.hazelcast.spi.impl.operationservice.impl.operations.Backup.run(Backup.java:101)
    at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:137)
    at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:315)
    at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.processPacket(OperationThread.java:142)
    at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.process(OperationThread.java:115)
    at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.doRun(OperationThread.java:101)
    at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.run(OperationThread.java:76)
```

full logs and http://54.87.52.100/~jenkins/workspace/Release/3.5.4/

**Comment by Danny-Hazelcast** [comment]
full log http://54.87.52.100/~jenkins/workspace/Release/3.6-RC1/


in medium large and small cluster
