### ISSUE TITLE
MapMemoryUsageStressTest.voidCacher

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#6803]
```
java.lang.OutOfMemoryError: GC overhead limit exceeded
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-nightly/776/com.hazelcast$hazelcast-client/testReport/com.hazelcast.client.map/MapMemoryUsageStressTest/voidCacher/

**Older aborted build with different cause:**
```
java.lang.AssertionError: Timeout waiting for thread Thread-22 to terminate
	at org.junit.Assert.fail(Assert.java:88)
	at com.hazelcast.test.HazelcastTestSupport.assertJoinable(HazelcastTestSupport.java:722)
	at com.hazelcast.client.map.MapMemoryUsageStressTest.voidCacher(MapMemoryUsageStressTest.java:56)
```
https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast-client/763/testReport/junit/com.hazelcast.client.map/MapMemoryUsageStressTest/voidCacher/

**Comment by hasancelik** [comment]
```
Timeout waiting for thread Thread-53 to terminate
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-nightly/780/com.hazelcast$hazelcast-client/testReport/com.hazelcast.client.map/MapMemoryUsageStressTest/voidCacher/

**Comment by Donnerbart** [comment]
When I execute this test locally I get the following error with the new client:
```
java.lang.IllegalStateException: Unable to connect to any address in the config! The following addresses were tried:[/127.0.0.1:5701, /127.0.0.1:5702, /127.0.0.1:5703]

	at com.hazelcast.client.spi.impl.ClusterListenerSupport.connectToOne(ClusterListenerSupport.java:241)
	at com.hazelcast.client.spi.impl.ClusterListenerSupport.connectToCluster(ClusterListenerSupport.java:174)
	at com.hazelcast.client.spi.impl.ClientClusterServiceImpl.start(ClientClusterServiceImpl.java:203)
	at com.hazelcast.client.impl.HazelcastClientInstanceImpl.start(HazelcastClientInstanceImpl.java:303)
	at com.hazelcast.client.test.TestHazelcastFactory.newHazelcastClient(TestHazelcastFactory.java:73)
	at com.hazelcast.client.map.MapMemoryUsageStressTest.launchHazelcastServer(MapMemoryUsageStressTest.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:132)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at com.hazelcast.test.HazelcastParallelClassRunner.access$301(HazelcastParallelClassRunner.java:46)
	at com.hazelcast.test.HazelcastParallelClassRunner$TestRunner.run(HazelcastParallelClassRunner.java:139)
	at java.lang.Thread.run(Thread.java:745)
When I execute this test locally I get the following exception:
```
java.lang.IllegalStateException: Unable to connect to any address in the config! The following addresses were tried:[/127.0.0.1:5701, /127.0.0.1:5702, /127.0.0.1:5703]

	at com.hazelcast.client.spi.impl.ClusterListenerSupport.connectToOne(ClusterListenerSupport.java:241)
	at com.hazelcast.client.spi.impl.ClusterListenerSupport.connectToCluster(ClusterListenerSupport.java:174)
	at com.hazelcast.client.spi.impl.ClientClusterServiceImpl.start(ClientClusterServiceImpl.java:203)
	at com.hazelcast.client.impl.HazelcastClientInstanceImpl.start(HazelcastClientInstanceImpl.java:303)
	at com.hazelcast.client.test.TestHazelcastFactory.newHazelcastClient(TestHazelcastFactory.java:73)
	at com.hazelcast.client.map.MapMemoryUsageStressTest.launchHazelcastServer(MapMemoryUsageStressTest.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:132)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at com.hazelcast.test.HazelcastParallelClassRunner.access$301(HazelcastParallelClassRunner.java:46)
	at com.hazelcast.test.HazelcastParallelClassRunner$TestRunner.run(HazelcastParallelClassRunner.java:139)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by kobalski** [comment]
I get same exception inside session replication tests too.

```
java.lang.IllegalStateException: Unable to connect to any address in the config! The following addresses were tried:[/127.0.0.1:5703, /127.0.0.1:5702, /127.0.0.1:5701]
	at com.hazelcast.client.spi.impl.ClusterListenerSupport.connectToOne(ClusterListenerSupport.java:231)
	at com.hazelcast.client.spi.impl.ClusterListenerSupport.connectToCluster(ClusterListenerSupport.java:164)
	at com.hazelcast.client.spi.impl.ClientClusterServiceImpl.start(ClientClusterServiceImpl.java:203)
	at com.hazelcast.client.impl.HazelcastClientInstanceImpl.start(HazelcastClientInstanceImpl.java:303)
	at com.hazelcast.client.HazelcastClient.newHazelcastClient(HazelcastClient.java:86)
	at com.hazelcast.web.HazelcastInstanceLoader.createClientInstance(HazelcastInstanceLoader.java:123)
	at com.hazelcast.web.HazelcastInstanceLoader.createInstance(HazelcastInstanceLoader.java:73)
	at com.hazelcast.web.ClusteredSessionService.reconnectHZInstance(ClusteredSessionService.java:155)
	at com.hazelcast.web.ClusteredSessionService.ensureInstance(ClusteredSessionService.java:138)
	at com.hazelcast.web.ClusteredSessionService.access$100(ClusteredSessionService.java:61)
	at com.hazelcast.web.ClusteredSessionService$1.run(ClusteredSessionService.java:124)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
	at com.hazelcast.web.ClusteredSessionService$EnsureInstanceThread.run(ClusteredSessionService.java:349)
```

**Comment by gurbuzali** [comment]
I've removed this line `config.getNetworkConfig().addAddress("127.0.0.1");` #36 and the IllegalStateException is gone. Test failed with the first run :(

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: Timeout waiting for thread Thread-60 to terminate
	at org.junit.Assert.fail(Assert.java:88)
	at com.hazelcast.test.HazelcastTestSupport.assertJoinable(HazelcastTestSupport.java:732)
	at com.hazelcast.client.map.MapMemoryUsageStressTest.voidCacher(MapMemoryUsageStressTest.java:56)
```
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast-client/785/testReport/junit/com.hazelcast.client.map/MapMemoryUsageStressTest/voidCacher/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast-client/789/testReport/junit/com.hazelcast.client.map/MapMemoryUsageStressTest/voidCacher/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: Timeout waiting for thread Thread-30 to terminate
	at org.junit.Assert.fail(Assert.java:88)
	at com.hazelcast.test.HazelcastTestSupport.assertJoinable(HazelcastTestSupport.java:732)
	at com.hazelcast.client.map.MapMemoryUsageStressTest.voidCacher(MapMemoryUsageStressTest.java:50)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast-client/797/testReport/junit/com.hazelcast.client.map/MapMemoryUsageStressTest/voidCacher/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: Timeout waiting for thread Thread-80 to terminate
	at org.junit.Assert.fail(Assert.java:88)
	at com.hazelcast.test.HazelcastTestSupport.assertJoinable(HazelcastTestSupport.java:732)
	at com.hazelcast.client.map.MapMemoryUsageStressTest.voidCacher(MapMemoryUsageStressTest.java:54)
```
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast-client/800/testReport/junit/com.hazelcast.client.map/MapMemoryUsageStressTest/voidCacher/

**Comment by eminn** [comment]
Increased the timeout via 23b16ac2ca3c70c00cd09d4ac10da3c73b57c88b

**Comment by hasancelik** [comment]
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.lang.Object.wait(Native Method)
	at java.lang.Thread.join(Thread.java:1289)
	at com.hazelcast.test.HazelcastTestSupport.assertJoinable(HazelcastTestSupport.java:723)
	at com.hazelcast.client.map.MapMemoryUsageStressTest.voidCacher(MapMemoryUsageStressTest.java:54)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast-client/802/testReport/junit/com.hazelcast.client.map/MapMemoryUsageStressTest/voidCacher/

**Comment by eminn** [comment]
timeout increased via fd4fcc2010451c9b2a320c06ae801da8d6069643
