### ISSUE TITLE
TopicOverloadTest.whenBlock_whenNoSpace

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#6819]
```
java.lang.AssertionError: expected:<100> but was:<26>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.topic.impl.reliable.TopicOverloadTest.whenBlock_whenNoSpace(TopicOverloadTest.java:174)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK1.6/com.hazelcast$hazelcast/733/testReport/junit/com.hazelcast.topic.impl.reliable/TopicOverloadTest/whenBlock_whenNoSpace/

**Comment by enesakar** [comment]
can not be reproduced for a month. closing.

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: expected:<100> but was:<29>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.topic.impl.reliable.TopicOverloadAbstractTest.whenBlock_whenNoSpace(TopicOverloadAbstractTest.java:153)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:88)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:82)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.lang.Thread.run(Thread.java:745)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-OracleJDK1.7/com.hazelcast$hazelcast/372/testReport/junit/com.hazelcast.topic.impl.reliable/TopicOverloadTest/whenBlock_whenNoSpace/

**Comment by gurbuzali** [comment]
This is a very very time sensitive test. I can reproduce the failure if I put some sleep while filling the ring-buffer (very possible in high load test environment). I propose to remove this test altogether or increase ttl to a much higher value and mark the test as `slow`. @pveentjer WDYT ?

**Comment by pveentjer** [comment]
+1 for ali his suggestion

**Comment by jerrinot** [comment]
@pveentjer: can you implement it please?

**Comment by gurbuzali** [comment]
I've ignored the test
