### ISSUE TITLE
DummyClientReplicatedMapTest.testKeySet

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#6865]
```
java.lang.AssertionError: expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.client.replicatedmap.DummyClientReplicatedMapTest.testKeySet(DummyClientReplicatedMapTest.java:97)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/new-lab-fast-pr/99/testReport/junit/com.hazelcast.client.replicatedmap/DummyClientReplicatedMapTest/testKeySet/

**Comment by eminn** [comment]
fixed via 7fbe793dbc598c07cd92080cfcc997a6389b6b73
