### ISSUE TITLE
SlowOperationDetectorBasicTest Failures

### ISSUE THREAD

**Issue by mdogan** [hazelcast/hazelcast#6893]
```
testNestedSlowOperationOnPartitionAndGenericOperationThreads(com.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationDetectorBasicTest)  Time elapsed: 3.561 sec  <<< FAILURE!
18:20:46 java.lang.AssertionError: Expected 1 slow operation logs, but was 0. expected:<1> but was:<0>
18:20:46    at org.junit.Assert.fail(Assert.java:88)
18:20:46    at org.junit.Assert.failNotEquals(Assert.java:834)
18:20:46    at org.junit.Assert.assertEquals(Assert.java:118)
18:20:46    at com.hazelcast.test.HazelcastTestSupport.assertEqualsStringFormat(HazelcastTestSupport.java:874)
18:20:46    at com.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationDetectorAbstractTest.assertNumberOfSlowOperationLogs(SlowOperationDetectorAbstractTest.java:112)
18:20:46    at com.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationDetectorBasicTest.testNestedSlowOperationOnPartitionAndGenericOperationThreads(SlowOperationDetectorBasicTest.java:164)
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-pr-builder/17134/console

**Comment by Donnerbart** [comment]
Should be fixed via https://github.com/hazelcast/hazelcast/commit/a8b8ad71e2775efcabe01f71f790ae831113bf45

**Comment by hasancelik** [comment]
**maintenance**
```
java.lang.AssertionError: Expected 1 slow operation logs, but was 2. expected:<1> but was:<2>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at com.hazelcast.test.HazelcastTestSupport.assertEqualsStringFormat(HazelcastTestSupport.java:890)
	at com.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationDetectorAbstractTest.assertNumberOfSlowOperationLogs(SlowOperationDetectorAbstractTest.java:125)
	at com.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationDetectorAbstractTest$1.run(SlowOperationDetectorAbstractTest.java:118)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:851)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:865)
	at com.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationDetectorAbstractTest.getSlowOperationLogsAndAssertNumberOfSlowOperationLogs(SlowOperationDetectorAbstractTest.java:114)
	at com.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationDetectorBasicTest.testNestedSlowOperationOnPartitionAndGenericOperationThreads(SlowOperationDetectorBasicTest.java:157)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.maintenance-ZuluJDK8/com.hazelcast$hazelcast/88/testReport/junit/com.hazelcast.spi.impl.operationexecutor.slowoperationdetector/SlowOperationDetectorBasicTest/testNestedSlowOperationOnPartitionAndGenericOperationThreads/

**Comment by hasancelik** [comment]
**testNestedSlowOperationOnSamePartition**
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.lang.Thread.sleep(Native Method)
	at java.lang.Thread.sleep(Thread.java:302)
	at java.util.concurrent.TimeUnit.sleep(TimeUnit.java:328)
	at com.hazelcast.test.HazelcastTestSupport.sleepMillis(HazelcastTestSupport.java:280)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:892)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:898)
	at com.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationDetectorAbstractTest.getSlowOperationLogsAndAssertNumberOfSlowOperationLogs(SlowOperationDetectorAbstractTest.java:116)
	at com.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationDetectorBasicTest.testNestedSlowOperationOnSamePartition(SlowOperationDetectorBasicTest.java:145)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x/com.hazelcast$hazelcast/5353/testReport/junit/com.hazelcast.spi.impl.operationexecutor.slowoperationdetector/SlowOperationDetectorBasicTest/testNestedSlowOperationOnSamePartition/

**Comment by Donnerbart** [comment]
These failures are due to the timing sensitivity of the system and the tests. I tried to increase the accuracy of the system with a PR, but Peter didn't like to have the "when has this operation/task started?" in the runner. So these tests may fail if the system is under heavy load, but as we see this has not been the case for a long time. I'm closing this, since a fix will not be trivial, but I'm sure the system works fine within its capabilities.

**Comment by hasancelik** [comment]
**testSlowRunnableOnGenericOperationThread**
```
java.lang.AssertionError: Expected 1 slow operation logs, but was 0. expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at com.hazelcast.test.HazelcastTestSupport.assertEqualsStringFormat(HazelcastTestSupport.java:940)
	at com.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationDetectorAbstractTest.assertNumberOfSlowOperationLogs(SlowOperationDetectorAbstractTest.java:127)
	at com.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationDetectorAbstractTest$1.run(SlowOperationDetectorAbstractTest.java:112)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:901)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:915)
	at com.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationDetectorAbstractTest.getSlowOperationLogsAndAssertNumberOfSlowOperationLogs(SlowOperationDetectorAbstractTest.java:108)
	at com.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationDetectorBasicTest.testSlowRunnableOnGenericOperationThread(SlowOperationDetectorBasicTest.java:78)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-ZuluJDK8/com.hazelcast$hazelcast/291/testReport/junit/com.hazelcast.spi.impl.operationexecutor.slowoperationdetector/SlowOperationDetectorBasicTest/testSlowRunnableOnGenericOperationThread/

**Comment by Donnerbart** [comment]
I ran the failed test for almost 4 hours (over 4500 iterations) without a single failure. The test is just timing sensitive, due to the nature of the underlying system. I tried to improve this once, but Peter blocked any change in the `OperationRunner` to make the system more accurate (https://github.com/hazelcast/hazelcast/pull/8464). So right now I cannot fix this.

**Comment by jerrinot** [comment]
@Donnerbart: spuriously failing test is not good. it should be either removed or fixed.

**Comment by metanet** [comment]
We run some tests for more than 3 days to get a single test failure. These spuriously failing tests should be run on amazon for a long duration.

**Comment by Donnerbart** [comment]
Running the test for x days until a failure happens will not provide any new information. I just ran it today to rule out, that there is a general bug in the system (it didn't hurt me, it's quite cold here).

What may help could be to make the test "slower" by increasing the sleep times of the slow operations, to work against the built-in inaccuracy of the `SlowOperationDetector`.

The main reason for the inaccuracy is that Peter doesn't want to set a timestamp directly in the `OperationRunner` (where we know exactly when an operation execution is started). So the `SlowOperationDetector` observes the `OperationRunner` and has to see a task at least twice, before it can decide if it's a slow operation or not. So we lose up to a second of the execution time of each operation. This makes the testing quite hard and counterintuitive, since you always have to keep that lost second in mind for the asserts.

In the failing case there is no slow operation detected at all. So I assume there was a hiccup in the system and the `SlowOperationDetector` was not invoked the required times while the slow `Runnable` was still being processed. I'll have a look if I can increase those times without shooting the test times through the ceiling.

**Comment by Donnerbart** [comment]
https://github.com/hazelcast/hazelcast/pull/8690

**Comment by hasancelik** [comment]
**testNestedSlowOperationOnSamePartition**
```
java.lang.AssertionError: Expected 1 slow operation logs, but was 0. expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at com.hazelcast.test.HazelcastTestSupport.assertEqualsStringFormat(HazelcastTestSupport.java:944)
	at com.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationDetectorAbstractTest.assertNumberOfSlowOperationLogs(SlowOperationDetectorAbstractTest.java:127)
	at com.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationDetectorAbstractTest$1.run(SlowOperationDetectorAbstractTest.java:112)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:905)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:919)
	at com.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationDetectorAbstractTest.getSlowOperationLogsAndAssertNumberOfSlowOperationLogs(SlowOperationDetectorAbstractTest.java:108)
	at com.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationDetectorBasicTest.testNestedSlowOperationOnSamePartition(SlowOperationDetectorBasicTest.java:144)
```
https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.maintenance-OracleJDK1.7/com.hazelcast$hazelcast/305/testReport/junit/com.hazelcast.spi.impl.operationexecutor.slowoperationdetector/SlowOperationDetectorBasicTest/testNestedSlowOperationOnSamePartition/

**Comment by mdogan** [comment]
No failures since October.
