### ISSUE TITLE
RingbufferAddReadOneStressTest.whenShortTTLAndBigBuffer

### ISSUE THREAD

**Issue by Donnerbart** [hazelcast/hazelcast#6895]
Happened when I executed the all tests locally to measure code covrage:

```
java.lang.AssertionError: No error should have been thrown, but ConsumeThread-1 completed error expected null, but was:<com.hazelcast.ringbuffer.StaleSequenceException: sequence:914202 is too small. The current headSequence is:914219 tailSequence is:915218>

    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotNull(Assert.java:755)
    at org.junit.Assert.assertNull(Assert.java:737)
    at com.hazelcast.test.TestThread.assertSucceedsEventually(TestThread.java:62)
    at com.hazelcast.ringbuffer.impl.RingbufferAddReadOneStressTest.test(RingbufferAddReadOneStressTest.java:82)
    at com.hazelcast.ringbuffer.impl.RingbufferAddReadOneStressTest.whenLongTTLAndSmallBuffer(RingbufferAddReadOneStressTest.java:47)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:132)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:50)
    at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:29)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at com.hazelcast.test.AbstractHazelcastClassRunner$1.evaluate(AbstractHazelcastClassRunner.java:184)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runners.Suite.runChild(Suite.java:128)
    at org.junit.runners.Suite.runChild(Suite.java:27)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```

**Comment by hasancelik** [comment]
**RingbufferAddReadOneStressTest.whenShortTTLAndBigBuffer**
```
java.lang.AssertionError: No error should have been thrown, but ConsumeThread-2 completed error expected null, but was:<com.hazelcast.ringbuffer.StaleSequenceException: sequence:11817 is too small. The current headSequence is:11841 tailSequence is:11840>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotNull(Assert.java:755)
	at org.junit.Assert.assertNull(Assert.java:737)
	at com.hazelcast.test.TestThread.assertSucceedsEventually(TestThread.java:62)
	at com.hazelcast.ringbuffer.impl.RingbufferAddReadOneStressTest.test(RingbufferAddReadOneStressTest.java:83)
	at com.hazelcast.ringbuffer.impl.RingbufferAddReadOneStressTest.whenShortTTLAndBigBuffer(RingbufferAddReadOneStressTest.java:55)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/806/testReport/junit/com.hazelcast.ringbuffer.impl/RingbufferAddReadOneStressTest/whenShortTTLAndBigBuffer/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: No error should have been thrown, but ConsumeThread-2 completed error expected null, but was:<com.hazelcast.ringbuffer.StaleSequenceException: sequence:84578 is too small. The current headSequence is:84579 tailSequence is:84578>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotNull(Assert.java:755)
	at org.junit.Assert.assertNull(Assert.java:737)
	at com.hazelcast.test.TestThread.assertSucceedsEventually(TestThread.java:62)
	at com.hazelcast.ringbuffer.impl.RingbufferAddReadOneStressTest.test(RingbufferAddReadOneStressTest.java:83)
	at com.hazelcast.ringbuffer.impl.RingbufferAddReadOneStressTest.whenShortTTLAndBigBuffer(RingbufferAddReadOneStressTest.java:55)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/1084/testReport/junit/com.hazelcast.ringbuffer.impl/RingbufferAddReadOneStressTest/whenShortTTLAndBigBuffer/

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/1084/testReport/junit/com.hazelcast.ringbuffer.impl/RingbufferAddReadOneStressTest/whenShortTTLAndBigBuffer/

**Comment by hasancelik** [comment]
Related to #5498 and #7193

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: No error should have been thrown, but ConsumeThread-1 completed error expected null, but was:<com.hazelcast.ringbuffer.StaleSequenceException: sequence:19156 is too small and data store is disabled. The current headSequence is:19157 tailSequence is:19156>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotNull(Assert.java:755)
	at org.junit.Assert.assertNull(Assert.java:737)
	at com.hazelcast.test.TestThread.assertSucceedsEventually(TestThread.java:62)
	at com.hazelcast.ringbuffer.impl.RingbufferAddReadOneStressTest.test(RingbufferAddReadOneStressTest.java:82)
	at com.hazelcast.ringbuffer.impl.RingbufferAddReadOneStressTest.whenShortTTLAndBigBuffer(RingbufferAddReadOneStressTest.java:55)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/1105/testReport/junit/com.hazelcast.ringbuffer.impl/RingbufferAddReadOneStressTest/whenShortTTLAndBigBuffer/

**Comment by jerrinot** [comment]
fixed by #9505

**Comment by hasancelik** [comment]
*maintenance*
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.lang.Thread.sleep(Native Method)
	at java.lang.Thread.sleep(Thread.java:340)
	at java.util.concurrent.TimeUnit.sleep(TimeUnit.java:360)
	at com.hazelcast.test.HazelcastTestSupport.sleepSeconds(HazelcastTestSupport.java:269)
	at com.hazelcast.test.HazelcastTestSupport.sleepAndStop(HazelcastTestSupport.java:291)
	at com.hazelcast.ringbuffer.impl.RingbufferAddReadOneStressTest.test(RingbufferAddReadOneStressTest.java:79)
	at com.hazelcast.ringbuffer.impl.RingbufferAddReadOneStressTest.whenShortTTLAndBigBuffer(RingbufferAddReadOneStressTest.java:56)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-nightly/com.hazelcast$hazelcast/1133/testReport/junit/com.hazelcast.ringbuffer.impl/RingbufferAddReadOneStressTest/whenShortTTLAndBigBuffer/

**Comment by hasancelik** [comment]
*master*
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.lang.Thread.sleep(Native Method)
	at java.lang.Thread.sleep(Thread.java:340)
	at java.util.concurrent.TimeUnit.sleep(TimeUnit.java:360)
	at com.hazelcast.test.HazelcastTestSupport.sleepSeconds(HazelcastTestSupport.java:269)
	at com.hazelcast.test.HazelcastTestSupport.sleepAndStop(HazelcastTestSupport.java:291)
	at com.hazelcast.ringbuffer.impl.RingbufferAddReadOneStressTest.test(RingbufferAddReadOneStressTest.java:79)
	at com.hazelcast.ringbuffer.impl.RingbufferAddReadOneStressTest.whenShortTTLAndBigBuffer(RingbufferAddReadOneStressTest.java:56)
```
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/1254/testReport/junit/com.hazelcast.ringbuffer.impl/RingbufferAddReadOneStressTest/whenShortTTLAndBigBuffer/

**Comment by ahmetmircik** [comment]
seems this is a fix for this issue: https://github.com/hazelcast/hazelcast/commit/74f39edaa16ed8d81d10efb881528c45d6712b8b

**Comment by hasancelik** [comment]
```
org.junit.runners.model.TestTimedOutException: test timed out after 900000 milliseconds
	at java.lang.Thread.sleep(Native Method)
	at java.lang.Thread.sleep(Thread.java:340)
	at java.util.concurrent.TimeUnit.sleep(TimeUnit.java:386)
	at com.hazelcast.test.HazelcastTestSupport.sleepSeconds(HazelcastTestSupport.java:316)
	at com.hazelcast.test.HazelcastTestSupport.sleepAndStop(HazelcastTestSupport.java:338)
	at com.hazelcast.ringbuffer.impl.RingbufferAddReadOneStressTest.test(RingbufferAddReadOneStressTest.java:95)
	at com.hazelcast.ringbuffer.impl.RingbufferAddReadOneStressTest.whenShortTTLAndBigBuffer(RingbufferAddReadOneStressTest.java:72)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-nightly/com.hazelcast$hazelcast/1438/testReport/junit/com.hazelcast.ringbuffer.impl/RingbufferAddReadOneStressTest/whenShortTTLAndBigBuffer/

**Comment by mmedenjak** [comment]
Possible fix in a similar test: https://github.com/hazelcast/hazelcast/pull/12285
