### ISSUE TITLE
NPE - hazelcast 3.5.4

### ISSUE THREAD

**Issue by gembin** [hazelcast/hazelcast#6896]
jdk1.8, Mac OS X 10.9.5, hazelcast 3.5.4

Just ran the `GettingStarted` example in the http://hazelcast.org/getting-started/
Not sure how to reproduce.

configuration

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<hazelcast
    xsi:schemaLocation="http://www.hazelcast.com/schema/config hazelcast-config-3.5.xsd"
    xmlns="http://www.hazelcast.com/schema/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <group>
        <name>dev</name>
        <password>dev-pass</password>
    </group>

    <network>
        <public-address></public-address>
        <port auto-increment="false" port-count="100">5000</port>
        <outbound-ports>
            <ports>0</ports>
        </outbound-ports>
        <reuse-address>true</reuse-address>
        <join>
            <multicast enabled="true">
                <multicast-group>224.2.2.3</multicast-group>
                <multicast-port>54327</multicast-port>
            </multicast>
        </join>

    </network>
</hazelcast>
```

``` java
Nov 27, 2015 4:20:39 PM com.hazelcast.cluster.impl.MulticastJoiner
SEVERE: []:5000 [dev] [3.5.4] null
java.lang.NullPointerException
    at com.hazelcast.nio.Address.hashCode(Address.java:183)
    at com.hazelcast.cluster.impl.AbstractJoiner.shouldMerge(AbstractJoiner.java:194)
    at com.hazelcast.cluster.impl.MulticastJoiner.searchForOtherClusters(MulticastJoiner.java:122)
    at com.hazelcast.cluster.impl.SplitBrainHandler.searchForOtherClusters(SplitBrainHandler.java:48)
    at com.hazelcast.cluster.impl.SplitBrainHandler.run(SplitBrainHandler.java:38)
    at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:209)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
    at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
    at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)
```

**Comment by mdogan** [comment]
Is there any other cluster running with different Hazelcast version? and using the same default multicast configuration...

**Comment by gembin** [comment]
No, only one node running.

**Comment by gembin** [comment]
This code seems can reproduce this issue, where the configuration of `hazelcast.xml` is mentioned at the very beginning.

Wait about 2 minutes, the stacktrace is printed.
```java
  
        System.setProperty("java.net.preferIPv4Stack", "true");
        System.setProperty("hazelcast.config", "/path/to/hazelcast.xml");
        HazelcastInstance instance = Hazelcast.newHazelcastInstance();
        Map<Integer, String> mapCustomers = instance.getMap("customers");
        mapCustomers.put(1, "Joe");
        mapCustomers.put(2, "Ali");
        mapCustomers.put(3, "Avi");

        System.out.println("Customer with key 1: " + mapCustomers.get(1));
        System.out.println("Map Size:" + mapCustomers.size());

        Queue<String> queueCustomers = instance.getQueue("customers");
        queueCustomers.offer("Tom");
        queueCustomers.offer("Mary");
        queueCustomers.offer("Jane");
        System.out.println("First customer: " + queueCustomers.poll());
        System.out.println("Second customer: " + queueCustomers.peek());
        System.out.println("Queue size: " + queueCustomers.size());
```

**Comment by mdogan** [comment]
Most probably you have another Hazelcast cluster running on your network with a different version. 

`MulticastJoiner.searchForOtherClusters(MulticastJoiner.java:122)` is executed when a multicast message is received from a different node. 

2 minute is default search interval. See props:

```
hazelcast.merge.first.run.delay.seconds:  300 SECONDS
hazelcast.merge.next.run.delay.seconds: 120 SECONDS
```

**Comment by gembin** [comment]
Myself didn't run any other version of Hazelcast cluster on my network, not sure if anybody else did.

I change the `group name` to a random name e.g. `gdsjhkfhedj` and more random `multicast-group` e.g. `224.12.21.13` that is unlike to have the same value with others. Dose it mean my cluster will not try to join other cluster if i changed my configuration as described above?

But, the exception i got it's exactly the same.

**Comment by enesakar** [comment]
closing issue. please reopen if you think problem still exists.
