### ISSUE TITLE
MapLockTest failures 

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#6953]
**com.hazelcast.map.MapLockTest.testLockEviction
com.hazelcast.map.MapLockTest.testLockOwnership
com.hazelcast.map.MapLockTest.testAbsentKeyIsLocked**

```
org.junit.runners.model.TestTimedOutException: test timed out after 20000 milliseconds
	at java.lang.Thread.setPriority0(Native Method)
	at java.lang.Thread.setPriority(Thread.java:1131)
	at java.lang.Thread.init(Thread.java:414)
	at java.lang.Thread.init(Thread.java:349)
	at java.lang.Thread.<init>(Thread.java:532)
	at com.hazelcast.util.executor.HazelcastManagedThread.<init>(HazelcastManagedThread.java:46)
	at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.<init>(OperationThread.java:71)
	at com.hazelcast.spi.impl.operationexecutor.classic.PartitionOperationThread.<init>(PartitionOperationThread.java:37)
	at com.hazelcast.spi.impl.operationexecutor.classic.ClassicOperationExecutor.initPartitionThreads(ClassicOperationExecutor.java:154)
	at com.hazelcast.spi.impl.operationexecutor.classic.ClassicOperationExecutor.<init>(ClassicOperationExecutor.java:100)
	at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.<init>(OperationServiceImpl.java:167)
	at com.hazelcast.spi.impl.NodeEngineImpl.<init>(NodeEngineImpl.java:102)
```

**com.hazelcast.map.MapLockTest.com.hazelcast.map.MapLockTest**]

```
ava.lang.IllegalStateException: Instances haven't been shut down: [HazelcastInstance{name='_hzInstance_4065_dev', node=Address[127.0.0.1]:9026}]
	at com.hazelcast.test.AbstractHazelcastClassRunner$1.evaluate(AbstractHazelcastClassRunner.java:190)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-ZuluJDK7/com.hazelcast$hazelcast/38/

**Comment by eminn** [comment]
I couldn't be able to reproduce the failure. The problem seems that for some reason the nodes couldn't be initialized within the test timeout duration. Closing the issue...
