### ISSUE TITLE
ExecutorServiceTest.testInvokeAllTimeoutSuccess 

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#6954]
```
java.lang.AssertionError: expected:<null> but was:<Task completed>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.executor.ExecutorServiceTest.testInvokeAllTimeoutSuccess(ExecutorServiceTest.java:836)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-ZuluJDK7/com.hazelcast$hazelcast/38/testReport/junit/com.hazelcast.executor/ExecutorServiceTest/testInvokeAllTimeoutSuccess/

**Comment by gurbuzali** [comment]
duplicate https://github.com/hazelcast/hazelcast/issues/6954
