### ISSUE TITLE
SingleNodeTest.executorServiceStats

### ISSUE THREAD

**Issue by jerrinot** [hazelcast/hazelcast#6966]
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/297/

Jenkins is down right now so I can't paste more, however I can reproduce it locally with `Repeat(100)`

**Comment by hasancelik** [comment]
```
10:47:48 executorServiceStats(com.hazelcast.executor.SingleNodeTest)  Time elapsed: 120.241 sec  <<< FAILURE!
10:47:48 java.lang.AssertionError: expected:<1> but was:<0>
10:47:48 	at org.junit.Assert.fail(Assert.java:88)
10:47:48 	at org.junit.Assert.failNotEquals(Assert.java:834)
10:47:48 	at org.junit.Assert.assertEquals(Assert.java:645)
10:47:48 	at org.junit.Assert.assertEquals(Assert.java:631)
10:47:48 	at com.hazelcast.executor.SingleNodeTest$5.run(SingleNodeTest.java:359)
10:47:48 	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:835)
10:47:48 	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:849)
10:47:48 	at com.hazelcast.executor.SingleNodeTest.executorServiceStats(SingleNodeTest.java:351)
```

**Comment by gurbuzali** [comment]
should be fixed via https://github.com/hazelcast/hazelcast/pull/6975
