### ISSUE TITLE
ClientExecutorServiceTest.testGetFutureAfterCancel

### ISSUE THREAD

**Issue by jerrinot** [hazelcast/hazelcast#6969]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-pr-builder/com.hazelcast$hazelcast-client/17278/console

```
Tests run: 15, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 23.423 sec <<< FAILURE! - in com.hazelcast.client.executor.ClientExecutorServiceTest
testGetFutureAfterCancel(com.hazelcast.client.executor.ClientExecutorServiceTest)  Time elapsed: 21.842 sec  <<< FAILURE!
java.lang.AssertionError: Expected exception: java.util.concurrent.CancellationException
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:32)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:132)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at com.hazelcast.test.HazelcastParallelClassRunner.access$301(HazelcastParallelClassRunner.java:46)
	at com.hazelcast.test.HazelcastParallelClassRunner$TestRunner.run(HazelcastParallelClassRunner.java:139)
	at java.lang.Thread.run(Thread.java:662)
```

**Comment by muratayan** [comment]
Same test fails for my backport, in maintenance branch as well: #6942

**Comment by sancar** [comment]
Test is failed in new client. Writing it here, because pr builder logs tend to disappear very quickly.
