### ISSUE TITLE
ClientMapLoadAllTest testLoadAll_givenKeys

### ISSUE THREAD

**Issue by jerrinot** [hazelcast/hazelcast#6970]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-pr-builder/com.hazelcast$hazelcast-client/17278/consoleText

```
Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 120.593 sec <<< FAILURE! - in com.hazelcast.client.map.ClientMapLoadAllTest
testLoadAll_givenKeys(com.hazelcast.client.map.ClientMapLoadAllTest)  Time elapsed: 120.593 sec  <<< ERROR!
com.hazelcast.core.OperationTimeoutException: null
	at com.hazelcast.client.impl.protocol.ClientExceptionFactory$40.createException(ClientExceptionFactory.java:332)
	at com.hazelcast.client.impl.protocol.ClientExceptionFactory.createException(ClientExceptionFactory.java:553)
	at com.hazelcast.client.impl.protocol.ClientExceptionFactory.createException(ClientExceptionFactory.java:539)
	at com.hazelcast.client.spi.impl.ClientInvocationServiceSupport$ResponseThread.handleClientMessage(ClientInvocationServiceSupport.java:333)
	at com.hazelcast.client.spi.impl.ClientInvocationServiceSupport$ResponseThread.process(ClientInvocationServiceSupport.java:313)
	at com.hazelcast.client.spi.impl.ClientInvocationServiceSupport$ResponseThread.doRun(ClientInvocationServiceSupport.java:306)
	at com.hazelcast.client.spi.impl.ClientInvocationServiceSupport$ResponseThread.run(ClientInvocationServiceSupport.java:283)
	at ------ End remote and begin local stack-trace ------.(Unknown Source)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveResponse(ClientInvocationFuture.java:134)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.get(ClientInvocationFuture.java:101)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.get(ClientInvocationFuture.java:76)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.get(ClientInvocationFuture.java:39)
	at com.hazelcast.client.spi.ClientProxy.invoke(ClientProxy.java:144)
	at com.hazelcast.client.proxy.ClientMapProxy.size(ClientMapProxy.java:1300)
	at com.hazelcast.client.map.ClientMapLoadAllTest.testLoadAll_givenKeys(ClientMapLoadAllTest.java:76)
```

**Comment by hasancelik** [comment]
suppressed by https://github.com/hazelcast/hazelcast/commit/73150ae73b4ed21eb9393dc211b21d556a955907

**Comment by sancar** [comment]
Test is failing in local. 

Stacktrace of operation timeout should have been

```
java.util.concurrent.ExecutionException: com.hazelcast.core.OperationTimeoutException: No response for 60 ms. Aborting invocation! Invocation{serviceName='hz:impl:mapService', op=com.hazelcast.map.impl.operation.MapSizeOperation{serviceName='hz:impl:mapService', partitionId=67, replicaIndex=0, callId=0, invocationTime=1449138697769 (Thu Dec 03 12:31:37 EET 2015), waitTimeout=-1, callTimeout=10, name=08981a51-31f6-4d09-82de-b68e526619e5}, partitionId=67, replicaIndex=0, tryCount=250, tryPauseMillis=500, invokeCount=5, callTimeout=10, target=Address[127.0.0.1]:5001, backupsExpected=0, backupsCompleted=0, connection=MockConnection{localEndpoint=Address[127.0.0.1]:5001, remoteEndpoint=Address[127.0.0.1]:5001}} No response has been received!  backups-expected:0 backups-completed: 0
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveApplicationResponseOrThrowException(InvocationFuture.java:358)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.get(InvocationFuture.java:223)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.get(InvocationFuture.java:202)
	at com.hazelcast.spi.impl.operationservice.impl.InvokeOnPartitions.retryFailedPartitions(InvokeOnPartitions.java:131)
	at com.hazelcast.spi.impl.operationservice.impl.InvokeOnPartitions.invoke(InvokeOnPartitions.java:67)
	at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.invokeOnAllPartitions(OperationServiceImpl.java:368)
	at com.hazelcast.client.impl.protocol.task.AbstractAllPartitionsMessageTask.processMessage(AbstractAllPartitionsMessageTask.java:41)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:120)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:99)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)
```

I will also work on printing correct stack trace.

**Comment by jerrinot** [comment]
@sancar: is this fixed by #7015 ?

**Comment by sancar** [comment]
@jerrinot No it is not fix for the issue. It is just making sure that correct exception send from server.

**Comment by muratayan** [comment]
@sancar Is this issue still going on? If so, how were you available to fail it in your local?

**Comment by sancar** [comment]
It was failing something like 1 in 2000 run. But test is fast so it does not make you wait long time.

**Comment by ihsandemir** [comment]
I have repeated the test for 2000 times and it did not fail. The test also did not fail since 20.12.2015. Hence, closing this issue.
