### ISSUE TITLE
ClusterRollingRestartTest.test_rollingRestart[clusterState:PASSIVE,partitionAssignmentType:NEVER]

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#6974]
```
com.hazelcast.core.HazelcastException: java.util.concurrent.TimeoutException: Call Invocation{serviceName='hz:core:clusterService', op=com.hazelcast.cluster.impl.operations.LockClusterStateOperation{serviceName='hz:core:clusterService', partitionId=-1, replicaIndex=0, callId=4, invocationTime=1449113838589 (Thu Dec 03 05:37:18 EET 2015), waitTimeout=-1, callTimeout=60000}, partitionId=-1, replicaIndex=0, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeout=60000, target=Address[127.0.0.1]:8180, backupsExpected=0, backupsCompleted=0, connection=MockConnection{localEndpoint=Address[127.0.0.1]:8178, remoteEndpoint=Address[127.0.0.1]:8180}} encountered a timeout
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveApplicationResponse(InvocationFuture.java:367)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveApplicationResponseOrThrowException(InvocationFuture.java:335)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.get(InvocationFuture.java:223)
	at com.hazelcast.util.FutureUtil.executeWithDeadline(FutureUtil.java:294)
	at com.hazelcast.util.FutureUtil.waitWithDeadline(FutureUtil.java:278)
	at com.hazelcast.util.FutureUtil.waitWithDeadline(FutureUtil.java:252)
	at com.hazelcast.cluster.impl.ClusterStateManager.lockClusterState(ClusterStateManager.java:275)
	at com.hazelcast.cluster.impl.ClusterStateManager.changeClusterState(ClusterStateManager.java:249)
	at com.hazelcast.cluster.impl.ClusterStateManager.changeClusterState(ClusterStateManager.java:228)
	at com.hazelcast.cluster.impl.ClusterServiceImpl.changeClusterState(ClusterServiceImpl.java:821)
	at com.hazelcast.cluster.impl.AdvancedClusterStateTest.changeClusterStateEventually(AdvancedClusterStateTest.java:641)
	at com.hazelcast.cluster.impl.ClusterRollingRestartTest.test_rollingRestart(ClusterRollingRestartTest.java:90)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK1.7/com.hazelcast$hazelcast/317/testReport/junit/com.hazelcast.cluster.impl/ClusterRollingRestartTest/test_rollingRestart_clusterState_PASSIVE_partitionAssignmentType_NEVER_/

**Comment by mdogan** [comment]
This looks like a problem in mock network.

**Comment by hasancelik** [comment]
**test_rollingRestart[clusterState:PASSIVE,partitionAssignmentType:AT_THE_END]**
```
com.hazelcast.core.HazelcastException: java.util.concurrent.TimeoutException: Call Invocation{serviceName='hz:core:clusterService', op=com.hazelcast.cluster.impl.operations.LockClusterStateOperation{serviceName='hz:core:clusterService', partitionId=-1, replicaIndex=0, callId=4, invocationTime=1449705211898 (Thu Dec 10 01:53:31 EET 2015), waitTimeout=-1, callTimeout=60000}, partitionId=-1, replicaIndex=0, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeout=60000, target=Address[127.0.0.1]:7187, backupsExpected=0, backupsCompleted=0, connection=MockConnection{localEndpoint=Address[127.0.0.1]:7185, remoteEndpoint=Address[127.0.0.1]:7187}} encountered a timeout
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveApplicationResponse(InvocationFuture.java:367)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveApplicationResponseOrThrowException(InvocationFuture.java:335)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.get(InvocationFuture.java:223)
	at com.hazelcast.util.FutureUtil.executeWithDeadline(FutureUtil.java:294)
	at com.hazelcast.util.FutureUtil.waitWithDeadline(FutureUtil.java:278)
	at com.hazelcast.util.FutureUtil.waitWithDeadline(FutureUtil.java:252)
	at com.hazelcast.cluster.impl.ClusterStateManager.lockClusterState(ClusterStateManager.java:275)
	at com.hazelcast.cluster.impl.ClusterStateManager.changeClusterState(ClusterStateManager.java:249)
	at com.hazelcast.cluster.impl.ClusterStateManager.changeClusterState(ClusterStateManager.java:228)
	at com.hazelcast.cluster.impl.ClusterServiceImpl.changeClusterState(ClusterServiceImpl.java:821)
	at com.hazelcast.cluster.impl.AdvancedClusterStateTest.changeClusterStateEventually(AdvancedClusterStateTest.java:650)
	at com.hazelcast.cluster.impl.ClusterRollingRestartTest.test_rollingRestart(ClusterRollingRestartTest.java:90)
```

https://hazelcast-l337.ci.cloudbees.com/view/Quality-Outreach/job/Hazelcast-3.x-OpenJDK8-Quality-Outreach/com.hazelcast$hazelcast/266/testReport/junit/com.hazelcast.cluster.impl/ClusterRollingRestartTest/test_rollingRestart_clusterState_PASSIVE_partitionAssignmentType_AT_THE_END_/
