### ISSUE TITLE
MergePolicyTest.testLatestUpdateMapMergePolicy

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#6976]
```
org.junit.ComparisonFailure: expected:<[LatestUpdatedV]alue2> but was:<[v]alue2>
    at org.junit.Assert.assertEquals(Assert.java:115)
    at org.junit.Assert.assertEquals(Assert.java:144)
    at com.hazelcast.map.MergePolicyTest.testLatestUpdateMapMergePolicy(MergePolicyTest.java:79)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/789/testReport/junit/com.hazelcast.map/MergePolicyTest/testLatestUpdateMapMergePolicy/

**Comment by Holmistr** [comment]
*master* (commit f56a4c5893d908cdcef360317bffaddb353a9c17)

Reopening as it's failing again on nightly build: https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/186/testReport/com.hazelcast.map/MergePolicyTest/testLatestUpdateMapMergePolicy/

Stacktrace:
```
org.junit.ComparisonFailure: expected:<[LatestUpdatedV]alue2> but was:<[v]alue2>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.map.MergePolicyTest.testLatestUpdateMapMergePolicy(MergePolicyTest.java:102)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

Standard output:
```
Hiccups measured while running test 'testLatestUpdateMapMergePolicy(com.hazelcast.map.MergePolicyTest):'
04:05:50, accumulated pauses: 37 ms, max pause: 0 ms, pauses over 1000 ms: 0
04:05:55, accumulated pauses: 86 ms, max pause: 45 ms, pauses over 1000 ms: 0
04:06:00, accumulated pauses: 302 ms, max pause: 292 ms, pauses over 1000 ms: 0
```

Possible cause: https://github.com/hazelcast/hazelcast/commit/f56a4c5893d908cdcef360317bffaddb353a9c17
