### ISSUE TITLE
 com.hazelcast.core.HazelcastInstanceNotActiveException even after Cluster Comes up

### ISSUE THREAD

**Issue by prabhushan** [hazelcast/hazelcast#6987]
VERSION - 3.4.1
Hi,
We encounter this issue often. Whenever HazelCast Cluster went down and came up after few minutes or so. The Hazelcast client no longer able to poll the queue. It throws
```
 com.hazelcast.core.HazelcastInstanceNotActiveException: Hazelcast instance is not active!
	at com.hazelcast.client.impl.HazelcastClientProxy.getClient(HazelcastClientProxy.java:259)
	at com.hazelcast.client.impl.HazelcastClientProxy.getQueue(HazelcastClientProxy.java:82)
	at com.drfirst.hazelClient.client.HzQueueServiceImpl.get(HzQueueServiceImpl.java:54)
```
this is how the client is instantiated.

```
public static void main( String[] args )
    { 	
    	clientConfig.getNetworkConfig().addAddress("172.16.61.15:10500");
    	clientConfig.getGroupConfig().setName("test");
		clientConfig.getGroupConfig().setPassword("test");
		new HzQueueServiceImpl().init(clientConfig);
    }
    
    private <T> void init(ClientConfig clientConfig){
    	
		client = HazelcastClient.newHazelcastClient(clientConfig);
		final IQueue<String> queue = client.getQueue("test-queue");
		ExecutorService executorService = Executors.newFixedThreadPool(10);
		ConsumerExecutorService consumerExecutorService = new ConsumerExecutorService(executorService);
		ConsumerCallback<T> consumberCallBack = new ConsumerCallBackImpl();
		for (int i = 0; i < numberofThreads; i++) {
			// CALL A RUNNABLE TO PROCESS THE POLLED VALUE
			}
		executorService.shutdown();
    }

	public void put(String queueName, String value) throws InterruptedException {
		IQueue<String>queue = client.getQueue(queueName);
		queue.put(value);
	}

	public <T> T get(String queueName, Class<T> type)
			throws InterruptedException {
		try{
			IQueue<String>queue = client.getQueue(queueName);
			return (T) queue.poll();
		}
		/*catch(HazelcastInstanceNotActiveException e){
			//init(clientConfig);
		}*/
		finally{
			
		}
		
```

**Comment by sancar** [comment]
Hi, 
You will see 
`INFO: HazelcastClient[hz.client_0_dev][3.6-RC2-SNAPSHOT] is SHUTDOWN `

logs on client logs. Which means client is shutdown and will never try to connect back to cluster. If you want to increase this time you need to configure followings. 

`ClientNetworkConfig.connectionAttemptLimit` Default is 2 times
`ClientNetworkConfig.connectionAttemptPeriod` Default is  3000 ms

Defaults means after 6 seconds of Cluster shutdown client will also shutdown.
My answers are valid for 3.4.1. For latest version, there some config changes. 

For latest version see
http://docs.hazelcast.org/docs/latest-dev/manual/html-single/#handling-client-connection-failure

**Comment by prabhushan** [comment]
Thank you for the response. We had written our own reconnect logic and it solved the issue. But I shall try it out.
