### ISSUE TITLE
ClientMapNearCacheTest.testNearCacheInvalidationWithLFU

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#7002]
```
java.lang.AssertionError: ownedEntryCount should be smaller than 100, but was 100
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.client.map.impl.nearcache.ClientMapNearCacheTest.assertThatOwnedEntryCountIsSmallerThan(ClientMapNearCacheTest.java:610)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.6/769/com.hazelcast$hazelcast-client-legacy/testReport/com.hazelcast.client.map.impl.nearcache/ClientMapNearCacheTest/testNearCacheInvalidationWithLFU/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.6/com.hazelcast$hazelcast-client-legacy/771/testReport/junit/com.hazelcast.client.map.impl.nearcache/ClientMapNearCacheTest/testNearCacheInvalidation_WithLFU_whenMaxSizeExceeded/
