### ISSUE TITLE
BasicClusterStateTest.test_noMigration_whenNodeLeaves_onClusterState_PASSIVE

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#7004]
```
org.junit.runners.model.TestTimedOutException: test timed out after 60000 milliseconds
    at java.lang.Thread.sleep(Native Method)
    at com.hazelcast.test.TestNodeRegistry$MockJoiner.doJoin(TestNodeRegistry.java:221)
    at com.hazelcast.cluster.impl.AbstractJoiner.join(AbstractJoiner.java:103)
    at com.hazelcast.instance.Node.join(Node.java:581)
    at com.hazelcast.instance.Node.start(Node.java:339)
    at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:131)
    at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:160)
    at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:143)
    at com.hazelcast.test.TestHazelcastInstanceFactory.newHazelcastInstance(TestHazelcastInstanceFactory.java:130)
    at com.hazelcast.test.TestHazelcastInstanceFactory.newHazelcastInstance(TestHazelcastInstanceFactory.java:117)
    at com.hazelcast.cluster.impl.BasicClusterStateTest.testNoMigrationWhenNodeLeaves(BasicClusterStateTest.java:366)
    at com.hazelcast.cluster.impl.BasicClusterStateTest.test_noMigration_whenNodeLeaves_onClusterState_PASSIVE(BasicClusterStateTest.java:346)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK8/com.hazelcast$hazelcast/641/testReport/junit/com.hazelcast.cluster.impl/BasicClusterStateTest/test_noMigration_whenNodeLeaves_onClusterState_PASSIVE/

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK1.6/com.hazelcast$hazelcast/746/testReport/junit/com.hazelcast.cluster.impl/BasicClusterStateTest/test_noMigration_whenNodeLeaves_onClusterState_PASSIVE/

**Comment by hasancelik** [comment]
```
org.junit.runners.model.TestTimedOutException: test timed out after 60000 milliseconds
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:196)
	at java.lang.Thread.join(Thread.java:704)
	at java.lang.Thread.join(Thread.java:665)
	at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.awaitTermination(OperationThread.java:214)
	at com.hazelcast.spi.impl.operationexecutor.classic.ClassicOperationExecutor.awaitTermination(ClassicOperationExecutor.java:447)
	at com.hazelcast.spi.impl.operationexecutor.classic.ClassicOperationExecutor.shutdown(ClassicOperationExecutor.java:434)
	at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.shutdown(OperationServiceImpl.java:448)
	at com.hazelcast.spi.impl.NodeEngineImpl.shutdown(NodeEngineImpl.java:357)
	at com.hazelcast.instance.Node.shutdownServices(Node.java:423)
	at com.hazelcast.instance.Node.shutdown(Node.java:397)
	at com.hazelcast.instance.LifecycleServiceImpl.shutdown(LifecycleServiceImpl.java:91)
	at com.hazelcast.instance.HazelcastInstanceProxy.shutdown(HazelcastInstanceProxy.java:251)
	at com.hazelcast.cluster.impl.BasicClusterStateTest.testNoMigrationWhenNodeLeaves(BasicClusterStateTest.java:374)
	at com.hazelcast.cluster.impl.BasicClusterStateTest.test_noMigration_whenNodeLeaves_onClusterState_PASSIVE(BasicClusterStateTest.java:357)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.6/com.hazelcast$hazelcast/783/testReport/junit/com.hazelcast.cluster.impl/BasicClusterStateTest/test_noMigration_whenNodeLeaves_onClusterState_PASSIVE/

**Comment by Donnerbart** [comment]
Failed again in a PR builder with different assertion:
```
java.lang.AssertionError: Cluster size is not correct. Expected: 2 Actual: 1
	at org.junit.Assert.fail(Assert.java:88)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSize(HazelcastTestSupport.java:859)
	at com.hazelcast.test.HazelcastTestSupport$12.run(HazelcastTestSupport.java:878)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:992)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:874)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:869)
	at com.hazelcast.internal.cluster.impl.BasicClusterStateTest.testNoMigrationWhenNodeLeaves(BasicClusterStateTest.java:379)
	at com.hazelcast.internal.cluster.impl.BasicClusterStateTest.test_noMigration_whenNodeLeaves_onClusterState_PASSIVE(BasicClusterStateTest.java:357)
```
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/new-lab-fast-pr/8394/testReport/junit/com.hazelcast.internal.cluster.impl/BasicClusterStateTest/test_noMigration_whenNodeLeaves_onClusterState_PASSIVE/

**Comment by mmedenjak** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/8409/testReport/junit/com.hazelcast.internal.cluster.impl/BasicClusterStateTest/test_noMigration_whenNodeLeaves_onClusterState_PASSIVE/
