### ISSUE TITLE
ClientInvocationTest.executionCallback_FailOnShutdown

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#7008]
```
java.lang.AssertionError: No requests failed with reason client shutdown, failed to complete within 120 seconds , count left: 1
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:706)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:692)
	at com.hazelcast.client.spi.impl.ClientInvocationTest.executionCallback_FailOnShutdown(ClientInvocationTest.java:149)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance/com.hazelcast$hazelcast-client-new/1093/testReport/junit/com.hazelcast.client.spi.impl/ClientInvocationTest/executionCallback_FailOnShutdown/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-OracleJDK1.6/com.hazelcast$hazelcast-client/319/testReport/junit/com.hazelcast.client.spi.impl/ClientInvocationTest/executionCallback_FailOnShutdown/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: No requests failed with reason client shutdown, failed to complete within 120 seconds , count left: 1
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:706)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:692)
	at com.hazelcast.client.spi.impl.ClientInvocationTest.executionCallback_FailOnShutdown(ClientInvocationTest.java:149)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-ZuluJDK8/com.hazelcast$hazelcast-client-new/19/testReport/junit/com.hazelcast.client.spi.impl/ClientInvocationTest/executionCallback_FailOnShutdown/

**Comment by mesutcelik** [comment]
fixed by https://github.com/hazelcast/hazelcast/commit/42dd3075109d59f1b6847b7a6165b609299cc9d3

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: No requests failed with reason client shutdown, failed to complete within 120 seconds , count left: 1
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:706)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:692)
	at com.hazelcast.client.spi.impl.ClientInvocationTest.executionCallback_FailOnShutdown(ClientInvocationTest.java:149)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-OracleJDK1.6/com.hazelcast$hazelcast-client-new/324/testReport/junit/com.hazelcast.client.spi.impl/ClientInvocationTest/executionCallback_FailOnShutdown/

**Comment by mesutcelik** [comment]
I think that is a build which is executed after the commit... please reopen if it fails again.

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: No requests failed with reason client shutdown, failed to complete within 120 seconds , count left: 1
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:706)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:692)
	at com.hazelcast.client.spi.impl.ClientInvocationTest.executionCallback_FailOnShutdown(ClientInvocationTest.java:149)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-IbmJDK1.6/com.hazelcast$hazelcast-client-new/324/testReport/junit/com.hazelcast.client.spi.impl/ClientInvocationTest/executionCallback_FailOnShutdown/

**Comment by mesutcelik** [comment]
fixed by https://github.com/hazelcast/hazelcast/commit/79ffb37802255d4d7280cde86745bf6e97500928

**Comment by Donnerbart** [comment]
Failed again on fast PR builder:
```
Hazelcast instance is not active!
```
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/new-lab-fast-pr/1249/testReport/junit/com.hazelcast.client.spi.impl/ClientInvocationTest/executionCallback_FailOnShutdown/
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/new-lab-fast-pr/1242/testReport/junit/com.hazelcast.client.spi.impl/ClientInvocationTest/executionCallback_FailOnShutdown/

**Comment by sancar** [comment]
Closing since we could not look into this in time and we don't have any data left related to failure.
