### ISSUE TITLE
ReplicatedMapEntryListenerOnReconnectTest.testListenersSmartRouting

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#7022]
```
org.junit.runners.model.TestTimedOutException: test timed out after 120000 milliseconds
	at java.lang.Thread.sleep(Native Method)
	at java.lang.Thread.sleep(Thread.java:321)
	at java.util.concurrent.TimeUnit.sleep(TimeUnit.java:356)
	at com.hazelcast.test.HazelcastTestSupport.sleepMillis(HazelcastTestSupport.java:254)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:843)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:849)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest.testListenersInternal(AbstractListenersOnReconnectTest.java:72)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest.testListenersSmartRouting(AbstractListenersOnReconnectTest.java:108)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:622)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.lang.Thread.run(Thread.java:701)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-ZuluJDK6/com.hazelcast$hazelcast-client-legacy/43/testReport/junit/com.hazelcast.client.listeners/ReplicatedMapEntryListenerOnReconnectTest/testListenersSmartRouting/

**Comment by ihsandemir** [comment]
Examined the issue. Could not generate it locally in CentOs Linux ZuluJDK6. Inserted a debug log into the test code (https://github.com/hazelcast/hazelcast/pull/7053 ) so that the next time the test fails, we will have some idea about what caused the failure.

**Comment by Donnerbart** [comment]
Test failed again in a fast PR builder:
```
org.junit.runners.model.TestTimedOutException: test timed out after 120000 milliseconds
	at java.lang.Thread.sleep(Native Method)
	at java.lang.Thread.sleep(Thread.java:302)
	at java.util.concurrent.TimeUnit.sleep(TimeUnit.java:328)
	at com.hazelcast.test.HazelcastTestSupport.sleepMillis(HazelcastTestSupport.java:297)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:909)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:915)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest.testListenersInternal(AbstractListenersOnReconnectTest.java:61)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest.testListenersNonSmartRoutingMultipleServer(AbstractListenersOnReconnectTest.java:131)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:88)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:82)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.lang.Thread.run(Thread.java:662)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/3985/testReport/junit/com.hazelcast.client.listeners/ReplicatedMapEntryListenerOnReconnectTest/testListenersNonSmartRoutingMultipleServer/

**Comment by mdogan** [comment]
I've removed 120 seconds test timeout : d6b2a5076403904ac3c57d172e1ad48d8868d9e6 
There's already a global timeout and `assertTrueEventually` also has 120s timeout by default.

Let's see if it's gonna fail again...

**Comment by ihsandemir** [comment]
Could not generate the problem.

PR https://github.com/hazelcast/hazelcast/pull/8765 and https://github.com/hazelcast/hazelcast/pull/8757 may have corrected the problem. Closing for now.
