### ISSUE TITLE
org.hibernate.PropertyAccessException on java.sql.Timestamp

### ISSUE THREAD

**Issue by 0l33l** [hazelcast/hazelcast#7039]
Environment:
* Hazelcast 3.5.4, 3.6-EA2
* Hibernate 3.6.10
* Spring 3.2.15
* One client, single cluster
* Default hazelcast.xml (hazelcast-default.xml)
* Java version "1.7.0_80"
* OS: Ubuntu 14.04 x64 (3.13.0-66-generic), OSX Yosemite

We are converting from ehcache to hazelcast (3.5.4 or 3.6-EA2) with hibernate 3.6.10. 

When we use *com.hazelcast.hibernate.HazelcastCacheRegionFactory* we receive the below error.

Using *HazelcastLocalCacheRegionFactory* is successful.

The superclass definition and our domain object is defined below:
```
@MappedSuperclass
abstract public class AuditableEntityImpl extends EntityImpl implements AuditableEntity {
  @Column(name = "CreationDateTime", nullable = false)
  protected Timestamp creationDateTime = null;

  @Column(name = "LastUpdateDateTime", nullable = true)
  @Version
  protected Timestamp lastUpdateDateTime = null;
}

@Table(name = "Bean")
@Cacheable
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
@javax.persistence.Entity(name = "BeanImpl")
@org.hibernate.annotations.Entity (dynamicUpdate = true, dynamicInsert = true)
public class BeanImpl extends AuditableEntityImpl implements Bean {
  private static final Logger LOG = LoggerFactory.getLogger(BeanImpl.class);

  @Transient
  private short dirty = 0;

  @Id
  @Access(javax.persistence.AccessType.PROPERTY)
  @Column(name = "BeanID", nullable = false)
  private Integer beanID = null;

  @Column(name = "CachingPolicyCV", nullable = false, length = 2)
  @Type(type = "com.setgen.gen.dao.hibernate.type.CachingPolicyUserType")
  private CachingPolicy cachingPolicy = null;

}
```

```
Dec 09, 2015 3:18:23 PM org.hibernate.validator.internal.util.Version <clinit>
INFO: HV000001: Hibernate Validator 5.0.0.Final
Dec 09, 2015 3:18:24 PM com.hazelcast.hibernate.HazelcastCacheRegionFactory
INFO: Starting up HazelcastCacheRegionFactory
Dec 09, 2015 3:18:24 PM com.hazelcast.config.XmlConfigLocator
INFO: Loading 'hazelcast-default.xml' from classpath.
Dec 09, 2015 3:18:25 PM com.hazelcast.instance.DefaultAddressPicker
INFO: [LOCAL] [dev] [3.6-EA2] Prefer IPv4 stack is true.
Dec 09, 2015 3:18:25 PM com.hazelcast.instance.DefaultAddressPicker
INFO: [LOCAL] [dev] [3.6-EA2] Picked Address[172.17.42.1]:5701, using socket ServerSocket[addr=/0:0:0:0:0:0:0:0,localport=5701], bind any local is true
Dec 09, 2015 3:18:25 PM com.hazelcast.spi.OperationService
INFO: [172.17.42.1]:5701 [dev] [3.6-EA2] Backpressure is disabled
Dec 09, 2015 3:18:25 PM com.hazelcast.spi.impl.operationexecutor.classic.ClassicOperationExecutor
INFO: [172.17.42.1]:5701 [dev] [3.6-EA2] Starting with 6 generic operation threads and 12 partition operation threads.
Dec 09, 2015 3:18:25 PM com.hazelcast.system
INFO: [172.17.42.1]:5701 [dev] [3.6-EA2] Hazelcast 3.6-EA2 (20151125 - 8af85c5) starting at Address[172.17.42.1]:5701
Dec 09, 2015 3:18:25 PM com.hazelcast.system
INFO: [172.17.42.1]:5701 [dev] [3.6-EA2] Copyright (c) 2008-2015, Hazelcast, Inc. All Rights Reserved.
Dec 09, 2015 3:18:25 PM com.hazelcast.system
INFO: [172.17.42.1]:5701 [dev] [3.6-EA2] Configured Hazelcast Serialization version:1
Dec 09, 2015 3:18:25 PM com.hazelcast.instance.Node
INFO: [172.17.42.1]:5701 [dev] [3.6-EA2] Creating MulticastJoiner
Dec 09, 2015 3:18:25 PM com.hazelcast.core.LifecycleService
INFO: [172.17.42.1]:5701 [dev] [3.6-EA2] Address[172.17.42.1]:5701 is STARTING
Dec 09, 2015 3:18:25 PM com.hazelcast.nio.tcp.nonblocking.NonBlockingIOThreadingModel
INFO: [172.17.42.1]:5701 [dev] [3.6-EA2] TcpIpConnectionManager configured with Non Blocking IO-threading model: 3 input threads and 3 output threads
Dec 09, 2015 3:18:28 PM com.hazelcast.cluster.impl.MulticastJoiner
INFO: [172.17.42.1]:5701 [dev] [3.6-EA2] 


Members [1] {
	Member [172.17.42.1]:5701 this
}

Dec 09, 2015 3:18:28 PM com.hazelcast.core.LifecycleService
INFO: [172.17.42.1]:5701 [dev] [3.6-EA2] Address[172.17.42.1]:5701 is STARTED
Dec 09, 2015 3:18:29 PM com.hazelcast.partition.InternalPartitionService
INFO: [172.17.42.1]:5701 [dev] [3.6-EA2] Initializing cluster partition table arrangement...
Processing Application.xml
Processing Member.xml
Dec 09, 2015 3:18:29 PM com.hazelcast.hibernate.HazelcastCacheRegionFactory
INFO: Shutting down HazelcastCacheRegionFactory
Dec 09, 2015 3:18:29 PM com.hazelcast.core.LifecycleService
INFO: [172.17.42.1]:5701 [dev] [3.6-EA2] Address[172.17.42.1]:5701 is SHUTTING_DOWN
Dec 09, 2015 3:18:29 PM com.hazelcast.instance.Node
INFO: [172.17.42.1]:5701 [dev] [3.6-EA2] Shutting down multicast service...
Dec 09, 2015 3:18:29 PM com.hazelcast.instance.Node
INFO: [172.17.42.1]:5701 [dev] [3.6-EA2] Shutting down connection manager...
Dec 09, 2015 3:18:29 PM com.hazelcast.instance.Node
INFO: [172.17.42.1]:5701 [dev] [3.6-EA2] Shutting down node engine...
Dec 09, 2015 3:18:29 PM com.hazelcast.instance.NodeExtension
INFO: [172.17.42.1]:5701 [dev] [3.6-EA2] Destroying node NodeExtension.
Dec 09, 2015 3:18:29 PM com.hazelcast.instance.Node
INFO: [172.17.42.1]:5701 [dev] [3.6-EA2] Hazelcast Shutdown is completed in 12 ms.
Dec 09, 2015 3:18:29 PM com.hazelcast.core.LifecycleService
INFO: [172.17.42.1]:5701 [dev] [3.6-EA2] Address[172.17.42.1]:5701 is SHUTDOWN
Exception in thread "main" org.hibernate.PropertyAccessException: could not set a field value by reflection setter of com.setgen.gen.domain.BeanImpl.creationDateTime
	at org.hibernate.property.DirectPropertyAccessor$DirectSetter.set(DirectPropertyAccessor.java:151)
	at org.hibernate.tuple.entity.AbstractEntityTuplizer.setPropertyValues(AbstractEntityTuplizer.java:583)
	at org.hibernate.tuple.entity.PojoEntityTuplizer.setPropertyValues(PojoEntityTuplizer.java:229)
	at org.hibernate.persister.entity.AbstractEntityPersister.setPropertyValues(AbstractEntityPersister.java:3848)
	at org.hibernate.cache.entry.CacheEntry.assemble(CacheEntry.java:137)
	at org.hibernate.cache.entry.CacheEntry.assemble(CacheEntry.java:104)
	at org.hibernate.event.def.DefaultLoadEventListener.assembleCacheEntry(DefaultLoadEventListener.java:651)
	at org.hibernate.event.def.DefaultLoadEventListener.loadFromSecondLevelCache(DefaultLoadEventListener.java:605)
	at org.hibernate.event.def.DefaultLoadEventListener.doLoad(DefaultLoadEventListener.java:459)
	at org.hibernate.event.def.DefaultLoadEventListener.load(DefaultLoadEventListener.java:227)
	at org.hibernate.event.def.DefaultLoadEventListener.onLoad(DefaultLoadEventListener.java:147)
	at org.hibernate.impl.SessionImpl.fireLoad(SessionImpl.java:1090)
	at org.hibernate.impl.SessionImpl.immediateLoad(SessionImpl.java:1026)
	at org.hibernate.proxy.AbstractLazyInitializer.initialize(AbstractLazyInitializer.java:176)
	at org.hibernate.Hibernate.initialize(Hibernate.java:414)
	at com.setgen.gen.dao.hibernate.BeanDAOImpl.findByPrimaryKey(BeanDAOImpl.java:219)
	at com.setgen.gen.dao.hibernate.BeanDAOImpl.find(BeanDAOImpl.java:351)
	at com.setgen.gen.dao.hibernate.ReferenceDAOImpl.find(ReferenceDAOImpl.java:307)
	at com.setgen.gen.dao.hibernate.ReferenceDAOImpl.post(ReferenceDAOImpl.java:120)
	at com.setgen.gen.dao.hibernate.ReferenceDAOImpl.post(ReferenceDAOImpl.java:77)
	at com.setgen.gen.sets.Application.ApplicationSetDAOImpl.post(ApplicationSetDAOImpl.java:140)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
	at com.setgen.core.spring.interceptor.DataSetFactoryImpl.invoke(DataSetFactoryImpl.java:83)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:96)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:260)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at com.setgen.core.spring.interceptor.UserCredentialsDataSourceInterceptor.invoke(UserCredentialsDataSourceInterceptor.java:64)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at com.setgen.core.spring.interceptor.ByteArrayToSetInterceptor.invoke(ByteArrayToSetInterceptor.java:20)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
	at com.sun.proxy.$Proxy45.post(Unknown Source)
	at com.setgen.core.DataSetImpl.post(DataSetImpl.java:240)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:198)
	at com.sun.proxy.$Proxy47.post(Unknown Source)
	at com.setgen.gen.input.set.PostSets.doit(PostSets.java:54)
	at com.setgen.gen.input.set.PostSets$2.invoke(PostSets.java:102)
	at com.setgen.services.ApplicationServices.runAsSystem(ApplicationServices.java:357)
	at com.setgen.gen.input.set.PostSets.main(PostSets.java:97)
Caused by: java.lang.IllegalArgumentException: Can not set java.sql.Timestamp field com.setgen.core.AuditableEntityImpl.creationDateTime to java.util.Date
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:164)
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:168)
	at sun.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81)
	at java.lang.reflect.Field.set(Field.java:741)
	at org.hibernate.property.DirectPropertyAccessor$DirectSetter.set(DirectPropertyAccessor.java:139)
	... 51 more
```
```
  <bean id="sessionFactory" class="org.springframework.orm.hibernate3.annotation.AnnotationSessionFactoryBean">
    <property name="dataSource" ref="dataSource"/>
    <property name="entityInterceptor">
		  <bean class="com.setgen.core.hibernate.ReadOnlyEntityInterceptor">
		    <property name="readOnlyEntities">
		      <list>
		      </list>
		    </property>
		  </bean>
    </property>
    <property name="annotatedClasses">
      <list>
            <value>com.setgen.gen.domain.BeanImpl</value>
      </list>
    </property>
    <property name="hibernateProperties">
      <props>
        <prop key="hibernate.dialect">org.hibernate.dialect.HSQLDialect</prop>  
        <prop key="hibernate.autocommit">false</prop>
        <prop key="hibernate.cache.region.factory_class">com.hazelcast.hibernate.HazelcastCacheRegionFactory</prop>
        <prop key="hibernate.cache.use_query_cache">true</prop>
        <prop key="hibernate.jdbc.batch_size">0</prop>
      </props>
    </property>
  </bean>
```

**Comment by 0l33l** [comment]
This has been fixed in 3.6-RC1.
