### ISSUE TITLE
CacheSplitBrainTest.testPassThroughCacheMergePolicy

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#7042]
```
java.lang.IllegalStateException: Partitions can't be assigned since cluster-state: FROZEN
    at com.hazelcast.spi.impl.operationservice.impl.Invocation.notifyWithExceptionWhenTargetIsNull(Invocation.java:341)
    at com.hazelcast.spi.impl.operationservice.impl.Invocation.initInvocationTarget(Invocation.java:304)
    at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:234)
    at com.hazelcast.spi.impl.operationservice.impl.Invocation.invokeInternal(Invocation.java:210)
    at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:180)
    at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.invokeOnPartition(OperationServiceImpl.java:314)
    at com.hazelcast.cache.impl.AbstractInternalCacheProxy.invoke(AbstractInternalCacheProxy.java:113)
    at com.hazelcast.cache.impl.AbstractInternalCacheProxy.invoke(AbstractInternalCacheProxy.java:134)
    at com.hazelcast.cache.impl.AbstractInternalCacheProxy.putAsyncInternal(AbstractInternalCacheProxy.java:193)
    at com.hazelcast.cache.impl.AbstractCacheProxy.put(AbstractCacheProxy.java:200)
    at com.hazelcast.cache.impl.CacheProxy.put(CacheProxy.java:75)
    at com.hazelcast.cache.impl.CacheProxy.put(CacheProxy.java:135)
    at com.hazelcast.cache.merge.CacheSplitBrainTest.testPassThroughCacheMergePolicy(CacheSplitBrainTest.java:238)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/796/testReport/junit/com.hazelcast.cache.merge/CacheSplitBrainTest/testPassThroughCacheMergePolicy/

**Comment by mdogan** [comment]
Problem here is, `cache.put()` is invoked while clusters just started merging. Tests in this class don't guarantee that these puts are done before nodes get merged. 
A quick solution for the test will be to assign partitions at the beginning.

**Comment by serkan-ozal** [comment]
you mean warm-up partitions at the beginning?

**Comment by mdogan** [comment]
yes. that way partitions will be already assigned even if put is invoked during merge.

**Comment by serkan-ozal** [comment]
@mdogan 

Also besides this, for preventing put during merge as I mentioned in the comment

```
// TODO We assume that until here and also while doing get/put, cluster is still splitted.
// This assumptions seems fragile due to time sensitivity.
```

What about adding a lifecycle listener and blocking (by a simple volatile field) when there is a `MERGING` event and after puts are completed, notify it to continue?

**Comment by mdogan** [comment]
sounds good to ensure doing put before merge. but still partition warm up before split is required, partitions cannot be assigned during merge (cluster will be frozen).

**Comment by serkan-ozal** [comment]
yes, it is just for ensuring put is done before merge.

**Comment by hasancelik** [comment]
```
org.junit.ComparisonFailure: expected:<[passThroughV]alue> but was:<[v]alue>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.cache.merge.CacheSplitBrainTest.testPassThroughCacheMergePolicy(CacheSplitBrainTest.java:265)
```

https://hazelcast-l337.ci.cloudbees.com/view/Sonar/job/Hazelcast-3.x-sonar/com.hazelcast$hazelcast/1403/testReport/junit/com.hazelcast.cache.merge/CacheSplitBrainTest/testPassThroughCacheMergePolicy/
