### ISSUE TITLE
ClientServiceTest.testClientListener

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#7044]
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.client.ClientServiceTest.testClientListener(ClientServiceTest.java:219)
```

https://hazelcast-l337.ci.cloudbees.com/view/Quality-Outreach/job/Hazelcast-3.x-OpenJDK8-Quality-Outreach/com.hazelcast$hazelcast-client/266/testReport/junit/com.hazelcast.client/ClientServiceTest/testClientListener/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.client.ClientServiceTest.testClientListener(ClientServiceTest.java:220)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/802/testReport/com.hazelcast.topic.impl.reliable/ReliableTopicStressTest/test/

**Comment by cangencer** [comment]
@hasancelik I don't think this failure is related to the test in this issue?

**Comment by ihsandemir** [comment]
@hasancelik last test report is as @cangencer mentioned belongs to ReliableTopicStressTest.

**Comment by hasancelik** [comment]
@cangencer @ihsandemir sorry guys. I updated the link.
