### ISSUE TITLE
BasicClusterStateTest.test_noMigration_whenNodeLeaves_onClusterState_FROZEN

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#7095]
```
org.junit.runners.model.TestTimedOutException: test timed out after 60000 milliseconds
	at java.lang.Thread.sleep(Native Method)
	at com.hazelcast.partition.impl.InternalPartitionServiceImpl.sleepWithBusyWait(InternalPartitionServiceImpl.java:1204)
	at com.hazelcast.partition.impl.InternalPartitionServiceImpl.prepareToSafeShutdown(InternalPartitionServiceImpl.java:1150)
	at com.hazelcast.instance.Node.shutdown(Node.java:368)
	at com.hazelcast.instance.LifecycleServiceImpl.shutdown(LifecycleServiceImpl.java:91)
	at com.hazelcast.instance.HazelcastInstanceProxy.shutdown(HazelcastInstanceProxy.java:251)
	at com.hazelcast.cluster.impl.BasicClusterStateTest.testNoMigrationWhenNodeLeaves(BasicClusterStateTest.java:373)
	at com.hazelcast.cluster.impl.BasicClusterStateTest.test_noMigration_whenNodeLeaves_onClusterState_FROZEN(BasicClusterStateTest.java:343)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/new-lab-fast-pr/613/testReport/junit/com.hazelcast.cluster.impl/BasicClusterStateTest/test_noMigration_whenNodeLeaves_onClusterState_FROZEN/

**Comment by mdogan** [comment]
I guess there's an issue with (graceful) shutdown.
```
09:18:04,527  INFO |test_noMigration_whenNodeLeaves_onClusterState_FROZEN| - [InternalPartitionService] Time-limited test - [127.0.0.1]:5067 [dev] [3.6-RC2-SNAPSHOT] Processing replica sync requests: 2
...
09:18:22,531  INFO |test_noMigration_whenNodeLeaves_onClusterState_FROZEN| - [InternalPartitionService] Time-limited test - [127.0.0.1]:5067 [dev] [3.6-RC2-SNAPSHOT] Processing replica sync requests: 2
...
09:18:23,531  INFO |test_noMigration_whenNodeLeaves_onClusterState_FROZEN| - [InternalPartitionService] Time-limited test - [127.0.0.1]:5067 [dev] [3.6-RC2-SNAPSHOT] Processing replica sync requests: 2
...
09:18:24,531  INFO |test_noMigration_whenNodeLeaves_onClusterState_FROZEN| - [InternalPartitionService] Time-limited test - [127.0.0.1]:5067 [dev] [3.6-RC2-SNAPSHOT] Processing replica sync requests: 2
```

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.6/com.hazelcast$hazelcast/783/testReport/junit/com.hazelcast.cluster.impl/BasicClusterStateTest/test_noMigration_whenNodeLeaves_onClusterState_FROZEN/

**Comment by hasancelik** [comment]
```
org.junit.runners.model.TestTimedOutException: test timed out after 60000 milliseconds
	at java.lang.Thread.sleep(Native Method)
	at com.hazelcast.cluster.impl.AbstractJoiner.ensureConnectionToAllMembers(AbstractJoiner.java:141)
	at com.hazelcast.cluster.impl.AbstractJoiner.postJoin(AbstractJoiner.java:123)
	at com.hazelcast.cluster.impl.AbstractJoiner.join(AbstractJoiner.java:104)
	at com.hazelcast.instance.Node.join(Node.java:581)
	at com.hazelcast.instance.Node.start(Node.java:339)
	at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:131)
	at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:160)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:143)
	at com.hazelcast.test.TestHazelcastInstanceFactory.newHazelcastInstance(TestHazelcastInstanceFactory.java:137)
	at com.hazelcast.test.TestHazelcastInstanceFactory.newHazelcastInstance(TestHazelcastInstanceFactory.java:123)
	at com.hazelcast.cluster.impl.BasicClusterStateTest.testNoMigrationWhenNodeLeaves(BasicClusterStateTest.java:377)
	at com.hazelcast.cluster.impl.BasicClusterStateTest.test_noMigration_whenNodeLeaves_onClusterState_FROZEN(BasicClusterStateTest.java:352)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-ZuluJDK8/com.hazelcast$hazelcast/71/testReport/junit/com.hazelcast.cluster.impl/BasicClusterStateTest/test_noMigration_whenNodeLeaves_onClusterState_FROZEN/

**Comment by metanet** [comment]
fixed via https://github.com/hazelcast/hazelcast/commit/8c32a87348a2997880b4698a6365697db8b47842
