### ISSUE TITLE
MigrationAwareServiceTest.testPartitionDataSize_whenBackupNodesTerminated_withThreeBackups & withTwoBackups

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#7104]
**withThreeBackups**
```
java.lang.AssertionError: expected:<1084> but was:<1033>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.spi.MigrationAwareServiceTest$3.run(MigrationAwareServiceTest.java:222)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:835)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:849)
	at com.hazelcast.spi.MigrationAwareServiceTest.assertSize(MigrationAwareServiceTest.java:211)
	at com.hazelcast.spi.MigrationAwareServiceTest.testPartitionDataSize_whenBackupNodesTerminated(MigrationAwareServiceTest.java:147)
	at com.hazelcast.spi.MigrationAwareServiceTest.testPartitionDataSize_whenBackupNodesTerminated_withThreeBackups(MigrationAwareServiceTest.java:135)
```

**withTwoBackups**
```
java.lang.AssertionError: expected:<813> but was:<799>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.spi.MigrationAwareServiceTest$3.run(MigrationAwareServiceTest.java:222)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:835)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:849)
	at com.hazelcast.spi.MigrationAwareServiceTest.assertSize(MigrationAwareServiceTest.java:211)
	at com.hazelcast.spi.MigrationAwareServiceTest.testPartitionDataSize_whenBackupNodesTerminated(MigrationAwareServiceTest.java:147)
	at com.hazelcast.spi.MigrationAwareServiceTest.testPartitionDataSize_whenBackupNodesTerminated_withTwoBackups(MigrationAwareServiceTest.java:130)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK1.7/333/

**Comment by mesutcelik** [comment]
merged into https://github.com/hazelcast/hazelcast/issues/5393
