### ISSUE TITLE
CacheBasicServerTest.testIteratorDuringRemoval_withEviction

### ISSUE THREAD

**Issue by serkan-ozal** [hazelcast/hazelcast#7144]
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:196)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.pollResponse(InvocationFuture.java:300)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.waitForResponse(InvocationFuture.java:245)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.get(InvocationFuture.java:222)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.get(InvocationFuture.java:202)
	at com.hazelcast.cache.impl.AbstractCacheProxy.put(AbstractCacheProxy.java:202)
	at com.hazelcast.cache.impl.CacheProxy.put(CacheProxy.java:75)
	at com.hazelcast.cache.impl.CacheProxy.put(CacheProxy.java:135)
	at com.hazelcast.cache.CacheBasicAbstractTest.testIteratorDuringRemoval(CacheBasicAbstractTest.java:425)
	at com.hazelcast.cache.CacheBasicAbstractTest.testIteratorDuringRemoval_withEviction(CacheBasicAbstractTest.java:469)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:60)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:37)
	at java.lang.reflect.Method.invoke(Method.java:611)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:314)
	at java.util.concurrent.FutureTask.run(FutureTask.java:149)
	at java.lang.Thread.run(Thread.java:767)
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.6/785/

**Comment by serkan-ozal** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.6/785/

**Comment by serkan-ozal** [comment]
When I have looked at the logs, I have noticed that there are so so many threads not terminated from `OutOfMemoryHandlerHelperTest` and `OutOfMemoryHandlerTest`. 

Then I have looked at the tests, I have seen that created instances are not shutdown.

**Comment by serkan-ozal** [comment]
Should be fixed via https://github.com/hazelcast/hazelcast/commit/a41f3929bb795caedbbbaee9c8e8474c72dc9708
