### ISSUE TITLE
ClientReconnectTest.testRequestShouldFailOnShutdown

### ISSUE THREAD

**Issue by sancar** [hazelcast/hazelcast#7181]
```
Error Message

Unexpected exception, expected<com.hazelcast.client.HazelcastClientNotActiveException> but was<java.util.concurrent.RejectedExecutionException>
Stacktrace

java.lang.Exception: Unexpected exception, expected<com.hazelcast.client.HazelcastClientNotActiveException> but was<java.util.concurrent.RejectedExecutionException>
	at com.hazelcast.client.spi.impl.ClientExecutionServiceImpl$1.rejectedExecution(ClientExecutionServiceImpl.java:59)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:768)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:656)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:78)
	at com.hazelcast.client.spi.impl.ClientExecutionServiceImpl.submitInternal(ClientExecutionServiceImpl.java:80)
	at com.hazelcast.client.spi.impl.ClientInvocation$1.run(ClientInvocation.java:245)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)
	at ------ End remote and begin local stack-trace ------.(Unknown Source)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveException(ClientInvocationFuture.java:176)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveResponse(ClientInvocationFuture.java:161)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.get(ClientInvocationFuture.java:128)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.get(ClientInvocationFuture.java:103)
	at com.hazelcast.client.spi.ClientProxy.invoke(ClientProxy.java:130)
	at com.hazelcast.client.proxy.ClientMapProxy.get(ClientMapProxy.java:198)
	at com.hazelcast.client.ClientReconnectTest.testRequestShouldFailOnShutdown(ClientReconnectTest.java:139)
```

**Comment by hasancelik** [comment]
fixed by #7183
