### ISSUE TITLE
WriteBehindFlushTest.testWriteBehindQueues_emptied_onBackupNodes

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#7182]
```
java.lang.AssertionError: expected:<0> but was:<49>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.map.impl.mapstore.writebehind.WriteBehindFlushTest.assertWriteBehindQueuesEmpty(WriteBehindFlushTest.java:92)
	at com.hazelcast.map.impl.mapstore.writebehind.WriteBehindFlushTest.testWriteBehindQueues_emptied_onBackupNodes(WriteBehindFlushTest.java:87)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK1.7/com.hazelcast$hazelcast/340/testReport/junit/com.hazelcast.map.impl.mapstore.writebehind/WriteBehindFlushTest/testWriteBehindQueues_emptied_onBackupNodes/

**Comment by hasancelik** [comment]
```java.lang.AssertionError: expected:<0> but was:<19>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.map.impl.mapstore.writebehind.WriteBehindFlushTest.assertWriteBehindQueuesEmpty(WriteBehindFlushTest.java:92)
	at com.hazelcast.map.impl.mapstore.writebehind.WriteBehindFlushTest.testWriteBehindQueues_emptied_onBackupNodes(WriteBehindFlushTest.java:87)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK8/lastCompletedBuild/com.hazelcast$hazelcast/testReport/com.hazelcast.map.impl.mapstore.writebehind/WriteBehindFlushTest/testWriteBehindQueues_emptied_onBackupNodes/

**Comment by ahmetmircik** [comment]
closed via https://github.com/hazelcast/hazelcast/commit/14520904ee7fad852e9c147f7ec2ed6d515f6321

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: expected:<0> but was:<7>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.map.impl.mapstore.writebehind.WriteBehindFlushTest.assertWriteBehindQueuesEmpty(WriteBehindFlushTest.java:106)
	at com.hazelcast.map.impl.mapstore.writebehind.WriteBehindFlushTest.testWriteBehindQueues_emptied_onBackupNodes(WriteBehindFlushTest.java:101)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-ZuluJDK7/com.hazelcast$hazelcast/65/testReport/junit/com.hazelcast.map.impl.mapstore.writebehind/WriteBehindFlushTest/testWriteBehindQueues_emptied_onBackupNodes/

**Comment by ahmetmircik** [comment]
closed via https://github.com/hazelcast/hazelcast/commit/8df2c0611ba33b95862b1f8bcc5e8cec63953f3b

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: expected:<0> but was:<1>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.map.impl.mapstore.writebehind.WriteBehindFlushTest$2.run(WriteBehindFlushTest.java:140)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:850)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:867)
	at com.hazelcast.map.impl.mapstore.writebehind.WriteBehindFlushTest.assertWriteBehindQueuesEmpty(WriteBehindFlushTest.java:136)
	at com.hazelcast.map.impl.mapstore.writebehind.WriteBehindFlushTest.testWriteBehindQueues_emptied_onBackupNodes(WriteBehindFlushTest.java:103)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-OracleJDK8/com.hazelcast$hazelcast/700/testReport/junit/com.hazelcast.map.impl.mapstore.writebehind/WriteBehindFlushTest/testWriteBehindQueues_emptied_onBackupNodes/
