### ISSUE TITLE
CacheBasicClientTest.testIteratorDuringRemoval

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#7184]
```
java.util.NoSuchElementException: null
	at com.hazelcast.cache.impl.AbstractClusterWideIterator.next(AbstractClusterWideIterator.java:123)
	at com.hazelcast.cache.impl.AbstractClusterWideIterator.next(AbstractClusterWideIterator.java:75)
	at com.hazelcast.cache.CacheBasicAbstractTest.testIteratorDuringRemoval(CacheBasicAbstractTest.java:423)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:134)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at com.hazelcast.test.HazelcastParallelClassRunner.access$201(HazelcastParallelClassRunner.java:29)
	at com.hazelcast.test.HazelcastParallelClassRunner$TestRunner.run(HazelcastParallelClassRunner.java:89)
	at java.lang.Thread.run(Thread.java:745)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-ZuluJDK8/com.hazelcast$hazelcast-client-new/22/testReport/junit/com.hazelcast.client.cache/CacheBasicClientTest/testIteratorDuringRemoval/

**Comment by serkan-ozal** [comment]
fixed via https://github.com/hazelcast/hazelcast/commit/d6f7b44fee0657e1825e10b5d91084713be969a2
