### ISSUE TITLE
ClusterRollingRestartTest.test_rollingRestart[clusterState:FROZEN,partitionAssignmentType:NEVER]

### ISSUE THREAD

**Issue by metanet** [hazelcast/hazelcast#7191]
```
java.lang.AssertionError: Cluster size is not correct. Expected: 3 Actual: 1
	at org.junit.Assert.fail(Assert.java:88)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSize(HazelcastTestSupport.java:694)
	at com.hazelcast.test.HazelcastTestSupport$10.run(HazelcastTestSupport.java:713)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:835)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:709)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:704)
	at com.hazelcast.cluster.impl.ClusterRollingRestartTest.test_rollingRestart(ClusterRollingRestartTest.java:86)
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.8/78/com.hazelcast$hazelcast/testReport/com.hazelcast.cluster.impl/ClusterRollingRestartTest/test_rollingRestart_clusterState_FROZEN_partitionAssignmentType_NEVER_/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: Cluster size is not correct. Expected: 3 Actual: 1
	at org.junit.Assert.fail(Assert.java:88)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSize(HazelcastTestSupport.java:696)
	at com.hazelcast.test.HazelcastTestSupport$10.run(HazelcastTestSupport.java:715)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:851)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:711)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:706)
	at com.hazelcast.internal.cluster.impl.ClusterRollingRestartTest.test_rollingRestart(ClusterRollingRestartTest.java:86)
```
https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK1.8/com.hazelcast$hazelcast/119/testReport/junit/com.hazelcast.internal.cluster.impl/ClusterRollingRestartTest/test_rollingRestart_clusterState_FROZEN_partitionAssignmentType_NEVER_/

**Comment by mdogan** [comment]
Failure is because of mock connection & joiner mechanism. Restarting node is not able to rejoin to the former cluster.

**Comment by mdogan** [comment]
See https://github.com/hazelcast/hazelcast/issues/7463

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: Cluster size is not correct. Expected: 3 Actual: 1
	at org.junit.Assert.fail(Assert.java:88)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSize(HazelcastTestSupport.java:696)
	at com.hazelcast.test.HazelcastTestSupport$10.run(HazelcastTestSupport.java:715)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:851)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:711)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:706)
	at com.hazelcast.cluster.impl.ClusterRollingRestartTest.test_rollingRestart(ClusterRollingRestartTest.java:86)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.maintenance-IbmJDK1.8/com.hazelcast$hazelcast/49/testReport/junit/com.hazelcast.cluster.impl/ClusterRollingRestartTest/test_rollingRestart_clusterState_FROZEN_partitionAssignmentType_NEVER_/

**Comment by mdogan** [comment]
@hasancelik: Reason of failure is mock joiner, please see issue: #7463

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: Cluster size is not correct. Expected: 3 Actual: 2
	at org.junit.Assert.fail(Assert.java:88)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSize(HazelcastTestSupport.java:702)
	at com.hazelcast.test.HazelcastTestSupport$10.run(HazelcastTestSupport.java:721)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:857)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:717)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:712)
	at com.hazelcast.internal.cluster.impl.ClusterRollingRestartTest.test_rollingRestart(ClusterRollingRestartTest.java:87)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.8/com.hazelcast$hazelcast/209/testReport/junit/com.hazelcast.internal.cluster.impl/ClusterRollingRestartTest/test_rollingRestart_clusterState_FROZEN_partitionAssignmentType_NEVER_/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: Cluster size is not correct. Expected: 3 Actual: 2
	at org.junit.Assert.fail(Assert.java:88)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSize(HazelcastTestSupport.java:720)
	at com.hazelcast.test.HazelcastTestSupport$10.run(HazelcastTestSupport.java:739)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:875)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:735)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:730)
	at com.hazelcast.internal.cluster.impl.ClusterRollingRestartTest.test_rollingRestart(ClusterRollingRestartTest.java:87)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.8/com.hazelcast$hazelcast/236/testReport/junit/com.hazelcast.internal.cluster.impl/ClusterRollingRestartTest/test_rollingRestart_clusterState_FROZEN_partitionAssignmentType_NEVER_/

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.8/237/com.hazelcast$hazelcast/testReport/com.hazelcast.internal.cluster.impl/ClusterRollingRestartTest/test_rollingRestart_clusterState_FROZEN_partitionAssignmentType_NEVER_/

**Comment by hasancelik** [comment]
**maintenance**
```
java.lang.AssertionError: Cluster size is not correct. Expected: 3 Actual: 1
	at org.junit.Assert.fail(Assert.java:88)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSize(HazelcastTestSupport.java:696)
	at com.hazelcast.test.HazelcastTestSupport$10.run(HazelcastTestSupport.java:715)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:851)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:711)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:706)
	at com.hazelcast.cluster.impl.ClusterRollingRestartTest.test_rollingRestart(ClusterRollingRestartTest.java:86)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.maintenance-IbmJDK1.8/com.hazelcast$hazelcast/98/testReport/junit/com.hazelcast.cluster.impl/ClusterRollingRestartTest/test_rollingRestart_clusterState_FROZEN_partitionAssignmentType_NEVER_/

**Comment by mdogan** [comment]
Last failure was related to issues in mock joiner. We won't fix them in maintenance.
