### ISSUE TITLE
ClientMapNearCacheTest.testAfterSubmitToKeyKeyIsInvalidatedFromNearCache[batchInvalidationEnabled:true]

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#7194]
```
java.lang.AssertionError: expected:<999> but was:<900>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.client.map.impl.nearcache.ClientMapNearCacheTest.assertThatOwnedEntryCountEquals(ClientMapNearCacheTest.java:986)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-OracleJDK8/com.hazelcast$hazelcast-client/664/testReport/junit/com.hazelcast.client.map.impl.nearcache/ClientMapNearCacheTest/testAfterSubmitToKeyKeyIsInvalidatedFromNearCache_batchInvalidationEnabled_true_/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/view/Quality-Outreach/job/Hazelcast-3.x-OpenJDK8-Quality-Outreach/com.hazelcast$hazelcast-client-legacy/282/testReport/junit/com.hazelcast.client.map.impl.nearcache/ClientMapNearCacheTest/testAfterExecuteOnKeyKeyIsInvalidatedFromNearCache_batchInvalidationEnabled_true_/
