### ISSUE TITLE
Multicast and large HZ xml files don't work

### ISSUE THREAD

**Issue by pveentjer** [hazelcast/hazelcast#7198]
As part of multicast discovery, the HZ xml file is send to the other member. This leads to problems when the HZ xml is big.

```
    2015-12-16 00:46:00,296 WARNING [com.hazelcast.cluster.impl.MulticastService] (default task-59) [192.168.3.14]:5701 [dev] [3.5.3] You probably have too long Hazelcast configuration!: java.io.IOException: Operation not permitted

    	at java.net.PlainDatagramSocketImpl.send(Native Method) [rt.jar:1.7.0_45]

    	at java.net.DatagramSocket.send(DatagramSocket.java:676) [rt.jar:1.7.0_45]

    	at com.hazelcast.cluster.impl.MulticastService.send(MulticastService.java:184) [hazelcast-3.5.3.jar:3.5.3]

    	at com.hazelcast.cluster.impl.MulticastJoiner.findMasterWithMulticast(MulticastJoiner.java:150) [hazelcast-3.5.3.jar:3.5.3]

    	at com.hazelcast.cluster.impl.MulticastJoiner.doJoin(MulticastJoiner.java:56) [hazelcast-3.5.3.jar:3.5.3]

    	at com.hazelcast.cluster.impl.AbstractJoiner.join(AbstractJoiner.java:93) [hazelcast-3.5.3.jar:3.5.3]

    	at com.hazelcast.instance.Node.join(Node.java:534) [hazelcast-3.5.3.jar:3.5.3]

    	at com.hazelcast.instance.Node.start(Node.java:343) [hazelcast-3.5.3.jar:3.5.3]

    	at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:126) [hazelcast-3.5.3.jar:3.5.3]

    	at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:152) [hazelcast-3.5.3.jar:3.5.3]
```

**Comment by jerrinot** [comment]
is this something we can fix in a patch release? the problem is part(?) of the configuration are send in the multicast datagram? can we change it and still maintain wire-level compatibility?

**Comment by jerrinot** [comment]
this PR probably contributed to this issue: #5609

as now the `JoinMessage` contains a full member list - if there are many members then the serialized message exceed MTU(?) and the datagram won't be sent?

**Comment by pveentjer** [comment]
I think you can't fix it in a patch release because it would require a change in the wire communication.

Imho it would be best to allow for a basic 'discovery' using multicast. Once a node is discovered, connect to it using regular tcp traffic and as part of the handshaking you figure out of there are any conflicts or other reasons to reject (e.g. password).

Currently the JoinMessage contains parts of the configuration, e.g. for each map. See ConfigCheck object.

**Comment by suchithjn225** [comment]
Hello, may I work on this issue?

**Comment by kwart** [comment]
Management center UI tests are hitting this issue. The tests run in docker on the `lab` machine. I don't see the exception when I execute it in docker locally.

Hazelcast XML is not sent as part of the discovery. Just a relatively small ConfigCheck.

Some other reports over the net suggest this issue is rather related to underlying system configuration (limiting rate of multicast datagrams sent):
* https://stackoverflow.com/questions/23859164/linux-udp-socket-sendto-operation-not-permitted
* https://github.com/netty/netty/issues/1258

**Comment by kwart** [comment]
Rarely I reproduce the problem locally when using similar code as listed in https://stackoverflow.com/a/28099592/653069.
My version uses `MulticastSocket` and Hazelcast-like configuration.

**Comment by kwart** [comment]
I see the issue is discussed over the internet and the problem is a pace of sending multicast messages. Users may hit it for instance when they start several Hazelcast members at once.

Great discussion around this topic is in following google group:
* https://groups.google.com/forum/#!msg/comp.protocols.tcp-ip/Qou9Sfgr77E/mVQAPaeI-VUJ

I was not able to reproduce the issue when running the reproducer using strace. Nevertheless the problem seems to be in a native `<sys/socket.h>` call:
```
ssize_t sendto(int sockfd, const void *buf, size_t len, int flags,
                      const struct sockaddr *dest_addr, socklen_t addrlen);
```

The call chain:
1. https://github.com/frohoff/jdk8u-dev-jdk/blob/jdk8u60-b10/src/solaris/classes/java/net/PlainDatagramSocketImpl.java#L75
1. https://github.com/frohoff/jdk8u-dev-jdk/blob/jdk8u60-b10/src/solaris/native/java/net/PlainDatagramSocketImpl.c#L456-L457
1. https://github.com/frohoff/jdk8u-dev-jdk/blob/jdk8u60-b10/src/solaris/native/java/net/linux_close.c#L297

I will update the exception message to describe better the problem.
