### ISSUE TITLE
InternalPartitionServiceLiteMemberTest failures

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#7209]
**test_liteMemberCanShutdownSafely_whenDataMemberExistsInCluster
test_liteMemberCanShutdownSafely_withClusterSize2**

```
org.junit.runners.model.TestTimedOutException: test timed out after 30000 milliseconds
	at com.hazelcast.spi.impl.NodeEngineImpl.<init>(NodeEngineImpl.java:108)
	at com.hazelcast.instance.Node.<init>(Node.java:176)
	at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:125)
	at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:160)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:143)
	at com.hazelcast.test.TestHazelcastInstanceFactory.newHazelcastInstance(TestHazelcastInstanceFactory.java:112)
	at com.hazelcast.test.TestHazelcastInstanceFactory.newHazelcastInstance(TestHazelcastInstanceFactory.java:99)
	at com.hazelcast.partition.impl.InternalPartitionServiceLiteMemberTest.test_liteMemberCanShutdownSafely_whenDataMemberExistsInCluster(InternalPartitionServiceLiteMemberTest.java:266)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK1.7/com.hazelcast$hazelcast/345/

**Comment by metanet** [comment]
I don't think that this failures have a relationship with lite members. In these failures, nodes failed to start before the timeout duration. 

Increased timeout duration with the given commit https://github.com/hazelcast/hazelcast/commit/eff36adf11064a1fb201d98654e8a6d72e912c15
