### ISSUE TITLE
Select_TcpIpConnection_TransferStressTest.testLargePackets

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#7210]
```
java.lang.AssertionError: Thread WriteThread-1 is still alive
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at com.hazelcast.test.TestThread$1.run(TestThread.java:52)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:835)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:849)
	at com.hazelcast.test.TestThread.assertTerminates(TestThread.java:49)
	at com.hazelcast.test.TestThread.assertSucceedsEventually(TestThread.java:61)
	at com.hazelcast.nio.tcp.TcpIpConnection_TransferStressBaseTest.test(TcpIpConnection_TransferStressBaseTest.java:84)
	at com.hazelcast.nio.tcp.TcpIpConnection_TransferStressBaseTest.testLargePackets(TcpIpConnection_TransferStressBaseTest.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:88)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:82)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.lang.Thread.run(Thread.java:745)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/816/testReport/junit/com.hazelcast.nio.tcp.nonblocking/Select_TcpIpConnection_TransferStressTest/testLargePackets/

**Comment by serkan-ozal** [comment]
should be fixed via https://github.com/hazelcast/hazelcast/commit/6ea8e13afd15692eb9b8da8d785677d054d7b258

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: expected:<1186047> but was:<1180602>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.nio.tcp.TcpIpConnection_TransferStressBaseTest$1.run(TcpIpConnection_TransferStressBaseTest.java:98)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:850)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:864)
	at com.hazelcast.nio.tcp.TcpIpConnection_TransferStressBaseTest.test(TcpIpConnection_TransferStressBaseTest.java:95)
	at com.hazelcast.nio.tcp.TcpIpConnection_TransferStressBaseTest.testLargePackets(TcpIpConnection_TransferStressBaseTest.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:88)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:82)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.lang.Thread.run(Thread.java:745)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/825/testReport/junit/com.hazelcast.nio.tcp.nonblocking/Select_TcpIpConnection_TransferStressTest/testLargePackets/

**Comment by serkan-ozal** [comment]
Closing this one after this PR #7278 merged. We can investigate the test failure if it fails again.

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: expected:<1611557> but was:<1606531>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.nio.tcp.TcpIpConnection_TransferStressBaseTest$1.run(TcpIpConnection_TransferStressBaseTest.java:98)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:850)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:864)
	at com.hazelcast.nio.tcp.TcpIpConnection_TransferStressBaseTest.test(TcpIpConnection_TransferStressBaseTest.java:95)
	at com.hazelcast.nio.tcp.TcpIpConnection_TransferStressBaseTest.testLargePackets(TcpIpConnection_TransferStressBaseTest.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:88)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:82)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.lang.Thread.run(Thread.java:745)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/832/testReport/junit/com.hazelcast.nio.tcp.nonblocking/Select_TcpIpConnection_TransferStressTest/testLargePackets/

**Comment by serkan-ozal** [comment]
There is a problem with the test itself. 
In `TcpIpConnection_TransferStressBaseTest.java`, there is an `AtomicBoolean` typed `stop` field which is not reset (updated to `false`) after each test.

**Comment by mdogan** [comment]
@serkan-ozal: `stop` field is not static, hence no need to reset it. Each test creates/uses its own instance.

**Comment by serkan-ozal** [comment]
ah, ok, I didn't know that serial class runner creates different instances of the test. I thought that it is specific to parallel runner. I had noticed this reset problem while repeating the test method itself.
