### ISSUE TITLE
Exception on cache population in HZ 3.6-EA3

### ISSUE THREAD

**Issue by dsukhoroslov** [hazelcast/hazelcast#7220]
When my app starts it populate several caches with config data. In HZ 3.6-EA3 I see a number of exception on start like the following:

<code>

фхъ 31, 2015 2:24:09 PM com.hazelcast.map.impl.MapKeyLoader$LoadFinishedFuture
 SEVERE: Failed asynchronous execution of execution callback: com.hazelcast.map.impl.operation.PartitionCheckIfLoadedOperation$CallbackResponseSender@5bc305bdfor call class com.hazelcast.map.impl.MapKeyLoader$LoadFinishedFuture
 com.hazelcast.spi.exception.ResponseAlreadySentException: NormalResponse already responseReceived for callback: Invocation{serviceName='hz:impl:mapService', op=com.hazelcast.map.impl.operation.PartitionCheckIfLoadedOperation{serviceName='hz:impl:mapService', partitionId=263, replicaIndex=0, callId=0, invocationTime=1451561049718 (Thu Dec 31 14:24:09 MSK 2015), waitTimeout=-1, callTimeout=60000, name=users}, partitionId=263, replicaIndex=0, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeout=60000, target=Address[127.0.0.1]:5871, backupsExpected=0, backupsCompleted=0, connection=null}, current-response: : true
     at com.hazelcast.spi.impl.operationservice.impl.Invocation.sendResponse(Invocation.java:360)
     at com.hazelcast.spi.impl.operationservice.impl.PartitionInvocation.sendResponse(PartitionInvocation.java:29)
     at com.hazelcast.spi.Operation.sendResponse(Operation.java:277)
     at com.hazelcast.map.impl.operation.PartitionCheckIfLoadedOperation$CallbackResponseSender.onResponse(PartitionCheckIfLoadedOperation.java:97)
     at com.hazelcast.map.impl.operation.PartitionCheckIfLoadedOperation$CallbackResponseSender.onResponse(PartitionCheckIfLoadedOperation.java:93)
     at com.hazelcast.spi.impl.AbstractCompletableFuture$ExecutionCallbackRunnable.run(AbstractCompletableFuture.java:339)
     at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:212)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
     at java.lang.Thread.run(Thread.java:745)
     at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
     at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)

</code>

The system still works properly after exceptions are loged. But I had no such issues in HZ 3.5.4  Should I do something to prevent them?

**Comment by tombujok** [comment]
Thanks for reporting @dsukhoroslov  It has been fixed after EA3.
Here's the PR with the fix: https://github.com/hazelcast/hazelcast/pull/7115

**Comment by manishonline** [comment]
Hi,

Has the fix been merged into any of the EA releases?
