### ISSUE TITLE
EntryListenerConfigTest.testMapListenerAddition_withClassName

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#7221]
```
java.lang.AssertionError: expected:<2> but was:<3>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.map.EntryListenerConfigTest$1.run(EntryListenerConfigTest.java:164)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:737)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:751)
	at com.hazelcast.map.EntryListenerConfigTest.assertReceivedEventCount(EntryListenerConfigTest.java:161)
	at com.hazelcast.map.EntryListenerConfigTest.testMapListenerAddition_withClassName(EntryListenerConfigTest.java:67)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.maintenance/com.hazelcast$hazelcast/1128/testReport/junit/com.hazelcast.map/EntryListenerConfigTest/testMapListenerAddition_withClassName/

**Comment by eminn** [comment]
test fixed via e727b3d77ff4b3da8f602a590a26deac7a4ba83d
