### ISSUE TITLE
MapLockTest failures

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#7223]
**testLockOwnership**

```
org.junit.runners.model.TestTimedOutException: test timed out after 15000 milliseconds
    at java.lang.Object.wait(Native Method)
    at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.pollResponse(InvocationFuture.java:300)
    at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.waitForResponse(InvocationFuture.java:245)
    at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.get(InvocationFuture.java:222)
    at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.get(InvocationFuture.java:202)
    at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.getSafely(InvocationFuture.java:214)
    at com.hazelcast.concurrent.lock.LockProxySupport.lock(LockProxySupport.java:84)
    at com.hazelcast.concurrent.lock.LockProxySupport.lock(LockProxySupport.java:76)
    at com.hazelcast.map.impl.proxy.MapProxyImpl.lock(MapProxyImpl.java:232)
    at com.hazelcast.map.MapLockTest.testLockOwnership(MapLockTest.java:242)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-OracleJDK1.6/com.hazelcast$hazelcast/772/testReport/junit/com.hazelcast.map/MapLockTest/testLockOwnership/

**testLockEviction**

```
org.junit.runners.model.TestTimedOutException: test timed out after 20000 milliseconds
    at sun.misc.Unsafe.park(Native Method)
    at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:226)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1037)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1326)
    at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:281)
    at com.hazelcast.map.MapLockTest.testLockEviction(MapLockTest.java:134)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-ZuluJDK6/67/

**Comment by jerrinot** [comment]
Timeout of this test is explicitly set to 15s. 
It takes up to 7 seconds on my local box. I can imagine 15s might not always be enough on Cloudbees.

**Comment by hasancelik** [comment]
**testLockOwnership**

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-ZuluJDK6/com.hazelcast$hazelcast/71/testReport/junit/com.hazelcast.map/MapLockTest/testLockOwnership/

**Comment by hasancelik** [comment]
increased timeout via 0221a80073451ab91416176bf90d3c247ce7c928

**Comment by hasancelik** [comment]
**testLockEviction**
```
org.junit.runners.model.TestTimedOutException: test timed out after 20000 milliseconds
	at java.lang.Thread.sleep(Native Method)
	at java.lang.Thread.sleep(Thread.java:302)
	at java.util.concurrent.TimeUnit.sleep(TimeUnit.java:328)
	at com.hazelcast.internal.cluster.impl.AbstractJoiner.ensureConnectionToAllMembers(AbstractJoiner.java:173)
	at com.hazelcast.internal.cluster.impl.AbstractJoiner.postJoin(AbstractJoiner.java:155)
	at com.hazelcast.internal.cluster.impl.AbstractJoiner.join(AbstractJoiner.java:136)
	at com.hazelcast.instance.Node.join(Node.java:650)
	at com.hazelcast.instance.Node.start(Node.java:362)
	at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:130)
	at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:218)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:176)
	at com.hazelcast.test.TestHazelcastInstanceFactory.newHazelcastInstance(TestHazelcastInstanceFactory.java:116)
	at com.hazelcast.map.MapLockTest.testLockEviction(MapLockTest.java:119)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-OracleJDK1.6/com.hazelcast$hazelcast/958/testReport/junit/com.hazelcast.map/MapLockTest/testLockEviction/

**Comment by mmedenjak** [comment]
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.7/1240/

com.hazelcast.map.MapLockTest.testBackupDies

```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.map.MapLockTest.testBackupDies(MapLockTest.java:101)
```

com.hazelcast.map.MapLockTest.testLockMigration

```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at org.apache.logging.log4j.core.appender.OutputStreamManager.write(OutputStreamManager.java:122)
	at org.apache.logging.log4j.core.appender.OutputStreamManager.write(OutputStreamManager.java:135)
	at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.append(AbstractOutputStreamAppender.java:110)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:99)
	at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:430)
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:409)
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:367)
	at org.apache.logging.log4j.core.Logger.logMessage(Logger.java:112)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:727)
	at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:716)
	at com.hazelcast.logging.Log4j2Factory$Log4j2Logger.log(Log4j2Factory.java:60)
	at com.hazelcast.test.TestLoggerFactory$DelegatingTestLogger.log(TestLoggerFactory.java:144)
	at com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:168)
	at com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:158)
	at com.hazelcast.logging.AbstractLogger.info(AbstractLogger.java:69)
	at com.hazelcast.instance.DefaultNodeExtension.printNodeInfo(DefaultNodeExtension.java:105)
	at com.hazelcast.instance.Node.<init>(Node.java:201)
	at com.hazelcast.instance.HazelcastInstanceImpl.createNode(HazelcastInstanceImpl.java:163)
	at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:130)
	at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:195)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:174)
	at com.hazelcast.test.TestHazelcastInstanceFactory.newHazelcastInstance(TestHazelcastInstanceFactory.java:111)
	at com.hazelcast.map.MapLockTest.testLockMigration(MapLockTest.java:180)
```



Linked : 
https://github.com/hazelcast/hazelcast/issues/6953

**Comment by mdogan** [comment]
Last failures were before the latest logging fixes.
