### ISSUE TITLE
Exception during shutdown

### ISSUE THREAD

**Issue by publicocean0** [hazelcast/hazelcast#7230]
<pre>
01:19:57,020 DEBUG ApplicationBootstrap:169 - Stopping HazelCast ...
02-Jan-2016 01:19:57.020 INFO [localhost-startStop-2] com.hazelcast.core.LifecycleService.null [192.168.0.3]:5701 [dev] [3.5] Address[192.168.0.3]:5701 is SHUTTING_DOWN
02-Jan-2016 01:19:57.033 INFO [localhost-startStop-2] com.hazelcast.instance.Node.null [192.168.0.3]:5701 [dev] [3.5] Shutting down multicast service...
02-Jan-2016 01:19:57.033 INFO [localhost-startStop-2] com.hazelcast.instance.Node.null [192.168.0.3]:5701 [dev] [3.5] Shutting down connection manager...
02-Jan-2016 01:19:57.036 INFO [localhost-startStop-2] com.hazelcast.instance.Node.null [192.168.0.3]:5701 [dev] [3.5] Shutting down node engine...
Exception in thread "cached5" 02-Jan-2016 01:19:57.140 INFO [localhost-startStop-2] com.hazelcast.instance.NodeExtension.null [192.168.0.3]:5701 [dev] [3.5] Destroying node NodeExtension.
02-Jan-2016 01:19:57.140 INFO [localhost-startStop-2] com.hazelcast.instance.Node.null [192.168.0.3]:5701 [dev] [3.5] Hazelcast Shutdown is completed in 108 ms.
java.util.concurrent.RejectedExecutionException: Task com.hazelcast.util.executor.CompletableFutureTask$1@333c6388 rejected from ThreadPoolExecutor{name='hz:async'}
    at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047)
    at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823)
    at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369)
    at com.hazelcast.util.executor.CompletableFutureTask.runAsynchronous(CompletableFutureTask.java:110)
    at com.hazelcast.util.executor.CompletableFutureTask.fireCallbacks(CompletableFutureTask.java:103)
    at com.hazelcast.util.executor.CompletableFutureTask.run(CompletableFutureTask.java:59)
    at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:209)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
    at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
    at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)
</pre>

**Comment by publicocean0** [comment]
it seams some tasks in queue are rejects by client after shutdown.
How is possible to grant the delivery of last map updates ?

**Comment by publicocean0** [comment]
I found for IMap flush method. but is not present for MultiMap

**Comment by publicocean0** [comment]
the error is resolved even if the observation of missing api flush for multimap remains.

**Comment by jerrinot** [comment]
Hello @publicocean0,

many thanks for reporting the issue. Do you have a reproducer for it?

**Comment by publicocean0** [comment]
i will monitor the error in the log ... now is disappeared :)

Observations :     
- missing flush() api in all ADT
- <Collection>loadAll() in Store is not correct , replace it with Iterator. If the collection is loaded from DB with a million of items, what does it  happen? 
- i dont know the real reason but server continues to send notifications similar to 

  Warning: com.hazelcast.cluster.impl.MulticastService.null [192.168.0.3]:5701 [dev] [3.5] You probably have too long Hazelcast configuration!
 java.io.IOException: Message too long
	at java.net.PlainDatagramSocketImpl.send(Native Method)
	at java.net.DatagramSocket.send(DatagramSocket.java:693)
	at com.hazelcast.cluster.impl.MulticastService.send(MulticastService.java:184)
	at com.hazelcast.cluster.impl.MulticastJoiner.searchForOtherClusters(MulticastJoiner.java:112)
	at com.hazelcast.cluster.impl.SplitBrainHandler.searchForOtherClusters(SplitBrainHandler.java:48)
	at com.hazelcast.cluster.impl.SplitBrainHandler.run(SplitBrainHandler.java:38)
	at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:209)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)

**Comment by jerrinot** [comment]
could you please create new issues for the first 2 points? the 3rd point is most likely caused by #7198

**Comment by publicocean0** [comment]
Ok , inserted new 2 issues as requested.
