### ISSUE TITLE
MapPreconditionsTest failures

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#7233]
**testLocalKeySetWithPredicate
testLocalKeySetWithNullPredicate
testEntrySetWithPredicate
testKeySetWithPredicate
testValues
testEntrySet
testKeySet
testValuesWitPredicate
testLocalKeySet**

```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
    at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:245)
    at com.hazelcast.spi.impl.operationservice.impl.Invocation.invokeInternal(Invocation.java:210)
    at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:180)
    at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:46)
    at com.hazelcast.map.impl.proxy.MapProxySupport.invokeOperation(MapProxySupport.java:314)
    at com.hazelcast.map.impl.proxy.MapProxySupport.putInternal(MapProxySupport.java:288)
    at com.hazelcast.map.impl.proxy.MapProxyImpl.put(MapProxyImpl.java:106)
    at com.hazelcast.map.impl.proxy.MapProxyImpl.put(MapProxyImpl.java:96)
    at com.hazelcast.map.MapPreconditionsTest.testLocalKeySetWithNullPredicate(MapPreconditionsTest.java:559)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.7/774/#showFailuresLink

**Comment by eminn** [comment]
increased the timeout via dcfcb0f2de83ec3cb27666c8f43cc894b6fc0870

**Comment by mmedenjak** [comment]
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.7/1240/
com.hazelcast.client.map.MapPreconditionsTest.testPutAsyncWithNullValue

```
java.lang.IllegalStateException: Unable to connect to any address in the config! The following addresses were tried: [localhost/127.0.0.1:5703, /127.0.0.1:8001, /127.0.0.1:8000, /127.0.0.1:7999, localhost/127.0.0.1:5702, localhost/127.0.0.1:5701]
	at com.hazelcast.client.spi.impl.ClusterListenerSupport.connectToCluster(ClusterListenerSupport.java:180)
	at com.hazelcast.client.spi.impl.ClientClusterServiceImpl.start(ClientClusterServiceImpl.java:189)
	at com.hazelcast.client.impl.HazelcastClientInstanceImpl.start(HazelcastClientInstanceImpl.java:408)
	at com.hazelcast.client.test.TestHazelcastFactory.newHazelcastClient(TestHazelcastFactory.java:76)
	at com.hazelcast.client.test.TestHazelcastFactory.newHazelcastClient(TestHazelcastFactory.java:53)
	at com.hazelcast.client.map.MapPreconditionsTest.setUp(MapPreconditionsTest.java:68)
```
