### ISSUE TITLE
MapUnboundedReturnValues_QuickTest failures

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#7234]
**testMapKeySet_SmallLimit_NoPreCheck
testMapKeySet_SmallLimit_PreCheck**

```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:245)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invokeInternal(Invocation.java:210)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:180)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:46)
	at com.hazelcast.map.impl.proxy.MapProxySupport.invokeOperation(MapProxySupport.java:314)
	at com.hazelcast.map.impl.proxy.MapProxySupport.putInternal(MapProxySupport.java:288)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.put(MapProxyImpl.java:106)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.put(MapProxyImpl.java:96)
	at com.hazelcast.map.MapUnboundedReturnValuesTestSupport.mapPut(MapUnboundedReturnValuesTestSupport.java:162)
	at com.hazelcast.map.MapUnboundedReturnValuesTestSupport.fillToLimit(MapUnboundedReturnValuesTestSupport.java:171)
	at com.hazelcast.map.MapUnboundedReturnValuesTestSupport.runMapQuickTest(MapUnboundedReturnValuesTestSupport.java:87)
	at com.hazelcast.map.MapUnboundedReturnValues_QuickTest.testMapKeySet_SmallLimit_NoPreCheck(MapUnboundedReturnValues_QuickTest.java:16)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.7/774/#showFailuresLink

**Comment by eminn** [comment]
increased the timeout via dcfcb0f2de83ec3cb27666c8f43cc894b6fc0870
