### ISSUE TITLE
[near-cache] ClientMapNearCacheLiteMemberTest failures 

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#7235]
**testExecuteOnKey
testRemove
testEvict**

```
java.lang.AssertionError: lite member near cache size should be 0 after evict but was 1 expected:<0> but was:<1>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:834)
    at org.junit.Assert.assertEquals(Assert.java:645)
    at com.hazelcast.map.nearcache.NearCacheLiteMemberTest$2.run(NearCacheLiteMemberTest.java:438)
    at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:850)
    at com.hazelcast.map.nearcache.NearCacheLiteMemberTest.assertNearCacheIsEmptyEventually(NearCacheLiteMemberTest.java:433)
    at com.hazelcast.map.nearcache.NearCacheLiteMemberTest.testExecuteOnKey(NearCacheLiteMemberTest.java:358)
    at com.hazelcast.client.map.impl.nearcache.ClientMapNearCacheLiteMemberTest.testExecuteOnKey(ClientMapNearCacheLiteMemberTest.java:116)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.7/775/

**Comment by eminn** [comment]
9fd7a063b602674e145a20f392568ba7bfa6bb69

**Comment by hasancelik** [comment]
*testSet*
```
java.lang.AssertionError: Near Cache size should be > 0 but was 0
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.map.impl.nearcache.NearCacheLiteMemberTest.assertLiteMemberNearCacheNonEmpty(NearCacheLiteMemberTest.java:492)
	at com.hazelcast.map.impl.nearcache.NearCacheLiteMemberTest.testSet(NearCacheLiteMemberTest.java:249)
	at com.hazelcast.client.map.impl.nearcache.ClientMapNearCacheLiteMemberTest.testSet(ClientMapNearCacheLiteMemberTest.java:78)
```

https://hazelcast-l337.ci.cloudbees.com/view/Sonar/job/Hazelcast-3.x-sonar/com.hazelcast$hazelcast-client/1518/testReport/junit/com.hazelcast.client.map.impl.nearcache/ClientMapNearCacheLiteMemberTest/testSet/

**Comment by Donnerbart** [comment]
Passed about 3200 local runs without failure.
