### ISSUE TITLE
On WAN replication overrun, server logging is excessive

### ISSUE THREAD

**Issue by StanAccy** [hazelcast/hazelcast#7242]
3.6-122315-Enterprise:

When a WAN Q overrun occurs (with exception enabled), the source cluster logs an excessive amount of noise.  This seems to be logged, 1 stacktrace per IMap partition:

```java
2016-01-04 18:02:13,880 ERROR [hz._hzInstance_1_WAN1.partition-operation.thread-5] com.hazelcast.client.impl.protocol.task.map.MapPutAllMessageTask - [127.0.0.1]:5701 [WAN1] [3.6-122315] While executing request: com.hazelcast.client.impl.protocol.codec.MapPutAllCodec$RequestParameters@64e82635 -> null
com.hazelcast.enterprise.wan.WANReplicationQueueFullException
	at com.hazelcast.enterprise.wan.replication.AbstractWanReplication.checkWanReplicationQueues(AbstractWanReplication.java:332)
	at com.hazelcast.enterprise.wan.WanReplicationPublisherDelegate.checkWanReplicationQueues(WanReplicationPublisherDelegate.java:79)
	at com.hazelcast.map.impl.MapContainer.checkWanReplicationQueues(MapContainer.java:223)
	at com.hazelcast.map.impl.operation.WANAwareOperationProvider.checkWanReplicationQueues(WANAwareOperationProvider.java:173)
	at com.hazelcast.map.impl.operation.WANAwareOperationProvider.createPutAllOperation(WANAwareOperationProvider.java:129)
	at com.hazelcast.client.impl.protocol.task.map.MapPutAllMessageTask.prepareOperation(MapPutAllMessageTask.java:49)
	at com.hazelcast.client.impl.protocol.task.AbstractPartitionMessageTask.processMessage(AbstractPartitionMessageTask.java:58)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:121)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:100)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:127)
	at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.processPartitionSpecificRunnable(OperationThread.java:159)
	at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.process(OperationThread.java:142)
	at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.doRun(OperationThread.java:124)
	at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.run(OperationThread.java:99)
```

**Comment by pveentjer** [comment]
There is no reason to log this exception. Just logging actual message would be sufficient. But even in that case you still can get a huge amount of logging. So probably best to log it at most every x seconds and include the total number of failures?

```
WanReplication Queue full: occurrences 105853
```

This way there will be total control on the number of log messages.

**Comment by emrahkocaman** [comment]
I don't think that we can easily get rid of these logs.
in "putAll" operation,client divides the input smaller batches depending on their key and sends a "putAll" operation for each partition. (see : https://github.com/hazelcast/hazelcast/blob/master/hazelcast-client/src/main/java/com/hazelcast/client/proxy/ClientMapProxy.java#L1376)
This is why you're seeing lots of traces.

And WAN side just throws the exception, no logging is done. Logging is done by client engine. 
(https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/client/impl/ClientEngineImpl.java#L446)

**Comment by gregrluck** [comment]
There is no reason to log this exception at all. That we throwing an exception is sufficient.

**Comment by emrahkocaman** [comment]
We're only throwing, there is no logging on WAN side, but as seen [here] ( (https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/client/impl/ClientEngineImpl.java#L446)
, client engine is logging every exception.

I think all we can do for now is, adding an instance of check to client engine impl to see if the incoming throwable is WAN exception and ignore it.

Dear Clients team, if you've any objections to this approach or better alternatives in mind, I'd like to hear them.

**Comment by gregrluck** [comment]
Saying ignore is ambiguous. What we want is:

1. Not to log this exception on the client side.
2. We do want the exception thrown to the calling user code. i.e. we do not want to swallow this exception. It is needed to implement back pressure in client code.

**Comment by emrahkocaman** [comment]
I meant ignoring logging. 
Here is the line where logging is done;
https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/client/impl/ClientEngineImpl.java#L446 

What I proposed was, adding an instance of check to this line and skip logging part if exception is instance of `WANReplicationQueueFullException`

1. Exceptions are logged in server side, I think there is no problem in client side. My proposed changes are in server side also.

2. Exception won't be swallowed. This is just logging part.

**Comment by pveentjer** [comment]
An exception shoud be thrown or logged; not both. If the client engine is throwing and logging an exception, it is doing too much. So probably we should get rid of the exception logging in the client engine.

**Comment by sancar** [comment]
I don't want to lose it completely because sometimes it helps a lot. How about printing in FINEST log level ?

**Comment by pveentjer** [comment]
I think having it at finest is ok since it is meant for debugging anyway.

**Comment by pveentjer** [comment]
Do we want to wait for 3.7 to get this fixed? Imho it is a small change in the ClientEngine and without this fix, there could be a serious performance degradation.

**Comment by jerrinot** [comment]
3.6.1 ?

**Comment by pveentjer** [comment]
why not in 3.6? Imho it is a log level change. @sancar WDYT

**Comment by sancar** [comment]
I am ok with 3.6 with only log level change
