### ISSUE TITLE
BasicCacheLiteMemberTest.testCompletionTest

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#7249]
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.lang.Object.wait(Native Method)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.pollResponse(InvocationFuture.java:300)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.waitForResponse(InvocationFuture.java:245)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.get(InvocationFuture.java:222)
	at com.hazelcast.util.FutureUtil.executeWithDeadline(FutureUtil.java:294)
	at com.hazelcast.util.FutureUtil.waitWithDeadline(FutureUtil.java:278)
	at com.hazelcast.util.FutureUtil.waitWithDeadline(FutureUtil.java:252)
	at com.hazelcast.spi.impl.eventservice.impl.EventServiceImpl.invokeRegistrationOnOtherNodes(EventServiceImpl.java:246)
	at com.hazelcast.spi.impl.eventservice.impl.EventServiceImpl.registerListenerInternal(EventServiceImpl.java:200)
	at com.hazelcast.spi.impl.eventservice.impl.EventServiceImpl.registerListener(EventServiceImpl.java:181)
	at com.hazelcast.cache.impl.AbstractCacheService.registerListenerInternal(AbstractCacheService.java:398)
	at com.hazelcast.cache.impl.AbstractCacheService.registerListener(AbstractCacheService.java:381)
	at com.hazelcast.cache.impl.CacheProxy.registerCacheEntryListener(CacheProxy.java:301)
	at com.hazelcast.cache.impl.AbstractHazelcastCacheManager.registerListeners(AbstractHazelcastCacheManager.java:412)
	at com.hazelcast.cache.impl.AbstractHazelcastCacheManager.getCacheUnchecked(AbstractHazelcastCacheManager.java:252)
	at com.hazelcast.cache.impl.AbstractHazelcastCacheManager.getCache(AbstractHazelcastCacheManager.java:215)
	at com.hazelcast.cache.impl.AbstractHazelcastCacheManager.getCache(AbstractHazelcastCacheManager.java:63)
	at com.hazelcast.cache.BasicCacheLiteMemberTest.testCompletionTest(BasicCacheLiteMemberTest.java:156)
```

https://hazelcast-l337.ci.cloudbees.com/view/Quality-Outreach/job/Hazelcast-3.x-OpenJDK8-Quality-Outreach/com.hazelcast$hazelcast/292/testReport/junit/com.hazelcast.cache/BasicCacheLiteMemberTest/testCompletionTest/

**Comment by hasancelik** [comment]
This test failed only at unofficial build.

**Comment by hasancelik** [comment]
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at com.hazelcast.cache.impl.CacheProxy.updateCacheListenerConfigOnOtherNodes(CacheProxy.java:338)
	at com.hazelcast.cache.impl.CacheProxy.registerCacheEntryListener(CacheProxy.java:305)
	at com.hazelcast.cache.impl.AbstractHazelcastCacheManager.registerListeners(AbstractHazelcastCacheManager.java:412)
	at com.hazelcast.cache.impl.AbstractHazelcastCacheManager.getCacheUnchecked(AbstractHazelcastCacheManager.java:252)
	at com.hazelcast.cache.impl.AbstractHazelcastCacheManager.getCache(AbstractHazelcastCacheManager.java:215)
	at com.hazelcast.cache.impl.AbstractHazelcastCacheManager.getCache(AbstractHazelcastCacheManager.java:63)
	at com.hazelcast.cache.BasicCacheLiteMemberTest.testCompletionTest(BasicCacheLiteMemberTest.java:156)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.8/com.hazelcast$hazelcast/101/testReport/junit/com.hazelcast.cache/BasicCacheLiteMemberTest/testCompletionTest/

**Comment by hasancelik** [comment]
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.lang.Object.wait(Native Method)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.pollResponse(InvocationFuture.java:300)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.waitForResponse(InvocationFuture.java:245)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.get(InvocationFuture.java:222)
	at com.hazelcast.util.FutureUtil.executeWithDeadline(FutureUtil.java:294)
	at com.hazelcast.util.FutureUtil.waitWithDeadline(FutureUtil.java:278)
	at com.hazelcast.util.FutureUtil.waitWithDeadline(FutureUtil.java:252)
	at com.hazelcast.spi.impl.eventservice.impl.EventServiceImpl.invokeRegistrationOnOtherNodes(EventServiceImpl.java:246)
	at com.hazelcast.spi.impl.eventservice.impl.EventServiceImpl.registerListenerInternal(EventServiceImpl.java:200)
	at com.hazelcast.spi.impl.eventservice.impl.EventServiceImpl.registerListener(EventServiceImpl.java:181)
	at com.hazelcast.cache.impl.AbstractCacheService.registerListenerInternal(AbstractCacheService.java:398)
	at com.hazelcast.cache.impl.AbstractCacheService.registerListener(AbstractCacheService.java:381)
	at com.hazelcast.cache.impl.CacheProxy.registerCacheEntryListener(CacheProxy.java:301)
	at com.hazelcast.cache.impl.AbstractHazelcastCacheManager.registerListeners(AbstractHazelcastCacheManager.java:412)
	at com.hazelcast.cache.impl.AbstractHazelcastCacheManager.getCacheUnchecked(AbstractHazelcastCacheManager.java:252)
	at com.hazelcast.cache.impl.AbstractHazelcastCacheManager.getCache(AbstractHazelcastCacheManager.java:215)
	at com.hazelcast.cache.impl.AbstractHazelcastCacheManager.getCache(AbstractHazelcastCacheManager.java:63)
	at com.hazelcast.cache.BasicCacheLiteMemberTest.testCompletionTest(BasicCacheLiteMemberTest.java:156)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.maintenance-ZuluJDK8/com.hazelcast$hazelcast/39/testReport/junit/com.hazelcast.cache/BasicCacheLiteMemberTest/testCompletionTest/

**Comment by hasancelik** [comment]
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.lang.Object.wait(Native Method)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.pollResponse(InvocationFuture.java:300)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.waitForResponse(InvocationFuture.java:245)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.get(InvocationFuture.java:222)
	at com.hazelcast.util.FutureUtil.executeWithDeadline(FutureUtil.java:294)
	at com.hazelcast.util.FutureUtil.waitWithDeadline(FutureUtil.java:278)
	at com.hazelcast.util.FutureUtil.waitWithDeadline(FutureUtil.java:252)
	at com.hazelcast.spi.impl.eventservice.impl.EventServiceImpl.invokeRegistrationOnOtherNodes(EventServiceImpl.java:246)
	at com.hazelcast.spi.impl.eventservice.impl.EventServiceImpl.registerListenerInternal(EventServiceImpl.java:200)
	at com.hazelcast.spi.impl.eventservice.impl.EventServiceImpl.registerListener(EventServiceImpl.java:181)
	at com.hazelcast.cache.impl.AbstractCacheService.registerListenerInternal(AbstractCacheService.java:398)
	at com.hazelcast.cache.impl.AbstractCacheService.registerListener(AbstractCacheService.java:381)
	at com.hazelcast.cache.impl.CacheProxy.registerCacheEntryListener(CacheProxy.java:301)
	at com.hazelcast.cache.impl.AbstractHazelcastCacheManager.registerListeners(AbstractHazelcastCacheManager.java:412)
	at com.hazelcast.cache.impl.AbstractHazelcastCacheManager.getCacheUnchecked(AbstractHazelcastCacheManager.java:252)
	at com.hazelcast.cache.impl.AbstractHazelcastCacheManager.getCache(AbstractHazelcastCacheManager.java:215)
	at com.hazelcast.cache.impl.AbstractHazelcastCacheManager.getCache(AbstractHazelcastCacheManager.java:63)
	at com.hazelcast.cache.BasicCacheLiteMemberTest.testCompletionTest(BasicCacheLiteMemberTest.java:156)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.maintenance-ZuluJDK8/com.hazelcast$hazelcast/63/testReport/junit/com.hazelcast.cache/BasicCacheLiteMemberTest/testCompletionTest/

**Comment by metanet** [comment]
Closed by https://github.com/hazelcast/hazelcast/commit/e9297246f299885e67f949a7f55cf556588db2d6
