### ISSUE TITLE
Hazelcast 3.6 querying collections with "this"

### ISSUE THREAD

**Issue by mjquigley** [hazelcast/hazelcast#7281]
It would be nice if the following would work
```Java
IMap<String, List<String>> map;
Predicate p = Predicates.equals('this[0].name', 'someName');
map.entrySet(p);
```

Currently I get the following exception
```
Throwable: java.lang.IllegalArgumentException: Cannot use EqualPredicate predicate with an array or a collection attribute
	at com.hazelcast.query.impl.predicates.AbstractPredicate.apply(AbstractPredicate.java:59)
	at com.hazelcast.map.impl.query.MapQueryEngineImpl.queryTheLocalPartition(MapQueryEngineImpl.java:285)
	at com.hazelcast.map.impl.query.MapQueryEngineImpl.querySequential(MapQueryEngineImpl.java:187)
	at com.hazelcast.map.impl.query.MapQueryEngineImpl.queryUsingFullTableScan(MapQueryEngineImpl.java:176)
	at com.hazelcast.map.impl.query.MapQueryEngineImpl.queryLocalPartitions(MapQueryEngineImpl.java:131)
	at com.hazelcast.map.impl.query.QueryOperation.run(QueryOperation.java:51)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:172)
	at com.hazelcast.spi.impl.operationexecutor.classic.ClassicOperationExecutor.runOnCallingThread(ClassicOperationExecutor.java:385)
	at com.hazelcast.spi.impl.operationexecutor.classic.ClassicOperationExecutor.runOnCallingThreadIfPossible(ClassicOperationExecutor.java:345)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:259)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:243)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invokeInternal(Invocation.java:210)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:180)
	at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.invokeOnTarget(OperationServiceImpl.java:323)
	at com.hazelcast.map.impl.query.MapQueryEngineImpl.queryOnMembers(MapQueryEngineImpl.java:468)
	at com.hazelcast.map.impl.query.MapQueryEngineImpl.invokeQueryAllPartitions(MapQueryEngineImpl.java:420)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.keySet(MapProxyImpl.java:595)
        ...
```

This appears to be caused because the new logic in GetterFactory.newFieldGetter() isn't done when using GetterFactory.newThisGetter().

**Comment by jerrinot** [comment]
Hello @mjquigley,

thank you for reporting it. This is a very good point.

**Comment by bwzhang2011** [comment]
@jerrinot, is there any plan that hazelcast will take the consideration for join operation cross many caches into consideration ? as in real world that the predicate result could come from many caches, so some nice support for such would be much more appreciated.

**Comment by jerrinot** [comment]
@bwzhang2011: Hi, we are not planning to add JOIN support in a foreseeable future. I recommend to model your data in the way that embraces the distributed nature of a datagrid and its strength.
