### ISSUE TITLE
NearCacheTest.testGetAll[batchInvalidationEnabled:true]

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#7285]
```
java.lang.AssertionError: Near cache hits should be > 400 but were 371
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.map.nearcache.NearCacheTest.testGetAll(NearCacheTest.java:437)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-OracleJDK1.6/com.hazelcast$hazelcast/784/testReport/junit/com.hazelcast.map.nearcache/NearCacheTest/testGetAll_batchInvalidationEnabled_true_/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: Near cache hits should be 481 but were 400 expected:<481> but was:<400>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.map.nearcache.NearCacheTest.testGetAll(NearCacheTest.java:450)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast$hazelcast/833/testReport/junit/com.hazelcast.map.nearcache/NearCacheTest/testGetAll_batchInvalidationEnabled_true_/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: Near cache hits should be 491 but were 428 expected:<491> but was:<428>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.map.nearcache.NearCacheTest.testGetAll(NearCacheTest.java:450)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.maintenance-OracleJDK1.6/com.hazelcast$hazelcast/355/testReport/junit/com.hazelcast.map.nearcache/NearCacheTest/testGetAll_batchInvalidationEnabled_true_/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: Near cache hits should be 498 but were 440 expected:<498> but was:<440>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.map.nearcache.NearCacheTest.testGetAll(NearCacheTest.java:452)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast$hazelcast/921/testReport/junit/com.hazelcast.map.nearcache/NearCacheTest/testGetAll_batchInvalidationEnabled_true_/

**Comment by ahmetmircik** [comment]
Fixed via https://github.com/hazelcast/hazelcast/commit/b688d4f9076d53864a940f4ef394682a44bb3d19

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: Near cache hits should be 510 but were 501 expected:<510> but was:<501>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.map.nearcache.NearCacheTest.testGetAll(NearCacheTest.java:452)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.maintenance/com.hazelcast$hazelcast/1344/testReport/junit/com.hazelcast.map.nearcache/NearCacheTest/testGetAll_batchInvalidationEnabled_true_/

**Comment by ahmetmircik** [comment]
should be fixed by https://github.com/hazelcast/hazelcast/commit/b41c380408dfeedc51226f1456016d4c83056f11
