### ISSUE TITLE
issues with HazelcastClient config

### ISSUE THREAD

**Issue by dsukhoroslov** [hazelcast/hazelcast#7289]
HZ 3.5.4
1. there is no way to set HazelcastClient Name and/or InstanceName programmatically. So, the HazelcastClient.getHazelcastClientByName(String name) method does not work.
2. When I trying to achieve the same functionality via group name:

```java
        for (HazelcastInstance hz: HazelcastClient.getAllHazelcastClients()) {
            if (name.equals(hz.getConfig().getGroupConfig().getName())) {
                hzClient = hz;
                break;
            }
        }
```

then it throws an exception:

```
java.lang.UnsupportedOperationException: Client cannot access cluster config!
     at com.hazelcast.client.impl.HazelcastClientInstanceImpl.getConfig(HazelcastClientInstanceImpl.java:278) ~[hazelcast-all-3.5.4.jar:3.5.4]
     at com.hazelcast.client.impl.HazelcastClientProxy.getConfig(HazelcastClientProxy.java:78) ~[hazelcast-all-3.5.4.jar:3.5.4]
     at com.bagri.xdm.cache.hazelcast.util.HazelcastUtils.getHazelcastClientByName(HazelcastUtils.java:90) ~[classes/:na]
     at com.bagri.xdm.cache.hazelcast.management.SchemaManager.setClientContext(SchemaManager.java:89) ~[classes/:na]
     at com.bagri.xdm.cache.hazelcast.management.SchemaManagement.initSchema(SchemaManagement.java:205) [classes/:na]
     at com.bagri.xdm.cache.hazelcast.management.SchemaManagement.initMember(SchemaManagement.java:316) [classes/:na]
     at com.bagri.xdm.cache.hazelcast.task.schema.SchemaAdministrator.call(SchemaAdministrator.java:64) [classes/:na]
     at com.bagri.xdm.cache.hazelcast.task.schema.SchemaAdministrator.call(SchemaAdministrator.java:23) [classes/:na]
     at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_76]
     at com.hazelcast.executor.impl.DistributedExecutorService$CallableProcessor.run(DistributedExecutorService.java:202) [hazelcast-all-3.5.4.jar:3.5.4]
     at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:209) [hazelcast-all-3.5.4.jar:3.5.4]
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_76]
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_76]
     at java.lang.Thread.run(Thread.java:745) [na:1.7.0_76]
     at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76) [hazelcast-all-3.5.4.jar:3.5.4]
     at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92) [hazelcast-all-3.5.4.jar:3.5.4]
```

**Comment by jerrinot** [comment]
Hello,

thank you for reporting this issue. It seems like a weakness of client implementation.

**Comment by rajavikram** [comment]
@jerrinot Any, ETA on a fix for this.

**Comment by mehmetsunkur** [comment]
Hello,
It seems this issue fixed. You can check [HazelcastClientInstanceImpl](https://github.com/hazelcast/hazelcast/blob/master/hazelcast-client/src/main/java/com/hazelcast/client/impl/HazelcastClientInstanceImpl.java) in master,maintenance-3.x branches.

```
public Config getConfig() {
        throw new UnsupportedOperationException("Client cannot access cluster config!");
}
```
method changed to 
```
@Override
public Config getConfig() {
        return new ClientDynamicClusterConfig(this);
}
```

**Comment by sancar** [comment]
Fixed by https://github.com/hazelcast/hazelcast/pull/5605 in 3.6 .
