### ISSUE TITLE
JCache isn't shown in Hazelcast ManCenter

### ISSUE THREAD

**Issue by JuKu** [hazelcast/hazelcast#7294]
Hi,

for an session store i am using the Hazelcast JCache Provider so store sessions as json string in distributed hazelcast jcache.
But the JCache isnt shown in Hazelcast ManCenter.

If the server doesnt have jcache.jar in Classpath, the hazelcast client throws an exception, but now its in classpath and there arent any warnings.

IMPORTANT: The Client doesnt use an hazelcast-client.xml, it is be configured at runtime.
How i create the Hazelcast Client: http://imgur.com/zpQhHSq
Here is the code from Hazelcast Session Store: http://pastebin.com/FgqGHzWR

It isnt any exception thrown, the log doesnt shown any detail, about jcache, only my own logger output.
Here is my Server start script: http://pastebin.com/1tNZm4dw

Of recommendation from @noctarius i also have added hazelcast.xml to classpath and added the jcache section, with key and value of String, @noctarius means, this maybe has to be thrown an exception, because my application use an Cache with key of Long and value of String, but it doesnt.
Here is the hazelcast.xml: http://pastebin.com/4w6uh18c

Is it an bug?
Thanks!

**Comment by emrahkocaman** [comment]
Hi @JuKu ,
 
Could you please provide a sample project so that we can try reproducing this behaviour? (It's very hard to understand what's happening with screenshots and snippets)

**Comment by JuKu** [comment]
Here is an new image: http://www.bilder-upload.eu/show.php?file=fc1845-1456180673.png
[hazelcast-issue-example.zip](https://github.com/hazelcast/hazelcast/files/141583/hazelcast-issue-example.zip)

I have attached an example project, how you can reproduce the problem.

**Comment by emrahkocaman** [comment]
@JuKu ,

By default statistics are disabled for JCache, you need to enable them in your configuration.
Just add below two lines to your config in your `HazelcastSessionStore` class and then it should be visible in mancenter.

```java
configuration.setManagementEnabled(true);
configuration.setStatisticsEnabled(true);
```

![image](https://cloud.githubusercontent.com/assets/2887123/13249941/ca47122c-da2f-11e5-99ff-801664f3ee48.png)

**Comment by noctarius** [comment]
Oh cool, didn't know that either, couldn't answer his question. Good to know, thanks @emrahkocaman  :)

**Comment by JuKu** [comment]
Thank you for your answer!

But now there is also an other problem:
`"main" java.lang.NoClassDefFoundError: com/hazelcast/cache/impl/CacheEntryCountResolver
	at com.hazelcast.client.cache.impl.ClientCacheStatisticsImpl.<init>(ClientCacheStatisticsImpl.java:32)
	at com.hazelcast.client.cache.impl.AbstractClientInternalCacheProxy.<init>(AbstractClientInternalCacheProxy.java:142)
	at com.hazelcast.client.cache.impl.AbstractClientCacheProxy.<init>(AbstractClientCacheProxy.java:64)
	at com.hazelcast.client.cache.impl.ClientCacheProxy.<init>(ClientCacheProxy.java:79)
	at com.hazelcast.client.cache.impl.HazelcastClientCacheManager.createCacheProxy(HazelcastClientCacheManager.java:149)
	at com.hazelcast.cache.impl.AbstractHazelcastCacheManager.createCacheInternal(AbstractHazelcastCacheManager.java:118)
	at com.hazelcast.cache.impl.AbstractHazelcastCacheManager.createCache(AbstractHazelcastCacheManager.java:145)
	at com.hazelcast.cache.impl.AbstractHazelcastCacheManager.createCache(AbstractHazelcastCacheManager.java:63)
	at com.pentaquin.usersystem.permission.impl.DefaultPermissionManager.createCache(DefaultPermissionManager.java:401)
	at com.pentaquin.usersystem.permission.impl.DefaultPermissionManager.<init>(DefaultPermissionManager.java:55)
	at com.pentaquin.usersystem.impl.DefaultUserSystem.<init>(DefaultUserSystem.java:63)
	at com.pentaquin.usersystem.factory.UserSystemFactory.createUserSystem(UserSystemFactory.java:14)
	at com.pentaquin.login.server.LoginServerMain.main(LoginServerMain.java:111)
Caused by: java.lang.ClassNotFoundException: com.hazelcast.cache.impl.CacheEntryCountResolver
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
`

**Comment by JuKu** [comment]
EDIT:

The code

`configuration.setManagementEnabled(true);
configuration.setStatisticsEnabled(true);`

doesnt work.
JCache isnt shown in hazelcast mancenter.

I have attached the updatet hazelcast issue example project.
[hazelcast-issue-example.zip](https://github.com/hazelcast/hazelcast/files/142931/hazelcast-issue-example.zip)

**Comment by emrahkocaman** [comment]
I've tried with your sample project and there is no problem.

![image](https://cloud.githubusercontent.com/assets/2887123/13279875/3f0e8992-dae3-11e5-9fd8-6d34d4867221.png)

Please make sure that all your hz servers are connected management center and also you can try refreshing the management center tab in your browser.

**Comment by JuKu** [comment]
@emrahkocaman  Does the mancenter also needs jcache in classpath?

**Comment by emrahkocaman** [comment]
Nope.

**Comment by JuKu** [comment]
Did you use Hazelcast Version 3.5.4?

 

 

 

-----Original-Nachricht-----

Betreff: Re: [hazelcast] JCache isnt shown in Hazelcast ManCenter (#7294)

Datum: 2016-02-25T18:09:20+0100

Von: "emrahkocaman" <notifications@github.com>

An: "hazelcast/hazelcast" <hazelcast@noreply.github.com>

 

 

 

Nope.

On Thu, Feb 25, 2016 at 6:20 PM, JuKu <notifications@github.com> wrote:

> @emrahkocaman <https://github.com/emrahkocaman> Does the mancenter also
> needs jcache in classpath?
>
> —
> Reply to this email directly or view it on GitHub
> 
<https://github.com/hazelcast/hazelcast/issues/7294#issuecomment-188860755>
> .
>

—
Reply to this email directly or view it on GitHub
<https://github.com/hazelcast/hazelcast/issues/7294#issuecomment-188881571> 
.

 


<div style=\"border:0;border-bottom:1px solid black;width:100%;\"> Telekom 
Mail: Ihre Daten bleiben in Deutschland.
Jetzt persönliche E-Mail-Adresse sichern!
www.t-online.de/email-kostenlos

**Comment by emrahkocaman** [comment]
Yes, I'm using the project that you've provided. 
[hazelcast-issue-example.zip](https://github.com/hazelcast/hazelcast/files/169103/hazelcast-issue-example.zip)

**Comment by mdogan** [comment]
@JuKu: Are you still having problems with seeing JCache on Management Center?

**Comment by emre-aydin** [comment]
Closing the issue for inactivity. @JuKu if you still have this problem, feel free to reopen the issue.
