### ISSUE TITLE
ICache should be empty, TTL events not processed expected

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#7302]
Test 
`com.hazelcast.simulator.tests.icache.ExpiryICacheTest`
https://github.com/hazelcast/hazelcast-simulator/blob/2084e82116e4409e40504a9350294091453e5dad/tests/src/main/java/com/hazelcast/simulator/tests/icache/ExpiryICacheTest.java

Jenkins sim runs, failed:
https://hazelcast-l337.ci.cloudbees.com/view/Simulator/job/Hazelcast-Simulator-nightly/377/console
https://hazelcast-l337.ci.cloudbees.com/view/Simulator/job/Hazelcast-Simulator-nightly-enterprise/

```
WORKER_EXCEPTION[java.lang.AssertionError: iCacheTtl: ICache should be empty, TTL events not processed expected:<0> but was:<14905>]
```
```
INFO  2016-01-12 23:11:36,713 [Thread-96] com.hazelcast.simulator.tests.icache.ExpiryICacheTest: iCacheTtl cache size = 14905
INFO  2016-01-12 23:13:13,140 [Thread-96] com.hazelcast.simulator.tests.icache.ExpiryICacheTest: iCacheTtl cache size = 14905
NFO  2016-01-12 23:13:53,979 [Thread-96] com.hazelcast.simulator.tests.icache.ExpiryICacheTest: iCacheTtl cache size = 14905
INFO  2016-01-12 23:13:54,307 [Thread-96] com.hazelcast.simulator.tests.icache.ExpiryICacheTest: iCacheTtl cache size = 14905
INFO  2016-01-12 23:14:17,243 [Thread-96] com.hazelcast.simulator.tests.icache.ExpiryICacheTest: iCacheTtl cache size = 14905

INFO  2016-01-12 23:15:00,038 [Thread-96] com.hazelcast.simulator.tests.icache.ExpiryICacheTest: iCacheTtl cache size = 14905
WARN  2016-01-12 23:15:03,868 [txnCon-Thread-1] com.hazelcast.simulator.tests.map.MapTransactionGetForUpdateTest: txnCon: commit failed key=280 inc=66
com.hazelcast.transaction.TransactionException: Transaction is timed-out!
	at com.hazelcast.client.proxy.txn.TransactionProxy.checkTimeout(TransactionProxy.java:141)
	at com.hazelcast.client.proxy.txn.TransactionProxy.commit(TransactionProxy.java:99)
	at com.hazelcast.client.proxy.txn.TransactionContextProxy.commitTransaction(TransactionContextProxy.java:77)
	at com.hazelcast.simulator.tests.map.MapTransactionGetForUpdateTest$Worker.run(MapTransactionGetForUpdateTest.java:112)
	at java.lang.Thread.run(Thread.java:745)
	at com.hazelcast.simulator.utils.ThreadSpawner$ReportExceptionThread.run(ThreadSpawner.java:183)
INFO  2016-01-12 23:15:21,161 [Thread-96] com.hazelcast.simulator.tests.icache.ExpiryICacheTest: iCacheTtl cache size = 14905
INFO  2016-01-12 23:15:22,302 [Thread-96] com.hazelcast.simulator.tests.icache.ExpiryICacheTest: iCacheTtl cache size = 14905
INFO  2016-01-12 23:15:22,522 [Thread-90] com.hazelcast.simulator.protocol.processors.TestOperationProcessor: --------------------------- Completed run of MapTransactionTest ---------------------------
INFO  2016-01-12 23:15:24,185 [Thread-96] com.hazelcast.simulator.tests.icache.ExpiryICacheTest: iCacheTtl cache size = 14905
INFO  2016-01-12 23:15:24,504 [Thread-88] com.hazelcast.simulator.protocol.processors.TestOperationProcessor: --------------------------- Completed run of txnCon ---------------------------
INFO  2016-01-12 23:15:29,451 [Thread-96] com.hazelcast.simulator.tests.icache.ExpiryICacheTest: iCacheTtl cache size = 14905
INFO  2016-01-12 23:15:33,509 [Thread-96] com.hazelcast.simulator.tests.icache.ExpiryICacheTest: iCacheTtl cache size = 14905
INFO  2016-01-12 23:15:39,360 [Thread-96] com.hazelcast.simulator.tests.icache.ExpiryICacheTest: iCacheTtl cache size = 14905
INFO  2016-01-12 23:15:48,417 [Thread-96] com.hazelcast.simulator.tests.icache.ExpiryICacheTest: iCacheTtl cache size = 14905
INFO  2016-01-12 23:15:56,956 [nioEventLoopGroup-3-1] com.hazelcast.simulator.protocol.processors.WorkerOperationProcessor: Pinged by C (queue size: 0)...
INFO  2016-01-12 23:16:01,389 [Thread-96] com.hazelcast.simulator.tests.icache.ExpiryICacheTest: iCacheTtl cache size = 14905
INFO  2016-01-12 23:16:22,494 [Thread-96] com.hazelcast.simulator.tests.icache.ExpiryICacheTest: iCacheTtl cache size = 14905
ERROR 2016-01-12 23:16:24,080 [Thread-96] com.hazelcast.simulator.protocol.processors.TestOperationProcessor: Error while executing test phase
java.lang.AssertionError: iCacheTtl: ICache should be empty, TTL events not processed expected:<0> but was:<14905>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.simulator.tests.icache.ExpiryICacheTest$1.run(ExpiryICacheTest.java:90)
	at com.hazelcast.simulator.utils.TestUtils.assertTrueEventually(TestUtils.java:100)
	at com.hazelcast.simulator.utils.TestUtils.assertTrueEventually(TestUtils.java:131)
	at com.hazelcast.simulator.tests.icache.ExpiryICacheTest.globalVerify(ExpiryICacheTest.java:86)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.hazelcast.simulator.utils.ReflectionUtils.invokeMethod(ReflectionUtils.java:105)
	at com.hazelcast.simulator.worker.TestContainer.invoke(TestContainer.java:172)
	at com.hazelcast.simulator.protocol.processors.TestOperationProcessor$1.doRun(TestOperationProcessor.java:115)
	at com.hazelcast.simulator.protocol.processors.TestOperationProcessor$OperationThread.run(TestOperationProcessor.java:182)
WARN  2016-01-12 23:16:24,081 [Thread-96] com.hazelcast.simulator.protocol.exception.AbstractExceptionLogger: Logged exception #1: AssertionError(iCacheTtl: ICache should be empty, TTL events not processed expected:<0> but was:<14905>)
WARN  2016-01-12 23:16:24,104 [Thread-96] com.hazelcast.simulator.protocol.exception.AbstractExceptionLogger: Failure #1 C_A5_W1 Test: iCacheTtl WORKER_EXCEPTION[java.lang.AssertionError: iCacheTtl: ICache should be empty, TTL events not processed expected:<0> but was:<14905>]
```

**Comment by Danny-Hazelcast** [comment]
@serkan-ozal   I assigned to you   is it ok ?  or i can assigne to some one else

**Comment by serkan-ozal** [comment]
I am ok. I will take it

**Comment by serkan-ozal** [comment]
Without touching entries are not expired in JCache. Because there is no background task to collect expired entries. Even if we would have such background thread to collect these expired entries, it would be problem for HD-JCache because it is designed for single thread access.

But the test itself relies on auto expiration of entries and so the test is fragile from this perspective.

**Comment by mdogan** [comment]
@serkan-ozal: is it possible this test to pass at all? there are only puts and even a record with the same key expires, a new one will be put. Or am I missing something?

**Comment by serkan-ozal** [comment]
@mdogan yes, i don't think so it can pass. In fact the verify part has been added 3 days ago to check cache size is 0 and this is why this test started to fail.

**Comment by Donnerbart** [comment]
The verify method uses `assertTrueEventually()` to wait for expiration, after the run phase is done. I also tried to sleep the double of the expire duration (which we do in some other tests), same result.

So either there is no auto-expire without an access or it doesn't work.

**Comment by mdogan** [comment]
There's no auto expire in jcache. it's only on access.

**Comment by serkan-ozal** [comment]
We can discuss auto-expiration support for jcache later in a new PRD but I think it is too late for this release to add this behaviour. At the moment, JCache has no auto expire at all.

**Comment by Danny-Hazelcast** [comment]
@serkan-ozal  @mdogan    i think cache.containsKey(key)  should logically, expire the key value

(not that it would make the test pass)  so i am happey close the issue

**Comment by Danny-Hazelcast** [comment]
@ahmetmircik  so we presume that HD Imap also has not auto expire

**Comment by serkan-ozal** [comment]
@Danny-Hazelcast yes `containsKey` trigger expiration

**Comment by mdogan** [comment]
hmm.. I was looking at an earlier version... I didn't recognize there's `containsKey()` ...

**Comment by serkan-ozal** [comment]
sorry, it is `contains` not `containsKey`

**Comment by mdogan** [comment]
@serkan-ozal: I can't see `contains()` method in cache, there's only `containsKey()`.

**Comment by serkan-ozal** [comment]
ah ok, i had opened cache record store not cache proxy

**Comment by mdogan** [comment]
Let's start over... Problem with the test is, I think, some of the keys may not be touched after put, means they are not expired at all.

**Comment by Danny-Hazelcast** [comment]
there is a background task to expire entries in HD Imap

**Comment by mdogan** [comment]
@Danny-Hazelcast: yes, IMap has background (auto) expiration. ICache doesn't have.

**Comment by serkan-ozal** [comment]
@mdogan yes they are not touched after put so they are not expired at all.

**Comment by Danny-Hazelcast** [comment]
@mdogan  yes that is the problem,   I am just confirming what methods count as access 

for instance size()   to me i would expect to get the size of the cache after TTL expires

**Comment by enesakar** [comment]
I think we should change/adapt the test to pass and close this issue for now.

**Comment by mdogan** [comment]
I think making `size()` to do expiry is kinda expensive. But at least for now, it does not.

**Comment by Danny-Hazelcast** [comment]
ok

**Comment by serkan-ozal** [comment]
@Danny-Hazelcast will the test is updated?

**Comment by Danny-Hazelcast** [comment]
sure
