### ISSUE TITLE
OS sim lab run  TargetDisconnectedException

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#7312]
using OS, version of HZ and using to replicate issue  https://github.com/hazelcast/hazelcast-enterprise/issues/691

issue is not replicated we have

```
grep cause failures-2016-01-13__12_01_25.txt | sort | uniq
   cause=com.hazelcast.spi.exception.TargetDisconnectedException: Target[Address[10.212.40.101]:5701] disconnected.
   cause=com.hazelcast.spi.exception.TargetDisconnectedException: Target[Address[10.212.40.102]:5701] disconnected.
   cause=com.hazelcast.spi.exception.TargetDisconnectedException: Target[Address[10.212.40.103]:5701] disconnected.
```

Testing on the Lab, with 40Gbit

Testing with
```
boxCount=9
memberBox=0
members=3
clients=900
duration=15m
```

sim test set
```
txnConflict@class=com.hazelcast.simulator.tests.map.MapTransactionContextConflictTest
txnConflict@threadCount=3
txnConflict@keyCount=50
txnConflict@maxKeysPerTxn=5
txnConflict@throwCommitException=false
txnConflict@throwRollBackException=false
txnConflict@basename=txnConflict
```

```
Failure[
   message='Worked ran into an unhandled exception'
   type=WORKER_EXCEPTION
   timestamp=1452686683677
   workerAddress=C_A2_W86
   agentAddress=10.212.1.102
   hzAddress=client:10.212.1.102
   workerId=worker-10.212.1.102-86-client
   test=TestCase{
        id=txnConflict,
        class=com.hazelcast.simulator.tests.map.MapTransactionContextConflictTest,
        basename=txnConflict,
        keyCount=50,
        maxKeysPerTxn=5,
        threadCount=3,
        throwCommitException=false,
        throwRollBackException=false
    }
   cause=com.hazelcast.spi.exception.TargetDisconnectedException: Target[Address[10.212.40.102]:5701] disconnected.
	at com.hazelcast.client.spi.impl.ClientInvocationServiceSupport$CleanResourcesTask$1.createNew(ClientInvocationServiceSupport.java:230)
	at com.hazelcast.client.spi.impl.ClientInvocationServiceSupport$CleanResourcesTask$1.createNew(ClientInvocationServiceSupport.java:227)
	at com.hazelcast.client.spi.impl.ClientInvocationServiceSupport.cleanResources(ClientInvocationServiceSupport.java:174)
	at com.hazelcast.client.spi.impl.ClientSmartInvocationServiceImpl.cleanResources(ClientSmartInvocationServiceImpl.java:31)
	at com.hazelcast.client.spi.impl.ClientInvocationServiceSupport$CleanResourcesTask.run(ClientInvocationServiceSupport.java:227)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)
	at ------ End remote and begin local stack-trace ------.(Unknown Source)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveResponse(ClientInvocationFuture.java:133)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.get(ClientInvocationFuture.java:100)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.get(ClientInvocationFuture.java:75)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.get(ClientInvocationFuture.java:38)
	at com.hazelcast.client.proxy.txn.ClientTxnProxy.invoke(ClientTxnProxy.java:48)
	at com.hazelcast.client.proxy.txn.ClientTxnMapProxy.getForUpdate(ClientTxnMapProxy.java:81)
	at com.hazelcast.simulator.tests.map.MapTransactionContextConflictTest$Worker.run(MapTransactionContextConflictTest.java:113)
	at java.lang.Thread.run(Thread.java:745)
	at com.hazelcast.simulator.utils.ThreadSpawner$ReportExceptionThread.run(ThreadSpawner.java:183)
]
```

**Comment by Danny-Hazelcast** [comment]
logs at

ls /nfs/danny/issue7312
worker-10.212.1.101-1-member
worker-10.212.1.102-1-member
worker-10.212.1.103-1-member

**Comment by jerrinot** [comment]
First observation: I'm trying my own run on AWS. there are tons of messages like this:
```
WARN  2016-01-13 13:56:42,037 [txnConflict-Thread-2] com.hazelcast.simulator.tests.map.MapTransactionContextConflictTest: txnConflict: commit failed. tried key increments=[]
com.hazelcast.transaction.TransactionException: Transaction couldn't obtain lock for the key: 48
```

**Comment by jerrinot** [comment]
the test is practically guaranteed to make no progress with sufficient number of clients. 
that's probably intentional and still it does not explain the `TargetDisconnectedException`

**Comment by Danny-Hazelcast** [comment]
yes its intentional and in the name txnConflict@class=com.hazelcast.simulator.tests.map.MapTransactionContextConflictTest

**Comment by jerrinot** [comment]
I think the `TargetDisconnectedException` is just a side-effect of something else. Simulator decided to shutdown the test for some reason. Hence clients received the `TargetDisconnectedException`
```
worker-10.212.1.101-1-member/worker.log:INFO  2016-01-13 14:04:44,339 [nioEventLoopGroup-3-1] com.hazelcast.simulator.protocol.processors.TestOperationProcessor: --------------------------- Stopping txnConflict ---------------------------
worker-10.212.1.102-1-member/worker.log:INFO  2016-01-13 14:04:44,336 [nioEventLoopGroup-3-1] com.hazelcast.simulator.protocol.processors.TestOperationProcessor: --------------------------- Stopping txnConflict ---------------------------
worker-10.212.1.103-1-member/worker.log:INFO  2016-01-13 14:04:44,335 [nioEventLoopGroup-3-1] com.hazelcast.simulator.protocol.processors.TestOperationProcessor: --------------------------- Stopping txnConflict ---------------------------
```

```
worker-10.212.1.101-1-member/worker.log:INFO  2016-01-13 14:04:47,058 [WorkerShutdownThread] com.hazelcast.simulator.worker.MemberWorker: Stopping HazelcastInstance...
worker-10.212.1.102-1-member/worker.log:INFO  2016-01-13 14:04:47,003 [WorkerShutdownThread] com.hazelcast.simulator.worker.MemberWorker: Stopping HazelcastInstance...
worker-10.212.1.103-1-member/worker.log:INFO  2016-01-13 14:04:46,996 [WorkerShutdownThread] com.hazelcast.simulator.worker.MemberWorker: Stopping HazelcastInstance...
```

**Comment by jerrinot** [comment]
the question is what's the real root cause. Unfortunately we do not have enough logs retained to tell this.

**Comment by jerrinot** [comment]
this is worrying:
```
worker-10.212.1.101-1-member/worker.log:ERROR 2016-01-13 14:04:46,628 [hz._hzInstance_1_workers.client.thread-389] com.hazelcast.client.impl.protocol.task.transaction.TransactionCreateMessageTask: [10.212.40.101]:5701 [workers] [3.6-SNAPSHOT] Client ClientEndpoint{conn=Connection [0.0.0.0/0.0.0.0:5701 -> null], endpoint=Address[10.212.40.105]:45257, alive=false, type=JAVA_CLIENT, principal='ClientPrincipal{uuid='645a6c98-1495-4b33-b3fe-b2fe980b535b', ownerUuid='9cd7e5df-a45e-47ca-80f6-c3d184c78f96'}', firstConnection=false, authenticated=false} must authenticate before any operation.
```

**Comment by gurbuzali** [comment]
some findings:
Logs starts at `14:02:54,002` and first exception is a connection-lost at `14:04:43,546`
```
INFO  2016-01-13 14:04:43,546 [hz._hzInstance_1_workers.IO.thread-in-2] com.hazelcast.nio.tcp.TcpIpConnection: [10.212.40.101]:5701 [workers] [3.6-SNAPSHOT] Connection [Address[10.212.40.102]:58761] lost. Reason: java.io.EOFException[Remote socket closed!]
```
related port is `58761` and logs containing that port are below:
```
INFO  2016-01-13 14:03:28,546 [hz._hzInstance_1_workers.IO.thread-Acceptor] com.hazelcast.nio.tcp.SocketAcceptorThread: [10.212.40.101]:5701 [workers] [3.6-SNAPSHOT] Accepting socket connection from /10.212.40.102:58761
INFO  2016-01-13 14:03:28,547 [cached1] com.hazelcast.nio.tcp.TcpIpConnectionManager: [10.212.40.101]:5701 [workers] [3.6-SNAPSHOT] Established socket connection between /10.212.40.101:5701 and /10.212.40.102:58761
INFO  2016-01-13 14:03:28,556 [hz._hzInstance_1_workers.client.thread-38] com.hazelcast.client.impl.protocol.task.AuthenticationMessageTask: [10.212.40.101]:5701 [workers] [3.6-SNAPSHOT] Received auth from Connection [/10.212.40.101:5701 -> /10.212.40.102:58761], endpoint=null, alive=true, type=JAVA_CLIENT, successfully authenticated, principal : ClientPrincipal{uuid='b45dc903-b218-428b-b0c1-379dee2251a8', ownerUuid='eee430cf-4759-4197-90de-4b071f293c4f'}, owner connection : true
INFO  2016-01-13 14:04:43,546 [hz._hzInstance_1_workers.IO.thread-in-2] com.hazelcast.nio.tcp.TcpIpConnection: [10.212.40.101]:5701 [workers] [3.6-SNAPSHOT] Connection [Address[10.212.40.102]:58761] lost. Reason: java.io.EOFException[Remote socket closed!]
WARN  2016-01-13 14:04:43,547 [hz._hzInstance_1_workers.IO.thread-in-2] com.hazelcast.nio.tcp.nonblocking.NonBlockingSocketReader: [10.212.40.101]:5701 [workers] [3.6-SNAPSHOT] hz._hzInstance_1_workers.IO.thread-in-2 Closing socket to endpoint Address[10.212.40.102]:58761, Cause:java.io.EOFException: Remote socket closed!
INFO  2016-01-13 14:04:43,548 [hz._hzInstance_1_workers.event-3] com.hazelcast.client.ClientEndpointManager: [10.212.40.101]:5701 [workers] [3.6-SNAPSHOT] Destroying ClientEndpoint{conn=Connection [0.0.0.0/0.0.0.0:5701 -> /10.212.40.102:58761], endpoint=Address[10.212.40.102]:58761, alive=false, type=JAVA_CLIENT, principal='ClientPrincipal{uuid='b45dc903-b218-428b-b0c1-379dee2251a8', ownerUuid='eee430cf-4759-4197-90de-4b071f293c4f'}', firstConnection=true, authenticated=true}
ERROR 2016-01-13 14:04:46,650 [hz._hzInstance_1_workers.client.thread-389] com.hazelcast.client.impl.protocol.task.PingMessageTask: [10.212.40.101]:5701 [workers] [3.6-SNAPSHOT] Client ClientEndpoint{conn=Connection [0.0.0.0/0.0.0.0:5701 -> null], endpoint=Address[10.212.40.102]:58761, alive=false, type=JAVA_CLIENT, principal='ClientPrincipal{uuid='b45dc903-b218-428b-b0c1-379dee2251a8', ownerUuid='eee430cf-4759-4197-90de-4b071f293c4f'}', firstConnection=true, authenticated=false} must authenticate before any operation.
INFO  2016-01-13 14:04:46,650 [hz._hzInstance_1_workers.client.thread-389] com.hazelcast.client.ClientEndpointManager: [10.212.40.101]:5701 [workers] [3.6-SNAPSHOT] Destroying ClientEndpoint{conn=Connection [0.0.0.0/0.0.0.0:5701 -> null], endpoint=Address[10.212.40.102]:58761, alive=false, type=JAVA_CLIENT, principal='ClientPrincipal{uuid='b45dc903-b218-428b-b0c1-379dee2251a8', ownerUuid='eee430cf-4759-4197-90de-4b071f293c4f'}', firstConnection=true, authenticated=false}
ERROR 2016-01-13 14:04:46,651 [hz._hzInstance_1_workers.client.thread-389] com.hazelcast.client.impl.protocol.task.GetPartitionsMessageTask: [10.212.40.101]:5701 [workers] [3.6-SNAPSHOT] Client ClientEndpoint{conn=Connection [0.0.0.0/0.0.0.0:5701 -> null], endpoint=Address[10.212.40.102]:58761, alive=false, type=JAVA_CLIENT, principal='ClientPrincipal{uuid='b45dc903-b218-428b-b0c1-379dee2251a8', ownerUuid='eee430cf-4759-4197-90de-4b071f293c4f'}', firstConnection=true, authenticated=false} must authenticate before any operation.
INFO  2016-01-13 14:04:46,651 [hz._hzInstance_1_workers.client.thread-389] com.hazelcast.client.ClientEndpointManager: [10.212.40.101]:5701 [workers] [3.6-SNAPSHOT] Destroying ClientEndpoint{conn=Connection [0.0.0.0/0.0.0.0:5701 -> null], endpoint=Address[10.212.40.102]:58761, alive=false, type=JAVA_CLIENT, principal='ClientPrincipal{uuid='b45dc903-b218-428b-b0c1-379dee2251a8', ownerUuid='eee430cf-4759-4197-90de-4b071f293c4f'}', firstConnection=true, authenticated=false}
ERROR 2016-01-13 14:04:46,781 [hz._hzInstance_1_workers.client.thread-410] com.hazelcast.client.impl.protocol.task.PingMessageTask: [10.212.40.101]:5701 [workers] [3.6-SNAPSHOT] Client ClientEndpoint{conn=Connection [0.0.0.0/0.0.0.0:5701 -> null], endpoint=Address[10.212.40.102]:58761, alive=false, type=JAVA_CLIENT, principal='ClientPrincipal{uuid='b45dc903-b218-428b-b0c1-379dee2251a8', ownerUuid='eee430cf-4759-4197-90de-4b071f293c4f'}', firstConnection=true, authenticated=false} must authenticate before any operation.
INFO  2016-01-13 14:04:46,781 [hz._hzInstance_1_workers.client.thread-410] com.hazelcast.client.ClientEndpointManager: [10.212.40.101]:5701 [workers] [3.6-SNAPSHOT] Destroying ClientEndpoint{conn=Connection [0.0.0.0/0.0.0.0:5701 -> null], endpoint=Address[10.212.40.102]:58761, alive=false, type=JAVA_CLIENT, principal='ClientPrincipal{uuid='b45dc903-b218-428b-b0c1-379dee2251a8', ownerUuid='eee430cf-4759-4197-90de-4b071f293c4f'}', firstConnection=true, authenticated=false}
ERROR 2016-01-13 14:04:46,848 [hz._hzInstance_1_workers.client.thread-410] com.hazelcast.client.impl.protocol.task.PingMessageTask: [10.212.40.101]:5701 [workers] [3.6-SNAPSHOT] Client ClientEndpoint{conn=Connection [0.0.0.0/0.0.0.0:5701 -> null], endpoint=Address[10.212.40.102]:58761, alive=false, type=JAVA_CLIENT, principal='ClientPrincipal{uuid='b45dc903-b218-428b-b0c1-379dee2251a8', ownerUuid='eee430cf-4759-4197-90de-4b071f293c4f'}', firstConnection=true, authenticated=false} must authenticate before any operation.
INFO  2016-01-13 14:04:46,848 [hz._hzInstance_1_workers.client.thread-410] com.hazelcast.client.ClientEndpointManager: [10.212.40.101]:5701 [workers] [3.6-SNAPSHOT] Destroying ClientEndpoint{conn=Connection [0.0.0.0/0.0.0.0:5701 -> null], endpoint=Address[10.212.40.102]:58761, alive=false, type=JAVA_CLIENT, principal='ClientPrincipal{uuid='b45dc903-b218-428b-b0c1-379dee2251a8', ownerUuid='eee430cf-4759-4197-90de-4b071f293c4f'}', firstConnection=true, authenticated=false}
ERROR 2016-01-13 14:04:46,848 [hz._hzInstance_1_workers.client.thread-389] com.hazelcast.client.impl.protocol.task.GetPartitionsMessageTask: [10.212.40.101]:5701 [workers] [3.6-SNAPSHOT] Client ClientEndpoint{conn=Connection [0.0.0.0/0.0.0.0:5701 -> null], endpoint=Address[10.212.40.102]:58761, alive=false, type=JAVA_CLIENT, principal='ClientPrincipal{uuid='b45dc903-b218-428b-b0c1-379dee2251a8', ownerUuid='eee430cf-4759-4197-90de-4b071f293c4f'}', firstConnection=true, authenticated=false} must authenticate before any operation.
INFO  2016-01-13 14:04:46,848 [hz._hzInstance_1_workers.client.thread-389] com.hazelcast.client.ClientEndpointManager: [10.212.40.101]:5701 [workers] [3.6-SNAPSHOT] Destroying ClientEndpoint{conn=Connection [0.0.0.0/0.0.0.0:5701 -> null], endpoint=Address[10.212.40.102]:58761, alive=false, type=JAVA_CLIENT, principal='ClientPrincipal{uuid='b45dc903-b218-428b-b0c1-379dee2251a8', ownerUuid='eee430cf-4759-4197-90de-4b071f293c4f'}', firstConnection=true, authenticated=false}
ERROR 2016-01-13 14:04:46,926 [hz._hzInstance_1_workers.client.thread-360] com.hazelcast.client.impl.protocol.task.PingMessageTask: [10.212.40.101]:5701 [workers] [3.6-SNAPSHOT] Client ClientEndpoint{conn=Connection [0.0.0.0/0.0.0.0:5701 -> null], endpoint=Address[10.212.40.102]:58761, alive=false, type=JAVA_CLIENT, principal='ClientPrincipal{uuid='b45dc903-b218-428b-b0c1-379dee2251a8', ownerUuid='eee430cf-4759-4197-90de-4b071f293c4f'}', firstConnection=true, authenticated=false} must authenticate before any operation.
INFO  2016-01-13 14:04:46,926 [hz._hzInstance_1_workers.client.thread-360] com.hazelcast.client.ClientEndpointManager: [10.212.40.101]:5701 [workers] [3.6-SNAPSHOT] Destroying ClientEndpoint{conn=Connection [0.0.0.0/0.0.0.0:5701 -> null], endpoint=Address[10.212.40.102]:58761, alive=false, type=JAVA_CLIENT, principal='ClientPrincipal{uuid='b45dc903-b218-428b-b0c1-379dee2251a8', ownerUuid='eee430cf-4759-4197-90de-4b071f293c4f'}', firstConnection=true, authenticated=false}
ERROR 2016-01-13 14:04:47,058 [hz._hzInstance_1_workers.client.thread-389] com.hazelcast.client.impl.protocol.task.PingMessageTask: [10.212.40.101]:5701 [workers] [3.6-SNAPSHOT] Client ClientEndpoint{conn=Connection [0.0.0.0/0.0.0.0:5701 -> null], endpoint=Address[10.212.40.102]:58761, alive=false, type=JAVA_CLIENT, principal='ClientPrincipal{uuid='b45dc903-b218-428b-b0c1-379dee2251a8', ownerUuid='eee430cf-4759-4197-90de-4b071f293c4f'}', firstConnection=true, authenticated=false} must authenticate before any operation.
INFO  2016-01-13 14:04:47,058 [hz._hzInstance_1_workers.client.thread-389] com.hazelcast.client.ClientEndpointManager: [10.212.40.101]:5701 [workers] [3.6-SNAPSHOT] Destroying ClientEndpoint{conn=Connection [0.0.0.0/0.0.0.0:5701 -> null], endpoint=Address[10.212.40.102]:58761, alive=false, type=JAVA_CLIENT, principal='ClientPrincipal{uuid='b45dc903-b218-428b-b0c1-379dee2251a8', ownerUuid='eee430cf-4759-4197-90de-4b071f293c4f'}', firstConnection=true, authenticated=false}
INFO  2016-01-13 14:04:47,090 [hz._hzInstance_1_workers.client.thread-389] com.hazelcast.client.ClientEndpointManager: [10.212.40.101]:5701 [workers] [3.6-SNAPSHOT] Destroying ClientEndpoint{conn=Connection [0.0.0.0/0.0.0.0:5701 -> null], endpoint=Address[10.212.40.102]:58761, alive=false, type=JAVA_CLIENT, principal='ClientPrincipal{uuid='b45dc903-b218-428b-b0c1-379dee2251a8', ownerUuid='eee430cf-4759-4197-90de-4b071f293c4f'}', firstConnection=true, authenticated=false}
INFO  2016-01-13 14:04:47,193 [hz._hzInstance_1_workers.client.thread-389] com.hazelcast.client.ClientEndpointManager: [10.212.40.101]:5701 [workers] [3.6-SNAPSHOT] Destroying ClientEndpoint{conn=Connection [0.0.0.0/0.0.0.0:5701 -> null], endpoint=Address[10.212.40.102]:58761, alive=false, type=JAVA_CLIENT, principal='ClientPrincipal{uuid='b45dc903-b218-428b-b0c1-379dee2251a8', ownerUuid='eee430cf-4759-4197-90de-4b071f293c4f'}', firstConnection=true, authenticated=false}
INFO  2016-01-13 14:04:47,316 [hz._hzInstance_1_workers.client.thread-389] com.hazelcast.client.ClientEndpointManager: [10.212.40.101]:5701 [workers] [3.6-SNAPSHOT] Destroying ClientEndpoint{conn=Connection [0.0.0.0/0.0.0.0:5701 -> null], endpoint=Address[10.212.40.102]:58761, alive=false, type=JAVA_CLIENT, principal='ClientPrincipal{uuid='b45dc903-b218-428b-b0c1-379dee2251a8', ownerUuid='eee430cf-4759-4197-90de-4b071f293c4f'}', firstConnection=true, authenticated=false}
INFO  2016-01-13 14:04:47,317 [hz._hzInstance_1_workers.client.thread-389] com.hazelcast.client.ClientEndpointManager: [10.212.40.101]:5701 [workers] [3.6-SNAPSHOT] Destroying ClientEndpoint{conn=Connection [0.0.0.0/0.0.0.0:5701 -> null], endpoint=Address[10.212.40.102]:58761, alive=false, type=JAVA_CLIENT, principal='ClientPrincipal{uuid='b45dc903-b218-428b-b0c1-379dee2251a8', ownerUuid='eee430cf-4759-4197-90de-4b071f293c4f'}', firstConnection=true, authenticated=false}
INFO  2016-01-13 14:04:47,490 [hz._hzInstance_1_workers.client.thread-389] com.hazelcast.client.ClientEndpointManager: [10.212.40.101]:5701 [workers] [3.6-SNAPSHOT] Destroying ClientEndpoint{conn=Connection [0.0.0.0/0.0.0.0:5701 -> null], endpoint=Address[10.212.40.102]:58761, alive=false, type=JAVA_CLIENT, principal='ClientPrincipal{uuid='b45dc903-b218-428b-b0c1-379dee2251a8', ownerUuid='eee430cf-4759-4197-90de-4b071f293c4f'}', firstConnection=true, authenticated=false}
INFO  2016-01-13 14:04:47,616 [hz._hzInstance_1_workers.client.thread-410] com.hazelcast.client.ClientEndpointManager: [10.212.40.101]:5701 [workers] [3.6-SNAPSHOT] Destroying ClientEndpoint{conn=Connection [0.0.0.0/0.0.0.0:5701 -> null], endpoint=Address[10.212.40.102]:58761, alive=false, type=JAVA_CLIENT, principal='ClientPrincipal{uuid='b45dc903-b218-428b-b0c1-379dee2251a8', ownerUuid='eee430cf-4759-4197-90de-4b071f293c4f'}', firstConnection=true, authenticated=false}
INFO  2016-01-13 14:04:47,617 [hz._hzInstance_1_workers.client.thread-389] com.hazelcast.client.ClientEndpointManager: [10.212.40.101]:5701 [workers] [3.6-SNAPSHOT] Destroying ClientEndpoint{conn=Connection [0.0.0.0/0.0.0.0:5701 -> null], endpoint=Address[10.212.40.102]:58761, alive=false, type=JAVA_CLIENT, principal='ClientPrincipal{uuid='b45dc903-b218-428b-b0c1-379dee2251a8', ownerUuid='eee430cf-4759-4197-90de-4b071f293c4f'}', firstConnection=true, authenticated=false}
INFO  2016-01-13 14:04:47,678 [hz._hzInstance_1_workers.client.thread-410] com.hazelcast.client.ClientEndpointManager: [10.212.40.101]:5701 [workers] [3.6-SNAPSHOT] Destroying ClientEndpoint{conn=Connection [0.0.0.0/0.0.0.0:5701 -> null], endpoint=Address[10.212.40.102]:58761, alive=false, type=JAVA_CLIENT, principal='ClientPrincipal{uuid='b45dc903-b218-428b-b0c1-379dee2251a8', ownerUuid='eee430cf-4759-4197-90de-4b071f293c4f'}', firstConnection=true, authenticated=false}
INFO  2016-01-13 14:04:47,710 [hz._hzInstance_1_workers.client.thread-427] com.hazelcast.client.ClientEndpointManager: [10.212.40.101]:5701 [workers] [3.6-SNAPSHOT] Destroying ClientEndpoint{conn=Connection [0.0.0.0/0.0.0.0:5701 -> null], endpoint=Address[10.212.40.102]:58761, alive=false, type=JAVA_CLIENT, principal='ClientPrincipal{uuid='b45dc903-b218-428b-b0c1-379dee2251a8', ownerUuid='eee430cf-4759-4197-90de-4b071f293c4f'}', firstConnection=true, authenticated=false}
INFO  2016-01-13 14:04:47,710 [hz._hzInstance_1_workers.client.thread-427] com.hazelcast.client.ClientEndpointManager: [10.212.40.101]:5701 [workers] [3.6-SNAPSHOT] Destroying ClientEndpoint{conn=Connection [0.0.0.0/0.0.0.0:5701 -> null], endpoint=Address[10.212.40.102]:58761, alive=false, type=JAVA_CLIENT, principal='ClientPrincipal{uuid='b45dc903-b218-428b-b0c1-379dee2251a8', ownerUuid='eee430cf-4759-4197-90de-4b071f293c4f'}', firstConnection=true, authenticated=false}
```

Test finishes at `14:08:45,198`

**Comment by pveentjer** [comment]
@jerrinot what do to with this issue? I would like to prevent automatic movement to 3.8.

**Comment by jerrinot** [comment]
Re-running the test it with the latest master should give us more info what's going.

**Comment by tombujok** [comment]
@jerrinot @pveentjer @Danny-Hazelcast @gurbuzali Have we run the test again? What's the outcome?

**Comment by jerrinot** [comment]
@Danny-Hazelcast Did you manage to reproduce this as we discussed last week?

**Comment by Danny-Hazelcast** [comment]
@jerrinot  I have retested the same scenario withe OS HZ hat master. and could not reproduce this issue.  Given @pveentjer it looking into a generic TargetDisconnectedException issue.

I think we can close this issue.
