### ISSUE TITLE
Reliable topic => StaleSequenceException

### ISSUE THREAD

**Issue by nilskp** [hazelcast/hazelcast#7317]
If a reliable `ITtopic` has a (`RingBuffer` with) small capacity and a `ReliableMessageListener` subscribes with a sequence number smaller than what's available (even when both `isLossTolerant = true` and `isTerminal = false`), it fails:
```
Caused by: com.hazelcast.ringbuffer.StaleSequenceException: sequence:0 is too small. The current headSequence is:2 tailSequence is:4
	at com.hazelcast.ringbuffer.impl.RingbufferContainer.checkBlockableReadSequence(RingbufferContainer.java:177)
	at com.hazelcast.ringbuffer.impl.operations.ReadManyOperation.beforeRun(ReadManyOperation.java:66)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:166)
	at com.hazelcast.spi.impl.operationexecutor.classic.ClassicOperationExecutor.runOnCallingThread(ClassicOperationExecutor.java:392)
	at com.hazelcast.spi.impl.operationexecutor.classic.ClassicOperationExecutor.runOnCallingThreadIfPossible(ClassicOperationExecutor.java:345)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:259)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:243)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invokeInternal(Invocation.java:210)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:180)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:46)
	at com.hazelcast.client.impl.protocol.task.AbstractPartitionMessageTask.processMessage(AbstractPartitionMessageTask.java:65)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:121)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:100)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:127)
	at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.processPartitionSpecificRunnable(OperationThread.java:159)
	at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.process(OperationThread.java:142)
	at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.doRun(OperationThread.java:124)
	at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.run(OperationThread.java:99)
```

**Comment by eminn** [comment]
Do you have a reproducer for this issue ?

**Comment by vbekiaris** [comment]
My attempt at reproducing this issue is at https://github.com/vbekiaris/hazelcast-issues. When the listener sequence is outside head-tail, a `StaleSequenceException` is thrown for any combination of `isLossTolerant`/`isTerminal`. If the message listener is loss-tolerant, it is provided with currently available messages and future updates, otherwise the listener is terminated. The same behavior is observed in both 3.6 and 3.6.1 releases (the committed pom references version 3.6).

**Comment by pveentjer** [comment]
It appears that your listener is still running fine; but you get this exception being logged on the serverside.

**Comment by vbekiaris** [comment]
Yes, I agree this does not seem like an actual defect as it does not break the listener.

**Comment by nilskp** [comment]
For a RingBuffer with capacity 3, this is what I would expect:

Publish "A" (seq:0)
Publish "B" (seq:1)
Publish "C" (seq:2)
Publish "D" (seq:3)
Publish "E" (seq:4)

Now add listener, with `retrieveInitialSequence` = `0`, I would expect to get `onMessage` invoked for "C", "D", and "E", but that does not happen.

**Comment by nilskp** [comment]
Unit test:
```java
public class TestTopic {

    static final String smallRB = "smallRB";
    static final int smallRBCapacity = 3;

    private static HazelcastInstance[] hzs = new HazelcastInstance[3];

    @BeforeClass
    public static void setup() {
        Config conf = new Config();
        RingbufferConfig rbConf = new RingbufferConfig(smallRB);
        rbConf.setCapacity(smallRBCapacity);
        conf.addRingBufferConfig(rbConf);
        for (int i = 0; i < hzs.length; i++) {
            hzs[i] = Hazelcast.newHazelcastInstance(conf);
        }
    }

    @AfterClass
    public static void teardown() {
        for (HazelcastInstance hz : hzs) {
            hz.shutdown();
        }
    }

  @Test
  public void stale() throws InterruptedException {
    ClientConfig conf = new ClientConfig();
    conf.getNetworkConfig().addAddress("localhost");
    HazelcastInstance client = HazelcastClient.newHazelcastClient(conf);
    final List<String> messages = Arrays.asList("a", "b", "c", "d", "e");
    final CountDownLatch cdl = new CountDownLatch(smallRBCapacity);
    ITopic<String> rTopic = client.getReliableTopic(smallRB);
    for (String message : messages) {
        rTopic.publish(message);
    }
    ReliableMessageListener<String> listener = new ReliableMessageListener<String>() {
        long seq;
        public void onMessage(Message<String> msg) {
            System.out.println("Got message" + msg.getMessageObject());
            assertEquals(messages.size() - cdl.getCount(), (int) seq);
            assertEquals(messages.get((int) seq), msg.getMessageObject());
            cdl.countDown();
        }
        public long retrieveInitialSequence() {
            return 0;
        }
        public void storeSequence(long sequence) {
            seq = sequence;
        }
        public boolean isLossTolerant() {
            return true;
        }
        public boolean isTerminal(Throwable failure) {
            return true;
        }
    };
    String reg = rTopic.addMessageListener(listener);
    assertTrue(cdl.await(5, TimeUnit.SECONDS));
    rTopic.removeMessageListener(reg);
  }
}
```

**Comment by vbekiaris** [comment]
Thanks @nilskp for the reproducer. Interestingly, this issue only manifests in client-server mode as demonstrated by above reproducer. The following test (same as above, however in embedded mode) passes successfully:

```
    @Test
    public void staleEmbedded() throws InterruptedException {
        Config conf = new Config();
        RingbufferConfig rbConf = new RingbufferConfig(smallRB);
        rbConf.setCapacity(smallRBCapacity);
        conf.addRingBufferConfig(rbConf);
        HazelcastInstance hz = Hazelcast.newHazelcastInstance(conf);
        final List<String> messages = Arrays.asList("a", "b", "c", "d", "e");
        final CountDownLatch cdl = new CountDownLatch(smallRBCapacity);
        ITopic<String> rTopic = hz.getReliableTopic(smallRB);
        for (String message : messages) {
            rTopic.publish(message);
        }
        ReliableMessageListener<String> listener = new ReliableMessageListener<String>() {
            long seq;
            public void onMessage(Message<String> msg) {
                System.out.println("Got message" + msg.getMessageObject());
                assertEquals(messages.size() - cdl.getCount(), (int) seq);
                assertEquals(messages.get((int) seq), msg.getMessageObject());
                cdl.countDown();
            }
            public long retrieveInitialSequence() {
                return 0;
            }
            public void storeSequence(long sequence) {
                seq = sequence;
            }
            public boolean isLossTolerant() {
                return true;
            }
            public boolean isTerminal(Throwable failure) {
                return true;
            }
        };
        String reg = rTopic.addMessageListener(listener);
        assertTrue(cdl.await(5, TimeUnit.SECONDS));
        rTopic.removeMessageListener(reg);
    }
```

**Comment by vbekiaris** [comment]
In `ClientReliableTopicProxy.MessageRunner.onFailure(Throwable t)`, code looks for a `StaleSequenceException` in order to jump to the current head, in case the listener is loss tolerant. However the `StaleSequenceException` comes wrapped within a `java.util.concurrent.ExecutionException`, therefore this code path is never activated.

On the embedded side, the same code is properly executed in `ReliableMessageListenerRunner.onFailure(Throwable t)` as the `StaleSequenceException` is delivered as-is.

**Comment by vbekiaris** [comment]
Additionally, the `StaleSequenceException` resurrected on the client side does not carry over the `headSeq` value from the server-side, it is always 0. This is also demonstrated in https://github.com/vbekiaris/hazelcast/commit/26f62b08a76b216a6f645fa1e05eeac1f105b697

A client protocol update is required to fix this issue.

**Comment by vbekiaris** [comment]
I have committed a fix at https://github.com/vbekiaris/hazelcast/commit/bc5a7be1e6ffd21b935be1ddc35b0b15cccb1b87. As discussed with @sancar and @asimarslan , instead of retrieving the topic's head sequence from the `StaleSequenceException` (which will always be 0 on the client side), we now use `ringbuffer.headSequence()` which obtains the actual head sequence, at the cost of an additional remote invocation.
Note that the need for a remote invocation for `ringbuffer.headSequence()` can be further confined within the condition at https://github.com/vbekiaris/hazelcast/commit/bc5a7be1e6ffd21b935be1ddc35b0b15cccb1b87#diff-a67c8d5d9f043676fe755602a10c35e7R271 however the warning that is logged at https://github.com/vbekiaris/hazelcast/commit/bc5a7be1e6ffd21b935be1ddc35b0b15cccb1b87#diff-a67c8d5d9f043676fe755602a10c35e7R284 requires that we log the head sequence, so we cannot move it inside the condition, unless we agree to not log the head sequence.
