### ISSUE TITLE
WanReplicationTest failures

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#7352]
**entryProcessorTest**
```
java.lang.AssertionError: expected:<10> but was:<9>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.wan.impl.WanReplicationTest.entryProcessorTest(WanReplicationTest.java:78)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.8/com.hazelcast$hazelcast/101/testReport/junit/com.hazelcast.wan.impl/WanReplicationTest/entryProcessorTest/

**Comment by hasancelik** [comment]
**maintenance**
```
java.lang.AssertionError: expected:<10> but was:<9>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.wan.impl.WanReplicationTest.entryProcessorTest(WanReplicationTest.java:78)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.maintenance-OracleJDK1.6/com.hazelcast$hazelcast/335/testReport/junit/com.hazelcast.wan.impl/WanReplicationTest/entryProcessorTest/

**Comment by hasancelik** [comment]
**mapPutRemoveTest**
```
java.lang.AssertionError: expected:<20> but was:<19>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.wan.impl.WanReplicationTest.mapPutRemoveTest(WanReplicationTest.java:66)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-ZuluJDK6/com.hazelcast$hazelcast/95/testReport/junit/com.hazelcast.wan.impl/WanReplicationTest/mapPutRemoveTest/

**Comment by emrahkocaman** [comment]
@hasancelik , I've sent a fix, let's monitor it for some time.
