### ISSUE TITLE
ClientExceptionFactoryTest.testException Failures

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#7360]
```
org.junit.internal.ArrayComparisonFailure: arrays first differed at element [13]; expected: java.lang.StackTraceElement<<unknown class>.<unknown method>(Unknown Source)> but was: java.lang.StackTraceElement<<unknown class>.<unknown method>(Unknown Source)>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at org.junit.internal.ExactComparisonCriteria.assertElementsEqual(ExactComparisonCriteria.java:8)
	at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:53)
	at org.junit.Assert.internalArrayEquals(Assert.java:532)
	at org.junit.Assert.assertArrayEquals(Assert.java:283)
	at org.junit.Assert.assertArrayEquals(Assert.java:298)
	at com.hazelcast.client.protocol.ClientExceptionFactoryTest.testException(ClientExceptionFactoryTest.java:198)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.7/792/#showFailuresLink

**maintenance**
https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.maintenance-IbmJDK1.8/32/#showFailuresLink

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK1.7/794/#showFailuresLink

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK1.8/104/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.maintenance-IbmJDK1.7/344/#showFailuresLink

**Comment by sancar** [comment]
closed via https://github.com/hazelcast/hazelcast/commit/3e8fbafa03b070547d036996479f201e21c7611a
