### ISSUE TITLE
com.hazelcast.config.InvalidConfigurationException: Your xsd schema couldn't be load

### ISSUE THREAD

**Issue by lifengllk** [hazelcast/hazelcast#7371]
hazelcast-client.xml  version 3.5.4
```
<?xml version="1.0" encoding="UTF-8"?>
<hazelcast-client xsi:schemaLocation="http://www.hazelcast.com/schema/client-config hazelcast-client-config-3.5.xsd"
       xmlns="http://www.hazelcast.com/schema/client-config"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <network>
        <cluster-members>
       	          <address>192.168.35.61</address>
			<address>192.168.35.62</address>
			<address>192.168.35.63</address>
        </cluster-members>
    </network>
</hazelcast-client>
```
IN JAVA:
```
Config cfg = new XmlConfigBuilder("hazelcast-client.xml").build();
			HazelcastInstance hz = Hazelcast.newHazelcastInstance(cfg);
```

Error Below:
JAXP: using thread context class loader (sun.misc.Launcher$AppClassLoader@73d16e93) for search
JAXP: Looking up system property 'javax.xml.xpath.XPathFactory:http://java.sun.com/jaxp/xpath/dom'
JAXP: The property is undefined.
JAXP: found null in $java.home/jaxp.properties
JAXP: attempting to use the platform default W3C DOM XPath lib
JAXP: createInstance(com.sun.org.apache.xpath.internal.jaxp.XPathFactoryImpl)
JAXP: loaded com.sun.org.apache.xpath.internal.jaxp.XPathFactoryImpl from jar:file:/C:/Java/jdk1.8.0_25/jre/lib/rt.jar!/com/sun/org/apache/xpath/internal/jaxp/XPathFactoryImpl.class
JAXP: factory 'com.sun.org.apache.xpath.internal.jaxp.XPathFactoryImpl' was found for http://java.sun.com/jaxp/xpath/dom
JAXP: find factoryId =javax.xml.parsers.DocumentBuilderFactory
JAXP: loaded from fallback value: com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderFactoryImpl
JAXP: created new instance of class com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderFactoryImpl using ClassLoader: null
com.hazelcast.config.InvalidConfigurationException: Your xsd schema couldn't be load
	at com.hazelcast.config.AbstractXmlConfigHelper.loadSchemaFile(AbstractXmlConfigHelper.java:205)
	at com.hazelcast.config.AbstractXmlConfigHelper.schemaValidation(AbstractXmlConfigHelper.java:164)
	at com.hazelcast.config.XmlConfigBuilder.parseAndBuildConfig(XmlConfigBuilder.java:212)
	at com.hazelcast.config.XmlConfigBuilder.build(XmlConfigBuilder.java:195)
	at com.hazelcast.config.XmlConfigBuilder.build(XmlConfigBuilder.java:188)
	at com.gts2.AggregationsDemo.main(AggregationsDemo.java:51)

**Comment by lifengllk** [comment]
resolved by add dependency:
···
<dependency>
		<groupId>com.hazelcast</groupId>
		<artifactId>hazelcast-client</artifactId>
		<version>3.5.4</version>
	</dependency>
···

but another error  as below:

```
一月 20, 2016 2:16:50 下午 com.hazelcast.config.ClasspathXmlConfig
信息: Configuring Hazelcast from 'hazelcast-client.xml'.
JAXP: using thread context class loader (sun.misc.Launcher$AppClassLoader@73d16e93) for search
JAXP: Looking up system property 'javax.xml.xpath.XPathFactory:http://java.sun.com/jaxp/xpath/dom'
JAXP: The property is undefined.
JAXP: found null in $java.home/jaxp.properties
JAXP: attempting to use the platform default W3C DOM XPath lib
JAXP: createInstance(com.sun.org.apache.xpath.internal.jaxp.XPathFactoryImpl)
JAXP: loaded com.sun.org.apache.xpath.internal.jaxp.XPathFactoryImpl from jar:file:/C:/Java/jdk1.8.0_25/jre/lib/rt.jar!/com/sun/org/apache/xpath/internal/jaxp/XPathFactoryImpl.class
JAXP: factory 'com.sun.org.apache.xpath.internal.jaxp.XPathFactoryImpl' was found for http://java.sun.com/jaxp/xpath/dom
JAXP: find factoryId =javax.xml.parsers.DocumentBuilderFactory
JAXP: loaded from fallback value: com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderFactoryImpl
JAXP: created new instance of class com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderFactoryImpl using ClassLoader: null
JAXP: find factoryId =javax.xml.transform.TransformerFactory
JAXP: found system property, value=com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl
JAXP: created new instance of class com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl using ClassLoader: null
JAXP: using thread context class loader (sun.misc.Launcher$AppClassLoader@73d16e93) for search
JAXP: Looking up system property 'javax.xml.validation.SchemaFactory:http://www.w3.org/2001/XMLSchema'
JAXP: The property is undefined.
JAXP: found null in $java.home/jaxp.properties
JAXP: attempting to use the platform default XML Schema validator
JAXP: createInstance(com.sun.org.apache.xerces.internal.jaxp.validation.XMLSchemaFactory)
JAXP: loaded com.sun.org.apache.xerces.internal.jaxp.validation.XMLSchemaFactory from jar:file:/C:/Java/jdk1.8.0_25/jre/lib/rt.jar!/com/sun/org/apache/xerces/internal/jaxp/validation/XMLSchemaFactory.class
JAXP: factory 'com.sun.org.apache.xerces.internal.jaxp.validation.XMLSchemaFactory' was found for http://www.w3.org/2001/XMLSchema
com.hazelcast.config.InvalidConfigurationException: cvc-elt.1: 找不到元素 'hazelcast-client' 的声明。
	at com.hazelcast.config.AbstractXmlConfigHelper.schemaValidation(AbstractXmlConfigHelper.java:193)
	at com.hazelcast.config.XmlConfigBuilder.parseAndBuildConfig(XmlConfigBuilder.java:212)
	at com.hazelcast.config.XmlConfigBuilder.build(XmlConfigBuilder.java:195)
	at com.hazelcast.config.ClasspathXmlConfig.<init>(ClasspathXmlConfig.java:100)
	at com.hazelcast.config.ClasspathXmlConfig.<init>(ClasspathXmlConfig.java:57)
	at com.hazelcast.config.ClasspathXmlConfig.<init>(ClasspathXmlConfig.java:44)
	at com.gts2.AggregationsDemo.main(AggregationsDemo.java:48)
```

**Comment by lifengllk** [comment]
resolved, since I use java client, I should use code as below:
```
ClientConfig clientcfg = new XmlClientConfigBuilder("hazelcast-client.xml").build();
HazelcastInstance hz = HazelcastClient.newHazelcastClient(clientcfg);
```

thanks!
