### ISSUE TITLE
SystemClockChangeTest failures [HZ-1834]

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#7408]
**testCluster_whenSlaveClockJumpsForward**

```
java.lang.AssertionError: Cluster should be stable when system clock changes! expected:<2> but was:<1>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:834)
    at org.junit.Assert.assertEquals(Assert.java:645)
    at com.hazelcast.cluster.SystemClockChangeTest.assertClusterSizeAlways(SystemClockChangeTest.java:132)
    at com.hazelcast.cluster.SystemClockChangeTest.testCluster_whenSlaveClockJumpsForward(SystemClockChangeTest.java:99)
```

**testCluster_whenMasterClockJumpsForward**

```
java.lang.AssertionError: Cluster time should be equal to master time! expected:<1.453851074083E12> but was:<1.453849274088E12>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:834)
    at org.junit.Assert.assertEquals(Assert.java:553)
    at com.hazelcast.cluster.SystemClockChangeTest.assertClusterTime(SystemClockChangeTest.java:125)
    at com.hazelcast.cluster.SystemClockChangeTest.testCluster_whenMasterClockJumpsForward(SystemClockChangeTest.java:77)
```

**testCluster_whenSlaveClockJumpsBackward**

```
java.lang.AssertionError: Cluster should be stable when system clock changes! expected:<2> but was:<1>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:834)
    at org.junit.Assert.assertEquals(Assert.java:645)
    at com.hazelcast.cluster.SystemClockChangeTest.assertClusterSizeAlways(SystemClockChangeTest.java:132)
    at com.hazelcast.cluster.SystemClockChangeTest.testCluster_whenSlaveClockJumpsBackward(SystemClockChangeTest.java:110)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-nightly/844/

**Comment by metanet** [comment]
https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.maintenance-nightly/com.hazelcast$hazelcast/747/
https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.maintenance-nightly/com.hazelcast$hazelcast/749/

Copied from #7444

**Comment by hasancelik** [comment]
**testCluster_whenSlaveClockJumpsForward**
```
java.lang.AssertionError: Cluster should be stable when system clock changes! expected:<2> but was:<1>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.cluster.SystemClockChangeTest.assertClusterSizeAlways(SystemClockChangeTest.java:132)
	at com.hazelcast.cluster.SystemClockChangeTest.testCluster_whenSlaveClockJumpsForward(SystemClockChangeTest.java:99)
```
**testCluster_whenMasterClockJumpsBackward**
```
java.lang.AssertionError: Cluster time should be equal to master time! expected:<1.455568626108E12> but was:<1.455566826113E12>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:553)
	at com.hazelcast.cluster.SystemClockChangeTest.assertClusterTime(SystemClockChangeTest.java:125)
	at com.hazelcast.cluster.SystemClockChangeTest.testCluster_whenMasterClockJumpsBackward(SystemClockChangeTest.java:89)
```
**estCluster_whenSlaveClockJumpsBackward**
```
java.lang.AssertionError: Cluster should be stable when system clock changes! expected:<2> but was:<1>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.cluster.SystemClockChangeTest.assertClusterSizeAlways(SystemClockChangeTest.java:132)
	at com.hazelcast.cluster.SystemClockChangeTest.testCluster_whenSlaveClockJumpsBackward(SystemClockChangeTest.java:110)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.maintenance-nightly/763/

**Comment by hasancelik** [comment]
**testCluster_whenSlaveClockJumpsBackward**
```
java.lang.AssertionError: Cluster time should be (approx.) equal to master time! expected:<1.456280752582E12> but was:<1.456282552586E12>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:553)
	at com.hazelcast.cluster.SystemClockChangeTest.assertClusterTime(SystemClockChangeTest.java:183)
	at com.hazelcast.cluster.SystemClockChangeTest.testCluster_whenSlaveClockJumpsBackward(SystemClockChangeTest.java:174)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/872/testReport/junit/com.hazelcast.cluster/SystemClockChangeTest/testCluster_whenSlaveClockJumpsBackward/

**Comment by mdogan** [comment]
Hmm.. problem is; cluster clock on slave is adjusted twice after its local clock drifted backwards. First by master heartbeat and then by local member which detects the clock jump.

**Comment by sumnerib** [comment]
Failed again on _master_ with OracleJDK8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-OracleJDK8-nightly/921/testReport/junit/com.hazelcast.cluster/SystemClockChangeTest/testCluster_whenMasterClockJumpsBackward/

**Comment by ramizdundar** [comment]
See https://github.com/hazelcast/hazelcast/pull/24227#issuecomment-1503331803

**Comment by sumnerib** [comment]
Reopening as issue occurred again on: _5.3.z_ (commit c93e1cca30ac94ad008f27c300db5edc58b59954)
with oracle-8: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-OracleJDK8-nightly/122/testReport/junit/com.hazelcast.cluster/SystemClockChangeTest/testCluster_whenMasterClockJumpsBackward/

<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: Cluster time should be (approx.) equal to master time! expected:<1.704746129956E12> but was:<1.704746134727E12>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:555)
	at com.hazelcast.internal.util.AbstractClockTest.assertClusterTime(AbstractClockTest.java:149)
	at com.hazelcast.internal.util.AbstractClockTest.assertClusterTime(AbstractClockTest.java:123)
	at com.hazelcast.internal.util.AbstractClockTest.assertClusterTime(AbstractClockTest.java:119)
	at com.hazelcast.cluster.SystemClockChangeTest.testCluster_whenMasterClockJumpsBackward(SystemClockChangeTest.java:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:750)

```
</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: testCluster_whenMasterClockJumpsForward in 33.957 seconds.
Started Running Test: testCluster_whenMasterClockJumpsBackward
20:34:55,887  INFO |testCluster_whenMasterClockJumpsBackward| - [MetricsConfigHelper] testCluster_whenMasterClockJumpsBackward - [LOCAL] [dev] [5.3.7-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
20:34:55,927  INFO |testCluster_whenMasterClockJumpsBackward| - [logo] testCluster_whenMasterClockJumpsBackward - [127.0.0.1]:5701 [dev] [5.3.7-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
20:34:55,927  INFO |testCluster_whenMasterClockJumpsBackward| - [system] testCluster_whenMasterClockJumpsBackward - [127.0.0.1]:5701 [dev] [5.3.7-SNAPSHOT] Copyright (c) 2008-2023, Hazelcast, Inc. All Rights Reserved.
20:34:55,927  INFO |testCluster_whenMasterClockJumpsBackward| - [system] testCluster_whenMasterClockJumpsBackward - [127.0.0.1]:5701 [dev] [5.3.7-SNAPSHOT] Hazelcast Platform 5.3.7-SNAPSHOT (20240108 - c93e1cc) starting at [127.0.0.1]:5701
20:34:55,927  INFO |testCluster_whenMasterClockJumpsBackward| - [system] testCluster_whenMasterClockJumpsBackward - [127.0.0.1]:5701 [dev] [5.3.7-SNAPSHOT] Cluster name: dev
20:34:55,927  INFO |testCluster_whenMasterClockJumpsBackward| - [system] testCluster_whenMasterClockJumpsBackward - [127.0.0.1]:5701 [dev] [5.3.7-SNAPSHOT] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed. For more information, see the documentation for Integrity Checker.
20:34:55,929  INFO |testCluster_whenMasterClockJumpsBackward| - [system] testCluster_whenMasterClockJumpsBackward - [127.0.0.1]:5701 [dev] [5.3.7-SNAPSHOT] The Jet engine is disabled.
To enable the Jet engine on the members, do one of the following:
  - Change member config using Java API: config.getJetConfig().setEnabled(true)
  - Change XML/YAML configuration property: Set hazelcast.jet.enabled to true
  - Add system property: -Dhz.jet.enabled=true (for Hazelcast embedded, works only when loading config via Config.load)
  - Add environment variable: HZ_JET_ENABLED=true (recommended when running container image. For Hazelcast embedded, works only when loading config via Config.load)
20:34:56,065  INFO |testCluster_whenMasterClockJumpsBackward| - [MetricsConfigHelper] testCluster_whenMasterClockJumpsBackward - [127.0.0.1]:5701 [dev] [5.3.7-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
20:34:56,083  INFO |testCluster_whenMasterClockJumpsBackward| - [TpcServerBootstrap] testCluster_whenMasterClockJumpsBackward - [127.0.0.1]:5701 [dev] [5.3.7-SNAPSHOT] TPC: disabled
20:34:56,360  INFO |testCluster_whenMasterClockJumpsBackward| - [Node] testCluster_whenMasterClockJumpsBackward - [127.0.0.1]:5701 [dev] [5.3.7-SNAPSHOT] Using Multicast discovery
20:34:56,363  WARN |testCluster_whenMasterClockJumpsBackward| - [CPSubsystem] testCluster_whenMasterClockJumpsBackward - [127.0.0.1]:5701 [dev] [5.3.7-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
20:34:56,578  INFO |testCluster_whenMasterClockJumpsBackward| - [Diagnostics] testCluster_whenMasterClockJumpsBackward - [127.0.0.1]:5701 [dev] [5.3.7-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
20:34:56,583  INFO |testCluster_whenMasterClockJumpsBackward| - [LifecycleService] testCluster_whenMasterClockJumpsBackward - [127.0.0.1]:5701 [dev] [5.3.7-SNAPSHOT] [127.0.0.1]:5701 is STARTING
20:34:58,674  INFO |testCluster_whenMasterClockJumpsBackward| - [ClusterService] testCluster_whenMasterClockJumpsBackward - [127.0.0.1]:5701 [dev] [5.3.7-SNAPSHOT] 

Members {size:1, ver:1} [
	Member [127.0.0.1]:5701 - e86353c9-5e8a-462f-9ec7-da511888a5d1 this
]

20:34:58,702  INFO |testCluster_whenMasterClockJumpsBackward| - [LifecycleService] testCluster_whenMasterClockJumpsBackward - [127.0.0.1]:5701 [dev] [5.3.7-SNAPSHOT] [127.0.0.1]:5701 is STARTED
20:34:58,704  INFO |testCluster_whenMasterClockJumpsBackward| - [MetricsConfigHelper] testCluster_whenMasterClockJumpsBackward - [LOCAL] [dev] [5.3.7-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
20:34:58,706  INFO |testCluster_whenMasterClockJumpsBackward| - [logo] testCluster_whenMasterClockJumpsBackward - [127.0.0.1]:5702 [dev] [5.3.7-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
20:34:58,706  INFO |testCluster_whenMasterClockJumpsBackward| - [system] testCluster_whenMasterClockJumpsBackward - [127.0.0.1]:5702 [dev] [5.3.7-SNAPSHOT] Copyright (c) 2008-2023, Hazelcast, Inc. All Rights Reserved.
20:34:58,706  INFO |testCluster_whenMasterClockJumpsBackward| - [system] testCluster_whenMasterClockJumpsBackward - [127.0.0.1]:5702 [dev] [5.3.7-SNAPSHOT] Hazelcast Platform 5.3.7-SNAPSHOT (20240108 - c93e1cc) starting at [127.0.0.1]:5702
20:34:58,706  INFO |testCluster_whenMasterClockJumpsBackward| - [system] testCluster_whenMasterClockJumpsBackward - [127.0.0.1]:5702 [dev] [5.3.7-SNAPSHOT] Cluster name: dev
20:34:58,706  INFO |testCluster_whenMasterClockJumpsBackward| - [system] testCluster_whenMasterClockJumpsBackward - [127.0.0.1]:5702 [dev] [5.3.7-SNAPSHOT] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed. For more information, see the documentation for Integrity Checker.
20:34:58,706  INFO |testCluster_whenMasterClockJumpsBackward| - [system] testCluster_whenMasterClockJumpsBackward - [127.0.0.1]:5702 [dev] [5.3.7-SNAPSHOT] Jet is enabled
20:34:58,716  INFO |testCluster_whenMasterClockJumpsBackward| - [MetricsConfigHelper] testCluster_whenMasterClockJumpsBackward - [127.0.0.1]:5702 [dev] [5.3.7-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
20:34:58,716  INFO |testCluster_whenMasterClockJumpsBackward| - [TpcServerBootstrap] testCluster_whenMasterClockJumpsBackward - [127.0.0.1]:5702 [dev] [5.3.7-SNAPSHOT] TPC: disabled
20:34:58,729  INFO |testCluster_whenMasterClockJumpsBackward| - [Node] testCluster_whenMasterClockJumpsBackward - [127.0.0.1]:5702 [dev] [5.3.7-SNAPSHOT] Using Multicast discovery
20:34:58,729  WARN |testCluster_whenMasterClockJumpsBackward| - [CPSubsystem] testCluster_whenMasterClockJumpsBackward - [127.0.0.1]:5702 [dev] [5.3.7-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
20:34:58,736  INFO |testCluster_whenMasterClockJumpsBackward| - [JetServiceBackend] testCluster_whenMasterClockJumpsBackward - [127.0.0.1]:5702 [dev] [5.3.7-SNAPSHOT] Setting number of cooperative threads and default parallelism to 8
20:34:58,738  INFO |testCluster_whenMasterClockJumpsBackward| - [Diagnostics] testCluster_whenMasterClockJumpsBackward - [127.0.0.1]:5702 [dev] [5.3.7-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
20:34:58,738  INFO |testCluster_whenMasterClockJumpsBackward| - [LifecycleService] testCluster_whenMasterClockJumpsBackward - [127.0.0.1]:5702 [dev] [5.3.7-SNAPSHOT] [127.0.0.1]:5702 is STARTING
20:34:58,814  INFO |testCluster_whenMasterClockJumpsBackward| - [MulticastJoiner] testCluster_whenMasterClockJumpsBackward - [127.0.0.1]:5702 [dev] [5.3.7-SNAPSHOT] Trying to join to discovered node: [127.0.0.1]:5701
20:34:58,836  INFO |testCluster_whenMasterClockJumpsBackward| - [TcpServerConnection] hz.SystemClockChangeTest_pedantic_shamir.IO.thread-in-0 - [127.0.0.1]:5701 [dev] [5.3.7-SNAPSHOT] Initialized new cluster connection between /127.0.0.1:5701 and /127.0.0.1:46707
20:34:58,838  INFO |testCluster_whenMasterClockJumpsBackward| - [TcpServerConnection] hz.SystemClockChangeTest_sweet_turing.IO.thread-in-0 - [127.0.0.1]:5702 [dev] [5.3.7-SNAPSHOT] Initialized new cluster connection between /0.0.0.0:46707 and /127.0.0.1:5701
20:34:59,931  INFO |testCluster_whenMasterClockJumpsBackward| - [ClusterService] hz.SystemClockChangeTest_pedantic_shamir.priority-generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [5.3.7-SNAPSHOT] 

Members {size:2, ver:2} [
	Member [127.0.0.1]:5701 - e86353c9-5e8a-462f-9ec7-da511888a5d1 this
	Member [127.0.0.1]:5702 - d1180a67-e8eb-497e-b6c2-a0e9d71fb18c
]

20:34:59,951  INFO |testCluster_whenMasterClockJumpsBackward| - [ClusterService] hz.SystemClockChangeTest_sweet_turing.priority-generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.3.7-SNAPSHOT] 

Members {size:2, ver:2} [
	Member [127.0.0.1]:5701 - e86353c9-5e8a-462f-9ec7-da511888a5d1
	Member [127.0.0.1]:5702 - d1180a67-e8eb-497e-b6c2-a0e9d71fb18c this
]

20:34:59,952  INFO |testCluster_whenMasterClockJumpsBackward| - [JobCoordinationService] testCluster_whenMasterClockJumpsBackward - [127.0.0.1]:5702 [dev] [5.3.7-SNAPSHOT] Jet started scanning for jobs
20:34:59,952  INFO |testCluster_whenMasterClockJumpsBackward| - [LifecycleService] testCluster_whenMasterClockJumpsBackward - [127.0.0.1]:5702 [dev] [5.3.7-SNAPSHOT] [127.0.0.1]:5702 is STARTED
20:35:11,568  INFO |testCluster_whenMasterClockJumpsBackward| - [ClusterHeartbeatManager] hz.SystemClockChangeTest_pedantic_shamir.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.3.7-SNAPSHOT] System clock apparently jumped from 2024-01-08 20:35:10.567 to 2024-01-08 20:05:11.567 since last heartbeat (-1800000 ms)
20:35:11,568  WARN |testCluster_whenMasterClockJumpsBackward| - [ClusterHeartbeatManager] hz.SystemClockChangeTest_pedantic_shamir.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.3.7-SNAPSHOT] Resetting heartbeat timestamps because of huge system clock jump! Clock-Jump: -1800000 ms, Heartbeat-Timeout: 10000 ms
20:35:35,582  INFO |testCluster_whenMasterClockJumpsBackward| - [LifecycleService] main - [127.0.0.1]:5702 [dev] [5.3.7-SNAPSHOT] [127.0.0.1]:5702 is SHUTTING_DOWN
20:35:35,582  WARN |testCluster_whenMasterClockJumpsBackward| - [Node] main - [127.0.0.1]:5702 [dev] [5.3.7-SNAPSHOT] Terminating forcefully...
20:35:35,582  INFO |testCluster_whenMasterClockJumpsBackward| - [Node] main - [127.0.0.1]:5702 [dev] [5.3.7-SNAPSHOT] Shutting down multicast service...
20:35:35,582  INFO |testCluster_whenMasterClockJumpsBackward| - [Node] main - [127.0.0.1]:5702 [dev] [5.3.7-SNAPSHOT] Shutting down connection manager...
20:35:35,583  INFO |testCluster_whenMasterClockJumpsBackward| - [TcpServerConnection] main - [127.0.0.1]:5702 [dev] [5.3.7-SNAPSHOT] Connection[id=1, /0.0.0.0:46707->/127.0.0.1:5701, qualifier=null, endpoint=[127.0.0.1]:5701, remoteUuid=e86353c9-5e8a-462f-9ec7-da511888a5d1, alive=false, connectionType=MEMBER, planeIndex=0] closed. Reason: TcpServer is stopping
20:35:35,583  INFO |testCluster_whenMasterClockJumpsBackward| - [Node] main - [127.0.0.1]:5702 [dev] [5.3.7-SNAPSHOT] Shutting down node engine...
20:35:35,584  INFO |testCluster_whenMasterClockJumpsBackward| - [TcpServerConnection] hz.SystemClockChangeTest_pedantic_shamir.IO.thread-in-0 - [127.0.0.1]:5701 [dev] [5.3.7-SNAPSHOT] Connection[id=1, /127.0.0.1:5701->/127.0.0.1:46707, qualifier=null, endpoint=[127.0.0.1]:5702, remoteUuid=d1180a67-e8eb-497e-b6c2-a0e9d71fb18c, alive=false, connectionType=MEMBER, planeIndex=0] closed. Reason: Connection closed by the other side
20:35:35,633  INFO |testCluster_whenMasterClockJumpsBackward| - [NodeExtension] main - [127.0.0.1]:5702 [dev] [5.3.7-SNAPSHOT] Destroying node NodeExtension.
20:35:35,633  INFO |testCluster_whenMasterClockJumpsBackward| - [Node] main - [127.0.0.1]:5702 [dev] [5.3.7-SNAPSHOT] Hazelcast Shutdown is completed in 51 ms.
20:35:35,633  INFO |testCluster_whenMasterClockJumpsBackward| - [LifecycleService] main - [127.0.0.1]:5702 [dev] [5.3.7-SNAPSHOT] [127.0.0.1]:5702 is SHUTDOWN
20:35:35,633  INFO |testCluster_whenMasterClockJumpsBackward| - [LifecycleService] main - [127.0.0.1]:5701 [dev] [5.3.7-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
20:35:35,638  INFO |testCluster_whenMasterClockJumpsBackward| - [TcpServerConnector] hz.SystemClockChangeTest_pedantic_shamir.cached.thread-11 - [127.0.0.1]:5701 [dev] [5.3.7-SNAPSHOT] Connecting to /127.0.0.1:5702, timeout: 10000, bind-any: true
20:35:35,639  INFO |testCluster_whenMasterClockJumpsBackward| - [TcpServerConnector] hz.SystemClockChangeTest_pedantic_shamir.cached.thread-11 - [127.0.0.1]:5701 [dev] [5.3.7-SNAPSHOT] Could not connect to: /127.0.0.1:5702. Reason: IOException[Connection refused to address /127.0.0.1:5702]
20:35:35,660  INFO |testCluster_whenMasterClockJumpsBackward| - [Node] main - [127.0.0.1]:5701 [dev] [5.3.7-SNAPSHOT] Shutting down multicast service...
20:35:35,661  INFO |testCluster_whenMasterClockJumpsBackward| - [Node] main - [127.0.0.1]:5701 [dev] [5.3.7-SNAPSHOT] Shutting down connection manager...
20:35:35,674  INFO |testCluster_whenMasterClockJumpsBackward| - [Node] main - [127.0.0.1]:5701 [dev] [5.3.7-SNAPSHOT] Shutting down node engine...
20:35:35,696  INFO |testCluster_whenMasterClockJumpsBackward| - [NodeExtension] main - [127.0.0.1]:5701 [dev] [5.3.7-SNAPSHOT] Destroying node NodeExtension.
20:35:35,696  INFO |testCluster_whenMasterClockJumpsBackward| - [Node] main - [127.0.0.1]:5701 [dev] [5.3.7-SNAPSHOT] Hazelcast Shutdown is completed in 61 ms.
20:35:35,696  INFO |testCluster_whenMasterClockJumpsBackward| - [LifecycleService] main - [127.0.0.1]:5701 [dev] [5.3.7-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
BuildInfo right after testCluster_whenMasterClockJumpsBackward(com.hazelcast.cluster.SystemClockChangeTest): BuildInfo{version='5.3.7-SNAPSHOT', build='20240108', buildNumber=20240108, revision=c93e1cc, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'testCluster_whenMasterClockJumpsBackward(com.hazelcast.cluster.SystemClockChangeTest):'
20:34:55, accumulated pauses: 62 ms, max pause: 0 ms, pauses over 1000 ms: 0
20:35:00, accumulated pauses: 65 ms, max pause: 0 ms, pauses over 1000 ms: 0
20:35:05, accumulated pauses: 65 ms, max pause: 0 ms, pauses over 1000 ms: 0
20:35:10, accumulated pauses: 66 ms, max pause: 0 ms, pauses over 1000 ms: 0
20:35:15, accumulated pauses: 65 ms, max pause: 0 ms, pauses over 1000 ms: 0
20:35:20, accumulated pauses: 66 ms, max pause: 0 ms, pauses over 1000 ms: 0
20:35:25, accumulated pauses: 4823 ms, max pause: 4758 ms, pauses over 1000 ms: 1
20:35:30, accumulated pauses: 452 ms, max pause: 452 ms, pauses over 1000 ms: 0
20:35:35, accumulated pauses: 8 ms, max pause: 3 ms, pauses over 1000 ms: 0


No metrics recorded during the test

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-5.maintenance-OracleJDK8-nightly/122/

**Comment by olukas** [comment]
Closing the test failure - it doesn't seem to be related to `master` or the latest maintenance stream `5.5.z` and it hasn't fail in the last 3 months. Feel free to reopen test failure if it occurs on `master` or on the latest maintenance stream.
