### ISSUE TITLE
FrozenPartitionTableTest.partitionTable_isFrozen_whenNodesLeave_duringClusterStateIsFrozen

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#7409]
```
java.lang.AssertionError: expected:<3> but was:<1>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.partition.impl.FrozenPartitionTableTest.assertPartitionTablesSame(FrozenPartitionTableTest.java:170)
	at com.hazelcast.partition.impl.FrozenPartitionTableTest.testPartitionTableIsFrozenDuring(FrozenPartitionTableTest.java:104)
	at com.hazelcast.partition.impl.FrozenPartitionTableTest.partitionTable_isFrozen_whenNodesLeave_duringClusterStateIsFrozen(FrozenPartitionTableTest.java:36)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-ZuluJDK7/com.hazelcast$hazelcast/97/testReport/junit/com.hazelcast.partition.impl/FrozenPartitionTableTest/partitionTable_isFrozen_whenNodesLeave_duringClusterStateIsFrozen/

**Comment by mdogan** [comment]
See https://github.com/hazelcast/hazelcast/issues/7463
