### ISSUE TITLE
CacheStatsTest.testOwnedEntryCountWhenThereAreBackupsOnDynamicCluster

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#7422]
```
java.lang.AssertionError: expected:<100> but was:<99>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.cache.stats.CacheStatsTest.doTestForOwnedEntryCount(CacheStatsTest.java:490)
	at com.hazelcast.cache.stats.CacheStatsTest.testOwnedEntryCountWhenThereAreBackupsOnDynamicCluster(CacheStatsTest.java:400)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK1.6/com.hazelcast$hazelcast/803/testReport/junit/com.hazelcast.cache.stats/CacheStatsTest/testOwnedEntryCountWhenThereAreBackupsOnDynamicCluster/

**Comment by serkan-ozal** [comment]
should be fixed via https://github.com/hazelcast/hazelcast/commit/73f147b426ccbf1336946554531cd9e4f0ff7df8
