### ISSUE TITLE
Ringbuffer IllegalArgumentException: sequence:102 is too large. The current tailSequence is:12

### ISSUE THREAD

**Issue by manishag** [hazelcast/hazelcast#7431]
I am getting following exception when in a 4 node cluster, 2 of the nodes are killed

```
Exception in thread "Thread-3" java.lang.IllegalArgumentException: sequence:102 is too large. The current tailSequence is:12
	at com.hazelcast.ringbuffer.impl.RingbufferContainer.checkBlockableReadSequence(RingbufferContainer.java:171)
	at com.hazelcast.ringbuffer.impl.operations.ReadOneOperation.beforeRun(ReadOneOperation.java:46)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:135)
	at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.processOperation(OperationThread.java:154)
	at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.process(OperationThread.java:110)
	at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.doRun(OperationThread.java:101)
	at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.run(OperationThread.java:76)
```

**Comment by bwzhang2011** [comment]
@pveentjer, any update with such issue ?

**Comment by gurbuzali** [comment]
This is an expected exception. RingBuffer has 1 backup as default, this means ringbuffer data will be held in 2 nodes (primary and backup). If these nodes goes down at the same time then it is expected that the data will be lost and you will get `IllegalArgumentException`

You may increase the backup count(via RingBufferConfig) if you want the ringbuffer to be resilient to 2 node failures
