### ISSUE TITLE
Hazelcast 3.6 unble to connect client. I have verfied the hazelcast.xml in bin. anybody can help? [ Hazel cast run on aws EC2 instance on default port. 1507 checked]

### ISSUE THREAD

**Issue by saurabhsharmaj** [hazelcast/hazelcast#7433]
Jan 31, 2016 7:17:57 PM com.hazelcast.client.spi.impl.ClusterListenerSupport
    WARNING: Exception during initial connection to /127.0.0.1:5701
    com.hazelcast.client.AuthenticationException: Invalid credentials!
            at com.hazelcast.client.spi.impl.ClusterListenerSupport$ManagerAuthenticator.authenticate(ClusterListenerSupport.java:153)
            at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.authenticate(ClientConnectionManagerImpl.java:249)
            at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.initializeConnection(ClientConnectionManagerImpl.java:220)
            at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.getOrConnect(ClientConnectionManagerImpl.java:211)
            at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.getOrConnect(ClientConnectionManagerImpl.java:67)
            at com.hazelcast.client.spi.impl.ClusterListenerSupport.connect(ClusterListenerSupport.java:241)
            at com.hazelcast.client.spi.impl.ClusterListenerSupport.connectToOne(ClusterListenerSupport.java:209)
            at com.hazelcast.client.spi.impl.ClusterListenerSupport.connectToCluster(ClusterListenerSupport.java:161)
            at com.hazelcast.client.spi.impl.ClientClusterServiceImpl.start(ClientClusterServiceImpl.java:203)
            at com.hazelcast.client.impl.HazelcastClientInstanceImpl.start(HazelcastClientInstanceImpl.java:303)
            at com.hazelcast.client.HazelcastClient.newHazelcastClient(HazelcastClient.java:86)
            at Hazel.main(Hazel.java:13)

    Jan 31, 2016 7:17:57 PM com.hazelcast.client.connection.nio.ClientConnection
    WARNING: Connection [/172.31.29.162:5701] lost. Reason: com.hazelcast.client.AuthenticationException[Invalid credentials!]
    Jan 31, 2016 7:17:57 PM com.hazelcast.client.spi.impl.ClusterListenerSupport
    WARNING: Exception during initial connection to /172.31.29.162:5701
    com.hazelcast.client.AuthenticationException: Invalid credentials!
            at com.hazelcast.client.spi.impl.ClusterListenerSupport$ManagerAuthenticator.authenticate(ClusterListenerSupport.java:153)
            at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.authenticate(ClientConnectionManagerImpl.java:249)
            at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.initializeConnection(ClientConnectionManagerImpl.java:220)
            at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.getOrConnect(ClientConnectionManagerImpl.java:211)
            at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.getOrConnect(ClientConnectionManagerImpl.java:67)
            at com.hazelcast.client.spi.impl.ClusterListenerSupport.connect(ClusterListenerSupport.java:241)
            at com.hazelcast.client.spi.impl.ClusterListenerSupport.connectToOne(ClusterListenerSupport.java:209)
            at com.hazelcast.client.spi.impl.ClusterListenerSupport.connectToCluster(ClusterListenerSupport.java:161)
            at com.hazelcast.client.spi.impl.ClientClusterServiceImpl.start(ClientClusterServiceImpl.java:203)
            at com.hazelcast.client.impl.HazelcastClientInstanceImpl.start(HazelcastClientInstanceImpl.java:303)
            at com.hazelcast.client.HazelcastClient.newHazelcastClient(HazelcastClient.java:86)
            at Hazel.main(Hazel.java:13)

**Comment by sancar** [comment]
It looks like client and server credentials are not matching. 
See related config here
http://docs.hazelcast.org/docs/3.6/manual/html-single/index.html#creating-cluster-groups
Closing this issue. Please ask your similar question in our google group first.
https://groups.google.com/forum/#!forum/hazelcast
