### ISSUE TITLE
NullPointerException when node is joining during a MapReduce operation

### ISSUE THREAD

**Issue by sjelen** [hazelcast/hazelcast#7438]
While running a MapReduce operation, if a new node joins at the right moment it results with an NPE.
The stack trace from the supervisor node:

`com.hazelcast.core.HazelcastException: java.util.concurrent.ExecutionException: com.hazelcast.mapreduce.RemoteMapReduceException: Exception on mapreduce operation
    at com.hazelcast.map.impl.proxy.MapProxyImpl.aggregate(MapProxyImpl.java:673) ~[hazelcast-3.5.4.jar:3.5.4]
    at com.hazelcast.map.impl.proxy.MapProxyImpl.aggregate(MapProxyImpl.java:644) ~[hazelcast-3.5.4.jar:3.5.4]
    at com.mgmtp.lidl.jarvis.core.tasks.TaskManagerImpl.createDependentTasks(TaskManagerImpl.java:290) ~[jarvis-core-1.2.0.0-SNAPSHOT.jar:1.2.0.0-SNAPSHOT]
    at com.mgmtp.lidl.jarvis.core.tasks.TaskManagerImpl.postProcessTask(TaskManagerImpl.java:158) ~[jarvis-core-1.2.0.0-SNAPSHOT.jar:1.2.0.0-SNAPSHOT]
    at com.mgmtp.lidl.jarvis.core.tasks.TaskManagerImpl.finishTaskExecution(TaskManagerImpl.java:128) ~[jarvis-core-1.2.0.0-SNAPSHOT.jar:1.2.0.0-SNAPSHOT]
    at com.mgmtp.lidl.jarvis.core.tasks.PartitionedTask.call(PartitionedTask.java:67) [jarvis-core-1.2.0.0-SNAPSHOT.jar:1.2.0.0-SNAPSHOT]
    at com.mgmtp.lidl.jarvis.core.tasks.PartitionedTask.call(PartitionedTask.java:29) [jarvis-core-1.2.0.0-SNAPSHOT.jar:1.2.0.0-SNAPSHOT]
    at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_79]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
    at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
Caused by: java.util.concurrent.ExecutionException: com.hazelcast.mapreduce.RemoteMapReduceException: Exception on mapreduce operation
    at com.hazelcast.mapreduce.impl.task.TrackableJobFuture.setResult(TrackableJobFuture.java:78) ~[hazelcast-3.5.4.jar:3.5.4]
    at com.hazelcast.mapreduce.impl.task.JobSupervisor$2.run(JobSupervisor.java:344) ~[hazelcast-3.5.4.jar:3.5.4]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) ~[na:1.7.0_79]
    at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_79]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
    at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
    at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76) ~[hazelcast-3.5.4.jar:3.5.4]
    at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92) ~[hazelcast-3.5.4.jar:3.5.4]
Caused by: com.hazelcast.mapreduce.RemoteMapReduceException: Exception on mapreduce operation
    at com.hazelcast.mapreduce.impl.MapReduceUtil.executeOperation(MapReduceUtil.java:280) ~[hazelcast-3.5.4.jar:3.5.4]
    at com.hazelcast.mapreduce.impl.task.JobSupervisor$2.run(JobSupervisor.java:324) ~[hazelcast-3.5.4.jar:3.5.4]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) ~[na:1.7.0_79]
    at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_79]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
    at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
    at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76) ~[hazelcast-3.5.4.jar:3.5.4]
    at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92) ~[hazelcast-3.5.4.jar:3.5.4]
    at --- Remote Exception: null ---.(Unknown Source) ~[na:na]
    at     com.hazelcast.mapreduce.impl.task.JobSupervisor.getJobResults(JobSupervisor.java:249) ~[na:na]
    at     com.hazelcast.mapreduce.impl.operation.GetResultOperation.run(GetResultOperation.java:52) ~[na:na]
    at     com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:137) ~[na:na]
    at     com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:315) ~[na:na]
    at     com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.processPacket(OperationThread.java:142) ~[na:na]
    at     com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.process(OperationThread.java:115) ~[na:na]
    at     com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.doRun(OperationThread.java:101) ~[na:na]
    at     com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.run(OperationThread.java:76) ~[na:na]
    at     ------ End remote and begin local stack-trace ------.(Unknown Source) ~[na:na]
    at     com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveApplicationResponse(InvocationFuture.java:384) ~[na:na]
    at     com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveApplicationResponseOrThrowException(InvocationFuture.java:334) ~[na:na]
    at     com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.get(InvocationFuture.java:225) ~[na:na]
    at     com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.get(InvocationFuture.java:204) ~[na:na]
    at     com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.getSafely(InvocationFuture.java:216) ~[na:na]
    at     com.hazelcast.mapreduce.impl.MapReduceUtil.executeOperation(MapReduceUtil.java:266) ~[na:na]
    at     com.hazelcast.mapreduce.impl.task.JobSupervisor$2.run(JobSupervisor.java:324) ~[na:na]
    at     java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) ~[na:na]
    at     java.util.concurrent.FutureTask.run(FutureTask.java:262) ~[na:na]
    at     java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) ~[na:na]
    at     java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) ~[na:na]
    at     java.lang.Thread.run(Thread.java:745) ~[na:na]
    at     com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76) ~[na:na]
    at     com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92) ~[na:na]`

Stack trace from the other node:

`java.lang.NullPointerException: null
    at com.hazelcast.mapreduce.impl.task.JobSupervisor.getJobResults(JobSupervisor.java:249) ~[hazelcast-3.5.4.jar:3.5.4]
    at com.hazelcast.mapreduce.impl.operation.GetResultOperation.run(GetResultOperation.java:52) ~[hazelcast-3.5.4.jar:3.5.4]
    at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:137) [hazelcast-3.5.4.jar:3.5.4]
    at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:315) [hazelcast-3.5.4.jar:3.5.4]
    at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.processPacket(OperationThread.java:142) [hazelcast-3.5.4.jar:3.5.4]
    at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.process(OperationThread.java:115) [hazelcast-3.5.4.jar:3.5.4]
    at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.doRun(OperationThread.java:101) [hazelcast-3.5.4.jar:3.5.4]
    at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.run(OperationThread.java:76) [hazelcast-3.5.4.jar:3.5.4]`

From what I've managed to debug, `context` atomic reference points to null, hence `currentContext` is null and this is where the NPE is thrown. (JobSupervisor:249)

Hazelcast version  3.5.4
2 nodes
Both Windows and Linux platforms
Java 1.7.0_79
Full logs are attached from both nodes.
[uuid20015 - 2 nodes.zip](https://github.com/hazelcast/hazelcast/files/112336/uuid20015.-.2.nodes.zip)

We'd appreciate the fix being available in 3.5 version.

**Comment by jerrinot** [comment]
Hi @sjelen,

thanks for a nice report and analysis.

**Comment by zeratul021** [comment]
Hi @jerrinot - how severe would the fix be in your opinion? Would it be possible to fix it in 3.6 branch? Can we help somehow?

**Comment by noctarius** [comment]
Contributions are always welcomed :) It should possible to push it into 3.6 patchlevel releases as it can be added, it doesn't have to change anything in special.

**Comment by bwzhang2011** [comment]
@jerrinot, any update with such issue ? it seems a bug.

**Comment by kirhgoff** [comment]
What are consequences of that error, would cluster behave properly after that error?

**Comment by mdogan** [comment]
MapReduce is going to be deprecated and eventually removed. Won't fix.
