### ISSUE TITLE
SystemClockChangeTest failures

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#7444]
**testCluster_whenSlaveClockJumpsBackward**
**testCluster_whenSlaveClockJumpsForward**
**testCluster_whenMasterClockJumpsBackward**
**testCluster_whenMasterClockJumpsForward**
```
java.lang.AssertionError: Cluster time should be equal to master time! expected:<1.454355429247E12> but was:<1.454357229252E12>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:553)
	at com.hazelcast.cluster.SystemClockChangeTest.assertClusterTime(SystemClockChangeTest.java:125)
	at com.hazelcast.cluster.SystemClockChangeTest.testCluster_whenMasterClockJumpsForward(SystemClockChangeTest.java:77)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.maintenance-nightly/com.hazelcast$hazelcast/747/
https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.maintenance-nightly/com.hazelcast$hazelcast/749/

**Comment by metanet** [comment]
We already have another issue for this. Closing this one and copying these failures to the other one.
