### ISSUE TITLE
ClientMapTest.testLockTtl2 & testLockTtl

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#7460]
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.client.map.ClientMapTest.testLockTtl2(ClientMapTest.java:447)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.maintenance-IbmJDK1.8/com.hazelcast$hazelcast-client-legacy/42/testReport/junit/com.hazelcast.client.map/ClientMapTest/testLockTtl2/

**Comment by gurbuzali** [comment]
as a note: it is legacy client

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.client.map.ClientMapTest.testLockTtl2(ClientMapTest.java:447)
```
https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.maintenance-IbmJDK1.7/com.hazelcast$hazelcast-client/354/testReport/junit/com.hazelcast.client.map/ClientMapTest/testLockTtl2/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.client.map.ClientMapTest.testLockTtl2(ClientMapTest.java:487)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK1.8/com.hazelcast$hazelcast-client/184/testReport/junit/com.hazelcast.client.map/ClientMapTest/testLockTtl2/

**Comment by hasancelik** [comment]
maintenance
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.client.map.ClientMapTest.testLockTtl2(ClientMapTest.java:447)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.maintenance-IbmJDK1.7/com.hazelcast$hazelcast-client/370/testReport/junit/com.hazelcast.client.map/ClientMapTest/testLockTtl2/

**Comment by hasancelik** [comment]
**master**

```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.client.map.ClientMapTest.testLockTtl2(ClientMapTest.java:487)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast$hazelcast-client/884/testReport/junit/com.hazelcast.client.map/ClientMapTest/testLockTtl2/

**Comment by hasancelik** [comment]
**master**

```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.client.map.ClientMapTest.testLockTtl2(ClientMapTest.java:497)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK1.8/com.hazelcast$hazelcast-client/207/testReport/junit/com.hazelcast.client.map/ClientMapTest/testLockTtl2/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.client.map.ClientMapTest.testLockTtl2(ClientMapTest.java:497)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast$hazelcast-client/919/testReport/junit/com.hazelcast.client.map/ClientMapTest/testLockTtl2/

**Comment by hasancelik** [comment]
**master**
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.client.map.ClientMapTest.testLockTtl2(ClientMapTest.java:497)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast$hazelcast-client/922/testReport/junit/com.hazelcast.client.map/ClientMapTest/testLockTtl2/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.client.map.ClientMapTest.testLockTtl2(ClientMapTest.java:497)
```
https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK1.8/com.hazelcast$hazelcast-client/245/testReport/junit/com.hazelcast.client.map/ClientMapTest/testLockTtl2/

**Comment by hasancelik** [comment]
**testLockTtl**
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at org.junit.Assert.assertFalse(Assert.java:74)
	at com.hazelcast.client.map.ClientMapTest.testLockTtl(ClientMapTest.java:471)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK1.8/com.hazelcast$hazelcast-client/254/testReport/junit/com.hazelcast.client.map/ClientMapTest/testLockTtl/

**testLockTtl2**
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.client.map.ClientMapTest.testLockTtl2(ClientMapTest.java:497)
```
https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK1.8/com.hazelcast$hazelcast-client/254/testReport/junit/com.hazelcast.client.map/ClientMapTest/testLockTtl2/

**Comment by hasancelik** [comment]
*testLockTtl2*
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.client.map.ClientMapTest.testLockTtl2(ClientMapTest.java:497)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast$hazelcast-client/947/testReport/junit/com.hazelcast.client.map/ClientMapTest/testLockTtl2/
