### ISSUE TITLE
ExecutorServiceTest.testSubmitToAllMembersRunnable

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#7461]
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.executor.ExecutorServiceTest.testSubmitToAllMembersRunnable(ExecutorServiceTest.java:450)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-OracleJDK8/com.hazelcast$hazelcast/706/testReport/junit/com.hazelcast.executor/ExecutorServiceTest/testSubmitToAllMembersRunnable/

**Comment by vbekiaris** [comment]
This test is no longer failing.

**Comment by jerrinot** [comment]
The latest failure is from February. 

Given it's a quick test running with each merge build it's safe to assume it has been fixed as a side-effect of some other change.
