### ISSUE TITLE
Mock Connection(Manager) & Joiner problems

### ISSUE THREAD

**Issue by mdogan** [hazelcast/hazelcast#7463]
Mock Connection(Manager) & Joiner can cause failures during cluster discovery & join. Mostly this happens when a node shutdowns and restarts to rejoin to the cluster. 

This is the root cause of following test failures:

- https://github.com/hazelcast/hazelcast/issues/6383
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.8/com.hazelcast%24hazelcast/115/testReport/junit/com.hazelcast.cluster.impl/AdvancedClusterStateTest/clusterState_shouldBeFrozen_whenMemberReJoins_inFrozenState/

- https://github.com/hazelcast/hazelcast/issues/7191
https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK1.8/com.hazelcast%24hazelcast/119/testReport/junit/com.hazelcast.internal.cluster.impl/ClusterRollingRestartTest/test_rollingRestart_clusterState_FROZEN_partitionAssignmentType_NEVER_/

- https://github.com/hazelcast/hazelcast/issues/7409
https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-ZuluJDK7/com.hazelcast%24hazelcast/97/testReport/junit/com.hazelcast.partition.impl/FrozenPartitionTableTest/partitionTable_isFrozen_whenNodesLeave_duringClusterStateIsFrozen/

**Comment by mdogan** [comment]
It seems there are still problems: https://github.com/hazelcast/hazelcast/issues/8026

**Comment by mdogan** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/2894/testReport/junit/com.hazelcast.mapreduce/MapReduceLiteMemberTest/testMapper/

```
java.lang.IllegalStateException: Node failed to start!
    at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:135)
    at com.hazelcast.instance.DefaultHazelcastInstanceFactory.newHazelcastInstance(DefaultHazelcastInstanceFactory.java:38)
    at com.hazelcast.instance.HazelcastInstanceManager.constructHazelcastInstance(HazelcastInstanceManager.java:227)
    at com.hazelcast.instance.HazelcastInstanceManager.newHazelcastInstance(HazelcastInstanceManager.java:185)
    at com.hazelcast.test.TestHazelcastInstanceFactory.newHazelcastInstance(TestHazelcastInstanceFactory.java:116)
    at com.hazelcast.test.TestHazelcastInstanceFactory.newHazelcastInstance(TestHazelcastInstanceFactory.java:103)
    at com.hazelcast.mapreduce.MapReduceLiteMemberTest.before(MapReduceLiteMemberTest.java:44)
```

**Comment by mdogan** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/2897/

```
org.junit.runners.model.TestTimedOutException: test timed out after 60000 milliseconds
    at java.lang.Thread.sleep(Native Method)
    at com.hazelcast.test.mocknetwork.MockJoiner.doJoin(MockJoiner.java:75)
    at com.hazelcast.internal.cluster.impl.AbstractJoiner.join(AbstractJoiner.java:118)
    at com.hazelcast.instance.Node.join(Node.java:607)
    at com.hazelcast.instance.Node.start(Node.java:357)
    at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:133)
    at com.hazelcast.instance.DefaultHazelcastInstanceFactory.newHazelcastInstance(DefaultHazelcastInstanceFactory.java:38)
    at com.hazelcast.instance.HazelcastInstanceManager.constructHazelcastInstance(HazelcastInstanceManager.java:227)
    at com.hazelcast.instance.HazelcastInstanceManager.newHazelcastInstance(HazelcastInstanceManager.java:185)
    at com.hazelcast.test.TestHazelcastInstanceFactory.newHazelcastInstance(TestHazelcastInstanceFactory.java:116)
    at com.hazelcast.test.TestHazelcastInstanceFactory.newHazelcastInstance(TestHazelcastInstanceFactory.java:103)
    at com.hazelcast.mapreduce.MapReduceTest.testExceptionDistribution(MapReduceTest.java:238)
```

**Comment by mdogan** [comment]
Added more log: https://github.com/hazelcast/hazelcast/commit/ba957ccbf45ab9aff2b547ffa5762dd99c1d67e1
