### ISSUE TITLE
[ZING-JVM] Quorum failures

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#7497]
**com.hazelcast.quorum.map.MapWriteQuorumTest**
```
com.hazelcast.quorum.map.MapWriteQuorumTest Time elapsed: 0 sec <<< ERROR!
java.lang.ClassCastException: com.hazelcast.nio.tcp.TcpIpConnectionManager cannot be cast to com.hazelcast.nio.tcp.FirewallingMockConnectionManager
at com.hazelcast.quorum.PartitionedCluster.getConnectionManager(PartitionedCluster.java:187)
at com.hazelcast.quorum.PartitionedCluster.splitCluster(PartitionedCluster.java:147)
at com.hazelcast.quorum.PartitionedCluster.splitFiveMembersThreeAndTwo(PartitionedCluster.java:105)
at com.hazelcast.quorum.PartitionedCluster.partitionFiveMembersThreeAndTwo(PartitionedCluster.java:57)
at com.hazelcast.quorum.map.MapWriteQuorumTest.initialize(MapWriteQuorumTest.java:71)
```
**com.hazelcast.quorum.map.MapReadWriteQuorumTest**
```
com.hazelcast.quorum.map.MapReadWriteQuorumTest Time elapsed: 0 sec <<< ERROR!
java.lang.ClassCastException: com.hazelcast.nio.tcp.TcpIpConnectionManager cannot be cast to com.hazelcast.nio.tcp.FirewallingMockConnectionManager
at com.hazelcast.quorum.PartitionedCluster.getConnectionManager(PartitionedCluster.java:187)
at com.hazelcast.quorum.PartitionedCluster.splitCluster(PartitionedCluster.java:147)
at com.hazelcast.quorum.PartitionedCluster.splitFiveMembersThreeAndTwo(PartitionedCluster.java:105)
at com.hazelcast.quorum.PartitionedCluster.partitionFiveMembersThreeAndTwo(PartitionedCluster.java:57)
at com.hazelcast.quorum.map.MapReadWriteQuorumTest.initialize(MapReadWriteQuorumTest.java:69)
```
**com.hazelcast.quorum.map.TransactionalMapWriteQuorumTest**
```
com.hazelcast.quorum.map.TransactionalMapWriteQuorumTest Time elapsed: 0 sec <<< ERROR!
java.lang.ClassCastException: com.hazelcast.nio.tcp.TcpIpConnectionManager cannot be cast to com.hazelcast.nio.tcp.FirewallingMockConnectionManager
at com.hazelcast.quorum.PartitionedCluster.getConnectionManager(PartitionedCluster.java:187)
at com.hazelcast.quorum.PartitionedCluster.splitCluster(PartitionedCluster.java:147)
at com.hazelcast.quorum.PartitionedCluster.splitFiveMembersThreeAndTwo(PartitionedCluster.java:105)
at com.hazelcast.quorum.PartitionedCluster.partitionFiveMembersThreeAndTwo(PartitionedCluster.java:57)
at com.hazelcast.quorum.map.TransactionalMapWriteQuorumTest.initialize(TransactionalMapWriteQuorumTest.java:87)
```
**com.hazelcast.quorum.map.MapReadQuorumTest**
```
com.hazelcast.quorum.map.MapReadQuorumTest Time elapsed: 0 sec <<< ERROR!
java.lang.ClassCastException: com.hazelcast.nio.tcp.TcpIpConnectionManager cannot be cast to com.hazelcast.nio.tcp.FirewallingMockConnectionManager
at com.hazelcast.quorum.PartitionedCluster.getConnectionManager(PartitionedCluster.java:187)
at com.hazelcast.quorum.PartitionedCluster.splitCluster(PartitionedCluster.java:147)
at com.hazelcast.quorum.PartitionedCluster.splitFiveMembersThreeAndTwo(PartitionedCluster.java:105)
at com.hazelcast.quorum.PartitionedCluster.partitionFiveMembersThreeAndTwo(PartitionedCluster.java:57)
at com.hazelcast.quorum.map.MapReadQuorumTest.initialize(MapReadQuorumTest.java:66)
```
**com.hazelcast.quorum.map.TransactionalMapReadQuorumTest**
```
com.hazelcast.quorum.map.TransactionalMapReadQuorumTest Time elapsed: 0 sec <<< ERROR!
java.lang.ClassCastException: com.hazelcast.nio.tcp.TcpIpConnectionManager cannot be cast to com.hazelcast.nio.tcp.FirewallingMockConnectionManager
at com.hazelcast.quorum.PartitionedCluster.getConnectionManager(PartitionedCluster.java:187)
at com.hazelcast.quorum.PartitionedCluster.splitCluster(PartitionedCluster.java:147)
at com.hazelcast.quorum.PartitionedCluster.splitFiveMembersThreeAndTwo(PartitionedCluster.java:105)
at com.hazelcast.quorum.PartitionedCluster.partitionFiveMembersThreeAndTwo(PartitionedCluster.java:57)
at com.hazelcast.quorum.map.TransactionalMapReadQuorumTest.initialize(TransactionalMapReadQuorumTest.java:87)
```

**Comment by jerrinot** [comment]
@hasancelik: how was the test executed? it seems `mock network` was not used for some reason.

**Comment by hasancelik** [comment]
@jerrinot : I think @Danny-Hazelcast can answer this question.

**Comment by jerrinot** [comment]
the Quorum tests assume the mock network is always used -  they need a mock manager to introduce network partitioning. however it seems it was not the case this time. 

perhaps this property was set to `true`: https://github.com/jerrinot/hazelcast/blob/eef987b9920f3f7b4c506e433b0d067cab9ba93c/hazelcast/src/test/java/com/hazelcast/test/TestEnvironment.java#L21-L21 ?

**Comment by Danny-Hazelcast** [comment]
closing did not see error again after ulimit fix 
https://github.com/hazelcast/hazelcast/issues/7498
