### ISSUE TITLE
[hazelcast-hibernate3][3.6]NullPointerException on Value.isReplaceableBy

### ISSUE THREAD

**Issue by cmuramoto** [hazelcast/hazelcast#7517]
After upgrading from 3.5 to 3.6, I started to get exceptions when the system attempted to load some cacheable entities.

I am using Local mode and I noticed that the problem was arrond the following structure:

``` java
public interface RegionSymbols {

    String UNVERSIONED = "UNVERSIONED_REGION";

    String VERSIONED = "VERSIONED_REGION_INT_TYPE";
}


@Entity
@Table(name = "TB_VERSIONED_TREE")
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE, region = RegionSymbols.VERSIONED)
public class VersionedTree {

    @Id
    @GeneratedValue(strategy = GenerationType.TABLE, generator = "tree_gen")
    @TableGenerator(name = "tree_gen", pkColumnName = "NM_TABLE", pkColumnValue = "TB_VERSIONED_TREE", valueColumnName = "NR_SEQ", initialValue = 1, allocationSize = 10)
    @Column(name = "ID")
    Integer id;

    @Cache(usage = CacheConcurrencyStrategy.READ_WRITE, region = RegionSymbols.UNVERSIONED)
    @OneToMany(fetch = FetchType.EAGER, orphanRemoval = true)
    @JoinColumn(name = "CD_VTREE", nullable = false)
    @Cascade({ CascadeType.ALL, CascadeType.LOCK, CascadeType.DETACH })
    @Fetch(FetchMode.SUBSELECT)
    Set<UnversionedNode> nodes = new HashSet<>();

    @Column(name = "NM_LABEL")
    String label;

    @Version
    @Column(name = "NM_VERSION")
    Long version;

    //...accessor methods
}

@Entity
@Table(name = "TB_UNVERSIONED_NODE")
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE, region = RegionSymbols.UNVERSIONED)
public class UnversionedNode {

    @Id
    @Column(name = "ID")
    String label;

    //...accessor methods
}
```

The problem is that the com.hazelcast.hibernate.serialization.Value instances associated with the **UN**VERSIONED_REGION are somehow getting a non-null version field, which is always the same of newVersion.

It seems to me that the bug itself sort of lies on this piece hibernate code, [Excerpt from org.hibernate.engine.loading.CollectionLoadContext.addCollectionToCache(LoadingCollectionEntry, CollectionPersister) ]:

``` java
final Object version;
        if ( persister.isVersioned() ) {
            Object collectionOwner = getLoadContext().getPersistenceContext().getCollectionOwner( lce.getKey(), persister );
            if ( collectionOwner == null ) {
                // generally speaking this would be caused by the collection key being defined by a property-ref, thus
                // the collection key and the owner key would not match up.  In this case, try to use the key of the
                // owner instance associated with the collection itself, if one.  If the collection does already know
                // about its owner, that owner should be the same instance as associated with the PC, but we do the
                // resolution against the PC anyway just to be safe since the lookup should not be costly.
                if ( lce.getCollection() != null ) {
                    Object linkedOwner = lce.getCollection().getOwner();
                    if ( linkedOwner != null ) {
                        final Serializable ownerKey = persister.getOwnerEntityPersister().getIdentifier( linkedOwner, session );
                        collectionOwner = getLoadContext().getPersistenceContext().getCollectionOwner( ownerKey, persister );
                    }
                }
                if ( collectionOwner == null ) {
                    throw new HibernateException(
                            "Unable to resolve owner of loading collection [" +
                                    MessageHelper.collectionInfoString( persister, lce.getKey(), factory ) +
                                    "] for second level caching"
                    );
                }
            }
            version = getLoadContext().getPersistenceContext().getEntry( collectionOwner ).getVersion();
        }
        else {
            version = null;
        }
```

If the owning entity is versioned, the collection entries will get a version as well, even if the corresponding entities are unversioned.

I changed hazelcast-hibernate3 code to cope with this situation:

``` java
        @Override
    @SuppressWarnings({ "unchecked", "rawtypes" })
    public boolean isReplaceableBy(long txTimestamp, Object newVersion, Comparator versionComparator) {
        Object v = version;
        if (v == null) {
            return timestamp <= txTimestamp;
        } else {
            if (versionComparator == null) {
                if ((v instanceof Comparable) /* && newVersion instanceof Comparable */) {
                    return ((Comparable) v).compareTo(newVersion) < 0;
                }
            }
            return versionComparator.compare(v, newVersion) < 0;
        }
    }
```

The NPEs have gone away, but I'm still observing the system behavior after this change. 

I'll try downgrading from 3.6 to 3.5 to see why 3.5 code can handle this situation.

Edit: changed the entities according to the ones used in the [test case](https://github.com/cmuramoto/hz_research/tree/master/hz-2nd-level-cache)

**Comment by cmuramoto** [comment]
I have created a [test case](https://github.com/cmuramoto/hz_research/tree/master/hz-2nd-level-cache) that can easily reproduce the issue.

The problem happens when one tries to load VersionedTree instances a second time by using a criteria with LEFT_JOIN. 

```java
	@Override
	public List<VersionedTree> findWith(String label) {
		DetachedCriteria dc = DetachedCriteria.forClass(VersionedTree.class).add(Property.forName("label").eq(label));
		dc.createAlias("nodes", "nodes", CriteriaSpecification.LEFT_JOIN);

		return (List<VersionedTree>) ops.findByCriteria(dc);
	}
```

Even though it is **wrong** to use LEFT_JOIN instead of INNER_JOIN in this case, I felt like it is a useful simple example to illustrate the issue.

What is happening is:

1. When [saving](https://github.com/cmuramoto/hz_research/blob/master/hz-2nd-level-cache/domain/src/main/java/com/nc/hz/service/impl/TreeService.java#L38) the entity, the cache gets populated with an **ExpireMarker** because the program issues a com.hazelcast.hibernate.local.LocalRegionCache::tryLock(Object, Object), as a consequence of org.hibernate.action.CollectionAction::beforeExecutions().

2. When [querying](https://github.com/cmuramoto/hz_research/blob/master/hz-2nd-level-cache/domain/src/main/java/com/nc/hz/service/impl/TreeService.java#L23) the entity for the first time, the **ExpireMarker** gets succefully replaced with a **Value** holding the **CollectionCacheEntry** instance during org.hibernate.engine.loading.CollectionLoadContext::addCollectionToCache(LoadingCollectionEntry, CollectionPersister)

3. When attempting to query the entity for a second time, the **LocalRegionCache** holds a **Value** instead of an **ExpiryMark**, and Value does have a non-null version, however the **LocalRegionCache** doesn't provide a non-null comparator since it's meant to store unversioned entities.

I think that **LocalRegionCache**s that represent regions for unversioned entities (versionComparator==null) should not be allowed to create ExpiryMarker and Value instances with non-null version values.

**Comment by wenerme** [comment]
Same problem, 3.6.4, hibernate4


```
2016-09-05 13:46:59.446 ERROR 13153 --- [http-nio-7788-exec-3] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() fo
r servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lan
g.NullPointerException] with root cause

java.lang.NullPointerException: null
        at com.hazelcast.hibernate.serialization.Value.isReplaceableBy(Value.java:44)
        at com.hazelcast.hibernate.local.LocalRegionCache.put(LocalRegionCache.java:132)
        at com.hazelcast.hibernate.access.AbstractAccessDelegate.putFromLoad(AbstractAccessDelegate.java:76)
        at com.hazelcast.hibernate.access.AbstractAccessDelegate.putFromLoad(AbstractAccessDelegate.java:88)
        at com.hazelcast.hibernate.region.CollectionRegionAccessStrategyAdapter.putFromLoad(CollectionRegionAccessStrategyAdap
ter.java:69)
        at org.hibernate.engine.loading.internal.CollectionLoadContext.addCollectionToCache(CollectionLoadContext.java:369)
        at org.hibernate.engine.loading.internal.CollectionLoadContext.endLoadingCollection(CollectionLoadContext.java:278)
        at org.hibernate.engine.loading.internal.CollectionLoadContext.endLoadingCollections(CollectionLoadContext.java:238)
        at org.hibernate.engine.loading.internal.CollectionLoadContext.endLoadingCollections(CollectionLoadContext.java:211)
        at org.hibernate.loader.plan.exec.process.internal.CollectionReferenceInitializerImpl.endLoading(CollectionReferenceIn
itializerImpl.java:168)
        at org.hibernate.loader.plan.exec.process.internal.AbstractRowReader.finishLoadingCollections(AbstractRowReader.java:2
55)
        at org.hibernate.loader.plan.exec.process.internal.AbstractRowReader.finishUp(AbstractRowReader.java:218)
        at org.hibernate.loader.plan.exec.process.internal.ResultSetProcessorImpl.extractResults(ResultSetProcessorImpl.java:1
40)
        at org.hibernate.loader.plan.exec.internal.AbstractLoadPlanBasedLoader.executeLoad(AbstractLoadPlanBasedLoader.java:13
8)
        at org.hibernate.loader.plan.exec.internal.AbstractLoadPlanBasedLoader.executeLoad(AbstractLoadPlanBasedLoader.java:10
2)
        at org.hibernate.loader.collection.plan.AbstractLoadPlanBasedCollectionInitializer.initialize(AbstractLoadPlanBasedCol
lectionInitializer.java:100)
        at org.hibernate.persister.collection.AbstractCollectionPersister.initialize(AbstractCollectionPersister.java:693)
        at org.hibernate.event.internal.DefaultInitializeCollectionEventListener.onInitializeCollection(DefaultInitializeColle
ctionEventListener.java:92)
        at org.hibernate.internal.SessionImpl.initializeCollection(SessionImpl.java:1933)
        at org.hibernate.collection.internal.AbstractPersistentCollection$4.doWork(AbstractPersistentCollection.java:559)
        at org.hibernate.collection.internal.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentColle
ction.java:261)
        at org.hibernate.collection.internal.AbstractPersistentCollection.initialize(AbstractPersistentCollection.java:555)
        at org.hibernate.collection.internal.AbstractPersistentCollection.read(AbstractPersistentCollection.java:143)
        at org.hibernate.collection.internal.PersistentBag.iterator(PersistentBag.java:294)
```

**Comment by wenerme** [comment]
This should be closed due to https://github.com/hazelcast/hazelcast-hibernate/issues/11

**Comment by Michael-S-Smith** [comment]
I understand you see these issues as the same thing - but can we get an update on [https://github.com/hazelcast/hazelcast-hibernate/issues/11] ? I have seen no feedback on it since 10/25 - what is the status? Thanks.

**Comment by mdogan** [comment]
This issue was moved to hazelcast/hazelcast-hibernate#34
