### ISSUE TITLE
CacheClientListenerTest.testSyncListener_shouldNotHang_whenHazelcastInstanceShutdown

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#7527]
```
java.lang.AssertionError: Cache operations should not hang when sync listener is present!, failed to complete within 120 seconds , count left: 1
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:761)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:747)
	at com.hazelcast.cache.CacheListenerTest.testSyncListener_shouldNotHang_AfterAction(CacheListenerTest.java:331)
	at com.hazelcast.cache.CacheListenerTest.testSyncListener_shouldNotHang_whenHazelcastInstanceShutdown(CacheListenerTest.java:263)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:622)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:88)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:82)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.lang.Thread.run(Thread.java:701)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-ZuluJDK6/com.hazelcast$hazelcast-client/117/testReport/junit/com.hazelcast.client.cache/CacheClientListenerTest/testSyncListener_shouldNotHang_whenHazelcastInstanceShutdown/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x/com.hazelcast$hazelcast-client/4574/testReport/junit/com.hazelcast.client.cache/CacheClientListenerTest/testSyncListener_shouldNotHang_whenHazelcastInstanceShutdown/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: Cache operations should not hang when sync listener is present!, failed to complete within 120 seconds , count left: 2
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:761)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:747)
	at com.hazelcast.cache.CacheListenerTest.testSyncListener_shouldNotHang_AfterAction(CacheListenerTest.java:331)
	at com.hazelcast.cache.CacheListenerTest.testSyncListener_shouldNotHang_whenHazelcastInstanceShutdown(CacheListenerTest.java:263)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:88)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:82)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-OracleJDK8/com.hazelcast$hazelcast-client/727/testReport/junit/com.hazelcast.client.cache/CacheClientListenerTest/testSyncListener_shouldNotHang_whenHazelcastInstanceShutdown/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.maintenance-IbmJDK1.8/com.hazelcast$hazelcast-client/51/testReport/junit/com.hazelcast.client.cache/CacheClientListenerTest/testSyncListener_shouldNotHang_whenHazelcastInstanceShutdown/

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.maintenance-OracleJDK8/com.hazelcast$hazelcast-client/346/testReport/junit/com.hazelcast.client.cache/CacheClientListenerTest/testSyncListener_shouldNotHang_whenHazelcastInstanceShutdown/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: Cache operations should not hang when sync listener is present!, failed to complete within 120 seconds , count left: 4
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:761)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:747)
	at com.hazelcast.cache.CacheListenerTest.testSyncListener_shouldNotHang_AfterAction(CacheListenerTest.java:331)
	at com.hazelcast.cache.CacheListenerTest.testSyncListener_shouldNotHang_whenHazelcastInstanceShutdown(CacheListenerTest.java:263)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:88)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:82)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.lang.Thread.run(Thread.java:745)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-ZuluJDK7/com.hazelcast$hazelcast-client/134/testReport/junit/com.hazelcast.client.cache/CacheClientListenerTest/testSyncListener_shouldNotHang_whenHazelcastInstanceShutdown/

**Comment by hasancelik** [comment]
suppressed by https://github.com/hazelcast/hazelcast/commit/73decc86db470cc70160b8b4dff667588d88e82f

**Comment by sancar** [comment]
fixed via https://github.com/hazelcast/hazelcast/pull/7691

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: Cache operations should not hang when sync listener is present!, failed to complete within 120 seconds , count left: 4
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:767)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:753)
	at com.hazelcast.cache.CacheListenerTest.testSyncListener_shouldNotHang_AfterAction(CacheListenerTest.java:330)
	at com.hazelcast.cache.CacheListenerTest.testSyncListener_shouldNotHang_whenHazelcastInstanceShutdown(CacheListenerTest.java:262)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:88)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:82)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-ZuluJDK8/com.hazelcast$hazelcast-client/151/testReport/junit/com.hazelcast.client.cache/CacheClientListenerTest/testSyncListener_shouldNotHang_whenHazelcastInstanceShutdown/
