### ISSUE TITLE
ClientRegressionWithMockNetworkTest.testClusterShutdown_thenCheckOperationsNotHanging

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#7582]
```
java.lang.AssertionError: Put operations should not hang., failed to complete within 120 seconds , count left: 15
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:761)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:747)
	at com.hazelcast.client.ClientRegressionWithMockNetworkTest.testClusterShutdown_thenCheckOperationsNotHanging(ClientRegressionWithMockNetworkTest.java:861)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x/com.hazelcast$hazelcast-client/4596/testReport/junit/com.hazelcast.client/ClientRegressionWithMockNetworkTest/testClusterShutdown_thenCheckOperationsNotHanging/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: Put operations should not hang., failed to complete within 120 seconds , count left: 1
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:761)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:747)
	at com.hazelcast.client.ClientRegressionWithMockNetworkTest.testClusterShutdown_thenCheckOperationsNotHanging(ClientRegressionWithMockNetworkTest.java:794)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.maintenance-ZuluJDK8/com.hazelcast$hazelcast-client/45/testReport/junit/com.hazelcast.client/ClientRegressionWithMockNetworkTest/testClusterShutdown_thenCheckOperationsNotHanging/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-ZuluJDK8/com.hazelcast$hazelcast-client/127/testReport/junit/com.hazelcast.client/ClientRegressionWithMockNetworkTest/testClusterShutdown_thenCheckOperationsNotHanging/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-ZuluJDK8/com.hazelcast$hazelcast-client/131/testReport/junit/com.hazelcast.client/ClientRegressionWithMockNetworkTest/testClusterShutdown_thenCheckOperationsNotHanging/

**Comment by hasancelik** [comment]
suppressed by https://github.com/hazelcast/hazelcast/commit/73decc86db470cc70160b8b4dff667588d88e82f
