### ISSUE TITLE
While updating the hazelcast maps in the clustered environment, we are getting exception

### ISSUE THREAD

**Issue by rameshhzl1982** [hazelcast/hazelcast#7584]
We will constantly update the Hazelcast map which is setup in the Hazelcast server as our master details repository.

Sometime, when we try to update the map in the server, we are getting an error the map is not updated.

Will log the error details:
User gets Hazelcast update failed error while updating master. After multiple attempts, master update works fine. Below is the log for the same

```
[2016-02-19 15:17:23,382] [SimpleAsyncTaskExecutor-39717] [ERROR] [master.MasterReplicationServiceImpl] [com.wwglobal.wits.service.master.MasterReplicationServiceImpl.rollbackTransaction(MasterReplicationServiceImpl.java:215)] [Unable to rollback hazelcast transaction]
[2016-02-19 15:17:23,383] [SimpleAsyncTaskExecutor-39717] [ERROR] [master.MasterReplicationServiceImpl] [com.wwglobal.wits.service.master.MasterReplicationServiceImpl.loadHazelCastAsync(MasterReplicationServiceImpl.java:198)] [After Rollback Transaction]
com.hazelcast.spi.exception.TargetNotMemberException: Address : Address[uswclux219p]:5701
    at com.hazelcast.client.spi.impl.ClientInvocationServiceImpl.sendInternal(ClientInvocationServiceImpl.java:159)
    at com.hazelcast.client.spi.impl.ClientInvocationServiceImpl.doSend(ClientInvocationServiceImpl.java:144)
    at com.hazelcast.client.spi.impl.ClientInvocationServiceImpl.send(ClientInvocationServiceImpl.java:112)
    at com.hazelcast.client.txn.TransactionProxy.invoke(TransactionProxy.java:201)
    at com.hazelcast.client.txn.TransactionProxy.begin(TransactionProxy.java:99)
    at com.hazelcast.client.txn.TransactionContextProxy.beginTransaction(TransactionContextProxy.java:77)
    at com.wwglobal.wits.service.master.MasterReplicationServiceImpl.loadHazelCastAsync(MasterReplicationServiceImpl.java:169)
    at com.wwglobal.wits.service.master.MasterReplicationServiceImpl$$FastClassBySpringCGLIB$$84725bf.invoke(<generated>)
    at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
    at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:717)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
    at org.springframework.aop.interceptor.AsyncExecutionInterceptor$1.call(AsyncExecutionInterceptor.java:110)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.lang.Thread.run(Thread.java:682)
    at ------ End remote and begin local stack-trace ------.(Unknown Source)
    at com.hazelcast.client.spi.impl.ClientCallFuture.resolveResponse(ClientCallFuture.java:202)
    at com.hazelcast.client.spi.impl.ClientCallFuture.get(ClientCallFuture.java:143)
    at com.hazelcast.client.spi.impl.ClientCallFuture.get(ClientCallFuture.java:119)
    at com.hazelcast.client.txn.TransactionProxy.invoke(TransactionProxy.java:202)
    at com.hazelcast.client.txn.TransactionProxy.begin(TransactionProxy.java:99)
    at com.hazelcast.client.txn.TransactionContextProxy.beginTransaction(TransactionContextProxy.java:77)
    at com.wwglobal.wits.service.master.MasterReplicationServiceImpl.loadHazelCastAsync(MasterReplicationServiceImpl.java:169)
    at com.wwglobal.wits.service.master.MasterReplicationServiceImpl$$FastClassBySpringCGLIB$$84725bf.invoke(<generated>)
    at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
    at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:717)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
    at org.springframework.aop.interceptor.AsyncExecutionInterceptor$1.call(AsyncExecutionInterceptor.java:110)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.lang.Thread.run(Thread.java:682)
```

**Comment by sancar** [comment]
This issue looks similar to this one https://github.com/hazelcast/hazelcast/issues/8545
In case of exception from `beginTransaction`, new transaction context needs to be created. See the example link above.
