### ISSUE TITLE
WriteBehindFlushTest.testWriteBehindQueues_flushed_uponEviction

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#7660]
```
java.lang.AssertionError: expected:<0> but was:<3>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.map.impl.mapstore.writebehind.WriteBehindFlushTest$3.run(WriteBehindFlushTest.java:187)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:851)
	at com.hazelcast.map.impl.mapstore.writebehind.WriteBehindFlushTest.assertWriteBehindQueuesEmpty(WriteBehindFlushTest.java:183)
	at com.hazelcast.map.impl.mapstore.writebehind.WriteBehindFlushTest.testWriteBehindQueues_flushed_uponEviction(WriteBehindFlushTest.java:166)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-OracleJDK8/com.hazelcast$hazelcast/734/testReport/junit/com.hazelcast.map.impl.mapstore.writebehind/WriteBehindFlushTest/testWriteBehindQueues_flushed_uponEviction/

**Comment by ahmetmircik** [comment]
Not failed recently after this PR https://github.com/hazelcast/hazelcast/pull/7655 , closing this test failure.
