### ISSUE TITLE
Application server is Unresponsive due to not able to fetch objects from IMap.get(key)

### ISSUE THREAD

**Issue by veerumallavarapu** [hazelcast/hazelcast#7689]
Hi All,

we have clustered environment and one of the application server is unresponsive and all other servers are working without any issues.  From thread dumps it is found that while fetching the objects from Imap. it is stuck and it has effect on subsequent request  and all requests pertaining to that app server are in waiting state. As a result of that the server is unresponsive. To resolve this issue , App Server got restarted. However , it is required find out the root cause. Here I am pasting the issue from thread dump.  There are around more than 100 threads are in waiting state.

At present ,  we are using hazelcast 3.2.4 version in production environment.  I am not sure , how to re-produce this in local environment. And it is not happening frequently.  Thanks in advance.

```
"ajp-apr-0.0.0.0-8009-exec-170" daemon prio=6 tid=0x0000000048370800 nid=0x1054 in Object.wait() [0x0000000052aad000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
    at java.lang.Object.wait(Native Method)
    at com.hazelcast.spi.impl.BasicInvocation$InvocationFuture.waitForResponse(BasicInvocation.java:723)
    - locked <0x0000000735eb1948> (a com.hazelcast.spi.impl.BasicInvocation$InvocationFuture)
    at com.hazelcast.spi.impl.BasicInvocation$InvocationFuture.get(BasicInvocation.java:697)
    at com.hazelcast.spi.impl.BasicInvocation$InvocationFuture.get(BasicInvocation.java:676)
    at com.hazelcast.map.proxy.MapProxySupport.invokeOperation(MapProxySupport.java:256)
    at com.hazelcast.map.proxy.MapProxySupport.getInternal(MapProxySupport.java:159)
    at com.hazelcast.map.proxy.MapProxyImpl.get(MapProxyImpl.java:53)
    at com.qumu.viewer.services.favorite.ClusteredUserFavoriteStore._findFavorite(ClusteredUserFavoriteStore.java:188)
    at com.qumu.viewer.services.favorite.ClusteredUserFavoriteStore.isFavorited(ClusteredUserFavoriteStore.java:72)
    at com.qumu.viewer.services.favorite.ClusteredUserFavoriteStore$$FastClassBySpringCGLIB$$b41d6daa.invoke(<generated>)
    at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
    at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:629)
    at com.qumu.viewer.services.favorite.ClusteredUserFavoriteStore$$EnhancerBySpringCGLIB$$25b32836.isFavorited(<generated>)
    at com.qumu.viewer.services.program.ProgramDetailsServiceImpl.populateFavoriteFlag(ProgramDetailsServiceImpl.java:915)
    at com.qumu.viewer.services.program.ProgramDetailsServiceImpl.fetchProgramDetails(ProgramDetailsServiceImpl.java:287)
    at com.qumu.viewer.services.program.ProgramDetailsServiceImpl$$FastClassBySpringCGLIB$$a19bdda4.invoke(<generated>)
    at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
    at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:700)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
    at com.mpi.framework.hibernate.MPIHibernateInterceptor.invoke(MPIHibernateInterceptor.java:57)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at com.mpi.framework.hibernate.MPIHibernateInterceptor.invoke(MPIHibernateInterceptor.java:57)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:633)
    at com.qumu.viewer.services.program.ProgramDetailsServiceImpl$$EnhancerBySpringCGLIB$$ff46df3f.fetchProgramDetails(<generated>)
    at com.qumu.vp.rest.program.ProgramResource.fetchProgram(ProgramResource.java:276)
    at com.qumu.vp.rest.program.ProgramResource$$FastClassBySpringCGLIB$$6e7766ed.invoke(<generated>)
    at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
    at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:700)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
    at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:96)
    at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:260)
    at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:633)
    at com.qumu.vp.rest.program.ProgramResource$$EnhancerBySpringCGLIB$$12fbf419.fetchProgram(<generated>)
    at com.mpi.mp.webutil.dataset.gen.DScom_qumu_vp_rest_program_ProgramResource_fetchProgram.invokeService(DScom_qumu_vp_rest_program_ProgramResource_fetchProgram.java)
    at com.mpi.mp.webutil.dataset.DatasetFactoryBean$AbstractReflectiveDataset$Loader.loadDataset(DatasetFactoryBean.java:431)
    at com.mpi.mp.webutil.dataset.DatasetInstance.getData(DatasetInstance.java:73)
    at com.qumu.vp.jsonmodel.JSONModelDirectiveFactory$JSONModelNode.render(JSONModelDirectiveFactory.java:135)
    at com.mpi.template.ste.Template.render(Template.java:18)
    at com.qumu.vp.jsonmodel.AbstractJSONModelController$JSONModelView.render(AbstractJSONModelController.java:189)
    at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1201)
    at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:986)
    at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:933)
    at com.mpi.mp.webutil.spring.MPIDispatcherServlet.dispatchAfterFiltering(MPIDispatcherServlet.java:78)
    at com.mpi.mp.webutil.spring.MPIDispatcherServlet.doDispatch(MPIDispatcherServlet.java:61)
    at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:851)
    at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:953)
    at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:844)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:620)
```

**Comment by pveentjer** [comment]
Many issues have been fixed that could cause this problem. Currently HZ is at 3.6.1, so I would certainly upgrade to that version.

**Comment by veerumallavarapu** [comment]
so you are suggesting to use latest version of Hazelcast to fix this issue? And I am not sure how to convince them as I am not able to re-produce it.

**Comment by rkawecki** [comment]
Hello, 

Our customer had their 2nd outage this month which was at least in part due to Hazelcast. It's critical that we determine if the issue my colleague described has been address in alter version of Hazelcast, therefore please confirm it what version this has been address and please share the release notes of that version referencing the fix.

Your attention to this matter is much appreciated!

Regards,
Ryan Kawecki
Service Delivery Manager for Qumu

**Comment by rkawecki** [comment]
Hello, 

I left a comment two weeks ago and have not heard back from your support. Please respond.

Since then we have reviewed the latest Release notes which don't mention anything regarding this issue being fixed. Again, please confirm if this issue has been addressed and in which patch and share with us.

http://docs.hazelcast.org/docs/release-notes/


Regards,
Ryan Kawecki
Qumu Service Delivery Manager

**Comment by mickgiles** [comment]
We are seeing essentially the same issue on 3.6.2. Looking at the code, InvocationFuture.get() blocks forever. In our case we are simply looking if the map contains a key and .the get() call is blocking forever resulting in thousands of threads spawning, as we call this in a CompletableFuture, eventually causing the node to leave the cluster and essentially melting down completely. I suspect that there may be an underlying problem in the core threading system that is being overlooked here. 
For us, this primarily happens when a node joins or leaves and partition operations are in progress.

```
Thread 804: (state = BLOCKED)
 - java.lang.Object.wait(long) @bci=0 (Compiled frame; information may be imprecise)
 - com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.pollResponse(long) @bci=41, line=300 (Compiled frame)
 - com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.waitForResponse(long, java.util.concurrent.TimeUnit) @bci=85, line=245 (Compiled frame)
 - com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.get(long, java.util.concurrent.TimeUnit) @bci=3, line=222 (Compiled frame)
 - com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.get() @bci=7, line=202 (Compiled frame)
 - com.hazelcast.map.impl.proxy.MapProxySupport.containsKeyInternal(com.hazelcast.nio.serialization.Data) @bci=58, line=494 (Compiled frame)
 - com.hazelcast.map.impl.proxy.MapProxyImpl.containsKey(java.lang.Object) @bci=19, line=215 (Compiled frame)
 - utils.caching.MapCacheSplitIndexImpl.indexMap(java.lang.Object) @bci=7, line=100 (Compiled frame)
 - utils.caching.MapCacheSplitIndexImpl.addEntry(java.lang.Object, java.lang.Object, java.lang.Object) @bci=7, line=262 (Compiled frame)
 - utils.caching.MapCacheSplitIndexImpl.onAddedEntryEvent(com.hazelcast.core.EntryEvent) @bci=23, line=312 (Compiled frame)
 - utils.caching.MapCacheSplitIndexImpl$$Lambda$90.accept(java.lang.Object) @bci=8 (Compiled frame)
 - utils.caching.AsynchEntryListener.lambda$entryAdded$1(com.hazelcast.core.EntryEvent) @bci=5, line=95 (Compiled frame)
 - utils.caching.AsynchEntryListener$$Lambda$192.run() @bci=8 (Compiled frame)
 - java.util.concurrent.CompletableFuture$AsyncRun.run() @bci=36, line=1626 (Compiled frame)
 - java.lang.Thread.run() @bci=11, line=745 (Compiled frame)
```

**Comment by mdogan** [comment]
`InvocationFuture.get()` has a built-in timeout when remote node doesn't respond at all. It doesn't wait forever. That timeout is defined by system property `hazelcast.operation.call.timeout.millis`. 
When remote node doesn't respond in time, invocation fails with `OperationTimeoutException`.

Those timeouts are generally because of network problem between caller and remote or system pauses due to high load (GC pauses, OS freezes, IO latency etc). 

You can decrease `hazelcast.operation.call.timeout.millis` to a lower value and enable diagnostics reports to see detailed metrics of the system.

```
-Dhazelcast.diagnostics.enabled=true
-Dhazelcast.diagnostics.metric.level=info
-Dhazelcast.diagnostics.invocation.sample.period.seconds=30
-Dhazelcast.diagnostics.pending.invocations.period.seconds=30
-Dhazelcast.diagnostics.slowoperations.period.seconds=30 
```
http://docs.hazelcast.org/docs/latest/manual/html-single/index.html#diagnostics

**Comment by veerumallavarapu** [comment]
Hi mdogan

I am here attaching the diagnostics files for review.   Please do through it and let me know if you find any suspicious workflow.

Regards
Veeru

**Comment by veerumallavarapu** [comment]
Diagnostics files are available at below location as I am not able to upload here. Making it available from google drive.

https://drive.google.com/file/d/1Im1MWokLP9HxHnM34ZHUwTLMq4OftHPB/view?usp=sharing

https://drive.google.com/file/d/1ygC1-09p69TD07IjkIdpUA_BfpsYpfJk/view?usp=sharing
