### ISSUE TITLE
ClientTransactionalMapQuorumTest.*. [Executing: TransactionOptions{timeoutMillis=120000, durability=1, txType=TWO_PHASE}]

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#7693]
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:156)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:811)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:969)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1281)
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:207)
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl$BlockingCallback.get(ClientConnectionManagerImpl.java:259)
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.getOrConnect(ClientConnectionManagerImpl.java:234)
	at com.hazelcast.client.spi.impl.ClientTransactionManagerServiceImpl.connect(ClientTransactionManagerServiceImpl.java:107)
	at com.hazelcast.client.proxy.txn.TransactionContextProxy.<init>(TransactionContextProxy.java:58)
	at com.hazelcast.client.spi.impl.ClientTransactionManagerServiceImpl.newTransactionContext(ClientTransactionManagerServiceImpl.java:57)
	at com.hazelcast.client.impl.HazelcastClientInstanceImpl.newTransactionContext(HazelcastClientInstanceImpl.java:427)
	at com.hazelcast.client.impl.HazelcastClientProxy.newTransactionContext(HazelcastClientProxy.java:169)
	at com.hazelcast.client.quorum.ClientTransactionalMapQuorumTest.testTxReplaceThrowsExceptionWhenQuorumSizeNotMet(ClientTransactionalMapQuorumTest.java:207)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x/com.hazelcast$hazelcast-client/4687/

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.maintenance/1228/

These failures occur at Jenkins machines and my local.Our pr builder is working properly. I think problematic commit is: https://github.com/hazelcast/hazelcast/pull/7673
Here is the its pr builder:
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/1797/

**Comment by hasancelik** [comment]
suppressed by https://github.com/hazelcast/hazelcast/commit/65738eee1e74d1637bb7755dff2c079d73eedc2d & https://github.com/hazelcast/hazelcast/commit/6482f201b079e5052d6c0c06440ce3b8735ad94f

**Comment by hasancelik** [comment]
```
java.lang.Exception: Unexpected exception, expected<com.hazelcast.transaction.TransactionException> but was<com.hazelcast.core.OperationTimeoutException>
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.newOperationTimeoutException(InvocationFuture.java:150)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:96)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrow(InvocationFuture.java:74)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:158)
	at com.hazelcast.map.impl.query.MapQueryEngineImpl.addResultsOfPredicate(MapQueryEngineImpl.java:528)
	at com.hazelcast.map.impl.query.MapQueryEngineImpl.invokeQueryAllPartitions(MapQueryEngineImpl.java:434)
	at com.hazelcast.map.impl.tx.TransactionalMapProxy.keySet(TransactionalMapProxy.java:306)
	at com.hazelcast.map.impl.tx.TransactionalMapProxy.keySet(TransactionalMapProxy.java:291)
	at com.hazelcast.client.impl.protocol.task.transactionalmap.TransactionalMapKeySetMessageTask.innerCall(TransactionalMapKeySetMessageTask.java:47)
	at com.hazelcast.client.impl.protocol.task.AbstractTransactionalMessageTask.call(AbstractTransactionalMessageTask.java:34)
	at com.hazelcast.client.impl.protocol.task.AbstractCallableMessageTask.processMessage(AbstractCallableMessageTask.java:35)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:119)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:99)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrow(ClientInvocationFuture.java:74)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrow(ClientInvocationFuture.java:30)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:158)
	at com.hazelcast.client.proxy.txn.ClientTxnProxy.invoke(ClientTxnProxy.java:49)
	at com.hazelcast.client.proxy.txn.ClientTxnMapProxy.keySet(ClientTxnMapProxy.java:173)
	at com.hazelcast.client.quorum.ClientTransactionalMapQuorumTest.testTxKeySetThrowsExceptionWhenQuorumSizeNotMet(ClientTransactionalMapQuorumTest.java:256)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-sonar/1049/

**Comment by Donnerbart** [comment]
I had a timeout on a local code coverage run in
`ClientTransactionalMapQuorumTest.testTxKeySetWithPredicateThrowsExceptionWhenQuorumSizeNotMet()`:
```
Executing: TransactionOptions{timeoutMillis=120000, durability=1, txType=TWO_PHASE}
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds

	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:304)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:156)
	at com.hazelcast.client.proxy.txn.ClientTxnProxy.invoke(ClientTxnProxy.java:49)
	at com.hazelcast.client.proxy.txn.ClientTxnMapProxy.keySet(ClientTxnMapProxy.java:219)
	at com.hazelcast.client.quorum.ClientTransactionalMapQuorumTest.testTxKeySetWithPredicateThrowsExceptionWhenQuorumSizeNotMet(ClientTransactionalMapQuorumTest.java:265)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:88)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:82)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by cangencer** [comment]
I haven't been able to reproduce this issue, after running it for many hours both on EC2 and my local machine. Some test improvements have been made at #8557, but otherwise I'm suspecting the issue was not directly related to this test. The recent failures are also different from the original failures. If again this test fails, it would be good to open a new issue instead.
