### ISSUE TITLE
[ZING-JVM] QueueAdvancedTest Failures (only JDK8)

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#7707]
```
20:46:54 Tests run: 18, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 152.397 sec <<< FAILURE! - in com.hazelcast.collection.impl.queue.QueueAdvancedTest
20:46:54 testShutdown(com.hazelcast.collection.impl.queue.QueueAdvancedTest)  Time elapsed: 6.238 sec  <<< ERROR!
20:46:54 java.lang.NoSuchMethodError: com.hazelcast.core.IQueue.offer(Ljava/lang/String;JLjava/util/concurrent/TimeUnit;)Z
20:46:54    at com.hazelcast.collection.impl.queue.QueueAdvancedTest.testShutdown(QueueAdvancedTest.java:156)
20:46:54 
20:46:54 testOffer(com.hazelcast.collection.impl.queue.QueueAdvancedTest)  Time elapsed: 6.565 sec  <<< ERROR!
20:46:54 java.lang.NoSuchMethodError: com.hazelcast.core.IQueue.offer(Ljava/lang/String;JLjava/util/concurrent/TimeUnit;)Z
20:46:54    at com.hazelcast.collection.impl.queue.QueueAdvancedTest.testOffer(QueueAdvancedTest.java:67)
20:46:54 
20:46:54 testOfferLong(com.hazelcast.collection.impl.queue.QueueAdvancedTest)  Time elapsed: 6.503 sec  <<< ERROR!
20:46:54 java.lang.NoSuchMethodError: com.hazelcast.core.IQueue.offer(Ljava/lang/String;JLjava/util/concurrent/TimeUnit;)Z
20:46:54    at com.hazelcast.collection.impl.queue.QueueAdvancedTest.testOfferLong(QueueAdvancedTest.java:321)
```

https://hazelcast-l337.ci.cloudbees.com/view/Zing/job/Hazelcast-3.x-ZingJDK8/9/consoleFull

**Comment by jerrinot** [comment]
@hasancelik: Did you report this to Azul? There was a similar issue in OpenJDK in the past.

**Comment by hasancelik** [comment]
fixed via upgrading version of zing jdk.
