### ISSUE TITLE
Hazelcast lifeCycle exception

### ISSUE THREAD

**Issue by toktarev** [hazelcast/hazelcast#7749]
JET got an exception:

https://hazelcast-l337.ci.cloudbees.com/job/Jet/com.hazelcast$hazelcast-jet-core/14/testReport/junit/com.hazelcast.jet/ProcessingStrategyTest/com_hazelcast_jet_ProcessingStrategyTest/

```
java.lang.RuntimeException: java.net.SocketException: Invalid argument
    at sun.nio.ch.Net.bind0(Native Method)
    at sun.nio.ch.Net.bind(Net.java:433)
    at sun.nio.ch.Net.bind(Net.java:425)
    at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
    at java.nio.channels.ServerSocketChannel.bind(ServerSocketChannel.java:157)
    at com.hazelcast.jet.impl.application.JetApplicationManagerImpl.bindSocketChannel(JetApplicationManagerImpl.java:155)
    at com.hazelcast.jet.impl.application.JetApplicationManagerImpl.<init>(JetApplicationManagerImpl.java:78)
    at com.hazelcast.jet.impl.hazelcast.JetServiceImpl.<init>(JetServiceImpl.java:46)
```

As result we got HZ exception:

```
13:58:36,748 ERROR || - [ServiceManagerImpl] main - [127.0.0.1]:5001 [dev] [3.7-SNAPSHOT] Error while shutting down service[com.hazelcast.replicatedmap.impl.ReplicatedMapService@45efc20d]: null
java.lang.NullPointerException
   at com.hazelcast.replicatedmap.impl.ReplicatedMapService.shutdown(ReplicatedMapService.java:176)
   at com.hazelcast.spi.impl.servicemanager.impl.ServiceManagerImpl.shutdownService(ServiceManagerImpl.java:304)
   at com.hazelcast.spi.impl.servicemanager.impl.ServiceManagerImpl.shutdown(ServiceManagerImpl.java:295)
   at com.hazelcast.spi.impl.NodeEngineImpl.shutdown(NodeEngineImpl.java:380)
   at com.hazelcast.instance.Node.shutdownServices(Node.java:433)
   at com.hazelcast.instance.Node.shutdown(Node.java:407)
   at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:141)
   at com.hazelcast.instance.DefaultHazelcastInstanceFactory.newHazelcastInstance(DefaultHazelcastInstanceFactory.java:38)
   at com.hazelcast.instance.HazelcastInstanceManager.constructHazelcastInstance(HazelcastInstanceManager.java:226)
   at com.hazelcast.instance.HazelcastInstanceManager.newHazelcastInstance(HazelcastInstanceManager.java:184)
   at com.hazelcast.test.TestHazelcastInstanceFactory.newHazelcastInstance(TestHazelcastInstanceFactory.java:112)
```

**Comment by jerrinot** [comment]
There is a lifecycle issue: Start had been interrupted due the `SocketException` -> `init()` was not even called. However the `shutdown()` method WAS called -> NPE. 

"If you do not call `init()` then you should not call `shutdown()` either."
