### ISSUE TITLE
ClientMapStoreTest.mapStore_OperationQueue_AtMaxCapacity_Test

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#7811]
```
java.lang.AssertionError: Expected exception: com.hazelcast.map.ReachedMaxSizeException
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:32)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:88)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:82)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-sonar/com.hazelcast$hazelcast-client/996/testReport/junit/com.hazelcast.client.map/ClientMapStoreTest/mapStore_OperationQueue_AtMaxCapacity_Test/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: Expected exception: com.hazelcast.map.ReachedMaxSizeException
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:32)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:88)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:82)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-sonar/com.hazelcast$hazelcast-client/999/testReport/junit/com.hazelcast.client.map/ClientMapStoreTest/mapStore_OperationQueue_AtMaxCapacity_Test/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: Expected exception: com.hazelcast.map.ReachedMaxSizeException
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:32)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:88)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:82)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-sonar/com.hazelcast$hazelcast-client/1020/testReport/junit/com.hazelcast.client.map/ClientMapStoreTest/mapStore_OperationQueue_AtMaxCapacity_Test/

**Comment by ahmetmircik** [comment]
not failed recently.
