### ISSUE TITLE
CacheFromDifferentNodesTest.testCompletionTestByPuttingAndRemovingFromDifferentNodes

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#7812]
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at sun.misc.Unsafe.unpark(Native Method)
	at java.util.concurrent.locks.LockSupport.unpark(LockSupport.java:141)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.unparkSuccessor(AbstractQueuedSynchronizer.java:662)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.release(AbstractQueuedSynchronizer.java:1264)
	at java.util.concurrent.locks.ReentrantLock.unlock(ReentrantLock.java:457)
	at java.util.concurrent.LinkedBlockingQueue.signalNotEmpty(LinkedBlockingQueue.java:176)
	at java.util.concurrent.LinkedBlockingQueue.offer(LinkedBlockingQueue.java:430)
	at java.util.AbstractQueue.add(AbstractQueue.java:95)
	at com.hazelcast.spi.impl.operationexecutor.classic.DefaultScheduleQueue.add(DefaultScheduleQueue.java:49)
	at com.hazelcast.spi.impl.operationexecutor.classic.ClassicOperationExecutor.execute(ClassicOperationExecutor.java:429)
	at com.hazelcast.spi.impl.operationexecutor.classic.ClassicOperationExecutor.execute(ClassicOperationExecutor.java:373)
	at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.handle(OperationServiceImpl.java:271)
	at com.hazelcast.spi.impl.packetdispatcher.impl.PacketDispatcherImpl.dispatch(PacketDispatcherImpl.java:57)
	at com.hazelcast.test.mocknetwork.MockConnection.write(MockConnection.java:66)
	at com.hazelcast.test.mocknetwork.MockConnectionManager.transmit(MockConnectionManager.java:194)
	at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.send(OperationServiceImpl.java:410)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeRemote(Invocation.java:265)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:241)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invokeInternal(Invocation.java:210)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:180)
	at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.invokeOnTarget(OperationServiceImpl.java:325)
	at com.hazelcast.cache.impl.CacheProxy.updateCacheListenerConfigOnOtherNodes(CacheProxy.java:335)
	at com.hazelcast.cache.impl.CacheProxy.registerCacheEntryListener(CacheProxy.java:305)
	at com.hazelcast.cache.impl.AbstractHazelcastCacheManager.registerListeners(AbstractHazelcastCacheManager.java:412)
	at com.hazelcast.cache.impl.AbstractHazelcastCacheManager.getCacheUnchecked(AbstractHazelcastCacheManager.java:252)
	at com.hazelcast.cache.impl.AbstractHazelcastCacheManager.getCache(AbstractHazelcastCacheManager.java:215)
	at com.hazelcast.cache.impl.AbstractHazelcastCacheManager.getCache(AbstractHazelcastCacheManager.java:63)
	at com.hazelcast.cache.CacheFromDifferentNodesTest.testCompletionTestByPuttingAndRemovingFromDifferentNodes(CacheFromDifferentNodesTest.java:147)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.maintenance-ZuluJDK8/com.hazelcast$hazelcast/54/testReport/junit/com.hazelcast.cache/CacheFromDifferentNodesTest/testCompletionTestByPuttingAndRemovingFromDifferentNodes/

**Comment by hasancelik** [comment]
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.lang.Object.wait(Native Method)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.get(InvocationFuture.java:219)
	at com.hazelcast.util.FutureUtil.executeWithDeadline(FutureUtil.java:294)
	at com.hazelcast.util.FutureUtil.waitWithDeadline(FutureUtil.java:278)
	at com.hazelcast.util.FutureUtil.waitWithDeadline(FutureUtil.java:252)
	at com.hazelcast.spi.impl.eventservice.impl.EventServiceImpl.invokeRegistrationOnOtherNodes(EventServiceImpl.java:251)
	at com.hazelcast.spi.impl.eventservice.impl.EventServiceImpl.registerListenerInternal(EventServiceImpl.java:205)
	at com.hazelcast.spi.impl.eventservice.impl.EventServiceImpl.registerListener(EventServiceImpl.java:186)
	at com.hazelcast.cache.impl.AbstractCacheService.registerListenerInternal(AbstractCacheService.java:408)
	at com.hazelcast.cache.impl.AbstractCacheService.registerListener(AbstractCacheService.java:391)
	at com.hazelcast.cache.impl.CacheProxy.registerCacheEntryListener(CacheProxy.java:301)
	at com.hazelcast.cache.impl.AbstractHazelcastCacheManager.registerListeners(AbstractHazelcastCacheManager.java:412)
	at com.hazelcast.cache.impl.AbstractHazelcastCacheManager.getCacheUnchecked(AbstractHazelcastCacheManager.java:252)
	at com.hazelcast.cache.impl.AbstractHazelcastCacheManager.getCache(AbstractHazelcastCacheManager.java:215)
	at com.hazelcast.cache.impl.AbstractHazelcastCacheManager.getCache(AbstractHazelcastCacheManager.java:63)
	at com.hazelcast.cache.CacheFromDifferentNodesTest.testCompletionTestByPuttingAndRemovingFromDifferentNodes(CacheFromDifferentNodesTest.java:147)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-ZuluJDK8/com.hazelcast$hazelcast/178/testReport/junit/com.hazelcast.cache/CacheFromDifferentNodesTest/testCompletionTestByPuttingAndRemovingFromDifferentNodes/

**Comment by hasancelik** [comment]
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.getTypeId(StreamSerializerAdapter.java:51)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.writeObject(AbstractSerializationService.java:198)
	at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataOutput.writeObject(ByteArrayObjectDataOutput.java:371)
	at com.hazelcast.cache.impl.operation.CacheListenerRegistrationOperation.writeInternal(CacheListenerRegistrationOperation.java:72)
	at com.hazelcast.spi.Operation.writeData(Operation.java:479)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.write(DataSerializableSerializer.java:161)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.write(DataSerializableSerializer.java:52)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.write(StreamSerializerAdapter.java:41)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:140)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:124)
	at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.send(OperationServiceImpl.java:374)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeRemote(Invocation.java:283)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:261)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:230)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:205)
	at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.invokeOnTarget(OperationServiceImpl.java:297)
	at com.hazelcast.cache.impl.CacheProxy.updateCacheListenerConfigOnOtherNodes(CacheProxy.java:322)
	at com.hazelcast.cache.impl.CacheProxy.registerCacheEntryListener(CacheProxy.java:292)
	at com.hazelcast.cache.impl.AbstractHazelcastCacheManager.registerListeners(AbstractHazelcastCacheManager.java:424)
	at com.hazelcast.cache.impl.AbstractHazelcastCacheManager.getCacheUnchecked(AbstractHazelcastCacheManager.java:255)
	at com.hazelcast.cache.impl.AbstractHazelcastCacheManager.getCache(AbstractHazelcastCacheManager.java:218)
	at com.hazelcast.cache.impl.AbstractHazelcastCacheManager.getCache(AbstractHazelcastCacheManager.java:66)
	at com.hazelcast.cache.CacheFromDifferentNodesTest.testCompletionTestByPuttingAndRemovingFromDifferentNodes(CacheFromDifferentNodesTest.java:147)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK1.8/com.hazelcast$hazelcast/219/testReport/junit/com.hazelcast.cache/CacheFromDifferentNodesTest/testCompletionTestByPuttingAndRemovingFromDifferentNodes/

**Comment by hasancelik** [comment]
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:349)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:182)
	at com.hazelcast.util.FutureUtil.executeWithDeadline(FutureUtil.java:294)
	at com.hazelcast.util.FutureUtil.waitWithDeadline(FutureUtil.java:278)
	at com.hazelcast.util.FutureUtil.waitWithDeadline(FutureUtil.java:252)
	at com.hazelcast.spi.impl.eventservice.impl.EventServiceImpl.invokeRegistrationOnOtherNodes(EventServiceImpl.java:251)
	at com.hazelcast.spi.impl.eventservice.impl.EventServiceImpl.registerListenerInternal(EventServiceImpl.java:205)
	at com.hazelcast.spi.impl.eventservice.impl.EventServiceImpl.registerListener(EventServiceImpl.java:186)
	at com.hazelcast.cache.impl.AbstractCacheService.registerListenerInternal(AbstractCacheService.java:460)
	at com.hazelcast.cache.impl.AbstractCacheService.registerListener(AbstractCacheService.java:443)
	at com.hazelcast.cache.impl.CacheProxy.registerCacheEntryListener(CacheProxy.java:288)
	at com.hazelcast.cache.impl.AbstractHazelcastCacheManager.registerListeners(AbstractHazelcastCacheManager.java:425)
	at com.hazelcast.cache.impl.AbstractHazelcastCacheManager.getCacheUnchecked(AbstractHazelcastCacheManager.java:255)
	at com.hazelcast.cache.impl.AbstractHazelcastCacheManager.getCache(AbstractHazelcastCacheManager.java:218)
	at com.hazelcast.cache.impl.AbstractHazelcastCacheManager.getCache(AbstractHazelcastCacheManager.java:66)
	at com.hazelcast.cache.CacheFromDifferentNodesTest.testCompletionTestByPuttingAndRemovingFromDifferentNodes(CacheFromDifferentNodesTest.java:147)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.8/com.hazelcast$hazelcast/236/testReport/junit/com.hazelcast.cache/CacheFromDifferentNodesTest/testCompletionTestByPuttingAndRemovingFromDifferentNodes/

**Comment by serkan-ozal** [comment]
The issue is caused by infinite loop while iterating `CacheEntryListenerConfiguration`s in the `AbstractHazelcastCacheManager::registerListeners`. 

There is infinite loop because  `CacheEntryListenerConfiguration` is removed through iterator and readded through `CacheConfig` (in the `CacheProxy::registerCacheEntryListener`). But the readded `CacheEntryListenerConfiguration` might be put to the end (or anywhere at the next of current item) of the collection. So the same items are reiterated over and over again.
