### ISSUE TITLE
Invocation_TimeoutTest.async_whenCallTimeout_thenOperationTimeoutException & sync_whenCallTimeout_thenOperationTimeoutException

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#7932]
```
DummyOperation invocation failed to complete due to operation-heartbeat-timeout. 
Total elapsed time: 10665 ms. 
Last heartbeat: never. Invocation{op=com.hazelcast.spi.impl.operationservice.impl.DummyOperation{serviceName='null', identityHash=1593789295, partitionId=1, replicaIndex=0, callId=0, invocationTime=1460335510642 (Mon Apr 11 03:45:10 EEST 2016), waitTimeout=-1, callTimeout=5000}, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=5000, firstInvocationTimeMs=1460335510642, firstInvocationTime='Mon Apr 11 03:45:10 EEST 2016', lastHeartbeatMillis=0, lastHeartbeatTime='Thu Jan 01 02:00:00 EET 1970', target=Address[127.0.0.1]:7970, pendingResponse={VOID}, backupsExpected=0, backupsCompleted=0, connection=MockConnection{localEndpoint=Address[127.0.0.1]:7969, remoteEndpoint=Address[127.0.0.1]:7970}}
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-ZuluJDK8/com.hazelcast$hazelcast/171/testReport/junit/com.hazelcast.spi.impl.operationservice.impl/Invocation_TimeoutTest/async_whenCallTimeout_thenOperationTimeoutException/

**Comment by hasancelik** [comment]
```
DummyOperation invocation failed to complete due to operation-heartbeat-timeout. Current time: 2016-05-11 18:52:19.699. Total elapsed time: 10037 ms. Last heartbeat: never. Last member heartbeat: 2016-05-11 18:52:18.856. Invocation{op=com.hazelcast.spi.impl.operationservice.impl.DummyOperation{serviceName='null', identityHash=1707326604, partitionId=2, replicaIndex=0, callId=0, invocationTime=1462981929662 (2016-05-11 18:52:09.662), waitTimeout=-1, callTimeout=5000}, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=5000, firstInvocationTimeMs=1462981929662, firstInvocationTime='2016-05-11 18:52:09.662', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 02:00:00.000', target=[127.0.0.1]:10503, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=MockConnection{localEndpoint=[127.0.0.1]:10502, remoteEndpoint=[127.0.0.1]:10503}}
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x/com.hazelcast$hazelcast/5064/testReport/junit/com.hazelcast.spi.impl.operationservice.impl/Invocation_TimeoutTest/async_whenCallTimeout_thenOperationTimeoutException/

**Comment by hasancelik** [comment]
```
DummyOperation invocation failed to complete due to operation-heartbeat-timeout. Current time: 2016-05-26 05:14:51.801. Total elapsed time: 10000 ms. Last heartbeat: never. Last member heartbeat: 2016-05-26 05:14:51.199. Invocation{op=com.hazelcast.spi.impl.operationservice.impl.DummyOperation{serviceName='null', identityHash=523555722, partitionId=2, replicaIndex=0, callId=0, invocationTime=1464228881801 (2016-05-26 05:14:41.801), waitTimeout=-1, callTimeout=5000}, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=5000, firstInvocationTimeMs=1464228881801, firstInvocationTime='2016-05-26 05:14:41.801', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 02:00:00.000', target=[127.0.0.1]:13808, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=MockConnection{localEndpoint=[127.0.0.1]:13807, remoteEndpoint=[127.0.0.1]:13808}}
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast$hazelcast/921/testReport/junit/com.hazelcast.spi.impl.operationservice.impl/Invocation_TimeoutTest/sync_whenCallTimeout_thenOperationTimeoutException/

**Comment by hasancelik** [comment]
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.lang.Thread.sleep(Native Method)
	at java.lang.Thread.sleep(Thread.java:340)
	at java.util.concurrent.TimeUnit.sleep(TimeUnit.java:386)
	at com.hazelcast.test.HazelcastTestSupport.sleepMillis(HazelcastTestSupport.java:280)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:883)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:889)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation_TimeoutTest.assertEventuallyFailsWithCallTimeout(Invocation_TimeoutTest.java:56)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation_TimeoutTest.async_whenCallTimeout_thenOperationTimeoutException(Invocation_TimeoutTest.java:344)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-ZuluJDK8/com.hazelcast$hazelcast/223/testReport/junit/com.hazelcast.spi.impl.operationservice.impl/Invocation_TimeoutTest/async_whenCallTimeout_thenOperationTimeoutException/

**Comment by hasancelik** [comment]
**sync_whenCallTimeout_thenOperationTimeoutException**
```
java.lang.AssertionError: DummyOperation invocation failed to complete due to operation-heartbeat-timeout. Current time: 2016-06-05 05:41:54.230. Total elapsed time: 10035 ms. Last operation heartbeat: never. Last operation heartbeat from member: 2016-06-05 05:41:53.951. Invocation{op=com.hazelcast.spi.impl.operationservice.impl.DummyOperation{serviceName='null', identityHash=1386057644, partitionId=1, replicaIndex=0, callId=0, invocationTime=1465094504195 (2016-06-05 05:41:44.195), waitTimeout=-1, callTimeout=5000}, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=5000, firstInvocationTimeMs=1465094504195, firstInvocationTime='2016-06-05 05:41:44.195', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 02:00:00.000', target=[127.0.0.1]:11922, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=MockConnection{localEndpoint=[127.0.0.1]:11921, remoteEndpoint=[127.0.0.1]:11922}}
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation_TimeoutTest.sync_whenCallTimeout_thenOperationTimeoutException(Invocation_TimeoutTest.java:321)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK1.6/com.hazelcast$hazelcast/931/testReport/junit/com.hazelcast.spi.impl.operationservice.impl/Invocation_TimeoutTest/sync_whenCallTimeout_thenOperationTimeoutException/

**Comment by hasancelik** [comment]
**sync_whenCallTimeout_thenOperationTimeoutException**
```
java.lang.AssertionError: DummyOperation invocation failed to complete due to operation-heartbeat-timeout. Current time: 2016-06-14 06:15:12.026. Total elapsed time: 10693 ms. Last operation heartbeat: never. Last operation heartbeat from member: 2016-06-14 06:15:11.025. Invocation{op=com.hazelcast.spi.impl.operationservice.impl.DummyOperation{serviceName='null', identityHash=519580774, partitionId=3, replicaIndex=0, callId=0, invocationTime=1465874101333 (2016-06-14 06:15:01.333), waitTimeout=-1, callTimeout=5000}, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=5000, firstInvocationTimeMs=1465874101333, firstInvocationTime='2016-06-14 06:15:01.333', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 02:00:00.000', target=[127.0.0.1]:13293, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=MockConnection{localEndpoint=[127.0.0.1]:13292, remoteEndpoint=[127.0.0.1]:13293}}
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation_TimeoutTest.sync_whenCallTimeout_thenOperationTimeoutException(Invocation_TimeoutTest.java:321)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-OracleJDK1.7/com.hazelcast$hazelcast/512/testReport/junit/com.hazelcast.spi.impl.operationservice.impl/Invocation_TimeoutTest/sync_whenCallTimeout_thenOperationTimeoutException/

**Comment by hasancelik** [comment]
**async_whenCallTimeout_thenOperationTimeoutException**
```
java.lang.AssertionError: DummyOperation invocation failed to complete due to operation-heartbeat-timeout. Current time: 2016-06-15 07:08:58.955. Total elapsed time: 10338 ms. Last operation heartbeat: never. Last operation heartbeat from member: 2016-06-15 07:08:58.342. Invocation{op=com.hazelcast.spi.impl.operationservice.impl.DummyOperation{serviceName='null', identityHash=1503447421, partitionId=0, replicaIndex=0, callId=0, invocationTime=1465963728617 (2016-06-15 07:08:48.617), waitTimeout=-1, callTimeout=5000}, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=5000, firstInvocationTimeMs=1465963728617, firstInvocationTime='2016-06-15 07:08:48.617', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 02:00:00.000', target=[127.0.0.1]:5072, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=MockConnection{localEndpoint=[127.0.0.1]:5071, remoteEndpoint=[127.0.0.1]:5072}}
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation_TimeoutTest$2.run(Invocation_TimeoutTest.java:64)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:884)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:898)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation_TimeoutTest.assertEventuallyFailsWithCallTimeout(Invocation_TimeoutTest.java:56)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation_TimeoutTest.async_whenCallTimeout_thenOperationTimeoutException(Invocation_TimeoutTest.java:344)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x/com.hazelcast$hazelcast/5256/testReport/junit/com.hazelcast.spi.impl.operationservice.impl/Invocation_TimeoutTest/async_whenCallTimeout_thenOperationTimeoutException/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: DummyOperation invocation failed to complete due to operation-heartbeat-timeout. Current time: 2016-06-20 04:57:55.987. Total elapsed time: 20782 ms. Last operation heartbeat: never. Last operation heartbeat from member: 2016-06-20 04:57:53.436. Invocation{op=com.hazelcast.spi.impl.operationservice.impl.DummyOperation{serviceName='null', identityHash=91811738, partitionId=0, replicaIndex=0, callId=0, invocationTime=1466387855205 (2016-06-20 04:57:35.205), waitTimeout=-1, callTimeout=10000}, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=10000, firstInvocationTimeMs=1466387855205, firstInvocationTime='2016-06-20 04:57:35.205', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 02:00:00.000', target=[127.0.0.1]:13186, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=MockConnection{localEndpoint=[127.0.0.1]:13185, remoteEndpoint=[127.0.0.1]:13186}}
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation_TimeoutTest.sync_whenCallTimeout_thenOperationTimeoutException(Invocation_TimeoutTest.java:321)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-ZuluJDK8/com.hazelcast$hazelcast/240/testReport/junit/com.hazelcast.spi.impl.operationservice.impl/Invocation_TimeoutTest/sync_whenCallTimeout_thenOperationTimeoutException/

**Comment by pveentjer** [comment]
I increased the timeouts from 10 to 60 seconds. So closing this again and I hope it stays closed.

**Comment by hasancelik** [comment]
**failed in spite of** https://github.com/hazelcast/hazelcast/commit/a8d01090e54c94d76357f5234b83a9e3df9d3577

```
org.mockito.exceptions.verification.WantedButNotInvoked: 
Wanted but not invoked:
executionCallback.onFailure(
    <Capturing argument>
);
-> at com.hazelcast.spi.impl.operationservice.impl.Invocation_TimeoutTest$2.run(Invocation_TimeoutTest.java:60)
Actually, there were zero interactions with this mock.

	at com.hazelcast.spi.impl.operationservice.impl.Invocation_TimeoutTest$2.run(Invocation_TimeoutTest.java:60)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:884)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:898)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation_TimeoutTest.assertEventuallyFailsWithCallTimeout(Invocation_TimeoutTest.java:56)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation_TimeoutTest.async_whenCallTimeout_thenOperationTimeoutException(Invocation_TimeoutTest.java:344)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-sonar/com.hazelcast$hazelcast/1101/testReport/junit/com.hazelcast.spi.impl.operationservice.impl/Invocation_TimeoutTest/async_whenCallTimeout_thenOperationTimeoutException/

**Comment by hasancelik** [comment]
```
ava.lang.AssertionError: DummyOperation invocation failed to complete due to operation-heartbeat-timeout. Current time: 2016-06-22 16:39:21.143. Total elapsed time: 120388 ms. Last operation heartbeat: never. Last operation heartbeat from member: 2016-06-22 16:39:19.151. Invocation{op=com.hazelcast.spi.impl.operationservice.impl.DummyOperation{serviceName='null', identityHash=536582790, partitionId=0, replicaIndex=0, callId=0, invocationTime=1466602640755 (2016-06-22 16:37:20.755), waitTimeout=-1, callTimeout=60000}, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=60000, firstInvocationTimeMs=1466602640755, firstInvocationTime='2016-06-22 16:37:20.755', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 02:00:00.000', target=[127.0.0.1]:14070, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=MockConnection{localEndpoint=[127.0.0.1]:14069, remoteEndpoint=[127.0.0.1]:14070}}
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation_TimeoutTest.sync_whenCallTimeout_thenOperationTimeoutException(Invocation_TimeoutTest.java:321)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x/com.hazelcast$hazelcast/5316/testReport/junit/com.hazelcast.spi.impl.operationservice.impl/Invocation_TimeoutTest/sync_whenCallTimeout_thenOperationTimeoutException/

**Comment by hasancelik** [comment]
```
org.mockito.exceptions.verification.WantedButNotInvoked: 
Wanted but not invoked:
executionCallback.onFailure(
    <Capturing argument>
);
-> at com.hazelcast.spi.impl.operationservice.impl.Invocation_TimeoutTest$4.run(Invocation_TimeoutTest.java:341)
Actually, there were zero interactions with this mock.

	at com.hazelcast.spi.impl.operationservice.impl.Invocation_TimeoutTest$4.run(Invocation_TimeoutTest.java:341)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:884)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:898)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation_TimeoutTest.assertEventuallyFailsWithCallTimeout(Invocation_TimeoutTest.java:337)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation_TimeoutTest.async_whenCallTimeout_thenOperationTimeoutException(Invocation_TimeoutTest.java:315)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.8/com.hazelcast$hazelcast/264/testReport/junit/com.hazelcast.spi.impl.operationservice.impl/Invocation_TimeoutTest/async_whenCallTimeout_thenOperationTimeoutException/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: DummyOperation invocation failed to complete due to operation-heartbeat-timeout. Current time: 2016-06-26 04:50:59.905. Total elapsed time: 120736 ms. Last operation heartbeat: never. Last operation heartbeat from member: 2016-06-26 04:50:52.885. Invocation{op=com.hazelcast.spi.impl.operationservice.impl.DummyOperation{serviceName='null', identityHash=1100826642, partitionId=3, replicaIndex=0, callId=0, invocationTime=1466905739169 (2016-06-26 04:48:59.169), waitTimeout=-1, callTimeout=60000}, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=60000, firstInvocationTimeMs=1466905739169, firstInvocationTime='2016-06-26 04:48:59.169', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 02:00:00.000', target=[127.0.0.1]:12399, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=MockConnection{localEndpoint=[127.0.0.1]:12398, remoteEndpoint=[127.0.0.1]:12399}}
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation_TimeoutTest$4.run(Invocation_TimeoutTest.java:345)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:884)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:898)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation_TimeoutTest.assertEventuallyFailsWithCallTimeout(Invocation_TimeoutTest.java:337)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation_TimeoutTest.async_whenCallTimeout_thenOperationTimeoutException(Invocation_TimeoutTest.java:315)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-ZuluJDK8/com.hazelcast$hazelcast/247/testReport/junit/com.hazelcast.spi.impl.operationservice.impl/Invocation_TimeoutTest/async_whenCallTimeout_thenOperationTimeoutException/

**Comment by jerrinot** [comment]
so finding from the build linked by Hasan at https://github.com/hazelcast/hazelcast/issues/7932#issuecomment-228716045

- The test was supposed to finish with `call-timeout`, but it failed with `operation-heartbeat-timeout`

Current time: 2016-06-26 04:50:59.905. 
Total elapsed time: 120736 ms. 
Last operation heartbeat: never. Last operation heartbeat from member: 2016-06-26 04:50:52.885.

**Comment by pveentjer** [comment]
since heartbeats are send by that member, it is strange that the operation is missing its heartbeat

**Comment by pveentjer** [comment]
perhaps the operation is pending in the operation queue? These don't get heartbeats.

**Comment by jerrinot** [comment]
indeed. the operation is supposed to be running. it should produce at least 1 operation heartbeat. so I would guess it wasn't executed at all. it was pending in *some* queue.

**Comment by jerrinot** [comment]
I can see this in the log: `04:49:10,166  WARN |async_whenCallTimeout_thenOperationTimeoutException| - [SlowOperationDetector] hz._hzInstance_7218_dev.SlowOperationDetectorThread - [127.0.0.1]:12399 [dev] [3.7-SNAPSHOT] Slow operation detected: com.hazelcast.spi.impl.operationservice.impl.SlowOperation`

so the operation WAS running on the target member [127.0.0.1]:12399

**Comment by pveentjer** [comment]
then why was heartbeat not created (or received)

**Comment by jerrinot** [comment]
that's the million dollar question:)


the `Future.complete(Object value) can only be called once` error has timestamp `04:50:59,882` which is almost exactly 120s from `invocationTime=1466905739169 (2016-06-26 04:48:59.169)`

The operation is supposed configured to run 2 minutes -> it was started immediately after the invocation was created. Yet it was not included in operation heartbeats. However the heartbeating seems fine otherwise as there is `Last operation heartbeat from member: 2016-06-26 04:50:52.885`

Something fishy is going on!

**Comment by pveentjer** [comment]
Do you know if the call was executed locally or remote?

**Comment by jerrinot** [comment]
remotely. this is from the error: `04:50:59,882  WARN |async_whenCallTimeout_thenOperationTimeoutException| - [Invocation] hz._hzInstance_7214_dev.response - [127.0.0.1]:12398 [dev] [3.7-SNAPSHOT]  [...] target=[127.0.0.1]:12399`

-> The invocation is created at `[127.0.0.1]:12398` and the target member is `[127.0.0.1]:12399`

**Comment by pveentjer** [comment]
since the sender member has received heartbeat quite recently it is very unlikely that it is an io issue.. or that something got stuck.. more an issue of not seeing.... or.. maybe the ping was received.. but not processed correctly.. or maybe the ping was send to the wrong member..
