### ISSUE TITLE
[operation] OperationServiceImpl_timeoutTest.testOperationTimeoutForLongRunningRemoteOperation

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#7940]
```
SleepingOperation invocation failed to complete due to operation-heartbeat-timeout. Total elapsed time: 4146 ms. Last heartbeat: Tue Apr 12 05:34:56 EEST 2016. Invocation{op=com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl_timeoutTest$SleepingOperation{serviceName='null', identityHash=1369455642, partitionId=-1, replicaIndex=0, callId=0, invocationTime=1460428493339 (Tue Apr 12 05:34:53 EEST 2016), waitTimeout=-1, callTimeout=1000}, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=1000, firstInvocationTimeMs=1460428493339, firstInvocationTime='Tue Apr 12 05:34:53 EEST 2016', lastHeartbeatMillis=1460428496465, lastHeartbeatTime='Tue Apr 12 05:34:56 EEST 2016', target=Address[127.0.0.1]:7668, pendingResponse={VOID}, backupsExpected=0, backupsCompleted=0, connection=MockConnection{localEndpoint=Address[127.0.0.1]:7667, remoteEndpoint=Address[127.0.0.1]:7668}}
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-OracleJDK8/com.hazelcast$hazelcast/773/testReport/junit/com.hazelcast.spi.impl.operationservice.impl/OperationServiceImpl_timeoutTest/testOperationTimeoutForLongRunningRemoteOperation/

**Comment by hasancelik** [comment]
```
SleepingOperation invocation failed to complete due to operation-heartbeat-timeout. Current time: 2016-04-29 05:33:35.743. Total elapsed time: 3608 ms. Last heartbeat: 2016-04-29 05:33:34.070. Last member heartbeat: 2016-04-29 05:33:35.743. Invocation{op=com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl_timeoutTest$SleepingOperation{serviceName='null', identityHash=1662732270, partitionId=-1, replicaIndex=0, callId=0, invocationTime=1461897212135 (2016-04-29 05:33:32.135), waitTimeout=-1, callTimeout=1000}, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=1000, firstInvocationTimeMs=1461897212135, firstInvocationTime='2016-04-29 05:33:32.135', lastHeartbeatMillis=1461897214070, lastHeartbeatTime='2016-04-29 05:33:34.070', target=Address[127.0.0.1]:8098, pendingResponse={VOID}, backupsExpected=0, backupsCompleted=0, connection=MockConnection{localEndpoint=Address[127.0.0.1]:8097, remoteEndpoint=Address[127.0.0.1]:8098}}
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-OracleJDK1.6/com.hazelcast$hazelcast/893/testReport/junit/com.hazelcast.spi.impl.operationservice.impl/OperationServiceImpl_timeoutTest/testOperationTimeoutForLongRunningRemoteOperation/

**Comment by hasancelik** [comment]
```
SleepingOperation invocation failed to complete due to operation-heartbeat-timeout. Current time: 2016-05-03 10:04:37.350. Total elapsed time: 4587 ms. Last heartbeat: 2016-05-03 10:04:36.258. Last member heartbeat: 2016-05-03 10:04:37.350. Invocation{op=com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl_timeoutTest$SleepingOperation{serviceName='null', identityHash=399659162, partitionId=-1, replicaIndex=0, callId=0, invocationTime=1462259072763 (2016-05-03 10:04:32.763), waitTimeout=-1, callTimeout=1000}, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=1000, firstInvocationTimeMs=1462259072763, firstInvocationTime='2016-05-03 10:04:32.763', lastHeartbeatMillis=1462259076258, lastHeartbeatTime='2016-05-03 10:04:36.258', target=Address[127.0.0.1]:8903, pendingResponse={VOID}, backupsExpected=0, backupsCompleted=0, connection=MockConnection{localEndpoint=Address[127.0.0.1]:8900, remoteEndpoint=Address[127.0.0.1]:8903}}
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x/com.hazelcast$hazelcast/4977/testReport/junit/com.hazelcast.spi.impl.operationservice.impl/OperationServiceImpl_timeoutTest/testOperationTimeoutForLongRunningRemoteOperation/

**Comment by hasancelik** [comment]
```
SleepingOperation invocation failed to complete due to operation-heartbeat-timeout. Current time: 2016-05-12 09:52:55.755. Total elapsed time: 4017 ms. Last heartbeat: 2016-05-12 09:52:53.857. Last member heartbeat: 2016-05-12 09:52:55.754. Invocation{op=com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl_timeoutTest$SleepingOperation{serviceName='null', identityHash=603031675, partitionId=-1, replicaIndex=0, callId=0, invocationTime=1463035971739 (2016-05-12 09:52:51.739), waitTimeout=-1, callTimeout=1000}, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=1000, firstInvocationTimeMs=1463035971739, firstInvocationTime='2016-05-12 09:52:51.739', lastHeartbeatMillis=1463035973857, lastHeartbeatTime='2016-05-12 09:52:53.857', target=[127.0.0.1]:11270, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=MockConnection{localEndpoint=[127.0.0.1]:11269, remoteEndpoint=[127.0.0.1]:11270}}
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x/com.hazelcast$hazelcast/5067/testReport/junit/com.hazelcast.spi.impl.operationservice.impl/OperationServiceImpl_timeoutTest/testOperationTimeoutForLongRunningRemoteOperation/

**Comment by hasancelik** [comment]
```
SleepingOperation invocation failed to complete due to operation-heartbeat-timeout. Current time: 2016-05-19 06:32:36.726. Total elapsed time: 4179 ms. Last heartbeat: 2016-05-19 06:32:35.722. Last member heartbeat: 2016-05-19 06:32:36.726. Invocation{op=com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl_timeoutTest$SleepingOperation{serviceName='null', identityHash=183583103, partitionId=-1, replicaIndex=0, callId=0, invocationTime=1463628752547 (2016-05-19 06:32:32.547), waitTimeout=-1, callTimeout=1000}, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=1000, firstInvocationTimeMs=1463628752547, firstInvocationTime='2016-05-19 06:32:32.547', lastHeartbeatMillis=1463628755722, lastHeartbeatTime='2016-05-19 06:32:35.722', target=[127.0.0.1]:14809, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=MockConnection{localEndpoint=[127.0.0.1]:14808, remoteEndpoint=[127.0.0.1]:14809}}
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK1.6/com.hazelcast$hazelcast/913/testReport/junit/com.hazelcast.spi.impl.operationservice.impl/OperationServiceImpl_timeoutTest/testOperationTimeoutForLongRunningRemoteOperation/

**Comment by hasancelik** [comment]
```
java.util.concurrent.ExecutionException: SleepingOperation invocation failed to complete due to operation-heartbeat-timeout. Current time: 2016-05-26 05:39:09.803. Total elapsed time: 3000 ms. Last heartbeat: 2016-05-26 05:39:06.855. Last member heartbeat: 2016-05-26 05:39:08.855. Invocation{op=com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl_timeoutTest$SleepingOperation{serviceName='null', identityHash=545855619, partitionId=-1, replicaIndex=0, callId=0, invocationTime=1464230346803 (2016-05-26 05:39:06.803), waitTimeout=-1, callTimeout=1000}, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=1000, firstInvocationTimeMs=1464230346803, firstInvocationTime='2016-05-26 05:39:06.803', lastHeartbeatMillis=1464230346855, lastHeartbeatTime='2016-05-26 05:39:06.855', target=[127.0.0.1]:11731, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=MockConnection{localEndpoint=[127.0.0.1]:11730, remoteEndpoint=[127.0.0.1]:11731}}
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.newOperationTimeoutException(InvocationFuture.java:150)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:98)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrow(InvocationFuture.java:74)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:150)
	at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl_timeoutTest.testOperationTimeoutForLongRunningRemoteOperation(OperationServiceImpl_timeoutTest.java:193)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-OracleJDK1.6/com.hazelcast$hazelcast/920/testReport/junit/com.hazelcast.spi.impl.operationservice.impl/OperationServiceImpl_timeoutTest/testOperationTimeoutForLongRunningRemoteOperation/

**Comment by hasancelik** [comment]
```
java.util.concurrent.ExecutionException: SleepingOperation invocation failed to complete due to operation-heartbeat-timeout. Current time: 2016-06-01 18:53:28.418. Total elapsed time: 3000 ms. Last heartbeat: 2016-06-01 18:53:26.307. Last member heartbeat: 2016-06-01 18:53:27.901. Invocation{op=com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl_timeoutTest$SleepingOperation{serviceName='null', identityHash=186810643, partitionId=-1, replicaIndex=0, callId=0, invocationTime=1464796405418 (2016-06-01 18:53:25.418), waitTimeout=-1, callTimeout=1000}, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=1000, firstInvocationTimeMs=1464796405418, firstInvocationTime='2016-06-01 18:53:25.418', lastHeartbeatMillis=1464796406307, lastHeartbeatTime='2016-06-01 18:53:26.307', target=[127.0.0.1]:13821, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=MockConnection{localEndpoint=[127.0.0.1]:13820, remoteEndpoint=[127.0.0.1]:13821}}
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.newOperationTimeoutException(InvocationFuture.java:150)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:98)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrow(InvocationFuture.java:74)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:150)
	at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl_timeoutTest.testOperationTimeoutForLongRunningRemoteOperation(OperationServiceImpl_timeoutTest.java:193)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x/com.hazelcast$hazelcast/5187/testReport/junit/com.hazelcast.spi.impl.operationservice.impl/OperationServiceImpl_timeoutTest/testOperationTimeoutForLongRunningRemoteOperation/

**Comment by jerrinot** [comment]
This failure is quite clear - The test uses 1000ms as a (global) call timeout. 

However this also drives a frequency within a [MonitorInvocationTask](https://github.com/jerrinot/hazelcast/blob/3e513c2e9f1835d83c90925312067762cc5870d2/hazelcast/src/main/java/com/hazelcast/spi/impl/operationservice/impl/InvocationMonitor.java#L224-L224) is expecting to receive heartbeats. 

so with 1s call timeout the [MonitorInvocationtTasks] expects to receive a heartbeat (at least) every 1s -> a bad thread scheduling or GC can cause the timeout.

**Comment by Donnerbart** [comment]
**com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl_timeoutTest.testOperationTimeoutForLongRunningRemoteOperation**
```java
java.util.concurrent.ExecutionException: SleepingOperation invocation failed to complete due to operation-heartbeat-timeout. Current time: 2017-05-17 14:41:09.977. Start time: 2017-05-17 14:41:00.970. Total elapsed time: 9008 ms. Last operation heartbeat: 2017-05-17 14:41:05.616. Last operation heartbeat from member: 2017-05-17 14:41:09.606. Invocation{op=com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl_timeoutTest$SleepingOperation{serviceName='null', identityHash=806986018, partitionId=-1, replicaIndex=0, callId=-2, invocationTime=1495032060970 (2017-05-17 14:41:00.970), waitTimeout=-1, callTimeout=3000}, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=3000, firstInvocationTimeMs=1495032060970, firstInvocationTime='2017-05-17 14:41:00.970', lastHeartbeatMillis=1495032065616, lastHeartbeatTime='2017-05-17 14:41:05.616', target=[127.0.0.1]:5043, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=MockConnection{localEndpoint=[127.0.0.1]:5042, remoteEndpoint=[127.0.0.1]:5043}}
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.newOperationTimeoutException(InvocationFuture.java:157)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:104)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:77)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:147)
	at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl_timeoutTest.testOperationTimeoutForLongRunningRemoteOperation(OperationServiceImpl_timeoutTest.java:208)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/8986/testReport/junit/com.hazelcast.spi.impl.operationservice.impl/OperationServiceImpl_timeoutTest/testOperationTimeoutForLongRunningRemoteOperation/

**Comment by sancar** [comment]
Failed again in maintenance pr builder

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-pr-builder/15877/testReport/junit/com.hazelcast.spi.impl.operationservice.impl/OperationServiceImpl_timeoutTest/testOperationTimeoutForLongRunningRemoteOperation/

```
Error Message
SleepingOperation invocation failed to complete due to operation-heartbeat-timeout. Current time: 2018-06-04 10:04:47.077. Start time: 2018-06-04 10:04:29.076. Total elapsed time: 18001 ms. Last operation heartbeat: 2018-06-04 10:04:32.087. Last operation heartbeat from member: 2018-06-04 10:04:45.583. Invocation{op=com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl_timeoutTest$SleepingOperation{serviceName='null', identityHash=402755160, partitionId=-1, replicaIndex=0, callId=-4, invocationTime=1528106669076 (2018-06-04 10:04:29.076), waitTimeout=-1, callTimeout=6000}, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=6000, firstInvocationTimeMs=1528106669076, firstInvocationTime='2018-06-04 10:04:29.076', lastHeartbeatMillis=1528106672087, lastHeartbeatTime='2018-06-04 10:04:32.087', target=[127.0.0.1]:5010, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=MockConnection{localEndpoint=[127.0.0.1]:5009, remoteEndpoint=[127.0.0.1]:5010}}
Stacktrace
java.util.concurrent.ExecutionException: SleepingOperation invocation failed to complete due to operation-heartbeat-timeout. Current time: 2018-06-04 10:04:47.077. Start time: 2018-06-04 10:04:29.076. Total elapsed time: 18001 ms. Last operation heartbeat: 2018-06-04 10:04:32.087. Last operation heartbeat from member: 2018-06-04 10:04:45.583. Invocation{op=com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl_timeoutTest$SleepingOperation{serviceName='null', identityHash=402755160, partitionId=-1, replicaIndex=0, callId=-4, invocationTime=1528106669076 (2018-06-04 10:04:29.076), waitTimeout=-1, callTimeout=6000}, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=6000, firstInvocationTimeMs=1528106669076, firstInvocationTime='2018-06-04 10:04:29.076', lastHeartbeatMillis=1528106672087, lastHeartbeatTime='2018-06-04 10:04:32.087', target=[127.0.0.1]:5010, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=MockConnection{localEndpoint=[127.0.0.1]:5009, remoteEndpoint=[127.0.0.1]:5010}}
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.newOperationTimeoutException(InvocationFuture.java:164)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:106)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:79)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:154)
	at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl_timeoutTest.testOperationTimeoutForLongRunningRemoteOperation(OperationServiceImpl_timeoutTest.java:208)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.hazelcast.core.OperationTimeoutException: SleepingOperation invocation failed to complete due to operation-heartbeat-timeout. Current time: 2018-06-04 10:04:47.077. Start time: 2018-06-04 10:04:29.076. Total elapsed time: 18001 ms. Last operation heartbeat: 2018-06-04 10:04:32.087. Last operation heartbeat from member: 2018-06-04 10:04:45.583. Invocation{op=com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl_timeoutTest$SleepingOperation{serviceName='null', identityHash=402755160, partitionId=-1, replicaIndex=0, callId=-4, invocationTime=1528106669076 (2018-06-04 10:04:29.076), waitTimeout=-1, callTimeout=6000}, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=6000, firstInvocationTimeMs=1528106669076, firstInvocationTime='2018-06-04 10:04:29.076', lastHeartbeatMillis=1528106672087, lastHeartbeatTime='2018-06-04 10:04:32.087', target=[127.0.0.1]:5010, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=MockConnection{localEndpoint=[127.0.0.1]:5009, remoteEndpoint=[127.0.0.1]:5010}}
	... 17 more
```

**Comment by jerrinot** [comment]
there was quite long pauses during the run:
```
10:04:20, accumulated pauses: 1085 ms, max pause: 138 ms, pauses over 1000 ms: 0
10:04:25, accumulated pauses: 2667 ms, max pause: 2000 ms, pauses over 1000 ms: 1
10:04:30, accumulated pauses: 4911 ms, max pause: 4562 ms, pauses over 1000 ms: 1
10:04:35, accumulated pauses: 4290 ms, max pause: 2537 ms, pauses over 1000 ms: 2
10:04:40, accumulated pauses: 704 ms, max pause: 146 ms, pauses over 1000 ms: 0
10:04:45, accumulated pauses: 1287 ms, max pause: 229 ms, pauses over 1000 ms: 0
10:04:50, accumulated pauses: 505 ms, max pause: 37 ms, pauses over 1000 ms: 0
```

most likely this impacted operation heartbeat delivery
