### ISSUE TITLE
SemaphoreSplitBrainTest.testSemaphoreSplitBrain

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#7958]
```
java.lang.AssertionError: expected:<5> but was:<2>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:834)
    at org.junit.Assert.assertEquals(Assert.java:645)
    at org.junit.Assert.assertEquals(Assert.java:631)
    at com.hazelcast.concurrent.semaphore.SemaphoreSplitBrainTest$2.run(SemaphoreSplitBrainTest.java:78)
    at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:857)
    at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:871)
    at com.hazelcast.concurrent.semaphore.SemaphoreSplitBrainTest.testSemaphoreSplitBrain(SemaphoreSplitBrainTest.java:75)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/924/testReport/junit/com.hazelcast.concurrent.semaphore/SemaphoreSplitBrainTest/testSemaphoreSplitBrain/

**Comment by metanet** [comment]
closed via #7912

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: expected:<5> but was:<2>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.concurrent.semaphore.SemaphoreSplitBrainTest$2.run(SemaphoreSplitBrainTest.java:78)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:905)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:919)
	at com.hazelcast.concurrent.semaphore.SemaphoreSplitBrainTest.testSemaphoreSplitBrain(SemaphoreSplitBrainTest.java:75)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/1103/testReport/junit/com.hazelcast.concurrent.semaphore/SemaphoreSplitBrainTest/testSemaphoreSplitBrain/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: expected:<5> but was:<2>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.concurrent.semaphore.SemaphoreSplitBrainTest$2.run(SemaphoreSplitBrainTest.java:78)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:913)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:927)
	at com.hazelcast.concurrent.semaphore.SemaphoreSplitBrainTest.testSemaphoreSplitBrain(SemaphoreSplitBrainTest.java:75)
```

https://hazelcast-l337.ci.cloudbees.com/view/Sonar/job/Hazelcast-3.x-sonar/com.hazelcast$hazelcast/1321/testReport/junit/com.hazelcast.concurrent.semaphore/SemaphoreSplitBrainTest/testSemaphoreSplitBrain/

**Comment by sancar** [comment]
@mdogan Failed again. Reopening for you to investigate. 
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/6560/testReport/junit/com.hazelcast.concurrent.semaphore/SemaphoreSplitBrainTest/testSemaphoreSplitBrain/

    Error Message

     expected:<5> but was:<2>
    Stacktrace

      java.lang.AssertionError: expected:<5> but was:<2>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.concurrent.semaphore.SemaphoreSplitBrainTest$1.run(SemaphoreSplitBrainTest.java:55)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:920)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:934)
	at com.hazelcast.concurrent.semaphore.SemaphoreSplitBrainTest.testSemaphoreSplitBrain(SemaphoreSplitBrainTest.java:52)

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: expected:<5> but was:<2>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.concurrent.semaphore.SemaphoreSplitBrainTest$2.run(SemaphoreSplitBrainTest.java:78)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:911)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:925)
	at com.hazelcast.concurrent.semaphore.SemaphoreSplitBrainTest.testSemaphoreSplitBrain(SemaphoreSplitBrainTest.java:75)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-nightly/com.hazelcast$hazelcast/1102/testReport/junit/com.hazelcast.concurrent.semaphore/SemaphoreSplitBrainTest/testSemaphoreSplitBrain/
