### ISSUE TITLE
ReplicatedMapTtlTest.testPutWithTTL_withMigration & testPutWithTTL_withoutMigration

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#7994]
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.lang.Object.wait(Native Method)
	at java.lang.Thread.join(Thread.java:1245)
	at java.lang.Thread.join(Thread.java:1319)
	at com.hazelcast.replicatedmap.ReplicatedMapTtlTest.testPutWithTTL(ReplicatedMapTtlTest.java:60)
	at com.hazelcast.replicatedmap.ReplicatedMapTtlTest.testPutWithTTL_withMigration(ReplicatedMapTtlTest.java:29)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-sonar/com.hazelcast$hazelcast/1028/testReport/junit/com.hazelcast.replicatedmap/ReplicatedMapTtlTest/testPutWithTTL_withMigration/

**Comment by hasancelik** [comment]
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.lang.Object.wait(Native Method)
	at java.lang.Thread.join(Thread.java:1245)
	at java.lang.Thread.join(Thread.java:1319)
	at com.hazelcast.replicatedmap.ReplicatedMapTtlTest.testPutWithTTL(ReplicatedMapTtlTest.java:60)
	at com.hazelcast.replicatedmap.ReplicatedMapTtlTest.testPutWithTTL_withMigration(ReplicatedMapTtlTest.java:29)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-sonar/1036/#showFailuresLink

**Comment by hasancelik** [comment]
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.lang.Object.wait(Native Method)
	at java.lang.Thread.join(Thread.java:1245)
	at java.lang.Thread.join(Thread.java:1319)
	at com.hazelcast.replicatedmap.ReplicatedMapTtlTest.testPutWithTTL(ReplicatedMapTtlTest.java:60)
	at com.hazelcast.replicatedmap.ReplicatedMapTtlTest.testPutWithTTL_withMigration(ReplicatedMapTtlTest.java:29)
```

https://hazelcast-l337.ci.cloudbees.com/view/Sonar/job/Hazelcast-3.x-sonar/com.hazelcast$hazelcast/1063/testReport/junit/com.hazelcast.replicatedmap/ReplicatedMapTtlTest/testPutWithTTL_withMigration/

https://hazelcast-l337.ci.cloudbees.com/view/Sonar/job/Hazelcast-3.x-sonar/com.hazelcast$hazelcast/1063/testReport/junit/com.hazelcast.replicatedmap/ReplicatedMapTtlTest/testPutWithTTL_withoutMigration/

**Comment by hasancelik** [comment]
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.lang.Object.wait(Native Method)
	at java.lang.Thread.join(Thread.java:1245)
	at java.lang.Thread.join(Thread.java:1319)
	at com.hazelcast.replicatedmap.ReplicatedMapTtlTest.testPutWithTTL(ReplicatedMapTtlTest.java:60)
	at com.hazelcast.replicatedmap.ReplicatedMapTtlTest.testPutWithTTL_withMigration(ReplicatedMapTtlTest.java:29)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-sonar/com.hazelcast$hazelcast/1075/testReport/junit/com.hazelcast.replicatedmap/ReplicatedMapTtlTest/testPutWithTTL_withMigration/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-sonar/1083/

**Comment by hasancelik** [comment]
**testPutWithTTL_withMigration**
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.lang.Object.wait(Native Method)
	at java.lang.Thread.join(Thread.java:1245)
	at java.lang.Thread.join(Thread.java:1319)
	at com.hazelcast.replicatedmap.ReplicatedMapTtlTest.testPutWithTTL(ReplicatedMapTtlTest.java:60)
	at com.hazelcast.replicatedmap.ReplicatedMapTtlTest.testPutWithTTL_withMigration(ReplicatedMapTtlTest.java:29)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-sonar/com.hazelcast$hazelcast/1091/testReport/junit/com.hazelcast.replicatedmap/ReplicatedMapTtlTest/testPutWithTTL_withMigration/

**Comment by hasancelik** [comment]
**testPutWithTTL_withoutMigration**
```
rg.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.lang.Object.wait(Native Method)
	at java.lang.Thread.join(Thread.java:1245)
	at java.lang.Thread.join(Thread.java:1319)
	at com.hazelcast.replicatedmap.ReplicatedMapTtlTest.testPutWithTTL(ReplicatedMapTtlTest.java:60)
	at com.hazelcast.replicatedmap.ReplicatedMapTtlTest.testPutWithTTL_withoutMigration(ReplicatedMapTtlTest.java:39)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-sonar/com.hazelcast$hazelcast/1092/testReport/junit/com.hazelcast.replicatedmap/ReplicatedMapTtlTest/testPutWithTTL_withoutMigration/

**Comment by metanet** [comment]
it seems that the test is running normally when it is timed out. Test is doing too many operations and replications. I decreased the operation & thread numbers in the test via https://github.com/hazelcast/hazelcast/commit/c83dfd3a1ebf933b4792a6efb6b40bad5496bb9c and closing this one for now. I will check if the test fails again.
