### ISSUE TITLE
MigrationCommitServiceTest.testPartitionOwnerShiftDownRollbackWithNullOwnerOfKeepReplicaIndex

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#7996]
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at org.junit.Assert.assertFalse(Assert.java:74)
	at com.hazelcast.internal.partition.impl.MigrationCommitServiceTest$5.run(MigrationCommitServiceTest.java:418)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:857)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:871)
	at com.hazelcast.internal.partition.impl.MigrationCommitServiceTest.clearReplicaIndex(MigrationCommitServiceTest.java:413)
	at com.hazelcast.internal.partition.impl.MigrationCommitServiceTest.testFailedShiftDownMigration(MigrationCommitServiceTest.java:255)
	at com.hazelcast.internal.partition.impl.MigrationCommitServiceTest.testPartitionOwnerShiftDownRollbackWithNullOwnerOfKeepReplicaIndex(MigrationCommitServiceTest.java:192)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-OracleJDK1.7/com.hazelcast$hazelcast/459/testReport/junit/com.hazelcast.internal.partition.impl/MigrationCommitServiceTest/testPartitionOwnerShiftDownRollbackWithNullOwnerOfKeepReplicaIndex/

**Comment by hasancelik** [comment]
```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:571)
	at java.util.ArrayList.get(ArrayList.java:349)
	at com.hazelcast.internal.partition.impl.MigrationCommitServiceTest.assertMigrationSourceCommit(MigrationCommitServiceTest.java:465)
	at com.hazelcast.internal.partition.impl.MigrationCommitServiceTest.testSuccessfulShiftDownMigration(MigrationCommitServiceTest.java:230)
	at com.hazelcast.internal.partition.impl.MigrationCommitServiceTest.testPartitionBackupShiftDownCommitWithOldOwnerOfKeepReplicaIndex(MigrationCommitServiceTest.java:199)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-ZuluJDK6/com.hazelcast$hazelcast/183/testReport/junit/com.hazelcast.internal.partition.impl/MigrationCommitServiceTest/testPartitionBackupShiftDownCommitWithOldOwnerOfKeepReplicaIndex/

**Comment by metanet** [comment]
Possible fix https://github.com/hazelcast/hazelcast/commit/7cdb88bd32909c88d5673758a383e0d35dfd39e6
