### ISSUE TITLE
BasicClusterStateTest.joinAllowed_whenKnownMemberReJoins_whenClusterState_isPassive

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#8001]
```
java.lang.AssertionError: Cluster size is not correct. Expected: 3 Actual: 1
	at org.junit.Assert.fail(Assert.java:88)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSize(HazelcastTestSupport.java:702)
	at com.hazelcast.test.HazelcastTestSupport$10.run(HazelcastTestSupport.java:721)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:857)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:717)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:712)
	at com.hazelcast.internal.cluster.impl.BasicClusterStateTest.joinAllowed_whenKnownMemberReJoins_whenClusterState_isPassive(BasicClusterStateTest.java:210)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast$hazelcast/887/testReport/junit/com.hazelcast.internal.cluster.impl/BasicClusterStateTest/joinAllowed_whenKnownMemberReJoins_whenClusterState_isPassive/

Output: 
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.7/887/artifact/hazelcast/target/surefire-reports/com.hazelcast.internal.cluster.impl.BasicClusterStateTest-output.txt

**Comment by mdogan** [comment]
Another mock joiner issue. see https://github.com/hazelcast/hazelcast/issues/7463
