### ISSUE TITLE
MigrationCommitServiceTest.testPartitionBackupMoveCopyBackCommitWithNullOwnerOfKeepReplicaIndex

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#8004]
```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:571)
	at java.util.ArrayList.get(ArrayList.java:349)
	at com.hazelcast.internal.partition.impl.MigrationCommitServiceTest.assertMigrationSourceCommit(MigrationCommitServiceTest.java:465)
	at com.hazelcast.internal.partition.impl.MigrationCommitServiceTest.testSuccessfulShiftDownMigration(MigrationCommitServiceTest.java:230)
	at com.hazelcast.internal.partition.impl.MigrationCommitServiceTest.testPartitionBackupMoveCopyBackCommitWithNullOwnerOfKeepReplicaIndex(MigrationCommitServiceTest.java:213)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-ZuluJDK6/com.hazelcast$hazelcast/183/testReport/junit/com.hazelcast.internal.partition.impl/MigrationCommitServiceTest/testPartitionBackupMoveCopyBackCommitWithNullOwnerOfKeepReplicaIndex/

**Comment by mdogan** [comment]
Should be fixed by https://github.com/hazelcast/hazelcast/commit/c2facddc6602133c7c239f4ddaf6f5159ad4dcc0
