### ISSUE TITLE
Invocation_NetworkSplitTest Failures

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#8026]
**testWaitNotifyService_whenNodeSplitFromCluster**

```
java.lang.AssertionError: expected:<4> but was:<3>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:834)
    at org.junit.Assert.assertEquals(Assert.java:645)
    at org.junit.Assert.assertEquals(Assert.java:631)
    at com.hazelcast.spi.impl.operationservice.impl.Invocation_NetworkSplitTest.testWaitNotifyService_whenNodeSplitFromCluster(Invocation_NetworkSplitTest.java:178)
    at com.hazelcast.spi.impl.operationservice.impl.Invocation_NetworkSplitTest.testWaitNotifyService_whenNodeSplitFromCluster(Invocation_NetworkSplitTest.java:125)
```

**testWaitNotifyService_whenNodePartiallySplitFromCluster**

```
java.lang.AssertionError: expected:<4> but was:<3>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:834)
    at org.junit.Assert.assertEquals(Assert.java:645)
    at org.junit.Assert.assertEquals(Assert.java:631)
    at com.hazelcast.spi.impl.operationservice.impl.Invocation_NetworkSplitTest.testWaitNotifyService_whenNodeSplitFromCluster(Invocation_NetworkSplitTest.java:177)
    at com.hazelcast.spi.impl.operationservice.impl.Invocation_NetworkSplitTest.testWaitNotifyService_whenNodePartiallySplitFromCluster(Invocation_NetworkSplitTest.java:131)
```

**testWaitingInvocations_whenNodePartiallySplitFromCluster_scenario2**

```
ava.lang.AssertionError: Cluster size is not correct. Expected: 3 Actual: 2
    at org.junit.Assert.fail(Assert.java:88)
    at com.hazelcast.test.HazelcastTestSupport.assertClusterSize(HazelcastTestSupport.java:702)
    at com.hazelcast.test.HazelcastTestSupport$10.run(HazelcastTestSupport.java:721)
    at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:857)
    at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:717)
    at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:712)
    at com.hazelcast.spi.impl.operationservice.impl.Invocation_NetworkSplitTest.testWaitingInvocations_whenNodeSplitFromCluster(Invocation_NetworkSplitTest.java:107)
    at com.hazelcast.spi.impl.operationservice.impl.Invocation_NetworkSplitTest.testWaitingInvocations_whenNodePartiallySplitFromCluster_scenario2(Invocation_NetworkSplitTest.java:74)
```

**testWaitingInvocations_whenNodePartiallySplitFromCluster_scenario1**

```
java.lang.AssertionError: Cluster size is not correct. Expected: 3 Actual: 2
    at org.junit.Assert.fail(Assert.java:88)
    at com.hazelcast.test.HazelcastTestSupport.assertClusterSize(HazelcastTestSupport.java:702)
    at com.hazelcast.test.HazelcastTestSupport$10.run(HazelcastTestSupport.java:721)
    at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:857)
    at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:717)
    at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:712)
    at com.hazelcast.spi.impl.operationservice.impl.Invocation_NetworkSplitTest.testWaitingInvocations_whenNodeSplitFromCluster(Invocation_NetworkSplitTest.java:107)
    at com.hazelcast.spi.impl.operationservice.impl.Invocation_NetworkSplitTest.testWaitingInvocations_whenNodePartiallySplitFromCluster_scenario1(Invocation_NetworkSplitTest.java:68)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-ZuluJDK7/com.hazelcast$hazelcast/186/testReport/junit/com.hazelcast.spi.impl.operationservice.impl/Invocation_NetworkSplitTest/testWaitNotifyService_whenNodeSplitFromCluster/

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-ZuluJDK8/185/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-OracleJDK8/787/

**Comment by hasancelik** [comment]
**testWaitingInvocations_whenNodePartiallySplitFromCluster_scenario1**
```
java.lang.AssertionError: Cluster size is not correct. Expected: 3 Actual: 2
	at org.junit.Assert.fail(Assert.java:88)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSize(HazelcastTestSupport.java:702)
	at com.hazelcast.test.HazelcastTestSupport$10.run(HazelcastTestSupport.java:721)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:857)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:717)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:712)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation_NetworkSplitTest.testWaitingInvocations_whenNodeSplitFromCluster(Invocation_NetworkSplitTest.java:107)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation_NetworkSplitTest.testWaitingInvocations_whenNodePartiallySplitFromCluster_scenario1(Invocation_NetworkSplitTest.java:68)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-sonar/com.hazelcast$hazelcast/1036/testReport/junit/com.hazelcast.spi.impl.operationservice.impl/Invocation_NetworkSplitTest/testWaitingInvocations_whenNodePartiallySplitFromCluster_scenario1/

**Comment by hasancelik** [comment]
suppressed by https://github.com/hazelcast/hazelcast/commit/a34e7c1fd68be446c4c33a701580eebf145e1687

**Comment by hasancelik** [comment]
**testWaitingInvocations_whenNodePartiallySplitFromCluster_scenario2**

```
java.lang.AssertionError: Cluster size is not correct. Expected: 3 Actual: 1
	at org.junit.Assert.fail(Assert.java:88)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSize(HazelcastTestSupport.java:702)
	at com.hazelcast.test.HazelcastTestSupport$10.run(HazelcastTestSupport.java:721)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:857)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:717)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:712)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation_NetworkSplitTest.testWaitingInvocations_whenNodeSplitFromCluster(Invocation_NetworkSplitTest.java:109)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation_NetworkSplitTest.testWaitingInvocations_whenNodePartiallySplitFromCluster_scenario2(Invocation_NetworkSplitTest.java:74)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x/com.hazelcast$hazelcast/4985/testReport/junit/com.hazelcast.spi.impl.operationservice.impl/Invocation_NetworkSplitTest/testWaitingInvocations_whenNodePartiallySplitFromCluster_scenario2/

**Comment by mdogan** [comment]
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
    at java.lang.Thread.sleep(Native Method)
    at com.hazelcast.test.mocknetwork.MockJoiner.doJoin(MockJoiner.java:67)
    at com.hazelcast.internal.cluster.impl.AbstractJoiner.join(AbstractJoiner.java:118)
    at com.hazelcast.instance.Node.join(Node.java:639)
    at com.hazelcast.internal.cluster.impl.ClusterMergeTask.rejoin(ClusterMergeTask.java:113)
    at com.hazelcast.internal.cluster.impl.ClusterMergeTask.run(ClusterMergeTask.java:65)
    at com.hazelcast.instance.LifecycleServiceImpl.runUnderLifecycleLock(LifecycleServiceImpl.java:107)
    at com.hazelcast.internal.cluster.impl.ClusterServiceImpl.merge(ClusterServiceImpl.java:302)
    at com.hazelcast.spi.impl.operationservice.impl.Invocation_NetworkSplitTest.testWaitingInvocations_whenNodeSplitFromCluster(Invocation_NetworkSplitTest.java:105)
    at com.hazelcast.spi.impl.operationservice.impl.Invocation_NetworkSplitTest.testWaitingInvocations_whenNodeSplitFromCluster(Invocation_NetworkSplitTest.java:62)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-ZuluJDK6/com.hazelcast$hazelcast/199/testReport/junit/com.hazelcast.spi.impl.operationservice.impl/Invocation_NetworkSplitTest/testWaitingInvocations_whenNodeSplitFromCluster/

**Comment by hasancelik** [comment]
**Invocation_NetworkSplitTest.testWaitingInvocations_whenNodeSplitFromCluster**
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.lang.Thread.sleep(Native Method)
	at java.util.concurrent.TimeUnit.sleep(TimeUnit.java:372)
	at com.hazelcast.test.HazelcastTestSupport.sleepMillis(HazelcastTestSupport.java:262)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:865)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:717)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:712)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation_NetworkSplitTest.testWaitingInvocations_whenNodeSplitFromCluster(Invocation_NetworkSplitTest.java:107)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation_NetworkSplitTest.testWaitingInvocations_whenNodeSplitFromCluster(Invocation_NetworkSplitTest.java:62)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast$hazelcast/917/testReport/junit/com.hazelcast.spi.impl.operationservice.impl/Invocation_NetworkSplitTest/testWaitingInvocations_whenNodeSplitFromCluster/

**Comment by hasancelik** [comment]
**testWaitingInvocations_whenNodeSplitFromCluster**
```
java.lang.AssertionError: Cluster size is not correct. Expected: 3 Actual: 2
	at org.junit.Assert.fail(Assert.java:88)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSize(HazelcastTestSupport.java:720)
	at com.hazelcast.test.HazelcastTestSupport$10.run(HazelcastTestSupport.java:739)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:875)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:735)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:730)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation_NetworkSplitTest.testWaitingInvocations_whenNodeSplitFromCluster(Invocation_NetworkSplitTest.java:107)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation_NetworkSplitTest.testWaitingInvocations_whenNodeSplitFromCluster(Invocation_NetworkSplitTest.java:62)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-OracleJDK1.6/com.hazelcast$hazelcast/927/testReport/junit/com.hazelcast.spi.impl.operationservice.impl/Invocation_NetworkSplitTest/testWaitingInvocations_whenNodeSplitFromCluster/

**Comment by mdogan** [comment]
We did many join & connection fixes and this test should have been fixed too (hopefully). 
Closing now, not failing for a long time.

**Comment by Donnerbart** [comment]
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.lang.Thread.sleep(Native Method)
	at com.hazelcast.test.mocknetwork.MockJoiner.doJoin(MockJoiner.java:69)
	at com.hazelcast.internal.cluster.impl.AbstractJoiner.join(AbstractJoiner.java:135)
	at com.hazelcast.instance.Node.join(Node.java:650)
	at com.hazelcast.internal.cluster.impl.ClusterMergeTask.rejoin(ClusterMergeTask.java:113)
	at com.hazelcast.internal.cluster.impl.ClusterMergeTask.run(ClusterMergeTask.java:65)
	at com.hazelcast.instance.LifecycleServiceImpl.runUnderLifecycleLock(LifecycleServiceImpl.java:107)
	at com.hazelcast.internal.cluster.impl.ClusterServiceImpl.merge(ClusterServiceImpl.java:320)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation_NetworkSplitTest.testWaitingInvocations_whenNodeSplitFromCluster(Invocation_NetworkSplitTest.java:104)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation_NetworkSplitTest.testWaitingInvocations_whenNodeSplitFromCluster(Invocation_NetworkSplitTest.java:61)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/4387/testReport/junit/com.hazelcast.spi.impl.operationservice.impl/Invocation_NetworkSplitTest/testWaitingInvocations_whenNodeSplitFromCluster/

**Comment by hasancelik** [comment]
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.lang.Thread.sleep(Native Method)
	at com.hazelcast.test.mocknetwork.MockJoiner.doJoin(MockJoiner.java:69)
	at com.hazelcast.internal.cluster.impl.AbstractJoiner.join(AbstractJoiner.java:135)
	at com.hazelcast.instance.Node.join(Node.java:650)
	at com.hazelcast.internal.cluster.impl.ClusterMergeTask.rejoin(ClusterMergeTask.java:113)
	at com.hazelcast.internal.cluster.impl.ClusterMergeTask.run(ClusterMergeTask.java:65)
	at com.hazelcast.instance.LifecycleServiceImpl.runUnderLifecycleLock(LifecycleServiceImpl.java:107)
	at com.hazelcast.internal.cluster.impl.ClusterServiceImpl.merge(ClusterServiceImpl.java:320)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation_NetworkSplitTest.testWaitingInvocations_whenNodeSplitFromCluster(Invocation_NetworkSplitTest.java:104)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation_NetworkSplitTest.testWaitingInvocations_whenNodeSplitFromCluster(Invocation_NetworkSplitTest.java:61)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK1.6/com.hazelcast$hazelcast/1040/testReport/junit/com.hazelcast.spi.impl.operationservice.impl/Invocation_NetworkSplitTest/testWaitingInvocations_whenNodeSplitFromCluster/

**Comment by hasancelik** [comment]
**maintenance**
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.lang.Thread.sleep(Native Method)
	at com.hazelcast.test.mocknetwork.MockJoiner.doJoin(MockJoiner.java:69)
	at com.hazelcast.internal.cluster.impl.AbstractJoiner.join(AbstractJoiner.java:135)
	at com.hazelcast.instance.Node.join(Node.java:650)
	at com.hazelcast.internal.cluster.impl.ClusterMergeTask.rejoin(ClusterMergeTask.java:113)
	at com.hazelcast.internal.cluster.impl.ClusterMergeTask.run(ClusterMergeTask.java:65)
	at com.hazelcast.instance.LifecycleServiceImpl.runUnderLifecycleLock(LifecycleServiceImpl.java:107)
	at com.hazelcast.internal.cluster.impl.ClusterServiceImpl.merge(ClusterServiceImpl.java:320)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation_NetworkSplitTest.testWaitingInvocations_whenNodeSplitFromCluster(Invocation_NetworkSplitTest.java:104)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation_NetworkSplitTest.testWaitingInvocations_whenNodeSplitFromCluster(Invocation_NetworkSplitTest.java:61)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-OracleJDK1.6/com.hazelcast$hazelcast/430/testReport/junit/com.hazelcast.spi.impl.operationservice.impl/Invocation_NetworkSplitTest/testWaitingInvocations_whenNodeSplitFromCluster/

**Comment by hasancelik** [comment]
**testWaitNotifyService_whenNodePartiallySplitFromCluster**
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.lang.Thread.sleep(Native Method)
	at com.hazelcast.test.mocknetwork.MockJoiner.doJoin(MockJoiner.java:65)
	at com.hazelcast.internal.cluster.impl.AbstractJoiner.join(AbstractJoiner.java:135)
	at com.hazelcast.instance.Node.join(Node.java:650)
	at com.hazelcast.internal.cluster.impl.ClusterMergeTask.rejoin(ClusterMergeTask.java:113)
	at com.hazelcast.internal.cluster.impl.ClusterMergeTask.run(ClusterMergeTask.java:65)
	at com.hazelcast.instance.LifecycleServiceImpl.runUnderLifecycleLock(LifecycleServiceImpl.java:107)
	at com.hazelcast.internal.cluster.impl.ClusterServiceImpl.merge(ClusterServiceImpl.java:320)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation_NetworkSplitTest.testWaitNotifyService_whenNodeSplitFromCluster(Invocation_NetworkSplitTest.java:174)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation_NetworkSplitTest.testWaitNotifyService_whenNodePartiallySplitFromCluster(Invocation_NetworkSplitTest.java:130)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK1.6/com.hazelcast$hazelcast/1056/testReport/junit/com.hazelcast.spi.impl.operationservice.impl/Invocation_NetworkSplitTest/testWaitNotifyService_whenNodePartiallySplitFromCluster/

**Comment by hasancelik** [comment]
**testWaitingInvocations_whenNodeSplitFromCluster**
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.lang.Thread.sleep(Native Method)
	at com.hazelcast.test.mocknetwork.MockJoiner.doJoin(MockJoiner.java:65)
	at com.hazelcast.internal.cluster.impl.AbstractJoiner.join(AbstractJoiner.java:135)
	at com.hazelcast.instance.Node.join(Node.java:650)
	at com.hazelcast.internal.cluster.impl.ClusterMergeTask.rejoin(ClusterMergeTask.java:113)
	at com.hazelcast.internal.cluster.impl.ClusterMergeTask.run(ClusterMergeTask.java:65)
	at com.hazelcast.instance.LifecycleServiceImpl.runUnderLifecycleLock(LifecycleServiceImpl.java:107)
	at com.hazelcast.internal.cluster.impl.ClusterServiceImpl.merge(ClusterServiceImpl.java:320)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation_NetworkSplitTest.testWaitingInvocations_whenNodeSplitFromCluster(Invocation_NetworkSplitTest.java:104)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation_NetworkSplitTest.testWaitingInvocations_whenNodeSplitFromCluster(Invocation_NetworkSplitTest.java:61)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-ZuluJDK7/com.hazelcast$hazelcast/362/testReport/junit/com.hazelcast.spi.impl.operationservice.impl/Invocation_NetworkSplitTest/testWaitingInvocations_whenNodeSplitFromCluster/

**Comment by hasancelik** [comment]
**testWaitingInvocations_whenNodeSplitFromCluster**
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.lang.Thread.sleep(Native Method)
	at com.hazelcast.test.mocknetwork.MockJoiner.doJoin(MockJoiner.java:69)
	at com.hazelcast.internal.cluster.impl.AbstractJoiner.join(AbstractJoiner.java:135)
	at com.hazelcast.instance.Node.join(Node.java:650)
	at com.hazelcast.internal.cluster.impl.ClusterMergeTask.rejoin(ClusterMergeTask.java:113)
	at com.hazelcast.internal.cluster.impl.ClusterMergeTask.run(ClusterMergeTask.java:65)
	at com.hazelcast.instance.LifecycleServiceImpl.runUnderLifecycleLock(LifecycleServiceImpl.java:107)
	at com.hazelcast.internal.cluster.impl.ClusterServiceImpl.merge(ClusterServiceImpl.java:320)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation_NetworkSplitTest.testWaitingInvocations_whenNodeSplitFromCluster(Invocation_NetworkSplitTest.java:104)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation_NetworkSplitTest.testWaitingInvocations_whenNodeSplitFromCluster(Invocation_NetworkSplitTest.java:61)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-ZuluJDK6/com.hazelcast$hazelcast/137/testReport/junit/com.hazelcast.spi.impl.operationservice.impl/Invocation_NetworkSplitTest/testWaitingInvocations_whenNodeSplitFromCluster/

**Comment by hasancelik** [comment]
**testWaitingInvocations_whenNodeSplitFromCluster**
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.lang.Thread.sleep(Native Method)
	at com.hazelcast.test.mocknetwork.MockJoiner.doJoin(MockJoiner.java:68)
	at com.hazelcast.internal.cluster.impl.AbstractJoiner.join(AbstractJoiner.java:135)
	at com.hazelcast.instance.Node.join(Node.java:654)
	at com.hazelcast.internal.cluster.impl.ClusterMergeTask.rejoin(ClusterMergeTask.java:113)
	at com.hazelcast.internal.cluster.impl.ClusterMergeTask.run(ClusterMergeTask.java:65)
	at com.hazelcast.instance.LifecycleServiceImpl.runUnderLifecycleLock(LifecycleServiceImpl.java:107)
	at com.hazelcast.internal.cluster.impl.ClusterServiceImpl.merge(ClusterServiceImpl.java:324)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation_NetworkSplitTest.testWaitingInvocations_whenNodeSplitFromCluster(Invocation_NetworkSplitTest.java:104)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation_NetworkSplitTest.testWaitingInvocations_whenNodeSplitFromCluster(Invocation_NetworkSplitTest.java:61)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance/com.hazelcast$hazelcast/1558/testReport/junit/com.hazelcast.spi.impl.operationservice.impl/Invocation_NetworkSplitTest/testWaitingInvocations_whenNodeSplitFromCluster/

**Comment by mdogan** [comment]
Fails on maintenance branch. We had many mock joiner fixes on master but none is backported to maintenance. Marked issue as 3.8.

**Comment by ahmetmircik** [comment]
```
com.hazelcast.spi.impl.operationservice.impl.Invocation_NetworkSplitTest.testWaitNotifyService_whenNodePartiallySplitFromCluster
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/14301/testReport/junit/com.hazelcast.spi.impl.operationservice.impl/Invocation_NetworkSplitTest/testWaitNotifyService_whenNodePartiallySplitFromCluster/
