### ISSUE TITLE
RingbufferMigrationTest.test

### ISSUE THREAD

**Issue by Donnerbart** [hazelcast/hazelcast#8038]
**Error Message**

```
expected:<0> but was:<864>
```

**Stacktrace**

```
java.lang.AssertionError: expected:<0> but was:<864>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:834)
    at org.junit.Assert.assertEquals(Assert.java:645)
    at org.junit.Assert.assertEquals(Assert.java:631)
    at com.hazelcast.ringbuffer.impl.RingbufferMigrationTest.test(RingbufferMigrationTest.java:46)
```

https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/2792/testReport/junit/com.hazelcast.ringbuffer.impl/RingbufferMigrationTest/test/

**Comment by gurbuzali** [comment]
I've tried to reproduce this on my local but couldn't. I think it is safe to assume all those enhancements/fixes related with node shutdown and migration may fixed this issue too.

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: expected:<0> but was:<1000>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.ringbuffer.impl.RingbufferMigrationTest.test(RingbufferMigrationTest.java:46)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast$hazelcast/1010/testReport/junit/com.hazelcast.ringbuffer.impl/RingbufferMigrationTest/test/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: expected:<0> but was:<1000>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.ringbuffer.impl.RingbufferMigrationTest.test(RingbufferMigrationTest.java:46)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-ZuluJDK8/com.hazelcast$hazelcast/360/testReport/junit/com.hazelcast.ringbuffer.impl/RingbufferMigrationTest/test/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: expected:<0> but was:<1000>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK1.7/com.hazelcast$hazelcast/648/testReport/junit/com.hazelcast.ringbuffer.impl/RingbufferMigrationTest/test/

**Comment by mmedenjak** [comment]
The head sequence is moved from 0 to 1000 or 864 while the tail sequence remains 999. This matches the theory that the items were expired between being added and the assertion. The expiration is 30seconds. Is it possible that the test is suspended long enough for the items to expire? We can disable TTL for this test in the case this is agreed upon. @pveentjer WDYT?
