### ISSUE TITLE
MapStoreDataLoadingContinuesWhenNodeJoins.testNoDeadLockDuringJoin & testDataLoadedCorrectly

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#8039]
**testNoDeadLockDuringJoin**
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.lang.Object.wait(Native Method)
	at java.lang.Thread.join(Thread.java:1245)
	at java.lang.Thread.join(Thread.java:1319)
	at com.hazelcast.map.impl.mapstore.MapStoreDataLoadingContinuesWhenNodeJoins.testNoDeadLockDuringJoin(MapStoreDataLoadingContinuesWhenNodeJoins.java:159)
```

**testDataLoadedCorrectly**
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.lang.Object.wait(Native Method)
	at java.lang.Thread.join(Thread.java:1245)
	at java.lang.Thread.join(Thread.java:1319)
	at com.hazelcast.map.impl.mapstore.MapStoreDataLoadingContinuesWhenNodeJoins.testDataLoadedCorrectly(MapStoreDataLoadingContinuesWhenNodeJoins.java:258)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-sonar/1035/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-sonar/1036/#showFailuresLink

**Comment by hasancelik** [comment]
fixed by https://github.com/hazelcast/hazelcast/commit/fc11f8334b7bf4ef80116f41fb142d7b7f9c967c
