### ISSUE TITLE
MapEvictionPolicyTest.testMapEvictionPolicy

### ISSUE THREAD

**Issue by Donnerbart** [hazelcast/hazelcast#8049]
**Error Message**
Key cannot be an odd number :18

**Stacktrace**
```
junit.framework.AssertionFailedError: Key cannot be an odd number :18
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.assertTrue(Assert.java:22)
	at junit.framework.TestCase.assertTrue(TestCase.java:192)
	at com.hazelcast.map.impl.eviction.MapEvictionPolicyTest.testMapEvictionPolicy(MapEvictionPolicyTest.java:59)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/2822/testReport/junit/com.hazelcast.map.impl.eviction/MapEvictionPolicyTest/testMapEvictionPolicy/

**Comment by ahmetmircik** [comment]
closed via https://github.com/hazelcast/hazelcast/commit/432967b9e6e64ca5413fe71e0c88a6d29015b24d
