### ISSUE TITLE
ClusterInfoTest.all_nodes_should_have_the_same_cluster_start_time_and_cluster_id

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#8097]
```
java.lang.AssertionError: expected:<1462416052225> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.cluster.ClusterInfoTest.all_nodes_should_have_the_same_cluster_start_time_and_cluster_id(ClusterInfoTest.java:72)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-OracleJDK1.6/com.hazelcast$hazelcast/899/testReport/junit/com.hazelcast.cluster/ClusterInfoTest/all_nodes_should_have_the_same_cluster_start_time_and_cluster_id/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: expected:<1462979987682> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.cluster.ClusterInfoTest.all_nodes_should_have_the_same_cluster_start_time_and_cluster_id(ClusterInfoTest.java:71)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x/com.hazelcast$hazelcast/5064/testReport/junit/com.hazelcast.cluster/ClusterInfoTest/all_nodes_should_have_the_same_cluster_start_time_and_cluster_id/
