### ISSUE TITLE
NPE when using Hazelcast Spring Integration with MapStore implementation

### ISSUE THREAD

**Issue by dgabm** [hazelcast/hazelcast#8120]
Hi team,

I'm new to Hazelcast, and I used Spring/jdbcTemplates for some projects.
Now I'm trying hazelcast MapStore implementation for postgresql with jdk1.8.0_31 on ubuntu Ubuntu 12.04.4 LTS x86_64
[hazelcast.xml.txt](https://github.com/hazelcast/hazelcast/files/252591/hazelcast.xml.txt)

.
my classpath:
hazelcast-client-3.2.6.jar:postgresql-9.4.1208.jre6.jar:spring-expression-3.2.11.RELEASE.jar:commons-logging-1.1.1.jar:spring-context-3.2.11.RELEASE.jar:spring-beans-3.2.11.RELEASE.jar:spring-core-3.2.11.RELEASE.jar:spring-tx-3.2.11.RELEASE.jar:hazelcast-spring-3.2.1.jar:spring-jdbc-3.2.11.RELEASE.jar:log4j-1.2.17.jar:hazelcast-3.2.6.jar:

Here is my configuration.xml:

`<?xml version="1.0" encoding="UTF-8"?>`
`<beans xmlns="http://www.springframework.org/schema/beans"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:context="http://www.springframework.org/schema/context"
 xmlns:camel="http://camel.apache.org/schema/spring" xmlns:p="http://www.springframework.org/schema/p"
 xmlns:hz="http://www.hazelcast.com/schema/spring"
 xsi:schemaLocation="
       http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd
       http://www.springframework.org/schema/context http://www.springframework.org/schema/context/spring-context.xsd
       http://camel.apache.org/schema/spring http://camel.apache.org/schema/spring/camel-spring.xsd
       http://www.hazelcast.com/schema/spring http://www.hazelcast.com/schema/spring/hazelcast-spring-3.2.xsd"
    profile="!test">`
`<context:component-scan base-package=com.myexample.hz />`
`<context:annotation-config />`
  `<bean id="postgresMapStore" class="com.myexample.PostgresMapStore">`
  `<property name="jdbcTemplate" ref="jdbcTemplate" />`
 `</bean>` 
 `<bean id="jdbcTemplate" class="org.springframework.jdbc.core.JdbcTemplate">`
  `<property name="dataSource" ref="dataSource"/>`
 `</bean>
 <hz:hazelcast id="instance">
     <hz:config>
       <hz:group name="test" password="test"/>
       <hz:network port="5701" port-auto-increment="false">
         <hz:join>
           <hz:multicast enabled="true" multicast-group="224.2.2.3" multicast-port="54327"/>
           <hz:tcp-ip enabled="false">
             <hz:members>127.0.0.1</hz:members>
           </hz:tcp-ip>
         </hz:join>
         <hz:interfaces enabled="false">
             <hz:interface>10.10.1.*</hz:interface>
   </hz:interfaces>        
       </hz:network>
        <hz:map name="postgresMap" >
      <hz:map-store enabled="true"  class-name="com.myexample.PostgresMapStore" write-delay-seconds="0"/>
      </hz:map>
     </hz:config>
   </hz:hazelcast>`

 `<bean name="dataSource" class="org.springframework.jdbc.datasource.DriverManagerDataSource">
   <property name="driverClassName" value="${db.driverClassName}" />
   <property name="url" value="${db.url}" />
   <property name="username" value="${db.username}" />
   <property name="password" value="${db.password}" />
  </bean>
 <context:property-placeholder location="classpath:hazel-server.properties" />
</beans>`

com.myexample.PostgresMapStore is slightly the one from [(http://vajjala-javapassion.blogspot.fr/2014/05/hazelcast-persistence-with-mysql.html)]

The jdbcTemplate is autowired properly in the main Thread that starts ClassPathXmlApplicationContext("configuration.xml") 
but just after somehow when  com.hazelcast.util.executor.HazelcastManagedThread is started the jdbcTemplate is null in com.myexample.PostgresMapStore in null triggering a NPE.

Log4j trace:

May 06, 2016 5:02:11 PM com.hazelcast.config.XmlConfigBuilder
INFO: Using configuration file at /applis/hazelcast-3.2.6/bin/hazelcast.xml
2016-05-06 17:02:16 INFO  org.springframework.context.support.ClassPathXmlApplicationContext     - Refreshing org.springframework.context.support.ClassPathXmlApplicationContext@69379752: startup date [Fri May 06 17:02:16 CEST 2016]; root of context hierarchy
2016-05-06 17:02:16 INFO  org.springframework.beans.factory.xml.XmlBeanDefinitionReader     - Loading XML bean definitions from class path resource [spring-config.xml]
2016-05-06 17:02:16 INFO  org.springframework.beans.factory.support.DefaultListableBeanFactory     - Overriding bean definition for bean 'postgresMapStore': replacing [Generic bean: class [com.myexamplePostgresMapStore]; scope=singleton; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null; defined in URL [jar:file:/applis/hazelcast-3.2.6/lib/myexample-SNAPSHOT.jar!/com/myexample/PostgresMapStore.class]] with [Generic bean: class [com.myexamplePostgresMapStore]; scope=; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null; defined in class path resource [spring-config.xml]]
2016-05-06 17:02:17 INFO  org.springframework.context.support.PropertySourcesPlaceholderConfigurer     - Loading properties file from class path resource [hazel-server.properties]
2016-05-06 17:02:17 INFO  org.springframework.beans.factory.support.DefaultListableBeanFactory     - Pre-instantiating singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@27ff5d15: defining beans [postgresMapStore,org.springframework.context.annotation.internalConfigurationAnnotationProcessor,org.springframework.context.annotation.internalAutowiredAnnotationProcessor,org.springframework.context.annotation.internalRequiredAnnotationProcessor,org.springframework.context.annotation.internalCommonAnnotationProcessor,jdbcTemplate,instance,dataSource,org.springframework.context.support.PropertySourcesPlaceholderConfigurer#0,org.springframework.context.annotation.ConfigurationClassPostProcessor.importAwareProcessor]; root of factory hierarchy
2016-05-06 17:02:17 INFO  org.springframework.jdbc.datasource.DriverManagerDataSource     - Loaded JDBC driver: org.postgresql.Driver //**At this point I can see in debug mod the jdbcTemplate properly injected in setter method**
May 06, 2016 5:02:28 PM com.hazelcast.instance.DefaultAddressPicker
INFO: [LOCAL] [orc2] [3.2.6] Prefer IPv4 stack is true.
May 06, 2016 5:02:28 PM com.hazelcast.instance.DefaultAddressPicker
INFO: [LOCAL] [orc2] [3.2.6] Picked Address[10.40.31.31]:5701, using socket ServerSocket[addr=/0.0.0.0,localport=5701], bind any local is true
May 06, 2016 5:02:29 PM com.hazelcast.system
INFO: [10.40.31.31]:5701 [orc2] [3.2.6] Hazelcast 3.2.6 (20140907) starting at Address[10.40.31.31]:5701
May 06, 2016 5:02:29 PM com.hazelcast.system
INFO: [10.40.31.31]:5701 [orc2] [3.2.6] Copyright (C) 2008-2014 Hazelcast.com
May 06, 2016 5:02:29 PM com.hazelcast.instance.Node
INFO: [10.40.31.31]:5701 [orc2] [3.2.6] Creating MulticastJoiner
May 06, 2016 5:02:29 PM com.hazelcast.core.LifecycleService
INFO: [10.40.31.31]:5701 [orc2] [3.2.6] Address[10.40.31.31]:5701 is STARTING
May 06, 2016 5:02:29 PM com.hazelcast.nio.SocketConnector
INFO: [10.40.31.31]:5701 [orc2] [3.2.6] Connecting to /10.40.31.99:5701, timeout: 0, bind-any: true
May 06, 2016 5:02:29 PM com.hazelcast.nio.TcpIpConnectionManager
INFO: [10.40.31.31]:5701 [orc2] [3.2.6] Established socket connection between /10.40.31.31:57334 and /10.40.31.99:5701
May 06, 2016 5:02:35 PM com.hazelcast.cluster.ClusterService
INFO: [10.40.31.31]:5701 [orc2] [3.2.6]

Members [2] {
        Member [10.40.31.99]:5701
        Member [10.40.31.31]:5701 this
}

May 06, 2016 5:02:36 PM com.hazelcast.core.LifecycleService
INFO: [10.40.31.31]:5701 [orc2] [3.2.6] Address[10.40.31.31]:5701 is STARTED
1
May 06, 2016 5:02:36 PM com.hazelcast.instance.DefaultAddressPicker
INFO: [LOCAL] [orc2] [3.2.6] Prefer IPv4 stack is true.
May 06, 2016 5:02:36 PM com.hazelcast.instance.DefaultAddressPicker
INFO: [LOCAL] [orc2] [3.2.6] Picked Address[10.40.31.31]:5703, using socket ServerSocket[addr=/0.0.0.0,localport=5703], bind any local is true
May 06, 2016 5:02:36 PM com.hazelcast.system
INFO: [10.40.31.31]:5703 [orc2] [3.2.6] Hazelcast 3.2.6 (20140907) starting at Address[10.40.31.31]:5703
May 06, 2016 5:02:36 PM com.hazelcast.system
INFO: [10.40.31.31]:5703 [orc2] [3.2.6] Copyright (C) 2008-2014 Hazelcast.com
May 06, 2016 5:02:36 PM com.hazelcast.instance.Node
INFO: [10.40.31.31]:5703 [orc2] [3.2.6] Creating MulticastJoiner
May 06, 2016 5:02:36 PM com.hazelcast.core.LifecycleService
INFO: [10.40.31.31]:5703 [orc2] [3.2.6] Address[10.40.31.31]:5703 is STARTING
May 06, 2016 5:02:36 PM com.hazelcast.nio.SocketConnector

WARNING: [10.40.31.31]:5701 [orc2] [3.2.6] Cannot create proxy [hz:impl:mapService:postgresMap]!
java.lang.NullPointerException
        at com.myexample.PostgresMapStore.loadAllKeys(PostgresMapStore.java:107)
        at com.hazelcast.map.MapStoreWrapper.loadAllKeys(MapStoreWrapper.java:115)
        at com.hazelcast.map.MapContainer.loadInitialKeys(MapContainer.java:185)
        at com.hazelcast.map.MapContainer.<init>(MapContainer.java:127)
        at com.hazelcast.map.MapService$3.createNew(MapService.java:189)
        at com.hazelcast.map.MapService$3.createNew(MapService.java:187)
        at com.hazelcast.util.ConcurrencyUtil.getOrPutSynchronized(ConcurrencyUtil.java:39)
        at com.hazelcast.map.MapService.getMapContainer(MapService.java:314)
        at com.hazelcast.map.proxy.MapProxySupport.<init>(MapProxySupport.java:67)
        at com.hazelcast.map.proxy.MapProxyImpl.<init>(MapProxyImpl.java:43)
        at com.hazelcast.map.MapService.createDistributedObject(MapService.java:557)
        at com.hazelcast.map.MapService.createDistributedObject(MapService.java:70)
        at com.hazelcast.spi.impl.ProxyServiceImpl$ProxyRegistry.createProxy(ProxyServiceImpl.java:304)
        at com.hazelcast.spi.impl.ProxyServiceImpl$PostJoinProxyOperation.run(ProxyServiceImpl.java:536)
        at com.hazelcast.spi.impl.BasicOperationService.processOperation(BasicOperationService.java:363)
        at com.hazelcast.spi.impl.BasicOperationService.runOperation(BasicOperationService.java:228)
        at com.hazelcast.cluster.PostJoinOperation.run(PostJoinOperation.java:69)
        at com.hazelcast.spi.impl.BasicOperationService.processOperation(BasicOperationService.java:363)
        at com.hazelcast.spi.impl.BasicOperationService.runOperation(BasicOperationService.java:228)
        at com.hazelcast.cluster.FinalizeJoinOperation.run(FinalizeJoinOperation.java:78)
        at com.hazelcast.spi.impl.BasicOperationService.processOperation(BasicOperationService.java:363)
        at com.hazelcast.spi.impl.BasicOperationService.processPacket(BasicOperationService.java:309)
        at com.hazelcast.spi.impl.BasicOperationService.access$400(BasicOperationService.java:102)
        at com.hazelcast.spi.impl.BasicOperationService$BasicOperationProcessorImpl.process(BasicOperationService.java:770)
        at com.hazelcast.spi.impl.BasicOperationScheduler$ProcessTask.run(BasicOperationScheduler.java:195)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
        at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
        at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)

INFO: [10.40.31.31]:5703 [orc2] [3.2.6] Connecting to /10.40.31.99:5701, timeout: 0, bind-any: true
May 06, 2016 5:02:36 PM com.hazelcast.nio.TcpIpConnectionManager
INFO: [10.40.31.31]:5703 [orc2] [3.2.6] Established socket connection between /10.40.31.31:57976 and /10.40.31.99:5701

Thanks in advance for the help!

**Comment by dgabm** [comment]
com.myexample.PostgresMapStore
[PostgresMapStore.java.txt](https://github.com/hazelcast/hazelcast/files/252595/PostgresMapStore.java.txt)

**Comment by dgabm** [comment]
I found the solution:
@SpringAware
@Component
public class PostgresMapStore implements MapStore<String, Object>, MapLoaderLifecycleSupport {


...
	@Override
	public void init(HazelcastInstance hazelcastInstance, Properties properties, String mapName) {
		hazelcastInstance.getConfig().getManagedContext().initialize(this);
		// TODO Auto-generated method stub
		
	}

**Comment by mesutcelik** [comment]
Thanks @dgabm
