### ISSUE TITLE
RawProtocolAuthenticationTest.testAuthenticateWithUsernameAndPassword_with_Invalid_MessageSize

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#8131]
```
java.lang.AssertionError: Expected exception: java.io.EOFException
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:32)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:88)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:82)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.lang.Thread.run(Thread.java:785)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-IbmJDK1.8/com.hazelcast$hazelcast/75/testReport/junit/com.hazelcast.client.protocol/RawProtocolAuthenticationTest/testAuthenticateWithUsernameAndPassword_with_Invalid_MessageSize/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: Expected exception: java.io.EOFException
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:32)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:88)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:82)
	at java.util.concurrent.FutureTask.run(FutureTask.java:274)
	at java.lang.Thread.run(Thread.java:809)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast$hazelcast/942/testReport/junit/com.hazelcast.client.protocol/RawProtocolAuthenticationTest/testAuthenticateWithUsernameAndPassword_with_Invalid_MessageSize/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: Expected exception: java.io.EOFException
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:32)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:88)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:82)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.lang.Thread.run(Thread.java:785)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.8/com.hazelcast$hazelcast/256/testReport/junit/com.hazelcast.client.protocol/RawProtocolAuthenticationTest/testAuthenticateWithUsernameAndPassword_with_Invalid_MessageSize/
