### ISSUE TITLE
SplitBrainHandlerTest failures

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#8137]
```
java.lang.AssertionError: CountDownLatch failed to complete within 120 seconds , count left: 1
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:758)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:751)
	at com.hazelcast.cluster.SplitBrainHandlerTest.testClusterMerge_ignoresLiteMembers(SplitBrainHandlerTest.java:577)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.maintenance-nightly/com.hazelcast$hazelcast/849/testReport/junit/com.hazelcast.cluster/SplitBrainHandlerTest/testClusterMerge_ignoresLiteMembers/

**Comment by hasancelik** [comment]
**testMulticast_ClusterMerge_when_split_not_detected_by_master
testClusterMerge_ignoresLiteMembers
testClusterMerge_when_split_not_detected_by_slave_and_restart_during_merge
testClusterMerge_when_split_not_detected_by_slave**
```
java.lang.AssertionError: CountDownLatch failed to complete within 120 seconds , count left: 3
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:764)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:757)
	at com.hazelcast.cluster.SplitBrainHandlerTest.testClusterMerge_ignoresLiteMembers(SplitBrainHandlerTest.java:575)
```

**testTcpIp_ClusterMerge_when_split_not_detected_by_master**
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.cluster.SplitBrainHandlerTest.testClusterMerge_when_split_not_detected_by_master(SplitBrainHandlerTest.java:503)
	at com.hazelcast.cluster.SplitBrainHandlerTest.testMulticast_ClusterMerge_when_split_not_detected_by_master(SplitBrainHandlerTest.java:432)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-nightly/953/#showFailuresLink

**Comment by hasancelik** [comment]
**testClusterMerge_when_split_not_detected_by_slave_and_restart_during_merge**
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.cluster.SplitBrainHandlerTest.testClusterMerge_when_split_not_detected_by_slave_and_restart_during_merge(SplitBrainHandlerTest.java:839)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/963/testReport/junit/com.hazelcast.cluster/SplitBrainHandlerTest/testClusterMerge_when_split_not_detected_by_slave_and_restart_during_merge/

**Comment by hasancelik** [comment]
**testClusterMerge_when_split_not_detected_by_slave**

```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.cluster.SplitBrainHandlerTest.testClusterMerge_when_split_not_detected_by_slave(SplitBrainHandlerTest.java:751)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/964/testReport/junit/com.hazelcast.cluster/SplitBrainHandlerTest/testClusterMerge_when_split_not_detected_by_slave/

**Comment by hasancelik** [comment]
**testClusterMerge_when_split_not_detected_by_slave_and_restart_during_merge**

```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.cluster.SplitBrainHandlerTest.testClusterMerge_when_split_not_detected_by_slave_and_restart_during_merge(SplitBrainHandlerTest.java:839)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-nightly/

**Comment by hasancelik** [comment]
**testTcpIp_ClusterMerge_when_split_not_detected_by_master**
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.cluster.SplitBrainHandlerTest.testClusterMerge_when_split_not_detected_by_master(SplitBrainHandlerTest.java:503)
	at com.hazelcast.cluster.SplitBrainHandlerTest.testTcpIp_ClusterMerge_when_split_not_detected_by_master(SplitBrainHandlerTest.java:437)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/968/testReport/junit/com.hazelcast.cluster/SplitBrainHandlerTest/testTcpIp_ClusterMerge_when_split_not_detected_by_master/

**Comment by hasancelik** [comment]
**testClusterMerge_when_split_not_detected_by_slave_and_restart_during_merge**
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.cluster.SplitBrainHandlerTest.testClusterMerge_when_split_not_detected_by_slave_and_restart_during_merge(SplitBrainHandlerTest.java:839)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/970/testReport/junit/com.hazelcast.cluster/SplitBrainHandlerTest/testClusterMerge_when_split_not_detected_by_slave_and_restart_during_merge/

**Comment by hasancelik** [comment]
**testClusterMerge_when_split_not_detected_by_slave**

```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.cluster.SplitBrainHandlerTest.testClusterMerge_when_split_not_detected_by_slave(SplitBrainHandlerTest.java:751)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/971/testReport/junit/com.hazelcast.cluster/SplitBrainHandlerTest/testClusterMerge_when_split_not_detected_by_slave/

**Comment by hasancelik** [comment]
**testClusterMerge_when_split_not_detected_by_slave_and_restart_during_merge**
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.cluster.SplitBrainHandlerTest.testClusterMerge_when_split_not_detected_by_slave_and_restart_during_merge(SplitBrainHandlerTest.java:839)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/972/testReport/junit/com.hazelcast.cluster/SplitBrainHandlerTest/testClusterMerge_when_split_not_detected_by_slave_and_restart_during_merge/

**Comment by hasancelik** [comment]
**testTcpIp_ClusterMerge_when_split_not_detected_by_master**
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.cluster.SplitBrainHandlerTest.testClusterMerge_when_split_not_detected_by_master(SplitBrainHandlerTest.java:503)
	at com.hazelcast.cluster.SplitBrainHandlerTest.testTcpIp_ClusterMerge_when_split_not_detected_by_master(SplitBrainHandlerTest.java:437)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/976/testReport/junit/com.hazelcast.cluster/SplitBrainHandlerTest/testTcpIp_ClusterMerge_when_split_not_detected_by_master/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.cluster.SplitBrainHandlerTest.testClusterMerge_when_split_not_detected_by_slave(SplitBrainHandlerTest.java:751)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/979/testReport/junit/com.hazelcast.cluster/SplitBrainHandlerTest/testClusterMerge_when_split_not_detected_by_slave/

**Comment by hasancelik** [comment]
**testMulticast_ClusterMerge_when_split_not_detected_by_master**
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.cluster.SplitBrainHandlerTest.testClusterMerge_when_split_not_detected_by_master(SplitBrainHandlerTest.java:503)
	at com.hazelcast.cluster.SplitBrainHandlerTest.testMulticast_ClusterMerge_when_split_not_detected_by_master(SplitBrainHandlerTest.java:432)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/982/testReport/junit/com.hazelcast.cluster/SplitBrainHandlerTest/testMulticast_ClusterMerge_when_split_not_detected_by_master/
