### ISSUE TITLE
No such accessible method: HazelCast

### ISSUE THREAD

**Issue by vinodhvp** [hazelcast/hazelcast#8150]
Hi,

When I access the hazelcast (3.2.3) main page(http://localhost:8080/hazelcast-mancenter/main.jsp),I am getting the following error.Please help.

com.hazelcast.webmonitor.service.DataService
SEVERE: No such accessible method: getUnsafeMembers() on object: com.hazelcast.webmonitor.service.DataService
java.lang.NoSuchMethodException: No such accessible method: getUnsafeMembers() on object: com.hazelcast.webmonitor.service.DataService
	at org.apache.commons.beanutils.MethodUtils.invokeMethod(MethodUtils.java:279)
	at org.apache.commons.beanutils.MethodUtils.invokeMethod(MethodUtils.java:226)
	at org.apache.commons.beanutils.MethodUtils.invokeMethod(MethodUtils.java:177)
	at com.hazelcast.webmonitor.service.DataService.invokeMethod(DataService.java:131)
	at com.hazelcast.webmonitor.service.DataService.getResponse(DataService.java:109)
	at com.hazelcast.webmonitor.servlet.MainServlet.doGet(MainServlet.java:80)

**Comment by mesutcelik** [comment]
what version of management center you are using?
Is there any particular reason that you don't use the latest stable version 3.6.2 of hazelcast and management center?

**Comment by mesutcelik** [comment]
I am closing this issue now. please reopen if you have more info.
