### ISSUE TITLE
WriteBehindStoreAllUpdatesTest.testAllUpdatesReflectedToMapStore

### ISSUE THREAD

**Issue by mdogan** [hazelcast/hazelcast#8168]
```
java.lang.AssertionError: expected:<1000> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.map.impl.mapstore.writebehind.WriteBehindStoreAllUpdatesTest$1.run(WriteBehindStoreAllUpdatesTest.java:67)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:857)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:871)
	at com.hazelcast.map.impl.mapstore.writebehind.WriteBehindStoreAllUpdatesTest.testAllUpdatesReflectedToMapStore(WriteBehindStoreAllUpdatesTest.java:61)
```

https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/3178/testReport/junit/com.hazelcast.map.impl.mapstore.writebehind/WriteBehindStoreAllUpdatesTest/testAllUpdatesReflectedToMapStore/

**Comment by ahmetmircik** [comment]
not failed recently
