### ISSUE TITLE
ExtractionInCollectionSpecTest aborted due to OutOfMemoryError

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#8184]
```
04:52:24 Running com.hazelcast.query.impl.extractor.specification.ExtractionInCollectionSpecTest
04:59:11 JVMDUMP039I Processing dump event "systhrow", detail "java/lang/OutOfMemoryError" at 2016/05/16 04:59:11 - please wait.
04:59:11 JVMDUMP032I JVM requested System dump using '/scratch/jenkins/workspace/Hazelcast-3.x-IbmJDK1.7/core.20160516.045911.292.0001.dmp' in response to an event
04:59:15 JVMPORT030W /proc/sys/kernel/core_pattern setting "|/usr/share/apport/apport %p %s %c %P" specifies that the core dump is to be piped to an external program.  Attempting to rename either core or core.21898.
04:59:15 
04:59:21 JVMDUMP012E Error in System dump: The core file created by child process with pid = 21898 was not found. Expected to find core file with name "/scratch/jenkins/workspace/Hazelcast-3.x-IbmJDK1.7/core"
04:59:21 JVMDUMP032I JVM requested Heap dump using '/scratch/jenkins/workspace/Hazelcast-3.x-IbmJDK1.7/heapdump.20160516.045911.292.0002.phd' in response to an event
04:59:25 JVMDUMP010I Heap dump written to /scratch/jenkins/workspace/Hazelcast-3.x-IbmJDK1.7/heapdump.20160516.045911.292.0002.phd
04:59:25 JVMDUMP032I JVM requested Java dump using '/scratch/jenkins/workspace/Hazelcast-3.x-IbmJDK1.7/javacore.20160516.045911.292.0003.txt' in response to an event
04:59:25 JVMDUMP010I Java dump written to /scratch/jenkins/workspace/Hazelcast-3.x-IbmJDK1.7/javacore.20160516.045911.292.0003.txt
04:59:25 JVMDUMP039I Processing dump event "systhrow", detail "java/lang/OutOfMemoryError" at 2016/05/16 04:59:25 - please wait.
04:59:25 JVMDUMP032I JVM requested Snap dump using '/scratch/jenkins/workspace/Hazelcast-3.x-IbmJDK1.7/Snap.20160516.045911.292.0005.trc' in response to an event
04:59:25 JVMDUMP010I Snap dump written to /scratch/jenkins/workspace/Hazelcast-3.x-IbmJDK1.7/Snap.20160516.045911.292.0005.trc
04:59:25 JVMDUMP013I Processed dump event "systhrow", detail "java/lang/OutOfMemoryError".
04:59:25 JVMDUMP032I JVM requested Heap dump using '/scratch/jenkins/workspace/Hazelcast-3.x-IbmJDK1.7/heapdump.20160516.045925.292.0004.phd' in response to an event
04:59:29 JVMDUMP010I Heap dump written to /scratch/jenkins/workspace/Hazelcast-3.x-IbmJDK1.7/heapdump.20160516.045925.292.0004.phd
04:59:29 JVMDUMP032I JVM requested Java dump using '/scratch/jenkins/workspace/Hazelcast-3.x-IbmJDK1.7/javacore.20160516.045925.292.0006.txt' in response to an event
04:59:29 JVMDUMP010I Java dump written to /scratch/jenkins/workspace/Hazelcast-3.x-IbmJDK1.7/javacore.20160516.045925.292.0006.txt
04:59:29 JVMDUMP032I JVM requested Snap dump using '/scratch/jenkins/workspace/Hazelcast-3.x-IbmJDK1.7/Snap.20160516.045925.292.0007.trc' in response to an event
04:59:29 JVMDUMP010I Snap dump written to /scratch/jenkins/workspace/Hazelcast-3.x-IbmJDK1.7/Snap.20160516.045925.292.0007.trc
04:59:29 JVMDUMP013I Processed dump event "systhrow", detail "java/lang/OutOfMemoryError".
05:07:25 JVMDUMP039I Processing dump event "systhrow", detail "java/lang/OutOfMemoryError" at 2016/05/16 05:07:25 - please wait.
05:07:25 JVMDUMP032I JVM requested Heap dump using '/scratch/jenkins/workspace/Hazelcast-3.x-IbmJDK1.7/heapdump.20160516.050725.292.0008.phd' in response to an event
05:07:28 JVMDUMP010I Heap dump written to /scratch/jenkins/workspace/Hazelcast-3.x-IbmJDK1.7/heapdump.20160516.050725.292.0008.phd
05:07:28 JVMDUMP032I JVM requested Java dump using '/scratch/jenkins/workspace/Hazelcast-3.x-IbmJDK1.7/javacore.20160516.050725.292.0009.txt' in response to an event
05:07:28 JVMDUMP010I Java dump written to /scratch/jenkins/workspace/Hazelcast-3.x-IbmJDK1.7/javacore.20160516.050725.292.0009.txt
05:07:28 JVMDUMP032I JVM requested Snap dump using '/scratch/jenkins/workspace/Hazelcast-3.x-IbmJDK1.7/Snap.20160516.050725.292.0010.trc' in response to an event
05:07:28 JVMDUMP010I Snap dump written to /scratch/jenkins/workspace/Hazelcast-3.x-IbmJDK1.7/Snap.20160516.050725.292.0010.trc
05:07:28 JVMDUMP013I Processed dump event "systhrow", detail "java/lang/OutOfMemoryError".
05:07:28 Exception in thread "Thread-7" java.lang.OutOfMemoryError: Java heap space
05:07:28 	at java.lang.String.<init>(String.java:311)
05:07:28 	at java.io.BufferedReader.readLine(BufferedReader.java:361)
05:07:28 	at java.io.BufferedReader.readLine(BufferedReader.java:394)
05:07:28 	at org.apache.maven.surefire.shade.org.apache.maven.shared.utils.cli.StreamPumper.run(StreamPumper.java:66)
05:32:06 JVMDUMP039I Processing dump event "systhrow", detail "java/lang/OutOfMemoryError" at 2016/05/16 05:32:06 - please wait.
05:32:06 JVMDUMP032I JVM requested Heap dump using '/scratch/jenkins/workspace/Hazelcast-3.x-IbmJDK1.7/heapdump.20160516.053206.292.0011.phd' in response to an event
05:32:07 JVMDUMP010I Heap dump written to /scratch/jenkins/workspace/Hazelcast-3.x-IbmJDK1.7/heapdump.20160516.053206.292.0011.phd
05:32:07 JVMDUMP032I JVM requested Java dump using '/scratch/jenkins/workspace/Hazelcast-3.x-IbmJDK1.7/javacore.20160516.053206.292.0012.txt' in response to an event
05:32:07 JVMDUMP010I Java dump written to /scratch/jenkins/workspace/Hazelcast-3.x-IbmJDK1.7/javacore.20160516.053206.292.0012.txt
05:32:07 JVMDUMP032I JVM requested Snap dump using '/scratch/jenkins/workspace/Hazelcast-3.x-IbmJDK1.7/Snap.20160516.053206.292.0013.trc' in response to an event
05:32:07 JVMDUMP010I Snap dump written to /scratch/jenkins/workspace/Hazelcast-3.x-IbmJDK1.7/Snap.20160516.053206.292.0013.trc
05:32:07 JVMDUMP013I Processed dump event "systhrow", detail "java/lang/OutOfMemoryError".
05:32:07 Exception in thread "process reaper" java.lang.OutOfMemoryError: Java heap space
05:32:07 	at java.lang.UNIXProcess$ProcessPipeOutputStream.processExited(UNIXProcess.java:374)
05:32:07 	at java.lang.UNIXProcess.processExited(UNIXProcess.java:248)
05:32:07 	at java.lang.UNIXProcess$4.run(UNIXProcess.java:230)
05:32:07 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1157)
05:32:07 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:627)
05:32:07 	at java.lang.Thread.run(Thread.java:809)
05:32:07 [ERROR] Unexpected error in channel channel
05:32:07 java.lang.OutOfMemoryError: Java heap space
05:32:07 	at java.io.ObjectInputStream$BlockDataInputStream.<init>(ObjectInputStream.java:2484)
05:32:07 	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:345)
05:32:07 	at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:48)
05:32:07 	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:34)
05:32:07 	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:48)
05:32:07 Exception in thread "main" java.lang.reflect.InvocationTargetException
05:32:07 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
05:32:07 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:95)
05:32:07 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:56)
05:32:07 	at java.lang.reflect.Method.invoke(Method.java:620)
05:32:07 	at jenkins.maven3.agent.Maven32Main.main(Maven32Main.java:144)
05:32:07 	at jenkins.maven3.agent.Maven32Main.main(Maven32Main.java:74)
05:32:07 Caused by: java.lang.OutOfMemoryError: Java heap space
05:32:07 	at hudson.remoting.Launcher.main(Launcher.java:535)
05:32:07 	at hudson.remoting.Launcher.main(Launcher.java:502)
05:32:07 	at hudson.remoting.Launcher.main(Launcher.java:493)
05:32:07 	at hudson.remoting.Launcher.main(Launcher.java:489)
05:32:07 	... 6 more
```

This failure seems `ibm-jdk` specific, for now:
https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK1.7/908/consoleFull

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK1.8/216/consoleFull

**Comment by tombujok** [comment]
It's a very complex test - try giving it a bit more Xmx

**Comment by hasancelik** [comment]
closing issue until new failure, new config like this -Xmx2G -Xms1G
