### ISSUE TITLE
WriteBehindWriteDelaySecondsTest.continuouslyUpdatedKey_shouldBeStored_inEveryWriteDelayTimeWindow

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#8207]
```
java.lang.AssertionError: Maximum store operation count should be smaller than 3 but found = 4
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.map.impl.mapstore.writebehind.WriteBehindWriteDelaySecondsTest$2.run(WriteBehindWriteDelaySecondsTest.java:135)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:851)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:865)
	at com.hazelcast.map.impl.mapstore.writebehind.WriteBehindWriteDelaySecondsTest.assertMinMaxStoreOperationsCount(WriteBehindWriteDelaySecondsTest.java:126)
	at com.hazelcast.map.impl.mapstore.writebehind.WriteBehindWriteDelaySecondsTest.continuouslyUpdatedKey_shouldBeStored_inEveryWriteDelayTimeWindow(WriteBehindWriteDelaySecondsTest.java:120)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/955/testReport/junit/com.hazelcast.map.impl.mapstore.writebehind/WriteBehindWriteDelaySecondsTest/continuouslyUpdatedKey_shouldBeStored_inEveryWriteDelayTimeWindow/

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.maintenance-nightly/com.hazelcast$hazelcast/857/testReport/junit/com.hazelcast.map.impl.mapstore.writebehind/WriteBehindWriteDelaySecondsTest/continuouslyUpdatedKey_shouldBeStored_inEveryWriteDelayTimeWindow/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: Maximum store operation count should be smaller than 3 but found = 4
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.map.impl.mapstore.writebehind.WriteBehindWriteDelaySecondsTest$2.run(WriteBehindWriteDelaySecondsTest.java:135)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:857)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:871)
	at com.hazelcast.map.impl.mapstore.writebehind.WriteBehindWriteDelaySecondsTest.assertMinMaxStoreOperationsCount(WriteBehindWriteDelaySecondsTest.java:126)
	at com.hazelcast.map.impl.mapstore.writebehind.WriteBehindWriteDelaySecondsTest.continuouslyUpdatedKey_shouldBeStored_inEveryWriteDelayTimeWindow(WriteBehindWriteDelaySecondsTest.java:120)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/959/testReport/junit/com.hazelcast.map.impl.mapstore.writebehind/WriteBehindWriteDelaySecondsTest/continuouslyUpdatedKey_shouldBeStored_inEveryWriteDelayTimeWindow/

**Comment by hasancelik** [comment]
**maintenance**
```
java.lang.AssertionError: Maximum store operation count should be smaller than 3 but found = 4
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.map.impl.mapstore.writebehind.WriteBehindWriteDelaySecondsTest$2.run(WriteBehindWriteDelaySecondsTest.java:135)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:851)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:865)
	at com.hazelcast.map.impl.mapstore.writebehind.WriteBehindWriteDelaySecondsTest.assertMinMaxStoreOperationsCount(WriteBehindWriteDelaySecondsTest.java:126)
	at com.hazelcast.map.impl.mapstore.writebehind.WriteBehindWriteDelaySecondsTest.continuouslyUpdatedKey_shouldBeStored_inEveryWriteDelayTimeWindow(WriteBehindWriteDelaySecondsTest.java:120)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.maintenance-nightly/com.hazelcast$hazelcast/863/testReport/junit/com.hazelcast.map.impl.mapstore.writebehind/WriteBehindWriteDelaySecondsTest/continuouslyUpdatedKey_shouldBeStored_inEveryWriteDelayTimeWindow/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: Maximum store operation count should be smaller than 3 but found = 4
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.map.impl.mapstore.writebehind.WriteBehindWriteDelaySecondsTest$2.run(WriteBehindWriteDelaySecondsTest.java:135)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:875)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:889)
	at com.hazelcast.map.impl.mapstore.writebehind.WriteBehindWriteDelaySecondsTest.assertMinMaxStoreOperationsCount(WriteBehindWriteDelaySecondsTest.java:126)
	at com.hazelcast.map.impl.mapstore.writebehind.WriteBehindWriteDelaySecondsTest.continuouslyUpdatedKey_shouldBeStored_inEveryWriteDelayTimeWindow(WriteBehindWriteDelaySecondsTest.java:120)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/963/testReport/junit/com.hazelcast.map.impl.mapstore.writebehind/WriteBehindWriteDelaySecondsTest/continuouslyUpdatedKey_shouldBeStored_inEveryWriteDelayTimeWindow/

**Comment by hasancelik** [comment]
**maintenance**
```
java.lang.AssertionError: Maximum store operation count should be smaller than 3 but found = 4
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.map.impl.mapstore.writebehind.WriteBehindWriteDelaySecondsTest$2.run(WriteBehindWriteDelaySecondsTest.java:135)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:851)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:865)
	at com.hazelcast.map.impl.mapstore.writebehind.WriteBehindWriteDelaySecondsTest.assertMinMaxStoreOperationsCount(WriteBehindWriteDelaySecondsTest.java:126)
	at com.hazelcast.map.impl.mapstore.writebehind.WriteBehindWriteDelaySecondsTest.continuouslyUpdatedKey_shouldBeStored_inEveryWriteDelayTimeWindow(WriteBehindWriteDelaySecondsTest.java:120)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.maintenance-nightly/864/com.hazelcast$hazelcast/testReport/com.hazelcast.map.impl.mapstore.writebehind/WriteBehindWriteDelaySecondsTest/continuouslyUpdatedKey_shouldBeStored_inEveryWriteDelayTimeWindow/

**Comment by ahmetmircik** [comment]
Fixed via https://github.com/hazelcast/hazelcast/commit/35068b64315a9f8a0fa6dd76aaec7c109243d96a
