### ISSUE TITLE
org.jsr107.tck.spi.CachingProviderTest.closeCachingProvider

### ISSUE THREAD

**Issue by serkan-ozal** [hazelcast/hazelcast#8214]
```
java.lang.IllegalStateException
	at com.hazelcast.cache.impl.AbstractHazelcastCacheManager.checkIfManagerNotClosed(AbstractHazelcastCacheManager.java:372)
	at com.hazelcast.cache.impl.AbstractHazelcastCacheManager.removeCache(AbstractHazelcastCacheManager.java:286)
	at com.hazelcast.cache.impl.AbstractHazelcastCacheManager.destroyCache(AbstractHazelcastCacheManager.java:281)
	at com.hazelcast.cache.impl.AbstractInternalCacheProxy.postDestroy(AbstractInternalCacheProxy.java:118)
	at com.hazelcast.spi.AbstractDistributedObject.destroy(AbstractDistributedObject.java:62)
	at com.hazelcast.cache.impl.AbstractHazelcastCacheManager.destroy(AbstractHazelcastCacheManager.java:355)
	at com.hazelcast.cache.impl.AbstractHazelcastCachingProvider.close(AbstractHazelcastCachingProvider.java:138)
	at com.hazelcast.cache.HazelcastCachingProvider.close(HazelcastCachingProvider.java:179)
	at org.jsr107.tck.spi.CachingProviderTest.closeCachingProvider(CachingProviderTest.java:165)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:53)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:123)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:104)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:172)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:104)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:70)
```

https://hazelcast-l337.ci.cloudbees.com/job/JCache-TCK-master/3076/

**Comment by serkan-ozal** [comment]
fixed via https://github.com/hazelcast/hazelcast/commit/e99c92e9b499aaa8a5b980759370665f1511f733
