### ISSUE TITLE
GracefulShutdownTest.shutdownMemberAndCluster_concurrently_withoutPartitionInitialization

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#8227]
```
com.hazelcast.core.OperationTimeoutException: ChangeClusterStateOperation invocation failed to complete due to operation-heartbeat-timeout. Current time: 2016-05-23 08:50:03.694. Total elapsed time: 120477 ms. Last heartbeat: never. Last member heartbeat: never. Invocation{op=com.hazelcast.internal.cluster.impl.operations.ChangeClusterStateOperation{serviceName='hz:core:clusterService', identityHash=1538069292, partitionId=-1, replicaIndex=0, callId=0, invocationTime=1463982483217 (2016-05-23 08:48:03.217), waitTimeout=-1, callTimeout=60000}, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=60000, firstInvocationTimeMs=1463982483217, firstInvocationTime='2016-05-23 08:48:03.217', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 02:00:00.000', target=[127.0.0.1]:7117, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=MockConnection{localEndpoint=[127.0.0.1]:7118, remoteEndpoint=[127.0.0.1]:7117}}
```

https://hazelcast-l337.ci.cloudbees.com/view/Zing/job/Hazelcast-3.x-ZingJDK8/25/testReport/junit/com.hazelcast.internal.partition/GracefulShutdownTest/shutdownMemberAndCluster_concurrently_withoutPartitionInitialization/

**Comment by Donnerbart** [comment]
**com.hazelcast.internal.partition.GracefulShutdownTest.shutdownMemberAndCluster_concurrently_withoutPartitionInitialization**
```java
java.util.concurrent.ExecutionException: com.hazelcast.core.OperationTimeoutException: CommitClusterStateOp invocation failed to complete due to operation-heartbeat-timeout. Current time: 2017-07-19 12:14:31.574. Start time: 2017-07-19 12:12:31.326. Total elapsed time: 120248 ms. Last operation heartbeat: never. Last operation heartbeat from member: never. Invocation{op=com.hazelcast.internal.cluster.impl.operations.CommitClusterStateOp{serviceName='hz:core:clusterService', identityHash=1140841731, partitionId=-1, replicaIndex=0, callId=-12, invocationTime=1500466351326 (2017-07-19 12:12:31.326), waitTimeout=-1, callTimeout=60000}, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=60000, firstInvocationTimeMs=1500466351326, firstInvocationTime='2017-07-19 12:12:31.326', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 00:00:00.000', target=[127.0.0.1]:5098, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=null}
	at java.util.concurrent.FutureTask$Sync.innerGet(FutureTask.java:222)
	at java.util.concurrent.FutureTask.get(FutureTask.java:83)
	at com.hazelcast.internal.partition.GracefulShutdownTest.shutdownMemberAndCluster_concurrently(GracefulShutdownTest.java:467)
	at com.hazelcast.internal.partition.GracefulShutdownTest.shutdownMemberAndCluster_concurrently_withoutPartitionInitialization(GracefulShutdownTest.java:432)
Caused by: com.hazelcast.core.OperationTimeoutException: CommitClusterStateOp invocation failed to complete due to operation-heartbeat-timeout. Current time: 2017-07-19 12:14:31.574. Start time: 2017-07-19 12:12:31.326. Total elapsed time: 120248 ms. Last operation heartbeat: never. Last operation heartbeat from member: never. Invocation{op=com.hazelcast.internal.cluster.impl.operations.CommitClusterStateOp{serviceName='hz:core:clusterService', identityHash=1140841731, partitionId=-1, replicaIndex=0, callId=-12, invocationTime=1500466351326 (2017-07-19 12:12:31.326), waitTimeout=-1, callTimeout=60000}, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=60000, firstInvocationTimeMs=1500466351326, firstInvocationTime='2017-07-19 12:12:31.326', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 00:00:00.000', target=[127.0.0.1]:5098, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=null}
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.newOperationTimeoutException(InvocationFuture.java:157)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:104)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:77)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:183)
	at com.hazelcast.util.FutureUtil.executeWithDeadline(FutureUtil.java:372)
	at com.hazelcast.util.FutureUtil.waitWithDeadline(FutureUtil.java:356)
	at com.hazelcast.util.FutureUtil.waitWithDeadline(FutureUtil.java:330)
	at com.hazelcast.transaction.impl.TransactionImpl.commit(TransactionImpl.java:292)
	at com.hazelcast.internal.cluster.impl.ClusterStateManager.changeClusterState(ClusterStateManager.java:367)
	at com.hazelcast.internal.cluster.impl.ClusterStateManager.changeClusterState(ClusterStateManager.java:333)
	at com.hazelcast.internal.cluster.impl.ClusterServiceImpl.changeClusterState(ClusterServiceImpl.java:975)
	at com.hazelcast.internal.cluster.impl.ClusterServiceImpl.changeClusterState(ClusterServiceImpl.java:970)
	at com.hazelcast.internal.cluster.impl.AdvancedClusterStateTest.changeClusterStateEventually(AdvancedClusterStateTest.java:780)
	at com.hazelcast.internal.partition.GracefulShutdownTest$6.run(GracefulShutdownTest.java:461)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.lang.Thread.run(Thread.java:662)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/9847/testReport/junit/com.hazelcast.internal.partition/GracefulShutdownTest/shutdownMemberAndCluster_concurrently_withoutPartitionInitialization/
