### ISSUE TITLE
[ZING-JVM] IOBalancerStressTest.testEachConnectionUseDifferentSelectorEventually

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#8229]
```
java.lang.AssertionError: activeHandlerEvent count should be at least 1000, but was:50
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.nio.tcp.nonblocking.iobalancer.IOBalancerStressTest.assertBalanced(IOBalancerStressTest.java:174)
	at com.hazelcast.nio.tcp.nonblocking.iobalancer.IOBalancerStressTest.assertBalanced(IOBalancerStressTest.java:97)
	at com.hazelcast.nio.tcp.nonblocking.iobalancer.IOBalancerStressTest.testEachConnectionUseDifferentSelectorEventually(IOBalancerStressTest.java:83)
```

https://hazelcast-l337.ci.cloudbees.com/view/Zing/job/Hazelcast-3.x-ZingJDK7/34/testReport/junit/com.hazelcast.nio.tcp.nonblocking.iobalancer/IOBalancerStressTest/testEachConnectionUseDifferentSelectorEventually/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: activeHandlerEvent count should be at least 1000, but was:35
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.nio.tcp.nonblocking.iobalancer.IOBalancerStressTest.assertBalanced(IOBalancerStressTest.java:172)
	at com.hazelcast.nio.tcp.nonblocking.iobalancer.IOBalancerStressTest.assertBalanced(IOBalancerStressTest.java:95)
	at com.hazelcast.nio.tcp.nonblocking.iobalancer.IOBalancerStressTest.testEachConnectionUseDifferentSelectorEventually(IOBalancerStressTest.java:81)
```

https://hazelcast-l337.ci.cloudbees.com/view/Zing/job/Hazelcast-3.x-ZingJDK6/17/testReport/junit/com.hazelcast.nio.tcp.nonblocking.iobalancer/IOBalancerStressTest/testEachConnectionUseDifferentSelectorEventually/

**Comment by vbekiaris** [comment]
Log output mentions:
```
in selectors
hz._hzInstance_9526_dev.IO.thread-in-0 :44
	Connection[id=2, /127.0.0.1:5701->/127.0.0.1:38384, endpoint=[127.0.0.1]:5703, alive=true, type=MEMBER].socketReader eventCount:40
hz._hzInstance_9526_dev.IO.thread-in-1 :42
	Connection[id=4, /127.0.0.1:5701->/127.0.0.1:60668, endpoint=[127.0.0.1]:5702, alive=true, type=MEMBER].socketReader eventCount:35
out selectors
hz._hzInstance_9526_dev.IO.thread-out-0 :3
	Connection[id=2, /127.0.0.1:5701->/127.0.0.1:38384, endpoint=[127.0.0.1]:5703, alive=true, type=MEMBER].socketWriter eventCount:41
hz._hzInstance_9526_dev.IO.thread-out-1 :2
	Connection[id=4, /127.0.0.1:5701->/127.0.0.1:60668, endpoint=[127.0.0.1]:5702, alive=true, type=MEMBER].socketWriter eventCount:45
```
