### ISSUE TITLE
LiteMemberJoinTest.test_liteMemberReconnects_multicast

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#8253]
```
java.lang.IllegalStateException: ConnectionManager is already shutdown. Cannot start!
	at com.hazelcast.nio.tcp.TcpIpConnectionManager.start(TcpIpConnectionManager.java:454)
	at com.hazelcast.internal.cluster.impl.ClusterMergeTask.rejoin(ClusterMergeTask.java:111)
	at com.hazelcast.internal.cluster.impl.ClusterMergeTask.run(ClusterMergeTask.java:65)
	at com.hazelcast.instance.LifecycleServiceImpl.runUnderLifecycleLock(LifecycleServiceImpl.java:107)
	at com.hazelcast.internal.cluster.impl.ClusterServiceImpl.merge(ClusterServiceImpl.java:302)
	at com.hazelcast.cluster.LiteMemberJoinTest.reconnect(LiteMemberJoinTest.java:162)
	at com.hazelcast.cluster.LiteMemberJoinTest.test_liteMemberReconnects(LiteMemberJoinTest.java:148)
	at com.hazelcast.cluster.LiteMemberJoinTest.test_liteMemberReconnects_multicast(LiteMemberJoinTest.java:136)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-OracleJDK8/com.hazelcast$hazelcast/815/testReport/junit/com.hazelcast.cluster/LiteMemberJoinTest/test_liteMemberReconnects_multicast/

**Comment by hasancelik** [comment]
```
java.lang.IllegalStateException: ConnectionManager is already shutdown. Cannot start!
	at com.hazelcast.nio.tcp.TcpIpConnectionManager.start(TcpIpConnectionManager.java:454)
	at com.hazelcast.internal.cluster.impl.ClusterMergeTask.rejoin(ClusterMergeTask.java:111)
	at com.hazelcast.internal.cluster.impl.ClusterMergeTask.run(ClusterMergeTask.java:65)
	at com.hazelcast.instance.LifecycleServiceImpl.runUnderLifecycleLock(LifecycleServiceImpl.java:107)
	at com.hazelcast.internal.cluster.impl.ClusterServiceImpl.merge(ClusterServiceImpl.java:302)
	at com.hazelcast.cluster.LiteMemberJoinTest.reconnect(LiteMemberJoinTest.java:162)
	at com.hazelcast.cluster.LiteMemberJoinTest.test_liteMemberReconnects(LiteMemberJoinTest.java:148)
	at com.hazelcast.cluster.LiteMemberJoinTest.test_liteMemberReconnects_multicast(LiteMemberJoinTest.java:136)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast$hazelcast/922/testReport/junit/com.hazelcast.cluster/LiteMemberJoinTest/test_liteMemberReconnects_multicast/

**Comment by hasancelik** [comment]
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.lang.Thread.sleep(Native Method)
	at com.hazelcast.internal.cluster.impl.MulticastJoiner.joinMaster(MulticastJoiner.java:94)
	at com.hazelcast.internal.cluster.impl.MulticastJoiner.doJoin(MulticastJoiner.java:72)
	at com.hazelcast.internal.cluster.impl.AbstractJoiner.join(AbstractJoiner.java:118)
	at com.hazelcast.instance.Node.join(Node.java:650)
	at com.hazelcast.internal.cluster.impl.ClusterMergeTask.rejoin(ClusterMergeTask.java:113)
	at com.hazelcast.internal.cluster.impl.ClusterMergeTask.run(ClusterMergeTask.java:65)
	at com.hazelcast.instance.LifecycleServiceImpl.runUnderLifecycleLock(LifecycleServiceImpl.java:107)
	at com.hazelcast.internal.cluster.impl.ClusterServiceImpl.merge(ClusterServiceImpl.java:302)
	at com.hazelcast.cluster.LiteMemberJoinTest.reconnect(LiteMemberJoinTest.java:162)
	at com.hazelcast.cluster.LiteMemberJoinTest.test_liteMemberReconnects(LiteMemberJoinTest.java:148)
	at com.hazelcast.cluster.LiteMemberJoinTest.test_liteMemberReconnects_multicast(LiteMemberJoinTest.java:136)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-sonar/com.hazelcast$hazelcast/1071/testReport/junit/com.hazelcast.cluster/LiteMemberJoinTest/test_liteMemberReconnects_multicast/

**Comment by jerrinot** [comment]
this is an interesting warning:
`WARNING: [127.0.0.1]:5701 [dev] [3.7-SNAPSHOT] SocketAcceptor thread is already live! Shutting down old acceptor...`
