### ISSUE TITLE
MultiMapEntryListenerOnReconnectTest.testListenersNonSmartRoutingMultipleServer & testListenersSmartRoutingMultipleServer

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#8254]
```
org.junit.runners.model.TestTimedOutException: test timed out after 120000 milliseconds
    at sun.misc.Unsafe.park(Native Method)
    at java.util.concurrent.locks.LockSupport.park(LockSupport.java:304)
    at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:156)
    at com.hazelcast.client.spi.ClientProxy.invokeOnPartition(ClientProxy.java:153)
    at com.hazelcast.client.spi.ClientProxy.invoke(ClientProxy.java:147)
    at com.hazelcast.client.proxy.ClientMultiMapProxy.put(ClientMultiMapProxy.java:109)
    at com.hazelcast.client.listeners.MultiMapEntryListenerOnReconnectTest.produceEvent(MultiMapEntryListenerOnReconnectTest.java:33)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-ZuluJDK8/com.hazelcast$hazelcast-client/215/testReport/junit/com.hazelcast.client.listeners/MultiMapEntryListenerOnReconnectTest/testListenersNonSmartRoutingMultipleServer/

**Comment by jerrinot** [comment]
from the log
```
04:06:15,188  WARN |testListenersNonSmartRoutingMultipleServer| - [Invocation] hz._hzInstance_888_dev.response - [127.0.0.1]:5840 [dev] [3.7-SNAPSHOT] Retrying invocation: Invocation{op=com.hazelcast.multimap.impl.operations.PutOperation{serviceName='hz:impl:multiMapService', identityHash=1927773733, partitionId=132, replicaIndex=0, callId=106, invocationTime=1464224775187 (2016-05-26 04:06:15.187), waitTimeout=-1, callTimeout=60000, name=f5192c5f-8686-49d7-b910-e2dcc2018bee}, tryCount=250, tryPauseMillis=500, invokeCount=100, callTimeoutMillis=60000, firstInvocationTimeMs=1464224727620, firstInvocationTime='2016-05-26 04:05:27.620', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 02:00:00.000', target=[127.0.0.1]:5843, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=MockConnection{localEndpoint=[127.0.0.1]:5840, remoteEndpoint=[127.0.0.1]:5843}}, Reason: com.hazelcast.spi.exception.WrongTargetException: WrongTarget! this: [127.0.0.1]:5843, target: null, partitionId: 132, replicaIndex: 0, operation: com.hazelcast.multimap.impl.operations.PutOperation, service: hz:impl:multiMapService
```

This is repeated multiple times. Until the timeout.

**Comment by hasancelik** [comment]
```
org.junit.runners.model.TestTimedOutException: test timed out after 120000 milliseconds
	at java.lang.Thread.sleep(Native Method)
	at com.hazelcast.client.spi.impl.ClientPartitionServiceImpl.getPartitionsBlocking(ClientPartitionServiceImpl.java:96)
	at com.hazelcast.client.spi.impl.ClientPartitionServiceImpl.getPartitionCount(ClientPartitionServiceImpl.java:192)
	at com.hazelcast.client.spi.impl.ClientPartitionServiceImpl.getPartitionId(ClientPartitionServiceImpl.java:175)
	at com.hazelcast.client.spi.impl.ClientPartitionServiceImpl.getPartitionId(ClientPartitionServiceImpl.java:186)
	at com.hazelcast.client.spi.ClientProxy.invoke(ClientProxy.java:146)
	at com.hazelcast.client.proxy.ClientMultiMapProxy.put(ClientMultiMapProxy.java:109)
	at com.hazelcast.client.listeners.MultiMapEntryListenerOnReconnectTest.produceEvent(MultiMapEntryListenerOnReconnectTest.java:33)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-ZuluJDK8/com.hazelcast$hazelcast-client/222/testReport/junit/com.hazelcast.client.listeners/MultiMapEntryListenerOnReconnectTest/testListenersSmartRoutingMultipleServer/

**Comment by cangencer** [comment]
closing issue, for explanation see: https://github.com/hazelcast/hazelcast/issues/8244#issuecomment-233323820

**Comment by hasancelik** [comment]
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1037)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1328)
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:277)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:872)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:867)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:859)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest$9.run(AbstractListenersOnReconnectTest.java:523)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:967)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:984)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest.validateListenerFunctionality(AbstractListenersOnReconnectTest.java:510)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest.validateRegistrationsAndListenerFunctionality(AbstractListenersOnReconnectTest.java:473)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest.testListenersTerminateOwnerNode(AbstractListenersOnReconnectTest.java:458)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest.testListenersNonSmartRoutingMultipleServer(AbstractListenersOnReconnectTest.java:409)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK8/com.hazelcast$hazelcast-client/1118/testReport/junit/com.hazelcast.client.listeners/MultiMapEntryListenerOnReconnectTest/testListenersNonSmartRoutingMultipleServer/

**Comment by Donnerbart** [comment]
```java
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:196)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1011)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1303)
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:253)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:947)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:942)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:934)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest$9.run(AbstractListenersOnReconnectTest.java:523)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1042)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1059)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest.validateListenerFunctionality(AbstractListenersOnReconnectTest.java:510)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest.validateRegistrationsAndListenerFunctionality(AbstractListenersOnReconnectTest.java:473)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest.testListenersTerminateOwnerNode(AbstractListenersOnReconnectTest.java:458)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest.testListenersNonSmartRoutingMultipleServer(AbstractListenersOnReconnectTest.java:409)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.lang.Thread.run(Thread.java:662)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/8807/testReport/junit/com.hazelcast.client.listeners/MultiMapEntryListenerOnReconnectTest/testListenersNonSmartRoutingMultipleServer/

**Comment by Holmistr** [comment]
*master*

Reopening as it failed in the PR builder: https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/15150/testReport/junit/com.hazelcast.client.listeners/MultiMapEntryListenerOnReconnectTest/testListenersNonSmartRoutingTerminateRandomNode/

Stacktrace:
```
java.lang.AssertionError: Member [127.0.0.1]:5006 - 8a7740b6-a594-4319-9bdc-911e7e1a35fe this expected:<1> but was:<2>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest$8.run(AbstractListenersOnReconnectTest.java:484)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1244)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1261)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest.validateRegistrationsOnMembers(AbstractListenersOnReconnectTest.java:475)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest.validateRegistrationsAndListenerFunctionality(AbstractListenersOnReconnectTest.java:468)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest.testListenersTerminateRandomNode(AbstractListenersOnReconnectTest.java:116)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest.testListenersNonSmartRoutingTerminateRandomNode(AbstractListenersOnReconnectTest.java:80)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by sancar** [comment]
Failed again in maintenance 3.10.2-SNAPSHOT

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-pr-builder/15725/

```


com.hazelcast.client.listeners.SetItemListenerOnReconnectTest.testListenersNonSmartRoutingMultipleServer

Failing for the past 1 build (Since Unstable#15725 )
Took 50 sec.
Error Message
Member [127.0.0.1]:5009 - 6831c297-92e3-4f1e-9550-0cd29d1a21c9 this expected:<1> but was:<2>
Stacktrace
java.lang.AssertionError: Member [127.0.0.1]:5009 - 6831c297-92e3-4f1e-9550-0cd29d1a21c9 this expected:<1> but was:<2>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest$8.run(AbstractListenersOnReconnectTest.java:486)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1246)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1272)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest.validateRegistrationsOnMembers(AbstractListenersOnReconnectTest.java:477)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest.validateRegistrationsAndListenerFunctionality(AbstractListenersOnReconnectTest.java:470)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest.testListenersTerminateOwnerNode(AbstractListenersOnReconnectTest.java:457)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest.testListenersNonSmartRoutingMultipleServer(AbstractListenersOnReconnectTest.java:408)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```
	
Problematic logs mentioned in following fix are still there:
https://github.com/hazelcast/hazelcast/pull/13073 
Problematic logs:
```
08:46:53,118  WARN |testListenersNonSmartRoutingMultipleServer| - [ClientInvocationService] hz.client_5.responsethread-0- - hz.client_5 [dev] [3.10.2-SNAPSHOT] Future.complete(Object) on completed future.
         Request: ClientMessage{length=64, correlationId=7, operation=Set.addListener, messageType=60b, partitionId=-1, isComplete=true, isRetryable=false, isEvent=false, writeOffset=0}, 
   current value: ClientMessage{length=62, correlationId=7, operation=null, messageType=68, partitionId=-1, isComplete=true, isRetryable=false, isEvent=false, writeOffset=0}, 
   offered value: ClientMessage{length=22, correlationId=22, operation=null, messageType=68, partitionId=-1, isComplete=false, isRetryable=false, isEvent=false, writeOffset=0}
```

**Comment by Holmistr** [comment]
Closing this issue for now with adding additional logging in https://github.com/hazelcast/hazelcast/pull/13200 and https://github.com/hazelcast/hazelcast/pull/13204 . @sancar and @ihsan were looking into this issue, couldn't find anything so far, so let's wait for another failure with additional logs and reopen then.

**Comment by tezc** [comment]
http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-OracleJDK11/105/testReport/com.hazelcast.client.listeners/MultiMapEntryListenerOnReconnectTest/testListenersNonSmartRoutingMultipleServer/

**Stacktrace**
```
java.lang.AssertionError: Cluster size is not correct. Expected: 3, actual: 2, instance index: 0
	at org.junit.Assert.fail(Assert.java:88)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSize(HazelcastTestSupport.java:1113)
	at com.hazelcast.test.HazelcastTestSupport$11.run(HazelcastTestSupport.java:1141)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1326)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1343)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:1138)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:1126)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest.testListenersTerminateCluster(AbstractListenersOnReconnectTest.java:324)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest.testListenersNonSmartRoutingMultipleServer(AbstractListenersOnReconnectTest.java:277)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

```
Hiccups measured while running test 'testListenersNonSmartRoutingMultipleServer(com.hazelcast.client.listeners.MultiMapEntryListenerOnReconnectTest):'
02:23:45, accumulated pauses: 103 ms, max pause: 21 ms, pauses over 1000 ms: 0
02:23:50, accumulated pauses: 410 ms, max pause: 95 ms, pauses over 1000 ms: 0
02:23:55, accumulated pauses: 280 ms, max pause: 241 ms, pauses over 1000 ms: 0
02:24:00, accumulated pauses: 81 ms, max pause: 25 ms, pauses over 1000 ms: 0
02:24:05, accumulated pauses: 51 ms, max pause: 1 ms, pauses over 1000 ms: 0
02:24:10, accumulated pauses: 272 ms, max pause: 146 ms, pauses over 1000 ms: 0
02:24:15, accumulated pauses: 38 ms, max pause: 2 ms, pauses over 1000 ms: 0
02:24:20, accumulated pauses: 39 ms, max pause: 0 ms, pauses over 1000 ms: 0
02:24:25, accumulated pauses: 60 ms, max pause: 1 ms, pauses over 1000 ms: 0
02:24:30, accumulated pauses: 50 ms, max pause: 1 ms, pauses over 1000 ms: 0
02:24:35, accumulated pauses: 59 ms, max pause: 2 ms, pauses over 1000 ms: 0
02:24:40, accumulated pauses: 52 ms, max pause: 7 ms, pauses over 1000 ms: 0
02:24:45, accumulated pauses: 46 ms, max pause: 1 ms, pauses over 1000 ms: 0
02:24:50, accumulated pauses: 44 ms, max pause: 1 ms, pauses over 1000 ms: 0
02:24:55, accumulated pauses: 42 ms, max pause: 0 ms, pauses over 1000 ms: 0
02:25:00, accumulated pauses: 34 ms, max pause: 1 ms, pauses over 1000 ms: 0
02:25:05, accumulated pauses: 41 ms, max pause: 1 ms, pauses over 1000 ms: 0
02:25:10, accumulated pauses: 30 ms, max pause: 0 ms, pauses over 1000 ms: 0
02:25:15, accumulated pauses: 34 ms, max pause: 0 ms, pauses over 1000 ms: 0
02:25:20, accumulated pauses: 41 ms, max pause: 0 ms, pauses over 1000 ms: 0
02:25:25, accumulated pauses: 48 ms, max pause: 1 ms, pauses over 1000 ms: 0
02:25:30, accumulated pauses: 62 ms, max pause: 1 ms, pauses over 1000 ms: 0
02:25:35, accumulated pauses: 96 ms, max pause: 1 ms, pauses over 1000 ms: 0
02:25:40, accumulated pauses: 41 ms, max pause: 1 ms, pauses over 1000 ms: 0
02:25:45, accumulated pauses: 40 ms, max pause: 9 ms, pauses over 1000 ms: 0
02:25:50, accumulated pauses: 911 ms, max pause: 888 ms, pauses over 1000 ms: 0
```

**Comment by ahmetmircik** [comment]
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/4646/testReport/junit/com.hazelcast.client.listeners/MultiMapEntryListenerOnReconnectTest/testClusterReconnectMultipleServerDueToHeartbeatNonSmartRouting/

```
Stacktrace
java.util.NoSuchElementException
	at java.util.concurrent.ConcurrentHashMap$ValueIterator.next(ConcurrentHashMap.java:3436)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest$5.run(AbstractListenersOnReconnectTest.java:393)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1326)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1428)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest.validateRegistrations(AbstractListenersOnReconnectTest.java:374)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest.validateRegistrationsAndListenerFunctionality(AbstractListenersOnReconnectTest.java:343)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest.testListenersHeartbeatTimeoutToCluster(AbstractListenersOnReconnectTest.java:256)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest.testClusterReconnectMultipleServerDueToHeartbeatNonSmartRouting(AbstractListenersOnReconnectTest.java:224)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by sancar** [comment]
I am on it. If it starts to fail a lot don't hesitate to @ignore.
