### ISSUE TITLE
PostJoinMapOperationTest.testPostJoinMapOperation_mapWithIndex

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#8257]
```
java.lang.AssertionError: expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.map.impl.operation.PostJoinMapOperationTest.testPostJoinMapOperation_mapWithIndex(PostJoinMapOperationTest.java:223)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x/com.hazelcast$hazelcast/5164/testReport/junit/com.hazelcast.map.impl.operation/PostJoinMapOperationTest/testPostJoinMapOperation_mapWithIndex/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.map.impl.operation.PostJoinMapOperationTest.testPostJoinMapOperation_mapWithIndex(PostJoinMapOperationTest.java:223)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-ZuluJDK8/com.hazelcast$hazelcast/216/testReport/junit/com.hazelcast.map.impl.operation/PostJoinMapOperationTest/testPostJoinMapOperation_mapWithIndex/

**Comment by vbekiaris** [comment]
This test failure was not reproducible on Mac OSX with:
- Apple JDK6 + maven 3.2.5
- Oracle JDK8 + maven 3.3.9
- Zulu JDK8 + maven 3.3.9

either standalone or running the `parallelTest` profile. #8266 improves the test .

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.map.impl.operation.PostJoinMapOperationTest.testPostJoinMapOperation_mapWithIndex(PostJoinMapOperationTest.java:223)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x/com.hazelcast$hazelcast/5174/testReport/junit/com.hazelcast.map.impl.operation/PostJoinMapOperationTest/testPostJoinMapOperation_mapWithIndex/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: index should return 1 match expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.map.impl.operation.PostJoinMapOperationTest.testPostJoinMapOperation_mapWithIndex(PostJoinMapOperationTest.java:222)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK1.8/com.hazelcast$hazelcast/240/testReport/junit/com.hazelcast.map.impl.operation/PostJoinMapOperationTest/testPostJoinMapOperation_mapWithIndex/

**Comment by jerrinot** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/3365/testReport/junit/com.hazelcast.map.impl.operation/PostJoinMapOperationTest/testPostJoinMapOperation_mapWithIndex/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: index should return 1 match expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.map.impl.operation.PostJoinMapOperationTest.testPostJoinMapOperation_mapWithIndex(PostJoinMapOperationTest.java:222)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x/com.hazelcast$hazelcast/5222/testReport/junit/com.hazelcast.map.impl.operation/PostJoinMapOperationTest/testPostJoinMapOperation_mapWithIndex/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: index should return 1 match expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.map.impl.operation.PostJoinMapOperationTest.testPostJoinMapOperation_mapWithIndex(PostJoinMapOperationTest.java:222)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-OracleJDK8/com.hazelcast$hazelcast/830/testReport/junit/com.hazelcast.map.impl.operation/PostJoinMapOperationTest/testPostJoinMapOperation_mapWithIndex/
