### ISSUE TITLE
Wait for event to be processed during shutdown

### ISSUE THREAD

**Issue by victornoel** [hazelcast/hazelcast#8258]
Hi,

This issue emanates from a [discussion on the mailing list](https://groups.google.com/d/topic/hazelcast/LGeczYEr-Jo/discussion).

Basically, my initial problem, which looks like a bug to me, is that if I have a Hazelcast member node with a ClientListener and a HazelcastClient node that connects to it, if things happen, in this order:
- client disconnects
- client listener removed from member node
- member shutdown

Then I would expect that if the member receive the disconnection event before shutdown, then it will execute the client listener code before shutdown is actually done.

What happens in my use case, is that the client listener is actually executed during the shutdown and finishes after the shutdown has happened, and since it relies on the member node to be up, exceptions are thrown like this one:
```
sample-0 2016/05/25 09:32:08,638 GMT+0200 SEVERE [com.hazelcast.spi.impl.eventservice.impl.EventServiceImpl] : [127.0.0.1]:7900 [default-sample] [3.6.2] hz._hzInstance_1_default-sample.event-5 caught an exception while processing task:com.hazelcast.spi.impl.eventservice.impl.LocalEventDispatcher@1d172ac0
com.hazelcast.core.HazelcastInstanceNotActiveException: Hazelcast instance is not active!
    at com.hazelcast.spi.AbstractDistributedObject.throwNotActiveException(AbstractDistributedObject.java:85)
    at com.hazelcast.spi.AbstractDistributedObject.lifecycleCheck(AbstractDistributedObject.java:80)
    at com.hazelcast.spi.AbstractDistributedObject.getNodeEngine(AbstractDistributedObject.java:74)
    at com.hazelcast.concurrent.lock.LockProxy.unlock(LockProxy.java:106)
    at org.ow2.petals.registry_overlay.core.ClientListener.clientDisconnected(ClientListener.java:89)
    at com.hazelcast.client.impl.ClientEngineImpl.dispatchEvent(ClientEngineImpl.java:293)
    at com.hazelcast.client.impl.ClientEngineImpl.dispatchEvent(ClientEngineImpl.java:99)
    at com.hazelcast.spi.impl.eventservice.impl.LocalEventDispatcher.run(LocalEventDispatcher.java:56)
    at com.hazelcast.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:187)
    at com.hazelcast.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:171)
```

So, in the same way that shutdown (contrary to terminate) waits for partition operation to finish, I don't see why the node wouldn't wait for event to be processed. It could, for example, stop accepting new event to process, but finish processing the previous ones, or something like that.

Thanks for your help :)

**Comment by cforce** [comment]
I this related with another bug which during rampup of new nodes applied map interceptors before going productive with new nodes are executed on node which are not active which leads to com.hazelcast.core.HazelcastInstanceNotActiveException: Member [XXXXX]:XXX is currently passive! Operation: com.hazelcast.map.impl.operation.AddInterceptorOperation{serviceName='hz:impl:mapService', identityHash=XXXXX, partitionId=-1, replicaIndex=0, callId=XXXX, invocationTime=XXXXX (XXXXXXXX), waitTimeout=-1, callTimeout=60000

Trying to send AddInterceptor operation to PASSIVE (because shutting down) members does not make sense at all and will fail completely.
addMapInterceptorInternal and removeMapInterceptorInternal must rather exclude passive member's, which is not done currently, is it?

**Comment by mmedenjak** [comment]
@cforce I'm not sure if I understood your question but yes, interceptors must be added to all of the members and the PASSIVE state assumes that no user actions which modify the data or the structures are allowed (internal ones being allowed). Adding interceptors to only some members can later lead to strange results.

**Comment by cforce** [comment]
I am currently have running conditions in the hazelcast cluster (count>45) while rolling updates. Some nodes are shutting down, and some of the nodes are ramping up. During the ramp-up of new nodes, we need to make sure that map interceptors are used before we get productive with new nodes. But this fails with above error message because AddInterceptor  methods are called on the passive nodes which will then fail of course.

**Comment by mmedenjak** [comment]
Then I guess you would benefit from [adding interceptors to the configuration](https://github.com/hazelcast/hazelcast/issues/3864) as opposed to adding them programmatically.

**Comment by cforce** [comment]
Confused now . Why is that a question of configuration. My expectation is that this tow methods of adding/removing interceptors need filtering on active nodes only.

**Comment by mmedenjak** [comment]
> During the ramp-up of new nodes, ineed to make sure that map interceptors are used before i get productive with new nodes.

This is the reason why we need to allow setting the map interceptors in the configuration, so that the interceptors are active as soon as the user starts interacting with the started nodes.

**Comment by cforce** [comment]
For me it look like interceptors are active on source node, but tried execution on remote failed due to NodeLifecycle is in NodeState passive and trying to execute them on nodes which are are in tear down and therefore not active , which  is a constraint to execute there. 
The node which is firing the issue might be a new node, yes , but even if if "enforce" interceptor" execution manually by code, i still don't understand why the MapProxySupport does not verify on active nodes condition before trying to execute it via syncInvokeOnAllMembers() while it shall  syncInvokeOnActiveMembers()  only

**Comment by mmedenjak** [comment]
The coordinator node on which you called `addMapInterceptor` or `removeMapInterceptor` may only check if it's local state is PASSIVE. It has no knowledge if the remote node is PASSIVE or not.

I believe the right approach here is not implementing any kind of filtering but moving the list of interceptors to the configuration so that the nodes can start and shut down with the appropriate interceptors, without any need to call `addMapInterceptor`.

**Comment by cforce** [comment]
The big problem is that since 6?  years the patch once done to support this kind of bug fix never made it into any release.

**Comment by mmedenjak** [comment]
That patch is incomplete as indicated [here](https://github.com/hazelcast/hazelcast/issues/3864#issuecomment-566925729).
