### ISSUE TITLE
MapStoreWriteBehindTest.testWriteBehindDestroy

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#8272]
```
java.lang.AssertionError: Values should be different. Actual: value
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failEquals(Assert.java:185)
	at org.junit.Assert.assertNotEquals(Assert.java:161)
	at org.junit.Assert.assertNotEquals(Assert.java:175)
	at com.hazelcast.map.impl.mapstore.MapStoreWriteBehindTest.testWriteBehindDestroy(MapStoreWriteBehindTest.java:329)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.7/

**Comment by ahmetmircik** [comment]
Fix attempt for this test: https://github.com/hazelcast/hazelcast/commit/bf57830124f1d8c5233fd61d243cbe0c16161b6c
