### ISSUE TITLE
[ZING-JVM] EntryListenerOnReconnectTest.testListenersSmartRoutingMultipleServer & MultiMapEntryListenerOnReconnectTest.testListenersSmartRouting 

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#8286]
**EntryListenerOnReconnectTest.testListenersSmartRoutingMultipleServer**
```
org.junit.runners.model.TestTimedOutException: test timed out after 120000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:311)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:156)
	at com.hazelcast.client.spi.ClientProxy.invokeOnPartition(ClientProxy.java:153)
	at com.hazelcast.client.spi.ClientProxy.invoke(ClientProxy.java:147)
	at com.hazelcast.client.proxy.ClientMapProxy.putInternal(ClientMapProxy.java:452)
	at com.hazelcast.client.proxy.ClientMapProxy.put(ClientMapProxy.java:446)
	at com.hazelcast.client.proxy.ClientMapProxy.put(ClientMapProxy.java:247)
	at com.hazelcast.client.listeners.EntryListenerOnReconnectTest.produceEvent(EntryListenerOnReconnectTest.java:49)
```

https://hazelcast-l337.ci.cloudbees.com/view/Zing/job/Hazelcast-3.x-ZingJDK6/14/testReport/junit/com.hazelcast.client.listeners/EntryListenerOnReconnectTest/testListenersSmartRoutingMultipleServer/

**MultiMapEntryListenerOnReconnectTest.testListenersSmartRouting**
```
org.junit.runners.model.TestTimedOutException: test timed out after 120000 milliseconds
	at java.lang.Thread.sleep(Native Method)
	at java.lang.Thread.sleep(Thread.java:340)
	at java.util.concurrent.TimeUnit.sleep(TimeUnit.java:360)
	at com.hazelcast.test.HazelcastTestSupport.sleepMillis(HazelcastTestSupport.java:280)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:883)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:889)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest.testListenersInternal(AbstractListenersOnReconnectTest.java:72)
	at com.hazelcast.client.listeners.AbstractListenersOnReconnectTest.testListenersSmartRouting(AbstractListenersOnReconnectTest.java:108)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:88)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:82)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.lang.Thread.run(Thread.java:745)
```

https://hazelcast-l337.ci.cloudbees.com/view/Zing/job/Hazelcast-3.x-ZingJDK7/35/testReport/junit/com.hazelcast.client.listeners/MultiMapEntryListenerOnReconnectTest/testListenersSmartRouting/

**Comment by cangencer** [comment]
closing issue, for explanation see: https://github.com/hazelcast/hazelcast/issues/8244#issuecomment-233323820
