### ISSUE TITLE
ClientMapTest.testAsyncPutWithTtl

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#8334]
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.client.map.ClientMapTest.testAsyncPutWithTtl(ClientMapTest.java:294)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK1.8/com.hazelcast$hazelcast-client/245/testReport/junit/com.hazelcast.client.map/ClientMapTest/testAsyncPutWithTtl/

**Comment by ahmetmircik** [comment]
should be fixed via https://github.com/hazelcast/hazelcast/commit/1d5af3f895c5ef0ab990c3af84d5f5c39745ab4b
