### ISSUE TITLE
WriteBehindFlushTest.testWriteBehindQueues_flushed_onNodeShutdown

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#8336]
```
java.lang.AssertionError: expected:<1000> but was:<1001>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.map.impl.mapstore.writebehind.WriteBehindFlushTest$1.run(WriteBehindFlushTest.java:74)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:884)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:898)
	at com.hazelcast.map.impl.mapstore.writebehind.WriteBehindFlushTest.testWriteBehindQueues_flushed_onNodeShutdown(WriteBehindFlushTest.java:71)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-ZuluJDK7/com.hazelcast$hazelcast/227/testReport/junit/com.hazelcast.map.impl.mapstore.writebehind/WriteBehindFlushTest/testWriteBehindQueues_flushed_onNodeShutdown/

**Comment by ahmetmircik** [comment]
should be fixed by https://github.com/hazelcast/hazelcast/commit/5af7fb3836a26085752cdb8edc2078f644808cf5
