### ISSUE TITLE
ExecutorServiceTest.testExecutorServiceStats_whenStatsAreDisabled & testExecutorServiceStats

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#8342]
```
java.lang.AssertionError: CountDownLatch failed to complete within 120 seconds , count left: 7
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:791)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:784)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:776)
	at com.hazelcast.executor.ExecutorServiceTest.executeTasksForStats(ExecutorServiceTest.java:960)
	at com.hazelcast.executor.ExecutorServiceTest.testExecutorServiceStats_whenStatsAreDisabled(ExecutorServiceTest.java:935)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-ZuluJDK8/com.hazelcast$hazelcast/228/testReport/junit/com.hazelcast.executor/ExecutorServiceTest/testExecutorServiceStats_whenStatsAreDisabled/

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-OracleJDK1.7/com.hazelcast$hazelcast/505/testReport/junit/com.hazelcast.executor/ExecutorServiceTest/testExecutorServiceStats_whenStatsAreDisabled/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: CountDownLatch failed to complete within 120 seconds , count left: 10
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:791)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:784)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:776)
	at com.hazelcast.executor.ExecutorServiceTest.executeTasksForStats(ExecutorServiceTest.java:960)
	at com.hazelcast.executor.ExecutorServiceTest.testExecutorServiceStats(ExecutorServiceTest.java:925)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x/com.hazelcast$hazelcast/5232/testReport/junit/com.hazelcast.executor/ExecutorServiceTest/testExecutorServiceStats/
