### ISSUE TITLE
MapStoreTest.testMapStoreWriteRemoveOrder

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#8349]
```
java.lang.AssertionError: expected:<0> but was:<1>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.map.impl.mapstore.MapStoreTest.testMapStoreWriteRemoveOrder(MapStoreTest.java:953)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-OracleJDK1.7/com.hazelcast$hazelcast/506/testReport/junit/com.hazelcast.map.impl.mapstore/MapStoreTest/testMapStoreWriteRemoveOrder/

**Comment by ahmetmircik** [comment]
closed via https://github.com/hazelcast/hazelcast/commit/f3174884eeac0af05d3dd81dae3b665e54c7a37f
