### ISSUE TITLE
GracefulShutdownTest.shutdownMultipleMembers_withPartitionInitialization/

### ISSUE THREAD

**Issue by metanet** [hazelcast/hazelcast#8450]
```
Error Message

test timed out after 120000 milliseconds
Stacktrace

java.lang.AssertionError: CountDownLatch failed to complete within 120 seconds , count left: 3
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:791)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:784)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:776)
	at com.hazelcast.internal.partition.GracefulShutdownTest.shutdownMultipleMembers(GracefulShutdownTest.java:246)
	at com.hazelcast.internal.partition.GracefulShutdownTest.shutdownMultipleMembers_withPartitionInitialization(GracefulShutdownTest.java:224)
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast%24hazelcast/953/testReport/junit/com.hazelcast.internal.partition/GracefulShutdownTest/shutdownMultipleMembers_withPartitionInitialization/

**Comment by metanet** [comment]
Reason of the failure is a long system pause during the test. We can see many clock jump logs as following:

```
04:28:23,214  INFO - [ClusterHeartbeatManager] hz._hzInstance_2590_dev.cached.thread-25 - [127.0.0.1]:7578 [dev] [3.7-SNAPSHOT] System clock apparently jumped from 2016-06-27 04:27:14.237 to 2016-06-27 04:28:23.214 since last heartbeat (+63977 ms)
04:28:36,201  INFO - [ClusterHeartbeatManager] hz._hzInstance_2632_dev.cached.thread-4 - [127.0.0.1]:7620 [dev] [3.7-SNAPSHOT] System clock apparently jumped from 2016-06-27 04:27:58.275 to 2016-06-27 04:28:36.201 since last heartbeat (+32926 ms)
04:28:44,213  INFO - [ClusterHeartbeatManager] hz._hzInstance_2610_dev.cached.thread-2 - [127.0.0.1]:7598 [dev] [3.7-SNAPSHOT] System clock apparently jumped from 2016-06-27 04:27:13.254 to 2016-06-27 04:28:44.212 since last heartbeat (+85958 ms)
``` and a few more

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: CountDownLatch failed to complete within 120 seconds , count left: 3
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:808)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:801)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:793)
	at com.hazelcast.internal.partition.GracefulShutdownTest.shutdownMultipleMembers(GracefulShutdownTest.java:246)
	at com.hazelcast.internal.partition.GracefulShutdownTest.shutdownMultipleSlaveMembers_withPartitionInitialization(GracefulShutdownTest.java:219)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-ZuluJDK6/274/

**Comment by metanet** [comment]
I checked the logs and we have the same failure again... Closing this one.
