### ISSUE TITLE
ClientQueueTest.testOfferPoll

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#8452]
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.client.queue.ClientQueueTest.testOfferPoll(ClientQueueTest.java:589)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.maintenance-IbmJDK1.7/com.hazelcast$hazelcast-client/399/testReport/junit/com.hazelcast.client.queue/ClientQueueTest/testOfferPoll/

**Comment by gurbuzali** [comment]
fixes via https://github.com/hazelcast/hazelcast/commit/eaea5677a3b5c701e89622024682914bd1f787ae
