### ISSUE TITLE
MapLoaderFailoverTest.testDoesntLoadAgain_whenLoaderNodeGoesDown

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#8453]
```
java.lang.AssertionError: expected:<1> but was:<2>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:834)
    at org.junit.Assert.assertEquals(Assert.java:645)
    at org.junit.Assert.assertEquals(Assert.java:631)
    at com.hazelcast.map.impl.mapstore.MapLoaderFailoverTest.testDoesntLoadAgain_whenLoaderNodeGoesDown(MapLoaderFailoverTest.java:76)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-ZuluJDK7/com.hazelcast$hazelcast/246/testReport/junit/com.hazelcast.map.impl.mapstore/MapLoaderFailoverTest/testDoesntLoadAgain_whenLoaderNodeGoesDown/

**Comment by hasancelik** [comment]
**maintenance**
```
java.lang.AssertionError: expected:<1> but was:<2>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.map.impl.mapstore.MapLoaderFailoverTest.testDoesntLoadAgain_whenLoaderNodeGoesDown(MapLoaderFailoverTest.java:78)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-IbmJDK1.7/com.hazelcast$hazelcast/410/testReport/junit/com.hazelcast.map.impl.mapstore/MapLoaderFailoverTest/testDoesntLoadAgain_whenLoaderNodeGoesDown/

**Comment by tombujok** [comment]
Fixed via https://github.com/hazelcast/hazelcast/pull/9569
