### ISSUE TITLE
QueryIndexPerformanceTest.testRangeIndexPerformance

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#8460]
```
java.lang.AssertionError: withIndex: 658375368 nanos, withoutIndex: 1259442345 nanos
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.map.impl.query.QueryIndexPerformanceTest.testIndexPerformance(QueryIndexPerformanceTest.java:66)
	at com.hazelcast.map.impl.query.QueryIndexPerformanceTest.testRangeIndexPerformance(QueryIndexPerformanceTest.java:59)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-ZuluJDK6/com.hazelcast$hazelcast/247/testReport/junit/com.hazelcast.map.impl.query/QueryIndexPerformanceTest/testRangeIndexPerformance/

**Comment by mdogan** [comment]
I've cleaned up and renamed QuerySlowTest to QueryIndexPerformanceTest with #8439 but I think we should remove this test completely. 
Because it's not testing correctness, it's just comparing query performance with and without using indexes.

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: withIndex: 611007942 nanos, withoutIndex: 552824258 nanos
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.map.impl.query.QueryIndexPerformanceTest.testIndexPerformance(QueryIndexPerformanceTest.java:66)
	at com.hazelcast.map.impl.query.QueryIndexPerformanceTest.testRangeIndexPerformance(QueryIndexPerformanceTest.java:59)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK8/com.hazelcast$hazelcast/889/testReport/junit/com.hazelcast.map.impl.query/QueryIndexPerformanceTest/testRangeIndexPerformance/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: withIndex: 724319168 nanos, withoutIndex: 284221893 nanos
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.map.impl.query.QueryIndexPerformanceTest.testIndexPerformance(QueryIndexPerformanceTest.java:66)
	at com.hazelcast.map.impl.query.QueryIndexPerformanceTest.testRangeIndexPerformance(QueryIndexPerformanceTest.java:59)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-OracleJDK1.7/com.hazelcast$hazelcast/569/testReport/junit/com.hazelcast.map.impl.query/QueryIndexPerformanceTest/testRangeIndexPerformance/

**Comment by mdogan** [comment]
`QueryIndexPerformanceTest` is not a real test but just trying to compare perf of indexed vs non-indexed queries. I think we should delete this test.
