### ISSUE TITLE
NPE at HazelcastTimeStamper.getNextTimeStamp

### ISSUE THREAD

**Issue by Michael-S-Smith** [hazelcast/hazelcast#8465]
Seeing the following error in my logs in a 2 node Hazelcast cluster when I attempt to being a Hibernate session from within a threads run method. This does not occur in other areas of the application. Is there any reason the AbstractHazelcastCacheRegionFactory would have a null instance here? Something about the thread?

java.lang.NullPointerException
	at com.hazelcast.hibernate.HazelcastTimestamper.nextTimestamp(HazelcastTimestamper.java:38)
	at com.hazelcast.hibernate.AbstractHazelcastCacheRegionFactory.nextTimestamp(AbstractHazelcastCacheRegionFactory.java:81)
	at org.hibernate.internal.SessionFactoryImpl$SessionBuilderImpl.openSession(SessionFactoryImpl.java:1589)
	at org.hibernate.internal.SessionFactoryImpl.openSession(SessionFactoryImpl.java:999)

**Comment by emrahkocaman** [comment]
Moving this issue to "hazelcast-hibernate" repository. Please follow https://github.com/hazelcast/hazelcast-hibernate/issues/11
