### ISSUE TITLE
PartitionReplicaStateCheckerTest.shouldNotBeSafe_whenUnknownReplicaOwnerPresent_whileNotActive & shouldBeSafe_whenKnownReplicaOwnerPresent_whileNotActive

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#8471]
```
java.lang.AssertionError: expected:<SAFE> but was:<REPLICA_NOT_SYNC>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:834)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:144)
    at com.hazelcast.internal.partition.impl.PartitionReplicaStateCheckerTest.shouldNotBeSafe_whenUnknownReplicaOwnerPresent_whileNotActive(PartitionReplicaStateCheckerTest.java:157)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-ZuluJDK8/com.hazelcast$hazelcast/250/testReport/junit/com.hazelcast.internal.partition.impl/PartitionReplicaStateCheckerTest/shouldNotBeSafe_whenUnknownReplicaOwnerPresent_whileNotActive/

**Comment by mdogan** [comment]
Improved code to be able to understand real cause of failure (with PR #8476). Closing for now. If it fails again, we'll be able to see which path exactly caused.

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: expected:<SAFE> but was:<REPLICA_NOT_OWNED>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.internal.partition.impl.PartitionReplicaStateCheckerTest.shouldNotBeSafe_whenUnknownReplicaOwnerPresent_whileNotActive(PartitionReplicaStateCheckerTest.java:165)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast$hazelcast/1018/testReport/junit/com.hazelcast.internal.partition.impl/PartitionReplicaStateCheckerTest/shouldNotBeSafe_whenUnknownReplicaOwnerPresent_whileNotActive/

**Comment by hasancelik** [comment]
**shouldBeSafe_whenKnownReplicaOwnerPresent_whileNotActive**
```
java.lang.AssertionError: expected:<SAFE> but was:<REPLICA_NOT_OWNED>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.internal.partition.impl.PartitionReplicaStateCheckerTest.shouldBeSafe_whenKnownReplicaOwnerPresent_whileNotActive(PartitionReplicaStateCheckerTest.java:134)
```
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK1.7/com.hazelcast$hazelcast/632/testReport/junit/com.hazelcast.internal.partition.impl/PartitionReplicaStateCheckerTest/shouldBeSafe_whenKnownReplicaOwnerPresent_whileNotActive/

**Comment by mdogan** [comment]
Not failing since [Oct 10](https://github.com/hazelcast/hazelcast/issues/8471#issuecomment-252553914). Please re-open if fails again.
