### ISSUE TITLE
TimeoutException in getMap()

### ISSUE THREAD

**Issue by jasoncarreira** [hazelcast/hazelcast#8496]
I just started getting this exception at startup:

    java.util.concurrent.TimeoutException: Call Invocation{ serviceName='hz:impl:mapService', op=com.hazelcast.map.impl.operation.PartitionCheckIfLoadedOperation{identityHash=327916222, serviceName='null', partitionId=157, callId=9223372036854775807, invocationTime=1467668300586, waitTimeout=-1, callTimeout=60000}, partitionId=157, replicaIndex=0, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeout=60000, target=Address[192.168.0.9]:5701, backupsExpected=0, backupsCompleted=0} encountered a timeout
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveApplicationResponse(InvocationFuture.java:366) ~[hazelcast-3.5.5.jar:3.5.5]
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveApplicationResponseOrThrowException(InvocationFuture.java:334) ~[hazelcast-3.5.5.jar:3.5.5]
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.get(InvocationFuture.java:225) ~[hazelcast-3.5.5.jar:3.5.5]
	at com.hazelcast.util.FutureUtil.executeWithDeadline(FutureUtil.java:294) [hazelcast-3.5.5.jar:3.5.5]
	at com.hazelcast.util.FutureUtil.waitWithDeadline(FutureUtil.java:278) [hazelcast-3.5.5.jar:3.5.5]
	at com.hazelcast.util.FutureUtil.waitWithDeadline(FutureUtil.java:252) [hazelcast-3.5.5.jar:3.5.5]
	at com.hazelcast.map.impl.proxy.MapProxySupport.waitUntilLoaded(MapProxySupport.java:681) [hazelcast-3.5.5.jar:3.5.5]
	at com.hazelcast.map.impl.proxy.MapProxyImpl.waitUntilLoaded(MapProxyImpl.java:71) [hazelcast-3.5.5.jar:3.5.5]
	at com.hazelcast.map.impl.proxy.MapProxySupport.initializeMapStoreLoad(MapProxySupport.java:182) [hazelcast-3.5.5.jar:3.5.5]
	at com.hazelcast.map.impl.proxy.MapProxySupport.initialize(MapProxySupport.java:174) [hazelcast-3.5.5.jar:3.5.5]
	at com.hazelcast.map.impl.proxy.MapProxyImpl.initialize(MapProxyImpl.java:71) [hazelcast-3.5.5.jar:3.5.5]
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyRegistry.doCreateProxy(ProxyRegistry.java:181) [hazelcast-3.5.5.jar:3.5.5]
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyRegistry.createProxy(ProxyRegistry.java:171) [hazelcast-3.5.5.jar:3.5.5]
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyRegistry.getOrCreateProxy(ProxyRegistry.java:140) [hazelcast-3.5.5.jar:3.5.5]
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyServiceImpl.getDistributedObject(ProxyServiceImpl.java:119) [hazelcast-3.5.5.jar:3.5.5]
	at com.hazelcast.instance.HazelcastInstanceImpl.getDistributedObject(HazelcastInstanceImpl.java:390) [hazelcast-3.5.5.jar:3.5.5]
	at com.hazelcast.instance.HazelcastInstanceImpl.getMap(HazelcastInstanceImpl.java:192) [hazelcast-3.5.5.jar:3.5.5]
	at com.hazelcast.instance.HazelcastInstanceProxy.getMap(HazelcastInstanceProxy.java:75) [hazelcast-3.5.5.jar:3.5.5]
	at com.ppi.api.service.BaseService.getMap(BaseService.java:109) [classes/:na]
	at com.ppi.api.service.OrgStructureService.init(OrgStructureService.java:30) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_92]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_92]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_92]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_92]

It's coming from a service I have that has a @PostConstruct method to initialize:

    @Component
    public class OrgStructureService implements MapListener, EntryAddedListener<String, Organization>, EntryRemovedListener<String, Organization>,
        EntryUpdatedListener<String, Organization>, MapClearedListener {

    public static final String ORG_STRUCTURE_MAP = "org-structure";

    private String listenerRegistration;

    @Autowired
    HazelcastInstance hazelcastInstance;

    @Autowired
    OrganizationService organizationService;

    @PostConstruct
    public void init() {
        IMap<String, Organization> organizationMap = organizationService.getMap();
        listenerRegistration = organizationMap.addLocalEntryListener(this);
     }

It's dying on getMap() in the init() method.

**Comment by tombujok** [comment]
It looks like you're using a MapLoader configured to EAGER to load the map on construction. 
It may take significant amount of time and this operation is blocking. In this case you got a timeout.
As I understand it, you started getting this exception now and nothing changed in your config.
It may happen due to the fact that you have more data in your DB than some time ago.

Plz try checking with HZ 3.6.4 and let me know if it helped.

**Comment by jasoncarreira** [comment]
Ah, that makes sense. 3.6.4 didn't help. FYI my dependency was on hazelcast-spring 3.6.3 and it still pointed at hazelcast 3.5.5, as does 3.6.4. I've explicitly put a dependency for hazelcast 3.6.4 and no change.

So is there a good way to queue this to run after the loading is done? Does HZ have an internal task queue I could run something on? I looked at the LifecycleListener but I wasn't sure if I'd end up with a race condition for it running when HZ gets to LifecycleEvent.STARTED.

**Comment by jasoncarreira** [comment]
I found the problem. Spring was looking for a transaction manager for my JPAMapStore and hanging because it couldn't find one when it went to call loadAllKeys(). Thanks for your help!

**Comment by tombujok** [comment]
No prob! Glad you found it.

**Comment by pasikon** [comment]
Hi @jasoncarreira , had the same problem. How have you found out that Spring was looking for transaction manager?

**Comment by jasoncarreira** [comment]
I forget.. setting breakpoints in there to see what Spring was hanging on. I just set up a bean for it like this:

```
@Bean(name = "hazelCastTransactionManager")
    public PlatformTransactionManager getHazelCastTransactionManager(HazelcastInstance hazelcastInstance) {
        return new HazelcastTransactionManager(hazelcastInstance);
    }
```

and then used it in my services:

```
@Transactional("hazelCastTransactionManager")
public abstract class BaseService
```

**Comment by pasikon** [comment]
Thank you!

2016-10-14 22:07 GMT+02:00 Jason Carreira <notifications@github.com>:
