### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by manchuwook** [hazelcast/hazelcast#8503]
Windows 7x64 Professional Service Pack 1

```
java version "1.8.0_11"
Java(TM) SE Runtime Environment (build 1.8.0_11-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.11-b03, mixed mode)
```

```
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T10:41:47-06:00)
Maven home: c:\tools\apache-maven-3.3.9
Java version: 1.8.0_05, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.8.0_05\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "dos"
```

```
Results :

Failed tests:
  SystemLogPluginTest.testLifecycle:43->HazelcastTestSupport.assertTrueEventually:914->HazelcastTestSupport.assertTrueEventually:900->AbstractDiagnosticsPluginTest.assertContains:18 '' doesn't contains 'Lifecycle[SHUTTING_DOWN]'
  OperatingSystemMetricSetTest.testSunManagementOperatingSystemImpl:76->assertContainsSensor:85 sensor:os.maxFileDescriptorCount is not found
  DiscoverySpiTest.test_AbstractDiscoveryStrategy_getOrNull:251 expected:<true> but was:<false>
Tests in error:
  QueueAdvancedTest.testOffer:70 NoSuchMethod com.hazelcast.core.IQueue.offer(Lj...
  QueueAdvancedTest.testOfferLong:324 NoSuchMethod com.hazelcast.core.IQueue.off...
  QueueAdvancedTest.testShutdown:159 NoSuchMethod com.hazelcast.core.IQueue.offe...

Tests run: 12359, Failures: 3, Errors: 3, Skipped: 167

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Hazelcast Root ..................................... SUCCESS [  3.003 s]
[INFO] hazelcast .......................................... FAILURE [  01:05 h]
[INFO] hazelcast-client ................................... SKIPPED
[INFO] hazelcast-spring ................................... SKIPPED
[INFO] hazelcast-build-utils .............................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:05 h
[INFO] Finished at: 2016-07-08T10:21:19-05:00
[INFO] Final Memory: 41M/471M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project hazelcast: There are test failures.
[ERROR]
[ERROR] Please refer to C:\dev\hazelcast-3.7\hazelcast\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :hazelcast
```

Advice?

**Comment by tombujok** [comment]
Due to the distributed manner of some tests, complexity of the test code and some poorly written tests that we constantly try to improve the mvn test phase may fail nondeterministically.  
In order to proceed restart the build.

**Comment by TheBellman** [comment]
I notice I am having the same problem, and it fails consistently. I've pulled the code into my IDE, and running _QueueAdvancedTest.testOffer()_ it is consistently upset about 

    assertTrue("Expected q1.offer() to succeed", q1.offer("item" + i, 100, SECONDS));

throwing 

    java.lang.NoSuchMethodError:  com.hazelcast.core.IQueue.offer(Ljava/lang/String;JLjava/util/concurrent/TimeUnit;)Z
	  at com.hazelcast.collection.impl.queue.QueueAdvancedTest.testOffer(QueueAdvancedTest.java:70)
	  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
          ....

building with 1.8.0_51 on a Mac, from within IntelliJ 15 

Interestingly 

    assertTrue("Expected q1.offer() to succeed", q1.offer("item" + i));

goes through, so there is genuinely something wonky around the actual class implementation the test is receiving at this point.

**Comment by TheBellman** [comment]
Ok, for anyone else stumbling across this when looking for the resolution, looks like this only happens with java 8. Switching the test build to use java 7 worked ok, and this appears to be related to http://blog.hazelcast.com/story-of-a-java-8-compiler-bug-jdk-8064803-3/
