### ISSUE TITLE
TransactionException when using Hazelcast Client and Transaction Context

### ISSUE THREAD

**Issue by juanavelez** [hazelcast/hazelcast#8507]
We are performing some tests using Hazelcast 3.6.4 and Transactions. Our setup consists of 4 nodes with two partition groups each of 2 nodes. We have a hazelcast client that gets a transactional map and inserts 1000 records at a time before committing. In one of our tests after successfully "putting" 50K+ entries, when one of the nodes (hc4.dev.xxx.com) was killed, we got the following exception

```
Jul 11, 2016 10:48:20 AM com.hazelcast.client.connection.nio.ClientConnection
WARNING: Connection [hc4.dev.xxx.com/172.16.100.25:5701] lost. Reason: java.io.EOFException[Remote socket closed!]
Jul 11, 2016 10:48:21 AM com.hazelcast.client.spi.impl.ClientMembershipListener
INFO: 

Members [3] {
	Member [hc1.dev.xxx.com]:5701
	Member [hc2.dev.xxx.com]:5701
	Member [hc3.dev.xxx.com]:5701
}

Exception in thread "main" com.hazelcast.transaction.TransactionException: Lock is not owned by the transaction! [<not-locked>]
	at com.hazelcast.map.impl.tx.TxnPrepareOperation.run(TxnPrepareOperation.java:54)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:172)
	at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.processOperation(OperationThread.java:198)
	at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.process(OperationThread.java:132)
	at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.doRun(OperationThread.java:124)
	at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.run(OperationThread.java:99)
	at ------ End remote and begin local stack-trace ------.(Unknown Source)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveResponse(ClientInvocationFuture.java:128)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.get(ClientInvocationFuture.java:95)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.get(ClientInvocationFuture.java:74)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.get(ClientInvocationFuture.java:37)
	at com.hazelcast.client.proxy.txn.TransactionProxy.invoke(TransactionProxy.java:149)
	at com.hazelcast.client.proxy.txn.TransactionProxy.commit(TransactionProxy.java:101)
	at com.hazelcast.client.proxy.txn.TransactionContextProxy.commitTransaction(TransactionContextProxy.java:77)
	at com.xxx.test.hazelcast.main.GettingStartedClient.main(GettingStartedClient.java:55)
```
This is the code
```
      ClientConfig clientConfig = new ClientConfig();
      ClientNetworkConfig networkConfig = new ClientNetworkConfig();
      networkConfig.setSmartRouting(true);
      String[] addresses = { "hc1.dev.xxx.com" , "hc2.dev.xxx.com" , "hc3.dev.xxx.com" , "hc4.dev.xxx.com" };
      networkConfig.setAddresses(Arrays.asList(addresses));
      clientConfig.setNetworkConfig(networkConfig);
      final HazelcastInstance client = HazelcastClient.newHazelcastClient( clientConfig );
      IMap<Integer, String> customersMap = client.getMap( "customers" );
      TransactionContext txCtx = client.newTransactionContext();
      boolean txActive = true;
      txCtx.beginTransaction();
      TransactionalMap<Integer, String> customersTxMap = txCtx.getMap( "customers" );
      System.out.println( "Starting putting " + Integer.MAX_VALUE + " entries. " + new Date());
      for (int i=1; i<Integer.MAX_VALUE; i++) {
          customersTxMap.put( new Integer(i), new Integer(i).toString() );
          if (i%1000==0) {
              if ( txActive ) {
                 txCtx.commitTransaction();
                 txActive = false;
                 System.out.println( "TxCommitted. " + new Date());
                 System.out.println( "Retrieving size for customers map. " + new Date());
                 System.out.println( "Size=" + customersMap.size() + ". " + new Date());
              }
              txCtx.beginTransaction();
              txActive = true;
              System.out.println("Put " + i + " entries so far. " + new Date());
          }
      }
      if ( txActive ) {
          txCtx.commitTransaction();
          System.out.println( "TxCommitted. " + new Date());
      }
```
The customers map is using backup-count=0 and async-backup-count=1.
```
    <map name="customers">
        <!--
           Data type that will be used for storing recordMap.
           Possible values:
           BINARY (default): keys and values will be stored as binary data
           OBJECT : values will be stored in their object forms
           NATIVE : values will be stored in non-heap region of JVM
        -->
        <in-memory-format>BINARY</in-memory-format>

        <!--
            Number of backups. If 1 is set as the backup-count for example,
            then all entries of the map will be copied to another JVM for
            fail-safety. 0 means no backup.
        -->
        <backup-count>0</backup-count>
        <!--
            Number of async backups. 0 means no backup.
        -->
        <async-backup-count>1</async-backup-count>
```

The line of code that fails is

```
                 txCtx.commitTransaction();
```
The hazelcast.xml config is the default one but using tcp-ip for join and enabling partition groups

```
        <join>
            <multicast enabled="false">
                <multicast-group>224.2.2.3</multicast-group>
                <multicast-port>54327</multicast-port>
            </multicast>
            <tcp-ip enabled="true">
                <member-list>
                    <member>hc1.dev.xxx.com</member>
                    <member>hc2.dev.xxx.com</member>
                    <member>hc3.dev.xxx.com</member>
                    <member>hc4.dev.xxx.com</member>
                </member-list>
            </tcp-ip>

    <partition-group enabled="false" group-type="CUSTOM">
        <member-group>
            <interface>hc1.dev.xxx.com</interface>
            <interface>hc2.dev.xxx.com</interface>
        </member-group>
        <member-group>
            <interface>hc3.dev.xxx.com</interface>
            <interface>hc4.dev.xxx.com</interface>
        </member-group>
    </partition-group>
```

We think we should not be getting this exception.

**Comment by gurbuzali** [comment]
Hi,

Hazelcast obtains a lock when you do a `put` inside the transaction and does the actual put while committing. There is a phase which is called `prepare` phase before the `commit` phase. At this phase hazelcast extends the already obtained lock. If the owner of the lock goes down before the prepare phase then it is expected that an exception will be thrown for the user to rollback the transaction. At this state, transaction does not have the lock, another thread/transaction may have acquired the lock. So rollback and restart the transaction is the way to go here.
