### ISSUE TITLE
Apache Storm Error not able to submit topology on Localcluster

### ISSUE THREAD

**Issue by imvipul** [hazelcast/hazelcast#8534]
I am using latest version of storm with below jars.

storm-core-1.0.1
storm-kafka-1.0.1
zookeeper-3.4.8
kafka_2.10-0.9.0.1
It is working fine with > storm-core-0.9.3 but throwing error with latest version of storm.

Exception in thread "main" java.lang.IllegalAccessError: tried to access method clojure.lang.RT.classForNameNonLoading(Ljava/lang/String;)Ljava/lang/Class; from class org.apache.storm.daemon.nimbus$loading__5340__auto____6155 at org.apache.storm.daemon.nimbus$loading__5340__auto____6155.invoke(nimbus.clj:16) at org.apache.storm.daemon.nimbus__init.load(Unknown Source) at org.apache.storm.daemon.nimbus__init.(Unknown Source) at java.lang.Class.forName0(Native Method) at java.lang.Class.forName(Class.java:348) at clojure.lang.RT.loadClassForName(RT.java:2093) at clojure.lang.RT.load(RT.java:430) at clojure.lang.RT.load(RT.java:411) at clojure.core$load$fn__5066.invoke(core.clj:5641) at clojure.core$load.doInvoke(core.clj:5640) at clojure.lang.RestFn.invoke(RestFn.java:408) at clojure.core$load_one.invoke(core.clj:5446) at clojure.core$load_lib$fn__5015.invoke(core.clj:5486) at clojure.core$load_lib.doInvoke(core.clj:5485) at clojure.lang.RestFn.applyTo(RestFn.java:142) at clojure.core$apply.invoke(core.clj:626) at clojure.core$load_libs.doInvoke(core.clj:5528) at clojure.lang.RestFn.applyTo(RestFn.java:137) at clojure.core$apply.invoke(core.clj:626) at clojure.core$require.doInvoke(core.clj:5607) at clojure.lang.RestFn.invoke(RestFn.java:408) at org.apache.storm.testing$loading__5340__auto____6153.invoke(testing.clj:17) at org.apache.storm.testing__init.load(Unknown Source) at org.apache.storm.testing__init.(Unknown Source) at java.lang.Class.forName0(Native Method) at java.lang.Class.forName(Class.java:348) at clojure.lang.RT.loadClassForName(RT.java:2093) at clojure.lang.RT.load(RT.java:430) at clojure.lang.RT.load(RT.java:411) at clojure.core$load$fn__5066.invoke(core.clj:5641) at clojure.core$load.doInvoke(core.clj:5640) at clojure.lang.RestFn.invoke(RestFn.java:408) at clojure.core$load_one.invoke(core.clj:5446) at clojure.core$load_lib$fn__5015.invoke(core.clj:5486) at clojure.core$load_lib.doInvoke(core.clj:5485) at clojure.lang.RestFn.applyTo(RestFn.java:142) at clojure.core$apply.invoke(core.clj:626) at clojure.core$load_libs.doInvoke(core.clj:5528) at clojure.lang.RestFn.applyTo(RestFn.java:137) at clojure.core$apply.invoke(core.clj:628) at clojure.core$use.doInvoke(core.clj:5618) at clojure.lang.RestFn.invoke(RestFn.java:408) at org.apache.storm.LocalCluster$loading__5340__auto____6151.invoke(LocalCluster.clj:17) at org.apache.storm.LocalCluster__init.load(Unknown Source) at org.apache.storm.LocalCluster__init.(Unknown Source) at java.lang.Class.forName0(Native Method) at java.lang.Class.forName(Class.java:348) at clojure.lang.RT.loadClassForName(RT.java:2093) at clojure.lang.RT.load(RT.java:430) at clojure.lang.RT.load(RT.java:411) at clojure.core$load$fn__5066.invoke(core.clj:5641) at clojure.core$load.doInvoke(core.clj:5640) at clojure.lang.RestFn.invoke(RestFn.java:408) at clojure.lang.Var.invoke(Var.java:379) at org.apache.storm.LocalCluster.(Unknown Source)

**Comment by jerrinot** [comment]
@imvipul: HI, I believe this does not belong to this project. I do not know what's your use-case, but feel free to try Hazelcast. I promise we have more readable stacktraces! :)))

**Comment by imvipul** [comment]
wrong window
