### ISSUE TITLE
HazelCast OSGI classloader issue NOsuchMethodException

### ISSUE THREAD

**Issue by jmavasa** [hazelcast/hazelcast#8573]
I am trying to  run Hazel Cast inside OSGI  when running hazelcast I get this error 

com.hazelcast.core.HazelcastException: java.lang.NoSuchMethodException: com.hazelcast.instance.DefaultNodeExtension.<init>(com.hazelcast.instance.Node)
    at com.hazelcast.util.ExceptionUtil.peel(ExceptionUtil.java:73)
    at com.hazelcast.util.ExceptionUtil.peel(ExceptionUtil.java:52)
    at com.hazelcast.util.ExceptionUtil.rethrow(ExceptionUtil.java:83)
    at com.hazelcast.instance.NodeExtensionFactory.create(NodeExtensionFactory.java:45)
    at com.hazelcast.instance.DefaultNodeContext.createNodeExtension(DefaultNodeContext.java:33)
    at com.hazelcast.instance.Node.<init>(Node.java:170)
    at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:125)
    at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:160)
    at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:143)
    at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:111)
    at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:58)
    at com.agentslab.datAdmcore.HazelStarter.start(HazelStarter.java:114)
    at com.agentslab.ame.protege.core.UnderSubMenu.actionPerformed(UnderSubMenu.java:22)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
    at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
    at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
    at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
    at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
    at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
    at java.awt.Component.processMouseEvent(Component.java:6535)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
    at java.awt.Component.processEvent(Component.java:6300)
    at java.awt.Container.processEvent(Container.java:2236)
    at java.awt.Component.dispatchEventImpl(Component.java:4891)
    at java.awt.Container.dispatchEventImpl(Container.java:2294)
    at java.awt.Component.dispatchEvent(Component.java:4713)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
    at java.awt.Container.dispatchEventImpl(Container.java:2280)
    at java.awt.Window.dispatchEventImpl(Window.java:2750)
    at java.awt.Component.dispatchEvent(Component.java:4713)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.awt.EventQueue$4.run(EventQueue.java:731)
    at java.awt.EventQueue$4.run(EventQueue.java:729)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.NoSuchMethodException: com.hazelcast.instance.DefaultNodeExtension.<init>(com.hazelcast.instance.Node)
    at java.lang.Class.getConstructor0(Class.java:3082)
    at java.lang.Class.getDeclaredConstructor(Class.java:2178)
    at com.hazelcast.instance.NodeExtensionFactory.create(NodeExtensionFactory.java:39)
    ... 48 more
when I run this outside the OSGI it runs and only has one classloader, inside the OSGI it shows two class loaders the other being a bundewiringimp bundleclass loader with the name of the OSGI.
any idea of what is causing this error

**Comment by jerrinot** [comment]
Hi @jmavasa, 

thanks for reporting the issue. What version of HAzelcast are you using? What OSGi container you are using? Do you have any idea why there are 2 classloaders? Are you sure you have just a single bundle with Hazelcast?

**Comment by jmavasa** [comment]
Hi Jerrinot,

Thanks for getting back to me, I am using hazelcast 3.6. I have created a Custom OSGI bundle using Apache Felix.I have a jar that contains my hazelcast code as a dependency and all the hazelcast dependency setup in the OSGI . Before bundling when I run the one class loader Laucher$AppClassLoader. Running in the OSGI I have two the Laucher$AppClassLoader and  Bundewiringimp$BundleclassLoaderJava and so in the NodeExtension create method of the NodeExtensionFactory it fails to create a constructor when iterating with the error above.
while(iter.hasNext()) {
                Class clazz = (Class)iter.next();
                if(!clazz.equals(DefaultNodeExtension.class)) {
                    **Constructor constructor = clazz.getDeclaredConstructor(new Class[]{Node.class});**
                    return (NodeExtension)constructor.newInstance(new Object[]{node});
                }
the second loader has the name of my OSGI bundle and is added as a  coreclassloader.

I have a single OSGI bundle with hazelcast. is there anything I may need to look out for.

Justice

**Comment by jerrinot** [comment]
@jmavasa: thanks for details. Can you please minimal reproducer? It would help us a lot!

**Comment by jmavasa** [comment]
Hi @jerrinot
  I will try do that. but beofre that, strangely when am debugging in NodeextensionFactory on the 
if(!clazz.equals(DefaultNodeExtension.class)) {}
the code goes into the if statement even though the class is com.hazelcast.instance.defaulNodeextension see my screen shot 
![selection_002](https://cloud.githubusercontent.com/assets/7574698/17055444/075a1f76-500d-11e6-8a7d-4b5da31f90bf.png)
can you see that

**Comment by tombujok** [comment]
Hi, could you retest with 3.6.4?
You can set the bundle classloader in HZ the configuration. I've done a fix
some time ago.

**Comment by jmavasa** [comment]
Hi @tombujok, Thank you, I managed to set the bundle class loader as the class loader of the thread loader and context loader and now works.

**Comment by tombujok** [comment]
@jmavasa cool, I'm happy that it worked!
