### ISSUE TITLE
DurableLongRunningTaskTest.test

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#8584]
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.durableexecutor.DurableLongRunningTaskTest$1.run(DurableLongRunningTaskTest.java:46)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:901)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:915)
	at com.hazelcast.durableexecutor.DurableLongRunningTaskTest.test(DurableLongRunningTaskTest.java:43)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast$hazelcast/980/testReport/junit/com.hazelcast.durableexecutor/DurableLongRunningTaskTest/test/

**Comment by gurbuzali** [comment]
I've added some logging to the test for further investigation https://github.com/hazelcast/hazelcast/commit/79f73f03faee48b17309960bb9d9af7d87ac88b7
