### ISSUE TITLE
[query] [map] QueryBasicTest Timeout Failures

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#8587]
```
org.junit.runners.model.TestTimedOutException: test timed out after 60000 milliseconds
    at org.apache.log4j.Category.callAppenders(Category.java:201)
    at org.apache.log4j.Category.forcedLog(Category.java:388)
    at org.apache.log4j.Category.log(Category.java:823)
    at com.hazelcast.logging.Log4jFactory$Log4jLogger.log(Log4jFactory.java:50)
    at com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:167)
    at com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:155)
    at com.hazelcast.logging.AbstractLogger.finest(AbstractLogger.java:30)
    at com.hazelcast.internal.diagnostics.Diagnostics.start(Diagnostics.java:183)
    at com.hazelcast.spi.impl.NodeEngineImpl.start(NodeEngineImpl.java:196)
    at com.hazelcast.instance.Node.start(Node.java:339)
    at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:132)
    at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:218)
    at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:176)
    at com.hazelcast.test.TestHazelcastInstanceFactory.newHazelcastInstance(TestHazelcastInstanceFactory.java:116)
    at com.hazelcast.test.HazelcastTestSupport.createHazelcastInstance(HazelcastTestSupport.java:140)
    at com.hazelcast.map.impl.query.QueryBasicTest.testIteratorContract(QueryBasicTest.java:164)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK1.6/981/#showFailuresLink

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK1.6/978/#showFailuresLink

**Comment by jerrinot** [comment]
There are suspicious message in the log:
```
06:10:52,268  WARN |testIteratorContract| - [InvocationMonitor] hz._hzInstance_6767_dev.InvocationMonitorThread - [127.0.0.1]:12523 [dev] [3.7-SNAPSHOT] MonitorInvocationsTask delayed 171659 ms
06:10:52,268 TRACE |testIteratorContract| - [InvocationMonitor] hz._hzInstance_6767_dev.InvocationMonitorThread - [127.0.0.1]:12523 [dev] [3.7-SNAPSHOT] Scanning all invocations
06:10:52,268  WARN |testIteratorContract| - [InvocationMonitor] hz._hzInstance_6767_dev.InvocationMonitorThread - [127.0.0.1]:12523 [dev] [3.7-SNAPSHOT] BroadcastOperationHeartbeatsTask delayed 157659 ms
06:05:26,472  INFO |testIteratorContract| - [HealthMonitor] hz._hzInstance_6767_dev.HealthMonitor - [127.0.0.1]:12523 [dev] [3.7-SNAPSHOT] processors=16, physical.memory.total=4.0G, physical.memory.free=0, swap.space.total=30.0G, swap.space.free=30.0G, heap.memory.used=765.1M, heap.memory.free=257.4M, heap.memory.total=1022.4M, heap.memory.max=1022.4M, heap.memory.used/total=74.71%, heap.memory.used/max=74.71%, minor.gc.count=2823, minor.gc.time=184226ms, major.gc.count=53, major.gc.time=49629ms, load.process=0.00%, load.system=0.00%, load.systemAverage=2725.00%, thread.count=1011, thread.peakCount=2915, cluster.timeDiff=0, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=2, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=1, proxy.count=0, clientEndpoint.count=0, connection.active.count=0, client.connection.count=0, connection.count=0
06:04:57,428  WARN |testIteratorContract| - [SlowOperationDetector] hz._hzInstance_6767_dev.SlowOperationDetectorThread - [127.0.0.1]:12523 [dev] [3.7-SNAPSHOT] Slow operation detected: com.hazelcast.map.impl.operation.PutOperation
```

**Comment by jerrinot** [comment]
this looks like environment issue to me. See the jumping timestamps in the log:
```
06:07:59,609 TRACE |testIteratorContract| - [InvocationMonitor] hz._hzInstance_6767_dev.InvocationMonitorThread - [127.0.0.1]:12523 [dev] [3.7-SNAPSHOT] Scanning all invocations
06:07:59,609 TRACE |testIteratorContract| - [InvocationMonitor] hz._hzInstance_6767_dev.InvocationMonitorThread - [127.0.0.1]:12523 [dev] [3.7-SNAPSHOT] Scanning all invocations
06:07:59,609 TRACE |testIteratorContract| - [InvocationMonitor] hz._hzInstance_6767_dev.InvocationMonitorThread - [127.0.0.1]:12523 [dev] [3.7-SNAPSHOT] Scanning all invocations
06:10:52,268  WARN |testIteratorContract| - [InvocationMonitor] hz._hzInstance_6767_dev.InvocationMonitorThread - [127.0.0.1]:12523 [dev] [3.7-SNAPSHOT] MonitorInvocationsTask delayed 171659 ms
06:10:52,268 TRACE |testIteratorContract| - [InvocationMonitor] hz._hzInstance_6767_dev.InvocationMonitorThread - [127.0.0.1]:12523 [dev] [3.7-SNAPSHOT] Scanning all invocations
06:10:52,268  WARN |testIteratorContract| - [InvocationMonitor] hz._hzInstance_6767_dev.InvocationMonitorThread - [127.0.0.1]:12523 [dev] [3.7-SNAPSHOT] BroadcastOperationHeartbeatsTask delayed 157659 ms
06:05:26,472  INFO |testIteratorContract| - [HealthMonitor] hz._hzInstance_6767_dev.HealthMonitor - [127.0.0.1]:12523 [dev] [3.7-SNAPSHOT] processors=16, physical.memory.total=4.0G, physical.memory.free=0, swap.space.total=30.0G, swap.space.free=30.0G, heap.memory.used=765.1M, heap.memory.free=257.4M, heap.memory.total=1022.4M, heap.memory.max=1022.4M, heap.memory.used/total=74.71%, heap.memory.used/max=74.71%, minor.gc.count=2823, minor.gc.time=184226ms, major.gc.count=53, major.gc.time=49629ms, load.process=0.00%, load.system=0.00%, load.systemAverage=2725.00%, thread.count=1011, thread.peakCount=2915, cluster.timeDiff=0, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=2, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=1, proxy.count=0, clientEndpoint.count=0, connection.active.count=0, client.connection.count=0, connection.count=0
```

Also: 
How could `PutOperation` possible be slow? 
`06:04:57,428  WARN |testIteratorContract| - [SlowOperationDetector] hz._hzInstance_6767_dev.SlowOperationDetectorThread - [127.0.0.1]:12523 [dev] [3.7-SNAPSHOT] Slow operation detected: com.hazelcast.map.impl.operation.PutOperation`

[...]

`06:04:46,472 TRACE |testIteratorContract| - [DefaultRecordStore] hz._hzInstance_6767_dev.partition-operation.thread-1 - [127.0.0.1]:12523 [dev] [3.7-SNAPSHOT] StartLoading invoked on partitionId=257 on [127.0.0.1]:12523 loadedOnCreate=false loadedOnPreMigration=false isLoaded=true`

`06:11:26,383  WARN |testIteratorContract| - [Invocation] hz._hzInstance_6767_dev.partition-operation.thread-1 - [127.0.0.1]:12523 [dev] [3.7-SNAPSHOT] Future.complete(Object value) can only be called once. Request: Invocation{op=com.hazelcast.map.impl.operation.PutOperation{serviceName='hz:impl:mapService', identityHash=1278202073, partitionId=257, replicaIndex=0, callId=0, invocationTime=1469156686472 (2016-07-22 06:04:46.472), waitTimeout=-1, callTimeout=60000, name=testIteratorContract}, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=60000, firstInvocationTimeMs=1469156686472, firstInvocationTime='2016-07-22 06:04:46.472', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 02:00:00.000', target=[127.0.0.1]:12523, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=null}, current value: Invocation::HEARTBEAT_TIMEOUT, offered value: null`

**Comment by jerrinot** [comment]
I date to make a conclusion this was caused by environment issues. Please try to re-open it if you see this again.

**Comment by mmedenjak** [comment]
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.7/1241/

com.hazelcast.map.impl.query.QueryBasicTest.testMultipleOrPredicatesIssue885WithIndex

```
org.junit.runners.model.TestTimedOutException: test timed out after 60000 milliseconds
	at org.apache.logging.log4j.core.appender.OutputStreamManager.flush(OutputStreamManager.java:155)
	at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.append(AbstractOutputStreamAppender.java:112)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:99)
	at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:430)
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:409)
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:412)
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:367)
	at org.apache.logging.log4j.core.Logger.logMessage(Logger.java:112)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:727)
	at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:716)
	at com.hazelcast.logging.Log4j2Factory$Log4j2Logger.log(Log4j2Factory.java:60)
	at com.hazelcast.test.TestLoggerFactory$DelegatingTestLogger.log(TestLoggerFactory.java:144)
	at com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:168)
	at com.hazelcast.logging.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:158)
	at com.hazelcast.logging.AbstractLogger.info(AbstractLogger.java:69)
	at com.hazelcast.internal.partition.impl.PartitionStateManager.initializePartitionAssignments(PartitionStateManager.java:127)
	at com.hazelcast.internal.partition.impl.InternalPartitionServiceImpl.firstArrangement(InternalPartitionServiceImpl.java:237)
	at com.hazelcast.internal.partition.impl.InternalPartitionServiceImpl.getPartitionOwner(InternalPartitionServiceImpl.java:183)
	at com.hazelcast.internal.partition.impl.InternalPartitionServiceImpl.getPartitionOwnerOrWait(InternalPartitionServiceImpl.java:197)
	at com.hazelcast.internal.partition.impl.InternalPartitionServiceImpl.getMemberPartitionsMap(InternalPartitionServiceImpl.java:887)
	at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.invokeOnAllPartitions(OperationServiceImpl.java:369)
	at com.hazelcast.map.impl.proxy.MapProxySupport.addIndex(MapProxySupport.java:1099)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.addIndex(MapProxyImpl.java:101)
	at com.hazelcast.map.impl.query.QueryBasicTest.testMultipleOrPredicatesIssue885WithIndex(QueryBasicTest.java:666)
```

com.hazelcast.map.impl.query.QueryBasicTest.com.hazelcast.map.impl.query.QueryBasicTest
```
java.lang.IllegalStateException: Instances haven't been shut down: [HazelcastInstance{name='_hzInstance_10502_dev', node=[127.0.0.1]:15791}]
	at com.hazelcast.test.AbstractHazelcastClassRunner$1.evaluate(AbstractHazelcastClassRunner.java:285)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:108)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:78)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:54)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:144)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
```

**Comment by mmedenjak** [comment]
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast$hazelcast/1239/#showFailuresLink

**Comment by mmedenjak** [comment]
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.7/1238/

**Comment by Donnerbart** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/9174/

**Comment by tombujok** [comment]
To me this is solved by environment issues. I increase the timeouts and we will see, but all the logs I browsed had some env issues & hiccups on node creation etc.
