### ISSUE TITLE
MapReduceLiteMemberTest Timeout Failures

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#8589]
```
org.junit.runners.model.TestTimedOutException: test timed out after 60000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:283)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:156)
	at com.hazelcast.map.impl.proxy.MapProxySupport.invokeOperation(MapProxySupport.java:375)
	at com.hazelcast.map.impl.proxy.MapProxySupport.putInternal(MapProxySupport.java:346)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.put(MapProxyImpl.java:109)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.put(MapProxyImpl.java:99)
	at com.hazelcast.mapreduce.MapReduceLiteMemberTest.populateMapAndCreateJob(MapReduceLiteMemberTest.java:258)
	at com.hazelcast.mapreduce.MapReduceLiteMemberTest.testKeyedMapperCollator(MapReduceLiteMemberTest.java:155)
	at com.hazelcast.mapreduce.MapReduceLiteMemberTest.testKeyedMapperCollator(MapReduceLiteMemberTest.java:80)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK1.6/com.hazelcast$hazelcast/982/testReport/junit/com.hazelcast.mapreduce/MapReduceLiteMemberTest/testKeyedMapperCollator/

**Comment by metanet** [comment]
I am closing this one as it is not related to lite members. It is same with our chronic map-reduce failures.
