### ISSUE TITLE
MapStoreWriteBehindTest.testOneMemberWriteBehindFlush

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#8591]
```
java.lang.AssertionError: expected:<null> but was:<value1>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:834)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:144)
    at com.hazelcast.map.impl.mapstore.MapStoreWriteBehindTest.testOneMemberWriteBehindFlush(MapStoreWriteBehindTest.java:254)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK8/com.hazelcast$hazelcast/878/testReport/junit/com.hazelcast.map.impl.mapstore/MapStoreWriteBehindTest/testOneMemberWriteBehindFlush/

**Comment by jerrinot** [comment]
the test is fragile. I can reproduce it by having a sleep between these 2 lines: https://github.com/jerrinot/hazelcast/blob/07cd42d5481bc8e9bdc882070746ca7ad10d015b/hazelcast/src/test/java/com/hazelcast/map/impl/mapstore/MapStoreWriteBehindTest.java#L253-L254

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: WriteBehind Queue was flushed too soon. Configured write delay: 2000 ms. But it took less than 30 ms to flush the queue.
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.map.impl.mapstore.MapStoreWriteBehindTest.assertMapStoreDidNotFlushValueTooSoon(MapStoreWriteBehindTest.java:272)
	at com.hazelcast.map.impl.mapstore.MapStoreWriteBehindTest.testOneMemberWriteBehindFlush(MapStoreWriteBehindTest.java:260)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-IbmJDK1.7/com.hazelcast$hazelcast/438/testReport/junit/com.hazelcast.map.impl.mapstore/MapStoreWriteBehindTest/testOneMemberWriteBehindFlush/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: WriteBehind Queue was flushed too soon. Configured write delay: 2000 ms. But it took less than 1 ms to flush the queue.
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.map.impl.mapstore.MapStoreWriteBehindTest.assertMapStoreDidNotFlushValueTooSoon(MapStoreWriteBehindTest.java:272)
	at com.hazelcast.map.impl.mapstore.MapStoreWriteBehindTest.testOneMemberWriteBehindFlush(MapStoreWriteBehindTest.java:260)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast$hazelcast/1089/testReport/junit/com.hazelcast.map.impl.mapstore/MapStoreWriteBehindTest/testOneMemberWriteBehindFlush/

**Comment by mdogan** [comment]
No failures since November.

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: WriteBehind Queue was flushed too soon. Configured write delay: 2000 ms. But it took less than 0 ms to flush the queue.
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.map.impl.mapstore.MapStoreWriteBehindTest.assertMapStoreDidNotFlushValueTooSoon(MapStoreWriteBehindTest.java:272)
	at com.hazelcast.map.impl.mapstore.MapStoreWriteBehindTest.testOneMemberWriteBehindFlush(MapStoreWriteBehindTest.java:260)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.8/com.hazelcast$hazelcast/510/testReport/junit/com.hazelcast.map.impl.mapstore/MapStoreWriteBehindTest/testOneMemberWriteBehindFlush/

**Comment by mdogan** [comment]
No failures since February. This failure might be related to slow environment issue caused by logging.
