### ISSUE TITLE
MigrationAwareServiceEventTest.migrationCommitEvents_shouldBeEqual_onSource_and_onDestination

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#8594]
```
java.lang.AssertionError: expected:<0> but was:<1>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.internal.partition.MigrationAwareServiceEventTest$1.run(MigrationAwareServiceEventTest.java:70)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:901)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:915)
	at com.hazelcast.internal.partition.MigrationAwareServiceEventTest.migrationCommitEvents_shouldBeEqual_onSource_and_onDestination(MigrationAwareServiceEventTest.java:81)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-ZuluJDK6/com.hazelcast$hazelcast/274/testReport/junit/com.hazelcast.internal.partition/MigrationAwareServiceEventTest/migrationCommitEvents_shouldBeEqual_onSource_and_onDestination/

**Comment by mdogan** [comment]
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-ZuluJDK6/274/

```
Test Result (4 failures / +3)
com.hazelcast.internal.partition.AntiEntropyCorrectnessTest.testPartitionData[backups:2,nodes:3]
com.hazelcast.internal.partition.GracefulShutdownTest.shutdownMultipleSlaveMembers_withPartitionInitialization
com.hazelcast.internal.partition.GracefulShutdownTest.shutdownMultipleMembers_withPartitionInitialization
com.hazelcast.internal.partition.MigrationAwareServiceEventTest.migrationCommitEvents_shouldBeEqual_onSource_and_onDestination
```

Above 4 tests failed on the same build, main reason was migrations didn't complete on time because of very slow environment.
