### ISSUE TITLE
PartitioningStrategyFactoryTest.whenStrategyForMapAlreadyDefined_getPartitioningStrategy_returnsSameInstance

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#8634]
```
java.lang.AssertionError: expected same:<com.hazelcast.partition.strategy.StringPartitioningStrategy@5a927881> was not:<com.hazelcast.partition.strategy.StringPartitioningStrategy@11bf4347>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotSame(Assert.java:828)
	at org.junit.Assert.assertSame(Assert.java:771)
	at org.junit.Assert.assertSame(Assert.java:782)
	at com.hazelcast.map.impl.PartitioningStrategyFactoryTest.whenStrategyForMapAlreadyDefined_getPartitioningStrategy_returnsSameInstance(PartitioningStrategyFactoryTest.java:93)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-ZuluJDK8/com.hazelcast$hazelcast/280/testReport/junit/com.hazelcast.map.impl/PartitioningStrategyFactoryTest/whenStrategyForMapAlreadyDefined_getPartitioningStrategy_returnsSameInstance/

**Comment by hasancelik** [comment]
**maintenance**
```
java.lang.AssertionError: expected same:<com.hazelcast.partition.strategy.StringPartitioningStrategy@1bf1ce4> was not:<com.hazelcast.partition.strategy.StringPartitioningStrategy@445d49e3>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotSame(Assert.java:828)
	at org.junit.Assert.assertSame(Assert.java:771)
	at org.junit.Assert.assertSame(Assert.java:782)
	at com.hazelcast.map.impl.PartitioningStrategyFactoryTest.whenStrategyForMapAlreadyDefined_getPartitioningStrategy_returnsSameInstance(PartitioningStrategyFactoryTest.java:93)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.maintenance-OracleJDK8/com.hazelcast$hazelcast/410/testReport/junit/com.hazelcast.map.impl/PartitioningStrategyFactoryTest/whenStrategyForMapAlreadyDefined_getPartitioningStrategy_returnsSameInstance/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: expected same:<com.hazelcast.partition.strategy.StringPartitioningStrategy@54bccadc> was not:<com.hazelcast.partition.strategy.StringPartitioningStrategy@35fdd8f2>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotSame(Assert.java:828)
	at org.junit.Assert.assertSame(Assert.java:771)
	at org.junit.Assert.assertSame(Assert.java:782)
	at com.hazelcast.map.impl.PartitioningStrategyFactoryTest.whenStrategyForMapAlreadyDefined_getPartitioningStrategy_returnsSameInstance(PartitioningStrategyFactoryTest.java:93)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK8/com.hazelcast$hazelcast/919/testReport/junit/com.hazelcast.map.impl/PartitioningStrategyFactoryTest/whenStrategyForMapAlreadyDefined_getPartitioningStrategy_returnsSameInstance/

**Comment by vbekiaris** [comment]
Also backported to `maintenance-3.x` branch with #8844
