### ISSUE TITLE
[ZING-JVM] BackpressureRegulatorStressTest -- JVM crash at Jenkins

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#8636]
```
12:01:16 Running com.hazelcast.spi.impl.operationservice.impl.BackpressureRegulatorStressTest
12:03:26 SUREFIRE-859: Detected TTSP issue, cycle start: 14389.895, wait: 2007.177
12:03:26 Dumping stack for thread 0x000044006bc00000
12:03:26 SUREFIRE-859:      "hz._hzInstance_10686_dev.SlowOperationDetectorThread", id=6448, prio=5, os_prio=0, sched=SCHED_OTHER, allowed_cpus=000000000f
12:03:26        JVM lock released at:14391.977
12:03:26        last cpu:0                      thread cpu time:69
12:03:26        #0 0x0000000020894d51 SafepointProfilerBuf::record_sync_stack(JavaThread*)
12:03:26        #1 0x0000000020709848 InterpreterRuntime::at_safepoint(JavaThread*)
12:03:26        #2 0x0000000030006e9a interpreter
12:03:26        #3 0x0000000030006940 interpreter
12:03:26        #4 0x0000000030006940 interpreter
12:03:26        #5 0x00000000300035d5 StubRoutines::call_stub
12:03:26        signal sent:14390.972                   signal responded:14390.973
12:03:26        thread state:S                      wchan:hrtimer_nanosleep
12:03:26        last cpu:3                      thread cpu time:40
12:03:26        #0 0x00007efd708cbe2d nanosleep
12:03:26 SUREFIRE-859:      #1 0x00000000206c454f GPGC_ObjectRelocation::mutator_relocate_object(GPGC_Defines::Gens, long, GPGC_Defines::Gens, oopDesc*)
12:03:26        #2 0x000000002068c534 GPGC_Collector::mutator_relocate_object(oopDesc*)
12:03:26 SUREFIRE-859:      #3 0x00000000206e4424 GPGC_TLB::lvb_trap_from_c(Thread*, oopDesc*, oopDesc* volatile*)
12:03:26 SUREFIRE-859:      #4 0x00000000206e45f6 GPGC_TLB::lvb_trap_from_asm(Thread*, oopDesc*, oopDesc* volatile*)
12:03:26        #5 0x0000000030003127 StubRoutines::lvb_handler
12:03:26        #6 0x00000000318c6eaf com.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationDetector$DetectorThread.scan(JJ[Lcom/hazelcast/spi/impl/operationexecutor/OperationRunner;[Lcom/hazelcast/spi/impl/operationexecutor/slowoperationdetector/SlowOperationDetector$Cur��
12:03:26        #7 0x0000000032f3d127 com.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationDetector$DetectorThread.run()V
12:03:26        #8 0x00000000300035d5 StubRoutines::call_stub
12:03:28 Exception in thread "Thread-1" java.lang.OutOfMemoryError: Java heap space
12:03:28    at java.io.BufferedReader.readLine(BufferedReader.java:356)
12:03:28    at java.io.BufferedReader.readLine(BufferedReader.java:389)
12:03:28    at org.apache.maven.surefire.shade.org.apache.maven.shared.utils.cli.StreamPumper.run(StreamPumper.java:66)
12:04:48 SUREFIRE-859: Detected TTSP issue, cycle start: 14472.200, wait: 0.001
12:04:48 Dumping stack for thread 0x0000440001400000
12:04:48 SUREFIRE-859:      "Monitor Deflator Thread", id=3380, prio=5, os_prio=0, sched=SCHED_OTHER, allowed_cpus=000000000f
12:04:48        JVM lock released at:14474.265
12:04:48        last cpu:2                      thread cpu time:286
12:04:48        #0 0x0000000020894d51 SafepointProfilerBuf::record_sync_stack(JavaThread*)
12:04:48 SUREFIRE-859:      #1 0x00000000208b3d08 ObjectSynchronizer::conc_deflation_monitor_list_walk(ObjLock*, MonitorChunk*, unsigned long*, bool)
12:04:48        #2 0x00000000208b48f9 ObjectSynchronizer::conc_deflation_pipeline()
12:04:48        #3 0x00000000208b4acd MonitorDeflatorThread::deflation_loop()
12:04:48        #4 0x00000000208dabf3 JavaThread::thread_main_inner()
12:04:48        #5 0x00007efd700ff1b3 preRun
12:04:48        #6 0x00007efd70ff0dc5 start_thread
12:04:48        signal sent:14473.258                   signal responded:14473.258
12:04:48        thread state:S                      wchan:hrtimer_nanosleep
12:04:48        last cpu:0                      thread cpu time:259
12:04:48        #0 0x00007efd708cbe2d nanosleep
12:04:48 SUREFIRE-859:      #1 0x00000000206c454f GPGC_ObjectRelocation::mutator_relocate_object(GPGC_Defines::Gens, long, GPGC_Defines::Gens, oopDesc*)
12:04:48        #2 0x000000002068c534 GPGC_Collector::mutator_relocate_object(oopDesc*)
12:04:48 SUREFIRE-859:      #3 0x00000000206e4424 GPGC_TLB::lvb_trap_from_c(Thread*, oopDesc*, oopDesc* volatile*)
12:04:48        #4 0x00000000208d7a7b JavaThread::oops_do_impl(OopClosure*)
12:04:48        #5 0x00000000206dfd78 GPGC_ThreadCleaner::LVB_thread_stack(JavaThread*)
12:04:48        #6 0x00000000208dcb2a JavaThread::jvm_lock_self_or_suspend()
12:04:48        #7 0x00000000208dd340 JavaThread::sleep(long long)
12:04:48        #8 0x00000000208b4a9b MonitorDeflatorThread::deflation_loop()
```

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project hazelcast: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test failed: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
```

https://hazelcast-l337.ci.cloudbees.com/view/Zing/job/Hazelcast-3.x-ZingJDK8/39/console

**Comment by hasancelik** [comment]
```
14:41:40 Running com.hazelcast.spi.impl.operationservice.impl.BackpressureRegulatorStressTest
14:52:18 SUREFIRE-859: Detected TTSP issue, cycle start: 15204.319, wait: 2009.545
14:52:18 Dumping stack for thread 0x0000440024400000
14:52:18 SUREFIRE-859: 		"hz._hzInstance_10849_dev.partition-operation.thread-0", id=8925, prio=5, os_prio=0, sched=SCHED_OTHER, allowed_cpus=000000000f
14:52:18 		JVM lock released at:15206.487
14:52:18 		last cpu:2						thread cpu time:1350
14:52:18 		#0 0x000000002086d3a1 SafepointProfilerBuf::record_sync_stack(JavaThread*)
14:52:18 		#1 0x00000000208b1895 JavaThread::poll_at_safepoint_static(JavaThread*)
14:52:18 		#2 0x000000003001568e StubRoutines::safepoint_handler
14:52:18 		#3 0x000000003168bb7b com.hazelcast.internal.serialization.impl.bufferpool.BufferPoolThreadLocal.get()Lcom/hazelcast/internal/serialization/impl/bufferpool/BufferPool;
14:52:18 		#4 0x00000000334f0f0b com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(Ljava/lang/Object;)Ljava/lang/Object;
14:52:18 		#5 0x0000000031ec817b com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(Lcom/hazelcast/nio/Packet;)V
14:52:18 		#6 0x0000000033f4019e com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(Ljava/lang/Object;)V
14:52:18 		#7 0x000000003106eb09 com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run()V
14:52:18 		#8 0x00000000300035d5 StubRoutines::call_stub
14:52:18 		signal sent:15205.480					signal responded:15205.480
14:52:18 		thread state:S						wchan:hrtimer_nanosleep
14:52:18 		last cpu:0						thread cpu time:1324
14:52:18 		#0 0x00007faf7a6fde2d nanosleep
14:52:18 SUREFIRE-859: 		#1 0x00000000206af8ef GPGC_ObjectRelocation::mutator_relocate_object(GPGC_Defines::Gens, long, GPGC_Defines::Gens, oopDesc*)
14:52:18 		#2 0x0000000020677a74 GPGC_Collector::mutator_relocate_object(oopDesc*)
14:52:18 SUREFIRE-859: 		#3 0x00000000206cf794 GPGC_TLB::lvb_trap_from_c(Thread*, oopDesc*, oopDesc* volatile*)
14:52:18 SUREFIRE-859: 		#4 0x00000000206cf966 GPGC_TLB::lvb_trap_from_asm(Thread*, oopDesc*, oopDesc* volatile*)
14:52:18 		#5 0x0000000030003127 StubRoutines::lvb_handler
14:52:18 		#6 0x00000000334f14a4 com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(Ljava/lang/Object;)Ljava/lang/Object;
14:52:18 		#7 0x0000000031ec817b com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(Lcom/hazelcast/nio/Packet;)V
14:52:18 		#8 0x0000000033f4019e com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(Ljava/lang/Object;)V
14:52:36 SUREFIRE-859: Detected TTSP issue, cycle start: 15221.757, wait: 2010.595
14:52:36 Dumping stack for thread 0x0000440024400000
14:52:36 SUREFIRE-859: 		"hz._hzInstance_10849_dev.partition-operation.thread-0", id=8925, prio=5, os_prio=0, sched=SCHED_OTHER, allowed_cpus=000000000f
14:52:36 		JVM lock released at:15223.811
14:52:36 		last cpu:2						thread cpu time:1979
14:52:36 		#0 0x000000002086d3a1 SafepointProfilerBuf::record_sync_stack(JavaThread*)
14:52:36 		#1 0x00000000208b1895 JavaThread::poll_at_safepoint_static(JavaThread*)
14:52:36 		#2 0x000000003001568e StubRoutines::safepoint_handler
14:52:36 		#3 0x000000003168bb7b com.hazelcast.internal.serialization.impl.bufferpool.BufferPoolThreadLocal.get()Lcom/hazelcast/internal/serialization/impl/bufferpool/BufferPool;
14:52:36 		#4 0x00000000334f0f0b com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(Ljava/lang/Object;)Ljava/lang/Object;
14:52:36 		#5 0x0000000031ec817b com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(Lcom/hazelcast/nio/Packet;)V
14:52:36 		#6 0x0000000033f4019e com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(Ljava/lang/Object;)V
14:52:36 		#7 0x000000003106eb09 com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run()V
14:52:36 		#8 0x00000000300035d5 StubRoutines::call_stub
14:52:36 		signal sent:15222.802					signal responded:15222.802
14:52:36 		thread state:S						wchan:hrtimer_nanosleep
14:52:36 		last cpu:1						thread cpu time:1950
14:52:36 		#0 0x00007faf7a6fde2d nanosleep
14:52:36 SUREFIRE-859: 		#1 0x00000000206af8ef GPGC_ObjectRelocation::mutator_relocate_object(GPGC_Defines::Gens, long, GPGC_Defines::Gens, oopDesc*)
14:52:36 		#2 0x0000000020677a74 GPGC_Collector::mutator_relocate_object(oopDesc*)
14:52:36 SUREFIRE-859: 		#3 0x00000000206cf794 GPGC_TLB::lvb_trap_from_c(Thread*, oopDesc*, oopDesc* volatile*)
14:52:36 SUREFIRE-859: 		#4 0x00000000206cf966 GPGC_TLB::lvb_trap_from_asm(Thread*, oopDesc*, oopDesc* volatile*)
14:52:36 		#5 0x0000000030003127 StubRoutines::lvb_handler
14:52:36 		#6 0x00000000334f14a4 com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(Ljava/lang/Object;)Ljava/lang/Object;
14:52:36 		#7 0x0000000031ec817b com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(Lcom/hazelcast/nio/Packet;)V
14:52:36 		#8 0x0000000033f4019e com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(Ljava/lang/Object;)V
14:53:07 Exception in thread "Thread-1" java.lang.OutOfMemoryError: Java heap space
14:53:07 	at java.io.BufferedReader.readLine(BufferedReader.java:348)
14:53:07 	at java.io.BufferedReader.readLine(BufferedReader.java:379)
14:53:07 	at org.apache.maven.surefire.shade.org.apache.maven.shared.utils.cli.StreamPumper.run(StreamPumper.java:66)
14:53:07 SUREFIRE-859: Detected TTSP issue, cycle start: 15253.772, wait: 2011.332
14:53:07 Dumping stack for thread 0x0000440024400000
14:53:07 SUREFIRE-859: 		"hz._hzInstance_10849_dev.partition-operation.thread-0", id=8925, prio=5, os_prio=0, sched=SCHED_OTHER, allowed_cpus=000000000f
14:53:07 		JVM lock released at:15255.888
14:53:07 		last cpu:0						thread cpu time:3098
14:53:07 		#0 0x000000002086d3a1 SafepointProfilerBuf::record_sync_stack(JavaThread*)
14:53:07 		#1 0x00000000208b1895 JavaThread::poll_at_safepoint_static(JavaThread*)
14:53:07 		#2 0x000000003001568e StubRoutines::safepoint_handler
14:53:07 		#3 0x000000003168bb7b com.hazelcast.internal.serialization.impl.bufferpool.BufferPoolThreadLocal.get()Lcom/hazelcast/internal/serialization/impl/bufferpool/BufferPool;
14:53:07 		#4 0x00000000334f0f0b com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(Ljava/lang/Object;)Ljava/lang/Object;
14:53:07 		#5 0x0000000031ec817b com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(Lcom/hazelcast/nio/Packet;)V
14:53:07 		#6 0x0000000033f4019e com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(Ljava/lang/Object;)V
14:53:07 		#7 0x000000003106eb09 com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run()V
14:53:07 		#8 0x00000000300035d5 StubRoutines::call_stub
14:53:07 		signal sent:15254.879					signal responded:15254.879
14:53:07 		thread state:S						wchan:hrtimer_nanosleep
14:53:07 		last cpu:1						thread cpu time:3069
14:53:07 		#0 0x00007faf7a6fde2d nanosleep
14:53:07 SUREFIRE-859: 		#1 0x00000000206af8ef GPGC_ObjectRelocation::mutator_relocate_object(GPGC_Defines::Gens, long, GPGC_Defines::Gens, oopDesc*)
14:53:07 		#2 0x0000000020677a74 GPGC_Collector::mutator_relocate_object(oopDesc*)
14:53:07 SUREFIRE-859: 		#3 0x00000000206cf794 GPGC_TLB::lvb_trap_from_c(Thread*, oopDesc*, oopDesc* volatile*)
14:53:07 SUREFIRE-859: 		#4 0x00000000206cf966 GPGC_TLB::lvb_trap_from_asm(Thread*, oopDesc*, oopDesc* volatile*)
14:53:07 		#5 0x0000000030003127 StubRoutines::lvb_handler
14:53:07 		#6 0x00000000334f14a4 com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(Ljava/lang/Object;)Ljava/lang/Object;
14:53:07 		#7 0x0000000031ec817b com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(Lcom/hazelcast/nio/Packet;)V
14:53:07 		#8 0x0000000033f4019e com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(Ljava/lang/Object;)V
14:54:48 SUREFIRE-859: Detected TTSP issue, cycle start: 15354.149, wait: 2009.829
14:54:48 Dumping stack for thread 0x0000440024400000
14:54:48 SUREFIRE-859: 		"hz._hzInstance_10849_dev.partition-operation.thread-0", id=8925, prio=5, os_prio=0, sched=SCHED_OTHER, allowed_cpus=000000000f
14:54:48 		JVM lock released at:15356.234
14:54:48 		last cpu:3						thread cpu time:7447
14:54:48 		#0 0x000000002086d3a1 SafepointProfilerBuf::record_sync_stack(JavaThread*)
14:54:48 		#1 0x00000000208b1895 JavaThread::poll_at_safepoint_static(JavaThread*)
14:54:48 		#2 0x000000003001568e StubRoutines::safepoint_handler
14:54:48 		#3 0x000000003168bb7b com.hazelcast.internal.serialization.impl.bufferpool.BufferPoolThreadLocal.get()Lcom/hazelcast/internal/serialization/impl/bufferpool/BufferPool;
14:54:48 		#4 0x00000000334f0f0b com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(Ljava/lang/Object;)Ljava/lang/Object;
14:54:48 		#5 0x0000000031ec817b com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(Lcom/hazelcast/nio/Packet;)V
14:54:48 		#6 0x0000000033f4019e com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(Ljava/lang/Object;)V
14:54:48 		#7 0x000000003106eb09 com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run()V
14:54:48 		#8 0x00000000300035d5 StubRoutines::call_stub
14:54:48 		signal sent:15355.227					signal responded:15355.227
14:54:48 		thread state:S						wchan:hrtimer_nanosleep
14:54:48 		last cpu:0						thread cpu time:7418
14:54:48 		#0 0x00007faf7a6fde2d nanosleep
14:54:48 SUREFIRE-859: 		#1 0x00000000206af8ef GPGC_ObjectRelocation::mutator_relocate_object(GPGC_Defines::Gens, long, GPGC_Defines::Gens, oopDesc*)
14:54:48 		#2 0x0000000020677a74 GPGC_Collector::mutator_relocate_object(oopDesc*)
14:54:48 SUREFIRE-859: 		#3 0x00000000206cf794 GPGC_TLB::lvb_trap_from_c(Thread*, oopDesc*, oopDesc* volatile*)
14:54:48 SUREFIRE-859: 		#4 0x00000000206cf966 GPGC_TLB::lvb_trap_from_asm(Thread*, oopDesc*, oopDesc* volatile*)
14:54:48 		#5 0x0000000030003127 StubRoutines::lvb_handler
14:54:48 		#6 0x00000000334f14a4 com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(Ljava/lang/Object;)Ljava/lang/Object;
14:54:48 		#7 0x0000000031ec817b com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(Lcom/hazelcast/nio/Packet;)V
14:54:48 		#8 0x0000000033f4019e com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(Ljava/lang/Object;)V
```

https://hazelcast-l337.ci.cloudbees.com/view/Zing/job/Hazelcast-3.x-ZingJDK6/1/consoleFull
