### ISSUE TITLE
TcpIpConnectionManager_TransmitTest.withAddress_whenConnectionNotExists_thenCreated

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#8642]
```
java.lang.AssertionError: null
    at org.junit.Assert.fail(Assert.java:86)
    at org.junit.Assert.assertTrue(Assert.java:41)
    at org.junit.Assert.assertTrue(Assert.java:52)
    at com.hazelcast.nio.tcp.TcpIpConnectionManager_TransmitTest$3.run(TcpIpConnectionManager_TransmitTest.java:131)
    at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:901)
    at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:915)
    at com.hazelcast.nio.tcp.TcpIpConnectionManager_TransmitTest.withAddress_whenConnectionNotExists_thenCreated(TcpIpConnectionManager_TransmitTest.java:128)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK1.8/com.hazelcast$hazelcast/300/testReport/junit/com.hazelcast.nio.tcp/TcpIpConnectionManager_TransmitTest/withAddress_whenConnectionNotExists_thenCreated/

**Comment by mdogan** [comment]
No failures since Aug 2.

**Comment by Holmistr** [comment]
*maintenance* (commit 54ede33e51d347478c0d182100221b3af2dc53be)

Reopening as it failed on IBM JDK8: https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.maintenance-IbmJDK8/com.hazelcast$hazelcast/333/testReport/junit/com.hazelcast.nio.tcp/TcpIpConnectionManager_TransmitTest/withAddress_whenConnectionNotExists_thenCreated/

Stacktrace:
```
java.lang.AssertionError: Collection [] (0) didn't contain expected 'Packet{partitionId=-1, conn=null, rawFlags=0, isUrgent=false, packetType=NULL, typeSpecificFlags=<NONE>}'
	at org.junit.Assert.fail(Assert.java:88)
	at com.hazelcast.test.HazelcastTestSupport.assertContains(HazelcastTestSupport.java:827)
	at com.hazelcast.nio.tcp.TcpIpConnectionManager_TransmitTest$3.run(TcpIpConnectionManager_TransmitTest.java:148)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1246)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1263)
	at com.hazelcast.nio.tcp.TcpIpConnectionManager_TransmitTest.withAddress_whenConnectionNotExists_thenCreated(TcpIpConnectionManager_TransmitTest.java:145)
```

Standard output:
```
Hiccups measured while running test 'withAddress_whenConnectionNotExists_thenCreated(com.hazelcast.nio.tcp.TcpIpConnectionManager_TransmitTest):'
19:16:05, accumulated pauses: 56 ms, max pause: 0 ms, pauses over 1000 ms: 0
19:16:10, accumulated pauses: 55 ms, max pause: 0 ms, pauses over 1000 ms: 0
19:16:15, accumulated pauses: 61 ms, max pause: 0 ms, pauses over 1000 ms: 0
19:16:20, accumulated pauses: 61 ms, max pause: 0 ms, pauses over 1000 ms: 0
19:16:25, accumulated pauses: 71 ms, max pause: 6 ms, pauses over 1000 ms: 0
19:16:30, accumulated pauses: 59 ms, max pause: 0 ms, pauses over 1000 ms: 0
19:16:35, accumulated pauses: 59 ms, max pause: 0 ms, pauses over 1000 ms: 0
19:16:40, accumulated pauses: 60 ms, max pause: 1 ms, pauses over 1000 ms: 0
19:16:45, accumulated pauses: 64 ms, max pause: 3 ms, pauses over 1000 ms: 0
19:16:50, accumulated pauses: 63 ms, max pause: 1 ms, pauses over 1000 ms: 0
19:16:55, accumulated pauses: 72 ms, max pause: 7 ms, pauses over 1000 ms: 0
19:17:00, accumulated pauses: 75 ms, max pause: 8 ms, pauses over 1000 ms: 0
19:17:05, accumulated pauses: 75 ms, max pause: 8 ms, pauses over 1000 ms: 0
19:17:10, accumulated pauses: 64 ms, max pause: 3 ms, pauses over 1000 ms: 0
19:17:15, accumulated pauses: 62 ms, max pause: 1 ms, pauses over 1000 ms: 0
19:17:20, accumulated pauses: 64 ms, max pause: 2 ms, pauses over 1000 ms: 0
19:17:25, accumulated pauses: 61 ms, max pause: 2 ms, pauses over 1000 ms: 0
19:17:30, accumulated pauses: 59 ms, max pause: 2 ms, pauses over 1000 ms: 0
19:17:35, accumulated pauses: 79 ms, max pause: 11 ms, pauses over 1000 ms: 0
19:17:40, accumulated pauses: 63 ms, max pause: 2 ms, pauses over 1000 ms: 0
19:17:45, accumulated pauses: 55 ms, max pause: 0 ms, pauses over 1000 ms: 0
19:17:50, accumulated pauses: 55 ms, max pause: 0 ms, pauses over 1000 ms: 0
19:17:55, accumulated pauses: 51 ms, max pause: 0 ms, pauses over 1000 ms: 0
19:18:00, accumulated pauses: 53 ms, max pause: 0 ms, pauses over 1000 ms: 0
19:18:05, accumulated pauses: 25 ms, max pause: 0 ms, pauses over 1000 ms: 0

19:18:07,392  WARN |withAddress_whenConnectionNotExists_thenCreated| - [TcpIpConnectionErrorHandler] hz.hz.IO.thread-in-0 - [LOCAL] [somegroup] [3.10.1-SNAPSHOT] Removing connection to endpoint [127.0.0.1]:5701 Cause => java.io.EOFException {Remote socket closed!}, Error-Count: 2
```
