### ISSUE TITLE
LockAdvancedTest Failures

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#8645]
```
java.lang.AssertionError: tryLock() is not interrupted!
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.assertTrue(Assert.java:41)
    at com.hazelcast.concurrent.lock.LockAdvancedTest.testLockInterruption(LockAdvancedTest.java:226)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-OracleJDK8/com.hazelcast$hazelcast/886/testReport/junit/com.hazelcast.concurrent.lock/LockAdvancedTest/testLockInterruption/

**Comment by hasancelik** [comment]
**testLockInterruption**
```
java.lang.AssertionError: tryLock() is not interrupted!
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.concurrent.lock.LockAdvancedTest.testLockInterruption(LockAdvancedTest.java:226)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast$hazelcast/1090/testReport/junit/com.hazelcast.concurrent.lock/LockAdvancedTest/testLockInterruption/

**testLockInterruptibly**
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.concurrent.lock.LockAdvancedTest.testLockInterruptibly(LockAdvancedTest.java:391)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast$hazelcast/1090/testReport/junit/com.hazelcast.concurrent.lock/LockAdvancedTest/testLockInterruptibly/

**Comment by jerrinot** [comment]
the last 2 failure are on IBM JVM. I wonder whether it's just a coincidence.

**Comment by hasancelik** [comment]
*testLockInterruption*
```
java.lang.AssertionError: tryLock() is not interrupted!, failed to complete within 30 seconds, count left: 1
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:1019)
	at com.hazelcast.concurrent.lock.LockAdvancedTest.testLockInterruption(LockAdvancedTest.java:242)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-ZuluJDK7-freestyle/35/testReport/junit/com.hazelcast.concurrent.lock/LockAdvancedTest/testLockInterruption/

**Comment by mmedenjak** [comment]
This is not a lock issue, more an issue with how operations, heartbeats, timeouts and interruptions interact. 
A thread waiting on a `InternalCompletableFuture#get()` can get interrupted but it will get the `InterruptedException` only when the operation is retried (see [here](https://github.com/hazelcast/hazelcast/blob/02825e67b1bf9fac68116e5504e605a70cbf2182/hazelcast/src/main/java/com/hazelcast/spi/impl/operationservice/impl/Invocation.java#L648-L650)). 
To simulate a retry, we lower the `GroupProperty#OPERATION_CALL_TIMEOUT_MILLIS` to 5000ms but this inadvertently lowers the heartbeat timeout as well. In case of a slow environment, the operation will most likely get a heartbeart timeout before getting interrupted.
