### ISSUE TITLE
MigrationCommitTest.shouldRollbackMigrationWhenMasterCrashesBeforeCommit

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#8654]
```
java.lang.AssertionError: null
    at org.junit.Assert.fail(Assert.java:86)
    at org.junit.Assert.assertTrue(Assert.java:41)
    at org.junit.Assert.assertTrue(Assert.java:52)
    at com.hazelcast.internal.partition.impl.MigrationCommitTest$1.run(MigrationCommitTest.java:160)
    at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:901)
    at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:915)
    at com.hazelcast.internal.partition.impl.MigrationCommitTest.shouldRollbackMigrationWhenMasterCrashesBeforeCommit(MigrationCommitTest.java:156)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x/com.hazelcast$hazelcast/5534/testReport/junit/com.hazelcast.internal.partition.impl/MigrationCommitTest/shouldRollbackMigrationWhenMasterCrashesBeforeCommit/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.internal.partition.impl.MigrationCommitTest$1.run(MigrationCommitTest.java:160)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:901)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:915)
	at com.hazelcast.internal.partition.impl.MigrationCommitTest.shouldRollbackMigrationWhenMasterCrashesBeforeCommit(MigrationCommitTest.java:156)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-ZuluJDK7/com.hazelcast$hazelcast/302/testReport/junit/com.hazelcast.internal.partition.impl/MigrationCommitTest/shouldRollbackMigrationWhenMasterCrashesBeforeCommit/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.internal.partition.impl.MigrationCommitTest$1.run(MigrationCommitTest.java:160)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:905)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:919)
	at com.hazelcast.internal.partition.impl.MigrationCommitTest.shouldRollbackMigrationWhenMasterCrashesBeforeCommit(MigrationCommitTest.java:156)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK1.6/com.hazelcast$hazelcast/1075/testReport/junit/com.hazelcast.internal.partition.impl/MigrationCommitTest/shouldRollbackMigrationWhenMasterCrashesBeforeCommit/

**Comment by mdogan** [comment]
fixed by https://github.com/hazelcast/hazelcast/pull/9450
