### ISSUE TITLE
Invocation_RetryTest.invocationShouldComplete_whenRetried_DuringShutdown

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#8655]
```
java.lang.AssertionError: RetryingOperation failed to complete within 2 MINUTES. Invocation{op=com.hazelcast.spi.impl.operationservice.impl.Invocation_RetryTest$RetryingOperation{serviceName='null', identityHash=218560542, partitionId=175, replicaIndex=0, callId=0, invocationTime=1470167694759 (2016-08-02 22:54:54.759), waitTimeout=-1, callTimeout=9223372036854775807}, tryCount=2147483647, tryPauseMillis=500, invokeCount=7, callTimeoutMillis=9223372036854775807, firstInvocationTimeMs=1470167693754, firstInvocationTime='2016-08-02 22:54:53.754', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 02:00:00.000', target=null, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=null}
    at org.junit.Assert.fail(Assert.java:88)
    at com.hazelcast.spi.impl.operationservice.impl.Invocation_RetryTest.invocationShouldComplete_whenRetried_DuringShutdown(Invocation_RetryTest.java:149)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-sonar/com.hazelcast$hazelcast/1152/testReport/junit/com.hazelcast.spi.impl.operationservice.impl/Invocation_RetryTest/invocationShouldComplete_whenRetried_DuringShutdown/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: RetryingOperation failed to complete within 2 MINUTES. Invocation{op=com.hazelcast.spi.impl.operationservice.impl.Invocation_RetryTest$RetryingOperation{serviceName='null', identityHash=1898225451, partitionId=7, replicaIndex=0, callId=0, invocationTime=1471566471752 (2016-08-19 03:27:51.752), waitTimeout=-1, callTimeout=9223372036854775807}, tryCount=2147483647, tryPauseMillis=500, invokeCount=6, callTimeoutMillis=9223372036854775807, firstInvocationTimeMs=1471566470799, firstInvocationTime='2016-08-19 03:27:50.799', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 02:00:00.000', target=[127.0.0.1]:11959, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=null}
	at org.junit.Assert.fail(Assert.java:88)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation_RetryTest.invocationShouldComplete_whenRetried_DuringShutdown(Invocation_RetryTest.java:149)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-ZuluJDK7/com.hazelcast$hazelcast/302/testReport/junit/com.hazelcast.spi.impl.operationservice.impl/Invocation_RetryTest/invocationShouldComplete_whenRetried_DuringShutdown/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: RetryingOperation failed to complete within 2 MINUTES. Invocation{op=com.hazelcast.spi.impl.operationservice.impl.Invocation_RetryTest$RetryingOperation{serviceName='null', identityHash=1007029617, partitionId=50, replicaIndex=0, callId=0, invocationTime=1471920916920 (2016-08-23 05:55:16.920), waitTimeout=-1, callTimeout=9223372036854775807}, tryCount=2147483647, tryPauseMillis=500, invokeCount=5, callTimeoutMillis=9223372036854775807, firstInvocationTimeMs=1471920916807, firstInvocationTime='2016-08-23 05:55:16.807', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 02:00:00.000', target=[127.0.0.1]:14910, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=null}
	at org.junit.Assert.fail(Assert.java:88)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation_RetryTest.invocationShouldComplete_whenRetried_DuringShutdown(Invocation_RetryTest.java:149)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-OracleJDK8/com.hazelcast$hazelcast/908/testReport/junit/com.hazelcast.spi.impl.operationservice.impl/Invocation_RetryTest/invocationShouldComplete_whenRetried_DuringShutdown/

**Comment by Donnerbart** [comment]
```
RetryingOperation failed to complete within 2 MINUTES. Invocation{op=com.hazelcast.spi.impl.operationservice.impl.Invocation_RetryTest$RetryingOperation{serviceName='null', identityHash=923070768, partitionId=255, replicaIndex=0, callId=0, invocationTime=1472030841304 (2016-08-24 09:27:21.304), waitTimeout=-1, callTimeout=9223372036854775807}, tryCount=2147483647, tryPauseMillis=500, invokeCount=5, callTimeoutMillis=9223372036854775807, firstInvocationTimeMs=1472030839874, firstInvocationTime='2016-08-24 09:27:19.874', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 00:00:00.000', target=[127.0.0.1]:5034, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=null}
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/4245/testReport/junit/com.hazelcast.spi.impl.operationservice.impl/Invocation_RetryTest/invocationShouldComplete_whenRetried_DuringShutdown/

**Comment by Donnerbart** [comment]
```
RetryingOperation failed to complete within 2 MINUTES. Invocation{op=com.hazelcast.spi.impl.operationservice.impl.Invocation_RetryTest$RetryingOperation{serviceName='null', identityHash=176174861, partitionId=154, replicaIndex=0, callId=0, invocationTime=1472566855034 (2016-08-30 14:20:55.034), waitTimeout=-1, callTimeout=9223372036854775807}, tryCount=2147483647, tryPauseMillis=500, invokeCount=7, callTimeoutMillis=9223372036854775807, firstInvocationTimeMs=1472566853818, firstInvocationTime='2016-08-30 14:20:53.818', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 00:00:00.000', target=null, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=null}
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/4302/testReport/junit/com.hazelcast.spi.impl.operationservice.impl/Invocation_RetryTest/invocationShouldComplete_whenRetried_DuringShutdown/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: RetryingOperation failed to complete within 2 MINUTES. Invocation{op=com.hazelcast.spi.impl.operationservice.impl.Invocation_RetryTest$RetryingOperation{serviceName='null', identityHash=-1812194543, partitionId=182, replicaIndex=0, callId=0, invocationTime=1472615300945 (2016-08-31 06:48:20.945), waitTimeout=-1, callTimeout=9223372036854775807}, tryCount=2147483647, tryPauseMillis=500, invokeCount=5, callTimeoutMillis=9223372036854775807, firstInvocationTimeMs=1472615300899, firstInvocationTime='2016-08-31 06:48:20.899', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 02:00:00.000', target=[127.0.0.1]:16479, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=null}
	at org.junit.Assert.fail(Assert.java:88)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation_RetryTest.invocationShouldComplete_whenRetried_DuringShutdown(Invocation_RetryTest.java:149)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast$hazelcast/1018/testReport/junit/com.hazelcast.spi.impl.operationservice.impl/Invocation_RetryTest/invocationShouldComplete_whenRetried_DuringShutdown/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: RetryingOperation failed to complete within 2 MINUTES. Invocation{op=com.hazelcast.spi.impl.operationservice.impl.Invocation_RetryTest$RetryingOperation{serviceName='null', identityHash=2124010545, partitionId=152, replicaIndex=0, callId=0, invocationTime=1475977086664 (2016-10-09 04:38:06.664), waitTimeout=-1, callTimeout=9223372036854775807}, tryCount=2147483647, tryPauseMillis=500, invokeCount=5, callTimeoutMillis=9223372036854775807, firstInvocationTimeMs=1475977086631, firstInvocationTime='2016-10-09 04:38:06.631', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 02:00:00.000', target=[127.0.0.1]:9704, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=null}
	at org.junit.Assert.fail(Assert.java:88)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation_RetryTest.invocationShouldComplete_whenRetried_DuringShutdown(Invocation_RetryTest.java:149)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK8/com.hazelcast$hazelcast/956/testReport/junit/com.hazelcast.spi.impl.operationservice.impl/Invocation_RetryTest/invocationShouldComplete_whenRetried_DuringShutdown/

**Comment by hasancelik** [comment]
**maintenance**
```
java.lang.AssertionError: RetryingOperation failed to complete within 2 MINUTES. Invocation{op=com.hazelcast.spi.impl.operationservice.impl.Invocation_RetryTest$RetryingOperation{serviceName='null', identityHash=669357098, partitionId=4, replicaIndex=0, callId=0, invocationTime=1478497919326 (2016-11-07 07:51:59.326), waitTimeout=-1, callTimeout=9223372036854775807}, tryCount=2147483647, tryPauseMillis=500, invokeCount=6, callTimeoutMillis=9223372036854775807, firstInvocationTimeMs=1478497918344, firstInvocationTime='2016-11-07 07:51:58.344', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 02:00:00.000', target=[127.0.0.1]:11325, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=null}
	at org.junit.Assert.fail(Assert.java:88)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation_RetryTest.invocationShouldComplete_whenRetried_DuringShutdown(Invocation_RetryTest.java:149)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-ZuluJDK6/com.hazelcast$hazelcast/137/testReport/junit/com.hazelcast.spi.impl.operationservice.impl/Invocation_RetryTest/invocationShouldComplete_whenRetried_DuringShutdown/

**Comment by hasancelik** [comment]
**master**
```
java.lang.AssertionError: RetryingOperation failed to complete within 2 MINUTES. Invocation{op=com.hazelcast.spi.impl.operationservice.impl.Invocation_RetryTest$RetryingOperation{serviceName='null', identityHash=943066927, partitionId=61, replicaIndex=0, callId=0, invocationTime=1478665865207 (2016-11-09 06:31:05.207), waitTimeout=-1, callTimeout=9223372036854775807}, tryCount=2147483647, tryPauseMillis=500, invokeCount=7, callTimeoutMillis=9223372036854775807, firstInvocationTimeMs=1478665864455, firstInvocationTime='2016-11-09 06:31:04.455', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 02:00:00.000', target=null, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=null}
	at org.junit.Assert.fail(Assert.java:88)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation_RetryTest.invocationShouldComplete_whenRetried_DuringShutdown(Invocation_RetryTest.java:149)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK1.6/com.hazelcast$hazelcast/1094/testReport/junit/com.hazelcast.spi.impl.operationservice.impl/Invocation_RetryTest/invocationShouldComplete_whenRetried_DuringShutdown/

**Comment by mdogan** [comment]
PRs https://github.com/hazelcast/hazelcast/pull/9296 and https://github.com/hazelcast/hazelcast/pull/9303 fixed/improved invocation retry mechanism. 

Closing for now, since not failing for more than a month. Will reopen if fails again.

**Comment by mdogan** [comment]
```
java.lang.AssertionError: RetryingOperation failed to complete within 2 MINUTES. Invocation{op=com.hazelcast.spi.impl.operationservice.impl.Invocation_RetryTest$RetryingOperation{serviceName='null', identityHash=1488269177, partitionId=165, replicaIndex=0, callId=-78, invocationTime=1481875178825 (2016-12-16 07:59:38.825), waitTimeout=-1, callTimeout=9223372036854775807}, tryCount=2147483647, tryPauseMillis=500, invokeCount=5, callTimeoutMillis=9223372036854775807, firstInvocationTimeMs=1481875178492, firstInvocationTime='2016-12-16 07:59:38.492', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 00:00:00.000', target=[127.0.0.1]:5007, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=null}
	at org.junit.Assert.fail(Assert.java:88)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation_RetryTest.invocationShouldComplete_whenRetried_DuringShutdown(Invocation_RetryTest.java:149)

```

https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/6308/testReport/com.hazelcast.spi.impl.operationservice.impl/Invocation_RetryTest/invocationShouldComplete_whenRetried_DuringShutdown/
