### ISSUE TITLE
PartitionServiceSafetyCheckTest.clusterShouldBeSafe_withSingleDataMember

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#8661]
```
java.lang.AssertionError: null
    at org.junit.Assert.fail(Assert.java:86)
    at org.junit.Assert.assertTrue(Assert.java:41)
    at org.junit.Assert.assertTrue(Assert.java:52)
    at com.hazelcast.internal.partition.PartitionServiceSafetyCheckTest.assertSafe(PartitionServiceSafetyCheckTest.java:204)
    at com.hazelcast.internal.partition.PartitionServiceSafetyCheckTest.clusterShouldBeSafe_withSingleDataMember(PartitionServiceSafetyCheckTest.java:86)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-OracleJDK1.6/com.hazelcast$hazelcast/993/testReport/junit/com.hazelcast.internal.partition/PartitionServiceSafetyCheckTest/clusterShouldBeSafe_withSingleDataMember/

**Comment by hasancelik** [comment]
**maintenance**
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.internal.partition.PartitionServiceSafetyCheckTest.assertSafe(PartitionServiceSafetyCheckTest.java:204)
	at com.hazelcast.internal.partition.PartitionServiceSafetyCheckTest.clusterShouldBeSafe_withSingleDataMember(PartitionServiceSafetyCheckTest.java:86)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-IbmJDK1.8/com.hazelcast$hazelcast/107/testReport/junit/com.hazelcast.internal.partition/PartitionServiceSafetyCheckTest/clusterShouldBeSafe_withSingleDataMember/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.internal.partition.PartitionServiceSafetyCheckTest.assertSafe(PartitionServiceSafetyCheckTest.java:204)
	at com.hazelcast.internal.partition.PartitionServiceSafetyCheckTest.clusterShouldBeSafe_withSingleDataMember(PartitionServiceSafetyCheckTest.java:86)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast$hazelcast/996/testReport/junit/com.hazelcast.internal.partition/PartitionServiceSafetyCheckTest/clusterShouldBeSafe_withSingleDataMember/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.internal.partition.PartitionServiceSafetyCheckTest.assertSafe(PartitionServiceSafetyCheckTest.java:204)
	at com.hazelcast.internal.partition.PartitionServiceSafetyCheckTest.clusterShouldBeSafe_withSingleDataMember(PartitionServiceSafetyCheckTest.java:86)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK1.8/com.hazelcast$hazelcast/309/testReport/junit/com.hazelcast.internal.partition/PartitionServiceSafetyCheckTest/clusterShouldBeSafe_withSingleDataMember/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.internal.partition.PartitionServiceSafetyCheckTest.assertSafe(PartitionServiceSafetyCheckTest.java:204)
	at com.hazelcast.internal.partition.PartitionServiceSafetyCheckTest.clusterShouldBeSafe_withSingleDataMember(PartitionServiceSafetyCheckTest.java:86)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK1.6/com.hazelcast$hazelcast/1004/testReport/junit/com.hazelcast.internal.partition/PartitionServiceSafetyCheckTest/clusterShouldBeSafe_withSingleDataMember/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.internal.partition.PartitionServiceSafetyCheckTest.assertSafe(PartitionServiceSafetyCheckTest.java:204)
	at com.hazelcast.internal.partition.PartitionServiceSafetyCheckTest.clusterShouldBeSafe_withSingleDataMember(PartitionServiceSafetyCheckTest.java:86)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast$hazelcast/1005/testReport/junit/com.hazelcast.internal.partition/PartitionServiceSafetyCheckTest/clusterShouldBeSafe_withSingleDataMember/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.internal.partition.PartitionServiceSafetyCheckTest.assertSafe(PartitionServiceSafetyCheckTest.java:204)
	at com.hazelcast.internal.partition.PartitionServiceSafetyCheckTest.clusterShouldBeSafe_withSingleDataMember(PartitionServiceSafetyCheckTest.java:86)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK1.8/com.hazelcast$hazelcast/323/testReport/junit/com.hazelcast.internal.partition/PartitionServiceSafetyCheckTest/clusterShouldBeSafe_withSingleDataMember/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.internal.partition.PartitionServiceSafetyCheckTest.assertSafe(PartitionServiceSafetyCheckTest.java:204)
	at com.hazelcast.internal.partition.PartitionServiceSafetyCheckTest.clusterShouldBeSafe_withSingleDataMember(PartitionServiceSafetyCheckTest.java:86)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast$hazelcast/1015/testReport/junit/com.hazelcast.internal.partition/PartitionServiceSafetyCheckTest/clusterShouldBeSafe_withSingleDataMember/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.internal.partition.PartitionServiceSafetyCheckTest.assertSafe(PartitionServiceSafetyCheckTest.java:204)
	at com.hazelcast.internal.partition.PartitionServiceSafetyCheckTest.clusterShouldBeSafe_withSingleDataMember(PartitionServiceSafetyCheckTest.java:86)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.maintenance-IbmJDK1.8/com.hazelcast$hazelcast/116/testReport/junit/com.hazelcast.internal.partition/PartitionServiceSafetyCheckTest/clusterShouldBeSafe_withSingleDataMember/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: Instances not in safe state! {[127.0.0.1]:10494=MIGRATION_LOCAL, [127.0.0.1]:10496=MIGRATION_ON_MASTER, [127.0.0.1]:10500=MIGRATION_ON_MASTER, [127.0.0.1]:10498=MIGRATION_ON_MASTER}
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport.assertAllInSafeState(HazelcastTestSupport.java:614)
	at com.hazelcast.internal.partition.PartitionServiceSafetyCheckTest.assertSafe(PartitionServiceSafetyCheckTest.java:204)
	at com.hazelcast.internal.partition.PartitionServiceSafetyCheckTest.clusterShouldBeSafe_withSingleDataMember(PartitionServiceSafetyCheckTest.java:86)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast$hazelcast/1021/testReport/junit/com.hazelcast.internal.partition/PartitionServiceSafetyCheckTest/clusterShouldBeSafe_withSingleDataMember/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: Instances not in safe state! {[127.0.0.1]:13829=MIGRATION_LOCAL, [127.0.0.1]:13831=MIGRATION_ON_MASTER, [127.0.0.1]:13832=MIGRATION_ON_MASTER, [127.0.0.1]:13830=MIGRATION_ON_MASTER}
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport.assertAllInSafeState(HazelcastTestSupport.java:614)
	at com.hazelcast.internal.partition.PartitionServiceSafetyCheckTest.assertSafe(PartitionServiceSafetyCheckTest.java:204)
	at com.hazelcast.internal.partition.PartitionServiceSafetyCheckTest.clusterShouldBeSafe_withSingleDataMember(PartitionServiceSafetyCheckTest.java:86)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-ZuluJDK6/com.hazelcast$hazelcast/316/testReport/junit/com.hazelcast.internal.partition/PartitionServiceSafetyCheckTest/clusterShouldBeSafe_withSingleDataMember/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: Instances not in safe state! {[127.0.0.1]:15940=MIGRATION_ON_MASTER, [127.0.0.1]:15939=MIGRATION_ON_MASTER, [127.0.0.1]:15941=MIGRATION_ON_MASTER, [127.0.0.1]:15938=MIGRATION_LOCAL}
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport.assertAllInSafeState(HazelcastTestSupport.java:614)
	at com.hazelcast.internal.partition.PartitionServiceSafetyCheckTest.assertSafe(PartitionServiceSafetyCheckTest.java:204)
	at com.hazelcast.internal.partition.PartitionServiceSafetyCheckTest.clusterShouldBeSafe_withSingleDataMember(PartitionServiceSafetyCheckTest.java:86)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK1.7/com.hazelcast$hazelcast/613/testReport/junit/com.hazelcast.internal.partition/PartitionServiceSafetyCheckTest/clusterShouldBeSafe_withSingleDataMember/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: Instances not in safe state! {[127.0.0.1]:13696=MIGRATION_ON_MASTER, [127.0.0.1]:13695=MIGRATION_LOCAL, [127.0.0.1]:13697=MIGRATION_ON_MASTER, [127.0.0.1]:13698=MIGRATION_ON_MASTER}
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport.assertAllInSafeState(HazelcastTestSupport.java:614)
	at com.hazelcast.internal.partition.PartitionServiceSafetyCheckTest.assertSafe(PartitionServiceSafetyCheckTest.java:204)
	at com.hazelcast.internal.partition.PartitionServiceSafetyCheckTest.clusterShouldBeSafe_withSingleDataMember(PartitionServiceSafetyCheckTest.java:86)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.maintenance-IbmJDK1.7/com.hazelcast$hazelcast/431/testReport/junit/com.hazelcast.internal.partition/PartitionServiceSafetyCheckTest/clusterShouldBeSafe_withSingleDataMember/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: Instances not in safe state! {[127.0.0.1]:13733=MIGRATION_LOCAL, [127.0.0.1]:13735=MIGRATION_ON_MASTER, [127.0.0.1]:13734=MIGRATION_ON_MASTER, [127.0.0.1]:13736=MIGRATION_ON_MASTER}
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport.assertAllInSafeState(HazelcastTestSupport.java:614)
	at com.hazelcast.internal.partition.PartitionServiceSafetyCheckTest.assertSafe(PartitionServiceSafetyCheckTest.java:204)
	at com.hazelcast.internal.partition.PartitionServiceSafetyCheckTest.clusterShouldBeSafe_withSingleDataMember(PartitionServiceSafetyCheckTest.java:86)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.8/com.hazelcast$hazelcast/357/testReport/junit/com.hazelcast.internal.partition/PartitionServiceSafetyCheckTest/clusterShouldBeSafe_withSingleDataMember/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: Instances not in safe state! {[127.0.0.1]:13184=MIGRATION_LOCAL, [127.0.0.1]:13185=MIGRATION_ON_MASTER, [127.0.0.1]:13187=MIGRATION_ON_MASTER, [127.0.0.1]:13186=MIGRATION_ON_MASTER}
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport.assertAllInSafeState(HazelcastTestSupport.java:614)
	at com.hazelcast.internal.partition.PartitionServiceSafetyCheckTest.assertSafe(PartitionServiceSafetyCheckTest.java:204)
	at com.hazelcast.internal.partition.PartitionServiceSafetyCheckTest.clusterShouldBeSafe_withSingleDataMember(PartitionServiceSafetyCheckTest.java:86)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-OracleJDK1.7/com.hazelcast$hazelcast/622/testReport/junit/com.hazelcast.internal.partition/PartitionServiceSafetyCheckTest/clusterShouldBeSafe_withSingleDataMember/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: Instances not in safe state! {[127.0.0.1]:12429=MIGRATION_ON_MASTER, [127.0.0.1]:12431=MIGRATION_ON_MASTER, [127.0.0.1]:12426=MIGRATION_LOCAL, [127.0.0.1]:12428=MIGRATION_ON_MASTER}
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport.assertAllInSafeState(HazelcastTestSupport.java:614)
	at com.hazelcast.internal.partition.PartitionServiceSafetyCheckTest.assertSafe(PartitionServiceSafetyCheckTest.java:204)
	at com.hazelcast.internal.partition.PartitionServiceSafetyCheckTest.clusterShouldBeSafe_withSingleDataMember(PartitionServiceSafetyCheckTest.java:86)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast$hazelcast/1051/testReport/junit/com.hazelcast.internal.partition/PartitionServiceSafetyCheckTest/clusterShouldBeSafe_withSingleDataMember/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: Instances not in safe state! {[127.0.0.1]:14303=MIGRATION_ON_MASTER, [127.0.0.1]:14302=MIGRATION_ON_MASTER, [127.0.0.1]:14301=MIGRATION_LOCAL, [127.0.0.1]:14304=MIGRATION_ON_MASTER}
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport.assertAllInSafeState(HazelcastTestSupport.java:614)
	at com.hazelcast.internal.partition.PartitionServiceSafetyCheckTest.assertSafe(PartitionServiceSafetyCheckTest.java:204)
	at com.hazelcast.internal.partition.PartitionServiceSafetyCheckTest.clusterShouldBeSafe_withSingleDataMember(PartitionServiceSafetyCheckTest.java:86)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x/com.hazelcast$hazelcast/5813/testReport/junit/com.hazelcast.internal.partition/PartitionServiceSafetyCheckTest/clusterShouldBeSafe_withSingleDataMember/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: Instances not in safe state! {[127.0.0.1]:16362=MIGRATION_ON_MASTER, [127.0.0.1]:16360=MIGRATION_ON_MASTER, [127.0.0.1]:16364=MIGRATION_ON_MASTER, [127.0.0.1]:16359=MIGRATION_LOCAL}
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport.assertAllInSafeState(HazelcastTestSupport.java:614)
	at com.hazelcast.internal.partition.PartitionServiceSafetyCheckTest.assertSafe(PartitionServiceSafetyCheckTest.java:204)
	at com.hazelcast.internal.partition.PartitionServiceSafetyCheckTest.clusterShouldBeSafe_withSingleDataMember(PartitionServiceSafetyCheckTest.java:86)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast$hazelcast/1063/testReport/junit/com.hazelcast.internal.partition/PartitionServiceSafetyCheckTest/clusterShouldBeSafe_withSingleDataMember/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: Instances not in safe state! {[127.0.0.1]:16386=MIGRATION_ON_MASTER, [127.0.0.1]:16385=MIGRATION_ON_MASTER, [127.0.0.1]:16383=MIGRATION_LOCAL, [127.0.0.1]:16384=MIGRATION_ON_MASTER}
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport.assertAllInSafeState(HazelcastTestSupport.java:614)
	at com.hazelcast.internal.partition.PartitionServiceSafetyCheckTest.assertSafe(PartitionServiceSafetyCheckTest.java:204)
	at com.hazelcast.internal.partition.PartitionServiceSafetyCheckTest.clusterShouldBeSafe_withSingleDataMember(PartitionServiceSafetyCheckTest.java:86)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast$hazelcast/1081/testReport/junit/com.hazelcast.internal.partition/PartitionServiceSafetyCheckTest/clusterShouldBeSafe_withSingleDataMember/

**Comment by metanet** [comment]
Fixed by  https://github.com/hazelcast/hazelcast/commit/fe0ed50a4d97c6c207381edae66b142a8bb5755e
