### ISSUE TITLE
ExecutorServiceTest.testLongRunningCallable

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#8679]
```
java.util.concurrent.ExecutionException: MemberCallableTaskOperation invocation failed to complete due to operation-heartbeat-timeout. Current time: 2016-08-07 04:31:42.527. Total elapsed time: 6983 ms. Last operation heartbeat: 2016-08-07 04:31:38.699. Last operation heartbeat from member: 2016-08-07 04:31:38.699. Invocation{op=com.hazelcast.executor.impl.operations.MemberCallableTaskOperation{serviceName='hz:impl:executorService', identityHash=1589868300, partitionId=-1, replicaIndex=0, callId=0, invocationTime=1470533495544 (2016-08-07 04:31:35.544), waitTimeout=-1, callTimeout=3000, name=test}, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=3000, firstInvocationTimeMs=1470533495544, firstInvocationTime='2016-08-07 04:31:35.544', lastHeartbeatMillis=1470533498699, lastHeartbeatTime='2016-08-07 04:31:38.699', target=[127.0.0.1]:14739, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=MockConnection{localEndpoint=[127.0.0.1]:14738, remoteEndpoint=[127.0.0.1]:14739}}
    at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.newOperationTimeoutException(InvocationFuture.java:150)
    at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:98)
    at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrow(InvocationFuture.java:74)
    at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:186)
    at com.hazelcast.util.executor.DelegatingFuture.get(DelegatingFuture.java:74)
    at com.hazelcast.executor.ExecutorServiceTest.testLongRunningCallable(ExecutorServiceTest.java:999)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-ZuluJDK6/com.hazelcast$hazelcast/286/testReport/junit/com.hazelcast.executor/ExecutorServiceTest/testLongRunningCallable/

**Comment by mdogan** [comment]
No failures since Aug 8.

**Comment by hasancelik** [comment]
```
java.util.concurrent.ExecutionException: MemberCallableTaskOperation invocation failed to complete due to operation-heartbeat-timeout. Current time: 2017-05-07 03:04:33.196. Start time: 2017-05-07 03:04:28.281. Total elapsed time: 4915 ms. Last operation heartbeat: 2017-05-07 03:04:29.761. Last operation heartbeat from member: 2017-05-07 03:04:33.196. Invocation{op=com.hazelcast.executor.impl.operations.MemberCallableTaskOperation{serviceName='hz:impl:executorService', identityHash=1028734689, partitionId=-1, replicaIndex=0, callId=-2, invocationTime=1494115468281 (2017-05-07 03:04:28.281), waitTimeout=-1, callTimeout=3000, name=test}, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=3000, firstInvocationTimeMs=1494115468281, firstInvocationTime='2017-05-07 03:04:28.281', lastHeartbeatMillis=1494115469761, lastHeartbeatTime='2017-05-07 03:04:29.761', target=[127.0.0.1]:5756, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=MockConnection{localEndpoint=[127.0.0.1]:5755, remoteEndpoint=[127.0.0.1]:5756}}
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.newOperationTimeoutException(InvocationFuture.java:151)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:101)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:75)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:183)
	at com.hazelcast.util.executor.DelegatingFuture.get(DelegatingFuture.java:88)
	at com.hazelcast.executor.ExecutorServiceTest.testLongRunningCallable(ExecutorServiceTest.java:1009)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-OracleJDK1.7/com.hazelcast$hazelcast/383/testReport/junit/com.hazelcast.executor/ExecutorServiceTest/testLongRunningCallable/

**Comment by hasancelik** [comment]
```
java.util.concurrent.ExecutionException: MemberCallableTaskOperation invocation failed to complete due to operation-heartbeat-timeout. Current time: 2017-07-13 02:44:33.360. Start time: 2017-07-13 02:44:27.183. Total elapsed time: 6177 ms. Last operation heartbeat: 2017-07-13 02:44:29.652. Last operation heartbeat from member: 2017-07-13 02:44:33.360. Invocation{op=com.hazelcast.executor.impl.operations.MemberCallableTaskOperation{serviceName='hz:impl:executorService', identityHash=1226906716, partitionId=-1, replicaIndex=0, callId=-2, invocationTime=1499903067183 (2017-07-13 02:44:27.183), waitTimeout=-1, callTimeout=3000, name=test}, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=3000, firstInvocationTimeMs=1499903067183, firstInvocationTime='2017-07-13 02:44:27.183', lastHeartbeatMillis=1499903069652, lastHeartbeatTime='2017-07-13 02:44:29.652', target=[127.0.0.1]:6467, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=MockConnection{localEndpoint=[127.0.0.1]:6466, remoteEndpoint=[127.0.0.1]:6467}}
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.newOperationTimeoutException(InvocationFuture.java:151)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:101)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:75)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:183)
	at com.hazelcast.util.executor.DelegatingFuture.get(DelegatingFuture.java:88)
	at com.hazelcast.executor.ExecutorServiceTest.testLongRunningCallable(ExecutorServiceTest.java:1009)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-OracleJDK1.6-freestyle/58/testReport/junit/com.hazelcast.executor/ExecutorServiceTest/testLongRunningCallable/

**Comment by tombujok** [comment]
Cause by jenkins stall.

**Comment by Holmistr** [comment]
*master* (commit 1f10121522ff194497d4d51660b5e77262681877)

Reopening as it failed on Zulu JDK7: https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-ZuluJDK7/209/testReport/junit/com.hazelcast.executor/ExecutorServiceTest/testLongRunningCallable/

Stacktrace:
```
java.util.concurrent.ExecutionException: MemberCallableTaskOperation invocation failed to complete due to operation-heartbeat-timeout. Current time: 2018-06-13 21:41:42.881. Start time: 2018-06-13 21:41:38.230. Total elapsed time: 4651 ms. Last operation heartbeat: 2018-06-13 21:41:38.720. Last operation heartbeat from member: 2018-06-13 21:41:38.720. Invocation{op=com.hazelcast.executor.impl.operations.MemberCallableTaskOperation{serviceName='hz:impl:executorService', identityHash=559050881, partitionId=-1, replicaIndex=0, callId=-5, invocationTime=1528915298230 (2018-06-13 21:41:38.230), waitTimeout=-1, callTimeout=3000, name=test}, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=3000, firstInvocationTimeMs=1528915298230, firstInvocationTime='2018-06-13 21:41:38.230', lastHeartbeatMillis=1528915298720, lastHeartbeatTime='2018-06-13 21:41:38.720', target=[127.0.0.1]:9276, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=MockConnection{localEndpoint=[127.0.0.1]:9275, remoteEndpoint=[127.0.0.1]:9276}}
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.newOperationTimeoutException(InvocationFuture.java:164)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:106)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:79)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:190)
	at com.hazelcast.util.executor.DelegatingFuture.get(DelegatingFuture.java:88)
	at com.hazelcast.executor.ExecutorServiceTest.testLongRunningCallable(ExecutorServiceTest.java:1048)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.hazelcast.core.OperationTimeoutException: MemberCallableTaskOperation invocation failed to complete due to operation-heartbeat-timeout. Current time: 2018-06-13 21:41:42.881. Start time: 2018-06-13 21:41:38.230. Total elapsed time: 4651 ms. Last operation heartbeat: 2018-06-13 21:41:38.720. Last operation heartbeat from member: 2018-06-13 21:41:38.720. Invocation{op=com.hazelcast.executor.impl.operations.MemberCallableTaskOperation{serviceName='hz:impl:executorService', identityHash=559050881, partitionId=-1, replicaIndex=0, callId=-5, invocationTime=1528915298230 (2018-06-13 21:41:38.230), waitTimeout=-1, callTimeout=3000, name=test}, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=3000, firstInvocationTimeMs=1528915298230, firstInvocationTime='2018-06-13 21:41:38.230', lastHeartbeatMillis=1528915298720, lastHeartbeatTime='2018-06-13 21:41:38.720', target=[127.0.0.1]:9276, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=MockConnection{localEndpoint=[127.0.0.1]:9275, remoteEndpoint=[127.0.0.1]:9276}}
	... 18 more
```

Standard output:
```
Hiccups measured while running test 'testLongRunningCallable(com.hazelcast.executor.ExecutorServiceTest):'
21:41:35, accumulated pauses: 3972 ms, max pause: 3888 ms, pauses over 1000 ms: 1
21:41:40, accumulated pauses: 443 ms, max pause: 216 ms, pauses over 1000 ms: 0
21:41:45, accumulated pauses: 21 ms, max pause: 0 ms, pauses over 1000 ms: 0
```

**Comment by Holmistr** [comment]
Fixed by https://github.com/hazelcast/hazelcast/pull/13332 .
