### ISSUE TITLE
ExecutorServiceTest.testCancellationAwareTask

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#8680]
```
java.lang.AssertionError: null
    at org.junit.Assert.fail(Assert.java:86)
    at org.junit.Assert.assertTrue(Assert.java:41)
    at org.junit.Assert.assertTrue(Assert.java:52)
    at com.hazelcast.executor.ExecutorServiceTest.testCancellationAwareTask(ExecutorServiceTest.java:648)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-ZuluJDK6/com.hazelcast$hazelcast/286/testReport/junit/com.hazelcast.executor/ExecutorServiceTest/testCancellationAwareTask/

**Comment by mdogan** [comment]
No failures since Aug 8.
