### ISSUE TITLE
Unchecked CancelledKeyException when client disconnects from cluster

### ISSUE THREAD

**Issue by alparslanavci** [hazelcast/hazelcast#8681]
Users can get `CancelledKeyException` when the client disconnects from the cluster. Here is the related stacktrace:

```
2016-07-26 09:09:49:981 [hz._hzInstance_1_dev.IO.thread-out-1] WARN c.h.n.t.n.NonBlockingSocketWriter - [example.hazelcast.com]:10330 [dev] [3.6.2] hz._hzInstance_1_dev.IO.thread-out-1 Closing socket to endpoint Address[10.98.205.19]:56160, Cause:java.nio.channels.CancelledKeyException

java.nio.channels.CancelledKeyException: null

at sun.nio.ch.SelectionKeyImpl.ensureValid(SelectionKeyImpl.java:73) ~[na:1.8.0_91]

at sun.nio.ch.SelectionKeyImpl.interestOps(SelectionKeyImpl.java:77) ~[na:1.8.0_91]

at com.hazelcast.nio.tcp.nonblocking.AbstractHandler.unregisterOp(AbstractHandler.java:73) ~[hazelcast-all-3.6.2.jar:3.6.2]

at com.hazelcast.nio.tcp.nonblocking.NonBlockingSocketWriter.unschedule(NonBlockingSocketWriter.java:295) ~[hazelcast-all-3.6.2.jar:3.6.2]

at com.hazelcast.nio.tcp.nonblocking.NonBlockingSocketWriter.handle(NonBlockingSocketWriter.java:344) ~[hazelcast-all-3.6.2.jar:3.6.2]

at com.hazelcast.nio.tcp.nonblocking.NonBlockingSocketWriter.run(NonBlockingSocketWriter.java:423) ~[hazelcast-all-3.6.2.jar:3.6.2]

at com.hazelcast.nio.tcp.nonblocking.NonBlockingIOThread.executeTask(NonBlockingIOThread.java:236) [hazelcast-all-3.6.2.jar:3.6.2]

at com.hazelcast.nio.tcp.nonblocking.NonBlockingIOThread.processTaskQueue(NonBlockingIOThread.java:229) [hazelcast-all-3.6.2.jar:3.6.2]

at com.hazelcast.nio.tcp.nonblocking.NonBlockingIOThread.runSelectLoop(NonBlockingIOThread.java:201) [hazelcast-all-3.6.2.jar:3.6.2]

at com.hazelcast.nio.tcp.nonblocking.NonBlockingIOThread.run(NonBlockingIOThread.java:163) [hazelcast-all-3.6.2.jar:3.6.2]
```

The warning seems harmless, but the printed log should be prettified for better user experience.

**Comment by lu-ko** [comment]
Similar exception in 3.6.3:

```
[hz._hzInstance_1_dev.IO.thread-in-2] 2016-10-13T19:24:49.13+02:00 WARNING [com.hazelcast.nio.tcp.nonblocking.NonBlockingSocketReader]  [127.0.0.1]:5704 [dev] [3.6.3] hz._hzInstance_1_dev.IO.thread-in-2 Closing socket to endpoint Address[127.0.0.1]:5703, Cause:java.nio.channels.CancelledKeyException
java.nio.channels.CancelledKeyException
	at com.hazelcast.nio.tcp.nonblocking.NonBlockingIOThread.handleSelectionKey(NonBlockingIOThread.java:323)
	at com.hazelcast.nio.tcp.nonblocking.NonBlockingIOThread.handleSelectionKeys(NonBlockingIOThread.java:314)
	at com.hazelcast.nio.tcp.nonblocking.NonBlockingIOThread.selectLoop(NonBlockingIOThread.java:234)
	at com.hazelcast.nio.tcp.nonblocking.NonBlockingIOThread.run(NonBlockingIOThread.java:187)
```
