### ISSUE TITLE
MigrationCommitTest.shouldNotEvictCompletedMigrationsWhenSomeMembersDoNotAckPublishedPartitionTableAfterSuccessfulMigration

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#8686]
```
java.lang.AssertionError: null
    at org.junit.Assert.fail(Assert.java:86)
    at org.junit.Assert.assertTrue(Assert.java:41)
    at org.junit.Assert.assertTrue(Assert.java:52)
    at com.hazelcast.internal.partition.impl.MigrationCommitTest$6.run(MigrationCommitTest.java:433)
    at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:901)
    at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:915)
    at com.hazelcast.internal.partition.impl.MigrationCommitTest.shouldNotEvictCompletedMigrationsWhenSomeMembersDoNotAckPublishedPartitionTableAfterSuccessfulMigration(MigrationCommitTest.java:428)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-OracleJDK8/com.hazelcast$hazelcast/894/testReport/junit/com.hazelcast.internal.partition.impl/MigrationCommitTest/shouldNotEvictCompletedMigrationsWhenSomeMembersDoNotAckPublishedPartitionTableAfterSuccessfulMigration/

**Comment by metanet** [comment]
Closing this issue since it is a very old one with no recent failure. I've also checked the logs on S3 but it seems they are also deleted.
