### ISSUE TITLE
MapStoreWriteBehindTest.testOneMemberWriteBehind

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#8694]
```
org.junit.ComparisonFailure: expected:<value[1]> but was:<value[2]>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.map.impl.mapstore.MapStoreWriteBehindTest.testOneMemberWriteBehind(MapStoreWriteBehindTest.java:207)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.maintenance-OracleJDK1.6/com.hazelcast$hazelcast/413/testReport/junit/com.hazelcast.map.impl.mapstore/MapStoreWriteBehindTest/testOneMemberWriteBehind/

**Comment by ahmetmircik** [comment]
should be fixed by https://github.com/hazelcast/hazelcast/commit/561bcb65cd81ace365114acaa72474fb2337e92c
