### ISSUE TITLE
EntryProcessorBouncingNodesTest.testEntryProcessorWhileTwoNodesAreBouncing_withPredicate

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#8695]
```
java.lang.AssertionError: The ListHolder should contain ITERATIONS entries expected:<50> but was:<51>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:834)
    at org.junit.Assert.assertEquals(Assert.java:645)
    at com.hazelcast.map.EntryProcessorBouncingNodesTest.testEntryProcessorWhileTwoNodesAreBouncing(EntryProcessorBouncingNodesTest.java:167)
    at com.hazelcast.map.EntryProcessorBouncingNodesTest.testEntryProcessorWhileTwoNodesAreBouncing_withPredicate(EntryProcessorBouncingNodesTest.java:90)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast$hazelcast/997/testReport/junit/com.hazelcast.map/EntryProcessorBouncingNodesTest/testEntryProcessorWhileTwoNodesAreBouncing_withPredicate/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: The ListHolder should contain ITERATIONS entries expected:<50> but was:<51>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.map.EntryProcessorBouncingNodesTest.testEntryProcessorWhileTwoNodesAreBouncing(EntryProcessorBouncingNodesTest.java:167)
	at com.hazelcast.map.EntryProcessorBouncingNodesTest.testEntryProcessorWhileTwoNodesAreBouncing_withPredicate(EntryProcessorBouncingNodesTest.java:90)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-ZuluJDK7/com.hazelcast$hazelcast/296/testReport/junit/com.hazelcast.map/EntryProcessorBouncingNodesTest/testEntryProcessorWhileTwoNodesAreBouncing_withPredicate/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: The ListHolder should contain ITERATIONS entries expected:<50> but was:<51>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.map.EntryProcessorBouncingNodesTest.testEntryProcessorWhileTwoNodesAreBouncing(EntryProcessorBouncingNodesTest.java:167)
	at com.hazelcast.map.EntryProcessorBouncingNodesTest.testEntryProcessorWhileTwoNodesAreBouncing_withPredicate(EntryProcessorBouncingNodesTest.java:90)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast$hazelcast/1007/testReport/junit/com.hazelcast.map/EntryProcessorBouncingNodesTest/testEntryProcessorWhileTwoNodesAreBouncing_withPredicate/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: The ListHolder should contain ITERATIONS entries expected:<50> but was:<51>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.map.EntryProcessorBouncingNodesTest.testEntryProcessorWhileTwoNodesAreBouncing(EntryProcessorBouncingNodesTest.java:167)
	at com.hazelcast.map.EntryProcessorBouncingNodesTest.testEntryProcessorWhileTwoNodesAreBouncing_withPredicate(EntryProcessorBouncingNodesTest.java:90)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-OracleJDK1.7/com.hazelcast$hazelcast/294/testReport/junit/com.hazelcast.map/EntryProcessorBouncingNodesTest/testEntryProcessorWhileTwoNodesAreBouncing_withPredicate/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: The ListHolder should contain ITERATIONS entries expected:<50> but was:<51>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.map.EntryProcessorBouncingNodesTest.testEntryProcessorWhileTwoNodesAreBouncing(EntryProcessorBouncingNodesTest.java:167)
	at com.hazelcast.map.EntryProcessorBouncingNodesTest.testEntryProcessorWhileTwoNodesAreBouncing_withPredicate(EntryProcessorBouncingNodesTest.java:90)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x/com.hazelcast$hazelcast/5693/testReport/junit/com.hazelcast.map/EntryProcessorBouncingNodesTest/testEntryProcessorWhileTwoNodesAreBouncing_withPredicate/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: The ListHolder should contain ITERATIONS entries expected:<50> but was:<51>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.map.EntryProcessorBouncingNodesTest.testEntryProcessorWhileTwoNodesAreBouncing(EntryProcessorBouncingNodesTest.java:167)
	at com.hazelcast.map.EntryProcessorBouncingNodesTest.testEntryProcessorWhileTwoNodesAreBouncing_withPredicate(EntryProcessorBouncingNodesTest.java:90)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK8/lastCompletedBuild/com.hazelcast$hazelcast/testReport/com.hazelcast.map/EntryProcessorBouncingNodesTest/testEntryProcessorWhileTwoNodesAreBouncing_withPredicate/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: The ListHolder should contain ITERATIONS entries expected:<50> but was:<51>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.map.EntryProcessorBouncingNodesTest.testEntryProcessorWhileTwoNodesAreBouncing(EntryProcessorBouncingNodesTest.java:167)
	at com.hazelcast.map.EntryProcessorBouncingNodesTest.testEntryProcessorWhileTwoNodesAreBouncing_withPredicate(EntryProcessorBouncingNodesTest.java:90)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x/com.hazelcast$hazelcast/6150/testReport/junit/com.hazelcast.map/EntryProcessorBouncingNodesTest/testEntryProcessorWhileTwoNodesAreBouncing_withPredicate/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: The ListHolder should contain ITERATIONS entries expected:<50> but was:<51>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.map.EntryProcessorBouncingNodesTest.testEntryProcessorWhileTwoNodesAreBouncing(EntryProcessorBouncingNodesTest.java:167)
	at com.hazelcast.map.EntryProcessorBouncingNodesTest.testEntryProcessorWhileTwoNodesAreBouncing_withPredicate(EntryProcessorBouncingNodesTest.java:90)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x/com.hazelcast$hazelcast/6286/testReport/junit/com.hazelcast.map/EntryProcessorBouncingNodesTest/testEntryProcessorWhileTwoNodesAreBouncing_withPredicate/
