### ISSUE TITLE
ClientConnectionTest.destroyConnection_whenDestroyedMultipleTimes_thenListenerRemoveCalledOnce

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#8702]
```
java.lang.AssertionError: connection removed should be called only once expected:<1> but was:<2>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:834)
    at org.junit.Assert.assertEquals(Assert.java:645)
    at com.hazelcast.client.ClientConnectionTest.destroyConnection_whenDestroyedMultipleTimes_thenListenerRemoveCalledOnce(ClientConnectionTest.java:139)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK1.8/com.hazelcast$hazelcast-client/310/testReport/junit/com.hazelcast.client/ClientConnectionTest/destroyConnection_whenDestroyedMultipleTimes_thenListenerRemoveCalledOnce/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: connection removed should be called only once expected:<1> but was:<2>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.client.ClientConnectionTest.destroyConnection_whenDestroyedMultipleTimes_thenListenerRemoveCalledOnce(ClientConnectionTest.java:162)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x/com.hazelcast$hazelcast-client/5704/testReport/junit/com.hazelcast.client/ClientConnectionTest/destroyConnection_whenDestroyedMultipleTimes_thenListenerRemoveCalledOnce/

**Comment by sancar** [comment]
Closing the issue since it is not failed over a month and we dont have the logs the investigate.
