### ISSUE TITLE
CacheCloseTest.test_cacheDestroyOperation

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#8710]
```
java.lang.AssertionError: expected null, but was:<CacheConfig{name='MyCache', managerPrefix='/hz/', inMemoryFormat=BINARY, backupCount=1, hotRestart=HotRestartConfig{enabled=false, fsync=false}}>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotNull(Assert.java:755)
    at org.junit.Assert.assertNull(Assert.java:737)
    at org.junit.Assert.assertNull(Assert.java:747)
    at com.hazelcast.cache.CacheCloseTest$1.run(CacheCloseTest.java:107)
    at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:901)
    at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:915)
    at com.hazelcast.cache.CacheCloseTest.test_cacheDestroyOperation(CacheCloseTest.java:103)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-ZuluJDK8/com.hazelcast$hazelcast/294/testReport/junit/com.hazelcast.cache/CacheCloseTest/test_cacheDestroyOperation/

**Comment by mdogan** [comment]
No failures since Aug 12.
