### ISSUE TITLE
[map] [operation] OperationTimeoutException in Tomcat - Hazelcast 3.6.1

### ISSUE THREAD

**Issue by ngophucuong2306** [hazelcast/hazelcast#8712]
Hi,

This is the first time we implement Hazelcast 3.6.1 in our application. 
We have 8 clusters and this exception only happens when we try to update the cache. 
It works fine when we start the clusters and the cache is loaded for the first time. 
When we try to update the cache from the front end screen, heap utilization on Tomcat is crossing 85%.
We did thread dump analysis for the time when heap utilization was high and found that the threads related to hazelcast cache were hung. 
This issue does not happen if we do not update the cache. 
I have looked at several similar issues but there's no solution, especially for Tomcat 7.0.68 with HazelCast 3.6.x version.

Below is the logic we have used to update what is in cache. Please let us know if that is correct.
```
public void updateCacheMap(Map<String, Map<String, Map<String, Integer>>> newCacheMap){
        IMap<String, Object> cachedMap = getCacheInstance().getMap("MY_MAP");
        cachedMap.clear();
        cachedMap.putAll(newCacheMap);
    }
```

Following is the configuration that we have used:

```
private static Config getConfig(CacheConfig config){
        Config cfg = new Config();
    //setting the cache cluster name
    GroupConfig grpCfg = new GroupConfig();
    grpCfg.setName(config.getCacheClusterName());
    cfg.setGroupConfig(grpCfg);     

    String cacheHostMembers = config.getCacheHostMembers();

    //setting the configuration for Map
    MapConfig mapConfig = cfg.getMapConfig("*");
    mapConfig.setMaxIdleSeconds(0);
    mapConfig.setTimeToLiveSeconds(0);
    mapConfig.setEvictionPolicy(EvictionPolicy.LFU);
    mapConfig.getMaxSizeConfig().setMaxSizePolicy(MaxSizePolicy.PER_NODE).setSize(Constants.INT_10000);
    //setting the percentage for eviction
    mapConfig.setEvictionPercentage(Constants.INT_10);


    //setting the network configuration
    NetworkConfig netCfg = cfg.getNetworkConfig();
    netCfg.setPort(5800).setPortAutoIncrement(true);
    netCfg.setReuseAddress(true);
    netCfg.setPortCount(4);

    JoinConfig joinCfg = netCfg.getJoin();

    joinCfg.getMulticastConfig().setEnabled(false);
    joinCfg.getTcpIpConfig().setEnabled(true);

    if(cacheHostMembers!= null && cacheHostMembers.length()>0){
        StringTokenizer tokens = new StringTokenizer(cacheHostMembers, Constants.STR_COMMA);
        while(tokens.hasMoreTokens()){
            joinCfg.getTcpIpConfig().addMember((String) tokens.nextElement());
        }
    }

    //setting the logging configuration
    if(config.getLoggingType()!=null){
        cfg.setProperty( "hazelcast.logging.type", config.getLoggingType() );
    }

    return cfg;

}
```

App log stack trace:
```
com.hazelcast.core.OperationTimeoutException: No response for 120000 ms. Aborting invocation! Invocation{serviceName='hz:impl:mapService', op=com.hazelcast.map.impl.operation.ClearOperation{identityHash=1990728310, serviceName='hz:impl:mapService', partitionId=127, replicaIndex=0, callId=57684713, invocationTime=1470059029023 (Mon Aug 01 08:43:49 CDT 2016), waitTimeout=-1, callTimeout=60000, name=ACTIVE_ID_MAP}, partitionId=127, replicaIndex=0, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeout=60000, target=Address[tp115000.domain.com]:5700, backupsExpected=0, backupsCompleted=1, connection=Connection [/178.15.122.133:22345 -> sd2333.domain.com/178.18.6.135:3812], endpoint=Address[sd2333.domain.com]:5700, alive=true, type=MEMBER} No response has been received!  backups-expected:0 backups-completed: 1
    at com.hazelcast.spi.impl.operationservice.impl.Invocation.newOperationTimeoutException(Invocation.java:536)
    at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.waitForResponse(InvocationFuture.java:275)
    at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.get(InvocationFuture.java:222)
    at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.get(InvocationFuture.java:202)
    at com.hazelcast.spi.impl.operationservice.impl.InvokeOnPartitions.retryFailedPartitions(InvokeOnPartitions.java:131)
    at com.hazelcast.spi.impl.operationservice.impl.InvokeOnPartitions.invoke(InvokeOnPartitions.java:67)
    at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.invokeOnAllPartitions(OperationServiceImpl.java:368)
    at com.hazelcast.map.impl.proxy.MapProxySupport.clearInternal(MapProxySupport.java:754)
    at com.hazelcast.map.impl.proxy.MapProxyImpl.clearInternal(MapProxyImpl.java:80)
    at com.hazelcast.map.impl.proxy.MapProxyImpl.clear(MapProxyImpl.java:565)
    at com.domain.app.util.cache.HazelCache.updateActiveIdCacheMap(HazelCache.java:51)
    at com.domain.app.util.DataUtils.getAllActiveIds(DataUtils.java:707)
    at com.domain.app.util.DataUtils.getActiveIdMap(DataUtils.java:724)
    at com.domain.app.util.DataUtils$$FastClassByCGLIB$$e080733b.invoke(<generated>)
    at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
    at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:698)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
    at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:55)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:631)
    at com.domain.app.util.MasterDataUtils$$EnhancerByCGLIB$$ff67d36d.getactiveIdMap(<generated>)
    at com.domain.app.service.impl.OperationServiceImpl.getCourseDetails(OperationServiceImpl.java:459)
    at com.domain.app.service.impl.OperationServiceImpl.operationDetails(OperationServiceImpl.java:401)
    at com.domain.app.service.impl.OperationServiceImpl.getemployeeoperationProgram(OperationServiceImpl.java:287)
    at sun.reflect.GeneratedMethodAccessor571.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
    at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:55)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
    at com.sun.proxy.$Proxy71.getemployeeoperationProgram(Unknown Source)
    at com.domain.app.manager.impl.operationManagerImpl.getemployeeoperationProgram(operationManagerImpl.java:35)
    at com.domain.app.controller.employeeController.getemployeeoperationProgram(employeeController.java:119)
    at sun.reflect.GeneratedMethodAccessor570.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.springframework.web.method.support.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:219)
    at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:132)
    at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104)
    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:745)
    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:686)
    at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:80)
    at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:925)
    at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:856)
    at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:936)
    at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:827)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
    at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:812)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at org.apache.catalina.filters.ExpiresFilter.doFilter(ExpiresFilter.java:1201)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at com.domain.app.security.CSRFFilter.doFilterInternal(CSRFFilter.java:63)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:203)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
    at org.apache.catalina.valves.StuckThreadDetectionValve.invoke(StuckThreadDetectionValve.java:221)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:436)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1078)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1757)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1716)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    at java.lang.Thread.run(Thread.java:745)
    at ------ End remote and begin local stack-trace ------.(Unknown Source)
    at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveApplicationResponse(InvocationFuture.java:385)
    at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveApplicationResponseOrThrowException(InvocationFuture.java:335)
    at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.get(InvocationFuture.java:223)
    at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.get(InvocationFuture.java:202)
    at com.hazelcast.spi.impl.operationservice.impl.InvokeOnPartitions.retryFailedPartitions(InvokeOnPartitions.java:131)
    at com.hazelcast.spi.impl.operationservice.impl.InvokeOnPartitions.invoke(InvokeOnPartitions.java:67)
    at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.invokeOnAllPartitions(OperationServiceImpl.java:368)
    at com.hazelcast.map.impl.proxy.MapProxySupport.clearInternal(MapProxySupport.java:754)
    at com.hazelcast.map.impl.proxy.MapProxyImpl.clearInternal(MapProxyImpl.java:80)
    at com.hazelcast.map.impl.proxy.MapProxyImpl.clear(MapProxyImpl.java:565)
    at com.domain.app.util.cache.AppCache.updateactiveIdCacheMap(AppCache.java:51)
    at com.domain.app.util.MasterDataUtils.getAllactiveIds(MasterDataUtils.java:707)
    at com.domain.app.util.MasterDataUtils.getactiveIdMap(MasterDataUtils.java:724)
    at com.domain.app.util.MasterDataUtils$$FastClassByCGLIB$$e080733b.invoke(<generated>)
    at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
    at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:698)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
    at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:55)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:631)
    at com.domain.app.util.MasterDataUtils$$EnhancerByCGLIB$$ff67d36d.getactiveIdMap(<generated>)
    at com.domain.app.service.impl.OperationServiceImpl.getCourseDetails(OperationServiceImpl.java:459)
    at com.domain.app.service.impl.OperationServiceImpl.operationDetails(OperationServiceImpl.java:401)
    at com.domain.app.service.impl.OperationServiceImpl.getemployeeoperationProgram(OperationServiceImpl.java:287)
    at sun.reflect.GeneratedMethodAccessor571.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
    at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:55)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
    at com.sun.proxy.$Proxy71.getemployeeoperationProgram(Unknown Source)
    at com.domain.app.manager.impl.operationManagerImpl.getemployeeoperationProgram(operationManagerImpl.java:35)
    at com.domain.app.controller.employeeController.getemployeeoperationProgram(employeeController.java:119)
    at sun.reflect.GeneratedMethodAccessor570.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.springframework.web.method.support.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:219)
    at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:132)
    at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104)
    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:745)
    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:686)
    at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:80)
    at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:925)
    at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:856)
    at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:936)
    at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:827)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
    at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:812)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at org.apache.catalina.filters.ExpiresFilter.doFilter(ExpiresFilter.java:1201)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at com.domain.app.security.CSRFFilter.doFilterInternal(CSRFFilter.java:63)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:203)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
    at org.apache.catalina.valves.StuckThreadDetectionValve.invoke(StuckThreadDetectionValve.java:221)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:436)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1078)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1757)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1716)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    at java.lang.Thread.run(Thread.java:745)
```

Catalina log:
```
org.apache.catalina.valves.StuckThreadDetectionValve notifyStuckThreadDetected
WARNING: Thread "http-nio-54389-exec-38" (id=628) has been active for 602,259 milliseconds (since 8/1/16 3:47 PM) to serve the same request for https://app.domain.com/app/main/courseStatus/222333444/144619/SHELF124_T4-C13/1/2272?noCache=1470084465625 and may be stuck (configured threshold for this StuckThreadDetectionValve is 600 seconds). There is/are 5 thread(s) in total that are monitored by this Valve and may be stuck.
```

**Comment by jerrinot** [comment]
@ngophucuong2306: can you try it with Hazelcast 3.7? IT has much improved diagnostics capabilities.

**Comment by ngophucuong2306** [comment]
@jerrinot  I have just checked the release notes for versions later than 3.6.1 but could not find any fix for this. I don't think we can try to roll out to production until we are sure that this problem is fixed (the application was backed out because of this issue and it affected a lot of users). Is there anything I may have missed in 3.7 that will fix this issue?

**Comment by jerrinot** [comment]
@ngophucuong2306 Hazelcast 3.7 has massive changes in the invocation system.

**Comment by tombujok** [comment]
@ngophucuong2306 Could you plz try with 3.7.4 and 3.8-EA?
There's a high chance it has been fixed. Quick feedback appreciated

**Comment by tombujok** [comment]
@ngophucuong2306 any chance for an update about retesting with newest 3.7.x or a reproducer? We're in a bug-fixing stage and we could act on it quickly.

**Comment by ngophucuong2306** [comment]
@tombujok 
We tried the 3.7.4 on production yesterday and facing the same behavior with different error:

`2017-01-18 15:02:55 ERROR - Exception occured in Util Method of getCacheMap
com.hazelcast.core.OperationTimeoutException: ClearOperation invocation failed to complete due to operation-heartbeat-timeout. Current time: 2017-01-18 15:02:55.806. Total elapsed time: 120992 ms. Last operation heartbeat: never. Last operation heartbeat from member: 2017-01-18 14:58:48.408. Invocation{op=com.hazelcast.map.impl.operation.ClearOperation{serviceName='hz:impl:mapService', identityHash=1896505810, partitionId=76, replicaIndex=0, callId=0, invocationTime=1484773254813 (2017-01-18 15:00:54.813), waitTimeout=-1, callTimeout=60000, name=ID_MAP}, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=60000, firstInvocationTimeMs=1484773254814, firstInvocationTime='2017-01-18 15:00:54.814', lastHeartbeatMillis=0, lastHeartbeatTime='1969-12-31 18:00:00.000', target=[server1.com]:1700, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=1, connection=Connection[id=6, /->server1.com/, endpoint=[server1.com]:1700, alive=true, type=MEMBER]}
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.newOperationTimeoutException(InvocationFuture.java:150)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:98)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrow(InvocationFuture.java:74)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:158)
	at com.hazelcast.spi.impl.operationservice.impl.InvokeOnPartitions.retryFailedPartitions(InvokeOnPartitions.java:139)
	at com.hazelcast.spi.impl.operationservice.impl.InvokeOnPartitions.invoke(InvokeOnPartitions.java:70)
	at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.invokeOnAllPartitions(OperationServiceImpl.java:359)
	at com.hazelcast.map.impl.proxy.MapProxySupport.clearInternal(MapProxySupport.java:901)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.clearInternal(MapProxyImpl.java:82)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.clear(MapProxyImpl.java:584)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:698)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
	at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:55)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:631)`

**Comment by jerrinot** [comment]
@ngophucuong2306: hi, is there any other suspiciously looking log entry in logs?

**Comment by tombujok** [comment]
@ngophucuong2306 I'm willing to work on this issue, but in order to do so I need more info:
- What's your use case?
- Do you use IMap only? 
- How much data (of what kind/size) do you load to the IMap? 
- Does the threads hang on first update call? 
- Are you sure that the map-loading has finished (you mentioned something about loading). Do you use map-loader (what settings?)
- How do you deploy your app to tomcat?

It would be great if you could send me a small reproducer, one tomcat instance, sample config that causes the error. Otherwise, it's too generic to figure out what goes wrong.

**Comment by sobhaw** [comment]
We are also facing the same issue  in 3.6.5 version.  When we pile up the load and run and there is a constant update to Hazelcast Map this is happening. We wanted the map to be available in the cluster and so that the values updated in both can be seen. SHould we reduce the timing from 120s and see?

**Comment by tombujok** [comment]
@sobhaw do you also run HZ on tomcat? Could you explain your use-case more precisely?

**Comment by sobhaw** [comment]
we run on Fuse 6.1 karaf containers with 2 VM . we only have Maploader .
Multiple threads are running.. We have a sequencing task based on the fault
occurance time. It should go in order , so we enter in cache from both
clusters the data and only proceed in order. If we do normal run we see
this issue very rare. but once we do load run it is more often.

But it happens quite often.

Should we make the 120s lesser and reduce the number of threads so that
Hazelcast threads run.

Do let us know.

Sobha

**Comment by jerrinot** [comment]
moving the 3.9 as it's not yet confirmed to be a bug -> not a 3.8 blocker.

**Comment by tombujok** [comment]
no reproducer or any further report. Plz reopen in case of new info.
