### ISSUE TITLE
SecondsBasedEntryTaskSchedulerTest.test_doNotRescheduleEntryWithinSameSecond_postpone

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#8728]
```
java.lang.AssertionError: First schedule() call should always be successful
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.assertTrue(Assert.java:41)
    at com.hazelcast.util.scheduler.SecondsBasedEntryTaskSchedulerTest.test_doNotRescheduleEntryWithinSameSecond_postpone(SecondsBasedEntryTaskSchedulerTest.java:85)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-ZuluJDK7/com.hazelcast$hazelcast/299/testReport/junit/com.hazelcast.util.scheduler/SecondsBasedEntryTaskSchedulerTest/test_doNotRescheduleEntryWithinSameSecond_postpone/

**Comment by Donnerbart** [comment]
```
java.lang.AssertionError: First schedule() call should always be successful
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.util.scheduler.SecondsBasedEntryTaskSchedulerTest.test_doNotRescheduleEntryWithinSameSecond_postpone(SecondsBasedEntryTaskSchedulerTest.java:85)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/4330/testReport/junit/com.hazelcast.util.scheduler/SecondsBasedEntryTaskSchedulerTest/test_doNotRescheduleEntryWithinSameSecond_postpone/

**Comment by Donnerbart** [comment]
```
java.lang.AssertionError: First schedule() call should always be successful
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.util.scheduler.SecondsBasedEntryTaskSchedulerTest.test_doNotRescheduleEntryWithinSameSecond_postpone(SecondsBasedEntryTaskSchedulerTest.java:85)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/4561/testReport/junit/com.hazelcast.util.scheduler/SecondsBasedEntryTaskSchedulerTest/test_doNotRescheduleEntryWithinSameSecond_postpone/

**Comment by Donnerbart** [comment]
I removed the `ParallelTest` category from this test, so the timing sensitive test should not run concurrently with other tests. https://github.com/hazelcast/hazelcast/commit/9e3cad6310cfdff251e657d82cf370233db0303b

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: First schedule() call should always be successful
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.util.scheduler.SecondsBasedEntryTaskSchedulerTest.test_doNotRescheduleEntryWithinSameSecond_postpone(SecondsBasedEntryTaskSchedulerTest.java:85)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-IbmJDK1.7/com.hazelcast$hazelcast/433/testReport/junit/com.hazelcast.util.scheduler/SecondsBasedEntryTaskSchedulerTest/test_doNotRescheduleEntryWithinSameSecond_postpone/

**Comment by hasancelik** [comment]
*maintenance*
```
java.lang.AssertionError: First schedule() call should always be successful
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.util.scheduler.SecondsBasedEntryTaskSchedulerTest.test_doNotRescheduleEntryWithinSameSecond_postpone(SecondsBasedEntryTaskSchedulerTest.java:85)

```
https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.maintenance-ZuluJDK6/com.hazelcast$hazelcast/125/testReport/junit/com.hazelcast.util.scheduler/SecondsBasedEntryTaskSchedulerTest/test_doNotRescheduleEntryWithinSameSecond_postpone/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: First schedule() call should always be successful
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.util.scheduler.SecondsBasedEntryTaskSchedulerTest.test_doNotRescheduleEntryWithinSameSecond_postpone(SecondsBasedEntryTaskSchedulerTest.java:87)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x/com.hazelcast$hazelcast/5863/testReport/junit/com.hazelcast.util.scheduler/SecondsBasedEntryTaskSchedulerTest/test_doNotRescheduleEntryWithinSameSecond_postpone/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: First schedule() call should always be successful
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.util.scheduler.SecondsBasedEntryTaskSchedulerTest.test_doNotRescheduleEntryWithinSameSecond_postpone(SecondsBasedEntryTaskSchedulerTest.java:87)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x/com.hazelcast$hazelcast/5950/testReport/junit/com.hazelcast.util.scheduler/SecondsBasedEntryTaskSchedulerTest/test_doNotRescheduleEntryWithinSameSecond_postpone/
