### ISSUE TITLE
NullPointerException when DefaultNodeExtension class has been loaded by two different class-loaders.

### ISSUE THREAD

**Issue by ttddlplp** [hazelcast/hazelcast#8755]
`java.lang.NullPointerException
	at com.hazelcast.instance.NodeExtensionFactory.create(NodeExtensionFactory.java:42)
	at com.hazelcast.instance.DefaultNodeContext.createNodeExtension(DefaultNodeContext.java:35)
	at com.hazelcast.instance.Node.createNodeExtension(Node.java:290)
	at com.hazelcast.instance.Node.<init>(Node.java:177)
	at com.hazelcast.instance.HazelcastInstanceImpl.createNode(HazelcastInstanceImpl.java:155)
	at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:126)
	at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:218)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:176)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:126)
	at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:58)`

At NodeExtensionFactory.class line 43, when DefaultNodeExtension class has been loaded by two different class-loaders, it tries to generate logging, but node.nodeEngine is null at that point, therefore cause NullPointerException: 

`if (clazz.getName().equals(DefaultNodeExtension.class.getName())) {
                        node.nodeEngine.getLogger(NodeExtensionFactory.class).warning(
                                "DefaultNodeExtension class has been loaded by two different class-loaders. "
                                        + "Are you running Hazelcast in an OSGi environment? "
                                        + "If so, set the bundle class-loader in the Config using the setClassloader() method");
                    }`

**Comment by jerrinot** [comment]
@ttddlplp: many thanks for your bug-report. it will be fixed in the next patch release.

**Comment by tombujok** [comment]
@ttddlplp thx for your report. Issue should be fixed in 3.7.1 and 3.8.
