### ISSUE TITLE
Member OOM making a simple (heap) map set operation  test, using large value size (1MB approx min) 

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#8756]
3.8-SNAPSHOT 

I am getting Member OOM making a simple (heap) map set operation  test, using large value size (1MB approx min)  the full logs and settings are hear http://54.87.52.100/~jenkins/workspace/aws-hot-bounce-clear/3.8-SNAPSHOT/2016_08_22-10_25_09/

I think this was the first member to OOM http://54.87.52.100/~jenkins/workspace/aws-hot-bounce-clear/3.8-SNAPSHOT/2016_08_22-10_25_09/output/HZ/HzMember2HZ/

![](https://files.slack.com/files-pri/T024PDR4H-F23H2CL0H/pasted_image_at_2016_08_22_11_44_am.png)

my map name is `mapBak1`

the config is http://54.87.52.100/~jenkins/workspace/aws-hot-bounce-clear/3.8-SNAPSHOT/2016_08_22-10_25_09/config-hz/hazelcast.xml

so using

```
<map name="mapBak1*">
<in-memory-format>BINARY</in-memory-format>
<backup-count>1</backup-count>
<hot-restart enabled="false">
<fsync>false</fsync>
</hot-restart>
</map>
```

the key domain is `mapBak1Set@keyDomain=1000`

and value size `mapBak1Set@valueSize=1000000`

member heap is `-Xms4G -Xmx4G`
even using 12G gives same results

```
Aug 22, 2016 7:31:08 AM com.hazelcast.nio.tcp.TcpIpConnection
WARNING: [10.0.0.160]:5701 [HZ] [3.8-SNAPSHOT] Connection[id=31, /10.0.0.160:5701->/10.0.0.163:38612, endpoint=[10.0.0.163]:38612, alive=false, type=JAVA_CLIENT] closed. Reason: Exception in NonBlockingSocketReader
java.lang.OutOfMemoryError: Java heap space
    at com.hazelcast.client.impl.protocol.ClientMessage.readFrom(ClientMessage.java:343)
    at com.hazelcast.client.impl.protocol.util.ClientMessageBuilder.onData(ClientMessageBuilder.java:45)
    at com.hazelcast.nio.tcp.ClientReadHandler.onRead(ClientReadHandler.java:52)
    at com.hazelcast.nio.tcp.nonblocking.NonBlockingSocketReader.handle(NonBlockingSocketReader.java:159)
    at com.hazelcast.nio.tcp.nonblocking.NonBlockingIOThread.handleSelectionKey(NonBlockingIOThread.java:345)
    at com.hazelcast.nio.tcp.nonblocking.NonBlockingIOThread.handleSelectionKeys(NonBlockingIOThread.java:330)
    at com.hazelcast.nio.tcp.nonblocking.NonBlockingIOThread.selectLoop(NonBlockingIOThread.java:248)
    at com.hazelcast.nio.tcp.nonblocking.NonBlockingIOThread.run(NonBlockingIOThread.java:201)

Aug 22, 2016 7:31:11 AM com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor
INFO: [10.0.0.160]:5701 [HZ] [3.8-SNAPSHOT] Invocations:87 timeouts:0 backup-timeouts:77
#
# java.lang.OutOfMemoryError: Java heap space
# -XX:OnOutOfMemoryError=" date >> HzMember2HZ.oome"
#   Executing /bin/sh -c "date >> HzMember2HZ.oome"...
Aug 22, 2016 7:31:12 AM com.hazelcast.nio.tcp.TcpIpConnection
WARNING: [10.0.0.160]:5701 [HZ] [3.8-SNAPSHOT] Connection[id=24, /10.0.0.160:5701->/10.0.0.163:38602, endpoint=[10.0.0.163]:38602, alive=false, type=JAVA_CLIENT] closed. Reason: Exception in NonBlockingSocketReader
java.lang.OutOfMemoryError: Java heap space
    at com.hazelcast.client.impl.protocol.ClientMessage.readFrom(ClientMessage.java:343)
    at com.hazelcast.client.impl.protocol.util.ClientMessageBuilder.onData(ClientMessageBuilder.java:45)
    at com.hazelcast.nio.tcp.ClientReadHandler.onRead(ClientReadHandler.java:52)
    at com.hazelcast.nio.tcp.nonblocking.NonBlockingSocketReader.handle(NonBlockingSocketReader.java:159)
    at com.hazelcast.nio.tcp.nonblocking.NonBlockingIOThread.handleSelectionKey(NonBlockingIOThread.java:345)
    at com.hazelcast.nio.tcp.nonblocking.NonBlockingIOThread.handleSelectionKeys(NonBlockingIOThread.java:330)
    at com.hazelcast.nio.tcp.nonblocking.NonBlockingIOThread.selectLoop(NonBlockingIOThread.java:248)
    at com.hazelcast.nio.tcp.nonblocking.NonBlockingIOThread.run(NonBlockingIOThread.java:201)
```

http://54.87.52.100/~jenkins/workspace/aws-hot-bounce-clear/3.8-SNAPSHOT/2016_08_22-10_25_09/output/HZ/HzMember2HZ/HzMember2HZ.hprof

**Comment by Danny-Hazelcast** [comment]
we see 

```
INFO: [10.0.0.160]:5701 [HZ] [3.8-SNAPSHOT] Invocations:154 timeouts:0 backup-timeouts:11
Aug 22, 2016 7:27:36 AM com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor
INFO: [10.0.0.160]:5701 [HZ] [3.8-SNAPSHOT] Invocations:164 timeouts:0 backup-timeouts:1
Aug 22, 2016 7:27:37 AM com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor
INFO: [10.0.0.160]:5701 [HZ] [3.8-SNAPSHOT] Invocations:166 timeouts:0 backup-timeouts:1
Aug 22, 2016 7:27:38 AM com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor
INFO: [10.0.0.160]:5701 [HZ] [3.8-SNAPSHOT] Invocations:156 timeouts:0 backup-timeouts:4
```

on all members.  before backup time out 

using settings  http://54.87.52.100/~jenkins/workspace/aws-hot-bounce-clear/3.8-SNAPSHOT/2016_08_22-10_25_09/go

```
ops="$ops -Dhazelcast.enterprise.license.key=${HAZELCAST_EE_KEY}"
ops="$ops -Dhazelcast.backpressure.enabled=true"
ops="$ops -ea"
ops="$ops -XX:+PrintFlagsFinal -XX:+UseLargePages"

mOps="$mOps -Dhazelcast.operation.call.timeout.millis=600000"
mOps="$mOps -Dhazelcast.hotrestart.gc.stuck.detect.threshold=10000"
mOps="$mOps -Dhazelcast.hotrestart.free.native.memory.percentage=15"
mOps="$mOps -Dhazelcast.hidensity.check.freememory=false"
```

**Comment by Danny-Hazelcast** [comment]
@jerrinot  recommended adding  (I put in the wrong property last run)

mOps="$mOps -Dhazelcast.operation.backup.timeout.millis=120000"

running with this added. 
http://54.87.52.100/~jenkins/workspace/aws-hot-bounce-clear/3.8-SNAPSHOT/2016_08_22-12_59_31/

And it seems to be running ok for approx 1H.

I am not sure why, back up time out's should lead to a Member OOME.  is this an issue inits self ?

**Comment by Danny-Hazelcast** [comment]
it likely creates a backlog of backup operations - as the 5s waiting threshold is reached quite often with such a massive payload -> it behaves similarly as async operations with no backpressure

**Comment by Danny-Hazelcast** [comment]
@ahmetmircik  @jerrinot  I am happy to close this issue.

**Comment by ahmetmircik** [comment]
@Danny-Hazelcast is this still happening? I cant reach the logs&dumps

**Comment by tombujok** [comment]
Closing since problem solved by increasing the timeout backup
