### ISSUE TITLE
MigrationCorrectnessTest.testPartitionData_whenNodesStartedParallel

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#8773]
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.internal.partition.PartitionCorrectnessTestSupport.startNodes(PartitionCorrectnessTestSupport.java:98)
	at com.hazelcast.internal.partition.AbstractMigrationCorrectnessTest.testPartitionData_whenNodesStartedParallel(AbstractMigrationCorrectnessTest.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:88)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:82)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.lang.Thread.run(Thread.java:662)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-OracleJDK1.6/com.hazelcast$hazelcast/1015/testReport/junit/com.hazelcast.internal.partition/MigrationCorrectnessTest/testPartitionData_whenNodesStartedParallel_backups_1_nodes_2_/

**Comment by metanet** [comment]
This is not an actual test failure. Nodes failed to start in 2 mins in the beginning of the test.
