### ISSUE TITLE
Management Center looses Connection to Cluster when set to passive

### ISSUE THREAD

**Issue by noctarius** [hazelcast/hazelcast#8780]
Test Setup: 
- 2 Nodes up and running 
- Mancenter connected

Test Scenario: 
- Set Cluster to passive state in hot restart tab in Mancenter 
- Set Cluster to active state in hot restart tab in Mancenter

Findings: 
Once Cluster is in passive state it cannot be change to active state again. 
Error Message Popup in Mancenter says: 
Error! 
Cluster State Update failed. Reason: No Cluster Data

```
16:27:44.400 [hz._hzInstance_1_cache-dev.partition-operation.thread-3] ERROR com.hazelcast.map.impl.operation.ClearExpiredOperation - [dcplnx21830480.sbb.ch]:5702 [-cache-dev] [3.6.4] Cluster is in PASSIVE state! Operation: com.hazelcast.map.impl.operation.ClearExpiredOperation{identityHash=129664851, serviceName='hz:impl:mapService', partitionId=7, replicaIndex=0, callId=0, invocationTime=-1 (Thu Jan 01 00:59:59 CET 1970), waitTimeout=-1, callTimeout=9223372036854775807, expirationPercentage=10} 
java.lang.IllegalStateException: Cluster is in PASSIVE state! Operation: com.hazelcast.map.impl.operation.ClearExpiredOperation{identityHash=129664851, serviceName='hz:impl:mapService', partitionId=7, replicaIndex=0, callId=0, invocationTime=-1 (Thu Jan 01 00:59:59 CET 1970), waitTimeout=-1, callTimeout=9223372036854775807, expirationPercentage=10} 
at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.checkNodeState(OperationRunnerImpl.java:200) [hazelcast-enterprise-all-3.6.4.jar:?] 
at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:156) [hazelcast-enterprise-all-3.6.4.jar:?] 
at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.processOperation(OperationThread.java:198) [hazelcast-enterprise-all-3.6.4.jar:?] 
at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.process(OperationThread.java:132) [hazelcast-enterprise-all-3.6.4.jar:?] 
at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.doRun(OperationThread.java:124) [hazelcast-enterprise-all-3.6.4.jar:?] 
at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.run(OperationThread.java:99) [hazelcast-enterprise-all-3.6.4.jar:?]
```

**Comment by emrahkocaman** [comment]
Are you using HD maps?

**Comment by noctarius** [comment]
Yes, please contact me in Slack to get more insight.

**Comment by emrahkocaman** [comment]
Closing this issue as management center service connection problem is fixed by https://github.com/hazelcast/hazelcast-enterprise/issues/1009.

The exception in the logs is not related to this connection problem. So I'm closing this issue and kindly suggest creating another one about "java.lang.IllegalStateException" with a reproducer if possible.
