### ISSUE TITLE
getForUpdate: Transaction couldn't obtain lock for the key

### ISSUE THREAD

**Issue by dmitrymz** [hazelcast/hazelcast#8793]
we are intensively updating records via transactions and using getForUpdate method.
sometimes we get this exception, and transaction takes approximately the same time we specified in timeout

```
com.hazelcast.transaction.TransactionException: Transaction couldn't obtain lock for the key: HeapData{type=-11, hashCode=-1899369607, partitionHash=-1899369607, totalSize=48, dataSize=40, heapCost=68}
        at com.hazelcast.map.impl.tx.TransactionalMapProxySupport.lockAndGet(TransactionalMapProxySupport.java:270) ~[hazelcast-3.6.4.jar:3.6.4]
        at com.hazelcast.map.impl.tx.TransactionalMapProxySupport.getForUpdateInternal(TransactionalMapProxySupport.java:117) ~[hazelcast-3.6.4.jar:3.6.4]
        at com.hazelcast.map.impl.tx.TransactionalMapProxy.getForUpdate(TransactionalMapProxy.java:124) ~[hazelcast-3.6.4.jar:3.6.4]
        at com.hazelcast.client.impl.protocol.task.transactionalmap.TransactionalMapGetForUpdateMessageTask.innerCall(TransactionalMapGetForUpdateMessageTask.java:43) ~[hazelcast-3.6.4.jar:3.6.4]
        at com.hazelcast.client.impl.protocol.task.AbstractTransactionalMessageTask.call(AbstractTransactionalMessageTask.java:34) ~[hazelcast-3.6.4.jar:3.6.4]
        at com.hazelcast.client.impl.protocol.task.AbstractCallableMessageTask.processMessage(AbstractCallableMessageTask.java:34) ~[hazelcast-3.6.4.jar:3.6.4]
        at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:118) ~[hazelcast-3.6.4.jar:3.6.4]
        at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:98) ~[hazelcast-3.6.4.jar:3.6.4]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_20]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_20]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_20]
        at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76) ~[hazelcast-3.6.4.jar:3.6.4]
        at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92) ~[hazelcast-3.6.4.jar:3.6.4]
        at ------ End remote and begin local stack-trace ------.(Unknown Source) ~[na:na]
        at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveResponse(ClientInvocationFuture.java:128) ~[hazelcast-client-3.6.4.jar:3.6.4]
        at com.hazelcast.client.spi.impl.ClientInvocationFuture.get(ClientInvocationFuture.java:95) ~[hazelcast-client-3.6.4.jar:3.6.4]
        at com.hazelcast.client.spi.impl.ClientInvocationFuture.get(ClientInvocationFuture.java:74) ~[hazelcast-client-3.6.4.jar:3.6.4]
        at com.hazelcast.client.spi.impl.ClientInvocationFuture.get(ClientInvocationFuture.java:37) ~[hazelcast-client-3.6.4.jar:3.6.4]
        at com.hazelcast.client.proxy.txn.ClientTxnProxy.invoke(ClientTxnProxy.java:48) ~[hazelcast-client-3.6.4.jar:3.6.4]
        at com.hazelcast.client.proxy.txn.ClientTxnMapProxy.getForUpdate(ClientTxnMapProxy.java:81) ~[hazelcast-client-3.6.4.jar:3.6.4]
```

This is our typical transaction cycle:
```

        TransactionOptions options = new TransactionOptions()
                .setTransactionType(TransactionOptions.TransactionType.ONE_PHASE)
                .setTimeout(hztrans.timeout(), TimeUnit.MILLISECONDS);

        TransactionContext context = ctx.createTransactionContext(options);
        context.beginTransaction();

        try {
            TransactionalMap map = context.getMap();
             Value ob = map.getForUpdate("key"):
             // other things

            context.commitTransaction();
            return res;
        } catch (Exception e) {
            context.rollbackTransaction();
            throw e;
        } finally {
            ctx.destroyTransactionContext();
        }
```

from TransactionalMapProxySupport.lockAndGet()

```
            Future<VersionedValue> future = nodeEngine.getOperationService()
                    .invokeOnPartition(MapService.SERVICE_NAME, operation, partitionId);
            versionedValue = future.get();
            if (versionedValue == null) {
                throw new TransactionException("Transaction couldn't obtain lock for the key: " + toObjectIfNeeded(key));
            }
```

could you please, explain, what are we doing wrong, and how should we handle this exception?

**Comment by dmitrymz** [comment]
This is our typical transaction cycle:

```
        TransactionOptions options = new TransactionOptions()
                .setTransactionType(TransactionOptions.TransactionType.ONE_PHASE)
                .setTimeout(hztrans.timeout(), TimeUnit.MILLISECONDS);

        TransactionContext context = ctx.createTransactionContext(options);
        context.beginTransaction();

        try {
            TransactionalMap map = context.getMap();
             Value ob = map.getForUpdate("key"):
             // other things

            context.commitTransaction();
            return res;
        } catch (Exception e) {
            context.rollbackTransaction();
            throw e;
        } finally {
            ctx.destroyTransactionContext();
        }
```

**Comment by dmitrymz** [comment]
from TransactionalMapProxySupport.lockAndGet()

```
            Future<VersionedValue> future = nodeEngine.getOperationService()
                    .invokeOnPartition(MapService.SERVICE_NAME, operation, partitionId);
            versionedValue = future.get();
            if (versionedValue == null) {
                throw new TransactionException("Transaction couldn't obtain lock for the key: " + toObjectIfNeeded(key));
            }
```

versionedValue is null... what that means?

could you please, explain, what are we doing wrong, and how should we handle this exception?

**Comment by dmitrymz** [comment]
another problem is lockAndGet takes timeout param, where the timeout is specified for the whole transaction not just for this method, but that's a separate issue.
