### ISSUE TITLE
Hazelcast 3.7 errors with Zing JVM

### ISSUE THREAD

**Issue by joanbalaguero** [hazelcast/hazelcast#8835]
After upgrading from Hz 3.6.2 to Hz 3.7 with Zing JVM, Tomcat log shows these errors:
```
01-Sep-2016 09:56:07.485 WARNING [localhost-startStop-1] com.hazelcast.config.AbstractXmlConfigHelper.null Name of the hazelcast schema location incorrect using default
01-Sep-2016 09:56:09.230 WARNING [localhost-startStop-1] com.hazelcast.config.AbstractXmlConfigHelper.null Name of the hazelcast schema location incorrect using default
01-Sep-2016 09:56:15.978 WARNING [hz._hzInstance_1_ventusproxy01.partition-operation.thread-5] com.hazelcast.util.JVMUtil.null Failed to read HotSpot specific configuration
 javax.management.RuntimeMBeanException: java.lang.IllegalArgumentException: VM option "UseCompressedOops" does not exist
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.rethrow(DefaultMBeanServerInterceptor.java:839)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.rethrowMaybeMBeanException(DefaultMBeanServerInterceptor.java:852)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:821)
        at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
        at com.hazelcast.util.JVMUtil.isHotSpotCompressedOopsOrNull(JVMUtil.java:69)
        at com.hazelcast.util.JVMUtil.isCompressedOops(JVMUtil.java:46)
        at com.hazelcast.util.JVMUtil.<clinit>(JVMUtil.java:39)
        at com.hazelcast.internal.serialization.impl.HeapData.getHeapCost(HeapData.java:96)
        at com.hazelcast.map.impl.BinaryMapSizeEstimator.calculateSize(BinaryMapSizeEstimator.java:54)
        at com.hazelcast.map.impl.recordstore.StorageImpl.calculateHeapCost(StorageImpl.java:144)
        at com.hazelcast.map.impl.recordstore.StorageImpl.put(StorageImpl.java:75)
        at com.hazelcast.map.impl.recordstore.StorageImpl.put(StorageImpl.java:41)
        at com.hazelcast.map.impl.recordstore.DefaultRecordStore.putIfAbsent(DefaultRecordStore.java:946)
        at com.hazelcast.map.impl.operation.PutIfAbsentOperation.run(PutIfAbsentOperation.java:34)
        at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:181)
        at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:122)
        at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:102)
Caused by: java.lang.IllegalArgumentException: VM option "UseCompressedOops" does not exist
        at sun.management.HotSpotDiagnostic.getVMOption(HotSpotDiagnostic.java:73)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:75)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:281)
        at com.sun.jmx.mbeanserver.ConvertingMethod.invokeWithOpenReturn(ConvertingMethod.java:193)
        at com.sun.jmx.mbeanserver.ConvertingMethod.invokeWithOpenReturn(ConvertingMethod.java:175)
        at com.sun.jmx.mbeanserver.MXBeanIntrospector.invokeM2(MXBeanIntrospector.java:117)
        at com.sun.jmx.mbeanserver.MXBeanIntrospector.invokeM2(MXBeanIntrospector.java:54)
        at com.sun.jmx.mbeanserver.MBeanIntrospector.invokeM(MBeanIntrospector.java:237)
        at com.sun.jmx.mbeanserver.PerInterface.invoke(PerInterface.java:138)
        at com.sun.jmx.mbeanserver.MBeanSupport.invoke(MBeanSupport.java:252)
        at javax.management.StandardMBean.invoke(StandardMBean.java:405)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
        ... 14 more

01-Sep-2016 09:56:15.982 WARNING [hz._hzInstance_1_ventusproxy01.partition-operation.thread-5] com.hazelcast.util.JVMUtil.null obj1
 java.lang.NoSuchFieldException: obj1
        at java.lang.Class.getField(Class.java:1584)
        at com.hazelcast.util.JVMUtil.isCompressedOopsOrNull(JVMUtil.java:93)
        at com.hazelcast.util.JVMUtil.isCompressedOops(JVMUtil.java:52)
        at com.hazelcast.util.JVMUtil.<clinit>(JVMUtil.java:39)
        at com.hazelcast.internal.serialization.impl.HeapData.getHeapCost(HeapData.java:96)
        at com.hazelcast.map.impl.BinaryMapSizeEstimator.calculateSize(BinaryMapSizeEstimator.java:54)
        at com.hazelcast.map.impl.recordstore.StorageImpl.calculateHeapCost(StorageImpl.java:144)
        at com.hazelcast.map.impl.recordstore.StorageImpl.put(StorageImpl.java:75)
        at com.hazelcast.map.impl.recordstore.StorageImpl.put(StorageImpl.java:41)
        at com.hazelcast.map.impl.recordstore.DefaultRecordStore.putIfAbsent(DefaultRecordStore.java:946)
        at com.hazelcast.map.impl.operation.PutIfAbsentOperation.run(PutIfAbsentOperation.java:34)
        at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:181)
        at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:122)
        at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:102)
```

**Comment by vbekiaris** [comment]
Thanks for reporting this issue @joanbalaguero 
The second `NoSuchFieldException` is an issue in code that detects memory cost of reference which should be fixed by #8834

**Comment by Petikoch** [comment]
I see the same issue, but on a **Oracle JVM** (Java 8 Update 60, 32-bit, Windows), using Hazelcast 3.7.1:

```
INFORMATION: [10.0.16.165]:5701 [b7cd02b1-b86c-4755-891b-3f65bf5df93d] [3.7.1] [10.0.16.165]:5701 is STARTED
Sep 06, 2016 9:46:27 AM com.hazelcast.internal.partition.impl.PartitionStateManager
INFORMATION: [10.0.16.165]:5701 [b7cd02b1-b86c-4755-891b-3f65bf5df93d] [3.7.1] Initializing cluster partition table arrangement...
Sep 06, 2016 9:46:27 AM com.hazelcast.util.JVMUtil
WARNUNG: Failed to read HotSpot specific configuration
javax.management.RuntimeMBeanException: java.lang.IllegalArgumentException: VM option "UseCompressedOops" does not exist
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.rethrow(DefaultMBeanServerInterceptor.java:839)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.rethrowMaybeMBeanException(DefaultMBeanServerInterceptor.java:852)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:821)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
	at com.hazelcast.util.JVMUtil.isHotSpotCompressedOopsOrNull(JVMUtil.java:69)
	at com.hazelcast.util.JVMUtil.isCompressedOops(JVMUtil.java:46)
	at com.hazelcast.util.JVMUtil.<clinit>(JVMUtil.java:39)
	at com.hazelcast.internal.serialization.impl.HeapData.getHeapCost(HeapData.java:96)
	at com.hazelcast.map.impl.BinaryMapSizeEstimator.calculateSize(BinaryMapSizeEstimator.java:54)
	at com.hazelcast.map.impl.recordstore.StorageImpl.calculateHeapCost(StorageImpl.java:144)
	at com.hazelcast.map.impl.recordstore.StorageImpl.put(StorageImpl.java:75)
	at com.hazelcast.map.impl.recordstore.StorageImpl.put(StorageImpl.java:41)
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.putInternal(DefaultRecordStore.java:735)
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.put(DefaultRecordStore.java:718)
	at com.hazelcast.map.impl.operation.PutOperation.run(PutOperation.java:34)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:181)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:122)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:102)
Caused by: java.lang.IllegalArgumentException: VM option "UseCompressedOops" does not exist
	at sun.management.HotSpotDiagnostic.getVMOption(HotSpotDiagnostic.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:275)
	at com.sun.jmx.mbeanserver.ConvertingMethod.invokeWithOpenReturn(ConvertingMethod.java:193)
	at com.sun.jmx.mbeanserver.ConvertingMethod.invokeWithOpenReturn(ConvertingMethod.java:175)
	at com.sun.jmx.mbeanserver.MXBeanIntrospector.invokeM2(MXBeanIntrospector.java:117)
	at com.sun.jmx.mbeanserver.MXBeanIntrospector.invokeM2(MXBeanIntrospector.java:54)
	at com.sun.jmx.mbeanserver.MBeanIntrospector.invokeM(MBeanIntrospector.java:237)
	at com.sun.jmx.mbeanserver.PerInterface.invoke(PerInterface.java:138)
	at com.sun.jmx.mbeanserver.MBeanSupport.invoke(MBeanSupport.java:252)
	at javax.management.StandardMBean.invoke(StandardMBean.java:405)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
	... 15 more

Sep 06, 2016 9:46:27 AM com.hazelcast.util.JVMUtil
WARNUNG: obj1
java.lang.NoSuchFieldException: obj1
	at java.lang.Class.getField(Class.java:1703)
	at com.hazelcast.util.JVMUtil.isCompressedOopsOrNull(JVMUtil.java:93)
	at com.hazelcast.util.JVMUtil.isCompressedOops(JVMUtil.java:52)
	at com.hazelcast.util.JVMUtil.<clinit>(JVMUtil.java:39)
	at com.hazelcast.internal.serialization.impl.HeapData.getHeapCost(HeapData.java:96)
	at com.hazelcast.map.impl.BinaryMapSizeEstimator.calculateSize(BinaryMapSizeEstimator.java:54)
	at com.hazelcast.map.impl.recordstore.StorageImpl.calculateHeapCost(StorageImpl.java:144)
	at com.hazelcast.map.impl.recordstore.StorageImpl.put(StorageImpl.java:75)
	at com.hazelcast.map.impl.recordstore.StorageImpl.put(StorageImpl.java:41)
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.putInternal(DefaultRecordStore.java:735)
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.put(DefaultRecordStore.java:718)
	at com.hazelcast.map.impl.operation.PutOperation.run(PutOperation.java:34)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:181)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:122)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:102)
```

Best regards from Switzerland,
Peti

**Comment by vbekiaris** [comment]
Thanks Peti for the additional information, it is much appreciated.
