### ISSUE TITLE
PartitionServiceSafetyCheckTest.clusterShouldBeSafe_whenBackupsBlocked_withForceToBeSafe

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#8839]
```
java.lang.AssertionError: null
    at org.junit.Assert.fail(Assert.java:86)
    at org.junit.Assert.assertTrue(Assert.java:41)
    at org.junit.Assert.assertTrue(Assert.java:52)
    at com.hazelcast.internal.partition.PartitionServiceSafetyCheckTest.clusterShouldBeSafe_whenBackupsBlocked_withForceToBeSafe(PartitionServiceSafetyCheckTest.java:176)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.8/com.hazelcast$hazelcast/335/testReport/junit/com.hazelcast.internal.partition/PartitionServiceSafetyCheckTest/clusterShouldBeSafe_whenBackupsBlocked_withForceToBeSafe/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.internal.partition.PartitionServiceSafetyCheckTest.clusterShouldBeSafe_whenBackupsBlocked_withForceToBeSafe(PartitionServiceSafetyCheckTest.java:176)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK1.8/com.hazelcast$hazelcast/359/testReport/junit/com.hazelcast.internal.partition/PartitionServiceSafetyCheckTest/clusterShouldBeSafe_whenBackupsBlocked_withForceToBeSafe/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.internal.partition.PartitionServiceSafetyCheckTest.clusterShouldBeSafe_whenBackupsBlocked_withForceToBeSafe(PartitionServiceSafetyCheckTest.java:176)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK1.8/com.hazelcast$hazelcast/366/testReport/junit/com.hazelcast.internal.partition/PartitionServiceSafetyCheckTest/clusterShouldBeSafe_whenBackupsBlocked_withForceToBeSafe/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.internal.partition.PartitionServiceSafetyCheckTest.clusterShouldBeSafe_whenBackupsBlocked_withForceToBeSafe(PartitionServiceSafetyCheckTest.java:176)
```
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.8/com.hazelcast$hazelcast/371/testReport/junit/com.hazelcast.internal.partition/PartitionServiceSafetyCheckTest/clusterShouldBeSafe_whenBackupsBlocked_withForceToBeSafe/

**Comment by mdogan** [comment]
Not failing since [Oct 10](https://github.com/hazelcast/hazelcast/issues/8839#issuecomment-252553504). Please re-open if fails again.
