### ISSUE TITLE
map Txn during cluster shutdown

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#8858]
HZ 3.8-SNAPSHOT 

Jenkins nightly build
https://hazelcast-l337.ci.cloudbees.com/view/shutdown/job/shutdown-map-txn-1phase/

Is regularly failing Validation,

e.g fail msgs 

```
HzMember1HZ validate hz.txn.map.validate.TxnAssert threadId=0 global.AssertionException: atomic[txnMap1phase16=2133] != map[txnMap1phase.get(16)=2134] 
```

here we can see that txnMap1phase0  to txnMap1phase15  was ok

```
HzMember1HZ validate hz.txn.map.validate.TxnAssert threadId=0 global.AssertionException: atomic[txnMap1phase53 1992] != map[txnMap1phase.get(53) 1993] 
```

hear we can see that txnMap1phase0  to txnMap1phase52  was ok

The configuration for this test can be found 
https://github.com/Danny-Hazelcast/hzCmd-bench/tree/beta/lab/hz/shutdown/map-txn-1phase

The test code running is 
https://github.com/Danny-Hazelcast/hzCmd-bench/tree/beta/src/main/java/hz/txn/map/validate

I note that this function https://github.com/Danny-Hazelcast/hzCmd-bench/blob/beta/lab/hz/shutdown/map-txn-1phase/txn
we mush ignore some exception thrown during the run 

```
txn1@ignore=com.hazelcast.core.HazelcastInstanceNotActiveException:com.hazelcast.spi.exception.TargetDisconnectedException:java.lang.IllegalStateException
```

however all other test under the cluster member shutdown scenario do not need to catch such exceptions to complete https://github.com/Danny-Hazelcast/hzCmd-bench/tree/beta/lab/hz/shutdown

**Comment by jerrinot** [comment]
Thanks! I assume phase = iteration?

**Comment by Danny-Hazelcast** [comment]
1 phase txn

**Comment by Danny-Hazelcast** [comment]
when looking at the output msg

```
HzMember1HZ validate hz.txn.map.validate.TxnAssert threadId=0 global.AssertionException: atomic[txnMap1phase16=2133] != map[txnMap1phase.get(16)=2134] 
```

atomic[txnMap1phase16=2133]
txnMap1phase16 is the name of an atomic long which contains the value 2133


map[txnMap1phase.get(16)=2134
txnMap1phase is the name of a transnational map which contains the value 2134 at the key 16


we can check the code hear https://github.com/Danny-Hazelcast/hzCmd-bench/blob/beta/src/main/java/hz/txn/map/validate/TxnAssert.java#L54

**Comment by Danny-Hazelcast** [comment]
the body of the test is 
https://github.com/Danny-Hazelcast/hzCmd-bench/blob/beta/src/main/java/hz/txn/map/validate/GetForUpdateSet.java#L42

each thread running this test, get a transactional map, increments the value of a batch of keys, and if the txn is committed with out a TransactionException  then  increments the its local memory of its increments.

at the end each thread,  knows how much it incremented each key.
then each thread add its local increments, to an IAtomicLong for each key    

we then check each IAtomicLong  with names post fixed with key idx 0..N
should be equal to the value in the transactional map at the same key

**Comment by Danny-Hazelcast** [comment]
https://hazelcast-l337.ci.cloudbees.com/view/shutdown/job/shutdown-map-txn-2phase/1/  
shows that a 2 phase txn also has same issue
settings 
TransactionOptions{timeoutMillis=120000, durability=1, txType=TWO_PHASE}

**Comment by Danny-Hazelcast** [comment]
searching the logs of all runs for Exception

http://54.87.52.100/~jenkins/workspace/shutdown-map-txn-1phase/3.8-SNAPSHOT//2016_09_07-20_56_43/output/HZ/HzMember3HZ/out.txt
```
WARNING: [10.0.0.23]:5701 [HZ] [3.8-SNAPSHOT] Op: com.hazelcast.map.impl.tx.TxnLockAndGetOperation{serviceName='hz:impl:mapService', identityHash=1947529611, partitionId=146, replicaIndex=0, callId=155, invocationTime=1473271645964 (2016-09-07 18:07:25.964), waitTimeout=120000, callTimeout=60000, name=txnMap1phase, timeout=120000, thread=30}, com.hazelcast.spi.exception.RetryableHazelcastException: Member [10.0.0.23]:5701 is currently shutting down! Operation: com.hazelcast.spi.impl.waitnotifyservice.impl.WaitingOperation{serviceName='hz:impl:mapService', identityHash=1724690424, partitionId=146, replicaIndex=0, callId=0, invocationTime=-1 (1969-12-31 23:59:59.999), waitTimeout=-1, callTimeout=9223372036854775807, op=com.hazelcast.map.impl.tx.TxnLockAndGetOperation{serviceName='hz:impl:mapService', identityHash=1947529611, partitionId=146, replicaIndex=0, callId=155, invocationTime=1473271645964 (2016-09-07 18:07:25.964), waitTimeout=120000, callTimeout=60000, name=txnMap1phase, timeout=120000, thread=30}, expirationTime=1473271765966, valid=true}
```

http://54.87.52.100/~jenkins/workspace/shutdown-map-txn-1phase/3.8-SNAPSHOT/2016_09_08-09_37_24/output/HZ/HzMember4HZ/out.txt
```
WARNING: [10.0.0.161]:5701 [HZ] [3.8-SNAPSHOT] Op: com.hazelcast.map.impl.tx.TxnLockAndGetOperation{serviceName='hz:impl:mapService', identityHash=889890236, partitionId=129, replicaIndex=0, callId=49020, invocationTime=1473317428345 (2016-09-08 06:50:28.345), waitTimeout=120000, callTimeout=60000, name=txnMap1phase, timeout=120000, thread=33}, com.hazelcast.spi.exception.RetryableHazelcastException: Member [10.0.0.161]:5701 is currently shutting down! Operation: com.hazelcast.spi.impl.waitnotifyservice.impl.WaitingOperation{serviceName='hz:impl:mapService', identityHash=1278551274, partitionId=129, replicaIndex=0, callId=0, invocationTime=-1 (1969-12-31 23:59:59.999), waitTimeout=-1, callTimeout=9223372036854775807, op=com.hazelcast.map.impl.tx.TxnLockAndGetOperation{serviceName='hz:impl:mapService', identityHash=889890236, partitionId=129, replicaIndex=0, callId=49020, invocationTime=1473317428345 (2016-09-08 06:50:28.345), waitTimeout=120000, callTimeout=60000, name=txnMap1phase, timeout=120000, thread=33}, expirationTime=1473317548367, valid=true}
Sep 08, 2016 6:51:28 AM com.hazelcast.spi.impl.waitnotifyservice.impl.WaitingOperation
WARNING: [10.0.0.161]:5701 [HZ] [3.8-SNAPSHOT] Op: com.hazelcast.map.impl.tx.TxnLockAndGetOperation{serviceName='hz:impl:mapService', identityHash=716486893, partitionId=129, replicaIndex=0, callId=49122, invocationTime=1473317428363 (2016-09-08 06:50:28.363), waitTimeout=120000, callTimeout=60000, name=txnMap1phase, timeout=120000, thread=31}, com.hazelcast.spi.exception.RetryableHazelcastException: Member [10.0.0.161]:5701 is currently shutting down! Operation: com.hazelcast.spi.impl.waitnotifyservice.impl.WaitingOperation{serviceName='hz:impl:mapService', identityHash=1309078744, partitionId=129, replicaIndex=0, callId=0, invocationTime=-1 (1969-12-31 23:59:59.999), waitTimeout=-1, callTimeout=9223372036854775807, op=com.hazelcast.map.impl.tx.TxnLockAndGetOperation{serviceName='hz:impl:mapService', identityHash=716486893, partitionId=129, replicaIndex=0, callId=49122, invocationTime=1473317428363 (2016-09-08 06:50:28.363), waitTimeout=120000, callTimeout=60000, name=txnMap1phase, timeout=120000, thread=31}, expirationTime=1473317548385, valid=true}
```

http://54.87.52.100/~jenkins/workspace/shutdown-map-txn-1phase/3.8-SNAPSHOT/2016_09_08-11_56_46/output/HZ/HzMember2HZ/out.txt
```
Reason: TcpIpConnectionManager is stopping
Sep 08, 2016 9:19:04 AM com.hazelcast.instance.Node
INFO: [10.0.0.38]:5701 [HZ] [3.8-SNAPSHOT] Shutting down node engine...
Sep 08, 2016 9:19:04 AM com.hazelcast.nio.tcp.SocketAcceptorThread
WARNING: [10.0.0.38]:5701 [HZ] [3.8-SNAPSHOT] java.lang.IllegalStateException: connection manager is not live!
java.lang.IllegalStateException: connection manager is not live!
	at com.hazelcast.nio.tcp.TcpIpConnectionManager.newConnection(TcpIpConnectionManager.java:353)
	at com.hazelcast.nio.tcp.SocketAcceptorThread.configureAndAssignSocket(SocketAcceptorThread.java:242)
	at com.hazelcast.nio.tcp.SocketAcceptorThread.access$000(SocketAcceptorThread.java:40)
	at com.hazelcast.nio.tcp.SocketAcceptorThread$1.run(SocketAcceptorThread.java:230)
	at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)

Sep 08, 2016 9:19:04 AM com.hazelcast.instance.NodeExtension
INFO: [10.0.0.38]:5701 [HZ] [3.8-SNAPSHOT] Destroying node NodeExtension.
Sep 08, 2016 9:19:04 AM com.hazelcast.instance.Node
INFO: [10.0.0.38]:5701 [HZ] [3.8-SNAPSHOT] Hazelcast Shutdown is completed in 571 ms.
Sep 08, 2016 9:19:04 AM com.hazelcast.core.LifecycleService
INFO: [10.0.0.38]:5701 [HZ] [3.8-SNAPSHOT] [10.0.0.38]:5701 is SHUTDOWN
```

**Comment by Danny-Hazelcast** [comment]
over view of Client exceptons

```
com.hazelcast.core.HazelcastInstanceNotActiveException: State: PASSIVE Operation: class com.hazelcast.map.impl.tx.TxnLockAndGetOp
eration
```

```
./2016_09_07-20_56_43/output/HZ/HzClient2HZ/out.txt:com.hazelcast.transaction.TransactionException: Transaction couldn't obtain lock for the key: HeapData{type=-7, hashCode=12226486
92, partitionHash=1222648692, totalSize=12, dataSize=4, heapCost=32}
./2016_09_07-20_56_43/output/HZ/HzClient2HZ/out.txt:com.hazelcast.transaction.TransactionException: Transaction couldn't obtain lock for the key: HeapData{type=-7, hashCode=17275059
03, partitionHash=1727505903, totalSize=12, dataSize=4, heapCost=32}
./2016_09_07-20_56_43/output/HZ/HzClient2HZ/out.txt:com.hazelcast.transaction.TransactionException: Transaction is timed-out!
./2016_09_07-20_56_43/output/HZ/HzClient3HZ/out.txt:Caused by: com.hazelcast.core.HazelcastInstanceNotActiveException: Hazelcast instance is not ready yet!

./2016_09_07-20_56_43/output/HZ/HzClient3HZ/out.txt:com.hazelcast.transaction.TransactionException: Transaction is timed-out!
./2016_09_07-20_56_43/output/HZ/HzClient3HZ/out.txt:java.util.concurrent.ExecutionException: com.hazelcast.core.HazelcastInstanceNotActiveException: Hazelcast instance is not ready
yet!
```

**Comment by Danny-Hazelcast** [comment]
linked to https://hazelcast.atlassian.net/wiki/display/PM/%5BSB%5D+Rolling+Member+Upgrades+for+Minor+Releases

as this issue seams a prerequisite for a rolling upgrade PRD

**Comment by mmedenjak** [comment]
Moving to backlog as it should be included in a transaction overhaul

**Comment by mmedenjak** [comment]
Go:
```
hz run txn &
hz-cluster-shutdown
hz stop
wait
hz run validate
```

Txn:
```
txn1@class=hzcmd.txn.map.validate.GetForUpdateSet
txn1@driver=Client
txn1@threads=12
txn1@keyDomain=400
txn1@phase=1
txn1@batchSize=1
txn1@name=txnMap1phase
txn1@ignore=com.hazelcast.spi.exception.TargetDisconnectedException:com.hazelcast.spi.exception.TargetNotMemberException:com.hazelcast.core.HazelcastInstanceNotActiveException:java.lang.IllegalStateException
```

Validate:
```
validate@class=hzcmd.txn.map.validate.TxnAssert
validate@driver=Member1
validate@keyDomain=400
validate@name=txnMap1phase
```

hzcmd.txn.map.validate.GetForUpdateSet:
```
public class GetForUpdateSet extends TxnBench {

    private int[] incCounts;
    private int[] keyBatch;

    public void init() throws Exception{
        super.init();

        incCounts = new int[keyDomain];
        keyBatch = new int[batchSize];

        IMap map = hzInstance.getMap(name);
        for(int i=0; i<keyDomain; i++) {
            map.put(getKey(i), 0);
        }
    }

    public void timeStep() throws Exception {

        TransactionContext context = hzInstance.newTransactionContext(txnOps);
        context.beginTransaction();

        TransactionalMap<Object, Integer> map = context.getMap(name);
        try {
            for(int i=0; i<batchSize; i++){
                int k = random.nextInt(keyDomain);
                Object obj_key = getKey(k);
                int val = map.getForUpdate(obj_key);
                map.set(obj_key, ++val);
                keyBatch[i]=k;
            }
            context.commitTransaction();
            for(int i=0; i<batchSize; i++){
                incCounts[keyBatch[i]]++;
            }
        } catch (TransactionException commitException) {
            commitException.printStackTrace();
            try {
                context.rollbackTransaction();
            }catch (TransactionException rollBackException){
                throw rollBackException;
            }
        }
    }

    public void postPhase() {
        for (int i=0; i<incCounts.length; i++) {
            IAtomicLong keyInc = hzInstance.getAtomicLong(name+i);
            keyInc.addAndGet(incCounts[i]);
        }
    }
```

TxnAssert:
```
public class TxnAssert extends TxnBench {

    private IMap<Integer, Integer> map;

    public void init() throws Exception{
        super.init();
        map = hzInstance.getMap(name);
    }

    public void timeStep() throws AssertionException {

        for(int i=0; i<keyDomain; i++) {
            System.out.println(infoFor(i));
        }

        for(int i=0; i<keyDomain; i++) {
            IAtomicLong expectedIncs = getAtomic(i);
            if( expectedIncs.get() != map.get(getKey(i)) ){
                throw new AssertionException(infoFor(i));
            }
        }
        setRunning(false);
    }

    public IAtomicLong getAtomic(int i){
        return hzInstance.getAtomicLong(name+i);
    }

    public String infoFor(int i){
        IAtomicLong expectedIncs = getAtomic(i);
        return "atomic["+expectedIncs.getName()+"="+expectedIncs.get()+"]"+" != "+"map["+map.getName()+".get("+i+")="+map.get(getKey(i))+"]";
    }
}
```
