### ISSUE TITLE
com.hazelcast.core.HazelcastException: java.io.IOException: Not able to setup owner connection!

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#8859]
this build https://hazelcast-l337.ci.cloudbees.com/view/hot-restart/job/aws-hot-shutdown/  Failed on 3 runs,

```
HzClient15HZ mapBak1Set hz.map.Set threadId=1 com.hazelcast.core.HazelcastException: java.io.IOException: Not able to setup owner connection!
```

https://hazelcast-l337.ci.cloudbees.com/view/hot-restart/job/aws-hot-shutdown/46/consoleFull
http://54.87.52.100/~jenkins/workspace/aws-hot-shutdown/3.8-SNAPSHOT/2016_09_06-01_35_03/output/HZ/HzClient15HZ/exception.txt

https://hazelcast-l337.ci.cloudbees.com/view/hot-restart/job/aws-hot-shutdown/47/consoleFull
http://54.87.52.100/~jenkins/workspace/aws-hot-shutdown/3.8-SNAPSHOT/2016_09_06-01_35_03/

https://hazelcast-l337.ci.cloudbees.com/view/hot-restart/job/aws-hot-shutdown/48/consoleFull
http://54.87.52.100/~jenkins/workspace/aws-hot-shutdown/3.8-SNAPSHOT/2016_09_07-01_35_04/

```
com.hazelcast.core.HazelcastException: java.io.IOException: Not able to setup owner connection!
    at com.hazelcast.util.ExceptionUtil.peel(ExceptionUtil.java:73)
    at com.hazelcast.util.ExceptionUtil.peel(ExceptionUtil.java:63)
    at com.hazelcast.util.ExceptionUtil.peel(ExceptionUtil.java:52)
    at com.hazelcast.util.ExceptionUtil.rethrow(ExceptionUtil.java:83)
    at com.hazelcast.client.spi.ClientProxy.invokeOnPartition(ClientProxy.java:155)
    at com.hazelcast.client.spi.ClientProxy.invoke(ClientProxy.java:147)
    at com.hazelcast.client.proxy.ClientMapProxy.setInternal(ClientMapProxy.java:557)
    at com.hazelcast.client.proxy.ClientMapProxy.set(ClientMapProxy.java:550)
    at com.hazelcast.client.proxy.ClientMapProxy.set(ClientMapProxy.java:1364)
    at hz.map.Set.timeStep(Set.java:10)
    at remote.bench.marker.MetricsMarker.flatOut(MetricsMarker.java:63)
    at remote.bench.marker.MetricsMarker.timeBenchFlatOut(MetricsMarker.java:47)
    at remote.bench.marker.MetricsMarker.bench(MetricsMarker.java:38)
    at remote.bench.BenchThread.call(BenchThread.java:38)
    at remote.bench.BenchThread.call(BenchThread.java:12)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Not able to setup owner connection!
    at com.hazelcast.client.spi.impl.ClientSmartInvocationServiceImpl.ensureOwnerConnectionAvailable(ClientSmartInvocationServiceImpl.java:93)
    at com.hazelcast.client.spi.impl.ClientSmartInvocationServiceImpl.getConnection(ClientSmartInvocationServiceImpl.java:74)
    at com.hazelcast.client.spi.impl.ClientSmartInvocationServiceImpl.invokeOnPartitionOwner(ClientSmartInvocationServiceImpl.java:46)
    at com.hazelcast.client.spi.impl.ClientInvocation.invokeOnSelection(ClientInvocation.java:142)
    at com.hazelcast.client.spi.impl.ClientInvocation.invoke(ClientInvocation.java:122)
    at com.hazelcast.client.spi.impl.ClientInvocation.run(ClientInvocation.java:153)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
    at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
    at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)
    at ------ submitted from ------.(Unknown Source)
    at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrow(ClientInvocationFuture.java:74)
    at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrow(ClientInvocationFuture.java:30)
    at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:158)
    at com.hazelcast.client.spi.ClientProxy.invokeOnPartition(ClientProxy.java:153)
    ... 16 more
```

is com.hazelcast.core.HazelcastException to generic for such an exception

**Comment by sancar** [comment]
Possibly fixed via https://github.com/hazelcast/hazelcast/pull/9585
