### ISSUE TITLE
ConnectedClientOperationTest.testNumberOfConnectedClients

### ISSUE THREAD

**Issue by Donnerbart** [hazelcast/hazelcast#8880]
**com.hazelcast.client.ConnectedClientOperationTest.testNumberOfConnectedClients**

```
java.lang.AssertionError: the size of the collection is not correct: found-content:[Member [127.0.0.1]:5702 - 4471b56a-195e-4443-b4bf-a25c9375051a this] expected:<2> but was:<1>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:834)
    at org.junit.Assert.assertEquals(Assert.java:645)
    at com.hazelcast.test.HazelcastTestSupport$6.run(HazelcastTestSupport.java:709)
    at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:905)
    at com.hazelcast.test.HazelcastTestSupport.assertSizeEventually(HazelcastTestSupport.java:706)
    at com.hazelcast.test.HazelcastTestSupport.assertSizeEventually(HazelcastTestSupport.java:702)
    at com.hazelcast.client.ConnectedClientOperationTest.testNumberOfConnectedClients(ConnectedClientOperationTest.java:45)
```

https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/4444/testReport/junit/com.hazelcast.client/ConnectedClientOperationTest/testNumberOfConnectedClients/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: the size of the collection is not correct: found-content:[Member [127.0.0.1]:5702 - bf5c0885-2e3e-4526-8b9a-e207ab13e479 this] expected:<2> but was:<1>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.test.HazelcastTestSupport$6.run(HazelcastTestSupport.java:709)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:905)
	at com.hazelcast.test.HazelcastTestSupport.assertSizeEventually(HazelcastTestSupport.java:706)
	at com.hazelcast.test.HazelcastTestSupport.assertSizeEventually(HazelcastTestSupport.java:702)
	at com.hazelcast.client.ConnectedClientOperationTest.testNumberOfConnectedClients(ConnectedClientOperationTest.java:45)
```

https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/4781/testReport/junit/com.hazelcast.client/ConnectedClientOperationTest/testNumberOfConnectedClients/
