### ISSUE TITLE
NearCacheTest.testNearCacheMaxIdleRecordsExpired

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#8896]
**testNearCacheMaxIdleRecordsExpired[batchInvalidationEnabled:true]**

```
java.lang.AssertionError: we expected to have all map entries in the Near Cache (NearCacheStatsImpl{ownedEntryCount=3498, ownedEntryMemoryCost=349800, creationTime=1474161861246, hits=0, misses=50000, ratio=0.0%, evictions=0, expirations=48147}), but was 51514 expected:<50000> but was:<51514>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:834)
    at org.junit.Assert.assertEquals(Assert.java:645)
    at com.hazelcast.map.nearcache.NearCacheTestSupport.testNearCacheExpiration(NearCacheTestSupport.java:97)
    at com.hazelcast.map.nearcache.NearCacheTest.testNearCacheMaxIdleRecordsExpired(NearCacheTest.java:888)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast$hazelcast/1037/testReport/junit/com.hazelcast.map.nearcache/NearCacheTest/testNearCacheMaxIdleRecordsExpired_batchInvalidationEnabled_true_/

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK1.6/com.hazelcast$hazelcast/1040/testReport/junit/com.hazelcast.map.nearcache/NearCacheTest/testNearCacheMaxIdleRecordsExpired_batchInvalidationEnabled_false_/

**Comment by jerrinot** [comment]
this has not failed since September. closing.
