### ISSUE TITLE
ClientTxnMapTest.testPutWithTTL

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#8898]
```
java.lang.AssertionError: expected:<Value> but was:<null>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:834)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:144)
    at com.hazelcast.client.txn.ClientTxnMapTest.testPutWithTTL(ClientTxnMapTest.java:223)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK1.6/com.hazelcast$hazelcast-client/1040/testReport/junit/com.hazelcast.client.txn/ClientTxnMapTest/testPutWithTTL/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: expected:<Value> but was:<null>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.client.txn.ClientTxnMapTest.testPutWithTTL(ClientTxnMapTest.java:223)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK1.8/com.hazelcast$hazelcast-client/397/testReport/junit/com.hazelcast.client.txn/ClientTxnMapTest/testPutWithTTL/
