### ISSUE TITLE
ManagementCenterServiceIntegrationTest.testTimedMemberStateNotNull

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#8900]
```
com.eclipsesource.json.ParseException: Expected value at 1:0
    at com.eclipsesource.json.JsonParser.error(JsonParser.java:382)
    at com.eclipsesource.json.JsonParser.expected(JsonParser.java:375)
    at com.eclipsesource.json.JsonParser.readValue(JsonParser.java:108)
    at com.eclipsesource.json.JsonParser.parse(JsonParser.java:73)
    at com.eclipsesource.json.JsonValue.readFrom(JsonValue.java:116)
    at com.eclipsesource.json.JsonObject.readFrom(JsonObject.java:149)
    at com.hazelcast.internal.management.ManagementCenterServiceIntegrationTest$1.run(ManagementCenterServiceIntegrationTest.java:76)
    at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:905)
    at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:919)
    at com.hazelcast.internal.management.ManagementCenterServiceIntegrationTest.testTimedMemberStateNotNull(ManagementCenterServiceIntegrationTest.java:66)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-nightly/com.hazelcast$hazelcast/982/testReport/junit/com.hazelcast.internal.management/ManagementCenterServiceIntegrationTest/testTimedMemberStateNotNull/

**Comment by mesutcelik** [comment]
@hasancelik , 
Can you please reopen this if you see it again? It looks like logs are already gone and the issue was created 3 months ago.

**Comment by Donnerbart** [comment]
I have a different failure on this test in the current master:
```
org.junit.ComparisonFailure: 
Expected :dev
Actual   :Session Integration (AWS discovery)
```
https://gist.github.com/Donnerbart/91110794585b6991292e6b3d42666891

**Comment by hasancelik** [comment]
fixed via https://github.com/hazelcast/hazelcast/pull/9571

**Comment by Holmistr** [comment]
*master*

Reopening as it failed in Sonar build: https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-sonar/68/testReport/junit/com.hazelcast.internal.management/ManagementCenterServiceIntegrationTest/testTimedMemberStateNotNull/

Stacktrace:
```
com.eclipsesource.json.ParseException: Expected value at 1:0
	at com.eclipsesource.json.JsonParser.error(JsonParser.java:379)
	at com.eclipsesource.json.JsonParser.expected(JsonParser.java:372)
	at com.eclipsesource.json.JsonParser.readValue(JsonParser.java:108)
	at com.eclipsesource.json.JsonParser.parse(JsonParser.java:73)
	at com.eclipsesource.json.JsonValue.readFrom(JsonValue.java:126)
	at com.eclipsesource.json.JsonObject.readFrom(JsonObject.java:151)
	at com.hazelcast.internal.management.ManagementCenterServiceIntegrationTest$1.run(ManagementCenterServiceIntegrationTest.java:87)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1244)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1261)
	at com.hazelcast.internal.management.ManagementCenterServiceIntegrationTest.testTimedMemberStateNotNull(ManagementCenterServiceIntegrationTest.java:77)
```

**Comment by Holmistr** [comment]
*master* (commit 12d23f34c4152fac4747eb06dac179517f00e4a5)

Reopening as it failed again on Sonar build: https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-sonar/116/testReport/junit/com.hazelcast.internal.management/ManagementCenterServiceIntegrationTest/testTimedMemberStateNotNull/

Stacktrace:
```
com.eclipsesource.json.ParseException: Expected value at 1:0
	at com.eclipsesource.json.JsonParser.error(JsonParser.java:379)
	at com.eclipsesource.json.JsonParser.expected(JsonParser.java:372)
	at com.eclipsesource.json.JsonParser.readValue(JsonParser.java:108)
	at com.eclipsesource.json.JsonParser.parse(JsonParser.java:73)
	at com.eclipsesource.json.Json.parse(Json.java:295)
	at com.hazelcast.internal.management.ManagementCenterServiceIntegrationTest$1.run(ManagementCenterServiceIntegrationTest.java:89)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1248)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1274)
	at com.hazelcast.internal.management.ManagementCenterServiceIntegrationTest.testTimedMemberStateNotNull(ManagementCenterServiceIntegrationTest.java:78)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

Standard output:
```
Hiccups measured while running test 'testTimedMemberStateNotNull(com.hazelcast.internal.management.ManagementCenterServiceIntegrationTest):'
22:04:50, accumulated pauses: 88 ms, max pause: 13 ms, pauses over 1000 ms: 0
22:04:55, accumulated pauses: 305 ms, max pause: 232 ms, pauses over 1000 ms: 0
```
