### ISSUE TITLE
[ZING-JVM] LazyEntryViewFromRecordTest.test_getCost

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#8909]
```
java.lang.AssertionError: expected:<109> but was:<121>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.map.impl.recordstore.LazyEntryViewFromRecordTest.test_getCost(LazyEntryViewFromRecordTest.java:83)
```

https://hazelcast-l337.ci.cloudbees.com/view/Zing/job/Hazelcast-3.x-ZingJDK6/34/testReport/junit/com.hazelcast.map.impl.recordstore/LazyEntryViewFromRecordTest/test_getCost/

https://hazelcast-l337.ci.cloudbees.com/view/Zing/job/Hazelcast-3.x-ZingJDK7/56/testReport/junit/com.hazelcast.map.impl.recordstore/LazyEntryViewFromRecordTest/test_getCost/

**Comment by vbekiaris** [comment]
Fixed by #8927
