### ISSUE TITLE
ExecuteScriptRequestTest.testExecuteScriptRequest_whenTargetAllMembers & testExecuteScriptRequest_whenTargetAllMembers_withTarget

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#8911]
**testExecuteScriptRequest_whenTargetAllMembers**
```
expected:<[error
error]
> but was:<[java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Could not find ScriptEngine named 'JavaScript'.
 at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrow(InvocationFuture.java:85)
 at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:150)
 at com.hazelcast.internal.management.ManagementCenterService.callOnAddress(ManagementCenterService.java:247)
 at com.hazelcast.internal.management.ManagementCenterService.callOnMember(ManagementCenterService.java:259)
 at com.hazelcast.internal.management.request.ExecuteScriptRequest.writeResponse(ExecuteScriptRequest.java:83)
 at com.hazelcast.internal.management.ExecuteScriptRequestTest.testExecuteScriptRequest_whenTargetAllMembers(ExecuteScriptRequestTest.java:64)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:622)
 at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
 at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
 at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
 at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
 at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:88)
 at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:82)
 at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
 at java.util.concurrent.FutureTask.run(FutureTask.java:166)
 at java.lang.Thread.run(Thread.java:701)
Caused by: java.lang.IllegalArgumentException: Could not find ScriptEngine named 'JavaScript'.
 at com.hazelcast.internal.management.operation.ScriptExecutorOperation.run(ScriptExecutorOperation.java:57)
 at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:181)
 at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:375)
 at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:402)
 at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:283)
 at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:268)
 at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:232)
 at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:207)
 at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.invokeOnTarget(OperationServiceImpl.java:310)
 at com.hazelcast.internal.management.ManagementCenterService.callOnAddress(ManagementCenterService.java:245)
 at com.hazelcast.internal.management.ManagementCenterService.callOnMember(ManagementCenterService.java:259)
 at com.hazelcast.internal.management.request.ExecuteScriptRequest.writeResponse(ExecuteScriptRequest.java:83)
 at com.hazelcast.internal.management.ExecuteScriptRequestTest.testExecuteScriptRequest_whenTargetAllMembers(ExecuteScriptRequestTest.java:64)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:622)
 at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
 at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
 at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
 at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
 at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:88)
 at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:82)
 at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
 at java.util.concurrent.FutureTask.run(FutureTask.java:166)
 at java.lang.Thread.run(Thread.java:701)
 at ------ submitted from ------.(Unknown Source)
 at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:111)
 at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrow(InvocationFuture.java:74)
 ... 18 more

java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Could not find ScriptEngine named 'JavaScript'.
 at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrow(InvocationFuture.java:85)
 at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:158)
 at com.hazelcast.internal.management.ManagementCenterService.callOnAddress(ManagementCenterService.java:247)
 at com.hazelcast.internal.management.ManagementCenterService.callOnMember(ManagementCenterService.java:259)
 at com.hazelcast.internal.management.request.ExecuteScriptRequest.writeResponse(ExecuteScriptRequest.java:83)
 at com.hazelcast.internal.management.ExecuteScriptRequestTest.testExecuteScriptRequest_whenTargetAllMembers(ExecuteScriptRequestTest.java:64)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:622)
 at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
 at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
 at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
 at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
 at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:88)
 at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:82)
 at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
 at java.util.concurrent.FutureTask.run(FutureTask.java:166)
 at java.lang.Thread.run(Thread.java:701)
Caused by: java.lang.IllegalArgumentException: Could not find ScriptEngine named 'JavaScript'.
 at com.hazelcast.internal.management.operation.ScriptExecutorOperation.run(ScriptExecutorOperation.java:57)
 at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:181)
 at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:396)
 at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:117)
 at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:102)
 at ------ submitted from ------.(Unknown Source)
 at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:111)
 at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrow(InvocationFuture.java:74)
 ... 18 more
]
>
```

**testExecuteScriptRequest_whenTargetAllMembers_withTarget**
```
expected:<[error]> but was:<[java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Could not find ScriptEngine named 'JavaScript'.
 at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrow(InvocationFuture.java:85)
 at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:150)
 at com.hazelcast.internal.management.ManagementCenterService.callOnAddress(ManagementCenterService.java:247)
 at com.hazelcast.internal.management.request.ExecuteScriptRequest.writeResponse(ExecuteScriptRequest.java:91)
 at com.hazelcast.internal.management.ExecuteScriptRequestTest.testExecuteScriptRequest_whenTargetAllMembers_withTarget(ExecuteScriptRequestTest.java:78)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:622)
 at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
 at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
 at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
 at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
 at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:88)
 at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:82)
 at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
 at java.util.concurrent.FutureTask.run(FutureTask.java:166)
 at java.lang.Thread.run(Thread.java:701)
Caused by: java.lang.IllegalArgumentException: Could not find ScriptEngine named 'JavaScript'.
 at com.hazelcast.internal.management.operation.ScriptExecutorOperation.run(ScriptExecutorOperation.java:57)
 at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:181)
 at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:375)
 at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:402)
 at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:283)
 at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:268)
 at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:232)
 at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:207)
 at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.invokeOnTarget(OperationServiceImpl.java:310)
 at com.hazelcast.internal.management.ManagementCenterService.callOnAddress(ManagementCenterService.java:245)
 at com.hazelcast.internal.management.request.ExecuteScriptRequest.writeResponse(ExecuteScriptRequest.java:91)
 at com.hazelcast.internal.management.ExecuteScriptRequestTest.testExecuteScriptRequest_whenTargetAllMembers_withTarget(ExecuteScriptRequestTest.java:78)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:622)
 at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
 at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
 at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
 at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
 at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:88)
 at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:82)
 at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
 at java.util.concurrent.FutureTask.run(FutureTask.java:166)
 at java.lang.Thread.run(Thread.java:701)
 at ------ submitted from ------.(Unknown Source)
 at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:111)
 at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrow(InvocationFuture.java:74)
 ... 17 more]>
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-ZuluJDK6/330/
https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-ZuluJDK7/334/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-ZuluJDK7/335/
https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-ZuluJDK6/331/#showFailuresLink
