### ISSUE TITLE
com.hazelcast.core.HazelcastException: java.io.IOException: Packet not send 

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#8919]
https://hazelcast-l337.ci.cloudbees.com/view/hot-restart/job/aws-hot-shutdown/

this build is failing regularly  Hz 3.8-SNAPSHOT nightly

/disk1/jenkins/workspace/aws-hot-shutdown/3.8-SNAPSHOT/2016_09_20-01_35_04

```
[jenkins@ip-10-72-134-107 2016_09_20-01_35_04]$ more ./output/HZ/HzClient35HZ/exception.txt
com.hazelcast.core.HazelcastException: java.io.IOException: Packet not send to [10.0.0.254]:5701
        at com.hazelcast.util.ExceptionUtil.peel(ExceptionUtil.java:73)
        at com.hazelcast.util.ExceptionUtil.peel(ExceptionUtil.java:63)
        at com.hazelcast.util.ExceptionUtil.peel(ExceptionUtil.java:52)
        at com.hazelcast.util.ExceptionUtil.rethrowAllowedTypeFirst(ExceptionUtil.java:111)
        at com.hazelcast.client.cache.impl.ClientCacheProxy.remove(ClientCacheProxy.java:176)
        at hz.cache.PutRemove.timeStep(PutRemove.java:11)
        at remote.bench.marker.MetricsMarker.flatOut(MetricsMarker.java:61)
        at remote.bench.marker.MetricsMarker.timeBenchFlatOut(MetricsMarker.java:45)
        at remote.bench.marker.MetricsMarker.bench(MetricsMarker.java:36)
        at remote.bench.BenchThread.call(BenchThread.java:38)
        at remote.bench.BenchThread.call(BenchThread.java:12)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Packet not send to [10.0.0.254]:5701
        at com.hazelcast.client.spi.impl.ClientInvocationServiceSupport.send(ClientInvocationServiceSupport.java:121)
        at com.hazelcast.client.spi.impl.ClientSmartInvocationServiceImpl.invokeOnPartitionOwner(ClientSmartInvocationServiceImpl.java:47)
        at com.hazelcast.client.spi.impl.ClientInvocation.invokeOnSelection(ClientInvocation.java:142)
        at com.hazelcast.client.spi.impl.ClientInvocation.invoke(ClientInvocation.java:122)
        at com.hazelcast.client.spi.impl.ClientInvocation.run(ClientInvocation.java:153)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
        at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
        at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)
        at ------ submitted from ------.(Unknown Source)
        at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrow(ClientInvocationFuture.java:74)
        at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrow(ClientInvocationFuture.java:30)
        at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:186)
        at com.hazelcast.client.util.ClientDelegatingFuture.get(ClientDelegatingFuture.java:122)
        at com.hazelcast.client.util.ClientDelegatingFuture.get(ClientDelegatingFuture.java:108)
        at com.hazelcast.client.cache.impl.ClientCacheProxy.remove(ClientCacheProxy.java:170)
```

**Comment by jerrinot** [comment]
this should be fixed by https://github.com/hazelcast/hazelcast/pull/8934

**Comment by jerrinot** [comment]
@Danny-Hazelcast: can you please test it with the maintenance branch?

**Comment by Danny-Hazelcast** [comment]
using 3.8-SNAPSHOT

in this build https://hazelcast-l337.ci.cloudbees.com/view/hot-restart/job/aws-hot-shutdown/91/console

at  http://54.87.52.100/~jenkins/workspace/aws-hot-shutdown/3.8-SNAPSHOT/2016_10_18-12_57_38

we hit 

```
HzClient19HZ cacheBak1Put hz.cache.Put threadId=5 com.hazelcast.core.HazelcastException: java.io.IOException: Packet not send to [10.0.0.185]:5701 
```

so reproducing this issue

**Comment by pveentjer** [comment]
What does this test do? I need to be able to run it myself so I can debug and fix.

**Comment by Danny-Hazelcast** [comment]
runs on 4  * r3.xlarge boxes with 30.5G

4   members  (2G) + (2G HD POOL) each
50 clients      (500M)  each

the clients make  put and remove operations on
  1 map on heap
  1 map HD
  1 cache on heap
  1 cache HD

each struct has 1 backup.

with a random value size between 1 byes  and   1001 bytes,  in the keyDomain of 0 to 10001

all structs  have Hot restart enabled.

while the clients are making the operations. we shutdown the cluster. using 
```
hzInstance.getCluster().shutdown();
```
from only 1 member node.

then we restart the hazelcast instance member nodes inside the Member jvm's

and repeat 75 times.
with a 60 second pause between each cycle.

**Comment by Danny-Hazelcast** [comment]
could the java.io.IOException: Packet not send to [10.0.0.185]:5701 
be connected with a high number of client on each box ?
I think my my calculations there should be enough ram on each box for  

12 client and 1 member + HD pool,  +  heap map size of   10001 keys with value size of 1001

**Comment by sancar** [comment]
Possibly fixed via https://github.com/hazelcast/hazelcast/pull/9585
