### ISSUE TITLE
[cache] JCache fails to initialise when type of a key or value is not available on a remote node

### ISSUE THREAD

**Issue by smillidge** [hazelcast/hazelcast#8972]
In the scenario where you create a cache like;

``` java
        cache = cacheManager.getCache("test",String.class, CustomPOJO.class);
        if (cache == null) {
            MutableConfiguration<String, CustomPOJO> cconfig = new MutableConfiguration<>();
            cache = cacheManager.createCache("test", cconfig);
        }
```

If a cluster member is started where CustomPojo can not be loaded by the context classloader of the hz._hzInstance_1_development.generic-operation.thread-3 thread then repeated errors are thrown and the cluster member never starts.

``` java
[2016-09-23T22:16:23.394+0100] [Payara 4.1] [SEVERE] [] [com.hazelcast.spi.impl.operationexecutor.classic.ClassicOperationExecutor] [tid: _ThreadID=74 _ThreadName=hz._hzInstance_1_development.generic-operation.thread-3] [timeMillis: 1474665383394] [levelValue: 1000] [[
  [192.168.139.128]:5901 [development] [3.6.4] Failed to process packet: Packet{header=17, isResponse=false, isOperation=true, isEvent=false, partitionId=-1, conn=Connection [/192.168.139.128:54657 -> /192.168.139.128:5900], endpoint=Address[192.168.139.128]:5900, alive=true, type=MEMBER} on hz._hzInstance_1_development.generic-operation.thread-3
com.hazelcast.nio.serialization.HazelcastSerializationException: java.lang.ClassNotFoundException: fish.payara.testcases.payara1072.CustomPOJO
    at com.hazelcast.internal.serialization.impl.JavaDefaultSerializers$ClassSerializer.read(JavaDefaultSerializers.java:181)
    at com.hazelcast.internal.serialization.impl.JavaDefaultSerializers$ClassSerializer.read(JavaDefaultSerializers.java:169)
    at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:46)
    at com.hazelcast.internal.serialization.impl.AbstractSerializationService.readObject(AbstractSerializationService.java:214)
    at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readObject(ByteArrayObjectDataInput.java:600)
    at com.hazelcast.config.CacheConfig.readData(CacheConfig.java:543)
    at com.hazelcast.internal.serialization.impl.DataSerializer.read(DataSerializer.java:121)
    at com.hazelcast.internal.serialization.impl.DataSerializer.read(DataSerializer.java:47)
    at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:46)
    at com.hazelcast.internal.serialization.impl.AbstractSerializationService.readObject(AbstractSerializationService.java:214)
    at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readObject(ByteArrayObjectDataInput.java:600)
    at com.hazelcast.cache.impl.operation.PostJoinCacheOperation.readInternal(PostJoinCacheOperation.java:64)
    at com.hazelcast.spi.Operation.readData(Operation.java:557)
    at com.hazelcast.internal.serialization.impl.DataSerializer.read(DataSerializer.java:121)
    at com.hazelcast.internal.serialization.impl.DataSerializer.read(DataSerializer.java:47)
    at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:46)
    at com.hazelcast.internal.serialization.impl.AbstractSerializationService.readObject(AbstractSerializationService.java:214)
    at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readObject(ByteArrayObjectDataInput.java:600)
    at com.hazelcast.cluster.impl.operations.PostJoinOperation.readInternal(PostJoinOperation.java:136)
    at com.hazelcast.spi.Operation.readData(Operation.java:557)
    at com.hazelcast.cluster.impl.operations.FinalizeJoinOperation.readInternal(FinalizeJoinOperation.java:178)
    at com.hazelcast.spi.Operation.readData(Operation.java:557)
    at com.hazelcast.internal.serialization.impl.DataSerializer.read(DataSerializer.java:121)
    at com.hazelcast.internal.serialization.impl.DataSerializer.read(DataSerializer.java:47)
    at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:46)
    at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:170)
    at com.hazelcast.spi.impl.NodeEngineImpl.toObject(NodeEngineImpl.java:234)
    at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:378)
    at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.processPacket(OperationThread.java:184)
    at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.process(OperationThread.java:137)
    at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.doRun(OperationThread.java:124)
    at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.run(OperationThread.java:99)
Caused by: java.lang.ClassNotFoundException: fish.payara.testcases.payara1072.CustomPOJO
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at com.sun.enterprise.loader.CurrentBeforeParentClassLoader.loadClass(CurrentBeforeParentClassLoader.java:82)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at com.hazelcast.nio.ClassLoaderUtil.tryLoadClass(ClassLoaderUtil.java:137)
    at com.hazelcast.nio.ClassLoaderUtil.loadClass(ClassLoaderUtil.java:115)
    at com.hazelcast.internal.serialization.impl.JavaDefaultSerializers$ClassSerializer.read(JavaDefaultSerializers.java:179)
    ... 31 more
]]
```

A workaround is to make the cache untyped.

``` java
        cache = cacheManager.getCache("test");
        if (cache == null) {
            MutableConfiguration cconfig = new MutableConfiguration<>();
            cache = cacheManager.createCache("test", cconfig);
        }
```

It may seem obvious that this is true. However the subtlety arises when the class is available within a classloader within the same JVM but not to the Hazelcast threads as they are booted with a different classloader. This is often the case in an application server.

**Comment by vbekiaris** [comment]
Thanks for the report @smillidge! The issue occurs as the receiving cluster
member deserializes the `CacheConfig` object, a part of which is the key
and value types definition. In doing so, an attempt is made to load the class
by name, using the input's classloader in 
[ClassSerializer](https://github.com/hazelcast/hazelcast/blob/75251c4f01d131a9624fc3d0c4190de5cdf7d93a/hazelcast/src/main/java/com/hazelcast/internal/serialization/impl/JavaDefaultSerializers.java#L179-L179).
In your use case, this class is not available in this classloader, resulting in the 
`ClassNotFoundException`. A simple workaround would be to override the default
serializer, however `ClassSerializer` is one of Hazelcast's built-in "default" serializers
and cannot be overriden.
In the meanwhile, could you please describe a bit more your use case, how is Hazelcast
booted and in which classloader are domain classes available?
In what kind of setup did you encounter this issue? Are you using OSGi?

Cheers!

**Comment by smillidge** [comment]
The use case is Payara Server, which is a Java application server bootstraps Hazelcast as a core function of the server. As Hazelcast spawns its own threads then these threads will inherit the server bootclassloader. Then a user deploys a web application war file which tries to use the JCache api to create a typed cache, using the code sample above. As the war file has its own classloader the classes in the war are only visible to the war. Hence we get the problem shown. 

I think as a rule Hazelcast should try as much as possible to not deserialize application data in threads it creates as these threads will just inherit whatever classloader was on the parent thread. I know there is no problem if we use Imap it is just the JCache api that creates a problem.

**Comment by lprimak** [comment]
I think an easy way to solve this is for Hazelcast to provide a hook when running an OperationThread-based operation.  This way, Payara can do whatever it wants, i.e. set classloaders etc.

**Comment by lprimak** [comment]
Another thing, not 100% sure on what to do about this, but OperationThreadHook.onXXX() should take a parameter so Payara can determine the tenant application that created the actual object that's being worked on

**Comment by lprimak** [comment]
Another major issue is the CacheConfig serialization / deserialization when instantiating a new Hazelcast node.  Usually, Hz is initialized first before Payara gets to "deploy" any application, thus when deserializing CacheConfig, it cannot find any application classes, even if the OperationThread hooks were there.
I believe the solution to this is to defer deserializing CacheConfig to a later point (where it's used) so at that point it's guaranteed that Applications (and thus all classes) have been loaded

**Comment by lprimak** [comment]
Related issues: #9735 and #10728

**Comment by lprimak** [comment]
I have started working on PR for Hazelcast for rudimentary tenant support

**Comment by vbekiaris** [comment]
@lprimak this is awesome. I also had some thoughts about it, ping me on https://gitter.im/hazelcast/hazelcast if you want to discuss

**Comment by lprimak** [comment]
Let me do some preliminary work and I will do that!
Thanks @vbekiaris

**Comment by vbekiaris** [comment]
Great, I think the key issue here is serialization / deserialization with a proper classloader. Assuming a hypothetical model where each named Hazelcast data structure can be associated with a classloader, then there must be a way for the serialization service to identify that an incoming packet (for example an incoming entry event for a `Cache`) is meant to be deserialized with the specific classloader associated with that `Cache` so that domain objects can be resolved. However there is currently no way of having knowledge of the datastructure in advance, rather the datastructure type & name become apparent as the packet is being deserialized, so it's a sort of chicken-and-egg problem.

**Comment by lprimak** [comment]
@vbekiaris I just got a working version of the stuff going.  Should be able to get a PR soon so we can start discussing and get it going.
Thanks!

**Comment by lprimak** [comment]
Ok, I got these PRs:

#10873 and #10874 (one dependent on the other)

Also this is also dependent on couple of issues:
#10727 #10728

**Comment by lprimak** [comment]
Motivation for all of this is BJug's JCache issues as well as other customer complaints:
https://gist.github.com/ivannov/906096dcff2100ccd5b2ef11f97362dd

**Comment by lprimak** [comment]
There are similar issues with Map loaders,
they need to have ```TenantControl``` as well

**Comment by lprimak** [comment]
Looks like this issue is fixed in 3.9

**Comment by lprimak** [comment]
@smillidge you can close this issue

**Comment by Andrew-Gr** [comment]
@smillidge is workaround in your initial post (to use untyped cache) still the only way for Payara-4.1.2.181, or there is a way to use typed cache available?
What about Payara 5? What version of the Hazelcast is expected to be shipped with Payara 5?
Thank you and sorry for possible off-topic...

**Comment by smillidge** [comment]
I haven't tested 181 but it uses Hazelcast 3.8.x 
Payara 5 will use Hazelcast 3.9.x but again I personally have not tested this explicitly.

**Comment by Andrew-Gr** [comment]
Thank you for quick response! I have just faced with this issue on Payara-4.1.2.181 with Hazelcast 3.8.5 and had to use workaround with Object.class in `MutableConfiguration<String, Object> config = ...`.
Thus was curious whether more valid solution available out-of-the-box. Will try to test on Payara 5 as well soon. Thank you!

**Comment by lprimak** [comment]
We are actively working on fixing this and other related issues in Hazelcast 3.10

**Comment by lprimak** [comment]
Hazelcast 3.9 solves this particular issue, when Payara uses 3.9 this issue will be resolved
There are other related issues that are being worked for Hz 3.10
