### ISSUE TITLE
ClientLoggingServiceTest.testLog_whenGetLevel_thenDefaultLevelIsReturned

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#8999]
```
java.lang.AssertionError: expected:<OFF> but was:<INFO>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:834)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:144)
    at com.hazelcast.client.impl.ClientLoggingServiceTest.testLog_whenGetLevel_thenDefaultLevelIsReturned(ClientLoggingServiceTest.java:90)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK1.8/com.hazelcast$hazelcast-client/359/testReport/junit/com.hazelcast.client.impl/ClientLoggingServiceTest/testLog_whenGetLevel_thenDefaultLevelIsReturned/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: expected:<OFF> but was:<INFO>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.client.impl.ClientLoggingServiceTest.testLog_whenGetLevel_thenDefaultLevelIsReturned(ClientLoggingServiceTest.java:90)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-OracleJDK1.7/com.hazelcast$hazelcast-client/622/testReport/junit/com.hazelcast.client.impl/ClientLoggingServiceTest/testLog_whenGetLevel_thenDefaultLevelIsReturned/
