### ISSUE TITLE
AtomicLongAdvancedTest.testAtomicLongSpawnNodeInParallel

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#9034]
```
java.lang.AssertionError: CountDownLatch failed to complete within 120 seconds , count left: 1
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.assertTrue(Assert.java:41)
    at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:812)
    at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:805)
    at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:797)
    at com.hazelcast.concurrent.atomiclong.AtomicLongAdvancedTest.testAtomicLongSpawnNodeInParallel(AtomicLongAdvancedTest.java:98)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast$hazelcast/1051/testReport/junit/com.hazelcast.concurrent.atomiclong/AtomicLongAdvancedTest/testAtomicLongSpawnNodeInParallel/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: CountDownLatch failed to complete within 120 seconds , count left: 1
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:812)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:805)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:797)
	at com.hazelcast.concurrent.atomiclong.AtomicLongAdvancedTest.testAtomicLongSpawnNodeInParallel(AtomicLongAdvancedTest.java:98)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x/com.hazelcast$hazelcast/5952/testReport/junit/com.hazelcast.concurrent.atomiclong/AtomicLongAdvancedTest/testAtomicLongSpawnNodeInParallel/

**Comment by mmedenjak** [comment]
This build run was slowed down due to heavy load on the machine. All operations were delayed, monitoring was delayed, packet send/receive was delayed. Due to this we got a timeout on this test. I propose to close this issue.
