### ISSUE TITLE
ConditionAdvancedTest.testInterruptionDuringWaiting

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#9036]
```
org.junit.runners.model.TestTimedOutException: test timed out after 60000 milliseconds
    at sun.misc.Unsafe.park(Native Method)
    at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:196)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1011)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1303)
    at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:253)
    at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:810)
    at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:805)
    at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:797)
    at com.hazelcast.concurrent.lock.ConditionAdvancedTest.testInterruptionDuringWaiting(ConditionAdvancedTest.java:58)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK1.6/com.hazelcast$hazelcast/1056/testReport/junit/com.hazelcast.concurrent.lock/ConditionAdvancedTest/testInterruptionDuringWaiting/\

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.8/com.hazelcast$hazelcast/364/testReport/junit/com.hazelcast.concurrent.lock/ConditionAdvancedTest/testInterruptionDuringWaiting/

**Comment by mdogan** [comment]
No failure for two months.
