### ISSUE TITLE
[ZING-JVM] QueryIndexMigrationTest.testQueryWithIndexesWhileMigrating

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#9043]
```
java.lang.AssertionError: expected:<30> but was:<29>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:834)
    at org.junit.Assert.assertEquals(Assert.java:645)
    at org.junit.Assert.assertEquals(Assert.java:631)
    at com.hazelcast.map.impl.query.QueryIndexMigrationTest.testQueryWithIndexesWhileMigrating(QueryIndexMigrationTest.java:156)
```

https://hazelcast-l337.ci.cloudbees.com/view/Zing/job/Hazelcast-3.x-ZingJDK7/lastCompletedBuild/testReport/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testQueryWithIndexesWhileMigrating/

**Comment by mdogan** [comment]
same as https://github.com/hazelcast/hazelcast/issues/8046
