### ISSUE TITLE
[ZING-JVM] XMLConfigBuilderTest.testConfigurationWithFileName

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#9044]
```
java.lang.AssertionError: expected:</dev/shm//foo6112012011309985144bar> but was:</dev/shm/foo6112012011309985144bar>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:834)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:144)
    at com.hazelcast.config.XMLConfigBuilderTest.testConfigurationWithFileName(XMLConfigBuilderTest.java:87)
```

https://hazelcast-l337.ci.cloudbees.com/view/Zing/job/Hazelcast-3.x-ZingJDK8/lastCompletedBuild/testReport/com.hazelcast.config/XMLConfigBuilderTest/testConfigurationWithFileName/

https://hazelcast-l337.ci.cloudbees.com/view/Zing/job/Hazelcast-3.x-ZingJDK6/1/testReport/junit/com.hazelcast.config/XMLConfigBuilderTest/testConfigurationWithFileName/

**Comment by Donnerbart** [comment]
Tried to fix this via: https://github.com/hazelcast/hazelcast/commit/05f3a177d748740fa2d2f68544d5ee5408b46836

**Comment by hasancelik** [comment]
```
org.junit.ComparisonFailure: expected:</dev/shm/[/]foo88036943264057655...> but was:</dev/shm/[]foo88036943264057655...>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.config.XMLConfigBuilderTest.testConfigurationWithFileName(XMLConfigBuilderTest.java:89)
```

https://hazelcast-l337.ci.cloudbees.com/view/Zing/job/Hazelcast-3.x-ZingJDK6/2/testReport/com.hazelcast.config/XMLConfigBuilderTest/testConfigurationWithFileName/

**Comment by hasancelik** [comment]
```
org.junit.ComparisonFailure: expected:</dev/shm/[/]foo65963353565338750...> but was:</dev/shm/[]foo65963353565338750...>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.config.XMLConfigBuilderTest.testConfigurationWithFileName(XMLConfigBuilderTest.java:89)
```

https://hazelcast-l337.ci.cloudbees.com/view/Zing/job/Hazelcast-3.x-ZingJDK6/3/testReport/com.hazelcast.config/XMLConfigBuilderTest/testConfigurationWithFileName/

**Comment by hasancelik** [comment]
```
org.junit.ComparisonFailure: expected:</dev/shm/[/]foo53814661405122229...> but was:</dev/shm/[]foo53814661405122229...>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.config.XMLConfigBuilderTest.testConfigurationWithFileName(XMLConfigBuilderTest.java:89)
```

https://hazelcast-l337.ci.cloudbees.com/view/Zing/job/Hazelcast-3.x-ZingJDK6/lastCompletedBuild/testReport/com.hazelcast.config/XMLConfigBuilderTest/testConfigurationWithFileName/

**Comment by hasancelik** [comment]
```
org.junit.ComparisonFailure: expected:</dev/shm/[/]foo50932946883738055...> but was:</dev/shm/[]foo50932946883738055...>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.config.XMLConfigBuilderTest.testConfigurationWithFileName(XMLConfigBuilderTest.java:89)
```

https://hazelcast-l337.ci.cloudbees.com/view/Zing/job/Hazelcast-3.x-ZingJDK6/6/testReport/com.hazelcast.config/XMLConfigBuilderTest/testConfigurationWithFileName/

**Comment by hasancelik** [comment]
```
org.junit.ComparisonFailure: expected:</dev/shm/[/]foo75535294664257420...> but was:</dev/shm/[]foo75535294664257420...>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.config.XMLConfigBuilderTest.testConfigurationWithFileName(XMLConfigBuilderTest.java:89)
```

https://hazelcast-l337.ci.cloudbees.com/view/Zing/job/Hazelcast-3.x-ZingJDK6/7/testReport/com.hazelcast.config/XMLConfigBuilderTest/testConfigurationWithFileName/

**Comment by mdogan** [comment]
This is most probably a bug in Zing JDK 6. `getAbsolutePath()` returns a path containing double slashes like `/dev/shm//foo...`. 
No need to fix and no need to reopen the issue with the same cause.
