### ISSUE TITLE
Occasional NullPointerException for a semaphore release operation

### ISSUE THREAD

**Issue by marmrk** [hazelcast/hazelcast#9059]
Hello,,

we have a 6 nodes in production using hazelcast library v2.6. Occasionally, in the logs NPE occures for distributed semaphore.

What would be the cause of this exception?
```
[192.168.7.3]:5703 [dev] error processing messages  packet=Packet [SEMAPHORE_RELEASE] name=c:__hz_SemaphoreMap, connection=Connection [/192.168.7.4:5701 -> Address[192.168.7.4]:5
701] live=true, client=false, type=MEMBER,blockId=21, keySize=31, valueSize=3 client=false obj=null callId=7659
java.lang.NullPointerException
        at com.hazelcast.impl.ConcurrentMapManager$SemaphoreOperationHandler.doResponse(ConcurrentMapManager.java:3431)
        at com.hazelcast.impl.ConcurrentMapManager$SemaphoreOperationHandler.onNoTimeToSchedule(ConcurrentMapManager.java:3424)
        at com.hazelcast.impl.ConcurrentMapManager$7.onExpire(ConcurrentMapManager.java:4106)
        at com.hazelcast.impl.ConcurrentMapManager$SemaphoreOperationHandler.doResponse(ConcurrentMapManager.java:3449)
        at com.hazelcast.impl.ConcurrentMapManager$SemaphoreReleaseOperationHandler.doSemaphoreOperation(ConcurrentMapManager.java:3539)
        at com.hazelcast.impl.ConcurrentMapManager$SemaphoreOperationHandler.doOperation(ConcurrentMapManager.java:3419)
        at com.hazelcast.impl.ConcurrentMapManager$SemaphoreOperationHandler.handle(ConcurrentMapManager.java:3395)
        at com.hazelcast.impl.BaseManager$TargetAwareOperationHandler.process(BaseManager.java:292)
        at com.hazelcast.cluster.ClusterService.processPacket(ClusterService.java:175)
       at com.hazelcast.cluster.ClusterService.dequeuePackets(ClusterService.java:225)
        at com.hazelcast.cluster.ClusterService.run(ClusterService.java:190)
        at java.lang.Thread.run(Unknown Source)
```

**Comment by Donnerbart** [comment]
Are you really using Hazelcast 2.6 or is it 3.6?

**Comment by marmrk** [comment]
I've just checked, it's 2.6

**Comment by pveentjer** [comment]
Please upgrade to 3.6. 2.6 is EOL; meaning there is no more development on it.
