### ISSUE TITLE
3.7 member + 3.8-SNAPSHOT member can't from cluster.

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#9064]
Test: https://hazelcast-l337.ci.cloudbees.com/view/multi-version/job/put-get/3/console
http://54.87.52.100/~jenkins/workspace/put-get/3.8-SNAPSHOT/2016_10_07-14_27_47/

http://54.87.52.100/~jenkins/workspace/put-get/3.8-SNAPSHOT/2016_10_07-14_27_47/go
from the scrip we see we are are starting a cluster with mixed version.
first Member 3.8-SANPSHOT (hat master version)
2nd Member a 3.7 

HzMember1HZ  3.8-SNAPSHOT
http://54.87.52.100/~jenkins/workspace/put-get/3.8-SNAPSHOT/2016_10_07-14_27_47/output/HZ/HzMember1HZ/out.txt
```
INFO: [10.0.0.188]:5701 [HZ] [3.8-SNAPSHOT] 


Members [1] {
	Member [10.0.0.188]:5701 - 04a6b61e-cee7-4699-bb8f-917bb56385e0 this
}

Oct 07, 2016 11:28:48 AM com.hazelcast.core.LifecycleService
INFO: [10.0.0.188]:5701 [HZ] [3.8-SNAPSHOT] [10.0.0.188]:5701 is STARTED
Oct 07, 2016 11:29:08 AM com.hazelcast.nio.tcp.SocketAcceptorThread
INFO: [10.0.0.188]:5701 [HZ] [3.8-SNAPSHOT] Accepting socket connection from /10.0.0.188:47572
Oct 07, 2016 11:29:08 AM com.hazelcast.nio.tcp.TcpIpConnectionManager
INFO: [10.0.0.188]:5701 [HZ] [3.8-SNAPSHOT] Established socket connection between /10.0.0.188:5701 and /10.0.0.188:47572
Oct 07, 2016 11:29:08 AM com.hazelcast.nio.tcp.nonblocking.NonBlockingSocketWriter
WARNING: [10.0.0.188]:5701 [HZ] [3.8-SNAPSHOT] SocketWriter is not set, creating WriteHandler with CLUSTER protocol!
Oct 07, 2016 11:29:09 AM com.hazelcast.spi.impl.operationservice.impl.ResponseHandler
WARNING: [10.0.0.188]:5701 [HZ] [3.8-SNAPSHOT] No Invocation found for error response with callId: 0 sent from [10.0.0.188]:5702
Oct 07, 2016 11:29:09 AM com.hazelcast.spi.impl.operationservice.impl.ResponseHandler
WARNING: [10.0.0.188]:5701 [HZ] [3.8-SNAPSHOT] No Invocation found for error response with callId: 0 sent from [10.0.0.188]:5702
Oct 07, 2016 11:29:10 AM com.hazelcast.spi.impl.operationservice.impl.ResponseHandler
WARNING: [10.0.0.188]:5701 [HZ] [3.8-SNAPSHOT] No Invocation found for error response with callId: 0 sent from [10.0.0.188]:5702
Oct 07, 2016 11:29:11 AM com.hazelcast.spi.impl.operationservice.impl.ResponseHandler
```
...
..
.
```
WARNING: [10.0.0.188]:5701 [HZ] [3.8-SNAPSHOT] No Invocation found for error response with callId: 0 sent from [10.0.0.188]:5702
Oct 07, 2016 11:33:45 AM com.hazelcast.spi.impl.operationservice.impl.ResponseHandler
WARNING: [10.0.0.188]:5701 [HZ] [3.8-SNAPSHOT] No Invocation found for error response with callId: 0 sent from [10.0.0.188]:5702
Oct 07, 2016 11:33:46 AM com.hazelcast.spi.impl.operationservice.impl.ResponseHandler
WARNING: [10.0.0.188]:5701 [HZ] [3.8-SNAPSHOT] No Invocation found for error response with callId: 0 sent from [10.0.0.188]:5702
Oct 07, 2016 11:33:47 AM com.hazelcast.spi.impl.operationservice.impl.ResponseHandler
WARNING: [10.0.0.188]:5701 [HZ] [3.8-SNAPSHOT] No Invocation found for error response with callId: 0 sent from [10.0.0.188]:5702
Oct 07, 2016 11:33:47 AM com.hazelcast.cluster.impl.TcpIpJoiner
WARNING: [10.0.0.188]:5701 [HZ] [3.8-SNAPSHOT] Error during join check!
java.util.concurrent.ExecutionException: com.hazelcast.nio.serialization.HazelcastSerializationException: com.hazelcast.internal.cluster.impl.ClusterDataSerializerHook$ClusterDataSerializerFactoryImpl@f0a0101 is not be able to create an instance for id: 13 on factoryId: 0
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrow(InvocationFuture.java:88)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:181)
	at com.hazelcast.internal.cluster.impl.AbstractJoiner.sendSplitBrainJoinMessage(AbstractJoiner.java:325)
	at com.hazelcast.cluster.impl.TcpIpJoiner.searchForOtherClusters(TcpIpJoiner.java:519)
	at com.hazelcast.internal.cluster.impl.SplitBrainHandler.searchForOtherClusters(SplitBrainHandler.java:75)
	at com.hazelcast.internal.cluster.impl.SplitBrainHandler.run(SplitBrainHandler.java:42)
	at com.hazelcast.spi.impl.executionservice.impl.SkipOnConcurrentExecutionDecorator.run(SkipOnConcurrentExecutionDecorator.java:40)
	at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)
Caused by: com.hazelcast.nio.serialization.HazelcastSerializationException: com.hazelcast.internal.cluster.impl.ClusterDataSerializerHook$ClusterDataSerializerFactoryImpl@f0a0101 is not be able to create an instance for id: 13 on factoryId: 0
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:119)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:52)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:46)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:172)
	at com.hazelcast.spi.impl.NodeEngineImpl.toObject(NodeEngineImpl.java:307)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:380)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:117)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:102)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:114)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrow(InvocationFuture.java:75)
	... 12 more

Oct 07, 2016 11:33:48 AM com.hazelcast.spi.impl.operationservice.impl.ResponseHandler
WARNING: [10.0.0.188]:5701 [HZ] [3.8-SNAPSHOT] No Invocation found for error response with callId: 0 sent from [10.0.0.188]:5702
Oct 07, 2016 11:33:49 AM com.hazelcast.spi.impl.operationservice.impl.ResponseHandler
```

HzMember2HZ  3.7
http://54.87.52.100/~jenkins/workspace/put-get/3.8-SNAPSHOT/2016_10_07-14_27_47/output/HZ/HzMember2HZ/out.txt
```
INFO: [10.0.0.188]:5702 [HZ] [3.7] Established socket connection between /10.0.0.188:47572 and /10.0.0.188:5701
Oct 07, 2016 11:29:09 AM com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl
SEVERE: [10.0.0.188]:5702 [HZ] [3.7] com.hazelcast.internal.cluster.impl.ClusterDataSerializerHook$ClusterDataSerializerFactoryImpl@f0a0101 is not be able to create an instance for id: 24 on factoryId: 0
com.hazelcast.nio.serialization.HazelcastSerializationException: com.hazelcast.internal.cluster.impl.ClusterDataSerializerHook$ClusterDataSerializerFactoryImpl@f0a0101 is not be able to create an instance for id: 24 on factoryId: 0
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:119)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:52)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:46)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:172)
	at com.hazelcast.spi.impl.NodeEngineImpl.toObject(NodeEngineImpl.java:307)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:380)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:117)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:102)
```

**Comment by Danny-Hazelcast** [comment]
not supported

**Comment by jerrinot** [comment]
this is expected. there is no support for heterogeneous clusters as of 3.7.
Clients can have different versions than members but all members have to have in the same (minor) version. Member can differ only in their patch-release
