### ISSUE TITLE
QueryAdvancedTest.testQueryWithTTL

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#9071]
```
java.lang.AssertionError: expected:<5> but was:<1>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:834)
    at org.junit.Assert.assertEquals(Assert.java:645)
    at org.junit.Assert.assertEquals(Assert.java:631)
    at com.hazelcast.map.impl.query.QueryAdvancedTest.testQueryWithTTL(QueryAdvancedTest.java:141)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.8/com.hazelcast$hazelcast/368/testReport/junit/com.hazelcast.map.impl.query/QueryAdvancedTest/testQueryWithTTL/

**Comment by mdogan** [comment]
No failure for two months.
