### ISSUE TITLE
NPE Diagnostics

### ISSUE THREAD

**Issue by pveentjer** [hazelcast/hazelcast#9085]
NPE using 3.8 master.

```
output threads
WARN  2016-10-11 11:20:53,441 [hz._hzInstance_1_workers.DiagnosticsSchedulerThread] com.hazelcast.internal.diagnostics.Diagnostics: [10.212.1.111]:5701 [workers] [3.8-SNAPSHOT] Failed to write file: /home/simulator/hazelcast-simulator-0.9-
RC1-SNAPSHOT/workers/2016-10-11__11_20_47/C_A1_W1-10.212.1.111-member/diagnostics-10.212.1.111_5701-1476174052737-000.log
java.lang.NullPointerException
        at java.io.PrintWriter.write(PrintWriter.java:473)
        at com.hazelcast.internal.diagnostics.DiagnosticsLogWriter.write(DiagnosticsLogWriter.java:107)
        at com.hazelcast.internal.diagnostics.MultiLineDiagnosticsLogWriter.writeKeyValueEntry(MultiLineDiagnosticsLogWriter.java:75)
        at com.hazelcast.internal.diagnostics.MemberHazelcastInstanceInfoPlugin.run(MemberHazelcastInstanceInfoPlugin.java:74)
        at com.hazelcast.internal.diagnostics.DiagnosticsLogFile.renderPlugin(DiagnosticsLogFile.java:109)
        at com.hazelcast.internal.diagnostics.DiagnosticsLogFile.write(DiagnosticsLogFile.java:84)
        at com.hazelcast.internal.diagnostics.Diagnostics$WritePluginTask.run(Diagnostics.java:214)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by pveentjer** [comment]
I have found the cause. The DiagnosticsLogWriter doesn't deal with writing null values correctly.
