### ISSUE TITLE
Client connectivity issue

### ISSUE THREAD

**Issue by pveentjer** [hazelcast/hazelcast#9090]
While running simulator I'm running into some exceptions when running with a client. Likely they are related to the io changed I made recently.

First exception:

```
7796, alive=false, type=JAVA_CLIENT] closed. Reason: Exception in NonBlockingSocketReader
java.lang.IllegalArgumentException: Client message frame length cannot be smaller than header size.
        at com.hazelcast.client.impl.protocol.ClientMessage.readFrom(ClientMessage.java:333)
        at com.hazelcast.client.impl.protocol.util.ClientMessageReadHandler.onRead(ClientMessageReadHandler.java:50)
        at com.hazelcast.nio.tcp.ClientReadHandler.onRead(ClientReadHandler.java:53)
        at com.hazelcast.nio.tcp.nonblocking.NonBlockingSocketReader.handle(NonBlockingSocketReader.java:163)
        at com.hazelcast.nio.tcp.nonblocking.NonBlockingIOThread.handleSelectionKey(NonBlockingIOThread.java:349)
        at com.hazelcast.nio.tcp.nonblocking.NonBlockingIOThread.handleSelectionKeys(NonBlockingIOThread.java:334)
        at com.hazelcast.nio.tcp.nonblocking.NonBlockingIOThread.selectLoop(NonBlockingIOThread.java:252)
        at com.hazelcast.nio.tcp.nonblocking.NonBlockingIOThread.run(NonBlockingIOThread.java:205)
```

**Comment by jerrinot** [comment]
there is a good chance it's related to https://github.com/hazelcast/hazelcast/issues/9062
in both cases a frame length is likely misinterpreted.

**Comment by pveentjer** [comment]
I was hoping it would be the first packet running into this problem. I added some counters:

```
java.lang.IllegalStateException: Failed at packet: 20002
        at com.hazelcast.nio.tcp.ClientReadHandler.onRead(ClientReadHandler.java:58)
        at com.hazelcast.nio.tcp.nonblocking.NonBlockingSocketReader.handle(NonBlockingSocketReader.java:163)
        at com.hazelcast.nio.tcp.nonblocking.NonBlockingIOThread.handleSelectionKey(NonBlockingIOThread.java:349)
        at com.hazelcast.nio.tcp.nonblocking.NonBlockingIOThread.handleSelectionKeys(NonBlockingIOThread.java:334)
        at com.hazelcast.nio.tcp.nonblocking.NonBlockingIOThread.selectLoop(NonBlockingIOThread.java:252)
        at com.hazelcast.nio.tcp.nonblocking.NonBlockingIOThread.run(NonBlockingIOThread.java:205)
Caused by: java.lang.IllegalArgumentException: Client message frame length cannot be smaller than header size.
        at com.hazelcast.client.impl.protocol.ClientMessage.readFrom(ClientMessage.java:333)
        at com.hazelcast.client.impl.protocol.util.ClientMessageReadHandler.onRead(ClientMessageReadHandler.java:50)
        at com.hazelcast.nio.tcp.ClientReadHandler.onRead(ClientReadHandler.java:56)
        ... 5 more
```

So it gets messed up somewhere in the stream.

**Comment by pveentjer** [comment]
Probably caused by this commit:

https://github.com/hazelcast/hazelcast/commit/b9390d845d809c1e199dd4a23b6c842e27d18d40

The problem immediately happens when using this commit. One commit before and 3 runs without a single failure.

**Comment by pveentjer** [comment]
PR in the making
