### ISSUE TITLE
QueryAdvancedTest.testSecondMemberAfterAddingIndexes

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#9123]
```
java.lang.AssertionError: expected:<23> but was:<22>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:834)
    at org.junit.Assert.assertEquals(Assert.java:645)
    at org.junit.Assert.assertEquals(Assert.java:631)
    at com.hazelcast.map.impl.query.QueryBasicTest.doFunctionalQueryTest(QueryBasicTest.java:538)
    at com.hazelcast.map.impl.query.QueryAdvancedTest.testSecondMemberAfterAddingIndexes(QueryAdvancedTest.java:401)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.8/com.hazelcast$hazelcast/377/testReport/junit/com.hazelcast.map.impl.query/QueryAdvancedTest/testSecondMemberAfterAddingIndexes/

**Comment by mdogan** [comment]
No failure for two months.
