### ISSUE TITLE
hz 3.8-SNAPSHOT members fail to form cluster / return from creating instance

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#9125]
```
SEVERE: [10.0.0.111]:5701 [HZ] [3.8-SNAPSHOT] Failed to process packet: Packet{flags=17, isResponse=false, isOperation=true, isEvent=false, partitionId=-1, conn=Connection[id=6, /10.0.0.111:33631->/10.0.0.109:5701, endpoint=[10.0.0.109]:5701, alive=true, type=MEMBER]} on hz._hzInstance_1_HZ.priority-generic-operation.thread-0
com.hazelcast.nio.serialization.HazelcastSerializationException: Problem while reading DataSerializable, namespace: 0, id: 7, class: 'null', exception: String index out of range: -2
           at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.rethrowReadException(DataSerializableSerializer.java:141)
           at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:130)
           at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:52)
           at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:46)
           at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:172)
           at com.hazelcast.spi.impl.NodeEngineImpl.toObject(NodeEngineImpl.java:307)
           at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:376)
           at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:117)
           at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:102)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -2
           at java.lang.String.<init>(String.java:197)
           at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readUTF(ByteArrayObjectDataInput.java:595)
           at com.hazelcast.internal.cluster.impl.operations.FinalizeJoinOperation.readInternal(FinalizeJoinOperation.java:185)
           at com.hazelcast.spi.Operation.readData(Operation.java:513)
           at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:127)
           ... 7 more
```

**Comment by Danny-Hazelcast** [comment]
hz version
```
INFO: [10.0.0.38]:5701 [HZ] [3.8-SNAPSHOT] Hazelcast Enterprise 3.8-SNAPSHOT (20161017 - 7dad0f5) starting at [10.0.0.38]:5701
```

```
Oct 17, 2016 2:50:18 PM com.hazelcast.internal.cluster.impl.ClusterJoinManager
WARNING: [10.0.0.38]:5701 [HZ] [3.8-SNAPSHOT] While waiting finalize join calls...
java.util.concurrent.ExecutionException: com.hazelcast.nio.serialization.HazelcastSerializationException: Problem while reading DataSerializable, namespace: 0, id: 7, class: 'null', exception: String index out of range: -2
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrow(InvocationFuture.java:88)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:181)
	at com.hazelcast.util.FutureUtil.executeWithDeadline(FutureUtil.java:326)
	at com.hazelcast.util.FutureUtil.waitWithDeadline(FutureUtil.java:310)
	at com.hazelcast.util.FutureUtil.waitWithDeadline(FutureUtil.java:284)
	at com.hazelcast.internal.cluster.impl.ClusterJoinManager.startJoin(ClusterJoinManager.java:531)
	at com.hazelcast.internal.cluster.impl.ClusterJoinManager.startJoinRequest(ClusterJoinManager.java:324)
	at com.hazelcast.internal.cluster.impl.ClusterJoinManager.executeJoinRequest(ClusterJoinManager.java:230)
	at com.hazelcast.internal.cluster.impl.ClusterJoinManager.handleJoinRequest(ClusterJoinManager.java:150)
	at com.hazelcast.internal.cluster.impl.operations.JoinRequestOperation.run(JoinRequestOperation.java:41)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:181)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:391)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:117)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:102)
Caused by: com.hazelcast.nio.serialization.HazelcastSerializationException: Problem while reading DataSerializable, namespace: 0, id: 7, class: 'null', exception: String index out of range: -2
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.rethrowReadException(DataSerializableSerializer.java:141)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:130)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:52)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:46)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:172)
	at com.hazelcast.spi.impl.NodeEngineImpl.toObject(NodeEngineImpl.java:307)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:376)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:117)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:102)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:114)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrow(InvocationFuture.java:75)
	... 13 more
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -2
	at java.lang.String.<init>(String.java:197)
	at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readUTF(ByteArrayObjectDataInput.java:595)
	at com.hazelcast.internal.cluster.impl.operations.FinalizeJoinOperation.readInternal(FinalizeJoinOperation.java:185)
	at com.hazelcast.spi.Operation.readData(Operation.java:513)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:127)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:52)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:46)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:172)
	at com.hazelcast.spi.impl.NodeEngineImpl.toObject(NodeEngineImpl.java:307)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:376)
	... 2 more

Oct 17, 2016 2:50:19 PM com.hazelcast.spi.impl.operationservice.impl.ResponseHandler
WARNING: [10.0.0.38]:5701 [HZ] [3.8-SNAPSHOT] No Invocation found for error response with callId: 0 sent from [10.0.0.40]:5701
Oct 17, 2016 2:50:19 PM com.hazelcast.spi.impl.operationservice.impl.ResponseHandler
WARNING: [10.0.0.38]:5701 [HZ] [3.8-SNAPSHOT] No Invocation found for error response with callId: 0 sent from [10.0.0.41]:5701
Oct 17, 2016 2:50:19 PM com.hazelcast.spi.impl.operationservice.impl.ResponseHandler
WARNING: [10.0.0.38]:5701 [HZ] [3.8-SNAPSHOT] No Invocation found for error response with callId: 0 sent from [10.0.0.39]:5701
Oct 17, 2016 2:50:20 PM com.hazelcast.spi.impl.operationservice.impl.ResponseHandler
WARNING: [10.0.0.38]:5701 [HZ] [3.8-SNAPSHOT] No Invocation found for error response with callId: 0 sent from [10.0.0.40]:5701
Oct 17, 2016 2:50:20 PM com.hazelcast.spi.impl.operationservice.impl.ResponseHandler
WARNING: [10.0.0.38]:5701 [HZ] [3.8-SNAPSHOT] No Invocation found for error response with callId: 0 sent from [10.0.0.41]:5701
Oct 17, 2016 2:50:20 PM com.hazelcast.spi.impl.operationservice.impl.ResponseHandler
WARNING: [10.0.0.38]:5701 [HZ] [3.8-SNAPSHOT] No Invocation found for error response with callId: 0 sent from [10.0.0.39]:5701
Oct 17, 2016 2:50:21 PM com.hazelcast.spi.impl.operationservice.impl.ResponseHandler
```



```
INFO: [10.0.0.40]:5701 [HZ] [3.8-SNAPSHOT] Could not connect to: /10.0.0.38:5703. Reason: SocketException[Connection refused to address /10.0.0.38:5703]
Oct 17, 2016 2:50:06 PM com.hazelcast.nio.tcp.TcpIpConnectionManager
INFO: [10.0.0.40]:5701 [HZ] [3.8-SNAPSHOT] Established socket connection between /10.0.0.40:35498 and /10.0.0.41:5701
Oct 17, 2016 2:50:06 PM com.hazelcast.nio.tcp.SocketWriterInitializerImpl
WARNING: [10.0.0.40]:5701 [HZ] [3.8-SNAPSHOT] SocketWriter is not set, creating WriteHandler with CLUSTER protocol!
Oct 17, 2016 2:50:06 PM com.hazelcast.nio.tcp.SocketWriterInitializerImpl
WARNING: [10.0.0.40]:5701 [HZ] [3.8-SNAPSHOT] SocketWriter is not set, creating WriteHandler with CLUSTER protocol!
Oct 17, 2016 2:50:06 PM com.hazelcast.nio.tcp.SocketWriterInitializerImpl
WARNING: [10.0.0.40]:5701 [HZ] [3.8-SNAPSHOT] SocketWriter is not set, creating WriteHandler with CLUSTER protocol!
Oct 17, 2016 2:50:06 PM com.hazelcast.cluster.impl.TcpIpJoiner
```

```
SEVERE: [10.0.0.40]:5701 [HZ] [3.8-SNAPSHOT] Problem while reading DataSerializable, namespace: 0, id: 7, class: 'null', exception: String index out of range: -2
com.hazelcast.nio.serialization.HazelcastSerializationException: Problem while reading DataSerializable, namespace: 0, id: 7, class: 'null', exception: String index out of range: -2
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.rethrowReadException(DataSerializableSerializer.java:141)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:130)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:52)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:46)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:172)
	at com.hazelcast.spi.impl.NodeEngineImpl.toObject(NodeEngineImpl.java:307)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:376)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:117)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:102)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -2
	at java.lang.String.<init>(String.java:197)
	at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readUTF(ByteArrayObjectDataInput.java:595)
	at com.hazelcast.internal.cluster.impl.operations.FinalizeJoinOperation.readInternal(FinalizeJoinOperation.java:185)
	at com.hazelcast.spi.Operation.readData(Operation.java:513)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:127)
	... 7 more

Oct 17, 2016 2:50:18 PM com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl
SEVERE: [10.0.0.40]:5701 [HZ] [3.8-SNAPSHOT] Failed to process packet: Packet{flags=17, isResponse=false, isOperation=true, isEvent=false, partitionId=-1, conn=Connection[id=6, /10.0.0.40:5701->/10.0.0.38:58284, endpoint=[10.0.0.38]:5701, alive=true, type=MEMBER]} on hz._hzInstance_1_HZ.priority-generic-operation.thread-0
```

**Comment by tombujok** [comment]
@Danny-Hazelcast Fix in EE version only.
