### ISSUE TITLE
NullPointerException while deleting an entry through Entry Processor by setting value to NULL

### ISSUE THREAD

**Issue by GirishKumar0310** [hazelcast/hazelcast#9135]
Hi when I try to delete an entry from cache through entry processor by setting value to null as per link updated by Ali Gurbuz https://groups.google.com/forum/#!topic/hazelcast/0B271m6vfBY,

 I am getting following inconsistently. Any idea why this happens and any work arounds? Version is 3.6.1

2016-10-19 03:50:43,710 ERROR [hz._hzInstance_1_M-SYD-V-SQL-H01/instance_EMEA2014_ODI.partition-operation.thread-0] PartitionWideEntryWithPredicateOperation:50 - [M-SYD-V-APP-M01]:25561 [M-SYD-V-SQL-H01/instance_EMEA2014_ODI_u_pControl] [3.6.1] null
java.lang.NullPointerException
at com.hazelcast.map.impl.operation.AbstractMultipleEntryOperation.doPostOps(AbstractMultipleEntryOperation.java:175)
at com.hazelcast.map.impl.operation.AbstractMultipleEntryOperation.entryRemoved(AbstractMultipleEntryOperation.java:147)
at com.hazelcast.map.impl.operation.PartitionWideEntryOperation.run(PartitionWideEntryOperation.java:81)
at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:172)
at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:393)
at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.processPacket(OperationThread.java:184)
at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.process(OperationThread.java:137)
at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.doRun(OperationThread.java:124)
at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.run(OperationThread.java:99)

**Comment by ahmetmircik** [comment]
Thanks for reporting this. It is a bug and appears when you have either `PostProcessingMapStore` or `MapInterceptor` and removing an entry.

**Comment by GirishKumar0310** [comment]
Hi, Any idea when this would be fixed? We have clients in production.

**Comment by ahmetmircik** [comment]
Hi @GirishKumar0310, 
Fix is ready and waiting to be merged: https://github.com/hazelcast/hazelcast/pull/9141. 
After merge, 3.6.6 release will be available in one week time most probably.
