### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: com/hazelcast/nio/ConnectionListenable

### ISSUE THREAD

**Issue by JuKu** [hazelcast/hazelcast#9136]
Hi,

We have upgraded from Hazelcast version 3.5.4 to 3.7.2 and get this exception now:
```
Exception in thread "main" java.lang.NoClassDefFoundError: com/hazelcast/nio/ConnectionListenable
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.hazelcast.client.HazelcastClientManager.newHazelcastClient(HazelcastClientManager.java:73)
	at com.hazelcast.client.HazelcastClient.newHazelcastClient(HazelcastClient.java:72)
	at com.pentaquin.core.database.hazelcast.HazelcastFactory.getHazelcastInstance(HazelcastFactory.java:39)
	at com.pentaquin.core.database.hazelcast.HazelcastFactory.getHazelcastInstanceFromConfig(HazelcastFactory.java:56)
	at com.pentaquin.proxy.server.ServerMain.main(ServerMain.java:156)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.ClassNotFoundException: com.hazelcast.nio.ConnectionListenable
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 22 more
```

I think its an bug in hazelcast.

Here is the class HazelcastFactory:
```java
public class HazelcastFactory {

    private static int counter = 0;

    /**
    * get hazelcast instance
     *
     * @return hazelcastInstance
    */
    public static HazelcastInstance getHazelcastInstance (String ip, int port, String user, String password) {
        ClientConfig clientConfig = new ClientConfig();
        clientConfig.getGroupConfig().setName(user).setPassword(password);
        clientConfig.getNetworkConfig().addAddress(ip + ":" + port);
        HazelcastInstance hazelcastInstance = HazelcastClient.newHazelcastClient(clientConfig);

        return hazelcastInstance;
    }

    /**
    * generate hazelcast configuration from configuration file and return hazelcast instance
    */
    public static HazelcastInstance getHazelcastInstanceFromConfig (File configFile) throws IOException {
        Ini ini = new Ini(configFile);
        Profile.Section section = ini.get("Hazelcast");

        String ip = section.get("ip");
        int port = Integer.parseInt(section.getOrDefault("port", "5701"));
        String user = section.get("user");
        String password = section.get("password");

        return HazelcastFactory.getHazelcastInstance(ip, port, user, password);
    }

}
```

Was this class removed?
Or why classloader couldnt found it?

**Comment by noctarius** [comment]
Are you sure there's only one version of Hazelcast in the classpath? Can you verify? Especially on upgrades it happens a lot that old JARs still somewhere in the classpath and produce all kinds of weird behavior :)

**Comment by jerrinot** [comment]
@JuKu: do you have any update? it indeed looks like a class versions conflict aka JAR hell.

**Comment by altfatterz** [comment]
could also reproduce the issue if `hazelcast-client` is 3.7.2 and `hazelcast` 3.6.5, make sure their version match, by declaring it explicitly

```
        <dependency>
			<groupId>com.hazelcast</groupId>
			<artifactId>hazelcast-client</artifactId>
			<version>3.7.2</version>
		</dependency>
		<dependency>
			<groupId>com.hazelcast</groupId>
			<artifactId>hazelcast</artifactId>
			<version>3.7.2</version>
		</dependency>
```

**Comment by JuKu** [comment]
Thanks for your help!

I have resolved the issue.
Their was some problems:
1. Snowcast currently doesnt support Hazelcast 3.7.2 and use an outdated version.
@noctarius has give this tipp.
2. The other problem was an wrong dependencie in an other library, which was using hazelcast (and uses an older version)

The problem ist, that hazelcast version 3.5.x and 3.7.x isnt compatbile.
