### ISSUE TITLE
RingbufferStoreTest.testRingbufferStoreAllAndReadFromMemory

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#9154]
```
java.lang.AssertionError: expected:<200> but was:<0>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:834)
    at org.junit.Assert.assertEquals(Assert.java:645)
    at org.junit.Assert.assertEquals(Assert.java:631)
    at com.hazelcast.ringbuffer.impl.RingbufferStoreTest.testRingbufferStoreAllAndReadFromMemory(RingbufferStoreTest.java:138)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK1.7/com.hazelcast$hazelcast/648/testReport/junit/com.hazelcast.ringbuffer.impl/RingbufferStoreTest/testRingbufferStoreAllAndReadFromMemory/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: expected:<200> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.ringbuffer.impl.RingbufferStoreTest.testRingbufferStoreAllAndReadFromMemory(RingbufferStoreTest.java:138)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast$hazelcast/1079/testReport/junit/com.hazelcast.ringbuffer.impl/RingbufferStoreTest/testRingbufferStoreAllAndReadFromMemory/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: expected:<200> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.ringbuffer.impl.RingbufferStoreTest.testRingbufferStoreAllAndReadFromMemory(RingbufferStoreTest.java:138)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-ZuluJDK8/com.hazelcast$hazelcast/393/testReport/junit/com.hazelcast.ringbuffer.impl/RingbufferStoreTest/testRingbufferStoreAllAndReadFromMemory/
