### ISSUE TITLE
BasicMapTest.testMapLockAndUnlockAndTryLock

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#9156]
```
java.lang.AssertionError: null
    at org.junit.Assert.fail(Assert.java:86)
    at org.junit.Assert.assertTrue(Assert.java:41)
    at org.junit.Assert.assertTrue(Assert.java:52)
    at com.hazelcast.map.BasicMapTest.testMapLockAndUnlockAndTryLock(BasicMapTest.java:595)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-ZuluJDK7/com.hazelcast$hazelcast/367/testReport/junit/com.hazelcast.map/BasicMapTest/testMapLockAndUnlockAndTryLock/

**Comment by jerrinot** [comment]
there is a fragile test - it depends on timing, the failure is easy to reproduce with additional sleeping. I'll send a PR for this one.
