### ISSUE TITLE
CardinalityEstimatorAdvancedTest.testCardinalityEstimatorFailure_whenSwitchedToDense

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#9217]
```
java.lang.AssertionError: expected:<10059> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.cardinality.CardinalityEstimatorAdvancedTest.testCardinalityEstimatorFailure_whenSwitchedToDense(CardinalityEstimatorAdvancedTest.java:60)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-OracleJDK1.7/com.hazelcast$hazelcast/659/testReport/junit/com.hazelcast.cardinality/CardinalityEstimatorAdvancedTest/testCardinalityEstimatorFailure_whenSwitchedToDense/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: expected:<10059> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.cardinality.CardinalityEstimatorAdvancedTest.testCardinalityEstimatorFailure_whenSwitchedToDense(CardinalityEstimatorAdvancedTest.java:60)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.8/com.hazelcast$hazelcast/404/testReport/junit/com.hazelcast.cardinality/CardinalityEstimatorAdvancedTest/testCardinalityEstimatorFailure_whenSwitchedToDense/

**Comment by tkountis** [comment]
Functionality seems to be correct, I don't see any race condition that could cause this. System seems to be going in overdrive, big delays in operations, big cluster time shifts and many migrations from which many aren't successful due to Nodes being still in STARTING mode. At some point, partitions are lost completely, which leads to the wrong figures. This is the same behaviour with both #9017 and #9124 . 

I checked system load on the diagnostic logs of the last build, and load was ok, no reason to have caused these delays. I don't know what caused this behaviour, but it also seems related to #9202. I would close the issue.

**Comment by hasancelik** [comment]
```
java.lang.NullPointerException: null
	at com.hazelcast.test.HazelcastTestSupport.getClusterService(HazelcastTestSupport.java:182)
	at com.hazelcast.test.HazelcastTestSupport.getAddress(HazelcastTestSupport.java:206)
	at com.hazelcast.test.HazelcastTestSupport.assertAllInSafeState(HazelcastTestSupport.java:667)
	at com.hazelcast.test.HazelcastTestSupport$4.run(HazelcastTestSupport.java:645)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1016)
	at com.hazelcast.test.HazelcastTestSupport.waitAllForSafeState(HazelcastTestSupport.java:643)
	at com.hazelcast.test.HazelcastTestSupport.waitAllForSafeState(HazelcastTestSupport.java:639)
	at com.hazelcast.test.HazelcastTestSupport.waitAllForSafeState(HazelcastTestSupport.java:635)
	at com.hazelcast.cardinality.CardinalityEstimatorAdvancedTest.testCardinalityEstimatorFailure_whenSwitchedToDense(CardinalityEstimatorAdvancedTest.java:60)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast$hazelcast/1156/testReport/junit/com.hazelcast.cardinality/CardinalityEstimatorAdvancedTest/testCardinalityEstimatorFailure_whenSwitchedToDense/
