### ISSUE TITLE
RingbufferAddReadOneStressTest.whenTTLEnabled

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#9222]
```
java.lang.AssertionError: No error should have been thrown, but ConsumeThread-1 completed error expected null, but was:<com.hazelcast.ringbuffer.StaleSequenceException: sequence:409847 is too small and data store is disabled. The current headSequence is:409848 tailSequence is:409847>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotNull(Assert.java:755)
	at org.junit.Assert.assertNull(Assert.java:737)
	at com.hazelcast.test.TestThread.assertSucceedsEventually(TestThread.java:62)
	at com.hazelcast.ringbuffer.impl.RingbufferAddReadOneStressTest.test(RingbufferAddReadOneStressTest.java:84)
	at com.hazelcast.ringbuffer.impl.RingbufferAddReadOneStressTest.whenTTLEnabled(RingbufferAddReadOneStressTest.java:40)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/1128/testReport/junit/com.hazelcast.ringbuffer.impl/RingbufferAddReadOneStressTest/whenTTLEnabled/

**Comment by jerrinot** [comment]
fixed by #9505
