### ISSUE TITLE
ClientMapNearCacheTest.receives_one_clearEvent_after_mapEvictAll_call_from_member

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#9223]
```
java.lang.AssertionError: Expecting only 1 clear event expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.client.map.impl.nearcache.ClientMapNearCacheTest$31.run(ClientMapNearCacheTest.java:1096)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:905)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:919)
	at com.hazelcast.client.map.impl.nearcache.ClientMapNearCacheTest.receives_one_clearEvent_after_mapEvictAll_call_from_member(ClientMapNearCacheTest.java:1093)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance/com.hazelcast$hazelcast-client/1469/testReport/junit/com.hazelcast.client.map.impl.nearcache/ClientMapNearCacheTest/receives_one_clearEvent_after_mapEvictAll_call_from_member_batchInvalidationEnabled_true_/

**Comment by mdogan** [comment]
No failures since November.
