### ISSUE TITLE
failed to start jmx

### ISSUE THREAD

**Issue by dmitrymz** [hazelcast/hazelcast#9293]
when attempting to start cluster node v3.6.5 with jmx enabled getting exception below and node is self-terminated immediately. 

jvm args: -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.port=15701 -Dcom.sun.management.jmxremo
te.authenticate=false -Dhazelcast.jmx=true

```
Exception in thread "main" java.lang.IllegalArgumentException
	at com.hazelcast.jmx.ManagementService.createObjectName(ManagementService.java:182)
	at com.hazelcast.jmx.MapMBean.<init>(MapMBean.java:39)
	at com.hazelcast.jmx.MBeans$MBeanFactory$1.createNew(MBeans.java:89)
	at com.hazelcast.jmx.MBeans.createHazelcastMBeanOrNull(MBeans.java:71)
	at com.hazelcast.jmx.ManagementService.registerDistributedObject(ManagementService.java:130)
	at com.hazelcast.jmx.ManagementService.<init>(ManagementService.java:77)
	at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:136)
	at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:160)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:143)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:111)
	at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:87)
	at com.mz.core.hazelcast.server.HazelcastServer.main(HazelcastServer.java:19)
Hazelcast cluster node destroyed

```

**Comment by jerrinot** [comment]
hi @dmitrymz, can you post your configuration?

**Comment by dmitrymz** [comment]
```
<hazelcast xsi:schemaLocation="http://www.hazelcast.com/schema/config
    http://www.hazelcast.com/schema/config/hazelcast-config-3.5.xsd"
           xmlns="http://www.hazelcast.com/schema/config"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <properties>
        <property name="hazelcast.logging.type">slf4j</property>
        <property name="hazelcast.icmp.enabled">true</property>
    </properties>

    <network>
        <port auto-increment="false">5701</port>
        <join>
            <multicast enabled="false"/>
            <tcp-ip enabled="false"/>
            <aws enabled="true">
                <access-key>bla</access-key>
                <secret-key>bla</secret-key>
                <region>us-west-2</region>
                <host-header>ec2.amazonaws.com</host-header>
                <security-group-name>hazelcast</security-group-name>
                <tag-key>hz-cluster</tag-key>
                <tag-value>stage</tag-value>
            </aws>
        </join>
    </network>

    <serialization>
        <portable-version>5</portable-version>
        <portable-factories>
            <portable-factory factory-id="1">
bla
            </portable-factory>
        </portable-factories>
    </serialization>
</hazelcast>
```

**Comment by jerrinot** [comment]
@dmitrymz: thanks! Can you share your map name? does it contain any special character?

**Comment by mesutcelik** [comment]
Hi @dmitrymz ,

any reply to @jerrinot on this?

**Comment by dmitrymz** [comment]
the name contains underscore

**Comment by jerrinot** [comment]
@dmitrymz you can try it with the Hazelcast v3.8-EA? It should produce a better error message. (with exception cause) thanks!

**Comment by jerrinot** [comment]
@dmitrymz: 3.8RC is out. Can you try it with this version?

**Comment by jerrinot** [comment]
moving to 3.9 as we do not have sufficient data to fix it.

**Comment by dmitrymz** [comment]
I can't try since we are on 3.6 release, and that would require me upgrade the cluster which is not a trivial task as you already know.

It would be easy for me to try on a clean hazelcast 3.8 cluster, however this issue appears when the node with enabled hazelcast jmx flag set to true joins existing cluster with existing imaps.
that is possible to do but will require a lot of extra work on my side.

so if you backport the change to v3.6 I will definitely try it.

**Comment by jerrinot** [comment]
logging was improved in 3.8. We are not planning a backport into 3.6. 
Feel free to re-open it when you have additional info. Thanks for understanding!
