### ISSUE TITLE
BasicClientReplicatedMapNearCacheTest Failures

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#9333]
**testNearCacheMemoryCostCalculation**
```
java.lang.AssertionError: The Near Cache is empty, there should be no owned entry memory costs expected:<0> but was:<81>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.internal.nearcache.AbstractBasicNearCacheTest.testNearCacheMemoryCostCalculation(AbstractBasicNearCacheTest.java:386)
	at com.hazelcast.internal.nearcache.AbstractBasicNearCacheTest.testNearCacheMemoryCostCalculation(AbstractBasicNearCacheTest.java:335)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:88)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:82)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.lang.Thread.run(Thread.java:745)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-ZuluJDK7/com.hazelcast$hazelcast-client/401/testReport/junit/com.hazelcast.client.replicatedmap.nearcache/BasicClientReplicatedMapNearCacheTest/testNearCacheMemoryCostCalculation_format_BINARY_/

**Comment by hasancelik** [comment]
**testNearCacheMemoryCostCalculation_withConcurrentCacheMisses**
```
java.lang.AssertionError: The Near Cache is empty, there should be no owned entry memory costs expected:<0> but was:<162>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.internal.nearcache.AbstractBasicNearCacheTest.testNearCacheMemoryCostCalculation(AbstractBasicNearCacheTest.java:386)
	at com.hazelcast.internal.nearcache.AbstractBasicNearCacheTest.testNearCacheMemoryCostCalculation_withConcurrentCacheMisses(AbstractBasicNearCacheTest.java:345)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:88)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:82)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.lang.Thread.run(Thread.java:662)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x/com.hazelcast$hazelcast-client/6159/testReport/junit/com.hazelcast.client.replicatedmap.nearcache/BasicClientReplicatedMapNearCacheTest/testNearCacheMemoryCostCalculation_withConcurrentCacheMisses_format_BINARY_/

**Comment by hasancelik** [comment]
**testNearCacheMemoryCostCalculation_withConcurrentCacheMisses**
```
java.lang.AssertionError: The Near Cache is empty, there should be no owned entry memory costs expected:<0> but was:<81>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.internal.nearcache.AbstractBasicNearCacheTest.testNearCacheMemoryCostCalculation(AbstractBasicNearCacheTest.java:386)
	at com.hazelcast.internal.nearcache.AbstractBasicNearCacheTest.testNearCacheMemoryCostCalculation_withConcurrentCacheMisses(AbstractBasicNearCacheTest.java:345)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:88)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:82)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
```

https://hazelcast-l337.ci.cloudbees.com/view/Sonar/job/Hazelcast-3.x-sonar/com.hazelcast$hazelcast-client/1319/testReport/junit/com.hazelcast.client.replicatedmap.nearcache/BasicClientReplicatedMapNearCacheTest/testNearCacheMemoryCostCalculation_withConcurrentCacheMisses_format_BINARY_/

**Comment by hasancelik** [comment]
**testNearCacheMemoryCostCalculation_withConcurrentCacheMisses**
```
java.lang.AssertionError: The Near Cache is empty, there should be no owned entry memory costs expected:<0> but was:<324>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.internal.nearcache.AbstractBasicNearCacheTest.testNearCacheMemoryCostCalculation(AbstractBasicNearCacheTest.java:386)
	at com.hazelcast.internal.nearcache.AbstractBasicNearCacheTest.testNearCacheMemoryCostCalculation_withConcurrentCacheMisses(AbstractBasicNearCacheTest.java:345)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:95)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:56)
	at java.lang.reflect.Method.invoke(Method.java:620)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:88)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:82)
	at java.util.concurrent.FutureTask.run(FutureTask.java:274)
	at java.lang.Thread.run(Thread.java:809)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast$hazelcast-client/1125/testReport/junit/com.hazelcast.client.replicatedmap.nearcache/BasicClientReplicatedMapNearCacheTest/testNearCacheMemoryCostCalculation_withConcurrentCacheMisses_format_BINARY_/

**Comment by hasancelik** [comment]
**testNearCacheMemoryCostCalculation_withConcurrentCacheMisses**
```
java.lang.AssertionError: The Near Cache is empty, there should be no owned entry memory costs expected:<0> but was:<81>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.internal.nearcache.AbstractBasicNearCacheTest.testNearCacheMemoryCostCalculation(AbstractBasicNearCacheTest.java:386)
	at com.hazelcast.internal.nearcache.AbstractBasicNearCacheTest.testNearCacheMemoryCostCalculation_withConcurrentCacheMisses(AbstractBasicNearCacheTest.java:345)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:622)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:88)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:82)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.lang.Thread.run(Thread.java:701)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-ZuluJDK6/com.hazelcast$hazelcast-client/426/testReport/junit/com.hazelcast.client.replicatedmap.nearcache/BasicClientReplicatedMapNearCacheTest/testNearCacheMemoryCostCalculation_withConcurrentCacheMisses_format_BINARY_/

**Comment by hasancelik** [comment]
*maintenance*
**whenCacheIsFull_thenPutOnSameKeyShouldUpdateValue_withUpdateOnDataAdapter**
```
java.lang.AssertionError: Near Cache hits should be 1, but were 0 (NearCacheStatsImpl{ownedEntryCount=500, ownedEntryMemoryCost=0, creationTime=1493122533235, hits=0, misses=2201, ratio=0.0%, evictions=0, expirations=0, lastPersistenceTime=0, persistenceCount=0, lastPersistenceDuration=0, lastPersistenceWrittenBytes=0, lastPersistenceKeyCount=0, lastPersistenceFailure=''}) expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils.assertEqualsFormat(NearCacheTestUtils.java:170)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils.assertNearCacheStats(NearCacheTestUtils.java:159)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils.assertNearCacheStats(NearCacheTestUtils.java:139)
	at com.hazelcast.internal.nearcache.AbstractBasicNearCacheTest$1.run(AbstractBasicNearCacheTest.java:183)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:988)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1005)
	at com.hazelcast.internal.nearcache.AbstractBasicNearCacheTest.whenCacheIsFull_thenPutOnSameKeyShouldUpdateValue_withUpdateOnDataAdapter(AbstractBasicNearCacheTest.java:174)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:95)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:56)
	at java.lang.reflect.Method.invoke(Method.java:620)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask.run(FutureTask.java:274)
	at java.lang.Thread.run(Thread.java:809)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-IbmJDK1.7/com.hazelcast$hazelcast-client/509/testReport/junit/com.hazelcast.client.replicatedmap.nearcache/BasicClientReplicatedMapNearCacheTest/whenCacheIsFull_thenPutOnSameKeyShouldUpdateValue_withUpdateOnDataAdapter_format_OBJECT_/

**Comment by tombujok** [comment]
@mmedenjak Are with fine with moving it to 3.8.3?

**Comment by sancar** [comment]
fixed by https://github.com/hazelcast/hazelcast/pull/10528
