### ISSUE TITLE
ExceptionInInitializerError with Hazelcast 3.7.1 on WebSphere 7 with IBM JVM 6

### ISSUE THREAD

**Issue by mathias-schulze-abit** [hazelcast/hazelcast#9400]
We've upgraded Hazelcast from 3.4.4 to 3.7.1 (includes an update of Log4J to 1.2.17) some month ago to resolve memory issues. Most of our installations are running on Tomcats with Oracle JVMs in various versions. Now we are trying to install this version of our software on WebSphere 7 with an IBM JVM Version 6. Now we're getting this error and a google search didn't helped us.

java.lang.ExceptionInInitializerError
	at java.lang.J9VMInternals.initialize(J9VMInternals.java:222)
	at com.hazelcast.internal.memory.GlobalMemoryAccessorRegistry.<clinit>(GlobalMemoryAccessorRegistry.java:63)
	at java.lang.J9VMInternals.initializeImpl(Native Method)
	at java.lang.J9VMInternals.initialize(J9VMInternals.java:200)
	at com.hazelcast.internal.util.counters.SwCounter.newSwCounter(SwCounter.java:67)
	at com.hazelcast.internal.util.counters.SwCounter.newSwCounter(SwCounter.java:57)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor.<init>(InvocationMonitor.java:88)
	at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.<init>(OperationServiceImpl.java:151)
	at com.hazelcast.spi.impl.NodeEngineImpl.<init>(NodeEngineImpl.java:126)
	at com.hazelcast.instance.Node.<init>(Node.java:184)
	at com.hazelcast.instance.HazelcastInstanceImpl.createNode(HazelcastInstanceImpl.java:155)
	at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:126)
	at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:218)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:176)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:126)
	at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:58)
	at net.abit.base.cluster.ClusterSupport.initCluster(ClusterSupport.java:386)
	at net.abit.view.start.unabhaenig.pagesupport.initAbit._init(initAbit.java:612)
	at net.abit.view.start.unabhaenig.pagesupport.initAbit.<init>(initAbit.java:137)
	at net.abit.view.start.unabhaenig.pagesupport.initAbitRunnable.run(initAbitRunnable.java:41)
	at java.lang.Thread.run(Thread.java:735)
Caused by: java.lang.NullPointerException
	at com.hazelcast.internal.memory.impl.AlignmentUtil.<clinit>(AlignmentUtil.java:24)
	at java.lang.J9VMInternals.initializeImpl(Native Method)
	at java.lang.J9VMInternals.initialize(J9VMInternals.java:200)
	... 20 more

**Comment by vbekiaris** [comment]
Thanks for reporting this issue. It should be fixed by https://github.com/hazelcast/hazelcast/pull/9131 which will be included in upcoming patch version `3.7.4`.
