### ISSUE TITLE
CloudyUtility: WARNING: Connection reset

### ISSUE THREAD

**Issue by dmitrymz** [hazelcast/hazelcast#9404]
rarely occurring exception.
should we worry about it or ignore?
using v3.6.5 on EC2

```
com.hazelcast.aws.utility.CloudyUtility
WARNING: Connection reset
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:209)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.readV3Record(InputRecord.java:593)
	at sun.security.ssl.InputRecord.read(InputRecord.java:532)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:930)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at sun.net.www.http.ChunkedInputStream.fastRead(ChunkedInputStream.java:244)
	at sun.net.www.http.ChunkedInputStream.read(ChunkedInputStream.java:689)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3336)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager$RewindableInputStream.read(XMLEntityManager.java:2928)
	at com.sun.org.apache.xerces.internal.impl.io.UTF8Reader.read(UTF8Reader.java:302)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.load(XMLEntityScanner.java:1896)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.skipChar(XMLEntityScanner.java:1551)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2818)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:118)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:504)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:243)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
	at com.hazelcast.aws.utility.CloudyUtility.unmarshalTheResponse(CloudyUtility.java:52)
	at com.hazelcast.aws.impl.DescribeInstances.execute(DescribeInstances.java:145)
	at com.hazelcast.aws.AWSClient.getPrivateIpAddresses(AWSClient.java:53)
	at com.hazelcast.cluster.impl.TcpIpJoinerOverAWS.getMembers(TcpIpJoinerOverAWS.java:42)
	at com.hazelcast.cluster.impl.TcpIpJoiner.getPossibleAddresses(TcpIpJoiner.java:399)
	at com.hazelcast.cluster.impl.TcpIpJoiner.searchForOtherClusters(TcpIpJoiner.java:501)
	at com.hazelcast.cluster.impl.SplitBrainHandler.searchForOtherClusters(SplitBrainHandler.java:75)
	at com.hazelcast.cluster.impl.SplitBrainHandler.run(SplitBrainHandler.java:42)
	at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)

```

config
```

<hazelcast xsi:schemaLocation="http://www.hazelcast.com/schema/config
    http://www.hazelcast.com/schema/config/hazelcast-config-3.5.xsd"
           xmlns="http://www.hazelcast.com/schema/config"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <properties>
        <property name="hazelcast.logging.type">slf4j</property>
        <property name="hazelcast.icmp.enabled">true</property>
    </properties>

    <network>
        <port auto-increment="false">5701</port>
        <join>
            <multicast enabled="false"/>
            <tcp-ip enabled="false"/>
            <aws enabled="true">
                <access-key>bla</access-key>
                <secret-key>bla</secret-key>
                <region>us-west-2</region>
                <host-header>ec2.amazonaws.com</host-header>
                <security-group-name>hazelcast</security-group-name>
                <tag-key>hz-cluster</tag-key>
                <tag-value>stage</tag-value>
            </aws>
        </join>
    </network>

    <serialization>
        <portable-version>5</portable-version>
        <portable-factories>
            <portable-factory factory-id="1">
bla
            </portable-factory>
        </portable-factories>
    </serialization>
</hazelcast>

```

**Comment by dmitrymz** [comment]
config
```

<hazelcast xsi:schemaLocation="http://www.hazelcast.com/schema/config
    http://www.hazelcast.com/schema/config/hazelcast-config-3.5.xsd"
           xmlns="http://www.hazelcast.com/schema/config"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <properties>
        <property name="hazelcast.logging.type">slf4j</property>
        <property name="hazelcast.icmp.enabled">true</property>
    </properties>

    <network>
        <port auto-increment="false">5701</port>
        <join>
            <multicast enabled="false"/>
            <tcp-ip enabled="false"/>
            <aws enabled="true">
                <access-key>bla</access-key>
                <secret-key>bla</secret-key>
                <region>us-west-2</region>
                <host-header>ec2.amazonaws.com</host-header>
                <security-group-name>hazelcast</security-group-name>
                <tag-key>hz-cluster</tag-key>
                <tag-value>stage</tag-value>
            </aws>
        </join>
    </network>

    <serialization>
        <portable-version>5</portable-version>
        <portable-factories>
            <portable-factory factory-id="1">
bla
            </portable-factory>
        </portable-factories>
    </serialization>
</hazelcast>

```

**Comment by emre-aydin** [comment]
Hi @dmitrymz 
As long as your Hazelcast instances can find each other on AWS, there's nothing to worry about - you can ignore this error. 

Hazelcast AWS discovery makes a `DescribeInstances` query request to EC2 Rest API  endpoint for finding out other Hazelcast instances. Response is in XML format and contains an XSD schema. For validating the response, XML parser fetches the XSD schema URL and it occasionally fails to reach the endpoint.

Closing the issue. Feel free to reopen if this doesn't answer your question.
