### ISSUE TITLE
MigrationAwareServiceEventTest.partitionIsMigratingFlag_shouldBeSet_until_serviceCommitRollback_isCompleted

### ISSUE THREAD

**Issue by mdogan** [hazelcast/hazelcast#9436]
```
java.lang.AssertionError: Unexpected responses: [true]
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.internal.partition.MigrationAwareServiceEventTest.partitionIsMigratingFlag_shouldBeSet_until_serviceCommitRollback_isCompleted(MigrationAwareServiceEventTest.java:109)
```

https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/6234/testReport/junit/com.hazelcast.internal.partition/MigrationAwareServiceEventTest/partitionIsMigratingFlag_shouldBeSet_until_serviceCommitRollback_isCompleted/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: 
Expected: an empty collection
     but: <[Response: true, Event: PartitionMigrationEvent{migrationEndpoint=DESTINATION, partitionId=46, currentReplicaIndex=1, newReplicaIndex=0}, Type: COMMIT]>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at com.hazelcast.internal.partition.MigrationAwareServiceEventTest.partitionIsMigratingFlag_shouldBeSet_until_serviceCommitRollback_isCompleted(MigrationAwareServiceEventTest.java:109)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-ZuluJDK8/com.hazelcast$hazelcast/423/testReport/junit/com.hazelcast.internal.partition/MigrationAwareServiceEventTest/partitionIsMigratingFlag_shouldBeSet_until_serviceCommitRollback_isCompleted/
