### ISSUE TITLE
InvalidationMemberAddRemoveTest.ensure_nearCached_and_actual_data_sync_eventually

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#9490]
```
java.lang.IllegalThreadStateException: null
	at java.lang.Thread.start(Thread.java:705)
	at com.hazelcast.map.impl.nearcache.invalidation.InvalidationMemberAddRemoveTest.ensure_nearCached_and_actual_data_sync_eventually(InvalidationMemberAddRemoveTest.java:156)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/1174/testReport/junit/com.hazelcast.map.impl.nearcache.invalidation/InvalidationMemberAddRemoveTest/ensure_nearCached_and_actual_data_sync_eventually/

**Comment by hasancelik** [comment]
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:315)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:153)
	at com.hazelcast.map.impl.proxy.MapProxySupport.invokeOperation(MapProxySupport.java:371)
	at com.hazelcast.map.impl.proxy.MapProxySupport.getInternal(MapProxySupport.java:302)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.get(MapProxyImpl.java:114)
	at com.hazelcast.map.impl.nearcache.invalidation.InvalidationMemberAddRemoveTest$5.run(InvalidationMemberAddRemoveTest.java:164)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:967)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:984)
	at com.hazelcast.map.impl.nearcache.invalidation.InvalidationMemberAddRemoveTest.ensure_nearCached_and_actual_data_sync_eventually(InvalidationMemberAddRemoveTest.java:160)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/1210/testReport/junit/com.hazelcast.map.impl.nearcache.invalidation/InvalidationMemberAddRemoveTest/ensure_nearCached_and_actual_data_sync_eventually/

**Comment by jerrinot** [comment]
possible related to https://github.com/hazelcast/hazelcast/issues/9735
