### ISSUE TITLE
RestTest.testListNodes & testListNodesWithWrongCredentials

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#9499]
**testListNodes**
```
org.junit.ComparisonFailure: expected:<{"status":"success"[ ]"response":"[Member ...> but was:<{"status":"success"[,]"response":"[Member ...>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.internal.ascii.RestTest.testListNodes(RestTest.java:259)
```
**testListNodesWithWrongCredentials**
```
org.junit.ComparisonFailure: expected:<..."status":"forbidden"[ "response":"null"]}> but was:<..."status":"forbidden"[]}>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.internal.ascii.RestTest.testListNodesWithWrongCredentials(RestTest.java:267)
```
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/1172/

**Comment by hasancelik** [comment]
fixed via https://github.com/hazelcast/hazelcast/commit/4129482de63bc974f46700caa8d99e0aa8b07e5f
