### ISSUE TITLE
3.8_SNAPSHOT  lock  java.lang.NullPointerException

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#9562]
Running this test 
https://github.com/Danny-Hazelcast/hzCmd-bench/tree/zeta/lab/hz/stable/create-use-destroy

2 member 400 clients on the lab

Data logs config ect.
http://54.87.52.100/~jenkins/workspace/temp/lock-null/hz/stable/create-use-destroy/
http://54.87.52.100/~jenkins/workspace/temp/lock-null/hz/stable/create-use-destroy/output/HZ/HzClient215HZ/exception.txt

http://54.87.52.100/~jenkins/workspace/temp/lock-null/hz/stable/create-use-destroy/gc.html

```
java.lang.NullPointerException
	at com.hazelcast.concurrent.lock.LockResourceImpl.canAcquireLock(LockResourceImpl.java:166)
	at com.hazelcast.concurrent.lock.LockStoreImpl.canAcquireLock(LockStoreImpl.java:159)
	at com.hazelcast.concurrent.lock.operations.LockOperation.shouldWait(LockOperation.java:70)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.waitingNeeded(OperationRunnerImpl.java:246)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:182)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:373)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:400)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:532)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:517)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:488)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:202)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:59)
	at com.hazelcast.client.impl.protocol.task.AbstractPartitionMessageTask.processMessage(AbstractPartitionMessageTask.java:67)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:123)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:103)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:142)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:127)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:102)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:114)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run(AbstractInvocationFuture.java:243)
	at com.hazelcast.client.impl.protocol.task.AbstractPartitionMessageTask.execute(AbstractPartitionMessageTask.java:78)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.unblock(AbstractInvocationFuture.java:239)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.andThen(AbstractInvocationFuture.java:215)
	at com.hazelcast.client.impl.protocol.task.AbstractPartitionMessageTask.processMessage(AbstractPartitionMessageTask.java:69)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:123)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:103)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:142)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:127)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:102)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:74)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:31)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:155)
	at com.hazelcast.client.spi.ClientProxy.invokeOnPartition(ClientProxy.java:154)
	at com.hazelcast.client.proxy.PartitionSpecificClientProxy.invokeOnPartition(PartitionSpecificClientProxy.java:47)
	at com.hazelcast.client.proxy.ClientLockProxy.tryLock(ClientLockProxy.java:145)
	at com.hazelcast.client.proxy.ClientLockProxy.tryLock(ClientLockProxy.java:135)
	at hz.lock.CreateUseDestroy.timeStep(CreateUseDestroy.java:18)
	at remote.bench.marker.GraphiteMarker.flatOut(GraphiteMarker.java:65)
	at remote.bench.marker.GraphiteMarker.bench(GraphiteMarker.java:52)
	at remote.bench.BenchThread.call(BenchThread.java:38)
	at remote.bench.BenchThread.call(BenchThread.java:12)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by Danny-Hazelcast** [comment]
repeated exception in another run,  not rare

**Comment by mdogan** [comment]
from `LockResourceImpl` class:

```java
    boolean canAcquireLock(String caller, long threadId) {
        return lockCount == 0 || getThreadId() == threadId && getOwner().equals(caller);
    }
```
`getOwner()` returns null

**Comment by mdogan** [comment]
There's a problem in `LockServiceImpl.destroyDistributedObject()` method, it doesn't follow threading model, releases resources directly out of partition thread;

```java
    public void destroyDistributedObject(String objectId) {
        Data key = nodeEngine.getSerializationService().toData(objectId);
        for (LockStoreContainer container : containers) {
            InternalLockNamespace namespace = new InternalLockNamespace(objectId);
            LockStoreImpl lockStore = container.getOrCreateLockStore(namespace);
            lockStore.forceUnlock(key);
        }
    }
```
