### ISSUE TITLE
3.8-SANPSHOT com.hazelcast.spi.exception.TargetDisconnectedException: java.lang.NullPointerException

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#9584]
```
com.hazelcast.spi.exception.TargetDisconnectedException: java.lang.NullPointerException
	at com.hazelcast.client.spi.impl.ClientInvocationServiceSupport$CleanResourcesTask.notifyException(ClientInvocationServiceSupport.java:240)
	at com.hazelcast.client.spi.impl.ClientInvocationServiceSupport$CleanResourcesTask.run(ClientInvocationServiceSupport.java:225)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at com.hazelcast.util.executor.LoggingScheduledExecutor$LoggingDelegatingFuture.run(LoggingScheduledExecutor.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:74)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:31)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:183)
	at com.hazelcast.client.util.ClientDelegatingFuture.get(ClientDelegatingFuture.java:127)
	at com.hazelcast.client.util.ClientDelegatingFuture.get(ClientDelegatingFuture.java:113)
	at com.hazelcast.client.util.ClientDelegatingFuture.join(ClientDelegatingFuture.java:162)
	at com.hazelcast.client.proxy.ClientAtomicLongProxy.compareAndSet(ClientAtomicLongProxy.java:168)
	at hz.atomic.validate.Cas.timeStep(Cas.java:19)
	at remote.bench.marker.MetricsMarker.flatOut(MetricsMarker.java:52)
	at remote.bench.marker.MetricsMarker.bench(MetricsMarker.java:39)
	at remote.bench.BenchThread.call(BenchThread.java:38)
	at remote.bench.BenchThread.call(BenchThread.java:12)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolve(ClientInvocationFuture.java:66)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run(AbstractInvocationFuture.java:243)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
	at com.hazelcast.util.executor.LoggingScheduledExecutor$LoggingDelegatingFuture.run(LoggingScheduledExecutor.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)
Caused by: java.lang.NullPointerException
	at com.hazelcast.client.impl.protocol.task.AuthenticationBaseMessageTask.reduce(AuthenticationBaseMessageTask.java:84)
	at com.hazelcast.client.impl.protocol.task.AbstractMultiTargetMessageTask.returnResponseIfNoTargetLeft(AbstractMultiTargetMessageTask.java:63)
	at com.hazelcast.client.impl.protocol.task.AbstractMultiTargetMessageTask.access$200(AbstractMultiTargetMessageTask.java:36)
	at com.hazelcast.client.impl.protocol.task.AbstractMultiTargetMessageTask$MultiTargetCallback.notify(AbstractMultiTargetMessageTask.java:93)
	at com.hazelcast.client.impl.protocol.task.AbstractMultiTargetMessageTask$SingleTargetCallback.notify(AbstractMultiTargetMessageTask.java:112)
	at com.hazelcast.spi.impl.SimpleExecutionCallback.onFailure(SimpleExecutionCallback.java:38)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run(AbstractInvocationFuture.java:246)
	... 5 more
```

https://github.com/hazelcast/hazelcast/pull/9576

**Comment by sancar** [comment]
fixed via https://github.com/hazelcast/hazelcast/pull/9585
