### ISSUE TITLE
3.8 CreateUseDestroy test hangs 

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#9586]
after this issue was fixed https://github.com/hazelcast/hazelcast/issues/9562  found by the same test.  I see the test hangs.

at
```
cat output/HZ/HzMember2HZ/timeout_stack.txt | grep timeStep
	at hz.executor.regular.CreateUseDestroy.timeStep(CreateUseDestroy.java:25)
	at hz.semaphore.CreateUseDestroy.timeStep(CreateUseDestroy.java:13)
[andrejs@Server1 create-use-destroy]$ cat output/HZ/HzMember1HZ/timeout_stack.txt | grep timeStep
	at hz.executor.regular.CreateUseDestroy.timeStep(CreateUseDestroy.java:25)
	at hz.semaphore.CreateUseDestroy.timeStep(CreateUseDestroy.java:13)
[andrejs@Server1 create-use-destroy]$ cat output/HZ/HzClient1HZ/timeout_stack.txt | grep timeStep
	at hz.executor.regular.CreateUseDestroy.timeStep(CreateUseDestroy.java:25)
	at hz.semaphore.CreateUseDestroy.timeStep(CreateUseDestroy.java:13)
[andrejs@Server1 create-use-destroy]$ cat output/HZ/HzClient2HZ/timeout_stack.txt | grep timeStep
	at hz.semaphore.CreateUseDestroy.timeStep(CreateUseDestroy.java:13)
```

https://github.com/Danny-Hazelcast/hzCmd-bench/blob/zeta/src/main/java/hz/executor/regular/CreateUseDestroy.java#L25

https://github.com/Danny-Hazelcast/hzCmd-bench/blob/bdee87fd90946e4a6d711f59d6604c6f799b7364/src/main/java/hz/semaphore/CreateUseDestroy.java#L13

Gc looks ok
http://54.87.52.100/~jenkins/workspace/temp/create-use-destroy-hang/gc.html

perf charts for all the types of create use destroy tests running
http://54.87.52.100/~jenkins/workspace/temp/create-use-destroy-hang/output/

map create use destroy through put.
http://54.87.52.100/~jenkins/workspace/temp/create-use-destroy-hang/output/HZ_3.8-SNAPSHOT_createUseDestroy_mapBak1_hz.map.CreateUseDestroy_1-bench.csv-charts/HZ_3.8-SNAPSHOT_createUseDestroy_mapBak1_hz.map.CreateUseDestroy_1-bench.csv-ops-perSec-1min-rate.png

hanging semaphore test through put
http://54.87.52.100/~jenkins/workspace/temp/create-use-destroy-hang/output/HZ_3.8-SNAPSHOT_createUseDestroy_semaphore_hz.semaphore.CreateUseDestroy_1-bench.csv-charts/HZ_3.8-SNAPSHOT_createUseDestroy_semaphore_hz.semaphore.CreateUseDestroy_1-bench.csv-ops-perSec-1min-rate.png

hanging regular executor test
http://54.87.52.100/~jenkins/workspace/temp/create-use-destroy-hang/output/HZ_3.8-SNAPSHOT_createUseDestroy_executor_hz.executor.regular.CreateUseDestroy_1-bench.csv-charts/HZ_3.8-SNAPSHOT_createUseDestroy_executor_hz.executor.regular.CreateUseDestroy_1-bench.csv-ops-perSec-1min-rate.png

JStack traces, taken 2 mins after the run was scheduled to end
http://54.87.52.100/~jenkins/workspace/temp/create-use-destroy-hang/output/HZ/HzMember1HZ/timeout_stack.txt
http://54.87.52.100/~jenkins/workspace/temp/create-use-destroy-hang/output/HZ/HzMember2HZ/timeout_stack.txt

http://54.87.52.100/~jenkins/workspace/temp/create-use-destroy-hang/output/HZ/HzClient1HZ/timeout_stack.txt
http://54.87.52.100/~jenkins/workspace/temp/create-use-destroy-hang/output/HZ/HzClient2HZ/timeout_stack.txt

find . -name *stack* | xargs grep 'hazelcast' | sort | uniq -c
```
      1 ./output/HZ/HzClient1HZ/timeout_stack.txt:	at com.hazelcast.client.proxy.ClientSemaphoreProxy.acquire(ClientSemaphoreProxy.java:53)
      1 ./output/HZ/HzClient1HZ/timeout_stack.txt:	at com.hazelcast.client.proxy.PartitionSpecificClientProxy.invokeOnPartition(PartitionSpecificClientProxy.java:47)
      1 ./output/HZ/HzClient1HZ/timeout_stack.txt:	at com.hazelcast.client.spi.ClientProxy.invokeOnPartition(ClientProxy.java:154)
      1 ./output/HZ/HzClient1HZ/timeout_stack.txt:	at com.hazelcast.client.spi.impl.ClientInvocationServiceSupport$ResponseThread.doRun(ClientInvocationServiceSupport.java:310)
      1 ./output/HZ/HzClient1HZ/timeout_stack.txt:	at com.hazelcast.client.spi.impl.ClientInvocationServiceSupport$ResponseThread.run(ClientInvocationServiceSupport.java:298)
      1 ./output/HZ/HzClient1HZ/timeout_stack.txt:	at com.hazelcast.client.util.ClientDelegatingFuture.get(ClientDelegatingFuture.java:113)
      1 ./output/HZ/HzClient1HZ/timeout_stack.txt:	at com.hazelcast.client.util.ClientDelegatingFuture.get(ClientDelegatingFuture.java:127)
      2 ./output/HZ/HzClient1HZ/timeout_stack.txt:	at com.hazelcast.internal.networking.nonblocking.NonBlockingIOThread.run(NonBlockingIOThread.java:206)
      2 ./output/HZ/HzClient1HZ/timeout_stack.txt:	at com.hazelcast.internal.networking.nonblocking.NonBlockingIOThread.selectLoop(NonBlockingIOThread.java:251)
      1 ./output/HZ/HzClient1HZ/timeout_stack.txt:	at com.hazelcast.internal.util.concurrent.MPSCQueue.take(MPSCQueue.java:153)
      1 ./output/HZ/HzClient1HZ/timeout_stack.txt:	at com.hazelcast.internal.util.concurrent.MPSCQueue.takeAll(MPSCQueue.java:231)
      1 ./output/HZ/HzClient1HZ/timeout_stack.txt:	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:153)
      1 ./output/HZ/HzClient1HZ/timeout_stack.txt:	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:179)
      5 ./output/HZ/HzClient1HZ/timeout_stack.txt:	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
      5 ./output/HZ/HzClient1HZ/timeout_stack.txt:	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)
      5 ./output/HZ/HzClient1HZ/timeout_stack.txt:	at com.hazelcast.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:203)
      1 ./output/HZ/HzClient2HZ/timeout_stack.txt:	at com.hazelcast.client.proxy.ClientSemaphoreProxy.acquire(ClientSemaphoreProxy.java:53)
      1 ./output/HZ/HzClient2HZ/timeout_stack.txt:	at com.hazelcast.client.proxy.PartitionSpecificClientProxy.invokeOnPartition(PartitionSpecificClientProxy.java:47)
      1 ./output/HZ/HzClient2HZ/timeout_stack.txt:	at com.hazelcast.client.spi.ClientProxy.invokeOnPartition(ClientProxy.java:154)
      1 ./output/HZ/HzClient2HZ/timeout_stack.txt:	at com.hazelcast.client.spi.impl.ClientInvocationServiceSupport$ResponseThread.doRun(ClientInvocationServiceSupport.java:310)
      1 ./output/HZ/HzClient2HZ/timeout_stack.txt:	at com.hazelcast.client.spi.impl.ClientInvocationServiceSupport$ResponseThread.run(ClientInvocationServiceSupport.java:298)
      2 ./output/HZ/HzClient2HZ/timeout_stack.txt:	at com.hazelcast.internal.networking.nonblocking.NonBlockingIOThread.run(NonBlockingIOThread.java:206)
      2 ./output/HZ/HzClient2HZ/timeout_stack.txt:	at com.hazelcast.internal.networking.nonblocking.NonBlockingIOThread.selectLoop(NonBlockingIOThread.java:251)
      1 ./output/HZ/HzClient2HZ/timeout_stack.txt:	at com.hazelcast.internal.util.concurrent.MPSCQueue.take(MPSCQueue.java:153)
      1 ./output/HZ/HzClient2HZ/timeout_stack.txt:	at com.hazelcast.internal.util.concurrent.MPSCQueue.takeAll(MPSCQueue.java:231)
      1 ./output/HZ/HzClient2HZ/timeout_stack.txt:	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:153)
      5 ./output/HZ/HzClient2HZ/timeout_stack.txt:	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
      5 ./output/HZ/HzClient2HZ/timeout_stack.txt:	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)
      5 ./output/HZ/HzClient2HZ/timeout_stack.txt:	at com.hazelcast.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:203)
      1 ./output/HZ/HzMember1HZ/timeout_stack.txt:	at com.hazelcast.concurrent.semaphore.SemaphoreProxy.acquire(SemaphoreProxy.java:65)
      1 ./output/HZ/HzMember1HZ/timeout_stack.txt:	at com.hazelcast.concurrent.semaphore.SemaphoreProxy.acquire(SemaphoreProxy.java:76)
      1 ./output/HZ/HzMember1HZ/timeout_stack.txt:	at com.hazelcast.internal.diagnostics.HealthMonitor$HealthMonitorThread.run(HealthMonitor.java:149)
      6 ./output/HZ/HzMember1HZ/timeout_stack.txt:	at com.hazelcast.internal.networking.nonblocking.NonBlockingIOThread.run(NonBlockingIOThread.java:206)
      6 ./output/HZ/HzMember1HZ/timeout_stack.txt:	at com.hazelcast.internal.networking.nonblocking.NonBlockingIOThread.selectLoop(NonBlockingIOThread.java:251)
      1 ./output/HZ/HzMember1HZ/timeout_stack.txt:	at com.hazelcast.internal.networking.nonblocking.iobalancer.IOBalancerThread.run(IOBalancerThread.java:53)
      1 ./output/HZ/HzMember1HZ/timeout_stack.txt:	at com.hazelcast.internal.partition.impl.MigrationQueue.poll(MigrationQueue.java:48)
      1 ./output/HZ/HzMember1HZ/timeout_stack.txt:	at com.hazelcast.internal.partition.impl.MigrationThread.doRun(MigrationThread.java:78)
      1 ./output/HZ/HzMember1HZ/timeout_stack.txt:	at com.hazelcast.internal.partition.impl.MigrationThread.run(MigrationThread.java:59)
     41 ./output/HZ/HzMember1HZ/timeout_stack.txt:	at com.hazelcast.internal.util.concurrent.MPSCQueue.take(MPSCQueue.java:153)
     41 ./output/HZ/HzMember1HZ/timeout_stack.txt:	at com.hazelcast.internal.util.concurrent.MPSCQueue.takeAll(MPSCQueue.java:231)
      1 ./output/HZ/HzMember1HZ/timeout_stack.txt:	at com.hazelcast.memory.SimpleGarbageCollector.run(SimpleGarbageCollector.java:39)
      1 ./output/HZ/HzMember1HZ/timeout_stack.txt:	at com.hazelcast.nio.tcp.SocketAcceptorThread.acceptLoop(SocketAcceptorThread.java:118)
      1 ./output/HZ/HzMember1HZ/timeout_stack.txt:	at com.hazelcast.nio.tcp.SocketAcceptorThread.run(SocketAcceptorThread.java:104)
      2 ./output/HZ/HzMember1HZ/timeout_stack.txt:	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:153)
      1 ./output/HZ/HzMember1HZ/timeout_stack.txt:	at com.hazelcast.spi.impl.operationexecutor.impl.DefaultOperationQueue.take(DefaultOperationQueue.java:76)
     60 ./output/HZ/HzMember1HZ/timeout_stack.txt:	at com.hazelcast.spi.impl.operationexecutor.impl.DefaultOperationQueue.take(DefaultOperationQueue.java:85)
     61 ./output/HZ/HzMember1HZ/timeout_stack.txt:	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:97)
      1 ./output/HZ/HzMember1HZ/timeout_stack.txt:	at com.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationDetector$DetectorThread.run(SlowOperationDetector.java:154)
      1 ./output/HZ/HzMember1HZ/timeout_stack.txt:	at com.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationDetector$DetectorThread.sleepInterval(SlowOperationDetector.java:290)
      1 ./output/HZ/HzMember1HZ/timeout_stack.txt:	at com.hazelcast.spi.impl.operationparker.impl.OperationParkerImpl$ExpirationTask.doRun(OperationParkerImpl.java:338)
      1 ./output/HZ/HzMember1HZ/timeout_stack.txt:	at com.hazelcast.spi.impl.operationparker.impl.OperationParkerImpl$ExpirationTask.run(OperationParkerImpl.java:323)
      1 ./output/HZ/HzMember1HZ/timeout_stack.txt:	at com.hazelcast.spi.impl.operationservice.impl.AsyncInboundResponseHandler$ResponseThread.doRun(AsyncInboundResponseHandler.java:150)
      1 ./output/HZ/HzMember1HZ/timeout_stack.txt:	at com.hazelcast.spi.impl.operationservice.impl.AsyncInboundResponseHandler$ResponseThread.run(AsyncInboundResponseHandler.java:139)
      1 ./output/HZ/HzMember1HZ/timeout_stack.txt:	at com.hazelcast.util.executor.DelegatingFuture.get(DelegatingFuture.java:83)
      8 ./output/HZ/HzMember1HZ/timeout_stack.txt:	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
      8 ./output/HZ/HzMember1HZ/timeout_stack.txt:	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)
      5 ./output/HZ/HzMember1HZ/timeout_stack.txt:	at com.hazelcast.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:203)
      1 ./output/HZ/HzMember2HZ/timeout_stack.txt:	at com.hazelcast.concurrent.semaphore.SemaphoreProxy.acquire(SemaphoreProxy.java:65)
      1 ./output/HZ/HzMember2HZ/timeout_stack.txt:	at com.hazelcast.concurrent.semaphore.SemaphoreProxy.acquire(SemaphoreProxy.java:76)
      1 ./output/HZ/HzMember2HZ/timeout_stack.txt:	at com.hazelcast.internal.diagnostics.HealthMonitor$HealthMonitorThread.run(HealthMonitor.java:149)
      6 ./output/HZ/HzMember2HZ/timeout_stack.txt:	at com.hazelcast.internal.networking.nonblocking.NonBlockingIOThread.run(NonBlockingIOThread.java:206)
      6 ./output/HZ/HzMember2HZ/timeout_stack.txt:	at com.hazelcast.internal.networking.nonblocking.NonBlockingIOThread.selectLoop(NonBlockingIOThread.java:251)
      1 ./output/HZ/HzMember2HZ/timeout_stack.txt:	at com.hazelcast.internal.networking.nonblocking.iobalancer.IOBalancerThread.run(IOBalancerThread.java:53)
      1 ./output/HZ/HzMember2HZ/timeout_stack.txt:	at com.hazelcast.internal.partition.impl.MigrationQueue.poll(MigrationQueue.java:48)
      1 ./output/HZ/HzMember2HZ/timeout_stack.txt:	at com.hazelcast.internal.partition.impl.MigrationThread.doRun(MigrationThread.java:78)
      1 ./output/HZ/HzMember2HZ/timeout_stack.txt:	at com.hazelcast.internal.partition.impl.MigrationThread.run(MigrationThread.java:59)
     41 ./output/HZ/HzMember2HZ/timeout_stack.txt:	at com.hazelcast.internal.util.concurrent.MPSCQueue.take(MPSCQueue.java:153)
     41 ./output/HZ/HzMember2HZ/timeout_stack.txt:	at com.hazelcast.internal.util.concurrent.MPSCQueue.takeAll(MPSCQueue.java:231)
      1 ./output/HZ/HzMember2HZ/timeout_stack.txt:	at com.hazelcast.memory.SimpleGarbageCollector.run(SimpleGarbageCollector.java:39)
      1 ./output/HZ/HzMember2HZ/timeout_stack.txt:	at com.hazelcast.nio.tcp.SocketAcceptorThread.acceptLoop(SocketAcceptorThread.java:118)
      1 ./output/HZ/HzMember2HZ/timeout_stack.txt:	at com.hazelcast.nio.tcp.SocketAcceptorThread.run(SocketAcceptorThread.java:104)
      2 ./output/HZ/HzMember2HZ/timeout_stack.txt:	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:153)
      1 ./output/HZ/HzMember2HZ/timeout_stack.txt:	at com.hazelcast.spi.impl.operationexecutor.impl.DefaultOperationQueue.take(DefaultOperationQueue.java:76)
     60 ./output/HZ/HzMember2HZ/timeout_stack.txt:	at com.hazelcast.spi.impl.operationexecutor.impl.DefaultOperationQueue.take(DefaultOperationQueue.java:85)
     61 ./output/HZ/HzMember2HZ/timeout_stack.txt:	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:97)
      1 ./output/HZ/HzMember2HZ/timeout_stack.txt:	at com.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationDetector$DetectorThread.run(SlowOperationDetector.java:154)
      1 ./output/HZ/HzMember2HZ/timeout_stack.txt:	at com.hazelcast.spi.impl.operationexecutor.slowoperationdetector.SlowOperationDetector$DetectorThread.sleepInterval(SlowOperationDetector.java:290)
      1 ./output/HZ/HzMember2HZ/timeout_stack.txt:	at com.hazelcast.spi.impl.operationparker.impl.OperationParkerImpl$ExpirationTask.doRun(OperationParkerImpl.java:338)
      1 ./output/HZ/HzMember2HZ/timeout_stack.txt:	at com.hazelcast.spi.impl.operationparker.impl.OperationParkerImpl$ExpirationTask.run(OperationParkerImpl.java:323)
      1 ./output/HZ/HzMember2HZ/timeout_stack.txt:	at com.hazelcast.spi.impl.operationservice.impl.AsyncInboundResponseHandler$ResponseThread.doRun(AsyncInboundResponseHandler.java:150)
      1 ./output/HZ/HzMember2HZ/timeout_stack.txt:	at com.hazelcast.spi.impl.operationservice.impl.AsyncInboundResponseHandler$ResponseThread.run(AsyncInboundResponseHandler.java:139)
      1 ./output/HZ/HzMember2HZ/timeout_stack.txt:	at com.hazelcast.util.executor.DelegatingFuture.get(DelegatingFuture.java:83)
      6 ./output/HZ/HzMember2HZ/timeout_stack.txt:	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
      6 ./output/HZ/HzMember2HZ/timeout_stack.txt:	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)
      5 ./output/HZ/HzMember2HZ/timeout_stack.txt:	at com.hazelcast.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:203)
```

**Comment by Danny-Hazelcast** [comment]
hanging test used  2 members 2 clients,  all were driving the test

**Comment by Danny-Hazelcast** [comment]
diff way of look at where it hangs in the test code
```
find . -name *stack* | xargs grep 'timeStep' | sort | uniq -c
      1 ./output/HZ/HzClient1HZ/timeout_stack.txt:	at hz.executor.regular.CreateUseDestroy.timeStep(CreateUseDestroy.java:25)
      1 ./output/HZ/HzClient1HZ/timeout_stack.txt:	at hz.semaphore.CreateUseDestroy.timeStep(CreateUseDestroy.java:13)
      1 ./output/HZ/HzClient2HZ/timeout_stack.txt:	at hz.semaphore.CreateUseDestroy.timeStep(CreateUseDestroy.java:13)
      1 ./output/HZ/HzMember1HZ/timeout_stack.txt:	at hz.executor.regular.CreateUseDestroy.timeStep(CreateUseDestroy.java:25)
      1 ./output/HZ/HzMember1HZ/timeout_stack.txt:	at hz.semaphore.CreateUseDestroy.timeStep(CreateUseDestroy.java:13)
      1 ./output/HZ/HzMember2HZ/timeout_stack.txt:	at hz.executor.regular.CreateUseDestroy.timeStep(CreateUseDestroy.java:25)
      1 ./output/HZ/HzMember2HZ/timeout_stack.txt:	at hz.semaphore.CreateUseDestroy.timeStep(CreateUseDestroy.java:13)
```

**Comment by mdogan** [comment]
@Danny-Hazelcast,

Problem with semaphore test is, `ISemaphore` must be initialized before `acquire()`. Otherwise, it will be created with 0 permits and `acquire()` will not return.

```java
    /**
     * Try to initialize this ISemaphore instance with the given permit count
     *
     * @param permits the given permit count
     * @return true if initialization success
     */
    boolean init(int permits);
```

`ISemaphore.init()` can be called concurrently, only the 1st one will initialize it and other calls will return false.

**Comment by mdogan** [comment]
`IExecutorService` looks like a bug. I think I am able reproduce it easily.

**Comment by Danny-Hazelcast** [comment]
@mdogan  thanks,  ISemaphore fixed
