### ISSUE TITLE
User Object Serialization Exception

### ISSUE THREAD

**Issue by Julm** [hazelcast/hazelcast#9598]
Hi, I'm using Hazelcast 3.7.4 and getting the following exception when trying to put a POJO of mine (Document) on a distributed queue. The said object is definitely Serializable with serialVersionUID properly set. 

Could anyone help me with this? It would be really great, Thank you so much! 

com.hazelcast.nio.serialization.HazelcastSerializationException: Failed to serialize 'org.icij.datashare.text.Document'
	at com.hazelcast.internal.serialization.impl.SerializationUtil.handleSerializeException(SerializationUtil.java:73) ~[datashare-api-0.5.jar:0.5]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:143) ~[datashare-api-0.5.jar:0.5]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toData(AbstractSerializationService.java:118) ~[datashare-api-0.5.jar:0.5]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toData(AbstractSerializationService.java:106) ~[datashare-api-0.5.jar:0.5]
	at com.hazelcast.spi.impl.NodeEngineImpl.toData(NodeEngineImpl.java:302) ~[datashare-api-0.5.jar:0.5]
	at com.hazelcast.collection.impl.queue.QueueProxyImpl.offer(QueueProxyImpl.java:76) ~[datashare-api-0.5.jar:0.5]
	at com.hazelcast.collection.impl.queue.QueueProxyImpl.put(QueueProxyImpl.java:70) ~[datashare-api-0.5.jar:0.5]
	at org.icij.datashare.concurrent.queue.OutputQueue.put(OutputQueue.java:25) ~[datashare-api-0.5.jar:0.5]
	at org.icij.datashare.text.extraction.FileParsingTask.process(FileParsingTask.java:65) [datashare-api-0.5.jar:0.5]
	at org.icij.datashare.text.extraction.FileParsingTask.process(FileParsingTask.java:18) [datashare-api-0.5.jar:0.5]
	at org.icij.datashare.concurrent.task.QueueInTask.call(QueueInTask.java:52) [datashare-api-0.5.jar:0.5]
	at org.icij.datashare.concurrent.task.QueueInTask.call(QueueInTask.java:15) [datashare-api-0.5.jar:0.5]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_74]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_74]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_74]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
Caused by: java.io.NotSerializableException: sun.nio.cs.UTF_8
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184) ~[?:1.8.0_74]
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548) ~[?:1.8.0_74]
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509) ~[?:1.8.0_74]
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432) ~[?:1.8.0_74]
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178) ~[?:1.8.0_74]
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348) ~[?:1.8.0_74]
	at com.hazelcast.internal.serialization.impl.JavaDefaultSerializers$JavaSerializer.write(JavaDefaultSerializers.java:242) ~[datashare-api-0.5.jar:0.5]
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.write(StreamSerializerAdapter.java:43) ~[datashare-api-0.5.jar:0.5]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:140) ~[datashare-api-0.5.jar:0.5]
	... 14 more

**Comment by tombujok** [comment]
The exception comes from Java code.
`Caused by: java.io.NotSerializableException: sun.nio.cs.UTF_8`.
Try without this field.
