### ISSUE TITLE
CardinalityEstimatorStressTest.addBigRange_checkErrorMargin_completeWithinFourMins

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#9651]
```
org.junit.runners.model.TestTimedOutException: test timed out after 240000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:315)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:153)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.join(AbstractInvocationFuture.java:136)
	at com.hazelcast.cardinality.impl.CardinalityEstimatorProxy.add(CardinalityEstimatorProxy.java:55)
	at com.hazelcast.cardinality.CardinalityEstimatorStressTest.addBigRange_checkErrorMargin_completeWithinFourMins(CardinalityEstimatorStressTest.java:50)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/1203/testReport/junit/com.hazelcast.cardinality/CardinalityEstimatorStressTest/addBigRange_checkErrorMargin_completeWithinFourMins/

**Comment by jerrinot** [comment]
this is interesting?

```
Invocation{op=com.hazelcast.cardinality.impl.operations.AggregateOperation{serviceName='hz:impl:cardinalityEstimatorService', identityHash=1398605225, partitionId=227, replicaIndex=0, callId=-8063408, invocationTime=1484532066555 (2017-01-16 04:01:06.555), waitTimeout=-1, callTimeout=60000, name=StressTest_Estimator}, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=60000, firstInvocationTimeMs=1484532066555, firstInvocationTime='2017-01-16 04:01:06.555', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 02:00:00.000', target=[127.0.0.1]:6796, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=null}, current value: com.hazelcast.core.HazelcastInstanceNotActiveException: Hazelcast instance is not active!, offered value: Invocation::INTERRUPTED
```

why is the a negative callId ?

**Comment by jerrinot** [comment]
ok, negative `callId` is a marker saying "op not active" and it was introduced by https://github.com/jerrinot/hazelcast/commit/d1b02847913b8678c0a2b7ba31fef5040b035f44

hence I think the failure is a non-issue - simply the timeout is too short.

**Comment by hasancelik** [comment]
**CardinalityEstimatorStressTest.addBigRange_checkErrorMargin_completeWithinEightMins**
```
org.junit.runners.model.TestTimedOutException: test timed out after 480000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:315)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:153)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.join(AbstractInvocationFuture.java:136)
	at com.hazelcast.cardinality.impl.CardinalityEstimatorProxy.add(CardinalityEstimatorProxy.java:55)
	at com.hazelcast.cardinality.CardinalityEstimatorStressTest.addBigRange_checkErrorMargin_completeWithinEightMins(CardinalityEstimatorStressTest.java:54)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/1219/testReport/junit/com.hazelcast.cardinality/CardinalityEstimatorStressTest/addBigRange_checkErrorMargin_completeWithinEightMins/

**Comment by jerrinot** [comment]
It almost finished. it made 9,200,000 iterations out of 10,000,000. 
I can see the test was doing progress, it was simply too slow. the nighly build is running on Cloudbees -> we slow environment. The only remedy is to further increase the test timeout. (or decrease iteration count)
