### ISSUE TITLE
DiscoverySpiTest.testSPIAwareMemberGroupFactoryCreateMemberGroups

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#9654]
```
java.lang.NullPointerException: null
	at sun.nio.ch.Util.atBugLevel(Util.java:448)
	at sun.nio.ch.SelectorImpl.<init>(SelectorImpl.java:40)
	at sun.nio.ch.EPollSelectorImpl.<init>(EPollSelectorImpl.java:47)
	at sun.nio.ch.EPollSelectorProvider.openSelector(EPollSelectorProvider.java:18)
	at java.nio.channels.Selector.open(Selector.java:209)
	at com.hazelcast.nio.tcp.nonblocking.NonBlockingIOThread.newSelector(NonBlockingIOThread.java:119)
	at com.hazelcast.nio.tcp.nonblocking.NonBlockingIOThread.<init>(NonBlockingIOThread.java:100)
	at com.hazelcast.nio.tcp.nonblocking.NonBlockingIOThreadingModel.start(NonBlockingIOThreadingModel.java:138)
	at com.hazelcast.nio.tcp.TcpIpConnectionManager.start(TcpIpConnectionManager.java:478)
	at com.hazelcast.instance.Node.start(Node.java:344)
	at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:130)
	at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:218)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:176)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:126)
	at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:58)
	at com.hazelcast.spi.discovery.DiscoverySpiTest.testSPIAwareMemberGroupFactoryCreateMemberGroups(DiscoverySpiTest.java:284)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance/com.hazelcast$hazelcast/1563/testReport/junit/com.hazelcast.spi.discovery/DiscoverySpiTest/testSPIAwareMemberGroupFactoryCreateMemberGroups/

**Comment by mdogan** [comment]
Looks like a JDK issue: 
- https://bugs.openjdk.java.net/browse/JDK-6427854
- http://www-01.ibm.com/support/docview.wss?uid=swg1IV81797
