### ISSUE TITLE
ClientRegistrationKey userRegistrationId can not be added to member Member 3.7.5 sim run issue

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#9666]
during 3.7.5 sim runs we hit this issue. 

multi fails at
http://54.87.52.100/~jenkins/workspace/Release/3.7.5/ee/lab/

```
./ee/lab/nohup.out
ERROR 19:18:14 Failure #1 C_A7_W6 MapEntryListenerTest WORKER_EXCEPTION[com.hazelcast.core.HazelcastException: Listener ClientRegistrationKey{ userRegistrationId='6b8826a8-970b-4339-815f-43ecdf240d7c'} can not be added to member Member [10.212.40.107]:5701 - 8d3857b6-c196-4a52-947f-141c3fccf9b7]
```

```
com.hazelcast.core.HazelcastException: Listener ClientRegistrationKey{ userRegistrationId='cadfa3e4-a7b3-4ea6-9a9a-590b59f55d40'} can not be added to member Member [10.212.
40.105]:5701 - bf562e64-bfd1-449b-876c-c39653e4c1a1
	at com.hazelcast.client.spi.impl.listener.ClientSmartListenerService.register(ClientSmartListenerService.java:102)
	at com.hazelcast.client.spi.impl.listener.ClientSmartListenerService.access$000(ClientSmartListenerService.java:52)
	at com.hazelcast.client.spi.impl.listener.ClientSmartListenerService$1.call(ClientSmartListenerService.java:81)
	at com.hazelcast.client.spi.impl.listener.ClientSmartListenerService$1.call(ClientSmartListenerService.java:74)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)
Caused by: java.util.concurrent.ExecutionException: com.hazelcast.client.HazelcastClientNotActiveException: ConnectionManager is not active!!!
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrow(ClientInvocationFuture.java:84)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrow(ClientInvocationFuture.java:30)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:186)
	at com.hazelcast.client.spi.impl.listener.ClientSmartListenerService.invoke(ClientSmartListenerService.java:139)
	at com.hazelcast.client.spi.impl.listener.ClientSmartListenerService.register(ClientSmartListenerService.java:95)
	... 9 more
Caused by: com.hazelcast.client.HazelcastClientNotActiveException: ConnectionManager is not active!!!
	at com.hazelcast.client.spi.impl.ClientInvocation.notifyException(ClientInvocation.java:170)
	at com.hazelcast.client.spi.impl.ClientInvocation.invoke(ClientInvocation.java:127)
	at com.hazelcast.client.spi.impl.ClientInvocation.run(ClientInvocation.java:153)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrow(ClientInvocationFuture.java:74)
	... 13 more
Caused by: com.hazelcast.core.HazelcastException: ConnectionManager is not active!!!
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.triggerConnect(ClientConnectionManagerImpl.java:310)
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.getOrTriggerConnect(ClientConnectionManagerImpl.java:290)
	at com.hazelcast.client.spi.impl.ClientSmartInvocationServiceImpl.getOrTriggerConnect(ClientSmartInvocationServiceImpl.java:85)
	at com.hazelcast.client.spi.impl.ClientSmartInvocationServiceImpl.invokeOnTarget(ClientSmartInvocationServiceImpl.java:79)
	at com.hazelcast.client.spi.impl.ClientInvocation.invokeOnSelection(ClientInvocation.java:144)
	at com.hazelcast.client.spi.impl.ClientInvocation.invoke(ClientInvocation.java:122)
	at com.hazelcast.client.spi.impl.ClientInvocation.run(ClientInvocation.java:153)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	... 5 more
```

```
cause=com.hazelcast.core.HazelcastException: Listener ClientRegistrationKey{ userRegistrationId='6b8826a8-970b-4339-815f-43ecdf240d7c'} can not be added to member Member [10.212.
40.107]:5701 - 8d3857b6-c196-4a52-947f-141c3fccf9b7
    at com.hazelcast.client.spi.impl.listener.ClientSmartListenerService.register(ClientSmartListenerService.java:102)
    at com.hazelcast.client.spi.impl.listener.ClientSmartListenerService.access$000(ClientSmartListenerService.java:52)
    at com.hazelcast.client.spi.impl.listener.ClientSmartListenerService$1.call(ClientSmartListenerService.java:81)
    at com.hazelcast.client.spi.impl.listener.ClientSmartListenerService$1.call(ClientSmartListenerService.java:74)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
    at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
    at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)
Caused by: java.util.concurrent.TimeoutException
    at com.hazelcast.client.spi.impl.ClientInvocationFuture.newTimeoutException(ClientInvocationFuture.java:55)
    at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:197)
    at com.hazelcast.client.spi.impl.listener.ClientSmartListenerService.invoke(ClientSmartListenerService.java:139)
    at com.hazelcast.client.spi.impl.listener.ClientSmartListenerService.register(ClientSmartListenerService.java:95)
    ... 9 more
```

**Comment by Danny-Hazelcast** [comment]
@sancar hi,  so i think this issue was, worked around by  setting a higher time out on the client xml 

as the time out was used in 2 places, 

with a repeated iteration count 
and one time without 

if so then we can close this issue
