### ISSUE TITLE
3.8-SNAPSHOT NullPointerException at CachedQueryEntry [EE]

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#9715]
this run https://hazelcast-l337.ci.cloudbees.com/view/shutdown/job/shutdown-projection/60/consoleFull
on hat master failed with the NPE

may be due to changes to fix the SQL shutdown issue ?
full logs http://54.87.52.100/~jenkins/workspace/shutdown-projection/3.8-SNAPSHOT/2017_01_20-12_54_20/

this is the PR that fixed sql-shutdown issue: https://github.com/hazelcast/hazelcast/pull/9688

```
java.lang.NullPointerException
	at com.hazelcast.query.impl.CachedQueryEntry.getValue(CachedQueryEntry.java:76)
	at hz.map.projection.IdProjection.transform(IdProjection.java:12)
	at hz.map.projection.IdProjection.transform(IdProjection.java:8)
	at com.hazelcast.map.impl.query.QueryResult.getValueData(QueryResult.java:114)
	at com.hazelcast.map.impl.query.QueryResult.add(QueryResult.java:99)
	at com.hazelcast.map.impl.query.QueryResultProcessor.populateResult(QueryResultProcessor.java:40)
	at com.hazelcast.map.impl.query.QueryResultProcessor.populateResult(QueryResultProcessor.java:27)
	at com.hazelcast.map.impl.query.QueryRunner.populateTheResult(QueryRunner.java:106)
	at com.hazelcast.map.impl.query.QueryRunner.runUsingPartitionScanOnSinglePartition(QueryRunner.java:161)
	at com.hazelcast.map.impl.query.QueryPartitionOperation.run(QueryPartitionOperation.java:47)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:186)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:401)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:117)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:102)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:114)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:75)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:147)
	at com.hazelcast.client.impl.protocol.task.map.AbstractMapQueryMessageTask.collectResultsFromMissingPartitions(AbstractMapQueryMessageTask.java:227)
	at com.hazelcast.client.impl.protocol.task.map.AbstractMapQueryMessageTask.invokeOnMissingPartitions(AbstractMapQueryMessageTask.java:112)
	at com.hazelcast.client.impl.protocol.task.map.AbstractMapQueryMessageTask.call(AbstractMapQueryMessageTask.java:91)
	at com.hazelcast.client.impl.protocol.task.AbstractCallableMessageTask.processMessage(AbstractCallableMessageTask.java:35)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:123)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:103)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:74)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:31)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:155)
	at com.hazelcast.client.spi.ClientProxy.invoke(ClientProxy.java:172)
	at com.hazelcast.client.proxy.ClientMapProxy.project(ClientMapProxy.java:1385)
	at hz.map.projection.ProjectionCheck.timeStep(ProjectionCheck.java:18)
	at remote.bench.marker.MetricsMarker.flatOut(MetricsMarker.java:52)
	at remote.bench.marker.MetricsMarker.bench(MetricsMarker.java:39)
	at remote.bench.BenchThread.call(BenchThread.java:38)
	at remote.bench.BenchThread.call(BenchThread.java:12)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

Tom Bujok [6:24 PM] 
maybe there's no null-check in the built-in projections (edited)
aha, is the `IdProjection` your own projection?

Danny Conlon 
yes but it should not get any null's ?  or at leas it did not when it got the wrong results

Tom Bujok 
it looks like it somehow got a an entry with null value
is there no such entry in the map?

Jaromir Hamala 
you cannot store null values into IMap

**Comment by mdogan** [comment]
`at com.hazelcast.query.impl.CachedQueryEntry.getValue(CachedQueryEntry.java:76)` is;

```java
    public Object getValue() {
        if (valueObject == null) {
            valueObject = serializationService.toObject(valueData); // <------ HERE
        }
        return valueObject;
    }
```

So, both `valueObject` and `serializationService` are null.

**Comment by Danny-Hazelcast** [comment]
this run https://hazelcast-l337.ci.cloudbees.com/view/shutdown/job/shutdown-projection/66/consoleFull

at version INFO: hz.client_0 [HZ] [3.8-SNAPSHOT] HazelcastClient 3.8-SNAPSHOT (20170120 - e23558c, e200526) is STARTING


failed with http://54.87.52.100/~jenkins/workspace/shutdown-projection/3.8-SNAPSHOT/2017_01_27-02_09_07/output/HZ/HzClient3HZ/exception.txt

```
java.lang.NullPointerException
	at com.hazelcast.query.impl.CachedQueryEntry.getValue(CachedQueryEntry.java:76)
	at hz.map.projection.IdProjection.transform(IdProjection.java:12)
	at hz.map.projection.IdProjection.transform(IdProjection.java:8)
	at com.hazelcast.map.impl.query.QueryResult.getValueData(QueryResult.java:114)
	at com.hazelcast.map.impl.query.QueryResult.add(QueryResult.java:99)
	at com.hazelcast.map.impl.query.QueryResultProcessor.populateResult(QueryResultProcessor.java:40)
	at com.hazelcast.map.impl.query.QueryResultProcessor.populateResult(QueryResultProcessor.java:27)
	at com.hazelcast.map.impl.query.QueryRunner.populateTheResult(QueryRunner.java:106)
	at com.hazelcast.map.impl.query.QueryRunner.runUsingPartitionScanOnSinglePartition(QueryRunner.java:161)
	at com.hazelcast.map.impl.query.QueryPartitionOperation.run(QueryPartitionOperation.java:47)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:186)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:401)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:117)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:102)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:114)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:75)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:147)
	at com.hazelcast.client.impl.protocol.task.map.AbstractMapQueryMessageTask.collectResultsFromMissingPartitions(AbstractMapQueryMessageTask.java:227)
	at com.hazelcast.client.impl.protocol.task.map.AbstractMapQueryMessageTask.invokeOnMissingPartitions(AbstractMapQueryMessageTask.java:112)
	at com.hazelcast.client.impl.protocol.task.map.AbstractMapQueryMessageTask.call(AbstractMapQueryMessageTask.java:91)
	at com.hazelcast.client.impl.protocol.task.AbstractCallableMessageTask.processMessage(AbstractCallableMessageTask.java:35)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:123)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:103)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:74)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:31)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:155)
	at com.hazelcast.client.spi.ClientProxy.invoke(ClientProxy.java:172)
	at com.hazelcast.client.proxy.ClientMapProxy.project(ClientMapProxy.java:1385)
	at hz.map.projection.ProjectionCheck.timeStep(ProjectionCheck.java:18)
	at remote.bench.marker.MetricsMarker.flatOut(MetricsMarker.java:52)
	at remote.bench.marker.MetricsMarker.bench(MetricsMarker.java:39)
	at remote.bench.BenchThread.call(BenchThread.java:38)
	at remote.bench.BenchThread.call(BenchThread.java:12)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by Danny-Hazelcast** [comment]
the run the day before passed 
https://hazelcast-l337.ci.cloudbees.com/view/shutdown/job/shutdown-projection/65/console

and before 

https://hazelcast-l337.ci.cloudbees.com/view/shutdown/job/shutdown-projection/64/console

**Comment by Danny-Hazelcast** [comment]
OK but this run passed https://hazelcast-l337.ci.cloudbees.com/view/shutdown/job/shutdown-projection/67/

 ?

**Comment by Danny-Hazelcast** [comment]
ok so this run  https://hazelcast-l337.ci.cloudbees.com/view/shutdown/job/shutdown-projection/68/console

failed 

HzClient2HZ projection_mapBak1HDIdx hz.map.projection.ProjectionCheck threadId=0 java.lang.NullPointerException

http://54.87.52.100/~jenkins/workspace/shutdown-projection/3.8-SNAPSHOT/2017_01_27-10_22_40/

http://54.87.52.100/~jenkins/workspace/shutdown-projection/3.8-SNAPSHOT/2017_01_27-10_22_40/output/HZ/HzClient2HZ/exception.txt

version

INFO: hz.client_0 [HZ] [3.8-SNAPSHOT] HazelcastClient 3.8-SNAPSHOT (20170120 - e23558c, e200526) is STARTING
