### ISSUE TITLE
ClientHeartbeatTest testClientEndpointsDelaySeconds_whenHeartbeatResumed

### ISSUE THREAD

**Issue by jerrinot** [hazelcast/hazelcast#9719]
```
Error Message

expected:<2> but was:<4>
Stacktrace

java.lang.AssertionError: expected:<2> but was:<4>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.client.heartbeat.ClientHeartbeatTest$6.run(ClientHeartbeatTest.java:264)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueAllTheTime(HazelcastTestSupport.java:895)
	at com.hazelcast.client.heartbeat.ClientHeartbeatTest.testClientEndpointsDelaySeconds_whenHeartbeatResumed(ClientHeartbeatTest.java:261)
Standard Output

Finished Running Test: testInvocation_whenHeartbeatStopped in 7.244 seconds.
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-IbmJDK1.8/com.hazelcast$hazelcast-client/167/testReport/junit/com.hazelcast.client.heartbeat/ClientHeartbeatTest/testClientEndpointsDelaySeconds_whenHeartbeatResumed/

**Comment by sancar** [comment]
@jerrinot I am moving the milestone to 3.7.6 since this failure is in maintenance

**Comment by hasancelik** [comment]
@sancar failure from **master**
```
java.lang.AssertionError: expected:<2> but was:<3>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.client.heartbeat.ClientHeartbeatTest$9.run(ClientHeartbeatTest.java:321)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueAllTheTime(HazelcastTestSupport.java:951)
	at com.hazelcast.client.heartbeat.ClientHeartbeatTest.testClientEndpointsDelaySeconds_whenHeartbeatResumed(ClientHeartbeatTest.java:318)
```
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x/com.hazelcast$hazelcast-client/6386/testReport/junit/com.hazelcast.client.heartbeat/ClientHeartbeatTest/testClientEndpointsDelaySeconds_whenHeartbeatResumed/
