### ISSUE TITLE
3.8-SNAPSHOT  Verbose stack trace logged in client for maxConcurrentInvocations, reached

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#9752]
verbose stack trace and Server level warning, for a case, which is expected, and really just a msg confirming that all is working as expected.

its not really a SEVER issue, with a stack trace.  as a user has explicitly configured back pressure and the prop. so the msg is to verbose.

```
 -Dhazelcast.client.max.concurrent.invocations=100
```
also the user will have to catch the com.hazelcast.core.HazelcastOverloadException
in the user code so the user is all ready directly dealing with a com.hazelcast.core.HazelcastOverloadException making the client log msg redundant. 

```
Jan 25, 2017 7:00:53 AM com.hazelcast.client.spi.ClientExecutionService
SEVERE: hz.client_0 [HZ] [3.8-SNAPSHOT] Failed to execute LoggingDelegatingFuture{task=RepairingTask{}}
com.hazelcast.core.HazelcastOverloadException: maxConcurrentInvocations : 100 is reached
	at com.hazelcast.client.spi.impl.CallIdSequence$CallIdSequenceFailFast.next(CallIdSequence.java:69)
	at com.hazelcast.client.spi.impl.ClientInvocationServiceSupport.registerInvocation(ClientInvocationServiceSupport.java:160)
	at com.hazelcast.client.spi.impl.ClientInvocationServiceSupport.send(ClientInvocationServiceSupport.java:114)
	at com.hazelcast.client.spi.impl.ClientSmartInvocationServiceImpl.invokeOnConnection(ClientSmartInvocationServiceImpl.java:119)
	at com.hazelcast.client.spi.impl.ClientSmartInvocationServiceImpl.invokeOnTarget(ClientSmartInvocationServiceImpl.java:81)
	at com.hazelcast.client.spi.impl.ClientInvocation.invokeOnSelection(ClientInvocation.java:135)
	at com.hazelcast.client.spi.impl.ClientInvocation.invoke(ClientInvocation.java:114)
	at com.hazelcast.client.cache.impl.nearcache.invalidation.ClientCacheMetaDataFetcher.scanMembers(ClientCacheMetaDataFetcher.java:72)
	at com.hazelcast.internal.nearcache.impl.invalidation.MetaDataFetcher.fetchMetadata(MetaDataFetcher.java:62)
	at com.hazelcast.internal.nearcache.impl.invalidation.RepairingTask.runAntiEntropyIfNeeded(RepairingTask.java:147)
	at com.hazelcast.internal.nearcache.impl.invalidation.RepairingTask.run(RepairingTask.java:118)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at com.hazelcast.util.executor.LoggingScheduledExecutor$LoggingDelegatingFuture.run(LoggingScheduledExecutor.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)
```

**Comment by sancar** [comment]
@Danny-Hazelcast 
The invocation is send by `MetaDataFetcher` . And it seems like it is running on ScheduledThreadPoolExecutor. So this is a case that we can not propagate the exception to user.

Since both RepairingTask and LoggingScheduledExecutor implemented by @ahmetmircik , I would like to get his opinion about logging level ? @ahmetmircik Do you think that severity stay at SEVERE ?

**Comment by ahmetmircik** [comment]
As a fix for the logging issue, `MetaDataFetcher` can catch and log exception with a warning level instead of throwing it. But for `LoggingScheduledExecutor `, `SEVERE ` level in case of execution exceptions is fine. No need to change it.

**Comment by sancar** [comment]
I wonder if this means for every client invocation coming from an internal thread, we should catch the HazelcastOverloadException or any other exception. I think this is not really applicable. I prefer to see a SEVERE log in a situation like this. 

@Danny-Hazelcast If you have no objection, I am closing this issue without taking any action.

**Comment by Danny-Hazelcast** [comment]
i think it's over the top to log a server warning and a stack trace for an event which is explicitly configured and will happen over and over again as designed.

my logs are 100's of MB large, when i make async operations. 

and as a user am all ready handling com.hazelcast.core.HazelcastOverloadException in user code using our map.putAsync(k, v) e.c.t e.c.t

**Comment by sancar** [comment]
In user code, I would expect a backup mechanism when first HazelcastOverloadException is seen. 
That case user will not repeatedly try putAsync and will not get this exception frequently. 

If user always gets this exception, I would argue design is wrong. Behaviour should be stable at the other end, meaning never reaches max concurrent invocation count. Only in exceptional cases(an issue in the cluster causes slowdown in system), user see this log. 

For this case, @ahmetmircik already told we could catch the exception and put a warning call. But  I am trying to figure out what should we do for every other similar cases.
