### ISSUE TITLE
[query-cache] EvictionTest.testMaxSizeEvictionWorks

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#9778]
```
java.lang.AssertionError: Cache size is 101, failed to complete within 120 seconds, count left: 3
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:877)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:863)
	at com.hazelcast.map.impl.querycache.EvictionTest.testMaxSizeEvictionWorks(EvictionTest.java:59)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast$hazelcast/1167/testReport/junit/com.hazelcast.map.impl.querycache/EvictionTest/testMaxSizeEvictionWorks/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: Cache size is 101, failed to complete within 120 seconds, count left: 1
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:882)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:868)
	at com.hazelcast.map.impl.querycache.EvictionTest.testMaxSizeEvictionWorks(EvictionTest.java:75)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast$hazelcast/1226/testReport/junit/com.hazelcast.map.impl.querycache/EvictionTest/testMaxSizeEvictionWorks/

**Comment by mmedenjak** [comment]
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.8/567/

``` Cache size is 101, failed to complete within 120 seconds, count left: 6 ```

**Comment by mmedenjak** [comment]
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.8/573/

**Comment by hasancelik** [comment]
*maintenance*
```
java.lang.AssertionError: Cache size is 101, failed to complete within 120 seconds, count left: 9
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:898)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:884)
	at com.hazelcast.map.impl.querycache.EvictionTest.testMaxSizeEvictionWorks(EvictionTest.java:75)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-IbmJDK1.8/com.hazelcast$hazelcast/202/testReport/junit/com.hazelcast.map.impl.querycache/EvictionTest/testMaxSizeEvictionWorks/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: Cache size is 101, failed to complete within 120 seconds, count left: 3
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:963)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:949)
	at com.hazelcast.map.impl.querycache.EvictionTest.testMaxSizeEvictionWorks(EvictionTest.java:75)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.8/com.hazelcast$hazelcast/619/testReport/junit/com.hazelcast.map.impl.querycache/EvictionTest/testMaxSizeEvictionWorks/

**Comment by ahmetmircik** [comment]
@hasancelik has updated IbmJDK1.8 to the latest version as a fix attempt. And test is passing now.

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: Cache size is 101, failed to complete within 120 seconds, count left: 2
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:996)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:982)
	at com.hazelcast.map.impl.querycache.EvictionTest.testMaxSizeEvictionWorks(EvictionTest.java:75)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast$hazelcast/1390/testReport/junit/com.hazelcast.map.impl.querycache/EvictionTest/testMaxSizeEvictionWorks/
