### ISSUE TITLE
BackupTest.testBackupMigrationAndRecovery_singleBackup

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#9780]
```
com.hazelcast.spi.exception.TargetNotMemberException: Not Member! target: [127.0.0.1]:8359, partitionId: 0, operation: com.hazelcast.map.impl.operation.MapSizeOperation, service: hz:impl:mapService
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.initInvocationTarget(Invocation.java:237)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:512)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.access$300(Invocation.java:96)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation$InvocationRetryTask.run(Invocation.java:709)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$101(ScheduledThreadPoolExecutor.java:165)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:701)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:114)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:75)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:155)
	at com.hazelcast.spi.impl.operationservice.impl.InvokeOnPartitions.retryFailedPartitions(InvokeOnPartitions.java:143)
	at com.hazelcast.spi.impl.operationservice.impl.InvokeOnPartitions.invoke(InvokeOnPartitions.java:73)
	at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.invokeOnAllPartitions(OperationServiceImpl.java:371)
	at com.hazelcast.map.impl.proxy.MapProxySupport.size(MapProxySupport.java:628)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.size(MapProxyImpl.java:102)
	at com.hazelcast.map.BackupTest.checkMapSizes(BackupTest.java:169)
	at com.hazelcast.map.BackupTest.testBackupMigrationAndRecovery(BackupTest.java:153)
	at com.hazelcast.map.BackupTest.testBackupMigrationAndRecovery_singleBackup(BackupTest.java:118)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-ZuluJDK6/com.hazelcast$hazelcast/459/testReport/junit/com.hazelcast.map/BackupTest/testBackupMigrationAndRecovery_singleBackup/

**Comment by mdogan** [comment]
This is a known member update & remove issue. See https://github.com/hazelcast/hazelcast/issues/9486

When there are 3 members; 

```
03:00:44,048  INFO |testBackupMigrationAndRecovery_singleBackup| - [ClusterService] testBackupMigrationAndRecovery_singleBackup - [127.0.0.1]:8359[dev] [3.8-SNAPSHOT]

Members [3] {
	Member [127.0.0.1]:8359 - cc39dd6e-230c-47f1-b37f-653567f301ab this
	Member [127.0.0.1]:8360 - 166cd42a-da86-4b26-ae51-da8f288c6a5a
	Member [127.0.0.1]:8363 - b4ffcd47-c9fd-4c8a-ae13-66b298a77581
}
```

`[127.0.0.1]:8363` terminates and other two removes it;

```
03:00:45,031  INFO |testBackupMigrationAndRecovery_singleBackup| - [ClusterService] testBackupMigrationAndRecovery_singleBackup - [127.0.0.1]:8360[dev] [3.8-SNAPSHOT]

Members [2] {
	Member [127.0.0.1]:8359 - cc39dd6e-230c-47f1-b37f-653567f301ab
	Member [127.0.0.1]:8360 - 166cd42a-da86-4b26-ae51-da8f288c6a5a this
}

03:00:45,033  INFO |testBackupMigrationAndRecovery_singleBackup| - [ClusterService] testBackupMigrationAndRecovery_singleBackup - [127.0.0.1]:8359[dev] [3.8-SNAPSHOT]

Members [2] {
	Member [127.0.0.1]:8359 - cc39dd6e-230c-47f1-b37f-653567f301ab this
	Member [127.0.0.1]:8360 - 166cd42a-da86-4b26-ae51-da8f288c6a5a
}
```

After this point, `[127.0.0.1]:8360` receives a stale member update and applies it;

```
03:00:45,034  INFO |testBackupMigrationAndRecovery_singleBackup| - [ClusterService] hz._hzInstance_1797_dev.priority-generic-operation.thread-0 - [127.0.0.1]:8360[dev] [3.8-SNAPSHOT]

Members [3] {
	Member [127.0.0.1]:8359 - cc39dd6e-230c-47f1-b37f-653567f301ab
	Member [127.0.0.1]:8360 - 166cd42a-da86-4b26-ae51-da8f288c6a5a this
	Member [127.0.0.1]:8363 - b4ffcd47-c9fd-4c8a-ae13-66b298a77581
}
```

When `[127.0.0.1]:8359` terminates too; `[127.0.0.1]:8360` has the member list;

```
03:00:49,320  INFO |testBackupMigrationAndRecovery_singleBackup| - [ClusterService] testBackupMigrationAndRecovery_singleBackup - [127.0.0.1]:8360[dev] [3.8-SNAPSHOT]

Members [2] {
	Member [127.0.0.1]:8360 - 166cd42a-da86-4b26-ae51-da8f288c6a5a this
	Member [127.0.0.1]:8363 - b4ffcd47-c9fd-4c8a-ae13-66b298a77581
}
```

Since `[127.0.0.1]:8363` is already terminates, `map.size()` call fails with `TargetNotMemberException ` after many retries.
