### ISSUE TITLE
OutofMemoryError in IOBalancer

### ISSUE THREAD

**Issue by pochadri** [hazelcast/hazelcast#9787]
Here is the exception we observe in our production logs and around this time web server would not respond to any request. we are using vertx framework 3.3.3 and hazelcast 3.6.3

```
2017-01-31T07:27:15,057 ERROR com.hazelcast.nio.tcp.nonblocking.iobalancer.IOBalancer: - [10.0.0.203]:5704 [dev] [3.6.3] IOBalancer failed
java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.util.concurrent.LinkedBlockingQueue.iterator(LinkedBlockingQueue.java:775)
        at com.hazelcast.nio.tcp.nonblocking.iobalancer.LoadTracker.handleAddedOrRemovedConnections(LoadTracker.java:91)
        at com.hazelcast.nio.tcp.nonblocking.iobalancer.LoadTracker.updateImbalance(LoadTracker.java:82)
        at com.hazelcast.nio.tcp.nonblocking.iobalancer.IOBalancer.scheduleMigrationIfNeeded(IOBalancer.java:141)
        at com.hazelcast.nio.tcp.nonblocking.iobalancer.IOBalancer.checkReadHandlers(IOBalancer.java:137)
        at com.hazelcast.nio.tcp.nonblocking.iobalancer.IOBalancerThread.run(IOBalancerThread.java:51)
2017-01-31T07:27:15,058 INFO  com.hazelcast.cluster.impl.ClusterHeartbeatManager: - [10.0.0.203]:5704 [dev] [3.6.3] System clock apparently jumped from 2017-01-31T07:23:30.010 to 2017-01-31T07:26:30.373 since last heartbeat (+175363 ms)
2017-01-31T07:27:15,058 WARN  com.hazelcast.cluster.impl.ClusterHeartbeatManager: - [10.0.0.203]:5704 [dev] [3.6.3] Resetting master confirmation timestamps because of huge system clock jump! Clock-Jump: 175363 ms, Master-Confirmation-Timeout: 350000 ms
2017-01-31T07:27:15,058 WARN  com.hazelcast.cluster.impl.ClusterHeartbeatManager: - [10.0.0.203]:5704 [dev] [3.6.3] Resetting heartbeat timestamps because of huge system clock jump! Clock-Jump: 175363 ms, Heartbeat-Timeout: 300000 ms

```

**Comment by jerrinot** [comment]
hi @pochadri,

thanks for reporting this. It could be just a side-effect of a memory leak in a different place. Do you have a heapdump you could share?

**Comment by pveentjer** [comment]
Closing this one due to not receiving any update regarding the issue. Feel free to re-open.
