### ISSUE TITLE
QueryBounceTest.testQuery

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#9802]
```
org.junit.runners.model.TestTimedOutException: test timed out after 240000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
	at java.util.concurrent.FutureTask.awaitDone(FutureTask.java:425)
	at java.util.concurrent.FutureTask.get(FutureTask.java:187)
	at com.hazelcast.test.bounce.BounceMemberRule.waitForFutures(BounceMemberRule.java:374)
	at com.hazelcast.test.bounce.BounceMemberRule.testWithDuration(BounceMemberRule.java:242)
	at com.hazelcast.test.bounce.BounceMemberRule.testRepeatedly(BounceMemberRule.java:204)
	at com.hazelcast.map.QueryBounceTest.prepareAndRunQueryTasks(QueryBounceTest.java:90)
	at com.hazelcast.map.QueryBounceTest.testQuery(QueryBounceTest.java:73)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/1225/com.hazelcast$hazelcast/testReport/com.hazelcast.map/QueryBounceTest/testQuery/

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/1228/testReport/junit/com.hazelcast.map/QueryBounceTest/testQuery/

**Comment by vbekiaris** [comment]
In https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/1228/testReport/junit/com.hazelcast.map/QueryBounceTest/testQuery/ time spent during GC was ~318 seconds out of the ~8 minutes during which `testQuery` log entries appear in the output.
https://github.com/hazelcast/hazelcast/pull/9806 changes the test to use the serial runner (as was previously the case for `QueryDuringMigrationsStressTest` which is replaced by this test) and adds the `JitterRule` to monitor hiccups.
