### ISSUE TITLE
TcpIpJoinTest.test_whenHostAndInterfacesConfigured

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#9805]
```
java.lang.AssertionError: Cluster size is not correct. Expected: 2 Actual: 1
	at org.junit.Assert.fail(Assert.java:88)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSize(HazelcastTestSupport.java:756)
	at com.hazelcast.test.HazelcastTestSupport$10.run(HazelcastTestSupport.java:775)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:911)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:771)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:766)
	at com.hazelcast.cluster.AbstractJoinTest.testJoin(AbstractJoinTest.java:30)
	at com.hazelcast.cluster.TcpIpJoinTest.test_whenHostAndInterfacesConfigured(TcpIpJoinTest.java:111)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-OracleJDK1.6-freestyle/2/testReport/junit/com.hazelcast.cluster/TcpIpJoinTest/test_whenHostAndInterfacesConfigured/

**Comment by mdogan** [comment]
No logs available on jenkins and S3.

**Comment by mdogan** [comment]
No failures since February and no logs available.
