### ISSUE TITLE
No DataSerializerFactory registered for namespace: -301858816 ClientReliableTopicProxy,  client compatibility 

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#9816]
```
SEVERE: hz.client_0 [HZ] [3.7] Failed asynchronous execution of execution callback: com.hazelcast.client.util.ClientDelegatingFuture$DelegatingExecutionCallback@2d7e12edfor call Cli
entMessage{length=62, correlationId=41465, messageType=190a, partitionId=54, isComplete=true, isRetryable=false, isEvent=false, writeOffset=0}
com.hazelcast.nio.serialization.HazelcastSerializationException: No DataSerializerFactory registered for namespace: -301858816
    at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:114)
    at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:52)
    at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:46)
    at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:172)
    at com.hazelcast.ringbuffer.impl.client.PortableReadResultSet.iterator(PortableReadResultSet.java:63)
    at com.hazelcast.client.proxy.ClientReliableTopicProxy$MessageRunner.onResponse(ClientReliableTopicProxy.java:231)
    at com.hazelcast.client.proxy.ClientReliableTopicProxy$MessageRunner.onResponse(ClientReliableTopicProxy.java:197)
    at com.hazelcast.client.util.ClientDelegatingFuture$DelegatingExecutionCallback.onResponse(ClientDelegatingFuture.java:227)
    at com.hazelcast.client.util.ClientDelegatingFuture$DelegatingExecutionCallback.onResponse(ClientDelegatingFuture.java:203)
    at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run(AbstractInvocationFuture.java:251)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
    at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
    at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)
```

```
Feb 04, 2017 7:26:50 AM com.hazelcast.client.spi.ClientInvocationService
SEVERE: hz.client_0 [HZ] [3.7.5] Failed asynchronous execution of execution callback: com.hazelcast.client.util.ClientDelegatingFuture$DelegatingExecutionCallback@5d3687fbfor call C
lientMessage{length=62, correlationId=44895, messageType=190a, partitionId=54, isComplete=true, isRetryable=false, isEvent=false, writeOffset=0}
com.hazelcast.nio.serialization.HazelcastSerializationException: No DataSerializerFactory registered for namespace: -301858816
    at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.readInternal(DataSerializableSerializer.java:135)
    at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:104)
    at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:54)
    at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48)
    at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:172)
    at com.hazelcast.ringbuffer.impl.client.PortableReadResultSet.iterator(PortableReadResultSet.java:63)
    at com.hazelcast.client.proxy.ClientReliableTopicProxy$MessageRunner.onResponse(ClientReliableTopicProxy.java:231)
    at com.hazelcast.client.proxy.ClientReliableTopicProxy$MessageRunner.onResponse(ClientReliableTopicProxy.java:197)
    at com.hazelcast.client.util.ClientDelegatingFuture$DelegatingExecutionCallback.onResponse(ClientDelegatingFuture.java:227)
    at com.hazelcast.client.util.ClientDelegatingFuture$DelegatingExecutionCallback.onResponse(ClientDelegatingFuture.java:203)
    at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run(AbstractInvocationFuture.java:251)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
    at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
    at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)
```

I don't see this msg in `HazelcastClient 3.8-SNAPSHOT (20170202 - 18f52af, 4d1c2dd) is STARTED` logs

using EE jars for all versions

what kind of items are stored in the ringbuffer?
Int or byte array  cant rember just now

do you have a store configured for the ringbuffer?
```
<reliable-topic name="topic*" >
        <topic-overload-policy>BLOCK</topic-overload-policy>
        <statistics-enabled>false</statistics-enabled>
    </reliable-topic>

    <ringbuffer name="topic*">
        <time-to-live-seconds>60</time-to-live-seconds>
    </ringbuffer>
```

https://github.com/Danny-Hazelcast/hzCmd-bench/blob/zeta/src/main/java/hz/topic/Publisher.java
hzCmd-bench - bench mark implementation
 
ok so its all under https://github.com/Danny-Hazelcast/hzCmd-bench/tree/zeta/src/main/java/hz/topic

and the scripts
https://github.com/Danny-Hazelcast/hzCmd-bench/tree/zeta/lab/hz/stable/topic

**Comment by vbekiaris** [comment]
@Danny-Hazelcast do you have link to full member/client logs from this run?

**Comment by jerrinot** [comment]
fixed by https://github.com/hazelcast/hazelcast/pull/9859
