### ISSUE TITLE
exception.RetryableHazelcastException: Map cache is still loading data from external store

### ISSUE THREAD

**Issue by prabhu-nishant** [hazelcast/hazelcast#9819]
Hi Team,

I have been observing this issue over weekend process restarts. It happens intermittently. Can you tell me solution to fix this. I am using hazelcast 3.7.1.

exception.RetryableHazelcastException: Map cache is still loading data from external store
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:275)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1143)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1046)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:839)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538)
        at msjava.base.application.SpringMain.runInternal(SpringMain.java:217)
        at msjava.base.application.SpringMain.run(SpringMain.java:147)
        at msjava.base.application.SpringMain.run(SpringMain.java:134)
        at msjava.base.application.SpringMain.main(SpringMain.java:285)

**Comment by tombujok** [comment]
Could you retry with Hazelcast 3.8.1?

**Comment by borball** [comment]
@tombujok 3.8.1 will fix this issue?

**Comment by tombujok** [comment]
This is not a bug. This exception is thrown when the data is still being loaded by the MapLoader in the initial load phase. 

It basically means that your MapLoader loads data. If your DB query is slow, or the DB is overloaded, your MapLoader will take a lot of time to load all the data in loadAll and loadAllKeys methods. 

You may add some logging of progress in the loadAll or loadAllKeys methods - since it's you who provide the implementation.

3.8.1 was just a tip to check it with the newest HZ version since it adds some more logging to mapLoader in the FINEST log level.
