### ISSUE TITLE
Using session distribution with invalid hazelcast.xml should fail more explicitly

### ISSUE THREAD

**Issue by akottr** [hazelcast/hazelcast#9825]
I created the repo https://github.com/akottr/filter-based-session-replication based on the filter-based-session-replication project from the hazelcast demo project to show the issue.
The tomcat should be started with `-Dhazelcast.logging.type=slf4j` parameter

Using an invalid hazelcast.xml does show following log messages when log level info is enabled. 

hz 3.7.5
```
2017-02-07 21:46:34 [.hazelcast-wm.ensureInstance] INFO  c.h.web.ClusteredSessionService - Retrying the connection!!
2017-02-07 21:46:34 [.hazelcast-wm.ensureInstance] INFO  c.hazelcast.config.XmlConfigLocator - Loading 'hazelcast.xml' from classpath.
```

hz 3.8-SNAPSHOT
```
2017-02-07 21:29:38 [.hazelcast-wm.ensureInstance] INFO  c.h.web.ClusteredSessionService - Retrying the connection!!
2017-02-07 21:29:38 [.hazelcast-wm.ensureInstance] INFO  c.h.web.HazelcastInstanceLoader - Using existing Hazelcast instance with name [default] for session replication
2017-02-07 21:29:38 [.hazelcast-wm.ensureInstance] WARN  c.h.web.ClusteredSessionService - Cannot connect to Hazelcast server: Hazelcast instance with name [default] could not be found.
```

The problem with these messages is that they do not really show the culprit. But what makes this even worse is that the `clusterMap` is not initialized. If you ignore these 'info' messages each `session.getAttribute()` leads to a silent `NullPointerException` (catched silently in `HazelcastHttpSession.getAttribute()` if trace log is not enabled).
Creating the silent `NullPointerExceptions` including the StackTraces adds up to additional 30% CPU usage to your tomcat server (Believe me I 'tested' that).
The real culprit can only be found when trace level logging is enabled. So showing a more explicit warning or error would be helpful.

```xml
<logger name="com.hazelcast.web.ClusteredSessionService" level="trace"
        additivity="false">
    <appender-ref ref="STDOUT" />
</logger>
```

hz 3.7.5
```
com.hazelcast.config.InvalidConfigurationException: <import> element can appear only in the top level of the XML
	at com.hazelcast.config.AbstractConfigBuilder.replaceImportElementsWithActualFileContents(AbstractConfigBuilder.java:92)
```
```
java.lang.NullPointerException: null
	at com.hazelcast.web.ClusteredSessionService.executeOnKey(ClusteredSessionService.java:178)
```

hz 3.8-SNAPSHOT
```
java.lang.NullPointerException: null
	at com.hazelcast.web.ClusteredSessionService.executeOnKey(ClusteredSessionService.java:166)    
```

**Comment by emre-aydin** [comment]
Hi @akottr 

Which version of `hazelcast-wm` are you using? We've improved configuration process significantly with version 3.8 of `hazelcast-wm`. Can you please try with that and let me know if there's any problem you see with it?

**Comment by akottr** [comment]
Hi @emre-aydin 

I updated the project https://github.com/akottr/filter-based-session-replication to Version 3.8.1. And now there is a warning log messages indicating the problem. This looks great. Thank you.

```
2017-04-18 22:12:23 [.hazelcast-wm.ensureInstance] INFO  c.hazelcast.config.XmlConfigLocator - Loading 'hazelcast.xml' from classpath.
2017-04-18 22:12:23 [.hazelcast-wm.ensureInstance] WARN  c.h.web.ClusteredSessionService - Cannot connect to Hazelcast server: <import> element can appear only in the top level of the XML
```

BTW. Configuring an instance-name in the `web.xml` does not start a hazlecast instance anymore. It tries to reuse an existing instance even if none exists. This seems to be a breaking change in Version 3.8 and the code in the example app https://github.com/hazelcast/hazelcast-code-samples/tree/master/hazelcast-integration/filter-based-session-replication is not properly working anymore. I will send a pull request for this issue to the hazelcast-code-samples repo.

**Comment by emre-aydin** [comment]
You're welcome @akottr. This code sample seems to be fixed, closing the issue.
