### ISSUE TITLE
[lock] LockLeaseMemberBounceTest.leaseShouldExpireWhenMemberBouncing

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#9869]
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at org.junit.Assert.assertFalse(Assert.java:74)
	at com.hazelcast.concurrent.lock.LockLeaseMemberBounceTest$Driver.doAssert(LockLeaseMemberBounceTest.java:122)
	at com.hazelcast.concurrent.lock.LockLeaseMemberBounceTest$1.run(LockLeaseMemberBounceTest.java:80)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:967)
	at com.hazelcast.concurrent.lock.LockLeaseMemberBounceTest.leaseShouldExpireWhenMemberBouncing(LockLeaseMemberBounceTest.java:76)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/1238/testReport/junit/com.hazelcast.concurrent.lock/LockLeaseMemberBounceTest/leaseShouldExpireWhenMemberBouncing/

https://hazelcast-l337.ci.cloudbees.com/view/Sonar/job/Hazelcast-3.x-sonar/com.hazelcast$hazelcast/1403/testReport/junit/com.hazelcast.concurrent.lock/LockLeaseMemberBounceTest/leaseShouldExpireWhenMemberBouncing/

**Comment by hasancelik** [comment]
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
	at java.util.concurrent.FutureTask.awaitDone(FutureTask.java:425)
	at java.util.concurrent.FutureTask.get(FutureTask.java:187)
	at com.hazelcast.test.bounce.BounceMemberRule.waitForFutures(BounceMemberRule.java:375)
	at com.hazelcast.test.bounce.BounceMemberRule.testWithDuration(BounceMemberRule.java:239)
	at com.hazelcast.test.bounce.BounceMemberRule.testRepeatedly(BounceMemberRule.java:203)
	at com.hazelcast.concurrent.lock.LockLeaseMemberBounceTest.leaseShouldExpireWhenMemberBouncing(LockLeaseMemberBounceTest.java:68)
```
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-nightly/com.hazelcast$hazelcast/1136/testReport/junit/com.hazelcast.concurrent.lock/LockLeaseMemberBounceTest/leaseShouldExpireWhenMemberBouncing/

**Comment by hasancelik** [comment]
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
	at java.util.concurrent.FutureTask.awaitDone(FutureTask.java:425)
	at java.util.concurrent.FutureTask.get(FutureTask.java:187)
	at com.hazelcast.test.bounce.BounceMemberRule.waitForFutures(BounceMemberRule.java:375)
	at com.hazelcast.test.bounce.BounceMemberRule.testWithDuration(BounceMemberRule.java:239)
	at com.hazelcast.test.bounce.BounceMemberRule.testRepeatedly(BounceMemberRule.java:203)
	at com.hazelcast.concurrent.lock.LockLeaseMemberBounceTest.leaseShouldExpireWhenMemberBouncing(LockLeaseMemberBounceTest.java:84)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-nightly/com.hazelcast$hazelcast/1156/testReport/junit/com.hazelcast.concurrent.lock/LockLeaseMemberBounceTest/leaseShouldExpireWhenMemberBouncing/

**Comment by mmedenjak** [comment]
Moved to 3.9 since the fix is not trivial and might introduce unforeseen regressions. Once tested we can backport to 3.8.2.

**Comment by hasancelik** [comment]
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
	at java.util.concurrent.FutureTask.awaitDone(FutureTask.java:425)
	at java.util.concurrent.FutureTask.get(FutureTask.java:187)
	at com.hazelcast.test.bounce.BounceMemberRule.waitForFutures(BounceMemberRule.java:375)
	at com.hazelcast.test.bounce.BounceMemberRule.testWithDuration(BounceMemberRule.java:239)
	at com.hazelcast.test.bounce.BounceMemberRule.testRepeatedly(BounceMemberRule.java:203)
	at com.hazelcast.concurrent.lock.LockLeaseMemberBounceTest.leaseShouldExpireWhenMemberBouncing(LockLeaseMemberBounceTest.java:84)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/1292/testReport/junit/com.hazelcast.concurrent.lock/LockLeaseMemberBounceTest/leaseShouldExpireWhenMemberBouncing/

**Comment by hasancelik** [comment]
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.FutureTask.awaitDone(FutureTask.java:429)
	at java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at com.hazelcast.test.bounce.BounceMemberRule.waitForFutures(BounceMemberRule.java:375)
	at com.hazelcast.test.bounce.BounceMemberRule.testWithDuration(BounceMemberRule.java:239)
	at com.hazelcast.test.bounce.BounceMemberRule.testRepeatedly(BounceMemberRule.java:203)
	at com.hazelcast.concurrent.lock.LockLeaseMemberBounceTest.leaseShouldExpireWhenMemberBouncing(LockLeaseMemberBounceTest.java:84)
```

https://hazelcast-l337.ci.cloudbees.com/view/Sonar/job/Hazelcast-3.x-sonar/com.hazelcast$hazelcast/1455/testReport/junit/com.hazelcast.concurrent.lock/LockLeaseMemberBounceTest/leaseShouldExpireWhenMemberBouncing/

**Comment by hasancelik** [comment]
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
	at java.util.concurrent.FutureTask.awaitDone(FutureTask.java:425)
	at java.util.concurrent.FutureTask.get(FutureTask.java:187)
	at com.hazelcast.test.bounce.BounceMemberRule.waitForFutures(BounceMemberRule.java:375)
	at com.hazelcast.test.bounce.BounceMemberRule.testWithDuration(BounceMemberRule.java:239)
	at com.hazelcast.test.bounce.BounceMemberRule.testRepeatedly(BounceMemberRule.java:203)
	at com.hazelcast.concurrent.lock.LockLeaseMemberBounceTest.leaseShouldExpireWhenMemberBouncing(LockLeaseMemberBounceTest.java:84)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/1302/testReport/junit/com.hazelcast.concurrent.lock/LockLeaseMemberBounceTest/leaseShouldExpireWhenMemberBouncing/

**Comment by mmedenjak** [comment]
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/1321/#showFailuresLink

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at org.junit.Assert.assertFalse(Assert.java:74)
	at com.hazelcast.concurrent.lock.LockLeaseMemberBounceTest$Driver.doAssert(LockLeaseMemberBounceTest.java:132)
	at com.hazelcast.concurrent.lock.LockLeaseMemberBounceTest$1.run(LockLeaseMemberBounceTest.java:90)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:992)
	at com.hazelcast.concurrent.lock.LockLeaseMemberBounceTest.leaseShouldExpireWhenMemberBouncing(LockLeaseMemberBounceTest.java:86)
```

https://hazelcast-l337.ci.cloudbees.com/view/Sonar/job/Hazelcast-3.x-sonar/com.hazelcast$hazelcast/1485/testReport/junit/com.hazelcast.concurrent.lock/LockLeaseMemberBounceTest/leaseShouldExpireWhenMemberBouncing/

**Comment by mmedenjak** [comment]
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/1334/

**Comment by hasancelik** [comment]
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
	at java.util.concurrent.FutureTask.awaitDone(FutureTask.java:425)
	at java.util.concurrent.FutureTask.get(FutureTask.java:187)
	at com.hazelcast.test.bounce.BounceMemberRule.waitForFutures(BounceMemberRule.java:375)
	at com.hazelcast.test.bounce.BounceMemberRule.testWithDuration(BounceMemberRule.java:239)
	at com.hazelcast.test.bounce.BounceMemberRule.testRepeatedly(BounceMemberRule.java:203)
	at com.hazelcast.concurrent.lock.LockLeaseMemberBounceTest.leaseShouldExpireWhenMemberBouncing(LockLeaseMemberBounceTest.java:84)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-nightly/com.hazelcast$hazelcast/1216/testReport/junit/com.hazelcast.concurrent.lock/LockLeaseMemberBounceTest/leaseShouldExpireWhenMemberBouncing/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at org.junit.Assert.assertFalse(Assert.java:74)
	at com.hazelcast.concurrent.lock.LockLeaseMemberBounceTest$Driver.doAssert(LockLeaseMemberBounceTest.java:132)
	at com.hazelcast.concurrent.lock.LockLeaseMemberBounceTest$1.run(LockLeaseMemberBounceTest.java:90)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1037)
	at com.hazelcast.concurrent.lock.LockLeaseMemberBounceTest.leaseShouldExpireWhenMemberBouncing(LockLeaseMemberBounceTest.java:86)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/1343/testReport/junit/com.hazelcast.concurrent.lock/LockLeaseMemberBounceTest/leaseShouldExpireWhenMemberBouncing/

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/1338/testReport/junit/com.hazelcast.concurrent.lock/LockLeaseMemberBounceTest/leaseShouldExpireWhenMemberBouncing/

**Comment by hasancelik** [comment]
*maintenance*

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-nightly/com.hazelcast$hazelcast/1218/testReport/junit/com.hazelcast.concurrent.lock/LockLeaseMemberBounceTest/leaseShouldExpireWhenMemberBouncing/

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-nightly/com.hazelcast$hazelcast/1216/testReport/junit/com.hazelcast.concurrent.lock/LockLeaseMemberBounceTest/leaseShouldExpireWhenMemberBouncing/

**Comment by hasancelik** [comment]
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
	at java.util.concurrent.FutureTask.awaitDone(FutureTask.java:425)
	at java.util.concurrent.FutureTask.get(FutureTask.java:187)
	at com.hazelcast.test.bounce.BounceMemberRule.waitForFutures(BounceMemberRule.java:375)
	at com.hazelcast.test.bounce.BounceMemberRule.testWithDuration(BounceMemberRule.java:239)
	at com.hazelcast.test.bounce.BounceMemberRule.testRepeatedly(BounceMemberRule.java:203)
	at com.hazelcast.concurrent.lock.LockLeaseMemberBounceTest.leaseShouldExpireWhenMemberBouncing(LockLeaseMemberBounceTest.java:84)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-nightly/com.hazelcast$hazelcast/1249/testReport/junit/com.hazelcast.concurrent.lock/LockLeaseMemberBounceTest/leaseShouldExpireWhenMemberBouncing/

**Comment by hasancelik** [comment]
*master*
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at org.junit.Assert.assertFalse(Assert.java:74)
	at com.hazelcast.concurrent.lock.LockLeaseMemberBounceTest$Driver.doAssert(LockLeaseMemberBounceTest.java:132)
	at com.hazelcast.concurrent.lock.LockLeaseMemberBounceTest$1.run(LockLeaseMemberBounceTest.java:90)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1054)
	at com.hazelcast.concurrent.lock.LockLeaseMemberBounceTest.leaseShouldExpireWhenMemberBouncing(LockLeaseMemberBounceTest.java:86)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/1383/testReport/junit/com.hazelcast.concurrent.lock/LockLeaseMemberBounceTest/leaseShouldExpireWhenMemberBouncing/

**Comment by hasancelik** [comment]
*maintenance*
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at org.junit.Assert.assertFalse(Assert.java:74)
	at com.hazelcast.concurrent.lock.LockLeaseMemberBounceTest$Driver.doAssert(LockLeaseMemberBounceTest.java:132)
	at com.hazelcast.concurrent.lock.LockLeaseMemberBounceTest$1.run(LockLeaseMemberBounceTest.java:90)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:988)
	at com.hazelcast.concurrent.lock.LockLeaseMemberBounceTest.leaseShouldExpireWhenMemberBouncing(LockLeaseMemberBounceTest.java:86)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-nightly/com.hazelcast$hazelcast/1253/testReport/junit/com.hazelcast.concurrent.lock/LockLeaseMemberBounceTest/leaseShouldExpireWhenMemberBouncing/

**Comment by hasancelik** [comment]
*master*
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at org.junit.Assert.assertFalse(Assert.java:74)
	at com.hazelcast.concurrent.lock.LockLeaseMemberBounceTest$Driver.doAssert(LockLeaseMemberBounceTest.java:132)
	at com.hazelcast.concurrent.lock.LockLeaseMemberBounceTest$1.run(LockLeaseMemberBounceTest.java:90)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1064)
	at com.hazelcast.concurrent.lock.LockLeaseMemberBounceTest.leaseShouldExpireWhenMemberBouncing(LockLeaseMemberBounceTest.java:86)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/1395/testReport/junit/com.hazelcast.concurrent.lock/LockLeaseMemberBounceTest/leaseShouldExpireWhenMemberBouncing/

**Comment by hasancelik** [comment]
*maintenance*
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
	at java.util.concurrent.FutureTask.awaitDone(FutureTask.java:425)
	at java.util.concurrent.FutureTask.get(FutureTask.java:187)
	at com.hazelcast.test.bounce.BounceMemberRule.waitForFutures(BounceMemberRule.java:375)
	at com.hazelcast.test.bounce.BounceMemberRule.testWithDuration(BounceMemberRule.java:239)
	at com.hazelcast.test.bounce.BounceMemberRule.testRepeatedly(BounceMemberRule.java:203)
	at com.hazelcast.concurrent.lock.LockLeaseMemberBounceTest.leaseShouldExpireWhenMemberBouncing(LockLeaseMemberBounceTest.java:84)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-nightly/com.hazelcast$hazelcast/1265/testReport/junit/com.hazelcast.concurrent.lock/LockLeaseMemberBounceTest/leaseShouldExpireWhenMemberBouncing/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at org.junit.Assert.assertFalse(Assert.java:74)
	at com.hazelcast.concurrent.lock.LockLeaseMemberBounceTest$Driver.doAssert(LockLeaseMemberBounceTest.java:132)
	at com.hazelcast.concurrent.lock.LockLeaseMemberBounceTest$1.run(LockLeaseMemberBounceTest.java:90)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1064)
	at com.hazelcast.concurrent.lock.LockLeaseMemberBounceTest.leaseShouldExpireWhenMemberBouncing(LockLeaseMemberBounceTest.java:86)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/1404/testReport/junit/com.hazelcast.concurrent.lock/LockLeaseMemberBounceTest/leaseShouldExpireWhenMemberBouncing/

**Comment by hasancelik** [comment]
*maintenance*
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
	at java.util.concurrent.FutureTask.awaitDone(FutureTask.java:425)
	at java.util.concurrent.FutureTask.get(FutureTask.java:187)
	at com.hazelcast.test.bounce.BounceMemberRule.waitForFutures(BounceMemberRule.java:375)
	at com.hazelcast.test.bounce.BounceMemberRule.testWithDuration(BounceMemberRule.java:239)
	at com.hazelcast.test.bounce.BounceMemberRule.testRepeatedly(BounceMemberRule.java:203)
	at com.hazelcast.concurrent.lock.LockLeaseMemberBounceTest.leaseShouldExpireWhenMemberBouncing(LockLeaseMemberBounceTest.java:84)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-nightly/com.hazelcast$hazelcast/1276/testReport/junit/com.hazelcast.concurrent.lock/LockLeaseMemberBounceTest/leaseShouldExpireWhenMemberBouncing/

**Comment by hasancelik** [comment]
*sonar*
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at org.junit.Assert.assertFalse(Assert.java:74)
	at com.hazelcast.concurrent.lock.LockLeaseMemberBounceTest$Driver.doAssert(LockLeaseMemberBounceTest.java:132)
	at com.hazelcast.concurrent.lock.LockLeaseMemberBounceTest$1.run(LockLeaseMemberBounceTest.java:90)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1064)
	at com.hazelcast.concurrent.lock.LockLeaseMemberBounceTest.leaseShouldExpireWhenMemberBouncing(LockLeaseMemberBounceTest.java:86)
```

https://hazelcast-l337.ci.cloudbees.com/view/Sonar/job/Hazelcast-3.x-sonar/com.hazelcast$hazelcast/1553/testReport/junit/com.hazelcast.concurrent.lock/LockLeaseMemberBounceTest/leaseShouldExpireWhenMemberBouncing/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at org.junit.Assert.assertFalse(Assert.java:74)
	at com.hazelcast.concurrent.lock.LockLeaseMemberBounceTest$Driver.doAssert(LockLeaseMemberBounceTest.java:132)
	at com.hazelcast.concurrent.lock.LockLeaseMemberBounceTest$1.run(LockLeaseMemberBounceTest.java:90)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1066)
	at com.hazelcast.concurrent.lock.LockLeaseMemberBounceTest.leaseShouldExpireWhenMemberBouncing(LockLeaseMemberBounceTest.java:86)
```

https://hazelcast-l337.ci.cloudbees.com/view/Sonar/job/Hazelcast-3.x-sonar/com.hazelcast$hazelcast/1559/testReport/junit/com.hazelcast.concurrent.lock/LockLeaseMemberBounceTest/leaseShouldExpireWhenMemberBouncing/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at org.junit.Assert.assertFalse(Assert.java:74)
	at com.hazelcast.concurrent.lock.LockLeaseMemberBounceTest$Driver.doAssert(LockLeaseMemberBounceTest.java:132)
	at com.hazelcast.concurrent.lock.LockLeaseMemberBounceTest$1.run(LockLeaseMemberBounceTest.java:90)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1066)
	at com.hazelcast.concurrent.lock.LockLeaseMemberBounceTest.leaseShouldExpireWhenMemberBouncing(LockLeaseMemberBounceTest.java:86)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/1414/testReport/junit/com.hazelcast.concurrent.lock/LockLeaseMemberBounceTest/leaseShouldExpireWhenMemberBouncing/

**Comment by hasancelik** [comment]
*maintenance*
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
	at java.util.concurrent.FutureTask.awaitDone(FutureTask.java:425)
	at java.util.concurrent.FutureTask.get(FutureTask.java:187)
	at com.hazelcast.test.bounce.BounceMemberRule.waitForFutures(BounceMemberRule.java:375)
	at com.hazelcast.test.bounce.BounceMemberRule.testWithDuration(BounceMemberRule.java:239)
	at com.hazelcast.test.bounce.BounceMemberRule.testRepeatedly(BounceMemberRule.java:203)
	at com.hazelcast.concurrent.lock.LockLeaseMemberBounceTest.leaseShouldExpireWhenMemberBouncing(LockLeaseMemberBounceTest.java:84)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-nightly/com.hazelcast$hazelcast/1289/testReport/junit/com.hazelcast.concurrent.lock/LockLeaseMemberBounceTest/leaseShouldExpireWhenMemberBouncing/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at org.junit.Assert.assertFalse(Assert.java:74)
	at com.hazelcast.concurrent.lock.LockLeaseMemberBounceTest$Driver.doAssert(LockLeaseMemberBounceTest.java:132)
	at com.hazelcast.concurrent.lock.LockLeaseMemberBounceTest$1.run(LockLeaseMemberBounceTest.java:90)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1066)
	at com.hazelcast.concurrent.lock.LockLeaseMemberBounceTest.leaseShouldExpireWhenMemberBouncing(LockLeaseMemberBounceTest.java:86)
```

https://hazelcast-l337.ci.cloudbees.com/view/Sonar/job/Hazelcast-3.x-sonar/com.hazelcast$hazelcast/1569/testReport/junit/com.hazelcast.concurrent.lock/LockLeaseMemberBounceTest/leaseShouldExpireWhenMemberBouncing/

**Comment by hasancelik** [comment]
*sonar*
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at org.junit.Assert.assertFalse(Assert.java:74)
	at com.hazelcast.concurrent.lock.LockLeaseMemberBounceTest$Driver.doAssert(LockLeaseMemberBounceTest.java:132)
	at com.hazelcast.concurrent.lock.LockLeaseMemberBounceTest$1.run(LockLeaseMemberBounceTest.java:90)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1066)
	at com.hazelcast.concurrent.lock.LockLeaseMemberBounceTest.leaseShouldExpireWhenMemberBouncing(LockLeaseMemberBounceTest.java:86)
```

https://hazelcast-l337.ci.cloudbees.com/view/Sonar/job/Hazelcast-3.x-sonar/com.hazelcast$hazelcast/1583/testReport/junit/com.hazelcast.concurrent.lock/LockLeaseMemberBounceTest/leaseShouldExpireWhenMemberBouncing/

**Comment by hasancelik** [comment]
*maintenance*
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at org.junit.Assert.assertFalse(Assert.java:74)
	at com.hazelcast.concurrent.lock.LockLeaseMemberBounceTest$Driver.doAssert(LockLeaseMemberBounceTest.java:132)
	at com.hazelcast.concurrent.lock.LockLeaseMemberBounceTest$1.run(LockLeaseMemberBounceTest.java:90)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:988)
	at com.hazelcast.concurrent.lock.LockLeaseMemberBounceTest.leaseShouldExpireWhenMemberBouncing(LockLeaseMemberBounceTest.java:86)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-nightly/com.hazelcast$hazelcast/1333/testReport/junit/com.hazelcast.concurrent.lock/LockLeaseMemberBounceTest/leaseShouldExpireWhenMemberBouncing/

**Comment by mdogan** [comment]
Fixed by https://github.com/hazelcast/hazelcast/pull/11301
