### ISSUE TITLE
NearCacheSerializationCountTest.testDeserializationCountWith_ObjectNearCache_invalidateLocalUpdatePolicy

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#9871]
```
java.lang.AssertionError: expected:<0> but was:<1>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.map.impl.nearcache.NearCacheSerializationCountTest.assertAndReset(NearCacheSerializationCountTest.java:140)
	at com.hazelcast.map.impl.nearcache.NearCacheSerializationCountTest.testDeserializationCountWith_ObjectNearCache_invalidateLocalUpdatePolicy(NearCacheSerializationCountTest.java:81)
```

https://hazelcast-l337.ci.cloudbees.com/view/Sonar/job/Hazelcast-3.x-sonar/com.hazelcast$hazelcast/1401/testReport/junit/com.hazelcast.map.impl.nearcache/NearCacheSerializationCountTest/testDeserializationCountWith_ObjectNearCache_invalidateLocalUpdatePolicy/

**Comment by ahmetmircik** [comment]
this was fixed before: https://github.com/hazelcast/hazelcast/commit/3e923c7470e6d65f36c7c616b4107c5b60e0c4ee
