### ISSUE TITLE
Lite member near cache clear issue in 3.7.2

### ISSUE THREAD

**Issue by sertugkaya** [hazelcast/hazelcast#9879]
In the case of using multiple lite members with near cache, when a clear is called it tries to use the same operation and results in:

 ```
Caused by: java.lang.IllegalStateException: An operation[com.hazelcast.map.impl.operation.ClearOperation{serviceName='hz:impl:mapService', identityHash=1083600, partitionId=-1, replicaIndex=0, callId=30, invocationTime=1486921301910 (2017-02-12 19:41:41.910), waitTimeout=-1, callTimeout=60000, name=SecurityDefinition}] can not be used for multiple invocations!

at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:220)

at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:207)

at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.invokeOnTarget(OperationServiceImpl.java:310)

at com.hazelcast.map.impl.proxy.MapProxySupport.runOnLiteMembers(MapProxySupport.java:923)

at com.hazelcast.map.impl.proxy.MapProxySupport.clearInternal(MapProxySupport.java:913)

at com.hazelcast.map.impl.proxy.MapProxyImpl.clearInternal(MapProxyImpl.java:82)

at com.hazelcast.map.impl.proxy.NearCachedMapProxyImpl.clearInternal(NearCachedMapProxyImpl.java:224)

at com.hazelcast.map.impl.proxy.MapProxyImpl.clear(MapProxyImpl.java:584)
```

This can be added to the test cases as well.

**Comment by ahmetmircik** [comment]
closed via https://github.com/hazelcast/hazelcast/pull/9885
