### ISSUE TITLE
[ZING] NearCacheTest.testNearCacheMaxIdleRecordsExpired

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#9881]
```
java.lang.AssertionError: we expected to have all map entries in the Near Cache or already expired (NearCacheStatsImpl{ownedEntryCount=44210, ownedEntryMemoryCost=7250440, creationTime=1486983933676, hits=0, misses=50000, ratio=0.0%, evictions=0, expirations=5789, lastPersistenceTime=0, persistenceCount=0, lastPersistenceDuration=0, lastPersistenceWrittenBytes=0, lastPersistenceKeyCount=0, lastPersistenceFailure=''})
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.map.impl.nearcache.NearCacheTestSupport.testNearCacheExpiration(NearCacheTestSupport.java:97)
	at com.hazelcast.map.impl.nearcache.NearCacheTest.testNearCacheMaxIdleRecordsExpired(NearCacheTest.java:911)
```

https://hazelcast-l337.ci.cloudbees.com/view/Zing/job/Hazelcast-3.x-ZingJDK7/69/testReport/junit/com.hazelcast.map.impl.nearcache/NearCacheTest/testNearCacheMaxIdleRecordsExpired_batchInvalidationEnabled_true_/

**Comment by hasancelik** [comment]
no recent failure. closing...
