### ISSUE TITLE
[WINDOWS] SystemLogPluginTest.testLifecycle

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#9893]
```
java.lang.AssertionError: '14-2-2017 09:40:55 ClusterVersionChanged[
                          3.9]
14-2-2017 09:40:55 Lifecycle[
                          SHUTTING_DOWN]
14-2-2017 09:40:55 Lifecycle[
                          SHUTDOWN]
' didn't contain expected 'Lifecycle[
                          SHUTTING_DOWN]'
	at org.junit.Assert.fail(Assert.java:88)
	at com.hazelcast.test.HazelcastTestSupport.assertContains(HazelcastTestSupport.java:689)
	at com.hazelcast.internal.diagnostics.AbstractDiagnosticsPluginTest.assertContains(AbstractDiagnosticsPluginTest.java:30)
	at com.hazelcast.internal.diagnostics.SystemLogPluginTest$1.run(SystemLogPluginTest.java:64)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:967)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:984)
	at com.hazelcast.internal.diagnostics.SystemLogPluginTest.testLifecycle(SystemLogPluginTest.java:59)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast-Windows/job/Hazelcast-3.x-Windows/com.hazelcast$hazelcast/11/testReport/junit/com.hazelcast.internal.diagnostics/SystemLogPluginTest/testLifecycle/

**Comment by Donnerbart** [comment]
Fixed via https://github.com/hazelcast/hazelcast/commit/a5f4d1cc78b10373a363ff88770c9ce58a9ed0f1
