### ISSUE TITLE
[WINDOWS] ExecuteScriptRequestTest.testExecuteScriptRequest_whenTargetAllMembers

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#9894]
```
org.junit.ComparisonFailure: expected:<error[
error
]
> but was:<error[
error]
>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.internal.management.ExecuteScriptRequestTest.testExecuteScriptRequest_whenTargetAllMembers(ExecuteScriptRequestTest.java:75)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast-Windows/job/Hazelcast-3.x-Windows/com.hazelcast$hazelcast/11/testReport/junit/com.hazelcast.internal.management/ExecuteScriptRequestTest/testExecuteScriptRequest_whenTargetAllMembers/

**Comment by Donnerbart** [comment]
Fixed via https://github.com/hazelcast/hazelcast/commit/f16bfdace7aa63cea45afaa807f9cac52d9c8b4f
