### ISSUE TITLE
[WINDOWS] DiscoverySpiTest.test_AbstractDiscoveryStrategy_getOrNull

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#9895]
```
java.lang.AssertionError: expected:<true> but was:<false>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.spi.discovery.DiscoverySpiTest.test_AbstractDiscoveryStrategy_getOrNull(DiscoverySpiTest.java:259)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast-Windows/job/Hazelcast-3.x-Windows/com.hazelcast$hazelcast/11/testReport/junit/com.hazelcast.spi.discovery/DiscoverySpiTest/test_AbstractDiscoveryStrategy_getOrNull/

**Comment by Donnerbart** [comment]
Fixed via https://github.com/hazelcast/hazelcast/commit/9f5328eb36f3b5372d7e62943b22552a3e78b7b8
