### ISSUE TITLE
[WINDOWS] XmlClientConfigImportVariableReplacementTest Failures

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#9896]
*testImportEmptyResourceContent
testThreeResourceCyclicImportThrowsException
testTwoResourceCyclicImportThrowsException*

```
java.lang.Exception: Unexpected exception, expected<com.hazelcast.config.InvalidConfigurationException> but was<com.hazelcast.core.HazelcastException>
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.Socket.connect(Socket.java:579)
	at java.net.Socket.connect(Socket.java:528)
	at sun.net.ftp.impl.FtpClient.doConnect(FtpClient.java:958)
	at sun.net.ftp.impl.FtpClient.tryConnect(FtpClient.java:918)
	at sun.net.ftp.impl.FtpClient.connect(FtpClient.java:1013)
	at sun.net.ftp.impl.FtpClient.connect(FtpClient.java:999)
	at sun.net.www.protocol.ftp.FtpURLConnection.connect(FtpURLConnection.java:294)
	at sun.net.www.protocol.ftp.FtpURLConnection.getInputStream(FtpURLConnection.java:393)
	at java.net.URL.openStream(URL.java:1041)
	at com.hazelcast.config.AbstractConfigBuilder.loadAndReplaceImportElement(AbstractConfigBuilder.java:115)
	at com.hazelcast.config.AbstractConfigBuilder.replaceImportElementsWithActualFileContents(AbstractConfigBuilder.java:100)
	at com.hazelcast.config.AbstractConfigBuilder.process(AbstractConfigBuilder.java:87)
	at com.hazelcast.client.config.XmlClientConfigBuilder.parseAndBuildConfig(XmlClientConfigBuilder.java:193)
	at com.hazelcast.client.config.XmlClientConfigBuilder.build(XmlClientConfigBuilder.java:174)
	at com.hazelcast.client.config.XmlClientConfigBuilder.build(XmlClientConfigBuilder.java:167)
	at com.hazelcast.client.config.XmlClientConfigBuilderTest.buildConfig(XmlClientConfigBuilderTest.java:363)
	at com.hazelcast.client.config.XmlClientConfigBuilderTest.buildConfig(XmlClientConfigBuilderTest.java:373)
	at com.hazelcast.client.config.XmlClientConfigImportVariableReplacementTest.testImportEmptyResourceContent(XmlClientConfigImportVariableReplacementTest.java:184)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast-Windows/job/Hazelcast-3.x-Windows/11/#showFailuresLink

**Comment by Donnerbart** [comment]
https://github.com/hazelcast/hazelcast/commit/669cc119ed28c138b10f3650f25d83d1dc3f3c63
