### ISSUE TITLE
TopicTest.testTopicGlobalOrder

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#9938]
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:226)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1037)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1326)
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:281)
	at com.hazelcast.topic.TopicTest.testTopicGlobalOrder(TopicTest.java:286)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-ZuluJDK6-freestyle/19/testReport/junit/com.hazelcast.topic/TopicTest/testTopicGlobalOrder/

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-ZuluJDK6-freestyle/21/testReport/com.hazelcast.topic/TopicTest/testTopicGlobalOrder/

**Comment by ahmetmircik** [comment]
Refactored failing topic tests: https://github.com/hazelcast/hazelcast/commit/85a05ead4d5f0ab52b49bddad0c0388fdf4e6c32

Lets wait for the next failure.
