### ISSUE TITLE
TopicTest.testTopicPublishingMember

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#9939]
```
java.lang.AssertionError: expected:<9> but was:<5>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.topic.TopicTest$3.run(TopicTest.java:145)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:967)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:984)
	at com.hazelcast.topic.TopicTest.testTopicPublishingMember(TopicTest.java:141)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-ZuluJDK6-freestyle/20/testReport/junit/com.hazelcast.topic/TopicTest/testTopicPublishingMember/

**Comment by ahmetmircik** [comment]
Refactored failing topic tests: https://github.com/hazelcast/hazelcast/commit/85a05ead4d5f0ab52b49bddad0c0388fdf4e6c32

Lets wait for the next failure.
