### ISSUE TITLE
ClientMapNearCacheTest.receives_one_clearEvent_after_mapClear_call_from_member

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#9940]
```
java.lang.AssertionError: Expecting only 1 clear event expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.client.map.impl.nearcache.ClientMapNearCacheTest$27.run(ClientMapNearCacheTest.java:993)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:967)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:984)
	at com.hazelcast.client.map.impl.nearcache.ClientMapNearCacheTest.receives_one_clearEvent_after_mapClear_call_from_member(ClientMapNearCacheTest.java:990)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-freestyle/20/testReport/junit/com.hazelcast.client.map.impl.nearcache/ClientMapNearCacheTest/receives_one_clearEvent_after_mapClear_call_from_member_batchInvalidationEnabled_true_/

**Comment by ahmetmircik** [comment]
Decreased max near cache size: in the test: https://github.com/hazelcast/hazelcast/commit/d573e716cc5ee615c83620f7ca99e71ecc532724

There seem high memory usage and system load is also high + full test logs are not available on s3 + not managed to reproduce failure.

Closing now, lets wait next failure.

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: Expecting only 1 clear event expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.client.map.impl.nearcache.ClientMapNearCacheTest$27.run(ClientMapNearCacheTest.java:993)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:967)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:984)
	at com.hazelcast.client.map.impl.nearcache.ClientMapNearCacheTest.receives_one_clearEvent_after_mapClear_call_from_member(ClientMapNearCacheTest.java:990)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK8/com.hazelcast$hazelcast-client/1100/testReport/junit/com.hazelcast.client.map.impl.nearcache/ClientMapNearCacheTest/receives_one_clearEvent_after_mapClear_call_from_member_batchInvalidationEnabled_true_/

**Comment by ahmetmircik** [comment]
Refactored test: https://github.com/hazelcast/hazelcast/commit/14cdc7b701ffca8370c01567535c4c705c6bef81

Lets wait next failure.

**Comment by Holmistr** [comment]
*maintenance*

Reopening as it failed on PR builder: https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/15465/testReport/junit/com.hazelcast.client.map.impl.nearcache/ClientMapNearCacheTest/receives_one_clearEvent_after_mapClear_call_from_member/

Stacktrace:
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:304)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:160)
	at com.hazelcast.client.spi.ClientProxy.invokeOnPartition(ClientProxy.java:225)
	at com.hazelcast.client.spi.ClientProxy.invoke(ClientProxy.java:219)
	at com.hazelcast.client.proxy.ClientMapProxy.putInternal(ClientMapProxy.java:518)
	at com.hazelcast.client.proxy.NearCachedClientMapProxy.putInternal(NearCachedClientMapProxy.java:281)
	at com.hazelcast.client.proxy.ClientMapProxy.put(ClientMapProxy.java:510)
	at com.hazelcast.client.proxy.ClientMapProxy.put(ClientMapProxy.java:313)
	at com.hazelcast.map.impl.nearcache.NearCacheTestSupport.populateMap(NearCacheTestSupport.java:244)
	at com.hazelcast.client.map.impl.nearcache.ClientMapNearCacheTest.mapClearFromMember(ClientMapNearCacheTest.java:981)
	at com.hazelcast.client.map.impl.nearcache.ClientMapNearCacheTest.receives_one_clearEvent_after_mapClear_call_from_member(ClientMapNearCacheTest.java:960)
```

Standard output:
```
Hiccups measured while running test 'receives_one_clearEvent_after_mapClear_call_from_member(com.hazelcast.client.map.impl.nearcache.ClientMapNearCacheTest):'
08:42:15, accumulated pauses: 1058 ms, max pause: 36 ms, pauses over 1000 ms: 0
08:42:20, accumulated pauses: 2302 ms, max pause: 149 ms, pauses over 1000 ms: 0
08:42:25, accumulated pauses: 3382 ms, max pause: 1799 ms, pauses over 1000 ms: 1
08:42:30, accumulated pauses: 4792 ms, max pause: 4295 ms, pauses over 1000 ms: 1
08:42:35, accumulated pauses: 1651 ms, max pause: 47 ms, pauses over 1000 ms: 0
08:42:40, accumulated pauses: 1794 ms, max pause: 97 ms, pauses over 1000 ms: 0
08:42:45, accumulated pauses: 2226 ms, max pause: 230 ms, pauses over 1000 ms: 0
08:42:50, accumulated pauses: 2336 ms, max pause: 352 ms, pauses over 1000 ms: 0
08:42:55, accumulated pauses: 3089 ms, max pause: 598 ms, pauses over 1000 ms: 0
08:43:00, accumulated pauses: 3042 ms, max pause: 232 ms, pauses over 1000 ms: 0
08:43:05, accumulated pauses: 3038 ms, max pause: 439 ms, pauses over 1000 ms: 0
08:43:10, accumulated pauses: 3641 ms, max pause: 668 ms, pauses over 1000 ms: 0
08:43:15, accumulated pauses: 7575 ms, max pause: 4983 ms, pauses over 1000 ms: 1
08:43:20, accumulated pauses: 1141 ms, max pause: 524 ms, pauses over 1000 ms: 0
08:43:25, accumulated pauses: 3130 ms, max pause: 478 ms, pauses over 1000 ms: 0
08:43:30, accumulated pauses: 1943 ms, max pause: 29 ms, pauses over 1000 ms: 0
08:43:35, accumulated pauses: 9411 ms, max pause: 6269 ms, pauses over 1000 ms: 2
08:43:40, accumulated pauses: 171 ms, max pause: 61 ms, pauses over 1000 ms: 0
08:43:45, accumulated pauses: 3767 ms, max pause: 929 ms, pauses over 1000 ms: 0
08:43:50, accumulated pauses: 2222 ms, max pause: 49 ms, pauses over 1000 ms: 0
08:43:55, accumulated pauses: 3831 ms, max pause: 1203 ms, pauses over 1000 ms: 1
08:44:00, accumulated pauses: 1804 ms, max pause: 198 ms, pauses over 1000 ms: 0
08:44:05, accumulated pauses: 3201 ms, max pause: 128 ms, pauses over 1000 ms: 0
08:44:10, accumulated pauses: 4181 ms, max pause: 2986 ms, pauses over 1000 ms: 1
08:44:15, accumulated pauses: 3557 ms, max pause: 720 ms, pauses over 1000 ms: 0
08:44:20, accumulated pauses: 2982 ms, max pause: 777 ms, pauses over 1000 ms: 0
08:44:25, accumulated pauses: 3267 ms, max pause: 1359 ms, pauses over 1000 ms: 1
08:44:30, accumulated pauses: 4478 ms, max pause: 1343 ms, pauses over 1000 ms: 1
08:44:35, accumulated pauses: 3641 ms, max pause: 2071 ms, pauses over 1000 ms: 1
08:44:40, accumulated pauses: 3730 ms, max pause: 800 ms, pauses over 1000 ms: 0
08:44:45, accumulated pauses: 4865 ms, max pause: 1486 ms, pauses over 1000 ms: 1
08:44:50, accumulated pauses: 1803 ms, max pause: 228 ms, pauses over 1000 ms: 0
08:44:55, accumulated pauses: 2644 ms, max pause: 159 ms, pauses over 1000 ms: 0
08:45:00, accumulated pauses: 2846 ms, max pause: 1022 ms, pauses over 1000 ms: 1
08:45:05, accumulated pauses: 3604 ms, max pause: 1123 ms, pauses over 1000 ms: 1
08:45:10, accumulated pauses: 3474 ms, max pause: 810 ms, pauses over 1000 ms: 0
08:45:15, accumulated pauses: 4712 ms, max pause: 2017 ms, pauses over 1000 ms: 1
08:45:20, accumulated pauses: 3753 ms, max pause: 1004 ms, pauses over 1000 ms: 1
08:45:25, accumulated pauses: 2298 ms, max pause: 93 ms, pauses over 1000 ms: 0
08:45:30, accumulated pauses: 2200 ms, max pause: 339 ms, pauses over 1000 ms: 0
08:45:35, accumulated pauses: 3436 ms, max pause: 637 ms, pauses over 1000 ms: 0
08:45:40, accumulated pauses: 3605 ms, max pause: 1530 ms, pauses over 1000 ms: 1
08:45:45, accumulated pauses: 3185 ms, max pause: 995 ms, pauses over 1000 ms: 0
08:45:50, accumulated pauses: 5458 ms, max pause: 2305 ms, pauses over 1000 ms: 1
08:45:55, accumulated pauses: 1175 ms, max pause: 212 ms, pauses over 1000 ms: 0
08:46:00, accumulated pauses: 4146 ms, max pause: 1516 ms, pauses over 1000 ms: 1
08:46:05, accumulated pauses: 3183 ms, max pause: 676 ms, pauses over 1000 ms: 0
08:46:10, accumulated pauses: 3958 ms, max pause: 879 ms, pauses over 1000 ms: 0
08:46:15, accumulated pauses: 2719 ms, max pause: 64 ms, pauses over 1000 ms: 0
08:46:20, accumulated pauses: 4511 ms, max pause: 868 ms, pauses over 1000 ms: 0
08:46:25, accumulated pauses: 3058 ms, max pause: 717 ms, pauses over 1000 ms: 0
08:46:30, accumulated pauses: 2931 ms, max pause: 958 ms, pauses over 1000 ms: 0
08:46:35, accumulated pauses: 3309 ms, max pause: 710 ms, pauses over 1000 ms: 0
08:46:40, accumulated pauses: 2620 ms, max pause: 1103 ms, pauses over 1000 ms: 1
08:46:45, accumulated pauses: 3359 ms, max pause: 1245 ms, pauses over 1000 ms: 1
08:46:50, accumulated pauses: 3559 ms, max pause: 660 ms, pauses over 1000 ms: 0
08:46:55, accumulated pauses: 7021 ms, max pause: 5178 ms, pauses over 1000 ms: 1
08:47:00, accumulated pauses: 846 ms, max pause: 208 ms, pauses over 1000 ms: 0
08:47:05, accumulated pauses: 2969 ms, max pause: 750 ms, pauses over 1000 ms: 0
08:47:10, accumulated pauses: 2498 ms, max pause: 804 ms, pauses over 1000 ms: 0
08:47:15, accumulated pauses: 3051 ms, max pause: 673 ms, pauses over 1000 ms: 0
08:47:20, accumulated pauses: 6690 ms, max pause: 4800 ms, pauses over 1000 ms: 1
08:47:25, accumulated pauses: 258 ms, max pause: 106 ms, pauses over 1000 ms: 0
08:47:30, accumulated pauses: 3782 ms, max pause: 1736 ms, pauses over 1000 ms: 1
08:47:35, accumulated pauses: 7379 ms, max pause: 4692 ms, pauses over 1000 ms: 1
08:47:40, accumulated pauses: 1805 ms, max pause: 554 ms, pauses over 1000 ms: 0
08:47:45, accumulated pauses: 2725 ms, max pause: 415 ms, pauses over 1000 ms: 0
08:47:50, accumulated pauses: 2882 ms, max pause: 524 ms, pauses over 1000 ms: 0
08:47:55, accumulated pauses: 3125 ms, max pause: 389 ms, pauses over 1000 ms: 0
08:48:00, accumulated pauses: 1541 ms, max pause: 276 ms, pauses over 1000 ms: 0
```
