### ISSUE TITLE
NPE at ReplicatedMapService.java:211

### ISSUE THREAD

**Issue by nikolayspb** [hazelcast/hazelcast#9957]
I see this warning at my service restart, while second node is still up.

```
java.lang.NullPointerException: null
    at com.hazelcast.replicatedmap.impl.ReplicatedMapService$ReplicationListener.onMessage(ReplicatedMapService.java:211)
    at com.hazelcast.replicatedmap.impl.ReplicatedMapService.dispatchEvent(ReplicatedMapService.java:146)
    at com.hazelcast.spi.impl.EventServiceImpl$EventPacketProcessor.process(EventServiceImpl.java:549)
    at com.hazelcast.spi.impl.EventServiceImpl$RemoteEventPacketProcessor.run(EventServiceImpl.java:630)
    at com.hazelcast.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:190)
    at com.hazelcast.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:174)
```

**Comment by jerrinot** [comment]
@nikolayspb: hi, what version of Hazelcast is it?

**Comment by metanet** [comment]
I think it is before 3.8. Closing this one
