### ISSUE TITLE
Hazelcast CPU load metrics on FreeBSD

### ISSUE THREAD

**Issue by evfool** [hazelcast/hazelcast#9961]
After deploying hazelcast inside an existing project, hazelcast logs warnings about not being able to get the cpuload.
Hazelcast version 3.8
OS is FreeBSD with OpenJDK 
openjdk version "1.7.0_111"
OpenJDK Runtime Environment (build 1.7.0_111-b01)
OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)

`Feb 22, 2017 10:05:21 AM com.hazelcast.internal.metrics.impl.MetricsRegistryImpl
WARNING: [172.31.240.236]:5701 [dev] [3.8] Failed to access probe:os.systemCpuLoad
java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor490.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.hazelcast.internal.metrics.metricsets.OperatingSystemMetricSet$3.get(OperatingSystemMetricSet.java:95)
	at com.hazelcast.internal.metrics.impl.DoubleGaugeImpl.read(DoubleGaugeImpl.java:55)
	at com.hazelcast.internal.diagnostics.HealthMonitor$HealthMetrics.exceedsThreshold(HealthMonitor.java:290)
	at com.hazelcast.internal.diagnostics.HealthMonitor$HealthMonitorThread.run(HealthMonitor.java:139)
Caused by: java.lang.UnsatisfiedLinkError: com.sun.management.UnixOperatingSystem.getSystemCpuLoad()D
	at com.sun.management.UnixOperatingSystem.getSystemCpuLoad(Native Method)
	... 7 more
`

**Comment by jerrinot** [comment]
hi @evfool,

thanks for reporting this. It smells like issues with FreeBSD build of OpenJDK. `UnsatisfiedLinkError`
it seems as the same issue as reported here https://github.com/hawtio/hawtio/issues/276

**Comment by ahmetmircik** [comment]
@evfool, as per my tests, issue is not happening with version `1.8.0_112`. Seems this is something missed to implement in version `1.7.0_111`. (Btw, i reproduced the same warning with `1.7.0_111`).

**Comment by jerrinot** [comment]
@ahmetmircik: did you also used FreeBSD? or was this on Linux?

**Comment by ahmetmircik** [comment]
it was with FreeBSD 11.

**Comment by jerrinot** [comment]
@ahmetmircik: thanks. then I'm going to close this issue as it's yet another indication it's the issue in the OpenJDK build.
