### ISSUE TITLE
BasicClientMapNearCacheTest.whenCacheIsFull_thenPutOnSameKeyShouldUpdateValue_withUpdateOnDataAdapter

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#9982]
```
java.lang.AssertionError: Near Cache hits should be 1, but were 0 (NearCacheStatsImpl{ownedEntryCount=500, ownedEntryMemoryCost=74463, creationTime=1488167129306, hits=0, misses=2201, ratio=0.0%, evictions=0, expirations=0, lastPersistenceTime=0, persistenceCount=0, lastPersistenceDuration=0, lastPersistenceWrittenBytes=0, lastPersistenceKeyCount=0, lastPersistenceFailure=''}) expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils.assertEqualsFormat(NearCacheTestUtils.java:154)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils.assertNearCacheStats(NearCacheTestUtils.java:143)
	at com.hazelcast.internal.nearcache.NearCacheTestUtils.assertNearCacheStats(NearCacheTestUtils.java:123)
	at com.hazelcast.internal.nearcache.AbstractBasicNearCacheTest$1.run(AbstractBasicNearCacheTest.java:167)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:967)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:984)
	at com.hazelcast.internal.nearcache.AbstractBasicNearCacheTest.whenCacheIsFull_thenPutOnSameKeyShouldUpdateValue_withUpdateOnDataAdapter(AbstractBasicNearCacheTest.java:158)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:95)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:89)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:81)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.lang.Thread.run(Thread.java:785)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.8/com.hazelcast$hazelcast-client/511/testReport/junit/com.hazelcast.client.map.impl.nearcache/BasicClientMapNearCacheTest/whenCacheIsFull_thenPutOnSameKeyShouldUpdateValue_withUpdateOnDataAdapter_format_BINARY_/

**Comment by Donnerbart** [comment]
Should be fixed via https://github.com/hazelcast/hazelcast/pull/10206
