### ISSUE TITLE
ClientScheduledExecutorServiceBasicTest.cancelledAndDone_durable

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#9984]
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.scheduledexecutor.ScheduledExecutorServiceBasicTest.cancelledAndDone_durable(ScheduledExecutorServiceBasicTest.java:529)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:89)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:81)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.lang.Thread.run(Thread.java:662)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-OracleJDK1.6-freestyle/10/testReport/junit/com.hazelcast.client.scheduledexecutor/ClientScheduledExecutorServiceBasicTest/cancelledAndDone_durable/

**Comment by tkountis** [comment]
@hasancelik I had a theory about this one, but was looking at the wrong place. Tried to access the logs but not available anymore, and it seems that there is not directory for this one on S3. Could you please update with a link if you have one, or if you see it again in the future.
